[techdebt]: [CDP-19974]: Exception Sanitizer in K8s and Helm swimlane
harness/harness-core pull request #29960
Opened 2022-01-17 04:28 UTC by namantalaycha10

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/29960)

2022-01-19 06:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=29960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=29960) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=29960) it.</sub>

2022-01-19 06:27 UTC, namantalaycha10 commented
/rebase

2022-01-19 07:29 UTC, namantalaycha10 commented
/rebase

2022-01-19 07:59 UTC, abosii-harness requested changes
> Reviewed 9 of 15 files at r1, 9 of 9 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/KubernetesSteadyStateCheckTask.java, line 60 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlGz1P1ZH4Lxpdyj2q:-MtlGz1P1ZH4Lxpdyj2r:b338drt) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/260-delegate/src/main/java/software/wings/delegatetasks/KubernetesSteadyStateCheckTask.java#L60)):*
> ```Java
>       BooleanSupplier preExecute) {
>     super(delegateTaskPackage, logStreamingTaskClient, consumer, preExecute);
>     SecretSanitizerThreadLocal.addAll(delegateTaskPackage.getSecrets());
> ```

nit: these tasks can be skipped in future, they are deprecated
___
*[260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java, line 95 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlH4QcEZ2Cz39gLBKY:-MtlH4QcEZ2Cz39gLBKZ:b-dni1fq) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java#L95)):*
> ```Java
>           .build();
>     } catch (Exception e) {
>       log.error("HelmValuesFetchTask execution failed with exception ", ExceptionMessageSanitizer.sanitizeException(e));
> ```

Let's use a temp variable for exception (ex: Exception sanitizedException = ...). It doesn't make sense to sanitize exception 3 times (It's actually the case when first call will change e and then it can be used with sanitizeException, but let's make it more clear)
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java, line 80 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHXyW82geMafk-b0K:-MtlHXyW82geMafk-b0L:bagl1ba) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L80)):*
> ```Java
>         log.error("Exception in processing K8s task [{}]",
>             k8sTaskParameters.getCommandName() + ":" + k8sTaskParameters.getCommandType(),
>             ExceptionMessageSanitizer.sanitizeException(ex));
> ```

Let's use a temp variable (ex: Exception sanitizedException = ...)
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java, line 123 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHc8s6Aa7mkvPkLNl:-MtlHc8s6Aa7mkvPkLNm:bagl1ba) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L123)):*
> ```Java
>         log.error("Exception in processing K8s task [{}]",
>             k8sTaskParameters.getCommandName() + ":" + k8sTaskParameters.getCommandType(),
>             ExceptionMessageSanitizer.sanitizeException(ex));
> ```

Let's use a temp variable (ex: Exception sanitizedException = ...)
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java, line 105 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHhUt-6uPTw4scqTp:-MtlHhUt-6uPTw4scqTq:bagl1ba) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L105)):*
> ```Java
>           errorMsg + "\n Overall deployment Failed", LogLevel.ERROR, CommandExecutionStatus.FAILURE);
>       log.error(format("Exception in processing helm task [%s]", helmCommandRequest.toString()),
>           ExceptionMessageSanitizer.sanitizeException(ex));
> ```

Let's use a temp variable (ex: Exception sanitizedException = ...)
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 143 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHjHt8RiwKoGdI2CT:-MtlHjHt8RiwKoGdI2CU:b9ifxjk) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L143)):*
> ```Java
>     if (isNotEmpty(helmChartConfigParams.getEncryptedDataDetails())) {
>       for (EncryptedDataDetail encryptedDataDetail : helmChartConfigParams.getEncryptedDataDetails()) {
>         secrets.add(String.valueOf(encryptionService.getDecryptedValue(encryptedDataDetail, false)));
> ```

Can we get the value from cache? (parameter false should be true) Not sure if this working properly, but let's try. It is totally worth of
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 155 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlI41oEWLXZBPj0El_:-MtlI41p9DZlI3KzV_Vh:bcd2v15) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L155)):*
> ```Java
>     if (isNotEmpty(helmChartConfigParams.getConnectorEncryptedDataDetails())) {
>       for (EncryptedDataDetail encryptedDataDetail : helmChartConfigParams.getConnectorEncryptedDataDetails()) {
>         secrets.add(String.valueOf(encryptionService.getDecryptedValue(encryptedDataDetail, false)));
> ```

Same, let's try to see if we can get value from cache
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 238 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlIY1UCJxBmVAqDONt:-MtlIY1V7g8ghYc7JQvV:bagl1ba) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L238)):*
> ```Java
>           } catch (Exception ex) {
>             String msg = format("Required values yaml file with path %s not found", filePath);
>             log.error(msg, ExceptionMessageSanitizer.sanitizeException(ex));
> ```

Let's use a temp variable (ex: Exception sanitizedException = ...)
___
*[400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java, line 321 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlIaeRDrZd9h4fYqQB:-MtlIaeRDrZd9h4fYqQC:b2mys9z) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L321)):*
> ```Java
>       if (isNotEmpty(delegateManifestConfig.getEncryptedDataDetails())) {
>         for (EncryptedDataDetail encryptedDataDetail : delegateManifestConfig.getEncryptedDataDetails()) {
>           secrets.add(String.valueOf(encryptionService.getDecryptedValue(encryptedDataDetail, false)));
> ```

Let's try to get value from cache
___
*[400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java, line 629 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlIjTo5taKCiv4gL6P:-MtlIjTo5taKCiv4gL6Q:bagl1ba) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L629)):*
> ```Java
>     } catch (Exception e) {
>       log.error(
>           "Helm chart rollback failed [{}]", commandRequest.toString(), ExceptionMessageSanitizer.sanitizeException(e));
> ```

Let's use a temp variable (ex: Exception sanitizedException = ...)
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/taskHandlers/GcpListBucketsTaskHandler.java, line 67 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlItYd6B9NrOL61cXN:-MtlItYd6B9NrOL61cXO:bsat28x) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/ta [...]

2022-01-19 17:18 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 25 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java, line 95 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlH4QcEZ2Cz39gLBKY:-MtnKiY8B87tWG_-Qbly:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java#L95)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable for exception (ex: Exception sanitizedException = ...). It doesn't make sense to sanitize exception 3 times (It's actually the case when first call will change e and then it can be used with sanitizeException, but let's make it more clear)
</blockquote></details>

Done.
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java, line 80 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHXyW82geMafk-b0K:-MtnKjo6Chb9kH1Yoq7N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L80)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java, line 123 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHc8s6Aa7mkvPkLNl:-MtnKkmgCUMC56HSDIPQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L123)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java, line 105 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHhUt-6uPTw4scqTp:-MtnKlsdAauvufC-3Iez:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L105)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 238 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlIY1UCJxBmVAqDONt:-MtnKoGn5-bKCp426idH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L238)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java, line 629 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlIjTo5taKCiv4gL6P:-MtnKplu8858vk8OSucW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L629)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/taskHandlers/GcpListBucketsTaskHandler.java, line 67 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlItYd6B9NrOL61cXN:-MtnKuU1BSD4AnpfuqTK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/taskHandlers/GcpListBucketsTaskHandler.java#L67)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Any reasons why we need to use this logic? Can't we sanitize with the new logic?
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java, line 250 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlJ7wkE5RQDvTAeS-a:-MtnKw2_9cyVFznWrOFm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L250)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java, line 136 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlJnRY6j21T-sf0oMo:-MtnL-fGEh5SCMcc5gjc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java#L136)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we use instead SecretSanitizerThreadLocal.addAll(Collections.singleton(String.valueOf(gcpCredentialSpecDTO.getSecretKeyRef().getDecryptedValue())) ?
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 2413 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlK1a_AUKOr3bAWKiI:-MtnL0Vg25KQefpjvomi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2413)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskNG.java, line 83 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlK70T2skNNuIne2Qj:-MtnL2Tg8ljVzop_6nbc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskNG.java#L83)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's rethrow a wings exception. Please check what the one that is more favorable 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskNG.java, line 144 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlKcVB0PIkshCYrjrw:-MtnL3PLDpdUFXd0v0_9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskNG.java#L144)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's use a temp variable (ex: Exception sanitizedException = ...)
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/software/wings/delegatetasks/ExceptionMessageSanitizer.java, line 27 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlKf6t7QDf-FhFdn4S:-MtnL4dzDN7Vk8Md5INc:b-896fix) ([raw file](https:// [...]

2022-01-20 01:38 UTC, yogesh-chauhan requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 25 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 143 at r1](https://reviewable.io/reviews/harness/harness-core/29960#-MtdPAlUBiRDF9PciDD1:-MtdPAlb7gdWy5iI9GP3:b-p3l8k1) ([raw file](https://github.com/harness/harness-core/blob/5d688fe2ab2b2ef7631a5219f9900d4afa91484b/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L143)):*
> ```Java
>     if (isNotEmpty(helmChartConfigParams.getEncryptedDataDetails())) {
>       for (EncryptedDataDetail encryptedDataDetail : helmChartConfigParams.getEncryptedDataDetails()) {
>         secrets.add(String.valueOf(encryptionService.getDecryptedValue(encryptedDataDetail, false)));
> ```

Do we need to decrypt again ?
___
*[980-commons/src/main/java/io/harness/secret/SecretSanitizerThreadLocal.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/29960#-MtdRu5TBus2DTE7fZ4f:-MtdRu5TBus2DTE7fZ4g:bvbg4u3) ([raw file](https://github.com/harness/harness-core/blob/5d688fe2ab2b2ef7631a5219f9900d4afa91484b/980-commons/src/main/java/io/harness/secret/SecretSanitizerThreadLocal.java#L16)):*
> ```Java
> @UtilityClass
> public class SecretSanitizerThreadLocal {
>   public static final ThreadLocal<Set<String>> triggeredByThreadLocal = new ThreadLocal<>();
> ```

lets change the name. Its copied from somewhere and does not make sense. Could be SecretsThreadLocal



_Code quote:_
```Java
triggeredByThreadLocal
```


<!-- Sent from Reviewable.io -->

2022-01-20 01:57 UTC, yogesh-chauhan requested changes
> Reviewed 2 of 15 files at r1, 1 of 9 files at r2, 8 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 22 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/29960#-MtpBqeyEafpiMSg4BnZ:-MtpBqeyEafpiMSg4Bn_:b-59gqbx) (no related file):*
@namantalaycha10 Have we increased the number of times we decrypt on delegate,  in this PR or is that a constant ?

---


<!-- Sent from Reviewable.io -->

2022-01-20 18:34 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 30 file(s) to review. 2 change requests. 19. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/29960#-MtpBqeyEafpiMSg4BnZ:-Mtskf7t7J8omsHQM0Ep:brtcm7a) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

@namantalaycha10 Have we increased the number of times we decrypt on delegate,  in this PR or is that a constant ?
</blockquote></details>

@yogesh-chauhan commit the new changes , now no. of decrypt is same as before

---
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 143 at r1](https://reviewable.io/reviews/harness/harness-core/29960#-MtdPAlUBiRDF9PciDD1:-Mtskqjh2lp1h9BXLxtj:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5d688fe2ab2b2ef7631a5219f9900d4afa91484b/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L143)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Do we need to decrypt again ?
</blockquote></details>

done
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 143 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlHjHt8RiwKoGdI2CT:-MtskwOq83cDlzEiPTJo:b-xie08v) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L143)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we get the value from cache? (parameter false should be true) Not sure if this working properly, but let's try. It is totally worth of
</blockquote></details>

no need as discussed
___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 155 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlI41oEWLXZBPj0El_:-MtskzAv6PO3Cs60dGDb:b-xie08v) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L155)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same, let's try to see if we can get value from cache
</blockquote></details>

no need as discussed
___
*[400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java, line 321 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlIaeRDrZd9h4fYqQB:-Mtsl0ma9JGsI2X6g1Ro:b-xie08v) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L321)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's try to get value from cache
</blockquote></details>

no need as discussed
___
*[980-commons/src/main/java/io/harness/secret/SecretSanitizerThreadLocal.java, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/29960#-MtdRu5TBus2DTE7fZ4f:-Mtsl3sC3kHSJgz1F1e1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5d688fe2ab2b2ef7631a5219f9900d4afa91484b/980-commons/src/main/java/io/harness/secret/SecretSanitizerThreadLocal.java#L16)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets change the name. Its copied from somewhere and does not make sense. Could be SecretsThreadLocal
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-01-21 07:30 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 15 files at r1, 2 of 18 files at r5, 16 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 28 file(s) to review. 2 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/software/wings/delegatetasks/ExceptionMessageSanitizer.java, line 100 at r7](https://reviewable.io/reviews/harness/harness-core/29960#-MtvXdAi6CZMSiuP8vys:-MtvXdAi6CZMSiuP8vyt:bqiaopv) ([raw file](https://github.com/harness/harness-core/blob/a7d63f3b1446e3f465384047aef7b79d46f7245c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/ExceptionMessageSanitizer.java#L100)):*
> ```Java
>         f.setAccessible(false);
>       } catch (IllegalAccessException ex) {
>         throw new EncryptDecryptException("Failed to store the Secrets for sanitize", ex);
> ```

Maybe we can log and not re-throw


<!-- Sent from Reviewable.io -->

2022-01-21 07:30 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 19 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 28 file(s) to review. 1 change requests. 17. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-01-21 07:48 UTC, abosii-harness approved these changes
> Reviewed 9 of 18 files at r5, 19 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-01-24 11:05 UTC, abosii-harness approved these changes
> Reviewed 35 of 35 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 35 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-01-24 18:59 UTC, yogesh-chauhan reviewed
> Reviewed 32 of 35 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 3 file(s) to review. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java, line 136 at r4](https://reviewable.io/reviews/harness/harness-core/29960#-MtlJnRY6j21T-sf0oMo:-MuCS3bs7SqYpsar_vn-:bq212wv) ([raw file](https://github.com/harness/harness-core/blob/02ab61a5423f42eb33b24aae7fac16f8632f6a7c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/ContainerDeploymentDelegateBaseHelper.java#L136)):*
<details><summary><i>Previously, namantalaycha10 (Naman Talaycha) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

dont we need this ?


<!-- Sent from Reviewable.io -->

2022-01-24 19:04 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-01-24 19:05 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 35 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29960)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-01-25 05:45 UTC, merged