feat: [CDS-16399]: Rancher backend changes
harness/harness-core pull request #30009
Opened 2022-01-17 12:44 UTC by sainath-b

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30009)

2022-01-19 03:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30009) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30009) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30009) it.</sub>

2022-01-19 10:28 UTC, sainath-b commented
trigger feature-build

2022-01-19 18:42 UTC, sainath-b commented
trigger feature-build

2022-01-20 03:28 UTC, sainath-b commented
trigger feature-build

2022-01-20 09:55 UTC, sainath-b commented
trigger feature-build

2022-01-20 11:31 UTC, sainath-b commented
trigger feature-build

2022-01-20 17:23 UTC, sainath-b commented
trigger feature-build

2022-01-23 14:08 UTC, sainath-b commented
trigger feature-build

2022-01-25 06:27 UTC, shubham-in10se commented on 400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java
> +    }
localise this for only the rancher canary state

2022-01-27 02:19 UTC, sainath-b commented
trigger feature-build

2022-01-27 05:39 UTC, sainath-b commented
trigger feature-build

2022-01-27 11:02 UTC, sainath-b commented
trigger feature-build

2022-01-30 06:52 UTC, yogesh-chauhan reviewed
> Reviewed 15 of 65 files at r1, 1 of 12 files at r2, 2 of 18 files at r7, 1 of 1 files at r10, 5 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-01-30 08:53 UTC, yogesh-chauhan requested changes
> Reviewed 4 of 65 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/RancherConfig.java, line 50 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmBgI1H5CTdLs-olK:-MudmBgI1H5CTdLs-olL:bdbw7sg) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherConfig.java#L50)):*
> ```Java
> public class RancherConfig extends SettingValue implements EncryptableSetting {
>   @Attributes(title = "Rancher URL") private String rancherUrl;
>   @Attributes(title = "Bearer Token") @Encrypted(fieldName = "bearer_token") private char[] bearerToken;
> ```

is this, the actual bearer token or the id to the secret containing bearer token ?
___
*[400-rest/src/main/java/software/wings/beans/RancherConfig.java, line 52 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudlUZL8JXmchGAffDP:-MudlUZL8JXmchGAffDQ:b3c89ho) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherConfig.java#L52)):*
> ```Java
>   @Attributes(title = "Bearer Token") @Encrypted(fieldName = "bearer_token") private char[] bearerToken;
>   @JsonView(JsonViews.Internal.class) @SchemaIgnore private String encryptedBearerToken;
>   @SchemaIgnore @NotEmpty private String accountId; // internal
> ```

SettingAttribute already has accountId. The settingValues ideally should only have connector specific data
___
*[400-rest/src/main/java/software/wings/beans/RancherConfig.java, line 87 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmK3c4Fdmj_pxxWY7:-MudmK3c4Fdmj_pxxWY8:b-xnr76a) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherConfig.java#L87)):*
> ```Java
>   public static final class Yaml extends CloudProviderYaml {
>     private String rancherUrl;
>     private String bearerToken;
> ```

is this, the actual bearertoken or the id to the secret containing bearer token ?
___
*[400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java, line 86 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmkngEuYW-MG6DD47:-MudmkngEuYW-MG6DD48:b-fi17lk) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java#L86)):*
> ```Java
>   }
> 
>   public static final class Builder {
> ```

We do not need to write all this boiler plate now. Lets use Builder annotation
___
*[400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java, line 259 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmvLpDM_MGL90SZyE:-MudmvLpDM_MGL90SZyF:bgf6ydw) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java#L259)):*
> ```Java
>   @NoArgsConstructor
>   @EqualsAndHashCode(callSuper = true)
>   public static class Yaml extends YamlWithComputeProvider {
> ```

This need not have a YAML. InfraMappings are now an Internal entity and do not need yaml decoder/encoders
___
*[400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java, line 89 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudqE7bCQFNy8t3toUS:-MudqE7bCQFNy8t3toUT:b3x99k3) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java#L89)):*
> ```Java
>   }
> 
>   public List<RancherClusterElement> list() {
> ```

nit :can be private ?
___
*[400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java, line 112 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mudr02xBYEQxzChzykl:-Mudr02xBYEQxzChzykm:b-woph8q) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java#L112)):*
> ```Java
> 
>     public static String getSweepingOutputID(ExecutionContext context) {
>       return SWEEPING_OUTPUT_NAME + context.getWorkflowExecutionId().trim();
> ```

are we keeping sweeping output at workflow scope ? 
We need to think about multi phase workflows like K8s Canary Workflow. In this case, do we store sweeping output, just once?
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherClusterDataResponse.java, line 20 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mudz-LFE4BJRc8lgU-1:-Mudz-LFE4BJRc8lgU-2:b-ysivdm) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherClusterDataResponse.java#L20)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class RancherClusterDataResponse {
>   String resourceType;
> ```

nit: fields should be private
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java, line 50 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudzvlQ1FG-nByU6WsC:-MudzvlQ1FG-nByU6WsD:b-a4ieqb) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java#L50)):*
> ```Java
> @OwnedBy(CDP)
> @TargetModule(HarnessModule._930_DELEGATE_TASKS)
> public class RancherResolveClustersTask extends AbstractDelegateRunnableTask {
> ```

can this be moved to 260-delegate ?
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java, line 116 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue1sQU7qe9Xj0H9rAT:-Mue1sQY4R46Fr5869te:b-y1q7xn) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java#L116)):*
> ```Java
>   private List<String> filterClustersForCriteria(
>       final RancherClusterDataResponse rancherClusterData, final Map<String, Set<String>> selectionParams) {
>     if (MapUtils.isEmpty(selectionParams)) {
> ```

nit:  we can use  io.harness.data.structure.EmptyPredicate.isEmpty(selectionParams) 
also in general, we can use the above in place of apache libraries
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java, line 51 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue-N2M34Fbo6V_xXlW:-Mue-N2M34Fbo6V_xXlX:btbi1kl) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L51)):*
> ```Java
> @TargetModule(HarnessModule._930_DELEGATE_TASKS)
> @OwnedBy(CDP)
> public class RancherTaskHelper {
> ```

Lets see if we can move this to lower modules like 930-delegate-tasks 
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java, line 92 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue6t3NAc6oGr3G2adn:-Mue6t3R6ApKXfS1U55L:bmoi8e2) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L92)):*
> ```Java
>                                    .socketTimeoutMillis(10000)
>                                    .url(urlBuffer.toString())
>                                    // TODO: Check if useProxy field need to be added in Rancher cloud provider
> ```

Lets discuss more on this. Some  [...]

2022-01-30 09:07 UTC, yogesh-chauhan requested changes
> Reviewed 2 of 65 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/DelegateRunnableTask.java, line 17 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueEEtb1jG7iX6zPTmq:-MueEEteBNPb4ZMYq5ul:b-l2d77f) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/930-delegate-tasks/src/main/java/io/harness/delegate/task/DelegateRunnableTask.java#L17)):*
> ```Java
> public interface DelegateRunnableTask extends Runnable {
>   @Deprecated DelegateResponseData run(Object[] parameters);
>   DelegateResponseData run(TaskParameters parameters) throws IOException, JoseException;
> ```

is this intentional ?


<!-- Sent from Reviewable.io -->

2022-01-30 10:37 UTC, yogesh-chauhan requested changes
> Reviewed 3 of 65 files at r1, 1 of 4 files at r3, 1 of 18 files at r7, 1 of 7 files at r11, 1 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sVersionTaskHandler.java, line 56 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MuePb2P8Yk1hrh23Tn1:-MuePb2Q29UBiJzX5zIC:b-vpa04z) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sVersionTaskHandler.java#L56)):*
> ```Java
>     K8sVersionResponse k8sVersionResponse = k8sVersionResponseBuilder(versionInfo);
> 
>     boolean isCloudCostEnabled = Objects.nonNull(kubernetesClusterConfig)
> ```

nit: Objects.nonNull looks too verbose for a null check. 



_Code quote:_
```Java
Objects.nonNull(kubernetesClusterConfig)
```
___
*[400-rest/src/main/java/software/wings/helpers/ext/container/ContainerDeploymentManagerHelper.java, line 160 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueUphsDKpgqEmVs1Qh:-MueUphtClBHXHHFemIX:b-6nzha7) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/helpers/ext/container/ContainerDeploymentManagerHelper.java#L160)):*
> ```Java
>       namespace = rancherInfra.getNamespace();
> 
>       RancherClusterElement element = context.getContextElement();
> ```

are we sure that this is always of type ```RancherClusterElement``` ?
___
*[400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java, line 41 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueVw3X5xrMRYPatAJz:-MueVw3X5xrMRYPatAK-:bf9u1) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java#L41)):*
> ```Java
>     implements InfraMappingInfrastructureProvider, KubernetesInfrastructure, FieldKeyValMapProvider {
>   private String cloudProviderId;
>   @IncludeFieldMap private String clusterName; // todo: why cluster name field is here.?
> ```

Is this needed here ?
___
*[400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java, line 89 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueW1DY2Eye6AEBuyxD:-MueW1DY2Eye6AEBuyxE:bf9u1) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java#L89)):*
> ```Java
>   public static final class Yaml extends CloudProviderInfrastructureYaml {
>     private String cloudProviderName;
>     private String clusterName;
> ```

Is this needed here ?


<!-- Sent from Reviewable.io -->

2022-01-31 08:42 UTC, yogesh-chauhan requested changes
> Reviewed 8 of 65 files at r1, 3 of 12 files at r2, 1 of 18 files at r7, 1 of 4 files at r8, 2 of 7 files at r11, 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: Some of the checks are too old. 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/infrastructuredefinition/InfrastructureDefinitionServiceImpl.java, line 579 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MujG2Fg0K0Lpm78fiH4:-MujG2Fg0K0Lpm78fiH5:bx4xwi7) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/infrastructuredefinition/InfrastructureDefinitionServiceImpl.java#L579)):*
> ```Java
>   public void validateAndPrepareInfraDefinition(@Valid InfrastructureDefinition infraDefinition) {
>     validateCloudProviderAndDeploymentType(infraDefinition.getCloudProviderType(), infraDefinition.getDeploymentType());
>     SettingAttribute settingAttribute = settingsService.getByAccountAndId(
> ```

this is unused


<!-- Sent from Reviewable.io -->

2022-02-03 19:51 UTC, yogesh-chauhan requested changes
> Reviewed 6 of 65 files at r1, 2 of 12 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, 4 of 18 files at r7, 2 of 4 files at r8, 3 of 7 files at r11, 2 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: Some of the checks are too old. 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java, line 61 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv01tMO53oy8PKBvyeu:-Mv01tMP4-2mCRK_B6y3:brwuvg9) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java#L61)):*
> ```Java
>     headers.add(KeyValuePair.builder()
>                     .key(HttpHeaders.AUTHORIZATION)
>                     .value("Bearer ${secretManager.obtain(\"" + rancherBearerTokenSecretEncryptedData.getName() + "\", "
> ```

did we not try with the usual expression i.e ${secrets.getValue(..)} ? I think we discussed it but I kind of do not remember now. The reason I say this is because, secretManager.obtain is an internal implementation detail that is subject to future changes but ${secrets.getValue(..)} cannot change because that is a user facing expression 
we will need to call the below code
```
private void renderTaskParameters(ExecutionContext context, StateExecutionData stateExecutionData,
      TaskParameters parameters, int expressionFunctorToken) {
    context.resetPreparedCache();
    ExpressionReflectionUtils.applyExpression(parameters,
        (secretMode, value)
            -> context.renderExpression(value,
                StateExecutionContext.builder()
                    .stateExecutionData(stateExecutionData)
                    .adoptDelegateDecryption(true)
                    .expressionFunctorToken(expressionFunctorToken)
                    .build()));
  }
```
___
*[400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java, line 105 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv05pTHBemw7VCGtJvu:-Mv05pTLC51pbRSDtOki:bxauwjn) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java#L105)):*
> ```Java
>         errorMessage = delegateResponseData.getErrorMessage();
>       } else {
>         Map<String, Object> httpResponseBody = JsonUtil.parseJson(delegateResponseData.getHttpResponseBody());
> ```

we should avoid this json from jose package. Better to use the one from io.harness.serializer package
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/inframapping/RancherKubernetesInfraMappingYamlHandler.java, line 31 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv06P0z92A0uY-Ad4m4:-Mv06P0z92A0uY-Ad4m5:bhtzbll) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/yaml/handler/inframapping/RancherKubernetesInfraMappingYamlHandler.java#L31)):*
> ```Java
> @OwnedBy(CDP)
> @TargetModule(_955_CG_YAML)
> public class RancherKubernetesInfraMappingYamlHandler
> ```

nit: we can get rid of this. InfraMappings are no longer user facing entities.
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/cloudprovider/RancherConfigYamlHandler.java, line 40 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv06jXr9HrnhWx9ZSU7:-Mv06jXr9HrnhWx9ZSU8:bs95kfq) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/cloudprovider/RancherConfigYamlHandler.java#L40)):*
> ```Java
>   protected SettingAttribute toBean(SettingAttribute previous, ChangeContext<RancherConfig.Yaml> changeContext,
>       List<ChangeContext> changeSetContext) throws HarnessException {
>     Optional<SettingAttribute> optionalPrevious = Optional.ofNullable(previous);
> ```

nit:I dont think we need an optional here. We can just check for previous != null 
___
*[400-rest/src/main/java/software/wings/sm/StepType.java, line 533 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv07Nah14NGcLu4jrVx:-Mv07Nah14NGcLu4jrVy:biu7ug9) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/StepType.java#L533)):*
> ```Java
>   RANCHER_K8S_DEPLOYMENT_ROLLING(RancherK8sRollingDeploy.class, WorkflowConstants.RANCHER_K8S_DEPLOYMENT_ROLLING,
>       asList(KUBERNETES), asList(K8S_PHASE_STEP), Lists.newArrayList(DeploymentType.KUBERNETES),
>       asList(PhaseType.NON_ROLLBACK), asList(ROLLING, CANARY)),
> ```

RANCHER_K8S_DEPLOYMENT_ROLLING should have MULTI_SERVICE as well 
___
*[400-rest/src/main/java/software/wings/sm/StepType.java, line 540 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv07VfKAJOsUnAe905n:-Mv07VfKAJOsUnAe905o:b-v7ytyc) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/StepType.java#L540)):*
> ```Java
>       asList(KUBERNETES), asList(K8S_PHASE_STEP), Lists.newArrayList(DeploymentType.KUBERNETES),
>       asList(PhaseType.NON_ROLLBACK), asList(BLUE_GREEN)),
>   RANCHER_KUBERNETES_SWAP_SERVICE_SELECTORS(RancherKubernetesSwapServiceSelectors.class,
> ```

RANCHER_KUBERNETES_SWAP_SERVICE_SELECTORS should have MULTI_SERVICE as well 
___
*[400-rest/src/main/java/software/wings/sm/StepType.java, line 547 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv07dFZ2rFn001aPUro:-Mv07dF_Ah70gK4FlQEP:bdxs93u) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/StepType.java#L547)):*
> ```Java
>   RANCHER_K8S_DELETE(RancherK8sDelete.class, WorkflowConstants.RANCHER_K8S_DELETE, asList(KUBERNETES),
>       asList(K8S_PHASE_STEP, WRAP_UP), Lists.newArrayList(DeploymentType.KUBERNETES),
>       asList(PhaseType.NON_ROLLBACK, PhaseType.ROLLBACK), asList(ROLLING, CANARY, BLUE_GREEN)),
> ```

should have multi service as well


<!-- Sent from Reviewable.io -->

2022-02-04 12:59 UTC, inderschera reviewed
> Reviewed 4 of 65 files at r1, 3 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: Some of the checks are too old. 80 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java, line 47 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv3TWvR9FzE9ZQGJgr2:-Mv3TWvS3mAP4_g0xzvz:bfg6ho) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java#L47)):*
> ```Java
> 
>   private static final String EXPRESSION_START_PATTERN = "rancherClusters()";
>   private static final String INSTANCE_EXPR_PROCESSOR = "rancherK8sClusterProcessor";
> ```

nit: change name to RANCHER_EXPR_PROCESSOR
___
*[400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java, line 89 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudqE7bCQFNy8t3toUS:-Mv3avHlDecppFRTnJb8:b-28fmfm) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java#L89)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit :can be private ?
</blockquote></details>

No Yogesh. This is used for expression rendering. Should be public.
___
*[400-rest/src/main/java/software/wings/sm/ExecutionContextImpl.java, line 1017 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv3nRdo0O5e_H-81UV4:-Mv3nRdo0O5e_H-81UV5:b-2vwd7f) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/ExecutionContextImpl.java#L1017)):*
> ```Java
> 
>     contextMap.put(RancherK8sClusterProcessor.FILTERED_CLUSTERS_EXPR_PREFIX,
>         expressionProcessorFactory.getExpressionProcessor(RancherK8sClusterProcessor.EXPRESSION_EQUAL_PATTERN, this));
> ```

Is this required? If rancher expression is only being used to add repeat state, it would be handle by framework and we don't need to add it here.


<!-- Sent from Reviewable.io -->

2022-02-04 19:04 UTC, yogesh-chauhan requested changes
> Reviewed 3 of 65 files at r1, 1 of 18 files at r7, 1 of 1 files at r14, 4 of 21 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/rancher/RancherResolveState.java, line 83 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv08g6J1BG1N0UZoXpK:-Mv08g6J1BG1N0UZoXpL:bmflvej) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/states/rancher/RancherResolveState.java#L83)):*
> ```Java
> @BreakDependencyOn("software.wings.service.intfc.DelegateService")
> public class RancherResolveState extends State {
>   @Inject public RancherStateHelper rancherStateHelper;
> ```

can be private
___
*[400-rest/src/main/java/software/wings/sm/states/rancher/RancherResolveState.java, line 84 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv08nhg0gtdGwzYo3Dz:-Mv08nhg0gtdGwzYo3E-:b-dvw61q) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/states/rancher/RancherResolveState.java#L84)):*
> ```Java
> public class RancherResolveState extends State {
>   @Inject public RancherStateHelper rancherStateHelper;
>   @Inject @Transient private SweepingOutputService sweepingOutputService;
> ```

I dont think we need transient annotation.  I checked in few other calls
___
*[400-rest/src/main/java/software/wings/sm/states/rancher/RancherStateExecutionData.java, line 50 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv08MG86onJ8pRmgCiC:-Mv08MG94QZL4m8mIRf2:by1dyj4) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/states/rancher/RancherStateExecutionData.java#L50)):*
> ```Java
>     Map<String, ExecutionDataValue> executionDetails = super.getExecutionDetails();
>     putNotNull(executionDetails, "activityId",
>         ExecutionDataValue.builder().value(activityId).displayName("Activity Id").build());
> ```

I think we should more details into this. Please check software.wings.api.k8s.K8sStateExecutionData for examples


<!-- Sent from Reviewable.io -->

2022-02-05 02:33 UTC, sainath-b reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/RancherConfig.java, line 50 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmBgI1H5CTdLs-olK:-Mv6ZEg3C8upizzVqVrx:b-d7vjem) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherConfig.java#L50)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this, the actual bearer token or the id to the secret containing bearer token ?
</blockquote></details>

bearerToken is to store actual secret and encrypted bearer token is reference. But we are making sure we are not exposing secret in Yaml.
___
*[400-rest/src/main/java/software/wings/beans/RancherConfig.java, line 52 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudlUZL8JXmchGAffDP:-Mv6ZcFK9Pz3riTAz9ff:b-rm08tc) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherConfig.java#L52)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

SettingAttribute already has accountId. The settingValues ideally should only have connector specific data
</blockquote></details>

This is needed for setting values inheriting encrypted setting
___
*[400-rest/src/main/java/software/wings/beans/RancherConfig.java, line 87 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmK3c4Fdmj_pxxWY7:-Mv6Zz2j7kGP85G3cy7q:b-d7vjem) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherConfig.java#L87)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this, the actual bearertoken or the id to the secret containing bearer token ?
</blockquote></details>

bearerToken is to store actual secret and encrypted bearer token is reference. But we are making sure we are not exposing secret in Yaml.
___
*[400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java, line 86 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmkngEuYW-MG6DD47:-Mv6Zx8E1KjYnS93EC89:b87ihgz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java#L86)):*
> Cannot remove this now as Builder annotation need to be added in parent class there are other child classes for this parent call where Builder boilerplate code is there and need to be removed in all.
___
*[400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java, line 259 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudmvLpDM_MGL90SZyE:-Mv6_id_CzwwlFlDR-ik:bhofej8) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/beans/RancherKubernetesInfrastructureMapping.java#L259)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This need not have a YAML. InfraMappings are now an Internal entity and do not need yaml decoder/encoders
</blockquote></details>

Deleted
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java, line 92 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue6t3NAc6oGr3G2adn:-Mv6_trs-bUQJilskIrl:b-e2eogs) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L92)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets discuss more on this. Some customers do use delegates behind proxy. We have already handled this as few other places,  HttpTask should be one of them 
</blockquote></details>

Noted this down. This will be done in another PR.
___
*[400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java, line 41 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueVw3X5xrMRYPatAJz:-Mv6a7bTCd64DzItFYCo:b-t9sbae) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Is this needed here ?
</blockquote></details>

Removed clusterName from here but added a method getClusterName() that returns null.
___
*[400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java, line 89 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueW1DY2Eye6AEBuyxD:-Mv6aFyQ0z3i9LRaKxiB:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/infra/RancherKubernetesInfrastructure.java#L89)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Is this needed here ?
</blockquote></details>

Removed
___
*[400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java, line 61 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv01tMO53oy8PKBvyeu:-Mv6aJEj9oRg3KyiVyyJ:b-wkg3a7) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java#L61)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

did we not try with the usual expression i.e ${secrets.getValue(..)} ? I think we discussed it but I kind of do not remember now. The reason I say this is because, secretManager.obtain is an internal implementation detail that is subject to future changes but ${secrets.getValue(..)} cannot change because that is a user facing expression 
we will need to call the below code
```
private void renderTaskParameters(ExecutionContext context, StateExecutionData stateExecutionData,
      TaskParameters parameters, int expressionFunctorToken) {
    context.resetPreparedCache();
    ExpressionReflectionUtils.applyExpression(parameters,
        (secretMode, value)
            -> context.renderExpression(value,
                StateExecutionContext.builder()
                    .stateExecutionData(stateExecutionData)
                    .adoptDelegateDecryption(true)
                    .expressionFunctorToken(expressionFunctorToken)
                    .build()));
  }
```
</blockquote></details>

This is to be done in next PR
___
*[400-rest/src/main/java/software/wings/service/impl/infrastructuredefinition/InfrastructureDefinitionServiceImpl.java, line 579 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MujG2Fg0K0Lpm78fiH4:-Mv6aP1Z9apqxLP-c9bi:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/infrastructuredefinition/InfrastructureDefinitionServiceImpl.java#L579)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this is unused
</blockquote></details>

Removed
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/cloudprovider/RancherConfigYamlHandler.java, line 40 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv06jXr9HrnhWx9ZSU7:-Mv6aRtw8GvvW5pUiqyZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/yaml/handler/setting/ [...]

2022-02-05 03:01 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 21 files at r15.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-05 03:01 UTC, yogesh-chauhan reviewed
> Reviewed 5 of 21 files at r15.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 86 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-05 07:56 UTC, sainath-b commented on 400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java
> +      if (delegateResponseData.getErrorMessage() != null) {
@shubham-in10se yogesh commented on this rancher error handling part as another comment. i have already done it here. please reuse this.

2022-02-05 11:18 UTC, sainath-b commented
trigger feature-build

2022-02-06 04:55 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 31 files at r17, 2 of 26 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 118 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-06 06:58 UTC, sainath-b commented
trigger feature-build

2022-02-06 07:48 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 12 files at r2, 1 of 18 files at r7, 4 of 21 files at r15, 4 of 20 files at r16, 5 of 31 files at r17, 15 of 26 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 118 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-06 07:56 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 21 files at r15, 5 of 20 files at r16, 20 of 31 files at r17, 7 of 26 files at r18.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 118 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-07 06:53 UTC, sainath-b commented
trigger feature-build

2022-02-09 18:39 UTC, shubham-in10se commented
trigger messagecheck

2022-02-09 18:41 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 1 files at r20, 4 of 26 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 28 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-10 02:57 UTC, sainath-b commented
trigger feature-build

2022-02-10 03:01 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 20 files at r16, 1 of 26 files at r18, 19 of 26 files at r21, 6 of 6 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java, line 135 at r22](https://reviewable.io/reviews/harness/harness-core/30009#-MvWZBx19x9RRBRSPGC1:-MvWZBx19x9RRBRSPGC2:b-yojko7) ([raw file](https://github.com/harness/harness-core/blob/aafc791fb11635ca153c57ac6385206c87df1dfc/400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java#L135)):*
> ```Java
>     if (k8sStateHelper.isRancherInfraMapping(context)
>         && !(Objects.nonNull(context.getContextElement())
>             && context.getContextElement() instanceof RancherClusterElement)) {
> ```

nit: do we need these 3 checks or is the first one enough ?


<!-- Sent from Reviewable.io -->

2022-02-10 05:57 UTC, sainath-b reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 5 file(s) to review. 1 change requests. 21. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java, line 47 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv3TWvR9FzE9ZQGJgr2:-MvXBbgsEaInhJdEXCQE:b-27bzmn) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java#L47)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: change name to RANCHER_EXPR_PROCESSOR
</blockquote></details>

will be take care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java, line 112 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mudr02xBYEQxzChzykl:-MvXBj-A8n0EszBMRhtJ:b4i63gf) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java#L112)):*
> will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherClusterDataResponse.java, line 20 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mudz-LFE4BJRc8lgU-1:-MvXBoY8EiAM95yUFiWI:b4i63gf) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherClusterDataResponse.java#L20)):*
> will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java, line 50 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MudzvlQ1FG-nByU6WsC:-MvXBqMQBnIE2QilOZDe:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java#L50)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can this be moved to 260-delegate ?
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java, line 116 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue1sQU7qe9Xj0H9rAT:-MvXBrPG2Qg3oTj2VGdZ:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherResolveClustersTask.java#L116)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit:  we can use  io.harness.data.structure.EmptyPredicate.isEmpty(selectionParams) 
also in general, we can use the above in place of apache libraries
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java, line 51 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue-N2M34Fbo6V_xXlW:-MvXBsUdAUALx3Ww8y38:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L51)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets see if we can move this to lower modules like 930-delegate-tasks 
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java, line 99 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue8ZK3AbAUaJSItmXa:-MvXBtSP-IGoVHhwSv69:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L99)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Are we going to propagate the same message to users ? 
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java, line 134 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mue8nFZ8ZNJsW5plNtW:-MvXBv0X3mXeJpvSsme4:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L134)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Unused, can be removed
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java, line 139 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueAmhT-8nF0xD7Ktb3:-MvXBvh66cnHGIbCSwxJ:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L139)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

It would be better if we have a RancherClient in 960-api-services module. That way we can separate harness logic and rancher client logic
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/helpers/ext/container/ContainerDeploymentManagerHelper.java, line 160 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-MueUphsDKpgqEmVs1Qh:-MvXBwdz3WP0XWgHOH3u:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/helpers/ext/container/ContainerDeploymentManagerHelper.java#L160)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we sure that this is always of type ```RancherClusterElement``` ?
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java, line 105 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv05pTHBemw7VCGtJvu:-MvXC0_703jbnPwhjpG0:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java#L105)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should avoid this json from jose package. Better to use the one from io.harness.serializer package
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java, line 101 at r15](https://reviewable.io/reviews/harness/harness-core/30009#-Mtc3EhMSSVEOzMs_quR-r15-101:-MvXBzizASpDtOYDnTP8:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/7cc36e93abc2d6dea3308d3b725a346bb06180d8/400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java#L101)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

@shubham-in10se yogesh commented on this rancher error handling part as another comment. i have already done it here. please reuse this.
</blockquote></details>

will be taken care by shubham in next PR
___
*[400-rest/src/main/java/software/wings/sm/ExecutionContextImpl.java, line 1017 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv3nRdo0O5e_H-81UV4:-MvXC1hV6tDJ4CKeLtsr:b-e29hpz) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/ExecutionContextIm [...]

2022-02-11 02:19 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 65 files at r1, 1 of 21 files at r15, 1 of 20 files at r16, 1 of 26 files at r18, 1 of 26 files at r21, 8 of 11 files at r23, 3 of 3 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-11 06:18 UTC, shubham-in10se approved these changes

2022-02-11 06:19 UTC, shubham-in10se approved these changes
> Reviewed 29 of 65 files at r1, 3 of 12 files at r2, 3 of 18 files at r7, 3 of 7 files at r11, 1 of 6 files at r12, 1 of 1 files at r14, 6 of 21 files at r15, 8 of 20 files at r16, 12 of 31 files at r17, 17 of 26 files at r18, 2 of 2 files at r19, 1 of 1 files at r20, 19 of 26 files at r21, 3 of 6 files at r22, 3 of 11 files at r23, 1 of 3 files at r24, 3 of 3 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-11 06:20 UTC, shubham-in10se submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: 1. unresolved discussions. 

___
*[400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java, line 101 at r15](https://reviewable.io/reviews/harness/harness-core/30009#-Mtc3EhMSSVEOzMs_quR-r15-101:-MvbRBMTCW37v2WUlcCE:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/7cc36e93abc2d6dea3308d3b725a346bb06180d8/400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java#L101)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

will be taken care by shubham in next PR
</blockquote></details>

Ok
___
*[400-rest/src/main/java/software/wings/sm/ExecutionContextImpl.java, line 1017 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv3nRdo0O5e_H-81UV4:-MvbRElbDxtPWaeOQK4o:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/sm/ExecutionContextImpl.java#L1017)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

will be taken care by shubham in next PR
</blockquote></details>

Ok


<!-- Sent from Reviewable.io -->

2022-02-11 06:37 UTC, shubham-in10se approved these changes
> Reviewed 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java, line 47 at r14](https://reviewable.io/reviews/harness/harness-core/30009#-Mv3TWvR9FzE9ZQGJgr2:-MvbUoc30Xc_rIDVgqNl:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/0011e18db34d5725da1354e5acbec43688c70327/400-rest/src/main/java/software/wings/common/RancherK8sClusterProcessor.java#L47)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

will be take care by shubham in next PR
</blockquote></details>

Ok


<!-- Sent from Reviewable.io -->

2022-02-11 06:37 UTC, shubham-in10se approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java, line 101 at r15](https://reviewable.io/reviews/harness/harness-core/30009#-Mtc3EhMSSVEOzMs_quR-r15-101:-MvbV0k04alRq36WW9jR:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/7cc36e93abc2d6dea3308d3b725a346bb06180d8/400-rest/src/main/java/software/wings/service/impl/RancherHelperService.java#L101)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

Ok


<!-- Sent from Reviewable.io -->

2022-02-11 07:22 UTC, shubham-in10se commented
Checklist for codebaseHash check:
Is it new task type? 
Yes

Did you make changes to the code in a backward-compatible manner?
some minor changes are also made to existing tasks. All changes made are in backward compatible fashion.

2022-02-11 07:36 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 29 of 65 files at r1, 3 of 12 files at r2, 3 of 18 files at r7, 3 of 7 files at r11, 1 of 6 files at r12, 1 of 1 files at r14, 6 of 21 files at r15, 8 of 20 files at r16, 12 of 31 files at r17, 17 of 26 files at r18, 2 of 2 files at r19, 1 of 1 files at r20, 19 of 26 files at r21, 3 of 6 files at r22, 3 of 11 files at r23, 1 of 3 files at r24, 1 of 3 files at r25, 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30009#-:-MvbhWXi5AZ3gKavO2oq:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-11 07:37 UTC, merged