feat: [CDC-16566]: handle template references on template service
harness/harness-core pull request #30021
Opened 2022-01-17 16:49 UTC by inderschera

Changes as part of this PR:

1.Modify FQN to add templateInputs to returned referred entities from pipeline service.
2. Get template references 
3. Get references of runtime entities referred by linked templates

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30021)

2022-01-19 07:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30021) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30021) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30021) it.</sub>

2022-01-27 10:30 UTC, archit-harness requested changes
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30021)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java, line 608 at r1](https://reviewable.io/reviews/harness/harness-core/30021#-MuQ48ReEdO17ENWKqCV:-MuQ48ReEdO17ENWKqCW:b-lkfs3l) ([raw file](https://github.com/harness/harness-core/blob/da0983f53f2905b58a3621e31436bc0d6fbbb820/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L608)):*
> ```Java
>   @POST
>   @Path("templateReferences")
>   public ResponseDTO<List<EntityDetailProtoDTO>> referenceTest(
> ```

listReferences would be a better name



_Code quote:_
```Java
referenceTest
```


<!-- Sent from Reviewable.io -->

2022-01-27 12:20 UTC, inderschera reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30021)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java, line 608 at r1](https://reviewable.io/reviews/harness/harness-core/30021#-MuQ48ReEdO17ENWKqCV:-MuQT45e5q6lygZ2TD1b:bhn6ahh) ([raw file](https://github.com/harness/harness-core/blob/da0983f53f2905b58a3621e31436bc0d6fbbb820/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L608)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

listReferences would be a better name
</blockquote></details>

Changed method name.


<!-- Sent from Reviewable.io -->

2022-01-28 06:48 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30021)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-01-28 06:52 UTC, merged