[feat]: [CCM-5367]: Anomaly Detection NG APIs
harness/harness-core pull request #30040
Opened 2022-01-18 05:55 UTC by svmav

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30040)

2022-01-19 06:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30040) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30040) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30040) it.</sub>

2022-01-21 06:51 UTC, ketankr9 requested changes
> Reviewed 2 of 9 files at r1, 5 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30040)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/AnomalyResource.java, line 78 at r2](https://reviewable.io/reviews/harness/harness-core/30040#-MtvJs5j4H9KjkSVZ6kP:-MtvJs5j4H9KjkSVZ6kQ:b9xbgoi) ([raw file](https://github.com/harness/harness-core/blob/07720d8b6abf893e41e1c26e2c88cd02f788e72e/340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/AnomalyResource.java#L78)):*
> ```Java
>       responses =
>       {
>         @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "default",
> ```

anomalyQuery will always be null because the request is `@GET` right? Did you mean to use `@POST`?



_Code quote:_
```Java
  @GET
  @Timed
  @LogAccountIdentifier
  @ExceptionMetered
  @ApiOperation(value = "List Anomalies", nickname = "listAnomalies")
  @Operation(operationId = "listAnomalies",
      description = "Fetch the list of anomalies reported according to the filters applied", summary = "List Anomalies",
      responses =
      {
        @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "default",
            description = "List of Anomalies", content = { @Content(mediaType = MediaType.APPLICATION_JSON) })
      })
  public ResponseDTO<List<AnomalyData>>
  listAnomalies(@Parameter(required = true, description = ACCOUNT_PARAM_MESSAGE) @QueryParam(
                    NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier @NotNull @Valid String accountId,
      @RequestBody(description = "Anomaly Query") AnomalyQueryDTO anomalyQuery) {
```
___
*[340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/AnomalyResource.java, line 106 at r2](https://reviewable.io/reviews/harness/harness-core/30040#-MtvKBKNAmJPjDsJv3lR:-MtvKBKNAmJPjDsJv3lS:b-xrk5jh) ([raw file](https://github.com/harness/harness-core/blob/07720d8b6abf893e41e1c26e2c88cd02f788e72e/340-ce-nextgen/src/main/java/io/harness/ccm/remote/resources/AnomalyResource.java#L106)):*
> ```Java
>                                NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier @NotNull @Valid String accountId,
>       @Parameter(required = true, description = "Unique identifier for perspective") @PathParam(
>           "perspectiveId") String perspectiveId,
> ```

Same, GET request and expecting a body.



_Code quote:_
```Java
  @GET
  @Path("perspective/{perspectiveId}")
  @Timed
  @LogAccountIdentifier
  @ExceptionMetered
  @ApiOperation(value = "List Anomalies for Perspective", nickname = "listPerspectiveAnomalies")
  @Operation(operationId = "listPerspectiveAnomalies", description = "Fetch anomalies for perspective",
      summary = "List Anomalies for Perspective",
      responses =
      {
        @io.swagger.v3.oas.annotations.responses.
        ApiResponse(responseCode = "default", description = "List of Anomalies for Perspective",
            content = { @Content(mediaType = MediaType.APPLICATION_JSON) })
      })
  public ResponseDTO<List<PerspectiveAnomalyData>>
  listPerspectiveAnomalies(@Parameter(required = true, description = ACCOUNT_PARAM_MESSAGE) @QueryParam(
                               NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier @NotNull @Valid String accountId,
      @Parameter(required = true, description = "Unique identifier for perspective") @PathParam(
          "perspectiveId") String perspectiveId,
      @RequestBody(required = true, description = "Perspective Query") PerspectiveQueryDTO perspectiveQueryDTO) {
```
___
*[340-ce-nextgen/src/main/java/io/harness/ccm/service/impl/AnomalyServiceImpl.java, line 63 at r2](https://reviewable.io/reviews/harness/harness-core/30040#-MtvOKYT9wF2kswetAWR:-MtvOKYU8nLlK1kTWyh4:b-vteiqf) ([raw file](https://github.com/harness/harness-core/blob/07720d8b6abf893e41e1c26e2c88cd02f788e72e/340-ce-nextgen/src/main/java/io/harness/ccm/service/impl/AnomalyServiceImpl.java#L63)):*
> ```Java
>   @Override
>   public Boolean updateAnomalyFeedback(@NonNull String accountIdentifier, String anomalyId, AnomalyFeedback feedback) {
>     // Todo: Add Update Query
> ```

Please complete this `Todo` if we are exposing update Anomaly via OAS.



_Code quote:_
```Java
  @Override
  public List<PerspectiveAnomalyData> listPerspectiveAnomalies(
      @NonNull String accountIdentifier, PerspectiveQueryDTO perspectiveQuery) {
    // Todo: Add perspective query to anomaly query mapping
    return null;
  }

  @Override
  public Boolean updateAnomalyFeedback(@NonNull String accountIdentifier, String anomalyId, AnomalyFeedback feedback) {
    // Todo: Add Update Query
    return true;
  }
```
___
*[374-ceng-graphql/src/main/java/io/harness/ccm/graphql/dto/perspectives/PerspectiveQueryDTO.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/30040#-MtvOAX47SvfBQolkQl_:-MtvOAX47SvfBQolkQla:b6zc440) ([raw file](https://github.com/harness/harness-core/blob/07720d8b6abf893e41e1c26e2c88cd02f788e72e/374-ceng-graphql/src/main/java/io/harness/ccm/graphql/dto/perspectives/PerspectiveQueryDTO.java#L23)):*
> ```Java
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @Schema(name = "PerspectiveQueryDTO", description = "The query object for perspective cost anomalies")
> ```

Pls remove `DTO` suffix.



_Code quote:_
```Java
@Schema(name = "PerspectiveQueryDTO",
```
___
*[490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/30040#-MtvMqPW2P06UOomh1MJ:-MtvMqPW2P06UOomh1MK:b2sy3ec) ([raw file](https://github.com/harness/harness-core/blob/07720d8b6abf893e41e1c26e2c88cd02f788e72e/490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java#L48)):*
> ```Java
>     return dslContext.selectFrom(ANOMALIES)
>         .where(ANOMALIES.ACCOUNTID.eq(accountId).and(firstNonNull(condition, DSL.noCondition())))
>         .orderBy(orderFields)
> ```

Can you try this like this and remove duplicity 
```
    SelectFinalStep<CeRecommendationsRecord> finalStep = dslContext.selectFrom(CE_RECOMMENDATIONS)
        .where(CE_RECOMMENDATIONS.ACCOUNTID.eq(accountId).and(firstNonNull(condition, DSL.noCondition())))
        .orderBy(CE_RECOMMENDATIONS.MONTHLYSAVING.desc().nullsLast())
        .offset(offset)
        .limit(limit);

    log.info("Query: {}", finalStep.getQuery().toString());
    return finalStep.fetchInto(CeRecommendations.class);
```



_Code quote:_
```Java
    String query = dslContext.selectFrom(ANOMALIES)
                       .where(ANOMALIES.ACCOUNTID.eq(accountId).and(firstNonNull(condition, DSL.noCondition())))
                       .orderBy(orderFields)
                       .offset(offset)
                       .limit(limit)
                       .toString();
    log.info("Anomaly Query: {}", query);
    return dslContext.selectFrom(ANOMALIES)
        .where(ANOMALIES.ACCOUNTID.eq(accountId).and(firstNonNull(condition, DSL.noCondition())))
        .orderBy(orderFields)
        .offset(offset)
        .limit(limit)
        .fetchInto(Anomalies.class);
```
___
*[490-ce-commons/src/main/java/io/harness/ccm/commons/entities/CCMSort.java, line 18 at r2](https://reviewable.io/reviews/harness/harness-core/30040#-MtvOdeL6MQFtioQ9Nby:-MtvOdeL6MQFtioQ9Nbz:b-rtg4sh) ([raw file](https://github.com/harness/harness-core/blob/07720d8b6abf893e41e1c26e2c88cd02f788e72e/490-ce-commons/src/main/java/io/harness/ccm/commons/entities/CCMSort.java#L18)):*
> ```Java
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class CCMSort {
> ```

Pls add OAS `@Schema` annotation on all child Objects of a request Body.



_Code quote:_
```Java
public class CCMSort {
```
___
*[490-ce-commons/src/main/java/io/harness/ccm/commons/entities/anomaly/AnomalyQueryDTO.java, line 25 at r2](https://reviewable.io/reviews/harness/harness-core/30040#-MtvN7PJ402c_ianjF2D:-MtvN7PJ [...]

2022-03-11 09:49 UTC, svmav commented
trigger messagecheck

2022-03-14 02:05 UTC, Rohit-Kaliki approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 17 files at r2, 25 of 31 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30040#-:-My59zemBWPKEwpSzAfL:bnfp4nl)* status: 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-14 02:13 UTC, merged