[feat]: [PL-21178]: Added resource layer for audit filters
harness/harness-core pull request #30089
Opened 2022-01-19 11:35 UTC by nishantsaini20

…ss control. Always filter out audit event for PMS, TEMPLATESERVICE modules

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-01-19 11:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30089) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30089) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30089) it.</sub>

2022-01-19 11:45 UTC, karansiwach requested changes

2022-01-19 11:45 UTC, karansiwach commented on 940-ng-audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
> +    criteriaList.add(Criteria.where(AuditEventKeys.module).nin(unwantedModules));
Clients should not publish audit with these modules if we don't want to show these. Otherwise we will need to have module as a compulsory field in the indexes and might need new indexes as well.

2022-01-19 11:45 UTC, karansiwach commented on 940-ng-audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
> +    criteriaList.add(Criteria.where(AuditEventKeys.module).nin(unwantedModules));
Input Sets events will not be visible otherwise as they currently sending module as PMS.

2022-01-19 13:54 UTC, nishantsaini20 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30089)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[940-ng-audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java, line 179 at r1](https://reviewable.io/reviews/harness/harness-core/30089#-Mtm6mO-n6NGQND-d3Qj-r1-179:-MtmbKsZ2cK9rsrg1Gb6:bh3w93j) ([raw file](https://github.com/harness/harness-core/blob/c6ca4348f0bd6637688d33b6e7db99c9b22a4451/940-ng-audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L179)):*
<details><summary><i>Previously, karansiwach (Karan Siwach) wrote…</i></summary><blockquote>

Input Sets events will not be visible otherwise as they currently sending module as PMS.
</blockquote></details>

Ok. Reverting the changes.


<!-- Sent from Reviewable.io -->

2022-01-19 14:00 UTC, karansiwach reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30089)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-01-19 14:00 UTC, karansiwach approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30089)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-01-21 06:40 UTC, piyush-harness approved these changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30089)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-01-23 09:27 UTC, piyush-harness commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-01-23 09:27 UTC, piyush-harness approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30089)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-01-23 09:28 UTC, piyush-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30089#-:-Mu5FtM5DM0uoBIQe_on:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-01-23 09:31 UTC, piyush-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30089#-:-Mu5GehLE_UrY6dcmK36:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-01-23 09:32 UTC, piyush-harness commented
/rebase

2022-01-23 10:42 UTC, merged