[feat]: [CDP-19458]: nexus artifactory integration
harness/harness-core pull request #30263
Opened 2022-01-26 09:41 UTC by markoharness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-01-26 09:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30263) it.</sub>

2022-02-07 08:09 UTC, markoharness commented
trigger ti1

2022-02-07 08:13 UTC, abosii-harness requested changes
> Reviewed 62 of 103 files at r1, 50 of 50 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 112 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/dtos/ArtifactoryBuildDetailsDTO.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI2B0_5Af2A7Rqhgfp:-MvI2B0a6wfqc6Ksy6pi:b-n6ms3e) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/dtos/ArtifactoryBuildDetailsDTO.java#L23)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(description = "This contains details regarding Artifactory artifact")
> public class ArtifactoryBuildDetailsDTO {
> ```

nit: missing owned by
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/dtos/ArtifactoryRequestDTO.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI2E0C264Qj3E1v3sV:-MvI2E0C264Qj3E1v3sW:b-n6ms3e) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/dtos/ArtifactoryRequestDTO.java#L26)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(description = "Contains image artifact filter details")
> public class ArtifactoryRequestDTO {
> ```

nit: missing owned by
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/dtos/ArtifactoryResponseDTO.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI2QpoABEUH8IsGrEP:-MvI2Qpp8z0beh4IcQjT:b-n6ms3e) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/dtos/ArtifactoryResponseDTO.java#L23)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(description = "Contains image artifact search result details")
> public class ArtifactoryResponseDTO {
> ```

nit: missing owned by
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java, line 20 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI2Rg07C-j-_fl7JPv:-MvI1DrL2S8RLgU4u95x:b-n6ms3e) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java#L20)):*
> ```Java
> 
> @UtilityClass
> public class ArtifactoryResourceMapper {
> ```

nit: missing owned by
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java, line 15 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI2SwE2H-fNz_HX6_z:-MvI2SwE2H-fNz_HX6a-:b-n6ms3e) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceService.java#L15)):*
> ```Java
> import io.harness.cdng.artifact.resources.artifactory.dtos.ArtifactoryResponseDTO;
> 
> public interface ArtifactoryResourceService {
> ```

nit: missing owned by
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 74 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI2efv03Y3j5cxIKTN:-MvI2efv03Y3j5cxIKTO:b-6lfssz) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L74)):*
> ```Java
> 
>   @Inject
>   public ArtifactoryResourceServiceImpl(@Named(DEFAULT_CONNECTOR_SERVICE) ConnectorService connectorService,
> ```

nit: Will it make sense to have only one 'type' of Inject here? Or move everything to the field injector, or add DelegateGrpcClientWrapper delegateGrpcClientWrapper in constructor list
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 100 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI3otsCoEVnjITBOOM:-MvI3otsCoEVnjITBOON:b-hfweu2) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L100)):*
> ```Java
>           String.format(HintException.DELEGATE_NOT_AVAILABLE, DocumentLinksConstants.DELEGATE_INSTALLATION_LINK),
>           new DelegateNotAvailableException(ex.getCause().getMessage(), WingsException.USER));
>     } catch (ExplanationException e) {
> ```

It doesn't really make sense for me why do you have to catch ExplanationException here. I couldn't find any references in the code to this, but maybe I'm missing something
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 159 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI50Cp9XhOklkdoXMB:-MvI50Cp9XhOklkdoXMC:ba744pu) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L159)):*
> ```Java
>   }
> 
>   private boolean isAArtifactoryConnector(@Valid @NotNull ConnectorResponseDTO connectorResponseDTO) {
> ```

nit: Does this @Valid do actually anything? 
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/dtos/NexusBuildDetailsDTO.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5XgLAMPgNnfWuC9R:-MvI5XgLAMPgNnfWuC9S:b-wsi8go) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/dtos/NexusBuildDetailsDTO.java#L23)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(description = "This contains details regarding Nexus artifact")
> public class NexusBuildDetailsDTO {
> ```

nit: missing OwnedBy
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/dtos/NexusRequestDTO.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5_sw3QycR1GPC6RM:-MvI5_sw3QycR1GPC6RN:b-wsi8go) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/dtos/NexusRequestDTO.java#L26)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(description = "Contains image artifact filter details")
> public class NexusRequestDTO {
> ```

nit: missing OwnedBy
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/dtos/NexusResponseDTO.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5cBI1sHWFhmP_qpH:-MvI5cBI1sHWFhmP_qpI:b-n6ms3e) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/dtos/NexusResponseDTO.java#L23)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(description = "Contains image artifact search result details")
> public class NexusResponseDTO {
> ```

nit: missing owned by
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/mappers/NexusResourceMapper.java, line 20 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5e_E-h8tM-24zTy8:-MvI5e_E-h8tM-24zTy9:b-n6ms3e) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd [...]

2022-02-07 10:03 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 159 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI50Cp9XhOklkdoXMB:-MvIcgQW6Y5JxXE90O3k:b-nxlgep) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L159)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: Does this @Valid do actually anything? 
</blockquote></details>

No, it does not. I have removed it.


<!-- Sent from Reviewable.io -->

2022-02-07 10:04 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java, line 121 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5zM-1lDygX1OylLF:-MvId1jYANIFXDGWW7Ut:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java#L121)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we be more detailed here? At least say that expected 1 build but got n builds
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 10:05 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/ArtifactoryRequestResponseMapper.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI8ywF4o04s1Xy6doB:-MvIdEFWDEqUMekBDkqK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/ArtifactoryRequestResponseMapper.java#L24)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can these value be null instead by default?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 10:05 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/NexusRequestResponseMapper.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI96yUCOGlU2aTtZr8:-MvIdH3h2DsuiTAOBVmH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/NexusRequestResponseMapper.java#L24)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can these values be null by default?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 10:07 UTC, markoharness commented
___
*[960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java, line 251 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvICs6oCLZ6esiqG2xL:-MvIddjsBuwN1BFyrQs6:b-42uimk) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java#L251)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we confirm that toString is actually working here? I can see that string() method is defined. And it's a bit questionable if you can call this method twice
</blockquote></details>

You are correct. I have extracted the string first and then reused it.


<!-- Sent from Reviewable.io -->

2022-02-07 10:07 UTC, markoharness commented
___
*[960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java, line 251 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvICs6oCLZ6esiqG2xL:-MvIdmf93hkpuFDM0LJ-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java#L251)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

You are correct. I have extracted the string first and then reused it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 10:08 UTC, markoharness commented
___
*[960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java, line 252 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvIByjP1l_lTjtbSOFP:-MvIdqA6528-_6X5C-pE:b302a5j) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java#L252)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we actually have any logs that customer can check? If the size is matter here, let's just at least provide first 500 characters instead
</blockquote></details>

Added only first 500 chars. Done.


<!-- Sent from Reviewable.io -->

2022-02-07 10:11 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 100 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI3otsCoEVnjITBOOM:-MvIeWtm-_KVWjJ3v2vo:bynzt6o) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L100)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

It doesn't really make sense for me why do you have to catch ExplanationException here. I couldn't find any references in the code to this, but maybe I'm missing something
</blockquote></details>

ExceptionHandler class was missing. Added it now. Done.


<!-- Sent from Reviewable.io -->

2022-02-07 10:11 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5uD_8-2nhNME5c17:-MvIefZG1_JLk8z3X_vP:bynzt6o) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java#L99)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, I can't get why we're catching ExplanationException
</blockquote></details>

ExceptionHandler class was missing. Added it now. Done.


<!-- Sent from Reviewable.io -->

2022-02-08 00:40 UTC, markoharness commented
trigger ti0

2022-02-10 12:28 UTC, markoharness commented
trigger messagecheck

2022-02-10 12:44 UTC, abosii-harness requested changes
> Reviewed 41 of 44 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 100 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI3otsCoEVnjITBOOM:-MvYbsrR5HszQL7YHCQ_:box6ktu) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L100)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

ExceptionHandler class was missing. Added it now. Done.
</blockquote></details>

So it will be always the reason behind access denied to add hint? Why we don't add this directly in exception handler and get rid of this catch?
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5uD_8-2nhNME5c17:-MvYeHJM05vZkqI6G80E:bu11qu3) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java#L99)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

ExceptionHandler class was missing. Added it now. Done.
</blockquote></details>

Can we add this logic in exception handler instead of having it here
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java, line 55 at r4](https://reviewable.io/reviews/harness/harness-core/30263#-MvYclqA3I-AD0wxKZim:-MvYclqBCXdB0RnFdrLE:b1r8af8) ([raw file](https://github.com/harness/harness-core/blob/1dd00185770a31798a4f9ad1edf3a7bbd920e17a/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java#L55)):*
> ```Java
>                 new InvalidCredentialsException(ex.getMessage(), USER)));
>       }
>       return new HintException(
> ```

Can we add an explanations as well? Just something simple would be enough, like artifactory credentials are wrong (the same for other cases)
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java, line 55 at r4](https://reviewable.io/reviews/harness/harness-core/30263#-MvYczz45HzQf-4WReQd:-MvYczz45HzQf-4WReQe:b-ucz1by) ([raw file](https://github.com/harness/harness-core/blob/1dd00185770a31798a4f9ad1edf3a7bbd920e17a/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java#L55)):*
> ```Java
>                 new InvalidCredentialsException(ex.getMessage(), USER)));
>       }
>       return new HintException(
> ```

Same here, would be great to add a simple explanation
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/response/ArtifactDelegateResponseBase.java, line 1 at r4](https://reviewable.io/reviews/harness/harness-core/30263#-MvYdfN_5Z9exLN9iCF9:-MvYdfN_5Z9exLN9iCFA:b-i3idcn) ([raw file](https://github.com/harness/harness-core/blob/1dd00185770a31798a4f9ad1edf3a7bbd920e17a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/response/ArtifactDelegateResponseBase.java#L1)):*
> ```Java
> package io.harness.delegate.task.artifacts.response;
> ```

Missing license copyright


<!-- Sent from Reviewable.io -->

2022-02-14 03:19 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 100 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI3otsCoEVnjITBOOM:-MvqEI7-9wFUwUUGG-0Y:bc7l4k3) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L100)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

So it will be always the reason behind access denied to add hint? Why we don't add this directly in exception handler and get rid of this catch?
</blockquote></details>

Removed the ExplanationException catch. Throwing HintException from the ExceptionHandler.


<!-- Sent from Reviewable.io -->

2022-02-14 03:20 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java, line 55 at r4](https://reviewable.io/reviews/harness/harness-core/30263#-MvYclqA3I-AD0wxKZim:-MvqEgp_Do3SkNmGT5gb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1dd00185770a31798a4f9ad1edf3a7bbd920e17a/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java#L55)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we add an explanations as well? Just something simple would be enough, like artifactory credentials are wrong (the same for other cases)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 03:20 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java, line 55 at r4](https://reviewable.io/reviews/harness/harness-core/30263#-MvYczz45HzQf-4WReQd:-MvqEje_1PndX63vr_R9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1dd00185770a31798a4f9ad1edf3a7bbd920e17a/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java#L55)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, would be great to add a simple explanation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 03:20 UTC, markoharness commented
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/response/ArtifactDelegateResponseBase.java, line 1 at r4](https://reviewable.io/reviews/harness/harness-core/30263#-MvYdfN_5Z9exLN9iCF9:-MvqEnzq9QAxkWIB6Opr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1dd00185770a31798a4f9ad1edf3a7bbd920e17a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/response/ArtifactDelegateResponseBase.java#L1)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Missing license copyright
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 03:21 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/30263#-MvI5uD_8-2nhNME5c17:-MvqErNkBsW-U5ShDQpJ:bc7l4k3) ([raw file](https://github.com/harness/harness-core/blob/9c06fee0520dc981eeb4af460f241732d5a1b316/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java#L99)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we add this logic in exception handler instead of having it here
</blockquote></details>

Removed the ExplanationException catch. Throwing HintException from the ExceptionHandler.


<!-- Sent from Reviewable.io -->

2022-02-14 03:21 UTC, markoharness reviewed
> Reviewed 45 of 103 files at r1, 19 of 50 files at r2, 28 of 44 files at r3, 2 of 11 files at r4, 32 of 32 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 32 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-14 06:32 UTC, abosii-harness requested changes
> Reviewed 31 of 32 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/NexusRegistryArtifactConfig.java, line 81 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqtOMi6duGaJsgxQm7:-MvqtOMi6duGaJsgxQm8:bhdjl8l) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/NexusRegistryArtifactConfig.java#L81)):*
> ```Java
>    * Repo port.
>    */
>   @Pattern(regexp = "^[\\d]+$")
> ```

What if this is an expression or runtime input?
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java, line 36 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvMAMB86RPquM0VJa:-MvqvMAMB86RPquM0VJb:b-hoc59s) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java#L36)):*
> ```Java
>     ArtifactoryServerRuntimeException ex = (ArtifactoryServerRuntimeException) exception;
>     if (ex instanceof ArtifactoryRegistryInvalidCredentialsRuntimeException) {
>       return new HintException("Artifactory registry credentials are not valid.", ex);
> ```

What about explanation? And if we're keeping ex as cause, will not cause this a loop in exception resolving? As well, ex will never be an serializable one
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java, line 38 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvcShAT7oIYMVyf1s:-MvqvcShAT7oIYMVyf1t:b-hoc59s) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java#L38)):*
> ```Java
>     NexusServerRuntimeException ex = (NexusServerRuntimeException) exception;
>     if (ex instanceof NexusRegistrySSLRuntimeException) {
>       return new HintException("SSL certificate validation failed.", ex);
> ```

What about explanation? And if we're keeping ex as cause, will not cause this a loop in exception resolving? As well, ex will never be an serializable one


<!-- Sent from Reviewable.io -->

2022-02-14 07:23 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/NexusRegistryArtifactConfig.java, line 81 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqtOMi6duGaJsgxQm7:-Mvr6Bcj9X_JeC4YbDpa:b-wxxur8) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/NexusRegistryArtifactConfig.java#L81)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What if this is an expression or runtime input?
</blockquote></details>

that is an expression to allow only numeric values for a Nexus repositoryPort field (the field is of String type)
.


<!-- Sent from Reviewable.io -->

2022-02-14 23:29 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java, line 36 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvMAMB86RPquM0VJa:-MvuZDQRCzSrj-OH2uSc:b-dkvw2y) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java#L36)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about explanation? And if we're keeping ex as cause, will not cause this a loop in exception resolving? As well, ex will never be an serializable one
</blockquote></details>

Done. There will be no ExplanationException, however explanation will come in the exception message.


<!-- Sent from Reviewable.io -->

2022-02-14 23:29 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java, line 38 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvcShAT7oIYMVyf1s:-MvuZVNM2CFKGe26q4z7:b-dkvw2y) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java#L38)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about explanation? And if we're keeping ex as cause, will not cause this a loop in exception resolving? As well, ex will never be an serializable one
</blockquote></details>

Done. There will be no ExplanationException, however explanation will come in the exception message.


<!-- Sent from Reviewable.io -->

2022-02-14 23:30 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/NexusRegistryArtifactConfig.java, line 81 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqtOMi6duGaJsgxQm7:-MvuZYmy4b3TePBp-M9p:b85t8yc) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/NexusRegistryArtifactConfig.java#L81)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

that is an expression to allow only numeric values for a Nexus repositoryPort field (the field is of String type)
.
</blockquote></details>

Removed the regex check and created a check in the code.


<!-- Sent from Reviewable.io -->

2022-02-14 23:30 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java, line 55 at r4](https://reviewable.io/reviews/harness/harness-core/30263#-MvYczz45HzQf-4WReQd:-MvuZkTA-TQe3UDxn0q2:b-dkvw2y) ([raw file](https://github.com/harness/harness-core/blob/1dd00185770a31798a4f9ad1edf3a7bbd920e17a/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java#L55)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done. There will be no ExplanationException, however explanation will come in the exception message.


<!-- Sent from Reviewable.io -->

2022-02-14 23:31 UTC, markoharness reviewed
> Reviewed 8 of 12 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-15 05:55 UTC, puthrayaharness requested changes

2022-02-15 05:55 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java
>      if (!RepositoryFormat.docker.name().equals(repositoryFormat)) {
We should move this logic to service layer? Also can you check if the exception is a valid NG supported exception? We generally throw Hint/Explanation exception.

2022-02-15 05:55 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java
> +      throw new InvalidRequestException("RepositoryFormat is not docker. Only 'docker' allowed.");
Same here.

2022-02-15 05:55 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java
> +      throw new InvalidRequestException("RepositoryFormat is not docker. Only 'docker' allowed.");
Same here.

2022-02-15 05:55 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java
> +      throw new InvalidRequestException("RepositoryFormat is not docker. Only 'docker' allowed.");
Same here.

2022-02-15 05:55 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java
> +      throw new InvalidRequestException("RepositoryFormat is not docker. Only 'docker' allowed.");
Same here.

2022-02-15 05:55 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java
> +      imageDetailsBuilder.registryUrl(connectorConfig.getNexusServerUrl());
This should be set even when the customer has no username/password configured?

2022-02-15 05:55 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java
> +      imageDetailsBuilder.registryUrl(connectorConfig.getArtifactoryServerUrl());
Should be set even if the username/password is missing.

2022-02-15 07:53 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 75 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafu-r7-75:-MvwM25q2GO_9alIg_p2:b-nwfvkk) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L75)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

We should move this logic to service layer? Also can you check if the exception is a valid NG supported exception? We generally throw Hint/Explanation exception. 
</blockquote></details>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.


<!-- Sent from Reviewable.io -->

2022-02-15 07:53 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 103 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafu-r7-103:-MvwMrg13xmYj1CPuF9l:b-nwfvkk) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L103)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.


<!-- Sent from Reviewable.io -->

2022-02-15 07:53 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java, line 76 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafv-r7-76:-MvwMuOtCLJYmKdSmTFO:b-nwfvkk) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java#L76)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.


<!-- Sent from Reviewable.io -->

2022-02-15 07:54 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java, line 104 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafv-r7-104:-MvwMv_x-XjZhglgUOsl:b-nwfvkk) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java#L104)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.


<!-- Sent from Reviewable.io -->

2022-02-15 07:54 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java, line 128 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafv-r7-128:-MvwMwqx5oDdcTgoQAmH:b-nwfvkk) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java#L128)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.


<!-- Sent from Reviewable.io -->

2022-02-15 07:56 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java, line 202 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafw-r7-202:-MvwNSLQC9eF60F19ERO:b-qh7ja2) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L202)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

This should be set even when the customer has no username/password configured?
</blockquote></details>

this is covered with the condition
if (connectorConfig.getAuth() != null && connectorConfig.getAuth().getCredentials() != null
        && connectorConfig.getAuth().getAuthType() == NexusAuthType.USER_PASSWORD) {


<!-- Sent from Reviewable.io -->

2022-02-15 07:57 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java, line 222 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafw-r7-222:-MvwN_XL0VOh6tX2DxWO:b-c2is9r) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java#L222)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Should be set even if the username/password is missing.
</blockquote></details>

this is covered with the condition
if (connectorConfig.getAuth() != null && connectorConfig.getAuth().getCredentials() != null
        && connectorConfig.getAuth().getAuthType() == ArtifactoryAuthType.USER_PASSWORD) {


<!-- Sent from Reviewable.io -->

2022-02-15 08:04 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 75 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafu-r7-75:-MvwPOCD42Gby5DxUBoe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L75)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 08:05 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java, line 103 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafu-r7-103:-MvwPRV1CZ3xli5UMYk2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L103)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 08:05 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java, line 76 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafv-r7-76:-MvwPUXy73rQXstGleE6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java#L76)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 08:05 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java, line 104 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafv-r7-104:-MvwPV_LAGPxRO_FJBKB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java#L104)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 08:05 UTC, markoharness commented
___
*[120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java, line 128 at r7](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpivHqJT1WyoCafv-r7-128:-MvwPX-X55zlZpaZKaAs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bddc6302e872075ef5bf6ab01adc9f57a5d9b0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java#L128)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

This field is being sent implicitly by UI (not being fill by actual user). There is also verification of this field in the logic on the delegate side. I will remove it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 08:05 UTC, markoharness reviewed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 16 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-17 08:02 UTC, puthrayaharness requested changes

2022-02-17 10:16 UTC, abosii-harness requested changes
> Reviewed 6 of 12 files at r6, 5 of 6 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 3 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java, line 36 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvMAMB86RPquM0VJa:-Mw5fdrC8YOutgy81CR4:b-jwwr46) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java#L36)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Done. There will be no ExplanationException, however explanation will come in the exception message.
</blockquote></details>

We can think of adding in explanation the command that we executed or api that we tried to reach, this information could be part ArtifactoryServerRuntimeException
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java, line 38 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvcShAT7oIYMVyf1s:-Mw5fxy896Yq4kcF-nE8:b-v01qzv) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java#L38)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Done. There will be no ExplanationException, however explanation will come in the exception message.
</blockquote></details>

We can think of adding in explanation the command that we executed or api that we tried to reach, this information could be part NexusServerRuntimeException
___
*[960-api-services/src/main/java/io/harness/artifactory/service/ArtifactoryRegistryServiceImpl.java, line 43 at r8](https://reviewable.io/reviews/harness/harness-core/30263#-Mw5gGOCEKD52k8Ov9F8:-Mw5gGOCEKD52k8Ov9F9:b4tz1ib) ([raw file](https://github.com/harness/harness-core/blob/dae2018caa3e6f503169f0788e01b960a52b7b89/960-api-services/src/main/java/io/harness/artifactory/service/ArtifactoryRegistryServiceImpl.java#L43)):*
> ```Java
>     } catch (IOException e) {
>       throw new ArtifactoryRegistryInvalidRequestRuntimeException(e.getMessage(), e);
>     } catch (HintException e) {
> ```

Why exactly we're catching HintException here?
___
*[960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java, line 128 at r8](https://reviewable.io/reviews/harness/harness-core/30263#-Mw6AaAF9cPE311T1g7u:-Mw6AaAH5tgtZ3UNKoWu:bwp840e) ([raw file](https://github.com/harness/harness-core/blob/dae2018caa3e6f503169f0788e01b960a52b7b89/960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java#L128)):*
> ```Java
>       NexusRequest nexusConfig, String repository, String port, String imageName, String repositoryFormat) {
>     if (isNotEmpty(port) && !port.matches(REPO_PORT_REGEX)) {
>       throw new NexusRegistryInvalidConfigurationRuntimeException(
> ```

let's see if we can throw the hint and explanation here rather than using exception handler logic 
___
*[960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java, line 205 at r8](https://reviewable.io/reviews/harness/harness-core/30263#-Mw6AffY5TBMqrt8b35x:-Mw6AffY5TBMqrt8b35y:bwp840e) ([raw file](https://github.com/harness/harness-core/blob/dae2018caa3e6f503169f0788e01b960a52b7b89/960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java#L205)):*
> ```Java
>   public List<BuildDetailsInternal> getBuildDetails(
>       NexusRequest nexusConfig, String repository, String port, String imageName, String repositoryFormat, String tag) {
>     if (isNotEmpty(port) && !port.matches(REPO_PORT_REGEX)) {
> ```

let's see if we can throw the hint and explanation here rather than using exception handler logic 


<!-- Sent from Reviewable.io -->

2022-02-17 10:17 UTC, markoharness commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java, line 192 at r8](https://reviewable.io/reviews/harness/harness-core/30263#-MuKkpiwvbfDKmn8a3Q5-r8-192:-Mw63Y9H62lhSw3cwW-i:b-o5e6vq) ([raw file](https://github.com/harness/harness-core/blob/dae2018caa3e6f503169f0788e01b960a52b7b89/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java#L192)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Do we not have static fields to things like `orgIdentifier`?
</blockquote></details>

Yes we have some static field in the SetupAbstractions class. I will apply it for this. 
Just FYI, it should have been done the same for gcr and docker resource services, however it is not currently.


<!-- Sent from Reviewable.io -->

2022-02-17 10:19 UTC, markoharness commented
___
*[960-api-services/src/main/java/io/harness/artifactory/service/ArtifactoryRegistryServiceImpl.java, line 43 at r8](https://reviewable.io/reviews/harness/harness-core/30263#-Mw5gGOCEKD52k8Ov9F8:-Mw6B3MX4_AJ9mebFI3M:bwkete2) ([raw file](https://github.com/harness/harness-core/blob/dae2018caa3e6f503169f0788e01b960a52b7b89/960-api-services/src/main/java/io/harness/artifactory/service/ArtifactoryRegistryServiceImpl.java#L43)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why exactly we're catching HintException here?
</blockquote></details>

Yes it is redundant here. I will remove it.


<!-- Sent from Reviewable.io -->

2022-02-21 17:00 UTC, markoharness commented
___
*[960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java, line 128 at r8](https://reviewable.io/reviews/harness/harness-core/30263#-Mw6AaAF9cPE311T1g7u:-MwSDc-Y9kxpdGLnjE1M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dae2018caa3e6f503169f0788e01b960a52b7b89/960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java#L128)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's see if we can throw the hint and explanation here rather than using exception handler logic 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 17:01 UTC, markoharness commented
___
*[960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java, line 205 at r8](https://reviewable.io/reviews/harness/harness-core/30263#-Mw6AffY5TBMqrt8b35x:-MwSDfF70jc9iTuHTFnE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dae2018caa3e6f503169f0788e01b960a52b7b89/960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java#L205)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's see if we can throw the hint and explanation here rather than using exception handler logic 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 17:01 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java, line 36 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvMAMB86RPquM0VJa:-MwSDjmF6Sc8t-C-1XpH:bt4geev) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ArtifactoryServerExceptionHandler.java#L36)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We can think of adding in explanation the command that we executed or api that we tried to reach, this information could be part ArtifactoryServerRuntimeException
</blockquote></details>

removed the ExceptionHandler completely.


<!-- Sent from Reviewable.io -->

2022-02-21 17:01 UTC, markoharness commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java, line 38 at r5](https://reviewable.io/reviews/harness/harness-core/30263#-MvqvcShAT7oIYMVyf1s:-MwSDpVj4dT6x1FMjWRK:bt4geev) ([raw file](https://github.com/harness/harness-core/blob/e2cdea67a7e60287ad1c86b3aadade71bcd19365/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/NexusServerExceptionHandler.java#L38)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We can think of adding in explanation the command that we executed or api that we tried to reach, this information could be part NexusServerRuntimeException
</blockquote></details>

removed the ExceptionHandler completely.


<!-- Sent from Reviewable.io -->

2022-02-21 17:03 UTC, markoharness reviewed
> Reviewed 52 of 52 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 52 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-21 17:14 UTC, abosii-harness requested changes
> Reviewed 42 of 52 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 10 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[980-commons/src/main/java/io/harness/exception/ArtifactoryRegistryException.java, line 14 at r9](https://reviewable.io/reviews/harness/harness-core/30263#-MwSGY0d7x0-8VavbpvD:-MwSGY0d7x0-8VavbpvE:boqq5h3) ([raw file](https://github.com/harness/harness-core/blob/293fc3cab13ba8f21bca396ba46412ccaf6318c9/980-commons/src/main/java/io/harness/exception/ArtifactoryRegistryException.java#L14)):*
> ```Java
> import java.util.EnumSet;
> 
> public class ArtifactoryRegistryException extends WingsException {
> ```

Missing owner and copyright year is outdated 
___
*[980-commons/src/main/java/io/harness/exception/NexusRegistryException.java, line 15 at r9](https://reviewable.io/reviews/harness/harness-core/30263#-MwSGc09-NLKS46u7PX5:-MwSGc09-NLKS46u7PX6:bejnoy1) ([raw file](https://github.com/harness/harness-core/blob/293fc3cab13ba8f21bca396ba46412ccaf6318c9/980-commons/src/main/java/io/harness/exception/NexusRegistryException.java#L15)):*
> ```Java
> import java.util.EnumSet;
> 
> public class NexusRegistryException extends WingsException {
> ```

Missing owner and copyright year is outdated


<!-- Sent from Reviewable.io -->

2022-02-21 17:49 UTC, markoharness commented
___
*[980-commons/src/main/java/io/harness/exception/ArtifactoryRegistryException.java, line 14 at r9](https://reviewable.io/reviews/harness/harness-core/30263#-MwSGY0d7x0-8VavbpvD:-MwSOmrX1CN9uI8DwHEE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/293fc3cab13ba8f21bca396ba46412ccaf6318c9/980-commons/src/main/java/io/harness/exception/ArtifactoryRegistryException.java#L14)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Missing owner and copyright year is outdated 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 17:50 UTC, markoharness reviewed
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 13 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[980-commons/src/main/java/io/harness/exception/NexusRegistryException.java, line 15 at r9](https://reviewable.io/reviews/harness/harness-core/30263#-MwSGc09-NLKS46u7PX5:-MwSOoUtDd8TlPO5Se1z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/293fc3cab13ba8f21bca396ba46412ccaf6318c9/980-commons/src/main/java/io/harness/exception/NexusRegistryException.java#L15)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Missing owner and copyright year is outdated
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-22 07:15 UTC, markoharness reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 4 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-22 07:30 UTC, puthrayaharness approved these changes
> Reviewed 40 of 103 files at r1, 13 of 50 files at r2, 21 of 44 files at r3, 4 of 32 files at r5, 2 of 12 files at r6, 1 of 2 files at r8, 48 of 52 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 1 change requests. 10. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-22 07:31 UTC, puthrayaharness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-22 08:42 UTC, markoharness commented
trigger ti1

2022-02-22 08:42 UTC, markoharness commented
trigger ti2

2022-02-25 08:30 UTC, abosii-harness approved these changes
> Reviewed 2 of 3 files at r10, 1 of 1 files at r11, 76 of 76 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-25 08:50 UTC, markoharness commented
trigger checkstyle

2022-02-25 09:07 UTC, markoharness commented
trigger checkstyle

2022-02-25 09:07 UTC, markoharness commented
trigger compile

2022-02-25 09:07 UTC, markoharness commented
trigger ti0

2022-02-25 09:07 UTC, markoharness commented
trigger ti1

2022-02-25 09:07 UTC, markoharness commented
trigger ti2

2022-02-25 09:08 UTC, markoharness commented
trigger ti3

2022-02-25 09:08 UTC, markoharness commented
trigger ti4

2022-02-25 09:08 UTC, markoharness commented
trigger ft1

2022-02-25 09:08 UTC, markoharness commented
trigger ft2

2022-02-27 12:48 UTC, markoharness reviewed
> Reviewed 3 of 76 files at r12, 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 7 file(s) to review. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-27 17:59 UTC, markoharness reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: 7 file(s) to review. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-28 08:15 UTC, puthrayaharness approved these changes
> Reviewed 71 of 76 files at r12, 6 of 7 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-28 08:21 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 6 of 7 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-28 08:39 UTC, abosii-harness approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-28 08:40 UTC, puthrayaharness approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-28 08:50 UTC, merged