feat: [DEL-3179]: expose UI apis for ng delegate token
harness/harness-core pull request #30293
Opened 2022-01-27 12:43 UTC by arpit3107

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-01-27 14:38 UTC, abhinav-harness requested changes

2022-01-27 14:38 UTC, abhinav-harness commented on 420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateNgTokenResource.java
> +      @Parameter(description = NGCommonEntityConstants.PROJECT_PARAM_MESSAGE) @QueryParam("projectId") String projectId,
use constant in query param string.

2022-01-27 14:38 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java
>        @Parameter(description = NGCommonEntityConstants.ORG_PARAM_MESSAGE) @QueryParam(
why the change?

2022-01-27 17:11 UTC, raghuAtWings approved these changes
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30293)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-01-28 18:17 UTC, raghuAtWings approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30293)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-01-31 10:04 UTC, abhinav-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30293)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-01-31 10:06 UTC, abhinav-harness approved these changes
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30293)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-01-31 13:12 UTC, merged