[PL-22097]: review git full sync APIs
harness/harness-core pull request #30411
Opened 2022-01-31 21:40 UTC by mohitg0795

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-01 11:52 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30411)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 74 at r1](https://reviewable.io/reviews/harness/harness-core/30411#-Mup5KPy7NY8_fSjtVX0:-Mup5KPy7NY8_fSjtVX1:b-muah0a) ([raw file](https://github.com/harness/harness-core/blob/d7addc89f7392339729a3da2d2ba1207d3511de1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L74)):*
> ```Java
> import retrofit2.http.Body;
> 
> @Api("/full-sync")
> ```

git-full-sync?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 110 at r1](https://reviewable.io/reviews/harness/harness-core/30411#-Mup5WjhDxGEDHdrsSH9:-Mup5WjhDxGEDHdrsSHA:b-gfs4si) ([raw file](https://github.com/harness/harness-core/blob/d7addc89f7392339729a3da2d2ba1207d3511de1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L110)):*
> ```Java
>       responses =
>       { @io.swagger.v3.oas.annotations.responses.ApiResponse(description = "Successfully triggered Full Sync") })
>   public ResponseDTO<TriggerFullSyncResponseDTO>
> ```

If full sync could not be triggered, what will we do? TriggerFullSyncResponseDTO would have "false" in it. But, it won't tell to user why full sync couldn't be triggered 
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 146 at r1](https://reviewable.io/reviews/harness/harness-core/30411#-Mup5p9e0298C9CpLkYA:-Mup5p9e0298C9CpLkYB:b-drmv5f) ([raw file](https://github.com/harness/harness-core/blob/d7addc89f7392339729a3da2d2ba1207d3511de1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L146)):*
> ```Java
>       @Parameter(description = PROJECT_PARAM_MESSAGE) @QueryParam(NGCommonEntityConstants.PROJECT_KEY) @io.
>       harness.accesscontrol.ProjectIdentifier @ProjectIdentifier String projectIdentifier,
>       @RequestBody(description = "Configuration body") @NotNull @Valid GitFullSyncConfigRequestDTO requestDTO) {
> ```

Wrong description. It should be more descriptive and should not use the term body
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 246 at r1](https://reviewable.io/reviews/harness/harness-core/30411#-Mup6n9fAPK1GQG6Hnd0:-Mup6n9fAPK1GQG6Hnd1:b-gr3361) ([raw file](https://github.com/harness/harness-core/blob/d7addc89f7392339729a3da2d2ba1207d3511de1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L246)):*
> ```Java
>   @NGAccessControlCheck(resourceType = ResourceTypes.PROJECT, permission = VIEW_PROJECT_PERMISSION)
>   public ResponseDTO<PageResponse<GitFullSyncEntityInfoDTO>>
>   listFiles(
> ```

API should be getFullSyncStatus
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/30411#-Mup4ioc-pLJzl0QfwFv:-Mup3rwh8zt9E1xdLNyr:bgh8tt8) ([raw file](https://github.com/harness/harness-core/blob/d7addc89f7392339729a3da2d2ba1207d3511de1/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java#L40)):*
> ```Java
>   // Why is this field required in response?
>   @Schema(description = "Checks the new Branch") boolean isNewBranch;
>   @Schema(description = "Target Branch for pull request") String targetBranch;
> ```

Whats the difference between targetBranch and baseBranch?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigRequestDTO.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/30411#-Mup4U8B3RGWpP1AYPgr:-Mup4U8B3RGWpP1AYPgs:b59rdax) ([raw file](https://github.com/harness/harness-core/blob/d7addc89f7392339729a3da2d2ba1207d3511de1/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigRequestDTO.java#L28)):*
> ```Java
>   @Schema(description = "Branch on which Entities will be pushed") @NotNull String branch;
>   @Schema(description = GitSyncApiConstants.REPOID_PARAM_MESSAGE) @NotNull String repoIdentifier;
>   @Schema(description = "Root Folder Path where entities will be pushed") @NotNull String rootFolder;
> ```

What is Root Folder Path? We should clarify that in the description



_Code quote:_
```Java
Root Folder Path where entities will be pushed
```
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncEntityInfoFilterDTO.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/30411#-Mup4rhv3YN9QfEbXgBv:-Mup4rhv3YN9QfEbXgBw:b-kz8irs) ([raw file](https://github.com/harness/harness-core/blob/d7addc89f7392339729a3da2d2ba1207d3511de1/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncEntityInfoFilterDTO.java#L38)):*
> ```Java
> @NoArgsConstructor
> @AllArgsConstructor
> @Schema(name = "GitFullSyncEntityInfoFilter", description = "This contains filters for Git Full Sync")
> ```

Description is incorrect


<!-- Sent from Reviewable.io -->

2022-02-02 05:34 UTC, rashminandasahoo requested changes

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigRequestDTO.java
>  @Schema(name = "GitFullSyncConfigRequest", description = "This contains details to trigger Full Sync")
Details required to trigger full sync.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java
>    @Schema(description = "Branch on which Entities will be pushed") private String branch;
Branch to which entities will be pushed.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java
>    @Schema(description = "Target Branch for pull request") String targetBranch;
Target branch for the pull request.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java
>    @Schema(description = "Checks the new Branch") boolean isNewBranch;
Determines if it is a new branch.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java
>  @Schema(name = "GitFullSyncConfig", description = "This has config details specific to Git Full Sync with Harness")
Can we say "Details to configure Git full sync with Harness"?
@mohitg0795

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java
>            "Configuration already exists, please update it instead of creating a new one", WingsException.USER);
@mohitg0795 I feel this should also be improved.
"Configuration already exists. Update this configuration or create a new one."

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java
>        @RequestBody(description = "Filters like entityType and syncStatus",
@mohitg0795 How about "Filters that must be used for full sync of the given entity."?

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java
>        @RequestBody(description = "Details of Page including: size, index, sort") @BeanParam PageRequest pageRequest,
Details to fetch paginated results.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java
>    @ApiOperation(value = "List files in full sync along with their status", nickname = "listFullSyncFiles")
Fetches the list of files and their status in full sync.
Also, isn't this a GET operation? Why have we used a POST?
cc: @mohitg0795

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java
>    @Operation(operationId = "deleteGitFullSyncConfig", summary = "Delete configuration for performing git full sync",
Deletes full sync configuration for the given Full Sync ID.
I guess we maintain ID for full sync and must provide that for deletion?
cc: @mohitg0795

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java
>    @Operation(operationId = "getGitFullSyncConfig", summary = "Get configuration for performing git full sync",
Fetches configuration details to perform Git full sync.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java
>          ApiResponse(description = "Returns the configuration back along with the scope information")
Returns the updated configuration details and scope for the Git full sync.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java
>    @Operation(operationId = "updateGitFullSyncConfig", summary = "Updates a configuration for performing git full sync",
Updates configuration for performing Git full sync for the given (?) ID.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/TriggerFullSyncResponseDTO.java
>    @Schema(description = "Indicates whether Full Sync is triggered or not") Boolean isFullSyncTriggered;
Determines if full sync is triggered.

2022-02-02 05:34 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/TriggerFullSyncResponseDTO.java
>  @Schema(name = "TriggerFullSyncResponse", description = "This has details to trigger Full Sync")
Details to trigger full sync.

2022-04-06 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30411) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30411) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: bhavya181<br/>:x: mohitg0795<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30411) it.</sub>

2022-04-06 10:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30411) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30411) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: bhavya181<br/>:x: mohitg0795<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30411) it.</sub>

2022-08-01 20:08 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/30411)

2022-08-11 19:39 UTC, closed without merging