added JOOQ queries
harness/harness-core pull request #30436
Opened 2022-02-01 09:51 UTC by shalini-agr

2022-02-01 09:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30436) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30436) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30436) it.</sub>

2022-02-02 08:21 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30436)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java, line 63 at r1](https://reviewable.io/reviews/harness/harness-core/30436#-MutWYsZ1Cfnvmeajuyb:-MutWYsZ1Cfnvmeajuyc:b-o457cv) ([raw file](https://github.com/harness/harness-core/blob/5fa7164d279e7685ccff6d6f3e95f5d0f334c6da/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java#L63)):*
> ```Java
>     public String queryBuilderSelectStatusAndTime(String accountId, String orgId, String projectId, String pipelineId,
>                                                   long startInterval, long endInterval, String tableName) {
>         Query selectStatusQuery = this.dsl.select(Tables.PIPELINE_EXECUTION_SUMMARY_CD.STATUS, Tables.PIPELINE_EXECUTION_SUMMARY_CD.STARTTS).where(Tables.PIPELINE_EXECUTION_SUMMARY_CD.ACCOUNTID.eq(accountId).and(Tables.PIPELINE_EXECUTION_SUMMARY_CD.ORGIDENTIFIER.eq(orgId)).and(Tables.PIPELINE_EXECUTION_SUMMARY_CD.PIPELINEIDENTIFIER.eq(pipelineId)).and(Tables.PIPELINE_EXECUTION_SUMMARY_CD.PROJECTIDENTIFIER.eq(projectId)).and(Tables.PIPELINE_EXECUTION_SUMMARY_CD.STARTTS.ge(startInterval)).and(Tables.PIPELINE_EXECUTION_SUMMARY_CD.STARTTS.lt(endInterval)).and(accountId != null).and(orgId != null).and(projectId != null).and(pipelineId != null).and(startInterval > 0).and(endInterval > 0));
> ```

run clang formatter
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java, line 72 at r1](https://reviewable.io/reviews/harness/harness-core/30436#-MutWSjw4UWj6mEVwPoM:-MutWSjw4UWj6mEVwPoN:b-xq7dr4) ([raw file](https://github.com/harness/harness-core/blob/5fa7164d279e7685ccff6d6f3e95f5d0f334c6da/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java#L72)):*
> ```Java
> //    }
> //
> //    if (orgId != null) {
> ```

delete these lines, no need to comment. Previous version is anyways available in Git


<!-- Sent from Reviewable.io -->

2022-02-07 07:01 UTC, vaibhav-si commented on 800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java
> +  public StatusAndTime queryBuilderSelectStatusAndTime(String accountId, String orgId, String projectId,
can we rename these methods? We are no longer builder the query.

Make it something like getPipelineExecutionStatusAndTime

2022-02-07 07:02 UTC, vaibhav-si commented on 800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java
> +  public StatusAndTime queryBuilderSelectStatusAndTime(String accountId, String orgId, String projectId,
Similarly rename other methods

2022-02-07 10:50 UTC, shalini-agr commented
trigger messageCheck

2022-02-07 10:51 UTC, shalini-agr commented
trigger messagecheck

2022-02-07 10:56 UTC, shalini-agr commented
trigger authorcheck

2022-02-07 11:22 UTC, vaibhav-si requested changes
> Reviewed 1 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30436)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java, line 45 at r6](https://reviewable.io/reviews/harness/harness-core/30436#-MvHlAQZDstPwH8PIUwZ:-MvHlAQZDstPwH8PIUw_:bgv2nzq) ([raw file](https://github.com/harness/harness-core/blob/02376480e23b83d36c74c734a1e42d47d1d90da0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java#L45)):*
> ```Java
>                          .and(Tables.PIPELINE_EXECUTION_SUMMARY_CD.STARTTS.ge(startInterval))
>                          .and(Tables.PIPELINE_EXECUTION_SUMMARY_CD.STARTTS.lt(endInterval))
>                          .and(accountId != null)
> ```

all below null checks can be removed, also >0 check can be removed
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java, line 52 at r6](https://reviewable.io/reviews/harness/harness-core/30436#-MvHlyiP51dRopOf5nf2:-MvHlyiP51dRopOf5nf3:bud1m71) ([raw file](https://github.com/harness/harness-core/blob/02376480e23b83d36c74c734a1e42d47d1d90da0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java#L52)):*
> ```Java
>                          .and(endInterval > 0))
>               .fetch()
>               .into(PipelineExecutionSummaryCd.class);
> ```

directly fetch into statusAndTime


<!-- Sent from Reviewable.io -->

2022-02-07 11:23 UTC, vaibhav-si reviewed
> Reviewed 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30436)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-07 12:26 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30436)* status: 16 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java, line 63 at r1](https://reviewable.io/reviews/harness/harness-core/30436#-MutWYsZ1Cfnvmeajuyb:-MvJ8YZCASK4DFaArbAV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5fa7164d279e7685ccff6d6f3e95f5d0f334c6da/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java#L63)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

run clang formatter
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java, line 72 at r1](https://reviewable.io/reviews/harness/harness-core/30436#-MutWSjw4UWj6mEVwPoM:-MvJ8ZO3BUNt0LlVAiNt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5fa7164d279e7685ccff6d6f3e95f5d0f334c6da/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java#L72)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

delete these lines, no need to comment. Previous version is anyways available in Git
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java, line 29 at r6](https://reviewable.io/reviews/harness/harness-core/30436#-MvHfJHxQeE2n-ga2nrc-r6-29:-MvJ8We0ExCKqN20DTJo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02376480e23b83d36c74c734a1e42d47d1d90da0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java#L29)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Similarly rename other methods
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java, line 45 at r6](https://reviewable.io/reviews/harness/harness-core/30436#-MvHlAQZDstPwH8PIUwZ:-MvJ8MSbDAyKK6IuZ8Er:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02376480e23b83d36c74c734a1e42d47d1d90da0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java#L45)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

all below null checks can be removed, also >0 check can be removed
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java, line 52 at r6](https://reviewable.io/reviews/harness/harness-core/30436#-MvHlyiP51dRopOf5nf2:-MvJ8VeQ7oXmGDmEnoKa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02376480e23b83d36c74c734a1e42d47d1d90da0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/QueryService.java#L52)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

directly fetch into statusAndTime
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 12:32 UTC, prashantsharma04 approved these changes
> Reviewed 7 of 9 files at r2, 1 of 3 files at r3, 1 of 3 files at r5, 2 of 6 files at r7, 2 of 2 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30436)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-08 07:16 UTC, vaibhav-si approved these changes
> Reviewed 1 of 3 files at r5, 1 of 6 files at r7, 2 of 2 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30436)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-02-08 07:17 UTC, vaibhav-si approved these changes
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30436)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-08 07:19 UTC, merged