feat: [CDP-17681]: Support for account level sdk default backoff strategy
harness/harness-core pull request #30463
Opened 2022-02-01 23:22 UTC by ivan-83

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-07 10:59 UTC, sainath-b requested changes
Looks good me. But made some minor comments. Please address them.

2022-02-07 10:59 UTC, sainath-b commented on 970-api-services-beans/src/main/java/io/harness/pcf/model/PcfConstants.java
> +  String THROTTLED_BASE_DELAY_ACCOUNT_VARIABLE =
Why are we defining these in PcfConstants file?. Lets create another file if possible.

2022-02-07 22:32 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30463)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[970-api-services-beans/src/main/java/io/harness/pcf/model/PcfConstants.java, line 117 at r1](https://reviewable.io/reviews/harness/harness-core/30463#-Mura79DzfqHKr0FVZ0A-r1-117:-MvLIn5l-SPRDTDP3ZKU:bngedrh) ([raw file](https://github.com/harness/harness-core/blob/a6e8ebe2ef1ea0c2bee69b30a581ddd80129e74c/970-api-services-beans/src/main/java/io/harness/pcf/model/PcfConstants.java#L117)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

Why are we defining these in PcfConstants file?. Lets create another file if possible.
</blockquote></details>

Thanks, Sainath. Moved it to AwsConstants.


<!-- Sent from Reviewable.io -->

2022-02-08 16:54 UTC, sainath-b reviewed
> Reviewed 10 of 13 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30463)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-08 16:54 UTC, sainath-b approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30463)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-08 20:05 UTC, ivan-83 commented
Is it new task type? 
No

2022-02-08 22:39 UTC, ivan-83 commented
Did you make changes to the code in a backward-compatible manner?
1- will the new version of the delegate receive old version task and process?
Yes
2- If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes

2022-02-08 22:41 UTC, abhinav-harness approved these changes
> Reviewed 10 of 13 files at r1, 3 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30463)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-08 22:46 UTC, merged