feat: [DEL-3183]: implement caching for delegate tokens
harness/harness-core pull request #30561
Opened 2022-02-04 14:38 UTC by arpit3107

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-04 14:44 UTC, abhinav-harness commented
___
*[420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/30561#-Mv4B9WsBzIpKM_NGVja:-Mv4B9WsBzIpKM_NGVjb:btba393) ([raw file](https://github.com/harness/harness-core/blob/61ba0c69855cb0f40c476d697cdb388b435203cf/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java#L30)):*
> ```Java
>   }
> 
>   public void invalidateCacheUsingAccountId(String accountId) {}
> ```

we can make invalidate cache and take token key from other class and we can keep logic internal to this class that we are invalidating whole account cache so that we can change it later.


<!-- Sent from Reviewable.io -->

2022-02-04 14:45 UTC, abhinav-harness commented
___
*[420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTokenCacheKey.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/30561#-Mv4BcrQ1uYK7VN0jwY2:-Mv4BcrR6m_P37NoAkjw:beh5my9) ([raw file](https://github.com/harness/harness-core/blob/61ba0c69855cb0f40c476d697cdb388b435203cf/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTokenCacheKey.java#L11)):*
> ```Java
> @OwnedBy(DEL)
> public class DelegateTokenCacheKey {
>     private final String accountId;
> ```

add it to kryo


<!-- Sent from Reviewable.io -->

2022-02-08 08:06 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30561)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 69 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNJdEu7SUnTuY9OzxQ:-MvNJdEu7SUnTuY9OzxR:b-koohg3) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L69)):*
> ```Java
> 
>   // TODO: Arpit convert this cache to a distributed one
>   private final LoadingCache<String, String> keyCache =
> ```

we should do it before release since its 5 mins task.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 96 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNKg5qCz0C0ad133jg:-MvNKg5r36mnEks6Y_PO:b-oegfgn) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L96)):*
> ```Java
>     boolean decryptedWithRevokedToken = false;
>     DelegateToken delegateToken =
>         delegateTokenCacheHelper.getDelegateToken(new DelegateTokenCacheKey(accountId, delegateHostName));
> ```

Use builder please for delegate token cache key
https://java-design-patterns.com/patterns/fluentinterface/
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNMLtdBpRs-jwkUvAq:-MvNMLtdBpRs-jwkUvAr:bbcw3bi) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L99)):*
> ```Java
>     boolean decryptedWithTokenFromCache = decryptJwtTokenWithDelegateToken(encryptedJWT, delegateToken);
>     if (!decryptedWithTokenFromCache) {
>       delegateTokenCacheHelper.invalidateCacheUsingKey(new DelegateTokenCacheKey(accountId, delegateHostName));
> ```

make this object once and store in variable and keep pasing


<!-- Sent from Reviewable.io -->

2022-02-08 10:05 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30561)* status: 6 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 72 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNiadQAW613UOYe9Gr:-MvNiadRDn6djGX31gF4:bs20aj) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L72)):*
> ```Java
>       Caffeine.newBuilder()
>           .maximumSize(10000)
>           .expireAfterWrite(5, TimeUnit.MINUTES)
> ```

We can also set "expireAfterAccess" to 5 minutes ? We can continue using cached entries if they continuously being accessed.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 95 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNhabf4Qvjglc_Bp_s:-MvNhabf4Qvjglc_Bp_t:bawej3m) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L95)):*
> ```Java
>     boolean decryptedWithActiveToken = false;
>     boolean decryptedWithRevokedToken = false;
>     DelegateToken delegateToken =
> ```

consider renaming it to tokenFromCache



_Code quote:_
```Java
delegateToken 
```
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 103 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNlJK04aCgehH3alDI:-MvNlJK04aCgehH3alDJ:b-fkwzsl) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L103)):*
> ```Java
>           decryptJWTDelegateToken(accountId, delegateHostName, DelegateTokenStatus.ACTIVE, encryptedJWT);
>       if (!decryptedWithActiveToken) {
>         decryptedWithRevokedToken =
> ```

Any idea why we check again revoked token, we can directly throw an error for either invalid token. What makes us being so specific ? 
CC: @raghuatwings 



_Code quote:_
```Java
        decryptedWithRevokedToken =
            decryptJWTDelegateToken(accountId, delegateHostName, DelegateTokenStatus.REVOKED, encryptedJWT);
```
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 114 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNk4xGEAjB9GCteEB0:-MvNk4xGEAjB9GCteEB1:b-w7lzxs) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L114)):*
> ```Java
>     }
> 
>     if (!decryptedWithTokenFromCache && !decryptedWithActiveToken && !decryptedWithRevokedToken) {
> ```

Previously we were decrypting with account key unconditionally, will this if condition be true always ?
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 147 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNkKY4Bpr6xFQlR4nu:-MvNkKY4Bpr6xFQlR4nv:b32x03) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L147)):*
> ```Java
>       String accountId, String delegateHostName, DelegateTokenStatus status, EncryptedJWT encryptedJWT) {
>     long startTime = System.currentTimeMillis();
>     // first try to decrypt with cg tokens and if you failed then try with ng tokens
> ```

we



_Code quote:_
```Java
you
```
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 168 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNksVODSNlLnO8RLXf:-MvNksVODSNlLnO8RLXg:bkuixd8) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L168)):*
> ```Java
>         DelegateToken delegateToken = iterator.next();
>         if (decryptJwtTokenWithDelegateToken(encryptedJWT, delegateToken)) {
>           delegateTokenCacheHelper.putIfTokenIsAbsent(
> ```

Can we skip inserting REVOKED token here in cache?



_Code quote:_
```Java
          delegateTokenCacheHelper.putIfTokenIsAbsent(
              new DelegateTokenCacheKey(accountId, delegateHostName), delegateToken);
```
___
*[400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java, line 96 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNmlJ13IPCspcFRzPn:-MvNmlJ13IPCspcFRzPo:btw8nmh) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L96)):*
> ```Java
>     DelegateToken updatedDelegateToken =
>         persistence.findAndModify(filterQuery, updateOperations, new FindAndModifyOptions());
>     delegateTokenCacheHelper.invalidateCacheUsingAccountId(accountId);
> ```

Have a log.info here saying we are going to invalidate token for this accountID
___
*[400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNXoeIDOWgfe_SRWUu:-MvNXoeIDOWgfe_SRWUv:b-4rvsco) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java#L26)):*
> ```Java
> 
>   public DelegateToken getDelegateToken(DelegateTokenCacheKey delegateTokenCacheKey) {
>     return delegateTokenCache != null ? delegateTokenCache.get(delegateTokenCacheKey) : null;
> ```

Let's break it down to if block for better readability
if (delegateTokenCache == null) {
  log.error("Delegate token cache not yet initialized);
  return;
}
delegateTokenCache.get(delegateTokenCacheKey) ;



_Code quote:_
```Java
    return delegateTokenCache != null ? delegateTokenCache.get(delegateTokenCacheKey) : null;
```
___
*[400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNm7kh7AwFWzV2AeyS:-MvNm7kh7AwFWzV2AeyT:b6msdog) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java#L30)):*
> ```Java
> 
>   // TODO: find a better way to invalidate a particular cache when a delegate token is revoked.
>   public void invalidateCacheUsingAccountId(String accountId) {
> ```

Consider renaming it to "erase(DelegateTokenCacheKey delegateTokenCacheKey)" and let the caller take care of create token key and call erase multiple times.



_Code quote:_
```Java
invalidateCacheUsingAccountId
```
___
*[400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 42 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNltBgCt1MO6GV8Lov:-MvNltBgCt1MO6GV8Low:b-6jkxhj) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java#L42)):*
> ```Java
>   public void putIfTokenIsAbsent(DelegateTokenCacheKey delegateTokenCacheKey, DelegateToken delegateToken) {
>     if (delegateTokenCache != null) {
>       delegateTokenCache.putIfAbsent(delegateTokenCacheKey, delegateToken);
> ```

What if we use "Put" here ?



_Code quote:_
```Java
putIfAbsent
```
___
*[400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNY_pB6MRbgjoF2KkO:-MvNY_pB6MR [...]

2022-02-08 17:00 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30561)* status: 7 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 69 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNJdEu7SUnTuY9OzxQ:-MvPE7q2Ea_b_8tWLiBu:bhy9ot6) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L69)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

we should do it before release since its 5 mins task.
</blockquote></details>

Will do.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 72 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNiadQAW613UOYe9Gr:-MvPEAFu2hwAOaZ4ir3F:b13i2qs) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L72)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We can also set "expireAfterAccess" to 5 minutes ? We can continue using cached entries if they continuously being accessed.
</blockquote></details>

It will be accessed very frequently, so every time we will be increasing expiry time by 5 mins.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 95 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNhabf4Qvjglc_Bp_s:-MvPEZzX12yO02NaWiH6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L95)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

consider renaming it to tokenFromCache
</blockquote></details>

Done.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 96 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNKg5qCz0C0ad133jg:-MvPE_voDeys6_yARaph:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L96)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Use builder please for delegate token cache key
https://java-design-patterns.com/patterns/fluentinterface/
</blockquote></details>

Done.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNMLtdBpRs-jwkUvAq:-MvPEb1l35XIawiI8SEq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L99)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

make this object once and store in variable and keep pasing
</blockquote></details>

Done.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 103 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNlJK04aCgehH3alDI:-MvPEck18sBlgZRkWetv:b20xv13) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L103)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Any idea why we check again revoked token, we can directly throw an error for either invalid token. What makes us being so specific ? 
CC: @raghuatwings 
</blockquote></details>

Yes, so that we can notify the delegate that it is using a revoked token and delegate will be sent into a freeze mode that it wont acquire any tasks. This will allow the users to create a new token and manually restart the delegate process again by changing the accountSecret stored in delegate-config.yml .

Freeze mode allows it to keep retrying.
Where as invalid token will destroy the delegate quickly.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 114 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNk4xGEAjB9GCteEB0:-MvPFJSw1w3d7GW1tKH7:b-1m3s0t) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L114)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Previously we were decrypting with account key unconditionally, will this if condition be true always ?
</blockquote></details>

No, even previously we were seeing these criteria but in a different way. Logic is same.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 147 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNkKY4Bpr6xFQlR4nu:-MvPFXp294sgZEq-T6jf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L147)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we
</blockquote></details>

Done.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 168 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNksVODSNlLnO8RLXf:-MvPFYyD6KI56dH25Fkt:bvwm0z1) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L168)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Can we skip inserting REVOKED token here in cache?
</blockquote></details>

Not actually, since freeze mode delegates will keep trying to access harness and hence we should store revoked token also in cache.
___
*[400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java, line 96 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNmlJ13IPCspcFRzPn:-MvPGhxvD-lYTDZZASAh:b-ykzmc) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L96)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Have a log.info here saying we are going to invalidate token for this accountID
</blockquote></details>

added a log.warn 
___
*[420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTokenCacheKey.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/30561#-Mv4BcrQ1uYK7VN0jwY2:-MvPGoLO-zPlarQKIu4u:b-r6kpff) ([raw file](https://github.com/harness/harness-core/blob/61ba0c69855cb0f40c476d697cdb388b435203cf/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTokenCacheKey.java#L11)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

add it to kryo
</blockquote></details>

added. But what is its use.
___
*[400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNXoeIDOWgfe_SRWUu:-MvPFvFr0xwWnSnuYvS6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0 [...]

2022-02-09 08:58 UTC, abhinav-harness commented
___
*[420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTokenCacheKey.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/30561#-Mv4BcrQ1uYK7VN0jwY2:-MvSh79a5TlOI6vZ_xQ6:b-vc1t90) ([raw file](https://github.com/harness/harness-core/blob/61ba0c69855cb0f40c476d697cdb388b435203cf/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTokenCacheKey.java#L11)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

added. But what is its use.
</blockquote></details>

for caching we use kryo to save it in redis.


<!-- Sent from Reviewable.io -->

2022-02-09 13:10 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30561)* status: 7 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 72 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNiadQAW613UOYe9Gr:-MvTX-Od5xmwlsuadThf:bt5gymz) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L72)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

It will be accessed very frequently, so every time we will be increasing expiry time by 5 mins.
</blockquote></details>

Yes, that will make sure cache will always be alive till we access it. Should be good right ?
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 103 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNlJK04aCgehH3alDI:-MvTXUMdEp4ixoqgKH0a:b2nhb2c) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L103)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Yes, so that we can notify the delegate that it is using a revoked token and delegate will be sent into a freeze mode that it wont acquire any tasks. This will allow the users to create a new token and manually restart the delegate process again by changing the accountSecret stored in delegate-config.yml .

Freeze mode allows it to keep retrying.
Where as invalid token will destroy the delegate quickly.
</blockquote></details>

Ack
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 114 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNk4xGEAjB9GCteEB0:-MvTXiZ_EI72QHpk9S61:bpyfxp5) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L114)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

No, even previously we were seeing these criteria but in a different way. Logic is same.
</blockquote></details>

Ok, can you put below comment here so that it's easier to understand for someone who walk through this code later.
// We were not able to decrypt token yet, trying to decrypt with accountId.
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 147 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNkKY4Bpr6xFQlR4nu:-MvTZ9mZ7Peml0ayXSUU:b32x03) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L147)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we



_Code quote:_
```Java
you
```
___
*[400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, line 156 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvTZHaID0S0BoFSr1Jy:-MvTZHaID0S0BoFSr1Jz:bb7pafw) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L156)):*
> ```Java
>     boolean result = decryptDelegateTokenByQuery(query, accountId, delegateHostName, encryptedJWT);
>     long endTime = System.currentTimeMillis() - startTime;
>     log.debug("Delegate Token verification for accountId {} and status {} has taken {} milliseconds.", accountId,
> ```

took



_Code quote:_
```Java
has taken
```
___
*[400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNm7kh7AwFWzV2AeyS:-MvT_4HF-iAAUSX0vcLb:bcu0s70) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java#L30)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

this method is being called at two places i.e for cg and ng . Also, invalidating whole account delegates is not a great idea, so code should be specific to this class so that we can change it later on easily.
</blockquote></details>

That's what my point is.. It will be good if keep a common interface across all the methods, which will accept TokenCacheKey as an argument. And than later it will easier for you to delete the specific token for cache, by changing the caller to pass the appropriate TokenCacheKey. All the below looping business will be with caller.
___
*[400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java, line 42 at r2](https://reviewable.io/reviews/harness/harness-core/30561#-MvNltBgCt1MO6GV8Lov:-MvT_nNnBCRkkBmcpc8b:bcta3fp) ([raw file](https://github.com/harness/harness-core/blob/c61ea86f4d0deda535eab965559fff21b9baf360/400-rest/src/main/java/io/harness/delegate/utils/DelegateTokenCacheHelper.java#L42)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

We can, but i chose to be on safer side. Whats your suggestion
</blockquote></details>

What safety ? Do we ever update with new tokencache ? If we are doing that, than its a bug. May be internally you can call putIfAbsent and log an error if it failes:
 public void put(DelegateTokenCacheKey delegateTokenCacheKey, DelegateToken delegateToken) {
  if (delegateTokenCache.putIfAbsent(delegateTokenCacheKey, delegateToken) != null) {
    log.error ("Trying to update previously existing token in cache, skipping cache update");
    return;
  }
}
 


<!-- Sent from Reviewable.io -->

2022-03-14 10:56 UTC, closed without merging