[PL-22248]: setup scm user cred in full-sync flow
harness/harness-core pull request #30562
Opened 2022-02-04 15:24 UTC by bhavya181

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-04 20:36 UTC, bhavya181 commented
trigger messagecheck

2022-02-05 10:40 UTC, DeepakPatankar requested changes
> Reviewed 2 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 301 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8T1tY1xCtE7OjXc2F:-Mv8T1tY1xCtE7OjXc2G:b-1ko4cr) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L301)):*
> ```Java
>     final EntityDetail entityDetailDTO = entityDetailRestToProtoMapper.createEntityDetailDTO(request.getEntityDetail());
>     final EntityReference entityReference = entityDetailDTO.getEntityRef();
>     Optional<GitFullSyncJob> gitFullSyncJob = fullSyncJobService.getRunningJob(
> ```

do we need a job which is running ?


<!-- Sent from Reviewable.io -->

2022-02-05 10:40 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 313 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8T72UAYb1wAzL9-Kk:-Mv8T72UAYb1wAzL9-Kl:bfy64wf) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L313)):*
> ```Java
>   private InfoForGitPush getInfoForGitPush(
>       FileInfo request, EntityReference entityReference, String accountId, YamlGitConfigDTO yamlGitConfig) {
>     Principal principal = request.getPrincipal();
> ```

What changes we are doing here ? Does it affect h2g flow ?


<!-- Sent from Reviewable.io -->

2022-02-05 10:44 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 94 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8TZDK-cX6KU73hQWD:-Mv8TZDK-cX6KU73hQWE:b-pqzr76) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L94)):*
> ```Java
>   private io.harness.security.dto.Principal getPrincipal(FileInfo request) {
>     final Principal principalFromProto = request.getPrincipal();
>     if (request.getIsFullSyncFlow()) {
> ```

Ok, so when doing full sync we are getting the user profile information from the git sync service side.

I was thinking that we could have passed the principal with the FullSynJobRequest to the sdk.


<!-- Sent from Reviewable.io -->

2022-02-05 10:46 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8UWdk4mh2t5nTxlp4:-Mv8UWdk4mh2t5nTxlp5:b4enrxn) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L76)):*
> ```protobuf
> message Principal {
>   oneof principal {
>     io.harness.gitsync.UserPrincipal user_principal = 1;
> ```

The user principal proto is part of git sync package ? 


<!-- Sent from Reviewable.io -->

2022-02-05 20:14 UTC, bhavya181 commented
so, I am storing UserPrincipal in FullSyncJob as for a scope and a user, there will be a unique fullSyncJob running. Then at time of pushing changes from git sdk, I have set this userPrincipal in the thread, so that scm is taken from this and also, committer will be taken from userPrincipal.

2022-02-05 20:16 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 313 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8T72UAYb1wAzL9-Kk:-MvAWUZV0g4_WGth9veN:bjvr43h) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L313)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

What changes we are doing here ? Does it affect h2g flow ?
</blockquote></details>

No, it won't, basically in case of full sync, we will be using userprinciapl, which has already been set in the thread earlier.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 94 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8TZDK-cX6KU73hQWD:-MvAWgks8AI2ETe99IoZ:b-loljbl) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L94)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Ok, so when doing full sync we are getting the user profile information from the git sync service side.

I was thinking that we could have passed the principal with the FullSynJobRequest to the sdk.
</blockquote></details>

No, we are passing it to sdk, we are just using FullSyncJob, so that we can query it in git sync side only.
___
*[953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8UWdk4mh2t5nTxlp4:-MvAWv_9ELkr4qKuLYpZ:b8fy4po) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L76)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The user principal proto is part of git sync package ? 
</blockquote></details>

yes, I have created it there.


<!-- Sent from Reviewable.io -->

2022-02-05 20:18 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 301 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-Mv8T1tY1xCtE7OjXc2F:-MvAXC-xAnGTko1stBAj:b-oaaubk) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L301)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

do we need a job which is running ?
</blockquote></details>

yes, there might be many completed or failed jobs for a particluar scope, but we will take userprincipal from running job,


<!-- Sent from Reviewable.io -->

2022-02-06 11:44 UTC, DeepakPatankar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562#-:-MvDqHDI2ol3mXlcZy4q:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-06 11:55 UTC, DeepakPatankar approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-06 11:56 UTC, abhinav-harness approved these changes
> Reviewed 14 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-06 12:03 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java
> +    Optional<GitFullSyncJob> gitFullSyncJob = fullSyncJobService.getRunningJob(
nit: We have a core assumption that there cannot be two running jobs for a project. This we are preventing using a check-in code.

But let's say that somehow that assumption is not valid due to a concurrency issue and two jobs have a running issue.  Then which job will be picked here? Instead of getting job by project identifier should we be getting a job by job's UUID ?>

2022-02-06 12:03 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java
> +    Optional<GitFullSyncJob> gitFullSyncJob = fullSyncJobService.getRunningJob(
nit: This is a non blocking comment and we can take it up later

2022-02-06 12:12 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java
> +      principal = Principal.newBuilder().setUserPrincipal(userProfileHelper.getUserPrincipal()).build();
Here we are doing userProfileHelper.getUserPrincipal(), shouldn't it be request.getPrincipal as the request already has the principal ?

Also userProfileHelper.getUserPrincipal() reads the principal from thread, Can you tag me to the code where we are setting it in the thread

2022-02-06 12:18 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java
> +      return;
nit: But let's say in the future we want to know what happened to this particular request which user sent, then we won't be able to get this data. The easiest solution is that we log that we are ignoring this request, the other solution can be that we create a job for 0 files.

2022-02-06 12:21 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java
> +      principal = Principal.newBuilder().setUserPrincipal(userProfileHelper.getUserPrincipal()).build();
Got the code where we are setting in in the thread. Do we need an if condition for full sync flows? The code for h2g would directly have worked?

2022-02-06 12:21 UTC, DeepakPatankar commented on 953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/UserPrincipalMapper.java
> +        .setEmail(StringValue.of(userPrincipal.getEmail()))
nit: None of emaill, getName, getUserName should be null. The StringValue.of() gives NPE for such inputs. Usually for such cases I set the value only when the variable is not null.

2022-02-06 13:11 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/FullSyncTriggerServiceImpl.java, line 134 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-MvE9E7F5iyic43C2BqN:-MvE9E7G6IVSXxrjQSDL:bpukjqc) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/FullSyncTriggerServiceImpl.java#L134)):*
> ```Java
>   }
> 
>   private UserPrincipal getUserPrincipal() {
> ```

This looks like a very generic utility method to fetch user principal. Can we check if there's any already existing method to do so? 
If not, then we should move it to some common layer. This is very generic method.


<!-- Sent from Reviewable.io -->

2022-02-06 13:18 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/FullSyncTriggerServiceImpl.java, line 84 at r1](https://reviewable.io/reviews/harness/harness-core/30562#-MvEAjKv5NNmzyTobgHG:-MvEAjKv5NNmzyTobgHH:bhinnzm) ([raw file](https://github.com/harness/harness-core/blob/c974e9fc7748287bae2db3a567bb1f8a84444fd2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/FullSyncTriggerServiceImpl.java#L84)):*
> ```Java
>         sendEventForFullSync(accountIdentifier, orgIdentifier, projectIdentifier, triggerFullSyncRequestDTO);
>     if (messageId == null) {
>       return TriggerFullSyncResponseDTO.builder().isFullSyncTriggered(false).build();
> ```

Follow up ticket: We need to change response here. It just says false which means couldn't trigger full sync but we don't mention whats the issue and whats the next action here. We should throw error with the reason why it failed and with a suggestion what should be done.


<!-- Sent from Reviewable.io -->

2022-02-07 06:40 UTC, bhavya181 commented
trigger ti0

2022-02-07 13:49 UTC, mohitg0795 requested changes
> Reviewed 13 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: :shipit: complete! ✓

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/impl/FullSyncJobServiceImpl.java, line 101 at r2](https://reviewable.io/reviews/harness/harness-core/30562#-MvJR8-b6ScHwqB3sOUg:-MvJR8-b6ScHwqB3sOUh:b-fmjv33) ([raw file](https://github.com/harness/harness-core/blob/74c7800d1c650260f7cc8da83a9934a2464169ca/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/impl/FullSyncJobServiceImpl.java#L101)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier) {
>     GitFullSyncJob fullSyncJob =
>         fullSyncJobRepository.findByAccountIdentifierAndOrgIdentifierAndProjectIdentifierAndSyncStatus(
> ```

Please add ticket to add indexing for this query.


<!-- Sent from Reviewable.io -->

2022-02-08 14:22 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java
> +      principal = Principal.newBuilder().setUserPrincipal(userProfileHelper.getUserPrincipal()).build();
No, it will not work.

2022-02-09 11:51 UTC, DeepakPatankar submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 2 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-09 13:21 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 4 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30562#-:-MvTdOJIEMRa_rBtuqvj:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-09 13:26 UTC, bhavya181 commented
Is it new task type? (If yes, no need to answer 2 then)
Yes, it's a new proto.

Did you make changes to the code in a backward-compatible manner?

will the new version of the delegate receive old version task and process?

If new version of the manager receives response for the old task will it be able to handle it successfully?

2022-02-09 13:27 UTC, merged