feat: [CDC-15645]: Mandate secrets for Github webhook authentication
harness/harness-core pull request #30588
Opened 2022-02-07 13:02 UTC by lalit-horcrux

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30588)

2022-02-09 10:35 UTC, lalit-horcrux commented
trigger messagecheck

2022-02-10 06:20 UTC, poojaSinghal requested changes
> Reviewed 9 of 11 files at r1, 3 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30588)* status: 1381 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/resources/graphql/public/application.graphql, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/30588#-MvXH2Hv0QpRXrP9tyoj:-MvXH2Hx-RgqUE1L0YnK:b7oujk2) ([raw file](https://github.com/harness/harness-core/blob/2989886b13aed3e3d7a0a9d7a14ba5c3084458dc/400-rest/src/main/resources/graphql/public/application.graphql#L26)):*
> ```GraphQL
>   # Doc link: https://docs.harness.io/article/mc2lxsas4c-trigger-a-deployment-using-c-url#option_enforce_api_keys_for_manual_triggers
>   isManualTriggerAuthorized: Boolean
>   AreWebHookSecretsMandated: Boolean
> ```

a should be small here?
___
*[400-rest/src/main/resources/graphql/public/applicationMutation.graphql, line 58 at r1](https://reviewable.io/reviews/harness/harness-core/30588#-MvXH5kc67AxPWgnzIZa:-MvXH5kc67AxPWgnzIZb:b-7teqkf) ([raw file](https://github.com/harness/harness-core/blob/2989886b13aed3e3d7a0a9d7a14ba5c3084458dc/400-rest/src/main/resources/graphql/public/applicationMutation.graphql#L58)):*
> ```GraphQL
>   # Doc link: https://docs.harness.io/article/mc2lxsas4c-trigger-a-deployment-using-c-url#option_enforce_api_keys_for_manual_triggers
>   isManualTriggerAuthorized: Boolean
>   AreWebHookSecretsMandated: Boolean
> ```

same.. change to areWebHookSecretsManda
___
*[400-rest/src/main/resources/graphql/public/applicationMutation.graphql, line 69 at r1](https://reviewable.io/reviews/harness/harness-core/30588#-MvXH50k-7O_xYZ-fYp3:-MvXH50k-7O_xYZ-fYp4:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/2989886b13aed3e3d7a0a9d7a14ba5c3084458dc/400-rest/src/main/resources/graphql/public/applicationMutation.graphql#L69)):*
> ```GraphQL
>   isManualTriggerAuthorized: Boolean
>   AreWebHookSecretsMandated: Boolean
> ```

same


<!-- Sent from Reviewable.io -->

2022-02-10 10:35 UTC, lalit-horcrux commented
> small

2022-02-11 03:53 UTC, inderschera requested changes

2022-02-11 03:53 UTC, inderschera commented on 400-rest/src/main/java/software/wings/service/impl/WebHookServiceImpl.java
> +    if (app.getAreWebHookSecretsMandated()) {
since app.getAreWebHookSecretsMandated() can be null as well, it will throw exception. Have Boolean.True.equals(app.getAreWebHookSecretsMandated()) check here.

2022-02-11 03:53 UTC, inderschera commented on 400-rest/src/main/java/software/wings/service/impl/WebHookServiceImpl.java
> +      if (isNotEmpty(webHookSecret) || isEmpty(hashedPayload)) {
Conidtion should be isEmpty(webhookSecret)

2022-02-17 04:55 UTC, inderschera commented on 400-rest/src/main/resources/graphql/public/applicationMutation.graphql
> +  areWebHookSecretsMandated: Boolean
Please have a comment on this telling what it does.

2022-02-17 05:56 UTC, inderschera approved these changes

2022-02-21 05:04 UTC, merged