[CI-3365]: Added files for versioning support
harness/harness-core pull request #30584
Opened 2022-02-07 11:52 UTC by aman-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-08 07:42 UTC, shubham149 commented on 310-ci-manager/src/main/java/io/harness/app/resources/CIExecutionConfigResource.java
> +        return ResponseDTO.newResponse(configService.updateCIContainerTag(accountIdentifier, tag));
How will it handle updates for OOTB step images? Also for aws vm ootb image which are different from k8?

2022-02-08 11:22 UTC, shubham149 submitted a review, later dismissed

2022-02-08 11:22 UTC, shubham149 commented on 310-ci-manager/ci-manager-config.yml
> +  ciImageTag: release-30
Set a value in local that is valid so that local development does not require change everytime.

2022-02-08 11:22 UTC, shubham149 commented on 310-ci-manager/ci-manager-config.yml
> +  supportedCIImageTags: release-30
Use a list here instead of using ; for splitting.

2022-02-08 11:23 UTC, aman-harness commented on 310-ci-manager/ci-manager-config.yml
> +  supportedCIImageTags: release-30
We don't know the size of supported tags -- can we have a dynamic sized list here?

2022-02-08 11:38 UTC, shubham149 commented on 310-ci-manager/ci-manager-config.yml
> +  supportedCIImageTags: release-30
yaml allows dynamic sized lists

2022-02-25 09:14 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/execution/CIExecutionConfigService.java
> +    executionConfig.setGitCloneImage(ciExecutionImages.getGitCloneTag());
why not use builder ?
Setters are not recommened

2022-02-25 09:15 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/execution/CIExecutionConfigService.java
> +  public List<DeprecatedImageInfo> getDeprecatedTags(String accountId) {
refactor this method in small methods
It has lot of if conditions

2022-02-25 09:16 UTC, harshjain12 commented on 330-ci-beans/src/main/java/io/harness/ci/beans/entities/CIExecutionConfig.java
> +@Data
use @value

2022-02-25 09:24 UTC, harshjain12 commented
Can we make sure that it will work for onprem. We don't want any regression

2022-02-25 09:29 UTC, harshjain12 commented
UTs are missing for all the newly added code

2022-02-25 10:03 UTC, aman-harness commented on 330-ci-beans/src/main/java/io/harness/ci/beans/entities/CIExecutionConfig.java
> +@Data
Done

2022-02-25 10:07 UTC, aman-harness commented on 320-ci-execution/src/main/java/io/harness/execution/CIExecutionConfigService.java
> +    executionConfig.setGitCloneImage(ciExecutionImages.getGitCloneTag());
We are upadating the existing record in db that's why setters.

2022-02-25 10:09 UTC, aman-harness commented on 320-ci-execution/src/main/java/io/harness/execution/CIExecutionConfigService.java
> +    executionConfig.setGitCloneImage(ciExecutionImages.getGitCloneTag());
If we create a new record from builder it adds a new entry in db.

2022-02-28 16:08 UTC, harshjain12 requested changes
> Reviewed 1 of 13 files at r1, 1 of 7 files at r2, 21 of 21 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30584)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-01 06:36 UTC, shubham149 commented on 310-ci-manager/src/main/java/io/harness/app/resources/CIExecutionConfigResource.java
> +@Api("/execution-config")
Naming convention for api needs to be better

2022-03-01 06:36 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/execution/CIExecutionConfigService.java
> +    executionConfig.setCacheGCSTag(ciExecutionImages.getCacheGCSTag());
where are we updating the vm based images?

2022-04-06 10:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30584) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30584) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: aman-harness<br/>:x: brijeshdhakar<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30584) it.</sub>

2022-04-06 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=30584) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=30584) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: aman-harness<br/>:x: brijeshdhakar<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=30584) it.</sub>

2022-08-01 13:28 UTC, closed without merging