[fix]: [CDS-2956]: skip adding selector harness.io/track to workloads
harness/harness-core pull request #30679
Opened 2022-02-10 12:50 UTC by tchaurasiya

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30679)

2022-02-10 13:14 UTC, abosii-harness approved these changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-10 14:19 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-15 07:46 UTC, shubham-in10se commented on 260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java
> +          List<KubernetesResource> workloadForAddingSelector =
`workloadForAddingSelector` variable not required. We can do a in-line method call for line 421

2022-02-15 07:46 UTC, shubham-in10se commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java
> +                Maps.immutableEntry(HarnessLabels.track, HarnessLabelValues.trackStable))));
`Maps.immutableEntry(HarnessLabels.track, HarnessLabelValues.trackStable)`
can this be a constant.?

2022-02-15 07:46 UTC, shubham-in10se commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java
> +    return kubernetesResourceId.getName() + kubernetesResourceId.getKind() + kubernetesResourceId.getNamespace();
let's add a separator between the concatenated fields.
this can lead of unwanted corner cases:
name1: abcd
kind1: ef

name2: abc
kind2: def

2022-02-15 07:46 UTC, shubham-in10se commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java
> +        .map(V1DeploymentSpec::getSelector)
can `getSpec` or `getSelector` ever be `null` .?

2022-02-15 08:07 UTC, yogesh-chauhan requested changes
> Reviewed 1 of 6 files at r1, 3 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java, line 369 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvwNexX7PVr8cZS_eGc:-MvwNexX7PVr8cZS_eGd:b-s43tkg) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L369)):*
> ```Java
>   private boolean prepareForRolling(K8sDelegateTaskParams k8sDelegateTaskParams, LogCallback executionLogCallback,
>       boolean inCanaryWorkflow, Boolean skipVersioningForAllK8sObjects, boolean isPruningEnabled,
>       boolean skipAddingTrackSelectorToDeployment) {
> ```

we need to refactor this ( in next PR ) to reduce number of arguments 
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java, line 417 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvwNxtGBw0KgcnTjIQX:-MvwNxtGBw0KgcnTjIQY:b-27tlur) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L417)):*
> ```Java
>         List<KubernetesResourceId> workloadsFromServer = new ArrayList<>();
>         if (skipAddingTrackSelectorToDeployment) {
>           workloadsFromServer = k8sTaskHelperBase.getWorkloadsContainingHarnessTrackSelector(
> ```

nit: getWorkloadsContainingHarnessTrackSelector -> does this get using canary or stable, which selector ?
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java, line 90 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvwPJaJ8MH34YllMuep:-MvwPJaJ8MH34YllMueq:bsoqzoy) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingBaseHandler.java#L90)):*
> ```Java
>   public void addLabelsInDeploymentSelectorForCanary(
>       boolean inCanaryWorkflow, List<KubernetesResource> managedWorkloads) {
>     if (!inCanaryWorkflow && isEmpty(managedWorkloads)) {
> ```

should it be OR ?
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 424 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvwPqT51R2Nx3K-84Wy:-MvwPqT51R2Nx3K-84Wz:b-l7g3vj) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L424)):*
> ```Java
>   public List<KubernetesResourceId> getDeploymentContainingHarnessTrackSelector(KubernetesConfig kubernetesConfig) {
>     List<V1Deployment> deployments = kubernetesContainerService.getDeploymentsWithLabelSelector(
>         kubernetesConfig, kubernetesConfig.getNamespace(), emptyMap());
> ```

ToDo: add support for multiple namespaces as discussed


<!-- Sent from Reviewable.io -->

2022-02-15 08:43 UTC, tchaurasiya commented
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java, line 369 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvwNexX7PVr8cZS_eGc:-MvwYDfx0kcqisKW2oaY:b-2zfusm) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L369)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we need to refactor this ( in next PR ) to reduce number of arguments 
</blockquote></details>

Yes i was thinking for another object for containing flags/boolean information


<!-- Sent from Reviewable.io -->

2022-02-15 08:49 UTC, tchaurasiya commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 424 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvwPqT51R2Nx3K-84Wy:-MvwYmi8-1qP28uJ7PRs:bedb23g) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L424)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

ToDo: add support for multiple namespaces as discussed
</blockquote></details>

Discussed with  @abosii-harness  , We changed logic to fetch deployment from workload iteratively, instead of fetching all namespaced deployments. As managed workload would be one mostly.



_Code quote (from 260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java):_
```Java
8sTaskHelperBase.getDeploymentContainingHarnessTrackSelector(
```


<!-- Sent from Reviewable.io -->

2022-02-15 08:55 UTC, tchaurasiya commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 436 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvviWf2YsafQLykK6iO-r4-436:-Mvwa33F6jFNtR0onCN2:b-61d9d6) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L436)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

can `getSpec` or `getSelector` ever be `null` .?
</blockquote></details>

Selector can be null.



_Code quote (from 260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java):_
```Java
workloadsFromServer = k8sTaskHelperBase.getDeploymentContainingHarnessTrackSelector(
```


<!-- Sent from Reviewable.io -->

2022-02-15 08:56 UTC, tchaurasiya commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 440 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvviWf2YsafQLykK6iO-r4-440:-Mvwa7NR79LIkMZLECfy:bdqifws) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L440)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

`Maps.immutableEntry(HarnessLabels.track, HarnessLabelValues.trackStable)`
can this be a constant.?
</blockquote></details>

Thanks.Done.


<!-- Sent from Reviewable.io -->

2022-02-15 08:56 UTC, tchaurasiya commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 465 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvviWf2YsafQLykK6iO-r4-465:-MvwaASe3aE_E1SxxDVh:bc1364l) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L465)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let's add a separator between the concatenated fields.
this can lead of unwanted corner cases:
name1: abcd
kind1: ef

name2: abc
kind2: def

</blockquote></details>

Thanks. the method is no longer needed now.


<!-- Sent from Reviewable.io -->

2022-02-15 08:58 UTC, tchaurasiya commented
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java, line 417 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvwNxtGBw0KgcnTjIQX:-MvwaZumEH_qQDk3-Ach:b-oxhvng) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L417)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: getWorkloadsContainingHarnessTrackSelector -> does this get using canary or stable, which selector ?
</blockquote></details>

Thanks. Changed now.


<!-- Sent from Reviewable.io -->

2022-02-15 08:58 UTC, tchaurasiya commented
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java, line 419 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvYfyrEgvZ9LrRaN7hW-r4-419:-Mvwach96XNBnwkw7Dmh:bxigcpk) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L419)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

`workloadForAddingSelector` variable not required. We can do a in-line method call for line 421
</blockquote></details>

Thanks. Removed now.


<!-- Sent from Reviewable.io -->

2022-02-15 09:02 UTC, abosii-harness requested changes
> Reviewed 4 of 10 files at r3, 3 of 6 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 2 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 436 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvviWf2YsafQLykK6iO-r4-436:-Mvwb6C8AYk86uKLiRkb:bpmigh) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L436)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Selector can be null.
</blockquote></details>

So we should filter it if is not null?
___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 2068 at r6](https://reviewable.io/reviews/harness/harness-core/30679#-MvwaDQr3Q0tgazKrIY-:-MvwaDQs7OkblotIk5p4:b-a0g40s) ([raw file](https://github.com/harness/harness-core/blob/cbe9411d639e51db1a296c7bc26f41f792118fd4/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2068)):*
> ```Java
>         return deploymentList.getItems();
>       } catch (ApiException exception) {
>         String message =
> ```

Shouldn't we check for if exception code is 404 and return null? ref: getService
___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 2077 at r6](https://reviewable.io/reviews/harness/harness-core/30679#-MvwaOm8A31Ep4UbJ7lj:-MvwaOm8A31Ep4UbJ7lk:b-39wiip) ([raw file](https://github.com/harness/harness-core/blob/cbe9411d639e51db1a296c7bc26f41f792118fd4/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2077)):*
> ```Java
> 
>   @Override
>   public V1Deployment getDeploymentFromServer(KubernetesConfig kubernetesConfig, String namespace, String name) {
> ```

nit: name can be simple getDeployment
___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 2084 at r6](https://reviewable.io/reviews/harness/harness-core/30679#-MvwaWPRAtU6caYDHM5M:-MvwaWPRAtU6caYDHM5N:b-a0g40s) ([raw file](https://github.com/harness/harness-core/blob/cbe9411d639e51db1a296c7bc26f41f792118fd4/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2084)):*
> ```Java
>         return new AppsV1Api(apiClient).readNamespacedDeployment(name, namespace, null, null, null);
>       } catch (ApiException exception) {
>         String message =
> ```

Shouldn't we check for if exception code is 404 and return null? ref: getService


<!-- Sent from Reviewable.io -->

2022-02-15 09:06 UTC, shubham-in10se requested changes
> Reviewed 1 of 6 files at r1, 3 of 10 files at r3, 3 of 6 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 3 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 436 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvviWf2YsafQLykK6iO-r4-436:-Mvwc1El4q4OocRqEgri:b-gcev6b) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L436)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

So we should filter it if is not null?
</blockquote></details>

if `getSelector` is null, this method chain can result in NPE.


<!-- Sent from Reviewable.io -->

2022-02-15 09:42 UTC, shubham-in10se approved these changes

2022-02-15 11:40 UTC, tchaurasiya commented
___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 2084 at r6](https://reviewable.io/reviews/harness/harness-core/30679#-MvwaWPRAtU6caYDHM5M:-MvxApJC5WkPpU7M52iQ:bp1p5cg) ([raw file](https://github.com/harness/harness-core/blob/cbe9411d639e51db1a296c7bc26f41f792118fd4/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2084)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't we check for if exception code is 404 and return null? ref: getService
</blockquote></details>

Thanks for ref. Done.


<!-- Sent from Reviewable.io -->

2022-02-15 11:41 UTC, tchaurasiya commented
___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 2068 at r6](https://reviewable.io/reviews/harness/harness-core/30679#-MvwaDQr3Q0tgazKrIY-:-MvxAs8v2gYTUa7dt3Ld:bkca2fg) ([raw file](https://github.com/harness/harness-core/blob/cbe9411d639e51db1a296c7bc26f41f792118fd4/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2068)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't we check for if exception code is 404 and return null? ref: getService
</blockquote></details>

Removed the corresponding method.


<!-- Sent from Reviewable.io -->

2022-02-15 11:44 UTC, tchaurasiya commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 436 at r4](https://reviewable.io/reviews/harness/harness-core/30679#-MvviWf2YsafQLykK6iO-r4-436:-MvxBXWG7U3TGXluEtZy:b2o7h46) ([raw file](https://github.com/harness/harness-core/blob/13db514d57554ecb9096e0d14f88e4a5baa276a9/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L436)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

if `getSelector` is null, this method chain can result in NPE.
</blockquote></details>

    public<U> Optional<U> map(Function<? super T, ? extends U> mapper) {
        Objects.requireNonNull(mapper);
        if (!isPresent())
            return empty();



_Code snippet:_
```Java
Checked this, Optional.map() handles empty values.
```


<!-- Sent from Reviewable.io -->

2022-02-15 12:03 UTC, abosii-harness approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-15 18:54 UTC, yogesh-chauhan requested changes
> Reviewed 5 of 10 files at r3, 2 of 2 files at r4, 2 of 4 files at r7, 5 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 1 change requests. 2. unresolved discussions. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java, line 417 at r8](https://reviewable.io/reviews/harness/harness-core/30679#-MvyiOw432zxNHT9X5WD:-MvyiOw432zxNHT9X5WE:b-57b2nh) ([raw file](https://github.com/harness/harness-core/blob/c9f8ad97ea91ab660835768d7ed1e313a2ae23d3/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L417)):*
> ```Java
>         List<KubernetesResource> workloadsFromServer = new ArrayList<>();
>         if (skipAddingTrackSelectorToDeployment) {
>           workloadsFromServer = k8sTaskHelperBase.getDeploymentContainingTrackStableSelector(
> ```

nit: better way to model this to take the selector as an argument
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 425 at r8](https://reviewable.io/reviews/harness/harness-core/30679#-MvyiomQ3V7XLCE-_Q-R:-MvyiomS-mJxWpcR8Mwe:b-lnyq3g) ([raw file](https://github.com/harness/harness-core/blob/c9f8ad97ea91ab660835768d7ed1e313a2ae23d3/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L425)):*
> ```Java
>       KubernetesConfig kubernetesConfig, List<KubernetesResource> managedWorkloads) {
>     // calling kubernetes api iteratively instead of getting all deployment object at once, as managedWorkloads would
>     // always be one
> ```

do we support just 1 managed workload in rolling also ?


<!-- Sent from Reviewable.io -->

2022-02-16 03:11 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 4 files at r7, 1 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-16 03:15 UTC, jennyjames21 approved these changes
> Reviewed 1 of 6 files at r1, 3 of 10 files at r3, 3 of 4 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-16 06:57 UTC, yogesh-chauhan reviewed
> Reviewed 9 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 419 at r9](https://reviewable.io/reviews/harness/harness-core/30679#-Mw0JPjL51RRy2ZvCZ1-:-Mw0JPjL51RRy2ZvCZ10:b-qjii4l) ([raw file](https://github.com/harness/harness-core/blob/bf36d44091b478f62be980ff42fe538cb4bb9d1e/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L419)):*
> ```Java
>   }
> 
>   public List<KubernetesResource> getDeploymentContainingTrackStableSelector(KubernetesConfig kubernetesConfig,
> ```

nit: change the name of the method. maybe getDeployment OR getDeploymentWithSelector


<!-- Sent from Reviewable.io -->

2022-02-16 07:01 UTC, tchaurasiya commented
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 425 at r8](https://reviewable.io/reviews/harness/harness-core/30679#-MvyiomQ3V7XLCE-_Q-R:-Mw0KRJYBxfYC37X4M00:brt4wgm) ([raw file](https://github.com/harness/harness-core/blob/c9f8ad97ea91ab660835768d7ed1e313a2ae23d3/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L425)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we support just 1 managed workload in rolling also ?
</blockquote></details>

Done.removed comment.


<!-- Sent from Reviewable.io -->

2022-02-16 07:06 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 9 of 11 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 1 change requests. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-16 07:12 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 11 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-16 07:12 UTC, yogesh-chauhan submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-16 07:46 UTC, shubham-in10se submitted a review, later dismissed
> Reviewed 1 of 10 files at r3, 1 of 6 files at r8, 9 of 11 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-16 10:52 UTC, namantalaycha10 approved these changes
> Reviewed 1 of 6 files at r1, 2 of 10 files at r3, 1 of 4 files at r7, 1 of 6 files at r8, 6 of 11 files at r9, 2 of 2 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-16 11:21 UTC, abhinavsingh1196 approved these changes
> Reviewed 1 of 6 files at r1, 2 of 10 files at r3, 1 of 4 files at r7, 1 of 6 files at r8, 6 of 11 files at r9, 2 of 2 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-16 12:42 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 2 of 10 files at r3, 1 of 4 files at r7, 1 of 6 files at r8, 6 of 11 files at r9, 2 of 2 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30679#-:-Mw1YSyq0O5xiCL8KiNF:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-16 12:54 UTC, merged