feat: [PL-22563]: Full Sync Files should be sorted by the time of creation
harness/harness-core pull request #30685
Opened 2022-02-10 15:06 UTC by bhavya181

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-10 15:15 UTC, bhavya181 commented
trigger messagecheck

2022-02-14 20:53 UTC, mohitg0795 commented on 960-persistence/src/main/java/io/harness/utils/NGResourcePageSortHelper.java
> +/*
Any reasons to put it in 960-persistence? Shouldn't it be in some NG utils module?

2022-02-15 01:52 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[960-persistence/src/main/java/io/harness/utils/NGResourcePageSortHelper.java, line 22 at r3](https://reviewable.io/reviews/harness/harness-core/30685#-Mvv3Xd6Cxm19rrZUJ2B:-Mvv3Xd6Cxm19rrZUJ2C:b-igas9k) ([raw file](https://github.com/harness/harness-core/blob/24f3cd750cae1d640d138fcfae5e9b46f3752f7c/960-persistence/src/main/java/io/harness/utils/NGResourcePageSortHelper.java#L22)):*
> ```Java
> @UtilityClass
> @OwnedBy(PL)
> public class NGResourcePageSortHelper {
> ```

I don't think we need this helper class. This method isn't doing much and has no logic. It's just setting up few fields. 

We can expose a method in PageRequest class itself  instead of a separate util class


<!-- Sent from Reviewable.io -->

2022-02-15 05:49 UTC, DeepakPatankar submitted a review, later dismissed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-15 12:41 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[960-persistence/src/main/java/io/harness/utils/NGResourcePageSortHelper.java, line 1 at r3](https://reviewable.io/reviews/harness/harness-core/30685#-Mvrj4qMRBytvx8jwHi1-r3-1:-MvxOYea0u514lbWizXL:b-kfc06w) ([raw file](https://github.com/harness/harness-core/blob/24f3cd750cae1d640d138fcfae5e9b46f3752f7c/960-persistence/src/main/java/io/harness/utils/NGResourcePageSortHelper.java#L1)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Any reasons to put it in 960-persistence? Shouldn't it be in some NG utils module?
</blockquote></details>

PageRequest was in that only.
___
*[960-persistence/src/main/java/io/harness/utils/NGResourcePageSortHelper.java, line 22 at r3](https://reviewable.io/reviews/harness/harness-core/30685#-Mvv3Xd6Cxm19rrZUJ2B:-MvxObXD3nR8kPI90dZN:bpfhf2y) ([raw file](https://github.com/harness/harness-core/blob/24f3cd750cae1d640d138fcfae5e9b46f3752f7c/960-persistence/src/main/java/io/harness/utils/NGResourcePageSortHelper.java#L22)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I don't think we need this helper class. This method isn't doing much and has no logic. It's just setting up few fields. 

We can expose a method in PageRequest class itself  instead of a separate util class
</blockquote></details>

I have added this method in PaaginationUtils


<!-- Sent from Reviewable.io -->

2022-02-15 12:43 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685#-:-MvxP8ap1_ex60pCb0pA:bnfp4nl)* status: 4 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-16 16:45 UTC, abhinav-harness approved these changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-16 16:47 UTC, DeepakPatankar approved these changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-17 06:54 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685#-:-Mw5ST0z-0YVs635mhBW:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-17 07:13 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30685#-:-Mw5WqO82EJHhukordmu:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-17 07:16 UTC, merged