feat
harness/harness-core pull request #30849
Opened 2022-02-17 13:04 UTC by PragyeshMishra01

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-08 16:53 UTC, PragyeshMishra01 commented
trigger feature-build

2022-03-08 17:18 UTC, PragyeshMishra01 commented
trigger feature-build

2022-03-10 17:42 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-04 03:22 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java
> +import io.harness.cdng.infra.yaml.*;
Don't use * import

2022-04-04 03:24 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java
> +import io.harness.cdng.infra.yaml.*;
Don't use * import. Check other files as well.

2022-04-04 03:31 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java
> +      manifestFileContent = manifestFileContent.replace(ARTIFACT_PATH, "artifactFile");
Make this artifactFile to be some harness specific directory to avoid any collisions between customer files, harness managed files

2022-04-04 10:11 UTC, piyush-bhuwalka commented
trigger feature-build

2022-04-04 17:03 UTC, PragyeshMishra01 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java
> +import io.harness.cdng.infra.yaml.*;
Done

2022-04-04 17:04 UTC, PragyeshMishra01 commented
trigger codeformat

2022-04-04 17:05 UTC, PragyeshMishra01 commented
trigger checkstyle

2022-04-04 18:18 UTC, PragyeshMishra01 commented
trigger checkstyle

2022-04-05 01:47 UTC, PragyeshMishra01 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java
> +      manifestFileContent = manifestFileContent.replace(ARTIFACT_PATH, "artifactFile");
Done

2022-04-07 11:52 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-11 03:10 UTC, sainath-b commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/mapper/ServerlessAwsLambdaFunctionToServerInstanceInfoMapper.java
> +    return serverlessAwsLambdaFunctions.stream()
@PragyeshMishra01 
Test a case where if serverless allows zero functions to be deployed. Check if NLP is happening in that case and handle them.

2022-04-11 08:48 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-11 09:10 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-11 09:49 UTC, PragyeshMishra01 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/mapper/ServerlessAwsLambdaFunctionToServerInstanceInfoMapper.java
> +    return serverlessAwsLambdaFunctions.stream()
I tried doing one such deployment with zero functions, It seems that serverless allows us to deploy with zero functions. In that case, deployment is happening successfully but the function output will be null and I have already added NPE check for that before calling this function.

2022-04-17 22:59 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-17 23:52 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-18 09:34 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-18 10:01 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-19 01:10 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-19 01:11 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-21 07:48 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-21 07:54 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-21 07:55 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-22 03:59 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-22 10:09 UTC, PragyeshMishra01 commented
trigger messagecheck

2022-04-22 15:01 UTC, arvind-choudhary-h reviewed
> Reviewed 107 of 242 files at r1, 18 of 45 files at r3, 7 of 19 files at r5, 12 of 23 files at r6, 3 of 12 files at r7, 81 of 95 files at r8, 3 of 16 files at r9, 1 of 1 files at r11, 13 of 20 files at r12, 2 of 3 files at r13, 1 of 1 files at r14, 14 of 14 files at r15, 2 of 2 files at r16, 8 of 8 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30849)* status: 4. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-22 20:58 UTC, PragyeshMishra01 commented
> _[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java, line 136 at r17](https://reviewable.io/reviews/harness/harness-core/30849#-N0GSxIQC1ypwfL08mMj:-N0GSxIRAGwhFmkFYGMw:b-l8ibda) ([raw file](https://github.com/harness/harness-core/blob/0fa640605ca66455e318b10af95ca63fb74f7751/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L136)):_
> 
> > ```java
> >         if (artifactoryRegistryArtifactConfig.getRepositoryFormat().getValue().equals(generic.name())) {
> >           String genericPlaceholder =
> >               " type: %s, artifactDirectory: %s, artifactPath/artifactPathFilter: %s, connectorRef: %s\n";
> > ```
> 
> extract as a constant?

Done

2022-04-23 00:58 UTC, puthrayaharness requested changes

2022-04-23 00:58 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/ArtifactoryRegistryArtifactInfo.java
> +        .connectorRef(connectorRef == null ? null : ParameterField.<String>builder().value(connectorRef).build())
Better to create a common utils for this. Null check everytime is not needed.

2022-04-23 12:52 UTC, puthrayaharness requested changes

2022-04-23 12:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +        artifactConfig.getArtifactPathFilter() != null ? artifactConfig.getArtifactPathFilter().getValue() : "";
Please use isNotBlank filter.

2022-04-23 12:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +        if (artifactoryRegistryArtifactConfig.getRepositoryFormat().getValue().equals(docker.name())) {
Switch case is more readable?

2022-04-23 12:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +  private ArtifactoryGenericArtifactOutcome getArtifactoryGenericArtifactOutcome(
Can we use isNotBlankFilter?

2022-04-23 12:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java
>    public ArtifactoryResponseDTO toArtifactoryResponse(
Rename className `toArtifactoryDockerResponse`

2022-04-23 12:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java
> +        if (artifactoryRegistryArtifactConfig.getRepositoryFormat().getValue().equals(generic.name())) {
Reverse the check `generic.name().equals(.....` this will ensure that there is no null pointer exception

2022-04-23 12:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java
> +              ParameterField.isNull(artifactoryRegistryArtifactConfig.getArtifactPath())
How are we differentiating between `blank` and `null`?

2022-04-23 12:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java
> +              ParameterField.isNull(artifactoryRegistryArtifactConfig.getArtifactPath())
Or does that not matter?

2022-04-23 12:52 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +      ArtifactoryDockerArtifactDelegateRequest attributesRequest =
Please wrap this into a private class the way it is done for `fetchFileBuilds`

2022-04-23 12:52 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +    if (artifactoryRequest instanceof ArtifactoryGenericArtifactDelegateRequest) {
May be instead of extending `ArtifactoryGenericArtifactDelegateRequest` from `ArtifactSourceDelegateRequest` may me create a class called `ArtifactoryBaseArtifactDelegateRequest` that extends `ArtifactSourceDelegateRequest` and has common fields like `auth`. And all methods in this class have `ArtifactoryBaseArtifactDelegateRequest` as parameter rather than `ArtifactSourceDelegateRequest`

2022-04-23 12:52 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +    if (artifactDirectory.isEmpty()) {
`artifactDirectory` can this be `null`? Instead use `EmptyPredicate` class

2022-04-23 12:52 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHelper.java
> +        artifactoryGenericArtifactDelegateRequest.getArtifactPath(), MAX_NO_OF_TAGS_PER_ARTIFACT);
Rename `MAX_NO_OF_TAGS_PER_ARTIFACT` this to a more generic appropriate name, may be `MAX_NO_OF_BUILDS_PER_ARTIFACT`

2022-04-23 12:52 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryGenericArtifactDelegateRequest.java
> +  public List<ExecutionCapability> fetchRequiredExecutionCapabilities(ExpressionEvaluator maskingEvaluator) {
This looks exactly same for `Docker` and `Generic` please create a base class that both `generic` and `docker ` can extend. That way we don't have to change logic in both places

2022-04-23 12:52 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryGenericArtifactDelegateRequest.java
> +  public List<ExecutionCapability> fetchRequiredExecutionCapabilities(ExpressionEvaluator maskingEvaluator) {
Also add relevant fields that are common between the two.

2022-04-23 12:52 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      if (repositories.isEmpty()) {
Please use `EmptyPredicate`

2022-04-23 12:52 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      log.info("Retrieving repositories for package {} success", packageType);
Please fetch the log message. It is already retrieved and this gets logged even when the fetched logs are empty.

2022-04-23 12:52 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +        log.info("Repositories are not available of package type {} or User not authorized to access artifactory",
nit: this can be `log.warn`

2022-04-23 12:52 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      log.error(ERROR_OCCURRED_WHILE_RETRIEVING_REPOSITORIES, e);
Don't we need to throw an exception? Why are we suppressing this exception?

2022-04-23 12:52 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      ArtifactoryConfigRequest artifactoryConfig, String repositoryName, String artifactPath, int maxVersions) {
Why is this logic being duplicated? We already have this written, please make sure that CG and NG have a common code. It is very difficult to maintain

2022-04-23 12:52 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/comparator/BuildDetailsComparatorDescending.java
> +public class BuildDetailsComparatorDescending implements Comparator<BuildDetails> {
This is not required in case of Articatory. Artifactory APIs return builds in the order of `createdAt desc`.

2022-04-25 05:39 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-26 04:50 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-26 06:06 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-26 06:06 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-26 06:06 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/ArtifactoryRegistryArtifactInfo.java
> +        .connectorRef(connectorRef == null ? null : ParameterField.<String>builder().value(connectorRef).build())
Done

2022-04-26 06:07 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +        artifactConfig.getArtifactPathFilter() != null ? artifactConfig.getArtifactPathFilter().getValue() : "";
Done

2022-04-26 06:07 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +        if (artifactoryRegistryArtifactConfig.getRepositoryFormat().getValue().equals(docker.name())) {
Done

2022-04-26 06:07 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +  private ArtifactoryGenericArtifactOutcome getArtifactoryGenericArtifactOutcome(
Done

2022-04-26 06:07 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java
>    public ArtifactoryResponseDTO toArtifactoryResponse(
Done

2022-04-26 06:07 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java
> +        if (artifactoryRegistryArtifactConfig.getRepositoryFormat().getValue().equals(generic.name())) {
Done

2022-04-26 06:08 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java
> +              ParameterField.isNull(artifactoryRegistryArtifactConfig.getArtifactPath())
We are keeping the same logic as Docker. Ideally it should not matter

2022-04-26 06:08 UTC, piyush-bhuwalka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +      ArtifactoryDockerArtifactDelegateRequest attributesRequest =
Done

2022-04-26 06:10 UTC, piyush-bhuwalka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +    if (artifactoryRequest instanceof ArtifactoryGenericArtifactDelegateRequest) {
Not Done. We fear that this might cause regression for docker . The docker class for the same is used at a lot of places

2022-04-26 06:10 UTC, piyush-bhuwalka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHelper.java
> +        artifactoryGenericArtifactDelegateRequest.getArtifactPath(), MAX_NO_OF_TAGS_PER_ARTIFACT);
Done

2022-04-26 06:10 UTC, piyush-bhuwalka commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryGenericArtifactDelegateRequest.java
> +  public List<ExecutionCapability> fetchRequiredExecutionCapabilities(ExpressionEvaluator maskingEvaluator) {
Not Done. Refer similar comment above

2022-04-26 06:10 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      if (repositories.isEmpty()) {
Done

2022-04-26 06:11 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      log.info("Retrieving repositories for package {} success", packageType);
Not Done. We are keeping the same logic as Artifactory Docker method which is a lot similar to this

2022-04-26 06:11 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +        log.info("Repositories are not available of package type {} or User not authorized to access artifactory",
Done

2022-04-26 06:11 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      log.info("Retrieving repositories for package {} success", packageType);
Done

2022-04-26 06:12 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      log.error(ERROR_OCCURRED_WHILE_RETRIEVING_REPOSITORIES, e);
Not Done. We are keeping the same logic as Artifactory Docker method of this which is very similar to it

2022-04-26 06:12 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      ArtifactoryConfigRequest artifactoryConfig, String repositoryName, String artifactPath, int maxVersions) {
Logic is a bit different for both the flows

2022-04-26 06:13 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifacts/comparator/BuildDetailsComparatorDescending.java
> +public class BuildDetailsComparatorDescending implements Comparator<BuildDetails> {
According to the product requirement, we want it in alphabetic descending order which is being used in Docker

2022-04-26 06:28 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +    if (artifactoryRequest instanceof ArtifactoryGenericArtifactDelegateRequest) {
I don't think it should. Adding fields should not cause such issues. May be discuss with Delegate team on this once.

2022-04-26 07:17 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      ArtifactoryConfigRequest artifactoryConfig, String repositoryName, String artifactPath, int maxVersions) {
Done

2022-04-27 10:41 UTC, piyush-bhuwalka commented
trigger feature-build

2022-04-27 11:00 UTC, piyush-bhuwalka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +    if (artifactoryRequest instanceof ArtifactoryGenericArtifactDelegateRequest) {
We have made changes. You can take a look

2022-04-27 11:00 UTC, piyush-bhuwalka commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryGenericArtifactDelegateRequest.java
> +  public List<ExecutionCapability> fetchRequiredExecutionCapabilities(ExpressionEvaluator maskingEvaluator) {
Done

2022-04-27 13:51 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-27 13:54 UTC, PragyeshMishra01 commented
trigger feature-build

2022-04-28 05:00 UTC, sainath-b approved these changes

2022-04-28 05:02 UTC, sainath-b reviewed
> Reviewed 90 of 242 files at r1, 13 of 45 files at r3, 6 of 19 files at r5, 9 of 23 files at r6, 1 of 12 files at r7, 13 of 95 files at r8, 3 of 16 files at r9, 1 of 1 files at r11, 11 of 20 files at r12, 2 of 3 files at r13, 8 of 14 files at r15, 1 of 2 files at r16, 4 of 8 files at r17, 28 of 62 files at r18, 16 of 17 files at r20, 30 of 38 files at r21, 24 of 24 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30849)* status: 1 change requests. 22. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-28 05:21 UTC, puthrayaharness approved these changes
> Reviewed 90 of 242 files at r1, 13 of 45 files at r3, 6 of 19 files at r5, 9 of 23 files at r6, 1 of 12 files at r7, 13 of 95 files at r8, 3 of 16 files at r9, 1 of 1 files at r11, 11 of 20 files at r12, 2 of 3 files at r13, 8 of 14 files at r15, 1 of 2 files at r16, 4 of 8 files at r17, 23 of 62 files at r18, 16 of 17 files at r20, 12 of 38 files at r21, 24 of 24 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30849)* status: 22. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-28 05:23 UTC, puthrayaharness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30849)* status: 6. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-28 07:00 UTC, merged

2022-05-03 18:54 UTC, PragyeshMishra01 commented
trigger feature-build