[fix]: [PL-22647]: Fixed error handling for file with same name
harness/harness-core pull request #30893
Opened 2022-02-21 13:30 UTC by rathodmeetsatish

Fixed error handling for file with same name

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-21 13:36 UTC, abhinav-harness commented on 900-git-sync-sdk/src/test/java/io/harness/gitsync/scm/SCMGitSyncHelperTest.java
> +    MDC.setContextMap(contextMap);
unset this too

2022-02-21 13:37 UTC, abhinav-harness requested changes
one change

2022-02-22 13:58 UTC, DeepakPatankar requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30893)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java, line 65 at r1](https://reviewable.io/reviews/harness/harness-core/30893#-MwWfyxK-joJht7f6ZyD:-MwWfyxL2a0FrGjO9gvX:b-grkke1) ([raw file](https://github.com/harness/harness-core/blob/15f9160d578d1ec3e7f0dcf986f7f8adfdc315bc/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L65)):*
> ```Java
>     try {
>       checkForError(pushFileResponse);
>     } catch (WingsException e) {
> ```

Whyy this change ?


<!-- Sent from Reviewable.io -->

2022-02-23 07:11 UTC, rathodmeetsatish commented
trigger messagecheck

2022-02-23 07:14 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30893)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[900-git-sync-sdk/src/test/java/io/harness/gitsync/scm/SCMGitSyncHelperTest.java, line 113 at r1](https://reviewable.io/reviews/harness/harness-core/30893#-MwRTYlqtvs_oRuqCPM7-r1-113:-Mw_QX7c-HU1-lFNOa3Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15f9160d578d1ec3e7f0dcf986f7f8adfdc315bc/900-git-sync-sdk/src/test/java/io/harness/gitsync/scm/SCMGitSyncHelperTest.java#L113)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

unset this too 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-23 08:19 UTC, DeepakPatankar approved these changes
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30893)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-23 09:17 UTC, rijajoo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30893#-:-Mw_rqy--rAuQp5tk8pW:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-23 09:22 UTC, abhinav-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30893#-:-Mw_sxvUDuOWjiNpx8Zs:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-02-23 09:27 UTC, merged