fix: [CI-3395]: Fixed trigger audit trail
harness/harness-core pull request #31021
Opened 2022-02-25 10:37 UTC by devkimittal

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-02-28 05:53 UTC, harshjain12 commented on 800-pipeline-service/src/main/java/io/harness/pms/outbox/PMSOutboxEventHandler.java
> +@OwnedBy(PL)
It should be pipeline team

2022-02-28 05:54 UTC, harshjain12 commented on 800-pipeline-service/src/test/java/io/harness/pms/outbox/PMSOutboxEventHandlerTest.java
> +public class PMSOutboxEventHandlerTest {
Add UT for trigger Update event

2022-02-28 05:55 UTC, devkimittal commented on 800-pipeline-service/src/main/java/io/harness/pms/outbox/PMSOutboxEventHandler.java
> +@OwnedBy(PL)
My bad, I thought PL is pipeline.

2022-02-28 05:56 UTC, harshjain12 commented
Auditing update trigger is extremely imp. Please add UT for it.

2022-02-28 05:57 UTC, harshjain12 commented on 800-pipeline-service/src/test/java/io/harness/pms/outbox/PMSOutboxEventHandlerTest.java
> +    OutboxEvent outboxEvent = OutboxEvent.builder()
Use common method to generate event by passing event type.
Code is duplicated across UTs

2022-02-28 05:57 UTC, harshjain12 commented on 800-pipeline-service/src/test/java/io/harness/pms/outbox/PMSOutboxEventHandlerTest.java
> +        NGTriggerEntity.builder().name(randomAlphabetic(10)).identifier(identifier).yaml(null).build();
why to pass null in yaml ?

2022-02-28 05:58 UTC, harshjain12 commented on 800-pipeline-service/src/test/java/io/harness/pms/outbox/PMSOutboxEventHandlerTest.java
> +  public void testPipelineCreate() throws Exception {
remove duplicate code across UTs

2022-02-28 06:04 UTC, devkimittal commented on 800-pipeline-service/src/test/java/io/harness/pms/outbox/PMSOutboxEventHandlerTest.java
> +        NGTriggerEntity.builder().name(randomAlphabetic(10)).identifier(identifier).yaml(null).build();
Not required in testing perspective

2022-02-28 06:08 UTC, harshjain12 commented on 800-pipeline-service/src/test/java/io/harness/pms/outbox/PMSOutboxEventHandlerTest.java
> +        NGTriggerEntity.builder().name(randomAlphabetic(10)).identifier(identifier).yaml(null).build();
we need it.
We do convert yaml to object. What if conversion has some issue.

2022-02-28 06:10 UTC, brijeshdhakar requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31021)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceModule.java, line 407 at r1](https://reviewable.io/reviews/harness/harness-core/31021#-MwyvU0981Bbxt2642Uk:-MwyvU0981Bbxt2642Ul:b-sb1dtb) ([raw file](https://github.com/harness/harness-core/blob/477d3bac79f8a945bfd90df583d1fd489c59e82a/800-pipeline-service/src/main/java/io/harness/PipelineServiceModule.java#L407)):*
> ```Java
>         MapBinder.newMapBinder(binder(), String.class, OutboxEventHandler.class);
>     outboxEventHandlerMapBinder.addBinding(ResourceTypeConstants.TRIGGER).to(TriggerOutboxEventHandler.class);
>     outboxEventHandlerMapBinder.addBinding(ResourceTypeConstants.PIPELINE).to(PipelineOutboxEventHandler.class);
> ```

InputSet events will have resourceType=INPUT_SET, So we need to add a binding for inputSet events as well. And can you test the pipeline and inputSet audits flow?
___
*[800-pipeline-service/src/main/java/io/harness/pms/outbox/PMSOutboxEventHandler.java, line 33 at r1](https://reviewable.io/reviews/harness/harness-core/31021#-MwywXsq0o1bJgogDo65:-MwywXsq0o1bJgogDo66:bkeowdh) ([raw file](https://github.com/harness/harness-core/blob/477d3bac79f8a945bfd90df583d1fd489c59e82a/800-pipeline-service/src/main/java/io/harness/pms/outbox/PMSOutboxEventHandler.java#L33)):*
> ```Java
>   public boolean handle(OutboxEvent outboxEvent) {
>     try {
>       OutboxEventHandler handler = outboxEventHandlerMap.get(outboxEvent.getResource().getType());
> ```

Currently this would be null for inputSet and input set audits will be skiped. Please test pipeline and inputset audit flows are working properly after adding the inputset binding in pipelineServiceModule.


<!-- Sent from Reviewable.io -->

2022-02-28 08:51 UTC, devkimittal commented
@brijeshdhakar Can you please check now?

2022-02-28 08:54 UTC, vistaarjuneja commented on 800-pipeline-service/src/main/java/io/harness/pms/outbox/PMSOutboxEventHandler.java
> +          String.format("Unexpected error occurred during handling event of type %s", outboxEvent.getEventType()));
Print the error as well

2022-02-28 08:54 UTC, vistaarjuneja commented on 800-pipeline-service/src/main/java/io/harness/pms/outbox/PMSOutboxEventHandler.java
> +      return false;
`return false` can be outside of both the try-catches

2022-02-28 08:54 UTC, vistaarjuneja commented on 800-pipeline-service/src/test/resources/trigger_new.yml
> +          infrastructureDefinition:
Indentation required?

2022-02-28 08:54 UTC, vistaarjuneja commented on 800-pipeline-service/src/test/resources/trigger_old.yml
> +          infrastructureDefinition:
Indentation required?

2022-02-28 08:56 UTC, brijeshdhakar reviewed
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31021)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-02-28 09:03 UTC, devkimittal commented on 800-pipeline-service/src/test/resources/trigger_new.yml
> +          infrastructureDefinition:
easy to look at

2022-02-28 09:10 UTC, vistaarjuneja submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31021#-:-Mwza9iK08VMHYVkdNiz:bnfp4nl)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-28 10:00 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 4 files at r1, 4 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31021)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-02-28 10:06 UTC, harshjain12 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r1, 5 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31021#-:-MwzmooF8d1CT-82MmxE:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-01 04:09 UTC, diptiman-adak commented
trigger ti0

2022-03-01 05:19 UTC, devkimittal commented
trigger ti0

2022-03-02 10:43 UTC, devkimittal commented
trigger ti0

2022-03-02 10:45 UTC, devkimittal commented
trigger ti0

2022-03-02 11:10 UTC, harshjain12 commented
trigger messagecheck

2022-03-02 11:13 UTC, merged