techdebt: [CDS-2952]: Completed the backend to fetch Values.yaml Files within collected Helm Chart"
harness/harness-core pull request #31067
Opened 2022-02-28 12:28 UTC by GoelPratyush99

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-01 09:45 UTC, achyuth-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 22 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 406 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3n8UWCP_zQMZ5QG-I:-Mx3n8UWCP_zQMZ5QG-J:b-jyz10s) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L406)):*
> ```Java
> 
>   // Aggregated Manifest methods of type chartValueStore. Here using get(0) as we are assuming only the case to override
>   // yaml file from same chart only.
> ```

nit: comment can be more clear
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java, line 299 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3np9cBwElfexl-UUI:-Mx3np9cBwElfexl-UUJ:b-9ruqoe) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L299)):*
> ```Java
>                                    .closeLogStream(!isAnyRemoteStore(aggregatedValuesManifests))
>                                    .build();
>     }
> ```

duplicated code. u can do something like:

      helmValuesFetchRequest = HelmValuesFetchRequest.builder()
                                   .accountId(accountId)
                                   .helmChartManifestDelegateConfig(helmManifest)
                                   .timeout(CDStepHelper.getTimeoutInMillis(stepElementParameters))
                                   .closeLogStream(!isAnyRemoteStore(aggregatedValuesManifests))
                                   .build();

if(chartValuesStoreManifest != null)
      helmValuesFetchRequest.setpaths(...)
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java, line 446 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3oKEy5xvELSkffjrd:-Mx3oKEy5xvELSkffjre:b-cb2yp3) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L446)):*
> ```Java
>                                    .helmChartManifestDelegateConfig(helmManifest)
>                                    .timeout(CDStepHelper.getTimeoutInMillis(stepElementParameters))
>                                    .build();
> ```

duplicated code here too. set paths only if chartValuesStoreManifest!=null
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 705 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3r8C414OLxtErvWoG:-Mx3r8C414OLxtErvWoH:b-xy9qy9) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L705)):*
> ```Java
>     List<String> valueFileContent = new ArrayList<>();
>     valueFileContent.add(
>         new String(Files.readAllBytes(Paths.get(getChartDirectory(workingDirectory, chartName), VALUES_YAML))));
> ```

why have we removed this?  "StandardCharsets.UTF_8" before it was like this:

String(Files.readAllBytes(Paths.get(getChartDirectory(workingDirectory, chartName), VALUES_YAML)),
        StandardCharsets.UTF_8);

lets have the same behaviour


<!-- Sent from Reviewable.io -->

2022-03-01 09:49 UTC, abosii-harness requested changes
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 419 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3lb-d-9h1jfF_EJSv:-Mx3lb-d-9h1jfF_EJSw:bmzp49v) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L419)):*
> ```Java
> 
>     if (isNotEmpty(aggregateChartValuesManifest)) {
>       return aggregateChartValuesManifest.get(0);
> ```

I'm not getting this. We're somehow prohibiting customer to provide multiple HelmChartValues? Is this some artificial requirements? Having multiple values manifests should be a valid use case. For example customer has multi stage deployment and want to add new values file only for second stage additional to existing ones. Without this support, customer will have to override existing HelmChartValues and add all files, it's not really friendly. And I don't see any limits why we shouldn't support this. 
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java, line 272 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3mrHZ8npNWWHMdbLY:-Mx3mrHZ8npNWWHMdbLZ:bqsijeb) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L272)):*
> ```Java
>         (HelmChartManifestDelegateConfig) getManifestDelegateConfig(helmChartManifestOutcome, ambiance);
>     /*
>     Check if it ValueManifest is of Store type ValueChart
> ```

nit: the code is self descriptive, I don't see a need for this comment that basically is a pseudo-code 
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java, line 431 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3rH3DCZqEMoMM3mQZ:-Mx3rH3DCZqEMoMM3mQ_:b-4gr7jj) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L431)):*
> ```Java
>         CDStepHelper.getAggregatedValuesManifestsTypeChartValueStore(aggregatedValuesManifests);
>     HelmValuesFetchRequest helmValuesFetchRequest;
>     if (chartValuesStoreManifest != null) {
> ```

Just as suggestion, in K8s we're creating a new ValuesManifestOutcome for values.yaml so the code doesn't really care about doing additional checks. Maybe we can have something similar here. Let me know if you want to sync on this to get more details
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestStep.java, line 117 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3qXhn0pYAnMrjHsgg:-Mx3qXhn0pYAnMrjHsgh:b7tutok) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestStep.java#L117)):*
> ```Java
>     // In some cases (eg. in k8s manifests) we're skipping auto evaluation, in this case we can skip connector
>     // validation for now. It will be done when all expression will be resolved
>     if (manifestAttributes.getStoreConfig().getKind().equals("HelmChartValues")) {
> ```

Can we use ManifestStoreType here? (not sure if is available)
___
*[125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java, line 195 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3qrF8BzM4AMrxRqox:-Mx3qrF8BzM4AMrxRqoy:bahm9e7) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L195)):*
> ```Java
>     kryo.register(HelmValuesFetchResponsePassThroughData.class, 12544);
>     kryo.register(StepExceptionPassThroughData.class, 12545);
>     kryo.register(HelmChartValuesStoreConfig.class, 12564);
> ```

should we add this at the end of block? After ShhServiceSpec? And I'm not sure why you can't use 12563? Is this used somewhere else, I can't find it
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 677 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3pRvp9dt87HRgrDtb:-Mx3pRvp9dt87HRgrDtc:b-wtqymk) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L677)):*
> ```Java
>       printHelmChartInfoWithVersionInExecutionLogs(workingDirectory, helmChartManifestDelegateConfig, logCallback);
> 
>       List<String> valuesFileContent = readValuesYamlFromChartFiles(
> ```

Let's double check how we're handling here if file doesn't exists. This null check doesn't make sense (it didn't make sense before either). But the idea is that if you're trying default values.yaml it shouldn't fail, in case of  helmChartValuesPaths it should fail. And let's provide a better error in case of file doesn't exist in helm chart (showing the exact file what is missing and the manifest identifier)
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchRequest.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3nl0Q6L-bdiiWy4Rc:-Mx3nl0Q6L-bdiiWy4Rd:bylmw9w) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchRequest.java#L43)):*
> ```Java
>   private HelmChartManifestDelegateConfig helmChartManifestDelegateConfig;
>   private boolean closeLogStream;
>   private List<String> paths;
> ```

This is more about additional to my comment that we should support multiple values manifests. In this case, will make more sense to have a list of complex object, i.e. { List<String> paths, String identifier } so we could provide more verbose logs (ex: Fetching files for manifest with id <id>) and better error (ex: Failed to fetch file <file> for manifest with id <id>) 
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchResponse.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3lNGZDGnJHdG64qSX:-Mx3lNGZDGnJHdG64qSY:b-ofbuqk) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchResponse.java#L30)):*
> ```Java
>   private String errorMessage;
>   private UnitProgressData unitProgressData;
>   private List<String> valuesFileContent;
> ```

Breaks backward compatibility, we should have a new field here


<!-- Sent from Reviewable.io -->

2022-03-01 10:28 UTC, tchaurasiya commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 409 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx4055s4dAQwWWTaWCZ:-Mx4055s4dAQwWWTaWC_:b-1pls7n) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L409)):*
> ```Java
>   public static ValuesManifestOutcome getAggregatedValuesManifestsTypeChartValueStore(
>       List<ValuesManifestOutcome> aggregatedValuesManifests) {
>     if (aggregatedValuesManifests.isEmpty()) {
> ```

can we use io.harness.data.structure.EmptyPredicate.isEmpty() in place of aggregatedValuesManifests.isEmpty()


<!-- Sent from Reviewable.io -->

2022-03-01 10:54 UTC, tchaurasiya commented
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java, line 446 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3oKEy5xvELSkffjrd:-Mx46H4k2mQzsThcT9yv:b-pmch5m) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L446)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

duplicated code here too. set paths only if chartValuesStoreManifest!=null
</blockquote></details>

 .paths(chartValuesStoreManifest==null ? null :  getParameterFieldValue(helmChartValuesStoreConfig.getPaths()))


<!-- Sent from Reviewable.io -->

2022-03-02 15:15 UTC, GoelPratyush99 commented
@abosii-harness I have re-written the code incorporating changes to enable overriding of values.yaml for Multistage Deployment. Also I have made the code backward compatible.

@achyuth-harness @tchaurasiya @abosii-harness Kindly review the code again.

2022-03-03 06:17 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 21 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 409 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx4055s4dAQwWWTaWCZ:-MxDLDCkBJolSNZTMqmp:b-uuy7ob) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L409)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

can we use io.harness.data.structure.EmptyPredicate.isEmpty() in place of aggregatedValuesManifests.isEmpty()
</blockquote></details>

Implemented this suggesting in new code
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 419 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3lb-d-9h1jfF_EJSv:-MxDLIDF0GYAlTOqRWwc:bi2gr4t) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L419)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm not getting this. We're somehow prohibiting customer to provide multiple HelmChartValues? Is this some artificial requirements? Having multiple values manifests should be a valid use case. For example customer has multi stage deployment and want to add new values file only for second stage additional to existing ones. Without this support, customer will have to override existing HelmChartValues and add all files, it's not really friendly. And I don't see any limits why we shouldn't support this. 
</blockquote></details>

Changed the complete code to incorporate a multi-stage deployment for customers.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java, line 299 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3np9cBwElfexl-UUI:-MxDLMJwDjY7DKLBlRrn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L299)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

duplicated code. u can do something like:

      helmValuesFetchRequest = HelmValuesFetchRequest.builder()
                                   .accountId(accountId)
                                   .helmChartManifestDelegateConfig(helmManifest)
                                   .timeout(CDStepHelper.getTimeoutInMillis(stepElementParameters))
                                   .closeLogStream(!isAnyRemoteStore(aggregatedValuesManifests))
                                   .build();

if(chartValuesStoreManifest != null)
      helmValuesFetchRequest.setpaths(...)
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java, line 431 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3rH3DCZqEMoMM3mQZ:-MxDPEDrEzVI7ccBkDSv:brlf3dc) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L431)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Just as suggestion, in K8s we're creating a new ValuesManifestOutcome for values.yaml so the code doesn't really care about doing additional checks. Maybe we can have something similar here. Let me know if you want to sync on this to get more details
</blockquote></details>

Removed it
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java, line 446 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3oKEy5xvELSkffjrd:-MxDPSkw9YbJAXtRGr9C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L446)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

 .paths(chartValuesStoreManifest==null ? null :  getParameterFieldValue(helmChartValuesStoreConfig.getPaths()))
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestStep.java, line 117 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3qXhn0pYAnMrjHsgg:-MxDPXWxAqFNRV57YD4y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestStep.java#L117)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we use ManifestStoreType here? (not sure if is available)
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java, line 195 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3qrF8BzM4AMrxRqox:-MxDP__XB7BwaYozG2Os:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L195)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

should we add this at the end of block? After ShhServiceSpec? And I'm not sure why you can't use 12563? Is this used somewhere else, I can't find it
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 677 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3pRvp9dt87HRgrDtb:-MxDPdSt91vMNjZLWtib:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L677)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's double check how we're handling here if file doesn't exists. This null check doesn't make sense (it didn't make sense before either). But the idea is that if you're trying default values.yaml it shouldn't fail, in case of  helmChartValuesPaths it should fail. And let's provide a better error in case of file doesn't exist in helm chart (showing the exact file what is missing and the manifest identifier)
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 705 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3r8C414OLxtErvWoG:-MxDPguc7LH_UD4oRPuL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L705)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

why have we removed this?  "StandardCharsets.UTF_8" before it was like this:

String(Files.readAllBytes(Paths.get(getChartDirectory(workingDirectory, chartName), VALUES_YAML)),
        StandardCharsets.UTF_8);

lets have the same behaviour
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchRequest.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31067#-Mx3nl0Q6L-bdiiWy4Rc:-MxDPmyhCdv2lEs4I4er:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2d8c6cc4a31c012276ef2847534712b9d09bd92/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchRequest.java#L43)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is more about additional to my comment that we should support multiple values manifests. In  [...]

2022-03-03 06:30 UTC, abosii-harness requested changes
> Reviewed 19 of 21 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java, line 547 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQ-2d5D2rVWDqqgpL:-MxDQ-2d5D2rVWDqqgpM:b-bhabai) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L547)):*
> ```Java
>           overrideValuesFileContent);
>     } else {
>       overrideValuesFileContent.add(valuesFileContent);
> ```

Can we do the same for isNotEmpty case? And store in passthrough data a list that will contain both list and values.yaml content
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepPassThroughData.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQK0sE7VX2e6ynD7h:-MxDQK0sE7VX2e6ynD7i:b-e8fig3) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepPassThroughData.java#L34)):*
> ```Java
>   InfrastructureOutcome infrastructure;
>   String helmValuesFileContent;
>   List<String> overrideHelmValuesFileContent;
> ```

Here we can use only overrideHelmValuesFileContent and remove helmValuesFileContent
___
*[125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java, line 219 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQdkP3ynI3LYCztZ1:-MxDQdkP3ynI3LYCztZ2:b-di9b5m) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L219)):*
> ```Java
>     kryo.register(NGVariableOverrideSets.class, 12560);
>     kryo.register(SshServiceSpec.class, 12561);
>     kryo.register(HelmChartValuesStoreConfig.class, 12563);
> ```

I think the next would be 12562, sorry for confusion
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 678 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDRRoA3c6AmWKHDQcD:-MxDRRoA3c6AmWKHDQcE:bdrgmea) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L678)):*
> ```Java
>       printHelmChartInfoWithVersionInExecutionLogs(workingDirectory, helmChartManifestDelegateConfig, logCallback);
> 
>       String valuesFileContent = readValuesYamlFromChartFiles(workingDirectory,
> ```

Since now this will throw an exception if file is not where, shouldn't we try to catch to ignore? If values.yaml fails with not found it should be ignored
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 701 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDRqtY2bCcJgMIfM-F:-MxDRqtY2bCcJgMIfM-G:b-j5ja47) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L701)):*
> ```Java
>         }
>       }
>       return Arrays.asList(valuesFileContent, helmChartValuesFileContent);
> ```

This will end in a list having 2 elements (String, List<String>), it doesn't look like a good idea. Maybe we could add all values in a single List<String> and have valuesFileContent for backward compatibility and in this case null? So on manager you could have a check if (valuesFileContent == null) use_helmChartValuesFileContent else use_valuesFileContent
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 727 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQz82DYuH3KbfHM31:-MxDQz82DYuH3KbfHM32:b-oeuf1e) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L727)):*
> ```Java
>       } catch (Exception ex) {
>         String errorMsg = format("Failed to fetch %s file ", path);
>         logCallback.saveExecutionLog(errorMsg + ExceptionUtils.getMessage(ex), WARN);
> ```

It does look like this is unnecessary since you'll catch it later anyway and this will result in 2 logs line for the same flow
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java, line 85 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDSgn38MvGGfan8gDv:-MxDSgn48gH2be1UHg7f:bujwhdb) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java#L85)):*
> ```Java
>           .valuesFileContent((String) fileContentList.get(0))
>           .helmChartValuesFileContent(
>               isEmpty((List<String>) fileContentList.get(1)) ? emptyList() : (List<String>) fileContentList.get(1))
> ```

This can't be empty, otherwise String) fileContentList.get(0) would throw 


<!-- Sent from Reviewable.io -->

2022-03-03 10:49 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 2 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 678 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDRRoA3c6AmWKHDQcD:-MxENE810bm2D4BLAMo5:b-qgcvc5) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L678)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Since now this will throw an exception if file is not where, shouldn't we try to catch to ignore? If values.yaml fails with not found it should be ignored
</blockquote></details>

Shouldn't we throw error if values.yaml file is not found why should we ignore it and return empty list instead?


<!-- Sent from Reviewable.io -->

2022-03-03 16:53 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 2 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java, line 547 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQ-2d5D2rVWDqqgpL:-MxFgf0W-GZWkx2qpQpU:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L547)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we do the same for isNotEmpty case? And store in passthrough data a list that will contain both list and values.yaml content
</blockquote></details>

Done
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepPassThroughData.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQK0sE7VX2e6ynD7h:-MxFghEq0m_BuxEZbrWe:b-va8vtb) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepPassThroughData.java#L34)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Here we can use only overrideHelmValuesFileContent and remove helmValuesFileContent
</blockquote></details>

Done the same for k8sStepPassThroughData as well
___
*[125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java, line 219 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQdkP3ynI3LYCztZ1:-MxFgrWp-mty4Prejs9b:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L219)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I think the next would be 12562, sorry for confusion
</blockquote></details>

Done
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 701 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDRqtY2bCcJgMIfM-F:-MxFbsvj-C32IaOzodTQ:bol60yi) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L701)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This will end in a list having 2 elements (String, List<String>), it doesn't look like a good idea. Maybe we could add all values in a single List<String> and have valuesFileContent for backward compatibility and in this case null? So on manager you could have a check if (valuesFileContent == null) use_helmChartValuesFileContent else use_valuesFileContent
</blockquote></details>

Taken care off. We are now populating the helmCHartValuesFileContent only valuesFileContent will be null
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 727 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDQz82DYuH3KbfHM31:-MxFgX6s4bgIyZtO4Omk:brlf3dc) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L727)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

It does look like this is unnecessary since you'll catch it later anyway and this will result in 2 logs line for the same flow
</blockquote></details>

Removed it
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java, line 85 at r3](https://reviewable.io/reviews/harness/harness-core/31067#-MxDSgn38MvGGfan8gDv:-MxFgZuGAZABm2g_haaZ:b5vuhjn) ([raw file](https://github.com/harness/harness-core/blob/2e1c182bcdcf155cb9a72c2281723f1b6c1cc26c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java#L85)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This can't be empty, otherwise String) fileContentList.get(0) would throw 
</blockquote></details>

Removed it. It will always null now


<!-- Sent from Reviewable.io -->

2022-03-07 05:38 UTC, achyuth-harness reviewed
> Reviewed 3 of 3 files at r4, 10 of 11 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 2 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-07 05:39 UTC, achyuth-harness reviewed
> Reviewed 6 of 22 files at r1, 6 of 21 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 2 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-07 05:41 UTC, achyuth-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: Some of the checks are too old. 1 change requests. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-07 07:30 UTC, abosii-harness requested changes
> Reviewed 1 of 3 files at r4, 10 of 11 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java, line 533 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxYFdN995DpicH6ABLv:-MxYFdNADyzUAcus5UaK:b-rvkb6z) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L533)):*
> ```Java
> 
>     List<String> valuesFileContents = new ArrayList<>();
>     List<String> overrideValuesFileContent = new ArrayList<>(helmValuesFetchResponse.getHelmChartValuesFileContent());
> ```

We should handle the case when old delegate is sending helmValuesFileContent as well, ex: if helmValuesFetchResponse.getValuesFileContent() != null then valuesFileContents.add(helmValuesFetchResponse.getValuesFileContent()). And let's add an unit test for this as well
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java, line 794 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxYG8XC2UA4sNycm7rO:-MxYG8XC2UA4sNycm7rP:bds75ad) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L794)):*
> ```Java
>       return TaskChainResponse.builder().chainEnd(true).passThroughData(helmValuesFetchPassTroughData).build();
>     }
>     List<String> valuesFileContents = new ArrayList<>(helmValuesFetchResponse.getHelmChartValuesFileContent());
> ```

Same here, we should handle both for backward compatibility
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 686 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxIhMHd3OKS_ga2KmCa:-MxIhMHfCnNysYY5LBIl:b76jkqp) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L686)):*
> ```Java
>           helmChartValuesFileContents.addAll(valuesFileContent);
>           logCallback.saveExecutionLog("\nSuccessfully fetched values.yaml", INFO);
>         } catch (IOException ignored) {
> ```

nit: is not ignored but used later 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 690 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxYGRoQC6mprlF0VMGL:-MxYGRoQC6mprlF0VMGM:bfe6wnd) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L690)):*
> ```Java
>         }
>       } else {
>         String errorMsg = format("\n Unable to find values.yaml in %s chart directory", chartDirectory);
> ```

Let's make the error less 'error like' to not confuse anyone, for example: No values.yaml found in %s chart directory
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java, line 82 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxIhdav7B0tUVvtQOIX:-MxIhdav7B0tUVvtQOIY:b-a7rkmn) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java#L82)):*
> ```Java
>           .commandExecutionStatus(SUCCESS)
>           .unitProgressData(UnitProgressDataMapper.toUnitProgressData(commandUnitsProgress))
>           .valuesFileContent(null)
> ```

nit: field by default will be null, no need to set it


<!-- Sent from Reviewable.io -->

2022-03-08 06:13 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31067)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java, line 533 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxYFdN995DpicH6ABLv:-Mxc93ZK6W-vNeSZR7wX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L533)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We should handle the case when old delegate is sending helmValuesFileContent as well, ex: if helmValuesFetchResponse.getValuesFileContent() != null then valuesFileContents.add(helmValuesFetchResponse.getValuesFileContent()). And let's add an unit test for this as well
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java, line 794 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxYG8XC2UA4sNycm7rO:-Mxc9Acp4jMK1ssRrt9g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L794)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, we should handle both for backward compatibility
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 690 at r6](https://reviewable.io/reviews/harness/harness-core/31067#-MxYGRoQC6mprlF0VMGL:-Mxc9DX15OYfHphhSDnN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb92ec51c058414f96c5530a904627fe2fc1f091/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L690)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's make the error less 'error like' to not confuse anyone, for example: No values.yaml found in %s chart directory
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-06 10:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31067) before we can accept your contribution.<br/>**0** out of **26** committers have signed the CLA.<br/><br/>:x: arpit3107<br/>:x: archit-harness<br/>:x: mohitg0795<br/>:x: abhinav-harness<br/>:x: rathodmeetsatish<br/>:x: namantalaycha10<br/>:x: GoelPratyush99<br/>:x: aman-harness<br/>:x: gupta-utkarsh<br/>:x: atharvatrivedi1<br/>:x: harshjain12<br/>:x: Xin-Harness<br/>:x: mdmilic<br/>:x: puthrayaharness<br/>:x: jennyjames21<br/>:x: sahilhindwani-harness<br/>:x: DeepakPatankar<br/>:x: boopesh007<br/>:x: Rohit-Kaliki<br/>:x: shivamnegi94<br/>:x: prashantsharma04<br/>:x: gaurav-jain1<br/>:x: brijeshdhakar<br/>:x: praveensugavanam<br/>:x: riyasyash<br/>:x: reetika04<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31067) it.</sub>

2022-04-06 10:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31067) before we can accept your contribution.<br/>**0** out of **26** committers have signed the CLA.<br/><br/>:x: namantalaycha10<br/>:x: mohitg0795<br/>:x: abhinav-harness<br/>:x: GoelPratyush99<br/>:x: sahilhindwani-harness<br/>:x: rathodmeetsatish<br/>:x: DeepakPatankar<br/>:x: aman-harness<br/>:x: arpit3107<br/>:x: atharvatrivedi1<br/>:x: archit-harness<br/>:x: puthrayaharness<br/>:x: prashantsharma04<br/>:x: harshjain12<br/>:x: Xin-Harness<br/>:x: mdmilic<br/>:x: jennyjames21<br/>:x: riyasyash<br/>:x: praveensugavanam<br/>:x: gupta-utkarsh<br/>:x: Rohit-Kaliki<br/>:x: gaurav-jain1<br/>:x: boopesh007<br/>:x: shivamnegi94<br/>:x: reetika04<br/>:x: brijeshdhakar<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31067) it.</sub>

2022-05-30 08:49 UTC, closed without merging