feat: [CDS-33891]: Added PDC connector
harness/harness-core pull request #31100
Opened 2022-03-01 15:16 UTC by ivan-83

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-01 16:21 UTC, vladimir-peric submitted a review, later dismissed
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-01 19:40 UTC, filip5rovic commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java
> +      return hostParts[1];
Not sure what input can be, but maybe trimming and checking whether `hostParts[1]` is the number

2022-03-01 19:43 UTC, filip5rovic commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java
> +    return Arrays.asList(trimHostNames.split(","));
Should we be worrying if hosts are separated by comma and space - ", "? If so, trimming parts after split could be nice to have.

2022-03-01 19:44 UTC, filip5rovic reviewed
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-09 12:15 UTC, vitsafronovici commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/pdcconnector/HostDTOsDeserializer.java
> +    String[] hostsArr = hosts.replace("\n", ",").split(",");
replace() creates an extra String object. Maybe to use:
Pattern.compile("\n") .splitAsStream(str) .map(s -> s.split(",")) .flatMap(Arrays::stream) .toArray(String[]::new);

2022-03-15 19:08 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 71 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java, line 102 at r4](https://reviewable.io/reviews/harness/harness-core/31100#-MxL38s_t-NFB38U4_ln-r4-102:-MyDx5S62QbBioOMBxX5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e97950675561dbbc048bb0e7a7a44e741b760b2f/120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java#L102)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

light validations should go first, 
`isBlank(host)` check should go before  `ngSecretServiceV2.get(...)` api call.
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/31100#-Mx52QJ0cSd-264d4DuZ-r1-20:-MyDxCWo55-xRIJ14LnC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44fc93b58df79808ca47ab8f745197640ece78fe/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java#L20)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

Should we be worrying if hosts are separated by comma and space - ", "? If so, trimming parts after split could be nice to have.
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/31100#-Mx52QJ0cSd-264d4DuZ-r1-30:-MyDxFEN9m_37PdWIaez:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44fc93b58df79808ca47ab8f745197640ece78fe/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java#L30)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

Not sure what input can be, but maybe trimming and checking whether `hostParts[1]` is a number
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java, line 11 at r4](https://reviewable.io/reviews/harness/harness-core/31100#-Mx52QJ0cSd-264d4DuZ-r4-11:-MyDy9tt2FOxxfXorX49:b-hqxfzi) ([raw file](https://github.com/harness/harness-core/blob/e97950675561dbbc048bb0e7a7a44e741b760b2f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java#L11)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

may be change signature of method and `DEFAULT_SSH_PORT ` to be `long`
</blockquote></details>

We use this method to create SocketConnectivityCapability by using SocketConnectivityCapabilityGenerator which requires a string and because of it, we are returning the string. 
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/pdcconnector/HostDTOsDeserializer.java, line 56 at r4](https://reviewable.io/reviews/harness/harness-core/31100#-MxYyE4wt0zNo3aCa7NB-r4-56:-MyDxHvR5sg_FsU3COCt:b-lq28ru) ([raw file](https://github.com/harness/harness-core/blob/e97950675561dbbc048bb0e7a7a44e741b760b2f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/pdcconnector/HostDTOsDeserializer.java#L56)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

replace() creates an extra String object. Maybe to use:
Pattern.compile("\n") .splitAsStream(str) .map(s -> s.split(",")) .flatMap(Arrays::stream) .toArray(String[]::new);
</blockquote></details>

I agree, it will create a new string object that could be taken from the string pool.  The currently used solution is more readable. 


<!-- Sent from Reviewable.io -->

2022-03-16 10:18 UTC, acasian-harness reviewed
> Reviewed 5 of 14 files at r1, 1 of 9 files at r2, 7 of 12 files at r3, 3 of 4 files at r4, 14 of 26 files at r5, 1 of 7 files at r6, 3 of 8 files at r7, 16 of 18 files at r8, 4 of 9 files at r9, 11 of 13 files at r10, 3 of 5 files at r11, 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java, line 87 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyH9Cw10bh6eicdpU2u:-MyH9Cw10bh6eicdpU2v:b-mwvtdd) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java#L87)):*
> ```Java
>       @RequestBody(required = true, description = "List of SSH hosts to validate") @NotNull List<String> hosts) {
>     return ResponseDTO.newResponse(hostValidationService.validateSSHHosts(
>         hosts, accountIdentifier, orgIdentifier, projectIdentifier, secretIdentifier));
> ```

do we need any rbac checks on that endpoint?
___
*[120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java, line 85 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyH9TyL-g-hOwbKLYeu:-MyH9TyL-g-hOwbKLYev:b6ye1gm) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java#L85)):*
> ```Java
>     }
> 
>     log.info("Start validation hosts: {}", StringUtils.join(hosts));
> ```

we might have here 100 of hosts, are we sure we want to display those in the logs?
___
*[120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java, line 182 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHAWKH63_kNPgcPV8x:-MyHAWKH63_kNPgcPV8y:b-ebrck4) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java#L182)):*
> ```Java
> 
>   @NotNull
>   private List<String> limitHosts(@NotNull List<String> hosts) {
> ```

we need to document this, let's ask Meenakshi on that.
___
*[120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java, line 27 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHB5BB2BuTub8592f3:-MyHB5BB2BuTub8592f4:b-b5ndry) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java#L27)):*
> ```Java
> 
> @RunWith(MockitoJUnitRunner.class)
> @OwnedBy(HarnessTeam.PL)
> ```

this should be CDP
___
*[120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java, line 35 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHB8d_CmvRosGcFovJ:-MyHB8d_CmvRosGcFovK:b49wf35) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java#L35)):*
> ```Java
>   @Owner(developers = VLAD)
>   @Category(UnitTests.class)
>   public void shouldValidateSshHosts() {
> ```

can we add negative scenarious also: secret is missing, host validation fails for some of the hosts and all hosts.
___
*[120-ng-manager/src/test/java/io/harness/ng/validator/service/HostValidationServiceImplTest.java, line 46 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBOz84pEWTuQx3zyx:-MyHBOz84pEWTuQx3zyy:b2nhbsa) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/test/java/io/harness/ng/validator/service/HostValidationServiceImplTest.java#L46)):*
> ```Java
> 
> 
> @OwnedBy(HarnessTeam.CDC)
> ```

CDP
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/featureFlag/CdEnumFilter.java, line 17 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBVWq8F_F6VPI459z:-MyHBVWq8F_F6VPI45A-:b-6hcrxo) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/125-cd-nextgen/src/main/java/io/harness/cdng/featureFlag/CdEnumFilter.java#L17)):*
> ```Java
> import com.google.inject.Singleton;
> 
> @Singleton
> ```

missing owner
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/PdcInfraMapping.java, line 26 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBibs1oIh-pyScBl0:-MyHBibs1oIh-pyScBl1:b2nhbsa) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/PdcInfraMapping.java#L26)):*
> ```Java
> @TypeAlias("PdcInfraMapping")
> @JsonTypeName("PdcInfraMapping")
> @OwnedBy(CDC)
> ```

CDP
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/PdcInfrastructure.java, line 43 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBoVl4ybfzopXhktZ:-MyHBoVl4ybfzopXhkt_:b2nhbsa) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/PdcInfrastructure.java#L43)):*
> ```Java
> import org.springframework.data.annotation.TypeAlias;
> 
> @OwnedBy(CDC)
> ```

CDP
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/HostAttribute.java, line 13 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCGPFDkdZQlCsGFtD:-MyHCGPFDkdZQlCsGFtE:blz8kxu) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/HostAttribute.java#L13)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @TypeAlias("io.harness.connector.entities.embedded.pdcconnector.HostAttribute")
> public class HostAttribute {
> ```

owner is missing
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/PhysicalDataCenterConnector.java, line 23 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCK5D4vRb0lA0xTiJ:-MyHCK5D4vRb0lA0xTiK:b-qk4ct7) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/PhysicalDataCenterConnector.java#L23)):*
> ```Java
> @Persistent
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @TypeAlias("io.harness.connector.entities.embedded.pdcconnector.PhysicalDataCenterConnector")
> ```

owner is missing also
___
*[440-connector-nextgen/src/main/java/io/harness/connector/featureflagfilter/ConnectorEnumFilter.java, line 18 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCMR4ChX_nU7qbF8Q:-MyHCMR4ChX_nU7qbF8R:blz8kxu) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/featureflagfilter/ConnectorEnumFilter.java#L18)):*
> ```Java
> 
> @Singleton
> public class ConnectorEnumFilter extends EnumFeatureFlagFilter {
> ```

owner is missing
___
*[440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/PhysicalDataCenterConnectorValidationParamsProvider.java, line 8 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCO8F0zW3-KrdDVcK:-MyHCO8F0zW3-KrdDVcL:blz8kxu) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/PhysicalDataCenterConnectorValidationParamsProvider.java#L8)):*
> ```Java
> import io.harness.delegate.beans.connector.pdcconnector.PhysicalDataCenterConnectorValidationParams;
> 
> public class PhysicalDataCenterConnectorValidationParamsProvider i [...]

2022-03-16 20:23 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 42 file(s) to review. 39. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java, line 87 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyH9Cw10bh6eicdpU2u:-MyJNhdL7L7KMpoiTtE6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java#L87)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

do we need any rbac checks on that endpoint?
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java, line 85 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyH9TyL-g-hOwbKLYeu:-MyJNj7RAdJEoa5Sdv5C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java#L85)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we might have here 100 of hosts, are we sure we want to display those in the logs?
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java, line 182 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHAWKH63_kNPgcPV8x:-MyJNlAtAnG0eP0BMIeC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/main/java/io/harness/ng/validator/service/HostValidationServiceImpl.java#L182)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we need to document this, let's ask Meenakshi on that.
</blockquote></details>

Done.
___
*[120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java, line 27 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHB5BB2BuTub8592f3:-MyJNn6H-I9a5OX4hOgG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java#L27)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

this should be CDP
</blockquote></details>

Done.
___
*[120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java, line 35 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHB8d_CmvRosGcFovJ:-MyJNotv9m9id7QoEt5q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/test/java/io/harness/ng/core/remote/HostValidationResourceTest.java#L35)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

can we add negative scenarious also: secret is missing, host validation fails for some of the hosts and all hosts.
</blockquote></details>

Done.
___
*[120-ng-manager/src/test/java/io/harness/ng/validator/service/HostValidationServiceImplTest.java, line 46 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBOz84pEWTuQx3zyx:-MyJNtey-pT8Q-PRhGop:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/120-ng-manager/src/test/java/io/harness/ng/validator/service/HostValidationServiceImplTest.java#L46)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

CDP
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/featureFlag/CdEnumFilter.java, line 17 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBVWq8F_F6VPI459z:-MyJNvnk2QyGsYV2iIrS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/125-cd-nextgen/src/main/java/io/harness/cdng/featureFlag/CdEnumFilter.java#L17)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

missing owner
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/PdcInfraMapping.java, line 26 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBibs1oIh-pyScBl0:-MyJNxfP5BXf9V0kBP1l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/PdcInfraMapping.java#L26)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

CDP
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/PdcInfrastructure.java, line 43 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHBoVl4ybfzopXhktZ:-MyJNyma1tQcf6H5ffWi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/PdcInfrastructure.java#L43)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

CDP
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/HostAttribute.java, line 13 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCGPFDkdZQlCsGFtD:-MyJO0NNC1YtfLyxjWIM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/HostAttribute.java#L13)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

owner is missing
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/PhysicalDataCenterConnector.java, line 23 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCK5D4vRb0lA0xTiJ:-MyJO1u51dUl3N4hZj_B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/pdcconnector/PhysicalDataCenterConnector.java#L23)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

owner is missing also
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/featureflagfilter/ConnectorEnumFilter.java, line 18 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCMR4ChX_nU7qbF8Q:-MyJO2vI5MfDwRCAU_BI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/featureflagfilter/ConnectorEnumFilter.java#L18)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

owner is missing
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/PhysicalDataCenterConnectorValidationParamsProvider.java, line 8 at r12](https://reviewable.io/reviews/harness/harness-core/31100#-MyHCO8F0zW3-KrdDVcK:-MyJO3rm5hmy4WZmhIb4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff45d1e691c6d83ec400f53fbc797b549353f7fd/440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/PhysicalDataCenterConnectorValidationParamsProvider.java#L8)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

owner is missing
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/helper/CatalogueHelper.java, line 26 at r12](https://reviewable.io/reviews/harness/harness-cor [...]

2022-03-17 00:52 UTC, yogesh-chauhan requested changes
> Reviewed 1 of 9 files at r2, 7 of 26 files at r5, 1 of 7 files at r6, 14 of 18 files at r8, 1 of 9 files at r9, 6 of 13 files at r10, 1 of 5 files at r11, 4 of 8 files at r12, 38 of 42 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 4 file(s) to review. 1 change requests. 39. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java, line 93 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKJeiV8F60hyvg2hwg:-MyKJeiV8F60hyvg2hwh:bg77fva) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java#L93)):*
> ```Java
>       @RequestBody(required = true, description = "List of SSH hosts to validate") @NotNull List<String> hosts) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
>         Resource.of(USERGROUP, null), VIEW_USERGROUP_PERMISSION);
> ```

VIEW_USERGROUP_PERMISSION does not look correct. Shouldn't it be VIEW_ENV or something similar ?
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java, line 121 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKKMueAeOqq0YQt6vg:-MyKKMueAeOqq0YQt6vh:bji8bl5) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L121)):*
> ```Java
>       throw new InvalidArgumentsException(Pair.of("sshKeyRef", "cannot be empty"),
>           Pair.of("connectorRef", "cannot be empty"),
>           new IllegalArgumentException("sshKeyRef and connectorRef are not defined"));
> ```

we seem to be checking for hosts but the error message talks about sshKeyRef ( but not for hosts )
___
*[440-connector-nextgen/src/test/java/io/harness/connector/ConnectorTestConstants.java, line 14 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLS8uEcjmdof4NZNg:-MyKLS8uEcjmdof4NZNh:b-d1vz8h) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/440-connector-nextgen/src/test/java/io/harness/connector/ConnectorTestConstants.java#L14)):*
> ```Java
> import io.harness.annotations.dev.OwnedBy;
> 
> @OwnedBy(CDP)
> ```

field can be private 
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterConstants.java, line 15 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLg8i40Nugz2Vw16V:-MyKLg8i40Nugz2Vw16W:bn2qct4) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterConstants.java#L15)):*
> ```Java
> 
> @OwnedBy(CDP)
> public interface PhysicalDataCenterConstants {
> ```

fields can be private
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java, line 41 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLwAA1nr8V6evfzg3:-MyKLwAA1nr8V6evfzg4:b-1td6i9) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java#L41)):*
> ```Java
>     if (hostParts.length == 2) {
>       return isBlank(hostParts[0]) ? Optional.empty() : Optional.of(hostParts[0]);
>     }
> ```

better to parse this using some sdk. We use it already at some places. Something like a URI parser


<!-- Sent from Reviewable.io -->

2022-03-21 22:50 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 16 file(s) to review. 1 change requests. 41. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java, line 93 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKJeiV8F60hyvg2hwg:-Myieyx-3n3UkpOx7u8G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java#L93)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

VIEW_USERGROUP_PERMISSION does not look correct. Shouldn't it be VIEW_ENV or something similar ?
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java, line 121 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKKMueAeOqq0YQt6vg:-Myiezub15bcHfVV9Dmw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L121)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we seem to be checking for hosts but the error message talks about sshKeyRef ( but not for hosts )
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/test/java/io/harness/connector/ConnectorTestConstants.java, line 14 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLS8uEcjmdof4NZNg:-MyiTwXTCgJN4wGfSB8g:b-7h8l98) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/440-connector-nextgen/src/test/java/io/harness/connector/ConnectorTestConstants.java#L14)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

field can be private 
</blockquote></details>

Are you thinking of converting this interface into class?
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterConstants.java, line 15 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLg8i40Nugz2Vw16V:-MyiSlYT-qUfshPZ8Hnj:b-7h8l98) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterConstants.java#L15)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

fields can be private
</blockquote></details>

Are you thinking of converting this interface into class?
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java, line 41 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLwAA1nr8V6evfzg3:-MyiTQGf9tuyF_3D3mjr:b-7498si) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to parse this using some sdk. We use it already at some places. Something like a URI parser
</blockquote></details>

I see, I tested and it doesn’t work properly for the following hosts because URI parses hosts based on RFC 2396 syntax. 
https://stackoverflow.com/questions/64513631/uri-and-double-slashes

URI.create("localhost:8080”).getHost()
URI.create("localhost:8080”).getPort()
URI.create(“somehost:8080”).getHost()
URI.create(“somehost:8080”).getPort()
URI.create("localhost").getHost()
URI.create("somehost").getHost()


<!-- Sent from Reviewable.io -->

2022-03-21 23:31 UTC, yogesh-chauhan requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 16 file(s) to review. 1 change requests. 40. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java, line 93 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKJeiV8F60hyvg2hwg:-MyioQ2DDjFBoiIaGUQP:b-gieaau) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java#L93)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

are we not setting `resourceIdentifier` ? 
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterConstants.java, line 15 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLg8i40Nugz2Vw16V:-MyimZr61XjqizIIk1U9:b-xa0tfi) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterConstants.java#L15)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Are you thinking of converting this interface into class?
</blockquote></details>

yes.. https://stackoverflow.com/questions/29382728/constant-interface-anti-pattern-clarification
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java, line 41 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKLwAA1nr8V6evfzg3:-Myio3Qc6DQoiW-5nuAs:bvbi8by) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/PhysicalDataCenterUtils.java#L41)):*
> https://stackoverflow.com/questions/64513631/uri-and-double-slashes
Got it. Can we write tests for all the cases we handle as of now. 


<!-- Sent from Reviewable.io -->

2022-03-22 19:25 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 39 file(s) to review. 1 change requests. 41. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java, line 93 at r13](https://reviewable.io/reviews/harness/harness-core/31100#-MyKJeiV8F60hyvg2hwg:-Myn4d2e4iC96NJDseAl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c84c2c8d0701986e2c42530844e40fd1fceb2a7/120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java#L93)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we not setting `resourceIdentifier` ? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-23 08:03 UTC, yogesh-chauhan requested changes
> Reviewed 2 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 6 of 6 files at r17, 2 of 2 files at r18, 21 of 23 files at r19, 2 of 2 files at r20, 3 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 1 file(s) to review. 1 change requests. 40. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java, line 101 at r21](https://reviewable.io/reviews/harness/harness-core/31100#-Mypn206E9X5KNUGczdH:-Mypn207CBjCJCHQFfmB:bwrvkct) ([raw file](https://github.com/harness/harness-core/blob/2d6cc2796a12f7767e2700394ffec80e3e3ddbd8/120-ng-manager/src/main/java/io/harness/ng/core/remote/HostValidationResource.java#L101)):*
> ```Java
>         ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
>             Resource.of(SECRET_RESOURCE_TYPE, secretIdentifier),
>         SECRET_ACCESS_PERMISSION, secret != null ? secret.getSecret().getOwner() : null);
> ```

This does not look correct. Lets discuss offline



_Code quote:_
```Java
secretPermissionValidator.checkForAccessOrThrow
```


<!-- Sent from Reviewable.io -->

2022-03-23 18:11 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 2 files at r23, 16 of 16 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 39. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-23 18:12 UTC, yogesh-chauhan submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 39. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-23 20:09 UTC, acasian-harness approved these changes
> Reviewed 19 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 5 of 6 files at r17, 2 of 2 files at r18, 13 of 23 files at r19, 2 of 2 files at r20, 2 of 4 files at r21, 2 of 2 files at r23, 16 of 16 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 39. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-24 19:23 UTC, ivan-83 commented
trigger messagecheck

2022-03-25 07:27 UTC, acasian-harness approved these changes
> Reviewed 9 of 9 files at r25, 14 of 14 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 09:17 UTC, bojanmicovic approved these changes
> Reviewed 1 of 9 files at r2, 6 of 26 files at r5, 7 of 18 files at r8, 5 of 13 files at r10, 1 of 8 files at r12, 18 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 5 of 6 files at r17, 2 of 2 files at r18, 8 of 23 files at r19, 2 of 2 files at r20, 3 of 16 files at r24, 7 of 9 files at r25, 14 of 14 files at r26, 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 09:17 UTC, bojanmicovic approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 10:39 UTC, vladimir-peric approved these changes
> Reviewed 1 of 9 files at r2, 6 of 26 files at r5, 7 of 18 files at r8, 5 of 13 files at r10, 1 of 8 files at r12, 18 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 5 of 6 files at r17, 2 of 2 files at r18, 8 of 23 files at r19, 2 of 2 files at r20, 3 of 16 files at r24, 7 of 9 files at r25, 14 of 14 files at r26, 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 10:43 UTC, hextechpal reviewed
> Reviewed 1 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 10:46 UTC, vladimir-peric approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 10:53 UTC, acasian-harness approved these changes
> Reviewed 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 11:03 UTC, vitsafronovici reviewed
> Reviewed 1 of 9 files at r2, 6 of 26 files at r5, 7 of 18 files at r8, 5 of 13 files at r10, 1 of 8 files at r12, 18 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 5 of 6 files at r17, 2 of 2 files at r18, 8 of 23 files at r19, 2 of 2 files at r20, 3 of 16 files at r24, 7 of 9 files at r25, 14 of 14 files at r26, 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 11:11 UTC, vitsafronovici approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 11:12 UTC, filip5rovic reviewed
> Reviewed 1 of 9 files at r2, 6 of 26 files at r5, 7 of 18 files at r8, 5 of 13 files at r10, 1 of 8 files at r12, 18 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 5 of 6 files at r17, 2 of 2 files at r18, 8 of 23 files at r19, 2 of 2 files at r20, 3 of 16 files at r24, 7 of 9 files at r25, 14 of 14 files at r26, 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 11:14 UTC, filip5rovic approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-25 11:17 UTC, filip5rovic approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 11:17 UTC, filip5rovic approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 11:17 UTC, filip5rovic submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100#-:-Mz-n-ds-EL7Fpkiin46:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 11:32 UTC, abhinav-harness submitted a review, later dismissed
> Reviewed 1 of 9 files at r2, 6 of 26 files at r5, 7 of 18 files at r8, 5 of 13 files at r10, 1 of 8 files at r12, 18 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 5 of 6 files at r17, 2 of 2 files at r18, 8 of 23 files at r19, 2 of 2 files at r20, 3 of 16 files at r24, 7 of 9 files at r25, 14 of 14 files at r26, 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 11:42 UTC, vladimir-peric approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 11:52 UTC, hextechpal approved these changes
> Reviewed 1 of 9 files at r2, 6 of 26 files at r5, 7 of 18 files at r8, 4 of 13 files at r10, 1 of 8 files at r12, 18 of 42 files at r13, 2 of 8 files at r15, 1 of 6 files at r16, 5 of 6 files at r17, 2 of 2 files at r18, 8 of 23 files at r19, 2 of 2 files at r20, 3 of 16 files at r24, 7 of 9 files at r25, 14 of 14 files at r26, 2 of 2 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 14:26 UTC, vladimir-peric commented
trigger CheckStyle-checkstylecheck

2022-03-25 16:26 UTC, vladimir-peric submitted a review, later dismissed
> Reviewed 4 of 78 files at r28, 76 of 76 files at r29, 2 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 18:11 UTC, vladimir-peric commented
trigger codeformat

2022-03-25 18:54 UTC, vladimir-peric submitted a review, later dismissed
> Reviewed 1 of 1 files at r31, 8 of 8 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 19:46 UTC, ivan-83 commented
trigger ti1

2022-03-25 21:25 UTC, abhinav-harness approved these changes
> Reviewed 3 of 78 files at r28, 1 of 76 files at r29, 2 of 2 files at r30, 1 of 1 files at r31, 1 of 8 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-25 21:25 UTC, abhinav-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-26 02:16 UTC, hextechpal submitted a review, later dismissed
> Reviewed 3 of 78 files at r28, 1 of 76 files at r29, 2 of 2 files at r30, 1 of 1 files at r31, 1 of 8 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-26 10:43 UTC, hextechpal approved these changes
> Reviewed 1 of 8 files at r6, 1 of 6 files at r17, 2 of 27 files at r19, 74 of 76 files at r29, 7 of 8 files at r32, 2 of 2 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-26 12:20 UTC, ivan-83 commented
trigger ti4

2022-03-27 09:26 UTC, abhinav-harness approved these changes
> Reviewed 2 of 2 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-27 09:26 UTC, merged