feat: [PL-22724]: K8s Auth method for Hashicorp Vault
harness/harness-core pull request #31113
Opened 2022-03-02 05:43 UTC by VikasMaddukuriHarness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-11 04:42 UTC, shashank-harness commented
___
*[890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java, line 195 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-MxrGxFt6QB_7VlLRLHB:-MxrGxFt6QB_7VlLRLHC:bjeovkn) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java#L195)):*
> ```Java
>       if (isEmpty(vaultConfig.getDelegateSelectors())) {
>         throw new io.harness.exception.SecretManagementException(VAULT_OPERATION_ERROR,
>             "You must provide a delegate selector to read token if you are using K8s Auth method", USER);
> ```

Change message to below:
You must provide a delegate selector to read service account token if you are using K8s Auth method



_Code quote:_
```Java
You must provide a delegate selector to read token if you are using K8s Auth method
```


<!-- Sent from Reviewable.io -->

2022-03-11 04:55 UTC, shashank-harness commented
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java, line 138 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-MxrJzkz82C3cZrfHhQc:-MxrJzkz82C3cZrfHhQd:bj4df0w) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java#L138)):*
> ```Java
>           INVALID_REQUEST, USER);
>     }
>     if (isUseVaultAgent() && isUseK8sAuth()) {
> ```

Please check Boopesh has recently merged this change in which he hadded validations to this class too. Please check that they are not breaking yours before merging your PR.
https://github.com/harness/harness-core/pull/30961/files


<!-- Sent from Reviewable.io -->

2022-03-11 04:55 UTC, shashank-harness requested changes
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31113)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-11 05:22 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java
> +    return vaultConnector.isUseVaultAgent() || vaultConnector.getUseAwsIam() || vaultConnector.getUseK8sAuth();
For these types we should not be passing renewal time as well. Recently we made this field as mandatory from BE which is not actually required in these cases.
We can later check how to change this. Not blocking

2022-03-11 05:29 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
> +                                            .filter(x -> x.getAccessType() == AccessType.K8s_AUTH)
Rename x to meaningful name.

2022-03-11 05:33 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
> +    vaultK8sAuthRole.ifPresent(x -> {
instead of ifPresent use Map to loop through Optional.

2022-03-11 05:36 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
> +      vaultConfig.setSinkPath(null);
I think we don't need to set these field as null explicitly. Please check if removing this also works fine.

2022-03-11 05:40 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
> +            .filter(x -> !x.isEmpty());
if(specDTO!=null)
{
specDTO.getAccessType() ......
getServiceAccountTokenPath()
}

Can it we this ?

2022-03-11 05:43 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
> +    serviceAccountTokenPath.ifPresent(x -> { vaultConfig.setServiceAccountTokenPath(x); });
Rename x

2022-03-11 05:45 UTC, meenakshi-harness commented on 440-connector-nextgen/src/test/resources/schema/Connectors/all.json
> +            "serviceAccountTokenPath": {
We should these field as required here in case of specific auth type. Else creating via Yaml wont show error.

2022-03-11 05:50 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResponse.java
> +  @JsonProperty("lease_duration") private long leaseDuration;
leaseDuration

2022-03-11 05:50 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResult.java
> +  @JsonProperty("client_token") private String clientToken;
same

2022-03-11 05:56 UTC, meenakshi-harness commented on 940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/VaultK8sCredentialDTO.java
> +  private String serviceAccountTokenPath;
These should be NotNull. Check if this can be done.

2022-03-11 06:53 UTC, shashank-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
> +      vaultConfig.setSinkPath(null);
We need to set them null.
Else it will break a case. I will explain later

2022-03-11 06:55 UTC, shashank-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java
> +            .filter(x -> !x.isEmpty());
Its doing the same thing.
We can discuss this separately. Not part of this PR

2022-03-11 06:56 UTC, shashank-harness commented on 890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResponse.java
> +  @JsonProperty("lease_duration") private long leaseDuration;
@meenakshi-harness this field is coming from vault side and we are just mapping them. So this is correct.

2022-03-11 06:57 UTC, shashank-harness commented on 890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResult.java
> +  @JsonProperty("client_token") private String clientToken;
Same as lease duration

2022-03-11 14:23 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31113)* status: 25 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java, line 112 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx8avQ3E9fCg0ZMvUp5-r1-112:-MxtM5fq9UCorHm5_00u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java#L112)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

For these types we should not be passing renewal time as well. Recently we made this field as mandatory from BE which is not actually required in these cases.
We can later check how to change this. Not blocking
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 465 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5h-r1-465:-MxtM7Yn8awf3y7CcWL1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L465)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Rename x to meaningful name.
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 468 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5h-r1-468:-MxtMCCd-JE3RhOgLyDJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L468)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

instead of ifPresent use Map to loop through Optional.
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 472 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5h-r1-472:-MxtMCoUEOYkeoONox4L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L472)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

We need to set them null.
Else it will break a case. I will explain later
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 483 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5h-r1-483:-MxtMD_o5_IBAcYbsHnh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L483)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Its doing the same thing.
We can discuss this separately. Not part of this PR
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 484 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5h-r1-484:-MxtME9xBs0vXqZIuCDN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L484)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Rename x 
</blockquote></details>

Done.
___
*[440-connector-nextgen/src/test/resources/schema/Connectors/all.json, line 4106 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mxd3BiD6ONexsiwxTu8-r1-4106:-MxtM8Jd6Hpre41hp7G8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/440-connector-nextgen/src/test/resources/schema/Connectors/all.json#L4106)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

We should these field as required here in case of specific auth type. Else creating via Yaml wont show error.
</blockquote></details>

Done.
___
*[890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java, line 195 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-MxrGxFt6QB_7VlLRLHB:-MxtM8yN7OEIbgGJiC8F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java#L195)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Change message to below:
You must provide a delegate selector to read service account token if you are using K8s Auth method
</blockquote></details>

Done.
___
*[890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResponse.java, line 18 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5r-r1-18:-MxtM9Vc5pzt6RXlw_6W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResponse.java#L18)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

@meenakshi-harness this field is coming from vault side and we are just mapping them. So this is correct.
</blockquote></details>

Done.
___
*[890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResult.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5s-r1-22:-MxtMAyFEtkr2IgnoEaO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/890-sm-core/src/main/java/io/harness/helpers/ext/vault/VaultK8sLoginResult.java#L22)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Same as lease duration
</blockquote></details>

Done.
___
*[940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/VaultK8sCredentialDTO.java, line 19 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-Mx88vS6UfXNUMWIBL5t-r1-19:-MxtMBV_9K301fApWP5S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/VaultK8sCredentialDTO.java#L19)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

These should be NotNull. Check if this can be done.
</blockquote></details>

Done.
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java, line 138 at r1](https://reviewable.io/reviews/harness/harness-core/31113#-MxrJzkz82C3cZrfHhQc:-MxrlPh94qJ9Kf8SjjKX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af3677c8ae810dbc1cbb96004f3513833bce9caf/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java#L138)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Please check Boopesh has recently merged this change in which he hadded validations to this class too. Please check that they are not breaking yours before merging your PR.
https://github.com/harness/harness-core/pull/30961/files

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-12 08:19 UTC, meenakshi-harness approved these changes
> Reviewed 18 of 23 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31113)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-12 09:50 UTC, abhinav-harness approved these changes
> Reviewed 18 of 23 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31113)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-12 09:59 UTC, arpit3107 approved these changes
> Reviewed 18 of 23 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31113)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-12 10:43 UTC, shashank-harness approved these changes
> Reviewed 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31113)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-12 10:46 UTC, merged