[feat]: [CVS-9247]: implemented External API call log end point
harness/harness-core pull request #31141
Opened 2022-03-02 21:24 UTC by kapil-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-02 21:47 UTC, kapil-harness commented
trigger messagecheck

2022-03-03 02:52 UTC, kjoshi12345 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 417 at r2](https://reviewable.io/reviews/harness/harness-core/31141#-MxCfSXy9IqnT3dDIa1I:-MxCfSXy9IqnT3dDIa1J:b-t9r5c) ([raw file](https://github.com/harness/harness-core/blob/99cd37612e0eb16940421329d555b27b27e8cdaa/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L417)):*
> ```Java
> 
>   @Override
>   public PageResponse<CVNGLogRecord> getLogs(String accountId, String verificationJobInstanceId, String logType,
> ```

This should be generic for time series and logs 
Also this logic should go into CVNGLogService instead of here.
The convention is that the query for any entity goes into the same service. You should not write the query of different entity into some other service.


<!-- Sent from Reviewable.io -->

2022-03-03 07:11 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, line 417 at r2](https://reviewable.io/reviews/harness/harness-core/31141#-MxCfSXy9IqnT3dDIa1I:-MxDbgzT-vLatOJLrzw3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/99cd37612e0eb16940421329d555b27b27e8cdaa/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L417)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

This should be generic for time series and logs 
Also this logic should go into CVNGLogService instead of here.
The convention is that the query for any entity goes into the same service. You should not write the query of different entity into some other service.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-03-03 10:16 UTC, kjoshi12345 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentExecutionAndExternalAPILogsServiceImpl.java, line 40 at r3](https://reviewable.io/reviews/harness/harness-core/31141#-MxEFiW_Ebuw9eMSX8MD:-MxEFiW_Ebuw9eMSX8ME:b-f9b253) ([raw file](https://github.com/harness/harness-core/blob/206e4ffc1ed840d64d848223dbdcba20533fa968/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentExecutionAndExternalAPILogsServiceImpl.java#L40)):*
> ```Java
>   public PageResponse<CVNGLogRecord> getLogs(String accountId, String verificationJobInstanceId, String logType,
>       List<String> healthSourceIdentifiers, boolean errorLogsOnly, PageParams pageParams) {
>     List<CVNGLog> cvngLogs = getCVNGLogs(accountId, verificationJobInstanceId, logType, healthSourceIdentifiers);
> ```

this logic can be in StepTaskService. We don't need a new service.


<!-- Sent from Reviewable.io -->

2022-03-03 18:20 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentExecutionAndExternalAPILogsServiceImpl.java, line 40 at r3](https://reviewable.io/reviews/harness/harness-core/31141#-MxEFiW_Ebuw9eMSX8MD:-MxG-kBI3nXV30KA9INZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/206e4ffc1ed840d64d848223dbdcba20533fa968/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentExecutionAndExternalAPILogsServiceImpl.java#L40)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this logic can be in StepTaskService. We don't need a new service.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-03-04 03:30 UTC, kjoshi12345 requested changes
> Reviewed 3 of 11 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java, line 171 at r4](https://reviewable.io/reviews/harness/harness-core/31141#-MxHwm07B7e0Mf6-pbsN:-MxHwm089SRblVem_mcn:b1rv8is) ([raw file](https://github.com/harness/harness-core/blob/1406d6e78735227b1bbdeffb35e02f2b3d19dde3/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java#L171)):*
> ```Java
>   public RestResponse<PageResponse<CVNGLogDTO>> getLogs(@NotEmpty @NotNull @QueryParam("accountId") String accountId,
>       @NotEmpty @NotNull @PathParam("verifyStepExecutionId") String callBackId,
>       @NotEmpty @NotNull @QueryParam("logType") String logType,
> ```

I think this can be enum instead of String. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 176 at r4](https://reviewable.io/reviews/harness/harness-core/31141#-MxHxcc52PSWxlrNGfI4:-MxHxcc52PSWxlrNGfI5:bnq9qp3) ([raw file](https://github.com/harness/harness-core/blob/1406d6e78735227b1bbdeffb35e02f2b3d19dde3/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L176)):*
> ```Java
>     Set<String> verificationTaskIds =
>         verificationTaskService.maybeGetVerificationTaskIds(accountId, verificationJobInstanceId);
>     if (isNotEmpty(healthSourceIdentifiers)) {
> ```

nit: ideally this filtering logic should be outside of CVNGLogService. we can refactor it once we implement it for live monitoring and sli. CVNGLogService should only provide generic methods.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 185 at r4](https://reviewable.io/reviews/harness/harness-core/31141#-MxHxvUn92SobWRrIo0m:-MxHxvUn92SobWRrIo0n:b-whenj5) ([raw file](https://github.com/harness/harness-core/blob/1406d6e78735227b1bbdeffb35e02f2b3d19dde3/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L185)):*
> ```Java
>               .collect(Collectors.toSet());
>     }
>     CVNGLogType cvngLogType = logType.equalsIgnoreCase("api") ? CVNGLogType.API_CALL_LOG : CVNGLogType.EXECUTION_LOG;
> ```

this is error prone. Please create a new enum for external api call and CVNGLogType enum should have a method for conversion of enum.


<!-- Sent from Reviewable.io -->

2022-03-04 10:22 UTC, kapil-harness commented
API:
https://localhost:8181/cv/api/verify-step/dhzj89dUT6OnA71kDgP70w/logs?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&logType=ApiCallLog&pageNumber=0&pageSize=10

Response:
{
    "metaData": {},
    "resource": {
        "totalPages": 1,
        "totalItems": 5,
        "pageItemCount": 5,
        "pageSize": 10,
        "content": [
            {
                "accountId": "kmpySmUISimoRrJL6NL73w",
                "traceableId": "6tQf7e7WTP-v9SjtPm19HA",
                "createdAt": 1645772566813,
                "startTime": 1645764000000,
                "endTime": 1645772100000,
                "traceableType": "VERIFICATION_TASK",
                "requests": [
                    {
                        "name": "url",
                        "value": "https://harness-test.saas.appdynamics.com/controller/rest/applications/cv-app/metric-data?output=JSON&time-range-type=BETWEEN_TIMES&rollup=false&start-time=1645764000000&end-time=1645772100000&metric-path=Errors|python-tier|*|Number%20of%20Errors",
                        "type": "URL"
                    }
                ],
                "responses": [
                    {
                        "name": "Status Code",
                        "value": "200",
                        "type": "NUMBER"
                    },
                    {
                        "name": "Response Body",
                        "value": "[{\"metricId\":3.68859702E8,\"metricName\":\"BTM|Application Diagnostic Data|Error:25801602|Number of Errors\",\"metricPath\":\"Errors|python-tier|werkzeug.exceptions.NotFound|Number of Errors\",\"frequency\":\"ONE_MIN\",\"metricValues\":[{\"startTimeInMillis\":1.645764E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576406E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576412E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576418E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576424E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.6457643E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576436E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576442E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576448E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576454E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.6457646E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576466E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576472E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576478E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576484E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.6457649E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576496E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576502E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576508E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576514E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.6457652E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576526E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576532E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576538E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576544E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.6457655E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576556E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576562E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576712E12,\"occurrences\":1.0,\"current\":2.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":2.0,\"value\":2.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576718E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576724E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.6457673E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576736E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576742E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false,\"count\":1.0,\"sum\":0.0,\"value\":0.0,\"standardDeviation\":0.0},{\"startTimeInMillis\":1.64576748E12,\"occurrences\":1.0,\"current\":0.0,\"min\":0.0,\"max\":0.0,\"useRange\":false, [...]

2022-03-04 10:25 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: 7 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java, line 171 at r4](https://reviewable.io/reviews/harness/harness-core/31141#-MxHwm07B7e0Mf6-pbsN:-MxJSKmPELlc_gTdEivB:b8644ty) ([raw file](https://github.com/harness/harness-core/blob/1406d6e78735227b1bbdeffb35e02f2b3d19dde3/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java#L171)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think this can be enum instead of String. 
</blockquote></details>

I did these changes however the @JsonProperty annotation is not getting picked up because of which I was getting an error. I am looking into this issue, meanwhile I have created a convertor inside the num which saves the issue.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 176 at r4](https://reviewable.io/reviews/harness/harness-core/31141#-MxHxcc52PSWxlrNGfI4:-MxJSdlh4dQhtH7RTcsG:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/1406d6e78735227b1bbdeffb35e02f2b3d19dde3/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L176)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

nit: ideally this filtering logic should be outside of CVNGLogService. we can refactor it once we implement it for live monitoring and sli. CVNGLogService should only provide generic methods.
</blockquote></details>

ok
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 185 at r4](https://reviewable.io/reviews/harness/harness-core/31141#-MxHxvUn92SobWRrIo0m:-MxJSeuj-sIouA17i7Cw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1406d6e78735227b1bbdeffb35e02f2b3d19dde3/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L185)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this is error prone. Please create a new enum for external api call and CVNGLogType enum should have a method for conversion of enum.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-03-04 10:34 UTC, kjoshi12345 approved these changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-04 10:38 UTC, kjoshi12345 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31141)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-04 11:33 UTC, merged