feat: [CDNG-242]: Adding Azure support to SCM
harness/harness-core pull request #31165
Opened 2022-03-03 17:55 UTC by tphoney

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-04 09:14 UTC, tphoney commented
trigger messagecheck

2022-03-04 09:30 UTC, tphoney commented
trigger messagecheck

2022-03-04 09:36 UTC, tphoney commented
trigger messagecheck

2022-03-04 09:39 UTC, tphoney commented
trigger messagecheck

2022-03-15 06:32 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[product/ci/scm/README.md, line 89 at r1](https://reviewable.io/reviews/harness/harness-core/31165#-MyBEjPtB5kv2pveFeyO:-MyBEjPtB5kv2pveFeyP:b-vdyhbu) ([raw file](https://github.com/harness/harness-core/blob/db40ed36ebdaa0f5a07205875e04f2ee419ff012/product/ci/scm/README.md#L89)):*
> ```Markdown
> 
> ```BASH
> AZURE_TOKEN=963408579168567c07ff8bfd2a5455e5307f74d4 go test -count=1 -v ./...
> ```

Is this a valid token? 
___
*[product/ci/scm/file/file.go, line 452 at r1](https://reviewable.io/reviews/harness/harness-core/31165#-MyBG0Wj2fs0pHmYKBGx:-MyBG0Wj2fs0pHmYKBGy:b-54awv) ([raw file](https://github.com/harness/harness-core/blob/db40ed36ebdaa0f5a07205875e04f2ee419ff012/product/ci/scm/file/file.go#L452)):*
> ```Go
> 			return "", ""
> 		}
> 		return out.RefUpdates[0].NewObjectID, ""
> ```

Shouldn't NewObjectID be 2nd in the return param list? First one is commit id right?


<!-- Sent from Reviewable.io -->

2022-03-15 15:47 UTC, tphoney commented
i'll look at these now

2022-03-15 16:19 UTC, shubham149 commented on product/ci/scm/file/file.go
> +		return out.RefUpdates[0].NewObjectID, ""
Ensure that we don't get null pointer exception here i.e if RefUpdates list is empty

2022-03-16 12:09 UTC, tphoney commented on product/ci/scm/file/file.go
> +		return out.RefUpdates[0].NewObjectID, ""
done

2022-03-16 12:10 UTC, tphoney reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[WORKSPACE, line 1012 at r1](https://reviewable.io/reviews/harness/harness-core/31165#-MxKa5Passo7xBBp557F-r1-1012:-MyDIAY1BNLm0K5h8uqg:bkykn6n) ([raw file](https://github.com/harness/harness-core/blob/db40ed36ebdaa0f5a07205875e04f2ee419ff012/WORKSPACE#L1012)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Shouldn't this use version v1.20
</blockquote></details>

it was not available at the time, updated now
___
*[product/ci/scm/README.md, line 89 at r1](https://reviewable.io/reviews/harness/harness-core/31165#-MyBEjPtB5kv2pveFeyO:-MyDI2PZCzDXVgXV18V-:b7303el) ([raw file](https://github.com/harness/harness-core/blob/db40ed36ebdaa0f5a07205875e04f2ee419ff012/product/ci/scm/README.md#L89)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is this a valid token? 
</blockquote></details>

it is not a valid token, copied from the line above.
___
*[product/ci/scm/file/file.go, line 452 at r1](https://reviewable.io/reviews/harness/harness-core/31165#-MyBG0Wj2fs0pHmYKBGx:-MyHch-14hXHCVFrtXiB:b-wswmj1) ([raw file](https://github.com/harness/harness-core/blob/db40ed36ebdaa0f5a07205875e04f2ee419ff012/product/ci/scm/file/file.go#L452)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Shouldn't NewObjectID be 2nd in the return param list? First one is commit id right?
</blockquote></details>

newobjectid is actually the commit id, it is very weird


<!-- Sent from Reviewable.io -->

2022-03-16 12:12 UTC, tphoney commented
@mohitg0795 @shubham149 changes made where appropriate

2022-03-16 12:34 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 14 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165#-:-MyHiIwn6ma0Y_Ih-7Pq:bnfp4nl)* status: 14 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-16 13:07 UTC, shubham149 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165)* status: 14 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 13:07 UTC, shubham149 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165)* status: 14 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 13:07 UTC, shubham149 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165#-:-MyHpppR12QZqBwVxufB:bnfp4nl)* status: 14 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 13:07 UTC, shubham149 approved these changes
> Reviewed 6 of 14 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 14:20 UTC, tphoney reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165#-:-MyI5YG95iLsRL_tWDSq:bnfp4nl)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 14:22 UTC, tphoney reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165#-:-MyI5rDwDKMS1ZHCpQlK:bnfp4nl)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 15:40 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165#-:-MyINkh9ERvCsb0Eyu4S:bnfp4nl)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 15:43 UTC, arpit3107 approved these changes
> Reviewed 6 of 14 files at r1, 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 15:47 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31165#-:-MyIPHRiBzHCt_v0cAWs:bnfp4nl)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-16 16:06 UTC, merged