[CDS-34522]: Add  TemplateLinkConfig in PipelineInforCondif DTO
harness/harness-core pull request #31177
Opened 2022-03-04 07:43 UTC by abhinavmittal-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-07 06:07 UTC, abhinavmittal-harness commented
/rebase

2022-03-08 04:21 UTC, abhinavmittal-harness commented
/rebase

2022-03-14 00:11 UTC, abhinavmittal-harness commented
/rebase

2022-03-15 07:15 UTC, inderschera requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31177)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[860-orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelineInfoConfig.java, line 79 at r1](https://reviewable.io/reviews/harness/harness-core/31177#-MyBPf-l78XiC6-wUUag:-MyBPf-l78XiC6-wUUah:bdn7zx3) ([raw file](https://github.com/harness/harness-core/blob/97660f31ffa4bc693cc203a5442ab4b5e792c5fe/860-orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelineInfoConfig.java#L79)):*
> ```Java
>   ParameterField<Timeout> timeout;
> 
>   TemplateLinkConfig template;
> ```

This will start showing up in auto suggestion in pipeline yaml along with stages and timeout, which is not expected.
Once we have written template in pipeline yaml, stages should not come in auto suggest.
We should add @OneOfSet on this to avoid that.
For reference, check StageElementConfig. 
We should test this part out in yaml view in harness UI.


<!-- Sent from Reviewable.io -->

2022-03-28 08:20 UTC, abhinavmittal-harness commented on 840-template-service/src/main/java/io/harness/template/handler/PipelineTemplateYamlConversionHandler.java
> +    YamlField typeYamlField = rootYamlField.getNode().getField(STAGES);
I'll fix the variable name in the subsequent commit

2022-03-28 08:33 UTC, inderschera reviewed
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31177)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[840-template-service/src/main/java/io/harness/template/handler/PipelineTemplateYamlConversionHandler.java, line 45 at r2](https://reviewable.io/reviews/harness/harness-core/31177#-MzEe1SB6o6SFvsSbaM3:-MzEe1SB6o6SFvsSbaM4:boxu98c) ([raw file](https://github.com/harness/harness-core/blob/da47f08540deac072203bddf9b08d1d4a61c432b/840-template-service/src/main/java/io/harness/template/handler/PipelineTemplateYamlConversionHandler.java#L45)):*
> ```Java
>     YamlField typeYamlField = rootYamlField.getNode().getField(STAGES);
>     if (typeYamlField == null) {
>       throw new NGTemplateException("yamlNode provided doesn not have type yaml field");
> ```

Please fix type -> stages here as well.


<!-- Sent from Reviewable.io -->

2022-03-28 09:17 UTC, inderschera submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31177#-:-MzEo65hENMcm46qkzD9:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-28 12:29 UTC, poojaSinghal approved these changes
> Reviewed 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31177)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-06 10:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31177) it.</sub>

2022-04-06 10:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31177) it.</sub>

2022-04-14 04:35 UTC, abhinavmittal-harness commented
/rebase

2022-04-19 05:27 UTC, inderschera reviewed
> Reviewed 1 of 2 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31177)* status: 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-19 06:13 UTC, inderschera reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31177)* status: 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-19 09:29 UTC, inderschera approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31177)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-19 10:32 UTC, merged