[fix]: [PL-22356]: Added support to delete all git sync config upon deletion of project
harness/harness-core pull request #31178
Opened 2022-03-04 09:51 UTC by rathodmeetsatish

Added support to delete all git sync config upon deletion of project

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-04 09:53 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-10 21:36 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 315 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpkMT-4n7ENTAM7HPO:-MxpkMT-4n7ENTAM7HPP:b-2ecgee) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L315)):*
> ```Java
> 
>   @Override
>   public void deleteAllOnProjectDeletion(String accountIdentifier, String organizationIdentifier, String projectIdentifier){
> ```

With respect to git entity service, method name isn't correct. It doesn't care about project deletion. It only cares about its own action. So, it should be something like : deleteAllEntitiesForGivenScope() or simply deleteAllEntities() etc.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 439 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpk_yF8Dtn6XnRQ8Y5:-Mxpk_yF8Dtn6XnRQ8Y6:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L439)):*
> ```Java
> 
>   @Override
>   public void deleteAllOnProjectDeletion(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigService.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpkbzz3_MqbXSLt8Pn:-Mxpkbzz3_MqbXSLt8Po:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigService.java#L26)):*
> ```Java
>   boolean delete(String accountIdentifier, String orgIdentifier, String projectIdentifier);
> 
>   void deleteAllOnProjectDeletion(String accountIdentifier, String orgIdentifier, String projectIdentifier);
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 107 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpkciQBDY4dfgdWLkU:-MxpkciQBDY4dfgdWLkV:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L107)):*
> ```Java
> 
>   @Override
>   public void deleteAllOnProjectDeletion(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 192 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpkdvR21oZTuPZwgta:-MxpkdvR21oZTuPZwgtb:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L192)):*
> ```Java
> 
>   @Override
>   public void deleteAllOnProjectDeletion(String accountIdentifier, String orgIdentifier, String projectIdentifier){
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/impl/FullSyncJobServiceImpl.java, line 107 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpkei66Qa357ps7vEa:-Mxpkei66Qa357ps7vEb:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/impl/FullSyncJobServiceImpl.java#L107)):*
> ```Java
> 
>   @Override
>   public void deleteAllOnProjectDeletion(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java, line 409 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpki0PDdd-J4lVYO70:-Mxpki0PDdd-J4lVYO71:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java#L409)):*
> ```Java
> 
>   @Override
>   public void removeScopeOnProjectDeletion(String accountIdentifier, String orgIdentifier, String projectIdentifier){
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpiuQaEz2e8x_uaOUL:-MxpiuQaEz2e8x_uaOUM:b7fglnl) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L26)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> public class GitAndFullSyncEntityCRUDStreamListener implements MessageListener {
> ```

The class name doesn't feel intuitive. Please can you share whats the use-case here, we can try to improve it.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 59 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjLRJCvV0Iyo5fT1X:-MxpjLRJCvV0Iyo5fT1Y:bz1eyh0) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L59)):*
> ```Java
>     String action = message.getMessage().getMetadataMap().get(ACTION);
>     if (action != null) {
>       if (action.equals(DELETE_ACTION)) {
> ```

null check can be removed by better if statement : if (DELETE_ACTION.equals(action))
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjX5M2nUl3peCtbHb:-MxpjX5M2nUl3peCtbHc:b-y9b2er) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L61)):*
> ```Java
>       if (action.equals(DELETE_ACTION)) {
>         return processProjectDeleteEvent(projectEntityChangeDTO);
>       }
> ```

can we add log for action in case its not DELETE_ACTION, just to trace out unexpected events.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 66 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjyghCCUHgvWsQz2E:-MxpjyghCCUHgvWsQz2F:b5wm90w) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L66)):*
> ```Java
>   }
> 
>   private boolean processProjectDeleteEvent(ProjectEntityChangeDTO projectEntityChangeDTO) {
> ```

Lets move this logic to a separate service and make it cleaner with some retries as well.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 68 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpk1Iy4yBZdvtucSHN:-Mxpk1Iy4yBZdvtucSHO:bqot8kj) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L68)):*
> ```Java
>   private boolean proces [...]

2022-03-14 17:24 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 315 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpkMT-4n7ENTAM7HPO:-My8SBq5AzGSGGxLjc1a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L315)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

With respect to git entity service, method name isn't correct. It doesn't care about project deletion. It only cares about its own action. So, it should be something like : deleteAllEntitiesForGivenScope() or simply deleteAllEntities() etc.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 439 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpk_yF8Dtn6XnRQ8Y5:-My8SCqA7xiXFLaxOnUi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L439)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigService.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpkbzz3_MqbXSLt8Pn:-My8SDrf1rp2NwuKPPET:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigService.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java, line 107 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpkciQBDY4dfgdWLkU:-My8SEfs3VNmRmGNOnlA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncConfigServiceImpl.java#L107)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 192 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpkdvR21oZTuPZwgta:-My8SFb05CtjNECaEIG4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L192)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/impl/FullSyncJobServiceImpl.java, line 107 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpkei66Qa357ps7vEa:-My8SGOE4IHhZbiJFNCn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/impl/FullSyncJobServiceImpl.java#L107)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java, line 409 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpki0PDdd-J4lVYO70:-My8SHOl8ipLnNEicriI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java#L409)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 59 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjLRJCvV0Iyo5fT1X:-My8Riqo3EsMZrM0ZGje:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

null check can be removed by better if statement : if (DELETE_ACTION.equals(action))
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 66 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjyghCCUHgvWsQz2E:-My8Rs9IC_GdTPrqnLdC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L66)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets move this logic to a separate service and make it cleaner with some retries as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-14 17:33 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpiuQaEz2e8x_uaOUL:-My8UCWH64tc2V-wJH8I:b83kdr1) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The class name doesn't feel intuitive. Please can you share whats the use-case here, we can try to improve it.
</blockquote></details>

named similar to other listeners in 120-ng-manager
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 68 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpk1Iy4yBZdvtucSHN:-My8U65vDDt9MdiHghLT:b-gp6nzz) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should move these calls into modular methods with proper names justifying their use-case. We should add 2-3 retries for each method with proper logging for failures.
</blockquote></details>

EntityCRUDStreamConsumer itself retries


<!-- Sent from Reviewable.io -->

2022-03-14 17:43 UTC, DeepakPatankar requested changes
> Reviewed 5 of 21 files at r2, 30 of 30 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java, line 829 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8UoEN2wyj3a4tAnk4:-My8UoEN2wyj3a4tAnk5:b-9rsscm) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L829)):*
> ```Java
>         .to(FullSyncMessageListener.class);
>     bind(MessageListener.class)
>         .annotatedWith(Names.named(EventsFrameworkConstants.GIT_AND_FULL_SYNC_ENTITY_STREAM + ENTITY_CRUD))
> ```

Since full sync is a subpart of git sync itself. Lets call it something else, like GIT_SYNC_ENTITY_STREAM
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java, line 27 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8WYY8AUjBVnCrtkhs:-My8WYY8AUjBVnCrtkht:b-ac3udr) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java#L27)):*
> ```Java
>   private final GitFullSyncEntityService gitFullSyncEntityService;
> 
>   public boolean deleteAssociatedGitEntities(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
> ```

Add logs lines at the starting and end of this function
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java, line 28 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8V7-F3C44ASaalH4F:-My8V7-F3C44ASaalH4G:bo0lc9z) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java#L28)):*
> ```Java
> 
>   public boolean deleteAssociatedGitEntities(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
>     try {
> ```

Can you please check that all these functions are idempotent? 

Let's say this message is processed again then it should not result in an ambiguous state.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java, line 33 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8VR3V-bR9cPWcxva8:-My8VR3V-bR9cPWcxva9:b-dsu8k5) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java#L33)):*
> ```Java
>       gitEntityService.deleteAllEntities(accountIdentifier, orgIdentifier, projectIdentifier);
>       gitSyncErrorService.removeScope(accountIdentifier, orgIdentifier, projectIdentifier);
>       fullSyncJobService.deleteAllEntities(accountIdentifier, orgIdentifier, projectIdentifier);
> ```

nit: We can simply call the functions which you made as deleteAll
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8WfUyCmwsloavtFj1:-My8WfUyCmwsloavtFj2:b3gmjce) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java#L37)):*
> ```Java
>       gitFullSyncEntityService.deleteAllEntities(accountIdentifier, orgIdentifier, projectIdentifier);
>       return true;
>     } catch (Exception ex) {
> ```

log this exception
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 321 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8VzBHEai764yFqtF5:-My8VzBHEai764yFqtF6:bsaxshd) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L321)):*
> ```Java
> 
>   @Override
>   public void deleteAllEntities(String accountIdentifier, String organizationIdentifier, String projectIdentifier) {
> ```

organizationIdentifier -> orgIdentifier. As that is the variable name we are following everywhere.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpiuQaEz2e8x_uaOUL:-My8Vc5y9qAWadoCEy7Y:b-vgh1xu) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L26)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

named similar to other listeners in 120-ng-manager
</blockquote></details>

There is no need to write Full Sync explicitly. Lets name it GitSyncRelatedEntityCrudStreamListener


<!-- Sent from Reviewable.io -->

2022-03-14 17:48 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 68 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpk1Iy4yBZdvtucSHN:-My8XlUW2jHzLMR-0_eD:bhp8b5j) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L68)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

EntityCRUDStreamConsumer itself retries
</blockquote></details>

@mohitg0795  If the consumer fails, then it is retired multiple times by our Events framework. Hence we can rely on event frameworks for the retries.


<!-- Sent from Reviewable.io -->

2022-03-14 18:37 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java, line 829 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8UoEN2wyj3a4tAnk4:-My8hvdu27RzV_aHHR1w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L829)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Since full sync is a subpart of git sync itself. Lets call it something else, like GIT_SYNC_ENTITY_STREAM
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 321 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8VzBHEai764yFqtF5:-My8i54U7NabM8Zc49Q5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L321)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

organizationIdentifier -> orgIdentifier. As that is the variable name we are following everywhere.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java, line 27 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8WYY8AUjBVnCrtkhs:-My8hx0NAd208I4Jb-8U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java#L27)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Add logs lines at the starting and end of this function
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8WfUyCmwsloavtFj1:-My8i02_11-n52_ZZxI0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java#L37)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

log this exception
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpiuQaEz2e8x_uaOUL:-My8i1tt6I_rJRRk6FI6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L26)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

There is no need to write Full Sync explicitly. Lets name it GitSyncRelatedEntityCrudStreamListener
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 68 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-Mxpk1Iy4yBZdvtucSHN:-My8i3WD5L1j27dxOlvd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L68)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

@mohitg0795  If the consumer fails, then it is retired multiple times by our Events framework. Hence we can rely on event frameworks for the retries.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-14 19:23 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/event/EntityCRUDStreamConsumer.java, line 68 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8qEG0ANEVzRb9lpsp:-My8qEG1Ar9hAThgvqUl:b7vpdqe) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/120-ng-manager/src/main/java/io/harness/ng/core/event/EntityCRUDStreamConsumer.java#L68)):*
> ```Java
>     messageListenersList = new ArrayList<>();
>     messageListenersList.add(projectEntityCRUDStreamListener);
>     messageListenersList.add(gitAndFullSyncEntityCRUDStreamListener);
> ```

naming issue
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 443 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8rlF0CO53MXBBIWwZ:-My8rlF0CO53MXBBIWw_:b7sisnn) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L443)):*
> ```Java
>     yamlGitConfigRepository.deleteByAccountIdAndOrgIdentifierAndProjectIdentifier(
>         accountIdentifier, orgIdentifier, projectIdentifier);
>     deleteExistingSetupUsages(yamlGitConfigDTOS);
> ```

this should be deleted before deleting the yaml git config document, right? Otherwise lets say this call fails, then how will you delete them later?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java, line 413 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8sCtT1GuJyjRO49g8:-My8sCtT1GuJyjRO49g9:bj2ssu8) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java#L413)):*
> ```Java
>     gitSyncErrorRepository.updateError(new Criteria(), update);
>     Criteria criteria = Criteria.where(GitSyncErrorKeys.scopes).size(0);
>     gitSyncErrorRepository.deleteAll(criteria);
> ```

@bhavya181 @deepakpatankar please review this logic
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 20 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8qtdE6Z0f1M73lOCF:-My8qtdE6Z0f1M73lOCG:b-v427cs) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L20)):*
> ```Java
> @Slf4j
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> public class GitSyncEntityCRUDEventHandler {
> ```

its not CRUD event handler right? You can name it something like: GitSyncCleanupHandler etc.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 33 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8qWiF2YlWKrNZZ_je:-My8qWiF2YlWKrNZZ_jf:b-4q5j7j) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L33)):*
> ```Java
>     try {
>       yamlGitConfigService.deleteAllEntities(accountIdentifier, orgIdentifier, projectIdentifier);
>       gitSyncSettingsService.delete(accountIdentifier, orgIdentifier, projectIdentifier);
> ```

can we make separate methods for all these calls? eg: removeGitSyncConfig(), removeGitSyncEntities() etc etc.

It will make the code much more readable and easier to refer in future. Currently, it looks bunch of DB calls that removes data.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java, line 23 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8r0c27CZRDPBWlw3P:-My8r0c27CZRDPBWlw3Q:b-h24aws) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java#L23)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> public class GitSyncEntityCRUDStreamListener implements MessageListener {
> ```

Why is this CRUD Stream Listener? What all events will be pushed into it?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java, line 50 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8rMhcEV4pGoacb_dd:-My8rMhcEV4pGoacb_de:b-zi8rhi) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java#L50)):*
> ```Java
>     String action = message.getMessage().getMetadataMap().get(ACTION);
>     if (DELETE_ACTION.equals(action)) {
>       return processProjectDeleteEvent(projectEntityChangeDTO);
> ```

we can directly call the service layer from here. Why do we need another method call?


<!-- Sent from Reviewable.io -->

2022-03-14 19:48 UTC, DeepakPatankar requested changes
> Reviewed 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 30 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8xzvP9iX2nXsQEE7l:-My8xzvQ2YAU8jRC9nfq:b-h3p1e3) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L30)):*
> ```Java
> 
>   public boolean deleteAssociatedGitEntities(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
>     log.info("Starting the deletion of git entities");
> ```

add the project id
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 42 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8y5vs0kvr6jOnJ-M0:-My8y5vs0kvr6jOnJ-M1:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L42)):*
> ```Java
>       return true;
>     } catch (Exception ex) {
>       log.error("Failed to delete all the git entities ", ex);
> ```

same



_Code quote:_
```Java
      log.error("Failed to delete all the git entities ", ex);
```


<!-- Sent from Reviewable.io -->

2022-03-15 05:27 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/event/EntityCRUDStreamConsumer.java, line 68 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8qEG0ANEVzRb9lpsp:-MyB0OVn6IuTHxIoIcxo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/120-ng-manager/src/main/java/io/harness/ng/core/event/EntityCRUDStreamConsumer.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

naming issue
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 443 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8rlF0CO53MXBBIWwZ:-MyB1xj7AA-lKhDbWo7m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L443)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be deleted before deleting the yaml git config document, right? Otherwise lets say this call fails, then how will you delete them later?
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 20 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8qtdE6Z0f1M73lOCF:-MyB0cZU2LP8hMtK9oYQ:bsy6ac) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

its not CRUD event handler right? You can name it something like: GitSyncCleanupHandler etc.
</blockquote></details>

Further if we want to do something on CREATE_ACTION or RESTORE_ACTION we can add here itself
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 30 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8xzvP9iX2nXsQEE7l:-MyB0pqmBX7rur9fdy57:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L30)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

add the project id
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 33 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8qWiF2YlWKrNZZ_je:-MyB0saIEjslXpO6bVzx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L33)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we make separate methods for all these calls? eg: removeGitSyncConfig(), removeGitSyncEntities() etc etc.

It will make the code much more readable and easier to refer in future. Currently, it looks bunch of DB calls that removes data.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 42 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8y5vs0kvr6jOnJ-M0:-MyB0tdG8SRPGkTJl-j4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L42)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java, line 23 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8r0c27CZRDPBWlw3P:-MyB11wO8Fr1ylG33_m-:b-5iqutp) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is this CRUD Stream Listener? What all events will be pushed into it?
</blockquote></details>

currently we are processing only deleteAction but further if we want to process CREATE_ACTION or RESTORE_ACTION whats why CRUD
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java, line 50 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8rMhcEV4pGoacb_dd:-MyB1SLY9af4I5iTOZMz:b-cof3qi) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java#L50)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can directly call the service layer from here. Why do we need another method call?
</blockquote></details>

to make it more readable further we when we have different actions it will look something similar to 
switch (action) {
        case CREATE_ACTION:
          return processProjectCreateEvent(projectEntityChangeDTO);
        case DELETE_ACTION:
          return processProjectDeleteEvent(projectEntityChangeDTO);
        case RESTORE_ACTION:
          return processProjectRestoreEvent(projectEntityChangeDTO);
        default:
      }


<!-- Sent from Reviewable.io -->

2022-03-15 05:31 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjX5M2nUl3peCtbHb:-My8VVTm-6PvC-vpTjqe:b-2701qu) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L61)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we add log for action in case its not DELETE_ACTION, just to trace out unexpected events.
</blockquote></details>

there will be lot of logs for other actions @deepakpatankar what do you suggest here?


<!-- Sent from Reviewable.io -->

2022-03-15 05:47 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java, line 23 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8r0c27CZRDPBWlw3P:-MyB6DFR00aSLEWd79ko:betzz4o) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java#L23)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

currently we are processing only deleteAction but further if we want to process CREATE_ACTION or RESTORE_ACTION whats why CRUD
</blockquote></details>

I don't think there would be something like CREATE_ACTION, what does that even mean?

And CRUD totally has a different meaning. RESTORE_ACTION also not sure, but even if it comes, then it isn't CRUD.


<!-- Sent from Reviewable.io -->

2022-03-15 05:48 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjX5M2nUl3peCtbHb:-MyB6e1b05VVpC8tdrgW:be1pp4g) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L61)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

there will be lot of logs for other actions @deepakpatankar what do you suggest here?
</blockquote></details>

Why would there be a lot of logs? This log is to identify if some unwanted events are being pushed into this stream. So, if there are lot of logs then its a point to worry about.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java, line 50 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8rMhcEV4pGoacb_dd:-MyB6ZZ77fJobURtTHIg:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java#L50)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

to make it more readable further we when we have different actions it will look something similar to 
switch (action) {
        case CREATE_ACTION:
          return processProjectCreateEvent(projectEntityChangeDTO);
        case DELETE_ACTION:
          return processProjectDeleteEvent(projectEntityChangeDTO);
        case RESTORE_ACTION:
          return processProjectRestoreEvent(projectEntityChangeDTO);
        default:
      }
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-03-15 06:07 UTC, DeepakPatankar requested changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 30 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8xzvP9iX2nXsQEE7l:-MyBA6uz9PeND1R_objo:b1fcu9b) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L30)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

add orgId too
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjX5M2nUl3peCtbHb:-MyBAVkO1G4yEF10vjXr:bpw7bua) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L61)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why would there be a lot of logs? This log is to identify if some unwanted events are being pushed into this stream. So, if there are lot of logs then its a point to worry about.
</blockquote></details>

In my opinion, since our consumers don't need to know anything other than project delete, we don't have an explicit need to log other action types.

@mohitg0795  If we wanted to see if there are unwanted events in the project crud stream then it should be handled at a different place. Our consumer is not responsible for figuring out the other unwanted events.


<!-- Sent from Reviewable.io -->

2022-03-15 06:20 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/31178#-MxpjX5M2nUl3peCtbHb:-MyBDib0BmVE48sVscs0:b-bvm1q8) ([raw file](https://github.com/harness/harness-core/blob/98c273eec372857bf722ef8779d501872df710bf/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitAndFullSyncEntityCRUDStreamListener.java#L61)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

In my opinion, since our consumers don't need to know anything other than project delete, we don't have an explicit need to log other action types.

@mohitg0795  If we wanted to see if there are unwanted events in the project crud stream then it should be handled at a different place. Our consumer is not responsible for figuring out the other unwanted events.
</blockquote></details>

If this was a generic stream out of which we only wanted to consume some specific events, I would agree with you. But here its a dedicated stream for our use-case, so we should put a precautionary log here to identify any events that are being pushed into stream but doesn't comply with our use-case.


<!-- Sent from Reviewable.io -->

2022-03-15 08:25 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 30 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8xzvP9iX2nXsQEE7l:-MyBfLUPCn8I2PejBemv:bhy2fue) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L30)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

add orgId too
</blockquote></details>

Add try catch with complete stream context at start of message listener itself


<!-- Sent from Reviewable.io -->

2022-03-15 12:37 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java, line 413 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8sCtT1GuJyjRO49g8:-MyC_F3M-fsdiCSsa5OI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/impl/GitSyncErrorServiceImpl.java#L413)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@bhavya181 @deepakpatankar please review this logic
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java, line 28 at r3](https://reviewable.io/reviews/harness/harness-core/31178#-My8V7-F3C44ASaalH4F:-MyC_Kod4IvkB-7DaBSr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31c9eca8c9654f78574c6572b98b5110aee8d787/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitAndFullSyncEntityCRUDEventHandler.java#L28)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Can you please check that all these functions are idempotent? 

Let's say this message is processed again then it should not result in an ambiguous state.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 30 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8xzvP9iX2nXsQEE7l:-MyC_Gum6PfGUFTeGVC4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Add try catch with complete stream context at start of message listener itself
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java, line 23 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8r0c27CZRDPBWlw3P:-MyC_BXeB9qLUfP5DxJC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/events/GitSyncEntityCRUDStreamListener.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I don't think there would be something like CREATE_ACTION, what does that even mean?

And CRUD totally has a different meaning. RESTORE_ACTION also not sure, but even if it comes, then it isn't CRUD.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-15 12:49 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 35 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCleanupHandler.java, line 39 at r7](https://reviewable.io/reviews/harness/harness-core/31178#-MyCbqRZ1H1n2HVgXZ6l:-MyCbqRZ1H1n2HVgXZ6m:b5nidz7) ([raw file](https://github.com/harness/harness-core/blob/05f94712aa2adc530034c720e500738466ad9da4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCleanupHandler.java#L39)):*
> ```Java
>       removeGitFullSyncConfig(accountIdentifier, orgIdentifier, projectIdentifier);
>       removeGitFullSyncEntityInfo(accountIdentifier, orgIdentifier, projectIdentifier);
>       log.info("Successfully deleted all the git entities");
> ```

I think we can add project id here, its just to give more sense to logs. It will become more readable that successfully deleted all entities for xyz project
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCleanupHandler.java, line 42 at r7](https://reviewable.io/reviews/harness/harness-core/31178#-MyCbzuS0xB_3DCZpFxW:-MyCbzuS0xB_3DCZpFxX:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/05f94712aa2adc530034c720e500738466ad9da4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCleanupHandler.java#L42)):*
> ```Java
>       return true;
>     } catch (Exception ex) {
>       log.error("Failed to delete all the git entities", ex);
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java, line 20 at r4](https://reviewable.io/reviews/harness/harness-core/31178#-My8qtdE6Z0f1M73lOCF:-MyCbPma85BjtGCIWYH4:b-gohk9n) ([raw file](https://github.com/harness/harness-core/blob/c0021c1e4b8a32eb96527ebb977c380bf5f66601/136-git-sync-manager/src/main/java/io/harness/gitsync/common/eventhandlers/GitSyncEntityCRUDEventHandler.java#L20)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

Further if we want to do something on CREATE_ACTION or RESTORE_ACTION we can add here itself
</blockquote></details>

I think we decided on GitSyncProjectCleanupHandler?

coz the method also is named as deleteAssociatedGitEntities(), which means associated with project scope


<!-- Sent from Reviewable.io -->

2022-03-15 16:06 UTC, mohitg0795 approved these changes
> Reviewed 5 of 21 files at r2, 12 of 30 files at r3, 13 of 17 files at r4, 1 of 3 files at r5, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-15 16:37 UTC, DeepakPatankar reviewed
> Reviewed 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-15 16:44 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31178)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-15 16:44 UTC, merged