feat: [PIE-0]: POC for batching orchestration event logs
harness/harness-core pull request #31224
Opened 2022-03-07 11:17 UTC by sahilhindwani-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-08 09:27 UTC, hextechpal requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31224)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationLogPublisher.java, line 82 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcoxM692f9FL2GYIVS:-MxcoxM692f9FL2GYIVT:b-levzy1) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L82)):*
> ```Java
>     OrchestrationLogEvent orchestrationLogEvent =
>         OrchestrationLogEvent.newBuilder().setPlanExecutionId(planExecutionId).build();
>     if (orchestrationLogConfiguration.isShouldUseBatching()) {
> ```

extract these ifs in a function
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 235 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqJf18X4xQlry_ugI:-MxcqJf18X4xQlry_ugJ:b8e9le1) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L235)):*
> ```Java
>     PlanExecution planExecution = planExecutionService.get(planExecutionId);
>     List<NodeExecution> nodeExecutions = nodeExecutionService.fetchNodeExecutionsWithoutOldRetries(planExecutionId);
>     List<NodeExecution> nodeExecutionWithNullParams =
> ```

is this intentional. I don not see it use below
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 240 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqMpZA2Gdw5j5rYSt:-MxcqMpZA2Gdw5j5rYSu:bfyd5u3) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L240)):*
> ```Java
>             .collect(Collectors.toList());
>     if (isEmpty(nodeExecutions)) {
>       throw new InvalidRequestException("No nodes found for planExecutionId [" + planExecutionId + "]");
> ```

We should remove this. This can be a genuine case
___
*[870-orchestration/src/main/java/io/harness/OrchestrationLogCacheEventListener.java, line 39 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqV-Z1HXPIOc3CqMb:-MxcqV-Z1HXPIOc3CqMc:by7y7uf) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/870-orchestration/src/main/java/io/harness/OrchestrationLogCacheEventListener.java#L39)):*
> ```Java
>     for (CacheEntryEvent<? extends String, ? extends Long> event : events) {
>       String lockName = ORCHESTRATION_EXPIRY_LOCK + event.getKey();
>       try (AcquiredLock<?> lock = persistentLocker.tryToAcquireLock(lockName, Duration.ofSeconds(10))) {
> ```

check if we need locking here
___
*[870-orchestration/src/main/java/io/harness/engine/events/OrchestrationEventEmitter.java, line 33 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqfzGA6RamjpE0MVg:-MxcqfzGA6RamjpE0MVh:b-dj78e4) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/870-orchestration/src/main/java/io/harness/engine/events/OrchestrationEventEmitter.java#L33)):*
> ```Java
>   public void emitEvent(OrchestrationEvent event) {
>     /**
>     try (AutoLogContext ignore = OrchestrationEventUtils.obtainLogContext(event)) {
> ```

should not go to master
___
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqjBXAT52zFRhwYdI:-MxcqjBXAT52zFRhwYdJ:b-dj78e4) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java#L83)):*
> ```Java
>       authorityToUse = defaultAuthority;
>     } else if (!("ONPREM".equals(deployMode) || "KUBERNETES_ONPREM".equals(deployMode))) {
>       String versionPrefix = "v-" + versionInfo.getVersion().replace('.', '-') + "-";
> ```

should not go to master


<!-- Sent from Reviewable.io -->

2022-03-11 06:01 UTC, sahilhindwani-harness commented
___
*[860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationLogPublisher.java, line 82 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcoxM692f9FL2GYIVS:-MxrZDyy-IYXBxxih1FG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L82)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

extract these ifs in a function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-11 06:01 UTC, sahilhindwani-harness commented
___
*[870-orchestration/src/main/java/io/harness/OrchestrationLogCacheEventListener.java, line 39 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqV-Z1HXPIOc3CqMb:-MxrZEjq5oIhWeqingIU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/870-orchestration/src/main/java/io/harness/OrchestrationLogCacheEventListener.java#L39)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

check if we need locking here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-11 06:01 UTC, sahilhindwani-harness commented
___
*[870-orchestration/src/main/java/io/harness/engine/events/OrchestrationEventEmitter.java, line 33 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqfzGA6RamjpE0MVg:-MxrZKEt4xS5M1sRnDOX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/870-orchestration/src/main/java/io/harness/engine/events/OrchestrationEventEmitter.java#L33)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

should not go to master
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-11 06:02 UTC, sahilhindwani-harness commented
___
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqjBXAT52zFRhwYdI:-MxrZVN6Bcw9P5EiyLZN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java#L83)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

should not go to master
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-11 10:33 UTC, hextechpal requested changes
> Reviewed 17 of 18 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31224)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 240 at r1](https://reviewable.io/reviews/harness/harness-core/31224#-MxcqMpZA2Gdw5j5rYSt:-MxsXABd7lRX9k9oYTai:bqhjww6) ([raw file](https://github.com/harness/harness-core/blob/5f01de1a032b304aae2d9b86401a03cbeffd8dbb/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L240)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

We should remove this. This can be a genuine case
</blockquote></details>

this is true in errored i think we can remove
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 102 at r2](https://reviewable.io/reviews/harness/harness-core/31224#-MxsX1-E63Z-mxxyhpsI:-MxsX1-E63Z-mxxyhpsJ:b-zc7dwv) ([raw file](https://github.com/harness/harness-core/blob/3b22a6682c3ff532e750e6c1f9410733c85bc0d0/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L102)):*
> ```Java
> 
>   @Override
>   public boolean updateGraph(OrchestrationGraph orchestrationGraph) {
> ```

why we need this method?


<!-- Sent from Reviewable.io -->

2022-03-11 10:52 UTC, sahilhindwani-harness commented
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 102 at r2](https://reviewable.io/reviews/harness/harness-core/31224#-MxsX1-E63Z-mxxyhpsI:-MxsazXUAsZGy62-8Cto:bh4f2s7) ([raw file](https://github.com/harness/harness-core/blob/3b22a6682c3ff532e750e6c1f9410733c85bc0d0/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L102)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why we need this method?
</blockquote></details>

Not required now, will remove


<!-- Sent from Reviewable.io -->

2022-03-11 10:57 UTC, sahilhindwani-harness commented
___
*[870-orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java, line 82 at r3](https://reviewable.io/reviews/harness/harness-core/31224#-Mxsc8B1EN72lBzbSEeC:-Mxsc8B1EN72lBzbSEeD:b-cqsrvo) ([raw file](https://github.com/harness/harness-core/blob/009201d7cc07437d4a8cc747efebf31a06462f34/870-orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L82)):*
> ```Java
>         OrchestrationLogEvent.newBuilder().setPlanExecutionId(planExecutionId).build();
>     if (orchestrationLogConfiguration.isShouldUseBatching()) {
>       if (orchestrationLogCache.containsKey(planExecutionId)) {
> ```

Extract into a method


<!-- Sent from Reviewable.io -->

2022-03-11 11:57 UTC, sahilhindwani-harness commented
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 102 at r2](https://reviewable.io/reviews/harness/harness-core/31224#-MxsX1-E63Z-mxxyhpsI:-Mxsphvt4XE_BxHsJHzr:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3b22a6682c3ff532e750e6c1f9410733c85bc0d0/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L102)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Not required now, will remove
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-03-11 11:58 UTC, sahilhindwani-harness commented
trigger messagecheck

2022-03-11 13:01 UTC, archit-harness approved these changes
> Reviewed 1 of 14 files at r1, 4 of 18 files at r2, 5 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31224)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/OrchestrationModule.java, line 225 at r5](https://reviewable.io/reviews/harness/harness-core/31224#-Mxt20Qj1lWEKuZLN9RF:-Mxt20Qj1lWEKuZLN9RG:bppjfyh) ([raw file](https://github.com/harness/harness-core/blob/29222a8ba8a75a45a21103eb4231a3e8baf96e0a/870-orchestration/src/main/java/io/harness/OrchestrationModule.java#L225)):*
> ```Java
>       HarnessCacheManager harnessCacheManager, VersionInfoManager versionInfoManager) {
>     Cache<String, Long> cache = harnessCacheManager.getCache("orchestrationLogCache", String.class, Long.class,
>         AccessedExpiryPolicy.factoryOf(new Duration(TimeUnit.SECONDS, 5)),
> ```

as discussed we can make this 1 minute as maybe till 5 seconds there comes no update due to being stuck anywhere and it will expire without any update, increasing at least gives some chance to update it, like user accessing the graph



_Code quote:_
```Java
new Duration(TimeUnit.SECONDS, 5
```


<!-- Sent from Reviewable.io -->

2022-03-11 13:04 UTC, archit-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31224)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/OrchestrationModule.java, line 225 at r5](https://reviewable.io/reviews/harness/harness-core/31224#-Mxt20Qj1lWEKuZLN9RF:-Mxt3z6qEBxs0NzM8DDk:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/29222a8ba8a75a45a21103eb4231a3e8baf96e0a/870-orchestration/src/main/java/io/harness/OrchestrationModule.java#L225)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed we can make this 1 minute as maybe till 5 seconds there comes no update due to being stuck anywhere and it will expire without any update, increasing at least gives some chance to update it, like user accessing the graph
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-03-11 14:18 UTC, hextechpal approved these changes
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31224)* status: 11 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-11 14:18 UTC, archit-harness approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31224)* status: 8 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-03-13 14:23 UTC, merged