fix: [PL-21765]: Added proper Error messages when Request is not containing the mandatory fields.
harness/harness-core pull request #31260
Opened 2022-03-08 09:33 UTC by boopesh007

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-08 11:42 UTC, boopesh007 commented
trigger messagecheck

2022-03-08 11:43 UTC, boopesh007 commented
trigger codeformat

2022-03-08 11:43 UTC, boopesh007 commented
trigger checkstyle

2022-03-08 13:09 UTC, meenakshi-harness commented on 970-ng-commons/src/main/java/io/harness/utils/FullyQualifiedIdentifierHelper.java
> +        throw new InvalidRequestException("Invalid Request Exception: No org identifier provided.");
I think `Invalid Request Exception` is not required.

2022-03-08 13:41 UTC, meenakshi-harness commented on 970-ng-commons/src/test/java/io/harness/utils/FullyQualifiedIdentifierHelperTest.java
> +  }
Can we add case for :
1. ProjectIdentifier is not null, but orgId is null. 
2. ProjectIdentifier is not null, but accountId is null. 
3. OrgId level entity --> but accountId is null

2022-03-08 14:04 UTC, boopesh007 commented on 970-ng-commons/src/main/java/io/harness/utils/FullyQualifiedIdentifierHelper.java
> +        throw new InvalidRequestException("Invalid Request Exception: No org identifier provided.");
yes, @meenakshi-harness felt that but added as the reference had it. will change it.

2022-03-08 14:05 UTC, boopesh007 commented on 970-ng-commons/src/test/java/io/harness/utils/FullyQualifiedIdentifierHelperTest.java
> +  }
1. Is that my test checks 
2. I will add 
3. already added by Naman

2022-03-08 22:09 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31260)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[970-ng-commons/src/main/java/io/harness/utils/FullyQualifiedIdentifierHelper.java, line 31 at r3](https://reviewable.io/reviews/harness/harness-core/31260#-MxfZpUl96LlvzQx23KJ:-MxfZpUl96LlvzQx23KK:b3uojgz) ([raw file](https://github.com/harness/harness-core/blob/9008e19dc1c675d44e8fdd0f4b2fed1618854815/970-ng-commons/src/main/java/io/harness/utils/FullyQualifiedIdentifierHelper.java#L31)):*
> ```Java
>       return String.format("%s/%s/%s/%s", accountId, orgIdentifier, projectIdentifier, identifier);
>     } else if (EmptyPredicate.isNotEmpty(orgIdentifier)) {
>       if (EmptyPredicate.isEmpty(accountId)) {
> ```

I see repetition of code. We can modularize check for account id and use it at both places as function call only. We can do this for org id check also, even though its called only once.

Method could be a void function like: validateAccountId() and it will throw exception if validation fails.


<!-- Sent from Reviewable.io -->

2022-03-09 06:51 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31260)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[970-ng-commons/src/main/java/io/harness/utils/FullyQualifiedIdentifierHelper.java, line 33 at r4](https://reviewable.io/reviews/harness/harness-core/31260#-MxhRN3F1mXHwq76nuBO:-MxhRN3G-_Au0y5dvRW2:b-ysa4lo) ([raw file](https://github.com/harness/harness-core/blob/3edff3eb23ee1d27bde89b3b5c11aad899e9c634/970-ng-commons/src/main/java/io/harness/utils/FullyQualifiedIdentifierHelper.java#L33)):*
> ```Java
>       throw new InvalidRequestException("No identifier provided.");
>     }
>   }
> ```

missing newline after this method


<!-- Sent from Reviewable.io -->

2022-03-09 06:59 UTC, mohitg0795 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31260#-:-MxhTL2B3ktSbVHDQDqe:bnfp4nl)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-09 08:03 UTC, meenakshi-harness reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31260)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-09 08:03 UTC, meenakshi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31260)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-09 08:27 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31260#-:-MxhmUJ-EeCCAJJwJDbT:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-09 08:28 UTC, merged