[CDS-34812]: Added Yaml support and GitSync entities to Environment
harness/harness-core pull request #31308
Opened 2022-03-09 12:57 UTC by shivamnegi94

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-10 13:09 UTC, archit-harness requested changes
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31308)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentResourceTest.java, line 85 at r1](https://reviewable.io/reviews/harness/harness-core/31308#-MxnvbIq7UmiFqktw-dw:-MxnvbIq7UmiFqktw-dx:b-d02rm5) ([raw file](https://github.com/harness/harness-core/blob/cb386b351692148a5ac228d53d3b4bc929906db3/120-ng-manager/src/test/java/io/harness/ng/core/environment/resources/EnvironmentResourceTest.java#L85)):*
> ```Java
>                                  .yaml("environment:\n  orgIdentifier: \"ORG_ID\"\n  "
>                                      + "projectIdentifier: \"PROJECT_ID\"\n  identifier: \"IDENTIFIER\"\n  "
>                                      + "tags:\n    k1: \"v1\"\n  name: \"ENV\"\n  type: \"PreProduction\"\n")
> ```

You can read yaml from a file rather than putting constant yaml here



_Code quote:_
```Java
                                 .yaml("environment:\n  orgIdentifier: \"ORG_ID\"\n  "
                                     + "projectIdentifier: \"PROJECT_ID\"\n  identifier: \"IDENTIFIER\"\n  "
                                     + "tags:\n    k1: \"v1\"\n  name: \"ENV\"\n  type: \"PreProduction\"\n")
```


<!-- Sent from Reviewable.io -->

2022-04-06 10:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31308) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: shivamnegi94<br/>:x: sahilhindwani-harness<br/>:x: vaibhav-si<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31308) it.</sub>

2022-04-06 10:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31308) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: sahilhindwani-harness<br/>:x: vaibhav-si<br/>:x: shivamnegi94<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31308) it.</sub>

2022-08-01 20:09 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/31308)

2022-08-02 05:01 UTC, closed without merging