fix: [CDS-34865]: code changes in NG related to the FFs USE_HELM_REPO…
harness/harness-core pull request #31350
Opened 2022-03-10 10:03 UTC by achyuth-harness

…_FLAGS, HELM_CHART_VERSION_STRICT_MATCH, HELM_VERSION_3_8_0, DELETE_HELM_REPO_CACHE_DIR

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-14 11:25 UTC, shubham-in10se reviewed
add one test where you are also validating the V380 for HelmVersion

2022-03-14 11:25 UTC, shubham-in10se commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNG.java
> +        helmPath = InstallUtils.getNewHelm3Path();
```suggestion
        helmPath = InstallUtils.getHelm380Path();
```

2022-03-14 11:25 UTC, shubham-in10se commented on 125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java
> +  @Inject public CDFeatureFlagHelper cdFeatureFlagHelper;
why `public` .?

2022-03-15 06:11 UTC, shubham-in10se requested changes
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31350)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 134 at r1](https://reviewable.io/reviews/harness/harness-core/31350#-MxnHEOK9qFqckj0qqu3-r1-134:-MyBBmLnCiMIfD0lyn4V:b-ey4n0p) ([raw file](https://github.com/harness/harness-core/blob/d8a50460919f1b814ca8338063c14148f7b842ca/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L134)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

So that we can inherit this field, i.e. CDStepHelper is extended by K8sStepHelper and NativeHelmStepHelper 
</blockquote></details>

let us make it `protected` in that case.


<!-- Sent from Reviewable.io -->

2022-03-15 06:14 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31350)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java, line 134 at r1](https://reviewable.io/reviews/harness/harness-core/31350#-MxnHEOK9qFqckj0qqu3-r1-134:-MyBCYon6dZ3lzP5y6yc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8a50460919f1b814ca8338063c14148f7b842ca/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L134)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let us make it `protected` in that case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-15 06:15 UTC, shubham-in10se approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31350)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-15 06:26 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31350#-:-MyBFVzfCm8hafVH3mol:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-15 06:48 UTC, merged