[PL-23497]: Fix the issue where the git provider type was not sent from git entity resource
harness/harness-core pull request #31372
Opened 2022-03-10 17:56 UTC by DeepakPatankar

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-11 06:39 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java, line 53 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgzrB0tM5YjaqEVy9:-MxrgzrC8D5nMKKufzOA:b-o23ebv) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java#L53)):*
> ```Java
>   @org.springframework.data.annotation.Id @org.mongodb.morphia.annotations.Id private String uuid;
>   private String gitConnectorId;
>   private io.harness.delegate.beans.connector.ConnectorType gitRepoProviderType;
> ```

it should be RepoProvider, right? Why is it connectorType?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 186 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgW3lCtSaVEgsGxjm:-MxrgW3m0blNHbm8ZvCu:b-hyve8p) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L186)):*
> ```Java
> 
>   @VisibleForTesting
>   RepoProviders getGitProvider(ConnectorType gitRepoProviderType, String repositoryUrl) {
> ```

Lets name arguments correctly, otherwise it just increases confusion while reading code.

If its ConnectorType, then lets name it connectorType.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 206 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgiAi-ES7cS6exwAS:-MxrgiAi-ES7cS6exwAT:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L206)):*
> ```Java
>   }
> 
>   private RepoProviders getRepoProviderFromConnectorType(ConnectorType gitRepoProviderType) {
> ```

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 209 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-Mxrgq1X2pLjSBanG7T1:-Mxrgq1X2pLjSBanG7T2:b-x6l7mc) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L209)):*
> ```Java
>     switch (gitRepoProviderType) {
>       case GITHUB:
>         return RepoProviders.GITHUB;
> ```

Can we fix the enum class name here? It should be "RepoProvider"
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 215 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-Mxrgnby8CMaYpyhuMxP:-MxrgnbzC6YdetmdQT7h:b-kbkzz9) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L215)):*
> ```Java
>         return RepoProviders.GITLAB;
>       default:
>         return null;
> ```

we should throw exception here
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImplTest.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-Mxrgy7hA0YdOQD0Z6VM:-Mxrgy7hA0YdOQD0Z6VN:b-hq2abc) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/test/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImplTest.java#L11)):*
> ```Java
> 
> import static io.harness.rule.OwnerRule.BHAVYA;
> import static io.harness.rule.OwnerRule.DEEPAK;
> ```

redundant change


<!-- Sent from Reviewable.io -->

2022-03-11 08:32 UTC, abhinav-harness approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-11 13:00 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 1 change requests. 6. unresolved discussions. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java, line 53 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgzrB0tM5YjaqEVy9:-Mxt1D0dDAcdhEZeMCwi:b-xod6v8) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it should be RepoProvider, right? Why is it connectorType?
</blockquote></details>

It was ConnectorType in GitSyncConfig. I created a tech debt item to fix it.  

Fixed it for GitEntities
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 186 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgW3lCtSaVEgsGxjm:-Mxt1cS9E23iiO38WPDT:b-swkrde) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L186)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets name arguments correctly, otherwise it just increases confusion while reading code.

If its ConnectorType, then lets name it connectorType.
</blockquote></details>

Right!!

Fixed it
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 206 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgiAi-ES7cS6exwAS:-Mxt1eQV76KnR2qhsPsc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L206)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 209 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-Mxrgq1X2pLjSBanG7T1:-Mxt1h3d5r_uPu_QxQxO:byrldm1) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L209)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we fix the enum class name here? It should be "RepoProvider"
</blockquote></details>

Class name rename won't be an API breaking change right?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 215 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-Mxrgnby8CMaYpyhuMxP:-Mxt20Zu4GJLbyXrrm2S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L215)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should throw exception here
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImplTest.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-Mxrgy7hA0YdOQD0Z6VM:-Mxt36wY3X9VFnOuZcri:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/test/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImplTest.java#L11)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

redundant change
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-15 09:56 UTC, abhinav-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 16 file(s) to review. 1 change requests. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-9zm--5y2UdPeYMh:-MyC-9zm--5y2UdPeYMi:b-11uhbi) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
> ```Java
>       UpdateResult updateResultForGithub = mongoTemplate.updateMulti(
>           query(criteriaForErrorsInGithub), updatingRecordWithGithubType, GitFileLocation.class);
>       log.info("Total {} records updated with value github", updateResultForGithub.getModifiedCount());
> ```

can you give records being updated here?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java, line 63 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-N2q8wuvcuJEtrkd:-MyC-N2q8wuvcuJEtrke:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java#L63)):*
> ```Java
> 
>       log.info("UpdateTheRepoProvidersInGitSyncErrors Migration completed");
>     } catch (Exception ex) {
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-03-15 09:59 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 16 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 74 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-zawCbag87cSXIlL:-MyC-zawCbag87cSXIlM:bldzawg) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L74)):*
> ```Java
>     switch (repoProviders) {
>       case GITHUB:
>         return String.format("%s/blob/%s%s", repoUrl, branch, completeFilePathWithSlash);
> ```

we are maintaining a tough things here - github could have done things on on prem over the versions to change these URLs and could also do it in future - Any reason why we are storing a thing which is very easy to compute and give back during runtime?


<!-- Sent from Reviewable.io -->

2022-03-15 11:30 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 16 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 74 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-zawCbag87cSXIlL:-MyCKta59a4G8CdLc4Zv:b-94s0f2) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L74)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

we are maintaining a tough things here - github could have done things on on prem over the versions to change these URLs and could also do it in future - Any reason why we are storing a thing which is very easy to compute and give back during runtime?
</blockquote></details>

Because of the reason you mentioned above, we are calculating it at runtime and not persisting it


<!-- Sent from Reviewable.io -->

2022-03-16 07:24 UTC, ankit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 16 file(s) to review. 3 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java, line 53 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgzrB0tM5YjaqEVy9:-MyGZONH33RTpkPD9srQ:byzqz9i) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Thanks.

 Do we also want to rename it "repoProvider" only? We should be as simple as possible in our naming going forward. We don't need to add redundant suffixes/prefixes if not required.
</blockquote></details>

Do we need to store repoProviderType? Can't we infer that from gitConnectorId associated with this file  or from gitSyncConfigId?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 46 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZjgL9lJUmAjXXQbT:-MyGZjgL9lJUmAjXXQbU:b-qr6uvt) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L46)):*
> ```Java
>   @Schema(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @JsonIgnore String accountId;
>   @Schema(hidden = true) @JsonIgnore String lastCommitId;
>   @Schema(description = "The url of the file") String filePathUrl;
> ```

entityUrl
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZg8OANNxEUdTQL2N:-MyGZg8OANNxEUdTQL2O:bu4f4li) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L47)):*
> ```Java
>   @Schema(hidden = true) @JsonIgnore String lastCommitId;
>   @Schema(description = "The url of the file") String filePathUrl;
>   @Schema(description = "The git repo provider where the file is stored") RepoProviders repoProviderType;
> ```

Any reason to include repoProviderType here?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java, line 55 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGaHMr1HQy0lmc9flh:-MyGaHMr1HQy0lmc9fli:b7ioid1) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java#L55)):*
> ```Java
>   @Schema(description = "Additional Details of Git Sync Error based on its type")
>   GitSyncErrorDetailsDTO additionalErrorDetails;
>   @Schema(description = "The git provider type") RepoProviders repoProviderType;
> ```

Why not just include entityUrl?
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 69 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGb5AT30Gdd4t7tPW7:-MyGb5AT30Gdd4t7tPW8:b1vrqxs) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L69)):*
> ```Java
>   }
> 
>   public static String getTheFilePathUrl(
> ```

We should have this logic of generating url in RepoProviders itself


<!-- Sent from Reviewable.io -->

2022-03-16 17:51 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 16 file(s) to review. 3 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java, line 53 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-MxrgzrB0tM5YjaqEVy9:-MyIl8rm21W-FDq81Zz9:b-9si29u) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/GitFileLocation.java#L53)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we need to store repoProviderType? Can't we infer that from gitConnectorId associated with this file  or from gitSyncConfigId?
</blockquote></details>

@ankit-harness  We can infer it from the git sync config id. But storing the repoProvider is also easy and,  in future if our logic/fix depends on the repoProvider then it will be easy.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZg8OANNxEUdTQL2N:-MyIoqIx3O-qCsDZbZAn:b-va9upa) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L47)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason to include repoProviderType here?
</blockquote></details>

I also wanted to avoid the repoProvidertype here, but this same DTO is used for the rest layer as well as inter-service communication.

When saving the git sync error the caller method should send us the repoProvider. Hence for inter-service communication, I had to add this field
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 209 at r1](https://reviewable.io/reviews/harness/harness-core/31372#-Mxrgq1X2pLjSBanG7T1:-MyIpcNlCYvpRi_i3cpf:bbj0fs5) ([raw file](https://github.com/harness/harness-core/blob/899c0359f287b9f20ab1a4caef990e817e4a3e71/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L209)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Does it make any changes on swagger? If yes, then its a breaking change.
</blockquote></details>

Yes its a breaking change, hence will do it separately
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java, line 55 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGaHMr1HQy0lmc9flh:-MyIpirqA2uOGqrrj-6V:b-dxhxkt) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java#L55)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why not just include entityUrl?
</blockquote></details>

The git sync error can be of type connectivity error or git to harness error.

The error-specific fields are present in the   GitSyncErrorDetailsDTO class.  I have added entityUrl there
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-9zm--5y2UdPeYMh:-MyIq3I6-BVOMvBhEEaP:b2t97aa) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

can you give records being updated here?
</blockquote></details>

The number of records will be extremely hugh. Hence we cannot log their ids here.


<!-- Sent from Reviewable.io -->

2022-03-16 18:34 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZg8OANNxEUdTQL2N:-MyJ-V_QEOx_nEhqLhki:b7net7l) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L47)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

I also wanted to avoid the repoProvidertype here, but this same DTO is used for the rest layer as well as inter-service communication.

When saving the git sync error the caller method should send us the repoProvider. Hence for inter-service communication, I had to add this field
</blockquote></details>

@deepakpatankar we can avoid sending it in response. I think something like @Jsonignore should work here.


<!-- Sent from Reviewable.io -->

2022-03-16 18:38 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 40 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ0KDz624axrSebVfT:-MyJ0KDz624axrSebVfU:bbnt6bd) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L40)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error("Failed to generate Git Provider Repository Url {}", repositoryUrl, e);
> ```

error should be : Failed to generate Git Provider "for" repository url {}


<!-- Sent from Reviewable.io -->

2022-03-16 18:38 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 42 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ0ShBBraAqWbHcT8T:-MyJ0ShBBraAqWbHcT8U:bjwjs2q) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L42)):*
> ```Java
>       log.error("Failed to generate Git Provider Repository Url {}", repositoryUrl, e);
>     }
>     return RepoProviders.UNKNOWN;
> ```

Why do we send UNKNOWN here, we should simply avoid such situations and throw error right?


<!-- Sent from Reviewable.io -->

2022-03-16 18:45 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 225 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2BIi9GhQLrQHjWOm:-MyJ2BIi9GhQLrQHjWOn:bs5pf2) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L225)):*
> ```Java
>   }
> 
>   private String getFilePathUrl(String filePathUrl, String repoUrl, String branch, String folderPath, String filePath) {
> ```

Is this redundant code?


<!-- Sent from Reviewable.io -->

2022-03-16 18:47 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 527 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2Y6l3A8ENijfQvbd:-MyJ2Y6l3A8ENijfQvbe:b-wxlj7c) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L527)):*
> ```Java
>       String errorMessage, ChangeSet changeSet, List<Scope> scopes) {
>     String repoUrl = gitToHarnessProcessingInfo.getRepoUrl();
>     String branchName = gitToHarnessProcessingInfo.getBranchName();
> ```

why this variable naming? 


<!-- Sent from Reviewable.io -->

2022-03-16 18:48 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 528 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2qV0-Gq8Eji4ZoWn:-MyJ2qV0-Gq8Eji4ZoWo:b-qjxggh) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L528)):*
> ```Java
>     String repoUrl = gitToHarnessProcessingInfo.getRepoUrl();
>     String branchName = gitToHarnessProcessingInfo.getBranchName();
>     final List<YamlGitConfigDTO> yamlGitConfigs = gitToHarnessProcessingInfo.getYamlGitConfigs();
> ```

can we avoid this variable naming as well if not required. 


<!-- Sent from Reviewable.io -->

2022-03-16 18:51 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java, line 55 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGaHMr1HQy0lmc9flh:-MyJ3JVJ6MqWZaes_kLb:b7g26eq) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java#L55)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The git sync error can be of type connectivity error or git to harness error.

The error-specific fields are present in the   GitSyncErrorDetailsDTO class.  I have added entityUrl there
</blockquote></details>

Why is repo provider required in this case? I assume coz UI will use it to build urls? If yes, then why aren't we sending pre-computed urls here as we do in other locations now?


<!-- Sent from Reviewable.io -->

2022-03-16 18:51 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ3V9ODqEIjJjGiVct:-MyJ3V9P2to41qyhP_FE:b-9h88c2) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java#L37)):*
> ```Java
>   @Schema(description = GitSyncApiConstants.COMMIT_MESSAGE_PARAM_MESSAGE) String commitMessage;
>   @Schema(description = "Commit Id that resolved the Git Sync Error") String resolvedByCommitId;
>   @Schema(description = "The url of the file") String filePathUrl;
> ```

Please make this description as a constant and use it commonly everwhere.


<!-- Sent from Reviewable.io -->

2022-03-16 18:53 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/remote/GitSyncErrorMapper.java, line 61 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ3wIjCEr3hvb_5KZg:-MyJ3wIjCEr3hvb_5KZh:bdnah0p) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/remote/GitSyncErrorMapper.java#L61)):*
> ```Java
>     if (errorType == GitSyncErrorType.CONNECTIVITY_ISSUE) {
>       return null;
>     } else if (errorType == FULL_SYNC || errorType == GitSyncErrorType.GIT_TO_HARNESS) {
> ```

In other cases, its written as GitSyncErrorType.CONNECTIVITY_ISSUE etc, here why it isn't written as GitSyncErrorType.FULL_SYNC? Can we make it consistent at all 3 places?


<!-- Sent from Reviewable.io -->

2022-03-16 19:06 UTC, mohitg0795 commented
___
*[970-api-services-beans/src/main/java/io/harness/gitsync/common/dtos/RepoProviders.java, line 35 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ6zIh532OGlYBl3Vs:-MyJ6zIiCAbOPSjwqp9H:bwrdvby) ([raw file](https://github.com/harness/harness-core/blob/f546fd5dac756b68c287cda22be372cff889fc5e/970-api-services-beans/src/main/java/io/harness/gitsync/common/dtos/RepoProviders.java#L35)):*
> ```Java
>   }
> 
>   public static String getTheFilePathUrl(
> ```

why is this method here? It doesn't belong here right?


<!-- Sent from Reviewable.io -->

2022-03-16 19:08 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java, line 29 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ7QW-2IXEGWXYbYTs:-MyJ7QW-2IXEGWXYbYTt:bu7zhey) ([raw file](https://github.com/harness/harness-core/blob/f546fd5dac756b68c287cda22be372cff889fc5e/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java#L29)):*
> ```Java
>   @Category(UnitTests.class)
>   public void test_getGitProvider() {
>     RepoProviders gitProvider = RepoProviderHelper.getGitProvider("https://github,com/wings-software/portal");
> ```

how is this test working? I see it has "," after github instead of "."


<!-- Sent from Reviewable.io -->

2022-03-16 19:09 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java, line 29 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ7XCm8E4vfkyfJjbQ:-MyJ7XCm8E4vfkyfJjbR:b-4l2r23) ([raw file](https://github.com/harness/harness-core/blob/f546fd5dac756b68c287cda22be372cff889fc5e/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java#L29)):*
> ```Java
>   @Category(UnitTests.class)
>   public void test_getGitProvider() {
>     RepoProviders gitProvider = RepoProviderHelper.getGitProvider("https://github,com/wings-software/portal");
> ```

Also, we should put similar tests for SSH type git providers as well. The url format changes in that case.


<!-- Sent from Reviewable.io -->

2022-03-16 19:17 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 49 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9SFq4iP84LuCtDLs:-MyJ9SFq4iP84LuCtDLt:b-xjcx9l) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L49)):*
> ```Java
>           update(GitFileLocation.GitFileLocationKeys.repoProviderType, RepoProviders.GITHUB);
>       Criteria criteriaForErrorsInGithub =
>           Criteria.where(GitFileLocation.GitFileLocationKeys.repo).not().regex("/.*bitbucket.*/");
> ```

regex is wrong here. Have we tested this code? It won't work I see.


<!-- Sent from Reviewable.io -->

2022-03-16 19:18 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java, line 45 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9mDx6LGVh3UGBn8f:-MyJ9mDx6LGVh3UGBn8g:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java#L45)):*
> ```Java
>     log.info("Started the migration to add the repo providers in git sync errors");
> 
>     try {
> ```

same as above.


<!-- Sent from Reviewable.io -->

2022-03-16 19:19 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 17 file(s) to review. 3 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 552 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ34gNBOMI0kffT7ab:-MyJ34gNBOMI0kffT7ac:bc2q1ho) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L552)):*
> ```Java
>   private RepoProviders getRepoProviderType(List<YamlGitConfigDTO> yamlGitConfigs) {
>     if (isEmpty(yamlGitConfigs)) {
>       return null;
> ```

Please don't introduce null in such cases. If we expect a value here, please throw error.


<!-- Sent from Reviewable.io -->

2022-03-17 08:07 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 17 file(s) to review. 3 change requests. 24. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 46 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZjgL9lJUmAjXXQbT:-MyLmiQuAEp1riVdXWTX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L46)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

entityUrl
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZg8OANNxEUdTQL2N:-MyLmpy2DbEmFtZWq38v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@deepakpatankar we can avoid sending it in response. I think something like @Jsonignore should work here.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 40 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ0KDz624axrSebVfT:-MyLmzOlEsW5UQusEVYS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

error should be : Failed to generate Git Provider "for" repository url {}
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 42 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ0ShBBraAqWbHcT8T:-MyLnA1jBA93s9fpsa5V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L42)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why do we send UNKNOWN here, we should simply avoid such situations and throw error right?
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 225 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2BIi9GhQLrQHjWOm:-MyLnOV_CyoIKETQoGEC:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L225)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is this redundant code?
</blockquote></details>

Removed
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 527 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2Y6l3A8ENijfQvbd:-MyLnSde45G_ZbowFR-y:b3kre) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L527)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why this variable naming? 
</blockquote></details>

?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 528 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2qV0-Gq8Eji4ZoWn:-MyLnUfPCflah-beceEz:b3kre) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L528)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we avoid this variable naming as well if not required. 
</blockquote></details>

?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 552 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ34gNBOMI0kffT7ab:-MyLpgku2ZnJIqhthqzh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L552)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please don't introduce null in such cases. If we expect a value here, please throw error.
</blockquote></details>

Done.



_Code quote:_
```Java
getRepoProviderType
```
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java, line 55 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGaHMr1HQy0lmc9flh:-MyLpmq09qGTVhdPcVjn:bz44m9v) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is repo provider required in this case? I assume coz UI will use it to build urls? If yes, then why aren't we sending pre-computed urls here as we do in other locations now?
</blockquote></details>

No UI doesn't need it to build urls. We included repoProvider because:

This same DTO is used for intern service communication and REst APIs. For Rest ApIs we don't need repoProvider. But we need it for the interservice communication.


`If yes, then why aren't we sending pre-computed urls here as we do in other locations now?`

The pre computation will be done at the time of storing the record. We are not planning to store entityUrl in the db, hence we don't need the precomputation.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ3V9ODqEIjJjGiVct:-MyLs--e-g1T0EV3qnyv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java#L37)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please make this description as a constant and use it commonly everwhere.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/remote/GitSyncErrorMapper.java, line 61 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ3wIjCEr3hvb_5KZg:-MyLs93RApMXpQkEARSx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/remote/GitSyncErrorMapper.java#L61)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

In other cases, its written as GitSyncErrorType.CONNECTIVITY_ISSUE etc, here why it isn't written as GitSyncErrorType.FULL_SYNC? Can we make it consistent at all 3 places?
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 38 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9b2B9B8_s8M9XWrO:-MyLtXhxAevORMbJegVn:b-896fix [...]

2022-03-17 09:30 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 46 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZjgL9lJUmAjXXQbT:-MyMCbSREHTJGkrWVGeH:bwyvevu) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L46)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why is JsonIgnore applied on this field? Then it won't come up in the response right?


<!-- Sent from Reviewable.io -->

2022-03-17 09:30 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZg8OANNxEUdTQL2N:-MyMCjux5yWNI0MYW3Yq:bfsgz4t) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L47)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see JsonIgnore here


<!-- Sent from Reviewable.io -->

2022-03-17 09:31 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 42 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ0ShBBraAqWbHcT8T:-MyMCp_J3WYl1__OdVlf:b-2yloph) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L42)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Arey, why are we sending null now. Please don't introduce unnecessary null in the codebase. Here simply throwing any error seems to be the best solution. Are there any concerns with it?


<!-- Sent from Reviewable.io -->

2022-03-17 09:32 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 527 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2Y6l3A8ENijfQvbd:-MyMD4L06WTzMCQfAP3C:b-khamt8) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L527)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

?
</blockquote></details>

This is an extra code that has been added and I don't see any purpose of this extra variable creation. It was correctly used directly inside the dto creation earlier. Any particular reason we added this variable here?


<!-- Sent from Reviewable.io -->

2022-03-17 09:32 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 528 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2qV0-Gq8Eji4ZoWn:-MyMDDM72R_94uJaa6lK:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L528)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

?
</blockquote></details>

same as above


<!-- Sent from Reviewable.io -->

2022-03-17 09:34 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java, line 55 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGaHMr1HQy0lmc9flh:-MyMDOfE0_o5ABBMGcUU:b-knxlut) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java#L55)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

No UI doesn't need it to build urls. We included repoProvider because:

This same DTO is used for intern service communication and REst APIs. For Rest ApIs we don't need repoProvider. But we need it for the interservice communication.


`If yes, then why aren't we sending pre-computed urls here as we do in other locations now?`

The pre computation will be done at the time of storing the record. We are not planning to store entityUrl in the db, hence we don't need the precomputation.
</blockquote></details>

So, we can use JsonIgnore here right? And also remove redundant annotations on the field as we don't plan to expose them on swagger at all.


<!-- Sent from Reviewable.io -->

2022-03-17 09:34 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ3V9ODqEIjJjGiVct:-MyMDc355sK-oXvDjoic:b7c9lxs) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java#L37)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see somewhere else this constant wasn't used above. Please can you make sure we use only this constant and no hard-coded description at all places for entity url.


<!-- Sent from Reviewable.io -->

2022-03-17 09:37 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 49 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9SFq4iP84LuCtDLs:-MyMED2gASvqjLZDCIua:bev7vkn) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L49)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

This is working fine. Can you please point out the issue which you see.
</blockquote></details>

How is github working with regex="bitbucket"?


<!-- Sent from Reviewable.io -->

2022-03-17 09:38 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r5](https://reviewable.io/reviews/harness/harness-core/31372#-MyMEOa-90T9ntZvhJOZ:-MyMEOa-90T9ntZvhJO_:b1r8hti) ([raw file](https://github.com/harness/harness-core/blob/6447bade1d34f3429ceb32815814740fd9c986b2/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
> ```Java
>     Criteria criteriaForErrorsInBitbucket =
>         Criteria.where(GitFileLocation.GitFileLocationKeys.repo).regex("/.*bitbucket.*/");
>     UpdateResult updateResult = mongoTemplate.updateMulti(
> ```

This update query seems to be same for both cases, can we make it common.

Also, I see criteria generation logic is also common apart from the input regex, we can make that also moduler


<!-- Sent from Reviewable.io -->

2022-03-17 09:40 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java, line 68 at r5](https://reviewable.io/reviews/harness/harness-core/31372#-MyMErpd03oXCjs-wnQ5:-MyMErpd03oXCjs-wnQ6:b-lzevu) ([raw file](https://github.com/harness/harness-core/blob/6447bade1d34f3429ceb32815814740fd9c986b2/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java#L68)):*
> ```Java
>     Update updatingRecordWithGithubType = update(GitSyncError.GitSyncErrorKeys.repoProvider, RepoProviders.GITHUB);
>     Criteria criteriaForErrorsInGithub =
>         Criteria.where(GitSyncError.GitSyncErrorKeys.repoUrl).not().regex("/.*bitbucket.*/");
> ```

same comments as above


<!-- Sent from Reviewable.io -->

2022-03-17 09:40 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java, line 29 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ7QW-2IXEGWXYbYTs:-MyMEwgpEH0Ab88ANJ1E:byr02fh) ([raw file](https://github.com/harness/harness-core/blob/fae8a7cff296dbb4d546e28725ec585061c24c46/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java#L29)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The current logic is that it it contains github, it is a github repo. 

I am removing this function itself as it is error prone.
</blockquote></details>

what if I create a bitbucket repo with github name in it? Then our logic is gone, right?


<!-- Sent from Reviewable.io -->

2022-03-17 09:41 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java, line 29 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ7XCm8E4vfkyfJjbQ:-MyMF3t9B725k5mHRTXp:b-nlz0oq) ([raw file](https://github.com/harness/harness-core/blob/fae8a7cff296dbb4d546e28725ec585061c24c46/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java#L29)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

sure in the unit test pr, i will take care of this cases too
</blockquote></details>

Can we add it here rn itself, these are basic cases and we don't know if these would work or get tested.


<!-- Sent from Reviewable.io -->

2022-03-17 09:42 UTC, mohitg0795 commented
___
*[970-api-services-beans/src/main/java/io/harness/gitsync/common/dtos/RepoProviders.java, line 35 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ6zIh532OGlYBl3Vs:-MyMFRlUDB7nbpHDJazy:bwoj433) ([raw file](https://github.com/harness/harness-core/blob/fae8a7cff296dbb4d546e28725ec585061c24c46/970-api-services-beans/src/main/java/io/harness/gitsync/common/dtos/RepoProviders.java#L35)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Based on the repo provider, we are providing the entityurl here. Since the logic is related to repoProviders, we are keeping this function hhere.
</blockquote></details>

I think we have a repoProviderHelper for such actions right? RepoProviderDTO shouldn't have this method.


<!-- Sent from Reviewable.io -->

2022-03-17 09:56 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 18 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 46 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZjgL9lJUmAjXXQbT:-MyMIZnfCgbn0XABc4oG:b-9chvtn) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is JsonIgnore applied on this field? Then it won't come up in the response right?
</blockquote></details>

Fixing this issue
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 49 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9SFq4iP84LuCtDLs:-MyMIHo05-2wfXVJpxEo:bz28xdm) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

How is github working with regex="bitbucket"?
</blockquote></details>

The regex there is that it should not contain bitbucket


<!-- Sent from Reviewable.io -->

2022-03-17 11:30 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 19 file(s) to review. 3 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZg8OANNxEUdTQL2N:-MyMd3hd670XKfdO4ek8:bta16xh) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I don't see JsonIgnore here
</blockquote></details>

Please add constant for this description as well.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 46 at r6](https://reviewable.io/reviews/harness/harness-core/31372#-MyMczrHDIf891WtjyJa:-MyMczrHDIf891WtjyJb:b-9pje21) ([raw file](https://github.com/harness/harness-core/blob/616c91befc5f553b7d4c11680566dc8f18ef1d61/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L46)):*
> ```Java
>   @Schema(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @JsonIgnore String accountId;
>   @Schema(hidden = true) @JsonIgnore String lastCommitId;
>   @Schema(description = "The url of the file in git")  String entityUrl;
> ```

description is hard coded here, it should be a constant as requested previously.


<!-- Sent from Reviewable.io -->

2022-03-17 11:31 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 49 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9SFq4iP84LuCtDLs:-MyMdC5j4PF0xFiapKJ4:b-nm8izy) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L49)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The regex there is that it should not contain bitbucket
</blockquote></details>

I think lets not be hacky over here. Lets put the correct one. This is a very hacky approach to do things.


<!-- Sent from Reviewable.io -->

2022-03-17 13:50 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 19 file(s) to review. 3 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGZg8OANNxEUdTQL2N:-MyN4kdBBcvEXuXbQkvS:bjkzaan) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please add constant for this description as well.
</blockquote></details>

added jsonignore
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java, line 46 at r6](https://reviewable.io/reviews/harness/harness-core/31372#-MyMczrHDIf891WtjyJa:-MyN4ISZDB0UdH64t3tP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/616c91befc5f553b7d4c11680566dc8f18ef1d61/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitSyncEntityDTO.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

description is hard coded here, it should be a constant as requested previously.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 42 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ0ShBBraAqWbHcT8T:-MyN6JgAE2HywMAkDnce:bdlv6fp) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L42)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Arey, why are we sending null now. Please don't introduce unnecessary null in the codebase. Here simply throwing any error seems to be the best solution. Are there any concerns with it?
</blockquote></details>

Removed this function
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 527 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2Y6l3A8ENijfQvbd:-MyN6_wz6kQlt_jaD-NS:b-m5othl) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L527)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is an extra code that has been added and I don't see any purpose of this extra variable creation. It was correctly used directly inside the dto creation earlier. Any particular reason we added this variable here?
</blockquote></details>

Reverted the change
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java, line 528 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ2qV0-Gq8Eji4ZoWn:-MyN6ki0CrbBD8cdIO2T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/gittoharness/GitToHarnessProcessorServiceImpl.java#L528)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java, line 55 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyGaHMr1HQy0lmc9flh:-MyN70XZDlGi7im78Ttn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitSyncErrorDTO.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

So, we can use JsonIgnore here right? And also remove redundant annotations on the field as we don't plan to expose them on swagger at all.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ3V9ODqEIjJjGiVct:-MyN72Lt-Q4MoeH0tUla:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/gitsyncerror/dtos/GitToHarnessErrorDetailsDTO.java#L37)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see somewhere else this constant wasn't used above. Please can you make sure we use only this constant and no hard-coded description at all places for entity url.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-17 13:53 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 19 file(s) to review. 3 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 49 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9SFq4iP84LuCtDLs:-MyN8SvXAPhabAf80N-Z:bevvm0) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think lets not be hacky over here. Lets put the correct one. This is a very hacky approach to do things.
</blockquote></details>

There cannot be a any correct one for github as for github we support the github enterprise also.

For bitbucket we support only cloud, hence only we are able to do this migration. 

The bitbucket cloud always contains the name bitbucket.org. So the entities which has bitbucket belongs to the bitbucket cloud and the rest belongs to github


<!-- Sent from Reviewable.io -->

2022-03-17 13:55 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 19 file(s) to review. 3 change requests. 20. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r5](https://reviewable.io/reviews/harness/harness-core/31372#-MyMEOa-90T9ntZvhJOZ:-MyN8yJOB3VqlP0HW_zV:btzal7a) ([raw file](https://github.com/harness/harness-core/blob/6447bade1d34f3429ceb32815814740fd9c986b2/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This update query seems to be same for both cases, can we make it common.

Also, I see criteria generation logic is also common apart from the input regex, we can make that also moduler
</blockquote></details>

Criteria is different for github and bitbucket.. 

This function looks simple(only 4line) and easy to understand. In my opinion, we don't need to break it furthur.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java, line 68 at r5](https://reviewable.io/reviews/harness/harness-core/31372#-MyMErpd03oXCjs-wnQ5:-MyN9Bqa8pmu0c3lWNN_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6447bade1d34f3429ceb32815814740fd9c986b2/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitSyncErrors.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same comments as above
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java, line 29 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ7QW-2IXEGWXYbYTs:-MyN9D3b59jNC8-Fixe8:b-2gucuq) ([raw file](https://github.com/harness/harness-core/blob/fae8a7cff296dbb4d546e28725ec585061c24c46/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if I create a bitbucket repo with github name in it? Then our logic is gone, right?
</blockquote></details>

deleted this function
___
*[136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java, line 29 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ7XCm8E4vfkyfJjbQ:-MyN9Eo99qIicGXAHh-V:bxur9jg) ([raw file](https://github.com/harness/harness-core/blob/fae8a7cff296dbb4d546e28725ec585061c24c46/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/RepoProviderHelperTest.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we add it here rn itself, these are basic cases and we don't know if these would work or get tested.
</blockquote></details>

Removed the function


<!-- Sent from Reviewable.io -->

2022-03-17 17:19 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 19 file(s) to review. 3 change requests. 21. unresolved discussions. 0 of 1 approvals obtained. 

___
*[970-api-services-beans/src/main/java/io/harness/gitsync/common/dtos/RepoProviders.java, line 35 at r4](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ6zIh532OGlYBl3Vs:-MyNt4QLEAye25tgKVbk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fae8a7cff296dbb4d546e28725ec585061c24c46/970-api-services-beans/src/main/java/io/harness/gitsync/common/dtos/RepoProviders.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we have a repoProviderHelper for such actions right? RepoProviderDTO shouldn't have this method.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-22 02:35 UTC, ankit-harness reviewed
> Reviewed 1 of 13 files at r4, 1 of 18 files at r8, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-22 02:43 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 72 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUXVZ7creEX6fcA_i:-MyjUXVZ7creEX6fcA_j:b355tjw) ([raw file](https://github.com/harness/harness-core/blob/94c5e937740c0b35f96609af151d8c9d7b41cb0e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L72)):*
> ```Java
>                 projectIdentifier, organizationIdentifier, accountIdentifier, gitSyncConfigIdentifierList,
>                 entityTypeList, searchTerm, size);
>     populateFilePathUrlInFilesGroupedByRepo(gitSyncRepoFilesDTOList);
> ```

Can we avoid separate populateMethods. We should initialise  filePathUrl at the time of instantiation of GitSyncEntityDTO
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 240 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUyLD-1QTIKAvyQ3P:-MyjUyLD-1QTIKAvyQ3Q:b-ioi20e) ([raw file](https://github.com/harness/harness-core/blob/94c5e937740c0b35f96609af151d8c9d7b41cb0e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L240)):*
> ```Java
>         .entityReference(entity.getEntityReference())
>         .lastCommitId(entity.getLastCommitId())
>         .entityUrl(filePathUrl)
> ```

Let's not a separate setter method for entityUrl. entityUrl can always be initialised automatically when GitSyncEntityDTO object is created


<!-- Sent from Reviewable.io -->

2022-03-23 07:39 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 19. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 72 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUXVZ7creEX6fcA_i:-Myph0bL9lJMRjyu0kgu:b1luxcf) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L72)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we avoid separate populateMethods. We should initialise  filePathUrl at the time of instantiation of GitSyncEntityDTO
</blockquote></details>

In the previous line, we are getting the list from the DB 

    List<GitSyncRepoFilesDTO> gitSyncRepoFilesDTOList =
        gitFileLocationRepository
            .getByProjectIdAndOrganizationIdAndAccountIdAndGitSyncConfigIdentifierListAndEntityTypeList(
                projectIdentifier, organizationIdentifier, accountIdentifier, gitSyncConfigIdentifierList,
                entityTypeList, searchTerm, size);


Ideally, we should have a mapper which converts the entity model to DTO. But since in this case, we are directly populating the DTO we had to use the populate Method.



_Code quote:_
```Java
populateFilePathUrlInFilesGroupedByRepo(gitSyncRepoFilesDTOList);
```
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 240 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUyLD-1QTIKAvyQ3P:-Mypht8J4i91wfPX2Ocp:b969n66) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L240)):*
> GitSyncEntityDTO
We don't have a setter method for entityUrl


<!-- Sent from Reviewable.io -->

2022-03-23 09:55 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 72 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUXVZ7creEX6fcA_i:-MyqBfwSAr85H4XAC3-j:bpqwg6t) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L72)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

In the previous line, we are getting the list from the DB 

    List<GitSyncRepoFilesDTO> gitSyncRepoFilesDTOList =
        gitFileLocationRepository
            .getByProjectIdAndOrganizationIdAndAccountIdAndGitSyncConfigIdentifierListAndEntityTypeList(
                projectIdentifier, organizationIdentifier, accountIdentifier, gitSyncConfigIdentifierList,
                entityTypeList, searchTerm, size);


Ideally, we should have a mapper which converts the entity model to DTO. But since in this case, we are directly populating the DTO we had to use the populate Method.
</blockquote></details>

filePathUrl can be a derived field inside GitSyncEntityDTO
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 240 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUyLD-1QTIKAvyQ3P:-MyqBPhn5NnUE4OkKo-a:bnw27jm) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L240)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

> GitSyncEntityDTO
We don't have a setter method for entityUrl
</blockquote></details>

.entityUrl(filePathUrl) is a setter method on the URL



_Code quote:_
```Java
.entityUrl(filePathUrl)
```


<!-- Sent from Reviewable.io -->

2022-03-23 11:17 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 50 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyqUoZRBFd3Wt1dUPZZ:-MyqUoZRBFd3Wt1dUPZ_:bi5tnqg) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L50)):*
> ```Java
>       return RepoProviders.BITBUCKET;
>     }
>     return RepoProviders.GITHUB;
> ```

Need to check


<!-- Sent from Reviewable.io -->

2022-03-23 11:19 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 49 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9SFq4iP84LuCtDLs:-MyqVA-gEfXAkWYVg2o_:b1kfgts) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L49)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

There cannot be a any correct one for github as for github we support the github enterprise also.

For bitbucket we support only cloud, hence only we are able to do this migration. 

The bitbucket cloud always contains the name bitbucket.org. So the entities which has bitbucket belongs to the bitbucket cloud and the rest belongs to github
</blockquote></details>

As confirmed, no record in prod with type provider github with "bitbucket" in repo url. So we should be good.



_Code quote:_
```Java
bitbucket.
```


<!-- Sent from Reviewable.io -->

2022-03-23 13:08 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 18. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 72 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUXVZ7creEX6fcA_i:-Myqsyh097uj7hYZNPVK:b-gvs7a5) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L72)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

filePathUrl can be a derived field inside GitSyncEntityDTO
</blockquote></details>

Incorporated the suggestion we discussed
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 240 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyjUyLD-1QTIKAvyQ3P:-Myqt0SqAAm79AOgBaDo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L240)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

.entityUrl(filePathUrl) is a setter method on the URL
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-23 16:53 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-9zm--5y2UdPeYMh:-MyrgdGjAKLpKVwQp_lz:b-qac6zg) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

i mean can you tell number of records being updated in different env here
</blockquote></details>

Yes we are loggin the number of records updated


<!-- Sent from Reviewable.io -->

2022-03-23 20:20 UTC, abhinav-harness commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-9zm--5y2UdPeYMh:-MysQzSn9Zv5zHNyTdqM:b-ibexau) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Yes we are loggin the number of records updated
</blockquote></details>

I meant, can you tell count of records in PROD and QA where query will be executed, wanted to check load on mongo.


<!-- Sent from Reviewable.io -->

2022-03-24 05:55 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-9zm--5y2UdPeYMh:-MyuRqfa20syJyqzjeUl:bkdc6re) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

I meant, can you tell count of records in PROD and QA where query will be executed, wanted to check load on mongo.
</blockquote></details>

qa:
  gitFileLocation -- 58396
  gitSyncError - -27045


prod2:
   gitFileLocation -- 5497
   gitSyncError -- 2253

prod1:
   gitFileLocation -- 1356
   gitSyncError -- 209   


<!-- Sent from Reviewable.io -->

2022-03-24 05:55 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 25 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 49 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyJ9SFq4iP84LuCtDLs:-MyuU_bK0xVMBfWVmr5t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

As confirmed, no record in prod with type provider github with "bitbucket" in repo url. So we should be good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-24 07:00 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 50 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyqUoZRBFd3Wt1dUPZZ:-MyuiO3wByXD9PyZzjM_:b-6x5xh1) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L50)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Need to check
</blockquote></details>

Can we create a separate ticket to track that this code is removed in the consequent release as soon as it goes into production.

Also, I see its usage in one of the methods:
  "public String getEntityUrl() {"
but this method isn't used anywhere. So, please remove this method.


<!-- Sent from Reviewable.io -->

2022-03-24 07:01 UTC, mohitg0795 requested changes
> Reviewed 1 of 4 files at r2, 1 of 15 files at r3, 1 of 13 files at r4, 2 of 12 files at r5, 2 of 7 files at r7, 16 of 18 files at r8, 1 of 2 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 23 file(s) to review. 3 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-24 07:09 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 23 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java, line 50 at r11](https://reviewable.io/reviews/harness/harness-core/31372#-MyqUoZRBFd3Wt1dUPZZ:-MyukMFb9se-lGWX9zbz:b-67bm6z) ([raw file](https://github.com/harness/harness-core/blob/4976144af48a78471a9a11f28c2d08a6e7092c12/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/RepoProviderHelper.java#L50)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we create a separate ticket to track that this code is removed in the consequent release as soon as it goes into production.

Also, I see its usage in one of the methods:
  "public String getEntityUrl() {"
but this method isn't used anywhere. So, please remove this method.

</blockquote></details>

Created this ticket https://harness.atlassian.net/browse/PL-24039

This method is only used in getEntityUrl. This is a fallback method which will only be called if the migration fails.


<!-- Sent from Reviewable.io -->

2022-03-24 07:17 UTC, abhinav-harness commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31372#-MyC-9zm--5y2UdPeYMh:-MyumDsYEz_mRLZDZyBs:bd2jgcd) ([raw file](https://github.com/harness/harness-core/blob/1969bd9deb08b659d33eb7ea32421884adf8ab99/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/UpdateTheRepoProvidersInGitEntities.java#L52)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

qa:
  gitFileLocation -- 58396
  gitSyncError - -27045


prod2:
   gitFileLocation -- 5497
   gitSyncError -- 2253

prod1:
   gitFileLocation -- 1356
   gitSyncError -- 209   


</blockquote></details>

It might kill us on QA since cursor will have to update a lot of records but fine for prod hence approving.


<!-- Sent from Reviewable.io -->

2022-03-24 07:17 UTC, abhinav-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372#-:-MyumPTu1t7bFzgxpLey:bnfp4nl)* status: 23 file(s) to review. 2 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-24 08:01 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 23 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 106 at r14](https://reviewable.io/reviews/harness/harness-core/31372#-MyuwBlk2qQ135r22JjZ:-MyuwBlk2qQ135r22Jj_:b3fx9ci) ([raw file](https://github.com/harness/harness-core/blob/2e405484cc6609720f31f98ec69c9171de8f964b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L106)):*
> ```Java
>                 projectIdentifier, organizationIdentifier, accountIdentifier, gitSyncConfigIdentifier, branch,
>                 entityTypeList, searchTerm, size);
>     addTheFilePathUrl(gitSyncEntityList);
> ```

Why this is still required? We don't even need filePathUrl field in GitSyncEntityDTO. Just getter should be fine



_Code quote:_
```Java
gitSyncEntityDTO.setEntityUrl(filePathUrl);
```


<!-- Sent from Reviewable.io -->

2022-03-24 08:38 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: 23 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java, line 106 at r14](https://reviewable.io/reviews/harness/harness-core/31372#-MyuwBlk2qQ135r22JjZ:-Myv3qxh5XbNhJAQqDso:brlf3dc) ([raw file](https://github.com/harness/harness-core/blob/2e405484cc6609720f31f98ec69c9171de8f964b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitEntityServiceImpl.java#L106)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this is still required? We don't even need filePathUrl field in GitSyncEntityDTO. Just getter should be fine
</blockquote></details>

Removed it


<!-- Sent from Reviewable.io -->

2022-03-24 10:11 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 15 files at r3, 2 of 12 files at r5, 2 of 7 files at r7, 13 of 18 files at r8, 1 of 1 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372#-:-MyvPEX28-R5MhGF-5-t:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-24 10:29 UTC, bhavya181 approved these changes
> Reviewed 1 of 4 files at r2, 1 of 15 files at r3, 1 of 13 files at r4, 2 of 12 files at r5, 2 of 7 files at r7, 16 of 18 files at r8, 1 of 1 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31372)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-24 10:29 UTC, merged