Create/api
harness/harness-core pull request #31438
Opened 2022-03-14 14:56 UTC by prashantsharma04

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-16 08:49 UTC, naidu-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/beans/EnvironmentGroupConfig.java
> +  Map<String, String> tags;
why cant we use <NGTag>

2022-03-16 08:54 UTC, namanvermah commented on 125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java
> +    } catch (DuplicateKeyException ex) {
No need to catch duplicate key here if service layer is catching this

2022-03-16 09:07 UTC, archit-harness requested changes
> Reviewed 12 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/beans/EnvironmentGroupConfig.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/31438#-My7vWMmFNQdeJKB1dlS-r1-38:-MyGyQjV39Xzr3bG4sjf:b-qkepw9) ([raw file](https://github.com/harness/harness-core/blob/00ef70405915595828f8781303ce2a76d4217469/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/beans/EnvironmentGroupConfig.java#L38)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

why cant we use `NGTag`
</blockquote></details>

List<NGTag> tags should use this
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/31438#-MyGyUtN8k-MSqBIpWbm:-MyGyUtN8k-MSqBIpWbn:bfezdms) ([raw file](https://github.com/harness/harness-core/blob/00ef70405915595828f8781303ce2a76d4217469/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java#L57)):*
> ```Java
>       throw new InvalidRequestException(
>           String.format("Error occurred while saving environment group %s", e.getMessage()));
>     }
> ```

write todo, and create ticket for enforcement if its valid for this



_Code quote:_
```Java
    try {
      return environmentRepository.create(entity);
    } catch (DuplicateKeyException ex) {
      throw new DuplicateFieldException(
          format("Identifier %s already exists in organization id %s and project id %s", entity.getIdentifier(),
              entity.getProjectIdentifier(), entity.getOrgIdentifier()),
          USER_SRE, ex);
    } catch (Exception e) {
      throw new InvalidRequestException(
          String.format("Error occurred while saving environment group %s", e.getMessage()));
    }
```
___
*[125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java, line 58 at r1](https://reviewable.io/reviews/harness/harness-core/31438#-MyGyoAdCGoWgupoIloK:-MyGyoAdCGoWgupoIloL:b1wc8q4) ([raw file](https://github.com/harness/harness-core/blob/00ef70405915595828f8781303ce2a76d4217469/125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java#L58)):*
> ```Java
>     EnvironmentGroupEntity savedEntity;
>     Supplier<OutboxEvent> functor = ()
>         -> outboxService.save(EnvironmentGroupCreateEvent.builder()
> ```

should log audits only if if git sync is disabled or if git sync is enabled (only for default branch)



_Code quote:_
```Java
outboxService.save
```


<!-- Sent from Reviewable.io -->

2022-03-16 09:11 UTC, prashantsharma04 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/beans/EnvironmentGroupConfig.java
> +  Map<String, String> tags;
In Entity, we have defined them as NGTag. This is the config file which will read from yaml. While converting to config to entities we are making it as NGTag.  (EnvironmentGroupMapper::toEnvironmentEntity)

I have handled the same way we are handling for environments

2022-03-16 10:04 UTC, prashantsharma04 commented
trigger messagecheck

2022-03-16 12:24 UTC, prashantsharma04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 17 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/beans/EnvironmentGroupConfig.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/31438#-My7vWMmFNQdeJKB1dlS-r1-38:-MyHfj6DDAfZ18AkhgNE:bim2das) ([raw file](https://github.com/harness/harness-core/blob/00ef70405915595828f8781303ce2a76d4217469/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/beans/EnvironmentGroupConfig.java#L38)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

In Entity, we have defined them as NGTag. This is the config file which will read from yaml. While converting
 config to entities we are making it as NGTag.  (EnvironmentGroupMapper::toEnvironmentEntity)

I have handled the same way we are handling for environments
</blockquote></details>

@archit-harness As discussed - we do have list of NGTag in EnvGroupEntity
___
*[125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java, line 58 at r1](https://reviewable.io/reviews/harness/harness-core/31438#-MyGyoAdCGoWgupoIloK:-MyHfts2Ec4_BdqpO8R-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/00ef70405915595828f8781303ce2a76d4217469/125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java#L58)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should log audits only if if git sync is disabled or if git sync is enabled (only for default branch)
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/31438#-My7vWMmFNQdeJKB1dlk-r1-67:-MyHfuc536MjBTnsDqHZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/00ef70405915595828f8781303ce2a76d4217469/125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java#L67)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

No need to catch duplicate key here if service layer is catching this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-16 12:27 UTC, naidu-harness approved these changes
> Reviewed 13 of 16 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-17 05:05 UTC, archit-harness requested changes
> Reviewed 2 of 16 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/config.yml, line 241 at r3](https://reviewable.io/reviews/harness/harness-core/31438#-MyLFp0_Bq7je_C9Z9oY:-MyLFp0_Bq7je_C9Z9oZ:b4wldth) ([raw file](https://github.com/harness/harness-core/blob/8964311f616ac219f62b3fc2b7f87a9b3054c4e8/120-ng-manager/config.yml#L241)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: true
> ```

revert this



_Code quote:_
```YAML
true
```


<!-- Sent from Reviewable.io -->

2022-03-17 05:25 UTC, prashantsharma04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/config.yml, line 241 at r3](https://reviewable.io/reviews/harness/harness-core/31438#-MyLFp0_Bq7je_C9Z9oY:-MyLKZ5iA6NeEnGiVCEL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8964311f616ac219f62b3fc2b7f87a9b3054c4e8/120-ng-manager/config.yml#L241)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

revert this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-17 05:36 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-17 05:56 UTC, sahilhindwani-harness approved these changes
> Reviewed 13 of 16 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 1 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-17 06:03 UTC, puthrayaharness approved these changes
> Reviewed 13 of 16 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438)* status: 1 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-21 04:58 UTC, namanvermah approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 16 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31438#-:-Myept4I7xQJw1BkDwlP:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-21 04:59 UTC, merged