[CDS-32522]: Fix for Failure strategy for a WF in progress considers …
harness/harness-core pull request #31467
Opened 2022-03-15 10:28 UTC by utkarshchoubey-harness

[CDS-32522]: Failure strategy for a WF in progress considers the info from the updated WF YAML instead of honouring the definition provided at the start of the WF execution

Fix is Made behind the Feature Flag - FAILURE_STRATEGY_CONSIDER_ORIGINAL_STATE_VERSION

Fix Done:-
* We are getting the original State Version from Context ( It contains state Machine, from where we can get the Origin version) 
* Incase the origin Version was NULL we are failing back to the default behaviour of using the latest Origin Version ( it is rare case as context should have the state machine and the origin version)

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-15 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31467) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31467) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31467) it.</sub>

2022-03-29 05:58 UTC, poojaSinghal requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31467)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java, line 155 at r2](https://reviewable.io/reviews/harness/harness-core/31467#-MzJFIMZ8i70p6GewGIj:-MzJFIMZ8i70p6GewGIk:bd4zuvz) ([raw file](https://github.com/harness/harness-core/blob/694e0ed4b4fd61683c899783e4d7591a2c8707dd/400-rest/src/main/java/software/wings/beans/CanaryWorkflowExecutionAdvisor.java#L155)):*
> ```Java
>         Integer originalStateVersion = context.getStateMachine().getOriginVersion();
>         if (originalStateVersion == null) {
>           workflow = workflowService.readWorkflow(workflowExecution.getAppId(), workflowExecution.getWorkflowId());
> ```

We dont want to read the workflow from DB here. It should be available in stateMAchine. can you discuss with @inderschera  once? 


<!-- Sent from Reviewable.io -->

2022-03-31 09:36 UTC, inderschera approved these changes
> Reviewed 1 of 5 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31467)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-01 05:16 UTC, poojaSinghal approved these changes
> Reviewed 1 of 5 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31467)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-01 05:19 UTC, merged