feat: [PIE-3124]: Store final graph with skipped vertices in cache
harness/harness-core pull request #31610
Opened 2022-03-21 13:10 UTC by sahilhindwani-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-22 08:57 UTC, hextechpal approved these changes
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31610)* status: 16 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-22 09:06 UTC, archit-harness requested changes
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31610)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 272 at r1](https://reviewable.io/reviews/harness/harness-core/31610#-Myks2OD6QmDCeK9c0kw:-Myks2OD6QmDCeK9c0kx:b-8ds92) ([raw file](https://github.com/harness/harness-core/blob/0d3eb4b28edd522fc98b2313f0426959e6a48655/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L272)):*
> ```Java
> 
>   private OrchestrationGraphDTO generatePartialGraph(String startId, OrchestrationGraph orchestrationGraph) {
>     OrchestrationGraph orchestrationGraph1 =
> ```

can we name this better



_Code quote:_
```Java
orchestrationGraph1
```
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 283 at r1](https://reviewable.io/reviews/harness/harness-core/31610#-Myks52NC_z7NsTEPSFX:-Myks52NC_z7NsTEPSFY:b8bkw4y) ([raw file](https://github.com/harness/harness-core/blob/0d3eb4b28edd522fc98b2313f0426959e6a48655/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L283)):*
> ```Java
>             .build();
> 
>     vertexSkipperService.removeSkippedVertices(orchestrationGraph);
> ```

new graph created above should be here



_Code quote:_
```Java
orchestrationGraph
```


<!-- Sent from Reviewable.io -->

2022-04-06 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31610) it.</sub>

2022-04-06 10:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31610) it.</sub>

2022-05-05 05:46 UTC, closed without merging