[fix]: [CI-3474]: fixed some connector apis
harness/harness-core pull request #31668
Opened 2022-03-22 13:14 UTC by devkimittal

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/31668)

2022-03-22 16:58 UTC, devkimittal commented
trigger authorcheck

2022-03-23 05:06 UTC, devkimittal commented
trigger ti1

2022-03-23 05:09 UTC, devkimittal commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
> -    validateNameIsUnique(connectorInfo, accountIdentifier, existingConnector.getIdentifier());
This is inconsistent with other entities i.e. identifier should be unique in a scope but name can be same.

2022-03-23 05:09 UTC, devkimittal commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java
> -    validateThatAConnectorWithThisNameDoesNotExists(connectorRequestDTO.getConnectorInfo(), accountIdentifier);
This is inconsistent with other entities i.e. identifier should be unique in a scope but name can be same.

2022-03-23 05:10 UTC, devkimittal commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/github/GithubUsernameTokenDTO.java
> +@OneOfField(fields = {"username", "usernameRef"})
Exactly one of the fields should be present

2022-03-23 05:10 UTC, devkimittal commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/gitlab/GitlabUsernameTokenDTO.java
> +@OneOfField(fields = {"username", "usernameRef"})
Exactly one of the fields should be present

2022-03-23 06:51 UTC, devkimittal commented
trigger ti1

2022-03-23 06:56 UTC, abhinav-harness requested changes
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31668)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 293 at r1](https://reviewable.io/reviews/harness/harness-core/31668#-MypYmZIAxoSJZ8hKXMv:-MypYmZJ8W2_AEYOpRWi:bt4cfu1) ([raw file](https://github.com/harness/harness-core/blob/e906abf04b25a69ad5aac42f6719cfab5caa991e/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L293)):*
> ```Java
>         accountIdentifier, connectorInfo.getOrgIdentifier(), connectorInfo.getProjectIdentifier(),
>         connectorInfo.getIdentifier());
>     validateNameIsUnique(connectorInfo, accountIdentifier, existingConnector.getIdentifier());
> ```

@deepakpatankar i remember this being  a req earlier


<!-- Sent from Reviewable.io -->

2022-03-23 07:31 UTC, aman-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31668#-:-Mypg1IE5AQvn9cmXIvc:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-23 08:11 UTC, devkimittal commented
trigger messagecheck

2022-03-23 08:15 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31668)* status: 1 change requests. 1. unresolved discussions. 

___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 293 at r1](https://reviewable.io/reviews/harness/harness-core/31668#-MypYmZIAxoSJZ8hKXMv:-Myppqfx0-qPGR6jD8Mm:bxsn1zm) ([raw file](https://github.com/harness/harness-core/blob/e906abf04b25a69ad5aac42f6719cfab5caa991e/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L293)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

@deepakpatankar i remember this being  a req earlier
</blockquote></details>

Yes this is a requirement


<!-- Sent from Reviewable.io -->

2022-03-23 08:41 UTC, devkimittal commented
___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 293 at r1](https://reviewable.io/reviews/harness/harness-core/31668#-MypYmZIAxoSJZ8hKXMv:-Mypvr982L3R7vAzNeFk:b-obcr6q) ([raw file](https://github.com/harness/harness-core/blob/e906abf04b25a69ad5aac42f6719cfab5caa991e/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L293)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Yes this is a requirement
</blockquote></details>

@deepakpatankar Can you please convey the same to this ticket here? https://harness.atlassian.net/browse/CI-3474
Vikas Naiyar had pointed this out.


<!-- Sent from Reviewable.io -->

2022-03-23 12:16 UTC, devkimittal commented
@DeepakPatankar @abhinav-harness,  @vikas-harness has confirmed that names can be same in connectors.

2022-03-23 16:40 UTC, aman-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31668#-:-MyrdbwV9TkkJgulhVAu:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-23 17:41 UTC, DeepakPatankar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31668#-:-MyrrYay7iTtaFBPkEpC:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-24 03:53 UTC, devkimittal reviewed
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31668)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-24 06:20 UTC, abhinav-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31668#-:-Myu_LQi4fka-iVjfrzu:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-24 06:20 UTC, merged