feat: [CDS-35216]: Add support for custom artifact with fixed value
harness/harness-core pull request #31673
Opened 2022-03-22 16:24 UTC by abosii-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/31673)

2022-03-25 06:33 UTC, shubham-in10se approved these changes

2022-03-25 06:33 UTC, shubham-in10se commented on 127-cd-nextgen-beans/src/main/java/io/harness/cdng/artifact/outcome/CustomArtifactOutcome.java
> +@OwnedBy(CDC)
shouldn't this be CDP

2022-03-25 06:33 UTC, shubham-in10se commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/CustomArtifactConfig.java
> +@OwnedBy(CDC)
CDP. ..?

2022-03-30 06:34 UTC, abosii-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31673)* status: 23 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/CustomArtifactConfig.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/31673#-MymS_MfXMVUOPlk_vTl-r1-35:-MzOWxEO8h9N09CyBjB1:b-9fud8d) ([raw file](https://github.com/harness/harness-core/blob/27d5acff68b864c42749ac9ec5d86bbb3b985ae0/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/bean/yaml/CustomArtifactConfig.java#L35)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

CDP. ..?
</blockquote></details>

All artifacts are owned by CDC
___
*[127-cd-nextgen-beans/src/main/java/io/harness/cdng/artifact/outcome/CustomArtifactOutcome.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/31673#-MymS_MfXMVUOPlk_vTp-r1-28:-MzOX02lE1DAgv2L5qtL:b-9fud8d) ([raw file](https://github.com/harness/harness-core/blob/27d5acff68b864c42749ac9ec5d86bbb3b985ae0/127-cd-nextgen-beans/src/main/java/io/harness/cdng/artifact/outcome/CustomArtifactOutcome.java#L28)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

shouldn't this be CDP
</blockquote></details>

All artifacts are owned by CDC


<!-- Sent from Reviewable.io -->

2022-04-06 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31673) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31673) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31673) it.</sub>

2022-04-07 09:57 UTC, puthrayaharness requested changes

2022-04-07 10:51 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/PrimaryArtifactPlanCreator.java
> +    if (ArtifactSourceType.CUSTOM_ARTIFACT == artifactStepParameters.getType()) {
Done

2022-04-07 11:51 UTC, puthrayaharness approved these changes
> Reviewed 14 of 23 files at r1, 1 of 7 files at r2, 3 of 7 files at r3, 2 of 4 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31673)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:54 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 14 of 23 files at r1, 1 of 7 files at r2, 3 of 7 files at r3, 2 of 4 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31673#-:-N-2rxAGADQVImaKu2vl:bnfp4nl)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-07 12:12 UTC, hextechpal approved these changes
> Reviewed 14 of 23 files at r1, 1 of 7 files at r2, 3 of 7 files at r3, 2 of 4 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31673)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-07 12:14 UTC, merged