feat: [DEL-3365]: Memoryff
harness/harness-core pull request #31680
Opened 2022-03-22 21:23 UTC by Xin-Harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-23 16:43 UTC, arpit3107 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31680)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1844 at r1](https://reviewable.io/reviews/harness/harness-core/31680#-MyrczHdAnTz6dkQB-_V:-MyrczHdAnTz6dkQB-_W:blnutcj) ([raw file](https://github.com/harness/harness-core/blob/b4c2f59682ec87ba4b1679c72e08dfb5122554d0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1844)):*
> ```Java
>             .ciEnabled(false)
>             .delegateCpu(1)
>             .delegateRam(delegateRam)
> ```

earlier the delegateRam was 4 but now you without FF, ram will be 8
___
*[400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh, line 318 at r1](https://reviewable.io/reviews/harness/harness-core/31680#-Myre4PBECTInxiPPjjf:-Myre4PBECTInxiPPjjg:bbdl0o4) ([raw file](https://github.com/harness/harness-core/blob/b4c2f59682ec87ba4b1679c72e08dfb5122554d0/400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh#L318)):*
> ```Shell
> if [[ $DEPLOY_MODE == "KUBERNETES" ]]; then
>   echo "Starting delegate - version $2 with java $JRE_BINARY"
>   $JRE_BINARY $JAVA_OPTS $INSTRUMENTATION $PROXY_SYS_PROPS $OVERRIDE_TMP_PROPS -Ddelegatesourcedir="$DIR" -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:mygclogfilename.gc -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -Dfile.encoding=UTF-8 -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -DLANG=en_US.UTF-8 -Xbootclasspath/p:alpn-boot-8.1.13.v20181017.jar -jar $2/delegate.jar config-delegate.yml watched $1
> ```

why this?



_Code quote:_
```Shell
-Xmx1536m
```


<!-- Sent from Reviewable.io -->

2022-03-23 18:18 UTC, raghuAtWings commented
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1844 at r1](https://reviewable.io/reviews/harness/harness-core/31680#-MyrczHdAnTz6dkQB-_V:-Mys-3UT5l9aYxVlzxPh:bp8ct0u) ([raw file](https://github.com/harness/harness-core/blob/b4c2f59682ec87ba4b1679c72e08dfb5122554d0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1844)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

earlier the delegateRam was 4 but now you without FF, ram will be 8
</blockquote></details>

thats correct, find for what kind of delegate we had ram to be 4


<!-- Sent from Reviewable.io -->

2022-03-23 18:19 UTC, raghuAtWings commented
___
*[400-rest/src/test/resources/expectedDelegateOpenJdk.sh, line 337 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-CT7DLXXYIsXI5tl:-Mys-CT83_rQGhzIv_L-:b33dksb) ([raw file](https://github.com/harness/harness-core/blob/c7012205b9c086c5952d1649f8c3bda0f9ec0833/400-rest/src/test/resources/expectedDelegateOpenJdk.sh#L337)):*
> ```Shell
> else
>   echo "Starting delegate - version $REMOTE_DELEGATE_VERSION with java $JRE_BINARY"
>   $JRE_BINARY $JAVA_OPTS $INSTRUMENTATION $PROXY_SYS_PROPS $OVERRIDE_TMP_PROPS -DACCOUNT_ID="ACCOUNT_ID" -DMANAGER_HOST_AND_PORT="https://localhost:9090" -Ddelegatesourcedir="$DIR" -Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:mygclogfilename.gc -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -Dfile.encoding=UTF-8 -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -DLANG=en_US.UTF-8 -Xbootclasspath/p:alpn-boot-8.1.13.v20181017.jar -jar delegate.jar config-delegate.yml watched $1
> ```

this should not change since by default the ff is off


<!-- Sent from Reviewable.io -->

2022-03-23 18:19 UTC, raghuAtWings commented
___
*[400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh, line 318 at r1](https://reviewable.io/reviews/harness/harness-core/31680#-Myre4PBECTInxiPPjjf:-Mys-HgFAFhtcDnuAPc3:b-2ipum1) ([raw file](https://github.com/harness/harness-core/blob/b4c2f59682ec87ba4b1679c72e08dfb5122554d0/400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh#L318)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

why this?
</blockquote></details>

same here, this should not change since by default the ff is off


<!-- Sent from Reviewable.io -->

2022-03-23 18:22 UTC, raghuAtWings commented
___
*[on-prem/kubernetes_installer/delegate.yaml, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-sKUDg5yDv2Ffuql:-Mys-sKUDg5yDv2Ffuqm:b-qdxjeg) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/on-prem/kubernetes_installer/delegate.yaml#L61)):*
> ```YAML
>             limits:
>               cpu: "1"
>               memory: "4Gi"
> ```

this should be also based on FF


<!-- Sent from Reviewable.io -->

2022-03-23 18:22 UTC, raghuAtWings requested changes
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31680)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[dockerization/delegate/immutable-scripts/start.sh, line 54 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-YKv-hsodTTcpm5D:-Mys-YKv-hsodTTcpm5E:bcpdo7z) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/dockerization/delegate/immutable-scripts/start.sh#L54)):*
> ```Shell
> 
> # 3. Start the delegate
> exec java $JAVA_OPTS $PROXY_SYS_PROPS -Xbootclasspath/p:alpn-boot-8.1.13.v20181017.jar -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:mygclogfilename.gc -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -Dfile.encoding=UTF-8 -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -DLANG=en_US.UTF-8 -jar delegate.jar server config.yml
> ```

why this change?

immutab


<!-- Sent from Reviewable.io -->

2022-03-23 18:59 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31680)* status: 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/test/resources/expectedDelegateOpenJdk.sh, line 337 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-CT7DLXXYIsXI5tl:-Mys5cYe9cg7AOV8kgXH:b-ps6s4p) ([raw file](https://github.com/harness/harness-core/blob/c7012205b9c086c5952d1649f8c3bda0f9ec0833/400-rest/src/test/resources/expectedDelegateOpenJdk.sh#L337)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should not change since by default the ff is off
</blockquote></details>

We discussed this yesterday. Eventually the memory size will drop to 1536 so the expected size should be changed. I made the change to the test case to enable the feature flag so that the test case would pass.
___
*[dockerization/delegate/immutable-scripts/start.sh, line 54 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-YKv-hsodTTcpm5D:-Mys6JB2BjzLXnM-C4nW:bo5bzah) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/dockerization/delegate/immutable-scripts/start.sh#L54)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why this change?

immutab
</blockquote></details>

Since the immutable delegate is designed to have smaller xmx so I changed.


<!-- Sent from Reviewable.io -->

2022-03-23 19:55 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31680)* status: 8 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1844 at r1](https://reviewable.io/reviews/harness/harness-core/31680#-MyrczHdAnTz6dkQB-_V:-MysKk252MHKXJY28e_X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b4c2f59682ec87ba4b1679c72e08dfb5122554d0/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1844)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

thats correct, find for what kind of delegate we had ram to be 4
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1767 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-MyrzoHh91JQ5n-hPZhs:-MysKeSG-zRybAFccwNs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1767)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

write this statement like below for readability

int delegateRam = featureFlagService.isEnabled(REDUCE_DELEGATE_MEMORY_SIZE, accountId) ? 4:8;
</blockquote></details>

Done.
___
*[400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh, line 318 at r1](https://reviewable.io/reviews/harness/harness-core/31680#-Myre4PBECTInxiPPjjf:-MysLA543bAWRetrZd-X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b4c2f59682ec87ba4b1679c72e08dfb5122554d0/400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh#L318)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here, this should not change since by default the ff is off
</blockquote></details>

Done.
___
*[400-rest/src/test/resources/expectedHarnessDelegate.yaml, line 68 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-ORP2E3ire4Urwko:-MysLB0I9XTTijAb2iLF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/400-rest/src/test/resources/expectedHarnessDelegate.yaml#L68)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[400-rest/src/test/resources/expectedHarnessDelegateImmutable.yaml, line 68 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-Q-x7X5sG-flQy-H:-MysLBc4D1k5gRx7yr8i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/400-rest/src/test/resources/expectedHarnessDelegateImmutable.yaml#L68)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[400-rest/src/test/resources/expectedHarnessDelegateWithCiEnabled.yaml, line 70 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-Ryx5ab4jGjExcEH:-MysLCCdAK455v-L-shu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/400-rest/src/test/resources/expectedHarnessDelegateWithCiEnabled.yaml#L70)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[on-prem/kubernetes_installer/delegate.yaml, line 61 at r2](https://reviewable.io/reviews/harness/harness-core/31680#-Mys-sKUDg5yDv2Ffuql:-MysLCqm8KIecXOv95Bq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c3fac9d2e939e7f2b7822cbcb399134623833a4/on-prem/kubernetes_installer/delegate.yaml#L61)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should be also based on FF
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-24 15:59 UTC, Xin-Harness commented
* install pr without the change and install delegates build 3565

test shell script
￼
￼
￼
￼

* upgrade the pr with the change and verify nothing changes build 3566
￼
￼

￼
￼
* 
* enable the FF to be true
￼
* create a new build with the same PR and upgrade and verify that xmx changes build 3567
￼
￼

￼
￼

2022-03-24 16:03 UTC, Xin-Harness commented
Test:
* install pr without the change and install delegates build no.3565
test shell script
<img width="1528" alt="Install Delegate" src="https://user-images.githubusercontent.com/80720012/159958824-71f75048-9e97-4cc1-8d47-d9c758bee60d.png">
![image](https://user-images.githubusercontent.com/80720012/159958847-cba06a99-51be-451c-9202-9cccea54fd21.png)
kubernetes delegate
<img width="1328" alt="testk8s-kmpysm-0" src="https://user-images.githubusercontent.com/80720012/159958912-71fad1c7-1bb5-4406-bc42-6dc79ebc8d89.png">
<img width="656" alt="Running" src="https://user-images.githubusercontent.com/80720012/159958930-cad94a44-311a-470d-99f9-be033f74dd60.png">
* upgrade the pr with the change and verify nothing changes build no.3566
<img width="1453" alt="Pasted Graphic 16" src="https://user-images.githubusercontent.com/80720012/159958985-2771edf5-f237-44ee-99cd-b526fbe6bdd8.png">
<img width="950" alt="0 1509 pts0" src="https://user-images.githubusercontent.com/80720012/159959005-05dda262-ed98-492d-8ff1-0c689d6e136d.png">
<img width="1515" alt="Pasted Graphic 18" src="https://user-images.githubusercontent.com/80720012/159959023-458a0830-2192-4aeb-86e5-0aaed4efe1ff.png">
<img width="958" alt="501 51651" src="https://user-images.githubusercontent.com/80720012/159959040-be77f470-7cd7-4fe2-89f6-d99f1342c865.png">
* enable the FF to be true
* 
<img width="1089" alt="Pasted Graphic 19" src="https://user-images.githubusercontent.com/80720012/159959086-4f55f5e4-746a-4cd6-ba94-2cebbc349869.png">
* create a new build with the same PR and upgrade and verify that xmx changes build no.3567
<img width="1089" alt="Pasted Graphic 20" src="https://user-images.githubusercontent.com/80720012/159959156-529142ea-fea3-4c5b-94f6-cd4395d0138a.png">
<img width="949" alt="5674 84 1513" src="https://user-images.githubusercontent.com/80720012/159959175-dc0eb7a3-9b9c-4d99-a982-10b2a3a6c1f5.png">
<img width="1475" alt="Pasted Graphic 22" src="https://user-images.githubusercontent.com/80720012/159959206-97d2e07c-3b32-4f4d-946b-412266af7e77.png">
<img width="1909" alt="Pasted Graphic 23" src="https://user-images.githubusercontent.com/80720012/159959230-1ae35c07-0c59-4ace-b1e9-22507bfcaafe.png">
Test successful

2022-03-24 16:28 UTC, arpit3107 submitted a review, later dismissed
> Reviewed 6 of 14 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31680)* status: 1 change requests. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-24 18:51 UTC, raghuAtWings approved these changes
> Reviewed 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31680)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-24 21:07 UTC, raghuAtWings approved these changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31680)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-24 21:11 UTC, merged

2022-03-25 14:56 UTC, gaurav-jain1 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  REDUCE_DELEGATE_MEMORY_SIZE;
Consider renaming it to DELEGATE_MEMORY_SIZE_TO_1536M