[CDS-35459]: Hide get gcp clusters api in open api spec
harness/harness-core pull request #31696
Opened 2022-03-23 11:52 UTC by sainath-b

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-23 11:57 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31696)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-23 12:31 UTC, ashishsanodia-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31696#-:-MyqkZMX09v7B6C_PIqY:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-23 12:36 UTC, rijajoo requested changes

2022-03-23 12:36 UTC, rijajoo commented on 120-ng-manager/src/main/java/io/harness/ng/core/k8s/cluster/resources/gcp/GcpClusterResource.java
> -@Tag(name = "gcp clusters", description = "This contains APIs related to gcp clusters")
Instead of removing @Tag annotation at the class level, the recommendation is to add hidden = true in the @Operation annotation of the getClusterNames method if we want to hide it just from OpenAPI spec.

2022-03-24 09:33 UTC, sainath-b commented
trigger messagecheck

2022-03-24 09:46 UTC, rijajoo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31696#-:-MyvJUF12mbdlunBkLb9:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-03-24 09:50 UTC, merged