[techdebt]: [PIE-3224]: Expose expression resolve in EngineExpressionService with proper skipUnresolvedExpressionsCheck
harness/harness-core pull request #31715
Opened 2022-03-24 05:39 UTC by namanvermah

2022-03-29 06:43 UTC, archit-harness requested changes
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31715)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java, line 102 at r1](https://reviewable.io/reviews/harness/harness-core/31715#-MzJPQcX58orY1eAr9AW:-MzJPQcY5syWqgtY3Zd_:bk4dimw) ([raw file](https://github.com/harness/harness-core/blob/51fb7570ad0e4a733a13a32ff0dd2b07452f9e84/870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java#L102)):*
> ```Java
>     return transactionHelper.performTransaction(() -> {
>       List<String> timeoutInstanceIds = registerTimeouts(ambiance, planNode.getTimeoutObtainments());
>       resolveInputs(ambiance, planNode.getStepInputs(), planNode.isSkipUnresolvedExpressionsCheck());
> ```

should not delete these calls



_Code quote:_
```Java
planNode.isSkipUnresolvedExpressionsCheck()
```
___
*[870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java, line 162 at r1](https://reviewable.io/reviews/harness/harness-core/31715#-MzJPSuy6mk8x53Hy0hu:-MzJPSuy6mk8x53Hy0hv:bk4dimw) ([raw file](https://github.com/harness/harness-core/blob/51fb7570ad0e4a733a13a32ff0dd2b07452f9e84/870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java#L162)):*
> ```Java
>   }
> 
>   private void resolveInputs(Ambiance ambiance, OrchestrationMap stepInputs, boolean skipUnresolvedCheck) {
> ```

should not delete these calls



_Code quote:_
```Java
boolean skipUnresolvedCheck
```


<!-- Sent from Reviewable.io -->

2022-04-06 06:34 UTC, archit-harness approved these changes
> Reviewed 2 of 10 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31715)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java, line 102 at r1](https://reviewable.io/reviews/harness/harness-core/31715#-MzJPQcX58orY1eAr9AW:-MzxZdd24ilxYERmhRvp:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3af38c14d7145c01eec4e1ad199f474bd48583cb/870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java#L102)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should not delete these calls
</blockquote></details>

done
___
*[870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java, line 162 at r1](https://reviewable.io/reviews/harness/harness-core/31715#-MzJPSuy6mk8x53Hy0hu:-MzxZjXUA6RQLN9bQPMO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3af38c14d7145c01eec4e1ad199f474bd48583cb/870-orchestration/src/main/java/io/harness/engine/pms/start/NodeStartHelper.java#L162)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should not delete these calls
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-04-06 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31715) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31715) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31715) it.</sub>

2022-04-06 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31715) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31715) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31715) it.</sub>

2022-04-22 06:25 UTC, namanvermah commented
The bug that this is solving has been de-prioritised for now. Will reopen this PR when it is picked up again.

2022-04-22 06:25 UTC, closed without merging