feat: [PL-23111]: Hard delete connectors
harness/harness-core pull request #31736
Opened 2022-03-24 17:12 UTC by VikasMaddukuriHarness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-24 17:59 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 141 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Myx3mSq3jR6AEb3TY3v:-Myx3mSq3jR6AEb3TY3w:b-v5w11f) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L141)):*
> ```Java
> 
>   @Override
>   public void delete(Connector objectToRemove, ConnectorDTO connectorDTO, ChangeType changeType, Supplier functor) {
> ```

why is change type required here?
___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 147 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Myx3p3lANJa9yMHJIIt:-Myx3p3lANJa9yMHJIIu:b-v5w11f) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L147)):*
> ```Java
> 
>   @Override
>   public void delete(Connector objectToRemove, ChangeType changeType) {
> ```

why is change type required here?


<!-- Sent from Reviewable.io -->

2022-03-24 18:35 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 141 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Myx3mSq3jR6AEb3TY3v:-MyxCOP36stB2ErM6z1P:b71jf9c) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L141)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is change type required here?
</blockquote></details>

change type is coming out as NONE and DELETE. So for this reason i had to pass in change type as well
___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 142 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Myx7eO58bf8g1EOej6t:-MyxCW28-Wa8HAdckvc7:b-eyund5) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L142)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Does delete function takes care of deleting the entity from mongo ?
</blockquote></details>

yes it is deleting from mongo
___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 147 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Myx3p3lANJa9yMHJIIt:-MyxCa7a8XAdqyAhyvhq:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L147)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is change type required here?
</blockquote></details>

same here


<!-- Sent from Reviewable.io -->

2022-03-24 19:26 UTC, abhinav-harness commented on 900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/testing/NoOpGitAwarePersistenceImpl.java
> +
changetype can be ignored as it will always be delete

2022-03-25 08:37 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 141 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Myx3mSq3jR6AEb3TY3v:-Mz-BYCV51oClFW68VTx:b-i8c0ck) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L141)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

change type is coming out as NONE and DELETE. So for this reason i had to pass in change type as well
</blockquote></details>

This is for secret managers. The secret manager is a connector but it is not git synced. Hence for the secret manager, we want to do an operation of type NONE


<!-- Sent from Reviewable.io -->

2022-03-25 08:39 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 107 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mz-DIIw9xx9lU3h-Wdi:-Mz-DIIw9xx9lU3h-Wdj:bbxwkql) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L107)):*
> ```Java
>       B objectToRemove, String yaml, ChangeType changeType, Class<B> entityClass, Supplier functor) {
>     final GitSdkEntityHandlerInterface gitSdkEntityHandlerInterface =
>         gitPersistenceHelperServiceMap.get(entityClass.getCanonicalName());
> ```

what happens if this get returns null ? Lets say that the map doesn't contain this entity ?
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 141 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mz-DdES2YBwzK_K9Fl3:-Mz-DdES2YBwzK_K9Fl4:b-x1rcce) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L141)):*
> ```Java
>   }
> 
>   private <B extends GitSyncableEntity> void deleteWithGitSyncEnabled(
> ```

I see we have added new functions. And we haven't changed any existing function, right ?

 Just wanted to ensure that we don't have any regressions because of this change.


<!-- Sent from Reviewable.io -->

2022-03-25 08:43 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/testing/NoOpGitAwarePersistenceImpl.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mywu_nmOfh9-t64NA6y-r1-83:-Mz-EN_Z-5aGWxXCaC4N:bb283b1) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/testing/NoOpGitAwarePersistenceImpl.java#L83)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

changetype can be ignored as it will always be delete
</blockquote></details>

The changeType was introduced for the secret manager. For  secret manager, change type would be NONE.


<!-- Sent from Reviewable.io -->

2022-03-25 08:43 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 168 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mz-Ed0B6ytQr_xlESZN:-Mz-Ed0CAjcFIoZrYMIt:broz84c) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L168)):*
> ```Java
> 
>   @Override
>   public <B extends GitSyncableEntity, Y extends YamlDTO> void delete(
> ```

This functions looks good. Please add UTs


<!-- Sent from Reviewable.io -->

2022-04-06 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31736) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31736) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31736) it.</sub>

2022-04-06 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31736) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31736) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31736) it.</sub>

2022-04-06 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31736) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31736) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31736) it.</sub>

2022-04-06 12:34 UTC, VikasMaddukuriHarness commented
trigger messagecheck

2022-04-06 12:35 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java, line 141 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Myx3mSq3jR6AEb3TY3v:-MzyroyZ9UB7IYfxIktJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/440-connector-nextgen/src/main/java/io/harness/repositories/ConnectorCustomRepositoryImpl.java#L141)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

This is for secret managers. The secret manager is a connector but it is not git synced. Hence for the secret manager, we want to do an operation of type NONE
</blockquote></details>

Done.
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 107 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mz-DIIw9xx9lU3h-Wdi:-Mzyrr1H3swEqvvj2zHT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L107)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

what happens if this get returns null ? Lets say that the map doesn't contain this entity ?
</blockquote></details>

Done.
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 141 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mz-DdES2YBwzK_K9Fl3:-Mzyrs1S0E39fuZOa3hn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L141)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

I see we have added new functions. And we haven't changed any existing function, right ?

 Just wanted to ensure that we don't have any regressions because of this change.
</blockquote></details>

Done.
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 168 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mz-Ed0B6ytQr_xlESZN:-MzyrsO7EbnDAxE0PedF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L168)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

This functions looks good. Please add UTs
</blockquote></details>

Done.
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/testing/NoOpGitAwarePersistenceImpl.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/31736#-Mywu_nmOfh9-t64NA6y-r1-83:-Mzyrsvp63L_Oyv01PEA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b41735f587828641a711c3fe72c8e41801054ae/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/testing/NoOpGitAwarePersistenceImpl.java#L83)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The changeType was introduced for the secret manager. For  secret manager, change type would be NONE.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 06:06 UTC, DeepakPatankar reviewed
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 07:09 UTC, mohitg0795 commented
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 126 at r4](https://reviewable.io/reviews/harness/harness-core/31736#-N-1qpB5CyvhfLfnlxx1:-N-1qpB5CyvhfLfnlxx2:b8xgkct) ([raw file](https://github.com/harness/harness-core/blob/f0c9b8fdb86b178dd338313e2f72958bed9582c2/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L126)):*
> ```Java
>         mongoTemplate.remove(objectToRemove);
>       } else {
>         throw new InvalidRequestException("ChangeType is not supported for delete operation");
> ```

Can we add the argument change type also, which is invalid


<!-- Sent from Reviewable.io -->

2022-04-07 07:11 UTC, mohitg0795 commented
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 186 at r4](https://reviewable.io/reviews/harness/harness-core/31736#-N-1r8PO83bAmcupzR3e:-N-1r8PO83bAmcupzR3f:b-m1y0lo) ([raw file](https://github.com/harness/harness-core/blob/f0c9b8fdb86b178dd338313e2f72958bed9582c2/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L186)):*
> ```Java
>       mongoTemplate.remove(objectToRemove);
>     } else {
>       throw new InvalidRequestException("ChangeType is not supported for delete operation");
> ```

Add invalid change type to the error message as well.


<!-- Sent from Reviewable.io -->

2022-04-07 10:16 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 126 at r4](https://reviewable.io/reviews/harness/harness-core/31736#-N-1qpB5CyvhfLfnlxx1:-N-2WdFT3qM92KjGbkEy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f0c9b8fdb86b178dd338313e2f72958bed9582c2/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L126)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we add the argument change type also, which is invalid
</blockquote></details>

Done.
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java, line 186 at r4](https://reviewable.io/reviews/harness/harness-core/31736#-N-1r8PO83bAmcupzR3e:-N-2WduD-BhOCoWIO5fu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f0c9b8fdb86b178dd338313e2f72958bed9582c2/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceNewImpl.java#L186)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Add invalid change type to the error message as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 10:20 UTC, DeepakPatankar reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 6 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:09 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2, 5 of 6 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736#-:-N-2hech6GxPIG4DSsWt:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:18 UTC, DeepakPatankar approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:49 UTC, abhinav-harness approved these changes
> Reviewed 5 of 6 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31736)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-07 14:19 UTC, merged