feat: [PL-23163]: allow service tokens to also modify user details
harness/harness-core pull request #31761
Opened 2022-03-25 12:46 UTC by naman-goenka

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-29 21:54 UTC, gupta-utkarsh commented
trigger messagecheck

2022-04-06 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31761) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31761) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31761) it.</sub>

2022-04-06 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31761) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31761) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31761) it.</sub>

2022-04-07 05:35 UTC, karansiwach360 commented on 123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java
> +    if (SourcePrincipalContextBuilder.getSourcePrincipal().getType() == PrincipalType.USER) {
Let's do PrincipalType.USER.equals(SourcePrincipalContextBuilder.getSourcePrincipal().getType()) to prevent NPE

2022-04-07 05:42 UTC, karansiwach360 requested changes

2022-04-07 05:42 UTC, karansiwach360 commented on 123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java
> +      if (userInfo.getEmail() == null) {
this can be moved above before assigning optionalTargetUserInfo and use isEmpty method instead of null check.

2022-04-07 05:42 UTC, karansiwach360 commented on 123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java
> +      validateUserUpdateRequestOfServiceAccountPrincipalType(optionalTargetUserInfo.get(), accountIdentifier);
We are not allowing user to update details of another user even though if one is admin but that is not the case with service account?

2022-04-07 05:42 UTC, karansiwach360 commented on 123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java
> +    if (!verifyUserPartOfAccount(targetUserInfo, accountIdentifier)) {
We can skip this, permission check will be enough.

2022-04-12 07:52 UTC, naman-goenka commented on 123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java
> +      validateUserUpdateRequestOfServiceAccountPrincipalType(optionalTargetUserInfo.get(), accountIdentifier);
Yes, we are not allowing user to change details of another user in case of personal access token even if other checks are passing, but we are allowing the same in case of service token with adequate checks.

2022-04-14 06:25 UTC, naman-goenka commented on 123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/UserInfoServiceImpl.java
> +    if (!verifyUserPartOfAccount(targetUserInfo, accountIdentifier)) {
Kept the original behaviour

2022-04-15 07:03 UTC, naman-goenka commented
trigger ti0

2022-04-15 07:03 UTC, naman-goenka commented
trigger ti1

2022-04-17 08:15 UTC, gupta-utkarsh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r1, 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31761#-:-N-q_hd0-Q4S-EpXakw2:bnfp4nl)* status: 6 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-17 13:38 UTC, naman-goenka commented
trigger recency

2022-04-18 04:46 UTC, reetika04 approved these changes
> Reviewed 1 of 5 files at r1, 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31761)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-18 04:51 UTC, reetika04 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31761)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-18 04:53 UTC, reetika04 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31761#-:-N-v0C18-VWl00qW5QZK:bnfp4nl)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-18 05:10 UTC, merged