[fix]: [PL-23979]: Getting incorrect status code on invalid input in create connector api
harness/harness-core pull request #31764
Opened 2022-03-25 13:18 UTC by rathodmeetsatish

Getting incorrect status code on invalid input in create connector api

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-25 13:25 UTC, DeepakPatankar requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 204 at r1](https://reviewable.io/reviews/harness/harness-core/31764#-Mz0F4Wa4USeZvTI09K5:-Mz0F4Wa4USeZvTI09K6:blda2fn) ([raw file](https://github.com/harness/harness-core/blob/9cf7cb5d38a1961b624b55b9078b9a822bfca6b9/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L204)):*
> ```Java
>         deleteConnectorHeartbeatTask(accountIdentifier, fullyQualifiedIdentifier, connectorHeartbeatTaskId.getId());
>       }
>       throw new InvalidRequestException(ex.getMessage());
> ```

This way we might be exposing internal errors also to the user like NPEs

why do we want to wrap the exception ?


<!-- Sent from Reviewable.io -->

2022-03-25 15:49 UTC, abhinav-harness commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
> +      throw new InvalidRequestException(ex.getMessage());
ExecptionUtils.getMessage

2022-03-25 15:50 UTC, abhinav-harness commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
> +      throw new InvalidRequestException(ex.getMessage());
or if it is specific grpc exception then do instance of check or error code check before putting here or else it can result in internal error msg surfacing on UI

2022-03-28 04:54 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java
> +        branchDetails = BranchDetails.newBuilder().setError("").build();
Since we are throwing exceptions in line 137, these branch details won't be required?

2022-03-28 04:54 UTC, DeepakPatankar commented on 900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java
> +    if (defaultBranch != null) {
lets call this value defaultBarnchDetails

2022-03-28 13:59 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 136 at r2](https://reviewable.io/reviews/harness/harness-core/31764#-MzFonEfD9QSsM2mddT3:-MzFonEfD9QSsM2mddT4:byomxdy) ([raw file](https://github.com/harness/harness-core/blob/1e27393fc6494b7da17968d4d11e0f931f1ed34f/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L136)):*
> ```Java
>         branchDetails = BranchDetails.newBuilder().setError(ex.getMessage()).build();
>       } else {
>         branchDetails = BranchDetails.newBuilder().setError("").build();
> ```

what does this error response means?


<!-- Sent from Reviewable.io -->

2022-03-28 14:01 UTC, mohitg0795 commented
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java, line 88 at r2](https://reviewable.io/reviews/harness/harness-core/31764#-Mz1IPu2vYK6DPi6Eyce-r2-88:-MzFp3VHEvY4b5HIU3k3:b-lifqox) ([raw file](https://github.com/harness/harness-core/blob/1e27393fc6494b7da17968d4d11e0f931f1ed34f/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java#L88)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

lets call this value defaultBarnchDetails 
</blockquote></details>

Also, this value can't be null, right? Its from a stub response.


<!-- Sent from Reviewable.io -->

2022-03-29 11:35 UTC, mohitg0795 commented
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 133 at r4](https://reviewable.io/reviews/harness/harness-core/31764#-MzKSQHUALJMq14EPIM6:-MzKSQHUALJMq14EPIM7:b-evkd4x) ([raw file](https://github.com/harness/harness-core/blob/ce4b4b387dc367e2a87b772bf1fe5948893c92d9/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L133)):*
> ```Java
>       branchDetails = harnessToGitHelperService.getBranchDetails(request);
>       log.debug("Grpc request completed for getDefaultBranch");
>     } catch (InvalidRequestException ex) {
> ```

This exception handling should be inside service layer


<!-- Sent from Reviewable.io -->

2022-03-30 21:21 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 239 at r5](https://reviewable.io/reviews/harness/harness-core/31764#-MzRh9Tv7jb6m-AA4QS1:-MzRh9TwDCaVZZEehpZj:b-6kkcvr) ([raw file](https://github.com/harness/harness-core/blob/ea52e85c102119895563f37dc1039fc0dd4d3580/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L239)):*
> ```Java
>           repoDetails.getOrgIdentifier().getValue(), repoDetails.getAccountId(), repoDetails.getYamlGitConfigId());
>       return BranchDetails.newBuilder().setDefaultBranch(yamlGitConfigDTO.getBranch()).build();
>     } catch (InvalidRequestException ex) {
> ```

can we please log the exception here.


<!-- Sent from Reviewable.io -->

2022-03-30 21:22 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 131 at r5](https://reviewable.io/reviews/harness/harness-core/31764#-MzRhEeV9VhV9hObk-JX:-MzRhEeV9VhV9hObk-JY:bnw0xmz) ([raw file](https://github.com/harness/harness-core/blob/ea52e85c102119895563f37dc1039fc0dd4d3580/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L131)):*
> ```Java
>       log.debug("Grpc request received for getDefaultBranch");
>       branchDetails = harnessToGitHelperService.getBranchDetails(request);
>       log.debug("Grpc request completed for getDefaultBranch");
> ```

As its a new log added, lets make it info log with complete request and response.


<!-- Sent from Reviewable.io -->

2022-03-30 21:23 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 134 at r5](https://reviewable.io/reviews/harness/harness-core/31764#-MzRhPlf73uVhh5x6UEl:-MzRhPlf73uVhh5x6UEm:b-7c3gfp) ([raw file](https://github.com/harness/harness-core/blob/ea52e85c102119895563f37dc1039fc0dd4d3580/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L134)):*
> ```Java
>     } catch (Exception ex) {
>       final String errorMessage = ExceptionUtils.getMessage(ex);
>       branchDetails = BranchDetails.newBuilder().setError("").build();
> ```

I don't see any usage of this branchDetails variable inside catch block.


<!-- Sent from Reviewable.io -->

2022-03-30 21:24 UTC, mohitg0795 commented
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java, line 88 at r2](https://reviewable.io/reviews/harness/harness-core/31764#-Mz1IPu2vYK6DPi6Eyce-r2-88:-MzRhd9C1MflNrZQD00d:b-edo5xr) ([raw file](https://github.com/harness/harness-core/blob/1e27393fc6494b7da17968d4d11e0f931f1ed34f/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java#L88)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

was not sure so to be on safe side added a null check
</blockquote></details>

I think lets check more on it. I don't think it can be null ever. We can check and then take an informed decision. We shouldn't be putting redundant null checks and be more confident about our code certainty wherever we can be.


<!-- Sent from Reviewable.io -->

2022-04-01 05:21 UTC, DeepakPatankar reviewed
> Reviewed 1 of 4 files at r2, 1 of 4 files at r3, 1 of 7 files at r5, 1 of 4 files at r6, 2 of 3 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-02 18:32 UTC, mohitg0795 commented
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java, line 87 at r9](https://reviewable.io/reviews/harness/harness-core/31764#-MzfXzUUE9Immi9fhNrE:-MzfXzUUE9Immi9fhNrF:b-aq5qqp) ([raw file](https://github.com/harness/harness-core/blob/3ebf67ab55a53b68de9927e7fc5ab020a149c078/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java#L87)):*
> ```Java
>     }
>     final BranchDetails defaultBranchDetails =
>         harnessToGitPushInfoServiceBlockingStub.getDefaultBranch(repoDetailsBuilder.build());
> ```

how is the response handled in case there's a hypothetical NPE on the grpc call? I mean if it goes into the exception handling block on the grpc handler side, how does response is handled here in that case?


<!-- Sent from Reviewable.io -->

2022-04-02 18:32 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 240 at r9](https://reviewable.io/reviews/harness/harness-core/31764#-MzfYB3S9u3cNBDO0QNC:-MzfYB3S9u3cNBDO0QND:b-sq2zg7) ([raw file](https://github.com/harness/harness-core/blob/3ebf67ab55a53b68de9927e7fc5ab020a149c078/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L240)):*
> ```Java
>           repoDetails.getOrgIdentifier().getValue(), repoDetails.getAccountId(), repoDetails.getYamlGitConfigId());
>       return BranchDetails.newBuilder().setDefaultBranch(yamlGitConfigDTO.getBranch()).build();
>     } catch (InvalidRequestException ex) {
> ```

Do we need this special handling here now? Coz we are already handling exception at the top most layer now properly.


<!-- Sent from Reviewable.io -->

2022-04-02 18:39 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 240 at r9](https://reviewable.io/reviews/harness/harness-core/31764#-MzfYB3S9u3cNBDO0QNC:-MzfZBcm2tiCY4-PSMqM:bd1fxu5) ([raw file](https://github.com/harness/harness-core/blob/3ebf67ab55a53b68de9927e7fc5ab020a149c078/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L240)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Do we need this special handling here now? Coz we are already handling exception at the top most layer now properly.
</blockquote></details>

yes because on catching invalidRequestException we are adding error message in branch details which we dont do for other exceptions and use this behaviour in gitsyncsdkserviceimpl to throw exception if we have a non empty error in branch details


<!-- Sent from Reviewable.io -->

2022-04-02 18:46 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: 8 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, line 131 at r5](https://reviewable.io/reviews/harness/harness-core/31764#-MzRhEeV9VhV9hObk-JX:-MzfaFlXE_sW9ADf9Yb3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ea52e85c102119895563f37dc1039fc0dd4d3580/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L131)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

As its a new log added, lets make it info log with complete request and response.
</blockquote></details>

Done.
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java, line 87 at r9](https://reviewable.io/reviews/harness/harness-core/31764#-MzfXzUUE9Immi9fhNrE:-MzfaJfeAHBr9rt-QOtq:be9bbmf) ([raw file](https://github.com/harness/harness-core/blob/3ebf67ab55a53b68de9927e7fc5ab020a149c078/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java#L87)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

how is the response handled in case there's a hypothetical NPE on the grpc call? I mean if it goes into the exception handling block on the grpc handler side, how does response is handled here in that case?
</blockquote></details>

i can add a try catch block here


<!-- Sent from Reviewable.io -->

2022-04-02 18:47 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 240 at r9](https://reviewable.io/reviews/harness/harness-core/31764#-MzfYB3S9u3cNBDO0QNC:-MzfaN8LAxJg8pyfQo72:b5hxkvs) ([raw file](https://github.com/harness/harness-core/blob/3ebf67ab55a53b68de9927e7fc5ab020a149c078/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L240)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

yes because on catching invalidRequestException we are adding error message in branch details which we dont do for other exceptions and use this behaviour in gitsyncsdkserviceimpl to throw exception if we have a non empty error in branch details
</blockquote></details>

Ok, so basically we want to say that "error" field in response represents if it was genuine error. Sending status runtime exception from topmost layer represents that it was some random issue that happened. Correct?


<!-- Sent from Reviewable.io -->

2022-04-02 18:50 UTC, mohitg0795 commented
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java, line 87 at r9](https://reviewable.io/reviews/harness/harness-core/31764#-MzfXzUUE9Immi9fhNrE:-MzfbL9GAE35Gp-a2cvZ:b-mb04jl) ([raw file](https://github.com/harness/harness-core/blob/3ebf67ab55a53b68de9927e7fc5ab020a149c078/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitSyncSdkServiceImpl.java#L87)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

i can add a try catch block here
</blockquote></details>

If try catch is the only solution, then lets add that.


<!-- Sent from Reviewable.io -->

2022-04-04 17:57 UTC, rathodmeetsatish commented
trigger messagecheck

2022-04-04 18:16 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764#-:-MzpmjHv61St34UqGHvL:bnfp4nl)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-04 18:16 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r2, 1 of 4 files at r3, 1 of 7 files at r5, 3 of 3 files at r8, 1 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764#-:-MzpmnF-C4k-3GD6Okxq:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-05 05:04 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-05 07:26 UTC, abhinav-harness reviewed
> Reviewed 1 of 4 files at r2, 1 of 4 files at r3, 1 of 7 files at r5, 3 of 3 files at r8, 1 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-05 07:29 UTC, abhinav-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31764)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-05 07:29 UTC, merged