Pl 23494
harness/harness-core pull request #31791
Opened 2022-03-28 06:15 UTC by mankrit-singh

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-30 06:49 UTC, DeepakPatankar requested changes
> Reviewed 23 of 29 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 29 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoAppApiAccess.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzOZEA6-5NKKu2C17RJ:-MzOZEA6-5NKKu2C17RK:b1duaad) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoAppApiAccess.java#L17)):*
> ```Java
> @Builder
> @TypeAlias("io.harness.connector.entities.embedded.azurerepoconnector.AzureRepoAppApiAccess")
> public class AzureRepoAppApiAccess implements AzureRepoApiAccess {
> ```

Remove this DTO, it is not required
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzOZKfq5wEO-OvMF7lM:-MzOZKfq5wEO-OvMF7lN:b-djdgqf) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java#L30)):*
> ```Java
> @Persistent
> public class AzureRepoConnector extends Connector {
>     GitConnectionType connectionType;
> ```

Lets create AzureRepoConnectionType enum
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoUsernameToken.java, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzOZiZyCCoXrRlgVeMM:-MzOZiZyCCoXrRlgVeMN:b1yfzwv) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoUsernameToken.java#L17)):*
> ```Java
> @Builder
> @TypeAlias("io.harness.connector.entities.embedded.azurerepoconnector.AzureRepoUsernameToken")
> public class AzureRepoUsernameToken implements AzureRepoHttpAuth {
> ```

We don't need the other dto related to AzureRepoUsernamePassword
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessType.java, line 14 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzO_3GuAIrmR5L51OAE:-MzO_3GuAIrmR5L51OAF:b-pq5ww2) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessType.java#L14)):*
> ```Java
> 
> public enum AzureRepoApiAccessType {
>     @JsonProperty(AzureRepoConnectorConstants.AZUREREPO_APP) AZUREREPO_APP(AzureRepoConnectorConstants.AZUREREPO_APP),
> ```

App is not required
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorConstants.java, line 11 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzO_9OL6QYqJzCta4Ev:-MzO_9OL6QYqJzCta4Ew:bvkix2p) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorConstants.java#L11)):*
> ```Java
> 
> public class AzureRepoConnectorConstants {
>     public static final String AZUREREPO_APP = "AzureRepoApp";
> ```

Not required
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorConstants.java, line 14 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzO_AY415egGqqOVCOJ:-MzO_AY415egGqqOVCOK:bwn0gsx) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorConstants.java#L14)):*
> ```Java
>     public static final String TOKEN = "Token";
> 
>     public static final String USERNAME_AND_PASSWORD = "UsernamePassword";
> ```

Not Required
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 47 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzO_D3-AvhqGgWS3bgb:-MzO_D3-AvhqGgWS3bgc:b-hbavkw) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L47)):*
> ```Java
>         implements ScmConnector, DelegateSelectable, ManagerExecutable {
>     @NotNull @JsonProperty("type")
>     GitConnectionType connectionType;
> ```

Have a different AzureRepoConnectionType
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 57 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzO_J269q0hPFI6Y5pp:-MzO_J269q0hPFI6Y5pq:ba3ndg1) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L57)):*
> ```Java
>     AzureRepoApiAccessDTO apiAccess;
>     Set<String> delegateSelectors;
>     Boolean executeOnDelegate;
> ```

lets not have executeOnDelegate
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoHttpAuthenticationType.java, line 15 at r2](https://reviewable.io/reviews/harness/harness-core/31791#-MzO_NreB4ieYsCRT3El:-MzO_NreB4ieYsCRT3Em:b-cobrrd) ([raw file](https://github.com/harness/harness-core/blob/8ce4b8ad81ffa17598aba4f9a2a5663d98c2f077/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoHttpAuthenticationType.java#L15)):*
> ```Java
> public enum AzureRepoHttpAuthenticationType {
>     @JsonProperty(AzureRepoConnectorConstants.USERNAME_AND_PASSWORD)
>     USERNAME_AND_PASSWORD(AzureRepoConnectorConstants.USERNAME_AND_PASSWORD),
> ```

Remove Username and password


<!-- Sent from Reviewable.io -->

2022-03-31 09:43 UTC, DeepakPatankar requested changes
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 31 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/AzureRepoConnectionType.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/31791#-MzULgdq-2CtT8Pb54QP:-MzULgdq-2CtT8Pb54QQ:b-51xpc8) ([raw file](https://github.com/harness/harness-core/blob/a6505de2619a5a41bd5d6ca6fac1816475d94991/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/AzureRepoConnectionType.java#L13)):*
> ```Java
> 
> public enum AzureRepoConnectionType {
>     @JsonProperty(AzureRepoConfigConstants.ACCOUNT) ACCOUNT,
> ```

We will have ORGANIZATION inplace of account


<!-- Sent from Reviewable.io -->

2022-04-01 07:33 UTC, rijajoo reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 32 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/ConnectorRegistryFactory.java, line 110 at r4](https://reviewable.io/reviews/harness/harness-core/31791#-MzZ17OP3q-W6a8R5SoK:-MzZ17OQE8p-OYSJ2yXW:b-tyigbi) ([raw file](https://github.com/harness/harness-core/blob/717a8748df9677ceeb0260c3cda1334522b58645/440-connector-nextgen/src/main/java/io/harness/connector/ConnectorRegistryFactory.java#L110)):*
> ```Java
> import io.harness.connector.task.NotSupportedValidationHandler;
> import io.harness.connector.task.git.GitValidationHandler;
> import io.harness.connector.validator.*;
> ```

Let's not do * imports. Can you go through all the files and change this.


<!-- Sent from Reviewable.io -->

2022-04-04 06:49 UTC, DeepakPatankar approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: Some of the checks are too old. 32 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-04 07:01 UTC, DeepakPatankar commented on 440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java
> +    public AzureRepoConnectorDTO createConnectorDTO(AzureRepoConnector connector) {
if connector is null, then return null dto

2022-04-04 08:49 UTC, DeepakPatankar requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 32 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java, line 46 at r5](https://reviewable.io/reviews/harness/harness-core/31791#-Mznkt9L5CudNrzt3w9z:-Mznkt9L5CudNrzt3wA-:b-fx86yb) ([raw file](https://github.com/harness/harness-core/blob/829290444af41b4aa1fda12c3e439843fd3ee9c3/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L46)):*
> ```Java
>         }
>         if(configDTO.getAuthentication()==null){
>             throw new InvalidRequestException("No Authentication Found");
> ```

No authentication details found in the connector


<!-- Sent from Reviewable.io -->

2022-04-04 10:15 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 32 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-04 10:21 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java
> +    @SecretReference @ApiModelProperty(dataType = "string") SecretRefData usernameRef;
Should we add validation that one of the filed username or username ref should be present?

2022-04-04 10:22 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/ConnectorRegistryFactory.java
> +import io.harness.connector.validator.*;
remove start import

2022-04-04 10:23 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java
> +    AzureRepoApiAccess azureRepoApiAccess;
Do we need any non empty validations here?

2022-04-04 10:23 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoHttpAuthentication.java
> +    AzureRepoHttpAuth auth;
same?

2022-04-04 10:24 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoSshAuthentication.java
> +    String sshKeyRef;
same

2022-04-04 10:24 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoTokenApiAccess.java
> +    String tokenRef;
same for all instances

2022-04-04 10:24 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoUsernameToken.java
> +    String tokenRef;
same

2022-04-04 10:29 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/AzureRepoConfigConstants.java
> +    // connection type
remove

2022-04-04 11:04 UTC, DeepakPatankar approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 32 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java, line 38 at r6](https://reviewable.io/reviews/harness/harness-core/31791#-MzE9Y_xjs_hUAo99iuy-r6-38:-MzoEmTzAXmVOwsm4IIx:ba60idt) ([raw file](https://github.com/harness/harness-core/blob/1322bfe6c27ef9772be8566e3e4a0242b13bd89d/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java#L38)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Do we need any non empty validations here?
</blockquote></details>

This is the entity class, I think the javax annotations won't work here


<!-- Sent from Reviewable.io -->

2022-04-04 11:05 UTC, DeepakPatankar submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 32 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 57 at r6](https://reviewable.io/reviews/harness/harness-core/31791#-MzE9Y_xjs_hUAo99ivE-r6-57:-MzoEvneEcTuMH3j6lTh:b9zqyx1) ([raw file](https://github.com/harness/harness-core/blob/1322bfe6c27ef9772be8566e3e4a0242b13bd89d/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L57)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

We will need to add description for all fields in DTO.
</blockquote></details>

acknowledged, @mankrit-singh please add descriptions
___
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java, line 32 at r6](https://reviewable.io/reviews/harness/harness-core/31791#-MzE9Y_xjs_hUAo99ivM-r6-32:-MzoF2eg7WHGEl2ccyfg:bo8nqbq) ([raw file](https://github.com/harness/harness-core/blob/1322bfe6c27ef9772be8566e3e4a0242b13bd89d/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java#L32)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Should we add validation that one of the filed username or username ref should be present?
</blockquote></details>

Yes acknowledged


<!-- Sent from Reviewable.io -->

2022-04-04 12:26 UTC, meenakshi-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 32 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java, line 38 at r6](https://reviewable.io/reviews/harness/harness-core/31791#-MzE9Y_xjs_hUAo99iuy-r6-38:-MzoXTCx9JaUI4TQiPIU:b-9eb1c9) ([raw file](https://github.com/harness/harness-core/blob/1322bfe6c27ef9772be8566e3e4a0242b13bd89d/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java#L38)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

This is the entity class, I think the javax annotations won't work here
</blockquote></details>

Not sure but should we try `org.hibernate.validator.constraints.NotEmpty;`


<!-- Sent from Reviewable.io -->

2022-04-04 12:41 UTC, DeepakPatankar reviewed
> Reviewed 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 32 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java, line 38 at r6](https://reviewable.io/reviews/harness/harness-core/31791#-MzE9Y_xjs_hUAo99iuy-r6-38:-Mzoa3xOBeI2qM1BKp5w:bzeik9w) ([raw file](https://github.com/harness/harness-core/blob/1322bfe6c27ef9772be8566e3e4a0242b13bd89d/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java#L38)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Not sure but should we try `org.hibernate.validator.constraints.NotEmpty;`
</blockquote></details>

Yes @mankrit-singh  can you add annotations from hibernate package


<!-- Sent from Reviewable.io -->

2022-04-05 06:48 UTC, DeepakPatankar requested changes
> Reviewed 1 of 4 files at r7, 14 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 34 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java, line 34 at r8](https://reviewable.io/reviews/harness/harness-core/31791#-MzsTU9e1W7TyNBM_7r7:-MzsTU9e1W7TyNBM_7r8:b-ditoeb) ([raw file](https://github.com/harness/harness-core/blob/641a2dc0acc41e30a1766029bf6b03a99c0083ca/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java#L34)):*
> ```Java
>     @NotEmpty AzureRepoConnectionType connectionType;
>     @NotEmpty String url;
>     @NotEmpty String validationRepo;
> ```

This can be empty
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java, line 38 at r8](https://reviewable.io/reviews/harness/harness-core/31791#-MzsTVgL2TSwlf24a6ii:-MzsTVgL2TSwlf24a6ij:b-ditoeb) ([raw file](https://github.com/harness/harness-core/blob/641a2dc0acc41e30a1766029bf6b03a99c0083ca/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java#L38)):*
> ```Java
>     @NotEmpty AzureRepoAuthentication authenticationDetails;
>     @NotEmpty boolean hasApiAccess;
>     @NotEmpty AzureRepoApiAccessType apiAccessType;
> ```

This can be empty
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java, line 39 at r8](https://reviewable.io/reviews/harness/harness-core/31791#-MzsTWrn5BYHc9Mh5qM9:-MzsTWrn5BYHc9Mh5qMA:b-ditoeb) ([raw file](https://github.com/harness/harness-core/blob/641a2dc0acc41e30a1766029bf6b03a99c0083ca/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoConnector.java#L39)):*
> ```Java
>     @NotEmpty boolean hasApiAccess;
>     @NotEmpty AzureRepoApiAccessType apiAccessType;
>     @NotEmpty AzureRepoApiAccess azureRepoApiAccess;
> ```

This can be empty
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoUsernameToken.java, line 19 at r8](https://reviewable.io/reviews/harness/harness-core/31791#-MzsTa-d2sxroIGeCqpd:-MzsTa-d2sxroIGeCqpe:bewwobp) ([raw file](https://github.com/harness/harness-core/blob/641a2dc0acc41e30a1766029bf6b03a99c0083ca/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoUsernameToken.java#L19)):*
> ```Java
> @TypeAlias("io.harness.connector.entities.embedded.azurerepoconnector.AzureRepoUsernameToken")
> public class AzureRepoUsernameToken implements AzureRepoHttpAuth {
>     @NotEmpty String username;
> ```

Can be empty
___
*[440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoUsernameToken.java, line 20 at r8](https://reviewable.io/reviews/harness/harness-core/31791#-MzsTb7U0rq1EyjBegv0:-MzsTb7U0rq1EyjBegv1:b-jiq5vf) ([raw file](https://github.com/harness/harness-core/blob/641a2dc0acc41e30a1766029bf6b03a99c0083ca/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurerepoconnector/AzureRepoUsernameToken.java#L20)):*
> ```Java
> public class AzureRepoUsernameToken implements AzureRepoHttpAuth {
>     @NotEmpty String username;
>     @NotEmpty String usernameRef;
> ```


Can be empty


<!-- Sent from Reviewable.io -->

2022-04-06 04:35 UTC, DeepakPatankar approved these changes
> Reviewed 30 of 30 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 37 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-06 06:54 UTC, meenakshi-harness reviewed
> Reviewed 2 of 29 files at r1, 1 of 15 files at r8, 30 of 30 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-06 06:57 UTC, meenakshi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:03 UTC, DeepakPatankar approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:08 UTC, rijajoo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 29 files at r1, 1 of 15 files at r8, 30 of 30 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791#-:-Mzxgvz1-1hVuHkLN0X5:bnfp4nl)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:15 UTC, rathodmeetsatish approved these changes
> Reviewed 2 of 29 files at r1, 1 of 15 files at r8, 30 of 30 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:16 UTC, meenakshi-harness submitted a review, later dismissed
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:18 UTC, mankrit-singh commented
*[440-connector-nextgen/src/main/java/io/harness/connector/ConnectorRegistryFactory.java, line 110 at r4](https://reviewable.io/reviews/harness/harness-core/31791#-MzZ17OP3q-W6a8R5SoK:-Mzxj6Ds7Bm5hFnqih_W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/717a8748df9677ceeb0260c3cda1334522b58645/440-connector-nextgen/src/main/java/io/harness/connector/ConnectorRegistryFactory.java#L110)):*
<details><summary><i>Previously, rijajoo (Richa Jajoo) wrote…</i></summary><blockquote>

Let's not do * imports. Can you go through all the files and change this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-06 07:19 UTC, rathodmeetsatish approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:25 UTC, rijajoo submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791#-:-MzxkmnO6JpYn4sHACXx:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:44 UTC, rathodmeetsatish approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 07:46 UTC, mankrit-singh reviewed
> Reviewed 2 of 29 files at r1, 1 of 10 files at r3, 1 of 15 files at r8, 28 of 30 files at r9, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 08:00 UTC, mankrit-singh reviewed
> Reviewed 2 of 6 files at r2, 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 08:28 UTC, DeepakPatankar approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-06 08:28 UTC, DeepakPatankar submitted a review, later dismissed

2022-04-06 08:34 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java, line 43 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy-cOB9wmRRBt5GriI:-Mzy-cOCE0eRUAXP0QEs:bt6lwbp) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L43)):*
> ```Java
>   public AzureRepoConnector toConnectorEntity(AzureRepoConnectorDTO configDTO) {
>     if (configDTO == null) {
>       return null;
> ```

Please don't return null here. Throw exception.


<!-- Sent from Reviewable.io -->

2022-04-06 08:37 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java, line 108 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy0HoQB7p-CxKLMzqq:-Mzy0HoQB7p-CxKLMzqr:bpecziu) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L108)):*
> ```Java
>       usernameRef = SecretRefHelper.getSecretConfigString(secretRefData);
>     }
>     return usernameRef;
> ```

lets not return null if this is not a valid case. Throw exception if null isn't expected.


<!-- Sent from Reviewable.io -->

2022-04-06 08:38 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java, line 42 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy0eIR23rEcDjGBSzv:-Mzy0eIR23rEcDjGBSzw:bv7eqw4) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L42)):*
> ```Java
>   public AzureRepoConnectorDTO createConnectorDTO(AzureRepoConnector connector) {
>     if (connector == null) {
>       return null;
> ```

please throw exception


<!-- Sent from Reviewable.io -->

2022-04-06 08:39 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java, line 40 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy0nQS4ahwxmnUExM8:-Mzy0nQS4ahwxmnUExM9:b-tmbhca) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L40)):*
> ```Java
> public class AzureRepoEntityToDTO implements ConnectorEntityToDTOMapper<AzureRepoConnectorDTO, AzureRepoConnector> {
>   @Override
>   public AzureRepoConnectorDTO createConnectorDTO(AzureRepoConnector connector) {
> ```

I see some methods are static while some are not. Any reason?


<!-- Sent from Reviewable.io -->

2022-04-06 08:40 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java, line 78 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy0zKu1fh-v4U5EDbp:-Mzy0zKu1fh-v4U5EDbq:bveywfy) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L78)):*
> ```Java
>         break;
>       default:
>         Switch.unhandled(authType);
> ```

I see different way of handling default in dtoToEntity layer. Please be consistent.


<!-- Sent from Reviewable.io -->

2022-04-06 08:40 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java, line 100 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy13Se9COE2Lp3H2VY:-Mzy13Se9COE2Lp3H2VZ:bveywfy) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L100)):*
> ```Java
>         break;
>       default:
>         Switch.unhandled(type);
> ```

I see different way of handling default in dtoToEntity layer. Please be consistent.


<!-- Sent from Reviewable.io -->

2022-04-06 08:40 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java, line 116 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy16Om9d7HxGrHp9_X:-Mzy16Om9d7HxGrHp9_Y:bveywfy) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L116)):*
> ```Java
>         break;
>       default:
>         Switch.unhandled(apiAccessType);
> ```

I see different way of handling default in dtoToEntity layer. Please be consistent.


<!-- Sent from Reviewable.io -->

2022-04-06 08:42 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java, line 95 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1Q5-DrRzRZgG1xw0:-Mzy1Q5-DrRzRZgG1xw1:b-uz7woq) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java#L95)):*
> ```Java
>       @JsonSubTypes.Type(value = ServiceNowConnectorDTO.class, name = "ServiceNow"),
>       @JsonSubTypes.Type(value = ErrorTrackingConnectorDTO.class, name = "ErrorTracking"),
>       @JsonSubTypes.Type(value = AzureRepoConnectorDTO.class, name = "AzureRepo"),
> ```

Just curious, for other connectors like github/bitbucket etc, its GithubConnectorDTO , but for azure, its Azure"Repo"ConnectorDTO, any reason? Can we be consistent?


<!-- Sent from Reviewable.io -->

2022-04-06 08:43 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java, line 59 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1bfd13Hl3JNSqO9G:-Mzy1bfd13Hl3JNSqO9H:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java#L59)):*
> ```Java
>   @JsonProperty("ServiceNow") SERVICENOW("ServiceNow"),
>   @JsonProperty("ErrorTracking") ERROR_TRACKING("ErrorTracking"),
>   @JsonProperty("AzureRepo") AZURE_REPO("AzureRepo"),
> ```

same as above


<!-- Sent from Reviewable.io -->

2022-04-06 08:43 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/AzureRepoConfigConstants.java, line 10 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1er34eQtOZaeqyXe:-Mzy1er34eQtOZaeqyXf:byh55ae) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/AzureRepoConfigConstants.java#L10)):*
> ```Java
> package io.harness.delegate.beans.connector.scm;
> 
> public class AzureRepoConfigConstants {
> ```

owned details missing.


<!-- Sent from Reviewable.io -->

2022-04-06 08:43 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/AzureRepoConnectionType.java, line 12 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1oSn6gZcnlWNmJuP:-Mzy1oSn6gZcnlWNmJuQ:bgpn7w8) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/AzureRepoConnectionType.java#L12)):*
> ```Java
> import com.fasterxml.jackson.annotation.JsonProperty;
> 
> public enum AzureRepoConnectionType {
> ```

owner details missing.


<!-- Sent from Reviewable.io -->

2022-04-06 08:44 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessDTO.java, line 30 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1w3u9vQ6EexSQvj0:-Mzy1w3u9vQ6EexSQvj1:bgpn7w8) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessDTO.java#L30)):*
> ```Java
> @Schema(name = "AzureRepoApiAccess",
>     description = "This contains details of the information needed for Azure DevOps API access")
> ```

owner details missing.


<!-- Sent from Reviewable.io -->

2022-04-06 08:45 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessDTO.java, line 29 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy20rD9sdHnMFH11cz:-Mzy20rD9sdHnMFH11d-:bv4tns7) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessDTO.java#L29)):*
> ```Java
> @ApiModel("AzureRepoApiAccess")
> @Schema(name = "AzureRepoApiAccess",
>     description = "This contains details of the information needed for Azure DevOps API access")
> ```

Just make sure we use same terminology all across : "Azure DevOps". We can check with documentation team as well.


<!-- Sent from Reviewable.io -->

2022-04-06 08:45 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessSpecDTO.java, line 24 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy2BWGD5cPpaM5qH-r:-Mzy2BWGD5cPpaM5qH-s:bgpn7w8) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessSpecDTO.java#L24)):*
> ```Java
>         "This contains details of the information such as references of username and password needed for Github API access")
> 
> public interface AzureRepoApiAccessSpecDTO extends DecryptableEntity {}
> ```

owner details missing.


<!-- Sent from Reviewable.io -->

2022-04-06 08:45 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessSpecDTO.java, line 20 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy2ChdCDZRftvG3R_l:-Mzy2ChdCDZRftvG3R_m:b-an4xjt) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessSpecDTO.java#L20)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @JsonSubTypes({ @JsonSubTypes.Type(value = AzureRepoTokenSpecDTO.class, name = TOKEN) })
> @Schema(name = "GithubApiAccessSpec",
> ```

Why is schema name github api access?


<!-- Sent from Reviewable.io -->

2022-04-06 08:45 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessSpecDTO.java, line 22 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy2Fk3D-NCoWgpfDJb:-Mzy2Fk3D-NCoWgpfDJc:b-np6uk6) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessSpecDTO.java#L22)):*
> ```Java
> @Schema(name = "GithubApiAccessSpec",
>     description =
>         "This contains details of the information such as references of username and password needed for Github API access")
> ```

again github in the description


<!-- Sent from Reviewable.io -->

2022-04-06 08:46 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessType.java, line 13 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy2PR39rWZE5nv2O3n:-Mzy2PR39rWZE5nv2O3o:bgpn7w8) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoApiAccessType.java#L13)):*
> ```Java
> import com.fasterxml.jackson.annotation.JsonValue;
> 
> public enum AzureRepoApiAccessType {
> ```

owner details missing.


<!-- Sent from Reviewable.io -->

2022-04-06 08:47 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoAuthenticationDTO.java, line 28 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy2Wd_6nxLyvYntMqP:-Mzy2Wd_6nxLyvYntMqQ:b-kbgz5a) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoAuthenticationDTO.java#L28)):*
> ```Java
> import lombok.experimental.FieldDefaults;
> 
> @OwnedBy(HarnessTeam.DX)
> ```

should be HarnessTeam.PL


<!-- Sent from Reviewable.io -->

2022-04-06 08:47 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorConstants.java, line 10 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy2izb0W2YxYm4D3b2:-Mzy2izb0W2YxYm4D3b3:bgpn7w8) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorConstants.java#L10)):*
> ```Java
> package io.harness.delegate.beans.connector.scm.azurerepo;
> 
> public class AzureRepoConnectorConstants {
> ```

owner details missing.


<!-- Sent from Reviewable.io -->

2022-04-06 08:49 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 51 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy2y1IBsgp6d3H29_e:-Mzy2y1J8AzgHsm2dIHd:b-s6tqb6) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L51)):*
> ```Java
>   @Schema(description = "Organization | Repository URL type")
>   AzureRepoConnectionType connectionType;
>   @NotBlank @NotNull @Schema(description = "SSH | HTTP based on type of connection") String url;
> ```

description should mention "url" somewhere


<!-- Sent from Reviewable.io -->

2022-04-06 08:49 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 49 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy31G3-ysV9_dSvi0n:-Mzy31G3-ysV9_dSvi0o:b-zev70g) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L49)):*
> ```Java
>   @NotNull
>   @JsonProperty("type")
>   @Schema(description = "Organization | Repository URL type")
> ```

its connectorType not URL type.


<!-- Sent from Reviewable.io -->

2022-04-06 08:49 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 52 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy36ds-33VsLrdmMZR:-Mzy36ds-33VsLrdmMZS:b-cprw47) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L52)):*
> ```Java
>   AzureRepoConnectionType connectionType;
>   @NotBlank @NotNull @Schema(description = "SSH | HTTP based on type of connection") String url;
>   @Schema(description = "The validation repo for when user selects an organization type connector")
> ```

description doesn't seem correct here.


<!-- Sent from Reviewable.io -->

2022-04-06 08:49 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 56 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3BMd4z8bpfNXV5zc:-Mzy3BMd4z8bpfNXV5zd:bqwlpsb) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L56)):*
> ```Java
>   @Valid
>   @NotNull
>   @Schema(description = "Type and Respective Spec for HTTP or SSH")
> ```

description doesn't seem correct


<!-- Sent from Reviewable.io -->

2022-04-06 08:50 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 58 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3F4Z06aR_-6y43Pi:-Mzy3F4Z06aR_-6y43Pj:bqwlpsb) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L58)):*
> ```Java
>   @Schema(description = "Type and Respective Spec for HTTP or SSH")
>   AzureRepoAuthenticationDTO authentication;
>   @Valid @Schema(description = "To provide API Access") AzureRepoApiAccessDTO apiAccess;
> ```

description doesn't seem correct


<!-- Sent from Reviewable.io -->

2022-04-06 08:50 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoCredentialsDTO.java, line 21 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3Nvo8cbg7zTXlgPz:-Mzy3Nvo8cbg7zTXlgQ-:b-41keyy) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoCredentialsDTO.java#L21)):*
> ```Java
>   , @JsonSubTypes.Type(value = AzureRepoSshCredentialsDTO.class, name = GitConfigConstants.SSH)
> })
> @Schema(name = "AzureRepoCredentials", description = "This is a interface for details of the Azure DevOps credentials")
> ```

owner details missing


<!-- Sent from Reviewable.io -->

2022-04-06 08:51 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoCredentialsDTO.java, line 18 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3S8-BBppe3D7si3-:-Mzy3S8-BBppe3D7si30:b-bpa4fd) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoCredentialsDTO.java#L18)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @JsonSubTypes({
>   @JsonSubTypes.Type(value = AzureRepoHttpCredentialsDTO.class, name = GitConfigConstants.HTTP)
> ```

name seems to be something Git, not Azure. Is it correct?


<!-- Sent from Reviewable.io -->

2022-04-06 08:51 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoCredentialsDTO.java, line 19 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3Vb28Hyg2sqtu2Xd:-Mzy3Vb28Hyg2sqtu2Xe:b-bpa4fd) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoCredentialsDTO.java#L19)):*
> ```Java
> @JsonSubTypes({
>   @JsonSubTypes.Type(value = AzureRepoHttpCredentialsDTO.class, name = GitConfigConstants.HTTP)
>   , @JsonSubTypes.Type(value = AzureRepoSshCredentialsDTO.class, name = GitConfigConstants.SSH)
> ```

name seems to be something Git, not Azure. Is it correct?


<!-- Sent from Reviewable.io -->

2022-04-06 08:51 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoHttpAuthenticationType.java, line 13 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3_Vs4kid_Oo1mXyR:-Mzy3_Vs4kid_Oo1mXyS:b-41keyy) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoHttpAuthenticationType.java#L13)):*
> ```Java
> import com.fasterxml.jackson.annotation.JsonValue;
> 
> public enum AzureRepoHttpAuthenticationType {
> ```

owner details missing


<!-- Sent from Reviewable.io -->

2022-04-06 08:52 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoHttpCredentialsSpecDTO.java, line 23 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3ljg5tK8X_d64NSQ:-Mzy3ljg5tK8X_d64NSR:bnas73k) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoHttpCredentialsSpecDTO.java#L23)):*
> ```Java
>     description =
>         "This is a interface for details of the AzureRepo credentials Specs such as references of username and password")
> public interface AzureRepoHttpCredentialsSpecDTO extends DecryptableEntity {}
> ```

owner details


<!-- Sent from Reviewable.io -->

2022-04-06 08:53 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoTokenSpecDTO.java, line 31 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy425C4lWQdR7yJnC7:-Mzy425C4lWQdR7yJnC8:bnas73k) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoTokenSpecDTO.java#L31)):*
> ```Java
>     description =
>         "This contains details of the information such as references of token needed for AzureRepo API access")
> public class AzureRepoTokenSpecDTO implements AzureRepoApiAccessSpecDTO {
> ```

owner details


<!-- Sent from Reviewable.io -->

2022-04-06 08:54 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java, line 32 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy48sI6AY0S9qRj0np:-Mzy48sI6AY0S9qRj0nq:bnas73k) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java#L32)):*
> ```Java
>     description = "This contains details of the AzureRepo credentials Specs such as references of username and token")
> @OneOfField(fields = {"username", "usernameRef"})
> public class AzureRepoUsernameTokenDTO implements AzureRepoHttpCredentialsSpecDTO {
> ```

owner details


<!-- Sent from Reviewable.io -->

2022-04-06 08:54 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java, line 34 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy4Ec1E3NMuVqaCJQl:-Mzy4Ec1E3NMuVqaCJQm:byiaeat) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java#L34)):*
> ```Java
> public class AzureRepoUsernameTokenDTO implements AzureRepoHttpCredentialsSpecDTO {
>   String username;
>   @SecretReference @ApiModelProperty(dataType = "string") SecretRefData usernameRef;
> ```

usernameRef can be null? I see no @NotNull annotation here.


<!-- Sent from Reviewable.io -->

2022-04-06 10:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31791) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31791) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31791) it.</sub>

2022-04-06 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31791) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31791) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31791) it.</sub>

2022-04-06 11:00 UTC, mankrit-singh commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java, line 108 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy0HoQB7p-CxKLMzqq:-MzyWsrB9r6qB73QRiuF:b-k94rp6) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L108)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets not return null if this is not a valid case. Throw exception if null isn't expected.
</blockquote></details>

Any one of username and usernameRef should be not null, have added annotation at a later stage for this


<!-- Sent from Reviewable.io -->

2022-04-06 11:31 UTC, mankrit-singh commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java, line 95 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1Q5-DrRzRZgG1xw0:-Mzyck29DCJZJY3_Sbiz:biqd7r3) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java#L95)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Just curious, for other connectors like github/bitbucket etc, its GithubConnectorDTO , but for azure, its Azure"Repo"ConnectorDTO, any reason? Can we be consistent?
</blockquote></details>

Since there were already other connectors related to Azure like AzureConnector and AzureKeyVaultConnector, went with this naming to remove any confusion


<!-- Sent from Reviewable.io -->

2022-04-06 12:51 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java, line 95 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1Q5-DrRzRZgG1xw0:-MzyvJAw5b8lYLgSR7sB:bjnyrtq) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java#L95)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

Since there were already other connectors related to Azure like AzureConnector and AzureKeyVaultConnector, went with this naming to remove any confusion
</blockquote></details>

@deepakpatankar @mankrit-singh in that case, can we rename it to AzureGitConnectorDTO, that sounds more logical?


<!-- Sent from Reviewable.io -->

2022-04-06 12:51 UTC, abhinav-harness approved these changes
> Reviewed 2 of 29 files at r1, 1 of 15 files at r8, 11 of 30 files at r9, 2 of 2 files at r11, 17 of 17 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 21 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-06 12:57 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 56 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3BMd4z8bpfNXV5zc:-MzywgNOCI1U3ugoGxva:b-d8tqhz) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

description doesn't seem correct
</blockquote></details>

This isn't correct. It should be something like : "Details related to authentication mechanism for Azure Repo connector"

@rashminandasahoo please review all schema descriptions. This is a new connector that we are adding.


<!-- Sent from Reviewable.io -->

2022-04-06 12:57 UTC, DeepakPatankar approved these changes
> Reviewed 17 of 17 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 4 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-06 12:58 UTC, mohitg0795 commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 59 at r12](https://reviewable.io/reviews/harness/harness-core/31791#-Mzyx7mH23JcwBA4pgza:-Mzyx7mI1cv6S_YLWAbf:brbqih1) ([raw file](https://github.com/harness/harness-core/blob/fa5763d22002ea20ac6e46c6a92a6d3a48b36575/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L59)):*
> ```Java
>   AzureRepoAuthenticationDTO authentication;
>   @Valid
>   @Schema(description = "DTO for API access, used in Harness Triggers and Git Experience")
> ```

No mention of DTO should be there in description. cc @rashminandasahoo 


<!-- Sent from Reviewable.io -->

2022-04-06 13:00 UTC, mohitg0795 commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java, line 102 at r12](https://reviewable.io/reviews/harness/harness-core/31791#-MzyxUYq6vWWucbt_he4:-MzyxUYq6vWWucbt_he5:b6oeud6) ([raw file](https://github.com/harness/harness-core/blob/fa5763d22002ea20ac6e46c6a92a6d3a48b36575/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L102)):*
> ```Java
>         throw new UnknownEnumTypeException("AzureRepo Http Auth Type", type == null ? null : type.getDisplayName());
>     }
>   }
> ```

line spacing is missing.


<!-- Sent from Reviewable.io -->

2022-04-06 13:00 UTC, mohitg0795 reviewed
> Reviewed 2 of 29 files at r1, 2 of 6 files at r2, 2 of 10 files at r3, 1 of 15 files at r8, 11 of 30 files at r9, 2 of 2 files at r11, 17 of 17 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-06 13:27 UTC, abhinav-harness approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-06 13:30 UTC, DeepakPatankar approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-06 13:45 UTC, mankrit-singh commented
trigger ft2

2022-04-07 05:53 UTC, mankrit-singh commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java, line 102 at r12](https://reviewable.io/reviews/harness/harness-core/31791#-MzyxUYq6vWWucbt_he4:-N-1_SQ1-b0t9T382NTC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa5763d22002ea20ac6e46c6a92a6d3a48b36575/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L102)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing is missing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 05:54 UTC, mankrit-singh commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java, line 108 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy0HoQB7p-CxKLMzqq:-N-1_WeO3LNmbp5VS6wi:b-jfm05q) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L108)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Just curious, I see method name is getStringSecretForNullableSecret and we are returning usernameRef. Method name and the logic inside it doesn't relate, am I missing something here?
</blockquote></details>

Changed it.


<!-- Sent from Reviewable.io -->

2022-04-07 05:54 UTC, mankrit-singh commented
*[440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java, line 40 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy0nQS4ahwxmnUExM8:-N-1_aZu3iJaxPGzZ3hs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see some methods are static while some are not. Any reason?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 05:55 UTC, mankrit-singh commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java, line 95 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1Q5-DrRzRZgG1xw0:-N-1_mrtApqImCjMEurI:ba1rl4c) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java#L95)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@deepakpatankar @mankrit-singh in that case, can we rename it to AzureGitConnectorDTO, that sounds more logical?
</blockquote></details>

Azure Repo is used generally as well


<!-- Sent from Reviewable.io -->

2022-04-07 05:56 UTC, mankrit-singh commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java, line 59 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy1bfd13Hl3JNSqO9G:-N-1a-2UCE7p0Ypiye1e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 05:56 UTC, mankrit-singh commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 56 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3BMd4z8bpfNXV5zc:-N-1a84U93XXhgKnntyN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This isn't correct. It should be something like : "Details related to authentication mechanism for Azure Repo connector"

@rashminandasahoo please review all schema descriptions. This is a new connector that we are adding.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 05:56 UTC, mankrit-singh commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 58 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy3F4Z06aR_-6y43Pi:-N-1aAGR3LcKN8-HcjDK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

description doesn't seem correct
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 05:56 UTC, mankrit-singh commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java, line 59 at r12](https://reviewable.io/reviews/harness/harness-core/31791#-Mzyx7mH23JcwBA4pgza:-N-1aBhv8O-_t1nZqzzE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa5763d22002ea20ac6e46c6a92a6d3a48b36575/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No mention of DTO should be there in description. cc @rashminandasahoo 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-07 05:57 UTC, mankrit-singh commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java, line 34 at r11](https://reviewable.io/reviews/harness/harness-core/31791#-Mzy4Ec1E3NMuVqaCJQl:-N-1aIvdEXkkKXn1xBA6:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/2991165ff843ec0f8a5310cca3d6558897260c0a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoUsernameTokenDTO.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

usernameRef can be null? I see no @NotNull annotation here.
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2022-04-07 06:35 UTC, mohitg0795 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791#-:-N-1isrZ6ykHeTVC4Rx5:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-07 06:49 UTC, DeepakPatankar approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 06:49 UTC, mohitg0795 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791#-:-N-1mIHyDIoq9FD5uJrh:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-07 06:52 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791#-:-N-1myTq5QzMYbjFuytF:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 06:53 UTC, DeepakPatankar approved these changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-07 07:20 UTC, puthrayaharness approved these changes
> Reviewed 2 of 29 files at r1, 1 of 15 files at r8, 11 of 30 files at r9, 15 of 17 files at r12, 2 of 2 files at r13, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31791)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-07 07:20 UTC, merged

2022-04-07 07:21 UTC, raghuAtWings commented
*[954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java, line 59 at r15](https://reviewable.io/reviews/harness/harness-core/31791#-N-1tBcK6C-yzhVGqwL1:-N-1tBcK6C-yzhVGqwL2:bbkuhza) ([raw file](https://github.com/harness/harness-core/blob/f1b38f9e3add3ea4db85d88a9cd0d40b224733f7/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java#L59)):*
> ```Java
>   @JsonProperty("ServiceNow") SERVICENOW("ServiceNow"),
>   @JsonProperty("ErrorTracking") ERROR_TRACKING("ErrorTracking"),
>   @JsonProperty("AzureRepo") AZURE_REPO("AzureRepo"),
> ```

this will break things, the new enum should be added in the end


<!-- Sent from Reviewable.io -->