fix: [CI-3930]: fix addon le version #31793
harness/harness-core pull request #31832
Opened 2022-03-29 05:04 UTC by aman-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-04-06 10:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31832) it.</sub>

2022-04-06 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31832) it.</sub>

2022-04-11 12:40 UTC, HenAmar requested changes

2022-04-11 14:46 UTC, aman-harness commented on 120-ng-manager/src/main/java/io/harness/ng/trialsignup/CIProvisionResource.java
> +  @POST
fixed

2022-04-13 17:26 UTC, HenAmar submitted a review, later dismissed

2022-04-13 19:21 UTC, HenAmar approved these changes

2022-04-14 06:04 UTC, HenAmar approved these changes

2022-04-14 06:08 UTC, HenAmar approved these changes
> Reviewed 2 of 7 files at r1, 2 of 4 files at r2, 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31832)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-14 06:08 UTC, merged