feat: [CDS-25357]: Digest SHA now available as an artifact field
harness/harness-core pull request #31871
Opened 2022-03-30 09:53 UTC by atharvatrivedi1

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-04-04 03:20 UTC, puthrayaharness requested changes

2022-04-04 03:20 UTC, puthrayaharness commented on 400-rest/src/main/java/software/wings/expression/ArtifactMetaEvaluator.java
> +  public synchronized String output() {
This should be private method and void.

2022-04-04 03:20 UTC, puthrayaharness commented on 400-rest/src/main/java/software/wings/expression/ArtifactMetaEvaluator.java
> +    return output();
Here we should call output. And do a return `artifactMetaInfo.getSha()` when `artifactMetaInfo` is not null.

2022-04-04 03:20 UTC, puthrayaharness commented on 400-rest/src/main/java/software/wings/expression/ArtifactMetaEvaluator.java
> +public class ArtifactMetaEvaluator {
We need to create an interface and have this class extend the interface. We are trying to move the Artifact class to the lower layer.

2022-04-04 03:20 UTC, puthrayaharness commented on 400-rest/src/main/java/software/wings/service/impl/BuildSourceServiceImpl.java
> +  public ArtifactMetaInfo getMetaInfo(ArtifactStream artifactStream, List<String> buildNos) {
Since this is taking a list of tags it cannot return just one AritfactMetaInfo. Please update this method to just take one tag rather than multiple tags.

2022-04-06 10:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31871) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31871) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31871) it.</sub>

2022-04-06 10:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31871) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31871) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31871) it.</sub>

2022-08-01 21:14 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 15 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 1 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 11 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 3 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/31871)

2022-09-27 05:12 UTC, closed without merging