[PL-24124]: processing full-sync files in batches
harness/harness-core pull request #31885
Opened 2022-03-30 13:25 UTC by bhavya181

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-31 07:17 UTC, abhinav-harness commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java
> +  Map<Microservice, List<EntityType>> getEntitiesProcessingOrderInMicroservice() {
create a techdebt ticket to get rid of this later
the idea should be in the fetch stage msvc give them in sorted order of processing

2022-03-31 07:22 UTC, abhinav-harness requested changes

2022-03-31 07:22 UTC, abhinav-harness commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java
> +  Map<Microservice, List<EntityType>> getEntitiesProcessingOrderInMicroservice() {
It would be better if we can do it already

2022-03-31 08:45 UTC, goelsatyam2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java, line 129 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU7CoP7nioEDj28INB:-MzU7CoP7nioEDj28INC:bq6mg71) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java#L129)):*
> ```Java
>   @Provides
>   @Singleton
>   @Named("gitEntitiesProcessingOrderInMsvc")
> ```

how provider and named annotation are helping here?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java, line 130 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU5yvJ2jQY-q5i5pIw:-MzU5yvJ2jQY-q5i5pIx:b-knp8dp) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java#L130)):*
> ```Java
>   @Singleton
>   @Named("gitEntitiesProcessingOrderInMsvc")
>   Map<Microservice, List<EntityType>> getEntitiesProcessingOrderInMicroservice() {
> ```

Please add the comment, on why we are processing entities on this specific order?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 100 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU6Yh16Gffxx3HkeKm:-MzU6Yh16Gffxx3HkeKn:b-u7d7fk) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L100)):*
> ```Java
> 
>   @Override
>   public FullSyncMsvcProcessingResponse processFilesInBatches(
> ```

can we break this function into two smaller functions?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-MzU8PmP2EeSGWRgJdol:bdl4jfo) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
> ```Java
>           processFiles(microservice, entityInfoList.subList(startIndex, endIndex));
>       fullSyncFileResponses.addAll(fullSyncMsvcProcessingResponse.getFullSyncFileResponses());
>       isSyncFailed = fullSyncMsvcProcessingResponse.isSyncFailed() || isSyncFailed;
> ```

if isSyncFailed fails do we need to process the remaining batches?


<!-- Sent from Reviewable.io -->

2022-03-31 13:38 UTC, DeepakPatankar requested changes
> Reviewed 1 of 3 files at r1, 3 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 11 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorService.java, line 22 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzVB_ak17OEnlu_R4jq:-MzVB_ak17OEnlu_R4jr:bxm8o2v) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorService.java#L22)):*
> ```Java
> @OwnedBy(DX)
> public interface GitFullSyncProcessorService {
>   FullSyncMsvcProcessingResponse processFilesInBatches(
> ```

This is not required to be a private function


<!-- Sent from Reviewable.io -->

2022-03-31 13:39 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 11 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 86 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzVBquFBbCS70HYWqdm:-MzVBquFBbCS70HYWqdn:bpc5epv) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L86)):*
> ```Java
>     boolean isSyncFailed = false;
>     if (isEmpty(entityInfoList)) {
>       FullSyncMsvcProcessingResponse.builder()
> ```

should we have a return statement here ?


<!-- Sent from Reviewable.io -->

2022-03-31 20:41 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/beans/GitFullSyncEntityInfo.java, line 70 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzWhUDf8wY3JgWHJHH2:-MzWhUDf8wY3JgWHJHH3:b-li4j5m) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/beans/GitFullSyncEntityInfo.java#L70)):*
> ```Java
>   @FdIndex @NonFinal Long nextRuntime;
>   List<String> errorMessage;
>   int fileProcessingNumber;
> ```

Can we name it better: something like fileProcessingSequenceIndex, fileProcessingSequenceNumber, fileProcessingSequenceOrderNumber etc.


<!-- Sent from Reviewable.io -->

2022-03-31 21:04 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 86 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzVBquFBbCS70HYWqdm:-MzWmsJk41h-sMZw8_sK:b32v57) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L86)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

should we have a return statement here ?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-03-31 21:08 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-MzWnhknDP8Xp969KkOw:b41ok7d) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

if isSyncFailed fails do we need to process the remaining batches?
</blockquote></details>

+1

Doesn't it violate the ordering logic that we have?


<!-- Sent from Reviewable.io -->

2022-03-31 21:09 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 104 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzWntYk46JhAXPVBPla:-MzWntYk46JhAXPVBPlb:bo0r5b2) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L104)):*
> ```Java
>       batchIndex++;
>     }
> ```

lets put a success log over here.


<!-- Sent from Reviewable.io -->

2022-03-31 21:17 UTC, mohitg0795 commented
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/fullsync/FullSyncSdkServiceImpl.java, line 57 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzWpfBd16WXpc_FHyTs:-MzWpfBd16WXpc_FHyTt:b-nk4229) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/900-git-sync-sdk/src/main/java/io/harness/gitsync/fullsync/FullSyncSdkServiceImpl.java#L57)):*
> ```Java
>           gitPersistenceHelperService.listAllUnsyncedEntitiesInProcessingOrder(scopeDetails);
>       log.info("Entities for full sync for entityType [{}]: [{}]", entityType, entitiesForFullSync);
>       if (entitiesForFullSync != null) {
> ```

we can use shorthand notation here : emptyIfNull()


<!-- Sent from Reviewable.io -->

2022-04-05 07:07 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 25 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/beans/GitFullSyncEntityInfo.java, line 70 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzWhUDf8wY3JgWHJHH2:-MzsXJ0U4YOnFMBW1kdt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/beans/GitFullSyncEntityInfo.java#L70)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we name it better: something like fileProcessingSequenceIndex, fileProcessingSequenceNumber, fileProcessingSequenceOrderNumber etc.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorService.java, line 22 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzVB_ak17OEnlu_R4jq:-MzsXtr91-HGzvMVXBBk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorService.java#L22)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

This is not required to be a private function
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 100 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU6Yh16Gffxx3HkeKm:-MzsXMYD0FwQCmiauXVF:btpwedp) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L100)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

can we break this function into two smaller functions?
</blockquote></details>

This just do a ssingle operation, no need to break it
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-MzsXvou9wkV02mgpODm:b-wx270n) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

+1

Doesn't it violate the ordering logic that we have?
</blockquote></details>

No, it won't, we will process other entities, if some middle entity has error
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/fullsync/FullSyncSdkServiceImpl.java, line 57 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzWpfBd16WXpc_FHyTs:-MzsXmE1BMJnzLx_sBFd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/900-git-sync-sdk/src/main/java/io/harness/gitsync/fullsync/FullSyncSdkServiceImpl.java#L57)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can use shorthand notation here : emptyIfNull()
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java, line 129 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU7CoP7nioEDj28INB:-MzsXrKwCb8btalAAdFG:b-5dfryo) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java#L129)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

how provider and named annotation are helping here?
</blockquote></details>

removed it
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java, line 130 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzQ-IzsJgP1_pdBrIgh-r1-130:-MzsXpVV-I6ar5PhSgr_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java#L130)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

It would be better if we can do it already
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java, line 130 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU5yvJ2jQY-q5i5pIw:-MzsXq3L62fkHVIErUUV:b-5dfryo) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java#L130)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

Please add the comment, on why we are processing entities on this specific order?
</blockquote></details>

removed it


<!-- Sent from Reviewable.io -->

2022-04-05 15:15 UTC, DeepakPatankar reviewed
> Reviewed 1 of 14 files at r2, 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 2 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-05 20:26 UTC, mohitg0795 commented
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 12 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvP7nHDAzzgxpl_lK-:-MzvP7nI92i5qQ8tzSAn:b-41keyy) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L12)):*
> ```Java
> import java.util.List;
> 
> public class PMSGitEntityOrderComparator implements GitSyncEntityOrderComparatorInMsvc {
> ```

owner details missing


<!-- Sent from Reviewable.io -->

2022-04-05 20:27 UTC, mohitg0795 commented
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvPHVC9zMBbSjXkYdK:-MzvPHVC9zMBbSjXkYdL:b-p2zujt) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L13)):*
> ```Java
> 
> public class PMSGitEntityOrderComparator implements GitSyncEntityOrderComparatorInMsvc {
>   public static final List<EntityType> sortOrder = Lists.newArrayList(EntityType.PIPELINES, EntityType.INPUT_SETS);
> ```

There was some ordering within input sets as well, right?


<!-- Sent from Reviewable.io -->

2022-04-05 20:38 UTC, mohitg0795 commented
*[840-template-service/src/main/java/io/harness/TemplateGitEntityOrderComparator.java, line 12 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvRr-u2zL6qFSJG2Mw:-MzvRr-vCagnt3PjrHqv:bnas73k) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/840-template-service/src/main/java/io/harness/TemplateGitEntityOrderComparator.java#L12)):*
> ```Java
> import java.util.List;
> 
> public class TemplateGitEntityOrderComparator implements GitSyncEntityOrderComparatorInMsvc {
> ```

owner details


<!-- Sent from Reviewable.io -->

2022-04-05 20:44 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-MzvSmte92UF5QAtuBuV:b-r2lo93) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

No, it won't, we will process other entities, if some middle entity has error
</blockquote></details>

Sorry but I forgot the reason. Just want to recheck. Pipelines are fullsynced before input sets. If a pipeline sync fails:
1) Does its coupled input sets sync pass?
2) If input sets sync pass, then in next retry there's no blocker on pipeline sync due to it?


<!-- Sent from Reviewable.io -->

2022-04-06 06:53 UTC, abhinav-harness approved these changes
> Reviewed 1 of 3 files at r1, 1 of 14 files at r2, 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 1 change requests. 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-06 10:12 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 5 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-MzyE-XC2g_ea6ywQ0hr:b-b7xik8) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Sorry but I forgot the reason. Just want to recheck. Pipelines are fullsynced before input sets. If a pipeline sync fails:
1) Does its coupled input sets sync pass?
2) If input sets sync pass, then in next retry there's no blocker on pipeline sync due to it?
</blockquote></details>

I will check this case
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 86 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzVBquFBbCS70HYWqdm:-MzyDueOBymT8o7Vlm3S:bz61o5x) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L86)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

+1
</blockquote></details>

removed it and also added UT to check null list case
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 104 at r2](https://reviewable.io/reviews/harness/harness-core/31885#-MzWntYk46JhAXPVBPla:-MzyE2nS-GgBdTtLgw8U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a2fbaeba8374fa645cce3d35cf789c20fdee49f3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L104)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets put a success log over here.
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 12 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvP7nHDAzzgxpl_lK-:-MzyE40V2li7j9duPQTK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L12)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

owner details missing
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvPHVC9zMBbSjXkYdK:-MzyE4nH5AhTLo-7WZen:bteqk8w) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L13)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

There was some ordering within input sets as well, right?
</blockquote></details>

Ya, rn no customer is using overlay, they will add that condition in it whenever they re.
___
*[840-template-service/src/main/java/io/harness/TemplateGitEntityOrderComparator.java, line 12 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvRr-u2zL6qFSJG2Mw:-MzyM1qD0zWmA3f2olmN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/840-template-service/src/main/java/io/harness/TemplateGitEntityOrderComparator.java#L12)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

owner details
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-06 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31885) it.</sub>

2022-04-06 10:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31885) it.</sub>

2022-04-06 13:21 UTC, mohitg0795 commented
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvPHVC9zMBbSjXkYdK:-Mzz16Zi6JW1kmUPJDbt:bx5yqno) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L13)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Ya, rn no customer is using overlay, they will add that condition in it whenever they re.
</blockquote></details>

Umm I think if we know the ordering, lets get it reviewed and added right away. We don't know when a customers starts using it and then how to track that it needs to be integrated here.


<!-- Sent from Reviewable.io -->

2022-04-06 13:21 UTC, mohitg0795 commented
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvPHVC9zMBbSjXkYdK:-Mzz1L7GBv4yAxvcATwg:bejo8j1) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L13)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Umm I think if we know the ordering, lets get it reviewed and added right away. We don't know when a customers starts using it and then how to track that it needs to be integrated here.
</blockquote></details>

Or get ack from pipeline team on a common channel regarding this, otherwise it will be another headache for us at later point of time.


<!-- Sent from Reviewable.io -->

2022-04-06 13:23 UTC, mohitg0795 reviewed
> Reviewed 1 of 3 files at r1, 1 of 14 files at r2, 24 of 24 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-06 13:50 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-Mzz7jNqAczgCdWpySvB:bcxjaa7) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I will check this case
</blockquote></details>

So, inputset are synced and pipeline is not synved, now, we can update the input set,but as pipeline is not synced, it cannot use that inputset.
now, after resync, all the methods work fine.
___
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvPHVC9zMBbSjXkYdK:-Mzz7VB68CA6Ja2edNXX:bdmc0sf) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L13)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Or get ack from pipeline team on a common channel regarding this, otherwise it will be another headache for us at later point of time.
</blockquote></details>

But it will be a big chabnge to write methods in there service level, I will talk to Naman tommorrow and post pon channel.


<!-- Sent from Reviewable.io -->

2022-04-07 05:57 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 1 of 14 files at r2, 11 of 24 files at r3, 6 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885#-:-N-1aJmF6jDjxpOloj9C:bnfp4nl)* status: 8 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 06:42 UTC, mohitg0795 commented
*[800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java, line 13 at r3](https://reviewable.io/reviews/harness/harness-core/31885#-MzvPHVC9zMBbSjXkYdK:-N-1kFPjCZ8i3NgvZAOK:b8gvj3i) ([raw file](https://github.com/harness/harness-core/blob/66167fece2d3943891bc3288d5e357a474c3490d/800-pipeline-service/src/main/java/io/harness/PMSGitEntityOrderComparator.java#L13)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

But it will be a big chabnge to write methods in there service level, I will talk to Naman tommorrow and post pon channel.
</blockquote></details>

I am resolving this comment for now. But please get this discussion on some open channel, so thats its there for future reference. Only issue that I see is any day if a customer starts using different types of input sets, then this might break our full sync flow and then bugs will start coming unnecessarily. 
I just want we are clear on the ownership of it. If its pipeline team that should be reporting us about it, then lets take an ack from them.


<!-- Sent from Reviewable.io -->

2022-04-07 06:42 UTC, mohitg0795 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885#-:-N-1kcT12u8K8Fupbhsp:bnfp4nl)* status: 8 file(s) to review. 1 change requests. 6. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-07 09:50 UTC, goelsatyam2 requested changes
> Reviewed 1 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 13 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/fullsync/FullSyncSdkServiceImpl.java, line 78 at r4](https://reviewable.io/reviews/harness/harness-core/31885#-N-2OfYP4o3RKgAQjDAM:-N-2OfYP4o3RKgAQjDAN:bpvtr4t) ([raw file](https://github.com/harness/harness-core/blob/a7db879e3e0b52f682207ab11adfecb74879a066/900-git-sync-sdk/src/main/java/io/harness/gitsync/fullsync/FullSyncSdkServiceImpl.java#L78)):*
> ```Java
>   }
> 
>   private void sortFileChanges(List<FileChange> fileChanges) {
> ```

we can add comments on why we need to sort file changes
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/GitSyncEntityOrderComparatorInMsvc.java, line 11 at r4](https://reviewable.io/reviews/harness/harness-core/31885#-N-2OLgg75xIwxprYixF:-N-2OLgg75xIwxprYixG:b-vlp6m6) ([raw file](https://github.com/harness/harness-core/blob/a7db879e3e0b52f682207ab11adfecb74879a066/953-git-sync-commons/src/main/java/io/harness/gitsync/common/GitSyncEntityOrderComparatorInMsvc.java#L11)):*
> ```Java
> 
> @OwnedBy(PL)
> public interface GitSyncEntityOrderComparatorInMsvc {
> ```

Do we need to have an extra interface for the comparator, does java has a predefined comparator that we can use here?


<!-- Sent from Reviewable.io -->

2022-04-07 09:53 UTC, DeepakPatankar reviewed
> Reviewed 4 of 14 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 13 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 09:54 UTC, DeepakPatankar submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 10:12 UTC, goelsatyam2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-N-2VHAQ9aOjsHfyw_VI:btw3ees) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

So, inputset are synced and pipeline is not synved, now, we can update the input set,but as pipeline is not synced, it cannot use that inputset.
now, after resync, all the methods work fine.
</blockquote></details>

I didn't get why we are processing other files if there is failure, better we add commend for this logic.


<!-- Sent from Reviewable.io -->

2022-04-07 10:16 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 120 at r1](https://reviewable.io/reviews/harness/harness-core/31885#-MzU8SgU2ttihhaAhI3T:-N-2W5yi0WsgL09e2m2v:bfq4p4q) ([raw file](https://github.com/harness/harness-core/blob/2590fbc9edd63d56d38fee664666a5e9d430b178/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L120)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

I didn't get why we are processing other files if there is failure, better we add commend for this logic.
</blockquote></details>

Suppose there are 100 pipelins and 100 input set, now suppose first pipeline failed, so, we should allow another 99 pipwlines and input sets to sync, what's the point of not processing now and the processing them again. 


<!-- Sent from Reviewable.io -->

2022-04-07 10:35 UTC, goelsatyam2 approved these changes
> Reviewed 1 of 3 files at r1, 7 of 24 files at r3, 3 of 14 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 9 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 10:36 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 8 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-07 10:53 UTC, DeepakPatankar approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 8 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:17 UTC, DeepakPatankar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885#-:-N-2ja7mEKMxC3wfsPnr:bnfp4nl)* status: 8 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:36 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885#-:-N-2npwGE2nTVbeLv638:bnfp4nl)* status: 7 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:52 UTC, abhinav-harness approved these changes
> Reviewed 3 of 14 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: 7 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-07 11:53 UTC, abhinav-harness approved these changes
> Reviewed 7 of 14 files at r4, 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31885)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-07 11:59 UTC, merged