[feat]: [PL-24242]: Add more logs when we are processing a webhook event
harness/harness-core pull request #31908
Opened 2022-03-31 06:03 UTC by DeepakPatankar

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-03-31 06:12 UTC, DeepakPatankar commented
trigger messagecheck

2022-03-31 06:14 UTC, abhinav-harness commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java
>          WebhookDTO webhookDTO = WebhookDTO.parseFrom(message.getMessage().getData());
@DeepakPatankar can we put webhookevent id as well in log context is possible?

2022-03-31 06:28 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java
>          WebhookDTO webhookDTO = WebhookDTO.parseFrom(message.getMessage().getData());
done

2022-03-31 07:12 UTC, mohitg0795 commented
*[953-events-api/src/main/java/io/harness/eventsframework/NgEventLogContext.java, line 17 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTo1_R9lvCP1ddLcwJ:-MzTo1_S4mZJrDSngh7G:b-lmv951) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/953-events-api/src/main/java/io/harness/eventsframework/NgEventLogContext.java#L17)):*
> ```Java
> public class NgEventLogContext extends AutoLogContext {
>   private static String MESSAGE_ID = "messageId";
>   private static String EVENT_ID = "eventId";
> ```

I'm wondering if its messing the current NgEventLogContext. Its made with a purpose to track our "events framework" events and thus it has only "message-id" as field. 
Now if we add eventId as well, it unnecessarily pollutes it. Can we make a new logContext for our use-case?


<!-- Sent from Reviewable.io -->

2022-03-31 07:13 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 48 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTo_bWCUNCeSDQ7ATD:-MzTo_bWCUNCeSDQ7ATE:b-ysumge) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L48)):*
> ```Java
>       }
>     } else {
>       log.error("The message for processing a webhook event was null {}", message);
> ```

if the message is null then why are we logging the message here?


<!-- Sent from Reviewable.io -->

2022-03-31 07:14 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 43 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTon6HE2FNXbT-UK7O:-MzTon6HE2FNXbT-UK7P:b-8kwbrb) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L43)):*
> ```Java
>         }
>       } catch (InvalidProtocolBufferException e) {
>         throw new InvalidRequestException(
> ```

will this exception be logged somewhere on upper layer? If not, then lets log it here.


<!-- Sent from Reviewable.io -->

2022-03-31 08:31 UTC, goelsatyam2 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java
> +        try (AutoLogContext ignore1 = new NgEventLogContext(message.getId(), webhookDTO.getEventId(), OVERRIDE_ERROR)) {
there is a try/catch inside a try, we can write a separate function for the nested try/catch to make the code cleaner.

2022-03-31 08:31 UTC, goelsatyam2 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java
> +      log.error("The message for processing a webhook event was null {}", message);
should we return false from here because?

2022-03-31 08:45 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java
> +        try (AutoLogContext ignore1 = new NgEventLogContext(message.getId(), webhookDTO.getEventId(), OVERRIDE_ERROR)) {
done

2022-03-31 08:45 UTC, DeepakPatankar commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java
> +      log.error("The message for processing a webhook event was null {}", message);
In that case we don't want to re process the error, hence false is not required

2022-03-31 08:47 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 4 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 43 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTon6HE2FNXbT-UK7O:-MzU8uKvDcY79PW1dr9Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

will this exception be logged somewhere on upper layer? If not, then lets log it here.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 48 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTo_bWCUNCeSDQ7ATD:-MzU8v3u2VayCpUKGy4A:bb2zig7) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if the message is null then why are we logging the message here?
</blockquote></details>

Fixed the message
___
*[953-events-api/src/main/java/io/harness/eventsframework/NgEventLogContext.java, line 17 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTo1_R9lvCP1ddLcwJ:-MzU8xDdCg-CrYyJmc-l:b-pilzns) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/953-events-api/src/main/java/io/harness/eventsframework/NgEventLogContext.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I'm wondering if its messing the current NgEventLogContext. Its made with a purpose to track our "events framework" events and thus it has only "message-id" as field. 
Now if we add eventId as well, it unnecessarily pollutes it. Can we make a new logContext for our use-case?
</blockquote></details>

Reverted the changes and created a separate context.


<!-- Sent from Reviewable.io -->

2022-03-31 10:22 UTC, DeepakPatankar commented
trigger license/cla

2022-03-31 10:44 UTC, abhinav-harness reviewed
> Reviewed 1 of 2 files at r1, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 4 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-31 12:31 UTC, abhinav-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 4 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-03-31 12:34 UTC, goelsatyam2 approved these changes
> Reviewed 1 of 2 files at r1, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-03-31 13:10 UTC, mohitg0795 commented
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 43 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTon6HE2FNXbT-UK7O:-MzV5G8KEz-JhWSFtIoA:b-t8f6dz) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L43)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We should log exception as well. Missed exception here.


<!-- Sent from Reviewable.io -->

2022-03-31 13:13 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 1 change requests. 2. unresolved discussions. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 30 at r5](https://reviewable.io/reviews/harness/harness-core/31908#-MzV5yPe7xvBzoZMheZW:-MzV5yPe7xvBzoZMheZX:b2ywyfz) ([raw file](https://github.com/harness/harness-core/blob/32043c8f4b53c48409ac3a2b701504c511c01be6/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L30)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.DX)
> public class GitPushEventStreamListener implements MessageListener {
> ```

Lets do same changes in the other stream listener as well. We have only 2 stream listeners and then it will remain consistent in terms of logging.


<!-- Sent from Reviewable.io -->

2022-03-31 13:33 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 4 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 43 at r3](https://reviewable.io/reviews/harness/harness-core/31908#-MzTon6HE2FNXbT-UK7O:-MzVAVEN2Ipu9eC6lEvu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/174563698360663dd7c4e3bd62f9e9b329c004e3/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should log exception as well. Missed exception here.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 30 at r5](https://reviewable.io/reviews/harness/harness-core/31908#-MzV5yPe7xvBzoZMheZW:-MzVA76B5s-669BXcTv7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32043c8f4b53c48409ac3a2b701504c511c01be6/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets do same changes in the other stream listener as well. We have only 2 stream listeners and then it will remain consistent in terms of logging.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java, line 36 at r5](https://reviewable.io/reviews/harness/harness-core/31908#-MzV5opQ0bZWDJcMjils:-MzVA61f9nicsHaWMruu:b6ar8zw) ([raw file](https://github.com/harness/harness-core/blob/32043c8f4b53c48409ac3a2b701504c511c01be6/136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent/GitPushEventStreamListener.java#L36)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Shouldn't we be passing the webhook event id in log context here? We are passing the message id 
</blockquote></details>

Fixed this log context, another type of log context was rquired here
___
*[980-commons/src/main/java/io/harness/logging/WebhookEventAutoLogContext.java, line 11 at r5](https://reviewable.io/reviews/harness/harness-core/31908#-MzV5Urh4i32TvygU_L4:-MzVAWJmApwX8cgTyNrY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32043c8f4b53c48409ac3a2b701504c511c01be6/980-commons/src/main/java/io/harness/logging/WebhookEventAutoLogContext.java#L11)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we make it clearer : "webhookEventId" ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-04 06:41 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 3 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908#-:-MznIj0PDV2N8h10wPPU:bnfp4nl)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-04 06:43 UTC, mohitg0795 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-04 06:43 UTC, mohitg0795 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-04 06:44 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908#-:-MznJCFY6CSOMYIKdmpf:bnfp4nl)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-04 06:47 UTC, rathodmeetsatish approved these changes
> Reviewed 1 of 2 files at r1, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-04 06:53 UTC, goelsatyam2 approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31908)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-04 07:05 UTC, merged