[fix]: [DEL-3648]: Move to name based kryo serializer for delegate/manager communication
harness/harness-core pull request #31942
Opened 2022-03-31 20:24 UTC by raghuAtWings

2022-04-01 20:24 UTC, puneetsar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31942)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/test/java/io/harness/delegate/KryoEnumSerializationTest.java, line 75 at r1](https://reviewable.io/reviews/harness/harness-core/31942#-MzamILF9wJ8CJY2KNhK:-MzamILF9wJ8CJY2KNhL:b-o3zmqw) ([raw file](https://github.com/harness/harness-core/blob/3cca7f2d865f7875762eee0534b3500a5b7804fe/400-rest/src/test/java/io/harness/delegate/KryoEnumSerializationTest.java#L75)):*
> ```Java
> 
>     byte[] serializedBytes = toBytes(kryo, connectorInfoDTO);
>     kryo = new HKryo(new ClassResolver());
> ```

Since you are instantiating HKryo, wont it by default use OrdinalBackwardEnumNameSerializer? I understand you want to deserialize with default serializer.



_Code quote:_
```Java
new HKryo(new ClassResolver())
```
___
*[980-commons/src/main/java/io/harness/serializer/OrdinalBackwardEnumNameSerializer.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/31942#-MzanBwF68UWRtvHEOk1:-MzanBwF68UWRtvHEOk2:bjbcm9m) ([raw file](https://github.com/harness/harness-core/blob/3cca7f2d865f7875762eee0534b3500a5b7804fe/980-commons/src/main/java/io/harness/serializer/OrdinalBackwardEnumNameSerializer.java#L31)):*
> ```Java
>       return;
>     }
>     output.writeVarInt(object.ordinal() + 1, true);
> ```

I understood we are going to write using name in this. Also second unit test also mentions the same?



_Code quote:_
```Java
output.writeVarInt(object.ordinal() + 1, true);
```


<!-- Sent from Reviewable.io -->

2022-04-06 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31942) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31942) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31942) it.</sub>

2022-04-06 10:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31942) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31942) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31942) it.</sub>

2022-08-01 20:17 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 2 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 2 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/31942)

2022-08-11 19:37 UTC, closed without merging