Test cases
harness/harness-core pull request #31955
Opened 2022-04-01 07:53 UTC by piyush-bhuwalka

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-04-01 07:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=31955) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=31955) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=31955) it.</sub>

2022-04-04 04:54 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/test/java/io/harness/cdng/infra/InfrastructureMapperTest.java
> +import static io.harness.rule.OwnerRule.*;
Fixed

2022-04-05 06:27 UTC, sainath-b approved these changes

2022-04-05 10:32 UTC, PragyeshMishra01 requested changes
> Reviewed 2 of 8 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31955)* status: 1 change requests. 1. unresolved discussions. 

___
*[125-cd-nextgen/src/test/java/io/harness/cdng/serverless/AbstractServerlessStepExecutorTestBase.java, line 80 at r2](https://reviewable.io/reviews/harness/harness-core/31955#-MztCuzc9gYTchFXmEOE:-MztCuzc9gYTchFXmEOF:bijhut3) ([raw file](https://github.com/harness/harness-core/blob/556984c2c936def1e36d1bde21379fc5ff7521fb/125-cd-nextgen/src/test/java/io/harness/cdng/serverless/AbstractServerlessStepExecutorTestBase.java#L80)):*
> ```Java
> 
>         doReturn(serverlessInfraConfig).when(serverlessStepHelper).getServerlessInfraConfig(infrastructureOutcome, ambiance);
>         doReturn(releaseName).when(serverlessStepHelper).getReleaseName(ambiance, infrastructureOutcome);
> ```

@piyush-bhuwalka you can remove release name from this test, we are not using it in serverless.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaDeployStepTest.java, line 62 at r2](https://reviewable.io/reviews/harness/harness-core/31955#-MztDVA_2OlbYvLAbN1z:-MztDVA_2OlbYvLAbN2-:bjlpllt) ([raw file](https://github.com/harness/harness-core/blob/556984c2c936def1e36d1bde21379fc5ff7521fb/125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaDeployStepTest.java#L62)):*
> ```Java
>     @Test
>     @Owner(developers = ABOSII)
>     @Category(UnitTests.class)
> ```

you can change the owner of this test
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaDeployStepTest.java, line 97 at r2](https://reviewable.io/reviews/harness/harness-core/31955#-MztEHvSDpiBwgkfJlJq:-MztEHvSDpiBwgkfJlJr:bwp4r3f) ([raw file](https://github.com/harness/harness-core/blob/556984c2c936def1e36d1bde21379fc5ff7521fb/125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaDeployStepTest.java#L97)):*
> ```Java
>                 .unitProgressData(UnitProgressData.builder().unitProgresses(Arrays.asList()).build())
>                 .commandExecutionStatus(SUCCESS)
>                 .build();
> ```

 you can add function instance also in serverlessDeployResponse object
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaDeployStepTest.java, line 237 at r2](https://reviewable.io/reviews/harness/harness-core/31955#-MztEe5x11ynun4OJSpn:-MztEe5x11ynun4OJSpo:budozb8) ([raw file](https://github.com/harness/harness-core/blob/556984c2c936def1e36d1bde21379fc5ff7521fb/125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaDeployStepTest.java#L237)):*
> ```Java
>     @Test
>     @Owner(developers = ABOSII)
>     @Category(UnitTests.class)
> ```

correct Test Owner, pls once check other places too.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaStepHelperTest.java, line 106 at r2](https://reviewable.io/reviews/harness/harness-core/31955#-MztFAjqDna33mxSNja9:-MztFAjqDna33mxSNjaA:bbykga4) ([raw file](https://github.com/harness/harness-core/blob/556984c2c936def1e36d1bde21379fc5ff7521fb/125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaStepHelperTest.java#L106)):*
> ```Java
>     @Spy
>     @InjectMocks
>     private K8sEntityHelper k8sEntityHelper;
> ```

Pls remove K8s specific class objects, we should not use it in serverless tests.
Check other places too.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessStepCommonHelperTest.java, line 108 at r2](https://reviewable.io/reviews/harness/harness-core/31955#-MztFhVLDoKU6AZzC9-y:-MztFhVM49lfdh40jzOv:b-ee92o8) ([raw file](https://github.com/harness/harness-core/blob/556984c2c936def1e36d1bde21379fc5ff7521fb/125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessStepCommonHelperTest.java#L108)):*
> ```Java
>   @Mock CDStepHelper cdStepHelper;
>   @Mock StepHelper stepHelper;
>   @Mock ServerlessStepHelper serverlessStepHelper;
> ```

private access modifier, pls check other places too.


<!-- Sent from Reviewable.io -->

2022-04-06 05:58 UTC, PragyeshMishra01 approved these changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31955)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-06 08:34 UTC, merged