[CDS-35042]: made jira timeout changes
harness/harness-core pull request #32079
Opened 2022-04-06 07:00 UTC by prabu-kr

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-04-06 08:00 UTC, poojaSinghal requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32079)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/resources/JiraSettingResource.java, line 92 at r1](https://reviewable.io/reviews/harness/harness-core/32079#-Mzxsiql10cmCHg5FUNC:-Mzxsiql10cmCHg5FUND:b-qwbiob) ([raw file](https://github.com/harness/harness-core/blob/0030c381ebff4a9387582423fbbdacb78d7c79d2/400-rest/src/main/java/software/wings/resources/JiraSettingResource.java#L92)):*
> ```Java
>       @QueryParam("accountId") @NotEmpty String accountId, @PathParam("connectorId") String connectorId,
>       @QueryParam("expand") String expand, @QueryParam("project") String project) {
>     return new RestResponse<>(jiraHelperService.getCreateMetadata(connectorId, expand, project, accountId, appId, 0));
> ```

we should not pass 0 as timeoutMillis 
Please pass default_delegate_task_timeout
___
*[400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java, line 192 at r1](https://reviewable.io/reviews/harness/harness-core/32079#-MzxsbtqBrAG3cwpidt4:-MzxsbtqBrAG3cwpidt5:b-qwbiob) ([raw file](https://github.com/harness/harness-core/blob/0030c381ebff4a9387582423fbbdacb78d7c79d2/400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java#L192)):*
> ```Java
>                                                 .issueId(jiraApprovalParams.getIssueId())
>                                                 .build();
>     return runTask(accountId, appId, jiraApprovalParams.getJiraConnectorId(), jiraTaskParameters, 0);
> ```

we should not pass 0 as timeoutMillis 
Please pass default_delegate_task_timeout
___
*[400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java, line 294 at r1](https://reviewable.io/reviews/harness/harness-core/32079#-MzxslV36CmKI_nhgcpb:-MzxslV36CmKI_nhgcpc:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/0030c381ebff4a9387582423fbbdacb78d7c79d2/400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java#L294)):*
> ```Java
>                                                 .rejectionValue(rejectionValue)
>                                                 .build();
>     JiraExecutionData jiraExecutionData = runTask(accountId, appId, connectorId, jiraTaskParameters, 0);
> ```

same


<!-- Sent from Reviewable.io -->

2022-04-06 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=32079) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=32079) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=32079) it.</sub>

2022-04-11 05:47 UTC, prabu-kr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32079)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/resources/JiraSettingResource.java, line 92 at r1](https://reviewable.io/reviews/harness/harness-core/32079#-Mzxsiql10cmCHg5FUNC:-N-M9JMW32PYENHIm3n1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0030c381ebff4a9387582423fbbdacb78d7c79d2/400-rest/src/main/java/software/wings/resources/JiraSettingResource.java#L92)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

we should not pass 0 as timeoutMillis 
Please pass default_delegate_task_timeout
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java, line 192 at r1](https://reviewable.io/reviews/harness/harness-core/32079#-MzxsbtqBrAG3cwpidt4:-N-M9K5QAibYbPqRGAwC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0030c381ebff4a9387582423fbbdacb78d7c79d2/400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java#L192)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

we should not pass 0 as timeoutMillis 
Please pass default_delegate_task_timeout
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java, line 294 at r1](https://reviewable.io/reviews/harness/harness-core/32079#-MzxslV36CmKI_nhgcpb:-N-M9Kri-ixv-xhdeDmF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0030c381ebff4a9387582423fbbdacb78d7c79d2/400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java#L294)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-13 05:33 UTC, poojaSinghal approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32079)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-13 05:40 UTC, merged