feat: [PIE-3422]: added api pattern to api telemetry
harness/harness-core pull request #32137
Opened 2022-04-07 10:06 UTC by vaibhav-si

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/32137)

2022-04-07 12:10 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32137)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-07 13:57 UTC, rijajoo requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32137)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[950-telemetry/src/main/java/io/harness/telemetry/utils/TelemetryDataUtils.java, line 87 at r1](https://reviewable.io/reviews/harness/harness-core/32137#-N-3JBz3-0mFSUOVd1H8:-N-3JBz3-0mFSUOVd1H9:bqoh1m1) ([raw file](https://github.com/harness/harness-core/blob/a5b82ab5ff133352881fda5fe85dbed67884a247/950-telemetry/src/main/java/io/harness/telemetry/utils/TelemetryDataUtils.java#L87)):*
> ```Java
>     StringBuilder pattern = new StringBuilder("");
>     for (int i = 0; i < templates.size(); i++) {
>       pattern.append(templates.get(templates.size() - 1 - i).getTemplate());
> ```

Why do we reverse the matched templates?


<!-- Sent from Reviewable.io -->

2022-04-07 16:50 UTC, brijeshdhakar commented
*[950-telemetry/src/main/java/io/harness/telemetry/utils/TelemetryDataUtils.java, line 87 at r1](https://reviewable.io/reviews/harness/harness-core/32137#-N-3JBz3-0mFSUOVd1H8:-N-3vJRu7ro_PbYvLWjN:b-7kdbd6) ([raw file](https://github.com/harness/harness-core/blob/a5b82ab5ff133352881fda5fe85dbed67884a247/950-telemetry/src/main/java/io/harness/telemetry/utils/TelemetryDataUtils.java#L87)):*
<details><summary><i>Previously, rijajoo (Richa Jajoo) wrote…</i></summary><blockquote>

Why do we reverse the matched templates?
</blockquote></details>

This list is in order of matched method level template and then class level template. So to create the complete matched API we need to reverse the order.
I tested this in API Errors telemetry event and it works correctly this way.


<!-- Sent from Reviewable.io -->

2022-04-11 06:31 UTC, rijajoo submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32137#-:-N-MJRVb5X1zLmXxriA4:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-04-11 06:33 UTC, vaibhav-si commented
/rebase

2022-04-11 08:29 UTC, rijajoo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32137#-:-N-MjUnVBYTQMmkllGer:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-11 09:57 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32137)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-11 11:30 UTC, merged

2022-04-12 06:29 UTC, vaibhav-si commented on 950-telemetry/src/main/java/io/harness/telemetry/utils/TelemetryDataUtils.java
> +    for (int i = 0; i < templates.size(); i++) {
I checked the library code and it never returns null.

2022-04-12 06:29 UTC, vaibhav-si commented on 950-telemetry/src/main/java/io/harness/telemetry/utils/TelemetryDataUtils.java
> +      pattern.append(templates.get(templates.size() - 1 - i).getTemplate());
yes, its documented. I showed to Richa the same yesterday