[PL-23082]: Added telemetry call for connection test
harness/harness-core pull request #32191
Opened 2022-04-12 06:11 UTC by tiwaritejas

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-04-12 06:16 UTC, tiwaritejas commented
trigger messagecheck

2022-04-12 06:20 UTC, tiwaritejas commented
trigger messagecheck

2022-04-12 06:27 UTC, tiwaritejas commented
trigger messagecheck

2022-04-12 09:32 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
>        if (connectorDTO.isPresent()) {
It is not required. To handle null values, Optional is used, and before the connectorDTO.get() call, isPresent() is checked.

2022-04-12 11:40 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
>        if (connectorDTO.isPresent()) {
Can  `get(accountIdentifier, orgIdentifier, projectIdentifier, connectorIdentifier)` return null ever instead of Optional? If no then it is fine. Else we will need the check

2022-04-12 11:57 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
>        if (connectorDTO.isPresent()) {
It will always be an Optional, checked all the cases by inspecting the get() method. This should be fine.

2022-04-12 13:05 UTC, meenakshi-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191#-:-N-SsCaE7S-pm_gvDDKM:bnfp4nl)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-13 05:38 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java, line 117 at r3](https://reviewable.io/reviews/harness/harness-core/32191#-N-WPZtI0mwmgNfba_he:-N-WPZtI0mwmgNfba_hf:be1x76x) ([raw file](https://github.com/harness/harness-core/blob/d816d7ce15b83d6d5493a6e305ea042f554c8cf9/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L117)):*
> ```Java
>       String eventMessage;
>       if (EmptyPredicate.isNotEmpty(accountId) || !accountId.equals(GLOBAL_ACCOUNT_ID)) {
>         HashMap<String, Object> map = new HashMap<>();
> ```

Keep meaningful variable name.
___
*[120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java, line 136 at r3](https://reviewable.io/reviews/harness/harness-core/32191#-N-WQ3yR29kmHiHlmEGb:-N-WQ3yR29kmHiHlmEGc:b36u3e7) ([raw file](https://github.com/harness/harness-core/blob/d816d7ce15b83d6d5493a6e305ea042f554c8cf9/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L136)):*
> ```Java
>         map.put(CONNECTIVITY_STATUS, connectorValidationResult.getStatus());
>         if (connectorValidationResult.getStatus() == ConnectivityStatus.SUCCESS) {
>           eventMessage = "test_connection_success";
> ```

Define constants for message.
___
*[120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java, line 140 at r3](https://reviewable.io/reviews/harness/harness-core/32191#-N-WPgDN1BJ6bohaSKbv:-N-WPgDN1BJ6bohaSKbw:bb302nl) ([raw file](https://github.com/harness/harness-core/blob/d816d7ce15b83d6d5493a6e305ea042f554c8cf9/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L140)):*
> ```Java
>           eventMessage = "test_connection_failure";
>           map.put(ERROR_SUMMARY, connectorValidationResult.getErrorSummary());
>           map.put(ERROR_DETAILS, connectorValidationResult.getErrors());
> ```

Extract map creation as a separate method.
UT for map creation logic is missing.


<!-- Sent from Reviewable.io -->

2022-04-13 11:48 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java, line 153 at r2](https://reviewable.io/reviews/harness/harness-core/32191#-N-ROWQzU8Z5y_glX4UX-r2-153:-N-XkEU_7ibESxhKfiZQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5fc7945476a554fa368fffff74f129528551430d/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L153)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

change log message
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java, line 117 at r3](https://reviewable.io/reviews/harness/harness-core/32191#-N-WPZtI0mwmgNfba_he:-N-XkHghCNO9YAvdr7cl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d816d7ce15b83d6d5493a6e305ea042f554c8cf9/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L117)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Keep meaningful variable name.
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java, line 136 at r3](https://reviewable.io/reviews/harness/harness-core/32191#-N-WQ3yR29kmHiHlmEGb:-N-XkGuJ3QUwWxUrx6DW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d816d7ce15b83d6d5493a6e305ea042f554c8cf9/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L136)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Define constants for message.
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java, line 140 at r3](https://reviewable.io/reviews/harness/harness-core/32191#-N-WPgDN1BJ6bohaSKbv:-N-XjHDAE5bPE0z-54ao:by6xwk6) ([raw file](https://github.com/harness/harness-core/blob/d816d7ce15b83d6d5493a6e305ea042f554c8cf9/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L140)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Extract map creation as a separate method.
UT for map creation logic is missing.
</blockquote></details>

The fields as well as conditions for map creation are different for each telemetry call. Hence, abstracting it out will not reduce any redundancy or make the modular. Right now, each method corresponds to a telemetry call, and the map for that call is constructed in that method itself because the same map can't be used for other telemetry call.


<!-- Sent from Reviewable.io -->

2022-04-25 10:22 UTC, meenakshi-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-25 11:06 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java` line 140 at r3](https://reviewable.io/reviews/harness/harness-core/32191#-N-WPgDN1BJ6bohaSKbv:-N0VGA-j-zelOvPAbhpH:baikojw) ([raw file](https://github.com/harness/harness-core/blob/d816d7ce15b83d6d5493a6e305ea042f554c8cf9/120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java#L140)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

The fields as well as conditions for map creation are different for each telemetry call. Hence, abstracting it out will not reduce any redundancy or make the modular. Right now, each method corresponds to a telemetry call, and the map for that call is constructed in that method itself because the same map can't be used for other telemetry call.
</blockquote></details>

sendTestConnectionEvent method have two responsibilities. One to create a map which can hold different info in different condition and other to send info. Each responsibility can be unit tested by their own test. 



_Code quote:_
```Java
sendTestConnectionEvent
```


<!-- Sent from Reviewable.io -->

2022-04-26 11:19 UTC, nishantsaini20 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-26 11:21 UTC, meenakshi-harness approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-26 11:23 UTC, tiwaritejas reviewed
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-26 11:46 UTC, naman-goenka submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-26 11:51 UTC, tiwaritejas reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191#-:-N0_hVJEAq0roF3226so:bnfp4nl)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-26 11:51 UTC, tiwaritejas reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191#-:-N0_hZ6z3q6ZtQTWbDd4:bnfp4nl)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-26 11:52 UTC, tiwaritejas reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191#-:-N0_heB637txBaLLGfSe:bnfp4nl)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-27 04:42 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-27 06:36 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-27 06:37 UTC, tiwaritejas reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-27 06:51 UTC, naman-goenka approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-27 07:22 UTC, tiwaritejas reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32191)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-04-28 13:18 UTC, merged