[feat]: [CDS-36228]: adding more unit-tests for NG cloudformation logic
harness/harness-core pull request #32253
Opened 2022-04-14 08:46 UTC by vlica-harness

[feat]: [CDS-36228]: adding more unit-tests for NG cloudformation logic

2022-04-14 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=32253) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=32253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=32253) it.</sub>

2022-04-14 13:42 UTC, tmacari-harness requested changes
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32253)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/S3FetchFilesTaskNGTest.java, line 59 at r2](https://reviewable.io/reviews/harness/harness-core/32253#-N-cICE71ebdA-Qjsirx:-N-cICE71ebdA-Qjsiry:bickfy5) ([raw file](https://github.com/harness/harness-core/blob/20557f6e20394eea490a4baf9e0e52177ef763b7/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/S3FetchFilesTaskNGTest.java#L59)):*
> ```Java
> import org.mockito.MockitoAnnotations;
> 
> @TargetModule(HarnessModule._930_DELEGATE_TASKS)
> ```

let's remove this as the class is already in 930_DELEGATE_TASKS.
add @OwnedBy(HarnessTeam.CDP).



_Code quote:_
```Java
@TargetModule(HarnessModule._930_DELEGATE_TASKS)
```
___
*[950-delegate-tasks-beans/src/test/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFilesTaskParamsTest.java, line 31 at r2](https://reviewable.io/reviews/harness/harness-core/32253#-N-cIknC5YSyrGe_J2_z:-N-cIknC5YSyrGe_J2a-:blkspht) ([raw file](https://github.com/harness/harness-core/blob/20557f6e20394eea490a4baf9e0e52177ef763b7/950-delegate-tasks-beans/src/test/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFilesTaskParamsTest.java#L31)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> @TargetModule(HarnessModule._950_DELEGATE_TASKS_BEANS)
> ```

let's remove @TargetModule
add @OwnedBy(HarnessTeam.CDP).


<!-- Sent from Reviewable.io -->

2022-04-15 09:49 UTC, vlica-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32253)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/S3FetchFilesTaskNGTest.java, line 59 at r2](https://reviewable.io/reviews/harness/harness-core/32253#-N-cICE71ebdA-Qjsirx:-N-gbkq5BnxF1tfnLKZ9:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/20557f6e20394eea490a4baf9e0e52177ef763b7/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/S3FetchFilesTaskNGTest.java#L59)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's remove this as the class is already in 930_DELEGATE_TASKS.
add @OwnedBy(HarnessTeam.CDP).
</blockquote></details>

Done
___
*[950-delegate-tasks-beans/src/test/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFilesTaskParamsTest.java, line 31 at r2](https://reviewable.io/reviews/harness/harness-core/32253#-N-cIknC5YSyrGe_J2_z:-N-gc8vY45okV5Nefqby:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/20557f6e20394eea490a4baf9e0e52177ef763b7/950-delegate-tasks-beans/src/test/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFilesTaskParamsTest.java#L31)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's remove @TargetModule
add @OwnedBy(HarnessTeam.CDP).
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-04-15 09:50 UTC, tmacari-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32253#-:-N-gcApp2PjZ0PiO9hJl:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-15 10:56 UTC, merged