[PL-24698]: Add a API to return the default branch along with branches list
harness/harness-core pull request #32383
Opened 2022-04-21 10:55 UTC by DeepakPatankar

Added a ListV2 API which returns the branch list and also the default branch of the repo

Testing Link: https://docs.google.com/spreadsheets/d/1NWs3XKpaEXvYUZ0E2aa2KJ4OCl-Uhx8Ue68l9WreNPE/edit#gid=0

2022-04-21 10:59 UTC, mohitg0795 commented
*[product/ci/scm/git/git.go, line 362 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0Ald1OECF1IpEQFkRe:-N0Ald1OECF1IpEQFkRf:b9hgp0) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L362)):*
> ```Go
>     }
> 
> 	log.Infow("ListBranchesV2 success", "slug", request.GetSlug(), "elapsed_time_ms", utils.TimeSince(start))
> ```

this should be the last log of this method


<!-- Sent from Reviewable.io -->

2022-04-21 11:00 UTC, mohitg0795 commented
*[product/ci/scm/git/git.go, line 378 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AlsBcDj5aft-KZ9Ut:-N0AlsBcDj5aft-KZ9Uu:bpmrnx4) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L378)):*
> ```Go
> 	out = &pb.ListBranchesV2Response{
> 		Branches: branches,
> 		DefaultBranch: userRepoResponse.GetRepo().GetBranch(),
> ```

what if there are no branches thus there's no default branch?


<!-- Sent from Reviewable.io -->

2022-04-21 11:02 UTC, mohitg0795 commented
*[product/ci/scm/proto/scm.proto, line 501 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AmGp1DPXiQPFGl0F1:-N0AmGp1DPXiQPFGl0F2:b-k5h2t) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L501)):*
> ```protobuf
> }
> 
> message ListBranchesV2Response {
> ```

lets order the fields in a logical manner. eg: main response fields should come first and then the supporting fields like pagination, error etc.


<!-- Sent from Reviewable.io -->

2022-04-25 07:18 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: Some of the checks are too old. 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/proto/scm.proto` line 490 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0U_DUO00xo-vMbmiBN:-N0U_DUO00xo-vMbmiBO:b9k8fo5) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L490)):*
> ```protobuf
> message ListBranchesV2Request {
>   string slug = 1;
>   PageRequest pagination = 2;
> ```

@mohitg0795 this API should list all the branches right? why are we making it paginated 


<!-- Sent from Reviewable.io -->

2022-04-25 07:29 UTC, mohitg0795 commented
*[`product/ci/scm/proto/scm.proto` line 490 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0U_DUO00xo-vMbmiBN:-N0Ub_TCAEKOb7xi3POl:b7ndy4n) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L490)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

@mohitg0795 this API should list all the branches right? why are we making it paginated 
</blockquote></details>

This is the default API. It has to be paginated. For complete list, we can expose another one that dedicatedly does loop for finding all branches.

And similar to repos use-case, it should also have a search term support and then paginated API should be good for us.


<!-- Sent from Reviewable.io -->

2022-04-25 09:31 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: Some of the checks are too old. 3 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/git/git.go` line 362 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0Ald1OECF1IpEQFkRe:-N0V1dXV0s0MZszk-lQG:b-y3rg0z) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L362)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be the last log of this method
</blockquote></details>

Moved this line to last line and added another log here
___
*[`product/ci/scm/git/git.go` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AlsBcDj5aft-KZ9Ut:-N0V1tNhAF3kEs_pvQBP:b-nfazao) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L378)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if there are no branches thus there's no default branch?
</blockquote></details>

I checked that the git providers are always returning a default branch even when there are no branches https://docs.google.com/spreadsheets/d/1NWs3XKpaEXvYUZ0E2aa2KJ4OCl-Uhx8Ue68l9WreNPE/edit#gid=0.

If some git provider doesn't provide the default branch, then we will return null from here.
___
*[`product/ci/scm/proto/scm.proto` line 490 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0U_DUO00xo-vMbmiBN:-N0V2At1C5Eh-8FRmpmJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L490)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is the default API. It has to be paginated. For complete list, we can expose another one that dedicatedly does loop for finding all branches.

And similar to repos use-case, it should also have a search term support and then paginated API should be good for us.
</blockquote></details>

Done.
___
*[`product/ci/scm/proto/scm.proto` line 501 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AmGp1DPXiQPFGl0F1:-N0V2qWwBzyAhrdfpxBx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L501)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets order the fields in a logical manner. eg: main response fields should come first and then the supporting fields like pagination, error etc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-25 10:22 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: 3 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/proto/scm.proto` line 490 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0U_DUO00xo-vMbmiBN:-N0VEPXh6UoXehCFRIe2:b1nzxvk) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L490)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This pageRequest doesn't take page size as input, it only takes page number, can we also add page size and accordingly get the results


<!-- Sent from Reviewable.io -->

2022-04-25 11:53 UTC, mohitg0795 commented
*[`product/ci/scm/git/git.go` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AlsBcDj5aft-KZ9Ut:-N0VZJC03oNwruHr2Q4z:bsahkkl) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L378)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

I checked that the git providers are always returning a default branch even when there are no branches https://docs.google.com/spreadsheets/d/1NWs3XKpaEXvYUZ0E2aa2KJ4OCl-Uhx8Ue68l9WreNPE/edit#gid=0.

If some git provider doesn't provide the default branch, then we will return null from here.
</blockquote></details>

"By default a main branch is created. But the list of branches returned by listBranches is empty"

Main branch is created? How's this possible if I don't have write permissions?

Also, in that case, we should first fetch list of branches. And if its not empty, then get default branch.


<!-- Sent from Reviewable.io -->

2022-04-25 11:54 UTC, mohitg0795 commented
*[`product/ci/scm/proto/scm.proto` line 490 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0U_DUO00xo-vMbmiBN:-N0VZYv0AnLuYXNcTYZy:b32v57) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L490)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

This pageRequest doesn't take page size as input, it only takes page number, can we also add page size and accordingly get the results
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-04-25 11:54 UTC, mohitg0795 commented
*[`product/ci/scm/proto/scm.proto` line 501 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AmGp1DPXiQPFGl0F1:-N0VZeR2CqtnS7dcfDWi:bh7qpyg) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L501)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can we keep status as top field as based on status only we fetch other fields.


<!-- Sent from Reviewable.io -->

2022-04-25 22:35 UTC, allofthesepeople requested changes
### API/Design

Main question is why we're making a v2 RPC as this appears to be an enhancement rather than a breaking change. 

### Code 

several nits but main functional issue is an unhandled error in `product/ci/scm/git/git.goL363`. 

I'd advise running gofmt against the code (or have editor run it on file same) to format according to Go styleguide & remove the mixed whitespace issues. 

Some questions about the overall code conventions, however, they seem to follow those of the package so probably not for this PR.

2022-04-25 22:35 UTC, allofthesepeople commented on product/ci/scm/git/git.go
> +	userRepoResponse, userRepoError := GetUserRepo(ctx, getUserRepoRequest, log)
`userRepoError` is unhandled. Is typical to override `err` if the previous err has been handled (as it has), so may be easier to rename to `err`.

2022-04-25 22:35 UTC, allofthesepeople commented on product/ci/scm/git/git.go
> +func ListBranchesV2(ctx context.Context, request *pb.ListBranchesV2Request, log *zap.SugaredLogger) (out *pb.ListBranchesV2Response, err error) {
nit: the rest of the file uses named returns but I'm not sure there's much benefit here as both are reassigned within the block.

2022-04-25 22:35 UTC, allofthesepeople commented on product/ci/scm/git/git.go
> +		// this is an error from the git provider, e.g. authentication.
nit: preference would be to have this comment as part of a function comment/docblock. Can be useful to IDEs and, while not useful here, for public functions it becomes part of the package documentation.

2022-04-25 22:35 UTC, allofthesepeople commented on product/ci/scm/git/git.go
> +		// this is an error from the git provider, e.g. authentication.
as above

2022-04-25 22:35 UTC, allofthesepeople commented on product/ci/scm/proto/scm.proto
> +message ListBranchesV2Request {
Is a new message type needed? It looks identical to `ListBranchesRequest`. Could we not reuse it?

2022-04-25 22:35 UTC, allofthesepeople commented on product/ci/scm/proto/scm.proto
> +message ListBranchesV2Response {
As with the request message, could we not simply extend `ListBranchesResponse`? This appears to be an extension rather than a breaking change to the message?
e.g.
```
message ListBranchesResponse {
    repeated string branches = 1;
    PageResponse pagination = 2;
    int32 status = 3;
    string error = 4;
    string default_branch = 5;
 }
```

This is a typical GRPC approach and why variables are assigned to a given slot.

2022-04-25 22:35 UTC, allofthesepeople commented on product/ci/scm/proto/scm.proto
> +  rpc ListBranchesV2(ListBranchesV2Request) returns (ListBranchesV2Response);
is there a breaking change to the API which requires a v2? From the messages, it appears to be an extension rather than breaking change.

2022-04-26 05:14 UTC, shubham149 commented on product/ci/scm/git/git.go
> +func createGetUserRepoFailureResponse(response *pb.GetUserRepoResponse, err error) ( *pb.ListBranchesV2Response,  error) {
Don't create a separate method to handle error. Handle it in the caller method.

2022-04-26 05:14 UTC, shubham149 commented on product/ci/scm/git/git.go
> +func createListBranchesFailureResponse(response *scm.Response, err error) ( *pb.ListBranchesV2Response,  error) {
Ditto as below one

2022-04-26 07:38 UTC, DeepakPatankar reviewed
API/Design

Yes, we could have done it as an enhancement too. But I selected to expose a new API to

1. Keep the impact area small. Any bug in this API won't break the other functionalities.
2. If someone doesn't want the default branch and only wants the branch list then he/she can use the listBranches API (listBranches  API will be faster)

Please let me know if this design looks good.


Code

Thanks, I will incorporate this comments

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383#-:-N0ZUMTa1OArFTG250Aj:b32kh27)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/git/git.go` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AlsBcDj5aft-KZ9Ut:-N0ZYi7I5Nujng1d-qlY:bxqc5a8) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L378)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

"By default a main branch is created. But the list of branches returned by listBranches is empty"

Main branch is created? How's this possible if I don't have write permissions?

Also, in that case, we should first fetch list of branches. And if its not empty, then get default branch.
</blockquote></details>

Since you are creating the repo, intially you will have the write permission. 

Okay I can do that, but that behavior would be different from what the scm providers are returning. 
___
*[`product/ci/scm/proto/scm.proto` line 490 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0U_DUO00xo-vMbmiBN:-N0ZnR0v5BllrZrR32X0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L490)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`product/ci/scm/proto/scm.proto` line 501 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AmGp1DPXiQPFGl0F1:-N0ZnPtE1C2lhTParNuC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/proto/scm.proto#L501)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we keep status as top field as based on status only we fetch other fields.
</blockquote></details>

Done.
___
*[`product/ci/scm/proto/scm.proto` line 488 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyv-r2-488:-N0ZnSvCE9BlRXiJ0IZx:b-vpxjwu) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/proto/scm.proto#L488)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

Is a new message type needed? It looks identical to `ListBranchesRequest`. Could we not reuse it? 
</blockquote></details>

Since I created new API, I decided to use a new request object. This will ensure that there is no coupling between two APIs. If in future, we want to add new parameter to V2 API, then it would be easier.
___
*[`product/ci/scm/proto/scm.proto` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyv-r2-501:-N0ZZUUWBkQtbN9H3rt2:b-c6rzpp) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/proto/scm.proto#L501)):*
extend is not supported in proto buffer 3.

> This is a typical GRPC approach and why variables are assigned to a given slot.
I 
___
*[`product/ci/scm/proto/scm.proto` line 763 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyv-r2-763:-N0ZZ6F952uziVXn2m5K:b-2elubv) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/proto/scm.proto#L763)):*
> Yes, we could have done it as an enhancement too. But I selected to expose a new API to
> 
> 1. Keep the impact area small. Any bug in this API won't break the other functionalities.
> 2. If someone doesn't want the default branch and only wants the branch list then he/she can use the listBranches API (listBranches  API will be faster)
> 
> Please let me know if this design looks good.


<!-- Sent from Reviewable.io -->

2022-04-26 07:54 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: 3 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/git/git.go` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-399:-N0Znuf79VglRv1SwcJl:b-aflhpq) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L399)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Don't create a separate method to handle error. Handle it in the caller method. 
</blockquote></details>

The listV2 function was becoming quite large, hence I created a new function.

What do you think ?



_Code quote:_
```Go
createGetUserRepoFailureResponse
```
___
*[`product/ci/scm/git/git.go` line 403 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-403:-N0Zo0sk4ZRlcKihHY-N:b-ia41wb) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L403)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

as above
</blockquote></details>

same comment as above


<!-- Sent from Reviewable.io -->

2022-04-26 09:34 UTC, shubham149 commented
*[`product/ci/scm/git/git.go` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-399:-N0_Cdct-0XzfTVUe0Tf:b-d0ae0c) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L399)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

The listV2 function was becoming quite large, hence I created a new function.

What do you think ?
</blockquote></details>

This is not the correct way to handle error. It should be in the caller method only. 
One way would have to create a separate method getDefaultUserBranch that returns default branch for a user. 


<!-- Sent from Reviewable.io -->

2022-04-26 11:05 UTC, allofthesepeople reviewed
On the introduction of bugs: I would argue the blast radius is now larger as there are two almost identical sets of functionality & code blocks so the issue is greater both in terms of potential future fixes now needing applied in two places but also potential for functional deviation between the two endpoints.

On the design: the main issue I have here is whether it is new functionality and how does an API consumer know if they want v1or v2.

The ticket doesn't reference use cases but from the comment the scenarios could be:
1. user wants a list of branches. 
2. user wants a list of branches with the default branch.
3. (user wants to know the default branch).

So wondering out loud if what we really want is an additional endpoint to expose the default branch only & leave the listBranches endpoint alone? 

This may require 2 calls for the user who wants both the list of branches and the defaultBranch but it gives more options if the concern if a user who may want one without the other. 

If not a more focused endpoint I would suggest the remaining options as a I see it would be:
- enhancement to the existing list functionality with no V2 and user gets all info
- renamed the new function to something like ListBranchesWithDefault which covers 2 of the three options. (but internally this should make use of the existing code to help save on the potential future bug issues).

Happy to talk this over as there may be requirements I'm missing. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383#-:-N0_QIm8Dwp2xjxAwy32:b8ahwcm)* status: 3 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-26 11:07 UTC, mohitg0795 commented
*[`product/ci/scm/git/git.go` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AlsBcDj5aft-KZ9Ut:-N0_YVbs7QkPCERspupE:batk1wa) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L378)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Since you are creating the repo, intially you will have the write permission. 

Okay I can do that, but that behavior would be different from what the scm providers are returning. 
</blockquote></details>

Where I'm creating the repo? I didn't get that point.


<!-- Sent from Reviewable.io -->

2022-04-27 06:35 UTC, DeepakPatankar reviewed
Roger we also want to include the support for searchTerm in the new API. 

I am currently with the second option which you suggested. We can rediscuss it in today's call

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383#-:-N0dg3hm0MM2dS-KIjpH:b-eztbvj)* status: 3 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/git/git.go` line 378 at r1](https://reviewable.io/reviews/harness/harness-core/32383#-N0AlsBcDj5aft-KZ9Ut:-N0diEzt1TgOzPaRKjmS:b-pgoq6w) ([raw file](https://github.com/harness/harness-core/blob/f51e622c9ce1befa1c85f29baa077eb4da303365/product/ci/scm/git/git.go#L378)):*
> Main branch is created? How's this possible if I don't have write permissions?

I meant the above statement for this line
___
*[`product/ci/scm/git/git.go` line 314 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-314:-N0di-pc4gZaNnWjCAtG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L314)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

please use tabs over spaces per gofmt
</blockquote></details>

Done.
___
*[`product/ci/scm/git/git.go` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-319:-N0di4v47rGlZQx9Y8Zz:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L319)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

nit: if declaring `out` at this point (and `err` is similarly declared in the function), please remove the named returns from the function signature as they aren't being used. 
</blockquote></details>

Done
___
*[`product/ci/scm/git/git.go` line 341 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-341:-N0di6WOCkBH4ass1TnQ:b-7ljw7j) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L341)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

nit: the rest of the file uses named returns but I'm not sure there's much benefit here as both are reassigned within the block. 
</blockquote></details>

I have removed the named returns
___
*[`product/ci/scm/git/git.go` line 353 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-353:-N0di8zp3LPIqpzAwWiJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L353)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

mixed indentation in this block: tabs over spaces as per gofmt. 
</blockquote></details>

Done.
___
*[`product/ci/scm/git/git.go` line 363 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-363:-N0diB8tCikQ9rV3CH4N:b5kjsqe) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L363)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

`userRepoError` is unhandled. Is typical to override `err` if the previous err has been handled (as it has), so may be easier to rename to `err`.
</blockquote></details>

Renamed the variable to err
___
*[`product/ci/scm/git/git.go` line 366 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-366:-N0diD_wEjMk5Bhc0Xwo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L366)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

mixed indentation in this block: tabs over spaces as per gofmt.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 06:40 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: 3 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/git/git.go` line 387 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-387:-N0djkad6lqx2NMkHfNm:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L387)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Ditto as below one
</blockquote></details>

Done
___
*[`product/ci/scm/git/git.go` line 391 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-391:-N0djima7w9vdrpHOXwv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L391)):*
<details><summary><i>Previously, allofthesepeople (Roger Simms) wrote…</i></summary><blockquote>

nit: preference would be to have this comment as part of a function comment/docblock. Can be useful to IDEs and, while not useful here, for public functions it becomes part of the package documentation. 
</blockquote></details>

Done
___
*[`product/ci/scm/git/git.go` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyt-r2-399:-N0djhW86Elq-O5tTQuq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/git/git.go#L399)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

This is not the correct way to handle error. It should be in the caller method only. 
One way would have to create a separate method getDefaultUserBranch that returns default branch for a user. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 10:31 UTC, shubham149 submitted a review, later dismissed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: 3 file(s) to review. 1 change requests. 13. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-27 11:10 UTC, allofthesepeople reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`product/ci/scm/proto/scm.proto` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/32383#-N0AkmKaXqnq5OLkywyv-r2-501:-N0ehW8b0VdyuDUaOQRu:b-q1cn1x) ([raw file](https://github.com/harness/harness-core/blob/e054d58c51e28f876878b985c8e4e69057943d27/product/ci/scm/proto/scm.proto#L501)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

extend is not supported in proto buffer 3.

> This is a typical GRPC approach and why variables are assigned to a given slot.
I 
</blockquote></details>

sorry, was meaning more the additional fields rather than inheritance. 


<!-- Sent from Reviewable.io -->

2022-04-27 11:11 UTC, allofthesepeople approved these changes
changes made

2022-04-27 11:11 UTC, allofthesepeople approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: 3 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-28 08:32 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r5, 2 of 4 files at r6, 3 of 3 files at r7, 14 of 14 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383#-:-N0jIC-Y1Gl9-UIqaXHu:bnfp4nl)* status: 20 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-28 11:16 UTC, DeepakPatankar commented
trigger codeformat

2022-04-28 11:17 UTC, DeepakPatankar commented
trigger messagecheck

2022-04-28 11:18 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 18 of 18 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383#-:-N0jtDVj36UgfS199V_R:bnfp4nl)* status: 21 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-04-28 11:20 UTC, abhinav-harness approved these changes
> Reviewed 1 of 3 files at r5, 2 of 4 files at r6, 1 of 3 files at r7, 4 of 18 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383)* status: 14 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-28 11:24 UTC, bhavya181 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r5, 2 of 4 files at r6, 1 of 3 files at r7, 18 of 18 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383#-:-N0juXIv3sABEEcRMP5T:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-04-28 11:24 UTC, DeepakPatankar reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32383#-:-N0ju_iS7pF1Pz2QOxPN:bnfp4nl)* status: 14 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-04-28 11:27 UTC, merged