feat: [CDS-36380]: Values yaml override feature for HelmCHart and K8sManifest.
harness/harness-core pull request #32391
Opened 2022-04-21 14:53 UTC by GoelPratyush99

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-04-21 14:57 UTC, GoelPratyush99 commented
MessageMetadata: trigger messagecheck

2022-05-05 17:00 UTC, johannesHarness submitted a review, later dismissed
> Reviewed 1 of 54 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 58 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-12 04:07 UTC, GoelPratyush99 commented
TI-bootstrap: trigger ti0

2022-05-12 06:45 UTC, GoelPratyush99 commented
TI-bootstrap1: trigger ti1
TI-bootstrap2: trigger ti2
TI-bootstrap3: trigger ti3
TI-bootstrap4: trigger ti4

2022-05-12 09:37 UTC, abosii-harness requested changes
> Reviewed 1 of 54 files at r2, 2 of 46 files at r3, 2 of 51 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 122 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 185 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1r105S3OnZi9BgHcDR:-N1r105S3OnZi9BgHcDS:bq8agit) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L185)):*
> ```Java
>                 && cdFeatureFlagHelper.isEnabled(
>                     AmbianceUtils.getAccountId(ambiance), FeatureName.DELETE_HELM_REPO_CACHE_DIR))
>             .valuesPaths(getParameterFieldValue(helmChartManifestOutcome.getValuesPaths()))
> ```

Where this valuesPaths is used? Can't find any usage
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 336 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1r1M03Dyky6H62fT9z:-N1r1M03Dyky6H62fTA-:b-rounn1) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L336)):*
> ```Java
>   public TaskChainResponse executeValuesFetchTask(Ambiance ambiance, StepElementParameters stepElementParameters,
>       InfrastructureOutcome infrastructure, ManifestOutcome k8sManifestOutcome,
>       List<ValuesManifestOutcome> aggregatedValuesManifests, Map<String, List<String>> inheritFromManifestFileContent) {
> ```

nit: name should be generalized 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 505 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1rKTkpA9H2aAekdfef:-N1rKTksEQUAqnzU3Awi:bz10gvo) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L505)):*
> ```Java
>       Ambiance ambiance, ManifestOutcome manifestOutcome) {
>     List<GitFetchFilesConfig> gitFetchFilesConfigList = new ArrayList<>();
>     String manifestOutcomeType;
> ```

Why do wee need manifestOutcomeType here? Can't we just use manifestOutcome.getType()?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 548 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1rFM383n1mZKrUYyMK:-N1rFM390UfHR55nNw6O:b-gnincg) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L548)):*
> ```Java
>   }
> 
>   private List<? extends ManifestOutcome> mapTheAggregateManifestOutcomeToItsRespectiveManifestType(
> ```

What is the actual purpose of this method? Just to create a new list?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 598 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1quQ8E3mNcTCqQe8vF:-N1quQ8E3mNcTCqQe8vG:bqa3bvb) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L598)):*
> ```Java
>             .helmChartManifestDelegateConfig(helmManifest)
>             .timeout(CDStepHelper.getTimeoutInMillis(stepElementParameters))
>             .inheritFromManifestFetchFileConfigList(inheritFromManifestFetchFileConfigList)
> ```

This and overall logic should be generalized, it shouldn't matter from where "filePaths" is coming 
So in the end you should have some like {identifier, type, filePaths} maybe under something like HelmFetchFilesConfig
As well, I would suggest to add default values.yaml under the same logic as we do for git fetch files, though is not really necessary under this PR, up to you 


<!-- Sent from Reviewable.io -->

2022-05-12 10:28 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 43 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 185 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1r105S3OnZi9BgHcDR:-N1rmu-B92XeJP6isRdL:b-9f2qba) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L185)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Where this valuesPaths is used? Can't find any usage
</blockquote></details>

Same as what we are doing for Native Helm I have done for Kubernetes

HelmChartManifestDelegateConfig helmManifest =
        (HelmChartManifestDelegateConfig) getManifestDelegateConfig(k8sManifestOutcome, ambiance);
L:583 K8sStepHelper.java


<!-- Sent from Reviewable.io -->

2022-05-12 11:07 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 43 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 505 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1rKTkpA9H2aAekdfef:-N1rsa4g6KFZO_Rz2cU7:b-fgyuf9) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L505)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why do wee need manifestOutcomeType here? Can't we just use manifestOutcome.getType()?
</blockquote></details>

I will rename it something like "overrideManifestOutcome". manifestOutcome.getType would return OpenshiftTemplate or Kustomize and not OpenshiftParams and KustomizePatches repectively.


<!-- Sent from Reviewable.io -->

2022-05-16 16:09 UTC, GoelPratyush99 commented
TI-bootstrap: trigger ti0

2022-05-17 06:25 UTC, abosii-harness requested changes
> Reviewed 1 of 30 files at r1, 6 of 46 files at r3, 7 of 88 files at r4, 3 of 51 files at r5, 24 of 50 files at r6, 2 of 7 files at r7, 23 of 25 files at r8, 5 of 5 files at r9, 3 of 3 files at r10, 5 of 5 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 241 at r11](https://reviewable.io/reviews/harness/harness-core/32391#-N2Fg2_c1jT9DP6inwtt:-N2Fg2_c1jT9DP6inwtu:bi61zeb) ([raw file](https://github.com/harness/harness-core/blob/8dc1baf24fb8b6e8ae99dc5ff20607ca2284a08e/120-ng-manager/config.yml#L241)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: true
> ```

should not be updated
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 321 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C3hOF-1zfJAubh7Qp:-N2C3hOF-1zfJAubh7Qq:b-q6tbkk) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L321)):*
> ```Java
>   }
> 
>   public GitFetchFilesConfig getGitFetchFilesConfigFromBuilder(String identifier, String manifestType,
> ```

nit: method is not reflecting the actual usage, you're getting git fetch files config from identifier, manifestType, etc. and not from builder. There is no actually a builder in params list and it would be strange if you would have a method that would call just .build() and builder from params. And this method looks more like a factory method so the naming can be createGitFetchFilesConfig
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 331 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C54Ab9VhhrEJa21EQ:-N2C54Ab9VhhrEJa21ER:b-is5d93) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L331)):*
> ```Java
>   }
> 
>   public GitFetchFilesConfig getOverridePathForGitFetchFileConfig(Ambiance ambiance, String validationMessage,
> ```

Method name and parameters overridesManifestOutcome, ManifestOutcome manifestOutcome are confusing. You're actually getting GitFetchFileConfig, so is not clear what is OverridePath here. As well we should pass directly GitStoreConfig from manifestOutcome instead of passing full ManifestOutcome
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 333 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C64i5BgDxBN_o1ftF:-N2C64i5BgDxBN_o1ftG:b3fq4j2) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L333)):*
> ```Java
>   public GitFetchFilesConfig getOverridePathForGitFetchFileConfig(Ambiance ambiance, String validationMessage,
>       ManifestOutcome overridesManifestOutcome, ManifestOutcome manifestOutcome) {
>     InheritFromManifestStoreConfig inheritFromManifestStoreConfig =
> ```

Do we need to ensure first if the type of store in overridesManifestOutcome is InheritFromManifest? Can this method be miss used? Is there actually a way to send only required details and not fully send ManifestOutcome?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 352 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6Iei1b9HsGjB6ocd:-N2C6Iei1b9HsGjB6oce:b3fq4j2) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L352)):*
> ```Java
> 
>   public static HelmFetchFileConfig getInheritFromManifestFetchFileConfig(ManifestOutcome manifestOutcome) {
>     InheritFromManifestStoreConfig inheritFromManifestStoreConfig =
> ```

Do we need to ensure first if the type of store in overridesManifestOutcome is InheritFromManifest? Can this method be miss used? Is there actually a way to send only required details and not fully send ManifestOutcome?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 474 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6XEc3vTHwAVevU-2:-N2C6XEc3vTHwAVevU-3:bfdadys) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L474)):*
> ```Java
>         .filter(valuesManifestOutcome
>             -> ManifestStoreType.InheritFromManifest.equals(valuesManifestOutcome.getStore().getKind()))
>         .map(valuesManifestOutcome -> getInheritFromManifestFetchFileConfig(valuesManifestOutcome))
> ```

nit: can be replaced to this::getInheritFromManifestFetchFileConfig
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 756 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6iV43HWIW-sO-cPw:-N2C6iV43HWIW-sO-cPx:b-2bl7z6) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L756)):*
> ```Java
>   }
> 
>   public static HelmFetchFileConfig getHelmFetchFileConfigBuilder(
> ```

name of method is wrong, I don't see any builders in return type
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 192 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6vjfAmaGHyJdFIzM:-N2C6vjfAmaGHyJdFIzN:by6ko7d) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L192)):*
> ```Java
>   public TaskChainResponse executeValuesFetchTask(Ambiance ambiance, StepElementParameters stepElementParameters,
>       InfrastructureOutcome infrastructure, ManifestOutcome helmChartManifestOutcome,
>       List<ValuesManifestOutcome> aggregatedValuesManifests, Map<String, List<String>> helmChartValuesFileMapContent,
> ```

these 2 arguments (helmChartValuesFileMapContent, valuesFileContent) can be merged in one list and stored as one map, there is no need to distinct them
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 526 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2F_IwC-tqLjrt5FC2o:-N2F_IwD0bgoWVKb5Nlf:b-guds5w) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L526)):*
> ```Java
>     }
>     Map<String, FetchFilesResult> gitFetchFilesResultMap = gitFetchResponse.getFilesFromMultipleRepo();
>     Map<String, List<String>> inheritFromManifestFetchFilesResultMap =
> ```

nit: the name of this variable is not accurate if helmValuesFileMapContents can contain in future a different values not only from inheritFromManifest
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 596 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2F_leb0h-RQw6Jv7r4:-N2F_lee2sINcFwKwEuY:bq51fk9) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L596)):*
> ```Java
>     for (ManifestOutcome valuesManifest : valuesManifests) {
>       StoreConfig store = extractStoreConfigFromManifestOutcome(valuesManifest);
>       if ((ManifestStoreType.isInGitSubset(store.getKind()) || isEmpty(helmChartFetchFilesResultMap))
> ```

I'm not sure about this condition isEmpty(helmChartFetchFilesResultMap), does it really need to be so specific? And do we need to care about from here it is coming? Actually the full method can be rewritten in simpler and more generic manner:
for each valuesManifest: 
  if gitFetchFilesResultMap.contains(valuesManifest.getIdentifier() [...]

2022-05-18 18:20 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 28 file(s) to review. 1 change requests. 18. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 241 at r11](https://reviewable.io/reviews/harness/harness-core/32391#-N2Fg2_c1jT9DP6inwtt:-N2NOUS1E5xkljheTDkW:b5y7hkz) ([raw file](https://github.com/harness/harness-core/blob/8dc1baf24fb8b6e8ae99dc5ff20607ca2284a08e/120-ng-manager/config.yml#L241)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

should not be updated
</blockquote></details>

reverted it
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 321 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C3hOF-1zfJAubh7Qp:-N2NKxNgA4im06puqv1F:b2fcaac) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L321)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: method is not reflecting the actual usage, you're getting git fetch files config from identifier, manifestType, etc. and not from builder. There is no actually a builder in params list and it would be strange if you would have a method that would call just .build() and builder from params. And this method looks more like a factory method so the naming can be createGitFetchFilesConfig
</blockquote></details>

Changed it to createGitFetchFilesConfig
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 331 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C54Ab9VhhrEJa21EQ:-N2NL2aL-zxXPP-kbaAu:b8qcrpn) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L331)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Method name and parameters overridesManifestOutcome, ManifestOutcome manifestOutcome are confusing. You're actually getting GitFetchFileConfig, so is not clear what is OverridePath here. As well we should pass directly GitStoreConfig from manifestOutcome instead of passing full ManifestOutcome
</blockquote></details>

Changed the method name. Removed the ManifestOutcome manifestOutcome and passed GitStoreConfig directly.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 333 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C64i5BgDxBN_o1ftF:-N2NLvp56LE_XEmJvJpN:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L333)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we need to ensure first if the type of store in overridesManifestOutcome is InheritFromManifest? Can this method be miss used? Is there actually a way to send only required details and not fully send ManifestOutcome?
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 352 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6Iei1b9HsGjB6ocd:-N2NMGtl4CMcMqJXaARJ:bffsrjm) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L352)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we need to ensure first if the type of store in overridesManifestOutcome is InheritFromManifest? Can this method be miss used? Is there actually a way to send only required details and not fully send ManifestOutcome?
</blockquote></details>

Divided the manifestOutcome into sub arguments to avoid misuse.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 474 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6XEc3vTHwAVevU-2:-N2NMM1r3TjoDWfT6j4d:bqtsinf) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L474)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: can be replaced to this::getInheritFromManifestFetchFileConfig
</blockquote></details>

Was not able to do this because the method is static.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 756 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6iV43HWIW-sO-cPw:-N2NMWes-sDXB8CMmLJZ:b-7iexpf) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L756)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

name of method is wrong, I don't see any builders in return type
</blockquote></details>

changed it to createHelmFetchFileConfig
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 192 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2C6vjfAmaGHyJdFIzM:-N2NMc-e72CesUD-_rXu:b-5dfryo) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L192)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

these 2 arguments (helmChartValuesFileMapContent, valuesFileContent) can be merged in one list and stored as one map, there is no need to distinct them
</blockquote></details>

removed it
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 526 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2F_IwC-tqLjrt5FC2o:-N2NMfKw96WRz7Gn7KqO:b6lmssh) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L526)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: the name of this variable is not accurate if helmValuesFileMapContents can contain in future a different values not only from inheritFromManifest
</blockquote></details>

changed it to helmChartValuesFetchFilesResultMap
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 596 at r9](https://reviewable.io/reviews/harness/harness-core/32391#-N2F_leb0h-RQw6Jv7r4:-N2NOYEKBEIRBLyUWI1w:bf0imza) ([raw file](https://github.com/harness/harness-core/blob/651af5224f1bfc0463eb763d138f0ba5ccf99de0/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L596)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm not sure about this condition isEmpty(helmChartFetchFilesResultMap), does it really need to be so specific? And do we need to care about from here it is coming? Actually the full method can be rewritten in simpler and more generic manner:
for each valuesManifest: 
  if gitFetchFilesResultMap.contains(valuesManifest.getIdentifier()) then:
     add all files from git fetch result
  if helmChartFetchFilesResultMap.contains(valuesManifest.getIdentifier()) then:
    add all files from helm fetch result
</blockquote></details>

Replaced it
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 185 at r5](https://reviewable.io/reviews/harness/harness-core/32391#-N1r105S3OnZi9BgHcDR:-N2NNJ86DdMadwq7_poH:brlf3dc) ([raw file](https://github.com/harness/harness-core/blob/f4c281185692366d373bcbb2c8a435b4f4e6d0da/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L185)):*
<details><summary><i>Previously, abosii-harness (Alex [...]

2022-05-19 06:21 UTC, abosii-harness requested changes
> Reviewed 25 of 28 files at r14, 3 of 3 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 366 at r15](https://reviewable.io/reviews/harness/harness-core/32391#-N2PounD8tcU6Ln32dm1:-N2PounD8tcU6Ln32dm2:beqwzg1) ([raw file](https://github.com/harness/harness-core/blob/82f38080828cdc1a9d92bff673b2fc12bec32190/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L366)):*
> ```Java
> 
>   public static HelmFetchFileConfig getInheritFromManifestFetchFileConfig(
>       String Identifier, String manifestType, InheritFromManifestStoreConfig inheritFromManifestStoreConfig) {
> ```

should be camelcase
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 157 at r16](https://reviewable.io/reviews/harness/harness-core/32391#-N2PyWDY0qY56uqalcy1:-N2PyWDY0qY56uqalcy2:b-wr344l) ([raw file](https://github.com/harness/harness-core/blob/bacce0b507d965e1383c46c476fc4c25420f7fc6/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L157)):*
> ```Java
>     kryo.register(ServerlessAwsLambdaRollbackDataOutcome.class, 12583);
>     kryo.register(CloudformationRollbackStepInfo.class, 12584);
>     kryo.register(HelmFetchFileResult.class, 12568);
> ```

any reasons why this is id is not next to 12584?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java` line 24 at r15](https://reviewable.io/reviews/harness/harness-core/32391#-N2PyAPH0IUQa_rsXIHE:-N2PyAPH0IUQa_rsXIHF:b-ww4s1u) ([raw file](https://github.com/harness/harness-core/blob/82f38080828cdc1a9d92bff673b2fc12bec32190/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java#L24)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public class HelmFetchFileResult implements Serializable {
>   private List<String> helmValuesFileContents;
> ```

nit: name doesn't need to contain helm
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java` line 26 at r15](https://reviewable.io/reviews/harness/harness-core/32391#-N2PyGWeBRPVjt_PVwA5:-N2PyGWeBRPVjt_PVwA6:b-6pde3e) ([raw file](https://github.com/harness/harness-core/blob/82f38080828cdc1a9d92bff673b2fc12bec32190/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java#L26)):*
> ```Java
>   private List<String> helmValuesFileContents;
> 
>   public void addEverything(HelmFetchFileResult helmFetchFileResult) {
> ```

nit: name of method can be addAllFrom


<!-- Sent from Reviewable.io -->

2022-05-19 09:21 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 366 at r15](https://reviewable.io/reviews/harness/harness-core/32391#-N2PounD8tcU6Ln32dm1:-N2Qbahm98-PMJNETeIX:b-6ibi0g) ([raw file](https://github.com/harness/harness-core/blob/82f38080828cdc1a9d92bff673b2fc12bec32190/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L366)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

should be camelcase
</blockquote></details>

Sorry for the mistake
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java` line 24 at r15](https://reviewable.io/reviews/harness/harness-core/32391#-N2PyAPH0IUQa_rsXIHE:-N2QbdzGCVdUKRpuZx9R:b-a4tmes) ([raw file](https://github.com/harness/harness-core/blob/82f38080828cdc1a9d92bff673b2fc12bec32190/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java#L24)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: name doesn't need to contain helm
</blockquote></details>

Changed to valuesFileContents
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java` line 26 at r15](https://reviewable.io/reviews/harness/harness-core/32391#-N2PyGWeBRPVjt_PVwA5:-N2QbhfACDcx2_XRGOZ3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/82f38080828cdc1a9d92bff673b2fc12bec32190/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmFetchFileResult.java#L26)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: name of method can be addAllFrom
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 157 at r16](https://reviewable.io/reviews/harness/harness-core/32391#-N2PyWDY0qY56uqalcy1:-N2QbjE53fR9l1Cx1Yhz:b-x1makv) ([raw file](https://github.com/harness/harness-core/blob/bacce0b507d965e1383c46c476fc4c25420f7fc6/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L157)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

any reasons why this is id is not next to 12584?
</blockquote></details>

removed the file from here and moved to DelegateTaskBeansKryoRegistrer.java as the file was wrongly registered in the ngkryoregistrar.java


<!-- Sent from Reviewable.io -->

2022-05-19 09:23 UTC, GoelPratyush99 commented
FunctionalTest1: trigger ft1
FunctionalTest2: trigger ft2

2022-05-19 09:23 UTC, GoelPratyush99 commented
FunctionalTest1: trigger ft1
FunctionalTest2: trigger ft2

2022-05-19 10:46 UTC, abosii-harness approved these changes
> Reviewed 2 of 5 files at r17, 3 of 10 files at r18, 7 of 7 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-19 11:05 UTC, achyuth-harness approved these changes
> Reviewed 1 of 54 files at r2, 13 of 46 files at r3, 7 of 88 files at r4, 1 of 51 files at r5, 1 of 50 files at r6, 1 of 7 files at r7, 5 of 25 files at r8, 1 of 3 files at r10, 13 of 28 files at r14, 1 of 5 files at r17, 3 of 10 files at r18, 7 of 7 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-19 11:35 UTC, anilchowdhury-harness approved these changes
> Reviewed 1 of 54 files at r2, 4 of 46 files at r3, 7 of 88 files at r4, 1 of 51 files at r5, 1 of 50 files at r6, 1 of 7 files at r7, 5 of 25 files at r8, 1 of 3 files at r10, 13 of 28 files at r14, 1 of 5 files at r17, 3 of 10 files at r18, 7 of 7 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-19 11:36 UTC, bojanmicovic approved these changes
> Reviewed 1 of 54 files at r2, 4 of 46 files at r3, 7 of 88 files at r4, 1 of 51 files at r5, 1 of 50 files at r6, 1 of 7 files at r7, 5 of 25 files at r8, 1 of 3 files at r10, 13 of 28 files at r14, 1 of 5 files at r17, 3 of 10 files at r18, 7 of 7 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32391)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-19 11:42 UTC, merged