fix: [PL-23642]: OAS non-complaint components for 120 ng-manager
harness/harness-core pull request #32637
Opened 2022-04-28 17:30 UTC by VikasMaddukuriHarness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-04-28 17:51 UTC, VikasMaddukuriHarness commented
trigger messagecheck

2022-04-29 09:06 UTC, VikasMaddukuriHarness commented
trigger ti2

2022-05-09 09:23 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java
> +  @Schema(description = "Name of the cluster associated with this account.")
Name of the cluster associated with this Account.

2022-05-09 09:23 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java
> +  @Schema(description = "Specifies the default experience of the account.")
Default experience of the Account.

2022-05-09 09:25 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java
> +  @Schema(description = "Configuration of the service account associated with the account.")
Service Account configuration associated with this Account.

2022-05-09 09:26 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java
> +  @Schema(description = "Specifies whether or not Nextgen is enabled to the account.")
Specifies if NextGen is enabled for this Account.

2022-05-09 09:28 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserGroupDTO.java
>  @Schema(name = "UserGroup", description = "This is the view of the UserGroup entity defined in Harness")
User Group details defined in Harness.

2022-05-09 09:29 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/environment/dto/EnvironmentRequestDTO.java
>  @Schema(name = "EnvironmentRequest", description = "This is the EnvironmentRequest entity defined in Harness")
Do not use DB nomenclature like "EnvironmentRequest". Please edit accordingly throughout.

2022-05-09 09:30 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/invites/dto/CreateInviteDTO.java
> +  @Schema(description = "List of the userGroups in the invite.") List<String> userGroups;
"user groups"

2022-05-09 09:31 UTC, rashminandasahoo commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/service/dto/ServiceRequestDTO.java
>  @Schema(name = "ServiceRequest", description = "This is the ServiceRequest entity defined in Harness")
Service Request details defined in Harness.

2022-05-09 10:28 UTC, rashminandasahoo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 21 of 33 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637#-:-N1cM7d8DSaalZUxuwPu:bnfp4nl)* status: 33 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-19 10:09 UTC, rashminandasahoo approved these changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 33 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-20 06:32 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 33 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/smtp/resources/SmtpNgResource.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/32637#-N2V8T5e2XD1568imrA9:-N2V8T5e2XD1568imrAA:btnb04z) ([raw file](https://github.com/harness/harness-core/blob/deb1ace44e36cf1ed38318c7300355a0afcaa037/120-ng-manager/src/main/java/io/harness/ng/core/smtp/resources/SmtpNgResource.java#L94)):*
> ```Java
>   public ResponseDTO<NgSmtpDTO>
>   save(@Valid @NotNull NgSmtpDTO variable,
>       @NotNull @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier String accountIdentifier)
> ```

@AccountIdentifier is for access control checks. Why removed at many places?


<!-- Sent from Reviewable.io -->

2022-05-20 11:52 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 33 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/smtp/resources/SmtpNgResource.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/32637#-N2V8T5e2XD1568imrA9:-N2WIqDW5bMViWqtjsCf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/deb1ace44e36cf1ed38318c7300355a0afcaa037/120-ng-manager/src/main/java/io/harness/ng/core/smtp/resources/SmtpNgResource.java#L94)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

@AccountIdentifier is for access control checks. Why removed at many places?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-20 12:07 UTC, nishantsaini20 requested changes
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 33 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 537 at r4](https://reviewable.io/reviews/harness/harness-core/32637#-N2WLVwcCG3yRgJuUM2F:-N2WLVwcCG3yRgJuUM2G:blyn122) ([raw file](https://github.com/harness/harness-core/blob/1b44a801c959697387619d2a529a6be780f55a76/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L537)):*
> ```Java
>   public ResponseDTO<DecryptableEntity>
>   decryptEncryptedDetails(@Body DecryptableEntityWithEncryptionConsumers decryptableEntityWithEncryptionConsumers,
>       @Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @AccountIdentifier @QueryParam(
> ```

Is @AccountIdentifier added intentionally here?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 560 at r4](https://reviewable.io/reviews/harness/harness-core/32637#-N2WLblm72qgAi9kKiHJ:-N2WLblm72qgAi9kKiHK:bha174) ([raw file](https://github.com/harness/harness-core/blob/1b44a801c959697387619d2a529a6be780f55a76/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L560)):*
> ```Java
>   public ResponseDTO<List<EncryptedDataDetail>>
>   getEncryptionDetails(@NotNull NGAccessWithEncryptionConsumer ngAccessWithEncryptionConsumer,
>       @Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @NotBlank @QueryParam(
> ```

@AccountIdentifier is removed?


<!-- Sent from Reviewable.io -->

2022-05-23 06:19 UTC, VikasMaddukuriHarness commented
trigger ti0

2022-05-23 06:23 UTC, nishantsaini20 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 33 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-23 06:43 UTC, meenakshi-harness commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/SmtpConfigDTO.java
> +  @Schema(description = "UserName credential to authenticate with SMTP server.")
why capital N?

2022-05-23 06:44 UTC, rashminandasahoo approved these changes
> Reviewed 4 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 27 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 06:45 UTC, meenakshi-harness commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/NgSmtpDTO.java
> +  @Schema(description = "Identifier of the SMTP config.") private String uuid;
Is this(uuid) field shown  in oas spac?

2022-05-23 06:49 UTC, VikasMaddukuriHarness commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/NgSmtpDTO.java
> +  @Schema(description = "Identifier of the SMTP config.") private String uuid;
Yes. This is the Identifier of the SMTP config. This is used in terms in update smtp call

2022-05-23 06:52 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java
> +  createToken(@Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @NotBlank @QueryParam(
why removed notnull and changed it with notblank?

2022-05-23 06:54 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/ApiKeyResource.java
> +  createApiKey(@Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @NotBlank @QueryParam(
why notnull changed to notblank?

2022-05-23 06:54 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java
> +      @Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @NotBlank @AccountIdentifier @QueryParam(
same

2022-05-23 07:10 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 31 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ApiKeyResource.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/32637#-N0lDNQ7h87lH-mewcjt-r5-110:-N2jk4Xz2sxey5hEC2cs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c68a9192697a88b54058962c32179353d430e74c/120-ng-manager/src/main/java/io/harness/ng/core/remote/ApiKeyResource.java#L110)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

why notnull changed to notblank?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 562 at r5](https://reviewable.io/reviews/harness/harness-core/32637#-N0lDNQ7h87lH-mewcju-r5-562:-N2jk6Yp7KhvHfCNiFUu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c68a9192697a88b54058962c32179353d430e74c/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L562)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-23 07:18 UTC, meenakshi-harness approved these changes
> Reviewed 15 of 33 files at r1, 8 of 12 files at r2, 1 of 5 files at r4, 1 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-23 07:34 UTC, gupta-utkarsh reviewed
> Reviewed 4 of 33 files at r1, 2 of 12 files at r2, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-23 07:37 UTC, nishantsaini20 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 07:50 UTC, meenakshi-harness approved these changes
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 09:08 UTC, nishantsaini20 approved these changes
> Reviewed 15 of 33 files at r1, 8 of 12 files at r2, 3 of 6 files at r3, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 09:09 UTC, manish-manchanda approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637#-:-N2kAKHl2_JecBQhXBeQ:bnfp4nl)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 09:10 UTC, nishantsaini20 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 13:42 UTC, diptiman-adak approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 33 files at r1, 8 of 12 files at r2, 1 of 5 files at r4, 1 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637#-:-N2l7wr4B1l5_F_2xg-t:bnfp4nl)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 13:44 UTC, diptiman-adak approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637#-:-N2l93Dp4w8I6z8bUW5y:bnfp4nl)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-23 17:10 UTC, manish-manchanda approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-24 05:44 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 33 files at r1, 8 of 12 files at r2, 1 of 5 files at r4, 1 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637#-:-N2oa8Ma55m9BDkofnnm:bnfp4nl)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-24 05:46 UTC, reetika04 approved these changes
> Reviewed 15 of 33 files at r1, 8 of 12 files at r2, 3 of 6 files at r3, 1 of 5 files at r4, 1 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-24 05:50 UTC, reetika04 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-24 05:50 UTC, reetika04 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-24 05:56 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637#-:-N2ocvKRE6RszquQ1M5o:bnfp4nl)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-24 05:58 UTC, nishantsaini20 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32637#-:-N2odCdiA_Ak0ebWOhk7:bnfp4nl)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-24 06:03 UTC, merged