[feat]: [PL-24120]: Added functor for variables
harness/harness-core pull request #32676
Opened 2022-04-29 14:26 UTC by nishantsaini20

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/32676)

2022-05-03 06:47 UTC, piyush-harness requested changes
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32676)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17eHrq7W6UWZnkZlRm:-N17eHrr37CHDRWuqnTK:bdgsyu) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L63)):*
> ```Java
>         variableDTOList = variableService.list(ngAccess.getAccountIdentifier(), ngAccess.getOrgIdentifier(), null);
>         break;
>       case PROJECT:
> ```

Why an empty case for Project Scope? Default should throw error in case Scope is wrong.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 84 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17e_a36UjEXB9ynU_p:-N17e_a42mC3UWVEFkhf:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L84)):*
> ```Java
>             variableService.get(ngAccess.getAccountIdentifier(), ngAccess.getOrgIdentifier(), null, identifier);
>         break;
>       case PROJECT:
> ```

Same here
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17ecUt5BGj7zxvYWcl:-N17ecUt5BGj7zxvYWcm:b-pt0y3r) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L89)):*
> ```Java
>             ngAccess.getAccountIdentifier(), ngAccess.getOrgIdentifier(), ngAccess.getProjectIdentifier(), identifier);
>     }
>     if (variableDTO.isPresent()) {
> ```

Could this be null?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17ee_u7iQYg5t7tyzw:-N17ee_u7iQYg5t7tyzx:bvrt2yj) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L90)):*
> ```Java
>     }
>     if (variableDTO.isPresent()) {
>       return variableDTO.get().getVariable().getVariableConfig().getValue();
> ```

What if anything is. Null here


<!-- Sent from Reviewable.io -->

2022-05-03 08:47 UTC, nishantsaini20 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32676)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17eHrq7W6UWZnkZlRm:-N185Y8NAst84H4ou26j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L63)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why an empty case for Project Scope? Default should throw error in case Scope is wrong.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 84 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17e_a36UjEXB9ynU_p:-N185XTq-j9ew4BpFiGT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L84)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17ecUt5BGj7zxvYWcl:-N17ll760pUVodIBNFzK:b-fvgf4t) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L89)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Could this be null?
</blockquote></details>

No this can never be null because the get method can return empty optional but never null.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17ee_u7iQYg5t7tyzw:-N17m9UNAnvLtMXaxPfH:bb9pauk) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L90)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

What if anything is. Null here
</blockquote></details>

The create method takes care that variable config is never null. So ideally anything here null means either incomplete data in DB or mapper from entity to DTO is buggy. In any case null pointer exception is expected to be thrown.


<!-- Sent from Reviewable.io -->

2022-05-04 05:13 UTC, piyush-harness commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17ee_u7iQYg5t7tyzw:-N1CU2dw2sW5sHJy6STi:bqff9ns) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L90)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

The create method takes care that variable config is never null. So ideally anything here null means either incomplete data in DB or mapper from entity to DTO is buggy. In any case null pointer exception is expected to be thrown.
</blockquote></details>

NullPointer as response is not a graceful fallback, We should throw specific error incase something which was expected to be mandatory and is not set.


<!-- Sent from Reviewable.io -->

2022-05-04 05:14 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java
> +  public static final String VARIABLE = "variable";
Should we move this to NGCommonCostants?

2022-05-04 05:18 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java
> +      case "project":
We must already have some constants for these. If not can we define?

2022-05-04 05:18 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java
> +    //<+variable.account.var1>
remove

2022-05-04 05:19 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java
> +    //<+variable.org.var1>
same

2022-05-04 05:19 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java
> +    //<+variable.project.var1>
same

2022-05-04 08:56 UTC, nishantsaini20 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32676)* status: 9 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/32676#-N17ee_u7iQYg5t7tyzw:-N1DDXGNBmC5VbZ6Yn34:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c3984d8c15782f9750c2c914633cd15971d3767/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L90)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

NullPointer as response is not a graceful fallback, We should throw specific error incase something which was expected to be mandatory and is not set.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/32676#-N0phqT_Jw7Q_yJJ2w1F-r2-33:-N1D-4AlDP3yqu94nXw-:bargbbw) ([raw file](https://github.com/harness/harness-core/blob/0b7ba934a86eab8737bd9d47a998e94343bb287d/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L33)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Should we move this to NGCommonCostants?
</blockquote></details>

This is functor specific, so we can leave it here.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/32676#-N0phqT_Jw7Q_yJJ2w1F-r2-116:-N1DGuBfEO7cXV_ATe9w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b7ba934a86eab8737bd9d47a998e94343bb287d/120-ng-manager/src/main/java/io/harness/ng/core/variable/expressions/functors/VariableFunctor.java#L116)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

We must already have some constants for these. If not can we define?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/32676#-N0phqT_Jw7Q_yJJ2w1H-r2-78:-N1DGvfT6oRDk1DbLGIy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b7ba934a86eab8737bd9d47a998e94343bb287d/120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java#L78)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/32676#-N0phqT_Jw7Q_yJJ2w1H-r2-104:-N1DGwOo-8wBW3g_rPWs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b7ba934a86eab8737bd9d47a998e94343bb287d/120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java#L104)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/32676#-N0phqT_Jw7Q_yJJ2w1H-r2-130:-N1DGwmx9NrRbPqw4Zdv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b7ba934a86eab8737bd9d47a998e94343bb287d/120-ng-manager/src/test/java/io/harness/ng/core/variable/expressions/functors/VariableFunctorTest.java#L130)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

remove  all commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-04 09:02 UTC, piyush-harness approved these changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32676)* status: 9 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-04 09:04 UTC, meenakshi-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 9 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32676#-:-N1DJ-hZ8s4MoNSPGV48:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-04 10:45 UTC, merged