[PL-24108]: Added update and delete api and service
harness/harness-core pull request #32805
Opened 2022-05-05 07:09 UTC by tiwaritejas

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-05 17:23 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java
> +    return new AccountScope(accountIdentifier);
Not in this PR but can we later have this piece of code in some util. Looks like reusable

2022-05-05 17:56 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java
> +    }
Not sure if these 3 check make sense. As we are getting the Variable from DB using identifiers from updated DTO and if we received a valid Variable then these will always be true.

2022-05-06 03:42 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32805#-N1MO7Ds1S7FujAMFRiG:-N1MO7Ds1S7FujAMFRiH:b-gwnt7c) ([raw file](https://github.com/harness/harness-core/blob/0ed70f9b7231e9abe4c05952beeff926482eb2f3/120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java#L30)):*
> ```Java
>     public static final String VARIABLE_UPDATED = "VariableUpdated";
>     private String accountIdentifier;
>     private VariableDTO variableDTO;
> ```

Update event should have both old (dto before update) and new (dto after update) variable dto.
Refer ProjectUpdateEvent.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/32805#-N1MOUjRERCRfBlnAcKA:-N1MOUjRERCRfBlnAcKB:bhiiq3g) ([raw file](https://github.com/harness/harness-core/blob/0ed70f9b7231e9abe4c05952beeff926482eb2f3/120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java#L94)):*
> ```Java
>                     .action(Action.UPDATE)
>                     .module(ModuleType.CORE)
>                     .newYaml(getYamlString(VariableRequestDTO.builder().variable(variableUpdateEvent.getVariableDTO()).build()))
> ```

update event should capture both oldYaml and newYaml
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/32805#-N1MPOxRETfHNUCq9kKB:-N1MPOxRETfHNUCq9kKC:b-3bve0b) ([raw file](https://github.com/harness/harness-core/blob/0ed70f9b7231e9abe4c05952beeff926482eb2f3/120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java#L111)):*
> ```Java
>                     .action(Action.DELETE)
>                     .module(ModuleType.CORE)
>                     .newYaml(getYamlString(VariableRequestDTO.builder().variable(variableDeleteEvent.getVariableDTO()).build()))
> ```

capture in oldYaml as this is delete event.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/32805#-N1MQ94DAPFNUVEUefmN:-N1MQ94DAPFNUVEUefmO:b-93su2s) ([raw file](https://github.com/harness/harness-core/blob/b91e65b7119ebde83112182df63cf5abafe4dda1/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L171)):*
> ```Java
>                     accountIdentifier, variableDTO.getOrgIdentifier(), variableDTO.getProjectIdentifier(), variableDTO.getIdentifier());
>     validateTheUpdateRequestIsValid(variableDTO, existingVariable, accountIdentifier);
>     assureThatTheProjectAndOrgExists(variableDTO, accountIdentifier);
> ```

add this check to create method as well.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/32805#-N1MR2RUCqi_3DNOdMTt:-N1MR2RUCqi_3DNOdMTu:b-k6pw40) ([raw file](https://github.com/harness/harness-core/blob/b91e65b7119ebde83112182df63cf5abafe4dda1/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L199)):*
> ```Java
>     }
>     else {
>       throw new VariableNotFoundException("Variable Not Found", USER);
> ```

Message should be proper.
___
*[`980-commons/src/main/java/io/harness/exception/VariableNotFoundException.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/32805#-N1MSW3f-qHt-V3ID871:-N1MSW3f-qHt-V3ID872:b88bg08) ([raw file](https://github.com/harness/harness-core/blob/b91e65b7119ebde83112182df63cf5abafe4dda1/980-commons/src/main/java/io/harness/exception/VariableNotFoundException.java#L12)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PL)
> public class VariableNotFoundException extends WingsException {
> ```

Why do we need to introduce a new type of exception?


<!-- Sent from Reviewable.io -->

2022-05-06 05:22 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java
> +    }
If the updated DTO is coming from UI, then the org and proj IDs will be correct, but while using it through APIs, different org/project can be passed and they need to be handled imo

2022-05-06 05:24 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/events/VariableDeleteEvent.java
> +    if (isNotEmpty(variableDTO.getOrgIdentifier())) {
In it's parent method, we check if the optional corresponding to this DTO is present and only then proceed forward

2022-05-06 05:24 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java
> +    return new AccountScope(accountIdentifier);
Yes, I was also thinking this

2022-05-06 05:28 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java
> +    }
From UI, the update DTO will have the correct org and project IDs, but if we update using API, these checks are required as different org/project can be passed

2022-05-06 05:32 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java
> +    }
So that is what I meant. Suppose from API we passed proj1 and org1, but there was no variable with these ids, then the first statement will not return any data from DB.

2022-05-06 05:52 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java
> +    }
removed

2022-05-06 05:52 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java
> +    }
removed the checks

2022-05-06 06:10 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 11 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32805#-N1MO7Ds1S7FujAMFRiG:-N1MzOEeAKtkNugBKeLp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ed70f9b7231e9abe4c05952beeff926482eb2f3/120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java#L30)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Update event should have both old (dto before update) and new (dto after update) variable dto.
Refer ProjectUpdateEvent.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/32805#-N1MOUjRERCRfBlnAcKA:-N1MzPrtExnziEP3E4Ef:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ed70f9b7231e9abe4c05952beeff926482eb2f3/120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java#L94)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

update event should capture both oldYaml and newYaml
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/32805#-N1MPOxRETfHNUCq9kKB:-N1MzQhi7XI4pljhiEdE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ed70f9b7231e9abe4c05952beeff926482eb2f3/120-ng-manager/src/main/java/io/harness/ng/core/outbox/VariableEventHandler.java#L111)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

capture in oldYaml as this is delete event.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/32805#-N1MQ94DAPFNUVEUefmN:-N1MzRsF3T2v0Vb_PmFP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b91e65b7119ebde83112182df63cf5abafe4dda1/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L171)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

add this check to create method as well.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/32805#-N1MR2RUCqi_3DNOdMTt:-N1MzSfNBkXUEeuLtbQF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b91e65b7119ebde83112182df63cf5abafe4dda1/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L199)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Message should be proper.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/VariableNotFoundException.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/32805#-N1MSW3f-qHt-V3ID871:-N1MzTZqDrMOd6xeNPHh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b91e65b7119ebde83112182df63cf5abafe4dda1/980-commons/src/main/java/io/harness/exception/VariableNotFoundException.java#L12)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why do we need to introduce a new type of exception?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-06 06:28 UTC, meenakshi-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 1 of 9 files at r2, 1 of 8 files at r3, 1 of 3 files at r4, 4 of 7 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805#-:-N1N2S2m9F2JF8AoMuo3:bnfp4nl)* status: 11 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-06 06:29 UTC, nishantsaini20 requested changes
> Reviewed 1 of 8 files at r3, 1 of 3 files at r4, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java` line 31 at r7](https://reviewable.io/reviews/harness/harness-core/32805#-N1N0dLXBmo6uAR-2Pgy:-N1N0dLXBmo6uAR-2Pgz:blmihyu) ([raw file](https://github.com/harness/harness-core/blob/76af55b8e28b144259c23caa85ea6109cd0525f8/120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java#L31)):*
> ```Java
>   private String accountIdentifier;
>   private VariableDTO newVariableDTO;
>   private VariableDTO olVariableDTO;
> ```

There is a typo here. Should be oldVariableDTO
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 184 at r7](https://reviewable.io/reviews/harness/harness-core/32805#-N1N1nsM22KBKpgCr8wX:-N1N1nsM22KBKpgCr8wY:bn36z0g) ([raw file](https://github.com/harness/harness-core/blob/76af55b8e28b144259c23caa85ea6109cd0525f8/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L184)):*
> ```Java
>         Variable updatedVariable = variableRepository.save(newVariable);
>         outboxService.save(
>             new VariableUpdateEvent(accountIdentifier, variableMapper.writeDTO(updatedVariable), variableDTO));
> ```

old variableDtO will be the one fetched from DB before the update call to DB.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 207 at r7](https://reviewable.io/reviews/harness/harness-core/32805#-N1N29ma81KByYE20UWH:-N1N29ma81KByYE20UWI:bxxnlgx) ([raw file](https://github.com/harness/harness-core/blob/76af55b8e28b144259c23caa85ea6109cd0525f8/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L207)):*
> ```Java
>     } else {
>       throw new NotFoundException(
>           String.format("Variable [%s] Not Found for account- [%s], organization- [%s], project- [%s]",
> ```

This message will also be shown to end user therefore call the values as orgIdentifier and projectIdentifier. Its not required to keep accountIdentifier as part of the message.


<!-- Sent from Reviewable.io -->

2022-05-06 07:01 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java` line 31 at r7](https://reviewable.io/reviews/harness/harness-core/32805#-N1N0dLXBmo6uAR-2Pgy:-N1N9y_LEXxtBAl93dJV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76af55b8e28b144259c23caa85ea6109cd0525f8/120-ng-manager/src/main/java/io/harness/ng/core/events/VariableUpdateEvent.java#L31)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

There is a typo here. Should be oldVariableDTO
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 184 at r7](https://reviewable.io/reviews/harness/harness-core/32805#-N1N1nsM22KBKpgCr8wX:-N1N9zCx3ffG1qzLl7xZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76af55b8e28b144259c23caa85ea6109cd0525f8/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L184)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

old variableDtO will be the one fetched from DB before the update call to DB.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 207 at r7](https://reviewable.io/reviews/harness/harness-core/32805#-N1N29ma81KByYE20UWH:-N1N9zpg9OkvM1IWx9M7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76af55b8e28b144259c23caa85ea6109cd0525f8/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L207)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This message will also be shown to end user therefore call the values as orgIdentifier and projectIdentifier. Its not required to keep accountIdentifier as part of the message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-06 07:03 UTC, nishantsaini20 approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 9 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-06 07:12 UTC, meenakshi-harness approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 6 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-06 07:16 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 6 files at r1, 1 of 9 files at r2, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-06 07:17 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 6 files at r1, 1 of 9 files at r2, 1 of 8 files at r3, 1 of 3 files at r4, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-06 07:18 UTC, nishantsaini20 approved these changes
> Reviewed 3 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32805)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-06 07:19 UTC, merged