[PL-25010]: exposing SCM API endpoints for git sdk
harness/harness-core pull request #32837
Opened 2022-05-05 20:24 UTC by mohitg0795

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-06 11:52 UTC, ankit-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837#-:-N1OCblY6_TXCOGi6h6B:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-16 19:47 UTC, mohitg0795 commented
trigger messagecheck

2022-05-16 20:01 UTC, mohitg0795 commented
trigger messagecheck

2022-05-17 02:37 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 165 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EpttH2pIS6ii0x2mV:-N2EpttI0C8H1msB5NDK:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L165)):*
> ```Java
>     try (GlobalContextManager.GlobalContextGuard guard = GlobalContextManager.ensureGlobalContextGuard();
>          MdcContextSetter ignore1 = new MdcContextSetter(request.getContextMapMap())) {
>       setPrincipal(request.getScopeIdentifiers().getAccountIdentifier(), request.getPrincipal());
> ```

Why this change?
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EqN5p7ehV7KzQysGI:-N2EqN5q6LULdsrxFnxh:b-c67x1h) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L170)):*
> ```Java
>   public void testGetFileByBranchWhenSCMOpsIsSuccess() {
>     GetFileRequest getFileRequest =
>         GetFileRequest.newBuilder().setBranchName(branch).setFilePath(filePath).setRepoName(repoName).build();
> ```

Have a default GetFileRequest with default fields. Its fields you can override on each tests basis
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2Eqmdv6GTSmp1iHz20:-N2Eqmdv6GTSmp1iHz21:b-k1i1bb) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L315)):*
> ```Java
>   }
> 
>   private void assertGitMetaData(
> ```

  private void assertGitMetaData(
      GitMetaData expected, GitMetadata actual) {
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2Er6Vp9Rw28DqgFT2i:-N2Er6Vp9Rw28DqgFT2j:b-lkgt0x) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L325)):*
> ```Java
>   }
> 
>   private void assertGitErrorDetails(ErrorDetails errorDetails) {
> ```

  private void assertGitMetaData(
      ErrorDetails expected, ErrorDetails actual) {


<!-- Sent from Reviewable.io -->

2022-05-17 09:59 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 165 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EpttH2pIS6ii0x2mV:-N2GS2NS8WbG4_Famqah:btrws3z) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L165)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

principal requires to be set for decrypting connector creds


<!-- Sent from Reviewable.io -->

2022-05-17 09:59 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EqN5p7ehV7KzQysGI:-N2GSI9o5u4xlAamrIjw:b-tzu2on) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L170)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Have a default GetFileRequest with default fields. Its fields you can override on each tests basis
</blockquote></details>

actually I don't need to override. Let me replace it with default request method.


<!-- Sent from Reviewable.io -->

2022-05-17 10:16 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2Er6Vp9Rw28DqgFT2i:-N2GWBf651zAcXVmVBqw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L325)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

  private void assertGitMetaData(
      ErrorDetails expected, ErrorDetails actual) {


</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-17 10:16 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2Eqmdv6GTSmp1iHz20:-N2GWCu-1IlxaSsY-xKt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L315)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

  private void assertGitMetaData(
      GitMetaData expected, GitMetadata actual) {


</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-17 10:16 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EqN5p7ehV7KzQysGI:-N2GWF8PEphfLuCTYeJM:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L170)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

actually I don't need to override. Let me replace it with default request method.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-17 11:26 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java
> +        harnessToGitHelperService.getFileByBranch(GetFileRequest.newBuilder()
why is it calling harnesstoGitHelperservice anf not ScmFacilatorService directly?

2022-05-17 11:26 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileRequestDTO.java
> +public class ScmGetFileRequestDTO {
We should name it specific to branch, because when we add get file by commit that also rrequires a separate dto as this dto does not have any commitId, right?

2022-05-17 12:37 UTC, DeepakPatankar requested changes
> Reviewed 7 of 17 files at r1, 1 of 14 files at r2, 2 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H0JWr5qIbET7HJF6u:-N2H0JWr5qIbET7HJF6v:bl6e7vv) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java#L35)):*
> ```Java
>     WingsException hintException = ExceptionUtils.cause(ErrorCode.HINT, ex);
>     if (hintException == null) {
>       return "";
> ```

Instead of "", we can return null here, so that at the caller side we can simply add a null check


<!-- Sent from Reviewable.io -->

2022-05-17 12:38 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 361 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H0b2MEmwgBnIMTCvZ:-N2H0b2NEu5tULrIuE0f:b9m054k) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L361)):*
> ```Java
>       if (scmException == null) {
>         return GetFileResponse.newBuilder()
>             .setStatusCode(ex.getCode().getStatus().getCode())
> ```

Will the exception always have a code? I have seen that SCM is not returning status in some of the cases


<!-- Sent from Reviewable.io -->

2022-05-17 12:43 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 228 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H1p_p7f6iTVUVfo7e:-N2H1p_p7f6iTVUVfo7f:bbv5209) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L228)):*
> ```Java
>         -> scmClientFacilitatorService.getFile(scope.getAccountIdentifier(), scope.getOrgIdentifier(),
>             scope.getProjectIdentifier(), scmGetFileRequestDTO.getConnectorRef(), scmGetFileRequestDTO.getRepoName(),
>             branchName, scmGetFileRequestDTO.getFilePath(), null),
> ```

Which value is null here ?


<!-- Sent from Reviewable.io -->

2022-05-17 12:43 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2DKak-WSvMal8zyoDV-r3-257:-N2H1wuV7DYX0NhYQkhF:b32v57) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L257)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

why is it calling harnesstoGitHelperservice anf not ScmFacilatorService directly?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-05-17 12:55 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2H4bhZ8P32fmE0EDYb:b-l0lp3m) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
> ```Java
>     try (GlobalContextManager.GlobalContextGuard guard = GlobalContextManager.ensureGlobalContextGuard();
>          MdcContextSetter ignore1 = new MdcContextSetter(request.getContextMapMap())) {
>       setPrincipal(request.getScopeIdentifiers().getAccountIdentifier(), request.getPrincipal());
> ```

Lets unset the principal object too


<!-- Sent from Reviewable.io -->

2022-05-17 20:12 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H0JWr5qIbET7HJF6u:-N2IbkakCQMGiEP7hrY3:b7gannh) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java#L35)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Instead of "", we can return null here, so that at the caller side we can simply add a null check
</blockquote></details>

Its an internal helper util, so created as per our requirements. We needed to fill in grpc response with error details where its used.
Also, alternatively I would prefer to put an isEmpty() check rather than a null check on client side if ever required. So, thats handled.


<!-- Sent from Reviewable.io -->

2022-05-17 20:13 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 361 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H0b2MEmwgBnIMTCvZ:-N2Idj4S3JvH2A5YIzWb:b8mj0u2) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L361)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Will the exception always have a code? I have seen that SCM is not returning status in some of the cases
</blockquote></details>

Yes, all exceptions have ERROR_CODE and every ERROR CODE has a status code.


<!-- Sent from Reviewable.io -->

2022-05-17 20:15 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2DKak-WSvMal8zyoDV-r3-257:-N2IdxxY5coTABGvJBJG:b-b9tw4m) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L257)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

+1
</blockquote></details>

you can imagine that Harness to git service grpc is our resource layer which is just an entry point -> which calls harnessToGitHelper service which is our service layer which does all orchestration, logic, error handling for it -> which will call SCM Facilitator service for any of its use-case. Thus, there's a middle layer as you see.


<!-- Sent from Reviewable.io -->

2022-05-17 20:17 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2IeIWj9jC6yLoohpRy:b-ql2fm1) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Lets unset the principal object too
</blockquote></details>

Why so? Thread will be dead once request is responded with a response.


<!-- Sent from Reviewable.io -->

2022-05-17 20:19 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 228 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H1p_p7f6iTVUVfo7e:-N2If8c3B90VOh_VqjGc:bvv06rj) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L228)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Which value is null here ?
</blockquote></details>

commit id


<!-- Sent from Reviewable.io -->

2022-05-17 20:19 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileRequestDTO.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N1KtMF5D2oSc3PPpl3j-r3-23:-N2IbZcu4CUMKZYNpBVX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmGetFileRequestDTO.java#L23)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

We should name it specific to branch, because when we add get file by commit that also rrequires a separate dto as this dto does not have any commitId, right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-18 02:56 UTC, ankit-harness requested changes
> Reviewed 4 of 14 files at r2, 6 of 12 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2K3InCETc0VOOCDthk:-N2K3InD0ogYV5-au_WV:bl38xku) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L200)):*
> ```Java
> 
>   @Override
>   public CreatePRResponse createPullRequest(
> ```

Whats the purpose of this method?
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 165 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EpttH2pIS6ii0x2mV:-N2K45rPBhVZfrUqj89K:bfprbja) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L165)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

principal requires to be set for decrypting connector creds
</blockquote></details>

I didn't understand
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 357 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2K4hefDOg7s8Na17Wx:-N2K4hefDOg7s8Na17Wy:bficjcj) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L357)):*
> ```Java
>   }
> 
>   private FileInfo getFileInfoDefault(String commitId, ChangeType changeType, boolean isNewBranch) {
> ```

getDefaultFileInfo OR newFileInfo


<!-- Sent from Reviewable.io -->

2022-05-18 03:14 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2K3InCETc0VOOCDthk:-N2K8wfQ-UFBEzqo5P-l:byd6b05) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L200)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the purpose of this method?
</blockquote></details>

It is a placeholder method for now. As we used the method in our other services, so had to add it. It will be pushed to develop in another PR.


<!-- Sent from Reviewable.io -->

2022-05-18 03:14 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 165 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EpttH2pIS6ii0x2mV:-N2K9AHI4NMbS5yu7srV:b-nn3j7g) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L165)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I didn't understand
</blockquote></details>

Are you talking about setting principal? If yes, then principal is required when we decrypt the connector, thus being set over here.


<!-- Sent from Reviewable.io -->

2022-05-18 03:16 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java` line 357 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2K4hefDOg7s8Na17Wx:-N2K9OJH7Pcu9ERojzrW:b-4kfz58) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImplTest.java#L357)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getDefaultFileInfo OR newFileInfo
</blockquote></details>

its existing code @ankit-harness, not a part of current change.


<!-- Sent from Reviewable.io -->

2022-05-18 07:10 UTC, bhavya181 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2DKak-WSvMal8zyoDV-r3-257:-N2KznMS4tL8m5RAqRHE:b-1mncg3) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L257)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

you can imagine that Harness to git service grpc is our resource layer which is just an entry point -> which calls harnessToGitHelper service which is our service layer which does all orchestration, logic, error handling for it -> which will call SCM Facilitator service for any of its use-case. Thus, there's a middle layer as you see.
</blockquote></details>

No, so what extra processing does that HarnessToGitHelperService is doing? This resource layer is for scm apis, that canjust gives use what scm sends to us directly, but if we want to call harnessToGitHalperService only, then maybe we can write another resource layer for that, putting this into ScmResource is not good.


<!-- Sent from Reviewable.io -->

2022-05-18 07:13 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2K3InCETc0VOOCDthk:-N2L-cNJ8x7rAw8KPml_:b49xopa) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L200)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It is a placeholder method for now. As we used the method in our other services, so had to add it. It will be pushed to develop in another PR.
</blockquote></details>

Mohit the changes for client side are in develop, you can please integrate both these methods, I have integrated them in feature branch.


<!-- Sent from Reviewable.io -->

2022-05-18 07:14 UTC, bhavya181 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2L-vR0C108OXrZ4KCm:-N2L-vR0C108OXrZ4KCn:b-w1oos5) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L140)):*
> ```Java
>                 .scmConnector(scmConnector)
>                 .yaml(scmCreateFileRequestDTO.getFileContent())
>                 .build()),
> ```

don't push these methods to develop, I will integrate them with the V2 clientfaciilitator methods indifferent pr
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 170 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2L0AaED9I0pD4t0qUv:-N2L0AaED9I0pD4t0qUw:b-w1oos5) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L170)):*
> ```Java
>                 .filePath(scmUpdateFileRequestDTO.getFilePath())
>                 .baseBranch(scmUpdateFileRequestDTO.getBaseBranch())
>                 .branch(scmUpdateFileRequestDTO.getBranchName())
> ```

don't push these methods to develop, I will integrate them with the V2 clientfaciilitator methods indifferent pr


<!-- Sent from Reviewable.io -->

2022-05-18 07:16 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 23 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 165 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EpttH2pIS6ii0x2mV:-N2L0UrH7_RhqcS3PzyE:b-ktvdyx) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L165)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Are you talking about setting principal? If yes, then principal is required when we decrypt the connector, thus being set over here.
</blockquote></details>

Please check once, we should set both SecurityPrincipal and SourcePrincipal in this case.


<!-- Sent from Reviewable.io -->

2022-05-18 12:40 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837#-:-N2MAj5L27Ws0zmmeFmo:bnfp4nl)* status: 23 file(s) to review. 2 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-18 13:20 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2DKak-WSvMal8zyoDV-r3-257:-N2MJkzc9XWA3FxT_W3S:b-aw8277) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L257)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

No, so what extra processing does that HarnessToGitHelperService is doing? This resource layer is for scm apis, that canjust gives use what scm sends to us directly, but if we want to call harnessToGitHalperService only, then maybe we can write another resource layer for that, putting this into ScmResource is not good.
</blockquote></details>

As discussed on call, it was more of a misunderstanding. Firstly, this change wasn't intended and got into PR when one of the methods was renamed. Removed the redundant method itself now.


<!-- Sent from Reviewable.io -->

2022-05-18 13:22 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 165 at r2](https://reviewable.io/reviews/harness/harness-core/32837#-N2EpttH2pIS6ii0x2mV:-N2MKL0W9Ggl4L5MYcLm:b-1j14xg) ([raw file](https://github.com/harness/harness-core/blob/d425362d94304fecc52067a5e4a90977dbb136ea/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L165)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Please check once, we should set both SecurityPrincipal and SourcePrincipal in this case.
</blockquote></details>

As discussed, both principal and source principal are being set, so we look good here.


<!-- Sent from Reviewable.io -->

2022-05-18 13:23 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 170 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2L0AaED9I0pD4t0qUv:-N2MKVDe4puLfvrY-iUX:bs5vqls) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L170)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

don't push these methods to develop, I will integrate them with the V2 clientfaciilitator methods indifferent pr
</blockquote></details>

as discussed, this will be taken care of consequent PRs.


<!-- Sent from Reviewable.io -->

2022-05-18 13:23 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2L-vR0C108OXrZ4KCm:-N2MKYo-DKjloH_4UW7Q:bs5vqls) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L140)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

don't push these methods to develop, I will integrate them with the V2 clientfaciilitator methods indifferent pr
</blockquote></details>

as discussed, this will be taken care of consequent PRs.


<!-- Sent from Reviewable.io -->

2022-05-18 13:28 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/32837#-N2K3InCETc0VOOCDthk:-N2MLbRBBGGKINs2ymUi:bsk3cnk) ([raw file](https://github.com/harness/harness-core/blob/ffef96b1e7f20dec11aab16a41533441cd08aa2f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L200)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Mohit the changes for client side are in develop, you can please integrate both these methods, I have integrated them in feature branch.
</blockquote></details>

As discussed, the changes are in feature branch and will be merged in consequent PRs.


<!-- Sent from Reviewable.io -->

2022-05-18 13:44 UTC, DeepakPatankar requested changes
> Reviewed 1 of 17 files at r1, 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 21 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H0JWr5qIbET7HJF6u:-N2MOyfi-OAdjigRyTMx:bhk3v17) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/ScmExceptionUtils.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Its an internal helper util, so created as per our requirements. We needed to fill in grpc response with error details where its used.
Also, alternatively I would prefer to put an isEmpty() check rather than a null check on client side if ever required. So, thats handled.
</blockquote></details>

Empty string has a meaning, whereas null string means that the String is not containing any value.

Setting it as null seems like a correct value as hint message is not set in this case.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 361 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H0b2MEmwgBnIMTCvZ:-N2MPGDtCqR1HN_v7UyX:b-ufcp7e) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L361)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, all exceptions have ERROR_CODE and every ERROR CODE has a status code.
</blockquote></details>

What is the status when scm service doesn't send the status ?


<!-- Sent from Reviewable.io -->

2022-05-18 13:58 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 361 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H0b2MEmwgBnIMTCvZ:-N2MSSEl5c0eVuTLOVTQ:b-ldwp39) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L361)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

What is the status when scm service doesn't send the status ?
</blockquote></details>

Its not possible. These are our ScmException(extends WingsException) which will always have a ERROR CODE (and every ERROR CODE has a status code).


<!-- Sent from Reviewable.io -->

2022-05-18 14:32 UTC, DeepakPatankar requested changes
> Reviewed 1 of 12 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 19 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2M_6bDCn-rALvjlyEU:b87jnpf) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why so? Thread will be dead once request is responded with a response.
</blockquote></details>

Are you sure that a new thread is spawn everytime a new grpc call is done. You can check that using breakpoing just before the principal is set.

Also it would be more safe, if we remove the thread variables which we have set.


<!-- Sent from Reviewable.io -->

2022-05-18 14:35 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2M_mjqCsThOUC3fR4V:b-gznqng) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Are you sure that a new thread is spawn everytime a new grpc call is done. You can check that using breakpoing just before the principal is set.

Also it would be more safe, if we remove the thread variables which we have set.
</blockquote></details>

- We aren't doing this in our current git sync as well
- Also, for grpc call, it should be new thread only. There's no reason for threads to be re-used here as we don't have any threadpool to serve it.
- I guess it should be fine for now. I will test what you mentioned in sometime and we can take it up in consequent PRs if we see any concern over there. We haven't been reported any failures until now as well.


<!-- Sent from Reviewable.io -->

2022-05-18 15:49 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2MqtDfEPWCJmzZEWv_:btb6dwv) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

- We aren't doing this in our current git sync as well
- Also, for grpc call, it should be new thread only. There's no reason for threads to be re-used here as we don't have any threadpool to serve it.
- I guess it should be fine for now. I will test what you mentioned in sometime and we can take it up in consequent PRs if we see any concern over there. We haven't been reported any failures until now as well.
</blockquote></details>

It is using gaurd and it's under try catch, gaurd will ensure thread will be dead as soon as try ends.


<!-- Sent from Reviewable.io -->

2022-05-18 20:22 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2NpHf26N9wI2INejQ8:bxemqdv) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

It is using gaurd and it's under try catch, gaurd will ensure thread will be dead as soon as try ends.
</blockquote></details>

It doesn't handle thread lifecycle, but it handles the context lifecycle from its start to end where guard is declared, so that should cover the concerned case here. Also, anyways there would always be a new thread so this problem won't occur.


<!-- Sent from Reviewable.io -->

2022-05-19 04:57 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2Pefke1SHmuSKWmELm:b-1g2e9d) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It doesn't handle thread lifecycle, but it handles the context lifecycle from its start to end where guard is declared, so that should cover the concerned case here. Also, anyways there would always be a new thread so this problem won't occur.
</blockquote></details>

Last time I created a P0, where I didn't unset the UserPrincipal and I assumed that a new thread is created every time.

This resulted in the issue where if Customer1's user was set and the same thread was run by Customer2, then for Customers2 we were using Customer1's user.

for eg: AXA was seeing that its pipeline is being run by NAB.


I would strongly suggest to use unset function here.


<!-- Sent from Reviewable.io -->

2022-05-19 05:06 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2PfpR_458Uxr2Ia3OR:bwyzfxo) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Last time I created a P0, where I didn't unset the UserPrincipal and I assumed that a new thread is created every time.

This resulted in the issue where if Customer1's user was set and the same thread was run by Customer2, then for Customers2 we were using Customer1's user.

for eg: AXA was seeing that its pipeline is being run by NAB.


I would strongly suggest to use unset function here.
</blockquote></details>

I have a few questions here:
1) Could you answer why its not being done in current git sync grpc pushFile call? And if thats working all perfect until now since last 1 year, do we need to still unset it?
2) Could you please point out where you did this fix and where was the exact issue happening? The context of that code flow might be very different from ours.

As a good practice, we can always unset things, but I don't see a good reason to do it here just like that. It seems to be all fine to me.

To put a logical conclusion on this topic in regards to particularly this PR, I've created a ticket to track it: https://harness.atlassian.net/browse/PL-25309. Lets try to take this up separately coz this would need a longer discussion it seems and we can unblock this PR for now. We can check more on this separately if that works for you.

If this looks good to you, kindly help to approve this PR if this is the only last concern left. Thanks.


<!-- Sent from Reviewable.io -->

2022-05-19 05:33 UTC, DeepakPatankar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/32837#-N2H4bhZ8P32fmE0EDYa:-N2PnRQqE-DiXEaUBVwc:bjy8m80) ([raw file](https://github.com/harness/harness-core/blob/719fc45dfc46eb12952ca3e80ceaa7b53d811e3d/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I have a few questions here:
1) Could you answer why its not being done in current git sync grpc pushFile call? And if thats working all perfect until now since last 1 year, do we need to still unset it?
2) Could you please point out where you did this fix and where was the exact issue happening? The context of that code flow might be very different from ours.

As a good practice, we can always unset things, but I don't see a good reason to do it here just like that. It seems to be all fine to me.

To put a logical conclusion on this topic in regards to particularly this PR, I've created a ticket to track it: https://harness.atlassian.net/browse/PL-25309. Lets try to take this up separately coz this would need a longer discussion it seems and we can unblock this PR for now. We can check more on this separately if that works for you.

If this looks good to you, kindly help to approve this PR if this is the only last concern left. Thanks.
</blockquote></details>

1. Since it is in guard it will be unset, but I would suggest that you should test it using breakpoint. The guard might be the reason we didn't get this issue.
2.  I didn't use a guard too. Otherwise it was a very similar case.


<!-- Sent from Reviewable.io -->

2022-05-19 05:34 UTC, DeepakPatankar approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 9 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-19 08:52 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 14 files at r2, 1 of 12 files at r3, 1 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837#-:-N2QWBxAAb25tUYzkOds:bnfp4nl)* status: 6 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-19 08:53 UTC, ankit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: 6 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-19 08:55 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837#-:-N2QWqEdC-dVPnOCN_KH:bnfp4nl)* status: 6 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-05-19 08:56 UTC, bhavya181 approved these changes
> Reviewed 10 of 17 files at r1, 4 of 14 files at r2, 4 of 12 files at r3, 5 of 5 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-19 08:56 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32837#-:-N2QWyciAptmhnuF1SE-:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-19 08:56 UTC, merged