feat: [CCM-7278] Delegate Health Check
harness/harness-core pull request #32919
Opened 2022-05-09 06:05 UTC by trunapushpa

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-11 00:58 UTC, hitesharinga commented on 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/DelegateHealthCheckTasklet.java
> +      for (String clusterId : lastReceivedTimeForClusters.keySet()) {
We need to check if the delegate is healthy or not.

2022-05-11 00:58 UTC, hitesharinga commented on 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/DelegateHealthCheckTasklet.java
> +          log.info("Delegate health check failed for clusterId: {}", clusterId);
We need to send alerts for those clusters where we have't received the events at all/

2022-05-11 11:09 UTC, nikunj-badjatya requested changes

2022-05-11 11:09 UTC, nikunj-badjatya commented on scripts/terraform/stackdriver/batch-processing/delegate_health_monitoring.tf
> +  display_name = join("_", [local.name_prefix, "ce_delayed_batch_jobs"])
Change the display name to be unique.

2022-05-12 07:58 UTC, trunapushpa reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32919)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/DelegateHealthCheckTasklet.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/32919#-N1bQ3JJRS92gtNApnkg-r1-62:-N1rDJ5869WrgOeoP_og:b-utawwg) ([raw file](https://github.com/harness/harness-core/blob/3c76978ccb49fe725c862edeb40fecdbd82e66a6/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/DelegateHealthCheckTasklet.java#L62)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

We need to check if the delegate is healthy or not. 
</blockquote></details>

Done, but I couldn't test it as there were no healthy delegates on `ce-dev`.
___
*[`280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/DelegateHealthCheckTasklet.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/32919#-N1bQ3JJRS92gtNApnkg-r1-64:-N1rGhvW6xq_NMJU2RoD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3c76978ccb49fe725c862edeb40fecdbd82e66a6/280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/DelegateHealthCheckTasklet.java#L64)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

We need to send alerts for those clusters where we have't received the events at all/ 
</blockquote></details>

Done.
___
*[`scripts/terraform/stackdriver/batch-processing/delegate_health_monitoring.tf` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/32919#-N1ctTyZXgNpMsCYKyjC-r2-29:-N1rDQpZ0wMsCv-v5JUV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39fc164ad10d1440f112a9ae37721bf21b57a0e6/scripts/terraform/stackdriver/batch-processing/delegate_health_monitoring.tf#L29)):*
<details><summary><i>Previously, nikunj-badjatya (Nikunj Badjatya) wrote…</i></summary><blockquote>

Change the display name to be unique.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-18 18:37 UTC, hitesharinga commented on 280-batch-processing/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java
> +  DELEGATE_HEALTH_CHECK(310, 10, ChronoUnit.MINUTES, emptyList(), IN_CLUSTER),
Hey Truna, we have to update this also fetchLastBatchJobScheduledTime,
Change this to hourly right not its MINUTE. 
We should run it for only last 1 hr, What I mean is if job has not ran for 6 hrs so we don't have to run for all 6 hrs, just last 1 hr will be enough.  Like this
if (null != instant
        && ImmutableSet.of(BatchJobBucket.OUT_OF_CLUSTER, BatchJobBucket.OUT_OF_CLUSTER_ECS)
               .contains(batchJobType.getBatchJobBucket())
        && !ImmutableSet.of(BatchJobType.AWS_ECS_CLUSTER_SYNC, BatchJobType.AWS_ECS_SERVICE_RECOMMENDATION)
                .contains(batchJobType)) {
      Instant startInstant = Instant.now().minus(2, ChronoUnit.HOURS).truncatedTo(ChronoUnit.HOURS);
      instant = startInstant.isAfter(instant) ? startInstant : instant;
    }

2022-05-18 18:37 UTC, hitesharinga commented on 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/DelegateHealthCheckTasklet.java
> +          lastReceivedPublishedMessageDao.getLastReceivedTimeForClusters(accountId, clusterIdsBatch);
One optimisation we can do is get last received data for only healthy delegates.

2022-05-18 18:37 UTC, hitesharinga commented on 280-batch-processing/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java
> +  DELEGATE_HEALTH_CHECK(310, 10, ChronoUnit.MINUTES, emptyList(), IN_CLUSTER),
Also first time it should run for last 1 hr. When you test on NG delete everything from BJSD for this job and then run.

2022-05-26 19:46 UTC, merged