[feat]: [PL-P24523] ldap changes
harness/harness-core pull request #32967
Opened 2022-05-10 07:19 UTC by pbarapatre10

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-11 09:37 UTC, mdmilic requested changes
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32967)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 331 at r5](https://reviewable.io/reviews/harness/harness-core/32967#-N1mTWNt4nRt7kXllZMq:-N1mTWNt4nRt7kXllZMr:b-hbuvb7) ([raw file](https://github.com/harness/harness-core/blob/2ccf9f1af0edc9c5c8f09fdb1ef72cb9bf886a60/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L331)):*
> ```Java
>   GIT_SIMPLIFICATION,
>   CIE_HOSTED_BUILDS,
>   LDAP_SECRET_AUTH,
> ```

You can only add enums at the end, not in the middle if enum needs to be serialized. Not backward compatible. 
___
*[`970-api-services-beans/src/main/java/software/wings/settings/SettingVariableTypes.java` line 297 at r5](https://reviewable.io/reviews/harness/harness-core/32967#-N1mTd8aCaMQLHl7UrVt:-N1mTd8aCaMQLHl7UrVu:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/2ccf9f1af0edc9c5c8f09fdb1ef72cb9bf886a60/970-api-services-beans/src/main/java/software/wings/settings/SettingVariableTypes.java#L297)):*
> ```Java
>   SSO_SAML("SSO SAML"),
> 
>   LDAP("LDAP"),
> ```

same


<!-- Sent from Reviewable.io -->

2022-05-11 09:38 UTC, mdmilic commented
Please follow codebase hashcheck checklist and answer the questions here in PR comments or description to get approval for hash change
https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist

2022-06-09 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=32967) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=32967) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: pbarapatre10<br/>:x: boopesh007<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=32967) it.</sub>

2022-08-01 20:46 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 6 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/32967)

2022-08-15 08:17 UTC, closed without merging