[PLG-787]: NG License API in batch processing
harness/harness-core pull request #33079
Opened 2022-05-11 21:32 UTC by hitesharinga

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-12 19:20 UTC, hitesharinga commented on 930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/LicenseResource.java
> +      @Parameter(
remove this

2022-05-12 19:20 UTC, hitesharinga commented on 930-ng-core-clients/src/main/java/io/harness/utils/RestCallToNGManagerClientUtils.java
> +        log.error("request {}", request.request());
remove this

2022-05-12 19:23 UTC, hitesharinga commented
trigger messagecheck

2022-05-16 04:29 UTC, nikunj-badjatya requested changes

2022-05-16 04:29 UTC, nikunj-badjatya commented on 280-batch-processing/src/main/java/io/harness/batch/processing/shard/AccountShardService.java
> +      return RestCallToNGManagerClientUtils.execute(moduleLicensesByModuleType);
Thoughts on this @hitesharinga , @svmav ?

2022-05-16 18:52 UTC, hitesharinga commented on 280-batch-processing/src/main/java/io/harness/batch/processing/shard/AccountShardService.java
> +      return RestCallToNGManagerClientUtils.execute(moduleLicensesByModuleType);
Sounds good. I will add that. 
Right now its both NG manager and CG, I can add that when we will remove CG.

2022-05-17 03:56 UTC, nikunj-badjatya commented on 280-batch-processing/src/main/java/io/harness/batch/processing/shard/AccountShardService.java
> +      return RestCallToNGManagerClientUtils.execute(moduleLicensesByModuleType);
cool

2022-05-17 03:56 UTC, nikunj-badjatya reviewed
> Reviewed 17 of 19 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33079)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-17 03:56 UTC, nikunj-badjatya approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33079)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-05-17 03:59 UTC, merged