[PL-25126]: service layer integration of create branch method
harness/harness-core pull request #33098
Opened 2022-05-12 07:57 UTC by bhavya181

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-16 08:03 UTC, mohitg0795 commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/33098#-N2At8rG96Ui2JhgGzY5:-N2At8rHDigfouZphJ1F:b-voyykj) ([raw file](https://github.com/harness/harness-core/blob/2dccdcb59cfe21ab4826cbc0783b5e2058193f77/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java#L26)):*
> ```Java
>   BRANCH_LIST_WITH_DEFAULT_BRANCH,
>   REPOSITORY_DETAILS,
>   CREATE_NEW_BRANCH
> ```

Lets make it CREATE_BRANCH_V2, otherwise it becomes confusing whats "CREATE_BRANCH" and "CREATE_NEW_BRANCH" which are essentially the same.


<!-- Sent from Reviewable.io -->

2022-05-16 11:02 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098)* status: 14 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/33098#-N2At8rG96Ui2JhgGzY5:-N2BX7mI2difNU1nKCmi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2dccdcb59cfe21ab4826cbc0783b5e2058193f77/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm/GitRefType.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets make it CREATE_BRANCH_V2, otherwise it becomes confusing whats "CREATE_BRANCH" and "CREATE_NEW_BRANCH" which are essentially the same.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-16 11:05 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 13 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098#-:-N2BXvNi5MnrEhDwdGTi:bnfp4nl)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-16 11:57 UTC, DeepakPatankar requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 699 at r3](https://reviewable.io/reviews/harness/harness-core/33098#-N2Bicps6cPEYKTKJ2hs:-N2Bicps6cPEYKTKJ2ht:b-e99igy) ([raw file](https://github.com/harness/harness-core/blob/4162d57c769f0d8ad15bf32b332d75b7785ad038/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L699)):*
> ```Java
>       return CreateBranchResponse.parseFrom(scmGitRefTaskResponseData.getCreateBranchResponse());
>     } catch (InvalidProtocolBufferException e) {
>       String errorMsg = String.format(errorMessage, "create branch", scope.getAccountIdentifier(),
> ```

rename errorMessage to errorFormat


<!-- Sent from Reviewable.io -->

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateBranchScmApiErrorHandler.java
> +      "Please check the requested Bitbucket repository / base branch, if they exist or not.";
Please check if the requested Bitbucket repository or base branch exists.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateBranchScmApiErrorHandler.java
> +      + "2. The given base branch does not exists.";
These are possible reasons for?

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorHints.java
> -  public static final String INVALID_CREDENTIALS = "Please check your bitbucket credentials.";
Please change the casing to Bitbucket across all the error messages.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorHints.java
> +  public static final String INVALID_CREDENTIALS = "Please check your Bitbucket credentials if they are valid or not.";
Please check if your Bitbucket credentials are valid.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorHints.java
> +  public static final String REPO_NOT_FOUND = "Please check if requested Bitbucket repository exists or not.";
Please check if the requested Bitbucket repository exists.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java
> -  public static final String CREATE_BRANCH_FAILED = "The requested branch could not be created on Github. ";
Let's provide a reason for such error messages.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java
> +      "Please check the requested base branch if it exists and new branch name, if it is valid and does not exists.";
Refer to similar review comment above.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java
> +      + "3. The given base branch does not exists.";
Refer to previous comments.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java
> +      "Please check the requested Github base branch, if it exists or not.";
Refer to previous comments.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImplTest.java
> +    String errorMessage = "Repo not exist";
Repo does not exist.

2022-05-16 12:10 UTC, rashminandasahoo commented on 136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImplTest.java
> +    String errorMessage = "Repo not exist";
Refer to previous comments.

2022-05-16 13:37 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateBranchScmApiErrorHandler.java
> +      + "2. The given branch name is invalid.";
Below is the whole error message shown to user, you can check that this string is explanation and hint is there above you asked for.

Please check that the requested Bitbucket branch name is valid and does not already exist.
The requested branch could not be created on Bitbucket. Possible reasons can be:
1. A branch with given name already exists in the remote Bitbucket repository.
2. The given branch name is invalid.

2022-05-16 13:40 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorHints.java
> +  public static final String REPO_NOT_FOUND = "Please check if requested Bitbucket repository exists or not.";
done

2022-05-16 13:40 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/ScmErrorHints.java
> -  public static final String INVALID_CREDENTIALS = "Please check your bitbucket credentials.";
this is deleted

2022-05-16 13:40 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateBranchScmApiErrorHandler.java
> +      "Please check the requested branch name if it is valid and does not exists.";
done

2022-05-16 13:41 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateBranchScmApiErrorHandler.java
> +  public static final String CREATE_BRANCH_FAILED_MESSAGE = "The requested branch could not be created on Bitbucket. ";
so, this  a single string, which is combined with explanation, that is provoided below

2022-05-16 13:41 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java
> -  public static final String CREATE_BRANCH_FAILED = "The requested branch could not be created on Github. ";
explained above

2022-05-16 13:41 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java
> +      "Please check the requested base branch if it exists and new branch name, if it is valid and does not exists.";
done

2022-05-16 13:41 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java
> +      "Please check the requested Github base branch, if it exists or not.";
done

2022-05-16 13:41 UTC, bhavya181 commented on 136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImplTest.java
> +    String errorMessage = "Repo not exist";
this is a test, so does not matter, it's for internal use only

2022-05-16 13:54 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098)* status: 19 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 699 at r3](https://reviewable.io/reviews/harness/harness-core/33098#-N2Bicps6cPEYKTKJ2hs:-N2C7eLi5UYJ1bGfgMgf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4162d57c769f0d8ad15bf32b332d75b7785ad038/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L699)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

rename errorMessage to errorFormat
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-16 14:14 UTC, rashminandasahoo submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 13 files at r1, 4 of 7 files at r2, 3 of 6 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098#-:-N2CD6zS0lZxsRCJewAi:bnfp4nl)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-17 07:57 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 6 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098#-:-N2G0OgmDLegsaLsi9--:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-17 08:09 UTC, DeepakPatankar reviewed
> Reviewed 5 of 13 files at r1, 4 of 7 files at r2, 3 of 6 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-17 08:09 UTC, DeepakPatankar approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-17 08:12 UTC, abhinav-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-17 08:13 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33098#-:-N2G3zTS7Dx8BOpe3bIj:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-17 08:14 UTC, merged