[feat]: [PIE-3765]: Add API to get Input Set by ID regardless of type
harness/harness-core pull request #33234
Opened 2022-05-17 04:59 UTC by namanvermah

2022-05-17 05:57 UTC, naidu-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33234#-:-N2Fa-oq8dc2qdVF_HEE:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-17 06:12 UTC, archit-harness requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33234)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetByIDResponseDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/33234#-N2Fd-_ZA5EzYZ-UGiJY:-N2Fd-_ZA5EzYZ-UGiJZ:b-6w6lrm) ([raw file](https://github.com/harness/harness-core/blob/1cbc892c4edafa659adeec366ad5da6df7dbc3c1/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetByIDResponseDTO.java#L23)):*
> ```Java
> @JsonInclude(JsonInclude.Include.NON_NULL)
> @ApiModel("InputSetByIDResponse")
> public class InputSetByIDResponseDTO {
> ```

@Schema missing and on fields as well and its inner fields with description, reason its a customer endpoint else mark the API as hidden if not customer usable



_Code quote:_
```Java
nputSetByIDResponseDTO
```


<!-- Sent from Reviewable.io -->

2022-05-17 06:13 UTC, namanvermah reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33234)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetByIDResponseDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/33234#-N2Fd-_ZA5EzYZ-UGiJY:-N2Fd_dm-FUXBXK5ZyHS:by5cbpj) ([raw file](https://github.com/harness/harness-core/blob/1cbc892c4edafa659adeec366ad5da6df7dbc3c1/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetByIDResponseDTO.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@Schema missing and on fields as well and its inner fields with description, reason its a customer endpoint else mark the API as hidden if not customer usable
</blockquote></details>

The API is marked as hidden yes


<!-- Sent from Reviewable.io -->

2022-05-17 06:15 UTC, archit-harness approved these changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33234)* status: :shipit: complete! ✓

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetByIDResponseDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/33234#-N2Fd-_ZA5EzYZ-UGiJY:-N2Fe-fmEcRCtmBQbjPx:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1cbc892c4edafa659adeec366ad5da6df7dbc3c1/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetByIDResponseDTO.java#L23)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

The API is marked as hidden yes
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-17 12:22 UTC, harshjain12 commented on 800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java
> +    Optional<InputSetEntity> inputSetEntity = pmsInputSetService.get(
can we make it list

2022-05-17 12:26 UTC, harshjain12 commented on 800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetByIDResponseDTO.java
> +public class InputSetByIDResponseDTO {
move it to common module

2022-05-17 12:26 UTC, harshjain12 commented
validation code can also be moved to common module

2022-05-18 07:24 UTC, namanvermah commented
Closing this because this API is not what triggers actually need. The merge call can suffice all usecases

2022-05-18 07:24 UTC, closed without merging