[PL-25262]: changes in entity and entity metadata
harness/harness-core pull request #33258
Opened 2022-05-17 10:26 UTC by ujjawal-harness

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-17 11:03 UTC, scottyw requested changes

2022-05-17 11:03 UTC, scottyw commented on 120-ng-manager/src/main/java/io/harness/ng/opa/OpaServiceImpl.java
> +      String entityMetadata = getEntityMetadataString(identifier);
The overall structure makes total sense to me, but the value here should be the human-friendly name of the thing rather than the identifier. The "entityMetadata->entityName" value is what we display in the UI.

2022-05-20 11:53 UTC, ujjawal-harness commented
trigger messagecheck

2022-05-20 11:57 UTC, scottyw requested changes

2022-05-20 11:57 UTC, scottyw commented on 120-ng-manager/src/main/java/io/harness/ng/opa/OpaServiceImpl.java
> +      String entityMetadata = getEntityMetadataString(identifier);
This is still passing the identifer rather than the name?

2022-05-20 12:01 UTC, scottyw approved these changes

2022-05-20 12:01 UTC, scottyw commented on 120-ng-manager/src/main/java/io/harness/ng/opa/OpaServiceImpl.java
> +      String entityMetadata = getEntityMetadataString(identifier);
We had a zoom call - the identifier and the name are deliberately the same in this context.

2022-05-20 12:06 UTC, scottyw reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33258)* status: 1 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-20 12:08 UTC, scottyw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33258#-:-N2WMXfm7v03400urYHo:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-20 12:15 UTC, DeepakPatankar approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33258)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-20 12:15 UTC, boopesh007 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33258)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-20 12:15 UTC, merged