[feat]: [CDS-37344] : Add AWS support for infra definition
harness/harness-core pull request #33267
Opened 2022-05-17 12:19 UTC by vitsafronovici

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-18 10:50 UTC, vitsafronovici commented
trigger compile

2022-05-18 10:59 UTC, vitsafronovici commented
trigger checkstyle

2022-05-27 12:28 UTC, acasian-harness reviewed
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N34SfJXAHY1IjHnn-FY:-N34SfJXAHY1IjHnn-FZ:b-7ds1z4) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L123)):*
> ```Java
> 
>         boolean useAutoScalingGroup = Boolean.TRUE
>             == ParameterFieldHelper.getParameterFieldValue(sshWinRmAwsInfrastructure.getUseAutoScalingGroup());
> ```

i think there is a helper method for boolean `ParameterFieldHelper#getBooleanParameterFieldValue()`
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 274 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N34SrmD-ibzTufNuf2s:-N34SrmD-ibzTufNuf2t:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L274)):*
> ```Java
> 
>     boolean useAutoScalingGroup =
>         Boolean.TRUE == ParameterFieldHelper.getParameterFieldValue(infrastructure.getUseAutoScalingGroup());
> ```

same here


<!-- Sent from Reviewable.io -->

2022-05-30 11:01 UTC, ivan-83 requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JLDrsBbrJryBy01bN:-N3JLDrsBbrJryBy01bO:bs5n0ur) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L128)):*
> ```Java
>     List<AwsInstance> instances = awsHelperService.filterHosts(connectorRef, filterDTO.isWinRm(), filterDTO.getRegion(),
>         filterDTO.getVpcIds(), filterDTO.getTags(), filterDTO.getAutoScalingGroupName());
>     List<String> result = Objects.isNull(instances)
> ```

Minor - we are usually using EmptyPredicate to deal with list.  
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JQWtk6xzTCM1_ybrC:-N3JQWtk6xzTCM1_ybrD:b-hpb6ip) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java#L32)):*
> ```Java
> @OwnedBy(CDP)
> @Schema(name = "AwsListInstancesFilter", description = "Properties of the Aws Instance list")
> public class AwsListInstancesFilterDTO {
> ```

I suggest to move this class to 125 next-gen in package io.harness.cdng.aws.resources.dto .Pls create package resources and dto. Also I think we should move AwsResourceService and AwsResourceServiceImpl to  io.harness.cdng.aws.resources.service and stay empty io.harness.cdng.aws for Manager AWS States. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JWn6N2k0uZyM69Of2:-N3JWn6N2k0uZyM69Of3:b-fezhvm) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java#L34)):*
> ```Java
> public class AwsListInstancesFilterDTO {
>   @ApiModelProperty(required = true) @NotBlank private String region;
>   private String autoScalingGroupName;
> ```

Minor - Schema for fields. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/InfraMapping.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JXj_j72uoLznIfvIP:-N3JXj_j72uoLznIfvIQ:bk1y0ty) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/InfraMapping.java#L29)):*
> ```Java
>   , @JsonSubTypes.Type(value = K8sGcpInfrastructure.class, name = "kubernetes-gcp"),
>       @JsonSubTypes.Type(value = PdcInfrastructure.class, name = "pdc"),
>       @JsonSubTypes.Type(value = SshWinRmAzureInfrastructure.class, name = "ssh-winrm-azure"),
> ```

Minor - should this be ssh-win-rm-aws to follow the same syntax 



_Suggestion:_
```Java
sshWinRmAws
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/AwsInstanceFilter.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JYAbjDdDFKxzQLHSY:-N3JYAbjDdDFKxzQLHSZ:b-bwg83t) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/AwsInstanceFilter.java#L19)):*
> ```Java
> @OwnedBy(CDP)
> @Data
> public class AwsInstanceFilter {
> ```

Quick question, why this is the part of yaml package? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JZ2IP81zhlRhZKj1O:-N3JZ2IP81zhlRhZKj1P:bhni3rn) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L63)):*
> ```Java
>     List<AwsInstance> result = new ArrayList<>();
> 
>     List<String> instanceIds =
> ```

Minor - if instanceIds is null return emptyList.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JZUiU51R4YrpcxmMi:-N3JZUiU51R4YrpcxmMj:bz0om3b) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L97)):*
> ```Java
>     } catch (Exception e) {
>       log.error("Exception getInstanceIds", e);
>       throw new InvalidRequestException(ExceptionUtils.getMessage(e), e);
> ```

Do we have some AWS Harness wrapper exception to throw here?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JZbOP1AM13pL7MpZs:-N3JZbOP1AM13pL7MpZt:buhp3fj) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L101)):*
> ```Java
>   }
> 
>   private AwsInternalConfig getAwsInternalConfig(AwsTaskParams awsTaskParams) {
> ```

Try to find AWS helper class where we already have this method 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JZxZBCmU6IHh5LMCZ:-N3JZxZBCmU6IHh5LMC_:buhp3fj) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L108)):*
> ```Java
>   }
> 
>   private void decryptRequestDTOs(AwsTaskParams awsTaskParams) {
> ```

Try to find AWS helper class where we already have this method 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3J_5w22ECRI09gtf9P:-N3J_5w22ECRI09gtf9Q:b-wsiv0o) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L119)):*
> ```Java
> 
>   @VisibleForTesting
>   AmazonAutoScalingClient getAmazonAutoScalingClient(Regions region, AwsInternalConfig awsConfig) {
> ```

Also the same, move this to some common class. See where we are creating other client.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3Ja4NUE0z97zJTh42S:-N3Ja4NUE0z97zJTh42T:b-1n4c5o) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L116)):*
> ```Java
>     } catch (Exception e) {
>       log.error("Exception getListInstances", e);
>       throw new InvalidRequestException(ExceptionUtils.getMessage(e), e);
> ```

Just to check do we have AWS Harness wrapper exception. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JbPa0B1pOWxRYrVW1:-N3JbPa1EEf5mSZF2y5s:bpb374i) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstanc [...]

2022-06-01 07:58 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/AwsInstanceFilter.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JYAbjDdDFKxzQLHSY:-N3TGHFtE6h91ymHmIuR:b9g6jff) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/AwsInstanceFilter.java#L19)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Quick question, why this is the part of yaml package? 
</blockquote></details>

this is a field used in SshWinRmAwsInfrastructure


<!-- Sent from Reviewable.io -->

2022-06-01 07:59 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JLDrsBbrJryBy01bN:-N3TG_UV3-RtQUx8D0Q5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L128)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - we are usually using EmptyPredicate to deal with list.  
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JWn6N2k0uZyM69Of2:-N3TGdky7bJc14D0BYD3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java#L34)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Schema for fields. 
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N34SfJXAHY1IjHnn-FY:-N3TGf_aBVgCnucQzKPW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L123)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i think there is a helper method for boolean `ParameterFieldHelper#getBooleanParameterFieldValue()`
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 274 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N34SrmD-ibzTufNuf2s:-N3TGh0uA3gy4wcGS2rv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L274)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same here
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/InfraMapping.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JXj_j72uoLznIfvIP:-N3TGjWc8OLTA826QmB6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/InfraMapping.java#L29)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - should this be ssh-win-rm-aws to follow the same syntax 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-01 08:13 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JZbOP1AM13pL7MpZs:-N3TJySc0trHdr7G9hQ2:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L101)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Try to find AWS helper class where we already have this method 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-01 08:14 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JZxZBCmU6IHh5LMCZ:-N3TK4_bDFFZvPJMAdwe:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L108)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Try to find AWS helper class where we already have this method 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-01 08:14 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3J_5w22ECRI09gtf9P:-N3TKDSA-yFJ62GMsv6k:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L119)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Also the same, move this to some common class. See where we are creating other client.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-01 08:31 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JZUiU51R4YrpcxmMi:-N3TO4YHCsewL2fHmBdW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListASGInstancesDelegateTaskHelper.java#L97)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we have some AWS Harness wrapper exception to throw here?
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3Ja4NUE0z97zJTh42S:-N3TO1zM0EfemKTvFI8O:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L116)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Just to check do we have AWS Harness wrapper exception. 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-01 12:15 UTC, ivan-83 approved these changes
LGTM wit minor comments which up to you regarding implementation.  

> Reviewed 3 of 30 files at r1, 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267#-:-N3UB7oc24MYd1LYGy-B:btxp8jj)* status: 2. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java` line 91 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U7ikvB70iX9LNHz-k:-N3U7ikvB70iX9LNHz-l:b97leu7) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java#L91)):*
> ```Java
> 
>   /**
>    *
> ```

Minor - missing description
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U87T16bnEEJVttzeI:-N3U87T16bnEEJVttzeJ:b97leu7) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java#L99)):*
> ```Java
> 
>   /**
>    *
> ```

Minor - missing description
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U88Az-k5cZa7bKdmW:-N3U88Az-k5cZa7bKdmX:b97leu7) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java#L106)):*
> ```Java
>   Map<String, String> getTags(IdentifierRef awsConnectorRef, String region);
> 
>   /**
> ```

Minor - missing description
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U9v4j3E_F2Zf3RKX5:-N3U9v4j3E_F2Zf3RKX6:b73xs1l) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java#L50)):*
> ```Java
> @Singleton
> @OwnedBy(CDP)
> public class AwsUtils {
> ```

Minor - this class shouldn't be a part of service/impl package
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3UAHGt3iE0cHKyU4o1:-N3UAHGt3iE0cHKyU4o2:b-4k37ej) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java#L99)):*
> ```Java
>   }
> 
>   public void decryptRequestDTOs(AwsTaskParams awsTaskParams) {
> ```

Minor - this method should accept connector and encryptedDetails
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsListVpcTaskResponse.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3UAc1jArOQSATrH1tX:-N3UAc1jArOQSATrH1tY:b-a0llua) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsListVpcTaskResponse.java#L26)):*
> ```Java
> public class AwsListVpcTaskResponse implements AwsDelegateTaskResponse {
>   private CommandExecutionStatus commandExecutionStatus;
>   private DelegateMetaInfo delegateMetaInfo;
> ```

Should delegateMetaInfo be part of AwsDelegateTaskResponse ?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3UAq2YDV1PhwQbjgH0:-N3UAq2YDV1PhwQbjgH1:b28etp5) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java#L19)):*
> ```Java
>   LIST_IAM_ROLES,
>   CF_LIST_PARAMS,
>   LIST_INSTANCES,
> ```

Minor - Maybe more meaningful name for LIST_INSTANCES


<!-- Sent from Reviewable.io -->

2022-06-01 12:41 UTC, ivan-83 submitted a review, later dismissed
One note related to exception, maybe it is better approach  to have one common exception like AwsSDKException instead of having exceptions per each operations. We can supply error msg to common general exception AwsSDKException which describes what is the error per operation.
Also, AwsSDKException should handle all AmazonServiceException and AmazonClientException exceptions from AWS side. 

We could have more specific AWS exception when we need to catch it and do extra logic for example for AWS authorization (AwsSDKAuthorizationException), but for all of these operation we can reuse the same one with different error msgs.

> Reviewed 16 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267#-:-N3UCqVG2d0ZrOyZQGEd:b-b7azbj)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-03 08:57 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 23 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java` line 91 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U7ikvB70iX9LNHz-k:-N3ckc8z9ztoB9tU_9hw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java#L91)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - missing description
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U87T16bnEEJVttzeI:-N3ckazy4MKSXG-TBhz1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java#L99)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - missing description
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U88Az-k5cZa7bKdmW:-N3ck_Cg6k4Z_WDjjdfF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java#L106)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - missing description
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JbPa0B1pOWxRYrVW1:-N3ckXI8EQaGNBXOshXL:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L120)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - get or list 
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JbBhb50oLSONxX5uu:-N3ckTI1ERopBoRoopxi:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L148)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Check do we have already this method in place.
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JbcPk8F9omQ6iVTgE:-N3ckRKj6NIj5-_Z6LTF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L180)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - put in separate method with self-explained name.
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 181 at r2](https://reviewable.io/reviews/harness/harness-core/33267#-N3JbqTJ-TYUcCT9x6Eo:-N3ckQPg8PiIGbvjLaxA:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8a9b396655f8153aa63d4a8d66a4391b19c0253d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L181)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

the same
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3U9v4j3E_F2Zf3RKX5:-N3cjOYN1C6NLnrUTZmy:b49grqj) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java#L50)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - this class shouldn't be a part of service/impl package
</blockquote></details>

not sure, it was already there
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3UAHGt3iE0cHKyU4o1:-N3cjLC374_EwAEwRHcv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/930-delegate-tasks/src/main/java/software/wings/service/impl/AwsUtils.java#L99)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - this method should accept connector and encryptedDetails
</blockquote></details>

done
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsListVpcTaskResponse.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3UAc1jArOQSATrH1tX:-N3ciGJHDnwkYpavae2p:b-f4rmg5) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsListVpcTaskResponse.java#L26)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should delegateMetaInfo be part of AwsDelegateTaskResponse ?
</blockquote></details>

not sure, but this is how the other responses a structured
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/33267#-N3UAq2YDV1PhwQbjgH0:-N3ciyCI9cg-4gJwmPOG:b-dl5lts) ([raw file](https://github.com/harness/harness-core/blob/3e7932f07c89378cee1ce968dbce311713957780/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java#L19)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Maybe more meaningful name for LIST_INSTANCES
</blockquote></details>

I think this is self explained if enum name is AwsTaskType, then it means AWS instances. This pattern is also in CG


<!-- Sent from Reviewable.io -->

2022-06-05 15:41 UTC, ivan-83 reviewed
We can try to do rebase again or create the new branch and do cherry-pick of your commits. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267#-:-N3oWKyaBBPMU53lAnmJ:bwprr75)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 52 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3oV_Fp6tWCWDtHneX0:-N3oV_Fp6tWCWDtHneX1:bqn2jdv) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L52)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.CDP)
> public class AwsListInstancesDelegateTaskHelper {
> ```

Minor - Rename AwsListInstancesDelegateTaskHelper >> AwsListEC2InstancesDelegateTaskHelper
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3oVHr_3S_jxSr2fJ9Q:-N3oVHr_3S_jxSr2fJ9R:b9vxnce) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java#L19)):*
> ```Java
>   LIST_IAM_ROLES,
>   CF_LIST_PARAMS,
>   LIST_INSTANCES,
> ```

Minor - Rename LIST_INSTANCES >> LIST_EC2_INSTANCES



_Suggestion:_
```Java
LIST_INSTANCES,
```
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/service/impl/aws/model/AwsInstance.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3oW1ywBFU5L-uxGYZA:-N3oW1ywBFU5L-uxGYZB:b-c42hk1) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/950-delegate-tasks-beans/src/main/java/software/wings/service/impl/aws/model/AwsInstance.java#L21)):*
> ```Java
> @Builder
> @OwnedBy(CDP)
> public class AwsInstance implements Serializable {
> ```

Minor - Rename AwsInstance >> AwsEC2Instance


<!-- Sent from Reviewable.io -->

2022-06-06 06:54 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 2 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java` line 105 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3dcoFXEznQHyryqeVK:-N3rmnQiBicBK4J4u-RY:bub4kip) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java#L105)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I guess these are not your changes.
</blockquote></details>

these are mine


<!-- Sent from Reviewable.io -->

2022-06-06 10:24 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 19 file(s) to review. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33267#-N3JQWtk6xzTCM1_ybrC:-N3sXhHr717N2-K-BEPK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2958829bcb8aa86b7f48e4256e4fd8519742bafd/120-ng-manager/src/main/java/io/harness/ng/core/dto/AwsListInstancesFilterDTO.java#L32)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I suggest to move this class to 125 next-gen in package io.harness.cdng.aws.resources.dto .Pls create package resources and dto. Also I think we should move AwsResourceService and AwsResourceServiceImpl to  io.harness.cdng.aws.resources.service and stay empty io.harness.cdng.aws for Manager AWS States. 
</blockquote></details>

done
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3oVHr_3S_jxSr2fJ9Q:-N3sXlwR9Vpt5_Xmp8kJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java#L19)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Rename LIST_INSTANCES >> LIST_EC2_INSTANCES
</blockquote></details>

done
___
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 615 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3dhwy95CwhAo695BVv:-N3sXo4ZEOE5cSfObw5m:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L615)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Check rebase whether it is done properly. 
</blockquote></details>

done
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 509 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3di5lL1XnFr_AsLgzM:-N3sXp7A7P_CHwIUwpQ4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L509)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same, do rebase again.
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java` line 52 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3oV_Fp6tWCWDtHneX0:-N3sXkW7Cv0ma5xZouIy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsListInstancesDelegateTaskHelper.java#L52)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Rename AwsListInstancesDelegateTaskHelper >> AwsListEC2InstancesDelegateTaskHelper
</blockquote></details>

done
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/service/impl/aws/model/AwsInstance.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/33267#-N3oW1ywBFU5L-uxGYZA:-N3sXn7I9Az3C92yb4vl:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bca5a7059a2aebb3797196127d1be4b433a1a6f2/950-delegate-tasks-beans/src/main/java/software/wings/service/impl/aws/model/AwsInstance.java#L21)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Rename AwsInstance >> AwsEC2Instance
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-06 10:24 UTC, vitsafronovici reviewed
done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267#-:-N3sXtJuBLePtHiwnLYe:bb7f2mf)* status: 19 file(s) to review. 6. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-06 10:33 UTC, acasian-harness submitted a review, later dismissed
> Reviewed 9 of 26 files at r3, 6 of 23 files at r4, 10 of 11 files at r5, 19 of 19 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-06 10:35 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267#-:-N3s_SgxEJ9QrGwOEFAr:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-08 11:14 UTC, vitsafronovici commented
trigger compile

2022-06-08 13:35 UTC, acasian-harness submitted a review, later dismissed
> Reviewed 7 of 8 files at r7, 13 of 14 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-08 13:42 UTC, archit-harness reviewed
> Reviewed 1 of 19 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-08 13:54 UTC, bojanmicovic approved these changes
> Reviewed 3 of 30 files at r1, 9 of 26 files at r3, 4 of 23 files at r4, 5 of 11 files at r5, 10 of 19 files at r6, 6 of 8 files at r7, 13 of 14 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-08 13:54 UTC, bojanmicovic submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-08 14:11 UTC, archit-harness reviewed
> Reviewed 1 of 23 files at r4, 1 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-08 14:15 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 19 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-08 19:03 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 3 of 30 files at r1, 9 of 26 files at r3, 4 of 23 files at r4, 6 of 11 files at r5, 10 of 19 files at r6, 7 of 8 files at r7, 13 of 14 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-09 10:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=33267) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=33267) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=33267) it.</sub>

2022-06-09 13:12 UTC, bojanmicovic submitted a review, later dismissed
> Reviewed 1 of 11 files at r5, 1 of 8 files at r7, 1 of 3 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-10 09:06 UTC, archit-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: 10 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-06-10 09:11 UTC, bojanmicovic approved these changes
> Reviewed 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-10 09:11 UTC, acasian-harness submitted a review, later dismissed
> Reviewed 1 of 3 files at r10, 4 of 4 files at r11, 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-10 09:22 UTC, ivan-83 approved these changes
> Reviewed 9 of 19 files at r6, 5 of 8 files at r7, 7 of 14 files at r8, 2 of 4 files at r9, 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33267)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-13 10:55 UTC, merged