[CDS-37734]: Implement deployStack for NG
harness/harness-core pull request #33303
Opened 2022-05-18 10:13 UTC by nassergonzalez

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-18 11:13 UTC, tmacari-harness requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2LmoKv3v6V1qCn1CP0:-N2LmoKw8mmjE02HTGtQ:b-8wq37g) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java#L61)):*
> ```Java
>       CloudformationTaskNGParameters taskNGParameters, String delegateId, String taskId, LogCallback logCallback)
>       throws IOException, TimeoutException, InterruptedException {
>     remainingTimeoutMs = taskNGParameters.getTimeoutInMs() > 0
> ```

is there a scenario when timeout s coming < 0?



_Code quote:_
```Java
long endTime
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2LrHKE15Klrm2EPia4:-N2LrHKE15Klrm2EPia5:b5o8eoo) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java#L310)):*
> ```Java
>     DeployStackResult deployStackResult = awsCloudformationClient.deployStack(
>         request.getRegion(), deployStackRequest, awsInternalConfig, Duration.ofMillis(endTime), logCallback);
>     if (deployStackResult.getStatus() == Status.FAILURE) {
> ```

can we have here the same logic as in CG?
``` if (deployStackResult.getStatus() == Status.FAILURE) {
      throw new InvalidRequestException(
          format("CF Change set creation failed: %s", deployStackResult.getStatusReason()));
    }
```
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGResponse.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2LgrU12DNGRGUruqf6:-N2LgrU12DNGRGUruqf7:b-ckmno1) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGResponse.java#L29)):*
> ```Java
>   CloudFormationCommandNGResponse cloudFormationCommandNGResponse;
>   CommandExecutionStatus commandExecutionStatus;
>   boolean stackSkipped;
> ```

maybe stackUpdated?


<!-- Sent from Reviewable.io -->

2022-05-18 11:33 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java
> +      populateCloudformationTaskNGResponse(builder, null, false);
I think that when we do an update, we always have an existing stack, even if creation of changeSet failed for any reason.

2022-05-18 12:19 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2M5OMw3MPhKTsb9QVT:-N2M5OMw3MPhKTsb9QVU:bwhlyto) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java#L172)):*
> ```Java
>         (CloudFormationCreateStackNGResponse) cloudformationTaskNGResponse.getCloudFormationCommandNGResponse();
> 
>     if (!cloudformationTaskNGResponse.isStackSkipped()) {
> ```

we should always save cloudformationIngeritOutput it is use also when we want to use Delete stack inherited.
We shouldn't save cloudformationConfig if there was no update


<!-- Sent from Reviewable.io -->

2022-05-18 13:44 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 1 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2M5OMw3MPhKTsb9QVT:-N2MPPd7AQif7Pf-zemG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java#L172)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we should always save cloudformationIngeritOutput it is use also when we want to use Delete stack inherited.
We shouldn't save cloudformationConfig if there was no update
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2LmoKv3v6V1qCn1CP0:-N2MFoAa41j9UDRBeNAG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java#L61)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

is there a scenario when timeout s coming < 0?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2LrHKE15Klrm2EPia4:-N2MG2tq8VE6ph4hjaeB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java#L310)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

can we have here the same logic as in CG?
``` if (deployStackResult.getStatus() == Status.FAILURE) {
      throw new InvalidRequestException(
          format("CF Change set creation failed: %s", deployStackResult.getStatusReason()));
    }
```
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java` line 313 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2Le4-erMBFO_1o97-7-r1-313:-N2MG3MYCEz6WEDtdj3C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandler.java#L313)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

Regarding the third parameter (false). I think that when we do an update, we always have an existing stack, even if creation of changeSet failed for any reason.
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGResponse.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/33303#-N2LgrU12DNGRGUruqf6:-N2MPO2T15V9ObCnfBpL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0a46761f5765924351794d58641d5a81784c1ca/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGResponse.java#L29)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

maybe stackUpdated?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-19 05:57 UTC, vlica-harness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java
> +    assertThat(logCaptor.getAllValues().contains("# Update Successful for stack"));
Hi Nasser, 
It looks strange why we get this log "Update Successful for stack", when we test/assert for failure update.

2022-05-19 08:23 UTC, tmacari-harness reviewed
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/33303#-N2Le4-erMBFO_1o97-8-r2-348:-N2QPCU_CEs4YqlAS2LQ:bh29xjf) ([raw file](https://github.com/harness/harness-core/blob/5a2751759adc0a9b144c105a1836777fd745cedf/930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java#L348)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

Hi Nasser, 
It looks strange why we get this log "Update Successful for stack", when we test/assert for failed (FAILURE) update.
</blockquote></details>

Good catch. It should be 
"assertThat(logCaptor.getAllValues()).contains("# Update Successful for stack");"
and probably it would fail.

Please fix in other places in that test class.


<!-- Sent from Reviewable.io -->

2022-05-19 09:44 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/33303#-N2Le4-erMBFO_1o97-8-r2-348:-N2QhADH9PXf9MNTkO1c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5a2751759adc0a9b144c105a1836777fd745cedf/930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java#L348)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Good catch. It should be 
"assertThat(logCaptor.getAllValues()).contains("# Update Successful for stack");"
and probably it would fail.

Please fix in other places in that test class.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-19 09:59 UTC, vlica-harness submitted a review, later dismissed

2022-05-19 10:09 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-19 13:05 UTC, vlica-harness approved these changes

2022-05-19 13:55 UTC, vlica-harness submitted a review, later dismissed

2022-05-19 14:04 UTC, abhinav-harness submitted a review, later dismissed
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-20 09:51 UTC, abhinav-harness approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-20 09:57 UTC, nassergonzalez reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33303#-:-N2Vtaxq7wcrYTBdbWTH:bnfp4nl)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-20 09:59 UTC, merged