[CDS-36559]: Monitor for zombie workflow execution
harness/harness-core pull request #33404
Opened 2022-05-20 21:45 UTC by Fernando-Dourado

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

2022-05-27 19:36 UTC, Fernando-Dourado commented
trigger messagecheck

2022-05-27 20:19 UTC, Fernando-Dourado commented
trigger messagecheck

2022-05-27 22:09 UTC, Fernando-Dourado commented
trigger checkstyle

2022-05-28 16:22 UTC, abhinav-harness commented on 400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieMonitorHandler.java
> +      }
move core logic out of iterator class

2022-05-30 08:33 UTC, puthrayaharness requested changes

2022-05-30 08:33 UTC, puthrayaharness commented on 400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieMonitorHandler.java
> +  public boolean shouldProcessEntity(WorkflowExecution entity) {
We cannot add this in filter criteria?

2022-05-30 08:33 UTC, puthrayaharness commented on 400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieMonitorHandler.java
> +    sort(stateExecutionInstances);
Please move all this logic to the DB layer. There is no need to sort and fetch this on the app side. DB can take care of this.

2022-05-31 16:59 UTC, Fernando-Dourado commented
A wrong rebase create a hard-to-review PR, closing this one and opening another at https://github.com/harness/harness-core/pull/33737.

2022-05-31 16:59 UTC, closed without merging