[DEL-3998]: implement jwt cache
harness/harness-core pull request #33436
Opened 2022-05-23 10:44 UTC by arpit3107

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

2022-05-27 06:35 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33BYXS3E4iyAi8rv-R:-N33BYXS3E4iyAi8rv-S:b-84wp7w) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L100)):*
> ```Java
>       encryptedJWT = EncryptedJWT.parse(tokenString);
>     } catch (ParseException e) {
>       throw new InvalidTokenException("Invalid delegate token format", USER_ADMIN);
> ```

we can even move this step after cache lookup



_Code quote:_
```Java
    EncryptedJWT encryptedJWT;
    try {
      encryptedJWT = EncryptedJWT.parse(tokenString);
    } catch (ParseException e) {
      throw new InvalidTokenException("Invalid delegate token format", USER_ADMIN);
    }
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33BQQa0snrzwMdHXqG:-N33BQQa0snrzwMdHXqH:b-5w1xmo) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L103)):*
> ```Java
>     }
> 
>     String tokenHash = DigestUtils.md5Hex(tokenString);
> ```

final string
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CmbnCKYf7p-RI6j8:-N33Be6HEiV_xGwPHPGY:b-ec76jd) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L106)):*
> ```Java
>     // first validate it from DelegateJWTCache
>     if (delegateJWTCacheHelper.validateDelegateJWTString(tokenHash)) {
>       return;
> ```

Ideally cache should only be for storing/fetching key-values.. It shouldn't do logic of validation and all. Can you move validation logic here ?
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33DYSG1ACi4R0hD4w_:-N33DYSG1ACi4R0hD4wa:bfqf5wr) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L146)):*
> ```Java
>     try {
>       JWTClaimsSet jwtClaimsSet = encryptedJWT.getJWTClaimsSet();
>       long validUntil = jwtClaimsSet.getExpirationTime().getTime();
> ```

final long



_Code quote:_
```Java
long
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33DIacDomnVbPsS2o2:-N33DIacDomnVbPsS2o3:b-ezrdl8) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L149)):*
> ```Java
>       if (System.currentTimeMillis() > validUntil) {
>         log.error("Delegate {} is using EXPIRED delegate token. DelegateId: {}", jwtClaimsSet.getIssuer(), delegateId);
>         delegateJWTCacheHelper.setDelegateJWTCache(tokenHash, false, 0);
> ```

Why do we need to store expired jwt in cache ?
Also we should check for token expiry at first place before decrypting it. Consider moving this check just after cache lookup fails



_Code quote:_
```Java
 delegateJWTCacheHelper.setDelegateJWTCache(tokenHash, false, 0);
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CDbv0XIb4PoaU0tD:-N33CDbv0XIb4PoaU0tE:b-ygz0cv) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L25)):*
> ```Java
> @OwnedBy(DEL)
> public class DelegateJWTCacheHelper {
>   // cache is for storing serialised JWT directly (since agent will be sending the same jwt for 25 mins)
> ```

Let remove such low level details here.



_Code quote:_
```Java
 (since agent will be sending the same jwt for 25 mins)
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33C9WLBFz25a08-vQ0:-N33C9WLBFz25a08-vQ1:b-4142o0) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L30)):*
> ```Java
>       Caffeine.newBuilder().maximumSize(50000).expireAfterWrite(15, TimeUnit.MINUTES).build();
> 
>   // setting validUntil doesnt makes sense, if token is not valid
> ```

Didn't got this comment here



_Code quote:_
```Java
  // setting validUntil doesnt makes sense, if token is not valid
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CctH3ZgjM20g5KRr:-N33CctH3ZgjM20g5KRs:bl19w9j) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L43)):*
> ```Java
>     } else if (!delegateJWTCacheValueObject.isValid()) {
>       // Not great, but, if token is not valid, then always send RevokedTokenException to freeze delegate. Don't send
>       // InvalidRequestException
> ```

Please rephrase the comment. Avoid using expressions here.



_Code quote:_
```Java
      // Not great, but, if token is not valid, then always send RevokedTokenException to freeze delegate. Don't send
      // InvalidRequestException
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CVHJ5b-xUC-HTqdy:-N33CVHJ5b-xUC-HTqdz:b-mizmck) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java#L18)):*
> ```Java
> @OwnedBy(HarnessTeam.DEL)
> public class DelegateJWTCacheValueObject {
>   private final boolean isValid;
> ```

Consider renaming isActive, here and elsewhere



_Code quote:_
```Java
isValid
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CYpTANsx0hle7aTh:-N33CYpTANsx0hle7aTi:b-a9j5wd) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java#L19)):*
> ```Java
> public class DelegateJWTCacheValueObject {
>   private final boolean isValid;
>   private final long validUntil;
> ```

expiryInMillis


<!-- Sent from Reviewable.io -->

2022-05-27 07:52 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 3 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33BYXS3E4iyAi8rv-R:-N33Ecte8Jlc487jMj7m:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L100)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we can even move this step after cache lookup
</blockquote></details>

done
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33BQQa0snrzwMdHXqG:-N33EfLYCn3nc8BePOv3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L103)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

final string
</blockquote></details>

done
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CmbnCKYf7p-RI6j8:-N33Egmu338kCdqbejGq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L106)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Ideally cache should only be for storing/fetching key-values.. It shouldn't do logic of validation and all. Can you move validation logic here ?
</blockquote></details>

done
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33DYSG1ACi4R0hD4w_:-N33Ekvm-RYi8GC4AE_O:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L146)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

final long
</blockquote></details>

done
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33DIacDomnVbPsS2o2:-N33GZfA2zhsQhVRlwhZ:bh15jni) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L149)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Why do we need to store expired jwt in cache ?
Also we should check for token expiry at first place before decrypting it. Consider moving this check just after cache lookup fails
</blockquote></details>

incase delegate is sending some expired jwt, then even though we send a freeze command to agent, but it takes some time to actually freeze delegate, and by that time it will keep sending calls for next 20-30 calls.

Payload is not visible unless jwt decryption has been done. And jwt expiry is a part of payload.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CDbv0XIb4PoaU0tD:-N33HSok9PY-xV406r2J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L25)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Let remove such low level details here.
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33C9WLBFz25a08-vQ0:-N33MrGCD8ZH29JPcqiU:bmsur26) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L30)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Didn't got this comment here
</blockquote></details>

will remove this comment.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CctH3ZgjM20g5KRr:-N33MyfZ45sRQmPAv3qm:b44u25) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L43)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Please rephrase the comment. Avoid using expressions here.
</blockquote></details>

😅
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CVHJ5b-xUC-HTqdy:-N33N4wy7L1JwcP4HDKs:bmbswpg) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java#L18)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Consider renaming isActive, here and elsewhere
</blockquote></details>

We are storing invalid (revoked and expired)  tokens also.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CYpTANsx0hle7aTh:-N33N5Je1fVdA6Mvmlip:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java#L19)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

expiryInMillis
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-27 14:26 UTC, mdmilic reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 3 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33DIacDomnVbPsS2o2:-N34tL2_-_Ry1ytCVD7X:b8ls6ax) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L149)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

incase delegate is sending some expired jwt, then even though we send a freeze command to agent, but it takes some time to actually freeze delegate, and by that time it will keep sending calls for next 20-30 calls.

Payload is not visible unless jwt decryption has been done. And jwt expiry is a part of payload.
</blockquote></details>

@arpit3107, payload should not be encrypted, so you can check the expiry time without decrypting the token (but you still need to deserialize the payload). Only the third part of the token which maintains the integrity (makes sure that the token was not tampered) is encrypted. 
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/33436#-N34sWNfEfp5gxlEhWPG:-N34sWNfEfp5gxlEhWPH:bhsy2yp) ([raw file](https://github.com/harness/harness-core/blob/4ae3f0852cfdaa0f33cdec422b9ed6dd5664e003/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L76)):*
> ```Java
> @TargetModule(HarnessModule._420_DELEGATE_SERVICE)
> public class DelegateTokenAuthenticatorImpl implements DelegateTokenAuthenticator {
>   @Inject private HPersistence persistence;
> ```

Make these final and use ctor injection



_Code quote:_
```Java
  @Inject private HPersistence persistence;
  @Inject private DelegateTokenCacheHelper delegateTokenCacheHelper;
  @Inject private DelegateJWTCacheHelper delegateJWTCacheHelper;
```


<!-- Sent from Reviewable.io -->

2022-05-27 15:58 UTC, raghuAtWings commented
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/33436#-N35DsTFCpV4Yhmk-7u3:-N35DsTFCpV4Yhmk-7u4:blz6acr) ([raw file](https://github.com/harness/harness-core/blob/4ae3f0852cfdaa0f33cdec422b9ed6dd5664e003/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L22)):*
> ```Java
> public class DelegateJWTCacheHelper {
>   private final Cache<String, DelegateJWTCacheValueObject> delegateJWTCache =
>       Caffeine.newBuilder().maximumSize(50000).expireAfterWrite(15, TimeUnit.MINUTES).build();
> ```

how about having delegate send the same token for 30 mins and we caching it for 25 mins in manager? Also why max size is 50k, if we have lets say 100k max, whats the max memory consumption? 


<!-- Sent from Reviewable.io -->

2022-05-27 15:59 UTC, raghuAtWings reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-31 05:32 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 2 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/33436#-N3NYMhJAvb0yJ-wWz3x:-N3NYK34CBnxyzBLgWzM:b-svdr1p) ([raw file](https://github.com/harness/harness-core/blob/48ce805ca1ce075094e2bf8b0a04dca831d222da/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L20)):*
> ```Java
> // TODO: ARPIT record cache hit and miss metrics using OpenCensus
> @OwnedBy(DEL)
> public class DelegateJWTCacheHelper {
> ```

Make this as a singleton
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/33436#-N3N_Nwn6YNMHExMHh1C:-N3N_Nwn6YNMHExMHh1D:b6idjsk) ([raw file](https://github.com/harness/harness-core/blob/48ce805ca1ce075094e2bf8b0a04dca831d222da/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L20)):*
> ```Java
> // TODO: ARPIT record cache hit and miss metrics using OpenCensus
> @OwnedBy(DEL)
> public class DelegateJWTCacheHelper {
> ```

Plan to introduce basic metrics like cache hit/miss/ evict etc, and publish it to gcp dashboard.



_Code quote (from 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java):_
```Java
    } else if (delegateJWTCacheValueObject.getExpiryInMillis() < System.currentTimeMillis()) {
      throw new InvalidRequestException("Unauthorized", EXPIRED_TOKEN, null);
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/33436#-N3Na6SfAYfE1_FWffJu:-N3Na6SfAYfE1_FWffJv:ba3p0da) ([raw file](https://github.com/harness/harness-core/blob/48ce805ca1ce075094e2bf8b0a04dca831d222da/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L20)):*
> ```Java
> // TODO: ARPIT record cache hit and miss metrics using OpenCensus
> @OwnedBy(DEL)
> public class DelegateJWTCacheHelper {
> ```

Consider renaming this class to DelegateJWTCache
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/33436#-N3NYp4l-3mdxiLujj_v:-N3NYp4l-3mdxiLujj_w:bybdxjk) ([raw file](https://github.com/harness/harness-core/blob/48ce805ca1ce075094e2bf8b0a04dca831d222da/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L25)):*
> ```Java
> 
>   public void setDelegateJWTCache(String tokenHash, Boolean isValid, long expiryInMillis) {
>     delegateJWTCache.put(tokenHash, new DelegateJWTCacheValueObject(isValid, expiryInMillis));
> ```

We need to make this threadsafe because
1) multiple threads can write this simultaneously
2) Read/write can coincide.



_Code quote:_
```Java
 delegateJWTCache.put(
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/33436#-N3NaDpj5hXs5mzzswZk:-N3NaDpj5hXs5mzzswZl:bk61vvw) ([raw file](https://github.com/harness/harness-core/blob/48ce805ca1ce075094e2bf8b0a04dca831d222da/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java#L17)):*
> ```Java
> @Data
> @OwnedBy(HarnessTeam.DEL)
> public class DelegateJWTCacheValueObject {
> ```

DelegateJWTCacheValue



_Code quote:_
```Java
DelegateJWTCacheValue
```


<!-- Sent from Reviewable.io -->

2022-06-03 08:48 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 23 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`270-verification/src/main/java/io/harness/app/VerificationAuthFilter.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3br28_7QaW9crpsZOu:-N3br28a2Urr4O6GZbke:b-5h2vsp) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/270-verification/src/main/java/io/harness/app/VerificationAuthFilter.java#L43)):*
> ```Java
>       if (header.contains("Delegate")) {
>         String delegateId = containerRequestContext.getHeaderString("delegateId");
>         String delegateTokenName = containerRequestContext.getHeaderString("delegateTokenName");
> ```

Is CV using delegate auth ? Is this communication between delegate and manager ? If not, than we shouldn't use delegateauth here



_Code quote:_
```Java
 String delegateTokenName = containerRequestContext.getHeaderString("delegateTokenName");
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bryFg5Q6F3IWVF_D2:-N3bryFg5Q6F3IWVF_D3:b-vyrro9) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L98)):*
> ```Java
>   // we should set global context data only for rest calls, because we unset the global context thread only for rest
>   // calls.
>   // We can use delegateTokenName variable to determine whether the delegate is reusing the same jwt or not. And remove
> ```

As discussed we should use separate header for this purpose.



_Code quote:_
```Java
  // We can use delegateTokenName variable to determine whether the delegate is reusing the same jwt or not. And remove
  // it after 1-2 months.
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 105 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bs3GX505sC5FQLn_H:-N3bs3GX505sC5FQLn_I:b-duz532) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L105)):*
> ```Java
>     final String tokenHash = DigestUtils.md5Hex(tokenString);
>     // first validate it from DelegateJWTCache
>     if (validateDelegateJWTFromCache(accountId, tokenHash)) {
> ```

use can choose to validate with this cache only if that new jwt header is set



_Code quote:_
```Java
validateDelegateJWTFromCache(accountId, tokenHash)
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 144 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bs8Zh2j-_EjV1Qhap:-N3bs8Zi2CwCrP4olR6F:bmtb2xf) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L144)):*
> ```Java
>         log.warn("Couldn't parse token", e);
>       }
>       delegateJWTCache.setDelegateJWTCache(tokenHash, delegateTokenName, new DelegateJWTCacheValue(false, 0L));
> ```

This is bad implementation of cache. keep the interface of cache as simple and move all the logic of `delegateTokenName` here during cache calls.



_Code quote:_
```Java
setDelegateJWTCache(tokenHash, delegateTokenName, new DelegateJWTCacheValue(false, 0L));
```
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3cjy4k2_DSFqnt_-WA:-N3cjy4k2_DSFqnt_-WB:b-k2pjop) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L342)):*
> ```Java
>     // cache miss
>     if (delegateJWTCacheValue == null) {
>       delegateMetricsService.recordDelegateJWTCacheMetrics(accountId, DELEGATE_JWT_CACHE_MISS);
> ```

account for cache looksup instead of misses
___
*[`400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml` line 1 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3ciipiB2OzgqA5vzOA:-N3ciipiB2OzgqA5vzOB:b-nv25dc) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml#L1)):*
> ```YAML
> name: Delegate JWT Cache Metrics
> ```

use `auth` instead of jwt here and every in this metric.yaml fiel
___
*[`400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml` line 9 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3civ_c4oJvGlb_31H9:-N3civ_c4oJvGlb_31HA:b-hf6xn6) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml#L9)):*
> ```YAML
>     type: Count
>     unit: "1"
>   - metricName: delegate_jwt_cache_miss
> ```

miss doesn't make sense, we should track total number of lookups


<!-- Sent from Reviewable.io -->

2022-06-08 06:09 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 24 file(s) to review. 1 change requests. 24. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`270-verification/src/main/java/io/harness/app/VerificationAuthFilter.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3br28_7QaW9crpsZOu:-N40teQN9p-hS2zwpyyo:b6c8zhj) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/270-verification/src/main/java/io/harness/app/VerificationAuthFilter.java#L43)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Is CV using delegate auth ? Is this communication between delegate and manager ? If not, than we shouldn't use delegateauth here
</blockquote></details>

this is communication b/w delegate and CV cg. CV cg uses the same logic to validate token. Since this is for delegate hence delegateAuth is needed here.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33DIacDomnVbPsS2o2:-N40usDw1V7pge_mjw96:b6fgwn7) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L149)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

@arpit3107, payload should not be encrypted, so you can check the expiry time without decrypting the token (but you still need to deserialize the payload). Only the third part of the token which maintains the integrity (makes sure that the token was not tampered) is encrypted. 
</blockquote></details>

I agree, but our current implementation is not good, and even payload is encrypted. i have tested that thoroughly.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/33436#-N34sWNfEfp5gxlEhWPG:-N40tz6tBzHyb6A3vxlc:b-hv4qa8) ([raw file](https://github.com/harness/harness-core/blob/4ae3f0852cfdaa0f33cdec422b9ed6dd5664e003/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L76)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Make these final and use ctor injection
</blockquote></details>

i dont remember the exact issue, but there was some problem in this class while using that. and it was not straight forward.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bryFg5Q6F3IWVF_D2:-N40u9lj924Z3Ox7NheJ:bdu3n4w) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L98)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

As discussed we should use separate header for this purpose.
</blockquote></details>

Yes, but then i have send one new authHeaders over 20-30 places. This is being used by CV, events framework and other services. So, i talked to raghu and we agreed that we can reuse this variable for this purpose.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 105 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bs3GX505sC5FQLn_H:-N40uSi93H7es6DnOiNx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L105)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

use can choose to validate with this cache only if that new jwt header is set
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 144 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bs8Zh2j-_EjV1Qhap:-N40uTf9BX6esbN1FeQE:b-g99fyk) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L144)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This is bad implementation of cache. keep the interface of cache as simple and move all the logic of `delegateTokenName` here during cache calls.
</blockquote></details>

I agree, but that is causing lots of if and else in the main validateToken method, which is not easy to read. And this tokenName is temporary, i.e will be removed when all delegates starting reusing the jwt. Then we can simplify this method call
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3cjy4k2_DSFqnt_-WA:-N40v5TIBovQgBi53dEo:bfen7cz) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L342)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

account for cache looksup instead of misses
</blockquote></details>

no, i think it should have both the metrices of cache hit and miss so that we can track if  there are lots of misses instead of hits.
___
*[`400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml` line 1 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3ciipiB2OzgqA5vzOA:-N40vHxT1pqzGTxxnGRz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml#L1)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

use `auth` instead of jwt here and every in this metric.yaml fiel
</blockquote></details>

Done.
___
*[`400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml` line 9 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3civ_c4oJvGlb_31H9:-N40vQ-gEM16lO5-WZKj:b-ix88fr) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/resources/metrics/metricDefinitions/delegate_jwt_cache_metrics.yaml#L9)):*
> no, i think it should have both the metrices of cache hit and miss so that we can track if  there are lots of misses instead of hits.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/33436#-N35DsTFCpV4Yhmk-7u3:-N40vYOZ6IJT1544QzMK:bpj4ap) ([raw file](https://github.com/harness/harness-core/blob/4ae3f0852cfdaa0f33cdec422b9ed6dd5664e003/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java#L22)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

how about having delegate send the same token for 30 mins and we caching it for 25 mins in manager? Also why max size is 50k, if we have lets say 100k max, whats the max memory consumption? 
</blockquote></details>

lets first keep the cache for 15 mins, and then we can increase it for 25 mins. I have increased the limit to 100k
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheHelper.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/33436#-N3NYMhJAvb0yJ-wWz3x:-N40vVZtDc5gwUMBMXN7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48ce805ca1ce075094e2bf8b0a0 [...]

2022-06-09 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=33436) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=33436) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=33436) it.</sub>

2022-06-14 05:55 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: Some of the checks are too old. 24 file(s) to review. 1 change requests. 19. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bryFg5Q6F3IWVF_D2:-N4Vjznc016neZ4kR0zh:b2g5vwn) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L98)):*
> ave send one new authHeaders over 20-30 
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 105 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bs3GX505sC5FQLn_H:-N4VkVux89ukuaGuJA8R:b-e27gen) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L105)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we add log.warn here because we don't expect delegate token name to be empty now.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 144 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bs8Zh2j-_EjV1Qhap:-N4VkuNxB_r52lGwpRmm:bifs6o7) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L144)):*
> sing lots of if and else in the main validateToken method, which is not easy to read. And this tokenName is temporary, i.e will be 
Please a comment to cleanup later than
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3cjy4k2_DSFqnt_-WA:-N4VlHqM-TVHRsmDmJ-1:b-y22qq7) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L342)):*
> it should have both the metrices of cache hit a
Misses can be derived if we have lookups and hit metric.. And we want cache lookups so that we can calculate hit percentage in gcp dashboard. Absolute number won't make much sense
___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 404 at r8](https://reviewable.io/reviews/harness/harness-core/33436#-N4VlctI6WfxdJWi8uOI:-N4VlctI6WfxdJWi8uOJ:b-vzwyl0) ([raw file](https://github.com/harness/harness-core/blob/7f125fccc67a28c7bbc3129916eef5bdae1995a8/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L404)):*
> ```Java
>         accountId, tokenString, delegateId, delegateTokenName, shouldSetTokenNameInGlobalContext);
>     long endTime = System.currentTimeMillis();
>     log.info("Arpit, time taken: {}", endTime - startTime);
> ```

Remove this log line and time computation.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/33436#-N33CVHJ5b-xUC-HTqdy:-N4Vlodz3sRYjcC8JwUk:b-8sdpa4) ([raw file](https://github.com/harness/harness-core/blob/1e32ebe0ef11fb2b41bb737881ce507c1c4c7e78/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCacheValueObject.java#L18)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

We are storing invalid (revoked and expired)  tokens also.
</blockquote></details>

Yes isActive makes more sense, if token is not active than its revoked


<!-- Sent from Reviewable.io -->

2022-06-22 05:23 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 25 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCache.java` line 27 at r9](https://reviewable.io/reviews/harness/harness-core/33436#-N58rIAg2q18NQynp4yH:-N58rIAg2q18NQynp4yI:b-idinbu) ([raw file](https://github.com/harness/harness-core/blob/86207be609a57e9c0646b66a7542f86a99c3735d/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCache.java#L27)):*
> ```Java
> 
>   private final Cache<String, DelegateJWTCacheValue> delegateJWTCache =
>       Caffeine.newBuilder().maximumSize(50000).expireAfterWrite(15, TimeUnit.MINUTES).build();
> ```

why to expire in 15 mins ? we can keep the same token for 25mins atleast



_Code quote:_
```Java
15
```


<!-- Sent from Reviewable.io -->

2022-06-22 06:29 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 25 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 105 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3bs3GX505sC5FQLn_H:-N5958A_CDyvyvM1CRuK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L105)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Can we add log.warn here because we don't expect delegate token name to be empty now.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/33436#-N3cjy4k2_DSFqnt_-WA:-N595Bbn1FyeLdyO4Grt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cadefedf39c242f470165f8ff00b86cd7de2d3a7/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L342)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> it should have both the metrices of cache hit a
Misses can be derived if we have lookups and hit metric.. And we want cache lookups so that we can calculate hit percentage in gcp dashboard. Absolute number won't make much sense
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 404 at r8](https://reviewable.io/reviews/harness/harness-core/33436#-N4VlctI6WfxdJWi8uOI:-N595D2iE-jNLJXNZki1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f125fccc67a28c7bbc3129916eef5bdae1995a8/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L404)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Remove this log line and time computation.
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCache.java` line 27 at r9](https://reviewable.io/reviews/harness/harness-core/33436#-N58rIAg2q18NQynp4yH:-N595FDXEV2xSVq4lmGo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86207be609a57e9c0646b66a7542f86a99c3735d/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateJWTCache.java#L27)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why to expire in 15 mins ? we can keep the same token for 25mins atleast
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-22 06:32 UTC, gaurav-jain1 approved these changes
> Reviewed 14 of 18 files at r4, 2 of 6 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 06:37 UTC, gaurav-jain1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 07:23 UTC, raghuAtWings approved these changes
> Reviewed 14 of 18 files at r4, 2 of 6 files at r5, 2 of 4 files at r6, 1 of 1 files at r7, 3 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 08:17 UTC, AbhijithHarness approved these changes
> Reviewed 1 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 08:17 UTC, AbhijithHarness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 08:19 UTC, AbhijithHarness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 08:19 UTC, AbhijithHarness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 08:20 UTC, AbhijithHarness approved these changes
> Reviewed 11 of 18 files at r4, 2 of 6 files at r5, 2 of 4 files at r6, 1 of 1 files at r7, 3 of 4 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 09:29 UTC, deepak-harness approved these changes
> Reviewed 13 of 18 files at r4, 2 of 6 files at r5, 2 of 4 files at r6, 1 of 1 files at r7, 3 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33436)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-22 17:41 UTC, merged