[CDS-37877]: Marking prev inprogress canary release as Failed
harness/harness-core pull request #33485
Opened 2022-05-24 09:38 UTC by namantalaycha10

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

2022-05-24 10:28 UTC, namantalaycha10 commented
Local testing is good

2022-05-24 10:51 UTC, shubham-in10se requested changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33485)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandlerTest.java` line 401 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2pfOMV2J9WDUrStlXY:-N2pfOMV2J9WDUrStlXZ:b-fd9yzp) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandlerTest.java#L401)):*
> ```Java
>     doReturn(true)
>         .when(k8sCanaryBaseHandler)
>         .prepareForCanary(canaryHandlerConfig, delegateTaskParams, false, executionLogCallback, false, false);
> ```

add a case when the 'cleanup' param is true.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java` line 217 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2pg7vg169xgs1u0V-h:-N2pg7vg169xgs1u0V-i:bcx9nhc) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java#L217)):*
> ```Java
>       LogCallback logCallback) throws Exception {
>     k8sCanaryBaseHandler.prepareForCanary(k8sCanaryHandlerConfig, k8sDelegateTaskParams,
>         k8sCanaryDeployRequest.isSkipResourceVersioning(), logCallback, true, false);
> ```

are we not doing this for both CG and NG ..?


<!-- Sent from Reviewable.io -->

2022-05-24 10:53 UTC, gitNavV reviewed
@namantalaycha10 Could you please look into these and revert?

2022-05-24 10:53 UTC, gitNavV commented on 260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandlerTest.java
> +        .prepareForCanary(canaryHandlerConfig, delegateTaskParams, null, executionLogCallback, false, false);
Minor: `true` and `false` here are/would be unrecognisable in stack traces and code, could we please try to use enums/tuples instead?

2022-05-24 10:53 UTC, gitNavV commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +      for (int releaseIndex = canaryHandlerConfig.getReleaseHistory().getReleases().size() - 1; releaseIndex >= 0;
High chances of `NPE` here, are we already handling `null` checks for `canaryHandlerConfig` and it's method outcomes?

2022-05-24 10:53 UTC, gitNavV commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +    if (isCleanUpPrevInProgressCanaryRelease) {
What if `canaryHandlerConfig.getReleaseHistory().getReleases().size()` is 0? [`isCleanUpPrevInProgressCanaryRelease` should never be passed `true` is there are no past releases, are we making sure this is assured?]

2022-05-24 10:53 UTC, gitNavV commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +        if (release.getStatus() == InProgress) {
What happens if it is not `InProgress`?

2022-05-24 11:15 UTC, namantalaycha10 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +        if (release.getStatus() == InProgress) {
other case will be handled in cleanup method

2022-05-24 12:43 UTC, namantalaycha10 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +    if (isCleanUpPrevInProgressCanaryRelease) {
if the size is 0 means there is no past release then it will not enter inside the for loop
safe case

2022-05-24 13:13 UTC, gitNavV commented
trigger messagecheck

2022-05-24 13:45 UTC, abosii-harness requested changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33485)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/K8sCanaryDeploy.java` line 199 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2qHO2D4UDYvja9EWdZ:-N2qHO2D4UDYvja9EWd_:bu54l0c) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/400-rest/src/main/java/software/wings/sm/states/k8s/K8sCanaryDeploy.java#L199)):*
> ```Java
>             .useLatestKustomizeVersion(isUseLatestKustomizeVersion(context.getAccountId()))
>             .useNewKubectlVersion(featureFlagService.isEnabled(NEW_KUBECTL_VERSION, infraMapping.getAccountId()))
>             .cleanUpPrevInProgressCanaryRelease(
> ```

nit: naming of field and feature flag is different, would be easier to track if the name will be same
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2qHejO8_NhbzGeKHkw:-N2qHejO8_NhbzGeKHkx:b-33g5o3) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L66)):*
> ```Java
>   public boolean prepareForCanary(K8sCanaryHandlerConfig canaryHandlerConfig,
>       K8sDelegateTaskParams k8sDelegateTaskParams, Boolean skipVersioning, LogCallback logCallback,
>       boolean isErrorFrameworkEnabled, boolean isCleanUpPrevInProgressCanaryRelease) throws Exception {
> ```

nit: 'is' doesn't really make sense here
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2qIHq_32COsh96vpxy:-N2qIHq_32COsh96vpxz:b-am4pj0) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L105)):*
> ```Java
> 
>     if (isCleanUpPrevInProgressCanaryRelease) {
>       for (int releaseIndex = canaryHandlerConfig.getReleaseHistory().getReleases().size() - 1; releaseIndex >= 0;
> ```

This can be for (Release release : canaryHandlerConfig.getReleaseHistory().getReleases()) 
I don't see any needs of going in reverse order (that can be achieved with reversed iterator if that is the case) or any need to have index track


<!-- Sent from Reviewable.io -->

2022-05-25 06:32 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33485)* status: 11 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2pQn2bRCj_QzXpngzz-r2-105:-N2tuOs56fnkSNQ_CW3f:b-a7rma3) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L105)):*
<details><summary><i>Previously, gitNavV (Navneet Das) wrote…</i></summary><blockquote>

High chances of `NPE` here, are we already handling `null` checks for `canaryHandlerConfig` and it's method outcomes?
</blockquote></details>

tested no case of NPE
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2qIHq_32COsh96vpxy:-N2tuT9tB_PO7cQVR2b1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L105)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This can be for (Release release : canaryHandlerConfig.getReleaseHistory().getReleases()) 
I don't see any needs of going in reverse order (that can be achieved with reversed iterator if that is the case) or any need to have index track
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java` line 217 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2pg7vg169xgs1u0V-h:-N2tuV_D68Derjc_ck-4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java#L217)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

are we not doing this for both CG and NG ..?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-25 07:30 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33485)* status: 12 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandlerTest.java` line 401 at r2](https://reviewable.io/reviews/harness/harness-core/33485#-N2pfOMV2J9WDUrStlXY:-N2u6zbiCSXbhVicOx8L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c28790b0b8c9b566f5bff5ae3ab256e5fc5c107/260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandlerTest.java#L401)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

add a case when the 'cleanup' param is true.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-25 07:41 UTC, namantalaycha10 commented
trigger ti0

2022-05-25 07:41 UTC, namantalaycha10 commented
trigger ti1

2022-05-25 07:41 UTC, namantalaycha10 commented
trigger ti3

2022-05-25 07:42 UTC, namantalaycha10 commented
trigger ti4

2022-05-25 07:42 UTC, namantalaycha10 commented
trigger ti2

2022-05-25 07:59 UTC, abosii-harness approved these changes
> Reviewed 9 of 11 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33485)* status: 1 change requests. 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-25 08:45 UTC, shubham-in10se requested changes
> Reviewed 8 of 11 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33485)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 653 at r7](https://reviewable.io/reviews/harness/harness-core/33485#-N2uNY34DS0PPFXaWKn4:-N2uNY34DS0PPFXaWKn5:b-vyoke6) ([raw file](https://github.com/harness/harness-core/blob/d49c50e72255e1f6662c60fe29eaf0ba24eb1728/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L653)):*
> ```Java
>   }
> 
>   public boolean isCleanUpIncompleteCanaryDeployRelease(String accountId) {
> ```

rename: shouldCleanUpIncompleteCanaryDeployRelease


<!-- Sent from Reviewable.io -->

2022-05-25 08:47 UTC, namantalaycha10 commented
Regarding the PR Codebasehash Check merge checklist

1. No new Task type is added in this
2. no
3. yes changes are backward-compatible manner
4. yes Ng backward compatibility is there because is feature is for CG only
5. No removal of enum
6. All new enum are added in the end of the already defined constants

2022-05-25 09:08 UTC, mdmilic submitted a review, later dismissed
Approve hashcheck change

> Reviewed 2 of 9 files at r1, 6 of 11 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 3 files at r7, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33485#-:-N2uTQIQBzh26AhCvNrJ:bigcz1q)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-25 10:37 UTC, merged