[feat]: [PL-25416]: Error handling for  bitbucket server in git sync
harness/harness-core pull request #33491
Opened 2022-05-24 10:36 UTC by DeepakPatankar

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

2022-05-24 20:25 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetDefaultBranchScmApiErrorHandler.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33491#-N2rjnAQ29vhlZnklgmt:-N2rjnAQ29vhlZnklgmu:bw4fqni) ([raw file](https://github.com/harness/harness-core/blob/af115e98422b4a5c4dde96debc21d0c8a28c6dcc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetDefaultBranchScmApiErrorHandler.java#L33)):*
> ```Java
>         throw NestedExceptionUtils.hintWithExplanationException(ScmErrorHints.REPO_NOT_FOUND,
>             GET_DEFAULT_BRANCH_FAILED_MESSAGE + ScmErrorExplanations.REPO_NOT_FOUND,
>             new ScmResourceNotFoundException(errorMessage));
> ```

should be bad request exception


<!-- Sent from Reviewable.io -->

2022-05-24 20:27 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/33491#-N2rk-z15tis-fDEIVok:-N2rk-z15tis-fDEIVol:b1gx56a) ([raw file](https://github.com/harness/harness-core/blob/af115e98422b4a5c4dde96debc21d0c8a28c6dcc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L225)):*
> ```Java
> 
>     if (isFailureResponse(updateFileResponse.getStatus())) {
>       RepoProviders repoProvider =
> ```

@deepakpatankar this is too much redundant work thats being done at every handler. I see that we need url as well to determine the repo provider for bitbucket server. Could you instead take scm connector as argument input in itself in that case and move this repo provider fetching at a central place just like before?


<!-- Sent from Reviewable.io -->

2022-05-25 05:27 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491)* status: 35 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/33491#-N2rk-z15tis-fDEIVok:-N2tfWRy-mVtE66r1hej:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af115e98422b4a5c4dde96debc21d0c8a28c6dcc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L225)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@deepakpatankar this is too much redundant work thats being done at every handler. I see that we need url as well to determine the repo provider for bitbucket server. Could you instead take scm connector as argument input in itself in that case and move this repo provider fetching at a central place just like before?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetDefaultBranchScmApiErrorHandler.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33491#-N2rjnAQ29vhlZnklgmt:-N2tfcrK6GmoOulZNqoF:bhcr3ps) ([raw file](https://github.com/harness/harness-core/blob/af115e98422b4a5c4dde96debc21d0c8a28c6dcc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetDefaultBranchScmApiErrorHandler.java#L33)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should be bad request exception
</blockquote></details>

For 404 we throw ScmResourceNotFoundException, isn't that correct ?


<!-- Sent from Reviewable.io -->

2022-05-25 06:30 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetDefaultBranchScmApiErrorHandler.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/33491#-N2rjnAQ29vhlZnklgmt:-N2ttsp04e6v9gSUKyJo:b-y5sfb) ([raw file](https://github.com/harness/harness-core/blob/af115e98422b4a5c4dde96debc21d0c8a28c6dcc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetDefaultBranchScmApiErrorHandler.java#L33)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

For 404 we throw ScmResourceNotFoundException, isn't that correct ?
</blockquote></details>

Idk if you attended the internal discussion where we decided to keep 403, 409, 400 and 500 as valid error codes from SCM service. Issue is 404 is sent out in different cases for different git providers and as an SCM service we can't be consistent in our behaviour in that case. Thus, to maintain consistency, we try to limit our error codes and send out consistent error codes in all different use-cases for different git providers.


<!-- Sent from Reviewable.io -->

2022-05-25 07:36 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreatePullRequestScmApiErrorHandler.java
> +      default:
log the error here

2022-05-25 07:36 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/exceptions/bitbucketserver/BitbucketServerScmExceptionHints.java
> +  public static final String REPO_NOT_FOUND = "Please check your bitbucket repository.";
"Please check if the requested Bitbucket repository exists."

2022-05-25 07:36 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/exceptions/bitbucketserver/BitbucketServerScmExceptionHints.java
> +  public static final String INVALID_CREDENTIALS = "Please check your bitbucket credentials.";
Please ccheck if your bitbucket creadentials are valid

2022-05-25 07:36 UTC, bhavya181 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetFileScmApiErrorHandler.java
> +      default:
log the error here

2022-05-25 12:43 UTC, bhavya181 requested changes
> Reviewed 12 of 35 files at r1, 11 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491)* status: 44 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreateFileScmApiErrorHandler.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/33491#-N2vDEoeEdKP0Klv8oAZ:-N2vDEoeEdKP0Klv8oA_:b-pl1he4) ([raw file](https://github.com/harness/harness-core/blob/13951a9b3ce46d01f01ada19d13a27086e544002/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreateFileScmApiErrorHandler.java#L37)):*
> ```Java
>         throw NestedExceptionUtils.hintWithExplanationException(ScmErrorHints.FILE_ALREADY_EXISTS,
>             CREATE_FILE_REQUEST_FAILURE + ScmErrorExplanations.FILE_ALREADY_EXISTS,
>             new ScmBadRequestException(errorMessage));
> ```

Here ScmConflictError should be thrown


<!-- Sent from Reviewable.io -->

2022-05-26 07:07 UTC, mohitg0795 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 21 of 35 files at r1, 13 of 23 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491#-:-N2zBL_QDaFPvMoAX2jw:bnfp4nl)* status: 29 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-26 08:16 UTC, DeepakPatankar commented
trigger messagecheck

2022-05-26 08:27 UTC, ujjawal-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 21 of 35 files at r1, 13 of 23 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491#-:-N2zTd4pBifaXwGMxdlD:bnfp4nl)* status: 1 change requests. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-26 08:28 UTC, meenakshi-harness approved these changes
> Reviewed 21 of 35 files at r1, 13 of 23 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491)* status: 1 change requests. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-26 08:40 UTC, DeepakPatankar commented
/rebase

2022-05-26 12:06 UTC, bhavya181 reviewed
> Reviewed 9 of 35 files at r1, 10 of 23 files at r3, 10 of 10 files at r4, 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491)* status: 5 file(s) to review. 1 change requests. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreateFileScmApiErrorHandler.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/33491#-N2vDEoeEdKP0Klv8oAZ:-N3-EnhZ-5RLjrQpdf9q:bp39sau) ([raw file](https://github.com/harness/harness-core/blob/13951a9b3ce46d01f01ada19d13a27086e544002/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreateFileScmApiErrorHandler.java#L37)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

V2 one ?
</blockquote></details>

Sorry, we have decided to keep scmbadRequest here and only in case of update where conflicts occur we will send scmConflict exception. Please change it.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreatePullRequestScmApiErrorHandler.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/33491#-N2pd3gP2_5RsYK1OtWP-r2-35:-N3-F2C29MXxSJS8RsTM:bvrg8uk) ([raw file](https://github.com/harness/harness-core/blob/fae912bc893ae360ebe6fff13e86acd13811ecd0/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreatePullRequestScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please ceck there are many places where logging is not done in case of default.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetFileScmApiErrorHandler.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/33491#-N2pd3gP2_5RsYK1OtWR-r2-33:-N3-FBEIBWeH0EUi_0l6:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/fae912bc893ae360ebe6fff13e86acd13811ecd0/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetFileScmApiErrorHandler.java#L33)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same


<!-- Sent from Reviewable.io -->

2022-05-26 12:13 UTC, DeepakPatankar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreateFileScmApiErrorHandler.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/33491#-N2vDEoeEdKP0Klv8oAZ:-N3-GWQN6-a9CqKVAnLd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/13951a9b3ce46d01f01ada19d13a27086e544002/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreateFileScmApiErrorHandler.java#L37)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Sorry, we have decided to keep scmbadRequest here and only in case of update where conflicts occur we will send scmConflict exception. Please change it.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreatePullRequestScmApiErrorHandler.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/33491#-N2pd3gP2_5RsYK1OtWP-r2-35:-N3-GYHJ1yVFxQZl1vRy:b-5cxb7z) ([raw file](https://github.com/harness/harness-core/blob/fae912bc893ae360ebe6fff13e86acd13811ecd0/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerCreatePullRequestScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Please ceck there are many places where logging is not done in case of default.
</blockquote></details>

Added everywhere
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetFileScmApiErrorHandler.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/33491#-N2pd3gP2_5RsYK1OtWR-r2-33:-N3-GZtLBB-fSEfIvPBq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fae912bc893ae360ebe6fff13e86acd13811ecd0/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetFileScmApiErrorHandler.java#L33)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-26 12:25 UTC, DeepakPatankar commented
trigger ti4

2022-05-26 12:25 UTC, DeepakPatankar commented
trigger ti1

2022-05-26 14:06 UTC, bhavya181 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491#-:-N3-gAt2-OE_wSJ1c5BP:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-26 14:27 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33491#-:-N3-l-Kd3CEb5iTGzSAg:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-05-26 14:27 UTC, merged