[feat]: [PIE-1652]: Added Pipeline Clone feat
harness/harness-core pull request #33508
Opened 2022-05-24 14:29 UTC by smjt-h

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33508)

2022-05-24 17:39 UTC, naidu-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 254 at r1](https://reviewable.io/reviews/harness/harness-core/33508#-N2r8SYtCysL1T-P7teL:-N2r8SYtCysL1T-P7teM:bu06d8p) ([raw file](https://github.com/harness/harness-core/blob/892c8a5c62ad955ebea07f172a43cac9938e9425/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L254)):*
> ```Java
>         accountId, destIdentifierConfig.getOrgIdentifier(), destIdentifierConfig.getProjectIdentifier(), destYaml);
> 
>     GovernanceMetadata governanceMetadata =
> ```

we dont have to do source governance check
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 269 at r1](https://reviewable.io/reviews/harness/harness-core/33508#-N2r8XAN5Z_f7QjyZgbC:-N2r8XAN5Z_f7QjyZgbD:b-4pinqi) ([raw file](https://github.com/harness/harness-core/blob/892c8a5c62ad955ebea07f172a43cac9938e9425/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L269)):*
> ```Java
>     return ResponseDTO.newResponse(createdClonedEntity.getVersion().toString(),
>         PipelineSaveResponse.builder()
>             .governanceMetadata(governanceMetadata)
> ```

should this not be destGovernanceMetadata?


<!-- Sent from Reviewable.io -->

2022-05-25 05:40 UTC, archit-harness requested changes
> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 269 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2tioap7qguLm0bEmka:-N2tioap7qguLm0bEmkb:b-swivht) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L269)):*
> ```Java
>     return ResponseDTO.newResponse(createdClonedEntity.getVersion().toString(),
>         PipelineSaveResponse.builder()
>             .governanceMetadata(destGovernanceMetadata)
> ```

business logic in clone helper



_Code quote:_
```Java
    CloneIdentifierConfig destIdentifierConfig = clonePipelineDTO.getDestination();
    accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountId, destIdentifierConfig.getOrgIdentifier(),
                                                  destIdentifierConfig.getProjectIdentifier()),
        Resource.of("PIPELINE", destIdentifierConfig.getPipelineIdentifier()),
        PipelineRbacPermissions.PIPELINE_CREATE_AND_EDIT);

    Optional<PipelineEntity> sourcePipelineEntity = pmsPipelineService.get(accountId,
        clonePipelineDTO.getSource().getOrgIdentifier(), clonePipelineDTO.getSource().getProjectIdentifier(),
        clonePipelineDTO.getSource().getPipelineIdentifier(), false);

    if (!sourcePipelineEntity.isPresent()) {
      throw new InvalidRequestException(
          String.format("Pipeline with id [%s] in org [%s] in project [%s] is not present or deleted",
              clonePipelineDTO.getSource().getPipelineIdentifier(), clonePipelineDTO.getSource().getOrgIdentifier(),
              clonePipelineDTO.getSource().getProjectIdentifier()));
    }

    String destYaml = pmsPipelineService.getDestYamlfromSource(clonePipelineDTO, sourcePipelineEntity.get(), accountId);
    PipelineEntity destPipelineEntity = PMSPipelineDtoMapper.toPipelineEntity(
        accountId, destIdentifierConfig.getOrgIdentifier(), destIdentifierConfig.getProjectIdentifier(), destYaml);

    GovernanceMetadata governanceMetadata =
        pipelineServiceHelper.validatePipelineYamlAndSetTemplateRefIfAny(sourcePipelineEntity.get(), true);
    if (governanceMetadata.getDeny()) {
      return ResponseDTO.newResponse(PipelineSaveResponse.builder().governanceMetadata(governanceMetadata).build());
    }

    GovernanceMetadata destGovernanceMetadata =
        pipelineServiceHelper.validatePipelineYamlAndSetTemplateRefIfAny(destPipelineEntity, true);
    if (destGovernanceMetadata.getDeny()) {
      return ResponseDTO.newResponse(PipelineSaveResponse.builder().governanceMetadata(destGovernanceMetadata).build());
    }

    PipelineEntity createdClonedEntity = pmsPipelineService.clone(destPipelineEntity);
    return ResponseDTO.newResponse(createdClonedEntity.getVersion().toString(),
        PipelineSaveResponse.builder()
            .governanceMetadata(destGovernanceMetadata)
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 441 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2tikca7V7cN8R4ErIf:-N2tikca7V7cN8R4ErIg:b-kp7imw) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L441)):*
> ```Java
>     }
>     return modifiedSourceYaml;
>   }
> ```

Should be moved to CloneHelper



_Code quote:_
```Java
  @Override
  public String getDestYamlfromSource(
      ClonePipelineDTO clonePipelineDTO, PipelineEntity sourcePipelineEntity, String accountId) {
    String sourcePipelineEntityYaml = sourcePipelineEntity.getYaml();
    String destOrgId = clonePipelineDTO.getDestination().getOrgIdentifier();
    String destProjectId = clonePipelineDTO.getDestination().getProjectIdentifier();
    ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory());

    JsonNode jsonNode;
    try {
      jsonNode = objectMapper.readTree(sourcePipelineEntityYaml);
    } catch (JsonProcessingException e) {
      log.error(
          String.format("Error while processing source yaml for pipeline [%s]", sourcePipelineEntity.getIdentifier()),
          e);
      throw new InvalidRequestException(
          String.format("Unable to process source Yaml for pipeline [%s] org [%s] project [%s]",
              clonePipelineDTO.getSource().getPipelineIdentifier(), clonePipelineDTO.getSource().getOrgIdentifier(),
              clonePipelineDTO.getSource().getProjectIdentifier()),
          e);
    }

    // Resolve source yaml Params
    if (destProjectId != null && !destProjectId.equals(clonePipelineDTO.getSource().getProjectIdentifier())) {
      JsonNodeUtils.updatePropertyInObjectNode(jsonNode.get("pipeline"), "projectIdentifier", destProjectId);
    }
    if (destOrgId != null && !destOrgId.equals(clonePipelineDTO.getSource().getOrgIdentifier())) {
      JsonNodeUtils.updatePropertyInObjectNode(jsonNode.get("pipeline"), "orgIdentifier", destOrgId);
    }
    if (clonePipelineDTO.getDestination().getPipelineIdentifier() != null
        && !clonePipelineDTO.getDestination().getPipelineIdentifier().equals(
            clonePipelineDTO.getSource().getPipelineIdentifier())) {
      JsonNodeUtils.updatePropertyInObjectNode(
          jsonNode.get("pipeline"), "identifier", clonePipelineDTO.getDestination().getPipelineIdentifier());
    }

    String modifiedSourceYaml;
    try {
      modifiedSourceYaml = new YAMLMapper().writeValueAsString(jsonNode);
    } catch (IOException e) {
      throw new InvalidRequestException(
          String.format("Cannot convert json to yaml for pipeline [%s] org [%s] project [%s]",
              clonePipelineDTO.getSource().getPipelineIdentifier(), clonePipelineDTO.getSource().getOrgIdentifier(),
              clonePipelineDTO.getSource().getProjectIdentifier()),
          e);
    }
    return modifiedSourceYaml;
  }
```


<!-- Sent from Reviewable.io -->

2022-05-25 15:01 UTC, naidu-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 10 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/helpers/PipelineCloneHelper.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/33508#-N2vijiF2m9jqi_bT-YU:-N2vijiF2m9jqi_bT-YV:b-z4sj31) ([raw file](https://github.com/harness/harness-core/blob/ac2ce266e00e47921d5f38c9f6bcbb0c6688eded/800-pipeline-service/src/main/java/io/harness/pms/helpers/PipelineCloneHelper.java#L34)):*
> ```Java
>   private final PMSPipelineService pmsPipelineService;
> 
>   public void checkAccess(ClonePipelineDTO clonePipelineDTO, String accountId) {
> ```

we should check Pipeline View Permissions for Source
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/33508#-N2vj-XHAI7QhAIxAEMG:-N2vj-XHAI7QhAIxAEMH:b-ufwba5) ([raw file](https://github.com/harness/harness-core/blob/ac2ce266e00e47921d5f38c9f6bcbb0c6688eded/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L223)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns cloned pipeline with metadata")
>       })
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_CREATE_AND_EDIT)
> ```

since we do not have pipeline Identifier in query/path param, would this work? @sahilhindwani-harness @vaibhav-si 


<!-- Sent from Reviewable.io -->

2022-05-26 05:18 UTC, namanvermah commented on 800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java
> +        pipelineServiceHelper.validatePipelineYamlAndSetTemplateRefIfAny(destPipelineEntity, true);
Add feature flag check instead of directly sending `true`. Check usages of `validatePipelineYamlAndSetTemplateRefIfAny` method to see how to

2022-05-26 05:36 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 10 file(s) to review. 3 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2uAIzdAygIKGQoBrNx:-N2uAIzdAygIKGQoBrNy:bon7lcg) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L219)):*
> ```Java
>   @Path("/clone")
>   @ApiOperation(value = "Clone a Pipeline", nickname = "clonePipeline")
>   @Operation(operationId = "clonePipeline", summary = "Clone a Pipeline API With Governance Checks",
> ```

In my opinion, no need to mention "with Governance Checks". We can keep it simple for the user.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 435 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2v0w5C55VMRaGejeKL:-N2v0w5C55VMRaGejeKM:bm8vnf6) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L435)):*
> ```Java
>     } catch (IOException e) {
>       throw new InvalidRequestException(
>           String.format("Cannot convert json to yaml for pipeline [%s] org [%s] project [%s]",
> ```

This error is not for user I think. If not, we can just log internally and throw e as it is. Framework will show generic message like contact Harness Support.

Or throw a more user friendly error.
___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneConfig.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2yrAS5CGhoYXrSG07R:-N2yrAS6DRYRGbZxkzEh:bgjira8) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneConfig.java#L15)):*
> ```Java
> @Data
> @Builder
> public class CloneConfig {
> ```

as of now, we don't honor these inputs, right? If we don't, why expose them to the user and create a false impression?


<!-- Sent from Reviewable.io -->

2022-05-26 11:58 UTC, smjt-h reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 10 file(s) to review. 3 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/helpers/PipelineCloneHelper.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/33508#-N2vijiF2m9jqi_bT-YU:-N3-DPco-SGbPFYwHn5Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac2ce266e00e47921d5f38c9f6bcbb0c6688eded/800-pipeline-service/src/main/java/io/harness/pms/helpers/PipelineCloneHelper.java#L34)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

we should check Pipeline View Permissions for Source
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 254 at r1](https://reviewable.io/reviews/harness/harness-core/33508#-N2r8SYtCysL1T-P7teL:-N3-DWMX1NGWvkRS0QNm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/892c8a5c62ad955ebea07f172a43cac9938e9425/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L254)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

we dont have to do source governance check
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 269 at r1](https://reviewable.io/reviews/harness/harness-core/33508#-N2r8XAN5Z_f7QjyZgbC:-N3-D_gN2gMS8P7Vmkq0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/892c8a5c62ad955ebea07f172a43cac9938e9425/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L269)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

should this not be destGovernanceMetadata?
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2uAIzdAygIKGQoBrNx:-N3-DT9x-P-XEtSBmqrc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L219)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

In my opinion, no need to mention "with Governance Checks". We can keep it simple for the user.
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 269 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2tioap7qguLm0bEmka:-N3-DaMz4y4JmH6DihbZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L269)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

business logic in clone helper
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/33508#-N2vj-XHAI7QhAIxAEMG:-N3-DVHHEVKnewgyXLhJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac2ce266e00e47921d5f38c9f6bcbb0c6688eded/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L223)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

since we do not have pipeline Identifier in query/path param, would this work? @sahilhindwani-harness @vaibhav-si 
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 239 at r4](https://reviewable.io/reviews/harness/harness-core/33508#-N2qTMubldG16qT2eKZy-r4-239:-N3-DX1e2BXns93WkxCz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac2ce266e00e47921d5f38c9f6bcbb0c6688eded/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L239)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Add feature flag check instead of directly sending `true`. Check usages of `validatePipelineYamlAndSetTemplateRefIfAny` method to see how to
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 435 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2v0w5C55VMRaGejeKL:-N3-Dd-l0opwXEb9jI2Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L435)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

This error is not for user I think. If not, we can just log internally and throw e as it is. Framework will show generic message like contact Harness Support.

Or throw a more user friendly error.
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 441 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2tikca7V7cN8R4ErIf:-N3-DdxQDudhDJmmNLnO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L441)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should be moved to CloneHelper
</blockquote></details>

Done.
___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneConfig.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/33508#-N2yrAS5CGhoYXrSG07R:-N3-DesmEO2HS6dbV5Az:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0730612146b58d88eb91bb027ec43b06ec6b4619/954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneConfig.java#L15)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

as of now, we don't honor these inputs, right? If we don't, why expose them to the user and create a false impression?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-26 12:11 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 4 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 10 file(s) to review. 2 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-26 19:43 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 2 of 9 files at r1, 1 of 4 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 2 change requests. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-05-27 05:43 UTC, naidu-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508#-:-N331Tdj1SN5xGLRxeOv:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-27 05:51 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneIdentifierConfig.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/33508#-N332sQmCoN2Sicgzrqm:-N332sQmCoN2Sicgzrqn:bqre9an) ([raw file](https://github.com/harness/harness-core/blob/84a679ed21b6b796dea596926c23c39edeb6c934/954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneIdentifierConfig.java#L23)):*
> ```Java
>   @NonNull private String projectIdentifier;
>   @NonNull private String pipelineIdentifier;
>   private String pipelineName;
> ```

These 3 fields are not valid for source pipeline. This will confuse the user. Also, they are not technically part of IdentifierConfig.

Instead, move them to separate structure like PipelineMetadata. The corresponding field in ClonePipeilneDTO we can name as destinationPipelineMetadata.

Also, all these fields would also need descriptions.


<!-- Sent from Reviewable.io -->

2022-05-27 05:53 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/33508#-N333dZ_5k3_u2lO-c-l:-N333dZ_5k3_u2lO-c-m:b-qyoroi) ([raw file](https://github.com/harness/harness-core/blob/84a679ed21b6b796dea596926c23c39edeb6c934/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L31)):*
> ```Java
>   PipelineEntity create(PipelineEntity pipelineEntity);
> 
>   ResponseDTO clone(PipelineEntity destPipelineEntity);
> ```

This method should take clonePipelineDTO and accountId. Call this method directly from resource instead of invoking helper from resource. Helper can be invoked from inside this method.

Otherwise, this service method is not usable in standalone mode.


<!-- Sent from Reviewable.io -->

2022-05-27 05:55 UTC, vaibhav-si reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/helpers/PipelineCloneHelper.java` line 52 at r6](https://reviewable.io/reviews/harness/harness-core/33508#-N334Az1ENSvSfDlqapT:-N334Az1ENSvSfDlqapU:b-54ase9) ([raw file](https://github.com/harness/harness-core/blob/84a679ed21b6b796dea596926c23c39edeb6c934/800-pipeline-service/src/main/java/io/harness/pms/helpers/PipelineCloneHelper.java#L52)):*
> ```Java
>   }
> 
>   public String getDestYamlfromSource(ClonePipelineDTO clonePipelineDTO, String accountId) {
> ```

nit, break this method into smaller logical methods for improving readability. 

like getPipelineFromSource() -> updatePipelineMetadataInSourceYaml()


<!-- Sent from Reviewable.io -->

2022-05-27 08:56 UTC, smjt-h reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/33508#-N333dZ_5k3_u2lO-c-l:-N33ih_z8R-U_2cVyJ7h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84a679ed21b6b796dea596926c23c39edeb6c934/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L31)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

This method should take clonePipelineDTO and accountId. Call this method directly from resource instead of invoking helper from resource. Helper can be invoked from inside this method.

Otherwise, this service method is not usable in standalone mode.
</blockquote></details>

Done.
___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneIdentifierConfig.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/33508#-N332sQmCoN2Sicgzrqm:-N33iiHM9HmFrVXqfYMU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84a679ed21b6b796dea596926c23c39edeb6c934/954-pms-contracts/src/main/java/io/harness/pms/pipeline/CloneIdentifierConfig.java#L23)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

These 3 fields are not valid for source pipeline. This will confuse the user. Also, they are not technically part of IdentifierConfig.

Instead, move them to separate structure like PipelineMetadata. The corresponding field in ClonePipeilneDTO we can name as destinationPipelineMetadata.

Also, all these fields would also need descriptions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-27 09:43 UTC, vaibhav-si submitted a review, later dismissed
> Reviewed 1 of 9 files at r1, 1 of 4 files at r4, 1 of 7 files at r5, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-27 10:05 UTC, vaibhav-si approved these changes
> Reviewed 6 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-27 10:55 UTC, naidu-harness approved these changes
> Reviewed 1 of 9 files at r1, 1 of 4 files at r4, 1 of 7 files at r5, 3 of 9 files at r7, 3 of 7 files at r8, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33508)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-05-27 10:55 UTC, merged