feat: [CDS-38023]: Jenkins Build Step
harness/harness-core pull request #33539
Opened 2022-05-25 11:14 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-08 11:34 UTC, shivamnegi94 commented
trigger messagecheck

2022-06-21 06:22 UTC, puthrayaharness requested changes

2022-06-21 06:22 UTC, puthrayaharness commented on 120-ng-manager/config.yml
> +shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-true}
Please revert the change

2022-06-21 06:22 UTC, puthrayaharness commented on 970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java
> +  public static final String JENKINS_BUILD = "jenkinsBuild";
`JenkinsBuild`

2022-06-21 06:22 UTC, puthrayaharness commented on 800-pipeline-service/src/main/java/io/harness/pms/pipeline/CommonStepInfo.java
> +          .setStepMetaData(StepMetaData.newBuilder().addCategory("Jenkins").addFolderPaths("Jenkins").build())
Please confirm with the Product what should be category and folder paths.

2022-06-21 06:22 UTC, puthrayaharness commented on 860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PmsStepFilterJsonCreatorV2.java
> +        StepSpecTypeConstants.SHELL_SCRIPT, StepSpecTypeConstants.SERVICENOW_APPROVAL, StepSpecTypeConstants.BARRIER,
Please fix this. The change should be mostly Jenkins build. These look to be already present.

2022-06-22 12:23 UTC, shivamnegi94 commented on 970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java
> +  public static final String JENKINS_BUILD = "jenkinsBuild";
done

2022-06-29 03:58 UTC, puthrayaharness approved these changes
> Reviewed 10 of 57 files at r1, 1 of 1 files at r2, 7 of 34 files at r3, 72 of 72 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 04:37 UTC, archit-harness requested changes
> Reviewed 7 of 72 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: 1 change requests. Waiting on team(s): sto. 

___
*[`860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PmsStepFilterJsonCreatorV2.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/33539#-N5hjaH-7pH8puQHz4OY:-N5hjaH02FU73Lsfv04O:b-6qg4r1) ([raw file](https://github.com/harness/harness-core/blob/e78c9f6ff7c3d657d16588be8fce1122d38493a6/860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PmsStepFilterJsonCreatorV2.java#L28)):*
> ```Java
>         StepSpecTypeConstants.SERVICENOW_APPROVAL, StepSpecTypeConstants.BARRIER, StepSpecTypeConstants.POLICY_STEP,
>         StepSpecTypeConstants.SERVICENOW_CREATE, StepSpecTypeConstants.SERVICENOW_UPDATE, StepSpecTypeConstants.QUEUE,
>         StepSpecTypeConstants.SHELL_SCRIPT);
> ```

shell script is already linked here, please remove from here



_Code quote:_
```Java
StepSpecTypeConstants.SHELL_SCRIPT
```
___
*[`860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 350 at r4](https://reviewable.io/reviews/harness/harness-core/33539#-N5hjkA40wY0ts2pyNLp:-N5hjkA40wY0ts2pyNLq:b-g7aa9e) ([raw file](https://github.com/harness/harness-core/blob/e78c9f6ff7c3d657d16588be8fce1122d38493a6/860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L350)):*
> ```Java
>                                            .namespace(SchemaNamespaceConstants.CD)
>                                            .modulesSupported(Arrays.asList(ModuleType.CD, ModuleType.PMS))
>                                            .yamlGroup(YamlGroup.builder().group(StepCategory.STEP.name()).build())
> ```

Why this is needed for jenkins step? or any other change is incorporated in your pr?



_Code quote:_
```Java
                                           .namespace(SchemaNamespaceConstants.CD)
                                           .modulesSupported(Arrays.asList(ModuleType.CD, ModuleType.PMS))
                                           .yamlGroup(YamlGroup.builder().group(StepCategory.STEP.name()).build())
```
___
*[`870-orchestration/src/main/java/io/harness/steps/StepSpecTypeConstants.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/33539#-N5hjrfXB7jJ_7k_Sg0Y:-N5hjrfXB7jJ_7k_Sg0Z:b181nta) ([raw file](https://github.com/harness/harness-core/blob/e78c9f6ff7c3d657d16588be8fce1122d38493a6/870-orchestration/src/main/java/io/harness/steps/StepSpecTypeConstants.java#L38)):*
> ```Java
>   String FEATURE_FLAG_STAGE = "FeatureFlag";
>   String POLICY_STEP = "Policy";
>   String JENKINS_BUILD = "JenkinsBuild";
> ```

it should not be in 870 module, it should be in cd



_Code quote:_
```Java
String JENKINS_BUILD = "JenkinsBuild";
```


<!-- Sent from Reviewable.io -->

2022-06-29 05:15 UTC, archit-harness approved these changes
> Reviewed 4 of 72 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 

___
*[`860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 350 at r4](https://reviewable.io/reviews/harness/harness-core/33539#-N5hjkA40wY0ts2pyNLp:-N5hs_MX1Qs2SFJ5tJmU:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e78c9f6ff7c3d657d16588be8fce1122d38493a6/860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L350)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why this is needed for jenkins step? or any other change is incorporated in your pr?
</blockquote></details>

done
___
*[`870-orchestration/src/main/java/io/harness/steps/StepSpecTypeConstants.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/33539#-N5hjrfXB7jJ_7k_Sg0Y:-N5hscT75EzPyI59Dqsk:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e78c9f6ff7c3d657d16588be8fce1122d38493a6/870-orchestration/src/main/java/io/harness/steps/StepSpecTypeConstants.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should not be in 870 module, it should be in cd
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-29 05:17 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 

___
*[`860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PmsStepFilterJsonCreatorV2.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/33539#-N5hjaH-7pH8puQHz4OY:-N5ht2Tq9vuXKoRQCC1D:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e78c9f6ff7c3d657d16588be8fce1122d38493a6/860-orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PmsStepFilterJsonCreatorV2.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shell script is already linked here, please remove from here
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-06-29 05:21 UTC, shivamnegi94 reviewed
> Reviewed 10 of 57 files at r1, 1 of 1 files at r2, 7 of 34 files at r3, 57 of 72 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 06:08 UTC, puthrayaharness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 06:09 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 06:18 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 57 files at r1, 1 of 1 files at r2, 7 of 34 files at r3, 55 of 72 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539#-:-N5i67VO7s6gG1-CRUM1:bnfp4nl)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 06:50 UTC, diptiman-adak approved these changes
> Reviewed 10 of 57 files at r1, 1 of 1 files at r2, 7 of 34 files at r3, 55 of 72 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 06:52 UTC, diptiman-adak approved these changes
> Reviewed 14 of 72 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 07:27 UTC, prashantsharma04 submitted a review, later dismissed
> Reviewed 10 of 57 files at r1, 1 of 1 files at r2, 7 of 34 files at r3, 55 of 72 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 08:27 UTC, diptiman-adak submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-06-29 10:54 UTC, williamwissemann approved these changes
> Reviewed 10 of 57 files at r1, 1 of 1 files at r2, 7 of 34 files at r3, 72 of 72 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-29 11:36 UTC, diptiman-adak reviewed
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: 29 file(s) to review. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-29 11:38 UTC, diptiman-adak reviewed
> Reviewed 3 of 83 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: 29 file(s) to review. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-29 11:39 UTC, diptiman-adak approved these changes
> Reviewed 29 of 29 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-29 11:39 UTC, puthrayaharness approved these changes
> Reviewed 3 of 3 files at r6, 29 of 29 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33539)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-29 11:40 UTC, merged