[feat]: [PL-25236]: Script to copy entities from one project to another
harness/harness-core pull request #33723
Opened 2022-05-31 10:26 UTC by rathodmeetsatish

Script to copy entities from one project to another

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-05-31 12:40 UTC, abhinav-harness commented on scripts/copy-entities/copy_entities_script.py
> +from abc import *
remove

2022-05-31 12:40 UTC, abhinav-harness commented on scripts/copy-entities/copy_entities_script.py
> +class ImportExport(ABC):
ABC is wrong name

2022-06-02 09:12 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33723)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`scripts/copy-entities/copy_entities_script.py` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/33723#-N3OdkZ-MIQbQ6-uQ93N-r1-37:-N3YftGw4QbG2txI2loq:b-ek0scc) ([raw file](https://github.com/harness/harness-core/blob/aef1f00b644333933c132a286882961a41bf8072/scripts/copy-entities/copy_entities_script.py#L37)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

ABC is wrong name
</blockquote></details>

its the library name 


<!-- Sent from Reviewable.io -->

2022-06-02 09:57 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33723)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`scripts/copy-entities/copy_entities_script.py` line 261 at r1](https://reviewable.io/reviews/harness/harness-core/33723#-N3Ypwv9EgwjoDB_NFQ6:-N3Ypwv9EgwjoDB_NFQ7:bu95qq0) ([raw file](https://github.com/harness/harness-core/blob/aef1f00b644333933c132a286882961a41bf8072/scripts/copy-entities/copy_entities_script.py#L261)):*
> ```Python
> print("Successfully copied "+str(success_failure_count_connector[0])+" connectors and got error while copying "+str(success_failure_count_connector[1])+" connectors")
> print("Successfully copied "+str(success_failure_count_template[0])+" templates and got error while copying "+str(success_failure_count_template[1])+" templates")
> print("Successfully copied "+str(success_failure_count_pipeline[0])+" pipelines and got error while copying "+str(success_failure_count_pipeline[1])+" pipelines")
> ```

Clean the code here - 
```
make a list add there and use for loop to publish and for loop to call main_exoprt for those entity
```



_Code quote:_
```Python
success_failure_count_secret = main_export("Secret")

success_failure_count_service= main_export("Service")

success_failure_count_environment = main_export("Environment")

success_failure_count_connector = main_export("Connector")

success_failure_count_template = main_export("Template")

success_failure_count_pipeline = main_export("Pipeline")

print("Successfully copied "+str(success_failure_count_secret[0])+" secret and got error while copying "+str(success_failure_count_secret[1])+" secrets")
print("Successfully copied "+str(success_failure_count_service[0])+" services and got error while copying "+str(success_failure_count_service[1])+" services")
print("Successfully copied "+str(success_failure_count_environment[0])+" environments and got error while copying "+str(success_failure_count_connector[1])+" environments")
print("Successfully copied "+str(success_failure_count_connector[0])+" connectors and got error while copying "+str(success_failure_count_connector[1])+" connectors")
print("Successfully copied "+str(success_failure_count_template[0])+" templates and got error while copying "+str(success_failure_count_template[1])+" templates")
print("Successfully copied "+str(success_failure_count_pipeline[0])+" pipelines and got error while copying "+str(success_failure_count_pipeline[1])+" pipelines")
```


<!-- Sent from Reviewable.io -->

2022-06-02 09:57 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33723)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`scripts/copy-entities/copy_entities_script.py` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33723#-N3YqNFF2pKpSq701pYY:-N3YqNFF2pKpSq701pYZ:b-prfgjw) ([raw file](https://github.com/harness/harness-core/blob/aef1f00b644333933c132a286882961a41bf8072/scripts/copy-entities/copy_entities_script.py#L93)):*
> ```Python
>       url_create_input_set = input_set_endpoint + "?routingId="+accountIdentifier+"&accountIdentifier="+accountIdentifier+"&orgIdentifier="+to_orgIdentifier+"&pipelineIdentifier="+pipelineIdentifier+"&projectIdentifier=" + to_projectIdentifier
>       create_and_print_entity(url_create_input_set, new_payload_json)
> ```

move this below implementors



_Code quote:_
```Python
def get_response_data(request_type, url, payload):
  conn.request(request_type, url, payload, headers)
  res = conn.getresponse()
  data = res.read()
  return json.loads(data.decode("utf-8"))

def modify_payload(payload, entity_type):
  payload[entity_type]["projectIdentifier"] = to_projectIdentifier
  payload[entity_type]["orgIdentifier"] = to_orgIdentifier
  return json.dumps(payload)

def list_entity(url, filterType):
  payload = json.dumps({"filterType":filterType})
  return get_response_data("POST", url, payload)

def create_and_print_entity(url, payload):
  response_create_dict = get_response_data("POST", url, payload)
  print(response_create_dict)
  print("\n")
  return response_create_dict

def export_input_set(pipelineIdentifier):
  url = input_set_endpoint+"?routingId="+accountIdentifier+"&accountIdentifier="+accountIdentifier+"&orgIdentifier="+from_orgIdentifier+"&projectIdentifier="+from_projectIdentifier+"&pipelineIdentifier="+pipelineIdentifier+"&pageIndex=0&pageSize=20"
  response_dict = get_response_data("GET", url, "")

  for j in range(0,response_dict["data"]["totalPages"]):
    url_paginated = input_set_endpoint+"?routingId="+accountIdentifier+"&accountIdentifier="+accountIdentifier+"&orgIdentifier="+from_orgIdentifier+"&projectIdentifier="+from_projectIdentifier+"&pipelineIdentifier="+pipelineIdentifier+"&pageIndex="+str(j)+"&pageSize=20"
    response_dict = get_response_data("GET", url_paginated, "")

    for i in range(0,response_dict["data"]["pageItemCount"]):
      url_get_input_set = input_set_endpoint +"/"+ response_dict["data"]["content"][i]["identifier"] + "?routingId="+accountIdentifier+"&accountIdentifier="+accountIdentifier+"&orgIdentifier="+from_orgIdentifier+"&pipelineIdentifier="+pipelineIdentifier+"&projectIdentifier="+from_projectIdentifier
      response_get_input_set = get_response_data("GET", url_get_input_set, "")
      new_payload_json = modify_payload(yaml.safe_load(response_get_input_set["data"]["inputSetYaml"]), "inputSet")
      url_create_input_set = input_set_endpoint + "?routingId="+accountIdentifier+"&accountIdentifier="+accountIdentifier+"&orgIdentifier="+to_orgIdentifier+"&pipelineIdentifier="+pipelineIdentifier+"&projectIdentifier=" + to_projectIdentifier
      create_and_print_entity(url_create_input_set, new_payload_json)
```


<!-- Sent from Reviewable.io -->

2022-06-06 10:53 UTC, rathodmeetsatish reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33723)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`scripts/copy-entities/copy_entities_script.py` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33723#-N3YqNFF2pKpSq701pYY:-N3sdSQXB9TJVgAnvczw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aef1f00b644333933c132a286882961a41bf8072/scripts/copy-entities/copy_entities_script.py#L93)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

move this below implementors
</blockquote></details>

Done.
___
*[`scripts/copy-entities/copy_entities_script.py` line 261 at r1](https://reviewable.io/reviews/harness/harness-core/33723#-N3Ypwv9EgwjoDB_NFQ6:-N3sdTSD1-X18Rnkay67:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aef1f00b644333933c132a286882961a41bf8072/scripts/copy-entities/copy_entities_script.py#L261)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Clean the code here - 
```
make a list add there and use for loop to publish and for loop to call main_exoprt for those entity
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-06 14:12 UTC, rathodmeetsatish commented
/rebase

2022-06-07 09:08 UTC, abhinav-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33723)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-09 10:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=33723) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=33723) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=33723) it.</sub>

2022-06-23 14:34 UTC, abhinav-harness approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33723)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-23 16:05 UTC, mankrit-singh approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33723)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-23 16:06 UTC, merged