Cds 38079 new
harness/harness-core pull request #33888
Opened 2022-06-03 10:13 UTC by namantalaycha10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-06 09:01 UTC, namantalaycha10 commented
trigger ti1

2022-06-06 10:31 UTC, abosii-harness requested changes
> Reviewed 44 of 51 files at r1, 15 of 15 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33888)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 532 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sDv36BW-_yCUA9xDR:-N3sDv36BW-_yCUA9xDS:bryoyqv) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L532)):*
> ```Java
>         if (!(connectorInfoDTO.getConnectorConfig() instanceof OciHelmConnectorDTO)) {
>           throw new InvalidRequestException(
>               format("Invalid connector selected in %s. Select Http Helm connector", message));
> ```

Should be select OCI Helm Repo connector
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 682 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sDnUaC7Y9k_-vjZqN:-N3sDnUaC7Y9k_-vjZqO:ba06vxv) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L682)):*
> ```Java
>   }
> 
>   public boolean helmOciSupport(String accountId) {
> ```

name should be isHelmOciSupported/Enabled
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartStoreGenericConfig.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sFh3m3b91ObJYfft_:-N3sFh3n0QywvrfIurK5:b-ob9lo6) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartStoreGenericConfig.java#L41)):*
> ```Java
> @SimpleVisitorHelper(helperClass = ConnectorRefExtractorHelper.class)
> @TypeAlias("OciGenericConfig")
> @RecasterAlias("io/harness/cdng/manifest/yaml/OciHelmChartGenericConfig.java")
> ```

I don't think it should path but package + class name
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciHelmChartStoreConfigType.java` line 2 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sGKio5OiKewEDAFUh:-N3sGKio5OiKewEDAFUi:brmzafn) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciHelmChartStoreConfigType.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

should be 2022
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciHelmChartStoreConfigWrapper.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sGjcyEV-ysv8SUxG5:-N3sGjcyEV-ysv8SUxG6:b-rewq1r) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciHelmChartStoreConfigWrapper.java#L53)):*
> ```Java
>   private String uuid;
> 
>   @NotNull @JsonProperty("type") OciHelmChartStoreConfigType type;
> ```

nit: JsonProperty not required here, the name is already type
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciStoreConfigType.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sH83E-GZVNdksIBHC:-N3sH83E-GZVNdksIBHD:b-umly3x) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciStoreConfigType.java#L15)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public interface OciStoreConfigType {
>   String GENERIC = "Generic";
> ```

We should use this in Enum
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciStoreConfigWrapperVisitorHelper.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sHCG00j6GqZjNTbVq:-N3sHCG00j6GqZjNTbVr:bapijl4) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ociHelmChartConfig/OciStoreConfigWrapperVisitorHelper.java#L13)):*
> ```Java
> import io.harness.walktree.visitor.validation.ValidationVisitor;
> 
> public class OciStoreConfigWrapperVisitorHelper implements ConfigValidator {
> ```

nit: missing ownedby
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/helm/OciHelmAuthentication.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sHcdz8AcQ4QS6bfaL:-N3sHcdz8AcQ4QS6bfaM:blfuw65) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/helm/OciHelmAuthentication.java#L10)):*
> ```Java
> package io.harness.connector.entities.embedded.helm;
> 
> public interface OciHelmAuthentication {}
> ```

missing ownedby
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/helm/OciHelmDTOToEntity.java` line 2 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sHnZq01ld2XLyn-em:-N3sHnZq01ld2XLyn-en:brmzafn) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/440-connector-nextgen/src/main/java/io/harness/connector/mappers/helm/OciHelmDTOToEntity.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

should be 2022
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/validator/OciHelmRepoConnectionValidator.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sWp-s5pxiRFQFugP-:-N3sWp-tBRQSp3qeCFk1:b-tg1ka5) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/440-connector-nextgen/src/main/java/io/harness/connector/validator/OciHelmRepoConnectionValidator.java#L48)):*
> ```Java
>   public ConnectorValidationResult validate(ConnectorConfigDTO connectorDTO, String accountIdentifier,
>       String orgIdentifier, String projectIdentifier, String identifier) {
>     OciHelmConnectivityTaskResponse responseData = (OciHelmConnectivityTaskResponse) super.validateConnector(
> ```

Shouldn't we create a custom validation for oci helm repo?
___
*[`810-ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/generator/OciHelmPollingItemGenerator.java` line 2 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sWxK5CkHzTg8khbeR:-N3sWxK5CkHzTg8khbeS:brmzafn) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/810-ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/generator/OciHelmPollingItemGenerator.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

should be 2022
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmConnectivityDelegateTask.java` line 2 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sXXgW6fgI5rytT8rG:-N3sXXgW6fgI5rytT8rH:brmzafn) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmConnectivityDelegateTask.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

should be 2022
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmConnectivityDelegateTask.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/33888#-N3sXhwl4UPP7lpR4Tol:-N3sXhwl4UPP7lpR4Tom:b-qn9rch) ([raw file](https://github.com/harness/harness-core/blob/844834f5b300cd7c86af722a47d714aa7f63c3f7/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmConnectivityDelega [...]

2022-06-07 18:50 UTC, shubham-in10se requested changes
> Reviewed 24 of 51 files at r1, 4 of 15 files at r2, 1 of 3 files at r3, 41 of 41 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33888)* status: 2 change requests. 20. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartConfig.java` line 55 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zOfBH9ffgofHqH6_6:-N3zOfBI1tG0mJSFIvPU:bxrpyu) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartConfig.java#L55)):*
> ```Java
> 
>   @EntityIdentifier String identifier;
>   @Wither
> ```

give a new line space here to better readability
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartConfig.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zOn0BCbLP5TeiIbqw:-N3zOn0BCbLP5TeiIbqx:bzaohgs) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartConfig.java#L59)):*
> ```Java
>   @ApiModelProperty(dataType = "io.harness.cdng.manifest.yaml.oci.OciHelmChartStoreConfigWrapper")
>   @SkipAutoEvaluation
>   ParameterField<OciHelmChartStoreConfigWrapper> config;
> ```

`identifier` and `config` fields are not marked `private`. Is this intentional .?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartConfig.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zP3tCCONF0aZFE8Fx:-N3zP3tCCONF0aZFE8Fy:b-mrg04k) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/OciHelmChartConfig.java#L79)):*
> ```Java
> 
>   public StoreConfig applyOverrides(StoreConfig overrideConfig) {
>     OciHelmChartConfig ociHelmChartConfig = (OciHelmChartConfig) overrideConfig;
> ```

rename to `overrideHelmConfig`
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/helm/OciHelmConnector.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zS60L1JU2DoANgSYx:-N3zS60L1JU2DoANgSYy:bfcy9yz) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/helm/OciHelmConnector.java#L33)):*
> ```Java
> @TypeAlias("io.harness.connector.entities.embedded.helm.OciHelmConnector")
> public class OciHelmConnector extends Connector {
>   String url;
> ```

all fields are `package` privacy level. Is this intentional .? Why not have them `private`
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/helm/OciHelmUsernamePasswordAuthentication.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zSEsG3wzLqhjzUuqi:-N3zSEsG3wzLqhjzUuqj:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/helm/OciHelmUsernamePasswordAuthentication.java#L25)):*
> ```Java
>   String username;
>   String usernameRef;
>   String passwordRef;
> ```

same as above
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/OciHelmConnectorValidationParamsProvider.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zSHoH6Z_l17d6uY-X:-N3zSHoH6Z_l17d6uY-Y:byxy4jw) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/OciHelmConnectorValidationParamsProvider.java#L27)):*
> ```Java
> @Singleton
> public class OciHelmConnectorValidationParamsProvider implements ConnectorValidationParamsProvider {
>   @Inject EncryptionHelper encryptionHelper;
> ```

All dependencies should be marked `private`
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/validator/OciHelmRepoConnectionValidator.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zSiQu5K4fNlreoIkb:-N3zSiQu5K4fNlreoIkc:b-egdodl) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/440-connector-nextgen/src/main/java/io/harness/connector/validator/OciHelmRepoConnectionValidator.java#L24)):*
> ```Java
> import lombok.extern.slf4j.Slf4j;
> 
> @Slf4j
> ```

there is no `log` statement in the class. We can remove this.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmConnectivityDelegateTask.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zTwTt5M1t85vrbr69:-N3zTwTw9F3R6GCSxY5x:b8eorsp) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmConnectivityDelegateTask.java#L52)):*
> ```Java
>               .ociHelmConnectorDTO(ociHelmConnectorDTO)
>               .build();
>       ConnectorValidationResult ociHelmConnectorValidationResult =
> ```

can be renamed as `validationResult`, since we are getting all the other context from the rest of the statement/block.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zUHLv2xV5-SviH1ES:-N3zUHLv2xV5-SviH1ET:b-ylxq63) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java#L69)):*
> ```Java
>       validationResultBuilder.status(ConnectivityStatus.SUCCESS);
>     } catch (IOException exception) {
>       log.warn("OciHelmValidationHandler execution failed with exception ", exception);
> ```

this should be an error log ..?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmValidationParams.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zUZZi7MQLQUiLx-_c:-N3zUZZi7MQLQUiLx-_d:be4e4xa) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmValidationParams.java#L26)):*
> ```Java
> public class OciHelmValidationParams
>     extends ConnectorTaskParams implements ConnectorValidationParams, ExecutionCapabilityDemander {
>   OciHelmConnectorDTO ociHelmConnectorDTO;
> ```

why not make them all `private`
please also check the same for other defined data objects as well.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmAuthenticationDTO.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zV1kz7d9n5g7dEn7Z:-N3zV1kz7d9n5g7dEn7_:bjuwolz) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmAuthenticationDTO.java#L29)):*
> ```Java
> @Schema(name = "OciHelmAuthentication", description = "This contains oci helm authentication details")
> public class OciHelmAuthenticationDTO {
>   @NotNull @JsonProperty("type") OciHelmAuthType authType;
> ```

`private` ..?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/oci/OciHelmChartStoreConfigType.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/33888#-N3zQtDW8DpylNNPH9tJ:-N3zQtDW8DpylNNPH9tK:b-uwi514) ([raw file](https://github.com/harness/harness-core/blob/d07764a4ec4531df736f816a865debb9193fb0a3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/oci/OciHelmChartStoreConfigType.java#L21)):*
> ```Java
> public enum OciHelm [...]

2022-06-09 06:44 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33888)* status: 2 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/oci/OciStoreConfigWrapperVisitorHelper.java` line 14 at r6](https://reviewable.io/reviews/harness/harness-core/33888#-N42zkSj1v2k188jeLjU:-N45lP3BCYaDnrZDTmtX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b34e55c9d0220939e57f7adbec43ea244559548/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/oci/OciStoreConfigWrapperVisitorHelper.java#L14)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Should be right up to class
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 08:07 UTC, namantalaycha10 commented
Regarding the PR Codebasehash Check merge checklist

1. Yes new Task type is added in this
2. a Added one class is Kryo register, but since changes are behind a FF, we can wait to enable the feature for any customer until the changes go live in delegate release
3. yes changes are backward-compatible manner
4. yes Ng backward compatibility is there because is feature is for CG only
5. No removal of enum
6. All new enum are added in the end of the already defined constants

2022-06-09 09:01 UTC, shubham-in10se submitted a review, later dismissed
> Reviewed 5 of 13 files at r5, 4 of 14 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33888)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-09 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=33888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=33888) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=33888) it.</sub>

2022-06-09 10:15 UTC, namantalaycha10 commented
trigger ti0

2022-06-09 11:24 UTC, puthrayaharness requested changes

2022-06-09 11:24 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +                    || storeType == StoreDelegateConfigType.GIT || storeType == StoreDelegateConfigType.GCS_HELM
Create a static list with all the types and do a contains check. This is not readable now.

2022-06-09 12:44 UTC, mdmilic approved these changes
Approve delegate related changes and codebase hash update

> Reviewed 7 of 51 files at r1, 7 of 41 files at r4, 1 of 16 files at r7, 2 of 4 files at r9, 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33888#-:-N47UYTi4_uxNLFtwNc-:b-wq7n8p)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-10 03:03 UTC, merged