Bt 1354 2
harness/harness-core pull request #33918
Opened 2022-06-03 13:28 UTC by diptiman-adak

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-03 13:32 UTC, diptiman-adak commented
trigger message_metadata

2022-06-03 20:44 UTC, gunascode commented on dockerization/base-image/Dockerfile-ubi-python-base
> +RUN rm -rf ~/.cache/pip/selfcheck/*
Can we add all these rm commands in one RUN step?

2022-06-06 11:38 UTC, shivagowda requested changes

2022-06-06 11:38 UTC, shivagowda commented on dockerization/base-image/Dockerfile-ubi-base
> +WORKDIR /opt/harness
why are we changing the workdir from /harness to /opt/harness?

2022-06-06 11:38 UTC, shivagowda commented on dockerization/base-image/Dockerfile-ubi-python-base
> +    rm -rf ~/.cache/pip/http/*
@parnianzargham please validate whether this image works for you.

2022-06-06 11:38 UTC, shivagowda commented on dockerization/base-image/ubi-java-base-cie/Dockerfile-ubi-java-base-cie
> +# Run under user "jboss" and prepare for be running
why do we need jboss?

2022-06-06 11:38 UTC, shivagowda commented on dockerization/base-image/ubi-java-base-cie/Dockerfile-ubi-java-base-cie
> +#yum group install -y "Development Tools" \
remove all commented out lines

2022-06-06 11:38 UTC, shivagowda commented on dockerization/base-image/Dockerfile-ubi-base
> +FROM redhat/ubi8:latest
Please add clear comment on where this image will be used. please add it to each image

2022-06-06 12:36 UTC, pranay-harness commented on dockerization/base-image/Dockerfile-ubi-base
> +FROM redhat/ubi8:latest
@diptiman-adak It's not recommended to use the latest tag for deployments. 
Reason: It will be difficult to figure out which version of ubi is used, also sometime the latest version released by them may not be stable for us.

Use version number (redhat/ubi8:ubi:8.6-754 for example)

2022-06-06 15:35 UTC, diptiman-adak commented
Test build for CIE image: https://app.harness.io/ng/#/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/TestCompileUBI/executions/ICELgHq-RD2w8O-SbaeR_Q/pipeline?step=VNO1D9YpRU2SaCcpCXmbuw&stage=ERusTkwCRTKE-eN9hhAXkA

2022-06-07 05:40 UTC, shivagowda commented on dockerization/base-images/ubi-base-cie-agent/Dockerfile-ubi-base-cie-agent
> +RUN curl -O https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz \
we need 1.17.8
please change

2022-06-07 05:46 UTC, shivagowda commented on dockerization/base-images/ubi-base-cie-agent/Dockerfile-ubi-base-cie-agent
> +RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo \
we don't need centos repo

2022-06-07 06:03 UTC, shivagowda commented
@diptiman-adak the increase in image size is not entirely due to Go,
we are adding tf, helm,, terragrunt and so on that are needed for functional tests. thats the reason.
Can we create a separate image just for functional tests?
https://harness.atlassian.net/browse/BT-310
So, most of our steps will be using .5 GB image instead of 1.5GB image
only functional tests can be 1.5GB

2022-06-07 17:43 UTC, merged