[fix]: [DEL-4028]: Fix receiving heartbeat multiple times within a min at agent
harness/harness-core pull request #33961
Opened 2022-06-06 06:06 UTC by AnupamIO

…ient

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-06 06:14 UTC, AnupamIO commented
trigger ti1

2022-06-06 12:53 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33961)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1683 at r1](https://reviewable.io/reviews/harness/harness-core/33961#-N3t3tac0ngDH-H1dcIT:-N3t3tac0ngDH-H1dcIU:b-9mdn31) ([raw file](https://github.com/harness/harness-core/blob/0c4900bb4c0f30a67157b6634be9d648bf9ada22/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1683)):*
> ```Java
>               .toBuilder()
>               .lastHeartBeat(clock.millis())
>               .heartbeatPacket(true)
> ```

How we are handling this on manager side ? I can't see those changes
___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33961#-N3sp5_WBsRTLVLfAbaZ:-N3sp5_WBsRTLVLfAba_:btb6634) ([raw file](https://github.com/harness/harness-core/blob/0c4900bb4c0f30a67157b6634be9d648bf9ada22/420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java#L93)):*
> ```Java
>   private transient String delegateRandomToken;
>   private transient boolean keepAlivePacket;
>   private boolean heartbeatPacket;
> ```

Why this got changed ?
___
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/33961#-N3t3pjoC54EudRHn0RY:-N3t3pjp0gJWxg_s2U19:b-xuupe8) ([raw file](https://github.com/harness/harness-core/blob/0c4900bb4c0f30a67157b6634be9d648bf9ada22/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java#L49)):*
> ```Java
>   boolean sampleDelegate;
>   boolean keepAlivePacket;
>   boolean heartbeatPacket;
> ```

consider renaming it to isHeartbeatRequest


<!-- Sent from Reviewable.io -->

2022-06-06 14:22 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33961)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1683 at r1](https://reviewable.io/reviews/harness/harness-core/33961#-N3t3tac0ngDH-H1dcIT:-N3tNRm67LNGniAgN_IU:b-xmqy2x) ([raw file](https://github.com/harness/harness-core/blob/0c4900bb4c0f30a67157b6634be9d648bf9ada22/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1683)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

How we are handling this on manager side ? I can't see those changes
</blockquote></details>

It is part of PR, hidden in reviewable not sure why. please refer to: 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java in https://github.com/harness/harness-core/pull/33961/files
___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/33961#-N3sp5_WBsRTLVLfAbaZ:-N3tNpxwETfbbGJe9JKF:b-jfq451) ([raw file](https://github.com/harness/harness-core/blob/0c4900bb4c0f30a67157b6634be9d648bf9ada22/420-delegate-service/src/main/java/io/harness/delegate/beans/Delegate.java#L93)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Why this got changed ?
</blockquote></details>

This will be used in https://github.com/harness/harness-core/blob/develop/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L125
___
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/33961#-N3t3pjoC54EudRHn0RY:-N3tNypG1ppcTXtU_KNR:btnf8gs) ([raw file](https://github.com/harness/harness-core/blob/0c4900bb4c0f30a67157b6634be9d648bf9ada22/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java#L49)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

consider renaming it to isHeartbeatRequest
</blockquote></details>

sure, will change it to heartRequest as renaming to isHeartbeatRequest will change the getter function to isIsHeartbeatRequest


<!-- Sent from Reviewable.io -->

2022-06-09 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=33961) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=33961) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=33961) it.</sub>

2022-06-09 11:19 UTC, closed without merging