[CCM-7875]: Add CCM related resources, roles and permissions
harness/harness-core pull request #34050
Opened 2022-06-07 11:41 UTC by svmav

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-08 05:56 UTC, hitesharinga requested changes

2022-06-08 05:56 UTC, hitesharinga commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: ccm_budget_edit
budget permissions are present twice.

2022-06-08 09:31 UTC, svmav commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: ccm_budget_edit
removed duplicate permissions

2022-06-09 09:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34050) it.</sub>

2022-08-01 20:08 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 #### 3 Issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 3 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/34050)

2022-08-07 18:50 UTC, svmav commented
trigger ti1

2022-08-07 19:13 UTC, reetika04 approved these changes
> Reviewed 1 of 14 files at r4, 26 of 26 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34050)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-07 22:38 UTC, hitesharinga reviewed
> Reviewed 1 of 14 files at r4, 26 of 26 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34050)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-07 22:38 UTC, hitesharinga approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34050)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-07 22:39 UTC, merged