techdebt: [CDS-38177]: Referncing the userGroups
harness/harness-core pull request #34105
Opened 2022-06-08 08:04 UTC by Y0709

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-08 08:13 UTC, Y0709 commented
trigger messagecheck

2022-06-08 14:25 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/service/impl/compliance/GovernanceConfigServiceImpl.java
> +      userGroupService.removeParentsReference(id, accountId, appId, EntityId, "GOVERNANCE_CONFIG");
small E in entity id

2022-06-09 07:09 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/service/impl/compliance/GovernanceConfigServiceImpl.java
> +    List<TimeRangeBasedFreezeConfig> newTimeRangeBasedFreezeConfigs = updatedSetting.getTimeRangeBasedFreezeConfigs();
add to execption msg in usergroupserviceimpl about ref in deployment freeze

2022-06-09 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34105) it.</sub>

2022-06-13 15:28 UTC, Y0709 commented
trigger codebasehash

2022-06-14 09:34 UTC, hingerabhinav approved these changes
> Reviewed 31 of 31 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34105)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-15 11:02 UTC, Y0709 commented
trigger ft1 ,ft2

2022-06-15 13:10 UTC, hingerabhinav submitted a review, later dismissed
> Reviewed 71 of 71 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34105)* status: :shipit: complete! ✓

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddDeploymentFreezeReferenceToUserGroups.java` line 54 at r5](https://reviewable.io/reviews/harness/harness-core/34105#-N4bSfIHBKi1P-cY5QOv:-N4bSfIHBKi1P-cY5QOw:b-gwdnx2) ([raw file](https://github.com/harness/harness-core/blob/afa30573d43097ed92b762e7c57ae63dbd52ef35/390-db-migration/src/main/java/io/harness/migrations/all/AddDeploymentFreezeReferenceToUserGroups.java#L54)):*
> ```Java
>           governanceConfigService.getReferencedUserGroupIds(governanceConfig.getTimeRangeBasedFreezeConfigs());
>       for (String id : userGroupIds) {
>         userGroupService.addParentsReference(
> ```

We're doing 1 API call for each user group that is used in a deployment freeze. 
Please check the number of user groups in QA/Prod per account. 


<!-- Sent from Reviewable.io -->

2022-06-16 08:04 UTC, abhinav-harness requested changes
> Reviewed 4 of 31 files at r4, 46 of 71 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34105)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/compliance/GovernanceConfigServiceImpl.java` line 254 at r5](https://reviewable.io/reviews/harness/harness-core/34105#-N4fNuxc6_BIW9xOzvYF:-N4fNuxc6_BIW9xOzvYG:b-n3ltsk) ([raw file](https://github.com/harness/harness-core/blob/afa30573d43097ed92b762e7c57ae63dbd52ef35/400-rest/src/main/java/software/wings/service/impl/compliance/GovernanceConfigServiceImpl.java#L254)):*
> ```Java
>     } catch (Exception e) {
>       log.error(
>           "error while fetching the timeRangeBasedFreezeConfig in account with id {} in Governance Config with id {}",
> ```

add user group info too 


<!-- Sent from Reviewable.io -->

2022-06-16 08:41 UTC, abhinav-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34105)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-16 09:21 UTC, abhinav-harness approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34105)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-16 10:58 UTC, abhinav-harness approved these changes
> Reviewed 22 of 71 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34105)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-16 11:36 UTC, poojaSinghal requested changes
> Reviewed 3 of 31 files at r4, 47 of 71 files at r5, 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34105)* status: :shipit: complete! ✓

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddDeploymentFreezeReferenceToUserGroups.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/34105#-N4gI9AEA395nYM2mKPP:-N4gI9AF5GZPyQSRMhFY:b-7cfvrg) ([raw file](https://github.com/harness/harness-core/blob/4235d56f8711d24b8916089b22fad2b3f087dc28/390-db-migration/src/main/java/io/harness/migrations/all/AddDeploymentFreezeReferenceToUserGroups.java#L47)):*
> ```Java
> 
>   private void migrateDeploymentFreezeWindowsForAccount(Account account) {
>     try {
> ```

add log line
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddDeploymentFreezeReferenceToUserGroups.java` line 52 at r6](https://reviewable.io/reviews/harness/harness-core/34105#-N4gIAPD8k-NaPKZNyKO:-N4gIAPD8k-NaPKZNyKP:b555i5p) ([raw file](https://github.com/harness/harness-core/blob/4235d56f8711d24b8916089b22fad2b3f087dc28/390-db-migration/src/main/java/io/harness/migrations/all/AddDeploymentFreezeReferenceToUserGroups.java#L52)):*
> ```Java
>                                               .get();
>       Set<String> userGroupIds =
>           governanceConfigService.getReferencedUserGroupIds(governanceConfig.getTimeRangeBasedFreezeConfigs());
> ```

add null check 


<!-- Sent from Reviewable.io -->

2022-06-16 12:05 UTC, merged