[feat]: [CDS-38131]: adding azure kubeconfig cluster user logic and updating …
harness/harness-core pull request #34123
Opened 2022-06-08 13:53 UTC by markoharness

…kubectl and helm usages

## Describe your changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/34123)

2022-06-08 15:13 UTC, markoharness commented
trigger feature-build

2022-06-09 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34123) it.</sub>

2022-06-09 21:14 UTC, markoharness commented
trigger feature-build

2022-06-10 09:50 UTC, markoharness commented
trigger publish-delegate

2022-06-14 15:36 UTC, markoharness commented
trigger feature-build

2022-06-14 15:36 UTC, markoharness commented
trigger publish-delegate

2022-06-14 21:37 UTC, markoharness commented
trigger feature-build

2022-06-15 10:36 UTC, abosii-harness requested changes
> Reviewed 64 of 68 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34123)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4amzlICfvae3-sF6ar:-N4amzlJ77-9FHtpcpoO:b-22rbhv) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L104)):*
> ```Java
>             .subscription(k8sAzureInfrastructure.getSubscriptionId().getValue())
>             .resourceGroup(k8sAzureInfrastructure.getResourceGroup().getValue())
>             .useClusterAdminCredentials(k8sAzureInfrastructure.getUseClusterAdminCredentials().getValue())
> ```

we should use ParameterFieldHelper.getBooleanParameterFieldValue instead, not sure if it was fixed or not, but expressions for boolean in parameter field will be resolved as string value
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4aoBbICCUwgJPKUzLr:-N4aoBbJ3drbUpF1-7S2:btsfqvr) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L162)):*
> ```Java
>     log.info(format("Number of retrieved resource groups: %s", response.getResourceGroups().size()));
>     if (response.getResourceGroups().size() > 0) {
>       log.info(format("Retrieved resource groups (listing first %s only): %s", ITEM_LOG_LIMIT,
> ```

nit: first %d 
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 243 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4aoENl1FhlLISmCptE:-N4aoENl1FhlLISmCptF:bx1f42x) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L243)):*
> ```Java
>     log.info(format("Number of retrieved container registries: %s", response.getContainerRegistries().size()));
>     if (response.getContainerRegistries().size() > 0) {
>       log.info(format("Retrieved container registries (listing first %s only): %s", ITEM_LOG_LIMIT,
> ```

nit: first %d
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 470 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4aocxE2v44Celf13_F:-N4aocxE2v44Celf13_G:b-73u9j9) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L470)):*
> ```Java
>         if (azureConfig.getAzureAuthenticationType() == AzureAuthenticationType.SERVICE_PRINCIPAL_SECRET
>             || azureConfig.getAzureAuthenticationType() == AzureAuthenticationType.SERVICE_PRINCIPAL_CERT) {
>           scope.append("/.default");
> ```

nit: this should be a constant
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 523 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4aqVMg6zIgJdmq-lv2:-N4aqVMg6zIgJdmq-lv3:brnwylj) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L523)):*
> ```Java
>       }
> 
>       if (isEmpty(azureKubeConfig.getCurrentContext())) {
> ```

Is that an actually a problem if there is no current context? Doesn't look like it does matter for our logic
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 539 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4aptQh57T_JRxYKwN1:-N4aptQh57T_JRxYKwN2:bjothn9) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L539)):*
> ```Java
>       }
> 
>       if (isEmpty(azureKubeConfig.getUsers().get(0).getUser().getAuthProvider().getConfig().getConfigMode())) {
> ```

Is configmode really required? I've seen few examples where it is not in kubeconfig. Not sure, just checking
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 573 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4ar6Fr8SfRg28u23AB:-N4ar6Fr8SfRg28u23AC:bo5botf) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L573)):*
> ```Java
>           .clusterUser(azureKubeConfig.getUsers().get(0).getName())
>           .currentContext(azureKubeConfig.getCurrentContext())
>           .apiServerId(azureKubeConfig.getUsers().get(0).getUser().getAuthProvider().getConfig().getApiServerId())
> ```

maybe it will be better to move specific to azure oauth fields to a different class so it will not create confusion?
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/AzureAsyncTaskHelperTest.java` line 702 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4asci2C0zXTJh-B8pd:-N4asci2C0zXTJh-B8pe:bv3lydk) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/AzureAsyncTaskHelperTest.java#L702)):*
> ```Java
>     assertThat(clusterConfig.getCaCert())
>         .isEqualTo(
>             "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQXRDZ0F3SUJBZ0lRVXU5YmZmK2dPZjZmUjZZY3RkRTE5VEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TWpBek1URXdPREUwTXpSYUdBOHlNRFV5TURNeE1UQTRNalF6TkZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUM3CktrVmI5MjFOanFNaXYxKzdjRFV4VEgzNm5QV05ieWRvY3ltQTVXUkx5SkU3SVJ3SzBQQWFkaHNEcHNiKzl5aCsKeU41cE11SktoQ09HQnFIbUQwQlBRSnhmck9CcDMrYUpiN1gyOUxrd3l6dzZhQy9BT1FxalhjK05yVjcvTElPcQpxcGFVTlpWMnB0T3FWVXE2cld5eE1GZnprbGFUeTRWMTBhNWFSMFZKcDg1Mjd3SzBLUTJPQXRwMVhIaE9vUzlTCkhvRUE2TjVFSEd0SVdzMEFBMjVsbTMraDNxM2xaZkQrMXdWQnR1bHRHL2VqS285d3VaZllpVGZSVjRrdDNUd0IKK21iU0t6cFp0c1FQcVZhRy8vcXdJbllkQ1pmUmp0dnA3VnM1bk5IQkpybTlDN3VTQzVJbnNKZk1Vd0w3Vjc4WApOS0JmZko0bGlyMXhEUFZNWHhsWW1udTZmQXFXM1lYOEk3bG9LVGQ4cDlvYkV1citYVzk3Mm1PRFpzQ3RoSURlClNPL0xheWNjU0YvUSt1SHZ2YjJOME85THowcjZsd0JSQk5zdFRvcXZseDdnRFd5dDdwQjloRThUaUNrU3FDaUcKMG5vanhtTFBYUlMxd2lEcURUUDRkcXlhRDV1aTYrOGduTWFaQjhTUTlHMk1hcCtWSWQ1cmdyRjZVbGRzOXFmUApuS3NhVWRPTTBDMlVSejFnZXBmdjM0Ym4xSC83WVJuUk5GSEZGQUU2amh1amIvM091NGpUSEdZeitSRkc4bW5CCjdYYkk0aW5GeFZjRXQ2MC96TEZpcU5MNWtBMDI3R1lMdjNtV1JNQkxKOTJ2UmYrVlZxTVN3d1NCZGVzWVVQcTkKcnF0dFIyOXpvT3ZhRWJMK1JNc2x5TVZaMmZyMkFFVWFnbHFKTEtodVNRSURBUUFCbzBJd1FEQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUwdllXVkpaazRRYzdVWi9BCjhHTXAwUWpXVDJvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFCbG9YOExqalROdW5wUlhnam1ERlgyb2F4RGEKajdXaUl1NDc5aXo2eHUwVXNWbVNaQXYwQ05BMTE1c0lKSDJ6aVZTdlpCM1hTL05EN2dGa0NWaXFmVDNOdDRFLwpHdEJ3SXluN2g4dGFnanRzZlEyc0FpUFpJb2QxM2dZK2czSEdzU0FMMGxJc0d6QWVPKzBmanNmVTluSmdFanIvClJiamdSQUpkUTFDL0piTXJhQzJtT1VTc281dmhrOTg5bzg2WkpyZi85WUV4MW1XYlFpT0VTQW1McUZnL205YzcKWkw0N012bWFiYzc2Y0VPVURBeGgzYmlsTFU4anFkZEFCUmFXdzltTGRTdmFSTWNVT0NxeWFZT3Q0NVBRMzlxMQpPNFJMZFhqZmI2b0R5U2FtRUxNMW1zMUFPNGh4c1B5aWZIVFd4TlB2QWVVRGJtc0h3elFobVlCWHJTNjA4ekJRCm41eTkvTEsvT3VtWHpPYW4zdzlKWmxqeFBWbkI2aWRReXFpYWVaRnMvRXdWcXRBK2lOYzdzdDdTZ0ZSZ1hQck8KMElGeUd6My9HMVdCMTFJazVMVU9ZVTFONk00bzU1MURRMW5IeWdkV1gvRG9lSmZ3dklTWk9hMVh0RjQ3TG1KNgpUZnFDTEMzMlBhbTl3V2VxbG1jeTMrRFgyWitQUFRuN1luT2NYeVZEUk9SVFhSYUl2NGlmMW1zMVd [...]

2022-06-15 20:55 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 492 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cV4Hj2FQbehUZTckf:-N4d8HpzChJNfKANu2Zz:bpwnoab) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L492)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Separate method for building scope with meaningful name. What is scope is null? 
</blockquote></details>

It defaults to what Azure SDK has predefined. In this case we are leaving it null only for Managed Identity.


<!-- Sent from Reviewable.io -->

2022-06-15 21:07 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java` line 509 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cY3N41pojDfE_O_g3:-N4dAkmY7uxjr85R1zHw:bn2zxrm) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L509)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - I suggest to have separate class for building commands. 
</blockquote></details>

This is just a method which is used for logging the command.
There is too much logic that I do not wish to tackle now in order to move building commands to a separate class (like we do for kubectl).


<!-- Sent from Reviewable.io -->

2022-06-16 09:10 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4amzlICfvae3-sF6ar:-N4flhC07XapyuO_ni9r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L104)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

we should use ParameterFieldHelper.getBooleanParameterFieldValue instead, not sure if it was fixed or not, but expressions for boolean in parameter field will be resolved as string value
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:10 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cLAO87NppqNC6W9Tt:-N4flkhu8E1kbCj6gY76:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L120)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I think we don't need log.isDebugEnabled(), the same comment for all below 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:11 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 445 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cVltOAd4VwP25npde:-N4flxCsD5Huco9QyjDd:bikz5km) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L445)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - maybe we can move all these logic related to building and validation KubernetesConfig to separate class. 
</blockquote></details>

We can do that in a another PR.


<!-- Sent from Reviewable.io -->

2022-06-16 09:11 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 463 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cULVN2-ThnJo4eArT:-N4fm11D5BIwVHMLcjl0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L463)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we separate logic for fetch AAD token to new method with meaningful name, also i will create separate methods for building different scopes.  
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:11 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 470 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cUrU71rkJnchci3lc:-N4fm3st5oPmrx3i3Fxa:bd9rrls) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L470)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This will be serverId/.default. Is it ok?  
</blockquote></details>

yes. that is how it should be for SP users


<!-- Sent from Reviewable.io -->

2022-06-16 09:12 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 523 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4aqVMg6zIgJdmq-lv2:-N4fmBd82z15WoYedz8_:b8mr640) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L523)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is that an actually a problem if there is no current context? Doesn't look like it does matter for our logic
</blockquote></details>

I am not completely certain. I will check it out and create a separate PR for it if needed.


<!-- Sent from Reviewable.io -->

2022-06-16 09:12 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 539 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4aptQh57T_JRxYKwN1:-N4fmKXFE9WnTIesiOHg:b8mr640) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L539)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is configmode really required? I've seen few examples where it is not in kubeconfig. Not sure, just checking
</blockquote></details>

I am not completely certain. I will check it out and create a separate PR for it if needed.


<!-- Sent from Reviewable.io -->

2022-06-16 09:13 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 573 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4ar6Fr8SfRg28u23AB:-N4fmQBI3KaaerqPPZ6D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L573)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

maybe it will be better to move specific to azure oauth fields to a different class so it will not create confusion?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:13 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/client/AzureManagementRestClient.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cWXf7AIBTJQqI8p9h:-N4fmVqg0cONRLUlPDAi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/azure/client/AzureManagementRestClient.java#L41)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should be a part of AzureKubernetesRestClient
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:14 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java` line 167 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4atXSY8o0VUYTXcRCw:-N4fmXjB06bfsM-caD6v:bu3za6) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/azure/impl/AzureAuthorizationClientImpl.java#L167)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Moved all added debug logs to trace mode.


<!-- Sent from Reviewable.io -->

2022-06-16 09:14 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java` line 184 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cXMsuEZoJT4xjL6Eu:-N4fmf-X5rBZodfMBtxf:bgprxxa) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/azure/impl/AzureContainerRegistryClientImpl.java#L184)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Avoid logging tokens(access, refresh)
</blockquote></details>

Moved all debug logging to trace logging


<!-- Sent from Reviewable.io -->

2022-06-16 09:14 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java` line 630 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cXkRW099Xocwlmsur:-N4fmlLZ68NiG86p1tSG:bgprxxa) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java#L630)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Avoid logging tokens 
</blockquote></details>

Moved all debug logging to trace logging


<!-- Sent from Reviewable.io -->

2022-06-16 09:15 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java` line 649 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cXtgCDAkxMktS_ZyU:-N4fmpliCZrbdNOgG7SS:bgprxxa) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java#L649)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Avoid logging credentials. 
</blockquote></details>

Moved all debug logging to trace logging


<!-- Sent from Reviewable.io -->

2022-06-16 09:15 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/k8s/model/KubernetesConfig.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4c_2qI6txLqt4S9gxd:-N4fn-P371xzJvfDpFcF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/k8s/model/KubernetesConfig.java#L82)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Create the new data structure instead of all these params.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:17 UTC, markoharness commented
*[`970-api-services-beans/src/main/java/io/harness/azure/model/kube/AzureKubeConfig.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4c_iNMAfH6BXydh4SO:-N4fn2f17REqC8xLJugt:bs13r79) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/970-api-services-beans/src/main/java/io/harness/azure/model/kube/AzureKubeConfig.java#L27)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Why do we need contexts and currentContext? 
</blockquote></details>

It is something we are always receiving and I wanted to keep it for kubeconfig consistency.
I will test if it is absolutely necessary and do it via another PR if needed.


<!-- Sent from Reviewable.io -->

2022-06-16 09:17 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/client/AzureManagementClient.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cWLg23N3_hFpMSfE6:-N4fnPse2kppyH5Pkz3H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/azure/client/AzureManagementClient.java#L183)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This should be part of AzureKubernetesClient.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:18 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/AzureTokenAuthentication.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4av-Np8FIA1ABclgIv:-N4fnSjn5ERrgrEex33P:b-kzg4j0) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/k8s/apiclient/AzureTokenAuthentication.java#L38)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

so is there any difference between AzureTokenAuthentication and AccessTokenAuthentication?
</blockquote></details>

removed AzureTokenAuthentication. Using AccessTokenAuthentication instead.


<!-- Sent from Reviewable.io -->

2022-06-16 09:18 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/AzureTokenAuthentication.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cYzA69ZdvQtEtxicZ:-N4fnXM25dgmyTmZykr0:b-kzg4j0) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/k8s/apiclient/AzureTokenAuthentication.java#L22)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Why do we need Interceptor?
</blockquote></details>

removed AzureTokenAuthentication. Using AccessTokenAuthentication instead.


<!-- Sent from Reviewable.io -->

2022-06-16 09:28 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/k8s/kubectl/AbstractExecutable.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/34123#-N4cZDF_BoJSTYcDE_O9:-N4fpy411GxtDRHK9V9J:b-jy9wkf) ([raw file](https://github.com/harness/harness-core/blob/6c39c9c699e959c4d53c251994d1f76569981b28/960-api-services/src/main/java/io/harness/k8s/kubectl/AbstractExecutable.java#L49)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - I suggest to have separate class for building commands. 
</blockquote></details>

removed this logic


<!-- Sent from Reviewable.io -->

2022-06-16 09:46 UTC, markoharness commented
trigger feature-build

2022-06-16 10:52 UTC, markoharness commented
trigger ti3

2022-06-16 11:22 UTC, ivan-83 submitted a review, later dismissed
LGTM with a note - I will avoid trace logs because I don't think we will enable Trace level on Prod, stage, or even QA, this only can be useful in local development, but then we can use the debugger to see the content of tokens.

> Reviewed 33 of 48 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34123#-:-N4gE5Uy-GBfIv_QKYKD:buww3gh)* status: 1 change requests. 8. unresolved discussions. 

___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/34123#-N4gCzZr99f6XIgPpg0b:-N4gCzZr99f6XIgPpg0c:b4xp1k4) ([raw file](https://github.com/harness/harness-core/blob/4515bb7431bb28a269ad8d9a38472da0ada16432/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L77)):*
> ```Java
>       clientBuilder.setAuthentication(new AccessTokenAuthentication(tokenRetriever.getOidcIdToken(kubernetesConfig)));
>     } else if (kubernetesConfig.getAzureConfig() != null && kubernetesConfig.getAzureConfig().getAadIdToken() != null) {
> //      clientBuilder.setAuthentication(new AzureTokenAuthentication(kubernetesConfig.getAzureConfig().getAadIdToken()));
> ```

Minor - remove comment here.


<!-- Sent from Reviewable.io -->

2022-06-16 11:37 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 17 of 48 files at r3, 7 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34123)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/k8s/model/KubernetesAzureConfig.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/34123#-N4gIF6Y7HetZTYIxMbd:-N4gIF6Y7HetZTYIxMbe:b-azun75) ([raw file](https://github.com/harness/harness-core/blob/4515bb7431bb28a269ad8d9a38472da0ada16432/960-api-services/src/main/java/io/harness/k8s/model/KubernetesAzureConfig.java#L31)):*
> ```Java
>   private String aadIdToken;
> 
>   @Builder
> ```

nit: Builder can be set at class level. Builder on constructor is mostly required if you're extending a super class, otherwise is adding some complexity in adding new field


<!-- Sent from Reviewable.io -->

2022-06-16 12:43 UTC, merged