feat: [STO-3683]: STO RBAC definitions
harness/harness-core pull request #34224
Opened 2022-06-10 22:22 UTC by r0610205

## Describe your changes
PR Includes RBAC definitions for STO module

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-14 20:57 UTC, chris-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: sto_test_target_view
I currently use `target` instead of `test_target` to refer to these

2022-06-14 20:57 UTC, chris-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: sto_issue_create
Issue `view` permission seems to be missing here

2022-06-15 02:45 UTC, gupta-utkarsh requested changes
Please update the version in the top  of each yaml when you are making changes to the yaml.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34224#-:-N4_EzAf8aeU8G2F6rVY:b-38if6b)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 860 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_EGKf4nzRKGwmezPI:-N4_EGKf4nzRKGwmezPJ:b3sug2d) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L860)):*
> ```YAML
>       - organization
>       - project
>   - identifier: sto_overview_page_view
> ```

This should be sto_overviewpage_view. Please make the resourceType permissionKey as "overviewpage".
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 876 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_E7utE2o6n1qgJDrP:-N4_E7utE2o6n1qgJDrQ:bi82ebv) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L876)):*
> ```YAML
>       - organization
>       - project
>   - identifier: sto_test_target_create
> ```

We do not support names with 4 parts. This can be sto_target_create or sto_testtarget_create. Please make the resourceType permissionKey is the same as the second part of the permission.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 610 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_EobF9h0N7iLEWEM6:-N4_EobF9h0N7iLEWEM7:bn97opw) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L610)):*
> ```YAML
>         - gitops_cert_view
>         - gitops_cert_edit
>         - gitops_cert_delete
> ```

The Gitops Admin role is edited as well. Please revert those changes.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 622 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_EfgK6_GynCs5mTEU:-N4_EfgK6_GynCs5mTEV:blxnju1) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L622)):*
> ```YAML
>         - sto_test_target_edit
>         - sto_exception_view
>         - sto_exception_create
> ```

Please add the scope levels at which this role is available.


<!-- Sent from Reviewable.io -->

2022-06-15 15:17 UTC, r0610205 commented
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 610 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_EobF9h0N7iLEWEM6:-N4bwDpgC0KzViFlAs-L:b-tdmo2c) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L610)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

The Gitops Admin role is edited as well. Please revert those changes.
</blockquote></details>

I didn't modify Gitops Admin, only Project Admin & Project Viewer


<!-- Sent from Reviewable.io -->

2022-06-15 15:22 UTC, r0610205 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34224)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 860 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_EGKf4nzRKGwmezPI:-N4bw97-3V4E_9ADR_93:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L860)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

This should be sto_overviewpage_view. Please make the resourceType permissionKey as "overviewpage".
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 861 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4EhdfwcPhnqVj3OcfD-r1-861:-N4bwA8C4elO3s4pQlFz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L861)):*
<details><summary><i>Previously, chris-harness (Chris Hamper) wrote…</i></summary><blockquote>

```suggestion
    name: View Security Tests Overview Page
```
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 868 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4EhdfwcPhnqVj3OcfD-r1-868:-N4bwAfk-bHtUSiRr_dT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L868)):*
<details><summary><i>Previously, chris-harness (Chris Hamper) wrote…</i></summary><blockquote>

I currently use `target` instead of `test_target` to refer to these
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 876 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_E7utE2o6n1qgJDrP:-N4bwBZ49NjUJmxvT4bd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L876)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

We do not support names with 4 parts. This can be sto_target_create or sto_testtarget_create. Please make the resourceType permissionKey is the same as the second part of the permission.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 932 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4EhdfwcPhnqVj3OcfD-r1-932:-N4bwCMf25gimgcJmeXP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L932)):*
<details><summary><i>Previously, chris-harness (Chris Hamper) wrote…</i></summary><blockquote>

Issue `view` permission seems to be missing here
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 622 at r1](https://reviewable.io/reviews/harness/harness-core/34224#-N4_EfgK6_GynCs5mTEU:-N4bxN7t31keK_6A1Pwz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd757b81f50c8aa16983136d613c99e7a324718e/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L622)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Please add the scope levels at which this role is available.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-15 15:44 UTC, chris-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +    permissionKey: target
FF already uses the `target` permission key, so we may be stuck with `test_target` here

2022-06-15 15:44 UTC, chris-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +      - project
Our APIs currently are not designed to restrict access to the org or project level. Should we work to support this for GA, or only allow `account` scope for now?

2022-06-22 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34224) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34224) it.</sub>

2022-06-24 14:41 UTC, r0610205 commented
trigger ti0

2022-06-25 07:02 UTC, gupta-utkarsh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34224#-:-N5Oep_ICrPxbkCmkiLn:bnfp4nl)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-06-26 20:19 UTC, merged