feat: [SRM-10734]: Add proper host filter to prometheus
harness/harness-core pull request #34235
Opened 2022-06-12 20:51 UTC by AbhijithHarness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-12 20:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34235) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34235) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34235) it.</sub>

2022-06-13 04:28 UTC, kjoshi12345 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34235)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/resources/prometheus/dsl/metric-collection.datacollection` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/34235#-N4QJSch20VOdSSTQ4cA:-N4QJSch20VOdSSTQ4cB:bsfvpm4) ([raw file](https://github.com/harness/harness-core/blob/30479940f309be8b710524ef27ebd9c3350b57b0/300-cv-nextgen/src/main/resources/prometheus/dsl/metric-collection.datacollection#L17)):*
> ```
> 
>     if Env:collectHostData == "true" {
>         Var hostQuery = concat(Env:baseUrl, "api/v1/label/", Var:serviceInstanceField, "/values?start=", Env:startTimeSeconds,"&end=", Env:endTimeSeconds, "&match[]={", Var:filters, "}")
> ```

does this work fine if filters is empty? Can Var:filters be null?


<!-- Sent from Reviewable.io -->

2022-06-13 04:59 UTC, AbhijithHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34235)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/resources/prometheus/dsl/metric-collection.datacollection` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/34235#-N4QJSch20VOdSSTQ4cA:-N4QQE9LAZa5FZtABRpl:b-pke5fj) ([raw file](https://github.com/harness/harness-core/blob/30479940f309be8b710524ef27ebd9c3350b57b0/300-cv-nextgen/src/main/resources/prometheus/dsl/metric-collection.datacollection#L17)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

does this work fine if filters is empty? Can Var:filters be null?
</blockquote></details>

No, it doesnt. But it can't be null, it throws exception in info-mapper only.


<!-- Sent from Reviewable.io -->

2022-06-13 05:02 UTC, kjoshi12345 approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34235)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-13 05:02 UTC, merged