[DEL-]Remove unused parked task api's in delegate
harness/harness-core pull request #34330
Opened 2022-06-15 04:44 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

2022-06-15 04:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34330) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34330) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34330) it.</sub>

2022-06-15 20:04 UTC, raghuAtWings approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34330)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-17 15:46 UTC, harshjain12 commented on 910-delegate-task-grpc-service/src/main/java/io/harness/task/service/impl/TaskServiceImpl.java
> -  public void taskProgress(TaskProgressRequest request, StreamObserver<TaskProgressResponse> responseObserver) {
This is being used in CD.
Do not remove it.

2022-06-17 15:47 UTC, harshjain12 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34330)* status: 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-20 16:41 UTC, jennyjames21 commented on 910-delegate-task-grpc-service/src/main/java/io/harness/task/service/impl/TaskServiceImpl.java
> -  public void taskProgress(TaskProgressRequest request, StreamObserver<TaskProgressResponse> responseObserver) {
There are 2 taskprogress api's, one related to parked task and other sendTaskProgress which is used to send task status.i removed specific to parked task.  Why do CD team parked task? Who is contact person in CD who is aware of this flow?

2022-06-22 06:08 UTC, harshjain12 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34330)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-22 06:37 UTC, merged