feat: [CI-4540]: Added step group support in CI
harness/harness-core pull request #34364
Opened 2022-06-15 12:01 UTC by devkimittal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/34364)

2022-06-15 12:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34364) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34364) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34364) it.</sub>

2022-06-16 14:34 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +    int stepIndex = 0;
ignore this

2022-06-20 06:04 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public List<ContainerDefinitionInfo> createStepContainerDefinitions_feature(List<ExecutionWrapperConfig> steps,
Method name should follow camel case

2022-06-20 06:04 UTC, harshjain12 commented
Add Unit tests and Put your change behind ff.

2022-06-20 06:06 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +    for (ExecutionWrapperConfig executionWrapper : steps) {
refactor this method.
It is not readable.
Divide it into small methods

2022-06-20 06:06 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +        if (temp != null) {
rename temp

2022-06-24 14:37 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +    for (ExecutionWrapperConfig executionWrapper : steps) {
Logic is getting quite complex here, this is what I could come up with

2022-06-28 06:28 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +      for (ExecutionWrapperConfig wrapper : stepGroupElementConfig.getSteps()) {
what if there is parallel section inside step group ?

2022-06-28 06:30 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void createStepContainerDefinitionsStepGroup1() throws Exception {
can you  name it better.
What is the difference with above 2 steps

2022-06-28 06:35 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/IntegrationStageUtils.java
> +  public void populateConnectorIdentifiers(
Updating the arguments is not a good idea. Readability is quite low. Instead it should return list of identifiers

2022-06-28 06:35 UTC, shubham149 commented
Do we have a doc on how step group will look like for CI? How will we calculate resources i.e. requests etc?

2022-06-28 07:16 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +      for (ExecutionWrapperConfig wrapper : stepGroupElementConfig.getSteps()) {
both single step and parallel step will be handled insdie getExecutionWrapperMemoryRequest method

2022-06-28 07:19 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/IntegrationStageUtils.java
> +  public void populateConnectorIdentifiers(
Since it was recursively calling itself, it seemed like a better option to me

2022-06-29 03:14 UTC, devkimittal commented
Doc used for resource allocation : https://harness.atlassian.net/wiki/spaces/~47984263/pages/21115371795/Resources+Calculation+for+step+groups

2022-06-29 06:15 UTC, shubham149 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsHelper.java
> +    JsonNode arrayNode = mapper.readValue("{\n"
Move this pipeline to a separate json file and read that file here

2022-06-29 06:15 UTC, shubham149 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsHelper.java
> +    JsonNode arrayNode = mapper.readValue("{\n"
Ditto

2022-06-29 07:23 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public List<ContainerDefinitionInfo> createStepContainerDefinitionsFeature(List<ExecutionWrapperConfig> steps,
Fix the method name. Unable to figure out what it intends to do from its method name.

2022-06-29 07:23 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  private List<ContainerDefinitionInfo> createStepContainerDefinitionsForStepGroup(
Move the 3 newly added methods after createStepContainerDefinitions method

2022-06-29 07:23 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public List<ContainerDefinitionInfo> createStepContainerDefinitionsFeature(List<ExecutionWrapperConfig> steps,
We should not have 2 different methods for step container definitions with and without step groups.

2022-06-29 07:23 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +    for (ExecutionWrapperConfig executionWrapper : steps) {
Readability is very important aspect of the code. Code is written once and read 10 times. Hence, it is important to write code that is easily readable.

2022-06-29 07:24 UTC, shubham149 commented
Improve the readability of K8InitializeStepUtils.java. I am not able to read from the beginning till the end of this file in one go.

2022-06-29 07:49 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/IntegrationStageUtils.java
> +  public void populateConnectorIdentifiers(
got your point, I'll make the change

2022-06-29 07:53 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public List<ContainerDefinitionInfo> createStepContainerDefinitionsFeature(List<ExecutionWrapperConfig> steps,
This is just for the testing purpose. I have put this code behind a feature flag so that it doesn't break much in prod. Once we are good with the testing then It will have only one method.

2022-06-29 08:04 UTC, devkimittal commented on 878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java
> +  @NotNull @EntityName @Pattern(regexp = NGRegexValidatorConstants.NAME_PATTERN) String name;
Got a go ahead from cd team, https://harness.slack.com/archives/CJFLDARK9/p1656483663234939

2022-06-29 08:05 UTC, devkimittal commented on 878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java
> +  @NotNull @EntityName @Pattern(regexp = NGRegexValidatorConstants.NAME_PATTERN) String name;
@harshjain12 @rajatharanganath

2022-06-29 14:32 UTC, devkimittal commented
trigger codebasehash

2022-06-29 14:32 UTC, devkimittal commented
trigger codeformat

2022-06-29 14:33 UTC, devkimittal commented
trigger compile

2022-06-29 14:33 UTC, devkimittal commented
trigger ti0

2022-06-29 14:33 UTC, devkimittal commented
trigger ti1

2022-06-29 14:35 UTC, rajatharanganath commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public List<ContainerDefinitionInfo> createStepContainerDefinitionsFeature(List<ExecutionWrapperConfig> steps,
Hey @devkimittal , I believe this is to ensure easy rollback in prod in case of an issue, than testing :)

2022-06-29 14:37 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public List<ContainerDefinitionInfo> createStepContainerDefinitionsFeature(List<ExecutionWrapperConfig> steps,
Yeah, I used the wrong keyword

2022-06-29 15:13 UTC, devkimittal commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public List<ContainerDefinitionInfo> createStepContainerDefinitionsFeature(List<ExecutionWrapperConfig> steps,
@rajatharanganath @shubham149 updated the code

2022-07-01 06:22 UTC, rajatharanganath approved these changes

2022-07-01 06:47 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  private List<ContainerDefinitionInfo> createStepContainerDefinitionsForStepGroup(
There are so many createStepContainerDefinitions* methods in this file. It is very hard to understand what each one is doing

2022-07-01 07:00 UTC, devkimittal commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsHelper.java
> +  private static JsonNode getRunStepsInStepGroupAsJsonNode1() throws Exception {
this is just for testing, method name will be too big if I state how they are different. I'll put a comment on a top of it.

2022-07-01 07:01 UTC, devkimittal commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsHelper.java
> +  private static JsonNode getRunStepsInStepGroupAsJsonNode1() throws Exception {
besides, they are exactly doing the same thing, just the memory and cpu request is different.

2022-07-01 12:21 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +      List<ContainerDefinitionInfo> definitionInfos = null;
Don't use it. Only it makes sense for all the step types, then usage of it would have been better

2022-07-01 12:21 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  private List<ContainerDefinitionInfo> handleStageStepGroup(ExecutionWrapperConfig executionWrapper,
Move this before handleStepGroup

2022-07-01 12:21 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  private List<ContainerDefinitionInfo> handleStepGroup(ExecutionWrapperConfig executionWrapper,
Move this after handleParallelStep

2022-07-04 05:08 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  private List<ContainerDefinitionInfo> handleStageStepGroup(ExecutionWrapperConfig executionWrapper,
stageMemoryRequest -> maxAllocatableMemoryRequest
stageCpuRequest -> maxAllocatableCpuRequest

After this, we won't require 2 stageGroup methods

2022-07-04 05:08 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +        StepElementConfig stepElementConfig = IntegrationStageUtils.getStepElementConfig(executionWrapperInParallel);
it should use handleSingleStep

2022-07-04 05:11 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  private List<ContainerDefinitionInfo> handleStageStepGroup(ExecutionWrapperConfig executionWrapper,
Instead of using stageMemoryRequest, we should use maxAllocatableMemoryRequest & update the code accordingly

2022-07-04 08:49 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +            step, integrationStage, ciExecutionArgs, portFinder, accountId, os, extraMemory, extraCpu, stepIndex);
This is wrong here

2022-07-04 10:28 UTC, shubham149 approved these changes
> Reviewed 6 of 16 files at r3, 2 of 10 files at r4, 5 of 10 files at r5, 5 of 7 files at r6, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364)* status: 2. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-07-04 10:28 UTC, shubham149 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364)* status: 2. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-07-04 14:21 UTC, shubham149 submitted a review, later dismissed
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364)* status: 2. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-07-04 14:29 UTC, devkimittal reviewed
> Reviewed 6 of 16 files at r3, 1 of 10 files at r4, 5 of 10 files at r5, 5 of 7 files at r6, 4 of 4 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364)* status: 2. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-07-04 14:33 UTC, devkimittal reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364#-:-N68cCDV0XmyLzLlJE5a:bnfp4nl)* status: 5. unresolved discussions. Waiting on team(s): sto. 

___
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/34364#-N4bEPrLxniCNjR5PQxs-r2-224:-N68c4ZRE5ttvr_SWAPm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1065a1b8bec6eb03121c20c7ea78b3313ff5c1a1/320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java#L224)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

Method name should follow camel case
</blockquote></details>

Done.
___
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java` line 235 at r2](https://reviewable.io/reviews/harness/harness-core/34364#-N4bEPrLxniCNjR5PQxs-r2-235:-N68c48h7WqFyLI9nMp5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1065a1b8bec6eb03121c20c7ea78b3313ff5c1a1/320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java#L235)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Readability is very important aspect of the code. Code is written once and read 10 times. Hence, it is important to write code that is easily readable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 19:00 UTC, r0610205 submitted a review, later dismissed

2022-07-05 02:41 UTC, devkimittal commented
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/34364#-N4bEPrLxniCNjR5PQxs-r2-224:-N6BDKdI4tq3_Kbm6MmU:bg7igkv) ([raw file](https://github.com/harness/harness-core/blob/1065a1b8bec6eb03121c20c7ea78b3313ff5c1a1/320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java#L224)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2022-07-05 03:59 UTC, harshjain12 approved these changes
> Reviewed 6 of 16 files at r3, 1 of 10 files at r4, 5 of 10 files at r5, 5 of 7 files at r6, 4 of 4 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-05 04:08 UTC, harshjain12 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364)* status: :shipit: complete! ✓

___
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java` line 154 at r10](https://reviewable.io/reviews/harness/harness-core/34364#-N6BX1Kh9WLGk1X3qn0W:-N6BX1Kh9WLGk1X3qn0X:b-3747xo) ([raw file](https://github.com/harness/harness-core/blob/e43ecf07ce665bda602d99325aae6d58999c2f25/320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java#L154)):*
> ```Java
>   }
> 
>   public List<ContainerDefinitionInfo> createStepContainerDefinitionsStepGroupFeature(
> ```

createStepContainerDefinitionsStepGroupFeature ---> createStepContainerDefinitionsStepGroupWithFF



_Code quote:_
```Java
createStepContainerDefinitionsStepGroupFeature
```
___
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java` line 760 at r10](https://reviewable.io/reviews/harness/harness-core/34364#-N6BXHl96qSkspwF1nrQ:-N6BXHl96qSkspwF1nrR:b3b20oq) ([raw file](https://github.com/harness/harness-core/blob/e43ecf07ce665bda602d99325aae6d58999c2f25/320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java#L760)):*
> ```Java
>   }
> 
>   public void getStepConnectorRefsUtil(ExecutionWrapperConfig executionWrapperConfig, Ambiance ambiance,
> ```

It is not returning anything
Why method name has get ?
___
*[`320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java` line 66 at r10](https://reviewable.io/reviews/harness/harness-core/34364#-N6BXO6cEauk1I50F-ew:-N6BXO6cEauk1I50F-ex:buuxigt) ([raw file](https://github.com/harness/harness-core/blob/e43ecf07ce665bda602d99325aae6d58999c2f25/320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java#L66)):*
> ```Java
>   @Owner(developers = DEV_MITTAL)
>   @Category(UnitTests.class)
>   public void createStepContainerDefinitionsStepGroup() throws Exception {
> ```

createStepContainerDefinitionsStepGroup --> testStepContainerDefinitionsStepGroupWithLogic


<!-- Sent from Reviewable.io -->

2022-07-05 04:10 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/K8InitializeStepUtils.java
> +  public void getStepConnectorRefsUtil(ExecutionWrapperConfig executionWrapperConfig, Ambiance ambiance,
This method is not returning anything.
Why it has get in name ?

2022-07-05 04:11 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void createStepContainerDefinitionsStepGroup() throws Exception {
createStepContainerDefinitionsStepGroup ---> testStepContainerDefinitionsStepGroupWith**YourCase**

2022-07-05 04:11 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void createStepContainerDefinitionsStepGroupComplexPipeline() throws Exception {
createStepContainerDefinitionsStepGroup ---> testStepGroupCreationWithSectionCombinations

2022-07-05 04:12 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void getStepConnectorRefs() throws Exception {
it is not returning anything and method name has get

2022-07-05 04:12 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void getExecutionWrapperCpuRequestTest() throws Exception {
Same as above

2022-07-05 04:12 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void getExecutionWrapperMemoryRequestTest() throws Exception {
fix it

2022-07-05 04:14 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +        assertThat(stepContainer.getContainerResourceParams().getResourceLimitMemoryMiB()).isEqualTo(500);
better would have been to create map with step identifier as key and expected resources.

You will not have to duplicate this code with if else

2022-07-05 04:14 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +      if (stepContainer.getStepIdentifier().equals("step-2")) {
better would have been to create map with step identifier as key and expected resources.

You will not have to duplicate this code with if else

2022-07-05 04:15 UTC, harshjain12 commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +      if (stepContainer.getStepIdentifier().equals("step-2")) {
just fetch the expected value from map and validate it in iteration without these many if else

2022-07-05 05:48 UTC, rajatharanganath approved these changes

2022-07-05 05:57 UTC, devkimittal commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void getStepConnectorRefs() throws Exception {
getStepConnectorRefs is returning a map

2022-07-05 05:59 UTC, devkimittal commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +  public void getExecutionWrapperCpuRequestTest() throws Exception {
getExecutionWrapperCpuRequest is returning an integer.\
This is a test method, it is always void.

2022-07-05 06:01 UTC, devkimittal commented on 320-ci-execution/src/test/java/io/harness/ci/integrationstage/K8InitializeStepUtilsTest.java
> +        assertThat(stepContainer.getContainerResourceParams().getResourceLimitMemoryMiB()).isEqualTo(500);
the method returns a list, do you want me to convert it into a map first and then assert?

2022-07-06 04:55 UTC, harshjain12 approved these changes
> Reviewed 3 of 8 files at r11, 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34364)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-06 05:00 UTC, merged