techdebt: [CDS-38672]: Adding reference for runtime user-groups
harness/harness-core pull request #34457
Opened 2022-06-20 07:42 UTC by Y0709

## Adding usergroup\ reference that are present as part of runtime inputs so that they are not allowed to be deleted as long as they are being referenced there.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/34457)

2022-06-20 07:47 UTC, Y0709 commented
trigger messagecheck

2022-06-20 07:52 UTC, Y0709 commented
trigger messagecheck

2022-06-20 07:59 UTC, abhinav-harness approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34457)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-20 07:59 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34457)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java` line 2107 at r1](https://reviewable.io/reviews/harness/harness-core/34457#-N5-6tEzDqi--2qFcZsP:-N5-6tEzDqi--2qFcZsQ:b-bdyay2) ([raw file](https://github.com/harness/harness-core/blob/9809d8e5d9abcba4cc3e96dda5ffcc402ee328db/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L2107)):*
> ```Java
>         } else {
>           if (stageElement.getRuntimeInputsConfig() != null) {
>             List<String> userGroupIds = stageElement.getRuntimeInputsConfig().getUserGroupIds();
> ```

unit test?


<!-- Sent from Reviewable.io -->

2022-06-21 06:34 UTC, puthrayaharness requested changes

2022-06-21 06:34 UTC, puthrayaharness commented on 400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java
> +            for (String id : userGroupIds) {
You can simply do a `userGroups.addAll(userGroupIds)`

2022-06-21 06:34 UTC, puthrayaharness commented on 400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java
> +      for (PipelineStageElement stageElement : bean.getPipelineStageElements()) {
There is no need to change this logic? I don't think we have more than one pipelineStageElement.

2022-06-21 07:05 UTC, Y0709 commented
trigger messagecheck

2022-06-21 07:10 UTC, puthrayaharness approved these changes

2022-06-21 07:10 UTC, puthrayaharness approved these changes
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34457)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-21 10:24 UTC, merged