[fix]: [PL-25105]: improve api description for framework squad
harness/harness-core pull request #34554
Opened 2022-06-22 07:13 UTC by shreyas-harness

## Describe your changes
Improved description for API's
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-06-22 07:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34554) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34554) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34554) it.</sub>

2022-06-22 07:51 UTC, VikasMaddukuriHarness approved these changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34554)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-22 10:24 UTC, rashminandasahoo requested changes

2022-06-22 10:24 UTC, rashminandasahoo commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationResource.java
> +      description = "Lists all Organizations matching search criteria.",
List all Organizations matching the given search criteria.

2022-06-22 10:24 UTC, rashminandasahoo commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationResource.java
> +  @Operation(operationId = "getOrganizationList", summary = "List all Organizations using a filter",
List Organizations by filter

2022-06-22 10:24 UTC, rashminandasahoo commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java
> +      description = "Updates a Project's settings for the given ID.",
Updates Project details for the given ID.

2022-06-22 10:24 UTC, rashminandasahoo commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java
> +      description = "Deletes a Project for the specified Project ID.",
Deletes a Project corresponding to the given ID.

2022-06-22 10:24 UTC, rashminandasahoo commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java
> +      description = "Lists all Tokens matching search criteria.",
Lists all the Tokens matching the given search criteria.

2022-06-22 10:24 UTC, rashminandasahoo commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java
> +      description = "Update the details of the Service Account for the given Service Account ID.",
Updates details of the Service Account for the given Service Account ID.

2022-06-22 10:24 UTC, rashminandasahoo commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java
> +      description = "Deletes a Service Account for the given Service Account ID.",
Deletes a Service Account corresponding to the given Service Account ID.

2022-06-22 10:24 UTC, rashminandasahoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      description =
Looks like there is extra space at the beginning.

2022-06-22 10:24 UTC, rashminandasahoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      description = "Lists all Connectors matching specified filters.",
Lists all the Connectors matching the specified filters.

2022-06-22 10:24 UTC, rashminandasahoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      description = "Lists all Connectors for an Account using an account ID.",
Lists all the Connectors for the given Account ID.

2022-06-22 10:24 UTC, rashminandasahoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +  @Operation(operationId = "listConnectorByFQN", summary = "List all Connectors for an account",
The summary is the same as above?

2022-06-22 10:24 UTC, rashminandasahoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      description = "Returns the field values that are allowed for each Connector type.",
Returns the list of Connector settings for the given Connector type.

2022-06-22 10:24 UTC, rashminandasahoo commented on 955-filters-sdk/src/main/java/io/harness/filter/resource/FilterResource.java
> +      description = "Lists filters using specified criteria such as type.",
Lists filters for the given criteria.

Is filter a Harness entity? If yes then the casing should be "Filter".

2022-06-23 04:10 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +  @Operation(operationId = "listConnectorByFQN", summary = "List all Connectors for an account",
Thats what is mentioned in the sheet you shared. - https://docs.google.com/spreadsheets/d/13jCy23e4gBr5qUMTydZ4BhH2yQ3mtqqX9XzxGrkWMhY/edit#gid=0

2022-06-23 06:32 UTC, rashminandasahoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +  @Operation(operationId = "listConnectorByFQN", summary = "List all Connectors for an account",
I meant to ask if we have 2 APIs with the same name (summary)?

2022-06-23 07:00 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationResource.java
> +      description = "Lists all Organizations matching search criteria.",
Done

2022-06-23 07:00 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationResource.java
> +  @Operation(operationId = "getOrganizationList", summary = "List all Organizations using a filter",
Done

2022-06-23 07:00 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java
> +      description = "Updates a Project's settings for the given ID.",
Done

2022-06-23 07:01 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java
> +      description = "Deletes a Project for the specified Project ID.",
Done

2022-06-23 07:01 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java
> +      description = "Lists all Tokens matching search criteria.",
Done

2022-06-23 07:01 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java
> +      description = "Update the details of the Service Account for the given Service Account ID.",
Done

2022-06-23 07:01 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java
> +      description = "Deletes a Service Account for the given Service Account ID.",
Done

2022-06-23 07:02 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      description =
This isn't the case.

2022-06-23 07:02 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      description = "Lists all Connectors matching specified filters.",
Done

2022-06-23 07:02 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      description = "Lists all Connectors for an Account using an account ID.",
Done

2022-06-23 07:04 UTC, shreyas-harness commented on 955-filters-sdk/src/main/java/io/harness/filter/resource/FilterResource.java
> +      description = "Lists filters using specified criteria such as type.",
Done.

2022-06-24 05:01 UTC, rashminandasahoo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34554#-:-N5J4W1U6EEmNJjlskJh:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-06-24 05:12 UTC, VikasMaddukuriHarness approved these changes
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34554)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-06-24 05:56 UTC, merged