[feat]: [CDS-38353]: Email Step Skeleton Code
harness/harness-core pull request #34845
Opened 2022-06-29 17:48 UTC by vivekkarnatiharness

## Describe your changes
Have written all the boilerplate code for the email step

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/34845)

2022-06-29 17:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=34845) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=34845) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=34845) it.</sub>

2022-07-01 08:12 UTC, puthrayaharness requested changes

2022-07-01 08:12 UTC, puthrayaharness commented on 860-orchestration-steps/src/main/java/io/harness/plancreator/steps/email/EmailStepPlanCreator.java
> +public class EmailStepPlanCreator extends PMSStepPlanCreatorV2<EmailStepNode> {
Add all relevant annotations. e.g owned by

2022-07-01 08:12 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/email/EmailStepResponse.java
> +public class EmailStepResponse implements ResponseData {}
Add owned by

2022-07-01 08:12 UTC, puthrayaharness commented on 860-orchestration-steps/src/main/java/io/harness/plancreator/steps/email/EmailStepNode.java
> +@RecasterAlias("io.harness.steps.email.EmailStepNode")
This is not correct. I think it should be `io.harness.plancreator.steps.email.EmailStepNode`

2022-07-01 10:50 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-07-01 11:03 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-07-01 11:27 UTC, vivekkarnatiharness commented on 860-orchestration-steps/src/main/java/io/harness/plancreator/steps/email/EmailStepPlanCreator.java
> +public class EmailStepPlanCreator extends PMSStepPlanCreatorV2<EmailStepNode> {
In shellscriptstepplancreator,httpstepplancreator there is no annoations added.
So i have added only Ownedby(CDC) right now...

2022-07-01 11:27 UTC, vivekkarnatiharness commented on 860-orchestration-steps/src/main/java/io/harness/serializer/kryo/OrchestrationStepsKryoRegistrar.java
> +    //    kryo.register(EmailStepInfo.class, 13001);
Removed

2022-07-01 11:27 UTC, vivekkarnatiharness commented on 860-orchestration-steps/src/main/java/io/harness/steps/Email/EmailOutcome.java
> +@RecasterAlias("io.harness.steps.Email.EmailOutcome")
Done

2022-07-01 11:29 UTC, vivekkarnatiharness commented on 860-orchestration-steps/src/main/java/io/harness/steps/Email/EmailStep.java
> +public class EmailStep extends TaskExecutableWithRollback<EmailStepResponse> {
Done

2022-07-01 11:30 UTC, vivekkarnatiharness commented on 860-orchestration-steps/src/main/java/io/harness/steps/Email/EmailStepParameters.java
> +public class EmailStepParameters implements SpecParameters {
Done

2022-07-01 11:30 UTC, vivekkarnatiharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/email/EmailStepResponse.java
> +public class EmailStepResponse implements ResponseData {}
Done

2022-07-01 11:30 UTC, vivekkarnatiharness commented on 860-orchestration-steps/src/main/java/io/harness/plancreator/steps/email/EmailStepNode.java
> +@RecasterAlias("io.harness.steps.email.EmailStepNode")
Done

2022-07-01 11:37 UTC, vivekkarnatiharness commented on 860-orchestration-steps/src/main/java/io/harness/plancreator/steps/email/EmailStepInfo.java
> +    this.cc = cc;
done

2022-07-02 03:40 UTC, puthrayaharness approved these changes
> Reviewed 14 of 23 files at r2, 8 of 9 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-07-02 03:41 UTC, puthrayaharness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-04 04:20 UTC, puthrayaharness approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-04 07:16 UTC, archit-harness requested changes
> Reviewed 13 of 23 files at r2, 7 of 9 files at r3, 10 of 12 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 177 at r5](https://reviewable.io/reviews/harness/harness-core/34845#-N672vDM8oQz8OqdlyWn:-N672vDM8oQz8OqdlyWo:bb500on) ([raw file](https://github.com/harness/harness-core/blob/80e1a66b482a70f459dc93fd9239a05c2cacf2ff/860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L177)):*
> ```Java
>                    .yamlSchemaMetadata(YamlSchemaMetadata.builder()
>                                            .namespace(SchemaNamespaceConstants.PMS)
>                                            .modulesSupported(Arrays.asList(ModuleType.CD, ModuleType.PMS))
> ```

CI will not consume this?



_Code quote:_
```Java
modulesSupported(Arrays.asList(ModuleType.CD, ModuleType.PMS)
```
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/email/EmailStepParameters.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/34845#-N6736fn568DQn06NvR6:-N6736fn568DQn06NvR7:bv3vojp) ([raw file](https://github.com/harness/harness-core/blob/70bebd966b96314a089c5d977a5bab5efcc86943/860-orchestration-steps/src/main/java/io/harness/steps/email/EmailStepParameters.java#L25)):*
> ```Java
> @OwnedBy(HarnessTeam.CDC)
> @TypeAlias("EmailStepParameters")
> ```

Recaster alias is necessary


<!-- Sent from Reviewable.io -->

2022-07-04 08:22 UTC, vivekkarnatiharness commented
*[`860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 177 at r5](https://reviewable.io/reviews/harness/harness-core/34845#-N672vDM8oQz8OqdlyWn:-N67I3Wl1dDplCDkcgDd:b-lsbjf9) ([raw file](https://github.com/harness/harness-core/blob/80e1a66b482a70f459dc93fd9239a05c2cacf2ff/860-orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L177)):*
> CI will not consume this?
For now It is CD only. We will add it to CI later.


<!-- Sent from Reviewable.io -->

2022-07-04 10:40 UTC, archit-harness approved these changes
> Reviewed 5 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓

___
*[`860-orchestration-steps/src/main/java/io/harness/steps/email/EmailStepParameters.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/34845#-N6736fn568DQn06NvR6:-N67mSSG2WbOb-bcXVTN:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/70bebd966b96314a089c5d977a5bab5efcc86943/860-orchestration-steps/src/main/java/io/harness/steps/email/EmailStepParameters.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Recaster alias is necessary
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-07-04 11:32 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 2 of 5 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-04 11:34 UTC, puthrayaharness commented
trigger ti0

2022-07-04 11:35 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-04 12:04 UTC, vivekkarnatiharness commented
trigger ti0

2022-07-04 13:49 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-04 13:50 UTC, prashantsharma04 submitted a review, later dismissed
> Reviewed 13 of 23 files at r2, 5 of 9 files at r3, 8 of 12 files at r4, 2 of 5 files at r7, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-05 06:31 UTC, archit-harness approved these changes
> Reviewed 2 of 4 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-05 06:45 UTC, puthrayaharness approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34845)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-05 06:48 UTC, merged