[CI-4848]: CI manager changes for setup, execute step and cleanup task
harness/harness-core pull request #34873
Opened 2022-06-30 12:05 UTC by shubham149

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-01 09:51 UTC, vistaarjuneja commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  DLITE_CI_VM_INITIALIZE_TASK(
Last boolean should be true otherwise java delegate agents will also start supporting this task.
Also, let's change the name to just be `CI_VM_INITIALIZE_TASK`

2022-07-04 07:26 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/dlite/DliteVmTaskExecutionResponse.java
> +    @JsonProperty("delegate_meta_info") private DelegateMetaInfo delegateMetaInfo;
Done

2022-07-04 07:27 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  DLITE_CI_VM_INITIALIZE_TASK(
Updated the boolean
Since vm initialize task is also handled by java, better to include dlite for better understanding.

2022-07-05 15:05 UTC, r0610205 approved these changes

2022-07-06 06:57 UTC, shubham149 commented
trigger messagecheck

2022-07-07 07:07 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/buildstate/BuildSetupUtils.java
> +      case RUNS_ON:
Vm builds that are not hosted also use runner. So, it can be confusing.

2022-07-08 04:51 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/buildstate/SecretDecryptorViaNg.java
> +    return secretUtils.decryptViaManager(object, encryptedDataDetails, "random", null);
pass null instead of random

2022-07-08 04:53 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/execution/PipelineExecutionUpdateEventHandler.java
> +          String taskType = "CI_CLEANUP";
Move to new method

2022-07-08 05:00 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java
> +      Map<String, SecretParams> secretVars = secretSpecBuilder.decryptGitSecretVariables(params.getGitConnector());
validate secret logging

2022-07-08 05:03 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java
> +    SetupVmRequest.TIConfig tiConfig = SetupVmRequest.TIConfig.builder()
create getSetupVmRequest

2022-07-08 05:04 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java
> +    SetupVmRequest.Config config = SetupVmRequest.Config.builder()
create getSetupVmRequestConfig

2022-07-08 05:05 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeUtils.java
> +      return OSType.Linux;
Add comment

2022-07-08 05:11 UTC, harshjain12 commented on 320-ci-execution/src/main/java/io/harness/ci/utils/HarnessImageUtils.java
> +      return vmStageInfraDetails.getHarnessImageConnectorRef();
check overridden harnessImageConnectorRef

2022-07-11 10:11 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/utils/HarnessImageUtils.java
> +      return vmStageInfraDetails.getHarnessImageConnectorRef();
it works fine

2022-07-11 10:14 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java
> +    SetupVmRequest.TIConfig tiConfig = SetupVmRequest.TIConfig.builder()
done

2022-07-11 10:20 UTC, shubham149 commented
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java` line 458 at r7](https://reviewable.io/reviews/harness/harness-core/34873#-N5shYCNYRXJrB0SV_be-r7-458:-N6glWLQ2-nKz_o6dptn:b-lu5pyh) ([raw file](https://github.com/harness/harness-core/blob/490fc699d0f7d2133719d35d36da2f4ced73be80/320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java#L458)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

create getSetupVmRequestConfig
</blockquote></details>

not required since after moving the ticonfig, method has become quite still


<!-- Sent from Reviewable.io -->

2022-07-11 10:20 UTC, shubham149 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873)* status: 82 file(s) to review. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`320-ci-execution/src/main/java/io/harness/ci/buildstate/SecretDecryptorViaNg.java` line 21 at r7](https://reviewable.io/reviews/harness/harness-core/34873#-N5shYCNYRXJrB0SV_bc-r7-21:-N6glTzg1MRMUk6It9NP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/490fc699d0f7d2133719d35d36da2f4ced73be80/320-ci-execution/src/main/java/io/harness/ci/buildstate/SecretDecryptorViaNg.java#L21)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

pass null instead of random
</blockquote></details>

Done.
___
*[`320-ci-execution/src/main/java/io/harness/ci/execution/PipelineExecutionUpdateEventHandler.java` line 89 at r7](https://reviewable.io/reviews/harness/harness-core/34873#-N68In4Lhv2i8Dq0shrS-r7-89:-N6glUg5AhhTcF-rtNMp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/490fc699d0f7d2133719d35d36da2f4ced73be80/320-ci-execution/src/main/java/io/harness/ci/execution/PipelineExecutionUpdateEventHandler.java#L89)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

Move to new method
</blockquote></details>

Done.
___
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeUtils.java` line 175 at r7](https://reviewable.io/reviews/harness/harness-core/34873#-N6BxKj7rDUgtfp2jYGG-r7-175:-N6glb_b8corb_53Sy2c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/490fc699d0f7d2133719d35d36da2f4ced73be80/320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeUtils.java#L175)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

Add comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 16:01 UTC, shubham149 commented
trigger ti1

2022-07-12 06:03 UTC, harshjain12 approved these changes
> Reviewed 13 of 37 files at r2, 31 of 53 files at r3, 13 of 26 files at r4, 2 of 3 files at r5, 4 of 6 files at r6, 1 of 1 files at r7, 10 of 13 files at r8, 5 of 5 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-07-12 06:12 UTC, harshjain12 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873#-:-N6l-KQrCdzQrnWFQ4_F:bnfp4nl)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-07-14 04:48 UTC, harshjain12 reviewed
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-07-14 04:48 UTC, harshjain12 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873#-:-N6v1LGO3N2edqpq2jsm:bnfp4nl)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-07-14 07:29 UTC, vistaarjuneja approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873#-:-N6vbG7I8uSLFzuj2vKd:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-14 07:33 UTC, vistaarjuneja commented
Stage runtime ID changes are not present

2022-07-14 07:38 UTC, vistaarjuneja requested changes
we need stage runtime ID changes as well here

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873#-:-N6vdFiFCu116_Op4cln:bipnxtb)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-14 09:46 UTC, shubham149 reviewed
> Reviewed 13 of 37 files at r2, 27 of 53 files at r3, 13 of 26 files at r4, 2 of 3 files at r5, 4 of 6 files at r6, 1 of 1 files at r7, 6 of 13 files at r8, 3 of 5 files at r9, 4 of 5 files at r10, 3 of 4 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java` line 433 at r7](https://reviewable.io/reviews/harness/harness-core/34873#-N5shYCNYRXJrB0SV_be-r7-433:-N6w5RRo3TcwL-SSRJeR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/490fc699d0f7d2133719d35d36da2f4ced73be80/320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeTaskParamsBuilder.java#L433)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

validate secret logging
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 09:48 UTC, vistaarjuneja approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 37 files at r2, 27 of 53 files at r3, 13 of 26 files at r4, 2 of 3 files at r5, 4 of 6 files at r6, 1 of 1 files at r7, 6 of 13 files at r8, 3 of 5 files at r9, 4 of 5 files at r10, 3 of 4 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873#-:-N6w5yOTAUhJ14jN_QzR:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-07-14 09:49 UTC, vistaarjuneja approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34873#-:-N6w680B865vB5hya0xc:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-07-14 09:55 UTC, shubham149 commented
Codebase hash approval PRs questions:

Is it new task type? (If yes, no need to answer 2 then)
Yes

Did you add a new class which is added in kryo serialization
-

Did you make changes to the code in a backward-compatible manner?
No

will the new version of the delegate receive old version task and process?
New task can only be accepted by dlite. It won't accept any old task types.

If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
Yes

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
Yes

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
Yes

Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
No

Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
No

2022-07-14 12:40 UTC, shubham149 commented
trigger codebasehash

2022-07-14 12:54 UTC, merged