feat: [CDS-39170]: GitOps instanceNg Syncs
harness/harness-core pull request #35076
Opened 2022-07-06 13:51 UTC by GabeAboy

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-06 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=35076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=35076) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: achyuth-harness<br/>:x: GabeAboy<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=35076) it.</sub>

2022-07-06 13:52 UTC, GabeAboy commented
*[`120-ng-manager/config.yml` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/35076#-N6ImCFMB8OEq8HcuQ3T:-N6ImCFMB8OEq8HcuQ3U:byp6rt5) ([raw file](https://github.com/harness/harness-core/blob/7dd4deb9532ee9cfcd7d3e862e6c6f444c52899a/120-ng-manager/config.yml#L183)):*
> ```YAML
>   secret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
> 
> enableAuth: true
> ```

Revert


<!-- Sent from Reviewable.io -->

2022-07-06 14:16 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 331 at r3](https://reviewable.io/reviews/harness/harness-core/35076#-N6Ir_LtDcTAcITZOKDu:-N6Ir_LtDcTAcITZOKDv:b-z0bcif) ([raw file](https://github.com/harness/harness-core/blob/3a3d2b2c1ea0030ebdec9497e7da56144d096ee7/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L331)):*
> ```Java
>           InfrastructureMappingDTO infrastructureMappingDTO, List<InstanceDTO> instanceFromServer, String accountIdentifier, AbstractInstanceSyncHandler instanceSyncHandler) {
> 
>     List<InstanceDTO> instancesInDB = instanceService.getActiveGitOpsInstances("asd", "asd", accountIdentifier, "svc1");
> ```

Remove hard coded values


<!-- Sent from Reviewable.io -->

2022-07-06 14:44 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/mappers/instanceinfo/GitOpsInstanceInfoMapper.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6Iy19o8RuLrY5uFnND:-N6Iy19o8RuLrY5uFnNE:b-j71m36) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/126-instance/src/main/java/io/harness/mappers/instanceinfo/GitOpsInstanceInfoMapper.java#L22)):*
> ```Java
>   }
> 
>   public GitOpsInfo toEntity(GitOpsInstanceInfoDTO k8sInstanceInfoDTO) {
> ```

Change name k8sInstanceDTO


<!-- Sent from Reviewable.io -->

2022-07-06 15:05 UTC, achyuth-harness requested changes
> Reviewed 1 of 8 files at r1, 14 of 18 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35076)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6J-M4Z4PLNjjbhSl0L:-N6J-M4Z4PLNjjbhSl0M:b7wj6nl) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L62)):*
> ```Java
>       @NotNull @Valid List<GitOpsInstanceRequestDTO> gitOpsInstanceRequestDTOList) {
>     instanceSyncService.processInstanceSyncForGitops(gitOpsRequestDTOMapper.instanceDTOList(gitOpsInstanceRequestDTOList, accountId), accountId);
>     return ResponseDTO.newResponse(Boolean.TRUE);
> ```

Let's return PageResponse<InstanceDTO> as we were doing before
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncService.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6J0hnXCdVMGqSwPCKT:-N6J0hnXCdVMGqSwPCKU:b-niwosr) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncService.java#L21)):*
> ```Java
> public interface InstanceSyncService {
>   void processInstanceSyncForGitops(List<InstanceDTO> instanceList, String accountIdentifier);
> ```

i think instead of returning void we can return the list of saved instances? (otherwise, we can't return anything in the API -- createGitOpsInstances)
___
*[`126-instance/src/main/java/io/harness/mappers/instanceinfo/GitOpsInstanceInfoMapper.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6Iy19o8RuLrY5uFnND:-N6J0Bqg6Uevyq3ZmvZ6:b-w79ars) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/126-instance/src/main/java/io/harness/mappers/instanceinfo/GitOpsInstanceInfoMapper.java#L22)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

Change name k8sInstanceDTO
</blockquote></details>

Change GitOpsInfo to K8sBasicInfo so that if required in future other services can reuse it
___
*[`126-instance/src/main/java/io/harness/mappers/instanceinfo/GitOpsInstanceInfoMapper.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6J0TDw-rjmBUMMU9WK:-N6J0TDw-rjmBUMMU9WL:b-w79ars) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/126-instance/src/main/java/io/harness/mappers/instanceinfo/GitOpsInstanceInfoMapper.java#L23)):*
> ```Java
> 
>   public GitOpsInfo toEntity(GitOpsInstanceInfoDTO k8sInstanceInfoDTO) {
>     return GitOpsInfo.builder()
> ```

Change GitOpsInfo to K8sBasicInfo so that if required in future other services can reuse it


<!-- Sent from Reviewable.io -->

2022-07-07 00:33 UTC, anshul-harness commented
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 1 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6JH0-m9qaSAO2r_Kp6:-N6JH0-m9qaSAO2r_Kp7:b221x2m) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L1)):*
> ```Java
> package io.harness.ng.instancesync.resources;
> ```

Harness License info is missing


<!-- Sent from Reviewable.io -->

2022-07-07 05:28 UTC, GabeAboy commented
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6J-M4Z4PLNjjbhSl0L:-N6M73Sc--e-DGNkTeJ9:b-arp8s2) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L62)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Let's return PageResponse<InstanceDTO> as we were doing before
</blockquote></details>

I'm going to stick to returning void, the response isn't necessary 


<!-- Sent from Reviewable.io -->

2022-07-07 05:29 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncService.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/35076#-N6J0hnXCdVMGqSwPCKT:-N6M7SHO13a_JYSburl4:bab9973) ([raw file](https://github.com/harness/harness-core/blob/642c4825b09f9f26d4cc72b2d7e8d23b2b89b8bc/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncService.java#L21)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

i think instead of returning void we can return the list of saved instances? (otherwise, we can't return anything in the API -- createGitOpsInstances)
</blockquote></details>

I'm going to stick to returning void,  since the response isnt necessary and the other methods in this interface dont return either.  


<!-- Sent from Reviewable.io -->

2022-07-07 05:47 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 88 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6MBB-54lLux8L95X7I:-N6MBB-54lLux8L95X7J:bj83gtb) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L88)):*
> ```Java
> 
> 
>             Map<InfrastructureMappingDTO, List<InstanceDTO>> instanceInfoByInfrastructureMap = new HashMap<>();
> ```

This map is to group instances (Pods) associated to the same infraMappingDTO. GitOps could be sending multiple pods associated to a variety of infraMappingDTOs. This map groups so that later we can batch create pods with the same infroMappingDTO.


<!-- Sent from Reviewable.io -->

2022-07-07 05:48 UTC, GabeAboy commented
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 69 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6MBvKX2jjQSB_JsZuF:-N6MBvKX2jjQSB_JsZuG:b-pi9d9n) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L69)):*
> ```Java
>       @NotEmpty @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @NotNull @Valid List<GitOpsInstanceRequestDTO> gitOpsInstanceRequestDTOList) {
> //    List<InstanceDTO> instanceDTOList =
> ```

remove this


<!-- Sent from Reviewable.io -->

2022-07-07 05:49 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 159 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6MC14Z68XPkN3FFY-e:-N6MC14Z68XPkN3FFY-f:buph6vk) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L159)):*
> ```Java
>   public List<Instance> getActiveGitOpsInstances(
>           String agentId, String applicationId, String accountIdentifier, String serviceId) {
> //TODO Add application and agent
> ```

TODO query app and agent


<!-- Sent from Reviewable.io -->

2022-07-07 05:50 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 496 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6MC9hV7r4CdmJehMTS:-N6MC9hV7r4CdmJehMTT:btinqux) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L496)):*
> ```Java
>     Sets.SetView<String> instancesToBeAdded =
>             Sets.difference(instanceInfosFromServerMap.keySet(), instancesInDBMap.keySet());
>     // TODO FIX THIS
> ```

This method does not work when there are no instances in instancesInDBMap. Investigate 


<!-- Sent from Reviewable.io -->

2022-07-07 11:40 UTC, yogesh-chauhan requested changes
> Reviewed 1 of 8 files at r1, 8 of 19 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35076)* status: 11 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6NRQga67P--eqkO0mb:-N6NRQgb7IBG3H5z4OIZ:b2grbh5) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L24)):*
> ```Java
> @Builder
> @EqualsAndHashCode(callSuper = true)
> public class GitOpsInstanceRequestDTO extends InstanceInfoDTO {
> ```

InstanceInfoDTO is not supposed to be a request class and hence it successors are also not supposed to be. 
IMO we should not expose InstanceInfoDTO directly through any REST APIs
___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 41 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6NSCpe-xSoplKGc3AP:-N6NSCpe-xSoplKGc3AQ:b-7p2ggh) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L41)):*
> ```Java
>         .projectIdentifier(projId)
>         .envIdentifier(envId)
>         .infrastructureKind("Agent")
> ```

should this not be k8s ?
___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 42 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6NSJGN7bAPobsQswh3:-N6NSJGN7bAPobsQswh4:b-r9h5l8) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L42)):*
> ```Java
>         .envIdentifier(envId)
>         .infrastructureKind("Agent")
>         .infrastructureMappingId(gitOpsInstanceRequestDTO.getAgentIdentifier())
> ```

we should not set this field for gitops


<!-- Sent from Reviewable.io -->

2022-07-07 16:05 UTC, GabeAboy commented
trigger feature-build

2022-07-07 23:39 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6NRQga67P--eqkO0mb:-N6Q0HD87itZfBcblarp:b-48smok) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/dtos/gitops/GitOpsInstanceRequestDTO.java#L24)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

InstanceInfoDTO is not supposed to be a request class and hence it successors are also not supposed to be. 
IMO we should not expose InstanceInfoDTO directly through any REST APIs
</blockquote></details>


This is clear, incoming in the next commit


<!-- Sent from Reviewable.io -->

2022-07-08 04:18 UTC, GabeAboy commented
trigger feature-build

2022-07-08 04:25 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 121 at r7](https://reviewable.io/reviews/harness/harness-core/35076#-N6R2E7_9e0eXf-2UqWE:-N6R2E7_9e0eXf-2UqWF:b-ezvuew) ([raw file](https://github.com/harness/harness-core/blob/194e938674c01bf2163ace5a070cf0fd0b87fd1b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L121)):*
> ```Java
>                         .serviceIdentifier(instance.get(0).getServiceIdentifier())
>                         .infrastructureKind(InstanceSyncFlow.GITOPS_APPLICATION_SYNC.name())
>                         .connectorRef("setCon") // TODO Gabriel ApplicationId
> ```

@anshul-harness @yogesh-chauhan @achyuth-harness 
InfrasfructureMappingDTO is needed, but for GitOps we don't have 
connectorRef & id, when they are set as @NOTNULL


<!-- Sent from Reviewable.io -->

2022-07-08 04:27 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 96 at r7](https://reviewable.io/reviews/harness/harness-core/35076#-N6R2xEk6zkxWU3QCcUV:-N6R2xEk6zkxWU3QCcUW:b-th28cs) ([raw file](https://github.com/harness/harness-core/blob/194e938674c01bf2163ace5a070cf0fd0b87fd1b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L96)):*
> ```Java
>                         .orgIdentifier(orgIdentifier)
>                         .artifactDetails(instanceDTO.getPrimaryArtifact())
> //                        .deployedById("")
> ```

I need to get this info from the pipeline service, remove comment and make another ticket


<!-- Sent from Reviewable.io -->

2022-07-08 04:32 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 514 at r7](https://reviewable.io/reviews/harness/harness-core/35076#-N6R3U5b2y27PmSf5RlL:-N6R3U5d3l7xO_mAi4re:b-3abpcd) ([raw file](https://github.com/harness/harness-core/blob/194e938674c01bf2163ace5a070cf0fd0b87fd1b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L514)):*
> ```Java
>             .addAll(buildInstances(instanceSyncHandler,
>                     instancesToBeAdded.stream().map(instanceInfosFromServerMap::get).collect(Collectors.toList()),
>                     deploymentSummaryDTO, infrastructureMappingDTO, isAutoScaled, "", ""));
> ```

I am sending empty string for
      String infraIdentifier,
      String infraName
What do you suggest we do here? Is it fine to leave blank?


<!-- Sent from Reviewable.io -->

2022-07-08 19:19 UTC, GabeAboy commented
trigger messagecheck

2022-07-08 19:25 UTC, GabeAboy commented
trigger messagecheck

2022-07-08 19:26 UTC, GabeAboy commented
trigger message-check

2022-07-08 19:27 UTC, GabeAboy commented
trigger messageCheck

2022-07-08 19:30 UTC, GabeAboy commented
trigger feature-build

2022-07-08 21:37 UTC, GabeAboy commented
trigger feature-build

2022-07-11 11:52 UTC, yogesh-chauhan requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35076)* status: 9 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 54 at r14](https://reviewable.io/reviews/harness/harness-core/35076#-N6h05XrAnueU1Y7fHaM:-N6h05XtAhNnwWzAK8P6:b-a7lrpe) ([raw file](https://github.com/harness/harness-core/blob/209a3095ee356ef66d12a841ec2006c40a9be320/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L54)):*
> ```Java
>         .envName(env.getName())
>         .envType(env.getType())
>         .serviceIdentifier(gitOpsInstanceRequest.getServiceIdentifier())
> ```

nit: use ```svcId``` here
___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 81 at r14](https://reviewable.io/reviews/harness/harness-core/35076#-N6h5LVcAERu3GDso7UJ:-N6h5LVe3yG9M6J7JEa8:b-np30ql) ([raw file](https://github.com/harness/harness-core/blob/209a3095ee356ef66d12a841ec2006c40a9be320/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L81)):*
> ```Java
>                                                         .build())
>                                              .collect(Collectors.toList());
>       K8sBasicInfo k8sBasicInfo = K8sBasicInfo.builder()
> ```

do we need to create this object ? I do not see it being used except for setting values in k8sInstanceInfoDTO
___
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 41 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6gxokH3u2V-GJq-wug:-N6gxol-5xHmYMja_8eX:byiki5s) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L41)):*
> ```Java
>                                 .orElseGet(() -> ServiceEntity.builder().build());
> 
>     String artifactId = String.format("%s/%s/%s", svcId, envId, service.getName());
> ```

this is not a valid artifactId, probably we should not set it at all


<!-- Sent from Reviewable.io -->

2022-07-11 14:37 UTC, yogesh-chauhan commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 88 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6MBB-54lLux8L95X7I:-N6hft4p9m3CdsdG2-FX:blpbv0b) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L88)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

This map is to group instances (Pods) associated to the same infraMappingDTO. GitOps could be sending multiple pods associated to a variety of infraMappingDTOs. This map groups so that later we can batch create pods with the same infroMappingDTO.
</blockquote></details>

I am bit confused here. Do we want to group by InfraMappingDTO or DeploymentSummaryDTO ?


<!-- Sent from Reviewable.io -->

2022-07-11 14:39 UTC, yogesh-chauhan reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35076)* status: 9 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-07-11 15:14 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 41 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6gxokH3u2V-GJq-wug:-N6horvx7dG_yMgEVwGz:b8e0vni) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this is not a valid artifactId, probably we should not set it at all
</blockquote></details>

going to try removing this


<!-- Sent from Reviewable.io -->

2022-07-11 15:16 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 50 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6goYw99iyz3nIRcyAZ:-N6hp-XBDVgP4IOkJhki:b-59bz6) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L50)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to remove not null constraint on connector ref and remove "unknown"
</blockquote></details>

try removing notNull from where connectorRef is required, inframappingDTO


<!-- Sent from Reviewable.io -->

2022-07-11 15:17 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 54 at r14](https://reviewable.io/reviews/harness/harness-core/35076#-N6h05XrAnueU1Y7fHaM:-N6hpTDw-1bFlHt7W8XU:b-62quhj) ([raw file](https://github.com/harness/harness-core/blob/209a3095ee356ef66d12a841ec2006c40a9be320/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L54)):*
> svcId here
variable here to reuse


<!-- Sent from Reviewable.io -->

2022-07-11 15:20 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 58 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6gomTX-FsCK2ah0XwW:-N6hpYjH0uMqKTP3wdm1:bt96vfw) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L58)):*
> nce key is what uniquely
app+agent is infrastructureID to make each pod unique
Instance instance key should be a pod ID + podName


<!-- Sent from Reviewable.io -->

2022-07-11 15:23 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 81 at r14](https://reviewable.io/reviews/harness/harness-core/35076#-N6h5LVcAERu3GDso7UJ:-N6hqmc2AM29Ar4GWiHu:b-6fygtd) ([raw file](https://github.com/harness/harness-core/blob/209a3095ee356ef66d12a841ec2006c40a9be320/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L81)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to create this object ? I do not see it being used except for setting values in k8sInstanceInfoDTO
</blockquote></details>

Discard this obj and populate directly



_Code quote:_
```Java
K8sBasicInfo k8sBasicInfo = K8sBasicInfo.builder()
```


<!-- Sent from Reviewable.io -->

2022-07-11 15:29 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 42 at r6](https://reviewable.io/reviews/harness/harness-core/35076#-N6NSJGN7bAPobsQswh3:-N6fGidBB8bMw8aeKBwA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf18e424bcb903b47558f5d3a8bf946e07e740aa/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L42)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should not set this field for gitops
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 15:48 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 41 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6gxokH3u2V-GJq-wug:-N6hwb-s-l-wtp-19R4T:b85fe3b) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L41)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

going to try removing this
</blockquote></details>

Shouldnt artifact ID have some values for ArtifactDetails?


<!-- Sent from Reviewable.io -->

2022-07-11 15:53 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 109 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6hsgTYAF5t2GF7UadW:-N6husxp8zAs02E19vHD:bwkdaee) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L109)):*
> appingDTO or DeploymentSummaryDTO ?
We cant because the agent can send pods from multiple env and service IDs


<!-- Sent from Reviewable.io -->

2022-07-11 17:31 UTC, achyuth-harness reviewed
> Reviewed 1 of 19 files at r6, 4 of 13 files at r7, 7 of 15 files at r9, 2 of 3 files at r11, 2 of 5 files at r12, 1 of 2 files at r13, 4 of 5 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35076)* status: 2 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-07-11 20:06 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 118 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6gpchi-JGi4AVzqw-1:-N6irXH7AcUiBD-asfa1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L118)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

infrastructure key and instance key are different concepts
- infrastructure key: what uniquely identifies my infrastructure ( appId - agentId ) makes sense here
- instance key: what uniquely identifies my instances ( appId - agentId ) does not makes sense here. We need to add pod information like podname, namespace here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 20:06 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 81 at r14](https://reviewable.io/reviews/harness/harness-core/35076#-N6h5LVcAERu3GDso7UJ:-N6irf-b7OM5_WHHDacO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/209a3095ee356ef66d12a841ec2006c40a9be320/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L81)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

Discard this obj and populate directly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 20:06 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 58 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6gomTX-FsCK2ah0XwW:-N6irhnR9Zvzlewg63P4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L58)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

> nce key is what uniquely
app+agent is infrastructureID to make each pod unique
Instance instance key should be a pod ID + podName
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 20:06 UTC, GabeAboy commented
*[`126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java` line 41 at r15](https://reviewable.io/reviews/harness/harness-core/35076#-N6gxokH3u2V-GJq-wug:-N6irk1M907IoRsJFqnS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf728ef1885ebef869f330673871187fa71a2415/126-instance/src/main/java/io/harness/helper/GitOpsRequestDTOMapper.java#L41)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

Shouldnt artifact ID have some values for ArtifactDetails?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 00:35 UTC, GabeAboy commented
trigger ti3

2022-07-12 04:56 UTC, yogesh-chauhan commented
*[`120-ng-manager/config.yml` line 190 at r26](https://reviewable.io/reviews/harness/harness-core/35076#-N6kkqHcB3Cx0dScQyXF:-N6kkqHd3M-ISAFMqVdW:b-5lds09) ([raw file](https://github.com/harness/harness-core/blob/5bdfabaaeee290eb6bd1f2a5c576351b2162f14f/120-ng-manager/config.yml#L190)):*
> ```YAML
>   secret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
> 
> enableAuth: false
> ```

lets revert this


<!-- Sent from Reviewable.io -->

2022-07-12 05:04 UTC, yogesh-chauhan commented
*[`126-instance/src/main/java/io/harness/dtos/instanceinfo/GitOpsInstanceInfoDTO.java` line 26 at r26](https://reviewable.io/reviews/harness/harness-core/35076#-N6klSif0fP71umgy-vT:-N6klSig6i9BZHwVSNvh:b-4igbrg) ([raw file](https://github.com/harness/harness-core/blob/5bdfabaaeee290eb6bd1f2a5c576351b2162f14f/126-instance/src/main/java/io/harness/dtos/instanceinfo/GitOpsInstanceInfoDTO.java#L26)):*
> ```Java
> 
>   @Override
>   public String prepareInstanceKey() {
> ```

This should be ```podId + namespace```

for reference: ```io.harness.dtos.instanceinfo.K8sInstanceInfoDTO#prepareInstanceKey```


<!-- Sent from Reviewable.io -->

2022-07-12 05:39 UTC, GabeAboy reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35076)* status: 19 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 190 at r26](https://reviewable.io/reviews/harness/harness-core/35076#-N6kkqHcB3Cx0dScQyXF:-N6ktkXO8SAXTytfVRHG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bdfabaaeee290eb6bd1f2a5c576351b2162f14f/120-ng-manager/config.yml#L190)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets revert this
</blockquote></details>

Done.



_Code quote:_
```YAML
enableAuth: false
```
___
*[`126-instance/src/main/java/io/harness/dtos/instanceinfo/GitOpsInstanceInfoDTO.java` line 26 at r26](https://reviewable.io/reviews/harness/harness-core/35076#-N6klSif0fP71umgy-vT:-N6ktltRDQ__uSzdLktm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bdfabaaeee290eb6bd1f2a5c576351b2162f14f/126-instance/src/main/java/io/harness/dtos/instanceinfo/GitOpsInstanceInfoDTO.java#L26)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This should be ```podId + namespace```

for reference: ```io.harness.dtos.instanceinfo.K8sInstanceInfoDTO#prepareInstanceKey```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 19:05 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 11 files at r31.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35076)* status: 19 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-07-12 19:55 UTC, GabeAboy commented
trigger feature-build

2022-07-12 20:17 UTC, merged