[Fix]: [CDS-39434]: added coverage for some jira files
harness/harness-core pull request #35217
Opened 2022-07-11 10:28 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-19 09:24 UTC, puthrayaharness requested changes

2022-07-19 09:24 UTC, puthrayaharness commented on 800-pipeline-service/src/test/java/io/harness/pms/approval/ApprovalinstanceHandlerTest.java
> +  @Mock private ApprovalInstance approvalInstance;
Same do not mock

2022-07-19 09:24 UTC, puthrayaharness commented on 800-pipeline-service/src/test/java/io/harness/pms/approval/ApprovalinstanceHandlerTest.java
> +    approvalInstanceHandler.handle(entity);
Same

2022-07-19 09:24 UTC, puthrayaharness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/jira/JiraTaskNGHandlerTest.java
> +    PowerMockito.whenNew(JiraClient.class).withAnyArguments().thenReturn(jiraClient);
Please remove usage of PowerMockito.

2022-07-19 09:24 UTC, puthrayaharness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/jira/JiraTaskNGHandlerTest.java
> +    PowerMockito.whenNew(JiraClient.class).withAnyArguments().thenReturn(jiraClient);
Please remove usage of PowerMockito

2022-07-19 09:24 UTC, puthrayaharness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/jira/JiraTaskNGHandlerTest.java
> +    PowerMockito.whenNew(JiraClient.class).withAnyArguments().thenReturn(jiraClient);
Please remove usage of Powermockito

2022-07-19 09:24 UTC, puthrayaharness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/jira/JiraTaskNGHandlerTest.java
> +    PowerMockito.whenNew(JiraClient.class).withAnyArguments().thenReturn(jiraClient);
Please remove usage of Powermockito

2022-07-19 09:24 UTC, puthrayaharness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/jira/JiraTaskNGHandlerTest.java
> +    PowerMockito.whenNew(JiraClient.class).withAnyArguments().thenReturn(jiraClient);
Please remove usage of PowerMockito

2022-07-19 09:24 UTC, puthrayaharness commented on 800-pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/ApprovalInstanceServiceTest.java
> +  @Mock private ApprovalInstance approvalInstance;
Remove mock

2022-07-19 09:24 UTC, puthrayaharness commented on 800-pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/ApprovalInstanceServiceTest.java
> +  @Mock private UpdateResult updateResult;
Remove global mock and move this to method. Use `UpdateResult updateResult = mock(UpdateResult.class)`

2022-07-22 09:39 UTC, vivekkarnatiharness commented
trigger ti1

2022-07-22 12:06 UTC, vivekkarnatiharness commented
trigger ti1

2022-07-25 06:20 UTC, puthrayaharness approved these changes
> Reviewed 1 of 2 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35217)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-25 07:55 UTC, gaurav-jain1 approved these changes
> Reviewed 1 of 2 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35217)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-25 07:55 UTC, merged