feat: [CDS-37792]: Created dummy API for fetching users
harness/harness-core pull request #35272
Opened 2022-07-12 11:52 UTC by mitishapandey

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-14 07:08 UTC, abhinav-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java
>    // Fields sent while creating/updating issue.
this we have to change

2022-07-14 09:56 UTC, arpit3107 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35272)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/35272#-N6w7pHz9lbBBqsyUSJ_:-N6w7pHz9lbBBqsyUSJa:b-2ejtd9) ([raw file](https://github.com/harness/harness-core/blob/4ee7f6caedb5e616989e906916db92113b7074b4/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java#L38)):*
> ```Java
>   JiraConnectorDTO jiraConnectorDTO;
>   List<EncryptedDataDetail> encryptionDetails;
>   JiraUserSearchParams jiraUserSearchParams;
> ```

is this change backward compatible? have you tested it with older version delegates?



_Code quote:_
```Java
JiraUserSearchParams jiraUserSearchParams;
```


<!-- Sent from Reviewable.io -->

2022-07-14 10:35 UTC, abhinav-harness submitted a review, later dismissed
> Reviewed 5 of 9 files at r1, 2 of 2 files at r2, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35272)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-14 10:39 UTC, arpit3107 approved these changes
> Reviewed 5 of 9 files at r1, 2 of 2 files at r2, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35272)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/35272#-N6w7pHz9lbBBqsyUSJ_:-N6wHYG61ll12wYGmqka:b-2uxucd) ([raw file](https://github.com/harness/harness-core/blob/4ee7f6caedb5e616989e906916db92113b7074b4/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java#L38)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

is this change backward compatible? have you tested it with older version delegates?
</blockquote></details>

This is behind FF. Approving.


<!-- Sent from Reviewable.io -->

2022-07-14 10:52 UTC, mitishapandey commented
trigger codebasehash

2022-07-18 06:01 UTC, DeepakPatankar commented
trigger codebasehash

2022-07-19 11:23 UTC, puthrayaharness requested changes

2022-07-19 11:23 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/jira/JiraSearchUserMetadataNG.java
> +public class JiraSearchUserMetadataNG {}
Is this being used anywhere?

2022-08-01 20:09 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35272)

2022-09-05 06:01 UTC, closed without merging