[fix]: [CDS-36795]: Feature Request: Not able to use docker labels from the artifacts
harness/harness-core pull request #35382
Opened 2022-07-14 20:42 UTC by rafaelmart1ns

2022-07-14 20:53 UTC, lasdox commented on 400-rest/src/main/java/software/wings/service/impl/BuildSourceServiceImpl.java
> -        && !ECR.name().equals(artifactStream.getArtifactStreamType())) {
We should add a check here for Artifactory so this call happens only if artifactType is docker image

2022-07-14 21:41 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/BuildSourceServiceImpl.java
> -        && !ECR.name().equals(artifactStream.getArtifactStreamType())) {
I did

2022-07-14 23:09 UTC, Fernando-Dourado requested changes
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35382)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/35382#-N6yx4Rg11fwsgiEMrxY:-N6yx4Rh29hDSBoQ_MZK:b-k2spkr) ([raw file](https://github.com/harness/harness-core/blob/9b28928516d11ebc74e5e25a3dde3c13cf0f5921/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L111)):*
> ```Java
> 
>     } catch (Exception e) {
>       log.info("Failed to retrieve docker label in artifactory");
> ```

I recommend changing to error priority instead of info and adding the stacktrace.
___
*[`960-api-services/src/test/java/io/harness/artifactory/ArtifactoryClientImplTest.java` line 173 at r1](https://reviewable.io/reviews/harness/harness-core/35382#-N6yxiJD04n_xyC-KCOv:-N6yxiJD04n_xyC-KCOw:bg1k43q) ([raw file](https://github.com/harness/harness-core/blob/9b28928516d11ebc74e5e25a3dde3c13cf0f5921/960-api-services/src/test/java/io/harness/artifactory/ArtifactoryClientImplTest.java#L173)):*
> ```Java
>   @Owner(developers = RAFAEL)
>   @Category(UnitTests.class)
>   public void shouldGetLabels() {
> ```

Please, add more different scenarios and assertions on what we send to the API call and it responds.


<!-- Sent from Reviewable.io -->

2022-07-15 06:01 UTC, puthrayaharness requested changes

2022-07-15 06:01 UTC, puthrayaharness commented on 960-api-services/src/test/java/io/harness/artifactory/ArtifactoryClientImplTest.java
> +    assertThat(labels.get(0).get("harness.test").equals("passed"));
Please check all the labels rather than just the first. You can construct an Immutable Hash Map and assert against that.

2022-07-18 12:43 UTC, rafaelmart1ns commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      Map<String, String> propertyParsed = properties.entrySet().stream().collect(
> What happens to properties that do not contain 'docker.label'?
Returns all other labels.  

> Also what if the key is 'docker.label.docker.label'?
In this case, we need to separate it into two parts, the first docker label being the standard part of docker and the second part being manually added as the label name ie the label name is `docker.label`. That said it will remove the default label part of docker and return the other labels including the `docker.label` content.

2022-07-18 12:46 UTC, rafaelmart1ns commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +      Map<String, String> propertyParsed = properties.entrySet().stream().collect(
Just to comment I did correct the code. In this version, it returns all other properties.

2022-07-18 14:02 UTC, puthrayaharness requested changes

2022-07-18 14:02 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +              .filter(e -> e.getKey().contains("docker.label"))
Take a example of docker.label.docker.label.maintainer

Here the actual label is docker.label.maintainer

2022-07-18 21:48 UTC, Fernando-Dourado submitted a review, later dismissed
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35382)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-07-19 03:14 UTC, puthrayaharness requested changes

2022-07-19 03:14 UTC, puthrayaharness commented on 960-api-services/src/test/java/io/harness/artifactory/ArtifactoryClientImplTest.java
> +    Map<String, String> assertionMap = ImmutableMap.copyOf(labels.get(0));
This test is great. At Harness, we do not use `@Test(expected = WingsException.class)` this affects our tooling in a few areas. So instead we use assertThatThrownBy to check for exceptions. Could you please change this test case to use that?

2022-07-19 18:41 UTC, rafaelmart1ns commented on 960-api-services/src/test/java/io/harness/artifactory/ArtifactoryClientImplTest.java
> +    Map<String, String> assertionMap = ImmutableMap.copyOf(labels.get(0));
Ok, I made this change. 
Thanks for tip.

2022-07-20 13:14 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 6 of 8 files at r1, 2 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35382)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-20 13:19 UTC, rafaelmart1ns commented
checkstyle

2022-07-20 13:25 UTC, rafaelmart1ns commented
trigger ti0

2022-07-20 14:17 UTC, rafaelmart1ns commented
trigger checkstyle

2022-07-20 15:12 UTC, lasdox submitted a review, later dismissed
> Reviewed 4 of 8 files at r1, 2 of 4 files at r2, 2 of 3 files at r3, 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35382)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-20 16:41 UTC, rafaelmart1ns commented
trigger ti4

2022-07-20 18:59 UTC, Fernando-Dourado approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35382)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-20 19:02 UTC, merged