fix: [PL-26600]: Fixed the optional field in k8s Auth displaying in other auth methods
harness/harness-core pull request #35455
Opened 2022-07-19 05:53 UTC by VikasMaddukuriHarness

…ther auth methods

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-19 06:02 UTC, nishantsaini20 requested changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35455)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/35455#-N7K2COZDZOQvB_cSaIe:-N7K2COZDZOQvB_cSaIf:bc97v6) ([raw file](https://github.com/harness/harness-core/blob/022c347a04e9d7fad3095cb06b9d32353fa69e42/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L97)):*
> ```Java
>   public String getK8sAuthEndpoint() {
>     if (!useK8sAuth) {
>       return null;
> ```

Is is safe to return null from this method?


<!-- Sent from Reviewable.io -->

2022-07-20 11:06 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35455)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/35455#-N7K2COZDZOQvB_cSaIe:-N7QHF28C9WgKBmtmOW3:b-a4ne5u) ([raw file](https://github.com/harness/harness-core/blob/022c347a04e9d7fad3095cb06b9d32353fa69e42/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L97)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is is safe to return null from this method?
</blockquote></details>

Verified all the flows and looks alright.


<!-- Sent from Reviewable.io -->

2022-07-20 12:32 UTC, gaurav-jain1 approved these changes

2022-07-21 05:03 UTC, VikasMaddukuriHarness commented
trigger codebasehash

2022-07-29 10:41 UTC, closed without merging