feat: [CDS-40096]: yaml and functional changes for change window
harness/harness-core pull request #35458
Opened 2022-07-19 07:12 UTC by naman-goenka

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/35458)

2022-07-19 07:28 UTC, puthrayaharness requested changes

2022-07-19 07:28 UTC, puthrayaharness commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +@JsonTypeName(StepSpecTypeConstants.CHANGE_WINDOW)
Why do you need `@JsonTypeName(StepSpecTypeConstants.CHANGE_WINDOW)`

2022-07-19 07:28 UTC, puthrayaharness commented on 800-pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps/StepSpecTypeConstants.java
> +  String CHANGE_WINDOW = "ChangeWindow";
Please remove

2022-07-19 07:28 UTC, puthrayaharness commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +@RecasterAlias("io.harness.steps.approval.step.jira.beans.ChangeWindowSpec")
This value is incorrect and I do not think you need this. 
TBH I do not think you need most of these annotations. You probably just need lombok annotations, team annotation.

2022-07-19 07:28 UTC, puthrayaharness commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +public class ChangeWindowSpec {
Please rename this to `ServiceNowChangeWindowSpec` in case we want to add this for other Approvals in the future then we can create a common class.

2022-07-19 07:28 UTC, puthrayaharness commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +@TypeAlias("changeWindowSpec")
Not needed

2022-07-19 08:00 UTC, naman-goenka commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +public class ChangeWindowSpec {
sure

2022-07-19 09:08 UTC, naman-goenka commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +@TypeAlias("changeWindowSpec")
Done

2022-07-19 09:08 UTC, naman-goenka commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +@RecasterAlias("io.harness.steps.approval.step.jira.beans.ChangeWindowSpec")
Done

2022-07-19 09:08 UTC, naman-goenka commented on 800-pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps/StepSpecTypeConstants.java
> +  String CHANGE_WINDOW = "ChangeWindow";
ok

2022-07-19 09:09 UTC, naman-goenka commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ChangeWindowSpec.java
> +@JsonTypeName(StepSpecTypeConstants.CHANGE_WINDOW)
Kept for the purpose of consistency, can forgo it for now

2022-07-28 10:32 UTC, puthrayaharness requested changes

2022-07-28 10:32 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/servicenow/resources/service/ServiceNowResourceServiceImpl.java
> +    if (isNull(internalType) || isNull(fieldType)) {
Whenever you see a string consider using `isBlank` rather than `isNull`. In most cases `isBlank` is the best method to check.

2022-07-28 10:32 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/servicenow/ServiceNowFieldNG.java
> +    if (this.internalType == null) {
Consider using blank here.

2022-07-28 12:38 UTC, naman-goenka commented on 800-pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans/ServiceNowChangeWindowSpecDTO.java
> +  public String toString() {
done

2022-07-28 12:41 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/servicenow/resources/service/ServiceNowResourceServiceImpl.java
> +    if (isNull(internalType) || isNull(fieldType)) {
Sure, although very less possibility of unintentional blank string here

2022-07-29 07:17 UTC, puthrayaharness approved these changes

2022-07-29 07:19 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 20 of 27 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35458)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-29 07:19 UTC, puthrayaharness commented
trigger codebasehash

2022-07-29 13:44 UTC, puthrayaharness approved these changes

2022-07-29 13:45 UTC, puthrayaharness approved these changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35458)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-01 19:48 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 3 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 3 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35458)

2022-08-16 14:54 UTC, puthrayaharness approved these changes
> Reviewed 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35458)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-17 11:32 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35458)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-17 13:17 UTC, puthrayaharness approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35458)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-17 13:18 UTC, merged