feat: [CDS-40016]: Custom artifact support
harness/harness-core pull request #35468
Opened 2022-07-19 10:21 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-28 03:59 UTC, shivamnegi94 commented
trigger ti1, ti2

2022-08-01 20:34 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 31 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 1 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 30 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35468)

2022-08-17 02:09 UTC, shivamnegi94 commented
trigger compile

2022-08-17 02:18 UTC, shivamnegi94 commented
trigger ti0, ti1, ti2, ti3, ti4

2022-08-17 07:55 UTC, puthrayaharness requested changes

2022-08-17 07:55 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/serializer/kryo/NGEntitiesKryoRegistrar.java
> -    kryo.register(ConfigFileOutcome.class, 130013);
Please cross check this. You seem to be changing the values of existing kryo entities.

2022-08-17 07:55 UTC, puthrayaharness commented on 400-rest/src/test/java/software/wings/helpers/ext/customrepository/CustomRepositoryServiceTest.java
> +  private static final String ARTIFACT_RESULT_PATH = "HARNESS_ARTIFACT_RESULT_PATH";
Please revert this change. Looks like you changed for CG here.

2022-08-17 07:55 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/customrepository/CustomRepositoryServiceImpl.java
> -  private static final String ARTIFACT_RESULT_PATH = "ARTIFACT_RESULT_PATH";
You have changed this for CG as well. Please change this back

2022-08-17 07:55 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/shell/ShellExecutionServiceImpl.java
> -  private static final String ARTIFACT_RESULT_PATH = "ARTIFACT_RESULT_PATH";
Please ensure this does not impact CG.

2022-08-17 07:55 UTC, puthrayaharness commented on 960-ng-core-beans/src/main/java/io/harness/serializer/kryo/NGCoreBeansKryoRegistrar.java
> +    kryo.register(ShellType.class, 20105);
Do we need to pass this? No need to send this info to delegate

2022-08-17 07:55 UTC, puthrayaharness commented on 970-ng-commons/src/main/java/io/harness/serializer/kryo/NGCommonsKryoRegistrar.java
> +    kryo.register(Timeout.class, 9300122);
Why do we need to register this? We do not need to send timeout to delegate?

2022-08-17 07:55 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/response/ArtifactTaskExecutionResponse.java
> +  UnitProgressData unitProgressData;
Why do we need to send unit progress data? Why do we need any of these fields?

2022-08-17 10:30 UTC, shivamnegi94 commented on 960-ng-core-beans/src/main/java/io/harness/serializer/kryo/NGCoreBeansKryoRegistrar.java
> +    kryo.register(ShellType.class, 20105);
It is required in Delegate Task

2022-08-17 10:30 UTC, shivamnegi94 commented on 970-ng-commons/src/main/java/io/harness/serializer/kryo/NGCommonsKryoRegistrar.java
> +    kryo.register(Timeout.class, 9300122);
Otherwise we are getting exception

2022-08-17 10:31 UTC, shivamnegi94 commented on 960-api-services/src/main/java/io/harness/shell/ShellExecutionServiceImpl.java
> -  private static final String ARTIFACT_RESULT_PATH = "ARTIFACT_RESULT_PATH";
reverted the changes

2022-08-17 10:31 UTC, shivamnegi94 commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/customrepository/CustomRepositoryServiceImpl.java
> -  private static final String ARTIFACT_RESULT_PATH = "ARTIFACT_RESULT_PATH";
Reverted the changes

2022-08-17 10:32 UTC, shivamnegi94 commented on 125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/CustomArtifactInfo.java
> +  Map<String, String> attributes;
Done

2022-08-18 11:56 UTC, puthrayaharness requested changes
`960-ng-core-beans/src/main/java/io/harness/steps/shellscript/ShellType.java` Please revert this change back. We should not have to move this.

2022-08-18 11:56 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/serializer/kryo/NGEntitiesKryoRegistrar.java
> +    kryo.register(ApplicationSettingsConfiguration.class, 140014);
Please do not change the kryo values

2022-08-18 11:56 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/serializer/kryo/NGEntitiesKryoRegistrar.java
> +    kryo.register(ConnectionStringsConfiguration.class, 140015);
Please do not change the kryo values

2022-08-18 11:56 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/serializer/kryo/NGEntitiesKryoRegistrar.java
> +    kryo.register(StartupCommandConfiguration.class, 140016);
Please do not change the kryo values

2022-08-22 08:27 UTC, puthrayaharness requested changes

2022-08-22 08:27 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/artifact/ArtifactPlanCreatorHelper.java
> +    if (ArtifactSourceType.CUSTOM_ARTIFACT == artifactStepParameters.getType()
merge the condition into one.

2022-08-22 08:27 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/serializer/kryo/NGEntitiesKryoRegistrar.java
> +    kryo.register(ConnectionStringsConfiguration.class, 140015);
Can you check this again

2022-08-22 08:27 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/custom/CustomArtifactTaskHandler.java
> +public class CustomArtifactTaskHandler extends DelegateArtifactTaskHandler<CustomArtifactDelegateRequest> {
Please remove the business logic from this class and move to a different or new service class.

2022-08-22 08:27 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/custom/CustomArtifactTaskHelper.java
> +@OwnedBy(HarnessTeam.PIPELINE)
CDC

2022-08-22 08:27 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/custom/CustomArtifactTaskHandler.java
> +public class CustomArtifactTaskHandler extends DelegateArtifactTaskHandler<CustomArtifactDelegateRequest> {
Owned by CDC

2022-08-22 08:27 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/custom/CustomArtifactTaskHelper.java
> +    } catch (JenkinsServerRuntimeException ex) {
Change this or remove

2022-08-22 08:27 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/custom/CustomArtifactTaskNG.java
> +    if (getLogStreamingTaskClient() != null) {
I do not think we need if else here. Please remove

2022-08-22 08:27 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ShellScriptExecutionOnDelegateNG.java
> +  public static final String COMMAND_UNIT = "Execute";
Reuse the command unit.

2022-08-22 08:27 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ShellScriptExecutionOnDelegateNG.java
> +public class ShellScriptExecutionOnDelegateNG {
Either we call this as `CustomArtifactSourceDelegateNG` or we make this be used by ShellScriptTaskNG + move the custom artifact code to a different class.

2022-08-22 08:27 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ArtifactDelegateRequestUtils.java
> +      String shellType, ArtifactSourceType sourceType, ScriptType scriptType, String versionPath, String script,
Remove `shellType`

2022-08-22 08:27 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ArtifactDelegateRequestUtils.java
> +        .executeOnDelegate(true)
Remove `executeOnDelegate`

2022-08-22 08:27 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/custom/CustomArtifactDelegateRequest.java
> +  boolean executeOnDelegate;
Remove from here.

2022-08-24 07:29 UTC, shivamnegi94 commented
trigger ti2

2022-08-24 08:13 UTC, puthrayaharness approved these changes

2022-08-24 08:15 UTC, puthrayaharness approved these changes
> Reviewed 6 of 28 files at r1, 8 of 29 files at r2, 38 of 59 files at r4, 4 of 14 files at r5, 5 of 9 files at r6, 1 of 3 files at r7, 10 of 17 files at r8, 20 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35468)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-24 08:15 UTC, puthrayaharness commented
trigger codebasehash

2022-08-24 09:07 UTC, archit-harness approved these changes
> Reviewed 5 of 59 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35468)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-24 09:27 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 28 files at r1, 8 of 29 files at r2, 38 of 59 files at r4, 4 of 14 files at r5, 5 of 9 files at r6, 1 of 3 files at r7, 10 of 17 files at r8, 20 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35468#-:-NAEAODjCbbRtrhf-J9R:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-24 09:37 UTC, sahilhindwani-harness reviewed
> Reviewed 3 of 59 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35468)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-24 09:38 UTC, sahilhindwani-harness approved these changes
> Reviewed 2 of 59 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35468)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-24 10:06 UTC, merged