feat: [PL-26473]: Role Assignment API for user details
harness/harness-core pull request #35529
Opened 2022-07-20 12:06 UTC by reetika04

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-20 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=35529) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=35529) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=35529) it.</sub>

2022-07-20 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=35529) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=35529) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=35529) it.</sub>

2022-07-26 05:49 UTC, gupta-utkarsh requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: Some of the checks are too old. 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroup.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/35529#-N7t-Pnw92gqoE9mzE-e:-N7t-Pnw92gqoE9mzE-f:b32vmt) ([raw file](https://github.com/harness/harness-core/blob/08989cb5cdabc019cdfc4fcd6f67d2364078fb7d/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroup.java#L24)):*
> ```Java
> import lombok.ToString;
> import lombok.experimental.FieldDefaults;
> import lombok.experimental.FieldNameConstants;
> ```

??
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupService.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/35529#-N7t-Tcj86LScjQSDpeO:-N7t-Tcj86LScjQSDpeP:b-quobdx) ([raw file](https://github.com/harness/harness-core/blob/08989cb5cdabc019cdfc4fcd6f67d2364078fb7d/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupService.java#L26)):*
> ```Java
>   UserGroup upsert(@NotNull @Valid UserGroup userGroup);
> 
>   List<UserGroup> list(String userIdentifier);
> ```

Why do we need this without pagination?


<!-- Sent from Reviewable.io -->

2022-07-26 06:56 UTC, reetika04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: Some of the checks are too old. 19 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupService.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/35529#-N7t-Tcj86LScjQSDpeO:-N7tHVEN7LmLDGAmF-uB:b-vbmvg9) ([raw file](https://github.com/harness/harness-core/blob/08989cb5cdabc019cdfc4fcd6f67d2364078fb7d/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupService.java#L26)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Why do we need this without pagination?
</blockquote></details>

We are fetching all the user groups for a user at once to append these to the principal filter while fetching the role assignments.


<!-- Sent from Reviewable.io -->

2022-07-26 07:19 UTC, gupta-utkarsh requested changes
> Reviewed 3 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: Some of the checks are too old. 19 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/ScopeFilter.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/35529#-N7tMndUDe2pd6TQVAj0:-N7tMndV4v71atsXwXNx:b2m8m70) ([raw file](https://github.com/harness/harness-core/blob/08989cb5cdabc019cdfc4fcd6f67d2364078fb7d/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/ScopeFilter.java#L25)):*
> ```Java
> @ToString
> @EqualsAndHashCode
> public class ScopeFilter {
> ```

Can we use ScopeFilter instead of the newly created ScopeSelector? They are serving the same purpose.


<!-- Sent from Reviewable.io -->

2022-07-27 04:23 UTC, reetika04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: Some of the checks are too old. 19 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/ScopeFilter.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/35529#-N7tMndUDe2pd6TQVAj0:-N7xt6tE76Bd4XOIzgqf:b-338665) ([raw file](https://github.com/harness/harness-core/blob/08989cb5cdabc019cdfc4fcd6f67d2364078fb7d/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/ScopeFilter.java#L25)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Can we use ScopeFilter instead of the newly created ScopeSelector? They are serving the same purpose.
</blockquote></details>

ScopeSelector is for the UI and ScopeFilter is for the backend and since UI doesn’t understand the string we store in backend we are using the same filter as the resource group.


<!-- Sent from Reviewable.io -->

2022-08-01 19:09 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35529)

2022-08-29 08:59 UTC, ankit-harness requested changes
> Reviewed 5 of 19 files at r1, 2 of 6 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 26 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/AggregateUserGroupServiceImpl.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcZk9MC0Qb5qQtsmZk:-NAcZk9MC0Qb5qQtsmZl:b-29o6e1) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/AggregateUserGroupServiceImpl.java#L134)):*
> ```Java
>         userGroupService.list(scopeFilter, userIdentifier, searchTerm, getPageRequest(pageRequest));
> 
>     List<String> userIdentifiers = userGroupPageResponse.stream()
> ```

Can we reuse this logic somehow? I see this logic being repeat multiple places in this class
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcTuEe0GVaBZz4kMYW:-NAcTuEe0GVaBZz4kMYX:bmxyd6z) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L205)):*
> ```Java
>   @POST
>   @Path("acl/user/{userIdentifier}/usergroups")
>   @ApiOperation(value = "Get Aggregated User Group list by User Id", nickname = "getUserGroupAggregateListByUser")
> ```

I think we should avoid using word aggregate in the description. 
Description  can be -> Get User Groups by User Id
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcSzbU1vwjzvDFVkl-:-NAcSzbU1vwjzvDFVkl0:b423v5b) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L206)):*
> ```Java
>   @Path("acl/user/{userIdentifier}/usergroups")
>   @ApiOperation(value = "Get Aggregated User Group list by User Id", nickname = "getUserGroupAggregateListByUser")
>   public ResponseDTO<PageResponse<UserGroupAggregateDTO>> list(
> ```

Can we hide this API in API Documentation for now.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 207 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcTW2R5KfnfivHeO0N:-NAcTW2R5KfnfivHeO0O:b-tkyq7t) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L207)):*
> ```Java
>   @ApiOperation(value = "Get Aggregated User Group list by User Id", nickname = "getUserGroupAggregateListByUser")
>   public ResponseDTO<PageResponse<UserGroupAggregateDTO>> list(
>       @NotNull @PathParam("userIdentifier") String userIdentifier,
> ```

Make it "userId" for consistency with rest of the codebase.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 212 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcUOkN7nXsAliGxpS0:-NAcUOkN7nXsAliGxpS1:b-kwibey) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L212)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier, @BeanParam PageRequest pageRequest,
>       @QueryParam(NGResourceFilterConstants.SEARCH_TERM_KEY) String searchTerm,
>       @QueryParam("userSize") @DefaultValue("6") @Max(20) int userSize,
> ```

userCount instead of userSize
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 213 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcTaRv-E7Z-aMMmqN0:-NAcTaRv-E7Z-aMMmqN1:b6ffl59) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L213)):*
> ```Java
>       @QueryParam(NGResourceFilterConstants.SEARCH_TERM_KEY) String searchTerm,
>       @QueryParam("userSize") @DefaultValue("6") @Max(20) int userSize,
>       @Body UserGroupFilterForUser userGroupFilterForUser) {
> ```

This should be called ScopeFilter. Then it can be reused also at other places
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 213 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcaugM2LT1QLg8hzeg:-NAcaugM2LT1QLg8hzeh:bawjuaf) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L213)):*
> ```Java
>       @QueryParam(NGResourceFilterConstants.SEARCH_TERM_KEY) String searchTerm,
>       @QueryParam("userSize") @DefaultValue("6") @Max(20) int userSize,
>       @Body UserGroupFilterForUser userGroupFilterForUser) {
> ```

In UI, default scope should be that scope only in which User is being viewed. Otherwise, we will end up fetching a lot of data.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 228 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcaNsW6HS2vXKQtbcC:-NAcaNsW6HS2vXKQtbcD:b-p6ye1q) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L228)):*
> ```Java
>         scopeFilter.stream()
>             .map(scope -> {
>               if (ScopeFilterType.INCLUDING_CHILD_SCOPES.equals(scope.getFilter())) {
> ```

Can we create a method : buildCriteria(Scope scope) and move this logic over there.

and make sure all indexes are in place.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/dto/UserGroupFilterForUser.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcVKzqDx1pznlSgeaB:-NAcVKzqDx1pznlSgeaC:b-ultegg) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/123-ng-core-user/src/main/java/io/harness/ng/core/dto/UserGroupFilterForUser.java#L27)):*
> ```Java
> @Schema(name = "UserGroupFilterForUser")
> @OwnedBy(PL)
> public class UserGroupFilterForUser {
> ```

We can just defined it as 

class ScopeFilter {
  accountId;
  orgId;
  projectId;
  ChildScopeIncludeFilter childScopeIncludeFilter;
}

ChildScopeIncludeFilter {
  EXCLUDING_CHILD_SCOPES
  INCLUDING_CHILD_SCOPES
}
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcec8BA6AV9jfcvmc3:-NAcec8BA6AV9jfcvmc4:bklzl7s) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java#L119)):*
> ```Java
>       })
>   ResponseDTO<PageResponse<RoleAssignmentAggregateWithScope>>
>   getList(@BeanParam PageRequest pageRequest, @PathParam("userIdentifier") String userIdentifier,
> ```

Can we hide this API from outside world
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcew4e09xphcklgRkx:-NAcew4f5BCfzsOQSH6h:b-jjy06t) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java#L119)):*
> ```Java
>       })
>   ResponseDTO<PageResponse<RoleAssignmentAggregateWithScope>>
>   getList [...]

2022-09-02 13:30 UTC, ankit-harness requested changes
> Reviewed 7 of 19 files at r1, 3 of 6 files at r2, 1 of 2 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 24 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateWithScope.java` line 22 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyJpPR8MmXCHWJot4B:-NAyJpPR8MmXCHWJot4C:bz279r9) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateWithScope.java#L22)):*
> ```Java
> @ApiModel(value = "RoleAssignmentAggregateWithScope")
> @Schema(name = "RoleAssignmentAggregateWithScope")
> public class RoleAssignmentAggregateWithScope {
> ```

Why is it called RoleAssignmentAggregateWithScope and not just RoleAssignmentAggregate
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateWithScope.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyJko8Ccxb6tSTho_R:-NAyJko8Ccxb6tSTho_S:b-gzgzpx) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateWithScope.java#L29)):*
> ```Java
>   ResourceGroupDTO resourceGroup;
>   ScopeResponseDTO scope;
>   String principalName;
> ```

Why principalName here?
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyKkRpDCwcMwqKPBWP:-NAyKkRpDCwcMwqKPBWQ:bf2o5q6) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java#L110)):*
> ```Java
>   @POST
>   @Path("v2/filter")
>   @InternalApi
> ```

Should this be Internal API or hidden?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentDTOMapper.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyLrr38UplAepGUvuq:-NAyLrr38UplAepGUvur:biziqta) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentDTOMapper.java#L110)):*
> ```Java
>   }
> 
>   public RoleAssignmentFilter fromDTO(String identifier, List<UserGroup> userGroups, RoleAssignmentFilterV2 object) {
> ```

Shouldn't we be converting from v2 to v1 instead of v1 to v2.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 266 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyOD1uDvGX2v4LaQHG:-NAyOD1uDvGX2v4LaQHH:b-cchepf) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L266)):*
> ```Java
>           roleAssignmentFilterV2.getPrincipalIdentifier(), userGroups, roleAssignmentFilterV2);
>       PageResponse<RoleAssignment> pageResponse = roleAssignmentService.list(pageRequest, filter);
>       PageResponse<RoleAssignmentAggregateWithScope> roleAssignmentAggregateWithScope = pageResponse.map(response -> {
> ```

Can we move this mapping logic inside RoleAssignmentAggregateWithScope class itself
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentFilterV2.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyKBDPBTI-tapfWxPV:-NAyKBDPBTI-tapfWxPW:b-sq3wow) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentFilterV2.java#L28)):*
> ```Java
>   @Schema(description = "Filter role assignments based on scope filters")
>   Set<ScopeSelector> scopeFilters = new HashSet<>();
>   @NotNull PrincipalType principalType;
> ```

Why we have expanded this and not kept PrincipalDTO?


<!-- Sent from Reviewable.io -->

2022-09-05 02:58 UTC, ankit-harness reviewed
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 27 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-05 03:02 UTC, reetika04 reviewed
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 27 file(s) to review. 2 change requests. 22. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/AggregateUserGroupServiceImpl.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcZk9MC0Qb5qQtsmZk:-NBAa3DI6CdYPEKg83ot:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/AggregateUserGroupServiceImpl.java#L134)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we reuse this logic somehow? I see this logic being repeat multiple places in this class
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcTuEe0GVaBZz4kMYW:-NBAa4j1DB9OE82ETOHT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L205)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think we should avoid using word aggregate in the description. 
Description  can be -> Get User Groups by User Id
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcSzbU1vwjzvDFVkl-:-NBAa4CM9byp_UHtXO-g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L206)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we hide this API in API Documentation for now.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 212 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcUOkN7nXsAliGxpS0:-NBAa5QN8bcufecLq2Lq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L212)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

userCount instead of userSize
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 213 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcTaRv-E7Z-aMMmqN0:-NBAa5kY4AFsQsngBA8G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L213)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should be called ScopeFilter. Then it can be reused also at other places
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 213 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcaugM2LT1QLg8hzeg:-NBAa6ITB0T30MXCCuVw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L213)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

In UI, default scope should be that scope only in which User is being viewed. Otherwise, we will end up fetching a lot of data.
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 228 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcaNsW6HS2vXKQtbcC:-NBAa7HQ41-5kJvzAA0-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L228)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we create a method : buildCriteria(Scope scope) and move this logic over there.

and make sure all indexes are in place.
</blockquote></details>

Done.
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcec8BA6AV9jfcvmc3:-NBAaBFO5flNs-WgupOc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java#L119)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we hide this API from outside world
</blockquote></details>

Done.
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcew4e09xphcklgRkx:-NBAaBf76HE1ym7Y-9l-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java#L119)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

userId
</blockquote></details>

Done.
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAchB8mDu3-ttjju0nD:-NBAaCTWDftXJ7R_7Mah:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java#L119)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we define a new generic v2 filter API instead of defining a new API specific for Users. That API will use enhanced RoleAssignmentFilterDTO. 

We can improve RoleAssignmentFilterDTO by adding List<RoleAssignmentScopeFilter>. No need to have UserRoleAssignmentFilter


Return Type can be RoleAssignmentResponseDTO which can be changed to or a new v2 can be defined along these lines -

  String identifier;
  boolean disabled;
  Long createdAt;
  Long lastModifiedAt;
  boolean harnessManaged;
  ScopeResponseDTO scope;
  RoleResponseDTO role;
  ResourceGroupResponseDTO resourceGroup;
  PrincipalDTO principal;

  

ScopeResponseDTO {
  String accountIdentifier;
  String accountName;
  String orgIdentifier;
  String orgName;
  String projectIdentifier;
  String projectName;
}

RoleResponseDTO {
  RoleDTO role;
  ScopeResponseDTO scope;
  harnessManaged;
  createdAt;
  lastModifiedAt;
}

etc...


</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroup.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/35529#-N7t-Pnw92gqoE9mzE-e:-NBAaDeyBAsKjtsWXMEK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/08989cb5cdabc019cdfc4fcd6f67d2364078fb7d/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroup.java#L24)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

??
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentDTOMapper.ja [...]

2022-09-05 03:03 UTC, reetika04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 27 file(s) to review. 2 change requests. 26. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java` line 207 at r3](https://reviewable.io/reviews/harness/harness-core/35529#-NAcTW2R5KfnfivHeO0N:-NBAaQJ8DoITyTZh7hcF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fdbc7453e6104ee1cef02c95bcbe67d9e79083b/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGAggregateResource.java#L207)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Make it "userId" for consistency with rest of the codebase.
</blockquote></details>

Done.
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyKkRpDCwcMwqKPBWP:-NBAaRtw4RLsMLBJ7dC6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResource.java#L110)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be Internal API or hidden?
</blockquote></details>

Done.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroup.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/35529#-NAcWVMACW2frNySmGGk:-NBAaSfP0iep8Lz1z3VJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0a6acfca2ff9420a0323486471a29ed9ccdff880/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroup.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is this file in PR?
</blockquote></details>

Done.
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentFilterV2.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/35529#-NAyKBDPBTI-tapfWxPV:-NBAaRE--6LeKEgWIOTW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ea22fed34e84de8afa83244c7e2fbca76705a508/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentFilterV2.java#L28)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why we have expanded this and not kept PrincipalDTO?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-05 03:08 UTC, ankit-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529#-:-NBAbXp77uyAyICqUho3:bnfp4nl)* status: 27 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-05 05:49 UTC, gupta-utkarsh requested changes
> Reviewed 16 of 19 files at r1, 4 of 6 files at r2, 1 of 8 files at r3, 1 of 2 files at r4, 6 of 12 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 669 at r6](https://reviewable.io/reviews/harness/harness-core/35529#-NBBAmur6-ApfdG3hUGV:-NBBAmur6-ApfdG3hUGW:b-hksbit) ([raw file](https://github.com/harness/harness-core/blob/ef7be4bde98bd9741fe4e9d61e6873c8929e5b21/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L669)):*
> ```Java
>   }
> 
>   private Criteria createUserGroupByUserCriteria(
> ```

createUserGroupCriteriaByUser?
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/dto/ScopeSelector.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/35529#-NBBB09C7G_qV06lrxNk:-NBBB09C7G_qV06lrxNl:b81dlt4) ([raw file](https://github.com/harness/harness-core/blob/ef7be4bde98bd9741fe4e9d61e6873c8929e5b21/123-ng-core-user/src/main/java/io/harness/ng/core/dto/ScopeSelector.java#L37)):*
> ```Java
> public class ScopeSelector {
>   @NotNull @ApiModelProperty(required = true) ScopeFilterType filter;
>   String accountIdentifier;
> ```

Should we have @NotEmpty for accountIdentifier? Can it  be empty?


<!-- Sent from Reviewable.io -->

2022-09-05 05:58 UTC, reetika04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 669 at r6](https://reviewable.io/reviews/harness/harness-core/35529#-NBBAmur6-ApfdG3hUGV:-NBBDePJ1Q7e1FwV20lB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef7be4bde98bd9741fe4e9d61e6873c8929e5b21/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L669)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

createUserGroupCriteriaByUser?
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/dto/ScopeSelector.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/35529#-NBBB09C7G_qV06lrxNk:-NBBDfSVBrEHZZfh3q4c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef7be4bde98bd9741fe4e9d61e6873c8929e5b21/123-ng-core-user/src/main/java/io/harness/ng/core/dto/ScopeSelector.java#L37)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Should we have @NotEmpty for accountIdentifier? Can it  be empty?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-05 07:02 UTC, gupta-utkarsh approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-05 07:02 UTC, gupta-utkarsh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529#-:-NBBSBfGAG9FHBUhJUFt:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-05 07:05 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35529#-:-NBBT2H68O0bOSWJeQUB:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-05 07:29 UTC, merged