[feat]: [CDS-40800]: Added skelton files
harness/harness-core pull request #35669
Opened 2022-07-24 17:32 UTC by vivekkarnatiharness

## Describe your changes
Added basic code to add yaml save code google artifact

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-25 09:34 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-07-25 09:40 UTC, vivekkarnatiharness commented
trigger ti1

2022-07-25 09:42 UTC, vivekkarnatiharness commented
trigger ti0

2022-07-25 09:42 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-07-25 09:46 UTC, vivekkarnatiharness commented
trigger ti0

2022-08-01 19:20 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 20 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 19 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35669)

2022-08-17 07:04 UTC, shivamnegi94 requested changes
> Reviewed 14 of 32 files at r1, 34 of 34 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35669)* status: 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1079 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9e_1umBXroVDRmgl1T:-N9e_1un41HdzbDJcifL:b3wox2t) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/400-rest/src/main/java/software/wings/app/WingsModule.java#L1079)):*
> ```Java
>     bind(EcrClassicService.class).to(EcrClassicServiceImpl.class);
>     bind(GcrApiService.class).to(GcrApiServiceImpl.class);
>     bind(GarApiService.class).to(GARApiServiceImpl.class);
> ```

This class is even  in NGmodule also, is it needed here ?
___
*[`400-rest/src/test/java/software/wings/helpers/ext/gar/GarApiServiceTest.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9e_Zdw8Y7F2q-9o_YQ:-N9e_Zdw8Y7F2q-9o_YR:b-oqt8ne) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/400-rest/src/test/java/software/wings/helpers/ext/gar/GarApiServiceTest.java#L47)):*
> ```Java
>   //
>   //         wireMockRule.stubFor(WireMock.get(WireMock.urlEqualTo("/v2/teapot/tags/list"))
>   //                 .withHeader("Authorization", equalTo("auth"))
> ```

Why these lines are commented ?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9ea4Ss3rp5Vqpk_CjQ:-N9ea4Ss3rp5Vqpk_CjR:b5nv62r) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java#L62)):*
> ```Java
>         default:
>           saveLogs(executionLogCallback,
>               "No corresponding Docker artifact task type [{}]: " + artifactTaskParameters.toString());
> ```

please update the logs line docker to GAR
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9ea9T575nvxFVcofM5:-N9ea9T575nvxFVcofM6:bs6qvsh) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java#L66)):*
> ```Java
>           return ArtifactTaskResponse.builder()
>               .commandExecutionStatus(CommandExecutionStatus.FAILURE)
>               .errorMessage("There is no Docker artifact task type impl defined for - "
> ```

Here as well


<!-- Sent from Reviewable.io -->

2022-08-17 12:55 UTC, vivekkarnatiharness commented
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1079 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9e_1umBXroVDRmgl1T:-N9frkgR5nWt5Qxd4vGK:b-dm8j3m) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/400-rest/src/main/java/software/wings/app/WingsModule.java#L1079)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

This class is even  in NGmodule also, is it needed here ?
</blockquote></details>

Yes,It should be in Wingmodule as well!


<!-- Sent from Reviewable.io -->

2022-08-17 12:55 UTC, vivekkarnatiharness commented
*[`400-rest/src/test/java/software/wings/helpers/ext/gar/GarApiServiceTest.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9e_Zdw8Y7F2q-9o_YQ:-N9frtSY0MRcPRGJe7TO:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/400-rest/src/test/java/software/wings/helpers/ext/gar/GarApiServiceTest.java#L47)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

Why these lines are commented ?
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2022-08-17 12:56 UTC, vivekkarnatiharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9ea4Ss3rp5Vqpk_CjQ:-N9frzoa1sRF6kJyLsBP:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java#L62)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

please update the logs line docker to GAR
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-08-17 12:56 UTC, vivekkarnatiharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/35669#-N9ea9T575nvxFVcofM5:-N9fs0aOE30aVMC-cUPq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/99ef77f5a3599767e2b904b0f1af4abbee035346/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHelper.java#L66)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

Here as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-18 04:07 UTC, shivamnegi94 reviewed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35669)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-18 04:07 UTC, shivamnegi94 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35669)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-18 04:08 UTC, shivamnegi94 approved these changes

2022-08-18 09:50 UTC, puthrayaharness requested changes

2022-08-18 09:50 UTC, puthrayaharness commented on 125-cd-nextgen/src/test/java/io/harness/cdng/artifact/resources/gar/service/GarResourceServiceImplTest.java
> +  private static final String pkg = "pjg";
Fix Typo

2022-08-18 09:50 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/GarArtifactSummary.java
> +  String pkg;
@JsonProperty("package")

2022-08-18 09:50 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/GarArtifactSummary.java
> +  String pkg;
Summary should also include project, repo & region

2022-08-18 09:50 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ArtifactDelegateRequestUtils.java
> +      List<EncryptedDataDetail> encryptedDataDetails, ArtifactSourceType sourceType, int MAXBUILDS) {
`MAXBUILDS` -> `maxBuilds`

2022-08-18 09:50 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/GarArtifactOutcome.java
> +    return null;
Why is this `null`?

2022-08-18 09:50 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googleartifactregistry/GARArtifactTaskHandler.java
> +public class GARArtifactTaskHandler extends DelegateArtifactTaskHandler<GarDelegateRequest> {
Please add test cases to this file. We should cover cases where we are throwing exceptions.

2022-08-18 09:50 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +    return "https://"
Make this oneline.

2022-08-18 09:50 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GarApiService.java
> +  int MAX_NO_OF_TAGS_PER_IMAGE = 10000;
Remove this.

2022-08-18 09:50 UTC, puthrayaharness commented on 980-commons/src/main/java/io/harness/artifact/ArtifactMetadataKeys.java
> +  String PACKAGE = "package";
`PACKAGE` -> `artifactPackage`. 
Where is this used? We can change `package` to `artifactPackage`

2022-08-18 09:50 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +                metadata.put(ArtifactMetadataKeys.PACKAGE, tagFinal);
Also add repository name, project name etc to the this?

2022-08-24 13:46 UTC, puthrayaharness requested changes

2022-08-24 13:46 UTC, puthrayaharness commented on 960-api-services/src/test/java/io/harness/gar/GARApiServiceTest.java
> +  //  @Owner(developers = vivekveman)
If these changes are not requires Please remove it.

2022-08-24 13:46 UTC, puthrayaharness commented on 120-ng-manager/config.yml
> -shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-false}
Please revert

2022-08-24 17:13 UTC, vivekkarnatiharness commented
trigger ti0

2022-08-24 18:56 UTC, vivekkarnatiharness commented
trigger ti0

2022-08-24 18:57 UTC, vivekkarnatiharness commented
trigger ti0

2022-08-24 18:58 UTC, vivekkarnatiharness commented
trigger ti1
trigger ti2

2022-08-24 19:08 UTC, vivekkarnatiharness commented
trigger ti1

2022-08-24 19:08 UTC, vivekkarnatiharness commented
trigger ti4

2022-08-24 19:08 UTC, vivekkarnatiharness commented
trigger ti3

2022-08-25 04:05 UTC, vivekkarnatiharness commented
trigger ti4

2022-08-25 04:09 UTC, vivekkarnatiharness commented
trigger ti4

2022-08-25 06:19 UTC, vivekkarnatiharness commented
trigger ti0

2022-08-25 06:36 UTC, vivekkarnatiharness commented
trigger ti4

2022-08-25 06:38 UTC, vivekkarnatiharness commented
trigger ft1

2022-08-25 06:39 UTC, vivekkarnatiharness commented
trigger ft2

2022-08-25 06:55 UTC, vivekkarnatiharness commented
trigger feature-build

2022-08-25 07:34 UTC, vivekkarnatiharness commented
trigger feature-build

2022-08-25 22:42 UTC, puthrayaharness requested changes

2022-08-25 22:42 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/GarRequestResponseMapper.java
> +  public GarInternalConfig toGarInternalConfig(GarDelegateRequest request, String bearerToken) {
These can be static methods

2022-08-25 22:42 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/GarRequestResponseMapper.java
> +  public GarDelegateResponse toGarResponse(BuildDetailsInternal buildDetailsInternal, GarDelegateRequest request) {
can be static method

2022-08-25 22:42 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +            "Google Artifact Registry: Connector provided Is not Having Artifact Registry Reader permission",
we are capitalizing message unnecessarily- `Is` -> `is`

2022-08-25 22:42 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +            "Google Artifact Registry: Connector provided Is not Having Artifact Registry Reader permission",
-> `The connector provided does not have sufficient privileges to access Google artifact registry`

2022-08-25 22:42 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +        throw NestedExceptionUtils.hintWithExplanationException("Google Artifact Registry", "Google Artifact Registry",
Please fix the hint & explanation.

2022-08-25 22:42 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +            "Please Check Project,RepositoryName,Package,Region fields",
You should have space after commas. Unnecessary capitalization

2022-08-25 22:42 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +            "Google Artifact Registry: Check Values of Project,RepositoryName,Package,Region Field",
Both Hint & explanation are the same. Can you please ensure they are different?

2022-08-25 22:42 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java
> +            "Check connector's permission and credentials",
Check -> Please check

2022-08-30 09:01 UTC, puthrayaharness commented
*[`960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java` line 178 at r9](https://reviewable.io/reviews/harness/harness-core/35669#-N8OxTjoQbm4TUzwkRku-r9-178:-NAhyqIqDUiZ59jH1KHN:b-r7jn8o) ([raw file](https://github.com/harness/harness-core/blob/53d2ccf66e99de40e05299a60357ea3895451c8f/960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java#L178)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please fix the hint & explanation. 
</blockquote></details>

Could you please check this?


<!-- Sent from Reviewable.io -->

2022-08-30 15:03 UTC, vivekkarnatiharness commented
trigger codebasehash

2022-09-01 05:32 UTC, vivekkarnatiharness commented
trigger codebasehash

2022-09-01 05:39 UTC, vivekkarnatiharness commented
trigger codebasehash

2022-09-01 05:56 UTC, vivekkarnatiharness commented
trigger codebasehash

2022-09-01 07:31 UTC, puthrayaharness approved these changes
> Reviewed 10 of 32 files at r1, 9 of 34 files at r2, 1 of 3 files at r3, 10 of 18 files at r5, 3 of 14 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 2 of 7 files at r10, 9 of 13 files at r11, 1 of 1 files at r12, 3 of 4 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35669)* status: 1. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-01 07:32 UTC, puthrayaharness commented
trigger codebasehash

2022-09-01 07:43 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35669)* status: 1. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-01 07:52 UTC, merged