techdebt: [SRM-11078]: Adding db record migration code to delete TimeSeriesRisk…
harness/harness-core pull request #35664
Opened 2022-07-23 10:40 UTC by dhruv-harness

…Summary records older than 180 days.

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-07-25 20:11 UTC, praveensugavanam requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35664)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/TimeSeriesRiskSummaryTTLMigration.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/35664#-N7qypgK4Nbtk9XgJb7Y:-N7qypgK4Nbtk9XgJb7Z:bm3185r) ([raw file](https://github.com/harness/harness-core/blob/59e7a6c50302d86ec65b52c24626381af5ded384/390-db-migration/src/main/java/io/harness/migrations/all/TimeSeriesRiskSummaryTTLMigration.java#L48)):*
> ```Java
>       long documentsToBeDeleted = query.count();
>       log.info("Number of records to be deleted " + documentsToBeDeleted);
>       wingsPersistence.deleteOnServer(query);
> ```

this might be a very heavy call to the DB depending on the number of elements. Ideally, you want to delete 100 at a time maybe ? That way you can reduce the DB load per call. 


<!-- Sent from Reviewable.io -->

2022-07-26 17:15 UTC, praveensugavanam approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35664)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-07-27 08:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=35664) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=35664) before we can accept your contribution.<br/>**12** out of **14** committers have signed the CLA.<br/><br/>:white_check_mark: GabeAboy<br/>:white_check_mark: dhruv-harness<br/>:white_check_mark: jennyjames21<br/>:white_check_mark: trunapushpa<br/>:white_check_mark: vcalasansh<br/>:white_check_mark: smjt-h<br/>:white_check_mark: raghavharness<br/>:white_check_mark: namanvermah<br/>:white_check_mark: sahilhindwani-harness<br/>:white_check_mark: prashantsharma04<br/>:white_check_mark: puthrayaharness<br/>:white_check_mark: AnupamIO<br/>:x: upadhyay-an<br/>:x: nikunj-badjatya<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=35664) it.</sub>

2022-07-27 21:59 UTC, praveensugavanam approved these changes

2022-08-01 05:33 UTC, deepak-harness approved these changes

2022-08-01 05:42 UTC, sunilgupta-harness commented
reviewable is not getting updated

2022-08-01 05:42 UTC, merged