[fix]: [CDS-25409]: Github Package Artifact Source
harness/harness-core pull request #35742
Opened 2022-07-26 11:25 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-01 20:04 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35742)

2022-08-08 13:59 UTC, puthrayaharness requested changes

2022-08-08 13:59 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +    if (EmptyPredicate.isEmpty(version) && EmptyPredicate.isEmpty(versionRegex)) {
Please use StringUtils.isBlank to check for empty string. It takes care of `null`, `""`, `"      "` as well.

2022-08-08 13:59 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java
> +  private static final String AUTHENTICATE_HEADER = "Www-Authenticate";
Unused. Remove

2022-08-08 13:59 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java
> +  private static final int MAX_NUMBER_OF_BUILDS = 250;
Unused remove

2022-08-08 13:59 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryService.java
> +  int MAX_NO_OF_TAGS_PER_IMAGE = 10000;
Remove this.

2022-08-08 13:59 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/GithubPackagesArtifactConfig.java
> +  @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) @Wither ParameterField<String> packageType;
This should be an enum. It should not be a parameterField

2022-08-08 13:59 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactDelegateRequest.java
> +    List<ExecutionCapability> capabilities =
The execution capability needs to check for access to HTTP requests to `https://api.github.com`. It does not need to check SSH etc.

2022-08-30 06:39 UTC, puthrayaharness requested changes

2022-08-30 06:39 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java
> +        attributes.getPackageType(), attributes.getOrg(), attributes.getVersionRegex(), MAX_NO_OF_TAGS_PER_IMAGE);
`MAX_NO_OF_TAGS_PER_IMAGE` should not be defined on the delegate side. We should not have a limit in the first place.

2022-08-30 06:39 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java
> +  private static final int ARTIFACT_RETENTION_SIZE = 25;
Please remove since not used.

2022-08-30 06:39 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java
> +  private static final int MAX_RETRY = 5;
Please remove if not used.

2022-09-01 13:00 UTC, puthrayaharness requested changes

2022-09-02 08:35 UTC, puthrayaharness requested changes

2022-09-02 08:35 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/serializer/kryo/NGEntitiesKryoRegistrar.java
> -    kryo.register(GarArtifactOutcome.class, 130022);
Never change existing Kryo values. Please revert these changes.

2022-09-02 08:44 UTC, puthrayaharness requested changes

2022-09-02 08:44 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java
> +            githubPackagesRestClient.listVersionsForPackages(basicAuthHeader, packageName, packageType, 100, i)
Please create a static variable with `100`. Do not hard everywhere

2022-09-02 08:44 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/beans/GithubPackagesConfig.java
> +@TargetModule(HarnessModule._957_CG_BEANS)
Remove target module

2022-09-05 10:56 UTC, shivamnegi94 requested changes

2022-09-05 10:56 UTC, shivamnegi94 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactDelegateRequest.java
> +        "https://api.github.com", maskingEvaluator));
Why we have hardcoded the URL?

2022-09-05 11:08 UTC, vtxorxwitty commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactDelegateRequest.java
> +        "https://api.github.com", maskingEvaluator));
Because for github packages the connection url that we get from connector is different from the one to access the artifact repo. So we need to hard code this url.

2022-09-05 11:14 UTC, vtxorxwitty commented on 120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java
> +      }
So in case of else statement, we don't want to do anything. The username will not get populated and the image details will not be fetched.

2022-09-05 11:20 UTC, shivamnegi94 approved these changes

2022-09-05 11:20 UTC, shivamnegi94 reviewed
> Reviewed 4 of 40 files at r2, 36 of 65 files at r4, 17 of 28 files at r5, 4 of 6 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35742)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-05 11:22 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35742)* status: 1 change requests. 14. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/35742#-N8xWBW83TSkulDa2JV4-r2-81:-NBCNcWdBxqnCr62aZBC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65ae8b18fbe90efdde4f90355bb0208721879a23/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L81)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please use StringUtils.isBlank to check for empty string. It takes care of `null`, `""`, `"      "` as well.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/GithubPackagesArtifactOutcome.java` line 88 at r5](https://reviewable.io/reviews/harness/harness-core/35742#-N8xGznrN3bkyS_RHNW3-r5-88:-NBCNdd6DPkEIBaNUQut:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/15b0ed1ce9d06f21847e39e19d14ba4cc6db1a9e/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/GithubPackagesArtifactOutcome.java#L88)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Why is this `null`? This should be nothing but value of version
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/35742#-N8UTSEv2LoHnIB4Ep4t-r4-36:-NBCNe4MBxnwUnmlqM1W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb2f3343116270914faf63bec02bb0e9baf19c3a/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java#L36)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please remove since not used.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/35742#-N8UTSEv2LoHnIB4Ep4t-r4-37:-NBCNeTi5XEPHfpICriC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb2f3343116270914faf63bec02bb0e9baf19c3a/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java#L37)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please remove if not used.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/35742#-N8UTSEv2LoHnIB4Ep4t-r4-46:-NBCNex40o6OMjpQPV6T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb2f3343116270914faf63bec02bb0e9baf19c3a/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactTaskHandler.java#L46)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

`MAX_NO_OF_TAGS_PER_IMAGE` should not be defined on the delegate side. We should not have a limit in the first place. 
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/GithubPackagesConfig.java` line 41 at r6](https://reviewable.io/reviews/harness/harness-core/35742#-N8hg7jK4wKfYm0D6YLE-r6-41:-NBCNfMu8UEaiVFds8ut:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d49e2a9e678543d9e60ab378558a070580890fb/930-delegate-tasks/src/main/java/software/wings/beans/GithubPackagesConfig.java#L41)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Remove target module
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactDelegateRequest.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/35742#-N8Xnehwao53-6bqLr7X-r3-57:-NBCNfs100Wpjs9oIp_l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/34bd2808c8ff8ea74b223509af2d63160da956ad/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/githubpackages/GithubPackagesArtifactDelegateRequest.java#L57)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

The execution capability needs to check for access to HTTP requests to `https://api.github.com`. It does not need to check SSH etc.
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryService.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/35742#-N8YU6BGmssvDalVtq9E-r2-22:-NBCNgaY-QDkWBNg6l4F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65ae8b18fbe90efdde4f90355bb0208721879a23/960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryService.java#L22)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/35742#-N8YU6BGmssvDalVtq9F-r2-44:-NBCNh-QD310rLz0V_pv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65ae8b18fbe90efdde4f90355bb0208721879a23/960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java#L44)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Unused. Remove
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/35742#-N8YU6BGmssvDalVtq9F-r2-45:-NBCNhGLCbXBPjIlbeQ0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65ae8b18fbe90efdde4f90355bb0208721879a23/960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java#L45)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Unused remove
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java` line 259 at r6](https://reviewable.io/reviews/harness/harness-core/35742#-N8YU6BGmssvDalVtq9F-r6-259:-NBCNhtc-3aiXoL5Im3F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d49e2a9e678543d9e60ab378558a070580890fb/960-api-services/src/main/java/io/harness/artifacts/githubpackages/service/GithubPackagesRegistryServiceImpl.java#L259)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please create a static variable with `100`. Do not hard everywhere
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/GithubPackagesArtifactConfig.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/35742#-N8xWBW83TSkulDa2JV6-r3-63:-NBCNdAf9pFY3FWxExFm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/34bd2808c8ff8ea74b223509af2d63160da956ad/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/GithubPackagesArtifactConfig.java#L63)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

This should be an enum. It should not be a parameterField
</blockquote></details>

Do [...]

2022-09-05 11:49 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 4 of 40 files at r2, 36 of 65 files at r4, 17 of 28 files at r5, 4 of 6 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35742)* status: 1 change requests. 14. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-05 11:50 UTC, vtxorxwitty commented
trigger codebasehash

2022-09-07 06:18 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 40 files at r2, 36 of 65 files at r4, 17 of 28 files at r5, 4 of 6 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35742#-:-NBLaJ62AnGLiKE5mnx5:bnfp4nl)* status: 1 change requests. 14. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-07 06:19 UTC, vtxorxwitty commented
trigger codebasehash

2022-09-11 21:43 UTC, puthrayaharness approved these changes
> Reviewed 4 of 40 files at r2, 36 of 65 files at r4, 17 of 28 files at r5, 4 of 6 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35742)* status: Some of the checks are too old. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-12 05:54 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 177 of 177 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35742)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-12 08:30 UTC, puthrayaharness approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35742)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-12 08:30 UTC, puthrayaharness commented
trigger codebasehash

2022-09-12 08:31 UTC, vtxorxwitty commented
trigger codebasehash

2022-09-12 08:42 UTC, merged