fix: [CDS-41026]: separating client tools according to manifest and store types
harness/harness-core pull request #35802
Opened 2022-07-28 06:01 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-01 20:14 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35802)

2022-08-04 10:30 UTC, GoelPratyush99 commented
TI-bootstrap: trigger ti0

2022-08-04 10:45 UTC, abosii-harness requested changes
> Reviewed 3 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 19 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java` line 195 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cPTDAEa-sKkdlnLNq:-N8cPTDAEa-sKkdlnLNr:bi6acj8) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L195)):*
> ```Java
>   private StoreType getManifestTypeFromK8sTaskParamerters(K8sTaskParameters k8sTaskParameters) {
>     if (k8sTaskParameters instanceof K8sApplyTaskParameters) {
>       return ((K8sApplyTaskParameters) k8sTaskParameters).getK8sDelegateManifestConfig().getManifestStoreTypes();
> ```

getK8sDelegateManifestConfig() can be made as part of K8sTaskParameters interface so this cast will not be required anymore, only null check
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cPg5g68hIuHcS0pyU:-N8cPg5g68hIuHcS0pyV:b54fjmu) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L207)):*
> ```Java
>       return ((K8sCanaryDeployTaskParameters) k8sTaskParameters).getK8sDelegateManifestConfig().getManifestStoreTypes();
>     } else if (k8sTaskParameters instanceof K8sDeleteTaskParameters) {
>       return ((K8sDeleteTaskParameters) k8sTaskParameters).getK8sDelegateManifestConfig().getManifestStoreTypes();
> ```

What if k8s delete is using delete by resource name/release name wouldn't getK8sDelegateManifestConfig() return null? 
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cQeknCB-t2x2Scj3V:-N8cQeknCB-t2x2Scj3W:b-s8bqlw) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L104)):*
> ```Java
>   @Inject private K8sGlobalConfigService k8sGlobalConfigService;
> 
>   public static final Set<String> openshiftResources = ImmutableSet.of("Route");
> ```

Why only Route is included in openshift resources? If I remember right all the logic is based on DeploymentConfig
and all constants should be upper case separated by underscore 
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRHFH1JJ48IGZB8dv:-N8cRHFH1JJ48IGZB8dw:bxf2op8) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L160)):*
> ```Java
> 
>     K8sDelegateTaskParams updatedK8sDelegateTaskParams =
>         k8sDelegateTaskParams.toBuilder().ocPath(checkForRequirementOfOcBinaries()).build();
> ```

wouldn't be safer to update existing object rather than create a new one?
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 456 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRPjS4GloX2nrViub:-N8cRPjS4GloX2nrViuc:bv0ylm8) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L456)):*
> ```Java
>   }
> 
>   private String checkForRequirementOfOcBinaries() {
> ```

method name doesn't really reflect what method is doing. Check here would mean that you would validate something and return true/false,  splitting method in check and if check matches setup oc path in object
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRk8w2VHveS62nmPt:-N8cRk8w2VHveS62nmPu:b-821ued) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L106)):*
> ```Java
>   @Inject private K8sGlobalConfigService k8sGlobalConfigService;
> 
>   public static final Set<String> openshiftResources = ImmutableSet.of("Route");
> ```

Same here, why we're relying only on Route and not DeploymentConfig?
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRqOD0I2n9QzY1HYM:-N8cRqOD0I2n9QzY1HYN:b9oja1f) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L478)):*
> ```Java
>   }
> 
>   private String checkForRequirementOfOcBinaries() {
> ```

This method looks generic enough to be generalized for all task types 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cS8x5BkWCRnSGjIZa:-N8cS8x5BkWCRnSGjIZb:b-rbl3uf) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java#L81)):*
> ```Java
>   @Inject private K8sGlobalConfigService k8sGlobalConfigService;
> 
>   public static final Set<String> openshiftResources = ImmutableSet.of("Route");
> ```

this again should support DeploymentConfig not Route, and I think it should be a common constant for every handler
___
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cSUxnD1Y4Qa63o9d7:-N8cSUxnD1Y4Qa63o9d8:b-gwngai) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L101)):*
> ```Java
>       return InstallUtils.getPath(tool, version);
>     } catch (Exception e) {
>       throw new UnsupportedOperationException(
> ```

try catch block should be removed at all


<!-- Sent from Reviewable.io -->

2022-08-04 12:31 UTC, GoelPratyush99 commented
TI-bootstrap: trigger ti0

2022-08-05 08:28 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 40 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java` line 195 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cPTDAEa-sKkdlnLNq:-N8gJOmg7F3uoa5zdULp:b3oh8n) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L195)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

getK8sDelegateManifestConfig() can be made as part of K8sTaskParameters interface so this cast will not be required anymore, only null check
</blockquote></details>


Done.
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cPg5g68hIuHcS0pyU:-N8h5R7j4GVpHH3O4H1c:bnuua9) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/K8sTask.java#L207)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What if k8s delete is using delete by resource name/release name wouldn't getK8sDelegateManifestConfig() return null? 
</blockquote></details>

Moved the k8sDelegateManifestConfig to K8sTaskParameters.
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cQeknCB-t2x2Scj3V:-N8h5Y9W1M4JZ4F4CzVb:b-w6bdi9) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L104)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why only Route is included in openshift resources? If I remember right all the logic is based on DeploymentConfig
and all constants should be upper case separated by underscore 
</blockquote></details>

Deployment config is called during steady state check and during apply manifest and dryRunManifest we only check for routes.
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRHFH1JJ48IGZB8dv:-N8h5lHW66ifU4ZK11Y2:b-tjg4ab) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L160)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

wouldn't be safer to update existing object rather than create a new one?
</blockquote></details>

Removed this logic.
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java` line 456 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRPjS4GloX2nrViub:-N8h5q893wr7WMzLOzHn:bzcp446) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sBlueGreenDeployTaskHandler.java#L456)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

method name doesn't really reflect what method is doing. Check here would mean that you would validate something and return true/false,  splitting method in check and if check matches setup oc path in object
</blockquote></details>

Changed it to setupPathForOcBinaries for Helm CG and NG.
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRk8w2VHveS62nmPt:-N8h68tx429OHLHg6M_s:b3rvze1) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L106)):*
> Deployment config is called during steady state check and during apply manifest and dryRunManifest we only check for routes.
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cRqOD0I2n9QzY1HYM:-N8h69uaBiFYiQfPb-PP:b-dngg4i) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L478)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This method looks generic enough to be generalized for all task types 
</blockquote></details>

Replaced it with InstallUtils.getLatestVersionPath where required.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cS8x5BkWCRnSGjIZa:-N8h6bm60exELZNosoc8:b-624hcf) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sApplyRequestHandler.java#L81)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this again should support DeploymentConfig not Route, and I think it should be a common constant for every handler
</blockquote></details>

Same here. Deployment config is called during steady state check and during apply manifest and dryRunManifest we only check for routes.
___
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/35802#-N8cSUxnD1Y4Qa63o9d7:-N8h6hCHBFiYyLn5weH5:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2573583a7cf68bf397c1d26b7fafc81a97e61e70/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L101)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

try catch block should be removed at all
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-08-05 11:51 UTC, shubham-in10se submitted a review, later dismissed
> Reviewed 3 of 22 files at r1, 17 of 29 files at r2, 2 of 11 files at r3, 2 of 2 files at r4, 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 1 change requests. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-05 11:54 UTC, GoelPratyush99 commented
CodeBaseHash: trigger codebasehash

2022-08-08 08:08 UTC, shubham-in10se requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 2 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 388 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wU0i77yNN3MFWmEzQ:-N8wU0i77yNN3MFWmEzR:b-knyqkk) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L388)):*
> ```Java
>       ocPath = InstallUtils.getLatestVersionPath(OC);
>     } catch (Exception ex) {
>       log.info(ex.getMessage());
> ```

always add some context info while logging.
Also, this is an exception we are logging, why at INFO level.?
If it is only for info, add relevant information for the same.
e.g.: "Could not fetch OC path from InstallUtils. Skipping as it might not be installed. Using null"
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 865 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUnP8-vs58_i4MPPH:-N8wUnP8-vs58_i4MPPI:b-a3mkfl) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L865)):*
> ```Java
>     try {
>       ocPath = InstallUtils.getLatestVersionPath(OC);
>     } catch (IllegalArgumentException ex) {
> ```

this code block appears 3-4 times in this same file. Extract this to a different method.



_Code quote:_
```Java
    String ocPath = null;
    try {
      ocPath = InstallUtils.getLatestVersionPath(OC);
    } catch (IllegalArgumentException ex) {
      log.info(ex.getMessage());
    }
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 866 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUS_o1Gc2cT5mj7nI:-N8wUS_p36nJKZ_Cz2aM:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L866)):*
> ```Java
>       ocPath = InstallUtils.getLatestVersionPath(OC);
>     } catch (IllegalArgumentException ex) {
>       log.info(ex.getMessage());
> ```

same as above
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 1206 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUUp-09TPA1VZq3ep:-N8wUUp-09TPA1VZq3eq:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1206)):*
> ```Java
>       ocPath = InstallUtils.getLatestVersionPath(OC);
>     } catch (IllegalArgumentException ex) {
>       log.info(ex.getMessage());
> ```

same as above
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 1488 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUW2m1XJIcH-TIcMO:-N8wUW2m1XJIcH-TIcMP:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1488)):*
> ```Java
>           ocPath = InstallUtils.getLatestVersionPath(OC);
>         } catch (IllegalArgumentException ex) {
>           log.info(ex.getMessage());
> ```

same as above
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java` line 1189 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUYXA5Of6b8KBi3-S:-N8wUYXA5Of6b8KBi3-T:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L1189)):*
> ```Java
>           ocPath = InstallUtils.getLatestVersionPath(OC);
>         } catch (IllegalArgumentException ex) {
>           log.info(ex.getMessage());
> ```

same as above


<!-- Sent from Reviewable.io -->

2022-08-08 09:05 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 4 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 388 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wU0i77yNN3MFWmEzQ:-N8wgWHK7dyDDDUPAADh:bf4wabl) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L388)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

always add some context info while logging.
Also, this is an exception we are logging, why at INFO level.?
If it is only for info, add relevant information for the same.
e.g.: "Could not fetch OC path from InstallUtils. Skipping as it might not be installed. Using null"
</blockquote></details>

Logged it at warn level as the user need to at-least configure the env variable to ensure OC command works.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 865 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUnP8-vs58_i4MPPH:-N8wgnXMEBc1_5Fj2I8W:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L865)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

this code block appears 3-4 times in this same file. Extract this to a different method.
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 866 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUS_o1Gc2cT5mj7nI:-N8wgosk60mFIwx1WHTp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L866)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 1206 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUUp-09TPA1VZq3ep:-N8wgpyC1HTiGD2yaT4W:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1206)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 1488 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUW2m1XJIcH-TIcMO:-N8wgqfM0UjYzWIRWeWC:bb6tzbb) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1488)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

DOne
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java` line 1189 at r6](https://reviewable.io/reviews/harness/harness-core/35802#-N8wUYXA5Of6b8KBi3-S:-N8wgr_k3OCGs-UVzGR-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/150bd71a8a130a9a0c0398efb442e55476f10e8d/930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L1189)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-08-08 09:53 UTC, shubham-in10se submitted a review, later dismissed
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 1 change requests. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-08 10:46 UTC, GoelPratyush99 commented
CodeBaseHash: trigger codebasehash

2022-08-08 11:54 UTC, abosii-harness approved these changes
> Reviewed 3 of 22 files at r1, 16 of 29 files at r2, 2 of 11 files at r3, 1 of 2 files at r4, 14 of 16 files at r5, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-08 17:41 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java` line 172 at r7](https://reviewable.io/reviews/harness/harness-core/35802#-N8yY-RL0sQ7tzOe_oSp:-N8yY-RM9lIz9h_YW1mQ:b-drcpl1) ([raw file](https://github.com/harness/harness-core/blob/6e28f63cb89e7359acb7e6c2871a698a50fa9284/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java#L172)):*
> ```Java
>         containerDeploymentDelegateBaseHelper.createKubernetesConfig(commandRequestNG.getK8sInfraDelegateConfig()));
>     commandRequestNG.setKubeConfigLocation(configLocation);
>     commandRequestNG.setOcPath(k8sGlobalConfigService.getOcPath());
> ```

is this intentional ? 


<!-- Sent from Reviewable.io -->

2022-08-08 18:13 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java` line 172 at r7](https://reviewable.io/reviews/harness/harness-core/35802#-N8yY-RL0sQ7tzOe_oSp:-N8ye0J02adFBVmeaVLo:b7j7mkc) ([raw file](https://github.com/harness/harness-core/blob/6e28f63cb89e7359acb7e6c2871a698a50fa9284/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java#L172)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this intentional ? 
</blockquote></details>

I have removed setOcPath and will be using if only if required in apply manifest step depending on openshift resources.



_Code snippet:_
```Java
 commandRequestNG.setOcPath(k8sGlobalConfigService.getOcPath());
```


<!-- Sent from Reviewable.io -->

2022-08-08 18:23 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java` line 172 at r7](https://reviewable.io/reviews/harness/harness-core/35802#-N8yY-RL0sQ7tzOe_oSp:-N8yg5tN8oW5aRu0CbrP:b-vnfi3m) ([raw file](https://github.com/harness/harness-core/blob/6e28f63cb89e7359acb7e6c2871a698a50fa9284/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java#L172)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

I have removed setOcPath and will be using if only if required in apply manifest step depending on openshift resources.
</blockquote></details>

Sorry apply is for k8s. steady state check step in HelmDeployServiceImplNG.java



_Code snippet:_
```Java
commandRequest.setOcPath(setupPathOfOcBinaries(entry.getValue()));
```


<!-- Sent from Reviewable.io -->

2022-08-09 08:00 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3062 at r8](https://reviewable.io/reviews/harness/harness-core/35802#-N90b43o9LEjRW66DVhV:-N90b43o9LEjRW66DVhW:b-6mrk4) ([raw file](https://github.com/harness/harness-core/blob/26d898b6287ca277adc5500878d99e4a06a3b745/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3062)):*
> ```Java
>   }
> 
>   public static String getLatestVersionOcPath() {
> ```

should be private


<!-- Sent from Reviewable.io -->

2022-08-09 08:00 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3069 at r8](https://reviewable.io/reviews/harness/harness-core/35802#-N90bCD82Votqsp3TZ4M:-N90bCD82Votqsp3TZ4N:bvjxju7) ([raw file](https://github.com/harness/harness-core/blob/26d898b6287ca277adc5500878d99e4a06a3b745/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3069)):*
> ```Java
>       log.warn("Unable to fetch OC binary path from delegate. Kindly ensure it is configured as env variable." + ex);
>     }
>     return ocPath;
> ```

we should not return null, should we default to "oc"


<!-- Sent from Reviewable.io -->

2022-08-09 09:03 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 5 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3062 at r8](https://reviewable.io/reviews/harness/harness-core/35802#-N90b43o9LEjRW66DVhV:-N90pwd0Abo1mLXAwSd-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26d898b6287ca277adc5500878d99e4a06a3b745/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3062)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be private
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3069 at r8](https://reviewable.io/reviews/harness/harness-core/35802#-N90bCD82Votqsp3TZ4M:-N90pwy90RNzwclzW8at:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26d898b6287ca277adc5500878d99e4a06a3b745/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3069)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should not return null, should we default to "oc"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-09 09:12 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sBlueGreenDeployTaskParameters.java` line 71 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90s1NdDwtH9kMTIGfV:-N90s1NdDwtH9kMTIGfW:bosg5qi) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sBlueGreenDeployTaskParameters.java#L71)):*
> ```Java
>         new ArrayList<>(super.fetchRequiredExecutionCapabilities(maskingEvaluator));
> 
>     Set<String> delegateSelectors = getDelegateSelectorsFromConfigs(super.getK8sDelegateManifestConfig());
> ```

we do not need super here


<!-- Sent from Reviewable.io -->

2022-08-09 09:12 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sCanaryDeployTaskParameters.java` line 81 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90s5so9cjrQS95ZOWy:-N90s5so9cjrQS95ZOWz:bosg5qi) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sCanaryDeployTaskParameters.java#L81)):*
> ```Java
>         new ArrayList<>(super.fetchRequiredExecutionCapabilities(maskingEvaluator));
> 
>     Set<String> delegateSelectors = getDelegateSelectorsFromConfigs(super.getK8sDelegateManifestConfig());
> ```

we do not need super here


<!-- Sent from Reviewable.io -->

2022-08-09 09:12 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDeleteTaskParameters.java` line 63 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90s9H2Aa1_anXgNTOf:-N90s9H2Aa1_anXgNTOg:bosg5qi) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDeleteTaskParameters.java#L63)):*
> ```Java
>         new ArrayList<>(super.fetchRequiredExecutionCapabilities(maskingEvaluator));
> 
>     Set<String> delegateSelectors = getDelegateSelectorsFromConfigs(super.getK8sDelegateManifestConfig());
> ```

we do not need super here


<!-- Sent from Reviewable.io -->

2022-08-09 09:13 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sRollingDeployTaskParameters.java` line 77 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90sD8dDx3cNm_V20MV:-N90sD8dDx3cNm_V20MW:bosg5qi) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sRollingDeployTaskParameters.java#L77)):*
> ```Java
>         new ArrayList<>(super.fetchRequiredExecutionCapabilities(maskingEvaluator));
> 
>     Set<String> delegateSelectors = getDelegateSelectorsFromConfigs(super.getK8sDelegateManifestConfig());
> ```

we do not need super here


<!-- Sent from Reviewable.io -->

2022-08-09 09:13 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 22 files at r1, 5 of 29 files at r2, 2 of 11 files at r3, 1 of 2 files at r4, 13 of 16 files at r5, 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-09 09:25 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 6 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sBlueGreenDeployTaskParameters.java` line 71 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90s1NdDwtH9kMTIGfV:-N90uz-A0IGwLC9DkL7w:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sBlueGreenDeployTaskParameters.java#L71)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we do not need super here
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sCanaryDeployTaskParameters.java` line 81 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90s5so9cjrQS95ZOWy:-N90v-vI5KnTKkr_99t9:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sCanaryDeployTaskParameters.java#L81)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we do not need super here
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDeleteTaskParameters.java` line 63 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90s9H2Aa1_anXgNTOf:-N90v0wv-VcPA_twV-iA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDeleteTaskParameters.java#L63)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we do not need super here
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sRollingDeployTaskParameters.java` line 77 at r9](https://reviewable.io/reviews/harness/harness-core/35802#-N90sD8dDx3cNm_V20MV:-N90v1Xd8F5TfbHQLO5n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0ad3fc73ad0f7b34715f1693bc9246a061a7521/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sRollingDeployTaskParameters.java#L77)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we do not need super here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-09 10:00 UTC, yogesh-chauhan reviewed
> Reviewed 5 of 29 files at r2, 1 of 16 files at r5, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-09 13:15 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 29 files at r2, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-09 13:28 UTC, yogesh-chauhan reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: 1 file(s) to review. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-09 13:28 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35802)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-09 13:42 UTC, merged