[feat]: [CDS-40199]: support rollback for package deployments
harness/harness-core pull request #35948
Opened 2022-08-02 11:46 UTC by tmacari-harness

## Describe your changes
Support rollback for package deployments

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-02 12:09 UTC, tmacari-harness commented
trigger checkMessage

2022-08-03 06:45 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/webapp/handler/AzureWebAppRollbackRequestHandler.java
> +        .build();
here should be a property isBasicDeployment, but seems it's not rebased on latest develop then

2022-08-03 06:57 UTC, abosii-harness requested changes
> Reviewed 15 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/35948#-N8XNiV38FwofwPHlxL9:-N8XNiV38FwofwPHlxLA:b-bpvn32) ([raw file](https://github.com/harness/harness-core/blob/e84d47a9f88439bbefb6f90760bcd9ea05762b7c/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L112)):*
> ```Java
>       AzureArtifactConfig artifactConfig = azureWebAppStepHelper.getPrimaryArtifactConfig(ambiance, artifactOutcome);
>       AzureArtifactConfig previousArtifactConfig = null;
>       if (AzureArtifactType.PACKAGE.equals(artifactConfig.getArtifactType())) {
> ```

nit: you can check fir if artifact outcome is of package type so you wouldn't have to do conversion if is not required
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/35948#-N8XNUv60aCopEsk2wp5:-N8XNUv60aCopEsk2wp6:b-fyie90) ([raw file](https://github.com/harness/harness-core/blob/e84d47a9f88439bbefb6f90760bcd9ea05762b7c/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L155)):*
> ```Java
>       RollbackData rollbackData = rollbackDataList.get(0);
>       deploymentInfo = (AzureWebAppRollbackDeploymentInfo) rollbackData.getValue();
>       log.info(String.format(
> ```

use {} for formatting
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/35948#-N8XNXpu1mr7_M3EO3iu:-N8XNXpu1mr7_M3EO3iv:b-fyie90) ([raw file](https://github.com/harness/harness-core/blob/e84d47a9f88439bbefb6f90760bcd9ea05762b7c/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L161)):*
> ```Java
>         if (rollbackDataList.size() == 2) {
>           deploymentInfo = (AzureWebAppRollbackDeploymentInfo) rollbackDataList.get(1).getValue();
>           log.info(String.format(
> ```

use {} for formatting
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/35948#-N8XN21BCBExZBJ58Vfh:-N8XN21DEOK3qjUK5BVR:b-kh6415) ([raw file](https://github.com/harness/harness-core/blob/e84d47a9f88439bbefb6f90760bcd9ea05762b7c/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L131)):*
> ```Java
> 
>   public String getRollbackInfoKey(Ambiance ambiance, String appName, String deploymentSlot) {
>     OptionalOutcome serviceOutcome = outcomeService.resolveOptional(
> ```

let's add env as well
And re-review this part with key, accountId, org and projectId shouldn't be part of rollback deployment info and part of rollback data with proper index
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/beans/AzureWebAppRollbackDeploymentInfo.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/35948#-N8XSnXV7uqODZLJ_Eu6:-N8XSnXV7uqODZLJ_Eu7:ba63wiz) ([raw file](https://github.com/harness/harness-core/blob/e84d47a9f88439bbefb6f90760bcd9ea05762b7c/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/beans/AzureWebAppRollbackDeploymentInfo.java#L24)):*
> ```Java
> @JsonTypeName("AzureWebAppRollbackDeploymentInfo")
> public class AzureWebAppRollbackDeploymentInfo implements RollbackDeploymentInfo {
>   String pipelineExecutionId;
> ```

nit: missing modifier


<!-- Sent from Reviewable.io -->

2022-08-05 06:42 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 5 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35948)

2022-08-05 14:40 UTC, abosii-harness requested changes
> Reviewed 1 of 17 files at r4, 45 of 45 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/35948#-N8XNiV38FwofwPHlxL9:-N8iNqLF8mUPHzwsr8J5:b-k21ivv) ([raw file](https://github.com/harness/harness-core/blob/e84d47a9f88439bbefb6f90760bcd9ea05762b7c/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L112)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I wold leave it like that as we're gonna support multiple package type artifact sources, so doing multiple instanceof wont be an option.
</blockquote></details>

the logic is going to be common, inside  azureWebAppStepHelper.getPrimaryArtifactConfig(ambiance, artifactOutcome); it's already using isPackageArtifactType, so basically you're not avoiding anything here, but now you're creating a new object that may not be required
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 109 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iQ7J197iucaK-Kl0A:-N8iQ7J197iucaK-Kl0B:b54jcr4) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L109)):*
> ```Java
>       AzureWebAppInfraDelegateConfig infraDelegateConfig = azureWebAppStepHelper.getInfraDelegateConfig(
>           ambiance, azureAppServicePreDeploymentData.getAppName(), azureAppServicePreDeploymentData.getSlotName());
>       ArtifactOutcome artifactOutcome = azureWebAppStepHelper.getPrimaryArtifactOutcome(ambiance);
> ```

Shouldn't we actually rely on artifactConfig from execution details? What if artifact type changed during executions?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java` line 216 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iORqL4GMUkfuxBwyb:-N8iORqL4GMUkfuxBwyc:b9ij5jd) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java#L216)):*
> ```Java
>       Ambiance ambiance, AzureArtifactConfig azureArtifactConfig, AzureAppServicePreDeploymentData preDeploymentData) {
>     Criteria criteria = new Criteria();
>     criteria.and(StageExecutionInfoKeys.accountIdentifier)
> ```

this matching query shouldn't be here but part of stageExecutionInfoService
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java` line 228 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iOfolAlvMAR7jbAx2:-N8iOfolAlvMAR7jbAx3:b-lehb8v) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java#L228)):*
> ```Java
>     query.addCriteria(criteria);
>     Update update = new Update();
>     update.set(StageExecutionInfoKeys.deploymentIdentifier,
> ```

I saw some logic based on ExecutionKey, can we use that logic instead?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java` line 231 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iOpxs5eISoRbbvIYi:-N8iOpxs5eISoRbbvIYj:b-1d62wb) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java#L231)):*
> ```Java
>         azureWebAppStepHelper.getDeploymentIdentifier(
>             ambiance, preDeploymentData.getAppName(), preDeploymentData.getSlotName()));
>     update.set(String.format("%s.%s", StageExecutionInfoKeys.executionDetails,
> ```

ArtifactConfig should be set as part of InfrastructureStep, same way as SSH is doing. I understand that this probably is done to not save artifactConfig if artifact type is not package, but this logic doesn't optimize anything because you already storing stage execution info in infrastructure step. But now you're going to have a stage execution info with null artifact config that can lead to some NPE if not taken in consideration
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 142 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iQznD0Fh9LZ-r2qMx:-N8iQznD0Fh9LZ-r2qMy:bmdjfvh) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L142)):*
> ```Java
>       Ambiance ambiance, AzureWebAppSwapSlotStepParameters azureWebAppSwapSlotStepParameters) {
>     Criteria criteria = new Criteria();
>     criteria.and(StageExecutionInfo.StageExecutionInfoKeys.accountIdentifier)
> ```

Same as previous, this query part should be part of the service 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoService.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iR9sjDPCrGrZ_grRk:-N8iR9sjDPCrGrZ_grRl:b-srgt6m) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoService.java#L50)):*
> ```Java
>    * @param update update
>    */
>   void update(Query query, Update update);
> ```

This is a bad design, service shouldn't expose DAO 


<!-- Sent from Reviewable.io -->

2022-08-08 06:52 UTC, tmacari-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 13 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/35948#-N8XNiV38FwofwPHlxL9:-N8wCxXK3hUp4n5w6B0k:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e84d47a9f88439bbefb6f90760bcd9ea05762b7c/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L112)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

the logic is going to be common, inside  azureWebAppStepHelper.getPrimaryArtifactConfig(ambiance, artifactOutcome); it's already using isPackageArtifactType, so basically you're not avoiding anything here, but now you're creating a new object that may not be required
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 109 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iQ7J197iucaK-Kl0A:-N8wCzoNEcfiwjL6dKdQ:b-ra62y2) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L109)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't we actually rely on artifactConfig from execution details? What if artifact type changed during executions?
</blockquote></details>

Handling that as we dicsussed.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java` line 216 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iORqL4GMUkfuxBwyb:-N8wD4Gh99Fxnbtb514l:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java#L216)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this matching query shouldn't be here but part of stageExecutionInfoService
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java` line 228 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iOfolAlvMAR7jbAx2:-N8wD73C1p_0Ai_h4gdF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java#L228)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I saw some logic based on ExecutionKey, can we use that logic instead?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java` line 231 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iOpxs5eISoRbbvIYi:-N8wDCMn71_nr9KOV5ZY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java#L231)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

ArtifactConfig should be set as part of InfrastructureStep, same way as SSH is doing. I understand that this probably is done to not save artifactConfig if artifact type is not package, but this logic doesn't optimize anything because you already storing stage execution info in infrastructure step. But now you're going to have a stage execution info with null artifact config that can lead to some NPE if not taken in consideration
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 142 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iQznD0Fh9LZ-r2qMx:-N8wDGR7-McUxyj6jmtB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L142)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same as previous, this query part should be part of the service 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoService.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/35948#-N8iR9sjDPCrGrZ_grRk:-N8wDL0M1wWQ3cPLnXM1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d14a349873eb6c6ac32df5473f1f5897d5d9a31/125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoService.java#L50)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is a bad design, service shouldn't expose DAO 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 07:09 UTC, abosii-harness requested changes
> Reviewed 12 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 111 at r6](https://reviewable.io/reviews/harness/harness-core/35948#-N8wGpsS3TMgLEoGTp2q:-N8wGpsTBiQ6cV8X8Y9y:b6luok2) ([raw file](https://github.com/harness/harness-core/blob/7f319e520371ac8e9fc45bed466cc82a9f7576fc/120-ng-manager/config.yml#L111)):*
> ```YAML
>   oauthTokenRefreshIteratorConfig:
>     threadPoolSize: ${
> NG_TOKEN_REFRESH_THREAD_POOL_SIZE:
> ```

This file contain some changes that shouldn't be here
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoService.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/35948#-N8wH8ZA-Tkx1_Q3vrSz:-N8wH8ZA-Tkx1_Q3vrT-:bnmxij2) ([raw file](https://github.com/harness/harness-core/blob/7f319e520371ac8e9fc45bed466cc82a9f7576fc/125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoService.java#L44)):*
> ```Java
>    * Update stage execution status.
>    *
>    * @param scope the scope
> ```

nit: these params description is just duplicating name, or remove it or provide better description


<!-- Sent from Reviewable.io -->

2022-08-08 07:15 UTC, tmacari-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 111 at r6](https://reviewable.io/reviews/harness/harness-core/35948#-N8wGpsS3TMgLEoGTp2q:-N8wIhEm-9t7FBcmz5Ze:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f319e520371ac8e9fc45bed466cc82a9f7576fc/120-ng-manager/config.yml#L111)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This file contain some changes that shouldn't be here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-08 07:36 UTC, abosii-harness approved these changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-08 07:54 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java
> +      boolean isPackageTye = azureWebAppStepHelper.isPackageArtifactType(artifactOutcome);
minor typo here **isPackageTye**

2022-08-08 08:18 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java
> +  private void updateTargetSlot(Ambiance ambiance, String targetSlot) {
Does it make more sense to rename to: updateStageExecutionInfoKey instead of updateTargetSlot?

2022-08-08 08:30 UTC, tmacari-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java` line 139 at r11](https://reviewable.io/reviews/harness/harness-core/35948#-N8TNFwAitGfYhmdSS3v-r11-139:-N8wZv0y1-or609cbx2g:blom4ud) ([raw file](https://github.com/harness/harness-core/blob/31d8d1bcf0bf243ff6e519d24ac5002ce1c29aca/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSwapSlotStep.java#L139)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

Does it make more sense to rename smth to: updateStageExecutionInfoKey instead of updateTargetSlot? 
</blockquote></details>

we're updating only the target slot here


<!-- Sent from Reviewable.io -->

2022-08-08 08:33 UTC, vlica-harness reviewed
> Reviewed 1 of 17 files at r4, 35 of 45 files at r5, 10 of 13 files at r6, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-08 08:33 UTC, vlica-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-08 09:09 UTC, abosii-harness approved these changes
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-08 10:27 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 17 files at r4, 35 of 45 files at r5, 10 of 13 files at r6, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35948#-:-N8wzaaq5Hd-nVghnIwk:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-08 10:28 UTC, tmacari-harness commented
trigger codebasehash

2022-08-08 10:36 UTC, merged