feat: [CDS-40961]: Improve error handling for azure web app
harness/harness-core pull request #35954
Opened 2022-08-02 14:14 UTC by abosii-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/35954)

2022-08-03 13:15 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/exception/AzureAppServicesRuntimeExceptionHandler.java
> +  private static final String EXPLANATION_WEBAPP_NOT_FOUND =
nit: for WEBAPP_NOT_FOUND saw you didn't mention subscription, but for DEPLOYMENT_SLOT_NOT_FOUND is mentioned

2022-08-03 13:36 UTC, vlica-harness approved these changes
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35954)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-04 06:19 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35954)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-05 06:49 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 1 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35954)

2022-08-05 08:58 UTC, abosii-harness commented
trigger messagecheck

2022-08-05 09:01 UTC, vlica-harness approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35954)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-05 09:28 UTC, anilchowdhury-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 17 of 21 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35954#-:-N8hKL1s2nmzb9f_zHVT:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-05 10:35 UTC, vlica-harness submitted a review, later dismissed

2022-08-05 10:38 UTC, tmacari-harness requested changes
> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35954)* status: 1 file(s) to review. 1 change requests. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 2257 at r3](https://reviewable.io/reviews/harness/harness-core/35954#-N8h_BqrCA6uOA-SkSgS:-N8h_BqrCA6uOA-SkSgT:bpm97k0) ([raw file](https://github.com/harness/harness-core/blob/56edcb8020b5096b1f181f85c79efcc381064248/260-delegate/src/test/resources/kryo-registrations.txt#L2257)):*
> ```help
> 980030:io.harness.exception.InterruptedRuntimeException
> 980031:io.harness.exception.InvalidIdentifierRefException
> 980033:io.harness.exception.ngexception.AzureAppServiceTaskException
> ```

it is registered with 980032


<!-- Sent from Reviewable.io -->

2022-08-05 10:51 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35954)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-05 11:36 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35954#-:-N8hmkIj0LUlB4zk3s8o:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-05 11:37 UTC, abosii-harness commented
trigger codebasehash

2022-08-05 11:38 UTC, merged