feat: [CDS-41105]: NG - Create route for getting execution summary from `eventCorrelationId` and add `apiUrl` field to webhook response and
harness/harness-core pull request #35951
Opened 2022-08-02 13:21 UTC by vcalasansh

## Describe your changes

This PR consists of two parts:

1. Add a route `/pipelines/execution/v2/triggered/{eventCorrelationId}` to fetch a plan execution summary from {eventCorrelationId}, which is the ID generated at the moment of pipeline triggering via webhook.
- This is necessary because `planExecutionId` is generated after the trigger is activated (in an asynchronous way), so if the user wants to get the status of pipelines triggered by a custom webhook, he would first need to find the `planExecutionId` from the `eventCorrelationId` and then query `/pipelines/execution/v2/{planExecutionId}`.
2. Change the `data` field in custom webhook trigger response from `"data": <eventCorrelationId>` to `"data": {"eventCorrelationId": <eventCorrelationId>, "apiUrl": "<base_url>/pipelines/execution/v2/triggered/<eventCorrelationId>?acocuntIdentifier=<accountId>&orgIdentifier=<orgId>&projectIdentifier=<projectId>"}`. This is just to improve usability, so that after successfully triggering the webhook, the user receives the URL he should use for querying info about the triggered pipeline.

***POSSIBLE BREAKING CHANGE***
This PR changes the `data` field in the webhook trigger response from a string (which contained the value of eventCorrelationId) to an object with keys {"eventCorrelationId", "apiUrl"}. I think this makes more sense as a response to the trigger, but could break a user who is currently parsing the content of the `data` field as a string. Please let me know your thoughts on this, if you think it might break some user, I can move the new data to another field.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-02 17:02 UTC, sribalij commented on pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java
> +  ResponseDTO<NGProcessWebhookEventResponseDTO>
This may not be backward compatible. Since many have automation written around webhooks, this may break.

2022-08-02 17:08 UTC, sribalij reviewed
This may not be backward compatible. Since many have automation written around webhooks, this may break.

2022-08-02 18:01 UTC, vaibhav-si reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: 11 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 245 at r2](https://reviewable.io/reviews/harness/harness-core/35951#-N8Thxjt25r2FXqRm8Og-r2-245:-N8UhnK06MQCweZ8wl5q:bgwfgv4) ([raw file](https://github.com/harness/harness-core/blob/f1819f9eb0934b9cb13ac631ef79af311236b1dc/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L245)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

This may not be backward compatible. Since many have automation written around webhooks, this may break.
</blockquote></details>

We can't have breaking change IMO.

You can mark this deprecated and introduce a new one.


<!-- Sent from Reviewable.io -->

2022-08-02 18:27 UTC, sribalij commented
> 

Yeh, if we introduce a new one then we wouldn't but if we are changing the existing one then there is a possibility.

2022-08-04 16:42 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35951)

2022-08-05 17:08 UTC, sribalij commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java
> +    if (webhookProcessingDetails.isEventFound()) {
Better to return a 404 instead of returning null response when not found.

```
if (!webhookProcessingDetails.isEventFound()) {
      throw new InvalidRequestException(String.format("Trigger event history %s does not exist", eventId));
    }
```

2022-08-05 17:16 UTC, sribalij commented on pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java
> +  fetchWebhookExecutionSummaryDetails(@NotNull @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY)
Fine with this but wondering if eventId could be a path parameter instead of queryParam since eventId defines the resource? What do you think?

2022-08-05 17:19 UTC, sribalij commented on clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote/PipelineServiceClient.java
> +  Call<ResponseDTO<Object>> getExecutionDetailV2(
May be better to have a DTO instead of an object

2022-08-05 17:20 UTC, sribalij reviewed
Added a few comments.

2022-08-05 21:53 UTC, vcalasansh commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java
> +    if (webhookProcessingDetails.isEventFound()) {
Updated the method. Thank you!

2022-08-05 21:54 UTC, vcalasansh commented on pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java
> +  fetchWebhookExecutionSummaryDetails(@NotNull @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY)
As we discussed, we can leave it like since it keeps consistency with method `fetchWebhookDetails` in the same class. Thank you!

2022-08-05 21:59 UTC, vcalasansh commented on clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote/PipelineServiceClient.java
> +  Call<ResponseDTO<Object>> getExecutionDetailV2(
As we discussed, this would require importing `PipelineExecutionDetailDTO` here, which is in a package that depends on `ngtriggers` package. In a future PR, we will propose moving this DTO and is inner DTOs to another package. For now, we will leave it like this.

2022-08-05 22:25 UTC, vcalasansh commented
trigger codeformat

2022-08-05 22:25 UTC, sribalij approved these changes
> Reviewed 6 of 10 files at r3, 7 of 9 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-05 23:48 UTC, vaibhav-si requested changes
> Reviewed 3 of 9 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote/PipelineServiceClient.java` line 93 at r4](https://reviewable.io/reviews/harness/harness-core/35951#-N8eHjJ_KXu5nmQf-AfW-r4-93:-N8jaCQB0yJzsz4AFqQa:b-bro159) ([raw file](https://github.com/harness/harness-core/blob/cf009d0a9578a3401fd24b834ddd13429aad2a34/clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote/PipelineServiceClient.java#L93)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

As we discussed, this would require importing `PipelineExecutionDetailDTO` here, which is in a package that depends on `ngtriggers` package. In a future PR, we will propose moving this DTO and its inner DTOs to another package. For now, we will leave it like this.
</blockquote></details>

Agree, we need to move this PipelineExecutionDetailDTO in pms-contracts, so pms-client and pipeline-service module can use it.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 274 at r4](https://reviewable.io/reviews/harness/harness-core/35951#-N8kPEON1gCBHERHFkqd:-N8kPEON1gCBHERHFkqe:bbxf84s) ([raw file](https://github.com/harness/harness-core/blob/cf009d0a9578a3401fd24b834ddd13429aad2a34/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L274)):*
> ```Java
>             responseCode = "default", description = "Returns webhook event processing details for input eventId.")
>       })
>   @Path("/triggerExecutionSummaryProcessingDetails")
> ```

simplify this path - maybe "executionDetails"
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 279 at r4](https://reviewable.io/reviews/harness/harness-core/35951#-N8Thxjt25r2FXqRm8Og-r4-279:-N8jaRaR8RTy7GvZ-7ao:b4y0508) ([raw file](https://github.com/harness/harness-core/blob/cf009d0a9578a3401fd24b834ddd13429aad2a34/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L279)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

As we discussed, we can leave it like since it keeps consistency with method `fetchWebhookDetails` in the same class. Thank you!
</blockquote></details>

I agree with Sridhar, EventId here defines the resource and should rather be a path param. I am fine skipping the consistency as we would anyways remove that method at some point.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java` line 164 at r6](https://reviewable.io/reviews/harness/harness-core/35951#-N8kOxC222u6Sr-HMc21:-N8kOxC222u6Sr-HMc22:b-8i97yz) ([raw file](https://github.com/harness/harness-core/blob/bd3acbc49c0d42c0f89136fc7bf8811256d39c71/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java#L164)):*
> ```Java
>           accountIdentifier, webhookProcessingDetails.getOrgIdentifier(),
>           webhookProcessingDetails.getProjectIdentifier());
>     } catch (InvalidRequestException ignored) {
> ```

at least log the exception


<!-- Sent from Reviewable.io -->

2022-08-06 00:41 UTC, sribalij approved these changes
> Reviewed 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-06 00:42 UTC, vaibhav-si reviewed
> Reviewed 6 of 10 files at r3, 2 of 9 files at r4, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-06 00:43 UTC, vcalasansh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: 1 change requests. 6. unresolved discussions. 

___
*[`clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote/PipelineServiceClient.java` line 93 at r4](https://reviewable.io/reviews/harness/harness-core/35951#-N8eHjJ_KXu5nmQf-AfW-r4-93:-N8kah3m12u66esEtv1R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf009d0a9578a3401fd24b834ddd13429aad2a34/clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote/PipelineServiceClient.java#L93)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Agree, we need to move this PipelineExecutionDetailDTO in pms-contracts, so pms-client and pipeline-service module can use it.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 245 at r2](https://reviewable.io/reviews/harness/harness-core/35951#-N8Thxjt25r2FXqRm8Og-r2-245:-N8kahqp0GwMJOx2imOy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1819f9eb0934b9cb13ac631ef79af311236b1dc/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L245)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

We can't have breaking change IMO.

You can mark this deprecated and introduce a new one.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 274 at r4](https://reviewable.io/reviews/harness/harness-core/35951#-N8kPEON1gCBHERHFkqd:-N8kaiIvB7_g_vtYhjEn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf009d0a9578a3401fd24b834ddd13429aad2a34/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L274)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

simplify this path - maybe "executionDetails"
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 279 at r4](https://reviewable.io/reviews/harness/harness-core/35951#-N8Thxjt25r2FXqRm8Og-r4-279:-N8kaijN1sKFL7FxPQhx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf009d0a9578a3401fd24b834ddd13429aad2a34/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L279)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

I agree with Sridhar, EventId here defines the resource and should rather be a path param. I am fine skipping the consistency as we would anyways remove that method at some point.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java` line 164 at r6](https://reviewable.io/reviews/harness/harness-core/35951#-N8kOxC222u6Sr-HMc21:-N8kajMr6tANzsUTqigv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd3acbc49c0d42c0f89136fc7bf8811256d39c71/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java#L164)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

at least log the exception
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-06 00:44 UTC, vaibhav-si approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-06 00:52 UTC, vcalasansh reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951#-:-N8kctXj1TJrisPdvWgx:bnfp4nl)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-06 00:55 UTC, sribalij approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-06 00:56 UTC, sribalij approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-06 01:15 UTC, vaibhav-si approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35951)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-06 01:16 UTC, merged