[FIX]: [CDS-41187] Fix getDetailsV2 endpoint
harness/harness-core pull request #35950
Opened 2022-08-02 13:02 UTC by nassergonzalez

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-02 13:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=35950) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=35950) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=35950) it.</sub>

2022-08-02 14:13 UTC, tmacari-harness requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35950#-:-N8Tt5PK0T065tryn7zu:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/35950#-N8TtSgX-LTnSE58PQT-:-N8TtSgX-LTnSE58PQT0:b-ihq8nz) ([raw file](https://github.com/harness/harness-core/blob/31cbf40131088dfb44501cef477bf94faa8d91a5/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L121)):*
> ```Java
>       // artifactPath is the artifactDirectory for Artifactory Generic
>       // artifactPath is the artifactPath for Artifactory Docker
>       if (artifactoryRegistryArtifactConfig.getRepositoryFormat().fetchFinalValue().equals("docker")) {
> ```

we can check isEmpty(artifactPath) only once.



_Suggestion:_
```Java
    if (isEmpty(artifactPath)) {
      if (artifactoryRegistryArtifactConfig.getRepositoryFormat().fetchFinalValue().equals("docker")) {
          artifactPath = (String) artifactoryRegistryArtifactConfig.getArtifactPath().fetchFinalValue();
      } else {
          artifactPath = (String) artifactoryRegistryArtifactConfig.getArtifactDirectory().fetchFinalValue();
      }
    }
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/35950#-N8Tt9tR06amVqGBRA17:-N8Tt9tR06amVqGBRA18:bmop6t4) ([raw file](https://github.com/harness/harness-core/blob/31cbf40131088dfb44501cef477bf94faa8d91a5/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L224)):*
> ```Java
>       @NotNull @QueryParam(NGCommonEntityConstants.ORG_KEY) String orgIdentifier,
>       @NotNull @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @QueryParam("fqnPath") String fqnPath, @QueryParam(NGCommonEntityConstants.SERVICE_KEY) String serviceRef) {
> ```

do we need the change for this endpoint?


<!-- Sent from Reviewable.io -->

2022-08-02 14:27 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35950)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/35950#-N8TtSgX-LTnSE58PQT-:-N8Twg6M72oZ8AvAqxX1:b-hikhx) ([raw file](https://github.com/harness/harness-core/blob/31cbf40131088dfb44501cef477bf94faa8d91a5/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L121)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we can check isEmpty(artifactPath) only once.
</blockquote></details>

I had that done first but I though that it was cleaner this way as it reads more natural. I am happy to change it if you want to
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/35950#-N8Tt9tR06amVqGBRA17:-N8TwuKP0fsV1khK7jg-:b-s7k09m) ([raw file](https://github.com/harness/harness-core/blob/31cbf40131088dfb44501cef477bf94faa8d91a5/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/artifactory/ArtifactoryArtifactResource.java#L224)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

do we need the change for this endpoint?
</blockquote></details>

That one is called from the service and in the service all the parameters are sent, if they are not sent they will be sent to the v2 version so I don't think that this endpoint needs to be changed


<!-- Sent from Reviewable.io -->

2022-08-03 09:08 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35950)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-03 09:17 UTC, vlica-harness approved these changes

2022-08-03 10:24 UTC, merged