feat: [CDS-40476]: SNow create and update output variables added in s…
harness/harness-core pull request #36084
Opened 2022-08-05 09:11 UTC by naman-goenka

…uggestion

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-05 11:25 UTC, shivamnegi94 submitted a review, later dismissed

2022-08-05 12:23 UTC, naman-goenka commented
trigger messagecheck

2022-08-08 13:15 UTC, hingerabhinav requested changes

2022-08-08 13:15 UTC, hingerabhinav commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowCreateStepVariableCreator.java
> +        ServiceNowTicketOutcome.builder().ticketNumber("").ticketUrl("").fields(new HashMap<>()).build();
nit: there's no need to provide dummy values since the logic uses field names. You can just do ServiceNowTicketOutcome.builder().build().

2022-08-08 13:15 UTC, hingerabhinav commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/ServiceNowCreateStepVariableCreatorTest.java
> +  public void shouldCreateExtraProperties() {
You can use existing tests to get output properties and assert on them. 
Eg. variablesForParentNodeV2.getYamlExtraProperties()
                                               .get("STEP_UUID") // uuid for step node
                                               .getOutputPropertiesList()

2022-08-08 17:37 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowUpdateStepVariableCreator.java
> +        ServiceNowTicketOutcome.builder().ticketNumber("").ticketUrl("").fields(new HashMap<>()).build();
yeah done

2022-08-08 18:10 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/ServiceNowCreateStepVariableCreatorTest.java
> +  public void shouldCreateExtraProperties() {
Done in both test files

2022-08-10 03:22 UTC, hingerabhinav approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36084#-:-N94lSfnEBAN6YNAIOAn:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-12 06:18 UTC, hingerabhinav approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36084)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-16 06:54 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36084)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-08-16 11:41 UTC, naman-goenka commented
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2

2022-08-16 12:14 UTC, puthrayaharness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36084)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-16 12:24 UTC, merged