[CDS-41317]: Add AzureCreateStep
harness/harness-core pull request #36101
Opened 2022-08-05 12:52 UTC by nassergonzalez

## Describe your changes

Add AzureCreateSteps with business logic.

There are a few things missing here that would be covered in 2 other tickets:
- Handle the responses: https://harness.atlassian.net/browse/CDS-41438
- Harness store for inline: https://harness.atlassian.net/browse/CDS-41439

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-05 12:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36101) it.</sub>

2022-08-05 12:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36101) it.</sub>

2022-08-05 12:55 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 12 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 12 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36101)

2022-08-08 06:34 UTC, abosii-harness requested changes
> Reviewed 4 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 43 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/AzureCreateResourceStepPlanCreator.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w4lPV3ZKcqyERL-mW:-N8w4lPV3ZKcqyERL-mX:b-unakov) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/AzureCreateResourceStepPlanCreator.java#L18)):*
> ```Java
> import java.util.Set;
> 
> public class AzureCreateResourceStepPlanCreator extends CDPMSStepPlanCreatorV2<AzureCreateStepNode> {
> ```

nit: let's add owner
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommandUnit.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w52mB2lLRNtcjFsbI:-N8w52mB2lLRNtcjFsbJ:b-jwy83u) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommandUnit.java#L10)):*
> ```Java
> package io.harness.cdng.provision.azure;
> 
> public enum AzureCommandUnit { Create }
> ```

let's add owner
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w62w3EDlCLF9RGTXA:-N8w62w3EDlCLF9RGTXB:b-fgphtu) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L80)):*
> ```Java
>   @Inject private StepHelper stepHelper;
> 
>   public GitFetchFilesConfig getTemplateGitFetchFileConfig(
> ```

Honestly this helper method doesn't make sense.. if this method is dependent on the specific step type, then it should be part of the specific Step class
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w77Y15czeWUknZAs0:-N8w77Y15czeWUknZAs1:b-550u4s) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L148)):*
> ```Java
>   }
> 
>   public TaskChainResponse getExceptionTaskChainResponse(
> ```

We shouldn't handle exception and transform it to TaskChainResponse, it should be let be handled by error framework
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStep.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w5nC_3VaslKcn2i1x:-N8w5nC_3VaslKcn2i1y:btkypa7) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStep.java#L54)):*
> ```Java
> import java.util.List;
> 
> public class AzureCreateStep extends TaskChainExecutableWithRollbackAndRbac implements AzureCreateStepExecutor {
> ```

I'm confused, didn't we decide to split ARM and BluePrint? Why this step name is AzureCreateResource and doesn't have to do anything related to ARM or BluePrint?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepExecutor.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w7clY3e0IulKfdiE3:-N8w7clY3e0IulKfdiE4:b-xih6q1) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepExecutor.java#L20)):*
> ```Java
> 
> @OwnedBy(CDP)
> public interface AzureCreateStepExecutor {
> ```

If there are going to have 2 different steps, I think using this kind of logic is confusing and hard to follow. Are common methods can be made as part of utility class, anything custom and flow control should be part of step 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w7zy9AQKI0OG9ysEq:-N8w7zy9AQKI0OG9ysEr:b-yjjh4d) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java#L63)):*
> ```Java
>   @Inject private AzureCommonHelper azureCommonHelper;
> 
>   public TaskChainResponse startChainLink(
> ```

This should be part of step logic
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java` line 129 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w8AKD7hSY9u-C1L5T:-N8w8AKD7hSY9u-C1L5U:bwyrr7e) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java#L129)):*
> ```Java
>         .parametersBody(azureCreatePassThroughData.getParametersBody())
>         .timeoutInMs(StepUtils.getTimeoutMillis(stepElementParameters.getTimeout(), DEFAULT_TIMEOUT));
>     if (stepConfigurationParameters.getScope().getSpec() instanceof AzureResourceGroupSpec) {
> ```

this should be split in a new method, and the logic should be be based on the spec instanceof but on the type, so it can be a switch statement
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w8u4vC8DUozW3-fvV:-N8w8u4vC8DUozW3-fvW:bnzq216) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L188)):*
> ```Java
>     kryo.register(MergePRStepParams.class, 12604);
>     kryo.register(MergePRStepInfo.class, 12605);
>     kryo.register(AzureCreateStepInfo.class, 12606);
> ```

Duplicate Id of RollbackDeploymentInfo, always add registration at the end and use next to last id
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w94Ps2YET0ZKHtgTu:-N8w94Ps2YET0ZKHtgTv:bo0nqw0) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java#L37)):*
> ```Java
>   String TERRAFORM_ROLLBACK = "TerraformRollback";
> 
>   String AZURE_CREATE_RESOURCE = "AzureCreateResource";
> ```

Shouldn't it be ARM or BluePrint?
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 387 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w9Ac30D7Pq_DbPM1U:-N8w9Ac30D7Pq_DbPM1V:bnc8qay) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L387)):*
> ```Java
>   USE_K8S_API_FOR_STEADY_STATE_CHECK,
>   WINRM_ASG_ROLLBACK("Used for Collect remaining instances rollback step", HarnessTeam.CDP),
>   AZURE_ARM_NG,
> ```

Please add description and harness team


<!-- Sent from Reviewable.io -->

2022-08-08 14:47 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 47 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommandUnit.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w52mB2lLRNtcjFsbI:-N8x9zCiCyciSWc4OsEk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommandUnit.java#L10)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's add owner
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w62w3EDlCLF9RGTXA:-N8xA-cX21ErNzO0xCai:b-1od7tj) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L80)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Honestly this helper method doesn't make sense.. if this method is dependent on the specific step type, then it should be part of the specific Step class
</blockquote></details>

This is my fault sorry. So as I mentioned, the code was rebased and I have to split the code again so this is why this file looks a bit strange. Basically there will be 3 files once all the PR are merged:
* This file which contains the logic that is going to be common to all the steps
* ARM helper to help with the ARM steps
* BP helper, to help with the BP steps
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w77Y15czeWUknZAs0:-N8xD6Zn389-hK-ClnIe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L148)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We shouldn't handle exception and transform it to TaskChainResponse, it should be let be handled by error framework
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStep.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w5nC_3VaslKcn2i1x:-N8xDBc61tzk-KDBtsZh:bic789g) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStep.java#L54)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm confused, didn't we decide to split ARM and BluePrint? Why this step name is AzureCreateResource and doesn't have to do anything related to ARM or BluePrint?
</blockquote></details>

I will rename the steps to be sure that is clearer that this is an ARM step
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepExecutor.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w7clY3e0IulKfdiE3:-N8xg4VQ4mc5bN-oLiHM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepExecutor.java#L20)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

If there are going to have 2 different steps, I think using this kind of logic is confusing and hard to follow. Are common methods can be made as part of utility class, anything custom and flow control should be part of step 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w7zy9AQKI0OG9ysEq:-N8xg57F5VuehC_xVKDc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java#L63)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be part of step logic
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java` line 129 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w8AKD7hSY9u-C1L5T:-N8xg5dX968RMXDfO3ir:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateStepHelper.java#L129)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this should be split in a new method, and the logic should be be based on the spec instanceof but on the type, so it can be a switch statement
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w8u4vC8DUozW3-fvV:-N8xgIbLDTOdDRfLF9OH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L188)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Duplicate Id of RollbackDeploymentInfo, always add registration at the end and use next to last id
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w94Ps2YET0ZKHtgTu:-N8xidMaAKH8FBojXVW-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java#L37)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't it be ARM or BluePrint?
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 387 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w9Ac30D7Pq_DbPM1U:-N8xj9m92JDWGcQXmPvU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L387)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please add description and harness team
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-09 14:44 UTC, abosii-harness requested changes
> Reviewed 9 of 47 files at r1, 26 of 36 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91xgaJ0pcrCkarPloB:-N91xgaJ0pcrCkarPloC:blg19st) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L139)):*
> ```Java
>   // Azure ARM/BP
>   @JsonProperty(StepSpecTypeConstants.AZURE_CREATE_ARM_RESOURCE)
>   AZ_CREATE_RESOURCE("Azure ARM/BP", Arrays.asList(ServiceDefinitionType.values()),
> ```

Why this is mentioning BP? Should be 2 different Steps? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w62w3EDlCLF9RGTXA:-N91xuYy5NkN49uSa6oD:bwafra0) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L80)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

This is my fault sorry. So as I mentioned, the code was rebased and I have to split the code again so this is why this file looks a bit strange. Basically there will be 3 files once all the PR are merged:
* This file which contains the logic that is going to be common to all the steps
* ARM helper to help with the ARM steps
* BP helper, to help with the BP steps
</blockquote></details>

I would suggest to not have a ARM/BP helper. All logic specific to ARM can be added as part of ARM Step, same for blue print. "CommonHelper" can be added to reduce code duplication between these 2 steps. The problem with this method is that basically there is no common logic here, all branches can be put in step
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 86 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91z8BXE9qBwUMIcs56:-N91z7HlDjdZGkJD5p0J:b-4134dp) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L86)):*
> ```Java
>     if (deploymentType.equals(AzureDeploymentTypes.ARM)) {
>       return GitFetchFilesConfig.builder()
>           .manifestType("Azure Template")
> ```

nit: let's make this consts
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91ykUd9zryP8wmPtMk:-N91ykUd9zryP8wmPtMl:bht7j9d) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L153)):*
> ```Java
>     if (isNotEmpty(azureConnectorDTO.getDecryptableEntities())) {
>       return secretManagerClientService.getEncryptionDetails(
>           AmbianceUtils.getNgAccess(ambiance), azureConnectorDTO.getDecryptableEntities().get(0));
> ```

What if there are more than one decryptable entity?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 212 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91z4MQ7MOQOeb6UlzV:-N91z4MQ7MOQOeb6UlzW:b-4134dp) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L212)):*
> ```Java
>       return new ArrayList<>(Collections.singletonList(
>           GitFetchFilesConfig.builder()
>               .manifestType("Azure Parameters")
> ```

nit: let's make this consts
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N921Dj42A7QUxxKs5MX:-N921Dj42A7QUxxKs5MY:b18itbf) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java#L15)):*
> ```Java
> 
> @OwnedBy(CDP)
> public interface AzureDeploymentTypes {
> ```

it may be better to have it as enum
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureScopeTypesNames.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N921Nsf4mVeDjZvSLZw:-N921Nsf4mVeDjZvSLZx:b-o26jll) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureScopeTypesNames.java#L16)):*
> ```Java
> @OwnedBy(CDP)
> public interface AzureScopeTypesNames {
>   String RESOURCE_GROUP = "RESOURCE_GROUP";
> ```

These values should follow title case style
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskType.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N922ajnDsRdpXr5S_RL:-N922ajo-9EyxTdHN44e:b-oyz8f5) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskType.java#L10)):*
> ```Java
> package io.harness.delegate.task.azure.arm;
> 
> public enum AzureARMTaskType {
> ```

nit: missing owner
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N922gM_8VTlwToffSPg:-N922gM_8VTlwToffSPh:b-wwz38x) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L384)):*
> ```Java
>   DLITE_CI_VM_CLEANUP_TASK(TaskGroup.CI, DliteVmCleanupTaskParams.class, VmTaskExecutionResponse.class, true),
>   NG_LDAP_GROUPS_SYNC(TaskGroup.LDAP),
>   AZURE_NG_ARM_BLUEPRINT(TaskGroup.AZURE_NG_ARM_BLUEPRINT, "Azure ARM/Blueprint");
> ```

Aren't we using 2 different tasks for ARM and Blueprint? 
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N922qLU9RbDHrP-ymaM:-N922qLU9RbDHrP-ymaN:b-m7n1a1) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L384)):*
> ```Java
>   WINRM_ASG_ROLLBACK("Used for Collect remaining instances rollback step", HarnessTeam.CDP),
>   NEW_LEFT_NAVBAR_SETTINGS("Used for new left navbar configuration", HarnessTeam.PL),
>   AZURE_ARM_NG("Used to allow customers to access ARM/BP capabilities", HarnessTeam.CDP),
> ```

Let's add this at the end of enum, and FF name should be AZURE_ARM_BP_NG
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N920FnQ5YZdWKmKXIMI:-N920FnQ5YZdWKmKXIMJ:b-ec1i5c) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java#L52)):*
> ```Java
>   }
> 
>   public AzureCreateARMTemplateFile getTemplateSpecs() {
> ```

This method doesn't make sense, you can use getTemplate. Or if it's required for any reasons annotate it with JsonIgnore, otherwise is going to be part of schema
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfigurationParameters.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N920a1i4jIOkiHuGt9A:-N920 [...]

2022-08-10 08:22 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 17 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91xgaJ0pcrCkarPloB:-N929gLq3nqEHkQ2XoMo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L139)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why this is mentioning BP? Should be 2 different Steps? 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w62w3EDlCLF9RGTXA:-N929jiJDpIWkgNObJle:b-hgl382) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L80)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I would suggest to not have a ARM/BP helper. All logic specific to ARM can be added as part of ARM Step, same for blue print. "CommonHelper" can be added to reduce code duplication between these 2 steps. The problem with this method is that basically there is no common logic here, all branches can be put in step
</blockquote></details>

Yes, that is what was done in the PR, the ARM helper is removed and all the logic there is in the ARM step. The CommonHelper only contains functions that are specific for both steps
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91ykUd9zryP8wmPtMk:-N92ANL0BxHLpMlKrKvU:b-j0yfnn) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L153)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What if there are more than one decryptable entity?
</blockquote></details>

Could that be a feasible scenario that we need to handle? the K8sEntityHelper.java and AzureWebAppInstanceSyncPerpetualTaskExecutor, both use the same logic than here where they extract only one element from the azureConnectorDTO. What other elements could we have here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N921Dj42A7QUxxKs5MX:-N92F2u-4KtjwbyphEd5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java#L15)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

it may be better to have it as enum
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N922gM_8VTlwToffSPg:-N92GYU593ffy69oprei:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L384)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Aren't we using 2 different tasks for ARM and Blueprint? 
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N922qLU9RbDHrP-ymaM:-N92GnPD5BPH_DA-VrQi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L384)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's add this at the end of enum, and FF name should be AZURE_ARM_BP_NG
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N920FnQ5YZdWKmKXIMI:-N92BNek9XY08MBPFXvW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java#L52)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This method doesn't make sense, you can use getTemplate. Or if it's required for any reasons annotate it with JsonIgnore, otherwise is going to be part of schema
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfigurationParameters.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N920a1i4jIOkiHuGt9A:-N92C0M59gJm5Pa6A4sn:b45v9q7) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfigurationParameters.java#L22)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm confused that actually configuration you're using. Class AzureCreateARMStepConfiguration looks to have similar configuration
</blockquote></details>

Is the problem that AzureCreateARMStepConfigurationParameters is really similar to AzureCreateARMStepConfiguration.java and why is that? 

From what I gathered when I started to do steps starting with the Terraform steps and with the same implementation in the cloudformation steps, I thought that the AzureCreateARMStepConfiguration is the class that is created from the yaml file. Then, through the `toStepParameters` it will be transformed into a POJO class which I thought was the AzureCreateARMStepConfigurationParameters which is the class that is used in the steps later on. We did that in the cloudformation steps and it is also done in the Terraform steps
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java` line 78 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N920oQJ9IWdxEI8e-jZ:-N92DNSfBMFDdmEVVjhs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java#L78)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add a todo to not forget to remove it
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/beans/AzureCreateARMPassThroughData.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N921VsM00LkEYjFUcQw:-N92G57_9GEfg6kbueGX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/beans/AzureCreateARMPassThroughData.java#L25)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

missing acces modifier or default private annotation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-10 08:25 UTC, tmacari-harness requested changes
> Reviewed 5 of 36 files at r2, 1 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 16 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 129 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92VSa9BKFEbmEVhTpg:-N92VSa9BKFEbmEVhTph:b-bre81k) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L129)):*
> ```Java
> 
>   private static final List<String> AZURE_RESOURCE_CATEGORY =
>       Arrays.asList("Kubernetes", "Provisioner", "Azure", "Helm");
> ```

please add AzureWebApp to that list.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 130 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92Va7EEHfAUY-8YZpt:-N92Va7EEHfAUY-8YZpu:b-jm8gfh) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L130)):*
> ```Java
>   private static final List<String> AZURE_RESOURCE_CATEGORY =
>       Arrays.asList("Kubernetes", "Provisioner", "Azure", "Helm");
>   private static final String AZURE_RESOURCE_STEP_METADATA = "Azure";
> ```

maybe something more specific: AzureProvisioner
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/ProvisionerType.java` line 39 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92XXKM0bw1XRyXfnTa:-N92XXKM0bw1XRyXfnTb:byd10cz) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/ProvisionerType.java#L39)):*
> ```Java
>   private static final List<NGStepType> supportedSteps =
>       Arrays.asList(TERRAFORM_APPLY, TERRAFORM_PLAN, TERRAFORM_DESTROY, TERRAFORM_ROLLBACK, CF_CREATE_STACK,
>           CF_DELETE_STACK, CF_ROLLBACK_STACK, AZ_CREATE_ARM_RESOURCE);
> ```

let's call it AZURE_CREATE_ARM_RESOURCE
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 139 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92Y0cG1zaKEkLJUwnH:-N92Y0cG1zaKEkLJUwnI:bl7ji5r) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L139)):*
> ```Java
>   // Azure ARM/BP
>   @JsonProperty(StepSpecTypeConstants.AZURE_CREATE_ARM_RESOURCE)
>   AZ_CREATE_ARM_RESOURCE("Azure ARM", Arrays.asList(ServiceDefinitionType.values()),
> ```

Let's not use abbreviation AZ.
Also not sure where that string is gonna show up "Azure ARM" but it it should be more specific for Azure Create ARM Resource step.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 135 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92aC8y2oxwFX5tVSq6:-N92aC9-7dJKieBM3zBJ:b-1ztvou) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L135)):*
> ```Java
>     List<String> paths = new ArrayList<>();
> 
>     if (Objects.equals(type, AzureDeploymentTypes.BLUEPRINT)) {
> ```

we can pass paths as parameter, and not to have if ARM on Blueprint.
Also if I remember correctly for parameters we can have only one file. If that's the case, even YAML accepts a list we should take only the first one.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92faJO19cyMHbSY598:-N92faJO19cyMHbSY599:b-ual8hz) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java#L42)):*
> ```Java
>   @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> resourceGroup;
> 
>   @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> mode;
> ```

if mode can have only two valid values lets put allowableValues = "Incremental, Complete" in @ApiModelProperty proeprties.


<!-- Sent from Reviewable.io -->

2022-08-10 10:19 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 16 file(s) to review. 2 change requests. 17. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 129 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92VSa9BKFEbmEVhTpg:-N965tnX379Dd2pDu6Xq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L129)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add AzureWebApp to that list.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 130 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92Va7EEHfAUY-8YZpt:-N965xHV0OrAp3LkOqC6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L130)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

maybe something more specific: AzureProvisioner
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/ProvisionerType.java` line 39 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92XXKM0bw1XRyXfnTa:-N96692M3iyUppntOe9p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/infra/beans/ProvisionerType.java#L39)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's call it AZURE_CREATE_ARM_RESOURCE
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 139 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92Y0cG1zaKEkLJUwnH:-N967QcJ5ULE0XTYvEPJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L139)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's not use abbreviation AZ.
Also not sure where that string is gonna show up "Azure ARM" but it it should be more specific for Azure Create ARM Resource step.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 135 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92aC8y2oxwFX5tVSq6:-N96EGF--D_rIlOgSqQL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L135)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we can pass paths as parameter, and not to have if ARM on Blueprint.
Also if I remember correctly for parameters we can have only one file. If that's the case, even YAML accepts a list we should take only the first one.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/36101#-N92faJO19cyMHbSY598:-N96Fl1j0PLQ4Fu9WqXD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39f7b36cee84249121a220642ef1c931878b1769/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java#L42)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

if mode can have only two valid values lets put allowableValues = "Incremental, Complete" in @ApiModelProperty proeprties.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureScopeTypesNames.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N921Nsf4mVeDjZvSLZw:-N96FvCJCcCO9hL0D1_Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureScopeTypesNames.java#L16)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

These values should follow title case style
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-10 15:31 UTC, tmacari-harness requested changes
> Reviewed 6 of 47 files at r1, 13 of 36 files at r2, 6 of 13 files at r3, 8 of 15 files at r4, 5 of 6 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 2 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java` line 78 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N978sNL1EFgIsHSopLG:-N978sNL1EFgIsHSopLH:b-3fpvhb) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java#L78)):*
> ```Java
> 
> @OwnedBy(CDP)
> public class AzureCreateARMStep extends TaskChainExecutableWithRollbackAndRbac {
> ```

AzureCreateArmResourceStep would be more correct
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java` line 250 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97LtlYDyfWTfVgJl7F:-N97LtlYDyfWTfVgJl7G:bbt353i) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java#L250)):*
> ```Java
>         .timeoutInMs(StepUtils.getTimeoutMillis(stepElementParameters.getTimeout(), DEFAULT_TIMEOUT));
> 
>     builder = setScopeTypeValues(builder, stepConfigurationParameters);
> ```

SonarLint: Remove this useless assignment; "builder" already holds the assigned value along all execution paths. 
___
*[`943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java` line 79 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97NFS32N59yI99AfRS:-N97NFS32N59yI99AfRT:b-9isxx1) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java#L79)):*
> ```Java
>   AZURE_WEBAPP_ROLLBACK,
>   JENKINS_BUILD,
>   AZURE_CREATE_ARM_RESOURCE,
> ```

configuration for ti should be added  here 925-enforcement-service/src/main/resources/features/cd_features.yml
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureTaskNGParameters.java` line 28 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97LCsn7TC_HVDjQdCq:-N97LCsn7TC_HVDjQdCr:b-qfupwx) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureTaskNGParameters.java#L28)):*
> ```Java
> @NoArgsConstructor
> @AllArgsConstructor
> public class AzureTaskNGParameters
> ```

I see it has AzureARMTaskType which makes me thinking is some thing specific to arm. Let's give it a name specific to AMR also.
Also consider making it an abstract class if we won't create instances of it.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java` line 69 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97FN1Q5oXyZETtuBkI:-N97FN1Q5oXyZETtuBkJ:brxvlcp) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java#L69)):*
> ```Java
> 
>   // Check that the number of parameters files is 1.
>   private boolean isNumberOfParametersValid() {
> ```

where do we use that method?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java` line 72 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97FPvc0LrNWNawZ_cX:-N97EubP8fXGd_0-qIe-:b-y3v8bf) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java#L72)):*
> ```Java
>     if (ManifestStoreType.isInGitSubset(parameters.getStore().getSpec().getKind())) {
>       GitStoreConfig gitStoreConfig = (GitStoreConfig) parameters.getStore().getSpec();
>       return gitStoreConfig.getPaths().getValue().size() == 1;
> ```

I think gitStoreConfig.getPaths().getValue() can return null
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java` line 78 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N920oQJ9IWdxEI8e-jZ:-N97G1-9Au9WgMu_ozTp:b-55q503) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java#L78)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now we know that new wont have a list of parameters
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java` line 96 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97GHja23dzHcRhZE1N:-N97GHja23dzHcRhZE1O:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java#L96)):*
> ```Java
>     return OrchestrationFacilitatorType.TASK_CHAIN;
>   }
>   @Override
> ```

please add empty line
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java` line 32 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97GgMg3QlBaO_GwWbk:-N97GgMg3QlBaO_GwWbl:b3twi5f) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java#L32)):*
> ```Java
> 
> public class AzureCreateARMStepParameters extends AzureCreateARMStepBaseStepInfo implements SpecParameters {
>   @NonNull AzureCreateARMStepConfigurationParameters configuration;
> ```

maybe configurationParameters
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java` line 36 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97Gmy19G-ljTTQrXS9:-N97Gmy19G-ljTTQrXSA:b-prpe79) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java#L36)):*
> ```Java
>   public AzureCreateARMStepParameters(ParameterField<String> provisionerIdentifier,
>       ParameterField<List<TaskSelectorYaml>> delegateSelectors, String uuid,
>       @NonNull AzureCreateARMStepConfigurationParameters configuration) {
> ```

configurationParameters
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepScope.java` line 33 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97HulxDimMAYuz2TrE:-N97HulxDimMAYuz2TrF:b-d7xdf2) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepScope.java#L33)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @RecasterAlias("io.harness.cdng.provision.azure.AzureARMCreateStepScope")
> public class AzureCreateARMStepScope {
> ```

RecasterAlias and class name are different.
maybe AzureArmResourceScope is more meaningful?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMTemplateFile.java` line 26 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97IkyH2KSIzemiHWa0:-N97IkyH2KSIzemiHWa1:badoucg) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMTemplateFile.java#L26)):*
> ```Java
> @Data
> @NoArgsConstructor
> pub [...]

2022-08-10 16:09 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 3 file(s) to review. 2 change requests. 23. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java` line 78 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N978sNL1EFgIsHSopLG:-N97Rx4d4B8tfzyMVLVs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java#L78)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

AzureCreateArmResourceStep would be more correct
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java` line 250 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97LtlYDyfWTfVgJl7F:-N97SG0mEVYkXu7TpRmH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStep.java#L250)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

SonarLint: Remove this useless assignment; "builder" already holds the assigned value along all execution paths. 
</blockquote></details>

Done.
___
*[`943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java` line 79 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97NFS32N59yI99AfRS:-N97VLYu5V-1DYPZS9xS:bus178m) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java#L79)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

configuration for ti should be added  here 925-enforcement-service/src/main/resources/features/cd_features.yml
</blockquote></details>

I added the restrictions in the cd_features.yaml file



_Code quote:_
```Java
  AZURE_CREATE_ARM_RESOURCE,
```
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureTaskNGParameters.java` line 28 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97LCsn7TC_HVDjQdCq:-N97Vn1Q6BWIlksGH67k:bzfpptn) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureTaskNGParameters.java#L28)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I see it has AzureARMTaskType which makes me thinking is some thing specific to arm. Let's give it a name specific to AMR also.
Also consider making it an abstract class if we won't create instances of it.
</blockquote></details>

This class is the base class of AzureARMTaskNGParameters which is the one that is specific for ARM. In future PRs there will be another class that also inherits from this one callez AzureBPTaskNGParameters which is the one specific for BP
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java` line 69 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97FN1Q5oXyZETtuBkI:-N97S_PoCFiR-CCbOlHE:b-gawzr4) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java#L69)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

where do we use that method?
</blockquote></details>

I added the call to the method in this commit
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java` line 72 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97FPvc0LrNWNawZ_cX:-N97TNSu1uxZqltJAEnl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepConfiguration.java#L72)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I think gitStoreConfig.getPaths().getValue() can return null
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java` line 78 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N920oQJ9IWdxEI8e-jZ:-N97TWr75UwVNd1Qzub9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java#L78)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Now we know that new wont have a list of parameters
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java` line 96 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97GHja23dzHcRhZE1N:-N97TbMS6eXJuCDaSsOS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepInfo.java#L96)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java` line 32 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97GgMg3QlBaO_GwWbk:-N97TyQB6dCqhRZ3IX92:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java#L32)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

maybe configurationParameters
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java` line 36 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97Gmy19G-ljTTQrXS9:-N97Tzq27g01EtQ2HqYj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepParameters.java#L36)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

configurationParameters
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepScope.java` line 33 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97HulxDimMAYuz2TrE:-N97UNf72p8bLkHvXCeo:b-8hww1o) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMStepScope.java#L33)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

RecasterAlias and class name are different.
maybe AzureArmResourceScope is more meaningful?
</blockquote></details>

The Recaster probably was not updated in the last refactorization of names. I am setting it to AzureCreateARMResourceStepScope as the name of the class
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMTemplateFile.java` line 26 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97IkyH2KSIzemiHWa0:-N97Up5-7rd2viwhqtm4:b-r83ljy) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMTemplateFile.java#L26)):*
 [...]

2022-08-10 17:09 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 3 file(s) to review. 2 change requests. 23. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java` line 79 at r8](https://reviewable.io/reviews/harness/harness-core/36101#-N97NFS32N59yI99AfRS:-N97il6pECCJYDadN2W2:b-tkekg3) ([raw file](https://github.com/harness/harness-core/blob/5627e1499deaeb0b959a3b4831a953a402bd96a8/943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java#L79)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I added the restrictions in the cd_features.yaml file
</blockquote></details>

I had a problem with this, I added the stuff in this file and i had run times errors, lets check it tomorrow


<!-- Sent from Reviewable.io -->

2022-08-11 07:05 UTC, tmacari-harness requested changes
> Reviewed 1 of 47 files at r1, 20 of 23 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 3 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 128 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9Ae5q26jqwJRUgNEme:-N9Ae5q3C_3yDUFZLVxm:byijlnw) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L128)):*
> ```Java
>   private static final List<String> TERRAFORM_CATEGORY = Arrays.asList("Kubernetes", "Provisioner", "Helm");
> 
>   private static final List<String> AZURE_RESOURCE_CATEGORY =
> ```

Why did we remove AzureWebApp 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java` line 83 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9AfzYi2MZZCUgQOICb:-N9AfzYi2MZZCUgQOICc:b5ohmj5) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java#L83)):*
> ```Java
>       return gitStoreConfig.getPaths().getValue() != null && gitStoreConfig.getPaths().getValue().size() == 1;
>     } else {
>       HarnessStore harnessStore = (HarnessStore) store.getSpec();
> ```

besides Git and Harness store there are other store types, in else branch let's validate if it's HarnessStore. 
If it 's not git or Harness store, throw an exception.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepNode.java` line 42 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9Agvf5BbIM8qDb0YS8:-N9Agvf5BbIM8qDb0YS9:b-h4fdah) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepNode.java#L42)):*
> ```Java
>   @JsonProperty("spec")
>   @JsonTypeInfo(use = NAME, property = "type", include = EXTERNAL_PROPERTY, visible = true)
>   AzureCreateARMResourceStepInfo createStepNodeStepInfo;
> ```

createStepNodeStepInfo is a bit confusing, maybe azureCreateArmResourceStepInfo or createArmResourceStepInfo


<!-- Sent from Reviewable.io -->

2022-08-11 07:33 UTC, abosii-harness requested changes
> Reviewed 1 of 47 files at r1, 6 of 15 files at r4, 1 of 6 files at r6, 1 of 4 files at r7, 18 of 23 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w62w3EDlCLF9RGTXA:-N9Alvbz5ywuG6VF8Qna:b-ksnqc6) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L80)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Yes, that is what was done in the PR, the ARM helper is removed and all the logic there is in the ARM step. The CommonHelper only contains functions that are specific for both steps
</blockquote></details>

but this method doesn't have anything common, right? All logic is behind if statement 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91ykUd9zryP8wmPtMk:-N9Am73b5C1YrCt3G94_:bgszanm) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L153)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Could that be a feasible scenario that we need to handle? the K8sEntityHelper.java and AzureWebAppInstanceSyncPerpetualTaskExecutor, both use the same logic than here where they extract only one element from the azureConnectorDTO. What other elements could we have here?
</blockquote></details>

It doesn't matter if it's a possible scenario or not, if we're exposing a list as value then it should be handled as list, this will make logic future proof for any changes. Before it was done in wrong way
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N921Dj42A7QUxxKs5MX:-N9AntRC09OHf_9AG7rS:beh6jzq) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java#L15)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But where we even use this? If we have different set of steps for each type when do we need to know what is deployment type?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java` line 44 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9Ao5KW2gGQzkDLL55o:-N9Ao5KW2gGQzkDLL55p:bu18hxq) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java#L44)):*
> ```Java
>   @NotNull
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH, allowableValues = "Incremental, Complete")
>   ParameterField<String> mode;
> ```

This should be enum
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java` line 54 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9AnDD49i0hZrbsTjgH:-N9AnDD49i0hZrbsTjgI:b-szw4j8) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java#L54)):*
> ```Java
>     Validator.notNullCheck("Connector ref can't be empty", connectorRef);
>     Validator.notNullCheck("Scope can't be empty", scope);
>     if (!isNumberOfFilesValid(template.getStore())) {
> ```

let's make validation and throwing exception as part of one method


<!-- Sent from Reviewable.io -->

2022-08-11 09:06 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 2 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 128 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9Ae5q26jqwJRUgNEme:-N9AyJjx3kF-PmAZR5RJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L128)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why did we remove AzureWebApp 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/36101#-N8w62w3EDlCLF9RGTXA:-N9AzCGKA2M-IhEw3EwG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4e2bc2edd12fe2b402c1665a90e7c0302e80510/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L80)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

but this method doesn't have anything common, right? All logic is behind if statement 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N91ykUd9zryP8wmPtMk:-N9B-9xrCrkI6rSBpKm6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L153)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

It doesn't matter if it's a possible scenario or not, if we're exposing a list as value then it should be handled as list, this will make logic future proof for any changes. Before it was done in wrong way
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/36101#-N921Dj42A7QUxxKs5MX:-N9B1Z4Q2mc1Tg5MUfrA:bgx2g33) ([raw file](https://github.com/harness/harness-core/blob/8a88850e68b60b745e3c6de561cbbe2b138180c4/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureDeploymentTypes.java#L15)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

But where we even use this? If we have different set of steps for each type when do we need to know what is deployment type?
</blockquote></details>

Before it was used in a method that we are removing in this commit and as a return value for the step type, but now i can remove it and have a string in the step type
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java` line 44 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9Ao5KW2gGQzkDLL55o:-N9B8iKD9_yeD-Li0VX8:bde76o3) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java#L44)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be enum
</blockquote></details>

There is a function later on that transforms this into an enum: retrieveDeploymentMode
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java` line 54 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9AnDD49i0hZrbsTjgH:-N9B0EFtD-clTM6XimXd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java#L54)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's make validation and throwing exception as part of one method
</blockquote></details>

Done.



_Code quote:_
```Java
throw new InvalidRequestException
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java` line 83 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9AfzYi2MZZCUgQOICb:-N9B0mIZ0gju_o6J6hYZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepConfiguration.java#L83)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

besides Git and Harness store there are other store types, in else branch let's validate if it's HarnessStore. 
If it 's not git or Harness store, throw an exception.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepNode.java` line 42 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9Agvf5BbIM8qDb0YS8:-N9B1-zq8rE69aL1SCuO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepNode.java#L42)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

createStepNodeStepInfo is a bit confusing, maybe azureCreateArmResourceStepInfo or createArmResourceStepInfo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-11 10:29 UTC, tmacari-harness approved these changes
> Reviewed 1 of 36 files at r2, 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 1 change requests. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-12 08:46 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 1 of 6 files at r6, 2 of 23 files at r10, 6 of 6 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java` line 44 at r10](https://reviewable.io/reviews/harness/harness-core/36101#-N9Ao5KW2gGQzkDLL55o:-N9GDinB0lfomVB7IVw2:b-60ibxm) ([raw file](https://github.com/harness/harness-core/blob/d3460aa7fb17b8adc743fffec1ba515a4dba1056/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java#L44)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

There is a function later on that transforms this into an enum: retrieveDeploymentMode
</blockquote></details>

But why don't make it an enum in model?


<!-- Sent from Reviewable.io -->

2022-08-12 10:05 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-12 12:41 UTC, nassergonzalez commented
trigger ti0

2022-08-12 12:41 UTC, nassergonzalez commented
trigger ti1

2022-08-12 12:41 UTC, nassergonzalez commented
trigger ti3

2022-08-12 12:58 UTC, nassergonzalez commented
trigger ti0

2022-08-12 12:58 UTC, nassergonzalez commented
trigger ti1

2022-08-15 09:09 UTC, abosii-harness requested changes
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMResourceDeploymentMode.java` line 15 at r14](https://reviewable.io/reviews/harness/harness-core/36101#-N9VkfYV58kufvkkPV0i:-N9VkfYV58kufvkkPV0j:b6hb0fh) ([raw file](https://github.com/harness/harness-core/blob/e70a03cf6f0acef2542bd677b6e78309bd753231/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMResourceDeploymentMode.java#L15)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public enum AzureARMResourceDeploymentMode {
>   INCREMENTAL("INCREMENTAL"),
> ```

you can either use @JsonProperty("Incremental") or create a new method getValue() { return mode; } and annotate it with @JsonValue, the value should be title case INCREMENTAL("Incremental")
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 666 at r14](https://reviewable.io/reviews/harness/harness-core/36101#-N9Vk_cj7tmP_GY_R4Wh:-N9Vk_ckAkMdN9NqapQ9:b1237kv) ([raw file](https://github.com/harness/harness-core/blob/e70a03cf6f0acef2542bd677b6e78309bd753231/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L666)):*
> ```JSON
>               "type": "string",
>               "enum": [
>                 "INCREMENTAL",
> ```

This should be title case Incremental
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentSteps/all.json` line 337 at r14](https://reviewable.io/reviews/harness/harness-core/36101#-N9VkdHg3rnIisvqDzDO:-N9VkdHg3rnIisvqDzDP:b1237kv) ([raw file](https://github.com/harness/harness-core/blob/e70a03cf6f0acef2542bd677b6e78309bd753231/125-cd-nextgen/src/test/resources/schema/DeploymentSteps/all.json#L337)):*
> ```JSON
>               "type": "string",
>               "enum": [
>                 "INCREMENTAL",
> ```

This should be title case Incremental


<!-- Sent from Reviewable.io -->

2022-08-15 09:14 UTC, tmacari-harness requested changes
> Reviewed 5 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java` line 42 at r14](https://reviewable.io/reviews/harness/harness-core/36101#-N9Vin6V-FE9C4Gs-3s8:-N9Vin6V-FE9C4Gs-3s9:b-yiuhi7) ([raw file](https://github.com/harness/harness-core/blob/e70a03cf6f0acef2542bd677b6e78309bd753231/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java#L42)):*
> ```Java
>   @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> resourceGroup;
> 
>   AzureARMResourceDeploymentMode mode;
> ```

Would that work if it is not at ParameterField ?
Did you try with an expression, runtime input?


<!-- Sent from Reviewable.io -->

2022-08-15 11:00 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 1 of 6 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-15 11:02 UTC, abosii-harness approved these changes
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-15 12:58 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMResourceDeploymentMode.java` line 15 at r14](https://reviewable.io/reviews/harness/harness-core/36101#-N9VkfYV58kufvkkPV0i:-N9VnHU73b22VC2PHpjT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e70a03cf6f0acef2542bd677b6e78309bd753231/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureARMResourceDeploymentMode.java#L15)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

you can either use @JsonProperty("Incremental") or create a new method getValue() { return mode; } and annotate it with @JsonValue, the value should be title case INCREMENTAL("Incremental")
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java` line 42 at r14](https://reviewable.io/reviews/harness/harness-core/36101#-N9Vin6V-FE9C4Gs-3s8:-N9W_PrDA0UH4d-pGtXH:b6ujch) ([raw file](https://github.com/harness/harness-core/blob/e70a03cf6f0acef2542bd677b6e78309bd753231/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureResourceGroupSpec.java#L42)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Would that work if it is not at ParameterField ?
Did you try with an expression, runtime input?
</blockquote></details>

Not applicable


<!-- Sent from Reviewable.io -->

2022-08-15 16:18 UTC, nassergonzalez commented
trigger ti1

2022-08-15 17:00 UTC, raghuAtWings submitted a review, later dismissed
> Reviewed 7 of 47 files at r1, 12 of 36 files at r2, 1 of 13 files at r3, 5 of 15 files at r4, 1 of 6 files at r6, 15 of 23 files at r10, 4 of 6 files at r11, 1 of 1 files at r12, 2 of 3 files at r13, 3 of 6 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-15 17:05 UTC, nassergonzalez commented
trigger ti1

2022-08-15 17:06 UTC, nassergonzalez commented
trigger codebasehash

2022-08-15 18:41 UTC, nassergonzalez commented
trigger compile

2022-08-15 18:41 UTC, nassergonzalez commented
trigger ti3

2022-08-15 18:42 UTC, nassergonzalez commented
trigger codebasehash

2022-08-15 18:42 UTC, nassergonzalez commented
trigger compile

2022-08-15 18:44 UTC, nassergonzalez commented
trigger compile

2022-08-16 08:09 UTC, nassergonzalez commented
trigger ti4

2022-08-16 08:11 UTC, nassergonzalez commented
trigger codebasehash

2022-08-16 09:04 UTC, puthrayaharness approved these changes

2022-08-16 09:05 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 7 of 47 files at r1, 12 of 36 files at r2, 1 of 13 files at r3, 5 of 15 files at r4, 1 of 6 files at r6, 15 of 23 files at r10, 4 of 6 files at r11, 1 of 1 files at r12, 2 of 3 files at r13, 3 of 6 files at r14, 3 of 4 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-16 09:05 UTC, nassergonzalez commented
trigger codebasehash

2022-08-16 09:37 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-16 09:39 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-16 09:44 UTC, prashantsharma04 approved these changes
> Reviewed 7 of 47 files at r1, 12 of 36 files at r2, 1 of 13 files at r3, 5 of 15 files at r4, 1 of 6 files at r6, 15 of 23 files at r10, 4 of 6 files at r11, 1 of 1 files at r12, 2 of 3 files at r13, 3 of 6 files at r14, 3 of 4 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-16 14:57 UTC, sahilhindwani-harness approved these changes
> Reviewed 7 of 47 files at r1, 12 of 36 files at r2, 1 of 13 files at r3, 5 of 15 files at r4, 1 of 6 files at r6, 15 of 23 files at r10, 4 of 6 files at r11, 1 of 1 files at r12, 3 of 6 files at r14, 3 of 4 files at r15, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36101)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-16 16:04 UTC, merged