feat: [CDS-40818]: PowerShell for ShellScript step
harness/harness-core pull request #36118
Opened 2022-08-06 14:47 UTC by filip5rovic

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-06 14:54 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 1 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36118)

2022-08-16 08:58 UTC, puthrayaharness requested changes

2022-08-16 08:58 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java
> +  public static final String COMMAND_UNIT = "Execute";
Please reuse this from ShellScript itself.

2022-08-16 09:30 UTC, filip5rovic commented
trigger feature-build

2022-08-17 13:02 UTC, filip5rovic commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java
> +  public static final String COMMAND_UNIT = "Execute";
Done 👍

2022-08-17 13:31 UTC, filip5rovic commented
trigger feature-build

2022-08-18 10:24 UTC, filip5rovic commented
@yogesh-chauhan 
Answers for https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist:
1. Yes
2. N/A
3. Yes, Yes, Yes
4. No changes in existing tasks
5. No enums removed
6. Yes, task type, added at the end

2022-08-18 11:28 UTC, yogesh-chauhan approved these changes

2022-08-18 11:28 UTC, yogesh-chauhan commented
trigger codebasehash

2022-08-18 13:25 UTC, filip5rovic commented
trigger publish-delegate

2022-08-24 08:44 UTC, puthrayaharness approved these changes

2022-08-24 08:44 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 10 of 18 files at r1, 3 of 6 files at r2, 1 of 3 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36118)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-24 08:45 UTC, puthrayaharness commented
trigger codebasehash

2022-09-05 07:24 UTC, yogesh-chauhan approved these changes
> Reviewed 8 of 18 files at r1, 1 of 6 files at r2, 2 of 6 files at r4, 15 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36118)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-05 07:25 UTC, yogesh-chauhan approved these changes

2022-09-06 07:35 UTC, yogesh-chauhan approved these changes

2022-09-06 08:12 UTC, poojaSinghal reviewed
> Reviewed 3 of 18 files at r1, 1 of 6 files at r4, 11 of 15 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36118)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-06 08:20 UTC, poojaSinghal approved these changes
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36118)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-06 08:22 UTC, merged