fix: [BT-1616]: speed up graphql schema load time
harness/harness-core pull request #36218
Opened 2022-08-09 18:45 UTC by rickmarry

reduce the number of times we load the schema files from 3 to 2

## Describe your changes
Very simple refactor that resultes in only calling loadSchemaForEnv 2 times instead of 3.. 
The outcome is identical and we reduce load time by about 29%  

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-09 18:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36218) it.</sub>

2022-08-09 18:48 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36218)

2022-08-10 13:47 UTC, rijajoo requested changes

2022-08-10 13:47 UTC, rijajoo commented on 400-rest/src/main/java/software/wings/graphql/provider/GraphQLProvider.java
> +      publicGraphQL = getGraphQL(GRAPHQL_SCHEMA_PUBLIC_DIRECTORY_PATH, typeDefinitionRegistry);
Shouldn't the privateGraphQL contain GRAPHQL_SCHEMA_PUBLIC_DIRECTORY_PATH as well?

2022-08-10 16:37 UTC, rickmarry commented on 400-rest/src/main/java/software/wings/graphql/provider/GraphQLProvider.java
> +      publicGraphQL = getGraphQL(GRAPHQL_SCHEMA_PUBLIC_DIRECTORY_PATH, typeDefinitionRegistry);
It does.. the typeDefinitionRegistry should accumulate it when we get the public one

2022-08-11 11:12 UTC, rijajoo submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36218#-:-N9Bao4dETbnKoQidtF8:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-11 15:03 UTC, ankit-harness approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36218)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-11 15:45 UTC, rickmarry reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36218)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-11 17:34 UTC, rickmarry reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36218)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/graphql/provider/GraphQLProvider.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/36218#-N92vIUPZ5OPXe2oRlLH-r1-61:-N9C_TdmBYYRcC4AZ40v:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/85d748ea06bd041013d54adeeaf2da55508a9092/400-rest/src/main/java/software/wings/graphql/provider/GraphQLProvider.java#L61)):*
<details><summary><i>Previously, rickmarry (Rick Marry) wrote…</i></summary><blockquote>

It does contain it. The typeDefinitionRegistry will accumulate it when we get the public one.  Prior to this change, typeDefinitionRegistry was a local var.. now we pass it in so that when it gets to do the private one, it also gets what public has accumulated
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-08-12 04:56 UTC, rijajoo approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36218)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-12 04:57 UTC, merged