[feat]:[PIE-4659]: Migrating Redis cache to enterprise for ng manager and cv
harness/harness-core pull request #36248
Opened 2022-08-10 08:32 UTC by ankittiwari-harness

## Migrating Redis cache to enterprise for ng manager and cv
1) Adding config changes in ng amnager, sto manager and cv for using enterprise cache manager
2) Migrated sdkEventsCache to Enterprise Redis
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-10 08:34 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36248)

2022-08-10 08:55 UTC, ankittiwari-harness commented
trigger codeformat

2022-08-10 08:55 UTC, ankittiwari-harness commented
trigger messagecheck

2022-08-10 09:32 UTC, ankittiwari-harness commented
trigger codeformat

2022-08-10 11:22 UTC, archit-harness requested changes
> Reviewed 20 of 22 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`120-ng-manager/container/scripts/replace_configs.sh` line 401 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96UTa-AvVlz6rGd7BM:-N96UTa-AvVlz6rGd7BN:b-vtms65) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/120-ng-manager/container/scripts/replace_configs.sh#L401)):*
> ```Shell
> 
> if [[ "$REDIS_SCRIPT_CACHE" == "false" ]]; then
>   yq write -i $ENTERPRISE_REDISSON_CACHE_FILE useScriptCache false
> ```

we need to make changes in build/container/scripts/replace_configs.sh as well
___
*[`300-cv-nextgen/cv-nextgen-config.yml` line 160 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96SC0A2EXTxm7NADOt:-N96SC0A2EXTxm7NADOu:b-818w1y) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/300-cv-nextgen/cv-nextgen-config.yml#L160)):*
> ```YAML
>   cacheNamespace: ""
>   disabledCaches: [ ]
>   enterpriseCacheEnabled: true
> ```

build_dist.sh, Build.bazel, replace_configs.sh changes for cv are not there
___
*[`315-sto-manager/sto-manager-config.yml` line 235 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96SU88AjP59iwr9S9X:-N96SU88AjP59iwr9S9Y:byppj8) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/315-sto-manager/sto-manager-config.yml#L235)):*
> ```YAML
>   corePoolSize: ${PLAN_CREATOR_SERVICE_EXECUTOR_POOL_CORE_SIZE:-2}
>   maxPoolSize: ${PLAN_CREATOR_SERVICE_EXECUTOR_POOL_MAX_SIZE:-3}
>   idleTime: ${PLAN_CREATOR_SERVICE_EXECUTOR_POOL_IDLE_TIME:-30}
> ```

BUILD.bazel file changes for sto are not there
___
*[`dockerization/cv-nextgen/Dockerfile-cv-nextgen-cie-jdk` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96TotuCXc29ih8LCTS:-N96TotuCXc29ih8LCTT:b-ysha8z) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/dockerization/cv-nextgen/Dockerfile-cv-nextgen-cie-jdk#L35)):*
> ```
> 
> COPY --chown=65534:65534 inject-saas-apm-bins-into-dockerimage.sh /opt/harness
> RUN /opt/harness/inject-saas-apm-bins-into-dockerimage.sh && rm -rf /opt/harness/inject-saas-apm-bins-into-dockerimage.sh
> ```

dockerisation folder changes for ci are not there
___
*[`scripts/jenkins/portal-openjdk-bazel.sh` line 199 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96T7pf7URR_1QybwkJ:-N96T7pf7URR_1QybwkK:b-vnlmer) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/scripts/jenkins/portal-openjdk-bazel.sh#L199)):*
> ```Shell
> cp ../../332-ci-manager/config/key.pem .
> cp ../../332-ci-manager/config/cert.pem .
> cp ../../332-ci-manager/service/src/main/resources/redisson-jcache.yaml .
> ```

enterprise redisson file not added for ci, plus changes for ci service not done


<!-- Sent from Reviewable.io -->

2022-08-10 11:24 UTC, sahilhindwani-harness commented
*[`120-ng-manager/config.yml` line 427 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96UsMiBLOhx4cTkZsr:-N96UsMiBLOhx4cTkZss:b-d4n8rg) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/120-ng-manager/config.yml#L427)):*
> ```YAML
>   cacheNamespace: ""
>   disabledCaches: [ ]
>   enterpriseCacheEnabled: true
> ```

${ENTERPRISE_CACHE_ENABLED:-false}

nit: We can use above so that we don't need to add this in replace_config.sh



_Code quote:_
```YAML
true
```


<!-- Sent from Reviewable.io -->

2022-08-10 11:28 UTC, sahilhindwani-harness requested changes
> Reviewed 20 of 22 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-11 09:10 UTC, archit-harness requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: 8 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`120-ng-manager/container/scripts/replace_configs.sh` line 401 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96UTa-AvVlz6rGd7BM:-N9B8D8n07eKcLphkNr5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/120-ng-manager/container/scripts/replace_configs.sh#L401)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we need to make changes in build/container/scripts/replace_configs.sh as well
</blockquote></details>

done
___
*[`300-cv-nextgen/cv-nextgen-config.yml` line 160 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96SC0A2EXTxm7NADOt:-N9B9JpA0S-dHsy5X3HE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/300-cv-nextgen/cv-nextgen-config.yml#L160)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

build_dist.sh, Build.bazel, replace_configs.sh changes for cv are not there
</blockquote></details>

done
___
*[`315-sto-manager/sto-manager-config.yml` line 235 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96SU88AjP59iwr9S9X:-N9B9_DW2vr5biAVk_8E:bi6l9uj) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/315-sto-manager/sto-manager-config.yml#L235)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

BUILD.bazel file changes for sto are not there
</blockquote></details>

@ankittiwari-harness this  example "//120-ng-manager/src/main/resources/enterprise-redisson-jcache.yaml", i think is still left
___
*[`dockerization/cv-nextgen/Dockerfile-cv-nextgen-cie-jdk` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96TotuCXc29ih8LCTS:-N9B9jJ717PmfXxFb9af:b-ekmyve) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/dockerization/cv-nextgen/Dockerfile-cv-nextgen-cie-jdk#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dockerisation folder changes for ci are not there
</blockquote></details>

this is i think is also pending
___
*[`scripts/jenkins/portal-openjdk-bazel.sh` line 199 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96T7pf7URR_1QybwkJ:-N9B9lY6AcjqZ85Wd1yQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/scripts/jenkins/portal-openjdk-bazel.sh#L199)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

enterprise redisson file not added for ci, plus changes for ci service not done
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-08-11 12:17 UTC, archit-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: 16 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`315-sto-manager/sto-manager-config.yml` line 235 at r3](https://reviewable.io/reviews/harness/harness-core/36248#-N96SU88AjP59iwr9S9X:-N9BpcVNBCDLPeXoeJc6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/397252369a6bcc4114d41235a3ce4b090c0fb0d7/315-sto-manager/sto-manager-config.yml#L235)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@ankittiwari-harness this  example "//120-ng-manager/src/main/resources/enterprise-redisson-jcache.yaml", i think is still left
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-08-11 15:38 UTC, AbhijithHarness submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: 16 file(s) to review. 1 change requests. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-12 07:19 UTC, shubham-in10se submitted a review, later dismissed
> Reviewed 19 of 22 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 8 of 8 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: 1 change requests. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-12 08:29 UTC, ankittiwari-harness commented
> > Reviewed 20 of 22 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)_ status: 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto.

 The config related improvements has to be done across multiple projects. Can we pick it up as part of a broader refactoring.

2022-08-12 09:13 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 8 of 8 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-12 09:30 UTC, ankittiwari-harness commented
trigger ti4

2022-08-16 04:22 UTC, kshitij-harness reviewed
Are the changes tested in pre QA environment?
If yes, kindly add that in description.

2022-08-16 04:22 UTC, kshitij-harness commented on 120-ng-manager/container/BUILD.bazel
> +        "//120-ng-manager/src/main/resources/enterprise-redisson-jcache.yaml",
Shouldn't this be resources:enterprise-redisson-jcache.yaml

2022-08-16 04:22 UTC, kshitij-harness commented on 332-ci-manager/build/container/BUILD.bazel
> +        "//332-ci-manager/service/src/main/resources/enterprise-redisson-jcache.yaml",
Shouldn't this be resources:enterprise-redisson-jcache.yaml

2022-08-16 04:22 UTC, kshitij-harness commented on 332-ci-manager/container/BUILD.bazel
> +        "//332-ci-manager/service/src/main/resources/enterprise-redisson-jcache.yaml",
Shouldn't this be resources:enterprise-redisson-jcache.yaml

2022-08-16 04:22 UTC, kshitij-harness commented on 332-ci-manager/service/src/main/resources/META-INF/services/enterprise-redisson-jcache.yaml
> +singleServerConfig : address : "redis://127.0.0.1:6379" codec
Could you format this file for better readability?

2022-08-16 04:38 UTC, ankittiwari-harness commented on 332-ci-manager/container/BUILD.bazel
> +        "//332-ci-manager/service/src/main/resources/enterprise-redisson-jcache.yaml",
done in revision

2022-08-16 04:39 UTC, ankittiwari-harness commented on 332-ci-manager/service/src/main/resources/META-INF/services/enterprise-redisson-jcache.yaml
> +singleServerConfig : address : "redis://127.0.0.1:6379" codec
done in revision

2022-08-16 04:42 UTC, ankittiwari-harness commented
> Are the changes tested in pre QA environment? If yes, kindly add that in description.

Changes will be tested in Pre QA once merged in develop.

2022-08-16 04:43 UTC, kshitij-harness approved these changes
> Reviewed 16 of 22 files at r1, 1 of 1 files at r3, 2 of 8 files at r4, 7 of 8 files at r5, 5 of 6 files at r6, 2 of 2 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: 12 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-16 04:54 UTC, archit-harness approved these changes
> Reviewed 5 of 6 files at r6, 2 of 2 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36248)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-08-16 06:14 UTC, ankittiwari-harness commented
trigger ti0

2022-08-16 13:32 UTC, merged