[fix]: [CDS-41000]: Add expired and aborted count to pipeline executions response
harness/harness-core pull request #36324
Opened 2022-08-12 06:28 UTC by Abhishek-CDC

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-12 06:32 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36324)

2022-08-16 07:40 UTC, Abhishek-CDC commented
trigger ft1

2022-08-16 07:41 UTC, Abhishek-CDC commented
trigger ft2

2022-08-16 08:00 UTC, Abhishek-CDC commented
trigger messagecheck

2022-08-17 06:08 UTC, abhinavmittal-harness approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36324)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-17 06:11 UTC, abhinavmittal-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/36324#-N9eQD4z8IQXT17Mtb1M:-N9eQD5-0yn5_HB6EyRk:boqib0y) ([raw file](https://github.com/harness/harness-core/blob/854cfc6e03210024ae2dbc21e5a5a182699d698b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java#L162)):*
> ```Java
>           }
>           if (statusAndTime.get(i).getStatus().contentEquals(ExecutionStatus.ABORTED.name())) {
>             aborted++;
> ```

do we want to include aborted and expired in failed count as well
Confirm that


<!-- Sent from Reviewable.io -->

2022-08-18 07:50 UTC, abhinavmittal-harness approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36324)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-18 10:35 UTC, Abhishek-CDC commented
trigger ft1

2022-08-18 11:42 UTC, abhinavmittal-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36324)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-18 11:42 UTC, abhinavmittal-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36324#-:-N9kkp155w2dpBPnJtVK:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-18 12:20 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36324)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-18 13:09 UTC, puthrayaharness requested changes

2022-08-18 13:09 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java
> +  private List<String> successList = Arrays.asList(ExecutionStatus.IGNOREFAILED.name(), ExecutionStatus.SUCCESS.name());
Please make this a `static final` & rename it to `SUCCESS_STATUS_LIST`.

2022-08-18 13:09 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java
> +  private List<String> successList = Arrays.asList(ExecutionStatus.IGNOREFAILED.name(), ExecutionStatus.SUCCESS.name());
Also rather than do a `.name()` each time. You can `Arrays.asList(IGNOREFAILED).stream().map(ExecutionStatus::name).collect(toList())` would be better.

2022-08-22 02:07 UTC, Abhishek-CDC commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/36324#-N9FjV9TS8ySP02ZIMCY-r3-43:-NA2IZUI7qT0Z-YMisqV:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f559f8f1947d11e099feeb31ce6844c008fc3505/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java#L43)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Also rather than do a `.name()` each time. You can `Arrays.asList(IGNOREFAILED).stream().map(ExecutionStatus::name).collect(toList())` would be better.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-08-22 02:08 UTC, Abhishek-CDC commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/36324#-N9eQD4z8IQXT17Mtb1M:-N9eT03g3jMKt7oW6utI:b32w12) ([raw file](https://github.com/harness/harness-core/blob/854cfc6e03210024ae2dbc21e5a5a182699d698b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardServiceImpl.java#L162)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

do we want to include aborted and expired in failed count as well
Confirm that
</blockquote></details>

No


<!-- Sent from Reviewable.io -->

2022-08-22 07:01 UTC, puthrayaharness approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36324)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-22 12:32 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36324)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-22 12:33 UTC, merged