[CI-4985]: Initial change for docker runner execution and cleanup tasks
harness/harness-core pull request #36373
Opened 2022-08-15 06:14 UTC by happyhebaby

## Describe your changes
This is the initial java change to enable execute and cleanup task, I also refactor the initial step change when I duplicated classes for docker case.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-15 06:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36373) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36373) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36373) it.</sub>

2022-08-15 06:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36373) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36373) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36373) it.</sub>

2022-08-15 06:17 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 123 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 119 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36373)

2022-08-25 10:48 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/stateutils/buildstate/BuildSetupUtils.java
> +/*
Why it is showing up as a new file? I can see there is a BuildSetupUtils already present.

2022-08-25 10:48 UTC, shubham149 commented on 325-sto-beans/src/main/java/io/harness/beans/stages/SecurityStageConfigImpl.java
> +  Runtime dockerRuntime;
Do not add dockerRuntime field. There should be a single runtime field

2022-08-26 12:51 UTC, vistaarjuneja commented on 332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/Infrastructure.java
> +  @ApiModelProperty(allowableValues = "KubernetesDirect, UseFromStage, VM, KubernetesHosted, DOCKER") Type getType();
`HostedVm` is not present in this list. Do we need to add docker here?

2022-08-26 12:51 UTC, vistaarjuneja commented on 332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/runtime/DockerRuntime.java
> +    private String size;
I think we can keep the spec empty for now. Is this getting used anywhere?

2022-08-26 12:51 UTC, vistaarjuneja commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +      if (isValidRuntime)
This kind of layout might be easier to understand:
```
if (runtime != null) {
    if type == docker {
    } else if type == vm {
    } else {
      // not supported
   }
...
} else {
throw error
}
```

2022-08-26 12:51 UTC, vistaarjuneja commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +        DockerInfraYaml infraYaml = DockerInfraYaml.builder()
Set `infrastructure` directly

2022-08-26 12:51 UTC, vistaarjuneja commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +                .spec(DockerOSYaml.builder().spec(DockerOSYamlSpec.builder().
Why does this have OS? It should be similar as hosted and contain platform right?

2022-08-26 12:51 UTC, vistaarjuneja commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/PluginSettingUtils.java
> +    } else if (infraType == Type.VM || infraType == Type.DOCKER) {
what is this check and do we need it in docker?

2022-08-26 12:51 UTC, vistaarjuneja commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  CI_VM_INITIALIZE_TASK(TaskGroup.CI, CIVmInitializeTaskParams.class, VmTaskExecutionResponse.class, true),
We shouldn't need these registrations in kryo since the CI VM flow works right now without this

2022-08-26 12:51 UTC, vistaarjuneja commented on 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
> +    kryo.register(CIExecuteStepTaskParams.class, 29000);
Ditto. We shouldn't need this kryo changes

2022-08-29 06:03 UTC, happyhebaby commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/vm/CIVmInitializeTaskHandler.java
> +    if (infraType == "vm") {
Already replaced with a safer enum based comparison, not sure why you didn't see the new change below:
```
if (infraType == CIVmInitializeTaskParams.Type.DOCKER) {
      poolId = "";
    } else {
      poolId = params.getPoolID();
    }

2022-08-29 06:33 UTC, happyhebaby commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +      if (isValidRuntime)
I agree this is easier to understand, thanks.

2022-08-29 17:50 UTC, happyhebaby commented on 320-ci-execution/src/main/java/io/harness/stateutils/buildstate/BuildSetupUtils.java
> +/*
Not sure, but this could be auto resolved when the merge happens.

2022-08-29 19:49 UTC, happyhebaby commented on 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
> +    kryo.register(CIExecuteStepTaskParams.class, 29000);
This looks necessary, the presence of CIInitializeTaskParams in the kryo file also suggests this. I tested without them and hit kryo error.

2022-08-30 09:22 UTC, shubham149 commented on 332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/Infrastructure.java
> +  @ApiModelProperty(allowableValues = "KubernetesDirect, UseFromStage, VM, KubernetesHosted, DOCKER") Type getType();
Docker should not be a part of this list

2022-08-30 09:22 UTC, shubham149 commented on 332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/Infrastructure.java
> +  @ApiModelProperty(allowableValues = "KubernetesDirect, UseFromStage, VM, KubernetesHosted, DOCKER") Type getType();
Also, verify whether other builds are working after this change i.e. k8, vm, hosted vm etc

2022-08-30 12:48 UTC, shubham149 commented on 320-ci-execution/src/main/java/io/harness/stateutils/buildstate/BuildSetupUtils.java
> +public class BuildSetupUtils {
320-ci-execution package does not exist. Can you rebase the code?

2022-08-30 18:57 UTC, happyhebaby commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/executioncapability/CIVmConnectionCapability.java
> +    if (infraType == CapabilityType.CI_DOCKER.toString()) {
Currently we return true for docker case, literally skipping capability check for docker.

2022-08-30 18:59 UTC, happyhebaby commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/runner/SetupVmRequest.java
> +  @JsonProperty("infra_type") String infraType;
We use this field the track the actual infra type used for the request. On golang side we need this field to identify the actual infrastructure that sent the request.

2022-08-30 19:04 UTC, happyhebaby commented on 933-ci-commons/src/main/java/io/harness/vm/VmExecuteStepUtils.java
> +    if (infraType == CIExecuteStepTaskParams.Type.DOCKER) {
Currently we try to try to re-use vm classes as much as we could, as most of the implementation is the same between docker and vm. There is no silver bullet in how to implement this, either we duplicate the code to produce an equivalent set of docker class, or we try to abstract the code into a same class, with small amount of infra specific logic embedded within the class. Overall I still believe the latter is a better approach with better code maintainability.

2022-08-31 00:23 UTC, happyhebaby commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/vm/CIVmCleanupTaskHandler.java
> +    CIVmCleanupTaskParams.Type infraType = params.getInfraType();
Dito

2022-08-31 00:32 UTC, happyhebaby commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/vm/CIVmInitializeTaskHandler.java
> +    CIVmInitializeTaskParams.Type infraType = params.getInfraType();
Dito

2022-08-31 00:38 UTC, happyhebaby commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  CI_VM_INITIALIZE_TASK(TaskGroup.CI, CIVmInitializeTaskParams.class, VmTaskExecutionResponse.class, true),
We don't need these in TaskType.java but do need the new kryo entries.

2022-08-31 00:38 UTC, happyhebaby commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/CIVmCleanupTaskParams.java
>  import io.harness.delegate.beans.ci.CICleanupTaskParams;
Dito

2022-09-01 05:56 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +      if (runtime != null) {
move this to new method

2022-09-01 05:56 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +      Runtime.Type runtimeType = null;
use optional

2022-09-01 05:57 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/VmInitializeTaskUtils.java
> +    if (infraType == Infrastructure.Type.VM) {
use this custom logic to new method

2022-09-01 05:57 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/VmInitializeTaskUtils.java
> +    if (infraType == Infrastructure.Type.VM) {
VM handling can be moved to new method

2022-09-01 06:01 UTC, harshjain12 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/CIVmConnectionCapabilityCheck.java
> +    if (connectionCapabiilty.getInfraType() == "vm") {
move all these constants to final constant file

2022-09-09 12:54 UTC, harshjain12 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java
> +    public String getPoolId() {
why do we have to keep poolId here. It should be part of k8

2022-09-09 13:06 UTC, harshjain12 requested changes
> Reviewed 8 of 43 files at r1, 1 of 8 files at r2, 12 of 40 files at r3, 8 of 22 files at r4, 48 of 48 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373)* status: 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXDrg6DXHs49X0fDwI:-NBXDrg6DXHs49X0fDwJ:b-pvpbws) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java#L50)):*
> ```Java
>   @NotNull private VmPoolYamlSpec spec;
> 
>   public String getPoolName() {
> ```

van you move this to utility
Yaml should not have logic
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java` line 96 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXECdS9ZHkQl3Yhk98:-NBXECdTD1g1tECpFMGU:bosrypc) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java#L96)):*
> ```Java
>         } else if (runtimeType == Runtime.Type.CLOUD) {
>           infrastructure = HostedVmInfraYaml.builder()
>                   .spec(HostedVmInfraSpec.builder().platform(integrationStageConfig.getPlatform()).build())
> ```

all this condition can be moved to separate method
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXEbBf0tWfYg1RG6yn:-NBXEbBf0tWfYg1RG6yo:bbnngp) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java#L41)):*
> ```Java
>   @Builder.Default @NotNull private Type type = Type.DLITE_VM;
> 
>   private InfraInfo infraInfo;
> ```

Add getter annotation instead of adding separate get met
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/K8StageInfraDetails.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXEpab1XK6Li6Yjxju:-NBXEpab1XK6Li6Yjxjv:bsxcljf) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/K8StageInfraDetails.java#L41)):*
> ```Java
> 
>   @Builder.Default @NotNull private Type type = Type.K8;
>   @NotNull private InfraInfo infraInfo;
> ```

Add lombok annotations to get instead of getter
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/VmStageInfraDetails.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXF6xC1LeayMQfPBeR:-NBXF6xC1LeayMQfPBeS:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/VmStageInfraDetails.java#L41)):*
> ```Java
> 
>   @Builder.Default @NotNull private Type type = Type.VM;
>   @NotNull private InfraInfo infraInfo;
> ```

ditto
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java` line 135 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXIMRC4hl_0f9NqifX:-NBXIMRD4hoXAr2EIz2Y:b32ifpk) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java#L135)):*
> ```Java
>     StageDetails stageDetails = (StageDetails) optionalSweepingOutput.getOutput();
>     InfraInfo infraInfo = vmStageInfraDetails.getInfraInfo();
>     String poolId = infraInfo.getPoolId();
> ```

Why are we retrieving  poolId from infraInfo ?
poolId is not even applicable for docker
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java` line 143 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXIaleBvMmiRPQrMUD:-NBXIaleBvMmiRPQrMUE:boalycm) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java#L143)):*
> ```Java
> 
>     if (infraType == Infrastructure.Type.VM) {
>       VmInfraYaml vmInfraYaml = (VmInfraYaml) infrastructure;
> ```

move if condition logic to new method
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java` line 155 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXIcZy2JWUue-jGW0H:-NBXIcZy2JWUue-jGW0I:bbik4h2) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java#L155)):*
> ```Java
>       return resolveOSType(vmPoolYaml.getSpec().getOs());
>     } else {
>       DockerInfraYaml dockerInfraYaml = (DockerInfraYaml) infrastructure;
> ```

move else condition  logic to new method
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 150 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXIhdp6FlMC1ggrHPC:-NBXIhdp6FlMC1ggrHPD:b1lr97f) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L150)):*
> ```Java
>     Infrastructure infrastructure = initializeStepInfo.getInfrastructure();
>     InfraInfo infraInfo = validateInfrastructureAndGetInfraInfo(infrastructure);
>     String poolId = infraInfo.getPoolId();
> ```

poolid should not be part of infraInfo
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/filter/CIStageFilterJsonCreator.java` line 128 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXJcpB-9QSJxmEcdUx:-NBXJcpB-9QSJxmEcdUy:b-fnf0yr) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/filter/CIStageFilterJsonCreator.java#L128)):*
> ```Java
>     {
>       Runtime.Type runtimeType = runtime.getType();
>       isValidRuntime = runtimeType == Runtime.Type.CLOUD || runtimeType == Runtime.Type.DOCKER;
> ```

We can make this method simple. It is very hard to read 


  private void validateRuntime(IntegrationStageConfig integrationStageConfig) {
    Runtime runtime = integrationStageConfig.getRuntime();
    if (runtime != null && (runtime.getType() == Runtime.Type.CLOUD || runtime.getType() == Runtime.Type.DOCKER)) {
      return;
    } else {
      throw new CIStageExecutionException(
          "Infrastructure or runtime field with type Cloud (for vm) or type Docker (for docker) is mandatory for execution");
    }
  }
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/vm/VmPluginCompatibleStepSerializer.java` line 48 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXKEWe-NRXF8oDVqSD:-NBXKEWe-NRXF8oDVqSE:b-iyyrb2) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/vm/VmPluginCompatibleStepSerializer.java#L48)):*
> ```Java
>     long timeout = TimeoutUtils.getTimeoutInSeconds(parameterFieldTimeout, pluginCompatibleStep.getDefaultTimeout());
>     StageInfraDetails.Type type = stageInfraDetails.getType();
>     if  [...]

2022-09-09 16:42 UTC, happyhebaby commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +      if (runtime != null) {
This is the only place this logic is used. Besides this logic involves two return variables `isValidRuntime` and `infrastructure`, unlike Python that could return multiple objects, if I want to return multiple objects then I have to define a class that capture them, or use a pair, either is less readable then keeping the logic in here.

2022-09-12 05:42 UTC, shubham149 reviewed
Unit tests are missing. We should cover all the UTs for the newly added code.

Also, test whether k8, vm & hosted vm builds are passing with this change.

2022-09-12 05:42 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/executioncapability/CapabilityType.java
> +  CI_DOCKER,
If docker is using VM capability check, then we can remove it.

2022-09-12 05:42 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java
> +public class K8InfraInfo implements InfraInfo{
why do we need k8InfraInfo?

2022-09-12 05:42 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java
> +        return Collections.singletonList(CIVmConnectionCapability.builder().stageRuntimeId(stageRuntimeId)
k8 does not use vm capability check

2022-09-12 05:42 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java
> +    enum Type { K8, VM, HOSTED_VM, DOCKER }
Hosted vm and k8 should not be a part of this

2022-09-12 05:42 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/HostedVmInfraInfo.java
> +public class HostedVmInfraInfo implements InfraInfo{
Hosted vm does not use capability check. Remove this.

2022-09-12 05:42 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/CIInitializeTaskParams.java
> +  InfraInfo getInfraInfo();
Move InfraInfo to CIVmInitializeTaskParams

2022-09-12 05:42 UTC, shubham149 commented on 933-ci-commons/src/main/java/io/harness/vm/VmExecuteStepUtils.java
> +                                      .id(getIdentifier(params.getStepRuntimeId()));
Remove this line since it is already set in L67.

2022-09-12 05:42 UTC, shubham149 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/CIVmConnectionCapabilityCheck.java
> +    //TODO:xun figure out logic for docker
Ensure that the comment is addressed before merging the PR

2022-09-12 05:42 UTC, shubham149 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/CIVmConnectionCapabilityCheck.java
> +      isOwner = true;
If 2 delegates are present. One is a K8 delegate and other is docker delegate. How will we figure out that tasks needs to be sent only to docker delegate which has this capability to execute docker vm tasks?

2022-09-12 05:42 UTC, shubham149 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/vm/CIVmInitializeTaskHandler.java
> +                                       .network(SetupVmRequest.Network.builder().id(stageId).build())
this is not addressed

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java
> +        infraType = CIExecuteStepTaskParams.Type.DOCKER;
Where is infraType used?

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java
> +      infraType = CIExecuteStepTaskParams.Type.DLITE_VM;
infraType is not valid for dlite vm

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/filter/CIStageFilterJsonCreator.java
> +    boolean isValidRuntime = runtime != null;
variable name is not correct. If runtime is not null, it does not mean it is valid.

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeUtils.java
>    public static OSType getOS(Infrastructure infrastructure) {
This file is deprecated. It should not be used anywhere.

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java
> +        .infraType(Infrastructure.Type.HOSTED_VM.toString())
Infra type is not valid for hosted vms.

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java
> +          InitializeStepInfo initializeStepInfo, Ambiance ambiance) {
As I suggested earlier, don't make any changes in this file. Changes need to be present in DockerInitializeTaskParamsBuilder.

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java
> +    if (type == InfraInfo.Type.VM || type == InfraInfo.Type.DOCKER) {
This should not be any docker related changes in this file.

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java
> +    if (infraType != Infrastructure.Type.VM && infraType != Infrastructure.Type.DOCKER) {
Docker related changes should not be part of this file.

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/VmInitializeTaskUtils.java
>    public CIVmInitializeTaskParams getInitializeTaskParams(
This file should not be used anywhere. It will be deprecated and removed

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/PluginSettingUtils.java
> +    } else if (infraType == Type.VM || infraType == Type.DOCKER) {
daemon should not be off in docker

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/InfraInfoBuilder.java
> +        switch (type) {
InfraInfo is only valid for vm and docker. Don't set it for others.

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/BuildSetupUtils.java
> +        return vmInitializeTaskParamsBuilder.getDockerInitializeTaskParams(initializeStepInfo, ambiance);
Use dockerInitializeTaskParamsBuilder as discussed. This should not call vmInitializeTaskParamsBuilder

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/K8StageInfraDetails.java
> +  @NotNull private InfraInfo infraInfo;
Remove infraInfo

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java
> +  private InfraInfo infraInfo;
Remove infraInfo

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +      if (runtime != null) {
As Harsh suggested, move it to a separate method and throw exception in the new method itself. This method has become too big

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java
> +  public String getPoolName() {
This is a bean. Implementation code should not be present here. @harshjain12 what do you think?

2022-09-12 05:42 UTC, shubham149 commented on 332-ci-manager/contracts/src/main/java/io/harness/cimanager/common/StageInfraDetails.java
> +  InfraInfo getInfraInfo();
InfraInfo is only valid for VM and DOcker. Remove it from here.

2022-09-12 06:03 UTC, shubham149 commented
VMs uses host volumes but docker needs to use docker volume instead. Is this change present in this PR?

2022-09-13 03:09 UTC, happyhebaby reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373)* status: Some of the checks are too old. 1 change requests. 55. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`320-ci-execution/src/main/java/io/harness/stateutils/buildstate/BuildSetupUtils.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9V80qjeHRrFsTep5_3-r3-28:-NBXzygd8yu-L5IQJ46g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/320-ci-execution/src/main/java/io/harness/stateutils/buildstate/BuildSetupUtils.java#L28)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

320-ci-execution package does not exist. Can you rebase the code?
</blockquote></details>

Done.
___
*[`325-sto-beans/src/main/java/io/harness/beans/stages/SecurityStageConfigImpl.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcU7-r1-73:-NBY-1w_1JeNYumzb8cF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/34aa2d9346c280fba927c8d52c537d1beb59a1a3/325-sto-beans/src/main/java/io/harness/beans/stages/SecurityStageConfigImpl.java#L73)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

DockerRuntime needs to be implemented by Runtime interface
</blockquote></details>

Done.
___
*[`325-sto-beans/src/main/java/io/harness/beans/stages/SecurityStageConfigImpl.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcU7-r3-73:-NBY-G0E8_8RuWOJ0yM2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/325-sto-beans/src/main/java/io/harness/beans/stages/SecurityStageConfigImpl.java#L73)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Do not add dockerRuntime field. There should be a single runtime field
</blockquote></details>

Done.
___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/serializer/CIContractsKryoRegistrar.java` line 108 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcUA-r5-108:-NBoODSe6ix2iy9Hs5oG:b-8kj54q) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/contracts/src/main/java/io/harness/cimanager/serializer/CIContractsKryoRegistrar.java#L108)):*
<details><summary><i>Previously, vistaarjuneja (Vistaar Juneja) wrote…</i></summary><blockquote>

Do we need these Kryo changes? 
</blockquote></details>

I tested, we need the Kryo changes.
___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/stages/IntegrationStageConfigImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcUB-r1-71:-NBY-JVU1ULN1XgcI_sN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/34aa2d9346c280fba927c8d52c537d1beb59a1a3/332-ci-manager/contracts/src/main/java/io/harness/cimanager/stages/IntegrationStageConfigImpl.java#L71)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXDrg6DXHs49X0fDwI:-NBY03FO9j16wlWl0ssT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java#L50)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

van you move this to utility
Yaml should not have logic
</blockquote></details>

Done.
___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluP4-r5-50:-NBnI0LfBGVqEc1wxUgR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java#L50)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

This is a bean. Implementation code should not be present here. @harshjain12 what do you think?
</blockquote></details>

Done.
___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/runtime/DockerRuntime.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcUG-r3-41:-NBY2fsC7dagKtRHwTtR:b86j2hf) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/runtime/DockerRuntime.java#L41)):*
<details><summary><i>Previously, vistaarjuneja (Vistaar Juneja) wrote…</i></summary><blockquote>

I think we can keep the spec empty for now. Is this getting used anywhere?
</blockquote></details>

It doesn't get used right now, just keep it for future elements that could be added into.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java` line 100 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9ilmcd6G5h8AnPJdw9-r3-100:-NBY49unCW9zc0zPOkUE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java#L100)):*
<details><summary><i>Previously, vistaarjuneja (Vistaar Juneja) wrote…</i></summary><blockquote>

Set `infrastructure` directly
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9ilmcd6G5h8AnPJdw9-r3-101:-NBY7tCH2B2FvtPmIwVL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java#L101)):*
<details><summary><i>Previously, vistaarjuneja (Vistaar Juneja) wrote…</i></summary><blockquote>

Why does this have OS? It should be similar as hosted and contain platform right?
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/36373#-N9ilmcd6G5h8AnPJdw9-r4-86:-NBY42PDDyIjeNsafDPd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1ab502791ca76fbf079db2eac23a1481922eb41b/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java#L86)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

use optional
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/36373#-N9ilmcd6G5h8AnPJdw9-r4-88:-NBYCdtk9NNqYLkMPaJ5:b-68q3gz) ([raw file](https://github.com/harness/harness-core/blob/1ab502791ca76fbf079db2eac23a1481922eb41b/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java#L88)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

This is the only place this logic is used. Besides this logic involves two return variables `isValidRuntime` and `infrastructure`, unlike Python that could return multiple objects, if I want to return multiple objects then I have to define a class that capture them, or use a pair, either is less readable then keeping the logic  [...]

2022-09-13 06:17 UTC, shubham149 commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 147 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9dLpi5IiJXAqyPSAvD-r5-147:-NBpUD-O9kkYy40o_o4R:b-jg8l3f) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L147)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

We already agreed to reuse class for both vm and docker, I already used a separate function for docker within the class.
</blockquote></details>

In our last to last call, we agreed on creating DockerInitializeTaskParamsBuilder class. That class will then call this class's getVmInitializeParams method and modify any docker related changes in it. That will re-use the function and ensure that this class does not have docker related changes in it.

We should not add any docker related changes in this file. 


<!-- Sent from Reviewable.io -->

2022-09-14 17:27 UTC, happyhebaby reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373)* status: 41 file(s) to review. 1 change requests. 63. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/common/StageInfraDetails.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcU9-r5-37:-NBu7g0T-r-APxWcBRDg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/contracts/src/main/java/io/harness/cimanager/common/StageInfraDetails.java#L37)):*
<details><summary><i>Previously, vistaarjuneja (Vistaar Juneja) wrote…</i></summary><blockquote>

As discussed offline, let's make sure we are not changing existing behaviour like introducing capability checks for hosted VMs
</blockquote></details>

Done.
___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/Infrastructure.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcUF-r3-48:-NBtPp759QyecQYXLFUh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/Infrastructure.java#L48)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Also, verify whether other builds are working after this change i.e. k8, vm, hosted vm etc
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java` line 88 at r4](https://reviewable.io/reviews/harness/harness-core/36373#-N9ilmcd6G5h8AnPJdw9-r4-88:-NBpGi_K3XebkYROg2JJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1ab502791ca76fbf079db2eac23a1481922eb41b/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java#L88)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

Quickly slack with Harsh, will move to a new method.
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluP5-r5-41:-NBs2HSWD-D_-HkDedD-:b5n5bfm) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java#L41)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Remove infraInfo
</blockquote></details>

We need infraInfo as this is one of the vm cases. See the other comment.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/K8StageInfraDetails.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluP6-r5-41:-NBtPr_SB4X0bXSlLAgE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/K8StageInfraDetails.java#L41)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Remove infraInfo 
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java` line 138 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoTHixsxgbHUOci-r5-138:-NBtQf4V8gqSJoRapaL1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java#L138)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Docker related changes should not be part of this file. 
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java` line 155 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXIcZy2JWUue-jGW0H:-NBtQhrP2PAFy7iNToiv:bs4q9op) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeStepUtils.java#L155)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

move else condition  logic to new method
</blockquote></details>

Ditto.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 147 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9dLpi5IiJXAqyPSAvD-r5-147:-NBu7np-7GrE2DULgjBD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L147)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

In our last to last call, we agreed on creating DockerInitializeTaskParamsBuilder class. That class will then call this class's getVmInitializeParams method and modify any docker related changes in it. That will re-use the function and ensure that this class does not have docker related changes in it.

We should not add any docker related changes in this file. 
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/HostedVmInfraInfo.java` line 25 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPA-r5-25:-NBrx0it931jcCkD-1ny:bdgzus4) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/HostedVmInfraInfo.java#L25)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Hosted vm does not use capability check. Remove this.
</blockquote></details>

This doesn't appear to be true. Look at function `VmInitializeTaskParamsBuilder.saveStageInfraDetails`, it includes DliteVm/HostedVm case.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java` line 16 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPB-r5-16:-NBrx9cV4ilqRNZLw49W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java#L16)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Hosted vm and k8 should not be a part of this
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java` line 25 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPC-r5-25:-NBrxFPP8oBypUuy3tbw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java#L25)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

why do we need k8InfraInfo?
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPC-r5-47:-NBrxIBf4jB2iL4YWcFl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java#L47)):*
<details><summary><i>Previously, shubham149 [...]

2022-09-15 05:08 UTC, shubham149 commented
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/common/StageInfraDetails.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcU9-r5-37:-NBzY5xs-0GmCt9Tur6_:bb7y96j) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/contracts/src/main/java/io/harness/cimanager/common/StageInfraDetails.java#L37)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

InfraInfo is not valid for dlite_vm


<!-- Sent from Reviewable.io -->

2022-09-15 05:16 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java
> +  enum Type { VM, DOCKER, DLITE_VM }
InfraInfo is not valid for dlite

2022-09-15 05:16 UTC, shubham149 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/DliteVmInfraInfo.java
> +public class DliteVmInfraInfo implements InfraInfo {
Not a valid class for Dlite vm

2022-09-15 05:16 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageStepParametersPMS.java
> +  private static Infrastructure getRuntimeInfrastructure(IntegrationStageConfig integrationStageConfig) {
Better code:

`Runtime runtime = integrationStageConfig.getRuntime();
if (runtime != null && runtime.getType() == Runtime.Type.DOCKER) {
  return DockerInfraYaml.builder()
                             .spec(DockerInfraSpec.builder().platform(integrationStageConfig.getPlatform()).build())
                             .build()
}

if (runtime != null && runtime.getType() == Runtime.Type.CLOUD) {
 return HostedVmInfraYaml.builder()
                             .spec(HostedVmInfraSpec.builder().platform(integrationStageConfig.getPlatform()).build())
                             .build();
}

throw new CIStageExecutionException(
          "Infrastructure or runtime field with type Cloud or type Docker is mandatory for execution");`

2022-09-15 05:16 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java
> +    InfraInfo infraInfo = InfraInfoUtils.validateInfrastructureAndGetInfraInfo(infrastructure);
infraInfo should not be a part of getVmInitializeParams since InfraInfo is not valid for dlite. It can be set in getDirectVmInitializeTaskParams.

2022-09-15 05:19 UTC, shubham149 commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 315 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9dLpi5IiJXAqyPSAvD-r5-315:-NBz_YQq5d9F_-bAwZ4D:bpczuaq) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L315)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

Ditto, we don't need a separate class but could reuse the same vm class, later we can rename the class to something represents both vm and docker.
</blockquote></details>

We need to remove any docker references from this class.


<!-- Sent from Reviewable.io -->

2022-09-15 05:30 UTC, shubham149 commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 255 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NBzc0LqDGnYwYzHoLmw:-NBzc0LqDGnYwYzHoLmx:bpgdv9t) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L255)):*
> ```Java
>   private void saveStageInfraDetails(Ambiance ambiance, String poolId, String workDir, String harnessImageConnectorRef,
>       Map<String, String> volToMountPath, InfraInfo infraInfo) {
>     InfraInfo.Type type = infraInfo.getType();
> ```

infra info is not valid for dlite


<!-- Sent from Reviewable.io -->

2022-09-15 11:36 UTC, harshjain12 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/DliteVmInfraInfo.java
> +  @NotNull @Getter private String poolId;
why we need pool id here ?

2022-09-15 11:37 UTC, harshjain12 submitted a review, later dismissed
> Reviewed 12 of 24 files at r6, 11 of 28 files at r7, 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373)* status: 49. unresolved discussions. Waiting on team(s): sto. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8InitializeTaskParams.java` line 44 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBXLPN912fbgziw8C6A:-NC-w4Of8rrdQN96fY-c:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8InitializeTaskParams.java#L44)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

> can you make sure that backward compatibility is not breaking if delegate does not upgrade
Just want to make sure there is nothing wrong with the line. You just made a general comment that we should test backward compatibility, right?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2022-09-15 11:50 UTC, shubham149 commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/vm/CIVmInitializeTaskHandler.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9V80qjeHRrFsTep5_L-r3-156:-NC-z7CR1y9_RCW1nq3t:b270g95) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/vm/CIVmInitializeTaskHandler.java#L156)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

I had fixed the issue, but hadn't submitted the change, should be fixed with the submission of the new change.
</blockquote></details>

We cannot merge this PR without fixing this.


<!-- Sent from Reviewable.io -->

2022-09-15 11:51 UTC, shubham149 commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/CIVmConnectionCapabilityCheck.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9V80qjeHRrFsTep5_M-r5-33:-NC-zI1eDhPI24HaiojI:b-ntjx6b) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/CIVmConnectionCapabilityCheck.java#L33)):*
<details><summary><i>Previously, vistaarjuneja (Vistaar Juneja) wrote…</i></summary><blockquote>

This is meant to be done by selectors. Docker init task would have a selector present to run only on delegates publishing `linux-amd64` tag
</blockquote></details>

How will we specify the selector in the pipeline?


<!-- Sent from Reviewable.io -->

2022-09-15 11:52 UTC, shubham149 commented
*[`933-ci-commons/src/main/java/io/harness/vm/VmExecuteStepUtils.java` line 87 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NC-zWb7Ew7jGdWIxk11:-NC-zWb7Ew7jGdWIxk12:b-e0bqy3) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/933-ci-commons/src/main/java/io/harness/vm/VmExecuteStepUtils.java#L87)):*
> ```Java
>   public ExecuteStepRequestBuilder convertService(
>       VmServiceDependency params, CIVmInitializeTaskParams initializeTaskParams) {
>     String id = params.getIdentifier();
> ```

Where is id used?


<!-- Sent from Reviewable.io -->

2022-09-15 11:53 UTC, shubham149 commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPC-r5-47:-NC-zgpi2fdCctxzo76-:bgo9k6o) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/K8InfraInfo.java#L47)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

DliteVmInfraInfo does not have capability checks. Remove this since it is not valid for dlite vms.


<!-- Sent from Reviewable.io -->

2022-09-15 11:53 UTC, shubham149 commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/DliteVmInfraInfo.java` line 48 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NC-zo2J0O1k_yA8CG-w:-NC-zo2J0O1k_yA8CG-x:b-t88k7k) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/DliteVmInfraInfo.java#L48)):*
> ```Java
> 
>   @Override
>   public String fetchCapabilityBasis() {
> ```

DliteVmInfraInfo does not have capability checks. Remove this since it is not valid for dlite vms.


<!-- Sent from Reviewable.io -->

2022-09-15 11:54 UTC, shubham149 commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java` line 16 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPB-r5-16:-NC-zuOIDwEsgXW9vOuf:b-hij2cl) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java#L16)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

InfraInfo is not valid for Dlite


<!-- Sent from Reviewable.io -->

2022-09-15 11:55 UTC, shubham149 commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 1114 at r3](https://reviewable.io/reviews/harness/harness-core/36373#-N9dLpi5IiJXAqyPSAvG-r3-1114:-NC0-4SZ3l1YSkyGObhy:b-5ehmx2) ([raw file](https://github.com/harness/harness-core/blob/d560e9669d70680663039ff658b185fc44e805d6/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1114)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

This looks necessary, the presence of CIInitializeTaskParams in the kryo file also suggests this. I tested without them and hit kryo error.
</blockquote></details>

CIExecuteStepTaskParams, CIExecuteStepTaskParams.Type, CICleanupTaskParams, CICleanupTaskParams.Type should not be present here. CI builds are already working for k8 and vms.


<!-- Sent from Reviewable.io -->

2022-09-15 11:57 UTC, shubham149 commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluP5-r5-41:-NC0-_yjDa6KQB5-aRui:by3lk0x) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java#L41)):*
<details><summary><i>Previously, happyhebaby (Xun He) wrote…</i></summary><blockquote>

We need infraInfo as this is one of the vm cases. See the other comment.
</blockquote></details>

InfraInfo is not valid for dlite. So, we cannot add it for dlite.


<!-- Sent from Reviewable.io -->

2022-09-15 12:00 UTC, shubham149 reviewed
Before merging this PR, this checklist should pass:
UT coverage of over 80% for the newly added code
Automation tests for docker functionality
Parallel builds for docker functionality should work. This parallel test should include a git clone step. I think parallel builds won't work right now since we are using host volumes in docker as well. Correct me if this is not correct.
Linux K8 & Linux VM automation should pass. This will ensure that this change does not introduce any regressions.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373#-:-NC00RZV0RUl594L5vY4:bef2acm)* status: 26. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-19 16:31 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/DliteVmInitializeTaskParamsBuilder.java
> +public class DliteVmInitializeTaskParamsBuilder {
singleton

2022-09-19 16:31 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/DockerInitializeTaskParamsBuilder.java
> +public class DockerInitializeTaskParamsBuilder {
singleton

2022-09-23 04:36 UTC, harshjain12 commented
Unit tests will be covered as part of https://harness.atlassian.net/browse/CI-5602

2022-09-25 23:04 UTC, vistaarjuneja submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 19 files at r8, 5 of 56 files at r16, 4 of 71 files at r17, 22 of 69 files at r18, 48 of 48 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373#-:-NCqtE9h4uoOjg_jPucs:bnfp4nl)* status: 36. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-25 23:35 UTC, happyhebaby reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373)* status: 51 file(s) to review. 45. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/common/StageInfraDetails.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9YTOoSyevd_r-YLcU9-r5-37:-NCqxHJOCihqol_Elt-h:bpacnck) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/contracts/src/main/java/io/harness/cimanager/common/StageInfraDetails.java#L37)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

InfraInfo is not valid for dlite_vm
</blockquote></details>

I discussed in slack that dlite vm should have infrinfo, this works, and if necessary we can have further discussion and include in the rename class change later.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluP5-r5-41:-NCqxWSo5e1Jkdi2uKPI:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java#L41)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

InfraInfo is not valid for dlite. So, we cannot add it for dlite.
</blockquote></details>

Ditto
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java` line 41 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluP5-r8-41:-NCqxXtgEJQf-YKw7ULk:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/332-ci-manager/service/src/main/java/io/harness/ci/beans/sweepingoutputs/DliteVmStageInfraDetails.java#L41)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

InfraInfo is not valid for DliteVmStageInfra
</blockquote></details>

Ditto
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/BuildSetupUtils.java` line 46 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NAFzQT-7iik1BvmSJ_8-r8-46:-NCqxk76-PQRfNtC_eyv:b-wr1yw3) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/BuildSetupUtils.java#L46)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Please don't move hosted vm functionality to separate class. It should reside in vmInitializeTaskParamsBuilder
</blockquote></details>

I also discussed this in slack. If we have a separate docker class to handle docker specific logic, then we should also add one for dlite vm. It's strange and hard for reader to understand why we add one and not the other.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 315 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9dLpi5IiJXAqyPSAvD-r5-315:-NCqzb1I9xyIaXdX7yVl:b-6hf0n7) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L315)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

We need to remove any docker references from this class.
</blockquote></details>

`saveStageInfraDetails` has very high percentage of code among vm, dlite vm and docker, so I think it's better to have the statement stay.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 144 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-N9dLpi5IiJXAqyPSAvD-r8-144:-NCqyYOD-BKvUl4EwA7P:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L144)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

infraInfo should not be a part of getVmInitializeParams since InfraInfo is not valid for dlite. It can be set in getDirectVmInitializeTaskParams.
</blockquote></details>

Ditto
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 255 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NBzc0LqDGnYwYzHoLmw:-NCqy_9y1a7KfixYftMZ:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L255)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

infra info is not valid for dlite
</blockquote></details>

Ditto
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/CIVmConnectionCapabilityCheck.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-N9V80qjeHRrFsTep5_M-r5-33:-NCqypTu2awiuCVsRdoc:b-mz6c8r) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/CIVmConnectionCapabilityCheck.java#L33)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

How will we specify the selector in the pipeline?
</blockquote></details>

It will be added after we merge.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java` line 16 at r5](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPB-r5-16:-NCqzHLO9xrTspPVRzV8:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/db098e690c67b0e59984527458337b5bfc72d3aa/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java#L16)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

InfraInfo is not valid for Dlite
</blockquote></details>

Ditto
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java` line 15 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NBSwEC-AYAO0UQNluPB-r8-15:-NCqzJYS3kdJ8DJ-ILO2:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/InfraInfo.java#L15)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

InfraInfo is not valid for dlite
</blockquote></details>

Ditto
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/DliteVmInfraInfo.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NBwpogr4ARULH32fhwG-r8-24:-NCr-FJ6A1gCsbXO8xvX:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/DliteVmInfraInfo.java#L24)):*
<details><summary><i>Previously, shubham149 (Shubham Agrawal) wrote…</i></summary><blockquote>

Not a valid class for Dlite vm 
</blockquote></details>

Ditto
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/DliteVmInfraInfo.java` line 48 at r8](https://reviewable.io/reviews/harness/harness-core/36373#-NC-zo2J0O1k_yA8CG-w:-NCqzE0K6BcoP1-KRoU2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0a4af28dce567abc1a40f977c601af2e738ea241/950-delegate-tasks-beans/src/main/java/i [...]

2022-09-26 00:15 UTC, happyhebaby reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373#-:-NCr8Dev5DdSN-fjFVv9:b-814g8k)* status: 51 file(s) to review. 45. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-26 17:40 UTC, aman-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 40 files at r11, 2 of 9 files at r12, 2 of 71 files at r17, 2 of 69 files at r21, 6 of 48 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373#-:-NCZQoHl3zlPsBODhcLY:bnfp4nl)* status: 63 file(s) to review. 45. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-26 17:54 UTC, vistaarjuneja commented
@happyhebaby why are OPA changes showing in your PR?

2022-09-26 19:08 UTC, happyhebaby reviewed
I reverted the OPA change yesterday, it caused error in the vm/docker run, that's not the clean way to revert it. Just did it cleanly.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373#-:-NCvBaPsDTyLlLWMlvYh:b-ffee7i)* status: 71 file(s) to review. 45. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-26 19:53 UTC, dgarg-harness approved these changes
> Reviewed 1 of 19 files at r8, 1 of 56 files at r16, 22 of 69 files at r21, 51 of 51 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373)* status: 45. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-26 20:01 UTC, vistaarjuneja approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 22 of 69 files at r21, 44 of 51 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373#-:-NCvNxC09lyrLAn8ZEqX:bnfp4nl)* status: 45. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-26 20:04 UTC, vistaarjuneja approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373)* status: 34. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-26 20:05 UTC, vistaarjuneja approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36373#-:-NCvOoVa-pgPN1lA5uRx:bnfp4nl)* status: 34. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-26 20:15 UTC, dgarg-harness commented
Xun, will take care of a couple of pending review comments in a follow PR. Force merging this one as its getting hard to rebase due to the size of the PR.

2022-09-26 20:15 UTC, merged