[feat]: [CDS-41440]: Add ARM/BP endpoints from CG to NG
harness/harness-core pull request #36385
Opened 2022-08-15 15:50 UTC by nassergonzalez

[CDS-41440]: Add ARM/BP endpoints from CG to NG

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-15 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36385) it.</sub>

2022-08-15 15:56 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 14 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 12 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36385)

2022-08-15 16:25 UTC, abosii-harness requested changes
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 323 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIFpPDRc1OlA-XqCI:-N9XIFpQ5UrH5QBEd-cm:b-kz76kk) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L323)):*
> ```Java
> 
>   @GET
>   @Path("locations-by-subscription")
> ```

this path should be just locations, logic can be if (isNotEmpty(subscriptionId)), I don't see why we would require a new endpoint here
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIlP76dt599MtMlhS:-N9XIlP76dt599MtMlhT:bsajc98) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java#L25)):*
> ```Java
> @Value
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> ```

This is already by default PRIVATE for @Value
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIeSPA4yAeaWUB2jF:-N9XIeSPA4yAeaWUB2jG:b-6afu8l) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java#L29)):*
> ```Java
> @OwnedBy(CDP)
> @Schema(name = "AzureLocationsDTO", description = "Azure response for locations")
> ```

this space is not required
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureManagementGroupsDTO.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIpKS0btYEFPr4bYF:-N9XIpKS0btYEFPr4bYG:bsajc98) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureManagementGroupsDTO.java#L25)):*
> ```Java
> @Value
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> ```

This is already by default PRIVATE for @Value
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 250 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XJ6Tc1N0r6VmD7uxe:-N9XJ6Tc1N0r6VmD7uxf:bbwtu7f) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L250)):*
> ```Java
>     BaseNGAccess baseNGAccess =
>         azureHelperService.getBaseNGAccess(connectorRef.getAccountIdentifier(), orgIdentifier, projectIdentifier);
>     List<EncryptedDataDetail> encryptionDetails = azureHelperService.getEncryptionDetails(connector, baseNGAccess);
> ```

we need to check this, after recent changes  this call may allow access to unathorized resources. Can you check with @vlica-harness what can be done here


<!-- Sent from Reviewable.io -->

2022-08-15 16:26 UTC, abosii-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 250 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XJ6Tc1N0r6VmD7uxe:-N9XJns59EJgNxI_5woM:b-4wihx4) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L250)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

we need to check this, after recent changes  this call may allow access to unathorized resources. Can you check with @vlica-harness what can be done here
</blockquote></details>

nvm, this is not merged yet.. my bad..


<!-- Sent from Reviewable.io -->

2022-08-16 14:33 UTC, tmacari-harness requested changes
> Reviewed 4 of 11 files at r1, 2 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: 4 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceService.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b1EOzCzhShgYDKyRC:-N9b1EP-7YXDZny_pVJL:bruftu4) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceService.java#L41)):*
> ```Java
>       IdentifierRef connectorRef, String orgIdentifier, String projectIdentifier, String subscriptionId);
> 
>   AzureManagementGroupsDTO getResourceManagement(
> ```

maybe getAzureManagementGroups ?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 265 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b1bgJ0JZbL4A3XeaA:-N9b1bgJ0JZbL4A3XeaB:bd0l7ax) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L265)):*
> ```Java
>     List<EncryptedDataDetail> encryptionDetails = azureHelperService.getEncryptionDetails(connector, baseNGAccess);
>     Map<AzureAdditionalParams, String> additionalParams = new HashMap<>(Collections.emptyMap());
>     if (!Objects.equals(subscriptionId, "")) {
> ```

can be better: if (isNotEmpty(subscriptionId))
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 705 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b2fIs94hDmeHOBo_-:-N9b2fIs94hDmeHOBo_0:b-j0lf8j) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L705)):*
> ```Java
>             .locations(Arrays.stream(Region.values())
>                            .filter(region
>                                -> (AzureEnvironmentType.AZURE_US_GOVERNMENT == azureEnvironmentType)
> ```

A bit confusing, whats the condition here?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b3Z6z3R6s1bEqqMDN:-N9b3Z6z3R6s1bEqqMDO:b-xutz6l) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java#L66)):*
> ```Java
>             azureTaskParams.getEncryptionDetails(), azureTaskParams.getAzureConnector());
>       case LIST_SUBSCRIPTION_LOCATIONS:
>         if (azureTaskParams.getAdditionalParams().size() == 0) {
> ```

I think it would be more safe to check for specific property we then for size.


<!-- Sent from Reviewable.io -->

2022-08-16 15:40 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: 7 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 323 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIFpPDRc1OlA-XqCI:-N9XS8fN3kv00WU1HEGb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L323)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this path should be just locations, logic can be if (isNotEmpty(subscriptionId)), I don't see why we would require a new endpoint here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIlP76dt599MtMlhS:-N9XSI252sph8RU7w_Zr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java#L25)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is already by default PRIVATE for @Value
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIeSPA4yAeaWUB2jF:-N9XSPwbBQkFivxn76h-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureLocationsDTO.java#L29)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this space is not required
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureManagementGroupsDTO.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/36385#-N9XIpKS0btYEFPr4bYF:-N9XSV2E1b3zhq8O--3e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5252e53dcc9be4f97c1e23902ba7913d24b3545e/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos/AzureManagementGroupsDTO.java#L25)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is already by default PRIVATE for @Value
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceService.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b1EOzCzhShgYDKyRC:-N9b9BgmBB3hTyC_j2H_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceService.java#L41)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

maybe getAzureManagementGroups ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 265 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b1bgJ0JZbL4A3XeaA:-N9bAouTAu8__cT4yA_Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L265)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

can be better: if (isNotEmpty(subscriptionId))
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 705 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b2fIs94hDmeHOBo_-:-N9bBaOE4M44nDciVjdF:bs40e5a) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L705)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

A bit confusing, whats the condition here?
</blockquote></details>

Filters out the Azure_US_GOVERMENT regions unless the environment is an AZURE_US_GOVERNMENT environment type
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b3Z6z3R6s1bEqqMDN:-N9bCKMO7UdNjm3HGOhp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java#L66)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I think it would be more safe to check for specific property we then for size.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 15:50 UTC, nassergonzalez commented
trigger compile

2022-08-17 08:40 UTC, tmacari-harness requested changes
> Reviewed 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 705 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b2fIs94hDmeHOBo_-:-N9ewO2A4YWMEKhqBJBH:bxje1p3) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L705)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Filters out the Azure_US_GOVERMENT regions unless the environment is an AZURE_US_GOVERNMENT environment type
</blockquote></details>

I mean the full condition for filtering it's confusing for me: 
```(AzureEnvironmentType.AZURE_US_GOVERNMENT == azureEnvironmentType) == AzureUtils.AZURE_GOV_REGIONS_NAMES.contains(region.name())```


<!-- Sent from Reviewable.io -->

2022-08-17 09:12 UTC, tmacari-harness approved these changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-17 09:32 UTC, vlica-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java
> +      @QueryParam("subscriptionId") String subscriptionId,
Could we have @NotNull @NotEmpty for subscriptionId ?

2022-08-17 10:15 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 1 of 11 files at r1, 2 of 6 files at r2, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 258 at r5](https://reviewable.io/reviews/harness/harness-core/36385#-N9fHn2R78daTZnNhzjq:-N9fHn2S5CbvrSRH-hUs:bqpc0mc) ([raw file](https://github.com/harness/harness-core/blob/ba67cd4ee3aad6f68357afbdbe36cda023c2f4a9/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L258)):*
> ```Java
> 
>   @Override
>   public AzureLocationsDTO getLocationsBySubscription(
> ```

nit: name can be just getLocations since subscription id here is optional


<!-- Sent from Reviewable.io -->

2022-08-22 08:24 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: Some of the checks are too old. 2. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 327 at r5](https://reviewable.io/reviews/harness/harness-core/36385#-N9XBf_AQBzb966A6ILF-r5-327:-NA3bVWR9Ak_APAGHuY4:b-rx08lf) ([raw file](https://github.com/harness/harness-core/blob/ba67cd4ee3aad6f68357afbdbe36cda023c2f4a9/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L327)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

Could we have @NotNull @NotEmpty for subscriptionId ?
</blockquote></details>

Subscription is optional. If subscription is not present, we will return all the regions, and if the subscription is present we will return the regions allowed for that subscription
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java` line 705 at r3](https://reviewable.io/reviews/harness/harness-core/36385#-N9b2fIs94hDmeHOBo_-:-NA3dYAx8XRaKCt4OgxX:b-7ui6zn) ([raw file](https://github.com/harness/harness-core/blob/aa96dfa6adb420469f88f674b659e488a066b7ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureAsyncTaskHelper.java#L705)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I mean the full condition for filtering it's confusing for me: 
```(AzureEnvironmentType.AZURE_US_GOVERNMENT == azureEnvironmentType) == AzureUtils.AZURE_GOV_REGIONS_NAMES.contains(region.name())```


</blockquote></details>

Maybe we can work together here but for me it's clear:
Filter the regions where if this is an environmentType where we use AzureGoverment regions, get only the region where the name of the region matches the region


<!-- Sent from Reviewable.io -->

2022-08-22 09:03 UTC, vlica-harness submitted a review, later dismissed
> Reviewed 4 of 11 files at r1, 2 of 6 files at r2, 1 of 6 files at r4, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-22 09:11 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 4 of 11 files at r1, 2 of 6 files at r2, 1 of 6 files at r4, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-22 09:28 UTC, tmacari-harness approved these changes
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-22 10:00 UTC, nassergonzalez commented
trigger codebasehash

2022-08-22 10:01 UTC, puthrayaharness approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36385)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-22 10:05 UTC, merged