techdebt: [CDS-39200]: snow_create_update ff removed BE
harness/harness-core pull request #36410
Opened 2022-08-16 07:35 UTC by naman-goenka

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-16 07:38 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36410)

2022-08-16 12:23 UTC, hingerabhinav requested changes

2022-08-16 12:23 UTC, hingerabhinav commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  SERVICENOW_CREATE_UPDATE_NG,
lets keep the enum in code for now. UI might use it.

2022-08-16 12:23 UTC, hingerabhinav commented on pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java
>        yamlFile = yamlFile.concat("WithCreateUpdate");
Since we are cleaning up the FF, we can keep a single YAML file with the name ServiceNowApproval.yaml which will have all 3 steps. Please remove ServiceNowApprovalWithCreateUpdate.yaml as well. Then we can remove the concat line as well.

2022-08-16 12:23 UTC, hingerabhinav commented on pipeline-service/service/src/test/java/io/harness/pms/approval/ApprovalResourceImplServiceImplTest.java
>    public void testSnippetWithServiceNowCreateUpdate() throws IOException {
this test can be modified to not use FF service

2022-08-16 12:51 UTC, naman-goenka commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  SERVICENOW_CREATE_UPDATE_NG,
I have created a subtask for UI to remove that ff. We can merge this PR after the UI cleanup. Can we remove it then?

2022-08-16 13:00 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java
>        yamlFile = yamlFile.concat("WithCreateUpdate");
done

2022-08-16 14:40 UTC, naman-goenka commented
trigger messagecheck

2022-08-16 14:46 UTC, naman-goenka commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  SERVICENOW_CREATE_UPDATE_NG,
This ff is not used in UI as confirmed here https://harness.atlassian.net/browse/CDS-41883

2022-08-18 13:57 UTC, naman-goenka commented on pipeline-service/service/src/test/java/io/harness/pms/approval/ApprovalResourceImplServiceImplTest.java
>    public void testSnippetWithServiceNowCreateUpdate() throws IOException {
It doesn't use ff after modification @hingerabhinav

2022-08-21 10:54 UTC, hingerabhinav approved these changes

2022-08-22 06:26 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36410)* status: Some of the checks are too old. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-24 11:25 UTC, vaibhav-si submitted a review, later dismissed
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36410)* status: Some of the checks are too old. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-24 14:04 UTC, naman-goenka commented
trigger ti0, ti3, ti4

2022-08-25 04:57 UTC, naman-goenka commented
trigget ti0, ti2, ft1

2022-08-25 08:17 UTC, naman-goenka commented
trigget ti0, ti2, ft1

2022-08-25 17:54 UTC, naman-goenka commented
trigger ti0, ti2, ft2

2022-08-25 17:54 UTC, naman-goenka commented
trigger ti0, ti2, ft2

2022-08-25 19:33 UTC, naman-goenka commented
trigger ti0, ti2

2022-08-25 22:04 UTC, puthrayaharness approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36410)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-26 02:10 UTC, vaibhav-si approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36410)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-26 05:19 UTC, hingerabhinav approved these changes
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36410)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-26 05:21 UTC, merged