feat: [CDS-38260]: Add support for Nexus3 raw repositories
harness/harness-core pull request #36487
Opened 2022-08-17 21:53 UTC by vcalasansh

This PR adds support for Nexus3 raw repositories being configured as artifact sources in CG.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-17 21:56 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36487)

2022-08-18 13:36 UTC, vcalasansh commented
trigger messagecheck

2022-08-24 22:06 UTC, vcalasansh commented
trigger buildnum,codeformat

2022-08-25 06:16 UTC, puthrayaharness requested changes

2022-08-25 06:16 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java
> +    while (hasMoreResults) {
We can use a do while loop instead of a while loop. We do not need hasMoreResults. We can just use  `continuationToken` is not blank as a check.

2022-08-25 06:16 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java
> +              names.add(name); // todo: add limit if results are returned in descending order of lastUpdatedTs
Please remove the TODO.

2022-08-25 06:16 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java
> +  public List<BuildDetails> getPackageNamesBuildDetails(
Why can we not use the existing `getPackageVersions`?

2022-08-25 18:40 UTC, vcalasansh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36487)* status: 22 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java` line 212 at r2](https://reviewable.io/reviews/harness/harness-core/36487#-N9hn-24h-ELAjXt5kp_-r2-212:-NALC93bBeSNSavlNzIG:bqrbuvy) ([raw file](https://github.com/harness/harness-core/blob/12b2efb923fa516da2a14df44f95bdfb148d1bc3/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java#L212)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Why can we not use the existing `getPackageVersions`?
</blockquote></details>

Since Nexus3 raw repositories don't support the `version` field like some other repository formats, I had to create this `getPackageNamesBuildDetails` to populate `BuildDetails` using just the name of the artifact instead of the version. This function is basically a copy-paste of `getPackageVersions`, but instead of using `version` it uses `name`. 
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java` line 222 at r2](https://reviewable.io/reviews/harness/harness-core/36487#-N9hn-24h-ELAjXt5kp_-r2-222:-NALG6FDE2iqA98EU74e:b-mbsp8h) ([raw file](https://github.com/harness/harness-core/blob/12b2efb923fa516da2a14df44f95bdfb148d1bc3/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java#L222)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

We can use a do while loop instead of a while loop. We do not need hasMoreResults. We can just use  `continuationToken` is not blank as a check.
</blockquote></details>

Updated the code (I was just copy-pasting `getPackageVersions` before). Thank you for the suggestion!
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java` line 240 at r2](https://reviewable.io/reviews/harness/harness-core/36487#-N9hn-24h-ELAjXt5kp_-r2-240:-NALEIYM1BNGyR-2Uw3w:bf3maur) ([raw file](https://github.com/harness/harness-core/blob/12b2efb923fa516da2a14df44f95bdfb148d1bc3/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java#L240)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please remove the TODO.
</blockquote></details>

Done, thank you!
___
*[`970-api-services-beans/src/main/java/software/wings/utils/RepositoryFormat.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/36487#-N9hn-24h-ELAjXt5kpb-r2-10:-NALGVS-9W3otCtKUZ34:b-ty64z4) ([raw file](https://github.com/harness/harness-core/blob/12b2efb923fa516da2a14df44f95bdfb148d1bc3/970-api-services-beans/src/main/java/software/wings/utils/RepositoryFormat.java#L10)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please add the new format at the end. Also where do we currently use "generic"? 
</blockquote></details>

Done, thank you! "generic" is a format of Artifactory repositories, I believe they are analogous to the "raw" format of Nexus. 


<!-- Sent from Reviewable.io -->

2022-08-25 19:42 UTC, vcalasansh commented
trigger ti0,ti1

2022-08-26 06:57 UTC, puthrayaharness requested changes

2022-08-26 06:57 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java
> +    } while (continuationToken != null);
Let us use `StringUtils.isBlank(continuationToken)` rather than null checks.

2022-08-26 08:03 UTC, puthrayaharness requested changes

2022-08-26 08:03 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusServiceImpl.java
> +            case "raw":
`nuget` & `raw` have the same flow? Can you ensure `raw` is before `nuget`?

I believe `nuget` & `npm` have the same flow?

2022-08-26 08:04 UTC, puthrayaharness commented
Please get the changes PR tested before merging.

2022-08-26 12:22 UTC, vcalasansh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36487)* status: 22 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusServiceImpl.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/36487#-N9hn-24h-ELAjXt5kpZ-r3-88:-NAP5JIZ2nZz4fCvuRxp:b-9524g8) ([raw file](https://github.com/harness/harness-core/blob/4705848d01d26c38d51fc2291b9bf04cabb63d80/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusServiceImpl.java#L88)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

`nuget` & `raw` have the same flow? Can you ensure `raw` is before `nuget`?

I believe `nuget` & `npm` have the same flow?
</blockquote></details>

All 3 `nuget` `raw` and `npm` have the same flow here. I put `raw` before `nuget` and removed the repeated code here. Thank you for noticing this! 
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java` line 260 at r3](https://reviewable.io/reviews/harness/harness-core/36487#-N9hn-24h-ELAjXt5kp_-r3-260:-NAP5_Rp2uJzM5cI7Iv2:bb5rwpx) ([raw file](https://github.com/harness/harness-core/blob/4705848d01d26c38d51fc2291b9bf04cabb63d80/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java#L260)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Let us use `StringUtils.isBlank(continuationToken)` rather than null checks.
</blockquote></details>

Done, thank you for the suggestion!


<!-- Sent from Reviewable.io -->

2022-08-26 12:32 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusServiceImpl.java
> +  public List<BuildDetails> getPackageNames(
This is only getting called from test cases. Did you mean add it to the switch case?

2022-08-26 12:43 UTC, vcalasansh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36487)* status: 22 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusServiceImpl.java` line 206 at r4](https://reviewable.io/reviews/harness/harness-core/36487#-N9hn-24h-ELAjXt5kpZ-r4-206:-NAPA7ux-1lcDAuJ6_k6:b-500f4i) ([raw file](https://github.com/harness/harness-core/blob/463af48ff61a9b45c37fc324ad63b27e09380e9d/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusServiceImpl.java#L206)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

This is only getting called from test cases. Did you mean add it to the switch case? 
</blockquote></details>

This `getPackageNames` is getting called on line 124 of NexusBuildServiceImpl.java. This is ok, right?


<!-- Sent from Reviewable.io -->

2022-08-26 17:44 UTC, vcalasansh commented
trigger ti0

2022-08-29 13:32 UTC, vcalasansh commented
trigger ti0

2022-09-01 15:11 UTC, puthrayaharness approved these changes
> Reviewed 17 of 21 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36487)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-01 16:19 UTC, vcalasansh commented
trigger ti2,ti4,ft2

2022-09-02 06:54 UTC, puthrayaharness approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36487)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-02 06:54 UTC, puthrayaharness commented
trigger codebasehash

2022-09-02 11:36 UTC, merged

2022-09-02 17:59 UTC, abhinav-harness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/NexusThreeServiceImpl.java
> +    log.info("After sorting alphanumerically names {}", names);
we can reduce one of the log