[PL-25548]: adding encryptor and delegate tasks
harness/harness-core pull request #36553
Opened 2022-08-20 11:28 UTC by shreyas-harness

## Describe your changes
Added encryptor and delegate task for custom secret manager. 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-20 11:32 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 2 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36553)

2022-08-22 08:53 UTC, meenakshi-harness requested changes

2022-08-22 08:53 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImplTest.java
> +            vaultEncryptorsRegistry, customEncryptorsRegistry, ngVaultService, customSecretManagerHelper);
Add test for Custom SM

2022-08-22 08:53 UTC, meenakshi-harness commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +    mapBinder.addBinding(TaskType.VALIDATE_CUSTOM_SECRET_MANAGER_SECRET_REFERENCE)
Why we create new Task type for Validation? Can't we use existing and add case for Custom SM in it?

2022-08-22 08:53 UTC, meenakshi-harness commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +    mapBinder.addBinding(TaskType.FETCH_CUSTOM_SECRET).toInstance(FetchCustomSecretTask.class);
same

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/FetchCustomSecretTask.java
> +        EncryptedDataParams.builder().name("resolvedScript").value(resolvedScript).build());
Why we need to again reset and rename `script` params to `resolvedScript`?

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ResolveCustomSecretManagerConfigTask.java
> +    return ValidateCustomSecretManagerSecretReferenceTaskResponse.builder().script(parameters1.getScript()).build();
We can add check for script is null --> then print error

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ResolveCustomSecretManagerConfigTask.java
> +    ValidateCustomSecretManagerSecretReferenceTaskParameters parameters1 =
rename this

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ValidateCustomSecretManagerSecretReferenceTask.java
> +        EncryptedDataParams.builder().name("resolvedScript").value(resolvedScript).build());
Same as above why?

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ValidateCustomSecretManagerSecretReferenceTask.java
> +    boolean isReferenceValid = customEncryptor.validateReference(
can rename this variable

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ValidateCustomSecretManagerSecretReferenceTaskParameters.java
> +  @Expression(ALLOW_SECRETS) String script;
These look similar to FetchSecretTaskParamenters. Can we create a common parameter and use it everywhere

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +      String errorMessage = "Could not retrieve secret with the given parameters due to error in shell script.";
Take error message from `ShellScriptTaskResponseNG` itself.  We can also pass status in case of failure

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +    String result = shellExecutionData.getSweepingOutputEnvVariables().get(OUTPUT_VARIABLE);
OUTPUT_VARIABLE should be taken from user input and not fixed value

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +        (ShellExecutionData) shellScriptTaskResponseNG.getExecuteCommandResponse().getCommandExecutionData();
check for NullPointerException here `shellScriptTaskResponseNG.getExecuteCommandResponse()`

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +    if (isEmpty(result) || result.equals("null")) {
Why we need "null" check?

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java
> +    int expressionFunctorToken = Integer.parseInt(getParameter("expressionFunctorToken", params));
add constant

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java
> +    return encryptedDataParamsSet.stream().filter(x -> x.getName().equals(parameterName)).findFirst().get().getValue();
why these methods are public?

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java
> +    return getParameter(parameterName, encryptedRecord.getParameters());
Also we can use 1 only

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java
> +    return encryptedDataParamsSet.stream().filter(x -> x.getName().equals(parameterName)).findFirst().get().getValue();
This looks like a helper method ... can be moved out and reused at all places

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerEncryptorHelper.java
> +      abstractions.put("projectIdentifier", ngAccess.getProjectIdentifier());
constants

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerEncryptorHelper.java
> +      abstractions.put("orgIdentifier", ngAccess.getOrgIdentifier());
Why we need these ?

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerEncryptorHelper.java
> +  public boolean validateCustomSecretManagerSecretReference(String accountId, int expressionFunctorToken,
check if we can re-use existing methods, task and response classes

2022-08-22 08:53 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/software/wings/service/impl/security/NGEncryptorServiceImpl.java
> +        value = customEncryptor.fetchSecretValue(accountIdentifier, encryptedData, secretManagerConfig);
Check this flow once .. why we don't need any resolution code to be called from here?

2022-08-22 08:53 UTC, meenakshi-harness commented on 930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java
> +        .outputVars(Collections.singletonList(OUTPUT_VARIABLE))
Dont set OUTPUT_VARIABLES with constant .. use it from template DTO/runtimeinputs

2022-08-22 11:32 UTC, shreyas-harness commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +    mapBinder.addBinding(TaskType.VALIDATE_CUSTOM_SECRET_MANAGER_SECRET_REFERENCE)
I think its better to have these as single combination.  
Task - TaskParameter - Task Response 
This will avoid confusion. 
For VALIDATE_CUSTOM_SECRET_MANAGER_SECRET_REFERENCE - it needs to use different task parameter and so different task

2022-08-22 11:40 UTC, shreyas-harness commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +    mapBinder.addBinding(TaskType.FETCH_CUSTOM_SECRET).toInstance(FetchCustomSecretTask.class);
Same as above.

2022-08-22 11:41 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/FetchCustomSecretTask.java
> +        EncryptedDataParams.builder().name("resolvedScript").value(resolvedScript).build());
Script field is coming from parameters. We are adding it in Encryption data here.

2022-08-22 11:41 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ResolveCustomSecretManagerConfigTask.java
> +    return ValidateCustomSecretManagerSecretReferenceTaskResponse.builder().script(parameters1.getScript()).build();
Script is now marked with not null

2022-08-22 11:42 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ValidateCustomSecretManagerSecretReferenceTask.java
> +        EncryptedDataParams.builder().name("resolvedScript").value(resolvedScript).build());
We want to pass script as part of encrypted data

2022-08-22 11:58 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +    String result = shellExecutionData.getSweepingOutputEnvVariables().get(OUTPUT_VARIABLE);
Shouldn't output be fixed as "secret" ?

2022-08-22 12:00 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerEncryptorHelper.java
> +      abstractions.put("orgIdentifier", ngAccess.getOrgIdentifier());
NG Access should have it for secret decryption within the script

2022-08-22 12:18 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +        (ShellExecutionData) shellScriptTaskResponseNG.getExecuteCommandResponse().getCommandExecutionData();
Will not be null.

2022-08-22 12:41 UTC, shreyas-harness commented on 890-sm-core/src/main/java/software/wings/service/impl/security/NGEncryptorServiceImpl.java
> +        value = customEncryptor.fetchSecretValue(accountIdentifier, encryptedData, secretManagerConfig);
This is being called from manager side

2022-08-22 12:41 UTC, shreyas-harness commented on 930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java
> +        .outputVars(Collections.singletonList(OUTPUT_VARIABLE))
Output for Script should be secret.

2022-08-23 02:54 UTC, shreyas-harness commented on 930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java
> +        .outputVars(Collections.singletonList(OUTPUT_VARIABLE))
Can we have call on this ? 
If we allow other output vars, what will we return when we call customEncryptor.fetchSecretValue ? 
This has to be one value we are returning

2022-08-23 07:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36553) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36553) before we can accept your contribution.<br/>**41** out of **42** committers have signed the CLA.<br/><br/>:white_check_mark: HenAmar<br/>:white_check_mark: VikasMaddukuriHarness<br/>:white_check_mark: mohitg0795<br/>:white_check_mark: bhavya181<br/>:white_check_mark: abhinav-harness<br/>:white_check_mark: lovish1999<br/>:white_check_mark: shreyas-harness<br/>:white_check_mark: sahilhindwani-harness<br/>:white_check_mark: trunapushpa<br/>:white_check_mark: lasdox<br/>:white_check_mark: gaurav-jain1<br/>:white_check_mark: Y0709<br/>:white_check_mark: raghavharness<br/>:white_check_mark: vikyathharekal<br/>:white_check_mark: namanvermah<br/>:white_check_mark: abosii-harness<br/>:white_check_mark: pbarapatre10<br/>:white_check_mark: nassergonzalez<br/>:white_check_mark: adivishy1<br/>:white_check_mark: tmacari-harness<br/>:white_check_mark: ivan-83<br/>:white_check_mark: Abhishek-CDC<br/>:white_check_mark: bojanmicovic<br/>:white_check_mark: DeepakPatankar<br/>:white_check_mark: Xin-Harness<br/>:white_check_mark: vitsafronovici<br/>:white_check_mark: rafaelmart1ns<br/>:white_check_mark: thomas-grasman<br/>:white_check_mark: ujjawal-harness<br/>:white_check_mark: acasian-harness<br/>:white_check_mark: brijeshdhakar<br/>:white_check_mark: kapil-harness<br/>:white_check_mark: yogesh-chauhan<br/>:white_check_mark: vladimir-peric<br/>:white_check_mark: gn-harness<br/>:white_check_mark: GabeAboy<br/>:white_check_mark: namantalaycha10<br/>:white_check_mark: jennyjames21<br/>:white_check_mark: tchaurasiya<br/>:white_check_mark: shalini-agr<br/>:white_check_mark: dhruv-harness<br/>:x: bot-harness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36553) it.</sub>

2022-08-23 07:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=36553) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=36553) before we can accept your contribution.<br/>**41** out of **42** committers have signed the CLA.<br/><br/>:white_check_mark: HenAmar<br/>:white_check_mark: VikasMaddukuriHarness<br/>:white_check_mark: mohitg0795<br/>:white_check_mark: abhinav-harness<br/>:white_check_mark: bhavya181<br/>:white_check_mark: lovish1999<br/>:white_check_mark: lasdox<br/>:white_check_mark: gaurav-jain1<br/>:white_check_mark: trunapushpa<br/>:white_check_mark: shreyas-harness<br/>:white_check_mark: pbarapatre10<br/>:white_check_mark: abosii-harness<br/>:white_check_mark: Y0709<br/>:white_check_mark: sahilhindwani-harness<br/>:white_check_mark: vikyathharekal<br/>:white_check_mark: namanvermah<br/>:white_check_mark: DeepakPatankar<br/>:white_check_mark: Abhishek-CDC<br/>:white_check_mark: nassergonzalez<br/>:white_check_mark: raghavharness<br/>:white_check_mark: ivan-83<br/>:white_check_mark: rafaelmart1ns<br/>:white_check_mark: Xin-Harness<br/>:white_check_mark: kapil-harness<br/>:white_check_mark: tmacari-harness<br/>:white_check_mark: brijeshdhakar<br/>:white_check_mark: adivishy1<br/>:white_check_mark: bojanmicovic<br/>:white_check_mark: vitsafronovici<br/>:white_check_mark: thomas-grasman<br/>:white_check_mark: jennyjames21<br/>:white_check_mark: ujjawal-harness<br/>:white_check_mark: gn-harness<br/>:white_check_mark: vladimir-peric<br/>:white_check_mark: GabeAboy<br/>:white_check_mark: yogesh-chauhan<br/>:white_check_mark: acasian-harness<br/>:white_check_mark: shalini-agr<br/>:white_check_mark: dhruv-harness<br/>:white_check_mark: tchaurasiya<br/>:white_check_mark: namantalaycha10<br/>:x: bot-harness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=36553) it.</sub>

2022-08-23 07:34 UTC, shreyas-harness commented
trigger ft1

2022-08-23 08:23 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java
> +            log.info("Secret manager type is custom");
Done

2022-08-23 08:24 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ResolveCustomSecretManagerConfigTask.java
> +    ValidateCustomSecretManagerSecretReferenceTaskParameters parameters1 =
Done

2022-08-23 08:24 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/delegatetasks/ValidateCustomSecretManagerSecretReferenceTaskParameters.java
> +  @Expression(ALLOW_SECRETS) String script;
Lets. have {task, task parameter, task response} as one set for now. 
We can do it in follow up pr if needed.

2022-08-23 08:25 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +      String errorMessage = "Could not retrieve secret with the given parameters due to error in shell script.";
Done

2022-08-23 08:25 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +    String result = shellExecutionData.getSweepingOutputEnvVariables().get(OUTPUT_VARIABLE);
Discussed offline. 
Agreed to let it remain fixed for now. 
Since secret manager expects output to be secret and not any variable.

2022-08-23 08:26 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java
> +    return encryptedDataParamsSet.stream().filter(x -> x.getName().equals(parameterName)).findFirst().get().getValue();
Done

2022-08-23 08:26 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java
> +    int expressionFunctorToken = Integer.parseInt(getParameter("expressionFunctorToken", params));
Done

2022-08-23 08:26 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerEncryptorHelper.java
> +      abstractions.put("projectIdentifier", ngAccess.getProjectIdentifier());
Done

2022-08-23 08:26 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerEncryptorHelper.java
> +  public boolean validateCustomSecretManagerSecretReference(String accountId, int expressionFunctorToken,
Same as above about set of ( task, params ,response )

2022-08-23 08:27 UTC, shreyas-harness commented on 930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java
> +        .outputVars(Collections.singletonList(OUTPUT_VARIABLE))
Discussed offline. 
Script needs to have secret as output variable for now.

2022-08-23 08:41 UTC, shreyas-harness commented
trigger messagecheck

2022-08-23 09:05 UTC, meenakshi-harness requested changes

2022-08-23 09:05 UTC, meenakshi-harness commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +    mapBinder.addBinding(TaskType.FETCH_CUSTOM_SECRET).toInstance(FetchCustomSecretTask.class);
We can discuss this later

2022-08-23 09:05 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGConnectorSecretManagerServiceImpl.java
> +        customSecretManagerHelper.prepareEncryptedDataParamsSet(customNGSecretManagerConfigDTO);
Are we preparing encrypted param set from secret input here?
Can you check this logic and comment on line 120

2022-08-23 09:05 UTC, meenakshi-harness commented on 878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptBaseDTO.java
> +  @ApiModelProperty(required = true) @NotNull @EntityIdentifier String orgIdentifier;
Why have you added these changes back?

2022-08-23 09:05 UTC, meenakshi-harness commented on 878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptBaseDTO.java
> +  @ApiModelProperty(required = true) @NotNull @EntityIdentifier String projectIdentifier;
remove

2022-08-23 11:00 UTC, shreyas-harness commented on 878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptBaseDTO.java
> +  @ApiModelProperty(required = true) @NotNull @EntityIdentifier String orgIdentifier;
Reverted

2022-08-23 11:00 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGConnectorSecretManagerServiceImpl.java
> +        customSecretManagerHelper.prepareEncryptedDataParamsSet(customNGSecretManagerConfigDTO);
Done

2022-08-23 11:31 UTC, meenakshi-harness requested changes

2022-08-23 11:31 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/NGConnectorSecretManagerServiceImpl.java
> +        customSecretManagerHelper.prepareEncryptedDataParamsSet(customNGSecretManagerConfigDTO);
This is not correct logic, as discussed change in last PR.

2022-08-23 11:31 UTC, meenakshi-harness commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/ShellScriptTaskHandlerNG.java
> +      log.info("Value of secret is " + executeCommandResponse.getCommandExecutionData());
Remove

2022-08-23 11:36 UTC, shreyas-harness commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/ShellScriptTaskHandlerNG.java
> +      log.info("Value of secret is " + executeCommandResponse.getCommandExecutionData());
Done

2022-08-23 11:39 UTC, meenakshi-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 17 of 30 files at r1, 19 of 21 files at r3, 7 of 7 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36553#-:-NA9UwWBCXfku89Md3Jr:bnfp4nl)* status: 46 file(s) to review. 21. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-23 12:20 UTC, piyush-harness commented
Approving only for codebase hashcheck. Do not have context around all the changes on this 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 





<!-- Sent from Reviewable.io -->

2022-08-23 13:02 UTC, shreyas-harness commented
trigger codebasehash

2022-08-23 13:17 UTC, piyush-harness approved these changes
> Reviewed 17 of 30 files at r1, 19 of 21 files at r3, 7 of 7 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36553)* status: 23. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-23 13:17 UTC, piyush-harness commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-08-23 13:23 UTC, shreyas-harness commented
trigger codebasehash

2022-08-23 13:43 UTC, puthrayaharness approved these changes

2022-08-23 13:44 UTC, merged