[feat]: [PL-19821]: csm conn dto map
harness/harness-core pull request #36576
Opened 2022-08-22 03:09 UTC by shreyas-harness

## Describe your changes
CSM connector dto , config, and mappers. 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-22 03:16 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 9 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 9 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36576)

2022-08-22 06:05 UTC, shreyas-harness commented
trigger messagecheck

2022-08-22 06:13 UTC, meenakshi-harness requested changes

2022-08-22 06:13 UTC, meenakshi-harness commented on 440-connector-nextgen/BUILD.bazel
> +        "//platform-service/modules/notification-service/contracts:module",
why added this?

2022-08-22 06:13 UTC, meenakshi-harness commented on 440-connector-nextgen/BUILD.bazel
> +        "//platform-service/modules/notification-service/contracts:module",
same?

2022-08-22 06:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/customsecretmanager/CustomSecretManagerConnector.java
> +@ToString(exclude = {"connectorRef"})
Why have we excluded connectorRef here?

2022-08-22 06:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    log.info("Yaml received from template service is \n" + mergedYaml);
Remove this

2022-08-22 06:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    log.info("Resolved script is " + script);
remove

2022-08-22 06:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    String script = shellScriptBaseDTO.getShellScriptSpec().getSource().getSpec().getScript().getValue();
Check if we can get NullPointerException here, else handle it

2022-08-22 06:39 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    encryptedDataParamsSet.add(EncryptedDataParams.builder().name("Script").value(script).build());
Create constant for `Script` and `expressionFunctorToken`

2022-08-22 06:39 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java
> +          .addAll(NGCommonModuleRegistrars.kryoRegistrars)
why we need this ?

2022-08-22 06:39 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java
> +          .addAll(NGCommonModuleRegistrars.springConverters)
same ?

2022-08-22 06:39 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java
> +          .add(NotificationBeansKryoRegistrar.class)
Why?

2022-08-22 06:39 UTC, meenakshi-harness commented on 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/CustomSecretManagerDTOToEntityTest.java
> +    }
Add tests for conversion of DTO to Entity with proper data

2022-08-22 06:39 UTC, meenakshi-harness commented on 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/CustomSecretManagerEntityToDTOTest.java
> +    }
Same here

2022-08-22 06:39 UTC, meenakshi-harness commented on 440-connector-nextgen/src/test/resources/schema/Connectors/all.json
> +          "type": "object",
this should not come as object ... it throws error in UI. Check in Pipeline all.json what type is send here

2022-08-22 06:39 UTC, meenakshi-harness commented on 890-sm-core/src/main/java/io/harness/ng/CustomSecretManagerConfigDTOMapper.java
> +      builder.connectorRef(String.valueOf(connectorDTO.getConnectorRef().getDecryptedValue()));
Why we setting this with decrypted value?

2022-08-22 06:39 UTC, meenakshi-harness commented on 940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/CustomSecretManagerConfigDTO.java
> +  @Schema(description = SecretManagerDescriptionConstants.CUSTOM_AUTH_TOKEN) private String connectorRef;
Don't we need SecretRef annotation here?

2022-08-22 06:39 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/customsecretmanager/CustomSecretManagerConnectorDTO.java
> +  @JsonProperty("onDelegate") @Builder.Default Boolean executeOnDelegate = true;
This should be required field. and remove default value.

2022-08-22 06:40 UTC, meenakshi-harness commented on 970-api-services-beans/src/main/java/io/harness/security/encryption/EncryptionType.java
> +  ;
fix this formatting

2022-08-22 07:54 UTC, shreyas-harness commented
trigger messagecheck

2022-08-22 10:12 UTC, shreyas-harness commented on 440-connector-nextgen/BUILD.bazel
> +        "//platform-service/modules/notification-service/contracts:module",
This was added because Kryo registration error was coming for NotificationBeansKryoRegistrar

2022-08-22 10:12 UTC, shreyas-harness commented on 440-connector-nextgen/BUILD.bazel
> +        "//platform-service/modules/notification-service/contracts:module",
Same as above

2022-08-22 10:13 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/customsecretmanager/CustomSecretManagerConnector.java
> +@ToString(exclude = {"connectorRef"})
So that connector ref is not printed when to string is called on object anywhere.

2022-08-22 10:14 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    log.info("Yaml received from template service is \n" + mergedYaml);
Why do we want remove it ? 
It will be helpful during bug fixes.

2022-08-22 10:16 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java
> +          .addAll(NGCommonModuleRegistrars.kryoRegistrars)
Thats the standard way I believe since we have added bazel dependency.

2022-08-22 10:16 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java
> +          .addAll(NGCommonModuleRegistrars.springConverters)
same

2022-08-22 10:16 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java
> +          .add(NotificationBeansKryoRegistrar.class)
Mentioned above

2022-08-22 10:17 UTC, shreyas-harness commented on 440-connector-nextgen/src/test/resources/schema/Connectors/all.json
> +          "type": "object",
this file is auto-generated.

2022-08-22 10:19 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    String script = shellScriptBaseDTO.getShellScriptSpec().getSource().getSpec().getScript().getValue();
We have NonNull annotation all upto script. 
So null pointer exception shouldn't come

2022-08-22 10:43 UTC, shreyas-harness commented on 890-sm-core/src/main/java/io/harness/ng/CustomSecretManagerConfigDTOMapper.java
> +      builder.connectorRef(String.valueOf(connectorDTO.getConnectorRef().getDecryptedValue()));
Adding encrypted annotation in config.

2022-08-22 13:57 UTC, meenakshi-harness commented on 440-connector-nextgen/BUILD.bazel
> +        "//platform-service/modules/notification-service/contracts:module",
Did we not removed this?

2022-08-22 14:16 UTC, shreyas-harness commented on 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/CustomSecretManagerDTOToEntityTest.java
> +    }
We can add in a followup PR. the existing cases checks for all default values.

2022-08-22 14:17 UTC, meenakshi-harness reviewed
> Reviewed 13 of 37 files at r1, 3 of 3 files at r2, 13 of 18 files at r3, 1 of 1 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576)* status: 37 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/test/resources/schema/Connectors/all.json` line 5204 at r2](https://reviewable.io/reviews/harness/harness-core/36576#-NA2WjUYn_KrmCpMlBD1-r2-5204:-NA4uQcADMwOhHVKgZ34:b46qw2x) ([raw file](https://github.com/harness/harness-core/blob/7e4777c6ea16cc619a48a3ce868bf28788493938/440-connector-nextgen/src/test/resources/schema/Connectors/all.json#L5204)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

this file is auto-generated.
</blockquote></details>

Yes we'll need to check this in follow up Pr


<!-- Sent from Reviewable.io -->

2022-08-22 14:18 UTC, meenakshi-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576)* status: 37 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-22 16:30 UTC, shreyas-harness commented
trigger ti4

2022-08-22 17:21 UTC, meenakshi-harness approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576)* status: 37 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-23 02:19 UTC, piyush-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 37 files at r1, 2 of 3 files at r2, 13 of 18 files at r3, 1 of 1 files at r4, 7 of 7 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576#-:-NA7Uuo69WWeD-YbzsYf:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-23 03:41 UTC, shreyas-harness commented
trigger ti4

2022-08-23 03:45 UTC, shreyas-harness commented
trigger ti1

2022-08-23 04:53 UTC, shreyas-harness commented on 440-connector-nextgen/BUILD.bazel
> +        "//platform-service/modules/notification-service/contracts:module",
Removed

2022-08-23 04:53 UTC, shreyas-harness commented on 440-connector-nextgen/BUILD.bazel
> +        "//platform-service/modules/notification-service/contracts:module",
Removed

2022-08-23 04:53 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    log.info("Resolved script is " + script);
Removed

2022-08-23 04:53 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +    encryptedDataParamsSet.add(EncryptedDataParams.builder().name("Script").value(script).build());
Done

2022-08-23 04:54 UTC, shreyas-harness commented on 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/CustomSecretManagerEntityToDTOTest.java
> +    }
Same as above

2022-08-23 04:54 UTC, shreyas-harness commented on 940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/CustomSecretManagerConfigDTO.java
> +  @Schema(description = SecretManagerDescriptionConstants.CUSTOM_AUTH_TOKEN) private String connectorRef;
Its DTO, not needed

2022-08-23 04:54 UTC, shreyas-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/customsecretmanager/CustomSecretManagerConnectorDTO.java
> +  @JsonProperty("onDelegate") @Builder.Default Boolean executeOnDelegate = true;
Done

2022-08-23 04:54 UTC, shreyas-harness commented on 970-api-services-beans/src/main/java/io/harness/security/encryption/EncryptionType.java
> +  ;
Done

2022-08-23 05:04 UTC, meenakshi-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576#-:-NA84Riv-oAPfjieSlaC:bnfp4nl)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-23 05:31 UTC, meenakshi-harness commented
`OwnedBy(PL)` in follow up PRs

2022-08-23 05:40 UTC, nishantsaini20 approved these changes
> Reviewed 13 of 37 files at r1, 1 of 3 files at r2, 13 of 18 files at r3, 1 of 1 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-23 06:09 UTC, piyush-harness approved these changes
> Reviewed 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-23 06:09 UTC, piyush-harness commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-08-23 06:11 UTC, shreyas-harness commented
trigger codebasehash

2022-08-23 06:20 UTC, meenakshi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36576)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-23 06:20 UTC, merged