[feat]: [CDS-41422]: Add unittest to AzureSteps
harness/harness-core pull request #36722
Opened 2022-08-24 10:17 UTC by nassergonzalez

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-24 10:21 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 19 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 3 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 16 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36722)

2022-08-25 12:57 UTC, tmacari-harness requested changes
> Reviewed 8 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJn-c4-8ECiwsu4Pmg:-NAJn-c4-8ECiwsu4Pmh:b-yfeb2c) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L65)):*
> ```Java
> import org.powermock.api.mockito.PowerMockito;
> 
> public class AzureCommonHelperTest extends CategoryTest {
> ```

missed OwnedBy
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK1oZD9vOEjAykCOds:-NAK1ZoODdswgk7uIkJ6:b-imjpmr) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L130)):*
> ```Java
>     GitStoreDelegateConfig response =
>         azureCommonHelper.getGitStoreDelegateConfig(store, azureHelperTest.getAmbiance(), paths);
>     assertThat(response.getGitConfigDTO().getConnectorType()).isEqualTo(ConnectorType.GIT);
> ```

We could add more assertions.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJye9B7_d-UAM08Y3o:-NAJye9C0msCEk8SKuGz:b-9tpqlx) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L149)):*
> ```Java
>     assertThat(azureCommonHelper.hasGitStoredParameters(parameters)).isTrue();
>   }
>   @Test
> ```

add empty line
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK0mVE3ztZUSK8NXMX:-NAK0mVFB2mrQIZyE9aa:b-l4jggq) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L176)):*
> ```Java
>     TaskChainResponse result = azureCommonHelper.getGitFetchFileTaskChainResponse(
>         azureHelperTest.getAmbiance(), files, stepElementParameters, azureCreateARMResourcePassThroughData);
>     assertThat(result.isChainEnd()).isFalse();
> ```

I think we can do more asserts on tat method, for example that it will set passThroughData, and expected taskRequest.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJzj5t23uPdiMFcDT7:-NAJzj5t23uPdiMFcDT8:bxfhvpk) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L32)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> ```

why do we need empty line?
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK-8EI66qNaY-FZOKI:-NAK-8EI66qNaY-FZOKJ:bxb8zux) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L47)):*
> ```Java
>             .build();
> 
>     AzureTemplateFile templateFileBuilder = new AzureTemplateFile();
> ```

it is not a builder
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJzox7-vFOOjT5LiAx:-NAJzox7-vFOOjT5LiAy:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L76)):*
> ```Java
>     assertThat(azureCreateStepInfo.getCreateStepConfiguration().getConnectorRef().getValue()).isEqualTo("connectorRef");
>   }
>   @Test
> ```

please add empty line
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 186 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK1xbs8-ioNosSTqYf:-NAK1xbs8-ioNosSTqYg:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L186)):*
> ```Java
>     assertThatThrownBy(azureCreateStepInfo::validateSpecParameters).hasMessageContaining("Scope can't be empty");
>   }
>   @Test
> ```

please add empty line
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK2-5XAKpo-wvqPiTp:-NAK2-5XAKpo-wvqPiTq:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L216)):*
> ```Java
>     assertThatThrownBy(azureCreateStepInfo::validateSpecParameters).hasMessageContaining("subscription can't be null");
>   }
>   @Test
> ```

Same here
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 246 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK20j5BMb2SjfX1D5J:-NAK20j5BMb2SjfX1D5K:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L246)):*
> ```Java
>     assertThatThrownBy(azureCreateStepInfo::validateSpecParameters).hasMessageContaining("resourceGroup can't be null");
>   }
>   @Test
> ```

same here
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK2AOUDIbgsyhOEkf1:-NAK2AOUDIbgsyhOEkf2:b-10fnb0) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L82)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> ```

no deed for empty line
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 402 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK2griCdlJLXSQ0x2d:-NAK2griCdlJLXSQ0x2e:b-928zzo) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L402)):*
> ```Java
>     assertThat(taskDataArgumentCaptor.getValue().getTaskType()).isEqualTo(TaskType.AZURE_NG_ARM.name());
>     assertThat(taskSelectorsArgumentCaptor.getValue().get(0).getSelector()).isEqualTo("create-d-selector-1");
>   }
> ```

Empty line
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateBPStepInfoTest.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK2mLZ1KvYpbTbqu2O:-NAK2mLZ1KvYpbTbqu2P:bpv6kja) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateBPStepInfoTest.java#L31)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> ```

Empty lin [...]

2022-08-25 13:41 UTC, vlica-harness commented on 125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java
> +    PowerMockito.when(StepUtils.prepareCDTaskRequest(any(), any(), any(), any(), any(), any(), any()))
on line above you use Mockito to mockStatic but use PowerMockito to stub a method,
can we please use only Mockito where is  possible? I think there was some issues with coverage when PowerMockito and sonar.

2022-08-25 14:03 UTC, vlica-harness commented
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAKJ6_w0x8X1l3pCB6a:-NAKJ6_w0x8X1l3pCB6b:b-qrh5r8) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L20)):*
> ```Java
> import static org.mockito.Mockito.times;
> import static org.mockito.Mockito.verify;
> import static org.powermock.api.mockito.PowerMockito.when;
> ```

same here, would be better to use Mockito for when stubing...


<!-- Sent from Reviewable.io -->

2022-08-26 08:14 UTC, tmacari-harness reviewed
> Reviewed 4 of 8 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-26 08:59 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJn-c4-8ECiwsu4Pmg:-NAK9obN8m8MRi_7cgFA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L65)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

missed OwnedBy
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK1oZD9vOEjAykCOds:-NAKCj6l4ORVF3AnYO7r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L130)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We could add more assertions.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJye9B7_d-UAM08Y3o:-NAKCpY46ey0KUxLRXoi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L149)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

add empty line
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAELyq3PuOSsVsOfiNQ-r1-172:-NAKKmwn-hYXq0rWUYT8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L172)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

on line above you use Mockito to mockStatic but use PowerMockito to stub a method,
can we please use only Mockito where is  possible? I think there was some issues with coverage when PowerMockito and sonar. 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK0mVE3ztZUSK8NXMX:-NAKMIx_46kOWYaY5_in:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java#L176)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I think we can do more asserts on tat method, for example that it will set passThroughData, and expected taskRequest.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJzj5t23uPdiMFcDT7:-NAKDWMZ4_YT_-F2mxmY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L32)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why do we need empty line?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK-8EI66qNaY-FZOKI:-NAKQ7gQ-3j9mNlU7LNx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L47)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

it is not a builder
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAJzox7-vFOOjT5LiAx:-NAKQGaoBim0a635RuUO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L76)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 186 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK1xbs8-ioNosSTqYf:-NAKQHAO28FHn3n5eNS4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L186)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK2-5XAKpo-wvqPiTp:-NAKQHo20A2ZoRTlrtjk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L216)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java` line 246 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK20j5BMb2SjfX1D5J:-NAKQI9Y-1IC7k1t74q-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepInfoTest.java#L246)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAKJ6_w0x8X1l3pCB6a:-NAKRXG32iO2nHzSoAuS:b-a9d2nw) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L20)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

same here, would be better to use Mockito for when stubing...
</blockquote></details>

I can replace the when but for the verifyStatic that is the only one that i know how to use
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK2AOUDIbgsyhOEkf1:-NAKTERSC9zf_XHjnbdk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L82)):*
<details><summary><i>Previously, tmacar [...]

2022-08-26 09:00 UTC, nassergonzalez commented
trigger ti0

2022-08-26 10:42 UTC, vlica-harness requested changes
> Reviewed 8 of 16 files at r1, 4 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-26 10:43 UTC, vlica-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-26 10:43 UTC, vlica-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722#-:-NAOk1xT9icdXZHkttxb:bnfp4nl)* status: 1 change requests. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-26 10:53 UTC, tmacari-harness requested changes
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/test/resources/cdng/variables/HowTo` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK3Nxl7zm8cE1RoEBj:-NAOl-XLCUdkTO3uCWc8:b-rsxcjr) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/resources/cdng/variables/HowTo#L1)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I thought that it will be good to have some instructions for the future developers that need to add test and don't know how to generate the json files, but I can remove it if you want
</blockquote></details>

You can add those as a comment in the test, but I don't think we need a file for that.
Besides tat it is also not enough informative, we have to start the app/ put a debug point.. all those steps are not mentioned here.
I wold say we don't need that file.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureTestHelper.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/36722#-NAOkqrLC7GDLnOO8jOB:-NAOkqrMEPa3yn-DjmP6:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/f04d223c11d7febfff0860d055bc007d24ea9266/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureTestHelper.java#L116)):*
> ```Java
>         .build();
>   }
>   public GitFetchFilesConfig getBPTemplate() {
> ```

please add empty line


<!-- Sent from Reviewable.io -->

2022-08-26 11:18 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: 1 change requests. 2. unresolved discussions. 

___
*[`125-cd-nextgen/src/test/resources/cdng/variables/HowTo` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/36722#-NAK3Nxl7zm8cE1RoEBj:-NAOrrdg4vf3x0C7rX_T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fa49d7fe0b34d9a540eacba437e39460ae3e0b/125-cd-nextgen/src/test/resources/cdng/variables/HowTo#L1)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

You can add those as a comment in the test, but I don't think we need a file for that.
Besides tat it is also not enough informative, we have to start the app/ put a debug point.. all those steps are not mentioned here.
I wold say we don't need that file.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureTestHelper.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/36722#-NAOkqrLC7GDLnOO8jOB:-NAOrsBH1IgL78aPtqjf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f04d223c11d7febfff0860d055bc007d24ea9266/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureTestHelper.java#L116)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-26 11:22 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-26 11:25 UTC, vlica-harness approved these changes

2022-09-01 06:07 UTC, tmacari-harness approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36722)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-01 09:03 UTC, merged