[feat][CDS-41419]: Add delegate task for Azure NG
harness/harness-core pull request #36768
Opened 2022-08-25 08:20 UTC by nassergonzalez

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-25 08:27 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 67 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 16 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 50 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36768)

2022-08-25 10:00 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelper.java
> +public interface AzureARMBaseHelper {
I believe the scope of Helper is to have static utility methods, but here I see it as an interface...

2022-08-25 10:23 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java
> +      deploymentParameters.getDeploymentName();
Shouldn't we have return statement here?

2022-08-25 10:25 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java
> +        ? String.format(DEPLOYMENT_NAME_PATTERN, "rollback_" + randomNum, System.currentTimeMillis())
I think we can move "rollback_" to a constant.

2022-08-25 10:27 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java
> +public class AzureARMBaseHelperImpl implements AzureARMBaseHelper {
missing @OwnedBy

2022-08-25 10:51 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: 45 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelper.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/36768#-NAJ4nV86FarZi7Bc0NX-r1-22:-NAJbfJg-UaeFrmBi8uD:b-9ojf0p) ([raw file](https://github.com/harness/harness-core/blob/0ae48d514bc9e2cbd4ccf3cf8a3d09cefffeaac1/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelper.java#L22)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

I believe the scope of Helper is to have static utility methods, but here I see it as an interface...
</blockquote></details>

We did the same thing for the cloudformation steps, where CloudformationBaseHelper was an interface and we implemented the methods in the implementation class
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/36768#-NAJ4nV86FarZi7Bc0NY-r1-26:-NAJbti01wbmFO_T173t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ae48d514bc9e2cbd4ccf3cf8a3d09cefffeaac1/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L26)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

missing @OwnedBy
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/36768#-NAJ4nV86FarZi7Bc0NY-r1-55:-NAJbx0aEMODa1WIuyv5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ae48d514bc9e2cbd4ccf3cf8a3d09cefffeaac1/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L55)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

Shouldn't we have return statement here?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/36768#-NAJ4nV86FarZi7Bc0NY-r1-59:-NAJcEAH-ItzWfcIh-vm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ae48d514bc9e2cbd4ccf3cf8a3d09cefffeaac1/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L59)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

I think we can move "rollback_" to a constant. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-25 11:00 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNG.java
> +    log.info("Started executing the Azure ARM/BP NG task");
minor:  If it's only the AzureARMTaskNG then we should update the log to reflect only ARM...

2022-08-25 11:05 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNG.java
> +    secretDecryptionService.decrypt(
I'm not sure why but having this way of decryption I faced some issues.
maybe we can have a look at AzureWebAppTaskNG how we decrypt...

2022-08-25 11:15 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMAbstractTaskHandler.java
> +public abstract class AzureARMAbstractTaskHandler {
I think the naming for NG would be AzureARMAbstractRequestHandler instead of having suffix with TaskHandler.
maybe @tmacari-harness  can also confirm...

2022-08-25 11:27 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMAbstractTaskHandler.java
> +  public AzureTaskNGResponse executeTask(AzureTaskNGParameters azureTaskNGParameters, String delegateId, String taskId,
In my opinion this AzureTaskNGResponse is too general.
In case we use it only for ARM/BP maybe it can be renamed to AzureResourceCreationTaskNGResponse...
For example on azure webapp we have: AzureWebAppTaskResponse

2022-08-25 12:28 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java
> +public class AzureBlueprintCreateTaskHandler extends AzureARMAbstractTaskHandler {
I believe this one should be a @Singleton 
and have @OwnedBy

2022-08-25 12:35 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java
> +  // TODO: Candidate
are these  TODO comments still actual?

2022-08-25 14:33 UTC, tmacari-harness requested changes
> Reviewed 22 of 45 files at r1, 13 of 18 files at r2, 2 of 5 files at r3, 11 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAK78Gw9fGwHO9-0IQ8:-NAK78Gw9fGwHO9-0IQ9:b43yg44) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L14)):*
> ```Java
> import static io.harness.azure.model.AzureConstants.DEPLOYMENT_NAME_PATTERN;
> import static io.harness.data.structure.EmptyPredicate.isEmpty;
> import static io.harness.delegate.task.azure.arm.AzureARMPreDeploymentData.builder;
> ```

That doesn't look correct for me, to import static builder method.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAK7Nyl3HFa-m_cz6rU:-NAK7Nyl3HFa-m_cz6rV:b-xscwvr) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L89)):*
> ```Java
>         .outputs(outputs)
>         .commandExecutionStatus(CommandExecutionStatus.SUCCESS)
>         .azureARMPreDeploymentData(builder().build())
> ```

let's not use static import.
Also why do we always return it empty?



_Suggestion:_
```Java
AzureARMPreDeploymentData.builder().build()
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKDfHP-2cMWDIdmF-q:-NAKDfHQC7XPJvxcWtgE:b-qe9xhx) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java#L37)):*
> ```Java
> import java.io.IOException;
> import lombok.extern.slf4j.Slf4j;
> @Slf4j
> ```

Add empty line
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKEJzS4oXjWWQXH3Yr:-NAKEJzT8Csb0tVIt-s9:bs0jlo6) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java#L40)):*
> ```Java
> @OwnedBy(CDP)
> @Singleton
> public class AzureARMCreateTaskHandler extends AzureResourceCreationAbstractTaskHandler {
> ```

Maybe AzureCreateArmResourcetaskHandler?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKEfqzBKs-wjNJPity:-NAKEfqzBKs-wjNJPitz:bscgyww) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L44)):*
> ```Java
> @OwnedBy(CDP)
> @Singleton
> public class AzureBlueprintCreateTaskHandler extends AzureResourceCreationAbstractTaskHandler {
> ```

maybe AzureCreateBlueprintTaskHandler
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKF8bo1pS_XRa__ZOi:-NAKF8bo1pS_XRa__ZOj:bbahr0x) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L57)):*
> ```Java
>     azureBlueprintDeploymentService.deployBlueprintAtResourceScope(
>         toDeploymentBlueprintContext(azureBlueprintTaskNGParameters, azureConfig, logCallback));
>     return AzureBlueprintTaskNGResponse.builder().build();
> ```

Why do we return an empty response object?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKG1HW6EqzOvbXY4Cx:-NAKG1HW6EqzOvbXY4Cy:b-qcbkx5) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L99)):*
> ```Java
>             .logStreamingTaskClient(logCallback)
>             .steadyStateTimeoutInMin(
>                 (int) azureBlueprintTaskNGParameters.getTimeoutInMs() * 1000) // TODO This may need to be in min
> ```

Why do we take timeoutInMS and multiply by 10000?
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java` line 144 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKMHzz3IOJjiPELx_-:-NAKMHzz3IOJjiPELx_0:bvqc7g7) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java#L144)):*
> ```Java
>     assertThatThrownBy(() -> azureARMTaskNG.run(taskNGParameters)).isInstanceOf(TaskNGDataException.class);
>   }
>   @Test(expected = UnexpectedTypeException.class)
> ```

Please add empty line
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java` line 147 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKMgYyCGx-buv-VD-d:-NAKMgYyCGx-buv-VD-e:b-imj0g8) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java#L147)):*
> ```Java
>   @Owner(developers = NGONZALEZ)
>   @Category(UnitTests.class)
>   public void testCFTaskNGWithParamsAndNoTaskType() throws Exception {
> ```

I think we have to rename it
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/handlers/AzureArmCreateTaskHandlerTest.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKNRyR6F6X6-FM3mG7:-NAKNRyR6F6X6-FM3mG8:b-ry1cp) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/handlers/AzureArmCreateTaskHandlerTest.java#L82)):*
> ```Java
>     doReturn(azureConfig).when(azureConnectorMapper).toAzureConfig(any());
>   }
>   private AzureConfig buildAzureConfig() {
> ```

Just to have ti more readable, let's add private methods at the end of class.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/handlers/AzureArmCreateTaskHandlerTest.java` line 111 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKN93w3w9jBdvhvdnn:-NAKN93x75ZlqYIf9Jgw:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/handlers/AzureArmCreateTaskHandlerTest.java#L111)):*
> ```Java
>     return getAzureARMDeploymentParametersBuilder().scopeType(ARMScopeType.TENANT).build();
>   }
>   private AzureARMTaskNGParametersBuilder getAzureARMDeploymentParametersBuilder() {
> ```

please add empty line
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/handlers/AzureArmCreateTaskHandlerTest.java` line 306 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKOZjN6UU4OQEb1w8S:-NAKOZjN6UU4OQEb1w8T:bm93koq) ([raw file](https://github.com/ [...]

2022-08-26 08:58 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: 8 file(s) to review. 1 change requests. 29. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAK78Gw9fGwHO9-0IQ8:-NAKmJEWAeYv5Z7ejXQV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L14)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

That doesn't look correct for me, to import static builder method.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAK7Nyl3HFa-m_cz6rU:-NAKmSJE-zPORxv4U9_B:behsqhx) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L89)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's not use static import.
Also why do we always return it empty?
</blockquote></details>

This function is called for the deployments at subscription level, management level and tenant level which we don't support for rollback and the PreDeploymentData is used for the Rollback option, which is why it' always empty. I am going to add a comment in the code because it will help us in the future
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKDfHP-2cMWDIdmF-q:-NAKoEyCB8GuSmvK2C2e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java#L37)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Add empty line
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKEJzS4oXjWWQXH3Yr:-NAKoPvUEDeCwlQfQVXy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureARMCreateTaskHandler.java#L40)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Maybe AzureCreateArmResourcetaskHandler?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAJ4nV86FarZi7Bc0Nm-r3-38:-NAK64xLEqkFN-hX86BL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L38)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

I believe this one should be a @Singleton 
and have @OwnedBy
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAJ4nV86FarZi7Bc0Nm-r3-53:-NAK65wV8Wvhq_Xzza9a:bo93cld) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L53)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

are these  TODO comments still actual? 
</blockquote></details>

Removed them
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKEfqzBKs-wjNJPity:-NAKoVw54jG-3u7MksUQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L44)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

maybe AzureCreateBlueprintTaskHandler
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKF8bo1pS_XRa__ZOi:-NAKpeCfB_1A832URYBA:b-olyt7a) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L57)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we return an empty response object?
</blockquote></details>

My fault, I forgot the CommandExecutionStatus. That should be done now. It returns always a success because if it fails, then the exception is thrown in the lower levels and the framework should pick it up and sent it to the manager
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKG1HW6EqzOvbXY4Cx:-NAKpsZX0Yz9V-IJ_jNi:bh34ur0) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureBlueprintCreateTaskHandler.java#L99)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we take timeoutInMS and multiply by 10000?
</blockquote></details>

I missed that TODO, this is fixed now
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java` line 144 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKMHzz3IOJjiPELx_-:-NAKrJ7j9PeJMwxh4xZq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java#L144)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Please add empty line
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java` line 147 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKMgYyCGx-buv-VD-d:-NAKrOFO5ap368pog-P9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/AzureArmTaskNGTest.java#L147)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I think we have to rename it
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/handlers/AzureArmCreateTaskHandlerTest.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/36768#-NAKNRyR6F6X6-FM3mG7:-NAKrdtJBoxzszqyMTUW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d1e89d89837d27cb9eefe67683e170465db8580/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/arm/han [...]

2022-08-26 09:30 UTC, tmacari-harness requested changes
> Reviewed 6 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: 3 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 84 at r5](https://reviewable.io/reviews/harness/harness-core/36768#-NAOO2m5B7DRdsrgfwye:-NAOO2m5B7DRdsrgfwyf:b-iuhwv9) ([raw file](https://github.com/harness/harness-core/blob/2c82adc13af979f5bf592b54227f06c83a7969b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L84)):*
> ```Java
> 
>   @Override
>   /*
> ```

@Override should be below the comments
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNG.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAK7oBQ6mzRAHdEDnN9:-NAOOTQ71RdzygVKAZvq:babe8ie) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNG.java#L60)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see we still return null
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureCreateArmResourceTaskHandler.java` line 159 at r5](https://reviewable.io/reviews/harness/harness-core/36768#-NAOOnK8-tQXCiaPcs-j:-NAOOnK8-tQXCiaPcs-k:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/2c82adc13af979f5bf592b54227f06c83a7969b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureCreateArmResourceTaskHandler.java#L159)):*
> ```Java
>     }
>   }
>   protected void printErrorMsg(
> ```

please add empty line


<!-- Sent from Reviewable.io -->

2022-08-26 10:57 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: 3 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 84 at r5](https://reviewable.io/reviews/harness/harness-core/36768#-NAOO2m5B7DRdsrgfwye:-NAOmml87cVimTHuGDs2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c82adc13af979f5bf592b54227f06c83a7969b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L84)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

@Override should be below the comments
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNG.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/36768#-NAK7oBQ6mzRAHdEDnN9:-NAOmyUfE1DETpVcO4wr:b-49o9p1) ([raw file](https://github.com/harness/harness-core/blob/b35f2d9e13fcc7245d5199da762e8b04d5536ac4/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNG.java#L60)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I see we still return null
</blockquote></details>

oh that explains something. Ok, NOW is done for sure xD
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureCreateArmResourceTaskHandler.java` line 159 at r5](https://reviewable.io/reviews/harness/harness-core/36768#-NAOOnK8-tQXCiaPcs-j:-NAOn6q-EPEl0gYGyivy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c82adc13af979f5bf592b54227f06c83a7969b2/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/handlers/AzureCreateArmResourceTaskHandler.java#L159)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-26 11:08 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: 11. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-26 11:14 UTC, vlica-harness reviewed
> Reviewed 20 of 45 files at r1, 13 of 18 files at r2, 2 of 5 files at r3, 10 of 19 files at r4, 6 of 8 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: 11. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-08-26 11:14 UTC, vlica-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-30 08:13 UTC, puthrayaharness approved these changes
> Reviewed 20 of 45 files at r1, 13 of 18 files at r2, 2 of 5 files at r3, 10 of 19 files at r4, 6 of 8 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-08-30 08:41 UTC, nassergonzalez commented
trigger codebasehash

2022-08-30 09:06 UTC, nassergonzalez commented
trigger ti0

2022-08-30 09:06 UTC, nassergonzalez commented
trigger ti1

2022-08-30 09:14 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-30 09:22 UTC, vlica-harness approved these changes

2022-08-30 09:27 UTC, nassergonzalez commented
trigger ti0

2022-08-30 09:27 UTC, nassergonzalez commented
trigger ti1

2022-08-30 09:27 UTC, nassergonzalez commented
trigger ti2

2022-08-30 09:27 UTC, nassergonzalez commented
trigger ti4

2022-08-30 09:50 UTC, anilchowdhury-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 20 of 45 files at r1, 13 of 18 files at r2, 2 of 5 files at r3, 10 of 19 files at r4, 6 of 8 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768#-:-NAi8ilACb3VM7fV9rN7:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-30 10:21 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-30 11:17 UTC, nassergonzalez commented
trigger codebasehash

2022-08-30 15:31 UTC, gaurav-jain1 commented
As per discussion with @nassergonzalez , this task has been there in manager since 2 weeks and disabled under FF (which is default disabled). So this should not cause any issues with older delegates.

2022-08-30 15:32 UTC, gaurav-jain1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 20 of 45 files at r1, 13 of 18 files at r2, 2 of 5 files at r3, 10 of 19 files at r4, 6 of 8 files at r5, 3 of 3 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36768#-:-NAjNR1O-5sx-dkN0dL9:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-30 15:43 UTC, nassergonzalez commented
trigger codebasehash

2022-08-30 15:51 UTC, merged