[feat]: [PL-26081]: Introducing Default User Groups at all scopes.
harness/harness-core pull request #36761
Opened 2022-08-25 04:47 UTC by Jimit09Gandhi

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-25 04:51 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 22 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 11 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 11 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36761)

2022-08-26 04:00 UTC, ankit-harness requested changes
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NAN9KQVDqBMtYZxt7Hk:-NAN9KQVDqBMtYZxt7Hl:bn3niou) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L148)):*
> ```Java
>       userGroupService.setUpDefaultUserGroup(scope);
>     } catch (DuplicateFieldException ex) {
>       log.error("User Group Creation failed for Organization:" + scope.toString() + "as User Group already exists", ex);
> ```

Can we mention in the error msg its the default user group
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 150 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NAN9OMv1gWKjA-qy-85:-NAN9OMv1gWKjA-qy-86:bo3ses6) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L150)):*
> ```Java
>       log.error("User Group Creation failed for Organization:" + scope.toString() + "as User Group already exists", ex);
>     } catch (Exception ex) {
>       log.error("User Group Creation failed for Organization: " + scope.toString(), ex);
> ```

Same here. Mention default user group
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANB6Q8BM6ochCH6lOo:-NANB6Q8BM6ochCH6lOp:b-it6i8h) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L78)):*
> ```Java
> 
>         try {
>             List<String> accountIdsToBeInserted = organizationService.getDistinctAccounts();
> ```

It should be named -> distinctAccountIds
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANCfUn47B_qVxRtITU:-NANCfUn47B_qVxRtITV:b4niy2l) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L94)):*
> ```Java
>             try {
>                 Scope scope = Scope.of(accountId, null, null);
>                 if (Boolean.FALSE.equals(userGroupService.exists(scope, getDefaultUserGroupId(scope)))) {
> ```

If DefaultUserGroup exists, shouldn't we just skip adding users again.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANDDDA5SeoBuY2nhUu:-NANDDDA5SeoBuY2nhUv:b2zex22) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L187)):*
> ```Java
>             }
>             try {
>                 if (userGroupOptional.isPresent()) {
> ```

I don't think this check should be here. Inside this method, assumption should be DefaultUserGroup doesn't exist and we are creating one inside this method.

All checks for existence/non-existence should be at higher level method
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupsCreationJob.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANCAAq0hHb1NPjGtx1:-NANCAAq0hHb1NPjGtx2:b-3pb5ze) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupsCreationJob.java#L17)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class DefaultUserGroupsCreationJob implements Managed {
> ```

This job might run on all Pods at similar time. We should take a lock before proceeding with the job. Also, once the job is done, next time job should be no-op. 
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 227 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANFklh3LcalbWLTclG:-NANFklh3LcalbWLTclH:b-s6wjsc) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L227)):*
> ```Java
>   }
> 
>   private void checkUpdateForHarnessManagedGroup(UserGroupDTO toBeSavedUserGroup, UserGroup savedUserGroup) {
> ```

Can this just be a simple check that User Group should not be Default User Group.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 805 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANHQRqCUagUmzHUKrX:-NANHQRqCUagUmzHUKrY:brejuat) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L805)):*
> ```Java
> 
>   @Override
>   public void setUpDefaultUserGroup(Scope scope) {
> ```

Why we are not adding users at the time of creation of default user group?


<!-- Sent from Reviewable.io -->

2022-08-30 00:43 UTC, gn-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 20 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/UserMembershipStreamListener.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAg882t2AkIen5VyZOr:-NAg882t2AkIen5VyZOs:b-ozqlg8) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/120-ng-manager/src/main/java/io/harness/ng/core/event/UserMembershipStreamListener.java#L59)):*
> ```Java
> 
>   private boolean processUserMembershipEvent(UserMembershipDTO userMembershipDTO) {
>     String action = userMembershipDTO.getAction();
> ```

Can this be null?



_Code quote:_
```Java
userMembershipDTO.getAction();
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAg8Vcy11lDrnSkRxOg:-NAg8Vcy11lDrnSkRxOh:bp1bdrs) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L149)):*
> ```Java
>       defaultUserGroupService.create(scope, emptyList());
>     } catch (DuplicateFieldException ex) {
>       log.error("User Group Creation failed for Organization:" + scope.toString() + "as User Group already exists", ex);
> ```

These are not user facing errors? 
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAg8rt94BhSiLPsBQDH:-NAg8rt94BhSiLPsBQDI:b-bv6n5b) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L13)):*
> ```Java
> import io.harness.annotations.dev.OwnedBy;
> import io.harness.beans.Scope;
> import io.harness.exception.DuplicateFieldException;
> ```

Please run optimize imports



_Code quote:_
```Java
DuplicateFieldException
```
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 254 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAgAtGk3jJSeXo3rnIA:-NAgAtGlAJyn2Ce7oveV:bebsayy) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L254)):*
> ```Java
>       return allUsersAtScope;
>     } catch (Exception ex) {
>       return null;
> ```

Returning null is not a good practice - just return an empty list or if you want different between null and empty list, you an Optional
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/DefaultUserGroupService.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAgB7MJ3t1YRAQ9yaM2:-NAgB7MK8DaJbDb7DVjP:bhmo421) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/api/DefaultUserGroupService.java#L12)):*
> ```Java
> public interface DefaultUserGroupService {
>   UserGroup create(Scope scope, List<String> userIds);
>   void addUserToDefaultUserGroups(Scope scope, String userId);
> ```

Please add JavaDocs to this interface



_Code quote:_
```Java
public interface DefaultUserGroupService {
  UserGroup create(Scope scope, List<String> userIds);
  void addUserToDefaultUserGroups(Scope scope, String userId);
  UserGroup update(UserGroup userGroup);
  Optional<UserGroup> get(String accountIdentifier, String orgIdentifier, String projectIdentifier, String identifier);
  String getUserGroupIdentifier(Scope scope);
  boolean isDefaultUserGroupService(Scope scope, String identifier);
```
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAgBFcgCLxJkOVr8heZ:-NAgBFcgCLxJkOVr8he_:b6e5z31) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L101)):*
> ```Java
>       String userGroupIdentifier, String userIdentifier);
> 
>   UserGroup updateDefaultUserGroup(UserGroup userGroup);
> ```

Please add javadocs to your interface

Reference: https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21149417486/Code+Review+Guildelines#Test-coverage-and-documentation



_Code quote:_
```Java
  UserGroup createDefaultUserGroup(UserGroupDTO userGroupDTO);

  UserGroup addMemberToDefaultUserGroup(String accountIdentifier, String orgIdentifier, String projectIdentifier,
      String userGroupIdentifier, String userIdentifier);

  UserGroup updateDefaultUserGroup(UserGroup userGroup);
```


<!-- Sent from Reviewable.io -->

2022-08-30 12:00 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 21 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NAN9KQVDqBMtYZxt7Hk:-NAibb--9CLIqX1c6ZTx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L148)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we mention in the error msg its the default user group
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 150 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NAN9OMv1gWKjA-qy-85:-NAibcXN-OUejrrqO9mN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L150)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Same here. Mention default user group
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANB6Q8BM6ochCH6lOo:-NAibfyuCq6FW4RD_4Lp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L78)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

It should be named -> distinctAccountIds
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANCfUn47B_qVxRtITU:-NAibggP9IyjDuR3Fs1I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L94)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

If DefaultUserGroup exists, shouldn't we just skip adding users again.
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 254 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAgAtGk3jJSeXo3rnIA:-NAibk5853vWtskFnDeM:bg583cl) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L254)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Returning null is not a good practice - just return an empty list or if you want different between null and empty list, you an Optional
</blockquote></details>

Done. Thanks for suggestion.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupsCreationJob.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANCAAq0hHb1NPjGtx1:-NAibp0eEXwmX--66Xfx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupsCreationJob.java#L17)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This job might run on all Pods at similar time. We should take a lock before proceeding with the job. Also, once the job is done, next time job should be no-op. 
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 227 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANFklh3LcalbWLTclG:-NAibsAOATHyfOJB6k-J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L227)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can this just be a simple check that User Group should not be Default User Group.
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 805 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANHQRqCUagUmzHUKrX:-NAibuo99-yw2W_pkwPd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L805)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why we are not adding users at the time of creation of default user group?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-01 04:00 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 21 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/36761#-NANDDDA5SeoBuY2nhUu:-NArC8iEBN_D4_0rfoZ8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9c3df4e86117e41c468f7627d4bd89948ac1ed9a/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L187)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I don't think this check should be here. Inside this method, assumption should be DefaultUserGroup doesn't exist and we are creating one inside this method.

All checks for existence/non-existence should be at higher level method
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAg8rt94BhSiLPsBQDH:-NArC4TdA33X3NELBPA6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L13)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Please run optimize imports
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-01 14:55 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 21 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/UserMembershipStreamListener.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAg882t2AkIen5VyZOr:-NAtX7LQDgvj_GSd8UqO:bj15ywg) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/120-ng-manager/src/main/java/io/harness/ng/core/event/UserMembershipStreamListener.java#L59)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Can this be null?
</blockquote></details>

These are predefined actions. If it is null it can be assumed the message is handled. Let me know if any other thoughts on same.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAg8Vcy11lDrnSkRxOg:-NAtXkQA8O-kllsc5lLW:b-fcwlwz) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L149)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

These are not user facing errors? 
</blockquote></details>

In case of any failure while creating User Groups we want to avoid blocking Scope creation as it would be creation handled in EntityCrud Listener in case it doesn't exist.


<!-- Sent from Reviewable.io -->

2022-09-01 17:55 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 21 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/DefaultUserGroupService.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAgB7MJ3t1YRAQ9yaM2:-NAuBQuQ8Lm2l7V1qrGD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/api/DefaultUserGroupService.java#L12)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Please add JavaDocs to this interface
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/36761#-NAgBFcgCLxJkOVr8heZ:-NAuBSHU7eZXDlXljSbo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5c13a513287fdf02598c9582ec3b2f4a2ee50396/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L101)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Please add javadocs to your interface

Reference: https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21149417486/Code+Review+Guildelines#Test-coverage-and-documentation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-01 20:34 UTC, gn-harness approved these changes
> Reviewed 3 of 14 files at r1, 9 of 16 files at r2, 1 of 5 files at r3, 1 of 4 files at r4, 4 of 5 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 18 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-02 03:38 UTC, ankit-harness requested changes
> Reviewed 10 of 16 files at r2, 1 of 5 files at r3, 1 of 4 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 4 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 150 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw0RYL04upQL6rP9gC:-NAw0RYL04upQL6rP9gD:b-llswk6) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L150)):*
> ```Java
>     } catch (DuplicateFieldException ex) {
>       log.error(
>           "All Users User Group Creation failed for Organization:" + scope.toString() + "as User Group already exists",
> ```

At all other places in the code we are calling All Users User Group as Default User Group. So, we should use the same terminology
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 197 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw0fGAEq4t02H5mQJD:-NAw0fGAEq4t02H5mQJE:b-llswk6) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L197)):*
> ```Java
>     } catch (DuplicateFieldException ex) {
>       log.error(
>           "All Users User Group Creation failed for Project:" + scope.toString() + "as User Group already exists", ex);
> ```

At all other places in the code we are calling All Users User Group as Default User Group. So, we should use the same terminology
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw5OBW4W2YWfM4WVI9:-NAw5OBW4W2YWfM4WVIA:bpams3k) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L71)):*
> ```Java
>       }
>       try {
>         log.info(DEBUG_MESSAGE + "Setting SecurityContext.");
> ```

We don't need to have these log lines of setting and unsetting security context
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 92 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw5X6aAMJzFVkDO7b5:-NAw5X6aAMJzFVkDO7b6:b-z30roc) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L92)):*
> ```Java
> 
>     try {
>       log.info(DEBUG_MESSAGE + " Fetching all accounts...");
> ```

No need to print this log line.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 97 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw5I5R9WXQsmUiWBWN:-NAw5I5R9WXQsmUiWBWO:b-2aamy8) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L97)):*
> ```Java
>         return;
>       }
>       log.info(DEBUG_MESSAGE + " Fetched all accounts...");
> ```

We should print the count as well. Otherwise this log line doesn't add much value
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 114 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw7Lqk7RvXVCy7b6_R:-NAw7LqlC8VLoUM_NRK4:b-ibiuen) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L114)):*
> ```Java
>   }
> 
>   private void createOrUpdateUserGroupAtScope(Scope scope) {
> ```

This should be done inside DefaultUserGroupService. It should be treated as a reusable piece of code
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 115 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw6XTu6ehYjmwNsdcD:-NAw6XTu6ehYjmwNsdcE:b-ddv72f) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L115)):*
> ```Java
> 
>   private void createOrUpdateUserGroupAtScope(Scope scope) {
>     Optional<List<String>> allUsersAtScopeOptional = getAllUsersAtScope(scope);
> ```

Optional should not be used with Collections. Check should be on if collection is empty or not
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 136 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw6y7iDwMY_eekMsPH:-NAw6y7iDwMY_eekMsPI:bbsz2ua) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L136)):*
> ```Java
>   private void createUserGroup(Scope scope, List<String> allUsersAtScope) {
>     try {
>       log.info(DEBUG_MESSAGE + String.format("Creating User Group at scope %s", scope));
> ```

No need to have this msg
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 151 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9li40Eb4UlK50Hbv:-NAw9li40Eb4UlK50Hbw:bbsz2ua) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L151)):*
> ```Java
>         Pageable pageable = PageRequest.of(pageIndex, pageSize);
>         Criteria criteria = Criteria.where("accountIdentifier").is(accountId);
>         log.info(DEBUG_MESSAGE + " Fetching all Organizations...");
> ```

No need to have this msg
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 153 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9mGj3ltwAJvuuLcR:-NAw9mGj3ltwAJvuuLcS:b-lp9kh1) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L153)):*
> ```Java
>         log.info(DEBUG_MESSAGE + " Fetching all Organizations...");
>         List<Organization> organizations = organizationService.list(criteria, pageable).getContent();
>         log.info(DEBUG_MESSAGE + " Fetched all Organizations...");
> ```

Print Org Count
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 175 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9cBsC33MZX0fU72p:-NAw9cBsC33MZX0fU72q:b-k25n26) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L175)):*
> ```Java
>       do {
>         Pageable pageable = PageRequest.of(pageIndex, pageSize);
>         Criteria criteria = Criteria.where("accountIdentifier").is(accountId).and("organizationId").is(organizationId);
> ```

It should be organizationId or orgIdentifier
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 176 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9JAnAy41xWd906Mi:-NAw9JAnAy41xWd906Mj:bbsz2ua) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L176)):*
> ```Java
>         Pageable pageable = PageRequest.of(pageIndex, pageSize);
>         Criteria criteria = Criteria.where("accountIdentifier").is(accountId).and [...]

2022-09-02 06:19 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 4 file(s) to review. 1 change requests. 34. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 150 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw0RYL04upQL6rP9gC:-NAwoY5Z80vSRnhmzfMF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L150)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

At all other places in the code we are calling All Users User Group as Default User Group. So, we should use the same terminology
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 197 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw0fGAEq4t02H5mQJD:-NAwoWeaElFQMpnzOhpP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L197)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

At all other places in the code we are calling All Users User Group as Default User Group. So, we should use the same terminology
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw5OBW4W2YWfM4WVI9:-NAwoZwi26NB3kWA7AAk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L71)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We don't need to have these log lines of setting and unsetting security context
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 92 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw5X6aAMJzFVkDO7b5:-NAwoaV2BhjcwF62o7qc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L92)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need to print this log line.
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 97 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw5I5R9WXQsmUiWBWN:-NAwobOi3bec-iVv5lTi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L97)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should print the count as well. Otherwise this log line doesn't add much value
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 115 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw6XTu6ehYjmwNsdcD:-NAwocem37S-0y36ownZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L115)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Optional should not be used with Collections. Check should be on if collection is empty or not
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 136 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw6y7iDwMY_eekMsPH:-NAwoelN1MCv89epl4Qq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L136)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need to have this msg
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 151 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9li40Eb4UlK50Hbv:-NAwofMK1XjZpT9F5Ogl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L151)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need to have this msg
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 153 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9mGj3ltwAJvuuLcR:-NAwog_Z6P-VV0GDE1b3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L153)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Print Org Count
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 175 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9cBsC33MZX0fU72p:-NAwohIOD8BWT-BOgxoa:bj063ij) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L175)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

It should be organizationId or orgIdentifier
</blockquote></details>

Changed to orgIdentifier. 
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 176 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9JAnAy41xWd906Mi:-NAwoqah6eiPgnmFAjO7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L176)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need to have this msg
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 178 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw9KXVEN0Jqku97TSE:-NAwoqxoA5IsKyif1CzJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L178)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Print Project count
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 200 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw8xJjCnXq8_uXsnU2:-NAwos6DEEtRGpwbWKzW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L200)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need to have this log msg
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core [...]

2022-09-02 13:41 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 12 file(s) to review. 1 change requests. 41. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java` line 114 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw7Lqk7RvXVCy7b6_R:-NAwzSpx0TeDB2HTnxRi:b595t4v) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java#L114)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should be done inside DefaultUserGroupService. It should be treated as a reusable piece of code
</blockquote></details>

Agreed. Same can be used in Reconciliation job we can introduce later.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/DefaultUserGroupService.java` line 14 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw3lMI-trXsD23Jtt-:-NAyK-AyAeKtAY06k2I4:b-btemd4) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/DefaultUserGroupService.java#L14)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why the need to expose this method?
</blockquote></details>

Not needed anymore. Removed.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw4O_f3G35rnbgBdr3:-NAyKbbuCFEvWE2LtcVo:bar83lw) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L98)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why need to pass userGroupIdentifier when it can be inferred from the fact that its default user group of a given scope
</blockquote></details>

UserGroupService need not know about default user group identifier for given scope. That information is encapsulated in DefaultUserGroupService.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 101 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAw4AGuE8jzZU5zpu-J:-NAyDGuG4DBzi2OMCaEz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L101)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

createDefaultUserGroup takes UserGroupDTO but updateDefaultUserGroup takes UserGroup as an argument. We should have consistency.
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 164 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAwCUicAL8Ba-0mf3Gl:-NAyJVSK-si_S9fBv1JA:bz8cge6) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L164)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This can be a package private method. Hence, no need to expose them in interfaces as well
</blockquote></details>

I am accessing this in DefaultUserGroupService through UserGroupService interface, hence public.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 209 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAwBnK-EtPx1YG460jP:-NAyHqHg8oMQTI0Hh3Wh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L209)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

checkUpdateToHarnessManagedUserGroup
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 217 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAwCMbn32r284d378PH:-NAyLUwn-N9ja7MShPam:bz8cge6) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L217)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This can be a package private method
</blockquote></details>

I am accessing this in DefaultUserGroupService through UserGroupService interface, hence public.


<!-- Sent from Reviewable.io -->

2022-09-02 14:02 UTC, ankit-harness requested changes
> Reviewed 11 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 231 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAwC9CV-pX6s4nWpsIk:-NAyVPcKD-azVTj83njZ:b-vo3pdp) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L231)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Because Notifications can be updated in User Group using same API. 
</blockquote></details>

This code is not reading well. Can we not put this check in the update call to default ug?


<!-- Sent from Reviewable.io -->

2022-09-02 15:04 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 231 at r5](https://reviewable.io/reviews/harness/harness-core/36761#-NAwC9CV-pX6s4nWpsIk:-NAyWMN99l36mC-lLoWK:b-e7a42a) ([raw file](https://github.com/harness/harness-core/blob/0b9a5b43a210885587cf5b67238d656db2b21ded/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L231)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This code is not reading well. Can we not put this check in the update call to default ug?
</blockquote></details>

This check is not related to Default User Group. It is for SCIM related. I refactored to reuse the logic.


<!-- Sent from Reviewable.io -->

2022-09-02 17:59 UTC, gupta-utkarsh submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 14 files at r1, 4 of 16 files at r2, 2 of 5 files at r5, 10 of 12 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761#-:-NAzLxSxAz0nSCQesOKA:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-03 16:26 UTC, reetika04 approved these changes
> Reviewed 3 of 14 files at r1, 4 of 16 files at r2, 2 of 5 files at r5, 9 of 12 files at r8, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-03 18:32 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 12 files at r8, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761#-:-NB3c3Cg-eTEvSp6ROSF:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-03 21:26 UTC, gupta-utkarsh approved these changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36761)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-04 03:28 UTC, merged