[feat]: [PL-25545]: Using getAsDefault for fixed values
harness/harness-core pull request #36778
Opened 2022-08-25 11:14 UTC by shreyas-harness

## Describe your changes
Supported useAsDefault key. Allows us to have fixed value while creation of connector, such runtime values wont be needed during creation of secret when using custom secret manager connector.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-25 11:17 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36778)

2022-08-25 12:38 UTC, mohitg0795 commented
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/36778#-NAK-OdO4ttnNEU1vRlP:-NAK-OdO4ttnNEU1vRlQ:bk4nrnx) ([raw file](https://github.com/harness/harness-core/blob/eefa542694eb0ae79a72c0a6f31653542e0d096a/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L95)):*
> ```Java
>       CustomSecretManagerConfigDTO customSecretManagerConfigDTO, List<String> keysToRemove) {
>     Map<String, List<Map<String, String>>> inputMap = customSecretManagerConfigDTO.getTemplate().getTemplateInputs();
>     if (inputMap == null) {
> ```

Just checking: similar thing we have done in the "mergeDefaultValuesInInputValues" method where we take connectorValues as input and its fetched very similar way. There we don't have any null check but here we have. We can check if its correct.


<!-- Sent from Reviewable.io -->

2022-08-25 20:41 UTC, meenakshi-harness requested changes

2022-08-25 20:41 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        Map<String, List<Map<String, String>>> inputValues =
Why are we saying here List<String, String> ?  useAsDefault is boolean value

2022-08-25 20:41 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +          if (variableInfo.containsKey(USE_AS_DEFAULT_KEY)) {
This will fail if useAsDefault is set to false. We should check for both conditions

2022-08-25 20:41 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +      Map<String, List<Map<String, String>>> inputValues, Map<String, List<Map<String, String>>> connectorValues) {
Using map doesn't seem right. We can have defined classes as we already know the keys and value pair type in template inputs

2022-08-25 20:41 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +    connectorEnvironmentVariable3.put("useAsDefault", "true");
this is wrong true is not passed as string for `useAsDefault`

2022-08-25 20:41 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +    connectorEnvironmentVariable3.put("type", "String");
even this is TemplateType and not String

2022-08-25 20:41 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +  }
no test case for false value

2022-08-25 20:41 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/customsecretmanager/TemplateLinkConfigForCustomSecretManager.java
> +  Map<String, List<Map<String, String>>> templateInputs;
lets discuss the implementation tomorrow morning

2022-08-26 07:56 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        Map<String, List<Map<String, String>>> inputValues =
Fixed this. As discussed over call offline.

2022-08-26 07:56 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +          if (variableInfo.containsKey(USE_AS_DEFAULT_KEY)) {
Done. fixed.

2022-08-26 07:56 UTC, shreyas-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +      Map<String, List<Map<String, String>>> inputValues, Map<String, List<Map<String, String>>> connectorValues) {
Discussed over call.

2022-08-26 07:56 UTC, shreyas-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +    connectorEnvironmentVariable3.put("useAsDefault", "true");
Changed

2022-08-26 07:57 UTC, shreyas-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +    connectorEnvironmentVariable3.put("type", "String");
This is valueType -> should be Integer / boolean ...

2022-08-26 07:57 UTC, shreyas-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +  }
Added.

2022-08-26 07:57 UTC, shreyas-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/customsecretmanager/TemplateLinkConfigForCustomSecretManager.java
> +  Map<String, List<Map<String, String>>> templateInputs;
Discussed over call.

2022-08-26 16:51 UTC, shreyas-harness commented
trigger ti0

2022-08-26 18:12 UTC, shreyas-harness commented
trigger compile

2022-08-26 18:13 UTC, shreyas-harness commented
trigger ti0

2022-08-26 18:13 UTC, shreyas-harness commented
trigger ti2

2022-08-26 18:13 UTC, shreyas-harness commented
trigger ft1

2022-08-26 18:13 UTC, shreyas-harness commented
trigger ft2

2022-08-26 19:11 UTC, shreyas-harness commented
trigger ti2

2022-08-26 19:21 UTC, shreyas-harness commented
trigger ft1

2022-08-27 02:13 UTC, shreyas-harness commented
trigger ft1

2022-08-27 02:26 UTC, shreyas-harness commented
trigger ft2
trigger ti0

2022-08-27 02:57 UTC, shreyas-harness commented
trigger ft2

2022-08-27 03:24 UTC, shreyas-harness commented
trigger compile

2022-08-27 03:41 UTC, shreyas-harness commented
trigger codebasehash

2022-08-28 07:14 UTC, meenakshi-harness requested changes

2022-08-28 07:14 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +  public void removeDefaultFromConfigDTO(
should be private

2022-08-28 07:14 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +  public void mergeDefaultValuesInInputValues(Map<String, List<NameValuePairWithDefault>> inputValues,
same

2022-08-28 07:18 UTC, mohitg0795 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 208 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYJ-w_-ysoIgDAeQne:-NAYJ-w_-ysoIgDAeQnf:br4k3d7) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L208)):*
> ```Java
>     if (SecretText.equals(dto.getType()) && isEmpty(((SecretTextSpecDTO) dto.getSpec()).getValue())) {
>       if ((((SecretTextSpecDTO) dto.getSpec()).getValueType()).equals(CustomSecretManagerValues)) {
>         log.info("Secret does not have any path");
> ```

does this log add any value? It doesn't have any identifier or any other infor attached to it. Will we be able to identify the secret for which this log is printed by any means?


<!-- Sent from Reviewable.io -->

2022-08-28 07:30 UTC, mohitg0795 commented
*[`980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java` line 32 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYLkOfDGldm9hKFJUu:-NAYLkOfDGldm9hKFJUv:byi3muv) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java#L32)):*
> ```Java
> @AllArgsConstructor
> @OwnedBy(HarnessTeam.PL)
> public class NameValuePairWithDefault {
> ```

This seems to be a very specific class for secret manager given the annotations used inside eg: "ALLOW_SECRETS" etc, but the name of the class is very generic. Can we be little specific here?


<!-- Sent from Reviewable.io -->

2022-08-28 07:31 UTC, mohitg0795 commented
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 146 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYM8yBBQs6QQQBKEbk:-NAYM8yBBQs6QQQBKEbl:b2avozf) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L146)):*
> ```Java
>   }
> 
>   public Map<String, List<NameValuePairWithDefault>> mergeStringInInputValues(
> ```

private or public?


<!-- Sent from Reviewable.io -->

2022-08-28 07:32 UTC, mohitg0795 commented
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 159 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYMJAL1Mn4CUKeAOCN:-NAYMJAL1Mn4CUKeAOCO:bxwjzpm) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L159)):*
> ```Java
>         log.error("Exception when converting user input to template input.", exception);
>         throw new SecretManagementException(SECRET_MANAGEMENT_ERROR,
>             "Value passed can not be processed as map. Parsing error : " + exception.getMessage(), USER);
> ```

The error message looks bit ambiguous. What does this mean "can not be processed as map" ? What is map here? 


<!-- Sent from Reviewable.io -->

2022-08-28 07:33 UTC, mohitg0795 commented
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 134 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYMUHi4hT2sn9e4UZt:-NAYMUHi4hT2sn9e4UZu:b24jmmq) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L134)):*
> ```Java
>         for (NameValuePairWithDefault variable : values) {
>           // if variable has useAsDefault and if its value is true.
>           if (variable.getUseAsDefault() != null && variable.getUseAsDefault().equals(Boolean.TRUE)) {
> ```

We can simply write it as "(Boolean.TRUE.equals(variable.getUseAsDefault())"


<!-- Sent from Reviewable.io -->

2022-08-28 07:34 UTC, mohitg0795 commented
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 108 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYMgbME8DUui7UKxVl:-NAYMgbME8DUui7UKxVm:bbhjcow) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L108)):*
> ```Java
>         customSecretManagerConfigDTO.getTemplate().getTemplateInputs();
>     if (inputMap == null) {
>       log.info("No runtime input variables");
> ```

Do we need more identifiers in this message for clarity? It may turn out to be not so useful comment. Please check.


<!-- Sent from Reviewable.io -->

2022-08-28 07:34 UTC, mohitg0795 commented
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 55 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYMrub8L4VQUC9OA4S:-NAYMrub8L4VQUC9OA4T:b-691scx) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L55)):*
> ```Java
>   @Inject private NGConnectorSecretManagerService ngConnectorSecretManagerService;
>   private final ObjectMapper objectMapper = HObjectMapper.NG_DEFAULT_OBJECT_MAPPER;
>   public Set<EncryptedDataParams> prepareEncryptedDataParamsSet(
> ```

lets have a line space before the method, otherwise it becomes difficult to read


<!-- Sent from Reviewable.io -->

2022-08-28 07:35 UTC, mohitg0795 reviewed
> Reviewed 1 of 6 files at r3, 1 of 1 files at r4, 7 of 9 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36778)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-28 08:21 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36778)* status: 11 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/36778#-NAK-27J9A5gs5o8PvRw:-NAYUY0D9pNN1QDDY-vu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eefa542694eb0ae79a72c0a6f31653542e0d096a/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L215)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should it be public or private?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 208 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYJ-w_-ysoIgDAeQne:-NAYVkPR0VUEbl4goXuR:b9qo6p1) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L208)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

does this log add any value? It doesn't have any identifier or any other infor attached to it. Will we be able to identify the secret for which this log is printed by any means?
</blockquote></details>

Added the secret identifier and secret manager for which this log was generated. 
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/36778#-NAK-7KT3XQk0GYmW6hE:-NAYW_vM33gF0Yt1Dhau:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eefa542694eb0ae79a72c0a6f31653542e0d096a/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L92)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

public or private?
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 55 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYMrub8L4VQUC9OA4S:-NAYWXKdDuHh57uCVYmq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets have a line space before the method, otherwise it becomes difficult to read
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 103 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAJhSH4K9XgUyiy6Zu7-r7-103:-NAYXDnX7Os8RM-lcWCf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L103)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

should be private
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 122 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAJhSH4K9XgUyiy6Zu7-r7-122:-NAYWkd995flW9ewPanL:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L122)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

same
</blockquote></details>

done
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 134 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYMUHi4hT2sn9e4UZt:-NAYWmfA5lN9VPuPz8-G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L134)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We can simply write it as "(Boolean.TRUE.equals(variable.getUseAsDefault())"
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 146 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYM8yBBQs6QQQBKEbk:-NAYWq6iCTIuCtOdmIDM:b1kws9y) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L146)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

private or public?
</blockquote></details>

This is public method being used at other places.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 159 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYMJAL1Mn4CUKeAOCN:-NAYWvSg7Oy5yCV-YSJQ:bqll474) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L159)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The error message looks bit ambiguous. What does this mean "can not be processed as map" ? What is map here? 
</blockquote></details>

Changed to show that its for parsing input values to input map
___
*[`980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java` line 32 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYLkOfDGldm9hKFJUu:-NAYXNzB9icFHqDyYF-6:b-w7z4k1) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java#L32)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This seems to be a very specific class for secret manager given the annotations used inside eg: "ALLOW_SECRETS" etc, but the name of the class is very generic. Can we be little specific here?
</blockquote></details>

This can be used at other places as well, where we allow value to contain secret as well. Along with marking the value as default. 


<!-- Sent from Reviewable.io -->

2022-08-28 08:26 UTC, mohitg0795 commented
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 146 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYM8yBBQs6QQQBKEbk:-NAYYXS5C6rd7e0WAJLI:b99fa71) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L146)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

This is public method being used at other places.
</blockquote></details>

Going forward, lets keep public methods on the top and later protected and later private. Random placement of methods adds to ambiguity. Resolving for now.


<!-- Sent from Reviewable.io -->

2022-08-28 08:27 UTC, mohitg0795 commented
*[`980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java` line 32 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYLkOfDGldm9hKFJUu:-NAYYmK50yMQVxeUBD8i:befmwmn) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java#L32)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

This can be used at other places as well, where we allow value to contain secret as well. Along with marking the value as default. 
</blockquote></details>

I agree but name of the class doesn't signify anything related to secret. IMO name of the class simply means that there will be a key value pair in the class object along with some default value. But actually, this class does more than that, wdyt?


<!-- Sent from Reviewable.io -->

2022-08-28 08:27 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +  public void removeDefaultFromConfigDTO(
Done

2022-08-28 08:27 UTC, mohitg0795 commented
*[`980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java` line 32 at r7](https://reviewable.io/reviews/harness/harness-core/36778#-NAYLkOfDGldm9hKFJUu:-NAYYzsZ7od-IAe-FMyT:byxv188) ([raw file](https://github.com/harness/harness-core/blob/7b956522b949e8ac9983f80e3056406cecd15e27/980-commons/src/main/java/software/wings/beans/NameValuePairWithDefault.java#L32)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I agree but name of the class doesn't signify anything related to secret. IMO name of the class simply means that there will be a key value pair in the class object along with some default value. But actually, this class does more than that, wdyt?
</blockquote></details>

Also, issue is its in generic beans package and not in some specific secret manager package.


<!-- Sent from Reviewable.io -->

2022-08-28 08:27 UTC, shreyas-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java
> +  public void mergeDefaultValuesInInputValues(Map<String, List<NameValuePairWithDefault>> inputValues,
Done. Made protected for testing

2022-08-28 15:38 UTC, shreyas-harness commented
The changes are behind Feature Flag on UI and are tested with older version of delegate for backward compatibility. We will be enabling this feature only for account that have latest delegate.

2022-08-28 15:40 UTC, shreyas-harness commented
@mohitg0795  changing to enum is taking more changes and will need testing all from the start. Can we have it as String for now as there wont be any downside to it for now.

2022-08-28 15:46 UTC, meenakshi-harness approved these changes
> Reviewed 1 of 1 files at r4, 7 of 9 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36778)* status: 2 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-08-28 18:29 UTC, mohitg0795 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36778#-:-NA_hp76ESWiONhjTvBq:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-08-28 18:48 UTC, meenakshi-harness commented
trigger codebasehash

2022-08-28 18:51 UTC, merged