Gar triggers
harness/harness-core pull request #36882
Opened 2022-08-29 11:34 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-29 11:45 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 28 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 26 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36882)

2022-09-12 11:49 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-09-12 12:02 UTC, puthrayaharness requested changes

2022-09-12 12:44 UTC, vivekkarnatiharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> -      versionRegex = ACCEPT_ALL_REGEX;
ACCEPT_ALL_REGEX("\\*") is not able to fetch all tags from getbuilds

2022-09-12 13:56 UTC, puthrayaharness approved these changes

2022-09-13 09:15 UTC, vivekkarnatiharness commented
trigger ti1

2022-09-13 09:15 UTC, vivekkarnatiharness commented
trigger ti2

2022-09-13 09:16 UTC, puthrayaharness approved these changes
> Reviewed 6 of 62 files at r1, 34 of 59 files at r2, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36882)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-13 19:38 UTC, vivekkarnatiharness commented
trigger ti2

2022-09-14 04:38 UTC, sahilhindwani-harness approved these changes
> Reviewed 4 of 62 files at r1, 4 of 59 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36882)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-14 04:40 UTC, merged