feat: [PIE-5063]: Add validation to detect missing supported types from filter and variable creators
harness/harness-core pull request #36987
Opened 2022-08-31 21:34 UTC by Fernando-Dourado

## Describe your changes
- Enforce the PMS-SDK initialization rules.
- Change to other services that don't respect these rules.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-08-31 21:38 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36987)

2022-09-01 12:06 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/36987#-NAsvvtEDlind4ZFMRJI:-NAsvvtFCWP-hVBFT369:b-4m7h9d) ([raw file](https://github.com/harness/harness-core/blob/8a2e188c1332c686f4289743fa78b86e9fdaa191/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L116)):*
> ```Java
> 
>   private static void validateSupportedTypes(
>       Map<String, Set<String>> supportedTypes, PipelineServiceInfoProvider pipelineServiceInfoProvider) {
> ```

instead of calling it supported types, can we call it planCreatorTypes for clarity?
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/36987#-NAsw9ewDLECuraynWzM:-NAsw9ewDLECuraynWzN:bse44fd) ([raw file](https://github.com/harness/harness-core/blob/8a2e188c1332c686f4289743fa78b86e9fdaa191/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L118)):*
> ```Java
>       Map<String, Set<String>> supportedTypes, PipelineServiceInfoProvider pipelineServiceInfoProvider) {
>     // VERIFY DECLARED SUPPORTED TYPES VS. SUPPORTED FILTER CREATORS
>     final Set<String> filters = new HashSet<>();
> ```

it needs to be a map of string, list<string> as we want to compare both the entries
keys should match and the values for keys should also match.

eg. step -> k8sstep. Both should be present. I think you only checking for keys right now.
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/36987#-NAswPyD55jtbuhapEtT:-NAswPyD55jtbuhapEtU:b-9j52qa) ([raw file](https://github.com/harness/harness-core/blob/8a2e188c1332c686f4289743fa78b86e9fdaa191/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L123)):*
> ```Java
>         .map(FilterJsonCreator::getSupportedTypes)
>         .forEach(m -> filters.addAll(m.keySet()));
>     removeUnsupportedTypesAndNotify("FilterJsonCreator", supportedTypes, filters);
> ```

we don't need to remove anything. Don't register if there is a discrepancy.


<!-- Sent from Reviewable.io -->

2022-09-07 08:41 UTC, vaibhav-si reviewed
If validations fail, what are we doing? I see you're only logging. Should we also fail the registration?

Also, after your change, what's the impact on other services? Are they coming up?
If not, are you fixing them?

> Reviewed 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987#-:-NBM5bJEE8eIW6U5ZsiF:b-9kfds0)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-08 04:54 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/36987#-NBQRgb47D94YPfw1lx7:-NBQRgb47D94YPfw1lx8:bc7m2uy) ([raw file](https://github.com/harness/harness-core/blob/2912339554a3bee2730ef021b46887547e80ebfb/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L82)):*
> ```Java
>     }
> 
>     Map<String, Set<String>> supportedTypes = PmsSdkInitValidator.supportedTypesP(planCreators);
> ```

nit: extra P 


<!-- Sent from Reviewable.io -->

2022-09-08 04:58 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/36987#-NBQS6pZ-pXsXAA14OYz:-NBQS6pZ-pXsXAA14OZ-:b-ketfh) ([raw file](https://github.com/harness/harness-core/blob/2912339554a3bee2730ef021b46887547e80ebfb/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java#L55)):*
> ```Java
>     supportedPlan.entrySet().forEach(entry -> {
>       detectUnsupportedTypes("FilterJsonCreators", entry, supportedFilters, unsupportedFilters);
>       detectUnsupportedTypes("VariableJsonCreators", entry, supportedVariables, unsupportedVariables);
> ```

Maybe we can simplify this using Sets.intersection (https://www.geeksforgeeks.org/sets-intersection-function-guava-java/)
if the intersection size is equal to both filter creators and variable creators, we are good else there is some discrepancy which we can calculate.



_Code quote:_
```Java
      detectUnsupportedTypes("FilterJsonCreators", entry, supportedFilters, unsupportedFilters);
      detectUnsupportedTypes("VariableJsonCreators", entry, supportedVariables, unsupportedVariables);
```


<!-- Sent from Reviewable.io -->

2022-09-08 04:58 UTC, sahilhindwani-harness requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 5 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-09 08:27 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/EmptyAnyVariableCreator.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/36987#-NBWLbyj3toh-SIariBP:-NBWLbyj3toh-SIariBQ:byvb8t) ([raw file](https://github.com/harness/harness-core/blob/91ca0d4451fd9e686392ef6ce570e2488611694e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/EmptyAnyVariableCreator.java#L23)):*
> ```Java
> import java.util.Set;
> 
> public class EmptyAnyVariableCreator extends ChildrenVariableCreator<YamlField> {
> ```

it doesn't need to extend ChildrenCreator. It can simply extend VariableCreator.


<!-- Sent from Reviewable.io -->

2022-09-14 21:22 UTC, Fernando-Dourado commented
trigger ti1

2022-09-15 06:01 UTC, vaibhav-si reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 21 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 156 at r8](https://reviewable.io/reviews/harness/harness-core/36987#-NBzi1VT4D57PCCY39gE:-NBzi1VT4D57PCCY39gF:be521a2) ([raw file](https://github.com/harness/harness-core/blob/6abe0bdd3f8e72807f1b4267e4804c7c2301babd/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L156)):*
> ```Java
>   private static final String AZURE_RESOURCE_STEP_METADATA = "AzureProvisioner";
> 
>   private static final Set<String> EMPTY_IDENTIFIERS = Sets.newHashSet("sidecars", "spec", "serviceConfig",
> ```

empty filter identifiers
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 160 at r8](https://reviewable.io/reviews/harness/harness-core/36987#-NBziZVM7CU8biwrGcaZ:-NBziZVM7CU8biwrGca_:bidn560) ([raw file](https://github.com/harness/harness-core/blob/6abe0bdd3f8e72807f1b4267e4804c7c2301babd/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L160)):*
> ```Java
>       "configFiles", "environmentGroup", "service", "manifests", "strategy", "stepGroup");
>   private static final Set<String> EMPTY_SIDECAR_TYPES = Sets.newHashSet("CustomArtifact", "Jenkins", "DockerRegistry",
>       "Acr", "AmazonS3", "ArtifactoryRegistry", "Ecr", "GoogleArtifactRegistry", "Gcr", "Nexus3Registry");
> ```

instead of using hardcoded types here, refer to StepSpecTypeConstants or YamlConstants or something similar.
All these would already be defined somewhere. Try to refer them wherever possible so it becomes easier to find usages through Intellij and also refactor.


<!-- Sent from Reviewable.io -->

2022-09-15 06:01 UTC, vaibhav-si reviewed
CVNG App doesn't have any change?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987#-:-NBzjHMRA0c9f-jEH_W_:b-spiinl)* status: 21 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-15 06:02 UTC, vaibhav-si reviewed
All the apps CD/CI/PMS/STO/CV are coming up fine after this change?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987#-:-NBzjQoT7QooAsCCr5W4:b-n9jnx4)* status: 21 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-15 17:11 UTC, Fernando-Dourado reviewed
Yes, all of them has a successful start after the change, including CVNG.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987#-:-NC0qiA3A8jZBuHLHy4e:bnb4pdt)* status: 23 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 156 at r8](https://reviewable.io/reviews/harness/harness-core/36987#-NBzi1VT4D57PCCY39gE:-NC0rAQUAWr1pZJr-J9a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6abe0bdd3f8e72807f1b4267e4804c7c2301babd/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L156)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

empty filter identifiers
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 160 at r8](https://reviewable.io/reviews/harness/harness-core/36987#-NBziZVM7CU8biwrGcaZ:-NC15NAH6-Q_jDz7xlqJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6abe0bdd3f8e72807f1b4267e4804c7c2301babd/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L160)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

instead of using hardcoded types here, refer to StepSpecTypeConstants or YamlConstants or something similar.
All these would already be defined somewhere. Try to refer them wherever possible so it becomes easier to find usages through Intellij and also refactor.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/36987#-NAsvvtEDlind4ZFMRJI:-NC15xa_BRoPRFU2l4ee:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a2e188c1332c686f4289743fa78b86e9fdaa191/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L116)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

instead of calling it supported types, can we call it planCreatorTypes for clarity?
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/36987#-NAsw9ewDLECuraynWzM:-NC15z530XRpqSepwtLI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a2e188c1332c686f4289743fa78b86e9fdaa191/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L118)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

it needs to be a map of string, list<string> as we want to compare both the entries
keys should match and the values for keys should also match.

eg. step -> k8sstep. Both should be present. I think you only checking for keys right now.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/36987#-NAswPyD55jtbuhapEtT:-NC15zhG6CX8gyG3ucFO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a2e188c1332c686f4289743fa78b86e9fdaa191/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L123)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

we don't need to remove anything. Don't register if there is a discrepancy.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/36987#-NBQRgb47D94YPfw1lx7:-NC15PF94NsL4X9-aIsD:bwkw6wc) ([raw file](https://github.com/harness/harness-core/blob/2912339554a3bee2730ef021b46887547e80ebfb/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L82)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: extra P 
</blockquote></details>

We need this "extra" P because override methods do not accept generics and we have a supported types extractor to plan creators, filter creators, and variable creators. As this methods/operations has a restricted scope a simple name can fit our needs. :) 
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/EmptyAnyVariableCreator.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/36987#-NBWLbyj3toh-SIariBP:-NC161AIAU-yqfRF_2dp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/91ca0d4451fd9e686392ef6ce570e2488611694e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/EmptyAnyVariableCreator.java#L23)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

it doesn't need to extend ChildrenCreator. It can simply extend VariableCreator.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-19 11:14 UTC, archit-harness requested changes
> Reviewed 5 of 7 files at r2, 3 of 4 files at r3, 3 of 5 files at r5, 1 of 1 files at r6, 10 of 11 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: Some of the checks are too old. 20 file(s) to review. 3 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`315-sto-manager/src/main/java/io/harness/sto/plan/creator/STOPipelineServiceInfoProvider.java` line 91 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKRXWD6Z-oNi9vQlEx:-NCKRXWD6Z-oNi9vQlEy:b-hiyfqq) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/315-sto-manager/src/main/java/io/harness/sto/plan/creator/STOPipelineServiceInfoProvider.java#L91)):*
> ```Java
>     variableCreators.add(new EmptyAnyVariableCreator(Set.of("parallel", "steps")));
>     variableCreators.add(
>         new EmptyVariableCreator("step", Set.of("Test", "PublishArtifacts", "liteEngineTask", "SaveCache", "Cleanup")));
> ```

Can use Constants which already exists in their service



_Code quote:_
```Java
"Test", "PublishArtifacts", "liteEngineTask", "SaveCache", "Cleanup"
```
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java` line 157 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKRah-DE9kUY4nY7xm:-NCKRah-DE9kUY4nY7xn:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java#L157)):*
> ```Java
>     variableCreators.add(new EmptyAnyVariableCreator(Set.of("parallel", "steps")));
>     variableCreators.add(
>         new EmptyVariableCreator("step", Set.of("Cleanup", "Test", "PublishArtifacts", "liteEngineTask", "SaveCache")));
> ```

same as above



_Code quote:_
```Java
"step", Set.of("Cleanup", "Test", "PublishArtifacts", "liteEngineTask", "SaveCache")));
```
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/36987#-NBQRgb47D94YPfw1lx7:-NCKRhlR0u1jCWn3j7Ee:bjni2vx) ([raw file](https://github.com/harness/harness-core/blob/2912339554a3bee2730ef021b46887547e80ebfb/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L82)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

We need this "extra" P because override methods do not accept generics and we have a supported types extractor to plan creators, filter creators, and variable creators. As this methods/operations has a restricted scope a simple name can fit our needs. :) 
</blockquote></details>

Just having extra P looks very odd
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java` line 123 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKRpvv4M0yhC6c7Y0d:-NCKRpvv4M0yhC6c7Y0e:bfxc5g0) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java#L123)):*
> ```Java
>     }
>     return supportedTypes;
>   }
> ```

Why do we have just extra Alphabet P, V, F, thus please add respective method name



_Code quote:_
```Java
  static Map<String, Set<String>> supportedTypesP(List<PartialPlanCreator<?>> planCreators) {
    Map<String, Set<String>> supportedTypes = new HashMap<>();
    for (PartialPlanCreator<?> planCreator : planCreators) {
      populateSupportedTypes(supportedTypes, planCreator.getSupportedTypes());
    }
    return supportedTypes;
  }

  private static Map<String, Set<String>> supportedTypesV(List<VariableCreator> variableCreators) {
    Map<String, Set<String>> supportedTypes = new HashMap<>();
    for (VariableCreator<?> variableCreator : variableCreators) {
      populateSupportedTypes(supportedTypes, variableCreator.getSupportedTypes());
    }
    return supportedTypes;
  }

  private static Map<String, Set<String>> supportedTypesF(List<FilterJsonCreator> filterCreators) {
    Map<String, Set<String>> supportedTypes = new HashMap<>();
    for (FilterJsonCreator<?> filterCreator : filterCreators) {
      populateSupportedTypes(supportedTypes, filterCreator.getSupportedTypes());
    }
    return supportedTypes;
  }
```
___
*[`clients/pipeline-service/pms-sdk/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker` line 1 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKS63x-rejd_bqDKDp:-NCKS63x-rejd_bqDKDq:b-mchm1z) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/clients/pipeline-service/pms-sdk/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker#L1)):*
> ```
> mock-maker-inline
> ```

do we need this?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java` line 177 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKSAeG66X4m5W78DWw:-NCKSAeG66X4m5W78DWx:b-1r81pu) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java#L177)):*
> ```Java
>     variableCreators.add(new EmptyVariableCreator("stage", ImmutableSet.of("FeatureFlag")));
>     variableCreators.add(
>         new EmptyVariableCreator("step", ImmutableSet.of("FlagConfiguration", "Barrier", "ResourceConstraint")));
> ```

dont use string directly here, use the one used in their step



_Code quote:_
```Java
    filterJsonCreators.add(new EmptyAnyFilterJsonCreator(ImmutableSet.of("stages", "strategy", "steps", "spec")));
    filterJsonCreators.add(new EmptyFilterJsonCreator("step", ImmutableSet.of("FlagConfiguration")));
    injectorUtils.injectMembers(filterJsonCreators);
    return filterJsonCreators;
  }
  
    variableCreators.add(new QueueStepVariableCreator());
    variableCreators.add(new CustomApprovalStepVariableCreator());
    variableCreators.add(new StrategyVariableCreator());
    variableCreators.add(new EmptyAnyVariableCreator(ImmutableSet.of("parallel", "steps", "spec", "stages")));
    variableCreators.add(new EmptyVariableCreator("stage", ImmutableSet.of("FeatureFlag")));
    variableCreators.add(
        new EmptyVariableCreator("step", ImmutableSet.of("FlagConfiguration", "Barrier", "ResourceConstraint")));
```


<!-- Sent from Reviewable.io -->

2022-09-19 20:28 UTC, Fernando-Dourado reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: Some of the checks are too old. 20 file(s) to review. 3 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`315-sto-manager/src/main/java/io/harness/sto/plan/creator/STOPipelineServiceInfoProvider.java` line 91 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKRXWD6Z-oNi9vQlEx:-NCMNdkA2LyyI1zV6YJ4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/315-sto-manager/src/main/java/io/harness/sto/plan/creator/STOPipelineServiceInfoProvider.java#L91)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can use Constants which already exists in their service
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java` line 157 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKRah-DE9kUY4nY7xm:-NCMOMS-CtdUeHyl70Au:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java#L157)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java` line 123 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKRpvv4M0yhC6c7Y0d:-NCMOrM97Cy4OS76mNB4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java#L123)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why do we have just extra Alphabet P, V, F, thus please add respective method name
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker` line 1 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKS63x-rejd_bqDKDp:-NCMOzI69tAnThSG7ubA:bjob0lk) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/clients/pipeline-service/pms-sdk/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker#L1)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

It is required when using MockedStatic from Mockito.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java` line 177 at r9](https://reviewable.io/reviews/harness/harness-core/36987#-NCKSAeG66X4m5W78DWw:-NCMQYqE-0XV_J8m3rQe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3985700cfac6ee1b5e8183efe296ff2edc0e2ae/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java#L177)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont use string directly here, use the one used in their step
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-20 05:11 UTC, archit-harness submitted a review, later dismissed
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 22 file(s) to review. 2 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-20 12:47 UTC, vaibhav-si requested changes
> Reviewed 2 of 4 files at r3, 3 of 5 files at r5, 1 of 1 files at r6, 6 of 11 files at r8, 1 of 3 files at r9, 7 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 2 file(s) to review. 2 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java` line 19 at r10](https://reviewable.io/reviews/harness/harness-core/36987#-NCPrfpy9WqK9ms2nXZq:-NCPrfpy9WqK9ms2nXZr:b-mboc1h) ([raw file](https://github.com/harness/harness-core/blob/6e6192fe0db21879399797d71a78e50ecc8dd51d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java#L19)):*
> ```Java
> @UtilityClass
> class CDNGPlanCreatorConstants {
>   static final String ECS_TASK_DEF = ManifestType.EcsTaskDefinition;
> ```

why we don't directly use these constants?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java` line 31 at r10](https://reviewable.io/reviews/harness/harness-core/36987#-NCPrjnZCXik79Y9n-0Q:-NCPrjnZCXik79Y9n-0R:btnqb9q) ([raw file](https://github.com/harness/harness-core/blob/6e6192fe0db21879399797d71a78e50ecc8dd51d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java#L31)):*
> ```Java
>   static final String OPENSHIFT_PARAM = ManifestType.OpenshiftParam;
> 
>   static final String CUSTOM_ARTIFACT = "CustomArtifact";
> ```

these must also be present somewhere, try full Intellij search
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java` line 42 at r10](https://reviewable.io/reviews/harness/harness-core/36987#-NCPrn8_CkM11h9KmVhE:-NCPrn8_CkM11h9KmVhF:b-tdp6et) ([raw file](https://github.com/harness/harness-core/blob/6e6192fe0db21879399797d71a78e50ecc8dd51d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java#L42)):*
> ```Java
>   static final String GCR = "Gcr";
> 
>   static final String SERVERLESS_AWS_LAMBDA = "ServerlessAwsLambda";
> ```

these must also be present somewhere, try full search


<!-- Sent from Reviewable.io -->

2022-09-21 18:43 UTC, Fernando-Dourado reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 2 file(s) to review. 2 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java` line 19 at r10](https://reviewable.io/reviews/harness/harness-core/36987#-NCPrfpy9WqK9ms2nXZq:-NCWLadm3HJINjrAhyZq:bb76ne4) ([raw file](https://github.com/harness/harness-core/blob/6e6192fe0db21879399797d71a78e50ecc8dd51d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java#L19)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

why we don't directly use these constants?
</blockquote></details>

Wipe
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java` line 31 at r10](https://reviewable.io/reviews/harness/harness-core/36987#-NCPrjnZCXik79Y9n-0Q:-NCWLlrY4V-Cjwde0dN3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e6192fe0db21879399797d71a78e50ecc8dd51d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java#L31)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

these must also be present somewhere, try full Intellij search
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java` line 42 at r10](https://reviewable.io/reviews/harness/harness-core/36987#-NCPrn8_CkM11h9KmVhE:-NCWLml35xpr12yXfzWa:b933jzd) ([raw file](https://github.com/harness/harness-core/blob/6e6192fe0db21879399797d71a78e50ecc8dd51d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorConstants.java#L42)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

these must also be present somewhere, try full search
</blockquote></details>

After the full search, only Azure and Helm were not found with valid references.


<!-- Sent from Reviewable.io -->

2022-09-22 12:14 UTC, vaibhav-si submitted a review, later dismissed
> Reviewed 2 of 7 files at r2, 1 of 8 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-22 12:46 UTC, ankittiwari-harness submitted a review, later dismissed

2022-09-22 14:52 UTC, Fernando-Dourado commented
trigger compile, codebasehash, ti0

2022-09-23 11:22 UTC, Fernando-Dourado reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/36987#-NBQS6pZ-pXsXAA14OYz:-NCMOlxzEfFXtPw-H5W3:b3nlsza) ([raw file](https://github.com/harness/harness-core/blob/2912339554a3bee2730ef021b46887547e80ebfb/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java#L55)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Maybe we can simplify this using Sets.intersection (https://www.geeksforgeeks.org/sets-intersection-function-guava-java/)
if the intersection size is equal to both filter creators and variable creators, we are good else there is some discrepancy which we can calculate.
</blockquote></details>

Not sure if it cover our case.


<!-- Sent from Reviewable.io -->

2022-09-23 11:52 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 2 of 4 files at r3, 3 of 5 files at r5, 1 of 1 files at r6, 1 of 11 files at r8, 7 of 8 files at r10, 1 of 2 files at r11, 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 7 file(s) to review. 1. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-23 20:15 UTC, r0610205 submitted a review, later dismissed

2022-09-26 09:30 UTC, vaibhav-si approved these changes
> Reviewed 6 of 7 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-26 11:32 UTC, ankittiwari-harness approved these changes
> Reviewed 3 of 7 files at r2, 2 of 4 files at r3, 3 of 5 files at r5, 1 of 1 files at r6, 1 of 11 files at r8, 7 of 8 files at r10, 1 of 7 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-26 11:53 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-26 18:26 UTC, r0610205 approved these changes
> Reviewed 3 of 7 files at r2, 2 of 4 files at r3, 3 of 5 files at r5, 1 of 1 files at r6, 1 of 11 files at r8, 7 of 8 files at r10, 1 of 7 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36987)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-26 18:29 UTC, merged