[fix]: [PL-27872]: Handle Azure KeyVaultErrorException in Secrets Management
harness/harness-core pull request #37033
Opened 2022-09-01 20:29 UTC by Raghav-Murali

## Describe your changes
This PR handles the KeyVaultErrorException thrown by Azure vault in case of an error scenario. Previously, the exception was just being embedded within the custom SecretManagementDelegateException that extends WingsException. However, since the KeyVaultErrorException doesn't extend WingsException the error message contained within it gets lost and thus useful info is not shown to the end user in the UI. This leads to more debugging at the delegate side and request of the logs from the customer environment. With this change the detailed error message and code contained in the KeyVaultErrorException provides sufficient information to the user on what exactly went wrong and allows them to fix the error on their own.

The KeyVaultErrorException need not be retried thus it's also handled only once. 

Additional adjustments were made in the renameSecret() code to fetch the secret only once at the beginning rather than fetching it 3 times which will yield the same outcome.

[Test Scenario] - Save a new secret with name containing “_” (ex: My_Azure_Secret or MyAzureSecret_1).
[Test Outcome] - Outcome: Apparently, Azure doesn’t allow secret names to include meta-chars in them thus it throws a “KeyVaultErrorException”.

[Prior Error Message on UI]-
Azure Key Vault Operation error: After 3 tries, encryption for secret My_Azure_Secret failed.
Azure Key Vault Operation error: The Secret could not be saved in Azure Vault. 
accountId: wFHXHD0RRQWoO8tIZT5YVw, Secret name: My_Azure_Secret, 
Vault name: QAAutomationKeyVault

[New Error Message on UI with this fix]-
Azure Key Vault Operation error: The Secret could not be saved in Azure Vault. 
accountId: kmpySmUISimoRrJL6NL73w, Secret name: My_Azure_Secret, 
error code: BadParameter, error message: The request URI contains an invalid name: My_Azure_Secret

As seen above the error code and message contained in the KeyVaultErrorException provides sufficient details on what needs to be corrected.

## Checklist
- [Yes] I've documented the changes in the PR description - Check [PL-27872](https://harness.atlassian.net/browse/PL-27872) for detailed summary.
- [Yes] I've tested this change either in PR or local environment - I have verified this change in the local test environment for secret creation and update. Will test it further in PR environment.
- [Not Yet] I've added unit tests to verify the changes - I will be adding unit tests in my next commit since renaming secret is not being covered in the tests above due to no option to rename a secret in the UI.
- [ N/A ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

2022-09-01 20:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=37033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=37033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=37033) it.</sub>

2022-09-01 20:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=37033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=37033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=37033) it.</sub>

2022-09-01 20:32 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 1 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37033)

2022-09-01 21:36 UTC, rickmarry requested changes

2022-09-01 21:36 UTC, rickmarry commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +    String secretName = value.toString();
value is an array char[]..  if you want to print it, you should call Arrays.toString(value)

2022-09-01 21:36 UTC, rickmarry commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +      if (ex instanceof KeyVaultErrorException) {
Since all we do it throw this, we should just give it it's own Catch instead of doing this instanceof call

2022-09-01 21:36 UTC, rickmarry commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +    String message =
don't really need this message variable if we're just immediately returning it

2022-09-01 22:35 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +      if (ex instanceof KeyVaultErrorException) {
Sure, will update it.

2022-09-01 22:36 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +    String message =
Ah yes, done.

2022-09-01 22:40 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +    String secretName = value.toString();
Actually just need the string to pass it to another function.

2022-09-06 19:10 UTC, rickmarry approved these changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/37033#-NAujm2odFYJTDeBhwEw-r1-132:-NBJBaJl8JWVbi9DMIIr:b-1cyu7w) ([raw file](https://github.com/harness/harness-core/blob/4c83ae50e144dca5e2f45f5de40bb31f156d6c3e/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L132)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Actually just need the string to pass it to another function. But after doing more tests I've updated this part of the code now.
</blockquote></details>

thank you
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/37033#-NAujm2odFYJTDeBhwEw-r1-169:-NBJBJJf-Jk4Tc1gIfxP:b-47fafm) ([raw file](https://github.com/harness/harness-core/blob/4c83ae50e144dca5e2f45f5de40bb31f156d6c3e/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L169)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Sure, will update it.
</blockquote></details>

looks good
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/37033#-NAujm2odFYJTDeBhwEw-r1-194:-NBJBSZU3hRaxMCyq7J0:bb7lbs2) ([raw file](https://github.com/harness/harness-core/blob/4c83ae50e144dca5e2f45f5de40bb31f156d6c3e/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L194)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Ah yes, done.
</blockquote></details>

nice


<!-- Sent from Reviewable.io -->

2022-09-07 20:46 UTC, Raghav-Murali commented
trigger feature-build

2022-09-07 23:04 UTC, gn-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 185 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBPBLWGBLwVGLys9KhW:-NBPBLWGBLwVGLys9KhX:bcx3eyr) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L185)):*
> ```Java
>     String errorMsg = keyVaultEx.body().error().message();
>     String errorCode = keyVaultEx.body().error().code();
>     return format("Azure Key Vault exception received. accountId: %s, Secret name: %s, "
> ```

Is there any value in showing accountId and Secret name to the end user again?

Might make sense to log it though



_Code quote:_
```Java
accountId: %s, Secret name: %s, "
```


<!-- Sent from Reviewable.io -->

2022-09-07 23:13 UTC, gn-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java` line 152 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBPDJUq6hhYxFwaOmin:-NBPDJUq6hhYxFwaOmio:bqeoxfm) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java#L152)):*
> ```Java
>     } catch (Exception e) {
>       fail("Wrong exception was thrown - KeyVaultErrorException expected");
>     }
> ```

assertThrows does not work?



_Code quote:_
```Java
    try {
      azureVaultEncryptor.createSecret(azureVaultConfig.getAccountId(), name, plainText, azureVaultConfig);
    } catch (SecretManagementDelegateException e) {
      String errorMsg = e.getMessage();
      assertThat(errorMsg).contains("The request URI contains an invalid name: My_Azure_Secret");
      assertThat(errorMsg).contains("BadParameter");
    } catch (Exception e) {
      fail("Wrong exception was thrown - KeyVaultErrorException expected");
    }
```


<!-- Sent from Reviewable.io -->

2022-09-08 12:32 UTC, nishantsaini20 requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBS3YtZ2-8gXnntt8Zi:-NBS3YtZ2-8gXnntt8Zj:b-1jgz5p) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L72)):*
> ```Java
>         // Key Vault Error Exception is non-retryable
>         throw new SecretManagementDelegateException(
>             AZURE_KEY_VAULT_OPERATION_ERROR, prepareKeyVaultErrorMessage(e, accountId, name), e, USER);
> ```

Are we sure on this? Can we still keep retries to avoid any unforeseen issue?
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBS3_NK1vKIAYaEAggg:-NBS3_NK1vKIAYaEAggh:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L132)):*
> ```Java
>         // Key Vault Error Exception is non-retryable
>         throw new SecretManagementDelegateException(
>             AZURE_KEY_VAULT_OPERATION_ERROR, prepareKeyVaultErrorMessage(e, accountId, name), e, USER);
> ```

same here


<!-- Sent from Reviewable.io -->

2022-09-08 19:30 UTC, Raghav-Murali reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java` line 152 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBPDJUq6hhYxFwaOmin:-NBTHuWi0r49kZErWwGT:bq0g3y3) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java#L152)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

assertThrows does not work?
</blockquote></details>

I didn't try assertThrows. Looks like assertThrows is replaced with assertThatThrownBy, so I have updated the tests with that.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBS3YtZ2-8gXnntt8Zi:-NBTI9c2Cgxg6oqCtnTF:bg06i0o) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L72)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Are we sure on this? Can we still keep retries to avoid any unforeseen issue?
</blockquote></details>

I came to this conclusion based on the below 2 points -

1. The errors for which KeyVault exception is thrown is provided here - https://docs.microsoft.com/en-us/azure/key-vault/general/common-error-codes and https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal?source=recommendations (the name of secret should only be "0-9, a-z, A-Z, and -" else it includes a BadParameter error). So looking at the descriptions of these error codes it looked like the outcome will always be the same despite trying for multiple times.
2. The setSecret() of Azure vault client invokes the setSecretDelegate() of com.microsoft.azure.keyvault.implementation package which uses a RestClient that comes with its own RetryHandler and RetryStrategy. And as per this article - https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults its suggested to have a retry mechanism only if there is no built-in retry mechanism in the client library and only for transient failures. All the failures / errors indicated above are non-transient since the input to the request is going to remain same.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBS3_NK1vKIAYaEAggg:-NBT_71CA5Nbi49Xz6L7:b-d22waz) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L132)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Same response as above.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 185 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBPBLWGBLwVGLys9KhW:-NBTHfv12iqhVsUU4Cac:b-2va04r) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L185)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Is there any value in showing accountId and Secret name to the end user again?

Might make sense to log it though
</blockquote></details>

Will update it.


<!-- Sent from Reviewable.io -->

2022-09-08 19:38 UTC, Raghav-Murali reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBS3YtZ2-8gXnntt8Zi:-NBT_L1vB8nOBLQ-fEhL:b-fwf5ws) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L72)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

I came to this conclusion based on the below 2 points -

1. The errors for which KeyVault exception is thrown is provided here - https://docs.microsoft.com/en-us/azure/key-vault/general/common-error-codes and https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal?source=recommendations (the name of secret should only be "0-9, a-z, A-Z, and -" else it includes a BadParameter error). So looking at the descriptions of these error codes it looked like the outcome will always be the same despite trying for multiple times.
2. The setSecret() of Azure vault client invokes the setSecretDelegate() of com.microsoft.azure.keyvault.implementation package which uses a RestClient that comes with its own RetryHandler and RetryStrategy. And as per this article - https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults its suggested to have a retry mechanism only if there is no built-in retry mechanism in the client library and only for transient failures. All the failures / errors indicated above are non-transient since the input to the request is going to remain same.
</blockquote></details>

Let me know if these points are not convincing and if you'd still prefer to have explicit retries. 


<!-- Sent from Reviewable.io -->

2022-09-08 22:27 UTC, Raghav-Murali commented
trigger feature-build

2022-09-08 22:55 UTC, gn-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java` line 143 at r4](https://reviewable.io/reviews/harness/harness-core/37033#-NBUITxU3bxAKN82AoiO:-NBUITxU3bxAKN82AoiP:b-gp975t) ([raw file](https://github.com/harness/harness-core/blob/221dbf973d610772b9ce9d6f6f0af0efcb0b9820/890-sm-core/src/test/java/io/harness/encryptors/AzureVaultEncryptorTest.java#L143)):*
> ```Java
>       // unable to process json
>       fail("Json processing error");
>     }
> ```


nit: Same here, we should not be catching exceptions in the tests cases - does not solve a purpose.



_Code quote:_
```Java
    try {
      KeyVaultError error = objectMapper.readValue(errorJson, KeyVaultError.class);
      when(keyVaultClient.setSecret(any(SetSecretRequest.class)))
          .thenThrow(
              new KeyVaultErrorException("The request URI contains an invalid name: My_Azure_Secret", null, error));
    } catch (Exception e) {
      // unable to process json
      fail("Json processing error");
    }
```
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/37033#-NBS3YtZ2-8gXnntt8Zi:-NBUIw-74Hdsro-ayqiU:b-mkiafr) ([raw file](https://github.com/harness/harness-core/blob/f8ef7201e5b0d64f27cf8a69e9b38e0ce72eabcc/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L72)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Let me know if these points are not convincing and if you'd still prefer to have explicit retries. 
</blockquote></details>

My two cents: Looks good to me, retries should generally be based on the error code type. @piyush-harness Do you have any input?


<!-- Sent from Reviewable.io -->

2022-09-15 11:45 UTC, meenakshi-harness commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +        char[] value = fetchSecretValueInternal(existingRecord, azureConfig);
Why we moved this out of time limiter?

2022-09-15 11:47 UTC, meenakshi-harness commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +    log.warn(message + " accountId: %s, Secret name: %s ", accountId, fullSecretName);
We should log whole exception. And also use log.error

2022-09-15 20:21 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +        char[] value = fetchSecretValueInternal(existingRecord, azureConfig);
Yes, I overlooked that a Get call is being made to Azure client in fetchSecretValueInternal. I will move it back into the timer. Thanks.

2022-09-15 20:21 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +    log.warn(message + " accountId: %s, Secret name: %s ", accountId, fullSecretName);
Done.

2022-09-19 20:06 UTC, meenakshi-harness approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-20 07:04 UTC, nishantsaini20 approved these changes
> Reviewed 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-20 14:49 UTC, gn-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-20 19:08 UTC, Raghav-Murali reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 4. unresolved discussions. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/37033#-NAujm2odFYJTDeBhwEw-r1-132:-NCRIAE97p9lD7vL-skF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c83ae50e144dca5e2f45f5de40bb31f156d6c3e/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L132)):*
<details><summary><i>Previously, rickmarry (Rick Marry) wrote…</i></summary><blockquote>

thank you
</blockquote></details>

Done.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/37033#-NAujm2odFYJTDeBhwEw-r1-169:-NCRIAws1j_SchsCmq9G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c83ae50e144dca5e2f45f5de40bb31f156d6c3e/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L169)):*
<details><summary><i>Previously, rickmarry (Rick Marry) wrote…</i></summary><blockquote>

looks good
</blockquote></details>

Done.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/37033#-NAujm2odFYJTDeBhwEw-r1-194:-NCRIBtwAcQIk_xU3o-7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c83ae50e144dca5e2f45f5de40bb31f156d6c3e/890-sm-delegate/src/main/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L194)):*
<details><summary><i>Previously, rickmarry (Rick Marry) wrote…</i></summary><blockquote>

nice
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-20 19:16 UTC, rickmarry approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-21 05:13 UTC, meenakshi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37033)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-21 05:15 UTC, merged