fix: [CI-4350]: Remove StageElementConfig and StepElementConfig to St…
harness/harness-core pull request #37100
Opened 2022-09-04 16:17 UTC by smjt-h

…ageNode and stepNode

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-04 16:21 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 24 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 5 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 17 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37100)

2022-09-09 12:13 UTC, harshjain12 commented
@archit-harness It will break backaward compatibility and plan which are already created before deployment might get break.
I think only option is to do deployment on weekend.

2022-09-09 13:10 UTC, archit-harness requested changes
> Reviewed 37 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37100)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/app/impl/CIYamlSchemaServiceImpl.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXDjr50Gc_jp5UrA4a:-NBXDjr50Gc_jp5UrA4b:bujogap) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/332-ci-manager/service/src/main/java/io/harness/ci/app/impl/CIYamlSchemaServiceImpl.java#L59)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CI)
> public class CIYamlSchemaServiceImpl implements CIYamlSchemaService {
> ```

@brijeshdhakar can you review this code part, does it needs to be done as part of this PR or separately when we need to make changes for all schema files for all services?
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXFSUX9x7EfFXi1kpr:-NBXFSUX9x7EfFXi1kps:b8jmpfm) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java#L49)):*
> ```Java
>   IntegrationStageConfigImpl integrationStageConfig;
> 
>   //  @VariableExpression(skipVariableExpression = true) List<FailureStrategyConfig> failureStrategies;
> ```

Can we remove this?



_Code quote:_
```Java
//  @VariableExpression(skipVariableExpression = true) List<FailureStrate
```
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXGTrb4KOblrMcNNOP:-NBXGTrb4KOblrMcNNOQ:b-yn6fh0) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java#L70)):*
> ```Java
> 
>   public List<FailureStrategyConfig> getFailureStrategies() {
>     return this.failureStrategies;
> ```

why we need this?



_Code quote:_
```Java
  public List<FailureStrategyConfig> getFailureStrategies() {
    return this.failureStrategies;
```
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXLLZL4Gb3XoMtLSCT:-NBXLLZL4Gb3XoMtLSCU:by7qwyq) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java#L124)):*
> ```Java
>     filterJsonCreators.add(new ExecutionPMSFilterJsonCreator());
>     filterJsonCreators.add(new ParallelGenericFilterJsonCreator());
>     injectorUtils.injectMembers(filterJsonCreators);
> ```

Can you add filter jsonCreator for InitialiseStep as well, it could be doing nothing
___
*[`960-yaml-sdk/src/main/java/io/harness/yaml/utils/YamlSchemaUtils.java` line 428 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXML3P1QDAbRXyZU4l:-NBXML3P1QDAbRXyZU4m:bcja02t) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/960-yaml-sdk/src/main/java/io/harness/yaml/utils/YamlSchemaUtils.java#L428)):*
> ```Java
>       String stepElementConfigRef = executionWrapperConfig.get(nodeLevel).get(REF_NODE).toString().replace("\"", "");
>       JsonNodeUtils.deletePropertiesInJsonNode((ObjectNode) stepsNode, REF_NODE);
>       //      oneOfList.add(JsonNodeUtils.upsertPropertyInObjectNode(
> ```

why we commented these out?
___
*[`960-yaml-sdk/src/test/java/io/harness/yaml/utils/YamlSchemaUtilsTest.java` line 244 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXMOXW9GxULbb5i1_B:-NBXMOXW9GxULbb5i1_C:b-2l18my) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/960-yaml-sdk/src/test/java/io/harness/yaml/utils/YamlSchemaUtilsTest.java#L244)):*
> ```Java
>         yamlSchemaWithDetailsList, ModuleType.CD, Collections.singleton("FF1"), Collections.emptyMap());
>     oneOfNode = getOneOfNodeFromSchema(schema);
>     assertEquals(oneOfNode.size(), 0);
> ```

why this test change?
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXMRqy25nPTBoHtuU7:-NBXMRqy25nPTBoHtuU8:b-kn3mb1) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java#L32)):*
> ```Java
>   String CV_VERIFICATION_JOB = "CvVerificationJob";
>   String INTEGRATION_STAGE = "IntegrationStage";
>   String CI_ABSTRACT = "CiAbstract";
> ```

These constants are needed in ci serivce or anywhere else as well? if only ci, then we should not create in this class
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXMmfiBIwE96WCt94t:-NBXMmfiBIwE96WCt94u:b-rwz75o) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java#L45)):*
> ```Java
>   public static final String CV_VERIFICATION_JOB = "cvVerificationJob";
>   public static final String INTEGRATION_STAGE = "integrationStage";
>   public static final String CI_ABSTRACT = "ciabstract";
> ```

why these are needed?



_Code quote:_
```Java
CI_ABSTRACT
```


<!-- Sent from Reviewable.io -->

2022-09-13 05:31 UTC, smjt-h reviewed
tested a pipeline execution with old plan, executed successfully

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37100#-:-NBpJWky-24pk0E1to5l:b-41uh17)* status: 15 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXFSUX9x7EfFXi1kpr:-NBpJmAZ-VvMJa_Zfkpz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java#L49)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we remove this?
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXGTrb4KOblrMcNNOP:-NBpJq2-EwIAHaMq4roa:bkoct0k) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we need this?
</blockquote></details>

it has failureStrategy in parent class
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXLLZL4Gb3XoMtLSCT:-NBpJx9o9mAl9TmkUriB:b-bzbfk3) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CIPipelineServiceInfoProvider.java#L124)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you add filter jsonCreator for InitialiseStep as well, it could be doing nothing
</blockquote></details>

removed initializeStepNode as it was not Revere
___
*[`960-yaml-sdk/src/main/java/io/harness/yaml/utils/YamlSchemaUtils.java` line 428 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXML3P1QDAbRXyZU4l:-NBpK61w3aBH6uCbE8nz:bvth56w) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/960-yaml-sdk/src/main/java/io/harness/yaml/utils/YamlSchemaUtils.java#L428)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we commented these out?
</blockquote></details>

reverted
___
*[`960-yaml-sdk/src/test/java/io/harness/yaml/utils/YamlSchemaUtilsTest.java` line 244 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXMOXW9GxULbb5i1_B:-NBpKCfn-x2BOKqgqUt6:bvth56w) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/960-yaml-sdk/src/test/java/io/harness/yaml/utils/YamlSchemaUtilsTest.java#L244)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this test change?
</blockquote></details>

reverted
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXMRqy25nPTBoHtuU7:-NBpKEsz9an0dSm9GzVx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

These constants are needed in ci serivce or anywhere else as well? if only ci, then we should not create in this class
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/37100#-NBXMmfiBIwE96WCt94t:-NBpKG4x4Y75byyxEZTY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a4050619bbf5c1b8919a522434651a5acd17878/970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why these are needed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-13 12:17 UTC, harshjain12 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 25 of 43 files at r1, 10 of 15 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37100#-:-NBqm05Q4KpfPoq_wQt8:bnfp4nl)* status: 1 change requests. 7. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-14 04:54 UTC, archit-harness requested changes
> Reviewed 8 of 15 files at r2, 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37100)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CICreatorUtils.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/37100#-NBuL34SDSeXIq2AdWv9:-NBuL34SDSeXIq2AdWvA:bhele2f) ([raw file](https://github.com/harness/harness-core/blob/4a787a4ea8a0009428eb07123dffebcec8c287ee/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CICreatorUtils.java#L20)):*
> ```Java
>   public static Set<String> getSupportedSteps() {
>     // These are internal steps does not need to be in V2
>     return Sets.newHashSet("Test", "SaveCache", "GitClone", "Cleanup", "PublishArtifacts");
> ```

Why cant we move them to V2? we want to remove all v1 impl



_Code quote:_
```Java
return Sets.newHashSet("Test", "SaveCache", "GitClone", "Cleanup", "PublishArtifacts");
```
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/37100#-NBuLF5_9IlT2V-Qls12:-NBuLF5_9IlT2V-Qls13:b-1ktglq) ([raw file](https://github.com/harness/harness-core/blob/4a787a4ea8a0009428eb07123dffebcec8c287ee/970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java#L72)):*
> ```Java
>   String SECURITY_STEPS = "SecuritySteps";
>   String GIT_CLONE = "GitClone";
>   String INITIALIZE = "Initialize";
> ```

Same we should not create CI constants in this common constant class unless required across services



_Code quote:_
```Java
String INITIALIZE = "Initialize";
```
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java` line 95 at r3](https://reviewable.io/reviews/harness/harness-core/37100#-NBuLNj983Y12MHiq4_x:-NBuLNj983Y12MHiq4_y:bw7wmzd) ([raw file](https://github.com/harness/harness-core/blob/4a787a4ea8a0009428eb07123dffebcec8c287ee/970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java#L95)):*
> ```Java
>   public static final String SECURITY_STEP = "securitySteps";
>   public static final String GIT_CLONE = "GitClone";
>   public static final String INITIALIZE = "Initialize";
> ```

Why this is needed?



_Code quote:_
```Java
public static final String INITIALIZE = "Initialize";
```


<!-- Sent from Reviewable.io -->

2022-09-14 06:54 UTC, smjt-h reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37100)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CICreatorUtils.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/37100#-NBuL34SDSeXIq2AdWv9:-NBuljqC70cQFDLR9skC:bmhtrjb) ([raw file](https://github.com/harness/harness-core/blob/4a787a4ea8a0009428eb07123dffebcec8c287ee/332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/CICreatorUtils.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why cant we move them to V2? we want to remove all v1 impl
</blockquote></details>

These are implicit steps, not needed in v2
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/37100#-NBuLF5_9IlT2V-Qls12:-NBulhke0fnUSD5j5BwV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a787a4ea8a0009428eb07123dffebcec8c287ee/970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Same we should not create CI constants in this common constant class unless required across services
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java` line 95 at r3](https://reviewable.io/reviews/harness/harness-core/37100#-NBuLNj983Y12MHiq4_x:-NBulhDO0CYqI5qUyc2p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4a787a4ea8a0009428eb07123dffebcec8c287ee/970-ng-commons/src/main/java/io/harness/common/EntityYamlRootNames.java#L95)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why this is needed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-14 10:55 UTC, harshjain12 reviewed
> Reviewed 1 of 1 files at r4, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37100)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-14 10:56 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37100)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-14 11:09 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/CiStageParametersUtils.java
> +public class CiStageParametersUtils {
Ci --> CI

2022-09-14 11:12 UTC, harshjain12 commented on 315-sto-manager/src/main/java/io/harness/sto/plan/creator/stage/SecurityStagePMSPlanCreator.java
> +    return null;
copy code of integration stage here.
It can not be null

2022-09-14 11:16 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage/IntegrationStagePMSPlanCreatorV2.java
> +    StageElementParametersBuilder stageParameters = CiStageParametersUtils.getStageParameters(stageNode);
CiStageParametersUtil --> CIStagePlanCreationUtils

2022-09-15 10:13 UTC, merged