[feat]: [CDS-42743]: Azure Artifacts Connector
harness/harness-core pull request #37117
Opened 2022-09-05 09:50 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-05 09:54 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37117)

2022-09-20 09:04 UTC, puthrayaharness requested changes

2022-09-20 09:04 UTC, puthrayaharness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azureartifacts/AzureArtifactsConnectionTypeDTO.java
> +  @JsonProperty(GitConfigConstants.PROJECT) PROJECT,
Why are these GitConfigConstants?

2022-09-20 09:04 UTC, puthrayaharness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azureartifacts/AzureArtifactsConnectionTypeDTO.java
> +  @JsonProperty(GitConfigConstants.REPO) REPO
Where are using these?

2022-09-20 09:04 UTC, puthrayaharness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azureartifacts/AzureArtifactsConnectorConstants.java
> +  public static final String USERNAME_AND_TOKEN = "UsernameToken";
Does Azure Artifacts support Username & Token?

2022-09-20 09:04 UTC, puthrayaharness commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  NG_AZURE_ARTIFACTS,
`AZURE_ARTIFACTS_NG`

2022-09-20 09:04 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/client/AzureArtifactsRestClientFactoryImpl.java
> +      throw new InvalidArtifactServerException("Azure DevOps URL is invalid");
Please throw Hint/Explanation exception

2022-09-20 09:04 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/client/AzureArtifactsRegistryRestClient.java
> +public interface AzureArtifactsRegistryRestClient {
Why are we recreating these? We already have all this in CG? We should be resuing the code from CG...

2022-09-24 05:04 UTC, puthrayaharness requested changes

2022-09-24 05:04 UTC, puthrayaharness commented on 440-connector-nextgen/src/main/java/io/harness/connector/mappers/azureartifacts/AzureArtifactsDTOToEntity.java
> +      case USERNAME_AND_TOKEN:
Where do we have username/Password? We just have token auth in Azure Artifacts?

2022-09-24 05:04 UTC, puthrayaharness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azureartifacts/AzureArtifactsConnectorDTO.java
> +  Boolean executeOnDelegate = true;
Why do need this? Where do we have executeOnDelegate?

2022-09-24 05:04 UTC, puthrayaharness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azureartifacts/AzureArtifactsConnectorDTO.java
> +  @NotBlank @NotNull @Schema(description = "SSH or HTTP URL based on type of connection") String url;
Where is SSH URL?

2022-09-24 05:04 UTC, puthrayaharness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azureartifacts/AzureArtifactsConnectorDTO.java
> +  public GitRepositoryDTO getGitRepositoryDetails() {
Where do we have GitRepo with Azure.

2022-09-24 05:04 UTC, puthrayaharness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azureartifacts/AzureArtifactsToGitMapper.java
> +      case SSH:
Where do we have SSH?

2022-09-24 05:24 UTC, puthrayaharness requested changes

2022-09-24 05:24 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/azureartifacts/AzureArtifactsTaskHelper.java
> +          saveLogs(executionLogCallback, "Validating  Artifact Server");
Please fix the logs in the whole file

2022-09-25 18:00 UTC, vtxorxwitty commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +      AzureArtifactsDelegateResponse azureArtifactsDelegateResponse, boolean useDelegateResponse) {
We are not using it anywhere. But this field is added for all the artifact source including docker, artifactory, s3, github...

2022-09-29 06:44 UTC, closed without merging