[feat]: [PL-25242]: validate url for connectors to prevent XSS attack.
harness/harness-core pull request #37221
Opened 2022-09-06 15:46 UTC by shreyas-harness

## Describe your changes
This PR is to add URL annotation to any field that is a URL. URL are being stored as string which allows user to pass any random / incorrect / and potentially malicious strings and they get into our system.
Adding `@URL` annotation does the first level of check ensuring that the passed URL follows the standards.
This does not guarantee that the passed URL is correct but acts as first level of defence. The URL passed may not even exist but if it follows the standard, its accepted. 

We have used Hibernate URL validator library to validate URL's
The default acceptable protocols which are guaranteed by JVM are **http, https, ftp, file, and jar**
If there is any need of other protocols we can pass it as a parameter. 

What we expect from each team:
1- Add single line comment Approve based on connectors owned by specific teams.
2- In case, we have added this annotation that is not expected to be a URL, mention us to remove it.
3- I have tried best to find across all connectors any URL field, but might have missed few. Each team should ensure that if there are any other place where we need this annotation, they should mention it and we will update the PR accordingly.

To see the current behaviour - here are few connectors
<img width="1728" alt="Screenshot 2022-09-06 at 6 27 59 PM" src="https://user-images.githubusercontent.com/105028678/188677536-e88641d7-c8d1-4197-9fa1-e4316e2c21ba.png">

<img width="1728" alt="Screenshot 2022-09-06 at 6 28 43 PM" src="https://user-images.githubusercontent.com/105028678/188677591-f834fd8a-d12c-48dc-9f3d-08ad2b9b1bab.png">

<img width="1728" alt="Screenshot 2022-09-06 at 6 29 10 PM" src="https://user-images.githubusercontent.com/105028678/188677639-07f9fc8f-a699-4022-87a3-bc79a7c30b5e.png">

After the changes, on putting incorrect url ( random_incorrect_url ) , error would be displayed like this. 
The incorrect URL message will come at the time, create connector request is called on Backend. FE needs to support similar logic for URL validation for individual connectors to ensure correct message is displayed on right screen. 

<img width="1725" alt="Screenshot 2022-09-06 at 9 11 14 PM" src="https://user-images.githubusercontent.com/105028678/188678191-5645b4da-2656-42b8-a9d0-b2055ca01fdf.png">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-06 15:49 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37221)

2022-09-07 04:18 UTC, nishantsaini20 requested changes
> Reviewed 1 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37221#-NBL94USAtXLFHPKUXd_:-NBL94USAtXLFHPKUXda:b-jypos6) ([raw file](https://github.com/harness/harness-core/blob/8fdb4356dddfe81550f986b6a6bc4fe07bcd2c91/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java#L52)):*
> ```Java
>     });
>     String exceptionMessage =
>         validationErrors.stream().map(ValidationError::getError).collect(Collectors.joining(", "));
> ```

This is changing the response structure. Exception message is lost. Why do we need to this when validation errors are already part of the response?


<!-- Sent from Reviewable.io -->

2022-09-07 04:36 UTC, shreyas-harness commented
> This is changing the response structure. Exception message is lost. Why do we need to this when validation errors are already part of the response?

We have logged the error before this. This is to hide path from users as exception.getMessage() contains path which is used by FE to display error.

2022-09-07 04:38 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: 27 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37221#-NBL94USAtXLFHPKUXd_:-NBLEDQw-ewsSh0CIaGo:b-h1p91z) ([raw file](https://github.com/harness/harness-core/blob/8fdb4356dddfe81550f986b6a6bc4fe07bcd2c91/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java#L52)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This is changing the response structure. Exception message is lost. Why do we need to this when validation errors are already part of the response?
</blockquote></details>

We have logged the error before this. This is to hide path from users as exception.getMessage() contains class path which is used by FE to display error. 


<!-- Sent from Reviewable.io -->

2022-09-07 05:02 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37221#-NBL94USAtXLFHPKUXd_:-NBLJ7Gj-Fe6Z4YXiw37:bfq7wer) ([raw file](https://github.com/harness/harness-core/blob/8fdb4356dddfe81550f986b6a6bc4fe07bcd2c91/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java#L52)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

We have logged the error before this. This is to hide path from users as exception.getMessage() contains class path which is used by FE to display error. 
</blockquote></details>

But this change will omit message for any other violation exception as well. 


<!-- Sent from Reviewable.io -->

2022-09-07 07:22 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: 27 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37221#-NBL94USAtXLFHPKUXd_:-NBLp-e227EWm4Gj-UNg:b-ipqgud) ([raw file](https://github.com/harness/harness-core/blob/8fdb4356dddfe81550f986b6a6bc4fe07bcd2c91/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/JerseyViolationExceptionMapperV2.java#L52)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

But this change will omit message for any other violation exception as well. 
</blockquote></details>

Discussed offline and changed the message structure as decided


<!-- Sent from Reviewable.io -->

2022-09-07 07:24 UTC, shreyas-harness commented
trigger codebasehash

2022-09-07 08:22 UTC, shreyas-harness commented
trigger codebasehash

2022-09-07 09:06 UTC, nishantsaini20 reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-07 10:10 UTC, shivamnegi94 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/docker/DockerConnectorDTO.java
> +  @URL @NotNull @NotBlank String dockerRegistryUrl;
Approved

2022-09-07 10:10 UTC, shivamnegi94 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/jenkins/JenkinsConnectorDTO.java
> +  @URL @NotNull @NotBlank String jenkinsUrl;
Approved

2022-09-07 10:10 UTC, shivamnegi94 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/jira/JiraConnectorDTO.java
> +  @URL @NotNull @NotBlank String jiraUrl;
Approved

2022-09-07 10:12 UTC, shivamnegi94 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/nexusconnector/NexusConnectorDTO.java
> +  @URL @NotNull @NotBlank String nexusServerUrl;
Approved

2022-09-07 10:47 UTC, piyush-harness submitted a review, later dismissed
> Reviewed 25 of 27 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: 25 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-09 06:56 UTC, namantalaycha10 commented
@shreyas-harness URL annotation will not work with OCI helm connector , this will throw the error mention in this SS
Please remove this changes of the OCI helm connector
<img width="1323" alt="Screenshot 2022-09-09 at 10 09 09 AM" src="https://user-images.githubusercontent.com/84320791/189289568-95dbe07d-e137-44fb-a4c2-3a9e1f72eba3.png">

2022-09-09 09:24 UTC, devkimittal commented
this pr env you provided https://plat.pr.harness.io/pl-25242/ng/#/account/kmpySmUISimoRrJL6NL73w/settings/resources/connectors
Can you please wake it up?

2022-09-09 10:32 UTC, devkimittal commented
Ssh urls are failng for github, gitlab, bitbucket, aws, azure repo connectors.
<img width="1312" alt="Screenshot 2022-09-09 at 4 01 17 PM" src="https://user-images.githubusercontent.com/99166403/189330813-307565ea-dd32-4d82-9ff2-ec3f0033c591.png">

2022-09-09 10:50 UTC, shivamnegi94 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/artifactoryconnector/ArtifactoryConnectorDTO.java
> +  @URL @NotNull @NotBlank String artifactoryServerUrl;
Approved

2022-09-09 10:50 UTC, shivamnegi94 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/servicenow/ServiceNowConnectorDTO.java
> +  @URL @NotNull @NotBlank String serviceNowUrl;
Approved

2022-09-09 11:05 UTC, devkimittal commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/genericgitconnector/GitConfigDTO.java
> +  @URL @NotNull @NotBlank String url;
please remove here as well.

2022-09-09 11:05 UTC, devkimittal commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/genericgitconnector/GitConfigDTO.java
> +  @URL private String gitConnectionUrl;
here also

2022-09-09 13:29 UTC, namantalaycha10 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/helm/HttpHelmConnectorDTO.java
>    @Valid HttpHelmAuthenticationDTO auth;
Approved

2022-09-10 15:48 UTC, shreyas-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java
> +  private String vaultUrl;
Approved.

2022-09-10 16:28 UTC, mohitg0795 approved these changes
Doing dummy approval just to unblock PR as requested.

> Reviewed 16 of 27 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221#-:-NBcDmfs9Q0C9t9mJsC8:bcnvwjo)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-10 17:45 UTC, abhinav-harness approved these changes
> Reviewed 16 of 27 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-10 17:46 UTC, abhinav-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221#-:-NBcVh5mBRe4QRzjshuX:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-10 18:46 UTC, tiwaritejas approved these changes
> Reviewed 16 of 27 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37221)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-11 14:43 UTC, merged