feat: [CDS-42623]: Docker Label support
harness/harness-core pull request #37257
Opened 2022-09-07 10:58 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-07 11:01 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37257)

2022-09-08 04:09 UTC, shivamnegi94 commented
trigger ti0, ti2, ti3

2022-09-08 14:32 UTC, vtxorxwitty approved these changes
> Reviewed 3 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37257)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-12 06:42 UTC, puthrayaharness requested changes

2022-09-12 06:42 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +      return null;
Return empty hashmap intead of `null`

2022-09-12 06:42 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +    return EmptyPredicate.isNotEmpty(artifactDelegateResponse.getLabel()) ? artifactDelegateResponse.getLabel() : null;
Same please return empty map instead of null

2022-09-12 06:42 UTC, puthrayaharness commented on 125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreatorTest.java
> -            "serviceVariables.svar2", "serviceVariables.envVar1", "serviceVariables.svar1");
We will have to take a look at all these expressions once we have multi artifats

2022-09-13 07:18 UTC, puthrayaharness approved these changes

2022-09-13 07:19 UTC, puthrayaharness approved these changes
> Reviewed 3 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37257)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-13 07:39 UTC, puthrayaharness commented
trigger codebasehash

2022-09-28 09:38 UTC, hextechpal approved these changes
> Reviewed 3 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37257)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-09-30 10:27 UTC, puthrayaharness approved these changes

2022-09-30 10:28 UTC, puthrayaharness approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37257)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-30 10:28 UTC, merged