fix: [CDS-41722]: code changes to download helm chart only once
harness/harness-core pull request #37308
Opened 2022-09-08 13:53 UTC by achyuth-harness

## Describe your changes

https://harness.atlassian.net/wiki/spaces/CDP/pages/21164818433/Avoid+downloading+helm+chart+for+every+deployment

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/37308)

2022-09-08 13:56 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 8 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37308)

2022-09-12 15:37 UTC, abosii-harness requested changes
> Reviewed 10 of 20 files at r1, 7 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 771 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHrJA2fBbPyaRhzqG:-NBmHrJA2fBbPyaRhzqH:bqmyt74) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L771)):*
> ```Java
> 
>     if (!helmTaskHelperBase.newDoesChartExist(workingDir, chartName)) {
>       downloadFilesFromChartRepo(
> ```

If multiple threads are going to call this method, and since working directory is expected to be shared between threads, can result in multiple helm processes trying to override same file. Since we expect the file content to be same, it's mostly about how helm is handling file access, but from previous experience with index.yaml it may be a problem and need to be synced 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 137 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHk7I8RHQfI4V_UIM:-NBmHk7I8RHQfI4V_UIN:b69gfrx) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L137)):*
> ```Java
> 
>   protected static final String WORKING_DIR = "./repository/helm/source/${"
>       + "ACTIVITY_ID"
> ```

No reasons this string to be multiline
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 149 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHZvI4H8KXSSuk3y7:-NBmHZvI4H8KXSSuk3y8:byuamkv) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L149)):*
> ```Java
> 
>   /*
>   TODO: Achyuth -- check the entire flow once for chartMuseum, need to make some changes
> ```

Any updates on this?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHbhm0VLcz7Pq7x4b:-NBmHbhm0VLcz7Pq7x4c:b9t5ic5) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L151)):*
> ```Java
>   TODO: Achyuth -- check the entire flow once for chartMuseum, need to make some changes
>    */
>   public void newModifyRepoNameToIncludeBucket(HelmChartConfigParams helmChartConfigParams) {
> ```

This new prefix in methods name is confusing, can we rename it to something else?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1132 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHJHY4eQTz9dXi4IP:-NBmHJHY4eQTz9dXi4IQ:bi5tf9y) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1132)):*
> ```Java
>   }
> 
>   public String createDirectory(String directoryBase) throws IOException {
> ```

Method name should be createDirectoryIfDoesNotExist, it's confusing now in code when you have logic where after createDirectory method we expect something to exist
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmKyom53ZkMJqcViVh:-NBmKyom53ZkMJqcViVi:b-bumozd) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L156)):*
> ```Java
>     boolean isEnvVarSet = isNotEmpty(helmTaskHelperBase.newGetWorkingDirFromEnv());
>     String workingDir = "";
>     boolean isNotReleaseHistCmd = helmCommandRequest instanceof HelmReleaseHistoryCommandRequest;
> ```

isReleaseHistCmd? Or condition is wrong?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java` line 162 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmKs-dCgOZyxqlSFx2:-NBmKs-dCgOZyxqlSFx3:bj66jz8) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L162)):*
> ```Java
>         workingDir = Paths
>                          .get(replace(WORKING_DIR,
>                              "${"
> ```

Can be single line
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java` line 2908 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBm88kdBLlD2gCB_B7E:-NBm88kdBLlD2gCB_B7F:bcdza4) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java#L2908)):*
> ```Java
> 
>   @Test
>   @Owner(developers = ABOSII)
> ```

I didn't write this test :) 
___
*[`960-api-services/src/main/java/io/harness/k8s/kubectl/AbstractExecutable.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBm8dFW5QpOOI6wH3AP:-NBm8dFW5QpOOI6wH3AQ:b91pgxe) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/960-api-services/src/main/java/io/harness/k8s/kubectl/AbstractExecutable.java#L24)):*
> ```Java
> public abstract class AbstractExecutable implements Executable {
>   @Override
>   public ProcessResult execute(String directory, OutputStream output, OutputStream error, boolean printCommand,
> ```

nit: you could have execute(...) without Map<String, String> env that will be a wrapper around execute(..., new HashMap<>)


<!-- Sent from Reviewable.io -->

2022-09-12 18:41 UTC, achyuth-harness commented
trigger ti2

2022-09-13 04:58 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 16 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 771 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHrJA2fBbPyaRhzqG:-NBmh0KD1wpvMxXqNJy1:b-wfyj4r) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L771)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

If multiple threads are going to call this method, and since working directory is expected to be shared between threads, can result in multiple helm processes trying to override same file. Since we expect the file content to be same, it's mostly about how helm is handling file access, but from previous experience with index.yaml it may be a problem and need to be synced 
</blockquote></details>

Have taken care of this by wrapping in synchronized block
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 137 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHk7I8RHQfI4V_UIM:-NBmcqi5DqX6RX95XuhB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L137)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

No reasons this string to be multiline
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 149 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHZvI4H8KXSSuk3y7:-NBmqyTU6kar4B2wWeZh:bxbxdut) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L149)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Any updates on this?
</blockquote></details>

Yes (tested locally, removed this comment)
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHbhm0VLcz7Pq7x4b:-NBmcsvJ6i2xj9ATjVrz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L151)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This new prefix in methods name is confusing, can we rename it to something else?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1132 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmHJHY4eQTz9dXi4IP:-NBmdOE25TO6JL6FWOWE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1132)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Method name should be createDirectoryIfDoesNotExist, it's confusing now in code when you have logic where after createDirectory method we expect something to exist
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmKyom53ZkMJqcViVh:-NBmdP0v1oRhQqXWl1fj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L156)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

isReleaseHistCmd? Or condition is wrong?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java` line 162 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBmKs-dCgOZyxqlSFx2:-NBmdPlIEEomjXZYmqEU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L162)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can be single line
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java` line 2908 at r3](https://reviewable.io/reviews/harness/harness-core/37308#-NBm88kdBLlD2gCB_B7E:-NBmdauI2PHBd1Mw98_M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/21fcae85368ec0aab9a5179637a3e6383b0812c8/930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java#L2908)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I didn't write this test :) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-13 10:06 UTC, achyuth-harness commented
trigger feature-build

2022-09-13 11:15 UTC, shubham-in10se requested changes
> Reviewed 8 of 20 files at r1, 2 of 14 files at r3, 12 of 15 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 1 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java` line 120 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqYbma2bXkpC6tuTLe:-NBqYbma2bXkpC6tuTLf:b-6y6rtf) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java#L120)):*
> ```Java
>         HelmChartManifestDelegateConfig helmChartConfig =
>             (HelmChartManifestDelegateConfig) helmCommandRequestNG.getManifestDelegateConfig();
>         workingDirectory = helmTaskHelperBase.getCompleteWorkingDirectory(helmTaskHelperBase.getWorkingDirFromEnv(),
> ```

is this the `working directory` or the location of the chart in `local repository`.?
if it's the latter, we should rename the variable.

the same would apply to other places as well. If this is pointing to the local repository, let's refrain from calling it working directory.



_Code quote:_
```Java
        workingDirectory = helmTaskHelperBase.getCompleteWorkingDirectory(helmTaskHelperBase.getWorkingDirFromEnv(),
            repoName, helmChartConfig.getChartName(), helmChartConfig.getChartVersion());
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 770 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqWXcKEtei4Oulgrir:-NBqWXcKEtei4Oulgris:b-y3xs3c) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L770)):*
> ```Java
>     String workingDir = Paths.get(commandRequestNG.getWorkingDir()).toString();
> 
>     if (!helmTaskHelperBase.doesChartExist(workingDir, chartName)) {
> ```

wouldn't the chart version also be required here to check if the chart with the required version is present in local repository.?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2666 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqVncn0wMZXLOOJadw:-NBqVncn0wMZXLOOJadx:bk6exta) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2666)):*
> ```Java
>         if (helmTaskHelperBase.doesChartExist(localChartDirectory, chartName)) {
>           isChartPresent = true;
>           localChartDirectory = helmTaskHelperBase.getChartDirectory(localChartDirectory, chartName);
> ```

the method `doesChartExist()` should ideally be renamed to `doesChartExistInLocalRepo()`
and should take the params: `repo name, chart name and chart version`, rest all the things can be abstracted within the method itself.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 843 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqXjjM6ffpX3n1sEnk:-NBqXjjM6ffpX3n1sEnl:b3unysi) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L843)):*
> ```Java
>   }
> 
>   public void newModifyRepoNameToIncludeBucket(HelmChartConfigParams helmChartConfigParams) {
> ```

rename this method. (I think `new` is not required in the name
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java` line 452 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqXxX65Hw0wTBU7LbY:-NBqXxX65Hw0wTBU7LbZ:bp6hygy) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L452)):*
> ```Java
>     }
>     if (!isChartPresent) {
>       helmTaskHelper.downloadChartFiles(
> ```

shouldn't we do the parallel handling here as well..?



_Code quote:_
```Java
    if (!isChartPresent) {
      helmTaskHelper.downloadChartFiles(
          helmChartConfigParams, workingDirectory, timeoutInMillis, commandRequest.getHelmCommandFlag());
    }
```
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNGTest.java` line 274 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqY7Mt30lreR-gXPv_:-NBqY7Mt30lreR-gXPva:bpq1e6j) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNGTest.java#L274)):*
> ```Java
>             .build();
> 
>     doReturn("/helm-working-dir/${REPO_NAME}").when(helmTaskHelperBase).getWorkingDirFromEnv();
> ```

update the test as now `${REPO_NAME}` is no longer a restriction on the user
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java` line 2926 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqYJK-6Y-yATifUX14:-NBqYJK-6Y-yATifUX15:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java#L2926)):*
> ```Java
>                                                                  .build();
> 
>     doReturn("/helm-working-dir/${REPO_NAME}").when(helmTaskHelperBase).getWorkingDirFromEnv();
> ```

same as above


<!-- Sent from Reviewable.io -->

2022-09-13 14:26 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 16 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java` line 120 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqYbma2bXkpC6tuTLe:-NBqeq7u9Wyrv1oIGONZ:byk81ua) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java#L120)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

is this the `working directory` or the location of the chart in `local repository`.?
if it's the latter, we should rename the variable.

the same would apply to other places as well. If this is pointing to the local repository, let's refrain from calling it working directory.
</blockquote></details>

Its the working directory
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 770 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqWXcKEtei4Oulgrir:-NBqZ_2Q306GTw_YGuvd:b2ruq5h) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L770)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

wouldn't the chart version also be required here to check if the chart with the required version is present in local repository.?
</blockquote></details>

We already set this(including chartVersion) in HelmCommantTaskNG line#117
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2666 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqVncn0wMZXLOOJadw:-NBqZobA2qaxGwG1lt7T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2666)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

the method `doesChartExist()` should ideally be renamed to `doesChartExistInLocalRepo()`
and should take the params: `repo name, chart name and chart version`, rest all the things can be abstracted within the method itself.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 843 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqXjjM6ffpX3n1sEnk:-NBq_1-uA9_SQoycftrj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L843)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

rename this method. (I think `new` is not required in the name
</blockquote></details>

Done.



_Code quote:_
```Java
newModifyRepoNameToIncludeBucket
```
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java` line 452 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqXxX65Hw0wTBU7LbY:-NBqbWvO1hta_wMnEmuH:b-yvwqdz) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L452)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

shouldn't we do the parallel handling here as well..?
</blockquote></details>

No, since the chart should be present in helm values fetch. Adding a check and throwing invalid request exception instead as in K8sTaskHelperBase line#2668
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNGTest.java` line 274 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqY7Mt30lreR-gXPv_:-NBqbrKXEr2blwjmXFDo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmValuesFetchTaskNGTest.java#L274)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

update the test as now `${REPO_NAME}` is no longer a restriction on the user
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java` line 2926 at r6](https://reviewable.io/reviews/harness/harness-core/37308#-NBqYJK-6Y-yATifUX14:-NBqc-qvCQ--i6hPm-G4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7177507f98d2ee991beaa85585253014ee861e66/930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java#L2926)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-14 03:16 UTC, diptiman-adak commented
trigger ft1

2022-09-14 03:16 UTC, diptiman-adak commented
trigger ft2

2022-09-14 04:32 UTC, achyuth-harness commented
trigger ti0, ti1, ti2, ti3, ti4

2022-09-14 04:32 UTC, achyuth-harness commented
trigger feature-build

2022-09-14 13:36 UTC, vikyathharekal reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 16 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java` line 104 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwCaCDEOX9dy-uRdwT:-NBwCaCDEOX9dy-uRdwU:bomvaz1) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java#L104)):*
> ```Java
>     try {
>       boolean isEnvVarSet = helmTaskHelperBase.isHelmLocalRepoSet();
>       String workingDirectory = "";
> ```

nit: redundant initialization
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 952 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwCQyZ7CkUtagHXulf:-NBwCQyZ7CkUtagHXulg:bomvaz1) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L952)):*
> ```Java
>       List<HelmFetchFileConfig> helmFetchFileConfigList) throws Exception {
>     logCallback.saveExecutionLog(color("\nStarting fetching Helm values", White, Bold));
>     String workingDirectory = "";
> ```

nit: redundant initialization
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2639 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw7PRW3YxIGi20Hvk7:-NBw7PRW3YxIGi20Hvk8:bm3r13z) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2639)):*
> ```Java
>   }
> 
>   public void copyHelmChartFolderToWorkingDir(String workingDirectory, String localChartDirectory) throws IOException {
> ```

could this be structured as copyXxx(src, dest)? right now it is kind of copyXxx(dest, src)
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2663 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw8Z5FEzjPoLTFHDbW:-NBw8Z5FEzjPoLTFHDbX:bks3t38) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2663)):*
> ```Java
>         String localChartDirectory =
>             helmTaskHelperBase.getHelmLocalRepositoryCompletePath(repoName, chartName, chartVersion);
>         if (helmTaskHelperBase.doesChartExistInLocalRepo(repoName, chartName, chartVersion)) {
> ```

Could this be simplified to



_Code snippet:_
```Java
if (helmTaskHelperBase.doesChartExistInLocalRepo(repoName, chartName, chartVersion)) {
  localChartDirectory = helmTaskHelperBase.getChartDirectory(localChartDirectory, chartName);
} else {
  throw new InvalidRequestException()
}
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2665 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw7t9gEFyZwuC1clBh:-NBw7t9gEFyZwuC1clBi:b-rebgpz) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2665)):*
> ```Java
>         if (helmTaskHelperBase.doesChartExistInLocalRepo(repoName, chartName, chartVersion)) {
>           isChartPresent = true;
>           localChartDirectory = helmTaskHelperBase.getChartDirectory(localChartDirectory, chartName);
> ```

static method getChartDirectory could be accessed using the class name rather than an instance variable
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2673 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw7FSVBoLS797dd4V8:-NBw7FSVBoLS797dd4V9:bx7ryv4) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2673)):*
> ```Java
>         String workingDirectory =
>             helmTaskHelperBase.createDirectoryIfNotExist(Paths.get(destinationDirectory, chartName).toString());
>         log.info("Copying locally present chart from directory: %s to current working directory: %s \n",
> ```

{} instead of %s
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java` line 154 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw9OZoC4zk0GMvrig2:-NBw9OZoC4zk0GMvrig3:b-b7xczc) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L154)):*
> ```Java
> 
>     boolean isEnvVarSet = helmTaskHelperBase.isHelmLocalRepoSet();
>     String workingDir = "";
> ```

Do we need workingDir initialized outside? If not we could move it inside if (!isEnvVarSet)



_Code quote:_
```Java
workingDir
```
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 223 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwA4JLAQeaJT1AYqr3:-NBwA4JLAQeaJT1AYqr4:b5upbg) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L223)):*
> ```Java
>             log.info("Did not find the chart and version in local repo: " + workingDirectory);
>             fetchChartFiles(helmChartConfig, workingDirectory, timeoutInMillis, helmCommandFlag);
>           } else {
> ```

Should we add/move this else for the outer if statement?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 255 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwAibo8NvhLpMub4ee:-NBwAibo8NvhLpMub4ef:b-2tg6ro) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L255)):*
> ```Java
>     Map<String, List<String>> mapK8sValuesLocationToContents = new HashMap<>();
> 
>     String workingDirectory = workingDir;
> ```

Any reason for not using workingDirectory instead of workingDir above? (we might avoid this assignment)
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java` line 502 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwBUfwCkehkZPigmQ2:-NBwBUfwCkehkZPigmQ3:bio6ig) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L502)):*
> ```Java
>             helmTaskHelperBase.getHelmLocalRepositoryCompletePath(helmChartConfigParams.getRepoName(),
>                 helmChartConfigParams.getChartName(), helmChartConfigParams.getChartVersion());
>         if (helmTaskHelperBase.doesChartExistInLocalRepo(helmChartConfigParams.getRepoName(),
> ```

Same comment as earlier. 
1. Could we simplify this if/else?
2. Could we use class instead of instance for static member call?
3. log.info("Copying   ... {} instead of %s 


<!-- Sent from Reviewable.io -->

2022-09-14 14:11 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 16 file(s) to review. 2 change requests. 23. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2639 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw7PRW3YxIGi20Hvk7:-NBwFfcA4RXJof3ZMWqy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2639)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

could this be structured as copyXxx(src, dest)? right now it is kind of copyXxx(dest, src)
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2663 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw8Z5FEzjPoLTFHDbW:-NBwGcQh7OhJwyp5ArUN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2663)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Could this be simplified to
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2665 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw7t9gEFyZwuC1clBh:-NBwHSRw2mMCzVH5Xt5p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2665)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

static method getChartDirectory could be accessed using the class name rather than an instance variable
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2673 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw7FSVBoLS797dd4V8:-NBwH_DXAG7KqDt6Oins:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2673)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

{} instead of %s
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java` line 154 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBw9OZoC4zk0GMvrig2:-NBwHuwt1-TkqGZ7c-JJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmCommandTask.java#L154)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Do we need workingDir initialized outside? If not we could move it inside if (!isEnvVarSet)
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 223 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwA4JLAQeaJT1AYqr3:-NBwIRpm-WR8M0eYVVvw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L223)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Should we add/move this else for the outer if statement?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 255 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwAibo8NvhLpMub4ee:-NBwITtS8R0qnlLv9Klf:b-qaafhv) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L255)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Any reason for not using workingDirectory instead of workingDir above? (we might avoid this assignment)
</blockquote></details>

Yes, we need workingDirectory variable to be final as its later used in a lambda expr
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java` line 502 at r8](https://reviewable.io/reviews/harness/harness-core/37308#-NBwBUfwCkehkZPigmQ2:-NBwJb7FEpLZKjrKH64t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ca7df9e27b7e6b7df5d3b53a08b3f59286a687c/930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L502)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Same comment as earlier. 
1. Could we simplify this if/else?
2. Could we use class instead of instance for static member call?
3. log.info("Copying   ... {} instead of %s 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-14 15:29 UTC, vikyathharekal approved these changes
> Reviewed 7 of 20 files at r1, 1 of 14 files at r3, 1 of 15 files at r4, 1 of 1 files at r6, 10 of 16 files at r7, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 2 change requests. 15. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-14 15:47 UTC, achyuth-harness commented
trigger feature-build

2022-09-14 18:34 UTC, shubham-in10se approved these changes
> Reviewed 10 of 16 files at r7, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: 1 change requests. 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-15 07:53 UTC, abosii-harness approved these changes
> Reviewed 4 of 15 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 10 of 16 files at r7, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37308)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-15 07:59 UTC, merged