[feat]: [CDS-41934] Git Triggers
harness/harness-core pull request #37315
Opened 2022-09-08 19:03 UTC by vivekkarnatiharness

## Describe your changes
Github Packages triggers backend changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-08 20:32 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 12 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 12 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37315)

2022-09-13 09:42 UTC, puthrayaharness requested changes

2022-09-13 09:42 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +    String versionRegex = artifactConfig.getVersionRegex() != null ? artifactConfig.getVersionRegex().getValue() : "";
We need to do a blank check here.

2022-09-13 09:42 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +    String version = artifactConfig.getVersion() != null ? artifactConfig.getVersion().getValue() : "";
Please do a blank check

2022-09-19 09:14 UTC, puthrayaharness approved these changes

2022-09-19 09:14 UTC, puthrayaharness approved these changes
> Reviewed 66 of 77 files at r4, 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37315)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-19 09:19 UTC, archit-harness approved these changes
> Reviewed 2 of 77 files at r4, 6 of 20 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37315)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-19 09:21 UTC, merged