[fix]: [PL-28103]: Handle GCP KMS UnathenticatedException in Secrets …
harness/harness-core pull request #37371
Opened 2022-09-11 21:32 UTC by Raghav-Murali

…Management

## Describe your changes
This PR handles the Unauthenticated Exception thrown by the GCP KMS incase of invalid credentials. Previously this exception was not explicitly caught and thus a generic message was displayed in the UI which doesn't convey any valid information to the end user or providing any details that it was the credentials that were invalid. This change will catch the exception explicitly and propagate back the error message and code which conveys to the user that something was wrong with the provided credentials.

[Test Scenario] - Create a new GCP KMS secret manager connector with given credentials. Since the provided credentials are no longer valid it doesn't allow to create a connector.
[Test Outcome] - GCP KMS doesn't recognize the given credentials and thus it throws a “UnauthenticatedException”.

[Prior Error Message on UI]-
Encryption failed after 3 retries

[New Error Message on UI with this fix]-
Unauthenticated exception thrown while encrypting secret. Error code - GrpcStatusCode{transportCode=UNAUTHENTICATED} Error Msg - io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

As seen above the error code and message contained in the UnauthenticatedException provides sufficient details on what needs to be corrected.

## Checklist
- [Yes ] I've documented the changes in the PR description - Check [PL-28103](https://harness.atlassian.net/browse/PL-28103) for sufficient summary.
- [ Yes ] I've tested this change either in PR or local environment - Tested in the local test environment.
- [ Yes ] I've added unit tests to verify the changes - Added sufficient unit test that covers all possible scenarios for this change.
- [ N/A ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-11 21:34 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37371)

2022-09-13 17:05 UTC, Raghav-Murali reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/37371#-NBiT03u6hW-quWXeKJI-r1-104:-NBrnuQT9un352NLmq2y:bw6ngop) ([raw file](https://github.com/harness/harness-core/blob/cd07dcafd6832e45918128a9f3482e9ae5c5c36b/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java#L104)):*
<details><summary><i>Previously, rickmarry (Rick Marry) wrote…</i></summary><blockquote>

Do we really want to give all this information in the response in the UI?  I think that stating the we have failed to authenticate with  GCP KMS secret manager should be enough
</blockquote></details>

I will remove the additional message in the front and just send the message in the exception which gives all the details.


<!-- Sent from Reviewable.io -->

2022-09-15 09:36 UTC, meenakshi-harness requested changes

2022-09-15 09:36 UTC, meenakshi-harness commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java
> +        log.warn("Unauthenticated exception thrown while encrypting secret");
Also should we add this log only when it is not retry-able?

2022-09-15 09:36 UTC, meenakshi-harness commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java
> +        log.warn("Unauthenticated exception thrown while decrypting secret");
same

2022-09-15 09:36 UTC, meenakshi-harness commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java
> +          String message = "Unauthenticated exception thrown while encrypting secret. Error code - " + errorCode
+1
For UI we can format same information in HInt and  Explanation format if possible like this
`hintWithExplanationException(HintException.HINT_GCP_ACCESS_DENIED,
                ExplanationException.INVALID_PARAMETER,
                new InvalidRequestException(e.getMessage(), GCP_KMS_OPERATION_ERROR, USER))`

2022-09-15 18:57 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java
> +          String message = "Unauthenticated exception thrown while encrypting secret. Error code - " + errorCode
Cool, makes sense. Will update it accordingly. Thanks guys!

2022-09-15 19:06 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java
> +        log.warn("Unauthenticated exception thrown while encrypting secret");
Yeah, I can change it to an error and log only when its non-retry able.

2022-09-15 19:11 UTC, Raghav-Murali commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java
> +        log.warn("Unauthenticated exception thrown while decrypting secret");
Done

2022-09-15 21:23 UTC, Raghav-Murali reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: 3 file(s) to review. 3 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/GcpKmsEncryptorTest.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/37371#-NC1psrs0Ca0tkZPCX8_:-NC1zWfwD6ya16yQTvMd:b7m9wun) ([raw file](https://github.com/harness/harness-core/blob/2064a400f6628079fb6451276dce5db66621ed70/890-sm-core/src/test/java/io/harness/encryptors/GcpKmsEncryptorTest.java#L175)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

do we need test for retriable UnauthenticationException too?

If this can never be retriable -- isRetriable() check is of any value?
</blockquote></details>

Yes, I will add another unit test where isRetriable() is true. 

Similar to in Azure Client the GCP client also has internal retry mechanism. And I think based on that it will either set this to true or false.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/37371#-NC1oeib16Q0IT7tFUOa:-NC2-VOs6SX8cdFJLeoV:b-awcbnd) ([raw file](https://github.com/harness/harness-core/blob/2064a400f6628079fb6451276dce5db66621ed70/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java#L100)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

What to do when this is retriable?

Is it possible that we retry this three times and then come back in UnauthenticatedException block again? 
</blockquote></details>

I previously thought if its retryable then to keep trying again and again. As per the docs - https://cloud.google.com/java/docs/reference/google-cloud-core/latest/com.google.cloud.BaseServiceException#com_google_cloud_BaseServiceException_isRetryable__ this function is suppose to return true only if its safe to retry. And in other cases it should return false. But the docs doesn't mention if there is a limit on how many time it will return True.

Yes, now there is no three times limit for this UnauthenticatedException block, so it will retry as many times as isRetryable() returns true. I'm assuming the GCP client will not indefinitely just keep returning true. But a safer approach is to do the three times approach. Let me modify it. 
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/37371#-NC1p_fu4-XbD-Uh-hW0:-NC21H1s-aMrSVOGv2hZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2064a400f6628079fb6451276dce5db66621ed70/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java#L101)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Please log the exception too
</blockquote></details>

Done.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/37371#-NC1phmA2fl3wOKUJ6V1:-NC21Fyt9gqITEgTOuUX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2064a400f6628079fb6451276dce5db66621ed70/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java#L180)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

same comments as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-21 05:19 UTC, meenakshi-harness submitted a review, later dismissed
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: Some of the checks are too old. 3 file(s) to review. 2 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-21 17:27 UTC, Raghav-Murali commented
trigger feature-build

2022-09-21 23:51 UTC, gn-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-22 00:09 UTC, rickmarry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371#-:-NCXWkfhAk7kymJS50mZ:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-22 00:09 UTC, rickmarry requested changes
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-22 00:10 UTC, rickmarry approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371#-:-NCXWuvH18rSkydJGpqY:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-22 05:33 UTC, Raghav-Murali commented
trigger feature-build

2022-09-23 04:59 UTC, meenakshi-harness approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-23 05:41 UTC, gn-harness approved these changes
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-23 13:10 UTC, rickmarry commented on 890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpKmsEncryptor.java
> +          String message = "Unauthenticated exception thrown while encrypting secret. Error code - " + errorCode
good.. thanks

2022-09-23 13:13 UTC, rickmarry approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37371)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-23 15:46 UTC, merged