[feat]: [CDS-42886]:Gar region fetch
harness/harness-core pull request #37419
Opened 2022-09-12 16:41 UTC by vivekkarnatiharness

## Describe your changes
Added Regions api for google artifact registry
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-12 16:44 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37419)

2022-09-12 17:00 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-09-12 17:07 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-09-12 18:14 UTC, puthrayaharness requested changes

2022-09-12 18:14 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/gar/regionGar.java
> +public class regionGar {
Please capitalize class name `RegionGar`

2022-09-12 18:14 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/gar/GARArtifactResource.java
> +    List<regionGar> regions = new ArrayList<>();
Please create a static final list of strings and you can initialize it using that.
Something along this line. 

`Lists.newArrayList("asia", "europe"...).stream().map(region -> new Region(region, region)).collect...`

Another way to do this is to have this as part of the config file where we have the regions listed in the config. That way we do not have to make a code change to add a new region we can just update the config file.

2022-09-13 05:28 UTC, puthrayaharness requested changes

2022-09-13 05:28 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/gar/GARArtifactResource.java
> +    List<RegionGar> regions =
Please make this static final like the way I had mentioned before. 
`private static final List<..> GAR_REGIONS = Arrays.asList(...)`

2022-09-13 06:55 UTC, puthrayaharness approved these changes

2022-09-13 06:57 UTC, puthrayaharness approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37419)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-13 07:28 UTC, merged