refactor heartbeat, step 1
harness/harness-core pull request #37422
Opened 2022-09-12 18:23 UTC by xingchi-jin

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-12 18:26 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37422)

2022-09-13 19:46 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsNpCMBBY1mVOOkiEY:-NBsNpCMBBY1mVOOkiEZ:bp86wsi) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L102)):*
> ```Java
> 
>           delegateService.handleDelegateHeartBeat(delegate);
>           delegateService.registerHeartbeat(accountId, delegateId,
> ```

why two methods? registerHeartbeat and handleDelegateHeartBeat?


<!-- Sent from Reviewable.io -->

2022-09-13 19:47 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsNwsxAHhdlLsltE2Q:-NBsNwsy4c1NcrKKYO_V:b53u1oh) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L145)):*
> ```Java
>       }
>     } else if (req.getMethod().equalsIgnoreCase("POST")) {
>       log.info("delegate socket POST request");
> ```

we should not add this log, it will log too many lines


<!-- Sent from Reviewable.io -->

2022-09-13 19:47 UTC, raghuAtWings commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2497 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsO3z4CA2w6NtHHFhi:-NBsO3z4CA2w6NtHHFhj:be2z0b8) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2497)):*
> ```Java
>   public void handleDelegateHeartBeat(Delegate delegate) {
>     // TODO: add heartbeat metrics
>     if (licenseService.isAccountDeleted(delegate.getAccountId())) {
> ```

we should move this logic of checking for correctness in another method and reuse for both register and heartbeat.


<!-- Sent from Reviewable.io -->

2022-09-13 19:50 UTC, raghuAtWings commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2529 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsOHJx5QfLfPtPuBWP:-NBsOHJx5QfLfPtPuBWQ:b-ci3wh8) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2529)):*
> ```Java
>     }
> 
>     if (existingDelegate != null && existingDelegate.getStatus() == DelegateInstanceStatus.DELETED) {
> ```

we don't need null check here


<!-- Sent from Reviewable.io -->

2022-09-13 19:52 UTC, xingchi-jin commented
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsNwsxAHhdlLsltE2Q:-NBsP4QrE-qlEKvPGzwc:b5wgeu4) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L145)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should not add this log, it will log too many lines
</blockquote></details>

got it. Actually I just filed this PR in order to run PR testing. code is not completely cleaned yet. Sorry for the confusion and thanks for taking a look ! 


<!-- Sent from Reviewable.io -->

2022-09-13 19:55 UTC, raghuAtWings commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2544 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsPdUq6p0KX_8xGNx8:-NBsPdUq6p0KX_8xGNx9:b-3ers5c) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2544)):*
> ```Java
> 
>     if (ECS.equals(delegate.getDelegateType())) {
>       handleEcsDelegateRequest(delegate);
> ```

we should handle the ECS case in a different PR but how far are we from handling that?


<!-- Sent from Reviewable.io -->

2022-09-13 19:55 UTC, raghuAtWings reviewed
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-13 19:58 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsNpCMBBY1mVOOkiEY:-NBsPfaj5XVCBlGKzagn:blj191w) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L102)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why two methods? registerHeartbeat and handleDelegateHeartBeat?
</blockquote></details>

The original code had like this, two methods. I am thinking about keeping it this way (but rename functions) in this PR, and remove the registerHeartbeat call in the next PR when I remove the DelegateConnection, for which, I will first write a design document
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2497 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsO3z4CA2w6NtHHFhi:-NBsQ1B19BIE-s8InBZ0:b-ywj639) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2497)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should move this logic of checking for correctness in another method and reuse for both register and heartbeat.
</blockquote></details>

yes, will do.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2529 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsOHJx5QfLfPtPuBWP:-NBsQ5uj1IaMs8bHH9E_:bd30ifx) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2529)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we don't need null check here
</blockquote></details>

good catch
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2544 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsPdUq6p0KX_8xGNx8:-NBsQRenDJ8luDrN2LIu:b-8oxxra) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2544)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should handle the ECS case in a different PR but how far are we from handling that?
</blockquote></details>

I have some local changes. Maybe +1 week. But I would suggest more time to test before roll out 


<!-- Sent from Reviewable.io -->

2022-09-13 20:40 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsNpCMBBY1mVOOkiEY:-NBsY_514282YiQmwrD8:b-v3w0iw) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L102)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

The original code had like this, two methods. I am thinking about keeping it this way (but rename functions) in this PR, and remove the registerHeartbeat call in the next PR when I remove the DelegateConnection, for which, I will first write a design document
</blockquote></details>

We should remove and test now, otherwise this effort will not yield the results


<!-- Sent from Reviewable.io -->

2022-09-15 20:23 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1oYcPEmgjA0syZOmB:-NC1oYcPEmgjA0syZOmC:b-j9tnjn) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java#L65)):*
> ```Java
>     return DelegateHeartbeatResponse.builder()
>         .delegateId(delegateId)
>         .jreVersion(delegateJreVersionHelper.getTargetJreVersion(accountId))
> ```

get rid of jreVersion and useCdn


<!-- Sent from Reviewable.io -->

2022-09-15 20:28 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1pUHLAj9llyl0FiYA:-NC1pUHLAj9llyl0FiYB:bke2ne5) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java#L47)):*
> ```Java
>                            .filter(Delegate.DelegateKeys.uuid, delegateId),
>         updateOperations);
>     eventEmitter.send(EventEmitter.Channel.DELEGATES,
> ```

we should not create an event when heartbeat is updated


<!-- Sent from Reviewable.io -->

2022-09-15 20:31 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/delegate/utils/DelegateJreVersionHelper.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1qLiA0cTU_2MnSJIc:-NC1qLiA0cTU_2MnSJId:bf2zr5h) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/utils/DelegateJreVersionHelper.java#L28)):*
> ```Java
> @Slf4j
> @Singleton
> public class DelegateJreVersionHelper {
> ```

jre changes are not needed, don't send or consume anything related to jre 


<!-- Sent from Reviewable.io -->

2022-09-15 20:32 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1qZu13wNF883nLj-P:-NC1qZu13wNF883nLj-Q:b-hna9sd) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L18)):*
> ```Java
> @OwnedBy(DEL)
> @UtilityClass
> public class DelegateServiceConstants {
> ```

this should be an interface


<!-- Sent from Reviewable.io -->

2022-09-15 20:33 UTC, raghuAtWings commented
*[`400-rest/src/main/java/io/harness/delegate/utils/DelegateValidityCheckHelper.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1qg6t5UjCCq7TchuN:-NC1qg6t5UjCCq7TchuO:b2wxv11) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/utils/DelegateValidityCheckHelper.java#L48)):*
> ```Java
>     if (licenseService.isAccountDeleted(params.getAccountId())) {
>       // TODO: add metrics outside of this function.
>       // delegateMetricsService.recordDelegateMetrics(delegate, DELEGATE_DESTROYED);
> ```

uncomment the metric part


<!-- Sent from Reviewable.io -->

2022-09-15 20:38 UTC, raghuAtWings commented
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatParams.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1rrOI8IZHm3oCAOkQ:-NC1rrOJ417TmxKcjP7K:b-t4gqaj) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatParams.java#L13)):*
> ```Java
>  * This interface defines the required fields for heart beat processing.
>  */
> public interface DelegateHeartbeatParams {
> ```

you shouldn't need this at all, or if you do, only a few of them are needed. 


<!-- Sent from Reviewable.io -->

2022-09-21 03:38 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java
> +    // ??? no idea why it's needed. But it's there in old code flow for all scenarios of heartbeat.
welcome for comments here

2022-09-21 03:39 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/utils/DelegateJreVersionHelper.java
> +/*
will remove jre version /cdn stuff in a different PR

2022-09-21 20:39 UTC, xingchi-jin commented on 260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
> -    if (isEcsDelegate()) {
it's only remove the if condition. because there is already a if (isEcsDelegate()) check before calling it

2022-09-21 20:46 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 23 file(s) to review. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1pUHLAj9llyl0FiYA:-NCWm9ab5ym3WhTlCcgR:brpmqbp) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java#L47)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should not create an event when heartbeat is updated
</blockquote></details>

removed 
___
*[`400-rest/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1qZu13wNF883nLj-P:-NCWmD4q8gpE9JC2wAgM:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/utils/DelegateServiceConstants.java#L18)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should be an interface
</blockquote></details>

done
___
*[`400-rest/src/main/java/io/harness/delegate/utils/DelegateValidityCheckHelper.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1qg6t5UjCCq7TchuN:-NCWmFWu6_wL9ZZJAkj-:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/utils/DelegateValidityCheckHelper.java#L48)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

uncomment the metric part
</blockquote></details>

removed
___
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsNwsxAHhdlLsltE2Q:-NCWmO8f7QNUJhMoYVoU:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L145)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

got it. Actually I just filed this PR in order to run PR testing. code is not completely cleaned yet. Sorry for the confusion and thanks for taking a look ! 
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2544 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsPdUq6p0KX_8xGNx8:-NCWmTTT1yOL5pSquV4E:bohs2i8) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2544)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

I have some local changes. Maybe +1 week. But I would suggest more time to test before roll out 
</blockquote></details>

ECS will be next PR
___
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatParams.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1rrOI8IZHm3oCAOkQ:-NCWmVvUEdglnEJz5hgh:bv4ttgo) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatParams.java#L13)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

you shouldn't need this at all, or if you do, only a few of them are needed. 
</blockquote></details>

minimized it.
it's a temporary approach, but still better than today's, which directly using DelegateParams everywhere. We should define HeartbeatParams as DTO, but it will cause API change, so plan it later 
 DelegateParams is overloaded for heartbeat, we should define DTOs and POJOs for every workflow separately instead of reusing the DelegateParams. 


<!-- Sent from Reviewable.io -->

2022-09-21 20:49 UTC, xingchi-jin commented
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1793 at r6](https://reviewable.io/reviews/harness/harness-core/37422#-NCWnl4mB_AAipJk49ez:-NCWnl4mB_AAipJk49f-:b-avyby8) ([raw file](https://github.com/harness/harness-core/blob/b8834e65e682a1e7dc432ad5c0e9eb93305d9c48/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1793)):*
> ```Java
>       }
> 
>       setSwitchStorage(receivedDelegateResponse.isUseCdn());
> ```

Need help here.
It is an ask to remove Jreversion and cdn from heartbeat. But I am not confident on these two lines.
can someone help confirm the behavior and suggest the impact of removing them ? 


<!-- Sent from Reviewable.io -->

2022-09-21 20:50 UTC, xingchi-jin commented
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1793 at r6](https://reviewable.io/reviews/harness/harness-core/37422#-NCWnl4mB_AAipJk49ez:-NCWoDLN2Yeiw6LJlmgb:b-sl9v1v) ([raw file](https://github.com/harness/harness-core/blob/b8834e65e682a1e7dc432ad5c0e9eb93305d9c48/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1793)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

Need help here.
It is an ask to remove Jreversion and cdn from heartbeat. But I am not confident on these two lines.
can someone help confirm the behavior and suggest the impact of removing them ? 
</blockquote></details>

@raghuatwings  can you comment here


<!-- Sent from Reviewable.io -->

2022-09-21 21:01 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 23 file(s) to review. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/37422#-NBsNpCMBBY1mVOOkiEY:-NCWoYn4EGsIEqHadlG1:badd6pr) ([raw file](https://github.com/harness/harness-core/blob/e92535dca1a7a01845cc8706a29a236851e85639/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L102)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

We should remove and test now, otherwise this effort will not yield the results
</blockquote></details>

i removed all the HB logics from the GET.
the registerHeartbeat is kept for POST still, because it handles DelegateConnection, which we don't want to remove now. I will rename the function properly 


<!-- Sent from Reviewable.io -->

2022-09-22 03:57 UTC, jennyjames21 commented
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1776 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYKRA_EYHz0UC5R32T:-NCYKRA_EYHz0UC5R32U:blv49ja) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1776)):*
> ```Java
>                                                    .map(DelegateTaskPackage::getDelegateTaskId)
>                                                    .collect(toList()))
>               .location(Paths.get("").toAbsolutePath().toString())
> ```

There are around 55 delegates in prod2 hasn't migrated to new HB(heartbeatAsObject) , so for another 3 months please keep heartbeatAsObject. Please add it back


<!-- Sent from Reviewable.io -->

2022-09-22 03:59 UTC, jennyjames21 commented
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1775 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYL4Vx6LSJPfzMUrja:-NCYL4Vx6LSJPfzMUrjb:bomtqnh) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1775)):*
> ```Java
>                                                    .stream()
>                                                    .map(DelegateTaskPackage::getDelegateTaskId)
>                                                    .collect(toList()))
> ```

This may needed for resource check, i may add it back if remove in this PR or you can keep it


<!-- Sent from Reviewable.io -->

2022-09-22 04:05 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 249 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYMgE38JkumIj_nimM:-NCYMgE38JkumIj_nimN:b-kklg91) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L249)):*
> ```Java
>    */
>   private void updateIfEcsDelegate(Delegate delegate, String sequenceNum, String delegateToken) {
>     if ("ECS".equals(delegate.getDelegateType())) {
> ```

so caller is checking if this is ECS?


<!-- Sent from Reviewable.io -->

2022-09-22 04:06 UTC, jennyjames21 commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1538 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYMuPm58QCtUDqaOZq:-NCYMuPm58QCtUDqaOZr:bbdgbft) ([raw file](https://github.com/harness/harness-core/blob/02b629a729cf842f51aa382cf2cb694dcfe6f3fe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1538)):*
> ```Java
>     JreConfig jreConfig =
>         jreVersionHelper.getJreConfig(templateParameters.getAccountId(), templateParameters.isWatcher());
> ```

Are we not removing JRE related code?


<!-- Sent from Reviewable.io -->

2022-09-22 04:09 UTC, jennyjames21 commented
*[`400-rest/src/main/java/software/wings/service/intfc/DelegateService.java` line 137 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYNTGq6cAgv1Apl8vn:-NCYNTGq6cAgv1Apl8vo:b-5nod16) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/400-rest/src/main/java/software/wings/service/intfc/DelegateService.java#L137)):*
> ```Java
> 
>   DelegateRegisterResponse register(@Valid Delegate delegate);
> ```

why remove @valid here, is it on purpose? 


<!-- Sent from Reviewable.io -->

2022-09-22 04:19 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/37422#-NC1fGnLjQiKzq2kqMh5-r5-49:-NCYPae05alhoRnea56v:b-117o5t) ([raw file](https://github.com/harness/harness-core/blob/60d00c15109c70be76f2563e9b10f2c60eedb2e3/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L49)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

welcome for comments here 
</blockquote></details>

to update task status to STARTED in the manager when the delegate starts executing the task. An important one


<!-- Sent from Reviewable.io -->

2022-09-22 04:20 UTC, jennyjames21 reviewed
> Reviewed 7 of 20 files at r3, 2 of 7 files at r4, 8 of 12 files at r5, 2 of 4 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 9. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-23 05:58 UTC, johannesHarness commented on 400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java
> -          delegate.setMtls(isConnectedUsingMtls);
For future reference, removing this part here is fine for mTLS.
As long as we don't introduce any new place where we register a delegate, and only rely on the existing HTTP register REST call.

2022-09-23 06:01 UTC, johannesHarness commented on 400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java
> +        return new RestResponse<>(delegatePollingHeartbeatService.process(delegateParams));
Since we don't use `isConnectedUsingMtls` here anymore, we can remove the parameter, too.
Since it's coming as header, I don't think there should be any backwards compatibility issues.

Delegate doesn't send the header (it get's injected by the agent-gateway). So the header will always be there if a delegate is using mTLS, independent of delegate version.

2022-09-23 06:03 UTC, johannesHarness commented on 400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java
> +        return new RestResponse<>(delegatePollingHeartbeatService.process(delegateParams));
Ignore if we still need it for ECS (though I'd assume we'd want both types of delegates to have a similar register flow?

2022-09-23 11:37 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 3 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1793 at r6](https://reviewable.io/reviews/harness/harness-core/37422#-NCWnl4mB_AAipJk49ez:-NCdw80SCKr4vfqYtkJm:bk5kd7g) ([raw file](https://github.com/harness/harness-core/blob/b8834e65e682a1e7dc432ad5c0e9eb93305d9c48/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1793)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

@raghuatwings  can you comment here
</blockquote></details>

we should get rid of both, @raghuatwings can confirm though
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1731 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCdLTHO2jqsrckGq4dL:-NCdLTHO2jqsrckGq4dM:b-ni2jm9) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1731)):*
> ```Java
>   }
> 
>   private void sendKeepAlivePacket(DelegateParamsBuilder builder, Socket socket) {
> ```

This method is no where used ? IMO this is meant to be used with websocket. Do you want to fix this or we can take it separately along with ECS change.



_Code quote:_
```Java
  private void sendKeepAlivePacket(DelegateParamsBuilder builder, Socket socket) {
```
___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1oYcPEmgjA0syZOmB:-NCe-uH_7NpAjIrgADRe:bfac7nl) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java#L65)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

get rid of jreVersion and useCdn
</blockquote></details>

+1, infact we can get read of migrate jre version as well
___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java` line 57 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCe0Vcn0RYff6lI-ad0:-NCe0Vco4Ue2GovkkEgt:bvkn541) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java#L57)):*
> ```Java
>     final DelegateHeartbeatResponse.DelegateHeartbeatResponseBuilder builder =
>         getResponseBuilder(params.getAccountId(), params.getDelegateId());
>     if (licenseService.isAccountDeleted(params.getAccountId())) {
> ```

shouldn't we check for account status heartbeat pre check and do not take any action if it's deleted.



_Code quote:_
```Java
    if (licenseService.isAccountDeleted(params.getAccountId())) {
      builder.status(DelegateInstanceStatus.DELETED.toString());
    }
```
___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/stream/DelegateHeartbeatResponseStreamingWrapper.java` line 18 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCe1e4j1cr2UsKxCC9o:-NCe1e4j1cr2UsKxCC9p:bz68uee) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/400-rest/src/main/java/io/harness/delegate/heartbeat/stream/DelegateHeartbeatResponseStreamingWrapper.java#L18)):*
> ```Java
>   private DelegateHeartbeatResponseStreaming delegateHeartbeatResponseStreaming;
>   private String responseMessage;
>   @Builder.Default private boolean isHeartbeatAsObject = true;
> ```

I didn't understand the use case of heartbeatAsObject field ? why is it required and the use of this class?



_Code quote:_
```Java
isHeartbeatAsObject = true;
```
___
*[`400-rest/src/main/java/io/harness/delegate/utils/DelegateJreVersionHelper.java` line 1 at r5](https://reviewable.io/reviews/harness/harness-core/37422#-NC1fGnLjQiKzq2kqMh9-r5-1:-NCe7L_u-GSBB9rNuqIM:b-ick69j) ([raw file](https://github.com/harness/harness-core/blob/60d00c15109c70be76f2563e9b10f2c60eedb2e3/400-rest/src/main/java/io/harness/delegate/utils/DelegateJreVersionHelper.java#L1)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

will remove jre version /cdn stuff soon
</blockquote></details>

@arpit3107 has changes out removing jre dependencies as part of this https://harness.atlassian.net/browse/DEL-4218.
Probably you can assume his changes will merge soon.
___
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java` line 23 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCdK3IoBfxHBX2s0Ddx:-NCdK3IoBfxHBX2s0Ddy:b-kbbv57) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java#L23)):*
> ```Java
>   long responseSentAt;
>   // Used by ECS
>   String delegateRandomToken;
> ```

We can create further child class for ecs delegate response 



_Code quote:_
```Java
  String delegateRandomToken;
  String sequenceNumber;
```
___
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java` line 25 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCdJyr5DsiQp-71-TuB:-NCdJyr5DsiQp-71-TuC:bwo73rh) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java#L25)):*
> ```Java
>   String delegateRandomToken;
>   String sequenceNumber;
>   // not used at present
> ```

can we get rid of status if not used ?



_Code quote:_
```Java
  // not used at present
  String status;
```


<!-- Sent from Reviewable.io -->

2022-09-26 18:46 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 19. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1793 at r6](https://reviewable.io/reviews/harness/harness-core/37422#-NCWnl4mB_AAipJk49ez:-NCbimYq7V04IWcBxqW6:bv14sdu) ([raw file](https://github.com/harness/harness-core/blob/b8834e65e682a1e7dc432ad5c0e9eb93305d9c48/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1793)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

@raghuatwings  can you comment here
</blockquote></details>

@jennyjames21  my concern is here
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1775 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYL4Vx6LSJPfzMUrja:-NCbgwHsCSNLFXrcMfxt:bsa1djq) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1775)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

This may needed for resource check, i may add it back if remove in this PR or you can keep it
</blockquote></details>

could you point me to the code where the resource check happens during HB ? we should do it properly in one PR
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1776 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYKRA_EYHz0UC5R32T:-NCbglXoE8tPmNLHAekj:b9qb6e8) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1776)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

There are around 55 delegates in prod2 hasn't migrated to new HB(heartbeatAsObject) , so for another 3 months please keep heartbeatAsObject. Please add it back
</blockquote></details>

this is read from database when processing Hb, do we need it in DTO ? 
___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/37422#-NC1fGnLjQiKzq2kqMh5-r5-49:-NCbhST242ZB-jw5Nq08:b-yynrmy) ([raw file](https://github.com/harness/harness-core/blob/60d00c15109c70be76f2563e9b10f2c60eedb2e3/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L49)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

to update task status to STARTED in the manager when the delegate starts executing the task. An important one
</blockquote></details>

the code of this function updates (extend) the expiry of all the "STARTED" tasks.  why does this operation ? 
___
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 249 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYMgE38JkumIj_nimM:-NCbhwqoDUiCSZRBHOEA:bmb5ino) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L249)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

so caller is checking if this is ECS?
</blockquote></details>

yes :cry: 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1538 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYMuPm58QCtUDqaOZq:-NCbi9nS0PM5ieFrNjOR:bovji7) ([raw file](https://github.com/harness/harness-core/blob/02b629a729cf842f51aa382cf2cb694dcfe6f3fe/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1538)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Are we not removing JRE related code?
</blockquote></details>

i have a comment below which states my concern. If that's addressed, I will remove it
___
*[`400-rest/src/main/java/software/wings/service/intfc/DelegateService.java` line 137 at r8](https://reviewable.io/reviews/harness/harness-core/37422#-NCYNTGq6cAgv1Apl8vn:-NCbiHa25M1a8_WG-r4I:bt1orgw) ([raw file](https://github.com/harness/harness-core/blob/999b3afb22b5173cf257ffd96b91120cb0997371/400-rest/src/main/java/software/wings/service/intfc/DelegateService.java#L137)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why remove @valid here, is it on purpose? 
</blockquote></details>

good catch. adding back
That's because I initially deleted this function, and later with IDE auto generation, it's added back, but annotation is gone


<!-- Sent from Reviewable.io -->

2022-10-04 06:37 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 12 file(s) to review. 1 change requests. 24. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1731 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCdLTHO2jqsrckGq4dL:-NDWTc8y-kXAuzkv4hdz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1731)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This method is no where used ? IMO this is meant to be used with websocket. Do you want to fix this or we can take it separately along with ECS change.
</blockquote></details>

Done.



_Code quote:_
```Java
sendKeepAlivePacket
```
___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java` line 57 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCe0Vcn0RYff6lI-ad0:-NDWUCQs7iD6a-3s_ZWy:buhlcsv) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/400-rest/src/main/java/io/harness/delegate/heartbeat/polling/DelegatePollingHeartbeatService.java#L57)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

shouldn't we check for account status heartbeat pre check and do not take any action if it's deleted.
</blockquote></details>

the old code runs this logic, so I kept it intact
But I think what you said makes sense, I will change to return failure in precheck and run tests.
@vbhatia20  this is one more behavior change. 
___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/stream/DelegateHeartbeatResponseStreamingWrapper.java` line 18 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCe1e4j1cr2UsKxCC9o:-NDWUWFlE_Dg9Qontk_n:b-mh1czt) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/400-rest/src/main/java/io/harness/delegate/heartbeat/stream/DelegateHeartbeatResponseStreamingWrapper.java#L18)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I didn't understand the use case of heartbeatAsObject field ? why is it required and the use of this class?
</blockquote></details>

the isHeartbeatAsObject means the heartbeat DTO will be json structured data instead of string. It's a feature added few months back. There are still few delegates running in Prod-2 that is heartbeating using string. 
___
*[`400-rest/src/main/java/io/harness/delegate/utils/DelegateJreVersionHelper.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/37422#-NC1qLiA0cTU_2MnSJIc:-NDWUvCC5KBFfWNmH9X5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b699891253c900c37f9b6891456590c6572eb61/400-rest/src/main/java/io/harness/delegate/utils/DelegateJreVersionHelper.java#L28)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

jre changes are not needed, don't send or consume anything related to jre 
</blockquote></details>

Done.
___
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java` line 23 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCdK3IoBfxHBX2s0Ddx:-NDWZbov5M21C-czXjFc:b-rvikq8) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java#L23)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We can create further child class for ecs delegate response 
</blockquote></details>

prefer to do this when refactoring ECS HB code. The reason is, this will need some agent side code change to handle the new java class deserialization, which requires agent upgrade. 
___
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java` line 25 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCdJyr5DsiQp-71-TuB:-NDWXZJk7qUyWBZIb3xh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java#L25)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

can we get rid of status if not used ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-13 04:29 UTC, xingchi-jin commented
trigger recency

2022-10-21 23:54 UTC, xingchi-jin commented on 400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java
> +        return new RestResponse<>(delegatePollingHeartbeatService.process(delegateParams));
good to know. In this polling workflow, I keep ECS code path intact. Plan is to refactor it in separate PR.

2022-10-24 21:18 UTC, raghuAtWings approved these changes
> Reviewed 3 of 20 files at r3, 1 of 7 files at r4, 2 of 12 files at r5, 4 of 11 files at r10, 3 of 12 files at r13, 4 of 7 files at r14, 10 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 1 change requests. 14. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-26 09:08 UTC, gaurav-jain1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 1 change requests. 10. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/stream/DelegateHeartbeatResponseStreamingWrapper.java` line 18 at r9](https://reviewable.io/reviews/harness/harness-core/37422#-NCe1e4j1cr2UsKxCC9o:-NFIXvOV6x5zn7z2Nh7f:b2nhb2c) ([raw file](https://github.com/harness/harness-core/blob/8c671b9f34d16c30382b318294e06c3c4c955349/400-rest/src/main/java/io/harness/delegate/heartbeat/stream/DelegateHeartbeatResponseStreamingWrapper.java#L18)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

the isHeartbeatAsObject means the heartbeat DTO will be json structured data instead of string. It's a feature added few months back. There are still few delegates running in Prod-2 that is heartbeating using string. 
</blockquote></details>

Ack


<!-- Sent from Reviewable.io -->

2022-10-27 05:16 UTC, gaurav-jain1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37422)* status: 10. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-27 17:06 UTC, xingchi-jin commented
trigger codebasehash

2022-10-27 17:26 UTC, merged