Cds 42410
harness/harness-core pull request #37445
Opened 2022-09-13 07:17 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-13 07:20 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37445)

2022-09-13 09:28 UTC, shivamnegi94 commented
trigger messagecheck

2022-09-13 10:30 UTC, puthrayaharness requested changes
Please add test case

2022-09-13 10:30 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/docker/service/DockerRegistryServiceImpl.java
> +      dockerRegistryUrl = dockerRegistryUrl.concat("/v2");
Please handle case where the urls are like `https://example.com/`. It might already have a trailing slash

2022-09-13 11:24 UTC, puthrayaharness approved these changes

2022-09-13 11:24 UTC, puthrayaharness requested changes

2022-09-13 11:24 UTC, puthrayaharness commented on 960-api-services/src/test/java/io/harness/artifacts/docker/service/DockerRegistryServiceImplTest.java
> +  @Owner(developers = DEEPAK_PUTHRAYA)
Change owner

2022-09-13 12:43 UTC, puthrayaharness approved these changes

2022-09-13 12:44 UTC, puthrayaharness approved these changes
> Reviewed 2 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37445)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-14 03:42 UTC, puthrayaharness commented
trigger ti1

2022-09-14 04:27 UTC, puthrayaharness commented
trigger ti1

2022-09-14 04:28 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37445)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-19 04:02 UTC, shivamnegi94 commented
trigger ti1

2022-09-19 07:00 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37445)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-19 08:32 UTC, puthrayaharness approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37445)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-19 08:50 UTC, merged