feat: [CI-5554]: block malicious patterens in ci command
harness/harness-core pull request #37524
Opened 2022-09-14 10:27 UTC by HenAmar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-14 10:30 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 1 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37524)

2022-09-14 10:31 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java
> +    verifySteps(initializeStepInfo);
sanitizeExecution ?

2022-09-14 10:31 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java
> +    verifySteps(initializeStepInfo);
call it if infra is k8 hosted

2022-09-14 10:32 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/validation/CIExecutionValidationServiceImpl.java
> +public class CIExecutionValidationServiceImpl implements CIExecutionValidationService {
should be singleton

2022-09-14 10:32 UTC, harshjain12 requested changes

2022-09-14 10:32 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/validation/CIExecutionValidationServiceImpl.java
> +      String list =
it should be global variable and static final

2022-09-14 11:04 UTC, HenAmar commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java
> +    verifySteps(initializeStepInfo);
the validation for infra happens in the function

2022-09-14 14:36 UTC, shubham149 commented on 332-ci-manager/service/src/main/resources/suspiciousMiningPatterns.txt
> +pool
`pool` keyword may fail valid pipelines as well

2022-09-14 14:36 UTC, shubham149 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java
> +    if (initializeStepInfo.getInfrastructure().getType() == Infrastructure.Type.KUBERNETES_HOSTED) {
can you add hosted_vms as well

2022-09-15 09:55 UTC, HenAmar commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/validation/CIExecutionValidationServiceImpl.java
> +public class CIExecutionValidationServiceImpl implements CIExecutionValidationService {
singleton by this bind(CIExecutionValidationService.class).to(CIExecutionValidationServiceImpl.class).in(Singleton.class);

2022-09-15 09:55 UTC, HenAmar commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java
> +    if (initializeStepInfo.getInfrastructure().getType() == Infrastructure.Type.KUBERNETES_HOSTED) {
done

2022-09-15 09:55 UTC, HenAmar commented on 332-ci-manager/service/src/main/resources/suspiciousMiningPatterns.txt
> +at01.supportxmr.com
done

2022-09-15 09:58 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/validation/CIYAMLSanitizationServiceImpl.java
> +      StepElementConfig stepElementConfig = IntegrationStageUtils.getStepElementConfig(executionWrapper);
We should not use StepElementConfig

2022-09-15 13:19 UTC, harshjain12 approved these changes
> Reviewed 3 of 5 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37524)* status: 2. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-15 13:39 UTC, shubham149 approved these changes
> Reviewed 3 of 5 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37524)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-15 13:39 UTC, shubham149 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37524#-:-NC0N0Y6Bg3OxDk9xEsp:bnfp4nl)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-09-15 16:23 UTC, merged