[CI-5558]: CI Dashboard performance improvement
harness/harness-core pull request #37545
Opened 2022-09-14 17:39 UTC by jamie-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-14 17:40 UTC, jamie-harness commented on 332-ci-manager/service/src/main/java/io/harness/ci/dashboard/CIOverviewDashboardServiceImpl.java
> -
I changed this to an exact match. I don't think there will be multiple ID here @harshjain12 let me know if I'm wrong

2022-09-14 17:41 UTC, naidu-harness requested changes

2022-09-14 17:41 UTC, naidu-harness commented on pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java
> +        .add(Pair.of(11, CreateServiceAndCIExecutionIndex.class))
we should remove these migrations from pipeline service and embed them in the CI manager.

2022-09-14 17:41 UTC, naidu-harness commented on pipeline-service/service/src/main/resources/timescale/add_index_on_service_infra_info_pipe_execution
> +COMMIT;
ditto

2022-09-14 17:43 UTC, jamie-harness commented on pipeline-service/service/src/main/resources/timescale/add_index_on_service_infra_info_pipe_execution
> +COMMIT;
ok let me figure this out. The service_infra_info table pipeline team owns it tho. Should it be in pipeline? @naidu-harness

2022-09-14 17:44 UTC, naidu-harness commented on pipeline-service/service/src/main/resources/timescale/add_index_on_service_infra_info_pipe_execution
> +COMMIT;
pipeline team does not own this table. it should CD

2022-09-14 17:45 UTC, jamie-harness commented on pipeline-service/service/src/main/resources/timescale/add_index_on_service_infra_info_pipe_execution
> +COMMIT;
got it. I will move it to CI. it's shared component of CI/CD

2022-09-14 17:45 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37545)

2022-09-23 02:06 UTC, naidu-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37545#-:-NCc4uGV0Ms9cpKdjO6b:bnfp4nl)* status: 11 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-09-23 16:33 UTC, rutvijmehta-harness commented on 332-ci-manager/service/src/main/java/io/harness/ci/dashboard/CIOverviewDashboardServiceImpl.java
> +            + "pipeline_execution_summary_cd_id=%s and service_name is not null;",
Is this an internal query and safe from injection?

2022-09-23 16:54 UTC, jamie-harness commented on 332-ci-manager/service/src/main/java/io/harness/ci/dashboard/CIOverviewDashboardServiceImpl.java
> +            + "pipeline_execution_summary_cd_id=%s and service_name is not null;",
yes it from a query result. And was previous populated by our code. It's a hash

2022-09-23 23:57 UTC, rutvijmehta-harness approved these changes
> Reviewed 1 of 4 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37545)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-23 23:58 UTC, merged