feat: [PL-28262]: fix the issue of error while logging the exception
harness/harness-core pull request #37586
Opened 2022-09-15 12:26 UTC by bhavya181

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-15 12:29 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37586)

2022-09-15 12:29 UTC, adivishy1 approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37586)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-15 17:46 UTC, abhinav-harness commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java
>        } catch (Exception ex) {
this is very repetitive and could have been moved to a method which takes enum as input.

2022-09-15 21:04 UTC, abhinav-harness requested changes
changes req

2022-09-19 11:52 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37586)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/37586#-NC06JYzBifO5TeY_eg5-r1-149:-NCK_ufM2he3zWUVh8R-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36cc22ae7dc9896223317cc27b29d6bdc071ddca/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L149)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

this is very repetitive and could have been moved to a method which takes enum as input.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-19 18:37 UTC, abhinav-harness approved these changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37586)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-20 09:04 UTC, mohitg0795 approved these changes
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37586)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-20 09:08 UTC, merged