[fix]: [PIE-5408]: GIT pipeline not syncing to Harness (renders empty pipeline)
harness/harness-core pull request #37703
Opened 2022-09-20 11:34 UTC by senjucanon2

## Describe your changes:
Added Catch for NGTemplateResolveExceptionV2 in getPipelineByIdentifier.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-20 11:37 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37703)

2022-09-21 06:31 UTC, senjucanon2 commented
trigger checkstyle

2022-09-21 06:31 UTC, senjucanon2 commented
trigger messagecheck

2022-09-21 06:32 UTC, senjucanon2 commented
trigger codeformat

2022-09-21 09:34 UTC, namanvermah requested changes

2022-09-21 09:34 UTC, namanvermah commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/template/exception/NGTemplateResolveException.java
> +  private String yaml;
make it referredByYaml

2022-09-21 09:34 UTC, namanvermah commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/template/exception/NGTemplateResolveExceptionV2.java
> +  private String yaml;
make it referredByYaml

2022-09-21 09:34 UTC, namanvermah commented on pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java
> +  TemplateInputsErrorMetadataDTO templateInputsErrorMetadata;
Don't need TemplateInputsErrorMetadataDTO here because it will never come up

2022-09-21 14:27 UTC, prashantsharma04 approved these changes
> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37703)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-23 04:06 UTC, vaibhav-si approved these changes
> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37703)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-23 04:07 UTC, merged