[feat]: [PL-28301]: google sec man conn mapper
harness/harness-core pull request #37750
Opened 2022-09-21 09:12 UTC by shreyas-harness

## Describe your changes
Adding google secret manager connector
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-21 09:18 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37750)

2022-09-21 12:39 UTC, mohitg0795 commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/gcpsmconnector/GcpSMValidationParams.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCV2s6yASUPgsYGHjH1:-NCV2s6yASUPgsYGHjH2:bh0mc69) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/gcpsmconnector/GcpSMValidationParams.java#L33)):*
> ```Java
> public class GcpSMValidationParams implements ConnectorValidationParams, ExecutionCapabilityDemander {
>   GcpSMConnectorDTO gcpSMConnectorDTO;
>   String connectorName;
> ```

private?


<!-- Sent from Reviewable.io -->

2022-09-22 10:22 UTC, meenakshi-harness requested changes

2022-09-22 10:22 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java
> +  @JsonProperty("GcpSM") GCP_SM("GcpSM");
Make this GCP_SECRETS_MANAGER and JsonProperty as GcpSecretsManager

2022-09-22 10:22 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMEntityToDTO.java
> +        .credentials(SecretRefHelper.createSecretRef(connector.getCredentialsRef()))
Keep the field name consistent in DTO and Entity (credentialRef)

2022-09-22 10:22 UTC, meenakshi-harness commented on 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java
> +    assertThat(connector.getIsDefault()).isEqualTo(false);
Instead of commenting each line, should we add summary of each test at top(only if your test name cannot specify the purpose of test) . Like what is does and assert?. Will make it more clear and avoid unnecessary comments which can be referred  code itself like `Check connector is not null`

2022-09-22 10:22 UTC, meenakshi-harness commented on 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java
> +  public void testIsDefaultDefaultValue() {
Name suggestion: testDefaultValueForIsDefaultAsFalse

2022-09-22 10:22 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java
> +      @JsonSubTypes.Type(value = GcpSMConnectorDTO.class, name = "GcpSM")
Change type as suggested above

2022-09-22 10:22 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSMConnectorDTO.java
> +  // Delegates
why we need these comments?

2022-09-22 10:22 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSMConnectorDTO.java
> +  // Credentials
same? Instead add Open Api Spec Description to all fields

2022-09-22 10:47 UTC, meenakshi-harness requested changes

2022-09-22 10:47 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java
> +  String credentialsRef;
This is a required field

2022-09-22 10:47 UTC, meenakshi-harness commented on 440-connector-nextgen/src/test/java/io/harness/connector/impl/GcpSMConnectorTest.java
> +  private static final String ACCOUNT_IDENTIFIER = "accountIdentifier";
You can maybe create a helper class with these variables as they look very generic. Also check we should already have these variables defined in some common class

2022-09-22 11:16 UTC, nishantsaini20 requested changes
> Reviewed 10 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 18 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZpRBs0Mqgr2ka66Vw:-NCZpRBs0Mqgr2ka66Vx:bhprvry) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java#L8)):*
> ```Java
>  */
> 
> package io.harness.connector.entities.embedded.gcpsm;
> ```

Change package name to gcpsecretmanager
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZpfaY4M8F4_WgAHVe:-NCZpfaY4M8F4_WgAHVf:bkjvc9w) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java#L40)):*
> ```Java
> @TypeAlias("io.harness.connector.entities.embedded.gcpsm.GcpSMConnector")
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class GcpSMConnector extends Connector {
> ```

Rename class to GcpSecretManagerConnector
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/GcpSMValidationParamProvider.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZqH__9Xuk8ip3JmsV:-NCZqH__9Xuk8ip3JmsW:b-el8psm) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/GcpSMValidationParamProvider.java#L20)):*
> ```Java
> 
> @OwnedBy(PL)
> public class GcpSMValidationParamProvider
> ```

Use SecretManager instead of SM in name
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMDTOToEntity.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZqXRy1rpeAXxjTZ6V:-NCZqXRy1rpeAXxjTZ6W:b-el8psm) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMDTOToEntity.java#L19)):*
> ```Java
> 
> @OwnedBy(PL)
> public class GcpSMDTOToEntity implements ConnectorDTOToEntityMapper<GcpSMConnectorDTO, GcpSMConnector> {
> ```

Use SecretManager instead of SM in name
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMEntityToDTO.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZqdXn7WbgnYcG6IzH:-NCZqdXn7WbgnYcG6IzI:b-el8psm) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMEntityToDTO.java#L19)):*
> ```Java
> 
> @OwnedBy(PL)
> public class GcpSMEntityToDTO implements ConnectorEntityToDTOMapper<GcpSMConnectorDTO, GcpSMConnector> {
> ```

Use SecretManager instead of SM in name
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/GcpSMConnectorTest.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdK-r1-48:-NCZqvXA30ZJstZc_o0l:bqo5ghu) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/impl/GcpSMConnectorTest.java#L48)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

You can maybe create a helper class with these variables as they look very generic. Also check we should already have these variables defined in some common class
</blockquote></details>

I would suggest using randomAlphabetic method to generate random string value instead of using constant values.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZrbFhEAJpQf73NbRf:-NCZrbFhEAJpQf73NbRg:b-cq8qgf) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java#L93)):*
> ```Java
>         // Get its value in the connector entity
>         Object value = field.get(connector);
>         // asset that the fields are null.
> ```

Comment for each line should not be required. Statements are self explanatory.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZsQcD-hR0ctiGWCwb:-NCZsQcD-hR0ctiGWCwc:b8qt2dm) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java#L143)):*
> ```Java
>       }
>     }
>   }
> ```

We should also have a test to check that correct values are set to every field after conversion.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMEntityToDTOTest.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZu8AH3icyWDBxPlD0:-NCZu8AH3icyWDBxPlD1:bjrnfwj) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMEntityToDTOTest.java#L124)):*
> ```Java
>     // Get all the fields in it
>     Field[] fields = GcpSMConnectorDTO.class.getDeclaredFields();
>     // Loop over all fields
> ```

Remove comments.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/gcpsmconnector/GcpSMValidationParams.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZta7g5vQfWGDD5xPV:-NCZta7g5vQfWGDD5xPW:b-el8psm) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/gcpsmconnector/GcpSMValidationParams.java#L31)):*
> ```Java
> @Value
> @Builder
> public class GcpSMValidationParams implements ConnectorValidationParams, ExecutionCapabilityDemander {
> ```

Use SecretManager instead of SM in name
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSMConnectorDTO.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZtn50D_10c9F29odl:-NCZtn50D_10c9F29odm:b-el8psm) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSMConnectorDTO.java#L47)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @Schema(name = "GcpSM", description = "This contains details of GCP Secret Manager")
> public class GcpSMConnectorDTO extends ConnectorConfigDTO implements DelegateSelectable {
> ```

Use SecretManager instead of SM in name


<!-- Sent from Reviewable.io -->

2022-09-23 07:12 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 79 file(s) to review. 2 change requests. 20. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdD-r1-107:-NCdABLy5582FqMB2BFX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorConfigDTO.java#L107)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Change type as suggested above
</blockquote></details>

Done.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdE-r1-64:-NCdAC9e-AyygMl2sfag:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/ConnectorType.java#L64)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Make this GCP_SECRETS_MANAGER and JsonProperty as GcpSecretsManager
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdL-r1-49:-NCdAcM65XhvrTxZaZih:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java#L49)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Name suggestion: testDefaultValueForIsDefaultAsFalse
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdL-r1-57:-NCdAbyvD5_7NJZUdttc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java#L57)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Instead of commenting each line, should we add summary of each test at top(only if your test name cannot specify the purpose of test) . Like what is does and assert?. Will make it more clear and avoid unnecessary comments which can be referred  code itself like `Check connector is not null`
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZrbFhEAJpQf73NbRf:-NCdAd0oBBSZ60-CkTaJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java#L93)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Comment for each line should not be required. Statements are self explanatory.
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZsQcD-hR0ctiGWCwb:-NCdAeNQ0dwQQu2uyhJA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSMDTOToEntityTest.java#L143)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We should also have a test to check that correct values are set to every field after conversion.
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZpRBs0Mqgr2ka66Vw:-NCd9Dmw9pWrYsrdlkka:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java#L8)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Change package name to gcpsecretmanager
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZpfaY4M8F4_WgAHVe:-NCd9GLo2lx67VtMBU-B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java#L40)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Rename class to GcpSecretManagerConnector
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdG-r1-42:-NCd9ILa6KFj2iQHLYfB:b-e90l4r) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java#L42)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

This is a required field
</blockquote></details>

Its marked as not null on dto. 
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/GcpSMValidationParamProvider.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZqH__9Xuk8ip3JmsV:-NCd9UK7B5HBAmwT71yG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/heartbeat/GcpSMValidationParamProvider.java#L20)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use SecretManager instead of SM in name
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMDTOToEntity.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZqXRy1rpeAXxjTZ6V:-NCd9VMU1YIKb75ruIaw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMDTOToEntity.java#L19)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use SecretManager instead of SM in name
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMEntityToDTO.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCZqdXn7WbgnYcG6IzH:-NCd9X6P0FI5aJQzW8XB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSMEntityToDTO.java#L19)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use SecretManager instead of SM in name
</block [...]

2022-09-26 09:11 UTC, nishantsaini20 requested changes
> Reviewed 13 of 88 files at r2, 1 of 2 files at r3, 5 of 75 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 89 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`954-connector-beans/src/test/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSecretManagerConnectorDTOTest.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/37750#-NCt2qAPCDxqa27pg5Kw:-NCt2qAQ1mpi1it6M1YN:bm7qdim) ([raw file](https://github.com/harness/harness-core/blob/fb77c1f8a43921263a31794a2968658b9a750590/954-connector-beans/src/test/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSecretManagerConnectorDTOTest.java#L86)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testInputFieldsHaveCorrectValue() throws IllegalAccessException {
>     String secretRef = "some-secret";
> ```

use randomAlphabetic


<!-- Sent from Reviewable.io -->

2022-09-26 09:14 UTC, meenakshi-harness requested changes
> Reviewed 13 of 88 files at r2, 1 of 2 files at r3, 9 of 75 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 70 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdG-r1-42:-NCt2wyk4CwloUvzTmbC:bskqqni) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java#L42)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

Its marked as not null on dto. 
</blockquote></details>

make required here as well.


<!-- Sent from Reviewable.io -->

2022-09-26 10:00 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 72 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37750#-NCUJQEnA_xI6CL8VHdG-r1-42:-NCtEIFm0eJSST39BEXZ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/467071175441a09d9ccccb2e3a9392e9c560e0c1/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsm/GcpSMConnector.java#L42)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

make required here as well.
</blockquote></details>

Done
___
*[`954-connector-beans/src/test/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSecretManagerConnectorDTOTest.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/37750#-NCt2qAPCDxqa27pg5Kw:-NCtEEQwEJeiOyMkjn7t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb77c1f8a43921263a31794a2968658b9a750590/954-connector-beans/src/test/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSecretManagerConnectorDTOTest.java#L86)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

use randomAlphabetic
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-26 11:26 UTC, nishantsaini20 requested changes
> Reviewed 1 of 75 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 71 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 1808 at r6](https://reviewable.io/reviews/harness/harness-core/37750#-NCtXz27A47AEPgw8Hw9:-NCtXz27A47AEPgw8HwA:bdqnnp8) ([raw file](https://github.com/harness/harness-core/blob/95d9c300c17e68041d400d3f70006d1934a84863/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1808)):*
> ```Java
>     kryo.register(AzureFetchArmPreDeploymentDataTaskParameters.class, 55423);
>     kryo.register(AzureFetchArmPreDeploymentDataTaskResponse.class, 55424);
>     kryo.register(AwsS3ArtifactDelegateConfig.class, 9800007);
> ```

Why this is changed?


<!-- Sent from Reviewable.io -->

2022-09-26 11:50 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 71 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 1808 at r6](https://reviewable.io/reviews/harness/harness-core/37750#-NCtXz27A47AEPgw8Hw9:-NCtcU-qD3cOefP4hgIM:bxuj5ue) ([raw file](https://github.com/harness/harness-core/blob/95d9c300c17e68041d400d3f70006d1934a84863/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1808)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why this is changed?
</blockquote></details>

Its not changed if considered till latest revision. 


<!-- Sent from Reviewable.io -->

2022-09-26 13:22 UTC, meenakshi-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 71 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsecretmanager/GcpSecretManagerConnector.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/37750#-NCtxAO08rMbu-aJZC3l:-NCtxAO08rMbu-aJZC3m:b9xxblg) ([raw file](https://github.com/harness/harness-core/blob/95d9c300c17e68041d400d3f70006d1934a84863/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsecretmanager/GcpSecretManagerConnector.java#L44)):*
> ```Java
> public class GcpSecretManagerConnector extends Connector {
>   @Builder.Default private Boolean isDefault = false;
>   @NotNull @NotEmpty String credentialsRef;
> ```

Did we test if these validation works? 
I think on DB entities `org.hibernate.validator.constraints.NotEmpty` will work


<!-- Sent from Reviewable.io -->

2022-09-27 05:04 UTC, meenakshi-harness approved these changes
> Reviewed 66 of 75 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 70 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-27 05:05 UTC, nishantsaini20 approved these changes
> Reviewed 69 of 75 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-27 07:56 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 2. unresolved discussions. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsecretmanager/GcpSecretManagerConnector.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/37750#-NCtxAO08rMbu-aJZC3l:-NCxwZE36P562vnG7US2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95d9c300c17e68041d400d3f70006d1934a84863/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsecretmanager/GcpSecretManagerConnector.java#L44)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Did we test if these validation works? 
I think on DB entities `org.hibernate.validator.constraints.NotEmpty` will work
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-27 07:56 UTC, shreyas-harness reviewed
> Reviewed 12 of 88 files at r2, 6 of 75 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-28 05:08 UTC, shreyas-harness commented
Tested with current delegate. It works as expected.

2022-09-28 05:09 UTC, mohitg0795 approved these changes
> Reviewed 12 of 88 files at r2, 75 of 75 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-28 05:10 UTC, shreyas-harness commented
trigger codebasehash

2022-09-28 05:18 UTC, meenakshi-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37750#-:-ND1WxVbEuxxdqaifD-k:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-28 05:19 UTC, merged