fix: [CDS-43409]: include time tracking to extract fields
harness/harness-core pull request #37763
Opened 2022-09-21 12:15 UTC by rafaelmart1ns

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-21 12:17 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37763)

2022-09-21 20:41 UTC, Fernando-Dourado requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/jira/JiraTaskTest.java` line 957 at r1](https://reviewable.io/reviews/harness/harness-core/37763#-NCWm0xC4OyWTZjlqOKn:-NCWm0xC4OyWTZjlqOKo:b-n34nkz) ([raw file](https://github.com/harness/harness-core/blob/a02d3c5fe7ae7831a196f26721b14be51d577596/260-delegate/src/test/java/software/wings/delegatetasks/jira/JiraTaskTest.java#L957)):*
> ```Java
>   public void shouldReturnSuccessfulExecutionForCheckJiraApproval() throws JiraException {
>     JiraTaskParameters taskParameters = getTaskParams(JiraAction.CHECK_APPROVAL);
>     ;
> ```

Please, remove this line


<!-- Sent from Reviewable.io -->

2022-09-21 20:44 UTC, rafaelmart1ns reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-21 20:44 UTC, rafaelmart1ns reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/jira/JiraTaskTest.java` line 957 at r1](https://reviewable.io/reviews/harness/harness-core/37763#-NCWm0xC4OyWTZjlqOKn:-NCWmv2t-UGUo2AMsHgI:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/a02d3c5fe7ae7831a196f26721b14be51d577596/260-delegate/src/test/java/software/wings/delegatetasks/jira/JiraTaskTest.java#L957)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Please, remove this line
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-09-21 20:46 UTC, Fernando-Dourado approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-22 12:04 UTC, Fernando-Dourado approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-22 12:04 UTC, vcalasansh commented on 260-delegate/src/test/java/software/wings/delegatetasks/jira/JiraTaskTest.java
> +
extra line

2022-09-22 12:10 UTC, rafaelmart1ns commented on 260-delegate/src/test/java/software/wings/delegatetasks/jira/JiraTaskTest.java
> +
added by format code.

2022-09-22 12:11 UTC, vcalasansh reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-22 12:11 UTC, vcalasansh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763#-:-NC_66Nk0WnPWixQeDzj:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-22 12:12 UTC, rafaelmart1ns reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-22 12:12 UTC, rafaelmart1ns reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-22 12:13 UTC, vcalasansh approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37763)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-22 12:15 UTC, merged