feat: [PL-24488]: Add emailId as part of the ApproveOrReject GraphQL request payload
harness/harness-core pull request #37833
Opened 2022-09-23 00:29 UTC by rafaelmart1ns

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-23 00:32 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37833)

2022-09-23 16:07 UTC, Fernando-Dourado requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/approval/ApproveOrRejectApprovalsDataFetcher.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/37833#-NCf0HnL4TVsF4UC7pKq:-NCf0HnL4TVsF4UC7pKr:bq8vh1z) ([raw file](https://github.com/harness/harness-core/blob/5719d0511299647ffaf9852b73b49aaf1d19b95d/380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/approval/ApproveOrRejectApprovalsDataFetcher.java#L90)):*
> ```Java
>     ApiKeyEntry apiKeyEntry = graphQLContext.get("apiKeyEntry");
> 
>     if (approveOrRejectApprovalsInput.getUserEmail() != null
> ```

Please, evaluate the condition one time and save it to a boolean to check in the second if condition.


<!-- Sent from Reviewable.io -->

2022-09-23 16:15 UTC, rafaelmart1ns reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/approval/ApproveOrRejectApprovalsDataFetcher.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/37833#-NCf0HnL4TVsF4UC7pKq:-NCf7RSTDUpVUSCOLxZ8:b-bmgb9m) ([raw file](https://github.com/harness/harness-core/blob/5719d0511299647ffaf9852b73b49aaf1d19b95d/380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/approval/ApproveOrRejectApprovalsDataFetcher.java#L90)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Please, evaluate the condition one time and save it to a boolean to check in the second if condition.
</blockquote></details>

it fixed. 


<!-- Sent from Reviewable.io -->

2022-09-23 16:35 UTC, Fernando-Dourado approved these changes
> Reviewed 3 of 6 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-26 15:48 UTC, rafaelmart1ns reviewed
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-26 15:57 UTC, Fernando-Dourado approved these changes
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-26 15:58 UTC, Fernando-Dourado approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-26 17:14 UTC, vcalasansh commented on 380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/approval/ApproveOrRejectApprovalsDataFetcher.java
> +        throw new InvalidRequestException("User email does not valid or your user cannot access", WingsException.USER);
Up to you, but I would suggest replacing "does not valid" for "is invalid" .

2022-09-26 18:59 UTC, rafaelmart1ns commented on 380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/approval/ApproveOrRejectApprovalsDataFetcher.java
> +    boolean hasNotEmailAndFFEnabled = (approveOrRejectApprovalsInput.getUserEmail() != null)
Yes it should. done.

2022-09-26 19:00 UTC, rafaelmart1ns commented on 380-cg-graphql/src/main/java/software/wings/graphql/datafetcher/approval/ApproveOrRejectApprovalsDataFetcher.java
> +        throw new InvalidRequestException("User email does not valid or your user cannot access", WingsException.USER);
Suggestion accepted. done.

2022-09-26 19:26 UTC, vcalasansh approved these changes
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-26 19:32 UTC, Fernando-Dourado approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37833)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-26 20:28 UTC, merged