[feat]: [CDS-43742]: Azure Artifacts APIs
harness/harness-core pull request #37877
Opened 2022-09-25 19:03 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-25 19:10 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 72 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 69 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 3 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37877)

2022-09-29 07:04 UTC, puthrayaharness requested changes

2022-09-29 07:04 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/client/AzureArtifactsDevopsRestClient.java
> +public interface AzureArtifactsDevopsRestClient {
Why can we not use the existing client?

2022-09-29 07:04 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/client/AzureArtifactsRegistryRestClient.java
> +  Call<NGAzureArtifactsFeeds> listAzureArtifactsFeeds(@Header("Authorization") String authHeader);
Why can we not use the existing client?

2022-09-29 07:04 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/client/AzureArtifactsRegistryRestClient.java
> +public interface AzureArtifactsRegistryRestClient {
Please use the same client as that of CG.

2022-09-29 07:04 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryUtils.java
> +  public static void validateAzureDevopsUrl(String azureDevopsUrl) {
Can we not use this same as CG? This does even depend on any credentials

2022-09-29 07:04 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/artifacts/azureartifacts/beans/NGAzureArtifactsFeeds.java
> +  private List<NGAzureArtifactsFeed> value;
Why can we not use this same as CG?

2022-09-29 07:04 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/artifacts/azureartifacts/beans/NGAzureArtifactsPackage.java
> +public class NGAzureArtifactsPackage {
Why can we not use the same as CG?

2022-09-29 07:04 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/artifacts/azureartifacts/beans/NGAzureArtifactsPackageFileInfo.java
> +public class NGAzureArtifactsPackageFileInfo {
Why not use the same as CG?

2022-09-29 07:04 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/artifacts/azureartifacts/beans/NGAzureArtifactsPackageVersion.java
> +public class NGAzureArtifactsPackageVersion {
Please share with CG file.

2022-09-29 07:04 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/artifacts/azureartifacts/beans/NGAzureArtifactsPackageVersions.java
> +public class NGAzureArtifactsPackageVersions {
Please use this same as CG

2022-09-29 07:04 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/artifacts/azureartifacts/beans/NGAzureArtifactsPackages.java
> +public class NGAzureArtifactsPackages {
Please use same as CG

2022-09-30 11:09 UTC, puthrayaharness requested changes

2022-09-30 11:09 UTC, puthrayaharness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azureartifacts/AzureArtifactsUsernameToken.java
> +public class AzureArtifactsUsernameToken {
Rename to PersonalAccessToken

2022-09-30 11:09 UTC, puthrayaharness commented on 440-connector-nextgen/src/main/java/io/harness/connector/mappers/azureartifacts/AzureArtifactsDTOToEntity.java
> +      throw new InvalidRequestException("AzureArtifacts Http Auth Type not found");
Change the error message.

2022-09-30 11:09 UTC, puthrayaharness commented on 440-connector-nextgen/src/main/java/io/harness/connector/mappers/azureartifacts/AzureArtifactsEntityToDTO.java
> +        throw new UnknownEnumTypeException("AzureArtifacts Http Auth Type", type.getDisplayName());
Change the error message.

2022-10-03 13:52 UTC, puthrayaharness requested changes

2022-10-03 13:52 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/azureartifacts/AzureArtifactsDelegateResponse.java
> +  public AzureArtifactsDelegateResponse(ArtifactBuildDetailsNG buildDetails, ArtifactSourceType sourceType,
Remove unused constructer params

2022-10-03 13:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +    if (EmptyPredicate.isEmpty(version) && EmptyPredicate.isEmpty(versionRegex)) {
Fix this. Throw error

2022-10-03 13:52 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/pms/expressions/utils/ImagePullSecretUtils.java
> +    imageDetailsBuilder.username(username);
Remove username

2022-10-03 13:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/azureartifacts/AzureArtifactsResourceServiceImpl.java
> +          HintException.HINT_GITHUB_ACCESS_DENIED, new InvalidRequestException(e.getMessage(), USER));
Fix message.

2022-10-03 13:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/azureartifacts/AzureArtifactsResourceServiceImpl.java
> +          HintException.HINT_GITHUB_ACCESS_DENIED, new InvalidRequestException(e.getMessage(), USER));
Fix

2022-10-03 13:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/azureartifacts/AzureArtifactsResourceServiceImpl.java
> +public class AzureArtifactsResourceServiceImpl implements AzureArtifactsResourceService {
Fix hint Github

2022-10-03 13:52 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/azureartifacts/AzureArtifactsResourceServiceImpl.java
> +public class AzureArtifactsResourceServiceImpl implements AzureArtifactsResourceService {
Please refactor the code to remove the try-catch block everywher.

2022-10-03 13:52 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      throw new InvalidRequestException("Failed to get builds from regex");
Replace with hint explnation exception

2022-10-04 07:31 UTC, puthrayaharness approved these changes

2022-10-04 07:32 UTC, puthrayaharness approved these changes
> Reviewed 18 of 102 files at r1, 31 of 81 files at r2, 32 of 40 files at r3, 20 of 30 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37877)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-04 07:35 UTC, vtxorxwitty commented
trigger codebasehash

2022-10-04 07:52 UTC, archit-harness approved these changes
> Reviewed 1 of 40 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37877)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-04 07:54 UTC, prashantsharma04 approved these changes
> Reviewed 18 of 102 files at r1, 31 of 81 files at r2, 32 of 40 files at r3, 20 of 30 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37877)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-04 08:00 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 40 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37877)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-04 08:56 UTC, merged