fix: [DEL-4834]: Display watcher/delegate version for all rings
harness/harness-core pull request #37893
Opened 2022-09-26 07:13 UTC by gaurav-jain1

## Describe your changes
Changeset to display delegate version from all rings in /api/version call.
Following will be api call, where one can find version for delegate and watcher:
1) /api/version/delegate/ring/all
2) /api/version/watcher/ring/all
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-26 07:15 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 2 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37893)

2022-09-26 07:25 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCsfPDG9-8xoL5JgMvm:-NCsfPDG9-8xoL5JgMvn:bldie7x) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L68)):*
> ```Java
>   @ExceptionMetered
>   @PublicApi
>   public RestResponse<Map<String, List<String>>> getDelegateVersionFromRing() {
> ```

This is useful for legacy delegates only, right? What if USE_IMMUTABLE_DELEGATE FF is on? should we display delegateImageTag then


<!-- Sent from Reviewable.io -->

2022-09-26 10:49 UTC, mdmilic submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCsfPDG9-8xoL5JgMvm:-NCtPQxFA3PwgGUBJxj6:blljbre) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L68)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

This is useful for legacy delegates only, right? What if USE_IMMUTABLE_DELEGATE FF is on? should we display delegateImageTag then
</blockquote></details>

No for immutable we should have a separate API


<!-- Sent from Reviewable.io -->

2022-09-26 11:09 UTC, AnupamIO submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-26 11:52 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCtcVH_EYE65CdqtmUr:-NCtcVH_EYE65CdqtmUs:b-jmd83u) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L72)):*
> ```Java
>     String[] rings = {RING_NAME_1, RING_NAME_2, RING_NAME_3};
>     for (String ringName : rings) {
>       final List<String> ringVersion = delegateRingService.getDelegateVersionsForRing(ringName, false);
> ```

Writing service logic in resource classes have caused problems for in the recent past. So, i would recommend to move all this logic to service layer.



_Code quote:_
```Java
    for (String ringName : rings) {
      final List<String> ringVersion = delegateRingService.getDelegateVersionsForRing(ringName, false);
      ringNameToVersion.put(ringName, ringVersion);
    }
```


<!-- Sent from Reviewable.io -->

2022-09-26 17:26 UTC, xingchi-jin requested changes

2022-09-26 17:26 UTC, xingchi-jin commented on 400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java
> +  @Path("/watcher/ring/all")
can we change the api path to. GET  /wather/rings 
API path should represent a resource in the system, because "all" is not a resource

2022-09-26 17:26 UTC, xingchi-jin commented on 400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java
> +  @Path("/delegate/ring/all")
can we change here to /delegate/rings ?

2022-09-27 00:02 UTC, xingchi-jin requested changes
add one comment

note: sorry I forgot to use the Reviewable tool.. it was a habit

2022-09-27 07:18 UTC, gaurav-jain1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893)* status: 1 change requests. 3. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCsd8IWZ2Q07dsQcjhh-r1-64:-NCxnrqp3sO3Wnjhe0c7:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L64)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

can we change here to /delegate/rings ? 
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCsfPDG9-8xoL5JgMvm:-NCxekp39lE4TCTGcQRI:b2ne6o5) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L68)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

No for immutable we should have a separate API
</blockquote></details>

We can integrate immutable tag version, once we enable FF in field. Right now not many folks are interested in knowing immutable version, so don't want to overload this API with too much info.
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCtcVH_EYE65CdqtmUr:-NCxnuhl4hgSA-w8u1Aw:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L72)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Writing service logic in resource classes have caused problems for in the recent past. So, i would recommend to move all this logic to service layer.
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCsd8IWZ2Q07dsQcjhh-r1-98:-NCxfEHLDvwjIDu14gBz:btzaiye) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L98)):*
> service logic in resource classes have caused problems for in the recent past. So, i would recommend to move all this logic to service layer
Done
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/37893#-NCsd8IWZ2Q07dsQcjhh-r1-103:-NCxnnNLBnyEC-BRIUGj:b-yvsr7h) ([raw file](https://github.com/harness/harness-core/blob/54fe3db5b2b7d2d27d8efeb48c7ba7f8a9b87cea/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L103)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

you can simply the code to be declarative way, one liner
return new RestResponse<>(
 Arrays.asList(RING_NAME_1, RING_NAME_2, RING_NAME_3)
   .stream()
   .collect(Collectors.toMap(
      ringName -> ringName,
      ringName -> delegateRingService.getWatcherVersionsForRing(ringName, false)
   )
);


</blockquote></details>

we moved this logic to service layer.


<!-- Sent from Reviewable.io -->

2022-09-27 16:32 UTC, xingchi-jin approved these changes
LGTM, with two nits

2022-09-27 16:32 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java
> +    for (String ringName : rings) {
use stream method

2022-09-27 16:32 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java
> +    for (String ringName : rings) {
use stream method

2022-09-28 18:17 UTC, xingchi-jin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893#-:-ND4JBkbC0VJFmBkxzfY:bnfp4nl)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-29 05:18 UTC, gaurav-jain1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893)* status: 5. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/37893#-NCxpxc0jQ_RO0Rz48Ex-r2-56:-ND6fUaW7M9Kb6-XM5Mi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3ff33cff7df4c690376a77026e1e894ec0a4bccb/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L56)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

use stream method
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/37893#-NCxpxc0jQ_RO0Rz48Ex-r2-89:-ND6fVSE5dUTAvb4GGo1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3ff33cff7df4c690376a77026e1e894ec0a4bccb/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L89)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

use stream method
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-29 05:31 UTC, xingchi-jin approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37893)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-29 05:50 UTC, merged