[fix]: [PL-27908]: Custom sm host machine changes
harness/harness-core pull request #37935
Opened 2022-09-26 15:49 UTC by shreyas-harness

## Describe your changes
Adding capablity to run on host machine
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-26 15:51 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37935)

2022-09-27 10:28 UTC, meenakshi-harness commented on 930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java
> +    String executionId = "custom-sm"
Why we need this?

2022-09-27 12:12 UTC, shreyas-harness commented
trigger messagecheck

2022-09-27 12:14 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: 13 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/37935#-NCuUF8wRF5l6ihFYDFu-r2-142:-NCyrPp74SnuRDpLiiBh:b-uq76ag) ([raw file](https://github.com/harness/harness-core/blob/2ed6145eb1eb084bc562f81ac31122b5c0aabc17/930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java#L142)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Why we need this?
</blockquote></details>

Execution id needs to be a not null value. 
Setting it as custom-sm-{timestamp} for easy navigation in logs.


<!-- Sent from Reviewable.io -->

2022-09-28 04:34 UTC, shreyas-harness commented on 930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java
> +    String executionId = "custom-sm"
Also, the execution id is used for caching session which we haven't enabled. So any not-null value would solve the purpose

2022-09-28 05:51 UTC, meenakshi-harness requested changes

2022-09-28 05:51 UTC, meenakshi-harness commented on 930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java
> +    String executionId = "custom-sm"
Is it required in Params DTO or in Handler? If in handler than lets modify the code to not use it?

2022-09-28 15:52 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: 14 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java` line 126 at r5](https://reviewable.io/reviews/harness/harness-core/37935#-ND1yeEE4QLu6JDYcPfL:-ND3msy2EFvBYcN2gVYT:b-otmhrv) ([raw file](https://github.com/harness/harness-core/blob/143863a5515a02a7781c23375af4d2fe96dd5e2d/890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java#L126)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add UT covering this method
</blockquote></details>

Done. Added test case
___
*[`890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java` line 137 at r5](https://reviewable.io/reviews/harness/harness-core/37935#-ND1xvDD-jPgRwPDh87j:-ND3mvMxBd8isKZB-7Bg:b-9ulnoc) ([raw file](https://github.com/harness/harness-core/blob/143863a5515a02a7781c23375af4d2fe96dd5e2d/890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java#L137)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Check that errorMSg as a parameter doesn't suppress original message.
</blockquote></details>

It does not suppress the original message. Only if we dont get any message but still null result, we use it as default message. 
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/37935#-NCuUF8wRF5l6ihFYDFu-r2-142:-ND3n3d16ybR-eU4P3Fb:bfbtml9) ([raw file](https://github.com/harness/harness-core/blob/2ed6145eb1eb084bc562f81ac31122b5c0aabc17/930-delegate-tasks/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerValidationUtils.java#L142)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Is it required in Params DTO or in Handler? If in handler than lets modify the code to not use it?
</blockquote></details>

Made it random uuid since any random value will work for us.


<!-- Sent from Reviewable.io -->

2022-09-29 04:00 UTC, nishantsaini20 requested changes
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: 14 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java` line 128 at r6](https://reviewable.io/reviews/harness/harness-core/37935#-ND6OQ7r7XFrXLxCq_Zb:-ND6OQ7r7XFrXLxCq_Zc:b7ecfqg) ([raw file](https://github.com/harness/harness-core/blob/de6257cdde44ea46d397f7be161cc3c599530dda/890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java#L128)):*
> ```Java
> 
>   @VisibleForTesting
>   public void getSSHSupportedConfig(EncryptionConfig encryptionConfig) {
> ```

This method doesn't return anything. It should be renamed to something like fillSSHSupportedConfig or addSSHSupportedConfig
___
*[`890-sm-core/src/test/java/io/harness/encryptors/NGManagerCustomEncryptorTest.java` line 76 at r6](https://reviewable.io/reviews/harness/harness-core/37935#-ND6Nqhj1EGZFM3g2V_v:-ND6Nqhk3uU6FFWKcZjD:b-iw90by) ([raw file](https://github.com/harness/harness-core/blob/de6257cdde44ea46d397f7be161cc3c599530dda/890-sm-core/src/test/java/io/harness/encryptors/NGManagerCustomEncryptorTest.java#L76)):*
> ```Java
>     assertThat(customSecretNGManagerConfig.getSshKeyEncryptionDetails()).isNotNull();
>     assertThat(customSecretNGManagerConfig.getSshKeyEncryptionDetails()).isEqualTo(encryptedDataDetails);
>   }
> ```

UT missing for case when secretResponseWrapper is null.


<!-- Sent from Reviewable.io -->

2022-09-29 04:46 UTC, shreyas-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: 14 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java` line 128 at r6](https://reviewable.io/reviews/harness/harness-core/37935#-ND6OQ7r7XFrXLxCq_Zb:-ND6ZAdH89LbaHPmCC-i:bctnihh) ([raw file](https://github.com/harness/harness-core/blob/de6257cdde44ea46d397f7be161cc3c599530dda/890-sm-core/src/main/java/io/harness/ng/core/encryptors/NGManagerCustomEncryptor.java#L128)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This method doesn't return anything. It should be renamed to something like fillSSHSupportedConfig or addSSHSupportedConfig
</blockquote></details>

Updated to method name to addSSHSupportedConfig
___
*[`890-sm-core/src/test/java/io/harness/encryptors/NGManagerCustomEncryptorTest.java` line 76 at r6](https://reviewable.io/reviews/harness/harness-core/37935#-ND6Nqhj1EGZFM3g2V_v:-ND6ZExO1_RBWTNwSNSO:b-b8rdhf) ([raw file](https://github.com/harness/harness-core/blob/de6257cdde44ea46d397f7be161cc3c599530dda/890-sm-core/src/test/java/io/harness/encryptors/NGManagerCustomEncryptorTest.java#L76)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

UT missing for case when secretResponseWrapper is null.
</blockquote></details>

Added test case to check correct exception is thrown when secret response data is null


<!-- Sent from Reviewable.io -->

2022-09-29 04:47 UTC, nishantsaini20 submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-29 07:34 UTC, meenakshi-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: 14 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-09-29 11:42 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-29 12:11 UTC, meenakshi-harness approved these changes
> Reviewed 4 of 9 files at r1, 5 of 6 files at r2, 1 of 1 files at r5, 1 of 3 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-29 14:43 UTC, piyush-harness commented
Approved for hashcheck





<!-- Sent from Reviewable.io -->

2022-09-29 14:43 UTC, piyush-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37935#-:-ND8grq2A386tIBZDtOg:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-29 14:50 UTC, merged