[CDS-42091]: Service V2 support for Jenkins API
harness/harness-core pull request #37936
Opened 2022-09-26 15:59 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-26 16:01 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 8 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 5 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 3 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37936)

2022-09-27 05:51 UTC, hingerabhinav commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/jenkins/JenkinsArtifactResource.java
> +      }
parentJobName would be available always? Should we get from config if its empty in request?

2022-09-28 09:47 UTC, hingerabhinav requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37936)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/jenkins/JenkinsArtifactResource.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/37936#-ND2T_yR0aWlE-4C2ktr:-ND2T_yS8GlLNy4MYRGT:b-g9eghl) ([raw file](https://github.com/harness/harness-core/blob/b4ed33bd419cd98810c6cb39e09711ef65a22892/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/jenkins/JenkinsArtifactResource.java#L137)):*
> ```Java
>       @NotNull @QueryParam(NGCommonEntityConstants.ORG_KEY) String orgIdentifier,
>       @NotNull @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @QueryParam("parentJobName") String parentJobName, @BeanParam GitEntityFindInfoDTO gitEntityBasicInfo,
> ```

Let's create constants for these params. We can reuse them.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/jenkins/JenkinsArtifactResource.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/37936#-NCuWZcJ_WD4wuYAl7NC-r2-146:-ND2TemR1h_gmXa4ilbW:b2kv38v) ([raw file](https://github.com/harness/harness-core/blob/b4ed33bd419cd98810c6cb39e09711ef65a22892/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/jenkins/JenkinsArtifactResource.java#L146)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

ParentJob name is not in yaml, UI have to provide this value
</blockquote></details>

Got it. Can it be given as an expression? Then we will need resolving logic here as well.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/jenkins/JenkinsArtifactResource.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/37936#-ND2UNFnD4-wPXVimwUF:-ND2UNFnD4-wPXVimwUG:bygpwf5) ([raw file](https://github.com/harness/harness-core/blob/b4ed33bd419cd98810c6cb39e09711ef65a22892/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/jenkins/JenkinsArtifactResource.java#L178)):*
> ```Java
>       }
>     }
>     jobName = artifactResourceUtils.getResolvedImagePath(accountId, orgIdentifier, projectIdentifier,
> ```

Please create a tech-debt to refactor this method since it works with other fields other than image path.



_Code quote:_
```Java
getResolvedImagePath
```


<!-- Sent from Reviewable.io -->

2022-10-19 17:44 UTC, puthrayaharness submitted a review, later dismissed

2022-10-20 05:46 UTC, hingerabhinav approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37936)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-20 05:46 UTC, merged