feat: [PL-28018]: added secrets decryption API
harness/harness-core pull request #37975
Opened 2022-09-27 08:50 UTC by tiwaritejas

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-27 08:52 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37975)

2022-09-27 10:30 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 612 at r1](https://reviewable.io/reviews/harness/harness-core/37975#-NCyNI56ETqCkDGznuGo:-NCyNI56ETqCkDGznuGp:b-v5epkr) ([raw file](https://github.com/harness/harness-core/blob/f5f730c726ed0598b69f4b2873fe7787f6f5fd09/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L612)):*
> ```Java
>         @io.swagger.v3.oas.annotations.responses.
>         ApiResponse(responseCode = "default", description = "Returns decrypted secret")
>       })
> ```

Mark it as @InternalApi and @Hidden
___
*[`980-commons/src/main/java/io/harness/beans/DecryptedSecretValue.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37975#-NCyT7V87jVUZwUydby9:-NCyT7V87jVUZwUydbyA:b-wtgk7v) ([raw file](https://github.com/harness/harness-core/blob/f5f730c726ed0598b69f4b2873fe7787f6f5fd09/980-commons/src/main/java/io/harness/beans/DecryptedSecretValue.java#L14)):*
> ```Java
> @Data
> @Builder
> @AllArgsConstructor
> ```

This is not required


<!-- Sent from Reviewable.io -->

2022-09-27 11:58 UTC, piyush-harness commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 604 at r2](https://reviewable.io/reviews/harness/harness-core/37975#-NCynl2o2kfTuBiH3oMu:-NCynl2pAUPCs46-TokJ:b-ptt7j) ([raw file](https://github.com/harness/harness-core/blob/853ec1ec693d44413e5c79582a9ec4d8e9014ff9/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L604)):*
> ```Java
> 
>   @GET
>   @Path("decrypt-secret/{identifier}")
> ```

/{identifier}/decrypt


<!-- Sent from Reviewable.io -->

2022-09-27 11:59 UTC, piyush-harness commented
*[`120-ng-manager/src/test/java/io/harness/NgManagerComponentTest.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/37975#-NCyo6feA532xCSIfYa9:-NCyo6ffESSLRH5-_6Nr:b-pi9d9n) ([raw file](https://github.com/harness/harness-core/blob/853ec1ec693d44413e5c79582a9ec4d8e9014ff9/120-ng-manager/src/test/java/io/harness/NgManagerComponentTest.java#L33)):*
> ```Java
>   public void componentNgManagerTests() {
>     for (Map.Entry<String, TestExecution> test : tests.entrySet()) {
>       log.info("hemlo"+test.getKey());
> ```

remove this


<!-- Sent from Reviewable.io -->

2022-09-27 12:14 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 612 at r1](https://reviewable.io/reviews/harness/harness-core/37975#-NCyNI56ETqCkDGznuGo:-NCyrVRYC7Y7jHQnll0O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f5f730c726ed0598b69f4b2873fe7787f6f5fd09/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L612)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Mark it as @InternalApi and @Hidden
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 604 at r2](https://reviewable.io/reviews/harness/harness-core/37975#-NCynl2o2kfTuBiH3oMu:-NCyrUxTCVezEhMNZJfD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/853ec1ec693d44413e5c79582a9ec4d8e9014ff9/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L604)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

/{identifier}/decrypt
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/beans/DecryptedSecretValue.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37975#-NCyT7V87jVUZwUydby9:-NCyrWY7Aow_foIv1H0U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f5f730c726ed0598b69f4b2873fe7787f6f5fd09/980-commons/src/main/java/io/harness/beans/DecryptedSecretValue.java#L14)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This is not required
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/NgManagerComponentTest.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/37975#-NCyo6feA532xCSIfYa9:-NCyrXRyCcFWtUGEDlFA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/853ec1ec693d44413e5c79582a9ec4d8e9014ff9/120-ng-manager/src/test/java/io/harness/NgManagerComponentTest.java#L33)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-27 12:25 UTC, nishantsaini20 requested changes
> Reviewed 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 474 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCytD3--01-cFcPjjWT:-NCytD3--01-cFcPjjWU:b-vccymd) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L474)):*
> ```Java
>         accountIdentifier, orgIdentifier, projectIdentifier, encryptedData.getSecretManagerIdentifier(), false);
>     String decryptedValue = null;
>     if (secretManager != null) {
> ```

Should throw an exception if secret manager is null
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 479 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCytob35z6dzpWn6EBO:-NCytob35z6dzpWn6EBP:bqh5h4u) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L479)):*
> ```Java
>       EncryptedRecordData encryptedRecordData;
>       if (secretManager.isHarnessManaged()
>           || HARNESS_SECRET_MANAGER_IDENTIFIER.equals(encryptedData.getSecretManagerIdentifier())) {
> ```

If this condition doesn't pass then response will have decrypted value as null. Instead we should throw proper exceptions in such cases.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 487 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCyu76uBBl88sN_-inp:-NCyu76uBBl88sN_-inq:b-bm9u6w) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L487)):*
> ```Java
>               ngEncryptorService.fetchSecretValue(accountIdentifier, encryptedRecordData, encryptionConfig));
>         } else {
>           log.error("Failed to decrypt secret {} with {} harness secret manager", encryptedData.getUuid(),
> ```

This error look misleading and doesn't give clear idea on actual failure.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCysoSVEQSYNTDLR_em:-NCysoSY5VlPZxqivTJE:bbj8ak) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java#L90)):*
> ```Java
>     when(vaultEncryptorsRegistry.getVaultEncryptor(any())).thenReturn(vaultEncryptor);
>   }
> ```

UT for new method is missing


<!-- Sent from Reviewable.io -->

2022-09-28 06:04 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 5 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 474 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCytD3--01-cFcPjjWT:-ND1gL4n-b-4-j8VoFls:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L474)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should throw an exception if secret manager is null
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 479 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCytob35z6dzpWn6EBO:-ND1gMKG17GCBKKdi3M0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L479)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

If this condition doesn't pass then response will have decrypted value as null. Instead we should throw proper exceptions in such cases.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 487 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCyu76uBBl88sN_-inp:-ND1gMwr9S50uWu8XRLE:b3az34w) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L487)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This error look misleading and doesn't give clear idea on actual failure.
</blockquote></details>

This check is not required, so removed it.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/37975#-NCysoSVEQSYNTDLR_em:-ND1gUUI1jIbN_bwoeVB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0388f431903c92be3aab3e40afc4a36c21613b89/120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java#L90)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

UT for new method is missing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-28 06:12 UTC, nishantsaini20 requested changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 474 at r4](https://reviewable.io/reviews/harness/harness-core/37975#-ND1hMTGAMssNOBrEfeZ:-ND1hMTI7LyCr5glY8_P:b-opvo9p) ([raw file](https://github.com/harness/harness-core/blob/da53617466c2ac688d874d3cd861926e8b05fcee/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L474)):*
> ```Java
>         accountIdentifier, orgIdentifier, projectIdentifier, encryptedData.getSecretManagerIdentifier(), false);
>     String decryptedValue = null;
>     if (secretManager != null) {
> ```

if (secretManager == null) {
   throw ..
}
//continue with business logic..

This way we can avoid nested ifs


<!-- Sent from Reviewable.io -->

2022-09-28 09:44 UTC, nishantsaini20 submitted a review, later dismissed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 5 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-28 09:58 UTC, meenakshi-harness requested changes

2022-09-28 09:58 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java
> +  @Path("{identifier}/decrypt")
What is the correct way `{identifier}/decrypt` or `decrypt/{identifier}`? I see both patterns in our code.Should we check with foundation squad once?

2022-09-28 09:58 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java
> +  @Operation(operationId = "getDecryptedSecret",
If this is Internal we should not need this

2022-09-28 09:58 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +            || HARNESS_SECRET_MANAGER_IDENTIFIER.equals(secretManagerConfig.getNgMetadata().getIdentifier()));
You can use `GlobalSecretManagerUtils.isNgHarnessSecretManage`

2022-09-28 10:01 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java
> +  @Path("{identifier}/decrypt")
@piyush-harness asked keep the structure this way. Earlier, I had used the other one, and then he asked me to use the current one

2022-09-28 10:02 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +            || HARNESS_SECRET_MANAGER_IDENTIFIER.equals(secretManagerConfig.getNgMetadata().getIdentifier()));
Its a part of 930-delegate-tasks, which will be needed to be added as a new dependency in 120-ng-manager, since it is not already present. Hence, I avoided it.

2022-09-28 10:04 UTC, meenakshi-harness requested changes

2022-09-28 10:04 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +          "Secret manager with the identifier {%s} does not exist", encryptedData.getSecretManagerIdentifier()));
Can we check if there is some existing method with this logic.

2022-09-28 10:06 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +          "Secret manager with the identifier {%s} does not exist", encryptedData.getSecretManagerIdentifier()));
Check this `getSecretManagerOrThrow`

2022-09-28 10:26 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 5 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 476 at r5](https://reviewable.io/reviews/harness/harness-core/37975#-NCyhqDfW7xTaRaDFomw-r5-476:-ND2cXH-3tfaAA9vxW3N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86dc1ee3e2b8a0ca35065fa0ed67ded139bde3b2/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L476)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Check this `getSecretManagerOrThrow` in same class
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java` line 607 at r5](https://reviewable.io/reviews/harness/harness-core/37975#-NCy7uzIC5uIE-L-l9C9-r5-607:-ND2cYy07p5iCOT-Tw3r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86dc1ee3e2b8a0ca35065fa0ed67ded139bde3b2/120-ng-manager/src/main/java/io/harness/ng/core/remote/NGSecretResourceV2.java#L607)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

If this is Internal we should not need this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-28 11:14 UTC, VikasMaddukuriHarness approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-28 11:32 UTC, meenakshi-harness approved these changes
> Reviewed 4 of 8 files at r2, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-28 11:36 UTC, nishantsaini20 approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-28 11:36 UTC, meenakshi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37975)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-09-28 11:55 UTC, merged