[feat]: [PIE-4876]: Trigger Drawer Listing Call
harness/harness-core pull request #38082
Opened 2022-09-28 19:13 UTC by sribalij

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-28 19:16 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38082)

2022-09-29 00:34 UTC, abhinav-harness requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38082)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 440 at r1](https://reviewable.io/reviews/harness/harness-core/38082#-ND5dWqrDXtcYihsmr6h:-ND5dWqrDXtcYihsmr6i:bb7phvt) ([raw file](https://github.com/harness/harness-core/blob/eb8a162e81ba5ff1966c77b49869dea52c5924bc/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L440)):*
> ```Java
>   PL_NO_EMAIL_FOR_SAML_ACCOUNT_INVITES("No email for users in account where SAML auth is enabled", HarnessTeam.PL),
>   PL_ENABLE_GOOGLE_SECRET_MANAGER_IN_NG("Enable Google Secret Manager in NG", HarnessTeam.PL),
>   CD_TRIGGER_CATALOG("Enables UI for Trigger cataloh for Nexus ", HarnessTeam.CDC);
> ```

typo
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogType.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/38082#-ND5e7Qf8DUFG-pZYXgs:-ND5e7Qf8DUFG-pZYXgt:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/eb8a162e81ba5ff1966c77b49869dea52c5924bc/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogType.java#L37)):*
> ```Java
> 
>   // Manifest
>   @JsonProperty("HelmChart") HELM_CHART("HelmChart"),
> ```

discussed offline



_Code quote:_
```Java
ate final String displayName;
```


<!-- Sent from Reviewable.io -->

2022-09-29 21:25 UTC, abhinav-harness commented on pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/NGTriggerCatalogDTO.java
> +  @Schema(description = ConnectorConstants.CONNECTOR_CATALOGUE_LIST) List<TriggerCatalogItem> catalog;
wrong schema?

2022-09-29 21:27 UTC, abhinav-harness commented on pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/NGTriggerCatalogDTO.java
> +  @Schema(description = ConnectorConstants.CONNECTOR_CATALOGUE_LIST) List<TriggerCatalogItem> catalog;
incorrect scgema

2022-09-29 21:28 UTC, abhinav-harness commented on pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java
> +        ApiResponse(responseCode = "default", description = "Returns the Connector catalogue response")
connector

2022-09-29 21:28 UTC, abhinav-harness commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerCatalogHelper.java
> +  public List<TriggerCatalogItem> getConnectorTypeToCategoryMapping(String accountIdentifier) {
wrong method name

2022-09-29 21:28 UTC, abhinav-harness commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +    return triggerCatalogHelper.getConnectorTypeToCategoryMapping(accountIdentifier);
wrong method name

2022-09-29 22:21 UTC, sribalij commented
trigger codeformat

2022-09-29 23:17 UTC, sribalij reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38082)* status: 13 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/NGTriggerCatalogDTO.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/38082#-ND4WDY2SAQ2jVdb30Fn-r2-33:-NDAXUM1CdrWqXPlYWOx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0cfde8a79059023546a95c57837318a253070bfc/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/NGTriggerCatalogDTO.java#L33)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

incorrect scgema
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogType.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/38082#-ND5e7Qf8DUFG-pZYXgs:-NDAXVfY8j9K_EeL_0gM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eb8a162e81ba5ff1966c77b49869dea52c5924bc/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogType.java#L37)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

discussed offline
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 263 at r2](https://reviewable.io/reviews/harness/harness-core/38082#-ND4WDY2SAQ2jVdb30Fr-r2-263:-NDAXWu_8NgtP7SzAI36:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0cfde8a79059023546a95c57837318a253070bfc/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L263)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

connector
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerCatalogHelper.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/38082#-ND4WDY2SAQ2jVdb30Fu-r2-28:-NDAXY9l6aX1CiDRgrBr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0cfde8a79059023546a95c57837318a253070bfc/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerCatalogHelper.java#L28)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

wrong method name
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 953 at r2](https://reviewable.io/reviews/harness/harness-core/38082#-ND4WDY2SAQ2jVdb30Fy-r2-953:-NDAXYvhAAVBvUjC3eEs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0cfde8a79059023546a95c57837318a253070bfc/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L953)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

wrong method name
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-30 05:42 UTC, vaibhav-si approved these changes
> Reviewed 7 of 14 files at r1, 2 of 4 files at r2, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38082)* status: 6 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-09-30 06:09 UTC, sribalij commented
trigger codebasehashcheck

2022-09-30 12:49 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 7 of 14 files at r1, 2 of 4 files at r2, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38082)* status: 1 change requests. 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-03 16:45 UTC, abhinav-harness approved these changes
> Reviewed 1 of 4 files at r2, 2 of 5 files at r3, 1 of 2 files at r4, 3 of 9 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38082)* status: 10 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-10-03 16:59 UTC, sahilhindwani-harness approved these changes
> Reviewed 3 of 9 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38082)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-03 17:20 UTC, praveensugavanam approved these changes
> Reviewed 6 of 14 files at r1, 2 of 4 files at r2, 2 of 5 files at r3, 1 of 2 files at r4, 3 of 9 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38082)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-03 17:26 UTC, merged