[feat]: [CDS-43742]: Azure Artifacts Classes Refactoring to 970-api-services-beas
harness/harness-core pull request #38129
Opened 2022-09-29 10:16 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-29 10:18 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 29 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 2 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 26 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38129)

2022-09-29 18:20 UTC, puthrayaharness requested changes

2022-09-29 18:20 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/serializer/kryo/ApiServiceBeansKryoRegister.java
> +    kryo.register(AzureArtifactsFeed.class, 80301);
Please do not change the Kryo numbers when you move classes. Keep them same as before otherwise they will fail

2022-09-29 18:44 UTC, puthrayaharness requested changes

2022-09-29 18:44 UTC, puthrayaharness commented on 260-delegate/src/test/resources/kryo-registrations.txt
> +80302:software.wings.helpers.ext.azure.devops.AzureArtifactsFeeds
Update here?

2022-09-29 19:42 UTC, puthrayaharness approved these changes
> Reviewed 5 of 15 files at r1, 11 of 13 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38129)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-30 05:04 UTC, vtxorxwitty commented
trigger codebasehash

2022-09-30 05:31 UTC, merged