fix: [cds-43667]: fix notification configured for a user group
harness/harness-core pull request #38201
Opened 2022-09-30 11:01 UTC by boopesh007

## fix notification configured for a user group

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-09-30 11:04 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38201)

2022-09-30 11:21 UTC, rijajoo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38201#-:-NDD7Jef89Wt9ckv9Zmi:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-09-30 11:24 UTC, rijajoo commented on pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java
> +            NotificationRequest.UserGroup.newBuilder().setIdentifier(userGroup.getIdentifier());
if userGroup is not null, then ..

2022-09-30 16:14 UTC, ershadalim reviewed
Where are unit tests?

2022-10-03 10:44 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38201)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-03 11:18 UTC, rijajoo requested changes
Unit tests are failing.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38201#-:-NDSZJ9PCSrWmMw2VWXp:b-c6qg44)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java` line 188 at r2](https://reviewable.io/reviews/harness/harness-core/38201#-NDSBWM_B3iDA8qFvMpU:-NDSBWM_B3iDA8qFvMpV:bzifj2g) ([raw file](https://github.com/harness/harness-core/blob/89b039251e9ef79b73770769fd19dea0399cadd2/pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java#L188)):*
> ```Java
>             ? PredefinedTemplate.HARNESS_APPROVAL_EXECUTION_NOTIFICATION_EMAIL.getIdentifier()
>             : PredefinedTemplate.HARNESS_APPROVAL_NOTIFICATION_EMAIL.getIdentifier();
>         NotificationRequest.UserGroup.Builder notifyUserGroupBuilder =
> ```

Please add userGroup != null check before this. 


<!-- Sent from Reviewable.io -->

2022-10-03 14:30 UTC, brijeshdhakar approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38201)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-03 14:52 UTC, rijajoo reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38201)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-03 14:52 UTC, rijajoo reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38201#-:-NDTKK5A-q0k4mDkeMKw:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-03 14:53 UTC, rijajoo approved these changes

2022-10-05 06:35 UTC, boopesh007 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java` line 188 at r2](https://reviewable.io/reviews/harness/harness-core/38201#-NDSBWM_B3iDA8qFvMpU:-NDaqjlRCBkTSG-WAhsm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89b039251e9ef79b73770769fd19dea0399cadd2/pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java#L188)):*
<details><summary><i>Previously, rijajoo (Richa Jajoo) wrote…</i></summary><blockquote>

Please add userGroup != null check before this. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-05 06:52 UTC, boopesh007 commented
trigger authorcheck

2022-10-05 07:12 UTC, abhinav-harness approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38201)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-05 07:14 UTC, merged