[fix]: [CDS-42953]: Custom Artifact trigger changes
harness/harness-core pull request #38263
Opened 2022-10-03 10:12 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-03 10:15 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38263)

2022-10-07 05:17 UTC, puthrayaharness requested changes

2022-10-07 05:17 UTC, puthrayaharness commented on 120-ng-manager/config.yml
> -shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-false}
Please revert

2022-10-07 11:18 UTC, vtxorxwitty approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 21 files at r1, 77 of 78 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38263#-:-NDm9hEs5UvIPgg5avj7:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-07 13:00 UTC, puthrayaharness approved these changes
> Reviewed 3 of 21 files at r1, 77 of 78 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-07 13:53 UTC, Jimit09Gandhi reviewed
> Reviewed 3 of 21 files at r1, 77 of 78 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38263)* status: :shipit: complete! ✓

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/version/VersionInfoResource.java` line 2 at r3](https://reviewable.io/reviews/harness/harness-core/38263#-NDmi4t_9TSFEL-l_zmq:-NDmi4t_9TSFEL-l_zmr:b-epz65v) ([raw file](https://github.com/harness/harness-core/blob/31f05ba0c11ba92bfd2a70c73fc6715e8f3aa763/access-control/service/src/main/java/io/harness/accesscontrol/commons/version/VersionInfoResource.java#L2)):*
> ```Java
> /*
>  * Copyright 2022 Harness Inc. All rights reserved.
> ```

Thanks for adding copyright info but I think it is better to have it as part of another PR and not mix with functional change as it may be difficult to track.


<!-- Sent from Reviewable.io -->

2022-10-07 14:00 UTC, reetika04 approved these changes
> Reviewed 3 of 21 files at r1, 77 of 78 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-07 14:05 UTC, AbhijithHarness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38263)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-07 16:33 UTC, shivamnegi94 commented
trigger ti3, ti4

2022-10-09 07:27 UTC, merged