Feat: [SRM-12273]: Create entities needed for Composite SLO Calculations
harness/harness-core pull request #38341
Opened 2022-10-04 11:20 UTC by Varsha-lalwani

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-04 11:23 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38341)

2022-10-04 12:10 UTC, Varsha-lalwani commented
trigger ti3

2022-10-12 10:02 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: Some of the checks are too old. 22 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAUYED7TnktcN1KDRM:-NEAUYED7TnktcN1KDRN:b-e23n87) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L53)):*
> ```Java
>   @Valid List<ServiceLevelIndicatorDTO> serviceLevelIndicators;
>   @Valid List<ServiceLevelObjectiveDetailsDTO> serviceLevelObjectivesDetails;
>   @Valid int sloVersion;
> ```

We don't need slo version to be sent from frontend. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/CompositeSLORecordService.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAVi0J9DpRAQnzBBqa:-NEAVi0J9DpRAQnzBBqb:b-kqex1p) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/CompositeSLORecordService.java#L22)):*
> ```Java
> 
> public interface CompositeSLORecordService {
>   void create(Map<ServiceLevelObjectivesDetail, List<SLIRecord>> serviceLevelObjectivesDetailSLIRecordMap,
> ```

Why we have serviceLevelObjectivesDetail as the key? We should just have the slo identifier as the key.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAYBm7CpjGVsGguXsX:-NEAYBm7CpjGVsGguXsY:b-hgza9g) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java#L186)):*
> ```Java
>     if (serviceLevelObjective.getType().equals(ServiceLevelObjectiveType.SIMPLE)) {
>       monitoredServiceIdentifier =
>           ((SimpleServiceLevelObjective) serviceLevelObjective).getMonitoredServiceIdentifier();
> ```

Lets just create a abstract Optional<String> getMonitoredServiceIdentifier() method ins abstract SLO.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java` line 223 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEA_wUq-Bmn1httimXb:-NEA_wUq-Bmn1httimXc:b-bflf91) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java#L223)):*
> ```Java
>     TimePeriod timePeriod = serviceLevelObjective.getCurrentTimeRange(currentLocalDate);
>     Instant currentTimeMinute = DateTimeUtils.roundDownTo1MinBoundary(clock.instant());
>     if (serviceLevelObjective.getType().equals(ServiceLevelObjectiveType.COMPOSITE)) {
> ```

We should create a recordService. which has SLORecordService and SLIRecordService impl. And then we can get service impl based on the SLO type. Lets avoid if else block
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAaWKn9iHK4oWe2vA-:-NEAaWKn9iHK4oWe2vA0:bh7p48y) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java#L53)):*
> ```Java
>                 .collect(Collectors.toList()))
>         .sloTargetPercentage(serviceLevelObjectiveV2DTO.getSloTarget().getSloTargetPercentage())
>         .version(serviceLevelObjectiveV2DTO.getSloVersion())
> ```

we don't need slo version from UI/Dto. we will increment it in case there is change in the configured SLOs. Karan will take this up in update API.


<!-- Sent from Reviewable.io -->

2022-10-12 11:21 UTC, Varsha-lalwani reviewed
> Reviewed 1 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: Some of the checks are too old. 22 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAUYED7TnktcN1KDRM:-NEAv3ij9mf-7xH6aRk5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L53)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We don't need slo version to be sent from frontend. 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/CompositeSLORecordService.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAVi0J9DpRAQnzBBqa:-NEAv5VR7pg-cF2JHKkl:brj6k8t) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/CompositeSLORecordService.java#L22)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Why we have serviceLevelObjectivesDetail as the key? We should just have the slo identifier as the key.
</blockquote></details>

Since we need the weightage as well in calculation
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAYBm7CpjGVsGguXsX:-NEAvAt_4sarkNV4fiTJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java#L186)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Lets just create a abstract Optional<String> getMonitoredServiceIdentifier() method ins abstract SLO.
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java` line 223 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEA_wUq-Bmn1httimXb:-NEAvBdj6UxEH2XRgz8X:b-u8d3gd) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOHealthIndicatorServiceImpl.java#L223)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We should create a recordService. which has SLORecordService and SLIRecordService impl. And then we can get service impl based on the SLO type. Lets avoid if else block
</blockquote></details>

Both of these methods take different args
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/38341#-NEAaWKn9iHK4oWe2vA-:-NEAvGKcEQnmOtGb1tzX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f7c73c4609e6f4caf0a653448b27e01d21629bcc/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java#L53)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

we don't need slo version from UI/Dto. we will increment it in case there is change in the configured SLOs. Karan will take this up in update API.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-12 12:29 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: 24 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 174 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB8WvD7fNE177hy-Ju:-NEB8WvG0UYskISll91E:b-yahqpb) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L174)):*
> ```Java
>     Map<Instant, Double> timeStampToBadCount = new HashMap<>();
>     Map<Instant, Integer> timeStampToTotalCount = new HashMap<>();
>     for (ServiceLevelObjectivesDetail objectivesDetail : serviceLevelObjectivesDetailCompositeSLORecordMap.keySet()) {
> ```

Let's move it to separate method.



_Code quote:_
```Java
    for (ServiceLevelObjectivesDetail objectivesDetail : serviceLevelObjectivesDetailCompositeSLORecordMap.keySet()) {
      for (SLIRecord sliRecord : serviceLevelObjectivesDetailCompositeSLORecordMap.get(objectivesDetail)) {
        if (SLIRecord.SLIState.GOOD.equals(sliRecord.getSliState())
            || (SLIRecord.SLIState.NO_DATA.equals(sliRecord.getSliState())
                && objectivesDetailSLIMissingDataTypeMap.get(objectivesDetail).equals(SLIMissingDataType.GOOD))) {
          double goodCount = timeStampToGoodCount.getOrDefault(sliRecord.getTimestamp(), 0.0);
          goodCount += objectivesDetail.getWeightagePercentage() / 100;
          timeStampToGoodCount.put(sliRecord.getTimestamp(), goodCount);
        } else {
          double badCount = timeStampToBadCount.getOrDefault(sliRecord.getTimestamp(), 0.0);
          badCount += objectivesDetail.getWeightagePercentage() / 100;
          timeStampToBadCount.put(sliRecord.getTimestamp(), badCount);
        }
        timeStampToTotalCount.put(
            sliRecord.getTimestamp(), timeStampToTotalCount.getOrDefault(sliRecord.getTimestamp(), 0) + 1);
      }
    }
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB-mYz7dwkdd1rmeIc:-NEB-mYz7dwkdd1rmeId:b2nhnu9) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L219)):*
> ```Java
>     Map<Instant, CompositeSLORecord> sloRecordMap =
>         toBeUpdatedSLORecords.stream().collect(Collectors.toMap(CompositeSLORecord::getTimestamp, Function.identity()));
>     List<CompositeSLORecord> updateOrCreateSLIRecords = new ArrayList<>();
> ```

SLO
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 231 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB3AvL1BDJ_vp1vTlH:-NEB3AvL1BDJ_vp1vTlI:bsv14gx) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L231)):*
> ```Java
>           goodCount += objectivesDetail.getWeightagePercentage() / 100;
>           timeStampToGoodCount.put(sliRecord.getTimestamp(), goodCount);
>         } else {
> ```

else if(BAD || NO_DATA with bad preference).
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 240 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB3_4M4SHLo0BJTFrI:-NEB3_4M4SHLo0BJTFrJ:b6oi1mv) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L240)):*
> ```Java
>       }
>     }
>     for (Instant instant : timeStampToTotalCount.keySet()) {
> ```

Find the min and max of the timestamptototalcount and iterate over that time. or use a TreeMap instead of HashMap



_Code quote:_
```Java
(Instant instant : timeStampToTotalCount.keySet()) 
```


<!-- Sent from Reviewable.io -->

2022-10-12 12:52 UTC, Varsha-lalwani reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: 24 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 174 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB8WvD7fNE177hy-Ju:-NEBDAf06F_0byIzltca:baarv6c) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L174)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Let's move it to separate method.
</blockquote></details>

not moving it since we need 3 maps as a return
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB-mYz7dwkdd1rmeIc:-NEBDMLqBUAVIiWIvMCH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L219)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

SLO
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 231 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB3AvL1BDJ_vp1vTlH:-NEBDpQ24Z2ECrkaZ_F0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L231)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

else if(BAD || NO_DATA with bad preference).
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 240 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB3_4M4SHLo0BJTFrI:-NEBF8YNC0qWJOggEXWr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L240)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Find the min and max of the timestamptototalcount and iterate over that time. or use a TreeMap instead of HashMap
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-13 11:18 UTC, AbhijithHarness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: 24 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOValue.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFaYwP1m2UUTLM0HIp:-NEFaYwP1m2UUTLM0HIq:b7iv1lh) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOValue.java#L19)):*
> ```Java
>   double badCount;
>   double total;
>   public double sloPercentage() {
> ```

nit: on Values, we generally use get,  "getSLOPercentage"
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java` line 75 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFfOmO1l-inhnVunzH:-NEFfOmO1l-inhnVunzI:b-y15f5g) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java#L75)):*
> ```Java
>   @FdIndex private String verificationTaskId;
>   private String sloId;
>   private Instant timestamp; // minute
> ```

nit: if minutes, Its better to name timeStampInMinutes, to avoid confusion
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFjDN8Ebi_Z4ruJViW:-NEFjDN8Ebi_Z4ruJViX:bgx7tnf) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L65)):*
> ```Java
>     CompositeSLORecord latestCompositeSLORecord = getLatestCompositeSLORecord(verificationTaskId);
>     if (Objects.nonNull(lastCompositeSLORecord)) {
>       runningGoodCount = lastCompositeSLORecord.getRunningGoodCount();
> ```

nit: make naming more obvious: runningGoodCountBeforeStartTime



_Code quote:_
```Java
    double runningGoodCount = 0;
    double runningBadCount = 0;
    CompositeSLORecord lastCompositeSLORecord = getLastCompositeSLORecord(verificationTaskId, startTime);
    CompositeSLORecord latestCompositeSLORecord = getLatestCompositeSLORecord(verificationTaskId);
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 214 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFlP_R0rl0HSIwrEPJ:-NEFlP_SD9EJSfXMWiZV:bug5s6f) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L214)):*
> ```Java
>   }
> 
>   @RetryOnException(retryCount = RETRY_COUNT, retryOn = ConcurrentModificationException.class)
> ```

nit: Please confirm that this works even if you call it from within the class, and not just through "guice". (spring had that issue, but by going through guice documentation, it looks like this should work)
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 228 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFohQ58DNBNYZe1kcs:-NEFohQ58DNBNYZe1kct:b-5gnq3e) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L228)):*
> ```Java
>     Map<Instant, Integer> timeStampToTotalCount = new HashMap<>();
>     for (ServiceLevelObjectivesDetail objectivesDetail : serviceLevelObjectivesDetailCompositeSLORecordMap.keySet()) {
>       for (SLIRecord sliRecord : serviceLevelObjectivesDetailCompositeSLORecordMap.get(objectivesDetail)) {
> ```

here we are assuming that we will have SLI records for all the SLIs, for all the minutes? is that assumption accurate? What if our analysis fails, or data collection fails? What happens if 1 SLI data is missing, may be because of delay in data_collection?, for a objectivesDetail?



_Code quote:_
```Java
for (SLIRecord sliRecord : serviceLevelObjectivesDetailCompositeSLORecordMap.get(objectivesDetail))
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 258 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFnj0YEmkZiuf1T0OE:-NEFnj0YEmkZiuf1T0OF:b9h4hkg) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L258)):*
> ```Java
>           sloRecord.setSloVersion(sloVersion);
>         } else {
>           sloRecord = CompositeSLORecord.builder()
> ```

We dont't need total here? What happens if we have missing SLO records in between?



_Code quote:_
```Java
runningGoodCount
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEFqsVXDpmiCw42nBrT:-NEFqsVYDuZ3b5hpzf5r:bfixslm) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L52)):*
> ```Java
>   @Valid ServiceLevelIndicatorType serviceLevelIndicatorType;
>   @Valid List<ServiceLevelIndicatorDTO> serviceLevelIndicators;
>   @Valid List<ServiceLevelObjectiveDetailsDTO> serviceLevelObjectivesDetails;
> ```

nit: We should have used generics for here, as serviceLevelIndicators and serviceLevelObjectivesDetails, can't be there together


<!-- Sent from Reviewable.io -->

2022-10-13 11:37 UTC, Varsha-lalwani reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: 24 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOValue.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFaYwP1m2UUTLM0HIp:-NEG5juD-p2rDH_Ea8Kz:b-8gcgmp) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOValue.java#L19)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: on Values, we generally use get,  "getSLOPercentage"
</blockquote></details>

not doing that now to have similar names in both SLI and SLO 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java` line 75 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFfOmO1l-inhnVunzH:-NEG62J7E0fAeVYD08WQ:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java#L75)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: if minutes, Its better to name timeStampInMinutes, to avoid confusion
</blockquote></details>

same as above
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 214 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFlP_R0rl0HSIwrEPJ:-NEG7eQg9LeJDOvBxFWG:bd6awjw) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L214)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: Please confirm that this works even if you call it from within the class, and not just through "guice". (spring had that issue, but by going through guice documentation, it looks like this should work)
</blockquote></details>

I think it works because we are using the same with SLI records
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 228 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFohQ58DNBNYZe1kcs:-NEG6Abf3AggUuIHJphY:bhs2bkn) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L228)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

here we are assuming that we will have SLI records for all the SLIs, for all the minutes? is that assumption accurate? What if our analysis fails, or data collection fails? What happens if 1 SLI data is missing, may be because of delay in data_collection?, for a objectivesDetail?
</blockquote></details>

No we don't have that assumption, for every SLI record of every serviceLevelObjective we are just calculating the goodCount, badCount and total and adding it to the map, and if the total count map at any instant is not equal to the number of simple SLO's in a composite SLO at any instant, we won't use that instant data.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 258 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFnj0YEmkZiuf1T0OE:-NEG6lNB0NcqUkdhpiNS:b-x1cepb) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L258)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We dont't need total here? What happens if we have missing SLO records in between?
</blockquote></details>

No we don't need total, if we have missing slo records, we don't have that instant record in the data. percentage we are just calculating using this (goodCount * 100.0) / (goodCount + badCount);
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEFqsVXDpmiCw42nBrT:-NEG7X_O2jF0wOO-8kDV:b-diijoj) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L52)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: We should have used generics for here, as serviceLevelIndicators and serviceLevelObjectivesDetails, can't be there together
</blockquote></details>

Karan is working on adding spec for both types of SLO and add that.


<!-- Sent from Reviewable.io -->

2022-10-17 03:31 UTC, deepak-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: Some of the checks are too old. 24 file(s) to review. 1 change requests. 14. unresolved discussions. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 174 at r4](https://reviewable.io/reviews/harness/harness-core/38341#-NEB8WvD7fNE177hy-Ju:-NEYz4ta-lgSyR-CsJqs:bma10fg) ([raw file](https://github.com/harness/harness-core/blob/22ea8c712c4bbe023b231962e78e8f0aa82c336a/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L174)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

not moving it since we need 3 maps as a return
</blockquote></details>

nit: You can pass the map as the input params.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 214 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEFlP_R0rl0HSIwrEPJ:-NEYzD-F9YQU68TM6v6v:b-5oikk3) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L214)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

I think it works because we are using the same with SLI records
</blockquote></details>

nit: It works. we have a test case as well to verify its functionality


<!-- Sent from Reviewable.io -->

2022-10-17 03:49 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: Some of the checks are too old. 24 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 192 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEZ2Pyz2b6A1py7q4CH:-NEZ2Pyz2b6A1py7q4CI:b2w8sjl) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L192)):*
> ```Java
>           timeStampToTotalCount.put(
>               sliRecord.getTimestamp(), timeStampToTotalCount.getOrDefault(sliRecord.getTimestamp(), 0) + 1);
>         }
> ```

In case of else if(NO_DATA and SLIMissingData is NO_DATA) we should increase the timeStampToTotalCount to 1.


<!-- Sent from Reviewable.io -->

2022-10-17 03:52 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: Some of the checks are too old. 24 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 245 at r5](https://reviewable.io/reviews/harness/harness-core/38341#-NEZ3N6x6N9xS9EYpxOJ:-NEZ3N6x6N9xS9EYpxOK:b-e8ybv0) ([raw file](https://github.com/harness/harness-core/blob/f71600402a8cb1beb5ee2fc9aae88c81213776f5/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L245)):*
> In case of else if(NO_DATA and SLIMissingData is NO_DATA) we should increase the timeStampToTotalCount to 1.
Also, lets move this duplicate code to seperate method.


<!-- Sent from Reviewable.io -->

2022-10-17 03:55 UTC, AbhijithHarness submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 6 of 14 files at r2, 5 of 12 files at r3, 9 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-17 07:38 UTC, deepak-harness submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 6 of 14 files at r2, 5 of 12 files at r3, 10 of 10 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-17 09:11 UTC, deepak-harness approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38341)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-17 09:14 UTC, merged