feat: [CDS-44054]: Improve Azure WebApp settings update logic
harness/harness-core pull request #38357
Opened 2022-10-04 12:51 UTC by abosii-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-04 12:53 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 11 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 9 Code issues 
* ![Anti-pattern](https://app.embold.io/assets/images/svg/anti-pattern.svg) 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38357)

2022-10-06 06:09 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppSlotDeploymentStep.java
> +  private void updatStageExecutionDetails(
minor typo here

2022-10-06 06:38 UTC, vlica-harness approved these changes
> Reviewed 15 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38357)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-13 06:43 UTC, tmacari-harness requested changes
> Reviewed 16 of 16 files at r1, 1 of 1 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38357)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 509 at r3](https://reviewable.io/reviews/harness/harness-core/38357#-NE6gCpv0KyFDMW4ZrVh:-NE6gCpv0KyFDMW4ZrVi:bnq3s3i) ([raw file](https://github.com/harness/harness-core/blob/9a93047e83fceae6e0e392bf007c3b5d1c601964/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L509)):*
> ```Java
>       AzureWebAppsStageExecutionDetails executionDetails =
>           (AzureWebAppsStageExecutionDetails) stageExecutionInfoList.get(0).getExecutionDetails();
>       log.info("Last successful deployment's artifact found with pipeline executionId: {}",
> ```

lets change the logging once we use it not only for artifact config


<!-- Sent from Reviewable.io -->

2022-10-13 08:29 UTC, vlica-harness submitted a review, later dismissed

2022-10-17 07:39 UTC, abosii-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38357)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 509 at r3](https://reviewable.io/reviews/harness/harness-core/38357#-NE6gCpv0KyFDMW4ZrVh:-NEZsYIv7is-Dkn_8SSR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9a93047e83fceae6e0e392bf007c3b5d1c601964/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L509)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

lets change the logging once we use it not only for artifact config
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-10-17 07:50 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38357)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-17 08:35 UTC, vlica-harness submitted a review, later dismissed
> Reviewed 14 of 14 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38357)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-19 08:23 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38357)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-19 08:25 UTC, abosii-harness commented
trigger messagecheck

2022-10-19 08:27 UTC, vlica-harness approved these changes

2022-10-19 09:22 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 16 files at r1, 14 of 14 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38357#-:-NEjYKPPCqXL2xHJF_aH:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-19 09:54 UTC, abosii-harness commented
trigger messagecheck, codebasehash

2022-10-19 09:57 UTC, merged