[feat]: [CDS-44268]: AMI Delegate Tasks
harness/harness-core pull request #38367
Opened 2022-10-04 15:39 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-04 15:41 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38367)

2022-10-20 04:05 UTC, shivamnegi94 requested changes

2022-10-20 04:05 UTC, shivamnegi94 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/AMIArtifactOutcome.java
> +
Please add metadata of type Map if required for additional information

2022-10-26 06:25 UTC, shivamnegi94 submitted a review, later dismissed

2022-10-26 11:26 UTC, puthrayaharness requested changes

2022-10-26 11:26 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/ami/AMITagsResponse.java
> +  private Map<String, String> tags;
Please use list for response.

2022-10-26 11:26 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +        && taskResponse.getArtifactTaskExecutionResponse().getArtifactDelegateResponses().size() != 0) {
Can`getArtifactDelegateResponses` be null?

2022-10-26 11:26 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +        && taskResponse.getArtifactTaskExecutionResponse().getArtifactDelegateResponses().size() != 0) {
Can we use EmptyPredicate instead?

2022-10-27 06:38 UTC, vtxorxwitty commented on 970-api-services-beans/src/main/java/io/harness/ami/AMITagsResponse.java
> +  private Map<String, String> tags;
@puthrayaharness We use Map<String, String> in CG API. So replicated the same

2022-10-27 07:02 UTC, vtxorxwitty commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +        && taskResponse.getArtifactTaskExecutionResponse().getArtifactDelegateResponses().size() != 0) {
Done

2022-10-27 20:43 UTC, puthrayaharness requested changes

2022-10-27 20:43 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/ami/AMITagsResponse.java
> +  private Map<String, String> tags;
Please do not return with a map. We should return a list here. If we want to add more fields in the future it is not extendible.

2022-10-27 20:43 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +      log.error("Unhandled aws exception");
Not a useful log line. What value is this log line adding?

2022-10-27 20:43 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +      throw new InvalidRequestException("The IAM role on the Ec2 delegate does not exist OR does not"
Please throw Hint/Explanation exception.

2022-10-27 20:43 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ami/AMIArtifactDelegateResponse.java
> +  String artifactUrl;
What URL is this?

2022-10-28 09:40 UTC, vtxorxwitty commented on 970-api-services-beans/src/main/java/io/harness/ami/AMITagsResponse.java
> +  private Map<String, String> tags;
Okay @puthrayaharness will change the API response to list then.

2022-10-31 09:53 UTC, puthrayaharness requested changes

2022-10-31 09:53 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/io/harness/ami/AMITagsResponse.java
> +  private List<String> tags;
List of objects.

2022-10-31 09:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +    log.info("Retrieving images from Aws");
Add more info the the log. Otherwise this is adding very little value.

2022-10-31 09:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +                                    .limit(AMI_MAX_RESULTS)
Remove the limit

2022-10-31 09:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +    log.info("Sorting on creation time");
Same. Remove the log line.

2022-10-31 09:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +                                    .filter(image -> image != null && isNotBlank(image.getName()))
image != null check is not required.

2022-10-31 09:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +    Collections.reverse(limitedImages);
Remove

2022-10-31 09:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/ami/service/AMIRegistryServiceImpl.java
> +    if (buildDetails.isEmpty()) {
use EmptyPredicate.

2022-10-31 09:53 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +          if (taskResponse.getArtifactTaskExecutionResponse().getArtifactDelegateResponses() != null
Use EmptyPredicate

2022-10-31 09:53 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java
> +      if (tags == null) {
Use emptyPredicate

2022-10-31 09:53 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +        .imagePullSecret(createImagePullSecret(ArtifactUtils.getArtifactKey(amiArtifactConfig)))
We do not need imagePullSecret

2022-10-31 09:53 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/AMIArtifactOutcome.java
> +  String imagePullSecret;
Not required

2022-10-31 09:53 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/ami/AMIArtifactTaskHandler.java
> +    return EmptyPredicate.isNotEmpty(artifactDelegateRequest.getVersionRegex());
StringUtils.

2022-10-31 09:53 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ami/AMIArtifactDelegateRequest.java
> +        new ArrayList<>(EncryptedDataDetailsCapabilityHelper.fetchExecutionCapabilitiesForEncryptedDataDetails(
Can this be same as S3?

2022-11-02 09:49 UTC, vtxorxwitty commented
trigger ti4

2022-11-02 10:37 UTC, vtxorxwitty commented
trigger ti3

2022-11-02 10:37 UTC, vtxorxwitty commented
trigger ti1

2022-11-02 10:39 UTC, vtxorxwitty commented
trigger ti2

2022-11-02 10:57 UTC, puthrayaharness reviewed
> Reviewed 1 of 12 files at r1, 21 of 83 files at r3, 2 of 15 files at r4, 18 of 35 files at r5, 4 of 17 files at r7, 53 of 57 files at r8, 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38367)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-02 10:57 UTC, puthrayaharness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38367)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-02 14:35 UTC, vtxorxwitty commented
trigger ti1

2022-11-02 14:35 UTC, vtxorxwitty commented
trigger ti2

2022-11-02 14:35 UTC, vtxorxwitty commented
trigger ti3

2022-11-02 14:35 UTC, vtxorxwitty commented
trigger ti4

2022-11-03 10:05 UTC, vtxorxwitty commented
trigger ti1

2022-11-03 10:05 UTC, vtxorxwitty commented
trigger ti2

2022-11-03 10:05 UTC, vtxorxwitty commented
trigger ti3

2022-11-03 10:08 UTC, vtxorxwitty commented
trigger ti4

2022-11-03 11:18 UTC, merged