feat: [PL-27160]: onboard disable harness sm setting
harness/harness-core pull request #38506
Opened 2022-10-07 11:57 UTC by tiwaritejas

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-07 12:00 UTC, diptiman-adak commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* ![Vulnerability](https://app.embold.io/assets/images/svg/vulnerability.svg) 1 Vulnerabilities 
 * ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38506)

2022-10-07 12:21 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmO3kXDTmuJ2FUK18E:-NDmO3kXDTmuJ2FUK18F:biu4m3l) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L21)):*
> ```Java
> 
> public class DisableBuiltInHarnessSMValidator implements SettingValidator {
>   @Inject ConnectorResourceClient connectorResourceClient;
> ```

add space after it.


<!-- Sent from Reviewable.io -->

2022-10-07 12:22 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmORBVCddMWAvn52Mw:-NDmORBVCddMWAvn52Mx:b-qpyz49) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L30)):*
> ```Java
>     try {
>       connectorResponseDTOList = connectorResourceClient
>                                      .listConnectors(accountIdentifier, null, null, 0, 10,
> ```

can we use constants here


<!-- Sent from Reviewable.io -->

2022-10-07 12:23 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmOVrl-JuAmvZozdIZ:-NDmOVrl-JuAmvZozdI_:b-aduyg1) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L39)):*
> ```Java
>                                      .getData()
>                                      .getContent();
>     } catch (Exception e) {
> ```

log the exception


<!-- Sent from Reviewable.io -->

2022-10-07 12:23 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmOcAZ5OHCqGO14Tsl:-NDmOcAZ5OHCqGO14Tsm:b-hvwyj6) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L47)):*
> ```Java
>     }
>     if (connectorResponseDTOList.size() == 1
>         && connectorResponseDTOList.get(0).getConnector().getIdentifier().equals(HARNESS_SECRET_MANAGER_IDENTIFIER)) {
> ```

we should try and use reverse condition matching in such cases: eg: Harness_secret_manager_identifier.equals();


<!-- Sent from Reviewable.io -->

2022-10-10 11:14 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38506)* status: 4 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmO3kXDTmuJ2FUK18E:-NE0a4Bf3WJTGPfrIErw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L21)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

add space after it.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmORBVCddMWAvn52Mw:-NE0a9N0BYqYvw1KhKhu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we use constants here
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmOVrl-JuAmvZozdIZ:-NE0aBGN6UnIxd8Tuipw:bbpd4kz) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log the exception
</blockquote></details>

It is already being logged in the parent function
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/38506#-NDmOcAZ5OHCqGO14Tsl:-NE0aW4C9euCIb4kYQ1S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0819e54af686ac4c5f80c238ae75022f9b5636d3/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should try and use reverse condition matching in such cases: eg: Harness_secret_manager_identifier.equals();
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-12 13:16 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38506)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/38506#-NEBCrYw7KXhf4rjhVSa:-NEBJJmsC9fDaulL0Ed0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/036a1cb644049563de405c7adf8624f6bd306f68/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L50)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

IMO this check is not required.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-13 03:49 UTC, meenakshi-harness requested changes

2022-10-13 03:49 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java
> +    if (connectorResponseDTOList.size() < 2) {
should we have a null check as well to be on safe side, in case Harness SM is not present( during account setup or got deleted some how - We have seen this case multiple times)

2022-10-13 05:27 UTC, tiwaritejas commented
trigger ti3

2022-10-13 06:05 UTC, tiwaritejas commented
trigger messagecheck

2022-10-13 06:15 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38506)* status: 4 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/38506#-NDmIdIFxdxHLcmNIlk9-r3-47:-NEEygyJ7C2L8YmbTnH1:b7d15ij) ([raw file](https://github.com/harness/harness-core/blob/f48d08a4e089f5c96afa2b5f0a6b2d3dac0761ea/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L47)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

should we have a null check as well to be on safe side, in case Harness SM is not present( during account setup or got deleted some how - We have seen this case multiple times) 
</blockquote></details>

Even if no SMs are present for the account, empty list is returned instead of null. We can make the setting changes in this case.


<!-- Sent from Reviewable.io -->

2022-10-13 08:57 UTC, nishantsaini20 approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38506)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/38506#-NDmIdIFxdxHLcmNIlk9-r3-47:-NEFYScYDUxuCMKzz8Yc:bq8ks1p) ([raw file](https://github.com/harness/harness-core/blob/084c16d93f47fc48a638d83afb40b721512accd6/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L47)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Even if no SMs are present for the account, empty list is returned instead of null. We can make the setting changes in this case.
</blockquote></details>

We should not allow in case the list is empty.


<!-- Sent from Reviewable.io -->

2022-10-13 09:00 UTC, meenakshi-harness approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38506)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-13 09:02 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38506)* status: 4. unresolved discussions. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/38506#-NDmIdIFxdxHLcmNIlk9-r3-47:-NEF_2QW7kJ0QM8nqGum:b-sfqbmu) ([raw file](https://github.com/harness/harness-core/blob/084c16d93f47fc48a638d83afb40b721512accd6/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/DisableBuiltInHarnessSMValidator.java#L47)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We should not allow in case the list is empty.
</blockquote></details>

Yes, I mean the setting would not change, the message will come up that no SM present other than Harness SM


<!-- Sent from Reviewable.io -->

2022-10-13 09:33 UTC, mohitg0795 approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38506)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-13 09:34 UTC, merged