feat: [CDS-44348]: migrate artifact streams
harness/harness-core pull request #38555
Opened 2022-10-10 06:53 UTC by prabu-kr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/38555)

2022-10-11 15:06 UTC, puthrayaharness requested changes

2022-10-11 15:06 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/artifactstream/ACRArtifactStreamMapper.java
> +        .sourceType(ArtifactSourceType.JENKINS)
Please fix.

2022-10-11 15:06 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/artifactstream/AMIArtifactStreamMapper.java
> +public class AMIArtifactStreamMapper implements ArtifactStreamMapper {
Please do not map AMI yet. This is not supported & it is still in develop

2022-10-12 07:03 UTC, prabu-kr commented on 100-migrator/src/main/java/io/harness/ngmigration/service/artifactstream/AmazonS3ArtifactStreamMapper.java
> +                  .filePath(amazonS3ArtifactStream.getArtifactPaths() != null
Done

2022-10-12 07:28 UTC, AnshuH commented
trigger ti1

2022-10-12 07:32 UTC, prabu-kr commented
trigger messagecheck

2022-10-12 13:41 UTC, puthrayaharness approved these changes

2022-10-12 17:12 UTC, merged