feat: [CDS-41900]: Support for RAW type
harness/harness-core pull request #38645
Opened 2022-10-11 10:38 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-13 08:29 UTC, puthrayaharness requested changes

2022-10-13 08:29 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/response/ArtifactTaskExecutionResponse.java
> +  Map<String, String> repositories;
Please make this a list of an Object.

2022-10-13 08:29 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java
> +  public List<BuildDetailsInternal> getPackageNamesBuildDetails(
Can we please reuse the code rather than duplicate the code?

2022-10-13 08:29 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java
> +      switch (nexusRegistryArtifactConfig.getRepositoryFormat().getValue()) {
Please move this logic to Service layer. Let's not have this as part of resource layer.

2022-10-19 11:19 UTC, shivamnegi94 commented on 960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java
> +  public List<BuildDetailsInternal> getPackageNamesBuildDetails(
We have to move the 930-delegate-task module in that case

2022-10-20 10:29 UTC, shivamnegi94 commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/nexus/NexusArtifactResource.java
> +      switch (nexusRegistryArtifactConfig.getRepositoryFormat().getValue()) {
To move this code to service layer, we need to move the `ArtifactResourceUtils` to lower module.

2022-10-21 07:00 UTC, puthrayaharness requested changes

2022-10-21 07:00 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/docker/DockerCapabilityHelper.java
> +    if ((!DockerRegistryProviderType.HARBOR.equals(dockerConnectorDTO.getProviderType()))
These changes should not be part of this PR?

2022-10-21 07:00 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/docker/service/DockerRegistryServiceImpl.java
> +    if ((!DockerRegistryProviderType.HARBOR.equals(dockerConfig.getProviderType()))
Not part of this PR?

2022-10-21 07:00 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java
> +  public List<BuildDetailsInternal> getPackageNamesBuildDetails(
Is there any reason we cannot move the code?

2022-10-21 07:00 UTC, puthrayaharness commented on 970-api-services-beans/src/main/java/software/wings/helpers/ext/nexus/NexusRepositories.java
> +  private Map<String, String> repositories;
Please use list rather than map.

2022-10-27 07:39 UTC, shivamnegi94 commented on 960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java
> +  public List<BuildDetailsInternal> getPackageNamesBuildDetails(
NexusThreeServiceImpl class is being used in CG and other classes also had dependencies on it so we have to move lot of other classes as well.

2022-10-28 05:13 UTC, puthrayaharness approved these changes

2022-10-28 05:16 UTC, archit-harness submitted a review, later dismissed
> Reviewed 2 of 21 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38645)* status: 35 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 06:28 UTC, shivamnegi94 commented
trigger messagecheck

2022-10-28 09:25 UTC, shivamnegi94 commented
trigger ti0, ti1, ti2, ti3, ti4

2022-10-28 11:39 UTC, archit-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38645)* status: 38 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 11:40 UTC, shivamnegi94 commented
trigger codebasehash

2022-10-28 12:00 UTC, puthrayaharness approved these changes

2022-10-28 12:20 UTC, merged