[feat]: [CDS-43717]: azure sdk upgrade - code changes
harness/harness-core pull request #38691
Opened 2022-10-11 21:32 UTC by markoharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-11 21:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=38691) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=38691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=38691) it.</sub>

2022-10-19 15:17 UTC, markoharness commented
trigger feature-build

2022-10-19 15:18 UTC, markoharness commented
trigger publish-delegate

2022-10-19 18:34 UTC, ivan-83 requested changes
> Reviewed 112 of 118 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/helpers/ext/azure/AzureHelperServiceTest.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NEl7HEA7mw8l2M3jf1l:-NEl7HEA7mw8l2M3jf1m:bxbnnoc) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/400-rest/src/test/java/software/wings/helpers/ext/azure/AzureHelperServiceTest.java#L153)):*
> ```Java
>   @InjectMocks private AzureDelegateHelperService azureDelegateHelperService;
> 
>   //  @Test()
> ```

We cam remove this or rewrite the unit test.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/AzureExceptionHandler.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NEl7g8K7sWkhYBJId1J:-NEl7g8K7sWkhYBJId1K:bojmc54) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/AzureExceptionHandler.java#L40)):*
> ```Java
>           new InvalidRequestException(ex.getMessage(), AZURE_AUTHENTICATION_ERROR, USER));
>     } else {
>       return hintWithExplanationException(HintException.HINT_AZURE_AUTHENTICATION_ISSUE,
> ```

Should we have more generic exception hints here instead of an authentication issue/error? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElAk1l3cxaLIC_Tt3c:-NElAk1l3cxaLIC_Tt3d:b-h2njy) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L107)):*
> ```Java
>           })
>           .doOnSuccess(
>               response -> result.set(Mono.just(response.getStatusCode() >= 200 && response.getStatusCode() < 300)))
> ```

Should we get NPE here? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElAtSc3I3sXSw9aHpL:-NElAtSc3I3sXSw9aHpM:b1grdp5) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L113)):*
> ```Java
>         sleep(ofSeconds(statusCheckIntervalInSeconds));
> 
>         //        if (slotStatusVerifier.operationFailed()) {
> ```

Pls, remove these comments. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/verifier/SlotStatusVerifier.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElCtnGBnk61HUMa_Fc:-NElCtnGBnk61HUMa_Fd:bkvuv60) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/verifier/SlotStatusVerifier.java#L76)):*
> ```Java
>   }
> 
>   //  public boolean operationFailed() {
> ```

Remove commented code.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java` line 167 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElG6AM8fj10WxNg7U_:-NElG6AM8fj10WxNg7Ua:bkvuv60) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMDeploymentService.java#L167)):*
> ```Java
>         azureManagementClient.deployAtSubscriptionScope(azureConfig, subscriptionId, azureARMTemplate);
>     logCallback.saveExecutionLog("ARM Deployment request send successfully", LogLevel.INFO, SUCCESS);
>     //    return performSteadyStateCheckSubscriptionScope(context);
> ```

Remove commented code.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureBlueprintDeploymentService.java` line 287 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElGbXx4jGBPFgUee37:-NElGbXx4jGBPFgUee38:bhtlgr6) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureBlueprintDeploymentService.java#L287)):*
> ```Java
> 
>       } catch (AzureException ex) {
>         if (ex instanceof ResourceExistsException) {
> ```

This needs to be properly tested.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIF84BAfy09DqXxCV:-NElIF84BAfy09DqXxCW:bpvm6cm) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L85)):*
> ```Java
>     AzureWebClient azureWebClient = mock(AzureWebClient.class);
>     AzureMonitorClient azureMonitorClient = mock(AzureMonitorClient.class);
>     //    AzureServiceCallBack restCallBack = new AzureServiceCallBack(mockLogCallback, SLOT_SWAP);
> ```

Remove commented code
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIIqc9DsUGycfckWb:-NElIIqc9DsUGycfckWc:bpvm6cm) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L154)):*
> ```Java
>     AzureWebClient azureWebClient = mock(AzureWebClient.class);
>     AzureMonitorClient azureMonitorClient = mock(AzureMonitorClient.class);
>     //    AzureServiceCallBack restCallBack = new AzureServiceCallBack(mockLogCallback, SLOT_SWAP);
> ```

Remove commented code
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIJiPDnz5Pj_t-K9B:-NElIJiPDnz5Pj_t-K9C:bpvm6cm) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L166)):*
> ```Java
>     doReturn(STOPPED.name()).when(deploymentSlot).state();
> 
>     //    ExecutorService executorService = Executors.newFixedThreadPool(1);
> ```

Remove commented code
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIL7G9AL8jfelQQGz:-NElIL7G9AL8jfelQQH-:bpvm6cm) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L183)):*
> ```Java
>     AzureWebClient azureWebClient = mock(AzureWebClient.class);
>     AzureMonitorClient azureMonitorClient = mock(AzureMonitorClient.class);
>     //    AzureServiceCallBack restCallBack = new AzureServiceCallBack(mockLogCallback, SLOT_SWAP);
> ```

Remove commented code
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIKU7CU6wKHazNyJZ:-NElIKU7CU6wKHazNyJ_:bpvm6cm) ([raw file](https://github.com/harness/harness-core/blob/36 [...]

2022-10-20 21:09 UTC, ivan-83 reviewed
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/38691#-NErCk9UE0PiPBk7jJER:-NErCk9UE0PiPBk7jJES:bdl8fez) ([raw file](https://github.com/harness/harness-core/blob/ebe2c487edf17e6f0491de3684dc099e330b918c/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L56)):*
> ```Java
>       "One or more of Client Id, Subscription, Tenant ID and Secret key is/are invalid.";
>   public static String INVALID_PARAMETER = "The credentials provided are incorrect.";
>   public static String AZURE_INVALID = "There was a problem with Azure.";
> ```

Minor - There was an issue with Azure.     


<!-- Sent from Reviewable.io -->

2022-10-21 16:09 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElAk1l3cxaLIC_Tt3c:-NEvIbwJ1fgpQBMyg6QL:b-1dcph8) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L107)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we get NPE here? 
</blockquote></details>

Corrected


<!-- Sent from Reviewable.io -->

2022-10-21 16:10 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElJrkB75hTzuxSGRve:-NEvIqETACX0e5hcoJyy:b-hft9kg) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L89)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What is HttpPipeline? 
</blockquote></details>

Its an Azure construct


<!-- Sent from Reviewable.io -->

2022-10-21 16:11 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/client/AzureWebClient.java` line 290 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElKeo872vN8T8on-Vl:-NEvIz3u7PzF10io0-sE:bmpc0uz) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/client/AzureWebClient.java#L290)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, why do we return Flux<ByteBuffer>?
</blockquote></details>

That is what Azure SDK API is returning.


<!-- Sent from Reviewable.io -->

2022-10-21 16:11 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImpl.java` line 304 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElLJTjAnH6GHB0Miep:-NEvJ5la1GttvweeJr5-:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImpl.java#L304)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to  AzureClient.
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:11 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImpl.java` line 308 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElLMxQEkNGlzDGELrP:-NEvJ9kGAOQHx91PM7Fr:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImpl.java#L308)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to  AzureClient.
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:12 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java` line 724 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElN8JT4jqzUBT8GNzS:-NEvJBd48KI53VDWeYAY:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java#L724)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I suggest moving to AzureClient.
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:12 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java` line 728 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElNETGAfkWJSPfzcWz:-NEvJDJ5519L1AJMT-Jp:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureComputeClientImpl.java#L728)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I suggest moving to AzureClient.
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:13 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java` line 637 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElOQ3o5KKgdLIN6P9T:-NEvJGOm9Zz8a_MK4yCf:be0rygg) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java#L637)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We need to call map() method to map Mono to PagedResponseBase, right?  How it is after map() method again map to Mono<PagedResponse<TagDetails>>, because FluxUtil does magic or... ?
</blockquote></details>

Magic is done by FluxUtil and PagedFlux and PagedResponse constructs.
This is the same way Azure SDK is written.


<!-- Sent from Reviewable.io -->

2022-10-21 16:13 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java` line 682 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElNm1W2WRKVYtrk4MB:-NEvJRmWEPFHBZm_OIWh:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java#L682)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I suggest moving to AzureClient.
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:13 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java` line 686 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElNgDDBZcqyRyfvPsY:-NEvJTRW1JS7oP20vxHL:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureManagementClientImpl.java#L686)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I suggest moving to AzureClient.
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:13 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 1046 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElUMoF18HIWCl15EBu:-NEvJVi10eROu22pjfnO:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L1046)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to AzureClient
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:13 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 1050 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElURjj-h9-Vr7yfrfU:-NEvJXFY-j_16aPKt9Kb:b-gbb73r) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L1050)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to AzureClient
</blockquote></details>

Agreed not to move it.


<!-- Sent from Reviewable.io -->

2022-10-21 16:13 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 222 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElRp8O0mRU55peSNCt:-NEvJZHtBhiNpZOZoCtu:b-1dcph8) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L222)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we need a list of 10 items or only 1? Or move this list below nonProxyHosts and create with the same size.
</blockquote></details>

Corrected


<!-- Sent from Reviewable.io -->

2022-10-21 16:26 UTC, ivan-83 requested changes
> Reviewed 14 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 310 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIMR0-2daTbIr7qx_:-NEvKpOo721qmmpkMmNs:bpvm6cm) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L310)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Remove commented code
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 110 at r4](https://reviewable.io/reviews/harness/harness-core/38691#-NEvLRjKEaARtHOcMpoo:-NEvLRjKEaARtHOcMpop:b-5svcp) ([raw file](https://github.com/harness/harness-core/blob/cec6974c691ab094292a227d420da02ff0488e99/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L110)):*
> ```Java
> 
>       if (isBlank(subscriptionId)) {
>         Subscription subscription = authenticated.subscriptions().list().stream().findFirst().get();
> ```

Check whether authenticated supports some other method like without subscription or.. The reason why I am asking is, ARM deployments on the Management Group level and Tenant level don't include subscriptions and probably we will be getting NPE  here >>> authenticated.subscriptions().list().stream().findFirst().get(); 


<!-- Sent from Reviewable.io -->

2022-10-24 07:38 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 110 at r4](https://reviewable.io/reviews/harness/harness-core/38691#-NEvLRjKEaARtHOcMpoo:-NF7usXX1ewdBrsvOGwO:b-tdd9nx) ([raw file](https://github.com/harness/harness-core/blob/cec6974c691ab094292a227d420da02ff0488e99/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L110)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Check whether authenticated supports some other method like without subscription or.. The reason why I am asking is, ARM deployments on the Management Group level and Tenant level don't include subscriptions and probably we will be getting NPE  here >>> authenticated.subscriptions().list().stream().findFirst().get(); 
</blockquote></details>

I does, but it fails when there is more than one subscription for same tenant (as it does not know which one to use). So i checked how old Azure SDK used to work and implemented the same logic.


<!-- Sent from Reviewable.io -->

2022-10-24 13:30 UTC, markoharness commented
trigger publish-delegate

2022-10-25 13:34 UTC, markoharness commented
trigger feature-build

2022-10-29 07:40 UTC, markoharness commented
trigger feature-build

2022-10-29 12:41 UTC, markoharness commented
trigger feature-build

2022-10-31 08:44 UTC, markoharness commented
trigger feature-build

2022-10-31 23:54 UTC, markoharness commented
trigger feature-build

2022-11-02 20:59 UTC, markoharness commented
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIF84BAfy09DqXxCV:-NFu87X88kS-gqkcknNd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L85)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 21:00 UTC, markoharness commented
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIIqc9DsUGycfckWb:-NFu8AI7AREILYu6OqgI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L154)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 21:00 UTC, markoharness commented
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIL7G9AL8jfelQQGz:-NFu8Dog3Fl54xH26kDR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L183)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 21:00 UTC, markoharness commented
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElIKU7CU6wKHazNyJZ:-NFu8FP75hrTyFqlobC8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/930-delegate-tasks/src/test/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateCheckerTest.java#L215)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 21:00 UTC, markoharness commented
*[`960-api-services/src/test/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImplTest.java` line 217 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElSVgr3CmoLbc-2bDp:-NFu8MU_9YQnuZtcYiRZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/test/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImplTest.java#L217)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 21:01 UTC, markoharness commented
*[`960-api-services/src/test/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImplTest.java` line 203 at r2](https://reviewable.io/reviews/harness/harness-core/38691#-NElSS_78v2x8C61PaOs:-NFu8bxt2n5-B0OuWfP_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/36359f2996b75a29a843b87d061cd8aae9200bfd/960-api-services/src/test/java/io/harness/azure/impl/AzureAutoScaleSettingsClientImplTest.java#L203)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-03 07:56 UTC, markoharness commented
trigger compile,ti0,ti1,ti2,ti3,ti4

2022-11-03 08:24 UTC, markoharness commented
trigger feature-build

2022-11-03 19:15 UTC, markoharness commented
trigger feature-build

2022-11-04 09:46 UTC, markoharness commented
trigger feature-build

2022-11-06 22:46 UTC, ivan-83 requested changes
> Reviewed 3 of 21 files at r5, 4 of 32 files at r7, 6 of 24 files at r9, 4 of 24 files at r10, 1 of 7 files at r11, 2 of 15 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691)* status: 64 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java` line 84 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE4Z_G8yeoDH0EmyqY:-NGE4Z_H8niE_0DEWEbn:b-6ls95z) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java#L84)):*
> ```Java
>   private PerpetualTaskResponse executeTask(
>       PerpetualTaskId taskId, AzureSshInstanceSyncPerpetualTaskParamsNg taskParams) throws IOException {
>     String workingDir = AzureUtils.createWorkingDir();
> ```

Question -  what is the purpose of working dir? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java` line 95 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE5yKiC-l_hu96ExUm:-NGE5yKiC-l_hu96ExUn:bgbo8qu) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java#L95)):*
> ```Java
>             AzureClientKeyCertDTO cert = (AzureClientKeyCertDTO) azureManualDetailsDTO.getAuthDTO().getCredentials();
>             byte[] certInBytes = String.valueOf(cert.getClientCertRef().getDecryptedValue()).getBytes();
>             String certFilePath = format("%s%s.pem", workingDir, DEFAULT_CERT_FILE_NAME);
> ```

Can we here create and remove workingDir not to pass as a method argument.


<!-- Sent from Reviewable.io -->

2022-11-07 09:06 UTC, markoharness commented
*[`260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java` line 84 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE4Z_G8yeoDH0EmyqY:-NGGKORO4U7LdQh1UklC:bvmscrz) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java#L84)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Question -  what is the purpose of working dir? 
</blockquote></details>

We need it for creating/saving a certificate file (from connector). Then when creating a credentials(authenticating with SP with certificate) we pass the path to the certificate file.


<!-- Sent from Reviewable.io -->

2022-11-07 09:08 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java` line 95 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE5yKiC-l_hu96ExUm:-NGGKsWLCEmDY_atKvrR:b8ki71s) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java#L95)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we here create and remove workingDir not to pass as a method argument.
</blockquote></details>

No, because the actual file is being used later in the code so we need the dir and the file to exist.


<!-- Sent from Reviewable.io -->

2022-11-07 16:00 UTC, markoharness commented
trigger feature-build

2022-11-08 20:39 UTC, ivan-83 requested changes
> Reviewed 4 of 21 files at r5, 20 of 32 files at r7, 11 of 24 files at r9, 11 of 24 files at r10, 5 of 7 files at r11, 11 of 15 files at r12, 5 of 8 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java` line 84 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE4Z_G8yeoDH0EmyqY:-NGNsETk3UA-DNlYfnly:bcr8sgp) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java#L84)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

We need it for creating/saving a certificate file (from connector). Then when creating a credentials(authenticating with SP with certificate) we pass the path to the certificate file.
</blockquote></details>

Can we use some constant as the working directory path and here call only AzureUtils.createWorkingDir() and not propagate it to the underlying method?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java` line 95 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE5yKiC-l_hu96ExUm:-NGNqT3nDubgUzipnQAx:b-z95ln) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java#L95)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

No, because the actual file is being used later in the code so we need the dir and the file to exist.
</blockquote></details>

I see we need to pass the working dir(certificate path) to toAzureInternalConfig method for all auth credentials-type cases which are not good.
I suggest a hardcoded path for working dir and throw an exception if the certificate is not presented for the KEY_CERT case if it is doable. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 108 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNm66k4xgq9RSzj-cv:-NGNm66k4xgq9RSzj-cw:b-qimevp) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L108)):*
> ```Java
>                 result.set(Boolean.TRUE);
>               } else {
>                 String errorMsg = "Task has failed";
> ```

Minor - we need more details in the error message, like response status and code and response msg if exists.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 116 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNn8j47xVW9tBdPL5h:-NGNn8j47xVW9tBdPL5i:b-r5pfo1) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L116)):*
> ```Java
>             .block(Duration.ofMinutes(steadyCheckTimeoutInMinutes));
>       } else {
>         // checking slot deployment status
> ```

qq, I see this is the old behavior where we are pooling for status. 

In which cases mono is different than null?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 78 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNonKe1q6iMstelFQp:-NGNonKf7SRjuJ9mR45I:b4revdz) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L78)):*
> ```Java
>       AzureManagementClient azureManagementClient, LogCallback logCallback,
>       SyncPoller<SyncPollerResult, ResponseObject> syncPoller) {
>     if (syncPoller == null) {
> ```

qq, the same here when syncPoller is null old behavior. In which cases syncPoller is different than null?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java` line 70 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNuJK0A-zJv73I9q2_:-NGNuJK0A-zJv73I9q2a:b-hdsqsu) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java#L70)):*
> ```Java
>     AzureTaskParams azureTaskParams = (AzureTaskParams) parameters;
> 
>     String workingDir = AzureUtils.createWorkingDir();
> ```

Pls, try to avoid working dir. It is only needed for connectors if I understand correctly. 
You can create auto closeable working dir,  AutoCloseableWorkingDirectory.
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 300 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvXWP0rj--pxuIZHD:-NGNvXWP0rj--pxuIZHE:blvg4my) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L300)):*
> ```Java
>   }
> 
>   public <T extends ContinuablePage, B> Mono<PagedResponse<B>> executePagedRequest(
> ```

Move to new class AzureClientUtils
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 329 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvayc9CQmI9RmqYvK:-NGNvayc9CQmI9RmqYvL:blvg4my) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L329)):*
> ```Java
>   }
> 
>   public <T> Mono<T> getMonoRequest(Mono<Response<T>> request, Class<T> responseType) {
> ```

Move to new class AzureClientUtils
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 334 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvcqDDSe_tyITzMr6:-NGNvcqDDSe_tyITzMr7:blvg4my) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L334)):*
> ```Java
>   }
> 
>   public <T> Mono<T> getMonoResponse(Response<T> response, Class<T> responseType) {
> ```

Move to new class AzureClientUtils
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 344 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvbjY5QbCLC04h67O:-NGNvbjY5QbCLC04h67P:blvg4my) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L344)):*
> ```Java
>   }
> 
>   private <T> T processResponse(Response<T> response, Class<T> responseType) {
> ```

Move to new class AzureClientUtils
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 354 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvdeh6B-siYqyX2ZL:-NGNvdeh6B-siYqyX2ZM:blvg4my) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L354)):*
> ```Java
>   }
> 
>   private void validateResponse(Response response) {
> ```

Move to new class AzureClientUtils
___
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 360 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvfCMDUk6RQu-NEHi:-NGNvfCN3Fe182ZU15rX:blvg4my) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harn [...]

2022-11-08 20:49 UTC, markoharness commented
*[`960-api-services/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker` line 1 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNxbHx575hQow7Dyfm:-NGO-8xI6SqnAg-JmY_4:b-85joi) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker#L1)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, what is mock-marker-inline?
</blockquote></details>

Its a mockito configuration which allows us to mock final classes.


<!-- Sent from Reviewable.io -->

2022-11-09 08:20 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 108 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNm66k4xgq9RSzj-cv:-NGQTCvBAbAKMTbj9m6T:b-4lup4u) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L108)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - we need more details in the error message, like response status and code and response msg if exists.
</blockquote></details>

We have only the response code here so I can add that to the error message. Nothing else.


<!-- Sent from Reviewable.io -->

2022-11-09 08:23 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 116 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNn8j47xVW9tBdPL5h:-NGQTm5g87Xb77FgeZ7L:b-7vg92m) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L116)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, I see this is the old behavior where we are pooling for status. 

In which cases mono is different than null?
</blockquote></details>

It depends on the Azure SDK call. In some cases we get the Mono response which we can use here, in others we don't have it (void) and we can not use it. I prefer not to list all cases.


<!-- Sent from Reviewable.io -->

2022-11-09 08:29 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java` line 78 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNonKe1q6iMstelFQp:-NGQV7zo1VYiwrcia1wq:bkvdv6s) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/ARMDeploymentSteadyStateChecker.java#L78)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, the same here when syncPoller is null old behavior. In which cases syncPoller is different than null?
</blockquote></details>

In this case you are right, we will not have a situation where syncPoller will be null. I will remove it from code.


<!-- Sent from Reviewable.io -->

2022-11-10 13:59 UTC, markoharness commented
*[`260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java` line 84 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE4Z_G8yeoDH0EmyqY:-NGWpS505ot7SFe6-9tG:b-pn6rhr) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/260-delegate/src/main/java/io/harness/perpetualtask/AzureSshWinrmInstanceSyncPerpetualTaskExecutor.java#L84)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we use some constant as the working directory path and here call only AzureUtils.createWorkingDir() and not propagate it to the underlying method?
</blockquote></details>

Implemented auto closeable dir


<!-- Sent from Reviewable.io -->

2022-11-10 14:00 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java` line 95 at r13](https://reviewable.io/reviews/harness/harness-core/38691#-NGE5yKiC-l_hu96ExUm:-NGWpleC3CKpFXVZiKa0:biv3sh6) ([raw file](https://github.com/harness/harness-core/blob/638754cc40c5a6b07d285ca90943c9abae56bc67/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/AcrRequestResponseMapper.java#L95)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I see we need to pass the working dir(certificate path) to toAzureInternalConfig method for all auth credentials-type cases which are not good.
I suggest a hardcoded path for working dir and throw an exception if the certificate is not presented for the KEY_CERT case if it is doable. 
</blockquote></details>

Implemented auto closeable dir which will be created only in case of KEY_CERT connector


<!-- Sent from Reviewable.io -->

2022-11-10 14:00 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java` line 108 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNm66k4xgq9RSzj-cv:-NGWpuLk1jtuxvjydd54:b-jt0a24) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/SlotSteadyStateChecker.java#L108)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

We have only the response code here so I can add that to the error message. Nothing else.
</blockquote></details>

added status code to error message


<!-- Sent from Reviewable.io -->

2022-11-10 14:01 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java` line 70 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNuJK0A-zJv73I9q2_:-NGWq1Pw3ddXQcWf7ni_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/AzureTask.java#L70)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls, try to avoid working dir. It is only needed for connectors if I understand correctly. 
You can create auto closeable working dir,  AutoCloseableWorkingDirectory.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-10 14:01 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 300 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvXWP0rj--pxuIZHD:-NGWq3U97h4ECyTjoDhA:b-kx6ju0) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L300)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to new class AzureClientUtils
</blockquote></details>

Moved to new AzureClientBase


<!-- Sent from Reviewable.io -->

2022-11-10 14:01 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 329 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvayc9CQmI9RmqYvK:-NGWq8XA5HOkfm84SybE:b-kx6ju0) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L329)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to new class AzureClientUtils
</blockquote></details>

Moved to new AzureClientBase


<!-- Sent from Reviewable.io -->

2022-11-10 14:01 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 334 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvcqDDSe_tyITzMr6:-NGWq9y81YVS5PamMC0H:b-kx6ju0) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L334)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to new class AzureClientUtils
</blockquote></details>

Moved to new AzureClientBase


<!-- Sent from Reviewable.io -->

2022-11-10 14:01 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 344 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvbjY5QbCLC04h67O:-NGWqBV28GOhcQhFhZhi:b-kx6ju0) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L344)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to new class AzureClientUtils
</blockquote></details>

Moved to new AzureClientBase


<!-- Sent from Reviewable.io -->

2022-11-10 14:02 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 360 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvfCMDUk6RQu-NEHi:-NGWqDla7yOPH3jkqxib:b-kx6ju0) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L360)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to new class AzureClientUtils
</blockquote></details>

Moved to new AzureClientBase


<!-- Sent from Reviewable.io -->

2022-11-10 14:02 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 366 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvg48D1LJiQZ3VMqt:-NGWqEfaDw3PbrX1rh9V:b-kx6ju0) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L366)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to new class AzureClientUtils
</blockquote></details>

Moved to new AzureClientBase


<!-- Sent from Reviewable.io -->

2022-11-10 14:02 UTC, markoharness commented
*[`960-api-services/src/main/java/io/harness/azure/AzureClient.java` line 393 at r15](https://reviewable.io/reviews/harness/harness-core/38691#-NGNvgp_EanpISgoosx7:-NGWqFvv31xgr61GEHQd:b-kx6ju0) ([raw file](https://github.com/harness/harness-core/blob/624c3a060b9ebc848420c40114658858ddc726ab/960-api-services/src/main/java/io/harness/azure/AzureClient.java#L393)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move to new class AzureClientUtils
</blockquote></details>

Moved to new AzureClientBase


<!-- Sent from Reviewable.io -->

2022-11-10 21:14 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 28 of 28 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691#-:-NGYOCJ7BbsEHI9RIrQ-:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-14 08:50 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691#-:-NGpKJvX3Kp5Qb-1G1C3:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-14 10:13 UTC, markoharness commented
trigger feature-build

2022-11-14 14:44 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 66 of 118 files at r1, 1 of 6 files at r2, 3 of 13 files at r3, 2 of 15 files at r4, 1 of 21 files at r5, 18 of 32 files at r7, 2 of 24 files at r9, 13 of 24 files at r10, 5 of 7 files at r11, 11 of 15 files at r12, 5 of 8 files at r14, 1 of 4 files at r15, 25 of 28 files at r16, 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691#-:-NGqaLEtAWkl07JLL1kC:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-14 15:00 UTC, markoharness commented
trigger codeformat

2022-11-15 13:27 UTC, mdmilic approved these changes
> Reviewed 9 of 118 files at r1, 3 of 24 files at r10, 1 of 8 files at r14, 3 of 28 files at r16.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38691)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-15 13:28 UTC, merged