[feat]: [CDS-44495]: Message fix for listBuckets
harness/harness-core pull request #38726
Opened 2022-10-12 12:16 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/38726)

2022-10-12 12:28 UTC, vtxorxwitty commented
trigger messagecheck

2022-10-12 12:31 UTC, puthrayaharness requested changes

2022-10-12 13:27 UTC, puthrayaharness requested changes

2022-10-12 13:27 UTC, puthrayaharness commented on 960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java
> +        throw new HintException("Please provide the correct region corresponding to the AWS access key.");
The message can be better. 
AWS connector without an access key as well. Will we get 403 in case of the wrong region or can it be because of anything else?

2022-10-17 05:15 UTC, vtxorxwitty commented on 960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java
> +        throw new HintException("Please provide the correct region corresponding to the AWS access key.");
This API will only fail in case of incorrect region. Authentication validations are already handled at the connector level. So I'll simplify this API try-catches.

2022-10-17 05:15 UTC, vtxorxwitty commented on 960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java
> +        throw new InvalidRequestException("Please provide the correct region corresponding to the AWS access key.");
Unit tests added.

2022-10-17 05:35 UTC, puthrayaharness requested changes

2022-10-17 05:35 UTC, puthrayaharness commented on 960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java
> +      throw new HintException("Please provide the correct region corresponding to the AWS access key.");
Why did we remove the explicit catch of the exception? Can we also update the Hint exception within `handleAmazonClientException` as well? Also we probably already have a test case file for this, can you confirm if we already have it or not?

2022-10-17 05:50 UTC, vtxorxwitty commented on 960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java
> +      throw new HintException("Please provide the correct region corresponding to the AWS access key.");
No @puthrayaharness, we don't have a test file for this class. Will check once again.

2022-10-27 12:50 UTC, closed without merging