feat : [CDS-44560] : Ecr labels backend code
harness/harness-core pull request #38772
Opened 2022-10-13 10:54 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-13 11:29 UTC, puthrayaharness requested changes

2022-10-13 11:29 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +    if (artifactDelegateResponse == null || artifactDelegateResponse.getLabel() == null) {
This can be simplified to `artifactDelegateResponse == null || EmptyPredicate.isEmpty(artifactdelegateresponse.getlabel)`

2022-10-13 11:29 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/ecr/EcrArtifactTaskHandler.java
> +    EcrArtifactDelegateResponse ecrArtifactDelegateResponse;
Please make the call in one place for labels. No need to write it in both if & else.

2022-10-13 11:29 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/EcrRequestResponseMapper.java
> +  public EcrArtifactDelegateResponse toEcrResponse(
Add labels to the existing response mapper. Why do we need a new method?

2022-10-13 11:29 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/ecr/EcrArtifactTaskHandler.java
> +      ecrArtifactDelegateResponse =
Why do we need two functions for the response mapper? Let the mapper handle an empty responses.

2022-10-13 11:29 UTC, puthrayaharness commented on 960-api-services/src/main/java/software/wings/helpers/ext/ecr/EcrServiceImpl.java
> +    } catch (NullPointerException ex) {
Why are we catching NullPointerException? Can we not fix the place that is throwing the NullPointerException?

2022-10-17 09:47 UTC, vivekkarnatiharness commented
trigger ti0

2022-10-17 09:47 UTC, vivekkarnatiharness commented
trigger ti1

2022-10-18 07:19 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-10-18 09:18 UTC, puthrayaharness requested changes

2022-10-18 09:18 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java
> +    return EmptyPredicate.isNotEmpty(artifactDelegateResponse.getLabel()) ? artifactDelegateResponse.getLabel()
Redundant check for empty. Directly return

2022-10-18 09:18 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/ecr/EcrArtifactTaskHandler.java
> +        EmptyPredicate.isNotEmpty(attributesRequest.getTagRegex())
Why check for regex? why can be not use `lastSuccessfulBuild` to fetch the number?

2022-10-18 09:18 UTC, puthrayaharness commented on 960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java
> +            -> ((Map<String, Object>) config.getValue()).get("Labels") != null
Why are we changing here? Also if you want to filter something then use `.filter` to take care of filter

2022-10-19 04:43 UTC, puthrayaharness approved these changes

2022-10-19 04:44 UTC, puthrayaharness approved these changes
> Reviewed 2 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38772)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2022-10-19 07:38 UTC, puthrayaharness approved these changes

2022-10-19 07:42 UTC, merged