feat: [CDS-36817]: added support for http and shell script templates
harness/harness-core pull request #38814
Opened 2022-10-16 22:12 UTC by prabu-kr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-20 07:29 UTC, puthrayaharness requested changes

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/dto/TemplateFilter.java
> +  @Parameter(description = "All services from Application to import") private String appId;
Do we only support application-level templates or even account-level templates?

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/template/TemplateFactory.java
> +    throw new InvalidRequestException("Currently only shell script & http templates are supported");
Let's not throw exception if we find unsupported Templates. Let's skip them.

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/template/TemplateFactory.java
> +    throw new InvalidRequestException("Currently only shell script & http templates are supported");
You can handle that two ways, either through NULL or have a default dummy implementation that return null when we try to generate the YAML.

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/template/NgTemplateService.java
> +  static boolean isMigrationSupported(Template template) {
Make this part of the interface with the default method returning `true`. Whoever implements this means that they support the template right?

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/template/NgTemplateService.java
> +  YamlDTO getNgTemplateConfig(Template template, String orgIdentifier, String projectIdentifier);
Please use the pattern used in other services like Secret, Connector Factory. We should rely on the inputs.

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/template/HttpTemplateService.java
> +    return NGTemplateConfig.builder()
Rather than having to duplicate this logic in every interface just return the spec from here.

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/importer/TemplateImportService.java
> +      throw new InvalidRequestException("No services found for given app");
Please update the error message.

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/dto/TemplateFilter.java
> +  @Parameter(description = "All services from Application to import") private String appId;
Please update the description

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/importer/TemplateImportService.java
> +public class TemplateImportService implements ImportService {
Add team annotation

2022-10-20 07:29 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/importer/TemplateImportService.java
> +      throw new InvalidRequestException("No services found for given app");
Can we have a common block for this logic & AppService where we find templates? Since they are pretty much the same?

2022-10-21 04:39 UTC, prabu-kr commented on 100-migrator/src/main/java/io/harness/ngmigration/dto/TemplateFilter.java
> +  @Parameter(description = "All services from Application to import") private String appId;
Done

2022-10-21 04:40 UTC, prabu-kr commented on 100-migrator/src/main/java/io/harness/ngmigration/template/TemplateFactory.java
> +    throw new InvalidRequestException("Currently only shell script & http templates are supported");
Done

2022-10-21 04:40 UTC, prabu-kr commented on 100-migrator/src/main/java/io/harness/ngmigration/template/NgTemplateService.java
> +  YamlDTO getNgTemplateConfig(Template template, String orgIdentifier, String projectIdentifier);
Done

2022-10-21 04:40 UTC, prabu-kr commented on 100-migrator/src/main/java/io/harness/ngmigration/template/NgTemplateService.java
> +  static boolean isMigrationSupported(Template template) {
Done

2022-10-21 04:40 UTC, prabu-kr commented on 100-migrator/src/main/java/io/harness/ngmigration/service/importer/TemplateImportService.java
> +      throw new InvalidRequestException("No services found for given app");
Done

2022-10-21 04:41 UTC, prabu-kr commented on 100-migrator/src/main/java/io/harness/ngmigration/service/importer/TemplateImportService.java
> +public class TemplateImportService implements ImportService {
Done

2022-10-21 05:21 UTC, puthrayaharness approved these changes

2022-10-21 07:06 UTC, merged