[feat]: [CDS-44248]: Data sync for deployment_step and execution_interrupt table
harness/harness-core pull request #38813
Opened 2022-10-16 15:30 UTC by Abhishek-CDC

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-03 15:04 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentStepEventProcessor.java
> +      "INSERT INTO DEPLOYMENT_STEP (ID,ACCOUNT_ID,APP_ID,STEP_NAME,STEP_TYPE,STATUS,FAILURE_DETAILS,START_TIME,END_TIME,DURATION,STAGE_NAME,EXECUTION_ID,APPROVED_BY,APPROVAL_TYPE,APPROVED_AT,APPROVAL
Manual intervention should never be null

2022-11-03 15:38 UTC, abhinavmittal-harness requested changes

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentStepEventProcessor.java
> +    upsertStatement.setTimestamp(
check if we can use null here

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +      if (stateType.equals(stateExecutionInstance.getStateType())) {
Reconcilliation shouldhave same thing

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +
ADd a comment describing why this was needed

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +          StepEventProcessor.DURATION, stateExecutionInstance.getEndTs() - stateExecutionInstance.getStartTs());
Consider starttime that you have calculated above

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +        }
Consider manual intervention in case of approval rejected

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +        }
Also considerif we rollback in case of approval reject

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +    stringData.put(StepEventProcessor.MANUAL_INTERVENTION_ID, executionInterrupt.getUuid());
InterruptId

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +          StepEventProcessor.MANUAL_INTERVENTION_TYPE, executionInterrupt.getExecutionInterruptType().toString());
Same as above

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +    if (executionInterrupt.getCreatedBy() != null && executionInterrupt.getCreatedBy().getEmail() != null) {
Check if interrupts can be triggered via pai or graphql
If so then we might need to sav e id as well

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java
> +      usageMetricsEventPublisher.publishDeploymentStepTimeSeriesEvent(
Dont publish if not updated

2022-11-03 15:38 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java
> +      try {
Can this be done in bulk

2022-11-04 04:57 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentStepEventProcessor.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zT-r1-23:-NG0-55q6E0mLKloTveK:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentStepEventProcessor.java#L23)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Manual intervention should never be null
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 06:10 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentStepEventProcessor.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zT-r1-71:-NG0Fpoj9vxhejTcc1in:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentStepEventProcessor.java#L71)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

check if we can use null here
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 06:11 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zO-r1-86:-NG0G25O1iJgs9L1Bi1m:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java#L86)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Reconcilliation shouldhave same thing
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 06:16 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java` line 129 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zO-r1-129:-NG0H7J1D-OewS-AMDYj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java#L129)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

ADd a comment describing why this was needed
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 06:17 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zO-r1-148:-NG0HFvf2Ybh-QJJg2y-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java#L148)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Consider starttime that you have calculated above
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 06:49 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zO-r1-210:-NG0Oi31AX6LWb-u7VXS:bb6tyiv) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java#L210)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

InterruptId
</blockquote></details>

DONE


<!-- Sent from Reviewable.io -->

2022-11-04 06:49 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zO-r1-213:-NG0Ojyc4DxaVndf97oY:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java#L213)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 07:02 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java` line 1104 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zR-r1-1104:-NG0Rjr4E2E2qNNgTGJR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L1104)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Dont publish if not updated
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 07:03 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java` line 2346 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zR-r1-2346:-NG0Rrmx2znXsGuB7GM0:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L2346)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Can this be done in bulk
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-04 09:17 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/38813#-NEWPkY8P-7YquNQB5zO-r1-220:-NG0vRt3ATJh4cWJ1jqs:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ba10b59eddfb78825d47cf4010c23fccda6ac1d1/400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java#L220)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Check if interrupts can be triggered via pai or graphql
If so then we might need to sav e id as well
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-06 09:59 UTC, merged