[feat]:[PL-25923]: removing duplicate validations from connector name.
harness/harness-core pull request #38929
Opened 2022-10-18 17:29 UTC by shreyas-harness

## Describe your changes
Removing NotNull and NotBlank check from connector name as NGEntityName has those validations. 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-19 11:28 UTC, VikasMaddukuriHarness approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38929)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-10-19 11:28 UTC, meenakshi-harness requested changes

2022-10-19 11:28 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/connector/ConnectorInfoDTO.java
> -  @NotNull @NotBlank @NGEntityName @Schema(description = ConnectorConstants.CONNECTOR_NAME) String name;
Removing this will make name as optional in Yaml schema. Did you test with UI?

2022-10-19 11:29 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/connector/ConnectorInfoDTO.java
> -  @NotNull @NotBlank @NGEntityName @Schema(description = ConnectorConstants.CONNECTOR_NAME) String name;
I see name been removed from all.json as well as required field

2022-10-19 11:31 UTC, tiwaritejas reviewed
Why is this change being made?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38929#-:-NEk-ni25tYnzqA9ctjI:bz3drnm)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-10-20 05:31 UTC, shreyas-harness commented
Closing this PR as it involves more complexity. 
Tracking the issue here - https://harness.slack.com/archives/CHTJL5STF/p1666239926259909

2022-10-20 05:31 UTC, closed without merging