[CCM-9342]: Batch job changes to fetch and store EC2 recommendations
harness/harness-core pull request #38935
Opened 2022-10-18 19:41 UTC by divyanshuchaubisa

## Describe your changes
Backend job will do below steps
* Fetch all ec2 recommendations for each aws account.
* Store in mongoDB (EC2Recommendation table)
* Store in CE_Recommendation table in timescale.
* Fetch all EC2 instance utilisation data (cpu, memory) for which the recommendations are present.
* Store in the Utilization_data table in timescale.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-18 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=38935) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=38935) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=38935) it.</sub>

2022-10-21 12:03 UTC, trunapushpa requested changes
> Reviewed 6 of 23 files at r1, 8 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/dao/recommendation/EC2RecommendationDAO.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/38935#-NEuQENL-kPWiVKt04G0:-NEuQENL-kPWiVKt04G1:bgyut5t) ([raw file](https://github.com/harness/harness-core/blob/e81e5eb1eb9f839857ff2b8c1dfb11e908bc9fec/490-ce-commons/src/main/java/io/harness/ccm/commons/dao/recommendation/EC2RecommendationDAO.java#L49)):*
> ```Java
> 
>   @NonNull
>   public Optional<EC2Recommendation> fetchECSRecommendationById(@NonNull String accountIdentifier, @NonNull String id) {
> ```

should this be `fetchEC2RecommendationById`?


<!-- Sent from Reviewable.io -->

2022-10-21 15:18 UTC, nikunj-badjatya requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)* status: 11 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/BUILD.bazel` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38935#-NEv6rLG6XTlis0PPBMT:-NEv6rLG6XTlis0PPBMU:bru0tgx) ([raw file](https://github.com/harness/harness-core/blob/e81e5eb1eb9f839857ff2b8c1dfb11e908bc9fec/400-rest/BUILD.bazel#L99)):*
> ```Starlark
>         "@maven//:com_amazonaws_aws_java_sdk_core",
>         "@maven//:com_amazonaws_aws_java_sdk_costandusagereport",
>         "@maven//:com_amazonaws_aws_java_sdk_costexplorer",
> ```

Please add this dependencies in batch processing build.bazel


<!-- Sent from Reviewable.io -->

2022-10-26 11:40 UTC, divyanshuchaubisa commented
> 
Removed this method, this change is regarding the backend job and data writing to the data stores. API changes will be taken care in another PR.

2022-10-26 11:41 UTC, divyanshuchaubisa commented
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)_ status: 11 file(s) to review. 2 change requests. 0 of 1 approvals obtained.
> 
> _[`400-rest/BUILD.bazel` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38935#-NEv6rLG6XTlis0PPBMT:-NEv6rLG6XTlis0PPBMU:bru0tgx) ([raw file](https://github.com/harness/harness-core/blob/e81e5eb1eb9f839857ff2b8c1dfb11e908bc9fec/400-rest/BUILD.bazel#L99)):_
> 
> > ```python
> >         "@maven//:com_amazonaws_aws_java_sdk_core",
> >         "@maven//:com_amazonaws_aws_java_sdk_costandusagereport",
> >         "@maven//:com_amazonaws_aws_java_sdk_costexplorer",
> > ```
> 
> Please add this dependencies in batch processing build.bazel

Added.

2022-10-26 11:42 UTC, divyanshuchaubisa commented
> > Reviewed 6 of 23 files at r1, 8 of 19 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)_ status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`490-ce-commons/src/main/java/io/harness/ccm/commons/dao/recommendation/EC2RecommendationDAO.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/38935#-NEuQENL-kPWiVKt04G0:-NEuQENL-kPWiVKt04G1:bgyut5t) ([raw file](https://github.com/harness/harness-core/blob/e81e5eb1eb9f839857ff2b8c1dfb11e908bc9fec/490-ce-commons/src/main/java/io/harness/ccm/commons/dao/recommendation/EC2RecommendationDAO.java#L49)):_
> 
> > ```java
> >   @NonNull
> >   public Optional<EC2Recommendation> fetchECSRecommendationById(@NonNull String accountIdentifier, @NonNull String id) {
> > ```
> 
> should this be `fetchEC2RecommendationById`?

Removed this method, this change is regarding the backend job and data writing to the data stores. API changes will be taken care in another PR.

2022-10-26 15:34 UTC, trunapushpa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/AWSRegionRegistry.java
> +  static final Map<String, String> regionMap = ImmutableMap.<String, String>builder()
Does it have to be a constant in code? What if the regions change or a new one is added? Is there an AWS API for this? Maybe we can have it as an enhancement if its more effort.

2022-10-26 15:43 UTC, trunapushpa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java
> +  private Map<String, AwsCrossAccountAttributes> getCrossAccountAttributes(String accountId) {
Same function is present in AwsECSClusterDataSyncTasklet. Should we move it out to a common helper class?

2022-10-26 15:44 UTC, trunapushpa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java
> +          cloudToHarnessMappingService.listSettingAttributesCreatedInDuration(accountId, CE_CONNECTOR, CE_AWS);
Why are we calling the same function again? It's called before too in Line no 380.

2022-10-26 16:24 UTC, divyanshuchaubisa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/AWSRegionRegistry.java
> +  static final Map<String, String> regionMap = ImmutableMap.<String, String>builder()
We are getting aws region description name from the rightsizing api not the actual region. Since there is no support in the aws sdk ([Regions](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html)) to fetch the region name from the description (vice versa is present though) hence we will have to write our own mapping.

Reference: https://stackoverflow.com/questions/38020106/how-should-i-get-aws-region-names-using-regions

Also this enum is having the values from the latest of `Regions` class. If there is any new region added to aws we might need to add here as well.

2022-10-26 21:50 UTC, trunapushpa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java
> +  @Autowired private AWSEC2RecommendationService awsec2RecommendationService;
Would the variable name `awsEc2RecommendationService` make more sense than `awsec2RecommendationService`?

2022-10-26 21:50 UTC, trunapushpa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/AWSEC2RecommendationService.java
> +public interface AWSEC2RecommendationService {
Can we have this in intfc directory? just like impl directory

2022-10-26 21:50 UTC, trunapushpa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/impl/AWSEC2RecommendationServiceImpl.java
> +  List<RightsizingRecommendation> getRecommendationsBasedRecommendationOnType(
Function name `getRecommendationsBasedRecommendationOnType` is unclear. Either change the name or add comment on what it means.

2022-10-26 21:50 UTC, trunapushpa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java
> +    List<AWSEC2Details> awsec2Details = new ArrayList<>();
awsEc2Details?

2022-10-27 03:47 UTC, hitesharinga requested changes
> Reviewed 4 of 23 files at r1, 15 of 19 files at r2, 4 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)* status: 3 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMSwBTCgDlFSkkeKpc:-NFMSwBTCgDlFSkkeKpd:b-g8raig) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java#L34)):*
> ```Java
> @OwnedBy(HarnessTeam.CE)
> public enum BatchJobType {
>   AWS_EC2_SERVICE_RECOMMENDATION(10, 1, ChronoUnit.DAYS, emptyList(), OUT_OF_CLUSTER_ECS),
> ```

We use BatchJobScheduledDataServiceImpl class to get the job run interval. 
Mostly the start time for the next run is end time of prev run but in some cases we don't run the specific job for more than one day if we haven't run it for a couple of days. 
IN fetchLastBatchJobScheduledTime could you add   AWS_EC2_SERVICE_RECOMMENDATION whereever you see AWS_ECS_CLUSTER_SYNC. 



_Code quote:_
```Java
OUT_OF_CLUSTER_ECS)
```
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java` line 97 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMUvf82HZ0Ny7hwIpF:-NFMUvf82HZ0Ny7hwIpG:b-dwixxy) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java#L97)):*
> ```Java
>         }
>       }
>       metricDataResultMap.putAll(awsCloudWatchHelperService
> ```

We are doing this call per instance, can we do this for a list of instances?
I have seen many customers asking us about # of calls we make.  
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMUOdz1qKabLt0ming:-NFMUOe-DnN7oQl-j_rQ:b-bgmxfh) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java#L110)):*
> ```Java
>     });
> 
>     log.info("metricDataResultMap = {}", metricDataResultMap);
> ```

we can change this to debug 
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 82 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMWl1w1PsaOCWNKMrS:-NFMWl1w1PsaOCWNKMrT:b5we8ce) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L82)):*
> ```Java
>     String accountId = jobConstants.getAccountId();
>     Instant startTime = Instant.ofEpochMilli(jobConstants.getJobStartTime());
>     log.info("accountId = {}", accountId);
> ```

accountId will be present in the above log line. 
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 93 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMWx3LD-YtD0aI5JTv:-NFMWx3LD-YtD0aI5JTw:bbszefp) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L93)):*
> ```Java
>             EC2RecommendationRequest.builder().awsCrossAccountAttributes(infraAccCrossArn.getValue()).build());
>         Map<String, List<EC2InstanceRecommendationInfo>> instanceLevelRecommendations = new HashMap<>();
>         log.info("Ec2RecommendationResponse = {}", ec2RecommendationResponse);
> ```

can we just log size? 
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 125 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMX5vu9qT2nURH3lUR:-NFMX5vu9qT2nURH3lUS:b-r03fev) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L125)):*
> ```Java
>               // Save the ec2 recommendation to mongo and timescale
>               EC2Recommendation ec2Recommendation = ec2RecommendationDAO.saveRecommendation(recommendation);
>               log.info("EC2Recommendation saved to mongoDB = {}", ec2Recommendation);
> ```

change to debug
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 378 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NEgbRkcqHFyBnV9VQkd-r5-378:-NFMXkjBAsD5yA46WVcS:b32v57) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L378)):*
<details><summary><i>Previously, trunapushpa (Trunapushpa) wrote…</i></summary><blockquote>

Same function is present in AwsECSClusterDataSyncTasklet. Should we move it out to a common helper class?
</blockquote></details>

+1
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 380 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMXtE07wEzYXcrMUlD:-NFMXtE07wEzYXcrMUlE:b-matuhq) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L380)):*
> ```Java
>   private Map<String, AwsCrossAccountAttributes> getCrossAccountAttributes(String accountId) {
>     List<SettingAttribute> ceConnectorsList =
>         cloudToHarnessMappingService.listSettingAttributesCreatedInDuration(accountId, CE_CONNECTOR, CE_AWS);
> ```

We just need to call for NG connectors, We don't have to support CG connectors.


<!-- Sent from Reviewable.io -->

2022-10-27 17:55 UTC, divyanshuchaubisa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java
> +  private Map<String, AwsCrossAccountAttributes> getCrossAccountAttributes(String accountId) {
Moved to helper class.

2022-10-27 17:56 UTC, divyanshuchaubisa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java
> +          cloudToHarnessMappingService.listSettingAttributesCreatedInDuration(accountId, CE_CONNECTOR, CE_AWS);
Removed the redundant call.

2022-10-27 18:12 UTC, divyanshuchaubisa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/AWSEC2RecommendationService.java
> +public interface AWSEC2RecommendationService {
Current path is `//../ec2.service` seems more intuitive to me. Service interfaces should reside in the service directory.

2022-10-27 18:17 UTC, divyanshuchaubisa commented on batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/impl/AWSEC2RecommendationServiceImpl.java
> +  List<RightsizingRecommendation> getRecommendationsBasedRecommendationOnType(
Renamed to `getRecommendationsBasedOnRecommendationTarget`.

2022-10-27 20:26 UTC, divyanshuchaubisa commented
>

2022-10-27 20:27 UTC, divyanshuchaubisa commented
>

2022-10-27 21:00 UTC, trunapushpa approved these changes

2022-10-30 10:05 UTC, trunapushpa approved these changes

2022-10-31 05:16 UTC, divyanshuchaubisa reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)* status: 16 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMSwBTCgDlFSkkeKpc:-NFgQ2xR4wMs7EMo5Zuv:bmnu3wp) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java#L34)):*
> AWS_ECS_CLUSTER_SYNC
Added
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java` line 97 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMUvf82HZ0Ny7hwIpF:-NFgQENI5loOiTOzo8IN:b-vsgi1b) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java#L97)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

We are doing this call per instance, can we do this for a list of instances?
I have seen many customers asking us about # of calls we make.  
</blockquote></details>

I have clubbed this to region level and making one call per region now.
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMUOdz1qKabLt0ming:-NFgPUz08h93h89Var3y:b499q7j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java#L110)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

we can change this to debug 
</blockquote></details>

Changed
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 67 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NEgbRkcqHFyBnV9VQkd-r5-67:-NFgQQgt13uY9nuBq70N:ba3o3s1) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L67)):*
<details><summary><i>Previously, trunapushpa (Trunapushpa) wrote…</i></summary><blockquote>

Would the variable name `awsEc2RecommendationService` make more sense than `awsec2RecommendationService`?
</blockquote></details>

Renamed
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 82 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMWl1w1PsaOCWNKMrS:-NFgQSml-ijoScKhzdMv:bkm2jry) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L82)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

accountId will be present in the above log line. 
</blockquote></details>

Removed the log.
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 93 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMWx3LD-YtD0aI5JTv:-NFgQcktAvEmaJZ9qVhh:b2wc95e) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L93)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

can we just log size? 
</blockquote></details>

This response is coming from recommendation api which could be the source of truth for the debugging. I have changed it to debug so we can convert whenever we need.
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 125 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMX5vu9qT2nURH3lUR:-NFgR8wZ9xPsbZ58pe0k:b499q7j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L125)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

change to debug
</blockquote></details>

Changed
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 231 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NEgbRkcqHFyBnV9VQkd-r5-231:-NFgRAclAhMId-YoxT_w:bt1b19p) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L231)):*
<details><summary><i>Previously, trunapushpa (Trunapushpa) wrote…</i></summary><blockquote>

awsEc2Details?
</blockquote></details>

Renamed.
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 380 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMXtE07wEzYXcrMUlD:-NFgRFqF2d9LjE6wtLV3:bxs70ls) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L380)):*
> Renamed.
Removed the cg call


<!-- Sent from Reviewable.io -->

2022-10-31 05:36 UTC, divyanshuchaubisa reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)* status: 16 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/BUILD.bazel` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38935#-NEv6rLG6XTlis0PPBMT:-NFgXDk59TYG-4ILBcLI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e81e5eb1eb9f839857ff2b8c1dfb11e908bc9fec/400-rest/BUILD.bazel#L99)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Added.
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMSwBTCgDlFSkkeKpc:-NFgXVTH5WFcN0W4duiE:ban9ryb) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/ccm/BatchJobType.java#L34)):*
> Done
Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/AWSEC2RecommendationService.java` line 6 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NEgbRkcqHFyBnV9VQkV-r5-6:-NFgXWUyB2mhSFWOjPBU:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/AWSEC2RecommendationService.java#L6)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Current path is `//../ec2.service` seems more intuitive to me. Service interfaces should reside in the service directory.
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/AWSRegionRegistry.java` line 10 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NEgbRkcqHFyBnV9VQkX-r5-10:-NFgXXSc50WCppcJBH_c:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/AWSRegionRegistry.java#L10)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

We are getting aws region description name from the rightsizing api not the actual region. Since there is no support in the aws sdk ([Regions](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html)) to fetch the region name from the description (vice versa is present though) hence we will have to write our own mapping.

Reference: https://stackoverflow.com/questions/38020106/how-should-i-get-aws-region-names-using-regions

Also this enum is having the values from the latest of `Regions` class. If there is any new region added to aws we might need to add here as well.

</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java` line 97 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMUvf82HZ0Ny7hwIpF:-NFgXYnG-s6mszyrybgu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java#L97)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

I have clubbed this to region level and making one call per region now.
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMUOdz1qKabLt0ming:-NFgXZG_64K5Itb769WI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/helper/EC2MetricHelper.java#L110)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Changed
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/impl/AWSEC2RecommendationServiceImpl.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NEgbRkcqHFyBnV9VQkZ-r5-55:-NFgXZmTCP8daDpUh21m:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/impl/AWSEC2RecommendationServiceImpl.java#L55)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Renamed to `getRecommendationsBasedOnRecommendationTarget`.
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 67 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NEgbRkcqHFyBnV9VQkd-r5-67:-NFgX_sd2chNSU4CSS-g:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L67)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Renamed
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 82 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMWl1w1PsaOCWNKMrS:-NFgXaHl3utVagTMaxcd:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L82)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Removed the log.
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 93 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMWx3LD-YtD0aI5JTv:-NFgXam387Yxkgt8D0Vm:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L93)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

This response is coming from recommendation api which could be the source of truth for the debugging. I have changed it to debug so we can convert whenever we need.
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 125 at r5](https://reviewable.io/reviews/harness/harness-core/38935#-NFMX5vu9qT2nURH3lUR:-NFgXbHFEXHIapjbZarf:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30927b20b97d90fed9f06a9346499993915d4c30/batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java#L125)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

Changed
</blockquote></details>

Done
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/tasklet/AWSEC2RecommendationTasklet.java` line 231 at r5 [...]

2022-10-31 06:17 UTC, hitesharinga approved these changes
> Reviewed 1 of 3 files at r6, 1 of 3 files at r7, 1 of 6 files at r8, 8 of 9 files at r11, 1 of 2 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935)* status: 1 change requests. 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-31 06:18 UTC, hitesharinga approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935#-:-NFggFInAHKLZ3zuWPCY:bnfp4nl)* status: 1 change requests. 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-31 07:00 UTC, hitesharinga approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38935#-:-NFgprjd2mgU51QG5J4k:bnfp4nl)* status: 1 change requests. 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-31 09:38 UTC, divyanshuchaubisa commented
trigger ti2
trigger ti3
trigger ti4
trigger ft1
trigger ft2

2022-10-31 09:42 UTC, AnshuH commented
trigger ti2 ti3 ti4 ft1

2022-10-31 12:21 UTC, merged