fix: [CDS-43477]: Service Dashboard showing the wrong Artifact info from what was Deployed
harness/harness-core pull request #39008
Opened 2022-10-19 18:03 UTC by rafaelmart1ns

## Describe your changes

This pr will change the version of the deployment artifact shown by the service dashboard.
Old behavior:
- When you have a deployment with success and after that, you have a deployment with rollback error services dashboard shows the last successful deployment.
New behavior:
- When you have the same case above now shows the last deployment with a rollback error with the correct artifact. 

<img width="2085" alt="image" src="https://user-images.githubusercontent.com/108759997/196769487-9d9d1df8-fbc1-48de-a357-f6b28915e56d.png">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-19 23:56 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java
> +        .filter(WorkflowExecutionKeys.envId, envId)
wont having only inframapping id except env and svc id work ?

2022-10-19 23:56 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java
> +        .filter(WorkflowExecutionKeys.infraMappingIds, infraMappingId)
if we have index 
account, app, inframpping we should use that i think

2022-10-20 11:21 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java
> +        .filter(WorkflowExecutionKeys.envId, envId)
it will only make this request if it has all the data and at least 1 workflow execution, I can't map a case where this can occur.

2022-10-20 11:36 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java
> +        .filter(WorkflowExecutionKeys.infraMappingIds, infraMappingId)
Do you mean that I have to put these fields in order to make use of the index?

2022-10-20 17:42 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39008)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 6668 at r1](https://reviewable.io/reviews/harness/harness-core/39008#-NElPgkhJ1v2qrijDjYf-r1-6668:-NEqUD-N7unG3cvv2uIm:bq5gpdt) ([raw file](https://github.com/harness/harness-core/blob/92e5b17cd975a0c57f2eaaa47c69f7442e8a054e/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L6668)):*
<details><summary><i>Previously, rafaelmart1ns (Rafael Martins) wrote…</i></summary><blockquote>

it will only make this request if it has all the data and at least 1 workflow execution, I can't map a case where this can occur.
</blockquote></details>

I would like to modify this query to have 
appId, workflowId and Inframapping id else it will have query performance issues - @lasdox can explain 
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 6670 at r1](https://reviewable.io/reviews/harness/harness-core/39008#-NElPgkhJ1v2qrijDjYf-r1-6670:-NEqULWl65Vmm7Gqj4Gy:by3hk3x) ([raw file](https://github.com/harness/harness-core/blob/92e5b17cd975a0c57f2eaaa47c69f7442e8a054e/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L6670)):*
<details><summary><i>Previously, rafaelmart1ns (Rafael Martins) wrote…</i></summary><blockquote>

Do you mean that I have to put these fields in order to make use of the index?
</blockquote></details>

No, we just have to make sure indexes are present


<!-- Sent from Reviewable.io -->

2022-10-21 18:07 UTC, abhinav-harness approved these changes
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39008)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-21 22:28 UTC, lasdox approved these changes
> Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39008)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-10-21 22:28 UTC, merged