fix: [CI-4536]: Send step status from LE to manager
harness/harness-core pull request #39034
Opened 2022-10-20 07:18 UTC by smjt-h

## Describe your changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/39034)

2022-10-21 10:39 UTC, smjt-h commented
trigger codebasehash

2022-10-27 06:15 UTC, shubham149 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CI_REST_ENABLED("Used for sending step status via rest apis from Lite Engine to manager", HarnessTeam.CI),
Why do we have 2 new feature flags for this change? Use a better name

2022-10-27 06:15 UTC, shubham149 commented on WORKSPACE
> +go_repository(
Ensure that we are not reducing the version of any library

2022-10-27 06:15 UTC, shubham149 commented on WORKSPACE
>  go_repository(
Remove all the changes that moves library download from type=zip

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/new/executor/async_executor.go
> +	log.Info("***New step req recieved: ", in)
Remove this log

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/new/executor/step_executor.go
> +	managerSvcEndpoint  string // Manager service endpoint
run gofmt on all the .go file changes

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/rest/http.go
> +	// log := logrus.New()
remove this line

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/rest/http.go
> +	Client            *http.Client
can we make it private?

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/rest/http.go
> +	p.Logger.Info("req==== ", req)
remove this log

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/rest/token_cache.go
> +	token, err := Token(audience, issuer, t.id, t.secret, t.expiry)
What's the reasoning for using token cache? Token is generated here without any network calls.

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/step_status.go
> +		log.Info("Grpc is Enabled: ", grpcEnabled)
This statement seems incorrect. grpcEnabled can either be true or false.

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/step_status.go
> +		log.Info("Sending Step Status via GRPC")
Step Status -> step status

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/step_status.go
> +		log.Info("Sending Step Status via REST")
ditto

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/step_status.go
> +			log.Info("Error sending status with http, sending status with grpc as fallback. err:", err)
Use warning log

2022-10-27 06:15 UTC, shubham149 commented on product/ci/engine/status/step_status.go
> +			arg := getRequestArg(stepID, accountID, callbackToken, taskID, numRetries, timeTaken, status, errMsg, stepOutput, artifact, log)
There has to be a separate method sendStatusGrpc which needs to be called instead of L74 and L75

2022-10-27 07:12 UTC, smjt-h commented on product/ci/engine/status/rest/token_cache.go
> +	token, err := Token(audience, issuer, t.id, t.secret, t.expiry)
This is inline with the logic that we are following in dlite.

2022-10-27 08:19 UTC, smjt-h commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/providers/InternalContainerParamsProvider.java
> +      envVars.put(HARNESS_LE_REST_ENABLED_STATUS, "true");
done

2022-10-27 08:20 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/CIK8ExecuteStepTaskHandler.java
> +    String managerurl = delegateConfiguration.getManagerUrl();
done

2022-10-27 08:20 UTC, smjt-h commented on WORKSPACE
> +go_repository(
checked

2022-10-27 08:20 UTC, smjt-h commented on product/ci/engine/new/executor/async_executor.go
> +	log.Info("***New step req recieved: ", in)
done

2022-10-27 08:20 UTC, smjt-h commented on product/ci/engine/status/rest/http.go
> +	Client            *http.Client
done

2022-10-27 08:20 UTC, smjt-h commented on product/ci/engine/status/step_status.go
> +		log.Info("Grpc is Enabled: ", grpcEnabled)
fixed

2022-10-27 08:21 UTC, smjt-h commented on product/ci/engine/status/step_status.go
> +			log.Info("Error sending status with http, sending status with grpc as fallback. err:", err)
done

2022-10-27 08:21 UTC, smjt-h commented on WORKSPACE
>  go_repository(
reverted all type=zip deps

2022-10-27 08:21 UTC, smjt-h commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CI_REST_ENABLED("Used for sending step status via rest apis from Lite Engine to manager", HarnessTeam.CI),
removed

2022-10-27 08:21 UTC, smjt-h commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/providers/InternalContainerParamsProvider.java
> +    if (featureFlagService.isEnabled(FeatureName.CI_LE_GRPC_ENABLED, accountID)) {
done

2022-10-27 08:26 UTC, vistaarjuneja requested changes

2022-10-27 08:26 UTC, vistaarjuneja commented on product/ci/engine/status/rest/token.go
> +package rest
We should not be replicating this code. It's already present in `dlite`, we should reuse wherever possible

2022-10-27 08:26 UTC, vistaarjuneja commented on product/ci/engine/status/rest/token_cache.go
> +package rest
Ditto. Let's not replicate

2022-10-27 08:26 UTC, vistaarjuneja commented on product/ci/engine/status/rest/http.go
> +package rest
We should be reusing the entire send status code of dlite

2022-10-27 08:35 UTC, vistaarjuneja commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/providers/InternalContainerParamsProvider.java
> +    if (featureFlagService.isEnabled(FeatureName.CI_LE_STATUS_GRPC_ENABLED, accountID)) {
Note that the default value would be false here which means we would start using this new flow as soon as we do the deployment. That's ok but just wanted to make sure you are aware of it.

2022-10-27 08:37 UTC, vistaarjuneja commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/stepstatus/artifact/DockerArtifactMetadata.java
> +  String type;
I'm not sure if this gets used in kryo anywhere but just for precaution can we move `String type` after `dockerArtifacts`? 
We have seen random issues with kryo in the past

2022-10-27 17:24 UTC, smjt-h commented
trigger ti1

2022-10-28 08:35 UTC, harshjain12 commented
Add response log in new api

Move hard coded strings to constants

2022-10-28 09:44 UTC, harshjain12 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CI_LE_STATUS_GRPC_ENABLED("Used for sending step status via rest apis from Lite Engine to manager", HarnessTeam.CI),
Create feature flag for rest api

2022-10-28 12:04 UTC, smjt-h commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CI_LE_STATUS_GRPC_ENABLED("Used for sending step status via rest apis from Lite Engine to manager", HarnessTeam.CI),
done

2022-10-28 12:38 UTC, vistaarjuneja commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/CIK8ExecuteStepTaskHandler.java
> +      managerUrl = managerUrl.replace("/api/", "");
Can you check if there is some function to get the manager URL instead of doing a replace here?

2022-10-28 12:44 UTC, vistaarjuneja commented on product/ci/engine/status/payloads/payloads.go
> +	TaskResponse struct {
Reuse from dlite, not needed to add here

2022-10-28 12:44 UTC, vistaarjuneja commented on product/ci/engine/status/step_status.go
> +			TotalTimeTakenInMillis: int64(timeTaken / time.Millisecond),
you can call Milliseconds on time.Duration
`timeTaken.Milliseconds()`

2022-10-28 12:44 UTC, vistaarjuneja commented
Last few comments, looks good overall

2022-10-28 12:53 UTC, smjt-h commented on product/ci/engine/status/step_status.go
> +			TotalTimeTakenInMillis: int64(timeTaken / time.Millisecond),
done

2022-10-28 12:53 UTC, smjt-h commented on product/ci/engine/status/payloads/payloads.go
> +	TaskResponse struct {
done

2022-10-28 12:53 UTC, smjt-h commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CI_LE_STATUS_REST_ENABLED("Used for sending step status via rest apis from Lite Engine to manager", HarnessTeam.CI),
done

2022-10-28 13:00 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/CIK8ExecuteStepTaskHandler.java
> +      managerUrl = managerUrl.replace("/api/", "");
this was the only way I found to get managerurl from delegate side

2022-10-28 13:04 UTC, smjt-h commented
tested with older delegate as well, its falling back to grpc and not failing

2022-10-28 14:01 UTC, smjt-h commented
trigger pmd

2022-10-28 14:13 UTC, harshjain12 submitted a review, later dismissed
> Reviewed 6 of 24 files at r1, 1 of 8 files at r2, 13 of 16 files at r3, 6 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39034)* status: 1 change requests. 15. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 14:49 UTC, smjt-h commented
trigger pmd

2022-10-28 15:25 UTC, vistaarjuneja submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 24 files at r1, 1 of 8 files at r2, 12 of 16 files at r3, 6 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39034#-:-NFUBXTU8w5rzzEPcayE:bnfp4nl)* status: 11. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 15:31 UTC, aman-harness approved these changes
> Reviewed 6 of 24 files at r1, 1 of 8 files at r2, 13 of 16 files at r3, 6 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39034)* status: 11. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 15:34 UTC, smjt-h commented
trigger codebasehash

2022-10-28 15:57 UTC, harshjain12 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39034#-:-NFUIvcm62sqAv4rr3O_:bnfp4nl)* status: 11. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 16:03 UTC, vistaarjuneja approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39034#-:-NFUKLrrE9drzjUDfKuY:bnfp4nl)* status: 11. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 16:33 UTC, aman-harness approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39034)* status: 11. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-10-28 16:37 UTC, smjt-h commented
trigger codebasehash

2022-10-28 17:08 UTC, merged