feat: [SRM-12401]: CRUD APIs for composite SLOs
harness/harness-core pull request #39050
Opened 2022-10-20 11:41 UTC by karansaraswat19

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-20 12:02 UTC, karansaraswat19 commented
trigger ti0, ti1, ti3, ti4, ft1, ft2, compile

2022-10-20 12:08 UTC, karansaraswat19 commented
trigger messagecheck

2022-10-20 14:29 UTC, Varsha-lalwani requested changes
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEphrud9tbMTmSNY6It:-NEphrud9tbMTmSNY6Iu:bj7xb9q) ([raw file](https://github.com/harness/harness-core/blob/d1cfbb24b144751cbb511e4e20618f2907a8bf6d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L52)):*
> ```Java
>   @ApiModelProperty(required = true) @NotNull List<String> userJourneyRefs;
>   @Valid @NotNull SLOTargetDTO sloTarget;
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier ServiceLevelObjectiveType type;
> ```

why did we remove Apimodelproperty annotation?



_Code quote:_
```Java
@ApiModelProperty(required = true)
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpk1--93buxWe4FauF:-NEpk1--93buxWe4FauG:b-2g233e) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L113)):*
> ```Java
>       sloHealthIndicatorService.upsert(
>           serviceLevelObjectiveTypeSLOV2TransformerMap.get(serviceLevelObjectiveDTO.getType())
>               .getSLOV2(projectParams, serviceLevelObjectiveDTO, true, serviceLevelIndicators));
> ```

sloHealthIndicator we have to update for compositeSLO as well.



_Code quote:_
```Java
      sloHealthIndicatorService.upsert(
          serviceLevelObjectiveTypeSLOV2TransformerMap.get(serviceLevelObjectiveDTO.getType())
              .getSLOV2(projectParams, serviceLevelObjectiveDTO, true, serviceLevelIndicators));
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEplIy7Evs5M3YSmMzs:-NEplIy7Evs5M3YSmMzt:b-na8b9u) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L113)):*
> ```Java
>       sloHealthIndicatorService.upsert(
>           serviceLevelObjectiveTypeSLOV2TransformerMap.get(serviceLevelObjectiveDTO.getType())
>               .getSLOV2(projectParams, serviceLevelObjectiveDTO, true, serviceLevelIndicators));
> ```

For composite SLO API, validation needs to be done before saving SLI.  



_Code quote:_
```Java
    List<String> serviceLevelIndicators = Collections.emptyList();
    if (serviceLevelObjectiveDTO.getType().equals(ServiceLevelObjectiveType.SIMPLE)) {
      SimpleServiceLevelObjectiveSpec simpleServiceLevelObjectiveSpec =
          (SimpleServiceLevelObjectiveSpec) serviceLevelObjectiveDTO.getSpec();
      serviceLevelIndicators = serviceLevelIndicatorService.create(projectParams,
          simpleServiceLevelObjectiveSpec.getServiceLevelIndicators(), serviceLevelObjectiveDTO.getIdentifier(),
          simpleServiceLevelObjectiveSpec.getMonitoredServiceRef(),
          simpleServiceLevelObjectiveSpec.getHealthSourceRef());
      sloHealthIndicatorService.upsert(
          serviceLevelObjectiveTypeSLOV2TransformerMap.get(serviceLevelObjectiveDTO.getType())
              .getSLOV2(projectParams, serviceLevelObjectiveDTO, true, serviceLevelIndicators));
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpmhMh9_sX6sRD7w28:-NEpmhMh9_sX6sRD7w29:b-tmt0gl) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L143)):*
> ```Java
>   @Override
>   public ServiceLevelObjectiveV2Response updateV2(
>       ProjectParams projectParams, String identifier, ServiceLevelObjectiveV2DTO serviceLevelObjectiveDTO) {
> ```

Here as well, we need to validate first that the entity exists before updating the SLI
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 154 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpmx5n6o1xD42m47Oo:-NEpmx5n6o1xD42m47Op:b-b2taeq) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L154)):*
> ```Java
>     }
>     return update(
>         projectParams, serviceLevelObjectiveDTO.getIdentifier(), serviceLevelObjectiveDTO, serviceLevelIndicators);
> ```

SLOHealthIndicator and errorBudget will be updated as well



_Code quote:_
```Java
    return update(
        projectParams, serviceLevelObjectiveDTO.getIdentifier(), serviceLevelObjectiveDTO, serviceLevelIndicators);
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 460 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpmPMA6XUCzMSo1Zx5:-NEpmPMA6XUCzMSo1Zx6:bj61j75) ([raw file](https://github.com/harness/harness-core/blob/d1cfbb24b144751cbb511e4e20618f2907a8bf6d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L460)):*
> ```Java
> 
>   private AbstractServiceLevelObjective saveServiceLevelObjectiveV2Entity(
>       ProjectParams projectParams, ServiceLevelObjectiveV2DTO serviceLevelObjectiveV2DTO, boolean isEnabled) {
> ```

also add an assertion that total weightage percentage is 100



_Code quote:_
```Java
     .getSLOV2(projectParams, serviceLevelObjectiveV2DTO, isEnabled);
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 513 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpm8LJ0WY8ve0POykR:-NEpm8LJ0WY8ve0POykS:b-30aztx) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L513)):*
> ```Java
> 
>   private AbstractServiceLevelObjective saveServiceLevelObjectiveV2Entity(ProjectParams projectParams,
>       ServiceLevelObjectiveV2DTO serviceLevelObjectiveV2DTO, boolean isEnabled, List<String> serviceLevelIndicators) {
> ```

Before saving the entity we need to verify that simple SLO exists for whichever simpleSLORefs we have added
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/SLOV2Transformer.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpklXF9PAcM3DrHKgF:-NEpklXF9PAcM3DrHKgG:b-3xr69x) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/SLOV2Transformer.java#L19)):*
> ```Java
> public interface SLOV2Transformer<E extends AbstractServiceLevelObjective> {
>   E getSLOV2(ProjectParams projectParams, ServiceLevelObjectiveV2DTO serviceLevelObjectiveV2DTO, Boolean isEnabled,
>       List<String> serviceLevelIndicators);
> ```

Why do we need sli's as a separate param? We do have sli's in the DTO, you can save sli's and update the DTO and send that DTO as the param



_Code quote:_
```Java
  [...]

2022-10-21 03:06 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsStBt14ORL-qvWRqr:-NEsStBt14ORL-qvWRqs:b-853zzs) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L57)):*
> ```Java
> 
> @Api("slo/v2")
> @Path("slo/v2")
> ```

remove path until API is tested and ready to be exposed to the outside world.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsUYcsBJlk5m8honTD:-NEsUYcsBJlk5m8honTE:b-tmsocy) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java#L30)):*
> ```Java
>   ServiceLevelObjectiveV2Response create(
>       ProjectParams projectParams, ServiceLevelObjectiveV2DTO serviceLevelObjectiveDTO);
>   ServiceLevelObjectiveV2Response createV2(ProjectParams projectParams,
> ```

why are we using createV2? we have a method for create and update. API call for the Simple ServiceLevelObjective resource is already calling it. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLOErrorBudgetResetService.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsVE1K6Dm0kxbAcByP:-NEsVE1K6Dm0kxbAcByQ:b-vmv4gb) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLOErrorBudgetResetService.java#L21)):*
> ```Java
> 
>   SLOErrorBudgetResetDTO resetErrorBudgetV2(ProjectParams projectParams, SLOErrorBudgetResetDTO sloErrorBudgetResetDTO);
> ```

what is the purpose of this method?


<!-- Sent from Reviewable.io -->

2022-10-21 03:17 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsXxG3-iOvtKPppWsL:-NEsXxG440XEfa2pXiC1:b9bzh5k) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L61)):*
> ```Java
> @ExposeInternalException
> @NextGenManagerAuth
> @Tag(name = "V2 SLOs", description = "This contains APIs related to CRUD operations of V2 SLOs")
> ```

remove tag annotation until API is tested and ready to be exposed to the outside world.


<!-- Sent from Reviewable.io -->

2022-10-21 08:57 UTC, karansaraswat19 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 1 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsUYcsBJlk5m8honTD:-NEtYGUQE6QSanenStyC:b-73i0hy) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java#L30)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

why are we using createV2? we have a method for create and update. API call for the Simple ServiceLevelObjective resource is already calling it. 
</blockquote></details>

create and update functions are just used for creating slos, for creating slis and sloHealthIndicators, v2 versions are being used which will be deleted later once we start using the new apis and the implementation inside the v2 functions will be shifted to those functions only
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLOErrorBudgetResetService.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsVE1K6Dm0kxbAcByP:-NEtXx6e5Hk75g0HN5gn:b514lq) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLOErrorBudgetResetService.java#L21)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

what is the purpose of this method?
</blockquote></details>

it requires the new entity abstractSLO inside this function
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/SLOV2Transformer.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpklXF9PAcM3DrHKgF:-NEtk4o5BR_psEuY1K0j:b7kb7td) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/SLOV2Transformer.java#L19)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Why do we need sli's as a separate param? We do have sli's in the DTO, you can save sli's and update the DTO and send that DTO as the param
</blockquote></details>

DTO requires List<ServiceLevelIndicatorDTO>, and then again in getSLOV2, List<String> will be needed. First I will have to convert String to DTO and then again to String; that's why I added a new param temporarily and will remove it afterwards.


<!-- Sent from Reviewable.io -->

2022-10-21 10:17 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 8 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/39050#-NEtsSja5bgi4kg6ZJ9o:-NEtsSja5bgi4kg6ZJ9p:bs11w83) ([raw file](https://github.com/harness/harness-core/blob/6b961f5ff13ee2ec47bc258bc2304a4e88aa22fa/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java#L55)):*
> ```Java
>     public void setUpdateOperations(UpdateOperations<CompositeServiceLevelObjective> updateOperations,
>         ServiceLevelObjectiveV2DTO serviceLevelObjectiveV2DTO) {
>       List<ServiceLevelObjectivesDetail> serviceLevelObjectivesDetailList =
> ```

Let's send the AbstractServiceLevelObjectiveV2 rather than DTO.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 258 at r2](https://reviewable.io/reviews/harness/harness-core/39050#-NEtwJ7Y6Ds3Rh4f55OG:-NEtwJ7Y6Ds3Rh4f55OH:beorngi) ([raw file](https://github.com/harness/harness-core/blob/6b961f5ff13ee2ec47bc258bc2304a4e88aa22fa/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L258)):*
> ```Java
>       @Parameter(description = CVConstants.SLO_PARAM_MESSAGE) @ApiParam(required = true) @NotNull @PathParam(
>           "identifier") @ResourceIdentifier String sloIdentifier) {
>     return new RestResponse<>(serviceLevelObjectiveService.getErrorBudgetResetHistory(projectParams, sloIdentifier));
> ```

Let's remove it from the PR. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsUYcsBJlk5m8honTD:-NEtwrApATzmTfXrHRU_:b-7vijfp) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java#L30)):*
<details><summary><i>Previously, karansaraswat19 (Karan Saraswat) wrote…</i></summary><blockquote>

create and update functions are just used for creating slos, for creating slis and sloHealthIndicators, v2 versions are being used which will be deleted later once we start using the new apis and the implementation inside the v2 functions will be shifted to those functions only
</blockquote></details>

Lets move the create SLI and update SLI to v2 and then just get and update the v1 entity.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/39050#-NEtzOdoDYbGHjITO0fP:-NEtzOdoDYbGHjITO0fQ:b-waxwgl) ([raw file](https://github.com/harness/harness-core/blob/6b961f5ff13ee2ec47bc258bc2304a4e88aa22fa/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java#L69)):*
> ```Java
>   SimpleServiceLevelObjective getFromSLIIdentifier(ProjectParams projectParams, String serviceLevelIndicatorIdentifier);
> 
>   List<SLOErrorBudgetResetDTO> getErrorBudgetResetHistory(ProjectParams projectParams, String sloIdentifier);
> ```

Lets remove it for now.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/39050#-NEu1oQA12dsCxFqYIs1:-NEu1oQA12dsCxFqYIs2:b-a1jhix) ([raw file](https://github.com/harness/harness-core/blob/6b961f5ff13ee2ec47bc258bc2304a4e88aa22fa/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java#L38)):*
> ```Java
>   @Override
>   public CompositeServiceLevelObjective getSLOV2(ProjectParams projectParams,
>       ServiceLevelObjectiveV2DTO serviceLevelObjectiveV2DTO, Boolean isEnabled, List<String> serviceLevelIndicators) {
> ```

Let's remove it from the signature. if required we should make a DB call from here to fetch the SLIs.


<!-- Sent from Reviewable.io -->

2022-10-27 08:03 UTC, AbhijithHarness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 20 file(s) to review. 3 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/AbstractServiceLevelObjective.java` line 169 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNKjOc2O0W7MUG9vuS:-NFNKjOc2O0W7MUG9vuT:b4jk446) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/AbstractServiceLevelObjective.java#L169)):*
> ```Java
> 
>   public abstract Optional<String> mayBeGetMonitoredServiceIdentifier();
>   public abstract static class AbstractServiceLevelObjectiveUpdatableEntity<T extends AbstractServiceLevelObjective, D
> ```

Just use 1 generic and it can implement UpdatableEntity<T, T>
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 133 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNOEji-gnPitp4UUiK:-NFNOEji-gnPitp4UUiL:b-enqgg) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L133)):*
> ```Java
>           (CompositeServiceLevelObjective) saveServiceLevelObjectiveV2Entity(
>               projectParams, serviceLevelObjectiveDTO, true);
>       sloHealthIndicatorService.upsert(compositeServiceLevelObjective);
> ```

the last 3 lines are common and should be outside if else condition.



_Code quote:_
```Java
      sloHealthIndicatorService.upsert(compositeServiceLevelObjective);
      return getSLOResponse(compositeServiceLevelObjective.getIdentifier(), projectParams);
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 478 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNQazuEUyiNonoD-YX:-NFNQazuEUyiNonoD-YY:b-42dhzz) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L478)):*
> ```Java
>     serviceLevelObjectiveTypeUpdatableEntityTransformerMap.get(serviceLevelObjectiveV2DTO.getType())
>         .setUpdateOperations(updateOperations,
>             serviceLevelObjectiveTypeSLOV2TransformerMap.get(serviceLevelObjectiveV2DTO.getType())
> ```

nit: we can move this to a private function, as it is getting used again and again.



_Code quote:_
```Java
            serviceLevelObjectiveTypeSLOV2TransformerMap.get(serviceLevelObjectiveV2DTO.getType())
                .getSLOV2(projectParams, serviceLevelObjectiveV2DTO, isSLOEnabled));
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 538 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNQwH15PbHDIlOKHop:-NFNQwH15PbHDIlOKHoq:bo8c6f1) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L538)):*
> ```Java
>   }
> 
>   private void validateCompositeSLO(ServiceLevelObjectiveV2DTO serviceLevelObjectiveDTO, ProjectParams projectParams) {
> ```

Validation should be done in the ServiceLevelObjectiveV2DTO, only, so that we dont need to call it at different places. 
Use : javax.validation.constraints.AssertTrue. Eg : https://github.com/harness/harness-core/blob/69c5639a212b61e9a97296ef4c01d49517cd4d8b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/yaml/NGEnvironmentInfoConfig.java#L69. Use multiple functions if required. 
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImplTest.java` line 1127 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNSq0b9Yp00K1GdiKF:-NFNSq0b9Yp00K1GdiKG:b37mewc) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImplTest.java#L1127)):*
> ```Java
>   }
> 
>   //  not valid now
> ```

Delete, dont comment out.


<!-- Sent from Reviewable.io -->

2022-10-27 08:19 UTC, AbhijithHarness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 20 file(s) to review. 3 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 246 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNW96B1VmBNy0i6C4j:-NFNW96C0MCkLjeik7rV:b267t80) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L246)):*
> ```Java
>   @Override
>   public boolean delete(ProjectParams projectParams, String identifier) {
>     AbstractServiceLevelObjective serviceLevelObjectiveV2 = getEntity(projectParams, identifier);
> ```

We need to check if SLOs are referred by any other compositeSLOs before deleting. If yes, we need to ask the user to edit the composite SLOs before deleting. 



_Code quote:_
```Java
  public boolean delete(ProjectParams projectParams, String identifier) {
    AbstractServiceLevelObjective serviceLevelObjectiveV2 = getEntity(projectParams, identifier);
    if (serviceLevelObjectiveV2 == null) {
      throw new InvalidRequestException(String.format(
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 545 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNUAPb6nSKpWiI6yiu:-NFNUAPb6nSKpWiI6yiv:bbqdd65) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L545)):*
> ```Java
>             .stream()
>             .peek(serviceLevelObjectiveDetailsDTO
>                 -> checkIfSLOPresent(serviceLevelObjectiveDetailsDTO.getServiceLevelObjectiveRef(), projectParams))
> ```

This check of checking if SLOs actually exists, we will have to keep in Service for now, but lets move the sum validation to DTO. 


<!-- Sent from Reviewable.io -->

2022-10-27 10:20 UTC, karansaraswat19 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 20 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 133 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNOEji-gnPitp4UUiK:-NFNxCix7LRMdj0O8VL1:b-grpdqx) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L133)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

the last 3 lines are common and should be outside if else condition.
</blockquote></details>

planning to move these to their entities
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 246 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNW96B1VmBNy0i6C4j:-NFNwxbF--A6-WVwmnQ5:b-oaby1j) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L246)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We need to check if SLOs are referred by any other compositeSLOs before deleting. If yes, we need to ask the user to edit the composite SLOs before deleting. 
</blockquote></details>

will pick this up in next PR.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 538 at r4](https://reviewable.io/reviews/harness/harness-core/39050#-NFNQwH15PbHDIlOKHop:-NFNx5k04vZgUl6C5lA9:barkvbh) ([raw file](https://github.com/harness/harness-core/blob/c365dd16a137b0313b3fc8b5ab9083b84c1765b9/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L538)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Validation should be done in the ServiceLevelObjectiveV2DTO, only, so that we dont need to call it at different places. 
Use : javax.validation.constraints.AssertTrue. Eg : https://github.com/harness/harness-core/blob/69c5639a212b61e9a97296ef4c01d49517cd4d8b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/yaml/NGEnvironmentInfoConfig.java#L69. Use multiple functions if required. 
</blockquote></details>

will pick this up in next PR


<!-- Sent from Reviewable.io -->

2022-10-27 18:06 UTC, karansaraswat19 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39050)* status: 20 file(s) to review. 3 change requests. 14. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEphrud9tbMTmSNY6It:-NFPbQ_vDpbmmCqG_SpX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d1cfbb24b144751cbb511e4e20618f2907a8bf6d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L52)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

why did we remove Apimodelproperty annotation?
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/39050#-NEtsSja5bgi4kg6ZJ9o:-NFPbTcW6cE1gHyqUdhs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b961f5ff13ee2ec47bc258bc2304a4e88aa22fa/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java#L55)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Let's send the AbstractServiceLevelObjectiveV2 rather than DTO.
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 258 at r2](https://reviewable.io/reviews/harness/harness-core/39050#-NEtwJ7Y6Ds3Rh4f55OG:-NFPbVSE883luXrFFn2H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b961f5ff13ee2ec47bc258bc2304a4e88aa22fa/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L258)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Let's remove it from the PR. 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEsUYcsBJlk5m8honTD:-NFPbWHeBkb47A411ahm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java#L30)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Lets move the create SLI and update SLI to v2 and then just get and update the v1 entity.
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/39050#-NEtzOdoDYbGHjITO0fP:-NFPbX4VCeTyhDXcVPh8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b961f5ff13ee2ec47bc258bc2304a4e88aa22fa/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/ServiceLevelObjectiveV2Service.java#L69)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Lets remove it for now.
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpk1--93buxWe4FauF:-NFPbYow35S1Ps2WeXaq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L113)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

sloHealthIndicator we have to update for compositeSLO as well.
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEplIy7Evs5M3YSmMzs:-NFPbbPX2SBpi_wC9hzL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L113)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

For composite SLO API, validation needs to be done before saving SLI.  
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 460 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpmPMA6XUCzMSo1Zx5:-NFPbkqg5wV0d7-udZD6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d1cfbb24b144751cbb511e4e20618f2907a8bf6d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L460)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

also add an assertion that total weightage percentage is 100
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 513 at r1](https://reviewable.io/reviews/harness/harness-core/39050#-NEpm8LJ0WY8ve0POykR:-NFPbk_w5a1khhfzCN5C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/614b2855422fdf2fd90a3b1feb1358b8f64a17cb/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L513)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Before saving the entity we need to verify that simple SLO exists for whichever simpleSLORefs we have added
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-28 06:14 UTC, closed without merging