fix: [CDS-40390]: added API for fetching helm chart versions
harness/harness-core pull request #39119
Opened 2022-10-21 16:29 UTC by achyuth-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-03 07:36 UTC, achyuth-harness commented
trigger ft1

2022-11-03 07:36 UTC, achyuth-harness commented
trigger ft2

2022-11-03 16:43 UTC, acasian-harness requested changes
> Reviewed 7 of 17 files at r1, 11 of 13 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyAjTd3W-HgZ3Hp9nb:-NFyAjTd3W-HgZ3Hp9nc:b-xffofi) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java#L42)):*
> ```Java
> @Slf4j
> 
> public class HelmChartVersionResource {
> ```

is this resource only dedicated to helm chart versions? in this case the api `helm/version` would make sense imho.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyA_eB0lJtdXbWyXEw:-NFyA_eB0lJtdXbWyXEx:b87itul) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java#L46)):*
> ```Java
>   private final ArtifactResourceUtils artifactResourceUtils;
>   @POST
>   @Path("getHelmChartVersionDetails")
> ```

why post method has a `get` name?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyH4ptCwU95uekTLQv:-NFyH4ptCwU95uekTLQw:b-cv8r5u) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java#L54)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.SERVICE_KEY) String serviceRef,
>       @NotNull @QueryParam("fqnPath") String fqnPath) {
>     HelmChartResponseDTO helmChartResponseDTO =
> ```

any rbac checks that we are missing?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartService.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyBMqw92bMtXJ4eZQV:-NFyBMqw92bMtXJ4eZQW:b-xcmjqw) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartService.java#L19)):*
> ```Java
>       HelmChartManifestOutcome helmChartManifestOutcome, String accountId, String orgId, String projectId);
> 
>   HelmVersion getHelmVersionBasedOnFF(HelmVersion helmVersion, String accountId);
> ```

why do we need `FF` name in interface? The consumer only asks about helmversion, either this method is redundant either it shouldn't be in interface.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyCVexET6jqOsCHO6e:-NFyCVexET6jqOsCHO6f:bn2o3ql) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L61)):*
> ```Java
>   @Inject private ExceptionManager exceptionManager;
> 
>   public HelmChartServiceImpl() {}
> ```

do we need it to declare?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 83 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyGs-F563EUwza-Atj:-NFyGs-F563EUwza-Atk:b-sy4rg8) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L83)):*
> ```Java
>                 && !cdFeatureFlagHelper.isEnabled(accountId, FeatureName.DISABLE_HELM_REPO_YAML_CACHE))
>             .checkIncorrectChartVersion(
>                 cdFeatureFlagHelper.isEnabled(accountId, FeatureName.HELM_CHART_VERSION_STRICT_MATCH))
> ```

don't we have a pr to get rid of this ff?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyD_8e9oRSA0PStoMh:-NFyD_8e9oRSA0PStoMi:b-nopoxo) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L106)):*
> ```Java
>                                                         .taskType(NGTaskType.HELM_FETCH_CHART_VERSIONS_TASK_NG.name())
>                                                         .taskParameters(helmFetchChartVersionRequestNG)
>                                                         .executionTimeout(java.time.Duration.ofSeconds(6000))
> ```

where is this timeout number coming from?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyI4Zr3GCLd_ZPdgQB:-NFyI4ZsDq3qMi9nI4uc:bf5tzco) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L107)):*
> ```Java
>                                                         .taskParameters(helmFetchChartVersionRequestNG)
>                                                         .executionTimeout(java.time.Duration.ofSeconds(6000))
>                                                         .taskSetupAbstractions(abstractions)
> ```

i don't see ng abstraction
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyIiKMEpFC7voLQy0Z:-NFyIiKMEpFC7voLQy0_:b-nro97v) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L108)):*
> ```Java
>                                                         .executionTimeout(java.time.Duration.ofSeconds(6000))
>                                                         .taskSetupAbstractions(abstractions)
>                                                         // ToDo: taskSelectors(helmChartManifestDelegateConfig.)
> ```

do we need to pick the selector from store config connector? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyGTUW-HBBRAVQQ59l:-NFyGTUW-HBBRAVQQ59m:blnz3mk) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L118)):*
> ```Java
>     }
> 
>     // ToDo: Need to do error handling correctly here!
> ```

what about error handling? :smile: 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 182 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyJSTNCrZ_etskrGc7:-NFyJSTNCrZ_etskrGc8:b50141s) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L182)):*
> ```Java
>     }
> 
>     throw new InvalidRequestException("Invalid/Unsupported store config type");
> ```

Unsupported is fine
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyKDfl18cwSKJIH5cH:-NFyKDfl18cwSKJIH5cI:b-3bt0sx) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e [...]

2022-11-03 16:45 UTC, acasian-harness reviewed
Please add unit tests for resource and service impl classes

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119#-:-NFyNK6wCeRSpLgz63Ej:b-jcygom)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-04 09:19 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: 5 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyAjTd3W-HgZ3Hp9nb:-NG09u2h9GM6HfLsjNP1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java#L42)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

is this resource only dedicated to helm chart versions? in this case the api `helm/version` would make sense imho.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyA_eB0lJtdXbWyXEw:-NG09v3fAzTmSIQwrv7z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java#L46)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why post method has a `get` name?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartService.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyBMqw92bMtXJ4eZQV:-NG0A91GBQht0HHGyfgm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartService.java#L19)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why do we need `FF` name in interface? The consumer only asks about helmversion, either this method is redundant either it shouldn't be in interface.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyCVexET6jqOsCHO6e:-NG0AFFg2S0wPw_vDgPK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L61)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

do we need it to declare?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 83 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyGs-F563EUwza-Atj:-NG0AHzfDSpxEHrsrEz4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L83)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

don't we have a pr to get rid of this ff?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyD_8e9oRSA0PStoMh:-NG0AkwL2FryjR1EfpSS:bvk8aq5) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L106)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

where is this timeout number coming from?
</blockquote></details>

Default timeout, created a var for the same
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyI4Zr3GCLd_ZPdgQB:-NG0B8-83CTJBKNuxyuJ:b-8b11j9) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L107)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i don't see ng abstraction
</blockquote></details>

Added
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyIiKMEpFC7voLQy0Z:-NG0F1CV-oJlbdb4ikeA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L108)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

do we need to pick the selector from store config connector? 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyGTUW-HBBRAVQQ59l:-NG0HmYU-u5mMzwX6qME:b3q5qbm) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L118)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

what about error handling? :smile: 
</blockquote></details>

Done. (Sorry, missed this 😅)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java` line 182 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyJSTNCrZ_etskrGc7:-NG0EOj10s6sZhwMmUrh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java#L182)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

Unsupported is fine
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyKDfl18cwSKJIH5cH:-NG0IQ816qEljGYf-PqF:b-tn6bt4) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java#L26)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

where is this exception coming from? 
</blockquote></details>

Removed it 😅
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyK0Y884lOtfU3Bg7H:-NG0IWKk2UgXYOsK5UD1:b-e6atrh) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java#L53)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

timeout should come from task params
</blockquote></details>

As this is an internal task, we don't have any task params for this. So using a default value (defined a static var) 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmFetchChartVersionTaskNG.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyKX5q0AjDG1CFDNtH:-NG0ulsV-QSlHU6P6U6A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/930-delegate-task [...]

2022-11-04 13:36 UTC, achyuth-harness reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119#-:-NG1qiys4xXOag_I0ULq:b-896fix)* status: 12 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/39119#-NFyH4ptCwU95uekTLQv:-NG1qkH69uKtxgeP7IqF:b-z1v515) ([raw file](https://github.com/harness/harness-core/blob/16cc282a9642c3e6386247c20bcd84b726c85ea9/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java#L54)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

any rbac checks that we are missing?
</blockquote></details>

As we discussed offline, not required for internal resource classes 


<!-- Sent from Reviewable.io -->

2022-11-04 15:36 UTC, acasian-harness submitted a review, later dismissed
> Reviewed 2 of 5 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-07 06:02 UTC, achyuth-harness commented
trigger messagecheck

2022-11-07 06:45 UTC, shubham-in10se approved these changes
> Reviewed 3 of 17 files at r1, 5 of 13 files at r2, 2 of 2 files at r3, 2 of 5 files at r4, 6 of 10 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 396 at r6](https://reviewable.io/reviews/harness/harness-core/39119#-NGFpGda3N9xCZJU17wX:-NGFpGda3N9xCZJU17wY:b-lha518) ([raw file](https://github.com/harness/harness-core/blob/a05f6816a089236e7045f2c6b583582bae3e88d2/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L396)):*
> ```Java
>   TRIGGER_AUTHENTICATION_TASK(TaskGroup.TRIGGER),
>   SPOT_TASK_NG(TaskGroup.SPOTINST, "Spot NG Task"),
>   HELM_FETCH_CHART_VERSIONS_TASK_NG(TaskGroup.HELM, "Fetch Helm Chart Versions Task"),
> ```

always add a new enum at the end of the list.
___
*[`970-ng-commons/src/main/java/io/harness/common/NGTaskType.java` line 35 at r6](https://reviewable.io/reviews/harness/harness-core/39119#-NGFpQtxBGH5xKBoe4fL:-NGFpQtxBGH5xKBoe4fM:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/a05f6816a089236e7045f2c6b583582bae3e88d2/970-ng-commons/src/main/java/io/harness/common/NGTaskType.java#L35)):*
> ```Java
>   CUSTOM_ARTIFACT_NG,
>   AZURE_ARTIFACT_TASK_NG,
>   HELM_FETCH_CHART_VERSIONS_TASK_NG,
> ```

same as above.


<!-- Sent from Reviewable.io -->

2022-11-07 07:09 UTC, inderschera approved these changes
> Reviewed 3 of 17 files at r1, 5 of 13 files at r2, 2 of 2 files at r3, 2 of 5 files at r4, 5 of 10 files at r5, 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1246 at r7](https://reviewable.io/reviews/harness/harness-core/39119#-NGFuO2I1ZbMsIYXEwf9:-NGFuO2I1ZbMsIYXEwfA:bdsr9tr) ([raw file](https://github.com/harness/harness-core/blob/43b96eb404dff226baa7535eb182db8e26c37ebc/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1246)):*
> ```Java
>     char[] password = getHttpHelmPassword(httpHelmConnector);
>     try {
>       removeRepo(storeDelegateConfig.getRepoName(), destinationDirectory, manifest.getHelmVersion(), timeoutInMillis,
> ```

why are we doing this first?


<!-- Sent from Reviewable.io -->

2022-11-07 07:17 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1246 at r7](https://reviewable.io/reviews/harness/harness-core/39119#-NGFuO2I1ZbMsIYXEwf9:-NGFwnvS977BbwOPT8GK:b-5c49qd) ([raw file](https://github.com/harness/harness-core/blob/43b96eb404dff226baa7535eb182db8e26c37ebc/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1246)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

why are we doing this first?
</blockquote></details>

Same behaviour in CG. so added this here too
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 396 at r6](https://reviewable.io/reviews/harness/harness-core/39119#-NGFpGda3N9xCZJU17wX:-NGFvfZV69nq42XcIk6h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a05f6816a089236e7045f2c6b583582bae3e88d2/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L396)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

always add a new enum at the end of the list.
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/common/NGTaskType.java` line 35 at r6](https://reviewable.io/reviews/harness/harness-core/39119#-NGFpQtxBGH5xKBoe4fL:-NGFvh3V5ldEYZUlg1aY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a05f6816a089236e7045f2c6b583582bae3e88d2/970-ng-commons/src/main/java/io/harness/common/NGTaskType.java#L35)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-07 08:40 UTC, shubham-in10se approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-07 08:41 UTC, achyuth-harness commented
trigger codebasehash

2022-11-07 08:46 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 17 files at r1, 5 of 13 files at r2, 2 of 2 files at r3, 2 of 5 files at r4, 5 of 10 files at r5, 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119#-:-NGGGFymDKzgIdr5d7kd:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-08 06:51 UTC, acasian-harness approved these changes
> Reviewed 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-08 06:54 UTC, acasian-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-08 07:56 UTC, inderschera approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39119)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-08 07:57 UTC, merged