fix: [CDS-44543]: Email step response builder
harness/harness-core pull request #39174
Opened 2022-10-25 07:57 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-28 12:20 UTC, shivamnegi94 commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +    String ccMail = emailStepParameters.cc.getValue();
Why ccMail and toMail are assigned to getValue()?

2022-10-28 13:15 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-10-28 13:19 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +    String ccMail = emailStepParameters.cc.getValue();
to present in emailparameters are parameter fields ,to get the string value,we have to use .getvalue()!

2022-10-28 15:49 UTC, shivamnegi94 approved these changes

2022-10-28 15:50 UTC, shivamnegi94 submitted a review, later dismissed

2022-10-28 17:55 UTC, puthrayaharness requested changes

2022-10-28 17:55 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +  private static final String INFRASTRUCTURE_COMMAND_UNIT = "Execute";
Please check if we can make do without passing command unit altogether.

2022-10-28 17:55 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +    } catch (SocketTimeoutException e) {
Let's not handle SockerTimeoutException separately. There is very little value that we are adding. Just catching IOException will do.

2022-10-28 17:55 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +      log.error("Not able to send emails", e.getCause());
`log.error("Not able to send emails", e);`

2022-10-28 17:55 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +      logCallback.saveExecutionLog(String.format("Not able to send email due to a internal error"), LogLevel.INFO,
Be a bit more verbose here. 
```
Failed to send the email. The reasons could be -
- Possible errors on the Harness side
- Delegate unable to reach custom SMTP server(if configured)
- The SMTP server may not be setup correctly(if configured)
```
You do not need to use the message as is, but please try to highlight all possible reasons why we could send the email. The reason for Sockertimeout would be the same. 

Let's merge IO & Sockertimeout error

2022-10-31 10:42 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +  private static final String INFRASTRUCTURE_COMMAND_UNIT = "Execute";
Yeah working!

2022-11-01 04:27 UTC, puthrayaharness approved these changes

2022-11-01 04:27 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +      return StepResponse.builder()
We should not have any outcomes for failed steps.

2022-11-01 04:27 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +                                       + "- Harness platform service might be not working\n"
Customer does not know what all microservices we have & they do not need to know what microservices we do have. 
rephrase the message as `Something went wrong on Harness's end.`
Put this as the last option & not the first option.

2022-11-01 04:31 UTC, puthrayaharness requested changes

2022-11-01 04:31 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/EmailStep.java
> +    NGLogCallback logCallback = new NGLogCallback(logStreamingStepClientFactory, ambiance, null, true);
Where are we closing the logCallback? Can we close the logCallback if the step is aborted?

2022-11-02 08:12 UTC, vivekkarnatiharness commented
trigger ti1

2022-11-02 08:12 UTC, vivekkarnatiharness commented
trigger ti2

2022-11-02 08:12 UTC, vivekkarnatiharness commented
trigger ti4

2022-11-02 16:58 UTC, vivekkarnatiharness commented
trigger compile

2022-11-02 16:59 UTC, vivekkarnatiharness commented
trigger ft1

2022-11-03 12:02 UTC, puthrayaharness approved these changes

2022-11-03 12:03 UTC, puthrayaharness approved these changes
> Reviewed 3 of 8 files at r1, 4 of 6 files at r2, 4 of 5 files at r4, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39174)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-03 12:03 UTC, puthrayaharness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39174)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-03 12:39 UTC, naman-goenka approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39174)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-03 12:39 UTC, naman-goenka approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39174)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-03 12:40 UTC, naman-goenka approved these changes
> Reviewed 3 of 8 files at r1, 3 of 6 files at r2, 4 of 5 files at r4, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39174)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-04 03:36 UTC, shivamnegi94 reviewed
> Reviewed 3 of 8 files at r1, 3 of 6 files at r2, 4 of 5 files at r4, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39174)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-04 03:37 UTC, shivamnegi94 approved these changes

2022-11-04 03:40 UTC, shivamnegi94 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39174)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-04 03:46 UTC, merged