feat: [PIE-5911]: Create new endpoint for trigger/pipeline input reconcilation
harness/harness-core pull request #39199
Opened 2022-10-25 23:18 UTC by vcalasansh

This PR implements a new API in pipeline-service's `triggers` resource for retrieving both the trigger and pipeline's input YAMLs for reconciliation purposes.

The new API may be called as `/pipeline/api/triggers/{triggerIdentifier}/triggerInputReconciliation?accountIdentifier={accountIdentifier}&orgIdentifier={orgIdentifier}&projectIdentifier={projectIdentifier}&targetIdentifier={pipelineIdentifier}`

## Describe your changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-27 05:34 UTC, sribalij commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +      return NGTriggerInputsReconciliationDTO.builder()
Can we return the old yaml and new yaml instead of just the runtime inputs?.
Please check io.harness.pms.ngpipeline.inputset.resources.InputSetResourcePMS#getInputSetYAMLDiff

2022-11-17 18:14 UTC, sribalij commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +    } else {
@vcalasansh Can you make sure this is not happening?
If pipeline is inline and has input sets - Make sure to store inline ref of the input set  (Currently the pipeline inline values are copied to trigger)

2022-11-17 18:15 UTC, sribalij submitted a review, later dismissed

2022-11-17 21:44 UTC, sribalij approved these changes
> Reviewed 2 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-17 21:44 UTC, sribalij approved these changes
> Reviewed 13 of 18 files at r2, 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-18 17:38 UTC, sribalij approved these changes
> Reviewed 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 21 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-23 17:16 UTC, archit-harness requested changes
> Reviewed 4 of 20 files at r2, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 217 at r9](https://reviewable.io/reviews/harness/harness-core/39199#-NH_TzEr9RTo4m2GgBO5:-NH_TzEt3XKi0XB1Z8af:b-ldipei) ([raw file](https://github.com/harness/harness-core/blob/2259577a964876776f5250ff0ad526743543621c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L217)):*
> ```Java
>         && isEmpty(triggerDetails.getNgTriggerConfigV2().getPipelineBranchName())
>         && isEmpty(triggerDetails.getNgTriggerConfigV2().getInputSetRefs())) {
>       // Only validate pipeline inputs if trigger is not for remote pipeline and not using input sets
> ```

where are you checking this?



_Code quote:_
```Java
// Only validate pipeline inputs if trigger is not for remote pipeline and not using input
```
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1095 at r3](https://reviewable.io/reviews/harness/harness-core/39199#-NFGR8JrExWZFkiTuWgQ-r3-1095:-NH_UNj9Ay6kLbFrZmiR:b-onr4ue) ([raw file](https://github.com/harness/harness-core/blob/88d7239049ae0c30a3e6e13acc54771fbad529de/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1095)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

@vcalasansh Can you make sure this is not happening?
If pipeline is inline and has input sets - Make sure to store inline ref of the input set  (Currently the pipeline inline values are copied to trigger)
</blockquote></details>

Do we need to introduce trigger reconcillation before git caching comes into picture?
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1027 at r9](https://reviewable.io/reviews/harness/harness-core/39199#-NH_UBUJ7xUZHC0z4ANW:-NH_UBUJ7xUZHC0z4ANX:brv0jet) ([raw file](https://github.com/harness/harness-core/blob/2259577a964876776f5250ff0ad526743543621c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1027)):*
> ```Java
>   }
> 
>   private String getUpdatedTriggerPipelineComponent(String triggerPipelineYaml, String templateYaml) {
> ```

what are we trying to achieve here?


<!-- Sent from Reviewable.io -->

2022-11-24 20:13 UTC, vcalasansh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 217 at r9](https://reviewable.io/reviews/harness/harness-core/39199#-NH_TzEr9RTo4m2GgBO5:-NHfFO_s2spmXPyCKrv0:bwwx5ya) ([raw file](https://github.com/harness/harness-core/blob/2259577a964876776f5250ff0ad526743543621c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L217)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where are you checking this?
</blockquote></details>

Thank you for the comment! We are checking in the `if` condition just above this line. We are only proceeding with checking the validity of the trigger inputs if trigger has no reference to input set and no pipeline branch name (which I suppose is only for git synced pipelines).
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1095 at r3](https://reviewable.io/reviews/harness/harness-core/39199#-NFGR8JrExWZFkiTuWgQ-r3-1095:-NHfGNAY-dkW6vFy0_d6:befll0v) ([raw file](https://github.com/harness/harness-core/blob/88d7239049ae0c30a3e6e13acc54771fbad529de/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1095)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Do we need to introduce trigger reconcillation before git caching comes into picture?
</blockquote></details>

I am not aware of git caching. Will with you about this.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1027 at r9](https://reviewable.io/reviews/harness/harness-core/39199#-NH_UBUJ7xUZHC0z4ANW:-NHfFrZP78wuwVcm9fMz:b-a6uhtv) ([raw file](https://github.com/harness/harness-core/blob/2259577a964876776f5250ff0ad526743543621c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1027)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what are we trying to achieve here?
</blockquote></details>

This method is for updating the pipeline input in trigger's yaml to be according to the pipeline's input. For example, if after creating a trigger, we add/remove or change type of some of the pipeline's variables, this method will generate a trigger input yaml that "fixes" the previously existing one. This will be used to create a reconciliation feature in the UI for triggers, just like we have for input sets. 


<!-- Sent from Reviewable.io -->

2022-11-24 20:13 UTC, vcalasansh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1003 at r1](https://reviewable.io/reviews/harness/harness-core/39199#-NFGR8JrExWZFkiTuWgQ-r1-1003:-NHfGZP17YnmVW0Lmno4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5ac88122449ba67e86896df39370256ddbf049c2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1003)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Can we return the old yaml and new yaml instead of just the runtime inputs?.
Please check io.harness.pms.ngpipeline.inputset.resources.InputSetResourcePMS#getInputSetYAMLDiff
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-06 15:09 UTC, archit-harness approved these changes
> Reviewed 10 of 20 files at r2, 3 of 6 files at r7, 1 of 2 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 4 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java` line 619 at r10](https://reviewable.io/reviews/harness/harness-core/39199#-NIbyvL43ce_0lYl-4af:-NIbyvL43ce_0lYl-4ag:b966wi2) ([raw file](https://github.com/harness/harness-core/blob/abbaeafbe23d5fa255b276cfc20b7cbc029710a4/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java#L619)):*
> ```Java
>                                                      .disable(USE_NATIVE_TYPE_ID));
>     objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
>     return objectMapper;
> ```

Maybe use YamlUtils 953 yaml-commons mapper



_Code quote:_
```Java
  public ObjectMapper getObjectMapper() {
    ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory()
                                                     .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES)
                                                     .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
                                                     .disable(USE_NATIVE_TYPE_ID));
    objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    return objectMapper;
```


<!-- Sent from Reviewable.io -->

2022-12-08 14:35 UTC, archit-harness reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-08 14:38 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 4 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java` line 619 at r10](https://reviewable.io/reviews/harness/harness-core/39199#-NIbyvL43ce_0lYl-4af:-NIm9xMQ7mc1VQp0OsSY:b-9zrv31) ([raw file](https://github.com/harness/harness-core/blob/abbaeafbe23d5fa255b276cfc20b7cbc029710a4/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java#L619)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

Thanks for the comment! But I think we can't use 953 yaml-commons YamlUtils'  ObjectMapper here because it is using different configuration from this one. Just to be clear, this piece of code (creation of this ObjectMapper) was being repeated a few times in trigger's code. What is move it to a new method, to avoid code repetition.
</blockquote></details>

@sribalij @vcalasansh we should have ticket in triggers to remove all new object mappers as its costly on the fly plus its not consistent


<!-- Sent from Reviewable.io -->

2022-12-08 17:54 UTC, sribalij approved these changes
> Reviewed 2 of 2 files at r9, 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39199)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-08 19:32 UTC, merged