fix: [CI-5959]: 100 builds per day for free users
harness/harness-core pull request #39258
Opened 2022-10-26 23:08 UTC by jamie-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-26 23:22 UTC, hemanthmantri commented on 925-enforcement-service/src/main/resources/features/ci_features.yml
> +        enabled: true
Do we need to add TEAM and ENTERPRISE here?

2022-10-26 23:22 UTC, hemanthmantri commented on 925-enforcement-service/src/main/resources/features/ci_features.yml
> +    description: The restriction on number of builds per day
Number of stages, right?

2022-10-26 23:23 UTC, jamie-harness commented on 925-enforcement-service/src/main/resources/features/ci_features.yml
> +        enabled: true
It is here right?

2022-10-27 01:36 UTC, hemanthmantri approved these changes

2022-10-27 01:36 UTC, hemanthmantri commented on 925-enforcement-service/src/main/resources/features/ci_features.yml
> +        enabled: true
I meant we don't have to add them here if nothing is restricted for them. So I was checking if the lines 90-95 are really needed.

2022-10-27 01:38 UTC, jamie-harness commented on 925-enforcement-service/src/main/resources/features/ci_features.yml
> +        enabled: true
oh yes they are needed. These lines means they are unrestricted

2022-10-27 03:51 UTC, archit-harness requested changes
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39258)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java` line 165 at r3](https://reviewable.io/reviews/harness/harness-core/39258#-NFMZ1Iu-4R6fZ1-fhhG:-NFMZ1Iw8XMqdilPZ0nU:bikiq5) ([raw file](https://github.com/harness/harness-core/blob/8440e76af1b239adf0fe2af8146742c75b19fb15/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java#L165)):*
> ```Java
>       } else if (module.equalsIgnoreCase(ModuleType.CI.name())) {
>         featureRestrictionToStepNameMap.put(FeatureRestrictionName.BUILDS.name(), BUILD_EXCEEDED_KEY);
>         featureRestrictionToStepNameMap.put(FeatureRestrictionName.DAILY_BUILDS.name(), BUILD_EXCEEDED_KEY);
> ```

@sahilhindwani-harness i think adding here only handles daily builds equal to pipeline execution and not ci stage is it correct?


<!-- Sent from Reviewable.io -->

2022-10-27 04:17 UTC, jamie-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39258)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java` line 165 at r3](https://reviewable.io/reviews/harness/harness-core/39258#-NFMZ1Iu-4R6fZ1-fhhG:-NFMdbju8fWDTA35_ias:b-l3uu4d) ([raw file](https://github.com/harness/harness-core/blob/8440e76af1b239adf0fe2af8146742c75b19fb15/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java#L165)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@sahilhindwani-harness i think adding here only handles daily builds equal to pipeline execution and not ci stage is it correct?
</blockquote></details>

This is where the enforcement happens, it would check the enforcement number and block the execution. The enforcement number comes from CI manager and it is counting CI stages. 


<!-- Sent from Reviewable.io -->

2022-10-27 05:19 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java` line 165 at r3](https://reviewable.io/reviews/harness/harness-core/39258#-NFMZ1Iu-4R6fZ1-fhhG:-NFMsApb3gfeGAl7tE-H:bvuk2pf) ([raw file](https://github.com/harness/harness-core/blob/8440e76af1b239adf0fe2af8146742c75b19fb15/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java#L165)):*
<details><summary><i>Previously, jamie-harness (Jamie Li) wrote…</i></summary><blockquote>

The count increase happens in PipelineExecutionUpdateEventHandler
</blockquote></details>

@jamie-harness , I don't think it happens per stage now. It is CIPipelineEndEventHandler where the count is increasing which get's called when the pipeline execution ends.


<!-- Sent from Reviewable.io -->

2022-10-27 05:22 UTC, jamie-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39258)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java` line 165 at r3](https://reviewable.io/reviews/harness/harness-core/39258#-NFMZ1Iu-4R6fZ1-fhhG:-NFMss1O9U249JL0P1XW:bhmtfcn) ([raw file](https://github.com/harness/harness-core/blob/8440e76af1b239adf0fe2af8146742c75b19fb15/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java#L165)):*
> PipelineExecutionUpdateEventHandler
@sahilhindwani-harness It's in handlerMap.put(NODE_EXECUTION_STATUS_UPDATE, Sets.newHashSet(PipelineExecutionUpdateEventHandler.class)); There are two calls. The daily one is in PipelineExecutionUpdateEventHandler. Which takes in NODE_EXECUTION_STATUS_UPDATE and filter out the steps only adding in stage end


<!-- Sent from Reviewable.io -->

2022-10-27 07:16 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/enforcement/BuildsPerDayRestrictionUsageImpl.java
> +    String day = yearMonth + "-" + startDate.getDayOfMonth();
What about next yr. It might put restriction next yr too.

2022-10-27 07:23 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java
> +        && level.getStepType().getStepCategory() == StepCategory.STAGE && isFinalStatus(status)) {
Let us use Queued status and not wait for final status.
What if execution takes more than 24 hr.

2022-10-27 07:28 UTC, archit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39258)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java` line 165 at r3](https://reviewable.io/reviews/harness/harness-core/39258#-NFMZ1Iu-4R6fZ1-fhhG:-NFNKmJ76xE3tSAZdlub:b-lfmamq) ([raw file](https://github.com/harness/harness-core/blob/8440e76af1b239adf0fe2af8146742c75b19fb15/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java#L165)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@jamie-harness @harshjain12 the license change in ci_features, that would need ng manager to be deployed, it will be treated as major release
cc: @naidu-harness @sahilhindwani-harness 
</blockquote></details>

Please impl local change for now, if the license info is not available


<!-- Sent from Reviewable.io -->

2022-10-27 16:26 UTC, jamie-harness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/enforcement/BuildsPerDayRestrictionUsageImpl.java
> +    String day = yearMonth + "-" + startDate.getDayOfMonth();
we are not

2022-10-27 16:27 UTC, jamie-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39258)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java` line 165 at r3](https://reviewable.io/reviews/harness/harness-core/39258#-NFMZ1Iu-4R6fZ1-fhhG:-NFPG9Jr8XVdSq_lUxMu:bl2dbru) ([raw file](https://github.com/harness/harness-core/blob/8440e76af1b239adf0fe2af8146742c75b19fb15/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEnforcementServiceImpl.java#L165)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please impl local change for now, if the license info is not available
</blockquote></details>

Will re-open after Harsh's hotfix without licensing are in, and do it properly via licensing


<!-- Sent from Reviewable.io -->

2022-10-29 00:35 UTC, jamie-harness commented
Closed, re-implemented on @harshjain12 change
https://github.com/harness/harness-core/pull/39370/files

2022-10-29 00:35 UTC, closed without merging