feat: [CDS-42950]: Support for Nexus3 Trigger
harness/harness-core pull request #39261
Opened 2022-10-27 05:04 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-03 09:53 UTC, vtxorxwitty commented on 125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/NexusRegistryArtifactInfo.java
>        NexusRegistryDockerConfig nexusRegistryDockerConfig =
Can we take out common setters for all the type here and keep only things which are repository format specific in the if-else.

2022-11-03 09:55 UTC, vtxorxwitty reviewed
> Reviewed 1 of 7 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39261)* status: 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-03 09:56 UTC, vtxorxwitty submitted a review, later dismissed
You can ignore the comment if we can't proceed it that way. Approving the PR. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39261#-:-NFwuomA0g02jRHf9Prm:bitq6tm)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-03 09:59 UTC, puthrayaharness requested changes

2022-11-03 09:59 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/NexusRegistryArtifactInfo.java
> +      return NexusRegistryArtifactConfig.builder()
We can refactor this code. NexusRegistryArtifactConfig can move down.
Have a top-level variable for spec. Just initialize the spec based on repo format

2022-11-07 02:49 UTC, puthrayaharness approved these changes

2022-11-07 03:20 UTC, shivamnegi94 commented
trigger compile

2022-11-07 06:12 UTC, vaibhav-si approved these changes
> Reviewed 3 of 9 files at r2, 41 of 41 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39261)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-07 06:16 UTC, abhinavmittal-harness approved these changes
> Reviewed 3 of 9 files at r2, 41 of 41 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39261)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-07 07:05 UTC, deepak-harness approved these changes
> Reviewed 3 of 9 files at r2, 41 of 41 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39261)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-07 07:06 UTC, merged