fix: [PL-27990]: Added token lookup call while validating vault config
harness/harness-core pull request #39310
Opened 2022-10-27 17:21 UTC by VikasMaddukuriHarness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-10-28 11:27 UTC, gn-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 19 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 424 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTKlOOASxfwtgPQAA5:-NFTKlOOASxfwtgPQAA6:b-x9oxao) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L424)):*
> ```Java
>     // the interval based on that
>     if (isTokenBased(vaultConfig) && (vaultConfig.getRenewalInterval() != 0)) {
>       modifyRenewalIntervalBasedOnTokenLookup(vaultConfig);
> ```

are we modifying something here?



_Code quote:_
```Java
modifyR
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTH16--H3vSUQgNqje:-NFTH16--H3vSUQgNqjf:bad4029) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L261)):*
> ```Java
>     while (true) {
>       try {
>         NGVaultRenewalTaskParameters parameters =
> ```

why reusing the renewal task parameters here?



_Code quote:_
```Java
NGVaultRenewalTaskParameters
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 373 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTEnC43TU5JRPL03Sr:-NFTEnC43TU5JRPL03Ss:b-olav63) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L373)):*
> ```Java
>                                                   .projectIdentifier(projectIdentifier)
>                                                   .build())
>                                   .build();
> ```

Let's extract this logic in a common helper. I remember this was the same logic used in the processAppRole function too and we had bugs when we missed setting a few fields



_Code quote:_
```Java
    ConnectorInfoDTO connectorInfo = connectorDTO.getConnectorInfo();
    VaultConnectorDTO vaultConnectorDTO = (VaultConnectorDTO) connectorInfo.getConnectorConfig();

    SecretRefData secretRefData = vaultConnectorDTO.getAuthToken();
    String orgIdentifier = connectorInfo.getOrgIdentifier();
    String projectIdentifier = connectorInfo.getProjectIdentifier();
    decryptSecretRefData(accountIdentifier, orgIdentifier, projectIdentifier, secretRefData);
    VaultConfig vaultConfig = VaultConfig.builder()
                                  .accountId(accountIdentifier)
                                  .name(connectorInfo.getName())
                                  .vaultUrl(vaultConnectorDTO.getVaultUrl())
                                  .authToken(String.valueOf(secretRefData.getDecryptedValue()))
                                  .namespace(vaultConnectorDTO.getNamespace())
                                  .ngMetadata(NGSecretManagerMetadata.builder()
                                                  .accountIdentifier(accountIdentifier)
                                                  .orgIdentifier(orgIdentifier)
                                                  .projectIdentifier(projectIdentifier)
                                                  .build())
                                  .build();
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTE23H6tLZNAkKcnHY:-NFTE23I1rwBp9KdQFa8:b-xy5qup) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java#L49)):*
> ```Java
>       String accountIdentifier, boolean create);
> 
>   void processTokenLookup(ConnectorDTO connectorDTO, String accountIdentifier);
> ```

nit: validateTokenRenewalInterval 

if you change it, update isTokenLookupInputValid too



_Code quote:_
```Java
processTokenLookup
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTCN131kbZRMq5bh_s:-NFTCN131kbZRMq5bh_t:b-p4p0vi) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java#L51)):*
> ```Java
>   void processTokenLookup(ConnectorDTO connectorDTO, String accountIdentifier);
> 
>   VaultTokenLookupResult tokenLookup(BaseVaultConfig vaultConfig);
> ```

Please add java docs to both of these functions. More detailed the merrier



_Code quote:_
```Java
  void processTokenLookup(ConnectorDTO connectorDTO, String accountIdentifier);

  VaultTokenLookupResult tokenLookup(BaseVaultConfig vaultConfig);
```


<!-- Sent from Reviewable.io -->

2022-10-31 02:27 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 19 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 424 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTKlOOASxfwtgPQAA5:-NFfrF0Z6lz8svkVINyO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L424)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

are we modifying something here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-31 11:52 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 19 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 373 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTEnC43TU5JRPL03Sr:-NFhsiEgBdABHGCO7VTw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L373)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Let's extract this logic in a common helper. I remember this was the same logic used in the processAppRole function too and we had bugs when we missed setting a few fields
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-01 21:44 UTC, Raghav-Murali commented on 400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java
> +          "The token used is a root token. Please set renewal interval as zero if you are using root token.");
Should we update the VaultSecretManagerRenewalHandler iterator query filter to exclude the documents that have renewal interval as 0 ? Else the iterator will keep trying to renew the token despite these tokens being non-renewable.

2022-11-02 03:48 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 19 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 396 at r4](https://reviewable.io/reviews/harness/harness-core/39310#-NFPSh_BMc4onM3IVFH9-r4-396:-NFqRlvbAzriDi6UU4tL:bhgq70x) ([raw file](https://github.com/harness/harness-core/blob/b35f5938b1e5f6438a36491e0de00df8ad76f37f/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L396)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Should we update the VaultSecretManagerRenewalHandler iterator query filter to exclude the documents that have renewal interval as 0 ? Else the iterator will keep trying to renew the token despite these tokens being non-renewable. 
</blockquote></details>

Adding the renewalInterval in query will require new index creation. We already have logic of not renewing the token when renewalInterval is set to zero in the VaultSecretManagerRenewalHandler.


<!-- Sent from Reviewable.io -->

2022-11-02 09:13 UTC, VikasMaddukuriHarness commented
trigger compile

2022-11-02 12:28 UTC, VikasMaddukuriHarness commented
trigger tin1, tin2, tin3, tin4, tin0

2022-11-14 06:15 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 22 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTH16--H3vSUQgNqje:-NGojxHd0HF6Q1R_kOx3:bm1vhy5) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L261)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

why reusing the renewal task parameters here?
</blockquote></details>

Renewal task parameter are similar to the task params that are required for token lookup. The same is the case for NgFetch engine task. Almost all vault operations use the same task parameters, which is essentially just checking the ability of delegate to reach vault. Probably we should modify the name of renewalTaskparameters to simply vault parameters or something. 
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTE23H6tLZNAkKcnHY:-NGol1kZ10Z0z-Galmtq:b-adht9b) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java#L49)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: validateTokenRenewalInterval 

if you change it, update isTokenLookupInputValid too
</blockquote></details>

I thought that will be similar to processAppRole. We can take this up later.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTCN131kbZRMq5bh_s:-NGolty-6VmT0HR3d9Dy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/services/NGVaultService.java#L51)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Please add java docs to both of these functions. More detailed the merrier
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-14 08:03 UTC, gn-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 22 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/BaseVaultServiceImpl.java` line 202 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp6ACX-gKZIZRk4HQW:-NGp6ACY-95KnAU-sEVn:bvwd6e5) ([raw file](https://github.com/harness/harness-core/blob/ae95643faefbaf6d96ed35ad717d7ee54f2b6767/400-rest/src/main/java/software/wings/service/impl/security/BaseVaultServiceImpl.java#L202)):*
> ```Java
>     //          "The token used is a non-renewable token. Please set renewal interval as zero or use a renewable token.
>     //          This if for this vault {}", baseVaultConfig.getUuid());
>     //    }
> ```

either remove this or leave a comment on why this is commented out / leave a link to the comment you posted on the jira



_Code quote:_
```Java
    // vault token lookup
    //    VaultTokenLookupResult tokenLookupResult = tokenLookup(decryptedVaultConfig);
    //    if (tokenLookupResult != null && tokenLookupResult.getExpiryTime() == null) {
    //      // this means this is root token
    //      // set the renewal interval as zero
    //      log.info("The token used is a root token. Updating the renewal interval as zero.");
    //      wingsPersistence.updateField(
    //          SecretManagerConfig.class, baseVaultConfig.getUuid(), BaseVaultConfigKeys.renewalInterval, 0L);
    //      return;
    //    }
    //    if (tokenLookupResult != null && !tokenLookupResult.isRenewable()) {
    //      // this means the token is not renewable
    //      log.info(
    //          "The token used is a non-renewable token. Please set renewal interval as zero or use a renewable token.
    //          This if for this vault {}", baseVaultConfig.getUuid());
    //    }
```
___
*[`400-rest/src/main/java/software/wings/service/intfc/security/VaultService.java` line 45 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp6sPM8d24EAyQ_TCj:-NGp6sPM8d24EAyQ_TCk:b-7bmciy) ([raw file](https://github.com/harness/harness-core/blob/ae95643faefbaf6d96ed35ad717d7ee54f2b6767/400-rest/src/main/java/software/wings/service/intfc/security/VaultService.java#L45)):*
> ```Java
>   void renewToken(BaseVaultConfig baseVaultConfig);
> 
>   VaultTokenLookupResult tokenLookup(BaseVaultConfig baseVaultConfig);
> ```

nit: Please add java doc on any public method / interface



_Code quote:_
```Java
 VaultTokenLook
```
___
*[`400-rest/src/test/java/software/wings/service/VaultTest.java` line 2218 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp79AV1Zf9Z9AXGgDp:-NGp79AV1Zf9Z9AXGgDq:bbnwkzv) ([raw file](https://github.com/harness/harness-core/blob/ae95643faefbaf6d96ed35ad717d7ee54f2b6767/400-rest/src/test/java/software/wings/service/VaultTest.java#L2218)):*
> ```Java
>   @Owner(developers = VIKAS_M)
>   @Category(UnitTests.class)
>   public void save_tokenBasedAuth_withRootToken_shouldFail() {
> ```

nit:_withNonZeroRenewInterval_...



_Code quote:_
```Java
_s
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/39310#-NFTH16--H3vSUQgNqje:-NGp7PLcBpzgQTRh2WWW:b7aqnt0) ([raw file](https://github.com/harness/harness-core/blob/76a58b78797cfce6e10a40a8c76f81b724a0e0e6/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L261)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

Renewal task parameter are similar to the task params that are required for token lookup. The same is the case for NgFetch engine task. Almost all vault operations use the same task parameters, which is essentially just checking the ability of delegate to reach vault. Probably we should modify the name of renewalTaskparameters to simply vault parameters or something. 
</blockquote></details>

nit: Please add a comment on NGVaultRenewalTaskParameters, that is a misnomer or just create another PR after this to fix it :)
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 377 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp7rOA1_olfTPvcUMc:-NGp7rOA1_olfTPvcUMd:b-knbatr) ([raw file](https://github.com/harness/harness-core/blob/ae95643faefbaf6d96ed35ad717d7ee54f2b6767/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L377)):*
> ```Java
>     SecretRefData secretRefData = vaultConnectorDTO.getAuthToken();
>     String orgIdentifier = connectorInfo.getOrgIdentifier();
>     String projectIdentifier = connectorInfo.getProjectIdentifier();
> ```

nit: see if you can inline them and get rid of  the extra variables



_Code quote:_
```Java
    SecretRefData secretRefData = vaultConnectorDTO.getAuthToken();
    String orgIdentifier = connectorInfo.getOrgIdentifier();
    String projectIdentifier = connectorInfo.getProjectIdentifier();
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 412 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp83WnCXeIXiXjeCkz:-NGp83WnCXeIXiXjeCl-:b-b3oj4z) ([raw file](https://github.com/harness/harness-core/blob/ae95643faefbaf6d96ed35ad717d7ee54f2b6767/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L412)):*
> ```Java
>     SecretRefData secretRefData = vaultConnectorDTO.getSecretId();
>     String orgIdentifier = connectorInfo.getOrgIdentifier();
>     String projectIdentifier = connectorInfo.getProjectIdentifier();
> ```

nit: here also



_Code quote:_
```Java
    String orgIdentifier = connectorInfo.getOrgIdentifier();
    String projectIdentifier = connectorInfo.getProjectIdentifier();
```
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java` line 188 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp8MEk-IKABQJItrI0:-NGp8MEk-IKABQJItrI1:bxs3jvi) ([raw file](https://github.com/harness/harness-core/blob/ae95643faefbaf6d96ed35ad717d7ee54f2b6767/440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java#L188)):*
> ```Java
>   @Owner(developers = VIKAS_M)
>   @Category(UnitTests.class)
>   public void processTokenLookup_nonVaultTypeConnector_doesNoeExecuteAnyDelegateTask() throws IOException {
> ```

nit: typo



_Code quote:_
```Java
oe
```
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java` line 202 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp8W2Y9YHnkF2BTFIC:-NGp8W2Y9YHnkF2BTFID:b-quu5ng) ([raw file](https://github.com/harness/harness-core/blob/ae95643faefbaf6d96ed35ad717d7ee54f2b6767/440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java#L202)):*
> ```Java
> 
>     // Assert.
>     verify(delegateService, times(0)).executeSyncTask(any());
> ```

Very neat, good job!



_Code quote:_
```Java
    ConnectorDTO inputConnector = ConnectorDTO.builder()
                                      .connectorInfo(ConnectorInfoDTO.builder()
                                                         .name(CONNECTOR_NAME)
                                                         .identifier(CONNECTOR_ID)
                                                         .connectorType(ConnectorType.AWS)
                                                         .build())
                                      .build();
    setUpCommonMocks();

    // Act.
    ngVaultService.processTokenLookup(inputConnector, ACCOUNT_IDENTIFIER);

    // Assert.
    verify(delegateService, times(0)).executeSyncTask(any());
```
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java` line 262 at r7](https://reviewable.io/reviews/harness/harness-core/39310#-NGp8lUEBYJIJ5ympOcM:-NGp [...]

2022-11-17 07:20 UTC, gn-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 22 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-22 12:57 UTC, nishantsaini20 requested changes
> Reviewed 5 of 12 files at r1, 4 of 12 files at r2, 1 of 4 files at r3, 1 of 4 files at r5, 1 of 6 files at r6, 2 of 7 files at r7, 1 of 4 files at r8, 1 of 4 files at r9, 5 of 5 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 23 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 396 at r3](https://reviewable.io/reviews/harness/harness-core/39310#-NFghvib2Ba6n45rE-aD:-NFghvib2Ba6n45rE-aE:b-u26436) ([raw file](https://github.com/harness/harness-core/blob/b3e0f0bbfea0c1b52072ec15934a1be67d5a93f6/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L396)):*
> ```Java
>       // this means this is root token
>       throw new SecretManagementException(
>           "The token used is a root token. Please set renewal interval as zero if you are using root token.");
> ```

Is expiry time null a sufficient condition to conclude that token is root token? Will any other token which is non-renewable not have null expiry time?
___
*[`400-rest/src/test/java/software/wings/service/VaultTest.java` line 2227 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUKKne70RQDjAHs4eA:-NHUKKne70RQDjAHs4eB:b-drv5bl) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/400-rest/src/test/java/software/wings/service/VaultTest.java#L2227)):*
> ```Java
>     try {
>       vaultService.saveOrUpdateVaultConfig(accountId, vaultConfig, false);
>     } catch (Exception ex) {
> ```

use ExpectedException instead of try catch block.
___
*[`400-rest/src/test/java/software/wings/service/VaultTest.java` line 2251 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUKaoi6vG6V3RdboWC:-NHUKaoi6vG6V3RdboWD:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/400-rest/src/test/java/software/wings/service/VaultTest.java#L2251)):*
> ```Java
>     try {
>       vaultService.saveOrUpdateVaultConfig(accountId, vaultConfig, false);
>     } catch (Exception ex) {
> ```

Same here
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 57 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHULB1t9lnkaxtZtbV1:-NHULB1t9lnkaxtZtbV2:b-crem8h) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L57)):*
> ```Java
>   String secretIdRef;
>   @FdIndex @NonFinal Long nextTokenRenewIteration;
>   @Getter(AccessLevel.NONE) @Setter @NonFinal Long renewalIntervalMinutes;
> ```

Why this is required?



_Code quote:_
```Java
@Setter
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 444 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUMMpG02QzsbDoDa4V:-NHUMMpH---wRFWJSSHW:bl69oaf) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L444)):*
> ```Java
>   }
> 
>   private boolean isTokenLookupInputValid(ConnectorDTO connectorDTO) {
> ```

Rather than validation its mainly decision whether or not lookup call is required or not.  So, method name could be isTokenLookupRequired.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java` line 300 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUNxdcEKF3xXCWygBP:-NHUNxddElh36w2U4vvN:bvdykaj) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java#L300)):*
> ```Java
>     try {
>       ngVaultService.processTokenLookup(inputConnector, ACCOUNT_IDENTIFIER);
>     } catch (Exception ex) {
> ```

use ExpectedException instead
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java` line 343 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUO67JAqgNYEsjFkP2:-NHUO67JAqgNYEsjFkP3:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java#L343)):*
> ```Java
>     try {
>       ngVaultService.processTokenLookup(inputConnector, ACCOUNT_IDENTIFIER);
>     } catch (Exception ex) {
> ```

same here


<!-- Sent from Reviewable.io -->

2022-11-22 13:17 UTC, piyush-harness submitted a review, later dismissed
> Reviewed 5 of 12 files at r1, 4 of 12 files at r2, 1 of 4 files at r3, 1 of 4 files at r5, 1 of 6 files at r6, 2 of 7 files at r7, 1 of 4 files at r8, 1 of 4 files at r9, 5 of 5 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-22 14:38 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 4 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 396 at r3](https://reviewable.io/reviews/harness/harness-core/39310#-NFghvib2Ba6n45rE-aD:-NHUl5sYBwWVaKLAJetj:bfo0ov0) ([raw file](https://github.com/harness/harness-core/blob/b3e0f0bbfea0c1b52072ec15934a1be67d5a93f6/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L396)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is expiry time null a sufficient condition to conclude that token is root token? Will any other token which is non-renewable not have null expiry time?
</blockquote></details>

Yes this should be sufficient. We cannot configure non-root tokens without expiry time. The max expiry time for tokens other than root tokens is 768h or 32 days.
___
*[`400-rest/src/test/java/software/wings/service/VaultTest.java` line 2227 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUKKne70RQDjAHs4eA:-NHUlIHpCusJKHRBk9eO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/400-rest/src/test/java/software/wings/service/VaultTest.java#L2227)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

use ExpectedException instead of try catch block.
</blockquote></details>

Done.
___
*[`400-rest/src/test/java/software/wings/service/VaultTest.java` line 2251 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUKaoi6vG6V3RdboWC:-NHUlJRV73pbcaAyVVl5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/400-rest/src/test/java/software/wings/service/VaultTest.java#L2251)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 444 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUMMpG02QzsbDoDa4V:-NHUlM9g5O7NHmm-Gjwt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L444)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Rather than validation its mainly decision whether or not lookup call is required or not.  So, method name could be isTokenLookupRequired.
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java` line 300 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUNxdcEKF3xXCWygBP:-NHUlMtIAMR7nTkQwrNz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java#L300)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

use ExpectedException instead
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java` line 343 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHUO67JAqgNYEsjFkP2:-NHUlNM78Oq7rAom1ORp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/test/java/io/harness/connector/impl/NGVaultServiceImplTest.java#L343)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 57 at r11](https://reviewable.io/reviews/harness/harness-core/39310#-NHULB1t9lnkaxtZtbV1:-NHUlO9f2NPi7rI697B5:brx0tmh) ([raw file](https://github.com/harness/harness-core/blob/6eed0ea3792aaede005b8f9d668ef14ec847ec12/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L57)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why this is required?
</blockquote></details>

This was required to set the renewal interval in case we check the token lookup in the existing token renewal iterator. As we are not doing that now, removed this code.


<!-- Sent from Reviewable.io -->

2022-11-23 14:56 UTC, nishantsaini20 approved these changes
> Reviewed 4 of 4 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-24 05:03 UTC, piyush-harness approved these changes
> Reviewed 4 of 4 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-24 05:52 UTC, arpit3107 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 1 change requests. 1. unresolved discussions. 

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 408 at r13](https://reviewable.io/reviews/harness/harness-core/39310#-NHcBAea2gMgEkaPkpgl:-NHcBAea2gMgEkaPkpgm:bj557jd) ([raw file](https://github.com/harness/harness-core/blob/7c5ce95a6d70f716471255bd163508ce7f12f051/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L408)):*
> ```Java
>   TERRAGRUNT_ROLLBACK_TASK_NG(TaskGroup.TERRAGRUNT, "Terragrunt Rollback Task", true),
>   VAULT_TOKEN_LOOKUP(TaskGroup.KMS, "Token lookup of token in Hashicorp Vault"),
>   NG_VAULT_TOKEN_LOOKUP(TaskGroup.KMS, "Token lookup of token in Hashicorp Vault");
> ```

How are you handling the backward compatibility here. Although this is a new taskType but still delegate will always be running behind manager. So how are you creating task?


<!-- Sent from Reviewable.io -->

2022-11-25 09:08 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 408 at r13](https://reviewable.io/reviews/harness/harness-core/39310#-NHcBAea2gMgEkaPkpgl:-NHi1sbfDAIyka-abwkm:b-cf1630) ([raw file](https://github.com/harness/harness-core/blob/a933b8da5f2eea0e5c528934c3cae85b575d33f3/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L408)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

How are you handling the backward compatibility here. Although this is a new taskType but still delegate will always be running behind manager. So how are you creating task?
</blockquote></details>

Added the isTaskSupported call as per doc


<!-- Sent from Reviewable.io -->

2022-11-28 05:18 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 12 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 393 at r16](https://reviewable.io/reviews/harness/harness-core/39310#-NHweMN-9PRokciw_pO5:-NHweMN-9PRokciw_pO6:b-5z4l4y) ([raw file](https://github.com/harness/harness-core/blob/218bea4993c6d0b00d43e92a410a96d861850f31/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L393)):*
> ```Java
> 
>   private void validateRenewalIntervalBasedOnTokenLookup(VaultConfig vaultConfig) {
>     if (!delegateTaskService.isTaskTypeSupportedByAllDelegates(vaultConfig.getAccountId(), "VAULT_TOKEN_LOOKUP")) {
> ```

call to isTaskTypeSupportedByAllDelegates() should be move to base class, so that others can also consume it.
Also what's the action are we taking here if we fail to proceed i.e. no delegates available to accept the task, we should show some error on UI, as well as in logs, so that customer can upgrade their delegates.



_Code quote:_
```Java
    if (!delegateTaskService.isTaskTypeSupportedByAllDelegates(vaultConfig.getAccountId(), "VAULT_TOKEN_LOOKUP")) {
      return;
    }
```


<!-- Sent from Reviewable.io -->

2022-11-28 06:05 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 14 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java` line 393 at r16](https://reviewable.io/reviews/harness/harness-core/39310#-NHweMN-9PRokciw_pO5:-NHwpbOJ3bz7zSz-973f:b-n94hoi) ([raw file](https://github.com/harness/harness-core/blob/218bea4993c6d0b00d43e92a410a96d861850f31/400-rest/src/main/java/software/wings/service/impl/security/VaultServiceImpl.java#L393)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

call to isTaskTypeSupportedByAllDelegates() should be move to base class, so that others can also consume it.
Also what's the action are we taking here if we fail to proceed i.e. no delegates available to accept the task, we should show some error on UI, as well as in logs, so that customer can upgrade their delegates.
</blockquote></details>

changed it to base class. This is our internal thing only so made it an info log for dev purpose. Customer do not need to know this.


<!-- Sent from Reviewable.io -->

2022-11-29 05:14 UTC, gaurav-jain1 approved these changes
> Reviewed 3 of 12 files at r1, 3 of 12 files at r2, 2 of 7 files at r7, 1 of 4 files at r12, 1 of 2 files at r13, 4 of 4 files at r14, 4 of 5 files at r15, 3 of 3 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 15 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-29 05:34 UTC, nishantsaini20 approved these changes
> Reviewed 4 of 4 files at r14, 4 of 5 files at r15, 3 of 3 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-29 06:06 UTC, arpit3107 approved these changes
> Reviewed 3 of 12 files at r1, 3 of 12 files at r2, 2 of 7 files at r7, 1 of 4 files at r12, 1 of 2 files at r13, 4 of 4 files at r14, 4 of 5 files at r15, 3 of 3 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-29 13:21 UTC, Raghav-Murali approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39310#-:-NI2Y7jJA07xiiUaYaWt:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-29 14:43 UTC, merged