[feat]: Elastigroup Setup Manager side changes
harness/harness-core pull request #39398
Opened 2022-10-31 05:22 UTC by piyush-bhuwalka

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-04 08:11 UTC, filip5rovic commented on 960-api-services/src/main/java/io/harness/elastigroup/ElastigroupCommandUnitConstants.java
> +  createSetup {
Any reason why these enum names are in camelCase? Why not `CREATE_SETUP`?

2022-11-04 10:44 UTC, filip5rovic commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java
> +      if (responseData instanceof ElastigroupStartupScriptFetchResponse) { // if EcsGitFetchResponse is received
Delete misleading comment

2022-11-04 11:04 UTC, filip5rovic commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepExecutor.java
> +  TaskChainResponse executeElastigroupTask(Ambiance ambiance, StepElementParameters stepParameters,
What's the idea behind this interface? Why it can't be part of `ElastigroupStepCommonHelper`? Invocation stack looks like this ElastigroupSetupStep -> ElastigroupStepCommonHelper -> ElastigroupSetupStep (ElastigroupStepExecutor) -> ElastigroupStepCommonHelper

2022-11-04 11:07 UTC, filip5rovic commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  ELASTIGROUP_STARTUP_SCRIPT_FETCH_RUN_TASK_NG(TaskGroup.ELASTIGROUP, "Elastigroup Startup Script Fetch Run Task"),
Could you check for this and other enums if it's okay to add new enums in the middle? For delegate backwards compatibility we must add enums at the end.

2022-11-04 12:01 UTC, filip5rovic requested changes
LGTM with couple of minor comments

2022-11-04 13:06 UTC, piyush-bhuwalka commented on 960-api-services/src/main/java/io/harness/elastigroup/ElastigroupCommandUnitConstants.java
> +  createSetup {
I was taking reference of this file EcsCommandUnitConstants

2022-11-04 13:13 UTC, piyush-bhuwalka commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  ELASTIGROUP_STARTUP_SCRIPT_FETCH_RUN_TASK_NG(TaskGroup.ELASTIGROUP, "Elastigroup Startup Script Fetch Run Task"),
Shifted to the end

2022-11-04 13:16 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepExecutor.java
> +  TaskChainResponse executeElastigroupTask(Ambiance ambiance, StepElementParameters stepParameters,
You could find the imp of it in ECS Swimlane in NG. Class name - ECSStepExecutor. You could check the usages where multiple classes could reuse the same method

2022-11-04 13:22 UTC, filip5rovic submitted a review, later dismissed

2022-11-04 13:32 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelper.java
> +      if (responseData instanceof ElastigroupStartupScriptFetchResponse) { // if EcsGitFetchResponse is received
Deleted

2022-11-04 13:35 UTC, filip5rovic approved these changes
> Reviewed 21 of 50 files at r1, 1 of 7 files at r3, 9 of 19 files at r4, 10 of 11 files at r5, 4 of 7 files at r6, 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-07 05:20 UTC, piyush-bhuwalka commented
trigger messagecheck

2022-11-07 06:39 UTC, raghuAtWings commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java` line 11 at r11](https://reviewable.io/reviews/harness/harness-core/39398#-NGFo8LLB3NDRmv3QANk:-NGFo8LM71NRvq2wbfvK:b-nxs0qb) ([raw file](https://github.com/harness/harness-core/blob/18aa5e478e9790d37c7d002d885e47e7eb441391/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java#L11)):*
> ```Java
> 
> public enum ElastigroupCommandTypeNG {
>   ELASTIGROUP_SETUP,
> ```

how are you using this enum? are you going to send different types of this for the same delegate task to handle differently?


<!-- Sent from Reviewable.io -->

2022-11-07 08:29 UTC, piyush-bhuwalka reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 55 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java` line 11 at r11](https://reviewable.io/reviews/harness/harness-core/39398#-NGFo8LLB3NDRmv3QANk:-NGGCMKfA4pnQnOpmzIf:b-3cc4wy) ([raw file](https://github.com/harness/harness-core/blob/18aa5e478e9790d37c7d002d885e47e7eb441391/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java#L11)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

how are you using this enum? are you going to send different types of this for the same delegate task to handle differently?
</blockquote></details>

Yes, I'll be using it that way


<!-- Sent from Reviewable.io -->

2022-11-07 09:59 UTC, puthrayaharness submitted a review, later dismissed

2022-11-07 10:07 UTC, piyush-bhuwalka commented
trigger codebasehash

2022-11-07 13:27 UTC, piyush-bhuwalka commented
trigger feature-build

2022-11-08 04:50 UTC, arvind-choudhary-h commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java` line 33 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKZhYU73n656N6lN9m:-NGKZhYU73n656N6lN9n:bml1qzm) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java#L33)):*
> ```Java
>     implements ElastigroupCommandRequest, ExpressionReflectionUtils.NestedAnnotationResolver {
>   String accountId;
>   ElastigroupCommandTypeNG ecsCommandType;
> ```

why there are fields with ecs?


<!-- Sent from Reviewable.io -->

2022-11-08 04:50 UTC, arvind-choudhary-h commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java` line 40 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKZkTn1AsjyemGqJQR:-NGKZkTn1AsjyemGqJQS:b-ggyimm) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java#L40)):*
> ```Java
>   String startupScript;
>   boolean blueGreen;
>   @NonFinal @Expression(ALLOW_SECRETS) EcsInfraConfig ecsInfraConfig;
> ```

here -- why there are fields with ecs?


<!-- Sent from Reviewable.io -->

2022-11-08 04:53 UTC, arvind-choudhary-h commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupEntityHelper.java` line 42 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGK_WL_6CVuUgGwKXlc:-NGK_WL_6CVuUgGwKXld:b-k7wjih) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupEntityHelper.java#L42)):*
> ```Java
>   @Named(DEFAULT_CONNECTOR_SERVICE) @Inject private ConnectorService connectorService;
> 
>   // todo: refactor it
> ```

what is to refactor?


<!-- Sent from Reviewable.io -->

2022-11-08 04:56 UTC, arvind-choudhary-h commented
*[`380-cg-graphql/src/main/java/io/harness/app/schema/type/delegate/QLTaskGroup.java` line 103 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKa-EK075LxJRrX0Pv:-NGKa-EK075LxJRrX0Pw:bxhsx5z) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/380-cg-graphql/src/main/java/io/harness/app/schema/type/delegate/QLTaskGroup.java#L103)):*
> ```Java
>   SHELL_SCRIPT_PROVISION_NG,
>   CUSTOM_DEPLOYMENT_NG,
>   ELASTIGROUP;
> ```

why do we have to do this? I believe this is related CG implementation for graphQL


<!-- Sent from Reviewable.io -->

2022-11-08 05:30 UTC, arvind-choudhary-h commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java` line 63 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKhoSf6oGsZS17ghDB:-NGKhoSg1zOlasGQNPrV:b-3x8534) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java#L63)):*
> ```Java
>       Ambiance ambiance, GitStoreConfig gitStoreConfig, ManifestOutcome manifestOutcome) {
>     String connectorId = gitStoreConfig.getConnectorRef().getValue();
>     String validationMessage = format("Ecs manifest with Id [%s]", manifestOutcome.getIdentifier());
> ```

please remove all "ECS" related code and comments from this PR.


<!-- Sent from Reviewable.io -->

2022-11-08 05:36 UTC, arvind-choudhary-h commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/elastigroup/ElastigroupSetupResult.java` line 29 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKi_8q3pVO2W6s25X6:-NGKi_8q3pVO2W6s25X7:bj4tn86) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/elastigroup/ElastigroupSetupResult.java#L29)):*
> ```Java
>   private ResizeStrategy resizeStrategy;
>   private boolean isBlueGreen;
>   private String elstiGroupNamePrefix;
> ```

naming... elastiGr...


<!-- Sent from Reviewable.io -->

2022-11-08 05:36 UTC, arvind-choudhary-h reviewed
> Reviewed 6 of 50 files at r1, 1 of 7 files at r3, 2 of 19 files at r4, 6 of 11 files at r5, 34 of 52 files at r9, 3 of 4 files at r10, 4 of 7 files at r11, 16 of 16 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 5. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-08 06:05 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java` line 63 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKhoSf6oGsZS17ghDB:-NGKpmvG6hQ2m33zy5X9:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java#L63)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

please remove all "ECS" related code and comments from this PR.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-08 06:05 UTC, piyush-bhuwalka commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupEntityHelper.java` line 42 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGK_WL_6CVuUgGwKXlc:-NGKpv_j2PH2oqybPE38:bhplzcy) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupEntityHelper.java#L42)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

what is to refactor?
</blockquote></details>

Removed this comment


<!-- Sent from Reviewable.io -->

2022-11-08 06:06 UTC, piyush-bhuwalka commented
*[`380-cg-graphql/src/main/java/io/harness/app/schema/type/delegate/QLTaskGroup.java` line 103 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKa-EK075LxJRrX0Pv:-NGKpzzwEnEZrhUCasI6:b5cbr0n) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/380-cg-graphql/src/main/java/io/harness/app/schema/type/delegate/QLTaskGroup.java#L103)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

why do we have to do this? I believe this is related CG implementation for graphQL
</blockquote></details>

The constants have NG in it, and all fields are newly added in the file. And one test case was also failing because of not adding it


<!-- Sent from Reviewable.io -->

2022-11-08 06:06 UTC, piyush-bhuwalka commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/elastigroup/ElastigroupSetupResult.java` line 29 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKi_8q3pVO2W6s25X6:-NGKq9bYEyfiMp7IXUWk:b-x1r2x) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/elastigroup/ElastigroupSetupResult.java#L29)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

naming... elastiGr...
</blockquote></details>

corrected it


<!-- Sent from Reviewable.io -->

2022-11-08 06:06 UTC, piyush-bhuwalka commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java` line 33 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKZhYU73n656N6lN9m:-NGKqCuvC-dB0tnZ8G_u:b-5dfryo) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java#L33)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

why there are fields with ecs?
</blockquote></details>

removed it


<!-- Sent from Reviewable.io -->

2022-11-08 06:06 UTC, piyush-bhuwalka commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java` line 40 at r13](https://reviewable.io/reviews/harness/harness-core/39398#-NGKZkTn1AsjyemGqJQR:-NGKqIG6-pipR-jwU_DZ:b-5dfryo) ([raw file](https://github.com/harness/harness-core/blob/40e01b6f0a90af83eab032d4b329108dd0ad5e73/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/request/ElastigroupSetupCommandRequest.java#L40)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

here -- why there are fields with ecs?
</blockquote></details>

removed it


<!-- Sent from Reviewable.io -->

2022-11-08 06:28 UTC, arvind-choudhary-h reviewed
> Reviewed 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 8. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-08 06:30 UTC, arvind-choudhary-h commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java` line 134 at r14](https://reviewable.io/reviews/harness/harness-core/39398#-NGKvdwwEPCYdvOYzBoc:-NGKvdwwEPCYdvOYzBod:b-u51gp0) ([raw file](https://github.com/harness/harness-core/blob/57d3890c9d42dbe5940fab9a81a277235491c7a5/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java#L134)):*
> ```Java
>       elastigroupSetupResponse = (ElastigroupSetupResponse) responseDataSupplier.get();
>     } catch (Exception e) {
>       log.error("Error while processing ecs task response: {}", e.getMessage(), e);
> ```

update log.


<!-- Sent from Reviewable.io -->

2022-11-08 06:30 UTC, arvind-choudhary-h commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java` line 47 at r14](https://reviewable.io/reviews/harness/harness-core/39398#-NGKvm8x1HlR4w5zV3sE:-NGKvm8x1HlR4w5zV3sF:borvic9) ([raw file](https://github.com/harness/harness-core/blob/57d3890c9d42dbe5940fab9a81a277235491c7a5/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java#L47)):*
> ```Java
> public class ElastigroupStepUtils extends CDStepHelper {
>   @Inject private EngineExpressionService engineExpressionService;
>   @Inject private EcsEntityHelper ecsEntityHelper;
> ```

can remove


<!-- Sent from Reviewable.io -->

2022-11-08 06:31 UTC, arvind-choudhary-h commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/beans/ElastigroupStartupScriptFetchPassThroughData.java` line 24 at r14](https://reviewable.io/reviews/harness/harness-core/39398#-NGKvwoYEcKX1uYN3elJ:-NGKvwoYEcKX1uYN3elK:bfh0rkp) ([raw file](https://github.com/harness/harness-core/blob/57d3890c9d42dbe5940fab9a81a277235491c7a5/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/beans/ElastigroupStartupScriptFetchPassThroughData.java#L24)):*
> ```Java
> @Value
> @Builder
> @TypeAlias("ecsGitFetchPassThroughData")
> ```

to fix.


<!-- Sent from Reviewable.io -->

2022-11-08 06:40 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/beans/ElastigroupStartupScriptFetchPassThroughData.java` line 24 at r14](https://reviewable.io/reviews/harness/harness-core/39398#-NGKvwoYEcKX1uYN3elJ:-NGKxrq03sB3iuVLQdl4:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/57d3890c9d42dbe5940fab9a81a277235491c7a5/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/beans/ElastigroupStartupScriptFetchPassThroughData.java#L24)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

to fix.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-08 06:40 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java` line 47 at r14](https://reviewable.io/reviews/harness/harness-core/39398#-NGKvm8x1HlR4w5zV3sE:-NGKy36-EcpRbXPiQ-1n:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/57d3890c9d42dbe5940fab9a81a277235491c7a5/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupStepUtils.java#L47)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

can remove
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-08 06:41 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java` line 134 at r14](https://reviewable.io/reviews/harness/harness-core/39398#-NGKvdwwEPCYdvOYzBoc:-NGKyAbW7ya8rk8OnxZY:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/57d3890c9d42dbe5940fab9a81a277235491c7a5/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java#L134)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

update log.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-08 06:46 UTC, arvind-choudhary-h submitted a review, later dismissed
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-08 06:58 UTC, piyush-bhuwalka commented
trigger codebasehash

2022-11-10 05:06 UTC, arvind-choudhary-h approved these changes
> Reviewed 7 of 7 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-10 05:07 UTC, piyush-bhuwalka commented
trigger codebasehash

2022-11-10 05:26 UTC, puthrayaharness approved these changes

2022-11-10 05:32 UTC, arvind-choudhary-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-10 06:46 UTC, filip5rovic approved these changes
> Reviewed 25 of 52 files at r9, 2 of 7 files at r11, 13 of 16 files at r12, 4 of 7 files at r14, 4 of 4 files at r15, 7 of 7 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-10 06:48 UTC, filip5rovic submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-10 07:39 UTC, raghuAtWings commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java` line 11 at r11](https://reviewable.io/reviews/harness/harness-core/39398#-NGFo8LLB3NDRmv3QANk:-NGVT88fB5Vgjbn85MX4:bpiukqf) ([raw file](https://github.com/harness/harness-core/blob/18aa5e478e9790d37c7d002d885e47e7eb441391/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java#L11)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Yes, I'll be using it that way
</blockquote></details>

This is not right thing to do. What will happen if a customer who doesn’t upgrade their delegates? How will you decide whether to use new enum or not?

What you should build is to have new task type for each functionality rather than one task for all functionality 

We have clean way exposed to let you decide when to enable the task for a customer based on whether their delegates have upgraded or not. 


<!-- Sent from Reviewable.io -->

2022-11-11 04:33 UTC, piyush-bhuwalka reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 12 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java` line 11 at r11](https://reviewable.io/reviews/harness/harness-core/39398#-NGFo8LLB3NDRmv3QANk:-NGZxg0Y1CBcxDL3A6in:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/18aa5e478e9790d37c7d002d885e47e7eb441391/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/elastigroup/response/ElastigroupCommandTypeNG.java#L11)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

This is not right thing to do. What will happen if a customer who doesn’t upgrade their delegates? How will you decide whether to use new enum or not?

What you should build is to have new task type for each functionality rather than one task for all functionality 

We have clean way exposed to let you decide when to enable the task for a customer based on whether their delegates have upgraded or not. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-11 04:56 UTC, raghuAtWings reviewed
> Reviewed 2 of 50 files at r1, 1 of 19 files at r4, 6 of 11 files at r5, 24 of 52 files at r9, 1 of 4 files at r10, 3 of 7 files at r11, 10 of 16 files at r12, 3 of 7 files at r14, 2 of 4 files at r15, 4 of 7 files at r16, 5 of 6 files at r17, 7 of 7 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-11 04:57 UTC, raghuAtWings approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-11 08:54 UTC, sahilhindwani-harness approved these changes
> Reviewed 2 of 50 files at r1, 1 of 19 files at r4, 6 of 11 files at r5, 24 of 52 files at r9, 1 of 4 files at r10, 3 of 7 files at r11, 10 of 16 files at r12, 3 of 7 files at r14, 2 of 4 files at r15, 4 of 7 files at r16, 5 of 6 files at r17, 7 of 7 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39398)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-11 08:57 UTC, merged