[fix]: [CDS-45009]: Trigger Update Bug
harness/harness-core pull request #39616
Opened 2022-11-04 10:26 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-04 10:43 UTC, puthrayaharness requested changes

2022-11-04 10:43 UTC, puthrayaharness commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +        boolean isUnsubscribed = executePollingUnSubscription(ngTriggerEntity, pollingItemBytes);
Please add a test case. Also since this returns a boolean and we are not using the boolean why bother saving the boolean?

2022-11-07 06:58 UTC, inderschera requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39616)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/39616#-NGFsHte-PiH_oud2SKh:-NGFsHte-PiH_oud2SKi:blfqwa9) ([raw file](https://github.com/harness/harness-core/blob/73c2f4b2b892cd412885d76edf501ee93748a888/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L213)):*
> ```Java
>         updatePollingRegistrationStatus(ngTriggerEntity, null, StatusResult.SUCCESS);
>       } else {
>         boolean isUnsubscribed = executePollingUnSubscription(ngTriggerEntity, pollingItemBytes);
> ```

We don't always need to unsubscribe. Could we pass on some parameter that if it's trigger update then only we call unsubscribe?



_Code quote:_
```Java
subscribePolling(NGTriggerEntity ngTriggerEntity)
```


<!-- Sent from Reviewable.io -->

2022-11-07 09:06 UTC, inderschera approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39616)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-07 10:20 UTC, puthrayaharness approved these changes

2022-11-07 10:44 UTC, vaibhav-si approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39616)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-07 10:54 UTC, merged