feat: [CDS-46055]: Adding columns to deployment table and syncing the data
harness/harness-core pull request #39757
Opened 2022-11-08 07:29 UTC by Y0709

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-08 08:07 UTC, Abhishek-CDC commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java
> +      insertStatement.setBoolean(++index, (Boolean) eventInfo.get(EventProcessor.ON_DEMAND_ROLLBACK));
this method insert data to deployment_stage and deployment_parent table in which you have not added column. so you should not add these values for this. please check and test on local

2022-11-08 08:15 UTC, Abhishek-CDC commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java
> +      eventInfo.put(EventProcessor.ON_DEMAND_ROLLBACK, resultSet.getBoolean(index++));
please check source where this method is called. as mentioned in above comment we cant populate this property to tables deployment_stage and deployment_parent so we dont need these in eventinfo. to mention, if you want these changes then you should modify query "fetch_account_executions_deployment_in_interval" also since this resultset is obtained after execution of that and currently it doesn't have these values.

2022-11-08 08:19 UTC, Abhishek-CDC commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +    if (workflowExecution.isOnDemandRollback() && workflowExecution.getOriginalExecution().getExecutionId() != null) {
please add null check for workflowExecution.getOriginalExecution() to avoid NPE for workflowExecution.getOriginalExecution().getExecutionId()

2022-11-08 08:20 UTC, Abhishek-CDC commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java
> +                  appId, workflowExecution.getOriginalExecution().getExecutionId());
null check

2022-11-08 08:21 UTC, Abhishek-CDC commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java
> +              usageMetricsEventPublisher.publishDeploymentTimeSeriesEvent(accountID, originalExecution);
please cover publish method in try catch block to ensure it doesn't affect earlier flow

2022-11-08 09:00 UTC, Y0709 commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java
> +      eventInfo.put(EventProcessor.ON_DEMAND_ROLLBACK, resultSet.getBoolean(index++));
done

2022-11-08 09:00 UTC, Y0709 commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java
> +      insertStatement.setBoolean(++index, (Boolean) eventInfo.get(EventProcessor.ON_DEMAND_ROLLBACK));
done

2022-11-08 09:00 UTC, Y0709 commented on 400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java
> +    if (workflowExecution.isOnDemandRollback() && workflowExecution.getOriginalExecution().getExecutionId() != null) {
done

2022-11-08 09:00 UTC, Y0709 commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java
> +                  appId, workflowExecution.getOriginalExecution().getExecutionId());
done

2022-11-08 09:01 UTC, Y0709 commented on 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java
> +              usageMetricsEventPublisher.publishDeploymentTimeSeriesEvent(accountID, originalExecution);
done

2022-11-09 08:18 UTC, abhinavmittal-harness requested changes
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39757)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java` line 510 at r3](https://reviewable.io/reviews/harness/harness-core/39757#-NGQN1_v6HMzxUa6id27:-NGQN1_v6HMzxUa6id28:bcwwmuw) ([raw file](https://github.com/harness/harness-core/blob/2273fb23bd37d406302de5047cbf2fe003d0a71e/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java#L510)):*
> ```Java
>     Long rollbackDuration = getRollbackDuration(eventInfo);
>     insertStatement.setLong(++index, rollbackDuration);
>     Boolean onDemandRollback = getOnDemandRollback(eventInfo);
> ```

no need for Boolean use boolean instead



_Code quote:_
```Java
Boolean
```
___
*[`400-rest/src/main/resources/timescaledb/add_on_demand_rollback_details_to_deployment.sql` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/39757#-NGQSUqM2wegsdcGsZgw:-NGQSUqM2wegsdcGsZgx:b-9y22l7) ([raw file](https://github.com/harness/harness-core/blob/2273fb23bd37d406302de5047cbf2fe003d0a71e/400-rest/src/main/resources/timescaledb/add_on_demand_rollback_details_to_deployment.sql#L10)):*
> ```TSQL
> ALTER TABLE DEPLOYMENT ADD COLUMN IF NOT EXISTS ORIGINAL_EXECUTION_ID TEXT;
> 
> CREATE INDEX IF NOT EXISTS ON_DEMAND_ROLLBACK_INDEX ON DEPLOYMENT(on_demand_rollback,ENDTIME DESC);
> ```

Add a new column to keep track of whther it has been on deman rollback and index


<!-- Sent from Reviewable.io -->

2022-11-10 07:25 UTC, Y0709 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39757)* status: 11 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java` line 510 at r3](https://reviewable.io/reviews/harness/harness-core/39757#-NGQN1_v6HMzxUa6id27:-NGVQI3mBJXL9JVuvh6A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2273fb23bd37d406302de5047cbf2fe003d0a71e/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java#L510)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

no need for Boolean use boolean instead
</blockquote></details>

Done.
___
*[`400-rest/src/main/resources/timescaledb/add_on_demand_rollback_details_to_deployment.sql` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/39757#-NGQSUqM2wegsdcGsZgw:-NGVQLzHE8tNLGa85sgW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2273fb23bd37d406302de5047cbf2fe003d0a71e/400-rest/src/main/resources/timescaledb/add_on_demand_rollback_details_to_deployment.sql#L10)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Add a new column to keep track of whther it has been on deman rollback and index
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-15 17:40 UTC, abhinavmittal-harness commented
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java` line 363 at r1](https://reviewable.io/reviews/harness/harness-core/39757#-NGL8C95X94zDB2ze-76-r1-363:-NGwN29gBVZslFDkLD6q:b8zzlkd) ([raw file](https://github.com/harness/harness-core/blob/596a73c83114fcfb5422478656436de04e7e3d69/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java#L363)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

done
</blockquote></details>

Acknowledged


<!-- Sent from Reviewable.io -->

2022-11-15 17:40 UTC, abhinavmittal-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39757)* status: 6. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java` line 410 at r1](https://reviewable.io/reviews/harness/harness-core/39757#-NGL8C95X94zDB2ze-76-r1-410:-NGwN77wC_DTfY_dnfpt:b8zzlkd) ([raw file](https://github.com/harness/harness-core/blob/596a73c83114fcfb5422478656436de04e7e3d69/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java#L410)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

done
</blockquote></details>

Acknowledged
___
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java` line 514 at r1](https://reviewable.io/reviews/harness/harness-core/39757#-NGL8C95X94zDB2ze-76-r1-514:-NGwN7yz1kjHTxw1OX-_:b8zzlkd) ([raw file](https://github.com/harness/harness-core/blob/596a73c83114fcfb5422478656436de04e7e3d69/400-rest/src/main/java/io/harness/event/timeseries/processor/DeploymentEventProcessor.java#L514)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

done
</blockquote></details>

Acknowledged
___
*[`400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java` line 325 at r1](https://reviewable.io/reviews/harness/harness-core/39757#-NGL8C95X94zDB2ze-78-r1-325:-NGwN8Xa24WLUk4FWog1:b8zzlkd) ([raw file](https://github.com/harness/harness-core/blob/596a73c83114fcfb5422478656436de04e7e3d69/400-rest/src/main/java/io/harness/event/usagemetrics/UsageMetricsEventPublisher.java#L325)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

done
</blockquote></details>

Acknowledged
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java` line 306 at r1](https://reviewable.io/reviews/harness/harness-core/39757#-NGL8C95X94zDB2ze-7A-r1-306:-NGwN95e4JmWNmOhNNTr:b8zzlkd) ([raw file](https://github.com/harness/harness-core/blob/596a73c83114fcfb5422478656436de04e7e3d69/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java#L306)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

done
</blockquote></details>

Acknowledged
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/39757#-NGL8C95X94zDB2ze-7A-r1-308:-NGwN9Zp7iLEJ1tcYdQS:b8zzlkd) ([raw file](https://github.com/harness/harness-core/blob/596a73c83114fcfb5422478656436de04e7e3d69/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java#L308)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

done
</blockquote></details>

Acknowledged


<!-- Sent from Reviewable.io -->

2022-11-15 17:41 UTC, abhinavmittal-harness approved these changes

2022-11-15 17:43 UTC, abhinavmittal-harness approved these changes

2022-11-16 04:37 UTC, Abhishek-CDC reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39757)* status: 6. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-16 04:38 UTC, Abhishek-CDC approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39757#-:-NGyirVS98AVzmIP1ifS:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-16 05:14 UTC, merged