fix: [SPG-786]: Move all secondary node queries to the analytics node
harness/harness-core pull request #39805
Opened 2022-11-08 19:21 UTC by rafaelmart1ns

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-08 20:43 UTC, abhinav-harness submitted a review, later dismissed
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39805)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-08 21:30 UTC, Fernando-Dourado requested changes
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39805)* status: :shipit: complete! ✓

___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 170 at r1](https://reviewable.io/reviews/harness/harness-core/39805#-NGO8RsI1toBExrgPc_M:-NGO8RsI1toBExrgPc_N:b-gxk767) ([raw file](https://github.com/harness/harness-core/blob/6d1caf460f423f9a1346cda6c272fc83f90ae627/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L170)):*
> ```Java
>      * @return the query
>      */
>   <T extends PersistentEntity> Query<T> createAnalyticsQuery(Class<T> cls);
> ```

It is not missing the implementation?


<!-- Sent from Reviewable.io -->

2022-11-08 21:37 UTC, Fernando-Dourado approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39805)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-09 12:18 UTC, Fernando-Dourado approved these changes
> Reviewed 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39805)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-09 12:22 UTC, lasdox commented on 400-rest/src/main/java/io/harness/execution/export/background/ExportExecutionsService.java
> -    Query<WorkflowExecution> query = wingsPersistence.createQuery(WorkflowExecution.class, excludeAuthority);
need to use the exclude authority here

2022-11-09 12:22 UTC, lasdox commented on 400-rest/src/main/java/software/wings/service/impl/ActivityServiceImpl.java
> -    List<Activity> activities = wingsPersistence.createQuery(Activity.class, excludeAuthority)
need to use the exclude authority here

2022-11-09 19:17 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/ActivityServiceImpl.java
> -    List<Activity> activities = wingsPersistence.createQuery(Activity.class, excludeAuthority)
done.

2022-11-09 19:17 UTC, rafaelmart1ns commented on 400-rest/src/main/java/io/harness/execution/export/background/ExportExecutionsService.java
> -    Query<WorkflowExecution> query = wingsPersistence.createQuery(WorkflowExecution.class, excludeAuthority);
done.

2022-11-09 20:31 UTC, lasdox approved these changes
> Reviewed 2 of 23 files at r1, 20 of 20 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39805)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-09 21:14 UTC, merged