[feat]:[pie-6178]: get remote pms from non default branch
harness/harness-core pull request #39869
Opened 2022-11-09 10:57 UTC by adivishy1

## Describe your changes
Code changes to load remote pipelines from non default branches for newly created pipelines. The following cases have been tested out: https://docs.google.com/spreadsheets/d/1qvOiucmg8UiRFzY8uotaOl_qvYS6rkTVNoAaiS9f0Z8/edit#gid=0

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-10 05:18 UTC, adivishy1 commented
trigger messagecheck

2022-11-10 20:05 UTC, mohitg0795 commented
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 244 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY8J6B2JWT7vCOHYtk:-NGY8J6B2JWT7vCOHYtl:b-sdu16g) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L244)):*
> ```Java
>               "This is a boolean value. If true, returns Templates resolved Pipeline YAML in the response else returns null.")
>       @QueryParam("getTemplatesResolvedPipeline") @DefaultValue("false") boolean getTemplatesResolvedPipeline,
>       @QueryParam("loadFromNonDefaultBranch") @DefaultValue("false") boolean loadFromNonDefaultBranch);
> ```

can we name it something like "loadFromFallbackBranch", sounds more intuitive or anything else if you can suggest


<!-- Sent from Reviewable.io -->

2022-11-10 20:08 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 161 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY8tdw7IVksu-TvstO:-NGY8tdw7IVksu-TvstP:b-nrwal4) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L161)):*
> ```Java
>   @Wither @Setter @NonFinal String connectorRef;
>   @Wither @Setter @NonFinal String repoURL;
>   @Wither @Setter @NonFinal String pipelineCreatedBranch;
> ```

I think we shouldn't name it "created" as for now, it looks like its branch on which pipeline is created, but logic may change later on and then it may sound wrong. eg: what if later we decide to update this branch based on updates?

I would say lets try to keep it named "branch" only or "fallbackBranch" or something similar thats quite generic in nature and can be used extensively the way we want to in future.


<!-- Sent from Reviewable.io -->

2022-11-10 20:10 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY9SC71us2C8xrqWLe:-NGY9SC71us2C8xrqWLf:b-ri4nf9) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L191)):*
> ```Java
>     log.info(String.format("Retrieving pipeline with identifier %s in project %s, org %s, account %s", pipelineId,
>         projectId, orgId, accountId));
>     LoadFromNonDefaultThreadLocal.set(loadFromNonDefaultBranch);
> ```

Is it possible to simply use some key value pair and put in generic thread context? We can avoid creating new special thread context if thats possible.


<!-- Sent from Reviewable.io -->

2022-11-10 20:12 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY9p4g7WLxpVxjs1oO:-NGY9p4g7WLxpVxjs1oP:b-k6w692) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L221)):*
> ```Java
>               .build());
>     } finally {
>       LoadFromNonDefaultThreadLocal.unset();
> ```

Is using such context thread-safe? Could you point me to some other references where its being used? I just want to see if it doesn't cause any concurrency issues.


<!-- Sent from Reviewable.io -->

2022-11-10 20:14 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 222 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYAPWJDdBQG63asCVi:-NGYAPWK7EoTXu3ijPJb:b-85f6dk) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L222)):*
> ```Java
> 
>   @VisibleForTesting
>   PipelineEntity fetchRemoteEntity(PipelineEntity savedEntity, String accountIdentifier, String orgIdentifier,
> ```

Always keep account id, org id, project id as first params for any method and then corresponding arguments. This helps us to follow a convention that scope always comes first.


<!-- Sent from Reviewable.io -->

2022-11-10 20:15 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 237 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYAd3QDMght1ROLfH3:-NGYAd3QDMght1ROLfH4:bwqmf8y) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L237)):*
> ```Java
>       ScmException scmException = GitXExceptionUtil.getScmException(ex);
>       log.error(
>           String.format("Error while retrieving pipeline [%s] from default branch", savedEntity.getIdentifier()), ex);
> ```

how can you say error is from "default branch"


<!-- Sent from Reviewable.io -->

2022-11-10 20:19 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 258 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYBQkQ1GEkODbwd72j:-NGYBQkQ1GEkODbwd72k:b3u92j5) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L258)):*
> ```Java
> 
>   @VisibleForTesting
>   boolean shouldRetryWithNonDefaultBranch(ScmException scmException, String branchTried, String pipelineCreateBranch) {
> ```

don't you think this method itself should also do check on the loadFromDefaultBranch param as well? It should be complete in nature in the sense that it holds complete logic to say that should we retry or not.


<!-- Sent from Reviewable.io -->

2022-11-10 20:20 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 244 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYBkQJ1g7zy6fopJPF:-NGYBkQJ1g7zy6fopJPG:bw1vff4) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L244)):*
> ```Java
>           log.info(String.format("Retrieving pipeline [%s] from non default branch [%s] ", savedEntity.getIdentifier(),
>               savedEntity.getPipelineCreatedBranch()));
>           savedEntity = fetchRemoteEntity(
> ```

Lets not do recursion here, it may become complicated and difficult to debug in future.


<!-- Sent from Reviewable.io -->

2022-11-10 20:22 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 251 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYBsuT4YjVuetzdQXM:-NGYBsuT4YjVuetzdQXN:b-3hrpef) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L251)):*
> ```Java
>         }
>       } else {
>         throw ex;
> ```

Now, as per contract with UI, branch always comes in error response so we cannot break that. All our pipeline fetch responses should contain branch as best as possible.

Also, when integrating with UI, keep in mind that they should take branch from API response. If not found, then they should always and always show default branch / branch selected on UI as fallback.


<!-- Sent from Reviewable.io -->

2022-11-10 20:23 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/utils/GitXExceptionUtil.java` line 11 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYCSp_26GSPTdTH_yX:-NGYCSp_26GSPTdTH_yY:blbb8b2) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/utils/GitXExceptionUtil.java#L11)):*
> ```Java
> @UtilityClass
> @OwnedBy(HarnessTeam.PIPELINE)
> public class GitXExceptionUtil {
> ```

It is not related to GitX, it doesn't hold any specific logic to gitx. Lets put this method into some common utils or rename it as ExceptionUtils or something similar.


<!-- Sent from Reviewable.io -->

2022-11-11 08:09 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 10 file(s) to review. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 244 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY8J6B2JWT7vCOHYtk:-NGZzsYLA5avZC5WQ5LE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L244)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we name it something like "loadFromFallbackBranch", sounds more intuitive or anything else if you can suggest
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 161 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY8tdw7IVksu-TvstO:-NG_--H0EX9nGmCcLcFy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L161)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we shouldn't name it "created" as for now, it looks like its branch on which pipeline is created, but logic may change later on and then it may sound wrong. eg: what if later we decide to update this branch based on updates?

I would say lets try to keep it named "branch" only or "fallbackBranch" or something similar thats quite generic in nature and can be used extensively the way we want to in future.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY9SC71us2C8xrqWLe:-NG_2FvVBKaAaOgZHXwS:b-749b5p) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L191)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is it possible to simply use some key value pair and put in generic thread context? We can avoid creating new special thread context if thats possible.
</blockquote></details>

Feel this will be cleaner compared to just adding to a generic thread context, this will help us in debugging as well
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY9p4g7WLxpVxjs1oO:-NG_-8mIB5rajpCAWEDy:bvkpefp) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L221)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is using such context thread-safe? Could you point me to some other references where its being used? I just want to see if it doesn't cause any concurrency issues.
</blockquote></details>

AuditHelper, PrincipalThreadLocal 
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 222 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYAPWJDdBQG63asCVi:-NG_2OOz0KTPrcPbTDCY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L222)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Always keep account id, org id, project id as first params for any method and then corresponding arguments. This helps us to follow a convention that scope always comes first.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 235 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYAkIz6kQssUhLttc3:-NG_G7tH2kgHz5JRmTEa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L235)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

before anything, we should just check if branch = empty or not. If empty, then only we do other logic, otherwise simply attach the branch with the exception and re-throw it.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 237 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYAd3QDMght1ROLfH3:-NG_1zZr6KTtPkAXK4s6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L237)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

how can you say error is from "default branch"
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 244 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYBkQJ1g7zy6fopJPF:-NG_2-Do4p9Q5ur4xjC9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L244)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets not do recursion here, it may become complicated and difficult to debug in future.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 251 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYBsuT4YjVuetzdQXM:-NG_G4DO4zWMgLNUBoa2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L251)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Now, as per contract with UI, branch always comes in error response so we cannot break that. All our pipeline fetch responses should contain branch as best as possible.

Also, when integrating with UI, keep in mind that they should take branch from API response. If not found, then they should always and always show default branch / branch selected on UI as fallback.
</blockquote></details>

Done.



_Code quote:_
```Java
          log.info(String.format("Retrieving pipeline [%s] from non default branch [%s] ", savedEntity.getIdentifier(),
              savedEntity.getPipelineCreatedBranch()));
```
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 258 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGYBQkQ1GEkODbwd72j:-NG_GyBD7DRfA1K6MLzt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L258)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

don't you think this method itself should also do check on the loadFromDefaultBranch param as well? It should be complete in nature in the sense that it holds complete logic to say that should we retry [...]

2022-11-11 10:02 UTC, mohitg0795 commented
*[`980-commons/src/main/java/io/harness/exception/ngexception/ErrorMetadataConstants.java` line 20 at r10](https://reviewable.io/reviews/harness/harness-core/39869#-NGa7x3y1HZRAIrqiuox:-NGa7x3y1HZRAIrqiuoy:b6cxdvq) ([raw file](https://github.com/harness/harness-core/blob/f7fdbbd5ac527e880d76c735d388c6d2807fda96/980-commons/src/main/java/io/harness/exception/ngexception/ErrorMetadataConstants.java#L20)):*
> ```Java
>   String INVALID_FIELDS_ERROR = "InvalidFieldsDTO";
>   String FILTER_CREATOR_ERROR = "FilterCreatorResponseError";
> ```

why did we leave a blank line here? Lets keep up with the file code pattern, otherwise it would get messier if everyone starts to violate it.


<!-- Sent from Reviewable.io -->

2022-11-11 10:08 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY9p4g7WLxpVxjs1oO:-NGa9-ZH6LxM66mx1d0q:blinxjt) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L221)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

AuditHelper, PrincipalThreadLocal 
</blockquote></details>

I think we can ignore this unsetting as its the first layer itself where we are setting the thread context. Unsetting context helps when we create a new context in some middle layer or end layer and we don't want it to be available for any parts of the thread before or after its creation point.
eg: A calls B calls C. Now, we would want that thread context created at B is available at B and C but surely not at A as it may start violating something over there which is unexpected. So, thus in that case, we would want to clear it.


<!-- Sent from Reviewable.io -->

2022-11-11 12:34 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 27 file(s) to review. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ngexception/ErrorMetadataConstants.java` line 20 at r10](https://reviewable.io/reviews/harness/harness-core/39869#-NGa7x3y1HZRAIrqiuox:-NGafepWDXzzpGIO6H--:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f7fdbbd5ac527e880d76c735d388c6d2807fda96/980-commons/src/main/java/io/harness/exception/ngexception/ErrorMetadataConstants.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why did we leave a blank line here? Lets keep up with the file code pattern, otherwise it would get messier if everyone starts to violate it.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/39869#-NGY9p4g7WLxpVxjs1oO:-NGaffhXEaO42g3pGPJK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f291e6942713a6afe63a40d216a0c1989fc3f2b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L221)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we can ignore this unsetting as its the first layer itself where we are setting the thread context. Unsetting context helps when we create a new context in some middle layer or end layer and we don't want it to be available for any parts of the thread before or after its creation point.
eg: A calls B calls C. Now, we would want that thread context created at B is available at B and C but surely not at A as it may start violating something over there which is unexpected. So, thus in that case, we would want to clear it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-11 12:42 UTC, mohitg0795 commented
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineFindParamDTO.java` line 18 at r14](https://reviewable.io/reviews/harness/harness-core/39869#-NGahRm91aQd62CajQVU:-NGahRm91aQd62CajQVV:bqui3uj) ([raw file](https://github.com/harness/harness-core/blob/1c3307c65f05ff0f822a250329284788d0201511/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineFindParamDTO.java#L18)):*
> ```Java
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class PipelineFindParamDTO {
> ```

Lets add some naming convention here so that its clear thats its specially added for repo layer eg: PipelineRepositoryFindParamsDTO


<!-- Sent from Reviewable.io -->

2022-11-11 12:46 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 180 at r14](https://reviewable.io/reviews/harness/harness-core/39869#-NGaiOfNA0jiMgSjutFR:-NGaiOfNA0jiMgSjutFS:bonb8ej) ([raw file](https://github.com/harness/harness-core/blob/1c3307c65f05ff0f822a250329284788d0201511/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L180)):*
> ```Java
>             savedEntity.getProjectIdentifier(), savedEntity.getIdentifier());
>     if (!metadataOptional.isPresent()) {
>       GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
> ```

what if gitEntityInfo is null?


<!-- Sent from Reviewable.io -->

2022-11-11 12:48 UTC, mohitg0795 reviewed
> Reviewed 1 of 5 files at r2, 1 of 7 files at r5, 3 of 3 files at r9, 1 of 2 files at r10, 14 of 18 files at r13, 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-11 13:05 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 15 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 180 at r14](https://reviewable.io/reviews/harness/harness-core/39869#-NGaiOfNA0jiMgSjutFR:-NGaku1Y-9AftPL7LOhR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c3307c65f05ff0f822a250329284788d0201511/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L180)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if gitEntityInfo is null?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java` line 70 at r14](https://reviewable.io/reviews/harness/harness-core/39869#-NGai36Q4u42Lxb2uE44:-NGam3Hs00Q6ot2COR-O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c3307c65f05ff0f822a250329284788d0201511/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageFilterCreator.java#L70)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

getPipeline should also have another method with this extra argument and internally re-direct to the new method. None of the existing consumers should have any change in their layers, thats the whole thing.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineFindParamDTO.java` line 18 at r14](https://reviewable.io/reviews/harness/harness-core/39869#-NGahRm91aQd62CajQVU:-NGakNLK6ypYbt-3InXm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c3307c65f05ff0f822a250329284788d0201511/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineFindParamDTO.java#L18)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets add some naming convention here so that its clear thats its specially added for repo layer eg: PipelineRepositoryFindParamsDTO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-11 13:11 UTC, mohitg0795 submitted a review, later dismissed
> Reviewed 15 of 15 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-11 13:37 UTC, archit-harness requested changes
> Reviewed 1 of 7 files at r5, 1 of 18 files at r13, 4 of 15 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: :shipit: complete! ✓

___
*[`980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java` line 17 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGap3oQCVcMmaT7dANV:-NGap3oQCVcMmaT7dANW:bn1e83k) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java#L17)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @JsonTypeName(ErrorMetadataConstants.GIT_ERROR)
> public class GitErrorMetadataDTO implements ErrorMetadataDTO {
> ```

Why do we need this in lower layer? don't we have contracts in git sync module which is shared?
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java` line 19 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqZ_89kWGRBjSQfLC:-NGaqZ_98GO_K4tZSDte:bxwfuft) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java#L19)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class PipelineGetParamsDTO {
>   boolean loadFromFallbackBranch;
> ```

We should description to this, to expose in swagger
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 188 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqrx08kYIpTFMvVGg:-NGaqrx08kYIpTFMvVGh:b-foq0it) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L188)):*
> ```Java
>       @NotNull @OrgIdentifier String orgId, @NotNull @ProjectIdentifier String projectId,
>       @ResourceIdentifier String pipelineId, GitEntityFindInfoDTO gitEntityBasicInfo,
>       boolean getTemplatesResolvedPipeline, boolean loadFromFallbackBranch) {
> ```

Can we expose the dto directly 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 64 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGasSoJ1jExB0j0Ubna:-NGasSoJ1jExB0j0Ubnb:b-dh9wfj) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L64)):*
> ```Java
> 
>   Optional<PipelineEntity> getAndValidatePipeline(String accountId, String orgIdentifier, String projectIdentifier,
>       String identifier, boolean deleted, PipelineGetParamsDTO pipelineGetParamsDTO);
> ```

rename to PipelineGitParamsDto
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 180 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGarpiYCCal3GvNDDzQ:-NGarpiYCCal3GvNDDzR:btkma61) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L180)):*
> ```Java
>             savedEntity.getProjectIdentifier(), savedEntity.getIdentifier());
>     if (!metadataOptional.isPresent()) {
>       PipelineMetadataV2 metadata =
> ```

PipelineMetadataServiceImpl please do the change here. as well
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 263 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGau65u2djYLwU4lZJC:-NGau65u2djYLwU4lZJD:bw1toy7) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L263)):*
> ```Java
>       return metadataOptional.get().getEntityGitDetails().getBranch();
>     }
>     return "";
> ```

if its empty how its helping?



_Code quote:_
```Java
""
```
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java` line 18 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqjem6zlu0MOBTUt6:-NGaqjem6zlu0MOBTUt7:b-nm7glg) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java#L18)):*
> ```Java
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class PipelineRepositoryFindParamsDTO {
> ```

why 2 dtos are needed? if its only for service layer then it should not be in pmscontracts and not append DTO keyword here
___
*[`pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java` line 11 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGauBWMDAtvcmFnM0qE:-NGauBWMDAtvcmFnM0qF:b8ithui) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java#L11)):*
> ```Java
> @UtilityClass
> @OwnedBy(HarnessTeam.PIPELINE)
> public class Exceptions {
> ```

WHy we are renaming git exceptions utisl to only exceptions


<!-- Sent from Reviewable.io -->

2022-11-11 13:41 UTC, mohitg0795 commented
*[`980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java` line 17 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGap3oQCVcMmaT7dANV:-NGaukcZ0nYHonqf586r:b-6c4zxk) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why do we need this in lower layer? don't we have contracts in git sync module which is shared?
</blockquote></details>

Its not something that git-sync owns. Its a generic error metadata dto that anybody can use. 


<!-- Sent from Reviewable.io -->

2022-11-11 13:42 UTC, mohitg0795 commented
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java` line 19 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqZ_89kWGRBjSQfLC:-NGav7r4CaEgRuibR5qC:bsygzvq) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should description to this, to expose in swagger
</blockquote></details>

This DTO is for intra-service use-only. If naming convention is a concern, that can be fixed. 


<!-- Sent from Reviewable.io -->

2022-11-11 13:43 UTC, mohitg0795 commented
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java` line 18 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqjem6zlu0MOBTUt6:-NGavNMX6uPOAHXCTbRp:b-gruw7t) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why 2 dtos are needed? if its only for service layer then it should not be in pmscontracts and not append DTO keyword here
</blockquote></details>

@adivishy1 why is it in the contracts? Probably you don't understand the constructs here, thats why a miss. Please sync with @archit-harness and put it in the right place.


<!-- Sent from Reviewable.io -->

2022-11-11 13:44 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 188 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqrx08kYIpTFMvVGg:-NGavZcJ4odokCsin4xV:beb1rap) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L188)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we expose the dto directly 
</blockquote></details>

This is anyways older API. We can do it right in the refactored version. For now, its on same lines as the other fields such as "getTemplatesResolvedPipeline"


<!-- Sent from Reviewable.io -->

2022-11-11 13:45 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 64 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGasSoJ1jExB0j0Ubna:-NGavqfaCU4Mq2A_bEDV:b-lohsqz) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to PipelineGitParamsDto
</blockquote></details>

We shouldn't rename it to anything related to "git". These aren't git params, but just behavioural params for get pipeline flow. They are not directly related to git, thus named generically which can be extended later on with more such fields if required.


<!-- Sent from Reviewable.io -->

2022-11-11 13:46 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java` line 11 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGauBWMDAtvcmFnM0qE:-NGaw8r15-TLPjloU_zE:b-dk9msj) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java#L11)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

WHy we are renaming git exceptions utisl to only exceptions
</blockquote></details>

@adivishy1 as discussed, this should be Helper class. @archit-harness this is a net new class. @adivishy1 mentioned that using "utils" makes some style checks fail, thus we are naming it Helper now.


<!-- Sent from Reviewable.io -->

2022-11-11 14:48 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 1 change requests. 6. unresolved discussions. 

___
*[`980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java` line 17 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGap3oQCVcMmaT7dANV:-NGb8zGVEUyUEHgwR77i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Its not something that git-sync owns. Its a generic error metadata dto that anybody can use. 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java` line 19 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqZ_89kWGRBjSQfLC:-NGb8h3vBMBvvKTHsVTH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java#L19)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This DTO is for intra-service use-only. If naming convention is a concern, that can be fixed. 
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 188 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqrx08kYIpTFMvVGg:-NGb8bHKCEMByqWGqT9R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L188)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is anyways older API. We can do it right in the refactored version. For now, its on same lines as the other fields such as "getTemplatesResolvedPipeline"
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 64 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGasSoJ1jExB0j0Ubna:-NGb90xLBNfL5QxU-oIm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We shouldn't rename it to anything related to "git". These aren't git params, but just behavioural params for get pipeline flow. They are not directly related to git, thus named generically which can be extended later on with more such fields if required.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java` line 18 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqjem6zlu0MOBTUt6:-NGb8G_sBvSHQcRkVrC5:b-spco5e) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java#L18)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@adivishy1 why is it in the contracts? Probably you don't understand the constructs here, thats why a miss. Please sync with @archit-harness and put it in the right place.
</blockquote></details>

inside the contracts, we had the other DTOs. hence placed them here, @archit-harness can you pls suggest if this has to be placed anywhere else?
___
*[`pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java` line 11 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGauBWMDAtvcmFnM0qE:-NGb9KVMB5jdXMItaTkL:b7mlduf) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java#L11)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@adivishy1 as discussed, this should be Helper class. @archit-harness this is a net new class. @adivishy1 mentioned that using "utils" makes some style checks fail, thus we are naming it Helper now.
</blockquote></details>

renamed to ExceptionHelper


<!-- Sent from Reviewable.io -->

2022-11-12 10:44 UTC, mohitg0795 commented
*[`980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java` line 17 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGap3oQCVcMmaT7dANV:-NGfQyBX8AHPvHL8GHMx:bnzy66u) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java#L17)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So we don't have any contracts or non-contracts thing yet in other services which are not refactored.
But I do see an issue here. @adivishy1 please move this file into 900-git-sync-sdk in some logical directory. As git-sdk is throwing exception and using it over there, it should be part of sdk directly.


<!-- Sent from Reviewable.io -->

2022-11-15 07:47 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 2 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java` line 17 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGap3oQCVcMmaT7dANV:-NGuAUtL2ltYdLOxFash:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/980-commons/src/main/java/io/harness/exception/ngexception/GitErrorMetadataDTO.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

So we don't have any contracts or non-contracts thing yet in other services which are not refactored.
But I do see an issue here. @adivishy1 please move this file into 900-git-sync-sdk in some logical directory. As git-sdk is throwing exception and using it over there, it should be part of sdk directly.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 180 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGarpiYCCal3GvNDDzQ:-NGuEdOc8GIdm6AixVgP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L180)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

PipelineMetadataServiceImpl please do the change here. as well
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 263 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGau65u2djYLwU4lZJC:-NGu9xIr225TTCVoV7Dw:bww2cmv) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L263)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if its empty how its helping?
</blockquote></details>

if this method returns empty, there is a check in before we retry from the fall back branch and we skip this


<!-- Sent from Reviewable.io -->

2022-11-15 11:04 UTC, archit-harness requested changes
> Reviewed 1 of 18 files at r13, 2 of 7 files at r14, 7 of 15 files at r15, 4 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java` line 19 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqZ_89kWGRBjSQfLC:-NGutQyW9EGCd3crqQOa:b-ctdj9w) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java#L19)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

discussed offline, we should add description yes as a general practice and nothing related to 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 188 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqrx08kYIpTFMvVGg:-NGuv4xM26dlLVB-suPF:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L188)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

discussed offline
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineMetadataServiceImpl.java` line 68 at r17](https://reviewable.io/reviews/harness/harness-core/39869#-NGuxVS_BMraGDiwRfAC:-NGuxVS_BMraGDiwRfAD:b5gnyxq) ([raw file](https://github.com/harness/harness-core/blob/6f595df7ff4dcca0ac29d53f73d302780767d1d0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineMetadataServiceImpl.java#L68)):*
> ```Java
>   }
> 
>   private String getBranchFromGitEntity() {
> ```

this method should be added to GitContextHelper
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 263 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGau65u2djYLwU4lZJC:-NGuwOAc55XMxN7R8gw8:b-vvfhl5) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L263)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

if this method returns empty, there is a check in before we retry from the fall back branch and we skip this
</blockquote></details>

we should return null
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java` line 18 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqjem6zlu0MOBTUt6:-NGuucpzBCTHh95D_N0W:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java#L18)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

inside the contracts, we had the other DTOs. hence placed them here, @archit-harness can you pls suggest if this has to be placed anywhere else?
</blockquote></details>

discussed offline
___
*[`pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java` line 11 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGauBWMDAtvcmFnM0qE:-NGuwvev98KGtVcbZicQ:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java#L11)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

renamed to ExceptionHelper
</blockquote></details>

discussed offline


<!-- Sent from Reviewable.io -->

2022-11-15 11:40 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 19 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 188 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqrx08kYIpTFMvVGg:-NGv2uEQ-ZtF_p4UHLjO:b-b65ig5) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L188)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline
</blockquote></details>

Done. As discussed added a TODO
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineMetadataServiceImpl.java` line 68 at r17](https://reviewable.io/reviews/harness/harness-core/39869#-NGuxVS_BMraGDiwRfAC:-NGv3Hz-5nWx5mmnDXKF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6f595df7ff4dcca0ac29d53f73d302780767d1d0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineMetadataServiceImpl.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this method should be added to GitContextHelper
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 263 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGau65u2djYLwU4lZJC:-NGv3JUs7cc8Rqx-iRr-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L263)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should return null
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java` line 19 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqZ_89kWGRBjSQfLC:-NGv2iWy04ofDQG05m_W:bwzqq1h) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineGetParamsDTO.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline, we should add description yes as a general practice and nothing related to 
</blockquote></details>

Done. As we removed this, DTO no description to be added
___
*[`pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java` line 11 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGauBWMDAtvcmFnM0qE:-NGv4lSqDloOkwEP0SBY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/service/src/main/java/io/harness/utils/Exceptions.java#L11)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java` line 18 at r15](https://reviewable.io/reviews/harness/harness-core/39869#-NGaqjem6zlu0MOBTUt6:-NGv2o700vRKMCNhj3YH:bq2gpcc) ([raw file](https://github.com/harness/harness-core/blob/e363da670718b11de822b32a7e27729197fcc1f6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineRepositoryFindParamsDTO.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline
</blockquote></details>

Done. As discussed removed this class


<!-- Sent from Reviewable.io -->

2022-11-15 11:54 UTC, archit-harness approved these changes
> Reviewed 2 of 3 files at r9, 12 of 13 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-11-15 11:55 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 7 files at r14, 1 of 7 files at r17, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-15 12:25 UTC, archit-harness submitted a review, later dismissed
> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-16 05:12 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39869)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-16 05:13 UTC, merged