feat: [CDS-41932]: artifactory labels
harness/harness-core pull request #39911
Opened 2022-11-10 02:23 UTC by vivekkarnatiharness

## Describe your changes
This is backend changes for artifactory labels support

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-14 02:14 UTC, puthrayaharness requested changes

2022-11-14 02:14 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/service/ArtifactoryRegistryServiceImpl.java
> +      // Catching this exception because artifact repository api is returning 404 for some open source images
Please log the exception

2022-11-14 02:14 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/service/ArtifactoryRegistryServiceImpl.java
> +  public List<Map<String, String>> getLabels(
Please add unit test case

2022-11-14 02:14 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +    List<Map<String, String>> labels;
Please use either `labels` or `label`. Please make sure to be consistent across. 
Please make sure we are consistent between Docker, ECR etc.

2022-11-14 06:06 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java
> +    List<Map<String, String>> labels;
Labels declared here is list of single map.Thats why we have named it as labels, In docker and ecr as well,we are declaring like this

2022-11-14 07:44 UTC, vivekkarnatiharness commented
trigger messagecheck

2022-11-14 10:18 UTC, harshjain12 commented
trigger messagecheck

2022-11-15 02:19 UTC, puthrayaharness approved these changes
> Reviewed 8 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39911)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-15 03:08 UTC, merged