fix: [PLG-1676]: Improve Rbac time
harness/harness-core pull request #39979
Opened 2022-11-10 21:34 UTC by Xin-Harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-11 22:35 UTC, hekimoglu010 submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39979)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-14 06:49 UTC, reetika04 approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39979)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-11-14 18:43 UTC, Xin-Harness commented
trigger messagecheck

2022-11-14 22:01 UTC, nekum1 requested changes

2022-11-14 22:21 UTC, Xin-Harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java
> +    if (!hasAdmin(accountScope)) {
I feel like setupAllLevelRBAC only have assign roles to users scope functionality and nothing else, separate it to another private method wouldn't help increase readability. It is my opinion

2022-11-14 22:39 UTC, nekum1 commented on 120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java
> +    if (!hasAdmin(accountScope)) {
As long as we don't have a huge private methods(> 40 lines of code) we should be good. Was just trying to see if we have an opportunity to modularize a bit. Otherwise looks good to me. Thanks Xin.

2022-11-14 23:32 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39979)* status: 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java` line 198 at r1](https://reviewable.io/reviews/harness/harness-core/39979#-NGYSnbmftBAcUXJxc6Z-r1-198:-NGsU7syDVd1g3kkZF8c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6cd8420378bb075b86b76f954812d409e9eabfc/120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java#L198)):*
<details><summary><i>Previously, nekum1 wrote…</i></summary><blockquote>

As long as we don't have a huge private methods(> 40 lines of code) we should be good. Was just trying to see if we have an opportunity to modularize a bit. Otherwise looks good to me. Thanks Xin.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-15 02:04 UTC, nekum1 approved these changes
LGTM

2022-11-15 17:10 UTC, nekum1 approved these changes

2022-11-15 17:14 UTC, hekimoglu010 approved these changes

2022-11-15 17:15 UTC, Xin-Harness reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39979)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-15 17:27 UTC, nekum1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39979)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-15 17:57 UTC, merged