fix: [CI-5606]: Fetch concurrent executions for CI build types
harness/harness-core pull request #40020
Opened 2022-11-11 11:17 UTC by smjt-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-14 06:06 UTC, aman-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40020)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/CIAccountBuildMetadata.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/40020#-NGoguAl4YJu--p3HlZN:-NGoguAl4YJu--p3HlZO:b-jagkjx) ([raw file](https://github.com/harness/harness-core/blob/69dd7b90a947b01209759b27e921228cf4e42f30/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/CIAccountBuildMetadata.java#L31)):*
> ```Java
> @TypeAlias("ciAccountBuildMetadata")
> @HarnessEntity(exportable = true)
> public class CIAccountBuildMetadata {
> ```

can we rename it to CIExecutionMetadata?
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/CIAccountBuildMetadata.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/40020#-NGoho3M93qrBEtWpuyC:-NGoho3M93qrBEtWpuyD:b-ymzuc5) ([raw file](https://github.com/harness/harness-core/blob/69dd7b90a947b01209759b27e921228cf4e42f30/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/CIAccountBuildMetadata.java#L34)):*
> ```Java
>   @Wither @Id @org.mongodb.morphia.annotations.Id String uuid;
>   String accountId;
>   OSType buildType;
> ```

Can we not hardcode the key as OSType and generate it in code and save it here? It could be of type K8s as well.


<!-- Sent from Reviewable.io -->

2022-11-14 06:09 UTC, aman-harness reviewed
Please make sure that the indexes are created. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40020#-:-NGokJGg3zlEbER8_ew2:b-74ih3k)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-15 07:08 UTC, aman-harness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/QueueExecutionUtils.java
> +  @Inject private CIAccountBuildRepository ciAccountBuildRepository;
CIExecutionRepository Pls rename

2022-11-15 08:50 UTC, smjt-h commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/QueueExecutionUtils.java
> +  @Inject private CIAccountBuildRepository ciAccountBuildRepository;
done

2022-11-15 12:10 UTC, aman-harness approved these changes

2022-11-15 12:10 UTC, aman-harness approved these changes
> Reviewed 2 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40020)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-16 04:39 UTC, merged