fix: [PL-27270]: Fix entity delete response
harness/harness-core pull request #40087
Opened 2022-11-14 08:08 UTC by tiwaritejas

## Describe your changes
Org, project and secrets will throw InvalidRequestException if the entity to be deleted is not present. Earlier, the API call returned success with the data field as false, but now API call will give 400 (Bad Request)
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/40087)

2022-11-14 08:30 UTC, mohitg0795 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGpFUdREa7f3ZtVFXCQ:-NGpFUdREa7f3ZtVFXCR:b-2inrcw) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L563)):*
> ```Java
>               accountIdentifier, orgIdentifier, projectIdentifier);
>       if (projectOptional.isEmpty()) {
>         throw new InvalidRequestException(
> ```

Why is this an exception if entity isn't found? It should not be a failure if thats the case. Even if you want to throw exception, then send custom exception here to highlight that operation didn't fail but the entity itself wasn't found.


<!-- Sent from Reviewable.io -->

2022-11-14 08:30 UTC, mohitg0795 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 560 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGpFjvW0xufyQBlNG5t:-NGpFjvX0peIEMfx98-g:bostfkj) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L560)):*
> ```Java
>     return Failsafe.with(DEFAULT_RETRY_POLICY).get(() -> transactionTemplate.execute(status -> {
>       Optional<Project> projectOptional =
>           projectRepository.findByAccountIdentifierAndOrgIdentifierAndIdentifierIgnoreCase(
> ```

Why do we want to query project in case we just want to delete it? Why can't we just do delete query here?


<!-- Sent from Reviewable.io -->

2022-11-14 08:33 UTC, mohitg0795 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 583 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGpGCs74NFO4_KucxYA:-NGpGCs74NFO4_KucxYB:b-vhs5p0) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L583)):*
> ```Java
>       yamlGitConfigService.deleteAll(accountIdentifier, orgIdentifier, projectIdentifier);
>       outboxService.save(new ProjectDeleteEvent(project.getAccountIdentifier(), ProjectMapper.writeDTO(project)));
>       instrumentationHelper.sendProjectDeleteEvent(project, accountIdentifier);
> ```

We should see how to handle failure of above 3 calls. Currently, if any of them fail, our operation will throw exception while actually project has already been deleted.


<!-- Sent from Reviewable.io -->

2022-11-17 10:47 UTC, tiwaritejas commented
trigger ti0, ti1, ti2, ti3, ti4

2022-11-17 10:51 UTC, tiwaritejas commented
trigger messagecheck

2022-11-18 07:28 UTC, mohitg0795 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 459 at r4](https://reviewable.io/reviews/harness/harness-core/40087#-NH8cuIq22fKKm7Lxf0A:-NH8cuIq22fKKm7Lxf0B:b-g8m51o) ([raw file](https://github.com/harness/harness-core/blob/f0837dbc147a891822638bf3460955c64b623da6/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L459)):*
> ```Java
>         }
>       } else {
>         log.error("Secret with identifier [%s] could not be deleted as it does not exist");
> ```

we haven't logged the identifier here


<!-- Sent from Reviewable.io -->

2022-11-18 07:43 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 11 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 459 at r4](https://reviewable.io/reviews/harness/harness-core/40087#-NH8cuIq22fKKm7Lxf0A:-NH8g75X3QqsnINm-Tpw:b-8tcgjo) ([raw file](https://github.com/harness/harness-core/blob/f0837dbc147a891822638bf3460955c64b623da6/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L459)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we haven't logged the identifier here
</blockquote></details>

Corrected the message
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 560 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGpFjvW0xufyQBlNG5t:-NH8gBkaAX0n93oVstQp:bmghj9w) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L560)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why do we want to query project in case we just want to delete it? Why can't we just do delete query here?
</blockquote></details>

Changed it to use a single delete call
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGpFUdREa7f3ZtVFXCQ:-NH8gA8014Gn70UHQhOr:buac65z) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L563)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is this an exception if entity isn't found? It should not be a failure if thats the case. Even if you want to throw exception, then send custom exception here to highlight that operation didn't fail but the entity itself wasn't found.
</blockquote></details>

Made it a 404 response
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 583 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGpGCs74NFO4_KucxYA:-NH8gGdc6xhItDUpAgNi:bvqejct) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L583)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should see how to handle failure of above 3 calls. Currently, if any of them fail, our operation will throw exception while actually project has already been deleted.
</blockquote></details>

Changed to 404 response


<!-- Sent from Reviewable.io -->

2022-11-18 08:02 UTC, tiwaritejas commented
trigger codebasehash

2022-11-18 08:43 UTC, mohitg0795 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 569 at r4](https://reviewable.io/reviews/harness/harness-core/40087#-NH8tpap-7xs17YrqMNm:-NH8tpap-7xs17YrqMNn:bhorcb0) ([raw file](https://github.com/harness/harness-core/blob/f0837dbc147a891822638bf3460955c64b623da6/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L569)):*
> ```Java
>             projectRepository.hardDelete(accountIdentifier, orgIdentifier, projectIdentifier, version);
> 
>         if (isNull(deletedProject)) {
> ```

ensure that hardDelete call doesn't throw any exception for cases where it doesn't delete anything.


<!-- Sent from Reviewable.io -->

2022-11-18 08:43 UTC, mohitg0795 submitted a review, later dismissed
> Reviewed 7 of 11 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 11 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-18 13:06 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java
> +        throw new InvalidRequestException("Unable to delete secret remotely.", USER);
can we add secret identifier to this log as well?

2022-11-18 13:07 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java
> +        throw new InvalidRequestException("Unable to delete secret locally, data might be inconsistent", USER);
same

2022-11-18 13:08 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java
> +          format("No such secret found [%s], please check identifier/scope and try again.", secretRef.getIdentifier()));
Should we also make this EntityNotFoundException instead of InvalidRequestException?

2022-11-18 13:09 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java
> +              "An organization with identifier [%s] is already present or was deleted", organization.getIdentifier()),
can you check if we hard delete org? If yes then  `or was deleted` should be removed from message (Can be done later as well)

2022-11-18 13:12 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +              "Project with identifier [%s] under organization [%s] could not be deleted as it does not exist",
We are already passing orgId in log context, do we need it here as well?

2022-11-18 13:17 UTC, meenakshi-harness submitted a review, later dismissed
> Reviewed 7 of 11 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 3 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-18 13:21 UTC, mohitg0795 submitted a review, later dismissed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 3 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-20 02:55 UTC, nishantsaini20 requested changes
> Reviewed 7 of 11 files at r2, 1 of 1 files at r3, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 1 change requests. 4. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 451 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGu7f9JBWpIrA37sxTT:-NGu7f9JBWpIrA37sxTU:b-sguzk0) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L451)):*
> ```Java
>     } else {
>       throw new InvalidRequestException(
>           String.format("Secret with identifier: %s does not exist for account: %s organization: %s project: %s",
> ```

Wrap identifiers in square brackets for clear distinction in message.
[%s]
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 450 at r6](https://reviewable.io/reviews/harness/harness-core/40087#-NHHulFJ9yYwgLNGwMsL:-NHHulFKCGcr4yOwMEs9:bw7wmzd) ([raw file](https://github.com/harness/harness-core/blob/e8aba98fca355d479e0edf152b8d672986560073/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L450)):*
> ```Java
>       boolean forceDelete) {
>     try (AutoLogContext ignore1 =
>              new NgAutoLogContext(projectIdentifier, orgIdentifier, accountIdentifier, OVERRIDE_ERROR)) {
> ```

Why this is needed?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 358 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGu82tW6IzCSSNw0roN:-NGu82tW6IzCSSNw0roO:b-5tv8j2) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L358)):*
> ```Java
>       if (organizationOptional.isEmpty()) {
>         throw new InvalidRequestException(
>             String.format("Organization with identifier: %s does not exist for account: %s", organizationIdentifier,
> ```

same here and other messages as well.


<!-- Sent from Reviewable.io -->

2022-11-21 04:27 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 1 change requests. 7. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 451 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGu7f9JBWpIrA37sxTT:-NHNQwUr3TulWcbg56CQ:bk8hppp) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L451)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Wrap identifiers in square brackets for clear distinction in message.
[%s]
</blockquote></details>

I think it is already done for all messages
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 450 at r6](https://reviewable.io/reviews/harness/harness-core/40087#-NHHulFJ9yYwgLNGwMsL:-NHNQdYM0VvU24I8xBY1:bt1xuqk) ([raw file](https://github.com/harness/harness-core/blob/e8aba98fca355d479e0edf152b8d672986560073/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L450)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why this is needed?
</blockquote></details>

For all logs, it will print the project, org and account identifiers. Hence, no need to log them separately in each log message
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 358 at r1](https://reviewable.io/reviews/harness/harness-core/40087#-NGu82tW6IzCSSNw0roN:-NHNR2-F890_WkrAlmC7:bktrv8v) ([raw file](https://github.com/harness/harness-core/blob/ea6feb356510998f41bdf53d3f9956ea10290107/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L358)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

same here and other messages as well.
</blockquote></details>

Already done


<!-- Sent from Reviewable.io -->

2022-11-22 12:46 UTC, meenakshi-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 5 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-22 13:16 UTC, nishantsaini20 approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40087)* status: 5 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-22 13:30 UTC, merged