feat: [CDS-46118]: Migration for onDemandRollback details
harness/harness-core pull request #40117
Opened 2022-11-14 15:17 UTC by Y0709

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-15 17:47 UTC, abhinavmittal-harness approved these changes

2022-11-16 06:15 UTC, Abhishek-CDC requested changes

2022-11-16 06:15 UTC, Abhishek-CDC commented on 400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java
> +        bulkSetOnDemandRollbackDetails(entry.getKey(), COLLECTION_NAME, appId, debugLine, batchLimit,
Even if exception occurred during `bulkSetOnDemandRollbackDetails` it will be catch and accountId will be added to migrated accountId.

2022-11-16 06:15 UTC, Abhishek-CDC commented on 400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java
> +      wingsPersistence.save(migratedAccounts);
save after finished for all accounts

2022-11-16 06:15 UTC, Abhishek-CDC commented on 400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java
> +        new BasicDBObject("accountId", accountId).append("appId", appId).append("onDemandRollback", true);
check for index

2022-11-16 06:21 UTC, Abhishek-CDC commented on 390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddOnDemandRollbackDetailsToDeployment.java
> +
not used anywhere

2022-11-16 07:31 UTC, Y0709 commented on 390-db-migration/src/main/java/io/harness/migrations/timescaledb/data/AddOnDemandRollbackDetailsToDeployment.java
> +
done

2022-11-16 07:32 UTC, Y0709 commented on 400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java
> +      wingsPersistence.save(migratedAccounts);
This we have save everytime because in case the pod gets evicted no accountIds will be saved

2022-11-16 07:53 UTC, Y0709 commented on 400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java
> +        bulkSetOnDemandRollbackDetails(entry.getKey(), COLLECTION_NAME, appId, debugLine, batchLimit,
done

2022-11-16 07:54 UTC, Y0709 commented on 400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java
> +      if (!migratedAccountIds.contains(accountId)) {
Not needed as not big effect

2022-11-17 09:45 UTC, Y0709 commented on 400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java
> +        new BasicDBObject("accountId", accountId).append("appId", appId).append("onDemandRollback", true);
done

2022-11-18 02:20 UTC, Abhishek-CDC commented
*[`400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/40117#-NGqhr1z1nqAALUnEJ1Q-r2-100:-NH7WIwQEQ2FDq6Fnixn:b3kz69c) ([raw file](https://github.com/harness/harness-core/blob/06d587e6706940376bb680d40d8b1441cceca5ee/400-rest/src/main/java/software/wings/timescale/migrations/DeploymentsMigrationHelper.java#L100)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

done
</blockquote></details>

logic is wrong. if migration was successful for last appId, it will save that accountId. it should pass for every appId.
Suggested approach: make success as true and check response of bulkSetOnDemandRollbackDetails() for every appId, make success false if got false even one time in response.


<!-- Sent from Reviewable.io -->

2022-11-18 05:40 UTC, Abhishek-CDC reviewed
> Reviewed 1 of 18 files at r1, 14 of 15 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-18 05:42 UTC, Abhishek-CDC approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117#-:-NH8FarY2tN-9uccP49c:bnfp4nl)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-18 05:43 UTC, abhinavmittal-harness reviewed
> Reviewed 1 of 18 files at r1, 1 of 15 files at r2, 1 of 4 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-18 06:06 UTC, abhinavmittal-harness approved these changes
> Reviewed 13 of 15 files at r2, 1 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-18 07:25 UTC, Abhishek-CDC approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-18 18:01 UTC, Y0709 commented
Merge after branch cut to properly test in qa

2022-11-21 09:40 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-21 23:43 UTC, abhinavmittal-harness approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-22 06:01 UTC, Abhishek-CDC approved these changes

2022-11-22 06:01 UTC, Abhishek-CDC approved these changes
> Reviewed 2 of 3 files at r6, 3 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40117)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-22 06:02 UTC, merged