feat: [CDS-45642]: ECS NG S3 Store Feature
harness/harness-core pull request #40149
Opened 2022-11-15 05:39 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-15 11:28 UTC, alluvamsi-harness commented
trigger feature-build

2022-11-16 02:02 UTC, sainath-b commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsS3FetchTask.java
> +  private DelegateResponseData getEcsS3CommandResponse(
These methods need to be moved to a Handler calss.

2022-11-16 02:33 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +    AtomicBoolean isGitManifest = new AtomicBoolean(false);
Any specific reason why we are using atomic boolean here?

2022-11-16 02:35 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +  public boolean checkForS3Manifest(List<ManifestOutcome> ecsManifestsOutcome) {
We can use better method naming here. 'checkForS3Manifest' can be called 'isAnyS3Manifest'

2022-11-16 02:40 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java
> +@TypeAlias("ecsGitFetchPassThroughData")
It should be 'ecsS3FetchPassThroughData'?

2022-11-16 04:20 UTC, sainath-b commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsS3FetchTask.java
> +        .taskStatus(TaskStatus.SUCCESS)
When are we setting Task Status as 'FAILURE'.? I don't see try catch as well.

2022-11-16 05:33 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +    AtomicBoolean isGitManifest = new AtomicBoolean(false);
no reason changing it

2022-11-16 06:42 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +    AtomicBoolean isS3Manifest = new AtomicBoolean(false);
no reason changing it

2022-11-16 06:55 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsS3FetchTask.java
> +  private DelegateResponseData getEcsS3CommandResponse(
done

2022-11-16 06:55 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +    AtomicBoolean isS3Manifest = new AtomicBoolean(false);
Done

2022-11-16 06:55 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +    AtomicBoolean isGitManifest = new AtomicBoolean(false);
Done

2022-11-16 06:55 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +  public boolean checkForGitManifest(List<ManifestOutcome> ecsManifestsOutcomes) {
Done

2022-11-16 06:55 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepUtils.java
> +  public boolean checkForS3Manifest(List<ManifestOutcome> ecsManifestsOutcome) {
Done

2022-11-16 07:03 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java
> +@TypeAlias("ecsGitFetchPassThroughData")
Done

2022-11-16 07:43 UTC, USB-05 commented
trigger sswc

2022-11-16 09:24 UTC, USB-05 commented
trigger sswc

2022-11-17 11:10 UTC, alluvamsi-harness commented
trigger ti3

2022-11-17 18:33 UTC, alluvamsi-harness commented
trigger feature-build

2022-11-18 10:47 UTC, PragyeshMishra01 requested changes
> Reviewed 8 of 28 files at r1, 21 of 22 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 429 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH95itH0RZ1YWXph6KH:-NH95itH0RZ1YWXph6KI:b8lmbzt) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L429)):*
> ```Java
>         .encryptedDataDetails(
>             k8sEntityHelper.getEncryptionDataDetails(awsConnectorDTO, AmbianceUtils.getNgAccess(ambiance)))
>         .build();
> ```

why are we using k8sEntityHelper class here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1142 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH9HQXh3Xyb4UNJHC7f:-NH9HQXh3Xyb4UNJHC7g:b-8t39h5) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1142)):*
> ```Java
>     if (CollectionUtils.isNotEmpty(ecsOtherStoreContent.getEcsScalableTargetManifestContentList())) {
>       ecsScalableTargetFileContentList.addAll(ecsOtherStoreContent.getEcsScalableTargetManifestContentList());
>     }
> ```

In case of ecsOtherStoreContent, don't we need to render expressions?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH9K7ov8BAMtoPrpWJ9:-NH9K7ov8BAMtoPrpWJA:b-s0spq5) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java#L27)):*
> ```Java
> public class EcsS3FetchPassThroughData implements PassThroughData {
>   String otherStoreTargetGroupArnKey;
>   InfrastructureOutcome infrastructureOutcome;
> ```

what does otherStoreTargetGroupArnKey mean in terms of naming?  How is it depending on store? 
I am seeing that we have used otherStore prefix for some variables. 


<!-- Sent from Reviewable.io -->

2022-11-18 11:38 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 429 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH95itH0RZ1YWXph6KH:-NH9WoJW2VDmse_deQPt:b-a9q4c4) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L429)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

why are we using k8sEntityHelper class here?
</blockquote></details>

working
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1142 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH9HQXh3Xyb4UNJHC7f:-NH9WVNo94oyMZPHCITx:by3058p) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1142)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

In case of ecsOtherStoreContent, don't we need to render expressions?
</blockquote></details>

No need they are the otherStoreContents(Git,Harness) which are already rendered 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH9K7ov8BAMtoPrpWJ9:-NH9WyE0Ai4f5UrzMES1:b9g4gsl) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java#L27)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

what does otherStoreTargetGroupArnKey mean in terms of naming?  How is it depending on store? 
I am seeing that we have used otherStore prefix for some variables. 
</blockquote></details>

The otherStore in S3 means the data which they are carrying is from Git or Harness Store
eg: In EcsS3FetchPassThroughData the otherStoreTargetArnKey is either from the Service Definition of Git or Harness Store but not from S3


<!-- Sent from Reviewable.io -->

2022-11-18 11:52 UTC, PragyeshMishra01 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1142 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH9HQXh3Xyb4UNJHC7f:-NH9_GvG3hKGUFT5A8Qa:b-y8hgn1) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1142)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

No need they are the otherStoreContents(Git,Harness) which are already rendered 
</blockquote></details>

Okay, then its good.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH9K7ov8BAMtoPrpWJ9:-NH9Zsd634ZYuYS_ij7d:b151596) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java#L27)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

The otherStore in S3 means the data which they are carrying is from Git or Harness Store
eg: In EcsS3FetchPassThroughData the otherStoreTargetArnKey is either from the Service Definition of Git or Harness Store but not from S3
</blockquote></details>

if they belong to harness or git store, then why are we putting them inside EcsS3FetchPassThroughData  class?


<!-- Sent from Reviewable.io -->

2022-11-18 13:16 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH9K7ov8BAMtoPrpWJ9:-NH9rcPv0RjbTwR9WTrG:b-v0jd30) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsS3FetchPassThroughData.java#L27)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

if they belong to harness or git store, then why are we putting them inside EcsS3FetchPassThroughData  class?
</blockquote></details>

The only way to pass the harness , gits files to EcsCommand Task is through the S3 Task so they are passed as passThrough
PassThroughData contains the data which we will use in future task but may not be used in current task if a right
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsS3FetchTask.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/40149#-NGtnDSr6hvxP3_d5CQG-r1-146:-NH9rRKk7zFlyK7qI9I6:b-896fjx) ([raw file](https://github.com/harness/harness-core/blob/b69cd7845c64897a6fbfaeec121381b425d112c0/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsS3FetchTask.java#L146)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

When are we setting Task Status as 'FAILURE'.? I don't see try catch as well.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-18 14:45 UTC, PragyeshMishra01 approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-18 14:45 UTC, PragyeshMishra01 approved these changes

2022-11-23 09:22 UTC, alluvamsi-harness commented
trigger ft1
trigger ft0

2022-11-23 09:23 UTC, alluvamsi-harness commented
trigger ft1

2022-11-29 04:46 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java
> +      case AWS:
@alluvamsi-harness lets discuss on why this code is needed. is it method not present already?

2022-11-29 11:09 UTC, alluvamsi-harness commented
trigger codebasehash

2022-11-29 12:42 UTC, sainath-b approved these changes

2022-11-29 12:43 UTC, sainath-b reviewed
> Reviewed 1 of 28 files at r1, 1 of 22 files at r2, 1 of 8 files at r6, 1 of 34 files at r8, 30 of 34 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 38 file(s) to review. 8. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-29 12:46 UTC, sainath-b approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 38 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-29 13:31 UTC, PragyeshMishra01 approved these changes

2022-11-30 14:26 UTC, alluvamsi-harness commented
trigger ti0

2022-11-30 14:27 UTC, alluvamsi-harness commented
trigger ti1

2022-11-30 17:22 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 22 files at r2, 8 of 34 files at r11, 1 of 6 files at r12, 1 of 7 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 30 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-30 18:25 UTC, alluvamsi-harness commented
trigger smartchecks

2022-12-01 03:11 UTC, sainath-b approved these changes

2022-12-01 03:12 UTC, sainath-b approved these changes
> Reviewed 6 of 7 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 28 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-01 04:45 UTC, PragyeshMishra01 approved these changes

2022-12-01 04:49 UTC, PragyeshMishra01 reviewed
> Reviewed 1 of 8 files at r6, 22 of 34 files at r11, 6 of 6 files at r12, 6 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-01 04:50 UTC, PragyeshMishra01 approved these changes
> Reviewed 3 of 34 files at r11, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-01 04:52 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 2. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 429 at r4](https://reviewable.io/reviews/harness/harness-core/40149#-NH95itH0RZ1YWXph6KH:-NIAfFUj-hPqs_r8xmGz:b9lmg9q) ([raw file](https://github.com/harness/harness-core/blob/680a9b528f1cbee74ef43f8a285a60da855eca74/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L429)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

working
</blockquote></details>

Not changing it as discussed in call


<!-- Sent from Reviewable.io -->

2022-12-01 04:57 UTC, alluvamsi-harness reviewed
> Reviewed 1 of 28 files at r1, 1 of 8 files at r6, 22 of 34 files at r11, 6 of 6 files at r12, 6 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-01 05:10 UTC, PragyeshMishra01 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-01 06:42 UTC, yogesh-chauhan reviewed
> Reviewed 8 of 9 files at r15.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 9 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-01 06:43 UTC, yogesh-chauhan reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 9 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-01 06:43 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 28 files at r1, 1 of 8 files at r6, 17 of 34 files at r11, 5 of 6 files at r12, 1 of 9 files at r15.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 9 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-01 09:44 UTC, sainath-b approved these changes

2022-12-01 09:45 UTC, sainath-b approved these changes
> Reviewed 8 of 9 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-01 09:51 UTC, PragyeshMishra01 approved these changes

2022-12-01 09:52 UTC, PragyeshMishra01 approved these changes
> Reviewed 8 of 9 files at r15, 1 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-12-01 09:56 UTC, PragyeshMishra01 approved these changes
> Reviewed 1 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-01 09:58 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40149)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-01 11:35 UTC, merged