[fix]: [PIE-6214]: Corrected Get call for pipeline while getting inputSet for execution, so that it includes branch in find query
harness/harness-core pull request #40416
Opened 2022-11-21 08:08 UTC by senjucanon2

## Describe your changes:
Issue: Runtime Inputs were not being showed while viewing execution History because get call for pipeline in default branch was failing in get flow for inputsets.
Change: Now whenever exception is thrown it will be catched and instead null pipelineEntity will be returned.
Testing: Expected behaviour observed on local.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-21 08:21 UTC, senjucanon2 commented
trigger messagecheck

2022-11-21 11:05 UTC, senjucanon2 commented
trigger messagecheck

2022-11-21 11:15 UTC, senjucanon2 commented
trigger ti4

2022-11-21 11:18 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 418 at r2](https://reviewable.io/reviews/harness/harness-core/40416#-NHOuH8u0RHIBfGHJIB_:-NHOuH8u0RHIBfGHJIBa:buk530j) ([raw file](https://github.com/harness/harness-core/blob/e3ac616cdc43951860e2ef37bbacfd1107bbf8d7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L418)):*
> ```Java
> 
>       EntityGitDetails entityGitDetails =
>           pmsGitSyncHelper.getEntityGitDetailsFromBytes(executionSummaryEntity.getGitSyncBranchContext());
> ```

what if entityGitDetails is null?


<!-- Sent from Reviewable.io -->

2022-11-21 11:19 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 432 at r2](https://reviewable.io/reviews/harness/harness-core/40416#-NHOuNDP0X9KPpYyUUcr:-NHOuNDP0X9KPpYyUUcs:b-49zwie) ([raw file](https://github.com/harness/harness-core/blob/e3ac616cdc43951860e2ef37bbacfd1107bbf8d7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L432)):*
> ```Java
>       }
>       if (EmptyPredicate.isEmpty(template) && EmptyPredicate.isNotEmpty(yaml)) {
>         template = latestTemplate;
> ```

I think this is wrong, let's just remove this if altogether


<!-- Sent from Reviewable.io -->

2022-11-21 11:19 UTC, sahilhindwani-harness requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40416)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-21 12:43 UTC, senjucanon2 commented
trigger ss

2022-11-21 14:10 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40416)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 418 at r2](https://reviewable.io/reviews/harness/harness-core/40416#-NHOuH8u0RHIBfGHJIB_:-NHPVvHH-FzmWCmC6V9h:b-cbgkn3) ([raw file](https://github.com/harness/harness-core/blob/e3ac616cdc43951860e2ef37bbacfd1107bbf8d7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L418)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

what if entityGitDetails is null?
</blockquote></details>

Have added a null check for it
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 432 at r2](https://reviewable.io/reviews/harness/harness-core/40416#-NHOuNDP0X9KPpYyUUcr:-NHPVxg9-5sDFc_u0OvR:b-k90mqx) ([raw file](https://github.com/harness/harness-core/blob/e3ac616cdc43951860e2ef37bbacfd1107bbf8d7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L432)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think this is wrong, let's just remove this if altogether
</blockquote></details>

I have just removed the redundant part of code, didn't wanted to change the backward compatibility for which this was introduced, may cause regressions


<!-- Sent from Reviewable.io -->

2022-11-22 06:31 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40416)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-22 11:37 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40416)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-23 10:31 UTC, senjucanon2 commented
Closing this as will be removing this get call altogether, after UI had made it changes.

2022-11-24 05:17 UTC, namanvermah commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +      try (PmsGitSyncBranchContextGuard ignored = new PmsGitSyncBranchContextGuard(gitSyncBranchContext, true)) {
you dont need guard here, the method you're calling in the guard creates its own guard. Can you check

2022-11-24 05:41 UTC, namanvermah approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40416)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-24 05:44 UTC, namanvermah approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40416)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-11-24 05:44 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40416)* status: 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 458 at r5](https://reviewable.io/reviews/harness/harness-core/40416#-NHODxuiigD9q0eQjmbq-r5-458:-NHc9WtN2YE684VEgAIH:b-y60xen) ([raw file](https://github.com/harness/harness-core/blob/1e350ea3b46542971b9909f2bfd186a3f932eb69/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L458)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

you dont need guard here, the method you're calling in the guard creates its own guard. Can you check
</blockquote></details>

I check for some case guard is not set


<!-- Sent from Reviewable.io -->

2022-11-24 05:47 UTC, merged