feat: [DEL-5320]: proto acquire task
harness/harness-core pull request #40469
Opened 2022-11-21 21:50 UTC by mdmilic

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-01 21:09 UTC, raghuAtWings commented
description and testing is missing





<!-- Sent from Reviewable.io -->

2022-12-01 21:12 UTC, raghuAtWings commented
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/acquire_task.proto` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/40469#-NIEX4590pPRhWyFYO2U:-NIEX45A0MH1e7kIF9Nz:bg0p2zf) ([raw file](https://github.com/harness/harness-core/blob/1b07aee310cad184a8ec1e71585e4dfcca534572/955-delegate-beans/src/main/proto/io/harness/delegate/core/acquire_task.proto#L18)):*
> ```protobuf
>  */
> message AcquireTasksResponse {
>   AgentData agent_data = 1;
> ```

remove agent_data


<!-- Sent from Reviewable.io -->

2022-12-01 21:19 UTC, raghuAtWings commented
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/40469#-NIEYeR7DfguAJ7_QgN1:-NIEYeR7DfguAJ7_QgN2:bulffsq) ([raw file](https://github.com/harness/harness-core/blob/1b07aee310cad184a8ec1e71585e4dfcca534572/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L34)):*
> ```protobuf
>  */
> enum TaskMode {
>   MODE_UNKNOWN = 0;
> ```

put a comment why unknown is added and should never be used. Put assertions to make sure its not used. 


<!-- Sent from Reviewable.io -->

2022-12-01 21:23 UTC, raghuAtWings commented
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/40469#-NIEZdvc2_gERUjXXgHb:-NIEZdvc2_gERUjXXgHc:b-8p5lrs) ([raw file](https://github.com/harness/harness-core/blob/1b07aee310cad184a8ec1e71585e4dfcca534572/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L112)):*
> ```protobuf
> }
> 
> message Resource {
> ```

put comments on each of these describing what each one of them are. 


<!-- Sent from Reviewable.io -->

2022-12-01 21:32 UTC, raghuAtWings commented
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/core/CoreDelegateResource.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/40469#-NIEalMyC-_YJ6ickfjy:-NIEalMzEdgIvYxvtVqV:b-b71n88) ([raw file](https://github.com/harness/harness-core/blob/1b07aee310cad184a8ec1e71585e4dfcca534572/420-delegate-service/src/main/java/io/harness/delegate/resources/core/CoreDelegateResource.java#L99)):*
> ```Java
>                                                .setMemory(1024)
>                                                .setCpu(1)
>                                                .setTimeout(Duration.newBuilder().setSeconds(600).build())
> ```

timeout should get from task


<!-- Sent from Reviewable.io -->

2022-12-01 21:34 UTC, raghuAtWings commented
*[`260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources/k8s_task_template.yaml` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/40469#-NIEb7J_D-pY_L6PYEnl:-NIEb7J_D-pY_L6PYEnm:bfo8r1v) ([raw file](https://github.com/harness/harness-core/blob/1b07aee310cad184a8ec1e71585e4dfcca534572/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources/k8s_task_template.yaml#L19)):*
> ```YAML
>               memory: "512Mi"
>             requests:
>               cpu: "0.5"
> ```

cpu: 0.1 and memory 128Mi



_Code quote:_
```YAML
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
```


<!-- Sent from Reviewable.io -->

2022-12-01 21:42 UTC, raghuAtWings reviewed
> Reviewed 8 of 17 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: Some of the checks are too old. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-20 02:33 UTC, xingchi-jin requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: Some of the checks are too old. 26 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/40469#-NJhMi7978sNPecqBtCl:-NJhMi7978sNPecqBtCm:biut46a) ([raw file](https://github.com/harness/harness-core/blob/9231e794605dcc8f687f27ac5a4ec0a098fab8a3/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L49)):*
> ```protobuf
> 
> message PluginSecret {
>   repeated PluginInput secrets = 1;
> ```

how to denote the secretRef  from steps yaml in here ?
The ExecutionEnvironment is defined in PluginSecret, does it mean it will be a "plugin" to fetch the secret and resolve it? 


<!-- Sent from Reviewable.io -->

2023-01-17 22:20 UTC, raghuAtWings submitted a review, later dismissed
> Reviewed 22 of 25 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: Some of the checks are too old. 1 change requests. 



<!-- Sent from Reviewable.io -->

2023-01-18 09:59 UTC, xingchi-jin submitted a review, later dismissed
> Reviewed 6 of 17 files at r1, 4 of 13 files at r2, 22 of 25 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-02-15 19:29 UTC, mdmilic reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: 46 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/40469#-NJhMi7978sNPecqBtCl:-NOLY0vf5nSy_CkBpfpq:b38j1s3) ([raw file](https://github.com/harness/harness-core/blob/9231e794605dcc8f687f27ac5a4ec0a098fab8a3/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L49)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

how to denote the secretRef  from steps yaml in here ?
The ExecutionEnvironment is defined in PluginSecret, does it mean it will be a "plugin" to fetch the secret and resolve it? 
</blockquote></details>

Yes, just different type of plugin. Secret providers are also plugins that are used to decrypt secrets as opposed to task plugins that actually use secrets and execute tasks. 


<!-- Sent from Reviewable.io -->

2023-02-16 07:12 UTC, gn-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: 47 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/BUILD.bazel` line 94 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NONqvvV7ZNQq5llktkQ:-NONqvvV7ZNQq5llktkR:baxer2a) ([raw file](https://github.com/harness/harness-core/blob/b1c0c63842f860999b7ef328ae302465f4b5e689/260-delegate/BUILD.bazel#L94)):*
> ```Starlark
>     resources = [
>         "//:resource",
>         "//260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources:resource",
> ```

relevant to this PR?
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO21h_4F4Rhfst1GpG:-NOO21h_4F4Rhfst1GpH:bdw5cg4) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L18)):*
> ```protobuf
>  All data that is needed to execute the job
>  */
> message PluginDescriptor {
> ```

Why plugin? but not just a task?



_Code quote:_
```protobuf
PluginDescriptor
```
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO3CEM261uReSKPtzm:-NOO3CEM261uReSKPtzn:b-ofkr5w) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L18)):*
> ```protobuf
>  All data that is needed to execute the job
>  */
> message PluginDescriptor {
> ```

This proto file can just be a PR on its own -- establishes the contact and then the code can follows



_Code quote:_
```protobuf
syntax = "proto3";

package io.harness.delegate.core;

option java_multiple_files = true;

import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";

/*
 All data that is needed to execute the job
 */
message PluginDescriptor {
```
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 19 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2-ef9ZiAuuII1w6o:-NOO2-ef9ZiAuuII1w6p:b-nwqwtc) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L19)):*
> ```protobuf
>  */
> message PluginDescriptor {
>   string id = 1;
> ```

Is this like a task id?



_Code quote:_
```protobuf
string id = 1;
```
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 48 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO1vtSEePSBvURw6R-:-NOO1vtSEePSBvURw6R0:bwn98ex) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L48)):*
> ```protobuf
>   PRIORITY_DEFAULT = 1;
>   PRIORITY_HIGH = 2;
> }
> ```

Do we have such abilities today?



_Code quote:_
```protobuf
enum ExecutionPriority {
  PRIORITY_UNKNOWN = 0;
  PRIORITY_DEFAULT = 1;
  PRIORITY_HIGH = 2;
}
```
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2xKl4nY5Qst5GghW:-NOO2xKl4nY5Qst5GghX:b3gv6ta) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L64)):*
> ```protobuf
> message ExecutionEnvironment {
>   PluginType type = 1;
>   PluginSource source = 2;
> ```

These don't seem to execution environment, rather metadata about the task itself?



_Code quote:_
```protobuf
  PluginType type = 1;
  PluginSource source = 2;
```
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 65 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2kY69sxfd9N3MF4W:-NOO2kY69sxfd9N3MF4X:bkn2nr8) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L65)):*
> ```protobuf
>   PluginType type = 1;
>   PluginSource source = 2;
>   string using = 3;
> ```

using? probably add some comments on these fields?



_Code quote:_
```protobuf
 string using = 3;
```
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 145 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2ZdEB07TqWqYKFzt:-NOO2ZdEB07TqWqYKFzu:b2auuw1) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L145)):*
> ```protobuf
>  Type of the plugin, can be anything from enum TaskType or any additional 3rd party plugins
>  */
> message PluginType {
> ```

why need this wrapper?



_Code quote:_
```protobuf
message PluginType {
```


<!-- Sent from Reviewable.io -->

2023-02-20 14:31 UTC, mdmilic commented
trigger feature-build

2023-02-20 22:33 UTC, mdmilic reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: Some of the checks are too old. 47 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/BUILD.bazel` line 94 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NONqvvV7ZNQq5llktkQ:-NOkqstr1sU0pc9BJeIu:bk5tedg) ([raw file](https://github.com/harness/harness-core/blob/b1c0c63842f860999b7ef328ae302465f4b5e689/260-delegate/BUILD.bazel#L94)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

relevant to this PR?
</blockquote></details>

Yes, I stopped using template for the task Job, instead I just generate all in code. Initially template was making sense, but now everything gets customized. 
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO3CEM261uReSKPtzm:-NOkr5h2Ee0D9MqO2R11:b-xyme8b) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L18)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

This proto file can just be a PR on its own -- establishes the contact and then the code can follows
</blockquote></details>

I tried that initially, but it was hard to imagine how the proto should look like until I start using it. That's why the ticket was parked for a while until I can start using proto to finalize it. 
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO21h_4F4Rhfst1GpG:-NOkrd3LE5feux-0WfJ0:bsvljmj) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L18)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Why plugin? but not just a task?
</blockquote></details>

Yeah, naming this stuff was hard. I switched between plugin and task multiple times. We even started making glossary to better understand naming conventions. Plugin is the thing that people provide as delegate extensions (so anything related to that should have plugin in the name), one instance of plugin execution is task. I think probably better name for this would be TaskDescriptor (because it describes one instance of the execution).
Brad has few doc about naming conventions (for pipeline yamls specifically), but I was trying to follow the style he proposed there since those yamls should more or less map to this API. 
Here's one
https://harness.atlassian.net/wiki/spaces/~5f1f0648e8c4560022265233/pages/21100134856/RFC-005+-+Yaml+Syntax+Simplification#Plugin

Will change this to TaskDescriptor. 
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 19 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2-ef9ZiAuuII1w6o:-NOkrVqH9DqJynabGe7h:b-165uuq) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L19)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Is this like a task id?
</blockquote></details>

Yes. Again following
https://harness.atlassian.net/wiki/spaces/~5f1f0648e8c4560022265233/pages/21100134856/RFC-005+-+Yaml+Syntax+Simplification#Abbreviations
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 48 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO1vtSEePSBvURw6R-:-NOku5Q89oEJEp7cT7lh:b-p6o1ye) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L48)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Do we have such abilities today?
</blockquote></details>

Yes & no. We have sync & async tasks. We run sync tasks in separate thread pool just for them. The idea is that someone (e.,g. UI) is waiting for sync task to complete, but for delegate all tasks are async. That's why I changed the paradigm. Delegate will not have sync/async tasks, but only async + priority. async + high priority should be old sync tasks for now. The design proposal goes on on how we can deal with priorities. 
Here in general: https://harness.atlassian.net/wiki/spaces/~686770990/pages/21186053409/Delegate+Platform+Architecture#Sync-Tasks
And for K8S Runner specifically (not nearly implemented): https://harness.atlassian.net/wiki/spaces/~686770990/pages/21186053409/Delegate+Platform+Architecture#Task-Priority
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2xKl4nY5Qst5GghW:-NOkw0Ig-Qi_37odASQF:b-z7g0w7) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L64)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

These don't seem to execution environment, rather metadata about the task itself?
</blockquote></details>

That's true. It's defining the plugin that will be executed in the execution environment. How do you think I should change it?
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 65 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2kY69sxfd9N3MF4W:-NOkvpqV2ulBIfJIRZV-:bto60xz) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L65)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

using? probably add some comments on these fields?
</blockquote></details>

Yes, this was again following Brads proposal. His is actually 'uses'. Will add docs. 
https://harness.atlassian.net/wiki/spaces/~5f1f0648e8c4560022265233/pages/21197979662/RFC-009+-+Plugins+without+Containers
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 145 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2ZdEB07TqWqYKFzt:-NOkwSV58xYYrhszSbgW:be17ha8) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L145)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

why need this wrapper?
</blockquote></details>

Can't recall, it probably had more info that got removed, can probably unbox it. 


<!-- Sent from Reviewable.io -->

2023-02-21 17:40 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: Some of the checks are too old. 47 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/k8s/K8STaskRunner.java` line 145 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp2vMV1Xewc-DVez80:-NOp2vMV1Xewc-DVez81:bw148sp) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/K8STaskRunner.java#L145)):*
> ```Java
>   }
> 
>   private V1ConfigMap createTaskConfig(final String taskId, final PluginDescriptor descriptor) throws ApiException {
> ```

maybe we can put task data also in Secret, optional 
___
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java` line 244 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp0r6b1RtTEmfvgukr:-NOp0r6c3yXtZ8XqyFR2:b946yvf) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java#L244)):*
> ```Java
>   @Consumes({"application/x-protobuf"})
>   @PUT("agent/delegates/task-progress/status/v2")
>   Call<SendTaskStatusResponse> sendTaskStatusV2(
> ```

why these need v2 ?
___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/core/CoreDelegateResource.java` line 108 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp1E5FDMEfOgW8VSXA:-NOp1E5FDMEfOgW8VSXB:b51291i) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/420-delegate-service/src/main/java/io/harness/delegate/resources/core/CoreDelegateResource.java#L108)):*
> ```Java
>                       .setUsing("us.gcr.io/gcr-play/delegate-plugin:k8s")
>                       .setResource(ResourceRequirements.newBuilder()
>                                        .setMemory("128Mi")
> ```

do you prefer the manager to guide the task containers to use memory and cpus ? or should it be controlled by the task side by the cd/ci teams ?
do you think if we can make these configurations loaded from a directory ?  
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/BUILD.bazel` line 22 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOoxVxz0DKWq90judvD:-NOoxVxz0DKWq90judvE:bggdltn) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/BUILD.bazel#L22)):*
> ```Starlark
> )
> 
> # FixMe: Don't use harness_grpc_library, use java_proto_library instead
> ```

maybe we can log jira, for important ones 
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 99 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp2CQh-03aC9-E9QeZ:-NOp2CQh-03aC9-E9Qe_:bsxzte7) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L99)):*
> ```protobuf
>   // TODO: apart from basic infra details we need some sort of credentials or connector information here
>   // e.g. imagePullSecret for pulling private images (not sure connector is useful for that since it's not delegate that
>   // pull image, it provides them for K8S) or GH credentials to do git clone etc...
> ```

will Files, variables, templates be related here ? 


<!-- Sent from Reviewable.io -->

2023-02-21 17:42 UTC, xingchi-jin reviewed
mostly looks good, i had looked at this PR previously too. 
I will LG after my current comments are answered 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469#-:-NOp3Jqr2GBKwQtVo5rr:b-nf9qhd)* status: Some of the checks are too old. 47 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-21 20:03 UTC, mdmilic reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: Some of the checks are too old. 47 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/k8s/K8STaskRunner.java` line 145 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp2vMV1Xewc-DVez80:-NOpXx7d33bCtI5yvDv_:b-7tdf7d) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/K8STaskRunner.java#L145)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

maybe we can put task data also in Secret, optional 
</blockquote></details>

agree
___
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java` line 244 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp0r6b1RtTEmfvgukr:-NOpYhQU5EK-pNRaM8cl:b-9byjqf) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java#L244)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why these need v2 ?
</blockquote></details>

no clue what those are, I didn't add them. They don't seem to be used. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/core/CoreDelegateResource.java` line 108 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp1E5FDMEfOgW8VSXA:-NOpYmuy-7G7xpK4XKSz:belzvuu) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/420-delegate-service/src/main/java/io/harness/delegate/resources/core/CoreDelegateResource.java#L108)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

do you prefer the manager to guide the task containers to use memory and cpus ? or should it be controlled by the task side by the cd/ci teams ?
do you think if we can make these configurations loaded from a directory ?  
</blockquote></details>

Eventually it should be controlled by the UI (similar to CI tasks right now where you can specify the CPU/Memory/timeout). If not specified we should assume reasonable defaults, that can be per task type for harness tasks or global for others. Right now since there are no incoming APIs that provide this information I hardcoded the values. 
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/BUILD.bazel` line 22 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOoxVxz0DKWq90judvD:-NOpZFoYAXZiHqA0y1jw:bktrv8v) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/BUILD.bazel#L22)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

maybe we can log jira, for important ones 
</blockquote></details>

Already done
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 99 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOp2CQh-03aC9-E9QeZ:-NOpZUtzC6_z6NdV5qFv:b-fddt2r) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L99)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

will Files, variables, templates be related here ? 
</blockquote></details>

Not sure I understand the question, but I don't know exactly how the infra info should look like until we start using it. 


<!-- Sent from Reviewable.io -->

2023-02-21 20:16 UTC, xingchi-jin approved these changes
> Reviewed 2 of 13 files at r2, 41 of 46 files at r5, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: 1 change requests. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-21 21:16 UTC, gn-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: 4. unresolved discussions. 

___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO21h_4F4Rhfst1GpG:-NOpoZKnETdHnirohZ1P:brxp9sd) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L18)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Yeah, naming this stuff was hard. I switched between plugin and task multiple times. We even started making glossary to better understand naming conventions. Plugin is the thing that people provide as delegate extensions (so anything related to that should have plugin in the name), one instance of plugin execution is task. I think probably better name for this would be TaskDescriptor (because it describes one instance of the execution).
Brad has few doc about naming conventions (for pipeline yamls specifically), but I was trying to follow the style he proposed there since those yamls should more or less map to this API. 
Here's one
https://harness.atlassian.net/wiki/spaces/~5f1f0648e8c4560022265233/pages/21100134856/RFC-005+-+Yaml+Syntax+Simplification#Plugin

Will change this to TaskDescriptor. 
</blockquote></details>

Sounds good!
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/40469#-NOO2xKl4nY5Qst5GghW:-NOppHjD8RlpECPTmXHa:b-pam3gv) ([raw file](https://github.com/harness/harness-core/blob/01a38f6b2255680fd88b8ecf555d30d8c06d11ff/955-delegate-beans/src/main/proto/io/harness/delegate/core/plugin.proto#L64)):*
> https://harness.atlassian.net/wiki/spaces/~686770990/pages/21186053409/Delegate+Platform+Architecture#Sync-Tasks
Will add ideas to the next PR


<!-- Sent from Reviewable.io -->

2023-02-21 21:17 UTC, gn-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-21 22:30 UTC, gn-harness approved these changes
> Reviewed 2 of 13 files at r2, 1 of 25 files at r3, 40 of 46 files at r5, 5 of 6 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-21 23:38 UTC, xingchi-jin approved these changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40469)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-22 01:11 UTC, raghuAtWings commented
*[`260-delegate/src/main/java/io/harness/delegate/service/common/client/CommonDelegateManagerClient.java` line 28 at r9](https://reviewable.io/reviews/harness/harness-core/40469#-NOqf2hX5s2LUA7yoa2q:-NOqf2hX5s2LUA7yoa2r:b-quezp8) ([raw file](https://github.com/harness/harness-core/blob/a8c0160046d583c90e05228f3f37f93726f49976/260-delegate/src/main/java/io/harness/delegate/service/common/client/CommonDelegateManagerClient.java#L28)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.DEL)
> public interface CommonDelegateManagerClient {
> ```

why there are two of these clients?


<!-- Sent from Reviewable.io -->

2023-02-22 12:23 UTC, AnshuH commented
trigger ut1

2023-02-22 12:25 UTC, AnshuH commented
trigger utAll

2023-02-22 18:19 UTC, merged