feat: [SRM-12787]: Composite SLO graph API for the onboarding page.
harness/harness-core pull request #40473
Opened 2022-11-22 02:49 UTC by sathish-soundarapandian

## Describe your changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-22 07:04 UTC, Varsha-lalwani requested changes
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40473)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecord.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/40473#-NHT8dbE2Xz3-8qLrAuJ:-NHT8dbE2Xz3-8qLrAuK:breruks) ([raw file](https://github.com/harness/harness-core/blob/7cdd0223cd40d8cce8cccf24fcb272bef691ad45/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecord.java#L119)):*
> ```Java
>           throw new IllegalStateException("Unhanded SLI State " + this);
>       }
>     }
> ```

This is already in the SLIMissingDataType, why is this copied here as well? And If needed here as well, then move this out in a separate class and remove from the enums



_Code quote:_
```Java
    public SLIValue calculateSLIValue(long goodCount, long badCount, long totalMinutes) {
      return calculateSLIValue(goodCount, badCount, totalMinutes, 0L);
    }

    public SLIValue calculateSLIValue(long goodCount, long badCount, long totalMinutes, long disabledMinutes) {
      Preconditions.checkState(totalMinutes != 0);
      long missingDataCount = totalMinutes - (goodCount + badCount) - disabledMinutes;
      switch (this) {
        case GOOD:
          return SLIValue.builder()
              .goodCount((int) (goodCount + missingDataCount))
              .badCount((int) badCount)
              .total((int) (totalMinutes - disabledMinutes))
              .build();
        case BAD:
          return SLIValue.builder()
              .goodCount((int) goodCount)
              .badCount((int) (badCount + missingDataCount))
              .total((int) (totalMinutes - disabledMinutes))
              .build();
        case NO_DATA:
          return SLIValue.builder()
              .goodCount((int) goodCount)
              .badCount((int) badCount)
              .total((int) (goodCount + badCount))
              .build();
        default:
          throw new IllegalStateException("Unhanded SLI State " + this);
      }
    }
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/40473#-NHSt7IdAHBdeKqJxh9N:-NHSt7IdAHBdeKqJxh9O:b-8v3xrq) ([raw file](https://github.com/harness/harness-core/blob/7cdd0223cd40d8cce8cccf24fcb272bef691ad45/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java#L94)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @Path("/onBoarding-graph")
> ```

onboarding*



_Code quote:_
```Java
onBoarding
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 171 at r2](https://reviewable.io/reviews/harness/harness-core/40473#-NHT8TGSCA59A4j25obt:-NHT8TGSCA59A4j25obu:b-wutna2) ([raw file](https://github.com/harness/harness-core/blob/7cdd0223cd40d8cce8cccf24fcb272bef691ad45/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L171)):*
> ```Java
>                            .build())
>                 .collect(Collectors.toList()))
>         .build();
> ```

These are sliRecords, you need to add compute sloRecords first from this.



_Code quote:_
```Java
    sliRecords.sort(Comparator.comparing(SLIRecord::getTimestamp));
    Instant initialSliRecordTimestamp = sliRecords.size() > 0 ? sliRecords.get(0).getTimestamp() : startTime;

    return TimeGraphResponse.builder()
        .startTime(startTime.toEpochMilli())
        .endTime(endTime.toEpochMilli())
        .dataPoints(
            sliRecords.stream()
                .map(sliRecord
                    -> TimeGraphResponse.DataPoints.builder()
                           .timeStamp(sliRecord.getTimestamp().toEpochMilli())
                           .value(
                               sliRecord.getSliState()
                                   .calculateSLIValue(sliRecord.getRunningGoodCount(), sliRecord.getRunningBadCount(),
                                       Duration.between(initialSliRecordTimestamp, sliRecord.getTimestamp()).toMinutes()
                                           + 1)
                                   .sliPercentage())
                           .build())
                .collect(Collectors.toList()))
        .build();
```


<!-- Sent from Reviewable.io -->

2022-11-23 05:00 UTC, deepak-harness commented on 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java
> +  @Operation(operationId = "getOnboardingGraph", summary = "Get onboarding graph for composite slo",
lets remove this. this will add the API to swagger 3 and API doc. Can't add it until the API is ready

2022-11-23 05:02 UTC, deepak-harness commented on 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveV2Resource.java
> +  @Path("/onboarding-graph")
composite-slo/onboarding-graph

2022-11-23 05:04 UTC, deepak-harness commented on 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java
>        createCompositeSLORecords(serviceLevelObjectivesDetailCompositeSLORecordMap,
create getCompositeSLORecrods which can internally be called createCompositeSLORecrods which also saves the records.

2022-11-23 05:10 UTC, deepak-harness commented on 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
> +  public Pair<Map<ServiceLevelObjectivesDetail, List<SLIRecord>>, Map<ServiceLevelObjectivesDetail, SLIMissingDataType>>
ideally should move to sloRecordService

2022-11-23 05:15 UTC, deepak-harness commented on 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java
> +  @AllArgsConstructor
Use ServiceLevelObjectiveDetailsTransformer

2022-11-23 08:25 UTC, Varsha-lalwani requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40473)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 158 at r5](https://reviewable.io/reviews/harness/harness-core/40473#-NHYYR469N-GMFfiVV6r:-NHYYR469N-GMFfiVV6s:bttbyj5) ([raw file](https://github.com/harness/harness-core/blob/124146fcfa7ac5215abc42406ec27381b80c92a6/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L158)):*
> ```Java
>                             -> TimeGraphResponse.DataPoints.builder()
>                                    .timeStamp(compositeSLORecord.getTimestamp().toEpochMilli())
>                                    .value(SLIValue.builder()
> ```

use SLOValue class
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java` line 461 at r5](https://reviewable.io/reviews/harness/harness-core/40473#-NHYZQWsCIGdufl_DwEm:-NHYZQWsCIGdufl_DwEn:b4k4u47) ([raw file](https://github.com/harness/harness-core/blob/124146fcfa7ac5215abc42406ec27381b80c92a6/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java#L461)):*
> ```Java
>       List<SLIRecord> sliRecords = getSLIRecordsWithSLIVersion(sliId, startTime, endTime, sliVersion);
>       serviceLevelObjectivesDetailSLIRecordMap.put(objectivesDetail, sliRecords);
>       objectivesDetailSLIMissingDataTypeMap.put(objectivesDetail, serviceLevelIndicator.getSliMissingDataType());
> ```

if sliRecords is empty we shouldn't add it in serviceLevelObjectivesDetailSLIRecordMap, otherwise the size comparsion we are doing is pointless.
I made the same mistake in CompositeSLOMetricAnalysisStateExecutor.



_Code quote:_
```Java
      serviceLevelObjectivesDetailSLIRecordMap.put(objectivesDetail, sliRecords);
      objectivesDetailSLIMissingDataTypeMap.put(objectivesDetail, serviceLevelIndicator.getSliMissingDataType());
```


<!-- Sent from Reviewable.io -->

2022-11-24 04:12 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40473)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 170 at r7](https://reviewable.io/reviews/harness/harness-core/40473#-NHbpDWUD5Yn5tmLCzJi:-NHbpDWUD5Yn5tmLCzJj:b3ho78l) ([raw file](https://github.com/harness/harness-core/blob/0c5da6af4e82f389e0635f1d6e8b8fa4ce81e75e/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L170)):*
> ```Java
>   }
> 
>   public List<CompositeSLORecord> getCompositeSLORecordsFromSLIsDetails(
> ```

We should add the method to the interface as well. It is publically accessible method should be accessed via interface.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 128 at r7](https://reviewable.io/reviews/harness/harness-core/40473#-NHbpbOY0AtOfQXANkVi:-NHbpbOY0AtOfQXANkVj:bxn0a69) ([raw file](https://github.com/harness/harness-core/blob/0c5da6af4e82f389e0635f1d6e8b8fa4ce81e75e/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L128)):*
> ```Java
>   @Inject private ServiceLevelObjectiveDetailsTransformer serviceLevelObjectiveDetailsTransformer;
>   @Inject private SLIRecordServiceImpl sliRecordService;
>   @Inject private CompositeSLORecordServiceImpl compositeSLORecordService;
> ```

use compositeSLORecordService not compositeSLORecordServiceImpl 


<!-- Sent from Reviewable.io -->

2022-11-24 04:50 UTC, merged