fix: [CDS-45115]: Nexus logs fix
harness/harness-core pull request #40690
Opened 2022-11-27 11:39 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-01 02:14 UTC, shivamnegi94 commented
trigger ti1, ti2, ti4, ft1, ft2, smartchecks

2022-12-01 03:24 UTC, shivamnegi94 commented
trigger checkstylecodeformat

2022-12-01 04:05 UTC, shivamnegi94 commented
trigger messagecheck

2022-12-01 04:05 UTC, shivamnegi94 commented
trigger codeformat

2022-12-02 03:23 UTC, vivekkarnatiharness submitted a review, later dismissed
> Reviewed 3 of 13 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: 13 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-02 05:07 UTC, puthrayaharness requested changes

2022-12-02 05:07 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/NexusArtifactOutcome.java
> +  String revision;
Why are we adding this?

2022-12-02 05:26 UTC, shivamnegi94 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/NexusArtifactOutcome.java
> +  String revision;
we have revision in CG

2022-12-02 05:26 UTC, shivamnegi94 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/NexusArtifactOutcome.java
> +  String revision;
To support all expression so added the revision as well

2022-12-02 10:35 UTC, puthrayaharness approved these changes

2022-12-02 10:36 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 1 of 13 files at r1, 7 of 10 files at r2, 4 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-02 10:48 UTC, vivekkarnatiharness submitted a review, later dismissed
> Reviewed 3 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-12-02 10:55 UTC, shivamnegi94 reviewed
> Reviewed 1 of 13 files at r1, 7 of 10 files at r2, 3 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-12-05 16:12 UTC, vivekkarnatiharness submitted a review, later dismissed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-05 17:29 UTC, puthrayaharness approved these changes

2022-12-05 17:30 UTC, puthrayaharness approved these changes
> Reviewed 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-05 19:15 UTC, vtxorxwitty approved these changes
> Reviewed 1 of 13 files at r1, 6 of 10 files at r2, 3 of 5 files at r3, 3 of 4 files at r4, 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-05 22:29 UTC, sribalij approved these changes
> Reviewed 1 of 13 files at r1, 6 of 10 files at r2, 2 of 5 files at r3, 3 of 4 files at r4, 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40690)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-06 00:07 UTC, merged