[PL-29671]: Remove locking from health threads
harness/harness-core pull request #40739
Opened 2022-11-28 11:17 UTC by bhavya181

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-28 12:00 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40739)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/health/HealthService.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/40739#-NHy4TGN3Txf6nSlshdq:-NHy4TGN3Txf6nSlshdr:b-ok5vz3) ([raw file](https://github.com/harness/harness-core/blob/dc56b4cda3561473e187026e9e73ac258ce92dfe/980-commons/src/main/java/io/harness/health/HealthService.java#L99)):*
> ```Java
>   private void startCheck(HealthMonitor monitor) {
>     final Future<Throwable> future = executorService.submit(() -> checkMonitor(monitor));
>     monitors.replace(monitor,
> ```

why use replace?


<!-- Sent from Reviewable.io -->

2022-11-28 12:46 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40739)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/health/HealthService.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/40739#-NHy4TGN3Txf6nSlshdq:-NHyGPXJ0h6BbYcLWaMk:b-jcnn1h) ([raw file](https://github.com/harness/harness-core/blob/dc56b4cda3561473e187026e9e73ac258ce92dfe/980-commons/src/main/java/io/harness/health/HealthService.java#L99)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

why use replace?
</blockquote></details>

replace will prevent from adding unwanted key to map, but as keys will always come from map we are iterating, we can use put,
I have changed it 


<!-- Sent from Reviewable.io -->

2022-11-28 13:18 UTC, kshitij-harness commented on 980-commons/src/main/java/io/harness/health/HealthService.java
> +  private Map<HealthMonitor, Response> monitors = new ConcurrentHashMap<>();
It's cleaner to use private ConcurrentMap<HealthMonitor, Response> monitors = new ConcurrentHashMap<>();

2022-11-28 13:38 UTC, ankit-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40739#-:-NHySYWbE2xK2G-Aa92K:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-29 08:40 UTC, bhavya181 commented
trigger feature-build

2022-11-29 09:45 UTC, kshitij-harness reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40739)* status: 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-29 09:47 UTC, kshitij-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40739)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-29 12:13 UTC, kshitij-harness approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40739)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-11-30 08:30 UTC, rijajoo approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40739)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-30 08:35 UTC, merged