[feat]: [PL-28387]: In AccessControlClient, added new overload method for performing RBAC check.
harness/harness-core pull request #40771
Opened 2022-11-28 18:37 UTC by Jimit09Gandhi

## Describe your changes
In AccessControlClient, added new overload method for performing RBAC check.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-29 06:29 UTC, meenakshi-harness requested changes

2022-11-29 06:29 UTC, meenakshi-harness commented on clients/access-control/sdk/src/main/java/io/harness/accesscontrol/clients/AbstractAccessControlClient.java
> +  public AccessCheckResponseDTO checkForAccessOrThrow(List<PermissionCheckDTO> permissionCheckDTOList) {
UTs for this?

2022-11-29 06:29 UTC, meenakshi-harness commented on clients/access-control/sdk/src/main/java/io/harness/accesscontrol/clients/AbstractAccessControlClient.java
> +        .principal(accessCheckResponseDTOs.get(0).getPrincipal())
Should we check accessCheckResponseDTOs is not empty?

2022-12-01 18:00 UTC, Jimit09Gandhi reviewed
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40771)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/access-control/sdk/src/main/java/io/harness/accesscontrol/clients/AbstractAccessControlClient.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/40771#-NHzX-JbJqHd_d6Zgmw_-r1-119:-NIDprRH-ShM7PWQSze8:bqvw7wv) ([raw file](https://github.com/harness/harness-core/blob/f9b9fe62e428ba6be986a26fb2e9c7ed5f509ec5/clients/access-control/sdk/src/main/java/io/harness/accesscontrol/clients/AbstractAccessControlClient.java#L119)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

UTs for this?
</blockquote></details>

Added UTs
___
*[`clients/access-control/sdk/src/main/java/io/harness/accesscontrol/clients/AbstractAccessControlClient.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/40771#-NHzX-JbJqHd_d6Zgmw_-r1-132:-NIDpubk7dYCHcBFi_r9:b-pre4ts) ([raw file](https://github.com/harness/harness-core/blob/f9b9fe62e428ba6be986a26fb2e9c7ed5f509ec5/clients/access-control/sdk/src/main/java/io/harness/accesscontrol/clients/AbstractAccessControlClient.java#L132)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Should we check accessCheckResponseDTOs is not empty?
</blockquote></details>

Added check on isEmpty check on permissionCheckDTOList. It is expected that accessCheckResponseDTOs will no of entities corresponding to permissionCheckDTOList.


<!-- Sent from Reviewable.io -->

2022-12-01 18:18 UTC, reetika04 commented on clients/access-control/sdk/BUILD.bazel
> +        "//clients/access-control/sdk:module",
Isn’t this already "//clients/access-control/sdk:module"?

2022-12-01 18:19 UTC, reetika04 reviewed
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40771)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-07 11:37 UTC, Jimit09Gandhi commented
trigger checkstyle

2022-12-08 12:04 UTC, meenakshi-harness approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40771)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-12-08 12:38 UTC, meenakshi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40771)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2022-12-08 14:12 UTC, reetika04 reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40771)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-09 13:38 UTC, reetika04 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40771)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-12 05:58 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40771#-:-NJ3uWRp994XytzJZYdo:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-12-13 06:04 UTC, closed without merging