Sumologic as a health source.
harness/harness-core pull request #40782
Opened 2022-11-29 03:22 UTC by n00bitax

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-05 08:23 UTC, n00bitax commented
trigger messagecheck

2022-12-05 17:05 UTC, dhruv-harness reviewed
Lets make sure we do not introduce any code smells.

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782#-:-NIYEq295Xc4XPrangPJ:byf29tg)* status: 0 of 1 approvals obtained. 

___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicLogDataCollectionInfo.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIY9IH0ET3YupQcy9to:-NIY9IH0ET3YupQcy9tp:b-m21mlh) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicLogDataCollectionInfo.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

Copyright year
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYAgwxE8wC9LjC4qVZ:-NIYAgwxE8wC9LjC4qV_:bb77u1u) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

Year
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYAl7o9Xp0x_JMCwp3:-NIYAl7o9Xp0x_JMCwp4:b-hlgav4) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L25)):*
> ```Java
> import lombok.experimental.FieldDefaults;
> 
> @Data
> ```

Can we standardise whether to use Data vs Value annotation?
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYAy_IBOGO4RimrH2X:-NIYAy_IBOGO4RimrH2Y:b-96oj6b) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L28)):*
> ```Java
> @Builder
> public class SumologicMetricDataCollectionInfo extends TimeSeriesDataCollectionInfo<SumoLogicConnectorDTO> {
>   static final String GROUPING_CLAUSE = "avg by ";
> ```

Access modifier ?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYD4dc8tYLtG809BaW:-NIYD4dc8tYLtG809BaX:b-p6xbmc) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java#L17)):*
> ```Java
> import lombok.experimental.SuperBuilder;
> 
> //@Value
> ```

Why are we adding this comment?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsResponse.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYCxHc9pzTPhJeRJhg:-NIYCxHc9pzTPhJeRJhh:b-p6xbmc) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsResponse.java#L22)):*
> ```Java
> public class HealthSourceRecordsResponse {
>   Status status;
>   // enum provider type
> ```

Why are we adding this comment?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYDDGQ9I4mpxxEiqe5:-NIYDDGQ9I4mpxxEiqe6:bf10oc) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java#L13)):*
> ```Java
> import lombok.Data;
> 
> @Data
> ```

Same as above, Data vs Value
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryJSONPath.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYDM7XAgv1CdH7kDOw:-NIYDM7XAgv1CdH7kDOx:btczy63) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryJSONPath.java#L15)):*
> ```Java
> @Value
> @Builder
> public class QueryJSONPath {
> ```

Should we have 4 consecutive uppercase letters in the name?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYDzNT24_J_XZ71gg8:-NIYDzNT24_J_XZ71gg9:b-wwvr6y) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java#L43)):*
> ```Java
> 
>   @POST
>   @Path("healthSourceRecords")
> ```

missing / before path
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYEOGQ03QSd7edejrA:-NIYEOGQ03QSd7edejrB:b-o0fkw0) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java#L51)):*
> ```Java
>   public RestResponse<HealthSourceRecordsResponse>
>   getSampleRawRecord(@PathParam(CVNextGenConstants.ACCOUNT_IDENTIFIER_KEY) @NonNull String accountIdentifier,
>       @PathParam(CVNextGenConstants.ORG_IDENTIFIER_KEY) @NonNull String orgIdentifier,
> ```

Why not use something like ProjectParams?
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYEfjwB1E5JTlOc6JS:-NIYEfjwB1E5JTlOc6JT:b749lwn) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java#L66)):*
> ```Java
>         SumoLogicConnectorDTO.builder()
>             .url("https://api.in.sumologic.com/")
>             .accessIdRef(SecretRefData.builder().decryptedValue("Harness@123".toCharArray()).build())
> ```

We should not commit secrets


<!-- Sent from Reviewable.io -->

2022-12-06 12:16 UTC, n00bitax reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782)* status: 25 file(s) to review. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicLogDataCollectionInfo.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIY9IH0ET3YupQcy9to:-NIbIbqN1Pr-SAY3ot7J:b-4626di) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicLogDataCollectionInfo.java#L2)):*
> fixed for all newly added classes.
`
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYAgwxE8wC9LjC4qVZ:-NIbIXbV8dGP-mXvR8gP:b-siw3vd) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L2)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Year
</blockquote></details>

fixed for all newly added classe
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYAy_IBOGO4RimrH2X:-NIbM8fS583m7mk9ZxrH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L28)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Access modifier ?
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYD4dc8tYLtG809BaW:-NIbMAn92obuEPZxquzn:bss4a2b) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java#L17)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Why are we adding this comment?
</blockquote></details>

Removed.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsResponse.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYCxHc9pzTPhJeRJhg:-NIbMDa52sVxnicpykqH:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsResponse.java#L22)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Why are we adding this comment?
</blockquote></details>

removed
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYDzNT24_J_XZ71gg8:-NIbMGHa0R7XoGYQwF7R:bq33ygo) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java#L43)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

missing / before path
</blockquote></details>

added slash
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYEfjwB1E5JTlOc6JS:-NIbMLSHAT_buVtjy4OT:bqingvm) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java#L66)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We should not commit secrets
</blockquote></details>

it was a dummy, made it more obvious.


<!-- Sent from Reviewable.io -->

2022-12-06 14:05 UTC, dhruv-harness reviewed
> Reviewed 17 of 22 files at r2, 6 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbjbyZEy5UWv9CvaFm:-NIbjbyZEy5UWv9CvaFn:b4d1v8q) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java#L36)):*
> ```Java
> 
> @Api("health-source-records")
> @Path(CVNextGenConstants.PROJECT_PATH)
> ```

Doesnt the path need / as prefix?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java` line 16 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbjlzQEqT7_rdpGAt1:-NIbjlzQEqT7_rdpGAt2:b-3g6e57) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java#L16)):*
> ```Java
> import io.harness.cvng.core.beans.healthsource.QueryRecordsRequest;
> /**
>  * The HealthSourceRawRecordService fetches metric data and log records from different health sources using delegates.
> ```

We should avoid comments. The code should be self-explanatory.
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicLogDataCollectionDSLTest.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbk2K-9WQZX1iZyoU-:-NIbk2K-9WQZX1iZyoU0:bvc67xy) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicLogDataCollectionDSLTest.java#L37)):*
> ```Java
> 
> public class SumologicLogDataCollectionDSLTest extends HoverflyTestBase {
>   public static final String SECRET_REF_DATA = "Dummy_Secret_Ref";
> ```

Any reason we are declaring them as public here?
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbkC1h1uc1m2SNvcjV:-NIbkC1h1uc1m2SNvcjW:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java#L40)):*
> ```Java
> 
> public class SumologicMetricDataCollectionDSLTest extends HoverflyCVNextGenTestBase {
>   public static final int THREADS = 10;
> ```

Same as above


<!-- Sent from Reviewable.io -->

2022-12-06 16:49 UTC, AbhijithHarness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYAl7o9Xp0x_JMCwp3:-NIbpsY6-7RKi1whzBEi:bmv3zha) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L25)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Can we standardise whether to use Data vs Value annotation?
</blockquote></details>

We should use @Value where ever possible, unless the setters are getting used in existing code. If so we can keep it getters.
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbqXlU5EtE57r58lP3:-NIbqXlVEkSra8L9wzBC:b-grst2q) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L33)):*
> ```Java
>   public List<MetricCollectionInfo> getMetricDefinitions() {
>     if (metricDefinitions == null) {
>       return new ArrayList<>();
> ```

We could have generalised this class too right? So that in future, we might be able to go away with InfoMapper completely. And Info class, will just have different implementations of abstractFunctions.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIcJ1HA98QXcNJoM3-k:-NIcJ1HA98QXcNJoM3-l:b-sz2cym) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java#L26)):*
> ```Java
>   @NotNull Long endTime;
>   @NotNull DataSourceType providerType;
>   ProviderParams providerParams;
> ```

we decided on queryParams and healthSourceParams right? instead of providerParams?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/LogRecordsResponse.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbwtlh1KehqHNWrxaW:-NIbwtlh1KehqHNWrxaX:bonkgcx) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/LogRecordsResponse.java#L20)):*
> ```Java
> @Builder
> public class LogRecordsResponse {
>   Status status;
> ```

If Status is required in all the response classes, we should move it to parent class.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbsICT-jYc5OXOICIT:-NIbsICT-jYc5OXOICIU:bsnzjl0) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java#L15)):*
> ```Java
> @Data
> @Builder
> public class ProviderParams {
> ```

naming HealthSourceQueryParams
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java` line 39 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbwPGf7sR3Eh0PpClG:-NIbwPGf7sR3Eh0PpClH:b6hj8bb) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceRawRecordResource.java#L39)):*
> ```Java
> @Produces(MediaType.APPLICATION_JSON)
> @NextGenManagerAuth
> public class HealthSourceRawRecordResource {
> ```

Same. naming needs to change
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java` line 16 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbjlzQEqT7_rdpGAt1:-NIbuoSv3XNjAeNqkU72:bjxikm5) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java#L16)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We should avoid comments. The code should be self-explanatory.
</blockquote></details>

I am of the opinion that comments are good... but in harness we have been following a no comments approach. Which we can debate within the team and change. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbw0Zq1uelc9qWV_U0:-NIbw0Zq1uelc9qWV_U1:b-7zs94x) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java#L18)):*
> ```Java
>  * The HealthSourceRawRecordService fetches metric data and log records from different health sources using delegates.
>  */
> public interface HealthSourceRawRecordService {
> ```

Why HealthSourceRawRecordService? It should be HealthSourceOnboardingService or similar



_Code quote:_
```Java
HealthSourceRawRecordService
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbvEGM-CIPFczoZnU6:-NIbvEGM-CIPFczoZnU7:bz6zt1p) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/HealthSourceRawRecordService.java#L27)):*
> ```Java
>    * @return raw healthSource records
>    */
>   HealthSourceRecordsResponse fetchSampleRawRecordsForHealthSource(
> ```

Use ProjectParams.


<!-- Sent from Reviewable.io -->

2022-12-07 04:48 UTC, n00bitax reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782)* status: 18 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYAl7o9Xp0x_JMCwp3:-NIelK3n22vN58cSeh6j:b-7n86lg) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L25)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We should use @Value where ever possible, unless the setters are getting used in existing code. If so we can keep it getters.
</blockquote></details>

changed to value wherever possible.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIcJ1HA98QXcNJoM3-k:-NIeuKAE9-tu57Oun1Um:b-6g0vo5) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java#L26)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

we decided on queryParams and healthSourceParams right? instead of providerParams?
</blockquote></details>

do we have 2 sections for these api too ?
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicLogDataCollectionDSLTest.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbk2K-9WQZX1iZyoU-:-NIeUu-71cRpHYDhmN9Z:bjaypah) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicLogDataCollectionDSLTest.java#L37)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Any reason we are declaring them as public here?
</blockquote></details>

made them private.
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbkC1h1uc1m2SNvcjV:-NIeUw_M-5YmLCsm5abT:b-8oeqsv) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/dsl/SumologicMetricDataCollectionDSLTest.java#L40)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

made private.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbsICT-jYc5OXOICIT:-NIeuITXEdGiNpSJdapW:b-b5c35t) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java#L15)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

naming HealthSourceQueryParams
</blockquote></details>

changed.


<!-- Sent from Reviewable.io -->

2022-12-07 05:09 UTC, n00bitax reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782)* status: 20 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbqXlU5EtE57r58lP3:-NIez1zZ0JOEiHHuEGq3:bqn9zri) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L33)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We could have generalised this class too right? So that in future, we might be able to go away with InfoMapper completely. And Info class, will just have different implementations of abstractFunctions.
</blockquote></details>

which class to generalize datacollectioninfo or metriccollectioninfo
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/LogRecordsResponse.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIbwtlh1KehqHNWrxaW:-NIeywCb8qsPXntGJ6Ym:bynbj3l) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/LogRecordsResponse.java#L20)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

If Status is required in all the response classes, we should move it to parent class.
</blockquote></details>

removed it, I guess we can figure out simple generic class later.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryJSONPath.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYDM7XAgv1CdH7kDOw:-NIexJhj5eVt3SJXtOJS:bewvpqm) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryJSONPath.java#L15)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Should we have 4 consecutive uppercase letters in the name?
</blockquote></details>

changed it to JsonPath
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/40782#-NIYDDGQ9I4mpxxEiqe5:-NIexfRV5aedCE1aPqYG:buhp7f) ([raw file](https://github.com/harness/harness-core/blob/e139eca903feb075273f94a33775cc2dac0d4f24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/ProviderParams.java#L13)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Same as above, Data vs Value
</blockquote></details>

changed in all places other than the request DTO


<!-- Sent from Reviewable.io -->

2022-12-07 08:46 UTC, dhruv-harness approved these changes
> Reviewed 3 of 6 files at r5, 4 of 14 files at r6, 9 of 9 files at r7, 1 of 5 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782)* status: 1 change requests. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-07 08:53 UTC, n00bitax reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40782)* status: 1 change requests. 7. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/40782#-NIcJ1HA98QXcNJoM3-k:-NIfmbMg-kmApveLEIX8:b-m766b8) ([raw file](https://github.com/harness/harness-core/blob/67e7e33d9243a14b04f58deddbfe10bf765c4627/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceRecordsRequest.java#L26)):*
<details><summary><i>Previously, n00bitax (Ansuman Satapathy) wrote…</i></summary><blockquote>

do we have 2 sections for these api too ?
</blockquote></details>

kept same in all APIs now


<!-- Sent from Reviewable.io -->

2022-12-07 12:17 UTC, merged