feat: [CDS-46590]: run step pt2
harness/harness-core pull request #40798
Opened 2022-11-29 09:49 UTC by abhinav-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-29 09:58 UTC, abhinav-harness commented
trigger ti1, ti2, ti3, ti4, ti5, ti0

2022-11-29 10:08 UTC, abhinav-harness commented
trigger ti0

2022-11-29 10:08 UTC, abhinav-harness commented
trigger ti1

2022-11-29 10:08 UTC, abhinav-harness commented
trigger ti2

2022-11-29 10:08 UTC, abhinav-harness commented
trigger ti3

2022-11-29 10:08 UTC, abhinav-harness commented
trigger ti4

2022-12-02 04:13 UTC, abhinav-harness commented
trigger pocmessagecheck

2022-12-02 04:13 UTC, abhinav-harness commented
trigger poc ti1

2022-12-02 04:13 UTC, abhinav-harness commented
trigger pocrecencycheck

2022-12-02 04:14 UTC, abhinav-harness commented
trigger pocti1

2022-12-02 10:00 UTC, hextechpal requested changes
> Reviewed 45 of 95 files at r1, 43 of 51 files at r2, 9 of 10 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40798)* status: 103 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`835-pipeline-ci-commons/BUILD.bazel` line 1 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHCQzf1mibH0u8YZwI:-NIHCQzf1mibH0u8YZwJ:b8mmynz) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/835-pipeline-ci-commons/BUILD.bazel#L1)):*
> ```Starlark
> load("@rules_java//java:defs.bzl", "java_binary")
> ```

Move this according to the new folder structure
___
*[`835-pipeline-ci-commons/src/main/java/io/harness/execution/ExecutionServiceConfig.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHCmyt21FO71M_VM9Z:-NIHCmyt21FO71M_VM9_:b-3uub4v) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/835-pipeline-ci-commons/src/main/java/io/harness/execution/ExecutionServiceConfig.java#L23)):*
> ```Java
> @AllArgsConstructor
> public class ExecutionServiceConfig {
>   String addonImageTag; // Deprecated
> ```

What does deprecated mean here, if really deprecated use annotation
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/ContainerStepPassThroughData.java` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHDgqJ-jq-CcnSswsV:-NIHDgqJ-jq-CcnSswsW:b-58so6z) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/ContainerStepPassThroughData.java#L18)):*
> ```Java
> @RecasterAlias("io.harness.steps.plugin.ContainerStepPassThroughData")
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class ContainerStepPassThroughData implements PassThroughData {}
> ```

needed?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHEtovBdZsiaEQj_zQ:-NIHEtovBdZsiaEQj_zR:bdrcq8q) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L60)):*
> ```Java
>     long timeout = Timeout.fromString((String) stepNode.getTimeout().fetchFinalValue()).getTimeoutInMillis();
>     SerializationFormat serializationFormat = SerializationFormat.KRYO;
>     String taskType = TaskType.INITIALIZATION_PHASE.getDisplayName();
> ```

Create a new task type and TaskParams (wrapping old) for but this will be a proxy CD task to CI so that atleast we have capabilities to evolve independently if needed



_Code quote:_
```Java
INITIALIZATION_PHASE
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerStepResolverUtils.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHGF-P4PHck3LG3uJs:-NIHGF-P4PHck3LG3uJt:b-z54vmi) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerStepResolverUtils.java#L21)):*
> ```Java
> @UtilityClass
> @Slf4j
> public class ContainerStepResolverUtils {
> ```

move to common module
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/K8sPodInitUtils.java` line 118 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHGIzm8iCk78ZPqZwi:-NIHGIzm8iCk78ZPqZwj:b-z54vmi) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/K8sPodInitUtils.java#L118)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PIPELINE)
> public class K8sPodInitUtils {
> ```

move to common module
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PipelineHelper.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHFvlF1MiGqN6DH7nU:-NIHFvlG4AoMypG0Id5n:b46a642) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PipelineHelper.java#L20)):*
> ```Java
>         executionSweepingOutputService.resolveOptional(ambiance, RefObjectUtils.getSweepingOutputRefObject(key));
>     if (!optionalSweepingOutput.isFound()) {
>       executionSweepingOutputResolver.consume(ambiance, key, value, StepOutcomeGroup.STAGE.name());
> ```

@archit-harness can we expose an API called consumeOptional for the same behaviour
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/SecretUtils.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHG5vD5cn7T4MmOazB:-NIHG5vD5cn7T4MmOazC:b-z54vmi) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/SecretUtils.java#L44)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PIPELINE)
> public class SecretUtils {
> ```

move to common module
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 781 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHGc7c5LmByXdQGlLB:-NIHGc7c5LmByXdQGlLC:b-q40y8c) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L781)):*
> ```Java
>   @Singleton
>   public ContainerExecutionConfig getContainerStepExecutionConfig() {
>     return configuration.getContainerExecutionConfig();
> ```

Move this to orchestration steps config and provide from that module not pipeline service


<!-- Sent from Reviewable.io -->

2022-12-02 10:24 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40798)* status: 103 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PipelineHelper.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHFvlF1MiGqN6DH7nU:-NIHMB2oCdSQ6WYI3-6f:b-wwfbyx) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PipelineHelper.java#L20)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

@archit-harness can we expose an API called consumeOptional for the same behaviour
</blockquote></details>

Sure i can expose in my next pr


<!-- Sent from Reviewable.io -->

2022-12-02 20:05 UTC, abhinav-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40798)* status: 103 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`835-pipeline-ci-commons/BUILD.bazel` line 1 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHCQzf1mibH0u8YZwI:-NIJQzMT6g7cwvngnt5W:b-ey816q) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/835-pipeline-ci-commons/BUILD.bazel#L1)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Move this according to the new folder structure
</blockquote></details>

didnt get, you want me to move this to non numbered module?
___
*[`835-pipeline-ci-commons/src/main/java/io/harness/execution/ExecutionServiceConfig.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHCmyt21FO71M_VM9Z:-NIJR3eQCcNUREGSVeuF:b9yzg3o) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/835-pipeline-ci-commons/src/main/java/io/harness/execution/ExecutionServiceConfig.java#L23)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

What does deprecated mean here, if really deprecated use annotation
</blockquote></details>

its CI construct - just abstracted out for our use case.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/ContainerStepPassThroughData.java` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHDgqJ-jq-CcnSswsV:-NIJR7kWDd3HoZmxpKyn:bgxz3b2) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/ContainerStepPassThroughData.java#L18)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

just creating for now can remove later if not needed
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHEtovBdZsiaEQj_zQ:-NIJRAqw4WDN_-u-a8sR:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L60)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Create a new task type and TaskParams (wrapping old) for but this will be a proxy CD task to CI so that atleast we have capabilities to evolve independently if needed
</blockquote></details>

ok
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerStepResolverUtils.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHGF-P4PHck3LG3uJs:-NIJRCaR6RrrGCVsY-L2:b374v5g) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerStepResolverUtils.java#L21)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

move to common module
</blockquote></details>

980 or pipeline?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/K8sPodInitUtils.java` line 118 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHGIzm8iCk78ZPqZwi:-NIJRI4oALRXHNSZXN4P:bu5idrv) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/K8sPodInitUtils.java#L118)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

move to common module
</blockquote></details>

will need to move a lot of things here
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/SecretUtils.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHG5vD5cn7T4MmOazB:-NIJRL4i2T1Ri1RXcbF7:bftam3c) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/SecretUtils.java#L44)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

move to common module
</blockquote></details>

will need to move multiple things here. 
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 781 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHGc7c5LmByXdQGlLB:-NIJRPtbCzuWfqYs8YDx:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L781)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Move this to orchestration steps config and provide from that module not pipeline service
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-12-02 20:22 UTC, abhinav-harness commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerStepResolverUtils.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHGF-P4PHck3LG3uJs:-NIJVCNBDQSBy1r_G094:b-nayucw) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerStepResolverUtils.java#L21)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

980 or pipeline?
</blockquote></details>

probably pms - checking feasibility


<!-- Sent from Reviewable.io -->

2022-12-06 00:26 UTC, abhinav-harness commented
trigger feature-build

2022-12-06 06:52 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40798)* status: 122 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PipelineHelper.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/40798#-NIHFvlF1MiGqN6DH7nU:-NIaC719BmeqlpL5kTRk:b-ft3rp7) ([raw file](https://github.com/harness/harness-core/blob/4f5c2f7ac04cc0d3c986371af69071b7662c55d9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/PipelineHelper.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Sure i can expose in my next pr
</blockquote></details>

@abhinav-harness expoed this in my new pr, move this in later pr


<!-- Sent from Reviewable.io -->

2022-12-06 09:50 UTC, merged