fix: [DEL-5460]: Add included kubectl for immutable-delegate to system $PATH variable
harness/harness-core pull request #40826
Opened 2022-11-29 20:34 UTC by raghuAtWings

## Describe your changes
1. change the base image of immutable delegate to redhat/ubi8-minimal:8.7
2. set the PATH to include v1.19.2 kubectl baked in the image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-11-29 20:44 UTC, xingchi-jin approved these changes
LG for this particular issue.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40826#-:-NI47ZfH-3gEG0oMWFcU:bwyyzcl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-11-29 20:55 UTC, mdmilic requested changes

2022-11-29 20:55 UTC, mdmilic commented on dockerization/delegate/Dockerfile-immutable
> +ENV PATH="$JAVA_HOME/bin:/opt/harness-delegate/client-tools/kubectl/v1.19.2/:${PATH}"
I think this is a very bad idea. I understand some customers requested it but we have a very simple one liner (in init script) which they can do in their environment to get it. 
It was a mistake to put this in legacy delegates as well and we can't get rid of it now, so would be great we avoid the same mistake. Reasons why it's bad:
* You are tied to a version. You can't change this. If you change version you can will break customers (IIRC something like this happened with legacy when we tried to remove this)
* It will affect existing customers with and without custom image. This will now behave as if they've put custom kubectl binary (and will now never use other version even if tasks request it), and for custom images it could even override their custom binary, depending on how they've configured it (e.g. if they've did $PATH:/my/path )
* Still not same as legacy - there it's latest kubectl
* Applies to minimal image as well which doesn't have the tool. I think it will not break it right now though, but not future proof.

2022-11-30 01:07 UTC, raghuAtWings commented
*[`dockerization/delegate/Dockerfile-immutable` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/40826#-NI45DLWYDEC6qJzvOuW-r1-39:-NI53Ns1A957Nu3EX_3u:b-6ujbh9) ([raw file](https://github.com/harness/harness-core/blob/e35f0213eccc9a75c57c34a724ac4c314aa79b53/dockerization/delegate/Dockerfile-immutable#L39)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think this is a very bad idea. I understand some customers requested it but we have a very simple one liner (in init script) which they can do in their environment to get it. 
It was a mistake to put this in legacy delegates as well and we can't get rid of it now, so would be great we avoid the same mistake. Reasons why it's bad:
* You are tied to a version. You can't change this. If you change version you can will break customers (IIRC something like this happened with legacy when we tried to remove this)
* It will affect existing customers with and without custom image. This will now behave as if they've put custom kubectl binary (and will now never use other version even if tasks request it), and for custom images it could even override their custom binary, depending on how they've configured it (e.g. if they've did $PATH:/my/path )
* Still not same as legacy - there it's latest kubectl
* Applies to minimal image as well which doesn't have the tool. I think it will not break it right now though, but not future proof.

</blockquote></details>

should we put this in our default generated INIT_SCRIPT? 


<!-- Sent from Reviewable.io -->

2022-11-30 01:52 UTC, xingchi-jin commented
*[`dockerization/delegate/Dockerfile-immutable` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/40826#-NI45DLWYDEC6qJzvOuW-r1-39:-NI5CtaN5nNJkxlJ3Hs4:b-wfmexx) ([raw file](https://github.com/harness/harness-core/blob/e35f0213eccc9a75c57c34a724ac4c314aa79b53/dockerization/delegate/Dockerfile-immutable#L39)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

should we put this in our default generated INIT_SCRIPT? 
</blockquote></details>

@mdmilic 's points are inspiring.
I think changing PATH will affect existing customers is the risk here.

Then the question in my mind is why do we provide tools to them?  If customers treat delegate as a blank execution sandbox to run shell commands or scripts, why don't they install kubectl in their script.


<!-- Sent from Reviewable.io -->

2022-11-30 16:47 UTC, mdmilic commented
> should we put this in our default generated INIT_SCRIPT

No, this would have the same effect as putting it in Dockerfile. I don't think we should do this for now. After we cleanup to have one client tool version, might be feasible. 
At that point I think this would be the only impact:
* For custom images it could even override their custom binary, depending on how they've configured it (e.g. if they've did $PATH:/my/path )

2023-02-23 09:33 UTC, closed without merging