[feat]: [PL-29917]: New Delegate task to write into S3 bucket
harness/harness-core pull request #40895
Opened 2022-11-30 22:43 UTC by kapil-harness

## Describe your changes
New Delegate task to write into S3 bucket

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-05 05:23 UTC, piyush-harness requested changes
> Reviewed 2 of 9 files at r1, 1 of 4 files at r2, 5 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: Some of the checks are too old. 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViYWx2gkF2aeNKTwf:-NIViYWx2gkF2aeNKTwg:bko4by6) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L139)):*
> ```Java
>         awsInternalConfig, awsTaskParams.getRegion(), awsTaskParams.getBucketName());
> 
>     return AwsPutObjectToBucketTaskResponse.builder()
> ```

What about failure response?
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIVjAkM7oH5VUMYxaOI:-NIVjAkM7oH5VUMYxaOJ:b55yihx) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L114)):*
> ```Java
> public class AwsApiHelperService {
>   private static final String NG_AUDITS_PATH = "960-api-services/src/test/resources/__files/ng_audits.json";
> ```

What is this hardcoded value?
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 248 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViq1t9s8vAorRFT1x:-NIViq1t9s8vAorRFT1y:b-1zmnxz) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L248)):*
> ```Java
> 
>   private String getKey() {
>     return "audits-key-" + UUID.randomUUID();
> ```

Key should contain timeStamp - From and to of the objects that we are writing


<!-- Sent from Reviewable.io -->

2022-12-05 15:12 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViYWx2gkF2aeNKTwf:-NIXpNDU1Qx09oV46Yhz:b2qjzjm) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L139)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

What about failure response?
</blockquote></details>

done, added failure response
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIVjAkM7oH5VUMYxaOI:-NIXpRztExktFy_ul3gS:b-gyan9w) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L114)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

What is this hardcoded value?
</blockquote></details>

It is the path to NG Audits json which we are reading and writing to S3 bucket.
In real scenario this won't be the case, we will get data to be written into S3 bucket as part of Delegate Task from Audit Streaming service, but since currently we are not sure of the data schema and how to zip it, we are using this mechanism for our POC.
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 248 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViq1t9s8vAorRFT1x:-NIXpQvnAZVug-p5W2mI:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L248)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Key should contain timeStamp - From and to of the objects that we are writing
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-06 07:53 UTC, piyush-harness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViYWx2gkF2aeNKTwf:-NIaQ8P86Zp8Px05py3i:b1mo2v9) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L139)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

done, added failure response
</blockquote></details>

What if there's exception in connecting , there should be try-catch and exception should also be captured in log


<!-- Sent from Reviewable.io -->

2022-12-06 07:54 UTC, piyush-harness commented
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIVjAkM7oH5VUMYxaOI:-NIaQSgR9QH9GNf9Ufk9:b-50ike6) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L114)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

It is the path to NG Audits json which we are reading and writing to S3 bucket.
In real scenario this won't be the case, we will get data to be written into S3 bucket as part of Delegate Task from Audit Streaming service, but since currently we are not sure of the data schema and how to zip it, we are using this mechanism for our POC.
</blockquote></details>

Do not put POC code in real flow, You can use mock data in tests


<!-- Sent from Reviewable.io -->

2022-12-06 07:56 UTC, piyush-harness requested changes
> Reviewed 1 of 9 files at r1, 1 of 1 files at r5, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java` line 615 at r6](https://reviewable.io/reviews/harness/harness-core/40895#-NIaQJMP5RBL2Br-A16z:-NIaQJMP5RBL2Br-A17-:bptnowf) ([raw file](https://github.com/harness/harness-core/blob/ad5cb07c0f2471253f92304c3760bba1e39735fe/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java#L615)):*
> ```Java
>     doReturn(new PutObjectResult())
>         .when(awsApiHelperService)
>         .putObjectToBucket(
> ```

add Failure test case in case of Network Error or anything thrown from AWS client
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 248 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViq1t9s8vAorRFT1x:-NIaQecQ3BjO70bSltms:beatwv5) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L248)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

done
</blockquote></details>

Not this way, You should take the first record and last record in a batch as timestamp and set it as name


<!-- Sent from Reviewable.io -->

2022-12-06 21:54 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 16 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViYWx2gkF2aeNKTwf:-NIdQgZsEiO96LChWXna:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L139)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

What if there's exception in connecting , there should be try-catch and exception should also be captured in log
</blockquote></details>

done
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java` line 615 at r6](https://reviewable.io/reviews/harness/harness-core/40895#-NIaQJMP5RBL2Br-A16z:-NIdQixk4mpI7VZXeiRQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ad5cb07c0f2471253f92304c3760bba1e39735fe/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelperTest.java#L615)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

add Failure test case in case of Network Error or anything thrown from AWS client
</blockquote></details>

done
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIVjAkM7oH5VUMYxaOI:-NIdQkYL5TauDb92VfFR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L114)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Do not put POC code in real flow, You can use mock data in tests
</blockquote></details>

done
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 248 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViq1t9s8vAorRFT1x:-NIdQm1LDVFjS516FKx6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L248)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Not this way, You should take the first record and last record in a batch as timestamp and set it as name
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-07 05:46 UTC, piyush-harness commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java` line 12 at r8](https://reviewable.io/reviews/harness/harness-core/40895#-NIf6NOd-HpxdCJXAaZJ:-NIf6NOd-HpxdCJXAaZK:b-l4t2p2) ([raw file](https://github.com/harness/harness-core/blob/9c1007bd4272f6512f6b784e2e861393e0652217/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java#L12)):*
> ```Java
> import io.harness.annotations.dev.HarnessTeam;
> import io.harness.annotations.dev.OwnedBy;
> import io.harness.aws.audits.AuditBatch;
> ```

This package name does not look correct , You should have a AuditBatchDTO object in platform-service and not under AWS package as the same can be used across destination 


<!-- Sent from Reviewable.io -->

2022-12-07 05:47 UTC, piyush-harness requested changes
> Reviewed 3 of 11 files at r7, 3 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViYWx2gkF2aeNKTwf:-NIf67BV4yKmPn2uPoJv:b-ud5on9) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L139)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

done
</blockquote></details>

Exception message should be propagated through delegate error response.
___
*[`970-api-services-beans/src/main/java/io/harness/aws/audits/AuditBatch.java` line 20 at r8](https://reviewable.io/reviews/harness/harness-core/40895#-NIf6nF6AXKhUoUgrvWC:-NIf6nF6AXKhUoUgrvWD:b-fu8w2z) ([raw file](https://github.com/harness/harness-core/blob/9c1007bd4272f6512f6b784e2e861393e0652217/970-api-services-beans/src/main/java/io/harness/aws/audits/AuditBatch.java#L20)):*
> ```Java
> @SuperBuilder
> @OwnedBy(HarnessTeam.PL)
> public class AuditBatch {
> ```

All of these should be part of platform service DTO


<!-- Sent from Reviewable.io -->

2022-12-07 08:11 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/40895#-NIViYWx2gkF2aeNKTwf:-NIfZrvQ9GyWnq0EhH8_:blrowzf) ([raw file](https://github.com/harness/harness-core/blob/6463b87fba4f82b6d7d52a38c1fac4e4b7628a74/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L139)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Exception message should be propagated through delegate error response.
</blockquote></details>

done, added an error message in the delegate response
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java` line 12 at r8](https://reviewable.io/reviews/harness/harness-core/40895#-NIf6NOd-HpxdCJXAaZJ:-NIfZxK66o0iFSuxRpWO:b-dgeb21) ([raw file](https://github.com/harness/harness-core/blob/9c1007bd4272f6512f6b784e2e861393e0652217/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java#L12)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This package name does not look correct , You should have a AuditBatchDTO object in platform-service and not under AWS package as the same can be used across destination 
</blockquote></details>

We can change the name, however if we put it inside platform-service then how would delegate access it?
On the other hand platform-service can access it as it has a dependency on 970-api-services-beans module
___
*[`970-api-services-beans/src/main/java/io/harness/aws/audits/AuditBatch.java` line 20 at r8](https://reviewable.io/reviews/harness/harness-core/40895#-NIf6nF6AXKhUoUgrvWC:-NIfcIslDZJM7D15dOGe:b-ia41wb) ([raw file](https://github.com/harness/harness-core/blob/9c1007bd4272f6512f6b784e2e861393e0652217/970-api-services-beans/src/main/java/io/harness/aws/audits/AuditBatch.java#L20)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

All of these should be part of platform service DTO
</blockquote></details>

same comment as above


<!-- Sent from Reviewable.io -->

2022-12-07 14:02 UTC, piyush-harness submitted a review, later dismissed
> Reviewed 3 of 11 files at r7, 1 of 6 files at r8, 12 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 16 file(s) to review. 1 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java` line 12 at r8](https://reviewable.io/reviews/harness/harness-core/40895#-NIf6NOd-HpxdCJXAaZJ:-NIfol53-gTC7nbYIF6G:b-4tetud) ([raw file](https://github.com/harness/harness-core/blob/9c1007bd4272f6512f6b784e2e861393e0652217/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java#L12)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

We can change the name, however if we put it inside platform-service then how would delegate access it?
On the other hand platform-service can access it as it has a dependency on 970-api-services-beans module
</blockquote></details>

Got it , Please change the package name to show these classes belong to platform service.


<!-- Sent from Reviewable.io -->

2022-12-07 18:01 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 16 file(s) to review. 1 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java` line 12 at r8](https://reviewable.io/reviews/harness/harness-core/40895#-NIf6NOd-HpxdCJXAaZJ:-NIhjqJDET4Q4BOygDbL:b-2d0wae) ([raw file](https://github.com/harness/harness-core/blob/9c1007bd4272f6512f6b784e2e861393e0652217/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java#L12)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Got it , Please change the package name to show these classes belong to platform service.
</blockquote></details>

done as discussed


<!-- Sent from Reviewable.io -->

2022-12-08 07:25 UTC, nishantsaini20 requested changes
> Reviewed 1 of 9 files at r1, 1 of 4 files at r6, 1 of 11 files at r7, 1 of 6 files at r8, 11 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java` line 114 at r10](https://reviewable.io/reviews/harness/harness-core/40895#-NIkR6gjAConZPRzq69N:-NIkR6gjAConZPRzq69O:b-31d5vi) ([raw file](https://github.com/harness/harness-core/blob/e850081d568af68aff1f0d69096860851dd8d82a/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsDelegateTask.java#L114)):*
> ```Java
>       case LIST_ELASTIC_LOAD_BALANCER_LISTENER_RULE:
>         return awsElasticLoadBalancersDelegateTaskHelper.getElbListenerRulesList(awsTaskParams);
>       case PUT_OBJECT_TO_BUCKET:
> ```

Should be renamed as this is specifically from audit batch
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java` line 134 at r10](https://reviewable.io/reviews/harness/harness-core/40895#-NIkOz0M5IpKEe6jlTXj:-NIkOz0M5IpKEe6jlTXk:bgdfrm3) ([raw file](https://github.com/harness/harness-core/blob/e850081d568af68aff1f0d69096860851dd8d82a/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsS3DelegateTaskHelper.java#L134)):*
> ```Java
>   }
> 
>   public DelegateResponseData putObjectToBucket(AwsPutObjectToBucketTaskParamsRequest awsTaskParams) {
> ```

This is method is expecting Audit batch in task parms. Method name should depict this.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java` line 20 at r10](https://reviewable.io/reviews/harness/harness-core/40895#-NIkMsq-0NntplLDsYDX:-NIkMsq0DE7q_PXRzTNY:b-oaj6c5) ([raw file](https://github.com/harness/harness-core/blob/e850081d568af68aff1f0d69096860851dd8d82a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsPutObjectToBucketTaskParamsRequest.java#L20)):*
> ```Java
> @SuperBuilder
> @OwnedBy(HarnessTeam.PL)
> public class AwsPutObjectToBucketTaskParamsRequest extends AwsTaskParams {
> ```

This class looks to be specific to writing AuditBatch to S3. Rename this to AwsPutAuditBatchToBucketTaskParamsRequest.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java` line 32 at r10](https://reviewable.io/reviews/harness/harness-core/40895#-NIkR4WRAVqkGLj8pcxh:-NIkR4WRAVqkGLj8pcxi:b-31d5vi) ([raw file](https://github.com/harness/harness-core/blob/e850081d568af68aff1f0d69096860851dd8d82a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsTaskType.java#L32)):*
> ```Java
>   LIST_ELASTIC_LOAD_BALANCER_LISTENERS,
>   LIST_ELASTIC_LOAD_BALANCER_LISTENER_RULE,
>   PUT_OBJECT_TO_BUCKET
> ```

Should be renamed as this is specifically from audit batch
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 232 at r10](https://reviewable.io/reviews/harness/harness-core/40895#-NIkPhvtBsTYJey-qAMm:-NIkPhvtBsTYJey-qAMn:b9ecnpk) ([raw file](https://github.com/harness/harness-core/blob/e850081d568af68aff1f0d69096860851dd8d82a/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L232)):*
> ```Java
>   }
> 
>   public PutObjectResultResponse putObjectToBucket(
> ```

This is method is expecting Audit batch in task params. Method name should depict this.
___
*[`960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java` line 256 at r10](https://reviewable.io/reviews/harness/harness-core/40895#-NIkRknl6zKF-qO3ZDFj:-NIkRknl6zKF-qO3ZDFk:b-tbaz60) ([raw file](https://github.com/harness/harness-core/blob/e850081d568af68aff1f0d69096860851dd8d82a/960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java#L256)):*
> ```Java
>       throw new InvalidRequestException(ExceptionUtils.getMessage(sanitizeException), sanitizeException);
>     }
>     return PutObjectResultResponse.builder().build();
> ```

Why is this required? Empty response would be confusing. The method should respond with proper response or throw exception.


<!-- Sent from Reviewable.io -->

2022-12-08 12:26 UTC, piyush-harness approved these changes
> Reviewed 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 12 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-08 13:53 UTC, piyush-harness approved these changes
> Reviewed 12 of 12 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: 14 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-08 13:55 UTC, piyush-harness commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-12-08 14:02 UTC, nishantsaini20 approved these changes
> Reviewed 9 of 11 files at r11, 12 of 12 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40895)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-08 15:00 UTC, merged