feat: [PL-29716]: add yaml support for plan based settings
harness/harness-core pull request #41085
Opened 2022-12-05 07:31 UTC by tiwaritejas

## Describe your changes
Added support for plan based settings in the settings framework. Settings can be available based on the account edition. Also, settings can have different default values based on the account plan. Similarly, settings can be editable/view-only based on the account plan.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-07 12:04 UTC, nishantsaini20 requested changes
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgPaj521gY5QMlb_-A:-NIgPaj521gY5QMlb_-B:bnw3m3x) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L206)):*
> ```Java
>       Scope currentScope, String identifier, SettingConfiguration settingConfiguration) {
>     return getSettingFromParentScope(currentScope, identifier, settingConfiguration,
>         SettingUtils.getDefaultValue(getEditionForAccount(currentScope.getAccountIdentifier()), settingConfiguration));
> ```

Make it more readable. Store method return values in variables and pass them as arguments.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 289 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgQBmZ2tmQ_6PdJu8N:-NIgQBmZ2tmQ_6PdJu8O:b-v32rsa) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L289)):*
> ```Java
>             .is(category)
>             .and(SettingConfigurationKeys.groupIdentifier)
>             .is(groupIdentifier)
> ```

remove this as it is added below if its not empty.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 311 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgRCn0AmZygJVlz7K-:-NIgRCn0AmZygJVlz7K0:b-8ycany) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L311)):*
> ```Java
>     checkIfAccountPlanAllowsSettingEdit(accountIdentifier, settingConfiguration);
> 
>     if (!isSettingEditableForAccountEdition(accountIdentifier, settingConfiguration)) {
> ```

Remove this check from here because checkIfAccountPlanAllowsSettingEdit is taking care of checking and throwing exception
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 320 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgRgkI00EQ3Cj38Vyg:-NIgRgkI00EQ3Cj38Vyh:b-lwzs9e) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L320)):*
> ```Java
>     SettingDTO newSettingDTO;
>     SettingDTO oldSettingDTO;
>     String defaultValue = SettingUtils.getDefaultValue(getEditionForAccount(accountIdentifier), settingConfiguration);
> ```

Call this method once per API call if possible.



_Code quote:_
```Java
getEditionForAccount
```
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgSux15yMY3dB6ETYy:-NIgSux2DAKTJLIuN4Mi:boq35s8) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java#L128)):*
> ```Java
> 
>     if (isNotEmpty(settingConfiguration.getAllowedPlans())
>         && isNotEmpty(planDefaultValue = settingConfiguration.getAllowedPlans().get(edition).getDefaultValue())) {
> ```

Can result in NPE if edition is not present in configuration


<!-- Sent from Reviewable.io -->

2022-12-07 12:04 UTC, nishantsaini20 reviewed
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-14 05:13 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 14 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgPaj521gY5QMlb_-A:-NIkEiwa5tj3-l6l_l6H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L206)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Make it more readable. Store method return values in variables and pass them as arguments.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 289 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgQBmZ2tmQ_6PdJu8N:-NIkF1_527xMrD23V-6Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L289)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

remove this as it is added below if its not empty.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 311 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgRCn0AmZygJVlz7K-:-NIkF75rAUjBdH5EYf9y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L311)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Remove this check from here because checkIfAccountPlanAllowsSettingEdit is taking care of checking and throwing exception
</blockquote></details>

Done.



_Code quote:_
```Java
  if (!isSettingEditableForAccountEdition(accountIdentifier, settingConfiguration)) 
```
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 320 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgRgkI00EQ3Cj38Vyg:-NIkHdi6BD3sUVJsfTDV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L320)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Call this method once per API call if possible.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/41085#-NIgSux15yMY3dB6ETYy:-NIkJziH4wFwDUpG6eJJ:ba3lqj3) ([raw file](https://github.com/harness/harness-core/blob/193669581002102be1498c63b806b5d7b538ab3b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java#L128)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Can result in NPE if edition is not present in configuration
</blockquote></details>

Added null checks.


<!-- Sent from Reviewable.io -->

2022-12-14 09:31 UTC, nishantsaini20 approved these changes
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-14 09:39 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingPlanConfig.java
> +  @JsonProperty("editable") Boolean editable;
Do we need to define JsonProperty here?

2022-12-14 09:42 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java
> +    //        .thenReturn(List.of(settingConfigurations.get(identifier)));
Remove commented code

2022-12-14 09:44 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
> +            && (ScopeLevel.of(accountIdentifier, orgIdentifier, projectIdentifier) == ScopeLevel.ACCOUNT
Move this to a variable `ScopeLevel.of(accountIdentifier, orgIdentifier, projectIdentifier)` Its used twice.

2022-12-14 09:45 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
> +      Setting parentSetting = getSettingFromParentScope(Scope.of(accountIdentifier, orgIdentifier, projectIdentifier),
Move this to variable `Scope.of(accountIdentifier, orgIdentifier, projectIdentifier)`, used multiple times.

2022-12-14 09:47 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
> +  private Boolean isSettingEditableForAccountEdition(Edition edition, SettingConfiguration settingConfiguration) {
should we make return type as boolean and handle null condition inside this method itself?

2022-12-14 09:48 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
> +    if (!isSettingEditableForAccountEdition(edition, settingConfiguration)) {
this can give NPE if this `isSettingEditableForAccountEdition(edition, settingConfiguration)` return null

2022-12-14 09:52 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
> +            && (ScopeLevel.of(accountIdentifier, orgIdentifier, projectIdentifier) == ScopeLevel.ACCOUNT
Any difference between ScopeLevel and Scope?

2022-12-14 10:00 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
> +  private Boolean isSettingEditableForAccountEdition(Edition edition, SettingConfiguration settingConfiguration) {
Add UT for this.

2022-12-14 10:01 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java
> +  public static String getDefaultValue(Edition edition, SettingConfiguration settingConfiguration) {
Add UT for this.

2022-12-15 10:03 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 14 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingPlanConfig.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2R-r3-18:-NJKEBohDvG-VqaU26O8:b-fhdfwf) ([raw file](https://github.com/harness/harness-core/blob/bbae8eb16ccc96f578a3cef8b9c2a70573a3cd99/120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingPlanConfig.java#L18)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Do we need to define JsonProperty here?
</blockquote></details>

I don't think it is needed. Removed it.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2L-r3-97:-NJK-Iqi4_CSV_REZzbR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbae8eb16ccc96f578a3cef8b9c2a70573a3cd99/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L97)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Move this to variable `Scope.of(accountIdentifier, orgIdentifier, projectIdentifier)`, used multiple times.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2L-r3-104:-NJK-Mc-EPFuLtT64nOY:b-ikr06m) ([raw file](https://github.com/harness/harness-core/blob/bbae8eb16ccc96f578a3cef8b9c2a70573a3cd99/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L104)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Any difference between ScopeLevel and Scope?
</blockquote></details>

Scope contains acc, org and project identifiers. ScopeLevel is an enum with values- ACCOUNT, ORGANISATION, PROJECT.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 408 at r3](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2L-r3-408:-NJK-lSG6EuRBwpDI1ku:b7fmxb6) ([raw file](https://github.com/harness/harness-core/blob/bbae8eb16ccc96f578a3cef8b9c2a70573a3cd99/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L408)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Add UT for this.
</blockquote></details>

Added null check and now returning boolean. Added UT.



_Code quote:_
```Java
isSettingEditableForAccountEdition
```
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 417 at r3](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2L-r3-417:-NJK4UjnBRlQAuUi_8BQ:b-5a4dst) ([raw file](https://github.com/harness/harness-core/blob/bbae8eb16ccc96f578a3cef8b9c2a70573a3cd99/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L417)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Add UT for this. 
</blockquote></details>

Made it a boolean. Added UT.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2M-r3-126:-NJK5yxpE2j-sNegikuW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbae8eb16ccc96f578a3cef8b9c2a70573a3cd99/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java#L126)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Add UT for this.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2Q-r3-106:-NJK64S54rVRWn8EZtt0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbae8eb16ccc96f578a3cef8b9c2a70573a3cd99/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/SettingsServiceImplTest.java#L106)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 11:01 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java
> +        Boolean isSettingEditable =
this should be boolean now

2022-12-15 11:21 UTC, meenakshi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 15 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-15 12:53 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 15 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 101 at r4](https://reviewable.io/reviews/harness/harness-core/41085#-NIWBbuZLdlAuKE0XX2L-r4-101:-NJKqDm--UHK6-DNUGcr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d010fd53403c39cfc37bbfe46717df16be228a5/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L101)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

this should be boolean now
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 14:47 UTC, meenakshi-harness approved these changes
> Reviewed 4 of 12 files at r1, 5 of 9 files at r2, 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-16 07:27 UTC, nishantsaini20 approved these changes
> Reviewed 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41085)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-16 07:31 UTC, merged