techDebt: [DEL-5377]: change log level/remove log lines to reduce delegate logging cost
harness/harness-core pull request #41138
Opened 2022-12-05 20:03 UTC by raghuAtWings

## Describe your changes
1. made changes to remove repetitive or easily be inferenced log lines to be not logged by default 
2. added changes to not log for statements which can be inferenced from manager logs

**Testing done** 
end to end k8 deployment

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/41138)

2022-12-05 20:15 UTC, jennyjames21 approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-07 12:08 UTC, mdmilic reviewed
> Reviewed 1 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-07 12:11 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1710 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgSE37CJ1oqKy-iHJG:-NIgSE389aY9wrCG7DJN:b-k5y50n) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1710)):*
> ```Java
>             getDurationString(lastHeartbeatReceivedAt.get(), now),
>             getDurationString(delegateHeartbeatResponse.getResponseSentAt(), now));
>       } else if (log.isDebugEnabled()) {
> ```

this check is not needed, as you logging as debug itself



_Code quote:_
```Java
if (log.isDebugEnabled())
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1912 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgSe_3AFcfG5f5BuV8:-NIgSe_3AFcfG5f5BuV9:b-86fuxy) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1912)):*
> ```Java
> 
>     if (currentlyExecutingFutures.containsKey(delegateTaskEvent.getDelegateTaskId())) {
>       log.info("Task [DelegateTaskEvent: {}] already queued, dropping this request ", delegateTaskEvent);
> ```

We might need this, if it's present in log context then okay to remove. Please verify.



_Code quote:_
```Java
delegateTaskEvent
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1925 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgSrS9EpGE2ZIWaWG4:-NIgSrS9EpGE2ZIWaWG5:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1925)):*
> ```Java
>     }
> 
>     log.info("Task [DelegateTaskEvent: {}] already queued, dropping this request ", delegateTaskEvent);
> ```

same here



_Code quote:_
```Java
delegateTaskEvent
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1970 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgTkWMDthrT7FTYvYq:-NIgTkWMDthrT7FTYvYr:byu13nn) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1970)):*
> ```Java
>           }
>           return;
>         } else if (log.isDebugEnabled()) {
> ```

this check is not needed



_Code quote:_
```Java
if (log.isDebugEnabled())
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1972 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgMFQB3ewJoEAC2Nyg:-NIgTa737TWxeD2DorQL:b-5get6k) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1972)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I don't know about these, logs still need to be useful after this exercise. 
</blockquote></details>

It should be fine, we already have taskId and accountId in context, so just cleaning these logs here.



_Code quote:_
```Java
submitted for execution
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1987 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgTnF-ANfBj2qDRUet:-NIgTnF05NIBGR7ZKMSr:b-fea4ra) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1987)):*
> ```Java
>           applyDelegateSecretFunctor(delegateTaskPackage);
>           // Whitelisted. Proceed immediately.
>           if (log.isDebugEnabled()) {
> ```

same here and elsewhere



_Code quote:_
```Java
log.isDebugEnabled()) 
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2024 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgU9MT0V6ak1SnG0j0:-NIgU9MT0V6ak1SnG0j1:bxgjtma) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2024)):*
> ```Java
>             Optional.ofNullable(delegateConnectionResults).orElse(emptyList());
>         boolean validated = results.stream().allMatch(DelegateConnectionResultDetail::isValidated);
>         log.info("Validation {} for task", validated ? "succeeded" : "failed");
> ```

this is better way of logging, instead of if/else



_Code quote:_
```Java
        log.info("Validation {} for task", validated ? "succeeded" : "failed");
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2035 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgULUC82iHjaIjZILz:-NIgULUC82iHjaIjZIM-:b-m1xcpv) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2035)):*
> ```Java
>             executeTask(delegateTaskPackage);
>           } else {
>             log.info("Did not get the go-ahead to proceed for task");
> ```

I think we should still log this as warning, I don't think thats the usual case.



_Code quote:_
```Java
log.info("Did not get the go-ahead to proceed for task");
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2338 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgUiUC4ecNuc3HgNz_:-NIgUiUC4ecNuc3HgNza:b-w168po) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2338)):*
> ```Java
>       sleep(ofSeconds(5));
>       taskFuture = currentlyExecutingFutures.get(taskId).getTaskFuture();
>       if (taskFuture != null && (taskFuture.isDone() || taskFuture.isCancelled())) {
> ```

I don't see any purpose of this check, if it's finished or cancelled, then we shouldn't be here.



_Code quote:_
```Java
(taskFuture.isDone() || taskFuture.isCancelled())
```


<!-- Sent from Reviewable.io -->

2022-12-07 22:10 UTC, jennyjames21 commented
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1711 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIicMwe245lU2t3F65_:-NIicMwe245lU2t3F65a:b-z14qzp) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1711)):*
> ```Java
>             getDurationString(delegateHeartbeatResponse.getResponseSentAt(), now));
>       } else if (log.isDebugEnabled()) {
>         log.debug("Delegate {} received heartbeat response {} after sending. {} since last response.", receivedId,
> ```

Else part is more of delay case and less number of occurrences, which is useful as we only debug if HB is delayed

 


<!-- Sent from Reviewable.io -->

2022-12-07 22:12 UTC, jennyjames21 commented
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2680 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIidGbo25xvFmy30LMY:-NIidGbo25xvFmy30LMZ:b-y81ash) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2680)):*
> ```Java
>           if (log.isDebugEnabled()) {
>             log.debug("Task {} response sent to manager", taskId);
>           }
> ```

Can we keep this line? how do we know the response sent back to the manager otherwise


<!-- Sent from Reviewable.io -->

2022-12-07 22:14 UTC, jennyjames21 commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 709 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIidgZaBTeSwnq97PrN:-NIidgZaBTeSwnq97PrO:b-92y5ga) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L709)):*
> ```Java
>                   + CapabilityHelper.generateLogStringWithSelectionCapabilitiesGenerated(
>                       task.getTaskDataV2().getTaskType(), task.getExecutionCapabilities()));
>         }
> ```

This is a helpful log.


<!-- Sent from Reviewable.io -->

2022-12-07 22:15 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIie1UT94U-O_4UbXBW:-NIie1UT94U-O_4UbXBX:b4hr5ep) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L141)):*
> ```Java
>           }
>         }
>         log.info("Response received for task: {} from Delegate: {}", taskId, delegateId);
> ```

Arpit, log cost is per line. So it's better to keep as much as useful information on a single line


<!-- Sent from Reviewable.io -->

2022-12-09 09:03 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1711 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIicMwe245lU2t3F65_:-NIpv6Kq7z8W5CDAepQZ:bj85d8w) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1711)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Else part is more of delay case and less number of occurrences, which is useful as we only debug if HB is delayed

 
</blockquote></details>

No, else part will occur if delay is less than 3 mins (most cases). We are already logging a warning above if delay is more that 3 mins
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1902 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgKqVv-iKZCr2G2Yhb:-NIpviuL7QprUgv-9C0v:b4gd3lm) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1902)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Is taskId present in the log context? What about when viewing raw container logs? If not easily available there, we shouldn't remove it, but also logs without any params usually are not useful and are candidates for removal. 
Whatever the case, if you want it back though, don't use string concatenation, use parametrized logging.  
We don't gain much by removing this from log. The same questions goes for delegateTaskEvent
</blockquote></details>

taskId is already present in logContext (labels). So we should avoid duplicacy here.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2035 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgULUC82iHjaIjZILz:-NIpywEx0Rx4AlbN0xuq:b-n0tmpk) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2035)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I think we should still log this as warning, I don't think thats the usual case.
</blockquote></details>

this can be inferred with the above log line of whether the validation succeeded or failed.



_Code quote:_
```Java
            if (validated) {
              log.info("Task validated but was not assigned");
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2680 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIidGbo25xvFmy30LMY:-NIpzcyrEf2tUjy8lPnw:b-791pmn) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2680)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Can we keep this line? how do we know the response sent back to the manager otherwise
</blockquote></details>

from the manager logs we can check whether it received the response or not. (save cost :) )
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 709 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIidgZaBTeSwnq97PrN:-NIq-0ga6wCg67PB51hw:b-7cwnp7) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L709)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

This is a helpful log.
</blockquote></details>

Will this not reflect in the selection logs? 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1191 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgS5CX8pH9B8l_IrOx:-NIq0da3Dbyq2AuDTlRC:b1azu7q) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1191)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

same here
</blockquote></details>

logContext is already there
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1553 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgSMhD1I9mHiiyKUfP:-NIq140M68r8in1i3FZP:b2v4nsm) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1553)):*
> logContext is already there
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIie1UT94U-O_4UbXBW:-NIq1T1W2dmWMj44PiwE:b304zeh) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L141)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Arpit, log cost is per line. So it's better to keep as much as useful information on a single line
</blockquote></details>

Ack, removed taskId which can be inferred from logContext labels
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/common/AbstractDelegateRunnableTask.java` line 135 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgSyhp5geFo9e6gwj7:-NIq2zDtA45cSpYsSytw:b-oaijxy) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/930-delegate-tasks/src/main/java/io/harness/delegate/task/common/AbstractDelegateRunnableTask.java#L135)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why remove this
</blockquote></details>

Ack. The occurrence of this message is almost negligible.
___
*[`970-grpc/src/main/java/io/harness/event/client/impl/appender/ChronicleEventAppender.java` line 50 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgTS_P3O2JdHApRzlF:-NIq6Yn9Ands451hZNV1:b3r9bpd) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/970-grpc/src/main/java/io/harness/event/client/impl/appender/ChronicleEventAppender.java#L50)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I don't think that warn messages should so lightly be converted to debug. This is obviously erroneous condition (or an edge case). If we are seeing a lot of these messages, to action should be to get it investigated and fixed by appropriate team, not to mask it and forget there is an issue. 
</blockquote></details>

We will get CCM team approval here. And let them have a take on this



_Code quote (from 960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java):_
```Java
log.info("Watcher up to date");
```


<!-- Sent from Reviewable.io -->

2022-12-09 09:19 UTC, puthrayaharness approved these changes

2022-12-09 09:38 UTC, abhinav-harness commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java
> -        log.info("Response received for task: {} from Delegate: {}", taskId, delegateId);
this should have task id

2022-12-09 09:39 UTC, abhinav-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/common/AbstractDelegateRunnableTask.java
> -      log.info("Started executing task {}", taskId);
can we not have this?

2022-12-09 09:39 UTC, abhinav-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/common/AbstractDelegateRunnableTask.java
> -      log.info("Completed executing task {}", taskId);
ditto

2022-12-09 09:40 UTC, abhinav-harness commented on 970-grpc/src/main/java/io/harness/event/client/impl/appender/ChronicleEventAppender.java
> +      log.debug("Dropping message as queue is not healthy");
this should be rare, right??

2022-12-09 09:40 UTC, abhinav-harness commented on 970-watcher-beans/src/main/java/io/harness/delegate/message/MessageServiceImpl.java
> +      log.info("{}: {}({})", output, message, paramStr);
log.debug?

2022-12-09 10:28 UTC, arpit3107 commented on 970-watcher-beans/src/main/java/io/harness/delegate/message/MessageServiceImpl.java
> +      log.info("{}: {}({})", output, message, paramStr);
Done

2022-12-09 10:30 UTC, arpit3107 commented on 970-grpc/src/main/java/io/harness/event/client/impl/appender/ChronicleEventAppender.java
> +      log.debug("Dropping message as queue is not healthy");
This was listed in the log cost sheet prepared by CCM team. BTW its 30k per hour in prod-2

2022-12-09 10:33 UTC, arpit3107 commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java
> -        log.info("Response received for task: {} from Delegate: {}", taskId, delegateId);
taskId is in logContext labels

2022-12-09 10:36 UTC, arpit3107 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/common/AbstractDelegateRunnableTask.java
> -      log.info("Started executing task {}", taskId);
Didnt got this. Do you want this log or not? I am moved it to debug

2022-12-09 13:50 UTC, mdmilic requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 11. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1902 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgKqVv-iKZCr2G2Yhb:-NIqmPV55qE26OXkbrt4:b-vj3ccs) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1902)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

taskId is already present in logContext (labels). So we should avoid duplicacy here.
</blockquote></details>

Removing that is a nano optimisation for logging price wise, but it actually makes logs less useful (so it costs way more in time you spent to understand them). E.g. makes it harder to filter logs because you can't search now for `Dropping task 12345`
I think you should not be removing parameters for any of these logs even if that parameter is in log context.
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIie1UT94U-O_4UbXBW:-NIr0XIS3aFV1LLhbH6H:bys610p) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L141)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Ack, removed taskId which can be inferred from logContext labels
</blockquote></details>

Logs actually cost per GB ($0.5/GiB), but I agree that we should keep as much useful info in log line. removing e.g. taskId from log will save you about $1 for every 100.000.000 occurrences. But can cost you $20 per lost dev productivity per instance. so this is not a save. If you want to remove it I would rather remove it from log context since there it's way less useful (though I would prefer we keep it there as well). 
You would make the same log price savings for instance by trimming the log line like this, but that's going to have the same negative effect at dev productivity. 
`log.info("Tsk {} rspns rcvd, del {}", taskId, delegateId);`
Logs savings should be done by:
* Removing duplicate log lines (e.g. merging them into single)
* Removing log lines that are not useful (e.g. all the info from that line is extremely obvious to see from surrounding logs. If it's just deducible, but takes you 10min to figure it out or you need to combine multiple sources to figure it out like logs + metrics or logs + code, this is not a save, it's actually more expensive)
* Logs that are not always needed, but can be useful & are happening millions of times per h, should become debug. 
* etc
Whatever you do to save cost on logs, that should not affect eng productivity in major way since that costs orders of magnitude more than logs. 
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 141 at r5](https://reviewable.io/reviews/harness/harness-core/41138#-NIr0OLc5N1PFeCEOQDD:-NIr0OLfDsrkAzWzwSkx:bukmgcn) ([raw file](https://github.com/harness/harness-core/blob/c749030bcdb5a07d3a49142a3a4e3b7de3ef3872/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L141)):*
> ```Java
>           }
>         }
>         log.info("Response received for task from Delegate: {}", delegateId);
> ```

put the taskId please. Ignore the fact that it's in the log context


<!-- Sent from Reviewable.io -->

2022-12-09 20:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=41138) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=41138) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: raghuAtWings<br/>:white_check_mark: arpit3107<br/>:x: hitesharinga<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=41138) it.</sub>

2022-12-10 00:46 UTC, raghuAtWings commented
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1075 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgIuGa1U84co8aHYCW:-NItUtxj9z39L1Wd9jw2:brmtv24) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1075)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

please don't use isDebugEnabled. Just use log.debug instead (for all occurrences here) it will reduce cognitive complexity . 
isDebugEnabled (and equivalent methods) are intended for much more complex use cases, where computing log string is expensive and can't be parametrized/static. We don't have these use cases anywhere. If you see usage of logs where strings are concatenated or there is String.format, you can convert it to parametrized, but even those normally wouldn't be expensive enough to sacrifice on code complexity for this.
</blockquote></details>

the pmd check fails if you don't do it


<!-- Sent from Reviewable.io -->

2022-12-12 06:42 UTC, arpit3107 commented on 970-watcher-beans/src/main/java/io/harness/delegate/message/MessageServiceImpl.java
> +      log.info("{}: {}({})", output, message, paramStr);
Updated the usage

2022-12-13 19:50 UTC, abhinav-harness approved these changes
> Reviewed 8 of 14 files at r3, 3 of 6 files at r4, 2 of 6 files at r5, 5 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-14 05:10 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 10. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1902 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgKqVv-iKZCr2G2Yhb:-NJ4-hBrCjbgg3hfu_74:b3i3fmd) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1902)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i don't think thats the case, we can still search with AND condition
</blockquote></details>

That log filtering is not a good approach. We should put taskId/delegateId in AND condition
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 141 at r5](https://reviewable.io/reviews/harness/harness-core/41138#-NIr0OLc5N1PFeCEOQDD:-NJ4-xvy7oZYV8znPXsc:b-gme6k2) ([raw file](https://github.com/harness/harness-core/blob/c749030bcdb5a07d3a49142a3a4e3b7de3ef3872/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L141)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

put the taskId please. Ignore the fact that it's in the log context
</blockquote></details>

:) Done


<!-- Sent from Reviewable.io -->

2022-12-14 05:45 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 10. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 452 at r8](https://reviewable.io/reviews/harness/harness-core/41138#-NJE9MF60icmxUWnjtd1:-NJE9MF60icmxUWnjtd2:bmf7qef) ([raw file](https://github.com/harness/harness-core/blob/581c720127361016954f9d86dc652d19cc55f130/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L452)):*
> ```Java
>              TaskType.valueOf(task.getData().getTaskType()).getTaskGroup().name(), task.getRank(), OVERRIDE_NESTS);
>          AutoLogContext ignore2 = new AccountLogContext(task.getAccountId(), OVERRIDE_ERROR)) {
>       log.info("Queueing async task {} of type {} ", task.getUuid(), task.getData().getTaskType());
> ```

This log is the indicator that task submitted to manager and it will soon prepare for its execution. We can have this.



_Code quote:_
```Java
log.info("Queueing async task {} of type {} ", task.getUuid(), task.getData().getTaskType());
```


<!-- Sent from Reviewable.io -->

2022-12-15 09:21 UTC, gaurav-jain1 reviewed
> Reviewed 8 of 14 files at r3, 3 of 6 files at r4, 2 of 6 files at r5, 5 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 10. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-18 10:27 UTC, arpit3107 approved these changes
> Reviewed 8 of 14 files at r3, 3 of 6 files at r4, 2 of 6 files at r5, 4 of 5 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2 change requests. 10. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-19 10:01 UTC, gaurav-jain1 approved these changes
> Reviewed 8 of 14 files at r3, 3 of 6 files at r4, 2 of 6 files at r5, 5 of 5 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 1 change requests. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-19 21:57 UTC, jennyjames21 commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 709 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIidgZaBTeSwnq97PrN:-NJgNvzwE2G6oCCbKg64:bm2vcr6) ([raw file](https://github.com/harness/harness-core/blob/a091b504a40e21c69f4e2e01313b260db675f412/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L709)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Will this not reflect in the selection logs? 
</blockquote></details>

no. please keep something :)


<!-- Sent from Reviewable.io -->

2022-12-19 23:39 UTC, mdmilic approved these changes
> Reviewed 4 of 5 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: 2. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1902 at r4](https://reviewable.io/reviews/harness/harness-core/41138#-NIgKqVv-iKZCr2G2Yhb:-NJgcROj67vP7WCsqg6p:b13p97b) ([raw file](https://github.com/harness/harness-core/blob/56f614b95767c7a7f52bcd2f88a538a4c9fdeab0/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1902)):*
Will resolve it, but I think this actually proves my point. You now need to be advanced log explorer user to be able to properly search the logs plus you now usually need more clicks to get to the results. The fact that three of us might know how to construct log queries doesn't mean that everyone does. Additional problem is that the taskId will now be hidden offscreen (usually not visible due to being at the end of the line with rest of log context), so you can't easily follow logs without filtering. I still think this costs more than it saves (and I also think the actual $ savings are quite minimal). 
> That log filtering is not a good approach. We should put taskId/delegateId in AND condition
Why do you think log filtering is not a good approach? They are both actually log queries, first one just being simpler, so if anything doing conditions might even have performance penalty (I'm sure google is heavily indexing those logs, so don't expect much of a penalty)


<!-- Sent from Reviewable.io -->

2022-12-20 06:36 UTC, arpit3107 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41138)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-20 06:38 UTC, merged