fix: [CDS-46113]: custom secret
harness/harness-core pull request #41186
Opened 2022-12-06 11:31 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-09 07:17 UTC, inderschera approved these changes
> Reviewed 2 of 16 files at r1, 1 of 6 files at r2, 6 of 9 files at r4, 3 of 5 files at r5, 3 of 4 files at r6, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41186)* status: 21 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-09 16:00 UTC, vivekkarnatiharness approved these changes
> Reviewed 2 of 16 files at r1, 1 of 6 files at r2, 6 of 9 files at r4, 2 of 5 files at r5, 3 of 4 files at r6, 6 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41186)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-10 01:36 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +      if (isEmpty(artifactConfig.getScripts().getFetchAllArtifacts().getArtifactsArrayPath().getValue())) {
If getArtifactsArraypath() is null won't getArtifactsArraypath().getValue() be null and give a NPE?

2022-12-10 01:36 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +      if (isEmpty(artifactConfig.getScripts().getFetchAllArtifacts().getVersionPath().getValue())) {
Same with getVersionPath()?

2022-12-10 02:07 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java
> +        if (customArtifactConfig.isFromTrigger()) {
Any way we can combine the logic with custom trigger? How was it working earlier?

2022-12-10 02:14 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +        delegateGrpcClientWrapper, delegateMetricsService, ngSecretService, exceptionManager);
May not need exceptionManager passed to NgCustomSecretExpressionEvaluator

2022-12-10 02:16 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +        delegateGrpcClientWrapper, delegateMetricsService, ngSecretService, exceptionManager);
Also delegateGrpcClientWrapperdelegateGrpcClientWrapper

2022-12-10 02:16 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +    int secretFunctor = HashGenerator.generateIntegerHash();
Nit: Change the variable name to secretFuntor token?

2022-12-10 02:22 UTC, sribalij requested changes
few comments added

2022-12-10 02:52 UTC, shivamnegi94 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java
> +        if (customArtifactConfig.isFromTrigger()) {
Same code is being used when we execute the pipeline to verify the build and secrets expression is taken care by delegate task

2022-12-10 04:08 UTC, shivamnegi94 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +    int secretFunctor = HashGenerator.generateIntegerHash();
Resolved

2022-12-12 02:23 UTC, shivamnegi94 commented
trigger messagecheck

2022-12-12 07:35 UTC, sribalij approved these changes
> Reviewed 2 of 16 files at r1, 2 of 5 files at r5, 2 of 4 files at r6, 4 of 6 files at r8, 1 of 1 files at r9, 1 of 4 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41186)* status: 4 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-12 07:48 UTC, vtxorxwitty approved these changes
> Reviewed 2 of 16 files at r1, 6 of 9 files at r4, 2 of 5 files at r5, 2 of 4 files at r6, 4 of 6 files at r8, 1 of 1 files at r9, 1 of 4 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41186)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-12 07:54 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41186)* status: 4. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 250 at r9](https://reviewable.io/reviews/harness/harness-core/41186#-NIbC9aUFpHpfPQ3zvpo-r9-250:-NJ4JsHk4b7DsVeHLuz1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0fc9c760003ec35050d485e3a5dc842b263cf72e/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L250)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Also delegateGrpcClientWrapperdelegateGrpcClientWrapper
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 285 at r9](https://reviewable.io/reviews/harness/harness-core/41186#-NIbC9aUFpHpfPQ3zvpo-r9-285:-NJ4JtOA4QW-pl3Slyeq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0fc9c760003ec35050d485e3a5dc842b263cf72e/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L285)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

If getArtifactsArraypath() is null won't getArtifactsArraypath().getValue() be null and give a NPE?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 288 at r9](https://reviewable.io/reviews/harness/harness-core/41186#-NIbC9aUFpHpfPQ3zvpo-r9-288:-NJ4Ju7t7nfApzYCHnzX:bs7wumb) ([raw file](https://github.com/harness/harness-core/blob/0fc9c760003ec35050d485e3a5dc842b263cf72e/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L288)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Same with getVersionPath()?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-12 08:09 UTC, sribalij approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41186)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-12 08:10 UTC, sribalij approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41186)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-12 09:33 UTC, merged