Cds 2970 merge
harness/harness-core pull request #41196
Opened 2022-12-06 14:03 UTC by akhilpandey1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-08 13:15 UTC, akhilpandey1 commented
trigger feature-build

2022-12-08 22:02 UTC, tmacari-harness requested changes
> Reviewed 2 of 29 files at r1, 1 of 12 files at r2, 3 of 14 files at r3, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 37 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIn0yvuAxslR70lqhnh:-NIn0yvuAxslR70lqhni:b5syrt1) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java#L64)):*
> ```Java
>   protected <T extends Base> void bulkSetTerraformSourceType(
>       String accountId, Class<T> clazz, Set<String> infrastructureProvisionersIdSet) {
>     final DBCollection collection = wingsPersistence.getCollection(clazz);
> ```

those fields are not used
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIn11VO6fQ-g3yymhfQ:-NIn11VO6fQ-g3yymhfR:bhre6nr) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java#L67)):*
> ```Java
>     BulkWriteOperation bulkWriteOperation = collection.initializeUnorderedBulkOperation();
> 
>     try (HIterator<TerraformInfrastructureProvisioner> terraformInfrastructureProvisioners =
> ```

We already fetched the provisioners in the method above to get their IDs, not sure if we need to fetch them again.
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 767 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInGwTU6zGVwnPjkNxi:-NInGwTU6zGVwnPjkNxj:b-7mdlnl) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L767)):*
> ```Java
>       TerraformSourceType terraformSourceType, String s3URI, String awsConfigId) {
>     //    Initialize Git variables
> ```

A validation should be done here, if it's s3 then all s3 required params should be there , if GIT all git details should be available
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 805 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInHLwf5mj_ZN_OCV7H:-NInHLwf5mj_ZN_OCV7I:bv9d34p) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L805)):*
> ```Java
>                             .useTfConfigInspectLatestVersion(
>                                 featureFlagService.isEnabled(TERRAFORM_CONFIG_INSPECT_VERSION_SELECTOR, accountId))
>                             .sourceRepoSettingId(!terraformSourceType.equals(TerraformSourceType.S3)
> ```

we can have only one if / else and set on the builder only the relevant values (s3 details or git details)
Same for targets.
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 944 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInHtl_DjxD64p9svaP:-NInHtl_DjxD64p9svaQ:b-viexsg) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L944)):*
> ```Java
>   private List<EncryptedDataDetail> getAwsS3EncryptionDetails(AwsConfig awsS3SourceBucketConfig, String appId) {
>     return secretManager.getEncryptionDetails(awsS3SourceBucketConfig, appId, null);
>   }
> ```

let's add empty line between methods.
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 948 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInIMJfDo75pAHF7R9g:-NInIMJfDo75pAHF7R9h:bco2njv) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L948)):*
> ```Java
>     return (AwsConfig) getAwsConfigSettingAttribute(awsConfigId).getValue();
>   }
>   protected SettingAttribute getAwsConfigSettingAttribute(String awsConfigId) {
> ```

Why protected? this is called only the above method,  we can have that logic in one method.
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 949 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInJCb_ACpTo3DDe5e0:-NInJCb_ACpTo3DDe5e1:b-ci6gue) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L949)):*
> ```Java
>   }
>   protected SettingAttribute getAwsConfigSettingAttribute(String awsConfigId) {
>     SettingAttribute awsSettingAttribute = settingsService.get(awsConfigId);
> ```

let't also check for null as we do for gitConfig
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 964 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInJNNs0tjDjF5KNCHd:-NInJNNs0tjDjF5KNCHe:b-4um2am) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L964)):*
> ```Java
> 
>   private void validateTerraformProvisioner(TerraformInfrastructureProvisioner terraformProvisioner) {
>     if (terraformProvisioner.getSourceType().equals(TerraformSourceType.GIT)) {
> ```

what if S3 we should validate if s3 details are there
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java` line 201 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInKJKoB9G4juIDCEq9:-NInKJKoB9G4juIDCEqA:b-z146ea) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java#L201)):*
> ```Java
>   protected void validateBranchCommitId(String sourceRepoBranch, String commitId) {
>     if (isEmpty(sourceRepoBranch) && isEmpty(commitId)) {
>       throw new InvalidRequestException("Either sourceRepoBranch or commitId or s3URI should be specified", USER);
> ```

we're checking only if sourceRepoBranch or commitId are empty, why do we add s3URi to error message?
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java` line 208 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInNnB59nDGgIjoBpq3:-NInNnB59nDGgIjoBpq4:be34mmp) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java#L208)):*
> ```Java
>   }
> 
>   protected void validateBranchCommitId(String sourceRepoBranch, String commitId, String s3URI) {
> ```

We are not validating only branch and commitId, method name should be more appropriate.
Validation should be more complex, what if we have s3URI but no awsConfigId..  there are more scenarios, we can discuss.
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java` line 209 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInM0BWDfDy_Qqzpyvz:-NInM0BWDfDy_Qqzpyw-:btmss2e) ([raw file](https://github.com/harness/ha [...]

2022-12-09 07:00 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 944 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInHtl_DjxD64p9svaP:-NIpfkIk72bw1BYBp5HQ:bb7oryy) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L944)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's add empty line between methods.
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2022-12-09 07:29 UTC, akhilpandey1 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIn11VO6fQ-g3yymhfQ:-NIpmUMu8epSDa_2AAMj:b-qsi48c) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java#L67)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We already fetched the provisioners in the method above to get their IDs, not sure if we need to fetch them again.
</blockquote></details>

Updated this file


<!-- Sent from Reviewable.io -->

2022-12-09 07:29 UTC, akhilpandey1 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIn0yvuAxslR70lqhnh:-NIpmXCA3g2Nl55RxJoj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java#L64)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

those fields are not used
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 07:34 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 767 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInGwTU6zGVwnPjkNxi:-NIpnW5p3ByDiKE-90E6:bxkeb0x) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L767)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

A validation should be done here, if it's s3 then all s3 required params should be there , if GIT all git details should be available
</blockquote></details>

Done, introduced new validation



_Code snippet:_
```Java
  private void validateS3Config(String awsConfigId, String s3URI, String scmSettingId) {
    if (isEmpty(awsConfigId) || isEmpty(s3URI)) {
      throw new InvalidRequestException("Both AWS Cloud Provider and S3 URI must be specified", USER);
    }
    if (isNotEmpty(scmSettingId) && isNotEmpty(awsConfigId)) {
      throw new InvalidRequestException("Cannot specify both AWS Cloud Provider and GIT repo", USER);
    }
  }
```


<!-- Sent from Reviewable.io -->

2022-12-09 09:42 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 949 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInJCb_ACpTo3DDe5e0:-NIqG-L3DhVGmkFiuQzk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L949)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let't also check for null as we do for gitConfig
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 09:42 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 948 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInIMJfDo75pAHF7R9g:-NIqG0NW8NFWfqKqpNdK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L948)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why protected? this is called only the above method,  we can have that logic in one method.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 10:19 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java` line 208 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInNnB59nDGgIjoBpq3:-NIqOP7y1QZCd55jpixG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java#L208)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We are not validating only branch and commitId, method name should be more appropriate.
Validation should be more complex, what if we have s3URI but no awsConfigId..  there are more scenarios, we can discuss.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 10:19 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java` line 209 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInM0BWDfDy_Qqzpyvz:-NIqOPuSBnfTZaUmxUYO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/InfrastructureProvisionerYamlHandler.java#L209)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

what if it's s3there is no branch and commitId? from now that's a valid scenario.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 10:32 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandler.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInRf0N3guG4gThb5Gq:-NIqRNdf4sqNdazFahcy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandler.java#L44)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We should set the the fields to YAML if that's the case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 10:32 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandler.java` line 105 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInRCaC1idagykfYkJw:-NIqRO9s2vhS0RA-EIeF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandler.java#L105)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we should set s3 fields form YAML to bean if that's the case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 10:32 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 258 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInUB0D7SwhhZ91NTCL:-NIqRS2N6dc0vpNVlf-t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L258)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why do we need tfVarAWSConfigId if we have S3FileConfig tfVarS3FileConfig which contains the awsConfigId ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 10:34 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 841 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInVqIsCoKbCUkeTEoB:-NIqRgE21QSre4puufkh:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L841)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

After we runt migration the should be no scenario when shourceType is null it should be GIT or S3
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-09 10:34 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1335 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIndt9_4xVz0okmzM3U:-NIqRuig1124lYw5dSCV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1335)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

After we run migration we should have no terraformProvisioner with sourceType null.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 10:35 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1344 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIne9Qg3-vrh3M-IdS9:-NIqS5IP7MBZlrDgePeG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1344)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

method name doesn't reflect what it actually does, awsConfigId is not used in that method
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 11:01 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1423 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInb2gp2jygdc0qeFKV:-NIqXuYG-Pc1dgXhO1T9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1423)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

it takes the URI from tfVarS3FileConfig, it should take it from backendConfig.getS3BackendConfig
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 11:01 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1427 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInba_f6frsuqj2gkrq:-NIqXw6REVdGdlH5Veij:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1427)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we set multipleFiles to S3URIList of tfVarS3FileConfig that's not correct while we're handling backendConfig
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 11:03 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 37 file(s) to review. 1 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 354 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIqVYCkBo65RmMmxK53:-NIqVYCmDsb-h1dI6ydY:b8hd0sn) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L354)):*
> ```Java
>       if (REMOTE_STORE_TYPE.equals(terraformExecutionData.getBackendConfigStoreType())) {
>         backendConfigStoreType = REMOTE_STORE_TYPE;
>         remoteBackendConfig = terraformExecutionData.getRemoteBackendConfig().getGitFileConfig();
> ```

should we handle scenario with s3?
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 641 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIqXho31cq3HntX9thY:-NIqXho89wxtthnHNe2M:b1vebsi) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L641)):*
> ```Java
>       collectVariables(others, terraformExecutionData.getVariables(), VARIABLES_KEY, ENCRYPTED_VARIABLES_KEY, true);
> 
>       if (featureFlagService.isEnabled(TERRAFORM_REMOTE_BACKEND_CONFIG, context.getAccountId())) {
> ```

We have to handle s3 scenario
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 680 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIqXriBEmMTkyiHFD0Q:-NIqXriBEmMTkyiHFD0R:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L680)):*
> ```Java
>       if (null != tfVarSource) {
>         if (tfVarSource.getTfVarSourceType() == TfVarSourceType.GIT) {
>           GitFileConfig gitFileConfig = ((TfVarGitSource) tfVarSource).getGitFileConfig();
> ```

same here
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1224 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIqYMNf06OuO9rBi6-h:-NIqYMNf06OuO9rBi6-i:b-o8duko) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1224)):*
> ```Java
>           }
> 
>           if (featureFlagService.isEnabled(TERRAFORM_REMOTE_BACKEND_CONFIG, context.getAccountId())
> ```

We should handle s3 scenario


<!-- Sent from Reviewable.io -->

2022-12-09 11:17 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1437 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIn_sxs0nUU2VVvEJjZ:-NIqaZto1vAerTz_nJHh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1437)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

This method and the one above are almost identical, we can reuse the logic and have only one method
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 11:17 UTC, akhilpandey1 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-12-09 11:18 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 805 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInHLwf5mj_ZN_OCV7H:-NIqaqzzAVJMeyShhHtA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L805)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we can have only one if / else and set on the builder only the relevant values (s3 details or git details)
Same for targets.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 11:18 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 964 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NInJNNs0tjDjF5KNCHd:-NIqaukn4ED6nS0_xGW2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L964)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

what if S3 we should validate if s3 details are there
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-11 10:40 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 40 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1344 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIne9Qg3-vrh3M-IdS9:-NJ-aha20GPkGQkXzOaH:bxfe6um) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1344)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We don't set any auth params in this method, we should remove AuthParams from method name 
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 897 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ-l1Sh9OP3yxmZtSqn:-NJ-l1Sh9OP3yxmZtSqo:b-7ylusm) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L897)):*
> ```Java
>       inhertiedConfig.setStoreType(storeType != null ? storeType : LOCAL_STORE_TYPE);
>       inhertiedConfig.setRemoteBackendConfig(element.getRemoteBackendConfig());
>       if (REMOTE_STORE_TYPE.equals(storeType)) {
> ```

Should we handle s3 scenario also?
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 945 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ-jiSdAwPl0LDpwIJe:-NJ-jiSdAwPl0LDpwIJf:b-eo6dfd) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L945)):*
> ```Java
>       }
>     } else if (tfVarS3FileConfig != null) {
>       tfVarSource = fetchTfVarS3Source(context);
> ```

Not sure if it makes sense, If it's inherit form plan scenario we should take data from inherit element.


<!-- Sent from Reviewable.io -->

2022-12-11 11:29 UTC, tmacari-harness requested changes
> Reviewed 1 of 8 files at r7, 2 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformRollbackState.java` line 283 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ-t5mN27PYTt-v9thc:-NJ-t5mN27PYTt-v9thd:bfx2v4v) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/sm/states/provision/TerraformRollbackState.java#L283)):*
> ```Java
>             .tfVarFiles(configParameter.getTfVarFiles())
>             .remoteS3BackendConfig(remoteS3BackendConfig)
>             .s3URI(terraformProvisioner.getSourceType().equals(TerraformSourceType.S3) ? terraformProvisioner.getS3URI()
> ```

Why  not to add s3URI inside if statement below (along with awsS3EncryptionDetails and  awsS3SourceBucketConfig)?


<!-- Sent from Reviewable.io -->

2022-12-11 12:47 UTC, tmacari-harness requested changes
> Reviewed 8 of 29 files at r1, 5 of 14 files at r3, 1 of 4 files at r4, 1 of 1 files at r5, 1 of 8 files at r7, 2 of 5 files at r8, 2 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationList.java` line 467 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ07cUY9QCAMa6yzWPc:-NJ07cUY9QCAMa6yzWPd:b-jg1u5d) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/390-db-migration/src/main/java/io/harness/migrations/MigrationList.java#L467)):*
> ```Java
>         .add(Pair.of(380, AddImmutableDelegateEnabledFieldToAccountCollection.class))
>         .add(Pair.of(381, AddRingDetailsToDelegateRing.class))
>         .add(Pair.of(384, InitTerraformProvisionersSourceType.class))
> ```

numbers should be consecutive
___
*[`400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java` line 43 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ0962n70i9wZI_fFKq:-NJ0962n70i9wZI_fFKr:b-8nlnm8) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java#L43)):*
> ```Java
>   private String awsConfigId;
>   private String s3URI;
>   private String awsSourceConfigName;
> ```

Here we don't need the name, name is only in YAML 
___
*[`400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java` line 80 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ09PXSC9wXpURFL0b7:-NJ09PXSC9wXpURFL0b8:b-j1yk14) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java#L80)):*
> ```Java
>       EmbeddedUser createdBy, long createdAt, EmbeddedUser lastUpdatedBy, long lastUpdatedAt, String entityYamlPath,
>       List<NameValuePair> backendConfigs, String repoName, List<NameValuePair> environmentVariables,
>       boolean skipRefreshBeforeApplyingPlan, String kmsId, String s3URI, String awsConfigId) {
> ```

why not to add TerraformSourceType to builder?
___
*[`400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java` line 117 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ08_YzCrUe2hm0aiky:-NJ08_YzCrUe2hm0aikz:bt6txq5) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java#L117)):*
> ```Java
>     private TerraformSourceType sourceType;
> 
>     private String awsConfigId;
> ```

Not sure if we need awsConfigId in YAML, usually we need only the name (ref: sourceRepoSettingName )
___
*[`400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java` line 77 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ09evy8TothtYj7gAO:-NJ09evy8TothtYj7gAP:b-4fd16d) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java#L77)):*
> ```Java
>   private final GitFileConfig remoteBackendConfig;
>   private final S3FileConfig s3BackendFileConfig;
>   private TerraformSourceType sourceType;
> ```

do we need to specify sourceType here? it is not used
___
*[`400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java` line 78 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ0Ax_VCBlOQ0_0dIoG:-NJ0Ax_VCBlOQ0_0dIoH:b-q8dv38) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java#L78)):*
> ```Java
>   private final S3FileConfig s3BackendFileConfig;
>   private TerraformSourceType sourceType;
>   private final S3FileConfig tfVarS3FileConfig;
> ```

I see we only set if when saving terraform config, why don't we use it at rollback?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java` line 125 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ02lYWBHm9kgaeQcIS:-NJ02lYWBHm9kgaeQcIT:b-x2taks) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java#L125)):*
> ```Java
>       }
> 
>       List<String> targets = terraformConfigInspectService.parseFieldsUnderCategory(absoluteModulePath,
> ```

in Git scenario it will always checkout or clone the repo. Even if absoluteModulePath will be the same on multiple tasks we will get latest content form git. What would happen in S3 case (when the content of a specific directory changed but we previously run TerraformFetchTargetsTask with it) ?
The same about fetch variables?
___
*[`930-delegate-tasks/src/main/java/software/wings/utils/GitUtilsDelegate.java` line 71 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ-xyizDM8VqBc545x1:-NJ-xyj-30C0TCPpGk5e:b-4gr7k5) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/930-delegate-tasks/src/main/java/software/wings/utils/GitUtilsDelegate.java#L71)):*
> ```Java
>   }
> 
>   public String resolveS3BucketAbsoluteFilePath(String downloadDir, AmazonS3URI s3URI) {
> ```

Those two methods are not about git, let's move them to a more appropriate place
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 2018 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ05qP519e4102Huq6s:-NJ05qP519e4102Huq6t:b-uc7lx4) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L2018)):*
> ```Java
>     kryo.register(EcsS3FetchRunTaskRequest.class, 573566);
>     kryo.register(EcsS3FetchRunTaskResponse.class, 573567);
>     kryo.register(TerragruntApplyTaskResponse.class, 573558);
> ```

Better not to change the place, they should be consecutive based on number
___
*[`scripts/license/add_license_header.sh` line 156 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ07Obn9BAp0qiDgiFO:-NJ07Obn9BAp0qiDgiFP:b-leegh1) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/scripts/license/add_license_header.sh#L156)):*
> ```Shell
> 
> function read_header_slash_star {
>   awk '/\/\*/ {isHeader=1}; isHeader == 1 {print}; /\*\// {exit}' "$FILE"
> ```

Is that an intentional change?


<!-- Sent from Reviewable.io -->

2022-12-11 12:47 UTC, tmacari-harness reviewed
> Reviewed 1 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-11 21:29 UTC, tmacari-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 221 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1kxMK2eCshEcFbUtq:-NJ1kxMK2eCshEcFbUtr:b-2pzkc0) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L221)):*
> ```Java
> 
>   private TerraformExecutionData run(TerraformProvisionParameters parameters) {
>     String sourceRepoSettingId;
> ```

Why do we need to define sourceRepoSettingId, gitOperationContext, gitConfig here? we need them only in git scenario. 
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 227 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1n8OHEx5fvvWG1SKz:-NJ1n8OHEx5fvvWG1SL-:b52g7r2) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L227)):*
> ```Java
>     GitOperationContext gitOperationContext = null;
>     GitConfig gitConfig = null;
>     EncryptedRecordData encryptedTfPlan = null;
> ```

Do we need that change?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 240 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1oTCeCzyiLFD_mqKg:-NJ1oTCeCzyiLFD_mqKh:b1hoc7b) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L240)):*
> ```Java
> 
>     if (parameters.getSourceType() != null && parameters.getSourceType().equals(TerraformSourceType.S3)) {
>       /**
> ```

those comments are not required, from code is obvious that we handle s3 scenario
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 246 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1omoW8p4qQFCEEkfn:-NJ1omoW8p4qQFCEEkfo:bbfy4i3) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L246)):*
> ```Java
>         encryptionService.decrypt(
>             parameters.getAwsS3SourceBucketConfig(), parameters.getAwsS3EncryptionDetails(), false);
>         awsS3HelperServiceDelegate.downloadS3Directory(
> ```

would be good lo add some informative execution logs as we do for git,,,, maybe to log the URI
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 252 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1of0PBdigXQ8GkdPI:-NJ1of0PBdigXQ8GkdPJ:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L252)):*
> ```Java
>       }
>     } else {
>       /**
> ```

same here
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 1320 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ232EF26aqDuOqFZOa:-NJ232EF26aqDuOqFZOb:brvwjy5) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L1320)):*
> ```Java
>   private String getTfBackendConfigContentLog(String tfBackendConfigFilePath, TerraformProvisionParameters parameters) {
>     StringBuilder backendLogBuilder = new StringBuilder("Initialize backend configuration with:\n");
>     if (REMOTE_STORE_TYPE.equals(parameters.getBackendConfigStoreType())) {
> ```

Should we handle s3 here?


<!-- Sent from Reviewable.io -->

2022-12-11 22:00 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 388 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ2BwnQ3acPB9BJyi_Y:-NJ2BwnR50b4EWHUYvWl:b1a7nox) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L388)):*
> ```Java
>       String tfBackendConfigFilePath = tfBackendConfigsFile.exists() ? tfBackendConfigsFile.getAbsolutePath() : null;
>       if (REMOTE_STORE_TYPE.equals(parameters.getBackendConfigStoreType())
>           && parameters.getRemoteBackendConfig() != null
> ```

Should we handle s3?


<!-- Sent from Reviewable.io -->

2022-12-12 08:00 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41196)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 248 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ4L2uB2Zz6TAv5H2rV:-NJ4L2uB2Zz6TAv5H2rW:b-ld2bxn) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L248)):*
> ```Java
>         awsS3HelperServiceDelegate.downloadS3Directory(
>             parameters.getAwsS3SourceBucketConfig(), parameters.getS3URI(), new File(workingDir));
>       } catch (InterruptedException e) {
> ```

Here we should catch any exception and handle in a way similar to git scenario.
If something fails we clean-up working directory.


<!-- Sent from Reviewable.io -->

2022-12-12 10:22 UTC, akhilpandey1 commented
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationList.java` line 467 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ07cUY9QCAMa6yzWPc:-NJ4qdDN8YbU4iiNiVHd:bcrkff1) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/390-db-migration/src/main/java/io/harness/migrations/MigrationList.java#L467)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

numbers should be consecutive
</blockquote></details>

Was done during testing, fixed



_Code quote:_
```Java
  .add(Pair.of(384, InitTerraformProvisionersSourceType.c
```


<!-- Sent from Reviewable.io -->

2022-12-13 18:50 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java` line 78 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ0Ax_VCBlOQ0_0dIoG:-NJBoehb8_q8I9SpXxN1:bcj22bk) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java#L78)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I see we only set if when saving terraform config, why don't we use it at rollback?
</blockquote></details>

we do use it in rollback, here: software/wings/sm/states/provision/TerraformRollbackState.java:241


<!-- Sent from Reviewable.io -->

2022-12-13 19:04 UTC, akhilpandey1 commented
*[`scripts/license/add_license_header.sh` line 156 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ07Obn9BAp0qiDgiFO:-NJBrrxL5EnaJvWGKSqr:b-1seavv) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/scripts/license/add_license_header.sh#L156)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Is that an intentional change?
</blockquote></details>

yes, this is a solution given by BT team for incorrect copyright comment addition


<!-- Sent from Reviewable.io -->

2022-12-13 19:17 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/utils/GitUtilsDelegate.java` line 71 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ-xyizDM8VqBc545x1:-NJBux7J-TtGtEYCK0oY:b-n334nv) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/930-delegate-tasks/src/main/java/software/wings/utils/GitUtilsDelegate.java#L71)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Those two methods are not about git, let's move them to a more appropriate place
</blockquote></details>

Done, introduced new utility class for s3 methods


<!-- Sent from Reviewable.io -->

2022-12-13 19:25 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 221 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1kxMK2eCshEcFbUtq:-NJBvCrf1GV4b2okEIA3:b-cvsw7n) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L221)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we need to define sourceRepoSettingId, gitOperationContext, gitConfig here? we need them only in git scenario. 
</blockquote></details>

Removed it and moved into git section of the code, I was following a pattern like manager, but it seems its not required on delegate


<!-- Sent from Reviewable.io -->

2022-12-13 19:25 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 227 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1n8OHEx5fvvWG1SKz:-NJBwmM8-ZLdZxtwvCfZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L227)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Do we need that change?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-13 19:27 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java` line 125 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ02lYWBHm9kgaeQcIS:-NJBx2VP5vmzO8-r8xHF:bi5ubap) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java#L125)):*
> TerraformFetchTargetsTask
> FetchVariables
Both should download files freshly as and when the command is triggered


<!-- Sent from Reviewable.io -->

2022-12-13 19:29 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformRollbackState.java` line 283 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ-t5mN27PYTt-v9thc:-NJBxjyCAsNiw7lzuVx3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/sm/states/provision/TerraformRollbackState.java#L283)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why  not to add s3URI inside if statement below (along with awsS3EncryptionDetails and  awsS3SourceBucketConfig)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-13 19:32 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1344 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIne9Qg3-vrh3M-IdS9:-NJBxsvy5h_HQvsLs8Uj:bdq6zzk) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1344)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We don't set any auth params in this method, we should remove AuthParams from method name 
</blockquote></details>

We do set AwsConfig param, so I felt that corresponds to auth param in this case which would be used by the delegate to fetch resources, naming is done as per existing convention ref: setAWSAuthParamsIfPresent() in this file


<!-- Sent from Reviewable.io -->

2022-12-14 13:46 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 240 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1oTCeCzyiLFD_mqKg:-NJFsd67BroDVfnPyWkg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L240)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

those comments are not required, from code is obvious that we handle s3 scenario
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 07:55 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 388 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ2BwnQ3acPB9BJyi_Y:-NJJlvEz9ms3G69m1rff:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L388)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Should we handle s3?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 07:55 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 1320 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ232EF26aqDuOqFZOa:-NJJlxUC81SfZxw7FvJZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L1320)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Should we handle s3 here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 07:56 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java` line 43 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ0962n70i9wZI_fFKq:-NJJm8-U-_lMP9pjwJTP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java#L43)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Here we don't need the name, name is only in YAML 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 07:56 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java` line 80 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ09PXSC9wXpURFL0b7:-NJJmCCI4FLYETkREtfv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java#L80)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why not to add TerraformSourceType to builder?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 07:57 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java` line 117 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ08_YzCrUe2hm0aiky:-NJJmPlz5HCIU8T5MPtk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/TerraformInfrastructureProvisioner.java#L117)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Not sure if we need awsConfigId in YAML, usually we need only the name (ref: sourceRepoSettingName )
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 07:57 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java` line 77 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ09evy8TothtYj7gAO:-NJJmYM3-l27z4Bk5XKP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/beans/infrastructure/TerraformConfig.java#L77)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

do we need to specify sourceType here? it is not used
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 09:13 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 354 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIqVYCkBo65RmMmxK53:-NJK2taC0NXL1OMvoufE:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L354)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

should we handle scenario with s3?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-15 09:14 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 641 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIqXho31cq3HntX9thY:-NJK32EW10O7ZMD1iSjm:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L641)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We have to handle s3 scenario
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-15 09:15 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 680 at r6](https://reviewable.io/reviews/harness/harness-core/41196#-NIqXriBEmMTkyiHFD0Q:-NJK3CxD6ePOqSDlszEM:b-w74okm) ([raw file](https://github.com/harness/harness-core/blob/c67059960c4c3c1150fd5518e1cc57f1dce39822/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L680)):*
Its already being done, if we expand below
>
else if (tfVarSource.getTfVarSourceType() == TfVarSourceType.S3) {
          S3FileConfig s3FileConfig = ((TfVarS3Source) tfVarSource).getS3FileConfig();
          others.put(TF_VAR_FILES_S3_CONFIG_ID_KEY, s3FileConfig.getAwsConfigId());
          others.put(TF_VAR_FILES_S3_URI_KEY, s3FileConfig.getS3URI());
          others.put(TF_VAR_FILES_S3_URI_LIST_KEY, s3FileConfig.getS3URIList());
  


<!-- Sent from Reviewable.io -->

2022-12-15 09:15 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 897 at r9](https://reviewable.io/reviews/harness/harness-core/41196#-NJ-l1Sh9OP3yxmZtSqn:-NJK3KL56Tzkwsjz38kM:b-5g9o7c) ([raw file](https://github.com/harness/harness-core/blob/2f36265dcbc3927140cd2b90bc5c6a246b41a735/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L897)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Should we handle s3 scenario also?
</blockquote></details>

yes, done


<!-- Sent from Reviewable.io -->

2022-12-15 09:18 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 248 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ4L2uB2Zz6TAv5H2rV:-NJK42w7BAjxvClEadbb:b91qw3f) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L248)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Here we should catch any exception and handle in a way similar to git scenario.
If something fails we clean-up working directory.
</blockquote></details>

makes sense, done in similar way


<!-- Sent from Reviewable.io -->

2022-12-15 09:19 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 252 at r10](https://reviewable.io/reviews/harness/harness-core/41196#-NJ1of0PBdigXQ8GkdPI:-NJK46weAMIYsrYAbvPJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/4ab5a0adf0f8b2b8b448eaa7aaea45f5d4280342/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L252)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-29 07:41 UTC, closed without merging