Piyushp/audit event service
harness/harness-core pull request #41197
Opened 2022-12-06 14:17 UTC by piyush-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-12 10:45 UTC, piyush-harness commented
trigger ti0,ti1,ti2,ti3,ti4

2022-12-15 12:06 UTC, piyush-harness commented
trigger ti1

2022-12-16 04:05 UTC, nishantsaini20 requested changes
> Reviewed 20 of 35 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41197)* status: 35 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/build/container/scripts/replace_configs.sh` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/41197#-NJO5CuB2oQpQyixNMTO:-NJO5CuB2oQpQyixNMTP:b-3q8d5n) ([raw file](https://github.com/harness/harness-core/blob/76d8b69e5330640c72238f717b522669207a26ef/audit-event-streaming/build/container/scripts/replace_configs.sh#L103)):*
> ```Shell
> fi
> 
> if [[ "" != "$GCP_PIPELINE_PUB_SUB_TOPIC" ]]; then
> ```

We don't need many such configs. We should clean up this file.
___
*[`platform-service/modules/audit-service/BUILD.bazel` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/41197#-NJO5wfd8Ay3sI6xAZp1:-NJO5wfd8Ay3sI6xAZp2:b-6qjmob) ([raw file](https://github.com/harness/harness-core/blob/76d8b69e5330640c72238f717b522669207a26ef/platform-service/modules/audit-service/BUILD.bazel#L14)):*
> ```Starlark
>     srcs = glob(["src/main/java/**/*.java"]),
>     resources = [],
>     visibility = ["//visibility:public"],
> ```

Should be ["//platform-service/service:__subpackages__", "//audit-event-streaming/service:__subpackages__"]


<!-- Sent from Reviewable.io -->

2022-12-16 04:28 UTC, reetika04 submitted a review, later dismissed
> Reviewed 20 of 35 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41197)* status: 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-16 04:33 UTC, piyush-harness commented
*[`platform-service/modules/audit-service/BUILD.bazel` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/41197#-NJO5wfd8Ay3sI6xAZp1:-NJOCPl5-hB0mHgMwdAn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76d8b69e5330640c72238f717b522669207a26ef/platform-service/modules/audit-service/BUILD.bazel#L14)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should be ["//platform-service/service:__subpackages__", "//audit-event-streaming/service:__subpackages__"]
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-16 04:35 UTC, nishantsaini20 submitted a review, later dismissed
As discussed UTs will be part of separate PR.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41197#-:-NJOCYOo4Ty3EAGcIALY:b-ckcuts)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-16 07:17 UTC, nishantsaini20 approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41197)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-16 11:49 UTC, reetika04 approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41197)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-19 05:10 UTC, diptiman-adak reviewed
Can we make use of the common files from dockerization folder for these two scripts?
I think maintaining these for independant services will be an overhead. What we can do here in the pipeline we can use "cp" to copy files from dockerization folder and make use of it.

2022-12-19 05:13 UTC, diptiman-adak commented on audit-event-streaming/release/release-branch.sh
> +#!/bin/bash
Better to parameterise these scripts. It will reduce maintenance overhead in future.

2022-12-19 05:14 UTC, diptiman-adak commented on audit-event-streaming/release/release_build.sh
> +#!/usr/bin/env bash
ditto

2022-12-19 06:30 UTC, diptiman-adak reviewed
> Reviewed 17 of 35 files at r1, 14 of 15 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41197)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-19 06:31 UTC, diptiman-adak commented
Had a discussion with @piyush-harness . I will create BT ticket to work on this common scripts and make sure independently deployable services can make use of it.

2022-12-19 06:45 UTC, diptiman-adak approved these changes

2022-12-19 06:47 UTC, diptiman-adak approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41197#-:-NJd7rTT0YhtrdndGuvV:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-12-19 08:51 UTC, merged