[fix]: [PIE-6784]: Fixing matrix in ci for complex objects and going with the expressionEvaluater route instead of string replace
harness/harness-core pull request #41204
Opened 2022-12-06 16:45 UTC by brijeshdhakar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-07 06:37 UTC, sahilhindwani-harness commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilFunctor.java
> +    for (Map.Entry<String, String> entry : combinations.entrySet()) {
Can we use the same util as we are using in normal StrategyFunctor? 
Maybe we can share some common code?

2022-12-07 06:38 UTC, sahilhindwani-harness commented
Add tests for the given scenerio in StrategyUtilsTest





<!-- Sent from Reviewable.io -->

2022-12-07 06:38 UTC, sahilhindwani-harness requested changes
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41204)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-08 07:55 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41204)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilFunctor.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/41204#-NIcJzbugFT2XCnNjCQP-r2-27:-NIkiusR51WuSj4dJqzp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/721b97337ea2217e91a05de0282c6697e65587f7/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtilFunctor.java#L27)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we use the same util as we are using in normal StrategyFunctor? 
Maybe we can share some common code?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-08 11:25 UTC, sahilhindwani-harness approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41204)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-08 11:30 UTC, prashantsharma04 approved these changes
> Reviewed 1 of 4 files at r1, 2 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41204)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-08 11:30 UTC, merged