[fix]: [CDS-44812]: perform Basic Validation For Remote Templates in …
harness/harness-core pull request #41292
Opened 2022-12-08 08:59 UTC by tchaurasiya

…get calls

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-08 11:35 UTC, utkarshchoubey-harness reviewed
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292)* status: 5 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-08 11:36 UTC, utkarshchoubey-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292#-:-NIlWLas1wJhFcxxS0Rp:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-08 14:39 UTC, yogesh-chauhan commented
Lets say the validation fails for an existing remote template, user will start seeing an error while trying to load the template, I think we should wait for the UI change where we show the Yaml in case of these errors




<!-- Sent from Reviewable.io -->

2022-12-09 04:52 UTC, tchaurasiya commented
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets say the validation fails for an existing remote template, user will start seeing an error while trying to load the template, I think we should wait for the UI change where we show the Yaml in case of these errors
</blockquote></details>

Make sense, But @yogesh-chauhan if lets say versionLabel(or any validated filed) is changed  on remote,
Will ui default yaml view point it out?




<!-- Sent from Reviewable.io -->

2022-12-09 06:14 UTC, adivishy1 submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292)* status: 5 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-09 12:40 UTC, yogesh-chauhan requested changes

2023-01-09 12:40 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java
> +            "Template version from remote template file [%s] does not match with template version in request [%s]. Template version field is only supposed to change through harness application",
Lets drop the "application" word. 
We should say
Each template version maps to a unique file on Git. Create a new version through harness or import a new version if the file is already created on Git

2023-01-09 12:40 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java
>    public void performImportFlowYamlValidations(String orgIdentifier, String projectIdentifier,
is this change needed now ?

2023-01-09 12:40 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java
> +import org.jetbrains.annotations.NotNull;
lets not use NotNull from jetbrains

2023-01-10 05:04 UTC, tchaurasiya commented
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 450 at r4](https://reviewable.io/reviews/harness/harness-core/41292#-NIkxZAxx4g2pdbHkyU9-r4-450:-NLP34H57sqKOD2OcwI7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9536c129bec1d330a1e7df3d74d54ea19a433cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L450)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets add private methods at the end for better readability

Generally its good to follow


class {

 .. all public methods

 .. all private methods

}



</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 05:04 UTC, tchaurasiya commented
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/41292#-NIkxZAxx4g2pdbHkyUC-r4-157:-NLP36Vf1s_KnFWXpf2f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9536c129bec1d330a1e7df3d74d54ea19a433cd/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L157)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this change needed now ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 05:04 UTC, tchaurasiya commented
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/41292#-NL6qjcHQrPgcbix-QVL-r4-29:-NLP37fS1Ftgao5_u5KB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9536c129bec1d330a1e7df3d74d54ea19a433cd/840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java#L29)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets not use NotNull from jetbrains
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 05:04 UTC, tchaurasiya reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292)* status: 6 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 460 at r4](https://reviewable.io/reviews/harness/harness-core/41292#-NIkxZAxx4g2pdbHkyU9-r4-460:-NLP35PI7ODIwfNyd3Rd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9536c129bec1d330a1e7df3d74d54ea19a433cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L460)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets drop the "application" word. 
We should say
Each template version maps to a unique file on Git. Create a new version through harness or import a new version if the file is already created on Git 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 12:13 UTC, yogesh-chauhan requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, 1 of 4 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1253 at r5](https://reviewable.io/reviews/harness/harness-core/41292#-NLQaC_F5oKAhcVwArOQ:-NLQ_iY6AllI7D7OGZiw:bb3r7u1) ([raw file](https://github.com/harness/harness-core/blob/a19fd1f133cc945c1f839ebd63537073b5cea02f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1253)):*
> ```Java
>       String templateVersionFromGit =
>           templateYamlField.getNode().getStringValue(YAMLFieldNameConstants.TEMPLATE_VERSION);
>       if (!(EmptyPredicate.isEmpty(versionLabel) && EmptyPredicate.isEmpty(templateVersionFromGit))
> ```

lets simplify for readability


<!-- Sent from Reviewable.io -->

2023-01-10 15:49 UTC, tchaurasiya commented
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1253 at r5](https://reviewable.io/reviews/harness/harness-core/41292#-NLQaC_F5oKAhcVwArOQ:-NLRMshRA5uAa4v5MqUG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a19fd1f133cc945c1f839ebd63537073b5cea02f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1253)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets simplify for readability
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 17:21 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-10 17:22 UTC, yogesh-chauhan approved these changes

2023-01-11 05:20 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 05:25 UTC, tchaurasiya commented
trigger messagecheck

2023-01-11 06:02 UTC, adivishy1 approved these changes
> Reviewed 1 of 4 files at r4, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41292)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-11 07:43 UTC, merged