[feat]: [CDS-47030]: All Canary Delete Manager Changes
harness/harness-core pull request #41429
Opened 2022-12-12 11:25 UTC by lovish1999

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-12 12:46 UTC, lovish1999 reviewed
AsgCanaryDeleteDataOutcome & AsgPrepareRollbackDataPassThroughData classes need some refactoring. Will do that.

2022-12-12 13:56 UTC, vitsafronovici approved these changes
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429)* status: 45 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-12 13:58 UTC, vitsafronovici requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429)* status: 45 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCommandTypeNG.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/41429#-NJ5cDGT-ch0j-oHRkSO:-NJ5cDGUCA0okbwcL_xh:b-pi9d9n) ([raw file](https://github.com/harness/harness-core/blob/8d015a76127ac229a718b5a5d614d42ed7962269/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCommandTypeNG.java#L10)):*
> ```Java
> package io.harness.delegate.task.aws.asg;
> 
> public enum AsgCommandTypeNG { ASG_CANARY_DEPLOY, ASG_CANARY_DELETE }
> ```

remove this


<!-- Sent from Reviewable.io -->

2022-12-12 18:01 UTC, yogesh-chauhan reviewed
> Reviewed 9 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429)* status: 36 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-14 06:43 UTC, arvind-choudhary-h commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/41429#-NJEMoUHDC8FUxnmIdKK:-NJEMoUHDC8FUxnmIdKL:b-h8302v) ([raw file](https://github.com/harness/harness-core/blob/ad8cd66cb394b17d87051427e81be66d86d2dc65/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java#L50)):*
> ```Java
>         StepSpecTypeConstants.ELASTIGROUP_ROLLBACK, StepSpecTypeConstants.ELASTIGROUP_SETUP,
>         StepSpecTypeConstants.TERRAGRUNT_PLAN, StepSpecTypeConstants.TERRAGRUNT_APPLY,
>         StepSpecTypeConstants.TERRAGRUNT_DESTROY, StepSpecTypeConstants.TERRAGRUNT_ROLLBACK);
> ```

Let's add in sequence -- StepSpecTypeConstants.ASG_CANARY_DELETE should be at end.


<!-- Sent from Reviewable.io -->

2022-12-14 06:46 UTC, arvind-choudhary-h commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCanaryDeployResult.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/41429#-NJENVZB8S1xWAtfi3D9:-NJENVZB8S1xWAtfi3DA:b-yhyd29) ([raw file](https://github.com/harness/harness-core/blob/ad8cd66cb394b17d87051427e81be66d86d2dc65/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCanaryDeployResult.java#L22)):*
> ```Java
> public class AsgCanaryDeployResult {
>   private String region;
>   //private List<AsgTask> asgTasks;
> ```

let's remove not required fields.


<!-- Sent from Reviewable.io -->

2022-12-14 06:46 UTC, arvind-choudhary-h commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCanaryDeployResult.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/41429#-NJENVZB8S1xWAtfi3D9:-NJENZFx2knuOtnL6VVQ:b-qghwja) ([raw file](https://github.com/harness/harness-core/blob/ad8cd66cb394b17d87051427e81be66d86d2dc65/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCanaryDeployResult.java#L22)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

let's remove not required fields.
</blockquote></details>

The commented line


<!-- Sent from Reviewable.io -->

2022-12-14 06:48 UTC, arvind-choudhary-h reviewed
> Reviewed 45 of 45 files at r1, 20 of 37 files at r2, 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429)* status: 40 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-14 09:04 UTC, vitsafronovici commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgInfraType.java
> +public enum AsgInfraType { ASG }
it is also used in ECS, but I don't understand it's purpose. why need enum with one value. why not to use InfrastructureKind.ASG instead

2022-12-14 16:43 UTC, arvind-choudhary-h commented
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 423 at r6](https://reviewable.io/reviews/harness/harness-core/41429#-NJGWB8z1ANLVtAdFa1s:-NJGWB8z1ANLVtAdFa1t:bg3ylsb) ([raw file](https://github.com/harness/harness-core/blob/07901e8fb46b0a3435748175932f7fcb24d8e333/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L423)):*
> ```Java
>   ELASTIGROUP_PRE_FETCH_TASK_NG(TaskGroup.ELASTIGROUP, "Elastigroup Pre Fetch Task"),
> 
>   AWS_ASG_CANARY_DEPLOY_TASK_NG(TaskGroup.ASG, "AWS Asg Canary Deploy"),
> ```

Please don't move Deploy task, it was already there. It's dangerous to change order of already existing tasks. Please revert. you can add your task at the end.


<!-- Sent from Reviewable.io -->

2022-12-14 16:44 UTC, arvind-choudhary-h commented
*[`400-rest/src/test/java/software/wings/beans/delegation/TaskTypeTest.java` line 419 at r6](https://reviewable.io/reviews/harness/harness-core/41429#-NJGWKlV8ainRC3TJp-_:-NJGWKlV8ainRC3TJp-a:bo4wvkf) ([raw file](https://github.com/harness/harness-core/blob/07901e8fb46b0a3435748175932f7fcb24d8e333/400-rest/src/test/java/software/wings/beans/delegation/TaskTypeTest.java#L419)):*
> ```Java
>     taskTypeOrdinalMapping.put(377, "ELASTIGROUP_SWAP_ROUTE_COMMAND_TASK_NG");
>     taskTypeOrdinalMapping.put(378, "ELASTIGROUP_ROLLBACK");
>     taskTypeOrdinalMapping.put(379, "ELASTIGROUP_PRE_FETCH_TASK_NG");
> ```

The existing task oridinals should be reverted back.


<!-- Sent from Reviewable.io -->

2022-12-14 16:44 UTC, arvind-choudhary-h reviewed
> Reviewed 13 of 15 files at r4, 6 of 6 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429)* status: 42 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-14 18:58 UTC, arvind-choudhary-h approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429#-:-NJH-3ca34thjPzs7hr3:bnfp4nl)* status: 42 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-15 10:33 UTC, lovish1999 commented
trigger ti3

2022-12-15 14:02 UTC, vitsafronovici approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429#-:-NJL4u6B3RYXNKupYdBB:bnfp4nl)* status: 12 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-15 14:14 UTC, arvind-choudhary-h approved these changes
> Reviewed 4 of 5 files at r8, 7 of 8 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41429)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-15 14:14 UTC, merged