feat: [CDS-2970]: Add S3 Support to Terraform-2
harness/harness-core pull request #41527
Opened 2022-12-13 12:09 UTC by akhilpandey1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-16 10:44 UTC, akhilpandey1 commented
trigger feature-build

2022-12-16 10:52 UTC, abhayganvir commented
trigger poccheckstyle

2022-12-19 15:13 UTC, tmacari-harness requested changes
> Reviewed 5 of 38 files at r1, 3 of 20 files at r2, 2 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 42 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationList.java` line 467 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJeneB052Sz8ADCerZ5:-NJeneB052Sz8ADCerZ6:b-98gmqb) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/390-db-migration/src/main/java/io/harness/migrations/MigrationList.java#L467)):*
> ```Java
>         .add(Pair.of(380, AddImmutableDelegateEnabledFieldToAccountCollection.class))
>         .add(Pair.of(381, AddRingDetailsToDelegateRing.class))
>         .add(Pair.of(384, InitTerraformProvisionersSourceType.class))
> ```

it should be 382
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 808 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJetlz44Fl_KIRh3V6U:-NJetlz44Fl_KIRh3V6V:b2qxitb) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L808)):*
> ```Java
>       terraformProvisionParameters
>           .sourceRepoSettingId(
>               !terraformSourceType.equals(TerraformSourceType.S3) ? gitSettingAttribute.getUuid() : null)
> ```

that would be always true 



_Code quote:_
```Java
!terraformSourceType.equals(TerraformSourceType.S3)
```
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 811 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJetscR1kxAF2qtmQNN:-NJetscR1kxAF2qtmQNO:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L811)):*
> ```Java
>           .sourceRepo(gitConfig)
>           .sourceRepoEncryptionDetails(
>               gitConfig != null ? secretManager.getEncryptionDetails(gitConfig, appId, null) : null)
> ```

same here


<!-- Sent from Reviewable.io -->

2022-12-19 15:19 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 42 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 800 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJexwq-9iveb3-fSL_0:-NJeu-Hs6u-6oQNfMBcQ:bqn27m2) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L800)):*
> ```Java
>                 featureFlagService.isEnabled(TERRAFORM_CONFIG_INSPECT_VERSION_SELECTOR, accountId));
> 
>     if (terraformSourceType.equals(TerraformSourceType.S3)) {
> ```

we have 2 if statements that check if (terraformSourceType.equals(TerraformSourceType.S3)), we could put all the logic from this if statement and the one above can be combined in to one


<!-- Sent from Reviewable.io -->

2022-12-19 21:29 UTC, akhilpandey1 commented
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationList.java` line 467 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJeneB052Sz8ADCerZ5:-NJgHNdY4kvYCnynEyye:bz1p285) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/390-db-migration/src/main/java/io/harness/migrations/MigrationList.java#L467)):*
> terraformSourceType.equals(TerraformSourceType.S3)
I'll check, I think develop is already using 382 and 383, would see if merging solves this


<!-- Sent from Reviewable.io -->

2022-12-19 21:31 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 808 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJetlz44Fl_KIRh3V6U:-NJgIBNy7b80Wie6rxSx:bx4i0vw) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L808)):*
> terraformSourceType.equals(TerraformSourceType.S3)
makes sense, removed


<!-- Sent from Reviewable.io -->

2022-12-19 21:34 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 811 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJetscR1kxAF2qtmQNN:-NJgIoaU3j00VzflHrt4:b-lmo7vq) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L811)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

makes sense, removed as well



_Code quote:_
```Java
 gitConfig != null ? secretManager.getEncrypt
```


<!-- Sent from Reviewable.io -->

2022-12-19 21:35 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 800 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJexwq-9iveb3-fSL_0:-NJgIt1kDerUvX0OsWdg:b-g92ajs) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L800)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we have 2 if statements that check if (terraformSourceType.equals(TerraformSourceType.S3)), we could put all the logic from this if statement and the one above can be combined in to one
</blockquote></details>

I see, combined both if and else's now


<!-- Sent from Reviewable.io -->

2022-12-20 08:29 UTC, akhilpandey1 commented
trigger feature-build

2022-12-20 09:12 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 800 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJexwq-9iveb3-fSL_0:-NJindcG9wOW8emGvj5g:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L800)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

I see, combined both if and else's now
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-12-21 06:50 UTC, akhilpandey1 commented
trigger feature-build

2022-12-21 07:09 UTC, akhilpandey1 commented
trigger feature-build

2022-12-21 10:53 UTC, akhilpandey1 commented
trigger feature-build

2022-12-21 11:37 UTC, tmacari-harness requested changes
> Reviewed 1 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 43 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java` line 128 at r10](https://reviewable.io/reviews/harness/harness-core/41527#-NJoSPAs8_GwjWXtOG2P:-NJoSPAtBZouNCgYjqdb:b-cq802) ([raw file](https://github.com/harness/harness-core/blob/37d9d2d5c4843e5491d88aaaeed88292c2e45d17/930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java#L128)):*
> ```Java
> 
>   @Override
>   public List<ExecutionCapability> fetchRequiredExecutionCapabilities(ExpressionEvaluator maskingEvaluator) {
> ```

we should add capabilities for new AWS fields


<!-- Sent from Reviewable.io -->

2022-12-21 13:25 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 43 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java` line 144 at r10](https://reviewable.io/reviews/harness/harness-core/41527#-NJoqv4Z10NHyGxfvfO7:-NJoqv4Z10NHyGxfvfO8:bj0eera) ([raw file](https://github.com/harness/harness-core/blob/37d9d2d5c4843e5491d88aaaeed88292c2e45d17/260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java#L144)):*
> ```Java
>   private static final String TASK_ID = "taskId";
> 
>   private GitConfig gitConfig;
> ```

lets add a test for run method with s3 details


<!-- Sent from Reviewable.io -->

2022-12-21 13:31 UTC, vlica-harness commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  AWS_ASG_CANARY_DELETE_TASK_NG(TaskGroup.ASG, "AWS Asg Canary Delete"),
I believe you need to put your element just at the end, and not change the order or other elements

2022-12-21 13:56 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java` line 128 at r10](https://reviewable.io/reviews/harness/harness-core/41527#-NJoSPAs8_GwjWXtOG2P:-NJoyALl0y-YrFCyWvvb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/37d9d2d5c4843e5491d88aaaeed88292c2e45d17/930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java#L128)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we should add capabilities for new AWS fields
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-21 14:09 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 43 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 2380 at r10](https://reviewable.io/reviews/harness/harness-core/41527#-NJp-xbp7NDfHUFaeOdJ:-NJp-xbp7NDfHUFaeOdK:bsg07a2) ([raw file](https://github.com/harness/harness-core/blob/37d9d2d5c4843e5491d88aaaeed88292c2e45d17/260-delegate/src/test/resources/kryo-registrations.txt#L2380)):*
> ```help
> 573581:io.harness.delegate.task.aws.asg.AutoScalingGroupContainer
> 573582:io.harness.delegate.task.aws.asg.AutoScalingGroupInstance
> 573583:software.wings.api.terraform.TfVarS3Source
> ```

looks like a merge issue


<!-- Sent from Reviewable.io -->

2022-12-21 16:02 UTC, akhilpandey1 commented
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 2380 at r10](https://reviewable.io/reviews/harness/harness-core/41527#-NJp-xbp7NDfHUFaeOdJ:-NJpPuwgAjL0PcCKvW8a:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/37d9d2d5c4843e5491d88aaaeed88292c2e45d17/260-delegate/src/test/resources/kryo-registrations.txt#L2380)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

looks like a merge issue
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-21 16:02 UTC, akhilpandey1 commented
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationList.java` line 467 at r3](https://reviewable.io/reviews/harness/harness-core/41527#-NJeneB052Sz8ADCerZ5:-NJpPySn5oBYFubOwTDs:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4a9869495290918fc23cff40a34e2df46c266d90/390-db-migration/src/main/java/io/harness/migrations/MigrationList.java#L467)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

> terraformSourceType.equals(TerraformSourceType.S3)
I'll check, I think develop is already using 382 and 383, would see if merging solves this
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-21 16:02 UTC, akhilpandey1 commented
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 433 at r10](https://reviewable.io/reviews/harness/harness-core/41527#-NJANw-WYj0B1ulnhKmo-r10-433:-NJpQ3Lc8oH6qfb3kQvN:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/37d9d2d5c4843e5491d88aaaeed88292c2e45d17/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L433)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

I believe you need to put your element just at the end, and not change the order or other elements
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-21 16:19 UTC, tmacari-harness requested changes
> Reviewed 1 of 8 files at r5, 1 of 7 files at r8, 1 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 43 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 783 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpT93J6SenhRA9I9_2:-NJpT93J6SenhRA9I9_3:bxn4m73) ([raw file](https://github.com/harness/harness-core/blob/56b38edcfc2db28268d56f81ce834577cfd86d36/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L783)):*
> ```Java
>                     .parameters(new Object[] {
>                         TerraformProvisionParameters.builder()
>                             .scriptPath(terraformDirectory)
> ```

Is that correct to remove it?


<!-- Sent from Reviewable.io -->

2022-12-21 18:02 UTC, tmacari-harness requested changes
> Reviewed 1 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 43 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1084 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpfqcG3H4jhcpKcr7_:-NJpfqcG3H4jhcpKcr7a:b-iexuvl) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1084)):*
> ```Java
>   }
> 
>   // ToDo:   Unit Test - AKHIL_PANDEY
> ```

Unit test should be added and comment removed
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1087 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpg7dL4UVyjuGU83kM:-NJpg7dL4UVyjuGU83kN:b-4xoxh8) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1087)):*
> ```Java
>   protected String getTaskType(TerraformProvisionParameters parameters, ExecutionContext context) {
>     if (featureFlagService.isEnabled(FeatureName.CDS_TERRAFORM_S3_SUPPORT, context.getAccountId())) {
>       if (parameters.getSourceType().equals(TerraformSourceType.S3) || tfVarS3FileConfig != null) {
> ```

what if FF is disabled but we have s3 resources?
It should return TERRAFORM_PROVISION_TASK_V2 if we need new delegate  version to execute the task. That would be the case when at least one of config files, var files, backend config are on S3, regardless of FF
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1094 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpm3cxDbVKAyHsl7xc:-NJpm3cxDbVKAyHsl7xd:bs2vz0) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1094)):*
> ```Java
>   }
> 
>   private ExecutionResponse executeInternalRegular(ExecutionContext context, String activityId) {
> ```

We should do a check here, if FF is disabled and there are S3 config files or var files workflow should be failed with a meaningful error message. 
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1095 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJphIDG3HtciBlC7zy8:-NJphIDG3HtciBlC7zy9:btlo438) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1095)):*
> ```Java
> 
>   private ExecutionResponse executeInternalRegular(ExecutionContext context, String activityId) {
>     //    Initialize variables for GIT and S3 source respectively
> ```

we don't need those comments
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1101 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpiyCz3ssajl0y4-hJ:-NJpiyCz3ssajl0y4-hK:bk49prf) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1101)):*
> ```Java
>     String path = null;
>     //    S3 ===>
>     AwsConfig awsS3SourceBucketConfig = null;
> ```

Why do we define it here?
Looks like we simply assign it to task parameters as null. 


<!-- Sent from Reviewable.io -->

2022-12-21 19:06 UTC, tmacari-harness requested changes
> Reviewed 1 of 38 files at r1, 1 of 20 files at r2, 1 of 6 files at r3, 1 of 11 files at r9, 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 43 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 769 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpyt7C9Ba-2KXrlx5I:-NJpVAmzCWr0uGpnus6A:b-1p7zsk) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L769)):*
> ```Java
>     //    Initialize Git variables
> 
>     GitConfig gitConfig = null;
> ```

No need to define them here, we ca do we don't need to initialize it here if we need it only in Git case. 
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 771 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpz5J48dFfAPFHiQv7:-NJpz5J48dFfAPFHiQv8:bdrfhwp) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L771)):*
> ```Java
>     GitConfig gitConfig = null;
> 
>     AwsConfig awsS3SourceBucketConfig = null;
> ```

same here, we need it only for s3 case
___
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 985 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpzZgSE1A5cnEoeO_O:-NJpzZgSE1A5cnEoeO_P:bkq7eth) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L985)):*
> ```Java
>   @Owner(developers = BOJANA)
>   @Category(UnitTests.class)
>   public void getTerraformVariablesBranchCommitIdTest() {
> ```

We should add tests for the logic we added in InfrastructureProvisionerServiceImpl
___
*[`400-rest/src/test/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandlerTest.java` line 225 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq-9JH6oH9xLkEq9Wp:-NJq-9JH6oH9xLkEq9Wq:bcl5rgr) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandlerTest.java#L225)):*
> ```Java
>         NameValuePair.builder().name("access_key").valueType(ServiceVariableType.TEXT.toString()).build(),
>         NameValuePair.builder().name("secret_key").valueType(ServiceVariableType.ENCRYPTED_TEXT.toString()).build());
>     TerraformInfrastructureProvisioner provisioner = TerraformInfrastructureProvisioner.builder()
> ```

That could be split into 2 tests.
___
*[`400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java` line 200 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq03VA-QX2aoPyDojO:-NJq03VA-QX2aoPyDojP:b-t7ah2) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java#L200)):*
> ```Java
>   @InjectMocks private TerraformProvisionState destroyProvisionState = new DestroyTerraformProvisionState("tf");
> 
>   private final Answer<String> answer = invocation -> invocation.getArgument(0, String.class) + "-rendered";
> ```

We should add tests for execute methods with execute regular and inherited.
Also for handle async methods.
___
*[`400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java` line 1904 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq-VxAEPZ8IZO3Dx2e:-NJq-VxBBBb6rsrP7WdN:bmx6vzz) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java#L1904)):*
> ```Java
>                                                          .appId(APP_ID)
>                                                          .repoName(REPO_NAME)
>                                                          .terraformSourceType(TerraformSourceType.GIT)
> ```

why do we set terraformSourceType twice in the places below?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java` line 101 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq3HNs1AHza6e3TCFs:-NJq3HNs1AHza6e3TCFt:bpasaop) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java#L101)):*
> ```Java
>               .executionStatus(ExecutionStatus.FAILED)
>               .errorMessage(
>                   TerraformTaskUtils.getGitExceptionMessageIfExists(ExceptionMessageSanitizer.sanitizeException(e)))
> ```

no need to call this in s3 case, we can simply do: ExceptionUtils.getMessage(ExceptionMessageSanitizer.sanitizeException(e)); 



_Code quote:_
```Java
 TerraformTaskUtils.getGitExceptionMessageIfExists
```


<!-- Sent from Reviewable.io -->

2022-12-22 05:41 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java` line 101 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq3HNs1AHza6e3TCFs:-NJsLWFC0sWtfLoezrMh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java#L101)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

no need to call this in s3 case, we can simply do: ExceptionUtils.getMessage(ExceptionMessageSanitizer.sanitizeException(e)); 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-22 05:43 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 769 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpyt7C9Ba-2KXrlx5I:-NJsLqn63Q76StZ8M42B:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L769)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

No need to define them here, we ca do we don't need to initialize it here if we need it only in Git case. 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-22 05:43 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 771 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpz5J48dFfAPFHiQv7:-NJsLtsmE_n8Gj93H5C-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L771)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here, we need it only for s3 case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-22 05:46 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 783 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpT93J6SenhRA9I9_2:-NJsMU821y9jogBRn4pB:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/56b38edcfc2db28268d56f81ce834577cfd86d36/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L783)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Is that correct to remove it?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2022-12-22 05:47 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1095 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJphIDG3HtciBlC7zy8:-NJsMq_i4fTSJOglgsq7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1095)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we don't need those comments
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-22 05:53 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1101 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpiyCz3ssajl0y4-hJ:-NJsO8VU23I_jlMXxQPN:bdek3t1) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1101)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we define it here?
Looks like we simply assign it to task parameters as null. 
</blockquote></details>

done, removed


<!-- Sent from Reviewable.io -->

2022-12-22 05:56 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java` line 1904 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq-VxAEPZ8IZO3Dx2e:-NJsOqu9DsUqKCaOtJ-A:b-1i3lbd) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java#L1904)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why do we set terraformSourceType twice in the places below?
</blockquote></details>

refactoring typo, fixed


<!-- Sent from Reviewable.io -->

2022-12-22 09:21 UTC, tmacari-harness requested changes
> Reviewed 10 of 38 files at r1, 1 of 7 files at r7, 1 of 11 files at r9, 1 of 3 files at r10, 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 43 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformInputVariablesObtainTask.java` line 110 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJsuWJ_4lEnwvbMiiZy:-NJsuWJ_4lEnwvbMiiZz:b-cott60) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformInputVariablesObtainTask.java#L110)):*
> ```Java
>               .terraformExecutionData(TerraformExecutionData.builder()
>                                           .executionStatus(ExecutionStatus.FAILED)
>                                           .errorMessage(TerraformTaskUtils.getGitExceptionMessageIfExists(ex))
> ```

Same thing here, there will be no git exception
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 238 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJswgAR8FzckzHr_6ew:-NJswgAR8FzckzHr_6ex:b-yul2t8) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L238)):*
> ```Java
>     if (parameters.getSourceType() != null && parameters.getSourceType().equals(TerraformSourceType.S3)) {
>       try {
>         encryptionService.decrypt(
> ```

We should ad some UI logs S3 URI for ex. as we do in git scenario
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 242 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJsvw6w0WFzXL_zj7cE:-NJsvw6w0WFzXL_zj7cF:b-pp8sxs) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L242)):*
> ```Java
>         awsS3HelperServiceDelegate.downloadS3Directory(
>             parameters.getAwsS3SourceBucketConfig(), parameters.getS3URI(), new File(workingDir));
>       } catch (InterruptedException e) {
> ```

Why do we catch only InterruptedException we should catch all exceptions. ref how it is done for git.
___
*[`930-delegate-tasks/src/main/java/software/wings/utils/S3Utils.java` line 15 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJt3toT5wy6VwvMf7mK:-NJt3toT5wy6VwvMf7mL:b-50zaga) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/utils/S3Utils.java#L15)):*
> ```Java
> import java.nio.file.Paths;
> 
> public class S3Utils {
> ```

Please add @OwnedBy(CDP)
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 435 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJt6FpACqZXKFPFmy8J:-NJt6FpACqZXKFPFmy8K:b-gsjlg2) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L435)):*
> ```Java
>   TAS_SWAP_ROLLBACK(TaskGroup.TAS, "Tas Swap Rollback task"),
>   TAS_DATA_FETCH(TaskGroup.TAS, "Tas Data Fetch task"),
>   TERRAFORM_PROVISION_TASK_V2(TaskGroup.TERRAFORM, "Terraform CDS S3 Support");
> ```

It's better to give it a display name like: "Terraform provision task V2"
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 518 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJt7-S_DnijOAACReVS:-NJt7-S_DnijOAACReVT:b-h9jpow) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L518)):*
> ```Java
>       "For supporting filtering of infras and gitOps clusters based on tags", HarnessTeam.CDC),
>   CDS_TERRAFORM_S3_SUPPORT(
>       "Enable support for S3 bucket and URIs for Terraform Source, tfVars and Backend Config", HarnessTeam.CDP),
> ```

maybe: "Enable support for AWS S3 as a source for terraform config files, var files and backend config"


<!-- Sent from Reviewable.io -->

2022-12-22 15:35 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformInputVariablesObtainTask.java` line 110 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJsuWJ_4lEnwvbMiiZy:-NJuTO_T-HHxaOKuRSRH:btwgzme) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformInputVariablesObtainTask.java#L110)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Same thing here, there will be no git exception
</blockquote></details>

Done.
Changed to ExceptionUtils.getMessage(ExceptionMessageSanitizer.sanitizeException(e));


<!-- Sent from Reviewable.io -->

2022-12-22 15:38 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 238 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJswgAR8FzckzHr_6ew:-NJuU8Nd2V2M32XiN1TA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L238)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We should ad some UI logs S3 URI for ex. as we do in git scenario
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-22 15:43 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 242 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJsvw6w0WFzXL_zj7cE:-NJuV3C2B0AmDgJQ0Q6W:bxbfbye) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L242)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we catch only InterruptedException we should catch all exceptions. ref how it is done for git.
</blockquote></details>

I think the PMD check kept asking us to catch the interrupted exception that is thrown by the downloadS3Directory() function, have changed it back to general exception, will see if PMD passes


<!-- Sent from Reviewable.io -->

2022-12-22 15:44 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/utils/S3Utils.java` line 15 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJt3toT5wy6VwvMf7mK:-NJuVO2lBxRiKaQXLSXm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/utils/S3Utils.java#L15)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Please add @OwnedBy(CDP)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-22 15:45 UTC, akhilpandey1 commented
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 435 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJt6FpACqZXKFPFmy8J:-NJuVRir0E1p8WVS56Cq:b-l6mkuu) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L435)):*
> Terraform provision task V2
I believe that information is already present in task name, the description for the task elaborates the new features/support that were put behind the task


<!-- Sent from Reviewable.io -->

2022-12-22 15:46 UTC, akhilpandey1 commented
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 518 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJt7-S_DnijOAACReVS:-NJuVnmB0DVy9LOccQ_V:bxtcnnx) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L518)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

maybe: "Enable support for AWS S3 as a source for terraform config files, var files and backend config"
</blockquote></details>

I see, done


<!-- Sent from Reviewable.io -->

2022-12-22 15:46 UTC, akhilpandey1 commented
*[`260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java` line 144 at r10](https://reviewable.io/reviews/harness/harness-core/41527#-NJoqv4Z10NHyGxfvfO7:-NJuVsbQ004GvHu7klQs:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/37d9d2d5c4843e5491d88aaaeed88292c2e45d17/260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java#L144)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

lets add a test for run method with s3 details
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-22 16:01 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1094 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpm3cxDbVKAyHsl7xc:-NJuZG8iEjygDCR9M63Y:b4yux0) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1094)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We should do a check here, if FF is disabled and there are S3 config files or var files workflow should be failed with a meaningful error message. 
</blockquote></details>

As discussed currently, we check it at last when all parameters are available and throw the correct error at line:1396


<!-- Sent from Reviewable.io -->

2022-12-22 16:06 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1084 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpfqcG3H4jhcpKcr7_:-NJu_PeCAxpFtFVRg6_w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1084)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Unit test should be added and comment removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-23 07:24 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 985 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpzZgSE1A5cnEoeO_O:-NJxr_NX3rf5ZWzNbms6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L985)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We should add tests for the logic we added in InfrastructureProvisionerServiceImpl
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-23 08:16 UTC, tmacari-harness requested changes
> Reviewed 4 of 16 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 47 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java` line 703 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJxvXgw436T85m2Ogce:-NJxvXgw436T85m2Ogcf:b-nvdck7) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java#L703)):*
> ```Java
>     Mockito.verify(awsS3HelperServiceDelegate, atLeastOnce()).downloadS3Directory(any(), any(), any());
>   }
>   @Test
> ```

please add empty line 
___
*[`260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java` line 726 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJxvkHqB73Q3g-UsDgW:-NJxvkHqB73Q3g-UsDgX:b-es6icb) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java#L726)):*
> ```Java
>     terraformProvisionTaskSpy.fetchS3Files(terraformProvisionParameters, dir, logCallback, BACKEND_CONFIG_KEY);
> 
>     Mockito.verify(mockEncryptionService, atLeastOnce())
> ```

This test may not be su useful as we want, if we're verifying interactions let's put the exact number.
Let's say we have config files, var files, and backend config on s3, we should call the method 3 times but the test will pass even if we call it only once.
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 986 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJy2FN13Qj0nEUvyWSW:-NJy2FN13Qj0nEUvyWSX:b-f95ff8) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L986)):*
> ```Java
>                     : null)
>             .scriptPath(path)
>             .s3URI(terraformProvisioner.getSourceType().equals(TerraformSourceType.S3) ? terraformProvisioner.getS3URI()
> ```

looks like we set it here and in setAWSS3SourceConfigSourceIfPresent
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1022 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJy1YTQEERHeZHA27-_:-NJy1YTQEERHeZHA27-a:bzhqf1o) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1022)):*
> ```Java
>       setAWSAuthParamsIfPresent(context, terraformProvisionParametersBuilder);
>     }
>     if (featureFlagService.isEnabled(CDS_TERRAFORM_S3_SUPPORT, context.getAccountId())
> ```

looks like if FF is disabled and we're in executeInherited with s3 var files, s3 backend config and s3 configuration files we will we will sett all details beside AWS config for config files


<!-- Sent from Reviewable.io -->

2022-12-23 09:48 UTC, akhilpandey1 commented
*[`260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java` line 703 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJxvXgw436T85m2Ogce:-NJyN_jaC1nky8GzX9jv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java#L703)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-23 09:49 UTC, akhilpandey1 commented
*[`260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java` line 726 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJxvkHqB73Q3g-UsDgW:-NJyNiso6i43q0x09ZAt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java#L726)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

This test may not be su useful as we want, if we're verifying interactions let's put the exact number.
Let's say we have config files, var files, and backend config on s3, we should call the method 3 times but the test will pass even if we call it only once.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-23 09:49 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 986 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJy2FN13Qj0nEUvyWSW:-NJyNnl_-mW7IfQXrmjX:bdek3t1) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L986)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

looks like we set it here and in setAWSS3SourceConfigSourceIfPresent
</blockquote></details>

done, removed


<!-- Sent from Reviewable.io -->

2022-12-23 10:52 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1087 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpg7dL4UVyjuGU83kM:-NJyavrh3lnFIO8TRzeU:b-v4bdl8) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1087)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

what if FF is disabled but we have s3 resources?
It should return TERRAFORM_PROVISION_TASK_V2 if we need new delegate  version to execute the task. That would be the case when at least one of config files, var files, backend config are on S3, regardless of FF

</blockquote></details>

removed the FF check from here now, by default if the execution comes to this point without being interrupted and any of the s3 configs are present (source, tfvars, be config) we'll return V2 task and proceed with execution


<!-- Sent from Reviewable.io -->

2022-12-23 11:15 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1022 at r13](https://reviewable.io/reviews/harness/harness-core/41527#-NJy1YTQEERHeZHA27-_:-NJygFgZ2HTxbEGMRpi0:bnde96n) ([raw file](https://github.com/harness/harness-core/blob/8135b2a223af0373ba4ac8fb6986aa4ecb09f6af/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1022)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

looks like if FF is disabled and we're in executeInherited with s3 var files, s3 backend config and s3 configuration files we will we will sett all details beside AWS config for config files
</blockquote></details>

We now throw exception here and fail WF if other fields are set and FF is disabled


<!-- Sent from Reviewable.io -->

2022-12-23 17:42 UTC, tmacari-harness reviewed
> Reviewed 6 of 16 files at r12, 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 238 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJswgAR8FzckzHr_6ew:-NJyJeg83bBQy2TFkrV_:b-c8uzvb) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L238)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

if we log bucket the we should also log the key, OR we can log only the URI


<!-- Sent from Reviewable.io -->

2022-12-26 19:44 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 238 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJswgAR8FzckzHr_6ew:-NKExpOQ8Hddyo5ASwLz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L238)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

if we log bucket the we should also log the key, OR we can log only the URI
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-27 11:58 UTC, tmacari-harness requested changes
> Reviewed 1 of 4 files at r14, 2 of 9 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1087 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpg7dL4UVyjuGU83kM:-NKIRVg32AnFMqSzTw2-:byncyle) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1087)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

removed the FF check from here now, by default if the execution comes to this point without being interrupted and any of the s3 configs are present (source, tfvars, be config) we'll return V2 task and proceed with execution
</blockquote></details>

Then we don't need the context as parameter anymore


<!-- Sent from Reviewable.io -->

2022-12-27 13:05 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1394 at r17](https://reviewable.io/reviews/harness/harness-core/41527#-NKIfgu_Er6zxs6zBx_U:-NKIfgu_Er6zxs6zBx_V:b-d406y7) ([raw file](https://github.com/harness/harness-core/blob/4a5076e262c06049582357ab662d91a9317eb64c/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1394)):*
> ```Java
>         && terraformProvisioner.getSourceType().equals(TerraformSourceType.S3)) {
>       setAWSS3SourceConfigSourceIfPresent(terraformProvisioner, context, terraformProvisionParametersBuilder);
>     } else if (!featureFlagService.isEnabled(FeatureName.CDS_TERRAFORM_S3_SUPPORT, context.getAccountId())) {
> ```

In the "if" above we check if FF is enabled, it doesn't make sense to check if it is disabled in "else if" statement.


<!-- Sent from Reviewable.io -->

2022-12-27 13:14 UTC, tmacari-harness requested changes
> Reviewed 1 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1118 at r17](https://reviewable.io/reviews/harness/harness-core/41527#-NKIi0hY7B_JZxf5mEGv:-NKIi0hY7B_JZxf5mEGw:bb6y8q5) ([raw file](https://github.com/harness/harness-core/blob/4a5076e262c06049582357ab662d91a9317eb64c/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1118)):*
> ```Java
>     doReturn(response).when(delegateService).executeTask(any(DelegateTask.class));
> 
>     String s3SourceURI = "s3://iis-website-quickstart/terraform-manifest/variablesAndNullResources/";
> ```

this string is not used anywhere


<!-- Sent from Reviewable.io -->

2022-12-27 13:24 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1056 at r17](https://reviewable.io/reviews/harness/harness-core/41527#-NKIkL9yBIiQC1JX0zH5:-NKIkL9yBIiQC1JX0zH6:bd3675i) ([raw file](https://github.com/harness/harness-core/blob/4a5076e262c06049582357ab662d91a9317eb64c/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1056)):*
> ```Java
>   @Category(UnitTests.class)
>   public void getS3TerraformVariablesTest() throws Exception {
>     String awsConfigId = "SETTING_ID";
> ```

unused string


<!-- Sent from Reviewable.io -->

2022-12-27 13:48 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1087 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJpg7dL4UVyjuGU83kM:-NKIpufj5l2zMHAW0wcv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1087)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Then we don't need the context as parameter anymore
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-27 15:29 UTC, akhilpandey1 commented
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1394 at r17](https://reviewable.io/reviews/harness/harness-core/41527#-NKIfgu_Er6zxs6zBx_U:-NKJBzcD30UeG2MadBsP:b-u8i1k6) ([raw file](https://github.com/harness/harness-core/blob/4a5076e262c06049582357ab662d91a9317eb64c/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1394)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

In the "if" above we check if FF is enabled, it doesn't make sense to check if it is disabled in "else if" statement.
</blockquote></details>

refactored, fixed


<!-- Sent from Reviewable.io -->

2022-12-27 15:32 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1056 at r17](https://reviewable.io/reviews/harness/harness-core/41527#-NKIkL9yBIiQC1JX0zH5:-NKJCg9Y16-QNoM76b7s:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/4a5076e262c06049582357ab662d91a9317eb64c/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1056)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

unused string
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2022-12-27 15:32 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1118 at r17](https://reviewable.io/reviews/harness/harness-core/41527#-NKIi0hY7B_JZxf5mEGv:-NKJChWl1Mpt9a3uEw19:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/4a5076e262c06049582357ab662d91a9317eb64c/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1118)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

this string is not used anywhere
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2022-12-27 15:35 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandlerTest.java` line 225 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq-9JH6oH9xLkEq9Wp:-NKJDFdk1GH0m9VIoSJv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/service/impl/yaml/handler/infraprovisioner/TerraformInfrastructureProvisionerYamlHandlerTest.java#L225)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

That could be split into 2 tests.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-27 15:35 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java` line 200 at r11](https://reviewable.io/reviews/harness/harness-core/41527#-NJq03VA-QX2aoPyDojO:-NKJDJ985qugc3o2txOB:b9env1s) ([raw file](https://github.com/harness/harness-core/blob/c502f688db3aec2309d2f0e108f4b661f46b63fe/400-rest/src/test/java/software/wings/sm/states/provision/TerraformProvisionStateTest.java#L200)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We should add tests for execute methods with execute regular and inherited.
Also for handle async methods.
</blockquote></details>

added for execute regular, inherited - invalid, handle async, 
Will add for execute inherited valid


<!-- Sent from Reviewable.io -->

2022-12-28 13:52 UTC, tmacari-harness requested changes
> Reviewed 2 of 11 files at r15, 10 of 19 files at r18, 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1073 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKNzpSN8LkNNBqtwHaC:-NKNzpSODcVuZTubpC0Z:b-pfencp) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1073)):*
> ```Java
>             .build();
> 
>     doReturn(null).when(mockEncryptionService).decrypt(awsConfig, awsConfigEncryptionDetails, false);
> ```

we don't need those mocks here
___
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1081 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKNzuU6E_k_LqULldE5:-NKNzuU6E_k_LqULldE6:b-cb0j8u) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1081)):*
> ```Java
>         APP_ID, null, ".", ACCOUNT_ID, null, null, null, TerraformSourceType.S3, s3SourceURI, SETTING_ID);
> 
>     assertThat(variables).isEqualTo(expectedVariables);
> ```

We are only asserting on result we mocked, we should do more meaningful assertions
___
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1113 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKO-GZm0ZEmQ7VB8wPe:-NKO-GZm0ZEmQ7VB8wPf:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1113)):*
> ```Java
>     TerraformExecutionData response = TerraformExecutionData.builder().executionStatus(ExecutionStatus.SUCCESS).build();
> 
>     doReturn(null).when(mockEncryptionService).decrypt(awsConfig, awsConfigEncryptionDetails, false);
> ```

same here


<!-- Sent from Reviewable.io -->

2022-12-28 13:54 UTC, tmacari-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 247 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKO-png86s5X7pRHUts:-NKO-png86s5X7pRHUtt:bwnjf4s) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L247)):*
> ```Java
>             parameters.getConfigFilesAwsSourceConfig(), parameters.getConfigFilesS3URI(), new File(workingDir));
>         saveExecutionLog("\nNormalized Path: " + workingDir, CommandExecutionStatus.RUNNING, INFO, logCallback);
>         Exception sanitizedException;
> ```

it is unused


<!-- Sent from Reviewable.io -->

2022-12-28 14:26 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1081 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKNzuU6E_k_LqULldE5:-NKO5P1Q2b8d32e8XHM5:b97sm5b) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1081)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We are only asserting on result we mocked, we should do more meaningful assertions
</blockquote></details>

asserting the behaviour changes with respect to S3 now


<!-- Sent from Reviewable.io -->

2022-12-28 14:26 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1073 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKNzpSN8LkNNBqtwHaC:-NKO5Kzx8VphWfdV8M8B:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1073)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we don't need those mocks here
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2022-12-28 14:26 UTC, akhilpandey1 commented
*[`400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java` line 1113 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKO-GZm0ZEmQ7VB8wPe:-NKO7CyH1hZx0xvytc-5:blry15z) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/400-rest/src/test/java/software/wings/service/impl/InfrastructureProvisionerServiceImplTest.java#L1113)):*
> removed, asserting the behaviour changes with respect to S3 now


<!-- Sent from Reviewable.io -->

2022-12-28 15:28 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 2 of 19 files at r18, 6 of 7 files at r20, 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 48 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-28 15:49 UTC, akhilpandey1 commented
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 247 at r19](https://reviewable.io/reviews/harness/harness-core/41527#-NKO-png86s5X7pRHUts:-NKOQEa-CtIvsZOyEWOo:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/82b3522b74cfa08bbe8f13607b45f67b58cdf71b/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L247)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

it is unused
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2022-12-29 06:26 UTC, arpit3107 approved these changes
new taskTypes are behind FF since they want to enable this feature for one customer only. Later on they will enable for others based on feedback

> Reviewed 14 of 38 files at r1, 2 of 20 files at r2, 1 of 6 files at r3, 1 of 8 files at r5, 1 of 7 files at r7, 2 of 7 files at r8, 1 of 3 files at r10, 5 of 16 files at r12, 2 of 11 files at r15, 9 of 19 files at r18, 1 of 3 files at r19, 5 of 7 files at r20, 3 of 3 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527#-:-NKRYmD-C-sVGtyDnvLv:bhpzn5p)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-29 07:36 UTC, tmacari-harness approved these changes
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41527)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-29 07:49 UTC, merged