[feat]: [PL-30095]: Update, Delete & Get APIs for StreamingDestinations
harness/harness-core pull request #41542
Opened 2022-12-13 20:23 UTC by kapil-harness

## Describe your changes
Update, Delete & Get APIs for StreamingDestinations

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-14 05:35 UTC, mankrit-singh approved these changes
> Reviewed 4 of 9 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: 11 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-14 14:21 UTC, nishantsaini20 requested changes
> Reviewed 3 of 9 files at r1, 4 of 7 files at r2, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFpoYy4bHM6wSttcDp:-NJFpoYy4bHM6wSttcDq:b-xcc16p) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L34)):*
> ```YAML
>     get:
>       summary: List Streaming Destinations
>       operationId: get-streaming-destinations-list
> ```

This was already plural indicating more than one streaming destination expected in response. No need to append "-list"
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFqCGCEEy1ZQtTl-QS:-NJFqCGCEEy1ZQtTl-QT:b7dpnk1) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L57)):*
> ```YAML
>     put:
>       summary: Update a Streaming Destination
>       operationId: update-streaming-destinations
> ```

We will not be supporting multiple streaming destination update in a single call. It should be update-streaming-destination
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFqVaW8nYgLI-jG4Eq:-NJFqVaW8nYgLI-jG4Er:b-mvs081) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L72)):*
> ```YAML
>     delete:
>       summary: Delete a Streaming Destination
>       operationId: Delete-streaming-destinations
> ```

Should be delete-disabled-streaming-destination
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFqfwJ3bfj2NMm8LrP:-NJFqfwJ3bfj2NMm8LrQ:b-bd35sk) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L86)):*
> ```YAML
>     get:
>       summary: Get a Streaming Destination
>       operationId: get-streaming-destinations
> ```

response will be just one streaming destination, so it should be get-streaming-destination
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 245 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFrFrP2VRLwJ9WcH5G:-NJFrFrP2VRLwJ9WcH5H:b-fv9ias) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L245)):*
> ```YAML
>         type: string
>       description: Status of the Streaming Destination
>     StreamingDestinationIdentifier:
> ```

StreamingDestinationParam
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 251 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFrKPv5Rppa__BtA_I:-NJFrKPw616AxWEssXfj:bjqi7y6) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L251)):*
> ```YAML
>       schema:
>         type: string
>       description: Unique identifer of a StreamingDestination entity
> ```

Streaming Destination identifier
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFtCqs9TFPKmb1sUKQ:-NJFtCqs9TFPKmb1sUKR:b-tgnc1a) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L62)):*
> ```Java
>     } catch (DuplicateKeyException exception) {
>       String message = String.format(
>           "StreamingDestination: with identifier [%s] already exists.", streamingDestinationDTO.getSlug());
> ```

This error message will shown to user on UI and API response. Keep it as it was earlier.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFunnC1Pkk-esCQ3lg:-NJFunnC1Pkk-esCQ3lh:b-a9arxi) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L79)):*
> ```Java
>   public StreamingDestination getStreamingDestination(String accountIdentifier, String identifier) {
>     Optional<StreamingDestination> optionalStreamingDestination = streamingDestinationRepository.findOneByCriteria(
>         getCriteriaForStreamingDestination(accountIdentifier, identifier));
> ```

There is no complex logic to create criteria. We can simply define findStreamingDestinationByAccountIdentifierAndIdentifier(... , ...) method in 
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFtPjP0CxH6bONt1Ve:-NJFtPjQ8XPcdUID8PzU:b-f3ob20) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L81)):*
> ```Java
>         getCriteriaForStreamingDestination(accountIdentifier, identifier));
>     if (optionalStreamingDestination.isEmpty()) {
>       log.error(String.format("StreamingDestination: not found with identifier [%s]", identifier));
> ```

Error message: Streaming Destination with identifier [%s] not found.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFt9J_4zqVSRd5WDT4:-NJFt9J_4zqVSRd5WDT5:b-wg2bxb) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L82)):*
> ```Java
>     if (optionalStreamingDestination.isEmpty()) {
>       log.error(String.format("StreamingDestination: not found with identifier [%s]", identifier));
>       throw NoResultFoundException.newBuilder()
> ```

throw NotFoundException
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFtwtC79Ii1Cph39uh:-NJFtwtC79Ii1Cph39ui:b-ib51cn) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L98)):*
> ```Java
>     if (streamingDestination.getStatus().equals(StatusEnum.ACTIVE)) {
>       log.error(String.format(
>           "StreamingDestination: cannot delete an active StreamingDestination with identifier [%s]", identifier));
> ```

Change error message: Streaming destination with identifier [%s] cannot be deleted because it active.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 100 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFuHsA5jqOKoJNGIog:-NJFuHsA5jqOKo [...]

2022-12-14 18:51 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: 5 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFpoYy4bHM6wSttcDp:-NJGrp9Q5q_aT-sfdJUk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L34)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This was already plural indicating more than one streaming destination expected in response. No need to append "-list"
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFqCGCEEy1ZQtTl-QS:-NJGrtZO2xxs_TMFNejH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L57)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We will not be supporting multiple streaming destination update in a single call. It should be update-streaming-destination
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFqVaW8nYgLI-jG4Eq:-NJGs3G90hSuihp6XHkN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L72)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should be delete-disabled-streaming-destination
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFqfwJ3bfj2NMm8LrP:-NJGs6xq1ObthvrzXxnL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L86)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

response will be just one streaming destination, so it should be get-streaming-destination
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 245 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFrFrP2VRLwJ9WcH5G:-NJGsM5s4rD_YoNXHP_4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L245)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

StreamingDestinationParam
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 251 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFrKPv5Rppa__BtA_I:-NJGsQ8jCtWfo-m2sUhi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L251)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Streaming Destination identifier
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFtCqs9TFPKmb1sUKQ:-NJGtwOhCECUcASGSZTO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L62)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This error message will shown to user on UI and API response. Keep it as it was earlier.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFtPjP0CxH6bONt1Ve:-NJGukFY56xpBmxQ4K-F:b-e5msri) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L81)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Error message: Streaming Destination with identifier [%s] not found.
</blockquote></details>

Done, however no need of prefix with Error message as it already log.error()
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFt9J_4zqVSRd5WDT4:-NJGu7JQEJjnuFO6ip4h:b-vadzj5) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L82)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

throw NotFoundException
</blockquote></details>

NotFoundException is not part of HarnessExceptions because of which the response to UI comes as "Internal server error. Contact Harness", that's why NoResultFoundException is used so that a proper message can be propagated to UI
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFtwtC79Ii1Cph39uh:-NJGvbOkCdyboCHiOVyL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L98)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Change error message: Streaming destination with identifier [%s] cannot be deleted because it active.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 100 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFuHsA5jqOKoJNGIog:-NJGvcLi6him4oKN3_kV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L100)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Assign error message to a variable and use in both logging and throw.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 154 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFz71w8N6KK8qHjTSR:-NJGvyDQA60FT_lWblOU:b-rldv64) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L154)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This check is redundant. getStreamingDestination call would throw not found exception if entit [...]

2022-12-15 11:06 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: 7 file(s) to review. 1 change requests. 19. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFunnC1Pkk-esCQ3lg:-NJK8dGu5GLKQD4piOjr:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L79)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

There is no complex logic to create criteria. We can simply define findStreamingDestinationByAccountIdentifierAndIdentifier(... , ...) method in 
</blockquote></details>

done
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/streaming/AwsS3StreamingDestination.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFy70LBz0lIIf3UaiH:-NJKPjkG1cRfOzcZCRWT:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/streaming/AwsS3StreamingDestination.java#L42)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why not doing it via repository?
</blockquote></details>

done
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/streaming/StreamingDestination.java` line 70 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFxLV0AyEmj52U8JSZ:-NJKPm_8C6q8qBR0uY6k:b-rldv64) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/streaming/StreamingDestination.java#L70)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why this is required?
</blockquote></details>

agreed and removed
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/v1/api/streaming/StreamingDestinationsApiImpl.java` line 55 at r4](https://reviewable.io/reviews/harness/harness-core/41542#-NJFznPe-7rcm4sQFthF:-NJKSCiY91HwUHnQQ-Y0:b4eyuoi) ([raw file](https://github.com/harness/harness-core/blob/0bdc6084920e37adae7157b0e6cda4fa59087c56/platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/v1/api/streaming/StreamingDestinationsApiImpl.java#L55)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

isDeleted will be FALSE in case when streamingDestinationRepository.deleteByCriteria() is unable to delete the mongo record due to some reason. In this case we want to inform the user.
I will improve the response here.
</blockquote></details>

removed this logic as we already have a retry logic while deleting for cases when DB is down and even after all the retries are exhausted then also we throw exception.
So this is not required.
code quote:
RetryPolicy<Object> retryPolicy = getRetryPolicy("[Retrying]: Failed deleting Streaming Destination; attempt: {}",
        "[Failed]: Failed deleting Streaming Destination; attempt: {}");


<!-- Sent from Reviewable.io -->

2022-12-16 04:43 UTC, nishantsaini20 requested changes
> Reviewed 10 of 11 files at r6, 3 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml` line 178 at r8](https://reviewable.io/reviews/harness/harness-core/41542#-NJO6brJ74KLYTIcSuLu:-NJO6brJ74KLYTIcSuLv:b-1fkzay) ([raw file](https://github.com/harness/harness-core/blob/d48bbd25dd581a05929972f8b2785def3fa3a848/platform-service/modules/audit-service/contracts/openapi/v1/openapi.yaml#L178)):*
> ```YAML
>           format: int64
>           description: Last updated time of the Streaming Destination
>         statusUpdated:
> ```

Use snake case : status_updated
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 156 at r8](https://reviewable.io/reviews/harness/harness-core/41542#-NJO8y-t7GwpLUNmmuoy:-NJO8y-u6OFhZ6MQUwwu:bv5bmv) ([raw file](https://github.com/harness/harness-core/blob/d48bbd25dd581a05929972f8b2785def3fa3a848/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L156)):*
> ```Java
>           "Streaming destination with identifier [%s] cannot be updated.", newStreamingDestination.getIdentifier());
>       log.error(message, exception);
>       throw new Exception(message);
> ```

Why general exception is thrown?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java` line 160 at r8](https://reviewable.io/reviews/harness/harness-core/41542#-NJO9PYp13EQmEu3ZoLU:-NJO9PYp13EQmEu3ZoLV:bdbeo3h) ([raw file](https://github.com/harness/harness-core/blob/d48bbd25dd581a05929972f8b2785def3fa3a848/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingServiceImpl.java#L160)):*
> ```Java
>   }
> 
>   private StreamingDestination validateUpdateRequestAndReturnStreamingDestination(String streamingDestinationIdentifier,
> ```

Fetch existing streaming destination in parent method and pass it as an argument to this method. This method should only perform validation.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/v1/api/streaming/StreamingDestinationsApiImpl.java` line 87 at r8](https://reviewable.io/reviews/harness/harness-core/41542#-NJOBT6u5voOLg7vvzF7:-NJOBT6u5voOLg7vvzF8:bri532v) ([raw file](https://github.com/harness/harness-core/blob/d48bbd25dd581a05929972f8b2785def3fa3a848/platform-service/modules/audit-service/src/main/java/io/harness/audit/remote/v1/api/streaming/StreamingDestinationsApiImpl.java#L87)):*
> ```Java
>   }
> 
>   @SneakyThrows
> ```

Why is this required?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/streaming/StreamingDestinationRepository.java` line 18 at r8](https://reviewable.io/reviews/harness/harness-core/41542#-NJOC2KpB4cNlt5f72Un:-NJOC2KpB4cNlt5f72Uo:b-a45gf7) ([raw file](https://github.com/harness/harness-core/blob/d48bbd25dd581a05929972f8b2785def3fa3a848/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/streaming/StreamingDestinationRepository.java#L18)):*
> ```Java
> public interface StreamingDestinationRepository
>     extends PagingAndSortingRepository<StreamingDestination, String>, StreamingDestinationRepositoryCustom {
>   StreamingDestination findByAccountIdentifierAndIdentifier(String accountIdentifier, String identifier);
> ```

Return can be Optional?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/streaming/StreamingDestinationRepositoryCustomImpl.java` line 51 at r8](https://reviewable.io/reviews/harness/harness-core/41542#-NJODnwH1P_I4fX0iR_S:-NJODnwH1P_I4fX0iR_T:b-jzqgdd) ([raw file](https://github.com/harness/harness-core/blob/d48bbd25dd581a05929972f8b2785def3fa3a848/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/streaming/StreamingDestinationRepositoryCustomImpl.java#L51)):*
> ```Java
>   public boolean deleteByCriteria(Criteria criteria) {
>     Query query = new Query(criteria);
>     RetryPolicy<Object> retryPolicy = getRetryPolicy("[Retrying]: Failed deleting Streaming Destination; attempt: {}",
> ```

IMO it is not really necessary to have this.


<!-- Sent from Reviewable.io -->

2022-12-16 06:22 UTC, nishantsaini20 approved these changes
> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-16 06:24 UTC, nishantsaini20 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-16 06:34 UTC, mankrit-singh approved these changes
> Reviewed 5 of 11 files at r6, 1 of 4 files at r7, 1 of 1 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41542)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-16 07:38 UTC, merged