[feat]: [CDS-46880]: creating crone job for moduleversioninfo
harness/harness-core pull request #41588
Opened 2022-12-14 19:08 UTC by RajBaviskar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-14 19:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=41588) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=41588) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=41588) it.</sub>

2022-12-22 20:34 UTC, abhinav-harness commented
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/41588#-NJvXNJz71Hk38cwobqq:-NJvXNJz71Hk38cwobqr:b-unsxmo) ([raw file](https://github.com/harness/harness-core/blob/1782e12c244a7d9c11acde5ef887337d7f87bbde/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L60)):*
> ```Java
>   @ExceptionMetered
>   @ApiKeyAuthorized(permissionType = LOGGED_IN)
>   public Response listModuleVersions(Integer page, Integer limit) {
> ```

we should return ng style response and java pojo


<!-- Sent from Reviewable.io -->

2022-12-23 03:22 UTC, RajBaviskar commented
> _[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/41588#-NJvXNJz71Hk38cwobqq:-NJvXNJz71Hk38cwobqr:b-unsxmo) ([raw file](https://github.com/harness/harness-core/blob/1782e12c244a7d9c11acde5ef887337d7f87bbde/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L60)):_
> 
> > ```java
> >   @ExceptionMetered
> >   @ApiKeyAuthorized(permissionType = LOGGED_IN)
> >   public Response listModuleVersions(Integer page, Integer limit) {
> > ```
> 
> we should return ng style response and java pojo

Yes we are using it here https://github.com/harness/harness-core/pull/41588/files#diff-b86e3a63eec9a766206b3702dbac647565b1da98b45686dc6e7659f6f5ea69d4R64 before sending it back.

2022-12-23 04:37 UTC, mankrit-singh approved these changes
> Reviewed 5 of 20 files at r1, 2 of 16 files at r5, 14 of 14 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 21 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-24 00:39 UTC, abhinav-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java
> +  @Inject private HPersistence persistence;
use mongo template

2022-12-24 00:39 UTC, abhinav-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/ModuleVersionInfoServiceImpl.java
> +  @Inject private HPersistence persistence;
use mongo template or spring orm

2022-12-24 00:40 UTC, abhinav-harness commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java
> +    moduleVersionsResponse.setName(versioningInfo.getModuleName());
can we use builder pattern instead?

2023-01-04 03:57 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: Some of the checks are too old. 21 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 871 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuodjj8lkjWRlbV_XN:-NKuodjj8lkjWRlbV_XO:b-98f514) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/contracts/openapi/v1/openapi.yaml#L871)):*
> ```YAML
>       security:
>         - x-api-key: []
>   /v1/module-versions:
> ```

We should get APIs reviewed with Doc/API Team
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 1639 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuoTx_9OYR0ymoAkJ6:-NKuoTx_9OYR0ymoAkJ7:b-h5jbqf) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/contracts/openapi/v1/openapi.yaml#L1639)):*
> ```YAML
>           type: string
>           description: Module Release Notes link
>         microservices_version_info:
> ```

Is there a reason we want to publish internal micro-service versions to customers?
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 884 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuot7d8od4_J1WMndn:-NKuot7d8od4_J1WMndo:brgc4e1) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L884)):*
> ```Java
>         .scheduleWithFixedDelay(injector.getInstance(InstanceAccountInfoRunnable.class), 0, 6, TimeUnit.HOURS);
> 
>     injector.getInstance(Key.get(ScheduledExecutorService.class, Names.named("taskPollExecutor")))
> ```

Name seems to be copy-pasted

Frequency of 3 hours seems too high to me. Is 3 hours delay acceptable?
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 885 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKup60-DMnvd_FjRazJ:-NKup60-DMnvd_FjRazK:b-hha41g) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L885)):*
> ```Java
> 
>     injector.getInstance(Key.get(ScheduledExecutorService.class, Names.named("taskPollExecutor")))
>         .scheduleWithFixedDelay(injector.getInstance(VersionInfoUpdateRunnable.class), 0, 3, TimeUnit.HOURS);
> ```

ModuleVersionsMaintenanceTask
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 45 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKupWJU2i7K9p6pfB2H:-NKupWJU2i7K9p6pfB2I:b-r62j2x) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L45)):*
> ```Java
> @Scope(APPLICATION)
> @AuthRule(permissionType = LOGGED_IN)
> @OwnedBy(HarnessTeam.CDC)
> ```

Is it owned by CDC?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/MicroservicesVersionInfo.java` line 22 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuritDAgWlKPA36Hlh:-NKuritDAgWlKPA36Hli:btry9uf) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/MicroservicesVersionInfo.java#L22)):*
> ```Java
> @Schema(name = "MicroservicesVersionInfo",
>     description = "This is the view of the Microservices Version Info of the entity.")
> public class MicroservicesVersionInfo implements Serializable {
> ```

Why it implements Serializable
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/ModuleVersioningInfo.java` line 49 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuqTSh5K3iTQJ3QE4C:-NKuqTSh5K3iTQJ3QE4D:bt185xx) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/ModuleVersioningInfo.java#L49)):*
> ```Java
> @Document("moduleVersioningInfo")
> @TypeAlias("io.harness.ng.core.ModuleVersioningInfo.entity.ModuleVersioningInfo")
> public class ModuleVersioningInfo implements PersistentEntity {
> ```

ModuleVersionInfo
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/ModuleVersioningInfo.java` line 60 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuqjTm1_dONcJgsZB3:-NKuqjTm1_dONcJgsZB4:b-b0j7k1) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/ModuleVersioningInfo.java#L60)):*
> ```Java
>   @NotNull @Schema(description = "Module Display Name") private String displayName;
>   @LastModifiedDate @Schema(description = "Module Last Modified") String lastModifiedAt;
>   @NotNull @Schema(description = "Module versionUrl") private String versionUrl;
> ```

Whats the diff between versionUrl here and in MicroservicesVersionInfo 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 42 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKusiCL24KXvy9h2w9e:-NKusiCL24KXvy9h2w9f:b-7ao6yh) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L42)):*
> ```Java
> @Singleton
> @Slf4j
> public class UpdateVersionInfoTask {
> ```

We should write unit tests for this class
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 76 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuulpV6NO3VUVGLhAo:-NKuulpV6NO3VUVGLhAp:b-1j9nn) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L76)):*
> ```Java
>     allModulesFromDB.forEach(module -> {
>       String currentVersion = "";
>       try {
> ```

Each module can have multiple microservices. currentVersion of which microservice is this?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 79 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKutcjf2uQ2q4oOQyFJ:-NKutcjf2uQ2q4oOQyFK:b-rj0dnz) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L79)):*
> ```Java
>         currentVersion = getCurrentMicroserviceVersions(module.getModuleName(), module.getVersionUrl());
>       } catch (IOException e) {
>         log.error("Update VersionInfo Task Sync job interrupted", e);
> ```

It's not interrupted. There is an exception which needs to be handled
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 98 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKutQwY0uyjl08TGAfH:-NKutQwY0uyjl08TGAfI:b5u2syd) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L98)):*
> ```Java
>       Type listType = new TypeToken<List<ModuleVersioningInfo>>() {}.getType();
>       allModulesFromDB = gson.fromJson(jsonArray.toString(), listType);
>       allModulesFromDB.forEach(module -> { getFormatt [...]

2023-01-09 21:15 UTC, RajBaviskar commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java
> +    moduleVersionsResponse.setName(versioningInfo.getModuleName());
hmm since the response obj is simple we can go with this If this obj gets bigger I'll convert it into a builder.

2023-01-09 21:31 UTC, RajBaviskar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 1 change requests. 21. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 871 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuodjj8lkjWRlbV_XN:-NLNNqdKDuPKtEmYcrDn:b20oo0p) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/contracts/openapi/v1/openapi.yaml#L871)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should get APIs reviewed with Doc/API Team
</blockquote></details>

@mankrit-singh from the API squad has done the work of adding this. I can ask him to re-review.
 
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 1639 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuoTx_9OYR0ymoAkJ6:-NLNON3s3ACbuH-VqwM5:bf8xy2f) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/contracts/openapi/v1/openapi.yaml#L1639)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is there a reason we want to publish internal micro-service versions to customers?
</blockquote></details>

keeping this for backup/iterative work/provide more details. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 884 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuot7d8od4_J1WMndn:-NLNOX9X4_hK4oUTbwxb:b-6d8phn) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L884)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Name seems to be copy-pasted

Frequency of 3 hours seems too high to me. Is 3 hours delay acceptable?
</blockquote></details>

hmm, We are starting with 3, but we are not hard set on it. what's your opinion? 
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 885 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKup60-DMnvd_FjRazJ:-NLNOj2Z0nsNag710bVe:b-b5c35t) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L885)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

ModuleVersionsMaintenanceTask
</blockquote></details>

changed.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 45 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKupWJU2i7K9p6pfB2H:-NLNOl4BDk--qAHdtAd-:brpmqc3) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L45)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is it owned by CDC?
</blockquote></details>

removed.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/MicroservicesVersionInfo.java` line 22 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuritDAgWlKPA36Hlh:-NLNOrKW04l9z3YqhKKG:brpmqc3) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/entity/MicroservicesVersionInfo.java#L22)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why it implements Serializable
</blockquote></details>

removed.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 42 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKusiCL24KXvy9h2w9e:-NLNP3rhE1R1eiYwT8Oe:b-ggxcm9) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L42)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should write unit tests for this class
</blockquote></details>

I tried. But at this point, it's more or less just a crone job making HTTP call script. Let's sync up on this and figure out the correct way to unit-test it. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 76 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKuulpV6NO3VUVGLhAo:-NLNPPmj51HOIWfMv9-q:bo8fdyi) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L76)):*
> currentVersion
for now, we have decided to go with the ng manager for CD and platform. but we will be iterating over this. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 79 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKutcjf2uQ2q4oOQyFJ:-NLNPa6W70vicj3jrbi6:b-t948zx) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L79)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

It's not interrupted. There is an exception which needs to be handled
</blockquote></details>

added.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 98 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKutQwY0uyjl08TGAfH:-NLNPiEp4zf8tR5P1aDC:br6d41e) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L98)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This logic doesn't seem it should belong to this method which is just concerned with reading the file
</blockquote></details>

hmm, should the name of the method be populateModulesInfo to correctly reflect the inner workings? 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 116 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKutyqFDFXUjgMTqB_u:-NLNQ0Ds5NusM4CGuYz8:binq4wk) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L116)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Make sure we are closing request and response body here
</blockquote></details>

don't have a close on request and response. Let's sync up on this. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java` line 129 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NKutx9A8a_wZgnkbHOA:-NLNRKbT92orViZqUp6M:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java#L129)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

It's not interrupted. There is an exception which needs to be handled
</blockquote></details>

added
___
*[`127-cd-nextgen [...]

2023-01-09 21:31 UTC, RajBaviskar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 1 change requests. 22. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/ModuleVersionInfoServiceImpl.java` line 21 at r8](https://reviewable.io/reviews/harness/harness-core/41588#-NJlQtn4IOQBk3tPFwRb-r8-21:-NLNRWya4gzMvC-nTg17:b-ta0gp6) ([raw file](https://github.com/harness/harness-core/blob/ecf0b475faa5e2164c6cd520e53820f834d0b7d2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/ModuleVersionInfoServiceImpl.java#L21)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

use mongo template or spring orm
</blockquote></details>

above.


<!-- Sent from Reviewable.io -->

2023-01-10 07:02 UTC, RajBaviskar commented
[feat]: [CDS-46880]: creating crone job for moduleversioninfo

2023-01-10 07:06 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 2 change requests. 20. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/41588#-NJvXNJz71Hk38cwobqq:-NLPUIhI0ud-aN0JNLUZ:b-y1jvg0) ([raw file](https://github.com/harness/harness-core/blob/1782e12c244a7d9c11acde5ef887337d7f87bbde/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L60)):*
<details><summary><i>Previously, RajBaviskar wrote…</i></summary><blockquote>

Yes we are using it here https://github.com/harness/harness-core/pull/41588/files#diff-b86e3a63eec9a766206b3702dbac647565b1da98b45686dc6e7659f6f5ea69d4R64 before sending it back. 
</blockquote></details>

didnt get you, it should be wrrapped by ResponseDTO
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 42 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUhf3CR6Y053OQqMF:-NLPUhf3CR6Y053OQqMG:b-nbj6cx) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L42)):*
> ```Java
> @Singleton
> @Slf4j
> public class UpdateVersionInfoTask {
> ```

use mongo template - hpersistence is deprecated
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 79 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUnqN5Fbh2Tk-rw5k:-NLPUnqN5Fbh2Tk-rw5l:b5roe09) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L79)):*
> ```Java
>         currentVersion = getCurrentMicroserviceVersions(module.getModuleName(), module.getVersionUrl());
>       } catch (IOException e) {
>         throw new RuntimeException("Update VersionInfo Task Sync job interrupted:" + e);
> ```

throw wingsexceptions child
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 95 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUuHz18MACtZa13Q1:-NLPUuHz18MACtZa13Q2:bvghhtl) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L95)):*
> ```Java
>       Gson gson = new Gson();
>       JsonParser jsonParser = new JsonParser();
>       JsonArray jsonArray = (JsonArray) jsonParser.parse(parsedYamlFile);
> ```

can we directly use objectMapper?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 143 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPV8P13n6VetEGlIQg:-NLPV8P13n6VetEGlIQh:bqj0y56) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L143)):*
> ```Java
>     JSONObject jsonObject = new JSONObject(response.body().toString().trim());
>     JSONObject resourcejsonObject = (JSONObject) jsonObject.get("resource");
>     JSONObject versionInfojsonObject = (JSONObject) resourcejsonObject.get("versionInfo");
> ```

can we use jackson/retrofit?


<!-- Sent from Reviewable.io -->

2023-01-11 05:28 UTC, mankrit-singh commented
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/41588#-NJvXNJz71Hk38cwobqq:-NLUI9GR1CAqNsCXLIYZ:b-dtgn9c) ([raw file](https://github.com/harness/harness-core/blob/1782e12c244a7d9c11acde5ef887337d7f87bbde/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L60)):*
> ResponseDTO
No, it should be Response type only as part of new API


<!-- Sent from Reviewable.io -->

2023-01-11 05:28 UTC, RajBaviskar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 2 change requests. 25. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/41588#-NJvXNJz71Hk38cwobqq:-NLUHpwH78y3Q7SD60DN:b-wwp3jc) ([raw file](https://github.com/harness/harness-core/blob/1782e12c244a7d9c11acde5ef887337d7f87bbde/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L60)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

didnt get you, it should be wrrapped by ResponseDTO
</blockquote></details>

synced offline. not needed for private API.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 42 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUhf3CR6Y053OQqMF:-NLUHx8dE_lrhSo3-iA8:b9k5jwh) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L42)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

use mongo template - hpersistence is deprecated
</blockquote></details>

changed. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 79 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUnqN5Fbh2Tk-rw5k:-NLUHyRmCy-YhKOwjsS8:b-30trtq) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L79)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

throw wingsexceptions child
</blockquote></details>

wingsexceptions is deprecated. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 95 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUuHz18MACtZa13Q1:-NLUI1HB6q2QKexy_Kje:b-t948zx) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L95)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

can we directly use objectMapper?
</blockquote></details>

added.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 143 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPV8P13n6VetEGlIQg:-NLUI2Lu7yitgQncZkSQ:b3j3rf0) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L143)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

can we use jackson/retrofit?
</blockquote></details>

synced offline. N/A


<!-- Sent from Reviewable.io -->

2023-01-11 05:29 UTC, RajBaviskar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 2 change requests. 25. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/41588#-NJvXNJz71Hk38cwobqq:-NLUINZs4H0a3mtJYFzL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1782e12c244a7d9c11acde5ef887337d7f87bbde/120-ng-manager/src/main/java/io/harness/ng/moduleversion/resource/ModuleVersionResource.java#L60)):*
<details><summary><i>Previously, RajBaviskar wrote…</i></summary><blockquote>

synced offline. not needed for private API.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-11 07:22 UTC, RajBaviskar commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/runnable/UpdateVersionInfoTask.java
> +  @Inject private HPersistence persistence;
changed

2023-01-11 07:22 UTC, RajBaviskar commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninginfo/ModuleVersionInfoServiceImpl.java
> +  @Inject private HPersistence persistence;
added

2023-01-11 08:12 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 2 change requests. 18. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 79 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUnqN5Fbh2Tk-rw5k:-NLUs_te5aObsP_kvarG:b39d0s3) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L79)):*
<details><summary><i>Previously, RajBaviskar wrote…</i></summary><blockquote>

wingsexceptions is deprecated. 
</blockquote></details>

Child class of wingsexception make it invalidrequestexception
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 143 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPV8P13n6VetEGlIQg:-NLUsU7G3e7hO-5laqWz:b3kre) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L143)):*
<details><summary><i>Previously, RajBaviskar wrote…</i></summary><blockquote>

synced offline. N/A
</blockquote></details>

?


<!-- Sent from Reviewable.io -->

2023-01-11 08:41 UTC, RajBaviskar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 2 change requests. 19. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 79 at r16](https://reviewable.io/reviews/harness/harness-core/41588#-NLPUnqN5Fbh2Tk-rw5k:-NLUzVm97MI6QFtvdFKS:b-t9490x) ([raw file](https://github.com/harness/harness-core/blob/c82af005dbc8f1caa4cbe5670a265e37dc8fa631/127-cd-nextgen-entities/src/main/java/io/harness/cdng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L79)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Child class of wingsexception make it invalidrequestexception
</blockquote></details>

added


<!-- Sent from Reviewable.io -->

2023-01-11 08:47 UTC, abhinav-harness submitted a review, later dismissed
> Reviewed 1 of 22 files at r1, 2 of 17 files at r11, 1 of 23 files at r17, 18 of 22 files at r22, 1 of 2 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 21 file(s) to review. 1 change requests. 18. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 01:45 UTC, ankit-harness approved these changes
> Reviewed 1 of 23 files at r28.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 22 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 01:45 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588#-:-NLYdpf58hOHaVmgYB2p:bnfp4nl)* status: 22 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 03:35 UTC, abhinav-harness approved these changes
> Reviewed 1 of 23 files at r26, 20 of 23 files at r28, 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 21 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-01-12 03:36 UTC, abhinav-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588#-:-NLZ2CVd4N4zLG0fQ75z:bnfp4nl)* status: 21 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-01-12 03:53 UTC, RajBaviskar reviewed
> Reviewed 1 of 22 files at r1, 1 of 23 files at r26, 13 of 23 files at r28, 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 21 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-01-12 04:42 UTC, mankrit-singh approved these changes
> Reviewed 1 of 23 files at r26, 13 of 23 files at r28, 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: 7 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-01-12 04:43 UTC, mankrit-singh approved these changes
> Reviewed 2 of 17 files at r11, 7 of 23 files at r28.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41588)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-12 06:24 UTC, merged