feat: [CDS-47984]: Ecs Run Task ARN
harness/harness-core pull request #41647
Opened 2022-12-15 20:22 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-15 21:22 UTC, alluvamsi-harness commented
trigger feature-build

2022-12-17 14:31 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: 12 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-18 14:41 UTC, sainath-b commented on 930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsRunTaskArnCommandTaskHandler.java
> +      throw new InvalidArgumentsException(Pair.of("ecsCommandRequest", "Must be instance of EcsRollingDeployRequest"));
exception message need to be changed to EcsRunTaskArnRequest

2022-12-19 05:57 UTC, PragyeshMishra01 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsRunTaskStep.java
> +      EcsRunTaskRequest ecsRunTaskRequest =
what will happen if taskDefinitionArn is expression?

2022-12-19 22:24 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsRunTaskArnCommandTaskHandler.java
> +      throw new InvalidArgumentsException(Pair.of("ecsCommandRequest", "Must be instance of EcsRollingDeployRequest"));
Done

2022-12-19 22:26 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsRunTaskStep.java
> +      EcsRunTaskRequest ecsRunTaskRequest =
added this cdExpressionResolver.updateExpressions(ambiance, stepElementParameters);
expression gets resolved and value will be replaced 
Tested expressions and secretes working fine now updated in test plan as well

2022-12-21 13:45 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java
> +      String errorMessage = "Configure only one Task Definition";
Error message could be better here. We can say 'Both Task Definition, Task Defintion Arn are configured. Only one of them is expected.'

2022-12-21 13:50 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java
> +      String errorMessage = "Configure only one Task Definition";
Ok changing it

2022-12-21 14:02 UTC, PragyeshMishra01 requested changes

2022-12-21 15:58 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsRunTaskArnCommandTaskHandler.java
> +        ecsRunTaskArnRequest.getEcsRunTaskRequestDefinitionManifestContent(),
Sure

2022-12-21 16:43 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java
> +        t -> runTaskLogCallback.saveExecutionLog(format("Task => %s succeeded", t.taskArn())));
task() is always initialized so even passing an empty list will not throw NPE

2022-12-21 16:47 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java
> +    });
failures() is always initialized so even passing an empty list will not throw NPE, failures will never be Null

2022-12-21 16:49 UTC, alluvamsi-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsRunTaskArnRequest.java
> +}
Ok adding it

2022-12-21 16:50 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsRunTaskArnCommandTaskHandler.java
> +        ecsRunTaskArnRequest.getEcsRunTaskRequestDefinitionManifestContent(),
Sure

2022-12-21 18:20 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsRunTaskArnCommandTaskHandler.java
> +        ecsRunTaskArnRequest.getEcsRunTaskRequestDefinitionManifestContent(),
Inside that function error handling is handled in different scenarios which will be caught in EcsDelegateTaskHelper and thrown as TaskNGDataException

2022-12-21 21:12 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsRunTaskArnCommandTaskHandler.java
> +        ecsRunTaskArnRequest.getEcsRunTaskRequestDefinitionManifestContent(),
added .

2022-12-22 03:19 UTC, alluvamsi-harness commented
trigger smartchecks

2022-12-22 08:38 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java
> +        t -> runTaskLogCallback.saveExecutionLog(format("Task => %s succeeded", t.taskArn())));
added

2022-12-22 08:39 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java
> +    });
added

2022-12-22 09:02 UTC, alluvamsi-harness commented
trigger checkpermission

2022-12-22 09:02 UTC, PragyeshMishra01 approved these changes

2022-12-22 09:24 UTC, alluvamsi-harness commented
trigger checkpermission

2022-12-22 09:27 UTC, alluvamsi-harness commented
trigger checkpermission

2022-12-22 11:33 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 10 files at r1, 1 of 2 files at r3, 5 of 16 files at r4, 2 of 11 files at r5, 1 of 5 files at r6, 6 of 8 files at r7, 4 of 4 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: 25 file(s) to review. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-22 12:09 UTC, anilchowdhury-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 10 files at r1, 1 of 2 files at r3, 5 of 16 files at r4, 2 of 11 files at r5, 1 of 5 files at r6, 6 of 8 files at r7, 4 of 4 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647#-:-NJtjGQ8DGEPywowHWkq:bnfp4nl)* status: 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-22 12:13 UTC, PragyeshMishra01 approved these changes
> Reviewed 3 of 10 files at r1, 1 of 2 files at r3, 5 of 16 files at r4, 2 of 11 files at r5, 1 of 5 files at r6, 6 of 8 files at r7, 4 of 4 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-22 12:16 UTC, PragyeshMishra01 approved these changes
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-22 12:18 UTC, PragyeshMishra01 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-22 12:19 UTC, alluvamsi-harness reviewed
> Reviewed 2 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-22 13:52 UTC, mdmilic approved these changes
approve delegate code owned changes

> Reviewed 4 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647#-:-NJu5lY05OX1RNu7cf8l:b-ecdtpk)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-23 07:02 UTC, sainath-b approved these changes

2022-12-23 07:03 UTC, sainath-b reviewed
> Reviewed 3 of 10 files at r1, 1 of 2 files at r3, 5 of 16 files at r4, 2 of 11 files at r5, 1 of 5 files at r6, 6 of 8 files at r7, 4 of 4 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-23 07:03 UTC, sainath-b approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41647)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-23 07:04 UTC, merged

2022-12-23 07:04 UTC, sainath-b commented
@alluvamsi-harness 
Approved this PR. But as discussed, please validate ecs task definition improvment as a part of another PR