fix: [PIE-5086]: Refactor PmsExecutionSummary to be more readable and optimisations
harness/harness-core pull request #41730
Opened 2022-12-19 06:43 UTC by sahilhindwani-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-20 06:14 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/41730#-NJi9lKKC46LaFuY3EyN:-NJi9lKL11ymmIg6AvNx:bp7ify) ([raw file](https://github.com/harness/harness-core/blob/ec745398362fce4ffe92c5bd411e7d4f9f1bfd58/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L189)):*
> ```Java
>           NodeExecution nodeExecution = nodeExecutionService.get(nodeExecutionId);
>           if (nodeExecution.getStepType().getStepCategory() == StepCategory.STRATEGY) {
>             log.info("Status" + nodeExecution.getStatus());
> ```

nit: remove


<!-- Sent from Reviewable.io -->

2022-12-21 10:27 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41730)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-23 07:19 UTC, prashantsharma04 submitted a review, later dismissed
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41730)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-23 07:20 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41730)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-23 08:57 UTC, archit-harness requested changes
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41730)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 145 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy3Zdr8wv1eZwh8HEV:-NJy3Zdu1naq2xDJPI50:bw2m6cy) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L145)):*
> ```Java
>     update.set(
>         String.format(LayoutNodeGraphConstants.BASE_KEY + "." + GraphLayoutNodeDTOKeys.isRollbackStageNode, stageUuid),
>         isRollbackStageNode);
> ```

why this is added here in GraphGenerationServiceImpl from pmsExecutionSUmmaryServiceImpl



_Code quote:_
```Java
    boolean isRollbackStageNode =
        nodeExecution.getNodeId().endsWith(NGCommonUtilPlanCreationConstants.ROLLBACK_STAGE_UUID_SUFFIX);
    update.set(
        String.format(LayoutNodeGraphConstants.BASE_KEY + "." + GraphLayoutNodeDTOKeys.isRollbackStageNode, stageUuid),
        isRollbackStageNode);
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy4zGf6cfCmfA3PKQl:-NJy4zGg6K6PnIiF4ZG2:b-n8xhpu) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java#L26)):*
> ```Java
>       String accountId, String orgId, String projectId, String planExecutionId);
> 
>   boolean handleNodeExecutionUpdate(String planExecutionId, NodeExecution nodeExecution, Update update);
> ```

Can we rename this to handleNodeExecutionUpdateFromGraphUpdate, so that we can different why we are calling this in graphGenerationServiceImpl and not as observer in NodeExecutionServiceImpl/update

Also can you add comments for new method/methods you are updating in interface?



_Code quote (from pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java):_
```Java
addStageNodeInGraphIfUnderStrateg
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy6W0G83BXa82bPQwz:-NJy6W0G83BXa82bPQx-:bsgqi6j) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L54)):*
> ```Java
>   /**
>    * Performs the following:
>    * 1. Fetches all stage and strategy nodeExecutions from db
> ```

can we add stage here is for  identity nodes only as well?
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy7ShaDBx5Fpdr9FEh:-NJy7Shb6PDnKLcNeAip:bn98f5u) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L59)):*
> ```Java
>    *    * if node is of type strategy then add all its children in layoutNodeMap and update the execution summary
>    */
>   public boolean updateStagesOfIdentityType(String planExecutionId, Update update) {
> ```

Rename updateStagesOfIdentityTypeInFinalStatusUpdate
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy5wPfDOljJFvm_uXD:-NJy5wPfDOljJFvm_uXE:b-rhi0fd) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L63)):*
> ```Java
> 
>     List<NodeExecution> stageOrStrategyNodeExecutions =
>         nodeExecutionService.fetchStageExecutionsWithEndTsAndStatusProjection(planExecutionId);
> ```

Refactor this nodeExecution method to use iterator and projectionField to be moved to NodeProjectionUtils, also verify this method is using proper index



_Code quote:_
```Java
fetchStageExecutionsWithEndTsAndStatusProjection
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy6Ij3-lNq_jLYmJfH:-NJy6Ij3-lNq_jLYmJfI:bfrqynt) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L74)):*
> ```Java
> 
>     // This is done inorder to reduce the load while updating stageInfo. Here we will update only the status.
>     for (NodeExecution nodeExecution : stageOrStrategyNodeExecutions) {
> ```

This we should use iterator from above method



_Code quote:_
```Java
for (NodeExecution nodeExecution : stageOrStrategyNodeExecutions)
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy6NRHEyVi699tqHQX:-NJy6NRHEyVi699tqHQY:bdet8ve) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L75)):*
> ```Java
>     // This is done inorder to reduce the load while updating stageInfo. Here we will update only the status.
>     for (NodeExecution nodeExecution : stageOrStrategyNodeExecutions) {
>       if (nodeExecution.getStepType().getStepCategory() != StepCategory.STRATEGY) {
> ```

Can you add comment, here not equal means this is stage node?
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy8bhh9oKvso7uKTaB:-NJy8bhi-Q3Mftef_PZL:bwez4xv) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L90)):*
> ```Java
> 
>       // Filter child executions for this strategy
>       List<NodeExecution> childrenNodeExecution = stageOrStrategyNodeExecutions.stream()
> ```

How this list can be child executions for the strategy? 



_Code quote:_
```Java
stageOrStrategyNodeExecutions
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 105 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy9Uo08DDWOQPOI59b:-NJy9Uo08DDWOQPOI59c:b-pjreql) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L105)):*
> ```Java
>                     + ".moduleInfo.maxConcu [...]

2023-01-04 04:15 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 145 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy3Zdr8wv1eZwh8HEV:-NKuzKFvBFPOEH9SyhQB:bvbd4zg) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L145)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this is added here in GraphGenerationServiceImpl from pmsExecutionSUmmaryServiceImpl
</blockquote></details>

This was added because of the change in approach to reduce updates.


<!-- Sent from Reviewable.io -->

2023-01-10 11:43 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy9jUYAfvij4VKjKoN:-NLQUOQG8UO0eCq5ccio:b-f5gfnp) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L114)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are adding new updates here?
</blockquote></details>

Have changed the approach in this PR, therefore had to move some code.


<!-- Sent from Reviewable.io -->

2023-01-10 11:45 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJyB3Oa3JUQcFEkzoN4:-NLQUxgP0XYBXIROLEfE:b-vc1db4) ([raw file](https://github.com/harness/harness-core/blob/698e89ec785bf79fe16c91cbadbee0cfdc164d32/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L126)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what will be the impact if we remove it from here? 
</blockquote></details>

There is a change in approach and there if node required here now.


<!-- Sent from Reviewable.io -->

2023-01-10 11:55 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy6Ij3-lNq_jLYmJfH:-NLQX7K_AIk408IuotF0:b-3y9a5t) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L74)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This we should use iterator from above method
</blockquote></details>

Is it fine if I do it in next PR? Want to ensure that many major changes don't go all at once.


<!-- Sent from Reviewable.io -->

2023-01-10 11:55 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy5wPfDOljJFvm_uXD:-NLQXF3x--JhjozeO7OA:b-hsd210) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Refactor this nodeExecution method to use iterator and projectionField to be moved to NodeProjectionUtils, also verify this method is using proper index
</blockquote></details>

Is it fine if I do that in next PR, don't want to have many changes in one go


<!-- Sent from Reviewable.io -->

2023-01-10 12:37 UTC, archit-harness reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41730)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy5wPfDOljJFvm_uXD:-NLQfdXJ4Ox9o4C57QrP:bqobrvj) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L63)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Is it fine if I do that in next PR, don't want to have many changes in one go
</blockquote></details>

done, should be okay
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy6Ij3-lNq_jLYmJfH:-NLQfh8Q5N-3kVJW7S6D:bqo5zt1) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L74)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Is it fine if I do it in next PR? Want to ensure that many major changes don't go all at once.
</blockquote></details>

done, should be fine


<!-- Sent from Reviewable.io -->

2023-01-11 13:39 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r3, 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41730)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy4zGf6cfCmfA3PKQl:-NLW1D9uBdq4nblkVbcT:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we rename this to handleNodeExecutionUpdateFromGraphUpdate, so that we can different why we are calling this in graphGenerationServiceImpl and not as observer in NodeExecutionServiceImpl/update

Also can you add comments for new method/methods you are updating in interface?
</blockquote></details>

done, discussed offline



_Code quote (from pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java):_
```Java
childSetupId
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy6W0G83BXa82bPQwz:-NLW1H3d1UsRPw-QNcRV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add stage here is for  identity nodes only as well?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy7ShaDBx5Fpdr9FEh:-NLW1L41CGlnbFcMzxgz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Rename updateStagesOfIdentityTypeInFinalStatusUpdate
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy6NRHEyVi699tqHQX:-NLW1ORJELMaHCBRoIjx:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you add comment, here not equal means this is stage node?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy8bhh9oKvso7uKTaB:-NLW1X_P3cKi5zpa-Sem:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L90)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

How this list can be child executions for the strategy? 
</blockquote></details>

done



_Code quote:_
```Java
stageOrStrategyNodeExecutions
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 105 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy9Uo08DDWOQPOI59b:-NLW1hHH6Y2eUflN2zbe:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we removed the method and brought it here? maybe private method we can retain?
</blockquote></details>

done, discussed offline



_Code quote:_
```Java
fetchStageExecutionsWithEndTsAndStatusProjection
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy9jUYAfvij4VKjKoN:-NLW1pyw3dmIlFgW2r-N:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L114)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Have changed the approach in this PR, therefore had to move some code.
</blockquote></details>

done, discussed offline
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 136 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJyAyAIANUR8mNwGGWL:-NLW1vCw7p4pBAGWmomR:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L136)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we move them to a private method?
</blockquote></details>

done, discussed offline
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 190 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJyBNJA32aI-KMwUIAA:-NLW20gP2SJqsEGld02Q:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L190)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This has some common code from updateStagesOfIdentityType, so private method for respective functionality would be better?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 304 at r3](https://reviewable.io/reviews/harness/harness-core/41730#-NJy74pZ1p_uQgxHjvNH:-NLW2JOk7E5KIPm_RNQ6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c0a39ef6670b2c87f5a9df3016424802837c2391/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L304)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you mention which handler we are talking about? so that any new person its easy to understand [...]

2023-01-11 13:45 UTC, senjucanon2 approved these changes
> Reviewed 2 of 7 files at r1, 2 of 2 files at r3, 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41730)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-11 13:46 UTC, merged