[feat]: [CCM-10266]: Budget Groups CRUD apis
harness/harness-core pull request #41802
Opened 2022-12-20 09:15 UTC by svmav

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-21 05:11 UTC, iamanmolm requested changes

2022-12-21 05:11 UTC, iamanmolm commented on ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/BudgetGroupsResource.java
> +    return ResponseDTO.newResponse(budgetGroupService.delete(budgetGroupId, accountId));
Should we enable RBAC here? Like who ever has access to budgets can access budgetgroups as well?
And same thing at all the CRUD apis.

2022-12-21 05:11 UTC, iamanmolm commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java
> +    return budgetGroupDao.delete(uuid, accountId);
At time of delete budgetGroup it should adjust the parent of all the child of the budget group we are deleting.

2022-12-21 05:11 UTC, iamanmolm commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java
> +    budgetGroupDao.update(uuid, accountId, budgetGroup);
Update would readjust all the child budgets recursively. And all the parent budget as well.

2022-12-21 05:11 UTC, iamanmolm commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java
> +    return budgetGroupDao.save(budgetGroup);
Can we put some validation like budgetGroup name will always be unique?
Like both at update & create flow.

2022-12-21 11:09 UTC, svmav commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java
> +    return budgetGroupDao.delete(uuid, accountId);
This is a basic CRUD apis PR, the cascading logic will be part of future PR.

2022-12-21 11:10 UTC, svmav commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java
> +    budgetGroupDao.update(uuid, accountId, budgetGroup);
This is a basic CRUD apis PR, the cascading logic will be part of future PR.

2022-12-22 04:27 UTC, svmav commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java
> +    return budgetGroupDao.save(budgetGroup);
Added validations

2022-12-22 04:28 UTC, svmav commented on ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/BudgetGroupsResource.java
> +    return ResponseDTO.newResponse(budgetGroupService.delete(budgetGroupId, accountId));
Added rbac checks

2022-12-23 03:32 UTC, iamanmolm commented on ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/BudgetGroupsResource.java
> +    return ResponseDTO.newResponse(budgetGroupService.delete(budgetGroupId, accountId));
Cool

2022-12-23 03:39 UTC, iamanmolm commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/dao/BudgetGroupDao.java
> +  public List<BudgetGroup> list(String accountId, String budgetGroupName) {
Wont it return just single budgetGroup? Why we are returning list of BudgetGroup here?

2022-12-23 03:39 UTC, iamanmolm commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java
> +    budgetGroupDao.update(uuid, accountId, budgetGroup);
We need to validate BudgetGroup name at the time of update as well.

2022-12-27 04:59 UTC, svmav commented on 490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/dao/BudgetGroupDao.java
> +  public List<BudgetGroup> list(String accountId, String budgetGroupName) {
It can return multiple elements in case of direct db inserts of documents having a duplicate budget group name. Similar handling has been done for budgets.

2022-12-27 06:43 UTC, iamanmolm approved these changes

2022-12-27 08:20 UTC, svmav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41802)* status: 6 file(s) to review. 5. unresolved discussions. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/41802#-NJioL8Bh61XTME2r2Zv-r4-29:-NKHerWd-3fKub6Y7NgE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fc62685daa025a27780fb1731d737a6338063333/490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/service/BudgetGroupServiceImpl.java#L29)):*
<details><summary><i>Previously, iamanmolm (Anmol Maheshwari) wrote…</i></summary><blockquote>

We need to validate BudgetGroup name at the time of update as well. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-27 08:32 UTC, iamanmolm approved these changes
> Reviewed 1 of 3 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41802)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2022-12-27 08:37 UTC, iamanmolm approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41802)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-27 08:43 UTC, merged