fix: [CDS-49020]: Nexus3 fix
harness/harness-core pull request #41869
Opened 2022-12-21 11:16 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-03 05:53 UTC, puthrayaharness requested changes
Please ensure that this code does not break anything in CG.

2023-01-03 05:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/nexus/NexusThreeClientImpl.java
> +              throw new ArtifactServerException(
Please throw Hint/Explanation exception

2023-01-03 05:53 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/nexus/NexusTwoClientImpl.java
> +        throw new ArtifactServerException("No versions found with specified extension/classifier", null, USER);
Please throw hint/explanation exception?

2023-01-03 05:53 UTC, puthrayaharness commented on 960-api-services/src/test/java/io/harness/artifacts/nexus/NexusThreeClientImplTest.java
> +      nexusThreeService.getVersions(nexusConfig, repoKey, "groupId", artifactPath, "war", "ex");
Please use assertThatThrownBy rather than try catch.
Please add more test cases to cover all the conditions added in the new code flow.

2023-01-04 09:26 UTC, shivamnegi94 commented
trigger ft1, ft2

2023-01-04 09:40 UTC, shivamnegi94 commented
trigger messagecheck

2023-01-04 13:11 UTC, puthrayaharness approved these changes

2023-01-04 13:12 UTC, puthrayaharness approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41869)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-04 16:01 UTC, naman-goenka approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41869)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-05 03:27 UTC, merged