fix: [CDS-49039]: Fixing the execution flow for openshift templates manifest
harness/harness-core pull request #41875
Opened 2022-12-21 11:54 UTC by GoelPratyush99

## Describe your changes
Fixing the execution flow for openshift templates manifest using custom remote store. Kubernetes deployment was not working with Openshift using custom remote store.

## Automation 
Added UT
Automation will be a part of this ticket: 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-22 14:02 UTC, abosii-harness requested changes
Please make sure that all scenarios are working properly. 
1. No Params
2. Git 
3. Git + Local 
4. Git + Local + Custom
5. Local
6. Local + Custom
7. Custom

The overall logic is very tricky and hard to follow

2022-12-22 14:05 UTC, abosii-harness requested changes

2022-12-22 14:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java
> +      return otGitStoreDelegateConfig.getPaths().get(0);
Can we make sure that the paths is not empty and if it is throw the proper error? This should be done for other branches, something like InvalidArgumentException should be enough, but if you can think about some hint + explanation that will be good

2022-12-22 14:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java
> +      if (openshiftTemplatePath.charAt(0) == '/') {
We should have an isNotEmpty(openshiftTemplatePath) check before openshiftTemplatePath.charAt(0)

2022-12-22 14:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java
> +      return getFileName(customRemoteStoreDelegateConfig.getCustomManifestSource().getFilePaths().get(0));
Why this getFileName method is required here? Didn't see it before. Anyway is comming from fabric8 
import static io.fabric8.utils.Files.getFileName;
First we should avoid using fabric8 and the method logic is not defined by us

2022-12-22 18:10 UTC, abosii-harness requested changes

2022-12-22 18:10 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +        LinkedList<ManifestOutcome> orderedParamsManifests = new LinkedList<>(openshiftParamManifestOutcomes);
Is this conversion from ArrayList -> LinkedList -> ArrayList is really required?

2022-12-28 18:24 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41875)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 750 at r3](https://reviewable.io/reviews/harness/harness-core/41875#-NJoXNBzn45PdMDa_YJd-r3-750:-NKOyWSeATnIRmTO7i7c:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/aea8c4dd9c01f415d7c5e8cad5b98512d1c0d8cb/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L750)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this conversion from ArrayList -> LinkedList -> ArrayList is really required?
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3128 at r3](https://reviewable.io/reviews/harness/harness-core/41875#-NJoXNBzn45PdMDa_YJf-r3-3128:-NKOy_E15Pzs3r6Nf9WD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/aea8c4dd9c01f415d7c5e8cad5b98512d1c0d8cb/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3128)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we make sure that the paths is not empty and if it is throw the proper error? This should be done for other branches, something like InvalidArgumentException should be enough, but if you can think about some hint + explanation that will be good 
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3132 at r3](https://reviewable.io/reviews/harness/harness-core/41875#-NJoXNBzn45PdMDa_YJf-r3-3132:-NKOyaIv1BjBDiaFwTse:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/aea8c4dd9c01f415d7c5e8cad5b98512d1c0d8cb/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3132)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We should have an isNotEmpty(openshiftTemplatePath) check before openshiftTemplatePath.charAt(0)
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3139 at r3](https://reviewable.io/reviews/harness/harness-core/41875#-NJoXNBzn45PdMDa_YJf-r3-3139:-NKOybKJ11BJ9qXCYH2m:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/aea8c4dd9c01f415d7c5e8cad5b98512d1c0d8cb/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3139)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why this getFileName method is required here? Didn't see it before. Anyway is comming from fabric8 
import static io.fabric8.utils.Files.getFileName;
First we should avoid using fabric8 and the method logic is not defined by us
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-05 14:00 UTC, abosii-harness approved these changes
> Reviewed 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41875)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 11:43 UTC, achyuth-harness approved these changes
> Reviewed 2 of 6 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41875)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 14:25 UTC, abosii-harness approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41875)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-11 18:00 UTC, merged