fix: [CDS-48637]: instances
harness/harness-core pull request #41902
Opened 2022-12-22 05:37 UTC by TarunUba1

## Describe your changes
Not sending nulll when tried and exception occuring
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-22 14:40 UTC, abosii-harness requested changes

2022-12-22 14:40 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/repositories/instancestats/InstanceStatsRepositoryImpl.java
> +          throw ex;
Aren't we losing this case the retries?

2022-12-26 15:46 UTC, abosii-harness approved these changes
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41902)* status: Some of the checks are too old. 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-27 07:19 UTC, namantalaycha10 approved these changes
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41902)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-12-27 07:20 UTC, namantalaycha10 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41902)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-12-27 07:44 UTC, namantalaycha10 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41902)* status: 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-27 07:48 UTC, abosii-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41902)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-27 08:49 UTC, merged