[fix]: [PL-30236]: throw 404 not found exception in ResourceGroup Get API
harness/harness-core pull request #41958
Opened 2022-12-23 10:32 UTC by kapil-harness

## Describe your changes
throw 404 not found exception in ResourceGroup Get API when a resource group is not found. Before this fix it was returning 200 response.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-23 10:33 UTC, kapil-harness commented
<img width="1792" alt="Screenshot 2022-12-23 at 3 55 20 PM" src="https://user-images.githubusercontent.com/90614549/209320762-f3f06800-d3f9-48ba-93cf-f815f60bb6cf.png">

2022-12-23 10:39 UTC, meenakshi-harness requested changes

2022-12-23 10:39 UTC, meenakshi-harness commented on platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java
> +      throw NoResultFoundException.newBuilder()
I think its better to make this change at service layer instead of resource layer?

2022-12-23 10:41 UTC, reetika04 commented on platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java
> +      throw NoResultFoundException.newBuilder()
Can we make this a common utility that can be used across services? I think we should keep it at the Resource layer itself.

2022-12-23 10:45 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyXegvdZMeVG-MLQIp-r1-71:-NJy_3bO1whLPBpkNI6X:b-jpuiwo) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Can we make this a common utility that can be used across services? I think we should keep it at the Resource layer itself.
</blockquote></details>

@meenakshi-harness I agree however access-control service uses it at the service layer and expects null as an output. So its better to make this change at resource layer. Refer comment https://harness.atlassian.net/browse/PL-30236?focusedCommentId=397108
@reetika04 common utility as in?


<!-- Sent from Reviewable.io -->

2022-12-23 11:09 UTC, mohitg0795 commented
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyf3VN2K9dPAUDTLYP:-NJyf3VN2K9dPAUDTLYQ:b-5a569r) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L70)):*
> ```Java
>     if (optionalResourceGroupResponse.isEmpty()) {
>       String message = String.format("Resource group with identifier [%s] not found.", identifier);
>       log.error(message);
> ```

why is this an error?


<!-- Sent from Reviewable.io -->

2022-12-23 11:10 UTC, mohitg0795 commented
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyf9mgCyXVdNBcRKGC:-NJyf9mgCyXVdNBcRKGD:bvyxxhx) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
> ```Java
>       String message = String.format("Resource group with identifier [%s] not found.", identifier);
>       log.error(message);
>       throw NoResultFoundException.newBuilder()
> ```

Why are we building complete exception here itself? We should throw ResourceNotFoundException or something similar which already has error code = RESOURCE_NOT_FOUND and other details.


<!-- Sent from Reviewable.io -->

2022-12-23 11:10 UTC, mohitg0795 commented
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyXegvdZMeVG-MLQIp-r1-71:-NJyfKSe4UDvxOx0eXfv:bxkfsxv) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

@meenakshi-harness I agree however access-control service uses it at the service layer and expects null as an output. So its better to make this change at resource layer. Refer comment https://harness.atlassian.net/browse/PL-30236?focusedCommentId=397108
@reetika04 common utility as in?
</blockquote></details>

Changing anything at service layer may impact other use-cases as well, so just be careful around it if we go ahead with it.


<!-- Sent from Reviewable.io -->

2022-12-23 11:22 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyXegvdZMeVG-MLQIp-r1-71:-NJyh5WG4oHWIaEM8pRU:bsof16m) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Changing anything at service layer may impact other use-cases as well, so just be careful around it if we go ahead with it.
</blockquote></details>

Following best practice, Http status handling should be done at Resource layer. 


<!-- Sent from Reviewable.io -->

2022-12-23 11:41 UTC, mohitg0795 commented
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyXegvdZMeVG-MLQIp-r1-71:-NJym2mVB53myRCkD7Zq:b-faw8f1) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Following best practice, Http status handling should be done at Resource layer. 
</blockquote></details>

Here we cannot throw error anyways from service layer as our service interface returns an optional response, which means it can be nullable. Thus, it doesn't make any sense to throw exception from service layer itself if object isn't found. Either we should change our interface method itself then it would be logical to throw exception, if we really want to go that way.


<!-- Sent from Reviewable.io -->

2022-12-23 14:59 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyf3VN2K9dPAUDTLYP:-NJzQ1SZDL1wmAyeqcgF:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L70)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this an error?
</blockquote></details>

removed
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyXegvdZMeVG-MLQIp-r1-71:-NJzPa-36nWcQa9dUNVn:b-6guzt3) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here we cannot throw error anyways from service layer as our service interface returns an optional response, which means it can be nullable. Thus, it doesn't make any sense to throw exception from service layer itself if object isn't found. Either we should change our interface method itself then it would be logical to throw exception, if we really want to go that way.
</blockquote></details>

Reiterating again, this logic will remain at resource layer because service layer is used by access-control service which expects a null value rather than an exception, so in order to avoid regression we will stick to it. 
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyf9mgCyXVdNBcRKGC:-NJzTib23FX5rjN7sW_O:b-vadzj5) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why are we building complete exception here itself? We should throw ResourceNotFoundException or something similar which already has error code = RESOURCE_NOT_FOUND and other details.
</blockquote></details>

NotFoundException is not part of HarnessExceptions because of which the response to UI comes as "Internal server error. Contact Harness", that's why NoResultFoundException is used so that a proper message can be propagated to UI


<!-- Sent from Reviewable.io -->

2022-12-23 15:02 UTC, mohitg0795 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-23 15:14 UTC, kapil-harness commented
trigger messagecheck

2022-12-23 15:35 UTC, meenakshi-harness approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-23 18:24 UTC, tiwaritejas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2022-12-27 03:20 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958)* status: Some of the checks are too old. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/41958#-NJyXegvdZMeVG-MLQIp-r1-71:-NKG_p0P8-9KhKGrtlMg:b1smoi1) ([raw file](https://github.com/harness/harness-core/blob/c7269cd1fbe2c6d3d7e517c10aa727426134a23b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L71)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

Reiterating again, this logic will remain at resource layer because service layer is used by access-control service which expects a null value rather than an exception, so in order to avoid regression we will stick to it. 
</blockquote></details>

@kapil-harness Use NotFoundException. check how NotFoundExceptionMapper will handle propogating 404 error to UI. You can find usage for NotFoundExceptionMapper.


<!-- Sent from Reviewable.io -->

2022-12-29 10:45 UTC, Jimit09Gandhi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41958#-:-NKSUCoD2EfhH2A6pfAY:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2022-12-29 12:07 UTC, merged