techdebt: [PIE-7200]: add policy eval for shell script step
harness/harness-core pull request #42007
Opened 2022-12-27 10:06 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-28 06:54 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVTxi5Kw9mXmC89sj:-NKMVTxj2XKOkoj2vNQg:b-qs9400) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L22)):*
> ```Java
> import java.util.Map;
> 
> public abstract class TaskExecutableWithRollbackAndPolicyEval<R extends ResponseData>
> ```

Can we raname it to CDTaskExecutable? Also rbac needs  to be there.


<!-- Sent from Reviewable.io -->

2022-12-28 06:54 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVTxi5Kw9mXmC89sj:-NKMVlWSCQG6sWB4kwMY:bnpp9mc) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L22)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we raname it to CDTaskExecutable? Also rbac needs  to be there.
</blockquote></details>

or PipelineTaskExecutable?


<!-- Sent from Reviewable.io -->

2022-12-28 06:55 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVsF-38ZDDU_JcjU3:-NKMVsF-38ZDDU_JcjU4:b-7d9ttp) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L42)):*
> ```Java
>       Ambiance ambiance, StepElementParameters stepParameters, ThrowingSupplier<R> responseSupplier) throws Exception;
> 
>   public StepResponse policyEval(Ambiance ambiance, StepElementParameters stepParameters, StepResponse stepResponse) {
> ```

nit: rename this function to postValidations


<!-- Sent from Reviewable.io -->

2022-12-28 06:56 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVz542JwSyusoyof9:-NKMVz542JwSyusoyofA:bosydgl) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L23)):*
> ```Java
> 
> public abstract class TaskExecutableWithRollbackAndPolicyEval<R extends ResponseData>
>     implements TaskExecutable<StepElementParameters, R> {
> ```

implement TaskExecutableWithRollback 


<!-- Sent from Reviewable.io -->

2022-12-28 07:01 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 7 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVTxi5Kw9mXmC89sj:-NKMWk-f6TI2ubCi4ZGZ:bq93ha9) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L22)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

or PipelineTaskExecutable?
</blockquote></details>

Shell script and HTTP step were extending TaskExecutableWithRollback only not with rbac. That's why I have also not used RBAC one here.
___
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVz542JwSyusoyof9:-NKMWz3262_X3RMgJaG5:b-bjfq88) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L23)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

implement TaskExecutableWithRollback 
</blockquote></details>

can we replace TaskExecutableWithRollback with this new abstract class, since older one is only used by shell script and http steps and with this new class, there are 0 usages of the older class.
___
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVsF-38ZDDU_JcjU3:-NKMXClZAsr8a4KLvOHV:b-d7bhn0) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L42)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: rename this function to postValidations
</blockquote></details>

will do


<!-- Sent from Reviewable.io -->

2022-12-30 06:04 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 159 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWcUHn4tOiIKq7zFYL:-NKWcUHn4tOiIKq7zFYM:b-16kh32) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L159)):*
> ```Java
>       log.error("Unable to parse error response from Policy Manager. Error response:\n" + errorResponseString, e);
>       return PolicyEvalUtils.buildFailureStepResponse(ErrorCode.HTTP_RESPONSE_EXCEPTION,
>           "Unexpected error occurred while evaluating Policies.", FailureType.APPLICATION_FAILURE);
> ```

Lets use constants here instead of hard coded strings.


<!-- Sent from Reviewable.io -->

2022-12-30 06:05 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 152 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWcXr43MIRtID_o9y3:-NKWcXr43MIRtID_o9y4:by2sq33) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L152)):*
> ```Java
>       PolicyEvaluationErrorResponse policyEvaluationErrorResponse =
>           YamlUtils.read(errorResponseString, PolicyEvaluationErrorResponse.class);
>       String errorMessage = policyEvaluationErrorResponse.getMessage().replace("policy set", "Policy Set");
> ```

use constants ^


<!-- Sent from Reviewable.io -->

2022-12-30 06:05 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 157 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWc_Kq0wuyU5QOQO_9:-NKWc_Kq0wuyU5QOQO_A:by2sq33) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L157)):*
> ```Java
> 
>     } catch (IOException e) {
>       log.error("Unable to parse error response from Policy Manager. Error response:\n" + errorResponseString, e);
> ```

use constants ^


<!-- Sent from Reviewable.io -->

2022-12-30 06:05 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 143 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWcekpBNCSxTm2yzny:-NKWcekpBNCSxTm2yznz:bel93dt) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L143)):*
> ```Java
>       // Policy manager does not support primitive values like strings or numbers. Arrays are also not supported
>       return !yamlField.getNode().isObject();
>     } catch (IOException e) {
> ```

lets log the exception


<!-- Sent from Reviewable.io -->

2022-12-30 06:05 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 133 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWcjBS7NgVvY5n7B8j:-NKWcjBS7NgVvY5n7B8k:by2sq33) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L133)):*
> ```Java
>     }
>     if (failedPolicySets.size() == 1) {
>       return "The following Policy Set was not adhered to: " + failedPolicySetsString;
> ```

use constants ^


<!-- Sent from Reviewable.io -->

2022-12-30 06:06 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 135 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWclueCUhcOrtem0Gx:-NKWclueCUhcOrtem0Gy:by2sq33) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L135)):*
> ```Java
>       return "The following Policy Set was not adhered to: " + failedPolicySetsString;
>     }
>     return "The following Policy Sets were not adhered to: " + failedPolicySetsString;
> ```

use constants ^


<!-- Sent from Reviewable.io -->

2022-12-30 06:07 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 114 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWd-6H-KCP6B7f_QfR:-NKWd-6H-KCP6B7f_QfS:b-jita6p) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L114)):*
> ```Java
>   }
>   public String getEntityMetadataString(String stepName) {
>     Map<String, String> metadataMap = ImmutableMap.<String, String>builder().put("entityName", stepName).build();
> ```

use constants 


<!-- Sent from Reviewable.io -->

2022-12-30 06:07 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 61 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWd3iABS706X7qJYju:-NKWd3iABS706X7qJYjv:b-6lh3jt) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L61)):*
> ```Java
>               getPolicySetsStringForQueryParam(stepParameters.getEnforce().getPolicySets().getValue()),
>               getEntityMetadataString(stepParameters.getName()), stepResponse.getStepOutcomes()));
>     } catch (InvalidRequestException ex) {
> ```

log error


<!-- Sent from Reviewable.io -->

2022-12-30 06:50 UTC, senjucanon2 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWmrYg6oKJBrc33KdM:-NKWmrYg6oKJBrc33KdN:bhahr8f) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L47)):*
> ```Java
> 
> @UtilityClass
> @Slf4j
> ```

do we really need these new methods to be public?
same for below ones


<!-- Sent from Reviewable.io -->

2022-12-30 07:07 UTC, shalini-agr commented
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWmrYg6oKJBrc33KdM:-NKWqeeO0o4flbkMqi9W:bir65h) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L47)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

do we really need these new methods to be public?
same for below ones
</blockquote></details>

Yes, because we will be using these in different steps across services, so has to be public.


<!-- Sent from Reviewable.io -->

2022-12-30 07:23 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 13 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 61 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWd3iABS706X7qJYju:-NKWuSE_40lw3PJM8ijm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L61)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log error
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 143 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWcekpBNCSxTm2yzny:-NKWuQdl60XWLdHtWGBX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L143)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets log the exception
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-30 08:14 UTC, senjucanon2 approved these changes
> Reviewed 1 of 5 files at r1, 2 of 6 files at r2, 6 of 10 files at r4, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 13 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2022-12-30 08:32 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 14 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 114 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWd-6H-KCP6B7f_QfR:-NKX92Jq9beyyh-0lQC5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

use constants 
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 152 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWcXr43MIRtID_o9y3:-NKX940P9yKLd3zAXbu8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L152)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

use constants ^
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-30 09:33 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 14 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java` line 159 at r6](https://reviewable.io/reviews/harness/harness-core/42007#-NKWcUHn4tOiIKq7zFYL:-NKXMoIv-RFAoYU3n-vU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a28fdcab074db2b7ffbfea1f9833ee561d128873/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyEvalUtils.java#L159)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets use constants here instead of hard coded strings.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-03 07:28 UTC, archit-harness reviewed
> Reviewed 1 of 5 files at r1, 3 of 10 files at r4, 1 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 10 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/PolicyConstants.java` line 10 at r10](https://reviewable.io/reviews/harness/harness-core/42007#-NKqWX4FEiGzXlPF4D6S:-NKqWX4H8ARLu4QX4vDn:b-7sv0tz) ([raw file](https://github.com/harness/harness-core/blob/bbe4b3dca1d9f535c670958e7f6a5e5f220d2bae/878-ng-common-utilities/src/main/java/io/harness/PolicyConstants.java#L10)):*
> ```Java
> package io.harness;
> 
> public interface PolicyConstants {
> ```

nit: public static final class can you make it this for constants, I am fine with thisas well though



_Code quote:_
```Java
interface PolicyConstants
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVz542JwSyusoyof9:-NKqWvuL7DSPFDI6qy4g:b-ij0xg6) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L23)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

can we replace TaskExecutableWithRollback with this new abstract class, since older one is only used by shell script and http steps and with this new class, there are 0 usages of the older class.
</blockquote></details>

@shalini-agr can we have call for this? 


<!-- Sent from Reviewable.io -->

2023-01-03 07:45 UTC, shalini-agr commented
*[`878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/42007#-NKMVz542JwSyusoyof9:-NKq_j1x7EKmSRVUR5hE:b-ty4s5a) ([raw file](https://github.com/harness/harness-core/blob/cb9a0ccebb7747ab0781e3fa6f39e1de26d80d71/878-ng-common-utilities/src/main/java/io/harness/executables/TaskExecutableWithRollbackAndPolicyEval.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shalini-agr can we have call for this? 
</blockquote></details>

sure @archit-harness 


<!-- Sent from Reviewable.io -->

2023-01-06 04:43 UTC, namanvermah submitted a review, later dismissed
> Reviewed 1 of 5 files at r1, 5 of 10 files at r4, 2 of 3 files at r10, 52 of 54 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 58 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-06 05:30 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/executables/CdTaskExecutable.java` line 29 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4YRjr0-IdHuGCMtgn:-NL4YRjs3K8Au0d_G9nO:bwlj2jp) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/125-cd-nextgen/src/main/java/io/harness/cdng/executables/CdTaskExecutable.java#L29)):*
> ```Java
> 
>   public StepResponse postValidate(Ambiance ambiance, StepElementParameters stepParameters, StepResponse stepResponse) {
>     if (stepResponse.getStatus().equals(Status.SUCCEEDED)) {
> ```

nit: better to have constants on the left side of comparison as a good practice


<!-- Sent from Reviewable.io -->

2023-01-06 05:40 UTC, shalini-agr commented
*[`878-ng-common-utilities/src/main/java/io/harness/PolicyConstants.java` line 10 at r10](https://reviewable.io/reviews/harness/harness-core/42007#-NKqWX4FEiGzXlPF4D6S:-NL4a7gP0fKDUC-bkfmG:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/bbe4b3dca1d9f535c670958e7f6a5e5f220d2bae/878-ng-common-utilities/src/main/java/io/harness/PolicyConstants.java#L10)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: public static final class can you make it this for constants, I am fine with thisas well though
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-06 05:57 UTC, archit-harness requested changes
> Reviewed 2 of 6 files at r2, 2 of 10 files at r4, 1 of 3 files at r10, 4 of 54 files at r11, 2 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 49 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiTaskExecutable.java` line 25 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4cFRa9eiTYsvUNqLQ:-NL4cFRa9eiTYsvUNqLR:b-5vt5k2) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiTaskExecutable.java#L25)):*
> ```Java
> public abstract class CiTaskExecutable<R extends ResponseData>
>     implements TaskExecutableWithRbac<StepElementParameters, R> {
>   @Inject OpaServiceClient opaServiceClient;
> ```

as we added OpaServiceClient, please ask ci team to test it out, plus you should do for a simple step in pr env
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java` line 22 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4dPGM11vB0awGQmzw:-NL4dPGM11vB0awGQmzx:b-jniig7) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java#L22)):*
> ```Java
> import java.util.Map;
> 
> public abstract class TaskExecutableWithCapabilities<R extends ResponseData>
> ```

add comment and owned by

comment mentioning  it has rbac and rollback
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java` line 39 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4bp2k1MZ0bU8wz-9j:-NL4bp2k1MZ0bU8wz-9k:bjzzmoi) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java#L39)):*
> ```Java
>   }
> 
>   public StepResponse postValidate(Ambiance ambiance, StepElementParameters stepParameters, StepResponse stepResponse) {
> ```

can we rename to postTaskValidate and add comments to this method what it is doing. and as its only doing validation it should not return stepResponse and return boolean or void
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStep.java` line 56 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4cvdvAdqsEaCGniFl:-NL4cvdvAdqsEaCGniFm:b-arf6st) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStep.java#L56)):*
> ```Java
> @OwnedBy(CDC)
> @Slf4j
> public class HttpStep extends PipelineTaskExecutable<HttpStepResponse> {
> ```

As you extended this one but it doesn't have rollback in pipelineTaskExecutable
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java` line 43 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d1vqAPysiUji11ap:-NL4d1vqAPysiUji11aq:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java#L43)):*
> ```Java
> 
> @OwnedBy(CDC)
> public class JiraCreateStep extends PipelineTaskExecutable<JiraTaskNGResponse> {
> ```

same for this
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/update/JiraUpdateStep.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d3_c462yXCZhbOC4:-NL4d3_c462yXCZhbOC5:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/update/JiraUpdateStep.java#L41)):*
> ```Java
> 
> @OwnedBy(CDC)
> public class JiraUpdateStep extends PipelineTaskExecutable<JiraTaskNGResponse> {
> ```

same for this
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d5X3-GssOKuAGoud:-NL4d5X3-GssOKuAGoue:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java#L41)):*
> ```Java
> 
> @OwnedBy(CDC)
> public class ServiceNowCreateStep extends PipelineTaskExecutable<ServiceNowTaskNGResponse> {
> ```

same
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/importset/ServiceNowImportSetStep.java` line 48 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d6Yh27rdd2hUY2hV:-NL4d6Yh27rdd2hUY2hW:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/importset/ServiceNowImportSetStep.java#L48)):*
> ```Java
> 
> @OwnedBy(CDC)
> public class ServiceNowImportSetStep extends PipelineTaskExecutable<ServiceNowTaskNGResponse> {
> ```

same
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d8v36g4QMMxoODAn:-NL4d8v36g4QMMxoODAo:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java#L41)):*
> ```Java
> 
> @OwnedBy(CDC)
> public class ServiceNowUpdateStep extends PipelineTaskExecutable<ServiceNowTaskNGResponse> {
> ```

same
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java` line 54 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d9iPAlCXbXidx3WS:-NL4d9iPAlCXbXidx3WT:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java#L54)):*
> ```Java
> 
> @OwnedBy(CDC)
> @Slf4j
> ```

same


<!-- Sent from Reviewable.io -->

2023-01-06 06:20 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 53 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/executables/CdTaskExecutable.java` line 29 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4YRjr0-IdHuGCMtgn:-NL4_zXG6E-Vki29eAMt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/125-cd-nextgen/src/main/java/io/harness/cdng/executables/CdTaskExecutable.java#L29)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: better to have constants on the left side of comparison as a good practice
</blockquote></details>

done
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java` line 22 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4dPGM11vB0awGQmzw:-NL4hUwz7Bv0pPUWxJ6T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment and owned by

comment mentioning  it has rbac and rollback
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java` line 39 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4bp2k1MZ0bU8wz-9j:-NL4if8-8oruwUBAKK3h:bnl1diu) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/878-ng-common-utilities/src/main/java/io/harness/steps/executable/TaskExecutableWithCapabilities.java#L39)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename to postTaskValidate and add comments to this method what it is doing. and as its only doing validation it should not return stepResponse and return boolean or void
</blockquote></details>

policy evaluation is actually updating step response based on the result of policy evaluation, if it fails, we are updating the status and adding failure info as well in the step response, so i thought it would be easier to just return updated step response
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStep.java` line 56 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4cvdvAdqsEaCGniFl:-NL4h25jACiC7ohZvRvy:bdusqts) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStep.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

As you extended this one but it doesn't have rollback in pipelineTaskExecutable
</blockquote></details>

Corrected by having pipelineTaskExecutable extend TaskExecutableWithCapabilities
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java` line 43 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d1vqAPysiUji11ap:-NL4h74_C1J9N4dHiPoy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create/JiraCreateStep.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same for this
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/update/JiraUpdateStep.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d3_c462yXCZhbOC4:-NL4h80U-dz08dYaiXw3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/update/JiraUpdateStep.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same for this
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d5X3-GssOKuAGoud:-NL4h8a70xHkm12IffPR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/importset/ServiceNowImportSetStep.java` line 48 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d6Yh27rdd2hUY2hV:-NL4h9Fr-OOVXfYkIH3L:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/importset/ServiceNowImportSetStep.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d8v36g4QMMxoODAn:-NL4h9mL5T7OnKnZK3xV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java` line 54 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4d9iPAlCXbXidx3WS:-NL4hAcD9Uuw5xIA_jeZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-01-06 07:58 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 53 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiTaskExecutable.java` line 25 at r12](https://reviewable.io/reviews/harness/harness-core/42007#-NL4cFRa9eiTYsvUNqLQ:-NL5401iA6TiuDwcc6qb:but7bvi) ([raw file](https://github.com/harness/harness-core/blob/2e59f165f2188ccbd25f2f650cedb52c81fd86f9/332-ci-manager/service/src/main/java/io/harness/ci/execution/executable/CiTaskExecutable.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as we added OpaServiceClient, please ask ci team to test it out, plus you should do for a simple step in pr env
</blockquote></details>

Have reverted changes in CI Manager as the only CI step implementing TaskExecutable is not user-facing. So, now there are no changes in CI Manager in this PR.


<!-- Sent from Reviewable.io -->

2023-01-06 09:25 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 10 file(s) to review. 8. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/executables/CdTaskExecutable.java` line 24 at r14](https://reviewable.io/reviews/harness/harness-core/42007#-NL5NkeP9ACfdXJE5LYC:-NL5Odep7gWruptDUg5k:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2f5e17e93d606d9ab34ef74655eed6b3ab0ed449/125-cd-nextgen/src/main/java/io/harness/cdng/executables/CdTaskExecutable.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: CDC
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-01-06 09:50 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 5 files at r1, 3 of 10 files at r4, 39 of 54 files at r11, 4 of 9 files at r13, 1 of 3 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 4 file(s) to review. 8. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-06 10:32 UTC, namanvermah approved these changes
> Reviewed 6 of 9 files at r13, 1 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-06 10:37 UTC, mohitg0795 approved these changes
> Reviewed 1 of 5 files at r1, 2 of 6 files at r2, 5 of 10 files at r4, 1 of 3 files at r10, 46 of 54 files at r11, 6 of 9 files at r13, 3 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-06 10:40 UTC, mohitg0795 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-09 04:57 UTC, senjucanon2 approved these changes
> Reviewed 1 of 3 files at r10, 45 of 54 files at r11, 6 of 9 files at r13, 1 of 3 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 1 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-09 05:12 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 5 files at r1, 2 of 6 files at r2, 5 of 10 files at r4, 1 of 3 files at r10, 45 of 54 files at r11, 6 of 9 files at r13, 3 of 3 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42007)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-09 05:48 UTC, merged