[fix]: [CDS-49411]: add access permission validation in service/env/envGroup
harness/harness-core pull request #42012
Opened 2022-12-27 12:59 UTC by tchaurasiya

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2022-12-29 05:15 UTC, hingerabhinav commented on 125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/CdStepParametersUtils.java
> +        io.harness.accesscontrol.acl.api.ResourceScope.of(AmbianceUtils.getAccountId(ambiance),
can we import ResourceScope directly?

2022-12-29 05:17 UTC, hingerabhinav commented on 125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/CdStepParametersUtils.java
> +  public void checkRuntimeAccessPermissionOrThrow(Ambiance ambiance, String resourceType, String identifier,
we can change this method name since we pass the permission to checked as well.

2023-01-05 15:15 UTC, tchaurasiya reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42012)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/CdStepParametersUtils.java` line 80 at r3](https://reviewable.io/reviews/harness/harness-core/42012#-NKNvHGvI6zUAXFd18y5-r3-80:-NL1V5CODCHHzRN-ZQBI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38b86a83fcfb0825d37fff0dae08fb3431b76a22/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/CdStepParametersUtils.java#L80)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

we can change this method name since we pass the permission to checked as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-05 15:15 UTC, tchaurasiya commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/CdStepParametersUtils.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/42012#-NKNvHGvI6zUAXFd18y5-r3-92:-NL1V6XO5LGWtJM7vwPJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38b86a83fcfb0825d37fff0dae08fb3431b76a22/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/CdStepParametersUtils.java#L92)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

can we import ResourceScope directly?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-06 06:06 UTC, hingerabhinav requested changes
> Reviewed 1 of 2 files at r1, 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42012)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java` line 200 at r5](https://reviewable.io/reviews/harness/harness-core/42012#-NL4fmaz2k5yTgP1ffRF:-NL4fmaz2k5yTgP1ffRG:b-tnou6t) ([raw file](https://github.com/harness/harness-core/blob/737aad342bcce1cf4005faf676b656b71d0cce6c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java#L200)):*
> ```Java
>             executionPrincipalInfo.getPrincipalType());
>     accessControlClient.checkForAccessOrThrow(Principal.of(principalType, principal),
>         ResourceScope.of(AmbianceUtils.getAccountId(ambiance), AmbianceUtils.getOrgIdentifier(ambiance),
> ```

we should create identifier ref using envGroupRef and use that to get Resource Scope. This is needed for env groups at org/account level


<!-- Sent from Reviewable.io -->

2023-01-09 09:51 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java
> +      String exceptionMessage, AccessControlClient accessControlClient) {
Does this handle org/account level environment groups ?
Can we also add NotNull annotations for usage of this generic method ?

2023-01-10 12:06 UTC, yogesh-chauhan requested changes

2023-01-10 12:06 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java
> +  public void checkPermissionOrThrow(@NonNull Ambiance ambiance, @NotNull String resourceType,
Lets move this to multi deployment step itself

2023-01-10 15:54 UTC, tchaurasiya commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java` line 189 at r6](https://reviewable.io/reviews/harness/harness-core/42012#-NLMPVetSRoSdDQ51hFc-r6-189:-NLRNryM6P_p8IOV2GA8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/93918e0fff65813968ddd274efbd4692ff8456dd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java#L189)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets move this to multi deployment step itself
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 15:54 UTC, tchaurasiya reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42012)* status: 7 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java` line 189 at r5](https://reviewable.io/reviews/harness/harness-core/42012#-NL1Uxo9wpey5x8VDlnR-r5-189:-NLMKOXz8aK399UYNk4a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/737aad342bcce1cf4005faf676b656b71d0cce6c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java#L189)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Does this handle org/account level environment groups ?
Can we also add NotNull annotations for usage of this generic method ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java` line 200 at r5](https://reviewable.io/reviews/harness/harness-core/42012#-NL4fmaz2k5yTgP1ffRF:-NLMKPvy0iZzIYzJSkr-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/737aad342bcce1cf4005faf676b656b71d0cce6c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentStepsUtils.java#L200)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

we should create identifier ref using envGroupRef and use that to get Resource Scope. This is needed for env groups at org/account level
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 17:06 UTC, tchaurasiya commented
trigger messagecheck

2023-01-10 17:26 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 6 files at r4, 5 of 7 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42012)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 01:16 UTC, hingerabhinav approved these changes
> Reviewed 2 of 6 files at r4, 5 of 7 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42012)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-11 03:55 UTC, merged