feat: [CDS-46922]: fixes for supporting org/acc level ser/env
harness/harness-core pull request #42198
Opened 2023-01-04 03:18 UTC by hingerabhinav

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-09 09:47 UTC, yogesh-chauhan requested changes

2023-01-09 09:47 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java
> +  @ExposeInternalException(withStackTrace = true)
what is the purpose of this ? Looks ike this was meant for interservice calls

2023-01-09 09:47 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
> +    String[] envRefSplit = StringUtils.split(requestEnvironment.getIdentifier(), ".", MAX_RESULT_THRESHOLD_FOR_SPLIT);
This splitting logic is already done by IdentifierRefHelper.getIdentifierRef

2023-01-09 09:47 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
> +    if (envRefSplit != null && envRefSplit.length == 2) {
Also, do we really need to support refs while CRUD ? Refs should be supported mostly from other entities which refer to the environment

2023-01-10 11:35 UTC, hingerabhinav commented on 125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java
> +  void checkForVariablesAccessOrThrow(Ambiance ambiance, NGServiceConfig serviceConfig, String serviceRef) {
check existing methods usage

2023-01-13 14:33 UTC, closed without merging