fix: [PLG-1496]: Added visitor token to signup complete
harness/harness-core pull request #42231
Opened 2023-01-04 16:32 UTC by devinder-harness

## Describe your changes
Added visitor token to signup complete call to track `mutiny visitor token`
JIRA 
https://harness.atlassian.net/browse/PLG-1496

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-12 20:28 UTC, neelam-harness requested changes

2023-01-12 20:28 UTC, neelam-harness commented on 920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java
> +      trackProperties.put("visitor_token", visitorToken);
Can we make `"name"`,  `"ga_client_id"`, and `"visitor_token"` as a constant variables similar to `EMAIL` instead of hard-coding ?

2023-01-13 10:33 UTC, devinder-harness commented on 920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java
> +      trackProperties.put("visitor_token", visitorToken);
updated

2023-01-13 10:59 UTC, vtxorxwitty approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-13 19:30 UTC, neelam-harness submitted a review, later dismissed

2023-01-13 19:34 UTC, thomas-grasman approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-16 09:27 UTC, kapil-harness approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-16 09:28 UTC, kapil-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-16 11:20 UTC, inderschera submitted a review, later dismissed
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-16 21:47 UTC, neelam-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231#-:-NLwYA0J6rS_rGVP2WPo:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:20 UTC, inderschera approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:25 UTC, yogesh-chauhan approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:38 UTC, devinder-harness reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231#-:-NM8ojUWA7nWiveXkw_K:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:40 UTC, vtxorxwitty approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:47 UTC, devinder-harness reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231#-:-NM8pxrE5_vVSmHGMJ4H:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:48 UTC, devinder-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 

___
*[`920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java` line 689 at r1](https://reviewable.io/reviews/harness/harness-core/42231#-NKxc497eqkZt4wyqooZ-r1-689:-NM8qoFm6jaMkcnRRE7a:b-qssecl) ([raw file](https://github.com/harness/harness-core/blob/9c66431d52a68b8decd20922e2b7ded8dbd58bcf/920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java#L689)):*
<details><summary><i>Previously, devinder-harness wrote…</i></summary><blockquote>

updated
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2023-01-19 11:49 UTC, devinder-harness reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231#-:-NM8r6wpC6RSJEvGfG_-:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:49 UTC, devinder-harness reviewed
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42231)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-19 11:52 UTC, merged