[CDS-47125]: Force deletion of services.
harness/harness-core pull request #42269
Opened 2023-01-05 10:02 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-09 06:51 UTC, yogesh-chauhan requested changes

2023-01-09 06:51 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/ServiceForceDeleteEvent.java
> +import lombok.Getter;
add space here for readability

2023-01-09 06:51 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/ServiceForceDeleteEvent.java
> +  private ServiceEntity service;
add space here for readability

2023-01-09 06:51 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/ServiceForceDeleteEvent.java
> +    return new ProjectScope(accountIdentifier, service.getOrgIdentifier(), service.getProjectIdentifier());
scope need not be project, it can be org/account depending on where the service existed

2023-01-09 06:51 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java
> +      Long version, Boolean forceDelete) {
lets use primitive boolean

2023-01-09 06:51 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java
> +  NGSettingsClient settingsClient;
add space for readability

2023-01-09 06:51 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java
>  public class ServiceEntityManagementServiceImpl implements ServiceEntityManagementService {
Lets get rid of this class. It not needed. We should directly call ServiceEntityServiceImpl from the service resource.

2023-01-09 06:51 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java
>  public class ServiceEntityManagementServiceImpl implements ServiceEntityManagementService {
Ownedby = CDC

2023-01-09 06:51 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +    boolean deleted = serviceEntityManagementService.deleteService(account, org, project, service, "ifMatch", false);
why are we not supporting force deletion here ?

2023-01-10 10:25 UTC, vivekkarnatiharness commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/42269#-NL0NZvH2nN_C66i2ZaO-r1-89:-NLQCaU_4qqxzqTmUlL7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0191d9440928748f880d48084a23726a4918989b/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java#L89)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why are we not supporting force deletion here ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 12:26 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ProjectServicesApiImpl.java` line 51 at r4](https://reviewable.io/reviews/harness/harness-core/42269#-NLQdBg1-DajKr2zeoys:-NLQdBg1-DajKr2zeoyt:bxv8o5) ([raw file](https://github.com/harness/harness-core/blob/b7f21280116a0525c12f355b2dc9f443a7bd8eb4/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ProjectServicesApiImpl.java#L51)):*
> ```Java
>   @Override
>   public Response deleteService(@OrgIdentifier String org, @ProjectIdentifier String project,
>       @ResourceIdentifier String service, @AccountIdentifier String account, Boolean forceDelete) {
> ```

Lets convert to primitive here only 
for eg. `Boolean.TRUE == forceDelete` 


<!-- Sent from Reviewable.io -->

2023-01-10 12:27 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/42269#-NLQdUsyCAV88sEErLmb:-NLQdUsz-jKxgOyTpEH1:b-p6e1h5) ([raw file](https://github.com/harness/harness-core/blob/b7f21280116a0525c12f355b2dc9f443a7bd8eb4/120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java#L72)):*
> ```Java
>     return isForceDeleteFFEnabled && isForceDeleteEnabledBySettings;
>   }
>   @VisibleForTesting
> ```

Lets get rid of `VisibleForTesting`, we should write tests for the public method only


<!-- Sent from Reviewable.io -->

2023-01-10 12:28 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 45 at r4](https://reviewable.io/reviews/harness/harness-core/42269#-NLQdldR1D3dG_oGF0-x:-NLQdldR1D3dG_oGF0-y:b-jilp0m) ([raw file](https://github.com/harness/harness-core/blob/b7f21280116a0525c12f355b2dc9f443a7bd8eb4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L45)):*
> ```Java
> 
>   boolean delete(String accountId, String orgIdentifier, String projectIdentifier, String serviceIdentifier,
>       Long version, Boolean forceDelete);
> ```

this should be primitive


<!-- Sent from Reviewable.io -->

2023-01-10 12:28 UTC, yogesh-chauhan reviewed
> Reviewed 6 of 13 files at r1, 2 of 5 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 04:18 UTC, tchaurasiya commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/42269#-NLU26L13ihb1_26gRKb:-NLU26L13ihb1_26gRKc:b-crv8mv) ([raw file](https://github.com/harness/harness-core/blob/c1d2b4cd926093c5bb2b910f0fa348bd259d933b/120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java#L43)):*
> ```Java
>   private final AccountClient accountClient;
> 
>   NGSettingsClient settingsClient;
> ```

nit: lets mark it private final


<!-- Sent from Reviewable.io -->

2023-01-11 04:22 UTC, tchaurasiya commented
*[`120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceResourceTest.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/42269#-NLU3-PB0qSA9_EkGOry:-NLU3-PB0qSA9_EkGOrz:bacmfqw) ([raw file](https://github.com/harness/harness-core/blob/c1d2b4cd926093c5bb2b910f0fa348bd259d933b/120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceResourceTest.java#L174)):*
> ```Java
>         .when(serviceEntityManagementService)
>         .deleteService("ACCOUNT_ID", serviceRequestDTO.getOrgIdentifier(), serviceRequestDTO.getProjectIdentifier(),
>             serviceRequestDTO.getIdentifier(), null, );
> ```

Seems like a miss!!


<!-- Sent from Reviewable.io -->

2023-01-11 04:32 UTC, tchaurasiya commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 359 at r5](https://reviewable.io/reviews/harness/harness-core/42269#-NLU4z2IDdvKSARvP15F:-NLU4z2IDdvKSARvP15G:bhcuumj) ([raw file](https://github.com/harness/harness-core/blob/c1d2b4cd926093c5bb2b910f0fa348bd259d933b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L359)):*
> ```Java
>               serviceEntityRetrieved.getProjectIdentifier(), serviceEntityRetrieved));
>         } else {
>           outboxService.save(new ServiceDeleteEvent(accountId, serviceEntityRetrieved.getOrgIdentifier(),
> ```

@vivekkarnatiharness Lets remember to make changes in this method io.harness.ng.core.events.ServiceDeleteEvent#getResourceScope to handle org/account level service.


<!-- Sent from Reviewable.io -->

2023-01-11 04:33 UTC, tchaurasiya reviewed
> Reviewed 5 of 13 files at r1, 1 of 5 files at r2, 1 of 5 files at r3, 1 of 2 files at r4, 3 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 04:33 UTC, tchaurasiya reviewed
> Reviewed 1 of 13 files at r1, 1 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 04:38 UTC, tchaurasiya commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/42269#-NLU60ZC0-U8x4eh6ms2:-NLU60ZD5T8XsJrW9YFB:b-c4wpxv) ([raw file](https://github.com/harness/harness-core/blob/c1d2b4cd926093c5bb2b910f0fa348bd259d933b/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java#L50)):*
> ```Java
>   @Override
>   public Response deleteAccountScopedService(
>       @ResourceIdentifier String service, @AccountIdentifier String account, Boolean forceDelete) {
> ```

@yogesh-chauhan Just for information, Why no argument in this class are primitibe?


<!-- Sent from Reviewable.io -->

2023-01-11 04:38 UTC, tchaurasiya reviewed
> Reviewed 1 of 5 files at r3, 3 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-11 05:23 UTC, yogesh-chauhan reviewed
> Reviewed 6 of 7 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/42269#-NLU60ZC0-U8x4eh6ms2:-NLUGdfTCFG45YlI7d6A:b-v87tmc) ([raw file](https://github.com/harness/harness-core/blob/c1d2b4cd926093c5bb2b910f0fa348bd259d933b/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java#L50)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

@yogesh-chauhan Just for information, Why no argument in this class are primitibe?
</blockquote></details>

I think thats just the limitation of the openapi tool that we use to convert the yaml specs to interfaces


<!-- Sent from Reviewable.io -->

2023-01-11 05:26 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-11 05:27 UTC, yogesh-chauhan commented
trigger ti0, ti1, ti2, ti3, ti4

2023-01-11 05:28 UTC, yogesh-chauhan commented
trigger messagecheck

2023-01-11 05:32 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        - schema:
Instead of repeating this Query Parameter 3 times, we can create a common parameter type and reference it like it is done for AccountHeader

2023-01-11 05:43 UTC, tchaurasiya approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-12 10:57 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> -      description: Deletes the requested service
why was this line removed? it is the description for the API

2023-01-12 10:59 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +
remove this blank line as well

2023-01-12 11:23 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java` line 891 at r8](https://reviewable.io/reviews/harness/harness-core/42269#-NL_i7AdB206jRK_VOdl:-NL_i7AdB206jRK_VOdm:b-iit703) ([raw file](https://github.com/harness/harness-core/blob/8e58d5e8398cf44d90d64e8b02579e51aff28f1e/127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java#L891)):*
> ```Java
>         .thenReturn(Page.empty());
>     boolean delete = serviceEntityService.delete("ACCOUNT_ID", "ORG_ID", "PROJECT_ID", id, 0L, true);
>     verify(entitySetupUsageService, times(0))
> ```

nit:  never() instead of times(0)


<!-- Sent from Reviewable.io -->

2023-01-12 11:24 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 11:27 UTC, mankrit-singh reviewed
> Reviewed 5 of 13 files at r1, 1 of 5 files at r2, 1 of 5 files at r3, 7 of 7 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 11:28 UTC, mankrit-singh approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-12 16:13 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 3 of 5 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 17:08 UTC, RajBaviskar approved these changes
> Reviewed 4 of 13 files at r1, 1 of 5 files at r2, 6 of 7 files at r5, 1 of 1 files at r6, 3 of 5 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 17:52 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-12 18:31 UTC, vaibhav-si approved these changes
> Reviewed 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42269)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-13 03:09 UTC, merged