feat: [cds-47127]: basic code force delete in case of deletetemplate
harness/harness-core pull request #42315
Opened 2023-01-06 09:44 UTC by vivekkarnatiharness

## Describe your changes
Adding a query param for force delete in case of templates
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-09 06:56 UTC, yogesh-chauhan requested changes
Lets get clarity on old git sync changes. For the rest, I have requested some changes

2023-01-09 06:56 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java
> +    if (!forceDelete) {
why do we need a not condition here?

can we just do

if (forceDelete) {send force delete event}
else {send delete event}

2023-01-09 06:56 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java
> +      if (!forceDelete) {
same comment as above

2023-01-09 06:56 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/events/TemplateForceDeleteEvent.java
> +  public TemplateForceDeleteEvent(String accountIdentifier, String orgIdentifier, String projectIdentifier,
This can be achieved using @AllArgsConstructor from lombok

2023-01-09 06:56 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java
> +        isNumeric("ifMatch") ? parseLong("ifMatch") : null, comments, false);
we should support force delete here also

2023-01-11 14:25 UTC, utkarshchoubey-harness reviewed
> Reviewed 2 of 9 files at r1, 4 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42315)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 563 at r3](https://reviewable.io/reviews/harness/harness-core/42315#-NLWCZ2bAekhVDSakDXt:-NLWCZ2bAekhVDSakDXu:br28lot) ([raw file](https://github.com/harness/harness-core/blob/4f398919761d3ef2e5b7adcde386b860e3c3af94/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L563)):*
> ```Java
>     boolean lastUpdatedTemplateDeleted = false;
>     for (TemplateEntity templateEntity : templateToDeleteList) {
>       // have to ask yogesh regarding this
> ```

nit remove this comment
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 588 at r3](https://reviewable.io/reviews/harness/harness-core/42315#-NLWChys8GDpi3q3JMAx:-NLWChyt9ISR6Cr6g59N:b-hzwwey) ([raw file](https://github.com/harness/harness-core/blob/4f398919761d3ef2e5b7adcde386b860e3c3af94/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L588)):*
> ```Java
>     comments = getActualComments(accountId, orgIdentifier, projectIdentifier, comments);
>     // find the given template version in the list
>     if (!forceDelete) {
> ```

nit make if (forceDelete) {
} else { } same as suggested by Yogesh


<!-- Sent from Reviewable.io -->

2023-01-11 14:25 UTC, utkarshchoubey-harness commented on 840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java
> +        isNumeric("ifMatch") ? parseLong("ifMatch") : null, comments, false);
+1

2023-01-12 03:04 UTC, vivekkarnatiharness commented
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 360 at r2](https://reviewable.io/reviews/harness/harness-core/42315#-NL6gjZMqTAqzfB2stGk-r2-360:-NLYvtzBCFIRNx_JDJH2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d0a22dda06e03507c550c28f208878ddad1ee58f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L360)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why do we need a not condition here?

can we just do

if (forceDelete) {send force delete event}
else {send delete event}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-12 03:04 UTC, vivekkarnatiharness commented
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 376 at r2](https://reviewable.io/reviews/harness/harness-core/42315#-NL6gjZMqTAqzfB2stGk-r2-376:-NLYvv8P2QA3vYXhyLq1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d0a22dda06e03507c550c28f208878ddad1ee58f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L376)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-12 03:04 UTC, vivekkarnatiharness commented
*[`840-template-service/src/main/java/io/harness/template/events/TemplateForceDeleteEvent.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/42315#-NL6gjZMqTAqzfB2stGl-r2-31:-NLYvw9DEkD_auE_4rF9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d0a22dda06e03507c550c28f208878ddad1ee58f/840-template-service/src/main/java/io/harness/template/events/TemplateForceDeleteEvent.java#L31)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This can be achieved using @AllArgsConstructor from lombok
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-12 03:11 UTC, vivekkarnatiharness commented
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 588 at r3](https://reviewable.io/reviews/harness/harness-core/42315#-NLWChys8GDpi3q3JMAx:-NLYxQe8DqV-HO-OGPp-:b-m9nctz) ([raw file](https://github.com/harness/harness-core/blob/4f398919761d3ef2e5b7adcde386b860e3c3af94/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L588)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

nit make if (forceDelete) {
} else { } same as suggested by Yogesh
</blockquote></details>

No else statement is present ,so not doing this


<!-- Sent from Reviewable.io -->

2023-01-12 06:43 UTC, yogesh-chauhan requested changes

2023-01-12 06:43 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/events/TemplateForceDeleteEvent.java
> +    if (templateEntity.getTemplateScope().equals(Scope.PROJECT)) {
constants should be on the left side of the comparison

2023-01-12 06:43 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/gitsync/TemplateEntityGitSyncHandler.java
> +          "", false);
don't we need to support force delete here ?

2023-01-12 11:26 UTC, yogesh-chauhan commented
*[`840-template-service/src/main/java/io/harness/template/gitsync/TemplateEntityGitSyncHandler.java` line 112 at r4](https://reviewable.io/reviews/harness/harness-core/42315#-NL5SqVgtPFiqX4gVrAQ-r4-112:-NL_icULEn-_RX7jdZvo:b-xnx8v5) ([raw file](https://github.com/harness/harness-core/blob/cebe7e890d097d744bc8aa3cff92b3293f18a113/840-template-service/src/main/java/io/harness/template/gitsync/TemplateEntityGitSyncHandler.java#L112)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

don't we need to support force delete here ?
</blockquote></details>

This is old git sync. As discussed, we do not need to support force deletion here


<!-- Sent from Reviewable.io -->

2023-01-12 11:28 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 9 files at r1, 2 of 7 files at r2, 1 of 1 files at r3, 7 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42315)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-12 16:23 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 9 files at r1, 2 of 7 files at r2, 2 of 13 files at r4, 5 of 8 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42315)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-12 17:53 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42315)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-13 03:10 UTC, merged