[STO-5353]: Add RBAC for Ticket Service
harness/harness-core pull request #42399
Opened 2023-01-09 16:18 UTC by chris-harness

Adds new RBAC for the new Ticket Service.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-09 16:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=42399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=42399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=42399) it.</sub>

2023-01-09 16:23 UTC, chris-harness commented
trigger messagecheck

2023-01-09 16:42 UTC, r0610205 approved these changes

2023-01-09 16:46 UTC, atmollo-harness submitted a review, later dismissed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42399)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-09 17:59 UTC, chris-harness commented
trigger messagecheck

2023-01-09 20:19 UTC, chris-harness commented
trigger messagecheck

2023-01-11 08:07 UTC, Jimit09Gandhi approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42399)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-13 05:33 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42399)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 4 at r3](https://reviewable.io/reviews/harness/harness-core/42399#-NLdbSNSDhu0F7FmDX4-:-NLdbSNSDhu0F7FmDX40:b-fqf43i) ([raw file](https://github.com/harness/harness-core/blob/1ca73c5e70d9479e861e7951a96e6f557a869d47/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L4)):*
> ```YAML
> name: rolesConfiguration
> version: 43
> roles:
> ```

Can u rebase the latest versions is 41. So new version should be 42.


<!-- Sent from Reviewable.io -->

2023-01-13 05:37 UTC, reetika04 requested changes

2023-01-13 05:37 UTC, reetika04 commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +version: 43
42?

2023-01-13 14:14 UTC, Jimit09Gandhi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42399#-:-NLfTkaM8y51B4f0yCyC:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-13 14:15 UTC, chris-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +version: 43
Fixed

2023-01-13 16:12 UTC, merged