feat: [PL-30098]: RBAC for Streaming Destination
harness/harness-core pull request #42598
Opened 2023-01-13 08:59 UTC by reetika04

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-13 09:37 UTC, nishantsaini20 approved these changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/42598#-NLeUEfq6DGFit9HRnQc:-NLeUEfq6DGFit9HRnQd:byotaq4) ([raw file](https://github.com/harness/harness-core/blob/2634694b13b98460828eebf9daa5437dc407ffae/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L123)):*
> ```YAML
>   - identifier: IAC_STACK
>     permissionKey: stack
>   - identifier: STREAMINGDESTINATION
> ```

STREAMING_DESTINATION


<!-- Sent from Reviewable.io -->

2023-01-13 10:29 UTC, meenakshi-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: STREAMINGDESTINATION
Do we not follow STREAMING_DESTINATION pattern for identifier?

2023-01-13 10:35 UTC, meenakshi-harness commented on platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/streamingdestination/StreamingDestinationResourceImpl.java
> +    return "STREAMINGDESTINATION";
create constant for this

2023-01-13 10:50 UTC, reetika04 commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: STREAMINGDESTINATION
No we don’t since it is a single entity. Trying to keep it consistent with other resources.

2023-01-13 11:00 UTC, meenakshi-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: STREAMINGDESTINATION
I see different patterns adopted like for ENVIRONMENT_GROUP. STREAMING_DESTINATION is more readable. 
It will be aligned with pattern in  `core_streamingDestination_view`. what you think?

2023-01-13 11:58 UTC, nishantsaini20 approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-13 12:04 UTC, meenakshi-harness approved these changes
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-14 08:58 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: :shipit: complete! ✓

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/42598#-NLjTbdu14B6dm6swItt:-NLjTbdu14B6dm6swItu:btnpkic) ([raw file](https://github.com/harness/harness-core/blob/0b02728fa7b899e2caae901f2a70efae8671840d/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L3)):*
> ```YAML
> # Any edit in this file should accompany an increment in version.
> name: permissionsConfiguration
> version: 44
> ```

Rebase PR as this  https://github.com/harness/harness-core/pull/42399/files is merged now.


<!-- Sent from Reviewable.io -->

2023-01-14 16:00 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: :shipit: complete! ✓

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/streamingdestination/StreamingDestinationResourceImpl.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/42598#-NLl-F5E1Ys4icdlUoVc:-NLl-F5E1Ys4icdlUoVd:b-2ozk3t) ([raw file](https://github.com/harness/harness-core/blob/0b02728fa7b899e2caae901f2a70efae8671840d/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/streamingdestination/StreamingDestinationResourceImpl.java#L58)):*
> ```Java
>   public Map<ScopeLevel, EnumSet<ValidatorType>> getSelectorKind() {
>     return ImmutableMap.of(ScopeLevel.ACCOUNT,
>         EnumSet.of(BY_RESOURCE_IDENTIFIER, BY_RESOURCE_TYPE, BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES));
> ```

Since the resource is only available at Account Scope. Is BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES relevant?


<!-- Sent from Reviewable.io -->

2023-01-16 06:52 UTC, reetika04 reviewed
> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-16 06:53 UTC, reetika04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/42598#-NLjTbdu14B6dm6swItt:-NLtLafwAhllmAd7vPwA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b02728fa7b899e2caae901f2a70efae8671840d/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L3)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Rebase PR as this  https://github.com/harness/harness-core/pull/42399/files is merged now.
</blockquote></details>

Done.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/streamingdestination/StreamingDestinationResourceImpl.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/42598#-NLl-F5E1Ys4icdlUoVc:-NLtLcZD1dtI7kaOQ-Ra:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b02728fa7b899e2caae901f2a70efae8671840d/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/streamingdestination/StreamingDestinationResourceImpl.java#L58)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Since the resource is only available at Account Scope. Is BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES relevant?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-16 07:07 UTC, Jimit09Gandhi submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598#-:-NLtOqeE3jv31EDWo0hT:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-16 07:12 UTC, meenakshi-harness approved these changes
> Reviewed 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-16 07:36 UTC, reetika04 commented
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)_ status: :shipit: complete! ✓
> 
> _[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/streamingdestination/StreamingDestinationResourceImpl.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/42598#-NLl-F5E1Ys4icdlUoVc:-NLl-F5E1Ys4icdlUoVd:b-2ozk3t) ([raw file](https://github.com/harness/harness-core/blob/0b02728fa7b899e2caae901f2a70efae8671840d/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/streamingdestination/StreamingDestinationResourceImpl.java#L58)):_
> 
> > ```java
> >   public Map<ScopeLevel, EnumSet<ValidatorType>> getSelectorKind() {
> >     return ImmutableMap.of(ScopeLevel.ACCOUNT,
> >         EnumSet.of(BY_RESOURCE_IDENTIFIER, BY_RESOURCE_TYPE, BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES));
> > ```
> 
> Since the resource is only available at Account Scope. Is BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES relevant?

No, we would need it to populate the resource in the UI.

2023-01-16 07:40 UTC, Jimit09Gandhi approved these changes
> Reviewed 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42598)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-16 08:56 UTC, reetika04 commented
trigger ti1

2023-01-17 05:01 UTC, merged