feat: [DEL-5801]: NG Shell task as executable binary
harness/harness-core pull request #42687
Opened 2023-01-16 20:00 UTC by mdmilic

## Describe your changes
Weeding out ShellSciprtTaskNg and it's params out of the rest of 930-delegate-tasks is quite complex. We already had basic shell script task created for initial POC (this is what shell task should actually be), but it was made for CG. I repurposed it as a basic NG Shell script task. It lacks remote execution features like SSH, WinRM, GCP, K8S etc... which we are not interested in anyway. But has all other important features like secret expression evaluation. 

This is not used anywhere yet, but also not even built into old delegates. Size is still quite big, around 265MB even with using all available package level targets. Will need further trimming down of deps once other modules are broken down. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-27 17:59 UTC, gn-harness submitted a review, later dismissed
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-27 19:59 UTC, xingchi-jin submitted a review, later dismissed
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-30 21:30 UTC, raghuAtWings commented
*[`260-delegate/src/main/java/io/harness/serializer/platform/DelegatePlatformRegistrar.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/42687#-NN3_X7Q6o5O85BrJSG8:-NN3_X7Q6o5O85BrJSG9:b-t3qesq) ([raw file](https://github.com/harness/harness-core/blob/ddd233eb57223b9a924002b6a3ca771c870b5a46/260-delegate/src/main/java/io/harness/serializer/platform/DelegatePlatformRegistrar.java#L41)):*
> ```Java
>     kryo.register(DelegateTaskPackage.class, 7150);
>     kryo.register(TaskData.class, 19002);
>     kryo.register(ShellScriptParameters.class, 19463); // This tries to hijack ShellScriptTaskParametersNG
> ```

what does this mean? if we change the number won't the old delegates break?



_Code quote:_
```Java
kryo.register(ShellScriptParameters.class, 19463); // This tries to hijack ShellScriptTaskParametersNG
```


<!-- Sent from Reviewable.io -->

2023-01-30 21:31 UTC, raghuAtWings reviewed
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-01 14:03 UTC, mdmilic reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: 1. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/serializer/platform/DelegatePlatformRegistrar.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/42687#-NN3_X7Q6o5O85BrJSG8:-NNCGOgqAZeNBSbs34cc:b-ssf82l) ([raw file](https://github.com/harness/harness-core/blob/ddd233eb57223b9a924002b6a3ca771c870b5a46/260-delegate/src/main/java/io/harness/serializer/platform/DelegatePlatformRegistrar.java#L41)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what does this mean? if we change the number won't the old delegates break?
</blockquote></details>

No, this registrar is only used by Bijou delegate. I'm essentially registering a different class with the same name so that Manager sends class A, but that gets deserialized to class B that I need. I made sure class B can be deserialized from Class A. This way I can remove features and dependencies from Class A and not need to make any changes to manager. 
Unfortunately this will not work any more until I migrate delegate core to proto. With recent changes to support secret decryption in init container I had to add bunch of Kryo registrars to delegate core, those registrars define this same registration so this now breaks. This was temporary measure until we migrate delegate core to proto. Normally this registrar would only be registered in respective task module (e.g. ShellTask java executable and docker image) and still not be present in existing delegates. 


<!-- Sent from Reviewable.io -->

2023-03-13 15:47 UTC, xingchi-jin requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/42687#-NQQdlv11NyrpEO0PNMp:-NQQdlv11NyrpEO0PNMq:bwfr752) ([raw file](https://github.com/harness/harness-core/blob/f29dcbff37ec779f8dd377d87aac41ff11b7d0d2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java#L47)):*
> ```Java
> 
>     return CommandExecutionResultMapper.from(
>         executor.executeCommandString(parameters.getScript(), items, secretItems, parameters.getSshTimeOut()));
> ```

TBH, i don't understand why ssh timeout was used here ? 



_Code quote:_
```Java
parameters.getSshTimeOut()
```
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java` line 50 at r6](https://reviewable.io/reviews/harness/harness-core/42687#-NQQdQF9284-8S5dTeIz:-NQQdQF9284-8S5dTeJ-:b32oh0l) ([raw file](https://github.com/harness/harness-core/blob/f29dcbff37ec779f8dd377d87aac41ff11b7d0d2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java#L50)):*
> ```Java
>   }
> 
>   private List<String> splitVars(final String vars) {
> ```

why this string processing can be skipped ?
___
*[`delegate/src/main/java/io/harness/taskapps/dockerization/Dockerfile` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/42687#-NQQcIyFAjTSYlEy_OoT:-NQQcIyFAjTSYlEy_OoU:b-h2o4wh) ([raw file](https://github.com/harness/harness-core/blob/ff61af11a9e2addcc4b41f792de12d3210557808/delegate/src/main/java/io/harness/taskapps/dockerization/Dockerfile#L33)):*
> ```Dockerfile
> WORKDIR /opt/harness
> 
> COPY --from=adoptopenjdk/openjdk11:jre-11.0.14_9-ubi-minimal /opt/java/openjdk/ /opt/java/openjdk/
> ```

question only: why delegate is not using base images (with jdk in it) and should we use the base image here? 


<!-- Sent from Reviewable.io -->

2023-03-13 20:02 UTC, mdmilic reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: 24 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/42687#-NQQdlv11NyrpEO0PNMp:-NQRXgAn7CRNawSvi1xV:b-ozp5s0) ([raw file](https://github.com/harness/harness-core/blob/f29dcbff37ec779f8dd377d87aac41ff11b7d0d2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java#L47)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

TBH, i don't understand why ssh timeout was used here ? 
</blockquote></details>

This task is unique for bijou delegate, it's a part of the shell script task for normal delegates that executes shel scripts locally (no winrm, ssh, kubeconfig and some other weirdness that doesn't belong to shell tasks. 
Initial implementation I had was for CG, this PR (besides containerization) moves it to NG. Most of these differences are CG vs NG shell tasks. In CG it was timing out with this SSH Timeout, in NG no timeout, but it gets killed by delegate when it enforces the timeout.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java` line 50 at r6](https://reviewable.io/reviews/harness/harness-core/42687#-NQQdQF9284-8S5dTeIz:-NQRYecK8D1Tw2mfKLyZ:b-kfkg9y) ([raw file](https://github.com/harness/harness-core/blob/f29dcbff37ec779f8dd377d87aac41ff11b7d0d2/930-delegate-tasks/src/main/java/software/wings/delegatetasks/bash/BashScriptTaskHandler.java#L50)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why this string processing can be skipped ?
</blockquote></details>

Same CG vs NG difference. In CG env vars were a single comma separated string (that we parse with this method). In NG it's a proper list of strings (so no parsing)
___
*[`delegate/src/main/java/io/harness/taskapps/dockerization/Dockerfile` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/42687#-NQQcIyFAjTSYlEy_OoT:-NQRYn3g6YI5ODe4u8LE:bew4ew1) ([raw file](https://github.com/harness/harness-core/blob/ff61af11a9e2addcc4b41f792de12d3210557808/delegate/src/main/java/io/harness/taskapps/dockerization/Dockerfile#L33)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

question only: why delegate is not using base images (with jdk in it) and should we use the base image here? 
</blockquote></details>

For some reason`adoptopenjdk/openjdk11:jre-11.0.14_9-ubi-minimal` is quite a bit larger than ubi-minimal + JDK copied to it, thats why I opted for this.


<!-- Sent from Reviewable.io -->

2023-03-14 19:25 UTC, xingchi-jin approved these changes
> Reviewed 2 of 3 files at r3, 6 of 22 files at r4, 13 of 14 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: 1. unresolved discussions. 

___
*[`delegate/src/main/java/io/harness/taskapps/dockerization/Dockerfile` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/42687#-NQQcIyFAjTSYlEy_OoT:-NQW_MgB3wb5CiK8uZjs:b-oges7h) ([raw file](https://github.com/harness/harness-core/blob/7cf19623b4a088da5dab520e0a20a0f5479b2896/delegate/src/main/java/io/harness/taskapps/dockerization/Dockerfile#L33)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

For some reason`adoptopenjdk/openjdk11:jre-11.0.14_9-ubi-minimal` is quite a bit larger than ubi-minimal + JDK copied to it, thats why I opted for this.
</blockquote></details>

good to know !


<!-- Sent from Reviewable.io -->

2023-03-14 22:14 UTC, xingchi-jin approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-14 22:18 UTC, raghuAtWings approved these changes
> Reviewed 2 of 3 files at r3, 6 of 22 files at r4, 13 of 14 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42687)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-14 23:12 UTC, merged