[feat]: [CDS-47037] Asg NG Blue Green Swap Service Delegate  Changes
harness/harness-core pull request #42712
Opened 2023-01-17 10:18 UTC by lovish1999

## Describe your changes
Asg NG Blue Green Swap Service Delegate  Changes 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/42712)

2023-01-17 13:06 UTC, acasian-harness requested changes
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42712)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkJ73DaexWTrPbY1S:-NLzkJ73DaexWTrPbY1T:b-z7bs20) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L192)):*
> ```Java
>             .loadBalancer("lovish-alb")
>             .prodListenerArn(
>                 "arn:aws:elasticloadbalancing:us-east-1:806630305776:listener/app/lovish-alb/4ff4788028fe646f/13c2c1652e75e445")
> ```

why are we hardcoding this? if it'a draft pr - please mark it as draft, we cannot have hardcoded things merged in develop.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkUVTClHziZ2cJDUM:-NLzkUVTClHziZ2cJDUN:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L209)):*
> ```Java
>             .timeoutIntervalInMin(CDStepHelper.getTimeoutInMin(stepParameters))
>             .asgLoadBalancerConfig(asgLoadBalancerConfig)
>             .oldServiceName("lovish2-asg")
> ```

same
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkzsa-3EH0LauK7-a:-NLzkzsa-3EH0LauK7-b:b-5q6i64) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L164)):*
> ```Java
>               .stageTargetGroupArnList(
>                   asgBlueGreenSwapServiceRequest.getAsgLoadBalancerConfig().getStageTargetGroupArnsList())
>               .trafficShifted(true)
> ```

why are always setting to true?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 181 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzlOrk6e7g_3IRmGvo:-NLzlOrlCty-wQwzOvBJ:bjg446d) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L181)):*
> ```Java
>     } catch (Exception e) {
>       swapServiceLogCallback.saveExecutionLog(color(format("Swapping Failed. %n"), LogColor.Red, LogWeight.Bold),
>           LogLevel.ERROR, CommandExecutionStatus.FAILURE);
> ```

hint with explanation - according to new error handler framework.
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 443 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzm9ZH9uIau_xVJmH9:-NLzm9ZI-Kr0adaAIs_K:by3kkjx) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L443)):*
> ```Java
>   TERRAFORM_INPUT_VARIABLES_OBTAIN_TASK_V2(TaskGroup.TERRAFORM, "Terraform Fetch Input variables Task V2"),
>   TERRAFORM_FETCH_TARGETS_TASK_V2(TaskGroup.TERRAFORM, "Terraform Fetch Targets Task V2"),
> ```

what is the change here?
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 672 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzmmCSAbpMmNR6jYHP:-NLzmmCSAbpMmNR6jYHQ:bzcxuuv) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L672)):*
> ```Java
>       }
>       nextToken = describeRulesResponse.nextMarker();
>     } while (nextToken != null);
> ```

if it will be a problem on AWS side and token will be always null we will end up in infinite loop, we need to have a better strategy based on retry attempts with backoff strategy in place rather then firing too many requests and reaching aws request limit.
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 694 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLznS7F8N_xuLQmSyJV:-NLznS7F8N_xuLQmSyJW:bwf990a) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L694)):*
> ```Java
>     newTag.withKey(BG_VERSION)
>         .withValue(newTagValue)
>         .withPropagateAtLaunch(true)
> ```

what is this property about?
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 696 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLznOr_6LDNa7yK9cMq:-NLznOra3uejh-Zulz3J:bqsw4o9) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L696)):*
> ```Java
>         .withPropagateAtLaunch(true)
>         .withResourceId(asgName)
>         .withResourceType("auto-scaling-group");
> ```

constant
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 754 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzonnf3wDzeWECvNEt:-NLzonnf3wDzeWECvNEu:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L754)):*
> ```Java
>       listeners.addAll(describeListenersResponse.listeners());
>       nextToken = describeLoadBalancersResponse.nextMarker();
>     } while (nextToken != null);
> ```

same here


<!-- Sent from Reviewable.io -->

2023-01-17 13:20 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42712)* status: 23 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkJ73DaexWTrPbY1S:-NLzqrlWEpZXyshLoXi8:b5hmkef) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L192)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why are we hardcoding this? if it'a draft pr - please mark it as draft, we cannot have hardcoded things merged in develop.
</blockquote></details>

yes, removing that in next commit 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkUVTClHziZ2cJDUM:-NLzqyhu3yDwRY12ZKvb:b5hmkef) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L209)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same
</blockquote></details>

yes, removing that in next commit 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkzsa-3EH0LauK7-a:-NLzrZfbBVahP7SMY3u7:bg2wlkx) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L164)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why are always setting to true?
</blockquote></details>

if swapping fails, this will remain by default false. 
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 443 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzm9ZH9uIau_xVJmH9:-NLzryjL1V1eXsGs-yiN:b-nos4su) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L443)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

what is the change here?
</blockquote></details>

added spaces. removing them in next commit
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 672 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzmmCSAbpMmNR6jYHP:-NLzsNqfEwVwFuBxBoFw:bawt97b) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L672)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

if it will be a problem on AWS side and token will be always null we will end up in infinite loop, we need to have a better strategy based on retry attempts with backoff strategy in place rather then firing too many requests and reaching aws request limit.
</blockquote></details>

okay, we can take it as a task later on ? as it is already same way implemented for ecs and elastigroup. 
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 694 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLznS7F8N_xuLQmSyJV:-NLzsUe685vCPnkL__jK:b-dg9sy9) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L694)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

what is this property about?
</blockquote></details>

Some AWS Properties - required to be passed. But it wont cause any issue. 
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 696 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLznOr_6LDNa7yK9cMq:-NLzs_LKDPX8-3aUWI3T:b-jjc181) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L696)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

constant
</blockquote></details>


Some AWS Properties - required to be passed. But it wont cause any issue. 
___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 754 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzonnf3wDzeWECvNEt:-NLzslb11J_h99mgmcQF:bawt97b) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L754)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same here
</blockquote></details>

okay, we can take it as a task later on ? as it is already same way implemented for ecs and elastigroup. 


<!-- Sent from Reviewable.io -->

2023-01-17 15:16 UTC, vitsafronovici commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java
> +    AsgBlueGreenSwapServiceStartOutcome asgBlueGreenSwapServiceStartOutcome =
why we need this `Start`

2023-01-17 15:32 UTC, vitsafronovici commented on 960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgSwapServiceHandler.java
> +          format(
info already has format

2023-01-19 13:02 UTC, vitsafronovici commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java
>                .stageTargetGroupArnList(asgBlueGreenSwapServiceResult.getStageTargetGroupArnList())
why we need all these fields if they are alreay in loadBalancer object

2023-01-19 13:05 UTC, vitsafronovici commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceOutcome.java
>    List<String> stageTargetGroupArnList;
why we need these fields, they are part of prepare rollback outcome

2023-01-19 13:31 UTC, vitsafronovici commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java
> +            .oldAsgName(asgBlueGreenPrepareRollbackDataOutcome.getAsgName())
should be prodAsgName

2023-01-19 13:36 UTC, vitsafronovici commented on 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
> +                                                .prodAsgName(asgBlueGreenSwapServiceRequest.getNewAsgName())
why prodasg is newName?

2023-01-19 13:38 UTC, vitsafronovici commented on 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
> +                                                .build())
why pros is new new name?

2023-01-19 13:41 UTC, vitsafronovici commented on 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
> +              .prodTargetGroupArnList(
no need to pass back what you can get on manager side from Outcomes. And no need to put then in request if it is not needed on delegate side. Why AsgBlueGreenSwapServiceResult has so many repeating properties, if it's inside LoadBalancer object

2023-01-19 13:43 UTC, vitsafronovici commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceResult.java
>    private List<String> stageTargetGroupArnList;
no need of these props

2023-01-19 15:50 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceOutcome.java
>    List<String> stageTargetGroupArnList;
Hmm, removing them. But still we need trafficshifted boolean

2023-01-20 07:19 UTC, lovish1999 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
> +                  asgBlueGreenSwapServiceRequest.getAsgLoadBalancerConfig().getStageTargetGroupArnsList())
hmm, ok

2023-01-20 07:19 UTC, lovish1999 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
> +              .prodTargetGroupArnList(
hmm, yes removing them

2023-01-20 07:19 UTC, lovish1999 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
> +                                                .build())
I was confused in the naming. Changing that.

2023-01-20 07:19 UTC, lovish1999 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java
> +                                                .prodAsgName(asgBlueGreenSwapServiceRequest.getNewAsgName())
I was confused in the naming. Changing that.

2023-01-20 07:20 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java
> +            .oldAsgName(asgBlueGreenPrepareRollbackDataOutcome.getAsgName())
I was confused in the naming. Changing that.

2023-01-20 12:25 UTC, vitsafronovici submitted a review, later dismissed
> Reviewed 7 of 23 files at r1, 13 of 17 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42712)* status: 20 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-23 09:24 UTC, arvind-choudhary-h commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/42712#-NMSsyYX-aPur2Ml-a3q:-NMSsyYX-aPur2Ml-a3r:b-sb18m1) ([raw file](https://github.com/harness/harness-core/blob/6842240db9b03bc0af06d8daea803c3f5d5c50f8/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L127)):*
> ```Java
>                          .addHandler(AsgConfiguration,
>                              AsgConfigurationManifestRequest.builder()
>                                  .manifests(Arrays.asList(asgConfigurationContent))
> ```

how will the downsizing work? here, we are not providing any ASG name so it will default to ASG name in the request.?
Also, in the if/else block initial code till AsgSwapService is duplicate, let's merge it.


<!-- Sent from Reviewable.io -->

2023-01-23 09:26 UTC, arvind-choudhary-h commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkzsa-3EH0LauK7-a:-NMSwkBPDNp2P2ix55bI:bodeo0q) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L164)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

if swapping fails, this will remain by default false. 
</blockquote></details>

Where is the second object of AsgBlueGreenSwapServiceResult being created?



_Code quote:_
```Java
AsgBlueGreenSwapServiceResult
```


<!-- Sent from Reviewable.io -->

2023-01-23 09:27 UTC, arvind-choudhary-h commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkzsa-3EH0LauK7-a:-NMSwt-B6fA9tfIPd2Jr:b-t3i2gy) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L164)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Where is the second object of AsgBlueGreenSwapServiceResult being created?
</blockquote></details>

In the catch section, there is no AsgBlueGreenSwapServiceResult being created


<!-- Sent from Reviewable.io -->

2023-01-23 09:27 UTC, arvind-choudhary-h reviewed
> Reviewed 6 of 23 files at r1, 10 of 17 files at r2, 4 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42712)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-23 13:27 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42712)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/42712#-NLzkzsa-3EH0LauK7-a:-NMTnvC_CNCaIG6XGJUU:bc7x07d) ([raw file](https://github.com/harness/harness-core/blob/bbcd3e575948f3ea171151ac5f75a7530273ed73/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L164)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

In the catch section, there is no AsgBlueGreenSwapServiceResult being created
</blockquote></details>

we are just throwing an exception in that case
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/42712#-NMSsyYX-aPur2Ml-a3q:-NMTmlPFClGLylWxxVxm:b-u7r9l) ([raw file](https://github.com/harness/harness-core/blob/6842240db9b03bc0af06d8daea803c3f5d5c50f8/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L127)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

how will the downsizing work? here, we are not providing any ASG name so it will default to ASG name in the request.?
Also, in the if/else block initial code till AsgSwapService is duplicate, let's merge it.
</blockquote></details>

we are providing the asgname in initial chain state. 


<!-- Sent from Reviewable.io -->

2023-01-24 06:50 UTC, arvind-choudhary-h commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/42712#-NMSsyYX-aPur2Ml-a3q:-NMXXRly5OLo_SKvrWLB:b-5n1yjk) ([raw file](https://github.com/harness/harness-core/blob/6842240db9b03bc0af06d8daea803c3f5d5c50f8/930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java#L127)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

we are providing the asgname in initial chain state. 
</blockquote></details>

Yeah, now it's fine -- earlier it was buggy. Also, make sure to merge these chains in next PRs.


<!-- Sent from Reviewable.io -->

2023-01-24 07:08 UTC, arvind-choudhary-h approved these changes
> Reviewed 1 of 23 files at r1, 1 of 17 files at r2, 3 of 8 files at r3, 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42712)* status: 22 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-24 07:30 UTC, lovish1999 commented
trigger ti0

2023-01-24 08:48 UTC, vitsafronovici approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42712#-:-NMXxbO2DdEXC9xEfJ7J:bnfp4nl)* status: 22 file(s) to review. 1 change requests. 8. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-24 09:08 UTC, merged