feat: [DEL-5738]: register new db for dms and migrate delegate collections to dms
harness/harness-core pull request #42726
Opened 2023-01-17 13:04 UTC by arpit3107

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-19 22:28 UTC, raghuAtWings commented
*[`960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java` line 30 at r5](https://reviewable.io/reviews/harness/harness-core/42726#-NMB87Q276VUKTn4k-vh:-NMB87Q276VUKTn4k-vi:b-m1v0zv) ([raw file](https://github.com/harness/harness-core/blob/83c2f56e1a0308549ac65be7ffe03fde781250c4/960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java#L30)):*
> ```Java
>   private Boolean enabled;
> 
>   static final Map<String, String> classRingMap =
> ```

two comments

1. not following this ring design here. How will this be rolled out
2. If we are using ring then ringName shouldn't be a string but a constant, may be an enum


<!-- Sent from Reviewable.io -->

2023-01-19 22:28 UTC, raghuAtWings reviewed
> Reviewed 18 of 23 files at r1, 1 of 1 files at r2, 1 of 3 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-20 05:34 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java` line 30 at r5](https://reviewable.io/reviews/harness/harness-core/42726#-NMB87Q276VUKTn4k-vh:-NMCe_N84FmgM0-npY9t:b53ble6) ([raw file](https://github.com/harness/harness-core/blob/83c2f56e1a0308549ac65be7ffe03fde781250c4/960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java#L30)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

two comments

1. not following this ring design here. How will this be rolled out
2. If we are using ring then ringName shouldn't be a string but a constant, may be an enum
</blockquote></details>

1. Complete ring design will be done in next pr. Right now i have only grouped all the static collections into 2 rings, and in next PR we will have AccountRings also along with this CollectionRing.
2. Keeping it as a constant string for time being. Will update in next pr along with account-rings.


<!-- Sent from Reviewable.io -->

2023-01-20 09:38 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 197 at r6](https://reviewable.io/reviews/harness/harness-core/42726#-NMDWix_92k3MbvYFr9i:-NMDWix_92k3MbvYFr9j:bh6ywqr) ([raw file](https://github.com/harness/harness-core/blob/f5f2e110d5584c826e45615e1baca30a8bce097a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L197)):*
> ```Java
>   @Override
>   public Map<Class, Store> getSecondaryClassStores() {
>     return secondaryClassStores;
> ```

Where do we fill the class names in this map ?



_Code quote:_
```Java
secondaryClassStores
```
___
*[`960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java` line 30 at r5](https://reviewable.io/reviews/harness/harness-core/42726#-NMB87Q276VUKTn4k-vh:-NMDXIdt5o3mOt2WBgeo:b-jfzsk7) ([raw file](https://github.com/harness/harness-core/blob/83c2f56e1a0308549ac65be7ffe03fde781250c4/960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java#L30)):*
> eeping it as a constant string for time being. Will update in next pr along with account-rings.
@arpit3107 let's not complicate this logic too much, as this will be one time used only during rollout.
I would say keep a static list of collections in account collection (GLOGBAL_ACCOUNT_ID) and load it at certain interval.
No need to use ring again here.


<!-- Sent from Reviewable.io -->

2023-01-21 14:08 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 197 at r6](https://reviewable.io/reviews/harness/harness-core/42726#-NMDWix_92k3MbvYFr9i:-NMJdupLC7VpCrZGZrAT:b-uxplt2) ([raw file](https://github.com/harness/harness-core/blob/f5f2e110d5584c826e45615e1baca30a8bce097a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L197)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Where do we fill the class names in this map ?
</blockquote></details>

getSecondaryClassStores().computeIfAbsent 
ComputeIfAbsent puts the value after computing
___
*[`960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java` line 30 at r5](https://reviewable.io/reviews/harness/harness-core/42726#-NMB87Q276VUKTn4k-vh:-NMJe4D71vCAgZP2L_ha:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83c2f56e1a0308549ac65be7ffe03fde781250c4/960-persistence/src/main/java/io/harness/persistence/DelegateMigrationFlag.java#L30)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> eeping it as a constant string for time being. Will update in next pr along with account-rings.
@arpit3107 let's not complicate this logic too much, as this will be one time used only during rollout.
I would say keep a static list of collections in account collection (GLOGBAL_ACCOUNT_ID) and load it at certain interval.
No need to use ring again here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-23 06:28 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java` line 2 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHBFH8JIiHn_Sr_No:-NMSHBFH8JIiHn_Sr_Np:bb6ht38) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java#L2)):*
> ```Java
> /*
>  * Copyright 2022 Harness Inc. All rights reserved.
> ```

2023



_Code quote:_
```Java
2022
```
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java` line 26 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSGd4-0DUa4QRy-3ju:-NMSGd4-0DUa4QRy-3jv:bys5hn8) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java#L26)):*
> ```Java
> public class DelegateMigrationFlag implements PersistentEntity {
>   @Id private String uuid;
>   private List<String> enabledClassNames;
> ```

just say classNames



_Code quote:_
```Java
enabledClassNames
```
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 2 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSH97x2yxmOmAuqXB-:-NMSH97x2yxmOmAuqXB0:bb6ht38) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L2)):*
> ```Java
> /*
>  * Copyright 2022 Harness Inc. All rights reserved.
> ```

2023



_Code quote:_
```Java
2022
```
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 31 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSIMQn2m2eU8nJoWxu:-NMSIMQn2m2eU8nJoWxv:b-t7nl93) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L31)):*
> ```Java
>   ReadWriteLock readWriteLock = new ReentrantReadWriteLock();
> 
>   static final List<String> classesToBeMigrated = Arrays.asList("io.harness.agent.beans.AgentMtlsEndpoint",
> ```

This list suppose to be come from db right ? why we are filling it here.



_Code quote:_
```Java
classesToBeMigrated
```
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 41 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHLL70Z0F7TlA5mp8:-NMSHLL70Z0F7TlA5mp9:b-9gxcy7) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L41)):*
> ```Java
> 
>   Cache<String, Boolean> delegateMigrationFlagCache =
>       Caffeine.newBuilder().maximumSize(100).expireAfterWrite(10, TimeUnit.SECONDS).build();
> ```

10 seconds will be too aggressive, let's make it 30mins. Infact you can you can remove this TTL and introduce a reset method here, which will clear entry from cache in case of any update.
For update, consider having an endpoint exposed in manager.



_Code quote:_
```Java
TimeUnit.SECONDS
```
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 45 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHYFG6wl9kq77xf4-:-NMSHYFG6wl9kq77xf40:bktb3n4) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L45)):*
> ```Java
>   public Boolean isMigrationEnabled(String className) {
>     try {
>       readWriteLock.readLock().lock();
> ```

why we need a lock here ?



_Code quote:_
```Java
readWriteLock.readLock().lock();
```
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSIRwUCh8djeNUYbJ3:-NMSIRwUCh8djeNUYbJ4:b-pjk4dw) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L59)):*
> ```Java
>     log.info("Arpit: populating migration cache with classes {}", classesHavingMigrationEnabled);
>     for (String className : classesToBeMigrated) {
>       if (classesHavingMigrationEnabled.contains(className)) {
> ```

Instead of all this, just update the existing value in cache.



_Code quote:_
```Java
      if (classesHavingMigrationEnabled.contains(className)) {
        setMigrationCache(className, Boolean.TRUE);
      } else {
        setMigrationCache(className, Boolean.FALSE);
      }
```


<!-- Sent from Reviewable.io -->

2023-01-23 07:11 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 9 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 31 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSIMQn2m2eU8nJoWxu:-NMSRQf4EBe3wFVb5VrB:b-jdkkct) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L31)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This list suppose to be come from db right ? why we are filling it here.
</blockquote></details>

Lets say I enabled only Delegate Class in db, then application should also need to set false for other classes.
So, an active list of all the migration classes needs to be there.
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 41 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHLL70Z0F7TlA5mp8:-NMSRhhJ1Da15ZII7XrP:b-isq2xr) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L41)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

10 seconds will be too aggressive, let's make it 30mins. Infact you can you can remove this TTL and introduce a reset method here, which will clear entry from cache in case of any update.
For update, consider having an endpoint exposed in manager.
</blockquote></details>

2 things:
1. If we make it 30 mins then pods will be inconsistent for 30 mins, which is a large time. Inconsistent means some pods will be using old db and some new db.
2. There are about 20 pods involved here (6 manager + 2 manager-iterator + 3 cvng + eventService, etc others). And management of all those will become tedious. Also one endpoint will be going to only one pod of a service but not all.
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 45 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHYFG6wl9kq77xf4-:-NMSSNQ3AAfztJN2g56q:b-c85os8) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L45)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why we need a lock here ?
</blockquote></details>

So that no threads reads a garbage value from cache when a cache-set operation is going on for that class.
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSIRwUCh8djeNUYbJ3:-NMSSp6L4c-PBIm8_7ZS:bt3tahc) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L59)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Instead of all this, just update the existing value in cache.
</blockquote></details>

We also need to set False for those classes which are not in list coming from DB.


<!-- Sent from Reviewable.io -->

2023-01-23 07:18 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 31 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSIMQn2m2eU8nJoWxu:-NMSU-pNAK1CwpJ9SXuz:btzceve) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L31)):*
>  enabled only Delegate Class in db, then application should also need to set false for other classes.
> So, an active list of all the migration classes needs to be there.
whatever is missing in cache consider it as false. and continue operating it from old db
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 41 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHLL70Z0F7TlA5mp8:-NMSTihU1MDrnHdRJSlb:bokmliy) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L41)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

2 things:
1. If we make it 30 mins then pods will be inconsistent for 30 mins, which is a large time. Inconsistent means some pods will be using old db and some new db.
2. There are about 20 pods involved here (6 manager + 2 manager-iterator + 3 cvng + eventService, etc others). And management of all those will become tedious. Also one endpoint will be going to only one pod of a service but not all.
</blockquote></details>

ok, so can we increase or get rid of this cache in future releases.



_Code quote:_
```Java
      Caffeine.newBuilder().maximumSize(100).expireAfterWrite(10, TimeUnit.SECONDS).build();
```
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 45 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHYFG6wl9kq77xf4-:-NMSUBB41BrUpPCToddL:b-n2yqgb) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L45)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

So that no threads reads a garbage value from cache when a cache-set operation is going on for that class.
</blockquote></details>

what will garbage would be, it will be old value, which should be fine.
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSIRwUCh8djeNUYbJ3:-NMSUJcs8mMGl-WKtA3Y:b-x5pocq) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L59)):*
>  need to set False for those classes w
no, that's not needed. Missing entries in cache can be consider as false.


<!-- Sent from Reviewable.io -->

2023-01-23 07:52 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 9 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 31 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSIMQn2m2eU8nJoWxu:-NMSaml57ToCa9G6UJdc:b-ojmw3u) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L31)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

>  enabled only Delegate Class in db, then application should also need to set false for other classes.
> So, an active list of all the migration classes needs to be there.
whatever is missing in cache consider it as false. and continue operating it from old db
</blockquote></details>

Okay so i am using NULL as the trigger to populate the cache.
For me its like if the value is NULL then populate cache.

 Any suggestion on when to populate the cache with your soln?
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 41 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHLL70Z0F7TlA5mp8:-NMSbB6fBpeFh9A7tzCf:b2nhysk) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L41)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

ok, so can we increase or get rid of this cache in future releases.
</blockquote></details>

ack
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java` line 45 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHYFG6wl9kq77xf4-:-NMSbCcv9uUK8nsWLaAT:b-13s6p7) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlagCacheHelper.java#L45)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

what will garbage would be, it will be old value, which should be fine.
</blockquote></details>

Okay, got you. We can use AtomicBoolean in this case and avoid locks.


<!-- Sent from Reviewable.io -->

2023-01-23 19:21 UTC, raghuAtWings approved these changes
> Reviewed 1 of 2 files at r6, 6 of 7 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-24 07:25 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 4 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java` line 2 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSHBFH8JIiHn_Sr_No:-NMXeeAI-cEjI1EqY-6z:b-3smrzx) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java#L2)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

2023
</blockquote></details>

ack. will do
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java` line 26 at r9](https://reviewable.io/reviews/harness/harness-core/42726#-NMSGd4-0DUa4QRy-3ju:-NMXefuK3M7hgW1SlCHa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/024d386da55b1d69ebbd8a35c0fa314d27e37a0b/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java#L26)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

just say classNames
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-24 07:40 UTC, gaurav-jain1 reviewed
> Reviewed 15 of 23 files at r1, 1 of 1 files at r2, 1 of 3 files at r3, 1 of 2 files at r6, 4 of 7 files at r8, 1 of 2 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 234 at r10](https://reviewable.io/reviews/harness/harness-core/42726#-NMXgrni8c1uxdHD6C4K:-NMXgrnj7mCwTdkO3k28:b-idqqbr) ([raw file](https://github.com/harness/harness-core/blob/3a521d64e1ff1db538993d6d135e3f2f8fb97240/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L234)):*
> ```Java
>       classesHavingMigrationEnabled.clear();
>     }
>     log.info("Arpit: populating migration cache {}", classesHavingMigrationEnabled);
> ```

this log not required, 



_Code quote:_
```Java
log.info("Arpit: populating migration cache {}", classesHavingMigrationEnabled);
```
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 114 at r10](https://reviewable.io/reviews/harness/harness-core/42726#-NMXh2a_AnsQ3vVJo_F_:-NMXh2a_AnsQ3vVJo_Fa:bor8x9c) ([raw file](https://github.com/harness/harness-core/blob/3a521d64e1ff1db538993d6d135e3f2f8fb97240/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L114)):*
> ```Java
>     });
>     if (secondaryStore != DEFAULT_STORE && isMigrationEnabled(cls)) {
>       logger().info("Arpit: NEW className {}", cls.getName());
> ```

make sure you remove these logs before merge.
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 117 at r10](https://reviewable.io/reviews/harness/harness-core/42726#-NMXhIOZ1bu5VJlDrJA_:-NMXhIO_1F2GWyKiolnY:b-3ktuy9) ([raw file](https://github.com/harness/harness-core/blob/3a521d64e1ff1db538993d6d135e3f2f8fb97240/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L117)):*
> ```Java
>       return getDatastore(secondaryStore);
>     }
>     if (secondaryStore != DEFAULT_STORE) {
> ```

this condition is useless, lets remove it.



_Code quote:_
```Java
  if (secondaryStore != DEFAULT_STORE) {
```


<!-- Sent from Reviewable.io -->

2023-01-25 05:47 UTC, jennyjames21 commented
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 111 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMbRz94DX_lfo4FqMcK:-NMbRz95Anh7jJYAVXYb:btoconi) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L111)):*
> ```Java
>           .map(name -> Store.builder().name(name).build())
>           .findFirst()
>           .orElseGet(() -> DEFAULT_STORE);
> ```

why do wee need else DEFAULT_STORE in secondaryStore list?



_Code quote:_
```Java
DEFAULT_STORE
```


<!-- Sent from Reviewable.io -->

2023-01-25 05:50 UTC, jennyjames21 commented
*[`960-persistence/src/main/java/io/harness/ng/DbAliases.java` line 28 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMbTQUU9AilkM9vPCAk:-NMbTQUU9AilkM9vPCAl:bmpvew6) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/ng/DbAliases.java#L28)):*
> ```Java
>   public static final String CENG = "events";
>   public static final String CDC = "change-data-capture";
>   public static final String DMS = "dms-harness";
> ```

Minor suggestion. Do we need harness in name, just dms?


<!-- Sent from Reviewable.io -->

2023-01-25 06:02 UTC, jennyjames21 commented
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 217 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMbWCPHCcvt2J8JSyCC:-NMbWCPHCcvt2J8JSyCD:blzwjsj) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L217)):*
> ```Java
>   @Override
>   public boolean isMigrationEnabled(Class cls) {
>     if (!isDelegateMigrationCacheThreadRunning.get()) {
> ```

is the idea behind this check for synchronization?


<!-- Sent from Reviewable.io -->

2023-01-25 06:04 UTC, jennyjames21 reviewed
> Reviewed 14 of 23 files at r1, 1 of 1 files at r2, 1 of 3 files at r3, 1 of 2 files at r6, 4 of 7 files at r8, 1 of 2 files at r9, 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-26 00:34 UTC, xingchi-jin requested changes
My comments are more about java codes. 
But have a more important question in mind :  
after running mirror before it finish. How will the on-going writes be persisted on the secondary store  ?
When is the time to turn on this flag?
After turn on the flag, if any failure, what's the rollback/forward strategy 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726#-:-NMfTj9JBWQZXgiTEFa0:bhddc0t)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 93 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfP6490LzHtLGgvCgS:-NMfP64A97l1b5VpJD00:b-fhbj) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L93)):*
> ```Java
>           .build());
>   private final AtomicBoolean isDelegateMigrationCacheThreadRunning = new AtomicBoolean(false);
>   List<String> classesHavingMigrationEnabled = new ArrayList<>();
> ```

Can we move the logics of checking if a class has migration enabled to a separate singleton class ? 
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 217 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfNKLQDfA9l0RsBVYz:-NMfNKLQDfA9l0RsBVZ-:b-hiaczb) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L217)):*
> ```Java
>   @Override
>   public boolean isMigrationEnabled(Class cls) {
>     if (!isDelegateMigrationCacheThreadRunning.get()) {
> ```

why start the thread in a boolean check function?  
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 226 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfS3sR7JxDZMzaV69h:-NMfS3sR7JxDZMzaV69i:b-dlq49e) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L226)):*
> ```Java
> 
>   private void populateMigrationCache() {
>     DelegateMigrationFlag migrationFlag = createQuery(DelegateMigrationFlag.class)
> ```

Feel like it's a generic feature, it works for all other entities. Maybe we just call it MigrationFlag


<!-- Sent from Reviewable.io -->

2023-01-26 12:40 UTC, mdmilic requested changes
> Reviewed 14 of 23 files at r1, 1 of 1 files at r2, 1 of 3 files at r3, 1 of 2 files at r6, 4 of 7 files at r8, 1 of 2 files at r9, 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 3 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 219 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMi4NHu-TmgXZa-yRx0:-NMi4NHu-TmgXZa-yRx1:b-yuu93y) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L219)):*
> ```Java
>     if (!isDelegateMigrationCacheThreadRunning.get()) {
>       isDelegateMigrationCacheThreadRunning.set(true);
>       populateMigrationCache();
> ```

Why this logic instead of using some ready available cache like guavas cache or caffein? You should avoid doing this. 



_Code quote:_
```Java
      isDelegateMigrationCacheThreadRunning.set(true);
      populateMigrationCache();
      delegateMigrationCacheThread.scheduleAtFixedRate(this::populateMigrationCache, 10, 10, TimeUnit.SECONDS);
```
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 111 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMbRz94DX_lfo4FqMcK:-NMi2U_DCWTxW0rc7gvN:bwpespx) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L111)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why do wee need else DEFAULT_STORE in secondaryStore list?
</blockquote></details>

Agree. Just return Optional<Store> instead and check if present. 


<!-- Sent from Reviewable.io -->

2023-01-26 12:40 UTC, mdmilic reviewed
> Reviewed 1 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 3 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-30 07:25 UTC, arpit3107 reviewed
These are documented in the wiki: https://harness.atlassian.net/wiki/spaces/DEL/pages/21241725344/Migrate+Delegate+Collections+Out+of+Harness+DB#Proposed-solution%3A

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726#-:-NN0Hg3k9N0WqKqSwqg_:b6l2eo3)* status: Some of the checks are too old. 3 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 93 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfP6490LzHtLGgvCgS:-NN0Hvsx2dFMxScdsXFA:bhyqr40) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L93)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

Can we move the logics of checking if a class has migration enabled to a separate singleton class ? 
</blockquote></details>

Not possible, because that class needs to depend on HPersistence to get the migrationFlag from DB and it will create a circular dependency b/w Persistence and that class.
___
*[`960-persistence/src/main/java/io/harness/ng/DbAliases.java` line 28 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMbTQUU9AilkM9vPCAk:-NN0YzaF18bbScElUlet:b-dfaoqf) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/ng/DbAliases.java#L28)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Minor suggestion. Do we need harness in name, just dms?
</blockquote></details>

dms rhymes with pms. so thought of keeping it as dms-harness :) 


<!-- Sent from Reviewable.io -->

2023-01-30 15:02 UTC, mdmilic requested changes
> Reviewed 2 of 4 files at r12, 4 of 4 files at r13, 10 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 3 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 223 at r14](https://reviewable.io/reviews/harness/harness-core/42726#-NN2AkMZEQU1hN2esUwi:-NN2AkMZEQU1hN2esUwj:bgs6k04) ([raw file](https://github.com/harness/harness-core/blob/949003309721b8d5dceb2ac43dc0acd70f51ed7f/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L223)):*
> ```Java
> 
>   @Override
>   public AtomicBoolean isMigrationEnabled(Class cls) {
> ```

Can you elaborate why you can't use standard caching like guava cache or caffeine and why you need atomics? Using atomics here synchronizes all DB queries and creates a bottleneck here. 


<!-- Sent from Reviewable.io -->

2023-01-30 15:46 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 3 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 223 at r14](https://reviewable.io/reviews/harness/harness-core/42726#-NN2AkMZEQU1hN2esUwi:-NN2LQUs7vQEjl7IYZsj:br1xldm) ([raw file](https://github.com/harness/harness-core/blob/949003309721b8d5dceb2ac43dc0acd70f51ed7f/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L223)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Can you elaborate why you can't use standard caching like guava cache or caffeine and why you need atomics? Using atomics here synchronizes all DB queries and creates a bottleneck here. 
</blockquote></details>

Now, i am using caffeine cache which is of String v/s AtomicBoolean type. AtomicBoolean is needed to avoid thread inconsistencies while one thread is writing and some are reading.


<!-- Sent from Reviewable.io -->

2023-01-31 18:24 UTC, xingchi-jin reviewed
> Reviewed 14 of 23 files at r1, 1 of 3 files at r3, 2 of 8 files at r8, 1 of 2 files at r9, 1 of 1 files at r11, 2 of 4 files at r13, 10 of 10 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 3 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 93 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfP6490LzHtLGgvCgS:-NN7zCXr-flFsB-2nEAk:b-aa6ndw) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L93)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Not possible, because that class needs to depend on HPersistence to get the migrationFlag from DB and it will create a circular dependency b/w Persistence and that class.
</blockquote></details>

no, i mean move the entire migrationFlag & cache logic to another class. Up to you
___
*[`dockerization/manager/scripts/replace_configs.sh` line 223 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NN83PHX0XINdPzGEhzJ:-NN83PHX0XINdPzGEhzK:budi4cf) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/dockerization/manager/scripts/replace_configs.sh#L223)):*
> ```Shell
> fi
> 
> if [[ "" != "$DMS_MONGO_CONNECTIONS_PER_HOST" ]]; then
> ```

are these new env need to deploy on manager? did you raise pr to the the corresponding manifest repos ? 


<!-- Sent from Reviewable.io -->

2023-02-01 05:01 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 3 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 234 at r10](https://reviewable.io/reviews/harness/harness-core/42726#-NMXgrni8c1uxdHD6C4K:-NNALJ4r-YEkf_HaQHI9:b-9unw5o) ([raw file](https://github.com/harness/harness-core/blob/3a521d64e1ff1db538993d6d135e3f2f8fb97240/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L234)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

this log not required, 
</blockquote></details>

deleted
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 93 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfP6490LzHtLGgvCgS:-NNAJv5o2usgx3zkGXkL:b-bxt3q2) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L93)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

no, i mean move the entire migrationFlag & cache logic to another class. Up to you
</blockquote></details>

Got you. But the problem is that singleton class needs to take depend on HPersistence to get the migrationFlag from DB. So in that class there would be only one cache and a simple get method, which in my opinion is of no use, since i am already creating the getCacheMethod in Hpersistence, so why not create the cache there only.
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 217 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMbWCPHCcvt2J8JSyCC:-NNALFif4ul1TT9PTXZ-:bhofej8) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L217)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

is the idea behind this check for synchronization?
</blockquote></details>

Deleted
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 217 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfNKLQDfA9l0RsBVYz:-NNALGjU76Wh2btw-QjQ:bhofej8) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L217)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why start the thread in a boolean check function?  
</blockquote></details>

Deleted
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 219 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMi4NHu-TmgXZa-yRx0:-NNALI5k-CLkPik_vSh8:b-9unw5o) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L219)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why this logic instead of using some ready available cache like guavas cache or caffein? You should avoid doing this. 
</blockquote></details>

deleted
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 226 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMfS3sR7JxDZMzaV69h:-NNAKUX7-rAvIigXE5YJ:b-ym9qem) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L226)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

Feel like it's a generic feature, it works for all other entities. Maybe we just call it MigrationFlag
</blockquote></details>

Yes but these methods will only be used while migration, but keeping it like this for everybody else will have a cost of if-else and checking for SecondaryStoreIn, so wanted to avoid that. And we will remove all these codes once migration is done.
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 227 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMmxmuC9gplzI-K1r9z:-NNAKuxR3uKubZLPJAdu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L227)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Having 'STATIC_MIGRATION_FLAG_UUID' creates complexity. Instead use collection name as separate record i.e.
{
className: (String)
Enabled: (true/false) 
}
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 111 at r11](https://reviewable.io/reviews/harness/harness-core/42726#-NMbRz94DX_lfo4FqMcK:-NNAKx8H4bvazrIHkVxJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b4aa80a8fd6c8b95a1a1e4db5a4e7fffca3678a/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L111)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Agree. Just return Optional<Store> instead and check if present. 
</blockquote></details>

Done.
___
*[`dockerization/manager/scripts/replace_configs.sh` line 223 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NN83PHX0XINdPzGEhzJ:-NNAKzakEDzwrDtt0O8s:b-dxpxj3) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/dockerization/manager/scripts/replace_configs.sh#L223)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

are these new env need to deploy on manager? did you raise pr to the the corresponding manifest repos ? 
</blockquote></details>

Correct. Have raised a pr for pr-env. Will have to do the same for other envs. I will be monitoring these changes


<!-- Sent from Reviewable.io -->

2023-02-01 05:29 UTC, xingchi-jin approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2 change requests. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-01 06:40 UTC, jennyjames21 reviewed
> Reviewed 2 of 4 files at r13, 10 of 10 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2 change requests. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-01 06:40 UTC, jennyjames21 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2 change requests. 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-01 13:10 UTC, deepak-harness approved these changes
> Reviewed 14 of 23 files at r1, 1 of 3 files at r3, 1 of 2 files at r6, 2 of 8 files at r8, 1 of 2 files at r9, 2 of 4 files at r10, 1 of 1 files at r11, 2 of 4 files at r13, 10 of 10 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2 change requests. 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-01 13:19 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2 change requests. 2. unresolved discussions. 

___
*[`420-delegate-service/src/main/java/software/wings/delegatetasks/validation/core/DelegateConnectionResult.java` line 42 at r13](https://reviewable.io/reviews/harness/harness-core/42726#-NN0dTwN4ANHpV7ICRsG:-NN0dTwN4ANHpV7ICRsH:b-il586t) ([raw file](https://github.com/harness/harness-core/blob/829de7706d4cdca6d455afa59bae492212e9e347/420-delegate-service/src/main/java/software/wings/delegatetasks/validation/core/DelegateConnectionResult.java#L42)):*
> ```Java
> @Builder
> @StoreIn(DbAliases.HARNESS)
> @SecondaryStoreIn(DbAliases.DMS)
> ```

Do we need to move this ? Since @jennyjames21 was working on moving this to redis. please confirm



_Code quote:_
```Java
@SecondaryStoreIn(DbAliases.DMS)
```
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 239 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NNC6fTWA6J7z5F4VH0e:-NNC6fTXAt6U2g8Ricse:b-c4j0b2) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L239)):*
> ```Java
>       return delegateMigrationFlagCache.get(cls.getName());
>     } catch (ExecutionException e) {
>       log.warn("Serious: Exception occurred while checking for delegate migration flag.");
> ```

no need to append Serious word.. make it log.error



_Code quote:_
```Java
Serious:
```
___
*[`960-persistence/src/main/java/io/harness/utils/DelegateMigrationFlagCacheHelper.java` line 28 at r13](https://reviewable.io/reviews/harness/harness-core/42726#-NN0eKaG1cwv28uuH9R9:-NN0eKaHAu8EHoLvPBmF:b9r844r) ([raw file](https://github.com/harness/harness-core/blob/829de7706d4cdca6d455afa59bae492212e9e347/960-persistence/src/main/java/io/harness/utils/DelegateMigrationFlagCacheHelper.java#L28)):*
> ```Java
>       Caffeine.newBuilder().maximumSize(20).expireAfterWrite(10, TimeUnit.SECONDS).build();
> 
>   public static final Map<String, String> classNameToCollectionName =
> ```

why we need this map ? I think request to Hpersistance comes with class name itself.


<!-- Sent from Reviewable.io -->

2023-02-01 13:48 UTC, mdmilic approved these changes
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-01 14:19 UTC, raghuAtWings commented
*[`420-delegate-service/src/main/java/software/wings/delegatetasks/validation/core/DelegateConnectionResult.java` line 42 at r13](https://reviewable.io/reviews/harness/harness-core/42726#-NN0dTwN4ANHpV7ICRsG:-NNCL4Tf2bfhNmBzQy2W:b-5f63ka) ([raw file](https://github.com/harness/harness-core/blob/829de7706d4cdca6d455afa59bae492212e9e347/420-delegate-service/src/main/java/software/wings/delegatetasks/validation/core/DelegateConnectionResult.java#L42)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Do we need to move this ? Since @jennyjames21 was working on moving this to redis. please confirm
</blockquote></details>

this collection was removed/not used anymore


<!-- Sent from Reviewable.io -->

2023-02-01 14:20 UTC, raghuAtWings commented
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java` line 25 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NNCLH0R7lIJkBRyPU9k:-NNCLH0R7lIJkBRyPU9l:bpjc4dm) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java#L25)):*
> ```Java
> public class DelegateMigrationFlag implements PersistentEntity {
>   @Id private String className;
>   private Boolean enabled;
> ```

should be boolean instead of Boolean


<!-- Sent from Reviewable.io -->

2023-02-01 14:22 UTC, raghuAtWings commented
*[`dockerization/verification/scripts/replace_configs.sh` line 35 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NNCLoo786PHXipQNAEc:-NNCLoo786PHXipQNAEd:b-tywa26) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/dockerization/verification/scripts/replace_configs.sh#L35)):*
> ```Shell
> 
> if [[ "" != "$DMS_MONGO_URI" ]]; then
>   export DMS_MONGO_URI=${DMS_MONGO_URI//\\&/&}; yq -i '.dms-mongo.uri=env(DMS_MONGO_URI)' $CONFIG_FILE
> ```

won't you need code to replace other things like username and pwd?


<!-- Sent from Reviewable.io -->

2023-02-01 14:23 UTC, raghuAtWings reviewed
> Reviewed 2 of 4 files at r10, 1 of 1 files at r11, 2 of 4 files at r13, 10 of 10 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-01 16:04 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/software/wings/delegatetasks/validation/core/DelegateConnectionResult.java` line 42 at r13](https://reviewable.io/reviews/harness/harness-core/42726#-NN0dTwN4ANHpV7ICRsG:-NNC8NM69M73jXALgFgB:b-g4d8z4) ([raw file](https://github.com/harness/harness-core/blob/829de7706d4cdca6d455afa59bae492212e9e347/420-delegate-service/src/main/java/software/wings/delegatetasks/validation/core/DelegateConnectionResult.java#L42)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this collection was removed/not used anymore
</blockquote></details>

Jenny removed delegateConnection (used while heartbeating).
This is delegateConnectionResult (used while executing delegateTasks, to keep the validation result of delegateTasks)
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 239 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NNC6fTWA6J7z5F4VH0e:-NNC8hHk9dGUfGHg5ijx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L239)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

no need to append Serious word.. make it log.error
</blockquote></details>

Done.
___
*[`dockerization/verification/scripts/replace_configs.sh` line 35 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NNCLoo786PHXipQNAEc:-NNChlQjAw5oWTOFZ5Ge:bkqu6a) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/dockerization/verification/scripts/replace_configs.sh#L35)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

won't you need code to replace other things like username and pwd?
</blockquote></details>

No, i made similar changes to MONGO_URI. whatever was there for primary harness mongo in this service.
So for verfication service DMS_MONGO_URI itself should have all the data.
___
*[`960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java` line 25 at r15](https://reviewable.io/reviews/harness/harness-core/42726#-NNCLH0R7lIJkBRyPU9k:-NNChkZZEWO6KFpK1Gcz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3900efa34ca0a1631352455201fe8567bad7b0cf/960-persistence/src/main/java/io/harness/migration/DelegateMigrationFlag.java#L25)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

should be boolean instead of Boolean
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-02 02:40 UTC, hitesharinga approved these changes

2023-02-02 04:46 UTC, arpit3107 commented
trigger ft2

2023-02-02 05:32 UTC, gaurav-jain1 approved these changes
> Reviewed 1 of 1 files at r11, 7 of 10 files at r14, 2 of 4 files at r15, 4 of 4 files at r16, 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 06:57 UTC, raghuAtWings approved these changes
> Reviewed 4 of 4 files at r16, 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42726)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-03 16:44 UTC, merged