[feat]: [CDS-50012]: Added Elastigroup swimlane connector, service, infra
harness/harness-core pull request #42761
Opened 2023-01-18 09:54 UTC by arvind-choudhary-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-19 08:52 UTC, arvind-choudhary-h commented
trigger messagecheck

2023-01-23 07:25 UTC, puthrayaharness requested changes

2023-01-23 07:25 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/infra/AmiElastigroupInfraDefMapper.java
> +    if (infrastructureDefinition.getCloudProviderType() == AWS) {
You are not taking care of `getCloudProviderId()` in this. But you are referencing this below in Spec

2023-01-23 07:25 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/infra/AmiElastigroupInfraDefMapper.java
> +        connectorDetail =
This might throw a null pointer exception if the cloud provider is not found.
In such cases, let's fall back to setting the `connectorRef` as runtime input.

2023-01-23 07:25 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/infra/AmiElastigroupInfraDefMapper.java
> +      Map<CgEntityId, NGYamlFile> migratedEntities, String infraName,
InfraName is not used at all. Please remove this from the signature.

2023-01-23 12:33 UTC, arvind-choudhary-h commented on 100-migrator/src/main/java/io/harness/ngmigration/service/infra/AmiElastigroupInfraDefMapper.java
> +        connectorDetail =
Here, cloudproviderId would always be there as AWS AMI Infra has this field required.

2023-01-24 10:02 UTC, arvind-choudhary-h commented on 100-migrator/src/main/java/io/harness/ngmigration/service/infra/AmiElastigroupInfraDefMapper.java
> +    if (infrastructureDefinition.getCloudProviderType() == AWS) {
These are additional connectors apart from the main infra connector.

2023-01-24 12:04 UTC, puthrayaharness approved these changes

2023-01-24 12:06 UTC, puthrayaharness approved these changes
> Reviewed 21 of 36 files at r1, 14 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42761)* status: 36 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-24 12:19 UTC, manjunatha-etagi approved these changes
> Reviewed 21 of 36 files at r1, 14 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42761)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-24 12:19 UTC, merged