feat: [PL-30372]: Handling timescale DB deletion when account is churned
harness/harness-core pull request #42775
Opened 2023-01-18 12:41 UTC by boopesh007

## Describe your changes
Handling timescale DB deletion when the account is churned. I wrote a deletion framework for Timescale data deletion whenever a account is chhurned. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-18 20:53 UTC, boopesh007 commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/TimescaleDataCleanup.java
> +            throw new RuntimeException(e);
Done

2023-01-18 20:58 UTC, abhinav-harness commented
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/TimescaleDataCleanup.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/42775#-NM5f8kb7paFoUUAtvMA:-NM5f8kb7paFoUUAtvMB:b-bs56de) ([raw file](https://github.com/harness/harness-core/blob/dccdf3dd2391418ff8d0cdf5cf755684fa7e2b36/400-rest/src/main/java/io/harness/event/timeseries/processor/TimescaleDataCleanup.java#L31)):*
> ```Java
>             deleteStatement.execute();
>           } catch (SQLException e) {
>             log.error("Error while deleting the timescale data for account: {}", accountId);
> ```

log exception everywhere


<!-- Sent from Reviewable.io -->

2023-01-19 06:18 UTC, abhinav-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42775)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/event/timeseries/processor/TimescaleDataCleanup.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/42775#-NM5f8kb7paFoUUAtvMA:-NM7fJZs9LqDjnsO7One:bphu7sc) ([raw file](https://github.com/harness/harness-core/blob/dccdf3dd2391418ff8d0cdf5cf755684fa7e2b36/400-rest/src/main/java/io/harness/event/timeseries/processor/TimescaleDataCleanup.java#L31)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

log exception everywhere
</blockquote></details>

still not logged


<!-- Sent from Reviewable.io -->

2023-01-20 14:31 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42775)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-20 19:01 UTC, lasdox commented on 400-rest/src/main/java/io/harness/event/timeseries/processor/TimescaleDataCleanup.java
> +    return tablesToBeDeleted;
this can be changed to a static list in a future enhancement

2023-01-20 19:02 UTC, lasdox approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42775)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-21 03:04 UTC, merged