fix: [CDS-49439]: Helm repo override should expect only required inputs
harness/harness-core pull request #42788
Opened 2023-01-18 18:29 UTC by abhinavsingh1196

## Describe your changes

Helm repo override earlier expected a `Store` as input to override service's helm chart. This was failing the UI schema validation, since we just use the `connectorRef` property of `Store` while performing helm repo overrides.
This change overrides just the connectorRef for Http, OCI, GCS, S3 stores (since only those are applicable for Helm Repo Overrides, we're not overriding Git based stores).

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-19 16:39 UTC, abhinavsingh1196 commented
trigger gitleaks

2023-01-20 06:31 UTC, yogesh-chauhan requested changes

2023-01-20 06:31 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmRepoOverrideManifest.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) @Wither ParameterField<String> connectorRef;
We should annotate with @NotNull

2023-01-20 06:47 UTC, yogesh-chauhan requested changes

2023-01-20 06:47 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/EnvironmentV2ManifestValidator.java
> +      String overrideManifestType = overrideManifest.getType();
can we call this "type" as "kind" so that it is easier to understand ?

2023-01-20 06:47 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/EnvironmentV2ManifestValidator.java
> +        throw new InvalidRequestException(
can we also print both the types ?

2023-01-20 06:47 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/S3StoreConfig.java
> +    if (!ParameterField.isNull(overridingConnectorRef)) {
nit: you can use ParameterField::isNotNull

2023-01-20 06:47 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/HelmRepoOverrideManifest.java
> +    return VisitableChildren.builder().build();
I think we should annotate the class with @SimpleVisitorHelper(helperClass = ConnectorRefExtractorHelper.class) and implement the WithConnectorRef for this connector to be recorded as a referred entity

2023-01-23 07:41 UTC, yogesh-chauhan submitted a review, later dismissed

2023-01-23 07:41 UTC, yogesh-chauhan reviewed
> Reviewed 7 of 15 files at r1, 1 of 2 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42788)* status: 16 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-23 07:51 UTC, abhinavsingh1196 commented
trigger feature-build

2023-01-23 07:51 UTC, tchaurasiya submitted a review, later dismissed
> Reviewed 7 of 15 files at r1, 1 of 2 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42788)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-23 16:12 UTC, yogesh-chauhan reviewed
> Reviewed 8 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42788)* status: 9 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-23 17:06 UTC, abhinavsingh1196 commented
trigger feature-build

2023-01-24 05:06 UTC, abhinavsingh1196 commented
trigger feature-build

2023-01-24 17:46 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42788)* status: 10 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-24 18:34 UTC, yogesh-chauhan approved these changes

2023-01-25 06:37 UTC, tchaurasiya approved these changes
> Reviewed 4 of 9 files at r5, 2 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42788)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-25 06:39 UTC, merged