feat: [DEL-5765] DMS skeleton code
harness/harness-core pull request #42825
Opened 2023-01-19 12:50 UTC by AnupamIO

Added skeleton code for 419-delegate-service-app which will serve as new DMS.
- This doesn't contain mongo, redis or eventFramework configuration will add that separately.

Testing:
- Able to build and start server, checked using swagger: 
- https: https://localhost:9080/api/swagger.json
- http: http://localhost:3458/api/swagger.json

Notes:
- dependencies are copied from 270-dms (anything which is under 419 is removed).
- copied cert, key.pem and keystore.jks from old dms.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/42825)

2023-01-19 22:12 UTC, raghuAtWings commented
*[`419-delegate-service-app/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB4a--ByxHR3oqBp15:-NMB4a--ByxHR3oqBp16:b-7v7geu) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/BUILD.bazel#L19)):*
> ```Starlark
>     "//420-delegate-service:module",
>     "//440-connector-nextgen:module",
>     "//450-ce-views:module",
> ```

why does it need so many modules like ce-views, ng-core-clients, expression-service etc. Please add the least possible modules 


<!-- Sent from Reviewable.io -->

2023-01-19 22:13 UTC, raghuAtWings commented
*[`419-delegate-service-app/BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB4qZfD-0pIAA12BhD:-NMB4qZfD-0pIAA12BhE:b745d4e) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/BUILD.bazel#L93)):*
> ```Starlark
>     "@maven//:com_deftlabs_mongo_java_distributed_lock",
>     "@maven//:com_eclipsesource_j2v8_j2v8_macosx_x86_64",
>     "@maven//:com_esotericsoftware_kryo",
> ```

also this list of dependency is huge, please work with @gn-harness and @mdmilic to include the minimum possible dependencies. 


<!-- Sent from Reviewable.io -->

2023-01-19 22:14 UTC, raghuAtWings commented
*[`419-delegate-service-app/delegate-service-config.yml` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5F8qBsqZRYeBWapt:-NMB5F8qBsqZRYeBWapu:bsckw25) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/delegate-service-config.yml#L30)):*
> ```YAML
>   level: INFO
>   loggers:
>     com.novemberain.quartz.mongodb: WARN
> ```

please review these logging settings and only add what is necessary 


<!-- Sent from Reviewable.io -->

2023-01-19 22:15 UTC, raghuAtWings commented
*[`419-delegate-service-app/delegate-service-config.yml` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5Ptd6YY9rbEVHN9C:-NMB5Ptd6YY9rbEVHN9D:bkuhav1) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/delegate-service-config.yml#L46)):*
> ```YAML
>       threshold: TRACE
>       target: STDOUT
>       stackdriverLogEnabled: false
> ```

is it false for other services as well?


<!-- Sent from Reviewable.io -->

2023-01-19 22:15 UTC, raghuAtWings commented
*[`419-delegate-service-app/key.pem` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5U2q5trmH2sFdHJU:-NMB5U2q5trmH2sFdHJV:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/key.pem#L6)):*
> ```
> Key Attributes: <No Attributes>
> -----BEGIN PRIVATE KEY-----
> MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8TaI2yJI0bYqF
> ```

why do we need this?


<!-- Sent from Reviewable.io -->

2023-01-19 22:15 UTC, raghuAtWings commented
*[`419-delegate-service-app/keystore.jks` line 0 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5YotEGNbas2CCKlJ:-NMB5YotEGNbas2CCKlK:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/keystore.jks#L0)):*
why do we need this?


<!-- Sent from Reviewable.io -->

2023-01-19 22:17 UTC, raghuAtWings commented
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5ma1D4_Rzj3U3Y-1:-NMB5ma1D4_Rzj3U3Y-2:b29puyb) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/container/scripts/replace_configs.sh#L48)):*
> ```Shell
> fi
> 
> if [[ "" != "$GRPC_SERVER_CLASSIC_PORT" ]]; then
> ```

we shouldn't be copy pasting here, each of these entries should be the only one that are required


<!-- Sent from Reviewable.io -->

2023-01-19 22:18 UTC, raghuAtWings commented
*[`419-delegate-service-app/container/scripts/start_process.sh` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5yeIBEtndEzPNf3H:-NMB5yeIBEtndEzPNf3I:b-7bmivk) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/container/scripts/start_process.sh#L15)):*
> ```Shell
> 
> if [[ -z "$MEMORY" ]]; then
>    export MEMORY=4096
> ```

why 4 gb? we should strive to run it under 2 gb and preferably under 1 gb


<!-- Sent from Reviewable.io -->

2023-01-19 22:19 UTC, raghuAtWings commented
*[`419-delegate-service-app/container/scripts/start_process.sh` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6DWzCK8UaLv1S-UP:-NMB6DWzCK8UaLv1S-UQ:ba9j950) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/container/scripts/start_process.sh#L46)):*
> ```Shell
> fi
> 
> if [[ "${DEPLOY_MODE}" == "KUBERNETES" ]] || [[ "${DEPLOY_MODE}" == "KUBERNETES_ONPREM" ]]; then
> ```

why these checks? even in on prem we run everything using kubernetes. This should be a simpler command


<!-- Sent from Reviewable.io -->

2023-01-19 22:21 UTC, raghuAtWings commented
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6iVIBW9yhz7CFB0w:-NMB6iVJ4w_zgcy036kA:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java#L8)):*
> ```Java
> import net.sourceforge.argparse4j.inf.Namespace;
> 
> public class InspectCommand<T extends io.dropwizard.Configuration> extends ConfiguredCommand<T> {
> ```

why do we need this?


<!-- Sent from Reviewable.io -->

2023-01-19 22:21 UTC, raghuAtWings commented
*[`419-delegate-service-app/src/main/resources/localhost.pem` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6vk28bqSoNJMDELp:-NMB6vk28bqSoNJMDELq:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/resources/localhost.pem#L2)):*
> ```
> -----BEGIN CERTIFICATE-----
> MIIDcTCCAlmgAwIBAgIEAetBozANBgkqhkiG9w0BAQsFADBpMQswCQYDVQQGEwJV
> ```

why do we need this?


<!-- Sent from Reviewable.io -->

2023-01-19 22:22 UTC, raghuAtWings commented
*[`419-delegate-service-app/src/main/resources/redisson-jcache.yaml` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB7-OZ6RF0mgUOCQZU:-NMB7-O_0_7A5n4Efflo:bq2x6gu) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/resources/redisson-jcache.yaml#L1)):*
> ```YAML
> singleServerConfig:
> ```

why a separate file? why not part of the main config file?


<!-- Sent from Reviewable.io -->

2023-01-19 22:23 UTC, raghuAtWings commented
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationTestBase.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB7KcqDWdVHFR0LTsY:-NMB7KcqDWdVHFR0LTsZ:bl0cqet) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationTestBase.java#L29)):*
> ```Java
> 
>   public static String getResourceFilePath(String filePath) {
>     return isBazelTest() ? "419-delegate-service-app/src/test/resources/" + filePath
> ```

now all tests are bazel so no need of checking isBazelTest


<!-- Sent from Reviewable.io -->

2023-01-19 22:24 UTC, raghuAtWings reviewed
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-19 22:56 UTC, gn-harness commented
> 

You should use BuildCleaner (https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21178155054/Build+Cleaner+101) to generate build file.

Ideally, you should be generating a per package build file. However, if for any reason you want to have a top-level target use something like "time bazel run  tools/build-cleaner/src/main/java/io/harness/buildcleaner:build_cleaner -- --workspace=$PWD --module 945-license-usage-sdk --srcsGlob="src/main/java/**/*.java"

2023-01-23 08:13 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: Some of the checks are too old. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/delegate-service-config.yml` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5F8qBsqZRYeBWapt:-NMSTrcqAjgbMYxObBFk:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/delegate-service-config.yml#L30)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

please review these logging settings and only add what is necessary 
</blockquote></details>

done
___
*[`419-delegate-service-app/delegate-service-config.yml` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5Ptd6YY9rbEVHN9C:-NMSLC4f3PFwwFIKLZJk:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/delegate-service-config.yml#L46)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

is it false for other services as well?
</blockquote></details>

yes



_Code quote:_
```YAML
stackdriverLogEnabled
```
___
*[`419-delegate-service-app/key.pem` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5U2q5trmH2sFdHJU:-NMSfQHBBFcLcDQmejTC:bpgitdi) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/key.pem#L6)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

This is not used as of now but will be used in grpc communication. Discussed with @abhinav-harness and copied same key which was used by old DMS.
___
*[`419-delegate-service-app/keystore.jks` line  at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5YotEGNbas2CCKlJ:-NMSfaaN3aMPEg1TKldJ:baba9p2) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/keystore.jks#L)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

will be used for grpc communication over http2. 
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5ma1D4_Rzj3U3Y-1:-NMSTgmlE__isw2N9x9q:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/container/scripts/replace_configs.sh#L48)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we shouldn't be copy pasting here, each of these entries should be the only one that are required
</blockquote></details>

done
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5yeIBEtndEzPNf3H:-NMSdUCo8-GOMZwz5NeT:b-r9oddj) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/container/scripts/start_process.sh#L15)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why 4 gb? we should strive to run it under 2 gb and preferably under 1 gb
</blockquote></details>

got it. changed to 1gb
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6DWzCK8UaLv1S-UP:-NMSenXH5FSQ5OHHzPDP:b-b5c35t) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/container/scripts/start_process.sh#L46)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why these checks? even in on prem we run everything using kubernetes. This should be a simpler command
</blockquote></details>

changed.
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6iVIBW9yhz7CFB0w:-NMSetBN7SkaCO_OM74K:b-czux3s) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java#L8)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

not entirely sure about the usage of this inspect command. Went through some slack thread and seems like it is somewhat related to mongo indexing. Discussed with @jennyjames21 and @arpit3107, if not required, we can remove this.


<!-- Sent from Reviewable.io -->

2023-01-23 08:33 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: Some of the checks are too old. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/resources/redisson-jcache.yaml` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB7-OZ6RF0mgUOCQZU:-NMSkWz5BcZ9KEp3PCqC:b-wtnuq7) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/resources/redisson-jcache.yaml#L1)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why a separate file? why not part of the main config file?
</blockquote></details>

CacheModule loads configuration from this file: https://github.com/harness/harness-core/blob/develop/960-persistence/src/main/java/io/harness/cache/CacheModule.java#L151


<!-- Sent from Reviewable.io -->

2023-01-24 06:12 UTC, raghuAtWings commented
*[`419-delegate-service-app/key.pem` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5U2q5trmH2sFdHJU:-NMXOo6gC6EmWML7ni3f:b-77z4ky) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/key.pem#L6)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

This is not used as of now but will be used in grpc communication. Discussed with @abhinav-harness and copied same key which was used by old DMS.
</blockquote></details>

lets add it when needed, but i also don't understand why this will be needed in grpc. 


<!-- Sent from Reviewable.io -->

2023-01-24 09:36 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 17 file(s) to review. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationTestBase.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB7KcqDWdVHFR0LTsY:-NMY7b-49Ipznji4gx50:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationTestBase.java#L29)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

now all tests are bazel so no need of checking isBazelTest
</blockquote></details>

Done.
___
*[`419-delegate-service-app/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB4a--ByxHR3oqBp15:-NMY7cEx6EnAo272U6ML:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/BUILD.bazel#L19)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why does it need so many modules like ce-views, ng-core-clients, expression-service etc. Please add the least possible modules 
</blockquote></details>

Done.
___
*[`419-delegate-service-app/BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB4qZfD-0pIAA12BhD:-NMY7c_21rxrk57INZzO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/BUILD.bazel#L93)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

also this list of dependency is huge, please work with @gn-harness and @mdmilic to include the minimum possible dependencies. 
</blockquote></details>

Done.
___
*[`419-delegate-service-app/key.pem` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5U2q5trmH2sFdHJU:-NMY7dl6EDQ45ghTlykt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/key.pem#L6)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

lets add it when needed, but i also don't understand why this will be needed in grpc. 
</blockquote></details>

Done.
___
*[`419-delegate-service-app/src/main/resources/localhost.pem` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6vk28bqSoNJMDELp:-NMY7eq-ADQHoVyLAsgS:brpmqc3) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/resources/localhost.pem#L2)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

removed.


<!-- Sent from Reviewable.io -->

2023-01-25 05:11 UTC, raghuAtWings commented
*[`419-delegate-service-app/keystore.jks` line  at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5YotEGNbas2CCKlJ:-NMbKOe5AO-7_1Q5fJwm:b-thbhah) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/keystore.jks#L)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

will be used for grpc communication over http2. 
</blockquote></details>

we should add it when needed. i am still not sure why there is a need for this for grpc


<!-- Sent from Reviewable.io -->

2023-01-25 05:13 UTC, raghuAtWings commented
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6iVIBW9yhz7CFB0w:-NMbKyFNDaZQbjmTSZsJ:b-9ixyj2) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java#L8)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

not entirely sure about the usage of this inspect command. Went through some slack thread and seems like it is somewhat related to mongo indexing. Discussed with @jennyjames21 and @arpit3107, if not required, we can remove this.
</blockquote></details>

lets remove it and add when we know its needed


<!-- Sent from Reviewable.io -->

2023-01-25 05:14 UTC, raghuAtWings reviewed
> Reviewed 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-25 06:12 UTC, jennyjames21 commented
*[`419-delegate-service-app/config/delegate-service-config.yml` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbYWRMB39gCqdNP-S8:-NMbYWRMB39gCqdNP-S9:b-cwg2x3) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/config/delegate-service-config.yml#L13)):*
> ```YAML
>       port: 3458
>       maxRequestHeaderSize: 100KiB
>   adminConnectors:
> ```

Do we need a


<!-- Sent from Reviewable.io -->

2023-01-25 06:13 UTC, jennyjames21 commented
*[`419-delegate-service-app/config/delegate-service-config.yml` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbYWRMB39gCqdNP-S8:-NMbYcl38LQHhRU6S2z-:b-le85ab) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/config/delegate-service-config.yml#L13)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Do we need a
</blockquote></details>

adminConnectors? i dont this is used in manager either. 


<!-- Sent from Reviewable.io -->

2023-01-25 06:22 UTC, jennyjames21 commented
*[`419-delegate-service-app/keystore.jks` line  at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5YotEGNbas2CCKlJ:-NMb_CY296GGqIeYksQ4:b-y2zees) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/keystore.jks#L)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should add it when needed. i am still not sure why there is a need for this for grpc
</blockquote></details>

i think this is needed for gRpc to work for inter-service communication also


<!-- Sent from Reviewable.io -->

2023-01-25 06:29 UTC, jennyjames21 commented
*[`419-delegate-service-app/config/redisson-jcache.yaml` line 5 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbaTbo1sCifo21Fhul:-NMbaTbo1sCifo21Fhum:b5spms8) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/config/redisson-jcache.yaml#L5)):*
> ```YAML
> codec: !<io.harness.redis.RedissonKryoCodec> {}
> nettyThreads: 16
> useScriptCache: true
> ```

Our config/address will be coming from config.yaml file. Config also nettyThreads and useScriptCache 

We may not need a copy of this in delegate service as we planning to use harness core Redis client which has this option set.


<!-- Sent from Reviewable.io -->

2023-01-25 06:35 UTC, jennyjames21 commented
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbcda_A-eGWcVs9kmL:-NMbcda_A-eGWcVs9kmM:bqh0jj9) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L55)):*
> ```Java
>     log.info("Starting Delegate Service App");
>     ExecutorModule.getInstance().setExecutorService(ThreadPool.create(
>             20, 1000, 500L, TimeUnit.MILLISECONDS, new ThreadFactoryBuilder().setNameFormat("main-app-pool-%d").build()));
> ```

Should poolsize, idletime, timout be coming from config?



_Code quote:_
```Java
main-app-pool
```


<!-- Sent from Reviewable.io -->

2023-01-25 06:46 UTC, jennyjames21 commented
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbeF9B2tmZcaAEWQ1D:-NMbeF9B2tmZcaAEWQ1E:b-rlsmlw) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L77)):*
> ```Java
>   }
> 
>   public static void configureObjectMapper(final ObjectMapper mapper) {
> ```

Below code can be replaced with common method from HObjectMapper. 
HObjectMapper.configureObjectMapperForNG(mapper);

Look like we may need most of the modules. except one(not sure about  NGHarnessJacksonModule())



_Code quote:_
```Java
onfigureObjectMapper(
```


<!-- Sent from Reviewable.io -->

2023-01-25 06:50 UTC, jennyjames21 reviewed
> Reviewed 3 of 23 files at r1, 5 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 3. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-25 06:54 UTC, jennyjames21 commented
*[`419-delegate-service-app/config/delegate-service-config.yml` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbYWRMB39gCqdNP-S8:-NMbgU2sEtyY8Nggc9uc:b-x7vaev) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/config/delegate-service-config.yml#L13)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

adminConnectors? i dont this is used in manager either. 
</blockquote></details>

I think it's needed for dropwizard to start but please check.

Pipeline Service is a good example to refer IMO.  This is how their config looks like, no keystore password and cerrts 

server:
  applicationConnectors:
    - type: http
      port: 12001
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 12002
  requestLog:
    appenders: []
  maxThreads: 1024


<!-- Sent from Reviewable.io -->

2023-01-25 06:58 UTC, jennyjames21 reviewed
> Reviewed 7 of 23 files at r1, 12 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 3. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-25 09:32 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/config/delegate-service-config.yml` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbYWRMB39gCqdNP-S8:-NMcF5muD-SVdzqWH6Bz:by25b7l) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/config/delegate-service-config.yml#L13)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

I think it's needed for dropwizard to start but please check.

Pipeline Service is a good example to refer IMO.  This is how their config looks like, no keystore password and cerrts 

server:
  applicationConnectors:
    - type: http
      port: 12001
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 12002
  requestLog:
    appenders: []
  maxThreads: 1024
</blockquote></details>

It is not a mandatory field, It basically spawns an endpoint: url/admin using which we can access metrics, ping, healthCheck, threadDump, memory and heap related data for dropwizard application. I think it's more useful if we add things specifically to MetricsServlet let's say, however we don't add anything using MetricServlet.

I think it should be okay to keep it.
source: https://www.baeldung.com/dropwizard-metrics#6-adminservlet-usage

We can remove keystore and cert, if we expose an http endpoint for admin connector.


<!-- Sent from Reviewable.io -->

2023-01-25 09:34 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB6iVIBW9yhz7CFB0w:-NMcGnV6-ABuBdEi2Olb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/src/main/java/io/harness/dms/app/InspectCommand.java#L8)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

lets remove it and add when we know its needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-25 09:53 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbcda_A-eGWcVs9kmL:-NMcL1bv2KlKX2KMbKoY:b-v2du60) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L55)):*
> main-app-pool

done added to config.yml


<!-- Sent from Reviewable.io -->

2023-01-25 09:57 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbeF9B2tmZcaAEWQ1D:-NMcM-F40s2APWy-zv7A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L77)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Below code can be replaced with common method from HObjectMapper. 
HObjectMapper.configureObjectMapperForNG(mapper);

Look like we may need most of the modules. except one(not sure about  NGHarnessJacksonModule())
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-25 10:45 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/config/redisson-jcache.yaml` line 5 at r2](https://reviewable.io/reviews/harness/harness-core/42825#-NMbaTbo1sCifo21Fhul:-NMcWzCn0X-tLRFFsp7v:bgnv1ys) ([raw file](https://github.com/harness/harness-core/blob/61f234979132b8601fb3c6a04c2d283b778cf0d5/419-delegate-service-app/config/redisson-jcache.yaml#L5)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Our config/address will be coming from config.yaml file. Config also nettyThreads and useScriptCache 

We may not need a copy of this in delegate service as we planning to use harness core Redis client which has this option set.

</blockquote></details>

will sync with you regarding this.


<!-- Sent from Reviewable.io -->

2023-01-25 14:06 UTC, mdmilic requested changes
> Reviewed 5 of 23 files at r1, 5 of 17 files at r2, 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 4 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/config/BUILD.bazel` line 6 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcquNL6wcOFIUzHjnh:-NMcquNNDi2mWHzdfm3E:b-cpzpku) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/config/BUILD.bazel#L6)):*
> ```Starlark
> # https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
> 
> exports_files(
> ```

This doesn't seem that it's needed (yet), you don't even have `419-delegate-service-app/build` subfolder. I think you can remove this entire file. 
___
*[`419-delegate-service-app/container/BUILD.bazel` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcwDG11AUW6TtOOOvV:-NMcwDG11AUW6TtOOOvW:bdq3tz7) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/BUILD.bazel#L27)):*
> ```Starlark
>     name = "files",
>     srcs = [
>         "//419-delegate-service-app/config:delegate-service-config.yml",
> ```

Does running this target work? Not exactly sure but these files should be private and not visible to the target. You `files_export` visibility is not configured on container folder



_Code quote:_
```Starlark
        "//419-delegate-service-app/config:delegate-service-config.yml",
        "//419-delegate-service-app/config:keystore.jks"
    ],
```
___
*[`419-delegate-service-app/container/BUILD.bazel` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcvtcUCDwLCpd77SLL:-NMcvtcUCDwLCpd77SLM:b-c2aup2) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/BUILD.bazel#L31)):*
> ```Starlark
>     ],
>     files = {
>         "@alpn_boot_8.1.13.v20181017//file": "alpn-boot-8.1.13.v20181017.jar",
> ```

You don't need alpn boot for JDK11 any more
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd-TP33RHo3GeZ4XR6:-NMd-TP33RHo3GeZ4XR7:bghwjq0) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L19)):*
> ```Shell
> 
> yq -i 'del(.server.applicationConnectors[0])' $CONFIG_FILE
> yq -i 'del(.grpcServerConfig.connectors[0])' $CONFIG_FILE
> ```

Why do we need this? These keys don't exist in our config.yaml anyway. 



_Code quote:_
```Shell
yq -i 'del(.server.applicationConnectors[0])' $CONFIG_FILE
yq -i 'del(.grpcServerConfig.connectors[0])' $CONFIG_FILE
yq -i 'del(.grpcServerClassicConfig.connectors[0])' $CONFIG_FILE
```
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd-xXDAmQ_pUnq1UOH:-NMd-xXDAmQ_pUnq1UOI:bkhpekf) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L23)):*
> ```Shell
> 
> 
> yq -i '.server.adminConnectors=[]' $CONFIG_FILE
> ```

Why removing admin connectors like this? If we don't need them, just remove them from config.yaml
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd0Ljh0JbCeM1jRo0e:-NMd0Ljh0JbCeM1jRo0f:b-p0eib0) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L33)):*
> ```Shell
>   for ITEM in "${LOGGER_ITEMS[@]}"; do
>     LOGGER=`echo $ITEM | awk -F= '{print $1}'`
>     LOGGER_LEVEL=`echo $ITEM | awk -F= '{print $2}'`
> ```

Lets get rid of this. No point in dynamically adding loggers. If needed we should modify config.yaml



_Code quote:_
```Shell
if [[ "" != "$LOGGERS" ]]; then
  IFS=',' read -ra LOGGER_ITEMS <<< "$LOGGERS"
  for ITEM in "${LOGGER_ITEMS[@]}"; do
    LOGGER=`echo $ITEM | awk -F= '{print $1}'`
    LOGGER_LEVEL=`echo $ITEM | awk -F= '{print $2}'`
    export LOGGER_LEVEL; export LOGGER; yq -i '.logging.loggers.[env(LOGGER)]=env(LOGGER_LEVEL)' $CONFIG_FILE
  done
fi
```
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd1lGE53J5U1A8YS5o:-NMd1lGE53J5U1A8YS5p:b2xkbkm) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L48)):*
> ```Shell
> fi
> 
> yq -i '.server.requestLog.appenders[0].threshold="TRACE"' $CONFIG_FILE
> ```

If we always want trace lvl logging, just do it in the config.yaml
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd1sI81NPWTIR2VMPG:-NMd1sI81NPWTIR2VMPH:bnxmrgx) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L57)):*
> ```Shell
>   if [[ "$ROLLING_FILE_LOGGING_ENABLED" == "true" ]]; then
>     yq -i 'del(.logging.appenders[1])' $CONFIG_FILE
>     yq -i '.logging.appenders[1].currentLogFilename="/opt/harness/logs/delegate-service.log"' $CONFIG_FILE
> ```

Let's get rid of all of these options. We will add them when necessary, but I don't think most of them are. 



_Code quote:_
```Shell
if [[ "" != "$SERVER_PORT" ]]; then
  export SERVER_PORT; yq -i '.server.applicationConnectors[0].port=env(SERVER_PORT)' $CONFIG_FILE
else
  yq -i '.server.applicationConnectors[0].port=9080' $CONFIG_FILE
fi

if [[ "" != "$SERVER_MAX_THREADS" ]]; then
  export SERVER_MAX_THREADS; yq -i '.server.maxThreads=env(SERVER_MAX_THREADS)' $CONFIG_FILE
fi

yq -i '.server.requestLog.appenders[0].threshold="TRACE"' $CONFIG_FILE

if [[ "$STACK_DRIVER_LOGGING_ENABLED" == "true" ]]; then
  yq -i 'del(.logging.appenders[2])' $CONFIG_FILE
  yq -i 'del(.logging.appenders[0])' $CONFIG_FILE
  yq -i '.logging.appenders[0].stackdriverLogEnabled=true' $CONFIG_FILE
else
  if [[ "$ROLLING_FILE_LOGGING_ENABLED" == "true" ]]; then
    yq -i 'del(.logging.appenders[1])' $CONFIG_FILE
    yq -i '.logging.appenders[1].currentLogFilename="/opt/harness/logs/delegate-service.log"' $CONFIG_FILE
    yq -i '.logging.appenders[1].archivedLogFilenamePattern="/opt/harness/logs/delegate-service.%d.%i.log"' $CONFIG_FILE
  else
    yq -i 'del(.logging.appenders[2])' $CONFIG_FILE
    yq -i 'del(.logging.appenders[1])' $CONFIG_FILE
  fi
```
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd2wLPAgWsWeT5W-8Y:-NMd2wLQCoK9bc2v638C:b-kefs5v) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L19)):*
> ```Shell
> 
> if [[ -z "$COMMAND" ]]; then
>    export COMMAND=server
> ```

Let's make this entire thing simpler. No need to follow what other services do, that's just 6y of tech dept. We have a chance to start fresh



_Code quote:_
```Shell
if [[ -z "$COMMAND" ]]; then
   export COMMAND=server
fi
```
___
*[`419-delegate-service-app/keystore.jks` line  at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5YotEGNbas2CCKlJ:-NMcuz6q3Bea3E_Lh_-G:b9nghjl) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/keystore.jks#L)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i think this is needed for gRpc to work for i [...]

2023-01-26 00:47 UTC, jennyjames21 commented
*[`419-delegate-service-app/keystore.jks` line  at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5YotEGNbas2CCKlJ:-NMfXCW56D2fvAcMiS5Q:b7lljiu) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/keystore.jks#L)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Doesn't seem like something we should be committing to the GH. This stores private keys. 
</blockquote></details>

i think it's only for internal service communication. all services have a copy of this in harness-core.  
Agree ideally it should be in a restricted different repo.
 


<!-- Sent from Reviewable.io -->

2023-01-26 11:06 UTC, mdmilic requested changes
> Reviewed 3 of 23 files at r1, 10 of 17 files at r2, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdcN65709xp1-ZPfjb:-NMdcN65709xp1-ZPfjc:b-l6mwxj) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L25)):*
> ```Shell
> 
> if [[ -z "$CAPSULE_JAR" ]]; then
>    export CAPSULE_JAR=/opt/harness/delegate-service-capsule.jar
> ```

remove



_Code quote:_
```Shell
if [[ -z "$CAPSULE_JAR" ]]; then
   export CAPSULE_JAR=/opt/harness/delegate-service-capsule.jar
fi
```
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdcLos9W2BwyAnmx-Q:-NMdcLos9W2BwyAnmx-R:b-l6mwxj) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L31)):*
> ```Shell
> if [[ "${ENABLE_G1GC}" == "true" ]]; then
>     export GC_PARAMS=" -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=40 -XX:MaxGCPauseMillis=1000 -Dfile.encoding=UTF-8"
> else
> ```

remove



_Code quote:_
```Shell
if [[ "${ENABLE_G1GC}" == "true" ]]; then
    export GC_PARAMS=" -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=40 -XX:MaxGCPauseMillis=1000 -Dfile.encoding=UTF-8"
else
    export GC_PARAMS=" -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -Dfile.encoding=UTF-8"
fi
```
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdcTRiDIgh1AJEuLNi:-NMdcTRiDIgh1AJEuLNj:b-lqu2l) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L35)):*
> ```Shell
> fi
> 
> export JAVA_OPTS="-Xms${MEMORY}m -Xmx${MEMORY}m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/heapdump -Xloggc:mygclogfilename.gc $GC_PARAMS $JAVA_ADVANCED_FLAGS"
> ```

Remove Xms/Xmx use percentage of the container, similar to what delegate does
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdc5UL9wqEBXA7XXFi:-NMdc5UL9wqEBXA7XXFj:b-674i5i) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L39)):*
> ```Shell
> 
> if [[ "${ENABLE_APPDYNAMICS}" == "true" ]]; then
>     mkdir /opt/harness/AppServerAgent-1.8-21.11.2.33305 && unzip AppServerAgent-1.8-21.11.2.33305.zip -d /opt/harness/AppServerAgent-1.8-21.11.2.33305
> ```

This should happen on image build. Here if we want to enable it, just add java_opts
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMe1BN4BpIkDuIKl79-:-NMe1BN62t156Pdl9bh1:b-6z9kc0) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L55)):*
> ```Java
> @OwnedBy(DEL)
> public class DelegateServiceConfiguration extends Configuration {
>   @JsonProperty("swagger") private SwaggerBundleConfiguration swaggerBundleConfiguration;
> ```

remove swaggerBundleConfig from here. It doesn't exist in the config.yaml. This class should reflect config.yaml.  Make the other one final. 
Make swagger bundle static in the DelegateServiceApp (or a separate utility class around there)



_Code quote:_
```Java
  @JsonProperty("swagger") private SwaggerBundleConfiguration swaggerBundleConfiguration;
  @JsonProperty("commonPoolConfig") private ThreadPoolConfig commonPoolConfig;
```
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMe2WA-5nXGAfc3YlQB:-NMe2WA-5nXGAfc3YlQC:bm6wl1i) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L92)):*
> ```Java
> 
>   private RequestLogFactory getDefaultlogbackAccessRequestLogFactory() {
>     LogbackAccessRequestLogFactory logbackAccessRequestLogFactory = new LogbackAccessRequestLogFactory();
> ```

I don't think you need any of this. All should come from the config.yaml and get automatically deserialized by dropwizard



_Code quote:_
```Java
  public DelegateServiceConfiguration() {
    DefaultServerFactory defaultServerFactory = new DefaultServerFactory();
    defaultServerFactory.setJerseyRootPath("/api");
    defaultServerFactory.setRegisterDefaultExceptionMappers(false);
    defaultServerFactory.setAdminContextPath("/admin");
    defaultServerFactory.setAdminConnectors(singletonList(getDefaultAdminConnectorFactory()));
    defaultServerFactory.setApplicationConnectors(singletonList(getDefaultApplicationConnectorFactory()));
    defaultServerFactory.setRequestLogFactory(getDefaultlogbackAccessRequestLogFactory());
    super.setServerFactory(defaultServerFactory);
  }

  @Override
  public void setServerFactory(ServerFactory factory) {
    DefaultServerFactory defaultServerFactory = (DefaultServerFactory) factory;
    ((DefaultServerFactory) getServerFactory())
        .setApplicationConnectors(defaultServerFactory.getApplicationConnectors());
    ((DefaultServerFactory) getServerFactory()).setAdminConnectors(defaultServerFactory.getAdminConnectors());
    ((DefaultServerFactory) getServerFactory()).setRequestLogFactory(defaultServerFactory.getRequestLogFactory());
    ((DefaultServerFactory) getServerFactory()).setMaxThreads(defaultServerFactory.getMaxThreads());
  }

  protected ConnectorFactory getDefaultAdminConnectorFactory() {
    final HttpConnectorFactory factory = new HttpConnectorFactory();
    factory.setPort(9081);
    return factory;
  }

  protected ConnectorFactory getDefaultApplicationConnectorFactory() {
    final HttpConnectorFactory factory = new HttpConnectorFactory();
    factory.setPort(9080);
    return factory;
  }

  private RequestLogFactory getDefaultlogbackAccessRequestLogFactory() {
    LogbackAccessRequestLogFactory logbackAccessRequestLogFactory = new LogbackAccessRequestLogFactory();
    FileAppenderFactory<IAccessEvent> fileAppenderFactory = new FileAppenderFactory<>();
    fileAppenderFactory.setArchive(true);
    fileAppenderFactory.setCurrentLogFilename("access.log");
```
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhe4Xf6mimtcDvPotF:-NMhe4XhDuOtwfEx_-A_:bgrep6t) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L119)):*
> ```Java
>   }
> 
>   public static Collection<Class<?>> getResourceClasses() {
> ```

Don't use reflection for this, add resource classes explicitly (we shouldn't have too many of them)
___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhhBcU-AK52uf6hhea:-NMhhBcU-AK52uf6hheb:b-j03qay) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java#L45)):*
> ```Java
>     // Handle sandboxed bazel path - remove path starting from /sandbox till execroot. This  [...]

2023-01-26 16:27 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/config/BUILD.bazel` line 6 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcquNL6wcOFIUzHjnh:-NMislRK-V2WHIOTK5xB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/config/BUILD.bazel#L6)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This doesn't seem that it's needed (yet), you don't even have `419-delegate-service-app/build` subfolder. I think you can remove this entire file. 
</blockquote></details>

Done.
___
*[`419-delegate-service-app/container/BUILD.bazel` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcvtcUCDwLCpd77SLL:-NMitEU10vGGqWdNqATH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/BUILD.bazel#L31)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You don't need alpn boot for JDK11 any more
</blockquote></details>

Done.
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd-TP33RHo3GeZ4XR6:-NMithx998wPqb1nF-ai:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L19)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why do we need this? These keys don't exist in our config.yaml anyway. 
</blockquote></details>

Done.
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd-xXDAmQ_pUnq1UOH:-NMitiE76icaTLnxU5UE:b-2078eh) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L23)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why removing admin connectors like this? If we don't need them, just remove them from config.yaml
</blockquote></details>

Done. removing adminConnectors from yaml, will add later if needed.
___
*[`419-delegate-service-app/config/delegate-service-config.yml` line 2 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd-cao2VgHA0DxACmC:-NMisvsl2QFJIKVCXh7n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/config/delegate-service-config.yml#L2)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Rename it to just config.yaml
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-27 08:14 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd0Ljh0JbCeM1jRo0e:-NMm5l21DJLZCGGB_CN1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L33)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Lets get rid of this. No point in dynamically adding loggers. If needed we should modify config.yaml
</blockquote></details>

Done.
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd1lGE53J5U1A8YS5o:-NMm7ne20yZYGVK4kwCd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L48)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

If we always want trace lvl logging, just do it in the config.yaml
</blockquote></details>

Done.



_Code quote:_
```Shell
yq -i '.server.requestLog.appenders[0].threshold="TRACE"' $CONFIG_FILE
```
___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMd1sI81NPWTIR2VMPG:-NMmHINW8PrFbtvsMY7L:baecr2j) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/replace_configs.sh#L57)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Let's get rid of all of these options. We will add them when necessary, but I don't think most of them are. 
</blockquote></details>

Removed STACK_DRIVER_LOGGING_ENABLED and ROLLING_FILE_LOGGING_ENABLED conditions, keeping SERVER_MAX_THREADS and SERVER_PORT for now. 


<!-- Sent from Reviewable.io -->

2023-01-27 10:48 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 14. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdcLos9W2BwyAnmx-Q:-NMmoOLf-Yu1LU9xbSo_:b-oz27mp) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L31)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Removing, I had a quick look on G1GC vs old parallelGC, parallelGC is default one and G1GC is mostly recommended with system with large heap sizes > 6GB mostly. I think we would not require heap > 6GB. We can use old parallelGC itself. 
regarding MaxGCPauseMillis, I had a look over recommendations and it is suggested to keep it at 200 here: https://docs.oracle.com/cd/E40972_01/doc.70/e40973/cnf_jvmgc.htm#autoId1 shall we do that? Not sure how we come up with value of 500.
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdcTRiDIgh1AJEuLNi:-NMmmgq_1tt_s5WSnAZ1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L35)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Remove Xms/Xmx use percentage of the container, similar to what delegate does
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-27 11:00 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdc5UL9wqEBXA7XXFi:-NMmqWzRDG3ygK8s458l:b-alt0u4) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L39)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This should happen on image build. Here if we want to enable it, just add java_opts
</blockquote></details>

okay, I think there will be a tradeoff, generally we don't use app-dynamics but if we add this in dockerfile, we will create directory and unzip always.


<!-- Sent from Reviewable.io -->

2023-01-27 11:01 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/BUILD.bazel` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcwDG11AUW6TtOOOvV:-NMmsrv77IIWsOmo2bMy:b9ztgq2) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/BUILD.bazel#L27)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Does running this target work? Not exactly sure but these files should be private and not visible to the target. You `files_export` visibility is not configured on container folder
</blockquote></details>

was not working before, due to incorrect naming of deploy.jar, corrected it.


<!-- Sent from Reviewable.io -->

2023-01-27 11:02 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/BUILD.bazel` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcwDG11AUW6TtOOOvV:-NMmt-7n6ub0umLrRW7y:bhk0mwi) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/BUILD.bazel#L27)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

was not working before, due to incorrect naming of deploy.jar, corrected it.
</blockquote></details>

build targets in this file are not invoked during normal bazel build repo/... when do we invoke this ?


<!-- Sent from Reviewable.io -->

2023-01-27 13:15 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 19. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMe2WA-5nXGAfc3YlQB:-NMnLp4yE-yYnigSXu5l:bfk4avv) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L92)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I don't think you need any of this. All should come from the config.yaml and get automatically deserialized by dropwizard
</blockquote></details>

Cleared not needed code, applicationContextPath when specified in config.yml wasn't working. so left defaultServerFactory.setJerseyRootPath("/api"); as is.


<!-- Sent from Reviewable.io -->

2023-01-27 13:21 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 20. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMe1BN4BpIkDuIKl79-:-NMnNzWb4H6auX_88PPV:bc4oy7g) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L55)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

remove swaggerBundleConfig from here. It doesn't exist in the config.yaml. This class should reflect config.yaml.  Make the other one final. 
Make swagger bundle static in the DelegateServiceApp (or a separate utility class around there)
</blockquote></details>

done, cannot make commonPoolConfig final as it is not initialised.


<!-- Sent from Reviewable.io -->

2023-01-28 20:39 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: Some of the checks are too old. 1 change requests. 25. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhe4Xf6mimtcDvPotF:-NMtucTRC1p7yd7sw62d:bwkz1sp) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L119)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Don't use reflection for this, add resource classes explicitly (we shouldn't have too many of them)
</blockquote></details>

I think we will have at least more than 8 resource classes, adding them explicitly would look untidy.
___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhhBcU-AK52uf6hhea:-NMu5Mi75iN6eXeKbvrc:b1kw6gm) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java#L45)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This is quite a weird way to get to the config file. Try loading it as a resource instead. E.g. something like (untested):

```Paths.get(getClass().getResource(CONFIG_FILE).toURI()).toString();```

</blockquote></details>

makes sense, facing some issues while loading as resource, will add separately in another pr.
___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhfrRgCSFSZEvXsWe2:-NMtuJlOD4jG6gi5irnP:b8fd61p) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java#L52)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why not making these changes in the test config directly 
</blockquote></details>

removed, this was optional. any port and type can be specified.
___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationTestBase.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhhpEz-zgGB9breKry:-NMu2d_t9i83c_Xzolii:b-2ryczp) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationTestBase.java#L19)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Do we need this and why? Doesn't seem you use mockito in the test and also no servers you are adding that will be autoclosed. Also, category test is quite bloated, you probably don't need that either. 
</blockquote></details>

Removing all, I'll use mockito later, will add mockito rule then. Removing dependency on categoryTest, got good insights from: https://harness.slack.com/archives/C01L5F4K2F4/p1651742823641229 .
Thanks.
___
*[`419-delegate-service-app/src/test/resources/test-delegate-service-config.yml` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhkNszAkNrxm7ozaiD:-NMtuSFvBwVAM2_LS0tw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/test/resources/test-delegate-service-config.yml#L40)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Don't think you need gke and file appender for tests
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 12:31 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 13 file(s) to review. 1 change requests. 25. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/config/BUILD.bazel` line 6 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMcquNL6wcOFIUzHjnh:-NN1eAra8Yhw4peb95ow:b-q7ayu4) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/config/BUILD.bazel#L6)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

changed visibility. exporting config.yml and .jks file was needed.


<!-- Sent from Reviewable.io -->

2023-01-30 12:33 UTC, AnupamIO commented
trigger copyrightcheck

2023-01-30 14:40 UTC, mdmilic requested changes
> Reviewed 11 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 2 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN1yFpp3zLD1y3uoAlL:-NN1yFpp3zLD1y3uoAlM:b-wpz43n) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/replace_configs.sh#L18)):*
> ```Shell
> }
> 
> yq -i 'del(.server.applicationConnectors[0])' $CONFIG_FILE
> ```

This just deletes the first application connector (the `h2` one) unconditionally. Just remove the connector from config.yaml and remove this. 
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdcLos9W2BwyAnmx-Q:-NN1zm7Y9hZPyr8fiEzW:b-s8r6x8) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L31)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

Removing, I had a quick look on G1GC vs old parallelGC, parallelGC is default one and G1GC is mostly recommended with system with large heap sizes > 6GB mostly. I think we would not require heap > 6GB. We can use old parallelGC itself. 
regarding MaxGCPauseMillis, I had a look over recommendations and it is suggested to keep it at 200 here: https://docs.oracle.com/cd/E40972_01/doc.70/e40973/cnf_jvmgc.htm#autoId1 shall we do that? Not sure how we come up with value of 500.
</blockquote></details>

G1GC is the default for Java 11. parallelGC was default for Java8. G1GC algorithm tries to minimise number of "pause the world" events, not sure where does 500 come from, 200 should be more than enough. I'd say lets just use defaults until we experience an issue. DMS is quite simple so shouldn't have problems with default GC. 
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdc5UL9wqEBXA7XXFi:-NN1zJQBAsZXB4rTRO2M:bz30m7t) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L39)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

okay, I think there will be a tradeoff, generally we don't use app-dynamics but if we add this in dockerfile, we will create directory and unzip always.
</blockquote></details>

This expects it to already be downloaded (by Dockerfile), so why not just have it unzipped and ready for usage as well (in Dockerfile)? Then here we just enable/disable it with env vars. I would also get rid of the versioned folder here, no point to it. The version should be just controlled through Dockerfile (i.e. which version gets downloaded, but then you unzip it to unversioned folder).
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 8 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN20YtL7pAbOAM53oLo:-NN20YtL7pAbOAM53oLp:b-lyg3ro) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/start_process.sh#L8)):*
> ```Shell
> 
> mkdir -p /opt/harness/logs
> touch /opt/harness/logs/delegate-service.log
> ```

Tbh I think this would create delegate-service.log with wrong permissions. Not sure why we would be doing it, but I would remove it for now. Logback should be more than capable to create this file. 
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 14 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN202X34d9fAclENgpI:-NN202X34d9fAclENgpJ:b-zalru8) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/start_process.sh#L14)):*
> ```Shell
> fi
> 
> export JAVA_OPTS="-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=40.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/heapdump -Xloggc:mygclogfilename.gc $GC_PARAMS $JAVA_ADVANCED_FLAGS"
> ```

You Don't have GC_PARAMS any more, remove it from the opts. The same for ADVANCED_FLAGS, I didn't find it being set. 
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN20OPUEgY3CgxgnDXW:-NN20OPUEgY3CgxgnDXX:bkkgoor) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/start_process.sh#L25)):*
> ```Shell
> fi
> 
> java $JAVA_OPTS -jar /opt/harness/delegate-service-capsule.jar server /opt/harness/delegate-service-config.yml
> ```

The config is now called just `config.yml`
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel` line 11 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN21N9X-6iU74VURE6Z:-NN21N9X-6iU74VURE6_:b5kv7on) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel#L11)):*
> ```Starlark
> 
> java_library(
>     name = "library",
> ```

Why this change? Not 100% sure, but I think you have to use the previous names. Our run_analysis macros expect that your library is named "module", if not you will not get checkstyle, sonar etc...
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhe4Xf6mimtcDvPotF:-NN22Cbf3aJAplrwSy1K:b4upnjr) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L119)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

I think we will have at least more than 8 resource classes, adding them explicitly would look untidy.
</blockquote></details>

We are working on getting rid of reflection altogether in general (as that would help with some other initiatives). In Java 11 you would only get warnings on usage, but after java 11 reflection is forbidden by JVM itself in most scenarios (including one you have). By default (IIRC) past Java11 you can only do reflection on the classes from the same module like yours. With bazel, every java package is a separate library, so that means you can only do reflection within same java package
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN24yN065QZrIg9u5av:-NN24yN065QZrIg9u5aw:buix5vj) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L77)):*
> ```Java
>   }
> 
>   private RequestLogFactory getDefaultlogbackAccessRequestLogFactory() {
> ```

You shouldn't be needing this, if you do, something is not right in the config.yaml (and we should look on fixing it there)
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN25hcG42NWshUWaWp4:-NN25hcG42NWshUWaWp5:b-16onwa) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L94)):*
> ```Java
>    * @return the swagger bundle configuration
>    */
>   public SwaggerBundleConfiguration getSwaggerBundleConfiguration() {
> ```

Make [...]

2023-01-30 14:41 UTC, mdmilic reviewed
> Reviewed 2 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-31 05:08 UTC, abhayganvir commented
trigger copyrightcheck

2023-01-31 05:14 UTC, abhayganvir commented
trigger abhaycopyrightcheck

2023-01-31 11:26 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN1yFpp3zLD1y3uoAlL:-NN2K1i0EEgMywoOK_UO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/replace_configs.sh#L18)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This just deletes the first application connector (the `h2` one) unconditionally. Just remove the connector from config.yaml and remove this. 
</blockquote></details>

done



_Code quote:_
```Shell
yq -i 'del(.server.applicationConnectors[0])' $CONFIG_FILE
```
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMdc5UL9wqEBXA7XXFi:-NN5wEgx1uVMnJPBT2zN:bk7yjkb) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/container/scripts/start_process.sh#L39)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This expects it to already be downloaded (by Dockerfile), so why not just have it unzipped and ready for usage as well (in Dockerfile)? Then here we just enable/disable it with env vars. I would also get rid of the versioned folder here, no point to it. The version should be just controlled through Dockerfile (i.e. which version gets downloaded, but then you unzip it to unversioned folder).
</blockquote></details>

Done, noted here: https://harness.atlassian.net/browse/DEL-5771 so we don't miss to unzip this file in DockerFile.
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 8 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN20YtL7pAbOAM53oLo:-NN5lk9b-SADyiNFnmIG:b-ro9bx9) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/start_process.sh#L8)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Tbh I think this would create delegate-service.log with wrong permissions. Not sure why we would be doing it, but I would remove it for now. Logback should be more than capable to create this file. 
</blockquote></details>

removed, this entire flow needs to be tested and will not work in current scenario because we don't have build_dist scripts (one purpose of this is to copy module.jar and config.yml to /opt directory). 
So this is just a placeholder, running this will throw exception because of missing files in /opt/harness.
jfyi: @bharatgoelharness 
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 14 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN202X34d9fAclENgpI:-NN2qWeKC-YkXy1MMgWC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/start_process.sh#L14)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You Don't have GC_PARAMS any more, remove it from the opts. The same for ADVANCED_FLAGS, I didn't find it being set. 
</blockquote></details>

Done.
___
*[`419-delegate-service-app/container/scripts/start_process.sh` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN20OPUEgY3CgxgnDXW:-NN5wuA13888atoVIX3n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/container/scripts/start_process.sh#L25)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

The config is now called just `config.yml`
</blockquote></details>

Done.
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel` line 11 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN21N9X-6iU74VURE6Z:-NN5y-E445fizBusDOGM:b-vhk5s5) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel#L11)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why this change? Not 100% sure, but I think you have to use the previous names. Our run_analysis macros expect that your library is named "module", if not you will not get checkstyle, sonar etc...
</blockquote></details>

- Changed this to maintain consistency, we mostly name our deployable jar as module_deploy.jar
- We have hardcoded this <module_deploy.jar> at few places as ik.
Example: this script is called while building artifacts from pr pipeline: https://github.com/harness/harness-core/blob/develop/scripts/bazel/bazel_script.sh and seems like it wants the deployment jar to be named as module_deploy.jar

I can name the library as module but then we need to change the name of java_binary. I'm afraid that we may need to change at other places because our jar will then look like. <new-name>_deploy.jar
___
*[`419-delegate-service-app/keystore.jks` line  at r1](https://reviewable.io/reviews/harness/harness-core/42825#-NMB5YotEGNbas2CCKlJ:-NN5lLYz4r0AKV9QACM5:biyc3m) ([raw file](https://github.com/harness/harness-core/blob/619e2f3ba134600207715f048c4c32da1e3e5039/419-delegate-service-app/keystore.jks#L)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i think it's only for internal service communication. all services have a copy of this in harness-core.  
Agree ideally it should be in a restricted different repo.
 
</blockquote></details>

removed jks file as discussed. will test rpc communication without it first.


<!-- Sent from Reviewable.io -->

2023-02-01 07:57 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhe4Xf6mimtcDvPotF:-NN6mizg4g_Qs4fiiZjg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L119)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

We are working on getting rid of reflection altogether in general (as that would help with some other initiatives). In Java 11 you would only get warnings on usage, but after java 11 reflection is forbidden by JVM itself in most scenarios (including one you have). By default (IIRC) past Java11 you can only do reflection on the classes from the same module like yours. With bazel, every java package is a separate library, so that means you can only do reflection within same java package
</blockquote></details>

Done.
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN24yN065QZrIg9u5av:-NNAy_Lm8MBXYel562j8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L77)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You shouldn't be needing this, if you do, something is not right in the config.yaml (and we should look on fixing it there)
</blockquote></details>

Done.
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN25hcG42NWshUWaWp4:-NN6cFkD4Ms7nFCxSXBV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceConfiguration.java#L94)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Make this static and put it in a separate class. Doesn't belong to this config I think. 
</blockquote></details>

Done.
___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhhBcU-AK52uf6hhea:-NNAybMP-KAU4Z0IyP9P:b5b9lm7) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java#L45)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Yep, I spent quite some time and debugging to figure it out at some point. You can find a working example here, but also let me know if you need help with that. 
How it's loaded:
https://github.com/harness/harness-core/blob/develop/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/K8STaskRunner.java#L83

Bazel setup (which I think you got right):
https://github.com/harness/harness-core/tree/develop/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources
https://github.com/harness/harness-core/blob/develop/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/BUILD.bazel#L29 <-- This can be in your test java_library
</blockquote></details>

Simplified. 


<!-- Sent from Reviewable.io -->

2023-02-01 08:17 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 12 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/42825#-NMhhBcU-AK52uf6hhea:-NNB1jBNE27u-BQVaGqC:b-pyl6jd) ([raw file](https://github.com/harness/harness-core/blob/aa697a1c9a3766ea5e28a72ef2a19c5704b24e0a/419-delegate-service-app/src/test/java/io/harness/delegate/service/DelegateServiceApplicationStartupTest.java#L45)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

Simplified. 
</blockquote></details>

Adding for future ref: tried couple of things here. We can point to configFile using: class.getResource(<file>) but this points to the file present inside jar file libtests.jar. When we provide this path (of inside of jar file) to dropwizard test support it will not work. so it's better to hardcode path to file as done.


<!-- Sent from Reviewable.io -->

2023-02-01 16:35 UTC, mdmilic submitted a review, later dismissed
> Reviewed 10 of 12 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 3. unresolved discussions. 

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel` line 11 at r4](https://reviewable.io/reviews/harness/harness-core/42825#-NN21N9X-6iU74VURE6Z:-NNCmaet3YmfrI2IzbLC:b-63a0wh) ([raw file](https://github.com/harness/harness-core/blob/0d18a5d2c786ad498a37b0331475cd2fbfe98e1a/419-delegate-service-app/src/main/java/io/harness/dms/app/BUILD.bazel#L11)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

- Changed this to maintain consistency, we mostly name our deployable jar as module_deploy.jar
- We have hardcoded this <module_deploy.jar> at few places as ik.
Example: this script is called while building artifacts from pr pipeline: https://github.com/harness/harness-core/blob/develop/scripts/bazel/bazel_script.sh and seems like it wants the deployment jar to be named as module_deploy.jar

I can name the library as module but then we need to change the name of java_binary. I'm afraid that we may need to change at other places because our jar will then look like. <new-name>_deploy.jar

</blockquote></details>

Resolving, but please make sure that checkstyle and sonar run on these correctly. You can merge it like this and then test that later on and fix it if needed. Technically you don't need java_library at all here, but the pattern we established with BuildCleaner is java_library named `module` & java_binary named ServiceName (e.g. DMS). You would build it with DMS_deploy.jar in that case and then you can rename it to whatever you wanted. TBH I don't know the reasoning behind the pattern BuildCleaner uses. Let's keep it like this for now and we can easily change later on. 
___
*[`419-delegate-service-app/src/test/java/io/harness/delegate/service/BUILD.bazel` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/42825#-NNCpKoPEYZderNRAS5N:-NNCp1mhDbFQjUXZrdPF:be2h5k4) ([raw file](https://github.com/harness/harness-core/blob/f5044a693d601cc431d66c1e0eeba871ec5bb1df/419-delegate-service-app/src/test/java/io/harness/delegate/service/BUILD.bazel#L29)):*
> ```Starlark
>         "@maven//:org_mockito_mockito_core",
>         "@maven//:io_dropwizard_dropwizard_testing",
>         "@bazel_tools//tools/java/runfiles:runfiles",
> ```

Can you double check this dep. Doesn't seem right



_Code quote:_
```Starlark
"@bazel_tools//tools/java/runfiles:runfiles"
```


<!-- Sent from Reviewable.io -->

2023-02-03 14:30 UTC, mdmilic approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: 3. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-05 16:56 UTC, raghuAtWings approved these changes
> Reviewed 1 of 5 files at r3, 2 of 13 files at r4, 6 of 12 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42825)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-05 18:04 UTC, merged