feat: [PLG-1861]: aws marketplace feature flags listing
harness/harness-core pull request #42839
Opened 2023-01-19 19:12 UTC by mtran7

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-19 19:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=42839) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=42839) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=42839) it.</sub>

2023-01-19 22:30 UTC, mtran7 commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseExpiryHandler.java
> +  public void registerIterator(IteratorExecutionHandler iteratorExecutionHandler) {
Not needed

2023-01-19 22:30 UTC, mtran7 commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseExpiryHandler.java
> +/*
Don't need entire file

2023-01-19 22:31 UTC, mtran7 commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseInfo.java
> + * Copyright 2021 Harness Inc. All rights reserved.
Don't need this file

2023-01-19 22:31 UTC, mtran7 commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseType.java
> +/*
Don't need this file

2023-01-19 22:32 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      updateFfLicense(
this is the main function that needs to be called when user tries to create an account

2023-01-19 22:33 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +    if (Instant.now().toEpochMilli() < ffLicenseInfo.getExpiryTime()) {
Replace w/ different logic that we'll get from PLG team

2023-01-19 22:33 UTC, hitesharinga commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseExpiryHandler.java
> +@OwnedBy(FF) // mt-unsure
This we might not need. Check with FF team what happens if account expires

2023-01-19 22:33 UTC, hitesharinga commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      updateFfLicense(
check with ff team which license we have to enable.

2023-01-19 22:33 UTC, hitesharinga commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseInfo.java
> +  private long expiryTime;
We don't need.

2023-01-19 22:33 UTC, hitesharinga commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseType.java
> +    Calendar calendar = Calendar.getInstance();
don't need this

2023-01-19 22:33 UTC, hitesharinga commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +  }
dont need this

2023-01-25 21:13 UTC, mtran7 commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseExpiryHandler.java
> +      account.setCloudCostEnabled(false);
should be ff specific handling

2023-01-25 21:13 UTC, mtran7 commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseExpiryHandler.java
> +      accountService.update(account);
should be ff specific handling

2023-01-25 22:31 UTC, mtran7 commented
trigger copyrightcheck

2023-01-26 22:16 UTC, mtran7 commented on 400-rest/src/main/java/io/harness/ff/license/FfLicenseExpiryHandler.java
> +/*
Remove this file

2023-01-27 00:42 UTC, mtran7 commented
trigger messagecheck

2023-01-30 18:33 UTC, neelam-harness requested changes
let's revert any changes in the config or yaml files that were due to `clang-format` 
otherwise the pr LGTM

2023-01-30 19:22 UTC, neelam-harness approved these changes
Thanks for making the nit changes as we discussed. This makes it more clean.
LGTM.

2023-01-30 22:04 UTC, mtran7 commented
trigger checkstylecodeformat

2023-01-31 17:53 UTC, hitesharinga submitted a review, later dismissed

2023-01-31 18:07 UTC, mtran7 commented on 270-delegate-service-app/src/test/resources/test-config-delegate-service.yml
>    awsSecretKey: awsMktPlaceSecretKeyPlaceHolder
removing "awsMktPlaceFfProductCodePlaceHolder"

2023-01-31 18:10 UTC, hitesharinga approved these changes

2023-01-31 18:16 UTC, neelam-harness approved these changes

2023-01-31 21:28 UTC, hitesharinga approved these changes
> Reviewed 2 of 17 files at r1, 1 of 12 files at r15, 1 of 15 files at r17, 3 of 5 files at r20, 9 of 10 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42839)* status: 17 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-01-31 21:29 UTC, merged

2023-02-14 21:36 UTC, mtran7 commented
Needed these changes as well 
https://github.com/harness/harness-core/pull/43965/files