[feat]:[pie-7735]: Code to perform BFS and get all templates as a batch
harness/harness-core pull request #42856
Opened 2023-01-20 06:34 UTC by adivishy1

## Describe your changes
Have added code for fetching all the templates first before the applyTemplates is processed. 

Testing:
1. Nested Stage template with step template [Remote Templates]
2. Nested Pipeline template with 2 Stage templates at same level [Remote Templates]
3. Nested Pipeline template with 2 Stage templates with nested 2 Step templates at same level [Remote Templates]
4. Nested Stage template with step template [Inline Templates]

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-23 10:47 UTC, yogesh-chauhan requested changes

2023-01-23 10:47 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java
> +        if (value.isArray()) {
can we structure the code like this

if (values.isObject()) { 

}

else if (values.isArray()) { 

}

2023-01-23 12:06 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856)* status: 12 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/42856#-NMCseFEjMwNO9hUDRq1-r1-98:-NMTPEOKBfsHlX-nsVBA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/27334f66e4ef1a4d50f321b624b60aa2598b00ca/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L98)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we add a java doc to indicate what these string keys mean in both inputs and output ?
And also add other information of what errors this can throw ?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/42856#-NMCseFEjMwNO9hUDRq3-r1-26:-NMTQJZH7f7XXDCDkgqL:bma06lq) ([raw file](https://github.com/harness/harness-core/blob/27334f66e4ef1a4d50f321b624b60aa2598b00ca/840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java#L26)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are all the fields non null here ? If some of them can be null, better to annotate with `javax.annotation.Nullable` 
You can refer to: https://github.com/google/guice/wiki/UseNullable
</blockquote></details>

all the fields are non null
have added context map here and currently passing an empty context map but as part of the integration will modify this context map with the required values, passing empty map will not create NPE in this case.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 269 at r1](https://reviewable.io/reviews/harness/harness-core/42856#-NMCseFEjMwNO9hUDRq5-r1-269:-NMTR14r1nFR_GoApNK4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/27334f66e4ef1a4d50f321b624b60aa2598b00ca/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L269)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we remove templateCacheMap as input argument here and simply return it from the method ?
</blockquote></details>

done



_Code quote:_
```Java
getAllTemplatesFromYaml
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 289 at r1](https://reviewable.io/reviews/harness/harness-core/42856#-NMCseFEjMwNO9hUDRq5-r1-289:-NMTRlN21kTjP7yAuhCI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/27334f66e4ef1a4d50f321b624b60aa2598b00ca/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L289)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we structure the code like this

if (values.isObject()) { 

}

else if (values.isArray()) { 

}
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 535 at r1](https://reviewable.io/reviews/harness/harness-core/42856#-NMCseFEjMwNO9hUDRqA-r1-535:-NMTWWiN7asolhC2lrdR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/27334f66e4ef1a4d50f321b624b60aa2598b00ca/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L535)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This PR description might not be helpful to product/sales etc. Can we make it more user friendly for eg. Batching to improve loading time of pipeline and template studio etc ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-23 17:57 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/42856#-NMCseFEjMwNO9hUDRq1-r1-98:-NMUlXc09XyXDY5ash4u:b9ih2nz) ([raw file](https://github.com/harness/harness-core/blob/27334f66e4ef1a4d50f321b624b60aa2598b00ca/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L98)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@adivishy1 why does it have to be a string? We should put a java class here for key. 


<!-- Sent from Reviewable.io -->

2023-01-23 17:59 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 553 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMUlurQ5Zj3kDPPf2qJ:-NMUlurQ5Zj3kDPPf2qK:b-2qx997) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L553)):*
> ```Java
>   @Override
>   public Map<String, TemplateEntity> getBatchTemplateEntities(
>       Map<String, FetchRemoteTemplateRequest> remoteTemplatesList) {
> ```

Why is there a method that only fetches "remote" templates in templates repo impl? Shouldn't repo layer have generic methods?


<!-- Sent from Reviewable.io -->

2023-01-23 18:00 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMUmQDMDelJApiMt4Yx:-NMUmQDMDelJApiMt4Yy:b-ex9q4e) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java#L26)):*
> ```Java
> @Builder
> public class FetchRemoteTemplateRequest {
>   @NotNull GitContextRequestParams gitContextRequestParams;
> ```

Why does template beans use any other module beans here? It shouldn't be aware of any such other DTOs. It should just have all required fields, thats it. Lets discuss this tomorrow if there's any confusion.


<!-- Sent from Reviewable.io -->

2023-01-24 07:09 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXazZBCkM-qhYfbQ4C:-NMXazZBCkM-qhYfbQ4D:b-rq9lys) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L271)):*
> ```Java
>   public Map<String, TemplateEntity> getAllTemplatesFromYaml(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, YamlNode yamlNode, boolean loadFromCache) {
>     Map<String, YamlNode> templateToGet = new HashMap<>();
> ```

nit: should be templatesToGet


<!-- Sent from Reviewable.io -->

2023-01-24 07:16 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 298 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXcfm0BV10akk3Ig9h:-NMXcfm0BV10akk3Ig9i:bv66us3) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L298)):*
> ```Java
> 
>       if (!templateToGet.isEmpty()) {
>         Map<String, GetTemplateEntityRequest> getBatchRequest = prepareBatchGetTemplatesRequestForTemplates(
> ```

Lets put all these methods into a single method which handles everything


<!-- Sent from Reviewable.io -->

2023-01-24 07:18 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 332 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXczo8EEtOv924j-jM:-NMXczo8EEtOv924j-jN:b-jusmg9) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L332)):*
> ```Java
> 
>   @VisibleForTesting
>   Map<String, GetTemplateEntityRequest> prepareBatchGetTemplatesRequestForTemplates(String accountIdentifier,
> ```

Fix method name as discussed


<!-- Sent from Reviewable.io -->

2023-01-24 07:24 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 302 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXeNZ79adtSowyit33:-NMXeNZ79adtSowyit34:bblkian) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L302)):*
> ```Java
> 
>         Map<String, FetchRemoteTemplateRequest> remoteTemplatesList =
>             fetchMetadataAndGetRemoteTemplateList(getBatchRequest, templateCacheMap);
> ```

This method should completely process the request which contains inline and remote templates both and return final processed list of templates


<!-- Sent from Reviewable.io -->

2023-01-24 07:28 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXfFjO6gObf7unamLW:-NMXfFjO6gObf7unamLX:b152s5w) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L384)):*
> ```Java
>           scope.getAccountIdentifier(), scope.getOrgIdentifier(), scope.getProjectIdentifier(),
>           getFileRequest.getValue().getTemplateIdentifier(), getFileRequest.getValue().getVersion(), false);
>       TemplateEntity savedEntity = templateEntity.get();
> ```

template entity can be empty here


<!-- Sent from Reviewable.io -->

2023-01-24 07:34 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 387 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXgo2mEf4wfT-nd5pg:-NMXgo2mEf4wfT-nd5ph:b2xnydh) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L387)):*
> ```Java
> 
>       if (StoreType.REMOTE == savedEntity.getStoreType()) {
>         String branchName = templateGitXService.getWorkingBranch(savedEntity.getRepoURL());
> ```

this fetching logic should be used from a common place so that its easier to maintain in future.


<!-- Sent from Reviewable.io -->

2023-01-24 07:44 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 476 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXj-Do6BysrE43EqXg:-NMXj-Do6BysrE43EqXh:b-krjf3u) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L476)):*
> ```Java
> 
>   public Map<String, TemplateEntity> getBatchTemplate(Map<String, FetchRemoteTemplateRequest> remoteTemplatesList) {
>     return templateRepository.getBatchTemplateEntities(remoteTemplatesList);
> ```

we are not going to use repository layer for getBatchTemplates as discussed


<!-- Sent from Reviewable.io -->

2023-01-24 07:49 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 368 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXk1go17mvqvoGPQMY:-NMXk1go17mvqvoGPQMZ:b-6uz9pk) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L368)):*
> ```Java
>         yamlNodeQueue.addAll(yamlNode.fields());
>       } else {
>         throw new InvalidRequestException(
> ```

Here we should throw internal server error exception as it means git-service violated the contract and didn't return response as expected. We should log all possible details here for our internal debugging use-case.


<!-- Sent from Reviewable.io -->

2023-01-24 07:52 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXkvZD6yET8q28AFfS:-NMXkvZD6yET8q28AFfT:bi8gtr2) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java#L25)):*
> ```Java
> @Data
> @Builder
> public class FetchRemoteTemplateRequest {
> ```

this isn't a template request looking from the fields it has.


<!-- Sent from Reviewable.io -->

2023-01-24 07:53 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMUmQDMDelJApiMt4Yx:-NMXl1W985_I1Iqd2h7s:bpseuww) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why does template beans use any other module beans here? It shouldn't be aware of any such other DTOs. It should just have all required fields, thats it. Lets discuss this tomorrow if there's any confusion.
</blockquote></details>

As discussed, its not a template specific request and thus beans from other modules are fine to have in the request.


<!-- Sent from Reviewable.io -->

2023-01-24 12:00 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856)* status: 12 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/42856#-NMCseFEjMwNO9hUDRq1-r1-98:-NMYCiaZ4AsxMPdDmuix:b-npxt02) ([raw file](https://github.com/harness/harness-core/blob/27334f66e4ef1a4d50f321b624b60aa2598b00ca/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L98)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@adivishy1 why does it have to be a string? We should put a java class here for key. 
</blockquote></details>

As discussed, ignoring it at the moment
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 553 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMUlurQ5Zj3kDPPf2qJ:-NMYDErQ1Mw4lY95y6Ed:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L553)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is there a method that only fetches "remote" templates in templates repo impl? Shouldn't repo layer have generic methods?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXkvZD6yET8q28AFfS:-NMY2JiN7wdIU-kHJMzI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/beans/FetchRemoteTemplateRequest.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this isn't a template request looking from the fields it has.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXazZBCkM-qhYfbQ4C:-NMYGGQh-zJfNne7K2wE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L271)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: should be templatesToGet
</blockquote></details>

done
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 298 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXcfm0BV10akk3Ig9h:-NMY3wWgEV6yy0QcbXTG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L298)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets put all these methods into a single method which handles everything
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 302 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXeNZ79adtSowyit33:-NMY8q_BDJnAjWSg_MP9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L302)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This method should completely process the request which contains inline and remote templates both and return final processed list of templates
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 332 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXczo8EEtOv924j-jM:-NMY9LbA23Ofy0rnKEFT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L332)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Fix method name as discussed
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 368 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXk1go17mvqvoGPQMY:-NMYGmEc-0JNdA1JojkA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L368)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here we should throw internal server error exception as it means git-service violated the contract and didn't return response as expected. We should log all possible details here for our internal debugging use-case.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXfFjO6gObf7unamLW:-NMYBEIJ8Cz3cfW9Qret:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L384)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

template entity can be empty here
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 387 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXgo2mEf4wfT-nd5pg:-NMYGC5X3zkW7ETvI0Yg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L387)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this fetching logic should be used from a common place so that its easier to maintain in future.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 476 at r3](https://reviewable.io/reviews/harness/harness-core/42856#-NMXj-Do6BysrE43EqXg:-NMYCC856Ldfv35kU9nG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83a8b363c300495a1a58633da005ee7f8df8ecff/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L476)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we are not going to use repository layer for getBatchTemplates as discussed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-25 06:40 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 348 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbdxGV7s0j-cUz6ZBQ:-NMbdxGV7s0j-cUz6ZBR:b-qtmrew) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L348)):*
> ```Java
>                       .build();
>     for (Map.Entry<String, YamlNode> entry : templatesToGet.entrySet()) {
>       JsonNode yaml = entry.getValue().getCurrJsonNode();
> ```

this logic of getting templateIdentifier and version label should be modularized.


<!-- Sent from Reviewable.io -->

2023-01-25 06:47 UTC, mohitg0795 commented
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 286 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbfWDS4LdlV2-Yzx9a:-NMbfWDT33Ysar4v13k0:b35lx2v) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L286)):*
> ```Java
>     Map<String, ScmGetFileRequest> scmGetBatchFilesRequestMap = scmGetBatchFileRequest.getScmGetBatchFilesRequestMap();
> 
>     Map<String, GetFileRequest> getFileRequestMap = new HashMap<>();
> ```

rename this variable to represent clearly that its sdk request map, otherwise it becomes confusing with previous statement itself which has exactly same map


<!-- Sent from Reviewable.io -->

2023-01-25 06:49 UTC, mohitg0795 commented
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 284 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbfw1W3UzPXfWxNFP5:-NMbfw1W3UzPXfWxNFP6:b1ed0yk) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L284)):*
> ```Java
>   public ScmGetBatchFilesResponse getBatchFilesByBranch(
>       String accountIdentifier, ScmGetBatchFileRequest scmGetBatchFileRequest) {
>     Map<String, ScmGetFileRequest> scmGetBatchFilesRequestMap = scmGetBatchFileRequest.getScmGetBatchFilesRequestMap();
> ```

have some validations over this map eg: null check or empty check etc


<!-- Sent from Reviewable.io -->

2023-01-25 06:51 UTC, mohitg0795 commented
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGetBatchFilesResponse.java` line 25 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbgYLS-HQMq0MCjnO_:-NMbgYLS-HQMq0MCjnOa:b3x20s) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGetBatchFilesResponse.java#L25)):*
> ```Java
> @Builder
> public class ScmGetBatchFilesResponse {
>   Map<String, GetFileResponse> batchFilesResponse;
> ```

Here we should use a new struct dedicated for GIT SDK instead of using proto struct "GetFileResponse"


<!-- Sent from Reviewable.io -->

2023-01-25 06:54 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/dto/FetchRemoteEntityRequest.java` line 25 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbh5yhDkp2nV7keleg:-NMbh5yhDkp2nV7keleh:b-a0ax4q) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/878-ng-common-utilities/src/main/java/io/harness/gitaware/dto/FetchRemoteEntityRequest.java#L25)):*
> ```Java
> @Builder
> public class FetchRemoteEntityRequest {
>   @NotNull GitContextRequestParams gitContextRequestParams;
> ```

Lets not use gitContextRequestParams here as its too generic struct to be used everywhere.


<!-- Sent from Reviewable.io -->

2023-01-25 06:57 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 490 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbhtBF9Qw6z9sGqQQe:-NMbhtBF9Qw6z9sGqQQf:b-qab5w9) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L490)):*
> ```Java
>    * @return
>    */
>   public Map<String, TemplateEntity> getBatchTemplate(
> ```

We should change name to something that depicts that this method is only to fetch batch remote templates.


<!-- Sent from Reviewable.io -->

2023-01-25 07:06 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 417 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbk-ztBWw-HETobAOS:-NMbk-ztBWw-HETobAOT:b-zg9fl2) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L417)):*
> ```Java
>         String branchName = templateGitXService.getWorkingBranch(savedEntity.getRepoURL());
> 
>         GitContextRequestParams gitContextRequestParams =
> ```

this whole preparation of git file request can be modularized


<!-- Sent from Reviewable.io -->

2023-01-25 09:42 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856)* status: 22 file(s) to review. 1 change requests. 21. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 348 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbdxGV7s0j-cUz6ZBQ:-NMcBP5_9kc4f6fcqDM8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L348)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this logic of getting templateIdentifier and version label should be modularized.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 417 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbk-ztBWw-HETobAOS:-NMcDA9z54rhQJTs28g9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L417)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this whole preparation of git file request can be modularized
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 490 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbhtBF9Qw6z9sGqQQe:-NMcFCRjCnU61FGbXkZZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L490)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should change name to something that depicts that this method is only to fetch batch remote templates.
</blockquote></details>

Done.



_Code quote:_
```Java
getBatchTemplate
```
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 284 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbfw1W3UzPXfWxNFP5:-NMcI8L_6O2U3R91MmmC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L284)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

have some validations over this map eg: null check or empty check etc
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 286 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbfWDS4LdlV2-Yzx9a:-NMcIFtJ84fz93KnCOIo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L286)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

rename this variable to represent clearly that its sdk request map, otherwise it becomes confusing with previous statement itself which has exactly same map
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGetBatchFilesResponse.java` line 25 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbgYLS-HQMq0MCjnO_:-NMcIIjgE1ClEFS_g-xd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGetBatchFilesResponse.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here we should use a new struct dedicated for GIT SDK instead of using proto struct "GetFileResponse"
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/dto/FetchRemoteEntityRequest.java` line 25 at r8](https://reviewable.io/reviews/harness/harness-core/42856#-NMbh5yhDkp2nV7keleg:-NMcFERaDzliLyMgIKcL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7168e77256497bda0195b3836821c4a0dd8a9cc0/878-ng-common-utilities/src/main/java/io/harness/gitaware/dto/FetchRemoteEntityRequest.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets not use gitContextRequestParams here as its too generic struct to be used everywhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-25 10:43 UTC, yogesh-chauhan approved these changes
> Reviewed 6 of 12 files at r1, 1 of 5 files at r2, 1 of 3 files at r3, 5 of 15 files at r4, 1 of 1 files at r8, 12 of 15 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856)* status: 16. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-25 10:51 UTC, mohitg0795 approved these changes
> Reviewed 4 of 12 files at r1, 5 of 15 files at r4, 1 of 1 files at r8, 12 of 15 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-01-25 10:52 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-25 10:56 UTC, utkarshchoubey-harness approved these changes
> Reviewed 5 of 12 files at r1, 4 of 15 files at r4, 1 of 1 files at r8, 11 of 15 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-25 11:37 UTC, utkarshchoubey-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42856#-:-NMchtLiAcWrg09Lj1tj:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-25 11:38 UTC, merged