feat: [CI-6709]: pipeline env variables in stage
harness/harness-core pull request #43025
Opened 2023-01-24 17:42 UTC by devkimittal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-30 05:13 UTC, harshjain12 commented
Can we add unit tests meanwhile i am reviewing

2023-01-30 05:19 UTC, raghavharness requested changes

2023-01-30 05:19 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +    for (NGVariable variable : variables) {
Can you keep using stream for this ?

2023-01-30 05:19 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/beans/serializer/RunTimeInputHandler.java
> +        return defaultValue.toString();
should handle null here as well for non-mandatory cases.

2023-01-30 09:19 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +    for (NGVariable variable : variables) {
Need to put two different conditions for String and number variable here, don't think that can be done using stream here.

2023-01-30 09:21 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +    for (NGVariable variable : variables) {
You can use stream two times I think

2023-01-30 11:45 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +    secretVarMap.putAll(getSecretVariablesMap(stageNode.getPipelineVariables()));
what if the both pipeline variable and stage variables are created with same name abc? stage one should override the pipeline one irrespectice of whether it is a account secret or a project secret, right?

2023-02-02 13:20 UTC, raghavharness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 9 files at r1, 1 of 6 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43025#-:-NNHH9zO8vRhwbkKkyhw:bnfp4nl)* status: 1. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-02-02 13:56 UTC, raghavharness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43025#-:-NNHPX2I7JhpIQd1YVe2:bnfp4nl)* status: 1. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-02-02 13:57 UTC, raghavharness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43025)* status: 1. unresolved discussions. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-02-03 05:58 UTC, merged