[feat]: [CDS-497934]: google cloud storage artifact delegate changes
harness/harness-core pull request #43068
Opened 2023-01-25 11:44 UTC by PragyeshMishra01

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-25 11:57 UTC, sainath-b requested changes

2023-01-25 11:57 UTC, sainath-b commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/GcpTask.java
> +      case LIST_PROJECTS:
This will make delegate changes backwards incompatible. Lets merge this PR. But we need to create another gcp task handler immediately after merging this PR. Before next branch cut.
@PragyeshMishra01

2023-01-25 12:36 UTC, PragyeshMishra01 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/gcp/GcpTask.java
> +      case LIST_PROJECTS:
As discussed, I will create a separate handler for this new task in separate pr.

2023-01-26 20:55 UTC, mdmilic approved these changes
Approving delegate owned file changes

> Reviewed 4 of 24 files at r1, 2 of 11 files at r2, 1 of 1 files at r3, 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43068#-:-NMjr7nOESUGwJhSTj-S:b-sjeihy)* status: 38 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-27 03:27 UTC, sainath-b approved these changes

2023-01-27 03:28 UTC, sainath-b approved these changes
> Reviewed 22 of 24 files at r1, 10 of 11 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43068)* status: 29 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-01-27 05:21 UTC, PragyeshMishra01 commented
trigger messagecheck

2023-01-27 06:39 UTC, sainath-b approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43068)* status: 30 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-27 06:39 UTC, sainath-b approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43068#-:-NMlx1rfC8d0XPebRFsA:bnfp4nl)* status: 30 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-27 07:22 UTC, merged