feat: [PLG-1881]: Add CD license for admin account for local dev before ng start
harness/harness-core pull request #43084
Opened 2023-01-25 15:59 UTC by Xin-Harness

…manager start

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-26 16:45 UTC, pranil-harness submitted a review, later dismissed

2023-01-30 14:57 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084#-:-NN2AbfhAmNSZz9RVM19:bnfp4nl)* status: Some of the checks are too old. 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-02-06 21:14 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/43084#-NNc_3Ku3o-Z5JO9rbcu:-NNc_3Ku3o-Z5JO9rbcv:b-s08pxl) ([raw file](https://github.com/harness/harness-core/blob/22bf90e305a2c27436cfe9e2a5a783434b72f471/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java#L35)):*
> ```Java
>     cdModuleLicense.setStartTime(System.currentTimeMillis());
>     cdModuleLicense.setExpiryTime(Long.MAX_VALUE);
>     cdModuleLicense.setWorkloads(5);
> ```

why serviceInstances is not required?


<!-- Sent from Reviewable.io -->

2023-02-06 21:41 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/43084#-NNc_3Ku3o-Z5JO9rbcu:-NNcf3m88O_Nm2CcKhQI:bklnpgw) ([raw file](https://github.com/harness/harness-core/blob/22bf90e305a2c27436cfe9e2a5a783434b72f471/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java#L35)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why serviceInstances is not required?
</blockquote></details>

The value I defined is from CDModuleLicenseClient which contains the content what free plan should have. Why you think Service Instance should be added here?


<!-- Sent from Reviewable.io -->

2023-02-06 22:19 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084#-:-NNcnxn4-clpiO0nWGz4:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-06 23:44 UTC, neelam-harness requested changes

2023-02-06 23:44 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java
> +    cdModuleLicense.setWorkloads(5);
nit: can we create a constant instead of hardcoding workloads ?

2023-02-06 23:44 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java
> +  private String ADMIN_ACCOUNT_IDENTIFIER = "kmpySmUISimoRrJL6NL73w";
let's make this a `final` variable ?

2023-02-07 01:02 UTC, neelam-harness reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/43084#-NNc_3Ku3o-Z5JO9rbcu:-NNdNyeD5tC0s-IiHow_:b-3xa2d1) ([raw file](https://github.com/harness/harness-core/blob/22bf90e305a2c27436cfe9e2a5a783434b72f471/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java#L35)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

The value I defined is from CDModuleLicenseClient which contains the content what free plan should have. Why you think Service Instance should be added here?
</blockquote></details>

I see that the field is not optional, that makes me think the field is mandatory. Please correct me if I am wrong. 


<!-- Sent from Reviewable.io -->

2023-02-07 07:00 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 2 change requests. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/43084#-NNc_3Ku3o-Z5JO9rbcu:-NNeesUMBxTuo1Mdg4XZ:bss20kh) ([raw file](https://github.com/harness/harness-core/blob/22bf90e305a2c27436cfe9e2a5a783434b72f471/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java#L35)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

I see that the field is not optional, that makes me think the field is mandatory. Please correct me if I am wrong. 
</blockquote></details>

@Xin-Harness I saw serviceInstances inside CDModuleLicense entity object but I am not sure whether it is required or not, I just pointed out if in case it is a miss.


<!-- Sent from Reviewable.io -->

2023-02-07 07:00 UTC, kapil-harness approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-07 16:47 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/43084#-NNcXwWXd3OXzD7MQ6TR-r3-23:-NNgldOd5lM37lbp5sTW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bf90e305a2c27436cfe9e2a5a783434b72f471/930-ng-license-manager/src/main/java/io/harness/licensing/migrations/licenses/LocalDevAdminAccountCDLicenseMigration.java#L23)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

let's make this a `final` variable ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-07 18:48 UTC, neelam-harness approved these changes

2023-02-07 18:48 UTC, kapil-harness approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 1 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-07 18:49 UTC, neelam-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084#-:-NNhCRUT4tsUdlX5Jzd5:bnfp4nl)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-02-07 18:49 UTC, kapil-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-02-07 18:51 UTC, Xin-Harness reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-02-07 19:30 UTC, pranil-harness approved these changes

2023-02-07 19:30 UTC, pranil-harness reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43084)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-07 19:31 UTC, merged