feat: [CDS-47337]: Create CSV report for Active services
harness/harness-core pull request #43154
Opened 2023-01-27 14:18 UTC by ivan-83

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-01-30 11:07 UTC, vladimir-peric submitted a review, later dismissed
> Reviewed 3 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-30 22:52 UTC, praveensugavanam approved these changes
> Reviewed 3 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-30 23:28 UTC, neelam-harness requested changes

2023-01-30 23:28 UTC, neelam-harness commented on 945-license-usage-sdk/src/main/java/io/harness/licensing/usage/interfaces/LicenseUsageInterface.java
> +  File getLicenseUsageCSVReport(String accountIdentifier, ModuleType module, long currentTsInMs);
nit: rename `module` -> `moduleType`

2023-01-30 23:28 UTC, neelam-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/usage/mapper/ActiveServiceMapper.java
> +  public static ActiveServiceFetchData buildActiveServiceFetchData(
We have same method above, wondering if we can re-use it by passing down the optionals instead ? If we don't need certain attributes we can just pass down Optional.empty().

2023-01-31 11:50 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/mapper/ActiveServiceMapper.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/43154#-NMna6eTAPoWs2nbrC8w-r2-66:-NN6_3AX3UnNyb7j7cHb:b-e8fmge) ([raw file](https://github.com/harness/harness-core/blob/f187a9702aa7353d61a6a5322f7dcc1a5f0d7a40/125-cd-nextgen/src/main/java/io/harness/cdng/usage/mapper/ActiveServiceMapper.java#L66)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

We have same method above, wondering if we can re-use it by passing down the optionals instead ? If we don't need certain attributes we can just pass down Optional.empty().
</blockquote></details>

We avoid passing Optional as a method param because the number of checks increases, beside check whether the value is present or not we need to check whether the passed optional arg itself is null. 
___
*[`945-license-usage-sdk/src/main/java/io/harness/licensing/usage/interfaces/LicenseUsageInterface.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/43154#-NMna6eTAPoWs2nbrC8x-r2-42:-NN6_--I7NwHh7xwJqbG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f187a9702aa7353d61a6a5322f7dcc1a5f0d7a40/945-license-usage-sdk/src/main/java/io/harness/licensing/usage/interfaces/LicenseUsageInterface.java#L42)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

nit: rename `module` -> `moduleType`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-31 12:09 UTC, vladimir-peric approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-01-31 16:34 UTC, deepak-harness approved these changes
> Reviewed 2 of 6 files at r1, 2 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-31 19:18 UTC, praveensugavanam approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-31 19:56 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/mapper/ActiveServiceMapper.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/43154#-NMna6eTAPoWs2nbrC8w-r2-66:-NN8IRr61YEua1YPq9Bc:b-f4pg81) ([raw file](https://github.com/harness/harness-core/blob/f187a9702aa7353d61a6a5322f7dcc1a5f0d7a40/125-cd-nextgen/src/main/java/io/harness/cdng/usage/mapper/ActiveServiceMapper.java#L66)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We avoid passing Optional as a method param because the number of checks increases, beside check whether the value is present or not we need to check whether the passed optional arg itself is null. 
</blockquote></details>

Makes sense. The only issue I see with this model is that we will keep adding more and more methods to build customized ActiveServiceFetchData each time but I'll let you decide on this :)


<!-- Sent from Reviewable.io -->

2023-01-31 19:59 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/mapper/ActiveServiceMapper.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/43154#-NMna6eTAPoWs2nbrC8w-r2-66:-NN8PO8O8GpQ3_AjaOA6:bb77ufg) ([raw file](https://github.com/harness/harness-core/blob/f187a9702aa7353d61a6a5322f7dcc1a5f0d7a40/125-cd-nextgen/src/main/java/io/harness/cdng/usage/mapper/ActiveServiceMapper.java#L66)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Makes sense. The only issue I see with this model is that we will keep adding more and more methods to build customized ActiveServiceFetchData each time but I'll let you decide on this :)
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2023-01-31 20:02 UTC, neelam-harness reviewed
> Reviewed 2 of 6 files at r1, 2 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-01-31 20:02 UTC, neelam-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43154)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-01-31 20:02 UTC, merged