feat: [DEL-5831]: provide support for migrating delegate tasks to new db
harness/harness-core pull request #43185
Opened 2023-01-30 06:02 UTC by arpit3107

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-01 06:01 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 21 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAW7B8BTsE3RUVFhjH:-NNAW7B8BTsE3RUVFhjI:b-n8krzy) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L89)):*
> ```Java
> 
>     try {
>       rebroadcastUnassignedTasks(false);
> ```

we should also stop running this once all the task moved to new db.



_Code quote:_
```Java
rebroadcastUnassignedTasks(false);
```
___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1179 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAWXNHEPoXwJRDhE6N:-NNAWXNHEPoXwJRDhE6O:b5dm0m3) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1179)):*
> ```Java
>           persistence
>               .createUpdateOperations(DelegateTask.class,
>                   delegateTaskMigrationHelper.isMigrationEnabledForTask(retryDelegate.getDelegateTask().getUuid()))
> ```

avoid calling this function again and again, store the value in new boolean variable above and use it here and below.
Ditto elsewhere



_Code quote:_
```Java
 delegateTaskMigrationHelper.isMigrationEnabledForTask(retryDelegate.getDelegateTask().getUuid()
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1077 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXHHKEL90q7rl3vgZ:-NNAXHHKEL90q7rl3vg_:bk5rzn6) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1077)):*
> ```Java
>           persistence
>               .createUpdateOperations(
>                   DelegateTask.class, delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid()))
> ```

create one boolean variable and use that here and below.



_Code quote:_
```Java
delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid()
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1149 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXNRK0gXBtJRRisuN:-NNAXNRK0gXBtJRRisuO:b-lr0xth) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1149)):*
> ```Java
>         persistence
>             .createUpdateOperations(
>                 DelegateTask.class, delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid()))
> ```

ditto here



_Code quote:_
```Java
delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid()
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1175 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXRCDDnA7pV8oD8Xd:-NNAXRCDDnA7pV8oD8Xe:bpgwxg1) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1175)):*
> ```Java
>         persistence
>             .createUpdateOperations(
>                 DelegateTask.class, delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid()))
> ```

here as well



_Code quote:_
```Java
delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid())
```
___
*[`400-rest/src/test/java/software/wings/app/DelegateQueueTaskTest.java` line 461 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXfM70GsU_2WR6KcB:-NNAXfM70GsU_2WR6KcC:bwj9ybt) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/test/java/software/wings/app/DelegateQueueTaskTest.java#L461)):*
> ```Java
>     taskAfterBroadcast6.setNextBroadcast(System.currentTimeMillis());
>     persistence.save(taskAfterBroadcast6);
>     delegateQueueTask.rebroadcastUnassignedTasks(false);
> ```

we should also have UT for the case when we pass true
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAVN5z3ylUf7MvM16v:-NNAVN5z3ylUf7MvM16w:b-4mudpn) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java#L26)):*
> ```Java
> @Singleton
> @Slf4j
> public class DelegateTaskMigrationHelper {
> ```

This class has nothing to do specifically with migration, rename it to DelegateTaskUUIDHelper



_Code quote:_
```Java
DelegateTaskMigrationHelper
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAY0UV47bZ9bqRPxQ0:-NNAY0UV47bZ9bqRPxQ1:b-kfsxv1) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java#L34)):*
> ```Java
> 
>   private final Cache<String, AtomicBoolean> delegateTaskMigrationFlagCache =
>           Caffeine.newBuilder().maximumSize(5).expireAfterWrite(10, TimeUnit.SECONDS).build();
> ```

why not use the same cache which you introduced at persistence layer ?



_Code quote:_
```Java
  private final Cache<String, AtomicBoolean> delegateTaskMigrationFlagCache =
          Caffeine.newBuilder().maximumSize(5).expireAfterWrite(10, TimeUnit.SECONDS).build();
```
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 279 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAYVWW1ND_NtOOWzI-:-NNAYVWW1ND_NtOOWzI0:bhyodc6) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L279)):*
> ```Java
> 
>   @Override
>   public <T extends PersistentEntity> Query<T> createQuery(Class<T> cls, boolean isMigrationEnabled) {
> ```

rename this to useSecondaryStoreIfExist



_Code quote:_
```Java
isMigrationEnabled
```
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 605 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAZ1aU9cYUHxhnsFMv:-NNAZ1aU9cYUHxhnsFMw:br6i0rt) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L605)):*
> ```Java
>     onUpdate(updateQuery, updateOperations, currentTimeMillis());
>     AdvancedDatastore datastore = getDatastore(updateQuery.getEntityClass());
>     return HPersistence.retry(() -> datastore.update(updateQuery, updateOperations));
> ```

you can get rid of this code and call the overload method by passing false.



_Code quote:_
```Java
    onUpdate(updateQuery, updateOperations, currentTimeMillis());
    AdvancedDatastore datastore = getDatastore(updateQuery.getEntityClass());
    return HPersistence.retry(() -> datastore.update(updateQuery, updateOperations));
```


<!-- Sent from Reviewable.io -->

2023-02-02 07:47 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 63 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAW7B8BTsE3RUVFhjH:-NNG4Tv99SFQHUn5YtJ7:b-iep4g4) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L89)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we should also stop running this once all the task moved to new db.
</blockquote></details>

For that we have to make this configurable, or put something in DB and that would become too heavy to modify. Keeping rollback in mind.
So kept it like this as it will make queries and will do nothing. 
___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1179 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAWXNHEPoXwJRDhE6N:-NNG3Tk94fYL80VsKL85:b-cdltcz) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1179)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

avoid calling this function again and again, store the value in new boolean variable above and use it here and below.
Ditto elsewhere
</blockquote></details>

Done. You reviewed this pr too early :) 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1077 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXHHKEL90q7rl3vgZ:-NNG3Z2e8OKEhu_arO5r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1077)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

create one boolean variable and use that here and below.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1149 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXNRK0gXBtJRRisuN:-NNG3Zyc3BpksFxXh6zW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1149)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

ditto here
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1175 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXRCDDnA7pV8oD8Xd:-NNG3bB53Drgf2jDVk9W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1175)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

here as well
</blockquote></details>

Done.
___
*[`400-rest/src/test/java/software/wings/app/DelegateQueueTaskTest.java` line 461 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAXfM70GsU_2WR6KcB:-NNG3dUXCRJQM6a4gUZV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/test/java/software/wings/app/DelegateQueueTaskTest.java#L461)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we should also have UT for the case when we pass true
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAVN5z3ylUf7MvM16v:-NNG3gBgDB-XFcuUUYhY:b-qipfvs) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java#L26)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This class has nothing to do specifically with migration, rename it to DelegateTaskUUIDHelper
</blockquote></details>

No, once migration is done we will not use this class anymore
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAY0UV47bZ9bqRPxQ0:-NNG3urE48i4d2GaNF6d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java#L34)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why not use the same cache which you introduced at persistence layer ?
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 279 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAYVWW1ND_NtOOWzI-:-NNG42DQ5nynktijcyZl:bt5f1mb) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L279)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

rename this to useSecondaryStoreIfExist
</blockquote></details>

This functionality is not for everyone. Only we are using it and we will cleanup all these code once migration is done
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 605 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAZ1aU9cYUHxhnsFMv:-NNG4Er10PlnUSYeT4lW:bgaos9j) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L605)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

you can get rid of this code and call the overload method by passing false.
</blockquote></details>

I wanted to touch methods as minimum as possible for our migration, so that cleanup will be easy


<!-- Sent from Reviewable.io -->

2023-02-03 08:13 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 63 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`270-verification/verification-config.yml` line 76 at r6](https://reviewable.io/reviews/harness/harness-core/43185#-NNLElGm7Vi-N1pTlrOi:-NNLElGn0h6xmJ8fGxoN:b-c3biit) ([raw file](https://github.com/harness/harness-core/blob/e8e15a7c46031db0d88b6c20279eab9c6dd32565/270-verification/verification-config.yml#L76)):*
> ```YAML
> 
> dms-mongo:
>   uri: mongodb://localhost:27017/harness
> ```

this is already changed as part of your previous pr
___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorV2.java` line 27 at r6](https://reviewable.io/reviews/harness/harness-core/43185#-NNLJIvvENj_Xl94wIJv:-NNLJIvvENj_Xl94wIJw:b2e7rzu) ([raw file](https://github.com/harness/harness-core/blob/e8e15a7c46031db0d88b6c20279eab9c6dd32565/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorV2.java#L27)):*
> ```Java
> @Singleton
> // TODO: ARPIT remove this iterator once delegate task migration has been done
> public class FailDelegateTaskIteratorV2
> ```

let's not call it v2, just say FailDelegateTaskIteratorOnDMS
___
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/43185#-NNAW7B8BTsE3RUVFhjH:-NNLJaON3qsmlt-LyXpZ:b-x8doso) ([raw file](https://github.com/harness/harness-core/blob/484e3b0cab5ba0f6ac3dcc0500bc146135343091/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L89)):*
>  
Ack


<!-- Sent from Reviewable.io -->

2023-02-06 07:25 UTC, gaurav-jain1 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 63 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`360-cg-manager/config.yml` line 322 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_Y7ij59lu3gnc8SFF:-NN_Y7ikCBu7oZdL1lyD:b-pjoqqt) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/360-cg-manager/config.yml#L322)):*
> ```YAML
> 
> dms-mongo:
>   uri: mongodb://localhost:27017/dms-harness
> ```

for local and pr env, you can create a new db for dms collections. Just say dms (no need to append harness)



_Code quote:_
```YAML
dms-harness
```
___
*[`360-cg-manager/iterator_config.json` line 350 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_YQKN3uYBsKjWrzdU:-NN_YQKN3uYBsKjWrzdV:b-zh6nhb) ([raw file](https://github.com/harness/harness-core/blob/1cfab822c6a89260bf7d42d5b54818463d2fc8ce/360-cg-manager/iterator_config.json#L350)):*
> ```JSON
>     "targetIntervalInSeconds": 30,
>     "throttleIntervalInSeconds": 0,
>     "iteratorMode": "REDIS_BATCH"
> ```

I think @Raghav-Murali was changing the mode how iterator runs. Just check with him about this change.



_Code quote:_
```JSON
REDIS_BATC
```
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 101 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN__RqK033GDv3IF4Pb:-NN__RqK033GDv3IF4Pc:bpvm6cm) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L101)):*
> ```Java
>     //    Query<DelegateTask> delegateTaskQuery = persistence.createQuery(DelegateTask.class)
>     //                                                .filter(DelegateTaskKeys.accountId, accountId)
>     //                                                .field(DelegateTaskKeys.uuid)
> ```

Remove commented code



_Code quote:_
```Java
    // TODO: ARPIT uncomment below lines and fallback to using HIterator for this operation after delegate task
    // migration has been done
    //    Query<DelegateTask> delegateTaskQuery = persistence.createQuery(DelegateTask.class)
    //                                                .filter(DelegateTaskKeys.accountId, accountId)
    //                                                .field(DelegateTaskKeys.uuid)
    //                                                .in(delegateTaskIds)
    //                                                .filter(DelegateTaskKeys.delegateId, delegateId)
    //                                                .filter(DelegateTaskKeys.status, DelegateTask.Status.STARTED)
    //                                                .project(DelegateTaskKeys.uuid, true)
    //                                                .project(DelegateTaskKeys.data_timeout, true);
    //
    //    // TODO: it seems like mongo 4.2 supports update based on another field. Change this when we fully migrate to
    //    it. long now = currentTimeMillis(); try (HIterator<DelegateTask> iterator = new
    //    HIterator<>(delegateTaskQuery.fetch())) {
    //      for (DelegateTask delegateTask : iterator) {
    //        persistence.update(delegateTask,
    //            persistence.createUpdateOperations(DelegateTask.class)
    //                .set(DelegateTaskKeys.expiry, now + delegateTask.getData().getTimeout()));
    //      }
    //    }
```
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 119 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN__Ey3A2_ze9m05JoA:-NN__Ey3A2_ze9m05JoB:bn2gwsa) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L119)):*
> ```Java
>   }
> 
>   private void touchExecutingTasksUsingForLoop(String accountId, String delegateId, List<String> delegateTaskIds) {
> ```

Just say  touchExecutingDelegateTasks



_Code quote:_
```Java
ForLoop
```
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 91 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_a1c06zeuqtKGK1fi:-NN_a1c06zeuqtKGK1fj:b-1gnmgr) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L91)):*
> ```Java
>   private final LoadingCache<String, Boolean> delegateMigrationFlagCache =
>       CacheBuilder.newBuilder()
>           .maximumSize(100)
> ```

why is this 100 ? Do we expect more class names ?



_Code quote:_
```Java
100
```
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/provider/PersistenceProvider.java` line 20 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_b5Db5at0AzmhN5Z5:-NN_b5Dc5dIiHgib-yOC:be9hoxg) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/960-persistence/src/main/java/io/harness/mongo/iterator/provider/PersistenceProvider.java#L20)):*
> ```Java
> import java.util.List;
> 
> public interface PersistenceProvider<T extends PersistentIterable, F extends FilterExpander> {
> ```

Can we convert this to a abstract class and create 2 more overload methods for obtainNextInstance and findInstance which accept new boolean variable ? Than it's easy to clear code later.


<!-- Sent from Reviewable.io -->

2023-02-06 10:48 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 63 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`360-cg-manager/config.yml` line 322 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_Y7ij59lu3gnc8SFF:-NNaF8h21ucg7McOWoOQ:b-e81q8m) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/360-cg-manager/config.yml#L322)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

for local and pr env, you can create a new db for dms collections. Just say dms (no need to append harness)
</blockquote></details>

Let it be dms-harness. There is another pms-harness also. 
___
*[`360-cg-manager/iterator_config.json` line 350 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_YQKN3uYBsKjWrzdU:-NNaFNRJDjVvhSKVbIcx:bcf8hly) ([raw file](https://github.com/harness/harness-core/blob/1cfab822c6a89260bf7d42d5b54818463d2fc8ce/360-cg-manager/iterator_config.json#L350)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I think @Raghav-Murali was changing the mode how iterator runs. Just check with him about this change.
</blockquote></details>

Yes having a discussion with him, anyway old iterator will be running on old DB with both REDIS mode and PUMP mode. But new iterator will be running on new DB only through PUMP mode as this is temporary
___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorV2.java` line 27 at r6](https://reviewable.io/reviews/harness/harness-core/43185#-NNLJIvvENj_Xl94wIJv:-NNaFchK-0S14e_jqBsO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e8e15a7c46031db0d88b6c20279eab9c6dd32565/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorV2.java#L27)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

let's not call it v2, just say FailDelegateTaskIteratorOnDMS
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 101 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN__RqK033GDv3IF4Pb:-NNaGe2O6LGK2MJDZ8QH:b-4cg178) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L101)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Wanted to keep it like this for making clean up easier once migration is done
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 119 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN__Ey3A2_ze9m05JoA:-NNaGmmG7eXz6SwSi0Je:b-sov8n4) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L119)):*
> Wanted to keep it like this for making clean up easier once migration is done
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 91 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_a1c06zeuqtKGK1fi:-NNaGqIU92WPq3COXfs6:b-kzr9eb) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L91)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why is this 100 ? Do we expect more class names ?
</blockquote></details>

Not expecting. But just to be on safe side
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/provider/PersistenceProvider.java` line 20 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN_b5Db5at0AzmhN5Z5:-NNaHV3cBiOnh7Jox4jA:bqauy0c) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/960-persistence/src/main/java/io/harness/mongo/iterator/provider/PersistenceProvider.java#L20)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Can we convert this to a abstract class and create 2 more overload methods for obtainNextInstance and findInstance which accept new boolean variable ? Than it's easy to clear code later.
</blockquote></details>

internally there are some more private methods, hence wanted to avoid changing lot of codes.


<!-- Sent from Reviewable.io -->

2023-02-06 16:37 UTC, mdmilic requested changes
> Reviewed 1 of 3 files at r3, 18 of 32 files at r5, 1 of 2 files at r6, 31 of 34 files at r7, 1 of 2 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 2 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 92 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNb5rSbBV2ZOkHYgUmT:-NNb5rSbBV2ZOkHYgUmU:b-9ac7oa) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L92)):*
> ```Java
> 
>       if (delegateTaskMigrationHelper.isDelegateTaskMigrationEnabled()
>           || delegateTaskMigrationHelper.isDelegateTaskMigrationRollingBack()) {
> ```

Should this be if/else or we always want to rebroadcast(false)?



_Code quote:_
```Java
      rebroadcastUnassignedTasks(false);

      if (delegateTaskMigrationHelper.isDelegateTaskMigrationEnabled()
          || delegateTaskMigrationHelper.isDelegateTaskMigrationRollingBack()) {
        rebroadcastUnassignedTasks(true);
      }
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1826 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNb7QjCCwam_eU1ms4j:-NNb7QjCCwam_eU1ms4k:bv9c46q) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1826)):*
> ```Java
>   private List<DelegateTaskEvent> getQueuedEvents(String accountId, String delegateId, boolean sync) {
>     // TODO - add assignment filter here (scopes. selectors, ...)
>     // ARPIT: Run at 2 places
> ```

Does this mean that you need to query a second DB as well, or will that happen automatically if you don't provide isMigrationEnabled? Why do we want to query both DBs for these events. 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1888 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNb6mbw-NDa4rTadh8L:-NNb6mbw-NDa4rTadh8M:bhru89s) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1888)):*
> ```Java
>   public void deleteByAccountId(String accountId) {
>     // ARPIT: run at 2 places
>     log.info("Account {} deleted. Deleting all delegate tasks owned by account.", accountId);
> ```

This used to delete delegates, not tasks. Is this change valid?
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 280 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNbRpI_8sz_blYktCq8:-NNbRpI_8sz_blYktCq9:b-tqpowy) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L280)):*
> ```Java
>                      .count();
> 
>     if (delegateTaskMigrationHelper.isDelegateTaskMigrationEnabled()
> ```

if/else or we read from old DB always intentionally?


<!-- Sent from Reviewable.io -->

2023-02-07 13:34 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 7 file(s) to review. 2 change requests. 19. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 92 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNb5rSbBV2ZOkHYgUmT:-NNg39KVAvh8UIaQTX89:bnvt5vl) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L92)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Should this be if/else or we always want to rebroadcast(false)?
</blockquote></details>

For sometime we want to rebroadcast from both DBs, as tasks will be in both DBs. But then we want to run only on new DB, but controlling this thread dynamically is too hectic process. Hence left it to always run on Old DB also till new code goes in.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1826 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNb7QjCCwam_eU1ms4j:-NNg3cSi0Ianid2E5e67:b-xq1k2p) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1826)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Does this mean that you need to query a second DB as well, or will that happen automatically if you don't provide isMigrationEnabled? Why do we want to query both DBs for these events. 
</blockquote></details>

This method is used to get the QueuedEvents for polling mode delegates. As this query is not having UUID field present, so we have to run on both DBs and get the collective list of delegateTasks.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1888 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNb6mbw-NDa4rTadh8L:-NNg3r7qB5cv5nMM3JXd:b-ir9tz6) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1888)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This used to delete delegates, not tasks. Is this change valid?
</blockquote></details>

This is used to delete all entities when an account is deleted. This includes delegates, tokens, tasks, profiles etc..
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 280 at r9](https://reviewable.io/reviews/harness/harness-core/43185#-NNbRpI_8sz_blYktCq8:-NNg4DyA0dos9tZzHDhb:b-pui326) ([raw file](https://github.com/harness/harness-core/blob/5aba0f174a27a7e70c10653bd7809e82594caff7/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L280)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

if/else or we read from old DB always intentionally?
</blockquote></details>

If the migration is enabled then also there will be some tasks living in old DB (created before enabling flag). So we have to query both


<!-- Sent from Reviewable.io -->

2023-02-07 18:14 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 119 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN__Ey3A2_ze9m05JoA:-NNh4Imw9qU_yTezUW34:b-8jdfii) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L119)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

> Wanted to keep it like this for making clean up easier once migration is done
</blockquote></details>

Do we still need this method touchExecutingDelegateTasks?


<!-- Sent from Reviewable.io -->

2023-02-07 18:16 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 249 at r10](https://reviewable.io/reviews/harness/harness-core/43185#-NNh4xr74_nrmB6Rf18p:-NNh4xr74_nrmB6Rf18q:bswbzvo) ([raw file](https://github.com/harness/harness-core/blob/11869decbe0944fbecaec88c988cb5c3dfe5e7b3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L249)):*
> ```Java
>     if (taskQuery != null) {
>       persistence.deleteOnServer(
>           taskQuery, delegateTaskMigrationHelper.isMigrationEnabledForTask(delegateTask.getUuid()));
> ```

is this cached, delegateTaskMigrationHelper.isMigrationEnabledForTask?  We are making this call very often


<!-- Sent from Reviewable.io -->

2023-02-07 18:23 UTC, jennyjames21 commented
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 95 at r10](https://reviewable.io/reviews/harness/harness-core/43185#-NNh5i1p4M09KYh_yW5h:-NNh5i1p4M09KYh_yW5i:bvttdka) ([raw file](https://github.com/harness/harness-core/blob/11869decbe0944fbecaec88c988cb5c3dfe5e7b3/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L95)):*
> ```Java
>     return getDatastore(getPrimaryStore(entity.getClass()));
>   }
> ```

We are adding delegate migration specific code to core DB persistence framework, should we check with code owners or wider audience for approval?
 


<!-- Sent from Reviewable.io -->

2023-02-07 18:28 UTC, jennyjames21 reviewed
> Reviewed 12 of 51 files at r4, 15 of 32 files at r5, 5 of 11 files at r9, 2 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 5 file(s) to review. 2 change requests. 19. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-08 07:47 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 5 file(s) to review. 2 change requests. 21. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 119 at r8](https://reviewable.io/reviews/harness/harness-core/43185#-NN__Ey3A2_ze9m05JoA:-NNjtnNU1xAgPtgTwVva:bkyrlor) ([raw file](https://github.com/harness/harness-core/blob/ccc07aeab1132dd6436dca2f46a16ca6568639e3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L119)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Do we still need this method touchExecutingDelegateTasks?
</blockquote></details>

Yes, delegate still send this list in heartbeat. https://github.com/harness/harness-core/blob/develop/260-delegate/src/main/java/io/harness/delegate/service/common/AbstractDelegateAgentService.java#:~:text=.currentlyExecutingDelegateTasks(getCurrentlyExecutingTaskIds())
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 249 at r10](https://reviewable.io/reviews/harness/harness-core/43185#-NNh4xr74_nrmB6Rf18p:-NNjvz_b1MmMhfWswmrS:be5euvb) ([raw file](https://github.com/harness/harness-core/blob/11869decbe0944fbecaec88c988cb5c3dfe5e7b3/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L249)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

is this cached, delegateTaskMigrationHelper.isMigrationEnabledForTask?  We are making this call very often
</blockquote></details>

No, I have reduced the redundant use of this isMigrationEnabledForTask(taskId).
But still we will be using it too often. What is the better way? Using caching for taskId is better than calculating it at the moment.

public boolean isMigrationEnabledForTask(String taskUUID) {
    String taskUUIDState = StringUtils.right(taskUUID, 4);
    return NEW_DELEGATE_TASK_UUID_STATE.equals(taskUUIDState);
  }
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 95 at r10](https://reviewable.io/reviews/harness/harness-core/43185#-NNh5i1p4M09KYh_yW5h:-NNjzFOODr2RKkZz2T-D:b-yqz944) ([raw file](https://github.com/harness/harness-core/blob/11869decbe0944fbecaec88c988cb5c3dfe5e7b3/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L95)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

We are adding delegate migration specific code to core DB persistence framework, should we check with code owners or wider audience for approval?
 
</blockquote></details>

We have already done that as part of static collections PR :) . But didnt asked wider audience as such. We will revert these changes after migration is done


<!-- Sent from Reviewable.io -->

2023-02-08 12:21 UTC, mdmilic approved these changes
> Reviewed 7 of 7 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 1 change requests. 17. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1846 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNkrVo47OdrYeWj1aJP:-NNkrVo47OdrYeWj1aJQ:bdq0id4) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1846)):*
> ```Java
> 
>       if (isEmpty(delegateTasks)) {
>         delegateTasks = delegateTasksFromDMS;
> ```

This is not a blocking comment since it's temp code, but if you do need to make some other changes you can update it. Collectors can only ever return empty list, never null. That means you don't really need this logic, you could just do 



_Suggestion:_
```Java
      delegateTasks.addAll(delegateTasksFromDMS);
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1863 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNks1JpBmM172n876OY:-NNks1JpBmM172n876OZ:b-wcnlzb) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1863)):*
> ```Java
>   }
> 
>   private List<DelegateTask> getQueuedDelegateTasksFromDMS(String accountId, String delegateId, boolean sync) {
> ```

This is not a blocking comment since it's temp code, but if you do need to make some other changes you can update it. This entire method is duplicated with only difference of boolean flag. Same goes for abort and delete cases. You could instead do something like snippet 1 (afaik new createQuery with migration false is just like old createQuery with no params) or if you think that would degrade performance something like snippet 2. Btw always do final :) 



_Code snippet (i):_
```Java
List<DelegateTask> tasks = getQueuedTasks(accountId, delegateId, sync, false).addAll(getQueuedTasks(accountId, delegateId, sync, true));
```



_Code snippet (ii):_
```Java
private Query<DelegateTask> createTasksQuery(final boolean isMigrationEnabled) {
    return isMigrationEnabled ? persistence.createQuery(DelegateTask.class, true) : persistence.createQuery(DelegateTask.class);
}

private List<DelegateTask> getQueuedDelegateTasksFromDMS(String accountId, String delegateId, boolean sync, final boolean isMigrationEnabled) {
    return createTasksQuery(isMigrationEnabled).filter()...
}
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java` line 33 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNkwGrOEVDagVgyrHaR:-NNkwGrOEVDagVgyrHaS:b-y1r3h4) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java#L33)):*
> ```Java
>       CacheBuilder.newBuilder()
>           .maximumSize(10)
>           .expireAfterWrite(5, TimeUnit.MINUTES)
> ```

5min might be too much. We use 10s on mongo persistence. Also, since this cache already exists in persistence why do you need it here again. Why can't we just keep persistence.isMigrationEnabled(DELEGATE_TASK_CLASS_NAME);
___
*[`420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java` line 103 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNkwulv8xBuWL1kObfy:-NNkwulv8xBuWL1kObfz:bsmtie3) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java#L103)):*
> ```Java
>           getTotalNumberOfTaskAssignedInDelegate_FromDMS(accountId, taskType, delegateId);
> 
>       if (isEmpty(delegateTaskList)) {
> ```

FYI same as before, not blocking but this logic is not necessary. 
___
*[`420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java` line 119 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNkx2c7ARWzwEVCC7-A:-NNkx2c7ARWzwEVCC7-B:b-7fyubw) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java#L119)):*
> ```Java
>   }
> 
>   private List<DelegateTask> getTotalNumberOfTaskAssignedInDelegate_FromDMS(
> ```

FYI same as before, not blocking, but this is duplicated code with only boolean flag different. 


<!-- Sent from Reviewable.io -->

2023-02-08 19:06 UTC, mdmilic submitted a review, later dismissed
> Reviewed 7 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 1 change requests. 17. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-09 07:01 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 1 change requests. 17. unresolved discussions. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java` line 22 at r13](https://reviewable.io/reviews/harness/harness-core/43185#-NNoxup0Cg0KnhG7xJK9:-NNoxup0Cg0KnhG7xJKA:b-wlyizp) ([raw file](https://github.com/harness/harness-core/blob/1df4bbd8ba937f80786c1580d86584f550e1b45f/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java#L22)):*
> ```Java
> @Slf4j
> public class DelegateTaskMigrationHelper {
>   private static final String NEW_DELEGATE_TASK_UUID_STATE = "-NEW";
> ```

for a period of time the taskid-NEW will be exposed to UI until the migration finishes. 

I am afraid the word "NEW" will cause confusion for customers. shall we use some words less "attractive"  @gaurav-jain1 @arpit3107  
___
*[`420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java` line 105 at r13](https://reviewable.io/reviews/harness/harness-core/43185#-NNou3Cy2tqO_UlQXf-e:-NNou3Cy2tqO_UlQXf-f:b-r5k0by) ([raw file](https://github.com/harness/harness-core/blob/1df4bbd8ba937f80786c1580d86584f550e1b45f/420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java#L105)):*
> ```Java
>   }
> 
>   private List<DelegateTask> getTotalNumberOfTaskAssignedInDelegate(
> ```

rename this function to getTasksAssignedInDelegate


<!-- Sent from Reviewable.io -->

2023-02-09 14:52 UTC, mdmilic submitted a review, later dismissed
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 1 change requests. 17. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-14 05:20 UTC, xingchi-jin approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: Some of the checks are too old. 1 change requests. 17. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-14 08:14 UTC, gaurav-jain1 reviewed
> Reviewed 1 of 3 files at r3, 12 of 32 files at r5, 1 of 2 files at r6, 30 of 34 files at r7, 5 of 11 files at r9, 4 of 7 files at r10, 3 of 7 files at r13, 5 of 6 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 90 at r14](https://reviewable.io/reviews/harness/harness-core/43185#-NNrMein2NsBzUvpz8nd:-NODb_ws2DB8KkoXAGQg:b2xf87j) ([raw file](https://github.com/harness/harness-core/blob/d36dcbd491c6d1f20819d33e4aba2f8fc8acf141/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L90)):*
> ving a discussion with him, anyway old iterator will be running on old DB with both REDIS mode and PUMP mode. But new iterator will be running on new DB only through PUMP mode as this is temporary
Actually we cannot right away turn the broadcast off from old db, I have introduced one config variable which we can tune to turn off activity from old db.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1846 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNkrVo47OdrYeWj1aJP:-NODizKIBoAjH-Sm7vuV:b-oechvq) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1846)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This is not a blocking comment since it's temp code, but if you do need to make some other changes you can update it. Collectors can only ever return empty list, never null. That means you don't really need this logic, you could just do 
</blockquote></details>

If we remove if condition above, what can happens here we end up inserting delegateTask entry twice. As it's possible that mongomirror is running but we haven't turned on the flag.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1863 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNks1JpBmM172n876OY:-NODjYzd3XYVEq7bhd-F:b78wami) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1863)):*
> his entire method is duplicated with only difference of boolean flag. Same goes for abort and delete cases. You could instead do something like snippet 1 (afaik new createQuery with migration false is just like old createQuery with no params) or if you think that would degrade performance something like snippet 2. Btw always do final 
Ack
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java` line 22 at r13](https://reviewable.io/reviews/harness/harness-core/43185#-NNoxup0Cg0KnhG7xJK9:-NODlLmw0HZ-EfM6Y7Jb:bbdgqgm) ([raw file](https://github.com/harness/harness-core/blob/1df4bbd8ba937f80786c1580d86584f550e1b45f/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateTaskMigrationHelper.java#L22)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

for a period of time the taskid-NEW will be exposed to UI until the migration finishes. 

I am afraid the word "NEW" will cause confusion for customers. shall we use some words less "attractive"  @gaurav-jain1 @arpit3107  
</blockquote></details>

Done, renamed this to -DEL


<!-- Sent from Reviewable.io -->

2023-02-14 15:55 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1846 at r11](https://reviewable.io/reviews/harness/harness-core/43185#-NNkrVo47OdrYeWj1aJP:-NOFcRsR8DtU-4bTbm_D:bf0as6u) ([raw file](https://github.com/harness/harness-core/blob/41106e56b9a04812b5f8b45e96f8a8fd81e2f945/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1846)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

If we remove if condition above, what can happens here we end up inserting delegateTask entry twice. As it's possible that mongomirror is running but we haven't turned on the flag.
</blockquote></details>

No Gaurav, that will not happen. As mongoMirror is not in picture for delegateTask. We are relying only on flags


<!-- Sent from Reviewable.io -->

2023-02-14 16:30 UTC, jennyjames21 reviewed
> Reviewed 1 of 7 files at r13.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-14 16:30 UTC, jennyjames21 submitted a review, later dismissed
> Reviewed 1 of 3 files at r3, 6 of 32 files at r5, 30 of 34 files at r7, 2 of 7 files at r10, 2 of 7 files at r13, 3 of 6 files at r14, 1 of 2 files at r15, 5 of 6 files at r16, 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-15 13:09 UTC, gaurav-jain1 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: 51 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-02-16 09:13 UTC, gaurav-jain1 approved these changes
> Reviewed 5 of 6 files at r16, 2 of 4 files at r17, 15 of 15 files at r18, 34 of 36 files at r19, 3 of 3 files at r20, 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-16 17:09 UTC, Raghav-Murali reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: :shipit: complete! ✓

___
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1519 at r21](https://reviewable.io/reviews/harness/harness-core/43185#-NOQBDH89vmMcUQIKbyN:-NOQBDH99Fi2IRinOdg3:b-p5mmyh) ([raw file](https://github.com/harness/harness-core/blob/6596aa9814e32187ed9926d2fd591ade3bd7b983/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1519)):*
> ```Java
>     injector.getInstance(DelegateDisconnectDetectorIterator.class).registerIterator(iteratorExecutionHandler);
>     injector.getInstance(FailDelegateTaskIterator.class).registerIterator(iteratorExecutionHandler);
>     injector.getInstance(FailDelegateTaskIteratorOnDMS.class).registerIterator(iteratorExecutionHandler);
> ```

This one just registers the iterator, it won't yet start the iterator.
___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorOnDMS.java` line 35 at r21](https://reviewable.io/reviews/harness/harness-core/43185#-NOQBPc23XkhcUQPqJEt:-NOQBPc23XkhcUQPqJEu:bf6qryi) ([raw file](https://github.com/harness/harness-core/blob/6596aa9814e32187ed9926d2fd591ade3bd7b983/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorOnDMS.java#L35)):*
> ```Java
> 
>   @Override
>   public void createAndStartIterator(
> ```

If you want this method to be invoked then you have to add a config for this iterator in iterator_config.json. Note that you have to update the manager-iterator/templates/confif.yaml in all envs - PR, Pre-QA, QA and Prod for this to take effect in those env. Else the other way is to not override the IteratorPumpModeHandler and instead start the iterator with hardcoded configs.


<!-- Sent from Reviewable.io -->

2023-02-16 17:13 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: :shipit: complete! ✓

___
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1519 at r21](https://reviewable.io/reviews/harness/harness-core/43185#-NOQBDH89vmMcUQIKbyN:-NOQCJxe8_Eaj2Fp67X8:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/6596aa9814e32187ed9926d2fd591ade3bd7b983/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1519)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

This one just registers the iterator, it won't yet start the iterator.
</blockquote></details>

Yes
___
*[`400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorOnDMS.java` line 35 at r21](https://reviewable.io/reviews/harness/harness-core/43185#-NOQBPc23XkhcUQPqJEt:-NOQCU3j96JkB4E9kQOG:b-6vfeya) ([raw file](https://github.com/harness/harness-core/blob/6596aa9814e32187ed9926d2fd591ade3bd7b983/400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorOnDMS.java#L35)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

If you want this method to be invoked then you have to add a config for this iterator in iterator_config.json. Note that you have to update the manager-iterator/templates/confif.yaml in all envs - PR, Pre-QA, QA and Prod for this to take effect in those env. Else the other way is to not override the IteratorPumpModeHandler and instead start the iterator with hardcoded configs.
</blockquote></details>

Yes. And i want to enable this iterator dynamically and on selected envs only. I dont want to enable it on PR env globally, but just to test the functionality I am enabling it. But manager deployment is failing because of this.
Here is the pr to enable it dynamically for manager only. https://github.com/wings-software/ng-pr-manifests/pull/425/files


<!-- Sent from Reviewable.io -->

2023-02-21 07:16 UTC, Raghav-Murali approved these changes
> Reviewed 1 of 3 files at r3, 8 of 32 files at r5, 30 of 34 files at r7, 2 of 11 files at r9, 3 of 7 files at r10, 2 of 7 files at r13, 3 of 6 files at r14, 1 of 2 files at r15, 4 of 6 files at r16, 2 of 4 files at r17, 15 of 15 files at r18, 34 of 36 files at r19, 3 of 3 files at r20, 3 of 4 files at r21, 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43185)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-21 10:27 UTC, merged