[feat]: [CDS-50873]: Delete trigger event history when pipeline is deleted
harness/harness-core pull request #43304
Opened 2023-01-31 14:37 UTC by rathodmeetsatish

## Describe your changes
Delete trigger event history when pipeline is deleted

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-01 12:37 UTC, vcalasansh submitted a review, later dismissed
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43304)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-02 00:27 UTC, sribalij requested changes

2023-02-02 00:27 UTC, sribalij commented on pipeline-service/service/src/test/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListenerTest.java
> +  @Mock private NGTriggerEventsService ngTriggerEventsService;
Can you add a few Junits to test it?

2023-02-02 10:42 UTC, rathodmeetsatish reviewed
> Reviewed 4 of 5 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43304)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListenerTest.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/43304#-NNBXEasALV8j_HCvwpR-r2-66:-NNGi8FWBp9VBswTeyOG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d83e4a60b6183c296a7bd83893f0253011e4ee4e/pipeline-service/service/src/test/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListenerTest.java#L66)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Can you add a few Junits to test it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-02 16:37 UTC, sribalij approved these changes
> Reviewed 4 of 5 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43304)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-02 22:34 UTC, rathodmeetsatish commented
trigger messagecheck

2023-02-02 22:36 UTC, vcalasansh approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43304)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 22:36 UTC, vcalasansh approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43304)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 23:43 UTC, sribalij approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43304)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-03 04:57 UTC, sahilhindwani-harness approved these changes
> Reviewed 4 of 5 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43304)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-03 05:01 UTC, merged