fix: [SRM-13807]: Making call to update analysis type null safe
harness/harness-core pull request #43317
Opened 2023-01-31 18:55 UTC by dhruv-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-01 07:10 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java
> +    log.info("Creating  Activity {}", activity.toString());
tostring is not needed theres issue of null safety too, we should add object only.
Also I think log with DB state changes will help , add it for create too.

2023-02-01 07:14 UTC, n00bitax submitted a review, later dismissed
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-01 07:38 UTC, AbhijithHarness commented
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/43317#-NN8Aj4DpQSny_tmIwe5-r2-159:-NNAtKvK5Oag1E0K8q5M:bx5gf60) ([raw file](https://github.com/harness/harness-core/blob/0321682a34f855b24f8bdac46bf4e6c3c67aa9f5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java#L159)):*
<details><summary><i>Previously, n00bitax (Ansuman Satapathy) wrote…</i></summary><blockquote>

tostring is not needed theres issue of null safety too, we should add object only.
Also I think log with DB state changes will help , add it for create too.
</blockquote></details>

Lets not print the entire activity. There are yaml diffs also present for some activities that the activity can be too large. Just print getEntityKeyLongString() value of it.


<!-- Sent from Reviewable.io -->

2023-02-01 07:43 UTC, AbhijithHarness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: 1 change requests. 1. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStep.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/43317#-NNAu_x48hrVPpleh46A:-NNAu_x50U6ljKcEAAw9:bx54bf7) ([raw file](https://github.com/harness/harness-core/blob/0321682a34f855b24f8bdac46bf4e6c3c67aa9f5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStep.java#L128)):*
> ```Java
>     String monitoredServiceTemplateVersionLabel = resolvedCVConfigInfo.getMonitoredServiceTemplateVersionLabel();
>     List<CVConfig> cvConfigs = resolvedCVConfigInfo.getCvConfigs();
>     log.info("ResolvedCVConfigInfo {}", resolvedCVConfigInfo);
> ```

Just print CV Config Id. Dont see much use of these, as it will be anyway saved in the verificationJobInstance log


<!-- Sent from Reviewable.io -->

2023-02-01 08:55 UTC, dhruv-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java
> +    log.info("Creating  Activity {}", activity.toString());
Addressed

2023-02-01 08:56 UTC, dhruv-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStep.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/43317#-NNAu_x48hrVPpleh46A:-NNBBIjWA7n9271BdyPZ:b32w0x) ([raw file](https://github.com/harness/harness-core/blob/0321682a34f855b24f8bdac46bf4e6c3c67aa9f5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStep.java#L128)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Just print CV Config Id. Dont see much use of these, as it will be anyway saved in the verificationJobInstance log
</blockquote></details>

OK
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/43317#-NN8Aj4DpQSny_tmIwe5-r2-159:-NNBBBDk-SwV8uB4IHTQ:bq76sqt) ([raw file](https://github.com/harness/harness-core/blob/0321682a34f855b24f8bdac46bf4e6c3c67aa9f5/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java#L159)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Addressed
</blockquote></details>

Removed the log for activity class as there is a log already present at the end


<!-- Sent from Reviewable.io -->

2023-02-01 09:23 UTC, deepak-harness approved these changes
> Reviewed 1 of 6 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-01 12:27 UTC, n00bitax approved these changes

2023-02-02 04:39 UTC, AbhijithHarness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 04:40 UTC, AbhijithHarness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 04:41 UTC, AbhijithHarness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 04:44 UTC, n00bitax approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 04:45 UTC, n00bitax approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43317)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-02 04:45 UTC, merged