Google Cloud Function Instance Sync
harness/harness-core pull request #43314
Opened 2023-01-31 18:15 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-02 04:03 UTC, sainath-b approved these changes

2023-02-02 04:05 UTC, sainath-b approved these changes
> Reviewed 40 of 46 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43314)* status: 49 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-03 06:14 UTC, PragyeshMishra01 requested changes

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionCommandTaskHelper.java
>      }
why remove this?

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionCommandTaskHelper.java
> +      return Optional.empty();
this can be a regression

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/googlefunctionbeans/response/GoogleFunctionPrepareRollbackResponse.java
here, project and region should not be required.

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/googlefunctionbeans/response/GoogleFunctionDeployWithoutTrafficResponse.java
here, dont we need infrastructure key also?

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/googlefunctionbeans/response/GoogleFunctionDeployResponse.java
here, dont we need infrastructure key ?

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionCommandTaskHelper.java
> +          + "Directory: " + repoSource.getDir();
remove repoSource?

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionCommandTaskHelper.java
>          .environment(function.getEnvironment().name())
why do we need updated time?

2023-02-03 06:14 UTC, PragyeshMishra01 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionCommandTaskHelper.java
>    }
why we remove exception, it will throw NPE.

2023-02-03 07:09 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/instance/util/InstanceSyncStepResolver.java
this will be done in separate PR, this can be tracked in Test Plan 
https://docs.google.com/spreadsheets/d/10AuhZ7s2nEnSwvv61LFhICU6HMeXm03zwXe7NInGMRw/edit#gid=0

2023-02-03 07:10 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/googlefunction/GoogleFunctionDeployCommandTaskHandler.java
> +          iLogStreamingTaskClient, GoogleFunctionsCommandUnitConstants.deploy.toString(), true, commandUnitsProgress);
Changed it back

2023-02-03 07:17 UTC, alluvamsi-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/googlefunction/GoogleFunctionCommandTaskHelper.java
>      }
Changed it back

2023-02-03 07:19 UTC, sainath-b requested changes

2023-02-03 07:19 UTC, sainath-b commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/googlefunctionbeans/response/GoogleFunctionTrafficShiftResponse.java
> +  String project;
Is it this added while resolving conflicts? Its not related to instance sync i think. Better to resolve conflicts again.

2023-02-03 07:31 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/googlefunctions/beans/GoogleFunctionStepOutcome.java
> +  long updatedTime;
Lets remove source updatedTime

2023-02-03 11:36 UTC, PragyeshMishra01 requested changes

2023-02-03 11:36 UTC, PragyeshMishra01 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/instance/util/InstanceSyncStepResolver.java
> +      AsgBlueGreenDeployStep.STEP_TYPE.getType(), AsgBlueGreenDeployStep.STEP_TYPE.getType(),
can we remove duplicates here

2023-02-03 12:07 UTC, PragyeshMishra01 approved these changes

2023-02-03 12:08 UTC, PragyeshMishra01 submitted a review, later dismissed
> Reviewed 26 of 46 files at r1, 1 of 9 files at r2, 22 of 23 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43314)* status: 23 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-03 13:54 UTC, alluvamsi-harness commented
trigger ti1, trigger ti2

2023-02-03 16:12 UTC, sainath-b submitted a review, later dismissed

2023-02-03 16:12 UTC, sainath-b reviewed
> Reviewed 22 of 23 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43314)* status: 9 file(s) to review. 3. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-04 08:46 UTC, sainath-b approved these changes

2023-02-04 08:47 UTC, sainath-b reviewed
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43314)* status: 9 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-04 10:53 UTC, merged