feat: [PIE-7997]: Need merge api for rerun page based on planExecutionId
harness/harness-core pull request #43342
Opened 2023-02-01 09:05 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-01 09:38 UTC, mohitg0795 commented
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 407 at r1](https://reviewable.io/reviews/harness/harness-core/43342#-NNBKkhb-Yq4qhYTSzGl:-NNBKkhb-Yq4qhYTSzGm:bqb2wyk) ([raw file](https://github.com/harness/harness-core/blob/6d8633f4747ceb217344ff9c87efef321ae5dab6/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L407)):*
> ```Java
> 
>   @POST
>   @Path("mergeForRerun")
> ```

We should use camel casing for paths. Its much clearer. Also, we can check with API squad if there are any other recommendations on the same.


<!-- Sent from Reviewable.io -->

2023-02-01 09:39 UTC, mohitg0795 commented
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetForRerunRequestDTO.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/43342#-NNBKyeI645Wxh4m-MRg:-NNBKyeI645Wxh4m-MRh:bykzz7p) ([raw file](https://github.com/harness/harness-core/blob/6d8633f4747ceb217344ff9c87efef321ae5dab6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetForRerunRequestDTO.java#L38)):*
> ```Java
>       description =
>           "This is a boolean value that indicates if the response must contain the YAML for the merged Pipeline. The default value is False.")
>   boolean withMergedPipelineYaml;
> ```

the variable name seems ambiguous and doesn't clearly represent what does it actually mean. May be something better would be : eg: "getResponseWithMergedPipelineYaml" or "getMergedPipelineYamlInResponse" or similar.


<!-- Sent from Reviewable.io -->

2023-02-01 09:40 UTC, namanvermah requested changes

2023-02-01 09:40 UTC, namanvermah commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +        "Invalid request : Input Set did not exist or pipeline execution has been deleted");
Why would this mean that input set is deleted? And which input set for that matter?

2023-02-01 09:40 UTC, namanvermah commented on pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java
> +
Empty line here can be removed

2023-02-01 09:40 UTC, namanvermah commented on pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java
> +  public String mergeInputSetIntoPipelineForRerun(String accountId, String orgIdentifier, String projectIdentifier,
Please add a unit test for this

2023-02-01 10:47 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 272 at r1](https://reviewable.io/reviews/harness/harness-core/43342#-NNBDQ4p4_X4sI_22gbV-r1-272:-NNB_h0-EFQQR-OO87-D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d8633f4747ceb217344ff9c87efef321ae5dab6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L272)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Please add a unit test for this
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 282 at r1](https://reviewable.io/reviews/harness/harness-core/43342#-NNBDQ4p4_X4sI_22gbW-r1-282:-NNBLkVBA4jCC8QeNkK8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d8633f4747ceb217344ff9c87efef321ae5dab6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L282)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Empty line here can be removed
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 457 at r1](https://reviewable.io/reviews/harness/harness-core/43342#-NNBDQ4p4_X4sI_22gbY-r1-457:-NNBMZgL5htDMQ4mrMTh:b-sddf2g) ([raw file](https://github.com/harness/harness-core/blob/6d8633f4747ceb217344ff9c87efef321ae5dab6/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L457)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Why would this mean that input set is deleted? And which input set for that matter?
</blockquote></details>

yeah, this would actually only mean that the pipeline execution has been deleted since we didn't send anything related to input set in the query


<!-- Sent from Reviewable.io -->

2023-02-01 10:53 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetForRerunRequestDTO.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/43342#-NNBKyeI645Wxh4m-MRg:-NNBaCBN99o5j2TGjuA_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d8633f4747ceb217344ff9c87efef321ae5dab6/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetForRerunRequestDTO.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

the variable name seems ambiguous and doesn't clearly represent what does it actually mean. May be something better would be : eg: "getResponseWithMergedPipelineYaml" or "getMergedPipelineYamlInResponse" or similar.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-01 11:09 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342)* status: 9 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 407 at r1](https://reviewable.io/reviews/harness/harness-core/43342#-NNBKkhb-Yq4qhYTSzGl:-NNBeXgSBn5A7hJUkZN9:b-kr7k2l) ([raw file](https://github.com/harness/harness-core/blob/6d8633f4747ceb217344ff9c87efef321ae5dab6/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L407)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should use camel casing for paths. Its much clearer. Also, we can check with API squad if there are any other recommendations on the same.
</blockquote></details>

renamed the path of merge-for-rerun


<!-- Sent from Reviewable.io -->

2023-02-01 11:09 UTC, namanvermah approved these changes
> Reviewed 1 of 6 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342)* status: 9 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-01 14:23 UTC, archit-harness approved these changes
> Reviewed 3 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-02 05:42 UTC, ankittiwari-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342#-:-NNFdSVk4R9v4oWwrmC4:bnfp4nl)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 06:01 UTC, namanvermah approved these changes
> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-02 06:28 UTC, mohitg0795 approved these changes
> Reviewed 3 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43342)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-02 06:40 UTC, merged