feat: [PL-30901]: Add caching for apiToken and password
harness/harness-core pull request #43352
Opened 2023-02-01 11:15 UTC by bhavya181

## Describe your changes
Add caching for apiToken and password

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-02 17:39 UTC, puneetsar commented on 965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java
> +  private final Cache<String, String> apiTokenPasswordCache =
String in the Value will be stored in heap, and we will not have control over its garbage collection. Can we use char[] instead? Or wrap it value in a class with char[]. And explicitly clear the value on cache eviction and application shutdown.

2023-02-02 17:43 UTC, puneetsar commented on 965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java
> +  public void setCache(String tokenId, String password) {
Instead of manually loading cache, it will be better to use asynchronous loading?
https://www.baeldung.com/java-caching-caffeine#3-asynchronous-loading

2023-02-02 17:43 UTC, puneetsar commented on 965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java
> +      Caffeine.newBuilder().maximumSize(1000).expireAfterAccess(1, TimeUnit.MINUTES).build();
How did we come up with 1000 as the cache size? and 1 Min as the expiry?

2023-02-03 06:59 UTC, ankit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43352)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 180 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL3ZWLA3McSal-PhpX:-NNL3ZWLA3McSal-PhpY:b4qrwxz) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L180)):*
> ```Java
>     return Failsafe.with(DEFAULT_RETRY_POLICY).get(() -> transactionTemplate.execute(status -> {
>       tokenRepository.deleteById(optionalToken.get().getUuid());
>       tokenPasswordCacheHelper.invalidateCache(optionalToken.get().getUuid());
> ```

tokenPasswordValidationHelper.invalidateToken()
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL1NuBE4K08e_8tnmc:-NNL1NuBE4K08e_8tnmd:b8qw4i2) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L23)):*
> ```Java
> @OwnedBy(PL)
> @Slf4j
> public class TokenPasswordCacheHelper {
> ```

ApiKeyPasswordCacheHelper
Cache<String, char[]> apiKeyPasswordCache
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL1CM26J6wauUJCqGt:-NNL1CM26J6wauUJCqGu:b-7tfo1v) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L27)):*
> ```Java
>       Caffeine.newBuilder().maximumSize(1000).expireAfterAccess(1, TimeUnit.MINUTES).build();
> 
>   public void setCache(String tokenId, String password) {
> ```

add()
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL194E-T4mGOUwQTWg:-NNL194E-T4mGOUwQTWh:b5vtlnd) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L45)):*
> ```Java
>   }
> 
>   public void invalidateCache(String tokenId) {
> ```

invalidateToken
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL2HoJ6rLYYjXXsbFu:-NNL2HoJ6rLYYjXXsbFv:b-159g2r) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L49)):*
> ```Java
>       apiTokenPasswordCache.invalidate(tokenId);
>     } else {
>       log.debug("Not able to remove raw password from cache, tokenId is null.");
> ```

You can remove these debug logs. not required


<!-- Sent from Reviewable.io -->

2023-02-03 14:15 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43352)* status: 4 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 180 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL3ZWLA3McSal-PhpX:-NNMb74y1405rDXI5Wo-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L180)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

tokenPasswordValidationHelper.invalidateToken()
</blockquote></details>

Done.
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL1NuBE4K08e_8tnmc:-NNMb92H96PVEgwjNsm6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L23)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

ApiKeyPasswordCacheHelper
Cache<String, char[]> apiKeyPasswordCache
</blockquote></details>

Done.
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNBroaNZAt_gXTwwq2W-r3-24:-NNMbDSy9n2VPM9-T573:b-hkfpn2) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L24)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

String in the Value will be stored in heap, and we will not have control over its garbage collection. Can we use char[] instead? Or wrap it value in a class with char[]. And explicitly clear the value on cache eviction and application shutdown.
</blockquote></details>

changed it to use char[]
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNBroaNZAt_gXTwwq2W-r3-25:-NNMbu9wE5Jp3mfb_-jw:blkrf0v) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L25)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

How did we come up with 1000 as the cache size? and 1 Min as the expiry?
</blockquote></details>

We do not want to have values in cache for longer time as its security sensitive and we have seen that request comes in a bulk for validation for with one minute access expiry, it will able to handle that bulk requests that causes cpu spike and also would be more safer
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNBroaNZAt_gXTwwq2W-r3-27:-NNMbJV2D2TA8gqbQJDs:b-ms1lqz) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L27)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

Instead of manually loading cache, it will be better to use asynchronous loading?
https://www.baeldung.com/java-caching-caffeine#3-asynchronous-loading
</blockquote></details>

asynchronous loading is used for two purposes - 
1. large number of update operations
2. need to large many keys at one time
And our use-case does not have any such requirement, so, we can use manual loading here, it will have almost same performance time.
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL1CM26J6wauUJCqGt:-NNMbrZB0eCbJEkqAbDE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L27)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

add()
</blockquote></details>

Done.
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL194E-T4mGOUwQTWg:-NNMbsBt1y3T1fDhsvV7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L45)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

invalidateToken
</blockquote></details>

Done.
___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNL2HoJ6rLYYjXXsbFu:-NNMbsSY3_MibsbmHjPx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

You can remove these debug logs. not required
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-03 14:28 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43352)* status: 4 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/43352#-NNBroaNZAt_gXTwwq2W-r3-25:-NNMew9m82mdvlJE3uNF:bt3qycd) ([raw file](https://github.com/harness/harness-core/blob/7e36c2d10740f98878a8d67a14e18ef87d924a3b/965-api-key-filter/src/main/java/io/harness/token/TokenPasswordCacheHelper.java#L25)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

We do not want to have values in cache for longer time as its security sensitive and we have seen that request comes in a bulk for validation for with one minute access expiry, it will able to handle that bulk requests that causes cpu spike and also would be more safer
</blockquote></details>

We have put 5000 as cache size, as we found that each entry is taking almost 100B, so cache will take 5MB in memory and in PROD, in one minute, there are approximately 250 token validation calls, so, 5000 would suffice as expiry time is very less.


<!-- Sent from Reviewable.io -->

2023-02-06 04:58 UTC, ankit-harness reviewed
> Reviewed 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43352)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-06 05:37 UTC, puneetsar approved these changes
> Reviewed 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43352)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-06 10:28 UTC, ankit-harness approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43352)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-06 11:53 UTC, kshitij-harness approved these changes
> Reviewed 2 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43352)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-06 11:54 UTC, merged