fix: [CDS-52386]: workflow rbac cover index
harness/harness-core pull request #43403
Opened 2023-02-02 06:58 UTC by abhinav-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-03 17:31 UTC, Fernando-Dourado submitted a review, later dismissed
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43403)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-04 16:13 UTC, ankit-harness submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 8 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43403#-:-NNSC64tA0GxpZcyCYlG:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-05 06:44 UTC, kshitij-harness requested changes

2023-02-05 06:44 UTC, kshitij-harness commented on 400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java
> +      findOptions.hint(BasicDBUtils.getIndexObject(WorkflowExecution.mongoIndexes(), queryHint));
This should be Workflow.mongoIndexes()

2023-02-07 04:46 UTC, kshitij-harness approved these changes
> Reviewed 3 of 8 files at r3, 3 of 3 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43403)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-07 12:00 UTC, rijajoo commented
"..by allowing developers with index with certain name to allow have id in composite index."
Don't we allow indexes with id in composite index to have any names here?

2023-02-07 21:16 UTC, RajBaviskar approved these changes

2023-02-07 21:16 UTC, abhinav-harness commented
@rijajoo thats bad english :P 
the aim was to not have uuid as part of any composite index

2023-02-07 21:16 UTC, RajBaviskar approved these changes
> Reviewed 3 of 8 files at r3, 3 of 3 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43403)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-07 21:16 UTC, merged

2023-02-07 21:16 UTC, RajBaviskar approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43403)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->