feat: [IDP-62]: API Spec for token management
harness/harness-core pull request #43482
Opened 2023-02-03 10:38 UTC by vikyathharekal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-04 03:54 UTC, vigneswara-propelo requested changes
> Reviewed 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/app/IDPModule.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/43482#-NNPYRYg9yeosjGDthkq:-NNPYRYg9yeosjGDthkr:bwht6m6) ([raw file](https://github.com/harness/harness-core/blob/89d47a12ef818f5b3e84ec1887ac84c2781ecf2c/idp-service/service/src/main/java/io/harness/idp/app/IDPModule.java#L126)):*
> ```Java
>     bind(EnvironmentVariableService.class).to(EnvironmentVariableServiceImpl.class);
>     bind(ConfigManagerResource.class).to(ConfigManagerResourceImpl.class);
>     bind(SecretManagerApi.class).to(SecretManagerApiImpl.class);
> ```

are we not including SecretManagerApi.java in this PR ?


<!-- Sent from Reviewable.io -->

2023-02-06 01:18 UTC, sandeepa-kv-jois reviewed
Since x-internal: true isn't specified, it will be added as a public endpoint. I guess as this endpoint details are not added in [x-tags.yaml](https://github.com/harness/harness-core/blob/develop/scripts/api/external/x-tags.yaml),  it will be skipped from API Documentation which goes public. Can we ensure that these new endpoints are not added to customer facing API doc since this module is under development?

2023-02-06 01:22 UTC, sandeepa-kv-jois commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +  /v1/secret:
Since we don't have the service name in endpoint now, I believe we need to ensure these paths are unique across the repo unlike earlier when uniqueness was scoped inside the module.

2023-02-06 04:48 UTC, vikyathharekal reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/app/IDPModule.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/43482#-NNPYRYg9yeosjGDthkq:-NN_1TIq2s4QPQ_sn__i:bbj8nb) ([raw file](https://github.com/harness/harness-core/blob/89d47a12ef818f5b3e84ec1887ac84c2781ecf2c/idp-service/service/src/main/java/io/harness/idp/app/IDPModule.java#L126)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

are we not including SecretManagerApi.java in this PR ?
</blockquote></details>

We have to run ` bazel build //idp-service/contracts/openapi/v1:idp-service-server-spec-module --sandbox_debug --verbose_failures`. This will generate the SecretManagerApi.class in the bazel directory.

For example, for me it is here - 
`/private/var/tmp/_bazel_vikyath.harekal/6966dd0f550ac7d6a7f29b5122d99702/execroot/harness_monorepo/bazel-out/darwin_arm64-fastbuild/bin/idp-service/contracts/openapi/v1/libidp-service-server-spec-module-ijar.jar!/io/harness/spec/server/idp/v1/SecretManagerApi.class`


<!-- Sent from Reviewable.io -->

2023-02-07 05:57 UTC, vikyathharekal commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +  /v1/secret:
changed to /environment-secrets

2023-02-07 09:53 UTC, vikyathharekal commented
trigger ti0

2023-02-07 11:21 UTC, vikyathharekal commented
trigger ti2

2023-02-07 14:01 UTC, vigneswara-propelo approved these changes

2023-02-08 03:50 UTC, sandeepa-kv-jois submitted a review, later dismissed

2023-02-08 03:50 UTC, sandeepa-kv-jois reviewed
> Reviewed 3 of 6 files at r1, 5 of 10 files at r2, 20 of 21 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: 24 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-08 13:46 UTC, mankrit-singh commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +          $ref: '#/components/responses/EnvironmentSecretResponse'
preferred to have delete with 204 response and no response body

2023-02-08 13:46 UTC, mankrit-singh commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +      summary: DeleteEnvironmentSecret
For internal APIs this is not compulsory, but before these are exposed as public please rename Summary as a better phrase like "Deletes an Environment Secret"

2023-02-08 13:46 UTC, mankrit-singh commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +        secretIdentifier:
please make this snake case : secret_identifier and optionally add parameter descriptions if this endpoint will be public in future

2023-02-08 13:46 UTC, mankrit-singh commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +  requestBodies:
optionally add support for application/yaml and examples, for both request and response bodies

2023-02-08 13:46 UTC, mankrit-singh commented on idp-service/contracts/openapi/v1/openapi.yaml
> +openapi: 3.0.3
same comments as SNAPSHOT folder

2023-02-08 15:34 UTC, vikyathharekal commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +          $ref: '#/components/responses/EnvironmentSecretResponse'
done

2023-02-08 15:34 UTC, vikyathharekal commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +      summary: DeleteEnvironmentSecret
done

2023-02-08 15:35 UTC, vikyathharekal commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +        secretIdentifier:
Done. Planning to add descriptions later

2023-02-08 15:40 UTC, vikyathharekal commented on idp-service/contracts/openapi/SNAPSHOT/openapi.yaml
> +  requestBodies:
Added support application/yaml. Will add examples later.

2023-02-08 16:13 UTC, mankrit-singh approved these changes
> Reviewed 3 of 6 files at r1, 4 of 10 files at r2, 16 of 21 files at r3, 1 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-08 16:15 UTC, vigneswara-propelo submitted a review, later dismissed
> Reviewed 3 of 6 files at r1, 16 of 21 files at r3, 1 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-09 05:52 UTC, vikyathharekal reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: 1. unresolved discussions. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/43482#-NNLqiskCMrEwFb9obMD-r2-11:-NNoivGnBxj7NhJvZRbh:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/89d47a12ef818f5b3e84ec1887ac84c2781ecf2c/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L11)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

changed to /environment-secrets
</blockquote></details>

Done
___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 1 at r5](https://reviewable.io/reviews/harness/harness-core/43482#-NNLqiskCMrEwFb9obMH-r5-1:-NNoistc10ox6DNnWBBB:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ed8f4ef650bc64b908c0c9f54c1920f020459aff/idp-service/contracts/openapi/v1/openapi.yaml#L1)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

same comments as SNAPSHOT folder
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-02-09 05:54 UTC, vikyathharekal commented
trigger ti0, ti1, ti2, ti3

2023-02-09 05:54 UTC, vikyathharekal commented
trigger ti4

2023-02-09 12:13 UTC, vikyathharekal commented
trigger ti4

2023-02-10 01:54 UTC, sandeepa-kv-jois approved these changes

2023-02-13 05:04 UTC, mankrit-singh approved these changes
> Reviewed 7 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: Some of the checks are too old. 8 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-13 05:51 UTC, sandeepa-kv-jois reviewed
> Reviewed 1 of 3 files at r5, 3 of 5 files at r6, 7 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: Some of the checks are too old. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-13 05:52 UTC, sandeepa-kv-jois approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-02-13 06:13 UTC, vigneswara-propelo approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-02-13 10:58 UTC, mankrit-singh approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-13 10:58 UTC, devesh-harness approved these changes
> Reviewed 3 of 6 files at r1, 3 of 10 files at r2, 15 of 21 files at r3, 1 of 3 files at r5, 3 of 5 files at r6, 7 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-13 12:01 UTC, deepharness approved these changes

2023-02-13 12:02 UTC, deepharness approved these changes
> Reviewed 3 of 6 files at r1, 5 of 10 files at r2, 20 of 21 files at r3, 1 of 1 files at r4, 1 of 3 files at r5, 3 of 5 files at r6, 7 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43482)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-13 12:03 UTC, merged