fix: [CDS-51663]: Handling Sync Status Response detail message
harness/harness-core pull request #43533
Opened 2023-02-06 06:32 UTC by namantalaycha10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-06 10:18 UTC, abosii-harness requested changes

2023-02-06 10:18 UTC, abosii-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +      if (k8sTaskExecutionResponse.getCommandExecutionStatus().equals(FAILURE)) {
Can we move this after line 924

2023-02-06 10:20 UTC, abosii-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +      if (k8sTaskExecutionResponse.getCommandExecutionStatus().equals(FAILURE)) {
Can we handle this for helm sync reponse (before line 939)

2023-02-07 09:01 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43533)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 928 at r3](https://reviewable.io/reviews/harness/harness-core/43533#-NN_QNpGz337nj3EmmRG-r3-928:-NNf5odZ52nSZI7YznkY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c6ace8c6dfcab310324c4d191dcc3e8b10632f4/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L928)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we handle this for helm sync reponse (before line 939)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-07 10:48 UTC, abhinavsingh1196 approved these changes
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43533)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-07 10:48 UTC, abosii-harness approved these changes
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43533)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-07 11:05 UTC, merged