fix: [CDS-42592]: improved error message in case we are unable to fetch files from SCM service.
harness/harness-core pull request #43535
Opened 2023-02-06 07:11 UTC by GoelPratyush99

## Describe your changes
improved error message in case we are unable to fetch files from SCM service.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-06 07:15 UTC, GoelPratyush99 commented
trigger messagecheck

2023-02-06 18:06 UTC, abhinavsingh1196 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/43535#-NNbu73TBekbmvq9QteA:-NNbsHfLAJGBgckRNnCN:bhfcd75) ([raw file](https://github.com/harness/harness-core/blob/92ef16152fa71467b82d2fed5a9b43fddb1a6af6/952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java#L57)):*
> ```Java
>         log.error("Unable to fetch files from manifest.", ex);
>         return new ConnectException("Unable to fetch files from manifest. ", WingsException.USER);
>       } else {
> ```

redundant else


<!-- Sent from Reviewable.io -->

2023-02-07 08:55 UTC, abosii-harness commented on 952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java
> +      return NestedExceptionUtils.hintWithExplanationException(isNotEmpty(hintMessage) ? hintMessage : HINT_MESSAGE,
Will this affecting CG as well, right? We should throw a RuntimeException instead and have an exception handler for this

2023-02-09 11:59 UTC, abosii-harness requested changes

2023-02-09 11:59 UTC, abosii-harness commented on 952-scm-java-client/src/main/java/io/harness/exception/ScmAPIRuntimeException.java
> +public class ScmAPIRuntimeException extends ScmException {
ScmException is a wings exception, it will not trigger exception handler
Can we just reuse SCMRuntimeException

2023-02-09 12:39 UTC, abosii-harness requested changes
> Reviewed 2 of 4 files at r2, 4 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: 9 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java` line 63 at r6](https://reviewable.io/reviews/harness/harness-core/43535#-NNqAwFh0edFos_W3kJ2:-NNqAwFi0WRiTVKnRKfM:b4c7jsy) ([raw file](https://github.com/harness/harness-core/blob/d8b4062cea967870d45a8be062d20396913e8624/952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java#L63)):*
> ```Java
> 
>       log.error(String.format(SCM_ERROR, functionName), ex);
>       return new SCMRuntimeException(String.format(SCM_ERROR, functionName), ex);
> ```

Don't we need to pass here SCM_API_ERROR error code?


<!-- Sent from Reviewable.io -->

2023-02-09 13:40 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: 9 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/43535#-NNbu73TBekbmvq9QteA:-NNqOsZS4wvRq9AEgyHI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/92ef16152fa71467b82d2fed5a9b43fddb1a6af6/952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java#L57)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

redundant else
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/43535#-NN_Z80Ucx_uuh3jK9Qg-r2-72:-NNqOuVK0VbdluXyItVr:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/24896287aebb1dc727a19f2c518c7c0df5bcea16/952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java#L72)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Will this affecting CG as well, right? We should throw a RuntimeException instead and have an exception handler for this
</blockquote></details>

Yes
___
*[`952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java` line 63 at r6](https://reviewable.io/reviews/harness/harness-core/43535#-NNqAwFh0edFos_W3kJ2:-NNqOvpZ9qWuOhlDPQbj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8b4062cea967870d45a8be062d20396913e8624/952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java#L63)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Don't we need to pass here SCM_API_ERROR error code?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-10 06:28 UTC, abosii-harness approved these changes
> Reviewed 2 of 5 files at r7, 3 of 7 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-10 08:16 UTC, GoelPratyush99 commented
trigger ti0

2023-02-10 08:44 UTC, GoelPratyush99 commented
trigger ti0

2023-02-10 08:49 UTC, GoelPratyush99 commented
trigger ti1

2023-02-10 08:49 UTC, GoelPratyush99 commented
trigger ti2

2023-02-10 08:49 UTC, GoelPratyush99 commented
trigger ti3

2023-02-10 08:49 UTC, GoelPratyush99 commented
trigger ti4

2023-02-10 09:43 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-10 10:14 UTC, GoelPratyush99 commented
trigger ft1

2023-02-10 10:14 UTC, GoelPratyush99 commented
trigger ft2

2023-02-10 10:50 UTC, achyuth-harness approved these changes
> Reviewed 2 of 4 files at r2, 1 of 3 files at r6, 3 of 7 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-20 10:57 UTC, abosii-harness approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-21 05:45 UTC, abhinavsingh1196 approved these changes
> Reviewed 2 of 4 files at r2, 1 of 3 files at r6, 2 of 7 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43535)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-21 05:49 UTC, merged