feat: [CDS-52151]: Add AWS lambda infrastructure, register the step a…
harness/harness-core pull request #43647
Opened 2023-02-08 00:26 UTC by rohitk-h

…dd aws lamba client

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-08 11:44 UTC, mdmilic approved these changes
Approving delegate codeowned files. 
@rohitk-h please add describe your changes and testing done in the PR description. I see the boxes are ticked, but nothing is added to the PR description. 

> Reviewed 2 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647#-:-NNkp8nQ4Oc7YtaWUm4Y:b-a91b2c)* status: 25 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-08 19:16 UTC, rohitk-h commented
Updated. Thanks!





<!-- Sent from Reviewable.io -->

2023-02-09 06:00 UTC, rohitk-h commented
trigger ft1

2023-02-10 05:21 UTC, sainath-b commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java
> +    JSONObject jsonObject = (JSONObject) parser.parse(awsLambdaDeployManifestContent);
We need to support yaml also in NG. @rohitk-h please refer to ecs code to see how we are doing.

2023-02-10 05:23 UTC, sainath-b requested changes
Added some comments. Please address.

2023-02-10 05:26 UTC, rohitk-h commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/43647#-NNiPdJK6Nuj9nhQrKGC-r3-63:-NNtmLEN9WUzPlgB7NH2:b-k57gt2) ([raw file](https://github.com/harness/harness-core/blob/36c9cbf32a44baddbe243ad3f62bf45aa8a23522/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java#L63)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

We need to support yaml also in NG. @rohitk-h please refer to ecs code to see how we are doing.
</blockquote></details>

Can I take care of this in a follow up PR? I have one going out with changes around this area. 


<!-- Sent from Reviewable.io -->

2023-02-10 05:44 UTC, alluvamsi-harness submitted a review, later dismissed

2023-02-10 05:52 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 17 of 23 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647)* status: 23 file(s) to review. 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-10 05:58 UTC, piyush-bhuwalka commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/AwsLambdaInfrastructure.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43647#-NNttky83Mb1v1m6iArx:-NNttky83Mb1v1m6iAry:b-gh6ry6) ([raw file](https://github.com/harness/harness-core/blob/36c9cbf32a44baddbe243ad3f62bf45aa8a23522/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/AwsLambdaInfrastructure.java#L65)):*
> ```Java
>   @Override
>   public InfraMapping getInfraMapping() {
>     return ServerlessAwsLambdaInfraMapping.builder()
> ```

Should be different infra mapping


<!-- Sent from Reviewable.io -->

2023-02-10 06:00 UTC, piyush-bhuwalka commented
*[`960-api-services/src/main/java/io/harness/aws/lambda/AwsLambdaClientImpl.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/43647#-NNtu9XC9TyYRQPy7TZk:-NNtu9XC9TyYRQPy7TZl:bcvedlp) ([raw file](https://github.com/harness/harness-core/blob/36c9cbf32a44baddbe243ad3f62bf45aa8a23522/960-api-services/src/main/java/io/harness/aws/lambda/AwsLambdaClientImpl.java#L54)):*
> ```Java
> 
>       WaiterResponse<GetFunctionResponse> waiterResponse = waiter.waitUntilFunctionExists(getFunctionRequest);
>       if (waiterResponse.matched().response().isPresent()) {
> ```

We have implementation of this done in Google Functions. If possible lets keep it same


<!-- Sent from Reviewable.io -->

2023-02-10 06:07 UTC, rohitk-h reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647)* status: 24 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/AwsLambdaInfrastructure.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43647#-NNttky83Mb1v1m6iArx:-NNtvcul9-YZ5IKLf3ki:b-dw8hqc) ([raw file](https://github.com/harness/harness-core/blob/36c9cbf32a44baddbe243ad3f62bf45aa8a23522/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/AwsLambdaInfrastructure.java#L65)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Should be different infra mapping
</blockquote></details>

good catch, updated. 
___
*[`960-api-services/src/main/java/io/harness/aws/lambda/AwsLambdaClientImpl.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/43647#-NNtu9XC9TyYRQPy7TZk:-NNtvezj420TUy5mONdM:b-426sja) ([raw file](https://github.com/harness/harness-core/blob/36c9cbf32a44baddbe243ad3f62bf45aa8a23522/960-api-services/src/main/java/io/harness/aws/lambda/AwsLambdaClientImpl.java#L54)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

We have implementation of this done in Google Functions. If possible lets keep it same
</blockquote></details>

Sure, will update this in the follow-up. 


<!-- Sent from Reviewable.io -->

2023-02-10 06:13 UTC, piyush-bhuwalka approved these changes
> Reviewed 10 of 23 files at r1, 2 of 4 files at r2, 3 of 4 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-10 06:30 UTC, yogesh-chauhan approved these changes
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-10 06:42 UTC, sainath-b approved these changes
> Reviewed 10 of 23 files at r1, 2 of 4 files at r2, 3 of 4 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/43647#-NNiPdJK6Nuj9nhQrKGC-r3-63:-NNu2jetCZZ35JBSBlSI:bb74ce2) ([raw file](https://github.com/harness/harness-core/blob/36c9cbf32a44baddbe243ad3f62bf45aa8a23522/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java#L63)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Can I take care of this in a follow up PR? I have one going out with changes around this area. 
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2023-02-10 06:42 UTC, sainath-b approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-10 09:27 UTC, PragyeshMishra01 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java
> +        jsonReader.readValue(awsLambdaDeployManifestContent, CreateFunctionRequest.class);
this may not work for yaml, we should use yamlFactory.

2023-02-10 09:29 UTC, PragyeshMishra01 approved these changes

2023-02-10 10:09 UTC, mdmilic approved these changes
> Reviewed 1 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43647)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-10 10:57 UTC, merged

2023-02-10 10:58 UTC, piyush-bhuwalka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java
> +        jsonReader.readValue(awsLambdaDeployManifestContent, CreateFunctionRequest.class);
@rohitk-h please take this into consideration in follow up PR

2023-02-10 17:36 UTC, rohitk-h commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java` line 47 at r4](https://reviewable.io/reviews/harness/harness-core/43647#-NNiPdJK6Nuj9nhQrKGC-r4-47:-NNwOWMgDGeXYsHFDlUE:b-cys64w) ([raw file](https://github.com/harness/harness-core/blob/e47fcf41ae3f67d11277e25021200d808db247e3/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java#L47)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

@rohitk-h please take this into consideration in follow up PR
</blockquote></details>

Yes, I will update it in the follow-up PR. Thanks!


<!-- Sent from Reviewable.io -->