Feat/cds 46180
harness/harness-core pull request #43649
Opened 2023-02-08 05:24 UTC by shivamnegi94

## Describe your changes
Added the support for Bamboo Connector and Artifact source

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-09 11:08 UTC, shivamnegi94 commented
trigger ti1, ti2

2023-02-15 07:21 UTC, yogesh-chauhan requested changes

2023-02-15 07:21 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +}
can we remove changes from 840-template-service module ?

2023-02-16 04:20 UTC, shivamnegi94 commented on 840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +}
Yes

2023-02-16 08:06 UTC, shivamnegi94 commented
trigger ft2

2023-02-16 10:17 UTC, yogesh-chauhan commented
*[`260-delegate/config-delegate.yml` line 19 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOi_z_6WGR5aZC7op6:-NOOi_z_6WGR5aZC7op7:b-hi4889) ([raw file](https://github.com/harness/harness-core/blob/0cb7fbed8e828530413692f674c896aaf589229a/260-delegate/config-delegate.yml#L19)):*
> ```YAML
> clientToolsDownloadDisabled: false
> installClientToolsInBackground: true
> isLocalNgDelegate: true
> ```

is this change intentional ?


<!-- Sent from Reviewable.io -->

2023-02-16 10:19 UTC, yogesh-chauhan commented
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/bamboo/BambooAuthCredentialsDTO.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOj5BoCegJShqgfWDD:-NOOj5BoCegJShqgfWDE:b-4gq9v4) ([raw file](https://github.com/harness/harness-core/blob/0cb7fbed8e828530413692f674c896aaf589229a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/bamboo/BambooAuthCredentialsDTO.java#L20)):*
> ```Java
> @OwnedBy(CDC)
> @Schema(
>     name = "BambooAuthCredentialsDTO", description = "This contains details of credentials for Jenkins Authentication")
> ```

description is not correct


<!-- Sent from Reviewable.io -->

2023-02-16 10:20 UTC, yogesh-chauhan commented
*[`970-ng-commons/src/main/java/io/harness/beans/EntityReference.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOjI-t7L9HaP69Snan:-NOOjI-t7L9HaP69Snao:b-wj8kbx) ([raw file](https://github.com/harness/harness-core/blob/8f1879ac36b2d09ae30b1d6bd43185cf0c76f703/970-ng-commons/src/main/java/io/harness/beans/EntityReference.java#L20)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @ApiModel(value = "EntityReference",
>     subTypes = {IdentifierRef.class, InputSetReference.class, NGTemplateReference.class}, discriminator = "type")
> ```

why are we removing this ?


<!-- Sent from Reviewable.io -->

2023-02-16 10:21 UTC, yogesh-chauhan commented
*[`970-ng-commons/src/main/java/io/harness/ng/core/deserializer/EntityDetailDeserializer.java` line 46 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOjSiS7nJXl6AdSHTE:-NOOjSiS7nJXl6AdSHTF:b-y1glgs) ([raw file](https://github.com/harness/harness-core/blob/8f1879ac36b2d09ae30b1d6bd43185cf0c76f703/970-ng-commons/src/main/java/io/harness/ng/core/deserializer/EntityDetailDeserializer.java#L46)):*
> ```Java
>     if (type == EntityType.INPUT_SETS) {
>       reference = mapper.readValue(entityRefNode.toString(), InputSetReference.class);
>     } else if (type == EntityType.TEMPLATE) {
> ```

why this change ?


<!-- Sent from Reviewable.io -->

2023-02-16 10:22 UTC, yogesh-chauhan commented
*[`980-commons/src/main/java/io/harness/exception/runtime/BambooServerRuntimeException.java` line 15 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOjbS9BI6asayqUe6g:-NOOjbS9BI6asayqUe6h:b-9zrt4g) ([raw file](https://github.com/harness/harness-core/blob/0cb7fbed8e828530413692f674c896aaf589229a/980-commons/src/main/java/io/harness/exception/runtime/BambooServerRuntimeException.java#L15)):*
> ```Java
>   private String message;
>   Throwable cause;
>   ErrorCode code = ErrorCode.INVALID_CREDENTIAL;
> ```

why is the default value of the code Invalid credential ? 


<!-- Sent from Reviewable.io -->

2023-02-16 10:22 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 11 files at r4, 84 of 88 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 91 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-16 10:36 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 91 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-ng-commons/src/main/java/io/harness/beans/EntityReference.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOjI-t7L9HaP69Snan:-NOOlG071cT6Mtc2uO8_:b280b0i) ([raw file](https://github.com/harness/harness-core/blob/8f1879ac36b2d09ae30b1d6bd43185cf0c76f703/970-ng-commons/src/main/java/io/harness/beans/EntityReference.java#L20)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why are we removing this ?
</blockquote></details>

It is not removed, rebasing the FF branch with develop branch reformat file.



_Code quote:_
```Java
EntityReference
```
___
*[`970-ng-commons/src/main/java/io/harness/ng/core/deserializer/EntityDetailDeserializer.java` line 46 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOjSiS7nJXl6AdSHTE:-NOOlu4x1BhEBMFsiuhl:b72r1uh) ([raw file](https://github.com/harness/harness-core/blob/8f1879ac36b2d09ae30b1d6bd43185cf0c76f703/970-ng-commons/src/main/java/io/harness/ng/core/deserializer/EntityDetailDeserializer.java#L46)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why this change ?
</blockquote></details>

Not sure how rebase the code impacting these changes
___
*[`980-commons/src/main/java/io/harness/exception/runtime/BambooServerRuntimeException.java` line 15 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOjbS9BI6asayqUe6g:-NOOmfZ52SN8g8Myoo_j:b-4hclgi) ([raw file](https://github.com/harness/harness-core/blob/0cb7fbed8e828530413692f674c896aaf589229a/980-commons/src/main/java/io/harness/exception/runtime/BambooServerRuntimeException.java#L15)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why is the default value of the code Invalid credential ? 
</blockquote></details>

It is currently used only in Connector validation, other places we are overriding it


<!-- Sent from Reviewable.io -->

2023-02-16 10:50 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 91 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/config-delegate.yml` line 19 at r7](https://reviewable.io/reviews/harness/harness-core/43649#-NOOi_z_6WGR5aZC7op6:-NOOq4RL-UzvBfT-oWXs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0cb7fbed8e828530413692f674c896aaf589229a/260-delegate/config-delegate.yml#L19)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this change intentional ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-16 11:42 UTC, puthrayaharness requested changes

2023-02-16 11:42 UTC, puthrayaharness commented on 970-ng-commons/src/main/java/io/harness/beans/EntityReference.java
> -@ApiModel(value = "EntityReference",
Why change here?

2023-02-16 11:42 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/nexusartifact/BambooArtifactConfig.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) @Wither ParameterField<String> build;
Why call this build? Why not call it tag & tagRegex like we call it in other places.

2023-02-16 12:23 UTC, shivamnegi94 commented on 970-ng-commons/src/main/java/io/harness/beans/EntityReference.java
> -@ApiModel(value = "EntityReference",
Rebase had made code format changes

2023-02-16 12:24 UTC, shivamnegi94 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/nexusartifact/BambooArtifactConfig.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) @Wither ParameterField<String> build;
This is similar to Jenkins and we used builds in Jenkins. I have check with shylaja also so she asked to use build as tag is not used in non docker type

2023-02-17 07:11 UTC, shivamnegi94 commented
trigger ti0

2023-02-20 19:54 UTC, sribalij commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java
> +    IdentifierRef connectorRef =
Resolve `bambooConnectorIdentifier` if it is an expression?

2023-02-20 20:05 UTC, sribalij commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactDelegateResponse.java
> +  /** Jenkins Job build number */
Change comments to Bamboo instead of Jenkins

2023-02-20 20:08 UTC, sribalij commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/BambooArtifactOutcome.java
> +  /** Jenkins connector. */
Change names to Bamboo

2023-02-20 20:09 UTC, sribalij commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/outcome/BambooArtifactOutcome.java
> +  /** Jenkins Artifact Metadata.*/
Same here

2023-02-21 13:38 UTC, puthrayaharness approved these changes

2023-02-21 13:39 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 3 of 11 files at r4, 71 of 88 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, 2 of 2 files at r9, 5 of 7 files at r10, 1 of 1 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 16 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 01:46 UTC, sribalij approved these changes

2023-02-22 06:21 UTC, vtxorxwitty approved these changes
> Reviewed 3 of 11 files at r4, 68 of 88 files at r6, 2 of 3 files at r8, 1 of 2 files at r9, 4 of 7 files at r10, 4 of 5 files at r12, 7 of 9 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 06:41 UTC, puthrayaharness submitted a review, later dismissed
> Reviewed 7 of 9 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 1 change requests. 4. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 07:38 UTC, sribalij approved these changes
> Reviewed 3 of 11 files at r4, 68 of 88 files at r6, 2 of 3 files at r8, 1 of 2 files at r9, 4 of 7 files at r10, 4 of 5 files at r12, 7 of 9 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 1 change requests. 4. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 11:09 UTC, mdmilic submitted a review, later dismissed
Approving only delegate owned files

> Reviewed 3 of 11 files at r4, 6 of 88 files at r6, 1 of 3 files at r8, 1 of 2 files at r9, 1 of 5 files at r12, 1 of 2 files at r15, 6 of 11 files at r16.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649#-:-NOsnoZ949kTkSrLFn9w:bwc08oq)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-ng-commons/src/main/java/io/harness/common/NGTaskType.java` line 32 at r16](https://reviewable.io/reviews/harness/harness-core/43649#-NOsnNIKBdfyopLw2shc:-NOsnNILEZFjHG6lC6na:b-ov8ka8) ([raw file](https://github.com/harness/harness-core/blob/ceb744d608be5d4f2a9b2e3937f777499089cb8b/970-ng-commons/src/main/java/io/harness/common/NGTaskType.java#L32)):*
> ```Java
>   JENKINS_ARTIFACT_TASK_NG,
> 
>   BAMBOO_ARTIFACT_TASK_NG,
> ```

Don't know what this enum is, but sounds like something being sent to delegate (and Kryo serialized). If so, you can't put new values in the middle, they have to go at the end to be backwards compatible.


<!-- Sent from Reviewable.io -->

2023-02-23 03:12 UTC, shivamnegi94 commented
trigger messagecheck

2023-02-23 03:13 UTC, shivamnegi94 commented
trigger messagecheck

2023-02-23 04:19 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 3 files at r8, 1 of 2 files at r9, 4 of 7 files at r10, 4 of 5 files at r12, 2 of 9 files at r14, 1 of 2 files at r15, 4 of 11 files at r16, 8 of 8 files at r17.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-23 04:20 UTC, yogesh-chauhan approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649)* status: 10 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-23 04:21 UTC, utkarshchoubey-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 11 files at r4, 62 of 88 files at r6, 2 of 3 files at r8, 1 of 2 files at r9, 4 of 7 files at r10, 4 of 5 files at r12, 2 of 9 files at r14, 1 of 2 files at r15, 4 of 11 files at r16, 8 of 8 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649#-:-NOwVELXEb6GVumblFqx:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-23 04:22 UTC, utkarshchoubey-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43649#-:-NOwVSJFAxkLb8L2qNB0:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-23 04:40 UTC, merged