feat: [CDS-52579]: Aws Lambda Instance Sync NG Changes
harness/harness-core pull request #43735
Opened 2023-02-09 08:30 UTC by piyush-bhuwalka

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-09 21:30 UTC, rohitk-h requested changes
> Reviewed 63 of 81 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 81 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/AwsLambdaInstanceInfo.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/43735#-NNs0M_s4y6vawQCF4pU:-NNs0M_s4y6vawQCF4pV:b-f768k7) ([raw file](https://github.com/harness/harness-core/blob/8e03593603ee80a6e2458b9c361620ed057ae4c5/126-instance/src/main/java/io/harness/entities/instanceinfo/AwsLambdaInstanceInfo.java#L28)):*
> ```Java
>   @NotNull private String version;
>   @NotNull private String functionName;
>   @NotNull private String project;
> ```

Lambda doesn't have project construct, can we remove? 
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AwsLambdaInstanceSyncPerpetualTaskExecutorNg.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/43735#-NNs1WfG1a_ExlMD65AJ:-NNs1WfG1a_ExlMD65AK:b-drn39t) ([raw file](https://github.com/harness/harness-core/blob/8e03593603ee80a6e2458b9c361620ed057ae4c5/260-delegate/src/main/java/io/harness/perpetualtask/AwsLambdaInstanceSyncPerpetualTaskExecutorNg.java#L73)):*
> ```Java
>                                                        .collect(Collectors.toList());
> 
>     log.info("Aws Lambda Function sync nInstances: {}, task id: {}",
> ```

typo: instances
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AwsLambdaInstanceSyncPerpetualTaskExecutorNg.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/43735#-NNs1_bw-dNsst49iQA0:-NNs1_bw-dNsst49iQA1:bk9qjap) ([raw file](https://github.com/harness/harness-core/blob/8e03593603ee80a6e2458b9c361620ed057ae4c5/260-delegate/src/main/java/io/harness/perpetualtask/AwsLambdaInstanceSyncPerpetualTaskExecutorNg.java#L85)):*
> ```Java
>       return awsLambdaTaskHelperBase.getAwsLambdaServerInstanceInfo(deploymentReleaseData);
>     } catch (Exception ex) {
>       log.warn("Unable to get google cloud function server instance", ex);
> ```

Update logger to aws lambda
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/43735#-NNs2ARHA_FzFzTTNmRH:-NNs2ARHA_FzFzTTNmRI:b-brafm4) ([raw file](https://github.com/harness/harness-core/blob/8e03593603ee80a6e2458b9c361620ed057ae4c5/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTaskHelper.java#L28)):*
> ```Java
> import com.amazonaws.services.ecs.model.ClusterNotFoundException;
> import com.amazonaws.services.ecs.model.ServiceNotFoundException;
> import com.amazonaws.services.lambda.AWSLambdaClient;
> ```

This is using the v1 version of the aws library, for v2 version the package is `software.amazon.awssdk.services.lambda.LambdaClient`
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaFunctionWithActiveVersions.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/43735#-NNs32Nx3wU-DWANIkJo:-NNs32Nx3wU-DWANIkJp:b-2f41k7) ([raw file](https://github.com/harness/harness-core/blob/8e03593603ee80a6e2458b9c361620ed057ae4c5/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaFunctionWithActiveVersions.java#L10)):*
> ```Java
> package io.harness.delegate.task.aws.lambda;
> 
> import com.amazonaws.services.lambda.model.AliasConfiguration;
> ```

Same comment as above, we should use v2 aws lambda version


<!-- Sent from Reviewable.io -->

2023-02-28 19:14 UTC, rohitk-h commented
*[`260-delegate/config-delegate.yml` line 19 at r17](https://reviewable.io/reviews/harness/harness-core/43735#-NPORXSv06DT2UGXwBl0:-NPORXSv06DT2UGXwBl1:bsck18e) ([raw file](https://github.com/harness/harness-core/blob/701219e55b76e9b90b59429b5e99bb1ed8f54831/260-delegate/config-delegate.yml#L19)):*
> ```YAML
> clientToolsDownloadDisabled: false
> installClientToolsInBackground: true
> isLocalNgDelegate: true
> ```

This file shouldn't be committed


<!-- Sent from Reviewable.io -->

2023-02-28 19:14 UTC, rohitk-h reviewed
> Reviewed 3 of 70 files at r4, 21 of 49 files at r12, 14 of 75 files at r13, 50 of 68 files at r14, 30 of 30 files at r16, 6 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 133 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-28 19:44 UTC, rohitk-h reviewed
> Reviewed 2 of 2 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 133 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-28 22:50 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 133 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-01 05:47 UTC, piyush-bhuwalka commented
trigger ut3

2023-03-01 07:47 UTC, piyush-bhuwalka commented
trigger ut5

2023-03-01 07:47 UTC, piyush-bhuwalka commented
trigger ut6

2023-03-01 07:47 UTC, piyush-bhuwalka commented
trigger ut7

2023-03-01 07:47 UTC, piyush-bhuwalka commented
trigger ut8

2023-03-01 07:47 UTC, piyush-bhuwalka commented
trigger ut9

2023-03-01 08:44 UTC, piyush-bhuwalka commented
trigger feature-build

2023-03-01 08:52 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 133 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-01 16:37 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 133 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-01 19:45 UTC, piyush-bhuwalka commented
trigger feature-build

2023-03-01 19:49 UTC, rohitk-h approved these changes
> Reviewed 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 133 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-01 20:24 UTC, rohitk-h submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 133 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-01 20:42 UTC, alluvamsi-harness requested changes

2023-03-01 20:42 UTC, alluvamsi-harness commented on 126-instance/src/main/java/io/harness/entities/instanceinfo/AwsLambdaInstanceInfo.java
> +  @NotNull private String project;
can we remove project?

2023-03-01 22:19 UTC, rohitk-h commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaTaskHelper.java` line 266 at r17](https://reviewable.io/reviews/harness/harness-core/43735#-NPUFMdV6YIYEJQbdd3z:-NPUFMdV6YIYEJQbdd4-:b-8ej4qk) ([raw file](https://github.com/harness/harness-core/blob/701219e55b76e9b90b59429b5e99bb1ed8f54831/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaTaskHelper.java#L266)):*
> ```Java
>     }
> 
>     UpdateFunctionCodeResponse updateFunctionCodeResponseDryRun =
> ```

Is this intentional? We needed this check to ensure we only update if there is a change


<!-- Sent from Reviewable.io -->

2023-03-02 04:04 UTC, sainath-b commented on 126-instance/src/main/java/io/harness/entities/instanceinfo/AwsLambdaInstanceInfo.java
> +  @NotNull private String project;
@piyush-bhuwalka please remove project

2023-03-02 04:22 UTC, sainath-b commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/info/AwsLambdaServerInstanceInfo.java
> +  // todo
is it still in todo state?

2023-03-02 04:23 UTC, sainath-b requested changes
Please address comments

2023-03-02 04:25 UTC, piyush-bhuwalka commented on 126-instance/src/main/java/io/harness/entities/instanceinfo/AwsLambdaInstanceInfo.java
> +  @NotNull private String project;
Done

2023-03-02 04:28 UTC, piyush-bhuwalka commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/info/AwsLambdaServerInstanceInfo.java
> +  // todo
Removed , we dont need it

2023-03-02 04:29 UTC, piyush-bhuwalka commented
trigger feature-build

2023-03-02 04:30 UTC, piyush-bhuwalka commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaTaskHelper.java` line 266 at r17](https://reviewable.io/reviews/harness/harness-core/43735#-NPUFMdV6YIYEJQbdd3z:-NPVVM5b5hI3JOaf23mJ:b-3a4h1m) ([raw file](https://github.com/harness/harness-core/blob/701219e55b76e9b90b59429b5e99bb1ed8f54831/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaTaskHelper.java#L266)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Is this intentional? We needed this check to ensure we only update if there is a change
</blockquote></details>

Updated again


<!-- Sent from Reviewable.io -->

2023-03-02 04:33 UTC, piyush-bhuwalka commented
trigger messagecheck

2023-03-02 04:36 UTC, sainath-b approved these changes

2023-03-02 04:37 UTC, sainath-b approved these changes
> Reviewed 15 of 82 files at r2, 3 of 70 files at r4, 20 of 49 files at r12, 14 of 75 files at r13, 50 of 68 files at r14, 20 of 30 files at r16, 4 of 7 files at r17, 1 of 2 files at r18, 1 of 1 files at r19, 2 of 3 files at r20, 2 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-02 04:38 UTC, sainath-b approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-02 04:45 UTC, piyush-bhuwalka commented
trigger messagecheck

2023-03-02 04:47 UTC, alluvamsi-harness reviewed
> Reviewed 15 of 82 files at r2, 3 of 70 files at r4, 20 of 49 files at r12, 14 of 75 files at r13, 50 of 68 files at r14, 20 of 30 files at r16, 4 of 7 files at r17, 1 of 2 files at r18, 1 of 1 files at r19, 2 of 3 files at r20, 2 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-02 04:48 UTC, alluvamsi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: 1. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-02 05:10 UTC, raghuAtWings approved these changes
> Reviewed 15 of 82 files at r2, 3 of 70 files at r4, 20 of 49 files at r12, 14 of 75 files at r13, 50 of 68 files at r14, 20 of 30 files at r16, 4 of 7 files at r17, 1 of 2 files at r18, 1 of 1 files at r19, 2 of 3 files at r20, 2 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43735)* status: Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-02 05:52 UTC, merged