feat: [CDS-52157]: Support for Bitbucket with GitOps CreatePR and Mer…
harness/harness-core pull request #43841
Opened 2023-02-11 00:42 UTC by meenaravichandran1

## Describe your changes
Support for bitbucket connectors in UpdateReleaseRepo and Merge PR steps.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-13 16:16 UTC, meenaravichandran1 commented
trigger feature-build

2023-02-13 20:46 UTC, meenaravichandran1 commented
trigger feature-build

2023-02-13 21:44 UTC, anshul-harness requested changes
> Reviewed 2 of 6 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 375 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBg1kT7GegLQl2eqza:-NOBg1kT7GegLQl2eqzb:bxfl43h) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L375)):*
> ```Java
>     } else {
>       String domain = GitClientHelper.getGitSCM(url);
>       return "https://" + domain + "/projects/" + workspace.toUpperCase() + "/repos/" + repoSlug + "/pull-requests/"
> ```

Will it be always "https" ?
Should we not get this info from the URL entered by the user?



_Code quote:_
```Java
https:
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBgzkU5AHJ5ULS_LZh:-NOBgzkU5AHJ5ULS_LZi:b-43j0i) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L89)):*
> ```Java
>     GitApiTaskResponseBuilder responseBuilder = GitApiTaskResponse.builder();
>     if (mergePRResponse != null) {
>       if ((boolean) getValue(mergePRResponse, "merged")) {
> ```

Create constants for these strings
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBh_Fq4QCMxAmxiBg-:-NOBh_Fq4QCMxAmxiBg0:bv2hqyu) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L93)):*
> ```Java
>         responseBuilder.commandExecutionStatus(CommandExecutionStatus.SUCCESS)
>             .gitApiResult(GitApiMergePRTaskResponse.builder()
>                               .sha(mergeCommitSha == null ? null : String.valueOf(mergeCommitSha))
> ```

When would the "mergeCommitSha" be null but the response is valid?



_Code quote:_
```Java
mergeCommitSha == null ? null
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 124 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBgMXZ78HwHbx2nOVT:-NOBgMXZ78HwHbx2nOVU:b-e3cjju) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L124)):*
> ```Java
>     }
>     String domain = GitClientHelper.getGitSCM(url);
>     return "https://" + domain + PATH_SEPARATOR;
> ```

"https" ---> Same as above
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 136 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBgh7J8xJEZKcDw9oq:-NOBgh7J8xJEZKcDw9or:bjjkbga) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L136)):*
> ```Java
>       throw new InvalidRequestException(format(USERNAME_ERR, identifier));
>     }
>     throw new InvalidRequestException(format(USERNAME_ERR, identifier));
> ```

Do we throw exception when the Authtype is not "USERNAME_AND_TOKEN"?



_Code quote:_
```Java
  throw new InvalidRequestException(format(USERNAME_ERR, identifier));
```
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiGSx8p0GHGGBowun:-NOBiGSx8p0GHGGBowuo:b-i4jzk8) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L108)):*
> ```Java
>           if (!isBranchDeleted) {
>             log.error(
>                 "Error encountered when deleting source branch {} of the pull request {}. URL {}", ref, prNumber, url);
> ```

We should fail otherwise we will silently ignore this errror
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiVPyCMAhbsCieiIR:-NOBiVPyCMAhbsCieiIS:bm3ypi9) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L134)):*
> ```Java
>     } catch (Exception e) {
>       log.error("Failed to get error message from merge response. Error {}", e.getMessage());
>       return "Failed to get error message from merge response";
> ```

Let's return the actual error code to user also



_Code quote:_
```Java
Failed to get error message from merge response
```
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 145 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiZrHDYILwxLQ5Gt-:-NOBiZrHDYILwxLQ5Gt0:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L145)):*
> ```Java
>     } catch (Exception e) {
>       log.error("Failed to get error message from merge response. Error {}", e.getMessage());
>       return "Failed to get error message from merge response";
> ```

Same as above
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBhz0H82_H5KRtVeWI:-NOBhz0H82_H5KRtVeWJ:bze5gyx) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L186)):*
> ```Java
> 
>   private Object getSaaSMergeCommit(Response<Object> mergePRResponse) {
>     return ((LinkedHashMap) ((LinkedHashMap) mergePRResponse.body()).get("merge_commit")).get("hash");
> ```

Can we create constants for these strings?
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 193 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBipKg-VUk0pFOvALg:-NOBipKg-VUk0pFOvALh:bg1o27) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L193)):*
> ```Java
>     Map<String, Object> parameters = new HashMap<>();
>     parameters.put("name", ref);
>     parameters.put("dryRun", false);
> ```

Is "dryRun" a property in the Bitbucket API? What does it do?


<!-- Sent from Reviewable.io -->

2023-02-13 21:45 UTC, anshul-harness reviewed
@meenaravichandran1: I did not see many tests. Please add UTs.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841#-:-NOBj5BL9Z8gHjaf47Ug:b-vj114)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-13 22:13 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 375 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBg1kT7GegLQl2eqza:-NOBjz_H2rvvWmhm8vZm:btmytar) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L375)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Will it be always "https" ?
Should we not get this info from the URL entered by the user?
</blockquote></details>

I initially tried to get url from the connector using URL class. But in case of ssh connector, it failed.
In case it is ssh/https, I will default it to https, else http. Is that the expected behavior?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBh_Fq4QCMxAmxiBg-:-NOBkiRO8VuSiJxsBxx4:bk7dzjk) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L93)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

When would the "mergeCommitSha" be null but the response is valid?
</blockquote></details>

have seen some weird behaviours with Bitbucket APIs specifically, one example is this https://harness.slack.com/archives/C01JMN5P7EX/p1676006277028399?thread_ts=1675825487.643279&cid=C01JMN5P7EX

Have added the null check for graceful handling when the sha is null.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 136 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBgh7J8xJEZKcDw9oq:-NOBlM8C0gr5V9pUQ6ft:bckfiw7) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L136)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Do we throw exception when the Authtype is not "USERNAME_AND_TOKEN"?
</blockquote></details>

yes, currently the only supported auth type is username and token
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiGSx8p0GHGGBowun:-NOBlTJB6-mGN1DP1bUU:b5mdsoz) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L108)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

We should fail otherwise we will silently ignore this errror
</blockquote></details>

we have this behaviour for github connectors as well. Also, what if this err happens but the branch is merged?
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiVPyCMAhbsCieiIR:-NOBm6kpE99pYvjpb67Z:b-58lo4h) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L134)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Let's return the actual error code to user also
</blockquote></details>

Can we get the error code for exceptions?
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBhz0H82_H5KRtVeWI:-NOBpVnF-0M839cg-yLL:be7ii2) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L186)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Can we create constants for these strings?
</blockquote></details>

I have created constants only for repeated strings. Will create for others.
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 193 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBipKg-VUk0pFOvALg:-NOBn2eXAGVq9q-pkmeE:b5d232k) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L193)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Is "dryRun" a property in the Bitbucket API? What does it do?
</blockquote></details>

yes. There's not much info on the official site about this. Reference - https://docs.atlassian.com/bitbucket-server/rest/7.21.0/bitbucket-branch-rest.html#idm45555984542992.

I believe this would have the same meaning as other tools where dryRun - true will just simulate the action without actually doing it and when dryRun is false the action will be done.

I couldn't validate it with true now, because of the connector issue. But dryRun false is going to perform the delete operation.


<!-- Sent from Reviewable.io -->

2023-02-13 22:23 UTC, meenaravichandran1 reviewed
yes, have mentioned it in the PR description. It is in progress

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841#-:-NOBryQ54IrYdtOXzEyL:b-hzvsxj)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-13 23:03 UTC, anshul-harness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 375 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBg1kT7GegLQl2eqza:-NOC018s22S5TOB-rUmX:b1fsqq3) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L375)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

I initially tried to get url from the connector using URL class. But in case of ssh connector, it failed.
In case it is ssh/https, I will default it to https, else http. Is that the expected behavior?
</blockquote></details>

What are we doing in Gitlab or Github or Azure?


<!-- Sent from Reviewable.io -->

2023-02-13 23:12 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 375 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBg1kT7GegLQl2eqza:-NOC2D_O0MQXokTmUeuv:b-xr7mt) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L375)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

What are we doing in Gitlab or Github or Azure?
</blockquote></details>

We have hardcoded the url as https. Hence I followed the same.


<!-- Sent from Reviewable.io -->

2023-02-13 23:13 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiVPyCMAhbsCieiIR:-NOC2TI_7zcgqWgs5LQy:b-228zj9) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L134)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

Can we get the error code for exceptions?
</blockquote></details>

Have made the return code as 500 as it is an unknown exception in the server.


<!-- Sent from Reviewable.io -->

2023-02-13 23:24 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 375 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBg1kT7GegLQl2eqza:-NOC4mLXE8bTRUpIZ1bF:br4bjnf) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L375)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

We have hardcoded the url as https. Hence I followed the same.
</blockquote></details>

reference: https://github.com/harness/harness-core/blob/ec4fc86a66e6eca95b310ba213bb86af57664846/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java#L179,
https://github.com/harness/harness-core/blob/ec4fc86a66e6eca95b310ba213bb86af57664846/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L109


<!-- Sent from Reviewable.io -->

2023-02-13 23:25 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 145 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiZrHDYILwxLQ5Gt-:-NOC5JiY7kxCSKe7e00M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L145)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-13 23:26 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBgzkU5AHJ5ULS_LZh:-NOC5POQ1ndmW5pYMOne:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L89)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Create constants for these strings
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-13 23:28 UTC, anshul-harness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBh_Fq4QCMxAmxiBg-:-NOC4tFgBy-VORJMG_ET:b-xnzybx) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L93)):*
> https://harness.slack.com/archives/C01JMN5P7EX/p1676006277028399?thread_ts=1675825487.643279&cid=C01JMN5P7EX
I am assuming it's happening for On-prem only. IMO, we should remove this NULL check and log it when this happens. This issue could be our setup only.


<!-- Sent from Reviewable.io -->

2023-02-13 23:30 UTC, anshul-harness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 136 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBgh7J8xJEZKcDw9oq:-NOC5v7H61luYgTxijfC:b2xh8x7) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L136)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

yes, currently the only supported auth type is username and token
</blockquote></details>

Got it. Just checked that API Authentication for BitBucket has Username also


<!-- Sent from Reviewable.io -->

2023-02-13 23:31 UTC, anshul-harness commented
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiGSx8p0GHGGBowun:-NOC6NApAhBKQYRUc9Wi:b9lit0p) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L108)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

we have this behaviour for github connectors as well. Also, what if this err happens but the branch is merged?
</blockquote></details>

We should say that the branch was merged but deleting the branch failed.


<!-- Sent from Reviewable.io -->

2023-02-13 23:32 UTC, anshul-harness commented
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiVPyCMAhbsCieiIR:-NOC6jNs-72kL2B7yOvf:b2o3lg6) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L134)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

Have made the return code as 500 as it is an unknown exception in the server.
</blockquote></details>

Got it. 


<!-- Sent from Reviewable.io -->

2023-02-13 23:34 UTC, anshul-harness reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-13 23:37 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBh_Fq4QCMxAmxiBg-:-NOC7k8a0fl0kvxXk9Lt:bwi9vzt) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L93)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

> https://harness.slack.com/archives/C01JMN5P7EX/p1676006277028399?thread_ts=1675825487.643279&cid=C01JMN5P7EX
I am assuming it's happening for On-prem only. IMO, we should remove this NULL check and log it when this happens. This issue could be our setup only.

</blockquote></details>

ok, will change this.
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/43841#-NOBiGSx8p0GHGGBowun:-NOC7vRR8pxuu9FZtmLs:b-y2604t) ([raw file](https://github.com/harness/harness-core/blob/12edf9e1a802733670f56bf07cc34fdc11d62929/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L108)):*
> ok, will change this.


<!-- Sent from Reviewable.io -->

2023-02-14 01:02 UTC, anshul-harness reviewed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 221 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOCPWMkDy5REv3tvG0X:-NOCPWMkDy5REv3tvG0Y:b-s3x4r8) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L221)):*
> ```Java
>     } catch (Exception e) {
>       populateErrorInResponse(responseObj, e.getMessage(), HttpStatus.SC_INTERNAL_SERVER_ERROR);
>       log.error("Failed to delete ref for Bitbucket Server. URL {}, ref {}, Error {}",
> ```

nit: We can create a constant for this string also



_Code quote:_
```Java
Failed to delete ref for Bitbucket Server. URL {}, ref {}, Error {}
```


<!-- Sent from Reviewable.io -->

2023-02-14 01:03 UTC, anshul-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-14 15:53 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java` line 31 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOFcIkCAXmdreMWvr5g:-NOFcIkCAXmdreMWvr5h:b-6a238m) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java#L31)):*
> ```Java
> 
>   @POST("2.0/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge")
>   Call<Object> mergeSaaSPR(@Header("Authorization") String authorization, @Path("workspace") String workspace,
> ```

can we not define the structure here in response instead of parsing JsonObject?


<!-- Sent from Reviewable.io -->

2023-02-14 17:56 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 366 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG-vRK8ipgPXWSjP6y:-NOG-vRK8ipgPXWSjP6z:bhig9xj) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L366)):*
> ```Java
>   }
> 
>   private String getBitbucketPRLink(BitbucketConnectorDTO bitbucketConnectorDTO, int prNumber) {
> ```

nit, Can this be moved to BitBucketHelper? Others can also use this if they need.



_Code quote:_
```Java
itbucketPRLink(
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 109 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG1O4S1e1UkfkTmvMZ:-NOG1O4T9P6yUcjxfu4J:bzc1irz) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L109)):*
> ```Java
>     }
> 
>     if (getValue(mergePRResponse, BitbucketServiceImpl.ERROR) != null) {
> ```

Try not to infer. Send the status of the deletion operation in the response.



_Code quote:_
```Java
 BitbucketServiceImpl.MERGED)
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 115 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG1fzjCWRKaN4Hgruy:-NOG1fzjCWRKaN4Hgruz:b-uztzbh) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L115)):*
> ```Java
>           mergeCommitSha, repoSlug, prNumber, getValue(mergePRResponse, BitbucketServiceImpl.ERROR),
>           getValue(mergePRResponse, BitbucketServiceImpl.CODE)));
>     } else {
> ```

nit, can we remove else block? 

Everything is validated. So success is the only option left right?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 134 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG3S4F85eMG9x2r9oD:-NOG3S4F85eMG9x2r9oE:bdcw2lb) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L134)):*
> ```Java
>   }
> 
>   private static String getBitbucketApiURL(String url, boolean isSaaS) {
> ```

nit, can this be moved to BitBucketHelper?



_Code quote:_
```Java
  private static String getBitbucketApiURL(String url, boolean isSaaS) {
    if (isSaaS) {
      return BITBUCKET_CLOUD_API_URL;
    }
    String domain = GitClientHelper.getGitSCM(url);
    return HTTPS + domain + PATH_SEPARATOR;
  }
```


<!-- Sent from Reviewable.io -->

2023-02-14 18:02 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java` line 31 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOFcIkCAXmdreMWvr5g:-NOG4uTL5MK76Iay2r6-:bvpk99r) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java#L31)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

can we not define the structure here in response instead of parsing JsonObject?
</blockquote></details>

Look at JiraClient as an example


<!-- Sent from Reviewable.io -->

2023-02-15 07:53 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 366 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG-vRK8ipgPXWSjP6y:-NOJ2rYN3oswv7vccN4u:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L366)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, Can this be moved to BitBucketHelper? Others can also use this if they need.
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 109 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG1O4S1e1UkfkTmvMZ:-NOJ2wfJ7uQ5cDqFJ2uP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L109)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Try not to infer. Send the status of the deletion operation in the response.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 115 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG1fzjCWRKaN4Hgruy:-NOJ2yaa5OgJyll1SxPa:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L115)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, can we remove else block? 

Everything is validated. So success is the only option left right?
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java` line 134 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOG3S4F85eMG9x2r9oD:-NOJ3-JQ-8zz4rrsqFnC:b-7ag5mv) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/BitbucketApiClient.java#L134)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, can this be moved to BitBucketHelper?
</blockquote></details>

Used a common method
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java` line 31 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOFcIkCAXmdreMWvr5g:-NOJ3262747eZKFja2uZ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java#L31)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Look at JiraClient as an example
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-02-15 07:58 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java` line 31 at r5](https://reviewable.io/reviews/harness/harness-core/43841#-NOFcIkCAXmdreMWvr5g:-NOJ49KH-2nQL88bYCnW:b-2fdhg4) ([raw file](https://github.com/harness/harness-core/blob/ad0afdf358370ef232cc37c5e80ed690cc06bb65/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketRestClient.java#L31)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

Done
</blockquote></details>

The changes might not look similar to JiraClient though


<!-- Sent from Reviewable.io -->

2023-02-15 17:42 UTC, anshul-harness approved these changes
> Reviewed 10 of 12 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 241 at r7](https://reviewable.io/reviews/harness/harness-core/43841#-NOL1swD2YsrcSYHX88Z:-NOL1swD2YsrcSYHX88_:bff62g9) ([raw file](https://github.com/harness/harness-core/blob/f1ccdd9230b380b2224c18dde6a219679809e20c/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L241)):*
> ```Java
> 
>   @Override
>   public boolean deleteRef(BitbucketConfig bitbucketConfig, String authToken, String ref, String repoSlug, String org,
> ```

Should we call deleteRefInOnPrem as it's only called in the on-prem scenario?


<!-- Sent from Reviewable.io -->

2023-02-15 18:40 UTC, rohitk-h approved these changes
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3, 10 of 12 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 1 change requests. 3. unresolved discussions. 

___
*[`933-ci-commons/src/main/java/io/harness/git/helper/BitbucketHelper.java` line 26 at r7](https://reviewable.io/reviews/harness/harness-core/43841#-NOLLPJ4BjmJHGdx0q_v:-NOLLPJ4BjmJHGdx0q_w:b-5cvbbd) ([raw file](https://github.com/harness/harness-core/blob/f1ccdd9230b380b2224c18dde6a219679809e20c/933-ci-commons/src/main/java/io/harness/git/helper/BitbucketHelper.java#L26)):*
> ```Java
>   private static final String BITBUCKET_CLOUD_URL = "https://bitbucket.org/";
> 
>   private BitbucketHelper() {
> ```

nit: could use the @singleton annotation instead. 



_Code quote:_
```Java
private BitbucketHelper
```


<!-- Sent from Reviewable.io -->

2023-02-15 21:04 UTC, meenaravichandran1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 1 change requests. 4. unresolved discussions. 

___
*[`933-ci-commons/src/main/java/io/harness/git/helper/BitbucketHelper.java` line 26 at r7](https://reviewable.io/reviews/harness/harness-core/43841#-NOLLPJ4BjmJHGdx0q_v:-NOLt-An-hfhUMoaxosL:bsgdg8k) ([raw file](https://github.com/harness/harness-core/blob/f1ccdd9230b380b2224c18dde6a219679809e20c/933-ci-commons/src/main/java/io/harness/git/helper/BitbucketHelper.java#L26)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nit: could use the @singleton annotation instead. 
</blockquote></details>

Sure, will add this along with UTs PR. 
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java` line 241 at r7](https://reviewable.io/reviews/harness/harness-core/43841#-NOL1swD2YsrcSYHX88Z:-NOLs9XKA4AQq9Q1U1HJ:b-gk05wh) ([raw file](https://github.com/harness/harness-core/blob/f1ccdd9230b380b2224c18dde6a219679809e20c/960-api-services/src/main/java/io/harness/cistatus/service/bitbucket/BitbucketServiceImpl.java#L241)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Should we call deleteRefInOnPrem as it's only called in the on-prem scenario?
</blockquote></details>

the logic of routing to bitbucket cloud or server is present in the service impl based on the URL.
Will add a condition in this method to handle the SaaS and onprem flavours separately, (same as Merge PR) - with 2 methods deleteRefInOnPrem and deleteRefInSaaS.

Will add this along with UTs PR. 


<!-- Sent from Reviewable.io -->

2023-02-15 22:07 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-15 22:07 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: 1 change requests. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-16 03:41 UTC, vaibhav-si approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-16 03:44 UTC, vaibhav-si approved these changes
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3, 10 of 12 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43841)* status: :shipit: complete! ✓

___
*[`933-ci-commons/src/main/java/io/harness/git/helper/BitbucketHelper.java` line 26 at r7](https://reviewable.io/reviews/harness/harness-core/43841#-NONJIMt9QlACvf52MJ4:-NONJIMt9QlACvf52MJ5:bg2urf4) ([raw file](https://github.com/harness/harness-core/blob/f1ccdd9230b380b2224c18dde6a219679809e20c/933-ci-commons/src/main/java/io/harness/git/helper/BitbucketHelper.java#L26)):*
> ```Java
>   private static final String BITBUCKET_CLOUD_URL = "https://bitbucket.org/";
> 
>   private BitbucketHelper() {
> ```

fyi, there is also Singleton annotation which takes care of boiler-plate code.


<!-- Sent from Reviewable.io -->

2023-02-16 15:27 UTC, merged