[feat]: [CDS-50112]: ECS task definition arn support
harness/harness-core pull request #43851
Opened 2023-02-12 23:56 UTC by PragyeshMishra01

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-13 07:19 UTC, sainath-b requested changes
Lets change the approach that we discussed.
We will go ahead by creating new delegate task to handle only ARN and refactor delegate code to keep delegate handlers light weight.
cc: @rohitk-h

2023-02-14 08:46 UTC, PragyeshMishra01 commented
> Lets change the approach that we discussed. We will go ahead by creating new delegate task to handle only ARN and refactor delegate code to keep delegate handlers light weight. cc: @rohitk-h

Done

2023-02-14 12:55 UTC, alluvamsi-harness requested changes
lets also check the backward compatibility, by running automation

2023-02-14 12:55 UTC, alluvamsi-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java
> +        ServiceSweepingOutput.builder().finalServiceYaml(mergedServiceYaml).build(), StepCategory.STAGE.name());
Why is this change done?

2023-02-14 12:55 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepHelperImpl.java
>              .filter(ecsManifest -> ManifestType.EcsTaskDefinition.equals(ecsManifest.getType()))
This class has
if (isEmpty(ecsManifests)) {
      throw new InvalidRequestException("ECS Task Definition, Service Definition Manifests are mandatory.", USER);
}
Can we add a better message here

2023-02-14 13:00 UTC, alluvamsi-harness requested changes

2023-02-14 13:08 UTC, PragyeshMishra01 commented
> lets also check the backward compatibility, by running automation

I will check, but I have written it in backward compatible manner.

2023-02-16 06:10 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 606 at r5](https://reviewable.io/reviews/harness/harness-core/43851#-NONpwOo6o1S4-V8TQhd:-NONpwOo6o1S4-V8TQhe:b-f7f9wf) ([raw file](https://github.com/harness/harness-core/blob/52640bcaf36e0b7b703bb41e788214e64d31a258/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L606)):*
> ```Java
>     serviceCustomSweepingOutputHelper.saveAdditionalServiceFieldsToSweepingOutput(mergedServiceYaml, ambiance);
> 
>     final NGServiceV2InfoConfig ngServiceV2InfoConfig = ngServiceConfig.getNgServiceV2InfoConfig();
> ```

we have the ngServiceConfig here, so in the `saveAdditionalServiceFieldsToSweepingOutput` can we not just pass it instead of taking the yaml and then converting it to the object


<!-- Sent from Reviewable.io -->

2023-02-16 06:10 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/43851#-NONq6_z4spSpyZVwXX_:-NONq6_z4spSpyZVwXXa:b86bify) ([raw file](https://github.com/harness/harness-core/blob/52640bcaf36e0b7b703bb41e788214e64d31a258/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java#L65)):*
> ```Java
>             .ecsTaskDefinitionArn(ecsServiceSpec.getEcsTaskDefinitionArn().fetchFinalValue().toString())
>             .build();
>     sweepingOutputService.consume(ambiance, ServiceStepV3Constants.SERVICE_CUSTOM_SWEEPING_OUTPUT,
> ```

Lets keep the name to be specific to ECS only instead of `ServiceStepV3Constants.SERVICE_CUSTOM_SWEEPING_OUTPUT`


<!-- Sent from Reviewable.io -->

2023-02-16 06:14 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsCanaryDeployStep.java
> +    if (ecsStepExecutorParams.getEcsTaskDefinitionManifestContent() == null) {
Pragyesh let discuss on this conditions. We can put better conditions here.

2023-02-20 14:41 UTC, sainath-b approved these changes

2023-02-20 14:45 UTC, sainath-b submitted a review, later dismissed

2023-02-20 17:44 UTC, PragyeshMishra01 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java
> +        ServiceSweepingOutput.builder().finalServiceYaml(mergedServiceYaml).build(), StepCategory.STAGE.name());
changed it now.

2023-02-20 17:44 UTC, PragyeshMishra01 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsCanaryDeployStep.java
> +    if (ecsStepExecutorParams.getEcsTaskDefinitionManifestContent() == null) {
Done

2023-02-20 17:44 UTC, PragyeshMishra01 commented
> _[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/43851#-NONq6_z4spSpyZVwXX_:-NONq6_z4spSpyZVwXXa:b86bify) ([raw file](https://github.com/harness/harness-core/blob/52640bcaf36e0b7b703bb41e788214e64d31a258/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java#L65)):_
> 
> > ```java
> >             .ecsTaskDefinitionArn(ecsServiceSpec.getEcsTaskDefinitionArn().fetchFinalValue().toString())
> >             .build();
> >     sweepingOutputService.consume(ambiance, ServiceStepV3Constants.SERVICE_CUSTOM_SWEEPING_OUTPUT,
> > ```
> 
> Lets keep the name to be specific to ECS only instead of `ServiceStepV3Constants.SERVICE_CUSTOM_SWEEPING_OUTPUT`

Done

2023-02-20 17:45 UTC, PragyeshMishra01 commented
> _[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/43851#-NONq6_z4spSpyZVwXX_:-NONq6_z4spSpyZVwXXa:b86bify) ([raw file](https://github.com/harness/harness-core/blob/52640bcaf36e0b7b703bb41e788214e64d31a258/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java#L65)):_
> 
> > ```java
> >             .ecsTaskDefinitionArn(ecsServiceSpec.getEcsTaskDefinitionArn().fetchFinalValue().toString())
> >             .build();
> >     sweepingOutputService.consume(ambiance, ServiceStepV3Constants.SERVICE_CUSTOM_SWEEPING_OUTPUT,
> > ```
> 
> Lets keep the name to be specific to ECS only instead of `ServiceStepV3Constants.SERVICE_CUSTOM_SWEEPING_OUTPUT`

Done

2023-02-20 17:46 UTC, PragyeshMishra01 commented
> Lets change the approach that we discussed. We will go ahead by creating new delegate task to handle only ARN and refactor delegate code to keep delegate handlers light weight. cc: @rohitk-h

Done

2023-02-20 17:58 UTC, PragyeshMishra01 commented
trigger messagecheck

2023-02-20 17:59 UTC, PragyeshMishra01 commented
trigger messagecheck

2023-02-20 18:02 UTC, alluvamsi-harness approved these changes

2023-02-20 18:43 UTC, sainath-b approved these changes

2023-02-20 18:44 UTC, sainath-b submitted a review, later dismissed
> Reviewed 2 of 12 files at r1, 22 of 35 files at r2, 1 of 2 files at r3, 2 of 6 files at r4, 2 of 4 files at r5, 17 of 17 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43851)* status: 29 file(s) to review. 1. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-20 18:45 UTC, alluvamsi-harness reviewed
> Reviewed 1 of 12 files at r1, 19 of 35 files at r2, 1 of 6 files at r4, 2 of 4 files at r5, 5 of 17 files at r6, 1 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43851)* status: 1. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-20 18:46 UTC, alluvamsi-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43851)* status: 1. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-20 21:45 UTC, mdmilic approved these changes
Approving only delegate owned files

> Reviewed 2 of 35 files at r2, 4 of 17 files at r6, 1 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43851#-:-NOkmUop4bwlGFf4N5Qk:bwc08oq)* status: 1. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-21 06:49 UTC, PragyeshMishra01 commented
trigger ti4

2023-02-21 08:58 UTC, sainath-b approved these changes

2023-02-21 08:58 UTC, sainath-b approved these changes
> Reviewed 2 of 3 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43851)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-21 11:10 UTC, alluvamsi-harness approved these changes

2023-02-22 09:06 UTC, merged