feat: [CDS-52610]: Instace Sync Aws Sam
harness/harness-core pull request #43902
Opened 2023-02-13 18:42 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-13 22:09 UTC, rohitk-h approved these changes
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 38 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-13 22:09 UTC, rohitk-h commented
Some files are missing the ownedat annotation, lgtm otherwise





<!-- Sent from Reviewable.io -->

2023-02-14 06:15 UTC, rohitk-h approved these changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 39 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-14 07:18 UTC, PragyeshMishra01 approved these changes

2023-02-14 07:18 UTC, PragyeshMishra01 approved these changes
> Reviewed 34 of 38 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-14 16:14 UTC, sainath-b commented on 126-instance/src/main/java/io/harness/models/infrastructuredetails/AwsSamInfrastructureDetails.java
> +  String region;
Don't we need connector here?

2023-02-14 16:15 UTC, sainath-b commented on 126-instance/src/main/java/io/harness/models/infrastructuredetails/InfrastructureDetails.java
> +      @JsonSubTypes.Type(value = AwsSamInfrastructureDetails.class, name = "AwsSam")
Lets use AWS_SAM

2023-02-14 16:19 UTC, sainath-b commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/awssam/request/AwsSamCommandRequest.java
> +      capabilities.add(AwsCliInstallationCapability.builder().criteria("AWS Cli Installed").build());
Lets use CLI instead of Cli

2023-02-14 16:22 UTC, sainath-b commented on 126-instance/src/main/java/io/harness/dtos/instanceinfo/InstanceInfoDTO.java
> +      @JsonSubTypes.Type(value = AwsSamInstanceInfoDTO.class, name = "AwsSam")
Lets use AWS_SAM here

2023-02-14 16:22 UTC, sainath-b requested changes
Commented few changes

2023-02-14 17:19 UTC, alluvamsi-harness commented on 126-instance/src/main/java/io/harness/dtos/instanceinfo/AwsSamInstanceInfoDTO.java
> +    return "AwsSam";
Done

2023-02-14 17:20 UTC, alluvamsi-harness commented on 126-instance/src/main/java/io/harness/dtos/instanceinfo/InstanceInfoDTO.java
> +      @JsonSubTypes.Type(value = AwsSamInstanceInfoDTO.class, name = "AwsSam")
Done

2023-02-14 17:22 UTC, alluvamsi-harness commented on 126-instance/src/main/java/io/harness/models/infrastructuredetails/AwsSamInfrastructureDetails.java
> +  String region;
Not needed, Its similar in other swim-lanes also

2023-02-14 17:23 UTC, alluvamsi-harness commented on 126-instance/src/main/java/io/harness/models/infrastructuredetails/InfrastructureDetails.java
> +      @JsonSubTypes.Type(value = AwsSamInfrastructureDetails.class, name = "AwsSam")
Done

2023-02-14 17:25 UTC, alluvamsi-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/awssam/request/AwsSamCommandRequest.java
> +      capabilities.add(AwsCliInstallationCapability.builder().criteria("AWS Cli Installed").build());
Done

2023-02-14 17:25 UTC, alluvamsi-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/awssam/request/AwsSamCommandRequest.java
> +    capabilities.add(AwsSamInstallationCapability.builder().criteria("Aws Sam Installed").build());
Done

2023-02-14 18:11 UTC, rohitk-h approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 5 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-14 18:16 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 5 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-15 07:19 UTC, yogesh-chauhan approved these changes

2023-05-03 17:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=43902) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=43902) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: alluvamsi-harness<br/>:x: sainath-b<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=43902) it.</sub>

2023-05-03 21:19 UTC, rohitk-h approved these changes
> Reviewed 12 of 13 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 19 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-05-03 22:21 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 19 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-05-03 22:21 UTC, rohitk-h commented
trigger uts

2023-05-05 16:14 UTC, rohitk-h submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 20 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-05-10 02:41 UTC, sainath-b commented
trigger uts

2023-05-10 03:06 UTC, sainath-b submitted a review, later dismissed

2023-05-10 03:06 UTC, sainath-b commented
trigger uts

2023-05-10 05:28 UTC, rohitk-h submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, 4 of 4 files at r8, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 31 file(s) to review. 6. unresolved discussions. Waiting on team(s): del-team. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java` line 195 at r10](https://reviewable.io/reviews/harness/harness-core/43902#-NV378WT92B2-OSrnwLK:-NV378WT92B2-OSrnwLL:b957gef) ([raw file](https://github.com/harness/harness-core/blob/33d2fbffbfd99bdcdd485a56ad25856f376a856b/332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java#L195)):*
> ```Java
>     String stepGroupIdentifier = AmbianceUtils.obtainStepGroupIdentifier(ambiance);
>     String stepIdentifier = AmbianceUtils.obtainStepIdentifier(ambiance);
>     //    if (Strings.isNotBlank(stepGroupIdentifier)) {
> ```

Is this intentional? 


<!-- Sent from Reviewable.io -->

2023-05-10 15:07 UTC, sainath-b commented
trigger codeformat

2023-05-10 15:07 UTC, sainath-b commented
trigger checkstyle

2023-05-10 16:19 UTC, sainath-b commented
trigger uts

2023-05-10 16:35 UTC, sainath-b commented
trigger uts

2023-05-10 17:23 UTC, rohitk-h approved these changes
> Reviewed 8 of 9 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43902)* status: 34 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-05-10 17:23 UTC, rohitk-h commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java` line 195 at r10](https://reviewable.io/reviews/harness/harness-core/43902#-NV378WT92B2-OSrnwLK:-NV5gBzW5y6_4oLpBOsC:bb7k0qh) ([raw file](https://github.com/harness/harness-core/blob/33d2fbffbfd99bdcdd485a56ad25856f376a856b/332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java#L195)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Is this intentional? 
</blockquote></details>

lgtm


<!-- Sent from Reviewable.io -->

2023-05-10 22:14 UTC, sainath-b commented
trigger codeformat

2023-05-10 22:15 UTC, sainath-b commented
trigger pmd

2023-05-10 22:20 UTC, sainath-b commented
trigger smartchecks

2023-05-10 22:32 UTC, sainath-b commented
trigger uts

2023-05-10 23:11 UTC, rohitk-h submitted a review, later dismissed

2023-05-10 23:46 UTC, sainath-b commented
trigger uts

2023-05-10 23:54 UTC, sainath-b commented
trigger uts

2023-05-11 00:29 UTC, sainath-b approved these changes

2023-05-11 01:57 UTC, merged