feat: [PIE-8323]: Add validations on pipeline limits and settings update
harness/harness-core pull request #43939
Opened 2023-02-14 11:38 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-14 11:52 UTC, shalini-agr commented
trigger messagecheck

2023-02-15 09:04 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-15 09:15 UTC, archit-harness requested changes
> Reviewed 1 of 4 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/SettingConstants.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/43939#-NOJLol03phPsqHKdl2n:-NOJLol25Bb57M3bi2BB:b-jqy28j) ([raw file](https://github.com/harness/harness-core/blob/de7fe81ec70339c3dec1ca5ad51a89ddba24c813/pipeline-service/modules/orchestration/src/main/java/io/harness/SettingConstants.java#L11)):*
> ```Java
> 
> public class SettingConstants {
>   public final static String PIPELINE_TIMEOUT = "pipeline_timeout";
> ```

why do we need this constant as well?


<!-- Sent from Reviewable.io -->

2023-02-15 09:23 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/SettingConstants.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/43939#-NOJLol03phPsqHKdl2n:-NOJNceq6GHQ3ks9oS50:bstm2e6) ([raw file](https://github.com/harness/harness-core/blob/de7fe81ec70339c3dec1ca5ad51a89ddba24c813/pipeline-service/modules/orchestration/src/main/java/io/harness/SettingConstants.java#L11)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need this constant as well?
</blockquote></details>

Right, we don't need these. I added these to test something but forgot to remove from here.
Have removed now.


<!-- Sent from Reviewable.io -->

2023-02-15 09:46 UTC, archit-harness approved these changes
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-15 11:44 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-15 11:52 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuGiG65RswuZE9sLG:-NOJuGiG65RswuZE9sLH:bjqvj0w) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L44)):*
> ```Java
>           "[SettingEnforcementValidator]: Error occurred while fetching enforcement metadata for featureRestrictionName: {}",
>           featureRestrictionName, ex);
>       throw new InternalServerErrorException("Failed to update the setting. Please try again later.");
> ```

Just wanted to understand the error message here. The method name is "validate", API called is "getFeatureRestrictionMetadata" and the error message is "Failed to update setting". How are all these things related?

I think mistake here is that we know what use-case we are integrating this for and thus we have added error message accordingly. Ideally error message should only be as per the current class.


<!-- Sent from Reviewable.io -->

2023-02-15 11:52 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuppp-xEk76qVnPH9:-NOJuppp-xEk76qVnPHA:btmxjzu) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L65)):*
> ```Java
>         break;
>       default:
>         log.warn(
> ```

why is this warn and not error log?


<!-- Sent from Reviewable.io -->

2023-02-15 11:54 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJvAAzCH1gGRfCf2FN:-NOJvAAzCH1gGRfCf2FO:b-trkckk) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java#L34)):*
> ```Java
>     if (settingValue > limit) {
>       throw new InvalidRequestException(
>           String.format("%s cannot be greater than %s seconds for your account plan", newSettingDTO.getName(), limit));
> ```

Again here the error message is too customized for a user. We should throw generic errors like "settings value {} exceeded permissible value {}" or something similar.


<!-- Sent from Reviewable.io -->

2023-02-15 12:00 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 1. unresolved discussions. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJvAAzCH1gGRfCf2FN:-NOJwKf01TF6lNsMWTI9:b-m0o3u9) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Again here the error message is too customized for a user. We should throw generic errors like "settings value {} exceeded permissible value {}" or something similar.
</blockquote></details>

This is specifically for the case of timeout when string would be of the format 1h, 1m, etc. 
And we have set default values in terms of seconds, so, in this case, it has to be a specific error message, can't be generic.


<!-- Sent from Reviewable.io -->

2023-02-15 12:02 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJvAAzCH1gGRfCf2FN:-NOJx62-EK7VczYilrhU:b-2pqz2q) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java#L34)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

This is specifically for the case of timeout when string would be of the format 1h, 1m, etc. 
And we have set default values in terms of seconds, so, in this case, it has to be a specific error message, can't be generic.
</blockquote></details>

Whats the need for "your account plan" here?


<!-- Sent from Reviewable.io -->

2023-02-15 12:05 UTC, shalini-agr commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJvAAzCH1gGRfCf2FN:-NOJxXwq3igkqpRce5bl:b69qxuu) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Whats the need for "your account plan" here?
</blockquote></details>

we have different default values for different account plans like free, enterprise, etc.
This is to mention that.


<!-- Sent from Reviewable.io -->

2023-02-15 12:07 UTC, shalini-agr commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuppp-xEk76qVnPH9:-NOJxrHf6tuBhBecbuDV:bwhjd4o) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this warn and not error log?
</blockquote></details>

.
As it's not an error in impl or configuration, logging it an error would be a wrong indication i guess. It's just a warning that we don't an impl for this specific restriction type.


<!-- Sent from Reviewable.io -->

2023-02-15 12:08 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuppp-xEk76qVnPH9:-NOJyD5XA7B_Lnqsnn0N:b-nxwitm) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L65)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

.
As it's not an error in impl or configuration, logging it an error would be a wrong indication i guess. It's just a warning that we don't an impl for this specific restriction type.

</blockquote></details>

If we are getting an unexpected restriction type, this should be flagged as error as its not intended. Only if we record it as an error, we would be able to get enough attention to it to fix it.


<!-- Sent from Reviewable.io -->

2023-02-15 12:10 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJvAAzCH1gGRfCf2FN:-NOJyQHYEbcxadqAXqjF:b-7fwi3n) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java#L34)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

we have different default values for different account plans like free, enterprise, etc.
This is to mention that.
</blockquote></details>

This class in itself doesn't talk about any plan. It just does a purpose of comparing and enforcing a limit. IMO a generic error saying limits breached or related should be good enough rather than customizing it with adding additional metadata details like "for your plan" or something.
Also, I would suggest to atleast say "for given account plan" and not "your plan". In terms of error, we just are generic and not directed towards anyone.


<!-- Sent from Reviewable.io -->

2023-02-15 12:12 UTC, shalini-agr commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJvAAzCH1gGRfCf2FN:-NOJz9MV07iXyYSOvsZy:bdlhlx3) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This class in itself doesn't talk about any plan. It just does a purpose of comparing and enforcing a limit. IMO a generic error saying limits breached or related should be good enough rather than customizing it with adding additional metadata details like "for your plan" or something.
Also, I would suggest to atleast say "for given account plan" and not "your plan". In terms of error, we just are generic and not directed towards anyone.
</blockquote></details>

yeah, I agree with this, better to not have error in second person narrative, i'll replace 'your account plan' with 'given account plan'


<!-- Sent from Reviewable.io -->

2023-02-15 12:27 UTC, shalini-agr commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuppp-xEk76qVnPH9:-NOK1XZABZSOiPerM37B:b-9lhaqc) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If we are getting an unexpected restriction type, this should be flagged as error as its not intended. Only if we record it as an error, we would be able to get enough attention to it to fix it.
</blockquote></details>

This case of default actually comes when an FF if off, which means we don't really want to validate the values. So, this is the expected behavior that validation won't happen in that case, again not an erorr on any part.


<!-- Sent from Reviewable.io -->

2023-02-15 12:31 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 3. unresolved discussions. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuGiG65RswuZE9sLG:-NOK1zeB602O4pCqDsz6:biyl4qz) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Just wanted to understand the error message here. The method name is "validate", API called is "getFeatureRestrictionMetadata" and the error message is "Failed to update setting". How are all these things related?

I think mistake here is that we know what use-case we are integrating this for and thus we have added error message accordingly. Ideally error message should only be as per the current class.
</blockquote></details>

currently, this method is only called by update or restore setting method which can both be generically categorized as update, 
yes i agree, error message shouldn't depend upon the caller but in this case, this error is what will be displayed on ui to the user, so if we log something like failed to validate, user won't be able to understand what failed since validation hasn't even happend yet and they were just trying to update/restore.


<!-- Sent from Reviewable.io -->

2023-02-15 12:41 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuGiG65RswuZE9sLG:-NOK4iaR4IaZAM9l-DGM:bc41qcl) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L44)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

currently, this method is only called by update or restore setting method which can both be generically categorized as update, 
yes i agree, error message shouldn't depend upon the caller but in this case, this error is what will be displayed on ui to the user, so if we log something like failed to validate, user won't be able to understand what failed since validation hasn't even happend yet and they were just trying to update/restore.
</blockquote></details>

We cannot rely on callers of this method, be it only update / restore at this moment. Next time we onboard a new caller, we won't come here and change things.

We should throw validation error something like "Failed to validate enforcement limits as we faced internal error" or something. On top of it, callers should append another layer of error or explanation mentioning the use-case which failed.


<!-- Sent from Reviewable.io -->

2023-02-15 12:43 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuppp-xEk76qVnPH9:-NOK59InCifbMBr_pqTS:b-6uktgm) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L65)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

This case of default actually comes when an FF if off, which means we don't really want to validate the values. So, this is the expected behavior that validation won't happen in that case, again not an erorr on any part.
</blockquote></details>

Then why is it a warn? Then it should be info log saying "no validation for restriction type: {}". We can discuss on call if required.


<!-- Sent from Reviewable.io -->

2023-02-15 12:43 UTC, shalini-agr commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuGiG65RswuZE9sLG:-NOK5GF-5OowzZVnzvQD:b-ofazkg) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We cannot rely on callers of this method, be it only update / restore at this moment. Next time we onboard a new caller, we won't come here and change things.

We should throw validation error something like "Failed to validate enforcement limits as we faced internal error" or something. On top of it, callers should append another layer of error or explanation mentioning the use-case which failed.
</blockquote></details>

In that case, changes would be required in settings framework.
Discussed with tejas, he said, they'll take it as an enhancement to update the error messages


<!-- Sent from Reviewable.io -->

2023-02-15 12:43 UTC, shalini-agr commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuppp-xEk76qVnPH9:-NOK5Vev3meM_ZK-2DIv:b-7lm35b) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Then why is it a warn? Then it should be info log saying "no validation for restriction type: {}". We can discuss on call if required.
</blockquote></details>

okay


<!-- Sent from Reviewable.io -->

2023-02-15 13:19 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 354 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDCinAEEX12_Qp3LW:-NOKDCinAEEX12_Qp3LX:b63vbq9) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L354)):*
> ```Java
>       customValidation(accountIdentifier, oldSettingDTO, newSettingDTO);
>     } catch (InternalServerErrorException ex) {
>       throw new InternalServerErrorException("Failed to update the setting. Please try again later.");
> ```

We should have better error handling.
1) Either we wrap the caught exception inside another exception and then throw it. I'm not sure if UI will be able to properly parse it or not.
2) We should attach the message from the caught exception into message from this layer and then throw the exception.

Idea is to eventually let user with more info around the failure. Current message doesn't help user in any way. its as good as saying "Something failed, please try again".


<!-- Sent from Reviewable.io -->

2023-02-15 13:19 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 405 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDj5b29am22i8fOA5:-NOKDj5b29am22i8fOA6:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L405)):*
> ```Java
>       customValidation(accountIdentifier, oldSettingDTO, settingDTO);
>     } catch (InternalServerErrorException ex) {
>       throw new InternalServerErrorException("Failed to restore the setting. Please try again later.");
> ```

same here


<!-- Sent from Reviewable.io -->

2023-02-15 13:21 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuGiG65RswuZE9sLG:-NOKE-_yBbMrxFOQqVq5:b7ejwct) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L44)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done
</blockquote></details>

We should mention the failure here. eg: Failed to fetch enforcement limits for the given account. Also, we shouldn't mention "please try again later" as this is user specific error message. Any functional layer shouldn't send user specific error message.


<!-- Sent from Reviewable.io -->

2023-02-15 13:22 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 53 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKEHT41rChEJ1FBhI_:-NOKEHT41rChEJ1FBhIa:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L53)):*
> ```Java
>           featureRestrictionName);
>       throw new InternalServerErrorException(
>           "Failed to validate the setting because of an internal error. Please try again later.");
> ```

same here


<!-- Sent from Reviewable.io -->

2023-02-15 13:22 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKEK9cBuHD67L0l6r0:-NOKEK9cBuHD67L0l6r1:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L62)):*
> ```Java
>           featureRestrictionName, edition);
>       throw new InternalServerErrorException(
>           "Failed to validate the setting because of an internal error. Please try again later.");
> ```

same


<!-- Sent from Reviewable.io -->

2023-02-15 16:43 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 5 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 354 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDCinAEEX12_Qp3LW:-NOKxGbkESOScXot6rhC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L354)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should have better error handling.
1) Either we wrap the caught exception inside another exception and then throw it. I'm not sure if UI will be able to properly parse it or not.
2) We should attach the message from the caught exception into message from this layer and then throw the exception.

Idea is to eventually let user with more info around the failure. Current message doesn't help user in any way. its as good as saying "Something failed, please try again".
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 405 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDj5b29am22i8fOA5:-NOKxGJT5dxVxkWWjJhR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L405)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/43939#-NOJuGiG65RswuZE9sLG:-NOKxJVmENr3OO4AeHya:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25ad728295601e97fb144bc935b1a37fadfe932a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should mention the failure here. eg: Failed to fetch enforcement limits for the given account. Also, we shouldn't mention "please try again later" as this is user specific error message. Any functional layer shouldn't send user specific error message.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 53 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKEHT41rChEJ1FBhI_:-NOKxJhvAsEWzaaOM-HN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKEK9cBuHD67L0l6r0:-NOKxE3MBx2PUjYNen39:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/AbstractEnforcementValidator.java#L62)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-16 07:05 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 354 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDCinAEEX12_Qp3LW:-NOO0vTe2a1i75myU4Yf:b-uar2if) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L354)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you try and execute it once? I don't think it will give correct error message as there's no space after "because" and we are just directly appending the exception message.
Also, we can't comment what type of error message may come from upstream layers, thus we shouldn't rely on complete english sentences here such as "couldn't update because" etc as they may sound completely un-meaningful once shown up on UI.
Lets keep it simple may be something like : "Failed to update setting : {error message}". TBH this could also go wrong but should be working in 99.9% cases.


<!-- Sent from Reviewable.io -->

2023-02-16 07:05 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 354 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDCinAEEX12_Qp3LW:-NOO1fRR6EC5Rl3AuTsx:bd6zgjq) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L354)):*
> Either we wrap the caught exception inside another exception and then throw it. I'm not sure if UI will be able to properly parse it or not.
Also did we check on this? This is the best way to handle it


<!-- Sent from Reviewable.io -->

2023-02-16 07:06 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 405 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDj5b29am22i8fOA5:-NOO1vxq9sYapw8cVX_Z:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L405)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same


<!-- Sent from Reviewable.io -->

2023-02-16 07:10 UTC, mohitg0795 commented
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/43939#-NOO2gpd4MyKToBR5QnC:-NOO2gpd4MyKToBR5QnD:b2kro1z) ([raw file](https://github.com/harness/harness-core/blob/b321bd39234f55f6220bba6da74bf725a37620c8/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/TimeoutMaxLimitEnforcementValidator.java#L21)):*
> ```Java
> import lombok.extern.slf4j.Slf4j;
> 
> @Slf4j
> ```

This isn't required, we aren't logging anything here.


<!-- Sent from Reviewable.io -->

2023-02-16 10:17 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 354 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDCinAEEX12_Qp3LW:-NOOiXxBEq2BVGG-K3a-:b1vtebn) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L354)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

> Either we wrap the caught exception inside another exception and then throw it. I'm not sure if UI will be able to properly parse it or not.
Also did we check on this? This is the best way to handle it
</blockquote></details>

Nested exceptions are not yet supported by UI
Have just appended error messages and tested in local. It's looking like this:
`Error while updating the setting: Failed to fetch enforcement limits for the given account plan.`
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 405 at r4](https://reviewable.io/reviews/harness/harness-core/43939#-NOKDj5b29am22i8fOA5:-NOOiip_8d4VZbD68MjC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8d957d9057e24365332748697530029740d2277/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L405)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-16 10:32 UTC, mohitg0795 approved these changes
> Reviewed 1 of 4 files at r1, 1 of 5 files at r2, 1 of 1 files at r3, 1 of 5 files at r4, 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-16 10:45 UTC, archit-harness approved these changes
> Reviewed 1 of 5 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-16 10:52 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 5 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-16 12:34 UTC, tiwaritejas approved these changes
> Reviewed 1 of 4 files at r1, 1 of 5 files at r2, 1 of 1 files at r3, 1 of 5 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-16 12:50 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 4 files at r1, 1 of 5 files at r2, 1 of 1 files at r3, 1 of 5 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43939)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-16 13:17 UTC, merged