[feat]: [PLG-1639]: added isCrossGenerationAccessEnabled account setting and APIs
harness/harness-core pull request #43955
Opened 2023-02-14 19:10 UTC by kapil-harness

## Describe your changes
added isCrossGenerationAccessEnabled account setting and APIs

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-16 21:57 UTC, thomas-grasman commented
trigger messagecheck

2023-02-21 21:20 UTC, neelam-harness requested changes
Overall LGTM

2023-02-21 21:20 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/beans/Account.java
> +    private Boolean isCrossGenerationAccessEnabled = Boolean.FALSE;
Since we are defaulting this value to false, can we just make it a primitive `boolean` instead of `Boolean` ?

2023-02-21 21:20 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
> +    if (account.isCrossGenerationAccessEnabled() != null) {
nit: when will this boolean be null ?

2023-02-21 21:20 UTC, neelam-harness commented on 400-rest/src/test/java/software/wings/service/AccountServiceTest.java
> +                          .withCompanyName("Wings")
nit: let's rename it to `Harness` now ? :)

2023-02-21 21:20 UTC, neelam-harness commented on 945-account-mgmt/src/main/java/io/harness/account/resource/AccountResource.java
> +  @Path("{accountIdentifier}/update-cross-generation-access-enabled")
As discussed offline, let's make it `Internal` if there is no specific use-case for the customers to call this API directly via postman etc. 
Eg: https://github.com/harness/harness-core/blob/9836e1757e280dd4943e1816a8655f40e098bf2a/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/LicenseResource.java#L83

2023-02-21 22:08 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43955)* status: 15 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 607 at r4](https://reviewable.io/reviews/harness/harness-core/43955#-NOGKUbhY2I_7JjtcvR3-r4-607:-NOq-dn81WEbol6pB4ls:b-i51zn7) ([raw file](https://github.com/harness/harness-core/blob/51fdfdaf097b49db867952e722dfa1a7254c7ac6/400-rest/src/main/java/software/wings/beans/Account.java#L607)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Since we are defaulting this value to false, can we just make it a primitive `boolean` instead of `Boolean` ?
</blockquote></details>

At first I did that only, however i was suggested by guys from SPG team to make it non-primitive as historically adding primitive fields in Account.java class has caused serialization/de-serialization issues.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 938 at r4](https://reviewable.io/reviews/harness/harness-core/43955#-NOGKUbhY2I_7JjtcvR6-r4-938:-NOq-nUvAvukyzTJvhGy:bu3dpm7) ([raw file](https://github.com/harness/harness-core/blob/51fdfdaf097b49db867952e722dfa1a7254c7ac6/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L938)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

nit: when will this boolean be null ?
</blockquote></details>

ideally not, but kept this null check just to be safe as it's non-primitve object
___
*[`400-rest/src/test/java/software/wings/service/AccountServiceTest.java` line 587 at r4](https://reviewable.io/reviews/harness/harness-core/43955#-NOjbNinE-XJ7Ty1KbE_-r4-587:-NOq0LsK-nNaf2kRZ5Qq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/51fdfdaf097b49db867952e722dfa1a7254c7ac6/400-rest/src/test/java/software/wings/service/AccountServiceTest.java#L587)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

nit: let's rename it to `Harness` now ? :) 
</blockquote></details>

done
___
*[`945-account-mgmt/src/main/java/io/harness/account/resource/AccountResource.java` line 177 at r4](https://reviewable.io/reviews/harness/harness-core/43955#-NOGKUbhY2I_7JjtcvR9-r4-177:-NOq0Nsu7UXvlZl529Kt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/51fdfdaf097b49db867952e722dfa1a7254c7ac6/945-account-mgmt/src/main/java/io/harness/account/resource/AccountResource.java#L177)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

As discussed offline, let's make it `Internal` if there is no specific use-case for the customers to call this API directly via postman etc. 
Eg: https://github.com/harness/harness-core/blob/9836e1757e280dd4943e1816a8655f40e098bf2a/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/LicenseResource.java#L83 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-02-21 22:20 UTC, Xin-Harness requested changes
> Reviewed 1 of 10 files at r1, 3 of 12 files at r2, 1 of 3 files at r3, 2 of 4 files at r4, 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43955)* status: 15 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResourceNG.java` line 248 at r5](https://reviewable.io/reviews/harness/harness-core/43955#-NOq2YJm51A6oEUm7YMS:-NOq2YJnEwUNCBfMWq8L:bvfq0kt) ([raw file](https://github.com/harness/harness-core/blob/ed3411698f5871c4f77851f5b77a75e020d8011e/400-rest/src/main/java/software/wings/resources/AccountResourceNG.java#L248)):*
> ```Java
>   @PUT
>   @Hidden
>   @Path("/{accountId}/update-cross-generation-access-enabled")
> ```

We should try to avoid use verb in rest api path, since the PUT method already indicate the action. I would suggest to call it /cross-generation-access


<!-- Sent from Reviewable.io -->

2023-02-21 23:05 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43955)* status: 15 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResourceNG.java` line 248 at r5](https://reviewable.io/reviews/harness/harness-core/43955#-NOq2YJm51A6oEUm7YMS:-NOqDNfd-vxPkHJH3iXp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed3411698f5871c4f77851f5b77a75e020d8011e/400-rest/src/main/java/software/wings/resources/AccountResourceNG.java#L248)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

We should try to avoid use verb in rest api path, since the PUT method already indicate the action. I would suggest to call it /cross-generation-access
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-21 23:30 UTC, neelam-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 12 files at r2, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43955#-:-NOqJ4T71ObtY7neaYg-:bnfp4nl)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/43955#-NOqIuPmAcp3E56LjkFd:-NOqIuPmAcp3E56LjkFe:b-gmmigm) ([raw file](https://github.com/harness/harness-core/blob/f321ac3c44c6ed3bae48a48bc42761314da7ccf6/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java#L53)):*
> ```Java
>   @VariableExpression(skipVariableExpression = true)
>   DefaultExperience defaultExperience;
>   @Schema(description = "Specifies weather access to other generation is allowed or not")
> ```

very nit: `weather` -> `whether`


<!-- Sent from Reviewable.io -->

2023-02-21 23:32 UTC, thomas-grasman approved these changes
> Reviewed 1 of 10 files at r1, 5 of 12 files at r2, 1 of 3 files at r3, 3 of 4 files at r4, 1 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43955)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-21 23:32 UTC, thomas-grasman approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43955)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-22 00:37 UTC, Xin-Harness approved these changes
> Reviewed 2 of 12 files at r2, 1 of 4 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43955)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-22 00:57 UTC, pranil-harness approved these changes

2023-02-22 01:01 UTC, merged