feat: [CDS-52600]: Deploy step handler with s3 artifact source
harness/harness-core pull request #44069
Opened 2023-02-17 07:09 UTC by rohitk-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-20 08:56 UTC, sainath-b approved these changes
> Reviewed 23 of 34 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 34 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-20 11:08 UTC, sainath-b requested changes
@rohitk-h UTs are failing. Please fix.

2023-02-20 16:47 UTC, PragyeshMishra01 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 34 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjeR00-1Dus-UyYAOx:-NOjeR00-1Dus-UyYAOy:b-81v7f0) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java#L272)):*
> ```Java
> 
>     ManifestOutcome awsLambdaManifestOutcome = getAwsLambdaManifestOutcome(manifestsOutcome.values());
> ```

are we not supporting harness store for manifest
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjdnHZ0MH6EGgr3urH:-NOjdnHZ0MH6EGgr3urI:b-33cs7c) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java#L325)):*
> ```Java
>     StoreConfig storeConfig = manifestOutcome.getStore();
>     if (!ManifestStoreType.isInGitSubset(storeConfig.getKind())) {
>       throw new InvalidRequestException("Invalid kind of storeConfig for Ecs step", USER);
> ```

should not be Ecs here in message exception
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaCommandRequest.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjh5m-0ZdzXr3RCGyw:-NOjh5m-0ZdzXr3RCGyx:bv9e2fw) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaCommandRequest.java#L61)):*
> ```Java
>     if (awsLambdaArtifactConfig instanceof AwsLambdaS3ArtifactConfig) {
>       AwsConnectorDTO connectorConfigDTO = (AwsConnectorDTO) ((AwsLambdaS3ArtifactConfig) awsLambdaArtifactConfig)
>                                                .getConnectorDTO()
> ```

nit: We should add NPE check for awsLambdaArtifactConfig, if it is null for prepareRollbackRequest
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaPrepareRollbackRequest.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjfwWF43ka31YYkX0O:-NOjfwWF43ka31YYkX0P:b-j0d31j) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaPrepareRollbackRequest.java#L45)):*
> ```Java
>   public AwsLambdaInfraConfig getAwsLambdaInfraConfig() {
>     return null;
>   }
> ```

is this intentional?


<!-- Sent from Reviewable.io -->

2023-02-21 01:07 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java
> +      throw new InvalidRequestException("Invalid kind of storeConfig for Ecs step", USER);
Remove Ecs

2023-02-21 01:11 UTC, sainath-b commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTask.java
>  public class AwsLambdaCommandTask extends AbstractDelegateRunnableTask {
@rohitk-h We shall use separate delegate task handler for each type of aws lambda task for backward compatibility

2023-02-21 01:13 UTC, sainath-b requested changes
@rohitk-h Please address comments

2023-02-21 05:12 UTC, piyush-bhuwalka commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +    mapBinder.addBinding(TaskType.AWS_LAMBDA_DEPLOY_COMMAND_TASK_NG).toInstance(AwsLambdaCommandTask.class);
we should have independent task types for each step

2023-02-21 05:18 UTC, piyush-bhuwalka commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaDeployRequest.java
>    String functionName;
@NonFinal @Expression(ALLOW_SECRETS) for functionName and qualifier as well

2023-02-21 05:19 UTC, piyush-bhuwalka commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambda.java
> +  String version;
there should be tags , aliases and other fields as well. We can look into GetFunction Response DTO for the fields

2023-02-21 05:25 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/beans/AwsLambdaStepOutcome.java
>  }
Lets add AwsLambdaPrepareRollbackOutcome DTO as well in this PR

2023-02-21 05:26 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java
> +    return executeTask(ambiance, stepParameters, awsLambdaStepPassThroughDataWithManifestContent);
assuming prepare rollback subtask will be part of another PR

2023-02-21 05:27 UTC, piyush-bhuwalka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java
> +  private AwsLambdaFunctionsInfraConfig getInfraConfig(InfrastructureOutcome infrastructure, Ambiance ambiance) {
make this public. This can be used in several steps

2023-02-21 06:52 UTC, rohitk-h reviewed
UT's fixed, comments addressed. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069#-:-NOmXvI1DFj_IXrFjajH:bd93d81)* status: 34 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Ptg-r2-110:-NOmSpywEhciv4FdIsIu:boac9ai) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java#L110)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Lets make this public. This can be used in several steps
</blockquote></details>

updated, 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java` line 202 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Ptg-r2-202:-NOmSr_61bpAeVgeFRSB:b-7g7nm2) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java#L202)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

assuming prepare rollback subtask will be part of another PR 
</blockquote></details>

yes, 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjeR00-1Dus-UyYAOx:-NOmSRk_Cn3ZajFdwcUN:b-3t3qa7) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java#L272)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

are we not supporting harness store for manifest
</blockquote></details>

not in the first iteration, we'll implement in phase 2. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjdnHZ0MH6EGgr3urH:-NOmSsry1UTanpTaMh-r:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java#L325)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

should not be Ecs here in message exception
</blockquote></details>

updated
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Ptg-r2-325:-NOmSxQmBgaPEg95S0uk:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/AwsLambdaHelper.java#L325)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

Remove Ecs
</blockquote></details>

updated
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/beans/AwsLambdaStepOutcome.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Ptk-r2-32:-NOmTSIz3IZPWP1lsjr5:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/beans/AwsLambdaStepOutcome.java#L32)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Lets add AwsLambdaPrepareRollbackOutcome DTO as well in this PR
</blockquote></details>

added
___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 2157 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Pts-r2-2157:-NOmYapN2rTlPqiGNm_d:b29yp0r) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L2157)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

we should have independent task types for each step
</blockquote></details>

Added `AwsLambdaDeployTask`
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTask.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Ptu-r2-34:-NOmZwsB3VcS-UP_gaQs:bkqrf2t) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambdaCommandTask.java#L34)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

@rohitk-h We shall use separate delegate task handler for each type of aws lambda task for backward compatibility
</blockquote></details>

agree, added `AwsLambdaDeployTask`
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambda.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Ptx-r2-23:-NOmj1Ay6K-tQTp3UDD3:b4rnasf) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/AwsLambda.java#L23)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

there should be tags , aliases and other fields as well. We can look into GetFunction Response DTO for the fields
</blockquote></details>

Can we add these as needed? Added tags, aliases are not being used yet. 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaCommandRequest.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjh5m-0ZdzXr3RCGyw:-NOmUvUI4BIjgI3xvqUp:b-bu91xm) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaCommandRequest.java#L61)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

nit: We should add NPE check for awsLambdaArtifactConfig, if it is null for prepareRollbackRequest
</blockquote></details>

Updated
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaDeployRequest.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Pu3-r2-36:-NOmV38A3QeUU31ItoAm:b-etnly2) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaDeployRequest.java#L36)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

@NonFinal @Expression(ALLOW_SECRETS) for functionName and qualifier as well
</blockquote></details>

good point, 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaPrepareRollbackRequest.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjfwWF43ka31YYkX0O:-NOmV7X6-0oSQJGZJhy0:b-skyv1y) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaPrepareRollbackRequest.java#L45)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

is this intentional?
</blockquote></details>

Added todo, this a WIP, so will update in followup PR. 


<!-- Sent from Reviewable.io -->

2023-02-21 08:28 UTC, sainath-b commented on 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
> +    kryo.register(AwsLambdaDeployRequest.class, 10000402);
100004XX series started for SAM
Please use different series for Lambda. May be 10000501

2023-02-21 08:29 UTC, sainath-b commented on 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
> +    kryo.register(AwsLambdaDeployRequest.class, 10000402);
@rohitk-h

2023-02-21 08:37 UTC, sainath-b commented on 400-rest/src/test/resources/manager-kryo-registrations.txt
> +10000403:io.harness.delegate.task.aws.lambda.response.AwsLambdaDeployResponse
Please use different series for AWS Lambda. 100004XX is used for AWS SAM

2023-02-21 08:37 UTC, sainath-b commented on 260-delegate/src/test/resources/kryo-registrations.txt
> +10000402:io.harness.delegate.task.aws.lambda.request.AwsLambdaDeployRequest
Please use different series for AWS Lambda. 100004XX is used for AWS SAM

2023-02-21 09:06 UTC, sainath-b submitted a review, later dismissed

2023-02-21 16:53 UTC, rohitk-h reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 38 file(s) to review. 16. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 2675 at r3](https://reviewable.io/reviews/harness/harness-core/44069#-NOmkifq2TfVJogn2dt3-r3-2675:-NOosoZz12PJtwGlZ9Km:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/b36fa5c40448f492bce093c911bd4a3ce07a199a/260-delegate/src/test/resources/kryo-registrations.txt#L2675)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

Please use different series for AWS Lambda. 100004XX is used for AWS SAM
</blockquote></details>

updated
___
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 3083 at r3](https://reviewable.io/reviews/harness/harness-core/44069#-NOmkifrUH6LXYdDHR27-r3-3083:-NOosmsh3t4e49i0iicx:boac9c8) ([raw file](https://github.com/harness/harness-core/blob/b36fa5c40448f492bce093c911bd4a3ce07a199a/400-rest/src/test/resources/manager-kryo-registrations.txt#L3083)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

Please use different series for AWS Lambda. 100004XX is used for AWS SAM
</blockquote></details>

updated. 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 2351 at r3](https://reviewable.io/reviews/harness/harness-core/44069#-NOTCEJ2JicewIFx0Pu6-r3-2351:-NOosvCV0_6uNq9pDTUA:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/b36fa5c40448f492bce093c911bd4a3ce07a199a/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L2351)):*
<details><summary><i>Previously, sainath-b (Sainath Batthala) wrote…</i></summary><blockquote>

@rohitk-h 
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-02-21 18:23 UTC, rohitk-h commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaCommandRequest.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/44069#-NOjh5m-0ZdzXr3RCGyw:-NOpCkCK7mWAxze8p7ZP:bnkqo4c) ([raw file](https://github.com/harness/harness-core/blob/5332906153c018ffacc98fc94ba30d37b12bde4c/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/lambda/request/AwsLambdaCommandRequest.java#L61)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Updated
</blockquote></details>

As per PMD:
`No need to check for null before an instanceof; the instanceof keyword returns false when given a null argument.`


<!-- Sent from Reviewable.io -->

2023-02-21 18:33 UTC, sainath-b approved these changes

2023-02-21 18:35 UTC, sainath-b approved these changes
> Reviewed 10 of 10 files at r3, 3 of 3 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 46 file(s) to review. 11. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 07:13 UTC, piyush-bhuwalka reviewed
> Reviewed 17 of 34 files at r1, 9 of 11 files at r2, 5 of 10 files at r3, 9 of 10 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 7 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 07:13 UTC, puthrayaharness approved these changes
> Reviewed 17 of 34 files at r1, 9 of 11 files at r2, 5 of 10 files at r3, 9 of 10 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 07:14 UTC, piyush-bhuwalka approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 6. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 11:11 UTC, mdmilic approved these changes
approving only delegate owned files

> Reviewed 1 of 34 files at r1, 3 of 11 files at r2, 1 of 10 files at r5, 2 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069#-:-NOsoX5U5v04eVBr3o5z:bm3cxlm)* status: 6. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-22 16:01 UTC, gn-harness approved these changes
> Reviewed 17 of 34 files at r1, 9 of 11 files at r2, 5 of 10 files at r3, 9 of 10 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: 6. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-22 16:08 UTC, piyush-bhuwalka approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44069)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-22 16:14 UTC, merged