[feat]: [IAC-49] Add License service for IAC
harness/harness-core pull request #44210
Opened 2023-02-22 10:55 UTC by nassergonzalez

## Describe your changes
Add license to the IAC module
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-23 15:38 UTC, Xin-Harness requested changes
> Reviewed 16 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44210)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java` line 221 at r1](https://reviewable.io/reviews/harness/harness-core/44210#-NOys3lR7-wFscHh1D29:-NOys3lR7-wFscHh1D2A:b-748jee) ([raw file](https://github.com/harness/harness-core/blob/c2b9b92b241caf587170a06afbfacf709251c46c/310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java#L221)):*
> ```Java
>     bind(AwsClient.class).to(AwsClientImpl.class); // same?
>     bind(CILicenseService.class)
>         .to(IACMLicenseServiceImpl.class)
> ```

Could you explain the reason that CILicenseService is bind to IACMLicenseServiceImpl, don't we need a IACMLicenseService instead?
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/license/IACMLicenseNoopServiceImpl.java` line 9 at r1](https://reviewable.io/reviews/harness/harness-core/44210#-NOyrApW1yo39Dd5zTm3:-NOyrApW1yo39Dd5zTm4:bm5rpdo) ([raw file](https://github.com/harness/harness-core/blob/c2b9b92b241caf587170a06afbfacf709251c46c/332-ci-manager/service/src/main/java/io/harness/ci/execution/license/IACMLicenseNoopServiceImpl.java#L9)):*
> ```Java
> 
> package io.harness.ci.license;
> ```

Missing Owner here
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/IACMLocalClient.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/44210#-NOytukq2mvcmGYQ7STB:-NOytukq2mvcmGYQ7STC:b-wub7qd) ([raw file](https://github.com/harness/harness-core/blob/c2b9b92b241caf587170a06afbfacf709251c46c/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/IACMLocalClient.java#L24)):*
> ```Java
> import java.time.temporal.ChronoUnit;
> public class IACMLocalClient implements IACMModuleLicenseClient {
>   private static final int ENTERPRISE_TRIAL_DEVELOPERS = 200;
> ```

Does Enterprise trial should have same number of developers as Team trial?


<!-- Sent from Reviewable.io -->

2023-02-23 15:54 UTC, nassergonzalez reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44210)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java` line 221 at r1](https://reviewable.io/reviews/harness/harness-core/44210#-NOys3lR7-wFscHh1D29:-NOyx7Vh6yBAs5SBrkOG:b-bbv0g0) ([raw file](https://github.com/harness/harness-core/blob/c2b9b92b241caf587170a06afbfacf709251c46c/310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java#L221)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Could you explain the reason that CILicenseService is bind to IACMLicenseServiceImpl, don't we need a IACMLicenseService instead?
</blockquote></details>

We use some CI code. For example when we start a step, we will eventually hit the VMInitialiseTaskParamBuilders which will try to retrieve the licenseSummary. The CILicenseService is just an interface so i think that it makes sense to use their interface and then bind it to our implementation so when we hit the VMInitialiseTaskPAramBuilder, the part of the code that requires the LicenseWithSummaryDTO, we will retrieve the license from the IACM server.

In this class for example, if the license is free, it will hit the free pool. There could be other scenarios that we don't know yet as we don't have the complete implementation right now. If in the future we need to implement our own interface then we can change it later
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/license/IACMLicenseNoopServiceImpl.java` line 9 at r1](https://reviewable.io/reviews/harness/harness-core/44210#-NOyrApW1yo39Dd5zTm3:-NOyySi-Bisuk-4MBsPp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2b9b92b241caf587170a06afbfacf709251c46c/332-ci-manager/service/src/main/java/io/harness/ci/execution/license/IACMLicenseNoopServiceImpl.java#L9)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Missing Owner here
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/IACMLocalClient.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/44210#-NOytukq2mvcmGYQ7STB:-NOyyZ8c-pL13GMxYqsm:b-lz38ag) ([raw file](https://github.com/harness/harness-core/blob/c2b9b92b241caf587170a06afbfacf709251c46c/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/IACMLocalClient.java#L24)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Does Enterprise trial should have same number of developers as Team trial?
</blockquote></details>

Those are placeholder values for now but yeah I am going to change them so it's clear that they will eventually be different


<!-- Sent from Reviewable.io -->

2023-02-23 16:18 UTC, Xin-Harness approved these changes
> Reviewed 2 of 19 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44210)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-24 14:15 UTC, scottyw approved these changes

2023-02-24 14:20 UTC, allofthesepeople approved these changes

2023-02-24 14:26 UTC, nassergonzalez commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/license/IACMLicenseNoopServiceImpl.java
> +    return CILicenseSummaryDTO.builder().edition(Edition.FREE).build();
Yeah so the CILicenseService is just an interface and the problem that I think that we will face is that the initial CI steps that we are using are the ones validating the license. So if this would not be an implementation of the CILicenseService, we would probably get problems. So I think that the way to go is using this interface but with our own implementation that will call our own license service

2023-02-24 14:37 UTC, allofthesepeople submitted a review, later dismissed
> Reviewed 16 of 19 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44210)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-24 14:37 UTC, scottyw reviewed
> Reviewed 16 of 19 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44210)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-24 14:48 UTC, scottyw submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44210)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-27 15:09 UTC, harshjain12 commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
> +        .to(IACMLicenseServiceImpl.class)
Put IACMLicenseServiceImpl in 310-iacm-manager
Move CILicenseService to contract

2023-02-28 15:17 UTC, Xin-Harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, 24 of 24 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44210)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-03-01 15:56 UTC, r0610205 approved these changes

2023-03-14 12:17 UTC, merged