feat: [CDS-52629]: Aws Lambda Rollback For Basic Strategy NG
harness/harness-core pull request #44218
Opened 2023-02-22 12:41 UTC by piyush-bhuwalka

## Describe your changes
- Introducing Prepare rollback and Rollback tasks for AWS Lambda
- Introducing new rollback step. 
- The feature is behind a feature flag and new swimlane.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/44218)

2023-02-23 21:12 UTC, rohitk-h commented
trigger feature-build

2023-02-24 06:35 UTC, rohitk-h commented
trigger feature-build

2023-02-24 11:47 UTC, piyush-bhuwalka commented
trigger messagecheck

2023-02-24 12:41 UTC, piyush-bhuwalka commented
trigger feature-build

2023-02-24 21:13 UTC, rohitk-h approved these changes
> Reviewed 3 of 35 files at r6, 5 of 17 files at r7, 41 of 49 files at r10, 2 of 5 files at r11, 6 of 14 files at r12, 1 of 1 files at r13, 19 of 22 files at r15, 1 of 2 files at r16, 5 of 5 files at r17, 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44218)* status: 87 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-27 02:57 UTC, piyush-bhuwalka commented
trigger feature-build

2023-02-27 04:45 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/rollback/AwsLambdaRollbackBaseStepInfo.java
> +  @JsonIgnore String awsLambdaDeployStepFnq;
nit: Use Fqn instead of Fnq

2023-02-27 04:46 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/aws/lambda/rollback/AwsLambdaRollbackStep.java
> +      log.error("Error while processing google function rollback response: {}", ExceptionUtils.getMessage(e), e);
Update error message with AWS Lambda

2023-02-27 05:13 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/cdstepinfo/aws/AwsLambdaRollbackStepInfoVisitorHelper.java
> +    return AwsLambdaDeployStepInfo.infoBuilder().build();
Should be AwsLambdaRollbackStepInfo

2023-02-27 05:24 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44218)* status: 87 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-27 05:29 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/CDStepInfo.java
> +        AwsLambdaDeployStepInfo.class, AwsSamRollbackStepInfo.class, AwsLambdaRollbackBaseStepInfo.class})
Add stepInfo call here not baseStepInfo

2023-02-27 05:33 UTC, sainath-b requested changes
Please address comments provided.

2023-02-27 05:38 UTC, piyush-bhuwalka commented
trigger feature-build

2023-02-27 05:41 UTC, sainath-b approved these changes

2023-02-27 05:41 UTC, sainath-b reviewed
> Reviewed 1 of 35 files at r6, 5 of 17 files at r7, 41 of 49 files at r10, 2 of 5 files at r11, 6 of 14 files at r12, 1 of 1 files at r13, 16 of 22 files at r15, 1 of 2 files at r16, 5 of 5 files at r17, 4 of 4 files at r18, 5 of 5 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44218)* status: 5 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-27 06:03 UTC, rohitk-h approved these changes
> Reviewed 5 of 5 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44218)* status: Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-27 11:50 UTC, piyush-bhuwalka commented
trigger feature-build

2023-02-27 17:30 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44218)* status: Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-27 21:28 UTC, raghuAtWings approved these changes
> Reviewed 1 of 35 files at r6, 5 of 17 files at r7, 41 of 49 files at r10, 2 of 5 files at r11, 6 of 14 files at r12, 1 of 1 files at r13, 16 of 22 files at r15, 1 of 2 files at r16, 5 of 5 files at r17, 4 of 4 files at r18, 5 of 5 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44218)* status: Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-02-27 21:35 UTC, sribalij approved these changes
> Reviewed 1 of 35 files at r6, 5 of 17 files at r7, 41 of 49 files at r10, 2 of 5 files at r11, 6 of 14 files at r12, 1 of 1 files at r13, 16 of 22 files at r15, 1 of 2 files at r16, 5 of 5 files at r17, 4 of 4 files at r18, 5 of 5 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44218)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-27 22:28 UTC, merged