[feat]: [CDS-53860]: create and save entity for frozen executions
harness/harness-core pull request #44264
Opened 2023-02-23 09:07 UTC by Abhishek-CDC

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-27 03:29 UTC, Abhishek-CDC commented
trigger messagecheck

2023-02-28 18:28 UTC, yogesh-chauhan requested changes

2023-02-28 18:28 UTC, yogesh-chauhan commented on 125-freeze/src/main/java/io/harness/freeze/entity/FrozenExecution.java
> +  public static List<MongoIndex> mongoIndexes() {
do we want to have some TTL on this collection so that automatic deletion happens ?

2023-02-28 18:28 UTC, yogesh-chauhan commented on 125-freeze/src/main/java/io/harness/freeze/service/impl/FrozenExecutionServiceImpl.java
> +          FrozenExecution frozenExecution1 = frozenExecutionRepository.save(frozenExecution);
nit: we can just
return frozenExecutionRepository.save(frozenExecution)

2023-03-01 09:13 UTC, Abhishek-CDC commented
*[`125-freeze/src/main/java/io/harness/freeze/entity/FrozenExecution.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/44264#-NOxWswJmzT-MowjqGRs-r3-41:-NPRRiNnCwXA72Szp1B0:bgy8kgp) ([raw file](https://github.com/harness/harness-core/blob/263ab5106be8b39c2f8177b607f250df700c315a/125-freeze/src/main/java/io/harness/freeze/entity/FrozenExecution.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we want to have some TTL on this collection so that automatic deletion happens ?
</blockquote></details>

Added for 6 months


<!-- Sent from Reviewable.io -->

2023-03-01 09:14 UTC, Abhishek-CDC commented
*[`125-freeze/src/main/java/io/harness/freeze/service/impl/FrozenExecutionServiceImpl.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/44264#-NOxWswJmzT-MowjqGRv-r3-48:-NPRRlqS-PuaeBl4A66G:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/263ab5106be8b39c2f8177b607f250df700c315a/125-freeze/src/main/java/io/harness/freeze/service/impl/FrozenExecutionServiceImpl.java#L48)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: we can just
return frozenExecutionRepository.save(frozenExecution)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-01 11:16 UTC, abhinavmittal-harness approved these changes
> Reviewed 7 of 12 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44264)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-01 16:54 UTC, yogesh-chauhan approved these changes
> Reviewed 7 of 12 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44264)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-01 16:55 UTC, merged