feat: [CCM-11377]: surfacing the worker error
harness/harness-core pull request #44278
Opened 2023-02-23 11:28 UTC by sahibaCCM

## Describe your changes
surfacing the worker error
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-02 19:20 UTC, nikunj-badjatya requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44278)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/governance/GovernanceRuleExecutionResource.java` line 191 at r2](https://reviewable.io/reviews/harness/harness-core/44278#-NPYj_uD8vzAETg9NEff:-NPYj_uD8vzAETg9NEfg:bqi22v8) ([raw file](https://github.com/harness/harness-core/blob/97dc90f0215deac1f680ae3de04ec9d280fc9202/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/governance/GovernanceRuleExecutionResource.java#L191)):*
> ```Java
>     if (ruleExecution.getExecutionStatus() == RuleExecutionStatusType.FAILED) {
>       if (ruleExecution.getErrorMessage() != null
>           && (ruleExecution.getErrorMessage().contains("UnauthorizedOperation")
> ```

imo, in worker side we are anyway taking "ClientError" (OR generic error in other cases). So in api side we can just return whatever is present in mongo. Keeping these conditions at two places will cause issues. Worker knows best about errors so we can keep all error conditions there. 

What do you think ?


<!-- Sent from Reviewable.io -->

2023-03-03 05:13 UTC, sahibaCCM commented
for the comment we are always returning the output irrespective of it contains client error or no.
In the case where the custodian is not containing ClientError the returned statement looks like 

 `   "errorMessage" : "Error in invoking : 2023-03-03 10:38:39,827: custodian.commands:ERROR invalid policy file: /tmp/38744087-e1f0-45ec-ab58-68ecf45beb35.yaml error: policy:s3-bucket-logging-disabled-list has unknown keys: filter\n2023-03-03 10:38:39,827: custodian.commands:ERROR Found 1 errors.  Exiting.\n",`

to avoid such cases either we can only send output results from worker when they contain ClientError or keep the logic we have

2023-03-07 18:13 UTC, nikunj-badjatya reviewed
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44278)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-08 00:46 UTC, nikunj-badjatya approved these changes

2023-03-08 00:49 UTC, merged