fix: [CDS-53380]: Fixing duplicate sweepingOutput exception.
harness/harness-core pull request #44286
Opened 2023-02-23 13:04 UTC by boopesh007

## Describe your changes
Ignoring duplicateKey exception in ECS 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-23 15:24 UTC, PragyeshMishra01 commented on 400-rest/src/main/java/software/wings/sm/states/EcsStateHelper.java
> +        log.error("Facing a duplicate key exception while saving sweepingOutputContext, ignoring", e);
here, does this InvalidRequestException comes only incase of duplicate key?

2023-02-23 18:37 UTC, abhinav-harness requested changes

2023-02-23 18:37 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/sm/states/EcsStateHelper.java
> +        log.error("Facing a duplicate key exception while saving sweepingOutputContext, ignoring", e);
why cant we catch a execption?

2023-02-27 04:51 UTC, sainath-b approved these changes
LGTM. @boopesh007 Make sure you test this locally and see if any NPE occurs.

2023-02-27 04:52 UTC, sainath-b submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44286)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-27 05:28 UTC, boopesh007 commented
*[`400-rest/src/main/java/software/wings/sm/states/EcsStateHelper.java` line 985 at r1](https://reviewable.io/reviews/harness/harness-core/44286#-NOyN2C1txUxX8N9jl60-r1-985:-NPGKs_X4f7oDuwyALjf:bdygk4c) ([raw file](https://github.com/harness/harness-core/blob/4e6273248a0b14b78f3010fa1c6969212beef4a5/400-rest/src/main/java/software/wings/sm/states/EcsStateHelper.java#L985)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

why cant we catch a execption?
</blockquote></details>

No valid anymore since additional logs are only being added.


<!-- Sent from Reviewable.io -->

2023-02-27 05:32 UTC, boopesh007 commented
trigger messagecheck

2023-02-27 06:39 UTC, inderschera approved these changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44286)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-27 07:18 UTC, sainath-b approved these changes

2023-02-27 07:20 UTC, sainath-b approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44286)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-27 07:21 UTC, sainath-b approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44286)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-27 07:33 UTC, PragyeshMishra01 reviewed
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44286)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-02-27 07:33 UTC, PragyeshMishra01 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44286)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-02-27 07:43 UTC, merged