feat: [PLG-1968]: Add Debezium flow for data transfer from MongoDB to TimescaleDB for ModuleLicenses
harness/harness-core pull request #44318
Opened 2023-02-24 05:08 UTC by neelam-harness

## Describe your changes
Adding Debezium flow for data transfer from ng-harness:moduleLicenses to TimescaleDB.
Note: This implementation only performs the logic for changestream and snapshotting will be done in a separate pr.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-27 22:05 UTC, neelam-harness commented
trigger ut0

2023-02-27 22:23 UTC, neelam-harness commented
trigger ut1

2023-02-27 23:05 UTC, neelam-harness commented
trigger ut3

2023-02-28 20:10 UTC, neelam-harness commented
trigger ut3, ut4

2023-02-28 22:06 UTC, neelam-harness commented
trigger ft1, ft2, checkstylecodeformat

2023-02-28 22:09 UTC, Xin-Harness requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java` line 9 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP2t0p-UvrYszfD0WH:-NPP2t0p-UvrYszfD0WI:b-z3kro6) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java#L9)):*
> ```Java
> 
> package io.harness.changestreams.common;
> ```

Shall we add owner here?
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP3EeM3BSB7xx4zYCS:-NPP3EeM3BSB7xx4zYCT:b-6x3xef) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java#L68)):*
> ```Java
>       record.set(Tables.MODULE_LICENSES.EDITION, node.get("edition").asText());
>     }
> ```

How do we support the other attribute, ex, CI related workloads, etc?


<!-- Sent from Reviewable.io -->

2023-02-28 22:21 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java` line 9 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP2t0p-UvrYszfD0WH:-NPP4GAT5tqfvH-97cN2:bsq6vth) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java#L9)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Shall we add owner here?
</blockquote></details>

This will be a common file so not sure who we should add as an owner :) any suggestions ? 
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP3EeM3BSB7xx4zYCS:-NPP4_nVDjiNMWj0XWqS:bhkcwfc) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java#L68)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

How do we support the other attribute, ex, CI related workloads, etc?
</blockquote></details>

Good point. I have tried to capture all the fields as per the ModuleLicenses collection attributes, wondering if there's a separate collection per moduleType ?



_Code snippet:_
```Java
ModuleLicense implements PersistentEntity, NGAccountAccess {
  @Id @dev.morphia.annotations.Id protected String id;
  @Trimmed @NotEmpty protected String accountIdentifier;
  @NotEmpty protected ModuleType moduleType;
  @NotEmpty protected Edition edition;
  @NotEmpty protected LicenseType licenseType;
  @NotEmpty protected LicenseStatus status;
  @NotEmpty protected long startTime;
  @NotEmpty protected long expiryTime;
  protected boolean premiumSupport;
  protected boolean selfService;
  @CreatedBy protected EmbeddedUser createdBy;
  @LastModifiedBy protected EmbeddedUser lastUpdatedBy;
  @CreatedDate protected Long createdAt;
  @LastModifiedDate protected Long lastUpdatedAt;
  protected Boolean trialExtended;
}
```


<!-- Sent from Reviewable.io -->

2023-02-28 22:33 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP3EeM3BSB7xx4zYCS:-NPP963s-FHOVvw6BmC1:b-kcd0m9) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java#L68)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Good point. I have tried to capture all the fields as per the ModuleLicenses collection attributes, wondering if there's a separate collection per moduleType ?
</blockquote></details>

For CD license type, it may have below attribute 



_Code snippet:_
```Java
@OwnedBy(HarnessTeam.GTM)
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(NON_NULL)
@Schema(name = "CDModuleLicense", description = "This contains details of the Continuous Delivery License in Harness")
public class CDModuleLicenseDTO extends ModuleLicenseDTO {
  CDLicenseType cdLicenseType;
  Integer workloads;
  Integer serviceInstances;
}
```


<!-- Sent from Reviewable.io -->

2023-02-28 23:12 UTC, neelam-harness commented
trigger ft1, ft2

2023-03-01 05:00 UTC, shalini-agr requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 13 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 411 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQWpBdDhorNWDv5gQY:-NPQWpBdDhorNWDv5gQZ:b-9ryxsn) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/config.yml#L411)):*
> ```YAML
>   timescaledbUrl: "jdbc:postgresql://localhost:5432/harness"
>   timescaledbUsername: "admin"
>   timescaledbPassword: "password"
> ```

please revert timescale enabling changes from PR
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 232 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXCar9rc8S7nSbbVo:-NPQXCar9rc8S7nSbbVp:b-f4qame) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L232)):*
> ```Java
> import com.google.common.util.concurrent.ServiceManager;
> import com.google.common.util.concurrent.ThreadFactoryBuilder;
> import com.google.inject.*;
> ```

replace * with individual imports
___
*[`120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXNmSCmBLQWyfyhlV:-NPQXNmSCmBLQWyfyhlW:b-f4qame) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java#L12)):*
> ```Java
> import static io.harness.annotations.dev.HarnessTeam.PL;
> import static io.harness.authorization.AuthorizationServiceHeader.NG_MANAGER;
> import static io.harness.eventsframework.EventsFrameworkConstants.*;
> ```

replace * with individual imports
___
*[`360-cg-manager/config.yml` line 292 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXYCL2iNuqs2WpQLH:-NPQXYCL2iNuqs2WpQLI:bhokkmn) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/360-cg-manager/config.yml#L292)):*
> ```YAML
> mongo:
>   #uri: mongodb://localhost:27017/harness
>   uri: mongodb://mongo1:30001,mongo2:30002,mongo3:30003
> ```

revert these changes
___
*[`debezium-service/config/config.yml` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXeEy7LFga_ehOjqB:-NPQXeEy7LFga_ehOjqC:b-8nvuh1) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/debezium-service/config/config.yml#L32)):*
> ```YAML
> # Please follow the naming convention for override variables for the configs
> debeziumConfigs:
>   - isEnabled: ${IS_ENABLED_PIPELINE:-false}
> ```

revert this change
___
*[`debezium-service/config/config.yml` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXgVd0b7t2XpS2RJB:-NPQXgVd0b7t2XpS2RJC:b-tqk67) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/debezium-service/config/config.yml#L81)):*
> ```YAML
>           CATrustStorePath: ${SNAPSHOT_EVENTS_FRAMEWORK_CATRUST_STORE_PATH:-/tmp/ca_trust_store}
>           CATrustStorePassword:  ${SNAPSHOT_EVENTS_FRAMEWORK_CATRUST_STORE_PASSWORD:-}
>   - isEnabled: ${IS_ENABLED_PLG:-true}
> ```

can you have false here, we can enable this in envs one by one by overriding the manifests


<!-- Sent from Reviewable.io -->

2023-03-01 15:37 UTC, ivan-83 requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 3 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSjuA-E8O66OnOUF3s:-NPSjuA-E8O66OnOUF3t:b5bxc5d) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/config.yml#L406)):*
> ```YAML
>   syncFeaturesToCF: false
> 
> enableDashboardTimescale: true
> ```

set to false
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java` line 9 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP2t0p-UvrYszfD0WH:-NPSkP5D786TPyn82Jvt:b-qjniia) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java#L9)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

This will be a common file so not sure who we should add as an owner :) any suggestions ? 
</blockquote></details>

Owner is who created the file, PLG
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSn5wt1S0fSu5P39am:-NPSn5wt1S0fSu5P39an:b3megzi) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java#L31)):*
> ```Java
>   private ExecutorService executorService =
>       Executors.newCachedThreadPool(new ThreadFactoryBuilder().setNameFormat("plg-event-consumer-%d").build());
>   // TODO: PLG-2014 change from PmsRedisConsumer to the generic interface RedisMessageConsumerTask
> ```

should we remove the comment
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 654 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSoCwm-ZpLpZoTlcDM:-NPSoCwn4PirOFrek4yX:b-vzaagj) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L654)):*
> ```Java
>   }
> 
>   private void registerPlgSdkEvents(NextGenConfiguration appConfig, Injector injector) {
> ```

Minor - we could rename registerPlgSdkEvents to registerDebeziumEvents, we don't have PLG SDK right? 



_Code quote:_
```Java
Debezium
```
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/DebeziumConsumersConfig.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSmZT12PYkMW3sgBd6:-NPSmZT12PYkMW3sgBd7:b-d42lgx) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/DebeziumConsumersConfig.java#L13)):*
> ```Java
> import lombok.Data;
> 
> // TODO: PLG-2014 This class is to be moved to generic changestreams package for re-use
> ```

should we remove this comment
___
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSml2RD8wbAHYxgVYA:-NPSml2RD8wbAHYxgVYB:b-u9p8mw) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L38)):*
> ```Java
> import lombok.extern.slf4j.Slf4j;
> 
> // TODO: PLG-2014 update PmsRedisConsumer -> RedisMessageConsumerTask for generic usage
> ```

remove comment


<!-- Sent from Reviewable.io -->

2023-03-02 08:24 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 12 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSjuA-E8O66OnOUF3s:-NPVbOb43FvrShEHsz1v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/config.yml#L406)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

set to false
</blockquote></details>

Done.



_Code quote:_
```YAML
enableDashboardTimescale
```
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java` line 9 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP2t0p-UvrYszfD0WH:-NPVbR6h1anU2x-U-MiS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java#L9)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Owner is who created the file, PLG
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSn5wt1S0fSu5P39am:-NPVbSOg4u-rbqLhRIDV:b-z5q7wc) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java#L31)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

should we remove the comment
</blockquote></details>

Added this comment for tracking this change later.
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPP3EeM3BSB7xx4zYCS:-NPVbcLg59Ok4VjExG68:b-xya0eb) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/changestreams/eventhandlers/ModuleLicensesChangeEventHandler.java#L68)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

For CD license type, it may have below attribute 
</blockquote></details>

Very good catch. Thanks for pointing it out. Added all the module specific attributes in the previously created table and updated the script. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXNmSCmBLQWyfyhlV:-NPVby7AEuRjsEsCOcCi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java#L12)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

replace * with individual imports
</blockquote></details>

Done.
___
*[`360-cg-manager/config.yml` line 292 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXYCL2iNuqs2WpQLH:-NPVcAab2NRIsVZjnvgt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/360-cg-manager/config.yml#L292)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

revert these changes
</blockquote></details>

Done.



_Code quote:_
```YAML
 mongodb://localhost:27017/harness
```
___
*[`debezium-service/config/config.yml` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXeEy7LFga_ehOjqB:-NPWNQdo3MgYz6a6UAk3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/debezium-service/config/config.yml#L32)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

revert this change
</blockquote></details>

Done.
___
*[`debezium-service/config/config.yml` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXgVd0b7t2XpS2RJB:-NPWNAK_E5tjqm5o1X8h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/debezium-service/config/config.yml#L81)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

can you have false here, we can enable this in envs one by one by overriding the manifests
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-02 08:24 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 12 file(s) to review. 3 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 411 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQWpBdDhorNWDv5gQY:-NPWPzDQ3PtlSMz4QP_5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/config.yml#L411)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

please revert timescale enabling changes from PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-02 09:16 UTC, shalini-agr submitted a review, later dismissed
> Reviewed 4 of 13 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 12 file(s) to review. 2 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-02 16:27 UTC, ivan-83 requested changes
> Reviewed 10 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 2 file(s) to review. 2 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY8bokBQCj8S_VQIPb:-NPY8bokBQCj8S_VQIPc:b-qw4yl3) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java#L14)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PLG)
> public interface RedisMessageConsumerTask extends Runnable {
> ```

Can this name be more specific? 
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY3te6CeX9m6DvoIAc:-NPY3te6CeX9m6DvoIAd:b63tsuu) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java#L28)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.PLG)
> public class PlgEventConsumerController implements Managed {
> ```

Minor: I would rename PlgEventConsumerController >> DebeziumEventConsumerController
___
*[`120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY60Om91-TcrLOu_0G:-NPY60Or0g19LcYzkN5j:bbh5kup) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java#L13)):*
> ```Java
> import static io.harness.authorization.AuthorizationServiceHeader.NG_MANAGER;
> import static io.harness.eventsframework.EventsFrameworkConstants.GIT_BRANCH_HOOK_EVENT_STREAM;
> import static io.harness.eventsframework.EventsFrameworkConstants.GIT_BRANCH_HOOK_EVENT_STREAM_MAX_TOPIC_SIZE;
> ```

You need to reformat the code here. 
___
*[`debezium-service/config/config.yml` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY7AQP0IthivusL_Kp:-NPY7AQQ8y1mRDAy0Mm0:b-188evo) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/debezium-service/config/config.yml#L81)):*
> ```YAML
>           CATrustStorePath: ${SNAPSHOT_EVENTS_FRAMEWORK_CATRUST_STORE_PATH:-/tmp/ca_trust_store}
>           CATrustStorePassword:  ${SNAPSHOT_EVENTS_FRAMEWORK_CATRUST_STORE_PASSWORD:-}
>   - isEnabled: ${IS_ENABLED_PLG:-false}
> ```

qq, should these names will be based on services or table names? Due to the fact that we can include the list of collections and that we are going to consume these properties in ng_manager I suggest giving the name service based. 


<!-- Sent from Reviewable.io -->

2023-03-02 19:37 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 2 file(s) to review. 2 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSjuA-E8O66OnOUF3s:-NPYlQOI-wvV1X_MY_74:b-7rl0kd) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/config.yml#L406)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY8bokBQCj8S_VQIPb:-NPYlUZN4UuT0sLvsSvp:baera7u) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/120-ng-manager/src/main/java/io/harness/changestreams/common/RedisMessageConsumerTask.java#L14)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can this name be more specific? 
</blockquote></details>

This is named generic so multiple concrete consumers can use the generic code without having to duplicate this task. This is an attempt to replace PMSRedisConsumer which is currently named specific but has generic code in it. 
___
*[`120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY3te6CeX9m6DvoIAc:-NPYlrSD57C6MIFtO7Hi:bfe6g8z) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/120-ng-manager/src/main/java/io/harness/changestreams/controllers/PlgEventConsumerController.java#L28)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: I would rename PlgEventConsumerController >> DebeziumEventConsumerController
</blockquote></details>

Ivan, this is a specific consumer for all things related to PLG data and not a generic DebeziumEventConsumer so naming it specifically makes more sense imho.
___
*[`debezium-service/config/config.yml` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY7AQP0IthivusL_Kp:-NPYnMRq3QZ-5Ree5kp3:b-h0l90) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/debezium-service/config/config.yml#L81)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, should these names will be based on services or table names? Due to the fact that we can include the list of collections and that we are going to consume these properties in ng_manager I suggest giving the name service based. 
</blockquote></details>

Since this changestream data from mongoDB-ngHarness flows to TimescaleDB specifically for plg and can include other collections if need be at a later point apart from moduleLicenses. I thought it makes sense to name it at a service level than at a table level. I followed the pattern of existing debeziumConfig for pipeline above. Let me know your thoughts!


<!-- Sent from Reviewable.io -->

2023-03-02 19:46 UTC, Xin-Harness reviewed
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 2 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-02 19:47 UTC, Xin-Harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-02 20:09 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318#-:-NPYwJSg9OSo5DTmmGR9:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-02 21:11 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 4. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 232 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPQXCar9rc8S7nSbbVo:-NPZ9MAK2VpuNPnZ9CnR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L232)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

replace * with individual imports
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/44318#-NPY60Om91-TcrLOu_0G:-NPZ9RyG15g3iqbdsbKc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c055f445394802b3467630a0ee9cf214ea5f6615/120-ng-manager/src/main/java/io/harness/ng/eventsframework/EventsFrameworkModule.java#L13)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

You need to reformat the code here. 
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/pms/redisConsumer/DebeziumConsumersConfig.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSmZT12PYkMW3sgBd6:-NPZ9UeN7PAd3Gr1OtB9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/DebeziumConsumersConfig.java#L13)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

should we remove this comment
</blockquote></details>

Done.
___
*[`958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/44318#-NPSml2RD8wbAHYxgVYA:-NPZ9YipC7Lit3UmIpS8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e34706e40ef0615ae6190fd363254ac6e8ad4a7/958-debezium-utils/src/main/java/io/harness/debezium/redisconsumer/DebeziumAbstractRedisConsumer.java#L38)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-02 21:12 UTC, ivan-83 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-03 17:09 UTC, shalini-agr approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-03 17:14 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318#-:-NPcSv4X4iRUoBbAxhoy:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-03 17:34 UTC, Xin-Harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-08 18:42 UTC, neelam-harness commented
trigger ut3

2023-03-09 09:16 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44318#-:-NQ4eAZ_-JWwbawlijEG:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-09 19:08 UTC, merged