feat: [DEL-5895]: Store delegate token value encrypted in DB
harness/harness-core pull request #44323
Opened 2023-02-24 06:35 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-24 21:35 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 10 file(s) to review. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateServiceTokenAuthenticatorImpl.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/44323#-NP4L9s6D3Vuko0NsObT:-NP4L9s6D3Vuko0NsObU:b-tv57iy) ([raw file](https://github.com/harness/harness-core/blob/2834c2f5acd6a2f7a1b217e459e442228f8d4079/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateServiceTokenAuthenticatorImpl.java#L267)):*
> ```Java
>     }
>     try {
>       decryptDelegateToken(encryptedJWT, delegateTokenServiceBase.getDelegateTokenValue(delegateToken));
> ```

being able to remove if-else here is great ! 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/44323#-NP4KhYOB3w0Cw8JJfu9:-NP4KhYOB3w0Cw8JJfuA:bfmp8nq) ([raw file](https://github.com/harness/harness-core/blob/2834c2f5acd6a2f7a1b217e459e442228f8d4079/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java#L39)):*
> ```Java
>   }
> 
>   public String encryptedTokenId(String accountId, String token) {
> ```

rename to 
encryptTokenValue
as it's an encryption action 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/44323#-NP4JIhnCfALvUxkODDt:-NP4JIhnCfALvUxkODDu:b-6usdju) ([raw file](https://github.com/harness/harness-core/blob/2834c2f5acd6a2f7a1b217e459e442228f8d4079/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java#L56)):*
> ```Java
>       delegateToken.setEncryptedTokenId(encrypedValue);
>       persistence.save(delegateToken);
>     }
> ```

if the token is not encrypted, we can return the token value directly after saving the encrypted id 


<!-- Sent from Reviewable.io -->

2023-02-27 05:47 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/44323#-NP4KhYOB3w0Cw8JJfu9:-NPGPDrx-zL2hxnpROp2:bl5soo0) ([raw file](https://github.com/harness/harness-core/blob/2834c2f5acd6a2f7a1b217e459e442228f8d4079/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java#L39)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

rename to 
encryptTokenValue
as it's an encryption action 
</blockquote></details>

it's token id not value, so renamed to encrypt


<!-- Sent from Reviewable.io -->

2023-02-27 05:48 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/44323#-NP4JIhnCfALvUxkODDt:-NPGPSYL3tOglfGFHaOE:b-lisig6) ([raw file](https://github.com/harness/harness-core/blob/2834c2f5acd6a2f7a1b217e459e442228f8d4079/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenServiceBase.java#L56)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

if the token is not encrypted, we can return the token value directly after saving the encrypted id 
</blockquote></details>

it wont come here if the token is not encrypted.


<!-- Sent from Reviewable.io -->

2023-02-27 16:22 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/44323#-NPHAT9AAlOwVNpYY6Vn:-NPIdy_J3_DzbpXvfyFc:b-mdlcso) ([raw file](https://github.com/harness/harness-core/blob/97513d4805de85114a338247a812253fb84e2810/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L55)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

[A non-blocking comment]:
Since we are running a background migration, I have 2 concerns here-
1. If the migration takes too long to run, the non-migrated delegate tokens will not work till that time.
2. Is there a fallback mechanism in case the migration fails for some token? 

For the other use case where we migrated api keys to global KMS, we kept the local decryption logic in code for cases when the migration is still in progress or some token fails to migrate. But, again, it depends on the use case. Please check if this makes sense for delegate tokens too.
</blockquote></details>

we rolling this change in different phases/releases, controlled by FF. In first encrypting token thru migration, second phase reading encrypted value instead of plain text(so decrypt here) and finally remove plain text value from DB(Code change-migration to delete plain text from)
The second phase will only be enabled after verifying all records in DB are migrated.

But good point on fallback mechanism, while testing locally I faced issue one due to a bug in my code, so what happened is, it created an encrypted record but failed to save the delegate token record as there are 2 different DB commits. So when next time i ran i got a duplicate record found on the encrypted record.


<!-- Sent from Reviewable.io -->

2023-02-27 20:23 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/44323#-NPJXELn7UrKFHJKJlNA:-NPJXp6J3Jbm0WLPjHYv:b-cxfu9) ([raw file](https://github.com/harness/harness-core/blob/bc4f072aa3c7d71dcecf675d8e04244aa760ce25/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L65)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

can we first check if the encrypted id exists, if not proceed with encryption 
so that the migration will be idempotent and we can run as many time whenever we see some problems 
</blockquote></details>

yes we can do


<!-- Sent from Reviewable.io -->

2023-02-27 21:49 UTC, jennyjames21 commented
trigger ut0

2023-02-27 21:49 UTC, jennyjames21 commented
trigger ut1

2023-02-27 21:49 UTC, jennyjames21 commented
trigger ut2

2023-02-27 21:49 UTC, jennyjames21 commented
trigger ut3

2023-02-27 21:49 UTC, jennyjames21 commented
trigger ut4

2023-02-27 22:40 UTC, jennyjames21 commented
CG
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/82905057/221696621-5ad018e6-0add-48e3-b1ff-2c92f8207d47.png">
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/82905057/221696775-35aa46a4-54af-4d59-9137-7131b2ea4dad.png">
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/82905057/221696840-1d8d71a2-8ca5-4778-8ae2-ecfde13d3ab9.png">
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/82905057/221696922-b58a81e2-56b3-4dae-90c8-8f69fc60c12f.png">

NG
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/82905057/221698921-60a9b9da-eeaa-4fe8-b8c2-48383f4891f8.png">
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/82905057/221698997-7bbbbae9-7575-43d7-b126-f75cbcca7be9.png">

2023-02-28 02:11 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 151 at r9](https://reviewable.io/reviews/harness/harness-core/44323#-NPKlr5o4SWz5nrTSJXX:-NPKlr5o4SWz5nrTSJXY:b-2chhcj) ([raw file](https://github.com/harness/harness-core/blob/194170c7e6a0401d41f6cfbad799828288b39dcf/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L151)):*
> ```Java
>     if (delegateToken != null) {
>       if (delegateToken.isNg()) {
>         return decodeBase64ToString(delegateToken.getValue());
> ```

TBH, i m not sure about the change here. Previously when i made the other token change, i keep the function same behavior as old way, which means, for ng it will return decoded token, for cg, it will return original token (which is not encoded anyways)

This function is used by ProvisionService.java. I don't know what it is
let me know your thoughts.

If we decide to return base64 token for ng in this function, we need to update the comments in here and in the interface file. 


<!-- Sent from Reviewable.io -->

2023-03-01 04:04 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 151 at r9](https://reviewable.io/reviews/harness/harness-core/44323#-NPKlr5o4SWz5nrTSJXX:-NPQKnEb8Hkp7be-q3-s:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/194170c7e6a0401d41f6cfbad799828288b39dcf/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L151)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

TBH, i m not sure about the change here. Previously when i made the other token change, i keep the function same behavior as old way, which means, for ng it will return decoded token, for cg, it will return original token (which is not encoded anyways)

This function is used by ProvisionService.java. I don't know what it is
let me know your thoughts.

If we decide to return base64 token for ng in this function, we need to update the comments in here and in the interface file. 
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-03-01 14:32 UTC, arpit3107 commented on 420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java
> +                                .name(UUID.randomUUID().toString())
Is it possible to use tokenName here? Maybe in future we need this info.
BTW, tokenName is already unique for an account.

2023-03-01 14:38 UTC, arpit3107 commented on 390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java
> +      log.error("Exception while migration delegate token with encrypted value", e);
Just an advice to double check these logs in prod. I had once forgot to check this log in prod and landed in a terrible situation.

2023-03-01 14:40 UTC, arpit3107 commented on 390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java
> +    log.info("The migration completed to insert encrypted delegate token values");
Also, before migration, first check the count of tokens not having encryptedID and match that count with the updated counts in the last. Sometimes there used to be a mismatch.

2023-03-01 14:41 UTC, arpit3107 commented on 390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java
> +        persistence.createQuery(DelegateToken.class, excludeAuthority).field(DelegateTokenKeys.value).exists();
Migrations should be idempotent, means it should be able to run any number of times. So add a filter of encryptedID not present.

2023-03-01 15:01 UTC, arpit3107 requested changes
> Reviewed 2 of 10 files at r1, 6 of 13 files at r5, 5 of 9 files at r6, 2 of 2 files at r8, 2 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 267 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NPSe05R9fP2KVOhWYhY:-NPSe05R9fP2KVOhWYhZ:b8wynr3) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L267)):*
> ```Java
> 
>     if (includeTokenValue) {
>       delegateTokenDetailsBuilder.value(delegateTokenEncryptDecrypt.getBase64EncodedTokenValue(delegateToken));
> ```

I think you should not modify anything here, its used for token creation api/ yaml.


<!-- Sent from Reviewable.io -->

2023-03-01 18:11 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 52 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NPGIEpyBAKUUjybm1u1-r10-52:-NPTLK7R78WVV48-o-YA:b-88c107) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L52)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Is it possible to use tokenName here? Maybe in future we need this info.
BTW, tokenName is already unique for an account.
</blockquote></details>

I think the name has to be unique here. Will two tokens in same account share same name? What we can do here is tokenName + UUID


<!-- Sent from Reviewable.io -->

2023-03-01 18:16 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 267 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NPSe05R9fP2KVOhWYhY:-NPTNVZ4CnuKQPMdRdJx:b-1mh3zl) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L267)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

I think you should not modify anything here, its used for token creation api/ yaml.
</blockquote></details>

not modifying anything here, just getting decrypted value.  Before it was delegateToken.getValue(), now fetching decrypted value from encrypted record using encrypted token recordds


<!-- Sent from Reviewable.io -->

2023-03-01 18:18 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 53 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NP17X1Tmom8tDmtUdvS-r10-53:-NPTOEj-2RvPW8QxVtEY:b6sc25p) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L53)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Just an advice to double check these logs in prod. I had once forgot to check this log in prod and landed in a terrible situation.
</blockquote></details>

not sure i got this, lets sync up on this


<!-- Sent from Reviewable.io -->

2023-03-01 22:26 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 40 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NP17X1Tmom8tDmtUdvS-r10-40:-NPUGa8aDkeeYXI_QVSw:blal38x) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L40)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Migrations should be idempotent, means it should be able to run any number of times. So add a filter of encryptedID not present.
</blockquote></details>

it tracks version in schema collection. Once completed then updates here
![image.png](https://files.reviewableusercontent.io/images/reviewable/82905057/goeRKFSE3CUHJO9DkawTIP3M/image.png)


<!-- Sent from Reviewable.io -->

2023-03-01 22:26 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/44323#-NPJXELn7UrKFHJKJlNA:-NPUHDMg-4F5FL4DU6oq:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/bc4f072aa3c7d71dcecf675d8e04244aa760ce25/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L65)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes we can do
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-03-01 22:28 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 40 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NP17X1Tmom8tDmtUdvS-r10-40:-NPUHVgz0u6VHbKwxlMl:b-8c5t6) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L40)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

it tracks version in schema collection. Once completed then updates here
![image.png](https://files.reviewableusercontent.io/images/reviewable/82905057/goeRKFSE3CUHJO9DkawTIP3M/image.png)

</blockquote></details>

adding filter for encrypted ID exists or not


<!-- Sent from Reviewable.io -->

2023-03-02 00:12 UTC, raghuAtWings commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 40 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NP17X1Tmom8tDmtUdvS-r10-40:-NPUeNJo3uShaNs2qoOp:b-rxgx7h) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L40)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

adding filter for encrypted ID exists or not
</blockquote></details>

shouldn't you have the query on where the id doesn't exist?


<!-- Sent from Reviewable.io -->

2023-03-02 00:13 UTC, raghuAtWings commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/44323#-NPJXELn7UrKFHJKJlNA:-NPUehG9BAvZJS4ORHqq:b-xyqr87) ([raw file](https://github.com/harness/harness-core/blob/bc4f072aa3c7d71dcecf675d8e04244aa760ce25/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L65)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

updated
</blockquote></details>

also do not use asList(). write a iterator and iterate


<!-- Sent from Reviewable.io -->

2023-03-02 00:17 UTC, raghuAtWings commented
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 52 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NPGIEpyBAKUUjybm1u1-r10-52:-NPUfG5y4gMJWdsw9-hW:b-76j2vl) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L52)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

I think the name has to be unique here. Will two tokens in same account share same name? What we can do here is tokenName + UUID
</blockquote></details>

don't put UUId, since tokens can be across project/org i think its a good idea to put tokenName + UUID


<!-- Sent from Reviewable.io -->

2023-03-02 00:17 UTC, raghuAtWings commented
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 52 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NPGIEpyBAKUUjybm1u1-r10-52:-NPUfX6LBL-1AvtMOzzT:b-ag9yh8) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L52)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't put UUId, since tokens can be across project/org i think its a good idea to put tokenName + UUID
</blockquote></details>

on a second thought may be we can put tokenName + org + project and make sure that we put unique index on token name


<!-- Sent from Reviewable.io -->

2023-03-02 00:19 UTC, raghuAtWings requested changes
> Reviewed 2 of 10 files at r1, 5 of 13 files at r5, 4 of 9 files at r6, 1 of 2 files at r8, 1 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 2 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-02 01:15 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 52 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NPGIEpyBAKUUjybm1u1-r10-52:-NPUoIpK0UuCQxsmcvSy:bnd77x6) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L52)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

on a second thought may be we can put tokenName + org + project and make sure that we put unique index on token name
</blockquote></details>

we dont have that data in delegateToken.  
![image.png](https://files.reviewableusercontent.io/images/reviewable/82905057/AZ7z3qZrDNDmgiq9VTuPqz_-/image.png)


<!-- Sent from Reviewable.io -->

2023-03-02 05:56 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 40 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NP17X1Tmom8tDmtUdvS-r10-40:-NPVtCM7DqDIbWr-Qiap:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L40)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

shouldn't you have the query on where the id doesn't exist?
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-03-02 05:56 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/44323#-NPJXELn7UrKFHJKJlNA:-NPVtFtw7gIdFxmienpp:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/bc4f072aa3c7d71dcecf675d8e04244aa760ce25/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L65)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

also do not use asList(). write a iterator and iterate
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-03-02 08:53 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 55 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NP17X1Tmom8tDmtUdvS-r10-55:-NPWWiHo9MwX4qgnH1vB:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L55)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Also, before migration, first check the count of tokens not having encryptedID and match that count with the updated counts in the last. Sometimes there used to be a mismatch.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-03-02 15:23 UTC, arpit3107 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 9 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 52 at r10](https://reviewable.io/reviews/harness/harness-core/44323#-NPGIEpyBAKUUjybm1u1-r10-52:-NPXuZnjBKxxrqxcRRAc:b-hqp5gr) ([raw file](https://github.com/harness/harness-core/blob/de485338f2c939a168446f5d956d910d90e7c0b6/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L52)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

we dont have that data in delegateToken.  
![image.png](https://files.reviewableusercontent.io/images/reviewable/82905057/AZ7z3qZrDNDmgiq9VTuPqz_-/image.png)


</blockquote></details>

We already have unique index on tokenName:

CompoundMongoIndex.builder()
                 .field(DelegateTokenKeys.accountId)
                 .field(DelegateTokenKeys.name)
                 .unique(true)
                 .name("byAccountAndName")
                 .build())

Jenny owner (org/project) should be there if the token is not an account level.

private DelegateEntityOwner owner;


<!-- Sent from Reviewable.io -->

2023-03-02 20:08 UTC, xingchi-jin reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 9 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 81 at r17](https://reviewable.io/reviews/harness/harness-core/44323#-NPYw8XU6yc-y4Wsno2Z:-NPYw8XU6yc-y4Wsno2_:b-dt465d) ([raw file](https://github.com/harness/harness-core/blob/b85ca540c9e80fbc5d685182ba359d25d556da22/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L81)):*
> ```Java
>           tokenIdentifier = String.format("%s_%s_%s", delegateToken.getName(), orgId, projectId);
>         }
>         String encryptedTokenId = delegateTokenEncryptDecrypt.encrypt(
> ```

will you do the check (id exists) before encryption ? 


<!-- Sent from Reviewable.io -->

2023-03-02 20:53 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 81 at r17](https://reviewable.io/reviews/harness/harness-core/44323#-NPYw8XU6yc-y4Wsno2Z:-NPZ5BXF43VvZEfhi-yz:b-3bzu3d) ([raw file](https://github.com/harness/harness-core/blob/b85ca540c9e80fbc5d685182ba359d25d556da22/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L81)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

will you do the check (id exists) before encryption ? 
</blockquote></details>

im doing in migration query itself
 Query<DelegateToken> query = persistence.createQuery(DelegateToken.class, excludeAuthority)
                                     .field(DelegateTokenKeys.value)
                                     .exists()
                                     .field(DelegateTokenKeys.encryptedTokenId)
                                     .doesNotExist();


<!-- Sent from Reviewable.io -->

2023-03-03 06:03 UTC, arpit3107 approved these changes

2023-03-03 15:28 UTC, jennyjames21 commented
trigger messagecheck

2023-03-03 17:45 UTC, raghuAtWings submitted a review, later dismissed
> Reviewed 2 of 4 files at r13, 3 of 4 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-03 23:20 UTC, xingchi-jin submitted a review, later dismissed
> Reviewed 2 of 10 files at r1, 3 of 13 files at r5, 4 of 9 files at r6, 1 of 2 files at r8, 2 of 4 files at r13, 2 of 4 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-06 09:16 UTC, AnupamIO approved these changes
> Reviewed 2 of 10 files at r1, 3 of 13 files at r5, 4 of 9 files at r6, 1 of 2 files at r8, 2 of 4 files at r13, 2 of 4 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-06 19:30 UTC, xingchi-jin commented
let's merge it ?

2023-03-07 05:31 UTC, tiwaritejas submitted a review, later dismissed
> Reviewed 1 of 2 files at r8, 2 of 4 files at r13, 2 of 4 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: Some of the checks are too old. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-07 12:57 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 42 at r18](https://reviewable.io/reviews/harness/harness-core/44323#-NPw7sRw-W6il0OKnKgF:-NPw7sRw-W6il0OKnKgG:b-o9aeol) ([raw file](https://github.com/harness/harness-core/blob/5194b931124a0092ede97857431b442554123394/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L42)):*
> ```Java
>   // this flow doesn't need to decodeBase64, it used for to display token in UI or yaml
>   public String getBase64EncodedTokenValue(DelegateToken delegateToken) {
>     if (featureFlagService.isEnabled(FeatureName.READ_ENCRYPTED_DELEGATE_TOKEN, delegateToken.getAccountId())) {
> ```

as this FF will be enabled for all accounts going ahead, should we have reverse flag then, something like: READ_UNENCRYPTED_DATA which will be by default disabled, we will enable only in case of any issue. 
I remember FF creates issue when it's linked to too many accounts, that's one of the reason we removed FF USE_IMMUTABLE_DELEGATE because it was enabled for a lot of acconts.


<!-- Sent from Reviewable.io -->

2023-03-07 13:56 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 60 at r18](https://reviewable.io/reviews/harness/harness-core/44323#-NPwLzUR2oTruEDmNMR1:-NPwLzUR2oTruEDmNMR2:b-nhna5m) ([raw file](https://github.com/harness/harness-core/blob/5194b931124a0092ede97857431b442554123394/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L60)):*
> ```Java
>   }
> 
>   public String decrypt(DelegateToken delegateToken) {
> ```

minor: we can make this function private ?


<!-- Sent from Reviewable.io -->

2023-03-07 16:01 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java` line 208 at r18](https://reviewable.io/reviews/harness/harness-core/44323#-NPwlrigDzdkeLqngN5c:-NPwlrigDzdkeLqngN5d:b-zeu8tt) ([raw file](https://github.com/harness/harness-core/blob/5194b931124a0092ede97857431b442554123394/400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java#L208)):*
> ```Java
>         try {
>           decryptDelegateAuthV2Token(
>               accountId, tokenString, delegateTokenEncryptDecrypt.getDelegateTokenValue(delegateToken));
> ```

* non blocking comment *
Thinking aloud: Should we also cache value of: delegateTokenEncryptDecrypt.getDelegateTokenValue(delegateToken), 
- we can use delegateTokenCache itself, key will remain same and for value, I think we can either extend DelegateToken or create a fresh class having required fields from DelegateToken class and one more field decryptedDelegateToken
- This will help to one db call to cg-manager and in DMS we will save one network call.

What do you think ?


<!-- Sent from Reviewable.io -->

2023-03-07 21:01 UTC, xingchi-jin commented
need to rebase develop

2023-03-10 02:18 UTC, xingchi-jin approved these changes
> Reviewed 4 of 4 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-10 04:46 UTC, jennyjames21 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 2. unresolved discussions. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java` line 42 at r18](https://reviewable.io/reviews/harness/harness-core/44323#-NPw7sRw-W6il0OKnKgF:-NQ8psJu3aZNkI-uwrNB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5194b931124a0092ede97857431b442554123394/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateTokenEncryptDecrypt.java#L42)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

as this FF will be enabled for all accounts going ahead, should we have reverse flag then, something like: READ_UNENCRYPTED_DATA which will be by default disabled, we will enable only in case of any issue. 
I remember FF creates issue when it's linked to too many accounts, that's one of the reason we removed FF USE_IMMUTABLE_DELEGATE because it was enabled for a lot of acconts.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-10 05:21 UTC, raghuAtWings approved these changes
> Reviewed 4 of 4 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-10 05:22 UTC, raghuAtWings approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-10 05:24 UTC, raghuAtWings commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/44323#-NPJXELn7UrKFHJKJlNA:-NQ8ydDH4qtyaOzG5ORo:bb7efny) ([raw file](https://github.com/harness/harness-core/blob/bc4f072aa3c7d71dcecf675d8e04244aa760ce25/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L65)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

updated
</blockquote></details>

cool


<!-- Sent from Reviewable.io -->

2023-03-10 05:25 UTC, jennyjames21 commented
*[`390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/44323#-NPJXELn7UrKFHJKJlNA:-NQ8ygh321cIEEfxd7Ch:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bc4f072aa3c7d71dcecf675d8e04244aa760ce25/390-db-migration/src/main/java/io/harness/migrations/all/EncryptDelegateTokenMigration.java#L65)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

cool
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-10 05:25 UTC, raghuAtWings approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323#-:-NQ8yi8T5smqDKNFcsX5:bnfp4nl)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-10 05:28 UTC, xingchi-jin approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-10 05:33 UTC, AnupamIO approved these changes
> Reviewed 1 of 4 files at r19.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44323)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-10 05:33 UTC, merged