feat: [CDS-53545]: v1 EOL banner APIs
harness/harness-core pull request #44368
Opened 2023-02-25 18:03 UTC by hingerabhinav

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-28 12:57 UTC, yogesh-chauhan requested changes

2023-02-28 12:57 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/resources/EOLBannerResource.java
> +@Api("/eol-banner")
lets use service v1 prefix here

2023-02-28 13:01 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java
> +            accountId, requestDTO.getOrgIdentifier(), requestDTO.getProjectIdentifier(), null, null, null));
Lets update pipeline service client

2023-02-28 13:02 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java
> +                    false))
lets check for cache here

2023-02-28 13:05 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java
> +    ArrayNode stageArrayNode = (ArrayNode) pipelineYamlField.getNode().getField("stages").getNode().getCurrJsonNode();
can we check for null getField("stages")

2023-02-28 13:06 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java
> +  private boolean checkStageNode(@NonNull EOLBannerRequestDTO requestDto, @NonNull String accountId,
can we call it isV1Stage ?

2023-02-28 13:06 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java
> +                TemplateApplyRequestDTO.builder().originalEntityYaml(stageYaml).checkForAccess(false).build(), false))
cache

2023-02-28 13:08 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java
> +    DeploymentStageConfig deploymentStageConfig = getDeploymentStageConfig(stageYaml);
can we just use getNode or getField here to decide v1

2023-02-28 13:09 UTC, yogesh-chauhan commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/service/dto/ServiceResponseDTO.java
> +  @Schema(hidden = true) boolean newVersion;
lets just call it v2Service ?

2023-03-01 12:01 UTC, hingerabhinav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44368)* status: 11 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pb-r1-71:-NPS1gqnDQjmtRASYysK:bx84fui) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java#L71)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets update pipeline service client
</blockquote></details>

Done. Tested w/ remote pipelines, pipeline templates and stage templates 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pb-r1-90:-NPS1mZg6RlcdCnhBQ7w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java#L90)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets check for cache here
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pb-r1-98:-NPS1oqe0n6HxwQT8iWH:bbjuibk) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java#L98)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we check for null getField("stages")
</blockquote></details>

All pipelines need to have stages. We're good here. I've added null checks where reqd.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pb-r1-139:-NPS1vrzA2V1SUl1B9DM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java#L139)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we call it isV1Stage ?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pb-r1-169:-NPS1wNf4XcjfdAkwCe8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java#L169)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

cache
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pb-r1-188:-NPS1xSq6MVi3ePIjazl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/EOLBannerService.java#L188)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we just use getNode or getField here to decide v1
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/resources/EOLBannerResource.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pe-r1-39:-NPS1zlE4SVVA9_LnSBf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/resources/EOLBannerResource.java#L39)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets use service v1 prefix here
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/resources/EOLBannerResource.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NPH1QUd94yz9q0tJ4pe-r1-49:-NPS2-0N-inY4f-Ju4F-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/120-ng-manager/src/main/java/io/harness/ng/core/eolbanner/resources/EOLBannerResource.java#L49)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets hide this resource
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/service/dto/ServiceResponseDTO.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/44368#-NP8jcK_d9YJ0lLEeE_Z-r1-38:-NPS20g77rZUF4Qc9TPs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/debeda3a881144543f4272ac13f6661ba590aeaf/960-ng-core-beans/src/main/java/io/harness/ng/core/service/dto/ServiceResponseDTO.java#L38)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets just call it v2Service ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-01 13:24 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/44368#-NPSL46J7qSRr3QGWJNg:-NPSL46K5D4Aexkf_5Qp:bpgm0e8) ([raw file](https://github.com/harness/harness-core/blob/022c32fc96de0cb7312dd0a602dcf3534a8a1a2d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L76)):*
> ```Java
>         serviceResponseDTO.setV2Service(true);
>       }
>     }
> ```

can we do this
```
if (includeVersionInfo && serviceEntity.getType() != null) {
      serviceResponseDTO.setV2Service(true);
    }
```


<!-- Sent from Reviewable.io -->

2023-03-01 13:24 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 2 of 8 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44368)* status: 11 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-01 16:44 UTC, hingerabhinav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44368)* status: 11 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/44368#-NPSL46J7qSRr3QGWJNg:-NPT2pbOBGVpTv0nnw03:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/022c32fc96de0cb7312dd0a602dcf3534a8a1a2d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L76)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we do this
```
if (includeVersionInfo && serviceEntity.getType() != null) {
      serviceResponseDTO.setV2Service(true);
    }
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-01 16:52 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44368)* status: 11 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-01 18:55 UTC, mohitg0795 approved these changes
> Reviewed 2 of 8 files at r1, 7 of 9 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44368)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-01 19:17 UTC, merged