[feat]: [PIE-7218]: Sending NodeExecutionEvents to AuditService
harness/harness-core pull request #44374
Opened 2023-02-26 17:45 UTC by senjucanon2

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-27 13:14 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-YRg3wxdNc7RedPU:-NPI-YRh97EuwyT1Ab8q:b-gahzn) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L30)):*
> ```Java
> @NoArgsConstructor
> public class NodeExecutionEvent implements Event {
>   String accountIdentifier;
> ```

There's a scope class that we can use. It has all the 3 fields account, org and project. It can be used in methods as well, just a bit more convenient to use it.


<!-- Sent from Reviewable.io -->

2023-02-27 13:16 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-x3a6KovVN6X9Z8V:-NPI-x3a6KovVN6X9Z8W:budcv3f) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L38)):*
> ```Java
>   private Status status;
>   private Long startTs;
>   private Long endTs;
> ```

Any specific reason to use Long here instead of long? If not, then lets use long.


<!-- Sent from Reviewable.io -->

2023-02-27 13:16 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI06-t2ut-f0rCY-ih:-NPI06-t2ut-f0rCY-ii:ba1976f) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L54)):*
> ```Java
>   @Override
>   public ResourceScope getResourceScope() {
>     return new ProjectScope(accountIdentifier, orgIdentifier, projectIdentifier);
> ```

this is same as parent, so if we aren't overriding any behaviour, lets use it from parent only.


<!-- Sent from Reviewable.io -->

2023-02-27 13:17 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0D8y9xvBSgJNqXga:-NPI0D8y9xvBSgJNqXgb:b-ua6yqc) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L60)):*
> ```Java
>   @Override
>   public Resource getResource() {
>     Map<String, String> labels = new HashMap<>();
> ```

exactly same as parent. If no changes, then lets not implement this method.


<!-- Sent from Reviewable.io -->

2023-02-27 13:18 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0McO9N4eybZKimq-:-NPI0McO9N4eybZKimq0:bks8pt6) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L29)):*
> ```Java
> @Getter
> @NoArgsConstructor
> public class NodeExecutionEvent implements Event {
> ```

Looking at other code pieces, it seems this is more like a parent class for all types of execution events. If yes, then lets make it abstract, implement all required methods and leave the ones that will be forced for child classes to implement.


<!-- Sent from Reviewable.io -->

2023-02-27 13:19 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0gQ565S6MBtRsKkG:-NPI0gQ565S6MBtRsKkH:b8vksar) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L55)):*
> ```Java
>                                 .build();
>     return auditClientService.publishAudit(auditEntry, globalContext);
>   }
> ```

blank line missing.


<!-- Sent from Reviewable.io -->

2023-02-27 13:19 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0n260mCZ8YYeZ7S_:-NPI0n260mCZ8YYeZ7Sa:bovsp72) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L110)):*
> ```Java
>       }
>     } catch (IOException ex) {
>       return false;
> ```

log exception


<!-- Sent from Reviewable.io -->

2023-02-27 13:20 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0pX51u-iHHjyCxys:-NPI0pX51u-iHHjyCxyt:b-t5mp3n) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L107)):*
> ```Java
>           return handleStageEndEvent(outboxEvent);
>         default:
>           return false;
> ```

why would default return false? Also this is something that would be unexpected I guess, so we should log the type of event here


<!-- Sent from Reviewable.io -->

2023-02-27 13:20 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0vJZ0Fgu4IRk7zdt:-NPI0vJZ0Fgu4IRk7zdu:b8vksar) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L80)):*
> ```Java
>                                 .build();
>     return auditClientService.publishAudit(auditEntry, globalContext);
>   }
> ```

blank line missing.


<!-- Sent from Reviewable.io -->

2023-02-27 13:20 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI1-qnEnd7d2W5mw17:-NPI1-qnEnd7d2W5mw18:b-5pnkfi) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L44)):*
> ```Java
>   }
> 
>   private boolean handlePipelineStartEvent(OutboxEvent outboxEvent) throws JsonProcessingException {
> ```

All of the handlers in this class are almost identical. Why are we duplicating the code and not making it modular enough?


<!-- Sent from Reviewable.io -->

2023-02-28 05:12 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0McO9N4eybZKimq-:-NPLQmpw9fEkhqn-fbgK:blzgntp) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Looking at other code pieces, it seems this is more like a parent class for all types of execution events. If yes, then lets make it abstract, implement all required methods and leave the ones that will be forced for child classes to implement.
</blockquote></details>

Yes, it should be abstract.


<!-- Sent from Reviewable.io -->

2023-02-28 05:13 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-YRg3wxdNc7RedPU:-NPLQsoo2zeP24r_tYWB:bf900vw) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

There's a scope class that we can use. It has all the 3 fields account, org and project. It can be used in methods as well, just a bit more convenient to use it.
</blockquote></details>

Execution event will always be at project level. Not sure, how does scope class help here?


<!-- Sent from Reviewable.io -->

2023-02-28 05:13 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0D8y9xvBSgJNqXga:-NPLREVO2IspPjyK7Kwm:b32v57) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L60)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

exactly same as parent. If no changes, then lets not implement this method.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-02-28 05:14 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0pX51u-iHHjyCxys:-NPLRJaYDD-Fysz7icbu:b-69tfqa) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L107)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why would default return false? Also this is something that would be unexpected I guess, so we should log the type of event here
</blockquote></details>

Yes, additional logging is required and it should return true otherwise we would be processing the outbox event again and again


<!-- Sent from Reviewable.io -->

2023-02-28 05:15 UTC, sahilhindwani-harness commented
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLRV3O7ixTCzy5ZVEc:-NPLRV3O7ixTCzy5ZVEd:b-xdtims) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java#L39)):*
> ```Java
>   // SLO Event
>   ERROR_BUDGET_RESET,
>   START,
> ```

nit: Add a comment that these are execution actions


<!-- Sent from Reviewable.io -->

2023-02-28 05:15 UTC, sahilhindwani-harness requested changes
> Reviewed 6 of 11 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-02-28 06:24 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-YRg3wxdNc7RedPU:-NPLfILJ-9n_JOxxpcnv:bnmreoy) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L30)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Execution event will always be at project level. Not sure, how does scope class help here?
</blockquote></details>

@mohitg0795 it is a well thought idea for smooth implementation but the meaning will go vague as per design. These 3 fields are needed as separate fields for audit logs, using a wrapper on them collectively(such as using Scope Class) will mean as if they combined mean something but this is not that case here. Ex: For an org level scope we have projIdentifier as null but here projIdentifier can never be null as far as executions are considered. Hence i agree with Sahil here. BTW a well thought suggestion.


<!-- Sent from Reviewable.io -->

2023-02-28 06:34 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-YRg3wxdNc7RedPU:-NPLiLkq5L1w9s3_i6yt:bsxn4mv) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L30)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

@mohitg0795 it is a well thought idea for smooth implementation but the meaning will go vague as per design. These 3 fields are needed as separate fields for audit logs, using a wrapper on them collectively(such as using Scope Class) will mean as if they combined mean something but this is not that case here. Ex: For an org level scope we have projIdentifier as null but here projIdentifier can never be null as far as executions are considered. Hence i agree with Sahil here. BTW a well thought suggestion.
</blockquote></details>

Scope class is just encapsulation of the 3 fields : account, org and project into a class object. Its just more convenient to use it everywhere as a single object rather than sending 3 params everywhere separately. There are no side-effects, its a choice to be done from coding perspective and nothing else.

@senjucanon2 The logic that you're providing doesn't stand correct in this case. These 3 fields don't have any relation to each other until enforced (which is the case right now).


<!-- Sent from Reviewable.io -->

2023-02-28 06:40 UTC, archit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 13 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLj_cb7B8rh_pOsQ9K:-NPLj_cb7B8rh_pOsQ9L:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java#L63)):*
> ```Java
>         .type(ResourceTypeConstants.NODE_EXECUTION)
>         .labels(labels)
>         .build();
> ```

same as above



_Code quote:_
```Java
  @JsonIgnore
  @Override
  public ResourceScope getResourceScope() {
    return new ProjectScope(accountIdentifier, orgIdentifier, projectIdentifier);
  }

  @JsonIgnore
  @Override
  public Resource getResource() {
    Map<String, String> labels = new HashMap<>();
    labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, pipelineIdentifier);
    return Resource.builder()
        .identifier(stageIdentifier)
        .type(ResourceTypeConstants.NODE_EXECUTION)
        .labels(labels)
        .build();
  }
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjb53CMf9pZocGiTL:-NPLjb53CMf9pZocGiTM:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java#L62)):*
> ```Java
>         .labels(labels)
>         .build();
>   }
> ```

same as above



_Code quote:_
```Java
  @JsonIgnore
  @Override
  public ResourceScope getResourceScope() {
    return new ProjectScope(accountIdentifier, orgIdentifier, projectIdentifier);
  }

  @JsonIgnore
  @Override
  public Resource getResource() {
    Map<String, String> labels = new HashMap<>();
    labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, pipelineIdentifier);
    return Resource.builder()
        .identifier(stageIdentifier)
        .type(ResourceTypeConstants.NODE_EXECUTION)
        .labels(labels)
        .build();
  }
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjgV9CeFTxXhPCI-V:-NPLjgV9CeFTxXhPCI-W:b98yys0) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L34)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @Singleton
> public class NodeExecutionOutboxEventHandler implements OutboxEventHandler {
> ```

add comments to handler what it is used for
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0pX51u-iHHjyCxys:-NPLjs7h2JTbkF1ZhIWL:b32v57) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L107)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Yes, additional logging is required and it should return true otherwise we would be processing the outbox event again and again
</blockquote></details>

+1
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0n260mCZ8YYeZ7S_:-NPLjt3F1kIoHlZNuvfN:b32v57) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L110)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log exception
</blockquote></details>

+1
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionOutboxEvents.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjERU26peRdwMDTve:-NPLjERU26peRdwMDTvf:b-9lqm6v) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionOutboxEvents.java#L14)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class NodeExecutionOutboxEvents {
> ```

final class
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjWRPE0mA8UrpdCJg:-NPLjWRPE0mA8UrpdCJh:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java#L62)):*
> ```Java
>         .labels(labels)
>         .build();
>   }
> ```

same as above



_Code quote:_
```Java
  @JsonIgnore
  @Override
  public ResourceScope getResourceScope() {
    return new ProjectScope(accountIdentifier, orgIdentifier, projectIdentifier);
  }

  @JsonIgnore
  @Override
  public Resource getResource() {
    Map<String, String> labels = new HashMap<>();
    labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, pipelineIdentifier);
    return Resource.builder()
        .identifier(pipelineIdentifier)
        .type(ResourceTypeConstants.NODE_EXECUTION)
        .labels(labels)
        .build();
  }
```


<!-- Sent from Reviewable.io -->

2023-02-28 08:17 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 13 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI1-qnEnd7d2W5mw17:-NPM3nXi5MuF9oI78gQR:b-3f2ora) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

All of the handlers in this class are almost identical. Why are we duplicating the code and not making it modular enough?
</blockquote></details>

It is one of the first pR that will be as part of AuditEvents, in next 2 PRs , methods will not be same , i just wnated to put a framework level code before.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0gQ565S6MBtRsKkG:-NPM40p_BI1L-Oop53WW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0vJZ0Fgu4IRk7zdt:-NPM41BVB6aB_Hykt-6S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L80)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0pX51u-iHHjyCxys:-NPM42Q-8BZ6gVcBFPqM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L107)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0n260mCZ8YYeZ7S_:-NPM42pw801HC4fJttxE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L110)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLRV3O7ixTCzy5ZVEc:-NPM43jg5d1-y4O9ADx5:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java#L39)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Add a comment that these are execution actions
</blockquote></details>

Done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0McO9N4eybZKimq-:-NPM3gWjB83mt_gwhoIb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L29)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Yes, it should be abstract.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-YRg3wxdNc7RedPU:-NPM47trB_SH_hRQhIqX:b-rds4hc) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Scope class is just encapsulation of the 3 fields : account, org and project into a class object. Its just more convenient to use it everywhere as a single object rather than sending 3 params everywhere separately. There are no side-effects, its a choice to be done from coding perspective and nothing else.

@senjucanon2 The logic that you're providing doesn't stand correct in this case. These 3 fields don't have any relation to each other until enforced (which is the case right now).
</blockquote></details>

I think scope is not just encapsulation of 3 fields, it itself has meaning like connectors/secrets with different level of scopes.
In my use case these 3 fields do not have any relation and nor they mean something if combined that's why not using scope here. In future some dev who may have worked with secrets may look at my DB audit record and seeing scope in it may think it has some parallels with the behaviour shown by connectors/secrets in terms of scope, to avoid this i think we should avoid scope here, anyway please provide your call.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-x3a6KovVN6X9Z8V:-NPM3iOk5MzA0-hQpwTg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Any specific reason to use Long here instead of long? If not, then lets use long.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI06-t2ut-f0rCY-ih:-NPM3jiRB6UKbVfyVo85:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L54)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this is same as parent, so if we aren't overriding any behaviour, lets use it from parent only.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0D8y9xvBSgJNqXga:-NPM3kEk33B_KQTYXs3N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L60)):*
<details><summary><i>Previously, sahilhindwani [...]

2023-02-28 08:22 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-YRg3wxdNc7RedPU:-NPM67x0-pkAc1s2L5wy:b-j73ozl) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L30)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

I think scope is not just encapsulation of 3 fields, it itself has meaning like connectors/secrets with different level of scopes.
In my use case these 3 fields do not have any relation and nor they mean something if combined that's why not using scope here. In future some dev who may have worked with secrets may look at my DB audit record and seeing scope in it may think it has some parallels with the behaviour shown by connectors/secrets in terms of scope, to avoid this i think we should avoid scope here, anyway please provide your call.
</blockquote></details>

You're not getting the point here and getting confused. Please schedule a call to close on it.


<!-- Sent from Reviewable.io -->

2023-02-28 10:24 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 13 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLj_cb7B8rh_pOsQ9K:-NPMY6QdCw95y__iRBcW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjb53CMf9pZocGiTL:-NPMY71a2X_wbtYLkGio:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjgV9CeFTxXhPCI-V:-NPMY7gIC9dILaTLcpZ8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments to handler what it is used for
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionOutboxEvents.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjERU26peRdwMDTve:-NPMWr7f87ESxklsDbSU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionOutboxEvents.java#L14)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

final class
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjWRPE0mA8UrpdCJg:-NPMY5j87W2IUHZ2AhxT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 17:56 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPO9gCB4GLoCFN47Ntp:-NPO9gCB4GLoCFN47Ntq:bnvero9) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L40)):*
> ```Java
>   private long endTs;
> 
>   public PipelineEndEvent(String orgIdentifier, String accountIdentifier, String projectIdentifier,
> ```

ordering of identifiers is not correct logically, lets fix it.



_Code quote:_
```Java
String orgIdentifier, String accountIdentifier, String projectIdentifier,
```


<!-- Sent from Reviewable.io -->

2023-02-28 17:59 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI-YRg3wxdNc7RedPU:-NPOATBN-24dWiO7NJQj:bi782lb) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

You're not getting the point here and getting confused. Please schedule a call to close on it.
</blockquote></details>

Discussed and finalized that its a subjective call, so we can go ahead with whats done at the moment.


<!-- Sent from Reviewable.io -->

2023-02-28 18:00 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPOAdGSE2YV2ShTwoQo:-NPOAdGSE2YV2ShTwoQp:b-fbbf6p) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L43)):*
> ```Java
>   @JsonIgnore
>   @Override
>   public ResourceScope getResourceScope() {
> ```

this shouldn't be overridden, so should be made final.


<!-- Sent from Reviewable.io -->

2023-02-28 18:01 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI06-t2ut-f0rCY-ih:-NPOAqms4V4xrdHRbHdY:b-o54qbx) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L54)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This needs to be addressed.


<!-- Sent from Reviewable.io -->

2023-02-28 18:03 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPOBCJl7oD0IAZ2g_7a:-NPOBCJl7oD0IAZ2g_7b:b-scy5uj) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L62)):*
> ```Java
>     Map<String, String> labels = new HashMap<>();
>     labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, pipelineIdentifier);
>     return Resource.builder()
> ```

This can be made better by use of common parent class method that can be used by all child classes with only required behaviour change.


<!-- Sent from Reviewable.io -->

2023-02-28 18:06 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI1-qnEnd7d2W5mw17:-NPOBzxyE9XD8R5_sbEh:bpxfguz) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L44)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

It is one of the first pR that will be as part of AuditEvents, in next 2 PRs , methods will not be same , i just wnated to put a framework level code before.
</blockquote></details>

As discussed, this will be modularized.


<!-- Sent from Reviewable.io -->

2023-02-28 18:08 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0pX51u-iHHjyCxys:-NPOCW425E-G9z8WPvj9:bb4xwpq) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L107)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As discussed, this needs to be handled. Logging and correct handling is missing.


<!-- Sent from Reviewable.io -->

2023-02-28 18:11 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 114 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPOD4434gyz6lKXaD0G:-NPOD4434gyz6lKXaD0H:baxgepx) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L114)):*
> ```Java
>       }
>     } catch (IOException ex) {
>       log.error(String.format("Unexpected error occurred during handling of event", ex));
> ```

We should add details about the event that failed in the log.


<!-- Sent from Reviewable.io -->

2023-02-28 18:14 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPODlfK8YrfKRMtVomr:-NPODlfK8YrfKRMtVoms:b-23q2vz) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L113)):*
> ```Java
>           return false;
>       }
>     } catch (IOException ex) {
> ```

change it to Exception class to handle all types of exceptions unless we are going to take a specific action on IOException.


<!-- Sent from Reviewable.io -->

2023-03-01 05:00 UTC, archit-harness requested changes
> Reviewed 2 of 11 files at r1, 1 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 11 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLj_cb7B8rh_pOsQ9K:-NPQX_mg927jVrWSO9Yj:b1arjer) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java#L63)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i dont see impl changes
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjb53CMf9pZocGiTL:-NPQXbUQ5SSRRHjp0Yj5:b-v4oabl) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java#L62)):*
> i dont see impl changes
i dont see impl changes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjgV9CeFTxXhPCI-V:-NPQXcrk0TGfPgxeVe0I:b1arjer) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L34)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i dont see impl changes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0n260mCZ8YYeZ7S_:-NPQXifK82wHhdOkeiwk:b1arjer) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L110)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i dont see impl changes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPODlfK8YrfKRMtVomr:-NPQXgfXEF-9l6xO3ofJ:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L113)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

change it to Exception class to handle all types of exceptions unless we are going to take a specific action on IOException.
</blockquote></details>

+1
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPO9gCB4GLoCFN47Ntp:-NPQXUF94C3i-UUQzski:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

ordering of identifiers is not correct logically, lets fix it.
</blockquote></details>

+1
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjWRPE0mA8UrpdCJg:-NPQXYtK9tna81SGzHMQ:bfkqb1r) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java#L62)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i dont see it to be done


<!-- Sent from Reviewable.io -->

2023-03-01 07:15 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 11 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLj_cb7B8rh_pOsQ9K:-NPQwvdP9W857PoGNUKA:bgjmv9) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageEndEvent.java#L63)):*
> By mistake i addressed these in the 2nd PR: will do an extra commit here also
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjb53CMf9pZocGiTL:-NPQwwc97OYHVQVpUMf4:bexb1hj) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/StageStartEvent.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

> i dont see impl changes
i dont see impl changes
</blockquote></details>

By mistake i addressed these in the 2nd PR: will do an extra commit here also
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjgV9CeFTxXhPCI-V:-NPQxOH25NHJi21pL-Yd:bgjmv9) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L34)):*
> By mistake i addressed these in the 2nd PR: will do an extra commit here also
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI1-qnEnd7d2W5mw17:-NPQxWPM3oqbG7WDYzG9:bl0d6q9) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

As discussed, this will be modularized.
</blockquote></details>

This i will do in the 2nd PR, it is on the way will put it for review today, as will uneccessarily generate merge conflicts with my other branch. So Please ignore this for once.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0n260mCZ8YYeZ7S_:-NPR0N-u0N3DvsneOB6o:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L110)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont see impl changes
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPOAdGSE2YV2ShTwoQo:-NPQulZPE7BuPuejoqma:bnj7v4) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/NodeExecutionEvent.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this shouldn't be overridden, so should be made final.
</blockquote></details>

Made final
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI06-t2ut-f0rCY-ih:-NPQv43R-52aLgYyNDPB:b-oinc7o) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L54)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This needs to be addressed.
</blockquote></details>

Made the method final
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPO9gCB4GLoCFN47Ntp:-NPQuv4-BUL1wHK56NHB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineEndEvent.java#L40)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPLjWRPE0mA8UrpdCJg:-NPQwmnZ71buCGWEwwCw:bexb1hj) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events/PipelineStartEvent.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont see it to be done
</blockquote></details>

By mistake i addressed these in the 2nd PR: will do an extra commit here also


<!-- Sent from Reviewable.io -->

2023-03-01 08:22 UTC, mohitg0795 submitted a review, later dismissed
> Reviewed 5 of 11 files at r1, 1 of 7 files at r3, 1 of 1 files at r4, 6 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 7 file(s) to review. 2 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-01 08:49 UTC, archit-harness requested changes
> Reviewed 3 of 11 files at r1, 6 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 1 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`955-outbox-sdk/src/main/java/io/harness/outbox/OutboxEvent.java` line 42 at r6](https://reviewable.io/reviews/harness/harness-core/44374#-NPRLpzP4JPa0tyjFUQn:-NPRLpzP4JPa0tyjFUQo:b-t721ea) ([raw file](https://github.com/harness/harness-core/blob/e57d80b0dc1b56ece09594d347e1548be2790236/955-outbox-sdk/src/main/java/io/harness/outbox/OutboxEvent.java#L42)):*
> ```Java
> @Builder
> @FieldNameConstants(innerTypeName = "OutboxEventKeys")
> @ToString
> ```

why do you need to string here? its in outbox sdk


<!-- Sent from Reviewable.io -->

2023-03-01 08:59 UTC, sahilhindwani-harness commented
*[`955-outbox-sdk/src/main/java/io/harness/outbox/OutboxEvent.java` line 42 at r6](https://reviewable.io/reviews/harness/harness-core/44374#-NPRLpzP4JPa0tyjFUQn:-NPROTmD3bPd9Kn-kh9J:bt0ag5k) ([raw file](https://github.com/harness/harness-core/blob/e57d80b0dc1b56ece09594d347e1548be2790236/955-outbox-sdk/src/main/java/io/harness/outbox/OutboxEvent.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need to string here? its in outbox sdk
</blockquote></details>

+1, can we remove this?


<!-- Sent from Reviewable.io -->

2023-03-01 09:00 UTC, archit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 1 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 118 at r6](https://reviewable.io/reviews/harness/harness-core/44374#-NPROkbZDm8a7krASmn5:-NPROkbZDm8a7krASmn6:b-fcd77i) ([raw file](https://github.com/harness/harness-core/blob/e57d80b0dc1b56ece09594d347e1548be2790236/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L118)):*
> ```Java
>       }
>     } catch (Exception ex) {
>       log.error(String.format("Unexpected error occurred during handling of OutboxEvent: {}", outboxEvent), ex);
> ```

use auto log context to log object details


<!-- Sent from Reviewable.io -->

2023-03-01 09:16 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 7 files at r3, 1 of 1 files at r4, 6 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-01 11:44 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0pX51u-iHHjyCxys:-NPRzEB5DQ0wNUmD0IF5:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L107)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Type should error and log the outboxEvent.getType
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-01 11:45 UTC, sahilhindwani-harness commented
*[`955-outbox-sdk/src/main/java/io/harness/outbox/OutboxEvent.java` line 42 at r6](https://reviewable.io/reviews/harness/harness-core/44374#-NPRLpzP4JPa0tyjFUQn:-NPRzSV6-FQQpwoXMTOh:b-896fjx) ([raw file](https://github.com/harness/harness-core/blob/e57d80b0dc1b56ece09594d347e1548be2790236/955-outbox-sdk/src/main/java/io/harness/outbox/OutboxEvent.java#L42)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1, can we remove this?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-01 11:45 UTC, sahilhindwani-harness approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-01 11:51 UTC, shalini-agr approved these changes
> Reviewed 5 of 11 files at r1, 1 of 7 files at r3, 1 of 1 files at r4, 5 of 7 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-01 11:57 UTC, archit-harness requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 118 at r6](https://reviewable.io/reviews/harness/harness-core/44374#-NPROkbZDm8a7krASmn5:-NPS12942igyWpiAYMLN:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e57d80b0dc1b56ece09594d347e1548be2790236/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L118)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use auto log context to log object details
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java` line 12 at r7](https://reviewable.io/reviews/harness/harness-core/44374#-NPS14PxD5HT5jkzDuxD:-NPS14PxD5HT5jkzDuxE:b-3vz1le) ([raw file](https://github.com/harness/harness-core/blob/02bbef8b5fcaf969f99278002d6fe4953feca572/pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java#L12)):*
> ```Java
> import io.harness.logging.AutoLogContext;
> 
> public class OutboxLogContext extends AutoLogContext {
> ```

add team annotation


<!-- Sent from Reviewable.io -->

2023-03-01 12:54 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java` line 12 at r7](https://reviewable.io/reviews/harness/harness-core/44374#-NPS14PxD5HT5jkzDuxD:-NPSE9nNBwkJX3p--WhB:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/02bbef8b5fcaf969f99278002d6fe4953feca572/pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java#L12)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add team annotation
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-03-01 12:57 UTC, shalini-agr approved these changes
> Reviewed 1 of 1 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-01 15:03 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: 2. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/44374#-NPI0pX51u-iHHjyCxys:-NPSgc1LAjskrFvkwfvD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3facd9dd78bf95945ed17f7ee7ad4d9e3089d0/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L107)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 114 at r4](https://reviewable.io/reviews/harness/harness-core/44374#-NPOD4434gyz6lKXaD0G:-NPSgcw6EABiYQqb9Jey:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c71dccaf754cdede025f0918d85cabd7ffc3ef2b/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should add details about the event that failed in the log.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-01 15:07 UTC, mohitg0795 approved these changes
> Reviewed 1 of 3 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44374)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-01 15:07 UTC, merged