[feat]: [CDS-53556]: Proper error handling in case of unsupported workload kinds
harness/harness-core pull request #44393
Opened 2023-02-27 08:58 UTC by lovish1999

## Describe your changes
Added proper error handling in case of unsupported workload kinds

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-27 10:51 UTC, abosii-harness requested changes

2023-02-27 10:51 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sScaleRequestHandler.java
> +    if (!K8S_SCALING_SUPPORTED_WORKLOAD_KINDS.contains(resourceIdToScale.getKind())) {
what if kind is lowercase or any other case that the one you expect?

2023-02-27 11:16 UTC, lovish1999 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sScaleRequestHandler.java
> +    if (!K8S_SCALING_SUPPORTED_WORKLOAD_KINDS.contains(resourceIdToScale.getKind())) {
Ok.

2023-02-27 11:29 UTC, lovish1999 commented
trigger messagecheck

2023-02-27 12:34 UTC, lovish1999 commented
trigger messagecheck

2023-02-28 05:43 UTC, lovish1999 commented
trigger checkstylecodeformat

2023-02-28 06:15 UTC, lovish1999 commented
trigger messagecheck

2023-02-28 10:17 UTC, abosii-harness requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44393)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 1151 at r3](https://reviewable.io/reviews/harness/harness-core/44393#-NPMVgOw04zcG5__TGnp:-NPMVgOw04zcG5__TGnq:bvf70m3) ([raw file](https://github.com/harness/harness-core/blob/77ca371d5600b3f74aabe24e1e83aff380becf14/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L1151)):*
> ```Java
>     ProcessResult result = runK8sExecutableSilent(k8sDelegateTaskParams, getCommand);
>     if (result.getExitValue() == 0) {
>       if (isEmpty(result.outputUTF8().trim())) {
> ```

we have to check for !result.hasOutput() 
let's just pass the logcallback here and log a warning: Unable to retrieve current replicas count based on path $.spec.replicas, resource 'x' may not be supported for scaling
and then return null


<!-- Sent from Reviewable.io -->

2023-03-01 05:41 UTC, namantalaycha10 approved these changes
> Reviewed 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44393)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-01 07:22 UTC, abosii-harness approved these changes
> Reviewed 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44393)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-01 07:22 UTC, lovish1999 commented
trigger ut5

2023-03-01 07:22 UTC, lovish1999 commented
trigger ut6

2023-03-01 07:22 UTC, lovish1999 commented
trigger ut7

2023-03-01 07:22 UTC, lovish1999 commented
trigger ut8

2023-03-01 07:22 UTC, lovish1999 commented
trigger ut9

2023-03-01 07:55 UTC, TarunUba1 approved these changes
> Reviewed 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44393)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-01 08:35 UTC, lovish1999 commented
trigger ut6

2023-03-01 09:16 UTC, merged