feat: [CDS-54179]: ECS NG Rolling BG Outcome
harness/harness-core pull request #44429
Opened 2023-02-27 18:13 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-02-28 01:06 UTC, sainath-b commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsRollingDeployStep.java
> +    EcsRollingDeployOutcome ecsRollingDeployOutcome =
What if no tasks are present or created?  Did we test that case?

2023-02-28 01:07 UTC, sainath-b requested changes
Please discuss and address comments

2023-03-01 19:33 UTC, alluvamsi-harness commented
trigger smartchecks

2023-03-02 04:26 UTC, sainath-b approved these changes

2023-03-02 04:26 UTC, sainath-b reviewed
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44429)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-02 04:54 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsRollingDeployStep.java
> +    EcsRollingDeployOutcome ecsRollingDeployOutcome =
remove it

2023-03-02 05:03 UTC, alluvamsi-harness commented
trigger messagecheck

2023-03-02 05:08 UTC, rohitk-h approved these changes
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44429)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-02 05:19 UTC, utkarshchoubey-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44429)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-02 05:47 UTC, yogesh-chauhan approved these changes

2023-03-02 05:53 UTC, sainath-b approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44429)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-02 05:59 UTC, merged