feat: [cds-54344]: Added support for isNewTemplate flag for template create flow
harness/harness-core pull request #44472
Opened 2023-02-28 11:26 UTC by utkarshchoubey-harness

Added support for isNewTemplate flag for template create flow

Tests:-
Create template with isNewTemplate flag as true with identifier as templateIdentifier11112345 version v57

![image](https://user-images.githubusercontent.com/101091340/221841023-e93bf6d7-ae2f-4629-b82a-77b8018590d5.png)

Now again try creating template with isNewTemplate flag as true again with same identifier and diff version v58

![image](https://user-images.githubusercontent.com/101091340/221841324-536983f0-c662-433a-9fbc-f16dc15eee7e.png)

Now try creating template with isNewTemplate flag as false with same identifier and same version v58 

![image](https://user-images.githubusercontent.com/101091340/221841624-3b67f9d8-aa42-446b-bfb1-f2567bc73ec2.png)

Now try creating a new version of template without passing flag -> Template creation is successful

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/44472)

2023-02-28 11:35 UTC, utkarshchoubey-harness commented
trigger messagecheck

2023-02-28 18:32 UTC, yogesh-chauhan requested changes

2023-02-28 18:32 UTC, yogesh-chauhan commented on 840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +      @QueryParam("isNewTemplate") @DefaultValue("false") @ApiParam(hidden = true) boolean isNewTemplate) {
Lets put a comment why we need a isNewTemplate query param since its not intuitive

2023-03-01 09:40 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44472)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 258 at r1](https://reviewable.io/reviews/harness/harness-core/44472#-NPMlXHl-prbMI5tY4eQ-r1-258:-NPRXRXg60__mu1wM7O2:bll5qlz) ([raw file](https://github.com/harness/harness-core/blob/c41e741941e410f754d5351a836bb92e76bceae4/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L258)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is the default value correct ? 
</blockquote></details>

yes @yogesh-chauhan it is correct. as isNewTemplate is a hidden field, if We set it as true, it will cause issues for customers as for creating a new template version also this api is only used Done


<!-- Sent from Reviewable.io -->

2023-03-01 12:04 UTC, yogesh-chauhan approved these changes
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44472)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-01 12:18 UTC, merged