[feat]: [PIE:8298]: Working Flow for Sending execution events to AuditService
harness/harness-core pull request #44500
Opened 2023-02-28 18:20 UTC by senjucanon2

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-02 07:43 UTC, senjucanon2 commented
trigger messagecheck

2023-03-02 20:25 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPYzzKY6yrjUZr4zKKu:-NPYzzKZEEHtNCwVZlOY:b-86bz07) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L29)):*
> ```Java
>   public void onNodeStart(NodeStartInfo nodeStartInfo) {
>     switch (nodeStartInfo.getNodeExecution().getGroup()) {
>       case "PIPELINE":
> ```

please use constants.


<!-- Sent from Reviewable.io -->

2023-03-02 20:25 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-1IE4x1loXKd9a_9:-NPZ-1IE4x1loXKd9a_A:bewv7z6) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L36)):*
> ```Java
>         break;
>       default:
>         log.info(String.format("Current type of event is not supported for Audits!"));
> ```

please log all details in such a case so that we are able to understand for what type of event this case came up.


<!-- Sent from Reviewable.io -->

2023-03-02 20:26 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-8DZ6_RAty8RtvN1:-NPZ-8DZ6_RAty8RtvN2:b-xk89y) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L28)):*
> ```Java
>   @Override
>   public void onNodeStart(NodeStartInfo nodeStartInfo) {
>     switch (nodeStartInfo.getNodeExecution().getGroup()) {
> ```

this can result into NPEs, please put appropriate null checks.


<!-- Sent from Reviewable.io -->

2023-03-02 20:26 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-CVNENU090kWIuez:-NPZ-CVNENU090kWIuf-:b-ti112t) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L25)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class NodeExecutionOutboxHandler implements NodeExecutionStartObserver {
>   @Inject private OutboxService outboxService;
> ```

blank line missing


<!-- Sent from Reviewable.io -->

2023-03-02 20:26 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-FMwDPOJ4yfkIk-T:-NPZ-FMwDPOJ4yfkIk-U:b-86bz07) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L44)):*
> ```Java
>     StageStartEvent stageStartEvent =
>         StageStartEvent.builder()
>             .accountIdentifier(ambiance.getSetupAbstractionsMap().get("account"))
> ```

please use constants.


<!-- Sent from Reviewable.io -->

2023-03-02 20:27 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-Pi_2xWdvp-eFDC1:-NPZ-Pi_2xWdvp-eFDC2:b1ztwtr) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L28)):*
> ```Java
>   @Override
>   public void onNodeStart(NodeStartInfo nodeStartInfo) {
>     switch (nodeStartInfo.getNodeExecution().getGroup()) {
> ```

there should be a global try catch to handle exceptions properly


<!-- Sent from Reviewable.io -->

2023-03-03 06:18 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 20 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-CVNENU090kWIuez:-NP_yGT_5r3-6y5QmFdB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-8DZ6_RAty8RtvN1:-NPa6XUOE4LlPqabD-qY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this can result into NPEs, please put appropriate null checks.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-Pi_2xWdvp-eFDC1:-NPa6XvmBaW3bzMC1Wtr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

there should be a global try catch to handle exceptions properly
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPYzzKY6yrjUZr4zKKu:-NPa23RVAjXA0Fs_vH4I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please use constants.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-1IE4x1loXKd9a_9:-NPa6ZG-50RjSg2o6Cgh:b8x7fg8) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L36)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please log all details in such a case so that we are able to understand for what type of event this case came up.
</blockquote></details>

Switch-Case is only on a string here hence, printed in logs.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/44500#-NPZ-FMwDPOJ4yfkIk-T:-NPa1I373uJTyrrCbKAK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ddbbe829963eb5ae0df4968e7512690ec974166/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please use constants.
</blockquote></details>

Done.



_Code quote:_
```Java
switch (nodeStartInfo.getNodeExecution().getGroup()) {
```


<!-- Sent from Reviewable.io -->

2023-03-03 06:23 UTC, senjucanon2 commented
trigger messagecheck

2023-03-03 09:02 UTC, archit-harness requested changes
> Reviewed 2 of 18 files at r1, 8 of 13 files at r2, 6 of 6 files at r3, 2 of 2 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 21 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 38 at r7](https://reviewable.io/reviews/harness/harness-core/44500#-NPagVZl2c4m2fybqGeo:-NPagVZl2c4m2fybqGep:bvjxx8y) ([raw file](https://github.com/harness/harness-core/blob/b657d5eaa8c46f28aff37a18a27c913d55b6a7e1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L38)):*
> ```Java
>   @Override
>   public void onNodeStart(NodeStartInfo nodeStartInfo) {
>     if (nodeStartInfo == null || nodeStartInfo.getNodeExecution() == null
> ```

move to validateMethod as it will be cleaner
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 36 at r7](https://reviewable.io/reviews/harness/harness-core/44500#-NPagnp95snqGiXar3ck:-NPagnp95snqGiXar3cl:b1k0svj) ([raw file](https://github.com/harness/harness-core/blob/5d5ad4e8c4debacebf4ac20c033d5f0118597205/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L36)):*
> ```Java
> /***
>  * Handler Methods in this class handle events for OutboxDb for NodeExecutionEvents during a pipeline execution
>  * NodeExecution can be of type Stage/Step/Pipeline etc.
> ```

why this comment is removed?


<!-- Sent from Reviewable.io -->

2023-03-03 09:09 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 21 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 38 at r7](https://reviewable.io/reviews/harness/harness-core/44500#-NPagVZl2c4m2fybqGeo:-NPai2pd9AxyKhqknMF5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b657d5eaa8c46f28aff37a18a27c913d55b6a7e1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

move to validateMethod as it will be cleaner
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java` line 36 at r7](https://reviewable.io/reviews/harness/harness-core/44500#-NPagnp95snqGiXar3ck:-NPaieAB9FYjMeNvymCx:btb535z) ([raw file](https://github.com/harness/harness-core/blob/5d5ad4e8c4debacebf4ac20c033d5f0118597205/pipeline-service/service/src/main/java/io/harness/pms/outbox/NodeExecutionOutboxEventHandler.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this comment is removed?
</blockquote></details>

It may have been removed while resolving merge conflicts with Previous PR, added again.


<!-- Sent from Reviewable.io -->

2023-03-03 10:25 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 29 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb-J4p7kJvH81FIZo2:-NPb-J4p7kJvH81FIZo3:b-7mwk2) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L29)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class NodeExecutionOutboxHandler implements NodeExecutionStartObserver {
>   public static final String ACCOUNT_ID = "accountId";
> ```

do you think these are some common params that can be extracted out in a util? 


<!-- Sent from Reviewable.io -->

2023-03-03 10:26 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 63 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb-ajF-ZVjboiJvvs3:-NPb-ajF-ZVjboiJvvs4:b-usndce) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L63)):*
> ```Java
>     if (nodeStartInfo == null || nodeStartInfo.getNodeExecution() == null
>         || nodeStartInfo.getNodeExecution().getGroup() == null) {
>       log.info(String.format("Required fields to send an outBoxEvent are not populated in nodeStartInfo!"));
> ```

why is it info log? It should be error


<!-- Sent from Reviewable.io -->

2023-03-03 10:29 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb08xT1jHT3MGEcnqw:-NPb08xT1jHT3MGEcnqx:bwc695u) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L53)):*
> ```Java
>           break;
>         default:
>           log.info(String.format("Current type of NodeGroup is not supported for Audits!"));
> ```

we should print the node group type here so that its clear what was the unexpected type here


<!-- Sent from Reviewable.io -->

2023-03-03 10:29 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb0JBO5WUbglbBhsHk:-NPb0JBO5WUbglbBhsHl:b-t00q8c) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L56)):*
> ```Java
>       }
>     } catch (Exception ex) {
>       log.error(String.format("Unexpected error occurred during handling of nodeGroup: {}", nodeGroup), ex);
> ```

did we check if nodegroup is getting logged properly?


<!-- Sent from Reviewable.io -->

2023-03-03 10:32 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb0JBO5WUbglbBhsHk:-NPb0mi59Ue6hgYg-rcy:bp4m343) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

did we check if nodegroup is getting logged properly?
</blockquote></details>

will these logs come up when we search with account identifier? If not, then please do such handling. We should be able to identify all error logs for a given account identifier.


<!-- Sent from Reviewable.io -->

2023-03-03 10:33 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java` line 16 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb16k90sdwnYYlEdOV:-NPb16k90sdwnYYlEdOW:b-s9mv2k) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java#L16)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class OutboxLogContext extends AutoLogContext {
>   public static final String ID = "outboxEventId";
> ```

why have we changed it? Are we using it in this PR?


<!-- Sent from Reviewable.io -->

2023-03-03 10:34 UTC, shalini-agr submitted a review, later dismissed
> Reviewed 2 of 18 files at r1, 8 of 13 files at r2, 5 of 6 files at r3, 2 of 2 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 2 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-03 11:13 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 2 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 29 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb-J4p7kJvH81FIZo2:-NPb1r7-AuIKWwyk8qE3:b-qof18q) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

do you think these are some common params that can be extracted out in a util? 
</blockquote></details>

Currently there are only 5 and only used in this class for this flow, if the no. of constants increase on implementation of full flow then will extract them in another class.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb08xT1jHT3MGEcnqw:-NPb2_gg3X5wz_wOOunp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should print the node group type here so that its clear what was the unexpected type here
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb0JBO5WUbglbBhsHk:-NPb9ea4CPJfLdPkrKRS:b-2sws6x) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

will these logs come up when we search with account identifier? If not, then please do such handling. We should be able to identify all error logs for a given account identifier.
</blockquote></details>

I have put this in AutoLogContext which will add nodeExecutionID in it, which is as good as accountIdentifier for searching logs in case of execution.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 63 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb-ajF-ZVjboiJvvs3:-NPb4DP8D1KGr9SBVbQX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it info log? It should be error
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java` line 16 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb16k90sdwnYYlEdOV:-NPb4FB06ALJIbfZK6WH:bnzwwhr) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/OutboxLogContext.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why have we changed it? Are we using it in this PR?
</blockquote></details>

It had wrong name  for Id in the previous PR, now it is correct


<!-- Sent from Reviewable.io -->

2023-03-03 11:23 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 29 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb-J4p7kJvH81FIZo2:-NPbCVoj5Cz9naLA8B-Y:bj5td05) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L29)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Currently there are only 5 and only used in this class for this flow, if the no. of constants increase on implementation of full flow then will extract them in another class.
</blockquote></details>

As discussed, this should move to some constants class. From where, it should be used both while setting and retrieving data from ambience.


<!-- Sent from Reviewable.io -->

2023-03-03 11:34 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 66 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPbF4yU-ZwgbeSG6PqD:-NPbF4yU-ZwgbeSG6PqE:bd3ul9f) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L66)):*
> ```Java
>         || nodeStartInfo.getNodeExecution().getGroup() == null) {
>       log.error(String.format("Required fields to send an outBoxEvent are not populated in nodeStartInfo!"));
>       return true;
> ```

this should be false as it failed validation.


<!-- Sent from Reviewable.io -->

2023-03-03 16:38 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 47 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcKfRH7IoozTR524ef:-NPcKfRI05ejBs7WUzjk:b-oxb850) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L47)):*
> ```Java
>       try {
>         switch (nodeGroup) {
>           case PIPELINE:
> ```

nit: Use StepOutcomeGroup


<!-- Sent from Reviewable.io -->

2023-03-03 16:39 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 43 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcKl356-9OuzBKKqmh:-NPcKl356-9OuzBKKqmi:b8igtcr) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L43)):*
> ```Java
>     String nodeGroup = null;
>     try (AutoLogContext ignore =
>              new NodeExecutionLogContext(nodeStartInfo.getNodeExecution().getUuid(), OVERRIDE_NESTS)) {
> ```

you can use AmbianceUtils.getAutoLogContext for this.


<!-- Sent from Reviewable.io -->

2023-03-03 16:39 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb0JBO5WUbglbBhsHk:-NPcKwuI29jS6nVWjVCE:ba6ff6o) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L56)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

I have put this in AutoLogContext which will add nodeExecutionID in it, which is as good as accountIdentifier for searching logs in case of execution.
</blockquote></details>

We should add auto log context from ambiance, accountId automatically comes from it. 


<!-- Sent from Reviewable.io -->

2023-03-03 16:40 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 66 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPbF4yU-ZwgbeSG6PqD:-NPcL78r4FM4CEElMTxZ:b-yy9xej) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L66)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be false as it failed validation.
</blockquote></details>

I think if it is false then we will retake the event. If group is not set, we should ignore


<!-- Sent from Reviewable.io -->

2023-03-03 16:41 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/NodeExecutionLogContext.java` line 15 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcLLvl8p6bovEsBasG:-NPcLLvl8p6bovEsBasH:b-50qoi3) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/NodeExecutionLogContext.java#L15)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class NodeExecutionLogContext extends AutoLogContext {
> ```

nit: Is this required, can we reuse autoLogContext from ambianceUtils?


<!-- Sent from Reviewable.io -->

2023-03-03 16:42 UTC, sahilhindwani-harness reviewed
> Reviewed 2 of 18 files at r1, 8 of 13 files at r2, 5 of 6 files at r3, 2 of 2 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 1 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-04 04:43 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 1 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 29 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb-J4p7kJvH81FIZo2:-NPet-SyEzhx1Zb0i_2m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L29)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

There should already be a constance for this, please use `SetupAbstractionKeys.accountId` for this.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 56 at r8](https://reviewable.io/reviews/harness/harness-core/44500#-NPb0JBO5WUbglbBhsHk:-NPeuQcaExmr9L-x-LYx:b84zwlp) ([raw file](https://github.com/harness/harness-core/blob/880f0959bce66ba44fbb6144e1ec479c9b1b3580/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L56)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We should add auto log context from ambiance, accountId automatically comes from it. 
</blockquote></details>

Great Suggestion. Added Ambiance as it has all the required data including "accountId".
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 43 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcKl356-9OuzBKKqmh:-NPetbBH6BetntbNYD2I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

you can use AmbianceUtils.getAutoLogContext for this.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 47 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcKfRH7IoozTR524ef:-NPeuGbv5oY-brrx8tFj:b-gpfvdm) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L47)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Use StepOutcomeGroup
</blockquote></details>

StepOutcomeGroup is an Enum type but here what we get from "nodeStartInfo.getNodeExecution().getGroup()" is a string.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 66 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPbF4yU-ZwgbeSG6PqD:-NPev4Pz70DnRj_oh8oU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L66)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think if it is false then we will retake the event. If group is not set, we should ignore
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/NodeExecutionLogContext.java` line 15 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcLLvl8p6bovEsBasG:-NPeugP4Dkd8TAI6gWZV:b-ejlhc5) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog/NodeExecutionLogContext.java#L15)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Is this required, can we reuse autoLogContext from ambianceUtils?
</blockquote></details>

Removed Class.


<!-- Sent from Reviewable.io -->

2023-03-06 04:03 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 47 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcKfRH7IoozTR524ef:-NPp4hXp19cnL-kyFEz9:bfha74b) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L47)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

StepOutcomeGroup is an Enum type but here what we get from "nodeStartInfo.getNodeExecution().getGroup()" is a string.
</blockquote></details>

we can use StepOutcomeGroup.name()


<!-- Sent from Reviewable.io -->

2023-03-06 04:40 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 4 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 47 at r9](https://reviewable.io/reviews/harness/harness-core/44500#-NPcKfRH7IoozTR524ef:-NPpDA9t04SE5szpgZ5a:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/22ad5a026e413ae637433add128725c768d66bb1/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L47)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

we can use StepOutcomeGroup.name()
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-06 04:43 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 2 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-06 05:11 UTC, archit-harness requested changes
> Reviewed 1 of 2 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 67 at r11](https://reviewable.io/reviews/harness/harness-core/44500#-NPpK6Aa8iwz9Vj7eQAu:-NPpK6Ab4ZeGDn3cTyWK:b-kdvwym) ([raw file](https://github.com/harness/harness-core/blob/9462328cb16777e228fe5fd6f6f101676b2c53b6/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L67)):*
> ```Java
>     }
> 
>     log.error("Required fields to send an outBoxEvent are not populated in nodeStartInfo!");
> ```

NodeStartInfo should be added in logs to further capture



_Code quote:_
```Java
NodeExecutionStartObserver
```


<!-- Sent from Reviewable.io -->

2023-03-06 05:37 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 3. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java` line 67 at r11](https://reviewable.io/reviews/harness/harness-core/44500#-NPpK6Aa8iwz9Vj7eQAu:-NPpQEoi6wBVNywjDK8q:b-vin8u9) ([raw file](https://github.com/harness/harness-core/blob/9462328cb16777e228fe5fd6f6f101676b2c53b6/pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers/NodeExecutionOutboxHandler.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

NodeStartInfo should be added in logs to further capture
</blockquote></details>

done, discussed offline, lets do it later


<!-- Sent from Reviewable.io -->

2023-03-06 05:47 UTC, shalini-agr approved these changes
> Reviewed 1 of 2 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-06 06:28 UTC, mohitg0795 approved these changes
> Reviewed 2 of 18 files at r1, 8 of 13 files at r2, 5 of 6 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 2 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44500)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-06 06:29 UTC, merged