fix: [CDS-50690]: git commit NG , changing FF name for CG
harness/harness-core pull request #44629
Opened 2023-03-02 16:39 UTC by TarunUba1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-03 10:10 UTC, abosii-harness requested changes

2023-03-03 10:10 UTC, abosii-harness commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_CG_K8S_MANIFEST_COMMIT_VAR(
we should not change existing FF

2023-03-03 10:10 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +            .manifest(((K8sExecutionPassThroughData) passThroughData).getK8sGitFetchInfo())
you already have  K8sExecutionPassThroughData executionPassThroughData, no need for casting here

2023-03-03 10:10 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryOutcome.java
> +  K8sGitFetchInfo manifest;
Let's get approval on the expression

2023-03-03 10:10 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +import software.wings.api.k8s.K8sGitFetchInfo;
Let's not reuse CG beans

2023-03-03 10:10 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java
> +        String k8ValuesLocation = gitFetchFilesConfig.getIdentifier();
This is not k8sValuesLocation but identifier

2023-03-03 11:18 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: 29 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/44629#-NPYBJxSlzFtEc4H7t0U-r1-208:-NPb7WwV9lHVROwuwAz2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ae11369a5da76bc8a7b9171e3718eb5453eba56/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java#L208)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

you already have  K8sExecutionPassThroughData executionPassThroughData, no need for casting here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/44629#-NPYBJxSlzFtEc4H7t0a-r1-108:-NPbAjmAAIZvhvnfxfVP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ae11369a5da76bc8a7b9171e3718eb5453eba56/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L108)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's not reuse CG beans
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/44629#-NPYBJxSlzFtEc4H7t0d-r1-107:-NPb9B991Fq8C9TaeTNw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ae11369a5da76bc8a7b9171e3718eb5453eba56/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java#L107)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is not k8sValuesLocation but identifier
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 583 at r1](https://reviewable.io/reviews/harness/harness-core/44629#-NPYBJxSlzFtEc4H7t0l-r1-583:-NPbApis5y-NmuQApl7k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ae11369a5da76bc8a7b9171e3718eb5453eba56/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L583)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

we should not change existing FF
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 07:15 UTC, abhinavsingh1196 requested changes
> Reviewed 13 of 27 files at r1, 8 of 12 files at r2, 5 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: 29 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 680 at r4](https://reviewable.io/reviews/harness/harness-core/44629#-NPpiO0k90zLTfJ950xk:-NPpiO0k90zLTfJ950xl:b74mf3q) ([raw file](https://github.com/harness/harness-core/blob/6eef7c6f8b6dd8342ea311d6bf9f57bda412eaa9/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L680)):*
> ```Java
>       Map<String, String> gitFetchFilesConfigMap = gitFetchResponse.getFetchedCommitIdsMap();
>       gitFetchFilesConfigMap.forEach(
>           (String keys, String values) -> { variables.put(keys, K8sGitInfo.builder().commitId(values).build()); });
> ```

redundant braces {}
also, can be renamed to "key" and "value"



_Code quote:_
```Java
K8sGitFetchInfo k8sGitFetchInfo = K8sGitFetchInfo.builder().build();
```


<!-- Sent from Reviewable.io -->

2023-03-06 08:44 UTC, abosii-harness requested changes
> Reviewed 13 of 27 files at r1, 9 of 12 files at r2, 5 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/44629#-NPq4Gbw7yS2Kzgb6Xg9:-NPq4Gbw7yS2Kzgb6XgA:b1ve8f2) ([raw file](https://github.com/harness/harness-core/blob/6eef7c6f8b6dd8342ea311d6bf9f57bda412eaa9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java#L26)):*
> ```Java
> @Builder
> @JsonTypeName("K8sGitFetchInfo")
> @TargetModule(HarnessModule._957_CG_BEANS)
> ```

Why we need target modules here? Do we need to implement sweepingOutput? This is a CG entity if I remember right
___
*[`960-api-services/src/main/java/io/harness/git/Constants.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/44629#-NPq4ry4DAFrWzkfbMrO:-NPq4ry5Bt-pOgoygVUe:b1l6w4r) ([raw file](https://github.com/harness/harness-core/blob/6eef7c6f8b6dd8342ea311d6bf9f57bda412eaa9/960-api-services/src/main/java/io/harness/git/Constants.java#L37)):*
> ```Java
>   String COMMIT_MESSAGE = "Harness IO Git Sync.\n";
>   String EXCEPTION_STRING = "Exception: ";
>   String DEFAULT_FETCH_IDENTIFIER = "--default";
> ```

nit: better __DEFAULT


<!-- Sent from Reviewable.io -->

2023-03-06 10:40 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: 4 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryOutcome.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/44629#-NPYBJxSlzFtEc4H7t0V-r1-35:-NPqINgIA6RPTrChYK_D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ae11369a5da76bc8a7b9171e3718eb5453eba56/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryOutcome.java#L35)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's get approval on the expression
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 680 at r4](https://reviewable.io/reviews/harness/harness-core/44629#-NPpiO0k90zLTfJ950xk:-NPqIMqwBuMO-npwz-dH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eef7c6f8b6dd8342ea311d6bf9f57bda412eaa9/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L680)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

redundant braces {}
also, can be renamed to "key" and "value"
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/44629#-NPq4Gbw7yS2Kzgb6Xg9:-NPqIP6Z2YczTWmxb7nH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eef7c6f8b6dd8342ea311d6bf9f57bda412eaa9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java#L26)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why we need target modules here? Do we need to implement sweepingOutput? This is a CG entity if I remember right
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 11:23 UTC, abosii-harness approved these changes
> Reviewed 1 of 7 files at r3, 1 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/44629#-NPq4Gbw7yS2Kzgb6Xg9:-NPqeHuB1qWAiLygqLBs:b-ulxiym) ([raw file](https://github.com/harness/harness-core/blob/6eef7c6f8b6dd8342ea311d6bf9f57bda412eaa9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java#L26)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about implements SweepingOutput?


<!-- Sent from Reviewable.io -->

2023-03-06 11:52 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/44629#-NPq4Gbw7yS2Kzgb6Xg9:-NPqjxqF2QWWPmMjNpR4:b-p7hwuk) ([raw file](https://github.com/harness/harness-core/blob/6eef7c6f8b6dd8342ea311d6bf9f57bda412eaa9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sGitFetchInfo.java#L26)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about implements SweepingOutput?
</blockquote></details>

FIXED, my bad


<!-- Sent from Reviewable.io -->

2023-03-06 12:48 UTC, abosii-harness approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-06 12:49 UTC, abosii-harness commented
Please provide a better PR title, this PR doesn't update FF name anymore

2023-03-06 16:39 UTC, abhinavsingh1196 approved these changes
> Reviewed 1 of 7 files at r3, 1 of 3 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44629)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-06 16:53 UTC, merged