[feat]: [PIE-8576]: added move config pipeline in the openapi yaml
harness/harness-core pull request #44680
Opened 2023-03-03 11:35 UTC by adivishy1

## Describe your changes
Added move config pipeline api in the openapi yaml and its impl.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-06 04:47 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        pipeline_identifier:
nit: this is already taken as input in Path param right? Any reason why it's in request body as well?

2023-03-06 04:47 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        application/json:
please add examples if this is a public facing API, for both Request and Response Bodies

2023-03-06 04:48 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      description: Fetches Pipeline YAML from Harness DB and creates a remote entity or Fetches Pipeline YAML from remote repository and creates a inline entity
nit nit -> creates an inline entity :P

2023-03-06 05:15 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 479 at r2](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r2-479:-NPpJh7JCQW8WSqbx4F3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3b6bda51f4f019b921c6ddbb15a173e534f05eec/pipeline-service/contracts/openapi/v1/openapi.yaml#L479)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

nit nit -> creates an inline entity :P 
</blockquote></details>

done
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1871 at r2](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r2-1871:-NPpIlx56n_nFosu1ZFg:bi1rklj) ([raw file](https://github.com/harness/harness-core/blob/3b6bda51f4f019b921c6ddbb15a173e534f05eec/pipeline-service/contracts/openapi/v1/openapi.yaml#L1871)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

nit: this is already taken as input in Path param right? Any reason why it's in request body as well?
</blockquote></details>

Without the pipelineIdentifier in the request body, the request body by it self will not be complete and we need it the path param as we are performing an operation for this entity. Hence as a good practice, we have to take it in both places and do a validation that both are the same or not
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2495 at r2](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r2-2495:-NPpK3Sm9y4MDfXXxIXU:b2stbwa) ([raw file](https://github.com/harness/harness-core/blob/3b6bda51f4f019b921c6ddbb15a173e534f05eec/pipeline-service/contracts/openapi/v1/openapi.yaml#L2495)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

please add examples if this is a public facing API, for both Request and Response Bodies
</blockquote></details>

not a public facing api


<!-- Sent from Reviewable.io -->

2023-03-06 05:26 UTC, vaibhav-si reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1871 at r2](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r2-1871:-NPpLyyk2cAMFdFsGQM9:bemixg0) ([raw file](https://github.com/harness/harness-core/blob/3b6bda51f4f019b921c6ddbb15a173e534f05eec/pipeline-service/contracts/openapi/v1/openapi.yaml#L1871)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Without the pipelineIdentifier in the request body, the request body by it self will not be complete and we need it the path param as we are performing an operation for this entity. Hence as a good practice, we have to take it in both places and do a validation that both are the same or not
</blockquote></details>

Didn't understand this. If the field is already taken in the path param, why do we need it in the request body again from the user?
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1869 at r3](https://reviewable.io/reviews/harness/harness-core/44680#-NPpLtyE-VDa1ZRxA2cC:-NPpLtyE-VDa1ZRxA2cD:b-yvd4lj) ([raw file](https://github.com/harness/harness-core/blob/23b275dcaeaa0f3f6e548b80c45c7a52fa5028f2/pipeline-service/contracts/openapi/v1/openapi.yaml#L1869)):*
> ```YAML
>         id: e4ec161edc199
>       type: object
>       description: 'Request body for pipeline move configuration '
> ```

type: Response?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 510 at r3](https://reviewable.io/reviews/harness/harness-core/44680#-NPpNGLn52nQQygrXR3y:-NPpNGLp3KMeNB2xn3p0:b-kydrui) ([raw file](https://github.com/harness/harness-core/blob/23b275dcaeaa0f3f6e548b80c45c7a52fa5028f2/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L510)):*
> ```Java
>   public static io.harness.pms.pipeline.MoveConfigOperationType getMoveConfigType(
>       io.harness.spec.server.pipeline.v1.model.MoveConfigOperationType moveConfigOperationType) {
>     if (io.harness.spec.server.pipeline.v1.model.MoveConfigOperationType.INLINE_TO_REMOTE.equals(
> ```

nit, switch-case can be used. Will be cleaner and faster.


<!-- Sent from Reviewable.io -->

2023-03-06 05:37 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1871 at r2](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r2-1871:-NPpOuRx4ywXFMWL4ow_:b-ytmwp7) ([raw file](https://github.com/harness/harness-core/blob/3b6bda51f4f019b921c6ddbb15a173e534f05eec/pipeline-service/contracts/openapi/v1/openapi.yaml#L1871)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Didn't understand this. If the field is already taken in the path param, why do we need it in the request body again from the user?
</blockquote></details>

https://dzone.com/articles/rest-api-path-vs-request-body-parameters
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1869 at r3](https://reviewable.io/reviews/harness/harness-core/44680#-NPpLtyE-VDa1ZRxA2cC:-NPpPQ3cECRJFFLk1L6r:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/23b275dcaeaa0f3f6e548b80c45c7a52fa5028f2/pipeline-service/contracts/openapi/v1/openapi.yaml#L1869)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

type: Response?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 510 at r3](https://reviewable.io/reviews/harness/harness-core/44680#-NPpNGLn52nQQygrXR3y:-NPpPcCeC6fVRH7kznQB:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/23b275dcaeaa0f3f6e548b80c45c7a52fa5028f2/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L510)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, switch-case can be used. Will be cleaner and faster.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-06 05:49 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      x-internal: false
if it's internal please mark x-internal: true here

2023-03-06 05:51 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 491 at r5](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r5-491:-NPpTOxbBytUaoJGTjKJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c5f7e1a60568011042f22a0474c0df0147521e2/pipeline-service/contracts/openapi/v1/openapi.yaml#L491)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

if it's internal please mark x-internal: true here 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 05:54 UTC, mankrit-singh reviewed
> Reviewed 2 of 4 files at r2, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-06 05:58 UTC, vaibhav-si approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-06 05:59 UTC, vaibhav-si reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1879 at r3](https://reviewable.io/reviews/harness/harness-core/44680#-NPpMTXR4E-BQjFao63o:-NPpMTXR4E-BQjFao63p:bzbs8it) ([raw file](https://github.com/harness/harness-core/blob/23b275dcaeaa0f3f6e548b80c45c7a52fa5028f2/pipeline-service/contracts/openapi/v1/openapi.yaml#L1879)):*
> ```YAML
>         - REMOTE_TO_INLINE
>       description: Move config operation type
>     GitMoveDetails:
> ```

Is this different from the Git details object we have in other pipeline apis? If not, can we reuse it?


<!-- Sent from Reviewable.io -->

2023-03-06 06:02 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 4 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1879 at r3](https://reviewable.io/reviews/harness/harness-core/44680#-NPpMTXR4E-BQjFao63o:-NPpVW7z2oGwf4TaNmit:b-v9up25) ([raw file](https://github.com/harness/harness-core/blob/23b275dcaeaa0f3f6e548b80c45c7a52fa5028f2/pipeline-service/contracts/openapi/v1/openapi.yaml#L1879)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Is this different from the Git details object we have in other pipeline apis? If not, can we reuse it?
</blockquote></details>

we dont have other git details object which has the same set of params, the closet was git create details object but again there was one query param difference, hence created a new object.
this same object will be used for input set move config api as well


<!-- Sent from Reviewable.io -->

2023-03-06 06:03 UTC, vaibhav-si submitted a review, later dismissed
> Reviewed 2 of 4 files at r2, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-06 10:06 UTC, mohitg0795 commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 491 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqNi3T2WxBIp2BincV:-NPqNi3T2WxBIp2BincW:b-ttmk9z) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L491)):*
> ```YAML
>       tags:
>         - Pipelines
>       x-internal: true
> ```

what is this for?


<!-- Sent from Reviewable.io -->

2023-03-06 10:07 UTC, mohitg0795 commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1856 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqNrcw1mGfX3i1avyD:-NPqNrcw1mGfX3i1avyE:b-q6crtc) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1856)):*
> ```YAML
>         id: ed578c29cb9dc
>       type: object
>       description: 'Request body for pipeline move configuration '
> ```

looks partial


<!-- Sent from Reviewable.io -->

2023-03-06 10:08 UTC, mohitg0795 commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1896 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqNx1v98tw9gT-15KA:-NPqNx1v98tw9gT-15KB:b-vnodo6) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1896)):*
> ```YAML
>         branch_name:
>           type: string
>           description: Name of the branch.
> ```

shouldn't we be very descriptive here? Eg: Name of the branch where we want to create the remote entity in case of moving pipeline from INLINE to REMOTE or from where we want to fetch the remote entity in case of moving pipeline from REMOTE to INLINE
?


<!-- Sent from Reviewable.io -->

2023-03-06 10:08 UTC, mohitg0795 commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1905 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOE-oDhwT8OYms4pp:-NPqOE-p87NGbt8ZUl9W:b-5st6v9) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1905)):*
> ```YAML
>         base_branch:
>           type: string
>           description: Name of the default branch (this checks out a new branch titled by branch_name).
> ```

this isn't clear at all.


<!-- Sent from Reviewable.io -->

2023-03-06 10:09 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 286 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOUD57fsjmO34diJD:-NPqOUD57fsjmO34diJE:bhvdoht) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L286)):*
> ```Java
>       @AccountIdentifier String account) {
>     if (requestBody == null) {
>       throw new InvalidRequestException("Pipeline Update request body must not be null.");
> ```

error message is wrong.


<!-- Sent from Reviewable.io -->

2023-03-06 10:12 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 290 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqP3vi0ZX6PTpbcvNP:-NPqP3vi0ZX6PTpbcvNQ:bt1uwyu) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L290)):*
> ```Java
>     if (!Objects.equals(pipeline, requestBody.getPipelineIdentifier())) {
>       throw new InvalidRequestException(
>           String.format("Expected Pipeline identifier in Request Body to be [%s], but was [%s]", pipeline,
> ```

are we the only one checking these cases? I guess these must be done in all APIs mostly. If yes, then this should be modularized.


<!-- Sent from Reviewable.io -->

2023-03-06 10:14 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 382 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqPV3l5CyYV2UiWk5D:-NPqPV3l5CyYV2UiWk5E:b2t7vnp) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L382)):*
> ```Java
>       return GitEntityInfo.builder().build();
>     }
>     return GitEntityInfo.builder()
> ```

I think we should create a method that just creates GitEntityInfo object based on input arguments. This way no one needs to understand logic behind setting up new branch field or any other field.


<!-- Sent from Reviewable.io -->

2023-03-06 10:22 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 284 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOZo90xr8Urf0Ud49:-NPqRIYDEyU4GmvZKJba:bkl2qcs) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L284)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

from the yaml, when the code gets generated, this is the order we are getting, I am not sure if we can control that
</blockquote></details>

@mankrit-singh any idea? This looks messy.


<!-- Sent from Reviewable.io -->

2023-03-06 10:22 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 290 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqP3vi0ZX6PTpbcvNP:-NPqROmf22wTZhuI7Xan:b-58hzga) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L290)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

only in this case, we are having the entity in path and the request body
</blockquote></details>

How is this only applicable for this API? Don't we have same use-case for IMPORT or CREATE?


<!-- Sent from Reviewable.io -->

2023-03-06 10:45 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 3. unresolved discussions. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 491 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqNi3T2WxBIp2BincV:-NPqWYYID69GY0FItVxY:b-toa60b) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L491)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

then why is it "internal"? It should be exposed to public, otherwise whats the point of even exposing it on v1 spec and adding all these descriptions etc.
</blockquote></details>

making it external, in the pipeline resource, we had marked the api as hidden, hence marked it internal here


<!-- Sent from Reviewable.io -->

2023-03-06 10:48 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 5. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 286 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOUD57fsjmO34diJD:-NPqX1oyEr9BOf2wCOFw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L286)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

error message is wrong.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 290 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqP3vi0ZX6PTpbcvNP:-NPqX33r-evEr9U7QXav:bauce3j) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L290)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

How is this only applicable for this API? Don't we have same use-case for IMPORT or CREATE?
</blockquote></details>

its not implemented in a way that it has resource identifier in both path and query param


<!-- Sent from Reviewable.io -->

2023-03-06 10:51 UTC, rashminandasahoo requested changes

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      description: Fetches Pipeline YAML from Harness DB and creates a remote entity or Fetches Pipeline YAML from remote repository and creates an inline entity
Creates a remote entity by fetching pipeline YAML from Harness or an inline entity by fetching pipeline YAML from a remote repository.

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      description: 'Request body for pipeline move configuration '
Request body for moving a pipeline configuration.

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
>            description: node id of parent pipeline stage
Node ID of the stage in the parent pipeline.

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      description: 'Response body for pipeline move configuration '
Response body for configuration to move a pipeline.

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      description: Move config operation type
How about "Operation type to move the configuration."?

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      description: Contains parameters related to moving an Entity for Git Experience.
Parameters related to moving an entity for Git Experience.

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          description: File path of the Entity in the repository.
```suggestion
          description: File path of the entity in the repository.
```

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          description: Commit message used for the merge commit.
```suggestion
          description: Merge commit message.
```

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          description: Name of the default branch (this checks out a new branch titled by branch_name).
```suggestion
          description: Default branch name. This checks out the branch titled branch_name.
```

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          description: Identifier of the Harness Connector used for CRUD operations on the Entity.
```suggestion
          description: Harness connector id used for entity CRUD operations.
```

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +      description: Response body for Pipeline move-config.
Response body for moving a pipeline configuration.

2023-03-06 10:51 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
>        description: Input Set update request body
```suggestion
      description: Request body to update input set.
```

2023-03-06 11:11 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 1 change requests. 19. unresolved discussions. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 479 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-479:-NPqZcO19boStcjCG32z:b-lhs69o) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L479)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

Creates a remote entity by fetching pipeline YAML from Harness or an inline entity by fetching pipeline YAML from a remote repository.
</blockquote></details>

done, thanks
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1850 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1850:-NPq_w_M1w0cQDpbm61R:b-1smjhi) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1850)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

Node ID of the stage in the parent pipeline.
</blockquote></details>

Not part of this pr change
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1856 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1856:-NPq_5EN7q85j6_PTuuT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1856)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

Request body for moving a pipeline configuration.
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1869 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1869:-NPq_5-w8GSj5DOn1f4R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1869)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

Response body for configuration to move a pipeline.
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1878 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1878:-NPq_76A1tZCv81DcpKn:bbvy7v0) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1878)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

How about "Operation type to move the configuration."?
</blockquote></details>

done, yes
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1884 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1884:-NPq_FQWB9dJyFErNd5P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1884)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

Parameters related to moving an entity for Git Experience.
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1896 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqNx1v98tw9gT-15KA:-NPqa3xT0LiD889fiGvo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1896)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't we be very descriptive here? Eg: Name of the branch where we want to create the remote entity in case of moving pipeline from INLINE to REMOTE or from where we want to fetch the remote entity in case of moving pipeline from REMOTE to INLINE
?
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1899 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1899:-NPqa3c6EDXcL_DU-vcp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1899)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

```suggestion
          description: File path of the entity in the repository.
```
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1902 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1902:-NPqa3EfEFWOX90fQI3F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1902)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

```suggestion
          description: Merge commit message.
```
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1905 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1905:-NPqa5fsAnJaYFQ-kdNM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1905)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

```suggestion
          description: Default branch name. This checks out the branch titled branch_name.
```
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1905 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOE-oDhwT8OYms4pp:-NPqa30ZDYf4HzTpblbg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1905)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this isn't clear at all.
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1908 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-1908:-NPqa6p25hy6NFkSfKzt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L1908)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

```suggestion
          description: Harness connector id used for entity CRUD operations.
```
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2493 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-2493:-NPq_fYy6NSXdghqsnGj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L2493)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

Response body for moving a pipeline configuration.
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2996 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r6-2996:-NPq_mO85TePqqLDPjnV:b-1smjhi) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/contracts/openapi/v1/openapi.yaml#L2996)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

```suggestion
      description: Request body to update input set.
```
</blockquote></details>

Not part of this pr change


<!-- Sent from Reviewable.io -->

2023-03-06 11:13 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 2 file(s) to review. 1 change requests. 20. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 382 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqPV3l5CyYV2UiWk5D:-NPqbq_V-NSgau72NUSd:b-xi0t0l) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L382)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we should create a method that just creates GitEntityInfo object based on input arguments. This way no one needs to understand logic behind setting up new branch field or any other field.
</blockquote></details>

As of now, for all the apis, this how the GitEntityInfo objects are being set, we can take this up as a separate optimisation ticket.


<!-- Sent from Reviewable.io -->

2023-03-06 11:29 UTC, rashminandasahoo submitted a review, later dismissed

2023-03-06 11:29 UTC, rashminandasahoo commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          description: Name of the branch where we want to create the remote entity in case of moving pipeline from INLINE to REMOTE or from where we want to fetch the remote entity in case of moving
```suggestion
          description: Name of the branch. When moving an inline pipeline or a remote pipeline, this branch is where the remote entity is created or fetched.
```

2023-03-06 11:33 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 2 file(s) to review. 21. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1896 at r7](https://reviewable.io/reviews/harness/harness-core/44680#-NPbFKzUeJBKplWPNur5-r7-1896:-NPqg_I070FQFUVUVll-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/453ed318693657097d532ae702a4fbaa3aaef6a6/pipeline-service/contracts/openapi/v1/openapi.yaml#L1896)):*
<details><summary><i>Previously, rashminandasahoo wrote…</i></summary><blockquote>

```suggestion
          description: Name of the branch. When moving an inline pipeline or a remote pipeline, this branch is where the remote entity is created or fetched.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 11:56 UTC, rashminandasahoo approved these changes

2023-03-06 12:35 UTC, mankrit-singh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 2 file(s) to review. 21. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 284 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOZo90xr8Urf0Ud49:-NPquOYL44wBhSMM48fd:b-lobr93) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L284)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@mankrit-singh any idea? This looks messy.
</blockquote></details>

yes, this mostly lilkely comes from the swagger codegen library used to generate this
will try to fix it


<!-- Sent from Reviewable.io -->

2023-03-07 06:42 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 284 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOZo90xr8Urf0Ud49:-NPunbI52V9Z7HFrkUVh:bhdbaef) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L284)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

yes, this mostly lilkely comes from the swagger codegen library used to generate this
will try to fix it
</blockquote></details>

@mankrit-singh lets create a bug for tracking purpose. We should fix it soon otherwise whole of our code-base will become untidy.


<!-- Sent from Reviewable.io -->

2023-03-07 06:43 UTC, mohitg0795 approved these changes
> Reviewed 1 of 4 files at r2, 1 of 2 files at r5, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 2 file(s) to review. 13. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-07 06:46 UTC, mankrit-singh approved these changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 13. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-07 06:47 UTC, adivishy1 commented
trigger ut1

2023-03-07 08:01 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 13. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 284 at r6](https://reviewable.io/reviews/harness/harness-core/44680#-NPqOZo90xr8Urf0Ud49:-NPunHOA8mVl9rUhTF7-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c21ed2e7e1b0888f0f6de03684dca7a7d437a9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L284)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@mankrit-singh lets create a bug for tracking purpose. We should fix it soon otherwise whole of our code-base will become untidy.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-07 08:53 UTC, vaibhav-si approved these changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: 13. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-07 08:57 UTC, rashminandasahoo approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44680)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-07 09:02 UTC, merged