fix: [CDS-54040]: error handling for FileNotFoundException while rend…
harness/harness-core pull request #44771
Opened 2023-03-06 16:26 UTC by achyuth-harness

…ering helm template

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-07 06:44 UTC, GoelPratyush99 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44771)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-07 10:21 UTC, abosii-harness requested changes

2023-03-07 10:21 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java
> +    } else if (lowerCaseMessage.contains("chart.yaml file is missing")) {
We need to handle the case when user doesn't provide an existing subchart

2023-03-08 14:36 UTC, achyuth-harness reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44771#-:-NQ0dgug2YuFBEnR_wkl:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/44771#-NPrv2ce17nyAZtL0E8e-r2-148:-NQ0dedSAuX7VjSNm37K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e5c01822c936f3bd041cdf53348b3f18ca06f50/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java#L148)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We need to handle the case when user doesn't provide an existing subchart
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-10 10:47 UTC, abosii-harness approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44771)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-10 11:53 UTC, GoelPratyush99 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44771)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-10 11:57 UTC, merged