feat:[CDS-54489]: TFCloud Code refactor
harness/harness-core pull request #44927
Opened 2023-03-09 11:36 UTC by alebuh

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-09 13:05 UTC, alebuh commented
trigger feature-build

2023-03-09 13:16 UTC, tmacari-harness requested changes
> Reviewed 4 of 48 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44927)* status: 48 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/steps/TerraformCloudRunStep.java` line 304 at r1](https://reviewable.io/reviews/harness/harness-core/44927#-NQ5T2rpB4h_tvXwavPj:-NQ5T2rpB4h_tvXwavPk:b-mp0o6z) ([raw file](https://github.com/harness/harness-core/blob/c1a55f097103697ec60b2caddb80710290e18613/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/steps/TerraformCloudRunStep.java#L304)):*
> ```Java
>     helper.saveTerraformCloudPlanOutput(planSpecParameters, runId, ambiance);
>     return getTerraformCloudRunOutcome(
>         runId, policyChecksJsonFileId, isExportJson ? tfPlanJsonFileId : null, provisionIdentifier, null);
> ```

Can we simply pass tfPlanJsonFileId without any condition?
If it is coming in response, means we generated it, which means isExportJson was true.


<!-- Sent from Reviewable.io -->

2023-03-09 13:44 UTC, tmacari-harness requested changes
> Reviewed 42 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44927)* status: 48 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraformcloud/TerraformCloudTaskNG.java` line 435 at r1](https://reviewable.io/reviews/harness/harness-core/44927#-NQ5_959CGZ3Ls_V-_Yf:-NQ5_959CGZ3Ls_V-_Yg:bbzbgdu) ([raw file](https://github.com/harness/harness-core/blob/c1a55f097103697ec60b2caddb80710290e18613/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraformcloud/TerraformCloudTaskNG.java#L435)):*
> ```Java
>       String entityId, PlanType planType) {
>     String jsonPlan = terraformCloudTaskHelper.getJsonPlan(credentials.getUrl(), credentials.getToken(), runData);
>     return jsonPlan != null ? terraformCloudTaskHelper.uploadJsonFile(accountId, getDelegateId(), getTaskId(), entityId,
> ```

IMHO it would be more readable if we extract nested condition. Sonar also would complain about it
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/terraformcloud/response/TerraformCloudRefreshTaskResponse.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/44927#-NQ5aHQKCIX5K00ZyHFh:-NQ5aHQKCIX5K00ZyHFi:b-38hvdk) ([raw file](https://github.com/harness/harness-core/blob/c1a55f097103697ec60b2caddb80710290e18613/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/terraformcloud/response/TerraformCloudRefreshTaskResponse.java#L22)):*
> ```Java
> @SuperBuilder
> @EqualsAndHashCode(callSuper = true)
> public class TerraformCloudRefreshTaskResponse extends TerraformCloudDelegateTaskResponse {
> ```

Let's also return runId and add it to output


<!-- Sent from Reviewable.io -->

2023-03-09 14:49 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/TerraformCloudParamsMapper.java
> +    return planType != null ? planType == PlanType.APPLY ? io.harness.delegate.task.terraformcloud.PlanType.APPLY
minor, is it not better to use "&&" ? instead of  the first "?"

2023-03-09 14:52 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 30 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44927)* status: 48 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-09 15:00 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/steps/TerraformCloudRunStep.java
> +  private TerraformCloudRunOutcome handlePlanAndAndDestroyResponse(
minor typo: AndAnd

2023-03-09 15:16 UTC, alebuh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44927)* status: 48 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/TerraformCloudParamsMapper.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/44927#-NQ59CNsyEaFq_h20r39-r2-147:-NQ5w1as4VvX9HqmTBcK:b-89wmjk) ([raw file](https://github.com/harness/harness-core/blob/62743d3dc77a4e47c073164c06ab092996874d79/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/TerraformCloudParamsMapper.java#L147)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

minor, is it not better to use "&&" ? instead of  the first "?" 
</blockquote></details>

changed this to avoid using nested if with "?"


<!-- Sent from Reviewable.io -->

2023-03-10 08:06 UTC, tmacari-harness approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44927)* status: 48 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-10 08:40 UTC, vlica-harness approved these changes
> Reviewed 18 of 48 files at r1, 28 of 30 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44927)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-10 08:48 UTC, merged