fix: [CDS-54346]: Resolving service inputs to fetch references
harness/harness-core pull request #45043
Opened 2023-03-13 09:57 UTC by vivekkarnatiharness

## Describe your changes
When we pass connectorref as a service inputs,Entity frame work is not resolving inputs.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-14 05:01 UTC, yogesh-chauhan commented
Lets fix the description of the PR. We should mention the exact thing that this PR is fixing

2023-03-15 04:59 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java` line 51 at r4](https://reviewable.io/reviews/harness/harness-core/45043#-NQYchgA5ZKxPtEv2lmD:-NQYchgA5ZKxPtEv2lmE:b-j7vztc) ([raw file](https://github.com/harness/harness-core/blob/2b3ef0eebd86957ae93b67e8f7126e0d523277ac/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java#L51)):*
> ```Java
>   @Inject ServiceEntitySetupUsageHelper serviceEntitySetupUsageHelper;
>   @Inject EntitySetupUsageService entitySetupUsageService;
>   private static final String FQN_SEPARATOR = ".";
> ```

FQN_SEPARATOR is unused


<!-- Sent from Reviewable.io -->

2023-03-15 05:04 UTC, yogesh-chauhan requested changes

2023-03-15 05:04 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +          serviceEntityService.get(accountIdentifier, orgIdentifier, projectIdentifier, serviceRefString, false);
if service entity is not found, lets return from here. We should not fail in that case
Also please verify with org/account scoped service

2023-03-15 05:04 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +          serviceEntitySetupUsageHelper.getAllReferredEntities(serviceEntity.get());
instead of finding all setup usages again, can we not make an API call to get all referred entities of the service because they would have been saved when the service was created/updated ?

2023-03-15 05:04 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +      if (serviceYamlV2.serviceInputs.getValue() != null) {
Lets use ParameterField.isNotNull(serviceYamlV2.getServiceInputs()) also and !serviceYamlV2.getServiceInputs().isExpression()

2023-03-15 05:04 UTC, yogesh-chauhan reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45043)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-15 11:43 UTC, vivekkarnatiharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +      if (serviceYamlV2.serviceInputs.getValue() != null) {
Done.

2023-03-15 11:44 UTC, vivekkarnatiharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +          serviceEntitySetupUsageHelper.getAllReferredEntities(serviceEntity.get());
There is a limitation here.Db is storing only one runtime input type of entity,if we have more than one.

2023-03-15 18:45 UTC, yogesh-chauhan reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45043)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java` line 121 at r5](https://reviewable.io/reviews/harness/harness-core/45043#-NQa_fHrCFWhLYOqBRFb:-NQa_fHrCFWhLYOqBRFc:b-friub) ([raw file](https://github.com/harness/harness-core/blob/61c7fe71d220a3b3b916ab244714679209c4d729/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java#L121)):*
> ```Java
>                   orgIdentifier, projectIdentifier, entityDetailProtoDTO.getIdentifierRef().getMetadataMap().get("fqn"),
>                   obj.textValue(), entityDetailProtoDTO.getType(), true);
>               result.add(entityDetailProtoDTOFinal);
> ```

Lets validate the cases
- no service inputs
- everything is fixed in the service
- few runtime inputs
- runtime inputs in the service inputs do not match with the service inputs in the entity


<!-- Sent from Reviewable.io -->

2023-03-15 18:46 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45043)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-17 12:59 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45043)* status: 5 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-21 04:52 UTC, utkarshchoubey-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45043#-:-NR1VnVXBCGZBkRJNXja:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-03-21 06:51 UTC, vivekkarnatiharness commented
trigger ut6

2023-03-21 06:51 UTC, vivekkarnatiharness commented
trigger ut9

2023-03-21 06:52 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-03-21 09:11 UTC, vivekkarnatiharness commented
trigger ut0

2023-03-21 09:11 UTC, vivekkarnatiharness commented
trigger ut9

2023-03-21 17:34 UTC, vivekkarnatiharness commented
trigger ut6

2023-03-21 17:52 UTC, tchaurasiya approved these changes
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45043)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-21 18:28 UTC, merged