feat: [SRM-14138]: implementation of GET APIs for secondary events
harness/harness-core pull request #45076
Opened 2023-03-13 23:04 UTC by karansaraswat19

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-14 05:34 UTC, naveen-harness reviewed
Please update/add unit-tests for these class as well 
--  srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
-- srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness
/cvng/downtime/services/impl/EntityUnavailabilityStatusesServiceImpl.java
-- srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/services/impl/DowntimeServiceImpl.java

2023-03-14 05:34 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java
> +  public ResponseDTO<List<SecondaryEventsResponse>> getSecondaryEvents(
Since it's a list API, the identifier should be before the resource you're fetching, i.e. `{identifier}/secondary-events`. 
`/secondary-events/{identifier}` is giving an impression that you're trying to fetch single secondary-event with the given uuid.

2023-03-14 05:34 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java
> +  @NGAccessControlCheck(resourceType = SLO, permission = VIEW_PERMISSION)
Why identifier is part of path param in the list API, and it's in the QueryParam in this GET API ? I think We should keep it consistent.

2023-03-14 05:34 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java
> +        annotationService.getAllInstancesGrouped(projectParams, startTime / 1000, endTime / 1000, identifier));
what is `startTime/1000` ? If you're converting seconds to milliseconds please use dedicated java library.

2023-03-14 05:34 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java
> +        EntityUnavailabilityStatuses instance = entityUnavailabilityStatusesService.getInstanceById(uuids.get(0));
What if uuids is empty, could you check for IndexOutOfBoundException here ?

2023-03-14 05:34 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java
> +            projectParams, startTime / 1000, endTime / 1000);
Use library to convert seconds to millis

2023-03-14 05:34 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImplTest.java
> +}
Please write unit-tests for all public methods

2023-03-14 09:00 UTC, karansaraswat19 commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java
> +  @NGAccessControlCheck(resourceType = SLO, permission = VIEW_PERMISSION)
identifiers is the list of uuids I will be getting from the frontend, it's not sloIdentifier

2023-03-14 10:15 UTC, Varsha-lalwani requested changes
> Reviewed 9 of 26 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45076)* status: 17 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/EntityUnavailabilityInstance.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQULeZo3RGptNSWL8Li:-NQULeZp6Y7iedfG-Q0_:b-vd0av6) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/EntityUnavailabilityInstance.java#L18)):*
> ```Java
> @Value
> @Builder
> public class EntityUnavailabilityInstance {
> ```

Why have we created this new class? We already have EntityUnavailabilityStatuses where we have everything of this
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/EntityUnavailabilityInstanceDetails.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUVdQ-90qa2ILdEIT0:-NQUVdQ00uLLoweXnedL:b-uji606) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/EntityUnavailabilityInstanceDetails.java#L18)):*
> ```Java
> @Value
> @Builder
> public class EntityUnavailabilityInstanceDetails extends SecondaryEventDetails {
> ```

Since this is just for downtime, rename it to DowntimeEventDetails



_Code quote:_
```Java
EntityUnavailabilityInstanceDetails
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationInstance.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUV0Ak3UjaRwWx3OVo:-NQUV0Ak3UjaRwWx3OVp:bpdp23t) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationInstance.java#L22)):*
> ```Java
> public class AnnotationInstance {
>   @NotNull String uuid;
>   @NotNull String message;
> ```

We decided to send all the list of messages together. this should be list



_Code quote:_
```Java
@NotNull String message;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventDetailsResponse.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUU_no8OznxtfYAkep:-NQUU_no8OznxtfYAkeq:bpidl2k) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventDetailsResponse.java#L24)):*
> ```Java
>   @JsonProperty(SECONDARY_EVENTS_TYPE) @NotNull SecondaryEventsType type;
>   @NotNull long startTime;
>   @NotNull long endTime;
> ```

For every Secondary event, startTime will be same but it's not necessary that endTime will be same as well. this start and endTime we should remove from here, we already have at details level



_Code quote:_
```Java
  @NotNull long startTime;
  @NotNull long endTime;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventsType.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUSjev0nAV7bVRbrqx:-NQUSjev0nAV7bVRbrqy:bxbrxeh) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventsType.java#L14)):*
> ```Java
> public enum SecondaryEventsType {
>   @JsonProperty("Downtime") DOWNTIME,
>   @JsonProperty("DataCollectionFailed") DATA_COLLECTION_FAILED,
> ```

DATA_COLLECTION_FAILURE



_Code quote:_
```Java
ATA_COLLECTION_FAILED
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/45076#-NQSD4H9g4NBCpOAh6Xd-r1-219:-NQURsd13DlkPESLBLuR:buk8you) ([raw file](https://github.com/harness/harness-core/blob/59c63058e416affd6f20672b6d2cbfa4c4fe2d15/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L219)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Since it's a list API, the identifier should be before the resource you're fetching, i.e. `{identifier}/secondary-events`. 
`/secondary-events/{identifier}` is giving an impression that you're trying to fetch single secondary-event with the given uuid. 
</blockquote></details>

https://docs.google.com/presentation/d/1wEKqeRPI-rDGyhlBf2jVbYG28Owa6i1taSFS1EVF160/edit#slide=id.g13367422017_0_60 According to API Standard it's correct
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java` line 236 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUT-Li3ywG1BzFEdZj:-NQUT-Li3ywG1BzFEdZk:b-aeunbv) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L236)):*
> ```Java
>   public ResponseDTO<SecondaryEventDetailsResponse> getSecondaryEventDetails(
>       @NotNull @Valid @QueryParam("secondaryEventType") SecondaryEventsType type,
>       @QueryParam("identifiers") List<String> uuids) {
> ```

Make it notNull and Valid



_Code quote:_
```Java
@QueryParam("identifiers") List<String> uuids)
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUaZbi8oMAVlEcdDt9:-NQUaZbi8oMAVlEcdDtA:bnxdj9z) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L98)):*
> ```Java
>                                        .order(Sort.ascending(AnnotationKeys.createdAt))
>                                        .asList();
>     if (isEmpty(annotationIds) || annotations.size() != annotationIds.size()) {
> ```

when will this happen



_Code quote:_
```Java
annotations.size() != annotationIds.size()
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUabdyAOI4aLWQy8wy:-NQUabdyAOI4aLWQy8wz:b-2vtr13) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L98)):*
> ```Java
>                                        .order(Sort.ascending(AnnotationKeys.createdAt))
>                                        .asList();
>     if (isEmpty(annotationIds) || annotations.size() != annotationIds.size()) {
> ```

this check should be at the resource level



_Code quote:_
```Java
isEmpty(annotationIds)
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUazTk3JoM-N [...]

2023-03-14 19:43 UTC, karansaraswat19 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45076)* status: 28 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationInstance.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUV0Ak3UjaRwWx3OVo:-NQUwu_M37M11RKdXt-W:b229ijh) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationInstance.java#L22)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

We decided to send all the list of messages together. this should be list
</blockquote></details>

this is a single entity with uuid, using AnnotationInstanceDetails which has a list of AnnotationInstance
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventDetailsResponse.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUU_no8OznxtfYAkep:-NQWcwhcCC4SAoRdPaWK:b-894as6) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventDetailsResponse.java#L24)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

For every Secondary event, startTime will be same but it's not necessary that endTime will be same as well. this start and endTime we should remove from here, we already have at details level
</blockquote></details>

Done as discussed
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventsType.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUSjev0nAV7bVRbrqx:-NQUziR320QiNHwRJLbC:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/secondaryEvents/SecondaryEventsType.java#L14)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

DATA_COLLECTION_FAILURE
</blockquote></details>

Done
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUabdyAOI4aLWQy8wy:-NQWdKAL1UD474szYsKp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L98)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

this check should be at the resource level
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUaZbi8oMAVlEcdDt9:-NQWdKqo7tt_uksyWCPZ:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L98)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

when will this happen
</blockquote></details>

Removed
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUazTk3JoM-NjRJz7X:-NQWdJIL8FoOfK1JY3uD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L116)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

add a validation that all staartTimes are same, or remove this startTime field altogether from here. Endtime we shouldn't have anyways, as it will be same for annottaions but not for downtime
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 573 at r1](https://reviewable.io/reviews/harness/harness-core/45076#-NQSD4H9g4NBCpOAh6Xh-r1-573:-NQWdRnb9r-2qvIUr6mw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/59c63058e416affd6f20672b6d2cbfa4c4fe2d15/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L573)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

what is `startTime/1000` ? If you're converting  milliseconds to seconds please use dedicated java library. 
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 544 at r2](https://reviewable.io/reviews/harness/harness-core/45076#-NQSD4H9g4NBCpOAh6Xh-r2-544:-NQWdNQc60hndVAetU0o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16f39b33db0a67a81deefa83a5bffa263697d31d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L544)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Use library to convert millis to seconds
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 585 at r2](https://reviewable.io/reviews/harness/harness-core/45076#-NQSD4H9g4NBCpOAh6Xh-r2-585:-NQWdSQy8HeY-aCh9M3e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16f39b33db0a67a81deefa83a5bffa263697d31d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L585)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

What if uuids is empty, could you check for IndexOutOfBoundException here ?
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 558 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUWKydCQZ_ROSb-2KX:-NQWdOTu-HYMN-zdOPi-:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L558)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

We don't have a plan to show DC failure instances on UI right now or do we?
</blockquote></details>

Removed
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 566 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUWqyp7GOsFqe9JkYx:-NQWdR4s2IUM3TcUimF-:b-896fix) ([raw file](https://github.com/harness [...]

2023-03-15 04:12 UTC, naveen-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45076)* status: 29 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/45076#-NQSD4H9g4NBCpOAh6Xd-r1-219:-NQYScJ33ANbDHJVe1WA:b-f0c16r) ([raw file](https://github.com/harness/harness-core/blob/59c63058e416affd6f20672b6d2cbfa4c4fe2d15/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L219)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

https://docs.google.com/presentation/d/1wEKqeRPI-rDGyhlBf2jVbYG28Owa6i1taSFS1EVF160/edit#slide=id.g13367422017_0_60 According to API Standard it's correct
</blockquote></details>

Checked the doc, in this case resource is seconday-events and {identifier} should be unique but it's not. So it should e query param instead of path param. 


<!-- Sent from Reviewable.io -->

2023-03-15 07:59 UTC, Varsha-lalwani approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 26 files at r1, 1 of 5 files at r2, 13 of 17 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45076#-:-NQZGwYy1WR-_eZ1BsfK:bnfp4nl)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/services/api/DowntimeService.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/45076#-NQZCYUd6my76y6un6Np:-NQZCYUd6my76y6un6Nq:b-i85cpb) ([raw file](https://github.com/harness/harness-core/blob/5cbfae469b40b6c22b1c4a098e999bee91b546f3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/services/api/DowntimeService.java#L55)):*
> ```Java
>       List<EntityUnavailabilityStatusesDTO> entityUnavailabilityStatusesDTOS, Set<String> monitoredServiceIdentifier);
> 
>   List<EntityUnavailabilityStatuses> filterDowntimeInstancesOnMSs(ProjectParams projectParams,
> ```

nit: rename it to filterDowntimeInstancesOnMonitoredServices(method overloading)



_Code quote:_
```Java
filterDowntimeInstancesOnMSs
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/45076#-NQSD4H9g4NBCpOAh6Xd-r1-219:-NQZEcFlAo4TIuMU1cyQ:b-yrxou4) ([raw file](https://github.com/harness/harness-core/blob/59c63058e416affd6f20672b6d2cbfa4c4fe2d15/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L219)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Checked the doc, in this case resource is seconday-events and {identifier} should be unique but it's not. So it should e query param instead of path param. 
</blockquote></details>

Since we don't have project params in the path param, identifier won't be considered unique. You are right. But since we already follow the path param way in this and other resources, we can go either way.


<!-- Sent from Reviewable.io -->

2023-03-15 08:20 UTC, deepak-harness approved these changes
> Reviewed 6 of 26 files at r1, 1 of 5 files at r2, 5 of 6 files at r3, 15 of 17 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45076)* status: 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-15 08:57 UTC, karansaraswat19 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45076)* status: 1 change requests. 3. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java` line 236 at r3](https://reviewable.io/reviews/harness/harness-core/45076#-NQUT-Li3ywG1BzFEdZj:-NQZU832Bk3zU19fL7_r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3ec96137faa216fd6df3eccc0bf8fd04825542e7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L236)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Make it notNull and Valid
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-15 09:51 UTC, naveen-harness approved these changes
> Reviewed 1 of 26 files at r1, 4 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45076)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-15 09:53 UTC, merged