[feat]: [CDS-55807]: Support CaseFormat for Identifiers
harness/harness-core pull request #45089
Opened 2023-03-14 05:41 UTC by arvind-choudhary-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-14 06:59 UTC, puthrayaharness requested changes

2023-03-14 06:59 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/expressions/AppVariablesCamelCaseMigratorFunctor.java
> +    return "<+variable." + MigratorUtility.generateIdentifier((String) key, CaseFormat.LOWER_CASE) + ">";
Do we need to fix this to CamelCase? Also, can we instead add the case format to the constructor instead?

2023-03-14 06:59 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/expressions/AppVariablesLowerCaseMigratorFunctor.java
> +  public synchronized Object get(Object key) {
Can we instead use constructor & pass the format? Instead of multiple classes

2023-03-14 06:59 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/service/CreateProjectService.java
> +  public List<ProjectCreateResultDTO> bulkCreateProjects(String accountId, String apiKey,
Can we add the caseFormat as a parameter to BulkCreateProjectsDTO?

2023-03-14 06:59 UTC, puthrayaharness commented on 100-migrator/src/main/java/io/harness/ngmigration/expressions/SecretMigratorFunctor.java
> -  public Object getValue(String secretName) {
Why did we remove this? Does this have no usage?

2023-03-14 07:19 UTC, arvind-choudhary-h commented on 100-migrator/src/main/java/io/harness/ngmigration/expressions/SecretMigratorFunctor.java
> -  public Object getValue(String secretName) {
yeah, no usage.

2023-03-14 07:22 UTC, abhinav-harness approved these changes
> Reviewed 158 of 158 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45089)* status: 158 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-14 19:06 UTC, puthrayaharness approved these changes

2023-03-15 00:13 UTC, abhinav-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45089#-:-NQXbI1cDnQX_f7gREWk:bnfp4nl)* status: 160 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-15 05:37 UTC, puthrayaharness commented
trigger messagecheck

2023-03-15 05:37 UTC, puthrayaharness approved these changes
> Reviewed 134 of 158 files at r1, 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45089)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-15 05:38 UTC, puthrayaharness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45089#-:-NQYlglP29E_j9QoPpz5:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-15 05:39 UTC, puthrayaharness commented
trigger messagecheck

2023-03-15 05:40 UTC, merged