feat: [CDS-50126]: AWS SDK Client Backoff Strategy
harness/harness-core pull request #45231
Opened 2023-03-16 10:44 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-20 15:21 UTC, rohitk-h requested changes
> Reviewed 24 of 32 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45231)* status: Some of the checks are too old. 38 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsNgConfigMapper.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/45231#-NQzZRua7cufhybQTYxQ:-NQzZRua7cufhybQTYxR:b1gt6c8) ([raw file](https://github.com/harness/harness-core/blob/ea08f520dcf8aeab2de9c20f79ce4a667b0a930a/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/AwsNgConfigMapper.java#L130)):*
> ```Java
>         awsSdkClientBackoffStrategyDTO.getBackoffStrategyConfig();
>     if (awsSdkClientBackoffStrategyDTO.getAwsSdkClientBackoffStrategyType()
>         == AwsSdkClientBackoffStrategyType.FIXED_DELAY_BACKOFF_STRATEGY) {
> ```

nitpick: can use switch case like other files. 
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsSdkClientBackoffStrategyDTO.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/45231#-NQzZqab2Yf0DBdVgruQ:-NQzZqab2Yf0DBdVgruR:b-vqe216) ([raw file](https://github.com/harness/harness-core/blob/ea08f520dcf8aeab2de9c20f79ce4a667b0a930a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsSdkClientBackoffStrategyDTO.java#L30)):*
> ```Java
> @ApiModel("AwsSdkClientBackoffStrategy")
> @JsonDeserialize(using = AwsSdkClientBackoffStrategyDTODeserializer.class)
> @Schema(name = "AwsSdkClientBackoffStrategy", description = "This contains details of the AWS connector credential")
> ```

Is this description correct? 
___
*[`960-api-services/src/main/java/io/harness/aws/v2/ecs/EcsV2ClientImpl.java` line 341 at r2](https://reviewable.io/reviews/harness/harness-core/45231#-NQz_VwH3BplSMCyMUiD:-NQz_VwI-rDieWCoci5s:b-efuc69) ([raw file](https://github.com/harness/harness-core/blob/ea08f520dcf8aeab2de9c20f79ce4a667b0a930a/960-api-services/src/main/java/io/harness/aws/v2/ecs/EcsV2ClientImpl.java#L341)):*
> ```Java
>         .credentialsProvider(getAwsCredentialsProvider(awsConfig))
>         .region(Region.of(region))
>         .overrideConfiguration(getClientOverrideConfiguration(awsConfig, true))
> ```

instead of hardcoding boolean values, can we have a common function to derive this value? 


<!-- Sent from Reviewable.io -->

2023-03-21 05:30 UTC, PragyeshMishra01 commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsConnectorDTO.java
>    Set<String> delegateSelectors;
It dont seems to be backward compatible to me.
We should add it at the end otherwise how will older version delegate handle it?
Lets test backward compatibility with older version delegate here.

2023-03-21 05:32 UTC, PragyeshMishra01 requested changes
lets test backward compatibility here.

2023-03-23 10:22 UTC, alluvamsi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsConnectorDTO.java
>    Set<String> delegateSelectors;
I test plan I have mentioned the backward compatability tests that I have tested

2023-03-23 11:14 UTC, PragyeshMishra01 submitted a review, later dismissed

2023-03-26 12:54 UTC, sainath-b approved these changes

2023-03-27 10:08 UTC, alluvamsi-harness commented
trigger ut8

2023-03-27 11:52 UTC, alluvamsi-harness commented
trigger messagecheck

2023-03-27 15:30 UTC, rohitk-h approved these changes
> Reviewed 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45231)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-28 06:44 UTC, PragyeshMishra01 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45231)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-28 06:47 UTC, merged