feat: [PIE-8995]: OPA api onboard to java client to check if OPA governance should be done or not
harness/harness-core pull request #45323
Opened 2023-03-18 08:15 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-20 04:21 UTC, namanvermah requested changes

2023-03-20 04:21 UTC, namanvermah commented on 950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java
> +public class OpaResponse {
Too generic a name, can you change this to something else?

2023-03-20 04:21 UTC, namanvermah commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/GovernanceServiceImpl.java
> +        OpaResponse opaResponse = SafeHttpCall.executeWithExceptions(opaServiceClient.evaluateWithCredentials(
@archit-harness we're supposed to check for this before json expansion right?

2023-03-20 04:41 UTC, archit-harness reviewed
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/45323#-NQnmZwZyaIhGQmFybVF-r2-21:-NQxJbR72DFVG3Uq7dza:b32v57) ([raw file](https://github.com/harness/harness-core/blob/724bc78f5faee0aa99f4c47f07a501c84d989390/950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java#L21)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Too generic a name, can you change this to something else?
</blockquote></details>

+1
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/GovernanceServiceImpl.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/45323#-NQnmZwZyaIhGQmFybVG-r2-60:-NQxJedSBJdyDd7Hlwfp:b32v57) ([raw file](https://github.com/harness/harness-core/blob/724bc78f5faee0aa99f4c47f07a501c84d989390/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/GovernanceServiceImpl.java#L60)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

@archit-harness we're supposed to check for this before json expansion right?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-03-20 05:55 UTC, mohitg0795 commented
*[`950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQx_NltBmwQ1n7NeyOI:-NQx_NltBmwQ1n7NeyOJ:b-c08ehr) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java#L17)):*
> ```Java
> import lombok.Data;
> 
> @Data
> ```

I think we won't need a @setter here, only a @getter should be fine. [@data = @setter + @getter]


<!-- Sent from Reviewable.io -->

2023-03-20 05:56 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/GovernanceServiceImpl.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/45323#-NQnmZwZyaIhGQmFybVG-r2-60:-NQx_Zak-IWCrYYknDTb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/724bc78f5faee0aa99f4c47f07a501c84d989390/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/GovernanceServiceImpl.java#L60)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/45323#-NQnmZwZyaIhGQmFybVF-r2-21:-NQx_b1s-J_MSBRhdkDD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/724bc78f5faee0aa99f4c47f07a501c84d989390/950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-20 05:57 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQx_x5G704p7Umgfn3L:-NQx_x5G704p7Umgfn3M:b-zbz1b6) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java#L69)):*
> ```Java
>     }
>     try {
>       OpaResponse opaResponse = SafeHttpCall.executeWithExceptions(
> ```

this code should move to some helper class. Its related to how do we call HTTP APIs. Also its used at multiple places.


<!-- Sent from Reviewable.io -->

2023-03-20 05:58 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQxa6a-9Z2xPdf-PMR9:-NQxa6a-9Z2xPdf-PMRA:ble5iz4) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java#L81)):*
> ```Java
>     } catch (Exception ex) {
>       log.error("Exception while evaluating OPA rules", ex);
>       throw new InvalidRequestException("Exception while evaluating OPA rules: " + ex.getMessage(), ex);
> ```

we should throw proper exception here, instead of a generic one.


<!-- Sent from Reviewable.io -->

2023-03-20 13:21 UTC, archit-harness requested changes
> Reviewed 2 of 5 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 7 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 112 at r4](https://reviewable.io/reviews/harness/harness-core/45323#-NQzAUVP7CVu0ZkfPrON:-NQzAUVP7CVu0ZkfPrOO:b-9udn12) ([raw file](https://github.com/harness/harness-core/blob/19ecd719db453751893f71ac2f719c5bd81a3415/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L112)):*
> ```Java
>       } catch (Exception ex) {
>         log.error("Exception while evaluating OPA rules", ex);
>         throw new InvalidRequestException("Exception while evaluating OPA rules: " + ex.getMessage(), ex);
> ```

Can you introduce one more exception, OPAPolicyEvaluationException
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQx_x5G704p7Umgfn3L:-NQzAbRP1dCfoMm6Y1to:b-q20lbs) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java#L69)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this code should move to some helper class. Its related to how do we call HTTP APIs. Also its used at multiple places.
</blockquote></details>

+1 as its used in above class as well
___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQx_NltBmwQ1n7NeyOI:-NQz9tpKCtzQsujktvSD:b15b8rw) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we won't need a @setter here, only a @getter should be fine. [@data = @setter + @getter]
</blockquote></details>

We should use @value, for apis always or getters as mohit shared


<!-- Sent from Reviewable.io -->

2023-03-20 14:47 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 11 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 112 at r4](https://reviewable.io/reviews/harness/harness-core/45323#-NQzAUVP7CVu0ZkfPrON:-NQzHIGU2jSMhop3pZKq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/19ecd719db453751893f71ac2f719c5bd81a3415/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you introduce one more exception, OPAPolicyEvaluationException
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQx_x5G704p7Umgfn3L:-NQzJoyl1SfqimJdxlN4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1 as its used in above class as well
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQxa6a-9Z2xPdf-PMR9:-NQzHJDy4tobq2G1gHc6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should throw proper exception here, instead of a generic one.
</blockquote></details>

Done.
___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/45323#-NQx_NltBmwQ1n7NeyOI:-NQzGO8u6DH09pY2G1Sq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a17f5ab6204569160e6ab8518c0383a6aa38401/950-opa-client/src/main/java/io/harness/opaclient/model/OpaResponse.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should use @value, for apis always or getters as mohit shared
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 09:15 UTC, namanvermah requested changes

2023-03-21 09:15 UTC, namanvermah commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java
> +        if (!opaPolicyEvaluationHelper.shouldEvaluatePolicy(accountId, orgIdentifier, projectIdentifier,
We dont need this here as the expanded json has already been calculated.

2023-03-21 09:15 UTC, namanvermah commented on pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java
> +      log.error("Exception while evaluating OPA rules", ex);
add this catch inside `shouldEvaluate` instead of here. This is because any exception that comes from json expansion needs to propagate rather than being caught here

2023-03-21 09:19 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NR2SiJJ9sf8RjSyO5I2:-NR2SiJJ9sf8RjSyO5I3:b29a3bu) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java#L23)):*
> ```Java
>   @Inject OpaServiceClient opaServiceClient;
> 
>   public boolean shouldEvaluatePolicy(String accountId, String orgId, String projectId, String type, String action)
> ```

conventionally the field names are "orgIdentifier, projectIdentifier, accountIdentifier" etc, lets keep it consistent.


<!-- Sent from Reviewable.io -->

2023-03-21 09:20 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java` line 25 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NR2St2R7DTe_1OvbvQV:-NR2St2R7DTe_1OvbvQW:babfhwd) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java#L25)):*
> ```Java
>   public boolean shouldEvaluatePolicy(String accountId, String orgId, String projectId, String type, String action)
>       throws IOException {
>     OpaShouldEvaluateResponse opaShouldEvaluateResponse = SafeHttpCall.executeWithExceptions(
> ```

Shouldn't we catch the exception here and throw OpaEvaluationException from here itself? Then its centrally configured.


<!-- Sent from Reviewable.io -->

2023-03-21 09:21 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NR2THDw3huPRd78PVbk:-NR2THDw3huPRd78PVbl:bm9dhs5) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java#L23)):*
> ```Java
>   @Inject OpaServiceClient opaServiceClient;
> 
>   public boolean shouldEvaluatePolicy(String accountId, String orgId, String projectId, String type, String action)
> ```

we can use Enum value instead of string for type and action, thats much better.


<!-- Sent from Reviewable.io -->

2023-03-21 09:32 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 14 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NR2SiJJ9sf8RjSyO5I2:-NR2VkJsA_P883WprN1W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

conventionally the field names are "orgIdentifier, projectIdentifier, accountIdentifier" etc, lets keep it consistent.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NR2THDw3huPRd78PVbk:-NR2Vl9yExrpUSAMIXzA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can use Enum value instead of string for type and action, thats much better.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java` line 25 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NR2St2R7DTe_1OvbvQV:-NR2Vmr749yURro26618:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OpaPolicyEvaluationHelper.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Shouldn't we catch the exception here and throw OpaEvaluationException from here itself? Then its centrally configured.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java` line 79 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NQxZ0uTGWTOuoC_JqF8-r7-79:-NR2Vp917bn0x6S3Vll-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java#L79)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

add this catch inside `shouldEvaluate` instead of here. This is because any exception that comes from json expansion needs to propagate rather than being caught here
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NQxZ0uTGWTOuoC_JqF6-r7-98:-NR2VqX2D3KE9tnY6DfD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L98)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

We dont need this here as the expanded json has already been calculated. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 10:14 UTC, shalini-agr commented
trigger ut3

2023-03-21 10:30 UTC, shalini-agr commented
trigger ut9

2023-03-22 05:34 UTC, archit-harness reviewed
> Reviewed 1 of 8 files at r5, 3 of 4 files at r6, 6 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 14 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NQxZ0uTGWTOuoC_JqF6-r7-98:-NR6nqqg2xs4otN_Yweg:b-b2yqqi) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L98)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why its not needed here?


<!-- Sent from Reviewable.io -->

2023-03-22 05:42 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 14 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NQxZ0uTGWTOuoC_JqF6-r7-98:-NR6oBmm3TN2tAY73k0s:b-mmeecj) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L98)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why its not needed here?
</blockquote></details>

Json expansion is already done at this point. 

In any case, there would be at least one call to policy manager, and if we do call should evaluate and if it returns true, we would essentially be making two requests to the policy manager, one for should evaluate and the other to actually evaluate the policies. 


<!-- Sent from Reviewable.io -->

2023-03-22 06:46 UTC, mohitg0795 approved these changes
> Reviewed 2 of 5 files at r3, 1 of 5 files at r4, 1 of 8 files at r5, 3 of 4 files at r6, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-23 06:56 UTC, shalini-agr commented
trigger ut2

2023-03-23 07:21 UTC, namanvermah requested changes
> Reviewed 1 of 5 files at r4, 1 of 8 files at r5, 1 of 4 files at r6, 1 of 7 files at r8, 11 of 12 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 13 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/PolicyAction.java` line 13 at r10](https://reviewable.io/reviews/harness/harness-core/45323#-NRCK_q56Vt_ckLMFxNj:-NRCK_q56Vt_ckLMFxNk:bzc30mu) ([raw file](https://github.com/harness/harness-core/blob/1c1e4eb80c3fa5b74d1d247309a5752aa9d8ca92/950-opa-client/src/main/java/io/harness/opaclient/model/PolicyAction.java#L13)):*
> ```Java
> import io.harness.annotations.dev.OwnedBy;
> 
> @OwnedBy(HarnessTeam.PIPELINE) public enum PolicyAction { onrun, onsave }
> ```

can you keep enum names in all caps?


<!-- Sent from Reviewable.io -->

2023-03-23 07:21 UTC, namanvermah reviewed
> Reviewed 1 of 5 files at r3, 3 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-23 07:40 UTC, archit-harness reviewed
> Reviewed 1 of 7 files at r8, 4 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 8 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/PolicyAction.java` line 13 at r10](https://reviewable.io/reviews/harness/harness-core/45323#-NRCK_q56Vt_ckLMFxNj:-NRCPDO054L9zAGJuj5c:b-5v7sdt) ([raw file](https://github.com/harness/harness-core/blob/1c1e4eb80c3fa5b74d1d247309a5752aa9d8ca92/950-opa-client/src/main/java/io/harness/opaclient/model/PolicyAction.java#L13)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

can you keep enum names in all caps?
</blockquote></details>

Moving to constant as previously used


<!-- Sent from Reviewable.io -->

2023-03-23 08:43 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 12 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-opa-client/src/main/java/io/harness/opaclient/model/PolicyAction.java` line 13 at r10](https://reviewable.io/reviews/harness/harness-core/45323#-NRCK_q56Vt_ckLMFxNj:-NRCcnuX6CyrDRbZs_1z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c1e4eb80c3fa5b74d1d247309a5752aa9d8ca92/950-opa-client/src/main/java/io/harness/opaclient/model/PolicyAction.java#L13)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Moving to constant as previously used
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-23 09:52 UTC, shalini-agr commented
trigger ut4

2023-03-24 06:14 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 12 files at r9, 12 of 12 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/45323#-NQxZ0uTGWTOuoC_JqF6-r7-98:-NRHFIDR0Uon3z8tkEnz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/80f2028bdd1781a764fdff5df5baa194f356fb2d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategy.java#L98)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Json expansion is already done at this point. 

In any case, there would be at least one call to policy manager, and if we do call should evaluate and if it returns true, we would essentially be making two requests to the policy manager, one for should evaluate and the other to actually evaluate the policies. 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-03-27 04:02 UTC, namanvermah submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 12 of 12 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323#-:-NRWDlHaEYuYsYRDIA1q:bnfp4nl)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-03-27 04:36 UTC, namanvermah approved these changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: 3 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-03-27 05:14 UTC, shalini-agr commented
trigger ut5

2023-03-27 05:24 UTC, shalini-agr commented
trigger ut9

2023-03-27 05:43 UTC, archit-harness approved these changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45323)* status: Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-03-27 06:21 UTC, merged