Cds 50514
harness/harness-core pull request #45345
Opened 2023-03-20 07:25 UTC by boopesh007

## Describe your changes
Applied RBAC on the Instances query which will filter only the instances to which the user has access. (Whichever the services the user has READ access)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-20 22:26 UTC, Fernando-Dourado requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45345)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java` line 353 at r1](https://reviewable.io/reviews/harness/harness-core/45345#-NR076kv0_wDZcGJ621q:-NR076kv0_wDZcGJ621r:bmxl1e7) ([raw file](https://github.com/harness/harness-core/blob/f9a56d57b22ecd397bea50fd12410185ae3e0810/400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java#L353)):*
> ```Java
> 
>   @Override
>   public Map<String, Set<String>> getAppSvcMapFromUserPermissions(
> ```

Please, add unit tests to cover the new scenarios.


<!-- Sent from Reviewable.io -->

2023-03-21 07:45 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java
> +      UserRequestContext userRequestContext = UserThreadLocal.get().getUserRequestContext();
UserThreadLocal.get()!=null

2023-03-21 07:46 UTC, abhinav-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java
> +      UserRequestContext userRequestContext = UserThreadLocal.get().getUserRequestContext();
private boolean hasUserContext() {
    User user = UserThreadLocal.get();
    return user != null && user.getUserRequestContext() != null;
  }

2023-03-21 10:51 UTC, boopesh007 commented
*[`400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java` line 353 at r1](https://reviewable.io/reviews/harness/harness-core/45345#-NR076kv0_wDZcGJ621q:-NR2mq-cBkdEzgIRxTlM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9a56d57b22ecd397bea50fd12410185ae3e0810/400-rest/src/main/java/software/wings/service/impl/UsageRestrictionsServiceImpl.java#L353)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Please, add unit tests to cover the new scenarios.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 10:51 UTC, boopesh007 commented
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 646 at r1](https://reviewable.io/reviews/harness/harness-core/45345#-NQxuEP86icmP9DnICLR-r1-646:-NR2mqwj0AOig1xz5YsJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9a56d57b22ecd397bea50fd12410185ae3e0810/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L646)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

  private boolean hasUserContext() {
    User user = UserThreadLocal.get();
    return user != null && user.getUserRequestContext() != null;
  }
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 11:24 UTC, Fernando-Dourado approved these changes
> Reviewed 1 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45345)* status: 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-21 21:18 UTC, abhinav-harness reviewed
> Reviewed 2 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45345)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-21 21:18 UTC, abhinav-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45345)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-22 07:12 UTC, VikasMaddukuriHarness approved these changes
> Reviewed 2 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45345)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-22 07:29 UTC, merged