feat: [CDS-55809]: Enabling App Resize Instance Count as the Target
harness/harness-core pull request #45435
Opened 2023-03-21 23:06 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-22 10:41 UTC, RishabhGupta34 requested changes

2023-03-22 10:41 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasAppResizeStep.java
> +        && TasInstanceCountType.FROM_MANIFEST.equals(instanceCountType)) {
shouldn't `ignoreInstanceCountManifest` be used instead of `TasInstanceCountType.FROM_MANIFEST.equals(instanceCountType)` ?

2023-03-22 10:41 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasAppResizeStep.java
> +        && TasInstanceCountType.FROM_MANIFEST.equals(instanceCountType)) {
also can you change this to nested if else, instead of else if, so that there is no condition missed?

2023-03-22 16:04 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasAppResizeStep.java
> +        && TasInstanceCountType.FROM_MANIFEST.equals(instanceCountType)) {
if TasInstanceCountType is MATCH_RUNNING_INSTANCES and ignoreInstanceCountManifest is enabled, I think there is no need throw error

2023-03-22 16:06 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasAppResizeStep.java
> +        && TasInstanceCountType.FROM_MANIFEST.equals(instanceCountType)) {
As we already ignore instance count from manifest, I think its ok even if ignoreInstanceCountManifest is enabled when TasInstanceCountType is MATCH_RUNNING_INSTANCES

2023-03-23 17:08 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasAppResizeBaseStepInfo.java
> +  ParameterField<Boolean> ignoreInstanceCountManifest;
Yes, I added that case in test plan as well

2023-03-24 04:43 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasAppResizeStep.java
> +        return upsizeInstanceCount;
this logic is still not correct, if it's percentage and match running instance, it will return 100% always.

2023-03-24 09:24 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasAppResizeStep.java
> +        return upsizeInstanceCount;
Implemented now in a nested loop, separated the cases for Matching Running Instances and FromManifest

2023-03-24 10:26 UTC, sourabh-awashti reviewed
> Reviewed 5 of 7 files at r1, 2 of 4 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45435)* status: 13 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-24 10:27 UTC, sourabh-awashti approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45435)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-24 10:27 UTC, RishabhGupta34 approved these changes
> Reviewed 5 of 7 files at r1, 2 of 4 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45435)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-24 10:28 UTC, RishabhGupta34 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45435)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-24 10:32 UTC, alluvamsi-harness commented
trigger messagecheck

2023-03-24 10:33 UTC, merged