feat: [CDS-54459]: Adding Instance Sync V2 proto for NG
harness/harness-core pull request #45463
Opened 2023-03-22 09:24 UTC by namantalaycha10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-22 09:55 UTC, abosii-harness requested changes
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45463)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustomImpl.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/45463#-NR7jH_TAXOWYCmmTxwf:-NR7jH_UAPihU_EjPe2K:b9hoq2n) ([raw file](https://github.com/harness/harness-core/blob/664fe1466b3b05a4db2ad897daed7f45914b9f8c/126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustomImpl.java#L2)):*
> ```Java
> /*
> <<<<<<< HEAD
> ```

merge conflict
___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/45463#-NR7jQ2g5CHF2WzEC_mN:-NR7jQ2h6L0Cs6u9nJEE:b-n65x4t) ([raw file](https://github.com/harness/harness-core/blob/664fe1466b3b05a4db2ad897daed7f45914b9f8c/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java#L83)):*
> ```Java
> 
>     List<K8sDeploymentReleaseData> deploymentReleaseList =
>         populateDeploymentReleaseList(infrastructureMappingDTO, deploymentInfoDTOList, infrastructureOutcome);
> ```

We shouldn't need this it may end up in duplicate capabilities. You should create capabilities only based on the connector. Either duplicate the logic, create a helper, etc.


<!-- Sent from Reviewable.io -->

2023-03-27 07:05 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45463)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/45463#-NR7jQ2g5CHF2WzEC_mN:-NRWsj1m2g4hjOPK7QCd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/664fe1466b3b05a4db2ad897daed7f45914b9f8c/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java#L83)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We shouldn't need this it may end up in duplicate capabilities. You should create capabilities only based on the connector. Either duplicate the logic, create a helper, etc.
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustomImpl.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/45463#-NR7jH_TAXOWYCmmTxwf:-NRWskj73SV3fbmMFjYz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/664fe1466b3b05a4db2ad897daed7f45914b9f8c/126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustomImpl.java#L2)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

merge conflict
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-27 09:25 UTC, abosii-harness requested changes
> Reviewed 2 of 11 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45463)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/45463#-NRXNOd52fcuVEGHDBsI:-NRXNOd52fcuVEGHDBsJ:b-g664ff) ([raw file](https://github.com/harness/harness-core/blob/77cac694d9616885e7ea0af892ab4b5f570387c9/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java#L209)):*
> ```Java
>     }
> 
>     return K8sTaskCapabilityHelper.fetchRequiredExecutionCapabilities(connectorInfoDTO.getConnectorConfig(), null,
> ```

What about GKE, AKS, etc? We should have a Utility class that based on the type of connector get capabilities


<!-- Sent from Reviewable.io -->

2023-03-27 09:26 UTC, abosii-harness requested changes

2023-03-27 09:26 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java
> +  @Inject private CDFeatureFlagHelper cdFeatureFlagHelper;
Should use accountClient, this cdFeatureFlagHelper is not working properly in NG

2023-03-28 06:27 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45463)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/45463#-NRXNOd52fcuVEGHDBsI:-NRatgUU13c69L9LKiIt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/77cac694d9616885e7ea0af892ab4b5f570387c9/126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java#L209)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about GKE, AKS, etc? We should have a Utility class that based on the type of connector get capabilities
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-28 08:56 UTC, abosii-harness requested changes

2023-03-28 08:56 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +          instanceSyncPerpetualTaskService.resetPerpetualTask(infrastructureMappingDTO.getAccountIdentifier(),
We will need to handle resetPerpetualTask with a different method

2023-03-28 08:56 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +              instanceSyncPerpetualTaskService.isInstanceSyncV2Enabled() ? infrastructureMappingDTO.getConnectorRef()
either always set as connector ref either null

2023-03-28 11:35 UTC, achyuth-harness approved these changes
> Reviewed 3 of 11 files at r1, 1 of 3 files at r4, 1 of 4 files at r5, 4 of 4 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45463)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-28 11:35 UTC, merged