[feat]: [CDS-53693]: EKS client-go plugin integration
harness/harness-core pull request #45512
Opened 2023-03-23 06:33 UTC by lovish1999

## Describe your changes
EKS client-go plugin integration & addition of EKS V2 Client classes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-24 06:55 UTC, lovish1999 commented
https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/IMImages/pipelines/publishimmutabledelegatetest/executions/CNJ_lJqGSpexrdWKVohiqw/pipeline. - Pipeline for verifying if the new eks delegate dependency has any vulnerability.

2023-03-24 07:53 UTC, abhinavsingh1196 requested changes
> Reviewed 13 of 18 files at r1, 2 of 5 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHWScO5lrYoV7bkhpM:-NRHWScO5lrYoV7bkhpN:b507vd7) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L21)):*
> ```Java
> import static org.mockito.Matchers.any;
> import static org.mockito.Mockito.doReturn;
> import static org.powermock.api.mockito.PowerMockito.mock;
> ```

shouldn't use powermockito
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 151 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHWbn35sjAOp4mvJmS:-NRHWbn35sjAOp4mvJmT:b-vy44uh) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L151)):*
> ```Java
>                        .build());
>   }
> }
> ```

also please add some tests for negative cases here
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 2376 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHVbxNAm3Nuu2ZMVgQ:-NRHVbxNAm3Nuu2ZMVgR:b-v7yo0z) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2376)):*
> ```Java
>   }
> 
>   public String generateExecFormatKubeconfig(KubernetesConfig config) {
> ```

missing @Override annotation?
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java` line 221 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHUo6Q-0MWIKsvhOQv:-NRHUo6R3ogz3EBjLiq8:b-pyxdzu) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java#L221)):*
> ```Java
>       + "source ~/.bashrc\n";
>   String EKS_AUTH_PLUGIN_BINARY = "aws-iam-authenticator";
>   String EKS_AUTH_PLUGIN_INSTALL_HINT = "";
> ```

to be added? we can provide a link to relevant AWS docs
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 36 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHYAMv8X_cEFtJujr2:-NRHYAMv8X_cEFtJujr3:b-hdl3g5) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L36)):*
> ```Java
>     } else {
>       shouldUseExecFormat = runCommand(binaryName + " --version", logCallback);
>     }
> ```

String commandToRun = getCommandToRun(binaryName)
boolean shouldUseExecFormat = runCommand(binaryName + commandToRun, logCallback);


String getCommandToRun(String binaryName) {
  if (binaryName == EKS) return " version"

  return " --version"
}
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRDRojTCvbhJguIc3TV:-NRDRojTCvbhJguIc3TW:b63bk3w) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L56)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.CDP)
> public class AwsEKSV2DelegateTaskHelper {
> ```

why is it EKS v2? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRDXW1b8XuceiViQOzB:-NRDXW1b8XuceiViQOzC:bau15e8) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L72)):*
> ```Java
>     }
>     String[] regionClusterName = regionAndClusterName.split(REGION_DELIMITER);
>     if (regionClusterName.length < 2) {
> ```

should this be != 2 ?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 63 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHZQ8m1LxIKI41HHIH:-NRHZQ8n-PnrlSp7DBFA:b-axlxnj) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L63)):*
> ```Java
>   public static final String EKS_KUBECFG_ENV_VARS_AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID";
>   public static final String EKS_KUBECFG_ENV_VARS_AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY";
>   public static final String EKS_KUBECFG_ARGS_I = "-i";
> ```

let's move all these constants(and any other constants present) to a new class AwsEksConstants
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 100 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHT0hdEjEJ0CoUuGiU:-NRHT0hdEjEJ0CoUuGiV:bjd5qlh) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L100)):*
> ```Java
>       return kubernetesConfigBuilder.build();
>     }
>     return null;
> ```

if we can't resolve the cluster, I think we should just throw an exception instead of continuing
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 111 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRH_A7q7eDqE39Ct1Ej:-NRH_A7q7eDqE39Ct1Ek:bm9653w) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L111)):*
> ```Java
> 
>     if (awsInternalConfig.getAccessKey() != null) {
>       EnvVariables awsAccessKey = new EnvVariables();
> ```

this class should be named `EnvVariable`? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 133 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHaYwd-VkK3p0RTi6p:-NRHaYwd-VkK3p0RTi6q:b-m0bnwf) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L133)):*
> ```Java
>       String crossAccountRoleArn = awsInternalConfig.getCrossAccountAttributes().getCrossAccountRoleArn();
>       String externalId = awsInternalConfig.getCrossAccountAttributes().getExternalId();
>       if (isNotEmpty(crossAccountRoleArn)) {
> ```

let's throw exception during awsInternalConfig creation if cross account ARN is enabled but empty, so we don't have to add this check here
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 149 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRH_vCb3XDSla3xQI24:-NRH_vCb3XDSla3xQI25:bxdld9y) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L149)):*
> ```Java
> 
>   public AwsInternalConfig createAwsInternalConfig(AwsConnectorDTO awsConnectorDTO, String region)  [...]

2023-03-24 10:10 UTC, abosii-harness requested changes
> Reviewed 13 of 18 files at r1, 2 of 5 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 87 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI3wscDQYQhwxkhSQA:-NRI3wsd53OySc3F18gG:b-4bygje) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L87)):*
> ```Java
>     doReturn("data").when(certificate).data();
> 
>     // MockedStatic mockedStaticKubernetesAuthPlugin = mockStatic(KubeConfigAuthPluginHelper.class);
> ```

remove commented code
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 117 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI4-rC9lej6pmyWPbn:-NRI4-rC9lej6pmyWPbo:b-adsz14) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L117)):*
> ```Java
>     assertNotNull(env);
>     assertEquals(2, env.size());
>     assertEquals("AWS_ACCESS_KEY_ID", env.get(0).getName());
> ```

Can we use constant values same are we using in the code?
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 32 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI4KlRCbCpSpHbBF4T:-NRI4KlS5uZaK5aShHxf:bq5cso2) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L32)):*
> ```Java
>   public static boolean isExecAuthPluginBinaryAvailable(String binaryName, LogCallback logCallback) {
>     boolean shouldUseExecFormat;
>     if (binaryName == EKS_AUTH_PLUGIN_BINARY) {
> ```

EKS_AUTH_PLUGIN_BINARY.equals(binaryName), I assume it's working for you because you pass the same constant instance, but any refactoring or changes around someone will have a hard time understanding why this may not match
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI0nbx1tEPIZvUPIxU:-NRI0nby-wGWw8wd2TBw:b-z7q7hl) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L71)):*
> ```Java
>       throw new InvalidRequestException("Cluster name is empty in Inframapping");
>     }
>     String[] regionClusterName = regionAndClusterName.split(REGION_DELIMITER);
> ```

split(delimiter, 2) -> will make it better, as any input like region/cluster1/cluster2 will work properly and will result ["region", "cluster1/cluster2"]



_Code quote:_
```Java
split
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 149 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI2aXzAPD-E8od7Dh5:-NRI2aXzAPD-E8od7Dh6:b-byhrkb) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L149)):*
> ```Java
> 
>   public AwsInternalConfig createAwsInternalConfig(AwsConnectorDTO awsConnectorDTO, String region) {
>     AwsInternalConfig awsInternalConfig = AwsInternalConfig.builder().build();
> ```

Let's use Builder for this, AwsInternalConfig.AwsInternalConfigBuilder awsInternalConfigBuilder = AwsInternalConfig.builder();
...
return awsInternalConfigBuilder.build()


<!-- Sent from Reviewable.io -->

2023-03-27 06:38 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: Some of the checks are too old. 2 change requests. 18. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHWScO5lrYoV7bkhpM:-NRWkRe83CjwIjpk4FzL:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L21)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

shouldn't use powermockito
</blockquote></details>

ok
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 87 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI3wscDQYQhwxkhSQA:-NRWkXO15Ozw3Kon2PQX:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L87)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

remove commented code
</blockquote></details>

ok
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 117 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI4-rC9lej6pmyWPbn:-NRWkY5V4SK1q1QYRE7Q:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L117)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we use constant values same are we using in the code?
</blockquote></details>

ok
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java` line 151 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHWbn35sjAOp4mvJmS:-NRWkZ82DloFpN_6IzKR:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/test/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelperTest.java#L151)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

also please add some tests for negative cases here
</blockquote></details>

ok
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 2376 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHVbxNAm3Nuu2ZMVgQ:-NRWlLjB6UN7ZiWlHRAy:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2376)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

missing @Override annotation?
</blockquote></details>

added



_Code quote:_
```Java
generateExecFormatKubeconfig
```
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java` line 221 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHUo6Q-0MWIKsvhOQv:-NRWlNMCAeUafH9OvEKn:b3m9voo) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/970-api-services-beans/src/main/java/io/harness/k8s/K8sConstants.java#L221)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

to be added? we can provide a link to relevant AWS docs
</blockquote></details>

yes. done. 
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 32 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI4KlRCbCpSpHbBF4T:-NRWmPAI0fIxNduFQZ87:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L32)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

EKS_AUTH_PLUGIN_BINARY.equals(binaryName), I assume it's working for you because you pass the same constant instance, but any refactoring or changes around someone will have a hard time understanding why this may not match
</blockquote></details>

ok
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java` line 36 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHYAMv8X_cEFtJujr2:-NRWmLmn-XiLkTxgpcMX:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/KubeConfigAuthPluginHelper.java#L36)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

String commandToRun = getCommandToRun(binaryName)
boolean shouldUseExecFormat = runCommand(binaryName + commandToRun, logCallback);


String getCommandToRun(String binaryName) {
  if (binaryName == EKS) return " version"

  return " --version"
}
</blockquote></details>

ok
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRDRojTCvbhJguIc3TV:-NRIS95f4F8lun5uf7IZ:bujqfi5) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L56)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

why is it EKS v2? 
</blockquote></details>

resolved
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRDXW1b8XuceiViQOzB:-NRISPsV4qp-qwEiT9QA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L72)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

should this be != 2 ?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 63 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRHZQ8m1LxIKI41HHIH:-NRISAD778auKI4c4Yjn:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L63)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

let's move all these constants(and any other constants present) to a new class AwsEksConstants
</blockquote></details>

ok
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/45512#-NRI0nbx1tEPIZvUPIxU:-NRISMm75Ef2rXD0wAnL:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/47846ffdab98cf15655b200e39d40aa88095ea81/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L71)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

split(delimiter, 2) -> will make it better, as any input like region/cluster1/cluster2 will work properly and will result ["region", "cluster1/cluster2"]
</blockquote></details>

ok
___
* [...]

2023-03-27 09:51 UTC, abosii-harness requested changes
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 11 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java` line 2 at r6](https://reviewable.io/reviews/harness/harness-core/45512#-NRXTY2W2G5PIyAI-M47:-NRXTY2W2G5PIyAI-M48:b-trx5wu) ([raw file](https://github.com/harness/harness-core/blob/f8e04572086a7c4f3bc90df4b4fbd2ebe14cb60a/970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

2023 and harness team


<!-- Sent from Reviewable.io -->

2023-03-27 18:12 UTC, abhinavsingh1196 requested changes
please check and resolve any relevant sonar issues

> Reviewed 10 of 11 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512#-:-NRZGKNG6TYzaZvHY_9f:b-2j6140)* status: 1 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java` line 16 at r8](https://reviewable.io/reviews/harness/harness-core/45512#-NRZG-1KEgN7qHm-ESmw:-NRZG-1KEgN7qHm-ESmx:b-3d2xaq) ([raw file](https://github.com/harness/harness-core/blob/97652e8ef6aefd0b657f66c51effec67b16faf17/970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java#L16)):*
> ```Java
> @OwnedBy(CDP)
> public interface EksConstants {
>   String REGION_DELIMITER = "/";
> ```

all fields can be static final
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRDRojTCvbhJguIc3TV:-NRZEfhn71R7CdDTiwb5:b-kkshid) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L56)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

resolved
</blockquote></details>

we're keeping it as EKS v2?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRZF3Bd4icaVKmHEzkm:-NRZF3Bd4icaVKmHEzkn:b-q37fh6) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L137)):*
> ```Java
>         args.add(awsInternalConfig.getCrossAccountAttributes().getCrossAccountRoleArn());
>       }
>       if (isNotEmpty(externalId)) {
> ```

this check is necessary right? we don't want to provide this arg until and unless its provided (since its optional)
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 99 at r8](https://reviewable.io/reviews/harness/harness-core/45512#-NRZEnub57TUuDj3aYvK:-NRZEnub57TUuDj3aYvL:bhfcd75) ([raw file](https://github.com/harness/harness-core/blob/97652e8ef6aefd0b657f66c51effec67b16faf17/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L99)):*
> ```Java
>       }
>       return kubernetesConfigBuilder.build();
>     } else {
> ```

redundant else
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 192 at r8](https://reviewable.io/reviews/harness/harness-core/45512#-NRZFLnf6YKC473Zym_M:-NRZFLnf6YKC473Zym_N:b-aee77z) ([raw file](https://github.com/harness/harness-core/blob/97652e8ef6aefd0b657f66c51effec67b16faf17/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L192)):*
> ```Java
>       }
>       if (isEmpty(externalId)) {
>         throw new InvalidArgumentsException("Aws externalId cannot be empty");
> ```

same comment as above, this is optional when cross account role is selected, so this can be empty. 


<!-- Sent from Reviewable.io -->

2023-03-28 06:25 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 1 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java` line 2 at r6](https://reviewable.io/reviews/harness/harness-core/45512#-NRXTY2W2G5PIyAI-M47:-NRapXe0B2hIZSLrewbe:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f8e04572086a7c4f3bc90df4b4fbd2ebe14cb60a/970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java#L2)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

2023 and harness team
</blockquote></details>

done
___
*[`970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java` line 16 at r8](https://reviewable.io/reviews/harness/harness-core/45512#-NRZG-1KEgN7qHm-ESmw:-NRap_9c5Umb40tFLPCG:b1cpo7h) ([raw file](https://github.com/harness/harness-core/blob/97652e8ef6aefd0b657f66c51effec67b16faf17/970-api-services-beans/src/main/java/io/harness/eks/EksConstants.java#L16)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

all fields can be static final
</blockquote></details>

ok. will make the change in next PR. It is same in k8sconstants. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRDRojTCvbhJguIc3TV:-NRaotqT5jNm_MNbCpWe:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L56)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

we're keeping it as EKS v2?
</blockquote></details>

yes
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/45512#-NRZF3Bd4icaVKmHEzkm:-NRat0Ou2GO5EXoDloAh:bp9998g) ([raw file](https://github.com/harness/harness-core/blob/9585379c6fa78b0f223cd89805cb9992c71be481/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L137)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

this check is necessary right? we don't want to provide this arg until and unless its provided (since its optional)
</blockquote></details>

But you suggested in last review to have this null check during creation of awsinternalconfig. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 99 at r8](https://reviewable.io/reviews/harness/harness-core/45512#-NRZEnub57TUuDj3aYvK:-NRap710-PmL_pteZ7Uz:bqzny8z) ([raw file](https://github.com/harness/harness-core/blob/97652e8ef6aefd0b657f66c51effec67b16faf17/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L99)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

redundant else
</blockquote></details>

Why ? We decided to throw exception in case cluster is null, right ? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java` line 192 at r8](https://reviewable.io/reviews/harness/harness-core/45512#-NRZFLnf6YKC473Zym_M:-NRasrBn4xVFRdRGCZEq:bp9998g) ([raw file](https://github.com/harness/harness-core/blob/97652e8ef6aefd0b657f66c51effec67b16faf17/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java#L192)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

same comment as above, this is optional when cross account role is selected, so this can be empty. 
</blockquote></details>

But you suggested in last review to have this null check during creation of awsinternalconfig. 


<!-- Sent from Reviewable.io -->

2023-03-28 13:27 UTC, abhinavsingh1196 reviewed
> Reviewed 5 of 6 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-03-28 20:35 UTC, raghuAtWings commented
*[`960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel` line 21 at r12](https://reviewable.io/reviews/harness/harness-core/45512#-NRdveFC4SDscPOPIgVr:-NRdveFE3Cg8Mo3ICO-C:bakybp9) ([raw file](https://github.com/harness/harness-core/blob/c7fcd721ee48a21e590357b100e65522b249a965/960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel#L21)):*
> ```Starlark
>         "//999-annotations/src/main/java/io/harness/annotations/dev:module",
>         "@maven//:com_google_inject_guice",
>         "@maven//:software_amazon_awssdk_aws_core",
> ```

why do we need to add all the aws dependencies here?


<!-- Sent from Reviewable.io -->

2023-03-28 20:36 UTC, raghuAtWings requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 5 file(s) to review. 3 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`WORKSPACE` line 5415 at r12](https://reviewable.io/reviews/harness/harness-core/45512#-NRdvpWf4kSPwMRRN41w:-NRdvpWg0LHW-fZlauYE:b-oso67t) ([raw file](https://github.com/harness/harness-core/blob/c7fcd721ee48a21e590357b100e65522b249a965/WORKSPACE#L5415)):*
> ```Starlark
>         "elasticloadbalancingv2",
>         "lambda",
>         "eks",
> ```

we need to scan delegate to see there is no vulnunerabilities added because of it. work with @bharatgoelharness  to scan the delegate image built with this PR


<!-- Sent from Reviewable.io -->

2023-03-29 01:09 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 5 file(s) to review. 3 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`WORKSPACE` line 5415 at r12](https://reviewable.io/reviews/harness/harness-core/45512#-NRdvpWf4kSPwMRRN41w:-NReuR7A4r36y91QYJd8:by9iiw3) ([raw file](https://github.com/harness/harness-core/blob/c7fcd721ee48a21e590357b100e65522b249a965/WORKSPACE#L5415)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we need to scan delegate to see there is no vulnunerabilities added because of it. work with @bharatgoelharness  to scan the delegate image built with this PR
</blockquote></details>

Yes, already did that. https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/IMImages/pipelines/publishimmutabledelegatetest/executions/CNJ_lJqGSpexrdWKVohiqw/pipeline. - Pipeline for verifying if the new eks delegate dependency has any vulnerability.
___
*[`960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel` line 21 at r12](https://reviewable.io/reviews/harness/harness-core/45512#-NRdveFC4SDscPOPIgVr:-NReuHFLAbv3hkMg7RgN:b-2nwn4m) ([raw file](https://github.com/harness/harness-core/blob/c7fcd721ee48a21e590357b100e65522b249a965/960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel#L21)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need to add all the aws dependencies here?
</blockquote></details>

Because we add package level build files now. Same is done for ECS NG. 


<!-- Sent from Reviewable.io -->

2023-03-29 02:07 UTC, raghuAtWings commented
*[`960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel` line 21 at r12](https://reviewable.io/reviews/harness/harness-core/45512#-NRdveFC4SDscPOPIgVr:-NRf6L91EFRp9LRxRogr:bucr6ea) ([raw file](https://github.com/harness/harness-core/blob/c7fcd721ee48a21e590357b100e65522b249a965/960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel#L21)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

Because we add package level build files now. Same is done for ECS NG. 
</blockquote></details>

My question is why you need “regions” “sdk_core” and “aws_core” at this level of you are just adding eks?


<!-- Sent from Reviewable.io -->

2023-03-29 06:47 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 8 file(s) to review. 3 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel` line 21 at r12](https://reviewable.io/reviews/harness/harness-core/45512#-NRdveFC4SDscPOPIgVr:-NRg6j4W90jUbIYVhWpQ:b-nuz365) ([raw file](https://github.com/harness/harness-core/blob/c7fcd721ee48a21e590357b100e65522b249a965/960-api-services/src/main/java/io/harness/aws/v2/eks/BUILD.bazel#L21)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

My question is why you need “regions” “sdk_core” and “aws_core” at this level of you are just adding eks?
</blockquote></details>

Oh Ok. Got it. My Bad, I have made the new changes. Removed these extra duplicate dependencies. 


<!-- Sent from Reviewable.io -->

2023-03-29 08:00 UTC, abosii-harness approved these changes
> Reviewed 1 of 1 files at r9, 4 of 6 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-29 12:56 UTC, lovish1999 commented
trigger ut5

2023-03-29 12:57 UTC, lovish1999 commented
trigger ut0

2023-03-29 14:09 UTC, abhinavsingh1196 approved these changes
> Reviewed 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45512)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-29 14:10 UTC, merged