techdebt: [CDS-57677]: Updating descriptions and docs for APIs
harness/harness-core pull request #45547
Opened 2023-03-23 12:06 UTC by mankrit-singh

## Describe your changes
Updating descriptions and docs for APIs
Deprecating SNAPSHOT folder for IDP
Making server as app.harness.io as opposed to api.harness.io

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-23 12:19 UTC, mankrit-singh commented
trigger messagecheck

2023-03-24 04:32 UTC, vikyathharekal approved these changes
Approving idp-service changes

2023-03-24 12:52 UTC, deepakbolangady requested changes
Please reach out if you wish to discuss any of these comments. Thank you.

2023-03-24 12:52 UTC, deepakbolangady commented on 970-ng-commons/contracts/openapi/v1/openapi.yaml
> +      The current version of our Beta APIs is **to be announced**. This will be a Date Header format, and will be valid only for our Beta APIs.
```suggestion
      The current version of our Beta APIs is yet to be announced. The version number will use the Date Header format and will be valid only for our Beta APIs.
```
(Why do we say "to be announced"? Or were we using this as a placeholder to replace during this merge? Also, where is the Date Header format officially described? Good to check on capitalization. I found many results but not the standard. Is that an RFC? Can we be more specific?)

2023-03-24 12:52 UTC, deepakbolangady commented on 970-ng-commons/contracts/openapi/v1/openapi.yaml
> +      All our Beta APIs have a **Generation** that is represented within API path. For example, the v1 in `app.harness.io/v1/`.
```suggestion
      All our beta APIs are versioned, and the version is included in the path to every API resource. For example, v1 beta APIs begin with `app.harness.io/v1/`, where v1 is the API version.
```
* Is that a generation or a version? I'm assuming version. Let me know if generation is correct (and if generation is correct, replace version in my suggestion.)

2023-03-24 12:52 UTC, deepakbolangady commented on 970-ng-commons/contracts/openapi/v1/openapi.yaml
> +      This number represents the core API and will not change frequently. The Generation will change only if there is a significant departure from the basic underpinnings of the existing API. For exa
```suggestion
      The version number represents the core API and does not change frequently. The version number changes only if there is a significant departure from the basic underpinnings of the existing API. For example, when Harness performs a system-wide refactoring of core concepts or resources.
```

2023-03-24 12:52 UTC, deepakbolangady commented on 970-ng-commons/contracts/openapi/v1/openapi.yaml
> +    There are 3 Pagination headers supported in the Response bodies of Paginated APIs.
```suggestion
    Following are the pagination headers supported in the response bodies of paginated APIs:
```

2023-03-24 12:52 UTC, deepakbolangady commented on 970-ng-commons/contracts/openapi/v1/openapi.yaml
> +      1. X-Total-Elements : Indicates the total number of entries in the Paginated response.
Global change (remove space before the colon):
```suggestion
      1. X-Total-Elements: Indicates the total number of entries in a paginated response.
```
(Also use lowercase: "paginated" globally, unless that's the proper noun in some way (unlikely).)

2023-03-24 12:52 UTC, deepakbolangady commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
>    - name: Org Project
* What is an "org project"? I did not understand the need for "org" as an adjective. Should it be just "Project".

2023-03-24 12:52 UTC, deepakbolangady commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
>    - name: Account Secret
```suggestion
  - name: Account Secrets
```
* We might want to consider using sentence case globally ("Account secrets" instead of "Account Secrets" and "Account connectors" instead of "Account Connectors". Too much uppercase is distracting. The docs team uses sentence case in titles. This is an idea we might want to explore for API docs as well. However, let's discuss before incorporating.).

2023-03-30 08:38 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
>      description: This contains APIs for Organizations.
adding this particular description but we would need more inputs across all APIs to fix this globally

2023-03-30 08:44 UTC, deepakbolangady commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
>    - name: Org Project
Okay, then we can skip this comment. Thanks.

2023-03-30 08:45 UTC, deepakbolangady commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
>    - name: Account Secret
Okay, please skip. Thanks.

2023-03-30 10:02 UTC, mankrit-singh commented
trigger ut0

2023-03-30 14:31 UTC, merged