Idp 247
harness/harness-core pull request #45543
Opened 2023-03-23 11:56 UTC by sarthakkasat

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-23 12:01 UTC, sarthakkasat commented
trigger messagecheck

2023-04-10 04:29 UTC, sarthakkasat commented
trigger ut5

2023-04-10 09:18 UTC, vikyathharekal requested changes

2023-04-10 09:18 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/service/impl/OnboardingServiceImpl.java
> -            String.format(BEARER_TOKEN_FORMAT, backstageServiceSecret),
We might not need this backstageServiceSecret anymore

2023-04-10 09:18 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java
> +  static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Could we rename this to something like alphanumeric

2023-04-10 09:18 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java
> +  static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Can we make these private

2023-04-10 09:18 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java
> +  static String generateSecret() {
Is there a standard library to generate these kinds of secrets?

2023-04-10 09:18 UTC, vikyathharekal commented on idp-service/modules/clients/src/main/java/io/harness/clients/BackstageAuthInterceptor.java
> +        ngSecretService.getDecryptedSecretValue(harnessAccount, null, null, "IDP_BACKEND_SECRET");
Can we use the constant created in provisioning module? Or move the constants to common and use it in both the places?

2023-04-10 09:18 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java
> +  public void createBackstageBackendSecret(String accountIdentifier) {
Can we add a log line in every provisioning method with the accountIdentifier? So that we can get to know what's happening from the logs

2023-04-10 10:42 UTC, sarthakkasat commented
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 122 at r4](https://reviewable.io/reviews/harness/harness-core/45543#gh-1161568335:-NSekX-r7oqZHzjYXi7K:bibldjs) ([raw file](https://github.com/harness/harness-core/blob/017d67c99a0c81346c7e7d3dd5793e0b5c356873/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L122)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Is there a standard library to generate these kinds of secrets?
</blockquote></details>

Did not find any


<!-- Sent from Reviewable.io -->

2023-04-10 10:42 UTC, sarthakkasat commented
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/45543#gh-1161573290:-NSek_0xD0PTbvrKIEqO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/017d67c99a0c81346c7e7d3dd5793e0b5c356873/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L94)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we add a log line in every provisioning method with the accountIdentifier? So that we can get to know what's happening from the logs 
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-10 10:42 UTC, sarthakkasat commented
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/45543#gh-1161567376:-NSekas78Ld1OdqIPer_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/017d67c99a0c81346c7e7d3dd5793e0b5c356873/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L57)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we make these private
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-10 10:42 UTC, sarthakkasat commented
*[`idp-service/src/main/java/io/harness/idp/onboarding/service/impl/OnboardingServiceImpl.java` line 0 at r4](https://reviewable.io/reviews/harness/harness-core/45543#gh-1161565884:-NSekcCMBL_GBulsYmG-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/017d67c99a0c81346c7e7d3dd5793e0b5c356873/idp-service/src/main/java/io/harness/idp/onboarding/service/impl/OnboardingServiceImpl.java#L0)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

We might not need this backstageServiceSecret anymore
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-10 10:42 UTC, sarthakkasat commented
*[`idp-service/modules/clients/src/main/java/io/harness/clients/BackstageResourceClientHttpFactory.java` line 73 at r4](https://reviewable.io/reviews/harness/harness-core/45543#gh-1161560001:-NSekeHC-JSLmweTBUCJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/017d67c99a0c81346c7e7d3dd5793e0b5c356873/idp-service/modules/clients/src/main/java/io/harness/clients/BackstageResourceClientHttpFactory.java#L73)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we remove the unused variable?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-10 10:42 UTC, sarthakkasat commented
*[`idp-service/modules/clients/src/main/java/io/harness/clients/BackstageAuthInterceptor.java` line 45 at r4](https://reviewable.io/reviews/harness/harness-core/45543#gh-1161570253:-NSekfOQ-8xPNpiFGEnK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/017d67c99a0c81346c7e7d3dd5793e0b5c356873/idp-service/modules/clients/src/main/java/io/harness/clients/BackstageAuthInterceptor.java#L45)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we use the constant created in provisioning module? Or move the constants to common and use it in both the places?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-10 12:13 UTC, sarthakkasat commented
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 117 at r5](https://reviewable.io/reviews/harness/harness-core/45543#gh-1161663965:-NSf4L8g1P1X7S_4pjca:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1ce489b2e931abe2dbdf69a8eac43908fff27fb2/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L117)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

`log.info("Created BACKEND_SECRET for account Id - {}", accountIdentifier);`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-10 14:42 UTC, sarthakkasat commented
trigger utAll

2023-04-11 02:30 UTC, sandeepa-kv-jois approved these changes

2023-04-11 04:08 UTC, vikyathharekal approved these changes

2023-04-11 04:08 UTC, vikyathharekal commented
trigger review

2023-04-11 04:12 UTC, merged