fix: [CDS-57721]: remove comments in values.yaml files
harness/harness-core pull request #45557
Opened 2023-03-23 13:16 UTC by achyuth-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-23 13:25 UTC, achyuth-harness commented
trigger messagecheck

2023-03-23 15:45 UTC, abosii-harness requested changes

2023-03-23 16:16 UTC, abosii-harness requested changes

2023-03-23 16:16 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +      modifiedValuesFiles.add(values.replaceAll("\\#.*\n", ""));
There may be an issue if comment is not the full line, for example:
`key: value #cooment \nkey2: "another value"`
This Will result in 
`key: value key2: "another value"`
can you check and confirm?

2023-03-24 13:41 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45557)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/45557#-NRDbHsUo0jzRWWWzeNS-r1-197:-NRIqW-a9jJD-LxGIiWc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85ad728f43ec3bdf6f588264ef13cca9145b0280/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L197)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

There may be an issue if comment is not the full line, for example:
`key: value #cooment \nkey2: "another value"`
This Will result in 
`key: value key2: "another value"`
can you check and confirm?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java` line 778 at r1](https://reviewable.io/reviews/harness/harness-core/45557#-NRDbHsUo0jzRWWWzeNT-r1-778:-NRIqX2n1vFyNlnw0Vlt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85ad728f43ec3bdf6f588264ef13cca9145b0280/125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java#L778)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we add an use case where comments is not at the start of the line but for example:
`key: value # comment`
as well some use cases where (some spaces):
`    # comment`
and one use case carriage return
`# comment \r\n`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-27 06:49 UTC, abhinavsingh1196 reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45557)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/45557#-NRDbHsUo0jzRWWWzeNS-r1-197:-NRWnOkQ4MIzR4ETFKs1:b-niw6ej) ([raw file](https://github.com/harness/harness-core/blob/85ad728f43ec3bdf6f588264ef13cca9145b0280/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L197)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Does this also handle the cases when `#` is present within the value?



_Code snippet (i):_
```Java
key: >-
  some-#-char-present-here
```



_Code snippet (ii):_
```Java
baseurl: "https://abc.xyz/#/api"
```


<!-- Sent from Reviewable.io -->

2023-03-27 09:21 UTC, abosii-harness requested changes

2023-03-27 09:21 UTC, abosii-harness commented on 125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java
> +  public void shouldRemoveCommentsBeforeRendering() {
Let's have some uses cases with nested values
env:
 - abc: abc # abc
 - etc:
      abc: abc #em
      adf: adf.             #abc

2023-03-27 13:20 UTC, achyuth-harness commented
trigger ut7

2023-03-27 13:41 UTC, achyuth-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45557)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/45557#-NRDbHsUo0jzRWWWzeNS-r1-197:-NRYIFii4rd3rTaKSzwv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85ad728f43ec3bdf6f588264ef13cca9145b0280/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L197)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Looks good, just add a isEmpty(values), there is an use case in harness store where this can be null
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java` line 778 at r1](https://reviewable.io/reviews/harness/harness-core/45557#-NRDbHsUo0jzRWWWzeNT-r1-778:-NRYIGWYD6xS9aem5UdJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85ad728f43ec3bdf6f588264ef13cca9145b0280/125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sStepHelperTest.java#L778)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's have some uses cases with nested values
env:
 - abc: abc # abc
 - etc:
      abc: abc #em
      adf: adf.             #abc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-27 17:29 UTC, abhinavsingh1196 approved these changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45557)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-27 18:27 UTC, merged