[feat]: [CDS-56678]: updating Helm chart list versions endpoints and logic
harness/harness-core pull request #45564
Opened 2023-03-23 14:43 UTC by markoharness

## Describe your changes
Endpoints that serve list of Helm chart versions needed to be update so that we support both fixed values and expressions/runtime values.

endpoint **/manifests/helm/chart/version** will be used for fixed configuration (when configuring standalone service or within pipeline configuration)

endpoint **/manifests/helm/v2/chart/version** will be used for pipeline runtime and in this case  one or more of prerequisite fields (connectorRef, chartName, bucket, region, etc...) can be set as expression/runtime as well as fixed value.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-24 08:05 UTC, markoharness commented
trigger feature-build

2023-03-24 08:08 UTC, abosii-harness requested changes

2023-03-24 08:08 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java
> -        helmChartService.getHelmChartVersionDetails(accountId, orgIdentifier, projectIdentifier, serviceRef, fqnPath,
Shouldn't we keep old flow as well here for backward compatibility? What if we release BE without UI changes? Will not fetch charts for runtime screen fail?

2023-03-24 14:29 UTC, markoharness commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java` line 0 at r1](https://reviewable.io/reviews/harness/harness-core/45564#gh-1147236718:-NRJ0aHM3j1fu0lHRgJg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad2a7ae06aa42c3c8880cd0a694d93b2cd0887ea/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/HelmChartVersionResource.java#L0)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Shouldn't we keep old flow as well here for backward compatibility? What if we release BE without UI changes? Will not fetch charts for runtime screen fail?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-24 14:39 UTC, markoharness commented
trigger feature-build

2023-03-27 09:16 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45564)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-28 08:56 UTC, markoharness commented
trigger feature-build

2023-03-28 09:17 UTC, abosii-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45564)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-28 18:35 UTC, markoharness commented
trigger feature-build

2023-03-28 19:44 UTC, markoharness commented
trigger utAll

2023-03-29 07:58 UTC, abosii-harness approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45564)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-29 08:57 UTC, abhinavsingh1196 approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45564)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-03-29 09:13 UTC, merged