Cds 52288
harness/harness-core pull request #45666
Opened 2023-03-27 08:48 UTC by Y0709

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-06 06:22 UTC, Y0709 commented
trigger messagecheck

2023-04-07 11:26 UTC, Y0709 commented
trigger ut4

2023-04-10 11:30 UTC, puthrayaharness requested changes

2023-04-10 11:30 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java
> +    if (!isNull(accountId)) {
`accountId` should always be used with all queries. Please add a notNull check if you expect `accountId` to be coming as `null`.

2023-04-19 05:58 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/HarnessApprovalInstanceDetailsDTO.java
> +  String approvalKey;
We can remove approvalKey from DTO and mapper in first phase

2023-04-19 11:18 UTC, Y0709 commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/HarnessApprovalInstanceDetailsDTO.java
> +  String approvalKey;
done

2023-04-20 09:44 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java
>      if (!USER.equals(principal.getType())) {
Do we need to support api-key here?

2023-04-20 15:14 UTC, Y0709 commented on pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java
>      if (!USER.equals(principal.getType())) {
Not sure about this but this is existing behaviour only

2023-04-25 11:36 UTC, naman-goenka approved these changes

2023-04-25 12:46 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java
>      if (!USER.equals(principal.getType())) {
ok, resolving this for now

2023-04-25 12:48 UTC, merged