feat: [CDS-54976] : plan creation for service hooks
harness/harness-core pull request #45664
Opened 2023-03-27 08:11 UTC by TarunUba1

## Describe your changes
Plan creation changes for service hooks 
## Testing
![Screenshot 2023-04-04 at 6 29 59 PM](https://user-images.githubusercontent.com/106597485/229799590-d8e01376-9538-4152-a8bc-92247e6da116.png)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/45664)

2023-03-31 06:33 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 22 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/IndividualServiceHookStep.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXFOxF8h-8dxbxptpd:-NRqLteu02F_6ot_Sf7I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/IndividualServiceHookStep.java#L35)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why PRE_HOOK?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStep.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXFl1i4UZCIHmf6e2-:-NRqLvjO7kn1NZYhdhDT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStep.java#L46)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we need to do some handling for env overrides? Can you test this?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXH1Mu7zuqfIWbccaj:-NRqLwSlD03_8r-JrF_b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java#L54)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Team should be CDP
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXGh2NBzCc6jRzCG4s:-NRqLxt-DNejEXz6xp2h:bj5cyq) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java#L88)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Any reason why we're doing this? Will it fail if some expressions can't be resolved? If no, then we're good here
</blockquote></details>

No it wouldnt in case of V2 we will get the result as is, for v1 we get null as string
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXGITF0q36hZEqfuKQ:-NRqM4cC9UOfQXoogRev:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java#L124)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This check and log can be removed
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 256 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXHN5F6sng1meY6UBv:-NRqM5yA9iqxMgJPA5nn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L256)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

If it can be null why we're not doing null check?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXI2BM46-Mer_cEBvB:-NRqMYvV4K5m-R-aBXut:beae0g4) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Instead of using NPE can we use contains or whatever is available? 
</blockquote></details>

added comment 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXICD41mS4FM_ThKoo:-NRqMX6X2QYW8dJJfORV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java#L63)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

otherwise this comment should go in lambda body
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXJYzCBCjgUvYI9bmh:-NRqMdyz-0Mx2i6T0CHi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java#L144)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about NativeHelmServiceSpec?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXJzzK4prFXbtJqnb6:-NRqMgDT--drVW0IiQjS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java#L40)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can we have this as private static constant? ImmutableMap.of as an option
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXKS1c3VyDSZDFiJPC:-NRqMhMl08tWxqRDDZzO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java#L108)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

should be right after } 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java` line 228 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXKqwdB4JE2VBxL4WM:-NRqMiIZ5WU8V01u5Uxy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java#L228)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Should return this otherwise is a NPE
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-31 07:36 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 22 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 444 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXH_MEANl4qt2miEBe:-NRq_y7514ieHzted1lR:b2gpu1j) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L444)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: this logic can be part of the servhiceHookWrapper:
getHook() and getHookType() with @JsonIgnore
</blockquote></details>

Will be doing these changes, created the functions.


<!-- Sent from Reviewable.io -->

2023-03-31 07:42 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java
> +      if (file.getPostHook() != null) {
Use functions, to access preHook and postHook now

2023-03-31 07:42 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +                identifier = serviceHookWrapper.getPreHook().getIdentifier();
use existing functions to create prehook postHooks

2023-03-31 07:42 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java
> +import java.util.Set;
unused import

2023-03-31 07:42 UTC, TarunUba1 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java
> +    }
This method can be better , Stream throws null if there is no PreHook or PostHook, need to approach better

2023-03-31 07:47 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java
> +    Optional<ServiceHooksOutcome> serviceHooksOutcome = cdStepHelper.getServiceHooksOutcome(ambiance);
Remove the manager step change

2023-03-31 08:12 UTC, abosii-harness requested changes
> Reviewed 19 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/IndividualServiceHookStep.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/45664#-NRqeIXODPFBGfBLPvrO:-NRqeIXP4WSV2URlEX21:bum0sxz) ([raw file](https://github.com/harness/harness-core/blob/a161f0e2410b2426fc65f9c69e1cc99474ab2f5b/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/IndividualServiceHookStep.java#L63)):*
> ```Java
>         .build();
>   }
>   protected ServiceHook applyConfigFileOverrides(ServiceHookStepParameters stepParameters) {
> ```

applyServiceHookOverrides?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHookStepParameters.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/45664#-NRqew9l5wQIY_27qVzD:-NRqew9l5wQIY_27qVzE:b-2w026a) ([raw file](https://github.com/harness/harness-core/blob/a161f0e2410b2426fc65f9c69e1cc99474ab2f5b/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHookStepParameters.java#L35)):*
> ```Java
>   StoreConfig store;
>   ServiceHookType type;
>   StoreConfig storeOverride;
> ```

Can we wrap all the StepParameters in one class and when we do create it just wrap it in that class
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 444 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXH_MEANl4qt2miEBe:-NRqh5vuCzxZYaJJvVJT:b-y2phu7) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L444)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

Will be doing these changes, created the functions.
</blockquote></details>

And why this changes are checking if PreHook is not null?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXI2BM46-Mer_cEBvB:-NRqhbOt1Ifcy00uOBIV:bq5f03m) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java#L59)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

added comment 
</blockquote></details>

We should check first if node is available and not rely on NPE
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXJzzK4prFXbtJqnb6:-NRqhnbd9jaKnZmmgGyK:bj7hg90) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java#L40)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And can we have this as const in the class?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/45664#-NRqiBriBGWIAec2UA6e:-NRqiBrj7g8QCkgW8lxU:b-usm8nm) ([raw file](https://github.com/harness/harness-core/blob/a161f0e2410b2426fc65f9c69e1cc99474ab2f5b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java#L178)):*
> ```Java
> 
>   @NotNull
>   private static Set<String> getDuplicateIdentifiersHooks(ArrayList<String> identifierStream) {
> ```

Why we can't reuse getDuplicateIdentifiers?


<!-- Sent from Reviewable.io -->

2023-04-03 18:35 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 53 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 823 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXE3njE6JBJVz2Y0fK:-NS7O-ss2g2iDhmNI2ui:b-or45ke) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L823)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this can be just:
return serviceHooksOutcome.map(OptionalOutcome::getOutcome).map(outcome -> (ServiceHooksOutcome) outcome)

</blockquote></details>

couldnt make this fn work, also liked keeping things same as other functions.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/IndividualServiceHookStep.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/45664#-NRqeIXODPFBGfBLPvrO:-NS7OCBX1zMkdTY8r4Nk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a161f0e2410b2426fc65f9c69e1cc99474ab2f5b/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/IndividualServiceHookStep.java#L63)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

applyServiceHookOverrides?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHookStepParameters.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/45664#-NRqew9l5wQIY_27qVzD:-NS7OEBa-30ZvwtKW_lN:b-aiam9t) ([raw file](https://github.com/harness/harness-core/blob/a161f0e2410b2426fc65f9c69e1cc99474ab2f5b/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHookStepParameters.java#L35)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we wrap all the StepParameters in one class and when we do create it just wrap it in that class
</blockquote></details>

Do we still need this change as we were thinking of doing so when overrides were there but as they are no longer there we can continue
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 444 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXH_MEANl4qt2miEBe:-NS7OQ4t1rIoQX5EvPK-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L444)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

And why this changes are checking if PreHook is not null?
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXI2BM46-Mer_cEBvB:-NS7OTVc0M0hW6oskG4H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We should check first if node is available and not rely on NPE
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/45664#-NRqLTgKnUHMu_YyOPFe-r2-103:-NS7Oc--4JLxCL-6GC5G:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a161f0e2410b2426fc65f9c69e1cc99474ab2f5b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java#L103)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

This method can be better , Stream throws null if there is no PreHook or PostHook, need to approach better
</blockquote></details>

done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/45664#-NRqiBriBGWIAec2UA6e:-NS7OfLE1_P8WAYnxgcr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a161f0e2410b2426fc65f9c69e1cc99474ab2f5b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java#L178)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why we can't reuse getDuplicateIdentifiers?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-04 07:47 UTC, abosii-harness requested changes
> Reviewed 18 of 27 files at r3, 12 of 14 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 53 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 444 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSACzJQCLR9xqe3j4c1:-NSACzJQCLR9xqe3j4c2:b-3zd32q) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L444)):*
> ```Java
>         return ((KubernetesServiceSpec) serviceSpec)
>             .getServiceHooks()
>             .stream()
> ```

let's add filter(f -> f.getHook() != null)
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 456 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSAD3QyA7hv7e3cZd8n:-NSAD3QyA7hv7e3cZd8o:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L456)):*
> ```Java
>         return ((NativeHelmServiceSpec) serviceSpec)
>             .getServiceHooks()
>             .stream()
> ```

Same here
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADC7wBBXoQoWXBlC7:-NSADC7wBBXoQoWXBlC8:b-1w6ne3) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java#L34)):*
> ```Java
>   @Inject KryoSerializer kryoSerializer;
> 
>   private static final Map<String, Set<String>> supportedTypes =
> ```

SUPPORTED_TYPES as is a static const
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java` line 234 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADJHa8uq6aozEf1lk:-NSADJHa8uq6aozEf1ll:bmusbmw) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java#L234)):*
> ```Java
>         serviceHookWrappers.forEach(serviceHookWrapper -> {
>           String hookType = serviceHookWrapper.getHookType();
>           ServiceHook serviceHook = serviceHookWrapper.getHook();
> ```

Let's have a null check
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 12249 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSAE1YW5sciol7rCfUO:-NSAE1YW5sciol7rCfUP:bfyicn6) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L12249)):*
> ```JSON
>       "type": "object",
>       "properties": {
>         "hook": {
> ```

Hook and HookType shouldn't be part of the schema, json ignore should handle this
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java` line 62 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADrfv-eQ4miyFzcJS:-NSADrfv-eQ4miyFzcJT:bj4jmgm) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java#L62)):*
> ```Java
>   }
> 
>   public String getHookType() {
> ```

Add @JsonIgnore
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADusT5VVO-eMAjVzX:-NSADusT5VVO-eMAjVzY:bj4jmgm) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java#L69)):*
> ```Java
>   }
> 
>   public ServiceHook getHook() {
> ```

Add @JsonIgnore


<!-- Sent from Reviewable.io -->

2023-04-04 11:32 UTC, TarunUba1 commented
trigger ut3

2023-04-05 03:35 UTC, TarunUba1 commented
trigger ut5, it7

2023-04-05 03:38 UTC, TarunUba1 commented
trigger ut7

2023-04-05 05:19 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 54 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 444 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSACzJQCLR9xqe3j4c1:-NSEqZCc2kXGrWwVSzdC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L444)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's add filter(f -> f.getHook() != null)
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 456 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSAD3QyA7hv7e3cZd8n:-NSEqZ_A6MXByCsmNJ8p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L456)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 12249 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSAE1YW5sciol7rCfUO:-NSEqaOz9_DDnm7VfiMo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L12249)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Hook and HookType shouldn't be part of the schema, json ignore should handle this
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java` line 62 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADrfv-eQ4miyFzcJS:-NSEqaoQ0JDEwIpVUXhb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java#L62)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Add @JsonIgnore
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java` line 69 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADusT5VVO-eMAjVzX:-NSEqb7NCVKMunD6MJJm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/127-cd-nextgen-entities/src/main/java/io/harness/cdng/hooks/ServiceHookWrapper.java#L69)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Add @JsonIgnore
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-05 06:07 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 54 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADC7wBBXoQoWXBlC7:-NSF0eMD6wEKMcBjvaJ6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/IndividualServiceHookPlanCreator.java#L34)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

SUPPORTED_TYPES as is a static const
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java` line 234 at r5](https://reviewable.io/reviews/harness/harness-core/45664#-NSADJHa8uq6aozEf1lk:-NSF0eiM-Q8ja4BtwK7e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84fce61f3a5fec46da83c5c0ab2d773fc05499bf/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/servicehook/ServiceHooksPlanCreator.java#L234)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's have a null check
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-05 08:28 UTC, abosii-harness requested changes
> Reviewed 1 of 27 files at r3, 18 of 18 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 54 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 8702 at r7](https://reviewable.io/reviews/harness/harness-core/45664#-NSFVv4q5LjMMcPEx_ji:-NSFVv4q5LjMMcPEx_jj:bn6g4s7) ([raw file](https://github.com/harness/harness-core/blob/0dad251f51d9a560f280530c34c54a58cd0592ba/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L8702)):*
> ```JSON
>           "type": "object",
>           "properties": {
>             "serviceHooks": {
> ```

I'm confused about this change, should have been hooks not serviceHooks


<!-- Sent from Reviewable.io -->

2023-04-05 09:52 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 54 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 8702 at r7](https://reviewable.io/reviews/harness/harness-core/45664#-NSFVv4q5LjMMcPEx_ji:-NSFp4aw0CTD-vzkvI2S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0dad251f51d9a560f280530c34c54a58cd0592ba/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L8702)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm confused about this change, should have been hooks not serviceHooks
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-05 11:58 UTC, TarunUba1 commented
trigger ut2

2023-04-05 15:35 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java
> +      if (serviceSpec instanceof KubernetesServiceSpec) {
can we introduce a getHooks method into service definition ?

2023-04-05 19:03 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/mapper/ServiceHookOutcomeMapper.java
> +@OwnedBy(CDP)
Done

2023-04-05 19:04 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java
> +public class NgServiceHooksMetadataSweepingOutput implements ExecutionSweepingOutput {
Done

2023-04-05 19:04 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java
> +  String environmentIdentifier;
identifiers only

2023-04-05 19:04 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/ServiceHooksStepV2.java
> +      ServiceHookWrapper file = serviceHooks.get(i);
done

2023-04-05 19:04 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceConfigStepOutcome.java
> +  ServiceHooksOutcome serviceHookResults;
removed

2023-04-05 19:04 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceOutcomeHelper.java
> +        .serviceHookResults(getServiceHooksOutcome(ambiance, outcomeService))
removed

2023-04-05 19:04 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceSectionStepOutcome.java
> +  ServiceHooksOutcome serviceHookResults;
removed

2023-04-05 19:04 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java
> +public class ServiceHookUtility {
removed

2023-04-05 19:05 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java
> +            .stepType(ServiceHooksStepV2.STEP_TYPE)
Done

2023-04-05 19:05 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java
> +      if (serviceSpec instanceof KubernetesServiceSpec) {
Done

2023-04-06 04:02 UTC, TarunUba1 commented
trigger ut2

2023-04-06 07:16 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java
> +public class ServiceHookUtility {
Done

2023-04-06 07:30 UTC, TarunUba1 commented
trigger ut6

2023-04-06 07:38 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java` line 32 at r9](https://reviewable.io/reviews/harness/harness-core/45664#-NRX6sEfLhQ0tK28hI0B-r9-32:-NSKV-RCELlWnYZLi8ru:bemhpyu) ([raw file](https://github.com/harness/harness-core/blob/479ea0ba136b214ca406e7204ca0bf2334ca3562/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java#L32)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

identifiers only
</blockquote></details>

We have account/org level services/environments only, just FYI


<!-- Sent from Reviewable.io -->

2023-04-06 07:38 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 72 at r12](https://reviewable.io/reviews/harness/harness-core/45664#-NSKVBvy8mY-BaVnVQKK:-NSKVBvy8mY-BaVnVQKL:b-kr4rfz) ([raw file](https://github.com/harness/harness-core/blob/53b053e712dad393dd9080b4815fbed9a7169b74/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L72)):*
> ```Java
>   @Inject private ExecutionSweepingOutputService sweepingOutputService;
> 
>   private static final String INVALID_REQUEST_EXCEPTION = "No service configuration found in the service";
> ```

please change the name of this variable to be more meaningful 


<!-- Sent from Reviewable.io -->

2023-04-06 07:40 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 264 at r12](https://reviewable.io/reviews/harness/harness-core/45664#-NSKVKHS3z06zV3QdUnm:-NSKVKHS3z06zV3QdUnn:bjz1ro6) ([raw file](https://github.com/harness/harness-core/blob/53b053e712dad393dd9080b4815fbed9a7169b74/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L264)):*
> ```Java
>     Map<String, ServiceHookWrapper> finalServiceHooksMap = new HashMap<>();
>     finalServiceHooksMap.putAll(serviceHooks);
>     finalServiceHooks = new ArrayList<>(finalServiceHooksMap.values());
> ```

why do we need a finalServiceHooksmap variable here ? can we not just use the ```serviceHooks``` variable ?


<!-- Sent from Reviewable.io -->

2023-04-06 07:44 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java` line 149 at r12](https://reviewable.io/reviews/harness/harness-core/45664#-NSKWPDtE4i4BcHRkGkK:-NSKWPDu6mO3s23edlgD:b8jfb62) ([raw file](https://github.com/harness/harness-core/blob/53b053e712dad393dd9080b4815fbed9a7169b74/127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java#L149)):*
> ```Java
>   GOOGLE_CLOUD_FUNCTIONS_GEN_ONE_ROLLBACK(
>       "GOOGLE_CLOUD_FUNCTIONS_GEN_ONE_ROLLBACK", YamlTypes.GOOGLE_CLOUD_FUNCTIONS_GEN_ONE_ROLLBACK),
>   SERVICE_HOOKS_V2("SERVICE_HOOKS_V2", YamlTypes.SERVICE_HOOKS);
> ```

This should be just SERVICE_HOOKS right ? there is no v1 here


<!-- Sent from Reviewable.io -->

2023-04-06 07:45 UTC, yogesh-chauhan reviewed
> Reviewed 4 of 45 files at r1, 1 of 22 files at r2, 11 of 27 files at r3, 4 of 14 files at r4, 13 of 18 files at r6, 1 of 3 files at r7, 11 of 15 files at r8, 9 of 12 files at r10, 1 of 2 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 27 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-06 09:21 UTC, abosii-harness requested changes
> Reviewed 13 of 15 files at r8, 1 of 2 files at r9, 8 of 12 files at r10, 1 of 2 files at r11, 2 of 2 files at r12, 1 of 1 files at r14, 3 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinition.java` line 77 at r15](https://reviewable.io/reviews/harness/harness-core/45664#-NSKrPsU110sVf3ZnHVn:-NSKrPsU110sVf3ZnHVo:bgp3eft) ([raw file](https://github.com/harness/harness-core/blob/48e5a7d2e7f64b3f6888d43439355cdb238c2620/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinition.java#L77)):*
> ```Java
> 
>   @JsonIgnore
>   public List<ServiceHookWrapper> getServiceHooks() {
> ```

can be just a method that each implementation would override and have a default impl that will return emptyList()


<!-- Sent from Reviewable.io -->

2023-04-06 10:06 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 30 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 72 at r12](https://reviewable.io/reviews/harness/harness-core/45664#-NSKVBvy8mY-BaVnVQKK:-NSKnA7n726-7i1aowFe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53b053e712dad393dd9080b4815fbed9a7169b74/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L72)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

please change the name of this variable to be more meaningful 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 264 at r12](https://reviewable.io/reviews/harness/harness-core/45664#-NSKVKHS3z06zV3QdUnm:-NSKn9pe2unkRuuy2rTd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53b053e712dad393dd9080b4815fbed9a7169b74/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L264)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why do we need a finalServiceHooksmap variable here ? can we not just use the ```serviceHooks``` variable ?
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinition.java` line 77 at r15](https://reviewable.io/reviews/harness/harness-core/45664#-NSKrPsU110sVf3ZnHVn:-NSL0QChDXEwiaDakoyN:b7035tn) ([raw file](https://github.com/harness/harness-core/blob/48e5a7d2e7f64b3f6888d43439355cdb238c2620/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinition.java#L77)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can be just a method that each implementation would override and have a default impl that will return emptyList()
</blockquote></details>

Not required anymore, that function was only used in v1
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java` line 149 at r12](https://reviewable.io/reviews/harness/harness-core/45664#-NSKWPDtE4i4BcHRkGkK:-NSKnAlH6rkCklu2NMQY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53b053e712dad393dd9080b4815fbed9a7169b74/127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java#L149)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This should be just SERVICE_HOOKS right ? there is no v1 here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java` line 32 at r9](https://reviewable.io/reviews/harness/harness-core/45664#-NRX6sEfLhQ0tK28hI0B-r9-32:-NSL0W9F9ShV0wK0KPQm:bhsjuvf) ([raw file](https://github.com/harness/harness-core/blob/479ea0ba136b214ca406e7204ca0bf2334ca3562/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java#L32)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We have account/org level services/environments only, just FYI
</blockquote></details>

i ran service "servicebluegreen" and i got the same from ngServiceV2InfoConfig.getIdentifier(). I dont see any option to create service at account and project level currently. As per the refex pattern for NGServiceV2InfoConfig identifier it is
[a-zA-Z_][0-9a-zA-Z_]{0,127}$ so it cannot be account.service_id
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/45664#-NRXIvRi0_ieLncd3vFF:-NSKZLXE9QgMjtoSLU1D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/daf6ff66b8378ca3496339e77f82dca27afe24e7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/utilities/ServiceHookUtility.java#L103)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm not clear about this logic, @yogesh-chauhan any idea why we need it? I do believe we copied it from config files logic, but don't believe if we have any clarity that this logic is fine
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-06 10:10 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java` line 32 at r9](https://reviewable.io/reviews/harness/harness-core/45664#-NRX6sEfLhQ0tK28hI0B-r9-32:-NSL1M33321q0TOd979D:bgpmhyn) ([raw file](https://github.com/harness/harness-core/blob/479ea0ba136b214ca406e7204ca0bf2334ca3562/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/hooks/steps/NgServiceHooksMetadataSweepingOutput.java#L32)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

i ran service "servicebluegreen" and i got the same from ngServiceV2InfoConfig.getIdentifier(). I dont see any option to create service at account and project level currently. As per the refex pattern for NGServiceV2InfoConfig identifier it is
[a-zA-Z_][0-9a-zA-Z_]{0,127}$ so it cannot be account.service_id
</blockquote></details>

You can enable FF ```CDS_OrgAccountLevelServiceEnvEnvGroup``` for that


<!-- Sent from Reviewable.io -->

2023-04-06 10:29 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 48 files at r1, 1 of 28 files at r3, 1 of 15 files at r10, 3 of 4 files at r15, 23 of 23 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-06 12:35 UTC, yogesh-chauhan approved these changes
> Reviewed 4 of 4 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: 28 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-06 12:37 UTC, abosii-harness approved these changes
> Reviewed 22 of 23 files at r16, 4 of 4 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45664)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-06 12:38 UTC, merged