feat: [CDS-54458]: New endpoints for Instance sync V2 for NG
harness/harness-core pull request #45748
Opened 2023-03-28 10:55 UTC by namantalaycha10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-29 08:09 UTC, abosii-harness requested changes

2023-03-29 08:09 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/repositories/instancesyncperpetualtaskinfo/InstanceSyncPerpetualTaskInfoRepositoryCustom.java
> +  List<InstanceSyncPerpetualTaskInfo> findAllByPerpetualTaskId(Criteria criteria);
Why do we need criteria here if we know that we're going to find by pereptual task id?

2023-03-29 08:09 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java
> +          @Body DelegateResponseData delegateResponseData) {
What is body here?

2023-03-29 08:14 UTC, abosii-harness requested changes

2023-03-29 08:14 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +/*
So the logic will be something like:
1. for each InstanceSyncPerpetualTaskInfoDTO -> get infra mapping (some caching will be greate)
2. based on infra mapping type get the task handler 
3. call task handler to transform InstanceSyncPerpetualTaskInfoDTO to instance sync task details

2023-03-30 09:34 UTC, abosii-harness requested changes

2023-03-30 09:34 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +                                                .setClusterName("clusterName")
is optional, you shouldn't set it

2023-03-30 09:34 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +        throw new UnsupportedOperationException("Must be K8sDeploymentInfoDTO");
log and continue

2023-03-30 09:34 UTC, abosii-harness commented on 930-ng-core-clients/src/main/java/io/harness/instancesync/InstanceSyncResourceClient.java
> +  Call<ResponseDTO<Boolean>> sendPerpetualTaskV2Response(
Method name is not correct

2023-03-30 09:34 UTC, abosii-harness commented on 930-ng-core-clients/src/main/java/io/harness/instancesync/InstanceSyncResourceClient.java
> +  @GET(INSTANCE_SYNC + "/v3/task/{perpetualTaskId}/details")
This can be without /v3/

2023-03-30 09:34 UTC, abosii-harness commented on 930-ng-core-clients/src/main/java/io/harness/instancesync/InstanceSyncResourceClient.java
> +  Call<ResponseDTO<InstanceSyncTaskDetails>> getInstanceSyncTaskDetails(
Add @Produces(ProtocolBufferMediaType.APPLICATION_PROTOBUF)

2023-03-30 09:34 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/k8s_instance_sync_task_params_v2.proto
> +message InstanceSyncTaskDetails {
InstanceSyncTaskDetails and DeploymentReleaseDetails should be moved to a common proto file

2023-03-30 09:34 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +        return null;
continue instead

2023-03-30 09:34 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/repositories/instancesyncperpetualtaskinfo/InstanceSyncPerpetualTaskInfoRepositoryCustomImpl.java
> +  }
nit: add space after

2023-03-30 09:34 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java
> +  processInstanceSyncV2PerpetualTaskV2Response(
This method is not correct
I would suggest this method to added now, it's anyway not working as expected and will be required to completely changed in future

2023-03-30 09:34 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java
> +  @Path("/v3/task/{perpetualTaskId}/details")
this can be without /v3/

2023-03-30 09:34 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java
> +  @ApiOperation(value = "Get instance sync perpetual task details", nickname = "fetchTaskDetails")
Add @Produces(ProtocolBufferMediaType.APPLICATION_PROTOBUF)

2023-03-30 12:49 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45748)* status: 21 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/45748#-NRbqvYkJg4hzynt8_up-r3-90:-NRmRgs36-QWbXnei8MH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1bd3508f0b183388fc705ae83ef024d7618a21d/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java#L90)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Path is not good, we can use /v3/response
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/45748#-NRbqvYkJg4hzynt8_up-r3-108:-NRmRqg-AogP5MQzWJx0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1bd3508f0b183388fc705ae83ef024d7618a21d/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java#L108)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Path should be /task/{perpetualTaskId}/details instead of query params
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java` line 115 at r3](https://reviewable.io/reviews/harness/harness-core/45748#-NRbqvYkJg4hzynt8_up-r3-115:-NRmS8b0DBnw1COSUEW0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1bd3508f0b183388fc705ae83ef024d7618a21d/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java#L115)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What is body here?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/45748#-NRbqvYkJg4hzynt8_up-r5-94:-NRmZ7WpAPUM60_DN6ge:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7dfe179f9878d64de512a173282042008fdf2e85/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java#L94)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This method is not correct
I would suggest this method to added now, it's anyway not working as expected and will be required to completely changed in future
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java` line 108 at r5](https://reviewable.io/reviews/harness/harness-core/45748#-NRbqvYkJg4hzynt8_up-r5-108:-NRmRxWFAge1eDNW0vNT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7dfe179f9878d64de512a173282042008fdf2e85/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java#L108)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this can be without /v3/
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java` line 109 at r5](https://reviewable.io/reviews/harness/harness-core/45748#-NRbqvYkJg4hzynt8_up-r5-109:-NRmS8vtAAmJjce5mKhy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7dfe179f9878d64de512a173282042008fdf2e85/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/InstanceSyncResource.java#L109)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Add @Produces(ProtocolBufferMediaType.APPLICATION_PROTOBUF)
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/repositories/instancesyncperpetualtaskinfo/InstanceSyncPerpetualTaskInfoRepositoryCustom.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/45748#-NRgLjt-2jxAIei4gpuc-r3-25:-NRmSUwI6FIO1cUXkgkd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1bd3508f0b183388fc705ae83ef024d7618a21d/126-instance/src/main/java/io/harness/repositories/instancesyncperpetualtaskinfo/InstanceSyncPerpetualTaskInfoRepositoryCustom.java#L25)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why do we need criteria here if we know that we're going to find by pereptual task id?
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 0 at r3](https://reviewable.io/reviews/harness/harness-core/45748#gh-1151547871:-NRmScJ46tmdRmWTR5XV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1bd3508f0b183388fc705ae83ef024d7618a21d/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L0)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

What is going on with these changes?
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 354 at r3](https://reviewable.io/reviews/harness/harness-core/45748#-NRc-DGJrsZuiUB2XCBq-r3-354:-NRmSeWh3f-UDJHDSwzc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1bd3508f0b183388fc705ae83ef024d7618a21d/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L354)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

So the logic will be something like:
1. for each InstanceSyncPerpetualTaskInfoDTO -> get infra mapping (some caching will be greate)
2. based on infra mapping type get the task handler 
3. call task handler to transform InstanceSyncPerpetualTaskInfoDTO to instance sync task details
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 358 at r5](https://reviewable.io/reviews/harness/harness-core/45748#-NRc-DGJrsZuiUB2XCBq-r5-358:-NRmT03WAnJMpPRWXPwQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7dfe179f9878d64de512a173282042008fdf2e85/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L358)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

continue instead 
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java` line 92 at r5](https://reviewable.io/reviews/harness/harness-core/45748#-NRc-DGJrsZuiUB2XCBs-r5-92:-NRmZ8gw4rKcVI9-ESTp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7dfe179f9878d64de512a173282042008fdf2e85/126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java#L92)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

is optional, you shouldn't set it
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java` line 95 at r5](https://reviewable.io/reviews/harness/harness-core/45748#-NRc-DGJrsZuiUB2XCBs-r5-95:-NRmTS8JCvkcrkkaMGbB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7dfe179f9878d64de512a173282042008fdf2e85/126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java#L95)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

log and continue 
</blockquote></details>

Done.
___
*[`930-ng-core-clients/src/main/java/io [...]

2023-03-30 14:36 UTC, namantalaycha10 commented
trigger ti2

2023-03-31 06:55 UTC, closed without merging