feat: [CDS-56652]: BE: Support Config File Configuration from Github repository
harness/harness-core pull request #45741
Opened 2023-03-28 09:42 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-28 10:46 UTC, alluvamsi-harness commented
trigger ut2

2023-03-28 18:10 UTC, acasian-harness requested changes
@alluvamsi-harness please add UT for `ConfigFilesStepV3` & `ConfigFileFunctor`

> Reviewed 27 of 27 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NRdP8nP-W3_CWxN97BI:b-ixp3fo)* status: 28 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 91 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdM64J5fbypKkm68pr:-NRdM64J5fbypKkm68ps:b-xtnmb7) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L91)):*
> ```Java
>                                : getSecretFileContent(ambiance, methodName, secretFiles.get(0));
>     } else if (ManifestStoreType.isInGitSubset(storeConfig.getKind())) {
>       return configFileOutcome.getConfigFileStepOutput().get(0).getFileContent();
> ```

why the first one only? Also what would be the output here if the delegate task succedded but no files were fetched (path to empty dir for example)
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdNPgV3_6tijOeLnkX:-NRdNPgV3_6tijOeLnkY:b-qelr0y) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L155)):*
> ```Java
>     cdExpressionResolver.updateExpressions(ambiance, configFiles);
> 
>     checkForAccessOrThrow(ambiance, configFiles);
> ```

why are checking the access here during runtime execution?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 180 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdODpS2w5xFGe5y66D:-NRdODpS2w5xFGe5y66E:b-94psd7) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L180)):*
> ```Java
>     if (isNotEmpty(gitConfigFilesOutcome)) {
>       String taskId = createDelegateTask(ambiance, logCallback, gitConfigFilesOutcome);
>       // create delegate task
> ```

we can remove that comment
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 182 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdO9jIAdpio0TbKcUx:-NRdO9jIAdpio0TbKcUy:b-8wzu4) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L182)):*
> ```Java
>       // create delegate task
>       taskIds.add(taskId);
>       configFilesMapDelegateTasks.put(taskId, gitConfigFilesOutcome);
> ```

why do we need that mapping of delegate task and config outcome?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdOL64AJgZO8wzhS6L:-NRdOL64AJgZO8wzhS6M:b-u1aihm) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L205)):*
> ```Java
>             .gitRequestFileConfigs(gitRequestFileConfigs)
>             .shouldOpenLogStream(true)
>             .commandUnitName(GoogleFunctionsCommandUnitConstants.fetchManifests.toString())
> ```

what is the name of this command unit?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 211 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdNCtV7VLkGXm0k_KS:-NRdNCtV7VLkGXm0k_KT:b-qvkkd6) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L211)):*
> ```Java
>     final TaskData taskData = TaskData.builder()
>                                   .async(true)
>                                   .timeout(3)
> ```

why timeout is 3?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 220 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdOUJo21-WMyMJiQL3:-NRdOUJo21-WMyMJiQL4:b-mfh8k9) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L220)):*
> ```Java
>     TaskRequest taskRequest = TaskRequestsUtils.prepareTaskRequestWithTaskSelector(ambiance, taskData,
>         referenceFalseKryoSerializer, TaskCategory.DELEGATE_TASK_V2, Collections.emptyList(), false, taskName,
>         TaskSelectorYaml.toTaskSelector(Collections.emptyList()));
> ```

task selector can be picked from git connector
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 256 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdN8E4Ez_D6CnKm7yu:-NRdN8E4Ez_D6CnKm7yv:b-gko95j) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L256)):*
> ```Java
>   }
> 
>   enum ACTION { CREATE_DELEGATE_TASK, RUN_SYNC, SKIP }
> ```

aren't we overengineering this part?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 292 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdOgjx2fjcuvTSZfNA:-NRdOgjx2fjcuvTSZfNB:bwy80eo) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L292)):*
> ```Java
>         ambiance, RefObjectUtils.getSweepingOutputRefObject(CONFIG_FILES_STEP_V3));
> 
>     // If there were some artifacts that did not require a delegate task, we cannot skip here.
> ```

is this comment relevant?


<!-- Sent from Reviewable.io -->

2023-03-28 20:17 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 28 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 91 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdM64J5fbypKkm68pr:-NRdqQ324ceET3tbwMTD:b-k8gd16) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L91)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why the first one only? Also what would be the output here if the delegate task succedded but no files were fetched (path to empty dir for example)
</blockquote></details>

We are only allowing one file per store, so only first one is used. I added a validation step now, if its empty or if there are many files it will throw an error
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 180 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdODpS2w5xFGe5y66D:-NRdrCkkAVCde4jwsch6:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L180)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we can remove that comment
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdOL64AJgZO8wzhS6L:-NRdrEb6ApfKtwlUESKl:bm79cih) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L205)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

what is the name of this command unit?
</blockquote></details>

Changed the command unit
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 256 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdN8E4Ez_D6CnKm7yu:-NRdrP9x9c_mFiOKQQsf:bsb2v19) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L256)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

aren't we overengineering this part?
</blockquote></details>

removed this 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 292 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdOgjx2fjcuvTSZfNA:-NRdrR97E0lN7zfxWF_B:bc8boik) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L292)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

is this comment relevant?
</blockquote></details>

changed it


<!-- Sent from Reviewable.io -->

2023-03-29 13:17 UTC, ivan-83 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 6 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 240 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhVbSl7r94FZqI6RGZ:-NRhVbSl7r94FZqI6RG_:bz1t01j) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L240)):*
> ```Java
>   }
> 
>   public List<TaskSelector> getDelegateSelectors(ConnectorInfoDTO connectorInfoDTO) {
> ```

I guess this method already exists, pls move this method from this class or reuse it.



_Code quote:_
```Java
getDelegateSelectors
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 253 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhVQ17AmGfpCrhlU-J:-NRhVQ17AmGfpCrhlU-K:b-yk9hll) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L253)):*
> ```Java
>   }
> 
>   private void checkAndWarnIfDoesNotFollowIdentifierRegex(
> ```

We don't need method for the first itteration
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 272 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhVsrM5u-JAgByq4ea:-NRhVsrM5u-JAgByq4eb:b-g6owu8) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L272)):*
> ```Java
>   }
> 
>   private NgConfigFilesMetadataSweepingOutput fetchConfigFilesMetadataFromSweepingOutput(Ambiance ambiance) {
> ```

move to AbstractConfigFileStep and reuse from ConfigFilesStepV3 and ConfigFilesStepV2


<!-- Sent from Reviewable.io -->

2023-03-29 13:28 UTC, ivan-83 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 6 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 194 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhY28A2KxSi5M_LW7r:-NRhY28A2KxSi5M_LW7s:bj17yxz) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L194)):*
> ```Java
>   }
> 
>   private String createDelegateTask(
> ```

Before calling this method call 
List<GitRequestFileConfig> gitRequestFileConfigs = getGitFetchFilesConfigList(ambiance, configFileOutcomeList)
and supply List<GitRequestFileConfig> as a method param after that when we make it not depend on ConfigFileOutcome we can move to another class or AbstractConfigFileStep



_Code quote:_
```Java
List<GitRequestFileConfig> gitRequestFileConfigs = getGitFetchFilesConfigList(ambiance, configFileOutcomeList)
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 373 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhXCLKDgpYDMdA6oBE:-NRhXCLL4U5HhcaXrlsX:b-fcwmv5) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L373)):*
> ```Java
>   }
> 
>   private List<ConfigFileStepOutput> getConfigFilesStepOutputFromGitFiles(List<GitFile> gitFileList) {
> ```

Create mapper class for this and move logic there



_Code quote:_
```Java
getConfigFilesStepOutputFromGitFiles
```


<!-- Sent from Reviewable.io -->

2023-03-29 16:50 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 6 file(s) to review. 2 change requests. 18. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhCPdXARW2CqshltIT:-NRiGelPAQUWcvjcUCiu:b2w96wx) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L106)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This is already checked in io.harness.data.structure.EmptyPredicate#isEmpty method.
</blockquote></details>

removed isNotEmpty(configFileStepOutputList)


<!-- Sent from Reviewable.io -->

2023-03-29 17:03 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 6 file(s) to review. 2 change requests. 20. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 410 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhUJ113Ymv5B2kwve9:-NRiIRgP55C3SO3w0q7R:bv8rf6r) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L410)):*
> getGitFetchFilesConfigList
Now supplying identifier in method, there are few changes in method can't reuse the existing method
So copied and made changes as required


<!-- Sent from Reviewable.io -->

2023-03-29 17:03 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 6 file(s) to review. 2 change requests. 21. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 423 at r4](https://reviewable.io/reviews/harness/harness-core/45741#-NRhTcem1CHrDFpATZaW:-NRiJpCK3qoShM8uUIn6:bvck34c) ([raw file](https://github.com/harness/harness-core/blob/f60c7572d8e88a82579147b0706af49b2e69299a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L423)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move this method from this class,  supply configFileOutcome.getIdentifier() as method param, not copy try reuse.
</blockquote></details>

Now supplying identifier in method, there are few changes in method can't reuse the existing method
So copied and made changes as required


<!-- Sent from Reviewable.io -->

2023-03-29 17:23 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 6 file(s) to review. 2 change requests. 24. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 211 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdNCtV7VLkGXm0k_KS:-NRiOINd3Boj9aBBYOUs:b-5bw2xn) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L211)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Also, timeout should be constant
</blockquote></details>

Changed it to constant


<!-- Sent from Reviewable.io -->

2023-03-29 22:13 UTC, alluvamsi-harness commented
trigger smartchecks

2023-03-29 22:37 UTC, alluvamsi-harness commented
trigger buildnum

2023-03-30 07:34 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 13 file(s) to review. 2 change requests. 24. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 182 at r3](https://reviewable.io/reviews/harness/harness-core/45741#-NRdO9jIAdpio0TbKcUx:-NRlPM0C0RQL45Dn82eh:b-b0l0bk) ([raw file](https://github.com/harness/harness-core/blob/09770b0267bae9742623ffce4b23c50a48e11373/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L182)):*
> why do we need that mapping of delegate task and config outcome?
Need this mapping to handle the response of each delegate task, and the outcome is saved in step outcome to use it in functor


<!-- Sent from Reviewable.io -->

2023-03-30 10:04 UTC, ivan-83 requested changes
> Reviewed 5 of 9 files at r5, 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 13 file(s) to review. 2 change requests. 20. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 90 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlwkRr1QPxuPr1Kl_L:-NRlwkRr1QPxuPr1Kl_M:b-4r45gt) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L90)):*
> ```Java
>       validateConfigFileAttachedFilesAndEncryptedFiles(configFileIdentifier, files, secretFiles);
> 
>       return isNotEmpty(files) ? getFileContent(ambiance, methodName, files.get(0))
> ```

Pls rename getFileContent >> getFileStoreFileContent
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 101 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlwZxuAmJFcNtc868b:-NRlwZxuAmJFcNtc868c:bbbokvz) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L101)):*
> ```Java
>   }
> 
>   private String getFileContentByMethodName(final String methodName, String content) {
> ```

Pls, rename, getFileContentByMethodName >> getGitFileContent
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 103 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlv0zOBxGK2-ruNUQQ:-NRlv0zQ3uBpFmgrvryy:b-bw10t) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L103)):*
> ```Java
>   private String getFileContentByMethodName(final String methodName, String content) {
>     if (FUNCTOR_STRING_METHOD_NAME.equals(methodName)) {
>       return content;
> ```

We need to resolve expressions here,  cdExpressionResolver.renderExpression(ambiance, content). You can create/reuse the method in  CDStepHelper or inject cdExpressionResolver, it's up to you.
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 105 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlvYdY0ZqO2iKKTrUk:-NRlvYd_ChovntoQvAAv:bx6ttox) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L105)):*
> ```Java
>       return content;
>     } else if (FUNCTOR_BASE64_METHOD_NAME.equals(methodName)) {
>       return EncodingUtils.encodeBase64(content);
> ```

We need to resolve expressions here before encoding,   cdExpressionResolver.renderExpression(ambiance, content). You can create/reuse the method in  CDStepHelper or inject cdExpressionResolver, it's up to you.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1038 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlxJteASDes8HeElz0:-NRlxJteASDes8HeElz1:bsvsnyq) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1038)):*
> ```Java
>                                                    .collect(Collectors.toList()));
>       default:
>         throw new UnsupportedOperationException(format("Unknown Connector Config"));
> ```

Add more specific msg here like "Unknown Connector Config for Git delegate selectors"
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigFilesMapper.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRly6DJEDQPeZYS0IXL:-NRly6DJEDQPeZYS0IXM:b2i5gw2) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigFilesMapper.java#L20)):*
> ```Java
> 
> @OwnedBy(CDP)
> public class ConfigFilesMapper {
> ```

Pls, rename ConfigFilesMapper >> ConfigGitFilesMapper


<!-- Sent from Reviewable.io -->

2023-03-30 11:42 UTC, ivan-83 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 13 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 199 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRm8sGU7GgdhP3rHyxd:-NRm8sGU7GgdhP3rHyxe:b-fzdpc1) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L199)):*
> ```Java
>     GitRequestFileConfig gitRequestFileConfig = getGitFetchFilesConfigList(ambiance, configFileOutcome);
>     logCallback.saveExecutionLog(
>         LogHelper.color("Starting delegate task to fetch details of config files", LogColor.Cyan, LogWeight.Bold));
> ```

Pls, rename, because we are going to fetch and content not only details, and fetch one file for the time being, not files,

 Starting delegate task to fetch details of config files >> Starting delegate task to fetch config file
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 225 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmCDl4-BwTiAJG_XMI:-NRmCDl4-BwTiAJG_XMJ:b-12oflo) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L225)):*
> ```Java
> 
>     final DelegateTaskRequest delegateTaskRequest = cdStepHelper.mapTaskRequestToDelegateTaskRequest(taskRequest,
>         taskData, delegateSelectors.stream().map(TaskSelector::getSelector).collect(Collectors.toSet()), "", false);
> ```

what is this "" param referring to?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 230 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmD39X6u7MlNu3bCX9:-NRmD39X6u7MlNu3bCXA:bno5aeo) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L230)):*
> ```Java
>   }
> 
>   public List<TaskSelector> getDelegateSelectorsFromOutcome(ConfigFileOutcome configFileOutcome, Ambiance ambiance) {
> ```

Here method param should be GitStoreConfig gitStoreConfig instead of ConfigFileOutcome configFileOutcome

pls rename this getDelegateSelectorsFromOutcome >> getDelegateSelectorsFromGitConnector



_Code quote:_
```Java
 GitStoreConfig gitStoreConfig
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 233 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmCnqhEi6euwbPFpdi:-NRmCnqhEi6euwbPFpdj:b-f6x3sl) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L233)):*
> ```Java
>     GitStoreConfig gitStoreConfig = ((GitStoreConfig) configFileOutcome.getStore());
>     ConnectorInfoDTO connectorInfoDTO =
>         cdStepHelper.getConnector(gitStoreConfig.getConnectorRef().getValue(), ambiance);
> ```

Use here ParameterFieldHelper.getParameterFieldValue(gitStoreConfig.getConnectorRef()) to avoid NPE



_Code quote:_
```Java
gitStoreConfig.getConnectorRef().getValue()
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 268 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmHPzi3HVFdwqjdkjQ:-NRmHPzk4n9_fTWK6X4g:brt8nk5) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L268)):*
> ```Java
> 
>     final NGLogCallback logCallback = serviceStepsHelper.getServiceLogCallback(ambiance);
>     ConfigFilesOutcome stepOutcome = new ConfigFilesOutcome();
> ```

pls, rename stepOutcome to configFileOutcome



_Code quote:_
```Java
stepOutcome
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 275 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmHaZJ4NP6-7HoYqTg:-NRmHaZJ4NP6-7HoYqTh:b-qwbjm) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L275)):*
> ```Java
>       HashMap<String, List<ConfigGitFile>> configGitFileHashMap = getConfigIdAndOutputFromGitResponse(taskResponse);
>       String identifier = configFileOutcome.getIdentifier();
>       ConfigFileOutcome tempConfigFileOutcome = ConfigFileOutcome.builder()
> ```

Pls rename tempConfigFileOutcome >> gitConfigFileOutcome



_Code quote:_
```Java
tempConfigFileOutcome
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 276 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmHqIY1Fcvi743bZ0-:-NRmHqIY1Fcvi743bZ00:b-847qcn) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L276)):*
> ```Java
>       String identifier = configFileOutcome.getIdentifier();
>       ConfigFileOutcome tempConfigFileOutcome = ConfigFileOutcome.builder()
>                                                     .identifier(configFileOutcome.getIdentifier())
> ```

you already have an identifier one line above



_Code quote:_
```Java
configFileOutcome.getIdentifier()
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 280 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmI-PP5sxYuikKn2WH:-NRmI-PP5sxYuikKn2WI:b-ozgr1z) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L280)):*
> ```Java
>                                                     .gitFiles(configGitFileHashMap.get(identifier))
>                                                     .build();
>       stepOutcome.put(configFileOutcome.getIdentifier(), tempConfigFileOutcome);
> ```

you already have an identifier up



_Code quote:_
```Java
configFileOutcome.getIdentifier()
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 296 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIM4w1uwOe3r4t-Qr:-NRmIM4w1uwOe3r4t-Qs:b-c9tb7l) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L296)):*
> ```Java
>   }
> 
>   private HashMap<String, List<ConfigGitFile>> getConfigIdAndOutputFromGitResponse(
> ```

Pls rename getConfigIdAndOutputFromGitResponse >> getConfigIdentiferAndGitFilesFromGitResponse



_Code quote:_
```Java
getConfigIdAndOutputFromGitResponse
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 321 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRm8J7wAWwI8OMycUtn:-NRm8J7y9IZAs0PFv8Y7:b-bee9g5) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L321)):*
> ```Java
>   }
> 
>   private GitRequestFileConfig getGitFetch [...]

2023-03-30 14:22 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 13 file(s) to review. 2 change requests. 31. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 90 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlwkRr1QPxuPr1Kl_L:-NRmU6luAQkjOSSkJh4y:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L90)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls rename getFileContent >> getFileStoreFileContent
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 101 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlwZxuAmJFcNtc868b:-NRmUJQXCMaueRfl_nFa:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L101)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls, rename, getFileContentByMethodName >> getGitFileContent
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 103 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlv0zOBxGK2-ruNUQQ:-NRmUxvKEac2quXNUHeG:b-hr4xnt) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L103)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We need to resolve expressions here,  cdExpressionResolver.renderExpression(ambiance, content). You can create/reuse the method in  CDStepHelper or inject cdExpressionResolver, it's up to you.
</blockquote></details>

rendered expressions using cdExpressionResolver.renderExpression()
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 105 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlvYdY0ZqO2iKKTrUk:-NRmVQXd0XEmtmAlhASy:bbnimgz) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L105)):*
> rendered expressions using cdExpressionResolver.renderExpression()
rendered expressions using cdExpressionResolver.renderExpression()
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1038 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRlxJteASDes8HeElz0:-NRmViDZEbMFh3nFidF9:b39skgw) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1038)):*
> Unknown Connector Config for Git delegate selectors
Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigFilesMapper.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRly6DJEDQPeZYS0IXL:-NRmtN1KBJP6M5Wpz4qx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigFilesMapper.java#L20)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls, rename ConfigFilesMapper >> ConfigGitFilesMapper
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 199 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRm8sGU7GgdhP3rHyxd:-NRmWQ4R1pxPj25oM1bs:bt1r0hh) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L199)):*
> Starting delegate task to fetch details of config files
Chnaged it to Starting delegate task to fetch config file
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 225 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmCDl4-BwTiAJG_XMI:-NRmYYo_Cp12FUTDhfRa:b-v5dm7p) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L225)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

what is this "" param referring to?
</blockquote></details>

this param refers to baseLogKey, this can be used if we want to show logs of delegates in service step, can be passed as "" if we don't want to show the logs



_Code quote:_
```Java
mapTaskRequestToDelegateTaskRequest
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 230 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmD39X6u7MlNu3bCX9:-NRm_PWyDBRKRw6Gig1p:b-ti3789) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L230)):*
> getDelegateSelectorsFromGitConnector
Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 233 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmCnqhEi6euwbPFpdi:-NRmaWvBAq66LF28whrK:bgg88hm) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L233)):*
> ParameterFieldHelper.getParameterFieldValue
Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 268 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmHPzi3HVFdwqjdkjQ:-NRmsghE005-h1Hn473E:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L268)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

pls, rename stepOutcome to configFileOutcome
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 275 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmHaZJ4NP6-7HoYqTg:-NRmo5uK8qQWsZlWWOD3:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L275)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls rename tempConfigFileOutcome >> gitConfigFileOutcome
</blockquote></details>

Done



_Code quote:_
```Java
tempConfigFileOutcome 
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 276 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmHqIY1Fcvi743bZ0-:-NRmoEP37G5zTav69Ny4:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L276)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wr [...]

2023-03-30 14:27 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 13 file(s) to review. 2 change requests. 33. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java` line 33 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIh1E4dQgJ_bRFgHl:-NRmu_h86NcZpXbZIuq-:b-utcrss) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java#L33)):*
> harnessConfigFileOutcomes
Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java` line 34 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIu5E6lzEUQXKRaHS:-NRmuaED1OJocaXyscMx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java#L34)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

rename configFilesMapNonDelegateTasks >> harnessConfigFileOutcomes
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-31 11:07 UTC, alluvamsi-harness commented
trigger feature-build

2023-03-31 11:39 UTC, ivan-83 requested changes
> Reviewed 1 of 9 files at r5, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 13 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 296 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIM4w1uwOe3r4t-Qr:-NRrRtSU-GocWKj8KVi8:b-y8ggwl) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L296)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

> getConfigIdentiferAndGitFilesFromGitResponse
Done
</blockquote></details>

One more renaming and we are good, getConfigIdentifierAndGitFilesFromGitResponse >> getConfigIdentifierAndGitFilesFromGitTaskNGResponse



_Code quote:_
```Java
gitTaskNGResponse
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 321 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRm8J7wAWwI8OMycUtn:-NRrQc4325DzKt9Rupz1:b-k6nu8z) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L321)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

> getGitRequestFileConfig
Need this method as it is required in task request object 
renamed to getGitRequestFileConfig and createGitDelegateTask
</blockquote></details>

Sure, I mean use getGitRequestFetchFileConfig method directly in the task request object instead of getGitFetchFilesConfig because we are doing an unnecessary ManifestStoreType.isInGitSubset check two times. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 258 at r8](https://reviewable.io/reviews/harness/harness-core/45741#-NRrO3Qt4C9fDVgBUOQf:-NRrO3Qu2VVZxpLmA3H0:bm1fte1) ([raw file](https://github.com/harness/harness-core/blob/f84475859daff80b7983c4aaec694d37fa28e290/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L258)):*
> ```Java
>           configFilesStepV3SweepingOutput.getConfigFilesMapDelegateTasks().get(taskId);
>       GitTaskNGResponse taskResponse = (GitTaskNGResponse) responseDataMap.get(taskId);
>       HashMap<String, List<ConfigGitFile>> configGitFileHashMap =
> ```

Pls rename, configGitFileHashMap >> gitFilesByTaskIds or something similar just remove HashMap from the name



_Code quote:_
```Java
configGitFileHashMap
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 273 at r8](https://reviewable.io/reviews/harness/harness-core/45741#-NRrOxb7CfkBdtPQw4tA:-NRrOxb8COCg6c3ckVkW:b-9v5nyw) ([raw file](https://github.com/harness/harness-core/blob/f84475859daff80b7983c4aaec694d37fa28e290/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L273)):*
> ```Java
>         configFilesStepV3SweepingOutput.getConfigFilesMapNonDelegateTasks();
> 
>     for (ConfigFileOutcome configFileOutcome : harnessConfigFileOutcomes) {
> ```

Minor configFileOutcome >> harnessConfigFileOutcome



_Code quote:_
```Java
configFileOutcome
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java` line 33 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIh1E4dQgJ_bRFgHl:-NRrSBi10uvuosk8ioi8:b-wp5xk0) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java#L33)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

> harnessConfigFileOutcomes
Done
</blockquote></details>

I don't see that this is changed
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java` line 34 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIu5E6lzEUQXKRaHS:-NRrSFgZ4mJeFwpil8Vo:b-j8j4k6) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java#L34)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I don't see that this is changed


<!-- Sent from Reviewable.io -->

2023-03-31 11:44 UTC, acasian-harness submitted a review, later dismissed
> Reviewed 5 of 9 files at r5, 2 of 6 files at r6, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-31 12:50 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 296 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIM4w1uwOe3r4t-Qr:-NRrgzdU7Ajnc5TNSizZ:bg9hz0n) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L296)):*
> getConfigIdentifierAndGitFilesFromGitTaskNGResponse
Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 321 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRm8J7wAWwI8OMycUtn:-NRrh1Uq8aERhUuMoyiz:b-ms2stk) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L321)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Sure, I mean use getGitRequestFetchFileConfig method directly in the task request object instead of getGitFetchFilesConfig because we are doing an unnecessary ManifestStoreType.isInGitSubset check two times. 
</blockquote></details>

Done, used getGitRequestFetchFileConfig method directly now
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 258 at r8](https://reviewable.io/reviews/harness/harness-core/45741#-NRrO3Qt4C9fDVgBUOQf:-NRrgbq31GBognFJqxmP:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f84475859daff80b7983c4aaec694d37fa28e290/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L258)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls rename, configGitFileHashMap >> gitFilesByTaskIds or something similar just remove HashMap from the name
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java` line 273 at r8](https://reviewable.io/reviews/harness/harness-core/45741#-NRrOxb7CfkBdtPQw4tA:-NRrgdPf0k4JTuoWBCt0:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f84475859daff80b7983c4aaec694d37fa28e290/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3.java#L273)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor configFileOutcome >> harnessConfigFileOutcome
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java` line 33 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIh1E4dQgJ_bRFgHl:-NRrhB1-7mj8ZyhWHJfn:b-jflwij) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java#L33)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I don't see that this is changed
</blockquote></details>

Changed now
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java` line 34 at r7](https://reviewable.io/reviews/harness/harness-core/45741#-NRmIu5E6lzEUQXKRaHS:-NRrhD_u8NpPWKKnCdH9:b-jflwij) ([raw file](https://github.com/harness/harness-core/blob/81518bcee55ba9f603132e23eee06a59403cce64/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV3SweepingOutput.java#L34)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I don't see that this is changed
</blockquote></details>

Changed now


<!-- Sent from Reviewable.io -->

2023-03-31 13:22 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NRrpHCC0Nt7WX0B2X8E:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-02 20:40 UTC, ivan-83 requested changes
LGTM with minor comments

> Reviewed 4 of 7 files at r10, 9 of 9 files at r11, 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NS2gSCEAq0EY3rss5Uk:b-z5hs9a)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 98 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2_lyM44ugvXqbIQXc:-NS2_lyNCKeY2mM5Klv8:b-2ywxqe) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L98)):*
> ```Java
>                                                .setStepCategory(StepCategory.STEP)
>                                                .build();
>   static final String CONFIG_FILES_STEP_V2 = "CONFIG_FILES_STEP_V2";
> ```

We can make these properties private because it is not used outside this class.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 108 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2dm3J2cOarGYJ9HTd:-NS2dm3KCAjbxMz4UvQd:b-eaf3ox) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L108)):*
> ```Java
>   @Inject private DelegateGrpcClientWrapper delegateGrpcClientWrapper;
>   @Inject private ConfigGitFilesMapper configGitFilesMapper;
>   @Named(DEFAULT_CONNECTOR_SERVICE) @Inject private ConnectorService connectorService;
> ```

Do we need here connectorService?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 258 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2bBwhBUDR4InCJ6pg:-NS2bBwhBUDR4InCJ6ph:bz8pkk4) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L258)):*
> ```Java
>       GitTaskNGResponse taskResponse = (GitTaskNGResponse) responseDataMap.get(taskId);
>       HashMap<String, List<ConfigGitFile>> gitFilesByTaskIds =
>           getConfigIdentifierAndGitFilesFromGitTaskNGResponse(taskResponse);
> ```

Minor - getConfigIdentifierAndGitFilesFromGitTaskNGResponse can only return a list of ConfigGitFiles not map, task id we are already getting in for loop. Based on it method could be renamed to getGitFilesFromGitTaskNGResponse



_Code quote:_
```Java
getConfigIdentifierAndGitFilesFromGitTaskNGResponse
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 309 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2dcby1KxwAdIrbvVQ:-NS2dcby1KxwAdIrbvVR:b-s7i0xf) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L309)):*
> ```Java
>     if (ManifestStoreType.isInGitSubset(storeConfig.getKind())) {
>       GitStoreConfig gitStoreConfig = (GitStoreConfig) storeConfig;
>       String connectorId = gitStoreConfig.getConnectorRef().getValue();
> ```

Use here io.harness.common.ParameterFieldHelper#getParameterFieldValue to avoid NPE

The connector is needed in getGitStoreDelegateConfig there is no reason to get here and propagate through methods. All logic of getting connectorId and connectorDTO should be done in getGitStoreDelegateConfig.



_Code quote:_
```Java
gitStoreConfig.getConnectorRef()
```


<!-- Sent from Reviewable.io -->

2023-04-02 22:01 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 98 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2_lyM44ugvXqbIQXc:-NS2mRDK0CZtkvKWuPZ1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L98)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We can make these properties private because it is not used outside this class.
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 108 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2dm3J2cOarGYJ9HTd:-NS2mXyaA9DwLBqugByz:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L108)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we need here connectorService?
</blockquote></details>

removed
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 258 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2bBwhBUDR4InCJ6pg:-NS2mZgW1SKbnhKCEO4Y:b-h0ba9j) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L258)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - getConfigIdentifierAndGitFilesFromGitTaskNGResponse can only return a list of ConfigGitFiles not map, task id we are already getting in for loop. Based on it method could be renamed to getGitFilesFromGitTaskNGResponse
</blockquote></details>

changed to return a list of ConfigGitFiles
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 309 at r11](https://reviewable.io/reviews/harness/harness-core/45741#-NS2dcby1KxwAdIrbvVQ:-NS2mddgDCgf9MtPZnks:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e8e48084c97703ebdf9a968cf18ce523c53805bd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L309)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Use here io.harness.common.ParameterFieldHelper#getParameterFieldValue to avoid NPE

The connector is needed in getGitStoreDelegateConfig there is no reason to get here and propagate through methods. All logic of getting connectorId and connectorDTO should be done in getGitStoreDelegateConfig.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-02 22:23 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NS33Ig8-dPDTBJoBwh1:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-03 05:28 UTC, alluvamsi-harness commented
trigger ut4

2023-04-03 07:22 UTC, yogesh-chauhan requested changes

2023-04-03 07:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigGitFilesMapper.java
> +    for (GitFile gitFile : gitFileList) {
does this take care of gitFileList being empty ?

nit: You can use java streams to acheive this in a cleaner way

EmptyIfNull(gitfileList).stream(ConfigGitFile.builder().filePath(GitFile::getFilePath()).fileContent(GitFile::getFileContent()).build()).collect(Collectors.toList())

2023-04-03 07:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +  @Inject EntityDetailProtoToRestMapper entityDetailProtoToRestMapper;
does this need to be private ?

2023-04-03 07:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +  void checkForAccessOrThrow(Ambiance ambiance, List<ConfigFileWrapper> configFiles) {
can this be protected instead of package-private ?

2023-04-03 07:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +  public NgConfigFilesMetadataSweepingOutput fetchConfigFilesMetadataFromSweepingOutput(Ambiance ambiance) {
this should be a protected instead of public

2023-04-03 07:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +  public NgConfigFilesMetadataSweepingOutput fetchConfigFilesMetadataFromSweepingOutput(Ambiance ambiance) {
can we put a @NotNull annotation to declare that this does not return null

2023-04-03 07:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +                                                   .getDelegateSelectors()
does this assume that getDelegateSelectors will not return null ?

2023-04-03 07:22 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/configfile/ConfigFileOutcome.java
> +  List<ConfigGitFile> gitFiles;
what will be the expression for a user to access content of a git file ?

2023-04-03 07:22 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java
> +      throw new InvalidRequestException(
we should print the store kind here

2023-04-03 07:22 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java
> +      return getGitFileContent(ambiance, methodName, configFileOutcome.getGitFiles().get(0).getFileContent());
does this mean we will only have 1 git file in the config file outcome ? 
If yes, why do we need a list ?

2023-04-03 07:28 UTC, yogesh-chauhan requested changes

2023-04-03 07:30 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +public class ConfigFilesStepV2 extends AbstractConfigFileStep implements AsyncExecutableWithRbac<EmptyStepParameters> {
You can keep the older method as is

2023-04-03 07:35 UTC, yogesh-chauhan requested changes

2023-04-03 07:35 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +        StepCategory.STAGE.name());
If you just want to use this sweeping output in the step, the step category should be step ?

2023-04-03 07:35 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +    String taskName = TaskType.GIT_TASK_NG.getDisplayName();
do we need to create this local variable ?

2023-04-03 07:35 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +      throw new ArtifactServerException("Failed to fetch config files. " + failedResponses.get(0).getErrorMessage());
why is this an Artifact Server Exception ?
Also can we make hint and explanation available here ?

2023-04-05 06:00 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 17 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 96 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI--r13-96:-NS5GcPP1kmTepn4CELP:b1ap3nn) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L96)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this mean we will only have 1 git file in the config file outcome ? 
If yes, why do we need a list ?
</blockquote></details>

There is a enhancement for this to support folder also were user will specify only folder. All files from that folder will be fetched and can be used by the expression <+configFiles.getAsString(“configFIle_ID:filePath”)>
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 98 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI--r13-98:-NS5L7al8EdelfUl7u4L:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L98)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should print the store kind here 
</blockquote></details>

Done



_Code quote:_
```Java
Invalid store kind 
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1028 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI2-r13-1028:-NSEtEYP1zslN-yYnF1U:b38k157) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1028)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this assume that getDelegateSelectors will not return null ?
</blockquote></details>

Added this emptyIfNull() 



_Code quote:_
```Java
toTaskSelector
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1028 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NSElvt_15igno4rfwmS:-NSElvt_15igno4rfwmT:b-lzxdhy) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1028)):*
> getDelegateSelectors
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 67 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRiP_tI6KlyzivBUMIC-r13-67:-NS5SkGH1X8kIX_LmRa_:b5ooebv) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L67)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this need to be private ?
</blockquote></details>

made the object private. Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 96 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRiP_tI6KlyzivBUMIC-r13-96:-NS5SwaSAK4DmUIVugsv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L96)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can this be protected instead of package-private ?
</blockquote></details>

Done



_Code quote:_
```Java
checkForAccessOrThrow
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 199 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRiP_tI6KlyzivBUMIC-r13-199:-NS5Ucaj-x36W41oslnL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L199)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we put a @NotNull annotation to declare that this does not return null
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 91 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI5-r13-91:-NSEsCflCTd-rT4tBV1Q:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L91)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

You can keep the older method as is
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 170 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI5-r13-170:-NS5V6yE0AC6bP5Szs4z:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L170)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

If you just want to use this sweeping output in the step, the step category should be step ?
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 196 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI5-r13-196:-NS5VMj6-sVBULU6wlHX:bpzq846) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L196)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to create this local variable ?
</blockquote></details>

removed local variable



_Code quote:_
```Java
String taskName = TaskType.GIT_TASK_NG.getDisplayName();
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 208 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI5-r13-208:-NS5VT6P5ocQHRXMsBQK:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L208)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can this be private ?
</blockquote></details>

Done



_Code quote:_
```Java
getDelegateSelectorsFromGitConnector
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 237 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI5-r13-237:-NS5WFCk33JGYj2vVLvR:b-ffw49p) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L237)):*
<details><summar [...]

2023-04-05 09:24 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 20 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/configfile/ConfigFileOutcome.java` line 36 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW8-4O_FK0ohHrQ-r13-36:-NSFhmyLDXDpFZY4QDyp:bjolboa) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/127-cd-nextgen-entities/src/main/java/io/harness/cdng/configfile/ConfigFileOutcome.java#L36)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what will be the expression for a user to access content of a git file ?
</blockquote></details>

This is the expected case of config file
<configFile.getAsString(configFileID)>


<!-- Sent from Reviewable.io -->

2023-04-05 09:25 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 20 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 170 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI5-r13-170:-NSFioYvC8LkaIP1k7MD:b-611mon) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L170)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I tested with step, It was failing not sure why, so changed it back to Stage, Ignore "Done" comment


<!-- Sent from Reviewable.io -->

2023-04-05 18:12 UTC, ivan-83 approved these changes
> Reviewed 8 of 15 files at r15, 10 of 10 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 20 file(s) to review. 1 change requests. 13. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java` line 98 at r13](https://reviewable.io/reviews/harness/harness-core/45741#-NRbaLW70NIECCB5GlI--r13-98:-NSHbKFfDp6obQ0vaZGk:bwpjir3) ([raw file](https://github.com/harness/harness-core/blob/a28f4516b86c06ec4482fe07d9d79a1ec2bd168c/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConfigFileFunctor.java#L98)):*
<details><summary><i>Previously, alluvamsi-harness (Allu Vamsi Vishal) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Add the store kind to the error msg


<!-- Sent from Reviewable.io -->

2023-04-06 10:48 UTC, yogesh-chauhan approved these changes
> Reviewed 7 of 29 files at r1, 2 of 7 files at r10, 2 of 8 files at r12, 8 of 15 files at r15, 9 of 10 files at r16, 7 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 7 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-04-06 22:08 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NSNaZwv9ENjHakGDogL:bnfp4nl)* status: :shipit: complete! ✓

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 709 at r17](https://reviewable.io/reviews/harness/harness-core/45741#-NSNb7Su4Xre3S99CUtW:-NSNb7Su4Xre3S99CUtX:b9orybg) ([raw file](https://github.com/harness/harness-core/blob/ec3731a0ee5f0fb56469293a3e34b00dab82770a/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L709)):*
> ```Java
>       "Enable Harness variable rendering in Hanress config files (SSH/WinRM)", HarnessTeam.CDP),
>   CDS_TERRAFORM_S3_NG("Enables storing Terraform config, backend and var files in S3", HarnessTeam.CDP),
>   CDS_HTTP_STEP_NG_CERTIFICATE("Allow enforce SSL/TLS certificate in NG HTTP step", HarnessTeam.CDC);
> ```

Have we added CDS_GIT_CONFIG_FILES new FF here?


<!-- Sent from Reviewable.io -->

2023-04-07 09:07 UTC, yogesh-chauhan submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-07 13:18 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 11 files at r18, 3 of 3 files at r19, 6 of 6 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NSQr_KT9be3_CeHlYDY:bnfp4nl)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-07 13:36 UTC, acasian-harness submitted a review, later dismissed

2023-04-07 16:58 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 3 of 11 files at r18, 5 of 6 files at r20, 1 of 5 files at r21, 5 of 6 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-07 18:29 UTC, ivan-83 commented
trigger ut8

2023-04-07 20:58 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r21, 5 of 6 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NSSVsfZCnLJKw_912A3:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-07 21:04 UTC, ivan-83 commented
trigger review

2023-04-10 05:30 UTC, RishabhGupta34 commented
trigger reviewcheck

2023-04-10 05:33 UTC, RishabhGupta34 commented
trigger review

2023-04-10 05:36 UTC, RishabhGupta34 approved these changes

2023-04-10 05:36 UTC, RishabhGupta34 commented
trigger review

2023-04-10 05:50 UTC, RishabhGupta34 approved these changes
> Reviewed 6 of 29 files at r1, 1 of 7 files at r10, 2 of 8 files at r12, 6 of 15 files at r15, 5 of 10 files at r16, 3 of 11 files at r18, 5 of 6 files at r20, 1 of 5 files at r21, 5 of 6 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-10 05:51 UTC, RishabhGupta34 commented
trigger review

2023-04-10 06:04 UTC, AnshuH approved these changes

2023-04-10 06:06 UTC, AnshuH submitted a review, later dismissed

2023-04-10 06:43 UTC, acasian-harness approved these changes

2023-04-10 07:03 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NSdyYXT51gy84z0qZZk:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-10 08:54 UTC, RishabhGupta34 approved these changes

2023-04-10 09:13 UTC, RishabhGupta34 commented
trigger codebasehashcheck

2023-04-10 09:14 UTC, RishabhGupta34 commented
trigger codebasehash

2023-04-10 09:55 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741#-:-NSeRf0t9I6eq9FkaQDS:bnfp4nl)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-04-10 10:15 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45741)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-10 10:15 UTC, merged