feat: [PL-32205]: Support sorting on variables listing.
harness/harness-core pull request #45838
Opened 2023-03-29 13:10 UTC by boopesh007

## Describe your changes
 Support sorting on variables listing.
 
 Tested
By giving Sort order LastModified DSC
By giving the Sort order name ASC
By not giving any sort order and obeying LastModified DSC by default
 
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/45838)

2023-03-29 18:48 UTC, boopesh007 commented
trigger messagecheck

2023-03-29 19:27 UTC, boopesh007 commented
trigger messagecheck

2023-03-30 11:59 UTC, nishantsaini20 requested changes

2023-03-30 11:59 UTC, nishantsaini20 commented on 120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java
> +      SortOrder order = SortOrder.Builder.aSortOrder().withField("lastModifiedAt", SortOrder.OrderType.DESC).build();
The default changed from `createdAt` to `lastModifiedAt`. Is this a conscious decision?
Also use `VariableKeys.lastModifiedAt` instead of hardcoding the field name.

2023-03-30 11:59 UTC, nishantsaini20 commented on 120-ng-manager/modules/ng-variables/contracts/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java
> +      @BeanParam PageRequest pageRequest);
Is pagination tested for this change?

2023-03-30 12:14 UTC, boopesh007 commented
*[`120-ng-manager/modules/ng-variables/contracts/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java` line 133 at r2](https://reviewable.io/reviews/harness/harness-core/45838#-NRhUSnYXLxfYwzdou4U-r2-133:-NRmRE5G3N-AQiKbIr2k:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/1d938ba2b0115ba2d36043ed6aceac462852d44f/120-ng-manager/modules/ng-variables/contracts/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java#L133)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is pagination tested for this change?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2023-03-30 12:14 UTC, boopesh007 commented
*[`120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/45838#-NRhUSnYXLxfYwzdou4V-r2-79:-NRmRI0S62cFbWvMYqVK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d938ba2b0115ba2d36043ed6aceac462852d44f/120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java#L79)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

The default changed from `createdAt` to `lastModifiedAt`. Is this a conscious decision?
Also use `VariableKeys.lastModifiedAt` instead of hardcoding the field name.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-30 13:24 UTC, nishantsaini20 commented on 120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java
> +      SortOrder order = SortOrder.Builder.aSortOrder().withField("lastModifiedAt", SortOrder.OrderType.DESC).build();
Also sort index should be added for `lastModifiedAt` field.

2023-03-30 18:28 UTC, boopesh007 commented on 120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java
> +      SortOrder order = SortOrder.Builder.aSortOrder().withField("lastModifiedAt", SortOrder.OrderType.DESC).build();
Yes, it's a conscious decision. We are imposing uniformity across the platform

2023-03-31 08:07 UTC, boopesh007 commented
*[`120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/45838#-NRhUSnYXLxfYwzdou4V-r2-79:-NRqh5Z3AXUKRs8ApKzN:b37kthj) ([raw file](https://github.com/harness/harness-core/blob/1d938ba2b0115ba2d36043ed6aceac462852d44f/120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/resources/VariableResourceImpl.java#L79)):*
<details><summary><i>Previously, boopesh007 (Boopesh Shanmugam) wrote…</i></summary><blockquote>

Yes, it's a conscious decision. We are imposing uniformity across the platform 
</blockquote></details>

Added the sorting index for lastModifiedAt


<!-- Sent from Reviewable.io -->

2023-03-31 08:15 UTC, nishantsaini20 submitted a review, later dismissed

2023-03-31 08:23 UTC, mankrit-singh approved these changes
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45838)* status: 7 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-31 08:49 UTC, mankrit-singh approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45838)* status: 8 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-03-31 08:50 UTC, rathodmeetsatish approved these changes
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45838)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-03-31 08:59 UTC, nishantsaini20 approved these changes

2023-03-31 09:05 UTC, merged