feat: [CDS-53513]: last published changes
harness/harness-core pull request #45880
Opened 2023-03-30 07:53 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-03-30 11:33 UTC, puthrayaharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandler.java
> +      Pattern pattern = Pattern.compile(attributesRequest.getBuildNumber());
Why are we doing this?

2023-03-31 06:22 UTC, shivamnegi94 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/custom/CustomArtifactService.java
> +        .sorted(new BuildDetailsComparatorDescending())
To get the latest build on top

2023-03-31 06:24 UTC, shivamnegi94 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandler.java
> +      Pattern pattern = Pattern.compile(attributesRequest.getBuildNumber());
In Bamboo we don't have option for build regex and we can pass regex as build number only.
Delegate side we are checking that if the build number is regex or not

2023-03-31 06:25 UTC, shivamnegi94 commented
trigger ut0, ut1, ut2, ut3, ut4

2023-04-03 12:11 UTC, puthrayaharness requested changes

2023-04-04 07:32 UTC, puthrayaharness approved these changes

2023-04-04 07:35 UTC, vtxorxwitty approved these changes
> Reviewed 2 of 7 files at r1, 3 of 14 files at r2, 11 of 18 files at r3, 7 of 8 files at r4, 1 of 1 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45880)* status: 28 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-04 07:36 UTC, merged