[feat]: [CDS-58214]: added UpdateEnvironmentRefValueInServiceOverrideNGMigration
harness/harness-core pull request #46004
Opened 2023-04-03 11:02 UTC by tchaurasiya

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-05 09:43 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java
> +public class UpdateEnvironmentRefValueInServiceOverrideNGMigration implements NGMigration {
Just to confirm, this migration is idempotent right ? It can run multiple times and not overwrite already migrated entities ?

2023-04-05 10:01 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java
> +  private static String getUpdatedYamlIfEnvRefIsNotQualifiedRef(String accountId,
I think because we are updating the yaml in the update flow, it can cause issues with state management when using TF provider
Can we try on local once with TF provider ?
Like create and then update using TF provider

2023-04-06 05:54 UTC, tchaurasiya commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/46004#-NS5m4cIAio0cAjlyluR-r4-43:-NSK72_s9YI0IRYJ_G_1:b-aawmj) ([raw file](https://github.com/harness/harness-core/blob/aa00345d685696409393c2cc919f83d72db90cc2/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L43)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Just to confirm, this migration is idempotent right ? It can run multiple times and not overwrite already migrated entities ?
</blockquote></details>

Done. Yes.
Update only happens when environmentRefSplit[].length == 1 and overrideScope!=project


<!-- Sent from Reviewable.io -->

2023-04-06 05:54 UTC, tchaurasiya commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 313 at r4](https://reviewable.io/reviews/harness/harness-core/46004#-NSCWaILsBhdCjxfBIoa-r4-313:-NSK7Sc_1OWKwETZQuH4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa00345d685696409393c2cc919f83d72db90cc2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L313)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can these 2 be final ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-06 11:29 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java` line 279 at r6](https://reviewable.io/reviews/harness/harness-core/46004#-NSLJt9l6PESHv0LKGol:-NSLJt9l6PESHv0LKGom:b-nig1qw) ([raw file](https://github.com/harness/harness-core/blob/87f0b3443b85fb2287eb1dbea806aafb6daf5cbd/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java#L279)):*
> ```Java
>       outputProperties.addAll(handleManifestProperties(specField, ngServiceConfig));
>       outputProperties.addAll(handleArtifactProperties(specField, ngServiceConfig));
>       if (environmentRef != null && !environmentRef.isExpression()) {
> ```

nit: we can just add 1 more and condition here optionalService.isPresent()


<!-- Sent from Reviewable.io -->

2023-04-06 11:34 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/46004#-NSCWaILsBhdCjxfBIoc-r4-62:-NSLL8GKAtb7iPTfJH4z:b-fom777) ([raw file](https://github.com/harness/harness-core/blob/aa00345d685696409393c2cc919f83d72db90cc2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java#L62)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think because we are updating the yaml in the update flow, it can cause issues with state management when using TF provider
Can we try on local once with TF provider ?
Like create and then update using TF provider
</blockquote></details>

Lets verify in PRE QA as discussed


<!-- Sent from Reviewable.io -->

2023-04-07 03:08 UTC, tchaurasiya commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentUpdatedEvent.java` line 148 at r4](https://reviewable.io/reviews/harness/harness-core/46004#-NSCWaILsBhdCjxfBIob-r4-148:-NSOfoZR1WsP9AzSAgWT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa00345d685696409393c2cc919f83d72db90cc2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentUpdatedEvent.java#L148)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

don't we have a utility for this logic already ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-07 03:08 UTC, tchaurasiya commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/46004#-NSCWaILsBhdCjxfBIoc-r4-62:-NSLAykt8C8Dni6k_rUi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa00345d685696409393c2cc919f83d72db90cc2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/mapper/ServiceOverridesMapper.java#L62)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think because we are updating the yaml in the update flow, it can cause issues with state management when using TF provider
Can we try on local once with TF provider ?
Like create and then update using TF provider
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-07 03:40 UTC, tchaurasiya reviewed
> Reviewed 1 of 7 files at r2, 1 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-07 09:09 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 5 of 8 files at r5, 2 of 3 files at r6, 2 of 3 files at r7, 1 of 2 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 50 at r6](https://reviewable.io/reviews/harness/harness-core/46004#-NSLJVSE9OpstR2aXzrY:-NSLJVSE9OpstR2aXzrZ:b6pmdxo) ([raw file](https://github.com/harness/harness-core/blob/87f0b3443b85fb2287eb1dbea806aafb6daf5cbd/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L50)):*
> ```Java
>   @Inject private AccountClient accountClient;
>   private static final String DEBUG_LOG = "[UpdateEnvironmentRefValueInServiceOverrideNGMigration]: ";
>   private static final String SERVICE_OVERRIDES_NODE = "serviceOverrides";
> ```

nit: empty line here for readability


<!-- Sent from Reviewable.io -->

2023-04-19 04:52 UTC, yogesh-chauhan approved these changes

2023-04-19 06:35 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 56 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNBPIeCYgiduB--P28:-NTNBPIeCYgiduB--P29:b2000vj) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L56)):*
> ```Java
>     try {
>       log.info(DEBUG_LOG + "Starting migration of updating environmentRef value in serviceOverridesNG");
>       List<AccountDTO> allAccounts = CGRestUtils.getResponse(accountClient.getAllAccounts());
> ```

This will load all the accounts in memory - both CG & NG. 

So, better approach would be

1. run iterators on account
2. make mongo query and filter for NG accounts only.  Since data seems to be less than 1MB, this should be fine for now.


100 accounts NG

1 record - 1000 char - 1000B  - 1KB per account

100KB<1mB
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 103 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNCkE_8KpaK8aXc49U:-NTNCkE_8KpaK8aXc49V:b-wg7bq2) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L103)):*
> ```Java
>                   }
> 
>                   if (isBlank(updatedYaml)) {
> ```

in case of unexpected yaml, fail the migratoin for this account. Instead of updating any incorrect/blank value.


<!-- Sent from Reviewable.io -->

2023-04-19 06:42 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 149 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNDtxNBk-lWkfa4zQJ:-NTNDtxNBk-lWkfa4zQK:bmyv33x) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L149)):*
> ```Java
>   private Criteria getServiceOverrideEqualityCriteria(NGServiceOverridesEntity requestServiceOverride) {
>     String[] environmentRefSplit =
>         StringUtils.split(requestServiceOverride.getEnvironmentRef(), ".", MAX_RESULT_THRESHOLD_FOR_SPLIT);
> ```

We previously fetched the override entity. Now can't we use its uuid to find it? It would be a lot simpler than the below query and also fully accurate.


<!-- Sent from Reviewable.io -->

2023-04-19 06:43 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 84 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNF4zU9RhSvMIssE7o:-NTNF4zU9RhSvMIssE7p:b-bodqqi) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L84)):*
> ```Java
> 
>                   String originalYaml = serviceOverride.getYaml();
>                   String updatedYaml = originalYaml;
> ```

try to write module code, so it's easier to understand and debug in future.


<!-- Sent from Reviewable.io -->

2023-04-19 08:52 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 329 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNfbzt8nVVkpLkP7U1:-NTNfbzt8nVVkpLkP7U2:b-9n6u5j) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L329)):*
> ```Java
>       environmentIdentifier = envIdentifierRef.getIdentifier();
>     }
>     baseCriteria.andOperator(
> ```

Add comments in the code to explain this. Will not be obvious in future.
"DB can have either ref or Id, so we need to check for both"
"Cleanup in future after successful migration"


<!-- Sent from Reviewable.io -->

2023-04-20 13:51 UTC, tchaurasiya commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 56 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNBPIeCYgiduB--P28:-NTTvnpv7ZO0myfl29C9:b-lzmo6h) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L56)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

This will load all the accounts in memory - both CG & NG. 

So, better approach would be

1. run iterators on account
2. make mongo query and filter for NG accounts only.  Since data seems to be less than 1MB, this should be fine for now.


100 accounts NG

1 record - 1000 char - 1000B  - 1KB per account

100KB<1mB
</blockquote></details>

Done. As discussed, its one time so keeping it same


<!-- Sent from Reviewable.io -->

2023-04-20 15:07 UTC, tchaurasiya commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 84 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNF4zU9RhSvMIssE7o:-NTUCGfTCPDTUvuyIKWF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L84)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

try to write module code, so it's easier to understand and debug in future.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-20 15:08 UTC, tchaurasiya commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 149 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNDtxNBk-lWkfa4zQJ:-NTUC61C7P_pZIZCdldq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L149)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

We previously fetched the override entity. Now can't we use its uuid to find it? It would be a lot simpler than the below query and also fully accurate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-20 15:08 UTC, tchaurasiya commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java` line 103 at r11](https://reviewable.io/reviews/harness/harness-core/46004#-NTNCkE_8KpaK8aXc49U:-NTUCIm9AZJcxC9aomjJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/463fc3c9da98b9799a0d8efa7e138f4211e268a1/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UpdateEnvironmentRefValueInServiceOverrideNGMigration.java#L103)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

in case of unexpected yaml, fail the migratoin for this account. Instead of updating any incorrect/blank value.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-20 19:03 UTC, yogesh-chauhan approved these changes
> Reviewed 4 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-20 19:03 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004)* status: 12 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-21 05:03 UTC, vaibhav-si approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 8 files at r5, 2 of 3 files at r7, 1 of 2 files at r8, 3 of 3 files at r9, 4 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46004#-:-NTXBSPiChB53bkwczpf:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-21 05:15 UTC, tchaurasiya commented
trigger review

2023-04-21 05:18 UTC, merged