[feat]: [PIE-9379]: Implemented Enforce GitX settings for Pipeline/InputSets
harness/harness-core pull request #46021
Opened 2023-04-03 16:25 UTC by senjucanon2

## Describe your changes:

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-05 08:39 UTC, shalini-agr requested changes
> Reviewed 3 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFXvcyALuhpFkGF6IH:-NSFXvcyALuhpFkGF6II:b-1jw0n7) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L183)):*
> ```Java
>   }
> 
>   private boolean isGitExperienceEnforcedInSettings(String accountId, String orgIdentifier, String projIdentifier) {
> ```

let's use accountIdentifier here instead of accountId, for uniformity.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFY5E_1OD6xvMi6mgp:-NSFY5E_1OD6xvMi6mgq:b9y77hr) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L19)):*
> ```Java
> 
> import com.google.inject.Inject;
> ```

add @OwnedBy annotation
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYVVt6h1WEMuo-aWe:-NSFYVVuEHmliZp-g846:bephnxg) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L20)):*
> ```Java
> import com.google.inject.Inject;
> 
> public class GitExperienceSettingsHandler {
> ```

it seems more like a helper class than a handler. 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFY7XZ9qk56OSv1gd1:-NSFY7XZ9qk56OSv1gd2:bsioknm) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L22)):*
> ```Java
> public class GitExperienceSettingsHandler {
>   @Inject private NGSettingsClient ngSettingsClient;
>   public boolean isGitExperienceEnforcedInSettings(String accountId, String orgIdentifier, String projIdentifier) {
> ```

here also rename it to accountIdentifier
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYE2jAs_xrXGkDpVF:-NSFYE2jAs_xrXGkDpVG:b78d5m2) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L31)):*
> ```Java
>   }
> 
>   public void enforceGitExperienceIfApplicable(
> ```

can we put this class in a common place? I see this block of code repeated in template service as well


<!-- Sent from Reviewable.io -->

2023-04-05 16:53 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFXvcyALuhpFkGF6IH:-NSHK4yh3r2LZ-JM5AJM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L183)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

let's use accountIdentifier here instead of accountId, for uniformity.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYVVt6h1WEMuo-aWe:-NSHKBFq5fLysblBcsNN:b-acwr2f) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L20)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

it seems more like a helper class than a handler. 
</blockquote></details>

discussed on call
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFY7XZ9qk56OSv1gd1:-NSHKPBlBmcF6Up1Iry-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L22)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

here also rename it to accountIdentifier
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYE2jAs_xrXGkDpVF:-NSHKQ0pAQzM79cfdn9C:b-4al4c7) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L31)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

can we put this class in a common place? I see this block of code repeated in template service as well
</blockquote></details>

As discussed i was not able to put it into 878 as NGsettings is not visible there.and also 970, 980 commons that's i have duplicated code.


<!-- Sent from Reviewable.io -->

2023-04-05 19:23 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYVVt6h1WEMuo-aWe:-NSHrr6jAnhMprrxPGjX:bqu0jvz) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L20)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

discussed on call
</blockquote></details>

Please also mention the conclusion of the discussion for other reviewers' reference.


<!-- Sent from Reviewable.io -->

2023-04-06 06:43 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/46021#-NSKIT_s69BTk2VVrz0e:-NSKIT_s69BTk2VVrz0f:b-ji1grx) ([raw file](https://github.com/harness/harness-core/blob/456a63770ac8a6e4b4002a70f22cb58c7ba0e8ae/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L175)):*
> ```Java
>       GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
> 
>       if (gitEntityInfo == null || StoreType.INLINE.equals(gitEntityInfo.getStoreType())) {
> ```

if (gitEntityInfo == null || TemplateUtils.isInlineEntity(gitEntityInfo)) {


<!-- Sent from Reviewable.io -->

2023-04-06 06:44 UTC, mohitg0795 commented
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFXvcyALuhpFkGF6IH:-NSKIeK-7K_NQQXF3oZa:b7slj80) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L183)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There was a helper class for all gitx settings right? Why are we not using it here?


<!-- Sent from Reviewable.io -->

2023-04-06 06:47 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYE2jAs_xrXGkDpVF:-NSKJSH138Nk0nLGB1-J:bbs56iy) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L31)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

As discussed i was not able to put it into 878 as NGsettings is not visible there.and also 970, 980 commons that's i have duplicated code.
</blockquote></details>

Whats the issue here? Wdym "NGSettings" is not visible in 878?


<!-- Sent from Reviewable.io -->

2023-04-06 06:48 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/46021#-NSKJ_dqEwHXrXdbhg1H:-NSKJ_dqEwHXrXdbhg1I:b-u7d04y) ([raw file](https://github.com/harness/harness-core/blob/456a63770ac8a6e4b4002a70f22cb58c7ba0e8ae/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L142)):*
> ```Java
>   @Inject @Named("PRIVILEGED") private ProjectClient projectClient;
>   @Inject PmsFeatureFlagService pmsFeatureFlagService;
>   @Inject GitExperienceSettingsHandler gitExperienceSettingsHandler;
> ```

lets simply say "GitXSettingsHandler". Using different conventions of naming just unnecessarily adds confusion.


<!-- Sent from Reviewable.io -->

2023-04-06 06:55 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFXvcyALuhpFkGF6IH:-NSKKjfo1HNwXZhZgYXz:bbn3se7) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L183)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

There was a helper class for all gitx settings right? Why are we not using it here?
</blockquote></details>

Now after moving it to right place and including in the build now we are using it.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYVVt6h1WEMuo-aWe:-NSKKsaN2tmGjguJnmc_:b-ot6gnt) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please also mention the conclusion of the discussion for other reviewers' reference.
</blockquote></details>

As this class primarily dictates the behaviour of settings thats why it was named as handler rather than helper.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFYE2jAs_xrXGkDpVF:-NSKL1n75ULHt683Jn80:b-v71qid) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Whats the issue here? Wdym "NGSettings" is not visible in 878?
</blockquote></details>

Now i have included the clients in build.bazel of 878, now it is visible.


<!-- Sent from Reviewable.io -->

2023-04-06 07:40 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 17 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/46021#-NSKIT_s69BTk2VVrz0e:-NSKVQk7-AKAYdbMrH5W:b-bcop7w) ([raw file](https://github.com/harness/harness-core/blob/456a63770ac8a6e4b4002a70f22cb58c7ba0e8ae/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L175)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if (gitEntityInfo == null || TemplateUtils.isInlineEntity(gitEntityInfo)) {
</blockquote></details>

this method has been moved to 878-ng-commons
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/46021#-NSKJ_dqEwHXrXdbhg1H:-NSKVX_B6hxcD17Hu15C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/456a63770ac8a6e4b4002a70f22cb58c7ba0e8ae/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L142)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets simply say "GitXSettingsHandler". Using different conventions of naming just unnecessarily adds confusion.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/46021#-NSFY5E_1OD6xvMi6mgp:-NSKVVDk9Tx2j1cdAqwq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd7e7b133382c6054518ea204d0da2b1037edf5d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/GitExperienceSettingsHandler.java#L19)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

add @OwnedBy annotation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-06 07:43 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 17 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/46021#-NSKIT_s69BTk2VVrz0e:-NSKW6FeDclwydP4hRBU:bqwiizu) ([raw file](https://github.com/harness/harness-core/blob/456a63770ac8a6e4b4002a70f22cb58c7ba0e8ae/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L175)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

this method has been moved to 878-ng-commons
</blockquote></details>

now as it is moved in ng-commons this utility method is not visible in 878-ng-commons during build hence not used it


<!-- Sent from Reviewable.io -->

2023-04-06 08:57 UTC, senjucanon2 commented
trigger ut5

2023-04-06 12:49 UTC, shalini-agr submitted a review, later dismissed
> Reviewed 1 of 7 files at r1, 1 of 13 files at r2, 2 of 4 files at r3, 3 of 12 files at r4, 7 of 9 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 18 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-07 05:26 UTC, archit-harness requested changes
> Reviewed 1 of 7 files at r1, 2 of 4 files at r3, 2 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSP9WuE6e7dFYObogMs:-NSP9WuE6e7dFYObogMt:brz9i14) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L24)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> public class GitXSettingsHandler {
> ```

add singleton annotation
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 30 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPAEFCDu-VO7HlfujJ:-NSPAEFCDu-VO7HlfujK:b-16zhok) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L30)):*
> ```Java
>     String isGitExperienceEnforced =
>         NGRestUtils
>             .getResponse(ngSettingsClient.getSetting(
> ```

on exception what we want to do?


<!-- Sent from Reviewable.io -->

2023-04-07 06:56 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 26 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPV9wB3b5a0XiWIR5u:-NSPV9wB3b5a0XiWIR5v:b-u607y7) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L26)):*
> ```Java
> public class GitXSettingsHandler {
>   @Inject private NGSettingsClient ngSettingsClient;
>   public boolean isGitExperienceEnforcedInSettings(
> ```

please add blank line before the method


<!-- Sent from Reviewable.io -->

2023-04-07 06:59 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 41 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPVoej6DpThS16fCk8:-NSPVoej6DpThS16fCk9:bjodrei) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L41)):*
> ```Java
>       GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
> 
>       if (gitEntityInfo == null || StoreType.INLINE.equals(gitEntityInfo.getStoreType())) {
> ```

If entity is already REMOTE, then why do we need to do this check? We can simply ignore it and return from first line.


<!-- Sent from Reviewable.io -->

2023-04-07 07:05 UTC, mohitg0795 commented
*[`840-template-service/src/test/java/io/harness/template/services/TemplateGitXServiceImplTest.java` line 58 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPX9by1sc_tmmZv5Gy:-NSPX9by1sc_tmmZv5Gz:bo4z8d3) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/840-template-service/src/test/java/io/harness/template/services/TemplateGitXServiceImplTest.java#L58)):*
> ```Java
>   @Mock GitAwareEntityHelper gitAwareEntityHelper;
> 
>   @Mock NGSettingsClient ngSettingsClient;
> ```

where is this being used?


<!-- Sent from Reviewable.io -->

2023-04-07 07:09 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 36 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPXMUl8VYBzQC_MpWg:-NSPXMUl8VYBzQC_MpWh:b-cmbe3o) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L36)):*
> ```Java
>   }
> 
>   public void enforceGitExperienceIfApplicable(
> ```

I'm not able to understand the motto of this class.
1) Initially, I thought its just a class that works as a client to check different GitX Settings that we have and will have in future. But I see it has other methods also that define functionality.
2) Is it possible to keep this class for only handling checking of settings? If not, then I think checking of settings should be only a private call as we are considering this class as E2E Gitx settings handler which handles both functionality + fetching of settings. The other way would be to use this class only to get settings status for Gitx related settings and then use these status in some functional interfaces in other already existing common utility class. The latter looks better to me.


<!-- Sent from Reviewable.io -->

2023-04-07 10:25 UTC, mohitg0795 commented
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 43 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSQEr4K3OOee6uWOy6p:-NSQEr4K3OOee6uWOy6q:b-rfw1eg) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L43)):*
> ```Java
>       if (gitEntityInfo == null || StoreType.INLINE.equals(gitEntityInfo.getStoreType())) {
>         throw new InvalidRequestException(String.format(
>             "Git Experience is enforced for the current scope with accountId: %s, orgIdentifier: %s and projIdentifier: %s. Hence Inline Entities cannot be created.",
> ```

This message should be generic, not specific to any operation "created".



_Code quote:_
```Java
Hence Inline Entities cannot be created.",
```


<!-- Sent from Reviewable.io -->

2023-04-09 16:31 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 17 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/test/java/io/harness/template/services/TemplateGitXServiceImplTest.java` line 58 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPX9by1sc_tmmZv5Gy:-NSaqNII3Qi-PhBgBsUz:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/840-template-service/src/test/java/io/harness/template/services/TemplateGitXServiceImplTest.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

where is this being used?
</blockquote></details>

Removed
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSP9WuE6e7dFYObogMs:-NSaqR1J23Ru6He-ybDU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add singleton annotation
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 26 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPV9wB3b5a0XiWIR5u:-NSaqXUT2tBuko4D_q4S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please add blank line before the method
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 30 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPAEFCDu-VO7HlfujJ:-NSaqRUH8SGTH7gnDE5Y:bmyt2el) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

on exception what we want to do?
</blockquote></details>

We would want that exception to surface up at the api level.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 36 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPXMUl8VYBzQC_MpWg:-NSaqc8d6vFDXF6AmE2A:boop0d7) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L36)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I'm not able to understand the motto of this class.
1) Initially, I thought its just a class that works as a client to check different GitX Settings that we have and will have in future. But I see it has other methods also that define functionality.
2) Is it possible to keep this class for only handling checking of settings? If not, then I think checking of settings should be only a private call as we are considering this class as E2E Gitx settings handler which handles both functionality + fetching of settings. The other way would be to use this class only to get settings status for Gitx related settings and then use these status in some functional interfaces in other already existing common utility class. The latter looks better to me.
</blockquote></details>

As discussed from now onwards this will the only GitXSettingsHelper class and all settings will be in this class. Previous implementations are for now ignored and will be picked up as another item.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 41 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSPVoej6DpThS16fCk8:-NSaqYif5igNWWYWAi-v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If entity is already REMOTE, then why do we need to do this check? We can simply ignore it and return from first line.
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java` line 43 at r8](https://reviewable.io/reviews/harness/harness-core/46021#-NSQEr4K3OOee6uWOy6p:-NSaqZps94948fS7hAxh:b-irtn3e) ([raw file](https://github.com/harness/harness-core/blob/6142325dd81ac8841f51436fb0fc5475c3344aba/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHandler.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This message should be generic, not specific to any operation "created".
</blockquote></details>

Changed message


<!-- Sent from Reviewable.io -->

2023-04-12 05:35 UTC, senjucanon2 commented
trigger ut0, ut1, ut2, ut5

2023-04-17 07:38 UTC, archit-harness reviewed
> Reviewed 1 of 13 files at r2, 1 of 12 files at r4, 1 of 2 files at r6, 5 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 14 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-18 06:07 UTC, mohitg0795 submitted a review, later dismissed
> Reviewed 1 of 7 files at r1, 1 of 13 files at r2, 1 of 4 files at r3, 3 of 12 files at r4, 1 of 2 files at r6, 7 of 12 files at r9, 3 of 3 files at r10, 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-18 07:49 UTC, mohitg0795 approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-18 08:22 UTC, archit-harness approved these changes
> Reviewed 2 of 12 files at r4, 2 of 12 files at r9, 3 of 3 files at r10, 2 of 3 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-18 09:13 UTC, shalini-agr approved these changes
> Reviewed 6 of 12 files at r9, 3 of 3 files at r10, 2 of 3 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-18 09:13 UTC, shalini-agr commented
trigger review

2023-04-18 09:45 UTC, utkarshchoubey-harness approved these changes
> Reviewed 1 of 7 files at r1, 1 of 13 files at r2, 1 of 4 files at r3, 3 of 12 files at r4, 1 of 2 files at r6, 6 of 12 files at r9, 3 of 3 files at r10, 2 of 3 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46021)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-18 09:47 UTC, merged