[feat]: [PL-29550]: API support to block Debezium events processing of a specific account.
harness/harness-core pull request #46107
Opened 2023-04-05 10:05 UTC by ashishsanodia-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-17 10:32 UTC, ashishsanodia-harness commented
*[`access-control/config/config.yml` line 277 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDC_sz727nKjJPRtc_:-NTDlAth2Ds-teidqluX:b6a8xv5) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/config/config.yml#L277)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we really need Distributed cache here?
</blockquote></details>

With distributed cache it will be visible to other pods as well.


<!-- Sent from Reviewable.io -->

2023-04-17 10:32 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDJQqPE_XtekPL1ilQ:-NTDlPge3t8yByYuSyYK:b-uuo60x) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L75)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getBlockedAccounts

This method doesn't return list?
</blockquote></details>

It returns generic Response. in impl we are returning list of blocked accounts


<!-- Sent from Reviewable.io -->

2023-04-17 10:33 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDLLcq4LRMUYVD-vl7:-NTDlYdp1bCdQFElG-9r:b-lbxrgs) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L53)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the need for this method?
</blockquote></details>

to check if account is already blocked 


<!-- Sent from Reviewable.io -->

2023-04-17 10:34 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDLYpU9q5Wo1dbB5sK:-NTDlkYd1yG6PqKOtR6u:bec65wb) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L75)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we do this after migration or before migration?
</blockquote></details>

Both ways it will run asynchronously 


<!-- Sent from Reviewable.io -->

2023-04-17 10:35 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDLcsABLeRCxYiqXh6:-NTDlx6g7nDQU3lPJFfU:b-4wqwgk) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L93)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the need for this method?
</blockquote></details>

cache is configured with expiry of 30 minutes. this is to ensure cache is loaded from db after expiry


<!-- Sent from Reviewable.io -->

2023-04-17 10:36 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleAssignmentChangeConsumerImpl.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDJmCM8kpkd3g21m8M:-NTDmFWu6KP79Q_fWNVk:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleAssignmentChangeConsumerImpl.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the need for accessControlAdminService in change consumers?
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2023-04-17 10:39 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/AccessControlEntity.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDJyrp6io9F0wOkqea:-NTDmyiY5qGzI26Jkvnw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/core/src/main/java/io/harness/accesscontrol/AccessControlEntity.java#L15)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think this should not be default method. Returning null isn't a proper default implementation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-17 10:39 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDCoVE5974meP4iiHP:-NTDlOMbBFBRgxdaaHIh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L59)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

blockAccount(BlockAccountDTO)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-17 10:39 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDJL1S-4HWwpYWIUME:-NTDlP6QCTAfrs7_KGfS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L68)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

unblockAccount(UnblockAccountDTO)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-17 10:39 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 70 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDLF0_6Bsu1PlzQgmg:-NTDljiD0W7_3zUSehZ2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L70)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

unblock
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-18 05:01 UTC, meenakshi-harness commented on access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/UnblockAccountDTO.java
> +  String accountIdentifier;
This is required field?

2023-04-18 05:03 UTC, meenakshi-harness commented on access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/BlockAccountDTO.java
> +  String accountIdentifier;
same

2023-04-18 05:07 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46107)* status: 38 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDpMlyDIS-rSKNcNnj:-NTDpMlyDIS-rSKNcNnk:btwwxif) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L56)):*
> ```Java
>   @POST
>   @Path("change-events/block")
>   @ApiOperation(value = "Blocks change events for given ACL entity", nickname = "blockChangeEvents", hidden = true)
> ```

Blocks change events for given account.



_Code quote:_
```Java
Blocks change events for given ACL entity
```
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDpQJB416q-qpNNeY_:-NTDpQJB416q-qpNNeYa:btwwxif) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L57)):*
> ```Java
>   @Path("change-events/block")
>   @ApiOperation(value = "Blocks change events for given ACL entity", nickname = "blockChangeEvents", hidden = true)
>   @Operation(operationId = "blockChangeEvents", summary = "Blocks change events for given ACL entity", hidden = true)
> ```

Blocks change events for given account.
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTF67wh8ZvnDj8ggKjN:-NTF67wh8ZvnDj8ggKjO:bxyzbfz) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L90)):*
> ```Java
>           blockedAclAccount -> blockedAclAccount.equalsIgnoreCase(accessControlEntity.getAccountId()));
>     }
>     return true;
> ```

This should return false. since if there is no blocked account it should return false.


<!-- Sent from Reviewable.io -->

2023-04-18 05:12 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/BlockAccountDTO.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/46107#gh-1169491259:-NTHloXl3LZVH5N-wBTT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f588d3c767f7faedbc8af124e8f3c7738674de8b/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/BlockAccountDTO.java#L29)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-18 05:12 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/UnblockAccountDTO.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/46107#gh-1169490528:-NTHlprCE_AdK4L5Iq4p:b5k5oqm) ([raw file](https://github.com/harness/harness-core/blob/f588d3c767f7faedbc8af124e8f3c7738674de8b/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/UnblockAccountDTO.java#L29)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

This is required field?
</blockquote></details>

Yes, Fixed


<!-- Sent from Reviewable.io -->

2023-04-18 05:19 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDpMlyDIS-rSKNcNnj:-NTHnOSI8MaJZ7hREcgG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L56)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Blocks change events for given account.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-18 05:19 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDpQJB416q-qpNNeY_:-NTHnPVT7QQyTGtOiNMB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L57)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Blocks change events for given account.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-18 05:22 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTF67wh8ZvnDj8ggKjN:-NTHo92w09Rkm1y50nFQ:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L90)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This should return false. since if there is no blocked account it should return false.
</blockquote></details>

Fixed



_Code quote:_
```Java
isBlocked(AccessControlEntity 
```


<!-- Sent from Reviewable.io -->

2023-04-18 06:17 UTC, ankit-harness requested changes
> Reviewed 2 of 23 files at r1, 1 of 21 files at r2, 7 of 22 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46107)* status: 38 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/config/config.yml` line 277 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDC_sz727nKjJPRtc_:-NTHxDic7He8ul0jMVvW:bir2rgk) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/config/config.yml#L277)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

With distributed cache it will be visible to other pods as well.
</blockquote></details>

Agree. But is it important for correctness? InMemory cache can also serve purpose here well
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDJQqPE_XtekPL1ilQ:-NTHxWEs8vrIsw_v_6-2:b38n5j6) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L75)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

It returns generic Response. in impl we are returning list of blocked accounts
</blockquote></details>

Is this how we have APIs at other places too?
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 55 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTHxcQtD-5heu1TvfUW:-NTHxcQtD-5heu1TvfUX:b-hhr7p) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L55)):*
> ```Java
> public interface AccessControlAdminResource {
>   @POST
>   @Path("change-events/block")
> ```

Should we mention change-events in the endpoints or description? It sounds to me an implementation detail. 
What about just mentioning block/unblock at the API level.
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDLLcq4LRMUYVD-vl7:-NTHzUby7Gn8xVRFRixQ:b-szhbf9) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L53)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

to check if account is already blocked 
</blockquote></details>

Methods in the service layer should be domain centric rather than repository centric like 
boolean isBlocked(String accountIdentifier);
List<BlockedAccount> getAllBlockedAccounts();

Also, do these methods need to be public?
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDLcsABLeRCxYiqXh6:-NTHyZ-22t0Mhya5H_ca:b-jxhk1g) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L93)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

cache is configured with expiry of 30 minutes. this is to ensure cache is loaded from db after expiry
</blockquote></details>

If we use in memory cache we can configure cache to do it implicitly
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 77 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTHyg4VDw32QXgCk1JK:-NTHyg4VDw32QXgCk1JL:bmk6bzz) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L77)):*
> ```Java
>     blockedEventsCache.put(BLOCKED_ACL_ACCOUNTS, blockedAclAccounts);
>     String scopeIdentifier = "/ACCOUNT/" + accountIdentifier;
>     executorService.execute(() -> generateACLsFromRoleAssignmentsJob.migrate(scopeIdentifier));
> ```

Can we pass just accountId to the migrate API. scopeIdentifier can be constructed internally in the API.
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/models/BlockedACLEntity.java` line 31 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTHzJHK3yZf8wTw3MGx:-NTHzJHK3yZf8wTw3MGy:b-d56s56) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/aggregator/src/main/java/io/harness/aggregator/models/BlockedACLEntity.java#L31)):*
> ```Java
> @Document("blockedACLEntity")
> @TypeAlias("blockedACLEntity")
> public class BlockedACLEntity {
> ```

BlockedAccount
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/repositories/BlockedACLEntityRepository.java` line 28 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTHzLHo3RBBtD6xbSHT:-NTHzLHo3RBBtD6xbSHU:bp426s4) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/aggregator/src/main/java/io/harness/aggregator/repositories/BlockedACLEntityRepository.java#L28)):*
> ```Java
> @Singleton
> @ValidateOnExecution
> public class BlockedACLEntityRepository {
> ```

BlockedEntityRepository
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDBO.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-ZZi5z4jfetKEs4F:-NTI-ZZi5z4jfetKEs4G:b-y71mys) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDBO.java#L98)):*
> ```Java
> 
>   @Override
>   public String getAccountId() {
> ```

Why is it null?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/users/persistence/UserDBO.java` line 100 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-_9oBTB29e_eP4Ur:-NTI-_9oBTB29e_eP4Us:b-y71mys) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/users/persistence/UserDBO.java#L100)):*
> ```Java
> 
>   @Override
>   public String getAccountId() {
> ```

Why is it null?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDBO.java` line 83 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-e4x16CsUqcSr5HM:-NTI-e4x16CsUqcSr5HN:b-y71mys) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDBO.java#L83)):*
> ```Java
> 
>   @Override
>   public String getAccountId() {
> ```

Why is it null?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/support/persistence/SupportPreferenceDBO.java` line 84 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-R2Q4ccjCRB_JDlK:-NTI-R2Q4ccjCRB_JDlL:b-y71mys) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/service/src/main/java/io/harness/accesscontrol/support/persistence/SupportPreferenceDBO.java#L84)):*
> ```Java
> 
>   @Override
>   public String getAccountId() {
> ```

Why is  [...]

2023-04-19 18:20 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDJQqPE_XtekPL1ilQ:-NTPjGn3-bvRzl8EKMgG:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L75)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is this how we have APIs at other places too?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2023-04-19 18:22 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 55 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTHxcQtD-5heu1TvfUW:-NTPkFZm1iEnVJINzAKb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L55)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we mention change-events in the endpoints or description? It sounds to me an implementation detail. 
What about just mentioning block/unblock at the API level.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-19 18:23 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDLLcq4LRMUYVD-vl7:-NTPkOr_4-VJWf6feydT:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L53)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Methods in the service layer should be domain centric rather than repository centric like 
boolean isBlocked(String accountIdentifier);
List<BlockedAccount> getAllBlockedAccounts();

Also, do these methods need to be public?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-04-19 18:25 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDBO.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-ZZi5z4jfetKEs4F:-NTPku6D44jcan-n5k86:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDBO.java#L98)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is it null?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-04-19 18:25 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/users/persistence/UserDBO.java` line 100 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-_9oBTB29e_eP4Ur:-NTPkyq8AD3Ul1LBCuZ-:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/users/persistence/UserDBO.java#L100)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is it null?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-04-19 18:26 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeHelper.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDKM9e6nqU_gd45Kcf:-NTPl1Ig29vFjP8LpB-X:b-o70jgf) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/ScopeHelper.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Add comment in this method. Logic isn't clear.

Is there already a helper method which gets account id from scope identifier?
</blockquote></details>

Added comment. 
There is no existing helper method


<!-- Sent from Reviewable.io -->

2023-04-19 18:27 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDBO.java` line 83 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-e4x16CsUqcSr5HM:-NTPlDd78Nl6CE6UIz_n:b-kriafh) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/core/persistence/ScopeDBO.java#L83)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is it null?
</blockquote></details>

no account or scope info available


<!-- Sent from Reviewable.io -->

2023-04-19 18:29 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/support/persistence/SupportPreferenceDBO.java` line 84 at r7](https://reviewable.io/reviews/harness/harness-core/46107#-NTI-R2Q4ccjCRB_JDlK:-NTPlj8D2wd2NGoqBuwi:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/45581bb23fba1a9776de8538c3039a099d949893/access-control/service/src/main/java/io/harness/accesscontrol/support/persistence/SupportPreferenceDBO.java#L84)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is it null?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-04-19 18:40 UTC, ashishsanodia-harness commented
*[`access-control/config/config.yml` line 277 at r3](https://reviewable.io/reviews/harness/harness-core/46107#-NTDC_sz727nKjJPRtc_:-NTPk7lQ6vtOpnF6B_NB:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/9dd1e8a1b4b46dc9ab4f9daf08965a2c3ed33416/access-control/config/config.yml#L277)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Agree. But is it important for correctness? InMemory cache can also serve purpose here well
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2023-04-20 06:33 UTC, ashishsanodia-harness commented
trigger checkstylecodeformat

2023-04-20 09:34 UTC, ashishsanodia-harness commented
trigger ut8

2023-04-20 10:22 UTC, ankit-harness requested changes
> Reviewed 1 of 22 files at r4, 3 of 11 files at r8, 3 of 5 files at r9, 15 of 15 files at r10, 4 of 4 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46107)* status: 38 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 60 at r13](https://reviewable.io/reviews/harness/harness-core/46107#-NTT77ur7xDRLwf7Y5nn:-NTT77ur7xDRLwf7Y5no:b-x6c90c) ([raw file](https://github.com/harness/harness-core/blob/6de25526ffed17d371e4acf51c39bc3f8be698e7/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L60)):*
> ```Java
>       value = "Blocks change events for given account", nickname = "blockChangeEventsForAccount", hidden = true)
>   @Operation(
>       operationId = "blockChangeEventsForAccount", summary = "Blocks change events for given account", hidden = true)
> ```

  @Operation(
      operationId = "blockAccount", summary = "Blocks processing ACLs for a given account", hidden = true)



_Code quote:_
```Java
  @Operation(
      operationId = "blockChangeEventsForAccount", summary = "Blocks change events for given account", hidden = true)
```
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 44 at r13](https://reviewable.io/reviews/harness/harness-core/46107#-NTT8Heh0sM3kamH3TAj:-NTT8Heh0sM3kamH3TAk:b-2orev4) ([raw file](https://github.com/harness/harness-core/blob/6de25526ffed17d371e4acf51c39bc3f8be698e7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L44)):*
> ```Java
>     this.blockedEntityRepository = blockedEntityRepository;
>     this.generateACLsFromRoleAssignmentsJob = generateACLsFromRoleAssignmentsJob;
>     executorService = Executors.newSingleThreadExecutor(
> ```

I think we should have a pool of 5 threads or so
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 49 at r13](https://reviewable.io/reviews/harness/harness-core/46107#-NTT7aVy3kn7ELz-STRD:-NTT7aVzDWG_K-iGXW6V:bl4k0z) ([raw file](https://github.com/harness/harness-core/blob/6de25526ffed17d371e4acf51c39bc3f8be698e7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L49)):*
> ```Java
>                               .maximumSize(10000)
>                               .expireAfterWrite(30, TimeUnit.MINUTES)
>                               .build(accountId -> blockedEntityRepository.find(accountId).isPresent());
> ```

If accountId is removed from repository, what would cache do? Ignore it?


<!-- Sent from Reviewable.io -->

2023-04-20 11:44 UTC, ashishsanodia-harness commented
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java` line 60 at r13](https://reviewable.io/reviews/harness/harness-core/46107#-NTT77ur7xDRLwf7Y5nn:-NTTTk560dLjcm_5qaa0:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/6de25526ffed17d371e4acf51c39bc3f8be698e7/access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api/AccessControlAdminResource.java#L60)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

  @Operation(
      operationId = "blockAccount", summary = "Blocks processing ACLs for a given account", hidden = true)

</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-04-20 11:45 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java` line 49 at r13](https://reviewable.io/reviews/harness/harness-core/46107#-NTT7aVy3kn7ELz-STRD:-NTTQEP4-_mYFYXU_hen:b-rzlt3a) ([raw file](https://github.com/harness/harness-core/blob/6de25526ffed17d371e4acf51c39bc3f8be698e7/access-control/libs/aggregator/src/main/java/io/harness/aggregator/AccessControlAdminService.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

If accountId is removed from repository, what would cache do? Ignore it?
</blockquote></details>

Cache is of type <String, Boolean>. It keeps key as <account-id> and value as <isBlocked>[true/false]

When we unblock account it deletes entry from cache as well. If subsequent request comes for the same account it will add entry in cache with value as false



_Code snippet:_
```Java
key = <account-id> and value = false
```


<!-- Sent from Reviewable.io -->

2023-04-20 11:50 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46107#-:-NTTUzrRCPzjowuEks6G:bnfp4nl)* status: 38 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-21 09:26 UTC, meenakshi-harness approved these changes

2023-04-24 13:50 UTC, Jimit09Gandhi approved these changes
> Reviewed 2 of 23 files at r1, 1 of 21 files at r2, 6 of 22 files at r4, 3 of 11 files at r8, 2 of 5 files at r9, 15 of 15 files at r10, 4 of 4 files at r11, 2 of 3 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46107)* status: Some of the checks are too old. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-25 04:35 UTC, merged