fix: [CDS-58542]: remove userInvite from the list of usergroups
harness/harness-core pull request #46194
Opened 2023-04-06 20:13 UTC by rafaelmart1ns

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-06 20:21 UTC, lasdox approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46194)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-06 20:25 UTC, lasdox submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46194)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-06 20:26 UTC, rafaelmart1ns reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46194)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-06 20:30 UTC, vcalasansh submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46194)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-07 06:29 UTC, AnshuH commented
trigger review

2023-04-10 12:29 UTC, rafaelmart1ns commented
trigger review

2023-04-10 14:33 UTC, meenakshi-harness commented on 400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupQueryHelper.java
> -    CriteriaContainer userGroupsCriteria = userGroupsQuery.criteria("_id").in(userGroups);
Why are we removing this whole flow. Can we sync on this?

2023-04-10 14:35 UTC, meenakshi-harness commented on 400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupQueryHelper.java
> -    query.or(memberIdsCriteria, userGroupsCriteria);
Can you add the testing done for this 
1. What is expected response.
2. What is existing response and new response ( Add screenshot preferably)
3. UTs

2023-04-10 14:35 UTC, meenakshi-harness approved these changes

2023-04-10 14:35 UTC, meenakshi-harness requested changes
Can you add the testing done for this

What is expected response.
What is existing response and new response ( Add screenshot preferably)
UTs
Test this change for new users as well

2023-04-10 19:56 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupQueryHelper.java
> -    CriteriaContainer userGroupsCriteria = userGroupsQuery.criteria("_id").in(userGroups);
Its synced up.

2023-04-10 19:57 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupQueryHelper.java
> -    query.or(memberIdsCriteria, userGroupsCriteria);
I added a video in the description as an example of behaviour.
It added UT.

2023-04-12 17:27 UTC, vcalasansh approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46194)* status: 2 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-12 17:37 UTC, rafaelmart1ns commented
trigger review

2023-04-12 17:39 UTC, merged