feat: [CDS-54461]: Adding K8s Instnace sync v2 Task Executor for NG
harness/harness-core pull request #46208
Opened 2023-04-07 06:49 UTC by namantalaycha10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-07 08:30 UTC, abosii-harness requested changes

2023-04-07 08:30 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +  public K8sInfraDelegateConfig getK8sInfraDelegateConfig(
We should move this to a different class

2023-04-07 08:30 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +              .encryptionDataDetails(getEncryptionDataDetails(connectorDTO, ngAccess))
Encryption details are already available as part of the K8sInstanceSyncTaskParams

2023-04-07 08:30 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +  private List<ServerInstanceInfo> getServerInstanceInfoList(PodDetailsRequest requestData) {
Move this to a different class and share it with v1 impl

2023-04-07 08:30 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +public class K8sInstanceSyncPerpetualTaskV2Executor implements PerpetualTaskExecutor {
Can we have some structure like:
`interface PerpetualTaskExecutor {}

class AbstractInstanceSyncV2TaskExectur {

    public PerpetualTaskResponse runOnce() {
        fetch task details 
        ... retrieveServiceInstances
        publish response
    }

    protected abstract List<ServerInstanceInfo> retrieveServiceInstances(DeploymentReleaseDetails details);
}


K8sInstanceSyncV2TaskExector extends AbstractInstanceSyncV2TaskExector {
    @Override
    protected List<ServerInstanceInfo> retrieveServiceInstances(DeploymentReleaseDetails details) {

    }
}`

2023-04-07 08:30 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/k8s_instance_sync_task_params_v2.proto
>      string cluster_name = 3;
message CloudClusterConfig {
  string clsuter_name = 1;
  string subscription_id = 2;
  string resource_group = 3;
}

2023-04-07 08:30 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/k8s_instance_sync_task_params_v2.proto
> +  bool use_k8s_direct_socket_capability = 7;
not required

2023-04-07 09:36 UTC, abhinavsingh1196 requested changes
> Reviewed 2 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46208)* status: 8 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ-cm_CN_LTux3H6aT:-NSQ-cm_CN_LTux3H6aU:byvix23) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L114)):*
> ```Java
>   }
> 
>   private PerpetualTaskResponse executeK8sInstanceSyncTask(
> ```

this method is too big, we should break it down since we're writing from scratch
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ-FzS-BGXC7Z8uIsY:-NSQ-FzT5gkMOArwBlia:b-ov53cn) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L132)):*
> ```Java
>       if (Objects.isNull(instanceSyncTaskDetails)
>           || CollectionUtils.isEmpty(instanceSyncTaskDetails.getDetailsList())) {
>         log.error("No deployments to track for perpetualTaskId: [{}]. Nothing to do here.", taskId.getId());
> ```

Can this be warn?
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ-ts-9v1j_Om8l-7V:-NSQ-ts-9v1j_Om8l-7W:b-gdfz0b) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L145)):*
> ```Java
> 
>     } catch (IOException ioException) {
>       log.error("Failed to fetch InstanceSyncTaskDetails for perpetual task Id: {}", taskId.getId());
> ```

we can log account ID here as well
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ03yLEaUp-ijcq_-p:-NSQ03yLEaUp-ijcq_-q:b-f195th) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L148)):*
> ```Java
>       return PerpetualTaskResponse.builder()
>           .responseCode(Response.SC_OK)
>           .responseMessage(format("Failed to fetch InstanceSyncTaskDetails for perpetual task Id: [%s], accountId [%s]",
> ```

lets extract this string as a static class var
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ18uX6KgNF4KpNvWw:-NSQ18uX6KgNF4KpNvWx:b-n4y37m) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L159)):*
> ```Java
>     for (DeploymentReleaseDetails deploymentReleaseDetails : deploymentReleaseDetailsList) {
>       List<K8sDeploymentReleaseDetails> k8sDeploymentReleaseDetailsList =
>           deploymentReleaseDetails.getDeploymentDetailsList()
> ```

will deploymentDetailsList always be non-null?
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ2BlA9uKiyOQRaw8h:-NSQ2BlA9uKiyOQRaw8i:bz128au) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L221)):*
> ```Java
>       responseBuilder.clearInstanceData();
>       batchInstanceCount.set(0);
>       batchReleaseDetailsCount.set(0);
> ```

the code here is same as above, can be extracted to common method
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 299 at r2](https://reviewable.io/reviews/harness/harness-core/46208#gh-1160525102:-NSQ2niF7nKjKkakKNw3:b6yz7xn) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L299)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We should move this to a different class
</blockquote></details>

the above getKubernetesConfig method can be moved to this same class as well


<!-- Sent from Reviewable.io -->

2023-04-11 08:45 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46208)* status: 9 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/46208#gh-1160531161:-NSjTMVoC0hW642QKSyI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L91)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we have some structure like:
`interface PerpetualTaskExecutor {}

class AbstractInstanceSyncV2TaskExectur {

    public PerpetualTaskResponse runOnce() {
        fetch task details 
        ... retrieveServiceInstances
        publish response
    }

    protected abstract List<ServerInstanceInfo> retrieveServiceInstances(DeploymentReleaseDetails details);
}


K8sInstanceSyncV2TaskExector extends AbstractInstanceSyncV2TaskExector {
    @Override
    protected List<ServerInstanceInfo> retrieveServiceInstances(DeploymentReleaseDetails details) {

    }
}`
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ-cm_CN_LTux3H6aT:-NSjTNueEg_NBxx0_Max:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L114)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

this method is too big, we should break it down since we're writing from scratch
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ-FzS-BGXC7Z8uIsY:-NSjTOyM9HAP0NPJLHn1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L132)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

Can this be warn?
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ-ts-9v1j_Om8l-7V:-NSjTPhn7_byHErctn27:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L145)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

we can log account ID here as well
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ03yLEaUp-ijcq_-p:-NSjUAIkBAA4ZaGBOeuS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L148)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

lets extract this string as a static class var
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ18uX6KgNF4KpNvWw:-NSjUBroCYALOWFb5A84:b-kp59hs) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L159)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

will deploymentDetailsList always be non-null?
</blockquote></details>

we have a check for empty as well
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/46208#-NSQ2BlA9uKiyOQRaw8h:-NSjUHG76cmHPEuOb_If:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L221)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

the code here is same as above, can be extracted to common method
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 268 at r2](https://reviewable.io/reviews/harness/harness-core/46208#gh-1160526208:-NSjUIsu3ka7oQuXiCcn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L268)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Move this to a different class and share it with v1 impl
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 299 at r2](https://reviewable.io/reviews/harness/harness-core/46208#gh-1160525102:-NSjUJaGEmKh3CCMUb3p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L299)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

the above getKubernetesConfig method can be moved to this same class as well
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 308 at r2](https://reviewable.io/reviews/harness/harness-core/46208#gh-1160525754:-NSjULao006RBx6q6e0S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L308)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Encryption details are already available as part of the K8sInstanceSyncTaskParams
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/k8s_instance_sync_task_params_v2.proto` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/46208#gh-1160539866:-NSjUN727rQ3STWiTFok:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/k8s_instance_sync_task_params_v2.proto#L24)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

message CloudClusterConfig {
  string clsuter_name = 1;
  string subscription_id = 2;
  string resource_group = 3;
}
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/k8s_instance_sync_task_params_v2.proto` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/46208#gh-1160539883:-NSjUObn5CkwKeLGh3HP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e82c4541b610cac35a40e0b6656ab719dd6bbdaa/950-delegate-tasks-beans/src/main/p [...]

2023-04-11 11:54 UTC, abosii-harness requested changes

2023-04-11 11:54 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +    try {
to many try {
   try {
   
   } 
}

Can we refactor this logic and move some logic to a different method?

2023-04-11 11:54 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +        publishInstanceSyncResult(taskId, getAccountId(params),
You're calling multiple time getAccountId, we can reuse it

2023-04-11 11:54 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +        responseBuilder.addInstanceData(instanceSyncData);
Can we addInstanceData and update batch details in the respective try or catch blocks, maybe even moving this to a different method will make this more clean

2023-04-11 11:54 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +                                 .setExecutionStatus(CommandExecutionStatus.SUCCESS.name())
Execution status should be failed

2023-04-11 11:54 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +        if (batchInstanceCount.get() > instanceSyncTaskDetails.getResponseBatchConfig().getInstanceCount()
Can we move this check to a different method?

2023-04-11 11:54 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +      publishInstanceSyncResult(taskId, accountId,
The response from publishInstanceSyncResult is ignored. We should have a proper error handling in this case. 
1. Retry with back-off if it failed
2. If we're unable to publish then perpetual task should fail

2023-04-11 11:54 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +  protected abstract List<DeploymentReleaseDetails> fetchTaskDetails(
This method doesn't look like is required if you have getAccountId then you can make it common

2023-04-21 07:34 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46208)* status: 7 file(s) to review. 2 change requests. 21. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162684561:-NTHr02U7GWpDM-DL9c1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

to many try {
   try {
   
   } 
}

Can we refactor this logic and move some logic to a different method?
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 61 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162684603:-NTHr-_o2vjX32cugCDt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L61)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm confused here. There is a method fetchTaskDetails that is doing the same thing. Why we're doing 2 calls to fetchInstanceSyncV2TaskDetails? Can we remove method fetchTaskDetails?
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162684661:-NTHr-9e-3sZDdevKl2Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L64)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

You're calling multiple time getAccountId, we can reuse it
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 75 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162598882:-NTHqzjA8GWGHLDrJhyM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L75)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We don't need this new ArrayList
</blockquote></details>

Done.



_Code quote:_
```Java
fetchInstanceSyncV2TaskDetail
```
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162691069:-NTHr7Ha3S3VcszbmH2I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L99)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Execution status should be failed
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 104 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162691032:-NTHs5Vm9Jfa8TmRfbrz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L104)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we addInstanceData and update batch details in the respective try or catch blocks, maybe even moving this to a different method will make this more clean
</blockquote></details>

Done.



_Code quote:_
```Java
.setTaskInfoId(taskId.getId())
```
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162691093:-NTHuykB0J_-Z7_KsLHW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L108)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we move this check to a different method?
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 132 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162685774:-NTX_oCQ8MrdSk6ooZTv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L132)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this okay? Looks like we're treating this PT as successful but is not. This may end up in wrong PT lifecycle
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162695540:-NTX_tp-4HZuKjouQxVj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L140)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This method doesn't look like is required if you have getAccountId then you can make it common
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-21 07:59 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +  private String publishInstanceSyncResult(PerpetualTaskId taskId, String accountId, InstanceSyncResponseV2 response) {
Let's do 2 things:
1. Create a story for back-off retries
2. remove return and just have it void

2023-04-21 08:05 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +  protected abstract String getAccountId(PerpetualTaskExecutionParams params);
Let's add @NotNull annotation to params

2023-04-21 08:08 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +    List<EncryptedDataDetail> encryptedDataDetails =
We could do this deser before the for loop

2023-04-21 08:09 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +    extends AbstractInstanceSyncV2TaskExecutor implements PerpetualTaskExecutor {
implements PerpetualTaskExecutor is not required

2023-04-27 11:43 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46208)* status: 9 file(s) to review. 2 change requests. 27. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 122 at r4](https://reviewable.io/reviews/harness/harness-core/46208#gh-1162687936:-NTr4lj0B2sjyGSJKbmI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fd92ab9f9c4dbde8e03f8f327d575d7707a1635d/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L122)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

The response from publishInstanceSyncResult is ignored. We should have a proper error handling in this case. 
1. Retry with back-off if it failed
2. If we're unable to publish then perpetual task should fail 
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 161 at r6](https://reviewable.io/reviews/harness/harness-core/46208#gh-1173461712:-NTr4ztt4icoNv2SQ7QI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85c1728045a49a88a258ff8387978d655c53a476/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L161)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's add @NotNull annotation to params
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java` line 165 at r6](https://reviewable.io/reviews/harness/harness-core/46208#gh-1173453712:-NTr8USXAtogUnO45cA-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85c1728045a49a88a258ff8387978d655c53a476/260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java#L165)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's do 2 things:
1. Create a story for back-off retries
2. remove return and just have it void
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 87 at r6](https://reviewable.io/reviews/harness/harness-core/46208#gh-1173464093:-NU1WVKo7CqsLLjYfWXb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85c1728045a49a88a258ff8387978d655c53a476/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L87)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What will happen if you'll recieve 2 deployment release details with same namespace and release name? Like for blue/green there would be 2 releases having same namespace and release name but for different color. We should deduplicate it first
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 117 at r6](https://reviewable.io/reviews/harness/harness-core/46208#gh-1173464939:-NTr9ZGY9ARsoncrFZDE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85c1728045a49a88a258ff8387978d655c53a476/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L117)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We could do this deser before the for loop
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 136 at r6](https://reviewable.io/reviews/harness/harness-core/46208#gh-1173466320:-NU1WWFA7tKTvUwYFHcQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85c1728045a49a88a258ff8387978d655c53a476/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L136)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This can be implemented in base class
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-27 11:48 UTC, namantalaycha10 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46208#-:-NU1Xf9x2_mV0T2vW5PY:bnfp4nl)* status: 9 file(s) to review. 2 change requests. 28. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java` line 54 at r6](https://reviewable.io/reviews/harness/harness-core/46208#gh-1173465875:-NU1Xds8BAK6xjEMcbBu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85c1728045a49a88a258ff8387978d655c53a476/260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java#L54)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

implements PerpetualTaskExecutor is not required
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-27 12:45 UTC, namantalaycha10 commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +    for (K8sDeploymentReleaseDetails k8sDeploymentReleaseDetails : k8sDeploymentReleaseDetailsList) {
This will be resolve by using Set
I replace list with set

2023-04-27 12:51 UTC, abosii-harness submitted a review, later dismissed

2023-04-27 12:51 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2Executor.java
> +  @Override
nit: add a space before Override

2023-04-27 22:33 UTC, jennyjames21 commented
approving from del team. please add summary and test section





<!-- Sent from Reviewable.io -->

2023-04-27 22:33 UTC, jennyjames21 approved these changes
> Reviewed 1 of 6 files at r1, 2 of 7 files at r3, 1 of 3 files at r4, 1 of 2 files at r6, 3 of 5 files at r7, 3 of 4 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46208)* status: 8 file(s) to review. 1 change requests. 28. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team,k8s-team. 



<!-- Sent from Reviewable.io -->

2023-04-28 08:33 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +          .setDeploymentType(getDeploymentType(serverInstanceInfos.get(0)))
May end up in IndexOutOfBound, let's handle this in the next PR. We don't actually need relly on the serviceInstanceInfos

2023-04-28 08:33 UTC, abosii-harness approved these changes

2023-04-28 08:34 UTC, namantalaycha10 commented
trigger review

2023-04-28 09:30 UTC, abhinavsingh1196 approved these changes

2023-04-28 09:30 UTC, abhinavsingh1196 commented on 260-delegate/src/test/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2ExecutorTest.java
> +  @InjectMocks private K8sInstanceSyncPerpetualTaskV2Executor executor;
these mocks aren't initialized, we can remove them if not needed during the tests. Can do this in another PR.

2023-04-28 09:59 UTC, merged