[CDS-55073]: Save CD stage data to Stage ExecutionInfo Entities
harness/harness-core pull request #46216
Opened 2023-04-07 08:03 UTC by abhinavmittal-harness

## Describe your changes
Do not review yet.
In progress

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-12 13:56 UTC, ivan-83 requested changes
> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 315 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSp_t9C5x3CvoKKSdxI:-NSp_t9C5x3CvoKKSdxJ:b-eerhvn) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L315)):*
> ```Java
>         AmbianceUtils.getProjectIdentifier(ambiance), ambiance.getStageExecutionId());
>     if (stageExecutionInfo == null) {
>       saveStageExecutionInfoAndPublishExecutionInfoKey(ambiance, executionInfoKey, executionDetails);
> ```

Minor- This is not related to your changes, could you pls rename this method saveStageExecutionInfoAndPublishExecutionInfoKey to saveStageExecutionInfo because this is the core method and we are not publishing the stage execution key here? We are publishing it in one level up, caller method. 



_Code quote:_
```Java
saveStageExecutionInfoAndPublishExecutionInfoKey
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpdSB04bEs5GVIYayr:-NSpdSB04bEs5GVIYays:bv2jluq) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L91)):*
> ```Java
>   }
> 
>   private void saveStageExecutionDataToStageInfo(Ambiance ambiance, StepResponse stepResponse) {
> ```

Here we are updating stage execution info and that is major logic, could saving stage execution info without tags and startts bring us to the unexpected behavior and get exceptions later when we need to consume stage execution info where we expect startts
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpcI0m--XhZhn7RkEv:-NSpcI0m--XhZhn7RkEw:b-ho0dxx) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L96)):*
> ```Java
>         AmbianceUtils.getProjectIdentifier(ambiance), ambiance.getStageExecutionId());
>     if (stageExecutionInfo == null) {
>       log.error("StageExecutionInfo should not be null");
> ```

Pls, provide more details in the log msg like account id, org id, project id, and stage execution id. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpdCIi9wcEUecd3UYl:-NSpdCIi9wcEUecd3UYm:b-lyu21d) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L125)):*
> ```Java
>   }
> 
>   private void insertStageExecutionSummary(Ambiance ambiance, StageElementParameters stepParameters) {
> ```

Minor - I will rename this method to saveStageExecutionInfo because here we are saving a new StageExecutionInfo entity.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpblIGBtrqp0MMXTEC:-NSpblIGBtrqp0MMXTED:b-adgjgv) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L148)):*
> ```Java
>   }
> 
>   private Level getDeploymentStageStepCurrentLevel(Ambiance ambiance) {
> ```

Minor - check whether this method already exists in AmbianceUtils class, if not I suggest making it general and moving there.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpf_3C1g3eTXbKt_Q4:-NSpf_3DB6NAGAmeJvZn:b-rxlirk) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L206)):*
> ```Java
>         AmbianceUtils.getProjectIdentifier(ambiance), ambiance.getStageExecutionId());
>     if (stageExecutionInfo == null) {
>       log.error("stageExecutionInfo should not be null");
> ```

The same as above. I would create ExecutionSummaryService or.. as a wrapper around stageExecutionInfoService and put saving/updating env, service, stage, infra steps logic there including FF logic. It's easier for maintenance. And it is easy to reuse common logic between methods.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpfebM07SB30xkYe1O:-NSpfebM07SB30xkYe1P:b4unrrf) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L234)):*
> ```Java
>   }
> 
>   protected ServiceExecutionSummaryDetails createServiceInfoFromResponse(Ambiance ambiance, StepResponse stepResponse) {
> ```

protected -> private
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpfn9l2g4PJBexTwxs:-NSpfn9l2g4PJBexTwxt:b3beyt4) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L253)):*
> ```Java
>   }
> 
>   private Optional<ArtifactsOutcome> getArtifactsOutcome(Ambiance ambiance) {
> ```

Check CDStepHelper for the existence of this method. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpjWh393gKr7qkpPSt:-NSpjWh49YnW2Mn3vPu6:b-rtxbvs) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java#L87)):*
> ```Java
>     if (isDeploymentStageStep(event.getAmbiance())) {
>       processDeploymentStageEvent(event);
>     } else if (isRollbackStepNode(event.getAmbiance())) {
> ```

What if we have more rollback steps in the rollback stage will this logic work? 



_Code quote:_
```Java
dngPipelineExecutionUpdateEventHandler
```


<!-- Sent from Reviewable.io -->

2023-04-18 04:52 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: Some of the checks are too old. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpdSB04bEs5GVIYayr:-NTFdMVDAUPsjTAU5Nip:b-8yzchd) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L91)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Here we are updating stage execution info and that is major logic, could saving stage execution info without tags and startts bring us to the unexpected behavior and get exceptions later when we need to consume stage execution info where we expect startts
</blockquote></details>

Shouldn't as there is insertStageExecutionSummary called when obtainChild is called.
Which will always be called before handleChildren



_Code quote:_
```Java
saveStageExecutionDataToStageInfo
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpcI0m--XhZhn7RkEv:-NTFi4iF74vbtpMagovA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L96)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls, provide more details in the log msg like account id, org id, project id, and stage execution id. 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpblIGBtrqp0MMXTEC:-NTFeVjp0U2moBmvLuSE:bsmxah3) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L148)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - check whether this method already exists in AmbianceUtils class, if not I suggest making it general and moving there.
</blockquote></details>

This is very specific to Deployment Stage Step.
That's the reason haven't kept it there
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 206 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpf_3C1g3eTXbKt_Q4:-NTFhCk3Di7TkbNB6uey:b-hnb45p) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L206)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above. I would create ExecutionSummaryService or.. as a wrapper around stageExecutionInfoService and put saving/updating env, service, stage, infra steps logic there including FF logic. It's easier for maintenance. And it is easy to reuse common logic between methods.
</blockquote></details>

First of all right now the ng manager build will have cyclic dependencies and even if they can be resolved.
My though process was that the common service will need to understand all outcomes and values that might be specific to certain steps
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpfebM07SB30xkYe1O:-NTFi1Vg-s_eJxkvWDed:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L234)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

protected -> private
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpfn9l2g4PJBexTwxs:-NTFi8flBIl1WPMbU7Nf:bnz0ayo) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L253)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Check CDStepHelper for the existence of this method. 
</blockquote></details>

Cyclic dependency
Will have a look as a subsequent pr porbbaly
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/46216#-NSpjWh393gKr7qkpPSt:-NTFiBwt7_udnICIKq63:b-l5avi2) ([raw file](https://github.com/harness/harness-core/blob/2971a87661dd921e5aa73f263b486044f1246c90/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java#L87)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What if we have more rollback steps in the rollback stage will this logic work? 
</blockquote></details>

This is an existent logic that has been used.
And locally checked with having multiple shell script steps within a rollback stage and works fine


<!-- Sent from Reviewable.io -->

2023-04-18 12:03 UTC, ivan-83 approved these changes
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-18 19:12 UTC, abhinavmittal-harness commented
trigger ut0

2023-04-18 19:12 UTC, abhinavmittal-harness commented
trigger ut4

2023-04-19 08:28 UTC, abhinavmittal-harness commented
trigger ut7

2023-04-19 08:29 UTC, abhinavmittal-harness commented
trigger ut4

2023-04-19 08:39 UTC, abhinavmittal-harness commented
trigger feature-build

2023-04-19 11:31 UTC, abhinavmittal-harness commented
trigger feature-build

2023-04-20 07:54 UTC, abhinavmittal-harness commented
trigger utAll

2023-04-20 07:55 UTC, abhinavmittal-harness commented
trigger pmd

2023-04-20 09:13 UTC, yogesh-chauhan commented
We have the logic of saving Stage Execution Info scattered at multiple places, can we try to de-duplicate and move the logic to the service layer ?




<!-- Sent from Reviewable.io -->

2023-04-20 09:15 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 86 at r7](https://reviewable.io/reviews/harness/harness-core/46216#-NTSw_OrC0AejUnFMQq4:-NTSw_OrC0AejUnFMQq5:bs3cpal) ([raw file](https://github.com/harness/harness-core/blob/0b5416091731c457a844566761e9c3b370581f73/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L86)):*
> ```Java
>     if (ngFeatureFlagHelperService.isEnabled(
>             AmbianceUtils.getAccountId(ambiance), FeatureName.CDS_STAGE_EXECUTION_DATA_SYNC)) {
>       saveStageExecutionDataToStageInfo(ambiance, stepResponse);
> ```

instead of calling save from each place, can we differentiate between save and update ?
For eg.
obtainChildren -> saveStageExecutionData
handleChildResponse -> updateStageExecutionData


<!-- Sent from Reviewable.io -->

2023-04-20 09:15 UTC, yogesh-chauhan reviewed
> Reviewed 14 of 37 files at r1, 7 of 21 files at r2, 2 of 5 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: 9 file(s) to review. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-20 09:28 UTC, abhinavmittal-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java
> +  public void saveServiceExecutionDataToStageInfo(Ambiance ambiance, ArtifactsOutcome artifactsOutcome) {
At this moment I don't want to move Outcomes beans to StageExecutionInfoService.
As they were causing cyclic dependencies.
We will need to spend effort to improve the build files to do so.
I can try that in a subsequent pr maybe

2023-04-20 09:31 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: 9 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/46216#-NTSw7Ko3zcz8ZBjKGrf:-NTSzzNYDFkqvfezexW4:b-n3lbzo) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We have the logic of saving Stage Execution Info scattered at multiple places, can we try to de-duplicate and move the logic to the service layer ?
</blockquote></details>

I had tried that but they were causing cyclic dependencies.
We will need to spend effort to improve the build files to do so.
I can try that in a subsequent pr maybe if that is okay

___
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 86 at r7](https://reviewable.io/reviews/harness/harness-core/46216#-NTSw_OrC0AejUnFMQq4:-NTT-CuX8E4pz-dBeYMi:b-7xofrp) ([raw file](https://github.com/harness/harness-core/blob/0b5416091731c457a844566761e9c3b370581f73/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L86)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

instead of calling save from each place, can we differentiate between save and update ?
For eg.
obtainChildren -> saveStageExecutionData
handleChildResponse -> updateStageExecutionData
</blockquote></details>

This can only be done if we could create a singular service layer for this


<!-- Sent from Reviewable.io -->

2023-04-20 13:03 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: 12 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/46216#-NTSw7Ko3zcz8ZBjKGrf:-NTTkmwJ948Wiwq8-vl5:bb6un1j) (no related file):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

I had tried that but they were causing cyclic dependencies.
We will need to spend effort to improve the build files to do so.
I can try that in a subsequent pr maybe if that is okay

</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2023-04-20 13:03 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: 12 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 135 at r7](https://reviewable.io/reviews/harness/harness-core/46216#gh-1172192047:-NTTkp-nEUG5d4-c1y0U:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0b5416091731c457a844566761e9c3b370581f73/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L135)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

At this moment I don't want to move Outcomes beans to StageExecutionInfoService.
As they were causing cyclic dependencies.
We will need to spend effort to improve the build files to do so.
I can try that in a subsequent pr maybe

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-20 20:39 UTC, abhinavmittal-harness commented
trigger feature-build

2023-04-21 05:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java
> +  @Inject StageExecutionInfoService stageExecutionInfoService;
nit: can be private

2023-04-21 05:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java
> +    ServiceExecutionSummaryDetails.ArtifactsSummary.ArtifactsSummaryBuilder artifactsSummaryBuilder =
nit: directly import ArtifactsSummaryBuilder instead of fully qualified import

2023-04-21 05:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java
> +    return stageExecutionInfoRepository.findByStageExecutionId(stageExecutionId, scope);
will the scope not always be project since these come from pipelines ?

2023-04-21 05:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java
> +        .stageStatus(stepResponse.getStatus().equals(Status.SUCCEEDED) ? StageStatus.SUCCEEDED : StageStatus.FAILED)
constants should be on the left side of the comparison 

Status.SUCCEEDED.equals(stepResponse.getStatus())

2023-04-21 05:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java
> +      return currentLevel;
same comment as above

2023-04-21 09:18 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: 14 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 125 at r9](https://reviewable.io/reviews/harness/harness-core/46216#gh-1173312617:-NTY4zgU8WSQJsP6pv2X:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b6d74d8adc240743886615743fa4c081b8c9b959/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L125)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: can be private
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 141 at r9](https://reviewable.io/reviews/harness/harness-core/46216#gh-1173313401:-NTY5073B3dyg962wOO0:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b6d74d8adc240743886615743fa4c081b8c9b959/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L141)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: directly import ArtifactsSummaryBuilder instead of fully qualified import
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java` line 163 at r9](https://reviewable.io/reviews/harness/harness-core/46216#gh-1173315851:-NTY4p481JW1C4JEMOJk:bbv3er4) ([raw file](https://github.com/harness/harness-core/blob/b6d74d8adc240743886615743fa4c081b8c9b959/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java#L163)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

will the scope not always be project since these come from pipelines ?
</blockquote></details>

This is not Scope like Project org or account rather a class that stores identifiers.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 88 at r9](https://reviewable.io/reviews/harness/harness-core/46216#gh-1173317064:-NTY51yR16Fy4LyJejKH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6d74d8adc240743886615743fa4c081b8c9b959/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L88)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

constants should be on the left side of the comparison 

Status.SUCCEEDED.equals(stepResponse.getStatus())
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java` line 96 at r9](https://reviewable.io/reviews/harness/harness-core/46216#gh-1173317211:-NTY52OGAfkFuUNPk-fO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6d74d8adc240743886615743fa4c081b8c9b959/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java#L96)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-21 09:20 UTC, abhinavmittal-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/DeploymentStageStep.java
> +      return currentLevel;
Done

2023-04-21 09:25 UTC, yogesh-chauhan approved these changes
> Reviewed 5 of 37 files at r1, 5 of 21 files at r2, 4 of 4 files at r6, 6 of 8 files at r8, 2 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-21 09:52 UTC, abhinavmittal-harness commented
trigger messagecheck

2023-04-21 10:17 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/StageExecutionInfo.java` line 110 at r12](https://reviewable.io/reviews/harness/harness-core/46216#-NTYJGlf8buTs3lpyfFF:-NTYJGlf8buTs3lpyfFG:b-bhtr7x) ([raw file](https://github.com/harness/harness-core/blob/660a0602599133e5d5050b6e6285b9a9916ea5a3/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/StageExecutionInfo.java#L110)):*
> ```Java
>                  .build())
>         .add(CompoundMongoIndex.builder()
>                  .name("unique_stage_execution_info_using_stage_execution_id_idx")
> ```

nit: Remove unique


<!-- Sent from Reviewable.io -->

2023-04-21 10:20 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStep.java` line 77 at r12](https://reviewable.io/reviews/harness/harness-core/46216#-NTYJwP3CP60L4itVI9Y:-NTYJwP3CP60L4itVI9Z:b-nlcgvf) ([raw file](https://github.com/harness/harness-core/blob/660a0602599133e5d5050b6e6285b9a9916ea5a3/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStep.java#L77)):*
> ```Java
>   @Inject private EngineExpressionService engineExpressionService;
>   @Inject NgExpressionHelper ngExpressionHelper;
>   @Inject private OutcomeService outcomeService;
> ```

nit: please remove if unused.


<!-- Sent from Reviewable.io -->

2023-04-21 10:21 UTC, sahilhindwani-harness approved these changes
> Reviewed 4 of 37 files at r1, 45 of 45 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46216)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-21 10:23 UTC, abhinavmittal-harness commented
trigger messagecheck

2023-04-21 10:24 UTC, abhinavmittal-harness commented
trigger review

2023-04-21 10:26 UTC, abhinavmittal-harness commented
trigger messagecheck

2023-04-21 14:34 UTC, abhinavmittal-harness commented
trigger ti9

2023-04-21 14:34 UTC, abhinavmittal-harness commented
trigger review

2023-04-21 14:34 UTC, abhinavmittal-harness commented
trigger ut0

2023-04-21 15:45 UTC, merged