Plg 2121 support ci aws listing
harness/harness-core pull request #46253
Opened 2023-04-07 19:56 UTC by mtran7

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-07 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=46253) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=46253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=46253) it.</sub>

2023-04-07 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=46253) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=46253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=46253) it.</sub>

2023-04-10 22:18 UTC, hitesharinga approved these changes
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253)* status: 11 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-10 22:47 UTC, neelam-harness requested changes

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +  private static String PREMIER = "PRMR";
Nit: please make this `final` unless it's expected to change somewhere else.

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +    log.info("accountId:{}", accountId);
Nit: we can log out all the variables in one log statement for better readability, `log.info("accountId:{}  orderQuantity:{}  expirationTime:{}", accountId, orderQuantity, expirationTime);`

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      adminLicenseHttpClient.createAccountLicense(accountId,
Since we make the same call to `adminLicenseHttpClient.createAccountLicense(accountId, <SpecificModule>LicenseDTO)` we can build the moduleLicenseDTO in the conditionals and then just make this call once in the end. Something as follows:
`ModuleLicenseDTO moduleLicenseDTO = null;`
```
else if (marketPlaceConfig.getAwsMarketPlaceCdProductCode().equals(productCode)) {
  moduleLicense = CDModuleLicenseDTO.builder()
              .serviceInstances(orderQuantity)
              .accountIdentifier(accountId)
              .moduleType(ModuleType.CD)
              .edition(plan)
              .licenseType(licenseType)
              .premiumSupport(premiumSupport)
              .status(LicenseStatus.ACTIVE)
              .startTime(DateTime.now().getMillis())
              .expiryTime(expirationTime)
              .build());
} else if (marketPlaceConfig.getAwsMarketPlaceCcmProductCode().equals(productCode)) {
  moduleLicenseDTO = CEModuleLicenseDTO.builder()
              .spendLimit(spendLimit)
              .accountIdentifier(accountId)
              .moduleType(ModuleType.CE)
              .edition(plan)
              .licenseType(licenseType)
              .premiumSupport(premiumSupport)
              .status(LicenseStatus.ACTIVE)
              .startTime(DateTime.now().getMillis())
              .expiryTime(expirationTime)
              .build());
} else {
 ....
} 
adminLicenseHttpClient.createAccountLicense(accountId, moduleLicenseDTO);
```

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      if (result[2].equals(PREMIER)) {
Nit: we should compare the variable against a constant `PREMIER.equals(result[2])` I think to avoid NPE. https://stackoverflow.com/questions/10911068/is-constant-equalsvariable-faster-than-variable-equalsconstant

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +  public boolean getPremierSupport(String dimension) {
Nit: since it's a boolean value, we can rename it to `hasPremierSupport` to signify that.

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
> +    log.info("dimension:{}", dimension);
Nit: Same as before. Let's use one log statement to log it all to reduce the size of the method.

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
> +      adminLicenseHttpClient.createAccountLicense(accountId,
same comment as in the other file for this same code.

2023-04-10 22:47 UTC, neelam-harness commented on 400-rest/src/test/java/software/wings/licensing/LicenseServiceImplTest.java
> +    assertThat(licenseService.getPremierSupport(dimension1)).isEqualTo(true);
there are `assertTrue()` and `assertFalse()` methods in Junit framework, so `assertTrue(licenseService.hasPremierSupport(dimension1))` should suffice. Please check this for reference
https://github.com/harness/harness-core/blob/c3fe7d8108a9111c320d70fdb5f5bb3ec3b7903c/400-rest/src/test/java/software/wings/sm/states/CollectRemainingInstancesStateTest.java#L122

2023-04-11 00:51 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      adminLicenseHttpClient.createAccountLicense(accountId,
Would prefer to refactor/make more concise later. We need to see if it works for FF before we extend to the rest.

2023-04-11 00:54 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      if (result[2].equals(PREMIER)) {
Done

2023-04-11 01:00 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      adminLicenseHttpClient.createAccountLicense(accountId,
This is a good suggestion and can be made once we remove the first two conditions that do not use adminLicenseHttpClient. Those two will be deprecated once the new CD & CCM have been published and are working fine.

2023-04-11 01:00 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java
> +      adminLicenseHttpClient.createAccountLicense(accountId,
This is a good suggestion and can be made once we remove the first two conditions that do not use adminLicenseHttpClient. Those two will be deprecated once the new CD & CCM have been published and are working fine.

2023-04-11 03:50 UTC, mtran7 commented
trigger ut0

2023-04-13 03:28 UTC, mtran7 commented
trigger ut7

2023-04-13 18:04 UTC, hitesharinga approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-13 21:14 UTC, neelam-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks for making the changes!

> Reviewed 7 of 11 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253#-:-NSwSviF9khDO_pa9BaJ:bd86i5h)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-13 21:14 UTC, mtran7 commented
trigger review

2023-04-13 21:21 UTC, mtran7 reviewed
> Reviewed 7 of 11 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-13 21:22 UTC, mtran7 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253)* status: 3. unresolved discussions. 

___
*[`400-rest/src/test/java/software/wings/licensing/LicenseServiceImplTest.java` line 138 at r2](https://reviewable.io/reviews/harness/harness-core/46253#gh-1162147009:-NSwUoIj4e8hETqd5xS-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b315ad0b8450f04d97ac56ac7f4f65559b07e575/400-rest/src/test/java/software/wings/licensing/LicenseServiceImplTest.java#L138)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

there are `assertTrue()` and `assertFalse()` methods in Junit framework, so `assertTrue(licenseService.hasPremierSupport(dimension1))` should suffice. Please check this for reference
https://github.com/harness/harness-core/blob/c3fe7d8108a9111c320d70fdb5f5bb3ec3b7903c/400-rest/src/test/java/software/wings/sm/states/CollectRemainingInstancesStateTest.java#L122 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-13 21:30 UTC, neelam-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253#-:-NSwWe8r9W242A2mhVPh:bnfp4nl)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 677 at r2](https://reviewable.io/reviews/harness/harness-core/46253#gh-1162141225:-NSwWYtW6sl4A-T8xYdC:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/b315ad0b8450f04d97ac56ac7f4f65559b07e575/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L677)):*
<details><summary><i>Previously, mtran7 wrote…</i></summary><blockquote>

This is a good suggestion and can be made once we remove the first two conditions that do not use adminLicenseHttpClient. Those two will be deprecated once the new CD & CCM have been published and are working fine. https://harness.atlassian.net/browse/PLG-2144
</blockquote></details>

LGTM


<!-- Sent from Reviewable.io -->

2023-04-13 21:30 UTC, mtran7 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253#-:-NSwWk2N1CkcsIxzVLtJ:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-13 23:39 UTC, neelam-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253#-:-NSwzGdm-HhObf5atxx8:bnfp4nl)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-13 23:46 UTC, neelam-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46253)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-04-13 23:56 UTC, merged