[CDS-58576]: [feat]: services api change for google function gen one
harness/harness-core pull request #46276
Opened 2023-04-10 10:31 UTC by PragyeshMishra01

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-11 11:43 UTC, PragyeshMishra01 commented
trigger messagecheck

2023-04-11 11:55 UTC, PragyeshMishra01 commented
trigger ss

2023-04-11 12:19 UTC, sainath-b requested changes

2023-04-11 12:19 UTC, sainath-b commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
> +          deploymentMetadataServiceHelper.parseDeploymentMetadataYaml(type, deploymentMetaDataYaml);
Please fix issues in this filter as it will break in some corner cases.

2023-04-11 13:14 UTC, PragyeshMishra01 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
> +          deploymentMetadataServiceHelper.parseDeploymentMetadataYaml(type, deploymentMetaDataYaml);
fixed it. Can you pls review it again?

2023-04-11 13:46 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 648 at r2](https://reviewable.io/reviews/harness/harness-core/46276#gh-1162733569:-NSkZLld0YWGyIhgPLOi:b-mclmnh) ([raw file](https://github.com/harness/harness-core/blob/969883ffb43bed171ca45d75d9b2394a3ce7ca31/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L648)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

fixed it. Can you pls review it again?
</blockquote></details>

Can we take this filter as a first class object instead of yaml ?


<!-- Sent from Reviewable.io -->

2023-04-11 14:00 UTC, PragyeshMishra01 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46276)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 648 at r2](https://reviewable.io/reviews/harness/harness-core/46276#gh-1162733569:-NSk_VHQDvBY7HO7EVuG:b-77qymc) ([raw file](https://github.com/harness/harness-core/blob/969883ffb43bed171ca45d75d9b2394a3ce7ca31/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L648)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Can we take this filter as a first class object instead of yaml ?
</blockquote></details>

just confirming that do you mean to take deploymentMetadata as object in QueryParam like below or something else?
 @QueryParam("deploymentMetadata") DeploymentMetadataDto deploymentMetaData 


<!-- Sent from Reviewable.io -->

2023-04-16 16:18 UTC, PragyeshMishra01 commented
trigger feature-build

2023-04-17 03:19 UTC, sainath-b approved these changes

2023-04-17 10:01 UTC, alluvamsi-harness approved these changes

2023-04-17 10:02 UTC, alluvamsi-harness approved these changes
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46276)* status: Some of the checks are too old. 4 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-17 10:07 UTC, PragyeshMishra01 commented
trigger review

2023-04-18 08:10 UTC, merged