fix: [CDS-54689]: manager step changes
harness/harness-core pull request #46273
Opened 2023-04-10 08:18 UTC by TarunUba1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-11 12:01 UTC, abosii-harness requested changes

2023-04-11 12:01 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
> +    kryo.register(ServiceHookDelegateConfig.class, 1002131);
We need to ensure that delegate does support this. You can achieve this by by creating a new TaskType _SERVICE_HOOKS or V(n) and bind it to the same task handler

2023-04-11 12:01 UTC, abosii-harness commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_SERVICE_HOOKS_NG("Enables Service hooks feature", HarnessTeam.CDP);
Shouldn't we be more specific, like CDS_K8S_SERVICE_HOOKS_NG?

2023-04-17 06:04 UTC, TarunUba1 commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/ServiceHookDelegateConfig.java
> +  String content;
Done

2023-04-17 06:05 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingStep.java
> +    Optional<ServiceHooksOutcome> serviceHookOutcome = cdStepHelper.getServiceHooksOutcome(ambiance);
Done

2023-04-17 06:05 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java
> +    Optional<ServiceHooksOutcome> serviceHookOutcome = cdStepHelper.getServiceHooksOutcome(ambiance);
Done

2023-04-17 06:05 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryStep.java
> +    Optional<ServiceHooksOutcome> serviceHookOutcome = cdStepHelper.getServiceHooksOutcome(ambiance);
Done

2023-04-17 06:05 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +    Optional<ServiceHooksOutcome> serviceHookOutcome = cdStepHelper.getServiceHooksOutcome(ambiance);
Done

2023-04-17 06:05 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +      cdExpressionResolver.updateExpressions(ambiance, serviceHookOutcome);
Done

2023-04-17 06:05 UTC, TarunUba1 commented on 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
> +    kryo.register(ServiceHookDelegateConfig.class, 1002131);
Done

2023-04-17 06:05 UTC, TarunUba1 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_SERVICE_HOOKS_NG("Enables Service hooks feature", HarnessTeam.CDP);
Done

2023-04-17 06:18 UTC, TarunUba1 commented
trigger messagecheck

2023-04-18 08:25 UTC, abosii-harness requested changes

2023-04-18 08:25 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +    if (cdFeatureFlagHelper.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.CDS_K8S_SERVICE_HOOKS_NG)) {
We should make it based on if service hooks are present and not FF

2023-04-18 08:25 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +    return Collections.emptyList();
Maybe is better as null? Not sure how kryo will behave here, if the field is set as non-null it may still try to decode

2023-04-18 08:25 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java
> +  List<ServiceHookDelegateConfig> serviceHooks;
It does require @Expression(ALLOW_SECRETS)

2023-04-18 08:25 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  K8S_COMMAND_TASK_NG_V2(TaskGroup.K8S_NG, "K8s Task with service Hooks");
We need the same logic for Native Helm

2023-04-18 08:25 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java
> +  public List<ServiceHookDelegateConfig> getServiceHooksDelegateConfig(ServiceHooksOutcome serviceHooksOutcome) {
You can make it common by moving to K8sHelmCommonStepHelper

2023-04-18 18:37 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java
> +  public List<ServiceHookDelegateConfig> getServiceHooksDelegateConfig(ServiceHooksOutcome serviceHooksOutcome) {
Done

2023-04-18 18:37 UTC, TarunUba1 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java
> +  List<ServiceHookDelegateConfig> serviceHooks;
Done

2023-04-18 18:37 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +    return Collections.emptyList();
Done

2023-04-18 18:37 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +    if (cdFeatureFlagHelper.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.CDS_K8S_SERVICE_HOOKS_NG)) {
Done with checking FF and service Hook both exist or not

2023-04-19 06:16 UTC, abhinavsingh1196 requested changes

2023-04-19 06:16 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java
> +    serviceHooksOutcome.forEach((k, v) -> {
let's rename (k,v) to some appropriate name like (identifier, serviceHookOutcome)

2023-04-19 06:16 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java
> +    TaskType taskType;
you can assign default value as TaskType.HELM_COMMAND_TASK_NG
and get rid of the else block

2023-04-19 06:16 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
> +  @Inject private CDExpressionResolver cdExpressionResolver;
this is unused

2023-04-19 06:16 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sCanaryStep.java
> +  @Inject private CDExpressionResolver cdExpressionResolver;
unused dependency

2023-04-19 06:16 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java
> +  @Inject private CDExpressionResolver cdExpressionResolver;
unused

2023-04-19 06:16 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/ServiceHookDelegateConfig.java
> +public class ServiceHookDelegateConfig implements ExpressionReflectionUtils.NestedAnnotationResolver {
add import for NestedAnnotationResolver itself directly

2023-04-19 06:16 UTC, abhinavsingh1196 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_K8S_SERVICE_HOOKS_NG("Enables Service hooks feature", HarnessTeam.CDP);
we can describe the FF in some more detail here, with possibly a link for the epic too

2023-04-19 06:33 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java
> +    return null;
Bosi said that it might be possible that for empty list delegate might run into kryo

2023-04-19 07:55 UTC, abosii-harness requested changes

2023-04-19 07:55 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java
> +    Optional<ServiceHooksOutcome> serviceHookOutcome = cdStepHelper.getServiceHooksOutcome(ambiance);
Can we instead rely on the helmCommandRequest service hooks not null or empty instead of making an additional call to outcome service?

2023-04-19 07:55 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java
> +    Optional<ServiceHooksOutcome> serviceHookOutcome = cdStepHelper.getServiceHooksOutcome(ambiance);
Same here, let's use k8sDeployRequest

2023-04-19 07:55 UTC, abhinavsingh1196 requested changes

2023-04-19 07:55 UTC, abhinavsingh1196 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_K8S_SERVICE_HOOKS_NG("Enables Service hooks support for K8s/Natuve Helm Services", HarnessTeam.CDP);
typo in "Native" :)

2023-04-19 11:00 UTC, abhinavsingh1196 approved these changes

2023-04-19 11:04 UTC, abosii-harness approved these changes

2023-04-19 11:05 UTC, TarunUba1 commented
trigger review

2023-04-19 11:10 UTC, merged