Cds 54796 delegate side changes fetch
harness/harness-core pull request #46298
Opened 2023-04-10 17:04 UTC by TarunUba1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-17 06:28 UTC, TarunUba1 commented
trigger messagecheck

2023-04-18 08:18 UTC, abosii-harness requested changes

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +  public void addContext(String key, String value) {
You can have some enums or const values and add the MANIFEST_FILES_DIRECTORY, MANIFEST_FILE_OUTPUT_PATH, etc. before you run execute
You can even improve this logic by providing multiple methods, like:
public void addContext(String key, String value)
public void addContext(String key, List<String> value)

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +    return;
Avoid unnecessary return statements

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +      return processExecutor.execute();
Add handle for process result output code is not 0, it should throw an error

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +        .timeout(5, TimeUnit.MINUTES)
Set it as constant

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +        .timeout(5, TimeUnit.MINUTES)
It's better to use timeout from task parameters, you can create it when create this hook handler service

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +        .readOutput(true);
Let's stream output/error output of the hook to the execution logs

2023-04-18 08:18 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sApplyRequest.java
> +  List<ServiceHookDelegateConfig> serviceHooks;
Add before method

2023-04-18 08:18 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/k8s/model/ServiceHookAction.java
> +public enum ServiceHookAction {
Please add owner CDP

2023-04-18 08:18 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/k8s/model/ServiceHookType.java
> +public enum ServiceHookType {
Please add owner CDP

2023-04-18 08:18 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
> +    kryo.register(ServiceHookDelegateConfig.class, 1002131);
Please add it to the end and increase it by 1

2023-04-18 08:18 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/ServiceHookDelegateConfig.java
> +public class ServiceHookDelegateConfig {
Please add owner CDP

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +      logCallback.saveExecutionLog(format("Starting %s ", type.getName()));
Let's make it bold and add \n before Starting. As well, mention that you're Starting %s hook

2023-04-18 08:18 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +      logCallback.saveExecutionLog(format("Hook output %s", processResult.getOutput().getUTF8()));
Once we will stream output to execution logs this shouldn't be required, you can mention that Hook completed successfully (and add \n at the end)

2023-04-20 16:05 UTC, abhinavsingh1196 requested changes

2023-04-20 16:05 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        k8sDelegateTaskParams.getWorkingDirectory(), executionLogCallback, manifestFilesDirectory);
after post hook, are we closing the `Fetch Files` log callback?

2023-04-20 16:05 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/k8s/model/ServiceHookContext.java
> +   */
we don't really need these docs!

2023-04-20 16:07 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        k8sDelegateTaskParams.getWorkingDirectory(), executionLogCallback, manifestFilesDirectory);
yes, i opened from different places to accomodate the logs in fetch files itself. then closing it later

2023-04-24 06:30 UTC, abhinavsingh1196 requested changes

2023-04-24 06:30 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +    String finalList = String.join(",", value);
nit: rename to commaSeparatedValues

2023-04-24 06:30 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +        e.printStackTrace();
we should remove this statement `e.printStackTrace();` since we're logging the error

2023-04-24 06:30 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +        log.error("Unable to delete hook directory", e.toString());
there is no need to do `e.toString()` ?

2023-04-25 06:45 UTC, abosii-harness requested changes

2023-04-25 06:45 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> -      executionLogCallback.saveExecutionLog("Done.", INFO, SUCCESS);
Instead of removing this can we have it configurable? Like adding a new parameter to method boolean denoteOverallSuccess and having 2 methods:
previousOne(...) => by default will send true to new method
newMethod(..., boolean denoteOverallSuccess)
And set the value false only if we use service hooks, this way we will avoid any issues

2023-04-25 06:45 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +    context.put(GOOGLE_APPLICATION_CREDENTIALS.getContextName(),
We need KUBECONFIG env variable as well

2023-04-25 06:45 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +  @SuppressWarnings("checkstyle:UnnecessaryParentheses")
nit: add an empty space

2023-04-25 06:45 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +    String envPath = envPathsSet.stream()
Let's move this to a method

2023-04-25 06:45 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +      Thread.currentThread().interrupt();
Instead of doing this, let's rethrow interrupted exception

2023-04-25 06:45 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +  public void execute(
Let's have this method to throw InterruptedException at least

2023-04-25 06:45 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/ServiceHookTaskParams.java
> +public class ServiceHookTaskParams {
Let's rename this to ServiceHookDTO or something more meaningful, it's not a task params

2023-04-25 06:45 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/ServiceHookTaskParams.java
> +public class ServiceHookTaskParams {
Add owner

2023-04-26 08:11 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +        color(String.format("\nExecuting %s for Action: %s \n", type.getName(), action.getActionName()), LogColor.White,
nit: follow the code static analysis suggestion. And let's add a log line when everythings is completed

2023-04-26 08:14 UTC, abosii-harness requested changes

2023-04-27 10:01 UTC, abosii-harness approved these changes

2023-04-27 11:10 UTC, achyuth-harness approved these changes

2023-04-27 11:11 UTC, TarunUba1 commented
trigger review

2023-04-27 11:16 UTC, GoelPratyush99 approved these changes
> Reviewed 8 of 22 files at r3, 3 of 10 files at r4, 1 of 3 files at r5, 9 of 12 files at r6, 3 of 3 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46298)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-27 11:16 UTC, abhinavsingh1196 approved these changes

2023-04-27 11:16 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +      throw e;
this is not needed? we're just catching and throwing it as it is anyway.
Let's change this with another PR.

2023-04-27 11:16 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/utils/ServiceHookDTO.java
> +    kubectlPath = null;
These will be null by default even if you don't initialize as null

2023-04-27 11:17 UTC, merged