feat: [CDS-56655]: added support for Github config files in ssh/Winrm
harness/harness-core pull request #46512
Opened 2023-04-18 10:25 UTC by vitsafronovici

## Describe your changes
added support for Github config files in ssh/Winrm

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-18 11:06 UTC, vitsafronovici commented
trigger ut1

2023-04-18 14:08 UTC, acasian-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/GitFetchedStoreDelegateConfig.java
> +public class GitFetchedStoreDelegateConfig implements StoreDelegateConfig, NestedAnnotationResolver {
`GitStoreDelegateConfig` type is also `GIT` - it might cause class cast exception. Are we checking in the code instance type?

2023-04-18 16:37 UTC, vitsafronovici commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/GitFetchedStoreDelegateConfig.java
> +public class GitFetchedStoreDelegateConfig implements StoreDelegateConfig, NestedAnnotationResolver {
we can have cast exception if we prepare wrong the config delegate file which is not the case, only if someone on purpose will change the code and construct a wrong instance. But if so, how to handle the wrong instance on delegate which is not the case to be there?

2023-04-19 07:15 UTC, acasian-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/GitFetchedStoreDelegateConfig.java
> +public class GitFetchedStoreDelegateConfig implements StoreDelegateConfig, NestedAnnotationResolver {
checking `instanceof` only, but i don't think it is worth it. Can we check where the git types are used - is it used by type only?

2023-04-19 07:20 UTC, acasian-harness commented
@vitsafronovici please update pr description with yaml part for git config. Also mention the use cases that are applicable, test plan & spec link.

2023-04-19 08:11 UTC, ivan-83 requested changes
Overall looks good to me with minor comments. 

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46512#-:-NTNYTnu5n9Qkb_4hMom:b-nok91z)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmConfigFileHelper.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/46512#-NTNV25_6CYESIzf4wLv:-NTNV25cA_Dps2GBgr9Y:b-3w030e) ([raw file](https://github.com/harness/harness-core/blob/1729c1355645e2191a43287a86e5cda6c848a1ac/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmConfigFileHelper.java#L101)):*
> ```Java
>             stores.add(buildGitFetchedStoreDelegateConfig(ambiance, configFileOutcome));
>             break;
>           default: // do nothing
> ```

Minor - stores.add(Collection.emptyList()) because it returns the type-safe immutable list. 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/GitFetchedStoreDelegateConfig.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/46512#gh-1170098924:-NTNW0K58EoEahlWhkY2:b-jgkwg1) ([raw file](https://github.com/harness/harness-core/blob/1729c1355645e2191a43287a86e5cda6c848a1ac/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/GitFetchedStoreDelegateConfig.java#L27)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

checking `instanceof` only, but i don't think it is worth it. Can we check where the git types are used - is it used by type only?
</blockquote></details>

I agree with both of you, we rely on developers to take care of this, doing appropriate casting on delegates or any other place based on sent class. However, because of simplicity and clarity and could be a case that two senders send the same GIT type with different classes and we will get an exception in the handler class, we should have the new type like GIT_FETCHED or GitFetchedStoreDelegateConfig should extend GitStoreDelegateConfig and use getType()  method from the parent class.


<!-- Sent from Reviewable.io -->

2023-04-19 12:21 UTC, acasian-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmConfigFileHelper.java
> +          default: // do nothing
we should throw the unsupported exception for ones that we are not supporting

2023-04-19 12:22 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46512#-:-NTOShjRDmBQnBTokss8:bnfp4nl)* status: 11 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-19 21:17 UTC, ivan-83 approved these changes
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46512)* status: 12 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmConfigFileHelper.java` line 103 at r5](https://reviewable.io/reviews/harness/harness-core/46512#-NTQN-900yuehAmcjbvf:-NTQN-900yuehAmcjbvg:b-6tpl3f) ([raw file](https://github.com/harness/harness-core/blob/5a9c40629b28653ba3d2365f6ab92f2fdaf93ca9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmConfigFileHelper.java#L103)):*
> ```Java
>           default:
>             throw new UnsupportedOperationException(
>                 format("Ssh/WinRm deployment does not support this storeConfig kind `%s`", storeConfig.getKind()));
> ```

Minor - Ssh/WinRm deployment does not support this storeConfig kind >>Ssh/WinRm deployment does not support storeConfig kind
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/exception/SshExceptionConstants.java` line 114 at r5](https://reviewable.io/reviews/harness/harness-core/46512#-NTQMkA58XjE5ofTDiIL:-NTQMkA58XjE5ofTDiIM:byl2ria) ([raw file](https://github.com/harness/harness-core/blob/5a9c40629b28653ba3d2365f6ab92f2fdaf93ca9/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/exception/SshExceptionConstants.java#L114)):*
> ```Java
>   public final String SSH_INVALID_CREDENTIALS_EXPLANATION = "Provided %s credentials are not authorized.";
> 
>   public final String INVALID_STORE_DELEGATE_CONFIG_TYPE_FAILED = "Invalid store type for config provided";
> ```

Minor - "Invalid store type for config provided" >> "Invalid store type for config files provided"


<!-- Sent from Reviewable.io -->

2023-04-20 09:34 UTC, acasian-harness approved these changes

2023-04-20 09:56 UTC, vitsafronovici commented
trigger review

2023-04-20 09:57 UTC, merged