fix: [PL-32460]: fix for better error msg while creating a secret
harness/harness-core pull request #46580
Opened 2023-04-19 08:50 UTC by bhavya181

## Describe your changes
if we create a secret using secret manager whose delegates are not available, then we were not showing correct error msg.

So, encrytion of secret through secretManager throws DelegateServiceDriverException in such cases and as its not an instance of wingsException, our response method does not able to parse it. Catch this exception and throw correct exception.
Same issue can happen while updating secret, so, changes has been done for that as well

Tested locally, by creating secret through secret manager whose delegates are not available. 
You can check error msg and api response in this ss - 
<img width="1679" alt="Screenshot 2023-04-19 at 1 56 32 PM" src="https://user-images.githubusercontent.com/85869295/233021849-81a59729-9222-4ae3-adcc-373686069e6c.png">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-19 11:33 UTC, nishantsaini20 requested changes

2023-04-19 11:33 UTC, nishantsaini20 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +                                  .updateSecret(encryptedData.getAccountIdentifier(),
Why `renameSecret` call is replaced with `updateSecret`?

2023-04-19 12:53 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46580)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 360 at r1](https://reviewable.io/reviews/harness/harness-core/46580#gh-1171208131:-NTOZjZa8cC8k7ioQgo6:b3calnm) ([raw file](https://github.com/harness/harness-core/blob/377c45e830bc1c2ecd1ef26cc660495ffaa597d7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L360)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why `renameSecret` call is replaced with `updateSecret`?
</blockquote></details>

I have not removed it, its just that this github reviewable showing it like this. I have just ut whole logic under try catch, nothing else


<!-- Sent from Reviewable.io -->

2023-04-19 13:32 UTC, nishantsaini20 approved these changes

2023-04-19 15:03 UTC, bhavya181 commented
trigger messagecheck

2023-04-19 20:55 UTC, abhinav-harness approved these changes

2023-04-20 09:10 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46580#-:-NTSvW-g0XJPUGyyNEvB:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-20 09:11 UTC, merged