feat: [PLG-2080]: credit expiry iterator
harness/harness-core pull request #46715
Opened 2023-04-20 20:35 UTC by Xin-Harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-01 20:52 UTC, thomas-grasman requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46715)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/46715#-NUO0tIjC23gzPTp_UA4:-NUO0tIjC23gzPTp_UA5:b-jskig7) ([raw file](https://github.com/harness/harness-core/blob/f77b6f27bcb10273d1b19ee14638a939684e796f/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L55)):*
> ```Java
> 
>   @Override
>   public void checkForCreditExpiry(Credit entity) {
> ```

This should be called **setCreditStatusExpired(Credit entity)** since there is no check being performed.


<!-- Sent from Reviewable.io -->

2023-05-01 22:24 UTC, mtran7 commented on 930-ng-license-manager/src/main/java/io/harness/credit/entities/CICredit.java
> +    throw new IllegalArgumentException("Invalid fieldName " + fieldName);
do you also want to capture telemetry events? See `sendSucceedTelemetryEvent` and `sendFailedTelemetryEvent` in harness-core/920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java

2023-05-01 22:25 UTC, mtran7 commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java
> +            .targetInterval(ofSeconds(31))
can define 31 above with variable so it is not a magic number

2023-05-01 22:27 UTC, mtran7 commented on 960-ng-license-beans/src/main/java/io/harness/credit/beans/credits/CreditDTO.java
> +public class CreditDTO {
For personal learning, what's the reason for removing abstract?

2023-05-01 22:27 UTC, mtran7 approved these changes

2023-05-01 22:33 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/entities/CICredit.java
> +  public Long obtainNextIteration(String fieldName) {
Nit: we can just name it as `nextIteration`

2023-05-01 22:57 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java
> +  public void checkForCreditExpiry(Credit entity) {
this method is named to `checkForCreditExpiry` but is actually saving the status as Expired. Le't re-name it to `updateCreditStatus`

2023-05-01 22:57 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/entities/CICredit.java
> +    throw new IllegalArgumentException("Invalid fieldName " + fieldName);
Good point. Let's add the telemetry wherever applicable for successful and failed events, will be very helpful in tracking. Thanks

2023-05-01 22:57 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java
> + * @author rktummala
Nit: this might have to be changed to your username. 
also, the java doc can be a bit more detailed in terms of how we define the license expiry.

2023-05-01 22:57 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java
> +      creditService.checkForCreditExpiry(entity);
Telemetry here for the successful event of saving the CreditStatus

2023-05-02 11:53 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46715)* status: 7 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/entities/CICredit.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/46715#gh-1181940777:-NURGd4l-Rj6NfDWlYNG:b-5ooh71) ([raw file](https://github.com/harness/harness-core/blob/f77b6f27bcb10273d1b19ee14638a939684e796f/930-ng-license-manager/src/main/java/io/harness/credit/entities/CICredit.java#L34)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Nit: we can just name it as `nextIteration`
</blockquote></details>

@neelam-harness this method comes from the parent and its fine this way.



_Code snippet:_
```Java
PersistentIterable
```
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/46715#-NURHI2w7abb3wXVpT0z:-NURHI2w7abb3wXVpT1-:bgr0wpe) ([raw file](https://github.com/harness/harness-core/blob/f77b6f27bcb10273d1b19ee14638a939684e796f/930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java#L40)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.GTM)
> public class CreditExpiryIteratorHandler implements Handler<CICredit> {
> ```

this should be like "public class CreditExpiryIteratorHandler implements Handler<Credit>"
we should make the iterator more general because we would not add more iterators when more credit types are added e.g. SRMCredit


<!-- Sent from Reviewable.io -->

2023-05-02 13:43 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/entities/CICredit.java
> +    throw new IllegalArgumentException("Invalid fieldName " + fieldName);
I hold a different opinion, we should not use telemetry in background job, like mongo iterators which works on the low backend to change mongo records, however telemetry is mainly use to collect customer data and understand customer behaviours etc. It is open for further discussion.
Here is the definition of Telemetry: 
Telemetry automatically collects, transmits and measures data from remote sources, using sensors and other devices to collect data. It uses communication systems to transmit the data back to a central location. Subsequently, the data is analyzed to monitor and control the remote system.

Telemetry data helps improve customer experiences and monitor security, application health, quality and performance.

2023-05-02 13:44 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/entities/CICredit.java
> +  public Long obtainNextIteration(String fieldName) {
This is an inherited method from PersistentIterable, hence can't rename it.

2023-05-02 13:44 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java
> +  public void checkForCreditExpiry(Credit entity) {
Will change the method name to setCreditStatusExpired

2023-05-02 15:26 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46715)* status: 7 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/46715#-NURHI2w7abb3wXVpT0z:-NUS3BIE8WI0tJZ9a7xb:b-37xylb) ([raw file](https://github.com/harness/harness-core/blob/f77b6f27bcb10273d1b19ee14638a939684e796f/930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java#L40)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

this should be like "public class CreditExpiryIteratorHandler implements Handler<Credit>"
we should make the iterator more general because we would not add more iterators when more credit types are added e.g. SRMCredit
</blockquote></details>

I have checked with PM and confirmed that we are not near to support other credits. For this PR, lets make it for CI credit expiry works, as for the other credits. After the discuss with the team, we can create a separate PR for deal with generic issue.


<!-- Sent from Reviewable.io -->

2023-05-02 15:57 UTC, thomas-grasman reviewed
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46715)* status: 7 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-02 19:05 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46715)* status: 7 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/46715#-NURHI2w7abb3wXVpT0z:-NUSqYRU-ZJ9t37y5mag:b-sot802) ([raw file](https://github.com/harness/harness-core/blob/f77b6f27bcb10273d1b19ee14638a939684e796f/930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditExpiryIteratorHandler.java#L40)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

I have checked with PM and confirmed that we are not near to support other credits. For this PR, lets make it for CI credit expiry works, as for the other credits. After the discuss with the team, we can create a separate PR for deal with generic issue.
</blockquote></details>

approving with caveat that we will make it generic in future


<!-- Sent from Reviewable.io -->

2023-05-02 20:04 UTC, mtran7 approved these changes
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46715)* status: 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-02 20:04 UTC, mtran7 approved these changes

2023-05-02 20:04 UTC, neelam-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46715#-:-NUT3Kk53p5K7JAYYWuR:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-05-02 20:06 UTC, merged