feat: [CDS-59012]: Add Delegate Selection Logs in Service Infra Step
harness/harness-core pull request #46773
Opened 2023-04-21 10:13 UTC by alluvamsi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-21 14:18 UTC, yogesh-chauhan requested changes

2023-04-21 14:18 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +  private static final String ARTIFACT_TASK = "ARTIFACT_TASK";
lets rename this to something more meaningful like StepDetailKey etc

2023-04-21 14:18 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +  private static final String CONFIG_FILES_TASK = "CONFIG_FILES_TASK";
lets rename this to something more meaningful like StepDetailKey etc

2023-04-21 14:18 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +  public static final String TASK_IDS = "Task IDs";
lets rename this to something more meaningful like StepDetailTaskIdKey etc

2023-04-21 14:18 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java
>                                                 .build();
lets rename this to something more meaningful like StepDetailKey etc

2023-04-21 14:18 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/InfraStepV2DetailsInfo.java
> +public class InfraStepV2DetailsInfo implements StepDetailsInfo {
Lets jusgt call this InfrastructureStepDetails ( get rid of v2 etc )

2023-04-21 14:18 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceStepV3DetailsInfo.java
> +public class ServiceStepV3DetailsInfo implements StepDetailsInfo {
Lets jusgt call this ServiceStepDetails ( get rid of v3 etc )

2023-04-24 10:25 UTC, alluvamsi-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +  private static final String ARTIFACT_TASK = "ARTIFACT_TASK";
Done

2023-04-24 10:25 UTC, alluvamsi-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +  private static final String CONFIG_FILES_TASK = "CONFIG_FILES_TASK";
Done

2023-04-24 10:25 UTC, alluvamsi-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +  public static final String TASK_IDS = "Task IDs";
removed it, as its not required

2023-04-24 10:26 UTC, alluvamsi-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java
>                                                 .build();
Done

2023-04-24 10:32 UTC, alluvamsi-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceStepV3DetailsInfo.java
> +public class ServiceStepV3DetailsInfo implements StepDetailsInfo {
Done

2023-04-24 10:32 UTC, alluvamsi-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/InfraStepV2DetailsInfo.java
> +public class InfraStepV2DetailsInfo implements StepDetailsInfo {
Dobne

2023-04-24 12:19 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 4 files at r2, 5 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46773)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-24 14:15 UTC, alluvamsi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46773)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1061 at r4](https://reviewable.io/reviews/harness/harness-core/46773#-NTnBdxT5Fd3fKhUwjVL:-NTnbiJKEcE02qGLw_XO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/43c63e249f9c9e2f0af2d3e5a7eedb7dd96c4da2/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1061)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to keep this logic in ServiceStepHelper instead of CDStepHelper. this is not a generic CD utility.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-24 14:50 UTC, yogesh-chauhan approved these changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46773)* status: 9 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-25 03:42 UTC, sainath-b approved these changes

2023-04-25 07:38 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46773)* status: 9 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-25 09:16 UTC, alluvamsi-harness commented
trigger ng_manager

2023-04-25 11:01 UTC, sainath-b approved these changes

2023-04-25 11:11 UTC, alluvamsi-harness commented
trigger review

2023-04-25 11:13 UTC, merged