feat: [CDS-59360]: approvals: prevented log stream to close in case of polling errors
harness/harness-core pull request #46831
Opened 2023-04-24 05:00 UTC by naman-goenka

## Describe your changes
- when an error like connector is invalid etc occurs during approval polling, the log stream is getting closed.
- for subsequent polling event, continuous stream of log errors is seen due to this.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-24 07:16 UTC, naman-goenka commented
trigger messagecheck

2023-04-24 08:23 UTC, puthrayaharness requested changes

2023-04-24 08:23 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/approval/AbstractApprovalCallback.java
> +        LogHelper.color(errorMessage, LogColor.Red), LogLevel.ERROR, CommandExecutionStatus.FAILURE);
Do not send the finalize status. Let the step take care of closing the log stream

2023-04-24 08:23 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/approval/servicenow/ServiceNowApprovalCallback.java
> +        LogHelper.color(errorMessage, LogColor.Red), LogLevel.ERROR, CommandExecutionStatus.FAILURE);
Do not send finalize status. Let the step take care of closing the stream

2023-04-24 08:38 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/AbstractApprovalCallback.java
> +        LogHelper.color(errorMessage, LogColor.Red), LogLevel.ERROR, CommandExecutionStatus.FAILURE);
to confirm in `handleAsyncResponseInternal` method in step, closing will be handled.

2023-04-26 08:12 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/servicenow/ServiceNowApprovalCallback.java
> +        LogHelper.color(errorMessage, LogColor.Red), LogLevel.ERROR, CommandExecutionStatus.FAILURE);
done

2023-04-26 15:42 UTC, puthrayaharness submitted a review, later dismissed

2023-04-27 08:13 UTC, abhinavmittal-harness approved these changes
> Reviewed 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46831)* status: 9 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-27 09:46 UTC, naman-goenka commented
trigger review

2023-04-27 09:50 UTC, Y0709 approved these changes

2023-04-27 09:51 UTC, naman-goenka commented
trigger review

2023-04-27 09:55 UTC, naman-goenka commented
trigger review

2023-04-27 09:56 UTC, merged

2023-04-27 09:57 UTC, shivamnegi94 approved these changes