fix: [PL-31963]: Added validation for inputs in custom secret manager
harness/harness-core pull request #46878
Opened 2023-04-24 12:18 UTC by VikasMaddukuriHarness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-05 08:42 UTC, meenakshi-harness requested changes

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +  private void testCustomSecretManagerInputs(ConnectorConfigDTO connectorConfigDTO, String accountIdentifier,
rename to validateCustomSecretManagerInputs

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +      log.error("error reading template yaml");
Add more context to log

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +      //      connectorConfigDTO).getTemplate().getTemplateInputs();
Remove commented code

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +                                                        .get("environmentVariables");
move `environmentVariables` to constant

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +          log.error("Duplicate input.");
Add more context to log

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +          throw new InvalidRequestException("Duplicate input.");
Add more context to exception thrown

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +          // validate this key value is present in the incoming connector inputs
Did not understand this logic. 

Also lets divide this method in separate methods. Right now its difficult to understand.

2023-06-05 08:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +  private String templateIdFromRef(String templateRef) {
Please add UTs for all new methods

2023-06-10 12:30 UTC, VikasMaddukuriHarness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +  private String templateIdFromRef(String templateRef) {
done

2023-06-10 12:30 UTC, VikasMaddukuriHarness commented
trigger uts

2023-06-12 03:27 UTC, VikasMaddukuriHarness commented
trigger messagecheck

2023-06-12 03:30 UTC, VikasMaddukuriHarness commented
trigger messagecheck

2023-06-12 15:21 UTC, meenakshi-harness submitted a review, later dismissed

2023-06-12 15:31 UTC, VikasMaddukuriHarness commented on 120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java
> +      log.error("error reading templateInputs from template YAML which is used in this Custom Secret Manager");
done

2023-06-12 15:33 UTC, VikasMaddukuriHarness commented
trigger uts

2023-06-12 15:42 UTC, VikasMaddukuriHarness commented
trigger uts

2023-06-12 15:47 UTC, meenakshi-harness approved these changes

2023-06-12 16:05 UTC, merged