[feat]: [PIE-9287]: Notes for particular PlanExecution
harness/harness-core pull request #46872
Opened 2023-04-24 11:31 UTC by senjucanon2

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-25 06:32 UTC, archit-harness reviewed
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr56UB8Nk2Y2nlTRgz:-NTr56UC6MYN4goTICOb:bhthbb2) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java#L32)):*
> ```Java
>       "This param provides an option to run only the failed stages when Pipeline fails at parallel group. By default, it will run all the stages in the failed parallel group.";
> 
>   String NOTES_FOR_PLAN_EXECUTION_PARAM_MESSAGE = "Notes of an execution for a planExecution";
> ```

Notes of a pipeline execution
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr6BX92A-qpwXubzfC:-NTr6BX92A-qpwXubzfD:bh67ssd) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java#L31)):*
> ```Java
>   void deleteMetadataForGivenPlanExecutionIds(Set<String> planExecutionIds);
> 
>   PlanExecutionMetadata updateExecutionNotes(Criteria criteria, Update update);
> ```

criteria should be created inside service layer, and should be passed to repository layer 
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr6JA34XmxRYbrBKqw:-NTr6JA34XmxRYbrBKqx:b-xj9kdu) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L33)):*
> ```Java
> public class PlanExecutionMetadataServiceImpl implements PlanExecutionMetadataService {
>   private final PlanExecutionMetadataRepository planExecutionMetadataRepository;
>   private final MongoTemplate mongoTemplate;
> ```

dont use mongoTemplate and call repository
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5QO400agqA9gjCem:-NTr5QO400agqA9gjCen:b-57mlfu) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java#L26)):*
> ```Java
> @JsonInclude(JsonInclude.Include.NON_NULL)
> @ApiModel("PipelineExecutionNotes")
> @Schema(name = "PipelineExecutionNotes", description = "Notes for a particular PipelineExecution")
> ```

same use constant which you created



_Code quote:_
```Java
Notes for a particular PipelineExecution
```
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5K_14cuqSuSfgtX7:-NTr5K_14cuqSuSfgtX8:b1aedl) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java#L29)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class PipelineExecutionNotesDTO {
>   @Schema(description = "The plan ExecutionID") String executionId;
> ```

The Pipeline ExecutionId
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5O-hEEfMbqUT_kzt:-NTr5O-hEEfMbqUT_kzu:b-621w8x) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java#L30)):*
> ```Java
> public class PipelineExecutionNotesDTO {
>   @Schema(description = "The plan ExecutionID") String executionId;
>   @Schema(description = "Notes for a particular PipelineExecution") String notes;
> ```

this constant you already have isnt?



_Code quote:_
```Java
Notes for a particular PipelineExecution
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 513 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5Zr10QrMzUgG4THu:-NTr5Zr10QrMzUgG4THv:bpn92xa) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L513)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns metadata of a execution")
>       })
>   @Hidden
> ```

these will not be hidden
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 534 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5aTl-gNGjqECiE9I:-NTr5aTl-gNGjqECiE9J:bqfy2tr) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L534)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns metadata of a execution")
>       })
>   @Hidden
> ```

same as above, not hidden
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 548 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr617b8c7adPNt4Dqj:-NTr617b8c7adPNt4Dqk:belv200) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L548)):*
> ```Java
>           description = "ExecutionId of the execution for which we want to get Metadata") String planExecutionId) {
>     PipelineExecutionNotesDTO pipelineExecutionNotes =
>         pmsExecutionService.updateNotesForExecution(planExecutionId, notes);
> ```

cant we expose this direclty on planExecutionMetadataService?



_Code quote:_
```Java
pmsExecutionService
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr64qO7rGd6wk-M9Db:-NTr5o9o46jmwP4JRyWl:b-tzz8xx) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java#L89)):*
> ```Java
>       List<String> stageIdentifiers);
> 
>   PipelineExecutionNotesDTO getNotesForExecution(String planExecutionId);
> ```

why cant we add directly to planExecutionMetadataService?


<!-- Sent from Reviewable.io -->

2023-04-25 10:18 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 14 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr56UB8Nk2Y2nlTRgz:-NTrjAiOE_zNDcJOLsjl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Notes of a pipeline execution
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr6BX92A-qpwXubzfC:-NTruo4E5APuIwsJSRt0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

criteria should be created inside service layer, and should be passed to repository layer 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr6JA34XmxRYbrBKqw:-NTruocuCiOT0Xf2qgX3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont use mongoTemplate and call repository
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5QO400agqA9gjCem:-NTrjCUH33aeF-WWTTfA:b-bsf03n) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same use constant which you created
</blockquote></details>

The file with the constant is not visible in this file.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5K_14cuqSuSfgtX7:-NTrjCyi3_6KQK7x8eE-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

The Pipeline ExecutionId
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5O-hEEfMbqUT_kzt:-NTrjDNr7qbNZJrhr_ei:b-bsf03n) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineExecutionNotesDTO.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this constant you already have isnt?
</blockquote></details>

The file with the constant is not visible in this file.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 513 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5Zr10QrMzUgG4THu:-NTrjDwM9nNBAf6fUkG_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L513)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

these will not be hidden
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 534 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr5aTl-gNGjqECiE9I:-NTrjEH-0Uaw5GQxehNY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L534)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above, not hidden
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 548 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr617b8c7adPNt4Dqj:-NTrjqZtBRtrhDN070O2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L548)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant we expose this direclty on planExecutionMetadataService?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr64qO7rGd6wk-M9Db:-NTrjpvgCi0dfTtCRd9H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java#L89)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why cant we add directly to planExecutionMetadataService?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-26 05:47 UTC, senjucanon2 commented
trigger ut0, ut1, ut2

2023-04-26 07:18 UTC, archit-harness requested changes
> Reviewed 6 of 10 files at r4, 3 of 6 files at r5, 4 of 11 files at r6, 3 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 28 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOh3FDUJuAv6QXZ7D:-NTwOh3FDUJuAv6QXZ7E:b3w6vcr) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L63)):*
> ```Java
> 
>   public PipelineExecutionNotesDTO getNotesForExecution(String planExecutionId) {
>     Optional<PlanExecutionMetadata> planExecutionMetadata = findByPlanExecutionId(planExecutionId);
> ```

use projections, here service layer can return just string. and resource layer can convert string to dto
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwPbYh46JNQME-9Vg-:-NTwPbYh46JNQME-9Vg0:b-3tldto) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L63)):*
> ```Java
> 
>   public PipelineExecutionNotesDTO getNotesForExecution(String planExecutionId) {
>     Optional<PlanExecutionMetadata> planExecutionMetadata = findByPlanExecutionId(planExecutionId);
> ```

use secondary mongo, check NodeExecutionReadHelper
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 74 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOqQ7312Q1Z-7FrPC:-NTwOqQ7312Q1Z-7FrPD:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L74)):*
> ```Java
>   }
> 
>   public PipelineExecutionNotesDTO updateNotesForExecution(String planExecutionId, String notes) {
> ```

same as above
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 75 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOs_G1L_7lgKh7KZ5:-NTwOs_G1L_7lgKh7KZ6:bmeiuf) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L75)):*
> ```Java
> 
>   public PipelineExecutionNotesDTO updateNotesForExecution(String planExecutionId, String notes) {
>     Criteria criteria = where(PlanExecutionMetadata.PlanExecutionMetadataKeys.planExecutionId).is(planExecutionId);
> ```

use import planExecutionMetadata else sonar will fail



_Code quote:_
```Java
PlanExecutionMetadata.PlanExecutionMetadataKeys
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 88 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQ1mF3KpUJz9rLhIn:-NTwQ1mF3KpUJz9rLhIo:b-1u9evg) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L88)):*
> ```Java
>     return PipelineExecutionNotesDTO.builder()
>         .executionId(planExecutionMetadata.getPlanExecutionId())
>         .notes(planExecutionMetadata.getNotes())
> ```

plus if notes are null, send empty string
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java` line 14 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwP1Yb5BSEw-LDA22J:-NTwP1Yb5BSEw-LDA22K:bln1t8j) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java#L14)):*
> ```Java
> import org.springframework.data.mongodb.core.query.Update;
> 
> public class PlanExecutionMetadataRepositoryCustomImpl implements PlanExecutionMetadataRepositoryCustom {
> ```

team annotation is missing
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwPJ5c3CUmHkbSCofe:-NTwPJ5c3CUmHkbSCoff:b-92sia3) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java#L17)):*
> ```Java
>   private final MongoTemplate mongoTemplate;
> 
>   public PlanExecutionMetadataRepositoryCustomImpl(MongoTemplate mongoTemplate) {
> ```

use all args, @AllArgsConstructor(access = AccessLevel.PRIVATE, onConstructor = @__({ @Inject }))
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionRepositoryCustomImpl.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwPgSJCsKlNoAMQreI:-NTwPgSJCsKlNoAMQreJ:bs2xoo9) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionRepositoryCustomImpl.java#L23)):*
> ```Java
> import com.google.inject.Singleton;
> import java.util.List;
> import net.jodah.failsafe.Failsafe;
> ```

where are these imports used?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 118 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQ8f53OtFbdy2fIk5:-NTwQ8f53OtFbdy2fIk6:b-f24mgq) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L118)):*
> ```Java
>             .withProcessedYaml(transformProcessedYaml(
>                 planExecutionMetadata.getProcessedYaml(), executionMode, originalPlanExecutionId))
>                 .withNotes(notes)
> ```

why do you need with here?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQBxTEsybfJ_-b93S:-NTwQBxTEsybfJ_-b93T:bup0x9z) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java#L20)):*
> ```Java
> import io.harness.pms.pipeline.PMSPipelineListRepoResponse;
> import io.harness.pms.pipeline.PipelineEntity;
> import io.harness.pms.pipeline.PipelineExecutionNotesDTO;
> ```

where is this improt used?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 436 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQFxuBGG1BKapauRP:-NTwQFxuBGG1BKapauRQ:bqz1yfs) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L436)):*
> ```Java
>         }
>         ExecArgs execArgs = executionHelper.buildExecutionArgs(pipelineEntity, null, runtimeInputYaml, stagesToExecute,
>         [...]

2023-04-26 07:18 UTC, prashantsharma04 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 28 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java` line 197 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOtzz4mIQPQ_MKQpR:-NTwOtzz4mIQPQ_MKQpS:bpbpwpc) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java#L197)):*
> ```Java
>   public static final String PLAN_NAME = "planName";
>   public static final String TARGET_IDENTIFIER_KEY = "targetIdentifier";
>   public static final String NOTES_FOR_PLAN_EXECUTION = "notesForPlanExecution";
> ```

Why are we adding PLAN in name. Can it be NOTES_FOR_EXECUTION or NOTEST_FOR_PIPELINE_EXECUTION? cc @archit-harness 
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr56UB8Nk2Y2nlTRgz:-NTwPX7vAXHaxwX59H7b:b-8qm09v) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java#L32)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Make P of pipeline in caps. Similarly for Execution


<!-- Sent from Reviewable.io -->

2023-04-26 10:28 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 28 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java` line 197 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOtzz4mIQPQ_MKQpR:-NTwvE3bBwaGV3SlCIQr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java#L197)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Why are we adding PLAN in name. Can it be NOTES_FOR_EXECUTION or NOTEST_FOR_PIPELINE_EXECUTION? cc @archit-harness 
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/46872#-NTr56UB8Nk2Y2nlTRgz:-NTwvTh01WEagSKpSzSd:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/310be0fe086cd4b113b349f5a8125ffb34611a3f/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceConstants.java#L32)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Make P of pipeline in caps. Similarly for Execution
</blockquote></details>

Done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 74 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOqQ7312Q1Z-7FrPC:-NTx47JW0MQo1boRsS7U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L74)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 75 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOs_G1L_7lgKh7KZ5:-NTwvtf6BU-aZ8Z1yDiC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use import planExecutionMetadata else sonar will fail
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 88 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQ1mF3KpUJz9rLhIn:-NTwwzwy4H3buZ5iXqD5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L88)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

plus if notes are null, send empty string
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java` line 14 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwP1Yb5BSEw-LDA22J:-NTwx4kD0QTQNpbJzBKh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java#L14)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

team annotation is missing
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwPJ5c3CUmHkbSCofe:-NTwxNmH3J93eZ3rDM6Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use all args, @AllArgsConstructor(access = AccessLevel.PRIVATE, onConstructor = @__({ @Inject }))
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 118 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQ8f53OtFbdy2fIk5:-NTx5T7YENDZ7H4dXSve:b-cm4cuq) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L118)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need with here?
</blockquote></details>

I just wanted to avoid an explicit set statement here, anyway have explicitly set it now.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 436 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQFxuBGG1BKapauRP:-NTx4hwhApbGrAQWbG6I:b-5kue1k) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L436)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we have default buildExecutionArgs method so people don't need to send null?
</blockquote></details>

here in the case of notes null is serves the purpose when we don't want any notes to pass
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionRepositoryCustomImpl.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwPgSJCsKlNoAMQreI:-NTx4TJo3TFgIzW3exM-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionRepositoryCustomImpl.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where are these imports used?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQBxTEsybfJ_-b93S:-NTx4FNi2gpS0YjIwcGe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where is this improt used?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-26 12:23 UTC, archit-harness requested changes
> Reviewed 1 of 2 files at r3, 1 of 11 files at r6, 7 of 11 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 28 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java` line 28 at r9](https://reviewable.io/reviews/harness/harness-core/46872#-NTxVXm0BObt_q4kkeEn:-NTxVXm0BObt_q4kkeEo:b-xreekj) ([raw file](https://github.com/harness/harness-core/blob/7819576bd71d8826e450b9d82b33e7dcca02e396/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java#L28)):*
> ```Java
>   public PlanExecutionMetadata getExecutionNotes(Criteria criteria) {
>     Query query = new Query(criteria);
>     return secondaryMongoTemplate.findOne(query, PlanExecutionMetadata.class);
> ```

check this for initialising PmsExecutionSummaryReadHelpers

for secondary mongo template

you may need to remove all args if you use this one, don't use directly as helper is already created
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 118 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQ8f53OtFbdy2fIk5:-NTxVuOJENs2Arr26Muf:b-ek3g4k) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L118)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

I just wanted to avoid an explicit set statement here, anyway have explicitly set it now.
</blockquote></details>

I meant why notes needs to be set?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 436 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQFxuBGG1BKapauRP:-NTxW-mQ1wprEcuOC7Et:bmmjtfd) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L436)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

here in the case of notes null is serves the purpose when we don't want any notes to pass
</blockquote></details>

but caller should not send null, if that flow doesn't care about notes to be passed


<!-- Sent from Reviewable.io -->

2023-04-27 05:35 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 28 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwOh3FDUJuAv6QXZ7D:-NU06Y245ivYlzmEKP4d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use projections, here service layer can return just string. and resource layer can convert string to dto
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwPbYh46JNQME-9Vg-:-NU06erlEhyCCrLFrGPk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use secondary mongo, check NodeExecutionReadHelper
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java` line 28 at r9](https://reviewable.io/reviews/harness/harness-core/46872#-NTxVXm0BObt_q4kkeEn:-NU0AurG5UbnSwwIZ4ev:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7819576bd71d8826e450b9d82b33e7dcca02e396/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/PlanExecutionMetadataRepositoryCustomImpl.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check this for initialising PmsExecutionSummaryReadHelpers

for secondary mongo template

you may need to remove all args if you use this one, don't use directly as helper is already created
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 118 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQ8f53OtFbdy2fIk5:-NU0BCDMBT8buNPkBdwG:b-d8174i) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L118)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I meant why notes needs to be set?
</blockquote></details>

This method is called for creating new PlanExecutionMetadata in rollback execution and at that time also we need to have notes for execution as discussed on the call. It just the integration of notes for rollbackExecution.Hence, reverting back to the use of with(notes).
___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 436 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQFxuBGG1BKapauRP:-NU0CEQc3mPZC-Libx6s:b-1zgn4e) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L436)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

but caller should not send null, if that flow doesn't care about notes to be passed
</blockquote></details>

@DefaultValue() does not supports null, can I set it to "" Empty string


<!-- Sent from Reviewable.io -->

2023-04-27 05:38 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 28 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 436 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQFxuBGG1BKapauRP:-NU0D14a1vRZYYKaGpKZ:bnslycj) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L436)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

@DefaultValue() does not supports null, can I set it to "" Empty string
</blockquote></details>

Ok i can do it via notes = null in method, will do it


<!-- Sent from Reviewable.io -->

2023-04-27 07:35 UTC, prashantsharma04 approved these changes
> Reviewed 1 of 10 files at r4, 2 of 6 files at r5, 7 of 11 files at r6, 3 of 6 files at r7, 6 of 11 files at r8, 2 of 3 files at r10, 3 of 4 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 18 file(s) to review. 1 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-27 08:28 UTC, archit-harness requested changes
> Reviewed 1 of 6 files at r5, 1 of 6 files at r7, 2 of 11 files at r8, 2 of 3 files at r10, 3 of 4 files at r11, 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 119 at r8](https://reviewable.io/reviews/harness/harness-core/46872#-NU0njKvAF8bs-7zr7EZ:-NU0njKvAF8bs-7zr7E_:bf17y3) ([raw file](https://github.com/harness/harness-core/blob/39e32e295cf974d0f1528a24ec4ce3e3f095f907/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L119)):*
> ```Java
>       @QueryParam("notifyOnlyUser") @DefaultValue("false") boolean notifyOnlyUser,
>       @QueryParam(NGCommonEntityConstants.NOTES_FOR_PIPELINE_EXECUTION) @Parameter(
>           description = NOTES_FOR_PLAN_EXECUTION_PARAM_MESSAGE) String notes,
> ```

this was correct, it should be placed before body
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 186 at r8](https://reviewable.io/reviews/harness/harness-core/46872#-NU0noeRB5_sI2snXkye:-NU0noeRB5_sI2snXkyf:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/39e32e295cf974d0f1528a24ec4ce3e3f095f907/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L186)):*
> ```Java
>       @NotEmpty String pipelineIdentifier, @BeanParam GitEntityFindInfoDTO gitEntityBasicInfo,
>       @QueryParam("useFQNIfError") @DefaultValue("false") boolean useFQNIfErrorResponse,
>       @QueryParam(NGCommonEntityConstants.NOTES_FOR_PIPELINE_EXECUTION) @Parameter(
> ```

same as above
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 513 at r13](https://reviewable.io/reviews/harness/harness-core/46872#-NU0oS6K5l30o8W1RpSD:-NU0oS6LBop63LK38Zv2:bu4nfjw) ([raw file](https://github.com/harness/harness-core/blob/4d476716be37e985ce1add0a62c2161e28b4dc3e/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L513)):*
> ```Java
>       {
>         @io.swagger.v3.oas.annotations.responses.
>         ApiResponse(responseCode = "default", description = "Returns Notes and executionId of a pipelineExecution")
> ```

remove executionId



_Code quote:_
```Java
executionId of
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 534 at r13](https://reviewable.io/reviews/harness/harness-core/46872#-NU0oTXB6Mjc00e6XTBh:-NU0oTXB6Mjc00e6XTBi:balou8q) ([raw file](https://github.com/harness/harness-core/blob/4d476716be37e985ce1add0a62c2161e28b4dc3e/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L534)):*
> ```Java
>       {
>         @io.swagger.v3.oas.annotations.responses.
>         ApiResponse(responseCode = "default", description = "Returns Notes and executionId of a pipelineExecution")
> ```

remove execution id
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 112 at r13](https://reviewable.io/reviews/harness/harness-core/46872#-NU0ow1A8ay5a41OuzIb:-NU0ow1A8ay5a41OuzIc:b-qu6g5e) ([raw file](https://github.com/harness/harness-core/blob/4d476716be37e985ce1add0a62c2161e28b4dc3e/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L112)):*
> ```Java
> 
>   public PlanExecutionMetadata transformPlanExecutionMetadata(PlanExecutionMetadata planExecutionMetadata,
>       String planExecutionID, ExecutionMode executionMode, List<String> stageNodeExecutionIds, String notes) {
> ```

rename notes field


<!-- Sent from Reviewable.io -->

2023-04-27 10:07 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 13 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 119 at r8](https://reviewable.io/reviews/harness/harness-core/46872#-NU0njKvAF8bs-7zr7EZ:-NU172On16aGIJBJ_ErP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39e32e295cf974d0f1528a24ec4ce3e3f095f907/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L119)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this was correct, it should be placed before body
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 186 at r8](https://reviewable.io/reviews/harness/harness-core/46872#-NU0noeRB5_sI2snXkye:-NU17UNS71hTKH2AOlOS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39e32e295cf974d0f1528a24ec4ce3e3f095f907/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L186)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 513 at r13](https://reviewable.io/reviews/harness/harness-core/46872#-NU0oS6K5l30o8W1RpSD:-NU17h4WEc_nFp6OyE_Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4d476716be37e985ce1add0a62c2161e28b4dc3e/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L513)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove executionId
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 534 at r13](https://reviewable.io/reviews/harness/harness-core/46872#-NU0oTXB6Mjc00e6XTBh:-NU17hL1DkPIKNSkOAqa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4d476716be37e985ce1add0a62c2161e28b4dc3e/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L534)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove execution id
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 112 at r13](https://reviewable.io/reviews/harness/harness-core/46872#-NU0ow1A8ay5a41OuzIb:-NU185tQ1bl_gViKNqgP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4d476716be37e985ce1add0a62c2161e28b4dc3e/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename notes field
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 436 at r7](https://reviewable.io/reviews/harness/harness-core/46872#-NTwQFxuBGG1BKapauRP:-NU190W56qy5uUTeehkA:b-mjai5l) ([raw file](https://github.com/harness/harness-core/blob/0334e13286d1950a8fec1722f3db69b0acd366b0/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L436)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Ok i can do it via notes = null in method, will do it
</blockquote></details>

Did by an overriding method and passing null value in our impl.


<!-- Sent from Reviewable.io -->

2023-04-27 11:01 UTC, archit-harness approved these changes
> Reviewed 3 of 11 files at r6, 1 of 6 files at r7, 1 of 11 files at r8, 6 of 7 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46872)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-04-27 11:06 UTC, senjucanon2 commented
trigger review

2023-04-27 11:10 UTC, merged