fix: [DEL-5749]: Move HB upadte to redis instead of mongo
harness/harness-core pull request #46913
Opened 2023-04-24 22:16 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-19 18:42 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 382 at r2](https://reviewable.io/reviews/harness/harness-core/46913#-NTrydhC428NLQcqbd1i:-NVpJ_E8DNhnjTJJcxCa:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/9782c094d4c0c2d968c9f8a7701e445958c87fc9/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L382)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Simplify this method, we can now have 4 cache reads for this one operation. I think best to extract `delegateRedisCache.get(delegateId)` to a variable to avoid going to cache multiple times.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-05-19 18:48 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/46913#-NTuWDqXBp08ZO-t3UMO:-NVpK1l5BpDEaO2ZqF32:b-8l7daw) ([raw file](https://github.com/harness/harness-core/blob/9782c094d4c0c2d968c9f8a7701e445958c87fc9/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java#L39)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Ideally you would only use (write through) cache here and in all other places and cache would read/write to DB/Redis based on the `enableRedisForDelegateService` flag. This way you have only one source of truth for delegates (Redis or DB based on config) which makes it much simpler and avoids all the corner cases. 
</blockquote></details>

it's not only here, for ecs update/HB delegate operations we need to refresh HB too which doesn't take this code path. I need to add over there too, which is missing currently


<!-- Sent from Reviewable.io -->

2023-05-19 18:49 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/46913#-NTuWDqXBp08ZO-t3UMO:-NVpKqx5DqRmA5oseV5K:b-rcdu0b) ([raw file](https://github.com/harness/harness-core/blob/9782c094d4c0c2d968c9f8a7701e445958c87fc9/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java#L39)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

it's not only here, for ecs update/HB delegate operations we need to refresh HB too which doesn't take this code path. I need to add over there too, which is missing currently
</blockquote></details>

agree it's safer at one place, unless we refactor ECS specific code


<!-- Sent from Reviewable.io -->

2023-05-19 22:02 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/46913#-NTuWDqXBp08ZO-t3UMO:-NVq1A4FAH6rV5zMEHGf:b-e0rzxy) ([raw file](https://github.com/harness/harness-core/blob/9782c094d4c0c2d968c9f8a7701e445958c87fc9/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java#L39)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

agree it's safer at one place, unless we refactor ECS specific code
</blockquote></details>

I think we can hard refresh cache everytime for ECS delegate, so moved refresh logic to this class so only one place to update HB to cache.


<!-- Sent from Reviewable.io -->

2023-05-26 04:21 UTC, raghuAtWings requested changes

2023-05-26 04:21 UTC, raghuAtWings commented on 360-cg-manager/src/main/java/software/wings/app/WingsApplication.java
> +    delegateExecutor.scheduleWithFixedDelay(new Schedulable("Sync delegate HB from redis",
not every manager pod should do, don't we have a concept of running a cron across pods?

2023-05-26 04:21 UTC, raghuAtWings commented on 360-cg-manager/src/main/java/software/wings/app/WingsApplication.java
> +    delegateExecutor.scheduleWithFixedDelay(new Schedulable("Sync delegate HB from redis",
not every manager pod should do, don't we have a concept of running a cron across pods?

2023-05-26 04:21 UTC, raghuAtWings commented on 360-cg-manager/src/main/java/software/wings/app/WingsApplication.java
> +    delegateExecutor.scheduleWithFixedDelay(new Schedulable("Sync delegate HB from redis",
not every manager pod should do, don't we have a concept of running a cron across pods?

2023-05-26 04:21 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java
> +      setUnset(updateOperations, DelegateKeys.lastHeartBeat, System.currentTimeMillis());
this can not be now, we need to find the minimum timestamp of the  heartbeat of the delegates in the list and update to that time

2023-05-26 04:21 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java
> +      Query<Delegate> query = persistence.createQuery(Delegate.class).field(DelegateKeys.uuid).in(delegates);
create query like createQuery(Delegate.class, excludeAuthority)

2023-05-26 04:21 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatDao.java
>      final UpdateOperations<Delegate> updateOperations = persistence.createUpdateOperations(Delegate.class);
what is the impact of this not being updated in db everytime?

2023-05-26 04:21 UTC, raghuAtWings commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +      return delegateCache.getDelegateLastHeartBeat(delegate) > (currentTimeMillis() - EXPIRY_TIME.toMillis());
why is EXPIRY_TIME different than other times? shouldn't we just one time to find everything related to delegates?

2023-05-30 21:28 UTC, jennyjames21 commented
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1394 at r3](https://reviewable.io/reviews/harness/harness-core/46913#gh-1206218430:-NWiYZMW0IVR_7fP8ZQL:b-q9pe0c) ([raw file](https://github.com/harness/harness-core/blob/b9a2d85f6c23b34a80353d010e2f79a6a522a943/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1394)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

not every manager pod should do, don't we have a concept of running a cron across pods?
</blockquote></details>

adding lock inside that class so that one manager pod runs it(yet to test as PR env broken). Note we are also moving all scheduled jobs to manager-iterator only in another PR.


<!-- Sent from Reviewable.io -->

2023-05-30 21:29 UTC, jennyjames21 commented
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1394 at r3](https://reviewable.io/reviews/harness/harness-core/46913#gh-1206218551:-NWiZ0Px2SFl2nzZbzGm:b-hue1ee) ([raw file](https://github.com/harness/harness-core/blob/b9a2d85f6c23b34a80353d010e2f79a6a522a943/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1394)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

not every manager pod should do, don't we have a concept of running a cron across pods?
</blockquote></details>

yes, that's what we trying to do with persistence lock


<!-- Sent from Reviewable.io -->

2023-05-30 21:29 UTC, jennyjames21 commented
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1394 at r3](https://reviewable.io/reviews/harness/harness-core/46913#gh-1206218920:-NWiZEbH5pihjGjp6QL1:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/b9a2d85f6c23b34a80353d010e2f79a6a522a943/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1394)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

not every manager pod should do, don't we have a concept of running a cron across pods?
</blockquote></details>

same


<!-- Sent from Reviewable.io -->

2023-05-30 21:34 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/46913#gh-1206219885:-NWiZI3R00oBpvQB4T8F:b-1hn9l1) ([raw file](https://github.com/harness/harness-core/blob/b9a2d85f6c23b34a80353d010e2f79a6a522a943/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java#L54)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this can not be now, we need to find the minimum timestamp of the  heartbeat of the delegates in the list and update to that time
</blockquote></details>

I dont see any point in taking minimum or max here as they both can be accurate so why not just be current then?  
Note with this change we dont use DB heartbeat only when data is not available in Redis cache.


<!-- Sent from Reviewable.io -->

2023-05-30 21:55 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/46913#gh-1206220567:-NWieB6n6TP1PUnbi8dI:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/b9a2d85f6c23b34a80353d010e2f79a6a522a943/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java#L52)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

create query like createQuery(Delegate.class, excludeAuthority)
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-07-18 18:08 UTC, closed without merging