feat: [CDS-56737]: Adding plan creator for Blue Green Stage Scale Down Step.
harness/harness-core pull request #46929
Opened 2023-04-25 07:53 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-27 05:05 UTC, GoelPratyush99 commented
trigger ut0

2023-04-27 05:06 UTC, GoelPratyush99 commented
trigger ut2

2023-04-27 05:06 UTC, GoelPratyush99 commented
trigger ut3

2023-04-27 05:08 UTC, GoelPratyush99 commented
trigger ut5

2023-04-27 05:08 UTC, GoelPratyush99 commented
trigger ut8

2023-04-27 05:08 UTC, GoelPratyush99 commented
trigger ut9

2023-04-28 08:21 UTC, abosii-harness requested changes

2023-04-28 08:21 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java
> +                   .clazz(K8sCanaryStepNode.class)
K8sCanaryStepNode?

2023-04-28 10:15 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java
> +                   .clazz(K8sCanaryStepNode.class)
Changed it to K8sBGStageScaleDownNode

2023-04-28 13:12 UTC, abosii-harness approved these changes

2023-04-28 13:58 UTC, markoharness approved these changes
> Reviewed 21 of 22 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46929)* status: 24 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-04-28 13:59 UTC, GoelPratyush99 commented
trigger messagecheck

2023-04-28 13:59 UTC, GoelPratyush99 commented
trigger review

2023-04-28 14:00 UTC, GoelPratyush99 commented
trigger messagecheck

2023-04-28 14:04 UTC, puthrayaharness requested changes

2023-04-28 14:04 UTC, puthrayaharness commented on 970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_type.proto
> +  K8S_BLUE_GREEN_STAGE_SCALE_DOWN = 209;
This might be breaking change. Can you please once confirm with Delegate team?

2023-04-28 14:08 UTC, puthrayaharness approved these changes

2023-05-02 07:16 UTC, abosii-harness approved these changes

2023-05-02 07:27 UTC, yogesh-chauhan reviewed
> Reviewed 20 of 22 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46929)* status: Some of the checks are too old. 1 file(s) to review. 2. unresolved discussions. 

___
*[`125-cd-nextgen/src/test/resources/cdng/variables/pipelineWithK8sBGStageScaleDownStep.json` line 67 at r3](https://reviewable.io/reviews/harness/harness-core/46929#-NUQLoc11CVzf6lJrHEL:-NUQLoc11CVzf6lJrHEM:b-nu7nw2) ([raw file](https://github.com/harness/harness-core/blob/7eedd365464ef00d1858b788f2c17fac891d2632/125-cd-nextgen/src/test/resources/cdng/variables/pipelineWithK8sBGStageScaleDownStep.json#L67)):*
> ```JSON
>                               ],
>                               "branch": "master",
>                               "__uuid": "EgwWjke4Tua5IFjK672P-A"
> ```

you can remove __uuid fields to make this more readable


<!-- Sent from Reviewable.io -->

2023-05-02 07:27 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46929)* status: Some of the checks are too old. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-02 07:32 UTC, merged