feat: [CDS-54411]: added getApprovalInstancesByExecutionId API
harness/harness-core pull request #47037
Opened 2023-04-27 06:41 UTC by naman-goenka

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-03 13:17 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47037#-NUWke2v6I-A4IAiNwqJ:-NUWke2v6I-A4IAiNwqK:b-cmiyxk) ([raw file](https://github.com/harness/harness-core/blob/10569206f53a3bb3902f7c30eedca5fef03e80ff/pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L47)):*
> ```Java
> 
>   public ResponseDTO<List<ApprovalInstanceResponseDTO>> getApprovalInstancesByExecutionId(
>       @NotNull @AccountIdentifier String accountId, @NotNull @OrgIdentifier String orgId,
> ```

why is there org id, project id in the params if its not used?


<!-- Sent from Reviewable.io -->

2023-05-03 16:24 UTC, naman-goenka commented
> _[`pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47037#-NUWke2v6I-A4IAiNwqJ:-NUWke2v6I-A4IAiNwqK:b-cmiyxk) ([raw file](https://github.com/harness/harness-core/blob/10569206f53a3bb3902f7c30eedca5fef03e80ff/pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L47)):_
> 
> > ```java
> >   public ResponseDTO<List<ApprovalInstanceResponseDTO>> getApprovalInstancesByExecutionId(
> >       @NotNull @AccountIdentifier String accountId, @NotNull @OrgIdentifier String orgId,
> > ```
> 
> why is there org id, project id in the params if its not used?

for rbac check getting properly enforced

2023-05-03 16:58 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47037#-NUWke2v6I-A4IAiNwqJ:-NUXY6SE9SMXDPv-io0z:b-3e3m9w) ([raw file](https://github.com/harness/harness-core/blob/10569206f53a3bb3902f7c30eedca5fef03e80ff/pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L47)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

for rbac check getting properly enforced
</blockquote></details>

Didn't get you, what rbac? Can you please explain further whats the issue if these params aren't passed?


<!-- Sent from Reviewable.io -->

2023-05-03 17:11 UTC, naman-goenka commented
> _[`pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47037#-NUWke2v6I-A4IAiNwqJ:-NUXY6SE9SMXDPv-io0z:b-3e3m9w) ([raw file](https://github.com/harness/harness-core/blob/10569206f53a3bb3902f7c30eedca5fef03e80ff/pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L47)):_
> 
> Previously, naman-goenka (Naman Goenka) wrote…
> Didn't get you, what rbac? Can you please explain further whats the issue if these params aren't passed?

We have ```@NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)``` on this resource. For another public API in this resource, we are facing a rbac issue where the check is not been honored, and pipeline team suggested one cause can be missing scope params in the resource (org / project). So, have included scope params in this API. 

Moreover, if the plan execution id is not unique across scopes in future, then changing API signature (backward incompatible change) would be required. So its better to have scope params in the resource.

2023-05-03 18:58 UTC, mohitg0795 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47037#-NUWke2v6I-A4IAiNwqJ:-NUXynnQ0BTn1BBPJuni:bd4c52d) ([raw file](https://github.com/harness/harness-core/blob/10569206f53a3bb3902f7c30eedca5fef03e80ff/pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L47)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

We have ```@NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)``` on this resource. For another public API in this resource, we are facing a rbac issue where the check is not been honored, and platform team suggested possible cause can be missing scope params in the resource (org / project). So, have included scope params in this API. 

Moreover, if the plan execution id is not unique across scopes in future, then changing API signature (backward incompatible change) would be required. So its better to have scope params in the resource. 

</blockquote></details>

Lets discuss on call tomorrow.


<!-- Sent from Reviewable.io -->

2023-05-18 05:44 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        - name: approvalStatus
these should be snake_cased
approval_status, approval_type etc.

2023-05-18 05:45 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        errorMessage:
here also snake_case

2023-05-18 05:46 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        id:
this has no type?

2023-05-18 05:51 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +            approvalMessage: |-
any chance these could also follow snake_case? Also since this part is not explicitly added in API contract I hope customer will be fine with the ambiguity after generating client stubs

2023-05-18 10:43 UTC, naman-goenka commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +            approvalMessage: |-
yes in API contract details is object. This results from detail DTO's of various types of approval, and will not be possible to easily convert to snake_case

2023-05-18 10:48 UTC, naman-goenka commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        - name: approvalStatus
done

2023-05-18 10:48 UTC, naman-goenka commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        errorMessage:
done

2023-05-18 11:38 UTC, naman-goenka commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        id:
done

2023-05-18 12:44 UTC, naman-goenka commented
trigger utAll

2023-05-18 13:56 UTC, naman-goenka commented
trigger utAll

2023-05-18 17:37 UTC, puthrayaharness requested changes

2023-05-18 17:37 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsAPIUtils.java
> +  public TypeEnum toTypeEnum(ApprovalType approvalType) {
Why do we have two enums?

2023-05-18 17:37 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsAPIUtils.java
> +    switch (approvalStatus) {
You can simplify it with `StatusEnum.fromString(approvalStatus.name())` something along line?

2023-05-18 18:29 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsAPIUtils.java
> +    switch (approvalStatus) {
@puthrayaharness this is working
```
  public StatusEnum toStatusEnum(ApprovalStatus approvalStatus) {
    if(isNull(approvalStatus)){
      return null;
    }
    return StatusEnum.fromValue(approvalStatus.name());
  }
```
But it would couple the enum display values in BE and in the spec. Should I prefer this or existing approach?

2023-05-19 08:46 UTC, vaibhav-si reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47037)* status: 13 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsAPIUtils.java` line 62 at r5](https://reviewable.io/reviews/harness/harness-core/47037#gh-1198100056:-NVnAdFn-7AotWMcoZB9:bmsk1np) ([raw file](https://github.com/harness/harness-core/blob/0603c168a486dde06edae02e209e95888c2b9983/pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsAPIUtils.java#L62)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

@puthrayaharness this is working
```
  public StatusEnum toStatusEnum(ApprovalStatus approvalStatus) {
    if(isNull(approvalStatus)){
      return null;
    }
    return StatusEnum.fromValue(approvalStatus.name());
  }
```
But it would couple the enum display values in BE and in the spec. Should I prefer this or existing approach?
</blockquote></details>

The existing approach is fine I think. If you foresee that the values could be different for the 2 enums, it's better not to couple tightly. 
Also, it's not an imp. decision. Can be easily changed later also.


<!-- Sent from Reviewable.io -->

2023-05-19 08:49 UTC, vaibhav-si requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47037)* status: 13 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsApiImpl.java` line 48 at r5](https://reviewable.io/reviews/harness/harness-core/47037#-NVnBX5E6T_QGevij9SU:-NVnBX5E6T_QGevij9SV:bm3usjy) ([raw file](https://github.com/harness/harness-core/blob/0603c168a486dde06edae02e209e95888c2b9983/pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsApiImpl.java#L48)):*
> ```Java
>   @Override
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)
>   public Response getApprovalInstancesByExecutionId(@OrgIdentifier String org, @ProjectIdentifier String project,
> ```

are these parameters all non-mandatory? like accountId? If not, pls add Notnull in the spec and it should show up automatically.


<!-- Sent from Reviewable.io -->

2023-05-24 09:46 UTC, puthrayaharness approved these changes

2023-05-24 11:21 UTC, naman-goenka commented
trigger review

2023-05-24 11:22 UTC, merged

2023-05-29 09:58 UTC, naman-goenka commented
> _[`pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47037#-NUWke2v6I-A4IAiNwqJ:-NUXynnQ0BTn1BBPJuni:bd4c52d) ([raw file](https://github.com/harness/harness-core/blob/10569206f53a3bb3902f7c30eedca5fef03e80ff/pipeline-service/service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L47)):_
> 
> Previously, naman-goenka (Naman Goenka) wrote…
> Lets discuss on call tomorrow.

This can be resolved as the related code reference was deleted and openAPI spec approach was followed.