[feat]: [CDS-59011]: adding HPA and PDB support for K8s deployments
harness/harness-core pull request #47098
Opened 2023-04-27 19:04 UTC by markoharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-28 08:17 UTC, abosii-harness requested changes

2023-04-28 08:17 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +      horizontalPodAutoscaler.appendSuffixInName('-' + stageColor, resources);
How we're handling the case if customer already created an HPA with -blue or green suffix?

2023-04-28 08:17 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/manifest/ManifestHelper.java
> +            "More than one HPA is found targeting the same resource. This is not expected!");
What if there are multiple HPA?

2023-04-28 08:17 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/manifest/ManifestHelper.java
> +        throw new KubernetesYamlException("More than one PodDisruptionBudget resource found. This is not expected!");
Same here, what if there are multiple PDB?

2023-04-28 08:17 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    resolveManagedWorkload(resources);
Can we think of a way to make it behind FF?

2023-05-08 07:17 UTC, markoharness commented
trigger uts

2023-05-08 08:12 UTC, abosii-harness requested changes
Please add some unit tests. We can add some kind of integration tests. For example, using Kubernetes resource class replicate the same steps as would Canary or Blue/Green task do and use some valid yaml files.

2023-05-08 08:12 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +        if (!resource.getResourceId().getName().endsWith(K8sConstants.CANARY_WORKLOAD_SUFFIX_NAME_WITH_SEPARATOR)) {
potentially this check shouldn't be required

2023-05-08 08:12 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        if (!resource.getResourceId().getName().endsWith(suffix)) {
potentially this check shouldn't be required

2023-05-08 08:12 UTC, abosii-harness requested changes
Please add some unit tests. We can add some kind of integration tests. For example, using Kubernetes resource class replicate the same steps as would Canary or Blue/Green task do and use some valid yaml files.

2023-05-08 19:19 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/beans/apply/K8sHandlerConfig.java
> +import java.util.ArrayList;
unused import ?

2023-05-08 19:33 UTC, abhinavsingh1196 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +    if (context.getResources() != null) {
context could be null? there is a usage in handler like this
`resource.appendSuffixInName(suffix, null);`

Maybe we could pass a dummy empty context object there instead of null

2023-05-08 19:49 UTC, abhinavsingh1196 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +          })
Spec is nullable, so we should add a null check for it just to be safe. Also, extracting this logic in a separate method cleans up the stream quite a bit
`return resources.stream()
              .filter(resource -> Kind.HorizontalPodAutoscaler.name().equals(resource.getResourceId().getKind()) && !resource.isDirectApply())
              .filter(resource -> matchesHpa(resource, kind, name))
              .collect(Collectors.toList());`

` private static boolean matchesHpa(KubernetesResource resource, String kind, String name) {
    V1HorizontalPodAutoscaler v1HorizontalPodAutoscaler = (V1HorizontalPodAutoscaler) resource.getK8sResource();
    return v1HorizontalPodAutoscaler.getSpec() != null && v1HorizontalPodAutoscaler.getSpec().getScaleTargetRef().getKind().equals(kind)
            && v1HorizontalPodAutoscaler.getSpec().getScaleTargetRef().getName().equals(name);
  }`

2023-05-08 20:40 UTC, markoharness commented
trigger uts

2023-05-09 07:40 UTC, markoharness commented
trigger uts

2023-05-12 08:12 UTC, abosii-harness requested changes

2023-05-12 08:12 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceContext.java
> +public class KubernetesResourceContext {
nit: you can rename this to KubernetesResourceUpdateContext, or you can have 2 different classes KubernetesResourceNameUpdateEvent and KubernetesResourceSelectorUpdateEvent

2023-05-12 08:12 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceHandler.java
> +public class KubernetesResourceHandler implements KubernetesResourceBaseHandler {
Let's do the refactor as we discussed offline

2023-05-16 07:18 UTC, markoharness commented
trigger feature-build

2023-05-17 07:21 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +      horizontalPodAutoscaler.appendSuffixInName('-' + stageColor, resources);
Handling logic has been added.

2023-05-17 07:21 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/manifest/ManifestHelper.java
> +            "More than one HPA is found targeting the same resource. This is not expected!");
Handling logic has been added.

2023-05-17 07:21 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/manifest/ManifestHelper.java
> +        throw new KubernetesYamlException("More than one PodDisruptionBudget resource found. This is not expected!");
Handling logic has been added.

2023-05-17 07:23 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        && k8sRequestHandlerContext.getResourcesForNameUpdate() != null) {
done

2023-05-17 07:23 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +  private void updateRefInPodDisruptionBudget(
added more generic logic

2023-05-17 07:23 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +                     .getMatchLabels()
handled the NPE

2023-05-17 07:23 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +              resource -> ImmutableSet.of(Kind.PodDisruptionBudget.name()).contains(resource.getResourceId().getKind()))
done

2023-05-17 07:24 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +      context.getResourcesForNameUpdate().addAll(
done

2023-05-17 07:24 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +        hpaK8sResource.getSpec().getScaleTargetRef().setName(newName);
handled the NPE

2023-05-17 07:24 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +  public Map<String, String> getWorkloadSelectorLabels() {
removed

2023-05-17 07:24 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +        if (!resource.getResourceId().getName().endsWith(K8sConstants.CANARY_WORKLOAD_SUFFIX_NAME_WITH_SEPARATOR)) {
removed

2023-05-17 07:24 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        if (!resource.getResourceId().getName().endsWith(suffix)) {
removed

2023-05-17 07:25 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +          })
changed the logic for this and added null check where needed.

2023-05-17 07:25 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceContext.java
> +public class KubernetesResourceContext {
done

2023-05-17 07:25 UTC, markoharness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceHandler.java
> +public class KubernetesResourceHandler implements KubernetesResourceBaseHandler {
done

2023-05-17 07:25 UTC, markoharness commented
trigger uts

2023-05-17 08:07 UTC, abosii-harness requested changes

2023-05-17 08:07 UTC, abosii-harness commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/KubernetesResourceTest.java
> +    List<KubernetesResource> hpaResourcesNotToBeUpdated =
let's add a size assertion

2023-05-17 11:28 UTC, markoharness commented
trigger feature-build

2023-05-18 12:35 UTC, markoharness commented
trigger publish-delegate

2023-05-19 06:39 UTC, markoharness commented
trigger uts

2023-05-19 08:09 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java
> +        -> ImmutableSet.of(Kind.HorizontalPodAutoscaler.name(), Kind.PodDisruptionBudget.name())
Done, reference line 184

2023-05-19 08:12 UTC, abosii-harness approved these changes

2023-05-19 08:55 UTC, markoharness commented
trigger uts

2023-05-19 08:57 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryDeleteRequestHandler.java` line 79 at r7](https://reviewable.io/reviews/harness/harness-core/47098#gh-1196091127:-NVnDdFB0YdrigRRZITX:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/83081c41c712d1abdc3395814769361a7513414a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryDeleteRequestHandler.java#L79)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is it used anywhere?
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2023-05-19 08:58 UTC, markoharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47098)* status: 44 file(s) to review. 1 change requests. 21. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java` line 182 at r7](https://reviewable.io/reviews/harness/harness-core/47098#gh-1196094505:-NVnDj6EA2fD-VYaErUa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83081c41c712d1abdc3395814769361a7513414a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java#L182)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

you need to add the same logic in handleTaskFailure
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java` line 640 at r5](https://reviewable.io/reviews/harness/harness-core/47098#gh-1187141807:-NVnD_WiAenmFhwUS_DT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6dda457ca9377ca0fa928f74863a333ceacc09cc/970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java#L640)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We can make this generic 
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/test/java/io/harness/k8s/model/KubernetesResourceTest.java` line 228 at r7](https://reviewable.io/reviews/harness/harness-core/47098#gh-1196106327:-NVnDc0h7rJkcNlk6hDA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/83081c41c712d1abdc3395814769361a7513414a/970-api-services-beans/src/test/java/io/harness/k8s/model/KubernetesResourceTest.java#L228)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's add a size assertion
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-19 09:22 UTC, GoelPratyush99 approved these changes

2023-05-19 09:23 UTC, abhinavsingh1196 approved these changes

2023-05-19 09:54 UTC, markoharness commented
trigger ut2

2023-05-19 09:55 UTC, markoharness commented
trigger review

2023-05-19 10:35 UTC, markoharness commented
trigger ut2

2023-05-19 11:45 UTC, merged