feat:[CDS-53484]: moving freeze activation handler to redis batch
harness/harness-core pull request #47114
Opened 2023-04-28 05:27 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-04 05:56 UTC, abhinavmittal-harness requested changes
> Reviewed 2 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47114)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers/NgDeploymentFreezeActivationHandler.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/47114#-NU_IJR72nXzUWaEsRqD:-NU_IJR80wnFZvOGpsDy:bvuooax) ([raw file](https://github.com/harness/harness-core/blob/695a2503f0e2bb13e875ab0379ed4f5a09fb48b4/120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers/NgDeploymentFreezeActivationHandler.java#L104)):*
> ```Java
>         entity.setShouldSendNotification(false);
>         entity.setNextIteration(null);
>         freezeCRUDService.updateExistingFreezeConfigEntity(entity);
> ```

When we update does this add a value to Audit trails
___
*[`125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/47114#-NU_K97L7r-njuG4K9O0:-NU_K97NAv9H2G8Z9iNh:bltmmh0) ([raw file](https://github.com/harness/harness-core/blob/695a2503f0e2bb13e875ab0379ed4f5a09fb48b4/125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java#L110)):*
> ```Java
>   @SchemaIgnore @LastModifiedBy private EmbeddedUser lastUpdatedBy;
> 
>   Long nextIteration;
> ```

We should not be updating type of entity as it might break older configs


<!-- Sent from Reviewable.io -->

2023-05-04 10:11 UTC, sourabh-awashti commented
trigger uts

2023-05-04 10:17 UTC, sourabh-awashti commented
trigger uts

2023-05-04 10:47 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 1 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47114)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/47114#-NUaMiEM-_YHV5pu7iOB:-NUaMiEN6AXX0G61av-_:b-mdeapw) ([raw file](https://github.com/harness/harness-core/blob/aa3bf7c4d15fb28bb513c99a31ea5183ff1c4568/125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java#L112)):*
> ```Java
>   Long nextIteration;
> 
>   List<Long> nextIterations;
> ```

nit: mark this deprecated


<!-- Sent from Reviewable.io -->

2023-05-04 11:34 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47114)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-04 11:39 UTC, RishabhGupta34 commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers/NgDeploymentFreezeActivationHandler.java
> +  private static final int EPOCH_VALUE_FOR_30_MINS_IN_MILLI = 18000000;
isn't this 300 mins? 
probably we should use some converter maybe like `TimeUnit.MINUTES.toMillis(30)`?

2023-05-04 11:41 UTC, RishabhGupta34 commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers/NgDeploymentFreezeActivationHandler.java
> +                                      .addCriteria(where(FreezeConfigEntityKeys.shouldSendNotification).is(true))));
is removing this value `.maximumDelayForCheck(ofMinutes(10))` desired? I see it was present previously but not now

2023-05-04 13:37 UTC, sourabh-awashti commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers/NgDeploymentFreezeActivationHandler.java
> +  private static final int EPOCH_VALUE_FOR_30_MINS_IN_MILLI = 18000000;
I am not using this variable so removing it

2023-05-04 13:44 UTC, sourabh-awashti commented
trigger uts

2023-05-04 14:42 UTC, RishabhGupta34 submitted a review, later dismissed

2023-05-04 14:43 UTC, sourabh-awashti commented
trigger review

2023-05-04 20:59 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47114)* status: 7 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-05 01:05 UTC, Raghav-Murali requested changes
Have reviewed only the iterator parts of the code.

2023-05-05 01:05 UTC, Raghav-Murali commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers/NgDeploymentFreezeActivationHandler.java
> +                           .persistenceProvider(new SpringPersistenceRequiredProvider<>(mongoTemplate))
I remember we discussing this on a call sometime back. Redis Batch mode currently supports MorphiaPersistenceProvider only and not SpringPersistenceProvider. 

I had already added and tested the support for SpringPersistenceProvider in this PR which is not merged - https://github.com/harness/harness-core/pull/45505/files#diff-15de57e84344b08335ecc8790cde1947521f9d90e218eeee7f55001a7aea861f. Can you being in the changes of the 2 SpringPersistenceProvider files into this PR ?

2023-05-08 21:36 UTC, Raghav-Murali approved these changes

2023-05-09 06:17 UTC, abhinavmittal-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47114)* status: Some of the checks are too old. 7 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-09 07:05 UTC, sourabh-awashti commented
trigger review

2023-05-09 07:15 UTC, merged