feat: [IDP-379]: Unit test cases for app-config and env variables man…
harness/harness-core pull request #47148
Opened 2023-04-28 12:17 UTC by devesh-harness

…agement

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-04-28 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=47148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=47148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=47148) it.</sub>

2023-04-28 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=47148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=47148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=47148) it.</sub>

2023-05-02 04:40 UTC, vikyathharekal requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47148)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/test/java/io/harness/idp/configmanager/services/ConfigEnvVariableServiceImplTest.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/47148#-NUPk63O6OLZ9DiH0x1O:-NUPk63PDiPKWs4FROd9:b-38rzjn) ([raw file](https://github.com/harness/harness-core/blob/a592137015e818c330ac03e4da3ec2ff906957b2/idp-service/src/test/java/io/harness/idp/configmanager/services/ConfigEnvVariableServiceImplTest.java#L64)):*
> ```Java
>   @Owner(developers = DEVESH)
>   @Category(UnitTests.class)
>   public void testInsertConfigEnvVariable() throws Exception {
> ```

Could we cover the case where configVariables is empty? for all the 3 methods - insert, update, and get
Also, a case where the reserved env variable is used and when the env variable is already used?
___
*[`idp-service/src/test/java/io/harness/idp/configmanager/services/ConfigEnvVariableServiceImplTest.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/47148#-NUPg_A1D3IDVPn-Zpv_:-NUPg_A1D3IDVPn-Zpva:b-t251dg) ([raw file](https://github.com/harness/harness-core/blob/a592137015e818c330ac03e4da3ec2ff906957b2/idp-service/src/test/java/io/harness/idp/configmanager/services/ConfigEnvVariableServiceImplTest.java#L69)):*
> ```Java
>     AppConfig appConfig = getTestAppConfig(backstageEnvSecretVariable);
> 
>     when(backstageEnvVariableService.createMulti(any(), any())).thenReturn(Arrays.asList(backstageEnvSecretVariable));
> ```

nit: could use Collections.singletonList when there's only one element.



_Code quote:_
```Java
Arrays.asList
```


<!-- Sent from Reviewable.io -->

2023-05-02 13:52 UTC, sathish-soundarapandian approved these changes

2023-05-02 13:58 UTC, vikyathharekal commented
trigger review

2023-05-02 15:20 UTC, merged