[fix]: [CDS-68205]: fetch SHA value of schemaVersion2 even when schemaVersion1 fails
harness/harness-core pull request #47201
Opened 2023-05-02 06:44 UTC by Abhishek-CDC

## Describe your changes
Earlier manifest API calls for schemaVersion1 and schemaVersion2 were in the same try catch block. 
It is possible for an image that manifest api for schemaVersion1 fails but successful for schemaVersion2. In such scenario SHA value for schemaVersion2 will be missed and there could be validation error because of digest mismatch.
Made changes to call both APIs separately in different try catch block.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-02 07:14 UTC, Abhishek-CDC commented
trigger smartchecks

2023-05-03 05:57 UTC, puthrayaharness requested changes

2023-05-03 05:57 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifacts/docker/service/DockerRegistryUtils.java
> +    if (shouldFetchDockerV2DigestSHA256) {
Let's deprecate this usage if possible. Let's fetch both v1 and v2 like we do in other artifact sources.

2023-05-05 05:00 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifacts/docker/service/DockerRegistryUtils.java
> +    if (shouldFetchDockerV2DigestSHA256) {
this method has multiple usages, with both true and false value. Not to break existing flow for others, made change to send always true for LastSuccessfulBuild

2023-05-05 05:39 UTC, Abhishek-CDC commented
trigger utAll

2023-05-05 05:52 UTC, Abhishek-CDC commented
trigger utAll

2023-05-05 08:05 UTC, Abhishek-CDC commented
trigger uts

2023-05-05 08:38 UTC, Abhishek-CDC commented
trigger uts

2023-05-05 09:01 UTC, Abhishek-CDC commented
trigger messagecheck

2023-05-05 10:36 UTC, puthrayaharness approved these changes

2023-05-05 11:12 UTC, vivekkarnatiharness approved these changes
> Reviewed 2 of 2 files at r1, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47201)* status: 5 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-05 12:01 UTC, Abhishek-CDC commented
trigger review

2023-05-05 12:05 UTC, merged