fix: [CDS-54797]: delegate side changes for the other actions
harness/harness-core pull request #47245
Opened 2023-05-02 17:26 UTC by TarunUba1

## Describe your changes
delegate changes for servicehooks regarding actions template rendering and wait for steady state
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-02 18:54 UTC, TarunUba1 commented
trigger messagecheck

2023-05-02 18:56 UTC, TarunUba1 commented
trigger utAll

2023-05-03 08:26 UTC, abosii-harness requested changes

2023-05-03 08:26 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +  public String prepareWorkloadContext(List<KubernetesResource> workloads) {
Just add these context variables using addToContext. For example, before rendering you can add MANIFEST_PATH (or what is the name) to context and it will make available for other hooks as well. In this case, for wait for steady state do this before starting wait for steady state. There shouldn't be any logic based on the hook type to add a specific env variable. Any env variables (context values) from previous hooks should be available in the next ones

2023-05-03 08:26 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    String renderedTemplate = k8sDelegateTaskParams.getWorkingDirectory() + "/manifests-dry-run.yaml";
Let's not use MANIFEST_FILE_OUTPUT_PATH, in the spec I had in mind that this manifest.yaml will be available after rendering but thinking about this more is not the case for most of the strategies, like Canary and Blue/Green. We can have later another hook action for APPLY for this purpose

2023-05-03 08:26 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java
> +    String renderedTemplate = k8sDelegateTaskParams.getWorkingDirectory() + "/manifests-dry-run.yaml";
Same here

2023-05-03 08:26 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +    String renderedTemplate = k8sDelegateTaskParams.getWorkingDirectory() + "/manifests-dry-run.yaml";
Same here

2023-05-03 08:26 UTC, abosii-harness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java
> +  private ServiceHookHandler serviceHookHandler;
You can have it as mock and then you should be able to verify if the hooks are running or not by using verify. Please add this check for each deployment test in K8s

2023-05-03 13:25 UTC, TarunUba1 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java
> +  private ServiceHookHandler serviceHookHandler;
not verifying as servicehookhandler is created in the method in itself. wrote tests for handler itself

2023-05-03 16:07 UTC, TarunUba1 commented
trigger smartchecks

2023-05-03 18:28 UTC, abhinavsingh1196 requested changes

2023-05-03 18:28 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +          customWorkloadIds.stream().map(KubernetesResourceId::getName).collect(Collectors.joining(","));
we can refactor this method further like this:

addToContext(managedWorkloads, MANAGED_WORKLOADS)
addToContext(customWorkloads, CUSTOM_WORKLOADS)
addToContext(Union(managedWorkloads, customWorkloads), WORKLOADS_LIST) 

void addToContext(List<..> workloads, String CONTEXT_NAME):
  if workloads is empty -> return empty string
  ...
  context.put(CONTEXT_NAME, < comma separated workload name list > )

2023-05-03 18:28 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +          managedWorkloadIds.stream().map(KubernetesResourceId::getName).collect(Collectors.joining(","));
These two above streams can be merged

2023-05-04 05:07 UTC, TarunUba1 commented
trigger uts

2023-05-04 10:52 UTC, TarunUba1 commented
trigger uts

2023-05-04 12:05 UTC, TarunUba1 commented
trigger uts

2023-05-04 14:07 UTC, abosii-harness requested changes

2023-05-04 14:07 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +    String workloadContext = (workloads.stream().map(KubernetesResource::getResourceId).collect(Collectors.toList()))
This should be:
workloads.stream()
 .map(KubernetesResource::getResourceId)
 .map(KubernetesResourceId::getName)
 .collect(Collectors.joining(","))

2023-05-04 15:23 UTC, TarunUba1 commented
trigger uts

2023-05-04 15:38 UTC, TarunUba1 commented
trigger codebasehash

2023-05-04 16:50 UTC, abhinavsingh1196 approved these changes

2023-05-04 16:50 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +  public void addToContext(String key, String value) {
unused method, we can remove it in another PR if you want

2023-05-04 16:51 UTC, abosii-harness approved these changes

2023-05-04 17:00 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/utils/ServiceHookHandler.java
> +  public void addToContext(String key, String value) {
it is used abhi for adding context for manifest directory😅

2023-05-04 17:00 UTC, TarunUba1 commented
trigger review

2023-05-04 17:01 UTC, merged