feat: [CDS-56736]: preparing skeleton for delegate side changes.
harness/harness-core pull request #47332
Opened 2023-05-04 06:58 UTC by GoelPratyush99

## Describe your changes
preparing skeleton for delegate side changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-05 07:49 UTC, abosii-harness requested changes

2023-05-05 07:49 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  K8S_BLUE_GREEN_STAGE_SCALE_DOWN_TASK(TaskGroup.K8S_NG, "K8s Task with Blue Green Stage Scale down step");
You can set unsupported as true for now K8S_BLUE_GREEN_STAGE_SCALE_DOWN_TASK(TaskGroup.K8S_NG, "K8s Task with Blue Green Stage Scale down step", true)

We will change this to false only after we made all delegate changes. In local for testing you can manually set it to false (there was an env variable, but not sure if DEL team made it work or still is not working)

2023-05-05 07:49 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBlueGreenStageScaleDownResponse.java
> +  List<K8sPod> k8sPodList;
I don't think you'll need this, we can remove from this PR and only if it will be required

2023-05-11 05:35 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  K8S_BLUE_GREEN_STAGE_SCALE_DOWN_TASK(TaskGroup.K8S_NG, "K8s Task with Blue Green Stage Scale down step");
Done

2023-05-11 05:35 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBlueGreenStageScaleDownResponse.java
> +  List<K8sPod> k8sPodList;
Removed it

2023-05-11 05:47 UTC, abosii-harness approved these changes

2023-05-11 06:04 UTC, GoelPratyush99 commented
trigger uts

2023-05-11 06:05 UTC, namantalaycha10 approved these changes

2023-05-11 06:05 UTC, namantalaycha10 approved these changes

2023-05-11 06:18 UTC, GoelPratyush99 commented
trigger review

2023-05-11 06:46 UTC, merged