feat: [CDS-59511]: Adding support for v3 urls for custom webhook triggers along with webhook token
harness/harness-core pull request #47375
Opened 2023-05-04 19:24 UTC by Y0709

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-04 19:40 UTC, Y0709 commented
trigger uts

2023-05-04 22:11 UTC, rohitk-h requested changes
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47375)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/webhook/WebhookHelper.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/47375#-NUclYO97WaOKQ-u1S2N:-NUclYO97WaOKQ-u1S2O:bra18x7) ([raw file](https://github.com/harness/harness-core/blob/00b8833ea734d9232a11fcc6a056c2bb3c213ab9/970-ng-commons/src/main/java/io/harness/webhook/WebhookHelper.java#L98)):*
> ```Java
>   }
> 
>   public String generateCustomWebhookCurlCommand(String webhookUrl, String mandatoryAuth) {
> ```

Why use a string here? 
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/47375#-NUcmlNp49vw3lHLzxWp:-NUcmlNp49vw3lHLzxWq:bvbbrfs) ([raw file](https://github.com/harness/harness-core/blob/00b8833ea734d9232a11fcc6a056c2bb3c213ab9/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L290)):*
> ```Java
>       })
>   @Path("/custom/{webhookToken}/v3")
>   @ApiOperation(value = "accept custom webhook event V2", nickname = "customWebhookEndpointV3")
> ```

nit: needs to be updated to v3
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java` line 534 at r1](https://reviewable.io/reviews/harness/harness-core/47375#-NUcn6Og3rW-3sVKzzrO:-NUcn6Og3rW-3sVKzzrP:b3t39j9) ([raw file](https://github.com/harness/harness-core/blob/00b8833ea734d9232a11fcc6a056c2bb3c213ab9/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java#L534)):*
> ```Java
>         webhookUrl = WebhookHelper.generateWebhookUrl(webhookConfigProvider, ngTriggerEntity.getAccountId());
>       } else if (webhookMetadata.getCustom() != null) {
>         String mandatoryAuth = "false";
> ```

Why not initialize as a boolean and below response can be cast to a boolean. This seems odd to read. 


<!-- Sent from Reviewable.io -->

2023-05-04 22:19 UTC, rohitk-h approved these changes

2023-05-05 16:37 UTC, rohitk-h submitted a review, later dismissed
> Reviewed 1 of 11 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47375)* status: 12 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-05 19:27 UTC, Y0709 commented
trigger uts

2023-05-05 19:39 UTC, Y0709 commented
trigger uts

2023-05-05 21:17 UTC, rohitk-h submitted a review, later dismissed
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47375)* status: 15 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-05 22:27 UTC, vcalasansh requested changes

2023-05-05 22:27 UTC, vcalasansh commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java
> +              Objects.equals(NGRestUtils
I think you should need to move this call to settingsResource outside this method. If you look in `ngTriggerResource`, you will see that `getListForTarget` is calling this method for every trigger that is being listed. So this would generate multiple repeated calls to settingsResource every time "list triggers" API is called.

2023-05-06 19:18 UTC, Y0709 commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java
> +              Objects.equals(NGRestUtils
done

2023-05-06 19:22 UTC, Y0709 commented
trigger uts

2023-05-07 14:55 UTC, vcalasansh approved these changes
> Reviewed 4 of 11 files at r1, 5 of 7 files at r2, 3 of 5 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47375)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-07 18:00 UTC, rohitk-h approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47375)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-05-07 18:03 UTC, Y0709 commented
trigger review

2023-05-07 18:06 UTC, merged