fix: [IDP-459]: Harness CI/CD Plugin nase config based on env type
harness/harness-core pull request #47419
Opened 2023-05-05 10:43 UTC by devesh-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-05 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=47419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=47419) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=47419) it.</sub>

2023-05-05 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=47419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=47419) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=47419) it.</sub>

2023-05-05 10:44 UTC, devesh-harness commented
trigger uts

2023-05-05 11:04 UTC, sandeepa-kv-jois approved these changes

2023-05-05 11:06 UTC, sandeepa-kv-jois requested changes
We may need to add for stage as well as for internal usecase, most of the pipelines would be on stage.

2023-05-05 11:09 UTC, sathish-soundarapandian commented on idp-service/src/main/resources/baseappconfig-preqa.yaml
> +  '/harness/stress':
I'm thinking if we need to handle this in a better way so that we don't need to make further changes based on environments. The dynamic value here is the "env".
```
proxy:
  '/harness/{ENV}':
    target: 'https://{ENV}.harness.io/'
    pathRewrite:
      'api/proxy/harness/{ENV}/?': '/'
    allowedHeaders:
      - authorization
```
The above can be your baseappconfig.yaml and our idp-service config.yml will have env with values like - qa, stress, uat, app, etc...
In the processing logic, we read the file from resource path and replace the ENV placeholder with the value from config.

2023-05-05 11:12 UTC, devesh-harness commented on idp-service/src/main/resources/baseappconfig-preqa.yaml
> +  '/harness/stress':
yes but prod actually do not follow this pattern there we have env as Prod not app.

2023-05-05 11:26 UTC, sathish-soundarapandian commented on idp-service/src/main/resources/baseappconfig-preqa.yaml
> +  '/harness/stress':
Ok. Then let's see if the dynamic values can be off env and harnessTargetUrl.
env - qa, stress, uat, prod
harnessTargetUrl - https://qa.harness.io/, https://stress.harness.io/, https://uat.harness.io/, https://app.harness.io/

But if you feel this might be overkill considering we don't have much environments, I'm ok with the current logic itself. Just check once.

2023-05-05 11:35 UTC, devesh-harness commented
trigger uts

2023-05-05 12:26 UTC, sathish-soundarapandian submitted a review, later dismissed

2023-05-06 04:11 UTC, devesh-harness commented
trigger ut8

2023-05-06 04:11 UTC, devesh-harness commented
trigger ut2

2023-05-08 04:17 UTC, devesh-harness commented
trigger ut8

2023-05-08 04:17 UTC, devesh-harness commented
trigger ut2

2023-05-08 07:23 UTC, vikyathharekal approved these changes

2023-05-08 09:33 UTC, devesh-harness commented
trigger uts

2023-05-08 10:42 UTC, devesh-harness commented
trigger uts

2023-05-08 12:32 UTC, sandeepa-kv-jois approved these changes

2023-05-08 12:43 UTC, sathish-soundarapandian approved these changes

2023-05-08 13:30 UTC, vikyathharekal commented
trigger review

2023-05-08 13:39 UTC, merged