feat: [CDS-54465]: Reuse or create a new Perpetual Task for new Deployment -> code fixes and Unit Test
harness/harness-core pull request #47465
Opened 2023-05-08 06:02 UTC by namantalaycha10

## Describe your changes
Changes include some code fixes and Unit Test
Changes are backward compatible and are behind the FF
These feature is in progress so FF will only be enable when complete changes will be in Prod 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/47465)

2023-05-11 07:11 UTC, abhinavsingh1196 approved these changes

2023-05-11 07:11 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java
> +        .setOrgId(connectorInfoDTO.getOrgIdentifier() == null ? "" : connectorInfoDTO.getOrgIdentifier())
nit: StringUtils can clean this up
defaultIfEmpty(connectorInfoDTO.getOrgIdentifier(), EMPTY)

2023-05-17 07:52 UTC, namantalaycha10 commented on 126-instance/src/main/java/io/harness/service/instancesyncperpetualtask/instancesyncperpetualtaskhandler/k8s/K8SInstanceSyncPerpetualTaskHandler.java
> +        .setOrgId(connectorInfoDTO.getOrgIdentifier() == null ? "" : connectorInfoDTO.getOrgIdentifier())
Done

2023-05-17 09:24 UTC, namantalaycha10 commented
trigger messagecheck

2023-05-18 05:37 UTC, namantalaycha10 commented
trigger uts

2023-05-18 06:59 UTC, namantalaycha10 commented
trigger uts

2023-05-18 07:12 UTC, GoelPratyush99 approved these changes
lgtm

> Reviewed 2 of 11 files at r1, 20 of 25 files at r2, 2 of 3 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47465#-:-NVhgr6n4PfI67DERQbq:bb7k0qh)* status: 27 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.  (waiting on @alebuh)



<!-- Sent from Reviewable.io -->

2023-05-18 07:17 UTC, abosii-harness requested changes

2023-05-18 07:17 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/perpetualtask/instancesync/DeploymentReleaseDetails.java
> +package io.harness.perpetualtask.instancesync;
Can we move all these classes to their own package?

2023-05-18 07:17 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/perpetualtask/instancesync/DeploymentReleaseDetails.java
> +  String taskInfoId;
Either add default private or add missing access modifier private to all fields

2023-05-18 07:17 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/perpetualtask/instancesync/CloudClusterConfig.java
> +public class CloudClusterConfig {
Let's rename this to KubernetesCloudClusterConfig

2023-05-18 08:06 UTC, namantalaycha10 commented
trigger commonchecks

2023-05-18 12:26 UTC, namantalaycha10 commented
trigger uts

2023-05-18 12:44 UTC, GoelPratyush99 approved these changes
> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47465)* status: 28 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): del-team.  (waiting on @alebuh)



<!-- Sent from Reviewable.io -->

2023-05-18 13:59 UTC, abosii-harness approved these changes

2023-05-18 14:12 UTC, mdmilic approved these changes
I don't think there are any files (that should be) code owned by del team. Approving to unblock.

2023-05-18 16:17 UTC, namantalaycha10 commented
trigger review

2023-05-18 16:18 UTC, namantalaycha10 commented
trigger pmd

2023-05-18 16:18 UTC, namantalaycha10 commented
trigger codebasehash

2023-05-18 16:27 UTC, merged