[feat]: [CI-7826]: Add logs to Check connectorref
harness/harness-core pull request #47508
Opened 2023-05-08 14:06 UTC by smjt-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/47508)

2023-05-08 14:07 UTC, smjt-h commented
trigger uts

2023-05-08 16:03 UTC, smjt-h commented
trigger uts

2023-05-08 16:20 UTC, aman-harness approved these changes

2023-05-09 07:16 UTC, smjt-h commented
trigger uts

2023-05-09 07:47 UTC, smjt-h commented
trigger uts

2023-05-09 09:33 UTC, harshjain12 commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorHelper.java
> +        return true;
Do not hard code string

2023-05-09 09:34 UTC, harshjain12 commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorHelper.java
> +        return true;
can you check class instead of type

Pipeline team should also review it

2023-05-09 10:38 UTC, smjt-h commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorHelper.java
> +        return true;
done.
All details are inside type only.
This is just for debugging in QA. will remove this later

2023-05-09 10:38 UTC, smjt-h commented
trigger uts

2023-05-10 04:43 UTC, smjt-h commented
trigger uts

2023-05-10 05:24 UTC, hextechpal requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47508)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/RunStepInfo.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/47508#-NV361SkErgZ7W7z1t-2:-NV361SkErgZ7W7z1t-3:bxc2aru) ([raw file](https://github.com/harness/harness-core/blob/c306253de33860070dc4199e99207245f53a0e06/879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/RunStepInfo.java#L152)):*
> ```Java
>       connectorRefMap.put(YAMLFieldNameConstants.CONNECTOR_REF, connectorRef);
>     }
>     log.info("connectorRef value=" + connectorRef.getValue());
> ```

shouldn't this line be inside else, other wise you will have 2 logs for non null values


<!-- Sent from Reviewable.io -->

2023-05-10 05:36 UTC, smjt-h reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47508)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/RunStepInfo.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/47508#-NV361SkErgZ7W7z1t-2:-NV39BDTEcrEBqgxi1wW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c306253de33860070dc4199e99207245f53a0e06/879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/RunStepInfo.java#L152)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

shouldn't this line be inside else, other wise you will have 2 logs for non null values
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-10 05:36 UTC, smjt-h commented
trigger uts

2023-05-10 06:12 UTC, hextechpal approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47508)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-10 06:22 UTC, merged