feat: [CDS-54183]: Shifting code to trigger pipeline via webhook event on a…
harness/harness-core pull request #47581
Opened 2023-05-09 19:56 UTC by Y0709

… redis queue to trigger pipelines asyncrounously

Context : The customer was facing slowness issue when their single webhook event had to fire many different triggers as we currently fire triggers syncrounously . Have implemented this pr to shift that code behind a redis queue so that each trigger does not wait for the one before to trigger the pipeline.

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/47581)

2023-05-10 05:31 UTC, Y0709 commented
trigger uts

2023-05-10 08:28 UTC, Y0709 commented
trigger ut1

2023-05-10 20:39 UTC, Y0709 commented
trigger uts

2023-05-10 20:44 UTC, Y0709 commented
trigger uts

2023-05-10 23:05 UTC, rohitk-h approved these changes

2023-05-10 23:10 UTC, rohitk-h approved these changes
Let's document the monitoring aspects of this queue as this rolls our into production. Having this as part of feature release will go a long way.

2023-05-10 23:10 UTC, rohitk-h commented on pipeline-service/service/src/main/java/io/harness/pms/event/triggerwebhookevent/TriggerWebhookEventStreamListener.java
> +        throw new InvalidRequestException("Exception while processing Trigger webhook event", e);
nit: Add message id in exception logs to help in troubleshooting.

2023-05-11 10:59 UTC, archit-harness reviewed
> Reviewed 7 of 14 files at r1, 3 of 6 files at r2, 1 of 1 files at r3, 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47581)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-11 13:10 UTC, vcalasansh commented on 953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java
> +  public static final String TRIGGER_WEBHOOK_EVENTS_STREAM = "trigger_webhook_events_stream";
I would suggest renaming this to `TRIGGER_EXECUTION_EVENTS_STREAM`. In the future, my idea is to move artifact/manifest trigger executions to the redis queue too, since we can also have the same slowness issue for artifact/manifest triggers firing multiple pipelines from the same event.

2023-05-11 13:11 UTC, vcalasansh commented on 953-events-api/src/main/proto/io/harness/eventsframework/schemas/webhookpayloads/webhookdata.proto
> +message TriggerWebhookDTO {
Same renaming suggestion here, I would name it `TriggerExecutionDTO, rename `TriggerWebhookEventStreamConsumer` to `TriggerExecutionEventStreamConsumer` and so on.

2023-05-11 13:23 UTC, vcalasansh commented on pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/helpers/TriggerEventExecutionHelper.java
> +                && mappingRequestData.getWebhookDTO() != null) {
Put a comment here explaining why this is needed because of V1 flow, so we can remember when removing the FF to make sure V1 is never being used.

2023-05-11 17:30 UTC, brijeshdhakar requested changes
> Reviewed 7 of 14 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47581)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/triggerwebhookevent/TriggerWebhookEventStreamConsumer.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/47581#-NV9OyyqChIn5b9ctqFR:-NV9Oyyr21ex5JVqGzlx:bw89rhx) ([raw file](https://github.com/harness/harness-core/blob/3b243e491e0b1c480025aa96fa8b9418b73acc97/pipeline-service/service/src/main/java/io/harness/pms/event/triggerwebhookevent/TriggerWebhookEventStreamConsumer.java#L33)):*
> ```Java
>   @Inject
>   public TriggerWebhookEventStreamConsumer(@Named(TRIGGER_WEBHOOK_EVENTS_STREAM) Consumer redisConsumer,
>       TriggerWebhookEventStreamListener messageListener, @Named("pmsEventsCache") Cache<String, Integer> eventsCache,
> ```

You have a bind with @Named and here you are not using the @Names while injecting the Listener. You can remove the @Named from in the Bind.
```    bind(MessageListener.class)
        .annotatedWith(Names.named(EventsFrameworkConstants.TRIGGER_WEBHOOK_EVENTS_STREAM))
        .to(TriggerWebhookEventStreamListener.class);
```


<!-- Sent from Reviewable.io -->

2023-05-11 19:48 UTC, Y0709 commented on pipeline-service/service/src/main/java/io/harness/pms/event/triggerwebhookevent/TriggerWebhookEventStreamListener.java
> +        throw new InvalidRequestException("Exception while processing Trigger webhook event", e);
done

2023-05-11 19:48 UTC, Y0709 commented on pipeline-service/service/src/main/java/io/harness/pms/event/triggerwebhookevent/TriggerWebhookEventStreamListener.java
> +        throw new InvalidRequestException("Exception while processing Trigger webhook event", e);
done

2023-05-11 19:49 UTC, Y0709 commented on 953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java
> +  public static final String TRIGGER_WEBHOOK_EVENTS_STREAM = "trigger_webhook_events_stream";
done

2023-05-11 19:49 UTC, Y0709 commented on 953-events-api/src/main/proto/io/harness/eventsframework/schemas/webhookpayloads/webhookdata.proto
> +message TriggerWebhookDTO {
done

2023-05-11 19:51 UTC, Y0709 commented
trigger uts

2023-05-11 19:59 UTC, vcalasansh reviewed
> Reviewed 1 of 1 files at r3, 1 of 5 files at r4, 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47581)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-12 16:11 UTC, brijeshdhakar approved these changes
> Reviewed 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47581)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-05-12 16:21 UTC, Y0709 commented
trigger review

2023-05-12 18:31 UTC, rohitk-h approved these changes
> Reviewed 7 of 14 files at r1, 1 of 1 files at r3, 1 of 5 files at r4, 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47581)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-05-12 18:54 UTC, sribalij commented on pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/service/impl/TriggerWebhookEventExecutionServiceImpl.java
> +  private void saveTriggerExecutionHistoryRecords(List<TriggerEventResponse> responseList) {
Let us make sure to move these helper methods to one common place than duplicating in  `TriggerWebhookEventExecutionServiceImpl` and `TriggerWebhookExecutionServiceImplV2`. Please add a ticket to refactor it at a later point.

2023-05-12 18:57 UTC, sribalij approved these changes

2023-05-12 19:01 UTC, Y0709 commented on pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/service/impl/TriggerWebhookEventExecutionServiceImpl.java
> +  private void saveTriggerExecutionHistoryRecords(List<TriggerEventResponse> responseList) {
https://harness.atlassian.net/browse/CDS-69350

2023-05-13 01:25 UTC, merged