fix: [CDS-68390]: add logic to refactor Kubectl client
harness/harness-core pull request #47730
Opened 2023-05-12 10:06 UTC by achyuth-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-15 13:31 UTC, alebuh commented
trigger uts

2023-05-15 15:38 UTC, alebuh commented
trigger ut4

2023-05-16 08:56 UTC, abosii-harness requested changes

2023-05-16 08:56 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/kubectl/KubectlFactory.java
> +      version = versionCommand.execute(workingDir, null, null, false, Collections.emptyMap()).outputUTF8();
We may need to add client=true to version command

2023-05-16 08:56 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/kubectl/KubectlFactory.java
> +      log.error("Failed to get kubernetes version, defaulting to version: " + DEFAULT_KUBECTL_VERSION, ex);
This should be infor or at least warn

2023-05-16 08:57 UTC, abosii-harness requested changes
// ignore

2023-05-16 13:16 UTC, alebuh commented
trigger uts

2023-05-17 06:48 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/kubectl/KubectlFactory.java
> +      log.error("Failed to get kubernetes version, defaulting to version: " + DEFAULT_KUBECTL_VERSION, ex);
done

2023-05-17 06:48 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/kubectl/KubectlFactory.java
> +      version = versionCommand.execute(workingDir, null, null, false, Collections.emptyMap()).outputUTF8();
done

2023-05-17 06:49 UTC, alebuh commented
trigger uts

2023-05-18 11:03 UTC, alebuh commented
trigger uts

2023-05-18 13:03 UTC, alebuh commented
trigger uts

2023-05-19 08:52 UTC, markoharness approved these changes
> Reviewed 1 of 4 files at r4, 6 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47730)* status: 8 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-19 08:58 UTC, alebuh commented
trigger review

2023-05-19 09:00 UTC, merged