fix: [PL-32654]: Added limits for connectors based on license
harness/harness-core pull request #47794
Opened 2023-05-15 05:43 UTC by VikasMaddukuriHarness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-16 07:21 UTC, nishantsaini20 requested changes

2023-05-16 07:21 UTC, nishantsaini20 commented on 925-enforcement-service/src/main/resources/features/platform_features.yml
> +        enabled: true
Can tests be added to validate behaviour for this addition on connector creation?

2023-05-31 04:32 UTC, VikasMaddukuriHarness commented
trigger uts

2023-06-01 04:59 UTC, VikasMaddukuriHarness commented
trigger ut1,ut2,ut3

2023-06-01 06:13 UTC, VikasMaddukuriHarness commented
trigger ut7

2023-06-02 06:17 UTC, VikasMaddukuriHarness commented
trigger uts

2023-06-02 11:06 UTC, VikasMaddukuriHarness commented on 925-enforcement-service/src/main/resources/features/platform_features.yml
> +        enabled: true
I don't think we have tests for these. I don't think testing these changes are that necessary. But please let me know if you think we can add. Thanks.

2023-06-02 11:38 UTC, nishantsaini20 commented on 925-enforcement-service/src/main/resources/features/platform_features.yml
> +        enabled: true
This addition changes the behaviour of connect create api. Therefore IMO we should have tests around it but if this need proper framework then we can have is as part of different PR.

2023-06-02 11:38 UTC, nishantsaini20 approved these changes

2023-06-02 12:05 UTC, tiwaritejas approved these changes
> Reviewed 5 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47794)* status: 10 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-06-02 12:10 UTC, merged