fix: [CDS-69297]: doing fixes for customer cases
harness/harness-core pull request #47793
Opened 2023-05-15 05:41 UTC by TarunUba1

## Describe your changes
using shell script code to run the commands, saving in context cache dir for helm repos
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-15 05:58 UTC, TarunUba1 commented
trigger uts

2023-05-15 08:15 UTC, abosii-harness requested changes

2023-05-15 08:15 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +      serviceHookHandler.addToContext(HELM_REPOSITORY_CONFIG_PATH.getContextName(), helmRepoConfigPath);
As discussed, due to that repo cache folder is cleaned up after fetch it doesn't really make sense to add it to context

2023-05-15 08:15 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java
> +      if (commandExecutionStatus == SUCCESS && denoteOverallSuccess) {
Let's add a TODO comment to figure out what's going on here. This logic is fine for now, but there should've been used closeLogStream parameter in shell script config. Something is broken here

2023-05-18 11:43 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java
> +      if (commandExecutionStatus == SUCCESS && denoteOverallSuccess) {
Done

2023-05-18 11:43 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +      serviceHookHandler.addToContext(HELM_REPOSITORY_CONFIG_PATH.getContextName(), helmRepoConfigPath);
removed

2023-05-18 12:00 UTC, TarunUba1 commented
trigger uts

2023-05-18 12:38 UTC, namantalaycha10 approved these changes

2023-05-18 12:39 UTC, GoelPratyush99 approved these changes

2023-05-18 12:42 UTC, TarunUba1 commented
trigger review

2023-05-18 12:43 UTC, merged