feat: [CDS-68527]: Scaling down the stage environment in BG
harness/harness-core pull request #47835
Opened 2023-05-15 15:43 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-15 16:20 UTC, GoelPratyush99 commented
trigger uts

2023-05-16 08:49 UTC, abosii-harness requested changes

2023-05-16 08:49 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +  private String getComplimentingColor(String color) {
There is already a method that return inverse color

2023-05-16 08:49 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      k8sClient.performSteadyStateCheck(k8sSteadyStateDTO);
We don't require steady state check

2023-05-16 08:49 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      ImmutableSet.of("Deployment", "StatefulSet", "DaemonSet", "HorizontalPodAutoscaler", "PodDisruptionBudget");
I do believe you're missing DeploymentConfig

2023-05-16 08:49 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      ImmutableSet.of("Deployment", "StatefulSet", "DaemonSet");
Here as well

2023-05-16 08:49 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +              -> k8sResourceId.setName(k8sResourceId.getName().replace(getComplimentingColor(stageColor), stageColor)))
This replace should handle the use case replace("abc-blue-blue", "green) -> "abc-blue-green"

2023-05-16 08:49 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
> +  public static final Set<String> BG_SUPPORTED_COLORS = ImmutableSet.of("blue", "green");
Use HarnessLabelValues.colorBlue and HarnessLabelValues.colorGreen

2023-05-16 08:49 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
> +  public static final Set<String> BG_SUPPORTED_COLORS = ImmutableSet.of("blue", "green");
And rename it to BLUE_GREEN_COLORS

2023-05-16 08:49 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sScaleTaskHandler.java
> +    scaleLogCallback.saveExecutionLog("\nDone.", INFO, SUCCESS);
you're marking it as success if if scale result is false

2023-05-16 10:12 UTC, abhinavsingh1196 requested changes

2023-05-16 10:12 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      executionLogCallback.saveExecutionLog("Manifests processed. Found following resources: \n"
nit: Message should be something like 
'Found following resources from stage release which are eligible for scale down:"

2023-05-16 10:12 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +    List<KubernetesResourceId> deletedResources =
for readability, we can break this into 2 methods

stageScaleDown(...)
- deleteResources(resourceIds, ...)
- scaleResources(resourceIds, ...)

2023-05-17 08:09 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +  private String getComplimentingColor(String color) {
Done

2023-05-17 08:09 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      k8sClient.performSteadyStateCheck(k8sSteadyStateDTO);
Removed

2023-05-17 08:09 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      ImmutableSet.of("Deployment", "StatefulSet", "DaemonSet", "HorizontalPodAutoscaler", "PodDisruptionBudget");
Done

2023-05-17 08:09 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      ImmutableSet.of("Deployment", "StatefulSet", "DaemonSet");
Done

2023-05-17 08:09 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +              -> k8sResourceId.setName(k8sResourceId.getName().replace(getComplimentingColor(stageColor), stageColor)))
Done

2023-05-17 08:10 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
> +  public static final Set<String> BG_SUPPORTED_COLORS = ImmutableSet.of("blue", "green");
Done

2023-05-17 08:10 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      executionLogCallback.saveExecutionLog("Manifests processed. Found following resources: \n"
Done

2023-05-17 18:39 UTC, GoelPratyush99 commented
trigger uts

2023-05-17 18:40 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      LogCallback scaleLogCallback =
That command unit gets skipped
<img width="1638" alt="Screenshot 2023-05-18 at 12 01 47 AM" src="https://github.com/harness/harness-core/assets/97931011/a387e6a4-d08f-4e23-ae2f-53586433a803">

2023-05-18 06:18 UTC, abhinavsingh1196 requested changes

2023-05-18 06:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +            resourceIdsToScale.stream()
this should be a separate variable in itself, method arguments like these should not be provided directly

2023-05-18 06:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +    for (KubernetesResourceId resourceId : resourceIdsToScale) {
you could just keep using stream like above for consistency
`resourceIdsToScale.stream().filter(SCALE_WORKLOADS).forEach(scale())`

2023-05-18 06:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public boolean validateExistingResourceIds(Kubectl client, K8sDelegateTaskParams k8sDelegateTaskParams,
this method can be named something like `checkIfResourceExists`

2023-05-18 06:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +          .filter(k8sResourceId
if you make `validateExistingResourceIds` static, then this filter predicate can be replaced with `(K8sTaskHelperBase::validateExistingResourceIds)`

2023-05-18 06:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +          .filter(k8sResourceId -> WORKLOAD_KINDS.contains(k8sResourceId.getKind()) && isNotEmpty(stageColor))
`isNotEmpty(stageColor)` is being checked repeatedly. This method can be refactored as 
if (release == null) return emptyList()
String stageColor = getStageColor(release);

if (stageColor is empty) return emptyList()
... Rest of the method...

2023-05-18 06:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      if (isNotEmpty(color) && BLUE_GREEN_COLORS.stream().anyMatch(expectedColor -> expectedColor.equals(color))) {
can use BLUE_GREEN_COLORS.contains(color)

2023-05-18 08:03 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +      if (isNotEmpty(color) && BLUE_GREEN_COLORS.stream().anyMatch(expectedColor -> expectedColor.equals(color))) {
Done

2023-05-18 08:03 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +          .filter(k8sResourceId -> WORKLOAD_KINDS.contains(k8sResourceId.getKind()) && isNotEmpty(stageColor))
Done

2023-05-18 08:03 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public boolean validateExistingResourceIds(Kubectl client, K8sDelegateTaskParams k8sDelegateTaskParams,
Done

2023-05-18 08:04 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +            resourceIdsToScale.stream()
Done

2023-05-18 08:04 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandlerTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Done

2023-05-18 08:05 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  private ProcessResult executeGetPodsCommand(Kubectl client, K8sDelegateTaskParams k8sDelegateTaskParams,
Done

2023-05-18 08:06 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +          .filter(k8sResourceId
I would need to change all the internal methods in K8sTaskHelperBase to static. So I am preventing that refactoring to not break existing features.

2023-05-18 09:25 UTC, GoelPratyush99 commented
trigger uts

2023-05-18 12:32 UTC, abhinavsingh1196 approved these changes

2023-05-19 05:01 UTC, GoelPratyush99 commented
trigger uts

2023-05-19 08:19 UTC, GoelPratyush99 commented
trigger review

2023-05-19 08:20 UTC, merged