[fix]: [PL-38460]: Updates acl generation to disable redundant acl
harness/harness-core pull request #47907
Opened 2023-05-16 18:53 UTC by ashishsanodia-harness

## Describe your changes
Updates acl generation to disable redundant acl

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-16 19:49 UTC, ashishsanodia-harness commented
trigger uts

2023-05-16 19:49 UTC, ashishsanodia-harness commented
trigger feature-build

2023-05-22 11:22 UTC, ashishsanodia-harness commented
trigger uts

2023-05-22 13:48 UTC, ashishsanodia-harness commented
trigger uts

2023-05-22 15:32 UTC, ashishsanodia-harness commented
trigger feature-build

2023-05-22 19:02 UTC, ashishsanodia-harness commented
trigger uts

2023-05-22 20:02 UTC, ashishsanodia-harness commented
trigger uts

2023-05-24 18:04 UTC, ashishsanodia-harness commented
trigger uts

2023-05-25 05:18 UTC, ashishsanodia-harness commented
trigger messagecheck

2023-05-25 11:16 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907)* status: 29 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 204 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHZRjj34cC7Cm4Ua7m:-NWHZRjk6bYT-rw1rsf1:b-8iscjh) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L204)):*
> ```Java
>     assertThat(enabledAcls).isEqualTo(3);
>     long disabledAcls = acls.stream().filter(acl -> !acl.isEnabled()).count();
>     assertThat(disabledAcls).isEqualTo(1);
> ```

Lets also check which for which ACL record it is disabled.
___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 241 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHZuqGEMSyZ9eMlpZQ:-NWHZuqGEMSyZ9eMlpZR:b-8iscjh) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L241)):*
> ```Java
>     assertThat(enabledAcls).isEqualTo(2);
>     long disabledAcls = acls.stream().filter(acl -> !acl.isEnabled()).count();
>     assertThat(disabledAcls).isEqualTo(2);
> ```

Lets also check which for which ACL record it is disabled.


<!-- Sent from Reviewable.io -->

2023-05-25 12:50 UTC, ankit-harness requested changes
> Reviewed 1 of 15 files at r1, 7 of 16 files at r2, 3 of 4 files at r4, 7 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907)* status: 29 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/build/container/scripts/replace_configs.sh` line 91 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHk1FsAzNGNFcylEqN:-NWHjiT49aPP1q7cNrRQ:bvkix2p) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/build/container/scripts/replace_configs.sh#L91)):*
> ```Shell
> replace_key_value featureFlagConfig.syncFeaturesToCF "$SYNC_FEATURES_TO_CF"
> 
> replace_key_value aclOptimizationConfig.enabled "$ENABLE_ACL_OPTIMIZATION"
> ```

Not required
___
*[`access-control/config/config.yml` line 277 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHjso46G2L4Pewzz5r:-NWHjso46G2L4Pewzz5s:b-d8qqsf) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/config/config.yml#L277)):*
> ```YAML
>   syncFeaturesToCF: false
> 
> aclOptimizationConfig:
> ```

disableRedundantACLs: {DISABLE_REDUNDANT_ACLS:-false}
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHqj5W7MRJrJj-fI4v:-NWHpFM1EjE4ozqmu2WP:b8x1670) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L33)):*
> ```Java
> public class ACLUtils {
>   public static ACL buildACL(String permission, Principal principal, RoleAssignmentDBO roleAssignment,
>       ResourceSelector resourceSelector, boolean isImplicitForScope, boolean permissionApplicableToResource) {
> ```

enabled
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 82 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHrAG19gg2Z84CzncB:-NWHrAG19gg2Z84CzncC:b-uwrg77) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L82)):*
> ```Java
>   }
> 
>   public static boolean permissionApplicableToResource(String permission, String resourceSelector) {
> ```

Move this logic to ACLGeneratorServiceImpl
Use pre computed Map
Use equalsIgnoreCase()
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 177 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHsjH66qXtbuaBh5Md:-NWHsjH66qXtbuaBh5Me:b-ojaq23) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L177)):*
> ```Java
>             if (SERVICE_ACCOUNT.equals(roleAssignment.getPrincipalType())) {
>               acls.add(buildACL(permission, Principal.of(SERVICE_ACCOUNT, principalIdentifier), roleAssignment,
>                   resourceSelector, true, true));
> ```

Lets compute enabled
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/ACLOffset.java` line 35 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHtAFo3bHTpZinBGOU:-NWHtAFo3bHTpZinBGOV:bkicocv) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/ACLOffset.java#L35)):*
> ```Java
> @Entity(value = "aclOffset", noClassnameStored = true)
> @TypeAlias("aclOffset")
> public class ACLOffset implements PersistentEntity {
> ```

ACLOptimizationMigrationOffset
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLOffsetRepository.java` line 19 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHtMLbCCmgOlDv82KA:-NWHtMLbCCmgOlDv82KB:b67f8wv) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLOffsetRepository.java#L19)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class ACLOffsetRepository {
> ```

Cleanup
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 48 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHxQFWEh6tvGLh1XmY:-NWHxQFWEh6tvGLh1XmZ:b-j0uzm) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L48)):*
> ```Java
>   public static final String REFERENCE_TIMESTAMP = "000000000000000000000000";
>   private static final String DEBUG_MESSAGE = "[DisableRedundantACLJob] ";
>   private String offset = REFERENCE_TIMESTAMP;
> ```

This should be local variable
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 126 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHugDW4My519c3urfk:-NWHugDW4My519c3urfl:b7k89c) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L126)):*
> ```Java
>     Query query = new Query();
>     query.with(Sort.by(ASC, ACLKeys.id)).limit(1);
>     ACLOffset aclOffset = mongoTemplate.findOne(query, ACLOffset.class);
> ```

Separate Query
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 126 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHuq4P6tsoZLR8Qc5C:-NWHuq4P6tsoZLR8Qc5D:b-mlcduw) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L126)):*
> ```Java
>     Query query = new Query();
>     query.with(Sort.by(ASC, ACLKeys.id)).limit(1);
>     ACLOffset aclOffset = mongoTemplate.findOne(query, ACLOffset.class);
> ```

offset
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DisableRedundantACLForRoleAssignmentMigration.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHu3o_6CNtFNSbOx3n:-NWHu3o_6CNtFNSbOx3o:byp18fd) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DisableRedundantACLForRoleAssignmentMigration.java#L31)):*
> ```Java
> @Singleton
> @OwnedBy(PL)
> public class DisableRedundantACLForRoleAssignmentMigration implements NGMigration {
> ```

Remove


<!-- Sent from Reviewable.io -->

2023-05-30 18:53 UTC, ashishsanodia-harness commented
trigger uts

2023-05-30 19:20 UTC, ashishsanodia-harness commented
trigger uts

2023-05-31 03:52 UTC, ashishsanodia-harness commented
*[`access-control/config/config.yml` line 277 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHjso46G2L4Pewzz5r:-NWjvyLj4E5IecFA5sTz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/config/config.yml#L277)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

disableRedundantACLs: {DISABLE_REDUNDANT_ACLS:-false}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:53 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHqj5W7MRJrJj-fI4v:-NWjw-Ow637AJgIM59Ns:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

enabled
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:53 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 82 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHrAG19gg2Z84CzncB:-NWjw5zJD30RNsafzAJY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L82)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Move this logic to ACLGeneratorServiceImpl
Use pre computed Map
Use equalsIgnoreCase()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:54 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 177 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHsjH66qXtbuaBh5Md:-NWjwGfAAcVEDOamzJfD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L177)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets compute enabled
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:54 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 204 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHZRjj34cC7Cm4Ua7m:-NWjwKco7xJgMCBAZs6A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L204)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets also check which for which ACL record it is disabled.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:54 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 241 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHZuqGEMSyZ9eMlpZQ:-NWjwM5326HYKoyVTk_u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L241)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets also check which for which ACL record it is disabled.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:55 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/ACLOffset.java` line 35 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHtAFo3bHTpZinBGOU:-NWjwUX72tyvV7lBhPgx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/ACLOffset.java#L35)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

ACLOptimizationMigrationOffset
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:55 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 48 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHxQFWEh6tvGLh1XmY:-NWjwY3hC2sMv7VOeo1Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L48)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should be local variable
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:55 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 126 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHugDW4My519c3urfk:-NWjw_800yWVJ5xiU7if:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L126)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Separate Query
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:55 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 126 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHuq4P6tsoZLR8Qc5C:-NWjwbUEC1dNHiRQ91co:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L126)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

offset
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:55 UTC, ashishsanodia-harness commented
*[`access-control/build/container/scripts/replace_configs.sh` line 91 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHk1FsAzNGNFcylEqN:-NWjwdlL3MMBrXFeilbX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/build/container/scripts/replace_configs.sh#L91)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Not required
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:56 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLOffsetRepository.java` line 19 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHtMLbCCmgOlDv82KA:-NWjwhZJ4mrjtp9SdJkr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLOffsetRepository.java#L19)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Cleanup
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 03:56 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DisableRedundantACLForRoleAssignmentMigration.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHu3o_6CNtFNSbOx3n:-NWjwj8bBars8c4ow6zN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DisableRedundantACLForRoleAssignmentMigration.java#L31)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 07:08 UTC, ashishsanodia-harness commented
trigger uts

2023-05-31 07:21 UTC, ashishsanodia-harness commented
trigger uts

2023-05-31 16:11 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907)* status: 34 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 82 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHrAG19gg2Z84CzncB:-NWmVVn71-NUhfZCKfJp:bw9a2uz) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L82)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Move checkResourceSelectorApplicableToResourceType to io.harness.accesscontrol.resources.resourcegroups.ResourceSelector
We have define static method.
Also we name it like validateResourceType
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 135 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWmWrV49ugZ6Pw0v7o7:-NWmWrV49ugZ6Pw0v7o8:bduqxe6) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L135)):*
> ```Java
>         for (ResourceSelector resourceSelector : resourceSelectors) {
>           if (disableRedundantACLs) {
>             isResourceSelectorApplicableToResourceType = checkResourceSelectorApplicableToResourceType(
> ```

change  isResourceSelectorApplicableToResourceType to isResourceTypeApplicableToPermission


<!-- Sent from Reviewable.io -->

2023-05-31 17:03 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907)* status: 34 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 127 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWmkq9O4dm3wBMmgjjH:-NWmkq9O4dm3wBMmgjjI:bx4bmsi) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L127)):*
> ```Java
> 
>   private void updateOffset(String lastProcessedAclId) {
>     mongoTemplate.remove(new Query(), ACLOptimizationMigrationOffset.class);
> ```

This operation should be in transaction else we can lose offset if remove succeds but save fails.


<!-- Sent from Reviewable.io -->

2023-06-02 03:29 UTC, ashishsanodia-harness commented
trigger uts

2023-06-02 03:30 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 135 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWmWrV49ugZ6Pw0v7o7:-NWu8vcm4_nX1B6DI_YN:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L135)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change  isResourceSelectorApplicableToResourceType to isResourceTypeApplicableToPermission
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-02 03:30 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 33 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWrBJyo6QvCNNovdOck:-NWu8z3J2ejh38C1wJlq:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

final?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-06-02 03:35 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/test/java/io/harness/accesscontrol/persistence/ACLDAOImplTest.java` line 66 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWmcToS7O30_op9fJ1o:-NWuA2ma2y7Ta7ZNgyp0:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/libs/core/src/test/java/io/harness/accesscontrol/persistence/ACLDAOImplTest.java#L66)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Move aclDaoImpl = new ACLDAOImpl(aclRepository, scopeLevels, false); to make it readable and usage of boolean is in context of test.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-06-02 03:35 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java` line 127 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWmkq9O4dm3wBMmgjjH:-NWuA81cE4rcOpDV81vO:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/DisableRedundantACLJob.java#L127)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This operation should be in transaction else we can lose offset if remove succeds but save fails.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-06-02 03:35 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 82 at r6](https://reviewable.io/reviews/harness/harness-core/47907#-NWHrAG19gg2Z84CzncB:-NWuAAsL2IXMnKZ228Qg:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/eabfc3a396cd849054eccbd728d02ed87a128c85/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L82)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Move checkResourceSelectorApplicableToResourceType to io.harness.accesscontrol.resources.resourcegroups.ResourceSelector
We have define static method.
Also we name it like validateResourceType
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-06-02 03:35 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWrBBpL-5LnRbqbqqfC:-NWu907xB0Vi28dZ9i4o:b-1p07em) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L59)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is this method needed?
</blockquote></details>

This is to refresh in memory permission data when permission management job runs after this InMemoryRepository loads data.


<!-- Sent from Reviewable.io -->

2023-06-02 05:36 UTC, Jimit09Gandhi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 15 files at r1, 3 of 16 files at r2, 1 of 11 files at r6, 23 of 29 files at r7, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907#-:-NWuaonH4EoWW8Em4E4O:bnfp4nl)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-02 06:07 UTC, ankit-harness requested changes
> Reviewed 6 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWrBBpL-5LnRbqbqqfC:-NWuhfDY11ET9pmjbEB3:b-405nrd) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L59)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

This is to refresh in memory permission data when permission management job runs after this InMemoryRepository loads data.
</blockquote></details>

This logic isn't clear. Lets discuss 


<!-- Sent from Reviewable.io -->

2023-06-02 07:02 UTC, harshjain12 commented
trigger ut8

2023-06-02 10:05 UTC, ashishsanodia-harness commented
trigger uts

2023-06-02 10:07 UTC, ashishsanodia-harness commented
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/47907#-NWrBBpL-5LnRbqbqqfC:-NWvZk778r8VB_CPwhJR:b-uzkf1f) ([raw file](https://github.com/harness/harness-core/blob/60938549994d239ff24aea09425f49385c8edd47/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L59)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This logic isn't clear. Lets discuss 
</blockquote></details>

Removed explicit refresh as discussed


<!-- Sent from Reviewable.io -->

2023-06-02 11:21 UTC, ashishsanodia-harness commented
trigger uts

2023-06-02 11:36 UTC, ashishsanodia-harness commented
trigger ut8

2023-06-02 12:49 UTC, ashishsanodia-harness commented
Unrelated DynatraceDataCollectionDSLTest is broken

2023-06-02 14:41 UTC, ashishsanodia-harness commented
trigger ut2

2023-06-02 16:20 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907#-:-NWwuHWW46Y1F486z_1Z:bnfp4nl)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-03 05:37 UTC, Jimit09Gandhi approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47907)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-03 09:58 UTC, merged