feat: [CDS-56738]: completed the K8s BG Stage Scale down step
harness/harness-core pull request #47989
Opened 2023-05-17 18:46 UTC by GoelPratyush99

## Describe your changes
This PR contains the complete delegate side changes for K8s Blue Green Stage Scale Down Step. This will Scale down the workload present in stage environment. This step does not have any outcome and using release name as input to process the release history and bring down stage environemnt.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-18 06:22 UTC, abhinavsingh1196 approved these changes

2023-05-18 07:14 UTC, namantalaycha10 approved these changes

2023-05-18 07:20 UTC, abosii-harness requested changes
If we're good with scale down, should we mark tasktype K8S_BLUE_GREEN_STAGE_SCALE_DOWN_TASK as supported?

2023-05-18 07:20 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGStageScaleDownStep.java
> +            .useK8sApiForSteadyStateCheck(cdStepHelper.shouldUseK8sApiForSteadyStateCheck(accountId))
Do we need this FF? We should not do steady state check

2023-05-18 09:34 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGStageScaleDownStep.java
> +            .useK8sApiForSteadyStateCheck(cdStepHelper.shouldUseK8sApiForSteadyStateCheck(accountId))
Removed it. We don't require this FF

2023-05-18 09:36 UTC, GoelPratyush99 reviewed
sure merge it to this PR

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47989#-:-NViCecd90CKjLcf1O5o:b-w4wgmy)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-19 07:51 UTC, GoelPratyush99 commented
trigger uts

2023-05-19 07:56 UTC, abosii-harness approved these changes

2023-05-19 08:23 UTC, GoelPratyush99 commented
trigger uts

2023-05-19 09:38 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGStageScaleDownStep.java
> +            .taskType(K8sTaskType.BLUE_GREEN_STAGE_SCALE_DOWN)
nit: we can have same naming convention for this feature, K8S_BG_STAGE_SCALE_COMMAND_NAME and  BLUE_GREEN_STAGE_SCALE_DOWN feels like two things for same.

2023-05-19 09:56 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47989)* status: 6 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-19 10:28 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGStageScaleDownStep.java
> +            .taskType(K8sTaskType.BLUE_GREEN_STAGE_SCALE_DOWN)
I think that it's understandable. We have been following similar naming convention for all the steps "Apply", "Blue Green" etc.

2023-05-19 10:30 UTC, GoelPratyush99 commented
trigger review

2023-05-19 10:30 UTC, GoelPratyush99 commented
trigger messagecheck

2023-05-19 10:33 UTC, merged