feat: [PLG-2131]: aws marketplace provision licenses
harness/harness-core pull request #48055
Opened 2023-05-18 21:12 UTC by mtran7

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/48055)

2023-05-18 21:13 UTC, mtran7 commented
trigger uts

2023-05-19 04:39 UTC, mtran7 commented
trigger uts

2023-05-19 13:18 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      if (TEAM.equals(tempPlan) || TEAM_SHORT.equals(tempPlan)) {
Any specific reason that we start to support abbreviation of Team and enterprise plan? Can't we stick to the formal name of it?

2023-05-19 13:19 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      if (TEAM.equals(tempPlan) || TEAM_SHORT.equals(tempPlan)) {
It may bring more scenario to handle the abbreviation and long term we may need to maintain more cases.

2023-05-19 13:26 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    log.info("DTO: {}", dto);
Any reason that we need to log DTO here?

2023-05-19 13:50 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    log.info("accountId: {}", accountId);
same here, more context please

2023-05-19 13:52 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    if (marketPlace == null) {
Suggest to separate validation steps in a standalone method

2023-05-19 13:54 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java
> +
remove the unused comment if necessary

2023-05-19 13:57 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
>    private static final String TEAM = "TEAM";
We already have edition defined in 920-ng-signup, please use the standard names for unification purpose

2023-05-19 13:59 UTC, Xin-Harness requested changes

2023-05-19 13:59 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +    String HARNESS_TEST_2_PRODUCT_CODE = "9g3jcw6iic4tpylipcti8vwcx";
specific reason for hard coded string?

2023-05-19 14:16 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +      if (TEAM.equals(tempPlan) || TEAM_SHORT.equals(tempPlan)) {
The dimension passed has a character limit. SalesOps may use for example, CCM_EN_PRMR_250K. The "EN" is for enterprise

2023-05-19 14:21 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java
> +    String HARNESS_TEST_2_PRODUCT_CODE = "9g3jcw6iic4tpylipcti8vwcx";
Hardcoded string is to test https://aws.amazon.com/marketplace/pp/prodview-eb54fberbyj2c listing. The other products are now live and have their prices reverted back to the original which is too costly to test with. This hard-coded product code will be removed once we finish testing/enable in Prod

2023-05-19 16:31 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    log.info("DTO: {}", dto);
Will delete after bug bash. Added comment

2023-05-19 16:31 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    log.info("accountId: {}", accountId);
Will delete after bug bash. Added comment

2023-05-19 16:33 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    log.info("Info for user: {}", user);
Removing

2023-05-19 16:33 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    log.info("accountId: {}", accountId);
Removing

2023-05-19 16:47 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/resources/UserResourceNG.java
> +    if (marketPlace == null) {
Preferably would keep as it all pertains to 
1. Create a user (1)
2. Verify the marketPlaceToken is correct
3. Get the claim details from the JWT Token
4. Get the marketPlaceID from the claim (2)
5. Get userInvite from the claim (3)
6. Then set up an account (line 253) for the user, userInvite, and marketplace

2023-05-19 19:04 UTC, mtran7 commented on 400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java
> +    if (StringUtils.isNotBlank(dimension) && dimension.split("_").length >= 3 && plan != null && quantity != null) {
MINIMUM_DIMENSION_V2_LENGTH

2023-05-19 19:12 UTC, neelam-harness requested changes
> Reviewed 5 of 14 files at r1, 1 of 4 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48055)* status: 14 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 659 at r3](https://reviewable.io/reviews/harness/harness-core/48055#gh-1198992691:-NVpHN9K2-yMBtcM15ox:b-3kqcyy) ([raw file](https://github.com/harness/harness-core/blob/5bcbe3b8c539ccdb3713231e2b2dfc8bfab91918/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L659)):*
<details><summary><i>Previously, mtran7 wrote…</i></summary><blockquote>

Hardcoded string is to test https://aws.amazon.com/marketplace/pp/prodview-eb54fberbyj2c listing. The other products are now live and have their prices reverted back to the original which is too costly to test with. This hard-coded product code will be removed once we finish testing/enable in Prod
</blockquote></details>

Can we add a comment with TODO jira for this removal for better tracking this ?
___
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 246 at r3](https://reviewable.io/reviews/harness/harness-core/48055#gh-1198985160:-NVpLDHx5490nyQBP_0d:buc47um) ([raw file](https://github.com/harness/harness-core/blob/5bcbe3b8c539ccdb3713231e2b2dfc8bfab91918/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L246)):*
<details><summary><i>Previously, mtran7 wrote…</i></summary><blockquote>

Preferably would keep as it all pertains to 
1. Create a user (1)
2. Verify the marketPlaceToken is correct
3. Get the claim details from the JWT Token
4. Get the marketPlaceID from the claim (2)
5. Get userInvite from the claim (3)
6. Then set up an account (line 253) for the user, userInvite, and marketplace
7. Set accountId details to user & marketplace once created
</blockquote></details>

This method has become very long, I'd also recommend to break it into smaller constructs as Xin suggested. Here is nice explanation on the method length: https://softwareengineering.stackexchange.com/questions/133404/what-is-the-ideal-length-of-a-method-for-you 
___
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 684 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpM1Dd316BAaPyns-F:-NVpM1Dd316BAaPyns-G:b-ty8pn2) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L684)):*
> ```Java
>           .build();
>     } catch (Exception e) {
>       throw new InvalidRequestException("Unable to convert Marketplace Request to User", e);
> ```

please also log the exception.
___
*[`400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java` line 378 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpMOve2T4rti3sE8WA:-NVpMOve2T4rti3sE8WB:b-5m2ugt) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java#L378)):*
> ```Java
> 
>   private String getUTMUrlParams(MarketPlaceConfig marketPlaceConfig, String productCode) {
>     // TODO: Add for CE (Chaos)
> ```

please add the ticket link as well.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 351 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpN0XMCz1bG9YEW-zC:-NVpN0XMCz1bG9YEW-zD:b4v31ph) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L351)):*
> ```Java
>   private static final String CI = "CI";
>   private static final String FF = "FF";
>   private static final String CCM = "CCM";
> ```

The used terminology for CCM is `CE`https://github.com/harness/harness-core/blob/739da1dd02d0d90b901ddc6fcb770241ce98cb45/970-ng-commons/src/main/java/io/harness/entities/ModuleType.java#L32 
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 355 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpMfzpDanR6Ga2Ki5o:-NVpMfzpDanR6Ga2Ki5p:b-x3u25b) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L355)):*
> ```Java
>   private static final String SRM = "SRM";
> 
>   /**
> ```

Can we not use ModuleType here ? https://github.com/harness/harness-core/blob/739da1dd02d0d90b901ddc6fcb770241ce98cb45/970-ng-commons/src/main/java/io/harness/entities/ModuleType.java 
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 4373 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpNNGZ-P5OLGhkzvZ0:-NVpNNGZ-P5OLGhkzvZ1:b7xt6fv) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L4373)):*
> ```Java
>               .build()));
>       log.info("CEModuleLicense {} created", response.getId());
>       log.info("CEModuleLicense {} response", response);
> ```

Nit: Logs can be merged like this: 



_Code snippet:_
```Java
 log.info("CEModuleLicense {} created with response {}", response.getId(), response);
```
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 4400 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpNklkA0DZO6xUEWO7:-NVpNklkA0DZO6xUEWO8:b-ck9aog) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L4400)):*
> ```Java
> 
>       log.info("CFModuleLicense {} created", response.getId());
>       log.info("CFModuleLicense {} response", response);
> ```

Nit: same here for merging the logs
___
*[`400-rest/src/main/java/software/wings/service/intfc/AwsMarketPlaceApiHandler.java` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpO7NdDFj1XYgDZD5w:-NVpO7NdDFj1XYgDZD5x:b-3kup04) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/intfc/AwsMarketPlaceApiHandler.java#L20)):*
> ```Java
>   Response processAWSMarktPlaceOrder(String token);
> 
>   boolean isDimensionV2Provisionable(String dimension, Integer quantity);
> ```

let's add java docs here to explain what this method does, new reader won't have context on what this is and is generally a good practice to add docs in the interfaces
___
*[`920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java` line 76 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpOgv53oPWm-E8-508:-NVpOgv53oPWm-E8-509:b4pqkgh) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java#L76)):*
> ```Java
> 
>   /**
>    * Follows the "complete marketplace sign up" path
> ```

Let's add some more explanation on what this API is for.
___
*[`920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java` line 209 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpP8ghB4EJTWbJ1Iqg:-NVpP8ghB4EJTWbJ1Iqh:bb4k5or) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java#L209)):*
> ```Java
>       if (e.getMessage().contains("User with this email is already registered")) {
>         sendFailedTelemetryEvent(email, dto.getUtmInfo(), e, account, "Create Marketplace user and complete signup");
>         throw new InvalidRequestException("Email is already signed up", ErrorCode.USER_ALREADY [...]

2023-05-19 21:54 UTC, mtran7 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48055)* status: 14 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 351 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpN0XMCz1bG9YEW-zC:-NVpxPjzDwpVr0d80w8C:bkf6jor) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L351)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

The used terminology for CCM is `CE`https://github.com/harness/harness-core/blob/739da1dd02d0d90b901ddc6fcb770241ce98cb45/970-ng-commons/src/main/java/io/harness/entities/ModuleType.java#L32 
</blockquote></details>

This had been in flux many times as teams were deciding whether chaos engineering was CE. We chose to stick with CCM. Same thing happened with Feature Flags being Continuous Features previously.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 355 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpMfzpDanR6Ga2Ki5o:-NVpxp2I8_HIwUM14ak5:b-d7ep9m) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L355)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Can we not use ModuleType here ? https://github.com/harness/harness-core/blob/739da1dd02d0d90b901ddc6fcb770241ce98cb45/970-ng-commons/src/main/java/io/harness/entities/ModuleType.java 
</blockquote></details>

When splitting the dimension string, we won't be able to cast as ModuleType so redefined as string 


<!-- Sent from Reviewable.io -->

2023-05-19 21:55 UTC, Xin-Harness submitted a review, later dismissed

2023-05-19 23:40 UTC, mtran7 commented
trigger uts

2023-05-20 17:44 UTC, sahithikolichala approved these changes

2023-05-21 02:09 UTC, mtran7 commented
trigger uts

2023-05-22 19:57 UTC, mtran7 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48055)* status: 14 file(s) to review. 1 change requests. 15. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/48055#gh-1198989661:-NW40WajA1aysnixTYoO:b-nofk9q) ([raw file](https://github.com/harness/harness-core/blob/5bcbe3b8c539ccdb3713231e2b2dfc8bfab91918/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L108)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

We already have edition defined in 920-ng-signup, please use the standard names for unification purpose
</blockquote></details>

Created follow up ticket https://harness.atlassian.net/browse/PLG-2388
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 659 at r3](https://reviewable.io/reviews/harness/harness-core/48055#gh-1198992691:-NVq0db05_dxbMq9LIua:b9t3qni) ([raw file](https://github.com/harness/harness-core/blob/5bcbe3b8c539ccdb3713231e2b2dfc8bfab91918/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L659)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Can we add a comment with TODO jira for this removal for better tracking this ?
</blockquote></details>

Done https://harness.atlassian.net/browse/PLG-2386
___
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 246 at r3](https://reviewable.io/reviews/harness/harness-core/48055#gh-1198985160:-NVq0Adv2GngtjhMOnum:bbmkhz6) ([raw file](https://github.com/harness/harness-core/blob/5bcbe3b8c539ccdb3713231e2b2dfc8bfab91918/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L246)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

This method has become very long, I'd also recommend to break it into smaller constructs as Xin suggested. Here is nice explanation on the method length: https://softwareengineering.stackexchange.com/questions/133404/what-is-the-ideal-length-of-a-method-for-you 
</blockquote></details>

Took out the validation user piece into a separate function validatedUserFromMarketplaceRequest
___
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 684 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpM1Dd316BAaPyns-F:-NVq08q9AaQ1D2r7yDLe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L684)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

please also log the exception.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java` line 233 at r3](https://reviewable.io/reviews/harness/harness-core/48055#gh-1198987019:-NVq-kbR61JqrK0kFApC:bjq6y9n) ([raw file](https://github.com/harness/harness-core/blob/5bcbe3b8c539ccdb3713231e2b2dfc8bfab91918/400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java#L233)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

remove the unused comment if necessary
</blockquote></details>

This is a valid todo comment. Created a ticket in the epic: https://harness.atlassian.net/browse/PLG-2385
___
*[`400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java` line 378 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpMOve2T4rti3sE8WA:-NVq-eKp4m_wWS_6aL8v:b-imd1m7) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/impl/AwsMarketPlaceApiHandlerImpl.java#L378)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

please add the ticket link as well.
</blockquote></details>

It is added into the Epic: https://harness.atlassian.net/browse/PLG-2384
___
*[`400-rest/src/main/java/software/wings/service/intfc/AwsMarketPlaceApiHandler.java` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpO7NdDFj1XYgDZD5w:-NW41Bk409IICbxUxdba:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/400-rest/src/main/java/software/wings/service/intfc/AwsMarketPlaceApiHandler.java#L20)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

let's add java docs here to explain what this method does, new reader won't have context on what this is and is generally a good practice to add docs in the interfaces
</blockquote></details>

Done.
___
*[`920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java` line 76 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpOgv53oPWm-E8-508:-NW41Cwt62jI1j0lJzjH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java#L76)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Let's add some more explanation on what this API is for.
</blockquote></details>

Done.
___
*[`920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java` line 209 at r5](https://reviewable.io/reviews/harness/harness-core/48055#-NVpP8ghB4EJTWbJ1Iqg:-NW41EOfErlNYkZjsMNn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/323cd3f885e837f75aab03eaac5c63afb3ffa8c3/920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java#L209)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Let's log the error message here as well before throwing the exception.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-22 20:27 UTC, neelam-harness approved these changes

2023-05-22 20:27 UTC, neelam-harness approved these changes

2023-05-22 20:28 UTC, mtran7 commented
trigger review

2023-05-22 20:29 UTC, merged