[feat]: [CDS-58165]: upsert api for ServiceOverride V2
harness/harness-core pull request #48100
Opened 2023-05-19 10:54 UTC by tchaurasiya

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-20 04:45 UTC, tchaurasiya commented
trigger review

2023-05-20 04:49 UTC, tchaurasiya commented
trigger uts

2023-05-20 08:21 UTC, yogesh-chauhan requested changes

2023-05-20 08:21 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +      existingVars.removeIf(ngVariable -> requestedVariablesName.contains(ngVariable.getName()));
if the number of variables is high, its more efficient to just use a map instead of list ?

2023-05-20 09:38 UTC, tchaurasiya commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 287 at r4](https://reviewable.io/reviews/harness/harness-core/48100#gh-1199578948:-NVsWX5L5wMn_ClVdChv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e8cd951dcd1876fc3759b669f54221f09df8816/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L287)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if the number of variables is high, its more efficient to just use a map instead of list ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-20 16:57 UTC, tchaurasiya commented
trigger uts

2023-05-20 17:13 UTC, tchaurasiya commented
trigger uts

2023-05-21 05:35 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48100)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-21 09:36 UTC, inderschera approved these changes
> Reviewed 2 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48100)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-05-21 09:37 UTC, tchaurasiya commented
trigger review

2023-05-21 10:00 UTC, merged