fix: [CDS-69576]: Remove "Java" logs when Yaml processing fails
harness/harness-core pull request #48112
Opened 2023-05-19 14:48 UTC by alebuh

## Describe your changes
Simplifying logs by removing
 "Java" parts from it
If Secret yaml is invalid output will look like this:
<img width="1152" alt="Screenshot 2023-05-23 at 11 21 22" src="https://github.com/harness/harness-core/assets/98389528/b291c0f9-8b0b-41b0-9dff-61bcc545d883">
If any resource is any other kind it will print a more detailed explanation:
<img width="1147" alt="Screenshot 2023-05-23 at 11 15 19" src="https://github.com/harness/harness-core/assets/98389528/f979c1db-6179-4dd2-86a7-d0b0752e1993">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/48112)

2023-05-22 06:52 UTC, alebuh commented
trigger uts

2023-05-22 07:37 UTC, abhinavsingh1196 submitted a review, later dismissed

2023-05-22 07:47 UTC, abosii-harness requested changes

2023-05-22 07:47 UTC, abosii-harness commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/KubernetesResourceTest.java
> +        + "      template:\n"
I believe we should show the full stack, as this error doesn't show the exact what is wrong here

2023-05-22 07:48 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +          ex instanceof ConstructorException && !"Secret".equals(this.resourceId.getKind())
equalsIgnoreCase just in case

2023-05-22 10:40 UTC, alebuh commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +          ex instanceof ConstructorException && !"Secret".equals(this.resourceId.getKind())
done

2023-05-22 10:40 UTC, alebuh commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/KubernetesResourceTest.java
> +        + "      template:\n"
done

2023-05-22 13:17 UTC, alebuh commented
trigger uts

2023-05-23 04:16 UTC, GoelPratyush99 approved these changes

2023-05-23 06:55 UTC, alebuh commented
trigger ut5

2023-05-26 15:38 UTC, abosii-harness approved these changes

2023-05-26 19:41 UTC, acasian-harness commented
@alebuh do we need to consider the same for configMap?

2023-05-26 19:41 UTC, acasian-harness submitted a review, later dismissed

2023-05-26 19:51 UTC, acasian-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +          ex instanceof ConstructorException && !"Secret".equalsIgnoreCase(this.resourceId.getKind())
nit: we have `io.harness.k8s.model.Secret` kind constant

2023-05-29 06:10 UTC, alebuh commented
trigger uts

2023-05-29 06:11 UTC, abosii-harness approved these changes

2023-05-29 08:25 UTC, alebuh commented
trigger uts

2023-05-29 09:25 UTC, harshjain12 commented
trigger ut0

2023-05-29 11:17 UTC, abhinavsingh1196 approved these changes

2023-05-29 11:24 UTC, alebuh commented
trigger review

2023-05-29 11:24 UTC, alebuh commented
trigger review

2023-05-29 11:27 UTC, merged