feat:[CDS-69416]: adding auto approval in approval step
harness/harness-core pull request #48220
Opened 2023-05-23 07:16 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-23 07:23 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/AutoApproval.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6UIOU4Vj5JUVjAwVQ:-NW6UIOV0Ca3gl9NDkmf:bl9aiv8) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/AutoApproval.java#L29)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @RecasterAlias("io.harness.steps.approval.step.harness.beans.AutoApproval")
> public class AutoApproval {
> ```

should this class be called "AutoApprovalParams" or "AutoApprovalDetails" etc?


<!-- Sent from Reviewable.io -->

2023-05-23 07:24 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6UVeiDqLfwHCpTUNH:-NW6UVeiDqLfwHCpTUNI:b-xfa782) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L51)):*
> ```Java
> @Slf4j
> public class HarnessApprovalStepFilterJsonCreatorV2 extends GenericStepPMSFilterJsonCreatorV2 {
>   private static String DEFAULT_TIMEOUT = "10m";
> ```

A better naming convention would be "DEFAULT_TIMEOUT_IN_MINUTES" or similar.


<!-- Sent from Reviewable.io -->

2023-05-23 07:25 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6Ur27Ba-CDhnlBOKD:-NW6Ur27Ba-CDhnlBOKE:b-ti112t) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L103)):*
> ```Java
>     return FilterCreationResponse.builder().build();
>   }
>   private void validateAutoApprovalTimeDuration(
> ```

blank line missing


<!-- Sent from Reviewable.io -->

2023-05-23 07:26 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6UxC8APYYE_jX8G-i:-NW6UxC8APYYE_jX8G-j:bjj158x) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L114)):*
> ```Java
>   }
> 
>   private Long getDurationFromTimeStamp(String scheduledDeadline) {
> ```

This method name is ambiguous. This method is tightly coupled to scheduledDeadline parameter so name of the method should also suggest the same.


<!-- Sent from Reviewable.io -->

2023-05-23 07:26 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6V5v6E704w0q6badF:-NW6V5v6E704w0q6badG:bovsp72) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L120)):*
> ```Java
>       endTime = parseTimestamp(scheduledDeadline);
>     } catch (Exception e) {
>       throw new InvalidRequestException("Invalid time stamp format for schedule deadline field for auto approval");
> ```

log exception


<!-- Sent from Reviewable.io -->

2023-05-23 07:26 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6VB0x37-RzrnziZhA:-NW6VB0x37-RzrnziZhB:b-ti112t) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L130)):*
> ```Java
>         : timeout.getValue().getTimeoutInMillis();
>   }
>   private static LocalDateTime parseTimestamp(String timestampString) {
> ```

blank line missing


<!-- Sent from Reviewable.io -->

2023-05-23 07:27 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6VERh6zZXPa6nP4tu:-NW6VERh6zZXPa6nP4tv:blbp268) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L133)):*
> ```Java
>     DateTimeFormatter formatter = new DateTimeFormatterBuilder()
>                                       .parseCaseInsensitive()
>                                       .appendPattern("yyyy-MM-dd hh:mm a")
> ```

these date formats should come from a central location such that everybody using timestamps can refer same format for all same use-cases.


<!-- Sent from Reviewable.io -->

2023-05-23 07:27 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6VMwGAlktIc4FYptf:-NW6VMwGAlktIc4FYptg:bwugsd1) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L138)):*
> ```Java
>   }
> 
>   private static long calculateDurationInMillis(LocalDateTime startTime, LocalDateTime endTime) {
> ```

why is it static?


<!-- Sent from Reviewable.io -->

2023-05-23 08:14 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 445 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6ezL220eEBTseEHyN:-NW6ezL220eEBTseEHyO:bwpfvpl) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L445)):*
> ```Java
>     List<String> rejectedApprovalIds =
>         findAllPreviousWaitingApprovals(accountId, orgId, projectId, pipelineId, approvalKey, ambiance);
>     final long[] cnt = {0};
> ```

whats use-case for it?


<!-- Sent from Reviewable.io -->

2023-05-23 08:14 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 437 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6f31N0O8jKEKV_WoJ:-NW6f31N0O8jKEKV_WoK:b2of5de) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L437)):*
> ```Java
>       return;
>     }
>     Ambiance ambiance = instance.getAmbiance();
> ```

I see that all these declared fields are just use once or twice. I think instead of declaring fields, these can be referred directly wherever required.


<!-- Sent from Reviewable.io -->

2023-05-23 08:15 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 462 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fDK-ETeBeyA1A0jc:-NW6fDK-ETeBeyA1A0jd:b-mt5yat) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L462)):*
> ```Java
>       return HarnessApprovalInstanceAuthorizationDTO.builder()
>           .authorized(false)
>           .reason("You have already approved/rejected the pipeline")
> ```

shouldn't it simply be : "Pipeline already approved/rejected" or "Pipeline already approved/rejected by the user" etc. I guess we shouldn't use "You" etc in such messages.


<!-- Sent from Reviewable.io -->

2023-05-23 08:17 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fjql4fVBHGUBhLrx:-NW6fjql4fVBHGUBhLry:b-h748ck) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L132)):*
> ```Java
>       Ambiance ambiance, StepElementParameters stepParameters, Map<String, ResponseData> responseDataMap) {
>     try {
>       if (responseDataMap.get(TIMEOUT_DATA) instanceof AsyncTimeoutResponseData) {
> ```

what if responseDataMap.get(TIMEOUT_DATA) is null?


<!-- Sent from Reviewable.io -->

2023-05-23 08:17 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fohgAxma4XWOSJIC:-NW6fohgAxma4XWOSJID:b7wbfep) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L179)):*
> ```Java
>     Optional<UserInfo> userOptional = CGRestUtils.getResponse(userClient.getUserById(userId));
> 
>     EmbeddedUser user = EmbeddedUser.builder().name("Unknown").email("Unknown").build();
> ```

remove hardcoding of strings.


<!-- Sent from Reviewable.io -->

2023-05-23 08:18 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fxRf6phgidIOkh1-:-NW6fxRf6phgidIOkh10:b-cbl4cm) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L225)):*
> ```Java
>   }
> 
>   private static LocalDateTime parseTimestamp(String timestampString) {
> ```

this is repeated code


<!-- Sent from Reviewable.io -->

2023-05-23 08:50 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/48220#-NW6ms0u8O506OdUwBfT:-NW6ms0u8O506OdUwBfU:b-o4ukva) ([raw file](https://github.com/harness/harness-core/blob/a5b1fb8b555af9f4dfdae331121c4e7f321dc644/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L51)):*
> ```Java
> @Slf4j
> public class HarnessApprovalStepFilterJsonCreatorV2 extends GenericStepPMSFilterJsonCreatorV2 {
>   private static String DEFAULT_TIMEOUT = "10m";
> ```

a better naming convention : "DEFAULT_TIMEOUT_IN_MINUTES", also why is it string?


<!-- Sent from Reviewable.io -->

2023-05-23 18:35 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8t9Jv2rs72h1NEJY-:-NW8t9Jw1eNpC2Sz2w6c:b-ti112t) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L49)):*
> ```Java
>   private final long DEFAULT_TIMEOUT_IN_MILLISECONDS = 600000;
>   @Inject private ApprovalStepHelper approvalStepHelper;
>   @Override
> ```

blank line missing


<!-- Sent from Reviewable.io -->

2023-05-23 18:39 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8uB0jEq1cNcEgRmqC:-NW8uB0jEq1cNcEgRmqD:bjtkecn) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java#L22)):*
> ```Java
> public class ApprovalStepHelper {
>   public Long getTotalDurationWRTCurrentTimeFromTimeStamp(String timestamp) {
>     LocalDateTime startTime = LocalDateTime.now();
> ```

This gets affected by TZ, are we taking care of it?


<!-- Sent from Reviewable.io -->

2023-05-23 18:40 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8uNgMCmS6XlRXo_x2:-NW8uNgMCmS6XlRXo_x3:b-ap9r7q) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java#L33)):*
> ```Java
>   }
> 
>   public LocalDateTime parseTimestamp(String timestampString) {
> ```

why is it public?


<!-- Sent from Reviewable.io -->

2023-05-23 18:47 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8vqrz0EKuMH6BON-J:-NW8vqrz0EKuMH6BON-K:b-38wufw) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L107)):*
> ```Java
>           StepSpecTypeConstants.JIRA_APPROVAL, StepSpecTypeConstants.CUSTOM_APPROVAL));
>   @Inject private PmsEngineExpressionService pmsEngineExpressionService;
>   @Inject private UserClient userClient;
> ```

why is this injected directly while userGroupClient is injected via constructor?


<!-- Sent from Reviewable.io -->

2023-05-23 18:52 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 477 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8xE5q8WlPBP_e7zHv:-NW8xE5q8WlPBP_e7zHw:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L477)):*
> ```Java
>       return HarnessApprovalInstanceAuthorizationDTO.builder()
>           .authorized(false)
>           .reason("You are not authorized to approve/reject")
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-05-23 18:53 UTC, mohitg0795 commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 474 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8xIep9KeKb0TbWfQO:-NW8xIep9KeKb0TbWfQP:b6ddxvv) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L474)):*
> ```Java
>     // Check if the user is member of any user groups given in step parameters. If there are no user groups configures,
>     // we do not allow approval/rejection.
>     if (!isMemberOfUserGroups(instance, user)) {
> ```

what if this method throws exception? Do we want to allow to throw exception directly or handle it and decorate with some other exception?


<!-- Sent from Reviewable.io -->

2023-05-24 03:44 UTC, sourabh-awashti commented
trigger uts

2023-05-24 04:11 UTC, sourabh-awashti commented
trigger uts

2023-05-24 10:15 UTC, yogesh-chauhan requested changes

2023-05-24 10:15 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java
> +    return LocalDateTime.parse(timestampString, formatter);
consider timezone as well

2023-05-24 10:15 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +
we need to use "harness" as a user to display

2023-05-24 10:15 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +          throw new InvalidRequestException("Unable to perform auto approval");
return step response as failed with message as timoeut occured

2023-05-24 11:37 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/HarnessApprovalActivityRequestDTO.java
> +  boolean autoApprove;
Why this is required? Changes should be avoided here as it is request body for a public API.

2023-05-24 12:13 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/HarnessApprovalActivityRequestDTO.java
> +  boolean autoApprove;
We need to know whether a approval activity coming from a user or auto approval action, thats why i added it and anyways default would always be false for this

2023-05-24 13:14 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java
> +public class ApprovalStepHelper {
@yogesh-chauhan we are giving specific errors in case of failures so i don't think we should move it to common methods

2023-05-25 04:19 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/AutoApprovalAction.java
> +  public HarnessApprovalAction getHarnessApprovalAction() {
Done

2023-05-25 04:19 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/AutoApprovalParams.java
> +@OwnedBy(HarnessTeam.CDP)
Done

2023-05-25 04:19 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +  @Inject private ApprovalStepHelper approvalStepHelper;
Done

2023-05-25 04:19 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +  private final long DEFAULT_TIMEOUT_IN_MILLISECONDS = 600000;
Done

2023-05-25 04:19 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +    return (timeout == null || timeout.getValue() == null) ? DEFAULT_TIMEOUT_IN_MILLISECONDS
Done

2023-05-25 04:20 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java
> +public class ApprovalStepHelper {
Done

2023-05-25 04:20 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +      throw new InvalidYamlRuntimeException(format("Time given for auto approval can not be greater the step timeout",
Done

2023-05-25 04:20 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java
> +    return LocalDateTime.parse(timestampString, formatter);
Done

2023-05-25 04:21 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +
done

2023-05-25 04:21 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +          throw new InvalidRequestException("Unable to perform auto approval");
done

2023-05-25 05:52 UTC, sourabh-awashti commented
trigger uts

2023-05-25 05:56 UTC, sourabh-awashti commented
trigger uts

2023-05-25 12:02 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/AutoApprovalParams.java
> +  @YamlSchemaTypes(value = {string}) ParameterField<String> comments;
nit:  we can add  `@ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH)`

2023-05-25 12:04 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/ScheduledDeadline.java
> +  @NotNull String time;
Is this not allowed to be an expression?

2023-05-25 12:24 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +    return ParameterField.isNull(timeout) ? DEFAULT_TIMEOUT_IN_MILLISECONDS : timeout.getValue().getTimeoutInMillis();
We can use `TimeoutParameters.DEFAULT_TIMEOUT_IN_MILLIS` it is also used in approval instance.

2023-05-25 12:38 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    int autoApprovalDuration = Math.toIntExact(TimeStampUtils.getTotalDurationWRTCurrentTimeFromTimeStamp(
A not null check on `scheduledDeadline` can be added

2023-05-25 12:55 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    }
We should check this condition before , reason: `Schedule deadline for auto approval reached. Auto approving step ...` we have logged this in normal timeout case as well

2023-05-25 13:00 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/HarnessApprovalActivityRequestDTO.java
> +  boolean autoApprove;
We should try to avoid this because by this variable we are giving any user with pipeline execute permissions to approve the approval step bypassing no of approvers condition. 

We can discriminate between normal addHarnessApproval call and autoApproval related call via boolean variable or overloaded method while calling addHarnessApproval in approval step during autoApproval

2023-05-25 13:01 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +            .autoApprove(true)
Same comment : https://github.com/harness/harness-core/pull/48220/files#r1205488643

2023-05-25 13:14 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/AutoApprovalParams.java
> +  @NotNull AutoApprovalAction action;
no, we discussed with @shylajas , we don't want to hide it

2023-05-25 13:16 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    int autoApprovalDuration = Math.toIntExact(TimeStampUtils.getTotalDurationWRTCurrentTimeFromTimeStamp(
there is already @notNull added, so we don't require it

2023-05-25 14:11 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java
> +    rejectedApprovalIds.forEach(id -> rejectPreviousExecutions(id, user, false, instance.getAmbiance()));
rejectPreviousExecutions -> run auhtorization checks for embedded user irrespective of user passed here. What will be the embedded user for previous rejections as we don't trigger this flow on from our end when autoApproval is met.

2023-05-25 14:14 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +        executorService.submit(() -> approvalNotificationHandler.sendNotification(instance, ambiance));
Since we call waitNotifyEngine.doneWith again in so flow is expected to come again to this method with normal response? In that case we will send notification and step output twice.

2023-05-25 14:16 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java
> +        doTransaction(status -> addHarnessApprovalActivityInTransaction(approvalInstanceId, user, request));
We can check if whether `addHarnessApprovalActivityV2` and `addHarnessApprovalActivity` would still maintain atomicity of `addHarnessApprovalActivityInTransaction` flow, once mongo transactions are enabled.

2023-05-25 14:19 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/HarnessApprovalActivityRequestDTO.java
> +  boolean autoApprove;
correct we can have seperate DTOs

2023-05-26 03:26 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/ScheduledDeadline.java
> +  @NotNull String time;
we are not going to support expression for deadline

2023-05-26 03:26 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +        executorService.submit(() -> approvalNotificationHandler.sendNotification(instance, ambiance));
No , i checked once i send the step response , it will not come again in this step

2023-05-26 07:20 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/AutoApprovalParams.java
> +  @YamlSchemaTypes(value = {string}) ParameterField<String> comments;
done

2023-05-26 07:30 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +    return ParameterField.isNull(timeout) ? DEFAULT_TIMEOUT_IN_MILLISECONDS : timeout.getValue().getTimeoutInMillis();
done

2023-05-29 03:16 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java
> +    rejectedApprovalIds.forEach(id -> rejectPreviousExecutions(id, user, false, instance.getAmbiance()));
done

2023-05-29 03:19 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +            .autoApprove(true)
done

2023-05-29 03:19 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/outcomes/HarnessApprovalStepOutcome.java
> +  String approvalInstanceId;
done

2023-05-29 03:23 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    int autoApprovalDuration = Math.toIntExact(TimeStampUtils.getTotalDurationWRTCurrentTimeFromTimeStamp(
done

2023-05-29 03:23 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/outcomes/HarnessApprovalStepOutcome.java
> +  String approvalInstanceId;
done

2023-05-29 03:23 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +            .autoApprove(true)
done

2023-05-29 04:19 UTC, sourabh-awashti commented
trigger uts

2023-05-29 05:26 UTC, sourabh-awashti commented
trigger uts

2023-05-29 05:30 UTC, yogesh-chauhan requested changes

2023-05-29 05:30 UTC, yogesh-chauhan commented on 878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java
> +  }
for better readability, public methods can remain at the top and the private methods can remain at the botton of the class
https://stackoverflow.com/a/1760877

2023-05-29 05:30 UTC, yogesh-chauhan commented on 878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java
> +public class TimeStampUtils {
please write tests for this class

2023-05-29 05:30 UTC, yogesh-chauhan commented on 878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java
> +
This can be a utility class. That will automatically make all members as static
https://projectlombok.org/features/experimental/UtilityClass

2023-05-29 05:30 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +      setResponseWithTimeoutIfAutoApprovalIsSet(specParameters.getAutoApproval(), asyncExecutableResponseBuilder);
instead of passing the builder as an argument and then modifying it, its is better to do this
```
if (autoApproval) {
 builder.timeout(calculateTimeout(specParams) 
}
```

2023-05-29 05:30 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +        logCallback.saveExecutionLog("Schedule deadline for auto approval reached. Auto approving step  ...");
typo: schedule -> scheduled
( lets get Shylaja to confirm on this execution log once)

my opinion ( minor edits to your log)
"Scheduled deadline for auto approval has reached. Marking the step as approved..."

2023-05-29 05:30 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    EmbeddedUser user = EmbeddedUser.builder().name(HARNESS).email(HARNESS).build();
do we need to set the email ? This might cause confusion/break some existing automation since the email is not a valid format

2023-05-29 05:30 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    EmbeddedUser user = EmbeddedUser.builder().name(HARNESS).email(HARNESS).build();
also, this user is being used at the last line of this method, we need not define it here

2023-05-29 05:30 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +            .comments(specParameters.getAutoApproval().getComments().getValue())
we should check for getComments() to be null

2023-05-29 05:30 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +    if (harnessApprovalSpecParameters.getAutoApproval() != null
if the condition at line 69 goes through, this logic will not run. We should probably move it upwards and also extract out the 2 major logics in this method into their own methods
- verify user groups
- verify auto approval timeout

2023-05-29 09:51 UTC, sourabh-awashti commented
trigger uts

2023-05-29 09:58 UTC, yogesh-chauhan reviewed
> Reviewed 4 of 12 files at r5, 1 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 20 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-30 04:21 UTC, sourabh-awashti commented on 878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java
> +  }
done

2023-05-30 04:21 UTC, sourabh-awashti commented on 878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java
> +public class TimeStampUtils {
done

2023-05-30 04:21 UTC, sourabh-awashti commented on 878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java
> +
done

2023-05-30 04:21 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +      setResponseWithTimeoutIfAutoApprovalIsSet(specParameters.getAutoApproval(), asyncExecutableResponseBuilder);
done

2023-05-30 04:21 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +        logCallback.saveExecutionLog("Schedule deadline for auto approval reached. Auto approving step  ...");
done

2023-05-30 04:21 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    EmbeddedUser user = EmbeddedUser.builder().name(HARNESS).email(HARNESS).build();
done

2023-05-30 04:22 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    EmbeddedUser user = EmbeddedUser.builder().name(HARNESS).email(HARNESS).build();
done

2023-05-30 04:22 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +            .comments(specParameters.getAutoApproval().getComments().getValue())
done

2023-05-30 04:22 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java
> +    if (harnessApprovalSpecParameters.getAutoApproval() != null
done

2023-05-30 04:24 UTC, sourabh-awashti commented
trigger uts

2023-05-30 05:26 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 13 files at r1, 3 of 10 files at r4, 1 of 12 files at r5, 6 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 21 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-30 05:26 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 10 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 21 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-30 05:26 UTC, yogesh-chauhan approved these changes

2023-05-30 05:33 UTC, diptiman-adak commented
trigger uts

2023-05-30 06:19 UTC, sourabh-awashti commented
trigger uts

2023-05-30 10:03 UTC, sourabh-awashti commented
trigger uts

2023-05-30 14:17 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    if (specParameters.getAutoApproval().getComments() != null) {
We can check ParameterField.isNotNull

```if(ParameterField.isNotNull(specParameters.getAutoApproval().getComments()) {
  comments = specParameters.getAutoApproval().getComments().getValue();
}```

2023-05-30 14:24 UTC, naman-goenka submitted a review, later dismissed

2023-05-30 14:27 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +    if (specParameters.getAutoApproval().getComments() != null) {
@naman-goenka is there any issue if we check for not null like this, because checking it in place seems to be more readable

2023-05-31 04:49 UTC, sourabh-awashti commented
trigger uts

2023-05-31 06:03 UTC, sourabh-awashti commented
trigger ut1, trigger ut3

2023-05-31 07:43 UTC, sourabh-awashti commented
trigger uts

2023-05-31 08:57 UTC, sourabh-awashti commented
trigger ut0, trigger ut2

2023-05-31 09:09 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 2 files at r10, 2 of 3 files at r12, 4 of 4 files at r13, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 26 file(s) to review. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-31 10:10 UTC, mohitg0795 submitted a review, later dismissed

2023-05-31 10:10 UTC, mohitg0795 commented
trigger review

2023-05-31 12:44 UTC, archit-harness requested changes
not approving as of now as we should take delta instead of exact time

> Reviewed 2 of 10 files at r4, 1 of 12 files at r5, 1 of 10 files at r8, 1 of 4 files at r9, 3 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220#-:-NWlpc2O9I9uEZVf6kTl:b-238ep8)* status: 18 file(s) to review. 1 change requests. 9. unresolved discussions. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java` line 20 at r14](https://reviewable.io/reviews/harness/harness-core/48220#-NWlmx7-2Le-8TPudwfz:-NWlmx7-2Le-8TPudwg-:bwnmvh5) ([raw file](https://github.com/harness/harness-core/blob/e3e4a1ccd2aaf38502a774c4c8b870cd8623a12f/878-ng-common-utilities/src/main/java/io/harness/utils/TimeStampUtils.java#L20)):*
> ```Java
> import lombok.experimental.UtilityClass;
> 
> @UtilityClass
> ```

nit: Add team annotation
___
*[`878-ng-common-utilities/src/test/java/io/harness/utils/TimeStampUtilsTest.java` line 24 at r14](https://reviewable.io/reviews/harness/harness-core/48220#-NWlmzsLEDKEREaR0EwG:-NWlmzsLEDKEREaR0EwH:bnec35g) ([raw file](https://github.com/harness/harness-core/blob/e3e4a1ccd2aaf38502a774c4c8b870cd8623a12f/878-ng-common-utilities/src/test/java/io/harness/utils/TimeStampUtilsTest.java#L24)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class TimeStampUtilsTest {
> ```

Add extends cateogryTest and team annotation


<!-- Sent from Reviewable.io -->

2023-05-31 13:01 UTC, abhinavmittal-harness approved these changes
> Reviewed 2 of 13 files at r1, 2 of 10 files at r4, 4 of 12 files at r5, 5 of 10 files at r8, 1 of 4 files at r9, 1 of 2 files at r10, 2 of 3 files at r12, 4 of 4 files at r13, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 1 change requests. 10. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-01 05:53 UTC, sourabh-awashti commented
trigger uts

2023-06-01 07:01 UTC, sourabh-awashti commented
trigger uts

2023-06-01 07:23 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 7 files at r15, 1 of 1 files at r16, 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 8 file(s) to review. 1 change requests. 10. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-01 07:43 UTC, sourabh-awashti commented
trigger uts

2023-06-01 07:44 UTC, sourabh-awashti commented
trigger uts

2023-06-01 08:58 UTC, sourabh-awashti commented
trigger uts

2023-06-01 09:25 UTC, sourabh-awashti commented
trigger uts

2023-06-01 09:46 UTC, archit-harness requested changes
> Reviewed 2 of 10 files at r8, 1 of 3 files at r12, 3 of 7 files at r15, 1 of 1 files at r16, 1 of 4 files at r17, 2 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 6 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 253 at r20](https://reviewable.io/reviews/harness/harness-core/48220#-NWqL6vAA46Shdyf37Ub:-NWqL6vAA46Shdyf37Uc:b-j4v0nq) ([raw file](https://github.com/harness/harness-core/blob/b75cf856b9c365e2e6011962db2b13ac98c4be24/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L253)):*
> ```Java
>       @NotNull EmbeddedUser user, @NotNull @Valid HarnessApprovalActivityRequestDTO request) {
>     final String instanceId = new String(approvalInstanceId);
>     synchronized (instanceId) {
> ```

Does this needs to be synced?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fjql4fVBHGUBhLrx:-NWqLMfK8jqVWTsTS7ff:b32v57) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L132)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if responseDataMap.get(TIMEOUT_DATA) is null?
</blockquote></details>

+1
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/outcomes/HarnessApprovalStepOutcome.java` line 23 at r20](https://reviewable.io/reviews/harness/harness-core/48220#-NWqLVrK74mAmXyA5g1K:-NWqLVrK74mAmXyA5g1L:bhxmyge) ([raw file](https://github.com/harness/harness-core/blob/b75cf856b9c365e2e6011962db2b13ac98c4be24/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/outcomes/HarnessApprovalStepOutcome.java#L23)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDC)
> @Data
> ```

Why you need data and not Value?


<!-- Sent from Reviewable.io -->

2023-06-01 09:50 UTC, sourabh-awashti commented
*[`878-ng-common-utilities/src/test/java/io/harness/utils/TimeStampUtilsTest.java` line 24 at r14](https://reviewable.io/reviews/harness/harness-core/48220#-NWlmzsLEDKEREaR0EwG:-NWqMU2s6wvd65sr1nLn:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e3e4a1ccd2aaf38502a774c4c8b870cd8623a12f/878-ng-common-utilities/src/test/java/io/harness/utils/TimeStampUtilsTest.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add extends cateogryTest and team annotation
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-06-01 09:51 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 253 at r20](https://reviewable.io/reviews/harness/harness-core/48220#-NWqL6vAA46Shdyf37Ub:-NWqMXQO1P_a2UYSbBem:bsmja62) ([raw file](https://github.com/harness/harness-core/blob/b75cf856b9c365e2e6011962db2b13ac98c4be24/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L253)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Does this needs to be synced?
</blockquote></details>

yes as there are multiple flows which can update the approval instance. we want all of them in sync


<!-- Sent from Reviewable.io -->

2023-06-01 09:52 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fjql4fVBHGUBhLrx:-NWqMlvuCGGSFG_MYytc:b-owiza4) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L132)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

i have already added the check, if you can see, anyways it is not required as instanceOf return null in that case


<!-- Sent from Reviewable.io -->

2023-06-01 10:02 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/outcomes/HarnessApprovalStepOutcome.java` line 23 at r20](https://reviewable.io/reviews/harness/harness-core/48220#-NWqLVrK74mAmXyA5g1K:-NWqNUjcEMv7w9xZVb-W:b-8w3vir) ([raw file](https://github.com/harness/harness-core/blob/b75cf856b9c365e2e6011962db2b13ac98c4be24/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/outcomes/HarnessApprovalStepOutcome.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why you need data and not Value?
</blockquote></details>

what is the issue if we use data, i see almost all the sweeping output classes has annotation value in them


<!-- Sent from Reviewable.io -->

2023-06-01 10:08 UTC, archit-harness approved these changes
> Reviewed 2 of 13 files at r1, 3 of 12 files at r5, 1 of 10 files at r8, 1 of 3 files at r12, 1 of 4 files at r13, 1 of 5 files at r14, 3 of 4 files at r18, 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 6 file(s) to review. 10. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/48220#-NW6ms0u8O506OdUwBfT:-NWqQgfECIrf4qDEWhht:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5b1fb8b555af9f4dfdae331121c4e7f321dc644/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

a better naming convention : "DEFAULT_TIMEOUT_IN_MINUTES", also why is it string?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8t9Jv2rs72h1NEJY-:-NWqQhLb-N5Z7Ek1hleq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6UxC8APYYE_jX8G-i:-NWqQjGCCoOOUpu4oUBS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This method name is ambiguous. This method is tightly coupled to scheduledDeadline parameter so name of the method should also suggest the same.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6VMwGAlktIc4FYptf:-NWauj6kDDPgZQ9gj2Ki:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/HarnessApprovalStepFilterJsonCreatorV2.java#L138)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it static?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8vqrz0EKuMH6BON-J:-NWqQm6x7gLBWtWM8LUY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L107)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this injected directly while userGroupClient is injected via constructor?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 445 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6ezL220eEBTseEHyN:-NWqQoCK254oKOGZyJlr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L445)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats use-case for it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 462 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fDK-ETeBeyA1A0jc:-NWqQp4cBYlzTKUqg2SK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L462)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't it simply be : "Pipeline already approved/rejected" or "Pipeline already approved/rejected by the user" etc. I guess we shouldn't use "You" etc in such messages.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 477 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8xE5q8WlPBP_e7zHv:-NWqQpbRB6G3jhASR-q6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L477)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:09 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 474 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8xIep9KeKb0TbWfQO:-NWqQqA_DZAbqALO3HZv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L474)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this method throws exception? Do we want to allow to throw exception directly or handle it and decorate with some other exception?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:10 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fohgAxma4XWOSJIC:-NWqQrpl5Z_2yArU9SA7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L179)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

remove hardcoding of strings.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:10 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/48220#-NW6fxRf6phgidIOkh1-:-NWqQsqXAalReXZ_1fLs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a4bc6e3ca1678183ef7b56253bdcb07708bad68/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java#L225)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this is repeated code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:10 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8uB0jEq1cNcEgRmqC:-NWqQuvLBo9O-RH9x8et:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This gets affected by TZ, are we taking care of it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:10 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/48220#-NW8uNgMCmS6XlRXo_x2:-NWqQvcr13YQ7cx19eZJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/148d5af706bb50d1ec4becff63bfab0ce66bf714/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/ApprovalStepHelper.java#L33)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it public?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:10 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 265 at r7](https://reviewable.io/reviews/harness/harness-core/48220#gh-1205588908:-NWqQyD5D19gb5nLzqpd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4333d4d7fa208d16d3051ac26f6efc20654128aa/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L265)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

We can check if whether `addHarnessApprovalActivityV2` and `addHarnessApprovalActivity` would still maintain atomicity of `addHarnessApprovalActivityInTransaction` flow, once mongo transactions are enabled.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-01 10:30 UTC, sourabh-awashti commented
trigger uts

2023-06-01 10:48 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 7 file(s) to review. 27. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-01 11:07 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 4 files at r18, 2 of 3 files at r19, 1 of 1 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48220)* status: 27. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-01 11:07 UTC, sourabh-awashti commented
trigger review

2023-06-01 11:40 UTC, merged