feat: [CDS-69282]: Integrated Template with OP
harness/harness-core pull request #48239
Opened 2023-05-23 11:02 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-23 11:24 UTC, shivamnegi94 commented
trigger uts

2023-05-24 05:00 UTC, utkarshchoubey-harness requested changes
> Reviewed 2 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48239)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB5gD9DPO7lR_6LXxT:-NWB5gDA95Re6Kf74u6Q:bt3me2b) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java#L152)):*
> ```Java
>       @Query("accountId") String accountId, @Body InstanceSyncPerpetualTaskResponse responseData);
> 
>   /// ##############INSTANCE SYNC V2 ###################
> ```

this is extra change right ?
Can we remove this if not needed
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 354 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB79L4DzfbIuKqHJoH:-NWB79L4DzfbIuKqHJoI:bhvx4os) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L354)):*
> ```Java
>                                              .map(PolicySetMetadata::getIdentifier)
>                                              .collect(Collectors.toList());
>       // todo: see if this can be changed to PolicyEvaluationFailureException, probably yes
> ```

yes we should not throw invalidRequestException, we can take it in future prs maybe 
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB641uC1ky8OR_JUuN:-NWB641uC1ky8OR_JUuO:bue1r6l) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java#L45)):*
> ```Java
>       String templateIdentifier) throws UnsupportedEncodingException {
>     String entityStringRaw =
>         String.format("accountIdentifier:%s/orgIdentifier:%s/projectIdentifier:%s/templateIdentifier:%s", accountId,
> ```

@shivamnegi94 just to confirm there's no need of versionLabel right here ?
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB6GmEEqf4NNW5tRyy:-NWB6GmF75DFX89djbac:bjo9xkj) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java#L89)):*
> ```Java
> 
>         response = SafeHttpCall.executeWithExceptions(
>             opaServiceClient.evaluateWithCredentials(OpaConstants.OPA_EVALUATION_TYPE_PIPELINE, accountId,
> ```

OPA_EVALUATION_TYPE_PIPELINE we will we changing this to template right, after adding template on save in OPA ?
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB6Zme4_pi6Ib2wxMO:-NWB6Zme4_pi6Ib2wxMP:b-vb3v4v) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java#L118)):*
> ```Java
>         return GovernanceMetadata.newBuilder().setDeny(false).build();
>       }
>       log.info("Initiating policy check for pipeline with expanded JSON:\n" + expandedJson);
> ```

Initiating policy check for template with expanded JSON ^


<!-- Sent from Reviewable.io -->

2023-05-24 06:06 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java
> +        templateEntity.getYaml(), templateEntity.getAccountId(), templateEntity.getOrgIdentifier(),
We are not going to expand the Yaml

2023-05-24 06:12 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48239)* status: 17 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/48239#gh-1202686560:-NWBNhli8RIP63gVb9AS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java#L152)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Is this change needed?
</blockquote></details>

Done.
___
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB5gD9DPO7lR_6LXxT:-NWBNitT7XbjJkM4pzjN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java#L152)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

this is extra change right ?
Can we remove this if not needed
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/GovernanceServiceImplTest.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/48239#gh-1202687043:-NWBNmnBCY8oW_nZN1i9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/GovernanceServiceImplTest.java#L195)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

same as above 
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 354 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB79L4DzfbIuKqHJoH:-NWBNo9BEOxfB3Ar_N-5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L354)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

yes we should not throw invalidRequestException, we can take it in future prs maybe 
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/48239#gh-1202686804:-NWBNjj-EWdKxm6y0etH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java#L43)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Isn't this the same method used by pipeline as well?
If so, we should either add an argument in this method to return different strings based on the argument being either pipeline or template. Or we can add a separate method for template.
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB641uC1ky8OR_JUuN:-NWBNk6J5a4K0_Mhw6hw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java#L45)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

@shivamnegi94 just to confirm there's no need of versionLabel right here ?
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/48239#gh-1202686850:-NWBNkVE44r1jjRu-6w6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java#L50)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB6GmEEqf4NNW5tRyy:-NWBNlDS3NySw3Cectd5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java#L89)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

OPA_EVALUATION_TYPE_PIPELINE we will we changing this to template right, after adding template on save in OPA ?
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/48239#-NWB6Zme4_pi6Ib2wxMO:-NWBNlh0DhncjJ9G8qFY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java#L118)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Initiating policy check for template with expanded JSON ^
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/48239#gh-1202686949:-NWBNm9AEcVhYFGcVNl4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e343dfa6cf4d3827b5fd247754e1a2e1377a932b/878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceImpl.java#L142)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

first argument should be OPA_EVALUATION_TYPE_TEMPLATE
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-24 09:57 UTC, utkarshchoubey-harness reviewed
> Reviewed 1 of 16 files at r1, 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48239)* status: 20 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-05-24 10:22 UTC, namanvermah commented on 878-ng-common-utilities/src/main/java/io/harness/engine/GovernanceServiceHelper.java
> +                                          .put("executionIdentifier", planExecutionId)
executionIdentifier is not needed for template. it is not something that exists for them

2023-05-24 10:23 UTC, namanvermah commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  OPA_TEMPLATE_GOVERNANCE,
Please add teamowner, description, etc

2023-05-25 08:29 UTC, shivamnegi94 commented on 420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java
> +  /// ##############INSTANCE SYNC V2 ###################
This changes are coming because of code format style

2023-05-29 03:45 UTC, shivamnegi94 commented
trigger uts

2023-05-29 07:41 UTC, utkarshchoubey-harness submitted a review, later dismissed

2023-05-29 07:48 UTC, shivamnegi94 commented
trigger uts

2023-05-29 07:50 UTC, namanvermah submitted a review, later dismissed

2023-05-29 08:36 UTC, shivamnegi94 commented
trigger uts

2023-05-29 11:47 UTC, utkarshchoubey-harness approved these changes

2023-05-29 15:21 UTC, namanvermah approved these changes

2023-05-30 03:54 UTC, shivamnegi94 commented
trigger review

2023-05-30 06:02 UTC, naidu-harness approved these changes
> Reviewed 8 of 16 files at r1, 1 of 2 files at r2, 2 of 8 files at r3, 5 of 8 files at r5, 1 of 2 files at r7, 1 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48239)* status: 20 file(s) to review. 9. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-05-30 06:02 UTC, merged