feat: [CDS-68394]: Refactor K8s Tasks to use KubectlFactory
harness/harness-core pull request #48254
Opened 2023-05-23 15:14 UTC by alebuh

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-24 13:29 UTC, alebuh commented
trigger uts

2023-05-25 07:06 UTC, abhinavsingh1196 requested changes

2023-05-25 07:06 UTC, abhinavsingh1196 commented on 960-api-services/src/test/java/io/harness/k8s/kubectl/FlagTest.java
> +  public void testVersionConfiguration() {
no assertion done in this test. If we expect the version parsing to pass without any exceptions we should probably do an assertion like
`assertThatThrownBy(() -> ...).isNull()`
Although if there are tests present for Version::parse method, we could probably just skip this

2023-05-25 09:02 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +  Kubectl getKubectlClient(boolean useNewKubectlVersion, String path) {
done

2023-05-25 09:06 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/kubectl/Flag.java
> +  private String getFlagFromMap(Version version, Map<String, String> versionMap) {
Good idea to use TreeMap, it will simplify the logic. Hoverer we would need to go through keySet in descending order to find the highest applicable version. For example, the tree map is (1.0: a, 2.0:b, 3.0 :c, 4.0:d) if we provide version 3.2 we would need to return c and not b.
Implement logic to use treeMap

2023-05-25 09:10 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/kubectl/Flag.java
> +    return isNotEmpty(flag) ? "--" + flag : "";
I think it would be better to leave that here, to keep flags more simple. Also, there are some other methods in Kubectl.java that are using flags and they are adding "--" so the concern is that we can have duplicated "--" symbols if we add them to the flags

2023-05-25 09:13 UTC, alebuh commented
trigger uts

2023-05-25 14:26 UTC, alebuh commented
trigger uts

2023-05-26 10:50 UTC, abhinavsingh1196 approved these changes

2023-05-29 06:59 UTC, abosii-harness approved these changes

2023-05-29 07:02 UTC, alebuh commented
trigger review

2023-05-29 07:03 UTC, merged