feat: [CDS-70246]: Refactor decryption logic for instance Sync v2 NG
harness/harness-core pull request #48296
Opened 2023-05-24 12:28 UTC by namantalaycha10

## Describe your changes
With the following change we are moving the decryption logic to general class so that we do not have to decrypt for every deploymentDetails

## Local test results
1. for new deployment creating one replica
<img width="738" alt="Screenshot 2023-05-25 at 6 45 50 PM" src="https://github.com/harness/harness-core/assets/84320791/e77d68b8-b8f5-4210-9db0-6709afc67025">

2. Manually scaling down the instance to 0
<img width="621" alt="Screenshot 2023-05-26 at 10 17 21 AM" src="https://github.com/harness/harness-core/assets/84320791/d3012cf0-97dd-4072-8eea-0de0ed78b14f">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/48296)

2023-05-25 17:57 UTC, namantalaycha10 commented
trigger uts

2023-05-25 18:05 UTC, namantalaycha10 commented
trigger uts

2023-05-26 05:39 UTC, namantalaycha10 commented
trigger uts

2023-05-26 06:05 UTC, namantalaycha10 commented
trigger messagecheck

2023-05-26 12:55 UTC, abosii-harness requested changes

2023-05-26 12:55 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +  private List<ServerInstanceInfo> retrieveServiceInstances(PerpetualTaskId taskId,
nit: add a space before

2023-05-26 12:55 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +  private List<ServerInstanceInfo> retrieveServiceInstances(PerpetualTaskId taskId,
And can we rename this method? It does match with the abstract one, may be confusing

2023-05-26 12:55 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +      PerpetualTaskId taskId, InstanceSyncV2Request instanceSyncV2Request, DeploymentReleaseDetails details);
Do we need to pass taskId here? Should be already available in InstanceSyncV2Request

2023-05-26 12:58 UTC, namantalaycha10 commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +  private List<ServerInstanceInfo> retrieveServiceInstances(PerpetualTaskId taskId,
thanks for pointing out, doing the changes

2023-05-26 12:59 UTC, namantalaycha10 commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +  private KryoSerializer kryoSerializer;
okay

2023-05-26 13:34 UTC, namantalaycha10 commented
trigger uts

2023-05-26 13:40 UTC, namantalaycha10 commented
trigger uts

2023-05-26 13:50 UTC, namantalaycha10 commented
trigger uts

2023-05-26 15:37 UTC, abosii-harness submitted a review, later dismissed

2023-05-26 21:17 UTC, jennyjames21 commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +  private KryoSerializer kryoSerializer;
just to be in sync, lets use kryoSerializer for now. i can change to referenceFalse

2023-05-29 10:16 UTC, GoelPratyush99 submitted a review, later dismissed

2023-05-29 10:16 UTC, namantalaycha10 commented
trigger uts

2023-05-29 10:16 UTC, namantalaycha10 commented
trigger review

2023-05-29 10:32 UTC, abhinavsingh1196 requested changes

2023-05-29 10:32 UTC, abhinavsingh1196 commented on 260-delegate/src/main/java/io/harness/perpetualtask/AbstractInstanceSyncV2TaskExecutor.java
> +              instanceSyncV2Request, deploymentReleaseDetails, accountId, instanceSyncData);
instanceSyncV2Request already has an attribute `accountId`. Can we use that to reduce this method's parameters further?

2023-05-29 11:11 UTC, abhinavsingh1196 approved these changes

2023-05-29 11:13 UTC, GoelPratyush99 approved these changes

2023-05-29 11:26 UTC, merged