fix: [CDS-53971]: added retry policy to Azure REST client
harness/harness-core pull request #48368
Opened 2023-05-25 14:41 UTC by vitsafronovici

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-25 14:48 UTC, vitsafronovici commented
trigger uts

2023-05-26 06:57 UTC, acasian-harness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
>        return new ArrayList<>();
nit: `Collections.emptyList()`

2023-05-26 06:58 UTC, acasian-harness commented
@vitsafronovici did we validated azure artifacts on local?

2023-05-26 06:59 UTC, acasian-harness submitted a review, later dismissed

2023-05-26 08:04 UTC, ivan-83 requested changes
Overall looks good to me with minor comments.

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368#-:-NWM4c0d4Cb6K8gAb0HU:baoxoev)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 403 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWLxw5NCaPO_T8dM5hh:-NWLxw5O6C0mMs7N_E2F:bjkr5ki) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L403)):*
> ```Java
> 
>   public static <T> T executeRestCall(Call<T> restRequest, WingsException defaultException) {
>     net.jodah.failsafe.RetryPolicy<Response<T>> retryPolicy =
> ```

Minor - retryPolicy should be a static class filed in order not to create on each method call. 
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 405 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWM0Sl85UtY2bw2ssZM:-NWM0Sl85UtY2bw2ssZN:bcl7vyq) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L405)):*
> ```Java
>     net.jodah.failsafe.RetryPolicy<Response<T>> retryPolicy =
>         new net.jodah.failsafe.RetryPolicy<Response<T>>()
>             .withBackoff(1, 20, ChronoUnit.SECONDS)
> ```

Here, I suggest 3 retrying on 10 seconds. 20 seconds is too much. 
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 407 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWLyMkD4LXEBxSRuyQV:-NWLyMkD4LXEBxSRuyQW:bd4tyfj) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L407)):*
> ```Java
>             .withBackoff(1, 20, ChronoUnit.SECONDS)
>             .withMaxAttempts(EXECUTE_REST_CALL_MAX_ATTEMPTS)
>             .handle(IOException.class)
> ```

Do retry on 502, 503, and 504, use the handleResultIf method with logic if the response is unsuccessful, and if one of these error codes retry. 
___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 436 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWM41Y0CxX4y0vsjyol:-NWM41Y0CxX4y0vsjyom:b-3fde6e) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L436)):*
> ```Java
>         throw defaultException;
>       }
>       throw new WingsException("Failsafe failure", ex.getCause());
> ```

We need a more meaningful message here instead of Failsafe failure


<!-- Sent from Reviewable.io -->

2023-05-26 09:26 UTC, vitsafronovici commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
>        return new ArrayList<>();
maybe it was put for some reason new ArrayList(), if Collections.emptyList() is used it is unmodifiable list and it will throw exception if anywhere in code it will be changed

2023-05-26 09:30 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 436 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWM41Y0CxX4y0vsjyol:-NWMNvY06ZB1dbs7Ely3:b-dpjddb) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L436)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We need a more meaningful message here instead of Failsafe failure
</blockquote></details>

there is a defaultException for that, this logic most likely will not be used, but just provided that in order to display something that makes sence


<!-- Sent from Reviewable.io -->

2023-05-26 09:49 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 403 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWLxw5NCaPO_T8dM5hh:-NWMSYBZAVMhBACaDaga:blhdpdm) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L403)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - retryPolicy should be a static class filed in order not to create on each method call. 
</blockquote></details>

It should not be static as it is not thread safe
https://github.com/failsafe-lib/failsafe/issues/47


<!-- Sent from Reviewable.io -->

2023-05-26 10:15 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 436 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWM41Y0CxX4y0vsjyol:-NWMYcPX2W5apbZ-JejW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L436)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

there is a defaultException for that, this logic most likely will not be used, but just provided that in order to display something that makes sence
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-05-26 10:16 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368)* status: 5 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 405 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWM0Sl85UtY2bw2ssZM:-NWMYiCcC1HygJZqF4_2:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L405)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Here, I suggest 3 retrying on 10 seconds. 20 seconds is too much. 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-05-26 10:16 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 407 at r2](https://reviewable.io/reviews/harness/harness-core/48368#-NWLyMkD4LXEBxSRuyQV:-NWMYsDm0pFCKyaHCsNX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/238d9a4c5f9f30e08fcd9d65a4ab07a62c46c46a/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L407)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do retry on 502, 503, and 504, use the handleResultIf method with logic if the response is unsuccessful, and if one of these error codes retry. 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-05-26 10:18 UTC, vitsafronovici commented
trigger uts

2023-05-26 10:32 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368#-:-NWMbVtm9EZFU372tnsJ:bnfp4nl)* status: 5 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java` line 443 at r3](https://reviewable.io/reviews/harness/harness-core/48368#-NWMaGbkBZmH6evyZqiT:-NWMaGbl-1ON6Cwn8RXq:bk8n394) ([raw file](https://github.com/harness/harness-core/blob/2a50efdd37f473e4f940847c7494a78faf9fa5ca/960-api-services/src/main/java/io/harness/azure/utility/AzureUtils.java#L443)):*
> ```Java
>   private boolean isRetryableHttpCode(int httpCode) {
>     // https://stackoverflow.com/questions/51770071/what-are-the-http-codes-to-automatically-retry-the-request
>     return httpCode == 408 || httpCode == 502 || httpCode == 503 || httpCode == 504;
> ```

Nice, we include 408 we could consider and 429 but it's enough for the time being. I remember we also included Loop Detected(508) but let's see how Azure API respond. 


<!-- Sent from Reviewable.io -->

2023-05-26 10:33 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368#-:-NWMbcOg0uDMLIQPuz9I:bnfp4nl)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-26 10:37 UTC, vitsafronovici commented
trigger uts

2023-05-26 11:07 UTC, vitsafronovici commented
trigger uts

2023-05-26 13:32 UTC, vitsafronovici commented
trigger uts

2023-05-26 14:03 UTC, acasian-harness approved these changes

2023-05-26 14:20 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48368#-:-NWNQgtQ6QmpkIi1A-Li:bnfp4nl)* status: 5 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-05-26 14:21 UTC, vitsafronovici commented
trigger review

2023-05-26 14:24 UTC, merged