feat: [IDP-532]: Support for OAuth based plugins
harness/harness-core pull request #48390
Opened 2023-05-26 03:45 UTC by vigneswara-propelo

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-26 04:10 UTC, vigneswara-propelo commented
trigger uts

2023-05-26 06:59 UTC, vigneswara-propelo commented
trigger uts

2023-05-26 08:54 UTC, mankrit-singh submitted a review, later dismissed

2023-05-26 11:07 UTC, devesh-harness requested changes

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/github-auth-schema.json
> +      "type": "object",
"additionalProperties": false
add this property in every object

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/github-auth-schema.json
> +          "type": "object",
"additionalProperties": false
add this property in every object

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/github-auth-schema.json
> +              "required": [
"additionalProperties": false
add this property in every object

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/github-auth-schema.json
> +                  "type": "object",
"additionalProperties": false
add this property in every object

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/google-auth-schema.json
> +      "type": "object",
"additionalProperties": false
add this property in every object

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/google-auth-schema.json
> +          "type": "object",
"additionalProperties": false
add this property in every object

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/google-auth-schema.json
> +              "required": [
"additionalProperties": false
add this property in every object

2023-05-26 11:07 UTC, devesh-harness commented on idp-service/src/main/resources/configs/auth/json-schemas/google-auth-schema.json
> +                  "type": "object",
"additionalProperties": false
add this property in every object

2023-05-26 11:11 UTC, devesh-harness commented on idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java
> +  AUTH;
Here if we are adding new type then on configuration screen where we show the combined configurations for enabled plugins then in that we are not planning to show auth configurations there?

2023-05-26 11:38 UTC, vigneswara-propelo commented on idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java
> +  AUTH;
yes, we are not planning to show auth configurations there. We will have a separate screen to show the clientId and clientSecret for users to configure.

2023-05-26 11:58 UTC, devesh-harness commented on idp-service/src/main/java/io/harness/idp/configmanager/ConfigType.java
> +  AUTH;
ok

2023-05-26 11:58 UTC, devesh-harness approved these changes

2023-05-26 12:00 UTC, vigneswara-propelo commented
trigger uts

2023-05-29 03:01 UTC, vigneswara-propelo commented
trigger uts

2023-05-29 03:33 UTC, vigneswara-propelo commented
trigger copyrightcheck

2023-05-29 07:28 UTC, vigneswara-propelo commented
trigger ut2

2023-05-29 11:11 UTC, sandeepa-kv-jois requested changes
Few things we need to consider:
1) Provide relevant IDP URL values that customers need to configure like Authorized JavaScript origins and  Authorized Redirect URIs in API response
2) Provide relevant IDP URL values that customers need to configure for callbackUrl in case of Github OAuth 
3) enterpriseInstanceUrl if needed or not check based on the connector gitHub Type(GitHub Vs GHE)

2023-05-30 11:43 UTC, vigneswara-propelo commented
> 

@sandeepa-kv-jois - Connected with UI team and we decided Authorized JavaScript origins and Redirect URIs will be constructed from UI itself. We just need to give namespace info in the API response.

2023-05-30 11:44 UTC, vigneswara-propelo commented
trigger uts

2023-05-31 06:21 UTC, sandeepa-kv-jois approved these changes

2023-05-31 06:37 UTC, vigneswara-propelo commented
trigger uts

2023-05-31 06:39 UTC, mankrit-singh commented on idp-service/contracts/openapi/v1/openapi.yaml
> +        envVariables:
env_variables

2023-05-31 06:52 UTC, vigneswara-propelo commented on idp-service/contracts/openapi/v1/openapi.yaml
> +        envVariables:
done

2023-05-31 07:00 UTC, mankrit-singh approved these changes

2023-05-31 07:07 UTC, sandeepa-kv-jois approved these changes

2023-05-31 07:27 UTC, vigneswara-propelo commented
trigger review

2023-05-31 09:15 UTC, merged