[feat]: [CDS-58159]: changes to get overrides v2 in service step
harness/harness-core pull request #48407
Opened 2023-05-26 09:35 UTC by tchaurasiya

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-26 12:28 UTC, yogesh-chauhan requested changes

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +    if (isEmpty(parameters.getEnvRef().getValue()) || isEmpty(parameters.getServiceRef().getValue())
can we check for ParamterField.isNotNull as well ?

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +        || isEmpty(parameters.getInfraId().getValue())) {
this should not throw error or log for now

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +      throw new InvalidRequestException("Service Override or Environment inputs are not resolved");
what is the value of this ? lets log it

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +      Map<String, NGServiceOverrideConfigV2> scopeWiseMergedOverrides =
nit: can we call this acrossScopes ?

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +    Map<String, NGServiceOverrideConfigV2> overridesMap = new HashMap<>();
can the key be enum TYPE ?

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +  private Optional<NGServiceOverrideConfigV2> mergeOverridesGroupedByScope(
nit: name can be grouped by type instead

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +          "Found more than 3 overrides, at one scope (project, org, account) only one override is supported");
this should be > 3 only

2023-05-26 12:28 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +    overridesSpec.getConfigFiles().forEach(
null check for override spec.getVariableS() and manifests/config files

2023-05-26 13:28 UTC, tchaurasiya commented
trigger uts

2023-05-26 20:50 UTC, tchaurasiya reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48407)* status: 52 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/48407#gh-1206692321:-NWOolBl5hgNNjIzoRFo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fcf5a6b8da14708a0e7771c5b7a281665cfefa6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L98)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we check for ParamterField.isNotNull as well ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/48407#gh-1206698483:-NWOolbg0j3jl4lwecMI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fcf5a6b8da14708a0e7771c5b7a281665cfefa6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L99)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this should not throw error or log for now
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/48407#gh-1206699561:-NWOop3d4hpsZ8PzSHhx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fcf5a6b8da14708a0e7771c5b7a281665cfefa6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L106)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what is the value of this ? lets log it
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/48407#gh-1206703868:-NWOopa72j4xSfzRv41H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fcf5a6b8da14708a0e7771c5b7a281665cfefa6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L109)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can the key be enum TYPE ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 190 at r2](https://reviewable.io/reviews/harness/harness-core/48407#gh-1206706305:-NWOos9A1njzHZCytiJc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fcf5a6b8da14708a0e7771c5b7a281665cfefa6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L190)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this should be > 3 only
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 259 at r2](https://reviewable.io/reviews/harness/harness-core/48407#gh-1206710691:-NWOowAB0Z9pyM_Or6Ot:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fcf5a6b8da14708a0e7771c5b7a281665cfefa6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L259)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

null check for override spec.getVariableS() and manifests/config files
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-28 07:05 UTC, yogesh-chauhan requested changes
> Reviewed 3 of 52 files at r1, 47 of 48 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48407)* status: 52 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/48407#gh-1206698483:-NWWA6oDB2jv-vptaxhX:b-f0exxg) ([raw file](https://github.com/harness/harness-core/blob/2fcf5a6b8da14708a0e7771c5b7a281665cfefa6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L99)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see exception is still being thrown ?


<!-- Sent from Reviewable.io -->

2023-05-28 07:06 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> +      log.warn("Infra Identifier has not been resolved to get service overrides");
will be below code be able to handle infraID not being present ?

2023-05-29 07:00 UTC, tchaurasiya commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/48407#gh-1208386486:-NWaIe0L7TuCD6WJemJx:b-pvxo0w) ([raw file](https://github.com/harness/harness-core/blob/5f9fff0d3e4f509f1c2300d0bc240edca289d059/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L103)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

will be below code be able to handle infraID not being present ?
</blockquote></details>

Yes. Discussed offline.


<!-- Sent from Reviewable.io -->

2023-05-29 07:15 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48407)* status: 52 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-05-29 07:39 UTC, tchaurasiya commented
trigger uts

2023-05-29 09:11 UTC, sourabh-awashti approved these changes

2023-05-29 09:11 UTC, tchaurasiya commented
trigger review

2023-05-29 09:13 UTC, merged