feat: [CDS-58338]: Adding Cluster name for K8S AWS,Azure,GCP connector type for instance sync V2 and fixing the cleanUpInstanceSyncPerpetualTaskInfo
harness/harness-core pull request #48454
Opened 2023-05-29 05:56 UTC by namantalaycha10

## Describe your changes
Adding Cluster name for K8S AWS,Azure,GCP connector type for instance sync V2 and fixing the cleanUpInstanceSyncPerpetualTaskInfo

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-29 06:06 UTC, abosii-harness requested changes

2023-05-29 06:06 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/InfrastructureOutcome.java
> +  default String getCluster() throws UnsupportedTypeException {
Any specific reason why we need this method? Not all infrastructure outcomes has cluster or concept of it in entity. And what about resource group and subscription id? Will we have to do the same? Why to not do casting to the actual type?

2023-05-29 06:06 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +            K8sAWSCloudConfigMetadata.builder().clusterName(infrastructureOutcome.getCluster()).build();
Why we're creating always AWS cloud config?

2023-05-29 06:06 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +                                           .clusterName(k8sDeploymentInfoDTO.getCloudConfigMetadata().clusterName())
What about resource group and subscription id?

2023-05-29 06:06 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/helper/K8sAzureCloudConfigMetadata.java
> +  String clusterName;
What about resource group and subscription id?

2023-05-29 06:59 UTC, namantalaycha10 commented
trigger messageCheck

2023-05-29 07:55 UTC, abosii-harness requested changes

2023-05-29 07:55 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +      throw new InvalidArgumentsException(Pair.of("infrastructureOutcome",
We should never throw the exception and just return null

2023-05-29 07:55 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/helper/InstanceSyncHelper.java
> +    instanceSyncPerpetualTaskService.deletePerpetualTask(
perpetualTaskId can be null

2023-05-29 07:55 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/helper/K8sCloudConfigMetadata.java
> +  String clusterName();
This should be getClusterName()

2023-05-29 07:55 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/helper/K8sGcpCloudConfigMetadata.java
> +  public String clusterName() {
Once you rename the method to getClusterName() you wouldn't need this override

2023-05-29 07:57 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +        if (k8sDeploymentInfoDTO.getCloudConfigMetadata() instanceof K8sAzureCloudConfigMetadata) {
This logic and the from infrastructure outcome is better to move to a utility class

2023-05-29 11:11 UTC, abhinavsingh1196 requested changes

2023-05-29 11:11 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/helper/K8sInfrastructureUtility.java
> +    if (infrastructureOutcome instanceof K8sGcpInfrastructureOutcome) {
a good way to get rid of a lot of these `if (a instanceof b)` checks is to write a separate interface `K8sInfraDataEmitter` which has this method:
`K8sCloudConfigMetadata getInfraOutcomeMetadata`

All the necessary outcomes(like `K8sAwsInfrastructureOutcome`) can implement this interface and return the necessary data. We just have to call that method here then.

2023-05-29 11:11 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/helper/K8sInfrastructureUtility.java
> +@Slf4j
should add `@Singleton` annotation here

2023-05-29 11:14 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/helper/K8sInfrastructureUtility.java
> +@Slf4j
I would say it should be @UtilityClass

2023-05-29 13:26 UTC, namantalaycha10 commented
trigger uts

2023-05-29 13:47 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/helper/K8sInfrastructureUtility.java
> +@Slf4j
yes my bad, I see no state is being altered by it. Should be a Utility class.

2023-05-30 06:04 UTC, namantalaycha10 commented
trigger uts

2023-05-30 06:36 UTC, namantalaycha10 commented
trigger uts

2023-05-30 06:49 UTC, abhinavsingh1196 approved these changes

2023-05-30 06:54 UTC, abosii-harness approved these changes

2023-05-30 06:55 UTC, namantalaycha10 commented
trigger review

2023-05-30 07:12 UTC, TarunUba1 approved these changes

2023-05-30 07:25 UTC, merged