feat: [CDS-69961]: Adding a new field in release hostory to track the bg environment
harness/harness-core pull request #48460
Opened 2023-05-29 07:49 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-05-29 08:01 UTC, GoelPratyush99 commented
trigger uts

2023-05-29 10:58 UTC, GoelPratyush99 commented
trigger uts

2023-05-29 11:36 UTC, abhinavsingh1196 requested changes

2023-05-29 11:36 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/ReleaseHistory.java
> +    if (index < this.getReleases().size()) {
we should add a unit test which checks this ordered insertion

2023-05-29 11:36 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
> +    V1ObjectMeta releaseMeta = releaseSecret.getMetadata();
we can use K8sReleaseSecretHelper.putLabelsItem(secret, key, value), it already handles these checks

2023-05-29 11:36 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +  private String bgEnvironment;
nit: this can be called `bgEnvironmentType`? if updating, please update the corresponding method names as well.

2023-05-29 11:37 UTC, abhinavsingh1196 commented
Please update PR description as well.

2023-05-29 11:55 UTC, abosii-harness requested changes

2023-05-29 11:55 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
> +  public static final String RELEASE_SECRET_RELEASE_BG_ENVIRONMENT_KEY = "bgEnvironment";
Can we rename this to something more standardized, i.e. harness.io/release/bg/env?

2023-05-29 11:55 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    if (bgStageEnv.equals(release.getBgEnvironment())) {
Will we revert it back to stage if swap services is rollback?

2023-05-29 13:31 UTC, GoelPratyush99 commented
trigger uts

2023-05-30 05:59 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/ReleaseHistory.java
> +    if (index < this.getReleases().size()) {
Done

2023-05-30 05:59 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
> +    V1ObjectMeta releaseMeta = releaseSecret.getMetadata();
Done

2023-05-30 06:00 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    if (bgStageEnv.equals(release.getBgEnvironment())) {
I have updated the code and added that functionality as well.

2023-05-30 06:11 UTC, GoelPratyush99 commented
trigger uts

2023-05-30 06:59 UTC, abosii-harness requested changes

2023-05-30 06:59 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +    if (release == null || bgStageEnv.equals(release.getBgEnvironment())) {
I'm not getting this logic.. Why if it's stage env then we're not deleting??

2023-05-30 06:59 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +    if (release == null || bgStageEnv.equals(release.getBgEnvironment())) {
potential NPE? As bgEnvironment is a new field or can be not set if release is not b/g

2023-05-30 06:59 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +  public IK8sRelease updateReleaseBGEnvironment(String bgEnvironment) {
nit: setBgEnvironment make more sense for me

2023-05-30 06:59 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/ReleaseHistory.java
> +    if (index < this.getReleases().size()) {
Is this actually required? Can you reveal more details why you did this? Are you creating a new immutable release?

2023-05-30 06:59 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    if (bgStageEnv.equals(release.getBgEnvironment())) {
Potential NPE

2023-05-30 09:27 UTC, GoelPratyush99 commented
trigger uts

2023-05-30 09:34 UTC, GoelPratyush99 commented
trigger copyrightcheck

2023-05-30 09:54 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +  public IK8sRelease updateReleaseBGEnvironment(String bgEnvironment) {
done

2023-05-30 09:55 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +    if (release == null || bgStageEnv.equals(release.getBgEnvironment())) {
Changed to stage environment. Also no NPE will be thrown as I am checking for release == null

2023-05-30 09:55 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    if (bgStageEnv.equals(release.getBgEnvironment())) {
Resolved it

2023-05-30 09:55 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/ReleaseHistory.java
> +    if (index < this.getReleases().size()) {
Thanks for pointing out. It was not required. I have removed the piece of code

2023-05-31 04:31 UTC, GoelPratyush99 commented
trigger ut3

2023-05-31 08:24 UTC, abosii-harness approved these changes

2023-05-31 10:12 UTC, GoelPratyush99 commented
trigger uts

2023-05-31 11:29 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java
> +    if (release == null || bgStageEnv.equals(release.getBgEnvironment())) {
So when the environment is stage then we skip the whole process and not delete anything. Only when the environment is primary then we find the stage color and scale down the stage environment.

2023-05-31 11:39 UTC, GoelPratyush99 commented
trigger uts

2023-05-31 12:16 UTC, GoelPratyush99 commented
trigger uts

2023-05-31 12:34 UTC, abhinavsingh1196 approved these changes

2023-05-31 12:53 UTC, abosii-harness approved these changes

2023-05-31 13:07 UTC, GoelPratyush99 commented
trigger review

2023-05-31 13:13 UTC, GoelPratyush99 commented
trigger messagecheck

2023-05-31 13:15 UTC, merged