feat: [CDS-58105]: Download manifests step integration in SAM
harness/harness-core pull request #48626
Opened 2023-06-01 03:35 UTC by sainath-b

## Describe your changes
Download manifests step integration in SAM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-01 03:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=48626) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=48626) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: sahilhindwani-harness<br/>:x: sainath-b<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=48626) it.</sub>

2023-06-06 05:27 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 61 at r6](https://reviewable.io/reviews/harness/harness-core/48626#-NXEA-ql9NcxTbNxP9Ur:-NXEA-ql9NcxTbNxP9Us:bxq3z15) ([raw file](https://github.com/harness/harness-core/blob/f415e74b8a12969e57dd1eac3dde2d7e12340145/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L61)):*
> ```Java
>     Map<String, String> envVarMap = new HashMap<>();
> 
>     awsSamStepHelper.putValuesYamlEnvVars(ambiance, awsSamBuildStepParameters, envVarMap);
> ```

nit: can we directly populate the map with this rather than modifying the reference?


<!-- Sent from Reviewable.io -->

2023-06-06 05:31 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 144 at r6](https://reviewable.io/reviews/harness/harness-core/48626#-NXEAy0N8RJfQGERH7ox:-NXEAy0N8RJfQGERH7oy:b-2llj5h) ([raw file](https://github.com/harness/harness-core/blob/f415e74b8a12969e57dd1eac3dde2d7e12340145/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L144)):*
> ```Java
>     StageInfraDetails stageInfraDetails = (StageInfraDetails) optionalSweepingOutput.getOutput();
> 
>     if (stageInfraDetails instanceof K8StageInfraDetails) {
> ```

Rather than using instanceOf, can we use the type?


<!-- Sent from Reviewable.io -->

2023-06-06 05:35 UTC, sainath-b commented
trigger uts

2023-06-06 06:49 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java` line 66 at r8](https://reviewable.io/reviews/harness/harness-core/48626#-NXESvKw6guCMqUyOeLu:-NXESvKx7vettVAunCG_:bz4jqsn) ([raw file](https://github.com/harness/harness-core/blob/c705ec94511a88b8634eb913ec7a9ef520df3b84/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java#L66)):*
> ```Java
> 
>   @Override
>   public AsyncExecutableResponse executeAsyncAfterRbac(
> ```

nit: can we write up a comment explaining as to what and why we are doing this?


<!-- Sent from Reviewable.io -->

2023-06-06 06:50 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java` line 110 at r8](https://reviewable.io/reviews/harness/harness-core/48626#-NXET0AaEUZFQu-1ukrS:-NXET0AaEUZFQu-1ukrT:bl86wb2) ([raw file](https://github.com/harness/harness-core/blob/c705ec94511a88b8634eb913ec7a9ef520df3b84/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java#L110)):*
> ```Java
>         .addAllCallbackIds(callbackIds)
>         .setStatus(samDirectoryAsyncExecutableResponse.getStatus())
>         .addAllLogKeys(samDirectoryAsyncExecutableResponse.getLogKeysList())
> ```

We might need to add log keys from gitClone step as well. Could you please check if we are getting correct logs?


<!-- Sent from Reviewable.io -->

2023-06-06 06:50 UTC, sahilhindwani-harness requested changes
> Reviewed 8 of 46 files at r6, 1 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48626)* status: 60 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStepParameters.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/48626#-NXESYVa83Vm2IceZ7Gw:-NXESYVbECcVxq9gs5TG:b-cbdkxz) ([raw file](https://github.com/harness/harness-core/blob/c705ec94511a88b8634eb913ec7a9ef520df3b84/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStepParameters.java#L39)):*
> ```Java
>   ParameterField<String> samBuildDockerRegistryConnectorRef;
> 
>   @JsonIgnore String downloadManifestsFqn;
> ```

why do we need this? Can we not publish an outcome at step group level and then use it here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 122 at r8](https://reviewable.io/reviews/harness/harness-core/48626#-NXESh7H7DI14gS0gGYm:-NXESh7H7DI14gS0gGYn:b-1s8xo) ([raw file](https://github.com/harness/harness-core/blob/c705ec94511a88b8634eb913ec7a9ef520df3b84/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L122)):*
> ```Java
>       }
> 
>       ObjectMapper objectMapper = new ObjectMapper().disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
> ```

Can we not reuse existing object mapper? 


<!-- Sent from Reviewable.io -->

2023-06-06 09:14 UTC, sainath-b commented
trigger uts

2023-06-06 17:23 UTC, sainath-b commented
trigger uts

2023-06-06 19:26 UTC, rohitk-h requested changes
> Reviewed 2 of 16 files at r4, 10 of 55 files at r5, 33 of 46 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, 5 of 6 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48626)* status: 54 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 88 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH5s2VBfGxmvN76g_5:-NXH5s2VBfGxmvN76g_6:b-96t4bd) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L88)):*
> ```Java
> 
>       String valuesYamlContent = awsSamValuesYamlDataOutcome.getValuesYamlContent();
>       String valuesYamlPath = awsSamValuesYamlDataOutcome.getValuesYamlPath();
> ```

Do we need to resolve expressions here? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 90 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH5BEADoIPBuPg2xY7:-NXH5BEADoIPBuPg2xY8:b-57hovx) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L90)):*
> ```Java
>       String valuesYamlPath = awsSamValuesYamlDataOutcome.getValuesYamlPath();
> 
>       if (StringUtils.isNotBlank(valuesYamlContent) && StringUtils.isNotBlank(valuesYamlPath)) {
> ```

Q: This doesn't process empty yaml files, is that a valid case? 
nit: add log lines when we populate envVars to aid in troubleshooting
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java` line 46 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH7JDCD0qKp9qK5IX0:-NXH7JDCD0qKp9qK5IX1:b-99j5qg) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java#L46)):*
> ```Java
> import org.apache.commons.lang3.StringUtils;
> 
> public class DownloadManifestsStep implements AsyncExecutableWithRbac<StepElementParameters> {
> ```

nit: we should log statements in this class. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java` line 128 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH7AhUDHXmao3eooAY:-NXH7AhUDHXmao3eooAZ:bkw5ye8) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java#L128)):*
> ```Java
>   @Override
>   public void handleAbort(
>       Ambiance ambiance, StepElementParameters stepParameters, AsyncExecutableResponse executableResponse) {}
> ```

Should this be implemented? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java` line 53 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH8lz4AQ_nO_0j6u39:-NXH8lz4AQ_nO_0j6u3A:b957gef) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java#L53)):*
> ```Java
>   public PluginCreationResponseWrapper getPluginInfo(
>       PluginCreationRequest request, Set<Integer> usedPorts, Ambiance ambiance) {
>     return null;
> ```

Is this intentional? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java` line 65 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH8v0U3DPPvQDfz6DA:-NXH8v0U3DPPvQDfz6DB:b-ilfku) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java#L65)):*
> ```Java
>     } catch (IOException e) {
>       throw new ContainerPluginParseException(
>           String.format("Error in parsing CI step for step type [%s]", request.getType()), e);
> ```

nit: CD step instead of CI
___
*[`879-pipeline-ci-commons/src/main/java/io/harness/cdng/plugininfoproviders/PluginInfoProviderHelper.java` line 68 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH9PViAjTXjKCf2FHW:-NXH9PViAjTXjKCf2FHX:b-rlzh6) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/879-pipeline-ci-commons/src/main/java/io/harness/cdng/plugininfoproviders/PluginInfoProviderHelper.java#L68)):*
> ```Java
>     pluginDetailsBuilder.addPortUsed(nextPort);
> 
>     //Todo Sainath
> ```

nit: can we add more details about the todo here
___
*[`879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/PluginServiceImpl.java` line 269 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH9fk5EiFl2eqjH8xE:-NXH9fk5EiFl2eqjH8xF:b-h12b09) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/PluginServiceImpl.java#L269)):*
> ```Java
>     Map<String, String> map = new HashMap<>();
> 
>     if (outputFilePathsContent != null && outputFilePathsContent.getValue() != null  && !CollectionUtils.isEmpty(outputFilePathsContent.getValue())) {
> ```

do we need to resolve expressions here? 
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java` line 61 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH9mOP6IxIuIE7pGDj:-NXH9mOP6IxIuIE7pGDk:bw6sbq) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitValidator.java#L61)):*
> ```Java
> 
>     if (MapUtils.isNotEmpty(unsupportedFilters) || MapUtils.isNotEmpty(unsupportedVariables)) {
>       //throw new PmsSdkPlanCreatorValidationException(unsupportedFilters, unsupportedVariables);
> ```

This doesn't seem to be intentional. 


<!-- Sent from Reviewable.io -->

2023-06-07 06:43 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +public class K8InitializeStepUtils extends K8InitializeServiceImpl {
Why utils extending K8InitializeServiceImpl
This needs to change

2023-06-07 06:43 UTC, harshjain12 commented on 879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/PluginServiceImpl.java
> +  private static Map<String, String> getPluginOutputFilePathsContent(ParameterField<List<String>> outputFilePathsContent) {
add uts for the methods which you have added

2023-06-07 06:45 UTC, harshjain12 commented on 879-pipeline-ci-commons/src/main/java/io/harness/plugin/service/PluginServiceImpl.java
> +    if (outputFilePathsContent != null && outputFilePathsContent.getValue() != null  && !CollectionUtils.isEmpty(outputFilePathsContent.getValue())) {
Check RunTimeInputHandler. It is already present there.
Do not duplicate this logic

2023-06-07 06:46 UTC, harshjain12 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java
> +public class DownloadManifestsPluginInfoProvider implements CDPluginInfoProvider {
uts for this class are missing completely

2023-06-07 06:48 UTC, harshjain12 requested changes

2023-06-07 06:48 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +public class K8InitializeStepUtils extends K8InitializeServiceImpl {
This class is for utility methods only

2023-06-07 13:07 UTC, sainath-b commented
trigger uts

2023-06-07 17:08 UTC, sainath-b commented
trigger uts

2023-06-07 17:51 UTC, harshjain12 submitted a review, later dismissed

2023-06-07 18:53 UTC, sainath-b commented
trigger uts

2023-06-08 05:26 UTC, sainath-b commented
trigger codeformat

2023-06-08 05:27 UTC, sainath-b commented
trigger messagecheck

2023-06-08 05:27 UTC, sainath-b commented
trigger pmd

2023-06-08 05:36 UTC, sainath-b commented
trigger codeformat

2023-06-08 13:30 UTC, sainath-b commented
trigger codeformat

2023-06-08 13:39 UTC, sainath-b commented
trigger uts

2023-06-08 14:41 UTC, sainath-b commented
trigger uts

2023-06-08 15:54 UTC, sainath-b reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48626)* status: 66 file(s) to review. 2 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto,del-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 61 at r6](https://reviewable.io/reviews/harness/harness-core/48626#-NXEA-ql9NcxTbNxP9Ur:-NXQgOTR8Zcf41gRhBWe:b72l94q) ([raw file](https://github.com/harness/harness-core/blob/f415e74b8a12969e57dd1eac3dde2d7e12340145/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L61)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: can we directly populate the map with this rather than modifying the reference?
</blockquote></details>

Will take care of this as separate code refactor PR.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStepParameters.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/48626#-NXESYVa83Vm2IceZ7Gw:-NXQgrO68pt9qEM1GAqf:bj1bt75) ([raw file](https://github.com/harness/harness-core/blob/c705ec94511a88b8634eb913ec7a9ef520df3b84/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStepParameters.java#L39)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why do we need this? Can we not publish an outcome at step group level and then use it here?
</blockquote></details>

Noted. Will address this as a part of separate PR.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 144 at r6](https://reviewable.io/reviews/harness/harness-core/48626#-NXEAy0N8RJfQGERH7ox:-NXQhICaDMrR3iniD2Ey:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f415e74b8a12969e57dd1eac3dde2d7e12340145/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L144)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Rather than using instanceOf, can we use the type?
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 122 at r8](https://reviewable.io/reviews/harness/harness-core/48626#-NXESh7H7DI14gS0gGYm:-NXQhH4j-Z_Wa-C5U1Jm:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c705ec94511a88b8634eb913ec7a9ef520df3b84/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L122)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we not reuse existing object mapper? 
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 88 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH5s2VBfGxmvN76g_5:-NXQh9uW04OnDYT5ZB3Y:b32w12) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L88)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Do we need to resolve expressions here? 
</blockquote></details>

No
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 90 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH5BEADoIPBuPg2xY7:-NXQhBFM5RjoBeYaLgLC:bgfs627) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L90)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Q: This doesn't process empty yaml files, is that a valid case? 
nit: add log lines when we populate envVars to aid in troubleshooting
</blockquote></details>

Yes. Its a valid case.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java` line 110 at r8](https://reviewable.io/reviews/harness/harness-core/48626#-NXET0AaEUZFQu-1ukrS:-NXQhVLM5GzbukmSICyb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c705ec94511a88b8634eb913ec7a9ef520df3b84/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java#L110)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We might need to add log keys from gitClone step as well. Could you please check if we are getting correct logs?
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java` line 46 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH7JDCD0qKp9qK5IX0:-NXQhJJYEa8OptqiXbV6:b-cdz0b3) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java#L46)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nit: we should log statements in this class. 
</blockquote></details>

Noted. will add it as a part of separate PR.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java` line 128 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH7AhUDHXmao3eooAY:-NXQhWlD8HT7Nzzz6_f4:bwn0gsx) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/DownloadManifestsStep.java#L128)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Should this be implemented? 
</blockquote></details>

Not Required
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/48626#gh-1220960652:-NXQhZNMASiBaz_riu_g:b-wr8coo) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java#L38)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

uts for this class are missing completely 
</blockquote></details>

Planned UTs as a part of different task
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java` line 53 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH8lz4AQ_nO_0j6u39:-NXQhcx2BXkbawRsJMha:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java#L53)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Is this intentional? 
</blockquote></details>

Yes
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java` line 65 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH8v0U3DPPvQDfz6DA:-NXQhe0w3eGM0bM3_7TW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/DownloadManifestsPluginInfoProvider.java#L65)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nit: CD step instead of CI
</blockquote></details>

Done
___
*[`879-pipeline-ci-commons/src/main/java/io/harness/cdng/plugininfoproviders/PluginInfoProviderHelper.java` line 68 at r10](https://reviewable.io/reviews/harness/harness-core/48626#-NXH9PViAjTXjKCf2FHW:-NXQhfVw8ykWg_C5G3sT:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/95c7b77927e9ca1b1e96366d021363cd9ecfd03d/879-pipeline-ci-commons/src/main/java/io/harness/cdng/plugininfoproviders/PluginInfoProviderHelper.java#L68)):*
< [...]

2023-06-08 16:35 UTC, sainath-b commented
trigger uts

2023-06-08 16:36 UTC, sainath-b commented
trigger messagecheck

2023-06-08 16:51 UTC, harshjain12 approved these changes

2023-06-08 17:09 UTC, sahilhindwani-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48626)* status: 66 file(s) to review. 1 change requests. 13. unresolved discussions. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-06-08 17:28 UTC, sainath-b commented
trigger review

2023-06-08 17:37 UTC, rohitk-h reviewed
> Reviewed 6 of 8 files at r11, 3 of 14 files at r12, 4 of 7 files at r13, 1 of 1 files at r14, 16 of 17 files at r15, 2 of 3 files at r16, 7 of 7 files at r17, 2 of 2 files at r18, 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48626)* status: 66 file(s) to review. 1 change requests. 8. unresolved discussions. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-06-08 17:43 UTC, rohitk-h submitted a review, later dismissed

2023-06-09 10:03 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 16 files at r4, 4 of 55 files at r5, 14 of 46 files at r6, 1 of 1 files at r7, 1 of 6 files at r8, 2 of 6 files at r9, 2 of 4 files at r10, 6 of 8 files at r11, 3 of 14 files at r12, 4 of 7 files at r13, 1 of 1 files at r14, 16 of 17 files at r15, 2 of 3 files at r16, 7 of 7 files at r17, 2 of 2 files at r18, 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48626)* status: 6. unresolved discussions. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-06-09 13:42 UTC, r0610205 submitted a review, later dismissed

2023-06-09 13:44 UTC, atmollo-harness submitted a review, later dismissed

2023-06-09 13:54 UTC, jamie-harness submitted a review, later dismissed

2023-06-09 15:53 UTC, sainath-b commented
trigger uts

2023-06-10 13:04 UTC, sainath-b commented
trigget uts

2023-06-10 13:04 UTC, sainath-b commented
trigger uts

2023-06-10 15:56 UTC, sainath-b commented
trigger uts

2023-06-11 03:42 UTC, sainath-b commented
trigger uts

2023-06-11 04:17 UTC, sainath-b commented
trigger uts

2023-06-11 08:55 UTC, sainath-b commented
trigger uts

2023-06-11 13:29 UTC, merged