feat: [CDS-54470]: Delete previous Perpetual Task if new Perpetual Task is successful  instance sync V2
harness/harness-core pull request #48648
Opened 2023-06-01 09:39 UTC by namantalaycha10

## Describe your changes
Delete previous Perpetual Task if new Perpetual Task is successful executed first time for instance sync V2

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-01 09:42 UTC, namantalaycha10 commented
trigger uts

2023-06-01 10:19 UTC, abosii-harness requested changes
Please review logic at io/harness/service/instancesync/InstanceSyncServiceImpl.java:298 when connector not found we're ending up in deleting v1 pt and not v2. As well null check is missing

2023-06-01 10:19 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +              && isSupportedDeploymentType(deploymentSummaryDTO.getDeploymentInfoDTO().getType())) {
I don't think this is required, logic around if instance sync v2 is enabled should be based on AbstractInstanceSyncHandler, for now we can keep the current logic for testing purpose

2023-06-01 10:53 UTC, namantalaycha10 commented
trigger uts

2023-06-01 13:58 UTC, namantalaycha10 commented
trigger uts

2023-06-01 14:04 UTC, abosii-harness requested changes

2023-06-01 14:04 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +  private boolean isSupportedDeploymentType(String DeploymentType) {
Not needed

2023-06-01 14:30 UTC, namantalaycha10 commented
trigger uts

2023-06-02 04:58 UTC, namantalaycha10 commented
trigger uts

2023-06-02 05:09 UTC, namantalaycha10 commented
trigger ut0

2023-06-02 05:38 UTC, abosii-harness approved these changes

2023-06-02 05:41 UTC, GoelPratyush99 approved these changes

2023-06-02 05:42 UTC, namantalaycha10 commented
trigger review

2023-06-02 05:43 UTC, merged