feat: [PL-38908]: Unit tests for Fav utils classes and adding indexes.
harness/harness-core pull request #48682
Opened 2023-06-01 17:53 UTC by boopesh007

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-02 06:20 UTC, boopesh007 commented
trigger uts

2023-06-02 06:51 UTC, boopesh007 commented
trigger uts

2023-06-02 23:27 UTC, gn-harness commented on 120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/FavoritesValidatorTest.java
> +                .connector(ConnectorInfoDTO.builder().connectorConfig(NexusConnectorDTO.builder().build()).build())
none of these tests are needed

2023-06-02 23:27 UTC, gn-harness commented on 120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/FavoritesValidatorTest.java
> +                .connector(ConnectorInfoDTO.builder().connectorConfig(NexusConnectorDTO.builder().build()).build())
You should write tests on the actual contract. These are tests on the implementation details

i.e. You try creating a favorite and that should return InvalidException or whatever, if invalid entity is passed in.

2023-06-03 07:15 UTC, boopesh007 commented on 120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/entities/BUILD.bazel
> +        "//960-persistence:module",
For adding the index, I want to reference the Mongo module in the persistence package, but it does not have a .bazel file, hence the up hierarchy, I had to reference the whole package.

2023-06-03 07:17 UTC, boopesh007 commented on 120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/FavoritesValidatorTest.java
> +                .connector(ConnectorInfoDTO.builder().connectorConfig(NexusConnectorDTO.builder().build()).build())
The actual tests on the contract are also there @gn-harness, it was merged in the last PR. I had the same thought as yours but there was a comment to cover unit tests for these as well. cc: @nishantsaini20 @rijajoo

2023-06-03 07:30 UTC, boopesh007 commented
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Create one more test with multiple favorites
</blockquote></details>

Done




<!-- Sent from Reviewable.io -->

2023-06-03 07:48 UTC, boopesh007 commented on 120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/FavoritesResourceUtilsTest.java
> +        favoritesResourceUtils.toFavoriteResponse(Collections.singletonList(favorite));
Done

2023-06-03 07:50 UTC, boopesh007 commented
trigger uts

2023-06-03 10:39 UTC, boopesh007 commented
trigger uts

2023-06-03 10:55 UTC, boopesh007 commented
trigger ut1

2023-06-05 06:32 UTC, boopesh007 commented
trigger uts

2023-06-06 06:40 UTC, nishantsaini20 requested changes

2023-06-06 06:42 UTC, nishantsaini20 commented on 120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/remote/AccountFavoritesApiImpl.java
> -  public Response getAccountFavorites(String userId, String harnessAccount, FavoritesResourceType resourceType) {
Why these reverts related to `FavoritesResourceType`?

2023-06-06 06:48 UTC, nishantsaini20 requested changes

2023-06-06 06:48 UTC, nishantsaini20 commented on 120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/remote/AccountFavoritesApiImpl.java
> -  public Response getAccountFavorites(String userId, String harnessAccount, FavoritesResourceType resourceType) {
Why these reverts related to `FavoritesResourceType`?

2023-06-06 06:48 UTC, nishantsaini20 commented on 120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/impl/FavoritesServiceImpl.java
> +      String accountIdentifier, String orgIdentifier, String projectIdentifier, String userId, String resourceTypeDTO) {
Why list call has `resourceTypeDTO`? If it is required then why `orgIdentifier` and `projectIdentifier` are required as separate arguments. They can be part of DTO itself.

2023-06-06 06:48 UTC, nishantsaini20 commented on 120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/impl/FavoritesServiceImpl.java
> +      String resourceTypeDTO, String resourceId) throws InvalidRequestException {
Same here. Why is resourceTypeDTO required in delete call?

2023-06-06 06:48 UTC, boopesh007 commented
trigger uts

2023-06-06 07:18 UTC, boopesh007 commented
trigger uts

2023-06-07 11:18 UTC, boopesh007 commented
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Shouldn't the order of fields be as, accountIdentifier->userIdentifier->org->proj->resourceType->id?
</blockquote></details>

Done.




<!-- Sent from Reviewable.io -->

2023-06-07 11:20 UTC, boopesh007 commented
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Was this not changed to FavoritesResourceType in earlier PR? Why this reverted back?
</blockquote></details>

Its because UI code generation is failing when we reference the FavoritesResourceType in the queryParams.
cc: @avinashmadhwani02




<!-- Sent from Reviewable.io -->

2023-06-07 11:21 UTC, boopesh007 commented
*[`120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/remote/AccountFavoritesApiImpl.java` line 0 at r4](https://reviewable.io/reviews/harness/harness-core/48682#gh-1219008124:-NXK_dXq--T1pG_ER1tb:b-dn6go6) ([raw file](https://github.com/harness/harness-core/blob/e8c7094ee185f86dbc0d46e0a7e3255ea7d97b16/120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/remote/AccountFavoritesApiImpl.java#L0)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Why these reverts related to `FavoritesResourceType`?
</blockquote></details>

Its because UI code generation is failing when we reference the FavoritesResourceType in the queryParams.
cc: @avinashmadhwani02


<!-- Sent from Reviewable.io -->

2023-06-07 11:21 UTC, boopesh007 commented
*[`120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/impl/FavoritesServiceImpl.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/48682#gh-1219012066:-NXK_hbO1p26hm3_jaTB:b5t4gye) ([raw file](https://github.com/harness/harness-core/blob/e8c7094ee185f86dbc0d46e0a7e3255ea7d97b16/120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services/impl/FavoritesServiceImpl.java#L56)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why list call has `resourceTypeDTO`? If it is required then why `orgIdentifier` and `projectIdentifier` are required as separate arguments. They can be part of DTO itself.
</blockquote></details>

Renamed it 


<!-- Sent from Reviewable.io -->

2023-06-07 15:03 UTC, gn-harness approved these changes

2023-06-08 11:24 UTC, boopesh007 commented
trigger uts

2023-06-08 12:17 UTC, nishantsaini20 submitted a review, later dismissed

2023-06-08 12:17 UTC, nishantsaini20 commented on 120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/utils/FavoritesValidatorTest.java
> +                .connector(ConnectorInfoDTO.builder().connectorConfig(NexusConnectorDTO.builder().build()).build())
These test not validating anything. When a specific validator doesn't return an entity then `validateFavoriteEntry` is expected to throw an exception and should what these tests should be validating.

2023-06-08 16:53 UTC, boopesh007 commented
trigger uts

2023-06-09 04:55 UTC, boopesh007 commented
trigger uts

2023-06-09 05:35 UTC, boopesh007 commented on 120-ng-manager/modules/favorites/src/test/java/io/harness/favorites/remote/FavoritesOrgApiImplTest.java
> +        .deleteFavorite(accountId, orgId, null, userId, "Random", resourceId);
Including the changes for this in the subsequent PR @nishantsaini20

2023-06-09 10:45 UTC, boopesh007 commented
trigger uts

2023-06-09 12:10 UTC, nishantsaini20 commented on 120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/utils/FavoritesValidator.java
> +              "The Resource with ID %s and type %s, which is being marked as favorite does not exist in account %s",
Wrap value of ID and type in square brackets 
`"The Resource with ID [%s] and type [%s], which is being marked as favorite does not exist"`

2023-06-09 12:12 UTC, nishantsaini20 submitted a review, later dismissed

2023-06-09 12:13 UTC, boopesh007 commented on 120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/utils/FavoritesValidator.java
> +              "The Resource with ID %s and type %s, which is being marked as favorite does not exist in account %s",
Will incorporate in the upcoming PR.

2023-06-09 12:20 UTC, boopesh007 commented
trigger uts

2023-06-09 12:22 UTC, nishantsaini20 approved these changes

2023-06-09 14:29 UTC, gn-harness approved these changes

2023-06-12 05:38 UTC, boopesh007 commented
trigger uts

2023-06-12 07:23 UTC, boopesh007 commented
trigger uts

2023-06-12 11:35 UTC, boopesh007 commented
trigger uts

2023-06-12 12:50 UTC, boopesh007 commented
trigger ut5

2023-06-12 12:58 UTC, merged