feat: [CDS-70186]: Added support for secrets command step output variables
harness/harness-core pull request #48690
Opened 2023-06-02 00:35 UTC by ivan-83

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-02 00:36 UTC, ivan-83 commented
trigger uts

2023-06-02 12:39 UTC, vitsafronovici commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/sshwinrm/SshWinRmStageExecutionDetails.java
> +    return Collections.emptySet();
why emptySet?

2023-06-05 07:41 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java
> +    List<String> outputVarValues = new ArrayList<>();
nit `new ArrayList(outputVariables.size())`

2023-06-05 07:44 UTC, acasian-harness requested changes

2023-06-05 07:44 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java
> +    List<String> outputVarValues = new ArrayList<>();
nit `new ArrayList(outputVariables.size())`

2023-06-05 07:44 UTC, acasian-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java
> +  @Expression(ALLOW_SECRETS) List<String> secretOutputVariables;
why do w e need a separate field for secret output vars?

2023-06-05 07:44 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java
> +  public static List<String> getSecretOutputVariableValues(
i think we will need a new delegate task in order to not have kryo issues or backward compatibility.

2023-06-05 14:52 UTC, ivan-83 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48690)* status: 24 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/sshwinrm/SshWinRmStageExecutionDetails.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/48690#gh-1214324647:-NXAwRQz2PP5lDKzGVa5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a41cfff9f4ce57dd8f1111fac8fda70cc053df0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/sshwinrm/SshWinRmStageExecutionDetails.java#L54)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

why emptySet? 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/48690#gh-1217657054:-NXAwT7268zxh8Fl0C8j:b-7l0xi8) ([raw file](https://github.com/harness/harness-core/blob/2a41cfff9f4ce57dd8f1111fac8fda70cc053df0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java#L90)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

nit `new ArrayList(outputVariables.size())`
</blockquote></details>

The size outputVarValue list depends on two input method params outputVariables and secretOutputVariableNames. It requires additional calculations of size, hence skipping it. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/48690#gh-1217660497:-NXAxC1q3t_VMY18yCk5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a41cfff9f4ce57dd8f1111fac8fda70cc053df0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java#L108)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i think we will need a new delegate task in order to not have kryo issues or backward compatibility.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/48690#gh-1217657164:-NXAxEKe9WkErfkENf9G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a41cfff9f4ce57dd8f1111fac8fda70cc053df0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java#L114)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

nit `new ArrayList(outputVariables.size())`
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/48690#gh-1217659232:-NXAxHAr2uFHg23uEqEA:bj9dw3t) ([raw file](https://github.com/harness/harness-core/blob/2a41cfff9f4ce57dd8f1111fac8fda70cc053df0/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java#L58)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why do w e need a separate field for secret output vars?
</blockquote></details>

To propagate a list of secrets from CommandStepInfo based on NGVariable. That's the only way how we for sure know the list of secrets. 


<!-- Sent from Reviewable.io -->

2023-06-05 14:58 UTC, ivan-83 commented
trigger uts

2023-06-06 10:44 UTC, acasian-harness submitted a review, later dismissed

2023-06-06 12:00 UTC, vitsafronovici submitted a review, later dismissed

2023-06-06 12:08 UTC, ivan-83 commented
trigger review

2023-06-07 09:57 UTC, yogesh-chauhan reviewed
> Reviewed 11 of 15 files at r1, 9 of 13 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48690)* status: 23 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java` line 136 at r4](https://reviewable.io/reviews/harness/harness-core/48690#-NXKGbyi9B--wvF6tbtN:-NXKGbyi9B--wvF6tbtO:b-ddignq) ([raw file](https://github.com/harness/harness-core/blob/6e36bf8fcdc7563d0a755fc1ffe5bf6b1cc5986a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/rollback/CommandStepRollbackHelper.java#L136)):*
> ```Java
>         commandStepParameters.getOutputVariables(), commandStepParameters.getSecretOutputVariablesNames());
>     List<String> secretOutputVariables = getSecretOutputVariableValues(
>         commandStepParameters.getOutputVariables(), commandStepParameters.getSecretOutputVariablesNames());
> ```

maybe better to write 1 method which returns both "outputVariables" and "secretOutputVariables"
```
class OutputVariables {
   List<String> regularVariables;
   List<String> secretVariables;
}

OutputVariables variables = getOutputVariables(commandStepParameters.getOutputVariables(), commandStepParameters.getSecretOutputVariablesNames())
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 233 at r4](https://reviewable.io/reviews/harness/harness-core/48690#-NXKHQzBBe33bu91p-AW:-NXKHQzBBe33bu91p-AX:b-7rv0o0) ([raw file](https://github.com/harness/harness-core/blob/6e36bf8fcdc7563d0a755fc1ffe5bf6b1cc5986a/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L233)):*
> ```Java
>     ShellExecutionDataBuilder executionDataBuilder = ShellExecutionData.builder();
>     secretEnvVariablesToCollect =
>         secretEnvVariablesToCollect == null ? Collections.emptyList() : secretEnvVariablesToCollect;
> ```

nit: ``` CollectionUtils.emptyIfNull(secretEnvVariablesToCollect) ``` 


<!-- Sent from Reviewable.io -->

2023-06-07 09:59 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48690)* status: 23 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-07 10:24 UTC, ivan-83 commented
trigger uts

2023-06-07 10:45 UTC, vitsafronovici approved these changes

2023-06-07 10:45 UTC, ivan-83 commented
trigger review

2023-06-07 10:47 UTC, merged

2023-06-07 10:47 UTC, acasian-harness approved these changes