feat:[CDS-70330]: Resource for encrypting and decrypting harness SM for TF plan
harness/harness-core pull request #48706
Opened 2023-06-02 10:20 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-02 11:01 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48706)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/EncryptionDecryptionResource.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/48706#-NWvlH5XBbQjeei1rVBP:-NWvlH5XBbQjeei1rVBQ:b-qhnp5r) ([raw file](https://github.com/harness/harness-core/blob/35e144c1ed851c33eb7be8cea960008f93ad4840/400-rest/src/main/java/software/wings/resources/EncryptionDecryptionResource.java#L44)):*
> ```Java
>   @DelegateAuth
>   @POST
>   @Path("/encrypt-HarnessSM-secret")
> ```

path is case insensitive


<!-- Sent from Reviewable.io -->

2023-06-02 11:03 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48706)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/48706#-NWvlhzU64-RQKoNBQBZ:-NWvlhzU64-RQKoNBQB_:bgt5x6l) ([raw file](https://github.com/harness/harness-core/blob/35e144c1ed851c33eb7be8cea960008f93ad4840/400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java#L31)):*
> ```Java
> @OwnedBy(CDP)
> public class EncryptionDecryptionServiceImpl implements EncryptionDecryptionService {
>   @Inject protected KmsEncryptorsRegistry kmsEncryptorsRegistry;
> ```

protected for some reason?


<!-- Sent from Reviewable.io -->

2023-06-02 11:04 UTC, mohitg0795 commented
*[`400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/48706#-NWvloy-0YJvPb2Uj4xa:-NWvloy-0YJvPb2Uj4xb:bvdnp4l) ([raw file](https://github.com/harness/harness-core/blob/35e144c1ed851c33eb7be8cea960008f93ad4840/400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java#L41)):*
> ```Java
>   }
> 
>   private EncryptedRecord encryptKmsSecret(String value, EncryptionConfig encryptionConfig) {
> ```

nit: move private methods at the last of the file for better readability


<!-- Sent from Reviewable.io -->

2023-06-02 11:55 UTC, yogesh-chauhan requested changes

2023-06-02 11:55 UTC, yogesh-chauhan commented on 400-rest/src/main/java/software/wings/resources/EncryptionDecryptionResource.java
> +@Produces("application/json")
can we have a better name like DelegateManagerClient etc

2023-06-02 11:55 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/managerclient/EncryptionDecryptionHarnessSMClient.java
> +@TargetModule(HarnessModule._420_DELEGATE_AGENT)
target is not needed

2023-06-02 11:55 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/managerclient/EncryptionDecryptionHarnessSMClient.java
> +      @Query("accountId") String accountId, @Body RequestBody content);
we should mark accountId as not null

2023-06-02 11:57 UTC, yogesh-chauhan requested changes

2023-06-02 11:57 UTC, yogesh-chauhan commented on 400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java
> +    SecretManagerConfig secretManagerConfig = secretManagerConfigService.getDefaultSecretManager(accountId);
this should be getGlobalSecretManager(..)

2023-06-05 07:18 UTC, sourabh-awashti commented on 400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java
> +    SecretManagerConfig secretManagerConfig = secretManagerConfigService.getDefaultSecretManager(accountId);
done

2023-06-05 07:18 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/managerclient/EncryptionDecryptionHarnessSMClient.java
> +@TargetModule(HarnessModule._420_DELEGATE_AGENT)
done

2023-06-05 07:18 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/managerclient/EncryptionDecryptionHarnessSMClient.java
> +      @Query("accountId") String accountId, @Body RequestBody content);
done

2023-06-05 07:18 UTC, sourabh-awashti commented
*[`400-rest/src/main/java/software/wings/resources/EncryptionDecryptionResource.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/48706#gh-1214276923:-NX9Q2HJCSYJ_E61jYkn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/35e144c1ed851c33eb7be8cea960008f93ad4840/400-rest/src/main/java/software/wings/resources/EncryptionDecryptionResource.java#L36)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we have a better name like DelegateManagerClient etc
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-05 07:19 UTC, sourabh-awashti commented
*[`400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/48706#-NWvlhzU64-RQKoNBQBZ:-NX9Q4iO2LdTjU9JjTiq:bx9f9oe) ([raw file](https://github.com/harness/harness-core/blob/35e144c1ed851c33eb7be8cea960008f93ad4840/400-rest/src/main/java/software/wings/service/impl/EncryptionDecryptionServiceImpl.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

protected for some reason?
</blockquote></details>

will remove it


<!-- Sent from Reviewable.io -->

2023-06-06 17:23 UTC, mohitg0795 commented
*[`400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/48706#-NXGj0dXEqQQboDM7tkw:-NXGj0dXEqQQboDM7tkx:blqzax2) ([raw file](https://github.com/harness/harness-core/blob/f9a01802b8c0f1ac3bc3474301ee20a87f2493cd/400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java#L51)):*
> ```Java
>     } catch (Exception e) {
>       log.error(format("Unable to encrypt the content for harness secret manager for account %s", accountId), e);
>       return new RestResponse<>(EncryptedRecordData.builder().build());
> ```

this should be error response


<!-- Sent from Reviewable.io -->

2023-06-06 17:24 UTC, mohitg0795 commented
*[`400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/48706#-NXGj8xg7k3GT4iMtenQ:-NXGj8xg7k3GT4iMtenR:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/f9a01802b8c0f1ac3bc3474301ee20a87f2493cd/400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java#L65)):*
> ```Java
>     } catch (Exception e) {
>       log.error(format("Unable to decrypt the content for harness secret manager for account %s", accountId), e);
>       return new RestResponse<>(DecryptedRecord.builder().decryptedValue(new char[0]).build());
> ```

same here


<!-- Sent from Reviewable.io -->

2023-06-06 17:25 UTC, mohitg0795 commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateManagerEncryptionDecryptionHarnessSMServiceImpl.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/48706#-NXGjWHL7hHCcunPYNc-:-NXGjWHL7hHCcunPYNc0:b-ooavak) ([raw file](https://github.com/harness/harness-core/blob/f9a01802b8c0f1ac3bc3474301ee20a87f2493cd/400-rest/src/main/java/software/wings/service/impl/DelegateManagerEncryptionDecryptionHarnessSMServiceImpl.java#L37)):*
> ```Java
>   @Override
>   public EncryptedRecordData encryptData(String accountId, byte[] content) {
>     String value = new String(CHARSET.decode(ByteBuffer.wrap(encodeBase64ToByteArray(content))).array());
> ```

this should be done inside a util


<!-- Sent from Reviewable.io -->

2023-06-06 17:29 UTC, mohitg0795 submitted a review, later dismissed
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48706)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-07 10:20 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48706)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-06-07 14:18 UTC, sourabh-awashti commented
trigger uts

2023-06-07 16:00 UTC, sourabh-awashti commented
*[`400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/48706#-NXGj0dXEqQQboDM7tkw:-NXL_WEF8SyNLaSWncVd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9a01802b8c0f1ac3bc3474301ee20a87f2493cd/400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be error response
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-07 16:00 UTC, sourabh-awashti commented
*[`400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/48706#-NXGj8xg7k3GT4iMtenQ:-NXL_XYT4e2WHEe6MCo7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9a01802b8c0f1ac3bc3474301ee20a87f2493cd/400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResource.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-07 17:20 UTC, mohitg0795 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48706)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-07 17:22 UTC, sourabh-awashti commented
trigger uts

2023-06-07 17:30 UTC, sourabh-awashti commented
trigger messagecheck

2023-06-08 04:23 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48706)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-06-08 04:24 UTC, yogesh-chauhan commented
trigger review

2023-06-08 04:31 UTC, sourabh-awashti commented
trigger review

2023-06-08 04:34 UTC, merged