fix:[PL-38776] Fix pagination in secrets list api in CG
harness/harness-core pull request #48769
Opened 2023-06-05 01:08 UTC by adiyaar24

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-05 06:39 UTC, adiyaar24 commented
trigger messagecheck

2023-06-05 11:16 UTC, adiyaar24 commented
trigger uts

2023-06-20 06:49 UTC, tiwaritejas commented on 890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java
> +      PageResponse<EncryptedData> batchPageResponse = secretsDao.listSecrets(a1);
We are fetching all the secrets in the account even though this is a paginated call. Can't we run a count query here instead of actually fetching all the documents? Just wondering if this might cause any slowness in case the account has a lot of secrets.

2023-07-03 12:40 UTC, adiyaar24 commented
trigger uts

2023-07-04 09:16 UTC, nishantsaini20 requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48769)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java` line 793 at r3](https://reviewable.io/reviews/harness/harness-core/48769#-NZVA03_DUT8T56r0UCf:-NZVA03_DUT8T56r0UCg:b-tduptz) ([raw file](https://github.com/harness/harness-core/blob/e14375b2c8f98d33c8ab6a711a8ed1f8b3d7fa6b/890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java#L793)):*
> ```Java
> 
>     try {
>       PageRequest<EncryptedData> a1 = pageRequest.copy();
> ```

Change variable name from a1 to something meaningful.
___
*[`890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java` line 814 at r3](https://reviewable.io/reviews/harness/harness-core/48769#-NZVAdYA7cJ_Fgam99cu:-NZVAdYA7cJ_Fgam99cv:b-4khujf) ([raw file](https://github.com/harness/harness-core/blob/e14375b2c8f98d33c8ab6a711a8ed1f8b3d7fa6b/890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java#L814)):*
> ```Java
>           response = filteredEncryptedDataList.subList(offset, endIdx);
>         }
>       }
> ```

Try simplifying this if-else. We should try to avoid nested blocks.


<!-- Sent from Reviewable.io -->

2023-07-05 03:57 UTC, nishantsaini20 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48769)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java` line 803 at r4](https://reviewable.io/reviews/harness/harness-core/48769#-NZZAot4CTpHR363xt8Z:-NZZAot4CTpHR363xt8_:b45h) ([raw file](https://github.com/harness/harness-core/blob/00d77495f36fe3012239746f5b579448c8788c72/890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java#L803)):*
> ```Java
>       filterSecreteDataBasedOnUsageRestrictions(accountId, appId, envId, encryptedDataList, filteredEncryptedDataList);
> 
>       if (filteredEncryptedDataList.isEmpty() || filteredEncryptedDataList.size() <= offset) {
> ```





_Code snippet:_
```Java
if (isNotEmpty(filteredEncryptedDataList) && filteredEncryptedDataList.size() > offset) {
  int endIdx = Math.min(offset + limit, filteredEncryptedDataList.size());
  response = filteredEncryptedDataList.subList(offset, endIdx);
} else {
  response = Collections.emptyList();
}
```


<!-- Sent from Reviewable.io -->

2023-07-05 05:00 UTC, adiyaar24 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48769)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java` line 799 at r2](https://reviewable.io/reviews/harness/harness-core/48769#gh-1234811975:-NZZQ0kr0_fsCeYSamfx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/17b45185acc432ab18db3219734c2e069ec734b9/890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java#L799)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

We are fetching all the secrets in the account even though this is a paginated call. Can't we run a count query here instead of actually fetching all the documents? Just wondering if this might cause any slowness in case the account has a lot of secrets.
</blockquote></details>

Done.
___
*[`890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java` line 793 at r3](https://reviewable.io/reviews/harness/harness-core/48769#-NZVA03_DUT8T56r0UCf:-NZZPog60Zt3LnmGBc1a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e14375b2c8f98d33c8ab6a711a8ed1f8b3d7fa6b/890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java#L793)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Change variable name from a1 to something meaningful.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 08:47 UTC, adiyaar24 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48769)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java` line 803 at r4](https://reviewable.io/reviews/harness/harness-core/48769#-NZZAot4CTpHR363xt8Z:-NZ_Dx3dD7OSuzIUesi7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/00d77495f36fe3012239746f5b579448c8788c72/890-sm-core/src/main/java/io/harness/secrets/SecretServiceImpl.java#L803)):*
> ```Java
>       filterSecreteDataBasedOnUsageRestrictions(accountId, appId, envId, encryptedDataList, filteredEncryptedDataList);
> 
>       if (filteredEncryptedDataList.isEmpty() || filteredEncryptedDataList.size() <= offset) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 08:47 UTC, adiyaar24 commented
trigger uts

2023-07-05 08:50 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48769)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-05 09:09 UTC, merged