feat: [CDS-54471]: NG: Implement rollback logic from new Perpetual Task to old Perpetual Task
harness/harness-core pull request #48799
Opened 2023-06-05 11:24 UTC by namantalaycha10

## Describe your changes
 NG: Implement rollback logic from new Perpetual Task to old Perpetual Task
 this logic is to recreate the deleted V1 PTs and delete the V2 PTs

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-05 11:51 UTC, namantalaycha10 commented
trigger uts

2023-06-05 12:01 UTC, abosii-harness requested changes

2023-06-05 12:01 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +      case KUBERNETES_DIRECT:
We do have a lot of places with logic around this introduced with V2. Can we somehow keep everything in one place and have the logic in common? This would be a challenge to add new infrastructure kind

2023-06-05 12:01 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +    instanceSyncPerpetualTaskInfoService.updatePerpetualTaskIdV2(instanceSyncPerpetualTaskInfoDTO);
Don't we need to update and perpetualTaskId?

2023-06-06 17:01 UTC, abosii-harness submitted a review, later dismissed

2023-06-07 04:53 UTC, namantalaycha10 commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +              "Deleted instance sync perpetual task info : {} and perpetual task as there is no deployment info to do instance sync",
ack

2023-06-07 05:40 UTC, namantalaycha10 commented
trigger uts

2023-06-07 06:02 UTC, abosii-harness approved these changes

2023-06-07 06:04 UTC, GoelPratyush99 approved these changes

2023-06-07 06:05 UTC, namantalaycha10 commented
trigger review

2023-06-07 06:10 UTC, merged