fix: [PL-38828]: Added RBAC check to list Connectors when specific selected.
harness/harness-core pull request #48825
Opened 2023-06-05 18:34 UTC by Jimit09Gandhi

## Describe your changes
Added RBAC check to list Connectors when specific selected.

## Checklist
- [X] I've documented the changes in the PR description.
- [] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-09 05:13 UTC, meenakshi-harness requested changes

2023-06-09 05:13 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
> +      List<String> connectorIds) {
Can we use filterProperties for sending connector Ids?

2023-06-09 05:13 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java
> +      Boolean getDistinctFromBranches, Pageable pageable, List<String> connectorIds) {
same

2023-06-09 05:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      return ResponseDTO.newResponse(getNGPageResponse(Page.empty()));
We should throw an error here for user not having access to view connector.

2023-06-09 05:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +      return ResponseDTO.newResponse(getNGPageResponse(Page.empty()));
same as above

2023-06-09 05:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +    if (accessControlClient.hasAccess(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
This API is deprecated, can we check if its not used in UI, we can skip the changes here

2023-06-09 05:13 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java
> +          ConnectorStatistics.builder().statusStats(emptyList()).typeStats(emptyList()).build());
same here

2023-06-12 07:37 UTC, nishantsaini20 commented on 440-connector-nextgen/src/main/java/io/harness/connector/helper/ConnectorRbacHelper.java
> +    Map<EntityScopeInfo, List<Connector>> connectorsMap =
Does `EntityScopeInfo` has equals and hashcode methods correctly implemented?

2023-06-12 07:37 UTC, nishantsaini20 commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java
> +      criteria.and(ConnectorKeys.id).in(connectorIds);
Is this intended for `_id` field? Please verify when using `ConnectorKeys.id` correct index is getting used or not.

2023-06-13 18:24 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48825)* status: 28 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java` line 762 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1223846349:-NXor-EW3SoR-dAjgcUr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L762)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Can we use filterProperties for sending connector Ids?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java` line 824 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1223847527:-NXor-a9-c_sRLNHPIZA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L824)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1223850354:-NXor0fH8fMlV6d14uAR:b-ho0ub9) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L261)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

This API is deprecated, can we check if its not used in UI, we can skip the changes here
</blockquote></details>

This API is invoked from UI.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java` line 271 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1223849788:-NXorB4Q1dFDVsopp4rP:b-4lyrh4) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L271)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

We should throw an error here for user not having access to view connector.
</blockquote></details>

Done. Implemented in getPermitted.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java` line 328 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1223850074:-NXorKYY1eKH997At-rI:b-4lyrh4) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L328)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done. Implemented in getPermitted.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java` line 616 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1223851153:-NXorLOC3u-73Rtf0YA-:b-4lyrh4) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L616)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done. Implemented in getPermitted.


<!-- Sent from Reviewable.io -->

2023-06-18 20:46 UTC, Jimit09Gandhi commented
trigger uts

2023-06-19 05:21 UTC, Jimit09Gandhi commented
trigger uts

2023-06-19 12:29 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48825)* status: 30 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1226193161:-NYIcO4xDb7kEbz6bUki:bivu6v8) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L94)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is this intended for `_id` field? Please verify when using `ConnectorKeys.id` correct index is getting used or not. 
</blockquote></details>

yes, checked it will use existing indexes or index on _id field.


<!-- Sent from Reviewable.io -->

2023-06-19 14:14 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48825)* status: 30 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/ConnectorRbacHelper.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/48825#gh-1226188380:-NYJ-Je5CRQeB3HM6cPQ:b-3vkcdu) ([raw file](https://github.com/harness/harness-core/blob/b3dd4e5280f6996176deec0bdf6f2fd7b649aad1/440-connector-nextgen/src/main/java/io/harness/connector/helper/ConnectorRbacHelper.java#L124)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Does `EntityScopeInfo` has equals and hashcode methods correctly implemented?
</blockquote></details>

Yes `EntityScopeInfo` is annotated with @Value and @Value internally uses @EqualsAndHashCode.
For details refer: https://projectlombok.org/features/Value


<!-- Sent from Reviewable.io -->

2023-06-19 16:07 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 11 files at r1, 1 of 26 files at r2, 2 of 17 files at r3, 17 of 25 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48825)* status: 30 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-19 16:29 UTC, merged