feat:[CDS-70330]:  Manager encryption changes for terraform and terragrunt in CG
harness/harness-core pull request #48843
Opened 2023-06-06 05:29 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-08 13:21 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntApplyDestroyTaskHandler.java
> +  private boolean ifHarnessSecretManager(SecretManagerConfig secretManagerConfig) {
hey @sourabh-awashti  typo in if and not isHarness?

2023-06-08 13:25 UTC, vlica-harness commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_ARTIFACTS_PRIMARY_IDENTIFIER("To change the expression value for primary artifact identifier", HarnessTeam.CDC);
what's the purpose of this line change?

2023-06-08 14:08 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java
> +          terraformExecuteStepRequest.isEncryptDecryptPlanForHarnessSMOnManager(), terraformExecuteStepRequest.isNG());
hey @sourabh-awashti 
do TerraformExecuteStepRequest have these properties isEncryptDecryptPlanForHarnessSMOnManager and isNG defined?

2023-06-08 14:49 UTC, vlica-harness commented on 400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java
> +                CDS_TERRAFORM_TERRAGRUNT_PLAN_ENCRYPTION_ON_MANAGER_CG, executionContext.getApp().getAccountId()))
can we set this property also to check  & isHarnessSecretManager? 
In the next if conditions  we won't need to have always check like this 
taskNGParameters.isEncryptDecryptPlanForHarnessSMOnManager() && isHarnessSecretManager(encryptionConfig)

2023-06-08 15:01 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/mappers/EncryptedRecordDataToEncryptedSMDataMapper.java
> +        .additionalMetadata(encryptedRecordData.getAdditionalMetadata())
do we need to have encryptionType?

2023-06-09 04:06 UTC, sourabh-awashti commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_TERRAFORM_TERRAGRUNT_PLAN_ENCRYPTION_ON_MANAGER_NG(
there a two PRs for one for NG and other for CG, this NG flag is getting used in that PR. I will also share that PR

2023-06-09 04:09 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/mappers/EncryptedRecordDataToEncryptedSMDataMapper.java
> +        .additionalMetadata(encryptedRecordData.getAdditionalMetadata())
yes, encryption type is needed to identify the SM type, although in our case encryption type will always be GCP_KMS.

2023-06-09 04:52 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/mappers/EncryptedRecordDataToEncryptedSMDataMapper.java
> +        .additionalMetadata(encryptedRecordData.getAdditionalMetadata())
done

2023-06-09 04:52 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java
> +          terraformExecuteStepRequest.isEncryptDecryptPlanForHarnessSMOnManager(), terraformExecuteStepRequest.isNG());
it was in other PR, so added it here as well, Done

2023-06-09 04:54 UTC, sourabh-awashti commented on 400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java
> +                CDS_TERRAFORM_TERRAGRUNT_PLAN_ENCRYPTION_ON_MANAGER_CG, executionContext.getApp().getAccountId()))
done

2023-06-09 04:54 UTC, sourabh-awashti commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_ARTIFACTS_PRIMARY_IDENTIFIER("To change the expression value for primary artifact identifier", HarnessTeam.CDC);
removed

2023-06-09 04:54 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerragruntApplyDestroyTaskHandler.java
> +  private boolean ifHarnessSecretManager(SecretManagerConfig secretManagerConfig) {
done

2023-06-09 07:11 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/mappers/EncryptedRecordDataToEncryptedSMDataMapper.java
> +        .additionalMetadata(encryptedRecordData.getAdditionalMetadata())
hey @sourabh-awashti I was asking about encryptionType because It's missing here, I think we need to add it.

2023-06-09 07:17 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/mappers/EncryptedRecordDataToEncryptedSMDataMapper.java
> +        .additionalMetadata(encryptedRecordData.getAdditionalMetadata())
ohhk, added it now

2023-06-09 10:24 UTC, tchaurasiya requested changes

2023-06-09 10:24 UTC, tchaurasiya commented on 400-rest/src/main/java/software/wings/helpers/ext/terragrunt/TerragruntStateHelper.java
> +        : secretManagerConfigService.getSecretManager(accountId, secretManagerId, false);
why is it maskSecrets parameter is false?

2023-06-09 10:24 UTC, tchaurasiya commented on 400-rest/src/main/java/software/wings/service/impl/DelegateManagerEncryptionDecryptionHarnessSMServiceImpl.java
> +  @Inject private SecretNGManagerClient secretNGManagerClient;
ngmanager client should not be needed in cg code

2023-06-09 10:24 UTC, tchaurasiya commented on 400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java
> +      removeCredFromHarnessSM(secretManagerConfig);
nit:  method name

2023-06-09 10:26 UTC, tchaurasiya requested changes
io.harness.delegate.task.terragrunt.TerragruntTaskService#saveTerraformPlanContentToFile

Here also i think it should be handled

2023-06-09 10:28 UTC, sourabh-awashti commented on 400-rest/src/main/java/software/wings/service/impl/DelegateManagerEncryptionDecryptionHarnessSMServiceImpl.java
> +  @Inject private SecretNGManagerClient secretNGManagerClient;
Delegate tasks can not directly call ng manager hence we are routing calls through ng manager

2023-06-09 10:51 UTC, sourabh-awashti commented on 400-rest/src/main/java/software/wings/helpers/ext/terragrunt/TerragruntStateHelper.java
> +        : secretManagerConfigService.getSecretManager(accountId, secretManagerId, false);
it was false already, we need creds for encryption and decryption

2023-06-09 10:57 UTC, sourabh-awashti commented
> io.harness.delegate.task.terragrunt.TerragruntTaskService#saveTerraformPlanContentToFile
> 
> Here also i think it should be handled

2023-06-09 10:59 UTC, sourabh-awashti commented
> io.harness.delegate.task.terragrunt.TerragruntTaskService#saveTerraformPlanContentToFile
> 
> Here also i think it should be handled

It is being handled in separate PR for NG changes

2023-06-09 14:12 UTC, vlica-harness commented
Souragh would you add unit tests also, or it's part of other PR?

2023-06-12 10:14 UTC, sourabh-awashti commented
> Souragh would you add unit tests also, or it's part of other PR?

will add it in other PR

2023-06-12 10:15 UTC, vlica-harness approved these changes

2023-06-12 11:40 UTC, tchaurasiya approved these changes

2023-06-12 11:41 UTC, tchaurasiya submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48843)* status: Some of the checks are too old. 27 file(s) to review. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-12 12:27 UTC, vlica-harness approved these changes

2023-06-13 05:14 UTC, sourabh-awashti commented
trigger uts

2023-06-13 05:14 UTC, sourabh-awashti commented
trigger review

2023-06-13 05:56 UTC, yogesh-chauhan commented on 400-rest/src/main/java/software/wings/service/impl/DelegateManagerEncryptionDecryptionHarnessSMServiceImpl.java
> +  public DecryptedRecord decryptDataNG(String accountId, EncryptedRecordData encryptedRecord) {
should we not create a new class for NG instead of re-using the same class for CG/NG ?

2023-06-13 05:56 UTC, yogesh-chauhan commented on 400-rest/src/main/java/software/wings/sm/states/provision/TerragruntProvisionState.java
> +                    CDS_TERRAFORM_TERRAGRUNT_PLAN_ENCRYPTION_ON_MANAGER_CG, executionContext.getApp().getAccountId())
context.getAccount() we can use

2023-06-13 05:56 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/HarnessSMEncryptionDecryptionHandler.java
> +  public EncryptedRecord encryptContent(byte[] content, EncryptionConfig config, boolean isNG) {
can we create newer methods for NG ?

2023-06-13 05:56 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/HarnessSMEncryptionDecryptionHandler.java
> +      log.error("Not able to encrypt harness SM secrets", e);
this should throw

2023-06-13 05:56 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/HarnessSMEncryptionDecryptionHandler.java
> +      return DecryptedRecord.builder().decryptedValue(new char[0]).build();
throw exception

2023-06-13 05:56 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java
> +    if (encryptDecryptPlanForHarnessSMOnManager) {
can we log time taken to decrypt ?

2023-06-13 05:56 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java
> +    if (encryptDecryptPlanForHarnessSMOnManager) {
in if-else branch both

2023-06-13 05:57 UTC, merged

2023-06-13 05:57 UTC, sourabh-awashti commented
Already discussed offline, will resolve comments in next PR