fix: [CDS-70641]: delegate changes for hash function
harness/harness-core pull request #48880
Opened 2023-06-06 16:15 UTC by TarunUba1

## Describe your changes
delegate changes for hash function, not used currently as integration will be done later
## Testing
1. tested with different version after changing hash, able to generate same hash after adding comments and changing sequence of key, values
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-06 17:07 UTC, abosii-harness requested changes

2023-06-06 17:07 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +  public String calculateHash(List<KubernetesResource> resources, K8sDelegateTaskParams k8sDelegateTaskParams,
Can we move this logic or part (the execution part) of it at to the kubectl client?

2023-06-06 17:07 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    if (lol < 0) {
lol?

2023-06-06 17:07 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +      String generatedYaml = processResult.outputUTF8();
Let's move this a new method

2023-06-06 17:07 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    FileIo.writeUtf8StringToFile(
Shoud we remove the file after it was created?

2023-06-06 17:07 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    // calculateHash(resources,k8sDelegateTaskParams,executionLogCallback,request.getTimeoutIntervalInMin());
We should remove this

2023-06-06 17:08 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        throw NestedExceptionUtils.hintWithExplanationException(KubernetesExceptionHints.MANIFEST_HASH_ERROR,
Ca we just throw KubernetesCliTaskRuntimeException instead and let the exception handler framework to handle it? Maybe you can add a branch in KubernetesCliRuntimeExceptionHandler

2023-06-06 17:09 UTC, abosii-harness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java
> +  public void testHashCommand() throws Exception {
Can we add some UTs that will test the full command? Like what is the result of some manifest and the hash value

2023-06-07 04:23 UTC, TarunUba1 commented
trigger uts

2023-06-07 05:53 UTC, abhinavsingh1196 requested changes

2023-06-07 05:53 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +  public String calculateHash(List<KubernetesResource> resources, K8sDelegateTaskParams k8sDelegateTaskParams,
I'm in favour of keeping as much as possible out of request handlers. So possibly all of these new methods.
Maybe we can have some static class itself like K8sManifestHashGenerator

2023-06-07 05:53 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +  public String getHashCommand(String manifestName) {
this should be named getKubectlCreateCommand ? since we are hashing later

2023-06-07 05:53 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    } else {
redundant else

2023-06-07 12:09 UTC, TarunUba1 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java
> +  public void testHashCommand() throws Exception {
added UT to check generated hash

2023-06-07 12:09 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +  public String calculateHash(List<KubernetesResource> resources, K8sDelegateTaskParams k8sDelegateTaskParams,
Moved to a new Util class

2023-06-07 12:59 UTC, abhinavsingh1196 requested changes

2023-06-07 12:59 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +public class K8sManifestHashGenerator {
if we make it @UtilityClass, then @NoArgsConstructor may not be needed

2023-06-07 12:59 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +  public static final String MANIFEST_FOR_HASH = "manifest-hash.yaml";
can be private

2023-06-07 14:18 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +public class K8sManifestHashGenerator {
Done

2023-06-07 14:35 UTC, TarunUba1 commented
trigger uts

2023-06-07 15:17 UTC, abosii-harness requested changes

2023-06-07 15:17 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +      FileIo.deleteFileIfExists(k8sDelegateTaskParams.getWorkingDirectory() + "/" + MANIFEST_FOR_HASH);
Should be in final block

2023-06-07 15:17 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +    int versionCheck = client.getVersion().compareTo(Version.parse("1.18"));
I'm still voting to move create command as part of the kubectl client, the version check as well. You can follow @alebuh approach. Which actually is already handled, you just need to call dryRyn method from kubectl client

2023-06-07 15:17 UTC, abosii-harness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sManifestHashGeneratorTest.java
> +    assertThat(k8sManifestHashGenerator.generatedHash(DEPLOYMENT_DIRECT_APPLY_YAML))
Does this test invoke the actual kubectl create? We should avoid this and instead mock the executeShellCommand. This can result in flaky test as becomes dependent on the kubeconfig availability in the running env

2023-06-07 15:46 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +    int versionCheck = client.getVersion().compareTo(Version.parse("1.18"));
are you referring to this https://github.com/harness/harness-core/pull/48815 ?

2023-06-07 15:50 UTC, TarunUba1 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sManifestHashGeneratorTest.java
> +    assertThat(k8sManifestHashGenerator.generatedHash(DEPLOYMENT_DIRECT_APPLY_YAML))
okay, this test was just checking if the hash created for a sample YAML is same as that created in terminal, will create proper UT

2023-06-08 11:03 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +    int versionCheck = client.getVersion().compareTo(Version.parse("1.18"));
Done

2023-06-08 11:03 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
> +      FileIo.deleteFileIfExists(k8sDelegateTaskParams.getWorkingDirectory() + "/" + MANIFEST_FOR_HASH);
Done

2023-06-08 11:05 UTC, TarunUba1 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sManifestHashGeneratorTest.java
> +    assertThat(k8sManifestHashGenerator.generatedHash(DEPLOYMENT_DIRECT_APPLY_YAML))
was unable to add a test for mocking executeShellCommand, as we created a utility class and are using k8sTaskHelperBase in function param.

2023-06-08 11:05 UTC, TarunUba1 commented
trigger uts

2023-06-08 11:06 UTC, TarunUba1 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sManifestHashGeneratorTest.java
> +    assertThat(k8sManifestHashGenerator.generatedHash(DEPLOYMENT_DIRECT_APPLY_YAML))
this test only checks that from a YAML the generated hash is same as what we get in terminal

2023-06-08 11:28 UTC, TarunUba1 commented
trigger uts

2023-06-09 07:37 UTC, abosii-harness approved these changes

2023-06-09 07:40 UTC, abhinavsingh1196 approved these changes

2023-06-09 07:40 UTC, TarunUba1 commented
trigger review

2023-06-09 07:48 UTC, merged