fix: [CDS-70876]: Scale only pirmary workload in  of Scale step after Canary Deploy
harness/harness-core pull request #48923
Opened 2023-06-07 10:02 UTC by GoelPratyush99

## Describe your changes
For the scenario when user used `${k8s.canaryWorkload}` variable in the scale step to scale down their primary workloads. We were unable to process the workloads and failed with the following exception (Only for declarative rollback)

`Invalid Kubernetes resource name smart-offering/Deployment/sos-canary,smart-offering/ConfigMap/sos-dependencies-yaml-canary,smart-offering/ConfigMap/sos-filebeat-canary,smart-offering/ConfigMap/sos-h-590ceb-deps-canary,smart-offering/ConfigMap/sos-nginx-canary,smart-offering/ConfigMap/sos-sysctl-dependencies-yaml-canary,smart-offering/ConfigMap/sos-sysctl-h-590ceb-deps-canary. Should be in format Kind/Name`

We have raised a fix to properly process the manifest and scale only the primary canary workload.

NG:
<img width="486" alt="Screenshot 2023-06-07 at 3 19 49 PM" src="https://github.com/harness/harness-core/assets/97931011/bad7a587-665a-4c48-93e0-50ec6aefe593">
<img width="1279" alt="Screenshot 2023-06-07 at 6 46 48 PM" src="https://github.com/harness/harness-core/assets/97931011/083c2d5f-e1ff-4282-b1cd-9f84d216422c">
<img width="1296" alt="Screenshot 2023-06-07 at 6 46 58 PM" src="https://github.com/harness/harness-core/assets/97931011/a686a5ee-69ad-4e4a-b739-e2690ca1d8d3">

CG
<img width="1454" alt="Screenshot 2023-06-07 at 4 16 46 PM" src="https://github.com/harness/harness-core/assets/97931011/4f7e2405-9736-4ee5-9242-3003d73126f6">
<img width="1449" alt="Screenshot 2023-06-07 at 4 16 51 PM" src="https://github.com/harness/harness-core/assets/97931011/e51455a7-d8f9-45c5-abab-c118fcbf23f9">

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/48923)

2023-06-07 10:48 UTC, GoelPratyush99 commented
trigger uts

2023-06-07 11:31 UTC, GoelPratyush99 commented
trigger messagecheck

2023-06-07 15:00 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +                  k8sResourceId -> CANARY_BG_SCALE_WORKLOAD_KINDS.contains(Kind.fromString(k8sResourceId.getKind())))
What if some customers want to use replica controller or some resources that we're not handling? This task can be used not only in canary flows. To be safe here, we should invoke any addition logic only if there are more than one resource provided

2023-06-07 15:03 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +  public static KubernetesResourceId createKubernetesResourceIdFromNamespaceKindNameWrapper(String kindName) {
we should rename this to something more descriptive to what this method actually do, i.e. findScalableKubernetesResourceIds

2023-06-07 15:04 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +      if (kubernetesResourceIds.size() != 1) {
I believe we should actually return a list of resource ids and then to the handling in scale handle itself

2023-06-07 15:04 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +              "Invalid Kubernetes resource name " + kindName + ". No workloads found in the Manifests");
in manifests? There is no manifest in scale task

2023-06-07 15:05 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +            + ". More than one workloads found in the Manifests. Others should be marked with annotation"
Same here, there is no manifest in scale task. Usually scale step asks for input

2023-06-07 15:07 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +                  k8sResourceId -> CANARY_BG_SCALE_WORKLOAD_KINDS.contains(Kind.fromString(k8sResourceId.getKind())))
Why CANARY_>>>BG<<<_SCALE_WORKLOAD_KINDS, what BG has to do with it? Why it does matter if it's canary or not? Ideally this logic should filter all scalable resources since at some point of time we may want to add support for a new managed workload and someone could forget about this logic

2023-06-07 17:35 UTC, GoelPratyush99 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +                  k8sResourceId -> CANARY_BG_SCALE_WORKLOAD_KINDS.contains(Kind.fromString(k8sResourceId.getKind())))
- This flow currently is only required for canary workload edge case that we are missing. For other step that we support currently none supports this feature.

- Right now to make changes according to multiple workloads we need to refactor the code specially how we calculate the required instances in case InstanceUnitType is PERCENTAGE. Besides it does not make sense to support multiple workloads in SCALE step because the user might want to scale different resources to different instances according to their use case. To keep things backwards compatible it would be better to design a new step.

2023-06-07 17:44 UTC, GoelPratyush99 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +  public static KubernetesResourceId createKubernetesResourceIdFromNamespaceKindNameWrapper(String kindName) {
Done

2023-06-07 17:44 UTC, GoelPratyush99 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +              "Invalid Kubernetes resource name " + kindName + ". No workloads found in the Manifests");
Removed it

2023-06-07 18:09 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +                  k8sResourceId -> CANARY_BG_SCALE_WORKLOAD_KINDS.contains(Kind.fromString(k8sResourceId.getKind())))
Am I missing something here? How this flow is specific only for canary edge case? From what I can see, you're replacing createKubernetesResourceIdFromNamespaceKindName with this method that is directly used by both CG and NG scale handler. These tasks are used by Scale steps, with scale step you can scale any resource that is scalable. The canary use case is working just because of expression resolver and it doesn't have anything to do with the design of Scale step. 

This method is restricting user to scale only Deployment, StatefulSet, DeploymentConfig. What will happen if user now setup a scale step and use default/ReplicationController/nginx as workload? From what I can see this will fail with: `Invalid Kubernetes resource name default/ReplicationController/nginx No workloads found in the Manifests`, but without this changes it will work fine, so it's a regression. 

My overall point is to not tight this logic to canary and you shouldn't look at the problem from the point of canary deployment. The problem statement is that we're ending up in passing to the scale step multiple resources and we need to identify only scalable single resource from that list. Most probably we could end up in missing some resource that user can scale but our filter will now filter it. Since previously we always supported only a single resource, to workaround our issue and not break anything we should apply this filter only if user provided multiple resources as step input and we know that from that list there should be at least one scalable resource.

2023-06-08 04:53 UTC, GoelPratyush99 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +                  k8sResourceId -> CANARY_BG_SCALE_WORKLOAD_KINDS.contains(Kind.fromString(k8sResourceId.getKind())))
In the updated code we are handling scaling of all the workloads that we support [https://github.com/harness/harness-core/pull/48923/files#diff-4c2de7f3a480e106f03c71f3235fcfe94c01f84842a4eea1fe554aba3dcf2ab0R37-R38](https://github.com/harness/harness-core/pull/48923/files#diff-4c2de7f3a480e106f03c71f3235fcfe94c01f84842a4eea1fe554aba3dcf2ab0R37-R38). In case multiple resources are passed then we fall to canary edge case [https://github.com/harness/harness-core/pull/48923/files#diff-4c2de7f3a480e106f03c71f3235fcfe94c01f84842a4eea1fe554aba3dcf2ab0R40](https://github.com/harness/harness-core/pull/48923/files#diff-4c2de7f3a480e106f03c71f3235fcfe94c01f84842a4eea1fe554aba3dcf2ab0R40).

2023-06-08 05:18 UTC, GoelPratyush99 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +                  k8sResourceId -> CANARY_BG_SCALE_WORKLOAD_KINDS.contains(Kind.fromString(k8sResourceId.getKind())))
I did fix it in my previous commit

2023-06-08 05:19 UTC, GoelPratyush99 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResourceId.java
> +      if (kubernetesResourceIds.size() != 1) {
Done. Moved it task handler.

2023-06-08 05:20 UTC, GoelPratyush99 commented
trigger uts

2023-06-08 07:11 UTC, GoelPratyush99 commented
trigger uts

2023-06-08 08:08 UTC, abhinavsingh1196 requested changes

2023-06-08 08:08 UTC, abhinavsingh1196 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/Kind.java
> +  public static final Set<Kind> BG_STAGE_WORKLOAD_KINDS = ImmutableSet.of(
nit: BG_STAGE_WORKLOAD_KINDS can be rewritten as
`Set<Kind> BG_STAGE_WORKLOAD_KINDS = SetUtils.union(BG_STAGE_SCALE_DOWN_WORKLOAD_KINDS, BG_STAGE_DELETE_WORKLOAD_KINDS);`

2023-06-08 08:08 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sScaleTaskHandler.java
> +  KubernetesResourceId findScalableKubernetesResourceIdFromWorkload(String kindName) {
Also, this method is duplicate in both CG and NG request handlers?

2023-06-08 08:27 UTC, GoelPratyush99 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/Kind.java
> +  public static final Set<Kind> BG_STAGE_WORKLOAD_KINDS = ImmutableSet.of(
DOne

2023-06-08 08:28 UTC, GoelPratyush99 commented
trigger uts

2023-06-08 09:56 UTC, USB-05 commented
trigger sst

2023-06-08 10:52 UTC, abosii-harness submitted a review, later dismissed

2023-06-09 05:28 UTC, GoelPratyush99 commented
trigger uts

2023-06-09 05:47 UTC, abosii-harness approved these changes

2023-06-09 07:56 UTC, merged