feat:[CDS-70330]: encryption TF plan changes for NG
harness/harness-core pull request #48986
Opened 2023-06-08 13:07 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-15 12:08 UTC, vlica-harness requested changes

2023-06-15 13:23 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java
> +      secretManagerConfig.maskSecrets();
@sourabh-awashti 
how do we handle secretManagerConfig with maskedSecrets if there is an older delegate?

2023-06-19 05:33 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java
> +      secretManagerConfig.maskSecrets();
We have to ask all customers who are using terraform or terragrunt to upgrade to new delegate

2023-06-19 05:34 UTC, sourabh-awashti commented
> Can we have please added unit tests for manager and delegate?

I have added it in separate PR, will share it

2023-06-19 06:24 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java
> +    if (secretManagerConfig != null) {
done

2023-06-19 06:24 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java
> +            .encryptDecryptPlanForHarnessSMOnManager(
done

2023-06-19 12:50 UTC, sourabh-awashti commented on 400-rest/src/main/java/software/wings/resources/DelegateManagerEncryptionDecryptionHarnessSMResourceNG.java
> +  @Inject DelegateManagerEncryptionDecryptionHarnessSMServiceNGImpl encryptionDecryptionService;
done

2023-06-19 12:51 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java
> +                helper.tfPlanEncryptionOnManager(accountId, inheritOutput.encryptionConfig))
done

2023-06-19 12:54 UTC, yogesh-chauhan approved these changes
> Reviewed 7 of 36 files at r1, 24 of 33 files at r2, 7 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48986)* status: 40 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-19 12:54 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48986)* status: 40 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-19 13:02 UTC, sourabh-awashti commented
trigger uts

2023-06-19 18:20 UTC, sourabh-awashti commented
trigger review

2023-06-19 18:22 UTC, merged