fix: [CDS-54472]: Delegate side changes for Helm Instance sync v2 support NG
harness/harness-core pull request #49025
Opened 2023-06-09 07:48 UTC by namantalaycha10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-09 08:57 UTC, abosii-harness requested changes

2023-06-12 05:59 UTC, namantalaycha10 commented
trigger uts

2023-06-12 06:29 UTC, namantalaycha10 commented
trigger uts

2023-06-12 07:35 UTC, namantalaycha10 commented
trigger uts

2023-06-12 08:42 UTC, abosii-harness submitted a review, later dismissed

2023-06-13 07:15 UTC, namantalaycha10 commented
trigger uts

2023-06-13 07:27 UTC, namantalaycha10 commented
trigger messagecheck

2023-06-13 07:41 UTC, abosii-harness requested changes

2023-06-13 09:14 UTC, abosii-harness approved these changes

2023-06-13 10:13 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/native_helm_instance_sync_task_params_v2.proto
> +// Copyright 2021 Harness Inc. All rights reserved.
Can we make this 2023

2023-06-13 10:18 UTC, namantalaycha10 commented
trigger uts

2023-06-13 10:18 UTC, GoelPratyush99 approved these changes

2023-06-13 10:20 UTC, TarunUba1 commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/native_helm_instance_sync_task_params_v2.proto
> +// Copyright 2021 Harness Inc. All rights reserved.
i think @namantalaycha10 you added it manually, it will be automatically added to file when you commit correctly

2023-06-13 10:20 UTC, TarunUba1 commented
can you add how you tested following cases as well

2023-06-13 10:21 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/native_helm_instance_sync_task_params_v2.proto
> +// Copyright 2021 Harness Inc. All rights reserved.
For that we need to run the git script. Probably @namantalaycha10 you have not enable the git hook

2023-06-13 10:23 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/native_helm_instance_sync_task_params_v2.proto
> +// Copyright 2021 Harness Inc. All rights reserved.
what is that hook name ?

2023-06-13 10:27 UTC, namantalaycha10 commented
> can you add how you tested following cases as well

Done

2023-06-13 10:39 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/proto/io/harness/perpetualtask/instancesync/native_helm_instance_sync_task_params_v2.proto
> +// Copyright 2021 Harness Inc. All rights reserved.
tools>git-hooks>install.sh that should do the trick

2023-06-13 11:20 UTC, abosii-harness approved these changes

2023-06-13 11:28 UTC, namantalaycha10 commented
trigger review

2023-06-13 11:31 UTC, merged