Pl 39076
harness/harness-core pull request #49081
Opened 2023-06-12 06:04 UTC by boopesh007

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-12 06:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=49081) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=49081) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: boopesh007<br/>:x: rijajoo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=49081) it.</sub>

2023-06-12 06:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=49081) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=49081) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: boopesh007<br/>:x: rijajoo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=49081) it.</sub>

2023-06-15 15:23 UTC, boopesh007 commented
trigger uts

2023-06-19 05:39 UTC, rijajoo requested changes
Please address all TODOs.

2023-06-19 08:52 UTC, boopesh007 commented
trigger uts

2023-06-19 10:05 UTC, rijajoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java
> +    populateFavoriteInformation(accountIdentifier, orgIdentifier, projectIdentifier, userHelperService.getUserId(),
We can do this similar to how we did in project favorites: check ProjectService isFavorite

2023-06-19 10:51 UTC, boopesh007 commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java
> +    populateFavoriteInformation(accountIdentifier, orgIdentifier, projectIdentifier, userHelperService.getUserId(),
Performance will deteriorate if for each entry (connector) we make a favorite service call (costly, since fetches from DB). For aggregate calls, we should get all the favorites and store them in memory and update the aggregate response with fav info accordingly. We should be doing it for projects as well. 
cc: @nishantsaini20 @gn-harness

2023-06-19 10:54 UTC, boopesh007 commented
trigger ut2

2023-06-19 11:48 UTC, rijajoo commented on 440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java
> +    populateFavoriteInformation(accountIdentifier, orgIdentifier, projectIdentifier, userHelperService.getUserId(),
Ok, I agree that this is the correct way. We can discuss with @gn-harness if we can do it the same way in projects too. Ref: https://github.com/harness/harness-core/pull/49126#discussion_r1227092492

2023-06-19 13:42 UTC, boopesh007 commented
trigger uts

2023-06-19 18:50 UTC, boopesh007 commented
trigger uts

2023-06-20 05:31 UTC, boopesh007 commented
trigger uts

2023-06-20 07:39 UTC, boopesh007 commented
trigger uts

2023-06-20 08:01 UTC, boopesh007 commented
trigger uts

2023-06-20 08:05 UTC, rijajoo approved these changes

2023-06-20 08:28 UTC, rijajoo commented
trigger checkstylecodeformat, messagecheck, codebasehash

2023-06-20 10:01 UTC, boopesh007 commented
trigger uts

2023-06-20 10:50 UTC, boopesh007 commented
trigger uts

2023-06-20 12:44 UTC, rijajoo approved these changes

2023-06-20 12:48 UTC, merged