[feat]: [CDS-71274]: Cascade Deletion support for Overrides 2.0
harness/harness-core pull request #49144
Opened 2023-06-13 05:51 UTC by lovish1999

## Describe your changes
Cascade Deletion support for Overrides 2.0

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-14 12:51 UTC, lovish1999 commented
trigger messagecheck

2023-06-15 08:34 UTC, tchaurasiya commented
trigger uts

2023-06-15 11:55 UTC, lovish1999 commented
trigger uts

2023-06-15 12:07 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +  public boolean deleteAllInInfra(
nit: lets make if ForEnv

2023-06-15 12:19 UTC, tchaurasiya approved these changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49144)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-15 13:52 UTC, yogesh-chauhan requested changes

2023-06-15 13:52 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
> +                              accountId, orgIdentifier, projectIdentifier, environmentIdentifier))
can we not delete both old/new overrides always ?

2023-06-15 13:52 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java
> +      Failsafe.with(transactionRetryPolicy).get(() -> transactionTemplate.execute(status -> {
should we not get the output of this and return at line:394 ?

2023-06-15 13:52 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java
> +                       -> serviceOverridesServiceV2.deleteAllInInfra(
this should be called "deleteAllForInfra", since overrides not "in" an infra rather they are associated with infrastructures

2023-06-21 07:38 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
> +                              accountId, orgIdentifier, projectIdentifier, environmentIdentifier))
We are deleting both of them with the deleteAllInEnv method of serviceOverridesServiceV2. Only for time being, calling this method is under the FF.

2023-06-21 14:12 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +  public boolean deleteAllInInfra(
ok

2023-06-21 14:12 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java
> +                       -> serviceOverridesServiceV2.deleteAllInInfra(
ok

2023-06-22 05:53 UTC, lovish1999 commented
trigger uts

2023-06-22 06:30 UTC, lovish1999 commented
trigger uts

2023-06-22 06:43 UTC, lovish1999 commented
trigger uts

2023-06-22 15:17 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 388 at r2](https://reviewable.io/reviews/harness/harness-core/49144#-NYYfeIU6qN5cWJbiq7M:-NYYfeIU6qN5cWJbiq7N:b-y1glgs) ([raw file](https://github.com/harness/harness-core/blob/4739906e23ce5688fe4ea18090e795aaa003dd91/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L388)):*
> ```Java
>         ServiceOverridesSpec spec = overrideV2Configs.get(overridesType).getSpec();
>         if (spec.getApplicationSettings() != null) {
>           configuration = spec.getApplicationSettings();
> ```

why this change ?


<!-- Sent from Reviewable.io -->

2023-06-23 06:12 UTC, lovish1999 commented
> _[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 388 at r2](https://reviewable.io/reviews/harness/harness-core/49144#-NYYfeIU6qN5cWJbiq7M:-NYYfeIU6qN5cWJbiq7N:b-y1glgs) ([raw file](https://github.com/harness/harness-core/blob/4739906e23ce5688fe4ea18090e795aaa003dd91/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L388)):_
> 
> > ```java
> >         ServiceOverridesSpec spec = overrideV2Configs.get(overridesType).getSpec();
> >         if (spec.getApplicationSettings() != null) {
> >           configuration = spec.getApplicationSettings();
> > ```
> 
> why this change ?

Sorry, this is not related to current change. It was a minor change of another PR which we decided to add in this PR in order to avoid running all the UTs of that PR again. @tchaurasiya can review this change.

2023-06-23 06:12 UTC, tchaurasiya submitted a review, later dismissed
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49144)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-25 14:54 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/event/ProjectEntityCRUDStreamListener.java
> +  private boolean isOverridesV2Enabled(String accountId, String orgId, String projectId) {
don't we have a similar method used at other places as well ? I remember @Tathagat also used a similar method

2023-06-25 14:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +    return delete.wasAcknowledged();
should we also check for delete.getDeletedCount() ?

2023-06-25 14:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +      String scopedServiceRef = serviceIdentifier.trim();
why do we need to trim it here ?

2023-06-25 14:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +    return delete.wasAcknowledged() && delete.getDeletedCount() > 0;
here we are using deletedCount but not in the other delete methods. Lets be consistent

2023-06-25 14:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +
Just to make sure, IF I delete an account level service, this will delete all its overrides across all orgs and projects, right ?

2023-06-25 14:54 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java
> +  private boolean isOverridesV2Enabled(String accountId, String orgId, String projectId) {
one similar method was used in ProjectEntityCRUDStreamListener ?

2023-06-26 06:22 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +    return delete.wasAcknowledged();
I do not think so. As there may be no service overrides associated with the environment. In that case, deleted count will be 0, so the method may fail ?

2023-06-26 06:25 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +      String scopedServiceRef = serviceIdentifier.trim();
This part is similar to the one working for overrides v1. There may have been issues of spaces with the identifier due to which @hingerabhinav added this. So we have just taken it from there.

2023-06-27 05:50 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +    return delete.wasAcknowledged() && delete.getDeletedCount() > 0;
okay

2023-06-27 05:51 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +
yes, because it fetches all overrides associated with that scoped service ref

2023-06-27 05:52 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java
> +  private boolean isOverridesV2Enabled(String accountId, String orgId, String projectId) {
okay, will remove duplicate methods

2023-06-27 05:52 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/event/ProjectEntityCRUDStreamListener.java
> +  private boolean isOverridesV2Enabled(String accountId, String orgId, String projectId) {
yes, removing the duplicate methods

2023-06-27 06:38 UTC, yogesh-chauhan reviewed
> Reviewed 9 of 17 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49144)* status: Some of the checks are too old. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-27 06:39 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49144)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-06-27 13:22 UTC, lovish1999 commented
trigger uts

2023-06-27 18:07 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49144)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-29 06:03 UTC, tchaurasiya commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/utils/serviceOverrideV2ValidationHelper.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/49144#-NZ4jrRbEeLJ7mDz3jBP:-NZ4jrRbEeLJ7mDz3jBQ:bnkvluc) ([raw file](https://github.com/harness/harness-core/blob/cb7ea371b064db0bfa97a5d429582a20e825d9f1/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/utils/serviceOverrideV2ValidationHelper.java#L27)):*
> ```Java
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> @OwnedBy(HarnessTeam.CDC)
> public class serviceOverrideV2ValidationHelper {
> ```

class name staring with small case?


<!-- Sent from Reviewable.io -->

2023-06-29 10:01 UTC, lovish1999 commented
trigger ut4

2023-06-29 10:18 UTC, tchaurasiya approved these changes
> Reviewed 17 of 17 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49144)* status: 17 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-29 10:38 UTC, yogesh-chauhan approved these changes

2023-06-29 10:38 UTC, yogesh-chauhan commented
trigger review

2023-06-29 11:01 UTC, merged