fix: [PL-39412]: Add try/catch block to get cache from redis
harness/harness-core pull request #49142
Opened 2023-06-13 05:38 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-13 06:02 UTC, xingchi-jin reviewed
Thanks for the quick fix

2023-06-13 15:27 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +    Delegate delegateFromCache = null;
updated

2023-06-13 15:45 UTC, raghuAtWings requested changes

2023-06-13 15:45 UTC, raghuAtWings commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +    if (!forceRefresh) {
this is pretty complicated, can we not always read from db if there is an exception. I would recommend to rewrite this the following way

if(forceRefresh) {
   //read from db,  update the cache and return 
}

try {
    //read from cache and return
} catch (Exception) {
   //read from db,  update the cache and return 
}

2023-06-13 16:15 UTC, jennyjames21 commented
trigger uts

2023-06-14 03:41 UTC, raghuAtWings requested changes

2023-06-14 03:41 UTC, raghuAtWings commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +      log.error("Exception occurred while loading Delegate from redis cache, loading from DB", ex);
should not be error, info should be good enough.

2023-06-14 03:41 UTC, raghuAtWings commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +      log.error("Exception occurred while loading Delegate Group from redis cache", ex);
same here.

2023-06-14 03:41 UTC, raghuAtWings commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +      log.error("Exception occurred while loading Delegate list from redis cache", ex);
same here

2023-06-14 03:56 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +      log.error("Exception occurred while loading Delegate list from redis cache", ex);
updated

2023-06-14 03:56 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +      log.error("Exception occurred while loading Delegate Group from redis cache", ex);
updated

2023-06-14 03:56 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +      log.error("Exception occurred while loading Delegate from redis cache, loading from DB", ex);
updated

2023-06-14 03:56 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +    if (!forceRefresh) {
updated

2023-06-14 03:58 UTC, raghuAtWings approved these changes

2023-06-14 06:13 UTC, jennyjames21 commented
trigger uts

2023-06-14 06:29 UTC, jennyjames21 commented
trigger messagecheck

2023-06-14 06:31 UTC, merged