[feat]: [CDS-71330]: audit trial support v2 for overrides
harness/harness-core pull request #49170
Opened 2023-06-13 10:41 UTC by tchaurasiya

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-14 06:11 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideRequestDTOV2.java
> +  String identifier;
But this will result in changes in the terraform provider code ?

2023-06-14 09:11 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideRequestDTOV2.java
> +  String identifier;
Yes we will need to update terraform and api tests post this,

2023-06-14 09:27 UTC, yogesh-chauhan requested changes
> Reviewed 1 of 7 files at r1, 1 of 6 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49170)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/49170#-NXtCpreEYDIH9MN-GKG:-NXtCpreEYDIH9MN-GKH:b1dizuq) ([raw file](https://github.com/harness/harness-core/blob/a3e14c110a1896c28d6e3a665e925769d2c403a8/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L126)):*
> ```Java
>         return saveAndSendOutBoxEvent(requestedEntity);
>       } catch (IOException e) {
>         throw new InvalidRequestException(
> ```

do we need to fail creation if we are unable to save outbox ? I think we can log an error 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentUpdatedEvent.java` line 157 at r3](https://reviewable.io/reviews/harness/harness-core/49170#-NXtDMAxC_WOQPPi10RR:-NXtDMAy0ChXPlWmTREw:bam0iuf) ([raw file](https://github.com/harness/harness-core/blob/a3e14c110a1896c28d6e3a665e925769d2c403a8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentUpdatedEvent.java#L157)):*
> ```Java
>       NGServiceOverridesEntity ngServiceOverridesEntity =
>           newServiceOverridesEntity == null ? oldServiceOverridesEntity : newServiceOverridesEntity;
>       resourceIdentifier = ngServiceOverridesEntity.getIdentifier();
> ```

have we changed the name(..) logic for older overrides ?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideAuditEventDTO.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/49170#-NXtDVflE-CDPHnEjPdQ:-NXtDVflE-CDPHnEjPdR:btvq36z) ([raw file](https://github.com/harness/harness-core/blob/a3e14c110a1896c28d6e3a665e925769d2c403a8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideAuditEventDTO.java#L27)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(
> ```

do we need schema annotation for this ? I don't think this entity is exposed in open api


<!-- Sent from Reviewable.io -->

2023-06-15 08:16 UTC, tchaurasiya commented
trigger uts

2023-06-15 08:42 UTC, tchaurasiya commented
trigger uts

2023-06-15 11:09 UTC, tchaurasiya commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideAuditEventDTO.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/49170#-NXtDVflE-CDPHnEjPdQ:-NXyjjnG9JEuCO6ibdRL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a3e14c110a1896c28d6e3a665e925769d2c403a8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideAuditEventDTO.java#L27)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need schema annotation for this ? I don't think this entity is exposed in open api
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-15 11:09 UTC, tchaurasiya commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentUpdatedEvent.java` line 157 at r3](https://reviewable.io/reviews/harness/harness-core/49170#-NXtDMAxC_WOQPPi10RR:-NXyjmuY9ksycs3MQVRs:b-bgy2lu) ([raw file](https://github.com/harness/harness-core/blob/a3e14c110a1896c28d6e3a665e925769d2c403a8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentUpdatedEvent.java#L157)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

have we changed the name(..) logic for older overrides ?
</blockquote></details>

Done. Made it backward compatible


<!-- Sent from Reviewable.io -->

2023-06-15 11:10 UTC, tchaurasiya commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/49170#-NXtCpreEYDIH9MN-GKG:-NXyj_nV9j0oOZuBV-sY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a3e14c110a1896c28d6e3a665e925769d2c403a8/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L126)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to fail creation if we are unable to save outbox ? I think we can log an error 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-15 11:10 UTC, tchaurasiya commented
trigger uts

2023-06-15 12:18 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 7 files at r1, 1 of 6 files at r2, 1 of 4 files at r3, 7 of 10 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49170)* status: 16 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 107 at r6](https://reviewable.io/reviews/harness/harness-core/49170#-NXyyETM4lkqIHv3AE79:-NXyyETM4lkqIHv3AE7A:b-960q6e) ([raw file](https://github.com/harness/harness-core/blob/27ab8bfe2df9d6d961754f0bb7aa957e24c057e2/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L107)):*
> ```Java
>           "Service Override inputs [%s] or Environment inputs [%s] are not resolved",
>           parameters.getServiceOverrideInputs().getExpressionValue(), parameters.getEnvInputs().getExpressionValue()));
>     }
> ```

nit: can we handle this as expression ( not runtime input )


<!-- Sent from Reviewable.io -->

2023-06-15 12:18 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49170)* status: 16 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-16 06:35 UTC, brijeshdhakar approved these changes
> Reviewed 2 of 7 files at r1, 1 of 6 files at r2, 1 of 4 files at r3, 7 of 10 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49170)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-16 06:48 UTC, tchaurasiya commented
trigger review

2023-06-16 06:50 UTC, merged