fix: [CDS-69215]: create migration to delete usergroup parents no longer exists
harness/harness-core pull request #49206
Opened 2023-06-13 21:06 UTC by rafaelmart1ns

## Describe your changes
This migration removes all relatives that no longer exist from the usergroup to prevent errors when trying to delete a usergroup.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-14 15:11 UTC, Fernando-Dourado commented
trigger uts

2023-06-14 16:19 UTC, Fernando-Dourado requested changes

2023-06-14 16:19 UTC, Fernando-Dourado commented on 390-db-migration/src/main/java/io/harness/migrations/all/DeleteUsergroupsParentsNotExists.java
> +          log.error(DEBUG_MESSAGE + "Migration failed for usergroup with id {} in accountId: 2zPKqzWjT3SUyklYJvslKg",
This usage of slf4j API is wrong. We cannot use it as argument objects and exceptions at the same time.

2023-06-14 16:19 UTC, Fernando-Dourado commented on 390-db-migration/src/main/java/io/harness/migrations/all/DeleteUsergroupsParentsNotExists.java
> +      if (!userGroupHIterator.hasNext()) {
This block is really required? If the `userGroupHIterator` doesn't have next it will not execute while code-block.

2023-06-14 17:37 UTC, rafaelmart1ns commented on 390-db-migration/src/main/java/io/harness/migrations/all/DeleteUsergroupsParentsNotExists.java
> +      if (!userGroupHIterator.hasNext()) {
its a over. it was removed.

2023-06-14 17:44 UTC, rafaelmart1ns commented on 390-db-migration/src/main/java/io/harness/migrations/all/DeleteUsergroupsParentsNotExists.java
> +          log.error(DEBUG_MESSAGE + "Migration failed for usergroup with id {} in accountId: 2zPKqzWjT3SUyklYJvslKg",
Looking at the implementations of the method, it supports this format passed, because it will format it in a string and then call the method `void error(String var1, Throwable var2);`.
In the presence of multiple parameters, if the last argument in a logging statement is an exception, then SLF4J will presume that the user wants the last argument to be treated as an exception instead of a simple parameter.

2023-06-14 20:54 UTC, rafaelmart1ns commented
trigger uts

2023-06-14 21:29 UTC, Fernando-Dourado approved these changes

2023-07-12 12:53 UTC, rafaelmart1ns commented
trigger smartchecks

2023-07-12 12:53 UTC, rafaelmart1ns commented
trigger review

2023-07-17 12:18 UTC, merged