[fix]: [CDS-68805]: handling for <+lastPublished.tag> and <lastPublished.tag>.regex(xyz) GCS
harness/harness-core pull request #49217
Opened 2023-06-14 05:01 UTC by Abhishek-CDC

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-14 07:30 UTC, Abhishek-CDC commented
trigger uts

2023-06-14 07:55 UTC, AnshuH commented
trigger messagecheck

2023-06-14 08:12 UTC, AnshuH commented
trigger review

2023-06-14 09:19 UTC, PragyeshMishra01 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactDelegateRequest.java
>    /** Gcp Connector*/
pls make sure that this change is backward compatible by testing it with previous versions of delegate. Otherwise, it looks good to me.

2023-06-14 09:20 UTC, PragyeshMishra01 reviewed
@Abhishek-CDC added one comment

2023-06-14 09:28 UTC, Abhishek-CDC commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactDelegateRequest.java
>    /** Gcp Connector*/
Older delegate doesn't handle artifactPathRegex so it will fail if case is of regex.
But the only case where we put value to artifactPathRegex is when user provide expression <+lastPublished.tag> or <+lastPublished.tag>.regex(xyz) which is already not working

2023-06-14 09:47 UTC, PragyeshMishra01 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactDelegateRequest.java
>    /** Gcp Connector*/
I meant that existing functionalities shouldn't break. Let say if there is no artifactPathRegex in request, then older delegate should work. 
I remember kryo exceptions had came once in past, when we put a new field in between delegate request schema. So lets test existing flow once with older delegate.

2023-06-15 03:16 UTC, srinivaswings requested changes

2023-06-15 03:16 UTC, srinivaswings commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +      artifactPath = "";
Why do you need this need to set to empty

2023-06-15 03:16 UTC, srinivaswings commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java
>        throw new InvalidRequestException(INVALID_ARTIFACT_PATH_ERROR);
If Builds are empty how do you know that it is Invalid Artifact Path error.

2023-06-15 04:45 UTC, Abhishek-CDC commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> +      artifactPath = "";
This delegate request will be used for verifying if artifactPath and bucket provided are valid in ArtifactTaskHandler.
When user provide artifactPath as an expression with value <+lastPublished.tag> we want to treat it as a regex with value ".*?" which means any match.
When user provide artifactPath as an expression with value <+lastPublished.tag>.regex(someValue) we want to treat it as a regex with value "someValue".
These value we are populating to new field 'artifactPathRegex' and it will be used in ArtifactTaskHandler for verification. Since value of artifactPath will not be used further, assigning it as "".

Why to make it "":
- In GoogleCloudStorageArtifactTaskHandler we have logic to check one of artifactPath and artifactPathRegex should non be empty. For the cases mentioned above this check will return true even if artifactPathRegex is "" if we don't make it artifactPath "".

2023-06-15 04:56 UTC, Abhishek-CDC commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage/GoogleCloudStorageArtifactTaskHandler.java
>        throw new InvalidRequestException(INVALID_ARTIFACT_PATH_ERROR);
The build/buildDetail/artifactPath list we are comparing before throwing exception is not actually the entire list of artifactPath details for that bucket.

Logic:
- First we fetch entire list of artifactPath list for a bucket.
- if artifactPath is a fixed value, filter list by comparing artifactPath values with user provided value.
- if artifactPath is a regex value, filter list by pattern matching artifactPath values with user provided value.

After this filtering if list is empty it means there is no match with user provided value of artifactPath.
And since this is a verification step we throw exception with message "No artifact exist for the provided artifact path. Please ensure that artifact path is valid"

2023-06-15 20:15 UTC, srinivaswings reviewed
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49217)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-15 20:15 UTC, srinivaswings requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49217)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/49217#gh-1230369755:-NY-ge0k5UXlr9Ya4n7E:b2nhlk9) (no related file):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

This delegate request will be used for verifying if artifactPath and bucket provided are valid in ArtifactTaskHandler.
When user provide artifactPath as an expression with value <+lastPublished.tag> we want to treat it as a regex with value ".*?" which means any match.
When user provide artifactPath as an expression with value <+lastPublished.tag>.regex(someValue) we want to treat it as a regex with value "someValue".
These value we are populating to new field 'artifactPathRegex' and it will be used in ArtifactTaskHandler for verification. Since value of artifactPath will not be used further, assigning it as "".

Why to make it "":
- In GoogleCloudStorageArtifactTaskHandler we have logic to check one of artifactPath and artifactPathRegex should non be empty. For the cases mentioned above this check will return true even if artifactPathRegex is "" if we don't make it artifactPath "".
</blockquote></details>

Ok

___
*[a discussion](https://reviewable.io/reviews/harness/harness-core/49217#gh-1230372518:-NY-ghrr8dP4BwyeuzY2:b-896fjx) (no related file):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

The build/buildDetail/artifactPath list we are comparing before throwing exception is not actually the entire list of artifactPath details for that bucket.

Logic:
- First we fetch entire list of artifactPath list for a bucket.
- if artifactPath is a fixed value, filter list by comparing artifactPath values with user provided value.
- if artifactPath is a regex value, filter list by pattern matching artifactPath values with user provided value.

After this filtering if list is empty it means there is no match with user provided value of artifactPath.
And since this is a verification step we throw exception with message "No artifact exist for the provided artifact path. Please ensure that artifact path is valid"
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2023-06-16 12:54 UTC, PragyeshMishra01 approved these changes

2023-06-16 12:56 UTC, Abhishek-CDC commented
trigger messagecheck

2023-06-16 13:02 UTC, merged