fix: [CDS-71315]: fixing bug for releases in Blue green
harness/harness-core pull request #49228
Opened 2023-06-14 06:54 UTC by TarunUba1

## Describe your changes
saving older release with bgEnv: stage if new release moved to primary and maintainig a consistency
## Testing
for both K8sLegacyRelease and K8Release, steps tested on.
2,3 succesfull -> 1 failed after apply step -> 1 failed in Swap step but before swap -> Succesful -> add two consecutive step in pipeline then and check that the deployed one is marked as stage at the end
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-14 08:16 UTC, abosii-harness requested changes

2023-06-14 08:16 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +        release.setBgEnvironment(bgStageEnv);
can we have a method in release.swapBgEnvironment?

2023-06-14 13:18 UTC, abhinavsingh1196 requested changes

2023-06-14 13:18 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java
> +    if (isNotEmpty(releaseHistory.getReleases())) {
should combine these two if conditions

2023-06-14 13:19 UTC, abosii-harness requested changes
Can you add UTs for all new methods and logic you've added?

2023-06-14 13:19 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +    switch (this.getBgEnvironment()) {
We should handle null bgEnvironment

2023-06-14 13:19 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
> +    switch (this.getBgEnvironment()) {
We should handle null bgEnvironment

2023-06-14 13:19 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +  public IK8sRelease getSecondLastSuccessfulBlueGreenRelease(int currReleaseNumber) {
This logic can be improved we would retrieve the color from the service selector and search by last successful matching a specific color. This can be applied to the latest. Is this possible to be done?

2023-06-14 13:21 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java
> +    if (isNotEmpty(releaseHistory.getReleases())) {
I didn't combine so that Nullpointer Doesn't come in If condition

2023-06-14 13:21 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +    switch (this.getBgEnvironment()) {
Ok

2023-06-14 13:24 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +  public IK8sRelease getSecondLastSuccessfulBlueGreenRelease(int currReleaseNumber) {
We dont require this logic cause we are only saving two successful or one failed one successful ata ny time max

2023-06-14 13:26 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java
> +    if (isNotEmpty(releaseHistory.getReleases())) {
we can still get rid of the nested IFs, just do 
if (isEmpty(releases))return null;
if(releases.size() >=2) {
    ...
}
return null;

2023-06-14 13:27 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +  public IK8sRelease getSecondLastSuccessfulBlueGreenRelease(int currReleaseNumber) {
What if we would decide to save more than 1?

2023-06-14 13:36 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +  public IK8sRelease getSecondLastSuccessfulBlueGreenRelease(int currReleaseNumber) {
cool will do

2023-06-14 13:53 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +  public IK8sRelease getSecondLastSuccessfulBlueGreenRelease(int currReleaseNumber) {
We can't get release color directly for Legacy release
![Screenshot 2023-06-14 at 7 22 34 PM](https://github.com/harness/harness-core/assets/106597485/cbec9483-6ec4-4058-a6df-1b90e38a5bc2)

2023-06-14 14:01 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +  public IK8sRelease getSecondLastSuccessfulBlueGreenRelease(int currReleaseNumber) {
i cant do this for legacy release as to check for color the function in that case is 
![Screenshot 2023-06-14 at 7 22 34 PM](https://github.com/harness/harness-core/assets/106597485/0ff26f87-83de-4537-a0dc-8f3a633c060c)

2023-06-14 14:39 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +  public IK8sRelease getSecondLastSuccessfulBlueGreenRelease(int currReleaseNumber) {
We already have logic to find releases matching a specific color

2023-06-14 19:00 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +        return;
unable to run tests written by Pratyush, will be taking that part out

2023-06-15 13:36 UTC, TarunUba1 commented
trigger uts

2023-06-15 14:36 UTC, abosii-harness requested changes

2023-06-15 14:36 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsHandler.java
> +      k8sTaskHelperBase.saveRelease(useDeclarativeRollback, false, kubernetesConfig, primaryRelease, releaseHistory,
Why we're doing this twice?

2023-06-15 14:36 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsHandler.java
> +    IK8sRelease primaryRelease = getLatestSuccessfulRelease(primaryColorReleases);
Can we move this logic to a a method in the releaseHistory, getLatestSuccessfulReleaseMatchingColor

2023-06-15 14:36 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsHandler.java
> +      k8sTaskHelperBase.saveRelease(useDeclarativeRollback, false, kubernetesConfig, primaryRelease, releaseHistory,
My guess is that this is required only for declarative, so this should be handled respectively. Can we move this to updateReleaseHistory method?

2023-06-15 14:44 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    V1Service service1 = kubernetesContainerService.getService(kubernetesConfig, service);
nit: don't name this `service1`

2023-06-15 15:00 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8SLegacyReleaseHistory.java
> +  public List<IK8sRelease> getReleasesMatchingColor(String color) {
refer above comment for refactor

2023-06-15 15:03 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    V1Service service1 = kubernetesContainerService.getService(kubernetesConfig, service);
I mean i can prevent it but like changes will be bad, we only return boolean and that function is then used in KubernetesSwapServiceSelectorsTask where it checks boolean.

2023-06-15 16:13 UTC, TarunUba1 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandlerTest.java
> +    V1Service service1 = createService("service1", ImmutableMap.of(harnessColorSelector, "blue"));
Done

2023-06-15 16:23 UTC, TarunUba1 commented
trigger uts

2023-06-15 16:49 UTC, abosii-harness requested changes

2023-06-15 16:49 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +            .filter(release -> release.getReleaseStatus().equals(IK8sRelease.Status.Succeeded))
Can we combine these streams? 
releaseHistory.stream()
            .map(K8sRelease.class ::cast)
            .filter(release -> K8sReleaseSecretHelper.checkReleaseColor(release.getReleaseSecret(), color))
             .filter(release -> release.getReleaseStatus().equals(IK8sRelease.Status.Succeeded))
             .max(Comparator.comparing(IK8sRelease::getReleaseNumber))?

2023-06-15 17:11 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistory.java
> +            .filter(release -> release.getReleaseStatus().equals(IK8sRelease.Status.Succeeded))
Done

2023-06-15 17:14 UTC, abosii-harness approved these changes

2023-06-15 17:15 UTC, TarunUba1 commented
trigger uts

2023-06-15 17:21 UTC, abhinavsingh1196 approved these changes

2023-06-15 17:32 UTC, TarunUba1 commented
trigger review

2023-06-15 17:34 UTC, merged