feat: [CDS-70335]: Delegate backward compatibility changes and adding FFs for K8s and Native Helm instance sync NG
harness/harness-core pull request #49380
Opened 2023-06-19 09:28 UTC by namantalaycha10

## Describe your changes
 Delegate backward compatibility changes and adding FFs for K8s and Native Helm instance sync NG

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-19 09:43 UTC, alebuh commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +    return delegateGrpcClientWrapper.isTaskTypeSupported(AccountId.newBuilder().setId(accountId).build(),
In the past, this method didn't work as expected, at least how we expected it to work, so we had to remove it from our code. The problem was that in order for this method return true, all delegates needed to support the task type. So if they had at least one delegate that doesn't support it it will return false. Not sure if that is fixed, so could you check with someone from the delegate team if this method is working and what is expected behavior?

2023-06-19 10:01 UTC, alebuh requested changes

2023-06-19 10:01 UTC, alebuh commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  INSTANCE_SYNC_V2_NG_SUPPORT(TaskGroup.K8S, "Instance sync V2 support for CG");
In the name is NG and in the description is CG

2023-06-19 10:01 UTC, namantalaycha10 commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +    return delegateGrpcClientWrapper.isTaskTypeSupported(AccountId.newBuilder().setId(accountId).build(),
This behaviour we are aware, and in this case we want all the delegate to support the Task Type, so this will not be a problem.

2023-06-19 10:02 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  INSTANCE_SYNC_V2_NG_SUPPORT(TaskGroup.K8S, "Instance sync V2 support for CG");
ohh missed this , changing

2023-06-19 10:49 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  INSTANCE_SYNC_V2_NG_SUPPORT(TaskGroup.K8S, "Instance sync V2 support for CG");
Also, TaskGroup.K8S_NG should be used instead?

2023-06-19 13:08 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java
> +  INSTANCE_SYNC_V2_NG_SUPPORT(TaskGroup.K8S, "Instance sync V2 support for CG");
Thanks for Pointing , making this change

2023-06-19 13:15 UTC, abosii-harness commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_K8S_HELM_INSTANCE_SYNC_V2_NG(
Should we mark this as supported right now? We should first ensure that there are no bugs before actually marking this task as prod ready

2023-06-20 11:14 UTC, namantalaycha10 commented
trigger uts

2023-06-20 11:15 UTC, namantalaycha10 commented
trigger uts

2023-06-20 11:29 UTC, abhinavsingh1196 requested changes

2023-06-20 11:29 UTC, abhinavsingh1196 commented on 126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java
> +    /*  when(cdFeatureFlagHelper.isEnabled(any(), any())).thenReturn(true);
this comment should be removed

2023-06-20 12:10 UTC, namantalaycha10 commented on 126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java
> +    /*  when(cdFeatureFlagHelper.isEnabled(any(), any())).thenReturn(true);
Done

2023-06-20 12:11 UTC, namantalaycha10 commented
trigger uts

2023-06-20 12:17 UTC, abhinavsingh1196 approved these changes

2023-06-20 12:24 UTC, TarunUba1 approved these changes

2023-06-20 12:38 UTC, namantalaycha10 commented
trigger messagecheck, review

2023-06-20 12:39 UTC, namantalaycha10 commented
trigger messagecheck

2023-06-20 12:46 UTC, abosii-harness approved these changes

2023-06-20 13:09 UTC, namantalaycha10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49380)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 

___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/49380#gh-1234048824:-NYNv1vF5LMdtw-qkKIt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7bf740dc9e4220c8d85bfc8f21bc62cea91e6c13/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L399)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What is the point of having 2 methods? Can we just merge everything in one method?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-20 13:12 UTC, alebuh approved these changes
> Reviewed 1 of 9 files at r2, 6 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49380)* status: 8 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-20 13:12 UTC, merged