fix: [CDS-71316]: delegate and manager side changes
harness/harness-core pull request #49414
Opened 2023-06-19 17:46 UTC by TarunUba1

## Describe your changes
Adding delegate changes of adding a new field in release and checking with the current manifest is same
In this case we will create an Outcome with a field "skipped" as true.
On manager side we need to handle such outcome and save in sweeping outcome
In swapStep we check if its stage skipped? In which case we skip the step with message 
"Stage Deployment (Blue Green Deploy) was skipped. Manifest to deploy match already deployed manifest"
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-20 05:44 UTC, GoelPratyush99 requested changes

2023-06-20 05:44 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    deploymentSkipped = false;
Setting deploymentSkipped = false seems redundant as we have already set it to false in L:156 and the only place it  is getting update is inside the above if statement

2023-06-20 05:48 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    deploymentSkipped = false;
missed it, thanks

2023-06-20 05:50 UTC, abhinavsingh1196 requested changes

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStep.java
> +      "Stage Deployment (Blue Green Deploy) was skipped. Manifest to deploy match already deployed manifest";
nit: Stage Deployment (Blue Green Deploy) was skipped because given manifest matches existing deployed manifest.

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStep.java
> +  public static final String SKIP_BG_SWAP_WHEN_STAGE_DEPLOYMENT_SKIPPED =
can be private?

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +    boolean deploymentSkipped = (k8sBGDeployResponse.getSkipped() != null) ? k8sBGDeployResponse.getSkipped() : false;
stageSkipped is a primitive boolean, would be false by default

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +    K8sBlueGreenOutcome k8sBlueGreenOutcome;
nit: no reason to have this var active across the whole func below

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +          ambiance, K8sPodToServiceInstanceInfoMapper.toServerInstanceInfoList(Collections.emptyList()));
does this need to be done?

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +          releaseHistory.getLatestSuccessfulReleaseMatchingColor(primaryColor).getManifestHash();
we should add null check here? getLatestSuccessfulReleaseMatchingColor() could return null?

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        executionLogCallback.saveExecutionLog(color("\nSkipping stage deployment", Yellow, Bold), INFO);
nit: we should write more info, like `Skipping stage deployment because given manifest matches existing deployed manifest`.

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    deploymentSkipped = false;
it's already set to false otherwise? this looks redundant

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployResponse.java
> +  Boolean skipped;
nit: this var name should be consistent

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +          releaseHistory.getLatestSuccessfulReleaseMatchingColor(primaryColor).getManifestHash();
just thinking if we can use getLatestSuccessfulRelease() instead? 
Though, it may not work for cases like when BG deploy was done and swap failed (or something else failed after that) ?

2023-06-20 05:50 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenOutcome.java
> +  boolean stageSkipped;
nit: should probably name this `stageDeploymentSkipped` ?

2023-06-20 06:04 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStep.java
> +  public static final String SKIP_BG_SWAP_WHEN_STAGE_DEPLOYMENT_SKIPPED =
will be used in Test file, siilar to other variables

2023-06-20 06:09 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +          releaseHistory.getLatestSuccessfulReleaseMatchingColor(primaryColor).getManifestHash();
Yup thats why checking only with the primary service

2023-06-20 12:17 UTC, TarunUba1 commented
trigger uts

2023-06-20 12:32 UTC, abhinavsingh1196 requested changes

2023-06-20 12:32 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +      if (k8sBGDeployResponse.getStageDeploymentSkipped()) {
these two IFs can be combined, it will be null safe. Or just use apache commons
`BooleanUtils.isTrue(k8sBGDeployResponse.getStageDeploymentSkipped())`

2023-06-20 12:32 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        if (primaryReleaseHash.equals(currentManifestHash)) {
nit: if you reverse this condition, then the above isNotEmpty check can be removed as well
`if (currentManifestHash.equals(primaryRelease.getManifestHash()))`

2023-06-20 12:44 UTC, abosii-harness requested changes

2023-06-20 12:44 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    if (skipUnchangedManifest) {
This may lead to an issue where customer can't just enable and disable the field and expect that the next deployments will work fine with feat enabled. For example:
1. Customer is setting skipUnchangedManifest as runtime input
2. Customer is doing a deployment with this set as false
3. Customer is doing next deployment with this set as true

The expectations could be that deployment is skipped since there are no changes. So the actual logic behind generating release hash shouldn't be based on the field input. I guess the best way to go is to have the logic of storing the hash behind the FF, so there would be 2 enablers:
1. skipUnchangedManifest
2. storeReleaseHash

2023-06-20 12:44 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +        return responseBuilder.status(Status.SUCCEEDED)
Have you tried to set the status here as SKIPPED? What is the behavior? If this is working as expected, should we then check with Rohan if in such scenarios should we mark step as skipped? 
This can help customer to rely on the step status

2023-06-20 13:57 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +        if (primaryReleaseHash.equals(currentManifestHash)) {
Nice ways huh up your sleeve to reduce if conditions, i was thinking also to reduce them but then no luck

2023-06-20 14:00 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +        return responseBuilder.status(Status.SUCCEEDED)
As discussed skipping it

2023-06-20 14:00 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    if (skipUnchangedManifest) {
Done

2023-06-20 14:06 UTC, TarunUba1 commented
trigger messagecheck

2023-06-20 14:21 UTC, abhinavsingh1196 approved these changes

2023-06-20 14:21 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java
>    public String manifestHash(List<KubernetesResource> resources, K8sDelegateTaskParams k8sDelegateTaskParams,
discussed offline, please add a unit test for this method as well in a future PR

2023-06-20 14:58 UTC, acasian-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    release.setManifestHash(currentManifestHash);
did we validated delegate n and then n-1 version of the same deployment?

2023-06-20 15:00 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    release.setManifestHash(currentManifestHash);
Yes i did, now adding another field to check only FF to keep this change behind FF

2023-06-20 15:01 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +    release.setManifestHash(currentManifestHash);
For safety purposes

2023-06-20 15:28 UTC, TarunUba1 commented
trigger uts

2023-06-20 16:58 UTC, abosii-harness approved these changes

2023-06-21 04:00 UTC, abhinavsingh1196 approved these changes

2023-06-21 04:00 UTC, abhinavsingh1196 commented
trigger review

2023-06-21 04:52 UTC, GoelPratyush99 approved these changes

2023-06-21 04:52 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +      K8sBlueGreenOutcome k8sBlueGreenOutcome = K8sBlueGreenOutcome.builder().stageDeploymentSkipped(true).build();
nit: As k8sBGDeployResponse.getStageDeploymentSkipped() is true can we use the same value in the builder
`K8sBlueGreenOutcome k8sBlueGreenOutcome = K8sBlueGreenOutcome.builder().stageDeploymentSkipped(k8sBGDeployResponse.getStageDeploymentSkipped()).build();`

2023-06-21 04:57 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBlueGreenStep.java
> +      K8sBlueGreenOutcome k8sBlueGreenOutcome = K8sBlueGreenOutcome.builder().stageDeploymentSkipped(true).build();
if condition is for that purpose, it gives checkstyle error if the value is always true in 'if' condition and you try to again fetch it

2023-06-21 04:57 UTC, merged