[feat]:[CDS-72442]: Created CRUD calls and resources for Step Instance Info for CV
harness/harness-core pull request #49498
Opened 2023-06-21 01:29 UTC by arvind-choudhary-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-21 18:04 UTC, arvind-choudhary-h commented
trigger uts

2023-06-25 15:16 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInstanceInfoService.java
> +  List<StepExecutionInstanceInfo> get(String accountIdentifier, String orgIdentifier, String projectIdentifier,
should this not be returning just 1 element always ?

2023-06-28 04:00 UTC, arvind-choudhary-h commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInstanceInfoService.java
> +  List<StepExecutionInstanceInfo> get(String accountIdentifier, String orgIdentifier, String projectIdentifier,
No no, this would return multiple-step instance info list on what all happened in this stage.

2023-06-30 05:32 UTC, arvind-choudhary-h commented
trigger uts

2023-06-30 05:32 UTC, yogesh-chauhan approved these changes

2023-06-30 07:52 UTC, yogesh-chauhan commented
trigger checkstylecodeformat

2023-06-30 10:59 UTC, puthrayaharness submitted a review, later dismissed

2023-07-02 10:06 UTC, ivan-83 approved these changes
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 13 file(s) to review. 1. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instance/InstanceNGResource.java` line 80 at r3](https://reviewable.io/reviews/harness/harness-core/49498#-NZKzory7iydeeFBSJ7p:-NZKzory7iydeeFBSJ7q:b-aq567d) ([raw file](https://github.com/harness/harness-core/blob/43c6900c794d8850954baaf9b65cd8ac9d578496/120-ng-manager/src/main/java/io/harness/ng/instance/InstanceNGResource.java#L80)):*
> ```Java
>   @GET
>   @Path("/stage-instance-info")
>   //  @InternalApi
> ```

Minor - remove the comment
___
*[`120-ng-manager/src/main/java/io/harness/ng/instance/InstanceNGResource.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/49498#-NZKzrxIBauRKVkQAZq9:-NZKzrxJBfStHQHhObS2:b-yvawlt) ([raw file](https://github.com/harness/harness-core/blob/43c6900c794d8850954baaf9b65cd8ac9d578496/120-ng-manager/src/main/java/io/harness/ng/instance/InstanceNGResource.java#L87)):*
> ```Java
>       @NotNull @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @NotNull @QueryParam(NGCommonEntityConstants.PIPELINE_EXECUTION_ID) String pipelineExecutionId,
>       @NotNull @QueryParam(NGCommonEntityConstants.STAGE_KEY) String stageExecutionId) {
> ```

Minor - NGCommonEntityConstants.STAGE_KEY, should it be STAGE_EXECUTION_ID
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInstanceInfoService.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/49498#gh-1241218921:-NZL2jxQE1xqp5Elyhh1:bgf7pk7) ([raw file](https://github.com/harness/harness-core/blob/4905221ce8c0638b1793466ea51426eeb637aff2/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInstanceInfoService.java#L20)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

No no, this would return multiple-step instance info list on what all happened in this stage.
</blockquote></details>

and one StepExecutionInstanceInfo contains the list of deployed/after/before service instances, right?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/repositories/executions/StageExecutionInstanceInfoRepositoryCustomImpl.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/49498#-NZL0fb58-WbKRf5tL6e:-NZL0fb58-WbKRf5tL6f:b-jv69a0) ([raw file](https://github.com/harness/harness-core/blob/43c6900c794d8850954baaf9b65cd8ac9d578496/125-cd-nextgen/modules/common/core/src/main/java/io/harness/repositories/executions/StageExecutionInstanceInfoRepositoryCustomImpl.java#L30)):*
> ```Java
> 
>   @Override
>   public StageExecutionInstanceInfo append(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

Minor - append could be renamed to updateStageExecutionInstanceInfos or...


<!-- Sent from Reviewable.io -->

2023-07-03 06:38 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/instance/InstanceNGResource.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/49498#-NZKzrxIBauRKVkQAZq9:-NZPTE1j4FHxWRjPFkUF:bbt660n) ([raw file](https://github.com/harness/harness-core/blob/43c6900c794d8850954baaf9b65cd8ac9d578496/120-ng-manager/src/main/java/io/harness/ng/instance/InstanceNGResource.java#L87)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - NGCommonEntityConstants.STAGE_KEY, should it be STAGE_EXECUTION_ID
</blockquote></details>

STAGE_KEY actually is "stageExecutionId" only 


<!-- Sent from Reviewable.io -->

2023-07-03 06:38 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInstanceInfoService.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/49498#gh-1241218921:-NZPTJCD4lpb_1Da3q9W:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/4905221ce8c0638b1793466ea51426eeb637aff2/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/service/StageExecutionInstanceInfoService.java#L20)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

and one StepExecutionInstanceInfo contains the list of deployed/after/before service instances, right?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2023-07-03 07:11 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498#-:-NZP_lVo65nN6kucbOV8:bnfp4nl)* status: 13 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-07-05 07:30 UTC, ivan-83 requested changes
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained.  (waiting on @sarthakkasat)

___
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 1008 at r5](https://reviewable.io/reviews/harness/harness-core/49498#-NZZxLjR2pnPO-1tNfkK:-NZZxLjR2pnPO-1tNfkL:bcnbgu6) ([raw file](https://github.com/harness/harness-core/blob/6895effe00d48a8bd931104a6333a351b6c53068/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L1008)):*
> ```help
> io.harness.cdng.execution.StepInstanceInfo
> io.harness.cdng.execution.K8sStepInstanceInfo
> io.harness.cdng.execution.StepExecutionInstanceInfo
> ```

why do we have a lot of new aliases?


<!-- Sent from Reviewable.io -->

2023-07-05 07:32 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 1008 at r5](https://reviewable.io/reviews/harness/harness-core/49498#-NZZxLjR2pnPO-1tNfkK:-NZZxjpJ6G_XExXDKKuL:b-cnoq5m) ([raw file](https://github.com/harness/harness-core/blob/6895effe00d48a8bd931104a6333a351b6c53068/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L1008)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

why do we have a lot of new aliases?
</blockquote></details>

Classes which have recaster alias annotation should be added to these file.


<!-- Sent from Reviewable.io -->

2023-07-05 07:35 UTC, ivan-83 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.  (waiting on @sarthakkasat)

___
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 1008 at r5](https://reviewable.io/reviews/harness/harness-core/49498#-NZZxLjR2pnPO-1tNfkK:-NZZyE5C6VYmpk5A8QtT:bo5pic0) ([raw file](https://github.com/harness/harness-core/blob/6895effe00d48a8bd931104a6333a351b6c53068/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L1008)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

Classes which have recaster alias annotation should be added to these file.
</blockquote></details>

yes, but it should be already added, right? Why do we have a lot of new or smt wrong with Reviewable?


<!-- Sent from Reviewable.io -->

2023-07-05 07:38 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 1008 at r5](https://reviewable.io/reviews/harness/harness-core/49498#-NZZxLjR2pnPO-1tNfkK:-NZZzDCR1v8vhahdpUkJ:b-ul25wm) ([raw file](https://github.com/harness/harness-core/blob/6895effe00d48a8bd931104a6333a351b6c53068/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L1008)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

yes, but it should be already added, right? Why do we have a lot of new or smt wrong with Reviewable?
</blockquote></details>

![](file:///var/folders/qn/s9rv8_4s3ml_dgf0xr5fl2g80000gp/T/TemporaryItems/NSIRD_screencaptureui_Tfvusq/Screenshot%202023-07-05%20at%201.07.48%20PM.png)
![image.png](https://files.reviewableusercontent.io/images/reviewable/109350689/PeBnsAaktdVtXxNzBtJDV4Hb/image.png)
The changes are only in 3 files, may be you are seeing it in a wrong revision


<!-- Sent from Reviewable.io -->

2023-07-05 07:41 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498#-:-NZZzoXq2SBCPlE-coHa:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.  (waiting on @sarthakkasat)



<!-- Sent from Reviewable.io -->

2023-07-05 07:43 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498#-:-NZ_-8ne0URsrecfYhhT:bg7igk9)* status: 13 file(s) to review. 1 of 2 approvals obtained.  (waiting on @sarthakkasat)



<!-- Sent from Reviewable.io -->

2023-07-05 07:43 UTC, yogesh-chauhan approved these changes
> Reviewed 10 of 11 files at r1, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 13 file(s) to review. 1 of 2 approvals obtained.  (waiting on @sarthakkasat)



<!-- Sent from Reviewable.io -->

2023-07-05 07:43 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 13 file(s) to review. 1 of 2 approvals obtained.  (waiting on @sarthakkasat)



<!-- Sent from Reviewable.io -->

2023-07-05 07:44 UTC, sarthakkasat commented
trigger uts

2023-07-05 09:04 UTC, sarthakkasat commented
trigger review

2023-07-05 09:49 UTC, sarthakkasat commented
trigger uts

2023-07-05 09:51 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49498)* status: 14 file(s) to review. 1 of 2 approvals obtained.  (waiting on @sarthakkasat)



<!-- Sent from Reviewable.io -->

2023-07-05 10:05 UTC, merged