fix: [CDS-69449]: add custom string list deserializer for items in repeat looping strategy
harness/harness-core pull request #49507
Opened 2023-06-21 05:13 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-21 06:21 UTC, mohitg0795 commented on 953-yaml-commons/src/main/java/io/harness/serializer/jackson/CustomStringListDeserializer.java
> +  public ParameterField<List<String>> deserialize(JsonParser jsonParser, DeserializationContext deserializationContext)
a UT would be great to have here

2023-06-23 08:43 UTC, archit-harness requested changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49507)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/test/java/io/harness/yaml/utils/JsonPipelineUtilsTest.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/49507#-NYbQ47Q84YWK71mV3mM:-NYbQ47Q84YWK71mV3mN:bjsoi6y) ([raw file](https://github.com/harness/harness-core/blob/9a5165838b3bb63c46e3e92d6c93286cf179ded9/953-yaml-commons/src/test/java/io/harness/yaml/utils/JsonPipelineUtilsTest.java#L36)):*
> ```Java
>         + "  items: \"[\\\"a\\\",\\\"b\\\"]\"";
>     StrategyConfig strategyConfig =
>         JsonPipelineUtils.read(YamlUtils.readAsJsonNode(yaml).toString(), StrategyConfig.class);
> ```

what is this test checking?


<!-- Sent from Reviewable.io -->

2023-06-23 08:46 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49507)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/test/java/io/harness/yaml/utils/JsonPipelineUtilsTest.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/49507#-NYbQ47Q84YWK71mV3mM:-NYbQK6c9FNdS0ZYD4Mh:b-pw31gv) ([raw file](https://github.com/harness/harness-core/blob/9a5165838b3bb63c46e3e92d6c93286cf179ded9/953-yaml-commons/src/test/java/io/harness/yaml/utils/JsonPipelineUtilsTest.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what is this test checking?
</blockquote></details>

in the repeat, we have given items as a string with its value as a list. Without the change, this test will fail with mismatchedInputException similar to the use case described in the ticket.


<!-- Sent from Reviewable.io -->

2023-06-23 09:03 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49507)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-23 10:21 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49507)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-23 10:35 UTC, shalini-agr commented
trigger uts

2023-06-23 11:13 UTC, archit-harness approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49507)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-23 11:26 UTC, brijeshdhakar approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49507)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-23 11:41 UTC, merged