[feat]: [CDS-65736]: Moving the TimeoutEngine iterator to Redis-batch mode
harness/harness-core pull request #49552
Opened 2023-06-21 14:32 UTC by brijeshdhakar

## Describe your changes

Currently our TimeoutEngine Iterator runs in the `Loop` mode. Which runs the `findAndModify` operation from all the pods in which they are running. This causes a lot of write conflicts and increases the load on the Mongo cluster. Another major disadvantage with findAndModify is that it operates on one document at a time thus it can cause significant delays in processing the documents and network overhead.

Now we are moving the TimeoutEngine to the `Redis batch mode`. This will ensure that multiple pods are not working on the same set of documents. This work on batches of documents thereby optimizing the iterator delay and network overheads. 

We have made the iteratorMode configurable so that we can use whatever mode we want to use for TimeoutEngine iterator.

Testing:
- Able to switch between modes by changing the value in config.yaml
- Did basic testing in the local for the timeouts that timeouts are happening on right time.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/49552)

2023-06-28 07:50 UTC, brijeshdhakar commented
trigger uts

2023-06-28 08:32 UTC, brijeshdhakar commented
trigger uts

2023-06-28 17:43 UTC, Raghav-Murali commented on 959-timeout-engine/src/main/java/io/harness/timeout/TimeoutEngine.java
> +            .schedulingType(REGULAR));
No need to specify this, Redis mode currently has support only for Regular scheduling type.

2023-06-28 17:46 UTC, Raghav-Murali commented on 960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java
>          notifyAll();
For notifyAll() to work we need to use `wait` but currently we are using `sleep` in `redisBatchProcess()`. Can you also make below update in `redisBatchProcess()` -

Instead of -

if (docIds.isEmpty()) {
        sleep(threadPoolIntervalInSeconds);
}

do this for notifyAll() to work -

if (docIds.isEmpty()) {
        synchronized (this) {
            wait(threadPoolIntervalInSeconds);
        }
}

Also, just test it once for your iterator if with above change you're able to wake up the sleeping iterator thread.

2023-06-28 17:51 UTC, Raghav-Murali commented on 960-persistence/src/main/java/io/harness/redis/iterator/RedisIteratorConfig.java
> +}
Can we re-use this - `DynamicIteratorConfig` in `960-persistence/src/main/java/io/harness/iterator/IteratorExecutionHandler.java` ? To avoid redundancies ?

2023-06-29 06:28 UTC, archit-harness commented on 960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java
>          notifyAll();
@Raghav-Murali the testing for thread is able to wakeup, do you recommend anything?

2023-06-29 09:00 UTC, Raghav-Murali commented on 960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java
>          notifyAll();
@archit-harness - I'd suggest using a very high value for threadPoolIntervalInSeconds (maybe 300 - 600 secs ?) and try to wake up the thread. Current value of 2 secs is too less to test this scenario ? 

Since there is no thread to notify because we're using `sleep` in line 380 I doubt the thread actually being notified, its probably just waking up on its own after sleeping for 2secs.

2023-07-11 09:34 UTC, brijeshdhakar commented on 960-persistence/src/main/java/io/harness/redis/iterator/RedisIteratorConfig.java
> +}
Done

2023-07-11 10:56 UTC, brijeshdhakar commented on 960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java
>          notifyAll();
@Raghav-Murali how is the `InterruptedException` handled? I mean what happens when the thread while waiting(or sleep) gets interrupted?
I see that sleep is throwing `InterruptedRuntimeException` exception after catching `InterruptedException`. But don't see any other handling for `InterruptedRuntimeException`.

2023-07-11 11:51 UTC, brijeshdhakar commented on 960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java
>          notifyAll();
Made the changes to use wait instead of sleep and tested.
Tested the wait by putting a big interval time. With sleep, the threads were waking after the specified time. But on using the wait, the threads were being waken on coming new tasks.(From timeoutEngine)

2023-07-11 11:58 UTC, brijeshdhakar commented
trigger uts

2023-07-11 12:56 UTC, archit-harness requested changes
> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49552)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`959-timeout-engine/src/main/java/io/harness/timeout/TimeoutEngine.java` line 138 at r4](https://reviewable.io/reviews/harness/harness-core/49552#-N_3zsgh2XdiGRpTcOUD:-N_3zsgh2XdiGRpTcOUE:b-o0rfm4) ([raw file](https://github.com/harness/harness-core/blob/cb3868e974a3627180e91178c0e865ce66e85031/959-timeout-engine/src/main/java/io/harness/timeout/TimeoutEngine.java#L138)):*
> ```Java
>                            .handler(this)
>                            .persistenceProvider(new SpringPersistenceRequiredProvider<>(mongoTemplate))
>                            .schedulingType(REGULAR));
> ```

remove this regular specification
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 386 at r4](https://reviewable.io/reviews/harness/harness-core/49552#-N_4-PsG01YSfLMISp7f:-N_4-PsHEXE6kfYtzV-Z:b-8xx7to) ([raw file](https://github.com/harness/harness-core/blob/cb3868e974a3627180e91178c0e865ce66e85031/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L386)):*
> ```Java
>           } catch (InterruptedException e) {
>             Thread.currentThread().interrupt();
>             throw new InterruptedRuntimeException(e);
> ```

I dont think we need to throw exception, as current thread is interrupted thus no need to throw


<!-- Sent from Reviewable.io -->

2023-07-11 13:16 UTC, archit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49552)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/config/config.yml` line 288 at r4](https://reviewable.io/reviews/harness/harness-core/49552#-N_44xdY-3yXHxjtcj5U:-N_44xdY-3yXHxjtcj5V:b-m1m4fm) ([raw file](https://github.com/harness/harness-core/blob/cb3868e974a3627180e91178c0e865ce66e85031/pipeline-service/config/config.yml#L288)):*
> ```YAML
>     targetIntervalInSeconds: 10
>   timeoutEngineRedisMode:
>     threadPoolSize: 5
> ```

make this configurable
___
*[`pipeline-service/config/config.yml` line 293 at r4](https://reviewable.io/reviews/harness/harness-core/49552#-N_44z43EFZK_XU2e_Jp:-N_44z43EFZK_XU2e_Jq:b-yqposw) ([raw file](https://github.com/harness/harness-core/blob/cb3868e974a3627180e91178c0e865ce66e85031/pipeline-service/config/config.yml#L293)):*
> ```YAML
>     threadPoolIntervalInSeconds: 2
>     redisLockTimeout: 5
>     redisBatchSize: 10
> ```

make this configurable for batch size


<!-- Sent from Reviewable.io -->

2023-07-11 13:33 UTC, brijeshdhakar commented
trigger uts

2023-07-11 17:29 UTC, brijeshdhakar commented
trigger ut1

2023-07-11 19:10 UTC, Raghav-Murali approved these changes

2023-07-12 06:15 UTC, archit-harness approved these changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49552)* status: 7 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-12 06:15 UTC, brijeshdhakar commented
trigger messagecheck

2023-07-12 06:16 UTC, brijeshdhakar commented
trigger review

2023-07-12 08:43 UTC, merged