fix: [PL-37955]: force refresh cache only places that needs update
harness/harness-core pull request #49628
Opened 2023-06-22 19:07 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-27 23:30 UTC, jennyjames21 commented
trigger uts

2023-06-28 07:49 UTC, jennyjames21 commented
trigger uts

2023-06-28 16:15 UTC, jennyjames21 commented
trigger uts

2023-06-28 18:41 UTC, jennyjames21 commented
trigger uts

2023-06-29 05:04 UTC, raghuAtWings requested changes

2023-06-29 05:04 UTC, raghuAtWings commented on 400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java
> +            .filter(delegate -> !delegateDao.isDelegateHeartBeatUpToDate(delegate, MAX_DELEGATE_LONG_LAST_HEARTBEAT))
why take MAX_DELEGATE_LONG_LAST_HEARTBEAT as an argument? why not just hardcode it in the implementation ?

2023-06-30 05:49 UTC, jennyjames21 commented on 400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java
> +            .filter(delegate -> !delegateDao.isDelegateHeartBeatUpToDate(delegate, MAX_DELEGATE_LONG_LAST_HEARTBEAT))
Different places have different expiry currently, we can keep it consistent eventually.
But they also different use cases like 
1) 5 mins expiry : to mark delegate  as disconnected in DB so that PT be balanced and expire task
2) 8 mins expiry: active delegate list to calculate eligible delegate list
3) 1 mins: to mark as disconnected in the UI

2023-07-03 06:02 UTC, jennyjames21 commented
trigger uts

2023-07-03 06:02 UTC, jennyjames21 commented on 400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java
> +            .filter(delegate -> !delegateDao.isDelegateHeartBeatUpToDate(delegate, MAX_DELEGATE_LONG_LAST_HEARTBEAT))
updated

2023-07-03 06:38 UTC, jennyjames21 commented
trigger uts

2023-07-04 03:21 UTC, raghuAtWings submitted a review, later dismissed

2023-07-12 18:18 UTC, jennyjames21 commented
trigger uts

2023-07-12 21:38 UTC, raghuAtWings approved these changes

2023-07-12 22:47 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +  public List<Delegate> getAllDelegatesFromRedisCache() {
This function is not used. remove ?

2023-07-12 22:50 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +  public boolean isDelegateHeartBeatUpToDate(String delegateId, String accountId, long maxExpiry) {
looks like this function is not used. remove ?

2023-07-12 22:58 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    return delegateHeartBeat >= (currentTimeMillis() - HEARTBEAT_EXPIRY_TIME_FIVE_MINS.toMillis());
do you know what's the difference of "HEARTBEAT_EXPIRY_TIME" Vs. "HEARTBEAT_EXPIRY_TIME_FIVE_MINS"

Looks like the HEARTBEAT_EXPIRY_TIME_FIVE_MINS is used for "active delegate" while the HEARTBEAT_EXPIRY_TIME is used for "connected delegate"
it looks super confusing to me. can we just use the "HEARTBEAT_EXPIRY_TIME"  everywhere ?

2023-07-12 23:00 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    if (enableRedisForDelegateService) {
the enableRedisForDelegateService is already checked inside the isDelegateHeartBeatUpToDate, you can skip the if check here

2023-07-12 23:05 UTC, xingchi-jin commented on 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
> +    Delegate delegate = delegateCache.get(accountId, delegateId);
If cache doesn't have delegate, it will fail the workflow. Should here be true ?

2023-07-12 23:06 UTC, xingchi-jin commented on 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
> +    Delegate delegate = delegateCache.get(accountId, delegateId);
If cache doesn't have delegate, it will fail the workflow. Should here be true ?

2023-07-13 03:16 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +  public boolean isDelegateHeartBeatUpToDate(String delegateId, String accountId, long maxExpiry) {
yes it's used in DelegateDisconnectAlertHelper, AssignDelegateServiceImpl, DelegateSetupServiceImpl , DelegateDao

2023-07-13 03:30 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    return delegateHeartBeat >= (currentTimeMillis() - HEARTBEAT_EXPIRY_TIME_FIVE_MINS.toMillis());
i can change one place for the selector display. Another place we need because I will keep it that way as involves rebalancing PT's . They are all different use cases, I tried to make most places 5 mins but in some cases it's necessary

2023-07-13 03:32 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    if (enableRedisForDelegateService) {
yes its but if not then we need the query below.

2023-07-13 03:52 UTC, jennyjames21 commented on 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
> +    Delegate delegate = delegateCache.get(accountId, delegateId);
add to refresh cache in get()

2023-07-13 03:52 UTC, jennyjames21 commented on 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
> +    Delegate delegate = delegateCache.get(accountId, delegateId);
add to refresh cache in get()

2023-07-13 03:52 UTC, jennyjames21 commented on 400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java
> -    long oldestAcceptableHeartBeat = currentTimeMillis() - MAX_DELEGATE_LONG_LAST_HEARTBEAT;
updated

2023-07-13 03:52 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    return delegateHeartBeat >= (currentTimeMillis() - HEARTBEAT_EXPIRY_TIME_FIVE_MINS.toMillis());
updated

2023-07-13 03:53 UTC, jennyjames21 commented
trigger uts

2023-07-13 08:44 UTC, jennyjames21 commented
trigger uts

2023-07-13 16:46 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
> +  public List<Delegate> getAllDelegatesFromRedisCache() {
i believe this is needed in next check-in, if not I will remove it there.

2023-07-13 19:56 UTC, jennyjames21 commented
trigger uts

2023-07-13 21:36 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +  public boolean isDelegateHeartBeatUpToDate(String delegateId, String accountId, long maxExpiry) {
there are two "isDelegateHeartBeatUpToDate" functions. This one is not used, correct ?

2023-07-13 21:43 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +  public boolean isDelegateHeartBeatUpToDate(String delegateId, String accountId, long maxExpiry) {
removed

2023-07-13 21:43 UTC, jennyjames21 commented
trigger uts

2023-07-13 21:48 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    if (enableRedisForDelegateService) {
Either decide whether delegate is connected from redis or from db.
This code logic is confusing because 
it is doing the following, where the boolean condition enableRedisForDelegateService is checked twice and read from cache also twice.

if (enableRedisForDelegateService) {
                        read delegate from redis
     (again) --> if (enableRedisForDelegateService) {
                                 (again) --> read delegate from redis
                                  return -  decide from redis
                         }
   }
}
else { 
 return - decide from db
 }


can you try flatten the logic to be simple

if (enableRedisForDelegateService) {
   read data from cache
   return - decide from cache data
} else  {
  read data from db
  return - decide from db
}

2023-07-13 21:51 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    if (enableRedisForDelegateService) {
why need else statement when we are returning?. IMO it's more cleaner and if else looks more complicated

2023-07-13 21:52 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    if (enableRedisForDelegateService) {
my point if not else.  If you prefer to return in If block and skip the else, it's fine.
could you read my comment again ?

2023-07-13 22:06 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/software/wings/service/impl/DelegateDao.java
> +    if (enableRedisForDelegateService) {
updated

2023-07-13 22:09 UTC, jennyjames21 commented
trigger uts

2023-07-13 22:11 UTC, xingchi-jin approved these changes

2023-07-13 22:40 UTC, jennyjames21 commented
trigger uts

2023-07-13 22:59 UTC, xingchi-jin approved these changes

2023-07-13 23:07 UTC, merged