fix: [PL-39609]: fix for not updating project and org identifiers
harness/harness-core pull request #49620
Opened 2023-06-22 15:27 UTC by bhavya181

## Describe your changes
We are able to update project and org ids, if we are updating existing ids changing their case.
Added a check in update call to not update identifiers in such cases
Tested locally by trying to update existing project id by changing its case 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/49620)

2023-06-23 03:49 UTC, nishantsaini20 requested changes

2023-06-23 03:49 UTC, nishantsaini20 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java
> +      }
Please add UTs for covering the case.

2023-06-23 08:46 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49620)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 280 at r1](https://reviewable.io/reviews/harness/harness-core/49620#gh-1239292001:-NYbQgSZEVZRLE5QNfyb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/08b79b8fd51fc018edea5e61bcd9aa7aec029a3b/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L280)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Please add UTs for covering the case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 19:03 UTC, gn-harness approved these changes

2023-06-26 19:03 UTC, gn-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java
> +  public void testUpdateOrgIdentifier_changingItsCase() {
nit: Test case names generally include three parts

`"<functionUnderTest>_<testSetup>_<expectedBehavior>"`

i.e. update_onlyIdentifierChanged_noOp

2023-06-26 19:03 UTC, gn-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java
> +  public void testUpdateOrgIdentifier_changingItsCase() {
nit:You can consider adding another test

update_identifierAndSomeOtherFieldChanged_onlyOtherFieldIsUpdated

2023-06-27 07:47 UTC, bhavya181 commented on 120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java
> +  public void testUpdateOrgIdentifier_changingItsCase() {
done

2023-06-27 08:14 UTC, ankit-harness reviewed
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49620)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-27 09:10 UTC, bhavya181 commented
trigger uts

2023-06-27 09:45 UTC, bhavya181 commented
trigger messagecheck

2023-06-27 12:33 UTC, nishantsaini20 approved these changes
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49620)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-27 12:33 UTC, nishantsaini20 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49620)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-27 12:33 UTC, merged