feat: [CDS-72709]: Add support for variables in step group
harness/harness-core pull request #49646
Opened 2023-06-23 06:12 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-26 04:27 UTC, shalini-agr commented
trigger uts

2023-06-26 05:05 UTC, shalini-agr commented
trigger uts

2023-06-26 05:27 UTC, shalini-agr commented
trigger uts

2023-06-26 07:21 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/common/steps/stepgroup/StepGroupStepParameters.java` line 72 at r5](https://reviewable.io/reviews/harness/harness-core/49646#-NYqZvl1Cc1NWWNtf6rZ:-NYqZvl1Cc1NWWNtf6r_:bb0j5jg) ([raw file](https://github.com/harness/harness-core/blob/1fc5ff1f19b2a38abd15dc28320413a33780aac6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/common/steps/stepgroup/StepGroupStepParameters.java#L72)):*
> ```Java
>   }
> 
>   public static void validateVariables(List<NGVariable> variables) {
> ```

Can we move this function to a util and use it everywhere, rather than duplicating it?


<!-- Sent from Reviewable.io -->

2023-06-26 07:21 UTC, sahilhindwani-harness requested changes
> Reviewed 3 of 11 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-26 07:49 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/common/steps/stepgroup/StepGroupStepParameters.java` line 72 at r5](https://reviewable.io/reviews/harness/harness-core/49646#-NYqZvl1Cc1NWWNtf6rZ:-NYqfL-g04NC1Q7wq42K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fc5ff1f19b2a38abd15dc28320413a33780aac6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/common/steps/stepgroup/StepGroupStepParameters.java#L72)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we move this function to a util and use it everywhere, rather than duplicating it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 08:01 UTC, shalini-agr commented
trigger uts

2023-06-26 08:36 UTC, sahilhindwani-harness approved these changes
> Reviewed 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-26 09:41 UTC, shalini-agr commented
trigger ut2, ut5, ut8

2023-06-26 10:38 UTC, yogesh-chauhan commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/CommonPlanCreatorUtils.java
> +        } else {
can we check instance of here also ? Tomorrow if we add a new type of variable, this will start throwing class cast exception

2023-06-26 10:40 UTC, shalini-agr commented
trigger review

2023-06-26 10:45 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 14 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/CommonPlanCreatorUtils.java` line 65 at r7](https://reviewable.io/reviews/harness/harness-core/49646#gh-1241970444:-NYrHr500pPhdsHdsZ8h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/669806c5cccf6926fe74b868793b72d6caaa9bf5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/CommonPlanCreatorUtils.java#L65)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we check instance of here also ? Tomorrow if we add a new type of variable, this will start throwing class cast exception
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 10:59 UTC, shalini-agr commented
trigger uts

2023-06-26 11:43 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 14 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-26 17:49 UTC, brijeshdhakar requested changes
> Reviewed 2 of 11 files at r1, 6 of 6 files at r2, 1 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StepGroupVariableCreator.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/49646#-NYsnup55paeDzFbJ8Mb:-NYsnup7CEryiVUBlICu:b-hke5ug) ([raw file](https://github.com/harness/harness-core/blob/e9a61287604e2518fde3a5e4cea8c383fb8ad717/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StepGroupVariableCreator.java#L65)):*
> ```Java
> 
>   @Override
>   public VariableCreationResponse createVariablesForParentNodeV2(
> ```

We have the same method in `io.harness.pms.sdk.core.pipeline.variables.StepGroupVariableCreator`. Logic should be same of these two as both are for StepGroup node.
can we extract the common logic out to some helper? This will reduce the code duplication and if we need to add something then don't have to maintain at both places.


<!-- Sent from Reviewable.io -->

2023-06-27 03:53 UTC, shalini-agr commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StepGroupVariableCreator.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/49646#-NYsnup55paeDzFbJ8Mb:-NYuycqpD3wiZXcJhEe6:bb547l1) ([raw file](https://github.com/harness/harness-core/blob/e9a61287604e2518fde3a5e4cea8c383fb8ad717/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StepGroupVariableCreator.java#L65)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We have the same method in `io.harness.pms.sdk.core.pipeline.variables.StepGroupVariableCreator`. Logic should be same of these two as both are for StepGroup node.
can we extract the common logic out to some helper? This will reduce the code duplication and if we need to add something then don't have to maintain at both places.
</blockquote></details>

The methods in both classes are exactly the same. So, can we remove the step group variable creator from CD and just use the one from SDK? We also have an Execution variable creator residing in SDK shared among all the services.
CC: @yogesh-chauhan 


<!-- Sent from Reviewable.io -->

2023-06-27 05:43 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StepGroupVariableCreator.java` line 65 at r8](https://reviewable.io/reviews/harness/harness-core/49646#-NYsnup55paeDzFbJ8Mb:-NYvN3G2-wj1-HDF-jvM:beglsq) ([raw file](https://github.com/harness/harness-core/blob/e9a61287604e2518fde3a5e4cea8c383fb8ad717/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/StepGroupVariableCreator.java#L65)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

The methods in both classes are exactly the same. So, can we remove the step group variable creator from CD and just use the one from SDK? We also have an Execution variable creator residing in SDK shared among all the services.
CC: @yogesh-chauhan 
</blockquote></details>

discussed with yogesh, since the code is exactly same, we can remove variable creator from cd and use from sdk.
Done.


<!-- Sent from Reviewable.io -->

2023-06-27 05:44 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 11 files at r1, 1 of 3 files at r6, 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-27 05:49 UTC, shalini-agr commented
trigger uts

2023-06-27 06:14 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: 1 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-27 06:15 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 11 files at r1, 5 of 6 files at r2, 2 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-06-27 06:15 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49646)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-06-27 06:15 UTC, shalini-agr commented
trigger review

2023-06-27 06:32 UTC, merged