feat: [CDS-70210]: Added ManifestConfiguration object in service yaml.
harness/harness-core pull request #49644
Opened 2023-06-23 05:59 UTC by GoelPratyush99

## Describe your changes
Updated service yaml

> serviceDefinition:
    type: Kubernetes
    spec:
      manifestsConfig:
        primaryManifestRef: <+input>
      manifests:
        - manifest:

<img width="841" alt="Screenshot 2023-06-23 at 10 37 33 AM" src="https://github.com/harness/harness-core/assets/97931011/46c33ce2-844a-49a7-99b5-29b18d30c639">
<img width="948" alt="Screenshot 2023-06-23 at 10 37 43 AM" src="https://github.com/harness/harness-core/assets/97931011/51216403-2141-45c4-a725-9c0d8140750a">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-23 06:12 UTC, GoelPratyush99 commented
trigger uts

2023-06-23 07:48 UTC, GoelPratyush99 commented
trigger ss

2023-06-23 07:48 UTC, GoelPratyush99 commented
trigger ut3, yt9

2023-06-23 11:13 UTC, acasian-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifestConfigs/ManifestConfigurations.java
> +@TypeAlias("ManifestConfigurations")
i think it was asked already, is it `manifestConfigurations` or `manifestConfiguration`?

2023-06-23 11:13 UTC, acasian-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/KubernetesServiceSpec.java
> +  ManifestConfigurations manifestConfigurations;
do we have any UTs covering the specs?

2023-06-23 11:47 UTC, GoelPratyush99 commented
trigger uts

2023-06-23 13:24 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/KubernetesServiceSpec.java
> +  ManifestConfigurations manifestConfigurations;
No we do not have it for specs

2023-06-23 14:59 UTC, GoelPratyush99 commented
trigger uts

2023-06-23 15:11 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifestConfigs/ManifestConfigurations.java
> +@TypeAlias("ManifestConfigurations")
Yes got confirmation for rohan. We are going ahead with ManifestConfigurations

2023-06-23 18:04 UTC, GoelPratyush99 commented
trigger review

2023-06-26 07:18 UTC, GoelPratyush99 commented
trigger uts

2023-06-26 08:19 UTC, acasian-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/KubernetesServiceSpec.java
> +  ManifestConfigurations manifestConfigurations;
@abosii-harness shall we consider UT's for specs also?

2023-06-26 09:49 UTC, TarunUba1 commented
For safety purpose, did you test the normal flow? and also were you able to get these variables in stepElementParameters?

2023-06-26 09:51 UTC, abosii-harness requested changes

2023-06-26 09:51 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/KubernetesServiceSpec.java
> +    children.add("manifestConfigurations", manifestConfigurations);
Should we add null check?

2023-06-26 09:51 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/KubernetesServiceSpec.java
> +  ManifestConfigurations manifestConfigurations;
I guess there is no point for this

2023-06-26 09:51 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/NativeHelmServiceSpec.java
> +    children.add("manifestConfigurations", manifestConfigurations);
Should we add null check?

2023-06-26 14:08 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/KubernetesServiceSpec.java
> +    children.add("manifestConfigurations", manifestConfigurations);
I think its fine. We do not add it to artifacts field (non - mandatory)

2023-06-26 14:08 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/NativeHelmServiceSpec.java
> +    children.add("manifestConfigurations", manifestConfigurations);
I think its fine. We do not add it to artifacts field (non - mandatory)

2023-06-26 14:31 UTC, GoelPratyush99 reviewed
Yes, I had test it on normal flow it worked fine. In stepElementParameters we will not see this field as manifestConfiguration is not manifest spec.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49644#-:-NYs1nQg9tXV1pbGi5So:b-trr9kp)* status: 7 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-27 07:43 UTC, abosii-harness approved these changes

2023-06-27 08:46 UTC, TarunUba1 submitted a review, later dismissed

2023-06-28 04:05 UTC, GoelPratyush99 commented
trigger uts

2023-06-28 07:33 UTC, abosii-harness approved these changes

2023-06-28 07:54 UTC, TarunUba1 approved these changes

2023-06-28 10:38 UTC, yogesh-chauhan approved these changes
> Reviewed 5 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49644)* status: 7 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-28 10:39 UTC, yogesh-chauhan commented
trigger review

2023-06-28 10:39 UTC, GoelPratyush99 commented
trigger review

2023-06-28 10:41 UTC, merged