feat:[CDS-69791]: Serverless Deploy Step Changes
harness/harness-core pull request #49654
Opened 2023-06-23 08:18 UTC by piyush-bhuwalka

## Describe your changes

This PR includes

- Serverless Deploy Step Changes
- Serverless Deploy Plugin Info Provider Changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-23 08:22 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 1433 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbL4it7zONCsAGVEm1:-NYbL4it7zONCsAGVEm2:b-moflai) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L1433)):*
> ```Java
>                                                .setType(StepSpecTypeConstants.SERVERLESS_AWS_LAMBDA_DEPLOY_V2)
>                                                .setStepMetaData(StepMetaData.newBuilder()
>                                                                     .addCategory("SERVERLESS_AWS_LAMBDA_DEPLOY_V2")
> ```

please add Plugin category here, similar to sam.


<!-- Sent from Reviewable.io -->

2023-06-23 08:23 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLGJiC2qSU2j6twqA:-NYbLGJiC2qSU2j6twqB:b-4n6b5z) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java#L48)):*
> ```Java
>   protected StepParameters getStepParameters(PlanCreationContext ctx, ServerlessAwsLambdaDeployV2StepNode stepNode) {
>     final StepParameters stepParameters = super.getStepParameters(ctx, stepNode);
>     String packageStepFqn = getExecutionStepFqn(ctx.getCurrentField(), SERVERLESS_AWS_LAMBDA_PACKAGE_V2);
> ```

Do we have only one package step fqn that can be configured in the step group?


<!-- Sent from Reviewable.io -->

2023-06-23 08:24 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLWTi54kqmGhBkSw2:-NYbLWTi54kqmGhBkSw3:b-msjwn9) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L91)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> public class ServerlessAwsLambdaDeployV2PluginInfoProvider implements CDPluginInfoProvider {
> ```

nit: Please add a todo to merge this with the SamPluginInfoProvider and also create a ticket for this.


<!-- Sent from Reviewable.io -->

2023-06-23 08:25 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLjcM5T4qpAx8XVil:-NYbLjcM5T4qpAx8XVim:bv4dqad) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L215)):*
> ```Java
>         ambiance, RefObjectUtils.getOutcomeRefObject(OutcomeExpressionConstants.INFRASTRUCTURE_OUTCOME));
>     ServerlessAwsLambdaInfraConfig serverlessAwsLambdaInfraConfig =
>         (ServerlessAwsLambdaInfraConfig) getServerlessInfraConfig(infrastructureOutcome, ambiance);
> ```

This code is nearly same for aws sam except the type of infra, can we abstract it out?


<!-- Sent from Reviewable.io -->

2023-06-23 08:27 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 309 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMHWP1iyPW3WrKp_A:-NYbMHWQ7dlVZ3vWsoLI:b-y368pr) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L309)):*
> ```Java
>     }
>     return folderPaths;
>     // todo: add error handling
> ```

nit: remove if not required.


<!-- Sent from Reviewable.io -->

2023-06-23 08:28 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 347 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMRc98h312C2pNGRp:-NYbMRc98h312C2pNGRq:bd4qav3) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L347)):*
> ```Java
>   }
> 
>   public IdentifierRef getIdentifierRef(String awsConnectorRef, NGAccess ngAccess) {
> ```

nit: why do we need this function, can we call the IdentifierRefHelper directly?


<!-- Sent from Reviewable.io -->

2023-06-23 08:28 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 352 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMYwC6molg73z9rDZ:-NYbMYwC6molg73z9rD_:b-ev1j9v) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L352)):*
> ```Java
>   }
> 
>   public NGAccess getNgAccess(Ambiance ambiance) {
> ```

nit: same as above.
We can use the AmbianceUtils.getNgAccess directly.


<!-- Sent from Reviewable.io -->

2023-06-23 08:29 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMffq90lkXGrUOtTo:-NYbMffq90lkXGrUOtTp:b7yu7uf) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L334)):*
> ```Java
> 
>   public ManifestOutcome getServerlessManifestOutcome(@NotEmpty Collection<ManifestOutcome> manifestOutcomes) {
>     List<ManifestOutcome> serverlessManifests =
> ```

should we extract out this function such that it expects manifestsOutcome and the type and then automatically filters the manifests based on type. Something which both aws sam and aws serverless can reuse.


<!-- Sent from Reviewable.io -->

2023-06-23 08:31 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 299 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbN46u3yDeEh9kjLOp:-NYbN46u3yDeEh9kjLOq:b-ba5aa2) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L299)):*
> ```Java
>   }
> 
>   public List<String> getFolderPathsForManifest(GitStoreConfig gitStoreConfig) {
> ```

We already have the same function in ServerlessStepUtils#getFolderPathsForManifest
Can we re-use that?


<!-- Sent from Reviewable.io -->

2023-06-23 08:31 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 294 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbNIIj-HLB6bwP7b43:-NYbNIIj-HLB6bwP7b44:b-p80ssi) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L294)):*
> ```Java
>   }
> 
>   public ServerlessInfraConfig getServerlessInfraConfig(InfrastructureOutcome infrastructure, Ambiance ambiance) {
> ```

Seems like we already have the same function in serverless, can we abstract out common code?


<!-- Sent from Reviewable.io -->

2023-06-23 08:32 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 284 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbNTq04ZwUfbcG3ohc:-NYbNTq04ZwUfbcG3ohd:biojfcd) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L284)):*
> ```Java
>   }
> 
>   public String getConfigOverridePath(ManifestOutcome manifestOutcome) {
> ```

Seems like we already have a function in `ServerlessAwsLambdaStepHelper` , can we reuse that?


<!-- Sent from Reviewable.io -->

2023-06-23 08:34 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbNwVq0SWRlx0zX4fW:-NYbNwVq0SWRlx0zX4fX:bp7geut) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L19)):*
> ```Java
> import java.util.stream.Collectors;
> 
> public class ServerlessV2PluginInfoProviderHelper {
> ```

This can be merged with AwsSamPluginInfoProviderHelper. Please create a ticket and link under this comment and also add a todo.


<!-- Sent from Reviewable.io -->

2023-06-23 08:35 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java` line 740 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbOA9D13RWOXXMS_x7:-NYbOA9EEjyHx8-8z_tA:b-bf3toh) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java#L740)):*
> ```Java
>   }
> 
>   public void putK8sServiceAccountEnvVars(Ambiance ambiance, Map<String, String> samDeployEnvironmentVariablesMap) {
> ```

I believe the same function is in AwsSamStepHelper, please reuse that.


<!-- Sent from Reviewable.io -->

2023-06-23 08:39 UTC, sahilhindwani-harness commented
*[`970-ng-commons/src/main/java/io/harness/entities/EntityType.java` line 614 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbP3QE5NOh57HV0U8t:-NYbP3QE5NOh57HV0U8u:b-jxvbhp) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/970-ng-commons/src/main/java/io/harness/entities/EntityType.java#L614)):*
> ```Java
>   COVERITY(ModuleType.STO, EntityTypeConstants.COVERITY, IdentifierRef.class, EntityYamlRootNames.COVERITY),
>   @JsonProperty(EntityTypeConstants.SERVERLESS_AWS_LAMBDA_DEPLOY_V2)
>   SERVERLESS_AWS_LAMBDA_DEPLOY_V2(ModuleType.CD, EntityTypeConstants.SERVERLESS_AWS_LAMBDA_DEPLOY_V2,
> ```

Please ensure UI changes are also done with this else swagger validation might break.


<!-- Sent from Reviewable.io -->

2023-06-23 08:39 UTC, sahilhindwani-harness requested changes
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49654)* status: 28 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-23 11:47 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 1433 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbL4it7zONCsAGVEm1:-NYc42pi3n0VD3P4JMHT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L1433)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

please add Plugin category here, similar to sam.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-23 11:47 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLGJiC2qSU2j6twqA:-NYc47lu1k3IRMOCb-he:b-vwrox0) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java#L48)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Do we have only one package step fqn that can be configured in the step group?
</blockquote></details>

Yes, there can be only one package step fqn in one step group


<!-- Sent from Reviewable.io -->

2023-06-23 11:48 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLWTi54kqmGhBkSw2:-NYc4HmZDZb2zFyxnjkT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L91)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Please add a todo to merge this with the SamPluginInfoProvider and also create a ticket for this.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-23 11:48 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLjcM5T4qpAx8XVil:-NYc4MFzEZCY1DG3EQcK:b-c9ip9z) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L215)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This code is nearly same for aws sam except the type of infra, can we abstract it out?
</blockquote></details>

will be abstracted out while merging


<!-- Sent from Reviewable.io -->

2023-06-23 11:55 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMffq90lkXGrUOtTo:-NYc5utp5tLZocIRBMmH:b-efksen) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L334)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

should we extract out this function such that it expects manifestsOutcome and the type and then automatically filters the manifests based on type. Something which both aws sam and aws serverless can reuse.
</blockquote></details>

Should be done when we are merging plugin info providers


<!-- Sent from Reviewable.io -->

2023-06-23 12:09 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbNwVq0SWRlx0zX4fW:-NYc9E_tA1SSW-1yx0VL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java#L19)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This can be merged with AwsSamPluginInfoProviderHelper. Please create a ticket and link under this comment and also add a todo.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-23 12:09 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 352 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMYwC6molg73z9rDZ:-NYc9CFq3Bum1GOb_Gsi:b-d6lys) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L352)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: same as above.
We can use the AmbianceUtils.getNgAccess directly.
</blockquote></details>

moving the static methods of another class into seperate methods helps in writing test cases where we can spy out unnecessary logic as necessary. We can improve it when merging all the code together


<!-- Sent from Reviewable.io -->

2023-06-23 12:09 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 347 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMRc98h312C2pNGRp:-NYc8SmT05zqluwoFbet:b-d6lys) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L347)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: why do we need this function, can we call the IdentifierRefHelper directly?
</blockquote></details>

moving the static methods of another class into seperate methods helps in writing test cases where we can spy out unnecessary logic as necessary. We can improve it when merging all the code together


<!-- Sent from Reviewable.io -->

2023-06-23 12:10 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 309 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMHWP1iyPW3WrKp_A:-NYc9K9oEQxNozkLWj0W:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L309)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: remove if not required.
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2023-06-23 12:10 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 299 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbN46u3yDeEh9kjLOp:-NYc9NfL6uUDjgm77ObO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L299)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We already have the same function in ServerlessStepUtils#getFolderPathsForManifest
Can we re-use that?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-23 12:10 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 294 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbNIIj-HLB6bwP7b43:-NYc9TOo74WHAHQUq7fn:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L294)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Seems like we already have the same function in serverless, can we abstract out common code?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-23 12:10 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 284 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbNTq04ZwUfbcG3ohc:-NYc9VWzExbF-_Hcy-5c:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L284)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Seems like we already have a function in `ServerlessAwsLambdaStepHelper` , can we reuse that?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-23 12:11 UTC, piyush-bhuwalka commented
*[`970-ng-commons/src/main/java/io/harness/entities/EntityType.java` line 614 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbP3QE5NOh57HV0U8t:-NYc9YmBAbF4EzktHrd6:bb71kmx) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/970-ng-commons/src/main/java/io/harness/entities/EntityType.java#L614)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please ensure UI changes are also done with this else swagger validation might break.
</blockquote></details>

Okay


<!-- Sent from Reviewable.io -->

2023-06-23 12:11 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java` line 740 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbOA9D13RWOXXMS_x7:-NYc9bPUDj-UhAgefDrq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java#L740)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I believe the same function is in AwsSamStepHelper, please reuse that.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-26 07:25 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLGJiC2qSU2j6twqA:-NYq_eF_1T2aOBXWUDD4:buerel2) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java#L48)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Yes, there can be only one package step fqn in one step group
</blockquote></details>

If yes, can we move away from storing the fqn? Can we publish an outcome at step group level from the aws lambda package fqn with all the details and use it in deploy step


<!-- Sent from Reviewable.io -->

2023-06-26 07:26 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMffq90lkXGrUOtTo:-NYqa-wY5akKcGC7H8HJ:b-a26tpz) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L334)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Should be done when we are merging plugin info providers
</blockquote></details>

Can we create a util now for that? Should be quick in my opinion.


<!-- Sent from Reviewable.io -->

2023-06-26 07:27 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 347 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMRc98h312C2pNGRp:-NYqaOg99L92Tx6z6O-u:b5d5rbd) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L347)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

moving the static methods of another class into seperate methods helps in writing test cases where we can spy out unnecessary logic as necessary. We can improve it when merging all the code together
</blockquote></details>

Just curious, can we not mock the static class itself using powermock and then verify, why is there a need to spy them out?


<!-- Sent from Reviewable.io -->

2023-06-26 07:29 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java` line 740 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbOA9D13RWOXXMS_x7:-NYqakz_7y_ZRXRgzQVj:bh1j0x) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java#L740)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think we have copied it, can we just directly use AwsSamStepHelper here?


<!-- Sent from Reviewable.io -->

2023-06-26 07:30 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/49654#-NYqaz8G4vUbPK29G88I:-NYqaz8G4vUbPK29G88J:b7e983v) ([raw file](https://github.com/harness/harness-core/blob/b9a6874948ba1059b47887742ffd6b23457dd115/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L110)):*
> ```Java
>   public PluginCreationResponseWrapper getPluginInfo(
> 
>       // todo: Merge this with SamPluginInfoProvider
> ```

Please create tickets for all this todo and share in this review.


<!-- Sent from Reviewable.io -->

2023-06-26 07:30 UTC, sahilhindwani-harness requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49654)* status: 28 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-26 10:44 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbLGJiC2qSU2j6twqA:-NYrIY2G1BwSoZry4DGm:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/serverless/ServerlessAwsLambdaDeployV2StepPlanCreator.java#L48)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

If yes, can we move away from storing the fqn? Can we publish an outcome at step group level from the aws lambda package fqn with all the details and use it in deploy step
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2023-06-26 10:45 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 347 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMRc98h312C2pNGRp:-NYrIaRB5UmCRlJsasjB:b-d2k6ow) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L347)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Just curious, can we not mock the static class itself using powermock and then verify, why is there a need to spy them out?
</blockquote></details>

Yes, we can mock the static classes using powermock


<!-- Sent from Reviewable.io -->

2023-06-26 10:46 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java` line 740 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbOA9D13RWOXXMS_x7:-NYrIj2s5Xet0KtnwbPP:b-6lbzpa) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/ServerlessStepCommonHelper.java#L740)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think we have copied it, can we just directly use AwsSamStepHelper here?
</blockquote></details>

No, we have used AwsSamStepHelper. That method in serverless common helper was not used, removed it in the commit 


<!-- Sent from Reviewable.io -->

2023-06-26 10:46 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/49654#-NYbMffq90lkXGrUOtTo:-NYrJ28m5izE7zGVv1bn:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c0f7aeb276fe497af4b8724b035a48bfbb06f605/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L334)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we create a util now for that? Should be quick in my opinion.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-26 10:52 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/49654#-NYqaz8G4vUbPK29G88I:-NYrJVmkDKRHhCKLMFoO:b-ym7mz0) ([raw file](https://github.com/harness/harness-core/blob/b9a6874948ba1059b47887742ffd6b23457dd115/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L110)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please create tickets for all this todo and share in this review.
</blockquote></details>

https://harness.atlassian.net/browse/CDS-72970

https://harness.atlassian.net/browse/CDS-73028


<!-- Sent from Reviewable.io -->

2023-06-26 11:08 UTC, piyush-bhuwalka commented
trigger uts

2023-06-26 11:21 UTC, piyush-bhuwalka commented
trigger uts

2023-06-27 04:04 UTC, piyush-bhuwalka commented
trigger uts

2023-06-27 05:02 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/PluginInfoProviderUtils.java` line 24 at r7](https://reviewable.io/reviews/harness/harness-core/49654#-NYvDZtH63JTaTGgz9lh:-NYvDZtIDg6Xbb38eqEL:b-7zpafd) ([raw file](https://github.com/harness/harness-core/blob/79dd351aa7ad50bd66c0f476b7cc3522d3b9f360/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/PluginInfoProviderUtils.java#L24)):*
> ```Java
> import org.hibernate.validator.constraints.NotEmpty;
> 
> public class PluginInfoProviderUtils {
> ```

should this be a static class?


<!-- Sent from Reviewable.io -->

2023-06-27 05:05 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 325 at r7](https://reviewable.io/reviews/harness/harness-core/49654#-NYvEEiP16qCXdrkqyzC:-NYvEEiQ51M_e9Hw7xBe:b-uwq222) ([raw file](https://github.com/harness/harness-core/blob/79dd351aa7ad50bd66c0f476b7cc3522d3b9f360/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L325)):*
> ```Java
> 
>   // todo: moving this function to a common class with Serverless 1.0
>   public String getConfigOverridePath(ManifestOutcome manifestOutcome) {
> ```

This same function is available in ServerlessAwsLambdaStepHelper, can we reuse that here.


<!-- Sent from Reviewable.io -->

2023-06-27 05:06 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java` line 312 at r7](https://reviewable.io/reviews/harness/harness-core/49654#-NYvEWeZEJZwSdNhgSpA:-NYvEWe_A243tVz64i2m:bf33xrl) ([raw file](https://github.com/harness/harness-core/blob/79dd351aa7ad50bd66c0f476b7cc3522d3b9f360/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessAwsLambdaDeployV2PluginInfoProvider.java#L312)):*
> ```Java
> 
>   // todo: moving this function to a common class with Serverless 1.0
>   public List<String> getFolderPathsForManifest(GitStoreConfig gitStoreConfig) {
> ```

we can use serverlessStepUtils here.


<!-- Sent from Reviewable.io -->

2023-06-27 05:10 UTC, sahilhindwani-harness approved these changes
> Reviewed 4 of 6 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 3 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49654)* status: 34 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-27 05:53 UTC, piyush-bhuwalka commented
trigger uts

2023-06-27 05:59 UTC, piyush-bhuwalka commented
trigger checkstylecodeformat

2023-06-27 06:00 UTC, piyush-bhuwalka commented
trigger uts

2023-06-27 06:33 UTC, piyush-bhuwalka commented
trigger uts

2023-06-27 07:32 UTC, RishabhGupta34 approved these changes

2023-06-27 08:01 UTC, piyush-bhuwalka commented
trigger uts

2023-06-27 08:13 UTC, piyush-bhuwalka commented
trigger ut7

2023-06-27 08:14 UTC, piyush-bhuwalka commented
trigger ut7

2023-06-27 12:20 UTC, piyush-bhuwalka commented
trigger ut0, ut3

2023-06-27 14:20 UTC, merged