fix: [CDS-69071]: changes to send releasename and check resources if
harness/harness-core pull request #49709
Opened 2023-06-26 08:20 UTC by TarunUba1

## Describe your changes
Adding a warning to show that their exist some resources with name same as release and which might affect deployments
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-26 08:40 UTC, TarunUba1 commented
trigger uts

2023-06-26 09:58 UTC, abhinavsingh1196 requested changes

2023-06-26 09:58 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +      if (isNotEmpty(commandRequest.getReleaseName())) {
this logic is same for both helm and k8s handler. we can just put it somewhere else like ManifestHelper and return a boolean to the task handlers. 
Also for K8s, avoid putting this in K8sTaskHelperBase and instead directly in the request handler if possible. It's making the change span across a lot of files and I don't see any helpful reason for having it in applyManifests() method.

if (!useDeclarativeRollback && ManifestHelper.conflictsWithReleaseName(resources, releaseName)) {
  logCallback.print(...)
}

......

boolean conflictsWithReleaseName(List<..> resources, String releaseName) {
  return resources.stream().filter(versionedKinds.contains(resource -> resource.getResourceId().resource.getKind())).anyMatch(resource -> resource.getResourceId().getName());
}

2023-06-26 10:06 UTC, abosii-harness requested changes

2023-06-26 10:06 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +    if (isNotEmpty(releaseName)) {
What if declarative rollback is used, is there any point of showing this warning?
Can we move this logic outside the applyManifests and have it as method called before apply?

2023-06-26 10:06 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +        if ((kubernetesResource.getResourceId().getKind().equals(Secret.name())
maybe instead use stream API?
.map(KubernetesResource::getResourceId)
.filter(id -> isNotNull(id.getKind()))
.filter(kind -> Secret.name().equals(kind) || ConfigMap.name().equals(kind))
... etc

2023-06-26 10:06 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +          executionLogCallback.saveExecutionLog(color(
I guess you can use  executionLogCallback.saveExecutionLog("<msg>", WARN, RUNNING) instead

2023-06-26 12:53 UTC, TarunUba1 commented
trigger uts

2023-06-26 12:56 UTC, abhinavsingh1196 requested changes

2023-06-26 12:56 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public void secretOrConfigMapNameConflictsWithReleaseName(
nit: since we're checking and warning in the same method, method can be named `warnIfReleaseNameConflictsWithSecretOrConfigMap`

2023-06-26 12:56 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +    if (isNotEmpty(releaseName)) {
for k8s deployments, release name would not be received as null or empty, if it does then nothing would work anyway :)
if you do want to keep this check, put a reverse check and return, like

`if (isEmpty(releaseName)) {
  return;
}`

2023-06-26 12:56 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +              .filter(id -> Secret.name().equals(id.getKind()) || ConfigMap.name().equals(id.getKind()))
nit: can use `versionedKinds.contains(id.getKind())` here, will allow you to remove the previous check also since it will handle null/empty cases :)

2023-06-26 12:56 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +              .collect(Collectors.toList());
best to replace this last part with anyMatch()
Instead of `.filter(id -> id.getName().equals(releaseName))
              .collect(Collectors.toList());`

we can do this and return a boolean

`boolean isConflicting = resources..<filters>...anyMatch(id -> releaseName.equals(id.getname()));`
`if (isConflicting) { log.print(...) }`

2023-06-26 12:56 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java
> +            "\nRelease Name conflicts with a Secret/ConfigMap resource. Please make sure that such conflicts are resolved for proper deployments",
nit: extract this message for reuse

2023-06-26 13:26 UTC, TarunUba1 commented
trigger uts

2023-06-26 18:14 UTC, abhinavsingh1196 approved these changes

2023-06-27 04:31 UTC, namantalaycha10 approved these changes

2023-06-27 04:31 UTC, namantalaycha10 commented
trigger review

2023-06-27 05:06 UTC, abosii-harness approved these changes

2023-06-27 06:14 UTC, merged