feat: [CDS-72657]: Adding API to fetch a list of manifest that can be applied as primary
harness/harness-core pull request #49715
Opened 2023-06-26 09:27 UTC by GoelPratyush99

## Describe your changes
Adding API to fetch a list of manifest that can be applied to primaryManifestRef Field.
<img width="1102" alt="Screenshot 2023-06-27 at 7 41 28 PM" src="https://github.com/harness/harness-core/assets/97931011/0022fafd-420b-4a43-b997-aad658810177">

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/49715)

2023-06-26 10:01 UTC, TarunUba1 requested changes

2023-06-26 10:01 UTC, TarunUba1 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +      YamlNode manifest = getManifestNodeYaml(manifestConfig).getNode();
similarly here just check ahead for null and then only fecth getNode, otherwise we will run in null.getNode() which feels weird

2023-06-26 10:54 UTC, abhinavsingh1196 requested changes

2023-06-26 10:54 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
> +  @GET
this needs to be made using spec first approach and not code-first, since it'll be customer facing.
For this PR, you can just merge the underlying logic which gets manifest IDs and create the API layer later.

2023-06-27 14:54 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +      YamlNode manifest = getManifestNodeYaml(manifestConfig).getNode();
Done

2023-06-27 14:55 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +    if (serviceDefinitionField == null) {
Not removing this as for all the null checks we are returning empty ManifestsResponseDTO object.

2023-06-27 15:04 UTC, GoelPratyush99 commented
trigger uts

2023-06-27 16:39 UTC, TarunUba1 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: return a list of eligible primary manifests from all configured manifest in a org-scoped service.
"in an org-scoped service" vowels

2023-06-27 16:39 UTC, TarunUba1 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: return a list of eligible primary manifests from all configured manifest in a account-scoped service.
"in an account-scoped"

2023-06-28 04:12 UTC, GoelPratyush99 commented
trigger uts

2023-06-28 04:12 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: return a list of eligible primary manifests from all configured manifest in a org-scoped service.
done

2023-06-28 04:12 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: return a list of eligible primary manifests from all configured manifest in a account-scoped service.
done

2023-06-28 05:46 UTC, mankrit-singh reviewed
Just some linting comments

2023-06-28 05:46 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +  '/v1/orgs/{org}/projects/{project}/services/{service}/primaryManifests':
primary-manifests

2023-06-28 05:46 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: return a list of eligible primary manifests from all configured manifest in a project-scoped service.
Returns ...

2023-06-28 05:46 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        manifestIdentifierList:
manifest_identifier_list

2023-06-28 06:26 UTC, abhinavsingh1196 requested changes

2023-06-28 06:26 UTC, abhinavsingh1196 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      summary: List primary manifests
can be `List primary manifests of a [project/org/account] scoped service`, and the same for other APIs as well, since this summary is displayed on the left nav IIRC

2023-06-28 06:26 UTC, abhinavsingh1196 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        manifestIdentifierList:
do we even need to say `list`? it could be `manifest_identifiers` or maybe even `identifiers`

2023-06-28 06:26 UTC, abhinavsingh1196 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: ManifestsResponseDTO return with a list of eligibe manifest identifiers that can be applied as primary manifest.
- typo in `eligible`
- would this be a better description?
`ManifestsResponseDTO returns a list of manifest identifiers from a service's eligible primary manifests`

2023-06-28 06:26 UTC, abhinavsingh1196 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +          manifestIdentifierList:
will need modification accordingly

2023-06-28 06:26 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +    Optional<ServiceEntity> serviceEntity = serviceEntityService.get(harnessAccount, org, project, service, false);
nit: should have suffix `Optional`

2023-06-28 06:26 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +    } else {
throw this exception at the start i.e.

if (!serviceEntity.isPresent) { throw ...}
ServiceEntity service = serviceEntityOptional.get();
if (isEmpty(service.getYaml())) {throw ...}
return Response...

2023-06-28 06:26 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +      if (manifest != null) {
can just be `if (manifest != null && supportedManifestTypes.contains(manifest.getType()))`

2023-06-28 06:49 UTC, abhinavsingh1196 requested changes

2023-06-28 06:49 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +  public YamlField getManifestNodeYaml(YamlNode manifestNode) {
this can be private? and would be best to move it under the following method

2023-06-28 06:49 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
> +  public void testGetManifestIdentifiersListServiceV2() {
This test should be split into 3 tests.

2023-06-28 06:49 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
> +  public void testGetManifestIdentifiersListServiceV2() {
Would it be better to mock ServiceFilterHelper for unit tests of ServiceEntityServiceImpl and have separate unit tests for ServiceFilterHelper? 
In any case, we should add tests for more negative scenarios for k8s/helm.

2023-06-28 07:04 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        manifestIdentifierList:
manifest_identifiers sounds good

2023-06-28 08:44 UTC, GoelPratyush99 commented
trigger uts

2023-06-28 08:45 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
> +  public void testGetManifestIdentifiersListServiceV2() {
Done

2023-06-28 08:45 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
> +  public void testGetManifestIdentifiersListServiceV2() {
Done

2023-06-28 08:49 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +  public YamlField getManifestNodeYaml(YamlNode manifestNode) {
Done

2023-06-28 08:50 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +      if (manifest != null) {
Done

2023-06-28 08:50 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +    } else {
Done

2023-06-28 08:50 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +    Optional<ServiceEntity> serviceEntity = serviceEntityService.get(harnessAccount, org, project, service, false);
Done

2023-06-28 08:50 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +          manifestIdentifierList:
Done

2023-06-28 08:50 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: ManifestsResponseDTO return with a list of eligibe manifest identifiers that can be applied as primary manifest.
changed it

2023-06-28 08:50 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      summary: List primary manifests
Done

2023-06-28 08:51 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        manifestIdentifierList:
changed it to identifiers

2023-06-28 08:51 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      description: return a list of eligible primary manifests from all configured manifest in a project-scoped service.
Done

2023-06-28 08:51 UTC, GoelPratyush99 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +  '/v1/orgs/{org}/projects/{project}/services/{service}/primaryManifests':
Done

2023-06-28 08:51 UTC, GoelPratyush99 commented
trigger uts

2023-06-28 10:43 UTC, GoelPratyush99 commented
trigger uts

2023-06-28 11:14 UTC, abhinavsingh1196 approved these changes

2023-06-28 16:29 UTC, GoelPratyush99 commented
trigger ut5

2023-06-29 05:40 UTC, mankrit-singh submitted a review, later dismissed

2023-06-29 05:47 UTC, GoelPratyush99 commented
trigger uts

2023-06-29 08:28 UTC, abhinavsingh1196 approved these changes
Please consider automation tests for this API in the test plan.

2023-06-29 09:15 UTC, TarunUba1 approved these changes

2023-06-29 10:16 UTC, tchaurasiya approved these changes

2023-06-29 10:26 UTC, mankrit-singh approved these changes

2023-06-29 10:27 UTC, abosii-harness approved these changes

2023-06-29 10:43 UTC, GoelPratyush99 commented
trigger review

2023-06-29 10:46 UTC, merged