fix: [CDS-71719]: ECR Regex
harness/harness-core pull request #49721
Opened 2023-06-26 10:07 UTC by sarthakkasat

## Describe your changes
For ECR Artifact, we are currently modifying the regex, if the modified regex does not match any build we will try to match it with original regex.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-27 12:30 UTC, yogesh-chauhan approved these changes

2023-06-27 15:28 UTC, puthrayaharness requested changes

2023-06-27 15:28 UTC, puthrayaharness commented on 960-api-services/src/main/java/software/wings/helpers/ext/ecr/EcrServiceImpl.java
>      if (buildsResponse.isEmpty()) {
Please use `EmptyPredicate.isEmpty` instead of isEmpty.

Please see if we can simplify the code using the following - 
https://harness.slack.com/archives/C8DHL8G8P/p1687805842187559

2023-06-27 15:30 UTC, puthrayaharness requested changes

2023-06-27 15:45 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49721)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/software/wings/helpers/ext/ecr/EcrServiceImpl.java` line 211 at r1](https://reviewable.io/reviews/harness/harness-core/49721#gh-1243947721:-NYxWijAC7RUSTFy5A9R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c6bf38f6d028f32bcb65927d611bf3164c42d030/960-api-services/src/main/java/software/wings/helpers/ext/ecr/EcrServiceImpl.java#L211)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please use `EmptyPredicate.isEmpty` instead of isEmpty.

Please see if we can simplify the code using the following - 
https://harness.slack.com/archives/C8DHL8G8P/p1687805842187559
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/software/wings/helpers/ext/ecr/EcrServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/49721#gh-1243949894:-NYxWp6S8R6E96GzNdi6:b-rjzmox) ([raw file](https://github.com/harness/harness-core/blob/c6bf38f6d028f32bcb65927d611bf3164c42d030/960-api-services/src/main/java/software/wings/helpers/ext/ecr/EcrServiceImpl.java#L213)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please add some detaila and link the ticket in the comment so that we can trace back why this is being done.
</blockquote></details>

For ECR Artifact, we are currently modifying the regex, if the modified regex does not match any build we will try to match it with original regex.
https://harness.atlassian.net/browse/CDS-72589
I have also added the same in PR description


<!-- Sent from Reviewable.io -->

2023-06-27 19:48 UTC, puthrayaharness requested changes
Please add a comment in the code linking the ticket and add a simple explanation. It makes it easier when we go over the code in the future as to why we have multiple regex checks.

2023-06-27 21:24 UTC, sarthakkasat reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49721#-:-NYyjS20-GZhCL5GUHNG:bb6un1j)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-06-28 08:43 UTC, yogesh-chauhan approved these changes

2023-06-28 08:47 UTC, tchaurasiya approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49721)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-28 08:48 UTC, sarthakkasat commented
trigger uts

2023-06-28 09:10 UTC, puthrayaharness approved these changes

2023-06-28 09:19 UTC, sarthakkasat commented
trigger review

2023-06-28 09:22 UTC, merged