fix: [PL:38735]: NG reset password emails to go through NG
harness/harness-core pull request #49758
Opened 2023-06-26 17:00 UTC by sahibaCCM

## Describe your changes
 NG reset password emails to go through NG
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-30 07:45 UTC, sahibaCCM commented
trigger messagecheck

2023-06-30 07:46 UTC, sahibaCCM commented
trigger uts

2023-06-30 10:11 UTC, sahibaCCM commented
trigger uts

2023-07-03 06:54 UTC, sahibaCCM commented
trigger uts

2023-07-03 07:08 UTC, sahibaCCM commented
trigger uts

2023-07-03 18:13 UTC, sahibaCCM commented
trigger uts

2023-07-04 06:31 UTC, rijajoo commented
UTs are failing.

2023-07-05 05:10 UTC, sahibaCCM commented
trigger ut0

2023-07-05 06:43 UTC, sahibaCCM commented
trigger uts

2023-07-05 10:33 UTC, rijajoo requested changes

2023-07-05 10:33 UTC, rijajoo commented on dockerization/manager/scripts/replace_configs.sh
> +replace_key_value notificationClient.messageBroker.uri "${NOTIFICATION_MONGO_URI//\\&/&}"
Is this a typo?

2023-07-05 10:33 UTC, rijajoo commented on 220-graphql-test/src/supporter-test/java/io/harness/rule/GraphQLRule.java
> +    MarketPlaceConfig marketPlaceConfig =
What's this block of code needed for?

2023-07-05 11:42 UTC, sahibaCCM commented on 220-graphql-test/src/supporter-test/java/io/harness/rule/GraphQLRule.java
> +    MarketPlaceConfig marketPlaceConfig =
the tests where failing due to missing configurations, due to the changes that where brought in by removing SpringPersistenceTestModule.

2023-07-05 11:48 UTC, rijajoo approved these changes

2023-07-05 11:55 UTC, merged