fix: [CDS-41001]: removing hard coded timeouts
harness/harness-core pull request #49807
Opened 2023-06-27 11:46 UTC by TarunUba1

## Describe your changes
Adding timeout logic in case of rollback step as well.
Removing timeout variable uses when the helmCommandData contains timeout values
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-27 12:04 UTC, TarunUba1 commented
trigger uts

2023-06-27 14:11 UTC, abhinavsingh1196 requested changes

2023-06-27 14:11 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
Doesn't this tie the step timeout with the helm command line timeout? I'm not sure if that's a good thing.

2023-06-27 14:12 UTC, abhinavsingh1196 commented
Please write a more detailed description on why we're doing this.

2023-06-27 16:04 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
> +        helmCommandData.getTimeOutInMillis());
Can we check if the timeout is provided or not? i.e. helmCommandData.getTimeOutInMillis() != null ? helmCommandData.getTimeOutInMillis()  : DEFAULT_HELM_COMMAND_TIMEOUT?

2023-06-27 16:06 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
> +          NGTimeConversionHelper.convertTimeStringToMilliseconds(stepParameters.getTimeout().getValue()));
Isn't stepParameters.getTimeout() returns a string, for example 10m? How you convert this to millis? you need to use StepUtils.getTimeoutMillis

2023-06-27 16:10 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
well actually, we are not even using timeout when executing command. So its doesnt affect in either case

2023-06-27 16:45 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
> +        helmCommandData.getTimeOutInMillis());
I have done the changes in cases of those functions only where HelmCommandData is extracted from Request which is of type either Install or Rollback, So in these cases we will always have timeout as it is set as default as well if not set.

2023-06-27 16:57 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
Will remove the logic itself for timeout as it was not even used

2023-06-27 16:58 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
> +          NGTimeConversionHelper.convertTimeStringToMilliseconds(stepParameters.getTimeout().getValue()));
yeah what getTimeoutInMillis does this code is doing the same

2023-06-27 17:42 UTC, TarunUba1 commented
trigger uts

2023-06-27 17:45 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
> +          NGTimeConversionHelper.convertTimeStringToMilliseconds(stepParameters.getTimeout().getValue()));
null check?

2023-06-28 04:23 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
> -import static io.harness.helm.HelmConstants.DEFAULT_HELM_COMMAND_TIMEOUT;
We can remove DEFAULT_HELM_COMMAND_TIMEOUT from Helm Constants if not used anywhere else

2023-06-28 04:36 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
> -import static io.harness.helm.HelmConstants.DEFAULT_HELM_COMMAND_TIMEOUT;
I got conscious about the constant, maybe in future someone needs it then kindoff, feels like yes we can.

2023-06-28 04:40 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
> +        helmCommandData.getTimeOutInMillis());
Still, best not to assume and keep a check

2023-06-28 04:51 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
> -import static io.harness.helm.HelmConstants.DEFAULT_HELM_COMMAND_TIMEOUT;
done

2023-06-28 04:52 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java
Got it, I see the timeout itself was removed because a customer was hitting the 30 minute limit and wanted to provide their own timeout.
https://github.com/harness/harness-core/pull/39688

2023-06-28 04:55 UTC, TarunUba1 commented
trigger uts

2023-06-28 07:33 UTC, abosii-harness approved these changes

2023-06-28 07:33 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
> +          NGTimeConversionHelper.convertTimeStringToMilliseconds(stepParameters.getTimeout().getValue()));
Just use StepUtils.getTimeoutMillis

2023-06-28 07:44 UTC, abhinavsingh1196 submitted a review, later dismissed

2023-06-28 08:55 UTC, TarunUba1 commented
trigger uts

2023-06-28 09:10 UTC, namantalaycha10 approved these changes

2023-06-28 09:29 UTC, TarunUba1 commented
trigger review

2023-06-28 09:31 UTC, merged