[fix]: [CDS-73150]: adding support for artifactory artifact name regex
harness/harness-core pull request #49820
Opened 2023-06-27 16:32 UTC by markoharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-27 16:44 UTC, markoharness commented
trigger uts

2023-06-27 16:51 UTC, markoharness commented
trigger uts

2023-06-28 16:12 UTC, markoharness commented
trigger uts

2023-06-29 09:11 UTC, markoharness commented
trigger uts

2023-07-03 07:56 UTC, markoharness commented
trigger uts

2023-07-03 08:13 UTC, markoharness commented
trigger uts

2023-07-03 09:17 UTC, markoharness commented
trigger uts

2023-07-03 10:28 UTC, yogesh-chauhan commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java
> +    List<BuildDetails> buildDetails = null;
is it safer to initialise this as empty list ?

2023-07-03 10:28 UTC, yogesh-chauhan commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java
> +    String filePath = Paths.get(artifactDirectory, ARTIFACT_PATH_FILTER_SEARCH_WILDCARD_TERM).toString();
here the filePath is a regex as it contains *
Does this mean we can pass a regex to artifactoryClient. If that is the case, can we not directly pass the artifactPathFilter to this artifactoryClient API

2023-07-03 10:28 UTC, yogesh-chauhan commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java
> +          return matcher.matches();
is it similar to doing

("^" + directory + artifactPathRegexPattern).matcher(bd.getArtifactPath()).matches() ?
basically prepend the directory in the regex and just do a regex match against the artifact path received from the getBuilds()

2023-07-03 10:46 UTC, markoharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java
> +    String filePath = Paths.get(artifactDirectory, ARTIFACT_PATH_FILTER_SEARCH_WILDCARD_TERM).toString();
No. 
Artifactory does not support regex for their search. Hence we pass the artifactory supported wildcard which is char *
Once we get the results we do regex matching on our own.

2023-07-03 10:46 UTC, markoharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java
> +          return matcher.matches();
Artifactory does not support regex for their search. Hence we pass the artifactory supported wildcard which is char *
Once we get the results we do regex matching on our own which is done in this part of code.

2023-07-03 10:49 UTC, markoharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java
> +    List<BuildDetails> buildDetails = null;
It does not matter in this case as one of two things will happen.
1. buildDetails will be created if all conditions are met (either with elements or empty)
2. Exception will be throw if conditions are not met.

Either way we do not have to initialize buildDetails at this moment in time.

2023-07-03 13:43 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49820)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-04 12:02 UTC, sarthakkasat commented
trigger review

2023-07-04 13:30 UTC, puthrayaharness requested changes

2023-07-04 13:34 UTC, puthrayaharness requested changes

2023-07-04 13:34 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java
> +    List<BuildDetails> buildDetailsFiltered = buildDetails.stream()
Also, since we are filtering exact matches how does sorting help here?

2023-07-04 13:51 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49820)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-04 13:57 UTC, markoharness commented
trigger uts

2023-07-04 13:58 UTC, puthrayaharness approved these changes

2023-07-04 13:59 UTC, markoharness commented
trigger review

2023-07-04 14:22 UTC, merged