feat: [CODE-550]: trigger webhook harness scm
harness/harness-core pull request #49868
Opened 2023-06-28 11:56 UTC by abhinav-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-28 11:59 UTC, abhinav-harness commented
trigger uts

2023-06-28 16:11 UTC, abhinav-harness commented
trigger uts

2023-06-28 20:08 UTC, abhinav-harness commented
trigger uts

2023-06-28 20:24 UTC, abhinav-harness commented
trigger uts

2023-06-28 20:25 UTC, abhinav-harness commented
trigger uts

2023-06-29 06:47 UTC, abhinav-harness commented
trigger uts

2023-06-29 08:32 UTC, abhinav-harness commented
trigger uts

2023-06-29 20:50 UTC, abhinav-harness commented
trigger uts

2023-06-29 21:05 UTC, abhinav-harness commented
trigger uts

2023-06-29 22:04 UTC, vcalasansh approved these changes
> Reviewed 6 of 13 files at r1, 4 of 5 files at r3, 4 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49868)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-06-29 22:57 UTC, abhinav-harness commented
trigger ut9

2023-06-30 05:24 UTC, rathodmeetsatish requested changes

2023-06-30 05:24 UTC, rathodmeetsatish commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +  private void checkForAccessForHarnessScm(NGTriggerEntity ngTriggerEntity) {
Add unit test

2023-06-30 05:24 UTC, rathodmeetsatish commented on 120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/HarnessSCMWebhookServiceImpl.java
> +    // Using service principal
add unit tests

2023-06-30 08:50 UTC, abhinav-harness commented on 120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/HarnessSCMWebhookServiceImpl.java
> +    // Using service principal
added in followup

2023-06-30 08:50 UTC, abhinav-harness commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +  private void checkForAccessForHarnessScm(NGTriggerEntity ngTriggerEntity) {
added in followup

2023-06-30 08:52 UTC, abhinav-harness commented
trigger messagecheck

2023-06-30 08:55 UTC, rathodmeetsatish approved these changes

2023-06-30 09:18 UTC, mohitg0795 approved these changes

2023-06-30 09:18 UTC, adivishy1 approved these changes
> Reviewed 6 of 13 files at r1, 4 of 5 files at r3, 4 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49868)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-06-30 09:19 UTC, merged