feat: [CDS-68853]: add commitIds of rettaform resources to step output
harness/harness-core pull request #49910
Opened 2023-06-29 08:41 UTC by tmacari-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-29 08:45 UTC, tmacari-harness commented
trigger uts

2023-06-29 19:58 UTC, tmacari-harness commented
trigger uts

2023-06-29 20:24 UTC, tmacari-harness commented
trigger feature-build

2023-06-30 06:19 UTC, tmacari-harness commented
trigger uts

2023-06-30 06:20 UTC, tmacari-harness commented
trigger feature-build

2023-06-30 07:16 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java
> +    } else if (parameters.getConfiguration().getType().getDisplayName().equalsIgnoreCase(
Do we need this else if statement when it's INHERIT_FROM_PLAN?

2023-06-30 07:16 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStepV2.java
> +        .varFileInfos(helper.prepareTerraformVarFileInfo(terraformConfig.getVarFileConfigs(), ambiance, true))
was it checked when destroy inherits from apply? will we have the original Identifier?

2023-06-30 07:29 UTC, tmacari-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStepV2.java
> +        .varFileInfos(helper.prepareTerraformVarFileInfo(terraformConfig.getVarFileConfigs(), ambiance, true))
Yes

2023-06-30 07:29 UTC, tmacari-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java
> +    } else if (parameters.getConfiguration().getType().getDisplayName().equalsIgnoreCase(
Yes, in that case we wont display commit ids for var files

2023-06-30 07:45 UTC, tmacari-harness commented
trigger uts

2023-06-30 10:47 UTC, puthrayaharness requested changes

2023-06-30 10:47 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java
> +          .stepOutcome(StepResponse.StepOutcome.builder()
Duplicate in builder. Please have only one stepOutcome

2023-06-30 10:58 UTC, vlica-harness approved these changes

2023-06-30 13:28 UTC, tmacari-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java
> +          .stepOutcome(StepResponse.StepOutcome.builder()
it supports multiple:
"@Wither @Singular Collection<StepOutcome> stepOutcomes;"

2023-06-30 13:31 UTC, puthrayaharness approved these changes

2023-06-30 13:32 UTC, tmacari-harness commented
trigger review

2023-06-30 13:36 UTC, tmacari-harness commented
trigger review

2023-06-30 13:39 UTC, merged