fix: [CDS-72250]: fixing file references in command and shell script provision step
harness/harness-core pull request #49938
Opened 2023-06-29 12:35 UTC by sourabh-awashti

## Describe your changes
File references was not being shown for file store when files are getting referenced in these steps
Implemented with file ref for these steps to extract file reference and added support for handling file reference in json creator.

Tests Done:
1. Adding files in command step and shell script provisioner step and getting reference in file store

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-03 10:40 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSStepFilterJsonCreatorV2.java
> +            fileDTO = fileStoreService.getByPath(fileReference.getAccountIdentifier(), fileReference.getOrgIdentifier(),
TEST

2023-07-03 10:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStepInfo.java
> +        fileRefs.addAll(fileRef);
commandUnits.identifier...

2023-07-03 10:55 UTC, yogesh-chauhan reviewed
Resolving some of the comments as discussed internally

2023-07-03 12:31 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSStepFilterJsonCreatorV2.java
>  public class CDPMSStepFilterJsonCreatorV2 extends GenericStepPMSFilterJsonCreatorV2 {
done

2023-07-03 12:31 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSStepFilterJsonCreatorV2.java
> +      addFileReferredEntities(filterCreationContext, result, fileRefs);
done

2023-07-03 19:00 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStepInfo.java` line 104 at r4](https://reviewable.io/reviews/harness/harness-core/49938#-NZS6voT5-_agVkbmCpU:-NZS6voT5-_agVkbmCpV:b-co96cx) ([raw file](https://github.com/harness/harness-core/blob/7cce0824b219e7bc968234eb8136d1e1f36a3129/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStepInfo.java#L104)):*
> ```Java
>       });
>     }
>     fileRefMap.put("commandUnits.identifier.spec.source.spec.file", ParameterField.createValueField(fileRefs));
> ```

I meant this can be the commandUnitIdentifier
String.format("commandUnits.%s.spec.source.spec.file", commandUnit.identifier)


<!-- Sent from Reviewable.io -->

2023-07-03 19:01 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49938)* status: 7 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-04 06:52 UTC, sourabh-awashti commented
trigger uts

2023-07-04 07:02 UTC, sourabh-awashti commented
trigger uts

2023-07-04 07:10 UTC, sourabh-awashti commented
trigger uts

2023-07-04 10:21 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 5 files at r1, 3 of 6 files at r5, 1 of 1 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49938)* status: 10 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-04 15:59 UTC, mohitg0795 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSStepFilterJsonCreatorV2.java
> +            log.error("Not able to add file reference");
we should log the exception here.

2023-07-04 18:36 UTC, sourabh-awashti commented
trigger uts

2023-07-04 18:40 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSStepFilterJsonCreatorV2.java
> +            log.error("Not able to add file reference");
done

2023-07-04 18:40 UTC, sourabh-awashti commented
trigger uts

2023-07-05 04:36 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration-steps/src/test/resources/schema/ApprovalStage/all.json` line 6379 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZKVSpCOLLrv1Y23l_:-NZZKVSpCOLLrv1Y23la:bllhj51) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/pipeline-service/modules/orchestration-steps/src/test/resources/schema/ApprovalStage/all.json#L6379)):*
> ```JSON
>       ],
>       "properties": {
>         "fileRefs": {
> ```

We will need to update static schema too for this.


<!-- Sent from Reviewable.io -->

2023-07-05 04:37 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 2 of 5 files at r1, 3 of 6 files at r5, 1 of 1 files at r6, 4 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49938)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-05 05:00 UTC, archit-harness requested changes
> Reviewed 1 of 5 files at r1, 3 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49938)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/CDPMSStepFilterJsonCreatorV2Test.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZPsylDt56coC6qFM8:-NZZPsylDt56coC6qFM9:b-klx8ip) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/CDPMSStepFilterJsonCreatorV2Test.java#L53)):*
> ```Java
> import org.mockito.MockitoAnnotations;
> 
> public class CDPMSStepFilterJsonCreatorV2Test extends CDNGTestBase {
> ```

you dont need this testBase, use categoryTest, example - DeploymentStageFilterJsonCreatorV2Test
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 14913 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZQ6KO5KfUmmf-Bu8n:-NZZQ6KO5KfUmmf-Bu8o:b-6x09m6) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L14913)):*
> ```JSON
>             "fileRef": {
>               "type": "string"
>             },
> ```

is this expected? @yogesh-chauhan 
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/ShellScriptSourceWrapper.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZQ3ThAxoqBtVu5jFP:-NZZQ3ThAxoqBtVu5jFQ:b-51nfo2) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/ShellScriptSourceWrapper.java#L53)):*
> ```Java
>   }
> 
>   public List<String> getFileRefs() {
> ```

We should add @jsonIgnore, else they will come in schema


<!-- Sent from Reviewable.io -->

2023-07-05 05:16 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49938)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-05 05:21 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 14913 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZQ6KO5KfUmmf-Bu8n:-NZZUtlmD6EGwnR_dtWS:b-1f9lfn) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L14913)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is this expected? @yogesh-chauhan 
</blockquote></details>

should not be. @sourabh-awashti this is due to the getFileRef method. Lets rename it 


<!-- Sent from Reviewable.io -->

2023-07-05 06:21 UTC, sourabh-awashti commented
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/CDPMSStepFilterJsonCreatorV2Test.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZPsylDt56coC6qFM8:-NZZhYUfAUaVTzMM5G4s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/CDPMSStepFilterJsonCreatorV2Test.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you dont need this testBase, use categoryTest, example - DeploymentStageFilterJsonCreatorV2Test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 06:21 UTC, sourabh-awashti commented
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/ShellScriptSourceWrapper.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZQ3ThAxoqBtVu5jFP:-NZZhZzSA0d-8WA-vLIW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/ShellScriptSourceWrapper.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should add @jsonIgnore, else they will come in schema
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 06:21 UTC, sourabh-awashti commented
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 14913 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZQ6KO5KfUmmf-Bu8n:-NZZhaAu4z7BkIIqF_9r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L14913)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should not be. @sourabh-awashti this is due to the getFileRef method. Lets rename it 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 06:21 UTC, sourabh-awashti commented
*[`pipeline-service/modules/orchestration-steps/src/test/resources/schema/ApprovalStage/all.json` line 6379 at r8](https://reviewable.io/reviews/harness/harness-core/49938#-NZZKVSpCOLLrv1Y23l_:-NZZhbg0APo_Hys0yYhb:ba32pwy) ([raw file](https://github.com/harness/harness-core/blob/238c1b2baa1575ecd5b1763bbfd07f02439ba348/pipeline-service/modules/orchestration-steps/src/test/resources/schema/ApprovalStage/all.json#L6379)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We will need to update static schema too for this.
</blockquote></details>

no need to do as there is no schema change now


<!-- Sent from Reviewable.io -->

2023-07-05 06:22 UTC, sourabh-awashti commented
trigger uts

2023-07-05 07:08 UTC, sourabh-awashti commented
trigger uts

2023-07-05 07:18 UTC, archit-harness approved these changes
> Reviewed 8 of 9 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49938)* status: 9 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-05 09:26 UTC, yogesh-chauhan commented
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/ShellScriptSourceWrapper.java` line 54 at r10](https://reviewable.io/reviews/harness/harness-core/49938#-NZ_N-n99cfHKUmt1qOK:-NZ_N-n99cfHKUmt1qOL:b74q46b) ([raw file](https://github.com/harness/harness-core/blob/4d22becd112de760100b5bba060d7baf6c6eafa2/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/ShellScriptSourceWrapper.java#L54)):*
> ```Java
>   }
> 
>   @JsonIgnore
> ```

we ideally don't need this now



_Code quote:_
```Java
@JsonIgnore
```


<!-- Sent from Reviewable.io -->

2023-07-05 09:27 UTC, yogesh-chauhan approved these changes
> Reviewed 8 of 9 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49938)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-05 09:27 UTC, yogesh-chauhan commented
trigger review

2023-07-05 09:29 UTC, merged