feat: [PLG-2486]: Provision CI credits once per month
harness/harness-core pull request #49951
Opened 2023-06-29 15:32 UTC by thomas-grasman

## Describe your changes
Once per month, this background job runs and iterates through all CI module licenses and provision 2,000 free credits to each account. Each credit will start at the first day of the following month and expire on the first day of the month after that.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-06-29 18:24 UTC, thomas-grasman commented
trigger uts

2023-06-29 22:50 UTC, neelam-harness commented
Could you add the steps or some documentation used for testing this in the Testing Section please ?

2023-06-29 22:55 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java
> +  private static final int QUANTITY = 2000;
let's re-name it to `FREE_CREDITS_QUANTITY` to make it more explanatory. Thanks

2023-06-29 22:55 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java
> +            .schedulingType(IRREGULAR)
with the TARGET_INTERVAL of 27 days, do we still need this to be scheduling type of IRREGULAR ?

2023-06-30 13:52 UTC, Xin-Harness requested changes

2023-06-30 13:52 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java
> +  protected static final Duration INTERVAL = ofSeconds(30);
This Interval could be set a little bit longer than 30 seconds, since it is an iterator with low frequent. For testing purpose, set it to 30sec would be ideal.

2023-06-30 16:49 UTC, thomas-grasman commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java
> +            .schedulingType(IRREGULAR)
Yes. If we run it every 27 days, it would run twice in some months. Any interval larger than 28 days could miss February.

2023-06-30 16:51 UTC, thomas-grasman commented
trigger uts

2023-06-30 17:57 UTC, thomas-grasman commented
trigger messagecheck

2023-06-30 18:47 UTC, neelam-harness approved these changes

2023-06-30 18:54 UTC, thomas-grasman commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java
> +  protected static final Duration INTERVAL = ofSeconds(30);
Good catch. Changed it to 6 hours.

2023-06-30 21:19 UTC, Xin-Harness approved these changes

2023-06-30 21:19 UTC, thomas-grasman commented
trigger review

2023-06-30 22:09 UTC, merged