Ie 222
harness/harness-core pull request #50007
Opened 2023-07-02 13:43 UTC by Vbhatia20

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-04 13:21 UTC, williamwissemann approved these changes

2023-07-05 11:53 UTC, Vbhatia20 commented
trigger uts

2023-07-05 12:12 UTC, williamwissemann approved these changes

2023-07-05 15:21 UTC, diptiman-adak requested changes

2023-07-05 15:21 UTC, diptiman-adak commented on bazelrc.remote
> +#startup --output_base=/tmp
This flag was specific to Harness CI. Changing the output base to avoid space and inode exhaustion issue. However running the build within docker container might not need it.
But if we are using volume mount we need to use how this behaves. It might have some issues going forward.

2023-07-05 15:21 UTC, diptiman-adak commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +RUN chmod +x /opt/harness/*.sh
This will bloat-up the docker image size. It will create duplicate layers. 
COPY --chown=65534:65534 use like this

2023-07-05 15:21 UTC, diptiman-adak commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +RUN chmod +x \
This section should be avoided by mounting machine dir to docker.

2023-07-05 15:21 UTC, diptiman-adak commented on platform-service/build/feature_build.sh
> +export GCP_KEY="$1"
@Vbhatia20 we should be see this GCP does not get exposed. Please inspect the image to confirm if we pass the key during the build it don't store it into layers. We had issues previously with this

2023-07-05 15:22 UTC, diptiman-adak commented
Two things I want to see which can be impacted due to this change.
1. Build time
2. Docker image size. 
Can you add the supporting data for these two areas

2023-07-05 16:38 UTC, Vbhatia20 commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +RUN chmod +x /opt/harness/*.sh
this is removed

2023-07-05 21:37 UTC, williamwissemann commented on platform-service/build/feature_build.sh
> +export GCP_KEY="$1"
As long as the script is only used in the `builder` target and isn't passed to the `base` target then the secret won't show up in the layers. It may be worth adding some comments about being careful with adding secrets to the base target

2023-07-06 10:29 UTC, williamwissemann commented on platform-service/build/feature_build.sh
> +export GCP_KEY="$1"
@Vbhatia20 While the secret shouldn't end up in the `base` targets layers, we should ensure the build args aren't cached inside the container. There is a script on this confluence page that should detect them if they are:

https://harness.atlassian.net/wiki/spaces/SC/pages/21370306573/Scanning+Docker+Images+with+Gitleaks

You might want to explore to passing that secret in via the `--secret` flag ( docker build --secret )

2023-07-06 15:40 UTC, Vbhatia20 commented on platform-service/build/feature_build.sh
> +export GCP_KEY="$1"
I scanned and no git leaks found.

2023-07-06 15:53 UTC, Vbhatia20 commented
trigger uts

2023-07-07 11:35 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +ARG GCP_KEY
Generally you can't have secrets as args, args are visible in the final image. Since this is not a final stage though, not sure if someone could extract the GCP_KEY or not.

2023-07-07 11:36 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +COPY --chown=65534:65534  --from=builder /app/dist/platform-service/profile.jfc /opt/harness/
duplicated

2023-07-07 11:41 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +USER 65534
You should create the user properly. Take a look at this delegate PR and associated bug caused by this #44233

2023-07-07 11:44 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +RUN microdnf remove tar unzip gzip
After running microdnf commands you should also cleanup the caches (to reduce the size)
```
  && microdnf clean all \
  && rm -rf /var/cache/yum \
```

2023-07-07 11:52 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +COPY --chown=65534:65534  --from=builder /app/dist/platform-service/platform-service-capsule.jar /opt/harness/
Checkout these redhat best practices around writing Dockerfiles with UBI as a base OS. [Depending if needed] one of them is to use root user group (e.g. --chown=65534:0). If not specified, when the container runs in openshift (e.g. in SMP), it will only have access to the files in root user group. This is because OpenShift for security reasons ignores the user:group you specified in your `USER` command and runs the container with a <random_uuid>:0 (i.e.  userId is random number in range 1001-65534 and user group is 0)

2023-07-07 12:05 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +FROM base as saas
I'm assuming you would want to build either SaaS or SMP in a single execution. Note that this could depend on the docker builder and could have negative effect on your build performance. Legacy builder would build all stages in the multi stage Dockerfile regardless if they are needed/requested. [BuildKit](https://docs.docker.com/build/buildkit/) would only build stages needed to build the stage you requested.

2023-07-07 12:05 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +FROM base as onprem
Maybe rename to smp as per new naming convention.

2023-07-07 12:06 UTC, mdmilic commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +USER root
Do we want to run as root in SaaS

2023-07-07 12:37 UTC, Vbhatia20 commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +RUN microdnf remove tar unzip gzip
added these, but image size still same.

2023-07-14 14:06 UTC, Vbhatia20 commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +RUN chmod +x \
mounting will not work here

2023-07-14 14:08 UTC, Vbhatia20 commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +FROM base as saas
we need to build both and depending on target we will use it

2023-07-17 04:47 UTC, diptiman-adak commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +USER root
Yes we need to run to debug issues. 
This has been requested by SRE team earlier.

2023-08-02 06:15 UTC, Vbhatia20 commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +USER root
we havent made any changes here

2023-08-02 06:16 UTC, Vbhatia20 commented on platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage
> +USER 65534
we haven't change anything here

2023-08-02 06:41 UTC, Vbhatia20 commented
trigger uts

2023-08-02 06:41 UTC, Vbhatia20 commented
/rebase

2023-08-02 11:42 UTC, mdmilic reviewed
> Reviewed 3 of 5 files at r1, 1 of 2 files at r5, 1 of 3 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50007)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`platform-service/build/build_jar.sh` line 13 at r9](https://reviewable.io/reviews/harness/harness-core/50007#-NapvsXu45g3Q_41jgVQ:-NapvsXu45g3Q_41jgVR:beiihuy) ([raw file](https://github.com/harness/harness-core/blob/e10f11c75fecb07ce7a783a2fc046c69cc135cb3/platform-service/build/build_jar.sh#L13)):*
> ```Shell
> BAZEL_ARGUMENTS="--show_timestamps --announce_rc --experimental_convenience_symlinks=normal --remote_download_outputs=all --symlink_prefix=${BAZEL_DIRS}/"
> PLATFORM_SERVICE_MODULE="//platform-service/service:module_deploy.jar"
> bazel build --remote_cache=https://storage.googleapis.com/harness-bazel-cache --google_credentials=/tmp/storage_secret.json $PLATFORM_SERVICE_MODULE ${BAZEL_ARGUMENTS}
> ```

Any specific reason why you don't use bazelrc.remote here? This would implicitly use bazelrc.local instead (which is meant for localdev on mac - specifies mac specific flags, though without any negative effects if run on other platforms)
___
*[`platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/50007#gh-1253271446:-Napz-PA0SldpO60g_8_:bq7fljf) ([raw file](https://github.com/harness/harness-core/blob/2d3b7d859774c5f791d1e9472ee042a4062a40f7/platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage#L16)):*
<details><summary><i>Previously, Vbhatia20 (Vishal Bhatia) wrote…</i></summary><blockquote>

mounting will not work here
</blockquote></details>

The reason why you need to do chmod is because when files were originally created & committed to git, it was done with default permissions (I think 644). You can change permissions and commit that to git, then no need for everyone to do chmod. 
https://stackoverflow.com/questions/10516201/updating-and-committing-only-a-files-permissions-using-git-version-control
___
*[`platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage` line 48 at r5](https://reviewable.io/reviews/harness/harness-core/50007#gh-1255697325:-Naq09egDRCYBZyIoQhm:b1zozne) ([raw file](https://github.com/harness/harness-core/blob/ab92ce9788806a282eaf00b2b2f709b78382cf12/platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage#L48)):*
<details><summary><i>Previously, Vbhatia20 (Vishal Bhatia) wrote…</i></summary><blockquote>

we haven't change anything here
</blockquote></details>

I'm assuming you are copying this script from somewhere, it would be good to fix the issue anyway. 
___
*[`platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/50007#gh-1255722741:-Naq0k-ZEg6HGNomchcL:b-wn56bf) ([raw file](https://github.com/harness/harness-core/blob/ab92ce9788806a282eaf00b2b2f709b78382cf12/platform-service/build/container/Dockerfile-platform-service-cie-jdk-multistage#L55)):*
<details><summary><i>Previously, Vbhatia20 (Vishal Bhatia) wrote…</i></summary><blockquote>

we havent made any changes here
</blockquote></details>

This will be runAsUser for the session which actually runs the app (and by default other sessions, like exec/SSH). This is just a default and can be overridden when creating the pod/container. 
It would be better though to disable elevated privileges by default for the application session (if they are needed you should consciously configure them when creating pod and not get them by accident when you don't even configure anything). You can still use root when you exec into the pod if you really need root (which usually you shouldn't need anyway especially not in PROD).
NOTE: doesn't matter if you are copying these things from other scripts, stackoverflow or somewhere else, this is a new script, if you see something wrong you should fix it and not carry over the tech debt. 


<!-- Sent from Reviewable.io -->

2023-08-02 12:30 UTC, williamwissemann submitted a review, later dismissed

2023-08-02 13:36 UTC, mdmilic approved these changes

2023-08-02 14:08 UTC, williamwissemann approved these changes

2023-08-03 12:07 UTC, AnshuH commented
/rebase

2023-08-10 00:16 UTC, closed without merging