fix: [CDS-73137]: Added NGShellScriptFunctor
harness/harness-core pull request #50021
Opened 2023-07-03 05:17 UTC by sarthakkasat

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-03 18:55 UTC, yogesh-chauhan commented on 980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java
> +  ScriptType scriptType;
this can be private

2023-07-03 18:55 UTC, yogesh-chauhan commented on 980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java
> +  public NGShellScriptFunctor(ScriptType scriptType) {
we can just use @AllArgsConstructur

2023-07-03 19:53 UTC, srinivaswings commented
@ankittiwari-harness Please start getting familiarizing with Shell Step

2023-07-04 05:36 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/50021#gh-1251197749:-NZUOGukAd42tTc90ij-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0e30e8338d80148068a6121ebbd587cba85d5a9b/980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java#L20)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this can be private
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/50021#gh-1251197890:-NZUOHfpAC-MoUVJvcJU:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/0e30e8338d80148068a6121ebbd587cba85d5a9b/980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java#L22)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can just use @AllArgsConstructur
</blockquote></details>

Discussed offline


<!-- Sent from Reviewable.io -->

2023-07-04 09:21 UTC, yogesh-chauhan submitted a review, later dismissed

2023-07-04 09:23 UTC, sarthakkasat commented
trigger messagecheck

2023-07-04 09:57 UTC, hingerabhinav approved these changes
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 7 file(s) to review. 2. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-07-04 10:00 UTC, sarthakkasat commented
trigger review

2023-07-04 11:23 UTC, sarthakkasat commented
trigger uts

2023-07-04 12:17 UTC, sarthakkasat commented
trigger uts

2023-07-04 13:37 UTC, sarthakkasat commented
trigger review

2023-07-04 14:15 UTC, puthrayaharness submitted a review, later dismissed

2023-07-05 05:47 UTC, sahilhindwani-harness commented
*[`980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/50021#gh-1251197749:-NZZ_o3_9hnfN_6NQhuj:b-embe7w) ([raw file](https://github.com/harness/harness-core/blob/0e30e8338d80148068a6121ebbd587cba85d5a9b/980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java#L20)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we not use shellScriptFunctor directly?


<!-- Sent from Reviewable.io -->

2023-07-05 05:51 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 7 file(s) to review. 2. unresolved discussions. Waiting on team(s): del-team. 

___
*[`980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/50021#gh-1251197749:-NZZaO6f1UAnOhKeuu_5:b-g0yyy) ([raw file](https://github.com/harness/harness-core/blob/0e30e8338d80148068a6121ebbd587cba85d5a9b/980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java#L20)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we not use shellScriptFunctor directly?
</blockquote></details>

We don't want to couple ng and cg functors, also we are not using all the methods from ShellScriptFunctor


<!-- Sent from Reviewable.io -->

2023-07-05 05:54 UTC, archit-harness requested changes
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 1 change requests. 2. unresolved discussions. Waiting on team(s): del-team. 

___
*[`970-api-services-beans/BUILD.bazel` line 95 at r4](https://reviewable.io/reviews/harness/harness-core/50021#-NZZaPiB4OJNJU3zlarp:-NZZaPiB4OJNJU3zlarq:b-2pfjt5) ([raw file](https://github.com/harness/harness-core/blob/35d95f2e178877fe9811fa26dcea28c8dd08d3c9/970-api-services-beans/BUILD.bazel#L95)):*
> ```Starlark
>         "//970-api-services-beans/src/main/java/software/wings/utils:module",
>         "//970-api-services-beans/src/main/proto:970_api_services_beans_java_proto",
>         "//980-commons/src/main/java/io/harness/shell:module",
> ```

why is this required?
___
*[`980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/50021#-NZZbJfK6-gc9yHc_Lwg:-NZZbJfK6-gc9yHc_Lwh:bqf7uew) ([raw file](https://github.com/harness/harness-core/blob/35d95f2e178877fe9811fa26dcea28c8dd08d3c9/980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java#L19)):*
> ```Java
> @OwnedBy(CDC)
> @Slf4j
> public class NGShellScriptFunctor implements ExpressionFunctor {
> ```

@sarthakkasat can you add comment that this is tested with bash script and powershell currently is not supported


<!-- Sent from Reviewable.io -->

2023-07-05 06:22 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 1 change requests. 2. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-07-05 06:40 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 1 change requests. 4. unresolved discussions. Waiting on team(s): del-team. 

___
*[`970-api-services-beans/BUILD.bazel` line 95 at r4](https://reviewable.io/reviews/harness/harness-core/50021#-NZZaPiB4OJNJU3zlarp:-NZZldnJ1WawCksY1m4K:b-4o07rf) ([raw file](https://github.com/harness/harness-core/blob/35d95f2e178877fe9811fa26dcea28c8dd08d3c9/970-api-services-beans/BUILD.bazel#L95)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

It is not required, will remove it in next pr
___
*[`980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/50021#gh-1251197749:-NZZliHbDl0A9Buy23Xp:bi686e1) ([raw file](https://github.com/harness/harness-core/blob/0e30e8338d80148068a6121ebbd587cba85d5a9b/980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java#L20)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think since the way this functor is written is generic, we should use that only. Otherwise there is a chance of missing fixes and maintain two same functors. 
</blockquote></details>

Discussed on slack.
___
*[`980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/50021#-NZZbJfK6-gc9yHc_Lwg:-NZZliVf-Mi7nfT16Grl:b6wbaml) ([raw file](https://github.com/harness/harness-core/blob/35d95f2e178877fe9811fa26dcea28c8dd08d3c9/980-commons/src/main/java/io/harness/expression/functors/NGShellScriptFunctor.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@sarthakkasat can you add comment that this is tested with bash script and powershell currently is not supported
</blockquote></details>

Will add it in next PR.


<!-- Sent from Reviewable.io -->

2023-07-05 06:41 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 2. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-07-05 06:56 UTC, sarthakkasat commented
trigger uts

2023-07-05 07:06 UTC, sarthakkasat commented
trigger uts

2023-07-05 07:46 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50021)* status: 2 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-07-05 09:32 UTC, merged