fix: [CDS-69762]: Support for metadata incase of bamboo artifacts
harness/harness-core pull request #50077
Opened 2023-07-03 18:29 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-03 21:01 UTC, sribalij commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/bamboo/BambooServiceImpl.java
> +                if (jsonNode.get("planName") != null) {
Can you add Constants for these?

2023-07-03 21:02 UTC, sribalij requested changes
Added minor comments

2023-07-04 02:44 UTC, arvind-choudhary-h approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50077)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-04 12:37 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/bamboo/BambooServiceImpl.java
> +                if (jsonNode.get("planName") != null) {
Done

2023-07-04 14:18 UTC, vivekkarnatiharness commented
trigger uts

2023-07-04 14:20 UTC, puthrayaharness approved these changes

2023-07-04 14:56 UTC, Abhishek-CDC commented on 930-delegate-tasks/src/main/java/software/wings/helpers/ext/bamboo/BambooServiceImpl.java
> +                if (jsonNode.get(id) != null) {
Can we use a more informative key for id, as it will be displayed as "id" in UI.
Also generally keys for metadata we store in a interface 'ArtifactMetadataKeys'.
Please refer ArtifactResponseToOutcomeMapper class for implementation

2023-07-04 15:26 UTC, Abhishek-CDC approved these changes

2023-07-04 16:12 UTC, puthrayaharness approved these changes

2023-07-04 16:35 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-07-04 16:35 UTC, vivekkarnatiharness commented
trigger review

2023-07-04 16:44 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-07-04 16:57 UTC, puthrayaharness approved these changes

2023-07-05 03:49 UTC, sribalij approved these changes

2023-07-05 03:50 UTC, merged