feat: [CDS-71603]: K8s Extend Enum list for Kind to all types of resources
harness/harness-core pull request #50100
Opened 2023-07-04 04:41 UTC by namantalaycha10

## Describe your changes
K8s Extend Enum list for Kind to all types of resources

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-04 04:55 UTC, namantalaycha10 commented
trigger uts

2023-07-04 05:51 UTC, namantalaycha10 commented
trigger messagecheck

2023-07-04 06:03 UTC, abhinavsingh1196 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/ListKind.java
> +  NOOPList(Kind.NOOP);
why do we need this ?

2023-07-04 06:04 UTC, GoelPratyush99 submitted a review, later dismissed

2023-07-04 11:42 UTC, namantalaycha10 commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/ListKind.java
> +  NOOPList(Kind.NOOP);
Done

2023-07-04 11:42 UTC, namantalaycha10 commented
trigger review

2023-07-04 11:43 UTC, namantalaycha10 commented
trigger uts

2023-07-04 11:45 UTC, TarunUba1 approved these changes

2023-07-04 11:56 UTC, abhinavsingh1196 requested changes

2023-07-04 11:56 UTC, abhinavsingh1196 commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/ListKindTest.java
> +public class ListKindTest extends CategoryTest {
this test contains a lot of redundancy, it can be refactored? 
the only variable changing in the KubernetesResource is the kind and name, maybe at least create that data from ListKind.values() for valid cases?

ListKind[] listKinds = ListKind.values()
List<KubernetesResource> validResources = Arrays.aslist(listKinds).stream().(listkind -> createResource(listkind.toString())).collect(toList());
// assert valid resources


testInvalidResources -> List.of(createResource("abc"), createResource("def")...)
// assert invalid resources

createResource(String name) {
...
}

2023-07-04 13:18 UTC, namantalaycha10 commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/ListKindTest.java
> +public class ListKindTest extends CategoryTest {
@abhinavsingh1196 but if we create the validResources using ListKind enum then how we will validate the enum properly
suppose if somebody tried to remove NamespaceList then also this test will pass as we are creating valid resources using ListKind and validating with ListKind itself

2023-07-04 13:22 UTC, abhinavsingh1196 commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/ListKindTest.java
> +public class ListKindTest extends CategoryTest {
we can create a static hardcoded list in the test with all values like:

List validResources  = List.of("ConfigMapList"......)

2023-07-04 13:40 UTC, namantalaycha10 commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/ListKindTest.java
> +public class ListKindTest extends CategoryTest {
Done

2023-07-04 13:40 UTC, namantalaycha10 commented
trigger uts

2023-07-04 13:56 UTC, abhinavsingh1196 approved these changes

2023-07-04 13:57 UTC, abhinavsingh1196 approved these changes

2023-07-04 13:57 UTC, abhinavsingh1196 commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/ListKindTest.java
> +      if (listKind.name().contains(kubernetesResource.getResourceId().getKind())) {
nit: equals would be more accurate

2023-07-04 16:45 UTC, TarunUba1 approved these changes

2023-07-04 17:13 UTC, GoelPratyush99 approved these changes

2023-07-05 04:41 UTC, namantalaycha10 commented
trigger review

2023-07-05 04:42 UTC, namantalaycha10 commented on 970-api-services-beans/src/test/java/io/harness/k8s/model/ListKindTest.java
> +      if (listKind.name().contains(kubernetesResource.getResourceId().getKind())) {
actually listKind.name() returns ListKind for example NamespaceList with contains Namespace thats why I used this one

2023-07-05 04:43 UTC, merged