feat: [CDS-70209]: Validating and resolving multiple helm chart manifests
harness/harness-core pull request #50143
Opened 2023-07-05 06:17 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-05 06:32 UTC, GoelPratyush99 commented
trigger uts

2023-07-05 08:57 UTC, abhinavsingh1196 requested changes

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +        featureFlagHelperService.isEnabled(account, FeatureName.CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG);
This layer doesn't look right to propagate FF value since we're ultimately using it only while creating/validating the entity. This feature is very specific and applicable only to helm charts.
When we want to GA this FF, all these layers would need to be modified again to remove this boolean.

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +        featureFlagHelperService.isEnabled(account, FeatureName.CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG);
Maybe we can add this in `ServiceResourceApiUtils` before we call NgServiceEntityMapper?

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java
> +        NGServiceEntityMapper.toNGServiceConfig(serviceEntity, isHelmMultipleManifestSupportEnabled);
adding a new arg every time will not scale. what i can think of is we can have a Map for FF values generated by some other interface, which we then pass to NGServiceEntityMapper

`Map<String, Boolean> featureFlags = NGServiceV2FFCalculator.computeFlags(accountId);`
`NGServiceConfig ngServiceConfig = NGServiceEntityMapper.toNGServiceConfig(serviceEntity, isHelmMultipleManifestSupportEnabled);`

NGServiceV2FFCalculator can have a static list of FFs it will evaluate like :

class NGServiceV2FFCalculator {
  static list featureFlags = [A, B, C];

  computeFlags(accountId) {
    computeFlags(accountId, featureFlags);
  }
  computeFlags(accountId, featureFlagListInput) {
    // compute featureFlagListInput and return map
  }

}

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +            .manifestConfigurations(featureFlagHelperService.isEnabled(AmbianceUtils.getAccountId(ambiance),
should probably move this condition inside method `getManifestConfigurations`

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java
> +        NGServiceEntityMapper.toNGServiceConfig(serviceEntity, isHelmMultipleManifestSupportEnabled);
we can then pass this map till the lowest level possible to avoid adding this boolean to every method

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java
> +    if (spec == null) {
this method should be broken down further into:
boolean isHelmMultipleManifestSupportEnabled(ServiceSpec spec, Map<String, Boolean> featureFlags) {
  return BooleanUtils.isTrue(featureFlags.get(HELM_MULTIPLE_MANIFESTS_FF)) && serviceContainsMultipleHelmManifests(spec)
}

boolean serviceContainsMultipleHelmManifests(ServiceSpec spec) {
    // rest of the logic for checking service spec
}

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +  public List<String> getManifestIdentifiersFilteredOnServiceType(YamlField manifestsField) {
nit: method name is not applicable anymore

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +  public YamlField getManifestsNodeFromServiceYaml(YamlField serviceYamlField) {
this method could be written on top of the existing method? 

getManifestsNodeFromServiceYaml (...) {
 // check service type

getManifestsNodeFromServiceDefinitionYaml(...)  {
 // existing method
}

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
> +    List<ServiceEntity> serviceEntities = serviceRequestDTOs.stream()
same as above, let's not pass a boolean here

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +    boolean isMultipleManifestSupportEnabled = manifestConfigurations != null;
nit: redundant var
`boolean isMultipleManifestSupportEnabled = ngManifestsMetadataSweepingOutput.getManifestConfigurations() != null;`

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      if (isMultipleManifestSupportEnabled && ManifestType.HelmChart.equals(manifestOutcome.getType())
just thinking here, can we make ManifestOutcome interface extend the following interface:

interface WithMultipleManifests {
  boolean supportsMultipleManifests();
  boolean isPrimaryManifestRef(String manifestId);
}

ManifestOutcome can extend this interface, with default implementation as false and we can implement it only for Helm chart manifest. 
It won't help much right now since there are not much usages like this. But we can avoid changes here if later we want to support other manifests.

2023-07-05 08:57 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java
> +  public static void throwMultipleManifestsExceptionIfApplicable(Map<String, String> manifestIdToManifestTypeMap,
unit tests should be added for this, for all negative cases and combinations of helm and non-helm manifests

2023-07-07 03:52 UTC, GoelPratyush99 commented
trigger uts

2023-07-07 03:53 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java
> +        featureFlagHelperService.isEnabled(account, FeatureName.CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG);
Done

2023-07-07 03:53 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java
> +        NGServiceEntityMapper.toNGServiceConfig(serviceEntity, isHelmMultipleManifestSupportEnabled);
Done

2023-07-07 03:53 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +            .manifestConfigurations(featureFlagHelperService.isEnabled(AmbianceUtils.getAccountId(ambiance),
done

2023-07-07 03:53 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java
> +    if (spec == null) {
Done

2023-07-07 03:53 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +  public List<String> getManifestIdentifiersFilteredOnServiceType(YamlField manifestsField) {
Done

2023-07-07 03:54 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +  public YamlField getManifestsNodeFromServiceYaml(YamlField serviceYamlField) {
Done

2023-07-07 03:54 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
> +    List<ServiceEntity> serviceEntities = serviceRequestDTOs.stream()
Done

2023-07-07 03:54 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +    boolean isMultipleManifestSupportEnabled = manifestConfigurations != null;
Removed it

2023-07-07 04:03 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      if (isMultipleManifestSupportEnabled && ManifestType.HelmChart.equals(manifestOutcome.getType())
I don't think we should do this. ManifestOutcome represents a single manifest and these fields `supportMultipleManifests` and `isPrimaryManifestRef` should be for a more higher entity such as manifests

2023-07-07 04:04 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java
> +  public static void throwMultipleManifestsExceptionIfApplicable(Map<String, String> manifestIdToManifestTypeMap,
Added in NGServiceEntityMapperTest.java

2023-07-07 06:37 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      if (isMultipleManifestSupportEnabled && ManifestType.HelmChart.equals(manifestOutcome.getType())
valid point, but we still should make this logic here generic. something like this maybe:

`if (shouldIgnoreManifestOutcome(ngManifestsMetadataSweepingOutput, manifestOutcome) {continue;}`



boolean shouldIgnoreManifestOutcome(manifestsMetadataSweepingOutput, manifestOutcome)
{
  switch (manifestOutcome.getType()) {
    case HelmChart:
      boolean isMultipleManifestSupportEnabled = manifestsMetadataSweepingOutput. getManifestConfigurations() != null
      // check equality with primary manifest ref
    default:
        return false;
  }
}

2023-07-10 13:12 UTC, GoelPratyush99 commented
trigger uts

2023-07-10 13:12 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java
> +    boolean isHelmMultipleManifestSupportEnabled =
Done

2023-07-10 13:13 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      if (isMultipleManifestSupportEnabled && ManifestType.HelmChart.equals(manifestOutcome.getType())
Moved the resolution part to ServiceStepOverrideHelper

2023-07-10 15:23 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +  private List<ManifestConfigWrapper> applyManifestConfigurationsToSvcManifests(
should we come up with better names for methods here? for ex - this method is collecting all non helm chart manifests + primary helm chart manifest. the name should indicate that

2023-07-10 15:23 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +  private List<ManifestConfigWrapper> applyManifestConfigurationsToSvcManifests(
there should be unit tests for this whole logic involving applying of manifest configurations? Or it's fine if it is covered by tests in some wrapper

2023-07-10 20:10 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +  private List<ManifestConfigWrapper> applyManifestConfigurationsToSvcManifests(
Changed to filterPrimaryHelmManifest and the tests are added in ServiceStepV3.java

2023-07-10 20:11 UTC, GoelPratyush99 commented
trigger uts

2023-07-11 05:20 UTC, abosii-harness requested changes

2023-07-11 05:20 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java
> +  private boolean serviceContainsMultipleHelmManifests(ServiceSpec spec) {
I don't see any checks on multiple manifests, is the method name correct?

2023-07-11 05:20 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +    if (!(ServiceSpecType.NATIVE_HELM.equals(serviceDefinitionType)
Is this method used by other swimlanes? Will it fail?

2023-07-11 05:20 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> -    Set<String> supportedManifestTypes = ManifestType.getSupportedManifestTypes(serviceType);
Can we keep previous logic? Or write something more generic?

2023-07-11 05:20 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +            -> !ManifestConfigType.HELM_CHART.equals(manifest.getManifest().getType())
Do we actually need to care about this at this point? Is it possible to make this logic generic independent of the type of HelmChart? I guess we are not allowing to save pipeline if service contains multiple non-helm chart manifests, so plan creator logic can be made generic and independent of this checks. This would allow to easy extend this by just updating validation logic on filter

2023-07-11 05:39 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> +    if (!(ServiceSpecType.NATIVE_HELM.equals(serviceDefinitionType)
No this is part of new api call that I have created. It will be used show all the eligible primary manifest in list format

2023-07-11 05:41 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +            -> !ManifestConfigType.HELM_CHART.equals(manifest.getManifest().getType())
ok

2023-07-11 09:56 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java
> -    Set<String> supportedManifestTypes = ManifestType.getSupportedManifestTypes(serviceType);
Its Part of API call so we should be specific to what we support at present.

2023-07-11 09:57 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java
> +  private boolean serviceContainsMultipleHelmManifests(ServiceSpec spec) {
changes the name to serviceContainsManifestConfigurations

2023-07-11 10:04 UTC, GoelPratyush99 commented
trigger uts

2023-07-11 11:13 UTC, abosii-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceResourceApiUtilsTest.java
> +    Reflect.on(serviceResourceApiUtils).set("serviceEntityService", serviceEntityService);
Is it?

2023-07-11 11:40 UTC, GoelPratyush99 commented
trigger uts

2023-07-11 15:40 UTC, GoelPratyush99 commented
trigger ut8

2023-07-12 04:15 UTC, GoelPratyush99 commented
trigger uts

2023-07-12 05:49 UTC, GoelPratyush99 commented
trigger ut8

2023-07-12 08:12 UTC, abosii-harness requested changes

2023-07-12 08:12 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceApiUtils.java
> +  @Inject private ServiceEntityService serviceEntityService;
We should use constructor injector

2023-07-12 08:12 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java
> +        && ctx.getDependency().getMetadataMap().containsKey(PRIMARY_MANIFEST_REF);
Can this condition be true? Is this metadata map populated somewhere to contain PRIMARY_MANIFEST_REF? Or it's done at the framework level?

2023-07-14 09:19 UTC, closed without merging