feat: [CDS-73627]: Trigger service integration with queue service
harness/harness-core pull request #50178
Opened 2023-07-05 13:21 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-11 05:12 UTC, shalini-agr commented
trigger uts

2023-07-11 05:46 UTC, archit-harness requested changes
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50178)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/50178#-N_2TxAX4Pz_DAWQa-Vs:-N_2TxAX4Pz_DAWQa-Vt:bh450nx) ([raw file](https://github.com/harness/harness-core/blob/5b290e0a7b6b1cdd555c91764e154ea7a6818bdd/120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java#L119)):*
> ```Java
>                              .producerName(moduleName + "WebhookPREvent")
>                              .payload(RecastOrchestrationUtils.toJson(webhookDTO))
>                              .build();
> ```

we should have a getEnqueueRequest method which returns requests based on event type


<!-- Sent from Reviewable.io -->

2023-07-11 06:59 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50178)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/50178#-N_2TxAX4Pz_DAWQa-Vs:-N_2jw984asheSyQri5-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5b290e0a7b6b1cdd555c91764e154ea7a6818bdd/120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java#L119)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should have a getEnqueueRequest method which returns requests based on event type
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-11 07:15 UTC, shalini-agr commented
trigger uts

2023-07-11 08:43 UTC, archit-harness approved these changes
> Reviewed 2 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50178)* status: 12 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-11 09:29 UTC, shalini-agr commented
trigger ut6

2023-07-12 05:21 UTC, sribalij commented on 120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java
> +    if (isEmpty(webhookEvent.getUuid())) {
Can we also include logs in the context?

2023-07-12 05:22 UTC, sribalij commented on 120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java
> +  private void generateWebhookDTOAndEnqueue(WebhookEvent webhookEvent) {
If you find it useful (in case something else comes up in future) move it to another class else this is fine too.

2023-07-12 05:23 UTC, sribalij commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  PIE_QUEUE_SERVICE_FOR_TRIGGERS(
We have been using FF with names mostly with CDS now instead of PIE. Can you please change this?

2023-07-12 06:30 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50178)* status: 12 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/50178#gh-1260605611:-N_7lye898h1vU7IdO1w:b-ccppd2) ([raw file](https://github.com/harness/harness-core/blob/929ffe6d0c1133efb501494a15e85a269cc5d607/120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java#L73)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

If you find it useful (in case something else comes up in future) move it to another class else this is fine too. 
</blockquote></details>

for now, we are only using this method in one place, we can move later if needed.
___
*[`120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/50178#gh-1260604497:-N_7lrhp1kiJluOVCxrk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/929ffe6d0c1133efb501494a15e85a269cc5d607/120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java#L74)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Can we also include logs in the context?
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 821 at r2](https://reviewable.io/reviews/harness/harness-core/50178#gh-1260606403:-N_7kjPz5MTIcdbHvvyu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/929ffe6d0c1133efb501494a15e85a269cc5d607/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L821)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

We have been using FF with names mostly with CDS now instead of PIE. Can you please change this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-12 06:43 UTC, shalini-agr commented
trigger uts

2023-07-12 07:31 UTC, ankittiwari-harness submitted a review, later dismissed
Approved for queue service integ

2023-07-12 07:31 UTC, ankittiwari-harness commented on 120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl/WebhookServiceImpl.java
> +          .topic(topic + "WebhookPushEvent")
nit: use contants

2023-07-12 08:30 UTC, shalini-agr commented
trigger ut5

2023-07-12 10:52 UTC, archit-harness submitted a review, later dismissed
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50178)* status: 12 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-12 11:51 UTC, shalini-agr commented
trigger uts

2023-07-12 14:10 UTC, shalini-agr commented
trigger uts

2023-07-12 18:56 UTC, sribalij approved these changes

2023-07-13 05:40 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50178)* status: 13 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-13 05:43 UTC, shalini-agr commented
trigger review

2023-07-13 05:45 UTC, merged