feat: [CDS-50312]: K8s delegate changes: Get Node information via API…
harness/harness-core pull request #50177
Opened 2023-07-05 12:51 UTC by namantalaycha10

… from CD Deployment Step for CV

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-05 13:47 UTC, abhinavsingh1196 requested changes

2023-07-05 13:47 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +  default List<K8sPod> getNewK8sPodList() {
can the default impl for this be like following so that we can remove the same impl from all responses:


allPods = getTotalK8sPodList() 
return allPods.stream().filter(K8sPod::isNewPod).collect(Collectors.toList());

2023-07-05 13:47 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +    return null;
same as above, should return empty list instead of null?

2023-07-05 13:47 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java
> +    List<K8sPod> existingPodList = k8sTaskHelperBase.getPodDetails(k8sCanaryHandlerConfig.getKubernetesConfig(),
same as above, please check if all vars are populated for this

2023-07-05 13:47 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java
> +        k8sCanaryHandlerConfig.getCanaryWorkload().getResourceId().getNamespace(),
sometimes namespace is not set in resources, we can use `k8sCanaryHandlerConfig.getKubernetesConfig().getNamespace()` to be sure

2023-07-06 08:07 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +  default List<K8sPod> getNewK8sPodList() {
Actually this impl we have to do for the selective steps blueGreen, canary and rolling only that why better idea here is in default method is to return emptyList() instead of impl here only

2023-07-06 08:09 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sCanaryDeployResponse.java
> +  public List<K8sPod> getNewK8sPodList() {
Actually this impl we have to do for the selective steps blueGreen, canary and rolling only that why better idea here is in default method is to return emptyList() instead of impl here only

2023-07-06 08:34 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDeployResponse.java
> +        .serviceInstancesBefore(k8sNGTaskResponse.getPreviousK8sPodList()
Done

2023-07-06 08:34 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +    return null;
Done

2023-07-06 08:34 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +    return null;
Done

2023-07-06 08:35 UTC, namantalaycha10 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java
> +        k8sCanaryHandlerConfig.getCanaryWorkload().getResourceId().getNamespace(),
Done

2023-07-06 09:21 UTC, acasian-harness commented
@namantalaycha10 please update the PR description

2023-07-06 10:13 UTC, acasian-harness reviewed
this covers only BG & Canary, don't we need the same for Rolling?

2023-07-06 10:33 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +  default List<K8sPod> getNewK8sPodList() {
We can even remove this method from the interface, since in `K8sDeployResponse` we can calculate this easily by filtering out the total list? There is no additional data required to do this and this method doesn't serve any more purpose.

2023-07-06 10:35 UTC, namantalaycha10 commented
> this covers only BG & Canary, don't we need the same for Rolling?

Yes for rolling also, I also added the changes for the rolling

2023-07-06 10:36 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +  default List<K8sPod> getNewK8sPodList() {
Sure Make Sense

2023-07-06 10:55 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sNGTaskResponse.java
> +  default List<K8sPod> getNewK8sPodList() {
Done

2023-07-06 11:55 UTC, abhinavsingh1196 requested changes

2023-07-06 11:55 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDeployResponse.java
> +        .deployedServiceInstances(convertK8sPodsToK8sStepInstanceInfo(k8sNGTaskResponse.getTotalK8sPodList(), true))
instead of passing true/false here, lets just make a different method for filtering the pod list
`convertK8sPodsToK8sStepInstanceInfo(extractNewPods(k8sNGTaskResponse.getTotalK8sPodList()))`

2023-07-06 12:23 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDeployResponse.java
> +        .deployedServiceInstances(convertK8sPodsToK8sStepInstanceInfo(k8sNGTaskResponse.getTotalK8sPodList(), true))
done

2023-07-07 07:01 UTC, abhinavsingh1196 submitted a review, later dismissed

2023-07-07 14:06 UTC, TarunUba1 submitted a review, later dismissed

2023-07-10 08:19 UTC, abosii-harness submitted a review, later dismissed

2023-07-12 04:46 UTC, namantalaycha10 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGBaseHandler.java
> +    allPods.addAll(primaryPods);
Yes I confirmed with @yogesh-chauhan we are sending back both colors pods

2023-07-12 10:05 UTC, namantalaycha10 commented
trigger uts

2023-07-12 10:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGBaseHandler.java
> +    allPods.addAll(primaryPods);
Then I guess will be more optimal to fetch by release name?

2023-07-12 10:12 UTC, namantalaycha10 commented
trigger uts

2023-07-12 12:38 UTC, namantalaycha10 commented
trigger uts

2023-07-12 13:34 UTC, namantalaycha10 commented
trigger uts

2023-07-12 13:44 UTC, abhinavsingh1196 requested changes

2023-07-12 17:52 UTC, namantalaycha10 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGBaseHandler.java
> +    allPods.addAll(primaryPods);
Done

2023-07-12 17:56 UTC, namantalaycha10 commented
trigger uts

2023-07-13 05:58 UTC, namantalaycha10 commented
trigger uts

2023-07-13 06:27 UTC, namantalaycha10 commented
trigger uts

2023-07-13 06:47 UTC, abhinavsingh1196 approved these changes

2023-07-13 06:47 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sRollingStepTest.java
> +                                                                     .previousK8sPodList(Collections.emptyList())
nit: if we're not asserting anything new, based on this newly added data, then we can avoid adding it altogether?

2023-07-13 08:31 UTC, TarunUba1 approved these changes

2023-07-13 08:40 UTC, GoelPratyush99 approved these changes

2023-07-13 08:43 UTC, namantalaycha10 commented
trigger review

2023-07-13 09:18 UTC, yogesh-chauhan approved these changes
> Reviewed 7 of 12 files at r6, 15 of 22 files at r7, 3 of 3 files at r9, 4 of 5 files at r10, 3 of 3 files at r11, 5 of 5 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50177)* status: 39 file(s) to review. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-13 09:29 UTC, namantalaycha10 commented
trigger review

2023-07-13 09:37 UTC, sahilhindwani-harness approved these changes
> Reviewed 3 of 5 files at r12, 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50177)* status: 35 file(s) to review. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-13 09:38 UTC, merged