fix: [PL-38934]: Moved acl check from service to resource layer for list resourcegroup API
harness/harness-core pull request #50170
Opened 2023-07-05 11:30 UTC by tiwaritejas

## Describe your changes
This PR refactors the ACL check from the service layer to the resource layer for the list API for resource groups. Since, this is a common method used by internal jobs for service startups as well, we are avoiding making an access control checks from the service. This will decouple the platform-service startup from access control service.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-05 11:33 UTC, tiwaritejas commented
trigger uts

2023-07-06 10:39 UTC, tiwaritejas commented
trigger uts

2023-07-17 14:54 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: Some of the checks are too old. 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/50170#-N_ZL84c9dbzabLfpYSi:-N_ZL84c9dbzabLfpYSj:bv5fl1m) ([raw file](https://github.com/harness/harness-core/blob/04b7db5c69227253c00b0ae0c38eb92cf551e581/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L106)):*
> ```Java
>       ResourceGroupFilterDTO resourceGroupFilterDTO, String accountIdentifier, PageRequest pageRequest) {
>     boolean fetchAllResourceGroups = accessControlClient.hasAccess(
>         ResourceScope.of(resourceGroupFilterDTO.getAccountIdentifier(), resourceGroupFilterDTO.getOrgIdentifier(),
> ```

@tiwaritejas   Please refer PR https://github.com/harness/harness-core/pull/48825 for implementation.


<!-- Sent from Reviewable.io -->

2023-07-24 10:29 UTC, tiwaritejas commented
trigger uts

2023-07-25 07:09 UTC, tiwaritejas commented
trigger uts_JDK11

2023-07-27 06:20 UTC, tiwaritejas commented
trigger uts_JDK11

2023-07-27 07:11 UTC, tiwaritejas commented
trigger uts

2023-07-27 07:28 UTC, tiwaritejas commented
trigger uts_JDK11

2023-07-27 08:49 UTC, tiwaritejas commented
trigger uts_JDK11

2023-08-01 03:55 UTC, meenakshi-harness commented on platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java
> +        PageUtils.getPage(permittedResourceGroups, pageRequest.getPageIndex(), pageRequest.getPageSize());
We should throw an exception of Missing permission in case permittedResourceGroups is empty.

2023-08-01 03:56 UTC, meenakshi-harness commented on platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java
> +    if (accessControlClient.hasAccess(
Also add UT for this

2023-08-03 04:24 UTC, tiwaritejas commented
trigger uts

2023-08-03 04:45 UTC, tiwaritejas commented
trigger uts

2023-08-03 05:05 UTC, tiwaritejas commented on platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java
> +        PageUtils.getPage(permittedResourceGroups, pageRequest.getPageIndex(), pageRequest.getPageSize());
Done

2023-08-03 05:05 UTC, tiwaritejas commented on platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java
> +    if (accessControlClient.hasAccess(
Done.

2023-08-04 08:41 UTC, meenakshi-harness submitted a review, later dismissed

2023-08-04 08:42 UTC, meenakshi-harness commented
Add testing done in deascription

2023-08-04 09:26 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/50170#-N_ZL84c9dbzabLfpYSi:-Nazrb7YBWM91hLybB2x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04b7db5c69227253c00b0ae0c38eb92cf551e581/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L106)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

@tiwaritejas   Please refer PR https://github.com/harness/harness-core/pull/48825 for implementation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-08 06:20 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: Some of the checks are too old. 12 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 299 at r7](https://reviewable.io/reviews/harness/harness-core/50170#-NbInHTUE0RzNRw7wKpD:-NbInHTUE0RzNRw7wKpE:bzcygx5) ([raw file](https://github.com/harness/harness-core/blob/62f6814ad0b791d68b05d0023feb7ca40820c2ee/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L299)):*
> ```Java
>   @Override
>   public Page<ResourceGroup> listAll(ResourceGroupFilterDTO resourceGroupFilterDTO, PageRequest pageRequest) {
>     Criteria criteria = getResourceGroupFilterCriteria(resourceGroupFilterDTO);
> ```

@tiwaritejas How is this going to fetch all RGs if we have pagination set from resource layer?


<!-- Sent from Reviewable.io -->

2023-08-08 08:59 UTC, Jimit09Gandhi requested changes
> Reviewed 2 of 11 files at r3, 7 of 9 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java` line 147 at r8](https://reviewable.io/reviews/harness/harness-core/50170#-NbJMega4fBGKLxAeYt7:-NbJMega4fBGKLxAeYt8:bz82dte) ([raw file](https://github.com/harness/harness-core/blob/bc83b39e425f0523b84809b37e5ec18e3271aabb/platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java#L147)):*
> ```Java
>     List<ResourceGroup> resourceGroupsList = List.of(ResourceGroup.builder().build());
>     Page<ResourceGroup> allResourceGroups = new PageImpl<>(resourceGroupsList);
>     when(resourceGroupService.listAll(resourceGroupFilterDTO, pageRequest)).thenReturn(allResourceGroups);
> ```

How is this working when expected page size to service is 50000 ? 
___
*[`platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java` line 152 at r8](https://reviewable.io/reviews/harness/harness-core/50170#-NbJMo5lA880WUN2jYro:-NbJMo5lA880WUN2jYrp:b-kk57os) ([raw file](https://github.com/harness/harness-core/blob/bc83b39e425f0523b84809b37e5ec18e3271aabb/platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java#L152)):*
> ```Java
>     harnessResourceGroupResource.list(resourceGroupFilterDTO, accountIdentifier, pageRequest);
> 
>     verify(resourceGroupService, times(1)).listAll(resourceGroupFilterDTO, pageRequest);
> ```

Add pageSize = 50000 in verify.


<!-- Sent from Reviewable.io -->

2023-08-08 09:33 UTC, tiwaritejas commented
trigger uts

2023-08-08 09:34 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: 12 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 299 at r7](https://reviewable.io/reviews/harness/harness-core/50170#-NbInHTUE0RzNRw7wKpD:-NbJUj-s4J26cdT7Ga7-:bditbs9) ([raw file](https://github.com/harness/harness-core/blob/62f6814ad0b791d68b05d0023feb7ca40820c2ee/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L299)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

@tiwaritejas How is this going to fetch all RGs if we have pagination set from resource layer?
</blockquote></details>

Corrected the page request
___
*[`platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java` line 147 at r8](https://reviewable.io/reviews/harness/harness-core/50170#-NbJMega4fBGKLxAeYt7:-NbJUm4WEjDB9QTmfOUy:bqy3ncn) ([raw file](https://github.com/harness/harness-core/blob/bc83b39e425f0523b84809b37e5ec18e3271aabb/platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java#L147)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

How is this working when expected page size to service is 50000 ? 
</blockquote></details>

This UT was failing, rectified it now
___
*[`platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java` line 152 at r8](https://reviewable.io/reviews/harness/harness-core/50170#-NbJMo5lA880WUN2jYro:-NbJUou_6OY5kbrHUW30:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bc83b39e425f0523b84809b37e5ec18e3271aabb/platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImplTest.java#L152)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add pageSize = 50000 in verify.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-10 11:04 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: 12 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 129 at r9](https://reviewable.io/reviews/harness/harness-core/50170#-NbU6OrdBvyE5P-lBop3:-NbU6Ore94qKX2yJimPB:b-gzazo1) ([raw file](https://github.com/harness/harness-core/blob/0cab9d63edd8e5cf6f1b29eb92d11c9e3f9153e1/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L129)):*
> ```Java
> 
>     if (isEmpty(permittedResourceGroups)) {
>       throw new AccessDeniedException(
> ```

checkForAccessOrThrow will throw exception if no RG are permitted. check message is same as that.


<!-- Sent from Reviewable.io -->

2023-08-14 05:03 UTC, tiwaritejas commented
trigger uts

2023-08-14 05:21 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: 12 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java` line 129 at r9](https://reviewable.io/reviews/harness/harness-core/50170#-NbU6OrdBvyE5P-lBop3:-NbmURtlAykP7CDfm62I:bxayja0) ([raw file](https://github.com/harness/harness-core/blob/0cab9d63edd8e5cf6f1b29eb92d11c9e3f9153e1/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/remote/resource/HarnessResourceGroupResourceImpl.java#L129)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

checkForAccessOrThrow will throw exception if no RG are permitted. check message is same as that.
</blockquote></details>

Updated the error message.


<!-- Sent from Reviewable.io -->

2023-08-14 10:57 UTC, Jimit09Gandhi approved these changes
> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50170)* status: 12 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-14 10:58 UTC, merged