feat: [CDS-72777]: AWS CDK bootstrap step skeleton
harness/harness-core pull request #50193
Opened 2023-07-06 05:58 UTC by tmacari-harness

## Describe your changes
feat: [CDS-72777]: AWS CDK bootstrap step skeleton

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-06 06:07 UTC, tmacari-harness commented
trigger uts

2023-07-06 09:26 UTC, tmacari-harness commented
trigger uts

2023-07-06 09:29 UTC, tmacari-harness commented
trigger smartchecks

2023-07-10 11:45 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/awscdk/AwsCdkBootstrapStepPlanCreator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/50193#-NZzbePU9GbCPe-wmNP7:-NZzbePU9GbCPe-wmNP8:b-q8mkh8) ([raw file](https://github.com/harness/harness-core/blob/eb5d2a85bc38969da57d1f20154c1149e496789d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/awscdk/AwsCdkBootstrapStepPlanCreator.java#L44)):*
> ```Java
>   protected StepParameters getStepParameters(PlanCreationContext ctx, AwsCdkBootstrapStepNode stepNode) {
>     final StepParameters stepParameters = super.getStepParameters(ctx, stepNode);
>     AwsCdkBootstrapStepParameters awsCdkBootstrapStepParameters =
> ```

Is this required? Could you please check if we are able to make it work without this?


<!-- Sent from Reviewable.io -->

2023-07-10 11:50 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 1540 at r1](https://reviewable.io/reviews/harness/harness-core/50193#-NZzcbYn2jWbWOQnk0cV:-NZzcbYn2jWbWOQnk0cW:b-8kcv64) ([raw file](https://github.com/harness/harness-core/blob/eb5d2a85bc38969da57d1f20154c1149e496789d/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L1540)):*
> ```JSON
>       ],
>       "$schema": "http://json-schema.org/draft-07/schema#"
>     },
> ```

Please update static schema as well
[https://harness.atlassian.net/wiki/spaces/PIPE/pages/21420410346/Developer+Guide+for+Static+Schema](https://harness.atlassian.net/wiki/spaces/PIPE/pages/21420410346/Developer+Guide+for+Static+Schema)


<!-- Sent from Reviewable.io -->

2023-07-10 11:50 UTC, sahilhindwani-harness requested changes
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: Some of the checks are too old. 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-10 13:57 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkBootstrapStepInfo.java
> +  }
I think we need to add this class in _io/harness/cdng/pipeline/CDStepInfo.java_ also..

2023-07-11 04:21 UTC, tmacari-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkBootstrapStepInfo.java
> +  }
Done

2023-07-11 04:24 UTC, tmacari-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: 26 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/awscdk/AwsCdkBootstrapStepPlanCreator.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/50193#-NZzbePU9GbCPe-wmNP7:-N_2ArAG0Z7pLuaPvwAV:b7u8byf) ([raw file](https://github.com/harness/harness-core/blob/eb5d2a85bc38969da57d1f20154c1149e496789d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/awscdk/AwsCdkBootstrapStepPlanCreator.java#L44)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Is this required? Could you please check if we are able to make it work without this?
</blockquote></details>

We need step parameters in step. The same is done for other steps.
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 1540 at r1](https://reviewable.io/reviews/harness/harness-core/50193#-NZzcbYn2jWbWOQnk0cV:-N_2BHJfEhw0hxIw-Z86:b-d7bhn0) ([raw file](https://github.com/harness/harness-core/blob/eb5d2a85bc38969da57d1f20154c1149e496789d/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L1540)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please update static schema as well
[https://harness.atlassian.net/wiki/spaces/PIPE/pages/21420410346/Developer+Guide+for+Static+Schema](https://harness.atlassian.net/wiki/spaces/PIPE/pages/21420410346/Developer+Guide+for+Static+Schema)
</blockquote></details>

will do


<!-- Sent from Reviewable.io -->

2023-07-11 05:44 UTC, tmacari-harness commented
trigger feature-build

2023-07-11 05:54 UTC, tmacari-harness commented
trigger uts

2023-07-11 13:48 UTC, tmacari-harness commented
trigger ut9

2023-07-12 06:01 UTC, tmacari-harness commented
trigger uts

2023-07-12 06:02 UTC, tmacari-harness commented
trigger feature-build

2023-07-12 07:13 UTC, tmacari-harness commented
trigger uts

2023-07-12 07:35 UTC, tmacari-harness commented
trigger uts

2023-07-12 07:36 UTC, tmacari-harness commented
trigger feature-build

2023-07-17 06:01 UTC, tmacari-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: Some of the checks are too old. 30 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 1540 at r1](https://reviewable.io/reviews/harness/harness-core/50193#-NZzcbYn2jWbWOQnk0cV:-N_XR22t-bCFdf8lcyyz:bqf5mez) ([raw file](https://github.com/harness/harness-core/blob/eb5d2a85bc38969da57d1f20154c1149e496789d/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L1540)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

will do
</blockquote></details>

https://github.com/harness/harness-schema/pull/64


<!-- Sent from Reviewable.io -->

2023-07-17 06:20 UTC, tmacari-harness commented
trigger uts

2023-07-17 07:26 UTC, tmacari-harness commented
trigger uts

2023-07-17 10:31 UTC, tmacari-harness commented
trigger uts

2023-07-17 11:36 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsCdkBootstrapPluginInfoProvider.java` line 97 at r8](https://reviewable.io/reviews/harness/harness-core/50193#-N_YceFhCIZOKNAEn4-_:-N_YceFhCIZOKNAEn4-a:bzbx2gy) ([raw file](https://github.com/harness/harness-core/blob/dc8bb758bb8f4fb5b2bc45057d73eaa6b2d0677f/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsCdkBootstrapPluginInfoProvider.java#L97)):*
> ```Java
> 
>     environmentVariablesMap.put(
>         "PLUGIN_AWS_CDK_APP_PATH", getParameterFieldValue(awsCdkBootstrapStepInfo.getAppPath()));
> ```

Could you please create a environment variable constant file inside the cdk package and use it here.
It would help know which environment variables are being used inside this step or cdk as a general


<!-- Sent from Reviewable.io -->

2023-07-17 11:38 UTC, sahilhindwani-harness reviewed
> Reviewed 1 of 6 files at r2, 2 of 11 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 18 of 19 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: 30 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-17 11:40 UTC, sahilhindwani-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: 30 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-17 11:56 UTC, lovish1999 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: 30 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkBootstrapStepInfo.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/50193#gh-1258314613:-N_YhM2f9FDJQezWEnxa:b2ni9b3) ([raw file](https://github.com/harness/harness-core/blob/eb5d2a85bc38969da57d1f20154c1149e496789d/125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/AwsCdkBootstrapStepInfo.java#L92)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Done
</blockquote></details>

ok 


<!-- Sent from Reviewable.io -->

2023-07-17 11:56 UTC, lovish1999 reviewed
> Reviewed 6 of 24 files at r1, 1 of 6 files at r2, 2 of 11 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 18 of 19 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-17 11:57 UTC, lovish1999 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50193)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-07-17 12:09 UTC, tmacari-harness commented
trigger uts

2023-07-17 12:35 UTC, tmacari-harness commented
trigger ut0

2023-07-17 12:35 UTC, tmacari-harness commented
trigger ut2

2023-07-17 12:36 UTC, tmacari-harness commented
trigger ut6

2023-07-17 13:29 UTC, tmacari-harness commented
trigger ut7

2023-07-17 14:04 UTC, tmacari-harness commented
trigger ut0

2023-07-17 14:04 UTC, tmacari-harness commented
trigger ut2

2023-07-17 14:06 UTC, tmacari-harness commented
trigger ut7

2023-07-17 14:10 UTC, tmacari-harness commented
trigger ut2

2023-07-17 20:13 UTC, tmacari-harness commented
trigger ut7

2023-07-18 05:37 UTC, yogesh-chauhan approved these changes

2023-07-18 05:38 UTC, merged