fix: [CDS-73641]: Added a command step parameter for session timeout
harness/harness-core pull request #50269
Opened 2023-07-07 08:18 UTC by sarthakkasat

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-07 09:46 UTC, acasian-harness requested changes

2023-07-07 09:46 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStep.java
> +              stepParameters.getTimeout() != null ? stepParameters.getTimeout().getValue() : null);
why do we need to pass it here explicitly if the helper has the step parameters?

2023-07-07 09:46 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java
> +      @Nonnull Ambiance ambiance, @Nonnull CommandStepParameters commandStepParameters, String sessionTimeout) {
imho don't need an additional argument since the step params are passed

2023-07-07 09:46 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java
> +          ambiance, commandStepParameters, mergedEnvVariables, delegateConfig, sessionTimeout);
same

2023-07-07 09:46 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java
> +      return createRollbackWinRmTaskParameters(
same

2023-07-07 09:46 UTC, acasian-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java
> +      WinRmInfraDelegateConfigOutput winRmInfraDelegateConfigOutput, String sessionTimeout) {
same

2023-07-07 09:46 UTC, acasian-harness commented on 125-cd-nextgen/src/test/java/io/harness/cdng/ssh/CommandStepTest.java
can we add a test and ensure if step params have timeout > 30 it is being passed to delegate task params.

2023-07-07 09:46 UTC, acasian-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java
> +  Long sessionTimeout;
just `timeout` is fine

2023-07-07 10:15 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStep.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/50269#gh-1255557837:-NZjpydOB5xZbycThXma:bhbc3ug) ([raw file](https://github.com/harness/harness-core/blob/680535027377bfa39b9204f0e4cdc8807cf324e6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStep.java#L108)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why do we need to pass it here explicitly if the helper has the step parameters?
</blockquote></details>

executeCommandSpecParameter only has the spec from stepParameters which does not contain the timeout, hence i have added it as a separate param.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/ssh/CommandStepTest.java` line 0 at r1](https://reviewable.io/reviews/harness/harness-core/50269#gh-1255561254:-NZjqOZ_3PTUSzIiUgrS:bcetm1f) ([raw file](https://github.com/harness/harness-core/blob/680535027377bfa39b9204f0e4cdc8807cf324e6/125-cd-nextgen/src/test/java/io/harness/cdng/ssh/CommandStepTest.java#L0)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

can we add a test and ensure if step params have timeout > 30 it is being passed to delegate task params.
</blockquote></details>

Will add it


<!-- Sent from Reviewable.io -->

2023-07-10 05:46 UTC, yogesh-chauhan commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/50269#gh-1255562618:-NZyK8OOBredM9F6cKQs:b4qu50g) ([raw file](https://github.com/harness/harness-core/blob/680535027377bfa39b9204f0e4cdc8807cf324e6/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java#L52)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

just `timeout` is fine
</blockquote></details>

timeout can mean different things
- session timeout
- connection timeout
etc

https://golangbyexample.com/all-types-client-timeouts-http-tcp-udp-unix/

Session timeout helps us to identify that this value will be used for the session and should be larger value compared to other type of timeouts like tcp connect timeout which are typically in the range of few seconds


<!-- Sent from Reviewable.io -->

2023-07-10 05:53 UTC, yogesh-chauhan reviewed
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-10 08:00 UTC, acasian-harness approved these changes

2023-07-10 08:01 UTC, acasian-harness commented
> 



> _[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/50269#gh-1255562618:-NZyK8OOBredM9F6cKQs:b4qu50g) ([raw file](https://github.com/harness/harness-core/blob/680535027377bfa39b9204f0e4cdc8807cf324e6/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java#L52)):_
> 
> Previously, acasian-harness (Alexandru Casian) wrote…
> timeout can mean different things
> 
> * session timeout
> * connection timeout
>   etc
> 
> https://golangbyexample.com/all-types-client-timeouts-http-tcp-udp-unix/
> 
> Session timeout helps us to identify that this value will be used for the session and should be larger value compared to other type of timeouts like tcp connect timeout which are typically in the range of few seconds

@yogesh-chauhan but we don't differentiate those at the step level, i'm fine with sesssionTimeout naming, but since it's coming from same source, shouldn't be a problem.

2023-07-10 09:01 UTC, ivan-83 reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269)* status: Some of the checks are too old. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-10 09:18 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269)* status: Some of the checks are too old. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStep.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/50269#gh-1255557837:-NZz3rNG3hbyWKDPSGg7:burm3sn) ([raw file](https://github.com/harness/harness-core/blob/680535027377bfa39b9204f0e4cdc8807cf324e6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStep.java#L108)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Agree with @acasian-harness , The following logic should be done here in this class in a separate method, where take the get sessionTimout from stepParameters and set executeCommandStepParameters with sessionTimeout without passing sessionTimeout to underlying methods. 
</blockquote></details>

executeCommandStepParameters is the contract between users and us, we cannot change that, it can be done my mapping the executeCommandStepParameters in a separate class and adding timeout to that and passing that object to method, we can take that up separately.


<!-- Sent from Reviewable.io -->

2023-07-10 09:36 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269#-:-NZz95ymDMN2ggDGfQGf:bnfp4nl)* status: Some of the checks are too old. 3. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStep.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/50269#gh-1255557837:-NZz8_agCOMd-cJAfXZV:b-w58gu) ([raw file](https://github.com/harness/harness-core/blob/680535027377bfa39b9204f0e4cdc8807cf324e6/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/CommandStep.java#L108)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

executeCommandStepParameters is the contract between users and us, we cannot change that, it can be done my mapping the executeCommandStepParameters in a separate class and adding timeout to that and passing that object to method, we can take that up separately.
</blockquote></details>

@sarthakkasat we already did it,  by using @JsonIgnore annotation.

see
@JsonIgnore Set<String> secretOutputVariablesNames; 


<!-- Sent from Reviewable.io -->

2023-07-11 07:24 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269#-:-N_2pURH7Th7BiVLum1t:bnfp4nl)* status: 3 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-11 07:25 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-11 07:31 UTC, sarthakkasat commented
trigger uts

2023-07-11 08:41 UTC, sarthakkasat commented
trigger commonchecks

2023-07-11 08:53 UTC, sarthakkasat commented
trigger commonchecks

2023-07-11 08:53 UTC, sarthakkasat commented
trigger uts

2023-07-11 09:03 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269)* status: 2 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-11 09:25 UTC, sarthakkasat commented
trigger commonchecks

2023-07-11 09:53 UTC, tchaurasiya approved these changes

2023-07-11 09:53 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269)* status: 3 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-11 09:54 UTC, sarthakkasat commented
trigger review

2023-07-11 09:56 UTC, merged

2023-07-11 10:03 UTC, ivan-83 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50269#-:-N_3P-TG53acPSiqXIvn:bnfp4nl)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->