[fix]: [CDS-53173]: Fixing a bug for multi-service runtime input in template
harness/harness-core pull request #50351
Opened 2023-07-10 12:48 UTC by lovish1999

## Describe your changes
Currently for both multi service & environment cases, if we define these entities as runtime in the template and try to use the template in a pipeline and fix the values for these entities inside the pipeline, then the pipeline is not updated (shown) as a referring entity for that service/environment. Fixed this bug. It was occuring as we are not creating children of ServicesYaml 
if it's value was an expression. Now we are creating a children for it also. Then at template side, we have added the code to handle the cases separately when multi-services are used. Same is done for multi-environment cases. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-10 13:39 UTC, lovish1999 commented
trigger uts

2023-07-10 16:34 UTC, brijeshdhakar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50351)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServicesYaml.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-VcJaBHFxjMJo8FUD:-N_-VcJaBHFxjMJo8FUE:bi90qkc) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServicesYaml.java#L56)):*
> ```Java
>         children.add(VisitableChild.builder().value(serviceYamlV2).fieldName("values").build());
>       }
>     } else {
> ```

We should check if the value is <+input>. Normal expressions will not be handled here.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-bplK5ioKC8ayC6Cq:-N_-bplK5ioKC8ayC6Cr:b-pmou10) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java#L69)):*
> ```Java
>           */
>           fullQualifiedDomainName = VisitorParentPathUtils.getFullQualifiedDomainName(contextMap);
>           metadata.put(PreFlightCheckMetadata.YAML_TYPE, YamlTypes.ENVIRONMENT_REF);
> ```

I think YAML_TYPE does not sound good name for this key. Maybe something like IDENTIFIER_REF_KEY or YAML_IDENTIFIER_REF or YAML_IDENTIFIER_REF_KEY?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-VqWF7TDT01wVmuFX:-N_-VqWF7TDT01wVmuFY:bg7hhbc) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java#L67)):*
> ```Java
>       }
>     } else {
>       EnvironmentYamlV2 environmentYamlV2 =
> ```

Same: We should check if the value is <+input>. Normal expressions will not be handled here.


<!-- Sent from Reviewable.io -->

2023-07-10 16:37 UTC, brijeshdhakar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50351)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 260 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-eKUI7yg3cBx2mSN9:-N_-eKUI7yg3cBx2mSNA:bwo69ei) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L260)):*
> ```Java
>             }
>             YamlNode childYamlNode = YamlNodeUtils.goToPathUsingFqn(yamlNode, completeFqnForReferredEntity);
>             for (YamlNode element : childYamlNode.asArray()) {
> ```

Can we connect on this? I think first we should check if element.isArray() is true.


<!-- Sent from Reviewable.io -->

2023-07-11 12:32 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50351)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServicesYaml.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-VcJaBHFxjMJo8FUD:-N_3w2p6D2sv9GsmdT7k:bb7m07t) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServicesYaml.java#L56)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We should check if the value is <+input>. Normal expressions will not be handled here.
</blockquote></details>

okay
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-bplK5ioKC8ayC6Cq:-N_3w3b-2C0NFnk-kfIA:bb7m07t) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java#L69)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think YAML_TYPE does not sound good name for this key. Maybe something like IDENTIFIER_REF_KEY or YAML_IDENTIFIER_REF or YAML_IDENTIFIER_REF_KEY?
</blockquote></details>

okay
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-VqWF7TDT01wVmuFX:-N_3w4mg8ecInFiR_WqX:bb7m07t) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java#L67)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Same: We should check if the value is <+input>. Normal expressions will not be handled here.
</blockquote></details>

okay
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 260 at r1](https://reviewable.io/reviews/harness/harness-core/50351#-N_-eKUI7yg3cBx2mSN9:-N_3w6aKDO17JwwIF8ov:bb7m07t) ([raw file](https://github.com/harness/harness-core/blob/7a154a67db9bac03875f8b0fc3b957f6757b17f4/template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L260)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Can we connect on this? I think first we should check if element.isArray() is true.
</blockquote></details>

okay


<!-- Sent from Reviewable.io -->

2023-07-12 11:28 UTC, lovish1999 commented
trigger uts

2023-07-12 11:56 UTC, lovish1999 commented
trigger uts

2023-07-12 13:18 UTC, lovish1999 commented
trigger uts

2023-07-12 16:20 UTC, lovish1999 commented
trigger uts

2023-07-13 07:12 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50351)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-14 07:13 UTC, yogesh-chauhan requested changes
Lets write UTs for all classes here

2023-07-14 07:13 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +    if (parentPath.isPresent() && parentPath.get().contains("services")) {
can you give an example of the parentPath in case of templates/pipelines ?

2023-07-14 07:13 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java
> +    if (parentPath.isPresent() && parentPath.get().contains("environments")) {
use field name constants

2023-07-14 07:13 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java
> +    } else if (ParameterField.isNotNull(values) && NGExpressionUtils.isRuntimeField(values.getExpressionValue())) {
null check not needed

2023-07-14 07:13 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java
> +              .environmentRef(ParameterField.createExpressionField(true, "<+input>", null, true))
reuse input variable, same as servicesYaml

2023-07-14 07:13 UTC, yogesh-chauhan commented on template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java
> +              throw new RuntimeException(e);
add more context here

2023-07-14 07:13 UTC, yogesh-chauhan commented on template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java
> +            }
lets extract out in a method

2023-07-14 07:49 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java
> +    } else if (ParameterField.isNotNull(values) && NGExpressionUtils.isRuntimeField(values.getExpressionValue())) {
ok

2023-07-14 07:49 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentsYaml.java
> +              .environmentRef(ParameterField.createExpressionField(true, "<+input>", null, true))
ok

2023-07-14 07:49 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServicesYaml.java
> +    } else if (ParameterField.isNotNull(values) && NGExpressionUtils.isRuntimeField(values.getExpressionValue())) {
ok

2023-07-14 07:50 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServicesYaml.java
> +              .serviceRef(ParameterField.createExpressionField(true, "<+input>", null, true))
ok

2023-07-14 07:50 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentYamlV2VisitorHelper.java
> +    if (parentPath.isPresent() && parentPath.get().contains("environments")) {
ok

2023-07-14 07:55 UTC, lovish1999 commented on template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java
> +              throw new RuntimeException(e);
ok

2023-07-14 08:00 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +    if (parentPath.isPresent() && parentPath.get().contains("services")) {
ok

2023-07-14 15:13 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +      if (serviceYamlV2.getServiceRef().isExpression()) {
is it a possible to get serviceYamlV2.getServiceRef().isExpression() == true, in case of multi service ?

2023-07-17 12:37 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +      if (serviceYamlV2.getServiceRef().isExpression()) {
yes, we are adding it in ServicesYaml.

2023-07-17 20:06 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/beans/ServiceEntityVisitorHelperV2.java
> +    if (parentPath.isPresent() && parentPath.get().contains("services")) {
As per our discussion offline, you are right. Stage can have identifier as "services" and that would then may result in error. So, I have changed the checking condition to - The element at end of linked list should be "values"

2023-07-17 20:07 UTC, lovish1999 commented on template-service/service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java
> +            }
Not possible, as that results in a method having 8-9 parameters.

2023-07-17 20:15 UTC, lovish1999 commented
trigger uts

2023-07-17 21:15 UTC, lovish1999 commented
trigger uts

2023-07-18 04:29 UTC, lovish1999 commented
trigger messagecheck

2023-07-18 04:59 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 6 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50351)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-18 07:34 UTC, lovish1999 commented
trigger review

2023-07-18 09:12 UTC, merged