feat:[CDS-73836]: Capability and validation changes for github app
harness/harness-core pull request #50386
Opened 2023-07-11 09:23 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-24 08:53 UTC, yogesh-chauhan requested changes

2023-07-24 09:11 UTC, sourabh-awashti commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +               .equals(GithubHttpAuthenticationType.USERNAME_AND_TOKEN);
done

2023-07-24 09:11 UTC, sourabh-awashti commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +               .equals(GithubHttpAuthenticationType.USERNAME_AND_TOKEN);
done

2023-07-24 16:19 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/GithubPackagesRequestResponseMapper.java
> +        } else if (httpDTO.getType() == GithubHttpAuthenticationType.GITHUB_APP) {
done

2023-07-24 16:20 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/GitConnectionNGCapabilityChecker.java
> +    log.info("Capability check using scm service");
done

2023-07-24 16:20 UTC, sourabh-awashti commented on 932-connector-task/src/main/java/io/harness/connector/task/git/ScmConnectorMapperDelegate.java
> +public class ScmConnectorMapperDelegate {
done

2023-07-24 16:20 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/GitConnectionNGCapabilityChecker.java
>      String accountId = delegateConfiguration.getAccountId();
done

2023-07-24 16:20 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/GitConnectionNGCapabilityChecker.java
> +    scmDelegateClient.processScmRequest(c -> scmServiceClient.listBranches(scmConnector, SCMGrpc.newBlockingStub(c)));
done

2023-07-24 16:20 UTC, sourabh-awashti commented on 932-connector-task/src/main/java/io/harness/connector/task/git/GitHubAppAuthenticationHelper.java
> +  @Inject GithubService githubService;
done

2023-07-24 16:20 UTC, sourabh-awashti commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/scm/GitCapabilityHelper.java
> +    GitConnectionNGCapability.GitConnectionNGCapabilityBuilder gitConnectionNGCapability =
done

2023-07-24 16:21 UTC, sourabh-awashti commented
trigger uts

2023-07-24 16:29 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +    } else if (githubAppAuthentication) {
I'm a bit confused about this flow. When it is used? Since optimizedFilesFetch is already checking for github app, this means that this branch will never reach if FF OPTIMIZED_GIT_FETCH_FILES, is this expected or I'm missing something?

2023-07-24 17:19 UTC, sourabh-awashti commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 324 at r2](https://reviewable.io/reviews/harness/harness-core/50386#gh-1271812784:-Na7uJPt1k86yuOfXBsZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e4a48482b21091d9dfd59202425f0029a934eaf0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L324)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we just use the isGithubAppAuth method from this class ?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-07-24 17:19 UTC, sourabh-awashti commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 494 at r3](https://reviewable.io/reviews/harness/harness-core/50386#gh-1272494971:-Na7uM5S8o6sR7APLHvO:bhep3vm) ([raw file](https://github.com/harness/harness-core/blob/9b4b4a6746078a9164fe83368a2e1ae3fa14179a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L494)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'm a bit confused about this flow. When it is used? Since optimizedFilesFetch is already checking for github app, this means that this branch will never reach if FF OPTIMIZED_GIT_FETCH_FILES, is this expected or I'm missing something?
</blockquote></details>

optimized file is checking for github app in api access , but this flow is used when we provide github app details in authentication , not in api access


<!-- Sent from Reviewable.io -->

2023-07-24 17:20 UTC, sourabh-awashti commented
*[`932-connector-task/src/main/java/io/harness/connector/task/git/GitHubAppAuthenticationHelper.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/50386#gh-1271851900:-Na7uYoe8UCH3h5bhO2c:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e4a48482b21091d9dfd59202425f0029a934eaf0/932-connector-task/src/main/java/io/harness/connector/task/git/GitHubAppAuthenticationHelper.java#L32)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be singleton
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-07-25 04:45 UTC, sourabh-awashti commented
trigger uts

2023-07-25 07:19 UTC, yogesh-chauhan reviewed
> Reviewed 9 of 20 files at r1, 6 of 12 files at r2, 4 of 5 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50386)* status: 37 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-25 07:19 UTC, yogesh-chauhan submitted a review, later dismissed

2023-07-25 07:37 UTC, sourabh-awashti commented
trigger uts

2023-07-25 10:46 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50386)* status: 37 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-25 15:06 UTC, abosii-harness approved these changes

2023-07-25 15:07 UTC, sourabh-awashti commented
trigger review

2023-07-25 15:24 UTC, merged