feat: [PLG-2219]: Don't run for licenses created this month & add credits in-line for new licenses
harness/harness-core pull request #50413
Opened 2023-07-11 20:48 UTC by thomas-grasman

## Describe your changes
When creating new licenses, we need build credits to be provisioned immediately, so we will now add them at the time of license creation.

To avoid duplicating the free credits for new accounts, we will skip any licenses that have been created this month.
Starting the following month, the new licenses will be picked up with the rest of the licenses, and be treated the same as all others.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-11 22:03 UTC, thomas-grasman commented
trigger uts

2023-07-11 23:35 UTC, neelam-harness approved these changes

2023-07-12 00:36 UTC, Xin-Harness requested changes

2023-07-12 00:36 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/services/DefaultLicenseServiceImpl.java
> +                                  .quantity(FREE_CI_CREDITS_QUANTITY)
Here would need add more fields(6 fields in total) as all the Credit fields are mandatory.

2023-07-12 00:44 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java
> +  private static Calendar getStartOfNextMonth() {
If I understand correctly the reason it call getStartOfNextMonth is because even the iterator start on this months but the nextIterations is generated for this month. Am I correct? I am a bit confused for the name and what it does.

2023-07-13 10:08 UTC, kapil-harness reviewed
IMO this logic is complicated and all we need to do is to run an iterator [for every lets say 10/60 mins] and go through each account in that cluster and create new credits for an account for that month if its not already created.

@thomas-grasman I think we discussed it.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50413#-:-N_DhMj9-lQE3lSOPJP4:b-re7hi3)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/50413#-N_DfyZ75l097rc0xE4n:-N_DfyZ75l097rc0xE4o:b-f84ett) ([raw file](https://github.com/harness/harness-core/blob/da0273397616ce38e94c7116750bf2a6e5cb030f/930-ng-license-manager/src/main/java/io/harness/credit/schedular/CreditProvisioningIteratorHandler.java#L65)):*
> ```Java
>   public void handle(CIModuleLicense entity) {
>     try {
>       if (entity.getStartTime() > getStartOfMonth().getTimeInMillis()) {
> ```

nit: this if clause makes more sense outside the try catch clause


<!-- Sent from Reviewable.io -->

2023-07-31 15:34 UTC, thomas-grasman commented
trigger uts

2023-08-28 00:02 UTC, closed without merging