feat: [CDS-74215]: Add Advisors for StepGroup and its Child Steps
harness/harness-core pull request #50466
Opened 2023-07-12 13:05 UTC by utkarshchoubey-harness

Add Advisors for StepGroup and its Child Steps

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-12 13:08 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-12 13:56 UTC, mohitg0795 commented
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 544 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_9NrI20fhZQOL8WaKE:-N_9NrI379zo7CHong30:b54k6ul) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L544)):*
> ```Java
>     for (int i = levelsList.size() - 1; i >= 0; i--) {
>       Level level = levelsList.get(i);
>       if (level.getStepType().getType().equals("STEP_GROUP")) {
> ```

possible to use this constant from some constant class? If not already created, we can create a new enum class from where we can start using constants.


<!-- Sent from Reviewable.io -->

2023-07-12 13:57 UTC, mohitg0795 commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/CommonAdviserTypes.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_9O-LR9FuNEEgth8M5:-N_9O-LR9FuNEEgth8M6:b-e1ss9i) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/CommonAdviserTypes.java#L20)):*
> ```Java
>   ON_FAIL_ROLLBACK,
>   ON_FAIL_PIPELINE_ROLLBACK,
>   RETRY_STEPGROUP_START,
> ```

Doesn't "RETRY_STEP_GROUP" in itself is a valid adviser name? What does "START" mean here?


<!-- Sent from Reviewable.io -->

2023-07-13 05:04 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/CommonAdviserTypes.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_9O-LR9FuNEEgth8M5:-N_CcdN-5COZwNovGPrZ:b-adhn4t) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/CommonAdviserTypes.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Doesn't "RETRY_STEP_GROUP" in itself is a valid adviser name? What does "START" mean here?
</blockquote></details>

+1, I don't think start is required


<!-- Sent from Reviewable.io -->

2023-07-13 06:53 UTC, sahilhindwani-harness commented
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 539 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_D0iKk5xizZYl-KZ9w:-N_D0iKk5xizZYl-KZ9x:bv9owhe) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L539)):*
> ```Java
>   }
> 
>   public Optional<Level> getClosestStepGroupLevelFromAmbiance(Ambiance ambiance) {
> ```

We can reuse the function for fetching step group level directly.


<!-- Sent from Reviewable.io -->

2023-07-13 06:54 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupChildStepsAdviserWithRollback.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_D0moGAOqOYxe1zX0K:-N_D0moGAOqOYxe1zX0L:b-9b8b7h) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupChildStepsAdviserWithRollback.java#L54)):*
> ```Java
> @Slf4j
> @OwnedBy(PIPELINE)
> public class RetryStepGroupChildStepsAdviserWithRollback implements Adviser {
> ```

Most of the code seems to be duplicate of the Retry adviser. let' move the common code to abstract class and then re-use.


<!-- Sent from Reviewable.io -->

2023-07-13 08:28 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-13 09:27 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-14 09:13 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-18 07:21 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/AbstractRetryAdviserWithRollback.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bs3KE6ioQq59CBE2t:-N_bs3KE6ioQq59CBE2u:bii2m96) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/AbstractRetryAdviserWithRollback.java#L8)):*
> ```Java
>  */
> 
> package io.harness.advisers.retry;
> ```

revert as it is not required.


<!-- Sent from Reviewable.io -->

2023-07-18 07:22 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 16 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bs7md-oU9IBtRka-N:-N_bs7meCU-ATY-8_a4y:b-69z5a4) ([raw file](https://github.com/harness/harness-core/blob/09e79fbc89aff743199a3b6d643b919810938b7c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L16)):*
> ```Java
> 
> import io.harness.advisers.CommonAdviserTypes;
> import io.harness.advisers.pipelinerollback.OnFailPipelineRollbackAdviser;
> ```

revert as it is not required


<!-- Sent from Reviewable.io -->

2023-07-18 07:28 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java` line 174 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_btYSGClGFwm06I3Dy:-N_btYSGClGFwm06I3Dz:bqba87u) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java#L174)):*
> ```Java
>       KryoSerializer kryoSerializer, YamlField currentField) {
>     List<AdviserObtainment> adviserObtainmentList = new ArrayList<>();
>     List<FailureStrategyConfig> stepGroupFailureStrategies =
> ```

Maybe we can use common code for steps.


<!-- Sent from Reviewable.io -->

2023-07-18 07:34 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java` line 174 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_btYSGClGFwm06I3Dy:-N_busdj8ejf1lAHnqi6:b2y0bux) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java#L174)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Maybe we can use common code for steps.
</blockquote></details>

Also, we should move this code to PlanCreatorsCommon and use as much as possible over there.


<!-- Sent from Reviewable.io -->

2023-07-18 07:34 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bv1URClfWHD-1-DN4:-N_bv1URClfWHD-1-DN5:b9wa1a0) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java#L57)):*
> ```Java
>     boolean isStepGroupRetry = false;
>     isStepGroupRetry =
>         (StepCategory.STEP_GROUP.name()).equals(AmbianceUtils.obtainCurrentLevel(ambiance).getStepType().getType());
> ```

nit: Can be combined to one statement



_Code quote:_
```Java
    boolean isStepGroupRetry = false;
    isStepGroupRetry =
        (StepCategory.STEP_GROUP.name()).equals(AmbianceUtils.obtainCurrentLevel(ambiance).getStepType().getType());
```


<!-- Sent from Reviewable.io -->

2023-07-18 07:35 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bv1URClfWHD-1-DN4:-N_bv9arAX25v2jiwfbE:b-hifyfg) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java#L57)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Can be combined to one statement
</blockquote></details>

to get stepType we can use `getCurrentStepType` function


<!-- Sent from Reviewable.io -->

2023-07-18 07:36 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bv1URClfWHD-1-DN4:-N_bvRfu828hrkQVpzx3:ba0ln8k) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java#L57)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

to get stepType we can use `getCurrentStepType` function
</blockquote></details>

Also, please use equal across category


<!-- Sent from Reviewable.io -->

2023-07-18 07:57 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 23 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/CommonAdviserTypes.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_9O-LR9FuNEEgth8M5:-N_bztdYC47Pg6J1Y5Z-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/CommonAdviserTypes.java#L20)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1, I don't think start is required
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bv1URClfWHD-1-DN4:-N_c-6vbETY0vWimTQa6:bwb4u50) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java#L57)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Also, please use equal across category
</blockquote></details>

use type only
___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 539 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_D0iKk5xizZYl-KZ9w:-N_c-Blo8xr-n9kMAEPg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L539)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We can reuse the function for fetching step group level directly.
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 544 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_9NrI20fhZQOL8WaKE:-N_c-By_2PsvHbIHSDBh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L544)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

possible to use this constant from some constant class? If not already created, we can create a new enum class from where we can start using constants.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-18 11:00 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 23 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java` line 174 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_btYSGClGFwm06I3Dy:-N_ce6zv6s9zBaQni1sK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java#L174)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Also, we should move this code to PlanCreatorsCommon and use as much as possible over there.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/AbstractRetryAdviserWithRollback.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bs3KE6ioQq59CBE2t:-N_cAiIc054S3ffm-d5X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b25301186669473d88ad7f750997033d55627630/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/AbstractRetryAdviserWithRollback.java#L8)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

revert as it is not required.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 16 at r6](https://reviewable.io/reviews/harness/harness-core/50466#-N_bs7md-oU9IBtRka-N:-N_cAdNBCI5K_KbP7tNA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09e79fbc89aff743199a3b6d643b919810938b7c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L16)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

revert as it is not required
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupChildStepsAdviserWithRollback.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/50466#-N_D0moGAOqOYxe1zX0K:-N_cAgIABfDGe8O_4v1R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db4033813cf198c7213673d9588792e865187d83/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupChildStepsAdviserWithRollback.java#L54)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Most of the code seems to be duplicate of the Retry adviser. let' move the common code to abstract class and then re-use.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-18 12:03 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-18 12:11 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java` line 191 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_cuO4aAXucy7hNSnpk:-N_cuO4aAXucy7hNSnpl:b-bsgdkm) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java#L191)):*
> ```Java
>   }
> 
>   public void validateRetrySGFailureAction(RetrySGFailureActionConfig retryAction) {
> ```

Can we extract out common code between validateRetryFailureAction and this?


<!-- Sent from Reviewable.io -->

2023-07-18 15:44 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java` line 55 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_deyne1iLLzvskYyAd:-N_deyne1iLLzvskYyAe:b-1s2lc) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java#L55)):*
> ```Java
>         interrupt.getNodeExecutionId(), NodeProjectionUtils.fieldsForRetryInterruptHandler);
>     Ambiance ambiance = nodeExecution.getAmbiance();
>     boolean isStepGroupRetry = false;
> ```

nit: this and below line can be combined into one


<!-- Sent from Reviewable.io -->

2023-07-18 15:45 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java` line 67 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_df5-yDesryjmOFk1f:-N_df5-yDesryjmOFk1g:b-olorp7) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java#L67)):*
> ```Java
> 
>     // If it is stepGroup then retries are supported.
>     if (!isStepGroupRetry && ExecutionModeUtils.isParentMode(nodeExecution.getMode())) {
> ```

For other revieweres, We might need to mark steps as retried , we will check it once and add that in another PR.


<!-- Sent from Reviewable.io -->

2023-07-18 15:45 UTC, sahilhindwani-harness reviewed
> Reviewed 1 of 7 files at r1, 1 of 9 files at r4, 2 of 9 files at r5, 10 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 11 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-19 06:42 UTC, archit-harness requested changes
> Reviewed 1 of 7 files at r1, 1 of 9 files at r5, 1 of 11 files at r6, 1 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java` line 191 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_cuO4aAXucy7hNSnpk:-N_gcKjp-AFsVHIS9q-B:bi2uauj) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java#L191)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we extract out common code between validateRetryFailureAction and this?
</blockquote></details>

can we add validation that onRetryFailure fields are not supported with this type? or introduce new spec for RetrySGFailureActionConfig which is better
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java` line 171 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_gsP79C23cLknoF6nf:-N_gsP79C23cLknoF6ng:b-ftp55a) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java#L171)):*
> ```Java
>   }
> 
>   public List<AdviserObtainment> getAdviserObtainmentForFailureStrategy(
> ```

We have same in StepGroupPMSPlanCreatorV2, how its different?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java` line 48 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_grKAtDl7X37ylxIAr:-N_grKAtDl7X37ylxIAs:b2se950) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java#L48)):*
> ```Java
>     if (advisingEvent.getRetryCount() >= retryAdviserRollbackParameters.getRetryCount()) {
>       return AdviserResponse.newBuilder().build();
>     }
> ```

Here if retry count is high, we should send fail advise as we discussed if retry counts is more we need to fail it like mark failed
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java` line 63 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_gjEMz7LmwbyJJpaer:-N_gjEMz7LmwbyJJpaes:bcs5vac) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java#L63)):*
> ```Java
>         && advisingEvent.getFromStatus() != INTERVENTION_WAITING;
>     RetryAdviserRollbackParameters parameters = extractParameters(advisingEvent);
>     return canAdvise && advisingEvent.getRetryCount() < parameters.getRetryCount();
> ```

why we are not checking failureType? 

if (parameters != null && !isEmpty(failureTypesList)) {  
  return canAdvise && !Collections.disjoint(parameters.getApplicableFailureTypes(), failureTypesList);  
}
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/PlanCreatorUtilsCommon.java` line 121 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_gsZiS0rbCf-AR-Kx7:-N_gsZiS0rbCf-AR-Kx8:b-dc8es1) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/PlanCreatorUtilsCommon.java#L121)):*
> ```Java
> 
>   public Map<FailureStrategyActionConfig, Collection<FailureType>>
>   getPriorityWiseMergedActionMapForFailureStrategiesForStepStageAndStepGroup(
> ```

why this needs to be added separately?


<!-- Sent from Reviewable.io -->

2023-07-19 06:47 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java` line 63 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_gjEMz7LmwbyJJpaer:-N_gtqoh7SxMmq_nC5nf:b-3sr6vu) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are not checking failureType? 

if (parameters != null && !isEmpty(failureTypesList)) {  
  return canAdvise && !Collections.disjoint(parameters.getApplicableFailureTypes(), failureTypesList);  
}
</blockquote></details>

yes, we will need to. Nice catch!


<!-- Sent from Reviewable.io -->

2023-07-19 09:51 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 9 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java` line 191 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_cuO4aAXucy7hNSnpk:-N_hT-5QB0Gf0MN8Q-5N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java#L191)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add validation that onRetryFailure fields are not supported with this type? or introduce new spec for RetrySGFailureActionConfig which is better
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java` line 67 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_df5-yDesryjmOFk1f:-N_hT2raE3P4kK2GSmkh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/RetryInterruptHandler.java#L67)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

For other revieweres, We might need to mark steps as retried , we will check it once and add that in another PR.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java` line 63 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_gjEMz7LmwbyJJpaer:-N_hSz916nQjYkr4qbsu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java#L63)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

yes, we will need to. Nice catch!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-19 11:04 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 14 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java` line 171 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_gsP79C23cLknoF6nf:-N_hoSkg-KDwk13m29vV:b-d0wgkb) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java#L171)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We have same in StepGroupPMSPlanCreatorV2, how its different?
</blockquote></details>

Done StepGroupPMSPlanCreatorV2 is internally calling StepGroupPMSPlanCreator only
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java` line 48 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_grKAtDl7X37ylxIAr:-N_hkwUv1jO1t4YrPacs:b-rz1f1t) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryStepGroupAdvisor.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Here if retry count is high, we should send fail advise as we discussed if retry counts is more we need to fail it like mark failed
</blockquote></details>

Done , I'll be creating a subsequent pr to restrict the retries count, also this is just for fail safe, code wont reach here, as can advise will only give false
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/PlanCreatorUtilsCommon.java` line 121 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_gsZiS0rbCf-AR-Kx7:-N_hoZHHDwPTWWlBLaq_:bq67lt5) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/PlanCreatorUtilsCommon.java#L121)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this needs to be added separately?
</blockquote></details>

Done.  We created generic functions to get priorityWiseMergedActionMap for FailureStrategies for stage, step and stepgroup


<!-- Sent from Reviewable.io -->

2023-07-19 11:05 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-20 04:52 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 9 files at r5, 1 of 11 files at r6, 2 of 5 files at r7, 1 of 1 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 12 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-20 05:35 UTC, utkarshchoubey-harness commented
trigger messagecheck

2023-07-20 06:03 UTC, archit-harness reviewed
> Reviewed 1 of 9 files at r4, 2 of 9 files at r5, 7 of 11 files at r6, 1 of 5 files at r7, 1 of 1 files at r9, 7 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java` line 191 at r9](https://reviewable.io/reviews/harness/harness-core/50466#-N_cuO4aAXucy7hNSnpk:-N_lqg999qfTqHqm3cjD:b-s9b9tq) ([raw file](https://github.com/harness/harness-core/blob/d5f1400446b3c0d4a698809f70aa42074efe4287/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/FailureStrategiesUtils.java#L191)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@utkarshchoubey-harness replace this spec in the class with new config as existing one contains action, which is not applicable


public class RetrySGFailureActionConfig implements FailureStrategyActionConfig {  
  @ApiModelProperty(allowableValues = RETRY\_STEP\_GROUP) NGFailureActionType type \= NGFailureActionType.RETRY\_STEP\_GROUP;  
  
  @NotNull @JsonProperty("spec") RetryFailureSpecConfig specConfig;  
}


<!-- Sent from Reviewable.io -->

2023-07-20 06:36 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-20 06:54 UTC, archit-harness reviewed
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-20 06:55 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 10 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-20 06:57 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-20 08:03 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-20 08:06 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 14368 at r12](https://reviewable.io/reviews/harness/harness-core/50466#-N_mKU7C1yliCdg12eJ-:-N_mKU7C1yliCdg12eJ0:bvad5zv) ([raw file](https://github.com/harness/harness-core/blob/01fd9a5f7730ede41ac3bf05a371ee4a606ec471/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L14368)):*
> ```JSON
>       "$schema": "http://json-schema.org/draft-07/schema#"
>     },
>     "RetryStepGroupFailureSpecConfig": {
> ```

You will need to update static schema too.


<!-- Sent from Reviewable.io -->

2023-07-20 08:37 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-20 08:45 UTC, sahilhindwani-harness approved these changes
> Reviewed 4 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50466)* status: 5 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-07-20 09:34 UTC, merged