fix: [CDS-74042]: closed all log streams for all command handlers
harness/harness-core pull request #50473
Opened 2023-07-12 14:01 UTC by vitsafronovici

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-12 14:29 UTC, vitsafronovici commented
trigger uts

2023-07-13 08:40 UTC, vitsafronovici commented
trigger uts

2023-07-13 12:18 UTC, vitsafronovici commented
trigger uts

2023-07-13 13:30 UTC, vitsafronovici commented
trigger uts

2023-07-14 08:04 UTC, acasian-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmInitCommandHandler.java
> -    executor.getLogCallback().saveExecutionLog("Command finished with status " + status, LogLevel.INFO, status);
why we are removing this statement?

2023-07-14 09:59 UTC, vitsafronovici commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java
> +        closeLogStream(executor.getLogCallback(), result);
```
result = executor.copyFiles(context);
        closeLogStream(executor.getLogCallback(), result);

        if (result == CommandExecutionStatus.FAILURE) {
          String artifactId = sshCommandTaskParameters.getArtifactDelegateConfig().getIdentifier();
          log.error("Failed to copy artifact with id: " + artifactId);
          throw NestedExceptionUtils.hintWithExplanationException(FAILED_TO_COPY_ARTIFACT_HINT,
              format(FAILED_TO_COPY_ARTIFACT_HINT_EXPLANATION, artifactId, copyCommandUnit.getDestinationPath()),
              new SshCommandExecutionException(format(FAILED_TO_COPY_ARTIFACT, artifactId)));
        }
        return ExecuteCommandResponse.builder().status(result).build();
```
we close with success or failure before throw or return

2023-07-14 10:01 UTC, vitsafronovici commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java
> +              throw NestedExceptionUtils.hintWithExplanationException(
we don't close for throw because it is caught one level up and closesWithError

2023-07-14 10:05 UTC, vitsafronovici commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java
> +  default void closeLogStreamWithSuccess(LogCallback logCallback) {
don't get your idea, but it is calling this method with commandExecutionStatus=success argument
```
  default void closeLogStream(LogCallback logCallback, CommandExecutionStatus commandExecutionStatus) {
    String msg = "Command finished with status " + commandExecutionStatus;
    closeLogStream(logCallback, commandExecutionStatus, msg);
  }
```

At the end this msg will close the log: "Command finished with status SUCCESS"

2023-07-14 10:21 UTC, acasian-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java
> +  default void closeLogStreamWithSuccess(LogCallback logCallback) {
<img width="983" alt="Screenshot 2023-07-14 at 13 20 35" src="https://github.com/harness/harness-core/assets/64784875/e7674ffc-0e89-4138-bc88-3cb6bf4be256">
see the line which was removed

2023-07-14 10:27 UTC, ivan-83 requested changes
> Reviewed 2 of 11 files at r1, 4 of 12 files at r2, 8 of 10 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50473)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/50473#-N_Itw3Q9rxzEWFMh-J4:-N_Itw3Q9rxzEWFMh-J5:b-ylmiuz) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java#L54)):*
> ```Java
>   }
> 
>   default void closeLogStreamWithError(LogCallback logCallback) {
> ```

Minor - closeLogStreamWithError >> closeLogStreamWithFailure
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/50473#gh-1263426590:-N_Iuj2u-wxTkliV5KoM:b-lx0wri) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java#L59)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

EMPTY
</blockquote></details>

qq, why do we need an empty message when we are already using "Command finished with status " msg?

Can we rely on an empty or "Command finished with status " msg?   It's important to close the stream, not add additional msg in logs.
  
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/50473#-N_IsjeaCs_3DTWYcrIt:-N_IsjeaCs_3DTWYcrIu:bpxj6aw) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java#L49)):*
> ```Java
> 
> @Slf4j
> public class WinRmShellScriptTaskNG extends AbstractDelegateRunnableTask {
> ```

QQ, do we need to close the stream on success flow in this handler?


<!-- Sent from Reviewable.io -->

2023-07-14 10:33 UTC, ivan-83 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50473)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/50473#-N_IxQJE23zQYAZ4wd-9:-N_IxQJE23zQYAZ4wd-A:b-l5a137) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java#L34)):*
> ```Java
>       Map<String, Object> taskContext);
> 
>   default void closeLogStream(LogCallback logCallback, CommandExecutionStatus commandExecutionStatus, String msg) {
> ```

These log stream methods could be moved to separate utility class.


<!-- Sent from Reviewable.io -->

2023-07-14 12:27 UTC, vitsafronovici reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50473)* status: 18 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/50473#-N_IxQJE23zQYAZ4wd-9:-N_JLbKu0hqCiQqXACgw:bdirlfy) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java#L34)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

These log stream methods could be moved to separate utility class.
</blockquote></details>

I think only ssh/winrm swimlane uses executors for logging streams, in other swimlanes it is closed in their manner
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/50473#-N_Itw3Q9rxzEWFMh-J4:-N_JM034EpyBg2SSAov4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java#L54)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - closeLogStreamWithError >> closeLogStreamWithFailure
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/50473#gh-1263426590:-N_JM39J5FXIYYaS8mfU:bosb8at) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/command/CommandHandler.java#L59)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, why do we need an empty message when we are already using "Command finished with status " msg?

Can we rely on an empty or "Command finished with status " msg?   It's important to close the stream, not add additional msg in logs.
  

</blockquote></details>

we need empty because, some executors already log this msg ''Command finished with status XXX", but in some cases the log is in RUNNING status, so we need to close it and also not to double the log message
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/50473#-N_IsjeaCs_3DTWYcrIt:-N_JK9a23dreJATROrId:b-bw2xke) ([raw file](https://github.com/harness/harness-core/blob/3930832ef354b8f6ae0fd4eb8f73b28722690ae2/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java#L49)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

QQ, do we need to close the stream on success flow in this handler?
</blockquote></details>

we need to provide a SUCCESS or FAILURE msg, this is termination of log streaming


<!-- Sent from Reviewable.io -->

2023-07-14 12:45 UTC, acasian-harness approved these changes

2023-07-14 13:46 UTC, vitsafronovici commented
trigger review

2023-07-14 13:51 UTC, merged