feat: [PL-39821]: add cache for hashicorp vault app role token
harness/harness-core pull request #50471
Opened 2023-07-12 13:41 UTC by bhavya181

## Describe your changes
add cache for hashicorp vault app role token

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-13 11:59 UTC, nishantsaini20 requested changes
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 304 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_DyQmKAHTIlrnDdWry:-N_DyQmKAHTIlrnDdWrz:b-7begl1) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L304)):*
> ```Java
>     if (null == token) {
>       VaultAppRoleLoginResult vaultAppRoleLoginResult = getVaultAppRoleLoginResult(vaultConfig);
>       hashicorpVaultTokenCacheHelper.putInAppRoleTokenCache(vaultConfig.getIdentifier(), vaultAppRoleLoginResult);
> ```

Two vaults can have same identifier. Key should include scopeIdentifiers as well.
___
*[`931-encryption-service/src/java/io/harness/encryptors/utils/BUILD.bazel` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_DzGnlBQUlV0MtsTNH:-N_DzGnlBQUlV0MtsTNI:b-c4xnpp) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/utils/BUILD.bazel#L23)):*
> ```Starlark
> )
> 
> run_analysis_per_module()
> ```

Is this file generated by using build cleaner tool? https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21178155054/Build+Cleaner+101


<!-- Sent from Reviewable.io -->

2023-07-14 19:33 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_Kt73-3xspYFxlFtF8:-N_Kt73-3xspYFxlFtF9:boqbqks) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L106)):*
> ```Java
> 
>   public void invalidateAppRoleToken(String vaultId) {
>     if (null != vaultId) {
> ```

Use isNotEmpty instead of null 


<!-- Sent from Reviewable.io -->

2023-07-17 11:20 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 304 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_DyQmKAHTIlrnDdWry:-N_Y_84aAt-nkAdlEM1A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L304)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Two vaults can have same identifier. Key should include scopeIdentifiers as well.
</blockquote></details>

Done.
___
*[`931-encryption-service/src/java/io/harness/encryptors/utils/BUILD.bazel` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_DzGnlBQUlV0MtsTNH:-N_Y_9nMCwvE1L43k0OR:b-c1kixu) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/utils/BUILD.bazel#L23)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is this file generated by using build cleaner tool? https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21178155054/Build+Cleaner+101
</blockquote></details>

yes, used this generator
___
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_Kt73-3xspYFxlFtF8:-N_Y_Cgw5NvVy6iEi4nG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L106)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Use isNotEmpty instead of null 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-17 16:57 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 302 at r2](https://reviewable.io/reviews/harness/harness-core/50471#-N_ZmK5n0G6a3COCNhK6:-N_ZmK5n0G6a3COCNhK7:b-96zob5) ([raw file](https://github.com/harness/harness-core/blob/a57095a215f0ba9ae5e9df6dcbb41491182ccf66/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L302)):*
> ```Java
>   String getVaultAppRoleToken(VaultConfig vaultConfig) {
>     String token = hashicorpVaultTokenCacheHelper.getAppRoleToken(vaultConfig);
>     if (null == token) {
> ```

This should be notEmpty check


<!-- Sent from Reviewable.io -->

2023-07-17 16:59 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/50471#-N_ZmaR6-gz_emDFsu49:-N_ZmaR6-gz_emDFsu4A:bbbiqsa) ([raw file](https://github.com/harness/harness-core/blob/a57095a215f0ba9ae5e9df6dcbb41491182ccf66/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L48)):*
> ```Java
>   @Value
>   @Builder
>   private static class VaultAppRoleTokenCacheKey {
> ```

You should also have Equals&HashCode for this object 


<!-- Sent from Reviewable.io -->

2023-07-17 17:41 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/50471#-N_ZwO65Ai374NZ1idsf:-N_ZwO65Ai374NZ1idsg:b-lp63ok) ([raw file](https://github.com/harness/harness-core/blob/a57095a215f0ba9ae5e9df6dcbb41491182ccf66/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L71)):*
> ```Java
>             @Override
>             public long expireAfterCreate(
>                 @NonNull VaultAppRoleTokenCacheKey key, @NonNull VaultAppRoleTokenCacheValue graph, long currentTime) {
> ```

Why graph?


<!-- Sent from Reviewable.io -->

2023-07-19 19:14 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_KswNP9pSOmT5QUoxB:-N_KswNP9pSOmT5QUoxC:boqbqks) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L87)):*
> ```Java
> 
>   public void putInAppRoleTokenCache(String vaultId, VaultAppRoleLoginResult vaultAppRoleLoginResult) {
>     if (null != vaultId && null != vaultAppRoleLoginResult && null != vaultAppRoleLoginResult.getClientToken()) {
> ```

Use isNotEmpty instead of null 


<!-- Sent from Reviewable.io -->

2023-07-19 19:14 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_Kt6RJ8VEw0s9oIQfj:-N_Kt6RJ8VEw0s9oIQfk:boqbqks) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L98)):*
> ```Java
> 
>   public String getAppRoleToken(String vaultId) {
>     if (null != vaultId) {
> ```

Use isNotEmpty instead of null 


<!-- Sent from Reviewable.io -->

2023-08-03 12:15 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 10 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 302 at r2](https://reviewable.io/reviews/harness/harness-core/50471#-N_ZmK5n0G6a3COCNhK6:-NavJfi5Alr8iFBddZ-0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a57095a215f0ba9ae5e9df6dcbb41491182ccf66/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L302)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This should be notEmpty check
</blockquote></details>

Done.
___
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/50471#-N_ZwO65Ai374NZ1idsf:-NavJiAAB_sLrRELCI68:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a57095a215f0ba9ae5e9df6dcbb41491182ccf66/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L71)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why graph?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-03 12:23 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 10 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/50471#-N_ZmaR6-gz_emDFsu49:-NavLdyB5QiyV6uNoz2r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a57095a215f0ba9ae5e9df6dcbb41491182ccf66/931-encryption-service/src/java/io/harness/encryptors/utils/HashicorpVaultTokenCacheHelper.java#L48)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

You should also have Equals&HashCode for this object 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-03 16:39 UTC, piyush-harness commented
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/platform/k8s/K8SRunnerModule.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NawGDQr0zwGPI3IUJ2_:-NawGDQr0zwGPI3IUJ2a:bg0bnsa) ([raw file](https://github.com/harness/harness-core/blob/bceda6c70c6723dac536cf381777c9a85d35b883/260-delegate/src/main/java/io/harness/delegate/app/modules/platform/k8s/K8SRunnerModule.java#L27)):*
> ```Java
>      install(new DelegateDecryptionModule());
>      */
>     // install(new ApiClientModule());
> ```

Why changes are needed here?


<!-- Sent from Reviewable.io -->

2023-08-03 16:41 UTC, piyush-harness commented
*[`931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NawGXDN8Rwcn2lMEvgR:-NawGXDN8Rwcn2lMEvgS:brhm5zk) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java#L119)):*
> ```Java
>   public void cleanup() {
>     vaultRestClientFactoryMockedStatic.close();
>     ngVaultTaskHelperMockedStatic.close();
> ```

Why removal?


<!-- Sent from Reviewable.io -->

2023-08-03 16:45 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 253 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NawHQGCAO9hGwTisqNA:-NawHQGCAO9hGwTisqNB:bbg24fl) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L253)):*
> ```Java
>   }
> 
>   private String getToken(VaultConfig vaultConfig) {
> ```

What happened with this method??


<!-- Sent from Reviewable.io -->

2023-08-03 16:45 UTC, piyush-harness reviewed
> Reviewed 2 of 7 files at r1, 1 of 6 files at r2, 6 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 304 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_DyQmKAHTIlrnDdWry:-N_KGA0N2V5gFkg-lhi9:bybcpx) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L304)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Two vaults can have same identifier. Key should include scopeIdentifiers as well.
</blockquote></details>

+1 Couple of more points:

Write logic of getting key in one single method and use that to PUT/GET to/from cache. 
Check for Valid Result before  updating in cache


<!-- Sent from Reviewable.io -->

2023-08-04 04:09 UTC, nishantsaini20 requested changes
> Reviewed 7 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-vault-beans/src/test/io/harness/helpers/vault/BUILD.bazel` line 10 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NayikII4MHmp-2BqO5M:-NayikII4MHmp-2BqO5N:b-9ipp08) ([raw file](https://github.com/harness/harness-core/blob/bceda6c70c6723dac536cf381777c9a85d35b883/931-vault-beans/src/test/io/harness/helpers/vault/BUILD.bazel#L10)):*
> ```Starlark
> load("//:tools/bazel/GenTestRules.bzl", "run_tests")
> 
> java_library(
> ```

Is this a new file or this is moved to different location?


<!-- Sent from Reviewable.io -->

2023-08-04 07:30 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 304 at r1](https://reviewable.io/reviews/harness/harness-core/50471#-N_DyQmKAHTIlrnDdWry:-NazRcFFB3eCkj6HRFIC:bgjp97h) ([raw file](https://github.com/harness/harness-core/blob/d3e8783bad1a1288bfbe4d4b80a680a1d533a065/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L304)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

+1 Couple of more points:

Write logic of getting key in one single method and use that to PUT/GET to/from cache. 
Check for Valid Result before  updating in cache
</blockquote></details>

This is already done, there is only one method which gets and put to cache 
___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java` line 253 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NawHQGCAO9hGwTisqNA:-NazRNhk9556dl93LfmF:byx540k) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/931-encryption-service/src/java/io/harness/encryptors/clients/HashicorpVaultEncryptor.java#L253)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

What happened with this method??
</blockquote></details>

This getToken method is same as present in NGVaultTask Helper, that's why used that method, so there will be only one method where we put caching
___
*[`931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NawGXDN8Rwcn2lMEvgR:-NazRi8vArtKyMyAENdq:bobnyxh) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java#L119)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why removal?
</blockquote></details>

removed by mistake, added back
___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/platform/k8s/K8SRunnerModule.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NawGDQr0zwGPI3IUJ2_:-NazRzhF7nIydigquc0C:b-xcd6oc) ([raw file](https://github.com/harness/harness-core/blob/bceda6c70c6723dac536cf381777c9a85d35b883/260-delegate/src/main/java/io/harness/delegate/app/modules/platform/k8s/K8SRunnerModule.java#L27)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why changes are needed here?
</blockquote></details>

reverted back, changed by mistake
___
*[`931-vault-beans/src/test/io/harness/helpers/vault/BUILD.bazel` line 10 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NayikII4MHmp-2BqO5M:-NazRqSc42t1nUFxRSCD:b-zcwpxd) ([raw file](https://github.com/harness/harness-core/blob/bceda6c70c6723dac536cf381777c9a85d35b883/931-vault-beans/src/test/io/harness/helpers/vault/BUILD.bazel#L10)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is this a new file or this is moved to different location?
</blockquote></details>

HashicorpCacheHelper is added here, that' why it got created 


<!-- Sent from Reviewable.io -->

2023-08-04 07:31 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-vault-beans/src/test/io/harness/helpers/vault/BUILD.bazel` line 10 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-NayikII4MHmp-2BqO5M:-NazSMOx4PQyHs92sfG5:bd76ale) ([raw file](https://github.com/harness/harness-core/blob/bceda6c70c6723dac536cf381777c9a85d35b883/931-vault-beans/src/test/io/harness/helpers/vault/BUILD.bazel#L10)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

HashicorpCacheHelper is added here, that' why it got created 
</blockquote></details>

Its a test file, no test was present earlier in this folder


<!-- Sent from Reviewable.io -->

2023-08-04 12:20 UTC, nishantsaini20 requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java` line 344 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb-ULnLAu3-xniFcKso:-Nb-ULnLAu3-xniFcKsp:b-sl5zdk) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java#L344)):*
> ```Java
>   }
> 
>   private String getToken(BaseVaultConfig vaultConfig) {
> ```

Why is this removed?


<!-- Sent from Reviewable.io -->

2023-08-04 12:21 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java` line 344 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb-ULnLAu3-xniFcKso:-Nb-UWz_0SBw6xCTFxGv:bvs5ewf) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java#L344)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

Also are these changes tested for CG flow as well? CG flow should not be impacted by this and other changes in this PR.


<!-- Sent from Reviewable.io -->

2023-08-04 13:19 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 6 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java` line 344 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb-ULnLAu3-xniFcKso:-Nb-gljf4DS60hSvwIRX:bksxd2o) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java#L344)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Also are these changes tested for CG flow as well? CG flow should not be impacted by this and other changes in this PR.
</blockquote></details>

Its again the same getToken method, which is copied hee as well, I have remove all instances of that method and kept only one getToken method in NGVaultTaskHelper


<!-- Sent from Reviewable.io -->

2023-08-04 13:20 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 6 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java` line 344 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb-ULnLAu3-xniFcKso:-Nb-h0cSEn1jFPEGAqiL:b2y837g) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/930-delegate-tasks/src/main/java/software/wings/service/impl/security/SecretManagementDelegateServiceImpl.java#L344)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Its again the same getToken method, which is copied hee as well, I have remove all instances of that method and kept only one getToken method in NGVaultTaskHelper
</blockquote></details>

for CG, it has been tested enableCache is coming as false, so no changes in CG flow


<!-- Sent from Reviewable.io -->

2023-08-04 15:57 UTC, piyush-harness commented
*[`931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java` line 95 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0GAs72YMyUiUyg08n:-Nb0GAs72YMyUiUyg08o:blooawb) ([raw file](https://github.com/harness/harness-core/blob/6583341b3aa9b6b80c96604cbd67bdfb6299cdfc/931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java#L95)):*
> ```Java
>     long expiryInSeconds = MAX_CACHE_EXPIRY_DURATION_IN_SECONDS;
>     if (expiresIn != 0) {
>       expiryInSeconds = (long) ((double) expiresIn * TOKEN_CACHE_EXPIRY_THRESHOLD);
> ```

Can we just do Long.valueOf?


<!-- Sent from Reviewable.io -->

2023-08-04 15:57 UTC, piyush-harness commented
*[`931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java` line 97 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0G8UMCfMFnWmA5tFR:-Nb0G8UMCfMFnWmA5tFS:b5n1e59) ([raw file](https://github.com/harness/harness-core/blob/bceda6c70c6723dac536cf381777c9a85d35b883/931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java#L97)):*
> ```Java
>     if (expiresIn != 0) {
>       expiryInSeconds = (long) ((double) expiresIn * TOKEN_CACHE_EXPIRY_THRESHOLD);
>       expiryInSeconds = Math.min(expiryInSeconds, MAX_CACHE_EXPIRY_DURATION_IN_SECONDS);
> ```

Why this logic was removed?


<!-- Sent from Reviewable.io -->

2023-08-04 16:00 UTC, piyush-harness requested changes
> Reviewed 2 of 10 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java` line 73 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0GigG2-6R6VDPSi-k:-Nb0GigG2-6R6VDPSi-l:b-m27nif) ([raw file](https://github.com/harness/harness-core/blob/6583341b3aa9b6b80c96604cbd67bdfb6299cdfc/931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java#L73)):*
> ```Java
> 
>   @Before
>   public void setup() throws IllegalAccessException {
> ```

is this needed?
___
*[`931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0GmhZ94U__np1vrPj:-Nb0GmhZ94U__np1vrPk:bb7kry6) ([raw file](https://github.com/harness/harness-core/blob/6583341b3aa9b6b80c96604cbd67bdfb6299cdfc/931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java#L94)):*
> ```Java
>     hashicorpVaultEncryptor = new HashicorpVaultEncryptor(HTimeLimiter.create(executorService));
>     vaultRestClientFactoryMockedStatic = mockStatic(VaultRestClientFactory.class);
> ```

Remove empty line


<!-- Sent from Reviewable.io -->

2023-08-07 08:32 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 1 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java` line 73 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0GigG2-6R6VDPSi-k:-NbE76O31JJUoStVZp3-:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/6583341b3aa9b6b80c96604cbd67bdfb6299cdfc/931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java#L73)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

removed
___
*[`931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0GmhZ94U__np1vrPj:-NbE77S9-PTTq3lncAN-:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/6583341b3aa9b6b80c96604cbd67bdfb6299cdfc/931-encryption-service/src/test/io/harness/encryptors/clients/HashicorpVaultEncryptorTest.java#L94)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Remove empty line
</blockquote></details>

removed
___
*[`931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java` line 97 at r4](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0G8UMCfMFnWmA5tFR:-NbE6ubmC1eQXoj-VcnH:bdtguae) ([raw file](https://github.com/harness/harness-core/blob/bceda6c70c6723dac536cf381777c9a85d35b883/931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java#L97)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why this logic was removed?
</blockquote></details>

It has been decided that we don't have any upper limit on cache timing, we will respect what vault gives us, kapil and you had decided that.
___
*[`931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java` line 95 at r5](https://reviewable.io/reviews/harness/harness-core/50471#-Nb0GAs72YMyUiUyg08n:-NbE6o328w7qgEsO1Swf:bh6zaps) ([raw file](https://github.com/harness/harness-core/blob/6583341b3aa9b6b80c96604cbd67bdfb6299cdfc/931-vault-beans/src/java/io/harness/helpers/vault/HashicorpVaultTokenCacheHelper.java#L95)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we just do Long.valueOf?
</blockquote></details>

Long.valueof() does not convert double value to Long


<!-- Sent from Reviewable.io -->

2023-08-07 19:39 UTC, piyush-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-08 08:53 UTC, nishantsaini20 submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-08-08 10:55 UTC, bhavya181 commented
trigger uts

2023-08-08 12:35 UTC, bhavya181 commented
trigger uts

2023-08-08 12:42 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50471)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-08 13:54 UTC, bhavya181 commented
trigger ut0

2023-08-08 15:14 UTC, merged