feat: [PL-37951]: Update delegate HB to redis
harness/harness-core pull request #50554
Opened 2023-07-14 08:01 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-26 05:13 UTC, jennyjames21 commented
trigger uts

2023-07-26 05:23 UTC, jennyjames21 commented
trigger uts

2023-07-26 06:21 UTC, AnupamIO commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java
> +public class DelegateHeartBeatSyncFromRedis implements Runnable {
I think we can have this class in 420-delegate-service instead of 400-rest. Please check

2023-07-26 06:22 UTC, AnupamIO commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java
> +      if (delegateRecordsToBulkUpdate > BULK_OPERATION_MAX) {
I think bulk_opration_max of 5000 will not work here, if 15k delegates are there in above while loop, bulkOperation will have 15k entries and all 15k will be inserted in one go. Please check

2023-07-26 18:21 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java
> +public class DelegateHeartBeatSyncFromRedis implements Runnable {
updated

2023-07-26 18:22 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatSyncFromRedis.java
> +      if (delegateRecordsToBulkUpdate > BULK_OPERATION_MAX) {
Line no: 61.62 takes care of anything less than 5000

2023-07-26 18:23 UTC, jennyjames21 commented
trigger uts

2023-07-27 23:57 UTC, xingchi-jin requested changes

2023-07-27 23:57 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java
> +                                                             .field(DelegateKeys.disconnected)
is it possible that, the del in DB is disconnected, for example, this del lost connection to manager for few min, but later it starts connect again.
In this case, the redis will not sync back to DB and mark it as connected again.

2023-07-27 23:57 UTC, xingchi-jin commented on 420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java
> +      if (delegateRecordsToBulkUpdate > BULK_OPERATION_MAX) {
should this be inside the while loop ?

2023-07-28 05:14 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java
> +                                                             .field(DelegateKeys.disconnected)
yes good point, i will remove disconnected field

2023-07-28 05:32 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java
> +      if (delegateRecordsToBulkUpdate > BULK_OPERATION_MAX) {
No, it's for any number below 5000. Here is the summary
- "delegateRecordsToBulkUpdate" var defined and initialized as zero outside while loop 
- Inside the while loop, it keeps iterating delegate records one by one and add the update query to bulk operation, and increment delegateRecordsToBulkUpdate ++  
- if ever reached 5000 inside the loop, reset "delegateRecordsToBulkUpdate" var to zero  and commit/execute a bulk operation for batch query update.
- So inside the loop we only commit/execute if ever reached 5000, If below that number do one batch commit/execute in the end which is outside of while loop

2023-07-28 05:36 UTC, jennyjames21 commented
trigger uts

2023-07-28 23:00 UTC, raghuAtWings requested changes

2023-07-28 23:00 UTC, raghuAtWings commented on 420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java
> +public class DelegateHeartBeatSyncFromRedis implements Runnable {
there is no unit test for it. Please add one

2023-08-04 04:52 UTC, jennyjames21 commented
trigger uts

2023-08-04 04:52 UTC, jennyjames21 commented on 420-delegate-service/src/main/java/io/harness/redis/DelegateHeartBeatSyncFromRedis.java
> +public class DelegateHeartBeatSyncFromRedis implements Runnable {
uodated

2023-08-04 19:48 UTC, jennyjames21 commented
trigger uts

2023-08-04 20:23 UTC, jennyjames21 commented
trigger uts

2023-08-04 20:45 UTC, jennyjames21 commented
trigger uts

2023-08-08 19:07 UTC, raghuAtWings approved these changes

2023-08-09 05:47 UTC, xingchi-jin approved these changes

2023-08-09 05:49 UTC, merged