[feat]: [IAC-767]: Add JEXL to IACM
harness/harness-core pull request #50558
Opened 2023-07-14 09:08 UTC by nassergonzalez

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-14 09:49 UTC, nassergonzalez commented
trigger uts

2023-07-14 09:50 UTC, allofthesepeople requested changes
as discussed, 

- Caching for performance is premature at this stage.
- If consistency of values across pipeline is required then we should investigate how other functors do this, or investigate how to handle with non in-mem solution.

2023-07-14 09:50 UTC, allofthesepeople commented on 310-iacm-manager/contracts/src/main/java/io/harness/beans/functors/IacmFunctor.java
> +          "Inappropriate usage of 'iacm' functor. The format should be <+iacm.workspace.name_of_the_output_to_use>",
typo for update to the namespace:
```
The format should be <+workspace.workspace_identifier.name_of_the_output_to_use>",
```

2023-07-14 09:50 UTC, allofthesepeople commented on 310-iacm-manager/contracts/src/main/java/io/harness/beans/functors/IacmFunctor.java
> +    if (lruCache.contains(cacheKey)) {
I think caching is premature and potentially err-prone at this stage.
- how many requests does it actually save? 
- how is it invalidated? 
- how long does it live for?
- what're the memory constraints? 
- how many instances are requests spread across?
- what's the behaviour if single workspace has more inputs than cache can hold?
- how many of these caches will actually be created? If 1/workspace this will not scale; if 1/node there is little benefit.

2023-07-14 10:01 UTC, nassergonzalez commented on 310-iacm-manager/contracts/src/main/java/io/harness/beans/functors/IacmFunctor.java
> +    if (lruCache.contains(cacheKey)) {
I can remove it but basically
- Each parameter is going to be called n+4 times where n is the number of times the parameter is in the pipeline. I thought that just to avoid those many calls to the service would be a good reason to implement this
- Because is a LRU where the key is the execution, each new execution will go and call the service at least once so there is no risk to have problems of the data becoming stale between executions. And inside the same execution they will be the same thanks to the cache
- Same as the point before, the ttl is just per execution and they will eventually be rotated from the cache so we won't have a memory problem
- We are using 10% of the memory that we have available RN in prod. If memory would be an issue we could add an env variable to control the size of the cache
- Currently we have 3 pods running in prod. Even if we are unlucky and the request go all to different pods, we will still save 1 call to the service in the worst case scenario with no problem about data consistency
- nothing, we will just go and do the request. The flow is: Is the output in the cache, if not, go and retrieve it from the server. Also the cache saves as key the pipeline execution/stage execution and we return all the outputs as a single object so it does not matter how many outputs a workspace has this is just a single entry in the cache
- there will be a cache per pod

2023-07-14 13:37 UTC, nassergonzalez commented
trigger uts

2023-07-14 14:19 UTC, allofthesepeople submitted a review, later dismissed

2023-07-14 16:09 UTC, nassergonzalez commented
trigger uts

2023-07-17 08:50 UTC, nassergonzalez commented
trigger uts

2023-07-17 11:54 UTC, nassergonzalez commented
trigger uts

2023-07-18 08:10 UTC, nassergonzalez commented
trigger ut7

2023-07-18 15:24 UTC, allofthesepeople approved these changes

2023-07-18 15:25 UTC, merged