feat: [CI-8134]: removed set -x from run command
harness/harness-core pull request #50560
Opened 2023-07-14 09:41 UTC by devkimittal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-14 09:43 UTC, devkimittal commented
k8s execution
<img width="1312" alt="Screenshot 2023-07-14 at 2 35 08 PM" src="https://github.com/harness/harness-core/assets/99166403/3929746f-61ef-4244-832e-adc8894f4c2d">


vm execution
<img width="1312" alt="Screenshot 2023-07-14 at 2 28 39 PM" src="https://github.com/harness/harness-core/assets/99166403/42abda5f-b7ba-4d4f-91a3-c513536fb76a">

2023-07-14 09:53 UTC, devkimittal commented
trigger uts

2023-07-14 09:54 UTC, devkimittal commented
tested for windows as well.

2023-07-21 05:13 UTC, devkimittal commented
trigger uts

2023-07-25 07:58 UTC, devkimittal commented
trigger uts

2023-07-25 11:16 UTC, devkimittal commented
trigger uts

2023-07-25 12:48 UTC, raghavharness requested changes

2023-07-25 12:48 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +  public static String appendPrintCommand(String command) {
`prependPrintCommand` makes more sense

2023-07-25 12:48 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +    }
Do we need to do this ? Can we set it similar to this ?
https://github.com/harness/harness-core/blob/66192457ce3cbae00683e75e34a9c8463a560a8c/product/ci/addon/tasks/run.go#L155

2023-07-25 13:07 UTC, devkimittal commented
trigger uts

2023-07-25 14:28 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +    }
we have to do for each line in java. I tried doing it in one command but doesn't work when new line is there

2023-07-27 07:44 UTC, devkimittal commented
trigger uts

2023-07-27 07:46 UTC, devkimittal commented
powershell
<img width="1312" alt="Screenshot 2023-07-27 at 12 39 18 PM" src="https://github.com/harness/harness-core/assets/99166403/b68927b8-925a-4f99-a23d-9248c6ff6567">

pwsh
<img width="1312" alt="Screenshot 2023-07-27 at 12 40 41 PM" src="https://github.com/harness/harness-core/assets/99166403/ad3a0c30-f474-4b7a-aaaa-00dde7ce05c7">

sh and bash
<img width="1312" alt="Screenshot 2023-07-27 at 12 48 20 PM" src="https://github.com/harness/harness-core/assets/99166403/95480ad1-7752-471c-aa9d-2d3f5842f245">

python
<img width="1312" alt="Screenshot 2023-07-27 at 12 50 46 PM" src="https://github.com/harness/harness-core/assets/99166403/83c9b37c-427c-4ba4-8db5-ff518263efa4">

2023-07-27 09:39 UTC, raghavharness requested changes

2023-07-27 11:08 UTC, devkimittal commented
triger uts

2023-07-27 11:08 UTC, devkimittal commented
trigger uts

2023-07-27 11:17 UTC, raghavharness approved these changes

2023-07-27 11:56 UTC, merged