[fix]: [CDS-72208]: Separate Get Api for Overrides V2 TF Provider
harness/harness-core pull request #50571
Opened 2023-07-14 11:50 UTC by lovish1999

## Describe your changes
Separate Get Api for Overrides V2 TF Provider

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-14 14:47 UTC, tchaurasiya requested changes

2023-07-14 14:47 UTC, tchaurasiya commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +      nickname = "getServiceOverridesV2tfProvider")
nit: getServiceOverridesV2TfProvider - camel case Tf

2023-07-14 14:47 UTC, tchaurasiya commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +                "Returns the Service Overrides by the identifier and scope derived from accountId, org identifier and project identifier")
nit: Returns the Service Override - singular

2023-07-14 14:47 UTC, tchaurasiya commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +                "Returns the Service Overrides by the identifier and scope derived from accountId, org identifier and project identifier")
Lets annotate this api @Hidden

2023-07-14 14:47 UTC, tchaurasiya commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +        String yamlInternalFromSpec = JsonPipelineUtils.writeJsonString(spec);
Lets use io.harness.pms.yaml.YamlUtils

2023-07-17 03:56 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +                "Returns the Service Overrides by the identifier and scope derived from accountId, org identifier and project identifier")
It was same as the v1 get call. And it also looks correct because the single entity may contain multiple override variables. But I will make the change.

2023-07-17 03:58 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +                "Returns the Service Overrides by the identifier and scope derived from accountId, org identifier and project identifier")
ok

2023-07-17 03:59 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +      nickname = "getServiceOverridesV2tfProvider")
ok

2023-07-17 04:15 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +        String yamlInternalFromSpec = JsonPipelineUtils.writeJsonString(spec);
ok

2023-07-17 08:50 UTC, tchaurasiya submitted a review, later dismissed

2023-07-17 08:52 UTC, lovish1999 commented
trigger uts

2023-07-17 09:28 UTC, lovish1999 commented
trigger uts

2023-07-17 09:30 UTC, lovish1999 commented
trigger messagecheck

2023-07-17 09:54 UTC, lovish1999 commented
trigger uts

2023-07-17 17:59 UTC, yogesh-chauhan commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +  getV2(@Parameter(description = NGCommonEntityConstants.SERVICE_OVERRIDES_IDENTIFIER) @PathParam(
instead of getV2, lets call it getForTerraformProvider

2023-07-17 18:55 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
> +  getV2(@Parameter(description = NGCommonEntityConstants.SERVICE_OVERRIDES_IDENTIFIER) @PathParam(
Sure. I have other PRs in line. I can make this change there in order to avoid running UTs again.

2023-07-18 07:31 UTC, lovish1999 commented
trigger uts

2023-07-18 07:36 UTC, lovish1999 commented
trigger uts

2023-07-18 10:54 UTC, tchaurasiya approved these changes

2023-07-20 19:38 UTC, lovish1999 commented
trigger uts

2023-07-21 09:25 UTC, tchaurasiya approved these changes

2023-07-21 09:26 UTC, lovish1999 commented
trigger review

2023-07-21 09:29 UTC, merged