[fix]: [CDS-73264]: implementing handleProgress logic for Helm Deploy step
harness/harness-core pull request #50593
Opened 2023-07-15 21:05 UTC by markoharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-15 21:06 UTC, markoharness commented
trigger uts

2023-07-16 00:18 UTC, markoharness commented
trigger uts

2023-07-16 00:18 UTC, markoharness commented
trigger feature-build

2023-07-16 00:18 UTC, markoharness commented
trigger publish-delegate

2023-07-17 04:48 UTC, abosii-harness requested changes

2023-07-17 04:48 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
> +        executionSweepingOutputService.consume(ambiance, OutcomeExpressionConstants.HELM_DEPLOY_OUTCOME,
Should we use a different outcome in this case? What will happen when we would receive a response from delegate and save the same outcome once more?

2023-07-17 04:48 UTC, abosii-harness commented on 260-delegate/src/main/java/io/harness/progressStreamingTaskClient/ProgressStreamingTaskClient.java
> +public class ProgressStreamingTaskClient implements ILogStreamingTaskClient {
Any reasons why we need this class? Looks to me the same as LogStreamingTaskClient

2023-07-17 04:48 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +    iLogStreamingTaskClient.openStream(event);
Any reasons why we need to open a new stream?

2023-07-17 04:48 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +  public void sendTaskProgressUpdate() {
Wouldn't be better if this method would receive as argument progress data that need to be sent (and all other options if there any) instead of doing something like:
1. For each progress data create a new NGDelegateTaskProgressCallback with DelegateProgressData
2. Then call sendTaskProgressUpdate

2023-07-17 07:26 UTC, abosii-harness requested changes
Can we have these changes behind FF?

2023-07-17 07:46 UTC, markoharness commented on 260-delegate/src/main/java/io/harness/progressStreamingTaskClient/ProgressStreamingTaskClient.java
> +public class ProgressStreamingTaskClient implements ILogStreamingTaskClient {
We don't. I will remove it.

2023-07-17 07:47 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +    iLogStreamingTaskClient.openStream(event);
It has a purpose for the command unit UI logs presentation. Since progress data in this case will not be presented in UI it has no purpose. I will remove it.

2023-07-17 07:48 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +  public void sendTaskProgressUpdate() {
I will make the change

2023-07-17 07:48 UTC, markoharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
> +        executionSweepingOutputService.consume(ambiance, OutcomeExpressionConstants.HELM_DEPLOY_OUTCOME,
I will test this and if necessary will create a outcome with different name.

2023-07-17 13:53 UTC, markoharness commented
trigger uts

2023-07-17 13:56 UTC, markoharness commented
trigger feature-build

2023-07-17 13:56 UTC, markoharness commented
trigger publish-delegate

2023-07-17 14:05 UTC, abosii-harness approved these changes

2023-07-17 14:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +  public void sendTaskProgressUpdate(String taskId, String event, DelegateProgressData delegateTaskProgressData) {
nit: I guess taskId can be injected in constructor, I don't expect that taskId would change

2023-07-17 14:05 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/stepsdependency/constants/OutcomeExpressionConstants.java
> +  public final String HELM_DEPLOY_OUTCOME_UNFINISHED_STEP = "helmDeployOutcomeUnfinishedStep";
A better name here would be helmDeployRelease

2023-07-17 17:12 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +  public void sendTaskProgressUpdate(String taskId, String event, DelegateProgressData delegateTaskProgressData) {
made the change

2023-07-17 17:12 UTC, markoharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/stepsdependency/constants/OutcomeExpressionConstants.java
> +  public final String HELM_DEPLOY_OUTCOME_UNFINISHED_STEP = "helmDeployOutcomeUnfinishedStep";
made the change

2023-07-17 17:12 UTC, markoharness commented
trigger uts

2023-07-17 17:23 UTC, markoharness commented
trigger checkstylecodeformat pmd,codebasehash

2023-07-17 18:37 UTC, markoharness commented
trigger checkstylecodeformat,pmd,codebasehash,messagecheck,uts

2023-07-18 09:06 UTC, abosii-harness submitted a review, later dismissed

2023-07-18 09:06 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +          synchronized (delegateTaskProgressData) {
nit: this synchronized doesn't make sense here, you will always have only one instance of delegateTaskProgressData, synchronized is not required

2023-07-18 09:06 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +  private ILogStreamingTaskClient taskProgressStreamingTaskClient;
nit: I guess we can reuse logStreamingTaskClient

2023-07-18 09:38 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/progresstaskstreaming/NGDelegateTaskProgressCallback.java
> +          synchronized (delegateTaskProgressData) {
True. I already made the change, but i am also adding UTs so i will push the changes with the next commit.

2023-07-18 11:51 UTC, markoharness commented
trigger checkstylecodeformat,pmd,codebasehash,messagecheck,uts

2023-07-18 11:54 UTC, abosii-harness submitted a review, later dismissed

2023-07-18 11:57 UTC, archit-harness requested changes
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50593)* status: 37 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java` line 118 at r6](https://reviewable.io/reviews/harness/harness-core/50593#-N_cqniyAq_ZnqKAZ3zI:-N_cqniyAq_ZnqKAZ3zJ:b-lf5ii9) ([raw file](https://github.com/harness/harness-core/blob/3af02f63a7814be82d1bd17f3e73b1c10f7d42f1/125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java#L118)):*
> ```Java
>           nativeHelmDeployOutcomeBuilder.hasInstallUpgradeStarted(helmDeployProgressData.isHasInstallUpgradeStarted());
> 
>           executionSweepingOutputService.consume(ambiance, OutcomeExpressionConstants.HELM_DEPLOY_RELEASE_OUTCOME,
> ```

Is there any particular reason we are storing the data in sweeping output and not in cd collection? if the data is not being used by the customer we should store it in respective services
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java` line 156 at r6](https://reviewable.io/reviews/harness/harness-core/50593#-N_cqyJ1-_39cLHYAuuI:-N_cqyJ1-_39cLHYAuuJ:b-2w5kad) ([raw file](https://github.com/harness/harness-core/blob/3af02f63a7814be82d1bd17f3e73b1c10f7d42f1/125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java#L156)):*
> ```Java
>             helmRollbackStepParams.getHelmRollbackFqn() + "." + OutcomeExpressionConstants.HELM_DEPLOY_OUTCOME));
>     if (!helmDeployOptionalOutput.isFound()) {
>       helmDeployOptionalOutput = executionSweepingOutputService.resolveOptional(ambiance,
> ```

you can get data from the respective cd collection based on fields


<!-- Sent from Reviewable.io -->

2023-07-18 12:00 UTC, harshjain12 submitted a review, later dismissed

2023-07-18 12:21 UTC, markoharness commented
trigger checkstylecodeformat,pmd,codebasehash,messagecheck,uts

2023-07-19 07:03 UTC, markoharness commented
trigger checkstylecodeformat,pmd,codebasehash,messagecheck,uts

2023-07-19 07:26 UTC, archit-harness reviewed
> Reviewed 1 of 9 files at r4, 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50593)* status: 34 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java` line 118 at r6](https://reviewable.io/reviews/harness/harness-core/50593#-N_cqniyAq_ZnqKAZ3zI:-N_h0rTA4GiRvEL7oiyF:b-kt4u5o) ([raw file](https://github.com/harness/harness-core/blob/3af02f63a7814be82d1bd17f3e73b1c10f7d42f1/125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java#L118)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

This is the logic we have already implemented before and now just reused it. Is there any strong reason why this approach should not be used?
</blockquote></details>

done, discussed offline, cd team will do in another pr so marking it done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java` line 156 at r6](https://reviewable.io/reviews/harness/harness-core/50593#-N_cqyJ1-_39cLHYAuuI:-N_h1kPa8u93CDQxuBpB:budilla) ([raw file](https://github.com/harness/harness-core/blob/3af02f63a7814be82d1bd17f3e73b1c10f7d42f1/125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java#L156)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

This is the logic we have already implemented before and now just reused it. Is there any strong reason why this approach should not be used?
</blockquote></details>

done, same as above


<!-- Sent from Reviewable.io -->

2023-07-19 07:27 UTC, archit-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50593)* status: 34 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-19 09:18 UTC, markoharness commented
trigger ut0,ut1,ut2,ut3,ut4

2023-07-19 11:10 UTC, markoharness commented
trigger ut1,ut2

2023-07-19 11:16 UTC, abosii-harness approved these changes

2023-07-19 11:20 UTC, yogesh-chauhan approved these changes

2023-07-19 11:22 UTC, raghavharness approved these changes

2023-07-19 11:24 UTC, yogesh-chauhan commented
trigger review

2023-07-19 12:59 UTC, merged