feat: [CDS-50312]: helm changes: Get Node information via API from CD Deployment Step for CI
harness/harness-core pull request #50609
Opened 2023-07-17 06:56 UTC by namantalaycha10

## Describe your changes
helm changes: Get Node information via API from CD Deployment Step for CI

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-17 08:05 UTC, namantalaycha10 commented
trigger uts

2023-07-17 08:09 UTC, abosii-harness requested changes

2023-07-17 08:09 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmInstallCmdResponseNG.java
> +  public List<K8sPod> getPreviousK8sPodList() {
Do we need these changes for rollback?

2023-07-17 08:18 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmInstallCmdResponseNG.java
> +  public List<K8sPod> getPreviousK8sPodList() {
let me confirm with @yogesh-chauhan

2023-07-17 11:36 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmInstallCmdResponseNG.java
> +  public List<K8sPod> getPreviousK8sPodList() {
yes I need to add changes for helm rollback as well

2023-07-17 12:25 UTC, yogesh-chauhan reviewed
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50609)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-18 05:44 UTC, namantalaycha10 commented
trigger uts

2023-07-18 05:48 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmInstallCmdResponseNG.java
> +  public List<K8sPod> getPreviousK8sPodList() {
helm rollback I will do in different PR

2023-07-18 06:12 UTC, namantalaycha10 commented
trigger messagecheck

2023-07-18 06:42 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50609)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-18 07:41 UTC, abosii-harness approved these changes

2023-07-18 07:47 UTC, namantalaycha10 commented
trigger review

2023-07-18 07:50 UTC, merged