feat: [CDS-70209]: Resolving manifest in manifest step v2
harness/harness-core pull request #50672
Opened 2023-07-18 05:36 UTC by GoelPratyush99

## Describe your changes
Resolving manifest in manifest step v2. Could not use service step v3 as service variables could not get resolved in service step V3.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-18 09:42 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +  private List<ManifestAttributes> updateManifests(
Done

2023-07-18 16:36 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +          updateManifests(manifestAttributes, ParameterFieldHelper.getParameterFieldValue(primaryManifestRef));
Lets discuss this tomorrow

2023-07-19 12:02 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +          updateManifests(manifestAttributes, ParameterFieldHelper.getParameterFieldValue(primaryManifestRef));
Done

2023-07-19 13:34 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +    return featureFlagHelperService.isEnabled(accountId, FeatureName.CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG)
Can we re-order the and condition here ?

2023-07-19 13:35 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +    boolean isMultipleManifestEnabled = isMultipleManifestEnabled(
nit: this can be final

2023-07-19 13:36 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +  private void resolvePrimaryManifestRefAndFilterSvcManifest(
can we split this method into
- resolve
- filter 
and then call these 2 individually from the caller location

2023-07-19 13:41 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +        -> !MULTIPLE_SUPPORTED_MANIFEST_TYPES.contains(manifest.getManifest().getType().name())
is this condition correct ? lets say the manifest type if azure webapp of something

2023-07-19 13:41 UTC, yogesh-chauhan requested changes
Requested some changes

2023-07-19 16:32 UTC, GoelPratyush99 commented
trigger uts

2023-07-19 17:45 UTC, GoelPratyush99 commented
trigger uts

2023-07-19 17:59 UTC, GoelPratyush99 commented
trigger uts

2023-07-19 19:41 UTC, GoelPratyush99 commented
trigger uts

2023-07-20 05:24 UTC, GoelPratyush99 commented
trigger uts

2023-07-20 05:50 UTC, GoelPratyush99 commented
trigger uts

2023-07-20 09:26 UTC, GoelPratyush99 commented
trigger uts

2023-07-20 11:55 UTC, TarunUba1 approved these changes

2023-07-20 12:32 UTC, yogesh-chauhan approved these changes

2023-07-20 12:32 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      resolve(ambiance, ngManifestsMetadataSweepingOutput.getManifestConfigurations().getPrimaryManifestRef());
we should check if the expression is resolved here or not. It can be done in the next PR

2023-07-20 19:14 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      resolve(ambiance, ngManifestsMetadataSweepingOutput.getManifestConfigurations().getPrimaryManifestRef());
Done in this PR also added UT

2023-07-20 19:15 UTC, GoelPratyush99 commented
trigger uts

2023-07-21 04:39 UTC, GoelPratyush99 commented
trigger ut2

2023-07-21 06:01 UTC, tchaurasiya requested changes

2023-07-21 06:08 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +    final boolean isMultipleManifestEnabled = isMultipleManifestEnabled(
Done. Also added UT for helm repo override

2023-07-21 09:28 UTC, tchaurasiya approved these changes

2023-07-21 10:02 UTC, abosii-harness approved these changes

2023-07-21 10:35 UTC, GoelPratyush99 commented
trigger review

2023-07-21 11:46 UTC, yogesh-chauhan approved these changes

2023-07-21 11:49 UTC, merged