feat: [CI-6928]: CI account data deletion
harness/harness-core pull request #50706
Opened 2023-07-18 14:52 UTC by devkimittal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/50706)

2023-07-24 06:13 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIEntityDeletionService.java
> +      ciTaskDetailsRepository.deleteAllByAccountId(accountId);
Put all statements in different try catch

2023-07-24 06:15 UTC, harshjain12 commented on 332-ci-manager/app/src/main/java/io/harness/ci/CIManagerServiceModule.java
> +      bind(MessageListener.class)
Event should be consumed by new ci manager in case of upgrade

2023-07-24 06:21 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/logserviceclient/CILogServiceUtils.java
> +      response = deleteLogsCall.execute();
make it async and use executor service.

2023-08-03 08:29 UTC, devkimittal commented on 332-ci-manager/app/src/main/java/io/harness/ci/CIManagerServiceModule.java
> +      bind(MessageListener.class)
Hey @harshjain12 Still not able to figure it out. Can you please help in this?

2023-08-16 10:26 UTC, devkimittal commented
@rutvijmehta-harness @vistaarjuneja for review

2023-08-21 15:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/CIExecutionServiceModule.java
> +        .toInstance(ThreadPool.create(
Isn't it fairly large thread pool size for an operation that runs every 12 hours ?

2023-08-21 15:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/AccountEntityListener.java
> +  @Inject @Named("ciEventHandlerExecutor") private ExecutorService executorService;
Why do we need this ?

2023-08-21 15:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +      executorService.submit(() -> {
We are already using executor service in `332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeleteJob.java` class, do we need here too ?

2023-08-21 15:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +    deletedAll =
Why `CITaskDetails` for other repositories ?

2023-08-21 15:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +    boolean logsExist = ciLogServiceUtils.checkIfLogsExist(accountId, key);
Just wondering, couldn't we have a single API which can do both check and delete ?

2023-08-21 15:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/logserviceclient/CILogServiceUtils.java
> +  public void deleteLogs(String accountID, String key) {
The parent function is expecting that this func will throw an exception if an error occurs but it's not throwing any error.

2023-08-21 15:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/repositories/CIAccountExecutionMetadataRepositoryCustom.java
> +
Remove extra new line

2023-08-21 15:35 UTC, raghavharness commented on product/log-service/store/s3/s3.go
> +				return err
Add a log here

2023-08-22 05:59 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeleteJob.java
> +  public void scheduleTasks() {
deletion for one account might take some time. What if the instance is restarted? We need to make sure the data is deleted.

2023-08-22 06:11 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/CIExecutionServiceModule.java
> +        .toInstance(ThreadPool.create(
I see. I think 2 would be a good corepoolsize and 5 as maxpoolsize. Assuming we get two accounts deleted in every 12 hours

2023-08-22 06:11 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/AccountEntityListener.java
> +  @Inject @Named("ciEventHandlerExecutor") private ExecutorService executorService;
was being used earlier, forgot to remove it.

2023-08-22 06:13 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +      executorService.submit(() -> {
in CIDataDeleteJob, the executor service is for running that method every 12 hours. Here is it for running each deletion in separate thread.

2023-08-22 06:14 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +    deletedAll =
didn't get your question.

2023-08-22 06:16 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +    boolean logsExist = ciLogServiceUtils.checkIfLogsExist(accountId, key);
delete logs api in log service can take huge amount of time, even 1 hour. If we want ci manager to know the data is deleted, we will have to wait for the response from log service all the time.

2023-08-22 06:17 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/logserviceclient/CILogServiceUtils.java
> +  public void deleteLogs(String accountID, String key) {
parent function is not expecting this func to throw an error.

2023-08-23 08:45 UTC, raghavharness requested changes

2023-08-23 08:45 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +    try (AcquiredLock<?> lock = persistentLocker.tryToAcquireLock(LOCK_NAME, Duration.ofMinutes(2))) {
Wait timeout can be in second (maybe 10s). No need to wait for 2 minutes since thread will be stuck.

2023-08-23 08:45 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +            saveSentTimeStamp(account);
Do this before starting the executorService. Just add this after the above if condition.

2023-08-23 09:00 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +            saveSentTimeStamp(account);
if we do this before it will block the main thread.

2023-08-23 09:07 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +            saveSentTimeStamp(account);
also the time stamp would be more exact right before making the delete call. As executorService.submit might take some ms to spawn a thread and start it.

2023-08-23 10:38 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +            saveSentTimeStamp(account);
No the problem is if you do in executor service and since it runs in a diff thread your `CI_DATA_DELETION_LOCK` can release before even setting the `lastSent` value in mongo. Another thread (from diff pod) can acquire `CI_DATA_DELETION_LOCK` meanwhile and start processing it.

2023-08-23 10:42 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +            saveSentTimeStamp(account);
achha haan. Nice catch. Teach me senpai 🙏

2023-08-23 14:01 UTC, devkimittal commented
trigger copyrightcheck

2023-08-23 15:12 UTC, devkimittal commented
trigger uts

2023-08-23 17:13 UTC, devkimittal commented
trigger uts

2023-08-23 19:12 UTC, devkimittal commented
trigger uts

2023-08-24 06:20 UTC, raghavharness approved these changes
LGTM

2023-08-24 06:24 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +    deletedAll = deleteData(() -> ciTaskDetailsRepository.deleteAllByAccountId(accountId), "CITaskDetails", accountId)
we should do it in try and catch block

2023-08-24 06:25 UTC, devkimittal commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/event/CIDataDeletionService.java
> +    deletedAll = deleteData(() -> ciTaskDetailsRepository.deleteAllByAccountId(accountId), "CITaskDetails", accountId)
it is in a try catch, see this method deleteData

2023-08-24 06:57 UTC, merged