feat: [SRM-15134]: Azure metrics populating service instance field for CV
harness/harness-core pull request #50767
Opened 2023-07-19 12:55 UTC by karansaraswat19

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-20 07:14 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50767)* status: 22 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/azure/AzureMetricsSampleDataRequest.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/50767#-N_m7uOM6HSYGWg8VbQ-:-N_m7uOM6HSYGWg8VbQ0:bt7qrxg) ([raw file](https://github.com/harness/harness-core/blob/cacce9655e97598e721d44c1cbe858824620e608/srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/azure/AzureMetricsSampleDataRequest.java#L30)):*
> ```Java
> @FieldNameConstants(innerTypeName = "AzureSampleDataRequestKeys")
> public class AzureMetricsSampleDataRequest extends AbstractAzureDataRequest {
>   String metricName;
> ```

aren't we adding aggregation to this
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/azure/metric-packs/default-custom-pack.yaml` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/50767#-N_m8aMr4m-OAIlkyV38:-N_m8aMr4m-OAIlkyV39:bscl0xe) ([raw file](https://github.com/harness/harness-core/blob/cacce9655e97598e721d44c1cbe858824620e608/srm-service/modules/cv-nextgen-service/service/src/main/resources/azure/metric-packs/default-custom-pack.yaml#L1)):*
> ```YAML
> identifier: Custom
> ```

nit: what is the significance of this?


<!-- Sent from Reviewable.io -->

2023-07-20 13:43 UTC, karansaraswat19 commented
trigger uts_JDK11

2023-07-20 17:37 UTC, karansaraswat19 commented
trigger uts_JDK11

2023-07-21 03:29 UTC, deepak-harness approved these changes
> Reviewed 3 of 14 files at r2, 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50767)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-07-21 09:27 UTC, karansaraswat19 commented
trigger ut5

2023-07-21 10:21 UTC, karansaraswat19 commented
trigger ut6

2023-07-21 10:21 UTC, karansaraswat19 commented
trigger ut8

2023-07-21 10:54 UTC, karansaraswat19 commented
trigger ut5

2023-07-21 10:55 UTC, karansaraswat19 commented
trigger ut6

2023-07-21 10:56 UTC, karansaraswat19 commented
trigger ut8

2023-07-21 11:15 UTC, karansaraswat19 commented
trigger uts

2023-07-21 12:25 UTC, karansaraswat19 commented
trigger ut6_JDK11

2023-07-21 15:26 UTC, merged

2023-07-21 15:31 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParamsDTO.java
> +        .metricNamespace(healthSourceParams.getMetricName())
why is name and namespace same, arent we going to change the metric name to something else

2023-07-21 15:49 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParamsDTO.java
> +        .metricName(healthSourceParams.getMetricName())
looks suspicious that metric name is at health source level