feat: [CDS-74758]: use config instead of Feature flag for queue service integration in triggers
harness/harness-core pull request #50814
Opened 2023-07-20 10:25 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-20 10:46 UTC, shalini-agr commented
trigger uts

2023-07-20 12:11 UTC, shalini-agr commented
trigger ut5, ut7

2023-07-20 13:25 UTC, archit-harness requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50814)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 826 at r1](https://reviewable.io/reviews/harness/harness-core/50814#-N_nTKpg6fv4aBOS7t5E:-N_nTKpg6fv4aBOS7t5F:b48jjva) ([raw file](https://github.com/harness/harness-core/blob/4f8680b6dc07ff97c8904f4f778a8d8a2fee3502/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L826)):*
> ```Java
>   CDS_ENABLE_LOAD_FROM_CACHE_FOR_RETRY_FORM("Used for enabling load from cache on retry form", PIPELINE),
>   CDS_GITHUB_PACKAGES("Used for SSH/WinRm copy and download Github packages artifacts", HarnessTeam.CDP),
>   CDS_QUEUE_SERVICE_FOR_TRIGGERS(
> ```

First create cds ticket to turn it off and delete the flag


<!-- Sent from Reviewable.io -->

2023-07-20 14:00 UTC, shalini-agr commented
@archit-harness the FF is not yet enabled anywhere or even added in UAT https://uat.harness.io/ng/account/I3TdrVLBSd2Zr2ttor7Z2A/cf/orgs/default/projects/HarnessFeatureFlags/feature-flags?activeEnvironment=PreQA&search=%22CDS_QUEUE_SERVICE_FOR_TRIGGERS%22

2023-07-20 14:01 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50814)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 826 at r1](https://reviewable.io/reviews/harness/harness-core/50814#-N_nTKpg6fv4aBOS7t5E:-N_naaBW1SyC9qVnTwtE:b-o8su23) ([raw file](https://github.com/harness/harness-core/blob/4f8680b6dc07ff97c8904f4f778a8d8a2fee3502/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L826)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

First create cds ticket to turn it off and delete the flag
</blockquote></details>

FF is not yet enabled anywhere or even added in UAT: https://uat.harness.io/ng/account/I3TdrVLBSd2Zr2ttor7Z2A/cf/orgs/default/projects/HarnessFeatureFlags/feature-flags?search=%22CDS_QUEUE_SERVICE_FOR_TRIGGERS%22&activeEnvironment=PreQA


<!-- Sent from Reviewable.io -->

2023-07-21 07:01 UTC, sribalij commented on pipeline-service/config/config.yml
> +useQueueServiceForWebhookTriggers: ${USE_QUEUE_SERVICE_FOR_WEBHOOK_TRIGGERS:-false}
Since useQueueServiceForWebhookTriggers is used in both ng-manager and pipeline-service. How do we ensure we turn both on or both off (both on is more important)?

2023-07-21 07:23 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50814)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/config/config.yml` line 664 at r1](https://reviewable.io/reviews/harness/harness-core/50814#gh-1270296692:-N_rJZrQCB3LzihrkJ4y:b-5tpj66) ([raw file](https://github.com/harness/harness-core/blob/c974fb30e8f46245358e44c4230362b5df785e89/pipeline-service/config/config.yml#L664)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Since useQueueServiceForWebhookTriggers is used in both ng-manager and pipeline-service. How do we ensure we turn both on or both off (both on is more important)?
</blockquote></details>

I think we'd have to make sure when we are updating manifests for this config, we do it for both services. 
We also have all-services.yaml file in preqa folder, if we update the config there, it'll be overridden in all services, but since this config is only for two services, we probably can't add it there.


<!-- Sent from Reviewable.io -->

2023-07-21 08:38 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50814)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-21 10:28 UTC, sribalij approved these changes

2023-07-21 10:29 UTC, shalini-agr commented
trigger review

2023-07-21 10:32 UTC, merged