fix: [CDS-71966]: draft data regarding InstanceStatsdDeleteJob
harness/harness-core pull request #50827
Opened 2023-07-20 17:04 UTC by TarunUba1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-26 12:06 UTC, abosii-harness requested changes

2023-07-26 12:06 UTC, abosii-harness commented on 400-rest/src/main/java/software/wings/scheduler/InstanceStatsDeleteJob.java
> +public class InstanceStatsDeleteJob implements Job {
Any reasons why this is part of the cg manager?

2023-07-27 10:50 UTC, TarunUba1 commented on 400-rest/src/main/java/software/wings/scheduler/InstanceStatsDeleteJob.java
> +                          .withIntervalInHours(SYNC_INTERVAL)
i can do for running every week at sunday/ saturday or every month
cant do it bi-weekly

2023-07-27 10:50 UTC, TarunUba1 commented on 400-rest/src/main/java/software/wings/scheduler/InstanceStatsDeleteJob.java
> +public class InstanceStatsDeleteJob implements Job {
Cause this is for CG stats only

2023-07-27 11:02 UTC, TarunUba1 commented on 390-db-migration/src/main/java/io/harness/migrations/all/AddInstanceStatsDeletionJobToAllAccounts.java
> +  @Inject private WingsPersistence wingsPersistence;
didn't get this comment

2023-07-27 12:32 UTC, closed without merging