feat: [CDS-74873]: Execution SubGraph API Initial changes
harness/harness-core pull request #50841
Opened 2023-07-21 06:09 UTC by utkarshchoubey-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-25 11:32 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-25 12:24 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-26 09:49 UTC, archit-harness requested changes
> Reviewed 6 of 16 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGUvO52WMvD7hZSMQ_:-NaGUvO52WMvD7hZSMQa:b-ow4gsr) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L155)):*
> ```Java
>   /**
>    * Returns iterator for all children nodeExecution for given parentId without projection sort by
>    * CreatedAt (Desc) Uses - planExecutionId_createdAt_idx
> ```

Recursive parent wise fetch, 



_Code quote:_
```Java
CreatedAt (Desc) Uses - planExecutionId_createdAt_idx
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGVxzz9tVENHSuMUnw:-NaGVxzz9tVENHSuMUnx:b-wloxx3) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L155)):*
> ```Java
>   /**
>    * Returns iterator for all children nodeExecution for given parentId without projection sort by
>    * CreatedAt (Desc) Uses - planExecutionId_createdAt_idx
> ```

this is not a valid index



_Code quote:_
```Java
planExecutionId_createdAt_idx
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 203 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGSvtp1DlLgq6rS-RA:-NaGSvtp1DlLgq6rS-RB:b-3hyxci) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L203)):*
> ```Java
>    * @return
>    */
>   List<NodeExecution> extractChildExecutions(String parentId, boolean includeParent, List<NodeExecution> finalList,
> ```

2 methods, one with false and one having this field as passing true?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 342 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGXE3wEkHIoJp3SagQ:-NaGXE3wEkHIoJp3SagR:b-7v9bv7) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L342)):*
> ```Java
>   public List<NodeExecution> extractChildExecutions(String parentId, boolean includeParent,
>       List<NodeExecution> finalList, List<NodeExecution> allExecutions, boolean includeChildrenOfStrategy,
>       boolean excludeChildOfOldRetries) {
> ```

this method is not needed and above method will handle
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 395 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGa4VH17DwN6N0tUFT:-NaGa4VH17DwN6N0tUFU:br5b5in) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L395)):*
> ```Java
>           required = true) @PathParam(NGCommonEntityConstants.PLAN_KEY) String planExecutionId) {
>     PipelineExecutionSummaryEntity executionSummaryEntity =
>         pmsExecutionService.getPipelineExecutionSummaryEntity(accountId, orgId, projectId, planExecutionId, false);
> ```

this first can be ignored or not, added projection query
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExecutionGraphServiceImpl.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGa25f2IALxkt2OfvE:-NaGa25f2IALxkt2OfvF:bmnw8ji) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExecutionGraphServiceImpl.java#L64)):*
> ```Java
>     OrchestrationGraphDTO orchestrationGraphDTO = OrchestrationGraphDTOConverter.convertFrom(graph);
>     ExecutionGraph executionGraph =
>         ExecutionGraphMapper.toExecutionGraph(orchestrationGraphDTO, executionSummaryEntity);
> ```

check if summaryEntity is required or not


<!-- Sent from Reviewable.io -->

2023-07-27 09:47 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 17 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGVxzz9tVENHSuMUnw:-NaLjbHs24uTdvti1Dpf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L155)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is not a valid index
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 203 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGSvtp1DlLgq6rS-RA:-NaLjbvbE32WN79nJLeg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L203)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

2 methods, one with false and one having this field as passing true?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 342 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGXE3wEkHIoJp3SagQ:-NaLjc_CECpVxzCUBLZO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L342)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this method is not needed and above method will handle
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 395 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGa4VH17DwN6N0tUFT:-NaLjdBy9RiyeYXfPaNK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L395)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this first can be ignored or not, added projection query
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExecutionGraphServiceImpl.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGa25f2IALxkt2OfvE:-NaLjdqTAb_RNnY3WdEO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExecutionGraphServiceImpl.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check if summaryEntity is required or not
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-27 10:02 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-27 10:53 UTC, brijeshdhakar requested changes
> Reviewed 4 of 16 files at r1, 2 of 2 files at r2, 6 of 10 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 11 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 310 at r4](https://reviewable.io/reviews/harness/harness-core/50841#-NaLwphw6XJA1DFFQbuI:-NaLwphw6XJA1DFFQbuJ:bs56wyn) ([raw file](https://github.com/harness/harness-core/blob/65a0e7d71a34b00ecf2047bfad92fc149ad05d53/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L310)):*
> ```Java
>   public List<NodeExecution> fetchChildrenNodeExecutionsRecursivelyFromGivenParentId(
>       String planExecutionId, List<String> parentIds) {
>     return fetchChildrenNodeExecutionsRecursivelyFromGivenParentId(planExecutionId, parentIds, 0);
> ```

nit: A good practice is to pass MAX_DEPTH here instead of zero. And check if depth<=0 then return.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 326 at r4](https://reviewable.io/reviews/harness/harness-core/50841#-NaLx47G4D4vPy3LQraG:-NaLx47G4D4vPy3LQraH:bhkbzp9) ([raw file](https://github.com/harness/harness-core/blob/65a0e7d71a34b00ecf2047bfad92fc149ad05d53/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L326)):*
> ```Java
>       return new ArrayList<>();
>     }
>     if (depth >= MAX_DEPTH) {
> ```

Can you move this check before making the DB call to fetch nodeExecutions? Since if this condition is true then we are not considering any nodeExecutions fetched above.


<!-- Sent from Reviewable.io -->

2023-07-27 11:44 UTC, utkarshchoubey-harness reviewed
> Reviewed 5 of 16 files at r1, 2 of 2 files at r2, 8 of 10 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 11 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGUvO52WMvD7hZSMQ_:-NaM9VJ90aYX4fGbgCFS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L155)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Recursive parent wise fetch, 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 326 at r4](https://reviewable.io/reviews/harness/harness-core/50841#-NaLx47G4D4vPy3LQraG:-NaM9X0l9YD6ARR80Q1v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65a0e7d71a34b00ecf2047bfad92fc149ad05d53/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L326)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Can you move this check before making the DB call to fetch nodeExecutions? Since if this condition is true then we are not considering any nodeExecutions fetched above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-27 11:44 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-27 12:12 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 1 of 16 files at r1, 1 of 10 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 10 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-27 16:32 UTC, archit-harness requested changes
> Reviewed 7 of 10 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 160 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaN9qJe0rNbUCbXmpHk:-NaN9qJe0rNbUCbXmpHl:bz93vrh) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L160)):*
> ```Java
>    * @return
>    */
>   CloseableIterator<NodeExecution> fetchChildrenNodeExecutionsIteratorWithoutProjection(
> ```

why do you need this method?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 171 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNAB8h5oAjkidc1Z1q:-NaNAB8h5oAjkidc1Z1r:bqvum71) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L171)):*
> ```Java
>    */
>   List<NodeExecution> fetchChildrenNodeExecutionsRecursivelyFromGivenParentId(
>       String planExecutionId, List<String> parentIds);
> ```

mention this is oldRetry is false
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 303 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNA4Z8-E3Q2YX8NG5S:-NaNA4Z8-E3Q2YX8NG5T:b-8pvnur) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L303)):*
> ```Java
>     // Uses planExecutionId_parentId_createdAt_idx
>     Query query = query(where(NodeExecutionKeys.planExecutionId).is(planExecutionId))
>                       .addCriteria(where(NodeExecutionKeys.parentId).in(parentIds))
> ```

confirm this is using index
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 318 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNAVa_9mSCOwAT_ZYq:-NaNAVa_9mSCOwAT_ZYr:b-if9yuf) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L318)):*
> ```Java
>       throw new InvalidRequestException(
>           String.format("Exceeded Max Depth level [%s] for the Node SubGraph", MAX_DEPTH));
>     }
> ```

if parentIds is empty then return empty 
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 338 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNAZXQEaxu8bxAdjqp:-NaNAZXQEaxu8bxAdjqq:b4m4xbp) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L338)):*
> ```Java
>     List<NodeExecution> childNodeExecutions =
>         fetchChildrenNodeExecutionsRecursivelyFromGivenParentId(planExecutionId, childParentIds, depth - 1);
>     recursiveChildrenNodeExecutions.addAll(childNodeExecutions);
> ```

if list empty or null is returned, it will not fail?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 395 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGa4VH17DwN6N0tUFT:-NaNBKWAAdBrt_X4oHO7:bw5q0fx) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L395)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

projection is still not used for this db query


<!-- Sent from Reviewable.io -->

2023-07-27 16:39 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 303 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNA4Z8-E3Q2YX8NG5S:-NaND2zk29SuyZU_p9d9:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L303)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

confirm this is using index
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-07-27 16:56 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 160 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaN9qJe0rNbUCbXmpHk:-NaNE6Uj-nTWgN3Gfw_m:bmad8no) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L160)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need this method?
</blockquote></details>

Done. 
This is where the actual DB is happening, the recursive function is calling this function only
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 171 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNAB8h5oAjkidc1Z1q:-NaNEabnDkxChFcKKjRA:bxea8w3) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L171)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

mention this is oldRetry is false
</blockquote></details>

Done.

Added in the description and function Name
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 318 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNAVa_9mSCOwAT_ZYq:-NaNEyNZCaWROHFRVY0X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L318)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if parentIds is empty then return empty 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 338 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaNAZXQEaxu8bxAdjqp:-NaNF2EPBip5-GmjuaCF:bmdrzn5) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L338)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if list empty or null is returned, it will not fail?
</blockquote></details>

Done. Nope it will not fail, for leaf nodes always empty is returned from the base case of recursion
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 395 at r2](https://reviewable.io/reviews/harness/harness-core/50841#-NaGa4VH17DwN6N0tUFT:-NaNFA15AQHbWydT0A3Y:bk9y1y6) ([raw file](https://github.com/harness/harness-core/blob/3f8bb37e55228e1d70a1267f74de655a23c27bb7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L395)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

projection is still not used for this db query
</blockquote></details>

Done.
Discussed , will be taking this up in my next pr


<!-- Sent from Reviewable.io -->

2023-07-27 16:56 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 160 at r5](https://reviewable.io/reviews/harness/harness-core/50841#-NaN9qJe0rNbUCbXmpHk:-NaNGrzdBDJJwTts7E1c:b-6799h8) ([raw file](https://github.com/harness/harness-core/blob/633010390da5a4dd823d274afeeecd98e56fc4c7/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L160)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done. 
This is where the actual DB is happening, the recursive function is calling this function only
</blockquote></details>

removed it from the interface


<!-- Sent from Reviewable.io -->

2023-07-27 16:58 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-27 17:05 UTC, utkarshchoubey-harness commented
trigger uts

2023-07-27 17:06 UTC, archit-harness approved these changes
> Reviewed 4 of 4 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50841)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-27 17:10 UTC, vivekkarnatiharness approved these changes

2023-07-27 17:19 UTC, utkarshchoubey-harness commented
trigger ut6

2023-07-27 17:20 UTC, utkarshchoubey-harness commented
trigger review

2023-07-27 17:33 UTC, utkarshchoubey-harness commented
trigger ut6

2023-07-27 17:45 UTC, utkarshchoubey-harness commented
trigger ut6

2023-07-27 17:57 UTC, merged