fix: [PL-38674]: Make delegate name unique within the scope in NG
harness/harness-core pull request #50870
Opened 2023-07-21 16:27 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-21 16:40 UTC, jennyjames21 commented
trigger uts

2023-07-21 18:20 UTC, jennyjames21 commented
trigger uts

2023-07-21 20:28 UTC, jennyjames21 commented
Delegate with same name under project and account level
<img width="1600" alt="image" src="https://github.com/harness/harness-core/assets/82905057/f8fc3073-c823-44af-a7b6-8320b095eca9">
<img width="1681" alt="image" src="https://github.com/harness/harness-core/assets/82905057/1fcd5452-5057-4b63-a513-eacbf9ffc9d7">
One delegate group
<img width="1253" alt="image" src="https://github.com/harness/harness-core/assets/82905057/19e86ee9-a25f-46a6-a6c7-368bd06029ed">
<img width="1208" alt="image" src="https://github.com/harness/harness-core/assets/82905057/bdc915a1-2cae-457b-bc1a-cb7fec0d47f1">

2023-07-21 20:28 UTC, jennyjames21 commented
trigger uts

2023-07-21 20:33 UTC, jennyjames21 commented
trigger uts

2023-07-21 22:00 UTC, raghuAtWings requested changes

2023-07-21 22:00 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java
> +    DelegateEntityOwner owner = DelegateEntityOwnerHelper.buildOwner(orgIdentifier, projectIdentifier);
These code changes seem to be ensuring the uniqueness while downloading the yaml. Where is the logic to ensure delegate do get registered with the same name and different scope? 

Also i don't see any unit test on this change. Can we add one?

2023-07-21 22:05 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java
> +    DelegateEntityOwner owner = DelegateEntityOwnerHelper.buildOwner(orgIdentifier, projectIdentifier);
DelegateServiceImpl line : 3209

2023-07-21 22:08 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java
> +    DelegateEntityOwner owner = DelegateEntityOwnerHelper.buildOwner(orgIdentifier, projectIdentifier);
There are already bunch of unit test on uniqueness check which is failing, i will fix and update that

2023-07-24 03:16 UTC, jennyjames21 commented
trigger uts

2023-07-24 16:27 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java
> +    DelegateEntityOwner owner = DelegateEntityOwnerHelper.buildOwner(orgIdentifier, projectIdentifier);
existing unit test 
![Uploading image.png…]()

2023-07-24 16:43 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java
> +    DelegateEntityOwner owner = DelegateEntityOwnerHelper.buildOwner(orgIdentifier, projectIdentifier);
yes, the line 3209 fixes the issue during registration.
and.. do we need to remove the delegateService.checkUniquenessOfDelegateName  in the download apis, and the k8s precheck api, these are UI functions for old installation wizard and CG, feel it's ok to keep them unchanged. And they will be removed by EoY .

2023-07-24 16:46 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateDownloadServiceImpl.java
> +    DelegateEntityOwner owner = DelegateEntityOwnerHelper.buildOwner(orgIdentifier, projectIdentifier);
Owner is passing as null for CG calls so no changes and yes they can be removed/unused once we fully adapt to the new wizard.

2023-07-25 16:56 UTC, xingchi-jin submitted a review, later dismissed
LG, thanks !

2023-07-26 20:23 UTC, jennyjames21 commented
trigger uts

2023-07-26 20:57 UTC, xingchi-jin submitted a review, later dismissed

2023-07-26 23:26 UTC, jennyjames21 commented
trigger uts

2023-07-27 05:41 UTC, jennyjames21 commented
trigger uts

2023-07-28 06:29 UTC, raghuAtWings approved these changes

2023-07-28 06:45 UTC, merged