Ie 212 - external secrets
harness/harness-core pull request #50881
Opened 2023-07-22 22:54 UTC by harness-jc

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-22 22:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=50881) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=50881) before we can accept your contribution.<br/><hr/>**Jon Charette** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=50881) it.</sub>

2023-07-24 11:58 UTC, mbatchelor requested changes

2023-07-24 11:58 UTC, mbatchelor commented on template-service/chart/Chart.yaml
> +version: 0.4.00
I htink this should be 0.4.0 - too many trailing zeros

2023-07-28 08:48 UTC, arya-harness submitted a review, later dismissed

2023-07-28 16:45 UTC, saitejavn-harness commented on 100-migrator/chart/templates/deployment.yaml
> +                optional: true
Looks like secrets in "migrator-external-secret" may overlap with generated/hardcoded ones. Should we handle these conflicts separately?

2023-07-28 16:48 UTC, saitejavn-harness commented on 100-migrator/chart/templates/external-secret.yaml
> +{{- end}}
Will this file be source for both app, database secrets?

2023-07-28 16:50 UTC, saitejavn-harness commented on 100-migrator/chart/templates/external-secret.yaml
> +      key: SMTP_HOST
Should we namespace these secrets like "HARNESS_SMTP_HOST" so that these names do not conflict with existing secrets if any?

2023-07-31 13:38 UTC, harness-jc commented on 100-migrator/chart/templates/external-secret.yaml
> +      key: SMTP_HOST
The values here match what is in ng-prod-manifests and are what the application is expecting.  The secret is already namespace'd and separated by application, so there should be no overlap.

2023-07-31 13:39 UTC, harness-jc commented on 100-migrator/chart/templates/external-secret.yaml
> +{{- end}}
Yes, the objective of this PR was to provide the framework (and need for SMTP settings) within IE. Additional secrets will be added.

2023-07-31 17:45 UTC, merged