[CDS-68782]: Support for jira retry interval
harness/harness-core pull request #50890
Opened 2023-07-24 05:23 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-25 16:45 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalInstanceHandler.java
>    PersistenceIterator<ApprovalInstance> iterator;
Can we rename this file to something like IrregularApprovalInstanceHandler

2023-07-25 16:47 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalInstanceHandler.java
> +        customApprovalHelperService.handlePollingEvent(iterator, customApprovalInstance);
please add log lines here for all type of approvals and including "irregular", so debugging is easier

2023-07-25 16:49 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java
> +            .retryInterval(getTimeout("retryInterval", specParameters.getRetryInterval().getValue()))
We can validate if this is working now with recent changes or fetchFinalValue is needed for expressions

2023-07-26 06:46 UTC, abhinavmittal-harness reviewed
> Reviewed 5 of 6 files at r1, 13 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50890)* status: 1 file(s) to review. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-26 10:08 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalInstanceHandler.java
> +        customApprovalHelperService.handlePollingEvent(iterator, customApprovalInstance);
Done

2023-07-26 10:08 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalInstanceHandler.java
>    PersistenceIterator<ApprovalInstance> iterator;
Done

2023-07-27 05:59 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50890)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-07-27 13:22 UTC, puthrayaharness requested changes

2023-07-27 13:22 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java
> +    long timeout = 20000L;
Extract out to a variable. static final.
It can be common variable for approval since they seem to have same value.

2023-07-27 13:22 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java
> +    return timeout + retryTime + 30000L;
Extract out to a variable. static final.

2023-07-28 08:10 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities/ApprovalInstance.java
> +  public static final long timeout = 20000l;
Please rename to `ASYNC_DELEGATE_TIMEOUT`

2023-07-28 08:20 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java
> +                    ? ParameterField.createValueField(Timeout.fromString("1m"))
please validate that unresolved timeout expression is giving `throw new IllegalArgumentException(String.format("Invalid value for %s", fieldName));`

2023-07-28 08:22 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java
> +    if (ParameterField.isNotNull(instance.getRetryInterval())) {
Instead of a not null check, we can assert if it is not null, else fail the step. Because we are expecting retry interval to be always populated and going to the irregular handler.

2023-07-28 08:30 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java
> +    return timeout + retryTime + 30000L;
Can we make buffer also a static constant like APPROVAL_LEEWAY_IN_MILLIS for all approvals.  (For custom approvals since we are making default retry interval in FE as 1m, we can keep leeway same as 30 secs for all approvals)

2023-07-28 08:33 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java
> +            .retryInterval(getTimeout("retryInterval", specParameters.getRetryInterval().getValue()))
Please ensure same logic as jira

2023-07-28 08:33 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java
> +            .retryInterval(getTimeout("retryInterval", specParameters.getRetryInterval().getValue()))
same comments as jira

2023-07-28 08:34 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java
> +    if (ParameterField.isNotNull(instance.getRetryInterval())) {
same comment

2023-07-28 08:42 UTC, naman-goenka reviewed
Please add the resetNextIteration logic conditionally in Jira/SNow helper service to reset nextIterations incase delegate task creation results in an error

2023-07-31 10:19 UTC, naman-goenka reviewed
We need to call the iterator wakeup in jira/snow step

2023-08-08 10:13 UTC, vivekkarnatiharness commented
trigger commonchecks

2023-08-08 10:13 UTC, vivekkarnatiharness commented
trigger uts

2023-08-08 10:21 UTC, vivekkarnatiharness commented
trigger commonchecks

2023-08-08 10:24 UTC, vivekkarnatiharness commented
trigger checkstyle
trigger codeformat
trigger codebasehash

2023-08-08 12:24 UTC, vivekkarnatiharness commented
trigger uts

2023-08-08 12:54 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 1 of 2 files at r3, 5 of 8 files at r5, 15 of 16 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50890)* status: 31 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-08 13:37 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java
> +  private static ParameterField<Timeout> getTimeout(String fieldName, Object objectParameterField) {
nit: we can abstract this method out in ApprovalUtils

2023-08-08 13:43 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/jira/JiraApprovalCallback.java
> +  private void resetNextIteration(JiraApprovalInstance instance) {
nit: this can be added in AbstractApprovalCallback

2023-08-08 13:46 UTC, naman-goenka submitted a review, later dismissed
We will need to add static schema changes as well

2023-08-08 17:01 UTC, vivekkarnatiharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50890)* status: 35 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities/ApprovalInstance.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/50890#gh-1277246976:-NbKZSWxETcfTaPEHvbK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/328e80d60c232ae1fb67fb5cf3b921d4fae120c1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities/ApprovalInstance.java#L77)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

Please rename to `ASYNC_DELEGATE_TIMEOUT`
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/50890#gh-1273833672:-NbL52Ug803zy41fqrBe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f5a855c38db973961bbc3857c9074e7c69f1b3b0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java#L97)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

We can validate if this is working now with recent changes or fetchFinalValue is needed for expressions
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/50890#gh-1277256264:-NbK_0Q28x4eM69a5plK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/328e80d60c232ae1fb67fb5cf3b921d4fae120c1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java#L98)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

please validate that unresolved timeout expression is giving `throw new IllegalArgumentException(String.format("Invalid value for %s", fieldName));`

This might be causing retry interval to be returned as null in this case
```
    if (objectParameterField == null) {
      return null;
    }
```    
    
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/50890#gh-1277258554:-NbK_1uu0J6Ms0j8BNsm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/328e80d60c232ae1fb67fb5cf3b921d4fae120c1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java#L105)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

Instead of a not null check, we can assert if it is not null, else fail the step. Because we are expecting retry interval to be always populated and going to the irregular handler. 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java` line 129 at r4](https://reviewable.io/reviews/harness/harness-core/50890#gh-1277266044:-NbK_30HAfj8KNPF3GQO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/328e80d60c232ae1fb67fb5cf3b921d4fae120c1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/entities/JiraApprovalInstance.java#L129)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

Can we make buffer also a static constant like APPROVAL_LEEWAY_IN_MILLIS for all approvals.  (For custom approvals since we are making default retry interval in FE as 1m, we can keep leeway same as 30 secs for all approvals) 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java` line 100 at r4](https://reviewable.io/reviews/harness/harness-core/50890#gh-1277269723:-NbK_6lk0rMse5RToz_k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/328e80d60c232ae1fb67fb5cf3b921d4fae120c1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java#L100)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

same comments as jira
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java` line 107 at r4](https://reviewable.io/reviews/harness/harness-core/50890#gh-1277270054:-NbK_CVH-QYrikauMPJ9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/328e80d60c232ae1fb67fb5cf3b921d4fae120c1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java#L107)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

same comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-08 17:06 UTC, vivekkarnatiharness commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalStep.java` line 79 at r6](https://reviewable.io/reviews/harness/harness-core/50890#gh-1280609751:-NbL5ApeA4M1_biR0P1Q:b6apgk9) ([raw file](https://github.com/harness/harness-core/blob/841d45ceefb5341251dc24e57b98040bc9246a34/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalStep.java#L79)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@vivekkarnatiharness we are going to consume one IrregularApprovalInstanceHandler which is singleton but has more running steps in different pipelines at the same time. Is it ok to re-wake up the handler for each running step? 
</blockquote></details>

Wakeup will be called only once per execution. This iterator is in pump mode, so definitely we need to wakeitup ,otherwise newer tasks might not pickedup, In Pump mode since the same executor is used for both the tasks depending the current state of the taskQ the thread might not take up the submitted task right away.


<!-- Sent from Reviewable.io -->

2023-08-09 03:10 UTC, vivekkarnatiharness commented
trigger uts

2023-08-09 03:17 UTC, vivekkarnatiharness commented
trigger uts

2023-08-09 04:50 UTC, puthrayaharness approved these changes

2023-08-09 05:10 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalSpecParameters.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_DASHBOARD})
CDS_APPROVALS

2023-08-09 05:58 UTC, vivekkarnatiharness commented
trigger uts

2023-08-09 06:26 UTC, abhinavmittal-harness reviewed
> Reviewed 7 of 10 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50890)* status: 35 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-09 07:04 UTC, vivekkarnatiharness commented
trigger uts

2023-08-09 07:05 UTC, vivekkarnatiharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50890)* status: 35 file(s) to review. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalSpecParameters.java` line 37 at r10](https://reviewable.io/reviews/harness/harness-core/50890#gh-1287950693:-NbO69f21CYQsYlZwq_b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cee495a7c5b920e009735ff764c7b88afde2b056/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalSpecParameters.java#L37)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

CDS_APPROVALS
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/50890#gh-1276273822:-NbO6Com1-svNl_dLpBo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0b1e9854b19eccd343ee6ec28fd4286f35a63d0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java#L133)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Extract out to a variable. static final.
It can be common variable for approval since they seem to have same value.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java` line 136 at r3](https://reviewable.io/reviews/harness/harness-core/50890#gh-1276274422:-NbO6DTwDHIZDtNoLtwA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0b1e9854b19eccd343ee6ec28fd4286f35a63d0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/entities/ServiceNowApprovalInstance.java#L136)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Extract out to a variable. static final.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-09 08:51 UTC, naman-goenka approved these changes

2023-08-09 08:56 UTC, vivekkarnatiharness commented
trigger review

2023-08-09 09:50 UTC, puthrayaharness approved these changes

2023-08-09 11:03 UTC, merged