[fix]: [CDS-73981]: Put validation on tag expression values in filters
harness/harness-core pull request #50916
Opened 2023-07-24 12:33 UTC by lovish1999

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-26 09:32 UTC, lovish1999 commented
trigger uts

2023-07-27 09:59 UTC, tchaurasiya commented
@lovish1999 can we add unit test for this?

2023-07-28 05:57 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 695 at r1](https://reviewable.io/reviews/harness/harness-core/50916#-NaQ3LxY-TRFDRzqnmRW:-NaQ3LxY-TRFDRzqnmRX:b-p4i0wh) ([raw file](https://github.com/harness/harness-core/blob/166e4f7a23dcd348f92949f021d8419cb8053453/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L695)):*
> ```Java
>     ParameterField<List<EnvironmentYamlV2>> environments = environmentGroup.getEnvironments();
>     if (ParameterField.isNotNull(environments)) {
>       validateTagExpressionValue((List<EnvironmentYamlV2>) environments);
> ```

environments in `ParameterField<List<EnvironmentYamlV2>>`, why are we casting it to `List<EnvironmentYamlV2>` ?


<!-- Sent from Reviewable.io -->

2023-07-28 05:57 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 700 at r1](https://reviewable.io/reviews/harness/harness-core/50916#-NaQ39Fz-9XZtblf2KC8:-NaQ39Fz-9XZtblf2KC9:bl7mdly) ([raw file](https://github.com/harness/harness-core/blob/166e4f7a23dcd348f92949f021d8419cb8053453/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L700)):*
> ```Java
> 
>   private boolean isSupportedTagExpression(String tagExpressionValue) {
>     return tagExpressionValue.equals(SERVICE_TAGS);
> ```

constants should always be on Left side of comparison
SERVICE_TAGS.equals(tagExpressionValue)


<!-- Sent from Reviewable.io -->

2023-07-28 05:57 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 700 at r1](https://reviewable.io/reviews/harness/harness-core/50916#-NaQ3j7w9Mrp6uDQuL4y:-NaQ3j7w9Mrp6uDQuL4z:beyic97) ([raw file](https://github.com/harness/harness-core/blob/166e4f7a23dcd348f92949f021d8419cb8053453/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L700)):*
> ```Java
> 
>   private boolean isSupportedTagExpression(String tagExpressionValue) {
>     return tagExpressionValue.equals(SERVICE_TAGS);
> ```

what happens when tagExpressionValue is empty ? Is it even possible ? Just asking


<!-- Sent from Reviewable.io -->

2023-07-28 05:58 UTC, yogesh-chauhan commented
Should we not do this check in DeploymentStageFilterCreatorV2 i.e during pipeline save ?




<!-- Sent from Reviewable.io -->

2023-07-28 05:59 UTC, yogesh-chauhan reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50916)* status: Some of the checks are too old. 2 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-31 10:28 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/50916#-NafUPbr-kbFL5KXx1FR:-NafUPbr-kbFL5KXx1FS:bm37b1d) ([raw file](https://github.com/harness/harness-core/blob/26bcecda735a1ddce7d7b9bfa06348d1129d89ee/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L92)):*
> ```Java
>   private static final String STEP_IDENTIFIER_FIELD = "identifier";
>   private static final Set<String> SUPPORTED_FILTER_TAGS_EXPRESSIONS =
>       ImmutableSet.of("<+service.tags>", "<+pipeline.tags>");
> ```

nit: you can just use 
```
java.util.Set#of()
```


<!-- Sent from Reviewable.io -->

2023-07-31 12:35 UTC, lovish1999 commented
trigger uts

2023-08-01 08:22 UTC, tchaurasiya requested changes

2023-08-01 08:22 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +        if (tags.isExpression() && !isSupportedTagExpression(tags.getExpressionValue())) {
Can we handle the case where tags are mixed expression? <+pipeline.name>-suffix

2023-08-07 08:29 UTC, closed without merging