feat:[CDS-73472]: delegate side changes for github app auth for GitFetch Task and download file task
harness/harness-core pull request #50952
Opened 2023-07-25 09:02 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-25 10:26 UTC, abosii-harness submitted a review, later dismissed

2023-07-25 11:54 UTC, yogesh-chauhan requested changes

2023-07-25 11:54 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java
> +        ngGitService.downloadFiles(gitStoreDelegateConfig, workingDirectory, accountId, sshSessionConfig);
we are removing gitConfigDTO, it will not get decrypted ?

2023-07-25 11:54 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java
>              gitConfigDTO, gitStoreDelegateConfig.getEncryptedDataDetails());
should we call ScmConnectorMapperDelegate instead ?

2023-07-25 11:54 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskHelper.java
> +        gitStoreDelegateConfig.getGitConfigDTO(), gitStoreDelegateConfig.getEncryptedDataDetails());
this needs to be moved to where we call "scmConnectorMapper.toGitConfigDTO"

2023-07-25 11:54 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +            gitStoreDelegateConfig, manifestFilesDirectory, commandRequest.getAccountId(), sshSessionConfig);
we need to pass gitconfigDTO here since its decrypted

2023-07-26 06:56 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java
> +        ngGitService.downloadFiles(gitStoreDelegateConfig, workingDirectory, accountId, sshSessionConfig);
done

2023-07-26 06:56 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBase.java
>              gitConfigDTO, gitStoreDelegateConfig.getEncryptedDataDetails());
done

2023-07-26 06:56 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskHelper.java
> +        gitStoreDelegateConfig.getGitConfigDTO(), gitStoreDelegateConfig.getEncryptedDataDetails());
done

2023-07-26 06:56 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +            gitStoreDelegateConfig, manifestFilesDirectory, commandRequest.getAccountId(), sshSessionConfig);
done

2023-07-26 06:56 UTC, sourabh-awashti commented
trigger uts

2023-07-26 10:51 UTC, yogesh-chauhan commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/adapter/GithubToGitMapper.java
> +        passwordRef = SecretRefHelper.createSecretRef(GITHUB_APP, Scope.ACCOUNT, GITHUB_APP.toCharArray());
why is the scope as ACCOUNT here ?

2023-07-26 10:54 UTC, yogesh-chauhan commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/adapter/GithubToGitMapper.java
> +        passwordRef = SecretRefHelper.createSecretRef(GITHUB_APP, Scope.ACCOUNT, GITHUB_APP.toCharArray());
Lets put a comment that this is dummy value and not used

2023-07-26 10:54 UTC, yogesh-chauhan reviewed
LGTM

2023-07-27 06:30 UTC, sourabh-awashti commented
trigger uts

2023-07-27 11:20 UTC, sourabh-awashti commented
trigger uts

2023-07-27 12:00 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 3 of 13 files at r1, 1 of 38 files at r2, 46 of 52 files at r3, 1 of 1 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50952)* status: 62 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-27 12:42 UTC, abosii-harness submitted a review, later dismissed

2023-07-27 12:43 UTC, sourabh-awashti commented
trigger ut2

2023-07-28 05:56 UTC, sourabh-awashti commented
trigger uts

2023-07-28 06:42 UTC, sourabh-awashti commented
trigger uts

2023-07-28 09:52 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50952)* status: 62 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-28 09:52 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50952)* status: 62 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-28 09:53 UTC, sarthakkasat approved these changes

2023-07-28 09:55 UTC, sourabh-awashti commented
trigger review

2023-07-28 09:56 UTC, abosii-harness approved these changes

2023-07-28 09:58 UTC, merged