feat: [CDS-74554]: k8s & helm rollback changes: Get Node information …
harness/harness-core pull request #50961
Opened 2023-07-25 11:27 UTC by namantalaycha10

…via API from CD Deployment Step for CI

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-25 12:00 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java` line 537 at r1](https://reviewable.io/reviews/harness/harness-core/50961#-NaBv3TdEbtQ-L4winag:-NaBv3TdEbtQ-L4winah:b7jz9mw) ([raw file](https://github.com/harness/harness-core/blob/720c48feecfa4e334d167ecb34de669dcad9a65b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java#L537)):*
> ```Java
>   }
> 
>   @VisibleForTesting
> ```

do we need this annotation ?


<!-- Sent from Reviewable.io -->

2023-07-25 12:01 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java` line 539 at r1](https://reviewable.io/reviews/harness/harness-core/50961#-NaBv85REKYfPEL9dkRQ:-NaBv85REKYfPEL9dkRR:bnsp8e0) ([raw file](https://github.com/harness/harness-core/blob/720c48feecfa4e334d167ecb34de669dcad9a65b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java#L539)):*
> ```Java
>   @VisibleForTesting
>   public List<K8sPod> tagNewPods(List<K8sPod> newPods, List<K8sPod> existingPods) {
>     Set<String> existingPodNames = existingPods.stream().map(K8sPod::getName).collect(Collectors.toSet());
> ```

do we need null check here ?
does this method need to be public ?


<!-- Sent from Reviewable.io -->

2023-07-25 12:03 UTC, yogesh-chauhan reviewed
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50961)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingDeployRollbackResponse.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/50961#-NaBvg_l3Ed8cGXJLyuy:-NaBvg_l3Ed8cGXJLyuz:b-ws7lzf) ([raw file](https://github.com/harness/harness-core/blob/720c48feecfa4e334d167ecb34de669dcad9a65b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingDeployRollbackResponse.java#L35)):*
> ```Java
>   public List<K8sPod> getTotalK8sPodList() {
>     return k8sPodList;
>   }
> ```

do we need explicit getters here ? 


<!-- Sent from Reviewable.io -->

2023-07-25 12:51 UTC, namantalaycha10 commented
trigger uts

2023-07-26 06:45 UTC, namantalaycha10 commented
> _[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java` line 537 at r1](https://reviewable.io/reviews/harness/harness-core/50961#-NaBv3TdEbtQ-L4winag:-NaBv3TdEbtQ-L4winah:b7jz9mw) ([raw file](https://github.com/harness/harness-core/blob/720c48feecfa4e334d167ecb34de669dcad9a65b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java#L537)):_
> 
> > ```java
> >   }
> > 
> >   @VisibleForTesting
> > ```
> 
> do we need this annotation ?

removed

2023-07-26 07:47 UTC, namantalaycha10 commented
> 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingDeployRollbackResponse.java

Actually I used the different get method name so getter will not work here

2023-07-26 07:47 UTC, namantalaycha10 commented
trigger uts

2023-07-26 10:22 UTC, namantalaycha10 commented
trigger uts

2023-07-26 10:35 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 7 files at r1, 50 of 51 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50961)* status: 58 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-26 11:30 UTC, namantalaycha10 commented
trigger messagecheck

2023-07-26 11:34 UTC, abosii-harness requested changes

2023-07-26 11:34 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java
> +  public List<K8sPod> tagNewPods(List<K8sPod> newPods, List<K8sPod> existingPods) {
Are these methods different than the one used in other handlers?

2023-07-26 11:49 UTC, namantalaycha10 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java
> +  public List<K8sPod> tagNewPods(List<K8sPod> newPods, List<K8sPod> existingPods) {
yaah right, made the update. Now using the comman method

2023-07-26 11:50 UTC, namantalaycha10 commented
trigger uts

2023-07-26 12:31 UTC, namantalaycha10 commented
trigger uts

2023-07-26 12:59 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50961)* status: 59 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-26 14:19 UTC, TarunUba1 approved these changes
add the description of PR and Testing you did around it otherwise everything looks goodd

2023-07-26 14:23 UTC, abosii-harness approved these changes

2023-07-27 03:41 UTC, namantalaycha10 commented
trigger review

2023-07-27 03:44 UTC, merged