feat:[CDS-73837]: change in Terragrunt/ Terraform For Github App authentication
harness/harness-core pull request #51009
Opened 2023-07-26 09:22 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-26 11:46 UTC, yogesh-chauhan requested changes

2023-07-26 11:46 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java
> +    return gitStoreDelegateConfigBuilder.build();
I think we should abstract out all these details about github app out of the Terraform & Terragrunt step code. Lets discuss offline on how we can do this

2023-07-27 05:24 UTC, yogesh-chauhan reviewed
Lets also put a comment in ScmConnectorMapper that it must be used on the manager side with appropriate reasoning

2023-07-27 05:24 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java
> -        gitConfigAuthenticationInfoHelper.getEncryptedDataDetails(gitConfigDTO, sshKeySpecDTO, basicNGAccessObject);
lets merge this method into gitConfigAuthenticationInfoHelper.getEncryptedDataDetails

2023-07-27 05:24 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntApplyTaskNG.java
> +  @Inject private ScmConnectorMapperDelegate scmConnectorMapperDelegate;
this is unused

2023-07-27 05:24 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java
> +  public void mapGitConfig(AbstractTerragruntTaskParameters taskParameters) {
this can be private

2023-07-27 05:24 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java
> +  public void mapGitConfig(AbstractTerragruntTaskParameters taskParameters) {
mapGitConfigFromGitFileStore

2023-07-27 06:52 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java
> +  public void mapGitConfig(AbstractTerragruntTaskParameters taskParameters) {
done

2023-07-27 06:52 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntApplyTaskNG.java
> +  @Inject private ScmConnectorMapperDelegate scmConnectorMapperDelegate;
done

2023-07-27 06:52 UTC, sourabh-awashti commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java
> -        gitConfigAuthenticationInfoHelper.getEncryptedDataDetails(gitConfigDTO, sshKeySpecDTO, basicNGAccessObject);
done

2023-07-27 06:58 UTC, sourabh-awashti commented
trigger uts

2023-07-27 08:16 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformDestroyTaskHandler.java
> +  @Inject GitHubAppAuthenticationHelper gitHubAppAuthenticationHelper;
This helper seems is not used: gitHubAppAuthenticationHelper

2023-07-27 08:16 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandler.java
> +  @Inject GitHubAppAuthenticationHelper gitHubAppAuthenticationHelper;
This helper seems is not used: gitHubAppAuthenticationHelper

2023-07-27 09:57 UTC, sourabh-awashti commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +  public ScmConnector getScmConnectorForGithubAppAuth(ScmConnector scmConnector, String accountIdentifier) {
It will return scm connector only in case of github app and  in any other case it will return gitConfigDTO, thats why i named it specific to github app

2023-07-27 10:03 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformDestroyTaskHandler.java
> +  @Inject GitHubAppAuthenticationHelper gitHubAppAuthenticationHelper;
done

2023-07-27 10:03 UTC, sourabh-awashti commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandler.java
> +  @Inject GitHubAppAuthenticationHelper gitHubAppAuthenticationHelper;
done

2023-07-27 10:30 UTC, yogesh-chauhan commented on 440-connector-nextgen/src/main/java/io/harness/connector/validator/scmValidators/GitConfigAuthenticationInfoHelper.java
> +    if (scmConnector instanceof GithubConnectorDTO) {
can we use this
```java
GitAuthenticationDecryptionHelper.isGitHubAppAuthentication(githubConnectorDTO) ?

```

2023-07-27 11:21 UTC, sourabh-awashti commented
trigger uts

2023-07-28 05:20 UTC, sourabh-awashti commented on 440-connector-nextgen/src/main/java/io/harness/connector/validator/scmValidators/GitConfigAuthenticationInfoHelper.java
> +    if (scmConnector instanceof GithubConnectorDTO) {
done

2023-07-28 05:21 UTC, sourabh-awashti commented
trigger uts

2023-07-28 06:02 UTC, sourabh-awashti commented
trigger uts

2023-07-28 06:03 UTC, sourabh-awashti commented
trigger messagecheck

2023-07-28 06:12 UTC, yogesh-chauhan requested changes

2023-07-28 06:12 UTC, yogesh-chauhan commented on 440-connector-nextgen/src/main/java/io/harness/connector/validator/scmValidators/GitConfigAuthenticationInfoHelper.java
> +        && GitAuthenticationDecryptionHelper.isGitHubAppAuthentication(scmConnector)) {
GitAuthenticationDecryptionHelper.isGitHubAppAuthentication already checks for 
```java
scmConnector instanceof GithubConnectorDTO
```

2023-07-28 06:25 UTC, sourabh-awashti commented on 440-connector-nextgen/src/main/java/io/harness/connector/validator/scmValidators/GitConfigAuthenticationInfoHelper.java
> +        && GitAuthenticationDecryptionHelper.isGitHubAppAuthentication(scmConnector)) {
done

2023-07-28 06:36 UTC, sourabh-awashti commented
trigger uts

2023-07-28 06:37 UTC, vlica-harness approved these changes

2023-07-28 09:18 UTC, yogesh-chauhan approved these changes

2023-07-28 09:21 UTC, sourabh-awashti commented
trigger review

2023-07-28 09:30 UTC, merged