[fix]: [CDS-75402]: BE changes for ImportFromGit Functionality
harness/harness-core pull request #51012
Opened 2023-07-26 10:16 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-26 10:20 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51012)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1073 at r1](https://reviewable.io/reviews/harness/harness-core/51012#-NaGhVJE8NpkVCPMm2WM:-NaGhVJE8NpkVCPMm2WN:b8w4bh2) ([raw file](https://github.com/harness/harness-core/blob/9a57653f1ce04421f27ed87476d36bb39e6e1222/pipeline-service/contracts/openapi/v1/openapi.yaml#L1073)):*
> ```YAML
>         pipeline_yaml:
>           type: string
>           description: Pipeline YAML (to be passed as a String). If Pipeline YAML is not passed but the git details are passed, Pipeline YAML present in the corresponding filePath will be imported.
> ```

get @SudarshanPurohit approval for the same



_Code quote:_
```YAML
If Pipeline YAML is not passed but the git details are passed, Pipeline YAML present in the corresponding filePath will be imported.
```


<!-- Sent from Reviewable.io -->

2023-07-26 10:21 UTC, vtxorxwitty commented
Yes @archit-harness I have sent a DM to him about this.

2023-07-26 10:21 UTC, vtxorxwitty commented
trigger messagecheck

2023-07-26 10:23 UTC, vtxorxwitty commented
trigger uts

2023-07-26 11:59 UTC, USB-05 commented
trigger cp

2023-07-31 07:16 UTC, vtxorxwitty commented
trigger checkstylecodeformat

2023-07-31 07:17 UTC, brijeshdhakar approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51012)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-31 09:18 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51012)* status: 3 file(s) to review. 2 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1073 at r2](https://reviewable.io/reviews/harness/harness-core/51012#-NafEGsU3Q7tHr_tqk2Y:-NafEGsV0uYCYxQcM8u1:bwnk0xp) ([raw file](https://github.com/harness/harness-core/blob/4e05f2f21c29963b29656d76f5b6f125efb221dc/pipeline-service/contracts/openapi/v1/openapi.yaml#L1073)):*
> ```YAML
>         pipeline_yaml:
>           type: string
>           description: Pipeline YAML (to be passed as a String). If Pipeline YAML is not passed but the git details are passed, Pipeline YAML present in the corresponding filePath will be imported.
> ```

Does this mean "create-pipeline" call is same as "import-pipeline" call? If yes, why do we want to combine these things together instead of creating new endpoint? IMO it creates unnecessary confusion as based on different set of params we are interpreting it differently and taking decisions.


<!-- Sent from Reviewable.io -->

2023-07-31 09:25 UTC, archit-harness requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51012)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1073 at r2](https://reviewable.io/reviews/harness/harness-core/51012#-NafEGsU3Q7tHr_tqk2Y:-NafFT5A3PheiA5gJXUs:byojrs6) ([raw file](https://github.com/harness/harness-core/blob/4e05f2f21c29963b29656d76f5b6f125efb221dc/pipeline-service/contracts/openapi/v1/openapi.yaml#L1073)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Does this mean "create-pipeline" call is same as "import-pipeline" call? If yes, why do we want to combine these things together instead of creating new endpoint? IMO it creates unnecessary confusion as based on different set of params we are interpreting it differently and taking decisions.
</blockquote></details>

@naidu-harness @SudarshanPurohit  i believe we should not combine this in openapi spec and have separate API only. and in TF we can include a mode for it?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/51012#-NafCqr01EW2waX7ffNT:-NafCqr1-9AYzH4pFPkB:bmdoitg) ([raw file](https://github.com/harness/harness-core/blob/4e05f2f21c29963b29656d76f5b6f125efb221dc/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L123)):*
> ```Java
> 
>       } else {
>         String hint = "Please check if the Pipeline Yaml given is correct.";
> ```

@vtxorxwitty the hint is wrong, we should mention as yaml is empty, git details should be present to treat as git import


<!-- Sent from Reviewable.io -->

2023-08-03 09:28 UTC, closed without merging