feat: [CET-1349] Add pipeline variables for CET collector URL & agent token
harness/harness-core pull request #51030
Opened 2023-07-26 14:23 UTC by angelo-m-rodriguez

## Describe your changes
Added two new, error tracking related, pipeline expressions: 1) cet.defaultAgentToken 2) cet.collectorUrl. Also created new error tracking client module that the pipeline service can use to fetch the values of the above two expressions from the error tracking backend.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-26 14:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=51030) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=51030) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=51030) it.</sub>

2023-08-04 01:48 UTC, angelo-m-rodriguez commented
trigger uts

2023-08-04 13:16 UTC, angelo-m-rodriguez commented
trigger ut0

2023-08-13 14:36 UTC, archit-harness requested changes
> Reviewed 8 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51030)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/build/container/scripts/replace_configs.sh` line 535 at r1](https://reviewable.io/reviews/harness/harness-core/51030#-NbjIzlO5JeSCaW_vLlI:-NbjIzlO5JeSCaW_vLlJ:b-mcdduu) ([raw file](https://github.com/harness/harness-core/blob/c9b1e2200e915fddaa4953a1e9adb62ec8bdc379/pipeline-service/build/container/scripts/replace_configs.sh#L535)):*
> ```Shell
> replace_key_value notificationClient.secrets.notificationClientSecret "$NOTIFICATION_CLIENT_SECRET"
> 
> replace_key_value errorTrackingClientConfig.errorTrackingServiceConfig.baseUrl "$ERROR_TRACKING_SERVICE_BASE_URL"
> ```

add this env variables directly in config.yml and not in replace configs.sh
___
*[`pipeline-service/config/config.yml` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/51030#-NbjJB2N3-Je_ibBpyqv:-NbjJB2N3-Je_ibBpyqw:b1lv15n) ([raw file](https://github.com/harness/harness-core/blob/c9b1e2200e915fddaa4953a1e9adb62ec8bdc379/pipeline-service/config/config.yml#L224)):*
> ```YAML
> errorTrackingClientConfig:
>   errorTrackingServiceConfig:
>     baseUrl: http://localhost:9191/api/
> ```

add env variable here diectly
___
*[`pipeline-service/container/scripts/replace_configs.sh` line 513 at r1](https://reviewable.io/reviews/harness/harness-core/51030#-NbjJEiq6pfnlIQTpnYg:-NbjJEiq6pfnlIQTpnYh:bsuoyq9) ([raw file](https://github.com/harness/harness-core/blob/c9b1e2200e915fddaa4953a1e9adb62ec8bdc379/pipeline-service/container/scripts/replace_configs.sh#L513)):*
> ```Shell
> 
> replace_key_value errorTrackingClientConfig.errorTrackingServiceConfig.baseUrl "$ERROR_TRACKING_SERVICE_BASE_URL"
> replace_key_value errorTrackingClientConfig.errorTrackingServiceSecret "$ERROR_TRACKING_SERVICE_SECRET"
> ```

not required
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/51030#-NbjJffb6phXWjBJExWJ:-NbjJffb6phXWjBJExWK:b-a6wvrh) ([raw file](https://github.com/harness/harness-core/blob/c9b1e2200e915fddaa4953a1e9adb62ec8bdc379/pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L91)):*
> ```Java
>         new PipelineExecutionFunctor(
>             pmsExecutionService, pipelineExpressionHelper, planExecutionMetadataService, ambiance));
>     addToContext("cet", new ErrorTrackingFunctor(errorTrackingClient, ambiance));
> ```

lets add this functor directly as sdkFunctor in PipelineServiceApplication, check out NextGenApplication
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/ErrorTrackingFunctor.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/51030#-NbjJoIW--R9tASBAcpg:-NbjJoIW--R9tASBAcph:b-kr9am6) ([raw file](https://github.com/harness/harness-core/blob/c9b1e2200e915fddaa4953a1e9adb62ec8bdc379/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/ErrorTrackingFunctor.java#L24)):*
> ```Java
> import java.util.Map;
> 
> @OwnedBy(PIPELINE)
> ```

Team name should be ET and not pipeline


<!-- Sent from Reviewable.io -->

2023-10-05 07:01 UTC, closed without merging