[feat]: [CDS-73527]: Made validate-template-input public with VIEW RBAC permissions.
harness/harness-core pull request #51048
Opened 2023-07-27 05:21 UTC by senjucanon2

## Describe your changes: 
Context: A public api is required by customers to reconcile pipeline

Change: Made the already existing "validate-template-inputs" api public.

Impact: Reconcile API.

Testing: Pending.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-27 06:21 UTC, senjucanon2 commented
trigger uts

2023-07-27 06:24 UTC, utkarshchoubey-harness approved these changes

2023-07-27 06:52 UTC, ankittiwari-harness approved these changes

2023-07-27 06:54 UTC, senjucanon2 commented
trigger review

2023-07-27 06:55 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51048)* status: 1 file(s) to review. 1 change requests. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/51048#-NaL7B434NP_YpoBVQqR:-NaL7B434NP_YpoBVQqS:byb10at) ([raw file](https://github.com/harness/harness-core/blob/2ad80129ac2a47cb7abf5ce8adba5b57c08da797/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L115)):*
> ```Java
>   @GET
>   @Path("validate-template-inputs")
>   @ApiOperation(value = "Validates whether yaml of pipeline is valid or not", nickname = "validateTemplateInputs")
> ```

If we are making API public, we should get approval from docs team as well on the API spec details.

Personally, I'm not able to interpret the descriptions correctly from the ones mentioned right now. We should improve on it.


<!-- Sent from Reviewable.io -->

2023-07-27 08:31 UTC, senjucanon2 commented
trigger uts

2023-07-28 07:12 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51048)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/51048#-NaQKiLQ7rRfWPd8nLH0:-NaQKiLQ7rRfWPd8nLH1:bli9npd) ([raw file](https://github.com/harness/harness-core/blob/008fc8ea071a12f39cca98bb31e5b30f416007a2/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L68)):*
> ```Java
>       , @ApiResponse(code = 500, response = ErrorDTO.class, message = "Internal server error")
>     })
> @Tag(name = "Pipeline", description = "This contains APIs related to validation of templates")
> ```

The description looks incorrect for the tag name provided.


<!-- Sent from Reviewable.io -->

2023-07-28 08:10 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51048)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/51048#-NaL7B434NP_YpoBVQqR:-NaQY-hrATeWaa3ZnZaf:bo212nu) ([raw file](https://github.com/harness/harness-core/blob/2ad80129ac2a47cb7abf5ce8adba5b57c08da797/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L115)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

This ticket is raised by PM, whom else approval is needed?
</blockquote></details>

Have improvised description for fields in Api.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/51048#-NaQKiLQ7rRfWPd8nLH0:-NaQXs4Y1o-RjKwIeIwJ:bz6ufkj) ([raw file](https://github.com/harness/harness-core/blob/008fc8ea071a12f39cca98bb31e5b30f416007a2/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The description looks incorrect for the tag name provided.
</blockquote></details>

Have Improvised tag name and description.


<!-- Sent from Reviewable.io -->

2023-07-28 11:24 UTC, deepakbolangady approved these changes
Approving with the assumption that you will look into these suggestions. Thanks.

2023-07-28 11:24 UTC, deepakbolangady commented on pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java
> +      description = "Validates pipeline yaml for template inputs, and if invalid returns error summary",
```suggestion
      description = "Validates the template inputs in a pipeline's YAML specification. If the template inputs are invalid, the operation returns an error summary.",
```

2023-07-28 11:24 UTC, deepakbolangady commented on pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java
> +      summary = "Validates template inputs in pipeline yaml",
```suggestion
      summary = "Validates template inputs in a pipeline's YAML specification.",
```

2023-07-28 11:24 UTC, deepakbolangady commented on pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java
> +            description = "Returns pipeline yaml validation result for template inputs present in pipeline yaml")
```suggestion
            description = "Returns a validation result for template inputs present in a pipeline's YAML specification.")
```

2023-07-28 11:24 UTC, deepakbolangady commented on pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java
> +            description = "Returns pipeline yaml validation result for template inputs present in pipeline yaml")
```suggestion
            description = "Returns a validation result for template inputs present in a pipeline's YAML specification.")
```

2023-07-28 11:24 UTC, deepakbolangady commented on pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java
> +            description = "Returns pipeline yaml validation result for template inputs present in pipeline yaml")
```suggestion
            description = "Returns a validation result for template inputs present in a pipeline's YAML specification.")
```

2023-07-31 04:29 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51048)* status: 1 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/51048#gh-1277398651:-NaeCAFM5SQOzZna8SbL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac238bf84495b60c7e455d07eab4ab67301851c3/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L117)):*
<details><summary><i>Previously, deepakbolangady (Deepak Bolangady) wrote…</i></summary><blockquote>

```suggestion
  @ApiOperation(value = "Validates the YAML specification of a pipeline.", nickname = "validateTemplateInputs")
```
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/51048#gh-1277414607:-NaeCAaN0qFk6jxLXOfy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac238bf84495b60c7e455d07eab4ab67301851c3/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L120)):*
<details><summary><i>Previously, deepakbolangady (Deepak Bolangady) wrote…</i></summary><blockquote>

```suggestion
      description = "Validates the template inputs in a pipeline's YAML specification. If the template inputs are invalid, the operation returns an error summary.",
```
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 121 at r4](https://reviewable.io/reviews/harness/harness-core/51048#gh-1277415345:-NaeCBtRDquFMb1639c5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac238bf84495b60c7e455d07eab4ab67301851c3/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L121)):*
<details><summary><i>Previously, deepakbolangady (Deepak Bolangady) wrote…</i></summary><blockquote>

```suggestion
      summary = "Validates template inputs in a pipeline's YAML specification.",
```
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/51048#gh-1277426659:-NaeCCFN6yL1kUqMXtgS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac238bf84495b60c7e455d07eab4ab67301851c3/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L125)):*
<details><summary><i>Previously, deepakbolangady (Deepak Bolangady) wrote…</i></summary><blockquote>

```suggestion
            description = "Returns a validation result for template inputs present in a pipeline's YAML specification.")
```
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/51048#gh-1277427217:-NaeCCjU6E6A5Scx7exU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac238bf84495b60c7e455d07eab4ab67301851c3/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L125)):*
<details><summary><i>Previously, deepakbolangady (Deepak Bolangady) wrote…</i></summary><blockquote>

```suggestion
            description = "Returns a validation result for template inputs present in a pipeline's YAML specification.")
```
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/51048#gh-1277427239:-NaeCDAz6m2E679qMfbb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac238bf84495b60c7e455d07eab4ab67301851c3/pipeline-service/service/src/main/java/io/harness/pms/template/PipelineRefreshResource.java#L125)):*
<details><summary><i>Previously, deepakbolangady (Deepak Bolangady) wrote…</i></summary><blockquote>

```suggestion
            description = "Returns a validation result for template inputs present in a pipeline's YAML specification.")
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-31 06:11 UTC, senjucanon2 commented
trigger uts

2023-07-31 06:46 UTC, mohitg0795 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51048)* status: 1 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-31 07:21 UTC, senjucanon2 commented
trigger uts

2023-07-31 09:27 UTC, archit-harness reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51048)* status: 2 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-07-31 09:45 UTC, mohitg0795 approved these changes

2023-07-31 09:46 UTC, senjucanon2 commented
trigger review

2023-07-31 10:08 UTC, shalini-agr approved these changes

2023-07-31 10:08 UTC, senjucanon2 commented
trigger review

2023-07-31 10:11 UTC, merged