feat: [PL-39269]: load certificate from a common source of truth
harness/harness-core pull request #51054
Opened 2023-07-27 06:41 UTC by xingchi-jin

## Describe your changes
1. Certificate will be loaded from a common source of truth specified by env CUSTOM_CERTS_PATH
2. With many experiments, only x509 ca certs can be supported by both RHEL and keytool. PEM format can contain multiple certs in a bundle file, while DER format can contain only one
3. When it's a PEM file, it will reach blocks one by one and import to truststore. 
4. Updated the connectivity check script, because when test with SMP environment, I realize the SMP ca certs are EV certs, which doesn't exist in normal RHEL ca bundle file even after running update-ca-trust. It exists in ca.bundle.trust.crt
5. the load cert script will only be executed when CUSTOM_CERTS_PATH is set AND when there are files in CUSTOM_CERTS_PATH 

Tests
1. Tested with SMP 
<img width="1712" alt="image" src="https://github.com/harness/harness-core/assets/109999795/7679b3c5-ed8e-4a8d-8de6-d4078201c3b5">
<img width="1126" alt="image" src="https://github.com/harness/harness-core/assets/109999795/61363c32-92b7-46c8-b828-1aa20b325b17">
2. Connectivity script test
<img width="780" alt="image" src="https://github.com/harness/harness-core/assets/109999795/087fba77-cb4f-4fad-a84e-35cef98f4597">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-12 00:25 UTC, xingchi-jin commented
trigger uts

2023-08-12 02:02 UTC, xingchi-jin commented
trigger uts

2023-08-21 03:18 UTC, bharatgoelharness requested changes

2023-08-21 03:18 UTC, bharatgoelharness commented on dockerization/delegate/Dockerfile-minimal
> +COPY delegate.jar /opt/harness-delegate/
@xingchi-jin why you have changed this?

2023-09-05 20:23 UTC, xingchi-jin commented on dockerization/delegate/Dockerfile-minimal
> +COPY delegate.jar /opt/harness-delegate/
sorry, removed

2023-09-05 20:31 UTC, xingchi-jin commented on dockerization/delegate/Dockerfile
> +ENV ADDITIONAL_CERTS_PATH=/opt/harness-delegate/additional_certs_pem_split
the ADDITIONAL_CERTS_PATH is described in the CI document https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates/#enable-self-signed-certificates 

I think the HARNESS_ADDITIONAL_CERTS_DIR is specified on the CI lite-engine

2023-09-05 20:47 UTC, williamwissemann commented on dockerization/delegate/Dockerfile
> +ENV ADDITIONAL_CERTS_PATH=/opt/harness-delegate/additional_certs_pem_split
My understanding is that `ADDITIONAL_CERTS_PATH` & `CI_MOUNT_VOLUMES` (in the docs) are combined to from `HARNESS_ADDITIONAL_CERTS_DIR` and `HARNESS_ADDITIONAL_CERTS_LIST`. Without `CI_MOUNT_VOLUMES` being specified, I'm not sure the certificates will be passed through to the CI steps.
  
 CC: @r0610205

2023-09-06 15:17 UTC, r0610205 approved these changes

2023-09-11 15:42 UTC, xingchi-jin commented
trigger uts

2023-09-14 03:57 UTC, bharatgoelharness submitted a review, later dismissed

2023-09-14 05:17 UTC, xingchi-jin commented on dockerization/delegate/Dockerfile
> +ENV ADDITIONAL_CERTS_PATH=/opt/harness-delegate/additional_certs_pem_split
we have addressed this in our meeting.

2023-09-14 05:17 UTC, xingchi-jin commented
trigger uts

2023-09-14 05:29 UTC, xingchi-jin commented
trigger uts

2023-09-14 06:10 UTC, bharatgoelharness approved these changes

2023-09-14 17:27 UTC, raghuAtWings approved these changes

2023-09-14 17:43 UTC, xingchi-jin reviewed
> Reviewed 1 of 3 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51054)* status: 5 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-14 17:44 UTC, merged