feat: [CI-9028]: support qa remote debug
harness/harness-core pull request #51077
Opened 2023-07-27 13:39 UTC by HenAmar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-27 16:13 UTC, HenAmar commented
trigger messagecheck

2023-07-27 16:21 UTC, HenAmar commented
trigger uts

2023-07-27 20:15 UTC, HenAmar commented
trigger uts

2023-07-28 11:07 UTC, raghavharness requested changes

2023-07-28 11:07 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/ci/ff/impl/CIFeatureFlagServiceImpl.java
> +  private static final int CACHE_EVICTION_TIME_MINUTES = 1;
Is this added by mistake ?

2023-07-28 11:07 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/execution/ExecutionServiceConfig.java
> +  String tmateEndpoint;
This is used in CD container steps. For this to work pipeline service config needs to be updates as well

2023-07-28 11:07 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/steps/container/execution/ContainerExecutionConfig.java
> +        tmateEndpoint);
Same as above

2023-07-28 12:05 UTC, HenAmar commented
trigger uts

2023-07-28 12:33 UTC, raghavharness requested changes

2023-07-28 12:33 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/execution/ExecutionServiceConfig.java
> +  String tmateEndpoint;
Can we just keep this value in CIExecutionServiceConfig since CD doesn't need it

2023-07-28 12:33 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/steps/container/execution/ContainerExecutionConfig.java
>      super(addonImageTag, liteEngineImageTag, defaultInternalImageConnector, delegateServiceEndpointVariableValue,
We can remove it from here

2023-07-28 12:56 UTC, HenAmar commented
trigger uts

2023-07-28 12:57 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/steps/container/execution/ContainerExecutionConfig.java
> +          "logStreamingContainerStepBaseUrl", "pluginConfig", "containerStepGroupConfig", "tmateEndpoint"})
You can remove this,

2023-07-28 13:02 UTC, raghavharness approved these changes

2023-07-28 13:04 UTC, HenAmar commented
trigger uts

2023-07-29 21:01 UTC, HenAmar commented
trigger uts

2023-07-29 21:47 UTC, jamie-harness approved these changes

2023-07-29 21:47 UTC, jamie-harness approved these changes

2023-07-29 21:52 UTC, merged