start coding
harness/harness-core pull request #51087
Opened 2023-07-27 16:41 UTC by rafaelmart1ns

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-31 17:28 UTC, rafaelmart1ns commented
trigger smartchecks

2023-07-31 17:48 UTC, rafaelmart1ns commented
trigger smartchecks

2023-07-31 19:07 UTC, rafaelmart1ns commented
trigger messagecheck

2023-07-31 19:21 UTC, lasdox commented
Please add unit testing

2023-08-01 09:37 UTC, hextechpal requested changes

2023-08-01 09:37 UTC, hextechpal commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +  @Inject @Transient private transient StateExecutionService stateExecutionService;
Only one transient is required, stick with dev morphia one

2023-08-01 09:37 UTC, hextechpal commented on 400-rest/src/main/java/software/wings/sm/states/ApprovalState.java
> +  @Inject private DelegateServiceImpl delegateService;
Is this needed

2023-08-01 09:37 UTC, hextechpal commented on 400-rest/src/main/java/software/wings/sm/states/ApprovalState.java
> +  @Inject SettingsService settingService;
Is this needed?

2023-08-01 09:37 UTC, hextechpal commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +public class ApprovalPollingCallback implements OldNotifyCallback {
Please add tests for this class

2023-08-01 09:37 UTC, hextechpal commented on 400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java
> +        waitNotifyEngine.waitForAllOn(OrchestrationNotifyEventListener.ORCHESTRATION, callback, taskId);
Extract into a diff method and add tests for the same

2023-08-02 12:43 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/sm/states/ApprovalState.java
> +  @Inject private DelegateServiceImpl delegateService;
Yes, because I need some information to check approval.

2023-08-02 12:43 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/sm/states/ApprovalState.java
> +  @Inject SettingsService settingService;
Yes, because I need some information to check approval.

2023-08-02 19:02 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +public class ApprovalPollingCallback implements OldNotifyCallback {
It was added.

2023-08-02 19:02 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/JiraHelperService.java
> +        waitNotifyEngine.waitForAllOn(OrchestrationNotifyEventListener.ORCHESTRATION, callback, taskId);
It was changed.

2023-08-02 19:08 UTC, lasdox commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +  ApprovalPollingJobEntity entity;
these should be private with @Getter i guess?

2023-08-02 19:09 UTC, lasdox commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +  @Inject @Transient private WaitNotifyEngine waitNotifyEngine;
you dont need to add @Transient since this will not be persisted, instead mark @Transient or transient if this will not be persisted anywhere.

2023-08-02 19:12 UTC, lasdox commented on 400-rest/src/main/java/software/wings/sm/states/ApprovalState.java
> +  @Inject private DelegateServiceImpl delegateService;
I dont see this being used anywhere

2023-08-02 19:12 UTC, lasdox commented on 400-rest/src/main/java/software/wings/sm/states/ApprovalState.java
> +  @Inject SettingsService settingService;
I dont see this being used anywhere

2023-08-02 19:43 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +  ApprovalPollingJobEntity entity;
it was changed.

2023-08-02 19:44 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +  @Inject @Transient private WaitNotifyEngine waitNotifyEngine;
it was changed

2023-08-02 19:45 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/ApprovalPollingCallback.java
> +  @Inject @Transient private transient StateExecutionService stateExecutionService;
it was changed.

2023-08-02 19:57 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/sm/states/ApprovalState.java
> +  @Inject private DelegateServiceImpl delegateService;
You are right, it was removed.

2023-08-03 14:06 UTC, hextechpal approved these changes
> Reviewed 10 of 14 files at r3, 2 of 5 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51087)* status: 16 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-03 14:43 UTC, hextechpal submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51087)* status: 16 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-03 18:44 UTC, rafaelmart1ns commented
trigger uts_JDK11

2023-08-03 19:04 UTC, rafaelmart1ns commented
trigger uts_JDK11

2023-08-03 19:13 UTC, vcalasansh approved these changes
> Reviewed 10 of 14 files at r3, 2 of 4 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51087)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-03 19:23 UTC, lasdox submitted a review, later dismissed

2023-08-03 19:24 UTC, rafaelmart1ns commented
trigger reviews

2023-08-03 19:26 UTC, rafaelmart1ns commented
trigger review

2023-08-03 20:21 UTC, rafaelmart1ns commented
trigger ut8

2023-08-04 14:17 UTC, vcalasansh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51087#-:-Nb-uIN4BB3LauGE5G4z:bnfp4nl)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-04 14:30 UTC, lasdox approved these changes

2023-08-04 14:30 UTC, rafaelmart1ns commented
trigger review

2023-08-04 14:31 UTC, merged