fix: [CDS-58921]: oc version upgrade to 4.8.57
harness/harness-core pull request #51112
Opened 2023-07-28 06:05 UTC by TarunUba1

## Describe your changes
updating oc bindary to 4.8.57, latest 4.8 version

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-02 08:00 UTC, alebuh commented
Do we need to upgrade only for immutable delegate or for legacy as well? I thought that we need to do it only for immutable?

2023-08-02 10:18 UTC, GoelPratyush99 requested changes
We still have these 2 files left to update the OC version 
<img width="1539" alt="Screenshot 2023-08-02 at 3 48 03 PM" src="https://github.com/harness/harness-core/assets/97931011/37ddd77a-c5a2-4077-be58-6f7b2b2b49d6">

2023-08-03 09:02 UTC, TarunUba1 commented
> Do we need to upgrade only for immutable delegate or for legacy as well? I thought that we need to do it only for immutable?

2023-08-08 12:32 UTC, markoharness requested changes
Shouldn't these classes also need to be updated?

io.harness.delegate.clienttools.OcVersion
io.harness.delegate.service.K8sGlobalConfigServiceImpl
dockerization/delegate-proxy/setup.sh
dockerization/delegate/scripts/client_tools.sh
on-prem/disconnected_on_prem_pov_installer/generate.sh
on-prem/dockerless_pov_installer_generator/generate_installer.sh
on-prem/harness_disconnected_on_prem_pov_final/install_harness.sh

and appropriate UT classes as well

2023-08-08 13:53 UTC, bharatgoelharness requested changes
did you tested this version for arm64 and amd64 both?

Please update the testing done as part of pr in description.

2023-08-30 06:45 UTC, alebuh requested changes

2023-08-30 06:45 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/delegate/clienttools/OcVersion.java
> +  V4_13("v4.13.4");
Are we using this enum anywhere? If not why do we need to add it?

2023-08-31 07:13 UTC, alebuh submitted a review, later dismissed

2023-09-01 15:28 UTC, TarunUba1 commented
trigger uts

2023-09-04 10:35 UTC, TarunUba1 commented
trigger commonchecks

2023-09-04 10:50 UTC, TarunUba1 commented
trigger uts

2023-09-04 11:12 UTC, alebuh approved these changes

2023-09-04 11:53 UTC, GoelPratyush99 approved these changes

2023-09-04 11:57 UTC, TarunUba1 commented
trigger review

2023-09-04 14:48 UTC, merged