Yaml simplification poc
harness/harness-core pull request #51155
Opened 2023-07-30 20:07 UTC by mohitg0795

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-25 08:27 UTC, brijeshdhakar requested changes
> Reviewed 34 of 39 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 39 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/YamlConfig.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAKeV13E1yXG9ixyOC:-NfAKeV13E1yXG9ixyOD:b-o7twmr) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/merger/YamlConfig.java#L122)):*
> ```Java
>       ArrayNode elements = (ArrayNode) jsonNode.get(currentFieldName);
>       for (int i = 0; i < elements.size(); i++) {
>         String resultantType = getParentNodeTypeForGivenFQNField(fqn, currentFqnIndex + 1, elements.get(i));
> ```

Why are we calling the `getParentNodeTypeForGivenFQNField` for each array element? And if we are calling for all array elements then we should have some condition to discard other elements and iterate internally only the correct iteration.

Like: there should be some index or identifier/name fields to select the correct element from the complete array?

I think it might give incorrect result.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfALhtKCE08txp8fS_G:-NfALhtKCE08txp8fS_H:bi54xev) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java#L37)):*
> ```Java
>     String fqnFromParentNode = "";
>     for (FQNNode fqnNode : fqn.getFqnList()) {
>       if (fqnNode.getKey().equals("stage") || fqnNode.getKey().equals("step")) {
> ```

there can be stepGroup as well as parent? There should be some method to check if current node is of parent type


<!-- Sent from Reviewable.io -->

2023-09-25 10:10 UTC, archit-harness requested changes
> Reviewed 26 of 39 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/YamlConfig.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAKeV13E1yXG9ixyOC:-NfA_oDO8y3jnMqnYCcn:bver3m6) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/merger/YamlConfig.java#L122)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why are we calling the `getParentNodeTypeForGivenFQNField` for each array element? And if we are calling for all array elements then we should have some condition to discard other elements and iterate internally only the correct iteration.

Like: there should be some index or identifier/name fields to select the correct element from the complete array?

I think it might give incorrect result.
</blockquote></details>

can we add UT for the same?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputDetails.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAd-yk4DG3iebHWONb:-NfAd-yk4DG3iebHWONc:bjao9cj) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputDetails.java#L8)):*
> ```Java
>  */
> 
> package io.harness.pms.yaml;
> ```

should we remove pms package from all these common dtos? as its generic, same for below
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputDetails.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAdbiLCXYLRb5d29Ui:-NfAdbiLCXYLRb5d29Uj:b-fqqcs5) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputDetails.java#L21)):*
> ```Java
>   boolean required;
>   Object defaultValue;
> }
> ```

nit: when we add validators in future, these will be added here?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAdgbq73mHcT1S7MHF:-NfAdgbq73mHcT1S7MHG:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java#L8)):*
> ```Java
>  */
> 
> package io.harness.pms.yaml;
> ```

same as above
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAeIlTAZ54tRXyhzOL:-NfAeIlTAZ54tRXyhzOM:bwhgg6f) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java#L37)):*
> ```Java
>     String fqnFromParentNode = "";
>     for (FQNNode fqnNode : fqn.getFqnList()) {
>       if (fqnNode.getKey().equals("stage") || fqnNode.getKey().equals("step")) {
> ```

we should use YamlfieldNameConstants and not hard coded value in code
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfALhtKCE08txp8fS_G:-NfAeNZL2LEJYKmzlLji:b-y205eh) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java#L37)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

there can be stepGroup as well as parent? There should be some method to check if current node is of parent type
</blockquote></details>

+1, plus wouldnt this parent logic change based on v0 or v1?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAeWcw53IkGwS67pou:-NfAeWcw53IkGwS67pov:b-ff8kay) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java#L8)):*
> ```Java
>  */
> 
> package io.harness.pms.yaml;
> ```

shouldnt be in pms
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAe_gMEP4sx93TlBM5:-NfAe_gMEP4sx93TlBM6:bu4d7eh) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java#L72)):*
> ```Java
>   private boolean checkNodeType(JsonNode jsonNode, String field, JsonNodeType jsonNodeType) {
>     if (isPresent(jsonNode, field)) {
>       return jsonNode.get(field).getNodeType() == jsonNodeType;
> ```

@brijeshdhakar i think there are built-in methods to check on jsonNode is array, object, string etc 
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlFieldConstants.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAekYi4n4dMGPFnpXC:-NfAekYi4n4dMGPFnpXD:b-15smk1) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlFieldConstants.java#L10)):*
> ```Java
> package io.harness.pms.yaml;
> 
> public enum YamlFieldConstants {
> ```

we already have YamlFieldNameConstants, how these are different? or change to SchemaFieldConstants
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputType.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAevqm9FrjwYgvlRUM:-NfAevqm9FrjwYgvlRUN:b5xvkf0) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputType.java#L10)):*
> ```Java
> package io.harness.pms.yaml;
> 
> public enum YamlInputType {
> ```

Can we rename to SchemaInputType?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAexrFD3QPXnKZR3Z2:-NfAexrFD3QPXnKZR3Z3:b-ryxpe6) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L30)):*
> ```Java
> @Slf4j
> @OwnedBy(PIPELINE)
> public class YamlInputUtils {
> ```

SchemaInputUtils?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAf-gT04kCMlsC_na2:-NfAf-gT04kCMlsC_na3:btyw654) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L31)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class YamlInputUtils {
>   private Set<String> terminalParentNodes = Set.of("pipeline", "template", "stage", "step");
> ```

wouldnt this be different for v0 and v1?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAgeh_ADkHogV2GVT0:-NfAgeh_ADkHogV2GVT1:btbpl0z) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L158)):*
> ```Java
>   }
> 
>   private InputDetails buildInputJsonNode(JsonNode inputNode, String inputName) {
> ```

can we rename this to buildInputsDetails
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 167 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAgZ8T-wNmOzhEcASY:-NfAgZ8T-wNmOzhEcASZ:b-x67ro4) [...]

2023-09-25 10:13 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputDetails.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAd-yk4DG3iebHWONb:-NfAp7Fg-run2ycqFiD3:b-juz9l1) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputDetails.java#L8)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should we remove pms package from all these common dtos? as its generic, same for below
</blockquote></details>

These are the ones that are redundant and have to be deleted as discussed, will remove them


<!-- Sent from Reviewable.io -->

2023-09-25 10:19 UTC, brijeshdhakar commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAe_gMEP4sx93TlBM5:-NfAqPF-B5snE61nqwqD:bluh65e) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar i think there are built-in methods to check on jsonNode is array, object, string etc
</blockquote></details>

Yes its jsonNode.isArray()


<!-- Sent from Reviewable.io -->

2023-09-25 10:27 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfALhtKCE08txp8fS_G:-NfAsGl_5wrOSmM5dCGr:b-lpfo0q) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1, plus wouldnt this parent logic change based on v0 or v1?
</blockquote></details>

this is old file, will be deleted.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAeIlTAZ54tRXyhzOL:-NfAsITA9DFYswJFfsbI:b-lpfo0q) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should use YamlfieldNameConstants and not hard coded value in code
</blockquote></details>

this is old file, will be deleted.


<!-- Sent from Reviewable.io -->

2023-09-25 10:27 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAeWcw53IkGwS67pou:-NfAsJx24tUqK3saD57t:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java#L8)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt be in pms
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-25 10:32 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlFieldConstants.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAekYi4n4dMGPFnpXC:-NfAtF1D6izkTQlCzuWv:b1ubba2) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlFieldConstants.java#L10)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

By looking at it, not able to make out any difference, so will change usages to YamlFieldNameConstants
</blockquote></details>

Oh ok got it. So, I did make a dedicated class so that my other util classes can dedicatedly work on it instead of working on "string" arguments. eg: JsonFieldUtil class works dedicatedly on YamlFieldConstants only, it doesn't take string as argument for any field.
I shall rename the class to YamlSchemaFieldConstants for clarity.


<!-- Sent from Reviewable.io -->

2023-09-25 10:34 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputType.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAevqm9FrjwYgvlRUM:-NfAtwSt5gyQcHCSzgLL:bdjz3pt) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputType.java#L10)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we rename to SchemaInputType?
</blockquote></details>

both look fine to me, let me rename if that suits better


<!-- Sent from Reviewable.io -->

2023-09-25 10:35 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAexrFD3QPXnKZR3Z2:-NfAuABP3yR3TZkXb-Te:b-uabx0m) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

SchemaInputUtils?
</blockquote></details>

redundant file, deleted it
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAf-gT04kCMlsC_na2:-NfAuBJ-CB7R7uXgrTi_:b-uabx0m) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

wouldnt this be different for v0 and v1?
</blockquote></details>

redundant file, deleted it
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAgeh_ADkHogV2GVT0:-NfAuC-79FlCccpVrHBv:b-uabx0m) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L158)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename this to buildInputsDetails
</blockquote></details>

redundant file, deleted it
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 167 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAgZ8T-wNmOzhEcASY:-NfAuCe-17Ck7Tc_Fthf:b-uabx0m) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L167)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont this hardCoded value, and use constants class
</blockquote></details>

redundant file, deleted it
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAfCB-8qQ-HZ48hLhY:-NfAuD4w5zyGNfC2LcRN:b-uabx0m) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputUtils.java#L174)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

wouldnt this logic be dependent upon yaml version?, same true for this method
</blockquote></details>

redundant file, deleted it


<!-- Sent from Reviewable.io -->

2023-09-25 11:12 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 789 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAhJdYA3-npo38R6Yi:-NfB1cFJ57BZyYOO0q1t:bcqdxfc) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L789)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what does this method do? its getting equivalent fqn node for given jsonNode?
</blockquote></details>

It follows the FQN and finds out the respective node from the given jsonNode


<!-- Sent from Reviewable.io -->

2023-09-25 11:17 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/individualschema/InputFieldMetadata.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAhpp2E3bfH1jWbKJB:-NfB2kHH1cxTq9tQ08WQ:br09kl9) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/yaml/individualschema/InputFieldMetadata.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar in v1 we dont have stage/step keyword, so how it will work? or is it working only as of now for v0 and v1 linking?
</blockquote></details>

Yes, this may require changes for V1. For V0, it will work for now.


<!-- Sent from Reviewable.io -->

2023-09-25 11:18 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/DependencyDetails.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAiE1h6HRRyVBp0_7A:-NfB2wRz501y22y_NWEZ:b-9myxfk) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/DependencyDetails.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need Data here?
</blockquote></details>

because we need to set and read values inside this class object.


<!-- Sent from Reviewable.io -->

2023-09-25 11:19 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 18. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/FixedValueDependencyDetails.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAiGxl6IlnrdHUiGRE:-NfB39de-cJN_5LNG8Dr:b-i5nbbb) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/FixedValueDependencyDetails.java#L16)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same here
</blockquote></details>

here, its not required. Fixed.


<!-- Sent from Reviewable.io -->

2023-09-25 11:20 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 19. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/YamlInputDetails.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAiWxBBMbuABe0Nhiv:-NfB3M8TCzx_B1t4NEvt:b-5spr4) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/YamlInputDetails.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what is input details?
</blockquote></details>

Details about input, eg: name, required, description etc.


<!-- Sent from Reviewable.io -->

2023-09-25 11:20 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 20. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/InputMetadata.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAiHr370AtQMoCwest:-NfB3PzQC2WzsZixad8P:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/beans/InputMetadata.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-25 11:23 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 11 file(s) to review. 2 change requests. 21. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java` line 211 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAiZLp8kuNhpolMTCe:-NfB430J2kYmx6LRIRLv:b-mavstq) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java#L211)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need it here, when we introduced in JsonFieldUtils?, plus isArray method exists in JsonNode
</blockquote></details>

isArray method doesn't handle null checks. Moved it for now.


<!-- Sent from Reviewable.io -->

2023-09-25 11:25 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 18 file(s) to review. 2 change requests. 23. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAdgbq73mHcT1S7MHF:-NfB4XKG2HOG9hMgkdaj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/InputFieldMetadata.java#L8)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAe_gMEP4sx93TlBM5:-NfB4Z-F9zZbpok1FsGp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/JsonFieldUtil.java#L72)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Yes its jsonNode.isArray()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-25 11:44 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 18 file(s) to review. 2 change requests. 23. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/YamlConfig.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAKeV13E1yXG9ixyOC:-NfB8lyq2DGx1L33qnJW:bmcom6g) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/merger/YamlConfig.java#L122)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add UT for the same?
</blockquote></details>

Discussed with @brijeshdhakar , we look good here. Will add UT in next PR.


<!-- Sent from Reviewable.io -->

2023-09-25 11:51 UTC, brijeshdhakar commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 789 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAhJdYA3-npo38R6Yi:-NfBAZLb6NvEs09yNm0C:b4o6pko) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L789)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It follows the FQN and finds out the respective node from the given jsonNode
</blockquote></details>

As discussed. Not needed and deleted the method.


<!-- Sent from Reviewable.io -->

2023-09-25 12:01 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 1 of 39 files at r1, 14 of 17 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 18 file(s) to review. 1 change requests. 24. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/individualschema/AbstractStaticSchemaParser.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/51155#-NfAhU6a9CVLQZ0Rnt57:-NfBBJZe67D9KszBB9np:b-ujzss6) ([raw file](https://github.com/harness/harness-core/blob/4dcce1d3544ae896b4312161176bdf90a1bbaa1f/953-yaml-commons/src/main/java/io/harness/yaml/individualschema/AbstractStaticSchemaParser.java#L158)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar please validate if this will work for all cases?
</blockquote></details>

Yes this will work for all cases. Because all the spec nodes for any step/stage nodes are under the allOff.spec path.


<!-- Sent from Reviewable.io -->

2023-09-25 13:11 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 39 files at r1, 14 of 17 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51155)* status: 1 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-25 14:27 UTC, mohitg0795 commented
trigger uts

2023-09-25 16:19 UTC, mohitg0795 commented
trigger uts

2023-09-25 16:26 UTC, ankittiwari-harness submitted a review, later dismissed

2023-09-25 17:43 UTC, mohitg0795 commented
trigger uts

2023-09-26 05:29 UTC, mohitg0795 commented
trigger uts

2023-09-26 05:45 UTC, mohitg0795 commented
trigger uts

2023-09-26 07:52 UTC, mohitg0795 commented
trigger uts

2023-09-26 10:46 UTC, mohitg0795 commented
trigger uts

2023-09-26 11:57 UTC, merged