feat: [PL-39190]: Helm chart url for smp
harness/harness-core pull request #51169
Opened 2023-07-31 09:52 UTC by AnupamIO

For onprem helm chart should be referencing to customer-manager-url not app.harness.io. This is because helm chart is stored in delegate proxy and customer will fetch from there.

For saas it should keep on referring to app.harness.io

Testing:
Tested in local using postman.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-01 13:53 UTC, mdmilic reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51169)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/51169#-NalM_x16LlZ8VCV9FnP:-NalM_x16LlZ8VCV9FnQ:b-hbbzcn) ([raw file](https://github.com/harness/harness-core/blob/2f3a01eba252187b60a8dc7d3c7a25dffda37e32/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L39)):*
> ```Java
>   private static final String TERRAFORM_TEMPLATE_FLE = "/delegatetemplates/delegate-terraform-example-module.ftl";
> 
>   private static final String onPremHelmRepoSuffix = "storage/harness-download/delegate-helm-chart/";
> ```

CAPITALIZE_CORRECTLY :slightly_smiling_face: 
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/51169#-NalMOzm8VzeXduu2pZ2:-NalMOzm8VzeXduu2pZ3:b-pnnb5o) ([raw file](https://github.com/harness/harness-core/blob/2f3a01eba252187b60a8dc7d3c7a25dffda37e32/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L123)):*
> ```Java
>       return saasHelmRepo;
>     }
>     return null;
> ```

Don't return null, just throw exception (e.g. IllegalArgumentException) 


<!-- Sent from Reviewable.io -->

2023-08-01 17:32 UTC, AnupamIO commented
trigger uts

2023-08-01 21:53 UTC, xingchi-jin requested changes

2023-08-01 21:53 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java
> +  private static final String ONPREM_HELM_REPO_SUFFIX = "storage/harness-download/delegate-helm-chart/";
why not create a single variable in MainConfiguration, and set the url in manager config

2023-08-17 06:18 UTC, AnupamIO commented on 400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java
> +  private static final String ONPREM_HELM_REPO_SUFFIX = "storage/harness-download/delegate-helm-chart/";
adding saas url to config.yml, as onprem url is just a suffix so keeping it in this class only.

2023-08-17 08:29 UTC, AnupamIO reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51169)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/51169#gh-1281191543:-Nc1bKCMAlCFS0yhbL-u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ef83fa06c3e03fe5a97d6db763e3948b647fc04/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateInstallationCommandServiceImpl.java#L39)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

why not create a single variable in MainConfiguration, and set the url in manager config 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-17 11:14 UTC, AnupamIO commented
trigger uts

2023-08-17 12:41 UTC, AnupamIO commented
trigger ut7

2023-08-17 13:41 UTC, AnupamIO commented
trigger ut6

2023-08-17 14:41 UTC, AnupamIO commented
trigger messagecheck

2023-08-17 22:03 UTC, xingchi-jin commented on 360-cg-manager/config.yml
> +saasDelegateHelmChartRepo: "https://app.harness.io/storage/harness-download/delegate-helm-chart/"
no very aligned with the implicit way of configuring smp url
can we just define a config called "delegateHelmChartRepo", and just set different values for saap and smp ?

2023-08-24 11:23 UTC, AnupamIO commented on 360-cg-manager/config.yml
> +saasDelegateHelmChartRepo: "https://app.harness.io/storage/harness-download/delegate-helm-chart/"
Xingchi, if we do that then that will mean we will have different set of configuration for smp and saas but at the time same time we have charter to make smp and saas configuration same. Adding different configurations will contradict that.

2023-08-24 11:23 UTC, AnupamIO commented
trigger ut7

2023-08-28 18:36 UTC, AnupamIO commented
trigger uts

2023-08-29 07:15 UTC, AnupamIO commented
trigger ut0

2023-08-29 12:10 UTC, merged