fix: [CDS-74516]: functions to handle taskChainResponse
harness/harness-core pull request #51179
Opened 2023-07-31 13:20 UTC by TarunUba1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-02 09:56 UTC, GoelPratyush99 requested changes

2023-08-02 09:56 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/CustomFetchManifestHandler.java
> +    return null;
Why are we returning null in case the CommandExecutionStatus in SUCCESS for all the scenarios. Shouldn't we return a TaskChainResponse with chainEnd as false and later handle the scenario.

2023-08-02 09:56 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/ManifestHandler.java
> +@OwnedBy(HarnessTeam.CDP)
We can remove OwnedBy When we have CodePulse

2023-08-02 09:56 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/HelmTypeManifestHandler.java
> +public class HelmTypeManifestHandler extends K8sHelmCommonStepHelper implements ManifestHandler {
Inconsistent Name: GitFetch..., CustomFetch.... Should be HelmFetch or something consistent.

2023-08-02 09:56 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/LocalManifestHandler.java
> +    List<ManifestFiles> manifestFiles = k8sStepPassThroughData.getManifestFiles();
Hey you would need to ensure that k8sStepPassThroughData must have an arraylist initialised. 
its better to have 
List<ManifestFiles> manifestFiles = new Arraylist<>();

2023-08-02 09:56 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/LocalManifestHandler.java
> +    List<ValuesManifestOutcome> aggregatedValuesManifests = getAggregatedValuesManifests(manifestOutcomes);
Would you be implementing a separate ManifestHandler for Openshift and Kustomize

2023-08-02 09:56 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/CustomFetchManifestHandler.java
> +    updatedK8sStepPassThroughData.updateOpenFetchFilesStreamStatus();
Not required here we should only do it in prepareFetchResponseForStoreType or Follow a convention to not miss things. Either do before the prepareFetchResponseForStoreType or after it in updatePassThroughData.

2023-08-02 11:06 UTC, abosii-harness requested changes

2023-08-02 11:06 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/HelmTypeManifestHandler.java
> +      return TaskChainResponse.builder().chainEnd(true).passThroughData(helmValuesFetchPassTroughData).build();
Why this is chainEnd true?

2023-08-02 11:06 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/GitFetchManifestHandler.java
> +    List<ValuesManifestOutcome> aggregatedValuesManifests = getAggregatedValuesManifests(manifestOutcomes);
How you're going to integrate this logic to previous one?

2023-08-03 08:38 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/CustomFetchManifestHandler.java
> +    return null;
The idea is to return a taskchainresponse if the fetch failed.
if it doesnt fail then we update the passthroughdata
and then we prepare next task chain response based on the group we selected out.
i have edited the name of the function to clarify

2023-08-03 08:38 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/ManifestHandler.java
> +@OwnedBy(HarnessTeam.CDP)
Done

2023-08-03 08:38 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/HelmTypeManifestHandler.java
> +public class HelmTypeManifestHandler extends K8sHelmCommonStepHelper implements ManifestHandler {
Done

2023-08-03 08:39 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/LocalManifestHandler.java
> +    List<ManifestFiles> manifestFiles = k8sStepPassThroughData.getManifestFiles();
In the start chain link we will initialize the steppassthroughdata with new arraylist to remove initialisation in miltiple places at different places

2023-08-03 08:40 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/LocalManifestHandler.java
> +    List<ValuesManifestOutcome> aggregatedValuesManifests = getAggregatedValuesManifests(manifestOutcomes);
No, more like i will be trying to group or handle cases around them when we group them, these classes will just get the ManifestOutcomeLIst and then create a response to be carried out. Things will get clarified in Next PR around integration,

2023-08-03 08:43 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/HelmTypeManifestHandler.java
> +      return TaskChainResponse.builder().chainEnd(true).passThroughData(helmValuesFetchPassTroughData).build();
if the Fetch request was unsuccessful we end the chain and return the failure

2023-08-03 08:43 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/GitFetchManifestHandler.java
> +    List<ValuesManifestOutcome> aggregatedValuesManifests = getAggregatedValuesManifests(manifestOutcomes);
TaskChainResponse executeNextChainLink (ResponseData responseData) {
	if(responseData of type Helm){
	// handle fetch response (return taskResponse if fails)
	// update passs through data (if success))
	}
	else if(response data of type Git){
	//handle fetch response (return taskResponse if fails)
	// update passs through data (if success)

	}
	else if (response data of type Custom){
	//handle fetch response (return taskResponse if fails)
	// update passs through data (if success)
	}

	prepare next job manifests () - by traversing the left over manifests
	get TaskChainResponse based on type and then execute
	prepareFetchResponseForStoreType() 
}


TaskChainResponse startChainLink ( {
	create a PassThroughData with initialized manifestFiles as empty list
	run function to get the manifestOutcomes grouped 
	prepareFetchResponseForStoreType() 
}



How to integraate
// eiter seperate start and next chain link functions for them with FF
// or different flow in the same functions w.r.t. FF



quick question:
want to integrate openshift and kustomize in it as well

2023-08-03 09:06 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/LocalManifestHandler.java
> +    List<ManifestFiles> manifestFiles = k8sStepPassThroughData.getManifestFiles();
But isn't this List<ManifestFiles> specific to Harness Store. How is it being used at multiple places?

2023-08-03 09:56 UTC, abosii-harness requested changes

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/GitFetchManifestHandler.java
> +    k8sStepPassThroughData.updateOpenFetchFilesStreamStatus();
The status should be handled in startChainLink, there is no point to always update fetch files stream

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/GitFetchManifestHandler.java
> +    ValuesManifestOutcome valuesManifestOutcome =
This should be done before calling this method

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/GitFetchManifestHandler.java
> +    GitFetchResponsePassThroughData gitFetchResponsePassThroughData =
Instead of using different type of passthrough data you can have common one that will handle errorMsg, unitProgressData and type
Overall this flow is likely to happen as we do have error framework support for most of the task types

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/GitFetchManifestHandler.java
> +      K8sStepExecutor k8sStepExecutor, Ambiance ambiance, StepElementParameters stepElementParameters,
I don't think you need all of these parameters, response data should be enough

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/GitFetchManifestHandler.java
> +  public K8sStepPassThroughData updatePassThroughData(ResponseData responseData, K8sStepExecutor k8sStepExecutor,
you could actually merge together the handleFailedFetchResponseForStoreType and updatePassThroughData
The method interface would be:
public PassthroughData handleResponse(ResponseData response)

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/LocalFetchManifestHandler.java
> +    if (ManifestStoreType.HARNESS.equals(k8sStepPassThroughData.getManifestOutcome().getStore().getKind())
This check shouldn't be required since you should ensure that List<ManifestOutcome> will contain only harness store

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/LocalFetchManifestHandler.java
> +    List<ValuesManifestOutcome> aggregatedValuesManifests = getAggregatedValuesManifests(manifestOutcomes);
This doesn't look to work with Openshift Params and Kustomize Patches

2023-08-03 09:56 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/createFetchTask/ManifestHandler.java
> +  TaskChainResponse prepareFetchResponseForStoreType(Ambiance ambiance, K8sStepExecutor k8sStepExecutor,
This method should be Optional<TaskData> createTaskData(Ambiance ambiance, List<ManifestOutcome> manifests)

2023-09-07 14:36 UTC, closed without merging