fix: [SRM-15219]: removed sensitive keys from request body
harness/harness-core pull request #51180
Opened 2023-07-31 13:27 UTC by karansaraswat19

## Describe your changes
- making new Requests with updated form body so that they can be saved while hiding sensitive keys

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-07-31 13:38 UTC, n00bitax requested changes
let's add a test case with Sensitive keys and non-sensitive keys.
Also write a test case asserting headers are there for one with no sensitive keys.

2023-08-01 13:36 UTC, n00bitax approved these changes

2023-08-01 17:58 UTC, AbhijithHarness commented on 957-cg-beans/src/main/java/io/harness/cvng/beans/cvnglog/ApiCallLogUtils.java
> +  final String CLIENT_SECRET = "client_secret";
nit: you dont need to add this seperatly, since list is also final just add directly there.

2023-08-01 18:02 UTC, AbhijithHarness commented on 957-cg-beans/src/main/java/io/harness/cvng/beans/cvnglog/ApiCallLogUtils.java
> +  final List<String> sensitiveKeys = List.of(CLIENT_SECRET);
nit: Name it sensitive SensitiveFormRequestKeys, as they are used only in case of form requests.

2023-08-02 03:53 UTC, jyotiraval approved these changes

2023-08-02 03:54 UTC, merged

2023-08-02 04:55 UTC, karansaraswat19 commented on 957-cg-beans/src/main/java/io/harness/cvng/beans/cvnglog/ApiCallLogUtils.java
> +  final String CLIENT_SECRET = "client_secret";
will pick this up in next PR

2023-08-02 04:55 UTC, karansaraswat19 commented on 957-cg-beans/src/main/java/io/harness/cvng/beans/cvnglog/ApiCallLogUtils.java
> +  final List<String> sensitiveKeys = List.of(CLIENT_SECRET);
will pick this up in next PR