feat: [CDS-72725]: Implementing CustomObject to get and set field from object
harness/harness-core pull request #51185
Opened 2023-07-31 16:09 UTC by GoelPratyush99

## Describe your changes
Implement Customs Object and CustomObjectFactory to read and update the KubernetesResource Object (like Virtual Services and DestinationRules) to remove dependency from fabric8

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/51185)

2023-07-31 16:31 UTC, GoelPratyush99 commented
trigger uts

2023-07-31 18:48 UTC, GoelPratyush99 commented
trigger ut2

2023-07-31 18:52 UTC, GoelPratyush99 commented
trigger ut0

2023-08-01 04:52 UTC, GoelPratyush99 commented
trigger ut2

2023-08-01 05:21 UTC, TarunUba1 approved these changes

2023-08-01 05:53 UTC, abosii-harness requested changes

2023-08-01 05:53 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/customObjects/ListCustomObject.java
> +  @Inject CustomObjectFactory customObjectFactory;
How exactly this is injected in object?

2023-08-01 05:53 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/customObjects/ListCustomObject.java
> +    List<Object> listNode = getObject();
What about the use case list[n]?

2023-08-01 05:53 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/customObjects/MapCustomObject.java
> +    if (mapNode.containsKey(fieldName)) {
What if field name is key.anotherKey?

2023-08-01 05:53 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/customObjects/MapCustomObject.java
> +      CustomObject customObject = customObjectFactory.create(node).getNode(fieldName);
I'm not getting overall logic, how you're folding the fieldName?

2023-08-01 05:53 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/customObjects/PrimitiveCustomObject.java
> +  public CustomObject getNode(String fieldName) {
Something is missing here, you can't just return null

2023-08-03 05:32 UTC, closed without merging