fix: [CDS-75153]: Add config file location in log line
harness/harness-core pull request #51189
Opened 2023-07-31 17:52 UTC by sarthakkasat

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-01 06:30 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/51189#-NajmVRsB-uq1v6vTbYl:-NajmVRtAFHiv7i4FfNQ:b-tqy4br) ([raw file](https://github.com/harness/harness-core/blob/3fce905f986d726bb818442cc3f5b212c4dbdd32/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L334)):*
> ```Java
>   }
> 
>   private static void createConfigMap(Map<String, String> configFileLocation,
> ```

need not be static



_Code quote:_
```Java
  private static void createConfigMap(Map<String, String> configFileLocation,
```


<!-- Sent from Reviewable.io -->

2023-08-01 11:45 UTC, sarthakkasat commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/51189#-NajmVRsB-uq1v6vTbYl:-NakucMF8TYa4R-_6TSG:bc2ctn3) ([raw file](https://github.com/harness/harness-core/blob/3fce905f986d726bb818442cc3f5b212c4dbdd32/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L334)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

need not be static
</blockquote></details>

Since the method calling this is also static, this method has to be static


<!-- Sent from Reviewable.io -->

2023-08-03 09:54 UTC, yogesh-chauhan requested changes

2023-08-03 09:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
>        verifyConnectorByRef(configFileIdentifier, storeConfig, ambiance);
do we need to add fileLocation here also ?

2023-08-03 09:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +      verifyConfigFileReference(identifier, spec, ambiance, null);
Instead of passing null, lets have a verify method which does not the location

2023-08-03 09:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +  private static void createConfigFileMap(Map<String, String> configFileLocation,
need not be static

2023-08-03 09:54 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java
> +    createConfigFileMap(configFileLocation, svcConfigFiles, finalConfigFilesMap, SERVICE_1);
what is SERVICE_1 here ?

2023-08-07 06:57 UTC, yogesh-chauhan requested changes

2023-08-07 06:57 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
>    protected void verifyConfigFileReference(
should we not call the 
```java
verifyConfigFileReference(final String configFileIdentifier, ConfigFileAttributes configFileAttributes,
      Ambiance ambiance, String fileLocation)
```
method will null value of file location ?

2023-08-07 06:57 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +            "Config file reference cannot be null or empty, ConfigFile identifier: [%s], ConfigFile location: [%s]";
better to construct the final error message here itself. Because both if-else block error messages have different string formatting

2023-08-07 06:57 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +            "Config file not found in Encrypted Store with secretFQN: [%s], ConfigFile identifier: [%s], ConfigFile Location: [%s]";
better to construct the final error message here itself. Because both if-else block error messages have different string formatting

2023-08-07 06:57 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +            errorMessage =
better to construct the final error message here itself. Because both if-else block error messages have different string formatting

2023-08-07 06:57 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
> +            "Connector not found with identifier: [%s], , ConfigFile identifier: [%s], Config file Location: [%s]";
better to construct the final error message here itself. Because both if-else block error messages have different string formatting

2023-08-07 06:57 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java
> +      if (configFileLocation != null) {
maybe just use  a ternary operator here ?

2023-08-07 12:26 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51189)* status: 9 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 132 at r4](https://reviewable.io/reviews/harness/harness-core/51189#gh-1285437946:-NbExWLD0O83Jau3mQdO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8e8db5eacc6e5f7288a1c46a2f65f35f25ba6bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L132)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not call the 
```java
verifyConfigFileReference(final String configFileIdentifier, ConfigFileAttributes configFileAttributes,
      Ambiance ambiance, String fileLocation)
```
method will null value of file location ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 153 at r4](https://reviewable.io/reviews/harness/harness-core/51189#gh-1285438991:-NbExWxs8IpaBAOzG3pA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8e8db5eacc6e5f7288a1c46a2f65f35f25ba6bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L153)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to construct the final error message here itself. Because both if-else block error messages have different string formatting
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 204 at r4](https://reviewable.io/reviews/harness/harness-core/51189#gh-1285439233:-NbExXXx13dLGzRXSxk7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8e8db5eacc6e5f7288a1c46a2f65f35f25ba6bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L204)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to construct the final error message here itself. Because both if-else block error messages have different string formatting
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/51189#gh-1285439299:-NbExXp-0kYfFrpDkZiV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8e8db5eacc6e5f7288a1c46a2f65f35f25ba6bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L219)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to construct the final error message here itself. Because both if-else block error messages have different string formatting
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java` line 237 at r4](https://reviewable.io/reviews/harness/harness-core/51189#gh-1285439391:-NbExYDv3NNku5vZl20t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8e8db5eacc6e5f7288a1c46a2f65f35f25ba6bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java#L237)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to construct the final error message here itself. Because both if-else block error messages have different string formatting
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 197 at r4](https://reviewable.io/reviews/harness/harness-core/51189#gh-1285440520:-NbExZ8n7mwrRpPWx7kM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8e8db5eacc6e5f7288a1c46a2f65f35f25ba6bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L197)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe just use  a ternary operator here ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-07 12:32 UTC, yogesh-chauhan approved these changes

2023-08-07 13:27 UTC, sourabh-awashti commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
>  @OwnedBy(HarnessTeam.CDP)
is this addition expected

2023-08-07 13:36 UTC, sourabh-awashti approved these changes

2023-08-07 13:44 UTC, sarthakkasat commented
trigger review

2023-08-07 14:02 UTC, sarthakkasat commented
trigger uts

2023-08-08 04:43 UTC, sourabh-awashti approved these changes

2023-08-08 04:47 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/AbstractConfigFileStep.java
>  @OwnedBy(HarnessTeam.CDP)
It is part of pr checks

2023-08-08 05:50 UTC, yogesh-chauhan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 7 files at r1, 3 of 7 files at r2, 1 of 4 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51189#-:-NbIgZjI0kS3Ud1IJqot:bnfp4nl)* status: 9 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-08 05:50 UTC, yogesh-chauhan commented
trigger review

2023-08-08 05:57 UTC, merged