fix: [PL-40484]:Secrets Created With CSM with Fixed Inputs Gets Override Via API
harness/harness-core pull request #51191
Opened 2023-07-31 18:11 UTC by adiyaar24

## Describe your changes
Secrets Created with CSM as FixedInputs gets overriden via API. This has been fixed over here

Issue Description
- Whenever a Secret was created using CSM with Fixed or Fixed & RunTime Inputs then if we passed the FIxed Inputs in the API that used to get overriden and it would then be shown as the runtime inputs rather than Fixed Inputs .

Solution
- Add a check to get the input variables from the CSM Template and make a check if all those are passed or not and if anything other than that is passed throw an error.

Testing Done
- Created a Secret with all the required values , Results in creation of secret without any issue
- Created a Secret with some missing fields from required values , Results in error being thrown stating missing fields
- Created a secret with duplicate fields , Results in Error stating duplicate fields are present
- Created a secret with extra fields , that were never present / required , Results in Error stating unnecessary fields added
- Created a secret by making the value an invalid JSON , Results in Error stating Invalid JSON passed 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/51191)

2023-07-31 18:15 UTC, adiyaar24 commented
trigger uts

2023-07-31 18:35 UTC, adiyaar24 commented
trigger mdc

2023-08-04 06:06 UTC, adiyaar24 commented
trigger uts

2023-08-05 22:29 UTC, adiyaar24 commented
trigger uts

2023-08-08 11:25 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +          throw new InvalidRequestException("Duplicate environment variable: " + name);
exception msg should contain all duplicate inputs

2023-08-08 11:26 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +      for (JsonNode variableNode : environmentVariablesNode) {
use single loop for both validations

2023-09-05 11:30 UTC, adiyaar24 commented
trigger uts

2023-09-05 11:37 UTC, adiyaar24 commented
trigger uts

2023-09-05 11:38 UTC, tiwaritejas approved these changes
Nit: Verify the flow when JsonNode.isArray() and JsonNode.isString() operations fail.

2023-09-06 07:04 UTC, adiyaar24 commented
trigger uts

2023-09-06 09:32 UTC, adiyaar24 commented
trigger ut8

2023-09-06 13:40 UTC, adiyaar24 commented
trigger ut8

2023-09-06 15:07 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +  private ConnectorDTO getConnectorDTO(CustomSecretManagerConfigDTO customSecretManagerConfigDTO) {
why we need this separate method ?

2023-09-06 15:08 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +  private void validateEnvironmentVariables(JsonNode environmentVariablesNode,
Add UTs for all new methods

2023-09-07 09:43 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +  private ConnectorDTO getConnectorDTO(CustomSecretManagerConfigDTO customSecretManagerConfigDTO) {
Just to improve the readability of the code it was split into multiple methods .

2023-09-08 07:46 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +  private void validateEnvironmentVariables(JsonNode environmentVariablesNode,
Added Test to validate

2023-09-08 07:57 UTC, adiyaar24 commented
trigger uts

2023-09-08 09:05 UTC, adiyaar24 commented
trigger uts

2023-09-11 10:38 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +  private ConnectorDTO getConnectorDTO(CustomSecretManagerConfigDTO customSecretManagerConfigDTO) {
Updated

2023-09-11 10:39 UTC, adiyaar24 commented
trigger uts

2023-09-13 06:09 UTC, meenakshi-harness requested changes

2023-09-13 06:09 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    if (jsonValue == null) {
we can move this check to line 220

2023-09-13 06:09 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        if (!nameNode.isTextual()) {
lets discuss this over call

2023-09-13 11:26 UTC, meenakshi-harness submitted a review, later dismissed

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    CustomSecretManagerConfigDTO customSecretManagerConfigDTO = (CustomSecretManagerConfigDTO) secretManager;
Try using CustomSecretManagerConfigDTO  to get template inputs instead of converting to CustomSecretManagerConnectorDTO

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        (connectorTemplateInputs != null) ? connectorTemplateInputs.get(ENVIRONMENT_VARIABLES) : null;
Add return instead of setting envVariables null.

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    if (jsonValue == null && envVariables != null) {
This `envVariables != null`  will not be needed post above comment

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +      throw new InvalidRequestException("Environment Variables are missing");
Environment Variables are missing in secret input.

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +      return;
Remove this block.. will not be needed

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    JsonNode environmentVariablesNode = rootNode.path("environmentVariables");
use constant for `environmentVariables`

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        if (inputs.contains(node.getName())) {
Implementation seems wrong. lets re-check this piece and add UTs

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        throw new InvalidRequestException("Invalid Environment Variables in the JSON body.");
Missing Environment Variables in Secret input. print the missing ones

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +          duplicateInputs.add(name);
Not needed as we are already checking above for duplicate input

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +      throw new InvalidRequestException(
same

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +          missingEnvVariables.add(name);
This piece is also redundant. We have already checked for missing variables above

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    if (!missingEnvVariables.isEmpty()) {
same

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +    assertThatThrownBy(() -> ngEncryptedDataService.createSecretText(accountIdentifier, secret))
assert error message as well.

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +        .isInstanceOf(InvalidRequestException.class);
You can use ExceptionRule to assert on exception.

2023-09-13 11:26 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +        .isInstanceOf(InvalidRequestException.class);
Same assert on exact error message

2023-09-14 16:37 UTC, adiyaar24 commented
trigger uts

2023-09-15 07:55 UTC, adiyaar24 commented
trigger ut9

2023-09-15 14:11 UTC, meenakshi-harness requested changes

2023-09-15 14:11 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        } catch (IOException e) {
Exception?

2023-09-15 14:11 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    if (envVariables.isEmpty()) {
should we check envVariables as null also?

2023-09-15 14:11 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    if (jsonValue == null) {
We need this check on line 217

2023-09-15 14:11 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    validateMissing(envVariables, givenInputs);
why validatingMissing 2 times?

2023-09-15 14:11 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +        .hasMessageContaining("RunTime Inputs are not provided for the Secret, Missing environment variables are: ");
Are we not throwing message with vars missing?

2023-09-15 14:11 UTC, meenakshi-harness commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +        .hasMessageContaining("RunTime Inputs are not provided for the Secret, Missing environment variables are: ");
We get same message in both test cases?

2023-09-17 13:05 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        } catch (IOException e) {
Lets discuss this over call

2023-09-17 13:06 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    if (envVariables.isEmpty()) {
No , we have made it an empty arraylist at the initialisation point

2023-09-17 13:06 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    validateMissing(envVariables, givenInputs);
Just to return the error message with the missing environment variables name

2023-09-17 13:07 UTC, adiyaar24 commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +        .hasMessageContaining("RunTime Inputs are not provided for the Secret, Missing environment variables are: ");
Yeah we are throwing that

2023-09-17 13:08 UTC, adiyaar24 commented on 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImplTest.java
> +        .hasMessageContaining("RunTime Inputs are not provided for the Secret, Missing environment variables are: ");
Ya , because if its missing from the input set , be it wrong or missing

2023-09-20 06:37 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +    validateMissing(envVariables, givenInputs);
Updated , and fixed it

2023-09-20 12:23 UTC, meenakshi-harness approved these changes

2023-09-20 14:00 UTC, adiyaar24 commented
trigger uts

2023-09-20 14:03 UTC, meenakshi-harness approved these changes

2023-09-20 14:20 UTC, merged