fix: [CDS-75900]: Validating directory size of the folder that will be send to the manager.
harness/harness-core pull request #51231
Opened 2023-08-01 14:28 UTC by GoelPratyush99

## Describe your changes
Validating directory size of the folder that will be send to the manager < 25Mb, Earlier we were checking the directory size of the cloned repo < 25Mb which was incorrect. The changes have been done for Custom Remote Manifest in both CG and NG.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-01 14:29 UTC, GoelPratyush99 commented
trigger uts

2023-08-01 15:00 UTC, namantalaycha10 requested changes

2023-08-01 15:03 UTC, namantalaycha10 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTask.java
> -              .commandExecutionStatus(FAILURE)
also can we use this string as a constant "Custom Manifest File size exceeds allowed max size of 25Mb" ? this will help us to remove code duplication as well

2023-08-02 04:30 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTask.java
> -              .commandExecutionStatus(FAILURE)
This is removed piece of code

2023-08-02 04:31 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTask.java
> +      throw new InvalidRequestException("Custom Manifest File size exceeds allowed max size of 25Mb");
Done

2023-08-02 04:31 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java
> -              new InvalidRequestException("Custom Manifest File size exceeds allowed max size of 25Mb"));
This is removed piece of code

2023-08-02 04:31 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java
> +      throw new InvalidRequestException("Custom Manifest File size exceeds allowed max size of 25Mb");
Done

2023-08-02 04:31 UTC, GoelPratyush99 commented
trigger uts

2023-08-02 04:35 UTC, namantalaycha10 approved these changes

2023-08-02 07:28 UTC, TarunUba1 submitted a review, later dismissed

2023-08-02 09:06 UTC, GoelPratyush99 commented
trigger review

2023-08-02 09:37 UTC, abosii-harness requested changes

2023-08-02 09:37 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTask.java
> +    if (!isManifestsFilesSizeAllowed(logCallback, destZippedManifestDirectory)) {
Should we do this before running zip?

2023-08-02 10:10 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTask.java
> +    if (!isManifestsFilesSizeAllowed(logCallback, destZippedManifestDirectory)) {
I was checking this destination directory as we the is the one that we send to manager. Made changes to check the size of manifest file only.

2023-08-02 10:13 UTC, GoelPratyush99 commented
trigger uts

2023-08-02 11:09 UTC, GoelPratyush99 commented
trigger uts

2023-08-02 13:41 UTC, namantalaycha10 approved these changes

2023-08-02 13:57 UTC, TarunUba1 approved these changes

2023-08-02 14:03 UTC, GoelPratyush99 commented
trigger review

2023-08-02 16:09 UTC, abosii-harness approved these changes

2023-08-02 16:11 UTC, merged