fix: [CDS-75280]: Show detailed error message from errorBody for docker API
harness/harness-core pull request #51307
Opened 2023-08-03 06:09 UTC by sarthakkasat

…r API

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-07 07:13 UTC, sourabh-awashti reviewed
pls add Junit

2023-08-07 07:39 UTC, yogesh-chauhan requested changes

2023-08-07 12:28 UTC, sarthakkasat reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51307#-:-NbExqq5BUL-H4_3cbnd:bb6un1j)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/51307#gh-1282985819:-NbExtIkBKluxBFCz7gi:b-896fix) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Maybe we should catch all exceptions here and return response.getMessaage() as the fallback ?
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/harness/harness-core/51307#gh-1282986221:-NbExtdmDeErVrRAut37:b-896fix) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Lets also do the same for all other APIs
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-08-07 12:42 UTC, yogesh-chauhan commented on 960-api-services/src/main/java/io/harness/artifacts/docker/service/DockerPublicRegistryProcessor.java
> +            new InvalidArtifactServerException(RetrofitUtils.getErrorBodyDetails(pageResponse, "message"), USER));
can we extract out "message" as a constant ?

2023-08-07 13:39 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51307)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/artifacts/docker/service/DockerPublicRegistryProcessor.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/51307#gh-1285802814:-NbFDEXM2rCrUGxG-lwr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ca1bc3d5155c6a9ab83e65b21a1ec893cafc7562/960-api-services/src/main/java/io/harness/artifacts/docker/service/DockerPublicRegistryProcessor.java#L159)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we extract out "message" as a constant ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-07 13:39 UTC, sourabh-awashti approved these changes

2023-08-07 13:40 UTC, sarthakkasat commented
trigger uts

2023-08-07 13:44 UTC, sarthakkasat commented
trigger uts

2023-08-07 14:04 UTC, sarthakkasat commented
trigger uts

2023-08-07 15:25 UTC, yogesh-chauhan commented
*[`960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java` line 48 at r5](https://reviewable.io/reviews/harness/harness-core/51307#-NbFaVD94XdwJBvTgx4l:-NbFaVD94XdwJBvTgx4m:bvxbwoc) ([raw file](https://github.com/harness/harness-core/blob/7c319986f5daa0f9bb73c9488ddae2b77a7bf98c/960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java#L48)):*
> ```Java
>             "{\"message\":\"httperror 404: tag 'evrb' not found\",\"errinfo\":{\"namespace\":\"library\",\"repository\":\"nginx\",\"tag\":\"evrb\"}}\n");
>     String errorMessage = RetrofitUtils.getErrorBodyDetails(response, "message");
>     assertThat(errorMessage).isEqualTo("httperror 404: tag 'evrb' not found");
> ```

we should add more tests like when field is not present in the json etc


<!-- Sent from Reviewable.io -->

2023-08-07 16:27 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51307)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java` line 48 at r5](https://reviewable.io/reviews/harness/harness-core/51307#-NbFaVD94XdwJBvTgx4l:-NbFnf7pALMYzJACheSo:btnjza5) ([raw file](https://github.com/harness/harness-core/blob/7c319986f5daa0f9bb73c9488ddae2b77a7bf98c/960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java#L48)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should add more tests like when field is not present in the json etc
</blockquote></details>

Added UTs for empty error body and error body with missing key


<!-- Sent from Reviewable.io -->

2023-08-08 04:44 UTC, sourabh-awashti submitted a review, later dismissed

2023-08-08 05:55 UTC, yogesh-chauhan commented on 960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java
> +    MockitoAnnotations.initMocks(this);
initmocks is not needed here since there are no @Mocks/@InjectMocks annotations in this class

2023-08-08 05:55 UTC, yogesh-chauhan commented on 960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java
> +@OwnedBy(HarnessTeam.CDP)
@OwnedBy(CDC)

2023-08-08 06:00 UTC, sarthakkasat commented
trigger uts

2023-08-08 09:37 UTC, sourabh-awashti approved these changes

2023-08-08 10:03 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51307)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java` line 32 at r6](https://reviewable.io/reviews/harness/harness-core/51307#gh-1286627162:-NbJ_aOjCsC9fpJShFvm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3d78797994efa5d9a25546b9b13bf2c92a7827c/960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java#L32)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

@OwnedBy(CDC)
</blockquote></details>

Done.
___
*[`960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java` line 36 at r6](https://reviewable.io/reviews/harness/harness-core/51307#gh-1286627036:-NbJ_adk4w_vt9UpN2D7:bxhxts7) ([raw file](https://github.com/harness/harness-core/blob/f3d78797994efa5d9a25546b9b13bf2c92a7827c/960-api-services/src/test/java/io/harness/artifacts/utils/RetrofitUtilsTest.java#L36)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

initmocks is not needed here since there are no @Mocks/@InjectMocks annotations in this class 
</blockquote></details>

Will remove in next PR


<!-- Sent from Reviewable.io -->

2023-08-08 10:03 UTC, yogesh-chauhan approved these changes

2023-08-08 10:04 UTC, yogesh-chauhan approved these changes

2023-08-08 10:04 UTC, sarthakkasat commented
trigger review

2023-08-08 10:06 UTC, merged