fix: [CDS-75443]: improve the error message for elastic group setup
harness/harness-core pull request #51333
Opened 2023-08-03 12:26 UTC by vlica-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-03 12:29 UTC, vlica-harness commented
trigger uts_JDK11

2023-08-04 06:25 UTC, vlica-harness commented
trigger messagecheck

2023-08-04 10:49 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java
> +          ERROR, CommandExecutionStatus.FAILURE);
can we check if this problem exists with other ECS steps as well ?

2023-08-04 10:50 UTC, yogesh-chauhan requested changes

2023-08-04 10:50 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java
> +      logCallback.saveExecutionLog(color(format("Failed to parse the ElasticGroup Json file, cause: %s",
is should be Elasti ( without the C )

2023-08-04 11:21 UTC, vlica-harness commented
trigger uts_JDK11

2023-08-04 13:56 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java
> +      logCallback.saveExecutionLog(color(format("Failed to parse the ElasticGroup Json file, cause: %s",
good catch, thanks

2023-08-04 14:42 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupSetupStep.java
> +          ERROR, CommandExecutionStatus.FAILURE);
I checked for EcsRollingDeploy, EcsCanaryDeploy when json manifest is malrformed, and the error is pretty meaningful. For example:
![ecs rolling deser](https://github.com/harness/harness-core/assets/102597442/cd53d109-7fb3-4376-a1d9-dc1e212f0191)

2023-08-04 16:58 UTC, arvind-choudhary-h approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51333)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-07 05:03 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51333)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-08-07 05:05 UTC, yogesh-chauhan commented
trigger ut4

2023-08-07 05:15 UTC, yogesh-chauhan commented
trigger review

2023-08-07 05:42 UTC, merged