CI-8602: Added error log for KubernetisHosted Infra
harness/harness-core pull request #51331
Opened 2023-08-03 11:44 UTC by sahithibanda01

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-03 11:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=51331) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=51331) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=51331) it.</sub>

2023-08-03 20:47 UTC, hemanthmantri reviewed
Didn't we deprecate k8s hosted infra? Also, I think you have changes in ci-manager config.yml which are supposed to be local.

2023-08-04 05:51 UTC, sahithibanda01 commented
> Didn't we deprecate k8s hosted infra? Also, I think you have changes in ci-manager config.yml which are supposed to be local.

We are removing the code path for K8Hosted Infra and also will remove my local changes in this PR

2023-08-07 06:09 UTC, raghavharness commented on 120-ng-manager/config.yml
> +useQueueServiceForWebhookTriggers: ${USE_QUEUE_SERVICE_FOR_WEBHOOK_TRIGGERS:-false}
you can undo this change

2023-08-07 07:38 UTC, sahithibanda01 commented
trigger uts

2023-08-07 09:13 UTC, sahithibanda01 commented
trigger ut0
trigger ut1
trigger ut5

2023-08-07 10:02 UTC, sahithibanda01 commented
trigger ut0,ut1,ut5

2023-08-07 10:58 UTC, raghavharness requested changes

2023-08-07 10:58 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/CIExecutionConfigService.java
> -  public List<DeprecatedImageInfo> getDeprecatedTags(String accountId) {
Revert this

2023-08-07 10:58 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +    if (stage != null && stage.getInfrastructure() != null) {
Remove the if condition

2023-08-07 10:58 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +    if (stage != null && stage.getInfrastructure() != null) {
ditto

2023-08-07 13:47 UTC, raghavharness approved these changes

2023-08-07 13:48 UTC, raghavharness commented
trigger uts

2023-08-07 13:53 UTC, sahithibanda01 commented
trigger uts

2023-08-07 18:27 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/BuildSetupUtils.java
> -        return k8InitializeTaskParamsBuilder.getK8InitializeTaskParams(initializeStepInfo, ambiance, logPrefix);
You should not be removing the return statement from here

2023-08-07 18:29 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/BuildSetupUtils.java
> -        return k8InitializeTaskParamsBuilder.getK8InitializeTaskParams(initializeStepInfo, ambiance, logPrefix);
Let's also run a k8 pipeline on local to verify the flow once.

2023-08-08 07:02 UTC, sahithibanda01 commented
trigger uts

2023-08-08 07:13 UTC, raghavharness approved these changes

2023-08-08 15:27 UTC, harshjain12 commented
@raghavharness Shall we test hosted vm once before merging it ?

2023-08-09 06:55 UTC, raghavharness commented
> @raghavharness Shall we test hosted vm once before merging it ?

@harshjain12 Has now tested for both k8 and VM. Can you review once.

2023-08-09 07:56 UTC, merged