fix: [CDS-76240]: adding release before wait for steady state to handle cases
harness/harness-core pull request #51367
Opened 2023-08-04 10:51 UTC by TarunUba1

## Describe your changes
adding release before wait for steady state to handle cases
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-04 11:31 UTC, TarunUba1 commented
trigger uts

2023-08-04 13:52 UTC, abhinavsingh1196 requested changes

2023-08-04 13:52 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandler.java
> +    k8sTaskHelperBase.saveRelease(k8sCanaryDeployTaskParameters.isUseDeclarativeRollback(), false,
What if there is an exception in this method while saving release? we should try to save release as failed then, since its better to save a release as failed than no release entry at all.
the catch block was taking care of this earlier

2023-08-04 14:07 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandler.java
> +    k8sTaskHelperBase.saveRelease(k8sCanaryDeployTaskParameters.isUseDeclarativeRollback(), false,
i see that we are saving like in this manner for RollingRequestHandler and BGRequestHandlers so kinda did that,
why does it matter to save as Fail, as later we take into consideration both Inprogress and Failed release when considereing resources to delete from release. in k8sDeleteTaskHandler.
When something fails in that try block it will be caught and the status of the Release will be changed from Inprogress to Failed so thats fine.
I kinda dont want to populate as failed personally but i see your point of what we were handling

2023-08-04 14:43 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandler.java
> +    k8sTaskHelperBase.saveRelease(k8sCanaryDeployTaskParameters.isUseDeclarativeRollback(), false,
@GoelPratyush99 ye kya rocket hai

2023-08-04 14:52 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandler.java
> +    k8sTaskHelperBase.saveRelease(k8sCanaryDeployTaskParameters.isUseDeclarativeRollback(), false,
@TarunUba1 It didn't show "+" sign so I added rocket :)

2023-08-04 15:19 UTC, abosii-harness requested changes

2023-08-04 15:19 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandler.java
> +    k8sCanaryBaseHandler.failAndSaveRelease(canaryHandlerConfig);
why we're failing?

2023-08-04 15:19 UTC, TarunUba1 commented
trigger uts

2023-08-04 15:27 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sCanaryDeployTaskHandler.java
> +    k8sCanaryBaseHandler.failAndSaveRelease(canaryHandlerConfig);
Not failing now

2023-08-04 15:38 UTC, TarunUba1 commented
trigger uts

2023-08-04 15:41 UTC, TarunUba1 commented
trigger uts

2023-08-04 15:52 UTC, abhinavsingh1196 approved these changes

2023-08-07 05:53 UTC, GoelPratyush99 approved these changes

2023-08-07 06:13 UTC, abosii-harness approved these changes

2023-08-07 06:14 UTC, TarunUba1 commented
trigger review

2023-08-07 06:19 UTC, merged