feat: [CDS-74848]: Added the DTOs and entity class for Global template
harness/harness-core pull request #51363
Opened 2023-08-04 08:08 UTC by shivamnegi94

I have split the PR into small PRs.
Adding the dtos, entity class and mapper in this PR.

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/51363)

2023-08-04 08:09 UTC, shivamnegi94 commented
trigger uts

2023-08-04 09:42 UTC, utkarshchoubey-harness requested changes

2023-08-04 09:42 UTC, utkarshchoubey-harness commented on 878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java
> +    validateReamMeFilePathHasCorrectExtension(filePath);
typo -
validateReadMeFileHasCorrectExtension

2023-08-04 09:42 UTC, utkarshchoubey-harness commented on template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java
> +  public CacheResponseMetadataDTO getCacheResponse(GlobalTemplateEntity templateEntity) {
Are you adding Caching support as well here ?

2023-08-04 09:42 UTC, utkarshchoubey-harness commented on template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java
> +  public void validateYamlSchemaInternal(GlobalTemplateEntity globalTemplateEntity) {
this is the exact same function , we can reuse the old function? 
Or create a overloaded 
or maybe put the common logic in diff function and use it across

2023-08-04 09:42 UTC, utkarshchoubey-harness commented on template-service/service/src/main/java/io/harness/template/events/GlobalTemplateUpdateEvent.java
> +public class GlobalTemplateUpdateEvent implements Event {
can we utilise the same Events we have for templates ?
As nearly the code is entirely duplicated 
Also does it makes sense to use same events ?
cc - @archit-harness @sribalij

2023-08-04 10:51 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/events/GlobalTemplateUpdateEvent.java
> +public class GlobalTemplateUpdateEvent implements Event {
We should not use same event.

2023-08-04 10:52 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java
> +  public CacheResponseMetadataDTO getCacheResponse(GlobalTemplateEntity templateEntity) {
I am creating same support as of template have right now.

2023-08-04 10:54 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java
> +  public void validateYamlSchemaInternal(GlobalTemplateEntity globalTemplateEntity) {
Entity type is different so i have overriden the method

2023-08-07 03:18 UTC, shivamnegi94 commented
trigger uts

2023-08-09 05:24 UTC, utkarshchoubey-harness approved these changes

2023-08-09 05:30 UTC, shivamnegi94 commented
trigger uts

2023-08-09 05:42 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51363)* status: 10 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/events/GlobalTemplateUpdateEvent.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/51363#gh-1284214238:-NbNo6438bhckl0MJi9B:b-lushab) ([raw file](https://github.com/harness/harness-core/blob/eda180668ca5c788dfeeb442c852249c1adc503e/template-service/service/src/main/java/io/harness/template/events/GlobalTemplateUpdateEvent.java#L33)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

We should not use same event.
</blockquote></details>

yeah having separate event is better if record is different, if fields are same, one thing you can do is put inside abstract class, that will remove duplicate code


<!-- Sent from Reviewable.io -->

2023-08-09 05:43 UTC, archit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51363)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/entity/GlobalTemplateEntity.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/51363#-NbNoSqs-9rq2U6Ex59F:-NbNoSqs-9rq2U6Ex59G:bb4pi2) ([raw file](https://github.com/harness/harness-core/blob/bf5d9a89054770c3d7d70236898c483a5b0e3da6/template-service/service/src/main/java/io/harness/template/entity/GlobalTemplateEntity.java#L127)):*
> ```Java
> 
>   public static List<MongoIndex> mongoIndexes() {
>     return ImmutableList.<MongoIndex>builder()
> ```

why so many indexes are required?


<!-- Sent from Reviewable.io -->

2023-08-09 11:04 UTC, archit-harness requested changes
> Reviewed 3 of 8 files at r1, 3 of 4 files at r3, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51363)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/entity/GlobalTemplateEntity.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/51363#-NbNoSqs-9rq2U6Ex59F:-NbOxRy16W7Dup4IsbPc:bysfpnd) ([raw file](https://github.com/harness/harness-core/blob/bf5d9a89054770c3d7d70236898c483a5b0e3da6/template-service/service/src/main/java/io/harness/template/entity/GlobalTemplateEntity.java#L127)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why so many indexes are required?
</blockquote></details>

how both index can be unique?
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 306 at r1](https://reviewable.io/reviews/harness/harness-core/51363#gh-1284211814:-NbOxXOH70y-m2uN1TPj:b-cphpbj) ([raw file](https://github.com/harness/harness-core/blob/eda180668ca5c788dfeeb442c852249c1adc503e/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L306)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

Entity type is different so i have overriden the method
</blockquote></details>

@utkarshchoubey-harness can you validate existing schema is not impacted?


<!-- Sent from Reviewable.io -->

2023-08-09 11:22 UTC, archit-harness approved these changes
> Reviewed 1 of 4 files at r3, 1 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51363)* status: 10 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-09 11:24 UTC, utkarshchoubey-harness approved these changes

2023-08-09 11:26 UTC, shivamnegi94 commented
trigger uts

2023-08-09 11:26 UTC, shivamnegi94 commented
trigger review

2023-08-09 12:20 UTC, merged