feat: [CDS-70107]: Add when condition in Yaml V1
harness/harness-core pull request #51440
Opened 2023-08-08 03:38 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-09 06:15 UTC, brijeshdhakar requested changes
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNtSuu8Qq4DYWdqZ2V:-NbNtSuu8Qq4DYWdqZ2W:baokymr) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L60)):*
> ```Java
>   String uuid;
> 
>   @NotNull @EntityIdentifier @Pattern(regexp = NGRegexValidatorConstants.IDENTIFIER_PATTERN) String identifier;
> ```

I think identifier is not mandatory field in YAML. Also it will be now id. 
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNuArZ2bvujU29skBc:-NbNuArZ2bvujU29skBd:bz8dxri) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L70)):*
> ```Java
>   @Getter(onMethod_ = { @ApiModelProperty(hidden = true) })
>   @ApiModelProperty(hidden = true)
>   ParameterField<String> skipCondition;
> ```

We don't use the skipCondition so we can remove it.
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNuPgq3dfGOcaxFUdG:-NbNuPgq3dfGOcaxFUdH:b-gw9i9e) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L80)):*
> ```Java
>   @VariableExpression(skipVariableExpression = true)
>   @JsonProperty("strategy")
>   ParameterField<StrategyConfig> strategy;
> ```

Use StrategyConfigV1 instead of StrategyConfig
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNv9KuAD46sRrbdC9Z:-NbNv9KuAD46sRrbdC9_:b-j6ifhg) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java#L38)):*
> ```Java
>   @Pattern(regexp = NGRegexValidatorConstants.TIMEOUT_PATTERN_WITHOUT_EXECUTION_INPUT)
>   @VariableExpression(skipInnerObjectTraversal = true)
>   ParameterField<Timeout> timeout;
> ```

nit: Should we move timeout to AbstractStepNodeV1? I think timeout will be available for all steps? @archit-harness any thought?


<!-- Sent from Reviewable.io -->

2023-08-09 06:20 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNv9KuAD46sRrbdC9Z:-NbNwpzs-fhhRfBuvWzb:b-bp89f5) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java#L38)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

nit: Should we move timeout to AbstractStepNodeV1? I think timeout will be available for all steps? @archit-harness any thought?
</blockquote></details>

timeout is not present in wait step, that's why we moved it from AbstractStepNode earlier.


<!-- Sent from Reviewable.io -->

2023-08-09 07:58 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNtSuu8Qq4DYWdqZ2V:-NbO5cF42C4_tIWHC8q1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L60)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think identifier is not mandatory field in YAML. Also it will be now id. 
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNuArZ2bvujU29skBc:-NbO5bclBI1bN6h-t63Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L70)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We don't use the skipCondition so we can remove it.
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNuPgq3dfGOcaxFUdG:-NbO5bQfELwntue4Lvh_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L80)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Use StrategyConfigV1 instead of StrategyConfig
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-09 08:48 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 6 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTbL_Af8MXau4rrYB:-NbOTbL_Af8MXau4rrYC:b-vt2pm6) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L72)):*
> ```Java
>   @ApiModelProperty(dataType = SwaggerConstants.STRATEGY_CLASSPATH)
>   @YamlSchemaTypes(value = {onlyRuntimeInputAllowed})
>   @VariableExpression(skipVariableExpression = true)
> ```

remove annotations as no schema nor variable creator
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTZucBxr3QTcSE_jW:-NbOTZucBxr3QTcSE_jX:b-p490xa) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L79)):*
> ```Java
>   @JsonIgnore public abstract String getType();
> 
>   @JsonIgnore public abstract StepSpecType getStepSpecType();
> ```

dont keep until required
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/51440#-NbNv9KuAD46sRrbdC9Z:-NbOTmHRDdO_YnVwyeC8:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c8c9d8641f6fda90e41b3c9973c256565d9fdca2/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java#L38)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

timeout is not present in wait step, that's why we moved it from AbstractStepNode earlier.
</blockquote></details>

+1
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java` line 147 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTrZ84mF6HvTHw1cd:-NbOTrZ84mF6HvTHw1ce:b-gffgxp) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java#L147)):*
> ```Java
>       return false;
>     }
>     return (boolean) kryoSerializer.asObject(dependency.getMetadataMap().get("isStepInsideRollback").toByteArray());
> ```

TODO yet to be implement comment and return false noe


<!-- Sent from Reviewable.io -->

2023-08-09 08:55 UTC, hextechpal requested changes
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 6 file(s) to review. 3 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 147 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTMK94WxtvhTDNGEp:-NbOTMK94WxtvhTDNGEq:bwztodx) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L147)):*
> ```Java
>   }
> 
>   private String getStageWhenCondition(ParameterField<String> stageWhenCondition) {
> ```

can we create new utils and use those
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/StepParametersUtils.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTQT47-FMIOiv39e_:-NbOTQT47-FMIOiv39ea:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/StepParametersUtils.java#L77)):*
> ```Java
>   }
> 
>   public StepElementParametersBuilder getStepParametersV1(PmsAbstractStepNodeV1 stepElementConfig) {
> ```

ditto
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTdR3C_LKVWO5v-PP:-NbOTdR3C_LKVWO5v-PQ:bqt6de9) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L8)):*
> ```Java
>  */
> 
> package io.harness.plancreator.steps.http;
> ```

put it inside v1 package, Do this need to exist in contracts folder any more as we have static schema and contract is defined there. I personally would like to have all beans related to HTTP in a single package @archit-harness ?
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUDA72tmcjQTFolQ0:-NbOUDA72tmcjQTFolQ1:b-dcl3v3) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L48)):*
> ```Java
> @NoArgsConstructor
> @EqualsAndHashCode(callSuper = true)
> @JsonTypeName(StepSpecTypeConstants.HTTP)
> ```

Does same json type name cause issues? Do we use this anywhere if not can we remove this?
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUNds1xo6uxLVZ3o7:-NbOUNds1xo6uxLVZ3o8:bucwb8k) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java#L8)):*
> ```Java
>  */
> 
> package io.harness.plancreator.steps.internal;
> ```

add a v1 package
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUfTKEDcxQSzDXcUl:-NbOUfTKEDcxQSzDXcUm:b-k8xo67) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java#L142)):*
> ```Java
>   }
> 
>   private boolean isStepInsideRollback(Dependency dependency) {
> ```

can we put this into a utility
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java` line 147 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOVHwP1rdc80qVFIqR:-NbOVHwP1rdc80qVFIqS:bn33vu9) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java#L147)):*
> ```Java
>       return false;
>     }
>     return (boolean) kryoSerializer.asObject(dependency.getMetadataMap().get("isStepInsideRollback").toByteArray());
> ```

We can use this https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L51 for metadata map to avoid this deserialization and serialization via kryo (lets add a todo)


<!-- Sent from Reviewable.io -->

2023-08-14 11:02 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 14 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java` line 147 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOVHwP1rdc80qVFIqR:-NbnhaLx8F9PSPV0uyye:b4c9lyr) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java#L147)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

We can use this https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L51 for metadata map to avoid this deserialization and serialization via kryo (lets add a todo)
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2023-08-14 11:06 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 14 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTdR3C_LKVWO5v-PP:-Nbni0HIEnBUzWi9wPKX:b-90yzee) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L8)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

put it inside v1 package, Do this need to exist in contracts folder any more as we have static schema and contract is defined there. I personally would like to have all beans related to HTTP in a single package @archit-harness ?
</blockquote></details>

Yes contracts for v1 pojos not required as of now, we will move other dtos once dynamic schema is complete removed
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUDA72tmcjQTFolQ0:-NbniBPs2chVRxc1q43X:bnwl2gv) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L48)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Does same json type name cause issues? Do we use this anywhere if not can we remove this?
</blockquote></details>

@shalini-agr can you try deserialising intp HttpStepNodeV1 directly the yaml in plan creators, if not needed we can remove it

Remove typeAlias, recaster alias is not required right? its not part of stepParameters so remove it
Data and noArgs constructor is required?


<!-- Sent from Reviewable.io -->

2023-08-14 11:51 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 14 file(s) to review. 3 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 147 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTMK94WxtvhTDNGEp:-NbTvA0J4s9yTHvrSgin:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L147)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

can we create new utils and use those
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUfTKEDcxQSzDXcUl:-NbTxOQB-AUW4M5831_6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java#L142)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

can we put this into a utility
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java` line 147 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTrZ84mF6HvTHw1cd:-NbTtzV5D314LbRQ3abL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java#L147)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

TODO yet to be implement comment and return false noe
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTbL_Af8MXau4rrYB:-NbOYKpo5MWvAgwkM_Bl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove annotations as no schema nor variable creator
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTZucBxr3QTcSE_jW:-NbOZ_ZZ8Egi0c3mZ1PK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNodeV1.java#L79)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont keep until required
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/StepParametersUtils.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTQT47-FMIOiv39e_:-NbTwPyi4uyBCRb0SFbO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/StepParametersUtils.java#L77)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOTdR3C_LKVWO5v-PP:-NbniuiFBPQr8IPWoP0B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L8)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Yes contracts for v1 pojos not required as of now, we will move other dtos once dynamic schema is complete removed
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUDA72tmcjQTFolQ0:-Nbnqc_DCdZvm_aLwDFm:b-spf2g2) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shalini-agr can you try deserialising intp HttpStepNodeV1 directly the yaml in plan creators, if not needed we can remove it

Remove typeAlias, recaster alias is not required right? its not part of stepParameters so remove it
Data and noArgs constructor is required?
</blockquote></details>

JsonTypeName is required for polymorphic deserialization and Data is also required because  Jackson uses the setter methods to set the values of the object's fields during deserialization.
We can remove the rest of them.
The same JsonTypeName is not causing any issues here because the abstract (parent) class is different for both of them.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUNds1xo6uxLVZ3o7:-NbOYTlR8KwptU0zfV1F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNodeV1.java#L8)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

add a v1 package
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-14 11:55 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 14 file(s) to review. 3 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUDA72tmcjQTFolQ0:-Nbntboe8rDZmqd-pgvr:bxlviyc) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L48)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

JsonTypeName is required for polymorphic deserialization and Data is also required because  Jackson uses the setter methods to set the values of the object's fields during deserialization.
We can remove the rest of them.
The same JsonTypeName is not causing any issues here because the abstract (parent) class is different for both of them.
</blockquote></details>

@shalini-agr can you send @value and not @data


<!-- Sent from Reviewable.io -->

2023-08-14 12:10 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOUDA72tmcjQTFolQ0:-NbnwjHkEZkj-1aEW4dR:b681er3) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/HttpStepNodeV1.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shalini-agr can you send @value and not @data
</blockquote></details>

@value is not working, because it needs setter 


<!-- Sent from Reviewable.io -->

2023-08-16 06:29 UTC, archit-harness requested changes
> Reviewed 6 of 14 files at r4, 2 of 4 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 14 file(s) to review. 3 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java` line 34 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx-O_vDne8fy2UpD5e:-Nbx-O_vDne8fy2UpD5f:b-vqzt72) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java#L34)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_PIPELINE})
> @Data
> @JsonIgnoreProperties(ignoreUnknown = true)
> ```

I dont think this is required, but test it



_Code quote:_
```Java
@JsonIgnoreProperties(ignoreUnknown = true)
```
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 26 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx0AlVB8FsGEsioa5C:-Nbx0AlVB8FsGEsioa5D:bygrnfr) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L26)):*
> ```Java
>     StepElementParametersV1Builder stepBuilder = StepElementParametersV1.builder();
>     stepBuilder.name(stepElementConfig.getName());
>     stepBuilder.identifier(stepElementConfig.getId());
> ```

this will be id



_Code quote:_
```Java
identifier
```
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 28 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx0D4W3m6DBCBbCvBO:-Nbx0D4W3m6DBCBbCvBP:bb7evbq) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L28)):*
> ```Java
>     stepBuilder.identifier(stepElementConfig.getId());
>     stepBuilder.delegateSelectors(stepElementConfig.getDelegateSelectors());
>     stepBuilder.description(stepElementConfig.getDescription());
> ```

desc



_Code quote:_
```Java
description
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java` line 46 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx0niIDsHazQT7RtrC:-Nbx0niIDsHazQT7RtrD:b-x5z7sn) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java#L46)):*
> ```Java
>   StepType type = StepType.Http;
> 
>   @JsonProperty("spec")
> ```

move field to spec keyword and remove JsonProperty


<!-- Sent from Reviewable.io -->

2023-08-16 07:14 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 14 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java` line 34 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx-O_vDne8fy2UpD5e:-NbxBMKTBU51GqW1-F5z:bszk4d6) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I dont think this is required, but test it
</blockquote></details>

Done.
Tested.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 26 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx0AlVB8FsGEsioa5C:-NbxBLWVACC0npDDhgHz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this will be id
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 28 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx0D4W3m6DBCBbCvBO:-Nbx7v2a7gJw01OA1Qlk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

desc
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java` line 147 at r3](https://reviewable.io/reviews/harness/harness-core/51440#-NbOVHwP1rdc80qVFIqR:-Nbx83m98b81kcWrVXvl:bj67okr) ([raw file](https://github.com/harness/harness-core/blob/d9cadb2b116b52dada1d2777f332fdd2f4be280a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepPlanCreatorV1.java#L147)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

:thumbsup:
</blockquote></details>

added todo
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java` line 46 at r6](https://reviewable.io/reviews/harness/harness-core/51440#-Nbx0niIDsHazQT7RtrC:-Nbx81n47lHau-2XuHyu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5baddef4e77b29be83046544f47c83c79f1a1fda/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepNodeV1.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

move field to spec keyword and remove JsonProperty
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-16 09:02 UTC, shalini-agr commented
trigger uts

2023-08-16 09:03 UTC, shalini-agr commented
trigger uts

2023-08-16 09:45 UTC, archit-harness requested changes
> Reviewed 2 of 14 files at r4, 4 of 4 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 16 file(s) to review. 3 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java` line 81 at r7](https://reviewable.io/reviews/harness/harness-core/51440#-NbxizH77vrea36MMdLG:-NbxizH81OHCe8_sh8SG:b-ajxadt) ([raw file](https://github.com/harness/harness-core/blob/ee3ccd1d1812ecf378e5f24e627b6cc52b3a8436/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java#L81)):*
> ```Java
>     return ParameterField.isNull(stageWhenCondition) ? RunInfoUtilsV1.getDefaultWhenCondition(true, executionMode)
>         : isNotEmpty(stageWhenCondition.getValue())  ? stageWhenCondition.getValue()
>                                                      : stageWhenCondition.getExpressionValue();
> ```

here should we do fetchFinalValue?



_Code quote:_
```Java
        : isNotEmpty(stageWhenCondition.getValue())  ? stageWhenCondition.getValue()
                                                     : stageWhenCondition.getExpressionValue();
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java` line 89 at r7](https://reviewable.io/reviews/harness/harness-core/51440#-Nbxj19K7oWEDTBXFfSZ:-Nbxj19K7oWEDTBXFfS_:bj8bldn) ([raw file](https://github.com/harness/harness-core/blob/ee3ccd1d1812ecf378e5f24e627b6cc52b3a8436/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java#L89)):*
> ```Java
>             : RunInfoUtilsV1.getDefaultWhenCondition(false)
>         : isNotEmpty(stepWhenCondition.getValue()) ? stepWhenCondition.getValue()
>                                                     : stepWhenCondition.getExpressionValue();
> ```

same as above?



_Code quote:_
```Java
        : isNotEmpty(stepWhenCondition.getValue()) ? stepWhenCondition.getValue()
                                                    : stepWhenCondition.getExpressionValue();
```


<!-- Sent from Reviewable.io -->

2023-08-16 09:54 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 16 file(s) to review. 2 change requests. 10. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-17 04:33 UTC, utkarshchoubey-harness approved these changes

2023-08-17 04:38 UTC, shalini-agr commented
trigger review

2023-08-17 05:08 UTC, brijeshdhakar approved these changes
> Reviewed 8 of 14 files at r4, 2 of 4 files at r5, 4 of 4 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 1 change requests. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-17 05:22 UTC, archit-harness approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51440)* status: 1 change requests. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-17 05:56 UTC, merged