feat: [CDS-CDS-76595]: Change code pulse annotations where ever needed
harness/harness-core pull request #51475
Opened 2023-08-08 12:27 UTC by abhinavmittal-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-16 06:56 UTC, puthrayaharness requested changes

2023-08-16 06:56 UTC, puthrayaharness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/servicenow/ServiceNowRefreshTokenAuthentication.java
> +@CodePulse(
This should be approvals

2023-08-16 06:56 UTC, puthrayaharness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = false,
This falls under Approvals

2023-08-16 06:56 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenAuthNgHelper.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
This falls under Approvals only

2023-08-16 06:56 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenResponseHandler.java
> +@CodePulse(
Approvals only

2023-08-16 06:56 UTC, puthrayaharness commented on 980-commons/src/main/java/io/harness/expression/ImageSecretFunctor.java
> -@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_APPROVALS})
This falls under Artifacts

2023-08-16 06:56 UTC, puthrayaharness commented on 999-annotations/src/main/java/io/harness/annotations/dev/HarnessModuleComponent.java
> +  CDS_SLACK,
Please remove Slack. Slack should only be an Approvals component. The component should match Jira component.
Please remove TO_BE_ADDED

2023-08-16 06:56 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/jira/JiraStepHelperServiceImpl.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
Remove common steps. It is approvals only

2023-08-16 06:56 UTC, puthrayaharness commented on pipeline-service/service/src/main/java/io/harness/pms/servicenow/ServiceNowStepHelperServiceImpl.java
> +@CodePulse(
Approvals

2023-08-16 15:33 UTC, naman-goenka commented on 960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenConstants.java
> +    components = {HarnessModuleComponent.CDS_APPROVALS, HarnessModuleComponent.CDS_COMMON_STEPS})
This is currently used in approvals only

2023-08-21 06:23 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51475)* status: 40 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/servicenow/ServiceNowRefreshTokenAuthentication.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295434892:-NcLjh_RCkkgJQiglz4W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/servicenow/ServiceNowRefreshTokenAuthentication.java#L23)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

This should be approvals
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295454184:-NcLjpBP2tSx-LM5OD7W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/jira/JiraTaskNGParameters.java#L31)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

This falls under Approvals
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenAuthNgHelper.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295454824:-NcLjqgW6cjdNf2Ss729:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenAuthNgHelper.java#L60)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

This falls under Approvals only
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenConstants.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1296093862:-NcLjrWt3aATahp_ACOM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenConstants.java#L14)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

This is currently used in approvals only
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/expression/ImageSecretFunctor.java` line 0 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295455843:-NcLjzT10Y1BX0djC6nU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/980-commons/src/main/java/io/harness/expression/ImageSecretFunctor.java#L0)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

This falls under Artifacts
</blockquote></details>

Done.
___
*[`999-annotations/src/main/java/io/harness/annotations/dev/HarnessModuleComponent.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295456827:-NcLk0706jXuafngfDsm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/999-annotations/src/main/java/io/harness/annotations/dev/HarnessModuleComponent.java#L35)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Please remove Slack. Slack should only be an Approvals component. The component should match Jira component.
Please remove TO_BE_ADDED
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/jira/JiraStepHelperServiceImpl.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295457169:-NcLk1j945bnpSzLx2tV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/pipeline-service/service/src/main/java/io/harness/pms/jira/JiraStepHelperServiceImpl.java#L56)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Remove common steps. It is approvals only
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenResponseHandler.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295455142:-NcLjx0zCb1ziZTxvhiH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenResponseHandler.java#L26)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Approvals only
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/servicenow/ServiceNowStepHelperServiceImpl.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/51475#gh-1295457321:-NcLk9ocCbOqy9jXY9QH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd3381c906a24ac5e6c4b5287ea60519a147379e/pipeline-service/service/src/main/java/io/harness/pms/servicenow/ServiceNowStepHelperServiceImpl.java#L67)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Approvals
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 12:44 UTC, puthrayaharness approved these changes

2023-08-21 12:44 UTC, puthrayaharness commented
trigger uts

2023-08-21 13:25 UTC, vcalasansh approved these changes
> Reviewed 16 of 39 files at r1, 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51475)* status: 40 file(s) to review. 9. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-21 17:46 UTC, abhinavmittal-harness commented
trigger messagecheck

2023-08-21 17:49 UTC, abhinavmittal-harness commented
trigger messagecheck

2023-08-21 17:50 UTC, merged