[feat]: [SRM-15298]: Created the DTO and function Signature for the API to get active monitored Services.
harness/harness-core pull request #51473
Opened 2023-08-08 11:39 UTC by shash-harness

## Have Created the DTO that will be used in the API and have defines the function for the API.

## Checklist
- [x] I've documented the changes in the PR description.
- [] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-09 08:48 UTC, shash-harness commented
trigger uts

2023-08-09 10:11 UTC, shash-harness commented
trigger uts

2023-08-09 10:24 UTC, shash-harness commented
trigger uts

2023-08-09 10:37 UTC, shash-harness commented
trigger messagecheck

2023-08-09 11:43 UTC, Varsha-lalwani requested changes
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51473)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java` line 139 at r4](https://reviewable.io/reviews/harness/harness-core/51473#-NbP4VnV5NvKTmoDmSJ7:-NbP4VnV5NvKTmoDmSJ8:b-v8uolg) ([raw file](https://github.com/harness/harness-core/blob/bd6871e5808da16ed8bde2a297b41f3bf0d41dd1/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java#L139)):*
> ```Java
>   List<ActiveServiceMonitoredDTO> listActiveServiceMonitored(ProjectParams projectParams);
> 
>   List<ActiveMonitoredServiceDTO> listActiveMonitoredService(
> ```

listActiveMonitoredServices*



_Code quote:_
```Java
listActiveMonitoredService
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/usage/impl/resources/ActiveMonitoredServiceDTO.java` line 41 at r4](https://reviewable.io/reviews/harness/harness-core/51473#-NbP5Ank8WEN2RHcc1SX:-NbP5Ank8WEN2RHcc1SY:b-wm9i9q) ([raw file](https://github.com/harness/harness-core/blob/bd6871e5808da16ed8bde2a297b41f3bf0d41dd1/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/usage/impl/resources/ActiveMonitoredServiceDTO.java#L41)):*
> ```Java
>   @Schema(description = "Active Monitored Service identifier.") @NotNull String identifier;
>   @Schema(description = "Organization identifier.") String orgIdentifier;
>   @Schema(description = "Project identifier.") String projectIdentifier;
> ```

@NotNull, as MS is project scoped, this should always be present



_Code quote:_
```Java
  @Schema(description = "Organization identifier.") String orgIdentifier;
  @Schema(description = "Project identifier.") String projectIdentifier;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/usage/impl/resources/ActiveMonitoredServiceDTO.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/51473#-NbP5pwg2grPKLesBzY2:-NbP5pwg2grPKLesBzY3:b-8u7n58) ([raw file](https://github.com/harness/harness-core/blob/bd6871e5808da16ed8bde2a297b41f3bf0d41dd1/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/usage/impl/resources/ActiveMonitoredServiceDTO.java#L43)):*
> ```Java
>   @Schema(description = "Project identifier.") String projectIdentifier;
>   @Schema(description = "Environment identifier.") String envIdentifier;
>   @Schema(description = "Active Service Identifier.") String serviceIdentifier;
> ```

mark as not NUll



_Code quote:_
```Java
  @Schema(description = "Environment identifier.") String envIdentifier;
  @Schema(description = "Active Service Identifier.") String serviceIdentifier;
```


<!-- Sent from Reviewable.io -->

2023-08-09 11:44 UTC, Varsha-lalwani requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51473)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2183 at r4](https://reviewable.io/reviews/harness/harness-core/51473#-NbP63Xk4fdAz1-NHIgg:-NbP63Xk4fdAz1-NHIgh:btd09pz) ([raw file](https://github.com/harness/harness-core/blob/bd6871e5808da16ed8bde2a297b41f3bf0d41dd1/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2183)):*
> ```Java
>                    .orgName(nextGenService
>                                 .getOrganization(monitoredService.getAccountId(), monitoredService.getOrgIdentifier())
>                                 .getName())
> ```

if service, env, org, project not presen, sett their names as null. something similar to this:

if (projectParams.getOrgIdentifier() != null) {  
  organizationDTO =  
      nextGenService.getOrganization(projectParams.getAccountIdentifier(), projectParams.getOrgIdentifier());  
}  
if (projectParams.getProjectIdentifier() != null) {  
  projectDTO = nextGenService.getProject(  
      projectParams.getAccountIdentifier(), projectParams.getOrgIdentifier(), projectParams.getProjectIdentifier());  
}  
if (entityDetails.get(SERVICE\_IDENTIFIER) != null) {  
  serviceResponseDTO =  
      nextGenService.getService(projectParams.getAccountIdentifier(), projectParams.getOrgIdentifier(),  
          projectParams.getProjectIdentifier(), entityDetails.get(SERVICE\_IDENTIFIER).toString());  
}  
  
String serviceName = Objects.isNull(serviceResponseDTO) ? null : serviceResponseDTO.getName();  
String orgName = Objects.isNull(organizationDTO) ? null : organizationDTO.getName();  
String projectName = Objects.isNull(projectDTO) ? null : projectDTO.getName();



_Code quote:_
```Java
                   .serviceName(
                       nextGenService
                           .getService(monitoredService.getAccountId(), monitoredService.getOrgIdentifier(),
                               monitoredService.getProjectIdentifier(), monitoredService.getServiceIdentifier())
                           .getName())
                   .envName(
                       nextGenService
                           .getEnvironment(monitoredService.getAccountId(), monitoredService.getOrgIdentifier(),
                               monitoredService.getProjectIdentifier(), monitoredService.getEnvironmentIdentifier())
                           .getName())
                   .projectName(nextGenService
                                    .getProject(monitoredService.getAccountId(), monitoredService.getOrgIdentifier(),
                                        monitoredService.getProjectIdentifier())
                                    .getName())
                   .orgName(nextGenService
                                .getOrganization(monitoredService.getAccountId(), monitoredService.getOrgIdentifier())
                                .getName())
```


<!-- Sent from Reviewable.io -->

2023-08-10 03:49 UTC, shash-harness commented
trigger uts

2023-08-10 05:22 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +          if (monitoredService.getOrgIdentifier() != null && monitoredService.getProjectIdentifier() != null) {
this will always be true

2023-08-10 05:22 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            if (monitoredService.getServiceIdentifier() != null) {
this as well

2023-08-10 08:34 UTC, shash-harness commented
trigger uts

2023-08-10 09:20 UTC, Varsha-lalwani approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r2, 1 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51473#-:-NbTjtxE-7vHb_XkHpOM:bnfp4nl)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-08-10 09:21 UTC, merged