feat: [IDP-913]: Score computation
harness/harness-core pull request #51513
Opened 2023-08-09 10:17 UTC by vikyathharekal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-09 14:06 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntity.java
> +  private String kind;
Do we need kind here ? It is defined in the inherited classes to be more concrete. Please check if we can use that itself.
Ex. -
```
private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
private String kind = BackstageCatalogEntityTypes.DOMAIN.kind;
```

2023-08-09 14:10 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      default:
default will not be needed here as "fromString" function also handles bad inputs. Moreover if we need to have default, it is better to throw error as it is a bad input which we don't recognise

2023-08-09 14:11 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      default:
Same as above comment. Just see if we need default. Else we can return null along with case GROUP itself

2023-08-09 14:12 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogGroupEntity.java
> +  private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
This will be BackstageCatalogEntityTypes.GROUP.kind

2023-08-09 14:12 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogLocationEntity.java
> +  private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
Same as above comment. This will be BackstageCatalogEntityTypes.LOCATION.kind

2023-08-09 14:12 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogTemplateEntity.java
> +  private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
Same as above comment. This will be BackstageCatalogEntityTypes.TEMPLATE.kind

2023-08-09 14:15 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckRepository.java
> +  List<CheckEntity> findByAccountIdentifierAndIsDeletedAndIdentifierIn(
I think a similar discussion we had earlier. Just make sure indexes are getting used.
From what I remember, fields order in the query doesn't matter ?

2023-08-09 14:17 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/datapoints/constants/DataPoints.java
> +  public static final String GITHUB_IS_BRANCH_PROTECTED = "isBranchProtected";
May be have a common prefix for similar DPs ?
Ex. All github DPs will start with "github_"

2023-08-09 14:19 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubIsBranchProtectedParser.java
> +    Map<?, ?> result = (Map<?, ?>) data.get(dataPoint.getIdentifier());
Capture of ? is not required here I think.

2023-08-09 14:22 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/constants/DataSourceLocations.java
> +  public static final String GITHUB_PR = "pr";
Similar to one of the previous comment. prefixing looks good right ? May be we can stay like that only.
```
public static final String GITHUB_PR = "github_pr";
public static final String GITHUB_BASE = "github_base";
```

2023-08-09 14:34 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java
> +    ObjectMapper mapper = new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
We can use singleton object here. And if we are planning to move this to common util, then we can support that in the util itself.

2023-08-09 14:51 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      default:
Checked. Default is needed when none of the cases match.

2023-08-09 14:52 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      default:
Default is needed when none of the cases match. Throwing an exception

2023-08-09 14:52 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogGroupEntity.java
> +  private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
Done

2023-08-09 14:52 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogLocationEntity.java
> +  private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
Done

2023-08-09 14:52 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogTemplateEntity.java
> +  private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
Done

2023-08-09 14:53 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/datapoints/constants/DataPoints.java
> +  public static final String GITHUB_IS_BRANCH_PROTECTED = "isBranchProtected";
So this dataPoint identidier "isBranchProtected" will appear in the expression. Expression already has data source "github".
Example expression: `github.isBranchProtected.master=true`

2023-08-09 15:02 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogTemplateEntity.java
> +  private String kind = BackstageCatalogEntityTypes.COMPONENT.kind;
Done

2023-08-09 15:04 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckRepository.java
> +  List<CheckEntity> findByAccountIdentifierAndIsDeletedAndIdentifierIn(
Yes. The order of the fields in the index only matters if the query doesn't include all of the fields in the index

2023-08-10 03:50 UTC, vigneswara-propelo requested changes
> Reviewed 26 of 48 files at r1, 17 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51513)* status: 48 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardRepository.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/51513#-NbSWS2u7luaw6o_-0vb:-NbSWS2u7luaw6o_-0vc:b-6ugukd) ([raw file](https://github.com/harness/harness-core/blob/eee3042a7a5d5ff47430abc8e675d054d31406e7/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardRepository.java#L21)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public interface ScorecardRepository extends CrudRepository<ScorecardEntity, String>, ScorecardRepositoryCustom {
>   List<ScorecardEntity> findByAccountIdentifierAndPublished(String accountIdentifier, boolean published);
> ```

We need to have a separate method as this is currently used to list all the available scorecards. Both drafted and published
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/51513#-NbSZ1t33eEbnXblkJOY:-NbSZ1t33eEbnXblkJOZ:bxxos8z) ([raw file](https://github.com/harness/harness-core/blob/eee3042a7a5d5ff47430abc8e675d054d31406e7/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java#L56)):*
> ```Java
>     List<Scorecard> scorecards = new ArrayList<>();
>     List<ScorecardEntity> scorecardEntities =
>         scorecardRepository.findByAccountIdentifierAndPublished(accountIdentifier, true);
> ```

same as above comment


<!-- Sent from Reviewable.io -->

2023-08-10 04:11 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntity.java
> +  private String kind;
Will move to abstract later

2023-08-10 04:36 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java
> +        Object entitiesResponse = getGeneralResponse(backstageResourceClient.getCatalogEntities(url));
Moved to static final

2023-08-10 04:36 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java
> +    ObjectMapper mapper = new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
Moved to static final

2023-08-10 04:38 UTC, vikyathharekal reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51513)* status: 48 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardRepository.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/51513#-NbSWS2u7luaw6o_-0vb:-NbSjBoE6ryjjTjppOHB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eee3042a7a5d5ff47430abc8e675d054d31406e7/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardRepository.java#L21)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

We need to have a separate method as this is currently used to list all the available scorecards. Both drafted and published
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/51513#-NbSZ1t33eEbnXblkJOY:-NbSjCtzElMEWh1qTc44:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eee3042a7a5d5ff47430abc8e675d054d31406e7/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java#L56)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

same as above comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-10 04:40 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/datapoints/constants/DataPoints.java
> +  public static final String GITHUB_IS_BRANCH_PROTECTED = "isBranchProtected";
Added datasource in the index

2023-08-10 04:55 UTC, mankrit-singh approved these changes

2023-08-10 05:04 UTC, vigneswara-propelo approved these changes

2023-08-10 05:46 UTC, sandeepa-kv-jois approved these changes

2023-08-10 05:46 UTC, sandeepa-kv-jois commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      case TEMPLATE:
Template is not a Kind. Also, we have API, USER and RESOURCE.

2023-08-10 05:46 UTC, sandeepa-kv-jois commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      case TEMPLATE:
Template is not a Kind. Also, API, USER and RESOURCE are valid ones.

2023-08-10 05:48 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      case TEMPLATE:
<img width="837" alt="template" src="https://github.com/harness/harness-core/assets/107480501/ef3c0b2e-1003-45db-a721-754eb6df04fd">
Template is listed here 🤔 
Do we have a list mentioned somewhere?

2023-08-10 05:54 UTC, sandeepa-kv-jois commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +      case TEMPLATE:
Ok, it shows up only if the template is added. Other valid ones like API, USER and RESOURCE also need to be handled in the above case block.

2023-08-10 05:54 UTC, vikyathharekal commented
trigger uts

2023-08-10 05:55 UTC, vikyathharekal commented
trigger review

2023-08-10 05:55 UTC, sandeepa-kv-jois commented on idp-service/src/main/java/io/harness/idp/onboarding/beans/BackstageCatalogEntityTypes.java
> +  TEMPLATE("Template");
Other valid ones like API, USER and RESOURCE need to be added here.

2023-08-10 06:03 UTC, devesh-harness approved these changes

2023-08-10 07:35 UTC, vikyathharekal commented
trigger ut8

2023-08-10 11:13 UTC, vikyathharekal commented
trigger uts

2023-08-10 14:38 UTC, vikyathharekal commented
trigger uts

2023-08-10 15:54 UTC, vikyathharekal commented
trigger ut5

2023-08-10 17:00 UTC, merged