[feat]: [CDS-66696]: Not allow saving pipeline when use from stages' stage not present
harness/harness-core pull request #51538
Opened 2023-08-09 18:48 UTC by lovish1999

## Describe your changes
<img width="1312" alt="Screenshot 2023-08-10 at 12 21 53 AM" src="https://github.com/harness/harness-core/assets/105869285/7e4ce5ea-4c70-44f0-bc55-f3ba287079ac">

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/51538)

2023-08-10 10:07 UTC, ivan-83 requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51538)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 175 at r1](https://reviewable.io/reviews/harness/harness-core/51538#-NbTtTyHCa3W-oUvOZSh:-NbTtTyHCa3W-oUvOZSi:b-sr5q4b) ([raw file](https://github.com/harness/harness-core/blob/b727df9466c86b9b8e2873e17511764988995640/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L175)):*
> ```Java
>             "cannot save a stage template that propagates service from another stage. Please remove useFromStage and set the serviceRef to fixed value or runtime or an expression and try again");
>       }
>       String useFromStageIdentifier = deploymentStageConfig.getService().getUseFromStage().getStage();
> ```

If deploymentStageConfig.getService().getUseFromStage() will return the null for deployments where we are not using the service from another stage, will get NPE?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/51538#-NbTsAag7aifofce1M31:-NbTsAah91DEgx9oSUzJ:b-lft40) ([raw file](https://github.com/harness/harness-core/blob/b727df9466c86b9b8e2873e17511764988995640/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L187)):*
> ```Java
>             "cannot save a stage template that propagates environment from another stage. Please remove useFromStage and set the environmentRef to fixed value or runtime or an expression and try again");
>       }
>       String useFromStageIdentifier = deploymentStageConfig.getEnvironment().getUseFromStage().getStage();
> ```

If deploymentStageConfig.getEnvironment().getUseFromStage() returns the null for deployments where we are not using the env from another stage, will get NPE?


<!-- Sent from Reviewable.io -->

2023-08-10 11:11 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51538)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 175 at r1](https://reviewable.io/reviews/harness/harness-core/51538#-NbTtTyHCa3W-oUvOZSh:-NbU7wxq2TGa5foRDn3v:b-54lkwg) ([raw file](https://github.com/harness/harness-core/blob/b727df9466c86b9b8e2873e17511764988995640/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L175)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

If deploymentStageConfig.getService().getUseFromStage() will return the null for deployments where we are not using the service from another stage, will get NPE?
</blockquote></details>

It should not because we are already having that check in the `usesServiceFromAnotherStage` method. 
if (usesServiceFromAnotherStage(deploymentStageConfig)) at line 170
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/51538#-NbTsAag7aifofce1M31:-NbU88gTAbjWJEOFHK64:b-eyhbob) ([raw file](https://github.com/harness/harness-core/blob/b727df9466c86b9b8e2873e17511764988995640/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L187)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

If deploymentStageConfig.getEnvironment().getUseFromStage() returns the null for deployments where we are not using the env from another stage, will get NPE?
</blockquote></details>

It should not because we are already having that check in the `usesServiceFromAnotherStage` method. 
if (usesServiceFromAnotherStage(deploymentStageConfig))


<!-- Sent from Reviewable.io -->

2023-08-10 17:31 UTC, lovish1999 commented
trigger uts

2023-08-10 20:06 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51538#-:-NbW2cUHEBOGeWKUP7mu:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-11 09:11 UTC, lovish1999 commented
trigger ut7

2023-08-11 09:16 UTC, lovish1999 commented
trigger messagecheck

2023-08-11 12:40 UTC, tchaurasiya requested changes

2023-08-11 12:40 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +      if (useFromStageDoesNotExist(filterCreationContext.getCurrentField(), useFromStageIdentifier)) {
nit: Lets use method Name referredStageForPropagationDoesNotExist, current name confusing with useFromStage node itself does not exist

2023-08-11 12:40 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +        && YamlNodeUtils.findFirstNodeMatchingFieldName(
Wouldn't give false true, if any other entity name matches to stage name?
Rather we should match at the exact FQN path, That can be stages --> or stages.parallel -->

2023-08-23 11:51 UTC, lovish1999 commented
trigger uts

2023-08-23 12:03 UTC, lovish1999 commented
trigger uts

2023-08-24 07:26 UTC, lovish1999 commented
trigger ut1

2023-08-24 07:27 UTC, lovish1999 commented
trigger ut7

2023-08-24 18:16 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +        && YamlNodeUtils.findFirstNodeMatchingFieldName(
As discussed offline, we won't be adding this stricter validation to avoid any false negative error cases.

2023-08-24 18:26 UTC, lovish1999 commented
trigger uts

2023-08-24 19:29 UTC, ivan-83 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +            "cannot save a stage template that propagates service from another stage. Please remove useFromStage and set the serviceRef to fixed value or runtime or an expression and try again");
Minor - cannot >> Cannot ... we start usually error msg with the noun in this case Stage template.

..and set the serviceRef to fixed value or runtime or an expression >> and set the serviceRef to fixed value, runtime or an expressin.

2023-08-24 19:29 UTC, ivan-83 commented on 953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java
>    private YamlNode findFieldNameInObject(YamlNode yamlNode, String fieldName) {
Minor - if fieldName is null, will get NPE on line 184

2023-08-24 19:29 UTC, ivan-83 commented on 953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java
>      if (yamlNode == null) {
Minor - if fieldName is null, will get NPE on line 214. And there wasn't a need for else if we could use || . The method name could be findFirstFiledNameInArray

2023-08-24 19:29 UTC, ivan-83 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +            "cannot save a stage template that propagates environment from another stage. Please remove useFromStage and set the environmentRef to fixed value or runtime or an expression and try agai
The same as above.

2023-08-24 19:30 UTC, ivan-83 reviewed
LGTM with minor comments.

2023-08-25 05:31 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +            "cannot save a stage template that propagates service from another stage. Please remove useFromStage and set the serviceRef to fixed value or runtime or an expression and try again");
changed

2023-08-25 05:31 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +            "cannot save a stage template that propagates environment from another stage. Please remove useFromStage and set the environmentRef to fixed value or runtime or an expression and try agai
changed

2023-08-25 05:32 UTC, lovish1999 commented on 953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java
>      if (yamlNode == null) {
changed

2023-08-25 05:32 UTC, lovish1999 commented on 953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java
>    private YamlNode findFieldNameInObject(YamlNode yamlNode, String fieldName) {
added check

2023-08-25 07:18 UTC, ivan-83 submitted a review, later dismissed
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51538)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java` line 180 at r5](https://reviewable.io/reviews/harness/harness-core/51538#-NcfYMbv-pcMSx8Uf22R:-NcfYMbv-pcMSx8Uf22S:b-gs7cpl) ([raw file](https://github.com/harness/harness-core/blob/273cf518dabda5145b9589c51f7bb7261b4b4d58/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java#L180)):*
> ```Java
>    */
>   private YamlNode findFieldNameInObject(YamlNode yamlNode, String fieldName) {
>     if (yamlNode == null) {
> ```

It could be a better solution, 
if(yamlNode == null || isEmpty(fieldName)) {
    return null;
}
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java` line 210 at r5](https://reviewable.io/reviews/harness/harness-core/51538#-NcfYeNB4qWoA0sY9o3H:-NcfYeNB4qWoA0sY9o3I:b-7ralkp) ([raw file](https://github.com/harness/harness-core/blob/273cf518dabda5145b9589c51f7bb7261b4b4d58/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java#L210)):*
> ```Java
>    */
>   private YamlNode findFieldNameInArray(YamlNode yamlNode, String fieldName) {
>     if (yamlNode == null) {
> ```

the same as above. 


<!-- Sent from Reviewable.io -->

2023-08-25 07:41 UTC, lovish1999 commented
trigger uts

2023-08-25 07:59 UTC, lovish1999 commented
trigger uts

2023-08-25 09:19 UTC, lovish1999 commented
trigger ut4

2023-08-25 09:19 UTC, lovish1999 commented
trigger ut9

2023-08-25 13:48 UTC, lovish1999 commented
trigger ut9

2023-08-28 05:35 UTC, tchaurasiya requested changes

2023-08-28 05:35 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +      }
Can we fix the error message, Its for environment

2023-08-28 05:35 UTC, tchaurasiya commented on 953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNodeUtils.java
> +      if (isNotEmpty(fieldName) && fieldName.equals(childYamlField.getName())) {
nit: if fieldName is empty, shouldn't be directly return null. Instead of iterating over YamlNode

2023-08-28 06:56 UTC, lovish1999 commented
trigger uts

2023-08-28 07:23 UTC, lovish1999 commented
trigger uts

2023-08-29 11:10 UTC, lovish1999 commented
trigger ut5

2023-08-29 11:10 UTC, lovish1999 commented
trigger ut7

2023-08-29 11:10 UTC, lovish1999 commented
trigger ut8

2023-08-29 11:10 UTC, lovish1999 commented
trigger ut9

2023-08-29 12:37 UTC, lovish1999 commented
trigger ut7

2023-08-29 12:37 UTC, lovish1999 commented
trigger ut8

2023-08-29 14:03 UTC, lovish1999 commented
trigger ut5

2023-08-29 17:37 UTC, lovish1999 commented
trigger ut5

2023-08-29 17:54 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51538#-:-Nd1QlPN-LGBgsc5aCzX:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-30 03:17 UTC, tchaurasiya approved these changes

2023-08-30 03:46 UTC, lovish1999 commented
trigger review

2023-08-30 07:05 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 3 files at r1, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51538)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-30 07:05 UTC, merged