[feat]: [CDS-76328]: generating individual step/stage/stepGroup schema from the pipeline schema json
harness/harness-core pull request #51532
Opened 2023-08-09 16:58 UTC by brijeshdhakar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/51532)

2023-08-09 18:19 UTC, brijeshdhakar commented
trigger uts

2023-08-10 06:26 UTC, brijeshdhakar commented
trigger uts

2023-08-10 08:07 UTC, brijeshdhakar commented
trigger uts

2023-08-10 20:43 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBCTr7nSilmH5OdGP:-NbWBCTr7nSilmH5OdGQ:b26q6k2) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L48)):*
> ```Java
>     isInitialised = true;
>   }
>   protected abstract void init(JsonNode rootSchemaNode);
> ```

every method is by default protected so we don't need to use the keyword explicitly


<!-- Sent from Reviewable.io -->

2023-08-10 20:44 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBL5o5U3DCwamp0mI:-NbWBL5o5U3DCwamp0mJ:b-uuqx25) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L40)):*
> ```Java
>   public boolean isInitialised() {
>     return isInitialised;
>   }
> ```

line spacing missing after method


<!-- Sent from Reviewable.io -->

2023-08-10 20:44 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBP2j6ZN0Nz58VkDa:-NbWBP2j6ZN0Nz58VkDb:b-nd38nl) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L34)):*
> ```Java
> 
>   Map<String, ObjectNode> nodeToResolvedSchemaMap =
>       new HashMap<>(); // It contains the complete resolved schema for a node.
> ```

lets add more comments to describe whats a "node" here


<!-- Sent from Reviewable.io -->

2023-08-10 20:45 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 47 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBUqQ9h0uZ0L2KiGe:-NbWBUqQ9h0uZ0L2KiGf:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L47)):*
> ```Java
>     }
>     isInitialised = true;
>   }
> ```

line spacing missing


<!-- Sent from Reviewable.io -->

2023-08-10 20:45 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 55 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBYnM2eWYXdpR_3kd:-NbWBYnM2eWYXdpR_3ke:b-l721d0) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L55)):*
> ```Java
>   protected void parseAndIngestSchema(JsonNode jsonNode) {
>     parseAndIngestSchemaInternal(jsonNode, "#");
>   }
> ```

line spacing


<!-- Sent from Reviewable.io -->

2023-08-10 20:46 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 76 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBfOQ9K4p8THaPcid:-NbWBfOQ9K4p8THaPcie:b8j3q83) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L76)):*
> ```Java
>   public JsonNode getFieldNode(InputFieldMetadata inputFieldMetadata) {
>     String[] fqnParts = inputFieldMetadata.fqnFromParentNode.split("\\.");
>     Map<String, ObjectNode> nodeMap = getApplicableNodeMap(fqnParts[0]);
> ```

Lets add a comment here what does fqn[0] represents here


<!-- Sent from Reviewable.io -->

2023-08-10 20:46 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBjai7Wgq75HS-pFv:-NbWBjai7Wgq75HS-pFw:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L86)):*
> ```Java
>     }
>     return targetFieldNode;
>   }
> ```

line spacing missing


<!-- Sent from Reviewable.io -->

2023-08-10 20:46 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 138 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBsA5AZWMeej6IG3B:-NbWBsA5AZWMeej6IG3C:b7v0gkc) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L138)):*
> ```Java
>     ObjectNode defNode = (ObjectNode) JsonUtils.readTree("  {}");
>     resolveRefsInNodeRecursively(defNode, objectNode, context);
>     objectNode.set(DEFINITIONS_NODE, defNode);
> ```

We discussed right that we don't need this definitions thing? 


<!-- Sent from Reviewable.io -->

2023-08-10 20:47 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 182 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWC3Qm8D3yjteqy3BI:-NbWC3Qm8D3yjteqy3BJ:bxkpmeg) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L182)):*
> ```Java
>   }
> 
>   JsonNode getJsonNodeByPath(ObjectNode definitionsNode, String path, IndividualSchemaGenContext context) {
> ```

we should have some description here to denote what does all the params represent here. Also, should it be protected or private?


<!-- Sent from Reviewable.io -->

2023-08-10 20:49 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 41 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCPRc4xyb-XZ8AzKu:-NbWCPRc4xyb-XZ8AzKv:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L41)):*
> ```Java
>   static final String PIPELINE_DEFINITION_PATH = "#/definitions/pipeline/pipeline";
>   static final String STEPS_DEFINITION_PATH = "#/definitions/pipeline/steps";
>   @Override
> ```

line spacing missing


<!-- Sent from Reviewable.io -->

2023-08-10 20:49 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCY6_7AhW-uyC0UjF:-NbWCY6_7AhW-uyC0UjG:b-ctrr75) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L72)):*
> ```Java
>   Map<String, ObjectNode> getApplicableNodeMap(String parentNode) {
>     switch (parentNode) {
>       case "pipeline":
> ```

won't it contain more such entries eg: stepGroup, or similar?


<!-- Sent from Reviewable.io -->

2023-08-10 20:50 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCcQI5U5DndREGjra:-NbWCcQI5U5DndREGjrb:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L79)):*
> ```Java
>         return stepToNodeMap;
>     }
>   }
> ```

line spacing missing


<!-- Sent from Reviewable.io -->

2023-08-10 20:50 UTC, mohitg0795 commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 129 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCf1v2nMplvOOyoXb:-NbWCf1v2nMplvOOyoXc:b-l721d0) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L129)):*
> ```Java
>     }
>     throw new InvalidRequestException("Provided nodeGroup not supported");
>   }
> ```

line spacing


<!-- Sent from Reviewable.io -->

2023-08-14 08:20 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51532)* status: 13 file(s) to review. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBP2j6ZN0Nz58VkDa:-Nbn7M4n-w7c7UpbUXmh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets add more comments to describe whats a "node" here
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBL5o5U3DCwamp0mI:-Nbn7NHE8DNvn3SkJtAX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing after method
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 47 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBUqQ9h0uZ0L2KiGe:-Nbn7NuL-TeOthuHAOFg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBCTr7nSilmH5OdGP:-Nbn7OcU4FTylFVY_FMq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

every method is by default protected so we don't need to use the keyword explicitly
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 55 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBYnM2eWYXdpR_3kd:-Nbn7PKHD-XUCqjzVmUp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 76 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBfOQ9K4p8THaPcid:-Nbn7Qdu40Lu18Jg3sJ-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L76)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets add a comment here what does fqn[0] represents here
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBjai7Wgq75HS-pFv:-Nbn7ROc-9xyYFzkwlgD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L86)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 182 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWC3Qm8D3yjteqy3BI:-Nbn7T432oiivEGIXMRg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L182)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should have some description here to denote what does all the params represent here. Also, should it be protected or private?
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 41 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCPRc4xyb-XZ8AzKu:-Nbn7To5DE8zExL8_6zl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCY6_7AhW-uyC0UjF:-Nbn7UBpEBffhjEn3m4J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L72)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

won't it contain more such entries eg: stepGroup, or similar?
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCcQI5U5DndREGjra:-Nbn7UgC547qSPKJ9w9e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L79)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java` line 129 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWCf1v2nMplvOOyoXb:-Nbn7V0w7pP5iZHZ2qbj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/PipelineSchemaParser.java#L129)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-14 09:10 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51532)* status: 13 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnBoi85k-RbO8h2bc7:-NbnBoi85k-RbO8h2bc8:b19bgp9) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L29)):*
> ```Java
> import lombok.Builder;
> 
> public abstract class AbstractStaticSchemaParser {
> ```

add comment explaining nodeToResolvedSchemaMap is provided by abstract method - checkIfRootNodeAndAddIntoFqnToNodeMap and can be added based on impl
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-Nbn8c865lXg6bWFOYP-:-Nbn8c865lXg6bWFOYP0:b-humlye) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L30)):*
> ```Java
> 
> public abstract class AbstractStaticSchemaParser {
>   Map<String, ObjectNode> typeToNodeMap = new HashMap<>();
> ```

as per usecase this should be saved, but infact the method will use nodeToResolvedSchemaMap and then fetch further on given fqn to return field schema
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-Nbn9bN2D_44hLYLepEj:-Nbn9bN2D_44hLYLepEk:b7wmmr7) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L31)):*
> ```Java
> public abstract class AbstractStaticSchemaParser {
>   Map<String, ObjectNode> typeToNodeMap = new HashMap<>();
>   Map<String, ObjectNodeWithMetadata> fqnToNodeMap = new HashMap<>();
> ```

mention value is unresolved, fqn share some example 
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnDnqF-gQ3pjxMWh7E:-NbnDnqF-gQ3pjxMWh7F:bh97mi3) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L37)):*
> ```Java
>       new HashMap<>(); // It contains the complete resolved schema for a node. A node can be for any
>                        // step/stage/stepGroup or pipeline or for any object like matrix/strategy.
>   JsonNode rootSchemaJsonNode;
> ```

mention this is the input root, which will never change and act as source of truth
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnE8X_BVWzhEYGN05z:-NbnE8X_BVWzhEYGN06-:b-moa23) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L59)):*
> ```Java
>   abstract String getApplicableNodePath(String parentNode, String nodeType);
> 
>   void traverseNodeAndExtractAllRefsRecursively(JsonNode jsonNode, String currentFqn) {
> ```

it only handles array and objectNode and primitives like textNode doesn't need to be handled
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 68 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnE_fb2xCtKr0358BS:-NbnE_fc4fKF37-COoJo:b-75g6bq) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L68)):*
> ```Java
>       }
>     }
>     if (jsonNode instanceof ObjectNode) {
> ```

else if condition
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 70 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFAgr6mQ0Tzw-yGOg:-NbnFAgr6mQ0Tzw-yGOh:b-3a6siw) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L70)):*
> ```Java
>     if (jsonNode instanceof ObjectNode) {
>       Set<String> fieldNames = new LinkedHashSet<>();
>       jsonNode.fieldNames().forEachRemaining(fieldNames::add);
> ```

why separate set of fieldNames is needed, can we traverse directly on fieldNames method



_Code quote:_
```Java
jsonNode.fieldNames().forEachRemaining(fieldNames::add);
```
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 73 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFLQl4hRwy-f7wHu8:-NbnFLQl4hRwy-f7wHu9:b-d7ulwk) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L73)):*
> ```Java
> 
>       for (String childFieldName : fieldNames) {
>         if (childFieldName.equals(DEFINITIONS_NODE)) {
> ```

why skip add comment
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 77 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFO_REFnzmV4pUjol:-NbnFO_REFnzmV4pUjom:b-nhm0n5) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L77)):*
> ```Java
>         }
>         JsonNode childNode = jsonNode.get(childFieldName);
>         if (childFieldName.equals(PROPERTIES_NODE)) {
> ```

as properties node contains all fields
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 81 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFSFm6QA2CMRcoklq:-NbnFSFm6QA2CMRcoklr:b-q9vlze) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L81)):*
> ```Java
>           continue;
>         }
>         if (childFieldName.equals(REF_NODE)) {
> ```

add comment telling ref node means ref and not complete schema
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 84 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnG4QQ-JlIcsXtCLvv:-NbnG4QQ-JlIcsXtCLvw:b9oyocy) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L84)):*
> ```Java
>           if (!childNode.asText().startsWith(DEFINITIONS_STRING_PREFIX)) {
>             continue;
>           }
> ```

add comment that this condition handles all definitions exists inside definitions path and if not, then it doesn't traverse inside it



_Code quote:_
```Java
          if (!childNode.asText().startsWith(DEFINITIONS_STRING_PREFIX)) {
            continue;
          }
```
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 117 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnGyMp3DEziFwhJFVr:-NbnGyMp3DEziFwhJFVs:b-iagrn1) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L117)):*
> ```Java
>             currentPath.toString(), ObjectNodeWithMetadata.builder().objectNode((ObjectNode) jsonNode).build());
>       }
>     }
> ```

add for loop is helping to add  [...]

2023-08-16 09:39 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51532)* status: 15 file(s) to review. 1 change requests. 32. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 138 at r4](https://reviewable.io/reviews/harness/harness-core/51532#-NbWBsA5AZWMeej6IG3B:-NbxWIiv4eB4GynoQmOv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b07a786a6c1c2f6aeb52efae5f643facb4f4bfc/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L138)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We discussed right that we don't need this definitions thing? 
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnBoi85k-RbO8h2bc7:-NbxVhCB7LUFRQMQy2cL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment explaining nodeToResolvedSchemaMap is provided by abstract method - checkIfRootNodeAndAddIntoFqnToNodeMap and can be added based on impl
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-Nbn8c865lXg6bWFOYP-:-NbxVmax2DPNuXvAFUdQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as per usecase this should be saved, but infact the method will use nodeToResolvedSchemaMap and then fetch further on given fqn to return field schema
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-Nbn9bN2D_44hLYLepEj:-NbxVnZQDqsPj_eM5jyy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

mention value is unresolved, fqn share some example
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnDnqF-gQ3pjxMWh7E:-NbxVqzSAxnnx7oLZ1NE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

mention this is the input root, which will never change and act as source of truth
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnE8X_BVWzhEYGN05z:-NbxVsdA-al4xGNl4Zq1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it only handles array and objectNode and primitives like textNode doesn't need to be handled
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 68 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnE_fb2xCtKr0358BS:-NbxVvEV26eZlVwHqkAU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

else if condition
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 70 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFAgr6mQ0Tzw-yGOg:-NbxVwTsC4O0nz2LXnF3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why separate set of fieldNames is needed, can we traverse directly on fieldNames method
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 73 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFLQl4hRwy-f7wHu8:-Nbxh-vrAhHnkW0Y7Ppp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why skip add comment
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 77 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFO_REFnzmV4pUjol:-NbxW1LUCRO-Ovr5M5OD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L77)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as properties node contains all fields
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 81 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnFSFm6QA2CMRcoklq:-NbxW6KzECw82Hlo6aOC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment telling ref node means ref and not complete schema
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 84 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnG4QQ-JlIcsXtCLvv:-NbxW7nxAF2UBrlP8iin:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L84)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment that this condition handles all definitions exists inside definitions path and if not, then it doesn't traverse inside it
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java` line 117 at r6](https://reviewable.io/reviews/harness/harness-core/51532#-NbnGyMp3DEziFwhJFVr:-NbxW8wCCtG0jFB5kXht:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba4ee849d06a83d7fb7436453f07f346244373c7/953-yaml-commons/src/main/java/io/harness/pms/yaml/AbstractStaticSchemaParser.java#L117)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrot [...]

2023-08-16 09:39 UTC, brijeshdhakar commented
trigger uts

2023-08-16 12:34 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51532)* status: 17 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlFieldConstants.java` line 10 at r8](https://reviewable.io/reviews/harness/harness-core/51532#-NbyIMol797MypExGR_2:-NbyKdxT7jj4H_GdiXvK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e7d0fdd3ba11492994df89ee10f08a1048ef035/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlFieldConstants.java#L10)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to schema fieldConstants to avoid clash?
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputType.java` line 10 at r8](https://reviewable.io/reviews/harness/harness-core/51532#-NbyIR_p6GXPiAZ0EnjL:-NbyKeiHAZ9_jRgyqY_f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e7d0fdd3ba11492994df89ee10f08a1048ef035/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlInputType.java#L10)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

schema input type
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/jackson/JsonNodeUtils.java` line 345 at r8](https://reviewable.io/reviews/harness/harness-core/51532#-NbyIkKq3mNTA2Yb13OY:-NbyKfdq1YRtxaUZ1dQX:b-rn6463) ([raw file](https://github.com/harness/harness-core/blob/6e7d0fdd3ba11492994df89ee10f08a1048ef035/980-commons/src/main/java/io/harness/jackson/JsonNodeUtils.java#L345)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this cant be moved to JsonPipelineUtils?
</blockquote></details>

Done. This i had added earlier so did not move. Moved now.


<!-- Sent from Reviewable.io -->

2023-08-16 12:36 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 8 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51532)* status: 17 file(s) to review. 13. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-16 16:55 UTC, brijeshdhakar commented
trigger uts

2023-08-16 17:17 UTC, brijeshdhakar commented
trigger uts

2023-08-16 18:04 UTC, brijeshdhakar commented
trigger uts

2023-08-17 05:15 UTC, brijeshdhakar commented
trigger messagecheck

2023-08-17 05:17 UTC, brijeshdhakar commented
trigger messagecheck

2023-08-17 05:21 UTC, archit-harness approved these changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51532)* status: 17 file(s) to review. 13. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-17 06:55 UTC, mohitg0795 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51532)* status: 17 file(s) to review. 6. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-17 06:56 UTC, brijeshdhakar commented
trigger review

2023-08-17 07:03 UTC, merged