fix: [PLG-2123] Fix the version endpoint for FF version in Release Notes
harness/harness-core pull request #51541
Opened 2023-08-09 23:40 UTC by neelam-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-10 08:20 UTC, davejohnston commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java
> +        ffApiUrl.append(nextGenConfiguration.getFfServerClientConfig().getBaseUrl());
I'm not sure if this will return the correct URL or not.  Do you have a link to the configuration that is used?

2023-08-10 09:34 UTC, ribeirophillipe commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java
> +        return nextGenConfiguration.getNgManagerClientConfig().getBaseUrl();
perhaps converting to a switch statement would make the code cleaner and more readable

2023-08-10 18:46 UTC, neelam-harness commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java
> +        return nextGenConfiguration.getNgManagerClientConfig().getBaseUrl();
good idea! I'll follow it up in another parallel task here: [PLG-2233 ](https://harness.atlassian.net/browse/PLG-2233)

2023-08-11 06:35 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51541)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/51541#gh-1289842800:-NbYG8Cy2e2KZr-pw6BW:b-l9t5y2) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L98)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

good idea! I'll follow it up in another parallel task here: [PLG-2233 ](https://harness.atlassian.net/browse/PLG-2233)
</blockquote></details>

Yes switch case makes more sense and lets throw error in the default case.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYHN1f7Lq2u_X9Bpk-:-NbYHN1f7Lq2u_X9Bpk0:bh4au2g) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L115)):*
> ```Java
>         return ffApiUrl.toString();
>       }
>     } catch (Exception e) {
> ```

this try catch is redundant as you already have a try catch in the callee method i.e. checkVersionChange()
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYHnCF97gk9MQvgYQx:-NbYHnCG8FGBRRWgSJM8:bly4nbf) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L177)):*
> ```Java
>       throw new UnexpectedException(JOB_INTERRUPTED, e);
>     } catch (InterruptedException e) {
>       log.error(JOB_INTERRUPTED, e);
> ```

why are we not throwing this error?
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYI2MT6WKPuLDZp_LJ:-NbYI2MT6WKPuLDZp_LK:biup6gy) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L185)):*
> ```Java
>     String responseString = response.body().toString().trim();
>     JSONObject jsonObject = new JSONObject(responseString);
>     if (serviceName.equals(ModuleType.CF.name())) {
> ```

again a switch case can be used like blow code snippet. By doing so we don't have to return an empty string in the end.



_Code snippet:_
```Java
switch {
case CF:
     // for FF
case default:
     //for all the other modules 
}
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 202 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYI_XhDOQbS1ZP4oO2:-NbYI_XhDOQbS1ZP4oO3:bly4nbf) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L202)):*
> ```Java
>       return versionInfoJsonObject.getString("version");
>     } catch (JSONException je) {
>       log.error("Error while jsonifying response={} for moduleName={}", responseString, serviceName, je);
> ```

why are we not throwing this error?


<!-- Sent from Reviewable.io -->

2023-08-14 18:53 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51541)* status: 1 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/51541#gh-1289842800:-NbotTYs35rft29JJmrc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L98)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

Yes switch case makes more sense and lets throw error in the default case.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYHN1f7Lq2u_X9Bpk-:-NbotVfZ5f2pbPqf8KUl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L115)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

this try catch is redundant as you already have a try catch in the callee method i.e. checkVersionChange()
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYHnCF97gk9MQvgYQx:-NbotdId1Bwrg4ONhXex:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L177)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why are we not throwing this error?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYI2MT6WKPuLDZp_LJ:-NbouMrvEhwlPmxCN5O9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L185)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

again a switch case can be used like blow code snippet. By doing so we don't have to return an empty string in the end.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 202 at r1](https://reviewable.io/reviews/harness/harness-core/51541#-NbYI_XhDOQbS1ZP4oO2:-NbouxVBAAwd3Jpxvf_z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/679bc532fec7a74f7eb2b0644673a0f414dc0603/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L202)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why are we not throwing this error?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-14 18:54 UTC, neelam-harness commented
trigger uts

2023-08-14 20:02 UTC, thomas-grasman approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51541)* status: 1 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-14 22:53 UTC, neelam-harness commented
trigger review

2023-08-14 22:54 UTC, neelam-harness reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51541)* status: 1 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-14 23:29 UTC, merged