fix: [CDS-76193]: adding HelmChartInfo for K8s instance info
harness/harness-core pull request #51572
Opened 2023-08-10 13:10 UTC by TarunUba1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-14 16:20 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public List<K8sPod> getPodDetailsWithLabels(KubernetesConfig kubernetesConfig, String namespace, String releaseName,
Unused function , need to remove

2023-08-14 17:02 UTC, TarunUba1 commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskExecutor.java
> +    // Need to decide if we need to fill the details for HELMCHART from the pod or from the task param itself
remove it

2023-08-14 17:11 UTC, TarunUba1 commented
trigger uts

2023-08-16 05:24 UTC, GoelPratyush99 commented on 260-delegate/src/main/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskExecutor.java
> +    // Need to decide if we need to fill the details for HELMCHART from the pod or from the task param itself
Yes I think it would be better to get the info from the pod

2023-08-16 05:33 UTC, GoelPratyush99 reviewed
Can we add UTs for this code and fix the breaking ones

2023-08-16 05:33 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java
> +import io.harness.delegate.task.k8s.*;
Can we remove the * import

2023-08-16 05:33 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java
> +import io.harness.delegate.task.k8s.*;
Same here

2023-08-16 05:33 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/rolling/K8sRollingRequestHandler.java
> +import io.harness.delegate.task.k8s.*;
Same here

2023-08-16 05:33 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +import static io.harness.helm.HelmConstants.*;
Also here

2023-08-16 05:33 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +import io.harness.delegate.beans.storeconfig.*;
same

2023-08-16 05:33 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +        helmTaskHelperBase.getHelmChartInfoFromChartsYamlFile(Paths.get(manifestFileDir, CHARTS_YAML_KEY).toString());
We can rewrite it as 
`HelmChartInfo helmChartInfo = helmTaskHelperBase.getHelmChartInfoFromChartsYamlFile(Paths.get(manifestFileDir, CHARTS_YAML_KEY).toString());`

2023-08-17 05:40 UTC, abhinavsingh1196 requested changes

2023-08-17 05:40 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/mapper/K8sPodToServiceInstanceInfoMapper.java
> +  public ServerInstanceInfo toServerInstanceInfo(K8sPod k8sPod, HelmChartInfo helmChartInfo) {
nit: these can be private?

2023-08-17 05:40 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/mapper/K8sPodToServiceInstanceInfoMapper.java
> +  public ServerInstanceInfo toServerInstanceInfo(K8sPod k8sPod, HelmChartInfo helmChartInfo) {
I think overloading here is not taking advantage of the builder object in the method. We can just have one method  `toServerInstanceInfo` which does this?

...
if (helmChartInfo != null) {
  k8sServerInstanceInfoBuilder.helmChartInfo(helmChartInfo);
}
return k8sServerInstanceInfoBuilder.build();
...

2023-08-17 05:40 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +      log.error("Incorrect/Unsupported store type.", ExceptionMessageSanitizer.sanitizeException(e));
nit: this message is correct?

2023-08-17 05:40 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public String getRepoUrlForHelmRepoConfig(HelmChartManifestDelegateConfig helmChartManifestDelegateConfig) {
Maybe this method `getRepoUrl` belongs in `HelmChartManifestDelegateConfig` ? 
This could then call a default method in the interface `StoreDelegateConfig` which returns empty string by default, then override it for these http/s3/gcs store types (and another override for Git store?) and return the respective URLs? 
This can eliminate these `if (instanceof)` checks and also the above switch statement

2023-08-17 05:40 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public HelmChartInfo getHelmChartDetails(ManifestDelegateConfig manifestDelegateConfig, String manifestFileDir)
please check if there is another appropriate class for this method, k8staskhelperbase is too big and generic

2023-08-17 07:46 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +      log.error("Incorrect/Unsupported store type.", ExceptionMessageSanitizer.sanitizeException(e));
yes, similar message is there for helm

2023-08-17 07:49 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/dtos/deploymentinfo/K8sDeploymentInfoDTO.java
> +  private HelmChartInfo helmChartInfo;
You should exclude this from EqualsAndHashCode as it's not something that defines deployment, similar to K8sCloudConfigMetadata cloudConfigMetadata

2023-08-17 07:49 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public String getRepoUrlForHelmRepoConfig(HelmChartManifestDelegateConfig helmChartManifestDelegateConfig) {
No the getRepoUrl doesnt exist in HelmChartManifestDelegateConfig but is a part of HttpHelmConnectorDTO. cant reference it directly

2023-08-17 07:51 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public HelmChartInfo getHelmChartDetails(ManifestDelegateConfig manifestDelegateConfig, String manifestFileDir)
one way is to create functions in K8sTaskHelperBase that reference HelmTaskHelperBase

2023-08-17 07:53 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +        case CUSTOM_REMOTE:
Can we put some hard coded values, like: 
"custom://custom-source-path"
and
"harness://harness-source-path"

if these details are available or just custom or harness if not

2023-08-17 08:11 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public String getRepoUrlForHelmRepoConfig(HelmChartManifestDelegateConfig helmChartManifestDelegateConfig) {
synced offline, this new method can be created to simplify the repo URL logic. Also, this same logic is also present in `io.harness.delegate.task.helm.HelmDeployServiceImplNG#getHelmChartDetails`, so it needs to be refactored as well to extract common code

2023-08-17 08:15 UTC, TarunUba1 commented
trigger uts

2023-08-17 08:16 UTC, TarunUba1 commented on 126-instance/src/main/java/io/harness/dtos/deploymentinfo/K8sDeploymentInfoDTO.java
> +  private HelmChartInfo helmChartInfo;
are we sure cause for NativeHelm also we have this

2023-08-17 11:36 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public String getRepoUrlForHelmRepoConfig(HelmChartManifestDelegateConfig helmChartManifestDelegateConfig) {
done

2023-08-17 11:37 UTC, TarunUba1 commented on 126-instance/src/main/java/io/harness/dtos/deploymentinfo/K8sDeploymentInfoDTO.java
> +  private HelmChartInfo helmChartInfo;
done

2023-08-17 11:40 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +        case CUSTOM_REMOTE:
i have customed the path , if only one file path then we print it other wise we just show custom://
Open for inputs

2023-08-17 12:41 UTC, TarunUba1 commented
trigger uts

2023-08-17 14:21 UTC, TarunUba1 commented
trigger uts

2023-08-17 15:14 UTC, abhinavsingh1196 commented on 126-instance/src/test/java/io/harness/mappers/deploymentinfomapper/K8sDeploymentInfoMapperTest.java
> +    // test
nit: redundant comment

2023-08-17 15:16 UTC, abhinavsingh1196 commented on 260-delegate/src/test/java/io/harness/perpetualtask/K8sInstanceSyncPerpetualTaskV2ExecutorTest.java
> +    // test
redundant comment

2023-08-17 15:20 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +    } catch (Exception e) {
I don't think this try catch is needed anymore. do we still expect some exception here? I believe no 🤔

2023-08-17 15:27 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +    } catch (Exception e) {
yeah not required now

2023-08-17 16:21 UTC, abhinavsingh1196 approved these changes

2023-08-17 16:22 UTC, abhinavsingh1196 commented
trigger uts

2023-08-17 17:36 UTC, TarunUba1 commented
trigger ut3

2023-08-21 05:18 UTC, abosii-harness approved these changes

2023-08-21 05:19 UTC, TarunUba1 commented
trigger review

2023-08-21 05:21 UTC, merged