feat: [CDS-72726]: Disable use of Fabric8 to fetch container info for Native Helm NG
harness/harness-core pull request #51607
Opened 2023-08-11 06:15 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-11 07:35 UTC, markoharness reviewed
Please update PR description and testing status

2023-08-11 08:14 UTC, acasian-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyBaseHandler.java
> +          denoteOverallSuccess && k8sApplyHandlerConfig.getCustomWorkloads().isEmpty(), isErrorFrameworkEnabled, true);
what is this boolean flag stands for?

2023-08-11 08:14 UTC, acasian-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +      return getKubectlContainerInfos(commandRequest, workloads, logCallback, timeoutInMillis, false);
i believe the boolean flag stands for `useSteadyStateCheck`? if that's the case we can pass the var itself.

2023-08-11 08:14 UTC, acasian-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +    return getFabric8ContainerInfos(commandRequest, logCallback, timeoutInMillis);
aren't we still fetching container info via fabric8 here: `return getFabric8ContainerInfos(commandRequest, logCallback, timeoutInMillis);` ?

2023-08-16 05:38 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyBaseHandler.java
> +          denoteOverallSuccess && k8sApplyHandlerConfig.getCustomWorkloads().isEmpty(), isErrorFrameworkEnabled, true);
It is to status check all the resources. The difference in using the kubernetes java client and fabric 8 implementation in our code base is that for java client we status check for all the resources whereas for fabric8 code flow we only status check deploymentConfig, deployment, replicaSets, DaemonSets, replicationControllers and statefulSets.

2023-08-16 05:40 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +      return getKubectlContainerInfos(commandRequest, workloads, logCallback, timeoutInMillis, false);
Simplified it

2023-08-16 05:42 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +    return getFabric8ContainerInfos(commandRequest, logCallback, timeoutInMillis);
Yes we will remove this flow once we GA this FF: **CDS_DISABLE_FABRIC8_NG**

2023-08-16 06:01 UTC, GoelPratyush99 commented
trigger uts

2023-08-16 06:33 UTC, GoelPratyush99 commented
trigger uts

2023-08-16 06:39 UTC, GoelPratyush99 commented
trigger uts

2023-08-17 05:18 UTC, abhinavsingh1196 requested changes

2023-08-17 05:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +      if (!statusCheckAllResources) {
This block is just filtering workloads based on this boolean. This function already accepts the list of workloads to do steady state check for, so we can remove the boolean and do the filtering in the caller ?

2023-08-17 05:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +        namespace, executionLogCallback, false, true, statusCheckAllResourcesForHelm);
could we filter out the resourceIds here itself and remove the boolean `statusCheckAllResourcesForHelm`?

2023-08-17 05:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +        namespace, executionLogCallback, false, true, statusCheckAllResourcesForHelm);
Also, please add unit tests

2023-08-17 05:18 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyBaseHandler.java
> +          denoteOverallSuccess && k8sApplyHandlerConfig.getCustomWorkloads().isEmpty(), isErrorFrameworkEnabled, true);
+1 for removing this boolean

2023-08-17 10:49 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +      if (!statusCheckAllResources) {
Done

2023-08-17 10:49 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyBaseHandler.java
> +          denoteOverallSuccess && k8sApplyHandlerConfig.getCustomWorkloads().isEmpty(), isErrorFrameworkEnabled, true);
Done

2023-08-17 10:49 UTC, GoelPratyush99 commented
trigger uts

2023-08-17 11:06 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +        List<KubernetesResource> resources = helmSteadyStateService.readManifestFromHelmRelease(
you dont need to create resources variable. You could directly call

rollbackWorkloads = helmSteadyStateService.readManifestFromHelmRelease(
            HelmCommandDataMapperNG.getHelmCmdDataNG(commandRequest)).stream()....

unless helmSteadyStateService.readManifestFromHelmRelease() can return null and then you need to handle that case

2023-08-17 12:08 UTC, GoelPratyush99 commented
trigger uts

2023-08-20 22:51 UTC, GoelPratyush99 commented
trigger uts

2023-08-20 22:51 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +        List<KubernetesResource> resources = helmSteadyStateService.readManifestFromHelmRelease(
DOne

2023-08-20 22:52 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +        namespace, executionLogCallback, false, true, statusCheckAllResourcesForHelm);
done

2023-08-21 04:57 UTC, GoelPratyush99 commented
trigger uts

2023-08-21 13:19 UTC, GoelPratyush99 commented
trigger uts

2023-08-22 07:38 UTC, TarunUba1 approved these changes

2023-08-22 07:42 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +  @VisibleForTesting
nit: this annotation can be removed?

2023-08-22 08:11 UTC, abosii-harness requested changes

2023-08-30 07:48 UTC, closed without merging