[feat]: [CDS-76134]: Support for consoleLogPollFrequency jenkins build
harness/harness-core pull request #51622
Opened 2023-08-11 09:36 UTC by Abhishek-CDC

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-11 13:31 UTC, Abhishek-CDC commented
trigger uts

2023-08-11 16:26 UTC, shivamnegi94 submitted a review, later dismissed

2023-08-14 07:32 UTC, puthrayaharness requested changes

2023-08-14 07:32 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsBuildStepHelperServiceImpl.java
> +      LogStreamingStepClientFactory logStreamingStepClientFactory, NGSettingsClient ngSettingsClient) {
Remove unwanted change

2023-08-14 07:32 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsBuildStepHelper.java
> +  long getConsoleLogPollingFrequency(ParameterField<String> frequency) {
Please log these to the HarnessUI console, not just to our app logs.

2023-08-14 07:32 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsBuildStepHelper.java
> +    long result = DEFAULT_CONSOLE_LOG_FREQUENCY_SECONDS;
Please avoid so much nesting in code. Consider returning early to make the code less nested & in turn makes the code a lot more readable.

2023-08-14 07:32 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsBuildStepHelper.java
> +    long result = DEFAULT_CONSOLE_LOG_FREQUENCY_SECONDS;
We can get on a call & resolve this.

2023-08-21 09:53 UTC, Abhishek-CDC commented
trigger uts

2023-08-21 10:45 UTC, puthrayaharness approved these changes

2023-08-21 12:13 UTC, shivamnegi94 approved these changes

2023-08-21 12:19 UTC, Abhishek-CDC commented
trigger review

2023-08-21 12:32 UTC, merged