feat: [CDS-74848]: Create and Update flow for Global template
harness/harness-core pull request #51658
Opened 2023-08-14 07:23 UTC by shivamnegi94

## Describe your changes
## Describe your changes
Global Template Market Place is a new feature which introduce templates to be shared across the accounts. Initially Harness only be the contributor to the Market Place.
Design docs: https://harness.atlassian.net/wiki/spaces/CDNG/pages/21420409865/Template+Library+Marketplace+-+Github+Repo
**Implementation:** 

- We will be using the Github trigger to create a template.
- User will create a template and push to the harness repo `harness-template-marketplace`
- Once trigger is activated, we will be making call to template service with git payload
- Template service will parse the files (added, modified or delete) from git commit payload.
- Then template service will get the content of file from git and save to the collection `globalTemplate`.
- UI will be calling list APIs to list all the global template.
- User can import these templates and use it.
Docs for implementation - https://harness.atlassian.net/wiki/spaces/CDNG/pages/21453471893/Global+Template+Library+Marketplace+-+Tech+Spec?focusedCommentId=21453308164

Testing :
TC1: globalTemplate API to read the git commit payload and create th
<img width="889" alt="Screenshot 2023-08-14 at 10 26 54 AM" src="https://github.com/harness/harness-core/assets/58415634/06a79a8d-b350-492c-857f-24b1cd88d8da">
e global template.

TC2: globalTemplate API to list all the templates.

<img width="869" alt="Screenshot 2023-08-14 at 10 26 31 AM" src="https://github.com/harness/harness-core/assets/58415634/358d8740-7dca-4bc8-b3ba-456f17fc6271">

TC3: API to list the template by identifier.
![Uploading Screenshot 2023-08-14 at 10.27.45 AM.png…]()

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/51526)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-14 07:26 UTC, shivamnegi94 commented
trigger uts

2023-08-16 04:59 UTC, shivamnegi94 commented
trigger uts

2023-08-22 11:36 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS0e0YCe5IebVyND_w:-NcS0e0YCe5IebVyND_x:b-qqjdi1) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L250)):*
> ```Java
>   }
> 
>   public ScmGetBatchFilesResponse fetchGlobalTemplateEntitiesFromRemote(
> ```

This should not be here, we can modify the above function itself to support fetching readme. Maybe add one more entity in FetchRemoteEntityRequest.


<!-- Sent from Reviewable.io -->

2023-08-22 11:39 UTC, sahilhindwani-harness commented
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS1WAG65EZcqz9Eb4j:-NcS1WAG65EZcqz9Eb4k:b-mk82kh) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java#L67)):*
> ```Java
>   Criteria makeCriteriaGitAware(
>       String accountId, String orgIdentifier, String projectIdentifier, Class entityClass, Criteria criteria);
>   <B extends GitSyncableEntity, Y extends YamlDTO> Optional<B> findOne(
> ```

We already have a function for findOne, can we use that only?
I see arguments are different but can we check if we can reuse?


<!-- Sent from Reviewable.io -->

2023-08-22 11:39 UTC, sahilhindwani-harness commented
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS1hT62-qFsRhwPxFp:-NcS1hT62-qFsRhwPxFq:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java#L69)):*
> ```Java
>   <B extends GitSyncableEntity, Y extends YamlDTO> Optional<B> findOne(
>       @NotNull Criteria criteria, Class<B> entityClass);
>   <B extends GitSyncableEntity, Y extends YamlDTO> boolean exists(@NotNull Criteria criteria, Class<B> entityClass);
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-08-22 11:44 UTC, sahilhindwani-harness commented
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGGlobalTemplateResource.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS2mKy2gfHSdF0njJ-:-NcS2mKy2gfHSdF0njJ0:b-emx7ep) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/contracts/src/main/java/io/harness/template/resources/NGGlobalTemplateResource.java#L89)):*
> ```Java
>       })
>   ResponseDTO<List<TemplateWrapperResponseDTO>>
>   createAndUpdate(@Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @NotNull @QueryParam(
> ```

Should this be hidden?
As only trigger should be able to update it. 


<!-- Sent from Reviewable.io -->

2023-08-22 11:45 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS2y4qAt6d6LWGI4RJ:-NcS2y4qAt6d6LWGI4RK:b-jczi3l) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L103)):*
> ```Java
> 
>   List<String> getListOfRepos(Criteria criteria);
>   GlobalTemplateEntity save(GlobalTemplateEntity templateToSave, String comments) throws InvalidRequestException;
> ```

Create a new repository for GlobalTemplateEntity.


<!-- Sent from Reviewable.io -->

2023-08-22 11:45 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 579 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS34cFCIPs1B722O6T:-NcS34cFCIPs1B722O6U:bd17hcg) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L579)):*
> ```Java
>     GitAwareContextHelper.initDefaultScmGitMetaData();
>     GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
>     if (gitEntityInfo == null || TemplateUtils.isInlineEntity(gitEntityInfo)) {
> ```

Since globalEntity cannot be inline, can we remove the inline code?


<!-- Sent from Reviewable.io -->

2023-08-22 11:46 UTC, sahilhindwani-harness requested changes
> Reviewed 13 of 16 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51658)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-22 11:47 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS3OI0AUh4s2po2s5Z:-NcS3OI0AUh4s2po2s5_:bo8ur00) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L600)):*
> ```Java
> 
>   @Override
>   public Optional<GlobalTemplateEntity> findGlobalTemplateByIdentifierAndVersionLabelAndDeletedNot(
> ```

Can we please check if these queries are using indexes?


<!-- Sent from Reviewable.io -->

2023-08-22 11:48 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 693 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS3eZT7lL5DJ6gbw7Q:-NcS3eZT7lL5DJ6gbw7R:b6ush3n) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L693)):*
> ```Java
>   }
> 
>   public Optional<GlobalTemplateEntity> getGlobalTemplateWithVersionLabel(
> ```

Create a new service for globalTemplate that will do this.


<!-- Sent from Reviewable.io -->

2023-08-22 11:48 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 693 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS3eZT7lL5DJ6gbw7Q:-NcS3ixZ3SgsB0Iox3Nf:b-eleo9g) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L693)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Create a new service for globalTemplate that will do this.
</blockquote></details>

Same for every method being used by global template.


<!-- Sent from Reviewable.io -->

2023-08-24 07:29 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51658)* status: 21 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 250 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS0e0YCe5IebVyND_w:-NcaRP2mAIV4I0d_MtSc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L250)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This should not be here, we can modify the above function itself to support fetching readme. Maybe add one more entity in FetchRemoteEntityRequest.
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS1WAG65EZcqz9Eb4j:-NcaRRDe1qibBTyVF4oK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java#L67)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We already have a function for findOne, can we use that only?
I see arguments are different but can we check if we can reuse?
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS1hT62-qFsRhwPxFp:-NcaRRpk7mq9V484qScy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistence.java#L69)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGGlobalTemplateResource.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS2mKy2gfHSdF0njJ-:-NcaRSQF7wIMMEz3GGee:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/contracts/src/main/java/io/harness/template/resources/NGGlobalTemplateResource.java#L89)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should this be hidden?
As only trigger should be able to update it.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS2y4qAt6d6LWGI4RJ:-NcaRTlz0UhZja5GkOD8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L103)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Create a new repository for GlobalTemplateEntity.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 579 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS34cFCIPs1B722O6T:-NcaRXrA8_-4FBQHMzy0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L579)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Since globalEntity cannot be inline, can we remove the inline code?
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS3OI0AUh4s2po2s5Z:-NcaRYdf5cPt_PvmFyON:b-9j9ufe) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L600)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we please check if these queries are using indexes?
</blockquote></details>

This query is not using indexes
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 693 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS3eZT7lL5DJ6gbw7Q:-NcaRbvG7RKekL9UUR1_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L693)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same for every method being used by global template.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-24 11:03 UTC, shivamnegi94 commented
trigger uts

2023-08-24 11:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=51658) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=51658) before we can accept your contribution.<br/>**36** out of **39** committers have signed the CLA.<br/><br/>:white_check_mark: hingerabhinav<br/>:white_check_mark: vigneswara-propelo<br/>:white_check_mark: nishantsaini20<br/>:white_check_mark: sahilhindwani-harness<br/>:white_check_mark: ShobhitSingh11<br/>:white_check_mark: abhinavsingh1196<br/>:white_check_mark: Y0709<br/>:white_check_mark: shash-harness<br/>:white_check_mark: hextechpal<br/>:white_check_mark: GoelPratyush99<br/>:white_check_mark: sahibaCCM<br/>:white_check_mark: acasian-harness<br/>:white_check_mark: vcalasansh<br/>:white_check_mark: arya-harness<br/>:white_check_mark: smjt-h<br/>:white_check_mark: anilchowdhury-harness<br/>:white_check_mark: karansaraswat19<br/>:white_check_mark: atmollo-harness<br/>:white_check_mark: archit-harness<br/>:white_check_mark: VikasMaddukuriHarness<br/>:white_check_mark: bharatgoelharness<br/>:white_check_mark: arvind-choudhary-h<br/>:white_check_mark: shivamnegi94<br/>:white_check_mark: williamwissemann<br/>:white_check_mark: lasdox<br/>:white_check_mark: Abhishek-CDC<br/>:white_check_mark: iamanmolm<br/>:white_check_mark: reetika04<br/>:white_check_mark: tiwaritejas<br/>:white_check_mark: abhinavsingh-ccm<br/>:white_check_mark: shalini-agr<br/>:white_check_mark: tchaurasiya<br/>:white_check_mark: devkimittal<br/>:white_check_mark: harshjain12<br/>:white_check_mark: prashantsharma04<br/>:white_check_mark: puthrayaharness<br/>:x: devesh-harness<br/>:x: RajBaviskar<br/>:x: nikunj-badjatya<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=51658) it.</sub>

2023-08-25 03:53 UTC, shivamnegi94 commented
trigger uts

2023-08-25 04:14 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcetYnU750u16GKAvwF:-NcetYnU750u16GKAvwG:blo3c4s) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L98)):*
> ```Java
>       boolean notDeleted, boolean getMetadataOnly, boolean loadFromCache, boolean loadFromFallbackBranch) {
>     Criteria criteria =
>         buildCriteriaForFindByAccountIdAndOrgIdentifierAndProjectIdentifierAndIdentifierAndVersionLabelAndDeletedNot(
> ```

Can we create one function that takes all the arguments and based on argument being not null, create the criteria?


<!-- Sent from Reviewable.io -->

2023-08-25 04:15 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 175 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcetoeB8SiM7wmK_1ea:-NcetoeB8SiM7wmK_1eb:be6i8wi) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L175)):*
> ```Java
>   public boolean globalTemplateExistByIdentifierAndVersionLabel(String templateIdentifier, String versionLabel) {
>     Optional<GlobalTemplateEntity> template =
>         getGlobalTemplateEntity(Criteria.where(GlobalTemplateEntityKeys.identifier)
> ```

Since we are just checking if template is present, can we use projections over here to fetch only uuid of template if it exists? This will ensure less data transfer from mongo.


<!-- Sent from Reviewable.io -->

2023-08-25 04:18 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 226 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-Nceu0ZM1-ND5Cy4ahm_:-Nceu0ZM1-ND5Cy4ahma:bvl46lv) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L226)):*
> ```Java
>       Criteria criteria, boolean getMetadataOnly, Pageable pageable) {
>     Query query = new Query(criteria).with(pageable);
>     List<GlobalTemplateEntity> templateEntities = mongoTemplate.find(query, GlobalTemplateEntity.class);
> ```

I think this is not used anywhere, can we remove this function. We can add if required?


<!-- Sent from Reviewable.io -->

2023-08-25 04:19 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS3OI0AUh4s2po2s5Z:-NceulHc17-0rTAahnLs:b-bmbd91) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L600)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

This query is not using indexes
</blockquote></details>

Can we add relevant index on the collection ? Any query which can be used again and again should have proper index.


<!-- Sent from Reviewable.io -->

2023-08-25 04:21 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcevCjL6fRT0soYWcK3:-NcevCjN-EIsITIVx6xQ:bj98r7j) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java#L57)):*
> ```Java
> 
>   private final TelemetryReporter telemetryReporter;
>   private final ExecutorService executorService;
> ```

nit: Remove unused variables.



_Code quote:_
```Java
  private final FilterService filterService;
  private final NGGlobalTemplateRepository ngGlobalTemplateRepository;
  private GitSyncSdkService gitSyncSdkService;
  private TemplateGitXService templateGitXService;

  private final GitAwareEntityHelper gitAwareEntityHelper;

  private final TelemetryReporter telemetryReporter;
  private final ExecutorService executorService;
```


<!-- Sent from Reviewable.io -->

2023-08-25 04:22 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java` line 50 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcevIye8bxkgm7funVZ:-NcevIye8bxkgm7funV_:b-4et35j) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java#L50)):*
> ```Java
> public class NGGlobalTemplateServiceHelper {
>   private final FilterService filterService;
>   private final NGGlobalTemplateRepository ngGlobalTemplateRepository;
> ```

NGGlobalTemplateRepository should be a part of NgGlobalTemplateService, we should not have it in helper. 


<!-- Sent from Reviewable.io -->

2023-08-25 04:23 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcevhqbE3MVdfxhZwgD:-NcevhqbE3MVdfxhZwgE:b-y288s) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java#L48)):*
> ```Java
> @Slf4j
> @OwnedBy(CDC)
> public class NGGlobalTemplateServiceHelper {
> ```

nit: remove unused methods.


<!-- Sent from Reviewable.io -->

2023-08-25 04:25 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java` line 159 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-Ncew-XU6ZQu9LmhBMu8:-Ncew-XU6ZQu9LmhBMu9:b9qzbao) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java#L159)):*
> ```Java
>   }
> 
>   public List<TemplateWrapperResponseDTO> updateGlobalTemplate(String accountId, String orgId, String projectId,
> ```

nit: should be private or package protected. 


<!-- Sent from Reviewable.io -->

2023-08-28 04:50 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51658)* status: 1077 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto,del-team. 

___
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcetYnU750u16GKAvwF:-NcuGbFm-nEzwFDJHvy0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L98)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we create one function that takes all the arguments and based on argument being not null, create the criteria?
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 175 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcetoeB8SiM7wmK_1ea:-NcuTTgC0jidHTNF16GT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L175)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Since we are just checking if template is present, can we use projections over here to fetch only uuid of template if it exists? This will ensure less data transfer from mongo.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 226 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-Nceu0ZM1-ND5Cy4ahm_:-NcuTV3dEUbOpPifG9nO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L226)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think this is not used anywhere, can we remove this function. We can add if required?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-28 08:16 UTC, shivamnegi94 commented
trigger uts

2023-08-28 16:04 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +      filePaths.addAll(fetchReadMeFilePath(filePaths));
ReadMe would be provided by the user. We would not need to add this.
Discussed offline.

2023-08-29 04:48 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 91 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-NczbWS1BY_ZviIUVYUj:-NczbWS1BY_ZviIUVYUk:b-xi2kmg) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L91)):*
> ```Java
>   @Override
>   public Optional<GlobalTemplateEntity>
>   findByAccountIdAndOrgIdentifierAndProjectIdentifierAndIdentifierAndVersionLabelAndDeletedNotForGlobalTemplate(
> ```

This name seems to be too long, can we rename it to getGlobalEntityUsingVersionLabel?


<!-- Sent from Reviewable.io -->

2023-08-29 04:49 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 91 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-NczbWS1BY_ZviIUVYUj:-Nczbq9sD-BJRg8qE2w1:b-mwp14d) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L91)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This name seems to be too long, can we rename it to getGlobalEntityUsingVersionLabel?
</blockquote></details>

Also, should we just keep one function in custom impl which contains the criteria and the service layer should create the criteria based on use-case?
Else the number of variables are too much in this function


<!-- Sent from Reviewable.io -->

2023-08-29 04:50 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 123 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-Nczc4Nk2dFQEOQjkqO4:-Nczc4NlA3BhXHE9Csgz:bxgqb4k) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L123)):*
> ```Java
>   }
> 
>   private Optional<GlobalTemplateEntity> getGlobalTemplateEntity(Criteria criteria, boolean getMetadataOnly) {
> ```

nit: It can be just get


<!-- Sent from Reviewable.io -->

2023-08-29 04:50 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 129 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-Nczc8-83TBkCU0ryYN1:-Nczc8-83TBkCU0ryYN2:b7dyljp) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L129)):*
> ```Java
>       return Optional.empty();
>     }
>     if (getMetadataOnly) {
> ```

This if condition seems to be redundant. 


<!-- Sent from Reviewable.io -->

2023-08-29 04:51 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 156 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-NczcDn7BwENvs_imJjH:-NczcDn7BwENvs_imJjI:b-ofi9kj) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L156)):*
> ```Java
>   public Page<GlobalTemplateEntity> findAll(String accountIdentifier, Criteria criteria, Pageable pageable) {
>     Query query = new Query(criteria).with(pageable);
>     List<GlobalTemplateEntity> globalTemplateEntities = mongoTemplate.find(query, GlobalTemplateEntity.class);
> ```

We should not use list query here. Could you please add a todo under your name and create a ticket for the same?


<!-- Sent from Reviewable.io -->

2023-08-29 04:53 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java` line 37 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-Nczci4qDPSXQws5myuJ:-Nczci4qDPSXQws5myuK:bnqjfoj) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java#L37)):*
> ```Java
>   public static String MODULE_NAME = "moduleName";
> 
>   public Criteria formCriteria(Criteria criteria, TemplateListType templateListType) {
> ```

nit: Is this required here. Can we move it to service layer? We can remove this function altogether then.


<!-- Sent from Reviewable.io -->

2023-08-29 04:55 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java` line 108 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-NczdByl6EJjBl_y1ChO:-NczdByl6EJjBl_y1ChP:b6s0vu6) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java#L108)):*
> ```Java
> @Slf4j
> @OwnedBy(CDC)
> public class NGGlobalTemplateServiceImpl implements NGGlobalTemplateService {
> ```

Could you please add comments  in reviewable or github as to what each method is doing, just for understanding easily?


<!-- Sent from Reviewable.io -->

2023-08-29 04:55 UTC, sahilhindwani-harness requested changes
> Reviewed 2 of 3 files at r3, 12 of 17 files at r4, 1051 of 1055 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51658)* status: 1077 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-08-29 08:15 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51658)* status: 1077 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto,del-team. 

___
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 91 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-NczbWS1BY_ZviIUVYUj:-Nd-7QSj1WI6uMjFEi5X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L91)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Also, should we just keep one function in custom impl which contains the criteria and the service layer should create the criteria based on use-case?
Else the number of variables are too much in this function
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 129 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-Nczc8-83TBkCU0ryYN1:-Nd-8R0L24RuXwfJK7TD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L129)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This if condition seems to be redundant.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java` line 156 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-NczcDn7BwENvs_imJjH:-Nd-9N5t3ypo-IrRsqjf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java#L156)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We should not use list query here. Could you please add a todo under your name and create a ticket for the same?
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/51658#-NcS3OI0AUh4s2po2s5Z:-Nd-5SqP9XI7_6dQF9kD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/525757d9c0b8711dd5c2c7719d7e4bf0d6509668/template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L600)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add relevant index on the collection ? Any query which can be used again and again should have proper index.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java` line 50 at r4](https://reviewable.io/reviews/harness/harness-core/51658#-NcevIye8bxkgm7funVZ:-Nd-5WGK74Kv0NxEPQcB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3702203ccc5d5df1b77307bc144a712e18aecd80/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceHelper.java#L50)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

NGGlobalTemplateRepository should be a part of NgGlobalTemplateService, we should not have it in helper.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java` line 108 at r9](https://reviewable.io/reviews/harness/harness-core/51658#-NczdByl6EJjBl_y1ChO:-Nd-G0tHE4oDkR4o0x9a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java#L108)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Could you please add comments  in reviewable or github as to what each method is doing, just for understanding easily?
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java` line 385 at r9](https://reviewable.io/reviews/harness/harness-core/51658#gh-1307620108:-Nd-G1YWBCu0rwIXV2yw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/df59ae1e86051c06aaf0811de2889483f66b10fa/template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java#L385)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

ReadMe would be provided by the user. We would not need to add this.
Discussed offline.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-30 01:07 UTC, sribalij reviewed
Added few comments

2023-08-30 01:07 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    TemplateUtils.setupGitParentEntityDetails(templateEntity.getAccountIdentifier(), templateEntity.getOrgIdentifier(),
Any reason we need this?

2023-08-30 05:15 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +      filePaths = fetchFilesDetails(webhookEvent, FILE_MODIFIED);
@sribalij Currently we are not supporting deletion of template Yaml file or ReadMe file, we are only supporting ADD and Modified.
Let say we have same file added or modified multiple commits, we are reading file from each commit and updating the db. It will make sure the template Yaml will always be the updated one.

2023-08-30 06:21 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    TemplateUtils.setupGitParentEntityDetails(templateEntity.getAccountIdentifier(), templateEntity.getOrgIdentifier(),
Just to check if the template is supported, i will remove the validation

2023-08-30 06:23 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    try {
Not sure how much effort needed to make these changes. can we take that as enhancement ?

2023-08-30 11:03 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +      filePaths = fetchFilesDetails(webhookEvent, FILE_MODIFIED);
Right now adding and updating ReadMe individually without template yaml is not supported.

2023-09-01 06:27 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +  public List<TemplateWrapperResponseDTO> createUpdateGlobalTemplate(String accountId, String orgId, String projectId,
Can we try to resuse from TemplateEntity

2023-09-01 06:33 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    try {
Created task for the changes - https://harness.atlassian.net/browse/CDS-78534

2023-09-04 06:24 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +  public List<TemplateWrapperResponseDTO> createUpdateGlobalTemplate(String accountId, String orgId, String projectId,
We tried using TemplateEntity but global entity will use seperate db collection and few of the fields in TemplateEntity are final which is causing issue in extending the class

2023-09-06 13:19 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 2 of 5 files at r10, 2 of 8 files at r11, 3 of 3 files at r12, 7 of 8 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51658)* status: 1078 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-09-08 03:54 UTC, shivamnegi94 commented
trigger uts

2023-09-08 23:16 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    try {
Yes, we are solving a similar problem in GitX. SCM has some libraries that we can use by giving the initial and final commit. That gives the files changed. It is generic and can be used for all SCM.

2023-09-08 23:38 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/resources/NGGlobalTemplateResourceImpl.java
> +      String projectIdentifier, String connectorRef, String targetBranch, GitEntityCreateInfoDTO gitEntityCreateInfo,
We don't seem to be using this GitEntityCreateInfoDTO. Do we need it?

2023-09-10 23:14 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    HashMap<String, Object> map = (HashMap<String, Object>) webhookEvent.get(HEAD_COMMITS);
Need to take care of this when we fix for other SCMs

2023-09-10 23:24 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +      if (validateFileIsYamlType(filePath)) {
What happens if it has README.md in the change? Are we omitting it?

2023-09-10 23:37 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/resources/NGGlobalTemplateResourceImpl.java
> +      String projectIdentifier, String connectorRef, String targetBranch, GitEntityCreateInfoDTO gitEntityCreateInfo,
targetBranch too?

2023-09-11 04:36 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    HashMap<String, Object> map = (HashMap<String, Object>) webhookEvent.get(HEAD_COMMITS);
Yes already raised a ticket for it

2023-09-11 04:46 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +      if (validateFileIsYamlType(filePath)) {
We are not omitting it, i am handling it in next if condition, because in Update scenario customer can update either template yaml or ReadMe file or both of them so to handle the scenario I am reading ReadMe and template yaml separate

2023-09-11 04:47 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    HashMap<String, Object> map = (HashMap<String, Object>) webhookEvent.get(HEAD_COMMITS);
https://harness.atlassian.net/browse/CDS-78534

2023-09-11 04:48 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +    HashMap<String, Object> map = (HashMap<String, Object>) webhookEvent.get(HEAD_COMMITS);
https://harness.atlassian.net/browse/CDS-78534

2023-09-13 00:47 UTC, sribalij commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +      if (validateFileIsYamlType(filePath)) {
What about during a create call? If it is added the first time and ReadMe is in the Added list?

2023-09-13 04:17 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/services/NGGlobalTemplateServiceImpl.java
> +      if (validateFileIsYamlType(filePath)) {
In case of create call, readMe is already added to globalTemplateEntity with template Yaml.
`io.harness.template.services.NGGlobalTemplateServiceImpl#processScmGetBatchFilesWithReadMe` Here i am adding Readme and template yaml to globalTemplateEntity, line no. 441

2023-09-13 07:14 UTC, sribalij approved these changes

2023-09-13 07:15 UTC, shivamnegi94 commented
trigger uts

2023-09-13 08:49 UTC, shivamnegi94 commented
trigger ut0, ut1, ut2, ut5, ut9

2023-09-13 09:25 UTC, shivamnegi94 commented
trigger ut1

2023-09-13 09:26 UTC, shivamnegi94 commented
trigger ut2

2023-09-13 09:26 UTC, shivamnegi94 commented
trigger ut9

2023-09-13 11:02 UTC, shivamnegi94 commented
trigger ut1, ut2

2023-09-14 04:48 UTC, utkarshchoubey-harness approved these changes

2023-09-14 04:49 UTC, shivamnegi94 commented
trigger review

2023-09-15 16:19 UTC, shivamnegi94 commented
@sahilhindwani-harness can you please resolve your comments and approve the PR again?

2023-09-20 10:24 UTC, sahilhindwani-harness approved these changes

2023-09-20 15:38 UTC, shivamnegi94 commented
@archit-harness can you please approve the PR, code owner review is required to merge the changes

2023-09-20 16:37 UTC, archit-harness commented on template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustom.java
> +public interface NGGlobalTemplateRepositoryCustom {
Add line breaks between methods

2023-09-20 16:39 UTC, archit-harness commented on template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java
> +  private OutboxEvent generateUpdateOutboxEvent(GlobalTemplateEntity templateToUpdate,
add ticket to move reads to secondary mongo

2023-09-21 03:21 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java
> +  public GlobalTemplateEntity toGlobalTemplateEntity(
I will address the issue in next PR

2023-09-21 03:23 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/repositories/NGGlobalTemplateRepositoryCustomImpl.java
> +  private OutboxEvent generateUpdateOutboxEvent(GlobalTemplateEntity templateToUpdate,
https://harness.atlassian.net/browse/CDS-79773

2023-09-21 03:26 UTC, shivamnegi94 commented on template-service/service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java
> +  public GlobalTemplateEntity toGlobalTemplateEntity(
I will create separate mapper in subsequent PR for global template

2023-09-21 03:52 UTC, archit-harness approved these changes

2023-09-21 04:03 UTC, merged