fix: [CDS-76768]: Changes for not overriding plan node by identity node
harness/harness-core pull request #51652
Opened 2023-08-13 15:35 UTC by Y0709

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-13 15:41 UTC, Y0709 commented
trigger messagecheck, uts

2023-08-13 17:04 UTC, Y0709 commented
trigger uts

2023-08-14 06:01 UTC, Y0709 commented on pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java
> +  String nodeId;
We have added this nodeId as earlier we were querying only on uuid and we were updating the planId for that uuid while converting the plan node to identity node. Now we will not update the planId of existing record instead a new node will be created for identity node with different with a unique uuid as uuid is the primary key so it cant be same for both plan node and identity node

2023-08-14 07:12 UTC, archit-harness requested changes
> Reviewed 14 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrRrGBpRgN9n21IBG:-NbmrRrGBpRgN9n21IBH:b-1hbe1y) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java#L26)):*
> ```Java
> 
>   <T extends Node> T fetchNode(String planId, String nodeId);
>   <T extends Node> T fetchNode(String nodeId);
> ```

remove this method as it wouldnt be used
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrnJm1bbnqqKPuWZm:-NbmrnJm1bbnqqKPuWZn:b-fugwzz) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java#L28)):*
> ```Java
>   <T extends Node> T fetchNode(String nodeId);
> 
>   <T extends Node> Set<T> fetchAllNodes(String planId, Set<String> nodeIds);
> ```

always mention which index methods are using so its easier to know devs understand about it, example read NodeExecutionService comments
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrV4b-_qWGXGyA5Ok:-NbmrV4b-_qWGXGyA5Ol:bogyz5k) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L98)):*
> ```Java
>    *   nodeId=null
>    *
>    *
> ```

remove from here, and add to pr description
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrYdF6p7N1CYGQgxT:-NbmrYdF6p7N1CYGQgxU:b-fgy3zq) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L120)):*
> ```Java
>       return nodeEntity.get().getNode();
>     }
>     // This is a fallback mechanism added.
> ```

add how this is fallback for running execution
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrahK7xi_dy-iNdfZ:-NbmrahK7xi_dy-iNdf_:biyy7o6) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L146)):*
> ```Java
>     }
>     Failsafe.with(DEFAULT_RETRY_POLICY).get(() -> {
>       nodeEntityRepository.deleteAllByNodeIdIn(nodeEntityIds);
> ```

we should delete on Uuuid in as well as with planId and nodeEntityId
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrfDO8Iimvmkhx5lt:-NbmrfDO8Iimvmkhx5lu:bfz344o) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L215)):*
> ```Java
> 
>     if (isEmpty(nodes)) {
>       // This is a fallback mechanism
> ```

same as above, add comment
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms2YS9jhvT8PsEiPg:-Nbms2YS9jhvT8PsEiPh:b-e7lfj2) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java#L31)):*
> ```Java
>   Optional<NodeEntity> findByPlanIdAndNodeId(String planId, String nodeId);
> 
>   Optional<NodeEntity> deleteAllByNodeIdIn(Set<String> ids);
> ```

it should be planId and nodeId
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms1aZ2FggvLa5tEKl:-Nbms1aZ2FggvLa5tEKm:b-p1r1zc) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java#L33)):*
> ```Java
>   Optional<NodeEntity> deleteAllByNodeIdIn(Set<String> ids);
> 
>   List<NodeEntity> findNodeEntityByNodeId(Set<String> ids);
> ```

where is this used?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms4zN8WOTZFwIyHtk:-Nbms4zN8WOTZFwIyHtl:bdtek4r) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java#L21)):*
> ```Java
>   private final MongoTemplate secondaryMongoTemplate;
> 
>   public NodeEntityRepositoryCustomImpl(MongoTemplate secondaryMongoTemplate) {
> ```

SecondaryMongoTemplateHolder
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms7XOAPn_DsiOTt-L:-Nbms7XOAPn_DsiOTt-M:bz4mrfv) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java#L27)):*
> ```Java
>   @Override
>   public List<NodeEntity> findByPlanIdAndNodeIds(String planId, Set<String> nodeIds) {
>     Query query = new Query(Criteria.where(NodeEntityKeys.planId).is(planId).and(NodeEntityKeys.nodeId).in(nodeIds));
> ```

mention as comment which index its using it, also move the criteria in serviceImpl layer only, thus RepoCustom can only take query with projection, check NodeExecutionReadHelper / PlanExecutionRepositoryCustomImpl
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmsTSn0vDBwXXQETrH:-NbmsTSn0vDBwXXQETrI:b4e4dic) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java#L43)):*
> ```Java
> public class NodeEntity implements PersistentEntity, UuidAccess {
>   public static List<MongoIndex> mongoIndexes() {
>     return ImmutableList
> ```

move indexes to original place and not at start of entity
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmnYKr0My26AlSAyEc:-NbmnYKr0My26AlSAyEd:b-pi9d9n) ([raw file](https://github.com/harness/harness-core/blob/c35770003843c702c4f089c20563d8627695a990/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java#L65)):*
> ```Java
>    * or planId, nodeId = argument
>    *
>    */
> ```

remove this
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/i [...]

2023-08-17 09:08 UTC, Y0709 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: 26 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrRrGBpRgN9n21IBG:-Nc1jK7H9aGasAivlHR9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove this method as it wouldnt be used
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrnJm1bbnqqKPuWZm:-Nc1jNrA5UP_GL1mbxoP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanService.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

always mention which index methods are using so its easier to know devs understand about it, example read NodeExecutionService comments
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrV4b-_qWGXGyA5Ok:-Nc1jOrJ69B62-cpKDLm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L98)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove from here, and add to pr description
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrYdF6p7N1CYGQgxT:-Nc1jPMeENvC7k7t373x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L120)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add how this is fallback for running execution
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrahK7xi_dy-iNdfZ:-Nc1jQcHDzzNGQgWN3WL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L146)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should delete on Uuuid in as well as with planId and nodeEntityId
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmrfDO8Iimvmkhx5lt:-Nc1jxmrCWb33YhHUN4j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L215)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above, add comment
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms2YS9jhvT8PsEiPg:-Nc1k9SXDTwCWF5_EthA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be planId and nodeId
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms1aZ2FggvLa5tEKl:-Nc1kB9A1Uk9Xq7595ZW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepository.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where is this used?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms4zN8WOTZFwIyHtk:-Nc1kCWO1sGB8lFHi89p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

SecondaryMongoTemplateHolder
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-Nbms7XOAPn_DsiOTt-L:-Nc1kD_c0pNu7s5UQaFu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/NodeEntityRepositoryCustomImpl.java#L27)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

mention as comment which index its using it, also move the criteria in serviceImpl layer only, thus RepoCustom can only take query with projection, check NodeExecutionReadHelper / PlanExecutionRepositoryCustomImpl
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmsTSn0vDBwXXQETrH:-Nc1kEVDDK3lyOQg3g44:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

move indexes to original place and not at start of entity
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/51652#-NbmnYKr0My26AlSAyEc:-Nc1kF-L17ZB3vFqKrxJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72751e1f187147ee4d2f1921947ba89d294212cf/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/NodeEntity.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils/NodeProjectionUtils.java` line 109 at r2](https://reviewable.io/reviews/harn [...]

2023-08-17 09:10 UTC, Y0709 commented
trigger uts

2023-08-21 06:02 UTC, Y0709 commented
trigger uts

2023-08-22 03:46 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 994 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQLNON37pYdaB9J66l:-NcQLNON37pYdaB9J66m:b214nkg) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L994)):*
> ```Java
> 
>     Set<String> nodeIds = nodeExecutionMap.values().stream().map(NodeExecution::getNodeId).collect(Collectors.toSet());
>     String planId = !isEmpty(nodeExecutions) ? nodeExecutions.get(0).getPlanId() : null;
> ```

nit: Add a comment tha the planId of all the nodeExecutions will be same, that is the assumption till now. 


<!-- Sent from Reviewable.io -->

2023-08-22 03:48 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 166 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQLpR59aDKZ3uxMbpX:-NcQLpR59aDKZ3uxMbpY:b-xvg37u) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L166)):*
> ```Java
>                          .build());
>         identityNodesToBeCreated.add(node);
>       } else if (nodeExecution.getNodeType() == NodeType.IDENTITY_PLAN_NODE) {
> ```

Let's add a comment why are we doing this.


<!-- Sent from Reviewable.io -->

2023-08-22 06:32 UTC, archit-harness requested changes
> Reviewed 2 of 21 files at r1, 11 of 13 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: 27 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 994 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQLNON37pYdaB9J66l:-NcQqtTV6tq8p7r201n-:b32v57) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L994)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Add a comment tha the planId of all the nodeExecutions will be same, that is the assumption till now.
</blockquote></details>

+1
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 185 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQvE_h3g7hFaXf2B8o:-NcQvE_h3g7hFaXf2B8p:b9aqnei) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L185)):*
> ```Java
> 
>   @Override
>   public <T extends Node> Set<T> fetchAllNodes(String planId, Set<String> nodeIds) {
> ```

we should make this paginated @sahilhindwani-harness 
Plus @sahilhindwani-harness can you add ticket that we will need to check how to improve - transformPlan as for bigger pipelines we are getting all nodes in memory
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 166 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQLpR59aDKZ3uxMbpX:-NcQve5H8H4sYIyc9Jr1:b-pfypju) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L166)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Let's add a comment why are we doing this.
</blockquote></details>

+1 @sahilhindwani-harness didnt we decide this flow we will check back whether its really needed and not a bug in some other flow as we are checking checkIfNodeAlreadyPresent
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 197 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQvoyR6_57tbx4DPNc:-NcQvoyR6_57tbx4DPNd:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L197)):*
> ```Java
>       return ChildExecutableResponse.newBuilder().setChildNodeId(identityPlanNode.getUuid()).build();
>     } else if (node.getNodeType() == NodeType.IDENTITY_PLAN_NODE) {
>       if (!checkIfNodeAlreadyPresentForPlanId(planId, node.getUuid())) {
> ```

same as above
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 442 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQwHK6Eo490XRkB6ti:-NcQwHK6Eo490XRkB6tj:byfsnxk) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L442)):*
> ```Java
>         nodeIdToPlanNodes.put(node.getUuid(), node);
>       }
>     }
> ```

can we think to improve as we are keeping 2 maps of all nodes at a time


<!-- Sent from Reviewable.io -->

2023-08-22 12:43 UTC, Y0709 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: 27 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 185 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQvE_h3g7hFaXf2B8o:-NcSF7zLD-o6bw26vH4H:bckspzc) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L185)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should make this paginated @sahilhindwani-harness 
Plus @sahilhindwani-harness can you add ticket that we will need to check how to improve - transformPlan as for bigger pipelines we are getting all nodes in memory
</blockquote></details>

@sahilhindwani-harness will create tickets for them , we are not doing that in this pr as it was not done earlier as well
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 166 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQLpR59aDKZ3uxMbpX:-NcSFHL3C1vsq28nUSmU:bjjf2bu) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L166)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1 @sahilhindwani-harness didnt we decide this flow we will check back whether its really needed and not a bug in some other flow as we are checking checkIfNodeAlreadyPresent
</blockquote></details>

This is not a bug . A few identity nodes are created earlier hence this is a required change to avoid duplicate creation
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 442 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQwHK6Eo490XRkB6ti:-NcSG4R6Akf2R0ufG4YR:bp5rnd0) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L442)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we think to improve as we are keeping 2 maps of all nodes at a time
</blockquote></details>

Can you point out which 2 maps , i think nodeIdToPlanNodes is the only map that is being maintained


<!-- Sent from Reviewable.io -->

2023-08-24 14:05 UTC, Y0709 commented
trigger uts

2023-08-24 14:53 UTC, sahilhindwani-harness approved these changes

2023-08-24 14:54 UTC, sahilhindwani-harness submitted a review, later dismissed

2023-08-24 14:56 UTC, sahilhindwani-harness commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java
> +      for (String id : nodeIds) {
You can use set difference for fetching the node ids not present in the above set

2023-08-25 08:50 UTC, Y0709 commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java
> +      for (String id : nodeIds) {
done

2023-08-25 08:50 UTC, Y0709 commented
trigger uts

2023-08-25 09:55 UTC, sahilhindwani-harness approved these changes
> Reviewed 9 of 21 files at r1, 10 of 13 files at r3, 2 of 3 files at r4, 6 of 6 files at r6, 12 of 14 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-25 10:05 UTC, archit-harness requested changes
> Reviewed 1 of 13 files at r3, 1 of 6 files at r6, 11 of 14 files at r7, 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 195 at r8](https://reviewable.io/reviews/harness/harness-core/51652#-Ncg6bo76rkGelb8RPmq:-Ncg6bo76rkGelb8RPmr:b-zgzaft) ([raw file](https://github.com/harness/harness-core/blob/59062a67dbe648fe54081f96bd31ecfb3d7432ce/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L195)):*
> ```Java
>     }
> 
>     if (nodeIdsFound.size() < nodeIds.size()) {
> ```

before if condition, do diff then if condition can be on remaining ids not empty
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 202 at r8](https://reviewable.io/reviews/harness/harness-core/51652#-Ncg6YNQ06OSscRLl89-:-Ncg6YNQ06OSscRLl890:bmudwt9) ([raw file](https://github.com/harness/harness-core/blob/59062a67dbe648fe54081f96bd31ecfb3d7432ce/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L202)):*
> ```Java
>       log.info("Unable to find some nodes from node Id and planId . Most likely this was an older running execution");
>       Set<String> remainingNodeIds = Sets.difference(nodeIds, nodeIdsFound);
>       nodesEntities = nodeEntityRepository.findAllById(remainingNodeIds);
> ```

can you check if not empty then only only db else do not.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 197 at r4](https://reviewable.io/reviews/harness/harness-core/51652#-NcQvoyR6_57tbx4DPNc:-Ncg6lyX6Ci-wyTV9PQ1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e539550351df4bfae85360420403236b44df06fb/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-08-25 11:31 UTC, Y0709 commented
trigger uts

2023-08-25 11:41 UTC, archit-harness approved these changes
> Reviewed 1 of 14 files at r7, 1 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 195 at r8](https://reviewable.io/reviews/harness/harness-core/51652#-Ncg6bo76rkGelb8RPmq:-NcgUncW0O8w0Bp-jMcJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/59062a67dbe648fe54081f96bd31ecfb3d7432ce/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L195)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

before if condition, do diff then if condition can be on remaining ids not empty
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java` line 202 at r8](https://reviewable.io/reviews/harness/harness-core/51652#-Ncg6YNQ06OSscRLl89-:-NcgUoIt506PRSRdcVNo:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/59062a67dbe648fe54081f96bd31ecfb3d7432ce/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanServiceImpl.java#L202)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you check if not empty then only only db else do not.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-08-25 11:42 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51652)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-08-25 11:44 UTC, Y0709 commented
trigger review

2023-08-25 11:51 UTC, merged