feat: [PL-39275]: Send events to segment for account logins
harness/harness-core pull request #51717
Opened 2023-08-16 10:06 UTC by sahibaCCM

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-17 05:30 UTC, Raghav-Murali commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
>        loginApiMetricsService.recordLoginRequestSuccessOAuth(
Can we replace the OAuth calls with updateDefaultLoginMetricsSuccess and Failure as well ?

2023-08-17 05:31 UTC, Raghav-Murali commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
>        loginApiMetricsService.recordLoginRequestFailureOAuth(
Can we just update all this calls with updateDefaultLoginMetrics* ?

2023-08-17 05:32 UTC, Raghav-Murali commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
>    private void updateDefaultLoginMetricsSuccess(String accountId, AuthenticationMechanism authMechanism) {
Since we are now using this from other API endpoints apart from just default login endpoint, we can just rename this as updateLoginMetricsSuccess() and the below function as updateLoginMetricsFailure().

2023-08-17 06:52 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
>        loginApiMetricsService.recordLoginRequestSuccessOAuth(
For Oauth calls we are also sending provider as an additional parameter; that's why I dint replace it with updateDefaultLoginMetricsSuccess.

2023-08-17 06:52 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
>        loginApiMetricsService.recordLoginRequestFailureOAuth(
ACK

2023-08-17 06:53 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
>        loginApiMetricsService.recordLoginRequestFailureOAuth(
same reason as above

2023-08-17 07:01 UTC, sahibaCCM commented
trigger uts

2023-08-21 05:41 UTC, sahibaCCM commented
trigger uts

2023-08-21 18:50 UTC, Raghav-Murali submitted a review, later dismissed
Please test it once locally and see if you can see these metrics and values for them.

2023-08-24 11:27 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51717)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 643 at r3](https://reviewable.io/reviews/harness/harness-core/51717#-NcbHNDQBOUy5kpDfkf4:-NcbHNDRE7fJVDBAmQ-w:bm80643) ([raw file](https://github.com/harness/harness-core/blob/0752ca1abe69d703caa6557220eb1374a241327d/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L643)):*
> ```Java
>       HashMap<String, Object> properties = new HashMap<>();
>       properties.put(AUTHENTICATION_MECHANISM, OAUTH);
>       telemetryReporter.sendTrackEvent(LOGIN_SUCCESSFUL, null, user.getDefaultAccountId(), properties,
> ```

always send identifyEvent() before a trackEvent(), as it will register the user in segment for which we are trying to track an event.
Also, lets not send null, we already have the userID here.
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 657 at r3](https://reviewable.io/reviews/harness/harness-core/51717#-NcbHtUD0RzdogNQooee:-NcbHtUE4SKzBot_Uf2U:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/0752ca1abe69d703caa6557220eb1374a241327d/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L657)):*
> ```Java
>       HashMap<String, Object> properties = new HashMap<>();
>       properties.put(AUTHENTICATION_MECHANISM, OAUTH);
>       telemetryReporter.sendTrackEvent(
> ```

same as above
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 686 at r3](https://reviewable.io/reviews/harness/harness-core/51717#-NcbHyyk-OfkSb7fszxv:-NcbHyyk-OfkSb7fszxw:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/0752ca1abe69d703caa6557220eb1374a241327d/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L686)):*
> ```Java
>     HashMap<String, Object> properties = new HashMap<>();
>     properties.put(AUTHENTICATION_MECHANISM, authMechanism);
>     telemetryReporter.sendTrackEvent(
> ```

same as above
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 708 at r3](https://reviewable.io/reviews/harness/harness-core/51717#-NcbI0d6-0C_3PU8Lw0_:-NcbI0d6-0C_3PU8Lw0a:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/0752ca1abe69d703caa6557220eb1374a241327d/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L708)):*
> ```Java
>     HashMap<String, Object> properties = new HashMap<>();
>     properties.put(AUTHENTICATION_MECHANISM, authMechanism);
>     telemetryReporter.sendTrackEvent(
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-08-25 09:36 UTC, sahibaCCM commented
trigger uts

2023-08-25 10:13 UTC, sahibaCCM commented
trigger uts

2023-08-25 11:09 UTC, sahibaCCM commented
trigger uts

2023-08-25 12:56 UTC, kapil-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51717)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 649 at r5](https://reviewable.io/reviews/harness/harness-core/51717#-Ncgk8sqDRxN25cQ4QL9:-Ncgk8sqDRxN25cQ4QLA:b-dmbucz) ([raw file](https://github.com/harness/harness-core/blob/a67bca66e0e668d03fb84320b40d5dcd87b75a4e/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L649)):*
> ```Java
>       identifyEventProperties.put("accountId", user.getDefaultAccountId());
>       identifyEventProperties.put("accountName", user.getAccountName());
>       telemetryReporter.sendIdentifyEvent(identifyEventProperties.get("email").toString(), identifyEventProperties,
> ```

nit: in the 1st argument a simple user.getEmail() would have been sufficient and neat. Why complicate with identifyEventProperties.get("email").toString() ?


<!-- Sent from Reviewable.io -->

2023-08-26 18:03 UTC, sahibaCCM commented
trigger uts

2023-08-28 18:59 UTC, kapil-harness approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51717)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-29 05:43 UTC, merged