feat: [PL-39275]: Send events to segment for project related audit enteries
harness/harness-core pull request #51716
Opened 2023-08-16 10:05 UTC by sahibaCCM

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-17 05:35 UTC, Raghav-Murali commented on platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
> +            properties.put("PROJECT_ID", savedAuditEvent.getResourceScope().getProjectIdentifier());
Will it be possible to publish this as Prometheus metrics as well ? We would need it for the Grafana dashboards as well. This can be used as a reference on how to define Prometheus metrics https://github.com/harness/harness-core/pull/51304.

2023-08-17 05:36 UTC, sahibaCCM commented on platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
> +            properties.put("PROJECT_ID", savedAuditEvent.getResourceScope().getProjectIdentifier());
Sure

2023-08-17 05:48 UTC, sahibaCCM commented
trigger uts

2023-08-17 08:29 UTC, sahibaCCM commented
trigger uts

2023-08-17 08:30 UTC, sahibaCCM commented on platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java
> +            properties.put("PROJECT_ID", savedAuditEvent.getResourceScope().getProjectIdentifier());
Will be creating a separate PR to onboard the changes.

2023-08-21 05:41 UTC, sahibaCCM commented
trigger ut0

2023-08-21 05:41 UTC, sahibaCCM commented
trigger ut7

2023-08-21 12:39 UTC, sahibaCCM commented
trigger ut0

2023-08-21 19:24 UTC, Raghav-Murali commented
@sahibaCCM - Have some discussions going on here (https://harness.atlassian.net/browse/PL-39275?focusedCommentId=557191). Let's get the conversation resolved and then merge this PR. We need these to be published to OpenCensus too, for which we can raise a different PR.

2023-08-23 03:18 UTC, Raghav-Murali submitted a review, later dismissed
Please get it reviewed from Neelam and get their approval as well. Since this has Segment related changes.

2023-08-23 10:27 UTC, sahibaCCM commented
trigger ut0

2023-08-25 11:21 UTC, sahibaCCM commented
trigger uts

2023-08-25 13:00 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51716)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/51716#-NcglYfsAuF-I6svkqb2:-NcglYft7BzVHYTr1bxl:b-9woyah) ([raw file](https://github.com/harness/harness-core/blob/11350c8cf99511bb6214deff393edb9693e295df/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L138)):*
> ```Java
>           if (isNotEmpty(savedAuditEvent.getResourceScope().getProjectIdentifier())) {
>             HashMap<String, Object> identifyEventProperties = new HashMap<>();
>             identifyEventProperties.put("AccountId", savedAuditEvent.getResourceScope().getAccountIdentifier());
> ```

should be "accountId"
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 139 at r3](https://reviewable.io/reviews/harness/harness-core/51716#-NcglaTt0fmrfwcW21CB:-NcglaTt0fmrfwcW21CC:b-t7a1ad) ([raw file](https://github.com/harness/harness-core/blob/11350c8cf99511bb6214deff393edb9693e295df/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L139)):*
> ```Java
>             HashMap<String, Object> identifyEventProperties = new HashMap<>();
>             identifyEventProperties.put("AccountId", savedAuditEvent.getResourceScope().getAccountIdentifier());
>             identifyEventProperties.put("ProjectId", savedAuditEvent.getResourceScope().getProjectIdentifier());
> ```

should be "projectId"
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 140 at r3](https://reviewable.io/reviews/harness/harness-core/51716#-NcglktOE2aU5HhS9adT:-NcglktOE2aU5HhS9adU:b97a1r0) ([raw file](https://github.com/harness/harness-core/blob/11350c8cf99511bb6214deff393edb9693e295df/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L140)):*
> ```Java
>             identifyEventProperties.put("AccountId", savedAuditEvent.getResourceScope().getAccountIdentifier());
>             identifyEventProperties.put("ProjectId", savedAuditEvent.getResourceScope().getProjectIdentifier());
>             telemetryReporter.sendIdentifyEvent(savedAuditEvent.getAuthenticationInfo().getPrincipal().getIdentifier(),
> ```

as we discussed last time, lets make it a sendGroupEvent() and both identify & trackEvent is not required


<!-- Sent from Reviewable.io -->

2023-08-26 18:00 UTC, sahibaCCM commented
trigger uts

2023-08-28 12:12 UTC, sahibaCCM commented
trigger uts

2023-08-28 12:23 UTC, sahibaCCM commented
trigger uts

2023-08-28 12:53 UTC, sahibaCCM commented
trigger ut1

2023-08-28 12:57 UTC, sahibaCCM commented
trigger ut1

2023-08-28 19:02 UTC, kapil-harness approved these changes
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51716)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-29 02:34 UTC, neelam-harness approved these changes

2023-08-29 05:42 UTC, merged