feat: [CDS-77006]: adds support to update multiples change task on se…
harness/harness-core pull request #51736
Opened 2023-08-16 20:39 UTC by rafaelmart1ns

…rvice now

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-16 21:35 UTC, lasdox commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +    });
```suggestion
Map<String, String> fieldsBody = serviceNowTaskNGParameters.getFields()
    .entrySet()
    .stream()
    .filter(entry -> !entry.getValue().isEmpty())
    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
```

2023-08-24 22:20 UTC, lasdox commented
trigger uts

2023-08-31 12:13 UTC, rafaelmart1ns commented
trigger uts

2023-08-31 23:15 UTC, rafaelmart1ns commented
trigger uts_JDK11

2023-09-01 01:08 UTC, RajBaviskar submitted a review, later dismissed

2023-09-01 15:19 UTC, rafaelmart1ns commented
trigger uts

2023-09-01 15:19 UTC, rafaelmart1ns commented
trigger featurenamecheck

2023-09-01 17:41 UTC, rafaelmart1ns commented
trigger uts

2023-09-01 18:30 UTC, rafaelmart1ns commented
trigger uts

2023-09-01 18:56 UTC, RajBaviskar commented
trigger uts

2023-09-04 11:59 UTC, abhinavmittal-harness requested changes
> Reviewed 5 of 11 files at r3, 3 of 5 files at r4, 9 of 14 files at r5, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 467 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV2JG05sf7SdOmlCCH:-NdV2JG05sf7SdOmlCCI:bg7uf8i) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L467)):*
> ```Java
>     String changeTaskType = serviceNowTaskNGParameters.getUpdateMultipleTasks().getChangeTaskType();
> 
>     if (changeRequestNumber.isEmpty()) {
> ```

nit: we can use isBlank it is a direct upgrade to isEmpty
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 470 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV1vNrDcBA3_SVOTGX:-NdV1vNrDcBA3_SVOTGY:b-jfb43k) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L470)):*
> ```Java
>       log.error("Change Request Number is required to update change tasks.");
>       throw new ServiceNowException(
>           "Change Request Number is required to update change tasks.", SERVICENOW_ERROR, USER);
> ```

Should we throw an error if a user has selected a ticket type other than CHANGE_TASK
Also should we add this validation in the plan creation itself.
If change request number is null then we can fail as early as the plan creation itself.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/UpdateMultipleTasksNode.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV1mXH-ubqykvCexaY:-NdV1mXH-ubqykvCexaZ:b-a8gtyg) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/UpdateMultipleTasksNode.java#L23)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class UpdateMultipleTasksNode {
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) String changeTaskType;
> ```

We are not planning to support these values as runtime or expression?


<!-- Sent from Reviewable.io -->

2023-09-04 12:07 UTC, abhinavmittal-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 492 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV46daEzaejGBjcAxP:-NdV46daEzaejGBjcAxQ:b3yyere) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L492)):*
> ```Java
>       log.info("Body of the update issue request made to the ServiceNow server: {}", fieldsBody);
>       Callable<ServiceNowTicketNG> task = ()
>           -> updateSingleTask(
> ```

Since we are hitting the requests concurrently, could it be possible to hit rate limits here. If so should we consider adding waits in between.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 501 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV3ZIkA87Nm9QjkLwX:-NdV3ZIkA87Nm9QjkLwY:b-2o7tpc) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L501)):*
> ```Java
>     for (Future<ServiceNowTicketNG> future : futures) {
>       try {
>         ServiceNowTicketNG partialResult = future.get(5, TimeUnit.SECONDS);
> ```

Do we have any reasoning of keeping it as 5 seconds, and if we decide on this we should take a note to document it.


<!-- Sent from Reviewable.io -->

2023-09-04 12:07 UTC, abhinavmittal-harness reviewed
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-04 12:51 UTC, rafaelmart1ns reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 22 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 467 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV2JG05sf7SdOmlCCH:-NdVEmYDCTNbir0UWbb8:b-je67d2) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L467)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

nit: we can use isBlank it is a direct upgrade to isEmpty
</blockquote></details>

It was updated.


<!-- Sent from Reviewable.io -->

2023-09-04 13:01 UTC, rafaelmart1ns reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 22 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 470 at r1](https://reviewable.io/reviews/harness/harness-core/51736#gh-1296453570:-NdVHB6P4fN3DhBB03QX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dc93d8a4263adc03ac92e08aa3986523f631550/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L470)):*
<details><summary><i>Previously, lasdox (Lucas Sales) wrote…</i></summary><blockquote>

```suggestion
Map<String, String> fieldsBody = serviceNowTaskNGParameters.getFields()
    .entrySet()
    .stream()
    .filter(entry -> !entry.getValue().isEmpty())
    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
```
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 492 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV46daEzaejGBjcAxP:-NdVGm1y8HJXiVt4P6TQ:b-xs05th) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L492)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Since we are hitting the requests concurrently, could it be possible to hit rate limits here. If so should we consider adding waits in between.
</blockquote></details>

This function has an exponential retry internally. As you see in: https://github.com/harness/harness-core/blob/0c86025d118dd4d06a14bd229a3959d794b3b948/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L521


<!-- Sent from Reviewable.io -->

2023-09-04 14:15 UTC, rafaelmart1ns reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 22 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/UpdateMultipleTasksNode.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV1mXH-ubqykvCexaY:-NdVXeQj9bdGmTe3amtM:bqb4zhr) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/UpdateMultipleTasksNode.java#L23)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

We are not planning to support these values as runtime or expression?
</blockquote></details>

For now, I think we should go without because it's an unblocker. So to unlock it we must follow, but I sent the suggestion to PM to keep it in our view.


<!-- Sent from Reviewable.io -->

2023-09-04 19:00 UTC, rafaelmart1ns reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 24 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 470 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV1vNrDcBA3_SVOTGX:-NdVi9DG7YAWY5eXd4Lg:bghld27) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L470)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Should we throw an error if a user has selected a ticket type other than CHANGE_TASK
Also should we add this validation in the plan creation itself.
If change request number is null then we can fail as early as the plan creation itself.
</blockquote></details>

As aligned in call, I did the change
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 501 at r6](https://reviewable.io/reviews/harness/harness-core/51736#-NdV3ZIkA87Nm9QjkLwX:-NdVeU1S1gMO09M4yDKk:bpef54z) ([raw file](https://github.com/harness/harness-core/blob/08a10b53e6edf1892fc4191ab52f45f4820594a8/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L501)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Do we have any reasoning of keeping it as 5 seconds, and if we decide on this we should take a note to document it.
</blockquote></details>

Im keeping the same behavior in other external requests.


<!-- Sent from Reviewable.io -->

2023-09-04 21:58 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 24 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-08 20:03 UTC, rafaelmart1ns commented
trigger uts

2023-09-11 12:48 UTC, rafaelmart1ns commented
trigger uts

2023-09-13 13:45 UTC, naman-goenka commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +  public ExecutorService serviceNowFetchTaskExecutor() {
nit: name can be serviceNowFetchTicketExecutor

2023-09-13 13:48 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowUtils.java
> +  public static final String QUERY = "change_request.number=%s^change_task_type=%s";
These can be added in `ServiceNowConstants`. Also please rename QUERY to know what the query is for

2023-09-13 14:01 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +                                         .filter(entry -> !entry.getValue().isEmpty())
StringUtils.isNotEmpty() to avoid npe/readability

2023-09-13 14:22 UTC, rafaelmart1ns commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +  public ExecutorService serviceNowFetchTaskExecutor() {
done.

2023-09-13 14:29 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +        ServiceNowTicketNG partialResult = future.get(5, TimeUnit.SECONDS);
`5` can be converted to a static variable, also we have noticed snow create/update calls taking more than a minute in customer setup. Would recommend to keep this value same as timeout in `ServiceNowTaskNGHelper` i.e. 2 minutes

2023-09-13 14:29 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
>    private ServiceNowTaskNGResponse updateTicketWithoutTemplate(ServiceNowTaskNGParameters serviceNowTaskNGParameters) {
`updateTicketUsingTemplate` will need to handled or fast failed.

2023-09-13 14:30 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +      log.info("Body of the update issue request made to the ServiceNow server: {}", fieldsBody);
This log will be the same for all tasks we can keep it outside of the forloop

2023-09-13 14:32 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +        log.error("Failed to get ServiceNowTicket", e);
Type - failed to update ticket in updateMultipleTask

2023-09-13 14:33 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowUtils.java
> +  public static final String QUERY = "change_request.number=%s^change_task_type=%s";
They were moved.

2023-09-13 14:33 UTC, rafaelmart1ns commented on 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java
> +  public ExecutorService serviceNowFetchTaskExecutor() {
it was changed.

2023-09-13 14:33 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +        throw new ServiceNowException("Failed to get ServiceNowTicket, please contact support", SERVICENOW_ERROR, USER);
Similarly here : Code Quote
```
      throw new ServiceNowException(
          String.format("Error occurred while updating serviceNow ticket: %s", ExceptionUtils.getMessage(ex)),
          SERVICENOW_ERROR, USER, ex);
```

2023-09-13 14:36 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +                                         .filter(entry -> !entry.getValue().isEmpty())
it was changed.

2023-09-13 14:38 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +        ServiceNowTicketNG partialResult = future.get(5, TimeUnit.SECONDS);
good suggestion, it was changed.

2023-09-13 14:42 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +        throw new ServiceNowException("Failed to get ServiceNowTicket, please contact support", SERVICENOW_ERROR, USER);
its not possible.

2023-09-13 14:43 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +      log.info("Body of the update issue request made to the ServiceNow server: {}", fieldsBody);
it was changed.

2023-09-13 14:44 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +  public ServiceNowTicketNG updateSingleTask(ServiceNowRestClient serviceNowRestClient,
This method is exactly the same as `updateTicketWithoutTemplate`, can you use it with minor refactoring if required. Will be easier to maintain.

2023-09-13 14:48 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +      handleResponse(response, "Failed to fetch ServiceNow ticket");
Failed to fetch tasks for CR

2023-09-13 14:50 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +      log.error("Failed to update ServiceNow ticket: {}", ExceptionUtils.getMessage(e), e);
fetch tasks

2023-09-13 14:50 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +          String.format("Error occurred while updating serviceNow ticket: %s", ExceptionUtils.getMessage(ex)),
similarly here

2023-09-13 14:51 UTC, abhinavmittal-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +          String.format("Error occurred while updating serviceNow ticket: %s", ExceptionUtils.getMessage(ex)),
nit: Error occurred while updating serviceNow ticket: %s This is being used multiple times.
A constant can be made.
Similar changes at other places are also possible.

2023-09-13 14:55 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
>      throw new ServiceNowException(message + " : " + response.errorBody().string(), SERVICENOW_ERROR, USER);
This can be removed as well as it is being refactored to be in Utils

2023-09-13 15:11 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepInfo.java
We will need a oneOff condition between ticketNumber and updateMultipleTaskNode

2023-09-13 15:20 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepPlanCreator.java
> +    validateServiceNowUpdateMultipleTasks(stepElement.getServiceNowUpdateStepInfo());
left to review

2023-09-13 15:22 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepPlanCreator.java
> +          || ParameterField.isNull(specParameters.getTemplateName())
We will need a different error message here

2023-09-13 15:23 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/test/resources/schema/Pipelines/all.json
> +      "properties": {
We will need static schema changes as well for this PR

2023-09-13 15:28 UTC, naman-goenka reviewed
Since this is a migration blocker, we can add an unit test coverage task in backlog

2023-09-13 15:55 UTC, abhinavmittal-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowUpdateMultipleHelper.java
> +  ServiceNowTaskNGResponse doUpdate(ServiceNowTaskNGParameters serviceNowTaskNGParameters,
Do we really need an interface and getType.
I don't see any reference to that

2023-09-13 17:37 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +          String.format("Error occurred while updating serviceNow ticket: %s", ExceptionUtils.getMessage(ex)),
it was changed

2023-09-13 17:39 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +      handleResponse(response, "Failed to fetch ServiceNow ticket");
done.

2023-09-13 17:41 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +      log.error("Failed to update ServiceNow ticket: {}", ExceptionUtils.getMessage(e), e);
done.

2023-09-13 17:41 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +          String.format("Error occurred while updating serviceNow ticket: %s", ExceptionUtils.getMessage(ex)),
done.

2023-09-13 17:48 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
>      throw new ServiceNowException(message + " : " + response.errorBody().string(), SERVICENOW_ERROR, USER);
I cannot move this, when I move it Bazel starts failing in another part of the code not related. See more details at https://harness.slack.com/archives/C013QRV6W2J/p1694204435740379

2023-09-13 17:54 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepInfo.java
It was added.

2023-09-13 17:56 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java
> +      if (updateMultipleType.equalsIgnoreCase("change_task")) {
it was changed.

2023-09-13 18:30 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowUpdateMultipleHelper.java
> +  ServiceNowTaskNGResponse doUpdate(ServiceNowTaskNGParameters serviceNowTaskNGParameters,
Yes, this was created to have a future abstraction for each type, but as they are different modules this would not work and it ended up this way. I made the necessary changes and removed it from the code.

2023-09-13 18:32 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java
> +                                               .changeTaskType(changeTaskSpec.getChangeTaskType().getValue())
As was done in the spec interface, it is mandatory for the yaml to have a value declared in the spec. In this case it will always have a valid value. And for now just the change_task.

2023-09-13 18:50 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepPlanCreator.java
> +          || ParameterField.isNull(specParameters.getTemplateName())
It was changed.

2023-09-13 18:50 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepPlanCreator.java
> +    validateServiceNowUpdateMultipleTasks(stepElement.getServiceNowUpdateStepInfo());
I changed it.

2023-09-14 15:46 UTC, abhinavmittal-harness reviewed
> Reviewed 2 of 12 files at r9, 7 of 23 files at r10, 7 of 7 files at r12, 1 of 6 files at r13, 12 of 13 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 35 file(s) to review. 1 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-14 15:48 UTC, abhinavmittal-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 35 file(s) to review. 17. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-14 23:49 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/test/resources/schema/Pipelines/all.json
> +      "properties": {
done.

2023-09-14 23:49 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java
> +                                               .changeTaskType(changeTaskSpec.getChangeTaskType().getValue())
It was solved.

2023-09-14 23:49 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowChangeTaskUpdateMultiple.java
> +  public ServiceNowTicketNG updateSingleTask(ServiceNowRestClient serviceNowRestClient,
It was changed.

2023-09-14 23:51 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
>    private ServiceNowTaskNGResponse updateTicketWithoutTemplate(ServiceNowTaskNGParameters serviceNowTaskNGParameters) {
I added support for it

2023-09-14 23:54 UTC, rafaelmart1ns commented
trigger uts

2023-09-15 01:09 UTC, rafaelmart1ns commented
trigger uts

2023-09-15 02:45 UTC, rafaelmart1ns commented
trigger uts

2023-09-15 13:12 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java
> +                                               .changeTaskType(changeTaskSpec.getChangeTaskType().getValue())
What happens in the case of unresolved expression for change request number, is the step fast failing?

2023-09-15 13:15 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
>      throw new ServiceNowException(message + " : " + response.errorBody().string(), SERVICENOW_ERROR, USER);
We can debug this later in that case

2023-09-15 13:40 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/ChangeTaskUpdateMultipleSpec.java
> +  @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> changeTaskType;
@rafaelmart1ns I believe this was optional in CG. If marking this as optional, we need to change the client query as well `"change_request.number=%s^change_task_type=%s";` won't work with null task type

2023-09-15 13:57 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepInfo.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> ticketType;
[ticketNumber = xyz; ticketType = null; updateMultiple = null]
[ticketNumber = null; ticketType = xyz; updateMultiple = null]

Both of them are possible now, do we want this as valid yamls?

2023-09-15 14:28 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +          throw new ServiceNowException(
We can throw the exception as here. 

If an ServiceNow exception is thrown while updating any of the tickets, will it be caught?

2023-09-15 14:31 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +    ChangeTaskUpdateMultiple changeTaskUpdateMultiple =
npe possible

2023-09-15 14:38 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepPlanCreator.java
> +            String.format("Missing ticket number when updating ticket from ServiceNow template in %s step",
`from ServiceNow template` this should be removed

2023-09-15 22:34 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStep.java
> +                                               .changeTaskType(changeTaskSpec.getChangeTaskType().getValue())
It was check and raised an exception.

2023-09-15 22:34 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/ChangeTaskUpdateMultipleSpec.java
> +  @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> changeTaskType;
I changed it.

2023-09-15 22:34 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepInfo.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> ticketType;
it was changed.

2023-09-15 22:39 UTC, rafaelmart1ns commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +    ChangeTaskUpdateMultiple changeTaskUpdateMultiple =
it was changed.

2023-09-15 22:40 UTC, rafaelmart1ns commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateStepPlanCreator.java
> +            String.format("Missing ticket number when updating ticket from ServiceNow template in %s step",
it was changed.

2023-09-15 23:30 UTC, rafaelmart1ns commented
trigger uts

2023-09-16 03:41 UTC, naman-goenka approved these changes

2023-09-16 08:42 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 13 files at r14, 9 of 21 files at r15, 1 of 2 files at r16, 1 of 5 files at r17, 12 of 12 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 35 file(s) to review. 22. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-16 08:42 UTC, abhinavmittal-harness commented
trigger review

2023-09-16 14:22 UTC, rafaelmart1ns commented
trigger uts

2023-09-16 17:31 UTC, naman-goenka approved these changes

2023-09-17 20:55 UTC, rafaelmart1ns commented
trigger uts

2023-09-18 03:18 UTC, naman-goenka approved these changes

2023-09-18 04:13 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51736)* status: 35 file(s) to review. 22. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-18 04:14 UTC, abhinavmittal-harness commented
trigger review

2023-09-18 07:19 UTC, merged