fix:[SRM-15329]:Created Subscription API for getting the License Usage
harness/harness-core pull request #51748
Opened 2023-08-17 08:47 UTC by shash-harness

## Created the API according to the new UI , and have added the corresponding UT's as well.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-17 08:49 UTC, shash-harness commented
trigger uts

2023-08-18 01:27 UTC, shash-harness commented
trigger uts

2023-08-18 02:23 UTC, shash-harness commented
trigger ut4

2023-08-18 03:43 UTC, shash-harness commented
trigger ut4

2023-08-22 13:14 UTC, shash-harness commented
trigger uts

2023-08-22 13:44 UTC, shash-harness commented
trigger uts

2023-08-23 00:37 UTC, shash-harness commented
trigger uts

2023-08-23 01:42 UTC, shash-harness commented
trigger commonchecks

2023-08-23 02:01 UTC, shash-harness commented
trigger uts

2023-08-23 02:11 UTC, shash-harness commented
trigger uts

2023-08-23 02:56 UTC, shash-harness commented
trigger uts

2023-08-23 04:19 UTC, deepak-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51748)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2157 at r6](https://reviewable.io/reviews/harness/harness-core/51748#-NcVZx-N56u-YosgK4LA:-NcVZx-N56u-YosgK4LB:bxatsd7) ([raw file](https://github.com/harness/harness-core/blob/53882adae357ec2f7ee8a314b28c679a63e93db6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2157)):*
> ```Java
>       ServiceParams serviceParams = getServiceParams(monitoredService);
>       ActiveDTO activeDTO =
>           serviceParamsCountMap.getOrDefault(serviceParams, new ActiveDTO(0, new ArrayList<String>()));
> ```

Can we use builder pattern here
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2161 at r6](https://reviewable.io/reviews/harness/harness-core/51748#-NcV_mtq03Djidd8ir1u:-NcV_mtq03Djidd8ir1v:bvorv8h) ([raw file](https://github.com/harness/harness-core/blob/53882adae357ec2f7ee8a314b28c679a63e93db6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2161)):*
> ```Java
>       List<String> envNames = activeDTO.getEnvNames();
>       List<String> env = monitoredService.getEnvironmentIdentifierList();
>       for (String temp : env) {
> ```

use better variable names than temp and env.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2211 at r6](https://reviewable.io/reviews/harness/harness-core/51748#-NcVaAGU4U8kZgT3NuAZ:-NcVaAGV-rCVUHNqxr1x:b-ekbyp3) ([raw file](https://github.com/harness/harness-core/blob/53882adae357ec2f7ee8a314b28c679a63e93db6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2211)):*
> ```Java
>     ServiceParams serviceParams = ServiceParams.builder().serviceIdentifier(ms.getServiceIdentifier()).build();
>     String serviceIdentifier = ms.getServiceIdentifier();
>     if (serviceIdentifier.startsWith("account")) {
> ```

define account, org as constant.


<!-- Sent from Reviewable.io -->

2023-08-23 06:34 UTC, Varsha-lalwani requested changes

2023-08-23 06:34 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/usage/impl/ActiveServiceMonitoredFilterParams.java
> -  @EntityIdentifier(allowBlank = true)
this allowBlank can still be true right?

2023-08-23 06:34 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/usage/impl/resources/ActiveMonitoredServiceDTO.java
>  public class ActiveMonitoredServiceDTO extends LicenseUsageDTO {
ActiveServiceDTO*

2023-08-23 06:34 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +      }
you can simplify and avoid code duplication here by having two if statements instead of if else statements

2023-08-23 08:55 UTC, shash-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/usage/impl/ActiveServiceMonitoredFilterParams.java
> -  @EntityIdentifier(allowBlank = true)
yeah, it still allows for blank , removed this to account for queryString of the form 'account/org.serviceIdentifier'

2023-08-23 11:00 UTC, shash-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51748)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2157 at r6](https://reviewable.io/reviews/harness/harness-core/51748#-NcVZx-N56u-YosgK4LA:-NcX2EZp76Oqef3JIljK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53882adae357ec2f7ee8a314b28c679a63e93db6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2157)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Can we use builder pattern here
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2161 at r6](https://reviewable.io/reviews/harness/harness-core/51748#-NcV_mtq03Djidd8ir1u:-NcX2FKE4elBKvk2YtMW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53882adae357ec2f7ee8a314b28c679a63e93db6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2161)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

use better variable names than temp and env.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2197 at r6](https://reviewable.io/reviews/harness/harness-core/51748#gh-1302543955:-NcX2Ggu2Djr1wRdvt5h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53882adae357ec2f7ee8a314b28c679a63e93db6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2197)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

you can simplify and avoid code duplication here by having two if statements instead of if else statements 
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2211 at r6](https://reviewable.io/reviews/harness/harness-core/51748#-NcVaAGU4U8kZgT3NuAZ:-NcX2HqB-OreGlvCmH1E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53882adae357ec2f7ee8a314b28c679a63e93db6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2211)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

define account, org as constant.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-23 11:01 UTC, shash-harness commented
trigger uts

2023-08-23 13:32 UTC, Varsha-lalwani approved these changes

2023-08-23 13:39 UTC, merged