fix: [PL-40669]: check for oldest active token incase of default token not present
harness/harness-core pull request #51741
Opened 2023-08-17 05:32 UTC by VikasMaddukuriHarness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-17 06:11 UTC, VikasMaddukuriHarness commented
trigger uts

2023-08-17 17:01 UTC, VikasMaddukuriHarness commented
trigger ut1

2023-08-21 04:47 UTC, VikasMaddukuriHarness commented
trigger uts

2023-08-23 21:08 UTC, jennyjames21 requested changes

2023-08-23 21:08 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +                                      .get();
Should this be list of delegateToken?

2023-08-23 21:08 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +            .set(DelegateTokenKeys.name, tokenName + REVOKED_TOKEN_SUFFIX)
if you rename the token name, how will we identify if the delegate using revoked token or not, as delegate has the old token name and we always do token lookup based on the token name?
What's the advantage of renaming here?

2023-08-27 13:52 UTC, VikasMaddukuriHarness commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +                                      .get();
We are just getting the oldest active token from the delegates collection. Why do we need a list here?

2023-08-27 13:53 UTC, VikasMaddukuriHarness commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +            .set(DelegateTokenKeys.name, tokenName + REVOKED_TOKEN_SUFFIX)
ok. Removing this suffix part and making the ttl of the revoked token to 3 days which is currently 30 days. But this will be applicable from now on only. Should we need a migration to delete the existing revoked delegate tokens?

2023-09-06 17:49 UTC, xingchi-jin reviewed
LG after a comment

2023-09-06 17:49 UTC, xingchi-jin commented on 920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java
> +  public static final Duration TTL = ofDays(3);
we need to set valid until based on status. only REVOKED is 3 days

2023-09-07 04:25 UTC, VikasMaddukuriHarness commented on 920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java
> +  public static final Duration TTL = ofDays(3);
Yes this static value is used when revoking a token. We use this value to set the valid until field 
This is the place - 

link - https://github.com/harness/harness-core/blob/1789ce5f412d8926e4c4b33b7c4ed89d76d54b20/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L128

2023-09-07 04:25 UTC, VikasMaddukuriHarness commented
trigger uts

2023-09-07 16:44 UTC, VikasMaddukuriHarness commented
trigger uts

2023-09-07 23:46 UTC, xingchi-jin approved these changes

2023-09-12 00:45 UTC, xingchi-jin commented on 920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java
> +  public static final Duration REVOKED_TOKEN_TTL = ofDays(3);
since the name nolonger unique index, do we still need this ?

2023-09-12 00:46 UTC, xingchi-jin commented on 920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java
>                   .field(DelegateTokenKeys.name)
shall we keep an index using tokenName, but not unique index

2023-09-12 00:48 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +  private Query<DelegateToken> matchNameTokenQuery(String accountId, String tokenName, DelegateEntityOwner owner) {
will this be a list of tokens in return ?

2023-09-12 02:26 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +  private Query<DelegateToken> matchNameTokenQuery(String accountId, String tokenName, DelegateEntityOwner owner) {
This is a common function, it can be list when two token with the same name exists but in a different state. 
Some flow only requires Active token ones, but the authentication, we may need both

2023-09-12 02:26 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +                                                                  .uuid(delegateToken.getUuid())
why this change?

2023-09-12 02:26 UTC, jennyjames21 commented on 920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java
>                   .field(DelegateTokenKeys.name)
@xingchi-jin Mongo considers partial index so this case {accountId, name} order is already indexed.

@VikasMaddukuriHarness Once this goes to prod, please work with DBAs to remove the old index manually as we have seen recently it will not automatically get deleted

2023-09-12 02:41 UTC, jennyjames21 commented
@VikasMaddukuriHarness When u test can you verify this use case
1) Create a token 'xxx' and start delegate with that token. Verify it's connected and HB coming throgh
2) Revoke the token "xxx", and verify delegate got disconnected
3) Create new token with the same name (xxx) with the same scope and start a new delegate with new token and verify it's connected
4) Do the same flow for different scope too

2023-09-13 00:44 UTC, xingchi-jin commented
also please test with:  register a delegate with a revoked token

2023-09-13 15:52 UTC, mdmilic requested changes
> Reviewed 1 of 1 files at r2, 2 of 4 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51741)* status: 12 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4462 at r5](https://reviewable.io/reviews/harness/harness-core/51741#-NeEDm3E7QqnvvsjpEbu:-NeEDm3E7QqnvvsjpEbv:bnt58cm) ([raw file](https://github.com/harness/harness-core/blob/c346279891b7d1da4e04ec297fb5d21748a20fbc/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4462)):*
> ```Java
>     if (delegateTokenName.isPresent()) {
>       DelegateTokenDetails delegateTokenDetails =
>           delegateNgTokenService.getDelegateToken(accountId, null, delegateTokenName.get());
> ```

Why null here, that would mean account scope? The same on other places as well. We use this to register delegate to the appropriate scope that it's token belongs to. 
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 54 at r5](https://reviewable.io/reviews/harness/harness-core/51741#gh-1322239794:-NeED-bu8ZMgSe7zzm4c:by2bewi) ([raw file](https://github.com/harness/harness-core/blob/c346279891b7d1da4e04ec297fb5d21748a20fbc/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L54)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

@xingchi-jin Mongo considers partial index so this case {accountId, name} order is already indexed.

@VikasMaddukuriHarness Once this goes to prod, please work with DBAs to remove the old index manually as we have seen recently it will not automatically get deleted
</blockquote></details>

I don't think we can change this index like this. I think our delegate auth mechanism assumes that the token is unique by name (so we cache JWT Token -> token.name), having multiple tokens with the same name across orgs/projs would cause collision and potentially authenticate delegate with to a wrong scope. Can you please double check those flows to make sure they would work with multiple tokens with the same name present in DB. 


<!-- Sent from Reviewable.io -->

2023-09-15 06:09 UTC, VikasMaddukuriHarness commented on 400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java
> +                                                                  .uuid(delegateToken.getUuid())
we are not returning the delegateToken UUID. This is required in case of delegate token crud using terraform. This does not impact any flow apart from the getCall for delegateToken

2023-09-15 06:09 UTC, VikasMaddukuriHarness commented on 920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java
> +  public static final Duration REVOKED_TOKEN_TTL = ofDays(3);
you mean to keep the revoked token till 30 days. Ok I will revert that change

2023-09-15 06:17 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51741)* status: Some of the checks are too old. 12 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 54 at r5](https://reviewable.io/reviews/harness/harness-core/51741#gh-1322239794:-NeMSr5q1aAqBWFzu_FQ:b-ssspyd) ([raw file](https://github.com/harness/harness-core/blob/c346279891b7d1da4e04ec297fb5d21748a20fbc/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L54)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I don't think we can change this index like this. I think our delegate auth mechanism assumes that the token is unique by name (so we cache JWT Token -> token.name), having multiple tokens with the same name across orgs/projs would cause collision and potentially authenticate delegate with to a wrong scope. Can you please double check those flows to make sure they would work with multiple tokens with the same name present in DB.
</blockquote></details>

Yes @mdmilic we need to modify the auth mechanism as well in that case. We need to start hashing the token along with the scope details in it. If multiple scopes have same name, there will be a hash collision if we just use the token name to hash.
@jennyjames21 @xingchi-jin what do you think.


<!-- Sent from Reviewable.io -->

2023-09-20 15:58 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51741)* status: Some of the checks are too old. 12 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 54 at r5](https://reviewable.io/reviews/harness/harness-core/51741#gh-1322239794:-NenIbkq0_D_pR8SHbKU:b52dnod) ([raw file](https://github.com/harness/harness-core/blob/c346279891b7d1da4e04ec297fb5d21748a20fbc/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L54)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

Yes @mdmilic we need to modify the auth mechanism as well in that case. We need to start hashing the token along with the scope details in it. If multiple scopes have same name, there will be a hash collision if we just use the token name to hash.
@jennyjames21 @xingchi-jin what do you think.
</blockquote></details>

@mdmilic I just went through the auth flow again. No where we are using the delegateTokenName to authenticate or store the hash.
The Jwt encrypted token coming from delegate does not depend on the tokenName. In the manager side, the hash which we store in cache also does not use the tokenName. So we are good in the token name changes in authentication of delegate.
I tested this throughly in pr env. 


<!-- Sent from Reviewable.io -->

2023-09-20 16:45 UTC, VikasMaddukuriHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51741)* status: Some of the checks are too old. 12 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4462 at r5](https://reviewable.io/reviews/harness/harness-core/51741#-NeEDm3E7QqnvvsjpEbu:-NenJ3c-EzghRbfxmsDv:b-g7yvtz) ([raw file](https://github.com/harness/harness-core/blob/c346279891b7d1da4e04ec297fb5d21748a20fbc/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4462)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why null here, that would mean account scope? The same on other places as well. We use this to register delegate to the appropriate scope that it's token belongs to.
</blockquote></details>

I understand what you meant by this @mdmilic. Yes this seems to be a problem now.
Because now if we have a token name common for both org and account level, and now if we use that token to create to register a delegate, now delegate will randomly get into accountLevel scope only. Because we check for the delegate Token details using the delegate token name only. In this case even if we use the delegateToken of the org level, after doing the auth in manager side, we actually authenticate it with the org level token, after the auth when registering, we try to fetch the delegateToken details using the delegateToken name. From this token value, we try to fetch the delegate scope. 
The problem arises here. We fetch the details of the accountLevel token only because we are not sure which scope the delegate is trying to register to. 
We need to think of some other approach now to make this change.
@jennyjames21 @xingchi-jin FYI


<!-- Sent from Reviewable.io -->

2023-10-16 00:03 UTC, closed without merging