feat: [PL-32652]: Perform Acl processing for Role through outbox event.
harness/harness-core pull request #51759
Opened 2023-08-17 11:25 UTC by Jimit09Gandhi

## Describe your changes
Perform Acl processing for Role through outbox event.
Refactored code to do outbox event generation from resource to service layer.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-01 11:50 UTC, ankit-harness requested changes
> Reviewed 77 of 77 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: Some of the checks are too old. 77 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFRE8t8vtZuLURXrpE:-NdFRE8t8vtZuLURXrpF:bbmhdk7) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/BUILD.bazel#L20)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//953-events-api:module",
> ```

Why is this needed in core?
___
*[`access-control/libs/core/BUILD.bazel` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFRGC4Dedl17xg4XTk:-NdFRGC5AsDbO86eSnrF:bbmhdk7) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/BUILD.bazel#L27)):*
> ```Starlark
>         "//999-annotations:module",
>         "//access-control/contracts:module",
>         "//platform-service/modules/audit-service/contracts:module",
> ```

Why is this needed in core?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleService.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFTo691RLEW1ZPvUBD:-NdFTo691RLEW1ZPvUBE:b-usl5ts) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleService.java#L44)):*
> ```Java
>   // NOTE: This method should be used only for deleting roles on scope deletion as here we are generating outbox event
>   // for ACLs processing.
>   long deleteMulti(@Valid @NotNull RoleFilter roleFilter);
> ```

Didn't understand this comment
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFVXOoBG6uxqejhs1G:-NdFVXOoBG6uxqejhs1H:b-kqv0ua) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L102)):*
> ```Java
>     validatePermissions(role);
>     addCompulsoryPermissions(role);
>     ScopeDTO scopeDTO = toDTO(scope);
> ```

Why is DTO needed here?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWgXd6CQRWg6L2wbj:-NdFWgXd6CQRWg6L2wbk:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java#L322)):*
> ```Java
>         ClientMode.PRIVILEGED));
> 
>     install(new TransactionOutboxModule(config.getOutboxPollConfig(), ACCESS_CONTROL_SERVICE.getServiceId(),
> ```

Why this change?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWoQ3AiXlIOy-ECIO:-NdFWoQ3AiXlIOy-ECIP:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java#L13)):*
> ```Java
> import static io.harness.accesscontrol.roleassignments.events.RoleAssignmentDeleteEvent.ROLE_ASSIGNMENT_DELETE_EVENT;
> import static io.harness.accesscontrol.roleassignments.events.RoleAssignmentUpdateEvent.ROLE_ASSIGNMENT_UPDATE_EVENT;
> import static io.harness.accesscontrol.scopes.harness.ScopeMapper.fromDTO;
> ```

Why this change?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFY-3U1EiLf5lXS5hR:-NdFY-3U1EiLf5lXS5hS:b-17tgts) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java#L101)):*
> ```Java
>   }
> 
>   private boolean handleRoleUpdateEvent(OutboxEvent outboxEvent) throws IOException {
> ```

Do events which didn't get processed successfully get deleted from outbox?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateMapper.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFY_Lx9xK5cSnDHS9q:-NdFY_Lx9xK5cSnDHS9r:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateMapper.java#L18)):*
> ```Java
> import io.harness.accesscontrol.roleassignments.RoleAssignment;
> import io.harness.accesscontrol.roles.RoleService;
> import io.harness.accesscontrol.roles.api.RoleDTOMapper;
> ```

Why this change?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFYdfhDmZdXoVCfPDg:-NdFYdfhDmZdXoVCfPDh:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L46)):*
> ```Java
> import io.harness.accesscontrol.scopes.core.ScopeLevel;
> import io.harness.accesscontrol.scopes.core.ScopeService;
> import io.harness.accesscontrol.scopes.harness.HarnessScopeLevel;
> ```

Why this change?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/AccountRolesApiImpl.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFZ9H4E7y6bdoGSHJC:-NdFZ9H4E7y6bdoGSHJD:btc8rm4) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/AccountRolesApiImpl.java#L99)):*
> ```Java
>     roleDTO.setAllowedScopeLevels(Sets.newHashSet(fromString(scope.getLevel().toString())));
> 
>     RolesResponse response = Failsafe.with(transactionRetryPolicy).get(() -> transactionTemplate.execute(status -> {
> ```

Can you help me recall why we moved outbox code in core from service
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/HarnessScopeLevel.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWC-_7oACc_912__Z:-NdFWC-a93NaUHZv10LR:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/HarnessScopeLevel.java#L8)):*
> ```Java
>  */
> 
> package io.harness.accesscontrol.scopes.harness;
> ```

Why this change?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/ScopeMapper.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWDOyBpc1dToMp_v-:-NdFWDOyBpc1dToMp_v0:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/ScopeMapper.java#L18)):*
> ```Java
> import io.harness.accesscontrol.scopes.core.Scope;
> import io.harness.accesscontrol.scopes.core.ScopeLevel;
> import io.harness.accesscontrol.scopes.harness.HarnessScopeParams;
> ```

Why this change?


<!-- Sent from Reviewable.io -->

2023-09-07 16:20 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: Some of the checks are too old. 77 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFRE8t8vtZuLURXrpE:-Ndk4ojG5zzm6tDXIsnX:b2ble5k) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/BUILD.bazel#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is this needed in core?
</blockquote></details>

Scope constants referenced in HarnessScopeLevel ie. EventsFrameworkMetadataConstants.ACCOUNT_ENTITY.
I think we can avoid this by defining in Core lib.
___
*[`access-control/libs/core/BUILD.bazel` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFRGC4Dedl17xg4XTk:-NdkMf9W7wLIAJwtdgqX:b8325x2) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/BUILD.bazel#L27)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is this needed in core?
</blockquote></details>

ResourceType constants for audits io.harness.audit.ResourceTypeConstants.ROLE used in RoleCreateEvent. Similarly for 
update and delete.  Same would be needed for other RBAC entities.


<!-- Sent from Reviewable.io -->

2023-09-07 17:18 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: Some of the checks are too old. 77 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleService.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFTo691RLEW1ZPvUBD:-Ndkc6XS1LQkdmMNAvAv:b-uxflvr) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleService.java#L44)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Didn't understand this comment
</blockquote></details>

updated comment.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFVXOoBG6uxqejhs1G:-NdkcbUM46JC_sLW62cV:b-t3kbi0) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L102)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is DTO needed here?
</blockquote></details>

All outbox event objects take in scope in DTO form so keeping it consistent with same. Refer RoleCreateEvent. We can discuss further if we want to refine.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/AccountRolesApiImpl.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFZ9H4E7y6bdoGSHJC:-NdkdF-j-tvj-6F12D9h:b8r00f4) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/AccountRolesApiImpl.java#L99)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can you help me recall why we moved outbox code in core from service
</blockquote></details>

Previously outbox was handled in resource layer. The responsibility should be with service class and not in resource class. 
Core lib hosts all the RBAC entities service, DAO and Repository classes. So we had to move outbox code to Core lib.


<!-- Sent from Reviewable.io -->

2023-09-07 17:45 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: Some of the checks are too old. 77 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/HarnessScopeLevel.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWC-_7oACc_912__Z:-Ndkjfiy8M6qmD5HJFfG:b-r755b3) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/HarnessScopeLevel.java#L8)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

ScopeMapper has reference of HarnessScopeLevel. ScopeMapper has mappers of toDTO and fromDTO which is used when adding event to outbox.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/ScopeMapper.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWDOyBpc1dToMp_v-:-Ndkjytx7CkyG1yQ0dbw:bkdrc0g) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/ScopeMapper.java#L18)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

ScopeMapper has mappers of toDTO and fromDTO which is used when adding event to outbox.


<!-- Sent from Reviewable.io -->

2023-09-08 07:17 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: Some of the checks are too old. 77 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWgXd6CQRWg6L2wbj:-NdncBE_859ORrUDKZ_H:bguid9t) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java#L322)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Moved outbox module registered from here to core module.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWoQ3AiXlIOy-ECIO:-NdncT0y6dxwXW8_mTpt:b-t3kbi0) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java#L13)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

All outbox event objects take in scope in DTO form so keeping it consistent with same. Refer RoleCreateEvent. We can discuss further if we want to refine.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateMapper.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFY_Lx9xK5cSnDHS9q:-NdnctnTE3nxU46rvilg:bfk25tl) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentAggregateMapper.java#L18)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

same as above. All outbox event objects take in scope in DTO form so keeping it consistent with same. Refer RoleCreateEvent. We can discuss further if we want to refine.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFYdfhDmZdXoVCfPDg:-NdndVqh6siVAv3kbz6g:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L46)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

same as above.


<!-- Sent from Reviewable.io -->

2023-09-08 10:29 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: Some of the checks are too old. 77 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFY-3U1EiLf5lXS5hR:-NdoKMt018Cplk6yhYsz:b-4w6btr) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java#L101)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do events which didn't get processed successfully get deleted from outbox?
</blockquote></details>

No, retry mechanism is baked in Outbox framebox with defined retries. If retries exhaust then post every 10 mins it will be retried. So in sense it is infinite retries.


<!-- Sent from Reviewable.io -->

2023-09-13 10:24 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 89 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFRE8t8vtZuLURXrpE:-NeCROdh0jQRkevK70-t:b-e80fay) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/BUILD.bazel#L20)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Scope constants referenced in HarnessScopeLevel ie. EventsFrameworkMetadataConstants.ACCOUNT_ENTITY.
I think we can avoid this by defining in Core lib.
</blockquote></details>

Introduced new constants in ACS and moved it there.
___
*[`access-control/libs/core/BUILD.bazel` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFRGC4Dedl17xg4XTk:-NeCRUdk12RJOapyZ_YI:bu5nob3) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/BUILD.bazel#L27)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

ResourceType constants for audits io.harness.audit.ResourceTypeConstants.ROLE used in RoleCreateEvent. Similarly for 
update and delete.  Same would be needed for other RBAC entities.
</blockquote></details>

This is valid as discussed. We want to rely on Constants for resources defined by Audits.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/HarnessScopeLevel.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFWC-_7oACc_912__Z:-NeCQKwCE8GHwC-nxF9S:b-9uyb7i) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/libs/core/src/main/java/io/harness/accesscontrol/scopes/HarnessScopeLevel.java#L8)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

ScopeMapper has reference of HarnessScopeLevel. ScopeMapper has mappers of toDTO and fromDTO which is used when adding event to outbox.
</blockquote></details>

Split ScopeMapper in 2 classes. One in core and other existing in Service module. Also moved HarnessScopeLevel to contracts module as it is needed core/ScopeMapper has reference to HarnessScopeLevel.


<!-- Sent from Reviewable.io -->

2023-09-13 10:30 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 89 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFVXOoBG6uxqejhs1G:-NeD3lyq4kgnLsBDmx-z:bikqdir) ([raw file](https://github.com/harness/harness-core/blob/13049d03f8a3eb89e4139aebe3126891d0f1a0df/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/RoleServiceImpl.java#L102)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

All outbox event objects take in scope in DTO form so keeping it consistent with same. Refer RoleCreateEvent. We can discuss further if we want to refine.
</blockquote></details>

As discussed we want to use DTO objects when writing to Outbox.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/51759#-NdFYdfhDmZdXoVCfPDg:-NeD4Ty3-4hb9Bqy_7V6:b-5nn5ul) ([raw file](https://github.com/harness/harness-core/blob/43d4547b3f519a34d809d7dd1e2c5c5d6255b8a9/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L46)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Moved ScopeLevel and HarnessScopeLevel to contracts module. They are then referenced in ScopeMapper in Core module.


<!-- Sent from Reviewable.io -->

2023-09-14 07:50 UTC, Jimit09Gandhi commented
trigger uts

2023-09-14 08:54 UTC, Jimit09Gandhi commented
trigger uts

2023-09-18 04:24 UTC, Jimit09Gandhi commented
trigger uts

2023-09-18 06:54 UTC, Jimit09Gandhi commented
trigger uts

2023-09-18 08:18 UTC, ankit-harness requested changes
> Reviewed 36 of 84 files at r2, 15 of 24 files at r4, 37 of 38 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java` line 122 at r5](https://reviewable.io/reviews/harness/harness-core/51759#-NebMc0f9rWxTcQ5Pm3C:-NebMc0gDyL8mrHuLwDo:b-eud6wl) ([raw file](https://github.com/harness/harness-core/blob/473a529cf151dabb0bddec1035a47927fe37b18a/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java#L122)):*
> ```Java
>   }
> 
>   private boolean handleRoleUpdateEvent(OutboxEvent outboxEvent) throws IOException {
> ```

Refactor this class
Also, move audit after acl processing
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/51759#-NebKEQe59FvmR94ke8q:-NebKEQe59FvmR94ke8r:b-7vbgc8) ([raw file](https://github.com/harness/harness-core/blob/473a529cf151dabb0bddec1035a47927fe37b18a/access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java#L33)):*
> ```Java
> @ValidateOnExecution
> public class ScopeMapper {
>   public static ScopeDTO toDTO(@Valid Scope scope) {
> ```

Revert as discussed
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java` line 54 at r5](https://reviewable.io/reviews/harness/harness-core/51759#-NebKGx8DafDdnWrUJzf:-NebKGx8DafDdnWrUJzg:b-7vbgc8) ([raw file](https://github.com/harness/harness-core/blob/473a529cf151dabb0bddec1035a47927fe37b18a/access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java#L54)):*
> ```Java
>   }
> 
>   public static Scope fromDTO(@Valid @NotNull ScopeDTO scopeDTO) {
> ```

Revert as discussed


<!-- Sent from Reviewable.io -->

2023-09-18 11:53 UTC, Jimit09Gandhi commented
trigger uts

2023-09-18 11:53 UTC, Jimit09Gandhi reviewed
> Reviewed 4 of 77 files at r1, 35 of 84 files at r2, 15 of 24 files at r4, 29 of 38 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/51759#-NebKEQe59FvmR94ke8q:-Nec7vDj36ywxo0__Yf8:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/473a529cf151dabb0bddec1035a47927fe37b18a/access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Revert as discussed
</blockquote></details>

Done
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java` line 54 at r5](https://reviewable.io/reviews/harness/harness-core/51759#-NebKGx8DafDdnWrUJzf:-Nec7vg-DdhW-N5KQQSf:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/473a529cf151dabb0bddec1035a47927fe37b18a/access-control/service/src/main/java/io/harness/accesscontrol/scopes/harness/ScopeMapper.java#L54)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Revert as discussed
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-18 11:54 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java` line 122 at r5](https://reviewable.io/reviews/harness/harness-core/51759#-NebMc0f9rWxTcQ5Pm3C:-Nec8-xx3Bd0jofWT1BS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/473a529cf151dabb0bddec1035a47927fe37b18a/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java#L122)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Refactor this class
Also, move audit after acl processing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-18 12:10 UTC, ankit-harness approved these changes
> Reviewed 10 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-18 12:10 UTC, ankit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-18 12:10 UTC, ankit-harness submitted a review, later dismissed

2023-09-18 12:20 UTC, Jimit09Gandhi commented
trigger uts

2023-09-18 12:29 UTC, Jimit09Gandhi commented
trigger uts

2023-09-18 14:12 UTC, Jimit09Gandhi commented
trigger uts

2023-09-26 14:26 UTC, Jimit09Gandhi commented
trigger uts

2023-09-26 15:50 UTC, Jimit09Gandhi commented
trigger ut7

2023-09-27 02:42 UTC, ankit-harness requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java` line 188 at r8](https://reviewable.io/reviews/harness/harness-core/51759#-NfJTeqg4JfHhbE2nrly:-NfJTeqg4JfHhbE2nrlz:bwvzl6c) ([raw file](https://github.com/harness/harness-core/blob/9b2be6e53bd37c77f0fc1316eac98606336abe79/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java#L188)):*
> ```Java
>   }
> 
>   private Set<String> getPermissions(Set<String> permissions) {
> ```

Why is this method needed?


<!-- Sent from Reviewable.io -->

2023-09-27 05:22 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java` line 188 at r8](https://reviewable.io/reviews/harness/harness-core/51759#-NfJTeqg4JfHhbE2nrly:-NfK4TqZDPoK19jn4te5:b45vekq) ([raw file](https://github.com/harness/harness-core/blob/9b2be6e53bd37c77f0fc1316eac98606336abe79/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleEventHandler.java#L188)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is this method needed?
</blockquote></details>

Resolving. Jimit will resolve it in next PR.


<!-- Sent from Reviewable.io -->

2023-09-27 05:22 UTC, ankit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759)* status: 94 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-27 14:40 UTC, Jimit09Gandhi commented
trigger uts

2023-09-27 16:52 UTC, Jimit09Gandhi commented
trigger ut1

2023-09-27 16:52 UTC, Jimit09Gandhi commented
trigger ut2

2023-09-27 16:52 UTC, Jimit09Gandhi commented
trigger ut9

2023-09-27 17:04 UTC, Jimit09Gandhi commented
trigger ut2

2023-09-27 17:04 UTC, Jimit09Gandhi commented
trigger ut1

2023-09-28 04:17 UTC, Jimit09Gandhi commented
trigger ut1

2023-09-28 04:17 UTC, Jimit09Gandhi commented
trigger ut2

2023-09-28 05:43 UTC, Jimit09Gandhi commented
trigger ut1

2023-09-28 06:01 UTC, Jimit09Gandhi commented
trigger ut1

2023-09-28 08:38 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51759#-:-NfPwAyo93UlgwP2N9Ze:bnfp4nl)* status: 94 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-28 08:53 UTC, merged