[feat]: [CDS-77041]: Adding Service Environment code pulse annotations to missing files
harness/harness-core pull request #51755
Opened 2023-08-17 10:27 UTC by lovish1999

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-23 11:51 UTC, lovish1999 commented
trigger uts

2023-08-23 13:14 UTC, lovish1999 commented
trigger messagecheck

2023-08-23 16:42 UTC, puthrayaharness requested changes

2023-08-23 16:42 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/OrgServicesApiImpl.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = false,
Please remove annotations from file

2023-08-23 16:42 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ProjectServicesApiImpl.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = false,
Remove this is PL related

2023-08-23 16:42 UTC, puthrayaharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeValidator.java
> +@CodePulse(
This also is owned by K8s team I believe. Since this is related to K8s

2023-08-23 16:42 UTC, puthrayaharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java
> +@CodePulse(
This is common steps?

2023-08-23 16:42 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java
> +@CodePulse(
This is Service & Environment?

2023-08-23 16:42 UTC, puthrayaharness commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java
> +@CodePulse(
This is K8s

2023-08-24 03:03 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/IndividualConfigFileStep.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
@puthrayaharness These are spec first apis for service environment

2023-08-24 03:03 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStep.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
Yes.

2023-08-24 03:03 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceCustomSweepingOutputHelper.java
> +@CodePulse(
This is used for overrides

2023-08-24 03:04 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java
> +    module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_COMMON_STEPS})
Yes.

2023-08-24 03:04 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java
> +@CodePulse(
Being used in service v1

2023-08-24 03:05 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/validator/SvcEnvV2ManifestValidator.java
> +@CodePulse(
This class is being used for validation manifest in override. Not specific to any swimlane.

2023-08-24 03:10 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java
> +    components = {HarnessModuleComponent.CDS_SERVICE_ENVIRONMENT})
This can be in common utils

2023-08-24 05:48 UTC, naman-goenka commented on 120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureHelper.java
> +    module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_COMMON_STEPS})
Can we please confirm if Service component is not required here

2023-08-24 05:52 UTC, naman-goenka commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java
> +    components = {HarnessModuleComponent.CDS_SERVICE_ENVIRONMENT})
We can confirm if this can be included in coverage as it has different flow branches

2023-08-24 06:21 UTC, naman-goenka submitted a review, later dismissed

2023-08-24 12:03 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeMapper.java
> +@CodePulse(
Yes. It contains multiple methods not related to k8s

2023-08-24 12:03 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java
> -@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_K8S})
Its Service env. component

2023-08-24 12:04 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/OrgServicesApiImpl.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = false,
Its Service env. component

2023-08-24 12:04 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ProjectServicesApiImpl.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = false,
Its Service env. component

2023-08-24 12:05 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeValidator.java
> +@CodePulse(
okay

2023-08-24 12:09 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java
> +    module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_COMMON_STEPS})
ok

2023-08-24 12:09 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java
> +@CodePulse(
ok

2023-08-24 12:10 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java
> +    components = {HarnessModuleComponent.CDS_SERVICE_ENVIRONMENT})
ok

2023-08-24 12:11 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java
> +    components = {HarnessModuleComponent.CDS_SERVICE_ENVIRONMENT})
ok

2023-08-24 12:13 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigGitFilesMapper.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
Hi @ivan-83 , should we have a different component for file store something.. or I can include them in service env. ?

2023-08-24 12:16 UTC, lovish1999 commented on 120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureHelper.java
> +    module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_COMMON_STEPS})
changed to service env.

2023-08-24 12:17 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigFileOutcomeMapper.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
yes.

2023-08-24 12:22 UTC, ivan-83 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/mapper/ConfigGitFilesMapper.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
This is service & environment because ConfigGitFilesMapper.java is used for mapping git files that are processed in the service step. Also, we set up config files on the service page.

2023-08-24 12:23 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStep.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
yes

2023-08-24 18:53 UTC, ivan-83 approved these changes
> Reviewed 78 of 87 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51755)* status: 88 file(s) to review. 1 change requests. 17. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`999-annotations/src/main/java/io/harness/annotations/dev/HarnessModuleComponent.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/51755#-NccsQ_x9AaHdFSDN3AQ:-NccsQ_x9AaHdFSDN3AR:b-8cliao) ([raw file](https://github.com/harness/harness-core/blob/000307a300c3729a1cd6bc997ed7b2462658938d/999-annotations/src/main/java/io/harness/annotations/dev/HarnessModuleComponent.java#L36)):*
> ```Java
>   CDS_TRIGGERS,
>   CI_PLG_LICENSING,
>   CDS_SLACK
> ```

Minor - why do we remove CDS_SLACK?


<!-- Sent from Reviewable.io -->

2023-08-25 04:36 UTC, tchaurasiya approved these changes

2023-08-25 04:42 UTC, lovish1999 commented
trigger review

2023-08-25 04:42 UTC, lovish1999 commented
> > Reviewed 78 of 87 files at r1, 10 of 10 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/51755)_ status: 88 file(s) to review. 1 change requests. 17. unresolved discussions. 1 of 2 approvals obtained.
> 
> _[`999-annotations/src/main/java/io/harness/annotations/dev/HarnessModuleComponent.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/51755#-NccsQ_x9AaHdFSDN3AQ:-NccsQ_x9AaHdFSDN3AR:b-8cliao) ([raw file](https://github.com/harness/harness-core/blob/000307a300c3729a1cd6bc997ed7b2462658938d/999-annotations/src/main/java/io/harness/annotations/dev/HarnessModuleComponent.java#L36)):_
> 
> > ```java
> >   CDS_TRIGGERS,
> >   CI_PLG_LICENSING,
> >   CDS_SLACK
> > ```
> 
> Minor - why do we remove CDS_SLACK?

It is not required. https://github.com/harness/harness-core/pull/51750#issuecomment-1691199570

2023-08-25 04:56 UTC, yogesh-chauhan approved these changes

2023-08-25 05:48 UTC, abhinavmittal-harness approved these changes
> Reviewed 78 of 87 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51755)* status: 1 change requests. 17. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-25 07:50 UTC, puthrayaharness approved these changes

2023-08-25 07:59 UTC, merged