Rbac OPA
harness/harness-core pull request #51753
Opened 2023-08-17 10:05 UTC by yagyanshbhatia

## Describe your changes

- Onboarded OPA resources in resource groups
- Added permissions in a few managed roles

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-21 04:29 UTC, meenakshi-harness requested changes

2023-09-21 04:29 UTC, meenakshi-harness commented on 953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java
> +  public static final String OPA_GOVERNANCE_POLICYSET = "OPAPolicySet";
Should we rename to opaPolicy and opaPolicySet ?

2023-09-21 04:29 UTC, meenakshi-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +        - core_governancePolicySets_evaluate
increase version of this file.

2023-09-21 04:29 UTC, meenakshi-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml
> +      - core_governancePolicySets_view
same

2023-09-21 04:29 UTC, meenakshi-harness commented on platform-service/config/config.yml
> +opaClientConfig:
don't we need replace config for these?

2023-09-21 06:52 UTC, yagyanshbhatia commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml
> +      - core_governancePolicySets_view
done

2023-09-21 08:58 UTC, yagyanshbhatia commented on platform-service/config/config.yml
> +opaClientConfig:
yes, my bad, adding it

2023-09-21 09:02 UTC, yagyanshbhatia commented on 953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java
> +  public static final String OPA_GOVERNANCE_POLICYSET = "OPAPolicySet";
Done

2023-09-22 10:17 UTC, ashishsanodia-harness commented
*[`dockerization/platform-service/scripts/replace_configs.sh` line 436 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewNwet5AaIFyxTUeHP:-NewNwet5AaIFyxTUeHQ:b-j62xuu) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/dockerization/platform-service/scripts/replace_configs.sh#L436)):*
> ```Shell
> replace_key_value opaClientConfig.baseUrl "$OPA_SERVER_BASEURL"
> if [[ "" != "$OPA_CONNECT_TIMEOUT" ]]; then
>   replace_key_value opaClientConfig.connectTimeOutSeconds "$OPA_CONNECT_TIMEOUT"
> ```

Why empty check? 
replace_key_value already doing empty check before replacing value. 


<!-- Sent from Reviewable.io -->

2023-09-22 10:17 UTC, ashishsanodia-harness commented
*[`platform-service/build/container/scripts/replace_configs.sh` line 323 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewOA0O9fEBsDV9W3jO:-NewOA0O9fEBsDV9W3jP:b-j62xuu) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/build/container/scripts/replace_configs.sh#L323)):*
> ```Shell
> if [[ "" != "$OPA_READ_TIMEOUT" ]]; then
>   replace_key_value opaClientConfig.readTimeOutSeconds "$OPA_READ_TIMEOUT"
> fi
> ```

Why empty check? 
replace_key_value already doing empty check before replacing value. 


<!-- Sent from Reviewable.io -->

2023-09-22 10:17 UTC, ashishsanodia-harness commented
*[`platform-service/chart/templates/config.yaml` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewODWw4hY7fLoEmZ6r:-NewODWw4hY7fLoEmZ6s:b-u6tvs2) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/chart/templates/config.yaml#L30)):*
> ```YAML
>   { { - if .Values.global.opa.enabled } }
>   OPA_SERVER_BASEURL: 'http://policy-mgmt.{{ .Release.Namespace }}.svc.cluster.local:3000/'
>   OPA_SERVER_SECRET: "dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq"
> ```

how this secret will get override?


<!-- Sent from Reviewable.io -->

2023-09-22 10:19 UTC, ashishsanodia-harness commented
*[`platform-service/service/src/main/java/io/harness/platform/PlatformConfiguration.java` line 122 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewOauN9oWzZnZAMXk6:-NewOauN9oWzZnZAMXk7:b6hv1xa) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/service/src/main/java/io/harness/platform/PlatformConfiguration.java#L122)):*
> ```Java
>   @ConfigSecret private String policyManagerSecret;
>   private ServiceHttpClientConfig opaClientConfig;
>   @JsonProperty("enforcementClientConfiguration") private EnforcementClientConfiguration enforcementClientConfiguration;
> ```

No @JsonProperty mapped for these configurations?


<!-- Sent from Reviewable.io -->

2023-09-22 10:20 UTC, ashishsanodia-harness commented
*[`platform-service/service/src/main/java/io/harness/platform/PlatformConfiguration.java` line 121 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewOnmt5ujlpW468Nop:-NewOnmuAA2MC6mlJJwc:b6hv1xa) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/service/src/main/java/io/harness/platform/PlatformConfiguration.java#L121)):*
> ```Java
>   private AccessControlClientConfiguration accessControlClientConfig;
>   @ConfigSecret private String policyManagerSecret;
>   private ServiceHttpClientConfig opaClientConfig;
> ```

No @JsonProperty mapped for these configurations?


<!-- Sent from Reviewable.io -->

2023-09-22 10:20 UTC, ashishsanodia-harness commented
*[`platform-service/service/src/main/resources/localhost.pem` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewOrjJ5debhbl7pcOF:-NewOrjJ5debhbl7pcOG:bdfrdvi) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/service/src/main/resources/localhost.pem#L21)):*
> ```
> A59Y218O3g/9MH3UVc2J7UB68N41GzYxwjk7EQn6P10EaVUqTwtjXfAxEI84UXpj
> SBXC7VCUjCXqgsHIoGyWhBY70P04
> -----END CERTIFICATE-----
> ```

Why this file?


<!-- Sent from Reviewable.io -->

2023-09-25 05:46 UTC, arya-harness commented on platform-service/chart/templates/config.yaml
> +  { { - if .Values.global.opa.enabled } }
{ { .. } } will not render
use {{ - if .Values.global.opa.enabled }} instead. 
Please confirm by templating the charts by running `helm template .` on the charts directory(wherever the Chart.yaml reside)

2023-09-25 05:46 UTC, arya-harness commented on platform-service/chart/templates/config.yaml
> +  { { - end } }
same here

2023-09-25 05:46 UTC, arya-harness commented on platform-service/chart/values.yaml
> +  stackDriverLoggingEnabled: true
by default, please set it as false.

2023-09-25 05:51 UTC, arya-harness commented on platform-service/service/src/main/resources/localhost.pem
> +-----BEGIN CERTIFICATE-----
what is the requirement for this file? gitleaks might flag it later

2023-09-25 05:57 UTC, yagyanshbhatia commented
> _[`dockerization/platform-service/scripts/replace_configs.sh` line 436 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewNwet5AaIFyxTUeHP:-NewNwet5AaIFyxTUeHQ:b-j62xuu) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/dockerization/platform-service/scripts/replace_configs.sh#L436)):_
> 
> > ```shell
> > replace_key_value opaClientConfig.baseUrl "$OPA_SERVER_BASEURL"
> > if [[ "" != "$OPA_CONNECT_TIMEOUT" ]]; then
> >   replace_key_value opaClientConfig.connectTimeOutSeconds "$OPA_CONNECT_TIMEOUT"
> > ```
> 
> Why empty check? replace_key_value already doing empty check before replacing value.

Agreed. Removed the check!


> _[`platform-service/chart/templates/config.yaml` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewODWw4hY7fLoEmZ6r:-NewODWw4hY7fLoEmZ6s:b-u6tvs2) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/chart/templates/config.yaml#L30)):_
> 
> > ```yaml
> >   { { - if .Values.global.opa.enabled } }
> >   OPA_SERVER_BASEURL: 'http://policy-mgmt.{{ .Release.Namespace }}.svc.cluster.local:3000/'
> >   OPA_SERVER_SECRET: "dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq"
> > ```
> 
> how this secret will get override?

TODO



> _[`platform-service/service/src/main/java/io/harness/platform/PlatformConfiguration.java` line 122 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewOauN9oWzZnZAMXk6:-NewOauN9oWzZnZAMXk7:b6hv1xa) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/service/src/main/java/io/harness/platform/PlatformConfiguration.java#L122)):_
> 
> > ```java
> >   @ConfigSecret private String policyManagerSecret;
> >   private ServiceHttpClientConfig opaClientConfig;
> >   @JsonProperty("enforcementClientConfiguration") private EnforcementClientConfiguration enforcementClientConfiguration;
> > ```
> 
> No @JsonProperty mapped for these configurations?

No need. Default config is needed, and replace_config fills this default configuration.

> _[`platform-service/service/src/main/resources/localhost.pem` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/51753#-NewOrjJ5debhbl7pcOF:-NewOrjJ5debhbl7pcOG:bdfrdvi) ([raw file](https://github.com/harness/harness-core/blob/881f766598c545223a46d8c637f60e0b0b7b96d7/platform-service/service/src/main/resources/localhost.pem#L21)):_
> 
> > ```
> > A59Y218O3g/9MH3UVc2J7UB68N41GzYxwjk7EQn6P10EaVUqTwtjXfAxEI84UXpj
> > SBXC7VCUjCXqgsHIoGyWhBY70P04
> > -----END CERTIFICATE-----
> > ```
> 
> Why this file?

Without this file, the abstractHttpClient (OPA client) is unable to connect and fails with java cert error
Other examples are https://github.com/harness/harness-core/blob/develop/120-ng-manager/src/main/resources/localhost.pem and https://github.com/harness/harness-core/blob/develop/pipeline-service/service/src/main/resources/localhost.pem

2023-09-25 05:59 UTC, yagyanshbhatia commented on platform-service/service/src/main/resources/localhost.pem
> +-----BEGIN CERTIFICATE-----
Without this file, the abstractHttpClient (OPA client) is unable to connect and fails with java cert error
Other examples are https://github.com/harness/harness-core/blob/develop/120-ng-manager/src/main/resources/localhost.pem and https://github.com/harness/harness-core/blob/develop/pipeline-service/service/src/main/resources/localhost.pem

2023-09-25 06:01 UTC, yagyanshbhatia commented on platform-service/chart/values.yaml
> +  stackDriverLoggingEnabled: true
Done

2023-09-25 06:03 UTC, yagyanshbhatia commented on platform-service/chart/templates/config.yaml
> +  { { - end } }
okay

2023-09-25 06:05 UTC, yagyanshbhatia commented on platform-service/chart/templates/config.yaml
> +  { { - if .Values.global.opa.enabled } }
Done, thanks!

2023-09-25 06:09 UTC, arya-harness submitted a review, later dismissed

2023-09-25 06:21 UTC, yagyanshbhatia commented
trigger uts

2023-09-25 06:26 UTC, yagyanshbhatia commented
trigger uts

2023-09-25 09:45 UTC, yagyanshbhatia commented
trigger uts

2023-09-25 10:27 UTC, yagyanshbhatia commented
trigger uts

2023-09-25 10:43 UTC, yagyanshbhatia commented
trigger gitleaks, uts

2023-09-25 11:11 UTC, yagyanshbhatia commented
trigger uts

2023-09-25 11:15 UTC, yagyanshbhatia commented
git uts

2023-09-25 11:15 UTC, yagyanshbhatia commented
trigger uts

2023-10-09 12:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=51753) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=51753) before we can accept your contribution.<br/>**29** out of **33** committers have signed the CLA.<br/><br/>:white_check_mark: dhruv-harness<br/>:white_check_mark: vikyathharekal<br/>:white_check_mark: puthrayaharness<br/>:white_check_mark: abhinav-harness<br/>:white_check_mark: vigneswara-propelo<br/>:white_check_mark: pbarapatre10<br/>:white_check_mark: reetika04<br/>:white_check_mark: sourabh-awashti<br/>:white_check_mark: AnshuH<br/>:white_check_mark: n00bitax<br/>:white_check_mark: ricksjames<br/>:white_check_mark: Fernando-Dourado<br/>:white_check_mark: rafaelmart1ns<br/>:white_check_mark: jennyjames21<br/>:white_check_mark: nikunj-badjatya<br/>:white_check_mark: deepharness<br/>:white_check_mark: abosii-harness<br/>:white_check_mark: sahibaHarness<br/>:white_check_mark: prashantsharma04<br/>:white_check_mark: hingerabhinav<br/>:white_check_mark: tchaurasiya<br/>:white_check_mark: archit-harness<br/>:white_check_mark: sandeshsalunkhegh<br/>:white_check_mark: inderschera<br/>:white_check_mark: shivamnegi94<br/>:white_check_mark: nassergonzalez<br/>:white_check_mark: yagyanshbhatia<br/>:white_check_mark: arya-harness<br/>:white_check_mark: tmacari-harness<br/>:x: devesh-harness<br/>:x: Rakshitharness<br/>:x: sahithibanda01<br/>:x: bot-harness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=51753) it.</sub>

2023-10-10 06:43 UTC, closed without merging