fix: [CDS-77283]: Error message improvement for ecr
harness/harness-core pull request #51910
Opened 2023-08-22 12:14 UTC by vivekkarnatiharness

## Describe your changes
Have added exception handling for ecr registry based on error code.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-22 17:02 UTC, puthrayaharness requested changes

2023-08-22 17:02 UTC, puthrayaharness commented on 960-api-services/src/main/java/software/wings/service/impl/AwsApiHelperService.java
> +        throw NestedExceptionUtils.hintWithExplanationException(
If I understand correctly from your comments in Slack we only see the hint part. If that is the case, lets throw a regular exception instead of Hint/Explanation. The exception can be a single string that has both reason, explanation & hint as to what can be done to get rid of the message.

2023-08-22 17:02 UTC, puthrayaharness commented on 960-api-services/src/main/java/software/wings/service/impl/delegate/AwsEcrApiHelperServiceDelegate.java
> +  private void handleExceptionWhileFetchingRepositories(int code, String errormessage) {
Is this not duplicate from previous file? Can we make this static public method in one the classes & reuse?

2023-08-23 05:58 UTC, vivekkarnatiharness commented
trigger uts

2023-08-23 07:25 UTC, puthrayaharness approved these changes

2023-08-23 08:11 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-08-23 08:11 UTC, vivekkarnatiharness commented
trigger review

2023-08-23 08:46 UTC, merged