fix: [PL-40820]: Added new metric to record heartBeat data
harness/harness-core pull request #51939
Opened 2023-08-23 04:28 UTC by VikasMaddukuriHarness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-23 13:10 UTC, mdmilic requested changes
Can you add PR Description why are we doing this, also update JIRA ticket with some more details. 
I don't think it's a good idea to add this metric at all as it's going to cost a ton of $ and I don't see a clear reason for having it.
CC @raghuAtWings

2023-08-23 13:10 UTC, mdmilic commented on 400-rest/src/main/resources/metrics/metricGroups/heartbeat_metrics_group.yaml
> +  - lastHB
Why are we adding all these dimensions, many of them are discreet values so it doesn't make sense to have them and most of others are not relevant

2023-08-23 13:10 UTC, mdmilic commented on 420-delegate-service/src/main/java/io/harness/metrics/beans/HeartbeatMetricContext.java
> +@NoArgsConstructor
You don't need any of these annotations

2023-08-23 13:10 UTC, mdmilic commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java
> +            existingDelegate.isImmutable(), "50", "50", existingDelegate.getLastHeartBeat(), HEARTBEAT_RECEIVED);
You are adding dummy values 50, 50

2023-08-29 04:48 UTC, gn-harness approved these changes

2023-08-29 04:48 UTC, gn-harness commented on 400-rest/src/main/resources/metrics/metricGroups/heartbeat_metrics_group.yaml
> +  - lastHB
@mdmilic Are you saying we should not add columns like accountId, orgId as those would be fixed values for a delegateId?

We had earlier decided to go with the un-normalized view - as we are using managed prometheus and charged only by number of API calls, rather than the data. Google takes care of persisting, aggregation and queriying for us. Performance most likely would not be a concern here.

2023-08-29 14:58 UTC, mdmilic submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51939)* status: Some of the checks are too old. 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/resources/metrics/metricGroups/heartbeat_metrics_group.yaml` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/51939#gh-1302989999:-Nd0jfkK7BiVgqF70qDD:bent9xw) ([raw file](https://github.com/harness/harness-core/blob/771b32d494e1272362db7ccd4720b5721debf265/400-rest/src/main/resources/metrics/metricGroups/heartbeat_metrics_group.yaml#L17)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

@mdmilic Are you saying we should not add columns like accountId, orgId as those would be fixed values for a delegateId?

We had earlier decided to go with the un-normalized view - as we are using managed prometheus and charged only by number of API calls, rather than the data. Google takes care of persisting, aggregation and queriying for us. Performance most likely would not be a concern here. 
</blockquote></details>

I might not fully understand how the data works and where it's persisted with prometheus dashboards, but what I mentioned would apply for Stackdriver metrics, those are charged by data as well as requests. I'm assuming that we need to pay for some data storage somewhere. 

[Prometheus docs](https://prometheus.io/docs/practices/naming/) do also state this (similar to GCP docs as well):
`*CAUTION:* Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.`

So `accountId` is a good label to have, but most of the others are not. E.g. orgId, projId, delegateName, delegateId - all of these have high cardinality so are not good labels, cpu, mem, lastHb etc these are even discrete (e.g. no two values are the same) so are not good labels. 
The only others that could be used are `isNg`, `isImmutable` and potentially `delegateVersion` (low cardinality in observed time window). However, having too many labels for a single metric is also bad because of the same issue as having labels with large cardinality (you exponentially increase the data). Usually having up to 3-4 low cardinality labels is acceptable. 

In my opinion we should look into MongoDB streams to record/aggregate/process the data you are looking for and not prometheus metrics. 


<!-- Sent from Reviewable.io -->

2023-09-11 19:26 UTC, xingchi-jin commented
discussed over a zoom call. two things to add
1. Ring information.
2. add company name of an account
3. Since there will be multiple DB calls, it may hurt performance. We need to either put it in separate thread or cache the db results.

2023-09-13 19:23 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatMetricsHelper.java
> +  public List<String> getRingDetails(String ringName) {
why not just return DelegateRing ?

2023-09-13 19:32 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java
> +      List<String> accountInfo = delegateHeartBeatMetricsHelper.getAccountDetails(existingDelegate.getAccountId());
1. can we move all the codes of publishing metrics to DelegateHeartBeatMetricsHelper  ?

2. Given the fact that we are not able to test the metrics in pre-qa on GMP, it has to go to Qa and will auto promote to prod. Let's add a feature flag.
cc. @gn-harness @raghuAtWings

2023-09-13 19:36 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java
> +      List<String> accountInfo = delegateHeartBeatMetricsHelper.getAccountDetails(existingDelegate.getAccountId());
3. when it reaches QA, let's use the MockDelegate developed by @bharatgoelharness  to test with tens of thousands delegate installations.

2023-09-21 16:17 UTC, VikasMaddukuriHarness commented
trigger uts

2023-09-21 18:41 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java
> +          delegateHeartBeatMetricsHelper.addDelegateHeartBeatMetric(currentTime, existingDelegate.getAccountId(), orgId,
in this case, the metric is published twice. line 153 and line 162

2023-09-21 18:43 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatMetricsHelper.java
> +  public List<String> getAccountDetails(String accountId) {
make this private

2023-09-21 18:43 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartBeatMetricsHelper.java
> +  public DelegateRing getDelegateRing(String ringName) {
make this private

2023-09-21 18:43 UTC, xingchi-jin reviewed
LG after some minor comments

2023-09-22 04:22 UTC, VikasMaddukuriHarness commented
trigger uts

2023-09-22 04:38 UTC, VikasMaddukuriHarness commented
trigger ut4

2023-09-22 05:45 UTC, VikasMaddukuriHarness commented
trigger ut2,ut3,ut5

2023-09-22 16:09 UTC, VikasMaddukuriHarness commented
trigger uts

2023-09-22 17:27 UTC, VikasMaddukuriHarness commented
trigger ut5

2023-09-22 17:54 UTC, VikasMaddukuriHarness commented
trigger ut7,ut9

2023-09-22 19:13 UTC, VikasMaddukuriHarness commented
trigger commonchecks

2023-09-23 04:24 UTC, VikasMaddukuriHarness commented
trigger ut5,trigger checkstylecodeformat,commonchecks

2023-09-23 05:19 UTC, xingchi-jin approved these changes

2023-09-24 03:22 UTC, VikasMaddukuriHarness commented
trigger codebasehash,pmd,checkstylecodeformat,messagecheck

2023-09-24 10:38 UTC, VikasMaddukuriHarness commented
trigger uts

2023-09-24 12:00 UTC, VikasMaddukuriHarness commented
trigger ut7

2023-09-24 12:01 UTC, VikasMaddukuriHarness commented
trigger featurenamecheck

2023-09-25 03:27 UTC, xingchi-jin approved these changes

2023-09-25 03:40 UTC, merged