feat: [CDS-76194]: adding manifestInfo in StepInfo for Api usage
harness/harness-core pull request #51974
Opened 2023-08-23 14:31 UTC by TarunUba1

## Describe your changes
adding manifestInfo in stepInfo
## Testing
<img width="763" alt="Screenshot 2023-08-23 at 9 27 56 AM" src="https://github.com/harness/harness-core/assets/106597485/d9e96206-9aa4-435e-babb-392c7c94145c">
<img width="1019" alt="Screenshot 2023-08-23 at 9 32 06 AM" src="https://github.com/harness/harness-core/assets/106597485/e1987974-cd10-443c-bfa7-dcfbdad5f8fb">
<img width="666" alt="Screenshot 2023-08-23 at 9 38 44 AM" src="https://github.com/harness/harness-core/assets/106597485/1cb00aa8-a04d-4b3a-a43a-4edfd3510f88">
<img width="1101" alt="Screenshot 2023-08-23 at 11 36 14 AM" src="https://github.com/harness/harness-core/assets/106597485/d26fe5ba-93d8-4bf8-9f4e-517b587ed809">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-23 14:49 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/storeConfig/StoreConfig.java
> +  default void setManifestStoreInfo(ManifestStoreInfoBuilder manifestStoreInfoBuilder) {
Can we rename this to populateManifestStoreInfo?

2023-08-24 05:10 UTC, TarunUba1 commented
trigger uts

2023-08-24 05:53 UTC, GoelPratyush99 requested changes

2023-08-24 05:53 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +import graphql.VisibleForTesting;
Don't we use this package for VisibleForTesting 
`import com.google.common.annotations.VisibleForTesting;`

2023-08-24 05:53 UTC, GoelPratyush99 commented on 127-cd-nextgen-entities/src/main/java/io/harness/helper/ManifestStoreInfo.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_K8S})
Set unitCoverageRequired = false for entity class

2023-08-24 05:53 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/creator/CDNGModuleInfoProviderTest.java
> +import io.harness.cdng.manifest.yaml.*;
We should not using * for import

2023-08-24 05:53 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +    manifestStoreInfoBuilder.storeType(manifestStoreInfo.getStoreType());
Why does kustomizeManifest have chartName, chartVersion, subChartPath, helm version... type fields

2023-08-24 05:53 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +      manifestStoreInfoBuilder.folderPath(manifestStoreInfo.getFolderPath());
This if else seems to be wrong

1. I don't think the folder path for kustomize manifest can be empty.
2. The operationalPath/ overlayPath may/ may not be empty
3. In case, overlayPath/ OperationalPath is empty then we should use manifestStoreInfo.getFolderPath()
4. Otherwise the path to kustomization yaml becomes `manifestStoreInfo.getFolderPath() + overlayPath`

Please verify it according to your use case

2023-08-24 07:37 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/creator/CDNGModuleInfoProviderTest.java
> +import io.harness.cdng.manifest.yaml.*;
@TarunUba1 you can increase the value of this setting in IntelliJ to avoid this happening after optimizing imports 😄 
`Class count to use import with '*'`

2023-08-24 08:58 UTC, TarunUba1 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/creator/CDNGModuleInfoProviderTest.java
> +import io.harness.cdng.manifest.yaml.*;
thanks @abhinavsingh1196 , you are life saver

2023-08-24 10:15 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +      manifestStoreInfoBuilder.folderPath(manifestStoreInfo.getFolderPath());
i will just keep the code for safety purpose. It can not be null but just what if

2023-08-24 10:15 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +    manifestStoreInfoBuilder.storeType(manifestStoreInfo.getStoreType());
nice point

2023-08-24 10:16 UTC, TarunUba1 commented on 127-cd-nextgen-entities/src/main/java/io/harness/helper/ManifestStoreInfo.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_K8S})
aahhh nice

2023-08-24 10:16 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +import graphql.VisibleForTesting;
my bad, did the change

2023-08-24 10:16 UTC, TarunUba1 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/storeConfig/StoreConfig.java
> +  default void setManifestStoreInfo(ManifestStoreInfoBuilder manifestStoreInfoBuilder) {
done

2023-08-24 10:26 UTC, TarunUba1 commented
trigger uts

2023-08-25 07:50 UTC, abhinavsingh1196 commented
please put a more detailed description about this change

2023-08-25 08:14 UTC, abhinavsingh1196 requested changes

2023-08-25 08:14 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +        return manifestStoreInfo;
in case of multiple outcomes present, we want to return the first info we can create?

2023-08-25 08:14 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +  @VisibleForTesting
this annotation is needed?

2023-08-25 08:18 UTC, abosii-harness requested changes

2023-08-25 08:18 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/HelmChartManifestOutcome.java
> +    manifestInfoBuilder.chartName(getParameterFieldValue(this.getChartName()));
We should rely first on the HelmChartOutcome helm for chartName and chartVersion, only in case it it's null then we can fallback to manifest outcome itself. This will allow to get the chartName and chartVersion even for store types like Git, as this HelmChartOutcome is populated when fetchHelmChartMetadata is enabled and will get this information from Chart.yaml

2023-08-25 10:12 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +        return manifestStoreInfo;
Yes so like we will anyways only have one manifest for service that is important, either will be k8smanifest, helmchart, kustomize etc. we will configure a manifestStoreInfo in these cases only as we can only set one, the other manifest types like values patches, we dont need them so they will use the default function to return null

2023-08-25 10:14 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +  @VisibleForTesting
kinda wanted to test this function specifically but that is not required as i did changes and that function is now straigtforward, removing it

2023-08-25 11:32 UTC, abosii-harness requested changes

2023-08-25 11:32 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/HelmChartManifestOutcome.java
> +  public ManifestStoreInfo setManifestStoreInfo() {
please rename this to toManifestStoreInfo

2023-08-25 11:32 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ManifestOutcome.java
> +  default ManifestStoreInfo setManifestStoreInfo() {
nit: using Optional will be a better way to handle this

2023-08-25 11:32 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/helper/ManifestStoreInfo.java
> +public class ManifestStoreInfo {
Can we move this to package to other summaries beans? io.harness.cdng.pipeline.executions.beans

2023-08-25 14:29 UTC, abosii-harness submitted a review, later dismissed

2023-08-25 14:31 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +        return manifestStoreInfo;
what about multiple helm charts feature? 😄

2023-08-25 14:32 UTC, abhinavsingh1196 approved these changes

2023-08-25 15:07 UTC, abhinavsingh1196 approved these changes

2023-08-25 15:07 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/HelmChartManifestOutcome.java
> +    if (this.getHelm() != null) {
fully utilising getters :)

2023-08-25 15:51 UTC, TarunUba1 commented
trigger uts

2023-08-28 04:48 UTC, GoelPratyush99 submitted a review, later dismissed

2023-08-28 07:05 UTC, TarunUba1 commented
trigger uts

2023-08-28 07:25 UTC, TarunUba1 commented
trigger uts

2023-08-28 09:26 UTC, alebuh approved these changes

2023-08-28 09:32 UTC, abosii-harness requested changes

2023-08-28 09:32 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/KustomizeManifestOutcome.java
> +      ManifestStoreInfo manifestStoreInfo = manifestInfoBuilder.build();
Can't you just pass current builder so to not have to a copy of the existing populated data? This may results in some bugs, like adding a new field that would be removed if not added here as well

2023-08-28 09:32 UTC, abosii-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/CustomRemoteStoreConfig.java
> +    manifestStoreInfoBuilder.extractionScript(getParameterFieldValue(this.getExtractionScript()));
Let's not include extraction script

2023-08-28 13:12 UTC, GoelPratyush99 approved these changes

2023-08-28 13:53 UTC, abosii-harness submitted a review, later dismissed

2023-08-28 13:53 UTC, TarunUba1 commented
trigger ut1

2023-08-28 13:54 UTC, TarunUba1 commented
trigger review

2023-08-28 13:55 UTC, TarunUba1 commented
trigger messagecheck

2023-08-28 13:57 UTC, TarunUba1 commented
trigger messagecheck

2023-08-28 14:44 UTC, TarunUba1 commented
trigger checkstylecodeformat

2023-08-28 14:54 UTC, yogesh-chauhan approved these changes
Approving as code owner for alias.txt

2023-08-28 14:56 UTC, GoelPratyush99 approved these changes

2023-08-28 14:56 UTC, TarunUba1 commented
trigger review

2023-08-28 15:02 UTC, merged