feat:[SSCA-372]: Added Upload and Download Sbom in SSCA-Manager
harness/harness-core pull request #52039
Opened 2023-08-24 19:57 UTC by arpit-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-25 03:44 UTC, inderschera commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +  '/v1/{artifactId}/step-executions/{stepExecutionId}':
This endpoint doesn't look right.
Probably should be /v1/org/{org}/project/{project}/orchestration/{orchestration-id}/sbom-download

2023-08-28 05:33 UTC, arpit-harness commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +  '/v1/{artifactId}/step-executions/{stepExecutionId}':
Fixed

2023-08-28 05:34 UTC, arpit-harness commented
trigger uts

2023-08-28 06:36 UTC, inderschera commented on ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java
> +  Optional<ArtifactEntity> findFirstByUrlLike(String url, Sort sort);
What does this method do?

2023-08-28 06:56 UTC, inderschera commented on ssca-manager/config/ssca-manager-config.yml
> +s3Config:
@deepharness Should we change it to gcpConfig? Since it's specific to gcp right now?

2023-08-28 06:57 UTC, inderschera commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +      operationId: sbom
let's change the operationid to downloadsbom

2023-08-28 06:57 UTC, inderschera commented on ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java
> +  public File DownloadSBOMToGCP(ArtifactEntity artifactEntity) {
nit: rename downloadSBOM

2023-08-28 06:59 UTC, inderschera commented on ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java
> +        byte[] buffer = new byte[4096];
Isn't 4096 bytes too small? Is there a way to file size before downloading the file? If not, let's increase it to maybe 15MB and put this as a constant in this file. 
Also, what happens if this buffer size is crossed? What exception do we get then? Can we catch and log the exception in that case?

2023-08-28 07:00 UTC, inderschera commented on ssca-manager/service/src/main/java/io/harness/ssca/services/OrchestrationStepServiceImpl.java
> +  public String sbom(String accountId, String orgIdentifier, String projectIdentifier, String orchestrationId) {
nit: rename method to downloadSbom

2023-08-28 07:24 UTC, deepharness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52039)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/config/ssca-manager-config.yml` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/52039#gh-1306989071:-NcuwhxFCTRcEeR1_ZQf:b-78x3xo) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/config/ssca-manager-config.yml#L51)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

@deepharness Should we change it to gcpConfig? Since it's specific to gcp right now?
</blockquote></details>

No , it should be s3 as s3 is a standard now , not specific to aws. For SMP we will use s3 compatible in-cluster minio bucket.
___
*[`ssca-manager/contracts/openapi/v1/openapi.yaml` line 385 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncv0l0F9rOTjq9rZ0_b:-Ncv0aZSBafm_goj1PsI:bc1vgp9) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/contracts/openapi/v1/openapi.yaml#L385)):*
> ```YAML
>       type: object
>       properties:
>         sbom:
> ```

Can we call it sbomUrl?



_Code quote:_
```YAML
sbom
```
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-NcuyI1t9omjJnnsDWfG:-NcuyI1t9omjJnnsDWfH:b-9vu82s) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L33)):*
> ```Java
> 
> @Slf4j
> public class S3Store {
> ```

Can we use Interface for this , as underlaying layer has specific implementation , we need to mock it for UT , everywhere else
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncuyj7v-I3VReZ2_oB_:-Ncuyj7v-I3VReZ2_oBa:b-zf1opm) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L36)):*
> ```Java
>   @Inject S3Config s3Config;
> 
>   public AmazonS3 newS3Client() {
> ```

Why is it public ?
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-NcuzG7U8QMj1LG0Bo9P:-NcuzG7U8QMj1LG0Bo9Q:b-myphgm) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L45)):*
> ```Java
>   }
> 
>   public void UploadSBOMToGCP(File file, String accountId, String orgIdentifier, String projectIdentifier,
> ```

no GCP
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-NcuzD6mEtVdm9IUyjq8:-NcuzD6mEtVdm9IUyjq9:bmm9xtl) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L47)):*
> ```Java
>   public void UploadSBOMToGCP(File file, String accountId, String orgIdentifier, String projectIdentifier,
>       SbomProcessRequestBody sbomProcessRequestBody) {
>     AmazonS3 s3Client = newS3Client();
> ```

Also we should keep the client as client normally comes with connection pooling , its good to keep the same client instance for all the call.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncv-Ms705JoEEUM7FH2:-Ncv-Ms705JoEEUM7FH3:b-cqu831) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L49)):*
> ```Java
>     AmazonS3 s3Client = newS3Client();
>     try {
>       String s3FilePath = getSBOMGCSFolder(accountId, orgIdentifier, projectIdentifier,
> ```

to avoid duplication , create getSBOMGCSFolder(Artifact ) method
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/52039#gh-1306991770:-Ncuzpiv1IDNyfyojfWg:bjnk5yi) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L75)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Isn't 4096 bytes too small? Is there a way to know file size before downloading the file? If not, let's increase it to maybe 15MB and put this as a constant in this file. 
Also, what happens if this buffer size is crossed? What exception do we get then? Can we catch and log the exception in that case?
</blockquote></details>


 size = s3Object.getObjectMetadata().getContentLength();
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncv-2oz3OGMScyIk9hw:-Ncv-2oz3OGMScyIk9hx:b-myphgj) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L89)):*
> ```Java
>   }
> 
>   private String getSBOMGCSFolder(String accountId, String orgIdentifier, String projectIdentifier,
> ```

no GCS


<!-- Sent from Reviewable.io -->

2023-08-28 14:29 UTC, arpit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52039)* status: 18 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/config/ssca-manager-config.yml` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/52039#gh-1306989071:-NcwCYGz3IXHcUtvHdJh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/config/ssca-manager-config.yml#L51)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

No , it should be s3 as s3 is a standard now , not specific to aws. For SMP we will use s3 compatible in-cluster minio bucket.
</blockquote></details>

Done.
___
*[`ssca-manager/contracts/openapi/v1/openapi.yaml` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/52039#gh-1306989669:-NcwCnmLDElACFi_ie6i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/contracts/openapi/v1/openapi.yaml#L99)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

let's change the operationid to downloadsbom
</blockquote></details>

Done.
___
*[`ssca-manager/contracts/openapi/v1/openapi.yaml` line 385 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncv0l0F9rOTjq9rZ0_b:-NcwCrFgCzPkVU2KJjtj:b-em0qux) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/contracts/openapi/v1/openapi.yaml#L385)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Can we call it sbomUrl?
</blockquote></details>

Its not actually a url, Its the sbom jsom string.
___
*[`ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/52039#gh-1306971586:-NcwD24P3o_Aj4O0yrs2:b4wu9qh) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/repositories/ArtifactRepositoryCustom.java#L20)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

What does this method do?
</blockquote></details>

Get the first artifact entity with given "url" and based will records are ordered as per "sort"
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-NcuyI1t9omjJnnsDWfG:-NcwHAcN4myaaHbc7qg2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L33)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Can we use Interface for this , as underlaying layer has specific implementation , we need to mock it for UT , everywhere else
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncuyj7v-I3VReZ2_oB_:-NcwHD3196FaTWY9xTkV:bktvxrl) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L36)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why is it public ?
</blockquote></details>

Moved it to a singleton binding in SSCAManagerModule
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-NcuzG7U8QMj1LG0Bo9P:-NcwHMdA6aj-orYdQtO2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L45)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

no GCP
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-NcuzD6mEtVdm9IUyjq8:-NcwHQTt7ZhBuLXYA3rv:bktvxrl) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L47)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Also we should keep the client as client normally comes with connection pooling , its good to keep the same client instance for all the call.
</blockquote></details>

Moved it to a singleton binding in SSCAManagerModule
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncv-Ms705JoEEUM7FH2:-NcwV0LLASbc9EsXw-6G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L49)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

to avoid duplication , create getSBOMGCSFolder(Artifact ) method
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/52039#gh-1306991770:-NcwYAsh0O0EKnKyNwCz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L75)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

size = s3Object.getObjectMetadata().getContentLength();
</blockquote></details>

Done.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/52039#-Ncv-2oz3OGMScyIk9hw:-NcwYBkW7NB4KuBZ_72Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/754b247313ce18fb7c47ccb59db0d1932cb27dd6/ssca-manager/service/src/main/java/io/harness/ssca/s3/S3Store.java#L89)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

no GCS
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-28 14:44 UTC, arpit-harness commented
trigger uts

2023-08-28 16:07 UTC, arpit-harness commented
trigger ut5

2023-08-28 18:48 UTC, deepharness approved these changes
> Reviewed 4 of 14 files at r1, 4 of 10 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52039)* status: 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-08-28 20:56 UTC, arpit-harness commented
trigger ut5

2023-08-29 05:03 UTC, mankrit-singh approved these changes

2023-08-29 05:10 UTC, merged