feat: [PLG-2233] Add release version support for STO
harness/harness-core pull request #52046
Opened 2023-08-25 01:46 UTC by neelam-harness

## Describe your changes
1. Added support for fetching the STO version number in Release Notes
2. Refactoring the code by adding switch-case instead of if-else cases and error handling with try-catch blocks

Tested locally:
1. Ran the sto-core server locally by following https://github.com/harness/sto-core#readme 
2. successfully GET request locally to get the version in the response
<img width="1094" alt="image" src="https://github.com/harness/harness-core/assets/117125370/84550bc6-2f4d-4651-bcb6-9c3cc2ef2270">
3. Updated the moduleVersionInfo collection's document for STO as follows:
<img width="1493" alt="image" src="https://github.com/harness/harness-core/assets/117125370/d02041b4-4e0f-448a-a482-b96cea55cdda">

Note:
Gotchas for running the postgres in local for sto-core
1. `docker pull postgres:14.4`
2. `docker run -d --name postgresSto -p 5432:5432 -e POSTGRES_PASSWORD=sto_local postgres:14.4`
3. `docker exec postgresSto sh -c 'echo "DO \$\$ BEGIN IF NOT EXISTS(SELECT schema_name FROM information_schema.schemata WHERE schema_name = '"'"'sto'"'"') THEN EXECUTE '"'"'CREATE SCHEMA sto'"'"'; END IF; END \$\$ ;" | psql postgres://postgres:sto_local@localhost:5432/'`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-25 07:14 UTC, kapil-harness requested changes

2023-08-25 07:14 UTC, kapil-harness commented on 120-ng-manager/config.yml
> +stoClientConfig:
lets add its corresponding replace_configs too
`dockerization/ng-manager/scripts/replace_configs.sh`

Also, add these configs in all the envs in ng-prod-manifest

2023-08-25 08:59 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52046)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-NcfuRbl87ARpqJfX0xQ:-NcfuRbl87ARpqJfX0xR:bwkcsiz) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L104)):*
> ```Java
> 
>   private String getBaseUrl(String moduleName) throws IOException {
>     String finalBaseUrl = "";
> ```

we don't need to create string here and then return later, each switch case can independently return



_Code snippet:_
```Java
software.wings.beans.loginSettings.outbox.LoginSettingsOutboxEventHandler#handle
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-NcfujU3D82m00Mu03qe:-NcfujU3D82m00Mu03qf:b-k2m2hv) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L105)):*
> ```Java
>   private String getBaseUrl(String moduleName) throws IOException {
>     String finalBaseUrl = "";
>     try {
> ```

try catch is not required here
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-Ncfuek04O5fBp09HoHI:-Ncfuek04O5fBp09HoHJ:bdwpolg) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L106)):*
> ```Java
>     String finalBaseUrl = "";
>     try {
>       if (PLATFORM.equals(moduleName)) {
> ```

why is this not part of the switch case?
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 214 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-NcfupzsDPUmZZ9eQwUm:-Ncfupzt0HzU0aJktoXF:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L214)):*
> ```Java
>     JSONObject jsonObject = new JSONObject(responseString);
>     
>     String finalVersion = "";
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-08-25 17:07 UTC, r0610205 commented on 120-ng-manager/config.yml
> +stoClientConfig:
And to corresponding helm chart

2023-08-25 17:18 UTC, r0610205 commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java
> +        case STO:
We have two components in STO, STO Manager & STO Core, we only pulling one version?

2023-08-29 00:59 UTC, neelam-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52046)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/52046#gh-1305263274:-Ncyj6g246hsKNtyHPCj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/config.yml#L145)):*
<details><summary><i>Previously, r0610205 (Sergey Bobrov) wrote…</i></summary><blockquote>

And to corresponding helm chart 
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-NcfuRbl87ARpqJfX0xQ:-NciBrZ33fPUOc9vfbfq:b-oqdfl8) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L104)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

we don't need to create string here and then return later, each switch case can independently return
</blockquote></details>

Both approaches work fine imho. The rationale for creating string here was to return `empty` in the end if none of the cases matched and populated an appropriate baseUrl. Can just do an early return. Thanks
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-NcfujU3D82m00Mu03qe:-NciHelL7iXWk8YpzNvF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L105)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

try catch is not required here
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-Ncfuek04O5fBp09HoHI:-NciCYkqDhOrY1gjrKpp:b-21rubv) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L106)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why is this not part of the switch case?
</blockquote></details>

because it's a special case and is not an independent moduleType so keeping it separate . https://github.com/harness/harness-core/blob/c417ccf6457af91a1dd38e0b646a21b3ef2eb2db/970-ng-commons/src/main/java/io/harness/entities/ModuleType.java#L26 
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/52046#gh-1305937095:-NcyjRhR5R52gskBpBZp:bj4q61s) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L132)):*
<details><summary><i>Previously, r0610205 (Sergey Bobrov) wrote…</i></summary><blockquote>

We have two components in STO, STO Manager & STO Core, we only pulling one version?
</blockquote></details>

Yes that's right. As per guideline from product we are only pulling version for STO Core. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 214 at r1](https://reviewable.io/reviews/harness/harness-core/52046#-NcfupzsDPUmZZ9eQwUm:-NcijqfN7y3PFE4cEzOh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6025f3e3e6de2150c08cff46fd667858950ef528/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L214)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-29 01:10 UTC, neelam-harness commented on 120-ng-manager/config.yml
> +stoClientConfig:
Added. Creating a separate PR for the ng-prod-manifest change. Thanks for pointing this out!

2023-08-29 02:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=52046) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=52046) before we can accept your contribution.<br/>**51** out of **55** committers have signed the CLA.<br/><br/>:white_check_mark: neelam-harness<br/>:white_check_mark: rathodmeetsatish<br/>:white_check_mark: shalini-agr<br/>:white_check_mark: adivishy1<br/>:white_check_mark: archit-harness<br/>:white_check_mark: hextechpal<br/>:white_check_mark: trunapushpa<br/>:white_check_mark: senjucanon2<br/>:white_check_mark: vikyathharekal<br/>:white_check_mark: bharatgoelharness<br/>:white_check_mark: lovish1999<br/>:white_check_mark: ashishsanodia-harness<br/>:white_check_mark: markoharness<br/>:white_check_mark: utkarshchoubey-harness<br/>:white_check_mark: piyush-bhuwalka<br/>:white_check_mark: tmacari-harness<br/>:white_check_mark: Y0709<br/>:white_check_mark: RishabhGupta34<br/>:white_check_mark: brijeshdhakar<br/>:white_check_mark: sarthakkasat<br/>:white_check_mark: Fernando-Dourado<br/>:white_check_mark: vigneswara-propelo<br/>:white_check_mark: lasdox<br/>:white_check_mark: smjt-h<br/>:white_check_mark: TarunUba1<br/>:white_check_mark: jennyjames21<br/>:white_check_mark: sathish-soundarapandian<br/>:white_check_mark: yogesh-chauhan<br/>:white_check_mark: shivamnegi94<br/>:white_check_mark: sandeshsalunkhegh<br/>:white_check_mark: jamie-harness<br/>:white_check_mark: shash-harness<br/>:white_check_mark: namantalaycha10<br/>:white_check_mark: avaakash<br/>:white_check_mark: reetika04<br/>:white_check_mark: sourabh-awashti<br/>:white_check_mark: ankittiwari-harness<br/>:white_check_mark: raghavharness<br/>:white_check_mark: naman-goenka<br/>:white_check_mark: sahilhindwani-harness<br/>:white_check_mark: VikasMaddukuriHarness<br/>:white_check_mark: n00bitax<br/>:white_check_mark: inderschera<br/>:white_check_mark: tiwaritejas<br/>:white_check_mark: karansaraswat19<br/>:white_check_mark: yagyanshbhatia<br/>:white_check_mark: abhinavmittal-harness<br/>:white_check_mark: anilchowdhury-harness<br/>:white_check_mark: kapil-harness<br/>:white_check_mark: Vbhatia20<br/>:white_check_mark: arya-harness<br/>:x: devesh-harness<br/>:x: bot-harness<br/>:x: RajBaviskar<br/>:x: ayushitiwari024<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=52046) it.</sub>

2023-09-01 19:21 UTC, closed without merging