feat:[CDS-77683]: Adding delegate capability for PT tasks
harness/harness-core pull request #52067
Opened 2023-08-25 09:56 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-25 10:09 UTC, sourabh-awashti commented
trigger uts

2023-08-25 10:20 UTC, RishabhGupta34 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/info/CustomDeploymentServerInstanceInfo.java
> +  private Set<String> delegateSelectors;
can we confirm one thing.. is the service dashboard working fine for the instances which didn't had this info previously? as we added a new field in the instance info

2023-08-25 11:10 UTC, sourabh-awashti commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/info/CustomDeploymentServerInstanceInfo.java
> +  private Set<String> delegateSelectors;
yes i checked, we are getting delegateSelectors as extra field in server instance info for ourput

2023-08-25 11:43 UTC, sourabh-awashti commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/info/CustomDeploymentServerInstanceInfo.java
> +  private Set<String> delegateSelectors;
I checked it @RishabhGupta34 , it is working fine in local

2023-08-25 11:45 UTC, sourabh-awashti commented
trigger uts

2023-08-25 12:29 UTC, yogesh-chauhan requested changes

2023-08-28 12:04 UTC, RishabhGupta34 approved these changes

2023-08-30 05:11 UTC, sourabh-awashti commented
trigger uts

2023-09-04 05:11 UTC, yogesh-chauhan approved these changes

2023-09-04 05:11 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/customDeployment/FetchInstanceScriptStep.java
> +    List<String> selectors = new ArrayList<>();
nit: we can use streaming to make this better readability

2023-09-04 16:25 UTC, sourabh-awashti commented
trigger  review

2023-09-04 16:25 UTC, sourabh-awashti commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/customDeployment/FetchInstanceScriptStep.java
> +    List<String> selectors = new ArrayList<>();
done

2023-09-04 16:28 UTC, sourabh-awashti commented
trigger uts

2023-09-05 05:00 UTC, sourabh-awashti commented
trigger uts

2023-09-05 05:39 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 13 files at r2, 19 of 20 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52067)* status: 24 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-05 05:39 UTC, sourabh-awashti commented
trigger review

2023-09-05 05:39 UTC, sourabh-awashti commented
trigger messagecheck

2023-09-05 05:40 UTC, sourabh-awashti commented
trigger messagecheck

2023-09-05 05:41 UTC, RishabhGupta34 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/CustomDeploymentOutcomeMetadata.java
> +public class CustomDeploymentOutcomeMetadata extends DeploymentOutcomeMetadata {
can we also use type alias? Because without that it stores the whole class name in mongodb, which creates issue if we want to move it to another package. 
You can confirm once what's being stored in the db with these changes

2023-09-05 06:22 UTC, sourabh-awashti commented
trigger uts

2023-09-05 06:22 UTC, sourabh-awashti commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/CustomDeploymentOutcomeMetadata.java
> +public class CustomDeploymentOutcomeMetadata extends DeploymentOutcomeMetadata {
done

2023-09-05 06:30 UTC, RishabhGupta34 approved these changes

2023-09-05 06:48 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52067)* status: 23 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-05 06:57 UTC, harshjain12 approved these changes

2023-09-05 06:58 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52067)* status: 23 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-05 06:58 UTC, sourabh-awashti commented
trigger review

2023-09-05 07:00 UTC, merged