fix: [CDS-77759]: log the errormessage as a warning in case the jira …
harness/harness-core pull request #52130
Opened 2023-08-28 10:56 UTC by abhinavmittal-harness

…approval step does not fail

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-28 10:58 UTC, abhinavmittal-harness commented
trigger uts

2023-08-28 12:36 UTC, Fernando-Dourado requested changes
@abhinavmittal-harness: Instead of changing every exception to a warning, let's identify the exception's pattern and add it to the `isWarningException` method.

2023-08-28 13:28 UTC, naman-goenka approved these changes

2023-08-28 13:29 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/software/wings/delegatetasks/jira/JiraTask.java
> +        log.warn(errorMessage, e);
Can we add that exception so that isWarningException returns true for TooManyRequests

2023-08-28 13:29 UTC, naman-goenka reviewed
Added comment

2023-08-28 18:04 UTC, rafaelmart1ns submitted a review, later dismissed

2023-08-28 19:41 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52130)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/jira/JiraTask.java` line 901 at r1](https://reviewable.io/reviews/harness/harness-core/52130#gh-1307428239:-NcxebZj9k5ASeCm2oXD:bpfrl3c) ([raw file](https://github.com/harness/harness-core/blob/76fdc2a6ad25d61c23ed113bbe65cc207996e051/930-delegate-tasks/src/main/java/software/wings/delegatetasks/jira/JiraTask.java#L901)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

Can we add that exception so that isWarningException returns true for TooManyRequests
</blockquote></details>

The reason I was thinking of not doing so is because if we are not going to fail the step, it is always going to be logged as an error and it will keep repeating in subsequent iterations of the polling job


<!-- Sent from Reviewable.io -->

2023-08-28 20:36 UTC, Fernando-Dourado commented
> error logs are expected because one of the cust

@abhinavmittal-harness I still don't agree with changing every exception from Jira integration to a warning. We should only change the `TooManyRequest` exception to warn and leave others as errors without any side effects.

Please, share the log link where is possible to identify that case.

We can jump on a call and discuss more if you need.

2023-08-29 20:21 UTC, abhinavmittal-harness reviewed
So the reasoning behind of shifting from warning to error was that when we don't fail the step then why log it as an error.
Discussed with @Fernando-Dourado and we seem to allign that it can be a valid behaviour in ng but to keep changes minimum in cg we won't be doing so and just moving 429 status to warning.
If it comes up again we will go ahead and move them as we were planning previously

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52130#-:-Nd1wox8AoiD3_gfdUF9:byg2oiz)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-08-29 22:21 UTC, Fernando-Dourado approved these changes

2023-08-29 22:21 UTC, Fernando-Dourado commented
trigger uts

2023-08-30 13:23 UTC, naman-goenka approved these changes

2023-08-30 13:24 UTC, rafaelmart1ns approved these changes

2023-08-30 13:24 UTC, abhinavmittal-harness commented
trigger review

2023-08-30 13:30 UTC, merged