feat:[PLG-2233] Add release version support for STO
harness/harness-core pull request #52158
Opened 2023-08-29 03:25 UTC by neelam-harness

## Describe your changes
1. Added support for fetching the STO version number in Release Notes
2. Refactoring the code by adding switch-case instead of if-else cases and error handling with try-catch blocks

Tested locally:
1. Ran the sto-core server locally by following https://github.com/harness/sto-core#readme 
2. successfully GET request locally to get the version in the response
<img width="1094" alt="image" src="https://github.com/harness/harness-core/assets/117125370/84550bc6-2f4d-4651-bcb6-9c3cc2ef2270">
3. Updated the moduleVersionInfo collection's document for STO as follows:
<img width="1493" alt="image" src="https://github.com/harness/harness-core/assets/117125370/d02041b4-4e0f-448a-a482-b96cea55cdda">

Note:
Gotchas for running the postgres in local for sto-core
1. `docker pull postgres:14.4`
2. `docker run -d --name postgresSto -p 5432:5432 -e POSTGRES_PASSWORD=sto_local postgres:14.4`
3. `docker exec postgresSto sh -c 'echo "DO \$\$ BEGIN IF NOT EXISTS(SELECT schema_name FROM information_schema.schemata WHERE schema_name = '"'"'sto'"'"') THEN EXECUTE '"'"'CREATE SCHEMA sto'"'"'; END IF; END \$\$ ;" | psql postgres://postgres:sto_local@localhost:5432/'`
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-29 09:31 UTC, kapil-harness requested changes

2023-08-29 18:17 UTC, neelam-harness commented on 120-ng-manager/config.yml
> +stoCoreClientConfig:
Raised a pr here: https://github.com/wings-software/ng-prod-manifests/pull/4138

2023-08-29 20:12 UTC, mohitg0795 commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java
> +          log.error("Encountered an exception while trying to get the baseURL for module: {}",
we should log some different error message here so that we clearly know that it was this particular case of exception. Also we should log the exception.

2023-08-29 20:13 UTC, mohitg0795 commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java
> +          throw new UnexpectedException("Update VersionInfo Task Sync job interrupted:" + e);
I don't know if this is right to pass the exception itself in the message. It may leak unrequired details to some user facing screens.

2023-09-01 13:33 UTC, r0610205 commented on 120-ng-manager/chart/templates/config.yaml
> +  STO_CORE_SERVICE_CLIENT_BASEURL: http://sto-core:4000/api/v2/system/
Should just be http://sto-core:4000/api

2023-09-01 19:00 UTC, mohitg0795 approved these changes

2023-09-01 19:02 UTC, r0610205 commented on 120-ng-manager/config.yml
> +  baseUrl: ${STO_CORE_SERVICE_BASE_URL:-http://localhost:4000/api}/v2/system/
${STO_CORE_SERVICE_BASE_URL:-http://localhost:4000/api/}v2/system/

2023-09-01 19:04 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52158)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/52158#-Nd1tpuB6tYF1VG_0SNp:-Nd1tpuB6tYF1VG_0SNq:b8up2b0) ([raw file](https://github.com/harness/harness-core/blob/d4278dd42ce581d1eb4a58377bfa57ecebd03622/120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java#L90)):*
> ```Java
>           moduleVersionInfo.setVersion(latestVersion);
>         } catch (InvalidRequestException e) {
>           log.error("Encountered an exception while trying to get the baseURL for module: {}",
> ```

we should log some different error message here otherwise


<!-- Sent from Reviewable.io -->

2023-09-01 19:17 UTC, mohitg0795 submitted a review, later dismissed

2023-09-01 19:28 UTC, neelam-harness commented
trigger uts

2023-09-01 19:37 UTC, neelam-harness commented
trigger codebasehash

2023-09-01 19:38 UTC, neelam-harness commented
trigger messagecheck

2023-09-01 19:42 UTC, kapil-harness requested changes

2023-09-01 19:42 UTC, kapil-harness commented on dockerization/ng-manager/scripts/replace_configs.sh
> -
@neelam-harness lets not change anything in a file where you have not made any changes e.g. newline or omitting a newline

2023-09-01 19:42 UTC, kapil-harness commented on 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java
> +        } catch (IOException e) {
so many catch clauses are unnecessary, the methods that you are calling inside this try clause are handling the specific exceptions, so here you just need to catch one general Exception
`} catch (Exception ex) {
      log.error("Failed to send ci_build_credits_provisioned telemetry event for account: {} and creditID: {}",
          ciCredit.getAccountIdentifier(), ciCredit.getUuid(), ex);
    }`

2023-09-01 20:31 UTC, kapil-harness approved these changes

2023-09-01 20:49 UTC, r0610205 approved these changes

2023-09-04 22:35 UTC, neelam-harness commented
trigger review

2023-09-04 22:36 UTC, neelam-harness commented
trigger uts

2023-09-05 04:10 UTC, merged