feat: [CDS-77254]: Fetch Helm Chart Version for OCI Helm ECR config type
harness/harness-core pull request #52227
Opened 2023-08-30 04:08 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-30 04:19 UTC, GoelPratyush99 commented
trigger uts

2023-08-30 04:33 UTC, GoelPratyush99 commented
trigger uts

2023-08-30 05:16 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java
>        OciHelmDockerApiListTagsTaskParams ociHelmDockerApiListTagsTaskParams =
Can we instead use a different task to fetch the aws tags? I believe this will help us in:
1. Making the code more clean, at least on the delegate side (we can refactor manager later)
2. Allow us to identify if delegate support fetching oci ecr tags and prevent some unexpected errors due to older versions of delegate

2023-08-30 06:23 UTC, GoelPratyush99 commented
trigger uts

2023-08-31 10:46 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/HelmChartServiceImpl.java
>        OciHelmDockerApiListTagsTaskParams ociHelmDockerApiListTagsTaskParams =
Done

2023-08-31 10:46 UTC, GoelPratyush99 commented
trigger uts

2023-09-04 07:43 UTC, GoelPratyush99 commented
trigger uts

2023-09-04 07:48 UTC, abosii-harness requested changes

2023-09-04 07:48 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java
> +  private ConnectorConfigDTO connectorConfigDTO;
let's divide the task parameters also

2023-09-04 07:48 UTC, abosii-harness commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  OCI_HELM_ECR_CONFIG_DOCKER_API_LIST_TAGS_TASK_NG(
Let's rename this to ECR_HELM_API_LIST_TAGS_TASK

2023-09-04 16:42 UTC, GoelPratyush99 commented
trigger uts

2023-09-04 16:42 UTC, GoelPratyush99 commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  OCI_HELM_ECR_CONFIG_DOCKER_API_LIST_TAGS_TASK_NG(
Done

2023-09-04 16:42 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java
> +  private ConnectorConfigDTO connectorConfigDTO;
Done

2023-09-04 18:03 UTC, GoelPratyush99 commented
trigger uts

2023-09-05 06:53 UTC, GoelPratyush99 commented
trigger uts

2023-09-05 07:00 UTC, GoelPratyush99 commented
trigger messagecheck

2023-09-05 07:05 UTC, GoelPratyush99 commented
trigger messagecheck

2023-09-05 07:18 UTC, GoelPratyush99 commented
trigger codebasehash

2023-09-05 07:20 UTC, GoelPratyush99 commented
trigger pmd

2023-09-05 07:36 UTC, GoelPratyush99 commented
trigger uts

2023-09-05 08:52 UTC, GoelPratyush99 commented
trigger uts

2023-09-05 09:14 UTC, GoelPratyush99 commented
trigger ut2

2023-09-05 10:20 UTC, GoelPratyush99 commented
trigger ut2

2023-09-05 16:16 UTC, abosii-harness requested changes

2023-09-05 16:16 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/aws/AwsClientImpl.java
> +    return repository != null ? repository.getRepositoryUri() : null;
Should we instead throw an error saying that unable to find repository for region, registry and image name?

2023-09-05 16:16 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/aws/AwsClientImpl.java
> +    return repository != null ? repository.getRepositoryUri() : null;
Otherwise let's use Optional instead of returning null (still this case should be handled at some point of time, it's not valid if the repository url is null)

2023-09-05 16:16 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    String[] usernamePassword = new String(
Is this operation really required? From my understanding you're already getting the credentials in basic format

2023-09-05 16:16 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +  private String getApiListTagsForEcrOciHelmConfig(
The method name is confusing, you're actually returning credentials

2023-09-05 16:16 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +        Base64.decode(awsClient.getAmazonEcrAuthToken(awsConfig, account, ecrHelmApiListTagsTaskParams.getRegion())))
Should we think about this more? Like add some caching, etc? We may ending up in calling this multiple times and generating a new token that lives for 12 hours doesn't really make sense I guess

2023-09-05 16:16 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java
> +  private ConnectorConfigDTO connectorConfigDTO;
Is this parameter still required?

2023-09-05 16:16 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java
> +        ociHelmConnector != null ? ociHelmConnector : connectorConfigDTO, maskingEvaluator);
is this check still required?

2023-09-05 16:16 UTC, abosii-harness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/OciHelmDockerApiHelperTest.java
> +                                                                                .connectorConfigDTO(ociHelmConnectorDTO)
Is this test correct now?

2023-09-05 16:16 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    Call call = ociHelmDockerApiRestClient.getTagsList(credentials, chartNameNormalized, pageSize, lastTag);
Is this how we're doing for ECR artifact? Maybe we should use instead aws sdk just to be safe here?

2023-09-06 06:08 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    String[] usernamePassword = new String(
We are getting it in base64 encoded format [https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_GetAuthorizationToken.html](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_GetAuthorizationToken.html)

2023-09-06 06:20 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/OciHelmDockerApiHelperTest.java
> +                                                                                .connectorConfigDTO(ociHelmConnectorDTO)
Done

2023-09-06 06:20 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java
> +        ociHelmConnector != null ? ociHelmConnector : connectorConfigDTO, maskingEvaluator);
Removed it

2023-09-06 06:20 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java
> +  private ConnectorConfigDTO connectorConfigDTO;
removed

2023-09-06 06:20 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +  private String getApiListTagsForEcrOciHelmConfig(
Done

2023-09-06 06:21 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/aws/AwsClientImpl.java
> +    return repository != null ? repository.getRepositoryUri() : null;
Done

2023-09-06 06:21 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmDockerApiHelper.java
> +    OciHelmConnectorDTO ociHelmConnector = ociHelmDockerApiListTagsTaskParams.getOciHelmConnector() == null
changed it

2023-09-06 06:21 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/EcrHelmApiListTagsDelegateTask.java
> +          e.getMessage(), "Failed to query Oci Helm Docker API List Tags", e);
Done

2023-09-06 06:38 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    Call call = ociHelmDockerApiRestClient.getTagsList(credentials, chartNameNormalized, pageSize, lastTag);
I don't think there is anyway around it. There is an existing issue from OCI side [https://github.com/helm/helm/issues/11000](https://github.com/helm/helm/issues/11000)

2023-09-06 06:39 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +        Base64.decode(awsClient.getAmazonEcrAuthToken(awsConfig, account, ecrHelmApiListTagsTaskParams.getRegion())))
Interesting, I will think and get back to you on this.

2023-09-06 06:43 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +        Base64.decode(awsClient.getAmazonEcrAuthToken(awsConfig, account, ecrHelmApiListTagsTaskParams.getRegion())))
I will take this enhancement as part of separate PR as it has already become very huge

2023-09-06 06:43 UTC, GoelPratyush99 commented
trigger uts

2023-09-06 09:02 UTC, GoelPratyush99 commented
trigger ut5, ut6, ut7

2023-09-06 11:23 UTC, GoelPratyush99 commented
trigger ut5, ut6, ut7

2023-09-07 04:26 UTC, GoelPratyush99 commented
trigger ut5, ut6, ut7

2023-09-07 08:06 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java
> +        ociHelmConnector != null ? ociHelmConnector : connectorConfigDTO, maskingEvaluator);
I sill see these changes

2023-09-07 08:14 UTC, abosii-harness submitted a review, later dismissed

2023-09-07 08:14 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    String credentials;
nit: can be inline

2023-09-07 08:14 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    Call call = ociHelmDockerApiRestClient.getTagsList(credentials, chartNameNormalized, pageSize, lastTag);
I mean by using AWS SDK to fetch tags, not sure what does it have with helm

2023-09-07 08:14 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    String[] usernamePassword = new String(
I mean it's basically "Basic " + awsClient.getAmazonEcrAuthToken(...)

2023-09-07 09:44 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    String credentials;
Done

2023-09-07 09:45 UTC, GoelPratyush99 commented
trigger uts

2023-09-07 09:55 UTC, GoelPratyush99 commented
trigger uts

2023-09-07 09:56 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52227)* status: 22 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java` line 84 at r9](https://reviewable.io/reviews/harness/harness-core/52227#gh-1316130560:-Ndj3NMvDP_9MS_t7WEe:bytp8aa) ([raw file](https://github.com/harness/harness-core/blob/84e0467a77f0087979391ee85fcbe24e0752cbb1/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java#L84)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I mean by using AWS SDK to fetch tags, not sure what does it have with helm
</blockquote></details>

got it. I will refactor it as part of PR for caching.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java` line 106 at r9](https://reviewable.io/reviews/harness/harness-core/52227#gh-1316118960:-Ndj3UWh-7Ij_DtJpMJG:bfdl9fc) ([raw file](https://github.com/harness/harness-core/blob/84e0467a77f0087979391ee85fcbe24e0752cbb1/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java#L106)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I mean it's basically "Basic " + awsClient.getAmazonEcrAuthToken(...)
</blockquote></details>

Got it. Done


<!-- Sent from Reviewable.io -->

2023-09-07 09:56 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52227)* status: 22 file(s) to review. 11. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java` line 43 at r9](https://reviewable.io/reviews/harness/harness-core/52227#gh-1316125987:-Ndj3b7L8vlf3Y6d2ZJl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84e0467a77f0087979391ee85fcbe24e0752cbb1/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/helm/OciHelmDockerApiListTagsTaskParams.java#L43)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I sill see these changes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-08 06:08 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    return awsClient.getAmazonEcrAuthToken(awsConfig, account, ecrHelmApiListTagsTaskParams.getRegion());
shouldn't it be "Basic " + awsClient.getAmazonEcrAuthToken(awsConfig, account, ecrHelmApiListTagsTaskParams.getRegion());?

2023-09-08 07:01 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmEcrConfigApiHelper.java
> +    return awsClient.getAmazonEcrAuthToken(awsConfig, account, ecrHelmApiListTagsTaskParams.getRegion());
Done

2023-09-08 07:03 UTC, GoelPratyush99 commented
trigger uts

2023-09-08 07:20 UTC, GoelPratyush99 commented
trigger uts

2023-09-08 07:42 UTC, GoelPratyush99 commented
trigger

2023-09-08 07:42 UTC, GoelPratyush99 commented
trigger uts

2023-09-08 07:52 UTC, abosii-harness approved these changes

2023-09-08 08:59 UTC, TarunUba1 approved these changes

2023-09-08 08:59 UTC, GoelPratyush99 commented
trigger review

2023-09-08 09:01 UTC, merged