fix: [CDS-78304]: CleanUpFiles for Winrm Execution
harness/harness-core pull request #52245
Opened 2023-08-30 09:16 UTC by sarthakkasat

## Describe your changes
When the WINRM_SCRIPT_COMMAND_SPLIT_NG FF is enabled during command step execution, in that case script is copied to a executable file which is then executed, during this process if the script execution fails with any exit code except for 0, the clean up for executable file will not be done, with this code change we are adding the try block with clean up called in finally block to ensure that clean up is always done.
When the pipeline is aborted clean up will not happen in any case, this change ensures that clean up is done every time.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/52245)

2023-08-30 11:16 UTC, acasian-harness reviewed
@sarthakkasat shall we have the cleanup logic in clean command unit itself?

2023-09-01 09:55 UTC, acasian-harness approved these changes

2023-09-01 09:55 UTC, acasian-harness commented
@sarthakkasat can we check for shell script step if the same approach is being used?

2023-09-01 18:58 UTC, sarthakkasat commented
This fix is in DefaultWinrmExecutor which is common for both Winrm shell script and command step

2023-09-12 13:38 UTC, yogesh-chauhan requested changes

2023-09-12 13:38 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java
> +    try (ExecutionLogWriter outputWriter = getExecutionLogWriter(INFO);
we have to initialize "WinRmSession" in the try block itself so that it gets auto closed
since WinrmSession extends AutoCloseable
Ref: https://www.baeldung.com/java-try-with-resources

2023-09-12 13:43 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java
> +    try (ExecutionLogWriter outputWriter = getExecutionLogWriter(INFO);
If we initialize session inside try block, the session gets closed in the finally block, I have closed the session after cleaning up the files

2023-09-12 14:36 UTC, yogesh-chauhan requested changes

2023-09-12 14:36 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java
> +            session, psScriptFile, powershell, disableCommandEncoding, config.getCommandParameters());
if cleanup throws an exception, then the session will not be closed

2023-09-12 16:30 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java
> +            session, psScriptFile, powershell, disableCommandEncoding, config.getCommandParameters());
Added a try finally block to ensure session is closed

2023-09-13 04:31 UTC, sarthakkasat commented
trigger messagecheck

2023-09-13 04:50 UTC, sarthakkasat commented
trigger messagecheck

2023-09-13 11:25 UTC, yogesh-chauhan requested changes

2023-09-13 11:25 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedAbstractWinRmExecutor.java
> +      io.harness.delegate.task.winrm.WinRmExecutorHelper.cleanupFiles(
lets fix import for this i.e not use fully qualified import

2023-09-13 11:26 UTC, yogesh-chauhan requested changes

2023-09-13 11:26 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java
> +          session.close();
should we remove the method call from line: 147 if we are already calling it in the finally block now ?

2023-09-13 12:45 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedAbstractWinRmExecutor.java
> +      io.harness.delegate.task.winrm.WinRmExecutorHelper.cleanupFiles(
Done

2023-09-13 12:52 UTC, sourabh-awashti approved these changes

2023-09-13 13:26 UTC, sarthakkasat commented
trigger uts

2023-09-15 05:55 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52245)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-09-15 05:57 UTC, sarthakkasat commented
trigger review

2023-09-15 05:57 UTC, sarthakkasat commented
trigger gitleaks

2023-09-15 06:00 UTC, merged