fix:[CDS-71319]: Add exception to error response data when task fails during validation phase
harness/harness-core pull request #52271
Opened 2023-08-30 19:02 UTC by Fernando-Dourado

## Describe your changes
- An NPE is regularly thrown when a delegate task fails during the validation phase. 
- In general, a validation failure does not need to be related to an exception, but from a notify event listener a failure always needs to be related to one.

![Uploading Screenshot 2023-08-30 at 16.00.31.png…]()
gers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

## [Latest PR Check Trig

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-30 19:07 UTC, Fernando-Dourado commented
trigger uts

2023-08-30 19:20 UTC, rafaelmart1ns commented on 400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java
> +      } catch (NoAvailableDelegatesException | NoInstalledDelegatesException | NoEligibleDelegatesInAccountException
what do you think about treating the messages separately?

2023-08-30 20:40 UTC, jennyjames21 requested changes

2023-08-30 20:40 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java
> +                                  .build())
this is gonna throw exceptions for other task types, we explicitly removed it for the log cost purpose.
Instead rely on error message,.

2023-08-30 21:36 UTC, Fernando-Dourado commented on 400-rest/src/main/java/io/harness/iterator/FailDelegateTaskIteratorHelper.java
> +                                  .build())
Now I see clearly what you told me during our last call, let me change it.

2023-08-31 13:08 UTC, Fernando-Dourado commented
trigger uts

2023-08-31 13:12 UTC, rafaelmart1ns approved these changes

2023-09-01 13:00 UTC, Fernando-Dourado commented
trigger ut0

2023-09-04 14:12 UTC, Fernando-Dourado commented
trigger ut0

2023-09-04 15:56 UTC, Fernando-Dourado commented
trigger uts

2023-09-04 17:05 UTC, rafaelmart1ns approved these changes

2023-09-04 21:05 UTC, Fernando-Dourado commented
trigger ut8

2023-09-04 21:07 UTC, vcalasansh approved these changes
> Reviewed 3 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52271)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-05 12:44 UTC, lasdox approved these changes

2023-09-05 15:33 UTC, Fernando-Dourado commented
trigger uts_JDK11

2023-09-05 16:03 UTC, jennyjames21 approved these changes

2023-09-06 13:42 UTC, Fernando-Dourado commented
trigger review

2023-09-06 13:44 UTC, Fernando-Dourado commented
trigger ut9

2023-09-06 21:42 UTC, Fernando-Dourado commented
trigger ut9

2023-09-08 13:28 UTC, merged