feat:[CCM-12293]: Anomaly detection for K8s including Harness Services
harness/harness-core pull request #52325
Opened 2023-08-31 17:31 UTC by shashwat-harness

## Describe your changes

Impact - Now we would be able to detect and monitor anomaly on services which was not present on the platform before

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-08-31 17:37 UTC, shashwat-harness commented
trigger codeformat

2023-08-31 18:28 UTC, shashwat-harness commented
trigger codeformat

2023-08-31 18:29 UTC, shashwat-harness commented
trigger checkstylecodeformat

2023-08-31 18:30 UTC, shashwat-harness commented
trigger uts

2023-08-31 21:15 UTC, trunapushpa commented on 450-ce-views/src/main/java/io/harness/ccm/views/helper/PerspectiveToAnomalyQueryHelper.java
> +import static io.harness.ccm.commons.constants.ViewFieldLowerCaseConstants.*;
Harness codeformat check will fail for star imports. Import each one separately.

2023-08-31 21:16 UTC, trunapushpa commented on 490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java
> +  String SERVICE_NAME_FIELD_ID = "serviceName";
why move it from line 22 to line 18?

2023-08-31 21:30 UTC, trunapushpa commented on ce-nextgen/service/src/main/java/io/harness/ccm/migration/CENGTimescaleMigrationDetails.java
> +        .add(Pair.of(5, CCMAnomalyTableAddServiceColumn.class))
merge both the migrations into one

2023-09-01 05:59 UTC, shashwat-harness commented on 490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java
> +  String SERVICE_NAME_FIELD_ID = "serviceName";
Nothing just aligning all important field constants together

2023-09-01 06:05 UTC, shashwat-harness commented on 450-ce-views/src/main/java/io/harness/ccm/views/helper/PerspectiveToAnomalyQueryHelper.java
> +import static io.harness.ccm.commons.constants.ViewFieldLowerCaseConstants.*;
Done

2023-09-01 06:05 UTC, shashwat-harness commented on ce-nextgen/service/src/main/java/io/harness/ccm/migration/CENGTimescaleMigrationDetails.java
> +        .add(Pair.of(5, CCMAnomalyTableAddServiceColumn.class))
Merged

2023-09-01 06:15 UTC, shashwat-harness commented
trigger checkstylecodeformat

2023-09-01 06:42 UTC, shashwat-harness commented
trigger ut0

2023-09-04 12:21 UTC, trunapushpa requested changes

2023-09-04 13:05 UTC, shashwat-harness commented on batch-processing/service/src/main/java/io/harness/batch/processing/anomalydetection/AnomalyDetectionTimeSeries.java
> +@Singleton
Removed

2023-09-04 13:05 UTC, shashwat-harness commented on batch-processing/service/src/main/java/io/harness/batch/processing/anomalydetection/helpers/TimeSeriesUtils.java
> +@Slf4j
Done

2023-09-04 13:06 UTC, shashwat-harness commented on batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/support/HarnessEntitiesService.java
> +    public CacheKey(String entityId, HarnessEntities entity) {
Yes, but i don't think it provides any added advantage or make a difference

2023-09-04 16:16 UTC, shashwat-harness commented
trigger uts

2023-09-05 09:59 UTC, trunapushpa submitted a review, later dismissed

2023-09-06 08:37 UTC, shashwat-harness commented
trigger uts

2023-09-06 11:12 UTC, shashwat-harness commented
trigger uts

2023-09-06 11:30 UTC, shashwat-harness commented
trigger uts

2023-09-06 13:56 UTC, shashwat-harness commented
trigger ut0

2023-09-06 13:57 UTC, shashwat-harness commented
trigger ut1

2023-09-06 13:59 UTC, shashwat-harness commented
trigger ut5

2023-09-06 14:01 UTC, shashwat-harness commented
trigger ut6

2023-09-06 14:02 UTC, shashwat-harness commented
trigger ut8

2023-09-06 14:08 UTC, shashwat-harness commented
trigger ut7

2023-09-06 14:34 UTC, shashwat-harness commented
trigger ut0

2023-09-06 14:34 UTC, shashwat-harness commented
trigger ut1

2023-09-06 15:48 UTC, shashwat-harness commented
trigger ut1

2023-09-06 15:49 UTC, shashwat-harness commented
trigger ut9

2023-09-06 17:07 UTC, shashwat-harness commented
trigger ut7

2023-09-06 17:09 UTC, shashwat-harness commented
trigger ut7

2023-09-06 17:09 UTC, shashwat-harness commented
trigger ut8

2023-09-06 18:15 UTC, shashwat-harness commented
trigger ut7

2023-09-06 18:20 UTC, shashwat-harness commented
trigger ut5

2023-09-07 05:40 UTC, shashwat-harness commented
trigger ut7

2023-09-07 06:51 UTC, shashwat-harness commented
trigger ut6

2023-09-07 06:56 UTC, shashwat-harness commented
trigger ut1

2023-09-07 06:57 UTC, shashwat-harness commented
trigger ut6

2023-09-07 07:05 UTC, shashwat-harness commented
trigger ut6

2023-09-07 07:05 UTC, shashwat-harness commented
trigger ut6

2023-09-07 07:06 UTC, shashwat-harness commented
trigger ut6

2023-09-07 08:26 UTC, shashwat-harness commented
trigger ut0

2023-09-07 10:44 UTC, shashwat-harness commented
trigger ut1

2023-09-07 12:58 UTC, shashwat-harness commented
trigger ut1

2023-09-07 15:37 UTC, trunapushpa approved these changes

2023-09-07 15:41 UTC, trunapushpa approved these changes
LGTM

> Reviewed 25 of 40 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52325#-:-NdkIT2C1VlTQX_Xt8iK:bb6ywmx)* status: :shipit: complete! ✓

___
*[`450-ce-views/src/main/java/io/harness/ccm/views/helper/PerspectiveToAnomalyQueryHelper.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/52325#gh-1312277257:-NdkHz30-dNEx308o-lr:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/ba7e82d2d5e1c11742dfd3fe02ef214afea4b867/450-ce-views/src/main/java/io/harness/ccm/views/helper/PerspectiveToAnomalyQueryHelper.java#L10)):*
<details><summary><i>Previously, shashwat-harness wrote…</i></summary><blockquote>

Done
</blockquote></details>

LGTM
___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/52325#gh-1312284362:-NdkI64731xeo3fnuPug:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/ba7e82d2d5e1c11742dfd3fe02ef214afea4b867/490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java#L18)):*
<details><summary><i>Previously, shashwat-harness wrote…</i></summary><blockquote>

Nothing just aligning all important cluster field constants together 
</blockquote></details>

LGTM
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/anomalydetection/AnomalyDetectionTimeSeries.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/52325#gh-1314831677:-NdkI9uKC_TPwwOGVmkt:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/0babfcac2a03508f3194a90a25b0c71804d58d9e/batch-processing/service/src/main/java/io/harness/batch/processing/anomalydetection/AnomalyDetectionTimeSeries.java#L27)):*
<details><summary><i>Previously, shashwat-harness wrote…</i></summary><blockquote>

Removed
</blockquote></details>

LGTM
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/anomalydetection/helpers/TimeSeriesUtils.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/52325#gh-1314821109:-NdkIFL1-00tjQjnvxYg:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/0babfcac2a03508f3194a90a25b0c71804d58d9e/batch-processing/service/src/main/java/io/harness/batch/processing/anomalydetection/helpers/TimeSeriesUtils.java#L25)):*
<details><summary><i>Previously, shashwat-harness wrote…</i></summary><blockquote>

Done
</blockquote></details>

LGTM
___
*[`batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/support/HarnessEntitiesService.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/52325#gh-1314834933:-NdkIHN6E0ZyUtttiHVi:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/0babfcac2a03508f3194a90a25b0c71804d58d9e/batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/support/HarnessEntitiesService.java#L28)):*
<details><summary><i>Previously, shashwat-harness wrote…</i></summary><blockquote>

Yes, but i don't think it provides any added advantage or make a difference
</blockquote></details>

LGTM
___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/migration/CENGTimescaleMigrationDetails.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/52325#gh-1312306818:-NdkIIiQCxhcyiZQod0H:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/ba7e82d2d5e1c11742dfd3fe02ef214afea4b867/ce-nextgen/service/src/main/java/io/harness/ccm/migration/CENGTimescaleMigrationDetails.java#L44)):*
<details><summary><i>Previously, shashwat-harness wrote…</i></summary><blockquote>

Merged
</blockquote></details>

LGTM


<!-- Sent from Reviewable.io -->

2023-09-07 16:48 UTC, shashwat-harness commented
trigger uts

2023-09-07 18:17 UTC, shashwat-harness commented
trigger ut2

2023-09-07 18:18 UTC, shashwat-harness commented
trigger ut7

2023-09-08 04:21 UTC, shashwat-harness commented
trigger ut2

2023-09-08 06:17 UTC, shashwat-harness commented
trigger ut7

2023-09-08 07:07 UTC, shashwat-harness commented
trigger uts

2023-09-08 09:12 UTC, shashwat-harness commented
trigger ut7

2023-09-08 09:12 UTC, rdsoze commented
@shashwat-harness Going forward, please add more meaningful commit messages.

2023-09-08 09:13 UTC, merged