feat: [CDS-77359]: add adviser obtainments for failure strategies
harness/harness-core pull request #52355
Opened 2023-09-01 08:52 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-04 07:18 UTC, shalini-agr commented
trigger uts

2023-09-04 08:49 UTC, shalini-agr commented
trigger uts

2023-09-04 09:13 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52355)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/52355#-NdUSgfN9FlNK1yH1UZ-:-NdUSgfN9FlNK1yH1UZ0:b-46ic5m) ([raw file](https://github.com/harness/harness-core/blob/ef4d6b5fac7848a6e0cdcd22e549cae0c98213f1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java#L92)):*
> ```Java
>   }
> 
>   Dependency getDependencyForChildren(PlanCreationContext ctx, YamlField config) {
> ```

we should re-discuss this approach with @hextechpal as one con with this approach this we are duplicating same info for all steps, which will lead to memory increased and grpc data transfer for cross steps.


<!-- Sent from Reviewable.io -->

2023-09-05 10:27 UTC, hextechpal approved these changes

2023-09-05 11:16 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52355)* status: 6 file(s) to review. 1 change requests. 



<!-- Sent from Reviewable.io -->

2023-09-05 12:03 UTC, utkarshchoubey-harness commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java
> +    Optional<Object> stageFailureStrategiesOptional = getDeserializedObjectFromParentInfo(
nit- name it stepGroupFailureStrategiesOptional

2023-09-05 12:09 UTC, utkarshchoubey-harness approved these changes

2023-09-05 12:18 UTC, archit-harness requested changes
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52355)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 212 at r4](https://reviewable.io/reviews/harness/harness-core/52355#-Nd_GaGdEyykOgBLDU2A:-Nd_GaGdEyykOgBLDU2B:b-884y0) ([raw file](https://github.com/harness/harness-core/blob/72d28a6dc9e535c38782e40d432e55055a033a21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L212)):*
> ```Java
>     if (dependency != null && dependency.getParentInfo() != null
>         && dependency.getParentInfo().getDataMap().containsKey(key)
>         && dependency.getParentInfo().getDataMap().get(key) != null) {
> ```

can this if condition be a private method? difficult to read in current method and gives more good code read if separated



_Code quote:_
```Java
    if (dependency != null && dependency.getParentInfo() != null
        && dependency.getParentInfo().getDataMap().containsKey(key)
        && dependency.getParentInfo().getDataMap().get(key) != null) {
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/52355#-Nd_GhX4An1ooBS3Am8w:-Nd_GhX4An1ooBS3Am8x:by945v0) ([raw file](https://github.com/harness/harness-core/blob/72d28a6dc9e535c38782e40d432e55055a033a21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L219)):*
> ```Java
>         }
>         return Optional.of(kryoSerializer.asObject(bytes.toByteArray()));
>       }
> ```

this piece of code is repeated, can be extracted out


<!-- Sent from Reviewable.io -->

2023-09-05 12:41 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52355)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 212 at r4](https://reviewable.io/reviews/harness/harness-core/52355#-Nd_GaGdEyykOgBLDU2A:-Nd_LpYB3j0Z18Uy-5bh:b-do95x3) ([raw file](https://github.com/harness/harness-core/blob/72d28a6dc9e535c38782e40d432e55055a033a21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L212)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can this if condition be a private method? difficult to read in current method and gives more good code read if separated
</blockquote></details>

simplified this condition by removing the redundant ones
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/52355#-Nd_GhX4An1ooBS3Am8w:-Nd_Ltjl7BE6cnWpT_Lg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72d28a6dc9e535c38782e40d432e55055a033a21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L219)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this piece of code is repeated, can be extracted out
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/52355#-NdUSgfN9FlNK1yH1UZ-:-Nd_LvZA1vvAqDUnpNVc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ef4d6b5fac7848a6e0cdcd22e549cae0c98213f1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should re-discuss this approach with @hextechpal as one con with this approach this we are duplicating same info for all steps, which will lead to memory increased and grpc data transfer for cross steps.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-06 08:59 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52355)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-06 09:00 UTC, mohitg0795 submitted a review, later dismissed

2023-09-06 09:00 UTC, shalini-agr commented
trigger uts

2023-09-06 09:00 UTC, shalini-agr commented
trigger review

2023-09-06 11:05 UTC, shalini-agr commented
trigger ut5, ut6, ut8, ut9

2023-09-06 11:08 UTC, shalini-agr commented
trigger ut7

2023-09-06 11:15 UTC, shalini-agr commented
trigger ut5, ut6, ut7, ut8, ut9

2023-09-06 13:30 UTC, shalini-agr commented
trigger uts

2023-09-06 16:29 UTC, shalini-agr commented
trigger uts

2023-09-07 05:29 UTC, mohitg0795 approved these changes

2023-09-07 05:39 UTC, brijeshdhakar approved these changes
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52355)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-09-07 05:45 UTC, merged