feat: [CDS-78627]: Added open api spec endpoint for runtime inputs API v1 pipeline yaml
harness/harness-core pull request #52393
Opened 2023-09-03 21:34 UTC by mohitg0795

## Describe your changes
Added new spec v1 endpoint for fetching details of runtime inputs in v1 pipeline yaml

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-04 06:09 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52393)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2661 at r1](https://reviewable.io/reviews/harness/harness-core/52393#-NdTnnkbD3_TYhwSLMKA:-NdTnnkbD3_TYhwSLMKB:b-st6p6p) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2661)):*
> ```YAML
>         id: t1e88zsr8os9p
>       enum:
>         - String
> ```

@mankrit-singh we are following small case for enums or first letter caps?


<!-- Sent from Reviewable.io -->

2023-09-04 06:21 UTC, mankrit-singh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52393)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2661 at r1](https://reviewable.io/reviews/harness/harness-core/52393#-NdTnnkbD3_TYhwSLMKA:-NdTqHgI5ny_-4CVqeFU:b-e0brf6) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2661)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@mankrit-singh we are following small case for enums or first letter caps?
</blockquote></details>

We follow all caps generally, but we didn't define this as a standard I believe


<!-- Sent from Reviewable.io -->

2023-09-04 06:24 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52393)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2661 at r1](https://reviewable.io/reviews/harness/harness-core/52393#-NdTnnkbD3_TYhwSLMKA:-NdTr7ztAhVFOem45VOl:b-byl62x) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2661)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

We follow all caps generally, but we didn't define this as a standard I believe
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/75259284/j4QzHjofzn3YbCbFbBUar2gQ/image.png)
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/75259284/HqyORfTcfjN4oq8vn3sDXRax/image.png)

btw, I see multiple such examples already in the spec


<!-- Sent from Reviewable.io -->

2023-09-04 06:30 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52393)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-04 06:50 UTC, mankrit-singh reviewed
same casing comments and use of common params

2023-09-04 06:50 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        name: org
please use the common params for this, referring to other APIs

2023-09-04 06:50 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        fieldProperties:
field_properties (casing)

2023-09-04 06:50 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        inputType:
input_type and internal_type

2023-09-04 06:50 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        fieldName:
field_name, input_name

2023-09-04 06:50 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        fieldName:
same here

2023-09-04 06:50 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        requiredRuntimeInputs:
and here too

2023-09-04 19:50 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52393)* status: 2 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2687 at r1](https://reviewable.io/reviews/harness/harness-core/52393#gh-1314502859:-NdWjco53oSZS6MkkFKw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2687)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

input_type and internal_type
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2702 at r1](https://reviewable.io/reviews/harness/harness-core/52393#gh-1314503061:-NdWjdOfAOo9KjqMCrRv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2702)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

field_name, input_name
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2717 at r1](https://reviewable.io/reviews/harness/harness-core/52393#gh-1314503211:-NdWjdkP7Ov0hsRoxzxm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2717)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2736 at r1](https://reviewable.io/reviews/harness/harness-core/52393#gh-1314503580:-NdWje9o5yVVXYt-iHWi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2736)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

and here too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-04 19:51 UTC, mohitg0795 commented
trigger uts

2023-09-05 21:00 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52393)* status: 2 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 799 at r1](https://reviewable.io/reviews/harness/harness-core/52393#gh-1314501812:-Ndb8K864BCkcT0uJ1ht:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L799)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

please use the common params for this, referring to other APIs
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2672 at r1](https://reviewable.io/reviews/harness/harness-core/52393#gh-1314502560:-Ndb7Dtb5qXf62MCzdVI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be7728d25d6f570f2184edb6a50016bf0d1cc28b/pipeline-service/contracts/openapi/v1/openapi.yaml#L2672)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

field_properties (casing)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-05 21:00 UTC, mohitg0795 commented
trigger uts

2023-09-05 21:15 UTC, mohitg0795 commented
trigger uts

2023-09-06 04:51 UTC, mankrit-singh approved these changes

2023-09-06 05:07 UTC, mohitg0795 commented
trigger ut1

2023-09-06 05:18 UTC, archit-harness approved these changes

2023-09-06 05:18 UTC, mohitg0795 commented
trigger review

2023-09-06 05:20 UTC, ankittiwari-harness approved these changes

2023-09-06 06:19 UTC, AnshuH commented
/rebase

2023-09-06 06:26 UTC, mohitg0795 commented
trigger uts

2023-09-06 06:53 UTC, merged