feat: [CDS-71173]: Added the setting control deleting execution
harness/harness-core pull request #52424
Opened 2023-09-04 15:26 UTC by shivamnegi94

## Describe your changes
**Current behaviour:** Deleting of pipeline will trigger the delete event which will delete all the executions of deleted pipeline.

**Enhancement:** Customer have ask to access the execution of the pipeline even after deletion.
We have added a setting `do_not_delete_pipeline_execution_details` to control the deletion of pipeline execution on delete event. ByDefault value will be false.

**Test case:**

- Verify the pipeline execution should get deleted if `do_not_delete_pipeline_execution_details` is false.
- Verify the pipeline execution should not get deleted if `do_not_delete_pipeline_execution_details` is true.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-04 15:28 UTC, shivamnegi94 commented
trigger uts

2023-09-05 03:34 UTC, shivamnegi94 commented
trigger uts

2023-09-05 04:50 UTC, naidu-harness commented on pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java
> +        log.info("Processed deleting metadata and execution details for given pipeline");
add details in the log -> accountId, orgIdentifier, projectIdentifier, pipelineIdentifier

2023-09-05 04:53 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 155 at r1](https://reviewable.io/reviews/harness/harness-core/52424#-NdYfnCXBxmq3xhdtVIo:-NdYfnCXBxmq3xhdtVIp:brcpxkl) ([raw file](https://github.com/harness/harness-core/blob/d2d61f2d28a8289a1d2f6f40c11b126a2ffbe8d9/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L155)):*
> ```Java
>           NGRestUtils
>               .getResponse(ngSettingsClient.getSetting(
>                   NGPipelineSettingsConstant.DO_NOT_DELETE_PIPELINE_EXECUTION_DETAILS.getName(), accountId, null, null))
> ```

Could you please check what happens if setting is not present in ng-manager and we call this?Does this return false or throws exception?
You can replicate this by running ng-manager without your change and then pipeline-service with your changes.


<!-- Sent from Reviewable.io -->

2023-09-05 04:55 UTC, sahilhindwani-harness commented
Please validate the following scenerios:
- Post deletion of pipeline and if the setting is enabled, you are able to see the execution listing page.
- Also, you are able to visit individual execution. 
- If edit button is not disabled then what is the error we are getting.
- 





<!-- Sent from Reviewable.io -->

2023-09-05 05:03 UTC, archit-harness requested changes
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 155 at r1](https://reviewable.io/reviews/harness/harness-core/52424#-NdYi1hdEf2iTGu0NWtx:-NdYi1he0RYOfUFvdVr2:b7gi7jw) ([raw file](https://github.com/harness/harness-core/blob/d2d61f2d28a8289a1d2f6f40c11b126a2ffbe8d9/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L155)):*
> ```Java
>           NGRestUtils
>               .getResponse(ngSettingsClient.getSetting(
>                   NGPipelineSettingsConstant.DO_NOT_DELETE_PIPELINE_EXECUTION_DETAILS.getName(), accountId, null, null))
> ```

@shivamnegi94 we should not delete just these collections mentioned in this heading, rest collections should be deleted, please evaluate if the flow seems okay or its a big change 

https://harness.atlassian.net/wiki/spaces/~5ce42d90c9167e0d6ea29342/pages/21453505732/Data+Terminology+and+Retention#Durable-Execution-Data


<!-- Sent from Reviewable.io -->

2023-09-05 19:32 UTC, rohitk-h approved these changes

2023-09-05 19:32 UTC, rohitk-h commented on pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java
> +        deletePipelineExecutionsDetails(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier);
suggestion: Since the two delete calls are consecutive better to have a log statement after each operation.

2023-09-05 19:32 UTC, rohitk-h commented on pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java
> +      log.debug(String.format("Could not fetch setting: %s",
bit: I would prefer the log to be at `warn` level.

2023-09-05 19:32 UTC, rohitk-h commented on pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java
>      log.info("Processed deleting metadata and execution details for given pipeline");
nit: this log line might indicate we indeed processed deletion if the setting is off. We should rephrase to say something else since we'll log and return in the flag was true from line 164.

2023-09-06 03:52 UTC, shivamnegi94 reviewed
1: Post deletion of pipeline and setting is enabled then execution are listed in deployment page
2: We are able to visit the individual executions.
3: Edit button is enabled and on clicking it will give you error that pipeline doesn't exist
![Screenshot 2023-09-05 at 3.16.57 PM.png](https://files.reviewableusercontent.io/images/reviewable/58415634/rdqvvP5RocwRiCbDikhWPISz/Screenshot%202023-09-05%20at%203.16.57%20PM.png)

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424#-:-Ndcb6756MyCoJ9zgVPN:b-kbciul)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 155 at r1](https://reviewable.io/reviews/harness/harness-core/52424#-NdYfnCXBxmq3xhdtVIo:-Ndcaq-C-5u3jP5PZkQK:bp4mtog) ([raw file](https://github.com/harness/harness-core/blob/d2d61f2d28a8289a1d2f6f40c11b126a2ffbe8d9/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L155)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Could you please check what happens if setting is not present in ng-manager and we call this?Does this return false or throws exception?
You can replicate this by running ng-manager without your change and then pipeline-service with your changes.
</blockquote></details>

We were getting false if setting is not present
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/52424#gh-1315359120:-Ndcb-hKAorj0pW1NS1y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d2d61f2d28a8289a1d2f6f40c11b126a2ffbe8d9/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L160)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

add details in the log -> accountId, orgIdentifier, projectIdentifier, pipelineIdentifier
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 04:42 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/52424#gh-1316314002:-Ndcn1Iq4aesZf5Sbab5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b1667a209e13e9360c8bd113d930b2f19157f754/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L159)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

suggestion: Since the two delete calls are consecutive better to have a log statement after each operation. 
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/52424#gh-1316314035:-Ndcn-eO5FRTXTt3BBnP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b1667a209e13e9360c8bd113d930b2f19157f754/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L166)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

bit: I would prefer the log to be at `warn` level. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 09:31 UTC, archit-harness requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 152 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddoHsu7LpmIJAEo3LU:-NddoHsu7LpmIJAEo3LV:b-sostxk) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L152)):*
> ```Java
>     String pipelineIdentifier = entityChangeDTO.getIdentifier().getValue();
>     try {
>       String retainPipelineExecutionDetailsAfterDelete =
> ```

we should try/catch here, if exception, treat as false
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 169 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-Nddnphg-vsB6AEyJj7v:-Nddnphg-vsB6AEyJj7w:b-vf4icp) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L169)):*
> ```Java
>       return true;
>     } catch (Exception ex) {
>       log.warn(String.format("Could not fetch setting: %s",
> ```

This catch of for complete method can come for any case, so we should only mention exception while processing delete event for pipeline.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 185 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddoYjd5EEdRvNeASZf:-NddoYjd5EEdRvNeASZg:b-d32j9y) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L185)):*
> ```Java
>     if (!retainPipelineExecutionDetailsAfterDelete) {
>       // Delete the pipeline metadata to delete run-sequence, etc.
>       pipelineMetadataService.deletePipelineMetadata(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier);
> ```

We dont want to preserve this -> we want to preserve planExecutionsMetadata
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 229 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddpF0aEj0vHKAJp3Zy:-NddpF0aEj0vHKAJp3Zz:b-rxlrbt) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L229)):*
> ```Java
>     interruptService.deleteAllInterrupts(planExecutionsToDelete);
>     // Delete all graph metadata
>     graphGenerationService.deleteAllGraphMetadataForGivenExecutionIds(planExecutionsToDelete);
> ```

graphGenerationService.deleteAllGraphMetadataForGivenExecutionIds(planExecutionsToDelete); this is for cacheEntities
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 230 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-Nddp5FH0UTSsmEp49al:-Nddp5FH0UTSsmEp49am:b1edcor) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L230)):*
> ```Java
>     // Delete all graph metadata
>     graphGenerationService.deleteAllGraphMetadataForGivenExecutionIds(planExecutionsToDelete);
>     if (!retainPipelineExecutionDetailsAfterDelete) {
> ```

this is wrong, data not to be deleted is present in -> PlanExecutionDeleteObserver
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 237 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddohFU8zGBjVqMU0PW:-NddohFU8zGBjVqMU0PX:bqwmfob) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L237)):*
> ```Java
>       planExecutionService.deleteAllPlanExecutionAndMetadata(planExecutionsToDelete);
>     }
>     // Delete nodeExecutions and its metadata
> ```

this is not nodeExecutions , wrong comment added


<!-- Sent from Reviewable.io -->

2023-09-06 10:16 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 4 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 185 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddoYjd5EEdRvNeASZf:-NddzLyT2cSPDKPA_TSy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L185)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We dont want to preserve this -> we want to preserve planExecutionsMetadata
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 229 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddpF0aEj0vHKAJp3Zy:-NddzNSg-2OOD4qv2xMB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L229)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

graphGenerationService.deleteAllGraphMetadataForGivenExecutionIds(planExecutionsToDelete); this is for cacheEntities
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 237 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddohFU8zGBjVqMU0PW:-NddzXIz6-4kywJ2owd0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L237)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is not nodeExecutions , wrong comment added
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 15:00 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 4 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 169 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-Nddnphg-vsB6AEyJj7v:-Ndf-AEVCWm92yuPcdE_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L169)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This catch of for complete method can come for any case, so we should only mention exception while processing delete event for pipeline.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 230 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-Nddp5FH0UTSsmEp49al:-Ndf-RKUEPa70iJ2qs7p:b-8osnsd) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L230)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is wrong, data not to be deleted is present in -> PlanExecutionDeleteObserver
</blockquote></details>

you mean this shouldn't be deleted if config is true right ? graphGenerationService.deleteAllGraphMetadataForGivenExecutionIds(planExecutionsToDelete


<!-- Sent from Reviewable.io -->

2023-09-08 06:40 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 17 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 152 at r4](https://reviewable.io/reviews/harness/harness-core/52424#-NddoHsu7LpmIJAEo3LU:-NdnW91TDcU9ZP8oJy7C:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1784222c28a7e95570818e42c87c1d55077963a5/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L152)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should try/catch here, if exception, treat as false
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-08 07:31 UTC, shivamnegi94 commented
trigger uts

2023-09-11 04:57 UTC, shivamnegi94 commented
trigger uts

2023-09-11 05:07 UTC, archit-harness requested changes
> Reviewed 13 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 17 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/PlanExecutionMetadataDeleteObserver.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/52424#-Ne1btEBA9lg8sFAI4Ky:-Ne1btEBA9lg8sFAI4Kz:b49t100) ([raw file](https://github.com/harness/harness-core/blob/f3ee75200991e9f30296de2919c05f5fe894753e/pipeline-service/modules/orchestration/src/main/java/io/harness/event/PlanExecutionMetadataDeleteObserver.java#L44)):*
> ```Java
>       planService.deletePlansForGivenIds(planIds);
>       // Delete all planExecutionMetadata for given planExecutionIds
>       planExecutionMetadataService.deleteMetadataForGivenPlanExecutionIds(planExecutionIds);
> ```

except planExecutionMetadata, planService can be deleted
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 162 at r6](https://reviewable.io/reviews/harness/harness-core/52424#-Ne1c8zS3L6MOm1yDnVY:-Ne1c8zS3L6MOm1yDnVZ:bvait6b) ([raw file](https://github.com/harness/harness-core/blob/f3ee75200991e9f30296de2919c05f5fe894753e/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L162)):*
> ```Java
>                    NGPipelineSettingsConstant.DO_NOT_DELETE_PIPELINE_EXECUTION_DETAILS.getName()),
>           ex);
>       return false;
> ```

why we are returning false? can we just set variable to false and continue
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 206 at r6](https://reviewable.io/reviews/harness/harness-core/52424#-Ne1ca0o-GlJlSNrHDQX:-Ne1ca0o-GlJlSNrHDQY:b-8se48e) ([raw file](https://github.com/harness/harness-core/blob/478bfd487c378e7015b17f31948d8ecce4fcb04a/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L206)):*
> ```Java
>     graphGenerationService.deleteAllGraphMetadataForGivenExecutionIds(planExecutionsToDelete);
>     // Delete nodeExecutions and its metadata
>     for (String planExecutionToDelete : planExecutionsToDelete) {
> ```

why this diff is showing for you?


<!-- Sent from Reviewable.io -->

2023-09-11 05:36 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 17 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/PlanExecutionMetadataDeleteObserver.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/52424#-Ne1btEBA9lg8sFAI4Ky:-Ne1jKS2C11gzZ2qelr0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3ee75200991e9f30296de2919c05f5fe894753e/pipeline-service/modules/orchestration/src/main/java/io/harness/event/PlanExecutionMetadataDeleteObserver.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

except planExecutionMetadata, planService can be deleted
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 162 at r6](https://reviewable.io/reviews/harness/harness-core/52424#-Ne1c8zS3L6MOm1yDnVY:-Ne1jOPPC3Xw0QQxUW0W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3ee75200991e9f30296de2919c05f5fe894753e/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L162)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are returning false? can we just set variable to false and continue
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java` line 206 at r6](https://reviewable.io/reviews/harness/harness-core/52424#-Ne1ca0o-GlJlSNrHDQX:-Ne1jQLZ9NLYmt6ltYxZ:b7yhk5b) ([raw file](https://github.com/harness/harness-core/blob/478bfd487c378e7015b17f31948d8ecce4fcb04a/pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud/PipelineEntityCRUDStreamListener.java#L206)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this diff is showing for you?
</blockquote></details>

Done. I have fixed it


<!-- Sent from Reviewable.io -->

2023-09-11 05:41 UTC, archit-harness approved these changes
> Reviewed 1 of 15 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 17 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-11 06:18 UTC, shivamnegi94 commented
trigger uts

2023-09-11 09:42 UTC, shivamnegi94 commented
trigger uts

2023-09-11 11:15 UTC, shivamnegi94 commented
trigger uts

2023-09-11 15:47 UTC, shivamnegi94 commented
trigger uts

2023-09-12 02:34 UTC, shivamnegi94 commented
trigger uts

2023-09-12 03:37 UTC, shivamnegi94 commented
trigger uts

2023-09-12 05:10 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 4 files at r10, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 18 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-12 06:23 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 10 of 15 files at r6, 2 of 2 files at r7, 1 of 4 files at r10, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-12 06:28 UTC, sahilhindwani-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-12 06:39 UTC, shivamnegi94 commented
trigger review

2023-09-12 08:22 UTC, shivamnegi94 commented
trigger uts

2023-09-12 12:21 UTC, shivamnegi94 commented
trigger uts

2023-09-12 15:36 UTC, rohitk-h approved these changes
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 9 of 15 files at r6, 1 of 2 files at r7, 1 of 4 files at r10, 2 of 3 files at r12, 2 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52424)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-12 15:47 UTC, shivamnegi94 commented
trigger review

2023-09-12 16:15 UTC, merged