feat: [PL-40873]: add condition to filter only mark for deletion account
harness/harness-core pull request #52425
Opened 2023-09-04 16:12 UTC by sahibaCCM

Accounts are marked for deletion and will be picked by iterator. But since we are picking random 60 accounts every 5 hours and then checking how many out of them are actually marked for deletion on weekend. This whole process becomes a bottle neck as there is huge number of account so probability  of selected account being marked for deleted is quite less.
To give a number in last 30 days 82 accounts where deleted out of approx. 2400~ accounts picked.

Adding a filter condition to only pick mark for deletion accounts. 

Tested for:
- running the iterator for a short interval of time to check only MARK-FOR-DELETION ACCOUNT are picked
 

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-04 16:39 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +      query.filter("licenseInfo.accountStatus", "MARKED_FOR_DELETION");
Nit:

Please use constants: 
like - `AccountKeys.licenseInfo + "." + LicenseInfoKeys.accountStatus` & AccountStatus.MARKED_FOR_DELETION

2023-09-04 16:40 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +    log.info("Log for testing Account Delete: AccountId: {}  AccountStatus: {}", account.getUuid(),
minor: lets log with better logging detail

2023-09-04 16:41 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +        account.getLicenseInfo().getAccountStatus());
Can this lead to NPE, please check if there are account with no licenseInfo data, thanks

2023-09-05 05:08 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +      query.filter("licenseInfo.accountStatus", "MARKED_FOR_DELETION");
AccountKeys.licenseInfo + "." + LicenseInfoKeys.accountStatus wont be possible
<img width="1162" alt="image" src="https://github.com/harness/harness-core/assets/112424209/b607f621-e9f4-4bd1-9c55-2eb8203d4dd8">

Making the changes for AccountStatus.MARKED_FOR_DELETION

2023-09-05 05:08 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +    log.info("Log for testing Account Delete: AccountId: {}  AccountStatus: {}", account.getUuid(),
This a test log I'll remove it post testing in preqa

2023-09-05 05:09 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +        account.getLicenseInfo().getAccountStatus());
I'm not sure if account creation is possible with out license Info; but since we'll be removing the log it self it shouldn't be a problem in other scenerio.

2023-09-05 05:59 UTC, sahibaCCM commented
trigger uts

2023-09-05 06:10 UTC, sahibaCCM commented
trigger ut4

2023-09-05 06:10 UTC, sahibaCCM commented
trigger ut5

2023-09-05 07:45 UTC, bhavya181 submitted a review, later dismissed

2023-09-05 10:51 UTC, sahibaCCM commented
trigger ut4

2023-09-06 11:04 UTC, manish-manchanda commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +      query.filter("licenseInfo.accountStatus", AccountStatus.MARKED_FOR_DELETION);
Please check and add index if need be

2023-09-06 16:20 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +      query.filter("licenseInfo.accountStatus", AccountStatus.MARKED_FOR_DELETION);
done

2023-09-06 16:29 UTC, sahibaCCM commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +      query.filter("licenseInfo.accountStatus", AccountStatus.MARKED_FOR_DELETION);
![Uploading image.png…]()

2023-09-07 08:11 UTC, sahibaCCM commented
trigger uts

2023-09-07 09:41 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> +        account.getLicenseInfo().getAccountStatus());
Please remove the logs after verifying, this can lead to NPE, thanks

2023-09-07 09:42 UTC, pbarapatre10 submitted a review, later dismissed

2023-09-07 11:56 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52425)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 90 at r4](https://reviewable.io/reviews/harness/harness-core/52425#-NdjUhG40CK95_2AL3II:-NdjUhG40CK95_2AL3IJ:bf1x542) ([raw file](https://github.com/harness/harness-core/blob/7376c7686c8188b63a4a0cf628eddda10080753a/400-rest/src/main/java/software/wings/beans/Account.java#L90)):*
> ```Java
>                  .build(),
>             CompoundMongoIndex.builder()
>                 .name("account_deletion_iterator")
> ```

account_status_deletion_iteration


<!-- Sent from Reviewable.io -->

2023-09-07 14:07 UTC, sahibaCCM reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52425)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 90 at r4](https://reviewable.io/reviews/harness/harness-core/52425#-NdjUhG40CK95_2AL3II:-Ndjxy3zDhJCfwFoY4Ph:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7376c7686c8188b63a4a0cf628eddda10080753a/400-rest/src/main/java/software/wings/beans/Account.java#L90)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

account_status_deletion_iteration
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/52425#gh-1315114063:-Ndjy1TG5Jn7WIy6O_Z0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/59f7b7832d6a7368e1dd4b04ee3ea68a68a5ab08/400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java#L102)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Please remove the logs after verifying, this can lead to NPE, thanks
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-07 14:18 UTC, sahibaCCM commented
trigger uts

2023-09-07 15:00 UTC, pbarapatre10 approved these changes

2023-09-07 15:41 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52425#-:-NdkIbZD8GiIwuYdkLe7:bnfp4nl)* status: 3 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-07 16:14 UTC, sahibaCCM commented
trigger ut7

2023-09-07 16:35 UTC, merged