fix: [CDS-78561]: adding helm chart info into a new outcome and updat…
harness/harness-core pull request #52429
Opened 2023-09-04 19:56 UTC by TarunUba1

…ing pipeine info and service info to contain helm chart details

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-05 06:18 UTC, TarunUba1 commented
trigger uts

2023-09-06 11:30 UTC, TarunUba1 commented
trigger uts

2023-09-06 12:31 UTC, TarunUba1 commented
trigger uts

2023-09-06 13:34 UTC, abosii-harness requested changes

2023-09-06 13:34 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/ManifestHelmChartOutcome.java
> +public class ManifestHelmChartOutcome implements Outcome, ExecutionSweepingOutput {
Let's rename this to ReleaseHelmChartOutcome

2023-09-06 13:34 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
> +                         .outcome(manifestHelmChartOutcome)
so here the manifestHelmChartOutcome can be null, I guess that outcome with null value is still a valid outcome and will be reported as found. This will result in NPE later

2023-09-06 14:58 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
> +                         .outcome(manifestHelmChartOutcome)
we check 
    return Optional.ofNullable((ManifestHelmChartOutcome) optionalOutcome.getOutcome());
    so if value is null than we return Optional.empty() also

2023-09-06 16:50 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +          RefObjectUtils.getOutcomeRefObject(OutcomeExpressionConstants.MANIFEST_HELM_CHART_OUTCOME));
nit. can we reuse the method `getHelmChartOutcome`?

2023-09-06 16:50 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +              String.format("%s:%s", releaseHelmChartOutcome.getName(), releaseHelmChartOutcome.getVersion())));
we only need version here, is there any other use-case which requires the chart name and the version both?
nit. If name is also needed, we can create a separate variable instead?

2023-09-07 11:35 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
> +          RefObjectUtils.getOutcomeRefObject(OutcomeExpressionConstants.MANIFEST_HELM_CHART_OUTCOME));
we can but i like to kinda keep them separate for clarity

2023-09-07 12:01 UTC, RishabhGupta34 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/stepsdependency/constants/OutcomeExpressionConstants.java
> +  public final String MANIFEST_HELM_CHART_OUTCOME = "releaseHelmChartOutcome";
nit. can we rename this also to `RELEASE_HELM_CHART_OUTCOME`, to keep it similar?

2023-09-07 12:47 UTC, abosii-harness submitted a review, later dismissed

2023-09-07 13:31 UTC, RishabhGupta34 submitted a review, later dismissed

2023-09-07 14:14 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java
> +  public ReleaseHelmChartOutcome getHelmChartOutcome(HelmChartInfo helmChartInfo) {
nit: Can rename this to getReleaseHelmChartOutcome

2023-09-07 14:15 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java
> +  public ReleaseHelmChartOutcome getHelmChartOutcome(HelmChartInfo helmChartInfo) {
its fine

2023-09-07 14:21 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
> +                         .outcome(manifestHelmChartOutcome)
There is no point to have such complex logic if we can conditionally set the step outcome if only manifestHelmChartOutcome is not null

2023-09-07 14:46 UTC, TarunUba1 commented
trigger uts

2023-09-07 15:22 UTC, GoelPratyush99 approved these changes

2023-09-07 15:23 UTC, yogesh-chauhan approved these changes

2023-09-07 15:30 UTC, TarunUba1 commented
trigger review

2023-09-07 15:32 UTC, merged