Fixed Special Chars Handling
harness/harness-core pull request #52435
Opened 2023-09-05 04:56 UTC by adiyaar24

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-06 09:57 UTC, adiyaar24 commented
trigger uts

2023-09-06 13:34 UTC, adiyaar24 commented
trigger ut6

2023-09-06 13:35 UTC, adiyaar24 commented
trigger ut7

2023-09-06 13:35 UTC, adiyaar24 commented
trigger ut8

2023-09-06 13:35 UTC, adiyaar24 commented
trigger ut9

2023-09-06 13:57 UTC, adiyaar24 commented
trigger ut9

2023-09-06 15:05 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java
> +              .regex(Pattern.quote(searchTerm), NGResourceFilterConstants.CASE_INSENSITIVE_MONGO_OPTIONS));
Please add UTs for cases we are solving with this PR.

2023-09-06 15:05 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java
> +      searchTermCriteria.orOperator(Criteria.where(InviteKeys.email).regex(Pattern.quote(searchTerm)),
Same for all services

2023-09-14 16:06 UTC, adiyaar24 commented
trigger uts

2023-09-15 14:12 UTC, meenakshi-harness commented on 120-ng-manager/modules/ng-variables/src/test/java/io/harness/ng/core/variable/services/impl/VariableServiceImplTest.java
> +    assertThat(list.getContent().get(0).getVariable().getIdentifier()).isEqualTo(varID);
What are we asserting for specialCharSearchTerm ?

2023-09-17 13:12 UTC, adiyaar24 commented on 120-ng-manager/modules/ng-variables/src/test/java/io/harness/ng/core/variable/services/impl/VariableServiceImplTest.java
> +    assertThat(list.getContent().get(0).getVariable().getIdentifier()).isEqualTo(varID);
When we used to send search term with special chars , it used to error out giving 500 as response , so now if I try to give that search term in the search field I am asserting that if my response is coming or not and if its coming is it the correct one

2023-10-09 10:35 UTC, nishantsaini20 requested changes
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52435)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-variables/src/test/java/io/harness/ng/core/variable/services/impl/VariableServiceImplTest.java` line 567 at r2](https://reviewable.io/reviews/harness/harness-core/52435#gh-1327345841:-NgIy4eb1CheeTWgPgoY:b-lsxwiq) ([raw file](https://github.com/harness/harness-core/blob/7b20762e5f9d909af0242d6c375ab55e35351435/120-ng-manager/modules/ng-variables/src/test/java/io/harness/ng/core/variable/services/impl/VariableServiceImplTest.java#L567)):*
<details><summary><i>Previously, adiyaar24 (Aditya Kashyap) wrote…</i></summary><blockquote>

When we used to send search term with special chars , it used to error out giving 500 as response , so now if I try to give that search term in the search field I am asserting that if my response is coming or not and if its coming is it the correct one 
</blockquote></details>

findAll() call is mocked, which is the call to DB. If this is what was causing 500 error then this test won't help much since the original call is mocked. What you can check in UT is that string used to form query is wrapped by \Q and \E
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 1017 at r2](https://reviewable.io/reviews/harness/harness-core/52435#-NgIzpeXBe5DosoaCeba:-NgIzpeXBe5DosoaCebb:b-odsbqm) ([raw file](https://github.com/harness/harness-core/blob/7b20762e5f9d909af0242d6c375ab55e35351435/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L1017)):*
> ```Java
>     }
>     if (!isBlank(searchTerm)) {
>       Page<UserInfo> userInfos = ngUserService.listCurrentGenUsers(accountIdentifier, Pattern.quote(searchTerm),
> ```

We should use this only when forming criteria.


<!-- Sent from Reviewable.io -->

2023-12-19 19:44 UTC, bot2-harness commented
This PR has been automatically closed due to inactivity.

2023-12-19 19:44 UTC, closed without merging