[feat]: [CDS-77615]: Changes in list infra api
harness/harness-core pull request #52430
Opened 2023-09-04 20:30 UTC by PragyeshMishra01

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-11 20:44 UTC, PragyeshMishra01 commented
trigger uts

2023-09-12 06:44 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDetailsAbstract.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) public List<String> scopedToServices;
Hi Pragyesh, why we are keeping this parameter at the end ?

2023-09-12 07:41 UTC, PragyeshMishra01 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDetailsAbstract.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) public List<String> scopedToServices;
I will move it above the methods, somehow I missed it.

2023-09-12 10:59 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDetailsAbstract.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) public List<String> scopedToServices;
ok thanks

2023-09-12 18:05 UTC, PragyeshMishra01 commented
trigger smartchecks

2023-09-12 20:50 UTC, PragyeshMishra01 commented
trigger checkstylecodeformat

2023-09-13 08:58 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 417 at r2](https://reviewable.io/reviews/harness/harness-core/52430#-NeCkqq0CFAGwJ8Cb3TT:-NeCkqq14Xw30ZZNUnOX:b-6akfbf) ([raw file](https://github.com/harness/harness-core/blob/0b4e2eb77a9fadd12395eb20fef2f3cf70315233/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L417)):*
> ```Java
>     if (cdFeatureFlagHelper.isEnabled(accountId, FeatureName.CDS_SCOPE_INFRA_TO_SERVICES)) {
>       infraEntities = infrastructureEntityService.getScopedInfrastructures(infraEntities, serviceRefs);
>     }
> ```

if FF is enabled, we will make 2 DB calls ?


<!-- Sent from Reviewable.io -->

2023-09-13 09:21 UTC, PragyeshMishra01 commented
trigger uts

2023-09-13 09:48 UTC, tchaurasiya requested changes

2023-09-13 09:48 UTC, tchaurasiya commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
> +    if (featureFlagService.isEnabled(accountId, FeatureName.CDS_SCOPE_INFRA_TO_SERVICES)) {
How are we handling deployToAll case here? will UI send the infra list in that case?

2023-09-13 09:48 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDetailsAbstract.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) public List<String> scopedToServices;
nit: can we add in swagger description that here serviceRefs are required not the identifier

2023-09-13 09:57 UTC, PragyeshMishra01 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDetailsAbstract.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) public List<String> scopedToServices;
sure, adding it

2023-09-13 10:33 UTC, PragyeshMishra01 commented on 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java
> +    if (featureFlagService.isEnabled(accountId, FeatureName.CDS_SCOPE_INFRA_TO_SERVICES)) {
currently, It is not handled here. It will work if UI sends all infras but that can add some overhead to UI. 
It is possible to handle it at BE but will need to add one more param in this API to take deployToAll fields for envs. 

Also, we are not handling deploy to filtered list and environment groups here. We will handle that during save of pipeline.

2023-09-13 12:47 UTC, PragyeshMishra01 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDetailsAbstract.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) public List<String> scopedToServices;
done

2023-09-13 13:26 UTC, PragyeshMishra01 commented
trigger uts

2023-09-14 05:39 UTC, tchaurasiya approved these changes

2023-09-14 05:42 UTC, piyush-bhuwalka submitted a review, later dismissed

2023-09-14 05:43 UTC, PragyeshMishra01 commented
trigger review

2023-09-14 06:30 UTC, lovish1999 submitted a review, later dismissed

2023-09-14 09:04 UTC, PragyeshMishra01 commented
trigger uts

2023-09-14 09:25 UTC, PragyeshMishra01 commented
trigger uts

2023-09-14 09:48 UTC, PragyeshMishra01 commented
trigger ut4

2023-09-14 09:50 UTC, PragyeshMishra01 commented
trigger ut6

2023-09-14 10:20 UTC, PragyeshMishra01 commented
trigger ut4

2023-09-14 10:21 UTC, PragyeshMishra01 commented
trigger ut4

2023-09-14 10:30 UTC, lovish1999 commented
trigger ut4

2023-09-14 10:31 UTC, piyush-bhuwalka commented
trigger ut4

2023-09-14 10:31 UTC, piyush-bhuwalka approved these changes

2023-09-14 10:37 UTC, lovish1999 approved these changes

2023-09-14 10:49 UTC, PragyeshMishra01 commented
trigger review

2023-09-14 10:51 UTC, PragyeshMishra01 commented
trigger review

2023-09-14 11:23 UTC, tchaurasiya approved these changes

2023-09-14 11:34 UTC, merged