[feat]: [CDS-77521]: Added a new mongo entity to store GitXWebhook events
harness/harness-core pull request #52450
Opened 2023-09-05 10:06 UTC by adivishy1

## Describe your changes
Added a new mongo entity to store GitXWebhook events.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-05 10:06 UTC, adivishy1 commented
trigger uts

2023-09-05 10:56 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZz6zI9IXLqtt8WX7g:-NdZz6zI9IXLqtt8WX7h:b-macr5p) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L63)):*
> ```Java
>   String webhookIdentifier;
>   String payload;
>   String triggerType;
> ```

whats triggerType?


<!-- Sent from Reviewable.io -->

2023-09-05 10:57 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZzE3TCDWDiIr3IDcW:-NdZzE3TCDWDiIr3IDcX:b-1f1abq) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L71)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(CompoundMongoIndex.builder()
>                  .name("accountIdentifier_webhookIdentifier_unique_idx")
> ```

why would webhook identifier + account identifier be unique?


<!-- Sent from Reviewable.io -->

2023-09-05 11:48 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZz6zI9IXLqtt8WX7g:-Nd_1Xcy1ut8BHCmyPcF:b-j7g2ln) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats triggerType?
</blockquote></details>

Push or PR or delete etc, waiting for the product call on this
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZz4P30bQgWtbVdv8c:-Nd_3Y9j-xfRiK7gNMwj:bmhjjd6) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the meaning of eventTriggeredTime?
</blockquote></details>

When the webhook was triggered, this will be helpful to go back to git provider and check for same time stamp
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZzE3TCDWDiIr3IDcW:-Nd_1gbS1-HcuUy4KU11:bhv3jrk) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why would webhook identifier + account identifier be unique?
</blockquote></details>

agreed, it wont be unique 


<!-- Sent from Reviewable.io -->

2023-09-06 00:04 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java
> +  String triggerType;
Can we use eventType instead of triggerType?
Github sends this as event 
![image](https://github.com/harness/harness-core/assets/106265061/e650810f-7359-4321-b8d7-3d73a7ffb0a8)

2023-09-06 00:06 UTC, sribalij requested changes
Added comment

2023-09-06 07:47 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 3 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/52450#gh-1316537032:-NddSUSNAB_2h73Lq34I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a3fbbe1b4162ea6ca6b12dfb1742baa23114ca2/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L63)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Can we use eventType instead of triggerType?
Github sends this as event 
![image](https://github.com/harness/harness-core/assets/106265061/e650810f-7359-4321-b8d7-3d73a7ffb0a8)

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 08:13 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 4 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/52450#gh-1316537032:-NddYFru1yiQs9guM8T_:b94qby5) ([raw file](https://github.com/harness/harness-core/blob/7a3fbbe1b4162ea6ca6b12dfb1742baa23114ca2/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L63)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've a concern here. Firstly, whats the use-case of this field? Secondly, is this consistent across git providers? We can't simply fetch something from any webhook and store directly with us.


<!-- Sent from Reviewable.io -->

2023-09-06 08:15 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 4 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZz4P30bQgWtbVdv8c:-NddYmzZ44quyCL1f9_Z:bzfzqsc) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L65)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

When the webhook was triggered, this will be helpful to go back to git provider and check for same time stamp
</blockquote></details>

I doubt if it serves any purpose as such. Once we have event id or something, it automatically takes care of everything. Only if this data is required for any purpose, we should add it otherwise not.


<!-- Sent from Reviewable.io -->

2023-09-06 08:16 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 4 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZzE3TCDWDiIr3IDcW:-NddZ362BYoH2OKF6J6U:b-sq1dw1) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L71)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

agreed, it wont be unique
</blockquote></details>

There should be some unique identifier here to avoid duplicate entries. What about eventId?


<!-- Sent from Reviewable.io -->

2023-09-06 09:06 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZz4P30bQgWtbVdv8c:-NddjFls4TLd-6UJz_5H:b-aoh9si) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L65)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Agreed.
We need this field for showing the webhook triggered time on the events listing page.
</blockquote></details>

Its fine for now but I guess its still an open question whether we want to show webhook trigger time or webhook captured time on harness. So, we should confirm it at the earliest.


<!-- Sent from Reviewable.io -->

2023-09-06 09:07 UTC, mohitg0795 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZzE3TCDWDiIr3IDcW:-NddjlYW-ALVEmAB-9Ue:b-wxw5rc) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L71)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

yes, added eventID
</blockquote></details>

webhook identifier should be there? Only eventIdentifier + account id should be good enough right?


<!-- Sent from Reviewable.io -->

2023-09-06 20:41 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/Author.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/52450#-NdgD_epD652IWPKQe3R:-NdgD_epD652IWPKQe3S:bgwq1l8) ([raw file](https://github.com/harness/harness-core/blob/9ea311ae91ca7579200d391541bb07b75f053c88/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/Author.java#L23)):*
> ```Java
>   String name;
>   String email;
>   String login;
> ```

whats login?


<!-- Sent from Reviewable.io -->

2023-09-06 20:42 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/Author.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/52450#-NdgD_epD652IWPKQe3R:-NdgDjXS11SFpcZSQc3g:b-rkle3c) ([raw file](https://github.com/harness/harness-core/blob/9ea311ae91ca7579200d391541bb07b75f053c88/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/Author.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats login?
</blockquote></details>

I would suggest to save only required info for now. We shouldn't save anything redundant that we don't need at the moment.


<!-- Sent from Reviewable.io -->

2023-09-07 04:15 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52450)* status: 4 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/Author.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/52450#-NdgD_epD652IWPKQe3R:-NdhqGG8-UFtpqt884ao:b-2ai4l) ([raw file](https://github.com/harness/harness-core/blob/9ea311ae91ca7579200d391541bb07b75f053c88/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/Author.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I would suggest to save only required info for now. We shouldn't save anything redundant that we don't need at the moment.
</blockquote></details>

agreed, removing login
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZz4P30bQgWtbVdv8c:-NddlCii0dCvng3MmMAs:b-f860ni) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Its fine for now but I guess its still an open question whether we want to show webhook trigger time or webhook captured time on harness. So, we should confirm it at the earliest.
</blockquote></details>

IMO, we should show the  webhook trigger time, based on this we can go back to git and check the webhook deliveries based on this time stamp. 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/52450#-NdZzE3TCDWDiIr3IDcW:-NdhqB-55LpghgrBMwxB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/383a3aa0a4cfe29b3f6c0ee69321d2ab4eb80902/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

webhook identifier should be there? Only eventIdentifier + account id should be good enough right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-07 04:44 UTC, adivishy1 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java
> +  String triggerType;
As discussed, we will parsing only the push events, we are not storing it in the db, hence removing the field

2023-09-07 05:46 UTC, mohitg0795 approved these changes

2023-09-07 05:47 UTC, adivishy1 commented
trigger uts

2023-09-07 06:36 UTC, sribalij approved these changes

2023-09-07 06:37 UTC, adivishy1 commented
trigger review

2023-09-07 06:40 UTC, merged