feat: [CDS:77191]: Improve Helm Deployment Tracking [Delegate Side]
harness/harness-core pull request #52481
Opened 2023-09-05 19:49 UTC by alebuh

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-07 11:05 UTC, alebuh commented
trigger uts

2023-09-07 11:38 UTC, alebuh commented
trigger uts

2023-09-08 06:15 UTC, GoelPratyush99 submitted a review, later dismissed
Require fixing of UTs to pass the check

2023-09-08 06:35 UTC, abosii-harness requested changes

2023-09-08 06:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +          kubernetesConfig, commandRequest.getReleaseName(), getLabelSelectors(commandRequest), logCallback);
Can we refactor this logic in a way that we will stop readManifestFromHelmRelease each time? This can have a significant increase on the execution time

2023-09-08 06:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  @VisibleForTesting
nit: this method is already public, no need for this annotation

2023-09-08 06:35 UTC, abosii-harness commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +                            -> format("%s %s (%s)", expression.getKey(), expression.getOperator().toLowerCase(),
nit: can we have utility method that will create these expressions? For both match label selector and match expression?

2023-09-08 06:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +      Map<String, List<String>> labelSelectors, long timeoutInMillis) throws Exception {
nit: better to rename argument to something workloadsLabelSelectors

2023-09-08 06:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +                     .filter(pod
Is there any different logic here and the logic that we are already have? Maybe we can have a shared method?

2023-09-08 11:36 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +            .filter(resource
Changed to use existing logic for filtering workloads

2023-09-08 11:37 UTC, alebuh commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +    Kind kind = Kind.valueOf(this.resourceId.getKind());
Done

2023-09-08 11:42 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +          kubernetesConfig, commandRequest.getReleaseName(), getLabelSelectors(commandRequest), logCallback);
Did some refactoring and now we are reading the manifest twice maximum. Once before deployment/rollback (if isImprovedHelmTracking is enabled) and once after deployment/rollback (if isImprovedHelmTracking or steady check flags are enabled).

2023-09-08 11:44 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  @VisibleForTesting
My understanding that the purpose of this annotation is to justify why a method that can be private is public. But I might get that wrong. Anyway removed it now

2023-09-08 11:44 UTC, alebuh commented on 970-api-services-beans/src/main/java/io/harness/k8s/model/KubernetesResource.java
> +                            -> format("%s %s (%s)", expression.getKey(), expression.getOperator().toLowerCase(),
Done

2023-09-08 11:44 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +      Map<String, List<String>> labelSelectors, long timeoutInMillis) throws Exception {
Done

2023-09-08 11:46 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +                     .filter(pod
They are almost the same, just using different inputs. One is using Map and the other List for labels. I've extracted common code for both of them to avoid duplications.

2023-09-08 11:46 UTC, alebuh commented
trigger uts

2023-09-08 12:09 UTC, abosii-harness submitted a review, later dismissed

2023-09-08 13:21 UTC, alebuh commented
trigger uts

2023-09-08 13:21 UTC, abosii-harness approved these changes

2023-09-08 14:16 UTC, TarunUba1 reviewed
can you add the test cases you have tested locally

2023-09-08 14:16 UTC, TarunUba1 approved these changes

2023-09-08 14:18 UTC, GoelPratyush99 approved these changes

2023-09-08 14:22 UTC, alebuh commented
> can you add the test cases you have tested locally

done

2023-09-08 14:22 UTC, alebuh commented
trigger review

2023-09-08 14:52 UTC, alebuh commented
trigger ut7

2023-09-08 16:05 UTC, alebuh commented
/rebase

2023-09-08 16:15 UTC, alebuh commented
trigger uts

2023-09-08 18:02 UTC, merged