techdebt: [CI-9497]: Integrated SLSA external parameters
harness/harness-core pull request #52569
Opened 2023-09-07 06:55 UTC by sahithibanda01

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-07 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=52569) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=52569) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=52569) it.</sub>

2023-09-07 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=52569) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=52569) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=52569) it.</sub>

2023-09-07 09:27 UTC, harshjain12 requested changes

2023-09-07 09:27 UTC, harshjain12 commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/provenance/BuildMetadata.java
>  @Data
@value

2023-09-07 09:27 UTC, harshjain12 commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/provenance/ProvenanceGenerator.java
> +                             .externalParameters(ExternalParameters.builder()
passExternal params here directly

2023-09-07 09:27 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/DockerStep.java
> +    OptionalSweepingOutput optionalSweepingOutput =
refactor this method

2023-09-07 09:27 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/DockerStep.java
> +      Ambiance ambiance, StepArtifactsBuilder stepArtifactsBuilder, StepElementParameters stepParameters) {
Pass DockerStepInfo dockerStepInfo

2023-09-07 14:19 UTC, harshjain12 commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/provenance/TriggerMetadata.java
> +@Data
remove @Data
@value is sufficient

2023-09-11 09:23 UTC, sahithibanda01 commented
trigger messagecheck

2023-09-11 09:33 UTC, inderschera commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NGTriggerElementMapper.java
> +      RunDetailsMetadata from the previously existing entity (e.g.: The number of artifacts it is listening for could
let's undo this change.

2023-09-11 09:33 UTC, inderschera commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +      // Copy each pollingDocId to the corresponding RunDetailsMetadata in Triggers metadata.
let's undo this change.

2023-09-11 09:34 UTC, inderschera commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/generator/PollingItemGenerator.java
> +      because the trigger's metadata itself contains a list of RunDetailsMetadata, so we don't know which element of the
let's undo this change

2023-09-11 10:03 UTC, sahithibanda01 commented
trigger uts

2023-09-11 11:24 UTC, sahithibanda01 commented
trigger uts

2023-09-11 11:34 UTC, sahithibanda01 commented
trigger uts

2023-09-11 11:34 UTC, merged

2023-09-11 11:34 UTC, harshjain12 commented
uts are failing