fix: [CDS-78547]: add delegate selector for container step from connector
harness/harness-core pull request #52598
Opened 2023-09-07 16:21 UTC by sourabh-awashti

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-07 16:28 UTC, jennyjames21 commented
Question: Does change follow the hierarchy mentioned in the document? https://developer.harness.io/docs/platform/delegates/manage-delegates/select-delegates-with-selectors/

2023-09-08 08:21 UTC, sourabh-awashti commented
@jennyjames21 yes i will add the selectors from step, stage and pipeline  as well

2023-09-08 11:34 UTC, sourabh-awashti commented
trigger uts

2023-09-09 16:24 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52598)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-11 07:35 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52598)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-09-11 10:58 UTC, sourabh-awashti commented
trigger uts

2023-09-11 11:14 UTC, sourabh-awashti commented
trigger uts

2023-09-13 08:39 UTC, sourabh-awashti commented
trigger ut1, ut2, ut6, ut8, ut9

2023-09-13 11:16 UTC, yogesh-chauhan requested changes

2023-09-13 11:16 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/AbstractContainerStep.java
> +  private String getConnectorRef(ContainerStepSpec containerStepInfo) {
nit: private methods at the end of the class for better readability

2023-09-13 11:16 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerSpecUtils.java
> +          ((KubernetesClusterConfigDTO) k8sConnector.getConnectorConfig()).getDelegateSelectors();
I think we should do a type check here that is a k8s connector

2023-09-13 14:04 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/AbstractContainerStep.java
> +  private String getConnectorRef(ContainerStepSpec containerStepInfo) {
done

2023-09-13 14:04 UTC, sourabh-awashti commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerSpecUtils.java
> +          ((KubernetesClusterConfigDTO) k8sConnector.getConnectorConfig()).getDelegateSelectors();
done

2023-09-14 11:15 UTC, yogesh-chauhan requested changes

2023-09-14 11:15 UTC, yogesh-chauhan commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/AbstractContainerStep.java
> +    ContainerK8sInfra containerK8sInfra = (ContainerK8sInfra) containerStepInfo.getInfrastructure();
we should do a type check here

2023-09-14 11:23 UTC, yogesh-chauhan approved these changes

2023-09-14 11:24 UTC, sourabh-awashti commented
trigger uts

2023-09-14 11:59 UTC, sahilhindwani-harness approved these changes
> Reviewed 9 of 11 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52598)* status: 11 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-14 12:51 UTC, sourabh-awashti commented
trigger review

2023-09-14 12:53 UTC, merged