[feat]: [CDS-78115]: Resolve provisioner expressions before infra validations
harness/harness-core pull request #52606
Opened 2023-09-07 20:04 UTC by lovish1999

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-07 20:04 UTC, lovish1999 commented
trigger uts

2023-09-07 20:06 UTC, lovish1999 commented
trigger uts

2023-09-10 19:56 UTC, ivan-83 requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52606)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-cLN5CDN2jpAorv9F:-Ne-cLN5CDN2jpAorv9G:b-y7g74f) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L188)):*
> ```Java
>       case InfrastructureKind.PDC:
>         PdcInfrastructure pdcInfrastructure = (PdcInfrastructure) infrastructure;
>         if (isDynamicallyProvisioned) {
> ```

Due to the fact that an expression evaluator is only needed for PDC, we can move the following logic from `io.harness.cdng.infra.InfrastructureOutcomeProvider`class
`ProvisionerExpressionEvaluator expressionEvaluator =  
    providerExpressionEvaluatorProvider.getProviderExpressionEvaluator(  
        ambiance, infrastructure.getProvisionerStepIdentifier());`

to `io.harness.cdng.infra.PdcProvisionedInfrastructureMapper#toOutcome` method by propagating Ambiance from InfrastructureOutcomeProvider.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java` line 150 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-_QGA0Xjj6E_QhCqE:-Ne-_QGB2M9tB__vhBHz:b-9enm7q) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java#L150)):*
> ```Java
> 
>   private <T> boolean unresolvedExpression(ParameterField<T> input) {
>     return !ParameterField.isNull(input) && input.isExpression() && input.getValue() == null;
> ```

I think this is good, the value should be resolved at this point. Please remind me, do we explicitly need additional check here? Thanks in advance!
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-EIE46KQTLE3CLbsW:-Ne-EIE46KQTLE3CLbsX:bjvn1ed) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java#L28)):*
> ```Java
> import io.harness.cdng.infra.yaml.SshWinRmAzureInfrastructure;
> import io.harness.cdng.infra.yaml.TanzuApplicationServiceInfrastructure;
> import io.harness.evaluators.ProviderExpressionEvaluatorProvider;
> ```

Pls rename ProviderExpressionEvaluatorProvider >> ProvisionerExpressionEvaluatorProvider , and method ProviderExpressionEvaluatorProvider.getProviderExpressionEvaluator >> ProvisionerExpressionEvaluatorProvider.getProvisionerExpressionEvaluator
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-FH1I5By9xKAiwRGR:-Ne-FH1I5By9xKAiwRGS:b63w8tv) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java#L41)):*
> ```Java
> @Singleton
> @Slf4j
> public class InfrastructureTaskHelper {
> ```

This is related only to the provisioner, pls rename it InfrastructureTaskHelper >> InfrastructureProvisionerHelper


<!-- Sent from Reviewable.io -->

2023-09-11 08:58 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52606)* status: 12 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-cLN5CDN2jpAorv9F:-Ne2Pbd96Ang5ytFmqPS:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L188)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Due to the fact that an expression evaluator is only needed for PDC, we can move the following logic from `io.harness.cdng.infra.InfrastructureOutcomeProvider`class
`ProvisionerExpressionEvaluator expressionEvaluator =  
    providerExpressionEvaluatorProvider.getProviderExpressionEvaluator(  
        ambiance, infrastructure.getProvisionerStepIdentifier());`

to `io.harness.cdng.infra.PdcProvisionedInfrastructureMapper#toOutcome` method by propagating Ambiance from InfrastructureOutcomeProvider.
</blockquote></details>

ok
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java` line 150 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-_QGA0Xjj6E_QhCqE:-Ne2Pe3W8jtJhIK1zGJM:b-i6v1y3) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java#L150)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I think this is good, the value should be resolved at this point. Please remind me, do we explicitly need additional check here? Thanks in advance!
</blockquote></details>

This is because the provisioner evaluator method resolves expressions but still keeps isExpression as true so this method gives false false negative results then for resolved expressions. So added this extra condition. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-EIE46KQTLE3CLbsW:-Ne2OZfx46LxSIvOGIFW:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java#L28)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Pls rename ProviderExpressionEvaluatorProvider >> ProvisionerExpressionEvaluatorProvider , and method ProviderExpressionEvaluatorProvider.getProviderExpressionEvaluator >> ProvisionerExpressionEvaluatorProvider.getProvisionerExpressionEvaluator
</blockquote></details>

ok
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/52606#-Ne-FH1I5By9xKAiwRGR:-Ne2OY-y71dckfd-fru_:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/fecdd3f05dd63f582a5435396bd9b6d7a8dd3c83/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskHelper.java#L41)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This is related only to the provisioner, pls rename it InfrastructureTaskHelper >> InfrastructureProvisionerHelper
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-09-11 09:32 UTC, ivan-83 requested changes
> Reviewed 8 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52606)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/PdcProvisionedInfrastructureMapper.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/52606#-Ne2ZVjYCJvGWA1LMVC_:-Ne2ZVjYCJvGWA1LMVCa:b-bqfvhv) ([raw file](https://github.com/harness/harness-core/blob/5bc43e5d7dd2684de5a699aae2ec85713444dd4b/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/PdcProvisionedInfrastructureMapper.java#L52)):*
> ```Java
>     ProvisionerExpressionEvaluator expressionEvaluator = new ProvisionerExpressionEvaluator(Collections.emptyMap());
>     if (ambiance != null) {
>       expressionEvaluator = provisionerExpressionEvaluatorProvider.getProvisionerExpressionEvaluator(
> ```

Just call provisionerExpressionEvaluatorProvider.getProvisionerExpressionEvaluator(...) method. We are having a check for ambiance within the method and returning empty map if provisionerOutput is empty.


<!-- Sent from Reviewable.io -->

2023-09-11 12:17 UTC, lovish1999 commented
trigger uts

2023-09-11 12:53 UTC, lovish1999 commented
trigger uts

2023-09-11 19:21 UTC, yogesh-chauhan requested changes

2023-09-11 19:21 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java
> +import static java.lang.String.format;
please use a new line to separate imports from the below annotations

2023-09-11 19:21 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/PdcProvisionedInfrastructureMapper.java
> +  @Inject
should be private

2023-09-11 19:21 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/PdcProvisionedInfrastructureMapper.java
> +  public PdcInfrastructureOutcome toOutcome(PdcInfrastructure pdcInfrastructure, Ambiance ambiance,
please add a new line between class fields and methods

2023-09-11 19:21 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java
> +        infrastructureConfig.getInfrastructureDefinitionConfig().getSpec(), null, EnvironmentOutcome.builder().build(),
instead of passing as null, we should probably just remove the argument.
null arguments are hard to read/understand and easy to mistake for any class type

2023-09-11 19:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java
> +      infrastructureProvisionerHelper.resolveProvisionerExpressions(ambiance, spec);
don't we need to do this also in the if-block `if (isTaskStep(infraSpec.getKind())) {` at line:180 ?
or is it already taken care of ?

2023-09-12 10:37 UTC, lovish1999 commented
trigger uts

2023-09-12 10:54 UTC, lovish1999 commented
trigger uts

2023-09-12 10:57 UTC, lovish1999 commented
trigger messagecheck

2023-09-12 11:07 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 11 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52606#-:-Ne83m1y49ZcItUa8bnb:bnfp4nl)* status: 13 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-12 12:47 UTC, yogesh-chauhan reviewed
> Reviewed 5 of 11 files at r2, 1 of 1 files at r5, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52606)* status: 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-12 12:59 UTC, yogesh-chauhan approved these changes

2023-09-12 13:00 UTC, lovish1999 commented
trigger review

2023-09-12 13:08 UTC, tchaurasiya approved these changes

2023-09-12 13:11 UTC, merged