Logupretry
harness/harness-core pull request #52614
Opened 2023-09-08 04:05 UTC by smjt-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-08 04:05 UTC, smjt-h commented
trigger uts

2023-09-08 06:15 UTC, smjt-h commented
trigger messagecheck

2023-09-08 06:16 UTC, smjt-h commented
trigger messagecheck

2023-09-08 12:24 UTC, rafaelmart1ns requested changes

2023-09-08 12:24 UTC, rafaelmart1ns commented on product/log-service/download/zipwork/zipwork.go
>  	gErrGroup.Go(func() error {
`errgroup` works as an error channel. to switch to using a goroutine to handle errors, it would have to be changed or it would become redundant.

2023-09-11 05:54 UTC, smjt-h commented on product/log-service/download/zipwork/zipwork.go
>  	gErrGroup.Go(func() error {
errgroup waits for all goroutines to complete execution. By inroducing errch we are implementing a pattern that allows us to capture errors as they occur in individual goroutines while also waiting for all goroutines to finish. This can be useful if you want to handle errors as soon as they are detected rather than waiting for all goroutines to complete before handling errors.
tested this logic with a failure scenario(incorrect bucket) that works and results in proper error message output in cache.

2023-09-11 06:02 UTC, smjt-h commented
trigger messagecheck

2023-09-11 12:31 UTC, rafaelmart1ns commented on product/log-service/download/zipwork/zipwork.go
>  	gErrGroup.Go(func() error {
so we must remove the errgroup because it is redundant.

2023-09-13 14:33 UTC, smjt-h commented on product/log-service/download/zipwork/zipwork.go
>  	gErrGroup.Go(func() error {
It would still be required. The errgroup is used to manage and coordinate the execution of the two goroutines that perform the upload and zipping tasks concurrently. It ensures that both tasks are completed before proceeding further, in the successfull scenarios.

2023-09-13 14:51 UTC, smjt-h commented
trigger messagecheck

2023-09-14 12:42 UTC, vistaarjuneja commented on product/log-service/download/zipwork/zipwork.go
> +			errCh <- fmt.Errorf("zip upload: cannot upload zip to s3: %w", err)
@smjt-h didn't get why we need this logic - why can't we just return the error from the error group?

2023-09-14 12:43 UTC, vistaarjuneja commented on product/log-service/download/zipwork/zipwork.go
> +				errCh <- fmt.Errorf("zipfile: failed to copy: %w", err)
Also, why is the goroutine itself writing to errCh and then there's another goroutine waiting for a reply and then writing to errCh?
The logic/need is not super clear to me here.

2023-09-14 13:00 UTC, smjt-h commented on product/log-service/download/zipwork/zipwork.go
> +			errCh <- fmt.Errorf("zip upload: cannot upload zip to s3: %w", err)
the error group will wait for goroutines to finish, so in case there is any error in download or upload the worker waits infinitely and doesnt return(it gets stuck), Added this logic so that the goroutines return as soon as there is any errors.

2023-09-20 11:23 UTC, vistaarjuneja submitted a review, later dismissed

2023-09-20 13:36 UTC, smjt-h commented
trigger uts

2023-09-22 08:18 UTC, vistaarjuneja commented on product/log-service/download/zipwork/zipwork.go
> +	return err
Use `g.Wait()` at the end (after `ctx.Done()` to get the error)

2023-09-22 09:29 UTC, smjt-h commented on product/log-service/download/zipwork/zipwork.go
> +	return err
added,
Although global err variable will also return the error

2023-09-22 09:29 UTC, smjt-h commented
trigger uts

2023-09-22 09:31 UTC, vistaarjuneja approved these changes

2023-09-22 12:18 UTC, merged