feat: [CI-9415]: azure trigger changed file
harness/harness-core pull request #52616
Opened 2023-09-08 04:21 UTC by devkimittal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-08 04:51 UTC, devkimittal commented
trigger uts

2023-09-08 05:59 UTC, raghavharness requested changes

2023-09-08 05:59 UTC, raghavharness commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/FilepathTriggerFilter.java
> +      return gitConfigDTO.getConnectionType() == AzureRepoConnectionTypeDTO.REPO ? GitConnectionType.REPO
Shouldn't we return `GitConnectionType.PROJECT` instead of `GitConnectionType.ACCOUNT` ?

2023-09-08 05:59 UTC, raghavharness commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/SCMFilePathEvaluatorOnManager.java
> +  public Set<String> sanitiseFilesForAzureRepo(Set<String> changedFiles) {
Let's move this to a common utility like `GitClientHelper`

2023-09-08 05:59 UTC, raghavharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/scm/ScmPathFilterEvaluationTask.java
> +      if (filterQueryParams.getScmConnector() instanceof AzureRepoConnectorDTO) {
Add a UT in delegate too.

2023-09-08 06:06 UTC, devkimittal commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/FilepathTriggerFilter.java
> +      return gitConfigDTO.getConnectionType() == AzureRepoConnectionTypeDTO.REPO ? GitConnectionType.REPO
Will do, although wouldn't affect the flow

2023-09-08 10:39 UTC, devkimittal commented
trigger uts

2023-09-08 11:19 UTC, raghavharness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/scm/ScmPathFilterEvaluationTaskTest.java
> +  @Owner(developers = MEET)
LOL

2023-09-08 11:21 UTC, raghavharness approved these changes

2023-09-11 05:46 UTC, devkimittal commented
@archit-harness can you please review this today?

2023-09-11 11:20 UTC, Y0709 approved these changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52616)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-09-12 06:44 UTC, merged