feat: [PL-39453]: Upon deletion of secret from Harness, purge them from azure key vault
harness/harness-core pull request #52635
Opened 2023-09-08 10:58 UTC by sahibaCCM

## Describe your changes

Whenever we delete a deployment (we are using a Harness provider via Terraform), the secrets that exist in the Azure key vault are deleted but not purged. 
if we then attempt to re-deploy, it fails, as it cannot create secrets with these names, as they are sitting in a soft deleted state.
 
Tested for:
Created secret in akv, deleted it and created another secret with same identifier.
Verified the non purging of deleted secret in qa.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-13 08:34 UTC, sahibaCCM commented
trigger uts

2023-09-18 10:52 UTC, sahibaCCM commented
trigger uts

2023-09-18 16:12 UTC, sahibaCCM commented
trigger uts

2023-09-18 21:43 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 272 at r4](https://reviewable.io/reviews/harness/harness-core/52635#-NeeEoCmC0qG53zubh4a:-NeeEoCmC0qG53zubh4b:by6ovvn) ([raw file](https://github.com/harness/harness-core/blob/bca91856f5d12dca038f7b3e488c77a0c7343452/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L272)):*
> ```Java
>         log.info("deletion of key {} in azure vault {} was successful.", existingRecord.getEncryptionKey(),
>             azureVaultConfig.getVaultName());
>         if (azureVaultConfig.getIsPurgeEnabled() != null && azureVaultConfig.getIsPurgeEnabled()) {
> ```

In general we should avoid Code flows based on exception , What's the recommended way/example from Azure to handle delete with purge.


<!-- Sent from Reviewable.io -->

2023-09-18 21:46 UTC, piyush-harness reviewed
> Reviewed 13 of 14 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52635)* status: 15 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-19 20:01 UTC, sahibaCCM commented
trigger uts

2023-09-19 20:10 UTC, sahibaCCM commented
> _[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 272 at r4](https://reviewable.io/reviews/harness/harness-core/52635#-NeeEoCmC0qG53zubh4a:-NeeEoCmC0qG53zubh4b:by6ovvn) ([raw file](https://github.com/harness/harness-core/blob/bca91856f5d12dca038f7b3e488c77a0c7343452/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L272)):_
> 
> > ```java
> >         log.info("deletion of key {} in azure vault {} was successful.", existingRecord.getEncryptionKey(),
> >             azureVaultConfig.getVaultName());
> >         if (azureVaultConfig.getIsPurgeEnabled() != null && azureVaultConfig.getIsPurgeEnabled()) {
> > ```
> 
> In general we should avoid Code flows based on exception , What's the recommended way/example from Azure to handle delete with purge.

Changed implementation for soft deletion and purge

2023-09-20 04:52 UTC, sahibaCCM commented
trigger ut1, trigger ut2, trigger ut3, trigger ut4, trigger ut7

2023-09-21 05:51 UTC, sahibaCCM commented
trigger uts

2023-09-21 15:06 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 272 at r4](https://reviewable.io/reviews/harness/harness-core/52635#-NeeEoCmC0qG53zubh4a:-NesGiXK8fN3iW9IryVa:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/bca91856f5d12dca038f7b3e488c77a0c7343452/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L272)):*
<details><summary><i>Previously, sahibaCCM (Sahiba Khan) wrote…</i></summary><blockquote>

Changed implementation for soft deletion and purge
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-09-21 15:09 UTC, piyush-harness commented
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 257 at r7](https://reviewable.io/reviews/harness/harness-core/52635#-NesH2_9CI6BMJTjXlmC:-NesH2_9CI6BMJTjXlmD:bb5x50g) ([raw file](https://github.com/harness/harness-core/blob/1bfb2d1747030a025bc85eeb3024b82204e73aff/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L257)):*
> ```Java
>       log.info("deletion of key {} in azure vault {} was successful.", existingRecord.getEncryptionKey(),
>           azureVaultConfig.getVaultName());
>       if (azureVaultConfig.getIsPurgeEnabled() != null && azureVaultConfig.getIsPurgeEnabled()) {
> ```

Use azureVaultConfig.getIsPurgeEnabled() == Boolean.TRUE


<!-- Sent from Reviewable.io -->

2023-09-21 15:09 UTC, piyush-harness reviewed
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52635)* status: 15 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-21 15:44 UTC, sahibaCCM reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52635)* status: 15 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 257 at r7](https://reviewable.io/reviews/harness/harness-core/52635#-NesH2_9CI6BMJTjXlmC:-NesPTuC7IEEyMGkImWZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1bfb2d1747030a025bc85eeb3024b82204e73aff/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L257)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Use azureVaultConfig.getIsPurgeEnabled() == Boolean.TRUE
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-21 15:45 UTC, sahibaCCM commented
trigger uts

2023-09-21 22:13 UTC, piyush-harness approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52635)* status: 15 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 04:50 UTC, meenakshi-harness requested changes

2023-09-22 04:50 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java
> +  @Builder.Default Boolean isPurgeEnabled = false;
should we rename this to `purgeEnabled` or `enablePurge` ?

2023-09-22 04:50 UTC, meenakshi-harness commented on 931-secret-providers/src/java/software/wings/beans/AzureVaultConfig.java
> +  @Attributes(description = "Boolean value to is purge is enabled") private Boolean isPurgeEnabled;
check description

2023-09-22 04:50 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/AzureKeyVaultConnectorDTO.java
> +  @Builder.Default @Schema(description = "Boolean value to is purge is enabled") private Boolean isPurgeEnabled = false;
same

2023-09-22 04:50 UTC, meenakshi-harness commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/outcome/AzureKeyVaultConnectorOutcomeDTO.java
> +  @Schema(description = "Boolean value to is purge is enabled") private Boolean isPurgeEnabled;
same

2023-09-22 04:50 UTC, meenakshi-harness commented on 931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +      syncPoller.waitForCompletion();
any default limit till which this will wait?

2023-09-22 04:50 UTC, meenakshi-harness commented on 931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +          throw new SecretManagementDelegateException(AZURE_KEY_VAULT_OPERATION_ERROR, ex.toString(), ex, USER);
Lets say if delete is successful and purge fails. What is user experience? Can we add screenshots of API response in description?

2023-09-22 04:50 UTC, meenakshi-harness commented on 931-encryption-service/src/test/io/harness/encryptors/clients/AzureVaultEncryptorTest.java
> +    when(keyVaultClient.getSecret(any())).thenThrow(ResourceNotFoundException.class);
this test case still valid given we have removed this piece off code?

2023-09-22 06:57 UTC, sahibaCCM commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java
> +  @Builder.Default Boolean isPurgeEnabled = false;
It's `isPurgeEnabled`; but we can make it enable purge as we. They both essentially mean the same thing

2023-09-22 06:57 UTC, sahibaCCM commented on 931-secret-providers/src/java/software/wings/beans/AzureVaultConfig.java
> +  @Attributes(description = "Boolean value to is purge is enabled") private Boolean isPurgeEnabled;
Will edit the description

2023-09-22 06:58 UTC, sahibaCCM commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/AzureKeyVaultConnectorDTO.java
> +  @Builder.Default @Schema(description = "Boolean value to is purge is enabled") private Boolean isPurgeEnabled = false;
will edit

2023-09-22 06:58 UTC, sahibaCCM commented on 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/azurekeyvaultconnector/outcome/AzureKeyVaultConnectorOutcomeDTO.java
> +  @Schema(description = "Boolean value to is purge is enabled") private Boolean isPurgeEnabled;
will edit

2023-09-22 07:00 UTC, sahibaCCM commented on 931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +      syncPoller.waitForCompletion();
As mention in AZURE docs it can take up to 90s
Since we want the job to be successful we are moving away from previous implementation where we kept the time as 30s followed by continuous polling.

2023-09-22 07:01 UTC, sahibaCCM commented on 931-encryption-service/src/test/io/harness/encryptors/clients/AzureVaultEncryptorTest.java
> +    when(keyVaultClient.getSecret(any())).thenThrow(ResourceNotFoundException.class);
I had removed the occurrences from all code; this line is ineffective will remove it.

2023-09-22 07:18 UTC, sahibaCCM commented on 931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +          throw new SecretManagementDelegateException(AZURE_KEY_VAULT_OPERATION_ERROR, ex.toString(), ex, USER);
It would return success; It is the current behaviour. Even if the soft delete fails in delegate task we dont propagate to the user. We remove the secret from harness side though.

2023-09-22 07:19 UTC, sahibaCCM commented on 931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +          throw new SecretManagementDelegateException(AZURE_KEY_VAULT_OPERATION_ERROR, ex.toString(), ex, USER);
So the experience remains consistent with what we had for soft delete

2023-09-23 12:48 UTC, sahibaCCM commented
trigger uts

2023-09-23 21:37 UTC, sahibaCCM commented
trigger ut1

2023-09-24 05:44 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java
> +  @Builder.Default Boolean isPurgeEnabled = false;
yes let rename it.

2023-09-24 19:28 UTC, sahibaCCM commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/azurekeyvaultconnector/AzureKeyVaultConnector.java
> +  @Builder.Default Boolean isPurgeEnabled = false;
Done

2023-09-24 19:28 UTC, sahibaCCM commented
trigger uts

2023-09-24 22:11 UTC, sahibaHarness commented
trigger ut4

2023-09-25 06:00 UTC, meenakshi-harness commented on 931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java
> +          throw new SecretManagementDelegateException(AZURE_KEY_VAULT_OPERATION_ERROR, ex.toString(), ex, USER);
You mean we will soft delete secret from azure and not throw any error to user in case purge fails - also if purge is enabled on Azure Vault?
Not sure if this is the right behaviour, we should at-least give some warning/error as in this case user will be expecting purge to be successful (Given the use-case in ticket, they can try create secret will same name and it would fail for them).

2023-09-26 07:29 UTC, sahibaHarness commented
trigger uts

2023-09-26 19:01 UTC, sahibaHarness commented
trigger uts

2023-09-26 19:07 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        throw ex;
this should be only when purge enabled right?

2023-09-27 05:59 UTC, sahibaHarness commented on 120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java
> +        throw ex;
In the case when soft delete fails; they can trigger delete again and it would work.

2023-09-27 06:44 UTC, sahibaHarness commented
trigger uts

2023-09-27 07:44 UTC, sahibaHarness commented
trigger uts

2023-09-28 07:40 UTC, sahibaHarness commented
trigger uts

2023-09-28 08:54 UTC, sahibaHarness commented
trigger ut3, ut4, ut8, ut9

2023-09-28 08:55 UTC, sahibaHarness commented
trigger ut5, ut7

2023-09-28 08:56 UTC, sahibaHarness commented
trigger ut0, ut2

2023-09-28 09:42 UTC, sahibaHarness commented
trigger ut6

2023-09-28 20:58 UTC, sahibaHarness commented
trigger ut6

2023-09-29 05:46 UTC, sahibaHarness commented
trigger uts

2023-09-30 08:34 UTC, sahibaHarness commented
trigger ut0, ut1, ut4

2023-10-03 04:19 UTC, sahibaHarness commented
trigger ut4

2023-10-03 04:20 UTC, meenakshi-harness approved these changes

2023-10-03 05:58 UTC, sahibaHarness commented
trigger ut4

2023-10-03 08:26 UTC, krishi0408 commented
trigger ut3,ut4,ut5,ut6,ut7,ut8,ut9

2023-10-03 12:32 UTC, sahibaHarness commented
trigger uts

2023-10-03 16:45 UTC, sahibaHarness commented
trigger ut6, ut9

2023-10-04 05:59 UTC, sahibaHarness commented
trigger uts

2023-10-04 07:02 UTC, sahibaHarness commented
trigger uts

2023-10-04 09:23 UTC, sahibaHarness commented
trigger ut9

2023-10-04 12:15 UTC, merged