fix: [CDS-78875]: Adding a new collection for chaos API
harness/harness-core pull request #52657
Opened 2023-09-08 15:38 UTC by TarunUba1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-12 06:52 UTC, TarunUba1 commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +      createReleaseDetails(ambiance, serviceStepOutcome, infrastructureOutcome, serverInstanceInfoList.get(0));
try not to use serverInstanceInfo

2023-09-12 06:54 UTC, TarunUba1 commented on 126-instance/src/main/java/io/harness/entities/ReleaseDetailsMapping.java
> +  private List<ReleaseDetails> releaseDetailsList;
instead of list have 1-1 mapping

2023-09-12 15:49 UTC, abosii-harness requested changes

2023-09-12 15:49 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/dtos/ReleaseDetailsMappingDTO.java
> +public class ReleaseDetailsMappingDTO {
/Do we need these details in DTO? I guess we can remove infraKey and return a List of ReleaseDetailsDTO

2023-09-12 15:49 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/releasedetailsmapping/ReleaseDetailsMappingService.java
> +  Optional<ReleaseDetailsMappingDTO> createNewOrReturnExistingReleaseDetailsMapping(
nit: name can be just upsert

2023-09-12 15:49 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/releasedetailsmapping/ReleaseDetailsMappingServiceImpl.java
> +  public Optional<ReleaseDetailsMappingDTO> createNewOrReturnExistingReleaseDetailsMapping(
Why we would need this back?

2023-09-12 15:49 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/ServerInstanceInfo.java
> +  public String getNamespace() {
do we need getNamespace and getReleaseName?

2023-09-12 16:17 UTC, TarunUba1 commented on 126-instance/src/main/java/io/harness/service/releasedetailsmapping/ReleaseDetailsMappingService.java
> +  Optional<ReleaseDetailsMappingDTO> createNewOrReturnExistingReleaseDetailsMapping(
we are not updating so upsert feels wrong

2023-09-13 04:52 UTC, TarunUba1 commented
trigger uts

2023-09-13 05:35 UTC, TarunUba1 commented
trigger uts

2023-09-13 06:37 UTC, abhinavsingh1196 requested changes

2023-09-13 06:37 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +  private Scope getScopeOfEntity(@NotEmpty String entity) {
- this method should go in `ScopeHelper`
- nit: parameter should be named `entityRef`

2023-09-13 06:37 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +      throw new InvalidRequestException(
should we fail it or just error logging would be enough?

2023-09-13 06:37 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +    ReleaseDetailsMappingDTO releaseDetailsMappingDTO =
this doesn't optimize it much, but I feel it's better:
we're calling this method for each serverInstanceInfo, but all the logic before creating the `ReleaseDetailsMappingDTO` is same. So, we could just create it once and pass to the loop which creates the release details mapping and persists it?

2023-09-13 06:37 UTC, abhinavsingh1196 commented on 126-instance/src/main/java/io/harness/service/releasedetailsmapping/ReleaseDetailsMappingService.java
> +   */
nit: javadoc not needed, method is self explanatory

2023-09-13 06:37 UTC, abhinavsingh1196 commented on 126-instance/src/test/java/io/harness/service/deploymentevent/DeploymentEventListenerTest.java
> +        .createNewOrReturnExistingReleaseDetailsMapping(any());
we should add UT here which verify that `createNewOrReturnExistingReleaseDetailsMapping` is executed n times for n serverInstanceInfo's

2023-09-13 06:37 UTC, abhinavsingh1196 commented on 126-instance/src/test/java/io/harness/service/releasedetailsmapping/ReleaseDetailsMappingServiceImplTest.java
> +  @Owner(developers = VIKYATH_HAREKAL)
nit: wrong author 😄

2023-09-13 06:37 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync/ServerInstanceInfo.java
> +  public String getReleaseKey() {
nit: I see that all current usages are handling null properly, but maybe we can add @Nullable here to indicate for any future usages

2023-09-13 11:14 UTC, TarunUba1 commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +      throw new InvalidRequestException(
we fail in case of infraMapping, the only reason why it will fail i feel is when we will run into mongo disconnecition which i feel is a genuine reason to fail but then it will be failed in other function also. keeping it similar to createInfrastructureMappingIfNotExists

2023-09-13 12:10 UTC, TarunUba1 commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +  private Scope getScopeOfEntity(@NotEmpty String entity) {
scopHelper is used in IdentifierRefHelper so creates a circular loop, best to do here only to incorporate project also

2023-09-13 12:52 UTC, abhinavsingh1196 submitted a review, later dismissed

2023-09-13 12:54 UTC, abosii-harness requested changes

2023-09-13 12:54 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +        createReleaseDetails(
What if there are 100+ instances? Will we create in less than a second 100 write requests. I do remember we discussed to do this based on instances to handle all possible namespaces so we should aggregate first unique namespaces and only then try to save it. It can be done with the next logic:
1. Pass all serviceInstanceInfo list
2. Store all release keys in a set
3. for each element in set create release details mapping

2023-09-13 12:54 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +  private void createReleaseDetails(
nit: name should be createReleaseDetailsMapping

2023-09-13 12:54 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +      throw new InvalidRequestException(
I kinda agree here, let's just log it

2023-09-13 14:32 UTC, TarunUba1 commented
trigger uts

2023-09-13 15:03 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/deploymentevent/DeploymentEventListener.java
> +      Map<String, ServerInstanceInfo> releaseKeyMap = getReleaseKeyToServerInstanceInfoMap(serverInstanceInfoList);
Is there any reason why we need this map? Do we actually need to pass ServerInstanceInfo to the create method? I would guess that release key should be enough and then the logic can be simple:
serverInstanceInfoList.stream().map(ServerInstanceInfo::getReleaseKey).filter(Objects::nonNull).collect(Collectors.toSet())
and the just loop through all release keys

2023-09-14 06:16 UTC, TarunUba1 commented
trigger uts

2023-09-14 07:38 UTC, abosii-harness approved these changes

2023-09-14 07:47 UTC, TarunUba1 commented
trigger gitleaks

2023-09-14 07:51 UTC, namantalaycha10 approved these changes

2023-09-14 07:52 UTC, TarunUba1 commented
trigger review

2023-09-14 07:54 UTC, merged