fix: [CDS-75773]: Make GitOps steps work without OPTIMIZED_GIT_FETCH_…
harness/harness-core pull request #52656
Opened 2023-09-08 15:12 UTC by meenaravichandran1

…FILES FF

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-08 20:47 UTC, meenaravichandran1 commented
trigger messagecheck

2023-09-08 22:28 UTC, rohitk-h requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52656)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 474 at r2](https://reviewable.io/reviews/harness/harness-core/52656#-NdqtYqF5qu5ANquIQFm:-NdqtYqF5qu5ANquIQFn:boywdjp) ([raw file](https://github.com/harness/harness-core/blob/2a4de3327057c1c462124a45bc592e0e49848c20/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L474)):*
> ```Java
>   }
> 
>   public GitStoreDelegateConfig getGitStoreDelegateConfigWithApiAccess(@Nonnull GitStoreConfig gitstoreConfig,
> ```

Can we write some unit tests for the method? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/52656#-NdqsMp58NM7c20fd3U2:-NdqsMp58NM7c20fd3U3:b-h5d7bo) ([raw file](https://github.com/harness/harness-core/blob/2a4de3327057c1c462124a45bc592e0e49848c20/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java#L94)):*
> ```Java
>       ExceptionMessageSanitizer.storeAllSecretsForSanitizing(
>           GitApiAccessDecryptionHelper.getAPIAccessDecryptableEntity(gitStoreDelegateConfig.getGitConfigDTO()),
>           gitStoreDelegateConfig.getApiAuthEncryptedDataDetails());
> ```

can this be replaced by the new method `setApiAccess`? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/52656#-NdqtDaV0gHGc-wbzX0o:-NdqtDaV0gHGc-wbzX0p:bx6i5mm) ([raw file](https://github.com/harness/harness-core/blob/2a4de3327057c1c462124a45bc592e0e49848c20/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java#L141)):*
> ```Java
>       GitConfigDTO gitConfigDTO = ScmConnectorMapper.toGitConfigDTO(gitStoreDelegateConfig.getGitConfigDTO());
>       gitDecryptionHelper.decryptGitConfig(gitConfigDTO, gitStoreDelegateConfig.getEncryptedDataDetails());
>       setApiAccess(gitStoreDelegateConfig);
> ```

nit: Method could get refactored into something below:



_Code snippet:_
```Java
setApiAccess(gitStoreDelegateConfig);
if (gitStoreDelegateConfig.isOptimizedFilesFetch()) {
      executionLogCallback.saveExecutionLog("Using optimized file fetch");
    } else {
      GitConfigDTO gitConfigDTO = ScmConnectorMapper.toGitConfigDTO(gitStoreDelegateConfig.getGitConfigDTO());
      gitDecryptionHelper.decryptGitConfig(gitConfigDTO, gitStoreDelegateConfig.getEncryptedDataDetails());
      
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/52656#-NdqrKiY8lAFdL8f3BZa:-NdqrKiZ6TmGaLna15JE:blznjkd) ([raw file](https://github.com/harness/harness-core/blob/2a4de3327057c1c462124a45bc592e0e49848c20/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitops/GitOpsTaskHelper.java#L145)):*
> ```Java
>   }
> 
>   public void setApiAccess(GitStoreDelegateConfig gitStoreDelegateConfig) {
> ```

This can be a private method


<!-- Sent from Reviewable.io -->

2023-09-09 01:29 UTC, rohitk-h reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52656)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-10 07:43 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +        .build();
instead of writing the entire method from scratch, can we look into reusing existing code ? It becomes tought to understand differnces between these multiple methods when doing some refactoring

2023-09-11 02:55 UTC, rohitk-h reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52656)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-11 02:55 UTC, rohitk-h approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52656)* status: 6 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-11 13:13 UTC, meenaravichandran1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +        .build();
I initially didn't write a new method and reused the existing getGitStoreDelegateConfig() method with passing optimizedFetchFiles parameter as true.

Later changed that becasue I noticed it has this condition,

`    if (optimizedFilesFetch) {
      scmConnector = (ScmConnector) connectorDTO.getConnectorConfig();
      addApiAuthIfRequired(scmConnector);
      final DecryptableEntity apiAccessDecryptableEntity =
          GitApiAccessDecryptionHelper.getAPIAccessDecryptableEntity(scmConnector);
      apiAuthEncryptedDataDetails =
          secretManagerClientService.getEncryptionDetails(basicNGAccessObject, apiAccessDecryptableEntity);
    } else if (githubAppAuthentication) {
      scmConnector = (ScmConnector) connectorDTO.getConnectorConfig();
      encryptedDataDetails =
          gitConfigAuthenticationInfoHelper.getGithubAppEncryptedDataDetail(scmConnector, basicNGAccessObject);
    }`

If I use this method, the if condition will always be executed and the githubAppAuthentication will be ignored even when it is set.

Hence wrote a new method.

2023-09-12 18:12 UTC, manavjot-harness approved these changes

2023-09-12 18:15 UTC, meenaravichandran1 commented
trigger review

2023-09-12 18:15 UTC, meenaravichandran1 commented
trigger uts

2023-09-12 18:55 UTC, merged