fix:[CDS-77767]: [StockX] Error showing in the UI when opening a template or issuing reconcile
harness/harness-core pull request #52669
Opened 2023-09-08 23:03 UTC by sribalij

## Describe your changes
Currently when a runtime exception containing a MismatchedInputException is thrown while resolving the <+input> field the error is not handled and a http 500 error is thrown with the following message
![image](https://github.com/harness/harness-core/assets/106265061/c43c7086-ec12-4079-9d82-0e8f6aef223a)

With this change, we are handling exclusively MismatchedInputException showing an invalid yaml exception with.
![image](https://github.com/harness/harness-core/assets/106265061/131b4ac5-67bd-488b-a625-411cc51fac60)

The reason we have to add it insde the Exception bucket is because MismatchedInputException is wrapped inside a runtime exception and hence we are handling it via `e.getCause() instanceof MismatchedInputException`

Added Junits and verified on the UI.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-09 01:24 UTC, rohitk-h approved these changes

2023-09-10 06:41 UTC, archit-harness requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52669)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/validation/RuntimeInputValuesValidator.java` line 226 at r1](https://reviewable.io/reviews/harness/harness-core/52669#-NdxoXpW8RdGrxS3J-8T:-NdxoXpW8RdGrxS3J-8U:b-3shjow) ([raw file](https://github.com/harness/harness-core/blob/04a6aa295a00f664e623038f2d164228cfe82410/953-yaml-commons/src/main/java/io/harness/pms/yaml/validation/RuntimeInputValuesValidator.java#L226)):*
> ```Java
>     } catch (Exception e) {
>       if (e.getCause() instanceof MismatchedInputException) {
>         throw new InvalidYamlException("Please check the input value provided, Input value: " + inputSetValue);
> ```

i think we should hint that add quotes around default value, or space after semi-colon : 
cc: @shalini-agr 


<!-- Sent from Reviewable.io -->

2023-09-11 22:12 UTC, sribalij reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52669)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/validation/RuntimeInputValuesValidator.java` line 226 at r1](https://reviewable.io/reviews/harness/harness-core/52669#-NdxoXpW8RdGrxS3J-8T:-Ne5HnG_4yRfkKmB_toj:b-yievma) ([raw file](https://github.com/harness/harness-core/blob/04a6aa295a00f664e623038f2d164228cfe82410/953-yaml-commons/src/main/java/io/harness/pms/yaml/validation/RuntimeInputValuesValidator.java#L226)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think we should hint that add quotes around default value, or space after semi-colon : 
cc: @shalini-agr
</blockquote></details>

Yes, trying to think if  we mention that it might be specific to "<+input.default(..)>". Trying to give a more generic error if it fails while resolving other values also?


<!-- Sent from Reviewable.io -->

2023-09-11 22:16 UTC, rohitk-h approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52669)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-20 06:54 UTC, closed without merging