[fix]: [PL-41154]: Stop creating redundant ACLs and delete existing ones
harness/harness-core pull request #52668
Opened 2023-09-08 20:49 UTC by ashishsanodia-harness

## Describe your changes
Stop creating redundant ACLs and delete existing ones

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-08 20:50 UTC, ashishsanodia-harness commented
trigger uts

2023-09-09 18:18 UTC, ashishsanodia-harness commented
trigger uts

2023-09-10 10:37 UTC, ashishsanodia-harness commented
trigger uts

2023-09-13 05:25 UTC, ashishsanodia-harness commented
trigger ut0, ut7

2023-09-13 05:26 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/52668#-Ne38DnQ8EuUqJ4m9Nqt:-NeC-DJ43C15W3rbRhOA:b7da51g) ([raw file](https://github.com/harness/harness-core/blob/235ef802bd0cf6c47c5a3b8c7982168dfac94781/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L88)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@ashishsanodia-harness I think we will waste compute power in doing unnecessary work because once redundant ACLs are removed, we would still end up iterating over all ACLs and check if its valid or not
</blockquote></details>

Done . Skipping job execution if already ran successfully


<!-- Sent from Reviewable.io -->

2023-09-14 05:44 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHBwIg0pD74ZxWp6on:-NeHBwIg0pD74ZxWp6oo:b2qq8ej) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L165)):*
> ```Java
>     long aclCount = aclGeneratorService.createACLs(roleAssignmentDBO, principals, permissions, resourceSelectors);
>     assertThat(aclCount).isEqualTo(60000);
> ```

Why change max of ACLs created in batch?
___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 206 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHD3ed7JC9LHNBrulp:-NeHD3ed7JC9LHNBrulq:b-h2cd65) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L206)):*
> ```Java
>     long aclCount = aclGeneratorService.createACLs(roleAssignmentDBO, principals, permissions, resourceSelectors);
> 
>     assertThat(aclCount).isEqualTo(1000000);
> ```

Why changing allowed limit from 2M to 1M in test?


<!-- Sent from Reviewable.io -->

2023-09-14 06:21 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 280 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHDg-m5xVbm-Ci6tSc:-NeHDg-m5xVbm-Ci6tSd:bwgoawk) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L280)):*
> ```Java
>   @Owner(developers = ASHISHSANODIA)
>   @Category(UnitTests.class)
>   public void createACLsOnlyForExactResourceTypeAndMarkRedundantACLDisabled() {
> ```

I think we dont this test case as we are no marking redundant ACLs anymore.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 228 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHLTra2j4JlneFy-VM:-NeHLTra2j4JlneFy-VN:b-olv0jb) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L228)):*
> ```Java
>         offset = firstAcl.getId();
>       }
>       mongoTemplate.save(ACLOptimizationRemovalOffset.builder().offset(offset).build());
> ```

In case of SMP env, wont this always set 1st ACL as offset?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 235 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHJdoM-48lcChyG6mo:-NeHJdoN0EKQV5E1Ddgp:bhehl1r) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L235)):*
> ```Java
>     Query aclQuery = new Query();
>     aclQuery.addCriteria(where(ACLKeys.id).gte(new ObjectId(offset)).and(ACLKeys.enabled).is(false));
>     aclQuery.cursorBatchSize(10000);
> ```

Lets have batch size of 1k.


<!-- Sent from Reviewable.io -->

2023-09-14 06:34 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/test/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJobTest.java` line 240 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHOPc-7vdbDNwyQu_6:-NeHOPc-7vdbDNwyQu_7:bqtbjkg) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/service/src/test/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJobTest.java#L240)):*
> ```Java
> 
>     ACLOptimizationRemovalOffset newOffset = mongoTemplate.findOne(new Query(), ACLOptimizationRemovalOffset.class);
>     assertThat(newOffset.getOffset()).isEqualTo("some-offset");
> ```

We can assert here that aclRepository remove method is not invoked.


<!-- Sent from Reviewable.io -->

2023-09-14 11:35 UTC, ashishsanodia-harness commented
trigger uts

2023-09-14 11:45 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHBwIg0pD74ZxWp6on:-NeIV7iz3aXpG5jJB8Fv:b-qp9a0x) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L165)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why change max of ACLs created in batch?
</blockquote></details>

This is based on test data I am using. but yeah refactored again to avoid any confusion.


<!-- Sent from Reviewable.io -->

2023-09-14 11:45 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 206 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHD3ed7JC9LHNBrulp:-NeIVcNK422ocDukKMX6:b-qp9a0x) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L206)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why changing allowed limit from 2M to 1M in test?
</blockquote></details>

This is based on test data I am using. but yeah refactored again to avoid any confusion.


<!-- Sent from Reviewable.io -->

2023-09-14 11:45 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 280 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHDg-m5xVbm-Ci6tSc:-NeIVhRDCRf41mBTEwz7:b-c5d4bc) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L280)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think we dont this test case as we are no marking redundant ACLs anymore.
</blockquote></details>

Fixed test name


<!-- Sent from Reviewable.io -->

2023-09-14 11:47 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 228 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHLTra2j4JlneFy-VM:-NeIVlZv8uR5o2H1EmM3:bew3kyj) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L228)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

In case of SMP env, wont this always set 1st ACL as offset?
</blockquote></details>

In both SMP and SAAS it will pick first acl entry. This logic is to support resume capability if job dies in between without removing all redundant acls.


<!-- Sent from Reviewable.io -->

2023-09-14 11:47 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 235 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHJdoM-48lcChyG6mo:-NeIW1cn6WpvS4UHt1YD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L235)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets have batch size of 1k.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-14 11:48 UTC, ashishsanodia-harness commented
*[`access-control/service/src/test/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJobTest.java` line 240 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHOPc-7vdbDNwyQu_6:-NeIW4au1KKUWFgmeqqa:b-iau5wy) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/service/src/test/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJobTest.java#L240)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We can assert here that aclRepository remove method is not invoked.
</blockquote></details>

We already asserting on no offset change. it is not using acl repo to remove. Also repository is not mock here. This should be suffice


<!-- Sent from Reviewable.io -->

2023-09-14 13:16 UTC, ashishsanodia-harness commented
trigger ut4

2023-09-15 03:19 UTC, ankit-harness requested changes
> Reviewed 1 of 20 files at r1, 3 of 4 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLqOeWEljeyMUyMi8M:-NeLqOeWEljeyMUyMi8N:b301v5) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L98)):*
> ```Java
> 
>       // First remove all disabled ACLs
>       try (CloseableIterator<ACL> iterator = runQueryWithBatchForDisabledAcls()) {
> ```

Simplified version of this code



_Code snippet:_
```Java
try (CloseableIterator<ACL> iterator = runQueryWithBatchForDisabledAcls()) {
    String offset = REFERENCE_TIMESTAMP;
    int totalRemoved = 0;
    BulkOperations bulkOperations = mongoTemplate.bulkOps(UNORDERED, ACL.class);

    while (iterator.hasNext()) {
        ACL acl = iterator.next();
        offset = acl.getId();

        // Create a query to remove the ACL
        Query query = new Query();
        query.addCriteria(where(ACLKeys.id).is(acl.getId()));
        bulkOperations.remove(query);

        totalRemoved++;

        // Check if it's time to execute the bulk removal
        if (totalRemoved % BATCH_SIZE == 0) {
            log.info(DEBUG_MESSAGE + "Removing disabled ACLs. total: {}, removed: {}", bulkOperations.execute(), totalRemoved);

            // Reset bulkOperations for the next batch
            bulkOperations = mongoTemplate.bulkOps(UNORDERED, ACL.class);

            // Update the offset
            updateOffset(offset);
        }
    }

    // Execute any remaining removals
    if (totalRemoved % BATCH_SIZE != 0) {
        log.info(DEBUG_MESSAGE + "Removing disabled ACLs. total: {}, removed: {}", bulkOperations.execute(), totalRemoved);

        // Update the offset
        updateOffset(offset);
    }
}
```
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 187 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLntBA0k6F1Gy6aKff:-NeLntBA0k6F1Gy6aKfg:baozl1p) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L187)):*
> ```Java
> 
>   private boolean isJobAlreadyExecutedSuccessfully() {
>     ACLOptimizationRemovalOffset existingOffset = mongoTemplate.findOne(
> ```

Let's rename this class to RemoveRedundantACLJobState. This state will have 2 fields - offset and jobCompleted
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 190 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLoHwH5-fWseAqqypo:-NeLoHwH5-fWseAqqypp:b-moln6t) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L190)):*
> ```Java
>         new Query().with(by(ASC, ACLOptimizationRemovalOffsetKey.id)).limit(1), ACLOptimizationRemovalOffset.class);
>     if (nonNull(existingOffset)) {
>       return existingOffset.isSuccessful();
> ```

state.isJobCompleted()
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 228 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLop9BEExRR8Z3clYb:-NeLop9BEExRR8Z3clYc:b-agh9eh) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L228)):*
> ```Java
>         offset = firstAcl.getId();
>       }
>       mongoTemplate.save(ACLOptimizationRemovalOffset.builder().offset(offset).build());
> ```

Shouldn't we save the offset after removal?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 233 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLpCzQ27DmvO98iTdu:-NeLpCzQ27DmvO98iTdv:bpbe50n) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L233)):*
> ```Java
>     }
> 
>     Query aclQuery = new Query();
> ```

override max query execution time. by default we have 30 sec limit. we applied it recently.


<!-- Sent from Reviewable.io -->

2023-09-15 03:20 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLqOeWEljeyMUyMi8M:-NeLq_3_75sLT7503LB0:b-lpb08o) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L98)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Simplified version of this code
</blockquote></details>

You can add Thread.sleep


<!-- Sent from Reviewable.io -->

2023-09-15 03:26 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 135 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLrlcn6BLF7982oODy:-NeLrlcn6BLF7982oODz:bmgnav6) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L135)):*
> ```Java
>       // We already marked ACLs disabled and have offset for last disabled ACL
>       // Using that offset start removing redundant ACLs which got created after this offset
>       try (CloseableIterator<ACL> iterator = runQueryWithBatch()) {
> ```

try (CloseableIterator<ACL> iterator = runQueryWithBatch()) {
    String offset = REFERENCE_TIMESTAMP;
    int totalRemoved = 0; // Counting only removed ACLs
    BulkOperations bulkOperations = mongoTemplate.bulkOps(UNORDERED, ACL.class);

    while (iterator.hasNext()) {
        ACL acl = iterator.next();
        offset = acl.getId();

        Query query = new Query().addCriteria(where(ACLKeys.id).is(acl.getId()));

        if (!inMemoryPermissionRepository.isPermissionCompatibleWithResourceSelector(
                acl.getPermissionIdentifier(), acl.getResourceSelector())) {
            bulkOperations.remove(query);
            totalRemoved++;
        }

        if (totalRemoved % BATCH_SIZE == 0) {
            executeAndLogBulkRemoval(bulkOperations, totalRemoved);
            bulkOperations = mongoTemplate.bulkOps(UNORDERED, ACL.class);
            updateOffset(offset);
        }
    }

    if (totalRemoved % BATCH_SIZE != 0) {
        executeAndLogBulkRemoval(bulkOperations, totalRemoved);
        updateOffset(offset);
    }

    markJobAsSuccessful();
} catch (Exception ex) {
    log.error(DEBUG_MESSAGE + "Exception occurred while processing ACLs ", ex);
}


You can add Thread.sleep


<!-- Sent from Reviewable.io -->

2023-09-15 03:27 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 135 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLsBF15iC-JO6kG9zl:-NeLsBF15iC-JO6kG9zm:bbu25wq) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L135)):*
> ```Java
>       // We already marked ACLs disabled and have offset for last disabled ACL
>       // Using that offset start removing redundant ACLs which got created after this offset
>       try (CloseableIterator<ACL> iterator = runQueryWithBatch()) {
> ```

Simplified version. You can add Thread.sleep



_Code snippet:_
```Java
try (CloseableIterator<ACL> iterator = runQueryWithBatch()) {
    String offset = REFERENCE_TIMESTAMP;
    int totalRemoved = 0; // Counting only removed ACLs
    BulkOperations bulkOperations = mongoTemplate.bulkOps(UNORDERED, ACL.class);

    while (iterator.hasNext()) {
        ACL acl = iterator.next();
        offset = acl.getId();

        Query query = new Query().addCriteria(where(ACLKeys.id).is(acl.getId()));

        if (!inMemoryPermissionRepository.isPermissionCompatibleWithResourceSelector(
                acl.getPermissionIdentifier(), acl.getResourceSelector())) {
            bulkOperations.remove(query);
            totalRemoved++;
        }

        if (totalRemoved % BATCH_SIZE == 0) {
            executeAndLogBulkRemoval(bulkOperations, totalRemoved);
            bulkOperations = mongoTemplate.bulkOps(UNORDERED, ACL.class);
            updateOffset(offset);
        }
    }

    if (totalRemoved % BATCH_SIZE != 0) {
        executeAndLogBulkRemoval(bulkOperations, totalRemoved);
        updateOffset(offset);
    }

    markJobAsSuccessful();
} catch (Exception ex) {
    log.error(DEBUG_MESSAGE + "Exception occurred while processing ACLs ", ex);
}
```


<!-- Sent from Reviewable.io -->

2023-09-15 08:21 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLqOeWEljeyMUyMi8M:-NeMvTtw7fbfDIhwDOS7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L98)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

You can add Thread.sleep
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-15 08:21 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 135 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLsBF15iC-JO6kG9zl:-NeMv_qkA1iKbqDo4r0N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L135)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Simplified version. You can add Thread.sleep
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-15 08:21 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 187 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLntBA0k6F1Gy6aKff:-NeMvcAC33pcw1Ntnswy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L187)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Let's rename this class to RemoveRedundantACLJobState. This state will have 2 fields - offset and jobCompleted
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-15 08:21 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 190 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLoHwH5-fWseAqqypo:-NeMve5dEbrsr1c9tCoS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L190)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

state.isJobCompleted()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-15 08:22 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 228 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLop9BEExRR8Z3clYb:-NeMvgUa-hkMxe9wd20c:b24rf0j) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L228)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't we save the offset after removal?
</blockquote></details>

This is to save offset from where we are starting. After removing ACLs we are just updating the same record.


<!-- Sent from Reviewable.io -->

2023-09-15 08:23 UTC, ashishsanodia-harness commented
*[`access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java` line 233 at r5](https://reviewable.io/reviews/harness/harness-core/52668#-NeLpCzQ27DmvO98iTdu:-NeMvrTU8P7UTeETSvMB:bb0eula) ([raw file](https://github.com/harness/harness-core/blob/38f11cda6e1d1c465c45247dccb845dbfdf51680/access-control/service/src/main/java/io/harness/accesscontrol/acl/worker/RemoveRedundantACLJob.java#L233)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

override max query execution time. by default we have 30 sec limit. we applied it recently.
</blockquote></details>

Increased maxTime to 2 minutes


<!-- Sent from Reviewable.io -->

2023-09-15 08:26 UTC, ankit-harness reviewed
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-15 08:28 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668#-:-NeMx5RDE54QUdb21bnW:bnfp4nl)* status: 20 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-15 08:28 UTC, ankit-harness approved these changes

2023-09-15 11:03 UTC, ashishsanodia-harness commented
trigger ut0

2023-09-18 06:38 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: 20 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHBwIg0pD74ZxWp6on:-Neb-ck26JQjvpVX6lho:bct41oi) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L165)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

This is based on test data I am using. but yeah refactored again to avoid any confusion.
</blockquote></details>

The batch size is baked in Prod code, so we have to test for same value.
___
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 206 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHD3ed7JC9LHNBrulp:-Neb-jpU7y-TbmwoUPV2:bhryvnd) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L206)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

This is based on test data I am using. but yeah refactored again to avoid any confusion.
</blockquote></details>

The max ACLs allowed for single change is baked in Prod code, so we have to test for same value.


<!-- Sent from Reviewable.io -->

2023-09-18 06:51 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHBwIg0pD74ZxWp6on:-Neb2CjR7WN2oM69EKc9:bh3ubis) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L165)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

The batch size is baked in Prod code, so we have to test for same value.
</blockquote></details>

Before my changes these return values were mocked in tests, so I refactored the tests. Now it is using actual values configured in backend.


<!-- Sent from Reviewable.io -->

2023-09-18 06:51 UTC, ashishsanodia-harness commented
*[`access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java` line 206 at r4](https://reviewable.io/reviews/harness/harness-core/52668#-NeHD3ed7JC9LHNBrulp:-Neb2m2S0vqAOHrZxLpc:bh3ubis) ([raw file](https://github.com/harness/harness-core/blob/a6cdee9b20ade6e0f94787d0ed349ffc6466f3a6/access-control/libs/aggregator/src/test/java/io/harness/aggregator/ACLGeneratorServiceImplTest.java#L206)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

The max ACLs allowed for single change is baked in Prod code, so we have to test for same value.
</blockquote></details>

Before my changes these return values were mocked in tests, so I refactored the tests. Now it is using actual values configured in backend.


<!-- Sent from Reviewable.io -->

2023-09-18 09:44 UTC, Jimit09Gandhi approved these changes
> Reviewed 10 of 20 files at r1, 5 of 5 files at r2, 1 of 4 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52668)* status: Some of the checks are too old. 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-09-18 09:56 UTC, merged