feat: [PL-39558]: Added public access client
harness/harness-core pull request #52683
Opened 2023-09-11 05:21 UTC by meenakshi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-11 17:46 UTC, piyush-harness commented
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientModule.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/52683#-Ne4LTVf9IEfDC6dSwU4:-Ne4LTVf9IEfDC6dSwU5:b6mlhyb) ([raw file](https://github.com/harness/harness-core/blob/f207ec008dddf23da32d7e4913b2d015981ab698/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientModule.java#L21)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PL)
> public class PublicAccessClientModule extends AbstractModule {
> ```

Why not use the same AccessControlClient?


<!-- Sent from Reviewable.io -->

2023-09-11 17:47 UTC, piyush-harness commented
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/52683#-Ne4LjK-BAKN54p2lSRu:-Ne4LjK-BAKN54p2lSRv:bw2t4ra) ([raw file](https://github.com/harness/harness-core/blob/f207ec008dddf23da32d7e4913b2d015981ab698/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java#L19)):*
> ```Java
> import retrofit2.http.POST;
> @OwnedBy(HarnessTeam.PL)
> public interface PublicAccessClient {
> ```

Can we use the same AccessContorlClient?


<!-- Sent from Reviewable.io -->

2023-09-11 17:48 UTC, piyush-harness reviewed
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 12 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-12 07:17 UTC, meenakshi-harness reviewed
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 12 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/52683#-Ne4LjK-BAKN54p2lSRu:-Ne7EW1H-ImKpEuTw8fl:b4gpsx3) ([raw file](https://github.com/harness/harness-core/blob/f207ec008dddf23da32d7e4913b2d015981ab698/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java#L19)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we use the same AccessContorlClient?
</blockquote></details>

Me and @Jimit09Gandhi  thought of keeping it separate from AccessControlClient (both resource and client). Also didn't seem right to keep in AccessControlClient given the functionality is different, wdyt?


<!-- Sent from Reviewable.io -->

2023-09-12 07:29 UTC, archit-harness requested changes
> Reviewed 3 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HmRSAuWiQiABzrUc:-Ne7HmRSAuWiQiABzrUd:b-hedmky) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L51)):*
> ```Java
>   StoreType storeType;
> 
>   boolean isPublic;
> ```

Should we list list of warning messages like if public failed but entity creation passed, so we can send false and error messages ? check with product
cc: @naidu-harness 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 288 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HMOV4UyCBERL2Jfn:-Ne7HMOV4UyCBERL2Jfo:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L288)):*
> ```Java
>   }
> 
>   private void setPublicContextInResponse(
> ```

same as above
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 295 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HO-ZCndmPz37A6zU:-Ne7HO-ZCndmPz37A6zV:b-jhrnyn) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L295)):*
> ```Java
>       isPublic = publicAccessClient.isResourcePublic(publicAccessRequest, accountId).execute();
>     } catch (IOException e) {
>       throw new RuntimeException(e);
> ```

we shouldnt throw exception -> this is a new feature -> we should get confirmation from product -> that if failed -> we will treat as false as entity is already saved/updated
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 312 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HGIA9TSI13jAhxLi:-Ne7HGIA9TSI13jAhxLj:b-k7reqv) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L312)):*
> ```Java
>     publicAccessRequest.setResourceScope(scope);
>     return publicAccessRequest;
>   }
> ```

isnt this code repetitive for all entities? should we move into a common util? provided by your new module which we installed?



_Code quote:_
```Java
  private PublicAccessRequest getPublicAccessRequest(
      String accountId, String orgId, String projectId, String pipelineId) {
    PublicAccessRequest publicAccessRequest = new PublicAccessRequest();
    publicAccessRequest.setResourceType("PIPELINE");
    publicAccessRequest.setResourceIdentifier(pipelineId);
    Scope scope = new Scope();
    scope.setOrg(orgId);
    scope.setAccount(accountId);
    scope.setProject(projectId);

    publicAccessRequest.setResourceScope(scope);
    return publicAccessRequest;
  }
```


<!-- Sent from Reviewable.io -->

2023-09-12 07:59 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HmRSAuWiQiABzrUc:-Ne7LqrY7WjP0HZnCkSO:bqipc3g) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineResponseDTO.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should we list list of warning messages like if public failed but entity creation passed, so we can send false and error messages ? check with product
cc: @naidu-harness
</blockquote></details>

Sounds good to me. cc: @piyush-harness 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 295 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HO-ZCndmPz37A6zU:-Ne7NF0oA6RxmcJMlCUl:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L295)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we shouldnt throw exception -> this is a new feature -> we should get confirmation from product -> that if failed -> we will treat as false as entity is already saved/updated
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-12 12:53 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 14 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 288 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HMOV4UyCBERL2Jfn:-Ne8RtQUAasj2_3-52_o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L288)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 312 at r2](https://reviewable.io/reviews/harness/harness-core/52683#-Ne7HGIA9TSI13jAhxLi:-Ne8RvYpEanj51pt5OT5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6f09df6eb6f12d7f68bd8974be67f23f146b68a4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L312)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this code repetitive for all entities? should we move into a common util? provided by your new module which we installed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-12 14:33 UTC, meenakshi-harness commented
trigger uts

2023-09-12 15:53 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 15 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/52683#-Ne4LjK-BAKN54p2lSRu:-Ne8vRlLBguqitK0hZmZ:b-fuhshf) ([raw file](https://github.com/harness/harness-core/blob/f207ec008dddf23da32d7e4913b2d015981ab698/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java#L19)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Me and @Jimit09Gandhi  thought of keeping it separate from AccessControlClient (both resource and client). Also didn't seem right to keep in AccessControlClient given the functionality is different, wdyt?
</blockquote></details>

We should add access control in package name io.harness.publicaccess 
___
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientFactory.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne8vwaL66sbppYJe3tp:-Ne8vwaL66sbppYJe3tq:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientFactory.java#L8)):*
> ```Java
>  */
> 
> package io.harness.publicaccess;
> ```

same as above.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 173 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne958G-8RS0Exzh4Hqe:-Ne958G-8RS0Exzh4Hqf:b-jtmluh) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L173)):*
> ```Java
>     try {
>       Response<Boolean> isPublicResponse = publicAccessClient.enable(publicAccessRequest, accountId).execute();
>       return createPublicAccessResponse(Boolean.TRUE.equals(isPublicResponse.body()), isPublicResponse.message());
> ```

does PublicResponse.message() return empty in case of success?


<!-- Sent from Reviewable.io -->

2023-09-12 15:54 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 15 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne95M2m9LGLTWGRM-WP:-Ne95M2m9LGLTWGRM-WQ:b-jtdgy0) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L175)):*
> ```Java
>       return createPublicAccessResponse(Boolean.TRUE.equals(isPublicResponse.body()), isPublicResponse.message());
>     } catch (Exception e) {
>       log.error("There was an error while marking pipeline {} as public", pipelineIdentifier, e);
> ```

Lets standarized this message to be shown for any public resource type.


<!-- Sent from Reviewable.io -->

2023-09-12 15:59 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 15 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 304 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne96VWt35HD1tzt_AQh:-Ne96VWt35HD1tzt_AQi:b-hrrou) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L304)):*
> ```Java
>       return createPublicAccessResponse(Boolean.TRUE.equals(isPublic.body()), isPublic.errorBody().string());
>     } catch (Exception e) {
>       log.error("There was an error while marking pipeline {} as public.", pipelineId, e);
> ```

standarized error msg. same as above.


<!-- Sent from Reviewable.io -->

2023-09-12 21:38 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 15 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 173 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne958G-8RS0Exzh4Hqe:-NeAJxgF-987-86R5WZt:bp986zt) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L173)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

does PublicResponse.message() return empty in case of success?
</blockquote></details>

replaced with error body
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 175 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne95M2m9LGLTWGRM-WP:-NeAK-nH4Zcp0dCnoOZT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L175)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets standarized this message to be shown for any public resource type.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 304 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne96VWt35HD1tzt_AQh:-NeAK0aZ7MxS5oj3720e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L304)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

standarized error msg. same as above.
</blockquote></details>

Done.
___
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/52683#-Ne4LjK-BAKN54p2lSRu:-NeAJtYyEujHGGX4b1yA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f207ec008dddf23da32d7e4913b2d015981ab698/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java#L19)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We should add access control in package name io.harness.publicaccess
</blockquote></details>

Done.
___
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientFactory.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/52683#-Ne8vwaL66sbppYJe3tp:-NeAJuMQ3ch_ovWbOvN1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/63a552a9695e1b62b10aa08da76427cd7e45503f/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientFactory.java#L8)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.
___
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientModule.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/52683#-Ne4LTVf9IEfDC6dSwU4:-NeAK3kwATYk5pPK5Ie3:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/f207ec008dddf23da32d7e4913b2d015981ab698/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClientModule.java#L21)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why not use the same AccessControlClient?
</blockquote></details>

same as above


<!-- Sent from Reviewable.io -->

2023-09-12 21:38 UTC, meenakshi-harness commented
trigger uts

2023-09-13 05:40 UTC, meenakshi-harness commented
trigger uts

2023-09-13 07:10 UTC, archit-harness requested changes
> Reviewed 1 of 1 files at r4, 3 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 15 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 163 at r7](https://reviewable.io/reviews/harness/harness-core/52683#-NeCMjCj3sA-_nI4IVy5:-NeCMjCj3sA-_nI4IVy6:b-evgigs) ([raw file](https://github.com/harness/harness-core/blob/b29cac3588ac52263589c2a82bacd9bf47203844/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L163)):*
> ```Java
>       String accountId, String orgId, String projectId, String pipelineIdentifier, boolean isPublic) {
>     PublicAccessResponse existingPublicStatus =
>         getPublicContextResponse(accountId, orgId, projectId, pipelineIdentifier);
> ```

apart from this getPublicContext, why mark Public methods needs to be in respective service? cant it be in publicAccessmodule and generic?


<!-- Sent from Reviewable.io -->

2023-09-13 17:11 UTC, Jimit09Gandhi requested changes
> Reviewed 1 of 12 files at r1, 2 of 9 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 9 of 11 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 11 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 185 at r8](https://reviewable.io/reviews/harness/harness-core/52683#-NeEWToBCca4tV8Eun7F:-NeEWToBCca4tV8Eun7G:b-mv25xx) ([raw file](https://github.com/harness/harness-core/blob/844e6fbb68b1162ef3fc97ed3e187686308c8d68/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L185)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error("There was an error while marking resource type [{}] with resource identifier [{}] as public.",
> ```

How about adding constants in SDK? This can easily get spread across modules.  You can take it up in next PRs.


<!-- Sent from Reviewable.io -->

2023-09-14 04:29 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 11 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 163 at r7](https://reviewable.io/reviews/harness/harness-core/52683#-NeCMjCj3sA-_nI4IVy5:-NeGvlgx7OmRqeDtljMi:b-hvjc5a) ([raw file](https://github.com/harness/harness-core/blob/b29cac3588ac52263589c2a82bacd9bf47203844/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L163)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

apart from this getPublicContext, why mark Public methods needs to be in respective service? cant it be in publicAccessmodule and generic?
</blockquote></details>

We can move mark public to PublicAccessClient but not sure if it will reduce the logic of response handling done in this method on service side. This will require introducing  new endpoint something like updatePublicContext. Let me take this up in follow up PR as this might take some time. 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 185 at r8](https://reviewable.io/reviews/harness/harness-core/52683#-NeEWToBCca4tV8Eun7F:-NeGwf018-iTrXHblvE8:b-7mr1oe) ([raw file](https://github.com/harness/harness-core/blob/844e6fbb68b1162ef3fc97ed3e187686308c8d68/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L185)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

How about adding constants in SDK? This can easily get spread across modules.  You can take it up in next PRs.
</blockquote></details>

Yes will take up with above comment in follow up PRs


<!-- Sent from Reviewable.io -->

2023-09-14 04:34 UTC, meenakshi-harness commented
trigger uts

2023-09-14 13:20 UTC, Jimit09Gandhi approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 11 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-14 13:35 UTC, meenakshi-harness commented
trigger uts

2023-09-15 06:44 UTC, meenakshi-harness commented
trigger uts

2023-09-15 11:41 UTC, meenakshi-harness commented
trigger messagecheck

2023-09-15 12:14 UTC, meenakshi-harness commented
trigger ut4

2023-09-15 17:29 UTC, piyush-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 163 at r7](https://reviewable.io/reviews/harness/harness-core/52683#-NeCMjCj3sA-_nI4IVy5:-NeOsKxqE_hWsCEoPJKS:b-ppqfo5) ([raw file](https://github.com/harness/harness-core/blob/b29cac3588ac52263589c2a82bacd9bf47203844/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L163)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

We can move mark public to PublicAccessClient but not sure if it will reduce the logic of response handling done in this method on service side. This will require introducing  new endpoint something like updatePublicContext. Let me take this up in follow up PR as this might take some time.
</blockquote></details>

Agree with @archit-harness We should expose only simple interfaces something similar to below

accessControlClient.enablePublicAccess(resourceId,resourceType,scope) 


<!-- Sent from Reviewable.io -->

2023-09-15 17:31 UTC, piyush-harness commented
*[`clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/52683#-Ne4LjK-BAKN54p2lSRu:-NeOrheZ3Eb9bHY3cjmT:b-j7zvtv) ([raw file](https://github.com/harness/harness-core/blob/f207ec008dddf23da32d7e4913b2d015981ab698/clients/access-control/sdk/src/main/java/io/harness/publicaccess/PublicAccessClient.java#L19)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think Resource Implementation can be different but client for One Micro service Service should be same so that it can share same available resources threads, connectionPool etc.


<!-- Sent from Reviewable.io -->

2023-09-15 17:31 UTC, piyush-harness reviewed
> Reviewed 2 of 9 files at r3, 1 of 11 files at r6, 1 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-18 05:39 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 8 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 163 at r7](https://reviewable.io/reviews/harness/harness-core/52683#-NeCMjCj3sA-_nI4IVy5:-NeamyR580AEkc_2A9HV:bz9zgof) ([raw file](https://github.com/harness/harness-core/blob/b29cac3588ac52263589c2a82bacd9bf47203844/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L163)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Agree with @archit-harness We should expose only simple interfaces something similar to below

accessControlClient.enablePublicAccess(resourceId,resourceType,scope)
</blockquote></details>

Yes @piyush-harness we already have `accessControlClient.enablePublicAccess(resourceId,resourceType,scope)` in our client. Something that Archit is sugggesting to have upsert operation to have enable and disable flows both. We can add in follow up PRs


<!-- Sent from Reviewable.io -->

2023-09-18 20:03 UTC, piyush-harness approved these changes
> Reviewed 1 of 1 files at r4, 7 of 11 files at r6, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-19 18:02 UTC, archit-harness requested changes
> Reviewed 2 of 3 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 161 at r11](https://reviewable.io/reviews/harness/harness-core/52683#-NeiaZHO6__wEoUsLcZY:-NeiaZHO6__wEoUsLcZZ:b-72m93q) ([raw file](https://github.com/harness/harness-core/blob/c2d923d6a34542ec039fe8bf83c5f88912af3c59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L161)):*
> ```Java
>   }
> 
>   private PublicAccessResponse markPipelinePublic(
> ```

please add todo, that this generic method will be moved to public access module and will taken only entity id and type
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 177 at r11](https://reviewable.io/reviews/harness/harness-core/52683#-NeiaRlmBKNF_1yq9ksF:-NeiaRlmBKNF_1yq9ksG:bexglpv) ([raw file](https://github.com/harness/harness-core/blob/c2d923d6a34542ec039fe8bf83c5f88912af3c59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L177)):*
> ```Java
>       } else {
>         isPublicResponse =
>             publicAccessClient.disable(accountId, orgId, projectId, PIPELINE, pipelineIdentifier, accountId).execute();
> ```

why do we need to mark it disable, by default it would be disabled isn't?
i think we should do this only for update flow and not create


<!-- Sent from Reviewable.io -->

2023-09-20 10:18 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 161 at r11](https://reviewable.io/reviews/harness/harness-core/52683#-NeiaZHO6__wEoUsLcZY:-Nem0N0w5__tdyOmRNl3:b-5w08rk) ([raw file](https://github.com/harness/harness-core/blob/c2d923d6a34542ec039fe8bf83c5f88912af3c59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L161)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

please add todo, that this generic method will be moved to public access module and will taken only entity id and type
</blockquote></details>

Created ticket to address same https://harness.atlassian.net/browse/PL-41403 instead of todo
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 177 at r11](https://reviewable.io/reviews/harness/harness-core/52683#-NeiaRlmBKNF_1yq9ksF:-Nem54xu0Fd_MnqGUzi6:b7v1yla) ([raw file](https://github.com/harness/harness-core/blob/c2d923d6a34542ec039fe8bf83c5f88912af3c59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L177)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need to mark it disable, by default it would be disabled isn't?
i think we should do this only for update flow and not create
</blockquote></details>

Disable will never be called for create flow.


<!-- Sent from Reviewable.io -->

2023-09-20 10:28 UTC, archit-harness reviewed
> Reviewed 1 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-20 10:55 UTC, meenakshi-harness commented
trigger uts

2023-09-20 12:24 UTC, meenakshi-harness commented
trigger ut7

2023-09-20 13:01 UTC, meenakshi-harness commented
trigger ut2

2023-09-20 13:53 UTC, meenakshi-harness commented
trigger ut7

2023-09-20 14:05 UTC, meenakshi-harness commented
trigger ut2

2023-09-20 14:22 UTC, meenakshi-harness commented
trigger ut7

2023-09-20 15:58 UTC, meenakshi-harness commented
trigger ut2

2023-09-20 16:18 UTC, ashishsanodia-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683#-:-NenNdGh-plpnS4we3EN:bnfp4nl)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-09-20 16:19 UTC, ashishsanodia-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683#-:-NenNxsX0hxygJSv1uMH:bnfp4nl)* status: 2 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-09-20 16:30 UTC, ashishsanodia-harness approved these changes
> Reviewed 1 of 9 files at r3, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-09-20 16:30 UTC, piyush-harness approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52683)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-09-20 17:12 UTC, merged