feat: [CDS-77253]: Adding support to fetch helm chart from Ecr using OCI
harness/harness-core pull request #52697
Opened 2023-09-11 07:52 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-12 05:19 UTC, GoelPratyush99 commented
trigger uts

2023-09-12 10:29 UTC, GoelPratyush99 commented
trigger uts

2023-09-12 10:48 UTC, GoelPratyush99 commented
trigger uts

2023-09-12 11:35 UTC, abosii-harness requested changes

2023-09-12 11:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +        // TODO: see how to add ecr repo url;
What is missing here?

2023-09-12 11:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +    String repositoryUrl = ociHelmStoreDelegateConfig.getRepoUrl();
How we're getting repo url from from the ociHelmStoredelegateConfig?

2023-09-12 11:35 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/mixin/HelmChartCapabilityGenerator.java
> +            capabilities.add(HelmInstallationCapability.builder()
Don't we need HelmInstallationCapability in both cases?

2023-09-12 11:35 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDeployRequest.java
> +                  ociHelmStoreConfig.getConnectorConfigDTO(), maskingEvaluator));
nit: can use connectorConfigDTO directly

2023-09-12 11:35 UTC, abosii-harness commented on 400-rest/src/test/resources/manager-kryo-registrations.txt
> +55433:io.harness.delegate.beans.storeconfig.ociHelmResources.OciHelmChartEcrConfigResource
You will need a new task type if you're going to introduce new kryo entities

2023-09-12 11:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +        ConnectorConfigDTO connectorConfigDTO = ociHelmStoreConfig.getConnectorConfigDTO();
Should we ensure compatibility with older version of manager?

2023-09-12 11:35 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/ociHelmResources/OciHelmChartEcrConfigResource.java
> +  public String getEcrRepoUrl(AwsConnectorDTO awsConnectorDTO, String repoName, String region, String registryId) {
This is not a getter, some serializations frameworks may treat this as a field and during serialization may call this method

2023-09-12 11:35 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/ociHelmResources/OciHelmChartEcrConfigResource.java
> +    AwsClient awsClient = new AwsClientImpl();
How you're injecting AwsClientImpl dependencies?

2023-09-13 05:06 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +    String repositoryUrl = ociHelmStoreDelegateConfig.getRepoUrl();
I have added that logic in `io.harness.delegate.beans.storeconfig.OciHelmStoreDelegateConfig#getRepoUrl` to avoid duplication of code.

2023-09-13 05:09 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/ociHelmResources/OciHelmChartEcrConfigResource.java
> +    AwsClient awsClient = new AwsClientImpl();
I have created a constructor in AwsClientImpl class

2023-09-13 05:12 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +        ConnectorConfigDTO connectorConfigDTO = ociHelmStoreConfig.getConnectorConfigDTO();
you mean delegate?

2023-09-13 05:13 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/ociHelmResources/OciHelmChartEcrConfigResource.java
> +  public String getEcrRepoUrl(AwsConnectorDTO awsConnectorDTO, String repoName, String region, String registryId) {
changed to fetchEcrRepoUrl

2023-09-13 05:13 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDeployRequest.java
> +                  ociHelmStoreConfig.getConnectorConfigDTO(), maskingEvaluator));
done

2023-09-13 05:17 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/mixin/HelmChartCapabilityGenerator.java
> +            capabilities.add(HelmInstallationCapability.builder()
Done

2023-09-13 05:21 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +        // TODO: see how to add ecr repo url;
Done added repo Url for ECR case

2023-09-13 05:54 UTC, GoelPratyush99 commented
trigger uts

2023-09-13 06:13 UTC, GoelPratyush99 commented on 400-rest/src/test/resources/manager-kryo-registrations.txt
> +55433:io.harness.delegate.beans.storeconfig.ociHelmResources.OciHelmChartEcrConfigResource
BUT OciHelmStoreDelegateConfig does not have a task type. Why would I require for these entities? Should I remove to another package and add it as part of their kryo?

2023-09-13 06:17 UTC, GoelPratyush99 commented
trigger uts

2023-09-13 07:16 UTC, abhinavsingh1196 requested changes

2023-09-13 07:16 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +        .split(COLON_DELIMITER);
awsClient does throw exception in case of any problems, but let's still add an assertion here for this array to contain only 2 values post split (username and password)

2023-09-13 07:16 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/ociHelmResources/OciHelmChartEcrConfigResource.java
> +    AwsClient awsClient = new AwsClientImpl();
we shouldn't be instantiating AwsClientImpl singleton repeatedly, it is a singleton for a reason. This `fetchEcrRepoUrl` should probably be outside this entity and in some singleton helper where you can inject AwsClientImpl directly?

2023-09-13 07:16 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java
> +    throw new InvalidArgumentsException("Invalid OCI Helm Chart Store Config Type");
nit: error message should also mention that only GENERIC and ECR store types are supported

2023-09-15 07:19 UTC, GoelPratyush99 commented
trigger uts

2023-09-15 07:50 UTC, GoelPratyush99 commented
trigger uts

2023-09-15 08:08 UTC, GoelPratyush99 commented
trigger uts

2023-09-15 11:48 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java
> +    throw new InvalidArgumentsException("Invalid OCI Helm Chart Store Config Type");
We do not carry that info with us to the delegate so we do not have context to the types of configs that we support

2023-09-15 11:49 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/ociHelmResources/OciHelmChartEcrConfigResource.java
> +    AwsClient awsClient = new AwsClientImpl();
Refactored the piece of code and added anew delegate task to support this.

2023-09-15 11:49 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +    // RepositoryUrl: 479370281431.dkr.ecr.us-east-1.amazonaws.com/helm-test-chart
Done

2023-09-15 12:33 UTC, GoelPratyush99 commented
trigger uts

2023-09-18 12:26 UTC, GoelPratyush99 commented
trigger uts

2023-09-19 04:24 UTC, GoelPratyush99 commented
trigger uts

2023-09-19 06:05 UTC, GoelPratyush99 commented
trigger uts

2023-09-20 03:30 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +    String[] usernamePassword = getEcrAuthCredentials(ociHelmStoreDelegateConfig.getEncryptedDataDetails(),
No its only present in HelmTaskHelperBase file

2023-09-20 04:46 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmChartManifestTaskService.java
> +              .cacheRepoUrl(format("%s/%s", ociHelm.getRepoUrl(), ociHelm.getBasePath()));
Done

2023-09-20 04:47 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/helm/NativeHelmStepHelperTest.java
> +    verify(kryoSerializer, times(3)).asDeflatedBytes(taskParametersArgumentCaptor.capture());
Earlier in capability check if the repourl is null then we didn't add the capability. This condition was removed by me. I have added the condition again.

2023-09-20 04:51 UTC, GoelPratyush99 commented
trigger uts

2023-09-20 06:23 UTC, GoelPratyush99 commented
trigger ut2, ut7

2023-09-20 06:41 UTC, abosii-harness submitted a review, later dismissed

2023-09-20 07:33 UTC, markoharness submitted a review, later dismissed

2023-09-20 08:14 UTC, abhinavsingh1196 approved these changes

2023-09-21 06:33 UTC, TarunUba1 approved these changes

2023-09-21 06:34 UTC, TarunUba1 commented
please add test cases you have tested

2023-09-21 07:26 UTC, GoelPratyush99 commented
trigger uts

2023-09-21 07:27 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/delegate/K8sManifestDelegateMapper.java
> +    String region = null;
No its required as region is only being used in ECR case and not Generic had it been in both then initialization would been redundant.

2023-09-21 07:59 UTC, abosii-harness approved these changes

2023-09-21 08:10 UTC, abhinavsingh1196 approved these changes

2023-09-21 08:39 UTC, markoharness approved these changes

2023-09-21 08:41 UTC, TarunUba1 approved these changes

2023-09-21 09:57 UTC, acasian-harness approved these changes

2023-09-21 13:52 UTC, mdmilic submitted a review, later dismissed
> Reviewed 1 of 22 files at r1, 2 of 2 files at r2, 1 of 14 files at r3, 1 of 2 files at r4, 16 of 25 files at r5, 1 of 2 files at r6, 8 of 8 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52697)* status: 23 file(s) to review. 12. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-09-21 14:20 UTC, abosii-harness approved these changes

2023-09-21 14:40 UTC, abhinavsingh1196 approved these changes

2023-09-21 14:41 UTC, GoelPratyush99 commented
trigger review

2023-09-21 14:43 UTC, mdmilic approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52697)* status: 22 file(s) to review. 12. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-21 15:24 UTC, GoelPratyush99 commented
trigger uts_JDK11

2023-09-21 17:05 UTC, GoelPratyush99 commented
trigger ut2, ut3, ut5, ut6

2023-09-21 17:07 UTC, GoelPratyush99 commented
ut2

2023-09-22 03:08 UTC, GoelPratyush99 commented
trigger uts

2023-09-22 04:23 UTC, GoelPratyush99 commented
trigger ut7, ut8

2023-09-22 09:07 UTC, GoelPratyush99 commented
trigger ut7

2023-09-22 15:38 UTC, GoelPratyush99 commented
trigger uts

2023-09-22 18:30 UTC, GoelPratyush99 commented
trigger ut2, ut3

2023-09-22 20:46 UTC, merged