feat: [CDS-0]: draft changes
harness/harness-core pull request #52703
Opened 2023-09-11 10:31 UTC by prashantsharma04

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-11 10:31 UTC, prashantsharma04 commented
trigger uts

2023-09-14 11:06 UTC, prashantsharma04 commented
trigger uts

2023-09-14 12:20 UTC, prashantsharma04 commented
trigger uts

2023-09-14 16:15 UTC, archit-harness requested changes
> Reviewed 1 of 3 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-NeJKvW17xiqGT28VvL1:-NeJKvW17xiqGT28VvL2:b-h0onu0) ([raw file](https://github.com/harness/harness-core/blob/6e7975dfcccc877d95f3a28ef1344dcb67fb0750/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L156)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns all the Executions of pipelines for given filter")
>       })
>   @NGAccessControlCheck(resourceType = PIPELINE_RESOURCE_TYPE, permission = PipelineRbacPermissions.PIPELINE_VIEW)
> ```

i dont think we should remove this? even restricted user will not have access to executions
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-NeJT3N51FKMVEtLTIW5:-NeJT3N51FKMVEtLTIW6:bzermoo) ([raw file](https://github.com/harness/harness-core/blob/62c67ced5c55067bcaa49600939513faeaa60c82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L106)):*
> ```Java
>     // Filtering entities based on pipeline view permission
>     List<PipelineEntity> permittedEntity =
>         getPermittedPipelineEntities(accountIdentifier, orgIdentifier, projectIdentifier, pipelineEntities);
> ```

@prashantsharma04 as discussed earlier, here if pipelineIds got from pagination have less permitted entities, the page will be less compared to required one, we should get all pipelineIds, and check permitted on them if filter is not on them


<!-- Sent from Reviewable.io -->

2023-09-18 14:20 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: Some of the checks are too old. 6 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-Necdp095xy7naZ1ZGCr:-Necdp095xy7naZ1ZGCs:b-gjiwf8) ([raw file](https://github.com/harness/harness-core/blob/62c67ced5c55067bcaa49600939513faeaa60c82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L116)):*
> ```Java
>   @NotNull
>   private List<PipelineEntity> getPermittedPipelineEntities(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, List<PipelineEntity> pipelineEntities) {
> ```

@prashantsharma04  We should avoid filtering at Repository layer and try to do it at resource layer.
You can check same done for resource groups. 
https://github.com/harness/harness-core/pull/50170

Also if Principal already has access to all Pipelines in given view we can avoid making filtering.

cc @archit-harness 


<!-- Sent from Reviewable.io -->

2023-09-18 16:32 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: Some of the checks are too old. 6 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-Necdp095xy7naZ1ZGCr:-Ned7YbZ421o7ekK-I72:b-nyqn5j) ([raw file](https://github.com/harness/harness-core/blob/62c67ced5c55067bcaa49600939513faeaa60c82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L116)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

@prashantsharma04  We should avoid filtering at Repository layer and try to do it at resource layer.
You can check same done for resource groups. 
https://github.com/harness/harness-core/pull/50170

Also if Principal already has access to all Pipelines in given view we can avoid making filtering.

cc @archit-harness
</blockquote></details>

Yes @Jimit09Gandhi commented the same, thanks for sharing the pr


<!-- Sent from Reviewable.io -->

2023-09-21 06:10 UTC, prashantsharma04 commented
trigger uts

2023-09-21 06:21 UTC, prashantsharma04 commented
trigger uts

2023-09-21 06:38 UTC, prashantsharma04 commented
trigger uts

2023-09-21 06:47 UTC, prashantsharma04 commented
trigger uts

2023-09-21 06:59 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 408 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXG1z0_nA6zkGf6ln:-NeqXG2-ACRf7EzXj6g2:bdsw4cg) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L408)):*
> ```Java
>           pmsPipelineService.getPermittedPipelineEntities(accountId, orgId, projectId, pipelineEntities.getContent());
>       pipelineEntities = PageUtils.getPage(permittedPipelineEntities, page, size);
>     }
> ```

can we extract this out to a function so that it is clear that we are filtering via selective view permissions?



_Code quote:_
```Java
      pipelineEntities = pmsPipelineService.list(criteria,
          PageUtils.getPageRequest(0, 50000, sort, Sort.by(Sort.Direction.DESC, PipelineEntityKeys.lastUpdatedAt)),
          accountId, orgId, projectId, getDistinctFromBranches);
      List<PipelineEntity> permittedPipelineEntities =
          pmsPipelineService.getPermittedPipelineEntities(accountId, orgId, projectId, pipelineEntities.getContent());
      pipelineEntities = PageUtils.getPage(permittedPipelineEntities, page, size);
    }
```


<!-- Sent from Reviewable.io -->

2023-09-21 07:00 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 989 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXbEk7XCQwS8L3KQ0:-NeqXbEk7XCQwS8L3KQ1:bkctxyf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L989)):*
> ```Java
>         getAccessCheckResponseDTO(accountId, orgId, projectId, entityIdentifierList);
> 
>     log.info(accessCheckResponse.toString());
> ```

nit: do we need to log this information?


<!-- Sent from Reviewable.io -->

2023-09-21 07:01 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 978 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXj8p3CdWbiMYrd54:-NeqXj8p3CdWbiMYrd55:bx3up9n) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L978)):*
> ```Java
>     }
> 
>     Map<String, PipelineEntity> identifierToEntityMap =
> ```

why do we need this map? Can we convert to list of identifiers directly?


<!-- Sent from Reviewable.io -->

2023-09-21 07:02 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-NeJKvW17xiqGT28VvL1:-NeqY1RE03X011l-02Zg:b32v57) ([raw file](https://github.com/harness/harness-core/blob/6e7975dfcccc877d95f3a28ef1344dcb67fb0750/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L156)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont think we should remove this? even restricted user will not have access to executions
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-09-21 07:03 UTC, sahilhindwani-harness requested changes
> Reviewed 1 of 2 files at r3, 5 of 9 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 11 file(s) to review. 3 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-21 07:14 UTC, prashantsharma04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 11 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 978 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXj8p3CdWbiMYrd54:-Neq_Kn450_FFM_1T_pA:b-lt4we8) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L978)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why do we need this map? Can we convert to list of identifiers directly?
</blockquote></details>

We are returning PipelineEntity. AccessControl will have identifier and its access hence to return back Entity, I have created this map.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 989 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXbEk7XCQwS8L3KQ0:-Neq_VIlAlr2XYpqo2kI:b-3x6b5y) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L989)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: do we need to log this information?
</blockquote></details>

This will be removed.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-NeJKvW17xiqGT28VvL1:-Neq_Z1P-uzPALaKs4T1:b3xpwi6) ([raw file](https://github.com/harness/harness-core/blob/6e7975dfcccc877d95f3a28ef1344dcb67fb0750/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L156)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

We are removing this and making access call internally.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-NeJT3N51FKMVEtLTIW5:-Neq_d62DoCPLs1mRn9S:b4l5nkt) ([raw file](https://github.com/harness/harness-core/blob/62c67ced5c55067bcaa49600939513faeaa60c82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L106)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@prashantsharma04 as discussed earlier, here if pipelineIds got from pagination have less permitted entities, the page will be less compared to required one, we should get all pipelineIds, and check permitted on them if filter is not on them
</blockquote></details>

This has been removed. Have made the changes in criteria itself
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-Necdp095xy7naZ1ZGCr:-Neq_k66BwfC5bPnYRzv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/62c67ced5c55067bcaa49600939513faeaa60c82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L116)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Yes @Jimit09Gandhi commented the same, thanks for sharing the pr
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-21 07:30 UTC, archit-harness requested changes
> Reviewed 1 of 2 files at r3, 3 of 9 files at r5, 2 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 4 file(s) to review. 3 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 403 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqaaU1CIbyvoUjiREo:-NeqaaU1CIbyvoUjiREp:bna8oht) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L403)):*
> ```Java
>     else {
>       pipelineEntities = pmsPipelineService.list(criteria,
>           PageUtils.getPageRequest(0, 50000, sort, Sort.by(Sort.Direction.DESC, PipelineEntityKeys.lastUpdatedAt)),
> ```

make it 10k, as we have kept mongo limit to query 10k records at a time



_Code quote:_
```Java
50000
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 406 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqbY5d2FPOgjp9VggD:-NeqbY5d2FPOgjp9VggE:bc1n5wo) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L406)):*
> ```Java
>           accountId, orgId, projectId, getDistinctFromBranches);
>       List<PipelineEntity> permittedPipelineEntities =
>           pmsPipelineService.getPermittedPipelineEntities(accountId, orgId, projectId, pipelineEntities.getContent());
> ```

fetch only identifier in first go, then get permitted ids and then do in query back on mongo, this way we are only getting rest metadata of respective page only, thus memory is not bloated else in current approach we are getting all entries into memory
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 973 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-Neqc20Z5iXXAJzMVW-e:-Neqc20Z5iXXAJzMVW-f:b-wh4yyh) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L973)):*
> ```Java
>   @Override
>   public List<PipelineEntity> getPermittedPipelineEntities(
>       String accountId, String orgId, String projectId, List<PipelineEntity> pipelineEntities) {
> ```

this will be list of ids only
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 978 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXj8p3CdWbiMYrd54:-Neqbsal-wnsNS6Z9x0m:bgifkcd) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L978)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

We are returning PipelineEntity. AccessControl will have identifier and its access hence to return back Entity, I have created this map.
</blockquote></details>

discussed offline, so only identifier will be sent
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 162 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcK8p03R_xECja_G5:-NeqcK8p03R_xECja_G6:bxppb14) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L162)):*
> ```Java
>         criteria.and(PlanExecutionSummaryKeys.pipelineIdentifier).is(pipelineIdentifier);
>       } else {
>         throw new AccessDeniedException(
> ```

abstract into a separate method
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 169 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcZpy29jTQHObdZKx:-NeqcZpy29jTQHObdZKy:bd1s8u0) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L169)):*
> ```Java
>       // If the user does not have permission for all pipelines then add the criteria for only view permission pipeline
>       if (!accessControlClient.hasAccess(ResourceScope.of(accountId, orgId, projectId), Resource.of("PIPELINE", null),
>               PipelineRbacPermissions.PIPELINE_VIEW)) {
> ```

use common method which you will be using in pipeline crud
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 170 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcVQE2p7zO7uN5CFO:-NeqcVQE2p7zO7uN5CFP:b-hlutlm) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L170)):*
> ```Java
>       if (!accessControlClient.hasAccess(ResourceScope.of(accountId, orgId, projectId), Resource.of("PIPELINE", null),
>               PipelineRbacPermissions.PIPELINE_VIEW)) {
>         setViewPermissionIdentifier(accountId, orgId, projectId, criteria);
> ```

setPermittedPipelineIdentifier



_Code quote:_
```Java
setViewPermissionIdentifie
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 275 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcckO2OA90MZdeeYw:-NeqcckO2OA90MZdeeYx:b1y5avd) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L275)):*
> ```Java
>   private void setViewPermissionIdentifier(String accountId, String orgId, String projectId, Criteria criteria) {
>     List<PipelineEntity> pipelineEntities = pmsPipelineService.listWithProjection(
>         PMSPipelineFilterHelper.getCriteriaForAllPipelinesInProject(accountId, orgId, projectId),
> ```

only ids
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 283 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcfJrEVWBmI0Yy7GJ:-NeqcfJrEVWBmI0Yy7GK:bofgj6o) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L283)):*
> ```Java
> 
>     List<String> permittedPipelineIdentifier =
>         pmsPipelineService.getPermittedPipelineIdentifier(accountId, orgId, projectId, identifiers);
> ```

resuse same as pipeline crud, complete method
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 370 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqdI056045Swdy9E8O:-NeqdI056045Swdy9E8P:btcquzv) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L370)):*
> ```Java
>       }
>     } else {
>       setViewPermissionIdentifier(accountId, orgId, projectId, criteria);
> ```

use same as above



_Code quote:_
```Java
      List<String> permittedPipelineIdentifier =
          pmsPipelineService.getPermittedPipelineIdentifier(accountId, orgId, projectId, pipelineIdentifier);
      if (permittedPipelineIdentifier.size() != 0) {
        pipelineCriteria.and(PlanExecutionSummaryKeys.pipelineIdenti [...]

2023-09-21 12:47 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 6 file(s) to review. 3 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 403 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqaaU1CIbyvoUjiREo:-Nerkfne6M8Qxixli5B7:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L403)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

make it 10k, as we have kept mongo limit to query 10k records at a time
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 410 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-NerklGnASmPyTr8MQ8Y:-NerklGnASmPyTr8MQ8Z:b-9iul1k) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L410)):*
> ```Java
>   }
> 
>   private void validateAndSetPermittedPipelines(String accountId, String orgId, String projectId, List<String> sort,
> ```

we are not validating anything isnt?



_Code quote:_
```Java
validate
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 413 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerkrqo74oSr2Y27R-s:-Nerkrqo74oSr2Y27R-t:bu2k79g) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L413)):*
> ```Java
>       Boolean getDistinctFromBranches, Criteria criteria) {
>     if (!pmsPipelineService.validateViewPermission(accountId, orgId, projectId)) {
>       Page<String> allPipelineIdentifiers = pmsPipelineService.listAllIdentifiers(criteria,
> ```

page request etc everything could be absorbed by your service, and then use constant for 10k in your service
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 420 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerl5ghCzyuqSb232Ev:-Nerl5ghCzyuqSb232Ew:b-5dwuf5) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L420)):*
> ```Java
>           accountId, orgId, projectId, allPipelineIdentifiers.toList());
> 
>       criteria.and(PipelineEntityKeys.identifier).in(permittedPipelineIdentifiers);
> ```

isnt this 3 lines block common for execution as well?



_Code quote:_
```Java
      Page<String> allPipelineIdentifiers = pmsPipelineService.listAllIdentifiers(criteria,
          PageUtils.getPageRequest(0, 10000, sort, Sort.by(Sort.Direction.DESC, PipelineEntityKeys.lastUpdatedAt)),
          accountId, orgId, projectId, getDistinctFromBranches);

      List<String> permittedPipelineIdentifiers = pmsPipelineService.getPermittedPipelineIdentifier(
          accountId, orgId, projectId, allPipelineIdentifiers.toList());

      criteria.and(PipelineEntityKeys.identifier).in(permittedPipelineIdentifiers);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 765 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-NerlChUDdeQfWgssrmO:-NerlChUDdeQfWgssrmP:bvw5lxs) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L765)):*
> ```Java
>   @Override
>   public List<String> getAllPipelineIdentifiers(String accountId, String orgIdentifier, String projectIdentifier) {
>     return pmsPipelineRepository.findAllPipelineIdentifiers(accountId, orgIdentifier, projectIdentifier);
> ```

use secondary mongo template
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 275 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcckO2OA90MZdeeYw:-NerlhNO6vjep8PmAPl0:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L275)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

only ids
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 268 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerljam7-ve86s4Q2Fx:-Nerljam7-ve86s4Q2Fy:bwzlbcu) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L268)):*
> ```Java
>   }
> 
>   private static void addPipelineIdentifierListInCriteria(Criteria criteria, List<String> permittedPipelineIdentifier) {
> ```

if static why we need to add to impl and not to a helper?
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 111 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerlr1oEBpCA2ShDug_:-Nerlr1oEBpCA2ShDuga:b-emux7f) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L111)):*
> ```Java
>     Query query = new Query(criteria);
> 
>     query.fields().include(PipelineEntityKeys.identifier);
> ```

add exclude uuid
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 116 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerltx7AaX1ViCDfWZa:-Nerltx7AaX1ViCDfWZb:b3c5yyt) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L116)):*
> ```Java
> 
>     return pipelineEntities.stream()
>         .map(PipelineEntity::getIdentifier) // Assuming "getIdentifier" is the method to retrieve the identifier
> ```

why this comment?



_Code quote:_
```Java
// Assuming "getIdentifier" is the method to retrieve the identifier
```
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 501 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-NerlxvmBeIhfiRRHFAz:-NerlxvmBeIhfiRRHFB-:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L501)):*
> ```Java
> 
>   @Override
>   public Page<String> findAllPipelineIdentifiers(Criteria criteria, Pageable pageable, String accountIdentifier,
> ```

why is this needed?


<!-- Sent from Reviewable.io -->

2023-09-21 13:36 UTC, prashantsharma04 commented
trigger uts

2023-09-22 08:29 UTC, prashantsharma04 commented
trigger uts

2023-09-25 05:38 UTC, prashantsharma04 commented
trigger uts

2023-09-25 09:23 UTC, prashantsharma04 commented
trigger uts

2023-09-25 10:06 UTC, prashantsharma04 commented
trigger ut1

2023-09-25 10:12 UTC, prashantsharma04 commented
trigger ut0

2023-09-25 10:12 UTC, prashantsharma04 commented
trigger ut4, ut8

2023-09-25 10:54 UTC, archit-harness requested changes
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 2 files at r12, 5 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 11 file(s) to review. 3 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 406 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqbY5d2FPOgjp9VggD:-NfAx5c22pI9FZg1oT2D:b8ftghq) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L406)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

fetch only identifier in first go, then get permitted ids and then do in query back on mongo, this way we are only getting rest metadata of respective page only, thus memory is not bloated else in current approach we are getting all entries into memory
</blockquote></details>

Discussed offline, still needs improvement in this method
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 410 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-NerklGnASmPyTr8MQ8Y:-NfAx8D1B3_Q_4F6qLcs:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L410)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we are not validating anything isnt?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 413 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerkrqo74oSr2Y27R-s:-NfAx8eOCpNvlmYT5U1E:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L413)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

page request etc everything could be absorbed by your service, and then use constant for 10k in your service
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 420 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerl5ghCzyuqSb232Ev:-NfAx9VhC9bSgxql3pgz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L420)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this 3 lines block common for execution as well?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 160 at r13](https://reviewable.io/reviews/harness/harness-core/52703#-NfAxCRh0Uq5VUGqn-od:-NfAxCRh0Uq5VUGqn-oe:b-vh6f2h) ([raw file](https://github.com/harness/harness-core/blob/69dac00c3d4efeaaaa74d08166fcd70d3c455788/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L160)):*
> ```Java
>       String accountId, String orgId, String projectId, List<String> pipelineIdentifierList);
> 
>   List<String> listAllIdentifiers(Criteria criteria, Pageable pageRequest, String accountId, String orgId,
> ```

this method can be improved
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 701 at r13](https://reviewable.io/reviews/harness/harness-core/52703#-NfAxUhKElOO1TqF_fex:-NfAxUhKElOO1TqF_fey:b-atvpv3) ([raw file](https://github.com/harness/harness-core/blob/69dac00c3d4efeaaaa74d08166fcd70d3c455788/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L701)):*
> ```Java
>     if (!pmsPipelineService.validateViewPermission(accountId, orgId, projectId)) {
>       List<String> allPipelineIdentifiers = pmsPipelineService.listAllIdentifiers(criteria,
>           PageUtils.getPageRequest(0, 10000, sort, Sort.by(Sort.Direction.DESC, PipelineEntityKeys.lastUpdatedAt)),
> ```

it should be absorbed by the service
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 973 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-Neqc20Z5iXXAJzMVW-e:-NfAx_5XB9cLncEmRb5Q:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L973)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this will be list of ids only
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 162 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcK8p03R_xECja_G5:-NfAy45f5P4d6mB06o43:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L162)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

abstract into a separate method
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 169 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcZpy29jTQHObdZKx:-NfAy7SC36pk_LWYXrhl:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L169)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use common method which you will be using in pipeline crud
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 170 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcVQE2p7zO7uN5CFO:-NfAy3_XBiUOupYnQlU9:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L170)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

setPermittedPipelineIdentifier
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 283 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcfJrEVWBmI0Yy7GJ:-NfAy8-29kXOufCr9aIW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L283)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

resuse same as pipeline crud, complete method
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 370 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqdI056045Swdy9E8O:-NfAyCD83h3TaPs5T8DR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L370)):*
<details>< [...]

2023-09-26 06:35 UTC, prashantsharma04 commented
trigger uts

2023-09-26 06:59 UTC, prashantsharma04 commented
trigger uts

2023-09-26 08:23 UTC, archit-harness requested changes
> Reviewed 5 of 6 files at r14, 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 11 file(s) to review. 3 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 406 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqbY5d2FPOgjp9VggD:-NfFNntP-9uI8VtKC3jy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L406)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Discussed offline, still needs improvement in this method
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEntityReadHelper.java` line 42 at r15](https://reviewable.io/reviews/harness/harness-core/52703#-NfFNqWN6xwPOENOY-zC:-NfFNqWN6xwPOENOY-zD:b4tdxuq) ([raw file](https://github.com/harness/harness-core/blob/56e88e0e199e5b118e48e9e82a8a6bf440680d2e/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEntityReadHelper.java#L42)):*
> ```Java
>   public List<String> findAllIdentifiers(Criteria criteria) {
>     List<PipelineEntity> pipelineEntities =
>         secondaryMongoTemplate.find(new Query(criteria).limit(10000), PipelineEntity.class);
> ```

use a constant rather than hard coded, example - NodeExecutionReadHelper.MAX_BATCH_SIZE
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java` line 160 at r13](https://reviewable.io/reviews/harness/harness-core/52703#-NfAxCRh0Uq5VUGqn-od:-NfF_JHC41PL8dtw4WZa:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/69dac00c3d4efeaaaa74d08166fcd70d3c455788/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java#L160)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this method can be improved
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 701 at r13](https://reviewable.io/reviews/harness/harness-core/52703#-NfAxUhKElOO1TqF_fex:-NfF_L1e48sChkVB3qv1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/69dac00c3d4efeaaaa74d08166fcd70d3c455788/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L701)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be absorbed by the service
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 978 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXj8p3CdWbiMYrd54:-NfF_Pr708rrRSMvzWw_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L978)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline, so only identifier will be sent
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 765 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-NerlChUDdeQfWgssrmO:-NfF_OQ59n5qpqJZmvyO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L765)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use secondary mongo template
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 268 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerljam7-ve86s4Q2Fx:-NfF_Th_7pcoc-hE8i1_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L268)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

one
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 111 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerlr1oEBpCA2ShDug_:-NfF_WIL-lMKAmqf06XG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L111)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add exclude uuid
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 116 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerltx7AaX1ViCDfWZa:-NfF_X5oCsvO1CiG2XEi:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L116)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this comment?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-26 08:37 UTC, prashantsharma04 commented
trigger uts

2023-09-26 08:40 UTC, prashantsharma04 commented
trigger uts

2023-09-27 05:18 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 11 file(s) to review. 2 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEntityReadHelper.java` line 42 at r15](https://reviewable.io/reviews/harness/harness-core/52703#-NfFNqWN6xwPOENOY-zC:-NfK3nH10PpImZUDT-mB:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/56e88e0e199e5b118e48e9e82a8a6bf440680d2e/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEntityReadHelper.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use a constant rather than hard coded, example - NodeExecutionReadHelper.MAX_BATCH_SIZE
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-28 05:42 UTC, prashantsharma04 commented
trigger uts

2023-09-28 06:11 UTC, archit-harness approved these changes
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 12 file(s) to review. 2 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-28 06:23 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 2 files at r3, 1 of 9 files at r5, 1 of 5 files at r6, 1 of 7 files at r13, 2 of 6 files at r14, 5 of 5 files at r15, 1 of 1 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 2 change requests. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-28 06:27 UTC, prashantsharma04 commented
trigger review

2023-09-28 06:39 UTC, prashantsharma04 commented
trigger messagecheck

2023-09-28 06:44 UTC, prashantsharma04 commented
trigger messagecheck

2023-09-28 07:02 UTC, Jimit09Gandhi requested changes
> Reviewed 1 of 2 files at r3, 1 of 9 files at r5, 1 of 5 files at r6, 1 of 7 files at r13, 2 of 6 files at r14, 5 of 5 files at r15, 1 of 1 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 2 change requests. 3. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 116 at r3](https://reviewable.io/reviews/harness/harness-core/52703#-Necdp095xy7naZ1ZGCr:-NfPa7FBCOnmAedYRTwm:bi4ul7x) ([raw file](https://github.com/harness/harness-core/blob/62c67ced5c55067bcaa49600939513faeaa60c82/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L116)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@Jimit09Gandhi suggestion for PL team to fetch only identifier in first go, then get permitted ids and then do in query back on mongo, this way we are only getting rest metadata of respective page only, thus memory is not bloated else in current approach we are getting all entries into memory
</blockquote></details>

Agreed @archit-harness.


<!-- Sent from Reviewable.io -->

2023-09-28 07:03 UTC, Jimit09Gandhi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703#-:-NfPaT729Dot52bHqYh-:bnfp4nl)* status: 1 change requests. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-28 07:20 UTC, prashantsharma04 commented
trigger review

2023-09-28 09:29 UTC, prashantsharma04 commented
trigger review

2023-09-28 11:19 UTC, prashantsharma04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 1 change requests. 3. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 406 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqbY5d2FPOgjp9VggD:-Nevi1h5AfWeR4rXM0sx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L406)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

fetch only identifier in first go, then get permitted ids and then do in query back on mongo, this way we are only getting rest metadata of respective page only, thus memory is not bloated else in current approach we are getting all entries into memory
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 408 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXG1z0_nA6zkGf6ln:-Nevi-at2tkh8bzGKWl-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L408)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

can we extract this out to a function so that it is clear that we are filtering via selective view permissions?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 410 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-NerklGnASmPyTr8MQ8Y:-NfAdUzWB6lSlQOJ90wR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L410)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we are not validating anything isnt?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 413 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerkrqo74oSr2Y27R-s:-NewJg4C1wUduVl5fD__:b-qlogn) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L413)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

page request etc everything could be absorbed by your service, and then use constant for 10k in your service
</blockquote></details>

We are returning now list instead of page
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 420 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-Nerl5ghCzyuqSb232Ev:-NewJjeB-spiI3jWWebl:b-wypf7) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L420)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this 3 lines block common for execution as well?
</blockquote></details>

Moved this method to PMSPipelineServiceHelper.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEntityReadHelper.java` line 42 at r15](https://reviewable.io/reviews/harness/harness-core/52703#-NfFNqWN6xwPOENOY-zC:-NfFor-K2rxEw_X6_gd1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/56e88e0e199e5b118e48e9e82a8a6bf440680d2e/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineEntityReadHelper.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use a constant rather than hard coded, example - NodeExecutionReadHelper.MAX_BATCH_SIZE
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 973 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-Neqc20Z5iXXAJzMVW-e:-NewK-FxDLDjzeIJlhju:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L973)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this will be list of ids only
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 978 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqXj8p3CdWbiMYrd54:-NewJzR31BRwHn_b1akm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L978)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline, so only identifier will be sent
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 765 at r8](https://reviewable.io/reviews/harness/harness-core/52703#-NerlChUDdeQfWgssrmO:-NfAdWVhDrbEPmlakIPt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1ea1b744ae99d9a64ffe23627498b1634d095f82/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L765)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use secondary mongo template
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 162 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcK8p03R_xECja_G5:-NfAdXjA2q_j6wiLuuAu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L162)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

abstract into a separate method
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 169 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcZpy29jTQHObdZKx:-NewK92V8veqnwComtlI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L169)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use common method which you will be using in pipeline crud
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 170 at r7](https://reviewable.io/reviews/harness/harness-core/52703#-NeqcVQE2p7zO7uN5CFO:-NfAdYoBCtj4QiBNeLRd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bde0a18ea90784c34158018584468f037f9ed800/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L170)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

setPermittedPipelineIdentifier
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 283 at r7](https://reviewable.io/ [...]

2023-09-28 11:20 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 7 files at r13, 2 of 6 files at r14, 5 of 5 files at r15, 1 of 1 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52703)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-28 11:32 UTC, merged