fix: [CDS-78819]: Adding Env variable AWS_STS_REGIONAL_ENDPOINTS=regi…
harness/harness-core pull request #52775
Opened 2023-09-12 13:20 UTC by namantalaycha10

…onal for EKS kube config behind FF CDS_EKS_ADD_REGIONAL_PARAM

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-12 13:21 UTC, namantalaycha10 commented
trigger uts

2023-09-12 14:31 UTC, yogesh-chauhan requested changes

2023-09-12 14:31 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/eks/AwsEKSV2DelegateTaskHelper.java
> +      }
we should add this always if the FF is true.
That means, it should be outside this `if` block

2023-09-12 14:32 UTC, yogesh-chauhan requested changes

2023-09-12 14:32 UTC, yogesh-chauhan commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +      "This flag adds the AWS_STS_REGIONAL_ENDPOINTS=regional environment variable while creating the kubenetes config",
Lets mention that this happens for EKS infrastructure

2023-09-12 14:35 UTC, lovish1999 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +      "This flag adds the AWS_STS_REGIONAL_ENDPOINTS=regional environment variable while creating the kubenetes config",
:nit: kubernetes ?

2023-09-13 06:11 UTC, namantalaycha10 commented
trigger uts

2023-09-13 06:11 UTC, namantalaycha10 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +      "This flag adds the AWS_STS_REGIONAL_ENDPOINTS=regional environment variable while creating the kubenetes config",
done

2023-09-13 06:21 UTC, namantalaycha10 commented
trigger uts

2023-09-13 06:35 UTC, yogesh-chauhan approved these changes
> Reviewed 8 of 13 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52775)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-13 06:57 UTC, namantalaycha10 commented
trigger messagecheck

2023-09-13 07:08 UTC, namantalaycha10 commented
trigger messagecheck

2023-09-13 07:28 UTC, lovish1999 approved these changes

2023-09-13 07:29 UTC, namantalaycha10 commented
trigger review

2023-09-13 07:35 UTC, merged