[fix]: [CDS-79062]: Index creation asynchronously
harness/harness-core pull request #52799
Opened 2023-09-12 17:03 UTC by archit-harness

## Describe your changes

Changes - Index creation asynchronously

Impact - Index creation will happen asynchronously without impacting service startup time and restarts

Testing -

a) Tested creating new index in the collection

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-12 17:04 UTC, archit-harness commented
trigger uts

2023-09-13 05:53 UTC, hextechpal requested changes

2023-09-13 05:53 UTC, hextechpal commented on 960-persistence/src/main/java/io/harness/mongo/index/IndexManagerSession.java
> +            log.warn("Index creation failed for {} {}", indexCreator.getOptions().toString(),
I think this is misleading,timeout exception just indicates that the future did not complete in the specified time which is expected for larger collections

I think we should change this to 
`
catch (TimeoutException e) {
            log.warn("")
}catch(InterruptedException | ExecutionException e){
            //This indicates that the creation truly failed
            log.error("")
}
`

2023-09-13 05:53 UTC, hextechpal commented on 960-persistence/src/main/java/io/harness/mongo/index/IndexManagerSession.java
> +        future.get(4, TimeUnit.HOURS);
This is a blocking operation for 4 hours, is this correct?

2023-09-13 05:53 UTC, abhinav-harness commented on 960-persistence/src/main/java/io/harness/mongo/index/IndexManagerSession.java
> +  private ExecutorService createIndexExecutorService = ThreadPool.create(
async index creation can cause newer queries to be slowed down

2023-09-13 05:58 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52799)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/index/IndexManagerSession.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/52799#gh-1324004112:-NeC5wnO-ueol_7opvAN:b-1aq217) ([raw file](https://github.com/harness/harness-core/blob/a784652ff37f0c83ccf6e339c80a19fdda39eb54/960-persistence/src/main/java/io/harness/mongo/index/IndexManagerSession.java#L108)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

async index creation can cause newer queries to be slowed down
</blockquote></details>

Yes, but if indexes takes a lot of time, we expect them to be created manually rather than through AUTO mode, it anyway happen if index creation doesn't get completed within few mins today as service restart happens
___
*[`960-persistence/src/main/java/io/harness/mongo/index/IndexManagerSession.java` line 514 at r2](https://reviewable.io/reviews/harness/harness-core/52799#gh-1324003581:-NeC5uCh6FfBqzKMSwEA:bvv3h5e) ([raw file](https://github.com/harness/harness-core/blob/a784652ff37f0c83ccf6e339c80a19fdda39eb54/960-persistence/src/main/java/io/harness/mongo/index/IndexManagerSession.java#L514)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

This is a blocking operation for 4 hours, is this correct?
</blockquote></details>

yes, for large collection kept higher value


<!-- Sent from Reviewable.io -->

2023-09-13 06:43 UTC, closed without merging