fix: [CDS-79020]: Check if clean up is successful for terragrunt
harness/harness-core pull request #52826
Opened 2023-09-13 06:36 UTC by sarthakkasat

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-22 09:10 UTC, yogesh-chauhan requested changes

2023-09-22 09:10 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java
> +      logCallback.saveExecutionLog("Failed to clean up files", ERROR, CommandExecutionStatus.FAILURE);
we should not set CommandExecutionStatus as FAILURE
Also, lets set the error log to WARN instead of Failure
We should also log.warn("failed to delete files", e)

2023-09-22 11:53 UTC, yogesh-chauhan requested changes

2023-09-22 11:53 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java
> +      log.warn("failed to delete files", e);
Lets also log the baseDir

2023-09-22 12:02 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52826)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 12:04 UTC, yogesh-chauhan approved these changes
Lets also fix in other usages of this method. in Next PR

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52826#-:-Newlj_XDAxhIUVoyJEl:b-sj1zuk)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 12:06 UTC, sarthakkasat commented
trigger uts

2023-09-22 12:19 UTC, sourabh-awashti approved these changes

2023-09-22 12:36 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52826)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-09-22 12:59 UTC, sarthakkasat commented
trigger uts

2023-09-22 13:53 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java
> +      logCallback.saveExecutionLog("Failed to clean up files", ERROR, CommandExecutionStatus.FAILURE);
Done

2023-09-23 15:50 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52826)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-23 15:50 UTC, merged