[feat]: [CDS-78366]: Addition of infra step to custom stage
harness/harness-core pull request #52840
Opened 2023-09-13 09:47 UTC by lovish1999

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-13 11:13 UTC, lovish1999 commented
trigger uts

2023-09-13 11:27 UTC, lovish1999 commented
trigger uts

2023-09-13 13:36 UTC, ivan-83 requested changes
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/52840#-NeDejTD35zypICFZK9C:-NeDejTE78Yir7u0cCsL:b4jme8p) ([raw file](https://github.com/harness/harness-core/blob/d584b46e7c3241b33fc041b6249c448a52a2d931/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L139)):*
> ```Java
> 
>   public PlanNode getInfraTaskExecutableStepV2PlanNode(EnvironmentYamlV2 environmentYamlV2,
>       ServiceDefinitionType deploymentType, ParameterField<Boolean> skipInstances) {
> ```

Remove ServiceDefinitionType deploymentType, ParameterField<Boolean> skipInstances  as params from this method. We don't need deploymentType and skipInstances for the custom stage.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 184 at r1](https://reviewable.io/reviews/harness/harness-core/52840#-NeDfTiOAp4BujMbTWq1:-NeDfTiOAp4BujMbTWq2:b-jua2mf) ([raw file](https://github.com/harness/harness-core/blob/d584b46e7c3241b33fc041b6249c448a52a2d931/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L184)):*
> ```Java
>         kryoSerializer.asBytes(OnSuccessAdviserParameters.builder().nextNodeId(envNextNodeUuid).build()));
>     final PlanNode envNode =
>         EnvironmentPlanCreatorHelper.getPlanNodeForCustomStage(envNodeUuid, stepParameters, advisorParameters);
> ```

Minor rename getPlanNodeForCustomStage >> getEnvPlanNodeForCustomStage
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 183 at r2](https://reviewable.io/reviews/harness/harness-core/52840#-NeDj61BB1h0M9CtLte3:-NeDj61BB1h0M9CtLte4:b-nnibk4) ([raw file](https://github.com/harness/harness-core/blob/5eaea64e69479c47d1d28087966b7ba24be1c4a3/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L183)):*
> ```Java
>       serviceOutcome = (ServiceStepOutcome) optionalServiceOutcome.getOutcome();
>     } else {
>       serviceOutcome = ServiceStepOutcome.builder().type(null).identifier(null).build();
> ```

We have to solve this better by making ServiceStepOutcome null in OutcomeSet and handling calling code in AbstractInfrastructureTaskExecutableStep & InfrastructureTaskExecutableStepV2.


<!-- Sent from Reviewable.io -->

2023-09-14 11:02 UTC, ivan-83 requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 443 at r3](https://reviewable.io/reviews/harness/harness-core/52840#-NeIKfnfAVOvPgkvWAcx:-NeIKfng7wM2XYnmr8Bh:b-qftovm) ([raw file](https://github.com/harness/harness-core/blob/f7a8f970022bcda5b21edf0c4db2b9b63785f925/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L443)):*
> ```Java
>           format("Service type %s not supported for following infrastructure step", serviceOutcome.getType()));
>     } else {
>       throw new UnsupportedOperationException("Null service not supported for following infrastructure step");
> ```

Instead of throwing an exception when serviceOutcome is null, we have to populate outcomes for SSH/WinRM Azure and SSH/WinRM AWS in order to consume it in the next custom stage steps.


You should have smt like this. The idea is to make decisions based on infrastructure outcome kind, and based on credentials type (SSH/WinRm).



_Code snippet:_
```Java
    .....
    if(serviceOutcome == null) {
      SecretDTOV2 credentialSpecDto = getCredentialSpecDto(infrastructureOutcome.getConnectorRef(), AmbianceUtils.getAccountId(ambiance),
              AmbianceUtils.getOrgIdentifier(ambiance), AmbianceUtils.getProjectIdentifier(ambiance));

      if(InfrastructureKind.SSH_WINRM_AZURE.equals(infrastructureOutcome.getKind())) {
        AzureInfraDelegateConfig azureInfraDelegateConfig;
        if(credentialSpecDto.getSpec() instanceof WinRmCredentialsSpecDTO){
          azureInfraDelegateConfig =
                  (AzureInfraDelegateConfig) publishWinRmInfraDelegateConfigOutput(infrastructureOutcome, ambiance);
        } else {
          azureInfraDelegateConfig =
                  (AzureInfraDelegateConfig) publishSshInfraDelegateConfigOutput(infrastructureOutcome, ambiance);
        }

        return buildAzureTaskRequest(ambiance, azureInfraDelegateConfig);

      } else if(InfrastructureKind.SSH_WINRM_AWS.equals(infrastructureOutcome.getKind())) {

        //...
        return buildAwsTaskRequest(ambiance, (AwsInfraDelegateConfig) awsInfraDelegateConfig);
      }
      .....
      //new method
    private SecretDTOV2 getCredentialSpecDto(
          final String sshKeyRef, final String accountId, final String orgIdentifier, final String projectIdentifier) {
    if (isEmpty(sshKeyRef)) {
      throw new InvalidRequestException("Missing SSH key for configured host(s)");
    }
    IdentifierRef identifierRef =
            IdentifierRefHelper.getIdentifierRef(sshKeyRef, accountId, orgIdentifier, projectIdentifier);
    String errorMSg = "No secret configured with identifier: " + sshKeyRef;
    SecretResponseWrapper secretResponseWrapper = NGRestUtils.getResponse(
            secretManagerClient.getSecret(identifierRef.getIdentifier(), identifierRef.getAccountIdentifier(),
                    identifierRef.getOrgIdentifier(), identifierRef.getProjectIdentifier()),
            errorMSg);
    if (secretResponseWrapper == null) {
      throw new InvalidRequestException(errorMSg);
    }

    return secretResponseWrapper.getSecret();
  }
      
```


<!-- Sent from Reviewable.io -->

2023-09-14 14:22 UTC, lovish1999 commented
trigger uts

2023-09-14 14:51 UTC, lovish1999 commented
trigger messagecheck

2023-09-14 19:01 UTC, ivan-83 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840#-:-NeK3MH_Chf0BMPXFA5T:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 482 at r4](https://reviewable.io/reviews/harness/harness-core/52840#-NeK2bHAEmAx3_A0tUs_:-NeK2bHAEmAx3_A0tUsa:b-nzmmb7) ([raw file](https://github.com/harness/harness-core/blob/aa2179fb0f504cd7fea40723cfe2d252d2a54046/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L482)):*
> ```Java
>     } else {
>       throw new UnsupportedOperationException(
>           format("Credential type %s not supported for following infrastructure step",
> ```

Minor  we need to distinguish two same error msg, msg could be >> Credential type % not supported in AWS SSH/WinRM infrastructure for following infrastructure step
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 500 at r4](https://reviewable.io/reviews/harness/harness-core/52840#-NeK1t110_fHq1kMn-aI:-NeK1t110_fHq1kMn-aJ:bydtvfd) ([raw file](https://github.com/harness/harness-core/blob/aa2179fb0f504cd7fea40723cfe2d252d2a54046/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L500)):*
> ```Java
>     } else {
>       throw new UnsupportedOperationException(
>           format("Credential type %s not supported for following infrastructure step",
> ```

Minor  we need to distinguish two same error msg,  msg could be >> Credential type % not supported in Azure SSH/WinRM infrastructure for following infrastructure step
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 505 at r4](https://reviewable.io/reviews/harness/harness-core/52840#-NeK0czx6qkbZp4D5iP0:-NeK0czx6qkbZp4D5iP1:b-3mvb6g) ([raw file](https://github.com/harness/harness-core/blob/aa2179fb0f504cd7fea40723cfe2d252d2a54046/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L505)):*
> ```Java
>   }
> 
>   private SecretDTOV2 getCredentialSpecDto(
> ```

Minor - getCredentialSpecDto method could be moved to CDStepHelper class.


<!-- Sent from Reviewable.io -->

2023-09-18 06:36 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 59 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb-K2f9AOGNCDxFL_d:-Neb-K2f9AOGNCDxFL_e:beeb51x) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L59)):*
> ```Java
>         .addAllChildren(stepParameters.getChildrenNodeIds()
>                             .stream()
>                             .map(id -> ChildrenExecutableResponse.Child.newBuilder().setChildNodeId(id).build())
> ```

what will be the children of Environment Step ?


<!-- Sent from Reviewable.io -->

2023-09-18 06:37 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStepParameters.java` line 26 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb-TD32Pd_c_Wbt8ng:-Neb-TD32Pd_c_Wbt8nh:b6j68kk) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStepParameters.java#L26)):*
> ```Java
> @RecasterAlias("io.harness.cdng.environment.steps.CustomStageEnvironmentStepParameters")
> public class CustomStageEnvironmentStepParameters implements StepParameters {
>   private List<String> childrenNodeIds;
> ```

is it nullable ?


<!-- Sent from Reviewable.io -->

2023-09-18 06:40 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/helper/ExecutionInfoKeyMapper.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb04MR1lGUIiWMKZrt:-Neb04MR1lGUIiWMKZru:b-byezgg) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/helper/ExecutionInfoKeyMapper.java#L43)):*
> ```Java
>         || InfrastructureKind.SSH_WINRM_AZURE.equals(infrastructureKind)
>         || InfrastructureKind.SSH_WINRM_AWS.equals(infrastructureKind)
>         || InfrastructureKind.TAS.equals(infrastructureKind) && (isBlank(infraIdentifier))) {
> ```

I think instead of doing a combination of || and && in the single statement, its better to do for readability
if (a || b || c ) {
 if ( d ) {
  // logic here 
}
}


<!-- Sent from Reviewable.io -->

2023-09-18 06:43 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 138 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb0ppS9C7wO2WskBoU:-Neb0ppS9C7wO2WskBoV:b-8sqteg) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L138)):*
> ```Java
>   }
> 
>   public PlanNode getInfraTaskExecutableStepV2PlanNode(EnvironmentYamlV2 environmentYamlV2) {
> ```

can we document why this method exists and how it is different from the other `getInfraTaskExecutableStepV2PlanNode` method in this class ? when should I use this vs the other method 


<!-- Sent from Reviewable.io -->

2023-09-18 06:44 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 171 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb1AtP6TSjkJLItbZt:-Neb1AtP6TSjkJLItbZu:bhigxx8) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L171)):*
> ```Java
>                 .build())
>         .skipExpressionChain(true)
>         .skipGraphType(SkipType.SKIP_TREE)
> ```

do we want to hide this node ?


<!-- Sent from Reviewable.io -->

2023-09-18 06:46 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb1Vae8wphqsFANLjo:-Neb1Vae8wphqsFANLjp:b-j7stvx) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L174)):*
> ```Java
>     final CustomStageEnvironmentStepParameters stepParameters = CustomStageEnvironmentStepParameters.builder().build();
> 
>     if (finalEnvironmentYamlV2.getInfrastructureDefinition() != null) {
> ```

what is this field is null but `infrastructureDefinitions` is set ?


<!-- Sent from Reviewable.io -->

2023-09-18 06:47 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, 1 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840)* status: 8 file(s) to review. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-18 11:17 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840)* status: 11 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 59 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb-K2f9AOGNCDxFL_d:-NebQWUTD6YgFbqVyae5:b-1f0who) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L59)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what will be the children of Environment Step ?
</blockquote></details>

Only manifest and config files
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStepParameters.java` line 26 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb-TD32Pd_c_Wbt8ng:-NebQZOe8pPS9I1mm7Ye:b32w12) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStepParameters.java#L26)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is it nullable ?
</blockquote></details>

No
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/helper/ExecutionInfoKeyMapper.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb04MR1lGUIiWMKZrt:-NebQ_Dz9_4eq_tKg4ru:b-hp2ph3) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution/helper/ExecutionInfoKeyMapper.java#L43)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think instead of doing a combination of || and && in the single statement, its better to do for readability
if (a || b || c ) {
 if ( d ) {
  // logic here 
}
}
</blockquote></details>

Ok. Actually sonar suggested to merge them so I merged the conditions. But will make the change. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 138 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb0ppS9C7wO2WskBoU:-NebQg3d9sVoRkz0KWAK:bb7oryy) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L138)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we document why this method exists and how it is different from the other `getInfraTaskExecutableStepV2PlanNode` method in this class ? when should I use this vs the other method
</blockquote></details>

sure
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 171 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb1AtP6TSjkJLItbZt:-NebQuCl8iACMhsyB8R2:b-y1jseg) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L171)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we want to hide this node ?
</blockquote></details>

no. As discussed over call, making the changes. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb1Vae8wphqsFANLjo:-NebQy5F2-LHUdSl3tmb:b-u35arm) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L174)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what is this field is null but `infrastructureDefinitions` is set ?
</blockquote></details>

We only support one env and infra currently. So UI will work accordingly. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 443 at r3](https://reviewable.io/reviews/harness/harness-core/52840#-NeIKfnfAVOvPgkvWAcx:-NebVgXX97v7G6kYGUnf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f7a8f970022bcda5b21edf0c4db2b9b63785f925/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L443)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Instead of throwing an exception when serviceOutcome is null, we have to populate outcomes for SSH/WinRM Azure and SSH/WinRM AWS in order to consume it in the next custom stage steps.


You should have smt like this. The idea is to make decisions based on infrastructure outcome kind, and based on credentials type (SSH/WinRm).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-18 22:36 UTC, ivan-83 requested changes
LGTM with minor comments.

> Reviewed 2 of 2 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840#-:-NeeQzrbEad13hmiHKke:b-o9mibo)* status: 9 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1202 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeJ3dW-OEIJUzzFMCA:-NeeJ3dW-OEIJUzzFMCB:ba22pve) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1202)):*
> ```Java
>     }
> 
>     return null;
> ```

I prefer returning Optional instead of null.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1205 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeJbT69V8mS74xL8vQ:-NeeJbT69V8mS74xL8vR:bca59hw) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1205)):*
> ```Java
>   }
> 
>   public SecretDTOV2 getCredentialSpecDto(
> ```

Should this method be private?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1208 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeJMBwA9k1om8r_sXa:-NeeJMBx-x8pIxnyERcf:b-o70ow) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1208)):*
> ```Java
>       final String sshKeyRef, final String accountId, final String orgIdentifier, final String projectIdentifier) {
>     if (isEmpty(sshKeyRef)) {
>       throw new InvalidRequestException("Missing SSH key for configured host(s)");
> ```

It could be an SSH key or NTLM/Kerberos credentials. It's better to make msg more generic, like missing SSH/WinRM credentials.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 142 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeKBwQAdMakTjiZGhN:-NeeKBwQAdMakTjiZGhO:bn7xa49) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L142)):*
> ```Java
>   cases we do not need to provide service definition type and skip  instances boolean.
>    */
>   public PlanNode getInfraTaskExecutableStepV2PlanNode(
> ```

It's better to rename this method getInfraTaskExecutableStepV2PlanNode >> getCustomStageInfraTaskExecutableStepV2PlanNode
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 247 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeLpUA-mef2ForFADO:-NeeLpUA-mef2ForFADP:b-3q42mx) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L247)):*
> ```Java
>   }
> 
>   private List<AdviserObtainment> addResourceConstraintDependencyWithWhenCondition(
> ```

Move this method to a common helper or utility class, make it public, and reuse it. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 254 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeMCvY3kZ8NEAo_zZc:-NeeMCvY3kZ8NEAo_zZd:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L254)):*
> ```Java
>   }
> 
>   private boolean isProjectScopedResourceConstraintQueueByFFOrSetting(PlanCreationContext ctx) {
> ```

The same as above.


<!-- Sent from Reviewable.io -->

2023-09-20 13:39 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840)* status: 9 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1202 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeJ3dW-OEIJUzzFMCA:-Nel6j198FCAfz0IAbTy:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1202)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I prefer returning Optional instead of null.
</blockquote></details>

ok
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1205 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeJbT69V8mS74xL8vQ:-Nel2GZABg1pFR0ov4qy:ba5k14c) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1205)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should this method be private?
</blockquote></details>

no, its used in other classes
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 1208 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeJMBwA9k1om8r_sXa:-Nel2braENpVlWe-Hz2P:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L1208)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

It could be an SSH key or NTLM/Kerberos credentials. It's better to make msg more generic, like missing SSH/WinRM credentials.
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 142 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeKBwQAdMakTjiZGhN:-Nel2u2dB_ljAd4ugXgP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L142)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

It's better to rename this method getInfraTaskExecutableStepV2PlanNode >> getCustomStageInfraTaskExecutableStepV2PlanNode
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 247 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeLpUA-mef2ForFADO:-Nel5-xB2uQB-cjZJJrR:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L247)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move this method to a common helper or utility class, make it public, and reuse it.
</blockquote></details>

ok
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 254 at r6](https://reviewable.io/reviews/harness/harness-core/52840#-NeeMCvY3kZ8NEAo_zZc:-Nel5-WM1XvMkCsSYDk-:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/444fd154751f470a8b932ad8781f4ee742a84bef/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L254)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-09-20 13:51 UTC, lovish1999 commented
trigger uts

2023-09-20 16:44 UTC, lovish1999 commented
trigger uts

2023-09-20 17:12 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840#-:-Nen_4AEBB-Y_6MYzg8n:bnfp4nl)* status: 12 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-21 09:23 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb1Vae8wphqsFANLjo:-Ner2FwTCZrR18ywQhia:b-f25hkj) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/CustomStagePlanCreator.java#L174)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

We only support one env and infra currently. So UI will work accordingly.
</blockquote></details>

as discussed, lets support infrasturctureDefinitions.get(0) as well


<!-- Sent from Reviewable.io -->

2023-09-21 09:24 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 6 files at r1, 3 of 7 files at r6, 5 of 6 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52840)* status: 2. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStepParameters.java` line 26 at r5](https://reviewable.io/reviews/harness/harness-core/52840#-Neb-TD32Pd_c_Wbt8ng:-NeqhoIfDD4Mh_NG-jvI:bsav7hh) ([raw file](https://github.com/harness/harness-core/blob/b19b0b27957d46976444eef9218e1f5f2d0a5b3e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStepParameters.java#L26)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

No
</blockquote></details>

Then we should annotate with NotNull 


<!-- Sent from Reviewable.io -->

2023-09-21 09:36 UTC, lovish1999 commented
trigger review

2023-09-21 09:39 UTC, merged