fix: [IDP-1157]: Make Scorecard Recaliberate API POST instead of GET
harness/harness-core pull request #52845
Opened 2023-09-13 11:07 UTC by Aashrit-Harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-13 11:45 UTC, Aashrit-Harness commented
trigger mesagecheck

2023-09-13 11:49 UTC, Aashrit-Harness commented
trigger messagecheck

2023-09-13 20:32 UTC, Aashrit-Harness commented
trigger uts

2023-09-14 04:33 UTC, Aashrit-Harness commented
trigger ut2

2023-09-14 05:14 UTC, Aashrit-Harness commented
trigger ut2

2023-09-14 08:17 UTC, Aashrit-Harness commented
trigger uts

2023-09-14 08:30 UTC, Aashrit-Harness commented
trigger ut4

2023-09-14 09:18 UTC, devesh-harness requested changes

2023-09-14 09:18 UTC, devesh-harness commented on idp-service/contracts/openapi/v1/openapi.yaml
> +    ScorecardRecaliberate:
can we rename it to ScorecardRecaliberateIdentifiers ?

2023-09-14 09:18 UTC, devesh-harness commented on idp-service/src/test/java/io/harness/idp/scorecard/scores/resources/ScoresApiImplTest.java
> +    Response response = scoreApiImpl.scorecardRecaliberate(scorecardRecaliberateRequest, TEST_ACCOUNT_IDENTIFIER);
we can create a common method to get scorecardRecaliberateRequest to avoid duplication, as we are doing same thing in two places

2023-09-14 09:19 UTC, devesh-harness requested changes

2023-09-14 09:19 UTC, devesh-harness commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java
> +import io.harness.spec.server.idp.v1.model.*;
avoid * here

2023-09-14 09:19 UTC, devesh-harness commented on idp-service/src/test/java/io/harness/idp/scorecard/scores/resources/ScoresApiImplTest.java
> +import io.harness.spec.server.idp.v1.model.*;
avoid * here

2023-09-14 10:36 UTC, Aashrit-Harness commented on idp-service/contracts/openapi/v1/openapi.yaml
> +    ScorecardRecaliberate:
Done

2023-09-14 10:36 UTC, Aashrit-Harness commented on idp-service/src/test/java/io/harness/idp/scorecard/scores/resources/ScoresApiImplTest.java
> +    Response response = scoreApiImpl.scorecardRecaliberate(scorecardRecaliberateRequest, TEST_ACCOUNT_IDENTIFIER);
Done

2023-09-14 10:36 UTC, Aashrit-Harness commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java
> +import io.harness.spec.server.idp.v1.model.*;
Done

2023-09-14 10:36 UTC, Aashrit-Harness commented on idp-service/src/test/java/io/harness/idp/scorecard/scores/resources/ScoresApiImplTest.java
> +import io.harness.spec.server.idp.v1.model.*;
Done

2023-09-14 11:08 UTC, Aashrit-Harness commented
trigger uts

2023-09-14 11:37 UTC, Aashrit-Harness commented
trigger ut3

2023-09-14 12:24 UTC, Aashrit-Harness commented
trigger ut2,ut4,ut9

2023-09-14 13:16 UTC, devesh-harness approved these changes

2023-09-14 15:19 UTC, Aashrit-Harness commented
trigger ut4

2023-09-14 17:37 UTC, Aashrit-Harness commented
trigger ut3

2023-09-15 05:00 UTC, vikyathharekal reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52845)* status: 3 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 3145 at r4](https://reviewable.io/reviews/harness/harness-core/52845#-NeMCMQ25DnYv1fVtEPK:-NeMCMQ25DnYv1fVtEPL:b-ord2aa) ([raw file](https://github.com/harness/harness-core/blob/992e8baf3afe332ed16b15150ad8a48a03768a18/idp-service/contracts/openapi/v1/openapi.yaml#L3145)):*
> ```YAML
>       type: object
>       properties:
>         identifiers:
> ```

Do we need another layer (identifiers) here? Or can we directly refer ScorecardRecalibrateIdentifiers in ScorecardRecalibrateRequest?



_Code quote:_
```YAML
identifiers:
```
___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 3449 at r4](https://reviewable.io/reviews/harness/harness-core/52845#-NeMBpT14xjZpyKdfhiZ:-NeMBpT14xjZpyKdfhi_:bb3ymmo) ([raw file](https://github.com/harness/harness-core/blob/992e8baf3afe332ed16b15150ad8a48a03768a18/idp-service/contracts/openapi/v1/openapi.yaml#L3449)):*
> ```YAML
>     ScorecardRecalibrateRequest:
>       content:
>         application/json:
> ```

can we add one for application/yaml as well?


<!-- Sent from Reviewable.io -->

2023-09-15 05:49 UTC, mankrit-singh approved these changes
small comment, feel free to take it up in the next PR

2023-09-15 05:49 UTC, mankrit-singh commented on idp-service/contracts/openapi/v1/openapi.yaml
> +      summary: ''
Please add the summary again

2023-09-15 05:59 UTC, vikyathharekal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52845#-:-NeMQ5Rd9gJL1Pi8BHRY:bnfp4nl)* status: 3 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-15 06:00 UTC, Aashrit-Harness commented
trigger review

2023-09-15 06:04 UTC, merged