[feat]: [CDS-78565]: Created a poller to pick up the queued webhook events
harness/harness-core pull request #52856
Opened 2023-09-13 12:25 UTC by adivishy1

## Describe your changes
The following code has been implemented:
1. Added gitX webhook poller for listening to webhook events which are in QUEUED state from GitXWebhook db. 
2. The poller listens checks for queued webhook events and compares the file path in webhook and the event. 
3. Once the file paths matches, we create background task to update the file cache.

Have tested out the code flow locally, the code is working as expected.
The state management to handle all the different webhook state will be implemented in the follow up pr.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-20 11:12 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemHNgm-UVPDTRC-zsr:-NemHNgm-UVPDTRC-zss:b-pk8r9n) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java#L127)):*
> ```Java
>   public static final String SCM_ON_DELEGATE = "scmOnDelegate";
>   public static final String GITX_BACKGROUND_CACHE_UPDATE_EXECUTOR_NAME = "gitxBackgroundCacheUpdateExecutorName";
>   public static final String GITX_WEBHOOK_CACHE_UPDATE_EXECUTOR_NAME = "gitxWebhookCacheUpdateExecutorName";
> ```

shouldn't we call it "gitxWebhookHandlerExecutor"? It would help to keep it bit generic in terms of the task it performs. For now, its updating cache, what if it does something else later?


<!-- Sent from Reviewable.io -->

2023-09-20 11:31 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 65 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemLw4v8g2ohQMILkjQ:-NemLw4v8g2ohQMILkjR:bl239ky) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L65)):*
> ```Java
>   String eventStatus;
>   Long eventTriggeredTime;
>   String commitIdBeforeTriggerEvent;
> ```

This naming can be better


<!-- Sent from Reviewable.io -->

2023-09-20 11:32 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemM7_bEYMFNN5Ejkka:-NemM7_bEYMFNN5Ejkkb:b-wxsqh8) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L25)):*
> ```Java
> @Slf4j
> public class GitXWebhookCacheUpdateRunnable implements Runnable {
>   @Inject ScmFacilitatorService scmFacilitatorService;
> ```

these should also be private


<!-- Sent from Reviewable.io -->

2023-09-20 11:35 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemMKjd3wuHKtMk_-8O:-NemMKjd3wuHKtMk_-8P:bk2c7mm) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L28)):*
> ```Java
>   @Inject GitXWebhookEventService gitXWebhookEventService;
>   private ScmGetBatchFilesByBranchRequestDTO scmGetBatchFilesByBranchRequestDTO;
>   private String eventIdentifier;
> ```

there should only be service inside the runnable, not the data objects


<!-- Sent from Reviewable.io -->

2023-09-20 11:36 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemN3KaCNX0iRhdhlk0:-NemN3KaCNX0iRhdhlk1:bj29bjg) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L38)):*
> ```Java
>   @Override
>   public void run() {
>     try (ResponseTimeRecorder ignore2 = new ResponseTimeRecorder("FetchFilesFromGitRunnable BG Task")) {
> ```

The argument message is unrelated, should be fixed


<!-- Sent from Reviewable.io -->

2023-09-20 11:36 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemN7e9BpNTpvQB2hlz:-NemN7e9BpNTpvQB2hm-:bis5j4v) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L44)):*
> ```Java
>           GitXWebhookEventStatus.SUCCESSFUL);
>     } catch (Exception exception) {
>       log.error("Unexpected error", exception);
> ```

bad logging


<!-- Sent from Reviewable.io -->

2023-09-20 11:37 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNEdwAHwJWFlbXdmI:-NemNEdwAHwJWFlbXdmJ:b-8xtshw) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L38)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @Slf4j
> public class GitXWebhookProcessingRunnable implements Runnable {
> ```

processor* ?


<!-- Sent from Reviewable.io -->

2023-09-20 11:37 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 55 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNHyq8MpkIWLAnWr6:-NemNHyq8MpkIWLAnWr7:bis5j4v) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L55)):*
> ```Java
> 
>     } catch (Exception exception) {
>       log.error("Unexpected error", exception);
> ```

bad logging


<!-- Sent from Reviewable.io -->

2023-09-20 11:37 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNQyw3LyB5FBJ6MmP:-NemNQyw3LyB5FBJ6MmQ:b2ve89e) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L59)):*
> ```Java
>   }
> 
>   private List<GitXWebhookEvent> getQueuesGitXWebhookEvents() {
> ```

Queued*


<!-- Sent from Reviewable.io -->

2023-09-20 11:38 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNVT2-PBQ9xaqsJma:-NemNVT2-PBQ9xaqsJmb:b-r30mp7) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L64)):*
> ```Java
>   }
> 
>   private void processQueuedEvents(GitXWebhookEvent gitXWebhookEvent) {
> ```

event*


<!-- Sent from Reviewable.io -->

2023-09-20 11:38 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNZFT-F2XHnYDu8Zp:-NemNZFT-F2XHnYDu8Zq:b-xjhgpk) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L68)):*
> ```Java
>     if (gitXWebhook == null) {
>       gitXWebhookEventService.updateEvent(gitXWebhookEvent.getAccountIdentifier(),
>           gitXWebhookEvent.getEventIdentifier(), GitXWebhookEventStatus.FAILED);
> ```

if webhook isn't found, then why is it failed?


<!-- Sent from Reviewable.io -->

2023-09-20 11:39 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNjqU2uPKIRnWom59:-NemNjqU2uPKIRnWom5A:bipom4) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L79)):*
> ```Java
>           gitXWebhookEvent.getEventIdentifier(), GitXWebhookEventStatus.SKIPPED);
>     } else {
>       gitXWebhookEventService.updateEvent(gitXWebhookEvent.getAccountIdentifier(),
> ```

we should create a flow diagram explaining the state machine. If not complete tech spec, atleast this helps to understand how the flow works.


<!-- Sent from Reviewable.io -->

2023-09-20 11:39 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNsZt2Oof_PR5QnD4:-NemNsZt2Oof_PR5QnD5:b-5kkke8) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L60)):*
> ```Java
> 
>   private List<GitXWebhookEvent> getQueuesGitXWebhookEvents() {
>     Criteria criteria = Criteria.where(GitXWebhookEventKeys.eventStatus).is(GitXWebhookEventStatus.QUEUED);
> ```

what if something is in PROCESSING state but thread that was processing it had died?


<!-- Sent from Reviewable.io -->

2023-09-20 11:41 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemO5m72bVmgoNDKrpY:-NemO5m72bVmgoNDKrpZ:bssp3jt) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L106)):*
> ```Java
>       ScmGetFileByBranchRequestDTO scmGetFileByBranchRequestDTO =
>           ScmGetFileByBranchRequestDTO.builder()
>               .scope(Scope.of(gitXWebhook.getAccountIdentifier(), "", ""))
> ```

there should be a better util method to create scopes for account or org only, this is pretty messy


<!-- Sent from Reviewable.io -->

2023-09-20 11:42 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 124 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemOOLg-17HkdINrab_:-NemOOLg-17HkdINraba:b-hfie6l) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L124)):*
> ```Java
>   }
> 
>   private List<String> shouldParsePayload(
> ```

method name doesn't align with return type. If its "should" then expected return type is boolean.


<!-- Sent from Reviewable.io -->

2023-09-20 11:43 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemOecs8XsVgmykz7X-:-NemOecs8XsVgmykz7X0:bws2tqh) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L140)):*
> ```Java
> 
>   private GitXWebhook getGitXWebhook(GitXWebhookEvent gitXWebhookEvent) {
>     List<GitXWebhook> gitXWebhookList = gitXWebhookRepository.findByAccountIdentifierAndIdentifier(
> ```

how can we call repo layer directly here. Its wrong per design. We can only interact with any service layers anywhere. Only the respective service layer interacts with its repo layer.


<!-- Sent from Reviewable.io -->

2023-09-20 11:45 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventHelper.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemP2C30mkPDWGZeoyF:-NemP2C30mkPDWGZeoyG:bswp6qz) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventHelper.java#L38)):*
> ```Java
>   private final GitRepoHelper gitRepoHelper;
> 
>   public List<String> getDiffFilesUsingSCM(
> ```

why is this method required in a gix "webhook event" helper? Is it doing something special as per handling of gitx webhook event? If not, then it should in itself be a part of some service only.


<!-- Sent from Reviewable.io -->

2023-09-20 11:46 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemPD8t8b-_I6YhE5b2:-NemPD8t8b-_I6YhE5b3:b-sbmme5) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventHelper.java#L59)):*
> ```Java
>   }
> 
>   public ScmConnector getScmConnector(String accountIdentifier, String connectorRef, String repoName) {
> ```

Getting an SCM connector shouldn't be done anywhere outside already created helper layers. It should all come from a single centralized place.


<!-- Sent from Reviewable.io -->

2023-09-21 06:05 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 16 file(s) to review. 1 change requests. 18. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemHNgm-UVPDTRC-zsr:-Nem_Yc0C3huSRakaZj1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/GitSyncModule.java#L127)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't we call it "gitxWebhookHandlerExecutor"? It would help to keep it bit generic in terms of the task it performs. For now, its updating cache, what if it does something else later?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java` line 65 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemLw4v8g2ohQMILkjQ:-Neq4Bio6UWCPwcOEq08:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity/GitXWebhookEvent.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This naming can be better
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateHelper.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemM-u46HsKjEVvgkru:-Neq4Diq2_tiaExWOwn7:b-r0punc) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateHelper.java#L42)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log should be improved
</blockquote></details>

in the following ticket will be added but as part of this pr, have changed the error message
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemM7_bEYMFNN5Ejkka:-Neq4l0R-ntqznD_whdd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

these should also be private
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemN3KaCNX0iRhdhlk0:-Neq5KmJ7ImsM_sQPmZz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The argument message is unrelated, should be fixed
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemN7e9BpNTpvQB2hlz:-NeqCCzkBJ73pFWPKe84:b-r0punc) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

bad logging
</blockquote></details>

in the following ticket will be added but as part of this pr, have changed the error message
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 38 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNEdwAHwJWFlbXdmI:-NeqCLJE-9wr5GmBlv6J:b-22w8ex) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

processor* ?
</blockquote></details>

sounds better
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 55 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNHyq8MpkIWLAnWr6:-NeqCibA6BQtcPmn28DB:b-r0punc) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

bad logging
</blockquote></details>

in the following ticket will be added but as part of this pr, have changed the error message
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNQyw3LyB5FBJ6MmP:-NeqCUlt9EpWa_xgbREJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Queued*
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNVT2-PBQ9xaqsJma:-NeqCwpd4P0qBy2grIAL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

event*
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNZFT-F2XHnYDu8Zp:-NeqD6bQED-HJWaqqIVz:ble5s8f) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if webhook isn't found, then why is it failed?
</blockquote></details>

changed it to SKIPPED
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNjqU2uPKIRnWom59:-NeqDP5z0UNxP4khMBFc:b52vy08) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L79)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should create a flow diagram explaining the state machine. If not complete tech spec, atleast this helps to understand how the flow works.
</blockquote></details>

will add it in the tech spec
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebho [...]

2023-09-21 06:06 UTC, adivishy1 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemMKjd3wuHKtMk_-8O:-NeqL1CzAip7aq29F4GT:b180zkj) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

there should only be service inside the runnable, not the data objects
</blockquote></details>

as discussed offline, we are good with it


<!-- Sent from Reviewable.io -->

2023-09-21 06:20 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 18 file(s) to review. 1 change requests. 21. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNLfz8VzyI_0UA8ee:-NeqOOpD4C0lkpXuphrm:bneuzy2) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L54)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if exception happens, then will this thread die completely?
</blockquote></details>

when the exception occurs, if the thread dies, we will have the following cases:  

1.  while getting the queued events
2.  while processing the events

in the first case, we should be good as the poller will pick it up in the next cyclein the second case, if we changed the status to processing but we failed to submit the task we will be in trouble, so will first submit the task and then change the status to processing
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNsZt2Oof_PR5QnD4:-NeqORVY17lZhOPB0Yo6:bpxplgh) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L60)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if something is in PROCESSING state but thread that was processing it had died?
</blockquote></details>

we are handling it after the cache updation happens


<!-- Sent from Reviewable.io -->

2023-09-22 05:24 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 18 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNLfz8VzyI_0UA8ee:-NevL0yTDvzBhHsuox94:bqr09bi) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L54)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

when the exception occurs, if the thread dies, we will have the following cases:  

1.  while getting the queued events
2.  while processing the events

in the first case, we should be good as the poller will pick it up in the next cyclein the second case, if we changed the status to processing but we failed to submit the task we will be in trouble, so will first submit the task and then change the status to processing
</blockquote></details>

This is the poller thread itself. So, if this thread dies, essentially our poller dies until next restart/deployment, isn't it?


<!-- Sent from Reviewable.io -->

2023-09-22 05:25 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 18 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemO5m72bVmgoNDKrpY:-NevLMD42ZtNJxJkWahb:b408z8q) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L106)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

checked, we dont have better util methods, we are passing it this way, some places they pass as null instead of empty string
</blockquote></details>

We should create util method to do these kind of stuff. This is very bad way of doing it right now.


<!-- Sent from Reviewable.io -->

2023-09-22 05:40 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemNLfz8VzyI_0UA8ee:-NevNR-E74cvFskQDTMo:bc4rc91) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L54)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is the poller thread itself. So, if this thread dies, essentially our poller dies until next restart/deployment, isn't it?
</blockquote></details>

The new thread will be spawned from the thread pool, https://stackoverflow.com/questions/37909543/are-dead-threads-replaced-in-an-executioncontext-and-or-java-thread-pool#:~:text=The%20thread%20itself%20cannot%20spawn,replaces%20dead%20threads%20when%20needed.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/52856#-NemO5m72bVmgoNDKrpY:-NevOGPM3-5h9sdV1LOE:b2o9q86) ([raw file](https://github.com/harness/harness-core/blob/1d799ecc1b353429faac779b142b018175d50d48/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessingRunnable.java#L106)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should create util method to do these kind of stuff. This is very bad way of doing it right now.
</blockquote></details>

added a util for the same


<!-- Sent from Reviewable.io -->

2023-09-22 06:26 UTC, adivishy1 commented
trigger uts

2023-09-22 07:05 UTC, mohitg0795 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52856)* status: 19 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 07:11 UTC, utkarshchoubey-harness approved these changes

2023-09-22 07:12 UTC, adivishy1 commented
trigger review

2023-09-22 07:15 UTC, merged