[feat]: [CDS-78377]: Addition of variables & variable overrides support for custom stage environment
harness/harness-core pull request #52850
Opened 2023-09-13 11:34 UTC by lovish1999

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-18 10:13 UTC, tchaurasiya requested changes

2023-09-18 12:39 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/BUILD.bazel
> -        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps:module",
removed the class

2023-09-18 12:45 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentStepParameters.java
> -@RecasterAlias("io.harness.cdng.environment.steps.EnvironmentStepParameters")
deleting the class

2023-09-19 10:10 UTC, ivan-83 requested changes
> Reviewed 9 of 14 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850)* status: 17 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 168 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-Negrb817yTNgVYPSNle:-Negrb817yTNgVYPSNlf:bh4wzr5) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L168)):*
> ```Java
>         if (isOverridesV2enabled) {
>           if (ngEnvironmentConfig != null && ngEnvironmentConfig.getNgEnvironmentInfoConfig() != null
>               && !mergedOverrideV2Configs.containsKey(ENV_GLOBAL_OVERRIDE)) {
> ```

@tchaurasiya ENV_GLOBAL_OVERRIDE is referring to only env overrides, right?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 184 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegtmP27oKOtL15Kn-N:-NegtmP33S1G2IUUM1xh:bzcabt9) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L184)):*
> ```Java
>           }
>         }
>         serviceStepsHelper.checkForAccessOrThrow(ambiance, secretNGVariables);
> ```

We could the whole logic for checking secretNgVariables move to a separate method if the method doesn't require more then 5 params.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegsBKZ1u5MVxLqOqry:-NegsBKZ1u5MVxLqOqrz:b-s5hdbx) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L186)):*
> ```Java
>         serviceStepsHelper.checkForAccessOrThrow(ambiance, secretNGVariables);
> 
>         NGServiceOverrideConfig ngServiceOverrides =
> ```

Can toEnvironmentOutcome be null and handle null logic in EnvironmentMapper.toEnvironmentOutcome method.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 202 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegsUFgCb9EpsPrRQsz:-NegsUFgCb9EpsPrRQt-:b-80vvsq) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L202)):*
> ```Java
>               StepUtils.generateLogAbstractions(ambiance), List.of(ENVIRONMENT_COMMAND_UNIT))))
>           .addAllUnits(List.of(ENVIRONMENT_COMMAND_UNIT))
>           .addAllChildren(stepParameters.getChildrenNodeIds()
> ```

The children list is empty in stepParams, how are we going to execute configFile, manifests, app settings, and conn strings steps?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-Neggxg52WN_NrhQvdpY:-Neggxg52WN_NrhQvdpZ:b-fc14oc) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L192)):*
> ```Java
>     // two NG Manager deployments
>     if (ParameterField.isNull(parameters.getInfraId()) || isEmpty(parameters.getInfraId().getValue())) {
>       log.warn("Infra Identifier has not been resolved to get service overrides");
> ```

We don't need this warning for the custom stage because infra is optional.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegiBT4-6ctQehqvBn7:-NegiBT4-6ctQehqvBn8:byar0r4) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L206)):*
> ```Java
> 
>       EnumMap<ServiceOverridesType, NGServiceOverrideConfigV2> acrossScopeMergedOverrides =
>           getMergedOverridesAcrossScope(allTypesOverridesV2);
> ```

@tchaurasiya Does getMergedOverridesAcrossScope method merge overrides across projects/org/accounts?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 265 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegidAj1QbuJqXE8wAe:-NegidAj1QbuJqXE8wAf:b-49f57s) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L265)):*
> ```Java
>     }
> 
>     if (ParameterField.isNotNull(parameters.getServiceRef()) && !parameters.getServiceRef().isExpression()
> ```

This is good.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java` line 282 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegipCK8Iz6jIZ5gmYm:-NegipCK8Iz6jIZ5gmYn:b-49f57s) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java#L282)):*
> ```Java
>       }
> 
>       if (ParameterField.isNotNull(parameters.getServiceRef()) && !parameters.getServiceRef().isExpression()
> ```

This is good.


<!-- Sent from Reviewable.io -->

2023-09-20 14:20 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-NemxWpH5G4cRLjblT1G:-NemxWpH5G4cRLjblT1H:b-7ed6pk) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L98)):*
> ```Java
>   @Override
>   public Class<ServiceStepV3Parameters> getStepParametersClass() {
>     return ServiceStepV3Parameters.class;
> ```

should we not use a new step parameter class for this instead or reusing the one for serviceStepV3 ? This will cause unwanted coupling


<!-- Sent from Reviewable.io -->

2023-09-20 14:22 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 122 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-Nemxv4fAz2XU5-7plUg:-Nemxv4fAz2XU5-7plUh:bkzmigy) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L122)):*
> ```Java
>       EnvironmentStepsUtils.checkForEnvAccessOrThrow(accessControlClient, ambiance, envRef);
> 
>       if (envRef.fetchFinalValue() != null) {
> ```

we should exit before only if this is null and not have the entire code within an `if` block
something like
```
if (envRef.fetchFinalValue() == null ) {
   // throw exception
}

// rest of the code here
```


<!-- Sent from Reviewable.io -->

2023-09-20 14:22 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 124 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-Nemy73u4cJlD3LGg7dV:-Nemy73u4cJlD3LGg7dW:b-bu698s) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L124)):*
> ```Java
>       if (envRef.fetchFinalValue() != null) {
>         Optional<Environment> environment =
>             environmentService.get(accountId, orgIdentifier, projectIdentifier, envRef.getValue(), false);
> ```

lets use `fetchFinalValue()` instead of getValue


<!-- Sent from Reviewable.io -->

2023-09-20 14:22 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 126 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-NemyCzICQ-1V7c3KkKD:-NemyCzICQ-1V7c3KkKE:b-bu698s) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L126)):*
> ```Java
>             environmentService.get(accountId, orgIdentifier, projectIdentifier, envRef.getValue(), false);
>         if (environment.isEmpty()) {
>           throw new InvalidRequestException(String.format("Environment with ref: [%s] not found", envRef.getValue()));
> ```

lets use `fetchFinalValue()` instead of getValue


<!-- Sent from Reviewable.io -->

2023-09-20 14:23 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-NemyL3uCK6qIVBTJweQ:-NemyL3uCK6qIVBTJweR:b5sjzq5) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L146)):*
> ```Java
>                 accountId, orgIdentifier, projectIdentifier, stepParameters, environment.get(), logCallback);
>           } catch (IOException e) {
>             throw new RuntimeException(e);
> ```

we should wrap it in InvalidRequestException instead


<!-- Sent from Reviewable.io -->

2023-09-20 14:26 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 162 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-NemyuzJ20k0Tii9YuKF:-NemyuzKEa4x09sSLm0C:bs6oo9s) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L162)):*
> ```Java
>           throw new InvalidRequestException(
>               "Unable to read yaml for environment: " + environment.get().getIdentifier(), ex);
>         }
> ```

We should modularize the code. Looks like we have put all the logic into 1 long method here. It is not very readable


<!-- Sent from Reviewable.io -->

2023-09-20 14:27 UTC, yogesh-chauhan reviewed
> Reviewed 4 of 14 files at r1, 1 of 7 files at r2, 1 of 1 files at r3, 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850)* status: 11 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-20 18:04 UTC, lovish1999 commented
trigger uts

2023-09-20 18:11 UTC, lovish1999 commented
trigger commonchecks

2023-09-21 08:59 UTC, ivan-83 requested changes
> Reviewed 5 of 6 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850)* status: 10 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegsBKZ1u5MVxLqOqry:-NequlxS3wDuSbsVwZj1:b-d1akg3) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L186)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

no, it cannot be null
</blockquote></details>

Sorry, I meant on ngServiceOverrides, just having it as null and handling null the logic in toEnvironmentOutcome method.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-NemxWpH5G4cRLjblT1G:-NeqwseZ6yA6Kju6dWZU:b-t77xdl) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L98)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not use a new step parameter class for this instead or reusing the one for serviceStepV3 ? This will cause unwanted coupling
</blockquote></details>

agree.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 156 at r5](https://reviewable.io/reviews/harness/harness-core/52850#-Neqxh_I-rfVjFZNVuAU:-Neqxh_I-rfVjFZNVuAV:b-pw3k90) ([raw file](https://github.com/harness/harness-core/blob/589dc6fd31e94a0fe26c0c9ef9741496d727fde7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L156)):*
> ```Java
>           ngEnvironmentConfig, ngServiceOverrides, mergedOverrideV2Configs, ambiance, isOverridesV2enabled);
> 
>       final EnvironmentOutcome environmentOutcome = EnvironmentMapper.toEnvironmentOutcome(environment.get(),
> ```

what is the difference between ngEnvironmentConfig and mergedOverrideV2Configs?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 313 at r5](https://reviewable.io/reviews/harness/harness-core/52850#-NeqwE-vDzbjG3-fekqR:-NeqwE-wAxSM5JA1j1Iq:b-5wq0xl) ([raw file](https://github.com/harness/harness-core/blob/589dc6fd31e94a0fe26c0c9ef9741496d727fde7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L313)):*
> ```Java
>           (VariablesSweepingOutput) outputObj, StepCategory.STAGE.name());
> 
>       saveExecutionLog(serviceStepLogCallback, "Processed service & environment variables");
> ```

This is the new log line in the deploy stage service and environment custom stage steps, right?


<!-- Sent from Reviewable.io -->

2023-09-21 09:27 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 99 at r5](https://reviewable.io/reviews/harness/harness-core/52850#-Ner3-Up401kkmj4wgYv:-Ner3-Up401kkmj4wgYw:b-i5wuj7) ([raw file](https://github.com/harness/harness-core/blob/589dc6fd31e94a0fe26c0c9ef9741496d727fde7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L99)):*
> ```Java
> 
>   public ChildrenExecutableResponse obtainChildren(
>       Ambiance ambiance, ServiceStepV3Parameters parameters, StepInputPackage inputPackage) {
> ```

// write an adapter to convert CustomStageEnvParams to serviceStepV3Parameters 


<!-- Sent from Reviewable.io -->

2023-09-21 12:10 UTC, lovish1999 commented
trigger uts

2023-09-21 13:02 UTC, lovish1999 commented
trigger uts

2023-09-21 13:23 UTC, lovish1999 commented
trigger uts

2023-09-21 16:36 UTC, lovish1999 commented
trigger uts

2023-09-21 18:16 UTC, lovish1999 commented
trigger uts

2023-09-21 19:17 UTC, lovish1999 commented
trigger uts

2023-09-21 20:02 UTC, lovish1999 commented
trigger uts

2023-09-22 07:07 UTC, lovish1999 commented
trigger ut5

2023-09-22 09:07 UTC, ivan-83 reviewed
> Reviewed 1 of 7 files at r6, 5 of 10 files at r7, 2 of 3 files at r8, 4 of 4 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850)* status: 15 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 252 at r10](https://reviewable.io/reviews/harness/harness-core/52850#-New7jAjD-YRGBGjyZJi:-New7jAjD-YRGBGjyZJj:bahtana) ([raw file](https://github.com/harness/harness-core/blob/ab3193b1abaeedef1b9b6dc82b67dfe05cba9b9f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L252)):*
> ```Java
>   }
> 
>   private ServiceStepV3Parameters toServiceStepV3Parameters(CustomStageEnvironmentStepParameters parameters) {
> ```

Minor- should be part of a separate mapper class.


<!-- Sent from Reviewable.io -->

2023-09-25 05:47 UTC, lovish1999 commented
trigger uts

2023-09-25 06:00 UTC, lovish1999 commented
trigger uts

2023-09-25 07:28 UTC, lovish1999 commented
trigger ut0

2023-09-25 07:47 UTC, lovish1999 commented
trigger ut1

2023-09-25 08:05 UTC, lovish1999 commented
trigger uts

2023-09-25 09:18 UTC, lovish1999 commented
trigger ut4

2023-09-25 09:18 UTC, lovish1999 commented
trigger ut6

2023-09-25 09:30 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/beans/CustomStageEnvironmentStepParameters.java` line 37 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAf9X0360bOha2VbxX:-NfAf9X0360bOha2VbxY:b-tuekzy) ([raw file](https://github.com/harness/harness-core/blob/ab49bc05f5756e2799826b61fe4b609efeeee601/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/beans/CustomStageEnvironmentStepParameters.java#L37)):*
> ```Java
>   @Override
>   public List<String> excludeKeysFromStepInputs() {
>     return new LinkedList<>(Arrays.asList("envRef", "infraId", "envInputs", "childrenNodeIds"));
> ```

we should show environmentRef and infraId in the step inputs 


<!-- Sent from Reviewable.io -->

2023-09-25 09:33 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 140 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAfsDC60sMXLtrrsNW:-NfAfsDC60sMXLtrrsNX:bp6pihc) ([raw file](https://github.com/harness/harness-core/blob/ab49bc05f5756e2799826b61fe4b609efeeee601/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L140)):*
> ```Java
> 
>       sweepingOutputService.consume(
>           ambiance, OutputExpressionConstants.ENVIRONMENT, environmentOutcome, StepCategory.STAGE.name());
> ```

we should resolve infraId after we save the environment outcome. This allows for infraIds to be resolved if they contain <+env> in the expression


<!-- Sent from Reviewable.io -->

2023-09-25 09:36 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 622 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAgelZC1JNPCj1eQZQ:-NfAgelZC1JNPCj1eQZR:bac59c4) ([raw file](https://github.com/harness/harness-core/blob/790caea2e78633f7bec292bd00c3e52369e0627f/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L622)):*
> ```help
> io.harness.cdng.aws.asg.UserDataOutcome
> io.harness.cdng.gitops.beans.GitOpsLinkedAppsOutcome
> io.harness.cdng.environment.steps.EnvironmentStepParameters
> ```

do we need to delete EnvironmentStepParameters class as well ?


<!-- Sent from Reviewable.io -->

2023-09-25 09:37 UTC, yogesh-chauhan requested changes
> Reviewed 1 of 14 files at r1, 1 of 7 files at r2, 1 of 6 files at r4, 1 of 3 files at r5, 1 of 7 files at r6, 3 of 10 files at r7, 2 of 3 files at r8, 4 of 4 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850)* status: 3 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 113 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAff3q0KpC2RF31SaV:-NfAff3q0KpC2RF31SaW:b-t67722) ([raw file](https://github.com/harness/harness-core/blob/ab49bc05f5756e2799826b61fe4b609efeeee601/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L113)):*
> ```Java
> 
>       if (!ParameterField.isNull(parameters.getInfraId()) && parameters.getInfraId().isExpression()) {
>         serviceStepV3Helper.resolve(ambiance, parameters.getInfraId());
> ```

this resolution is not needed since step parameters would be resolved automatically


<!-- Sent from Reviewable.io -->

2023-09-25 10:51 UTC, lovish1999 commented
trigger ut4

2023-09-25 11:22 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 10 files at r7, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850#-:-NfB3p9j8H-VS4Hp0w4e:bnfp4nl)* status: 3 file(s) to review. 2 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-25 11:41 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850)* status: 3 file(s) to review. 2 change requests. 10. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/beans/CustomStageEnvironmentStepParameters.java` line 37 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAf9X0360bOha2VbxX:-NfB7uADAzPo7DyXby76:bmxuhg7) ([raw file](https://github.com/harness/harness-core/blob/ab49bc05f5756e2799826b61fe4b609efeeee601/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/beans/CustomStageEnvironmentStepParameters.java#L37)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should show environmentRef and infraId in the step inputs
</blockquote></details>

Okay. Will make this change in next upcoming PR.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 168 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-Negrb817yTNgVYPSNle:-NfB84t4Bn9950kx-vA7:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L168)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@tchaurasiya ENV_GLOBAL_OVERRIDE is referring to only env overrides, right?
</blockquote></details>

Yes
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 184 at r3](https://reviewable.io/reviews/harness/harness-core/52850#-NegtmP27oKOtL15Kn-N:-NfB85nCC3DVgTmADEM_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8ee4a0b6919a257c034626db1740f58825e61d95/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L184)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We could the whole logic for checking secretNgVariables move to a separate method if the method doesn't require more then 5 params.
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-NemxWpH5G4cRLjblT1G:-NfB7zaF2G_Dh8x7ekE1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L98)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

agree.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 148 at r4](https://reviewable.io/reviews/harness/harness-core/52850#-NemyGoA47Hfd8In6ti-:-NfB83AHE2eCQOL-gmw2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/949ac042de4ce559842be799431435fad6f3064f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L148)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets move overrides handling into a new method itself
</blockquote></details>

Done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 99 at r5](https://reviewable.io/reviews/harness/harness-core/52850#-Ner3-Up401kkmj4wgYv:-NfB8-BkAL4Q4nDtNuq8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/589dc6fd31e94a0fe26c0c9ef9741496d727fde7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L99)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

// write an adapter to convert CustomStageEnvParams to serviceStepV3Parameters
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 252 at r10](https://reviewable.io/reviews/harness/harness-core/52850#-New7jAjD-YRGBGjyZJi:-NfB7qZ-5CsO8CLponc-:bmxuhg7) ([raw file](https://github.com/harness/harness-core/blob/ab3193b1abaeedef1b9b6dc82b67dfe05cba9b9f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L252)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor- should be part of a separate mapper class.
</blockquote></details>

Okay. Will make this change in next upcoming PR.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 113 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAff3q0KpC2RF31SaV:-NfB82Ma3JAZWgNjFCC2:bmxuhg7) ([raw file](https://github.com/harness/harness-core/blob/ab49bc05f5756e2799826b61fe4b609efeeee601/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L113)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this resolution is not needed since step parameters would be resolved automatically
</blockquote></details>

Okay. Will make this change in next upcoming PR.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java` line 140 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAfsDC60sMXLtrrsNW:-NfB88FA5XouAOtFKQbf:bmxuhg7) ([raw file](https://github.com/harness/harness-core/blob/ab49bc05f5756e2799826b61fe4b609efeeee601/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/steps/CustomStageEnvironmentStep.java#L140)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should resolve infraId after we save the environment outcome. This allows for infraIds to be resolved if they contain <+env> in the expression
</blockquote></details>

Okay. Will make this change in next upcoming PR.
___
*[`125-cd-nextgen/src/test/resources/recaster/alias/alias.txt` line 622 at r12](https://reviewable.io/reviews/harness/harness-core/52850#-NfAgelZC1JNPCj1eQZQ:-NfB7gay44VSNun52Fjl:b-25t781) ([raw file](https://github.com/harness/harness-core/blob/790caea2e78633f7bec292bd00c3e52369e0627f/125-cd-nextgen/src/test/resources/recaster/alias/alias.txt#L622)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to delete EnvironmentStepParameters class as well ?
</blockquote></details>

Yes, its not used anywhere and was causing build cycle issues. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java` line 313 at r5](https://reviewable.io/reviews/harness/harness-core/52850#-NeqwE-vDzbjG3-fekqR:-NfB7myf1uox_PQFYNke:b-7xt2jw) ([raw file](https://github.com/harness/harness-core/blob/589dc6fd31e94a0fe26c0c9ef9741496d727fde7/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceStepsHelper.java#L313)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This is the new log line in the deploy stage service and environment custom stage steps, right?
</blockquote></details>

Yes. 


<!-- Sent from Reviewable.io -->

2023-09-25 11:43 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 10 files at r7, 1 of 1 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52850)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-25 12:03 UTC, lovish1999 commented
trigger review

2023-09-25 12:14 UTC, tchaurasiya approved these changes

2023-09-25 12:17 UTC, merged