fix: [PL-41113]: Adding account status check in delegate auth flow
harness/harness-core pull request #52863
Opened 2023-09-13 13:37 UTC by AnupamIO

Adding account status check in delegate auth flow.

Testing:
TBA

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-13 16:26 UTC, raghuAtWings requested changes

2023-09-13 16:26 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +    if (AccountStatus.DELETED.equals(accountStatus)) {
if account is not there in db then accountService.getAccountStatus(accountId); will throw an exception and call will never come to line 120

2023-09-13 16:26 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +  @Inject private AccountService accountService;
with this change lets make sure we delete account related entries in dms db as well, e.g. delegateTokens

2023-09-13 17:58 UTC, AnupamIO commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +    if (AccountStatus.DELETED.equals(accountStatus)) {
yes, right. I think that should be okay because there we will throw AccountNotFound exception with meaningful message:    
```
 throw new AccountNotFoundException(
          "Account is not found for the given id:" + accountId, null, ACCOUNT_DOES_NOT_EXIST, Level.ERROR, USER, null);
    }
```

2023-09-13 17:58 UTC, AnupamIO commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +  @Inject private AccountService accountService;
ack

2023-09-17 16:58 UTC, raghuAtWings requested changes

2023-09-17 16:58 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +        log.error("account {} does not exist", accountId);
make it a debug statement

2023-09-17 16:58 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +      log.error("account {} does not exist", accountId, exception);
same here, make it a debug statement

2023-09-18 07:25 UTC, AnupamIO commented
trigger uts

2023-09-18 22:56 UTC, raghuAtWings approved these changes

2023-09-18 22:56 UTC, raghuAtWings approved these changes

2023-09-20 04:34 UTC, AnupamIO commented
trigger ut8

2023-09-20 04:34 UTC, AnupamIO commented
trigger ut9

2023-09-20 07:02 UTC, AnupamIO commented
trigger uts

2023-09-20 07:15 UTC, AnupamIO commented
trigger uts

2023-09-20 09:43 UTC, AnupamIO commented
trigger uts

2023-09-20 10:23 UTC, AnupamIO commented
trigger uts

2023-09-20 23:09 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +    // If we are reaching here that means, we have successfully decrypted jwt.
why not do this before validating jwt ?

2023-10-05 06:44 UTC, AnupamIO commented
trigger uts

2023-10-05 06:59 UTC, AnupamIO commented on 400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java
> +    // If we are reaching here that means, we have successfully decrypted jwt.
- We delete entities if account is marked as deleted or is not present in db. 

- Let's consider the case that when delegateToken is deleted from account but account entry is not deleted from accounts collection. (We delete account entry only when account is deleted successfully from other collections)

- Let's say if we keep this at the top (before validating jwt) and account is marked as deleted. Then this will trigger account deletion flow every time which would be useless. Hence idea is to keep this at bottom.

2023-10-06 10:50 UTC, AnupamIO commented
trigger uts

2023-10-09 12:48 UTC, deepak-harness approved these changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 3 of 4 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52863)* status: Some of the checks are too old. 6 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-09 14:58 UTC, AnupamIO commented
trigger messagecheck

2023-10-09 18:06 UTC, xingchi-jin commented on 270-verification/src/main/java/io/harness/app/VerificationAuthFilter.java
> +              .authenticateDelegateRequest(accountId, tokenString, delegateId, delegateTokenName, agentMtlsAuthority)
If we are applying the same "reject request from deleted account feature" to both delegate and CV, then I don't see a different from using delegateTokenAuthenticator as a library , versus as a service (api call). Test cases should still cover both services

For the short term, feels to me keeping the old way (as library) and less code change, is better

2023-10-09 18:08 UTC, xingchi-jin commented on 270-verification/src/main/java/io/harness/app/VerificationAuthFilter.java
> +              .authenticateDelegateRequest(accountId, tokenString, delegateId, delegateTokenName, agentMtlsAuthority)
discussed with @praveensugavanam  @sribalij 
cc. @raghuAtWings

2023-10-10 07:01 UTC, raghuAtWings approved these changes

2023-10-31 15:36 UTC, merged