fix: [CDS-78124]: change workflow id and name in case of rollback if tags mismatch
harness/harness-core pull request #52933
Opened 2023-09-14 13:58 UTC by TarunUba1

## Describe your changes
Handling case when in case of rollback we show wrong workflow against the artifact.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-20 06:45 UTC, abosii-harness requested changes
What about the case when PT is executed during the wait for steady state check and customer is using a different workflow? We're still going to show wrong workflow execution id

2023-09-20 06:45 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java
> +    rollbackHandlerConfig.setPreviousRollbackEligibleRelease(lastSuccessfulRelease);
Why these changes are required now?

2023-09-20 06:54 UTC, abhinavsingh1196 requested changes

2023-09-20 06:54 UTC, abhinavsingh1196 commented on 400-rest/src/main/java/software/wings/sm/states/k8s/K8sRollingDeployRollback.java
> +          ((K8sStateExecutionData) context.getStateExecutionData())
nit: use `stateExecutionData` from above instead of `((K8sStateExecutionData) context.getStateExecutionData())`

2023-09-20 06:54 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java
> +    rollbackHandlerConfig.setPreviousRollbackEligibleRelease(lastSuccessfulRelease);
we need to do this change in legacyRollback() as well? this method is for when declarative rollback is ON

2023-09-20 06:54 UTC, abhinavsingh1196 commented on 400-rest/src/main/java/software/wings/service/impl/instance/DeploymentServiceImpl.java
> +      if (k8sDeploymentKey.getReleaseNumber() != null)
nit: braces needed after IF condition

2023-09-20 06:54 UTC, abhinavsingh1196 commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +    }
`software.wings.service.impl.instance.InstanceHandler#getDeploymentSummaryForInstanceCreation` has same logic, that can be reused after appropriate renaming

2023-09-20 07:00 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java
> +    rollbackHandlerConfig.setPreviousRollbackEligibleRelease(lastSuccessfulRelease);
For legacy the changes are already there, this logic was missing here

2023-09-20 07:01 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java
> +    rollbackHandlerConfig.setPreviousRollbackEligibleRelease(lastSuccessfulRelease);
inorder to send back the the release number, we already have this logic in k8s, we were missing this in declarative i think

2023-09-22 12:01 UTC, abhinavsingh1196 submitted a review, later dismissed

2023-09-22 12:13 UTC, TarunUba1 commented
trigger uts

2023-09-22 14:04 UTC, abosii-harness requested changes

2023-09-22 14:04 UTC, abosii-harness commented on 260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployRollbackTaskHandler.java
> +              .releaseNumber(rollbackHandlerConfig.getPreviousRollbackEligibleRelease().getReleaseNumber())
This can be null, right?

2023-09-25 07:22 UTC, TarunUba1 commented
trigger uts

2023-09-25 08:44 UTC, TarunUba1 commented
trigger ut5

2023-09-26 05:26 UTC, abosii-harness requested changes

2023-09-26 05:26 UTC, abosii-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +        && deploymentSummary != deploymentSummaryMap.get(containerMetadata)) {
Why this check is here? Even if deployment summary is the same we still should update existing instances

2023-09-28 11:04 UTC, closed without merging