feat:[SRM-15553]:Implemented Least performance Request Based Composit…
harness/harness-core pull request #52987
Opened 2023-09-18 02:03 UTC by shash-harness

…e SLO

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-18 02:07 UTC, shash-harness commented
trigger uts

2023-09-18 10:58 UTC, shash-harness commented
trigger uts

2023-09-20 05:10 UTC, Varsha-lalwani requested changes

2023-09-20 05:10 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/slospec/WeightedAverageCompositeSLOEvaluator.java
> +          serviceLevelObjectiveV2Service.getScopedIdentifier(serviceLevelObjectivesDetail));
don't use serviceClass, use ScopedInformation.

2023-09-20 05:10 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/slospec/LeastPerformanceCompositeSLOEvaluator.java
> +          weightage * (SLIValue.getRunningCountDifference(sliRecord, prevSLIRecord).sliPercentage()), sloPercentage);
You are taking max of sliPercentage, sliPercentage is good/total. We want max badCount. you need Min here not Max.

2023-09-20 05:10 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImpl.java
> +    double sloPercentage =
There will be changes in getBudgetBurnDown as well

2023-09-20 05:10 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/slospec/CompositeSLOEvaluator.java
>    List<Double> getSLOValuesOfIndividualSLIs(List<Double> weightage, List<Integer> sliValues) {
add Uts after fixing

2023-09-26 23:38 UTC, shash-harness commented
trigger uts

2023-09-27 03:49 UTC, shash-harness commented
trigger uts

2023-09-28 02:05 UTC, shash-harness commented
trigger uts

2023-09-28 05:58 UTC, shash-harness commented
trigger uts

2023-09-28 06:51 UTC, shash-harness commented
trigger ut9

2023-09-28 07:55 UTC, shash-harness commented
trigger messagecheck

2023-10-01 19:40 UTC, shash-harness commented
trigger uts

2023-10-01 19:55 UTC, shash-harness commented
trigger messagecheck

2023-10-02 03:33 UTC, shash-harness commented
trigger ut3

2023-10-03 04:35 UTC, shash-harness commented
trigger uts

2023-10-05 08:40 UTC, closed without merging