feat: [CDS-78461]: API to get list of module boards from Harness Canny Portal
harness/harness-core pull request #53029
Opened 2023-09-18 15:30 UTC by ashinsabu3

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-20 08:20 UTC, ashinsabu3 commented
trigger uts

2023-09-20 09:14 UTC, sourabh-awashti approved these changes
LGTM!!

2023-09-20 09:15 UTC, sourabh-awashti commented
@ashinsabu3 please add the PR description and tests done

2023-09-20 09:59 UTC, ashinsabu3 commented
trigger uts

2023-09-20 14:09 UTC, ashinsabu3 commented
trigger reviews

2023-09-21 06:54 UTC, ashinsabu3 commented
> @ashinsabu3 please add the PR description and tests done

Added this

2023-09-21 07:37 UTC, mankrit-singh approved these changes
looks good

2023-09-21 08:16 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/53029#-NeqnlkwBUMZGfd6lBU6:-NeqnlkwBUMZGfd6lBU7:b-q6snwq) ([raw file](https://github.com/harness/harness-core/blob/fd9815a0f5c0f43731455eb62ba0078aff1f7735/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java#L43)):*
> ```Java
> 
>     } catch (Exception e) {
>       log.error("Exception occurred while fetching boards at getBoards(): {}", e.getMessage(), e);
> ```

we don't need to log e.message() if we are directly logging e.getMessage()


<!-- Sent from Reviewable.io -->

2023-09-21 09:16 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/53029#-NeqnlkwBUMZGfd6lBU6:-Ner0MlC8JnsyJO4QUS4:b-38zaqj) ([raw file](https://github.com/harness/harness-core/blob/fd9815a0f5c0f43731455eb62ba0078aff1f7735/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java#L43)):*
<details><summary><i>Previously, ashinsabu3 (Ashin Sabu) wrote…</i></summary><blockquote>

e.getMessage will only log the exception message, adding the exception object as a second parameter logs the exception as well separately along with its stacktrace, which I found to provide more context when viewing the logs locally(after forcing an exception).
<img width="1694" alt="image" src="https://github.com/harness/harness-core/assets/139749674/35bcd7e7-4577-4fae-a21a-780ab9e7c90c">
The first exception is one where I only log the message, second one has the Exception object present as well

</blockquote></details>

Yes, that means just 
log.error("Exception occurred while fetching boards at getBoards()", e);
is sufficient.


<!-- Sent from Reviewable.io -->

2023-09-21 09:31 UTC, sourabh-awashti approved these changes

2023-09-21 12:10 UTC, ashinsabu3 commented
trigger uts

2023-09-22 06:27 UTC, ashinsabu3 commented
trigger uts

2023-09-22 08:13 UTC, ashinsabu3 commented
trigger ut2, ut5

2023-09-22 08:50 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/53029#-Nevcg022mrD3xXTq6AS:-Nevcg022mrD3xXTq6AT:b-99ctbb) ([raw file](https://github.com/harness/harness-core/blob/3188b92ac35467054f6bf05cc920f2e8d9649ebf/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java#L23)):*
> ```Java
> 
> @Slf4j
> @OwnedBy(HarnessTeam.CDP)
> ```

nit: can be a singleton


<!-- Sent from Reviewable.io -->

2023-09-22 08:50 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyHelper.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/53029#-NevcouJCVY3Ze8ITDcY:-NevcouJCVY3Ze8ITDcZ:buztjvc) ([raw file](https://github.com/harness/harness-core/blob/3188b92ac35467054f6bf05cc920f2e8d9649ebf/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyHelper.java#L32)):*
> ```Java
>   @Inject CannyClient cannyClient;
> 
>   public CannyBoardsResponseDTO getBoards() {
> ```

Ideally, we do not need this class. It should be a part of Canny client itself


<!-- Sent from Reviewable.io -->

2023-09-22 08:50 UTC, yogesh-chauhan requested changes
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53029)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyHelper.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/53029#-NevcuwVA0nrLS84lVkC:-NevcuwVA0nrLS84lVkD:b1esgxl) ([raw file](https://github.com/harness/harness-core/blob/3188b92ac35467054f6bf05cc920f2e8d9649ebf/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyHelper.java#L52)):*
> ```Java
>         // TODO: A support ticket has been raised at Canny to add this feature, this section can be removed once this
>         // is handled as this is the only admin-only board.
>         if (Objects.equals(name, "Test Board - only admins can see")) {
> ```

can we extract this out as a constant


<!-- Sent from Reviewable.io -->

2023-09-22 09:17 UTC, ashinsabu3 commented
^ addressed these , cannyhelpers functionality has been moved to cannyclient

2023-09-22 09:34 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/53029#-NewEOqQBO3Cxz18dHCv:-NewEOqR7tOuLbgUHMZ9:b-5ou2md) ([raw file](https://github.com/harness/harness-core/blob/f067b2877d70c177f58f7171c7a0e68c6abc8b08/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java#L49)):*
> ```Java
>     try (Response response = getCannyBoardsResponse()) {
>       if (!response.isSuccessful()) {
>         String bodyString = (null != response.body()) ? response.body().string() : "null";
> ```

this can be null instead of "null"


<!-- Sent from Reviewable.io -->

2023-09-22 09:35 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/53029#-NewETfH47wihtFOg4up:-NewETfH47wihtFOg4uq:b-2tdqj5) ([raw file](https://github.com/harness/harness-core/blob/f067b2877d70c177f58f7171c7a0e68c6abc8b08/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java#L54)):*
> ```Java
>       }
> 
>       ObjectMapper objectMapper = new ObjectMapper();
> ```

we do not need to create a new ObjectMapper() always. We can create a common object mapper for this client 


<!-- Sent from Reviewable.io -->

2023-09-22 09:40 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java` line 74 at r4](https://reviewable.io/reviews/harness/harness-core/53029#-NewFkcZ97yp33_HKXh1:-NewFkcZ97yp33_HKXh2:b-kt6fe) ([raw file](https://github.com/harness/harness-core/blob/f067b2877d70c177f58f7171c7a0e68c6abc8b08/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java#L74)):*
> ```Java
>       }
> 
>       return CannyBoardsResponseDTO.builder().message("Response Successful").boards(boardsList).build();
> ```

message is not needed here


<!-- Sent from Reviewable.io -->

2023-09-22 09:42 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/53029#-NewG7ekArqw8q4_7ncW:-NewG7ekArqw8q4_7ncX:b-9nosil) ([raw file](https://github.com/harness/harness-core/blob/f067b2877d70c177f58f7171c7a0e68c6abc8b08/120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java#L81)):*
> ```Java
>   public ResponseDTO<CannyBoardsResponseDTO>
>   getBoardsList() {
>     return ResponseDTO.newResponse(cannyClient.getBoards());
> ```

can you check if there is any rate limiting on Canny ? 
We are making a call everytime to Canny and this is going to be propotional to the number of users using Harness. 
We might need to introduce some caching here 


<!-- Sent from Reviewable.io -->

2023-09-22 09:42 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 11 files at r1, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53029)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 09:54 UTC, ashinsabu3 commented
> _[`120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/53029#-NewG7ekArqw8q4_7ncW:-NewG7ekArqw8q4_7ncX:b-9nosil) ([raw file](https://github.com/harness/harness-core/blob/f067b2877d70c177f58f7171c7a0e68c6abc8b08/120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java#L81)):_
> 
> > ```java
> >   public ResponseDTO<CannyBoardsResponseDTO>
> >   getBoardsList() {
> >     return ResponseDTO.newResponse(cannyClient.getBoards());
> > ```
> 
> can you check if there is any rate limiting on Canny ? We are making a call everytime to Canny and this is going to be propotional to the number of users using Harness. We might need to introduce some caching here

the docs don't state anything about a rate limit. this call will be made only when user selects the feature request dropdown within the ticket modal, this most likely will not hit the rate limit even if it exists. I can write a script to test this if needed

2023-09-22 09:55 UTC, ashinsabu3 commented
> _[`120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java` line 74 at r4](https://reviewable.io/reviews/harness/harness-core/53029#-NewFkcZ97yp33_HKXh1:-NewFkcZ97yp33_HKXh2:b-kt6fe) ([raw file](https://github.com/harness/harness-core/blob/f067b2877d70c177f58f7171c7a0e68c6abc8b08/120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java#L74)):_
> 
> > ```java
> >       }
> > 
> >       return CannyBoardsResponseDTO.builder().message("Response Successful").boards(boardsList).build();
> > ```
> 
> message is not needed here

addressed

2023-09-22 10:42 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53029)* status: 11 file(s) to review. 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/53029#-NewTryyAkgOY1_QHh4Q:-NewTryyAkgOY1_QHh4R:b9kgxvn) (no related file):*
we need to write unit tests for this as well

___


<!-- Sent from Reviewable.io -->

2023-09-22 10:44 UTC, ashinsabu3 commented
> _[`120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/53029#-NewG7ekArqw8q4_7ncW:-NewG7ekArqw8q4_7ncX:b-9nosil) ([raw file](https://github.com/harness/harness-core/blob/f067b2877d70c177f58f7171c7a0e68c6abc8b08/120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java#L81)):_
> 
> > ```java
> >   public ResponseDTO<CannyBoardsResponseDTO>
> >   getBoardsList() {
> >     return ResponseDTO.newResponse(cannyClient.getBoards());
> > ```
> 
> can you check if there is any rate limiting on Canny ? We are making a call everytime to Canny and this is going to be propotional to the number of users using Harness. We might need to introduce some caching here

tested this with a script for 20 minutes with 1 call per second, hasn't hit any limit so far, some form of caching or store can be looked into later if we do reach the rate limit anytime in the future

2023-09-22 10:46 UTC, mankrit-singh approved these changes

2023-09-22 10:48 UTC, ashinsabu3 commented
trigger uts, review

2023-09-22 11:20 UTC, mankrit-singh submitted a review, later dismissed

2023-09-22 11:22 UTC, yogesh-chauhan approved these changes

2023-09-22 11:25 UTC, ashinsabu3 commented
trigger uts, review

2023-09-22 12:04 UTC, kapil-harness requested changes

2023-09-22 12:04 UTC, kapil-harness commented on 120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java
> +      return new Response.Builder()
why can't we just normally throw here?

2023-09-22 12:19 UTC, ashinsabu3 commented on 120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java
> +  @Path("/boards")
yes, I was not aware of the spec first process, but since this is already done, I will provide a swagger for the same to FE.

2023-09-22 12:25 UTC, ashinsabu3 commented on 120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java
> +      return new Response.Builder()
That makes more sense than sending a response, I've added this.

2023-09-22 12:25 UTC, ashinsabu3 commented on 120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java
> +  @Inject CannyClient cannyClient;
addressed

2023-09-22 12:26 UTC, ashinsabu3 commented on 120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyClient.java
> +package io.harness.ng.support.dto;
moved the client and configs to a client package

2023-09-22 12:42 UTC, kapil-harness approved these changes

2023-09-22 13:04 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53029)* status: 11 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-22 13:04 UTC, yogesh-chauhan commented
trigger review

2023-09-22 14:14 UTC, merged