[fix]: [CDS-76059]: Log-Key Simplification
harness/harness-core pull request #53032
Opened 2023-09-18 15:57 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-18 16:53 UTC, vtxorxwitty commented
trigger uts

2023-09-20 04:19 UTC, sahilhindwani-harness commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NeknuUO6U0WnCbuM0RM:-NeknuUO6U0WnCbuM0RN:bvkzqkk) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L221)):*
> ```Java
>         && ambiance.getMetadata().getFeatureFlagToValueMapMap().get(PIE_SIMPLIFY_LOG_BASE_KEY)) {
>       logBaseKey =
>           LogStreamingHelper.generateSimplifiedLogBaseKey(StepUtils.generateSimplifiedLogAbstractions(ambiance, null));
> ```

Move the if part to AmbianceUtils. There must be similar function already there.


<!-- Sent from Reviewable.io -->

2023-09-20 04:21 UTC, sahilhindwani-harness commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 216 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoKh--SzvXV31DT4j:-NekoKh--SzvXV31DT4k:b-e2hnre) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L216)):*
> ```Java
> 
>   private String getLogKey(Ambiance ambiance) {
>     String logBaseKey = "";
> ```

Also, create a function in AmbianceUtils that takes in Ambiance and gives logBaseKey. Wrap the whole logic inside that function itself and call that function from here.


<!-- Sent from Reviewable.io -->

2023-09-20 04:21 UTC, sahilhindwani-harness commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoUJcDRAJ4Uveg_rG:-NekoUJcDRAJ4Uveg_rH:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java#L175)):*
> ```Java
> 
>     String baseLogKey = "";
>     if (ambiance.getMetadata() != null && ambiance.getMetadata().getFeatureFlagToValueMapMap() != null
> ```

Same as above


<!-- Sent from Reviewable.io -->

2023-09-20 04:21 UTC, sahilhindwani-harness commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 547 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoX62BoCuDP0gEl51:-NekoX62BoCuDP0gEl52:b-fkd796) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L547)):*
> ```Java
>     String logBaseKey = "";
> 
>     if (ambiance.getMetadata() != null && ambiance.getMetadata().getFeatureFlagToValueMapMap() != null
> ```

Same for all below


<!-- Sent from Reviewable.io -->

2023-09-20 04:22 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 164 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-Nekoivg9pmVNWYARLIw:-Nekoivg9pmVNWYARLIx:bpvg84m) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L164)):*
> ```Java
>     logAbstractions.put("projectId", ambiance.getSetupAbstractionsMap().getOrDefault("projectIdentifier", ""));
>     logAbstractions.put("pipelineId", ambiance.getMetadata().getPipelineIdentifier());
>     logAbstractions.put("runSequence", String.valueOf(ambiance.getMetadata().getRunSequence()));
> ```

Extract this to a common private function and share between above and this.



_Code quote:_
```Java
    logAbstractions.put("accountId", ambiance.getSetupAbstractionsMap().getOrDefault("accountId", ""));
    logAbstractions.put("orgId", ambiance.getSetupAbstractionsMap().getOrDefault("orgIdentifier", ""));
    logAbstractions.put("projectId", ambiance.getSetupAbstractionsMap().getOrDefault("projectIdentifier", ""));
    logAbstractions.put("pipelineId", ambiance.getMetadata().getPipelineIdentifier());
    logAbstractions.put("runSequence", String.valueOf(ambiance.getMetadata().getRunSequence()));
```


<!-- Sent from Reviewable.io -->

2023-09-20 04:23 UTC, sahilhindwani-harness commented
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingHelper.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-Nekotce0OuMWGLzjP6B:-Nekotce0OuMWGLzjP6C:b-yz8eu9) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingHelper.java#L44)):*
> ```Java
>   @Nonnull
>   public String generateLogBaseKey(LinkedHashMap<String, String> logStreamingAbstractions) {
>     if (logStreamingAbstractions.containsKey("isSimplified")
> ```

nit: Move to constants


<!-- Sent from Reviewable.io -->

2023-09-20 04:23 UTC, sahilhindwani-harness commented
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingHelper.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-Nekp0BwA3QdsmCt2tMY:-Nekp0BwA3QdsmCt2tMZ:b-oivzzd) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingHelper.java#L46)):*
> ```Java
>     if (logStreamingAbstractions.containsKey("isSimplified")
>         && logStreamingAbstractions.get("isSimplified").equals("true")) {
>       generateSimplifiedLogBaseKey(logStreamingAbstractions);
> ```

Should'nt this be return generateSimplified...


<!-- Sent from Reviewable.io -->

2023-09-20 04:23 UTC, sahilhindwani-harness requested changes
> Reviewed 11 of 45 files at r1, 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 45 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-20 14:40 UTC, vtxorxwitty commented
trigger uts

2023-09-20 17:03 UTC, vtxorxwitty commented
trigger uts

2023-09-20 17:27 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 46 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 216 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoKh--SzvXV31DT4j:-NencSIY4L5SAV-hcTTK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L216)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Also, create a function in AmbianceUtils that takes in Ambiance and gives logBaseKey. Wrap the whole logic inside that function itself and call that function from here.
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NeknuUO6U0WnCbuM0RM:-NencRqtAg32L7pMRs-N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L221)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Move the if part to AmbianceUtils. There must be similar function already there.
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoUJcDRAJ4Uveg_rG:-NencSxwAEECdVPBH68t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java#L175)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java` line 547 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoX62BoCuDP0gEl51:-NencTQ6BZb8GIBJJ-D_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java#L547)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same for all below
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 164 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-Nekoivg9pmVNWYARLIw:-NencTuW9-YggDnB7zbp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L164)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Extract this to a common private function and share between above and this.
</blockquote></details>

Done.
___
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingHelper.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-Nekp0BwA3QdsmCt2tMY:-NencVcuElDr0RVZc0v6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingHelper.java#L46)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should'nt this be return generateSimplified...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-21 06:53 UTC, sahilhindwani-harness commented
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 216 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoKh--SzvXV31DT4j:-NeqVvI14xnDHjy4Rswg:bwry43v) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L216)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why is this null in here? Can we create one more function without null?


<!-- Sent from Reviewable.io -->

2023-09-21 06:55 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqWN1z152XBYPoHLNF:-NeqWN1z152XBYPoHLNG:b-xszu82) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L81)):*
> ```Java
>   }
> 
>   public static String getLogBaseKey(Ambiance ambiance, String lastGroup) {
> ```

Create one more function without group and that function should call a function with null value as group


<!-- Sent from Reviewable.io -->

2023-09-21 06:56 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 136 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqWXXL4MbYKTTJPViG:-NeqWXXL4MbYKTTJPViH:bymkyln) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L136)):*
> ```Java
>       if (ambiance.getMetadata() != null && ambiance.getMetadata().getFeatureFlagToValueMapMap() != null
>           && ambiance.getMetadata().getFeatureFlagToValueMapMap().get(PIE_SIMPLIFY_LOG_BASE_KEY)) {
>         if (levelValue.equals("spec") || levelValue.equals("execution")) {
> ```

Create a static list of all these expressions and do a contains on them


<!-- Sent from Reviewable.io -->

2023-09-21 06:57 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 124 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqWbQA6R0PL-EX0Tar:-NeqWbQA6R0PL-EX0Tas:byrxly4) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L124)):*
> ```Java
> 
>     if (ambiance.getMetadata() != null && ambiance.getMetadata().getFeatureFlagToValueMapMap() != null
>         && ambiance.getMetadata().getFeatureFlagToValueMapMap().get(PIE_SIMPLIFY_LOG_BASE_KEY)) {
> ```

See AmbianceUtils#shouldUseMatrixFieldName function and we should create a similar function there.



_Code quote:_
```Java
    if (ambiance.getMetadata() != null && ambiance.getMetadata().getFeatureFlagToValueMapMap() != null
        && ambiance.getMetadata().getFeatureFlagToValueMapMap().get(PIE_SIMPLIFY_LOG_BASE_KEY)) {
```


<!-- Sent from Reviewable.io -->

2023-09-21 06:57 UTC, sahilhindwani-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 46 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoUJcDRAJ4Uveg_rG:-NeqVz8PEUrV31O0sWzq:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java#L175)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same as above


<!-- Sent from Reviewable.io -->

2023-09-21 07:48 UTC, hextechpal requested changes
> Reviewed 15 of 45 files at r1, 1 of 10 files at r2, 5 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 34 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-NeqhChr0rKmrsuupnVb:bdrtep) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
> ```Java
>     logAbstractions.put("accountId", ambiance.getSetupAbstractionsMap().getOrDefault("accountId", ""));
>     logAbstractions.put("orgId", ambiance.getSetupAbstractionsMap().getOrDefault("orgIdentifier", ""));
>     logAbstractions.put("projectId", ambiance.getSetupAbstractionsMap().getOrDefault("projectIdentifier", ""));
> ```

Lets remove account org and project from here

/pipeineidentifier/run-sequence/.....

This should be our pattern


<!-- Sent from Reviewable.io -->

2023-09-21 08:43 UTC, archit-harness reviewed
> Reviewed 13 of 45 files at r1, 1 of 10 files at r2, 3 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 30 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-Neqt-b_4XuclK0Hpcet:bhi96e2) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Lets remove account org and project from here

/pipeineidentifier/run-sequence/.....

This should be our pattern
</blockquote></details>

@hextechpal wouldnt it will collide the logBaseKey isn't?


<!-- Sent from Reviewable.io -->

2023-09-21 15:22 UTC, hextechpal requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 30 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-NesKTEg-QxAUjLYEtwb:b-ix06nb) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@hextechpal wouldnt it will collide the logBaseKey isn't?
</blockquote></details>

because identifiers can be duplicated in projects?


<!-- Sent from Reviewable.io -->

2023-09-21 15:25 UTC, hextechpal requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 30 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-NesKfoc5COxyIn8SSkv:b-m0jczf) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

because identifiers can be duplicated in projects?
</blockquote></details>

In that case, we can use some unique like executionUuid as a prefix. Let's not include orgId, project id, etc., that are bound to change this key needs to be idempotent in a way and can be generate anytime.

We save it in database after generation so it doesn't matter as such but still we would like this to be correct


<!-- Sent from Reviewable.io -->

2023-09-22 07:24 UTC, vtxorxwitty commented
trigger uts

2023-09-22 10:11 UTC, vtxorxwitty commented
trigger uts

2023-09-22 10:15 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 36 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 216 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoKh--SzvXV31DT4j:-NewNdvD-S0FWKQrKzVW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L216)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why is this null in here? Can we create one more function without null?
</blockquote></details>

Done.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/53032#-NekoUJcDRAJ4Uveg_rG:-NewNejR6ArOAM6o8OFA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/933ee780db61ff457c4c8db7b86ed2cedea3db0d/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/StageCleanupUtility.java#L175)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqWN1z152XBYPoHLNF:-NewNgCe48wuM1cC3Dei:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L81)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Create one more function without group and that function should call a function with null value as group
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 124 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqWbQA6R0PL-EX0Tar:-NewNguK7_JuSzMTh65n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L124)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

See AmbianceUtils#shouldUseMatrixFieldName function and we should create a similar function there.
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 136 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqWXXL4MbYKTTJPViG:-NewNh_o6ULIxTr4alCN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L136)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Create a static list of all these expressions and do a contains on them
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-NewNiQe2Ggr2-5wYiHG:b-lsyza4) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

In that case, we can use some unique like executionUuid as a prefix. Let's not include orgId, project id, etc., that are bound to change this key needs to be idempotent in a way and can be generate anytime.

We save it in database after generation so it doesn't matter as such but still we would like this to be correct
</blockquote></details>

Addresed. Removed account/org/project Ids from the logic.


<!-- Sent from Reviewable.io -->

2023-09-22 10:37 UTC, vtxorxwitty commented
trigger ut4

2023-09-22 12:43 UTC, vtxorxwitty commented
trigger ut2

2023-09-22 12:44 UTC, vtxorxwitty commented
trigger ut3

2023-09-22 13:36 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-Nex5YWcEZsSDe-Sd77c:b-jr2w4g) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

Addresed. Removed account/org/project Ids from the logic.
</blockquote></details>

We have runSequence in the map so I think we should be good 
This should cause any collision I believe


<!-- Sent from Reviewable.io -->

2023-09-22 13:36 UTC, sahilhindwani-harness approved these changes
> Reviewed 14 of 45 files at r1, 1 of 10 files at r2, 6 of 14 files at r4, 11 of 12 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 34 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 13:42 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 34 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-Nex6oYv5lqWVu3VRZKA:b-a9vc12) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We have runSequence in the map so I think we should be good 
This should cause any collision I believe
</blockquote></details>

Yes identifier collision, @sahilhindwani-harness i dont think even with runsequence it will be handle  same pipelined across projects/orgs.

Also there is one more requirement like customer asking for all its logs - https://harness.slack.com/archives/C03L5J019P0/p1694785477925089

We should revisit if we want to remove accountId etc, and introduce planExecutionId


<!-- Sent from Reviewable.io -->

2023-09-22 14:28 UTC, vtxorxwitty commented
trigger ut2

2023-09-25 04:46 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-Nf9e1bq2Rj-LhbdqhvA:b4i0xag) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Yes identifier collision, @sahilhindwani-harness i dont think even with runsequence it will be handle  same pipelined across projects/orgs.

Also there is one more requirement like customer asking for all its logs - https://harness.slack.com/archives/C03L5J019P0/p1694785477925089

We should revisit if we want to remove accountId etc, and introduce planExecutionId
</blockquote></details>

Yes, across pipelines there can be collision. @vtxorxwitty , could you please setup a quick 15 mins call to close on this? 


<!-- Sent from Reviewable.io -->

2023-09-25 05:19 UTC, hextechpal requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 34 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/53032#-NeqhChr0rKmrsuupnVa:-Nf9lm3P6BshX9NysxmB:bxqaj7m) ([raw file](https://github.com/harness/harness-core/blob/8bab49387db9729b5abf6fa1efa13ed589535765/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L156)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Yes, across pipelines there can be collision. @vtxorxwitty , could you please setup a quick 15 mins call to close on this?
</blockquote></details>

We can use executionUuid?


<!-- Sent from Reviewable.io -->

2023-09-25 10:54 UTC, vtxorxwitty commented
trigger uts

2023-09-26 04:59 UTC, vtxorxwitty commented
trigger uts

2023-09-26 08:43 UTC, vtxorxwitty commented
trigger uts

2023-09-26 08:56 UTC, vtxorxwitty commented
trigger uts

2023-09-26 09:27 UTC, archit-harness requested changes
> Reviewed 3 of 45 files at r1, 4 of 14 files at r4, 7 of 12 files at r5, 8 of 11 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 23 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 100 at r9](https://reviewable.io/reviews/harness/harness-core/53032#-NfFmvDL5OG-exywQfgu:-NfFmvDL5OG-exywQfgv:b-fveq90) ([raw file](https://github.com/harness/harness-core/blob/85dbbc2e648135e7576231a02d3880cb99cb0c45/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L100)):*
> ```Java
>   public static String PIE_SIMPLIFY_LOG_BASE_KEY = "PIE_SIMPLIFY_LOG_BASE_KEY";
> 
>   public static List<String> keysToSkipInLogBaseKey = List.of("spec", "execution");
> ```

are we not skipping "steps"
___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 174 at r9](https://reviewable.io/reviews/harness/harness-core/53032#-NfFnNfo6kKK9yqLaCtQ:-NfFnNfo6kKK9yqLaCtR:b-g3f445) ([raw file](https://github.com/harness/harness-core/blob/85dbbc2e648135e7576231a02d3880cb99cb0c45/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L174)):*
> ```Java
> 
>   @Nonnull
>   public static LinkedHashMap<String, String> generateSimplifiedLogAbstractions(Ambiance ambiance, String lastGroup) {
> ```

why do we need this method -> if above method handles both cases?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/AbstractContainerStep.java` line 161 at r9](https://reviewable.io/reviews/harness/harness-core/53032#-NfFne7tBtz-LIEFzIad:-NfFne7tBtz-LIEFzIae:b243vz9) ([raw file](https://github.com/harness/harness-core/blob/85dbbc2e648135e7576231a02d3880cb99cb0c45/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/AbstractContainerStep.java#L161)):*
> ```Java
> 
>   private String getLogPrefix(Ambiance ambiance) {
>     return LogStreamingStepClientFactory.getLogBaseKey(ambiance, "STEP");
> ```

Why we are not using this proto enum - StepCategory and hardcoding everywhere?


<!-- Sent from Reviewable.io -->

2023-09-26 10:18 UTC, sahilhindwani-harness commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 100 at r9](https://reviewable.io/reviews/harness/harness-core/53032#-NfFmvDL5OG-exywQfgu:-NfFzmkL6NZPkgMvb-Yy:bmkfw21) ([raw file](https://github.com/harness/harness-core/blob/85dbbc2e648135e7576231a02d3880cb99cb0c45/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L100)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

are we not skipping "steps"
</blockquote></details>

@archit-harness , I think we decided to skip only spec and execution for now. In V1, steps will be removed.


<!-- Sent from Reviewable.io -->

2023-09-26 10:32 UTC, vtxorxwitty commented
trigger codebasehash

2023-09-26 10:32 UTC, vtxorxwitty commented
trigger uts

2023-09-26 10:44 UTC, vtxorxwitty commented
trigger uts

2023-09-26 11:01 UTC, archit-harness approved these changes
> Reviewed 10 of 45 files at r1, 1 of 10 files at r2, 1 of 12 files at r5, 1 of 11 files at r8, 9 of 10 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-26 11:32 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 9 of 11 files at r8, 1 of 1 files at r9, 9 of 10 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-26 13:22 UTC, vtxorxwitty commented
trigger ut0

2023-09-26 13:23 UTC, vtxorxwitty commented
trigger ut4

2023-09-26 13:23 UTC, vtxorxwitty commented
trigger ut8

2023-09-26 15:14 UTC, hextechpal submitted a review, later dismissed
> Reviewed 11 of 45 files at r1, 1 of 10 files at r2, 2 of 14 files at r4, 8 of 12 files at r5, 9 of 11 files at r8, 1 of 1 files at r9, 9 of 10 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-09-26 15:48 UTC, vtxorxwitty commented
trigger ut4

2023-09-26 15:55 UTC, vtxorxwitty commented
trigger ut0

2023-09-26 16:04 UTC, vtxorxwitty commented
trigger ut4

2023-09-27 03:57 UTC, vtxorxwitty commented
trigger ut4

2023-09-27 04:00 UTC, vtxorxwitty commented
trigger review

2023-09-27 04:52 UTC, sahilhindwani-harness approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-27 05:17 UTC, vtxorxwitty commented
trigger uts

2023-09-27 05:42 UTC, vtxorxwitty commented
trigger ut4

2023-09-27 05:42 UTC, vtxorxwitty commented
trigger ut3

2023-09-27 05:42 UTC, vtxorxwitty commented
trigger ut2

2023-09-27 05:42 UTC, vtxorxwitty commented
trigger ut1

2023-09-27 05:42 UTC, vtxorxwitty commented
trigger ut0

2023-09-27 06:13 UTC, archit-harness submitted a review, later dismissed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-09-27 06:14 UTC, vtxorxwitty commented
trigger review

2023-09-27 06:15 UTC, vtxorxwitty commented
trigger ut0

2023-09-27 06:16 UTC, vtxorxwitty commented
trigger ut1

2023-09-27 07:25 UTC, vtxorxwitty commented
trigger ut2

2023-09-27 07:27 UTC, vtxorxwitty commented
trigger ut3

2023-09-27 07:28 UTC, vtxorxwitty commented
trigger ut4

2023-09-27 08:26 UTC, vtxorxwitty commented
trigger ut3

2023-09-27 08:50 UTC, vtxorxwitty commented
trigger ut2

2023-09-27 09:28 UTC, vtxorxwitty commented
trigger uts

2023-09-27 10:08 UTC, abhinavmittal-harness approved these changes
> Reviewed 18 of 45 files at r1, 2 of 10 files at r2, 2 of 14 files at r4, 5 of 12 files at r5, 9 of 11 files at r8, 1 of 1 files at r9, 7 of 10 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-27 10:11 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-09-27 10:12 UTC, vtxorxwitty commented
trigger review

2023-09-27 10:14 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53032)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-09-27 10:39 UTC, harshjain12 approved these changes

2023-09-27 10:43 UTC, merged