feat: [IDP-1137]: Helm chart support for idp-service
harness/harness-core pull request #53079
Opened 2023-09-20 08:22 UTC by devesh-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-20 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53079) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53079) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53079) it.</sub>

2023-09-20 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53079) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53079) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53079) it.</sub>

2023-09-21 05:41 UTC, vikyathharekal submitted a review, later dismissed

2023-09-21 12:01 UTC, arya-harness commented
it is missing virtualservice.yaml

2023-09-21 12:35 UTC, harness-jc approved these changes

2023-09-21 12:36 UTC, harness-jc requested changes
please create virtualservice.yaml to support istio installations.

2023-09-21 13:38 UTC, devesh-harness commented on idp-service/build/container/Dockerfile-idp-service-multistage
> +RUN /opt/harness/inject-onprem-apm-bins-into-dockerimage.sh && rm /opt/harness/inject-onprem-apm-bins-into-dockerimage.sh
as discussed we will make these changes when we will do for all services.

2023-09-21 13:38 UTC, devesh-harness commented on idp-service/chart/Chart.yaml
> +version: 0.13.0
as discussed changed it.

2023-09-21 13:38 UTC, devesh-harness commented
> please create virtualservice.yaml to support istio installations.
done please check now.

2023-09-21 14:00 UTC, harness-jc approved these changes

2023-09-21 14:15 UTC, devesh-harness commented
trigger uts

2023-09-21 14:26 UTC, devesh-harness commented
trigger ut8

2023-09-21 14:49 UTC, vikyathharekal approved these changes

2023-09-21 15:13 UTC, arya-harness commented on idp-service/chart/templates/_helpers.tpl
> +Create the name of the s3 image to use
This is not required

2023-09-21 15:13 UTC, arya-harness commented on idp-service/chart/templates/_helpers.tpl
> +{{- define "idp-service.pullSecrets" -}}
this function is not required

2023-09-21 15:20 UTC, arya-harness commented on idp-service/chart/templates/deployment.yaml
> +            {{- include "harnesscommon.dbconnection.redisEnv" (dict "context" .Values.global.database.redis "userVariableName" "EVENTS_FRAMEWORK_REDIS_USERNAME" "passwordVariableName" "EVENTS_FRAMEWO
does idp support redis sentinels?

2023-09-21 15:21 UTC, arya-harness commented on idp-service/chart/templates/ingress.yaml
> +          - path: {{.Values.pathPrefix}}/(v1/backstage-env-variables.*)
remove {{.Values.pathPrefix}}
/(v1/backstage-env-variables.*) is enough

2023-09-21 15:21 UTC, arya-harness commented on idp-service/chart/templates/ingress.yaml
> +          - path: {{.Values.pathPrefix}}/(v1/backstage-env-variables.*)
lets do it for all openapi specs

2023-09-21 15:23 UTC, arya-harness commented on idp-service/chart/templates/virtualservice.yaml
> +      {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
{- if .Values.virtualService.annotations }}
      {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
      
      needs to be changed to
      {- if .Values.virtualService.annotations }}
      {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.virtualService.annotations "context" $) | nindent 4 }}

2023-09-21 15:24 UTC, arya-harness commented on idp-service/chart/values.yaml
> +securityImage:
we can remove unused values.

2023-09-22 04:26 UTC, jyotiraval approved these changes
Placeholder seceret

2023-09-22 05:37 UTC, devesh-harness commented on idp-service/chart/templates/_helpers.tpl
> +Create the name of the s3 image to use
done

2023-09-22 05:37 UTC, devesh-harness commented on idp-service/chart/templates/_helpers.tpl
> +{{- define "idp-service.pullSecrets" -}}
done

2023-09-22 05:37 UTC, devesh-harness commented on idp-service/chart/templates/deployment.yaml
> +      {{- if .Values.global.database.timescaledb.installed }}
done

2023-09-22 05:37 UTC, devesh-harness commented on idp-service/chart/templates/ingress.yaml
> +          - path: {{.Values.pathPrefix}}/(v1/backstage-env-variables.*)
done

2023-09-22 05:37 UTC, devesh-harness commented on idp-service/chart/templates/virtualservice.yaml
> +      {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
done

2023-09-22 05:37 UTC, devesh-harness commented on idp-service/chart/templates/ingress.yaml
> +apiVersion: networking.k8s.io/v1
removed it for now.

2023-09-22 05:50 UTC, devesh-harness commented
trigger uts

2023-09-22 05:56 UTC, arya-harness commented on idp-service/chart/templates/_helpers.tpl
> +{{/*
We can remove securityImage too, IDP does not require this I believe.

2023-09-22 05:57 UTC, arya-harness submitted a review, later dismissed

2023-09-22 10:22 UTC, devesh-harness commented
trigger uts

2023-09-24 17:34 UTC, devesh-harness commented
trigger uts

2023-09-25 04:49 UTC, devesh-harness commented
trigger ut7

2023-09-25 06:45 UTC, devesh-harness commented
trigger ut7

2023-09-25 09:27 UTC, jyotiraval approved these changes

2023-09-25 09:31 UTC, arya-harness approved these changes

2023-09-25 12:23 UTC, harness-jc approved these changes

2023-09-25 12:31 UTC, devesh-harness commented
trigger review

2023-09-25 12:34 UTC, sathish-soundarapandian approved these changes

2023-09-25 12:38 UTC, devesh-harness commented
trigger review

2023-09-25 12:41 UTC, devesh-harness commented
trigger review

2023-09-25 12:43 UTC, merged