feat: [CDS-78190]: Publish adviser event for custom advisers only
harness/harness-core pull request #53080
Opened 2023-09-20 08:50 UTC by Y0709

We have added a new flow for pipeline execution where we dont publish advise events for nodes that only have non custom advisers as we are unnecessarily publishing redis events from pipeline service to pipeline service and increase load on redis. For custom advisers or incase no advisers are present we will still publish advise event and let it go via that flow

Testing done- Executed a pipeline with both nodes having custom as well non custom advisers and checked it is working correctly.

Will be adding unit tests shortly

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-20 08:54 UTC, Y0709 commented
trigger uts

2023-09-20 09:17 UTC, archit-harness requested changes
> Reviewed 6 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53080)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/events/node/advise/NodeAdviseBaseHandler.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NelqBaN1rFbNnVKY0Fv:-NelqBaN1rFbNnVKY0Fw:bha2ch6) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/events/node/advise/NodeAdviseBaseHandler.java#L28)):*
> ```Java
> @Singleton
> public interface NodeAdviseBaseHandler {
>   default AdviserResponse handleEvent(AdviseEvent event) {
> ```

can we rename it to handleAdviseEvent?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NeloSvICfpLKpabQldE:-NeloSvICfpLKpabQldF:b-3y8wln) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java#L45)):*
> ```Java
>   @Inject private OrchestrationEngine engine;
>   @Inject @Named("PipelineExecutorService") ExecutorService executorService;
>   @Inject @Named("publishAdviserEventForCustomAdvisers") private Boolean publishAdviserEventForCustomAdvisers;
> ```

why do we need Boolean and not boolean?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NelsIrK8FPzrl6qbip2:-NelsIrK8FPzrl6qbip3:btl18g3) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java#L78)):*
> ```Java
>   private void handleInCaseOfNoCustomAdviser(NodeExecution nodeExecution, Node planNode, Status fromStatus) {
>     AdviseEvent event =
>         nodeAdviseEventPublisher.createAdviseEvent(nodeExecution, nodeExecution.getFailureInfo(), planNode, fromStatus);
> ```

reason to move above to util, as this method has no relation to event push, but still we are calling this, thus to avoid it, we should move createEvent to some util
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-Nels3GB-wJLuWRM-NHZ:-Nels3GB-wJLuWRM-NH_:b76u4f5) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java#L100)):*
> ```Java
>             SdkResponseEventUtils.getSdkErrorResponse(NodeExecutionEventType.ADVISE, event.getAmbiance(),
>                 event.getNotifyId(), NodeExecutionUtils.constructFailureInfo(ex));
>         executorService.submit(() -> engine.handleSdkResponseEvent(handleEventErrorRequest));
> ```

exception ones i think we should handle in same thread and not submit it
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/NodeAdviseEventPublisher.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NelpOS5Bt5MssXR-T2c:-NelofmC2-17fReUvAx2:b-tlkoym) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/NodeAdviseEventPublisher.java#L24)):*
> ```Java
>   String publishEvent(NodeExecution nodeExecution, FailureInfo failureInfo, Node planNode, Status fromStatus);
> 
>   AdviseEvent createAdviseEvent(NodeExecution nodeExecution, FailureInfo failureInfo, Node planNode, Status fromStatus);
> ```

We should move this method to NodeAdviserUtils



_Code quote:_
```Java
createAdviseEvent
```


<!-- Sent from Reviewable.io -->

2023-09-20 10:34 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/events/node/advise/NodeAdviseBaseHandler.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NelqBaN1rFbNnVKY0Fv:-Nem8yBsDxnKRsc0Wk5Y:b32v57) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/events/node/advise/NodeAdviseBaseHandler.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename it to handleAdviseEvent?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-09-20 10:35 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-Nels3GB-wJLuWRM-NHZ:-Nem9D0p2S9w7uY_pSWD:b32v57) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java#L100)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

exception ones i think we should handle in same thread and not submit it
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-09-20 20:30 UTC, Y0709 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53080)* status: 15 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/events/node/advise/NodeAdviseBaseHandler.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NelqBaN1rFbNnVKY0Fv:-NeoHHMcCoUsKeip961i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/events/node/advise/NodeAdviseBaseHandler.java#L28)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NeloSvICfpLKpabQldE:-NeoHIUC8395uLQQmRpo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need Boolean and not boolean?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NelsIrK8FPzrl6qbip2:-NeoHJCB5XJkZH4K0DsK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java#L78)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

reason to move above to util, as this method has no relation to event push, but still we are calling this, thus to avoid it, we should move createEvent to some util
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-Nels3GB-wJLuWRM-NHZ:-NeoHJmn2XrRzrncEsfe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/NodeAdviseHelper.java#L100)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/NodeAdviseEventPublisher.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/53080#-NelpOS5Bt5MssXR-T2c:-NeoHM6EDfx2S1i_7gQn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d12c3d256a79fdb92b39e08e84fdcba11bef1290/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher/NodeAdviseEventPublisher.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should move this method to NodeAdviserUtils
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-20 20:33 UTC, Y0709 commented
trigger uts

2023-09-21 11:13 UTC, Y0709 commented
trigger uts

2023-09-21 11:46 UTC, sahilhindwani-harness requested changes

2023-09-21 11:46 UTC, sahilhindwani-harness commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/AbstractNodeExecutionStrategy.java
> +      orchestrationEngine.handleSdkResponseEvent(sdkResponseEventProto);
Can we directly call this method rather than calling orchestrationEngine.

2023-09-21 12:06 UTC, Y0709 commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/AbstractNodeExecutionStrategy.java
> +      orchestrationEngine.handleSdkResponseEvent(sdkResponseEventProto);
done

2023-09-21 12:14 UTC, Y0709 commented
trigger uts

2023-09-21 12:53 UTC, archit-harness approved these changes
> Reviewed 1 of 10 files at r1, 8 of 10 files at r2, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53080)* status: 19 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 05:45 UTC, Y0709 commented
trigger uts

2023-09-22 07:01 UTC, Y0709 commented
trigger ut3

2023-09-22 07:06 UTC, Y0709 commented
trigger ut5

2023-09-22 07:14 UTC, archit-harness approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53080)* status: 21 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-22 07:26 UTC, Y0709 commented
trigger ut3, ut8

2023-09-22 07:35 UTC, Y0709 commented
trigger ut3, ut5, ut8

2023-09-22 09:54 UTC, sahilhindwani-harness approved these changes
> Reviewed 10 of 10 files at r1, 8 of 10 files at r2, 4 of 6 files at r3, 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53080)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-09-22 09:55 UTC, Y0709 commented
trigger messagecheck, review

2023-09-22 16:33 UTC, merged