feat: [CDS-78912]: service inputs for remote services
harness/harness-core pull request #53081
Opened 2023-09-20 09:00 UTC by hingerabhinav

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-22 04:19 UTC, yogesh-chauhan requested changes

2023-09-25 12:55 UTC, hingerabhinav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 795 at r2](https://reviewable.io/reviews/harness/harness-core/53081#gh-1332895190:-NfBP-468GitA6XXqS9-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d9add179ba19bc266685209c3510899e7053b9/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L795)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets rename this as discussed
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 842 at r2](https://reviewable.io/reviews/harness/harness-core/53081#gh-1332900304:-NfBP-ty1QmI5udplVFe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50d9add179ba19bc266685209c3510899e7053b9/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L842)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can extract serviceRefs just by doing map.keySet()
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 429 at r2](https://reviewable.io/reviews/harness/harness-core/53081#gh-1332909930:-NfBP1kP6kEV9qJfw1tn:b281h5r) ([raw file](https://github.com/harness/harness-core/blob/50d9add179ba19bc266685209c3510899e7053b9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L429)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

line: 438

this will fail since Sdef would be null for getMetadata method
</blockquote></details>

Done. Moved to using entity's type instead of getting from config 


<!-- Sent from Reviewable.io -->

2023-09-25 13:03 UTC, hingerabhinav commented
trigger uts

2023-09-26 11:21 UTC, hingerabhinav commented on 120-ng-manager/src/main/java/io/harness/ng/core/beans/EntityYamlMetadataInput.java
> +  GitEntityFindInfoDTO gitEntityFindInfoDTO;
no need for DTO, just branch will suffice

2023-09-26 11:22 UTC, hingerabhinav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 823 at r3](https://reviewable.io/reviews/harness/harness-core/53081#-NfG9X4742VSDDQvi-O4:-NfG9X4742VSDDQvi-O5:b-nrnpuj) ([raw file](https://github.com/harness/harness-core/blob/6f0c8530d7de114377d45a52222230ed4fe6b1c6/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L823)):*
> ```Java
>             servicesMetadataWithGitInfo, GitXUtils.parseLoadFromCacheHeaderParam(loadFromCache));
> 
>     List<ServiceV2YamlMetadata> serviceV2YamlMetadataList = new ArrayList<>();
> ```

instead of computing these, move into service layer. for openAPI as well. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 660 at r3](https://reviewable.io/reviews/harness/harness-core/53081#-NfGATGS7tXyTfbqdNa9:-NfGATGS7tXyTfbqdNaA:bui01un) ([raw file](https://github.com/harness/harness-core/blob/6f0c8530d7de114377d45a52222230ed4fe6b1c6/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L660)):*
> ```Java
>           accountIdentifier, orgIdentifier, projectIdentifier, serviceRefs, servicesMetadataWithGitInfo, loadFromCache);
>     } catch (CompletionException ex) {
>       log.error(String.format("Error while getting services: %s", serviceRefs), ex);
> ```

this is currently handling single exception in a thread. with multiple services likely one can fail. handle multiple exceptions here. Check out Scm Facilitator Service. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 685 at r3](https://reviewable.io/reviews/harness/harness-core/53081#-NfGB8Fe9VFOOM657s7R:-NfGB8Fe9VFOOM657s7S:b-507rbx) ([raw file](https://github.com/harness/harness-core/blob/6f0c8530d7de114377d45a52222230ed4fe6b1c6/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L685)):*
> ```Java
>       String projectIdentifier, List<String> serviceRefs, Map<String, GitEntityFindInfoDTO> serviceMetadataInputMap,
>       boolean loadFromCache) {
>     if (isEmpty(serviceRefs)) {
> ```

this can be removedS
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 311 at r3](https://reviewable.io/reviews/harness/harness-core/53081#-NfGCbzJD_bHbgtKz85T:-NfGCbzJD_bHbgtKz85U:b3r2oax) ([raw file](https://github.com/harness/harness-core/blob/6f0c8530d7de114377d45a52222230ed4fe6b1c6/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L311)):*
> ```Java
>   public ServiceEntity getWithYaml(
>       @NonNull ServiceEntity savedEntity, boolean loadFromCache, boolean loadFromFallbackBranch) {
>     if (savedEntity.getStoreType() == null || StoreType.INLINE.equals(savedEntity.getStoreType())) {
> ```

remove redundant code 
___
*[`950-log-client/src/main/java/io/harness/logstreaming/ServiceGitXThreadConfiguration.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/53081#-NfGD4pTCte049E3geg9:-NfGD4pTCte049E3gegA:bcpqczg) ([raw file](https://github.com/harness/harness-core/blob/6f0c8530d7de114377d45a52222230ed4fe6b1c6/950-log-client/src/main/java/io/harness/logstreaming/ServiceGitXThreadConfiguration.java#L25)):*
> ```Java
> @FieldDefaults(makeFinal = false)
> public class ServiceGitXThreadConfiguration {
>   ThreadPoolConfig threadPoolConfig;
> ```

check out the scaling thread pool if it maxes out. Read up. 


<!-- Sent from Reviewable.io -->

2023-09-27 07:10 UTC, hingerabhinav commented
trigger uts

2023-09-27 09:59 UTC, hingerabhinav commented
trigger uts

2023-09-28 11:47 UTC, hingerabhinav commented
trigger uts

2023-09-29 07:56 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 17 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 715 at r6](https://reviewable.io/reviews/harness/harness-core/53081#-NfUw05x7Gzbo1C52FPO:-NfUw05x7Gzbo1C52FPP:b-9vi8n8) ([raw file](https://github.com/harness/harness-core/blob/471bac0b676db8f6f51d0ff67eb416f014082e35/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L715)):*
> ```Java
>         CompletableFuture<ServiceEntity> future = CompletableFuture.supplyAsync(() -> {
>           // set principal
>           SecurityContextBuilder.setContext(new ServicePrincipal(AuthorizationServiceHeader.NG_MANAGER.getServiceId()));
> ```

this same security context logic is repeated here, we should modularize it


<!-- Sent from Reviewable.io -->

2023-09-29 08:20 UTC, yogesh-chauhan requested changes

2023-09-29 08:20 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +        if (!Objects.equals(se.getType(), deploymentType)) {
why not just do deploymentType != se.getType() for simplicity :)

2023-09-29 08:22 UTC, hingerabhinav commented on 120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java
> +  @JsonProperty("serviceGitXThreadConfig") @ConfigSecret private ServiceGitXThreadConfiguration serviceGitXThreadConfig;
@yogesh-chauhan we don't want 1 queues in service inputs request to affect another component like env, infra. That's why we created a new pool for each entity.

2023-09-29 08:25 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 465 at r6](https://reviewable.io/reviews/harness/harness-core/53081#-NfV1TgBEkC-vFhnfHBI:-NfV1TgC4cWlarvma0Bd:bpu7hfp) ([raw file](https://github.com/harness/harness-core/blob/471bac0b676db8f6f51d0ff67eb416f014082e35/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L465)):*
> ```Java
>                                       .buildScopedIdentifier();
>         filterBuilder.serviceName(scopedIdentifier);
>         if (se.getType() == null) {
> ```

I am not 100% sure about when we added this field in the service entity and whether ALL service v2 services have this field set or not ? 
You might want to check in DB or just log an error for now 


<!-- Sent from Reviewable.io -->

2023-09-29 08:37 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 674 at r6](https://reviewable.io/reviews/harness/harness-core/53081#-NfV4N1RDSe7lWF0hO9_:-NfV4N1RDSe7lWF0hO9a:bvtnsw) ([raw file](https://github.com/harness/harness-core/blob/471bac0b676db8f6f51d0ff67eb416f014082e35/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L674)):*
> ```Java
>       String errorMessage = cause != null ? cause.getMessage() : ex.getMessage();
>       // Wrap the exception in InternalServerErrorException
>       throw new InternalServerErrorException(
> ```

according to documentation for IntervalServerException

"// This exception can be used whenever there's an error in communication between internal services, Error code 500 will  
// be thrown with this exception."


<!-- Sent from Reviewable.io -->

2023-09-29 08:41 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 13 files at r1, 1 of 9 files at r2, 2 of 9 files at r3, 8 of 11 files at r4, 1 of 2 files at r5, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 17 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-03 10:01 UTC, hingerabhinav commented
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 674 at r6](https://reviewable.io/reviews/harness/harness-core/53081#-NfV4N1RDSe7lWF0hO9_:-NfV4N1RDSe7lWF0hO9a:bvtnsw) ([raw file](https://github.com/harness/harness-core/blob/471bac0b676db8f6f51d0ff67eb416f014082e35/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L674)):_
> 
> > ```java
> >       String errorMessage = cause != null ? cause.getMessage() : ex.getMessage();
> >       // Wrap the exception in InternalServerErrorException
> >       throw new InternalServerErrorException(
> > ```
> 
> according to documentation for IntervalServerException
> 
> "// This exception can be used whenever there's an error in communication between internal services, Error code 500 will // be thrown with this exception."

@yogesh-chauhan Yes. This should be a rare scenario. Technically this is an error between scm service and ng-manager. I will see if I can make it better afterwards.

2023-10-03 10:20 UTC, hingerabhinav commented
trigger uts

2023-10-03 12:04 UTC, hingerabhinav commented
trigger uts

2023-10-03 13:58 UTC, hingerabhinav commented
trigger uts

2023-10-03 19:28 UTC, hingerabhinav commented
trigger review

2023-10-03 19:29 UTC, hingerabhinav commented
trigger uts

2023-10-04 02:33 UTC, hingerabhinav commented
trigger ut0, ut7

2023-10-04 03:29 UTC, hingerabhinav commented
trigger uts

2023-10-04 04:25 UTC, hingerabhinav commented
trigger uts

2023-10-04 05:45 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 466 at r12](https://reviewable.io/reviews/harness/harness-core/53081#-NftCuLN8_fvafnXdRxS:-NftCuLN8_fvafnXdRxT:bthi2fc) ([raw file](https://github.com/harness/harness-core/blob/0ea9da918487511c3c9e41ccb8d8ec4ed2f768d1/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L466)):*
> ```Java
>         if (se.getType() == null) {
>           log.error(format(
>               "ServiceDefinition should be present in service [%s]. Please add it and try again", scopedIdentifier));
> ```

should we not return here ?


<!-- Sent from Reviewable.io -->

2023-10-04 05:52 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 289 at r12](https://reviewable.io/reviews/harness/harness-core/53081#-NftESy8-S8ycoZQ8e2F:-NftESy94sYXSYmSpQFb:b-dl6gtv) ([raw file](https://github.com/harness/harness-core/blob/0ea9da918487511c3c9e41ccb8d8ec4ed2f768d1/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L289)):*
> ```Java
>       boolean loadFromFallbackBranch, boolean getMetadataOnly) {
>     // set principal
>     setNgManagerSourcePrincipal();
> ```

this does not look like the correct way to set source principal, we should set principals just before they are needed, preferably wrapped in an auto closeable


<!-- Sent from Reviewable.io -->

2023-10-04 05:53 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 6 files at r7, 1 of 1 files at r8, 3 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 19 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-05 11:14 UTC, hingerabhinav commented
trigger uts

2023-10-05 11:20 UTC, hingerabhinav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 466 at r12](https://reviewable.io/reviews/harness/harness-core/53081#-NftCuLN8_fvafnXdRxS:-NfzZ3rjAIaS6Zxg57lk:b-vh0nm5) ([raw file](https://github.com/harness/harness-core/blob/0ea9da918487511c3c9e41ccb8d8ec4ed2f768d1/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L466)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not return here ?
</blockquote></details>

Done. I've tested the execution for a service without type as well.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 289 at r12](https://reviewable.io/reviews/harness/harness-core/53081#-NftESy8-S8ycoZQ8e2F:-NfzZDuT0jfCG0L0XARQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ea9da918487511c3c9e41ccb8d8ec4ed2f768d1/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L289)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this does not look like the correct way to set source principal, we should set principals just before they are needed, preferably wrapped in an auto closeable
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-05 11:32 UTC, hingerabhinav commented
trigger uts

2023-10-05 11:42 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 4 of 4 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-05 12:04 UTC, hingerabhinav commented
trigger ut9

2023-10-05 13:10 UTC, hingerabhinav commented
trigger ut5, ut6, ut7, ut9

2023-10-05 21:52 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 464 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0otUw8Pc9TflKxBXr:-Ng0otUw8Pc9TflKxBXs:by44v49) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L464)):*
> ```Java
>                                       .buildScopedIdentifier();
>         filterBuilder.serviceName(scopedIdentifier);
>         if (se.getType() == null) {
> ```

here it seems like backward incompatible change. Earlier we were throwing an exception, now we are just logging and returning.


<!-- Sent from Reviewable.io -->

2023-10-05 21:54 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/security/NgManagerSourcePrincipalGuard.java` line 18 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pHI1BtUfpp_Ym50k:-Ng0pHI1BtUfpp_Ym50l:bqnw687) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/security/NgManagerSourcePrincipalGuard.java#L18)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDC)
> public class NgManagerSourcePrincipalGuard implements AutoCloseable {
> ```

Please can you explain what this guard is doing, its bit confusing right now. 

From what I understand from name of the guard, it should essentially set ng manager service as principal when guard is created and at time of closure, it should revert the principal to original value.


<!-- Sent from Reviewable.io -->

2023-10-05 21:55 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 115 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pYD54SZvostFib1q:-Ng0pYD54SZvostFib1r:b-6680bt) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L115)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, List<String> serviceIdentifiers);
> 
>   List<ServiceEntity> getServicesWithYaml(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

when we have separate method as "metadata", then shouldn't we simply call this method as "getServices"?


<!-- Sent from Reviewable.io -->

2023-10-05 21:56 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 657 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pr5r-xtdSdXi6-aw:-Ng0pr5r-xtdSdXi6-ax:b-2ivnt2) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L657)):*
> ```Java
>       // internal method always wraps the CompletionException, so we will have a cause
>       log.error(String.format("Error while getting services: %s", serviceRefs), ex);
>       Throwables.throwIfUnchecked(ex.getCause());
> ```

what does this method do?
Why aren't we trying to wrap the exception caused into a more meaningful exception with proper error message and then throw it back?


<!-- Sent from Reviewable.io -->

2023-10-05 21:58 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 689 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qBmT-6CvENRMUt1m:-Ng0qBmU72owiy1a-tFw:b31v87u) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L689)):*
> ```Java
>     for (int i = 0; i < remoteServiceEntities.size(); i += REMOTE_SERVICE_BATCH_SIZE) {
>       int endIndex = Math.min(i + REMOTE_SERVICE_BATCH_SIZE, remoteServiceEntities.size());
>       List<ServiceEntity> batch = remoteServiceEntities.subList(i, endIndex);
> ```

it would be better/cleaner to create a simple private method that just gets you a batch instead of doing maths operations right here.


<!-- Sent from Reviewable.io -->

2023-10-05 22:01 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 305 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qqC10VzbJUjq9iMp:-Ng0qqC10VzbJUjq9iMq:b-agbrgg) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L305)):*
> ```Java
>   public ServiceEntity getRemoteServiceWithYaml(
>       @NonNull ServiceEntity savedEntity, boolean loadFromCache, boolean loadFromFallbackBranch) {
>     try (NgManagerSourcePrincipalGuard ignore = new NgManagerSourcePrincipalGuard()) {
> ```

is something similar done in pipeline fetch or template fetch call as well? Please can you point reference to the file once if thats the case.


<!-- Sent from Reviewable.io -->

2023-10-05 22:02 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 659 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0r5FY4dkI6z2sx8Xk:-Ng0r5FY4dkI6z2sx8Xl:bim5r0i) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L659)):*
> ```Java
>       Throwables.throwIfUnchecked(ex.getCause());
>     } catch (Exception ex) {
>       log.error(String.format("Error while getting services: %s", serviceRefs), ex);
> ```

it would be better to put error message something like : "Unexpected error occured while...", just bringing in a difference b/w the blanket exception block and other expected exception blocks.


<!-- Sent from Reviewable.io -->

2023-10-05 22:02 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 320 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0rGSdCQ2SuzRS3DER:-Ng0rGSdCQ2SuzRS3DES:bjquptk) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L320)):*
> ```Java
>       throw e;
>     } catch (Exception e) {
>       log.error(String.format("Error while retrieving service YAML: [%s]", savedEntity.getIdentifier()), e);
> ```

same as before


<!-- Sent from Reviewable.io -->

2023-10-05 22:03 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 322 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0rO2y4Jg13MGg1brx:-Ng0rO2y4Jg13MGg1bry:birs5at) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L322)):*
> ```Java
>       log.error(String.format("Error while retrieving service YAML: [%s]", savedEntity.getIdentifier()), e);
>       throw new InternalServerErrorException(
>           String.format("Error while retrieving service YAML: [%s]: %s", savedEntity.getIdentifier(), e.getMessage()));
> ```

Shouldn't we improve the error message here? What if there's an NPE, then it will be shown as appended message on UI?


<!-- Sent from Reviewable.io -->

2023-10-06 04:38 UTC, hingerabhinav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 464 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0otUw8Pc9TflKxBXr:-Ng2CgTk8v0JB5BvAcdm:bee7sjq) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L464)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

here it seems like backward incompatible change. Earlier we were throwing an exception, now we are just logging and returning.
</blockquote></details>

I've discussed with @yogesh-chauhan. We are not sure if all services would have their type set in the entity. I've tested it out and we're handling it execution time.  
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/security/NgManagerSourcePrincipalGuard.java` line 18 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pHI1BtUfpp_Ym50k:-Ng2DAVc94aZFXQUBRsV:b8p83xi) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/security/NgManagerSourcePrincipalGuard.java#L18)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Please can you explain what this guard is doing, its bit confusing right now. 

From what I understand from name of the guard, it should essentially set ng manager service as principal when guard is created and at time of closure, it should revert the principal to original value.
</blockquote></details>

Yes this principal is setting the Source principal IF it is not present. On close, It is setting the source principal back to null to not mess with downstream logic. We're doing the absolute minimum that scm-service requires. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java` line 115 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pYD54SZvostFib1q:-Ng2Dr1X2kLHOBkEECcT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java#L115)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

when we have separate method as "metadata", then shouldn't we simply call this method as "getServices"?
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 657 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pr5r-xtdSdXi6-aw:-Ng2E86C2xV-yJ_Ctji_:b-x3cz8l) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L657)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what does this method do?
Why aren't we trying to wrap the exception caused into a more meaningful exception with proper error message and then throw it back?
</blockquote></details>

The internal method will always give me a meaningful exception and an unchecked exception. I am just propagating the exception out of the worker thread. I think we can improve this iteratively. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 659 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0r5FY4dkI6z2sx8Xk:-Ng2Es-Y7dj2YwZmFiZ2:bs7wumx) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L659)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it would be better to put error message something like : "Unexpected error occured while...", just bringing in a difference b/w the blanket exception block and other expected exception blocks.
</blockquote></details>

Done. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 689 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qBmT-6CvENRMUt1m:-Ng2Ezs60190eLSDzMyz:b-s6odvl) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L689)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it would be better/cleaner to create a simple private method that just gets you a batch instead of doing maths operations right here.
</blockquote></details>

I disagree. The calculation for end index is straightforward and is just 2 lines. Making it into a separate method to get the batch reduces clarity of what is happening. We can keep it as it is.  
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 305 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qqC10VzbJUjq9iMp:-Ng2FMu95IXX0FiC677j:b-1cbcpg) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L305)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

is something similar done in pipeline fetch or template fetch call as well? Please can you point reference to the file once if thats the case.
</blockquote></details>

No I didn't find any. Since there are no worker threads for pipeline/template, the source principal would always be there. That's why we did this in the safest way possible. We can revisit it later. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 320 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0rGSdCQ2SuzRS3DER:-Ng2G4YE3RChM4Cx3Esz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L320)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as before
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 322 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0rO2y4Jg13MGg1brx:-Ng2GJqJCoSsPFjigDy6:buahuw8) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L322)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Shouldn't we improve the error message here? What if there's an NPE, then it will be shown as appended message on UI?
</blockquote></details>

Done. Since we're logging the error anyway. We can not show it to the end user. 
Majority of errors would be caught by the block above. 


<!-- Sent from Reviewable.io -->

2023-10-06 04:43 UTC, hingerabhinav commented
trigger uts

2023-10-06 05:17 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/security/NgManagerSourcePrincipalGuard.java` line 18 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pHI1BtUfpp_Ym50k:-Ng2PV2RE4tcdI099SIc:b-i9x4fr) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/security/NgManagerSourcePrincipalGuard.java#L18)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Yes this principal is setting the Source principal IF it is not present. On close, It is setting the source principal back to null to not mess with downstream logic. We're doing the absolute minimum that scm-service requires.
</blockquote></details>

This looks a bit custom logic to me. My basic expectations from guard would be to preserve current value, set new value for the context and then revert to older value once guard closes. Here, this happens only on certain condition which sort of goes against the name of the guard. Approving for now.


<!-- Sent from Reviewable.io -->

2023-10-06 05:18 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 657 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0pr5r-xtdSdXi6-aw:-Ng2PqSz0yAH1EriW4O3:b22d0o7) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L657)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

The internal method will always give me a meaningful exception and an unchecked exception. I am just propagating the exception out of the worker thread. I think we can improve this iteratively.
</blockquote></details>

These are small little things, we shouldn't create backlog out of newly written code itself. Lets be sure about it how its going to be handled and do it the right way itself. We can discuss offline on call and close this one.


<!-- Sent from Reviewable.io -->

2023-10-06 05:19 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 689 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qBmT-6CvENRMUt1m:-Ng2Q45XEHYuxBDQTAbS:b-9iy647) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L689)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

I disagree. The calculation for end index is straightforward and is just 2 lines. Making it into a separate method to get the batch reduces clarity of what is happening. We can keep it as it is.
</blockquote></details>

Exactly thats the reason why it should be moved to a separate method to make it a blackbox. No one cares how batch is calculated in context of this method, thus it should just be carved out for better code readability. 
For now, as you feel otherwise, approving it.


<!-- Sent from Reviewable.io -->

2023-10-06 05:20 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 305 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qqC10VzbJUjq9iMp:-Ng2QLZR3exeZbS30fwu:b-gbf7vs) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L305)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

No I didn't find any. Since there are no worker threads for pipeline/template, the source principal would always be there. That's why we did this in the safest way possible. We can revisit it later.
</blockquote></details>

From what I know, there's no need to set any context separately for any worker threads that originate from original thread. The context automatically gets passed onto it. We only need to do such things if there's poller in picture that create separate threads to do stuff.
Is the code failing without it?


<!-- Sent from Reviewable.io -->

2023-10-06 12:05 UTC, hingerabhinav commented
trigger uts

2023-10-06 12:23 UTC, hingerabhinav commented
trigger uts

2023-10-06 12:37 UTC, mohitg0795 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-06 12:49 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 1031 at r17](https://reviewable.io/reviews/harness/harness-core/53081#-Ng419h61okvlFFVzBeW:-Ng419h61okvlFFVzBeX:b-3kuizq) ([raw file](https://github.com/harness/harness-core/blob/2b4ab753d55b5d19e7c072f3c9cae672cc204ca2/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L1031)):*
> ```Java
>     bind(ExecutorService.class)
>         .annotatedWith(Names.named("service-gitx-executor"))
>         .toInstance(new ManagedExecutorService(serviceGitXThreadPool()));
> ```

does `serviceGitXThreadPool()` still need to be a guice provider i.e annotated with @Provides ? 


<!-- Sent from Reviewable.io -->

2023-10-06 12:52 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 5 files at r15, 10 of 12 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-06 13:17 UTC, hingerabhinav commented
trigger uts

2023-10-09 05:36 UTC, hingerabhinav commented
trigger ut7

2023-10-09 05:50 UTC, hingerabhinav reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 689 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qBmT-6CvENRMUt1m:-NgHz1SO9rNdyTXBLf58:bs7wumx) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L689)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Exactly thats the reason why it should be moved to a separate method to make it a blackbox. No one cares how batch is calculated in context of this method, thus it should just be carved out for better code readability. 
For now, as you feel otherwise, approving it.
</blockquote></details>

Done. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 305 at r14](https://reviewable.io/reviews/harness/harness-core/53081#-Ng0qqC10VzbJUjq9iMp:-NgHypvT8OwS3OhFdkZM:b-ecxdju) ([raw file](https://github.com/harness/harness-core/blob/0032cb3fe36eaee87e48cef83d85d0a616416dc7/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L305)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

From what I know, there's no need to set any context separately for any worker threads that originate from original thread. The context automatically gets passed onto it. We only need to do such things if there's poller in picture that create separate threads to do stuff.
Is the code failing without it?
</blockquote></details>

Right. We're now using the managed executor service which clones the context for worker threads. Done. 


<!-- Sent from Reviewable.io -->

2023-10-09 06:49 UTC, mohitg0795 approved these changes

2023-10-09 07:04 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53081)* status: 20 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-10-09 07:06 UTC, hingerabhinav commented
trigger review

2023-10-09 07:14 UTC, merged