fix: [CDS-79519]: Rollback step logs for elastigroup
harness/harness-core pull request #53158
Opened 2023-09-21 12:58 UTC by sarthakkasat

## Describe your changes
Add a delete command unit for elasti group basic and canary rollback deployment when setup is unsuccessful

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-22 06:37 UTC, yogesh-chauhan commented
@sarthakkasat , lets put more details in the description. 

- what is the current behaviour of logs in rollback ?
- why is it so and in what condition logs are not visible ?
- what are we doing to fix this ?

2023-09-22 09:08 UTC, yogesh-chauhan requested changes

2023-09-22 09:08 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
> +      taskHelper.deleteElastigroups(
Lets try to get rid of the previous method
```cleanupNewElastigroups()```
We can do in a separate PR but lets do it with ticket itself

2023-09-22 09:08 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupDeployTaskHelper.java
> +            logCallback.saveExecutionLog(format("Failed to delete Elastgroup: %s", newElastigroupId), ERROR, FAILURE);
passing commandExecutionStatus as SUCCESS will close the log stream here
WE should pass the status as RUNNING or not pass here

2023-09-22 09:08 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupDeployTaskHelper.java
> +            logCallback.saveExecutionLog(
passing commandExecutionStatus as SUCCESS will close the log stream here
WE should pass the status as RUNNING or not pass here

2023-09-22 12:05 UTC, sarthakkasat commented on 125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/rollback/ElastigroupRollbackStepHelper.java
> +  private static final List<String> BASIC_AND_CANARY_ROLLBACK_SETUP_EXECUTION_UNITS =
Done

2023-09-22 12:05 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
> +      taskHelper.deleteElastigroups(
Done

2023-09-22 12:05 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupDeployTaskHelper.java
> +            logCallback.saveExecutionLog(format("Failed to delete Elastgroup: %s", newElastigroupId), ERROR, FAILURE);
Done

2023-09-22 12:05 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupDeployTaskHelper.java
> +            logCallback.saveExecutionLog(
Done

2023-09-22 12:26 UTC, sourabh-awashti approved these changes

2023-09-22 12:40 UTC, sourabh-awashti approved these changes

2023-09-23 15:57 UTC, yogesh-chauhan commented
Lets update UTs also




<!-- Sent from Reviewable.io -->

2023-09-23 16:19 UTC, yogesh-chauhan requested changes

2023-09-23 16:19 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java
> +  public void close(CommandExecutionStatus commandExecutionStatus) {
Lets put a comment that this method is to explicitly close the stream without a message

2023-09-23 16:19 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupDeployTaskHelper.java
> +        logCallback.saveExecutionLog("Successfully deleted all Elastigroups", INFO);
instead of all, we should say, "newly created elastigroups"

2023-09-23 16:19 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
> +      deleteLogCallback.close(CommandExecutionStatus.SUCCESS);
this might be failure as well. I think we need to check the above 2 method calls to decide whether SUCCESS of failure
- taskHelper.deleteElastigroup
- taskHelper.cleanupNewElastigroups

2023-09-23 16:19 UTC, yogesh-chauhan requested changes

2023-09-23 16:19 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
>      }
same as above

2023-09-23 16:19 UTC, yogesh-chauhan commented on 970-api-services-beans/src/main/java/io/harness/logging/LogCallback.java
>    default void dispatchLogs() {}
nit: new line for readability

2023-09-25 10:59 UTC, sarthakkasat commented on 970-api-services-beans/src/main/java/io/harness/logging/LogCallback.java
>    default void dispatchLogs() {}
Done

2023-09-25 11:00 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
>      }
Done

2023-09-25 11:00 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
> +      deleteLogCallback.close(CommandExecutionStatus.SUCCESS);
Done

2023-09-25 12:02 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53158)* status: 6 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/53158#-Nf1kdX_6ZAQvFkySTvY:-NfBCPsCEHavkCNNytT0:b-896fix) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets update UTs also
</blockquote></details>

Done.

___
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/53158#gh-1335037576:-NfBCTKg8UCbtDgrzh9p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5d45b516bca76f9ce06edb54f09d69fa5ff048c/930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java#L84)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets put a comment that this method is to explicitly close the stream without a message
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupDeployTaskHelper.java` line 210 at r3](https://reviewable.io/reviews/harness/harness-core/53158#gh-1335038768:-NfBCupz2A78GLAaU4jg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5d45b516bca76f9ce06edb54f09d69fa5ff048c/930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupDeployTaskHelper.java#L210)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

instead of all, we should say, "newly created elastigroups"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-26 06:36 UTC, sarthakkasat commented
/rebase

2023-09-26 11:00 UTC, sourabh-awashti approved these changes

2023-09-26 11:24 UTC, yogesh-chauhan requested changes

2023-09-26 11:24 UTC, yogesh-chauhan commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
> +        getLogStreamingTaskClient().closeStream(DELETE_NEW_ELASTI_GROUP);
shouldn't we call 
```java
logCallback.close(CommandExecutionStatus.SUCCESS);
```

2023-09-26 11:45 UTC, sarthakkasat commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTask.java
> +        getLogStreamingTaskClient().closeStream(DELETE_NEW_ELASTI_GROUP);
Done

2023-09-27 05:00 UTC, yogesh-chauhan commented
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 105 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfK-PVY2KyTWxrTPAWq:-NfK-PVZB4GZ50opcu6Q:blnbcad) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L105)):*
> ```Java
>     elastigroupRollbackTask.run(parameters);
>     verify(logStreamingTaskClient, times(1)).closeStream(DELETE_NEW_ELASTI_GROUP);
>   }
> ```

are there test cases for when lets say `taskHelper.deleteElastigroup` fails ?


<!-- Sent from Reviewable.io -->

2023-09-27 05:00 UTC, yogesh-chauhan requested changes
> Reviewed 2 of 5 files at r2, 1 of 4 files at r4, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53158)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 49 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfJzyIY7YFdWy7nghpR:-NfJzyIZ9sNLvQ3vqHZ7:b-bluwmi) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L49)):*
> ```Java
>   @InjectMocks
>   private ElastigroupRollbackTask elastigroupRollbackTask = new ElastigroupRollbackTask(
>       DelegateTaskPackage.builder().data(TaskData.builder().build()).build(), logStreamingTaskClient, null, null);
> ```

new line for readability
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 52 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfJzz_u4739AsqlidX8:-NfJzz_u4739AsqlidX9:b4yr823) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L52)):*
> ```Java
>   @Before
>   public void setup() {
>     MockitoAnnotations.initMocks(this);
> ```

initMock is deprecated. We should use openMocks()
You can check usages of `MockitoAnnotations.openMocks(this)` in our codebase
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfK-BMWBxwSn4BKWziq:-NfK-BMWBxwSn4BKWzir:b-d0wxhj) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L53)):*
> ```Java
>   public void setup() {
>     MockitoAnnotations.initMocks(this);
>   }
> ```

new line


<!-- Sent from Reviewable.io -->

2023-09-27 06:48 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53158)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 49 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfJzyIY7YFdWy7nghpR:-NfKOCcRDfDeLiguU8Ac:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L49)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

new line for readability
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 52 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfJzz_u4739AsqlidX8:-NfKOCtO5X8ebns98jB9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L52)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

initMock is deprecated. We should use openMocks()
You can check usages of `MockitoAnnotations.openMocks(this)` in our codebase
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 53 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfK-BMWBxwSn4BKWziq:-NfKODEFBRw9bZh3771b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L53)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java` line 105 at r8](https://reviewable.io/reviews/harness/harness-core/53158#-NfK-PVY2KyTWxrTPAWq:-NfKOE_V0qrJOFLECK5f:blt06to) ([raw file](https://github.com/harness/harness-core/blob/95fa53cad5293edaf58b49ed2ca7dd93661794a7/930-delegate-tasks/src/test/java/io/harness/delegate/task/elastigroup/ElastigroupRollbackTaskTest.java#L105)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are there test cases for when lets say `taskHelper.deleteElastigroup` fails ?
</blockquote></details>

Added a test case for that scenario


<!-- Sent from Reviewable.io -->

2023-09-28 05:57 UTC, sarthakkasat commented
trigger uts

2023-09-28 07:20 UTC, yogesh-chauhan approved these changes

2023-09-28 07:20 UTC, sarthakkasat commented
trigger uts

2023-09-28 07:21 UTC, sourabh-awashti approved these changes

2023-09-28 07:21 UTC, sourabh-awashti commented
trigger review

2023-09-28 08:05 UTC, merged