feat: [PL-41303]: Added DTOs and configs for Google OIDC
harness/harness-core pull request #53181
Opened 2023-09-21 19:43 UTC by tiwaritejas

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-26 00:32 UTC, Raghav-Murali requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53181)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpconnector/GcpOidcConfig.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/53181#-NfDpW3x3_Z2-5spsR_5:-NfDpW3yEGwwSEdwJQsZ:b69w4t) ([raw file](https://github.com/harness/harness-core/blob/fe4d5646c16d002c72cf54944f8bb7f81f4cf2ea/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpconnector/GcpOidcConfig.java#L16)):*
> ```Java
> @Value
> @Builder
> @TypeAlias("io.harness.connector.entities.embedded.gcpconnector.GcpServiceAccountKey")
> ```

The typeAlias should end with the Class name which is `GcpOidcConfig` in this case.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/gcpmappers/GcpDTOToEntity.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/53181#-NfDp_k6CZ3U7BpMK5Gh:-NfDp_k6CZ3U7BpMK5Gi:b-95ipyg) ([raw file](https://github.com/harness/harness-core/blob/fe4d5646c16d002c72cf54944f8bb7f81f4cf2ea/440-connector-nextgen/src/main/java/io/harness/connector/mappers/gcpmappers/GcpDTOToEntity.java#L14)):*
> ```Java
> import io.harness.connector.entities.embedded.gcpconnector.GcpServiceAccountKey;
> import io.harness.connector.mappers.ConnectorDTOToEntityMapper;
> import io.harness.delegate.beans.connector.gcpconnector.*;
> ```

Fix the * import here.
___
*[`930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/53181#-NfDqbMz-JzbNP5WiEeU:-NfDqbMz-JzbNP5WiEeV:bkfqzp8) ([raw file](https://github.com/harness/harness-core/blob/fe4d5646c16d002c72cf54944f8bb7f81f4cf2ea/930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java#L183)):*
> ```Java
>       return connectorDetailsBuilder.encryptedDataDetails(encryptedDataDetails).build();
>     } else if (credential.getGcpCredentialType() == GcpCredentialType.INHERIT_FROM_DELEGATE
>         || credential.getGcpCredentialType() == GcpCredentialType.OIDC_AUTHENTICATION) {
> ```

Could you kindly check which all services are using ConnectorUtils.java ? Ideally we should be doing what is being done for Manual Credentials, we should fetch the credential details from Ng-Manager if this is being invoked from other services.


<!-- Sent from Reviewable.io -->

2023-09-26 11:50 UTC, tiwaritejas commented
trigger uts

2023-09-26 12:14 UTC, tiwaritejas commented
trigger uts

2023-09-26 18:05 UTC, tiwaritejas reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53181)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpconnector/GcpOidcConfig.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/53181#-NfDpW3x3_Z2-5spsR_5:-NfHeCCw4iNFcFPk3uEh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fe4d5646c16d002c72cf54944f8bb7f81f4cf2ea/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpconnector/GcpOidcConfig.java#L16)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

The typeAlias should end with the Class name which is `GcpOidcConfig` in this case.
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/gcpmappers/GcpDTOToEntity.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/53181#-NfDp_k6CZ3U7BpMK5Gh:-NfHeCvf5mLEaaEBgJno:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fe4d5646c16d002c72cf54944f8bb7f81f4cf2ea/440-connector-nextgen/src/main/java/io/harness/connector/mappers/gcpmappers/GcpDTOToEntity.java#L14)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Fix the * import here.
</blockquote></details>

Done.
___
*[`930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/53181#-NfDqbMz-JzbNP5WiEeU:-NfHeDUwBL5RsiG_Xa-S:b-te3j4s) ([raw file](https://github.com/harness/harness-core/blob/fe4d5646c16d002c72cf54944f8bb7f81f4cf2ea/930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java#L183)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Could you kindly check which all services are using ConnectorUtils.java ? Ideally we should be doing what is being done for Manual Credentials, we should fetch the credential details from Ng-Manager if this is being invoked from other services.
</blockquote></details>

Unlike the manual config, the OIDC config does not have any encrypted fields. Hence, the "secretManagerClientService.getEncryptionDetails()" call is not needed for it.


<!-- Sent from Reviewable.io -->

2023-09-27 04:12 UTC, tiwaritejas commented
trigger uts

2023-09-27 17:55 UTC, tiwaritejas commented
trigger uts

2023-09-27 18:25 UTC, tiwaritejas commented
trigger uts

2023-09-29 00:02 UTC, Raghav-Murali commented on 260-delegate/src/test/resources/kryo-registrations.txt
> +20001001:io.harness.delegate.beans.connector.gcpconnector.GcpOidcDetailsDTO
Was this added here due to some test case failures ? When we add token exchange capability in delegate we would need this.

2023-09-29 00:04 UTC, Raghav-Murali commented on 400-rest/src/test/resources/manager-kryo-registrations.txt
> +20001001:io.harness.delegate.beans.connector.gcpconnector.GcpOidcDetailsDTO
Same comment as the one for Kryo-registrations.txt

2023-09-29 05:32 UTC, tiwaritejas commented
trigger uts

2023-09-29 06:28 UTC, tiwaritejas commented on 260-delegate/src/test/resources/kryo-registrations.txt
> +20001001:io.harness.delegate.beans.connector.gcpconnector.GcpOidcDetailsDTO
As discussed, we will keep the kryo registrations since it will be used when we token exchange capability in delegates.

2023-09-29 06:29 UTC, tiwaritejas commented
trigger messagecheck

2023-09-29 06:41 UTC, sahilhindwani-harness approved these changes
> Reviewed 4 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53181)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-29 06:41 UTC, archit-harness approved these changes
> Reviewed 5 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53181)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-29 07:49 UTC, Raghav-Murali approved these changes

2023-09-29 11:05 UTC, harshjain12 approved these changes

2023-09-29 11:09 UTC, yogesh-chauhan approved these changes

2023-09-29 12:18 UTC, merged