fix: [CDS-77050]: changing read permission of kubeconfigfile for group and other for helm
harness/harness-core pull request #53196
Opened 2023-09-22 07:12 UTC by TarunUba1

## Describe your changes
missed these changes as while testing helm cases they were already had permission revoked in both qa and local as was using FF.
## Testing

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-22 12:05 UTC, abhinavsingh1196 requested changes

2023-09-22 12:05 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/containerdeployment/ContainerDeploymentDelegateBaseHelper.java
> +      log.error("Error updating file permissions", ExceptionMessageSanitizer.sanitizeException(e));
Can make this log.warn. Not being able to change the permissions of kubeconfig will not cause failures

2023-09-22 12:05 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/containerdeployment/ContainerDeploymentDelegateBaseHelper.java
> +  public void modifyConfigFileReadableProperties(String configFilePath) {
why are we duplicating this method again?
`io.harness.k8s.KubernetesContainerServiceImpl#modifyConfigFileReadableProperties`

2023-09-22 13:58 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/containerdeployment/ContainerDeploymentDelegateBaseHelper.java
> +  public void modifyConfigFileReadableProperties(String configFilePath) {
this one is for helm and doesnt need the logic to add on config at end of working dir thats why created new one

2023-09-22 14:53 UTC, abhinavsingh1196 requested changes

2023-09-22 14:53 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +  public void modifyConfigFileReadableProperties(String path, boolean isFile) {
instead of this boolean, let's make two separate methods with appropriate names


modifyKubeConfigReadableProperties(String kubeconfigPath) {
  modifyFileReadableProperties(Path.of(kubeconfigPath, KUBECONFIG_FILENAME));
}


modifyFileReadableProperties(String filePath) {
...
}

2023-09-25 07:22 UTC, TarunUba1 commented
trigger uts

2023-09-25 09:39 UTC, abosii-harness approved these changes

2023-09-25 09:46 UTC, abhinavsingh1196 approved these changes

2023-09-25 09:47 UTC, TarunUba1 commented
trigger review

2023-09-25 09:52 UTC, merged