feat:[SRM-15650]: Improved the efficiency for filtering on basis of e…
harness/harness-core pull request #53227
Opened 2023-09-22 15:55 UTC by shash-harness

…nvironment.

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-22 15:55 UTC, shash-harness commented
trigger uts

2023-09-22 16:12 UTC, shash-harness commented
trigger ut2

2023-09-22 16:29 UTC, shash-harness commented
trigger ut8

2023-09-23 06:31 UTC, karansaraswat19 requested changes

2023-09-23 06:31 UTC, karansaraswat19 commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
> +        .filter(slo -> slo.getType().equals(ServiceLevelObjectiveType.SIMPLE))
already filtered Simple SLOs on line 1466

2023-09-23 06:31 UTC, karansaraswat19 commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
> +  private List<AbstractServiceLevelObjective> getListAfterEnvFilter(
method can have better name and I feel map approach would have been better

2023-09-23 08:57 UTC, shash-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
> +  private List<AbstractServiceLevelObjective> getListAfterEnvFilter(
Will update it.

2023-09-23 08:57 UTC, shash-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
> +        .filter(slo -> slo.getType().equals(ServiceLevelObjectiveType.SIMPLE))
That is only for monitoredServiceIdentifiers, will have to do it again , or seperate the filtering part out as I did previously.

2023-09-23 17:55 UTC, shash-harness commented
trigger uts

2023-09-25 06:42 UTC, shash-harness commented
trigger uts

2023-09-25 06:57 UTC, shash-harness commented
trigger uts

2023-09-25 07:50 UTC, shash-harness commented
trigger uts

2023-09-25 08:31 UTC, shash-harness commented
trigger uts

2023-09-25 12:10 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
> +    Set<String> scopedMonitoredServices =
scopedMonitoredServiceIdentifiers*

2023-09-25 12:11 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java
> +    Map<String, String> monitoredServiceIdentifierToEnvRef =
Form a Map of scopedMonitoredServiceIdentifier and EnvironmentRef and then filter otherwise it will still fail if slos are from different projects

2023-09-25 13:50 UTC, shash-harness commented
trigger uts

2023-09-26 03:43 UTC, shash-harness commented
trigger uts

2023-09-26 03:47 UTC, Varsha-lalwani approved these changes

2023-09-26 03:58 UTC, shash-harness commented
trigger ut8

2023-09-26 04:38 UTC, merged