feat: [CDS-79715]: Added producer for async filter creation
harness/harness-core pull request #53232
Opened 2023-09-22 18:48 UTC by utkarshchoubey-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-27 05:50 UTC, utkarshchoubey-harness commented
trigger uts

2023-09-27 05:58 UTC, sahilhindwani-harness commented
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKCs7n3Ua4YGHj7pjg:-NfKCs7n3Ua4YGHj7pjh:b4ovep0) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L218)):*
> ```Java
>   public static final int POLLING_EVENTS_STREAM_BATCH_SIZE = 50;
>   public static final int TRIGGER_EXECUTION_EVENTS_STREAM_BATCH_SIZE = 50;
>   public static final int FILTER_CREATION_EVENTS_STREAM_BATCH_SIZE = 50;
> ```

Lets reduce the batch size to 20 as the updates won't be that frequent.


<!-- Sent from Reviewable.io -->

2023-09-27 05:59 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 909 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKD2IH9TZFGcpCXwgz:-NfKD2IH9TZFGcpCXwh-:b-7gymz) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L909)):*
> ```Java
>       Environment environment, Injector injector, PipelineServiceConfiguration appConfig) {
>     environment.lifecycle().manage(injector.getInstance(PMSEventConsumerService.class));
>     environment.lifecycle().manage(injector.getInstance(PMSFilterCreationConsumerService.class));
> ```

Why is this required?
We can directly add the consumer in queueController. 


<!-- Sent from Reviewable.io -->

2023-09-27 06:00 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDDXy5S6GrijeprPj:-NfKDDXy5S6GrijeprPk:b5as8rk) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java#L38)):*
> ```Java
> @Singleton
> @OwnedBy(PIPELINE)
> public class AsyncFilterCreationConsumer extends RedisTraceConsumer {
> ```

please extend PmsAbstractRedisConsumer.


<!-- Sent from Reviewable.io -->

2023-09-27 06:00 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/PMSFilterCreationConsumerService.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDIo97sJdbI80tjoD:-NfKDIoA6aipWF865yEW:b-skoyq9) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/PMSFilterCreationConsumerService.java#L26)):*
> ```Java
> @Slf4j
> @OwnedBy(PIPELINE)
> public class PMSFilterCreationConsumerService implements Managed {
> ```

This should not be required. See NodeResumeConsumer as to how we can use queueController for this.


<!-- Sent from Reviewable.io -->

2023-09-27 06:00 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDP-S8_ybkVSohsCJ:-NfKDP-S8_ybkVSohsCK:bayepom) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L83)):*
> ```Java
> @Singleton
> public class PipelineOutboxEventHandler implements OutboxEventHandler {
>   private static final String ACCOUNT_ID = "accountId";
> ```

nit: Can we fetch these constants from somewhere?


<!-- Sent from Reviewable.io -->

2023-09-27 06:01 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDYobEr9QCjV2wEmc:-NfKDYobEr9QCjV2wEmd:b-euz52e) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L169)):*
> ```Java
>     }
>     pipelineActionObserverSubject.fireInform(PipelineActionObserver::onUpdate, event);
>     Integer newYamlHash = getYamlHash(event.getNewPipeline().getYaml());
> ```

why to reconstruct the hash, why not take it from PipelineEntity?


<!-- Sent from Reviewable.io -->

2023-09-27 06:01 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 203 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDet6CfNTNmWgPgTq:-NfKDet6CfNTNmWgPgTr:b-3dvtot) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L203)):*
> ```Java
>         // usages after the entity has been created
>         PipelineEntity entityWithUpdatedInfo = pipelineEntity;
>         // If PIE_ASYNC_VALIDATION is ON, then we do filter creation async
> ```

nit: is OFF


<!-- Sent from Reviewable.io -->

2023-09-27 06:29 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKCs7n3Ua4YGHj7pjg:-NfKHop27tCLbKYv6ftS:b-cqv5v3) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L218)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Lets reduce the batch size to 20 as the updates won't be that frequent.
</blockquote></details>

i think it should be 10 for initial, and we should not pick not events until current ones are done
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfKI0UC0XmYWerC0oHz:bg7fclw) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
> ```proto
> 
> message AsyncFilterCreatorEvent {
>   string pipelineId = 1;
> ```

is it uuid or pipeline identifier?
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 909 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKD2IH9TZFGcpCXwgz:-NfKJcBN0kQVxT_Rwb5j:b32v57) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L909)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Why is this required?
We can directly add the consumer in queueController.
</blockquote></details>

+1
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKK-LV-u9Xa9zj9QoP:-NfKK-LV-u9Xa9zj9QoQ:b-cigba4) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java#L108)):*
> ```Java
>         success.set(false);
>       }
>     });
> ```

wait for all messages to complete from executor service
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamListener.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKJsz_7_uSi5PP-TRb:-NfKJsz_7_uSi5PP-TRc:bswbplf) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamListener.java#L48)):*
> ```Java
> 
>   @Override
>   public boolean handleMessage(Message message) {
> ```

we should submit tasks to some executor service and then wait for all filter creation to get completed


<!-- Sent from Reviewable.io -->

2023-09-27 11:17 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfLLdYOCN7l2YNfocIh:bh6gedm) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is it uuid or pipeline identifier?
</blockquote></details>

its pipeline identifier
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 909 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKD2IH9TZFGcpCXwgz:-NfLLhrB9oaKai7CzCrf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L909)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-29 06:28 UTC, utkarshchoubey-harness commented
/rebase

2023-09-29 06:33 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKCs7n3Ua4YGHj7pjg:-NfUct5a7M0Qu8q1636_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L218)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think it should be 10 for initial, and we should not pick not events until current ones are done
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfUctzxD9Uzo24r6-Bd:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

its pipeline identifier
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDYobEr9QCjV2wEmc:-NfUcy-U8I7pKiO4d4q3:b5qiont) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L169)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why to reconstruct the hash, why not take it from PipelineEntity?
</blockquote></details>

Done.
This hash is not updated for some reason, therefore calculated it again.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDDXy5S6GrijeprPj:-NfUd9aY3hAZbvL2Y737:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java#L38)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

please extend PmsAbstractRedisConsumer.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKK-LV-u9Xa9zj9QoP:-NfUd9OBELQEDxAeloPP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationConsumer.java#L108)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

wait for all messages to complete from executor service
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamListener.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKJsz_7_uSi5PP-TRb:-NfUdAJ398PIeiQTcFXs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamListener.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should submit tasks to some executor service and then wait for all filter creation to get completed
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/PMSFilterCreationConsumerService.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDIo97sJdbI80tjoD:-NfUdB1XALY22Qjlp0UK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/event/filter/PMSFilterCreationConsumerService.java#L26)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This should not be required. See NodeResumeConsumer as to how we can use queueController for this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-29 06:58 UTC, utkarshchoubey-harness commented
trigger uts

2023-09-29 06:58 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfUir_V3bMEGnuqxAOs:b-pqffxm) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think It should be uuid


<!-- Sent from Reviewable.io -->

2023-09-29 06:59 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUj1eJ-dPMVPnVwfZe:-NfUj1eJ-dPMVPnVwfZf:b-u257hv) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L57)):*
> ```Java
>       log.info("Start processing async filter creation via dispatcher for pipelineId: {}", pipelineId);
>       Optional<PipelineEntity> pipelineEntity =
>           pmsPipelineService.getPipeline(accountId, orgId, projectId, pipelineId, false, false, true, false);
> ```

We can pass just the uuid of pipeline entity in request and fetch using that. AccountId, orgId, projectId won't be required then


<!-- Sent from Reviewable.io -->

2023-09-29 07:00 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 75 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUjCu53vlBwTtEFicm:-NfUjCu53vlBwTtEFicn:b-6bygyh) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L75)):*
> ```Java
>             log.error(
>                 String.format("Async Filter creation failed for Pipeline %s in account - %s, org - %s, project - %s",
>                     pipelineId, accountId, orgId, projectId));
> ```

Please log the exception too


<!-- Sent from Reviewable.io -->

2023-09-29 07:03 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 236 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUjlm-0DrV4Oi-gizC:-NfUjlm-0DrV4Oi-gizD:bw24fnl) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L236)):*
> ```Java
>     String accountId;
>     String orgId;
>     String projectId;
> ```

if we just add pipeline uuid, then I think all this information can be removed. What do you think?



_Code quote:_
```Java
    String accountId;
    String orgId;
    String projectId;
```


<!-- Sent from Reviewable.io -->

2023-09-29 07:03 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDYobEr9QCjV2wEmc:-NfUjxKkB-7YxM5UILQL:brqxn7j) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L169)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
This hash is not updated for some reason, therefore calculated it again.
</blockquote></details>

Can we check why it is not updated?


<!-- Sent from Reviewable.io -->

2023-09-29 07:04 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 236 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUjlm-0DrV4Oi-gizC:-NfUk9Yo-v31lLGSO0gj:b-yu8kbw) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L236)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

if we just add pipeline uuid, then I think all this information can be removed. What do you think?
</blockquote></details>

or maybe we can keep them for debugging purpose.


<!-- Sent from Reviewable.io -->

2023-09-29 07:04 UTC, sahilhindwani-harness requested changes
> Reviewed 2 of 11 files at r1, 3 of 6 files at r4, 4 of 11 files at r5, 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-29 07:32 UTC, archit-harness requested changes
> Reviewed 1 of 11 files at r1, 3 of 6 files at r4, 2 of 11 files at r5, 3 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 13 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 171 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUlrPN5GfX_s1wIJA1:-NfUlrPN5GfX_s1wIJA2:b-b845g1) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L171)):*
> ```Java
>   public static final int TRIGGER_EXECUTION_EVENTS_STREAM_MAX_TOPIC_SIZE = 10000;
> 
>   public static final int ASYNC_FILTER_CREATION_EVENTS_STREAM_MAX_TOPIC_SIZE = 10000;
> ```

why this big of topic size is needed? lets start with small -> say 1k
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfUmKlw6Pd39bBnCSTo:bc6srnh) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think It should be uuid
</blockquote></details>

+1 make it pipelineUuid easier to read from code, if needed add a comment
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUprtM4i2c6VwstANY:-NfUprtN5nYe1vaiZ9Ni:bis4kny) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L53)):*
> ```Java
>   @Override
>   public void run() {
>     try (AutoLogContext ignore = new AutoLogContext(
> ```

here auto log context should have messageId as well and yamlHash
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUj1eJ-dPMVPnVwfZe:-NfUmr0A7zvqhQ1GDAh2:b32v57) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L57)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We can pass just the uuid of pipeline entity in request and fetch using that. AccountId, orgId, projectId won't be required then
</blockquote></details>

+1
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 66 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUq3yI9bE6HTN3dzmJ:-NfUq3yI9bE6HTN3dzmK:bkq6bmp) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L66)):*
> ```Java
>             updatedPipelineEntity =
>                 pmsPipelineServiceHelper.updatePipelineInfo(pipelineEntity.get(), HarnessYamlVersion.V0);
>             PipelineEntity updatedResult = pmsPipelineServiceHelper.updatePipelineFilters(updatedPipelineEntity);
> ```

here we should update pipeline filters only if yamlHash again matches with given input as another thread can update same filters
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUoM09BUhVZ5iDZEJ9:-NfUoM09BUhVZ5iDZEJA:bb6xyek) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L80)):*
> ```Java
>   @Inject
>   public AsyncFilterCreationStreamConsumer(@Named(ASYNC_FILTER_CREATION) Consumer eventConsumer,
>       QueueController queueController, @Named(CORE_EXECUTOR_NAME) ExecutorService executorService,
> ```

we should not use sdk  executor service as this work should not be shared.
i think we should use this -> @Named("PipelineExecutorService")
just check its max threads in all envs, if less we can increase
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 94 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUot8_BjhynPwVqGyf:-NfUot8_BjhynPwVqGyg:b3nh7sr) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L94)):*
> ```Java
> 
>   @Override
>   public void shutDown() {}
> ```

this is not implemented why?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 106 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUnTV84tz9C5rAVskH:-NfUnTV9ASbzGwmCXu9c:b-gz1esl) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L106)):*
> ```Java
>       do {
>         while (getMaintenanceFlag()) {
>           sleep(ofSeconds(1));
> ```

why sleep for 1 second -> use constant and sleep for 10 seconds
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 109 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUnXui-DI5xaHxP3qN:-NfUnXui-DI5xaHxP3qO:b-9bc75u) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L109)):*
> ```Java
>         }
>         if (queueController.isNotPrimary()) {
>           log.info(this.getClass().getSimpleName()
> ```

lets convert to debug
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 171 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUpje8Ck2G7pQ8SJjf:-NfUpje8Ck2G7pQ8SJjg:bxytu4l) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L171)):*
> ```Java
>             } catch (ExecutionException e) {
>               throw new RuntimeException(e);
>             } catch (TimeoutException e) {
> ```

you can convert this to Interrupted | ExecutionException | ..
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 227 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUnva826nfz4OgFv9Z:-NfUnva975Vg_rC2V-6g:b-s074ov) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L227)):*
> ```Java
>   static class ReadResult {
>     Set<PipelineDetails> filterCreationEvents;
>     String[] tobeAcked;
> ```

why not make messageId part of pipelineDetails?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 237 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUnqkDEs_YMAHxqW35:-NfUnqkDEs_YMAHxqW36:b- [...]

2023-09-29 09:57 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 13 file(s) to review. 2 change requests. 20. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java` line 171 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUlrPN5GfX_s1wIJA1:-NfVLqkS2m7dW9a5ovut:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkConstants.java#L171)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this big of topic size is needed? lets start with small -> say 1k
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfVLrXM2gxW-AIpgOWo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1 make it pipelineUuid easier to read from code, if needed add a comment
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 53 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUprtM4i2c6VwstANY:-NfVLsJ0-zCIbbNHiAaM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

here auto log context should have messageId as well and yamlHash
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUj1eJ-dPMVPnVwfZe:-NfVLsrC5GbVK8SPrJyf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L57)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 66 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUq3yI9bE6HTN3dzmJ:-NfVMbvT5KiX6JpONJ20:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L66)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

here we should update pipeline filters only if yamlHash again matches with given input as another thread can update same filters
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 75 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUjCu53vlBwTtEFicm:-NfVMcX9DzPJgFKwmq74:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L75)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please log the exception too
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUoM09BUhVZ5iDZEJ9:-NfVMdmIEswiY_8VvB7I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not use sdk  executor service as this work should not be shared.
i think we should use this -> @Named("PipelineExecutorService")
just check its max threads in all envs, if less we can increase
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 94 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUot8_BjhynPwVqGyf:-NfVMemK4faEJgRtrTTw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L94)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is not implemented why?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 106 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUnTV84tz9C5rAVskH:-NfVMfdl562JDDgH2BB3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L106)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why sleep for 1 second -> use constant and sleep for 10 seconds
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 109 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUnXui-DI5xaHxP3qN:-NfVMgMe8LkqEFgWiInK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L109)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets convert to debug
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 171 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUpje8Ck2G7pQ8SJjf:-NfVMgv849JJvTA4o6VC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L171)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you can convert this to Interrupted | ExecutionException | ..
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 227 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUnva826nfz4OgFv9Z:-NfVMhdK1v0GnxgKmDu5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L227)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why not make messageId part of pipelineDetails?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` [...]

2023-09-29 10:16 UTC, archit-harness requested changes
> Reviewed 4 of 14 files at r6, 9 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfVPnNI5svGtwmdzxTP:b5ywmyh) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why pipelineId and uuid are 2 separate fields?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 66 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUq3yI9bE6HTN3dzmJ:-NfVPxkM8Je8WHeRiQRX:bud9zvj) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L66)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we should make this part of update query -> findAndModify, the above condition will not handle it
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 88 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQ8U8DPJgwoetujlU:-NfVQ8U8DPJgwoetujlV:b-j6zuoy) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L88)):*
> ```Java
>             }
>             try {
>               eventConsumer.acknowledge(messageId);
> ```

we are ack messages in parent call, why do we need it here?



_Code quote:_
```Java
 eventConsumer.acknowledge(messageId
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUoM09BUhVZ5iDZEJ9:-NfVQHw9DAeW9dvzEbHw:b-ypr7nt) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L80)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What is the max number of threads for this in all envs?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 73 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQOfV-bfXSBFH9Hwy:-NfVQOfV-bfXSBFH9Hwz:b41epkt) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L73)):*
> ```Java
>   private static final String ORG_ID = "orgId";
>   private static final String PROJECT_ID = "projectId";
>   private static final Integer SLEEP_TIME_FOR_MAINTAINCE = 10;
> ```

spelling mistake
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDYobEr9QCjV2wEmc:-NfVQ_7W76OT96EXe18s:byoa7m0) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L169)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

which case it was not updating?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 180 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQdOU81HxIIc2p-zy:-NfVQdOU81HxIIc2p-zz:bqpryj6) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L180)):*
> ```Java
>   }
> 
>   Integer getYamlHash(String yaml) {
> ```

is this method needed here?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 197 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQgAc2Uewhw6l2USU:-NfVQgAc2Uewhw6l2USV:b-2pfjt5) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L197)):*
> ```Java
>   @Wither @Setter @NonFinal String connectorRef;
>   @Wither @Setter @NonFinal String repoURL;
>   @Wither @Setter @NonFinal Integer yamlHash;
> ```

why is this required?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 54 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQl1s4wOwMaiLltjY:-NfVQl1s4wOwMaiLltjZ:b56mgvz) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L54)):*
> ```Java
>   public PipelineEntity updateFieldsInDBEntry(
>       PipelineEntity entityFromDB, PipelineEntity fieldsToUpdate, long timeOfUpdate) {
>     return entityFromDB.withYaml(fieldsToUpdate.getYaml())
> ```

can we convert this to ToBuilder.set fields rather than using with



_Code quote:_
```Java
entityFromDB.withYaml
```


<!-- Sent from Reviewable.io -->

2023-09-29 12:08 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfVpYDhAxW9Q9Xzmczl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why pipelineId and uuid are 2 separate fields?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 66 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUq3yI9bE6HTN3dzmJ:-NfVpZc76PmLUZaDGBS3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L66)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should make this part of update query -> findAndModify, the above condition will not handle it
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 88 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQ8U8DPJgwoetujlU:-NfVp_Rs51do5b470nUp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L88)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we are ack messages in parent call, why do we need it here?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUoM09BUhVZ5iDZEJ9:-NfVpc9E3e_9xakXlRaS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

What is the max number of threads for this in all envs?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 73 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQOfV-bfXSBFH9Hwy:-NfVpaEQ6G2-2M0A0p2j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

spelling mistake
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDYobEr9QCjV2wEmc:-NfVpeDY7xUW346bpoAY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L169)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

which case it was not updating?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 180 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQdOU81HxIIc2p-zy:-NfVpekhAXfEuaoiT0Il:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L180)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is this method needed here?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 197 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQgAc2Uewhw6l2USU:-NfVpfWH2_wtAiFbzmKR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this required?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 54 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQl1s4wOwMaiLltjY:-NfVpg2J4U3GVjLI1O5D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we convert this to ToBuilder.set fields rather than using with
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-29 12:17 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfVrjoR1bYVvQyjVQaC:b-w2f3c4) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why pipeline identifier is required if we have uuid?


<!-- Sent from Reviewable.io -->

2023-09-29 12:32 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-NfVuK_r--nM_9kITJit:bwpuuhf) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why pipeline identifier is required if we have uuid?
</blockquote></details>

we have just sent it, as you mentioned it might be helpful while debugging, we anyway are not using it
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUj1eJ-dPMVPnVwfZe:-NfVuZrN5cGt9UCVELFr:bf8guz5) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L57)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

as mentioned in other comment keeping it, it may be required for debugging
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUoM09BUhVZ5iDZEJ9:-NfVujmd0PccFgb9OGPE:b45h) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L80)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>





_Code snippet:_
```Java
Quality Assurance -
Default value
PIPELINE_EXECUTION_POOL_CORE_SIZE: 5
Overriden in
For QA config primary golden -
PIPELINE_EXECUTION_POOL_CORE_SIZE: 1
For QA-free config primary golden -
PIPELINE_EXECUTION_POOL_CORE_SIZE: 1
Master -
PIPELINE_EXECUTION_POOL_CORE_SIZE ( this value not found ) -> might use default values provided in code
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKDYobEr9QCjV2wEmc:-NfVuxJ2En7tsWHeFlOs:b-7i8g9i) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L169)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

added in the updateOutboxEvent, now its getting update
___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 180 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQdOU81HxIIc2p-zy:-NfVv1kI74RPXVQm4-Ok:b-63wk1d) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L180)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no needed
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 197 at r8](https://reviewable.io/reviews/harness/harness-core/53232#-NfVQgAc2Uewhw6l2USU:-NfVv2xWBt1-q_m2TGF6:b-6jn253) ([raw file](https://github.com/harness/harness-core/blob/670c8c5206ddf871a765dba9b40cd3364c246a9d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L197)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

after using toBuilder its not required


<!-- Sent from Reviewable.io -->

2023-09-29 12:34 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUj1eJ-dPMVPnVwfZe:-NfVvgckD4PIDSFvYq6L:ba5odxh) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L57)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

as mentioned in other comment keeping it, it may be required for debugging
</blockquote></details>

pipelineIdentifier is also used in autologcontext


<!-- Sent from Reviewable.io -->

2023-09-29 12:55 UTC, archit-harness requested changes
> Reviewed 1 of 15 files at r8, 8 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUoM09BUhVZ5iDZEJ9:-NfVzdj63R4Tltu2h5f7:bdg7tjf) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L80)):*
> ```Java
>   @Inject
>   public AsyncFilterCreationStreamConsumer(@Named(ASYNC_FILTER_CREATION) Consumer eventConsumer,
>       QueueController queueController, @Named(CORE_EXECUTOR_NAME) ExecutorService executorService,
> ```

Lets use PipelineAsyncValidationExecutorService
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 164 at r9](https://reviewable.io/reviews/harness/harness-core/53232#-NfVzzASBVRQ7MKPGAF7:-NfVzzASBVRQ7MKPGAF8:b-wj0d15) ([raw file](https://github.com/harness/harness-core/blob/c4c550f7117d28f6d8209b781778bf53257e370b/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L164)):*
> ```Java
>       // Ack all the messages.
>       try {
>         if (EmptyPredicate.isNotEmpty(readResult.tobeAcked)) {
> ```

Calculate setOf messageIds from readResult here and not store toBeAcked Messages
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 370 at r9](https://reviewable.io/reviews/harness/harness-core/53232#-NfW-SH_9jrXVecRFIhY:-NfW-SH_9jrXVecRFIhZ:b3vipqp) ([raw file](https://github.com/harness/harness-core/blob/c4c550f7117d28f6d8209b781778bf53257e370b/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L370)):*
> ```Java
>     }
>     PipelineEntity pipelineEntityAfterUpdate =
>         PMSPipelineFilterHelper.updateFieldsInDBEntry(oldEntityFromDB, pipelineToUpdate, timeOfUpdate);
> ```

should use below method



_Code quote:_
```Java
    PipelineEntity oldEntityFromDB = mongoTemplate.findAndModify(
        query, updateOperations, new FindAndModifyOptions().returnNew(false), PipelineEntity.class);
    if (oldEntityFromDB == null) {
      return null;
    }
    PipelineEntity pipelineEntityAfterUpdate =
        PMSPipelineFilterHelper.updateFieldsInDBEntry(oldEntityFromDB, pipelineToUpdate, timeOfUpdate);
```


<!-- Sent from Reviewable.io -->

2023-09-29 12:59 UTC, utkarshchoubey-harness commented
trigger uts

2023-10-03 07:40 UTC, utkarshchoubey-harness commented
/rebase

2023-10-03 07:41 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 25 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUoM09BUhVZ5iDZEJ9:-Nfo2fI8Dmvf8lD_yeGM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Lets use PipelineAsyncValidationExecutorService
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java` line 164 at r9](https://reviewable.io/reviews/harness/harness-core/53232#-NfVzzASBVRQ7MKPGAF7:-NfoTwYuAqAsm-3TGqZ0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c550f7117d28f6d8209b781778bf53257e370b/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationStreamConsumer.java#L164)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Calculate setOf messageIds from readResult here and not store toBeAcked Messages
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 370 at r9](https://reviewable.io/reviews/harness/harness-core/53232#-NfW-SH_9jrXVecRFIhY:-NfoTyGV4CC3S5nGJ6l8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4c550f7117d28f6d8209b781778bf53257e370b/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L370)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should use below method
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 07:45 UTC, utkarshchoubey-harness commented
/rebase

2023-10-03 08:09 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/53232#-NfKI0UC0XmYWerC0oHy:-Nfo_KwkAt0ZmYctEJGm:bjzsap2) ([raw file](https://github.com/harness/harness-core/blob/782157cc09b1b156d425387d067ccac8a6083733/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

we have just sent it, as you mentioned it might be helpful while debugging, we anyway are not using it
</blockquote></details>

If we are not using it then we can ignore from message. 


<!-- Sent from Reviewable.io -->

2023-10-03 08:11 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUj1eJ-dPMVPnVwfZe:-Nfo_YRe9shScE19ST7X:b-4yxe7j) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L57)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

pipelineIdentifier is also used in autologcontext
</blockquote></details>

Can we use pipeline identifier post fetching from db? That way we won't require that in message?
Also, single pipeline Identifier is not that much helpful. We should have accountId, orgId and projectId that we can calculate after fetching from db.


<!-- Sent from Reviewable.io -->

2023-10-03 08:32 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 57 at r6](https://reviewable.io/reviews/harness/harness-core/53232#-NfUj1eJ-dPMVPnVwfZe:-NfoeddME52KfL2BPPDd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bf40daf27675bdbb4cac6b955a169ab40c618b3d/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L57)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we use pipeline identifier post fetching from db? That way we won't require that in message?
Also, single pipeline Identifier is not that much helpful. We should have accountId, orgId and projectId that we can calculate after fetching from db.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 08:34 UTC, utkarshchoubey-harness commented
trigger uts

2023-10-03 08:47 UTC, archit-harness submitted a review, later dismissed
> Reviewed 9 of 9 files at r11, 3 of 3 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 378 at r11](https://reviewable.io/reviews/harness/harness-core/53232#-NfohoQv9nruY4jTionH:-NfohoQv9nruY4jTionI:b-fgrvk4) ([raw file](https://github.com/harness/harness-core/blob/6f96f011382d399edad626f33b5d573e284ac285/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L378)):*
> ```Java
>   }
> 
>   Pair<PipelineEntity, PipelineEntity> updatePipelineEntityWithoutOutboxEvent(
> ```

nit: add comment first value is old and right value is new


<!-- Sent from Reviewable.io -->

2023-10-03 08:58 UTC, utkarshchoubey-harness commented
trigger uts

2023-10-03 09:10 UTC, utkarshchoubey-harness commented
trigger messagecheck

2023-10-03 10:07 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 378 at r11](https://reviewable.io/reviews/harness/harness-core/53232#-NfohoQv9nruY4jTionH:-Nfp-W1B-GdMZsa3EiXH:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6f96f011382d399edad626f33b5d573e284ac285/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L378)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: add comment first value is old and right value is new
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-03 17:32 UTC, utkarshchoubey-harness commented
trigger uts

2023-10-03 17:49 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r15](https://reviewable.io/reviews/harness/harness-core/53232#-NfqeAjI01HjWX02nmHm:-NfqeAjI01HjWX02nmHn:blgveua) ([raw file](https://github.com/harness/harness-core/blob/ec425983cf94280c1519b7f188f4f32b5afc6f4f/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
> ```proto
> 
> message AsyncFilterCreatorEvent {
>   int32 yamlHash = 1;
> ```

should it be int64?


<!-- Sent from Reviewable.io -->

2023-10-03 17:51 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 56 at r15](https://reviewable.io/reviews/harness/harness-core/53232#-NfqeUXTB3CuZGEoABq7:-NfqeUXTB3CuZGEoABq8:b-9e6yhl) ([raw file](https://github.com/harness/harness-core/blob/ec425983cf94280c1519b7f188f4f32b5afc6f4f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L56)):*
> ```Java
>   public PipelineEntity updateFieldsInDBEntry(
>       PipelineEntity entityFromDB, PipelineEntity fieldsToUpdate, long timeOfUpdate) {
>     return entityFromDB.toBuilder()
> ```

Just curious, why did we use toBuilder() here?


<!-- Sent from Reviewable.io -->

2023-10-03 17:55 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: 20 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto` line 13 at r15](https://reviewable.io/reviews/harness/harness-core/53232#-NfqeAjI01HjWX02nmHm:-NfqfMY_-M9vEDXePK-W:b-6xiwjr) ([raw file](https://github.com/harness/harness-core/blob/ec425983cf94280c1519b7f188f4f32b5afc6f4f/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/filter/async_filter_creator.proto#L13)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

should it be int64?
</blockquote></details>

Done
No it should be int32 only 
Hashing.murmur3\_32\_fixed().hashString(yaml, StandardCharsets.UTF\_8).asInt();
This is the hash function
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 56 at r15](https://reviewable.io/reviews/harness/harness-core/53232#-NfqeUXTB3CuZGEoABq7:-NfqfSXb9LaonvXvNBDr:b-q6jx28) ([raw file](https://github.com/harness/harness-core/blob/ec425983cf94280c1519b7f188f4f32b5afc6f4f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L56)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Just curious, why did we use toBuilder() here?
</blockquote></details>

Done.
with field creates copy everytime, 
suppose there are 10 fields it creates 10 copies everytime


<!-- Sent from Reviewable.io -->

2023-10-04 04:24 UTC, utkarshchoubey-harness commented
trigger ut5, ut7

2023-10-04 06:59 UTC, utkarshchoubey-harness commented
trigger ut7

2023-10-04 07:11 UTC, sahilhindwani-harness approved these changes
> Reviewed 5 of 15 files at r8, 3 of 9 files at r9, 4 of 9 files at r11, 3 of 3 files at r12, 4 of 5 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53232)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-10-04 07:25 UTC, utkarshchoubey-harness commented
trigger review

2023-10-04 08:56 UTC, merged