[feat]: [PL-41291]: add uniqueId for project and org entity during creation, updation
harness/harness-core pull request #53278
Opened 2023-09-25 10:04 UTC by pbarapatre10

## Describe your changes
Introduce a `uniqueId` for SCOPE (Org, Project) entities behind a FF `PL_ENABLE_UNIQUE_ID_ON_NG_ENTITY` in Creation and Updation flow of Org/Project.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-25 15:15 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java
> +      organization.setUniqueId(UUIDGenerator.generateUuid());
If unique Id is only a random ID, why can't we use `uuid` generated by mongo and start returning it in response and start returning in response? This might also save need of migration

2023-09-26 12:05 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53278)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/53278#-NfGHyV_APgPKUY0m84d:-NfGHyV_APgPKUY0m84e:b3puivi) ([raw file](https://github.com/harness/harness-core/blob/26d4d5460255c9c5ec66dd46e3b6133e5a4eba95/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L132)):*
> ```Java
>     Organization organization = toOrganization(organizationDTO);
>     organization.setAccountIdentifier(accountIdentifier);
>     if (featureFlagService.isEnabled(FeatureName.PL_ENABLE_UNIQUE_ID_ON_NG_ENTITY, accountIdentifier)) {
> ```

Don't use FF
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/53278#-NfGKeWN7a0jsEwMhzi0:-NfGKeWN7a0jsEwMhzi1:bcvkfuh) ([raw file](https://github.com/harness/harness-core/blob/26d4d5460255c9c5ec66dd46e3b6133e5a4eba95/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java#L101)):*
> ```Java
>   String accountIdentifier;
>   // TODO: add index on this post migration for existing Orgs
>   String uniqueId;
> ```

In this PR, let's

1. Only add uuid for org/project.
2. Do migration for existing org and projects (Migration should be generic)
3. Generate uuid at the time of persistence.


<!-- Sent from Reviewable.io -->

2023-09-28 03:27 UTC, pbarapatre10 commented
trigger uts

2023-09-28 06:04 UTC, pbarapatre10 commented
trigger uts

2023-09-28 08:59 UTC, ankit-harness requested changes
> Reviewed 15 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53278)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java` line 123 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxoZOBoVyvZwJFW-e:-NfPxoZOBoVyvZwJFW-f:budzm70) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java#L123)):*
> ```Java
>       log.info(String.format("[NGAccountSetupService]: Setting up default project for account %s", accountIdentifier));
>       Project defaultProject =
>           createDefaultProject(accountIdentifier, defaultOrg.getIdentifier(), defaultOrg.getUniqueId());
> ```

We shouldnt have this change in this PR. We are not introducing parentId in this PR
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxg_26QfsbBhcvaGm:-NfPxg_26QfsbBhcvaGn:b-6fg3ml) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L106)):*
> ```Java
>   private final OrganizationInstrumentationHelper instrumentationHelper;
>   private final DefaultUserGroupService defaultUserGroupService;
>   private final FeatureFlagService featureFlagService;
> ```

Whats the purpose of this? This looks unused
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 289 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxdmn7ICX8qsY19Bm:-NfPxdmn7ICX8qsY19Bn:buzmbbd) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L289)):*
> ```Java
>         organization.setVersion(existingOrganization.getVersion());
>       }
>       if (isNotEmpty(existingOrganization.getUniqueId())) {
> ```

Why do we need to do it here? Will this not be handled via 1 time migration?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 439 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxwnn1wW7JKnoHcB6:-NfPxwnn1wW7JKnoHcB7:buzmbbd) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L439)):*
> ```Java
>       project.setCreatedAt(existingProject.getCreatedAt() == null ? existingProject.getLastModifiedAt()
>                                                                   : existingProject.getCreatedAt());
>       if (isNotEmpty(existingProject.getUniqueId())) {
> ```

Why do we need to do it here? Will this not be handled via 1 time migration?
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfQ-mp2B61vyd6v33VV:-NfQ-mp2B61vyd6v33VW:byiultr) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java#L141)):*
> ```Java
>   @Owner(developers = PRATEEK)
>   @Category(UnitTests.class)
>   public void testCreateOrganizationWithUniqueId() {
> ```

Dont see value in this test
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java` line 189 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfQ-gEY-D9jYWiLiSmz:-NfQ-gEY-D9jYWiLiSn-:b-5ke87q) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java#L189)):*
> ```Java
>   @Owner(developers = PRATEEK)
>   @Category(UnitTests.class)
>   public void testUpdateExistentOrganizationWithUniqueId() {
> ```

Don't see value in this test
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/remote/OrgProjectApiImplTest.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzJO26CmMFM3OMxwp:-NfPzJO26CmMFM3OMxwq:b-v2ugzs) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/test/java/io/harness/ng/core/remote/OrgProjectApiImplTest.java#L108)):*
> ```Java
>     project.setOrgIdentifier(org);
>     project.setVersion(0L);
>     project.setUniqueId("uniqueId");
> ```

Should we generate something at random here?
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzPYj8CZi8jHt6ndn:-NfPzPYj8CZi8jHt6ndo:b5spsgc) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java#L58)):*
> ```Java
> @ChangeDataCapture(table = "organizations", dataStore = "ng-harness", fields = {}, handler = "Organizations")
> @ChangeDataCapture(table = "tags_info_ng", dataStore = "ng-harness", fields = {}, handler = "TagsInfoNGCD")
> public class Organization extends BaseUniqueIdEntity implements PersistentEntity, NGAccountAccess, UniqueIdAware {
> ```

extends BaseUniqueIdEntity should not be needed
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Project.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzRJD8oDztr3DcCQ0:-NfPzRJD8oDztr3DcCQ1:bym0gbd) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Project.java#L59)):*
> ```Java
> @ChangeDataCapture(table = "projects", dataStore = "ng-harness", fields = {}, handler = "Projects")
> @ChangeDataCapture(table = "tags_info_ng", dataStore = "ng-harness", fields = {}, handler = "TagsInfoNGCD")
> public class Project extends BaseUniqueIdEntity implements PersistentEntity, NGAccountAccess, UniqueIdAware {
> ```

extends BaseUniqueIdEntity should not be needed

We should have uniqueId field here
___
*[`959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzaQyAw8JK04S_LwI:-NfPzaQzDrbkbrLg7R4B:b-yd9zbn) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java#L21)):*
> ```Java
> 
> @OwnedBy(PL)
> public class UniqueIdAwareEntityEventListener extends AbstractMongoEventListener<BaseUniqueIdEntity> {
> ```

UniqueIdAware
___
*[`959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzfim2djTLIKQ6_uw:-NfPzfim2djTLIKQ6_ux:b89wtwq) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java#L27)):*
> ```Java
>     BaseUniqueIdEntity entity = event.getSource();
>     if (isEmpty(entity.getUniqueId())) {
>       entity.setUniqueId();
> ```

Call method to generate UUID here itself
___
*[`960-persistence/src/main/java/io/harness/ng/BaseUniqueIdEntity.java` line 17 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPyvek807FfkcGXIOr:-NfPyvek807FfkcGXIOs:bclvtt) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/960-persistence/src/main/java/io/harness/ng/BaseUniqueIdEntity.java#L17)):*
> ```Java
 [...]

2023-09-28 11:20 UTC, pbarapatre10 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java` line 123 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxoZOBoVyvZwJFW-e:-NfQ0udF3B5TpP0zwjoh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java#L123)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We shouldnt have this change in this PR. We are not introducing parentId in this PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-28 11:20 UTC, pbarapatre10 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxg_26QfsbBhcvaGm:-NfQ12pS0JKLDyvGBOZv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L106)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the purpose of this? This looks unused
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-28 11:20 UTC, pbarapatre10 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/53278#-NfGHyV_APgPKUY0m84d:-NfQ15luCeUdZ27aHpt-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26d4d5460255c9c5ec66dd46e3b6133e5a4eba95/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L132)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Don't use FF
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-28 11:20 UTC, pbarapatre10 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 289 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxdmn7ICX8qsY19Bm:-NfQ1AGx4yeRTpHdduNo:bjvolkt) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L289)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why do we need to do it here? Will this not be handled via 1 time migration?
</blockquote></details>

In update case, we still need to populate the uniqueId alike the id field, other-wise while save it will get re-generated. Or we could change code to be setting existingOrg with the new values, that way we won't have to set in the new organization object


<!-- Sent from Reviewable.io -->

2023-09-28 11:20 UTC, pbarapatre10 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 439 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPxwnn1wW7JKnoHcB6:-NfQ1bZqA2IVMA8rCR_j:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L439)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why do we need to do it here? Will this not be handled via 1 time migration?
</blockquote></details>

Same as above


<!-- Sent from Reviewable.io -->

2023-09-28 11:45 UTC, pbarapatre10 commented
trigger ut9

2023-09-29 06:17 UTC, pbarapatre10 commented
trigger ut9

2023-09-29 10:26 UTC, pbarapatre10 commented
trigger ut9

2023-09-29 10:40 UTC, pbarapatre10 commented
trigger uts

2023-09-29 17:34 UTC, pbarapatre10 commented
trigger uts

2023-09-30 06:30 UTC, pbarapatre10 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/53278#gh-1336039248:-NfZloSH5CDWaIHarWxh:b-yuzayg) ([raw file](https://github.com/harness/harness-core/blob/c4ea7305a8243ea1250d6e3c206e42dd0835802c/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L133)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

If unique Id is only a random ID, why can't we use `uuid` generated by mongo and start returning it in response? This might also save need of migration
</blockquote></details>

We want to keep the id pattern same so going with UUID generator, thanks


<!-- Sent from Reviewable.io -->

2023-09-30 06:31 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/53278#-NfGKeWN7a0jsEwMhzi0:-NfZm-WlCsiayYOVf6Rr:b-wgfliw) ([raw file](https://github.com/harness/harness-core/blob/26d4d5460255c9c5ec66dd46e3b6133e5a4eba95/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java#L101)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

In this PR, let's

1. Only add uuid for org/project.
2. Do migration for existing org and projects (Migration should be generic)
3. Generate uuid at the time of persistence.
</blockquote></details>

Added uuid for Org/Proj. And generate uuid at time of persistence. 
Migration will send in separate PR


<!-- Sent from Reviewable.io -->

2023-09-30 06:31 UTC, pbarapatre10 commented
*[`960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPz64r19Webkz-ao2c:-NfZmErEDluNAwETtVh1:b1b9snp) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java#L15)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason it extends from PersistentEntity
</blockquote></details>

removed the extends from PersistentEntity


<!-- Sent from Reviewable.io -->

2023-09-30 06:36 UTC, pbarapatre10 commented
*[`960-persistence/src/main/java/io/harness/ng/BaseUniqueIdEntity.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfQ-PKW0WwCU-S9ogz6:-NfZmQ_v23pA-q5dl-Hp:b-7b5abj) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/960-persistence/src/main/java/io/harness/ng/BaseUniqueIdEntity.java#L28)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we think to use UUID1 version which is timestamp based?
</blockquote></details>

We are going with internal UUID itself. UUID version 1 also uses mac addresses which may result into security/privacy concern as highlighted here https://stackoverflow.com/a/62628976 . Some other timestamp based UUID may have conflicting Ids generated and if they rely on the server/k8s node time, the nodes time may slightly vary node to node. Thanks


<!-- Sent from Reviewable.io -->

2023-09-30 06:36 UTC, pbarapatre10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53278)* status: 21 file(s) to review. 1 change requests. 19. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/remote/OrgProjectApiImplTest.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzJO26CmMFM3OMxwp:-NfZlxST4CPSW1wsJ_B6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/test/java/io/harness/ng/core/remote/OrgProjectApiImplTest.java#L108)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we generate something at random here?
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java` line 58 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzPYj8CZi8jHt6ndn:-NfZlyTX4fXiQkp0YVdb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java#L58)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

extends BaseUniqueIdEntity should not be needed
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Project.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzRJD8oDztr3DcCQ0:-NfZm90T0t8B8IuOMo2s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Project.java#L59)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

extends BaseUniqueIdEntity should not be needed

We should have uniqueId field here
</blockquote></details>

Done.
___
*[`959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java` line 21 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzaQyAw8JK04S_LwI:-NfZmBcTEU7CO7qQg6EC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java#L21)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

UniqueIdAware
</blockquote></details>

Done.
___
*[`959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPzfim2djTLIKQ6_uw:-NfZmDUb2-ygWk5-OsJW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/959-ng-persistence/src/main/java/io/harness/ng/persistence/listener/UniqueIdAwareEntityEventListener.java#L27)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Call method to generate UUID here itself
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfQ-mp2B61vyd6v33VV:-NfZmM5I36QdIK-BJEWF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java#L141)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Dont see value in this test
</blockquote></details>

Done.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java` line 189 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfQ-gEY-D9jYWiLiSmz:-NfZmMa1B9WCSdk_imjD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/120-ng-manager/src/test/java/io/harness/ng/core/impl/OrganizationServiceImplTest.java#L189)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Don't see value in this test
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/ng/BUILD.bazel` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPz22rCA80spMjpIw7:-NfZmOjg330QsEw_R5hr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/960-persistence/src/main/java/io/harness/ng/BUILD.bazel#L15)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why these changes?
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/ng/BaseUniqueIdEntity.java` line 17 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPyvek807FfkcGXIOr:-NfZmQ388EQKzfC-zvwN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/960-persistence/src/main/java/io/harness/ng/BaseUniqueIdEntity.java#L17)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we need this class?
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAware.java` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/53278#-NfPy_371nkWWvblDaon:-NfZmJpL6s--YI8qvMkq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0fc3c712ca50e81004c1006a63872af9c9c5226/960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAware.java#L18)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

why this 2nd method?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 11:29 UTC, ankit-harness approved these changes
> Reviewed 2 of 12 files at r5, 2 of 2 files at r6, 8 of 10 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53278)* status: Some of the checks are too old. 21 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-03 11:35 UTC, merged