feat: [CDS-74449]: Adding prod rollback info K8s and Native Helm instance
harness/harness-core pull request #53298
Opened 2023-09-25 14:00 UTC by GoelPratyush99

## Describe your changes
The Post Prod Rollback did not show the complete information about the pipeline, current artifact and previously used artifact to which it will be rolled back. 
This is a parity feature with CG. 
The user will be able to view the complete information about the version of the artifact to which it will be rolled back.

## Test Cases
# K8s Rolling
<img width="657" alt="Screenshot 2023-10-06 at 11 17 47 AM" src="https://github.com/harness/harness-core/assets/97931011/9bac4f1e-1595-4471-ac68-55af89f15037">
<img width="793" alt="Screenshot 2023-10-06 at 11 17 56 AM" src="https://github.com/harness/harness-core/assets/97931011/9660ed5f-9b55-4aa7-ab05-86d72985fb66">
<img width="645" alt="Screenshot 2023-10-06 at 11 18 10 AM" src="https://github.com/harness/harness-core/assets/97931011/99144930-7226-45cd-8dc2-e42a27099d76">

# K8s BG
<img width="944" alt="Screenshot 2023-10-09 at 6 17 09 PM" src="https://github.com/harness/harness-core/assets/97931011/2b69c58f-e794-49cc-bc34-f581ed6267d3">
<img width="616" alt="Screenshot 2023-10-09 at 6 18 07 PM" src="https://github.com/harness/harness-core/assets/97931011/ac30e41c-fe66-49ba-bb8a-cac4f64ce8fa">
<img width="1029" alt="Screenshot 2023-10-09 at 6 17 15 PM" src="https://github.com/harness/harness-core/assets/97931011/10efaa89-f135-4e41-b36b-f8a9b93afe0e">

## Drawback
If the instances are deleted then also it will show the previous eligible artifact version to which it will be rolledback.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/53298)

2023-09-25 14:02 UTC, GoelPratyush99 commented
trigger uts

2023-09-25 14:14 UTC, GoelPratyush99 commented
trigger messagecheck

2023-09-25 14:14 UTC, GoelPratyush99 commented
trigger ss

2023-09-25 14:23 UTC, abosii-harness requested changes

2023-09-25 14:23 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +                                             : Optional.empty();
why not getting latest?

2023-09-25 14:23 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +  Optional<ArtifactDetails> getPreviousActiveInstanceArtifactDetails(String accountId, String orgId, String projectId,
So this method actually is fetching the current active instance?

2023-09-25 14:26 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +                                             : Optional.empty();
The latest one will be redundant, we already have that info with us inside the instance supplied to `**getSwimlaneInfo()**` method.  In CG we showed both the details of current artifact and one to which we will revert.

2023-09-25 14:27 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +  Optional<ArtifactDetails> getPreviousActiveInstanceArtifactDetails(String accountId, String orgId, String projectId,
Yes

2023-09-25 14:37 UTC, GoelPratyush99 commented
trigger ss

2023-09-25 14:39 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +                                             : Optional.empty();
Then what you're showing differently for prev and curr?

2023-09-25 14:48 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +                                             : Optional.empty();
![image-20230714-160152](https://github.com/harness/harness-core/assets/97931011/0b892229-d1a5-4ce2-8c87-95b5f66f8fa4)
In CG, we were showing the build referring to current artifact (Before rollback) and artifact after rollback. Same is here curr refers to (Before rollback artifact) and prev refers to (After rollback artifact). I have chosen the previous terminology as the user still has the option to choose whether to rollback or not.

2023-09-26 07:06 UTC, abhinavsingh1196 commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +  Optional<ArtifactDetails> getPreviousActiveInstanceArtifactDetails(String accountId, String orgId, String projectId,
discussed offline in call, this won't work as expected

2023-09-26 09:48 UTC, alebuh commented on 126-instance/src/main/java/io/harness/dtos/rollback/NativeHelmPostProdRollbackInfo.java
> +public class NativeHelmPostProdRollbackInfo implements PostProdRollbackSwimLaneInfo {
Could we maybe extend the K8sPostProdRollbackInfo class instead of implementing the PostProdRollbackSwimLaneInfo interface? From what I can see we have the same data in both classes

2023-10-05 04:54 UTC, GoelPratyush99 commented
trigger uts

2023-10-06 05:26 UTC, abosii-harness requested changes

2023-10-06 05:26 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/repositories/deploymentsummary/DeploymentSummaryCustomImpl.java
> +                            .and(DeploymentSummaryKeys.deploymentInfo + ".releaseName")
Instead of relying on DeploymentSummaryKeys.deploymentInfo.releaseName, wouldn't it better if we will use instanceKey? This will allow other swimlanes to use these methods

2023-10-06 05:26 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/repositories/deploymentsummary/DeploymentSummaryCustom.java
> +  Optional<DeploymentSummary> getRollbackDeploymentSummary(
Have you checked if maybe we can rely on existing method fetchNthRecordFromNow?

2023-10-06 05:44 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/repositories/deploymentsummary/DeploymentSummaryCustomImpl.java
> +                            .and(DeploymentSummaryKeys.deploymentInfo + ".releaseName")
nvm, I've confused instanceKey with instanceSyncKey, but still these fields are not indexed, maybe it's worth to create DeploymentInfoDTO from the instance and generate the instance sync key from there.

2023-10-06 05:54 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +  @VisibleForTesting
Done

2023-10-06 05:55 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/dtos/rollback/NativeHelmPostProdRollbackInfo.java
> +public class NativeHelmPostProdRollbackInfo implements PostProdRollbackSwimLaneInfo {
Right now they both are same but we have have the usecase which would require us to have field specific to one class and not another.

2023-10-06 05:59 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/repositories/deploymentsummary/DeploymentSummaryCustomImpl.java
> +                            .and(DeploymentSummaryKeys.deploymentInfo + ".releaseName")
Deployment Summary NG table has instanceSyncKey. I was thinking to using it earlier but then we might have to address difficult edge cases and instanceSyncKey is a combination of multiple parameters like release name, color (Blue greeen) and different deployments have different ways to configure instanceSyncKey. 

For kubernetes matching the release name which would need to be properly handled or might lead to failures.

2023-10-06 06:00 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/repositories/deploymentsummary/DeploymentSummaryCustom.java
> +  Optional<DeploymentSummary> getRollbackDeploymentSummary(
If we choose to rely on instance sync key then we can possibly can leverage it.

2023-10-06 06:06 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 04:31 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/repositories/deploymentsummary/DeploymentSummaryCustomImpl.java
> +                            .and(DeploymentSummaryKeys.deploymentInfo + ".releaseName")
Done

2023-10-09 04:31 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/repositories/deploymentsummary/DeploymentSummaryCustom.java
> +  Optional<DeploymentSummary> getRollbackDeploymentSummary(
Done

2023-10-09 04:31 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 05:25 UTC, abosii-harness commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +  private String createInstanceSyncKey(Instance instance) {
If someone decide to change InstanceSyncKey in DeploymentInfo how they would know that they need to make changes here as well?

2023-10-09 07:02 UTC, GoelPratyush99 commented on 120-ng-manager/src/main/java/io/harness/ng/rollback/PostProdRollbackServiceImpl.java
> +  private String createInstanceSyncKey(Instance instance) {
Done the requested change

2023-10-09 07:08 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 07:15 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 07:32 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 07:52 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 07:53 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 10:45 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/util/HarnessLabelValues.java
> +public interface HarnessLabelValues {
Don't we already have this interface?

2023-10-09 11:29 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/util/HarnessLabelValues.java
> +public interface HarnessLabelValues {
It's in 970-api-services-beans.

2023-10-09 11:29 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 11:30 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/util/HarnessLabelValues.java
> +public interface HarnessLabelValues {
So why not reference it?

2023-10-09 11:31 UTC, abosii-harness submitted a review, later dismissed

2023-10-09 11:31 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/util/HarnessLabelValues.java
> +public interface HarnessLabelValues {
Done

2023-10-09 11:55 UTC, TarunUba1 approved these changes

2023-10-09 13:02 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 13:22 UTC, abosii-harness submitted a review, later dismissed

2023-10-09 13:33 UTC, TarunUba1 approved these changes

2023-10-09 14:23 UTC, GoelPratyush99 commented
trigger ut3, ut8, ut9

2023-10-09 15:43 UTC, GoelPratyush99 commented
trigger uts

2023-10-09 15:47 UTC, abosii-harness approved these changes

2023-10-09 16:17 UTC, TarunUba1 approved these changes

2023-10-09 17:06 UTC, GoelPratyush99 commented
trigger review

2023-10-09 17:07 UTC, GoelPratyush99 commented
trigger ut7

2023-10-09 18:50 UTC, GoelPratyush99 commented
trigger ut7

2023-10-09 20:06 UTC, GoelPratyush99 commented
trigger ut7

2023-10-10 02:15 UTC, merged