fix: [CI-9680]: removing dependency of pipeline over CI for curating step Identifiers
harness/harness-core pull request #53290
Opened 2023-09-25 12:13 UTC by ShobhitSingh11

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-25 12:31 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-09-25 12:31 UTC, ShobhitSingh11 commented
trigger uts

2023-09-25 12:37 UTC, ShobhitSingh11 commented
trigger uts

2023-09-25 16:55 UTC, ShobhitSingh11 commented
trigger ut0, trigger ut1, trigger ut4, trigger ut6, trigger ut7

2023-09-25 17:43 UTC, ShobhitSingh11 commented
trigger ut7

2023-09-25 17:45 UTC, ShobhitSingh11 commented
trigger ut0, trigger ut1, trigger ut4, trigger ut6, trigger ut7

2023-09-26 05:02 UTC, vtxorxwitty submitted a review, later dismissed

2023-09-26 05:32 UTC, ShobhitSingh11 commented
trigger ut6

2023-09-26 05:40 UTC, devkimittal commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
> +    String newIdentifier = jsonNode.get(IDENTIFIER).asText() + String.join("_", identifierPostfix);
why not just jsonNode.get(IDENTIFIER).asText() + "_" + identifierPostfix;

2023-09-26 05:41 UTC, devkimittal commented on 884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java
> +    if ((EmptyPredicate.isNotEmpty(nodeName) || useMatrixFieldName)
why this change?

2023-09-26 05:43 UTC, devkimittal commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java
> +      combinations.add(strategyMetadata.getMatrixMetadata().getMatrixValuesMap());
if strategyMetadata.getMatrixMetadata() is null, it will throw npe

2023-09-26 05:45 UTC, devkimittal commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java
> +    for (ChildrenExecutableResponse.Child child : children) {
you are doing the same thing in next for loop, code looks redundant

2023-09-26 05:47 UTC, sahilhindwani-harness commented
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 376 at r3](https://reviewable.io/reviews/harness/harness-core/53290#gh-1336650095:-NfF0iJI67c3t2IqBoys:bdariw3) ([raw file](https://github.com/harness/harness-core/blob/18bff7aeae92f6da3c8bd6a3b23cf51629950ba3/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L376)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

+1, why do we need this change?


<!-- Sent from Reviewable.io -->

2023-09-26 05:47 UTC, sahilhindwani-harness requested changes
> Reviewed 7 of 10 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53290)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-26 05:47 UTC, devkimittal commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java
> +      combinations.add(strategyMetadata.getMatrixMetadata().getMatrixValuesMap());
test this code with cases where no matrix/looping is there

2023-09-26 05:56 UTC, ShobhitSingh11 commented on 884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java
> +    if ((EmptyPredicate.isNotEmpty(nodeName) || useMatrixFieldName)
Reason is we are adding postfix to make identifiers unique if we get duplicate identifiers. But if both nodeName and useMatrixFieldName flag is off then all the combinations of step identifiers will be coming in the form of integers which
will be unique already so no need of adding postfix in this case. In previous PR we were making the separate change for CI where this condition was required but in this case we are taking it from Pipeline so can remove if really not needed.

2023-09-26 05:57 UTC, ShobhitSingh11 commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
> +    String newIdentifier = jsonNode.get(IDENTIFIER).asText() + String.join("_", identifierPostfix);
Both will have the same result

2023-09-26 06:07 UTC, ShobhitSingh11 commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java
> +    for (ChildrenExecutableResponse.Child child : children) {
We need to fetch full combinations list first in order to resolve JsonNode that's why using 2 separate loop. First loop is for fetching full combination list followed by resolving jsonNode in next for loop

2023-09-26 06:12 UTC, ShobhitSingh11 commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java
> +      combinations.add(strategyMetadata.getMatrixMetadata().getMatrixValuesMap());
I think it won't, because matrixMetaData will always formed through fetchCombination method if we provide any axis in matrix strategy so is the combination map. So if we don't provide any axis none of them will formed and the size of children will be zero so no for loop will be executed in this case.

2023-09-26 06:16 UTC, ShobhitSingh11 commented on 884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java
> +    if ((EmptyPredicate.isNotEmpty(nodeName) || useMatrixFieldName)
@sahilhindwani-harness

2023-09-26 06:46 UTC, devkimittal commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
> +    String newIdentifier = jsonNode.get(IDENTIFIER).asText() + String.join("_", identifierPostfix);
yes but since there is no list here, we don't require  String.join(

2023-09-26 10:09 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-09-26 10:10 UTC, ShobhitSingh11 commented
trigger uts

2023-09-26 10:21 UTC, sahilhindwani-harness approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53290)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-09-26 11:29 UTC, ShobhitSingh11 commented
trigger messagecheck

2023-09-26 11:29 UTC, ShobhitSingh11 commented
trigger ut8

2023-09-26 11:32 UTC, ShobhitSingh11 commented
trigger ut8

2023-09-26 13:02 UTC, raghavharness approved these changes

2023-09-26 13:16 UTC, merged