fix: [CDS-78340]: Rolling Rollback async step
harness/harness-core pull request #53315
Opened 2023-09-25 21:18 UTC by TarunUba1

## Describe your changes
Creating a new ASYNC step for rollingRollback
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-26 05:37 UTC, abosii-harness requested changes

2023-09-26 05:37 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/CdAsyncExecutable.java
> +public class CdAsyncExecutable<R extends ResponseData> extends AsyncExecutableWithCapabilities {
What is the point of this class? Shouldn't it be abstract and not have default impl?

2023-09-26 05:37 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStepV2.java
> +      List<K8sDeployResponse> executionResponses = responseDataMap.values()
How this behave when response is an exception?

2023-10-03 10:41 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStepV2.java
> +package io.harness.cdng.k8s;
K8s package has now a lot of classes, maybe we should add a new sub package for async steps

2023-10-03 11:25 UTC, alebuh requested changes

2023-10-03 11:25 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStepV2.java
> +      return AsyncExecutableResponse.newBuilder().build();
same here

2023-10-03 11:25 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStepV2.java
> +      if (responseDataMap.isEmpty()) {
Better to use isEmpty(responseDataMap) to avoid NPE

2023-10-03 11:25 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sRollingRollbackStepV2.java
> +      K8sDeployResponse executionResponse = executionResponses.get(0);
we can use findFirst in the stream instead of this, in that case we don't need to do collect.

2023-10-03 13:27 UTC, TarunUba1 commented
trigger commonchecks

2023-10-03 13:47 UTC, TarunUba1 commented
trigger uts

2023-10-03 14:28 UTC, abosii-harness requested changes

2023-10-03 14:28 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/CdAsyncExecutable.java
> +                                  .setCode(GENERAL_ERROR.name())
Why this is a general error? I feel like we're losing capability of the error framework

2023-10-03 14:28 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/ayncsteps/K8sRollingRollbackStepV2.java
> +    K8sRollingRollbackStepParameters rollingRollbackStepParameters =
When we're planning to remove v1 step and GA these changes? I'm just thinking that there is a lot of duplicated code here and if there are any changes made then we will have to duplicate these changes in both steps

2023-10-09 04:35 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sRollingRollbackStepPlanCreator.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/53315#-NgHhj2xBqQvVuMVVHD2:-NgHhj2xBqQvVuMVVHD3:bgv70fv) ([raw file](https://github.com/harness/harness-core/blob/47f33ef4c3ff545cd501efc58e972abc4f5dc83c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sRollingRollbackStepPlanCreator.java#L64)):*
> ```Java
>   @Override
>   public StepType getStepSpecType(PlanCreationContext ctx, K8sRollingRollbackStepNode stepElement) {
>     if (featureFlagService.isEnabled(
> ```

Please dont enable this FF just after deployment, we should enable a day after deployment because if rollback happens then many of the execution will be stuck.


<!-- Sent from Reviewable.io -->

2023-10-19 05:33 UTC, closed without merging