[feat]: [CDS-78902] : TF Assume IAM Role, Apply Step Data Model changes
harness/harness-core pull request #53313
Opened 2023-09-25 19:37 UTC by tchaurasiya

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-26 07:31 UTC, tmacari-harness requested changes
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53313)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/AWSIAMRoleCredentialSpec.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/53313#-NfFKrs69-oCyIFuSTx8:-NfFKrs69-oCyIFuSTx9:by409ry) ([raw file](https://github.com/harness/harness-core/blob/e690c99a933d3af05c6a8b40dac266a56aff6079/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/AWSIAMRoleCredentialSpec.java#L45)):*
> ```Java
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) @NotNull private ParameterField<String> connectorRef;
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) @NotNull private ParameterField<String> region;
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) @NotNull private ParameterField<String> roleArn;
> ```

I think roleArn and region are optional
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformConfig.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/53313#-NfFNr2tEr3o9sgkXDlQ:-NfFNr2tEr3o9sgkXDlR:b-wwu8e4) ([raw file](https://github.com/harness/harness-core/blob/e690c99a933d3af05c6a8b40dac266a56aff6079/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformConfig.java#L77)):*
> ```Java
>   boolean useConnectorCredentials;
>   boolean isTerraformCloudCli;
>   TerraformProviderCredential providerCredential;
> ```

I think we do no use to store object from YAML model, we're creating some DTO objects instead.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/terraform/TerraformTaskNGParameters.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/53313#-NfFOVgN4dxeJEAYEALf:-NfFOVgN4dxeJEAYEALg:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/e690c99a933d3af05c6a8b40dac266a56aff6079/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/terraform/TerraformTaskNGParameters.java#L95)):*
> ```Java
>   String planName;
>   boolean encryptDecryptPlanForHarnessSMOnManager;
>   TerraformProviderCredential providerCredential;
> ```

Same here


<!-- Sent from Reviewable.io -->

2023-09-26 07:54 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java
> +            .providerCredential(spec.getProviderCredential())
TerraformApplyStep is not used, as we have implemented TerraformApplyStepV2

2023-09-26 09:30 UTC, alebuh requested changes

2023-09-26 09:30 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformProviderCredential.java
> +@OwnedBy(CDC)
Shouldn't be CDP?

2023-09-26 09:30 UTC, alebuh commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/terraform/TerraformTaskNGParameters.java
> +  TerraformProviderCredential providerCredential;
If we are adding it to the DelegateParams we should add it to the Kryo registar

2023-10-06 06:22 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java
> +            .providerCredential(spec.getProviderCredential())
Yes @vlica-harness , I am making changes in incremantal way. TerraformApplyV2 step will come in next PR

2023-10-06 06:22 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformProviderCredential.java
> +@OwnedBy(CDC)
Done.

2023-10-06 06:22 UTC, tchaurasiya commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/terraform/TerraformTaskNGParameters.java
> +  TerraformProviderCredential providerCredential;
Done. thanks.

2023-10-06 06:22 UTC, tchaurasiya commented
trigger uts

2023-10-06 08:16 UTC, tmacari-harness submitted a review, later dismissed
> Reviewed 4 of 13 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53313)* status: 19 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-06 08:25 UTC, alebuh approved these changes

2023-10-06 08:25 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java
> +      return null;
nit: for future reference might be better to use Optional.empty() instead of null

2023-10-06 10:36 UTC, alebuh approved these changes

2023-10-06 10:38 UTC, vlica-harness approved these changes

2023-10-06 10:42 UTC, vlica-harness commented
@tchaurasiya what if customer will use an old delegate? If we want to make sure that delegate will pickup this new functionality we need to create a new terraform task version.
cc @tmacari-harness

2023-10-06 11:38 UTC, tchaurasiya commented
trigger review

2023-10-06 12:09 UTC, tchaurasiya commented
trigger uts

2023-10-06 13:12 UTC, vlica-harness submitted a review, later dismissed

2023-10-06 13:15 UTC, tmacari-harness approved these changes
> Reviewed 2 of 6 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53313)* status: 27 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-06 13:45 UTC, alebuh submitted a review, later dismissed

2023-10-08 08:33 UTC, tchaurasiya commented
trigger uts

2023-10-09 06:20 UTC, alebuh approved these changes

2023-10-09 07:07 UTC, vlica-harness approved these changes

2023-10-09 07:08 UTC, tchaurasiya commented
trigger messagecheck

2023-10-09 07:08 UTC, tchaurasiya commented
trigger review

2023-10-09 07:10 UTC, tchaurasiya commented
trigger messagecheck

2023-10-09 07:14 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 13 files at r2, 13 of 15 files at r3, 2 of 6 files at r4, 10 of 11 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53313)* status: 1 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-09 07:21 UTC, merged