[CDS-77252]: Support for service now create ticket using standard template
harness/harness-core pull request #53336
Opened 2023-09-26 05:57 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-27 06:43 UTC, abhinavmittal-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.error("Failed to create ServiceNow ticket: {}", ExceptionUtils.getMessage(e), e);
Make this a constant

2023-09-27 06:45 UTC, vivekkarnatiharness commented
trigger uts

2023-09-27 06:45 UTC, abhinavmittal-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +    String sys_id = standardTemplate.getServiceNowTemplateList().get(0).getSys_id();
can the list be empty or null?
If so please add a check

2023-09-27 07:01 UTC, abhinavmittal-harness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/servicenow/ServiceNowTaskNGHelperTest.java
> +    JsonNode successResponse = JsonUtils.asTree(Collections.singletonMap("result", responsemap));
Use RESULT enum from ServiceNowConstant

2023-09-27 12:53 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepInfo.java
> +  ParameterField<String> createType;
It can simply be a normal enum field, we don't need parameterField here. 
@abhinavmittal-harness please confirm

2023-09-28 04:05 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/servicenow/ServiceNowTaskNGHelperTest.java
> +    JsonNode successResponse = JsonUtils.asTree(Collections.singletonMap("result", responsemap));
Done

2023-09-28 04:05 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepInfo.java
> +  ParameterField<String> createType;
@abhinavmittal-harness

2023-10-03 04:02 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.error("Failed to create ServiceNow ticket: {}", ExceptionUtils.getMessage(e), e);
Done

2023-10-03 06:28 UTC, abhinavmittal-harness commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepInfo.java
> +  ParameterField<String> createType;
Yeah I agree

2023-10-09 06:36 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepInfo.java
> +  ParameterField<String> createType;
Done, have refactored the code to move it to use enum

2023-10-09 12:17 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/ServiceNowCreateType.java
> +  @JsonProperty("Form") FORM,
Please use constants here

2023-10-09 13:18 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepInfo.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH, allowableValues = "Form, Normal, Standard")
we should one allowed value coming from enum itself

2023-10-09 13:20 UTC, naman-goenka commented on pipeline-service/service/src/main/resources/static-schema/v0/pipeline.json
> +              "required" : [ "connectorRef", "ticketType" ],
we will need to revert this?

2023-10-09 13:21 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +  public static final String FAILURE_MESSAGE_SERVICENOW_CREATE_STANDARD_TEMPLATE = "Failed to create ServiceNow ticket";
Can we enhance both error messages to include creation from standard change template

2023-10-09 13:24 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +    if (serviceNowTaskNGParameters.getTemplateName() == null) {
nit: isBlank check

2023-10-09 13:34 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.info("Response received for createUsingTemplate: {}", response);
similarly here

2023-10-09 13:36 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.info("ticketNumber created for ServiceNow: {}", ticketNg.getNumber());
similalrly here

2023-10-09 13:36 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.info("ticketNumber created for ServiceNow: {}", ticketNg.getNumber());
we can add template id in logs as well here

2023-10-09 13:38 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      String ticketUrlFromTicketId = ServiceNowUtils.prepareTicketUrlFromTicketNumber(
we can use getTicketUrlFromTicketIdOrNumber for safety

2023-10-09 13:41 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.error("Failed to create ServiceNow ticket: {}", ExceptionUtils.getMessage(e), e);
similarly here

2023-10-10 06:32 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      String ticketUrlFromTicketId = ServiceNowUtils.prepareTicketUrlFromTicketNumber(
Done

2023-10-10 06:32 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.info("ticketNumber created for ServiceNow: {}", ticketNg.getNumber());
Done

2023-10-10 06:32 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.info("Response received for createUsingTemplate: {}", response);
Done

2023-10-10 06:32 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +      log.info("createUsingTemplate called for ticketType: {}, templateName: {}",
Done

2023-10-10 06:32 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +    if (serviceNowTaskNGParameters.getTemplateName() == null) {
Done

2023-10-10 06:33 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +  public static final String FAILURE_MESSAGE_SERVICENOW_CREATE_STANDARD_TEMPLATE = "Failed to create ServiceNow ticket";
Done

2023-10-10 06:34 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/beans/ServiceNowCreateType.java
> +  @JsonProperty("Form") FORM,
Done

2023-10-10 06:35 UTC, vivekkarnatiharness commented on pipeline-service/service/src/main/resources/static-schema/v0/pipeline.json
> +              "required" : [ "connectorRef", "ticketType" ],
Will revert it in the end, ui needs this for pr env to work

2023-10-10 06:35 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepInfo.java
> +  @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH, allowableValues = "Form, Normal, Standard")
Lets discuss once regarding this

2023-10-10 06:42 UTC, vivekkarnatiharness commented
trigger uts

2023-10-10 14:06 UTC, naman-goenka reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 16 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/53336#gh-1338117535:-NgOrGTN9i3UsmAS1ova:b-dxo14o) ([raw file](https://github.com/harness/harness-core/blob/eec80d014af6f836aa166ecd92743c35024586c3/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L292)):*
<details><summary><i>Previously, vivekkarnatiharness wrote…</i></summary><blockquote>

We will always get a singleton list. This method getStandardTemplate will make sure only one element is returned in list.
</blockquote></details>

nit: We can this and above statement in try catch: getting sys_id is also not catched in `getStandardTemplateFields` , we can get a npe there if sys_id is not present.


<!-- Sent from Reviewable.io -->

2023-10-11 06:21 UTC, vivekkarnatiharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 16 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 584 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350332688:-NgSOGT7B9EzO5Tr4W1w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L584)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

can we constant for "_meta"
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 586 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350333519:-NgSOHKS2kfFwjg7k7C8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L586)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

similarly here
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 589 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350353228:-NgSOKEGC2TQfXpt8FQB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L589)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

please add isArray check as well
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java` line 144 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350360622:-NgSOOW6CYO-kxRHy7YC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java#L144)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

better place for this would be in `ServiceNowCreateSpecParameters`
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350384398:-NgSOPNO2rOY2gu3MqW3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java#L41)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

this needs to be corrected: it will be error for 
`creationType: Normal`


</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 06:28 UTC, vivekkarnatiharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 16 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/53336#gh-1338117535:-NgSP9zY2r5gbdTJZ2h2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eec80d014af6f836aa166ecd92743c35024586c3/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L292)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

nit: We can this and above statement in try catch: getting sys_id is also not catched in `getStandardTemplateFields` , we can get a npe there if sys_id is not present.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 10:46 UTC, vivekkarnatiharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 16 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 593 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350330548:-NgTL6pP5WqHcWOe_UuM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L593)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

instead of doing this we can append non empty ignored fields in a list, and do `Joiner.on(",").join`
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 597 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350337288:-NgTL5CmBYxTTnutCbwB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L597)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

we need to `continue` the for loop here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 11:16 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java
> +    if (specParameters.getUseServiceNowTemplate().getValue() != null || specParameters.getCreateType() != null) {
Can you check the logic again??

2023-10-11 11:59 UTC, naman-goenka requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 16 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350384398:-NgTaMp95RSttqjZ-2Vz:b-6wfnb9) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java#L41)):*
<details><summary><i>Previously, vivekkarnatiharness wrote…</i></summary><blockquote>

Can you check the logic again??
</blockquote></details>

What if specParameters.getUseServiceNowTemplate().getValue() is false will it go into this loop?


<!-- Sent from Reviewable.io -->

2023-10-11 11:59 UTC, naman-goenka reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 16 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/53336#gh-1338117535:-NgTarVwDhWs_RN2y2ZO:b-tf2ymo) ([raw file](https://github.com/harness/harness-core/blob/eec80d014af6f836aa166ecd92743c35024586c3/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L292)):*
<details><summary><i>Previously, vivekkarnatiharness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: we can log here as well


<!-- Sent from Reviewable.io -->

2023-10-12 08:02 UTC, vivekkarnatiharness commented
trigger uts

2023-10-12 08:22 UTC, naman-goenka approved these changes
> Reviewed 2 of 8 files at r1, 1 of 7 files at r4, 4 of 6 files at r7, 3 of 6 files at r8, 1 of 1 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 16 file(s) to review. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-12 12:00 UTC, vivekkarnatiharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 17 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/53336#gh-1338117535:-NgYkUHp00S4IGO1Ylf-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eec80d014af6f836aa166ecd92743c35024586c3/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L292)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

nit: we can log here as well
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java` line 41 at r5](https://reviewable.io/reviews/harness/harness-core/53336#gh-1350384398:-NgYkVLW8qLJIrbgsw8X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cd4c88a0e50e4a0a4f1385489b2bacc304d43677/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java#L41)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

What if specParameters.getUseServiceNowTemplate().getValue() is false will it go into this loop?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-13 10:29 UTC, vivekkarnatiharness commented
trigger uts

2023-10-13 11:36 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-10-13 13:13 UTC, naman-goenka approved these changes

2023-10-13 14:08 UTC, abhinavmittal-harness approved these changes
> Reviewed 2 of 8 files at r1, 1 of 2 files at r3, 1 of 7 files at r4, 1 of 6 files at r7, 3 of 6 files at r8, 1 of 1 files at r10, 5 of 5 files at r11, 1 of 4 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53336)* status: 4 file(s) to review. 10. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-13 14:08 UTC, abhinavmittal-harness commented
trigger review

2023-10-13 14:28 UTC, merged