[feat]: [CCM-14342]: Adding permissions, resources for CCM Anomalies & Recommendations
harness/harness-core pull request #53350
Opened 2023-09-26 08:50 UTC by iamanmolm

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-26 09:00 UTC, Rohit-Kaliki approved these changes

2023-09-26 19:03 UTC, meenakshi-harness requested changes

2023-09-26 19:03 UTC, meenakshi-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: CCM_RECOMMENDATIONS
To use these resources we will need to create implementation class for each according to this https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812876/Onboarding+Resources+for+ResourceGroup

2023-09-27 01:50 UTC, iamanmolm commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: CCM_RECOMMENDATIONS
We don’t want to onboard these resources as part of resource groups. We have multiple such resources which are not necessarily onboarded to resource groups. These resources are added to cross map permission against their respective resources.

2023-09-27 02:39 UTC, ankit-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: ccm_anomalies_view
Can we expand on anomalies and recommendations? anomalies and recommendations are very generic resources. Something like

ccm_costanomalies_view
ccm_costrecommendations_view

2023-09-27 04:17 UTC, iamanmolm commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: ccm_anomalies_view
@ankit-harness 
Have named it similar to other existing permissions for CCM to keep the naming consistent.
Since, CCM has only one component each for anomalies and recommendations, did not add cost explicitly to the permissions.
Thoughts?

2023-09-27 04:33 UTC, iamanmolm commented
trigger ut1, ut5

2023-09-27 04:53 UTC, iamanmolm commented
trigger ut1

2023-09-27 07:25 UTC, ankit-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: ccm_anomalies_view
Issue I see is in future lets say other modules have same resources  - anomalies and recommendations. But since we have defined the permissions in this way earlier, we can be consistent here

2023-09-27 07:42 UTC, meenakshi-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: CCM_RECOMMENDATIONS
So there will be now way for customers to provide these permissions?

2023-09-27 08:47 UTC, iamanmolm commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: CCM_RECOMMENDATIONS
Customer would bind these permission against 'All Resources', as do they for other CCM resource as well, for ex: CCM_PERSPECTIVE etc.

2023-09-27 09:50 UTC, meenakshi-harness commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: CCM_RECOMMENDATIONS
But we have seen multiple cases in last few days were customer user custom resource group to provide permissions instead of build in resource groups. This can again open a ticket even for other CCM resources.

2023-09-28 09:56 UTC, iamanmolm commented on access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml
> +  - identifier: CCM_RECOMMENDATIONS
Done for these 2 resources added.

2023-09-28 10:03 UTC, iamanmolm commented
trigger uts

2023-09-28 12:59 UTC, iamanmolm commented
trigger ut2, ut4, ut5, ut7

2023-09-29 09:07 UTC, iamanmolm commented
trigger ut4

2023-09-29 10:32 UTC, meenakshi-harness approved these changes

2023-09-29 13:05 UTC, merged