fix: [CDS-75773]: Complete implementation for Restraint based on gh token
harness/harness-core pull request #53376
Opened 2023-09-26 11:53 UTC by hextechpal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-26 22:40 UTC, meenaravichandran1 commented
@lasdox @hextechpal are we planning to do the same for Revert PR step as well? it creates PRs as well, but the frequency in which it is used might be lesser compared to the Update Release Repo step.

2023-09-27 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53376) before we can accept your contribution.<br/>**28** out of **30** committers have signed the CLA.<br/><br/>:white_check_mark: n00bitax<br/>:white_check_mark: smjt-h<br/>:white_check_mark: tmacari-harness<br/>:white_check_mark: sahilhindwani-harness<br/>:white_check_mark: vikyathharekal<br/>:white_check_mark: brijeshdhakar<br/>:white_check_mark: vlica-harness<br/>:white_check_mark: TarunUba1<br/>:white_check_mark: inderschera<br/>:white_check_mark: shalini-agr<br/>:white_check_mark: vivekkarnatiharness<br/>:white_check_mark: hextechpal<br/>:white_check_mark: mohitg0795<br/>:white_check_mark: abhinavsingh1196<br/>:white_check_mark: sarthakkasat<br/>:white_check_mark: raghavharness<br/>:white_check_mark: ShobhitSingh11<br/>:white_check_mark: lasdox<br/>:white_check_mark: bhavya181<br/>:white_check_mark: adivishy1<br/>:white_check_mark: arpit-harness<br/>:white_check_mark: jamie-harness<br/>:white_check_mark: rohitk-h<br/>:white_check_mark: sandeepa-kv-jois<br/>:white_check_mark: kapil-harness<br/>:white_check_mark: anilchowdhury-harness<br/>:white_check_mark: sahibaHarness<br/>:white_check_mark: swapnil-harness<br/>:x: RajBaviskar<br/>:x: Rakshitharness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53376) it.</sub>

2023-09-27 10:52 UTC, hextechpal commented on 120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java
> +    //    injector.getInstance(GithubRestraintPersistenceMonitor.class)
remove this

2023-09-27 10:52 UTC, hextechpal commented on 120-ng-manager/config.yml
> +  githubRestraintIteratorConfig:
not needed

2023-09-27 10:52 UTC, hextechpal commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/githubrestraint/services/GithubRestraintPersistenceMonitor.java
> +public class GithubRestraintPersistenceMonitor implements Handler<GithubRestraintInstance> {
this is not needed

2023-09-27 10:52 UTC, hextechpal commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/githubrestraint/services/GitopsStepFinishHandler.java
> +public class GitopsStepFinishHandler implements OrchestrationEventHandler {
Name this a bit better

2023-09-27 10:52 UTC, hextechpal commented on 125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java
> +  private static final Set<StepType> STEP_TYPES_GIT_LOCK =
not needed

2023-09-27 10:52 UTC, hextechpal commented on 125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java
> +    kryo.register(GitopsStepFinishCallback.class, 13007);
change ids to be greater not lesser

2023-09-27 10:52 UTC, hextechpal commented on 445-gitops/src/main/java/io/harness/gitopsprovider/entity/GithubRestraintInstance.java
> +public class GithubRestraintInstance implements PersistentEntity, UuidAccess, PersistentRegularIterable {
No need for this to be iterable at least now

2023-09-27 10:52 UTC, hextechpal commented on 970-ng-commons/src/main/java/io/harness/NgIteratorsConfig.java
> +  NgIteratorConfig githubRestraintIteratorConfig;
not needed

2023-09-27 17:10 UTC, lasdox commented
trigger uts

2023-09-27 19:33 UTC, lasdox commented
trigger uts

2023-09-28 13:45 UTC, lasdox commented
trigger uts

2023-10-04 05:34 UTC, hextechpal commented
trigger uts

2023-10-04 09:53 UTC, hextechpal commented
trigger uts

2023-10-04 14:40 UTC, lasdox commented
trigger trigger uts

2023-10-04 14:42 UTC, lasdox commented
trigger commonchecks

2023-10-04 14:42 UTC, lasdox commented
trigger uts

2023-10-04 16:29 UTC, hextechpal commented
trigger pmd

2023-10-04 16:30 UTC, hextechpal commented
trigger codebasehash

2023-10-04 19:10 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/githubrestraint/services/GithubRestraintInstanceServiceImpl.java
> +      log.error("Failed to add GithubRestraintInstance", e);
missing placeholder for arguments here

2023-10-04 19:27 UTC, meenaravichandran1 reviewed
Since we have enabled this logic for all the git providers, it would be better to name GithubRestraint in a generic way (we can take that up later too).

2023-10-04 19:39 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java
> +    GithubConnectorDTO githubConnectorDTO = (GithubConnectorDTO) connectorInfoDTO.getConnectorConfig();
We have to handle other providers as well. This might result in ClassCastException.

2023-10-04 19:40 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +  private String extractToken(ConnectorInfoDTO connectorInfoDTO) {
Since this logic is common to Update release repo step, can we have it common somewhere?

2023-10-04 19:46 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +        GITOPS_MERGE_PR.getName() + AmbianceUtils.getAccountId(ambiance) + tokenRefIdentifier;
So, we have restricted executions based on token. Did a different token work for the ratelimited/blocked user?

2023-10-04 20:13 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +    GithubCredentialsDTO githubCredentialsDTO = githubConnectorDTO.getAuthentication().getCredentials();
We have to handle other providers as well. This might result in ClassCastException for Gitlab, Bitbucket, Azure.

2023-10-04 20:13 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +    GithubCredentialsDTO githubCredentialsDTO = githubConnectorDTO.getAuthentication().getCredentials();
Since this logic is common to Update release repo step, can we have it common somewhere?

2023-10-04 22:38 UTC, lasdox commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +        GITOPS_MERGE_PR.getName() + AmbianceUtils.getAccountId(ambiance) + tokenRefIdentifier;
No, it didnt, but this is the best we can work with. @meenaravichandran1

2023-10-04 22:38 UTC, lasdox commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +    GithubCredentialsDTO githubCredentialsDTO = githubConnectorDTO.getAuthentication().getCredentials();
Yes! Do we have a GitopsUtils?

2023-10-04 23:04 UTC, rohitk-h requested changes
> Reviewed 2 of 16 files at r1, 1 of 8 files at r2, 3 of 9 files at r3, 1 of 11 files at r4, 8 of 10 files at r5, 6 of 11 files at r6, 2 of 5 files at r7, 3 of 5 files at r8, 2 of 5 files at r9, 1 of 4 files at r13, 4 of 4 files at r14, 4 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53376)* status: 37 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto,del-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 195 at r15](https://reviewable.io/reviews/harness/harness-core/53376#-NfwlkmrBTg2Hu4gPWh7:-NfwlkmrBTg2Hu4gPWh8:b-8dd0xz) ([raw file](https://github.com/harness/harness-core/blob/cb5f263be44c24d721f79c3d8815c82b593cf90f/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L195)):*
> ```Java
>     Map<String, Object> constraintContext = populateConstraintContext(constraintUnit, releaseEntityId);
>     logCallback.saveExecutionLog(
>         String.format("Trying to acquire lock on token for %s operation", CONSTRAINT_OPERATION));
> ```

nit: we could print the connector identifier here. this will help user greatly. can be done in follow-up pr. Also, we should move this after the FF check to queue task. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 438 at r15](https://reviewable.io/reviews/harness/harness-core/53376#gh-1346407647:-NfwnWvk5viAR4EZKkzc:b32v57) ([raw file](https://github.com/harness/harness-core/blob/cb5f263be44c24d721f79c3d8815c82b593cf90f/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L438)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

Since this logic is common to Update release repo step, can we have it common?
</blockquote></details>

+1
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java` line 548 at r15](https://reviewable.io/reviews/harness/harness-core/53376#-NfwtmyB2aIfXsVTTy4T:-NfwtmyB2aIfXsVTTy4U:b-ud480z) ([raw file](https://github.com/harness/harness-core/blob/cb5f263be44c24d721f79c3d8815c82b593cf90f/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java#L548)):*
> ```Java
>                                     .build();
> 
>       return TaskRequestsUtils.prepareCDTaskRequest(ambiance, taskData, referenceFalseKryoSerializer,
> ```

Can we use `TaskRequestsUtils.prepareTaskRequestWithTaskSelector` like in `MergePR Step`


<!-- Sent from Reviewable.io -->

2023-10-04 23:05 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java
> +    GithubConnectorDTO githubConnectorDTO = (GithubConnectorDTO) connectorInfoDTO.getConnectorConfig();
will be fixed with https://github.com/harness/harness-core/pull/53738

2023-10-04 23:05 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +    GithubCredentialsDTO githubCredentialsDTO = githubConnectorDTO.getAuthentication().getCredentials();
will be fixed with https://github.com/harness/harness-core/pull/53738

2023-10-04 23:17 UTC, lasdox commented
> nit: we could print the connector identifier here. this will help user greatly. can be done in follow-up pr. Also, we should move this after the FF check to queue task.

will do in follow up

> +1

Already being taken care

> Can we use `TaskRequestsUtils.prepareTaskRequestWithTaskSelector` like in `MergePR Step`

No, one is for TaskExecutable interface, we are just keeping it there for backwards compability (it is the old way)

2023-10-04 23:21 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java
> +        GITOPS_MERGE_PR.getName() + AmbianceUtils.getAccountId(ambiance) + tokenRefIdentifier;
okay

2023-10-04 23:29 UTC, meenaravichandran1 submitted a review, later dismissed

2023-10-04 23:31 UTC, rohitk-h reviewed
> Reviewed 3 of 3 files at r16, 13 of 16 files at r17, 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53376)* status: 38 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-10-04 23:31 UTC, lasdox commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/githubrestraint/services/GithubRestraintInstanceServiceImpl.java
> +      log.error("Failed to add GithubRestraintInstance", e);
didnt get you

2023-10-04 23:31 UTC, lasdox commented
trigger uts

2023-10-04 23:32 UTC, rohitk-h reviewed
> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53376)* status: 38 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-10-04 23:33 UTC, meenaravichandran1 submitted a review, later dismissed

2023-10-04 23:35 UTC, rohitk-h commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java` line 548 at r15](https://reviewable.io/reviews/harness/harness-core/53376#-NfwtmyB2aIfXsVTTy4T:-Nfx2-Oh7wMd3qLStXFO:bbuke13) ([raw file](https://github.com/harness/harness-core/blob/cb5f263be44c24d721f79c3d8815c82b593cf90f/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java#L548)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Can we use `TaskRequestsUtils.prepareTaskRequestWithTaskSelector` like in `MergePR Step`
</blockquote></details>

Discussed offline, looks good!


<!-- Sent from Reviewable.io -->

2023-10-04 23:37 UTC, meenaravichandran1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/githubrestraint/services/GithubRestraintInstanceServiceImpl.java
> +      log.error("Failed to add GithubRestraintInstance", e);
discussed offline, we don't need {} for exception. Resolving

2023-10-05 00:05 UTC, lasdox commented
trigger uts

2023-10-05 00:29 UTC, rohitk-h submitted a review, later dismissed
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53376)* status: 38 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-10-05 01:54 UTC, lasdox commented
trigger uts

2023-10-05 03:27 UTC, merged