fix: [CI-9707]: Support certs from new location for CI
harness/harness-core pull request #53370
Opened 2023-09-26 10:59 UTC by smjt-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-26 11:03 UTC, smjt-h commented
trigger uts

2023-09-28 06:19 UTC, xingchi-jin commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      log.warn("Skipping mounting from {} as certs might not be set", DESTINATION_CA_PATH);
I feel it's better to say, cannot find valid certs or destination not set. Moving on to use certs specified with CI_MOUNT_VOLUMES

2023-09-28 06:21 UTC, xingchi-jin commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +    // try to get certs from SHARED_CA_CERTS_PATH if its set else get from ADDITIONAL_CERTS_PATH for backward
should the log be if SHARED_CA_CERTS_PATH , else ADDITIONAL_CERTS_PATH 
or should it be

if SHARED_CA_CERTS_PATH , takes certs from it
also 
if ADDITIONAL_CERTS_PATH, take certs from it

2023-09-28 06:23 UTC, xingchi-jin commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
>    public Map<String, List<String>> getSecretVolumeMappings() {
same question another comment below, should the logic be taking certs from either  new solution or old solution,

or should it be

take certs from both new solution and old solution ? 

I prefer the latter

2023-09-29 19:48 UTC, xingchi-jin requested changes

2023-09-29 19:48 UTC, xingchi-jin commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      if (fileExists(sourcePath)) {
@smjt-h  this may not work with this implementation, feel free to correct me.

In the new solution, we allow customer to mount a whole directory (of multiple cert files) to the delegate. Same here with the $SHARED_CA_CERTS_PATH,  this is a directory not a file.

2023-10-09 08:56 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      log.warn("Skipping mounting from {} as certs might not be set", DESTINATION_CA_PATH);
done

2023-10-09 08:58 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      if (fileExists(sourcePath)) {
modified the logic to take certs from dir

2023-10-09 09:08 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
>    public Map<String, List<String>> getSecretVolumeMappings() {
Set certs from new solution as precedence,
Else if there is any issues while setting from new solution then set from old solution.
It will set either from new or old but not both, as it will be easy to distinguish and migrate from old to new

2023-10-09 09:18 UTC, smjt-h commented
trigger uts

2023-10-10 04:52 UTC, smjt-h commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +    // try to get certs from SHARED_CA_CERTS_PATH if its set else get from ADDITIONAL_CERTS_PATH for backward
added log

2023-10-10 05:01 UTC, xingchi-jin commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +      additionalCertsPath = System.getenv(SHARED_CA_CERTS_PATH);
is it ok to return a directory path here ?  while line 150 is a file

2023-10-10 05:48 UTC, smjt-h commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +      additionalCertsPath = System.getenv(SHARED_CA_CERTS_PATH);
added logic to copy all certs to a file and return that

2023-10-10 05:48 UTC, smjt-h commented
trigger uts

2023-10-10 06:27 UTC, smjt-h commented
trigger ut8

2023-10-11 15:58 UTC, vistaarjuneja commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +          String outputFilePath =
@smjt-h there can be multiple tasks who are writing to this file simultaneously. This can lead to unexpeced behavior. Instead, we should either create a random temp file and remove it after every run or generate it once on startup and use it for all the tasks.
Also, move this variable outside this loop.

2023-10-11 15:58 UTC, vistaarjuneja commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +          secretVolumeMappings.get(sourcePath).addAll(destinationList);
Should we not use the combined certs here instead of treating every path separately?
Let's say `SHARED_CA_CERTS_PATH` contains `/path/to/x` and `/path/to/y`.
And destination list is `/tmp/certs`.
This would generate the mapping
`/path/to/x -> /tmp/certs`
`/path/to/y -> /tmp/certs`

which would effectively overwrite each other instead of adding all the certs together.

2023-10-12 12:33 UTC, smjt-h commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +          String outputFilePath =
modified logic to take certs from asingle concatenated pem files

2023-10-12 12:34 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +          secretVolumeMappings.get(sourcePath).addAll(destinationList);
modified logic so that source is always a single concatinated pem file , and there can be multiple destination path

2023-10-12 12:35 UTC, smjt-h commented
trigger uts

2023-10-13 04:34 UTC, xingchi-jin commented on dockerization/delegate/immutable-scripts/load_certificates.sh
> +# Add a variable to store the path of the concatenated .pem file
pl. also raise a PR here https://github.com/harness/delegate-dockerfile/blob/main/immutable-scripts/load_certificates.sh

2023-10-13 04:37 UTC, xingchi-jin commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
STO specifically asked for the certs to be splitted and then mouted. 

@williamwissemann can you help review this as well

2023-10-13 05:01 UTC, r0610205 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
Yes, correct that was the entire idea. As delegate splits the certs into individual files they need to be available for STO. We shouldn't concatenate them back after delegate splits them. Entire folder SHARED_CA_CERTS_PATH should be mounted to the destination paths as is.

2023-10-13 05:04 UTC, r0610205 requested changes
Please, check the comments in the PR

2023-10-13 05:06 UTC, r0610205 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +    log.warn("cannot find valid certs or destination not set. Moving on to use certs specified with CI_MOUNT_VOLUMES");
I think new method should take precedence over the old one, so processing of CI_MOUNT_VOLUMES should happen first

2023-10-13 05:07 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
SCM and CI build pods both need certs to be taken from a single file path.

2023-10-13 05:08 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +    log.warn("cannot find valid certs or destination not set. Moving on to use certs specified with CI_MOUNT_VOLUMES");
CI_MOUNT_VOLUMES is the old one, 
new solution takes precedence here then CI_MOUNT_VOLUMES

2023-10-13 05:47 UTC, smjt-h commented on dockerization/delegate/immutable-scripts/load_certificates.sh
> +# Add a variable to store the path of the concatenated .pem file
done

2023-10-13 05:53 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
The sto flow should remain the same as before since I am creating a separate file that have the concatenated .pem files

2023-10-13 08:02 UTC, smjt-h commented
trigger uts

2023-10-13 10:11 UTC, r0610205 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +        return false;
Destination path is location in the container where certificate will be mounted, it doesn't have to exist on delegate, so second condition is not necessary

2023-10-13 10:14 UTC, r0610205 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +    log.warn("cannot find valid certs or destination not set. Moving on to use certs specified with CI_MOUNT_VOLUMES");
Correct, missed that you are using the return in the condition is met

2023-10-13 10:26 UTC, r0610205 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +    // Add all certs from CI_MOUNT_VOLUMES if it is set
This comment is confusing. The purpose of if statement is to return empty secretVolumeMapping if v1 volumes are not configured.

2023-10-13 12:41 UTC, williamwissemann commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
Looking at the PL-39971 PR, it seems like we are creating two folders.

[dockerization/delegate/Dockerfile](https://github.com/harness/harness-core/pull/51054/files#diff-92d0902c705bdd6ce3ea233cb8435bc88302acb6a34b0178f5295b8921ea4b3fR73)

```
RUN mkdir -p /opt/harness-delegate/additional_certs_pem_split
[...]
ENV SHARED_CA_CERTS_PATH=/opt/harness-delegate/additional_certs_pem_split
```

So as long as we are volume mounting the `additional_certs_pem_split` directory and STO steps have access the flow should work.

2023-10-13 12:51 UTC, williamwissemann commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
Looking at the code a little bit closer, I'm actually seeing how `/opt/harness-delegate/additional_certs_pem_split` is getting added to `secretVolumeMappings`.

2023-10-16 05:15 UTC, smjt-h commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
secretVolumeMappings is getting updated from
SHARED_CA_CERTS_PATH/single-cert-path/all-certs.pem to DESTINATION_CA_PATH
SHARED_CA_CERTS_PATH/single-cert-path/all-certs.pem has the concatenated pem file.

2023-10-16 13:36 UTC, r0610205 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/SecretVolumesHelper.java
> +      String sourceCertPathConcatenated = sourceDirPath + "/single-cert-path/all-certs.pem";
@williamwissemann I'm going to add additional handling for STO side in the different PR

2023-10-16 13:36 UTC, r0610205 approved these changes

2023-10-16 14:22 UTC, smjt-h commented
trigger uts

2023-10-16 15:27 UTC, r0610205 submitted a review, later dismissed

2023-10-16 20:11 UTC, xingchi-jin approved these changes

2023-10-17 07:09 UTC, smjt-h commented
trigger uts

2023-10-17 12:07 UTC, merged