[fix]:[CDS-68938]:Added Validation before Delegate Creation
harness/harness-core pull request #53421
Opened 2023-09-27 05:05 UTC by Rakshitharness

## Describe your changes
Validation of required fields before creating delegate task for NexusArtifactResource

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-27 05:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53421) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53421) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53421) it.</sub>

2023-09-27 05:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53421) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53421) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53421) it.</sub>

2023-09-27 05:22 UTC, Rakshitharness commented
trigger uts

2023-09-27 06:22 UTC, Rakshitharness commented
trigger uts

2023-09-27 10:11 UTC, Rakshitharness commented
trigger uts

2023-09-27 12:15 UTC, puthrayaharness requested changes

2023-09-27 12:15 UTC, puthrayaharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java
> +    ArtifactUtils.validateIfAllValuesAssigned(MutablePair.of(NGArtifactConstants.REPOSITORY, repositoryName));
This can be a switch case for better readbility instead of if-else

2023-09-27 13:17 UTC, naman-goenka commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java
> +    ArtifactUtils.validateIfAllValuesAssigned(MutablePair.of(NGArtifactConstants.REPOSITORY, repositoryName));
+1

2023-09-28 09:28 UTC, Abhishek-CDC commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/NGArtifactConstants.java
> +  public static final String GROUP = "group";
lets use these constants in resource file also. like in place of "group" we can use this GROUP constant

2023-09-28 09:32 UTC, Abhishek-CDC commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java
> +import com.fasterxml.jackson.databind.exc.InvalidFormatException;
this is unused import, we should remove it.
Not sure why PR check didn't failed

2023-09-28 09:32 UTC, Abhishek-CDC commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImpl.java
> +import com.fasterxml.jackson.databind.exc.InvalidFormatException;
Please check files for unused imports

2023-09-28 14:49 UTC, Rakshitharness commented
trigger uts

2023-09-29 04:39 UTC, Rakshitharness commented
trigger uts

2023-09-29 05:16 UTC, Abhishek-CDC submitted a review, later dismissed

2023-09-29 06:47 UTC, naman-goenka commented on 125-cd-nextgen/src/test/java/io/harness/cdng/artifact/resources/nexus/service/NexusResourceServiceImplTest.java
> +                               RepositoryFormat.docker.name(), null, ORG_IDENTIFIER, PROJECT_IDENTIFIER, GROUP_ID,
Can we add test for invalid repository name (name not part of enum)

2023-09-29 09:09 UTC, Rakshitharness commented
trigger uts

2023-10-03 07:04 UTC, naman-goenka approved these changes

2023-10-03 10:19 UTC, Abhishek-CDC approved these changes

2023-10-04 06:28 UTC, puthrayaharness approved these changes

2023-10-04 07:25 UTC, Rakshitharness commented
trigger review

2023-10-04 08:27 UTC, merged