[feat]: [PLG-2576]: added a new API to validate a Credit Card
harness/harness-core pull request #53464
Opened 2023-09-28 00:40 UTC by kapil-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-28 00:42 UTC, kapil-harness commented
trigger uts

2023-09-28 05:09 UTC, neelam-harness approved these changes
lgtm overall! just some nits around naming

2023-09-28 05:09 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java
> +    Optional<CardDTO> optionalCreditCard =
very Nit: this can just be named as `maybeCreditCard`

2023-09-28 05:09 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java
> +  @ApiOperation(value = "Checks validity of a credit card", nickname = "is valid")
vey Nit: nickname can be rephrased as `is credit card valid`

2023-09-29 08:23 UTC, mohitg0795 commented
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/53464#-NfV1Bo80oqgoroFQ43Y:-NfV1Bo80oqgoroFQ43Z:bhsk08e) ([raw file](https://github.com/harness/harness-core/blob/58613d456769f4f51c4a29484411ca01242c9d68/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java#L220)):*
> ```Java
>   }
> 
>   private boolean isCreditCardUnexpired(CardDTO cardDTO) {
> ```

nit: better name would be "isCreditCardNotExpired"


<!-- Sent from Reviewable.io -->

2023-09-29 08:24 UTC, mohitg0795 commented
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/53464#-NfV1Bo80oqgoroFQ43Y:-NfV1Or56R5H-jUcosF-:bde55rl) ([raw file](https://github.com/harness/harness-core/blob/58613d456769f4f51c4a29484411ca01242c9d68/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java#L220)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: better name would be "isCreditCardNotExpired"
</blockquote></details>

or I would recommend you to even make this "isCreditCardExpired" and use negation on it wherever required. This is more intuitive way to use.


<!-- Sent from Reviewable.io -->

2023-09-29 08:25 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53464)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java` line 127 at r1](https://reviewable.io/reviews/harness/harness-core/53464#-NfV1cFY2PhP6d-2s_fa:-NfV1cFY2PhP6d-2s_fb:bske1bv) ([raw file](https://github.com/harness/harness-core/blob/58613d456769f4f51c4a29484411ca01242c9d68/930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java#L127)):*
> ```Java
>   @ApiOperation(value = "Checks validity of a credit card", nickname = "is valid")
>   @Operation(operationId = "isValid", summary = "Checks validity of a credit card in an account")
>   public ResponseDTO<Boolean> isValid(
> ```

Response should never be primitive type. It should always be a struct.


<!-- Sent from Reviewable.io -->

2023-09-29 19:01 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53464)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/53464#gh-1339533581:-NfXIiMn7JYxeQB5Tev-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/58613d456769f4f51c4a29484411ca01242c9d68/930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java#L125)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

vey Nit: nickname can be rephrased as `is credit card valid`
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java` line 127 at r1](https://reviewable.io/reviews/harness/harness-core/53464#-NfV1cFY2PhP6d-2s_fa:-NfXIgSm43co_33kr6LU:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/58613d456769f4f51c4a29484411ca01242c9d68/930-ng-license-manager/src/main/java/io/harness/subscription/resource/CreditCardResource.java#L127)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Response should never be primitive type. It should always be a struct.
</blockquote></details>

done
___
*[`930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/53464#gh-1339532519:-NfXIl9t54xLA8EFtBWw:b-3gqczd) ([raw file](https://github.com/harness/harness-core/blob/58613d456769f4f51c4a29484411ca01242c9d68/930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/CreditCardServiceImpl.java#L148)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

very Nit: this can just be named as `maybeCreditCard` 
</blockquote></details>

It's an optional type of object and they are always named like this e.g. optionalCrediCard.
IDE also suggested this name.


<!-- Sent from Reviewable.io -->

2023-09-29 19:02 UTC, kapil-harness commented
trigger uts

2023-09-29 19:35 UTC, mohitg0795 approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53464)* status: 7 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-09-29 19:47 UTC, kapil-harness commented
trigger ut9

2023-09-29 22:38 UTC, neelam-harness approved these changes

2023-09-29 22:53 UTC, neelam-harness commented
trigger review

2023-09-29 22:53 UTC, merged