fix: [CDS-79048]: support for linking serviceNow configuration CI to changeRequest
harness/harness-core pull request #53472
Opened 2023-09-28 06:08 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-28 12:02 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
> +        ticketUrlFromTicketId = ServiceNowUtils.prepareTicketUrlFromTicketId(serviceNowConnectorDTO.getServiceNowUrl(),
Can we fail elegantly if sys_id is also present

2023-09-29 12:23 UTC, vivekkarnatiharness commented
trigger uts

2023-10-03 06:35 UTC, abhinavmittal-harness requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53472)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 193 at r1](https://reviewable.io/reviews/harness/harness-core/53472#-NfQVnZ121dIPQqsZR6L:-NfQVnZ121dIPQqsZR6M:b-d4f04p) ([raw file](https://github.com/harness/harness-core/blob/4aa4d45c7a2657479890792d401452fbad5dabde/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L193)):*
> ```Java
>       } else {
>         ticketUrlFromTicketId = ServiceNowUtils.prepareTicketUrlFromTicketId(serviceNowConnectorDTO.getServiceNowUrl(),
>             ticketNg.getFields().get("sys_id").getDisplayValue(), serviceNowTaskNGParameters.getTicketType());
> ```

Add a check for "sys_id" not being present and if that is the case add a log
Mainly in case in future we find some use case where we are not returning  the vlaue.


<!-- Sent from Reviewable.io -->

2023-10-03 06:48 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
>              ServiceNowUtils.prepareTicketUrlFromTicketNumber(serviceNowConnectorDTO.getServiceNowUrl(),
Two suggestions: 
1. log.info("ticketNumber created for ServiceNow: {}", ticketNg.getNumber()); (If can add a isEmpty check here, and default to sys_id)
2. Can we move this logic to ServiceNowUtils in prepareTicketUrlFromTicketNumberOrId

2023-10-03 08:05 UTC, abhinavmittal-harness approved these changes

2023-10-03 10:00 UTC, vivekkarnatiharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java
>              ServiceNowUtils.prepareTicketUrlFromTicketNumber(serviceNowConnectorDTO.getServiceNowUrl(),
Done

2023-10-03 10:00 UTC, vivekkarnatiharness commented
trigger uts

2023-10-03 11:46 UTC, vivekkarnatiharness commented
trigger uts

2023-10-03 11:57 UTC, naman-goenka approved these changes

2023-10-03 12:58 UTC, vivekkarnatiharness commented
trigger uts

2023-10-03 14:10 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-10-03 21:32 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53472)* status: 3 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-03 21:32 UTC, abhinavmittal-harness commented
trigger review

2023-10-04 15:49 UTC, vivekkarnatiharness commented
trigger review

2023-10-04 16:15 UTC, merged