fix: [CDS-80278]: send response in form of page for template get response
harness/harness-core pull request #53487
Opened 2023-09-28 09:30 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 06:30 UTC, abhinavmittal-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53487)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/53487#-NfoDeem22-qRQ2SXZLD:-NfoDeem22-qRQ2SXZLE:bsjvd6l) ([raw file](https://github.com/harness/harness-core/blob/9ac76d24e0c91304884e58522f783d41ff00cf21/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L174)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectId, @QueryParam("ticketType") String ticketType,
>       @QueryParam("templateName") String templateName, @QueryParam("limit") int limit, @QueryParam("offset") int offset,
>       @BeanParam GitEntityFindInfoDTO gitEntityBasicInfo, @QueryParam("searchTerm") String searchTerm) {
> ```

should be page Number as discussed before and also please validate with de the request response


<!-- Sent from Reviewable.io -->

2023-10-03 06:37 UTC, abhinavmittal-harness commented on 120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java
> +import software.wings.beans.Service;
This is probably not needed

2023-10-05 08:37 UTC, vivekkarnatiharness commented
trigger uts

2023-10-05 08:38 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-10-05 09:05 UTC, naman-goenka commented on 120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java
> +      @QueryParam(NGCommonEntityConstants.PROJECT_KEY) String projectId, @QueryParam("ticketType") String ticketType,
since this V2, we can make ticketType as mandatory. It's always required to have that in both form and template flows.

2023-10-05 09:07 UTC, naman-goenka commented on 120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java
> +    Pageable pageable = PageRequest.of(0, size, Sort.by(Sort.Direction.DESC));
sort is required here?

2023-10-05 09:34 UTC, vivekkarnatiharness commented
trigger ut9

2023-10-05 11:27 UTC, vivekkarnatiharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53487)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/53487#gh-1343572999:-Nfz_lywApiEfou3-mfn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ac76d24e0c91304884e58522f783d41ff00cf21/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L30)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

This is probably not needed
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/53487#-NfoDeem22-qRQ2SXZLD:-Nfz_q1sA60Uo7ivyFoa:b-wk4m45) ([raw file](https://github.com/harness/harness-core/blob/9ac76d24e0c91304884e58522f783d41ff00cf21/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L174)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

should be page Number as discussed before and also please validate with de the request response
</blockquote></details>

Have done 
___
*[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 177 at r2](https://reviewable.io/reviews/harness/harness-core/53487#gh-1347063753:-Nfz_ndR3UjjMYq1WwWQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1ea6f398e65b840c352eebd1788672ef3f0eec53/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L177)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

since this V2, we can make ticketType as mandatory. It's always required to have that in both form and template flows.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 187 at r2](https://reviewable.io/reviews/harness/harness-core/53487#gh-1347065594:-Nfz_ufG2Bbvy1lOgt_L:bmn0jts) ([raw file](https://github.com/harness/harness-core/blob/1ea6f398e65b840c352eebd1788672ef3f0eec53/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L187)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

sort is required here?
</blockquote></details>

Have removed the sort


<!-- Sent from Reviewable.io -->

2023-10-05 11:45 UTC, vivekkarnatiharness commented
trigger uts

2023-10-05 11:49 UTC, naman-goenka approved these changes

2023-10-05 11:51 UTC, vivekkarnatiharness commented
trigger uts

2023-10-05 12:35 UTC, puthrayaharness approved these changes

2023-10-05 12:43 UTC, vivekkarnatiharness commented
trigger review

2023-10-05 12:54 UTC, abhinavmittal-harness reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53487)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-05 14:01 UTC, merged