[fix]: [CDS-79052]: Secrets Runtime Usages
harness/harness-core pull request #53480
Opened 2023-09-28 07:21 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 10:30 UTC, vtxorxwitty commented
trigger uts

2023-10-04 06:05 UTC, vtxorxwitty commented
trigger uts

2023-10-04 12:05 UTC, vtxorxwitty commented
trigger uts

2023-10-04 12:56 UTC, vtxorxwitty commented
trigger uts

2023-10-04 13:28 UTC, vtxorxwitty commented
trigger uts

2023-10-05 07:42 UTC, vtxorxwitty commented
trigger uts

2023-10-05 09:45 UTC, vtxorxwitty commented
trigger ut6

2023-10-05 09:45 UTC, vtxorxwitty commented
trigger ut9

2023-10-05 10:44 UTC, vtxorxwitty commented
trigger ut0

2023-10-05 10:47 UTC, vtxorxwitty commented
trigger ut9

2023-10-05 12:29 UTC, sahilhindwani-harness commented
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java` line 46 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-Nfzo3xl4jso4lk2UhR8:-Nfzo3xl4jso4lk2UhR9:b-1v9wwa) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java#L46)):*
> ```Java
>     EntityUsageData usageData;
>     ObjectMapper mapper = (ObjectMapper) jsonParser.getCodec();
>     if (usageType.equals("Pipeline Execution")) {
> ```

I think we should create our own deserialiser over here, rather than using this one.


<!-- Sent from Reviewable.io -->

2023-10-05 12:30 UTC, sahilhindwani-harness commented
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzoFljCwJSc-Yi4SBw:-NfzoFljCwJSc-Yi4SBx:bcyu8ci) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L20)):*
> ```Java
>   private EntityUsageData getUsageData(EntityUsageDetailProto detail) {
>     // populate for specific event types (Eg- Pipeline execution)
>     return PmsEntityUsageDetailData.builder()
> ```

Just curious, why are we keeping it here?


<!-- Sent from Reviewable.io -->

2023-10-05 12:31 UTC, sahilhindwani-harness commented
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/PmsEntityUsageDetailData.java` line 13 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzoRZG6HMBq54UoxQ6:-NfzoRZG6HMBq54UoxQ7:bo8x3ek) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/PmsEntityUsageDetailData.java#L13)):*
> ```Java
> 
> @Builder
> public class PmsEntityUsageDetailData extends EntityUsageData {
> ```

nit: Add codePulse annotation


<!-- Sent from Reviewable.io -->

2023-10-05 12:31 UTC, sahilhindwani-harness commented
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto` line 13 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzoWM07IVlFgpAucnN:-NfzoWM07IVlFgpAucnO:bj7uidi) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto#L13)):*
> ```proto
> 
> message PmsEntityUsageDataProto {
>   string planExecutionId = 1;
> ```

Why is pipeline related information in 970-ng-commons? @tiwaritejas , is this by design?


<!-- Sent from Reviewable.io -->

2023-10-05 12:32 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/PMSSecretsRuntimeUsagesService.java` line 13 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzojFLAe74Ks0MXFMk:-NfzojFLAe74Ks0MXFMl:bsmxqdn) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/PMSSecretsRuntimeUsagesService.java#L13)):*
> ```Java
> import io.harness.observer.Subject;
> 
> public interface PMSSecretsRuntimeUsagesService {
> ```

nit: add annotations


<!-- Sent from Reviewable.io -->

2023-10-05 12:33 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/PMSSecretsRuntimeUsagesServiceImpl.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-Nfzp0lNB9D1G1J2HMpP:-Nfzp0lNB9D1G1J2HMpQ:b-yju60u) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/PMSSecretsRuntimeUsagesServiceImpl.java#L17)):*
> ```Java
> 
> @Singleton
> public class PMSSecretsRuntimeUsagesServiceImpl implements PMSSecretsRuntimeUsagesService {
> ```

Can we rename this to  SecretObserverService and SecretObserverServiceImpl?


<!-- Sent from Reviewable.io -->

2023-10-05 12:35 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzpLro270xejNZzFNZ:-NfzpLro270xejNZzFN_:bc5c6nf) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java#L30)):*
> ```Java
> import java.util.concurrent.ExecutorService;
> 
> public class SecretsRuntimeUsagesEventHandler implements AsyncInformObserver, SecretsRuntimeUsagesObserver {
> ```

nit: Add annotations


<!-- Sent from Reviewable.io -->

2023-10-05 12:35 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java` line 35 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzpPU02I3Cm3qLwXBj:-NfzpPU02I3Cm3qLwXBk:b4gy5t8) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java#L35)):*
> ```Java
>   private final String projectIdentifier = "projectIdentifier";
> 
>   @Inject @Named("EngineExecutorService") ExecutorService executorService;
> ```

Could you please move this file to Pipeline service module rather than orchestration.


<!-- Sent from Reviewable.io -->

2023-10-05 12:36 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 520 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-Nfzpgix8T4Y9DFpjvOI:-Nfzpgix8T4Y9DFpjvOJ:b-sf9f3g) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L520)):*
> ```Java
>     bind(ContainerStepV2PluginProvider.class).to(ContainerStepV2PluginProviderImpl.class);
>     bind(SecretRuntimeUsageService.class).to(SecretRuntimeUsageServiceImpl.class);
>     bind(PMSSecretsRuntimeUsagesService.class).to(PMSSecretsRuntimeUsagesServiceImpl.class);
> ```

I think this should be in OrchestrationModule.


<!-- Sent from Reviewable.io -->

2023-10-05 12:36 UTC, sahilhindwani-harness requested changes
> Reviewed 7 of 11 files at r1, 1 of 3 files at r2, 3 of 10 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, 5 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-05 17:35 UTC, tiwaritejas requested changes

2023-10-05 17:35 UTC, tiwaritejas commented on 970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java
> +    return PmsEntityUsageDetailData.builder()
Let's make this condition based. Else, it will populate PmsEntityUsageDetailData for all other usage types as well.
```
if(detail.usageType == "Pipeline Execution") {
// return PmsEntityUsageDetailData
} else {
return null;
}
```

2023-10-05 17:35 UTC, tiwaritejas commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java
> +                                      .orgIdentifier(AmbianceUtils.getOrgIdentifier(ambiance))
The scope coming from ambiance will be the one of the pipeline, right? The secret meanwhile can belong to the parent scopes as well. We need to capture the secret's scope here.

2023-10-06 09:22 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 23 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53480#gh-1347763335:-Ng3Hm8JBlMYVakW5RJt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L20)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Let's make this condition based. Else, it will populate PmsEntityUsageDetailData for all other usage types as well.
```
if(detail.usageType == "Pipeline Execution") {
// return PmsEntityUsageDetailData
} else {
return null;
}
```
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/PMSSecretsRuntimeUsagesServiceImpl.java` line 17 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-Nfzp0lNB9D1G1J2HMpP:-Ng3HpAYDiTHKYHbrWxH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/PMSSecretsRuntimeUsagesServiceImpl.java#L17)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we rename this to  SecretObserverService and SecretObserverServiceImpl?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-06 09:36 UTC, vtxorxwitty commented on 970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java
> +    return PmsEntityUsageDetailData.builder()
Done

2023-10-08 22:14 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 24 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java` line 46 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-Nfzo3xl4jso4lk2UhR8:-NgGLJrpAzgcPE17FhJ8:b-d53ytp) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java#L46)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think we should create our own deserialiser over here, rather than using this one.
</blockquote></details>

Discussed over the call. Necessary action items will be taken by the framework team after considering the refactoring effort.
___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzoFljCwJSc-Yi4SBw:-NgGLbFhA2RHM2ACJfh9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L20)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Just curious, why are we keeping it here?
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto` line 13 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzoWM07IVlFgpAucnN:-NgGLdcW4fe2lgJoqgGK:b-d53ytp) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto#L13)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Why is pipeline related information in 970-ng-commons? @tiwaritejas , is this by design?
</blockquote></details>

Discussed over the call. Necessary action items will be taken by the framework team after considering the refactoring effort.
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 520 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-Nfzpgix8T4Y9DFpjvOI:-NgGLll-7uAZVs6CI3b1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L520)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think this should be in OrchestrationModule.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java` line 35 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzpPU02I3Cm3qLwXBj:-NgGLnqc9VLvWYLtJ8_j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java#L35)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Could you please move this file to Pipeline service module rather than orchestration.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java` line 54 at r7](https://reviewable.io/reviews/harness/harness-core/53480#gh-1347768626:-NgGLpko2PNxhFmBxaZo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets/SecretsRuntimeUsagesEventHandler.java#L54)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

The scope coming from ambiance will be the one of the pipeline, right? The secret meanwhile can belong to the parent scopes as well. We need to capture the secret's scope here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-08 22:57 UTC, vtxorxwitty commented
trigger uts

2023-10-09 06:56 UTC, vtxorxwitty commented
trigger uts

2023-10-09 10:55 UTC, vtxorxwitty commented
trigger uts

2023-10-09 12:40 UTC, vtxorxwitty commented
trigger uts

2023-10-09 15:11 UTC, vtxorxwitty commented
trigger ut7

2023-10-09 16:21 UTC, tiwaritejas submitted a review, later dismissed

2023-10-10 04:53 UTC, sahilhindwani-harness commented
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto` line 13 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzoWM07IVlFgpAucnN:-NgMve9hBHUXSsC29Jyi:bh4ch9i) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto#L13)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

Discussed over the call. Necessary action items will be taken by the framework team after considering the refactoring effort.
</blockquote></details>

Can you please create tickets for the action items?


<!-- Sent from Reviewable.io -->

2023-10-10 04:54 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationEventsFrameworkModule.java` line 71 at r12](https://reviewable.io/reviews/harness/harness-core/53480#-NgMvlkx1D4ckKV--geX:-NgMvlkx1D4ckKV--geY:braywzf) ([raw file](https://github.com/harness/harness-core/blob/e4a7085c593dbe4055e5c4e78f6a737c56a4d3f9/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationEventsFrameworkModule.java#L71)):*
> ```Java
>           .annotatedWith(Names.named(ORCHESTRATION_LOG))
>           .toInstance(NoOpProducer.of(EventsFrameworkConstants.DUMMY_TOPIC_NAME));
>       bind(Producer.class)
> ```

This producer should be in pipeline service module


<!-- Sent from Reviewable.io -->

2023-10-10 04:55 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java` line 188 at r12](https://reviewable.io/reviews/harness/harness-core/53480#-NgMvzoYC07dnwmnlmf9:-NgMvzoYC07dnwmnlmfA:b-ilok6b) ([raw file](https://github.com/harness/harness-core/blob/e4a7085c593dbe4055e5c4e78f6a737c56a4d3f9/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java#L188)):*
> ```Java
>     taskExecutorMap.addBinding(TaskCategory.DELEGATE_TASK_V2).to(NgDelegate2TaskExecutor.class);
> 
>     bind(SecretRuntimeUsageService.class).to(SecretRuntimeUsageServiceImpl.class);
> ```

secretRuntimeUsageService binding should be on pipeline-service and not in orchestrationModule.


<!-- Sent from Reviewable.io -->

2023-10-10 04:56 UTC, sahilhindwani-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 25 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-10 05:37 UTC, vtxorxwitty commented
trigger uts

2023-10-10 07:04 UTC, vtxorxwitty commented
trigger ut1

2023-10-10 07:05 UTC, vtxorxwitty commented
trigger ut5

2023-10-10 07:05 UTC, vtxorxwitty commented
trigger ut7

2023-10-10 07:53 UTC, vtxorxwitty commented
trigger ut7

2023-10-10 07:58 UTC, vtxorxwitty commented
trigger ut1

2023-10-10 07:58 UTC, vtxorxwitty commented
trigger ut5

2023-10-10 08:05 UTC, vtxorxwitty commented
trigger ut1

2023-10-10 09:13 UTC, vtxorxwitty commented
trigger ut5

2023-10-10 09:30 UTC, vtxorxwitty commented
trigger ut5

2023-10-10 10:42 UTC, vtxorxwitty commented
trigger ut5

2023-10-10 12:23 UTC, tiwaritejas submitted a review, later dismissed

2023-10-10 13:23 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 44 at r13](https://reviewable.io/reviews/harness/harness-core/53480#-NgOkJ-FEpAqrG_iVQtQ:-NgOkJ-FEpAqrG_iVQtR:b-q5iq3v) ([raw file](https://github.com/harness/harness-core/blob/23ffe586d4f5ccc4440319178a739810bc6dd709/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L44)):*
> ```Java
>   private final String projectIdentifier = "projectIdentifier";
> 
>   @Inject @Named("EngineExecutorService") ExecutorService executorService;
> ```

please change the name of this executor service 
Use PipelineExecutorService


<!-- Sent from Reviewable.io -->

2023-10-10 13:23 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 51 at r13](https://reviewable.io/reviews/harness/harness-core/53480#-NgOkRT43WtDkAv2WBaS:-NgOkRT43WtDkAv2WBaT:bb2klr0) ([raw file](https://github.com/harness/harness-core/blob/23ffe586d4f5ccc4440319178a739810bc6dd709/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L51)):*
> ```Java
>     Ambiance ambiance = secretObserverInfo.getAmbiance();
> 
>     IdentifierRefProtoDTO identifierRefProtoDTO =
> ```

Can we wrap this under FF?


<!-- Sent from Reviewable.io -->

2023-10-10 13:23 UTC, sahilhindwani-harness requested changes
> Reviewed 7 of 17 files at r8, 5 of 11 files at r9, 1 of 3 files at r10, 4 of 5 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 25 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-10 17:20 UTC, vtxorxwitty commented
trigger uts

2023-10-10 19:47 UTC, vtxorxwitty commented
trigger uts

2023-10-10 20:29 UTC, vtxorxwitty commented
trigger uts

2023-10-10 22:28 UTC, vtxorxwitty commented
trigger uts

2023-10-11 05:06 UTC, vtxorxwitty commented
trigger ut2

2023-10-11 05:07 UTC, vtxorxwitty commented
trigger ut6

2023-10-11 05:39 UTC, archit-harness requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 27 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 19 at r15](https://reviewable.io/reviews/harness/harness-core/53480#-NgSB0lj6oSzXjUx7Gk6:-NgSB0lj6oSzXjUx7Gk7:b-8xc3u3) ([raw file](https://github.com/harness/harness-core/blob/e3c438d1d23ce51a40eef7971a029c0ec7eafa70/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L19)):*
> ```Java
> 
>   private EntityUsageData getUsageData(EntityUsageDetailProto detail) {
>     if (detail.getUsageType().equals("Pipeline Execution")) {
> ```

how we are populating Pipeline Execution?



_Code quote:_
```Java
detail.getUsageType().equals("Pipeline Execution"
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 67 at r15](https://reviewable.io/reviews/harness/harness-core/53480#-NgSEf_8EDCr5QjB7Rx1:-NgSBUZs820hnEEiHjn0:b-ivormf) ([raw file](https://github.com/harness/harness-core/blob/e3c438d1d23ce51a40eef7971a029c0ec7eafa70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L67)):*
> ```Java
>     EntityUsageDetailProto entityUsageDetail =
>         EntityUsageDetailProto.newBuilder()
>             .setUsageType("Pipeline Execution")
> ```

@tiwaritejas how we are deciding which usageType we should pass?
Shouldnt this be a constant class in some common util which everyone should refer? as i think its a contract with ng manager isn't?



_Code quote:_
```Java
Pipeline Execution
```


<!-- Sent from Reviewable.io -->

2023-10-11 06:23 UTC, vtxorxwitty commented
trigger ut2

2023-10-11 11:30 UTC, vtxorxwitty commented
trigger uts

2023-10-11 13:54 UTC, vtxorxwitty commented
trigger ut6, ut7, ut9

2023-10-27 07:49 UTC, sahilhindwani-harness commented on 970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java
> -    usageData = mapper.readValue(dataNode.toString(), EntityUsageData.class);
will be removed

2023-10-27 07:49 UTC, sahilhindwani-harness commented on 970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java
> -    // populate for specific event types (Eg- Pipeline execution)
All 3 in this package to be removed.

2023-10-27 10:30 UTC, vtxorxwitty commented
trigger uts

2023-10-27 10:34 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 27 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java` line 0 at r16](https://reviewable.io/reviews/harness/harness-core/53480#gh-1374197732:-Nhkgn6PCJMPvephUUvc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fba9c2e045da7d060ada91ca79a21572f7446f0b/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java#L0)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/harness/harness-core/pull/53480#discussion_r1374197732) to the right spot — sorry!)*

will be removed
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 19 at r15](https://reviewable.io/reviews/harness/harness-core/53480#-NgSB0lj6oSzXjUx7Gk6:-NhkgoLY8XoMt0U_cWd0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e3c438d1d23ce51a40eef7971a029c0ec7eafa70/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

how we are populating Pipeline Execution?
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 0 at r16](https://reviewable.io/reviews/harness/harness-core/53480#gh-1374198239:-Nhkgosx9m5XO2wyAiX8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fba9c2e045da7d060ada91ca79a21572f7446f0b/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L0)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/harness/harness-core/pull/53480#discussion_r1374198239) to the right spot — sorry!)*

All 3 in this package to be removed.
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto` line 13 at r7](https://reviewable.io/reviews/harness/harness-core/53480#-NfzoWM07IVlFgpAucnN:-NhkgpUD2rs6vEGpP3bM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/32bcf12c9b0aaffa5d99701a6a10c80cbb9f3f4c/970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/pms_entity_usage_data.proto#L13)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can you please create tickets for the action items?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationEventsFrameworkModule.java` line 71 at r12](https://reviewable.io/reviews/harness/harness-core/53480#-NgMvlkx1D4ckKV--geX:-NhkgqgW816HHj83BcVJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e4a7085c593dbe4055e5c4e78f6a737c56a4d3f9/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationEventsFrameworkModule.java#L71)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This producer should be in pipeline service module
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java` line 188 at r12](https://reviewable.io/reviews/harness/harness-core/53480#-NgMvzoYC07dnwmnlmf9:-NhkgrIL6bJqtqPn40tB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e4a7085c593dbe4055e5c4e78f6a737c56a4d3f9/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java#L188)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

secretRuntimeUsageService binding should be on pipeline-service and not in orchestrationModule.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 44 at r13](https://reviewable.io/reviews/harness/harness-core/53480#-NgOkJ-FEpAqrG_iVQtQ:-NhkgjmsEerfPc081dSx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c2f91db81eab5a802d235a97c22f90beae02ff3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L44)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

please change the name of this executor service 
Use PipelineExecutorService
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 51 at r13](https://reviewable.io/reviews/harness/harness-core/53480#-NgOkRT43WtDkAv2WBaS:-NhkgkXi9lzAQDQZC2jB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c2f91db81eab5a802d235a97c22f90beae02ff3/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L51)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we wrap this under FF?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 67 at r15](https://reviewable.io/reviews/harness/harness-core/53480#-NgSEf_8EDCr5QjB7Rx1:-Nhkglay7OF8mFPbtRLm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e3c438d1d23ce51a40eef7971a029c0ec7eafa70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@tiwaritejas how we are deciding which usageType we should pass?
Shouldnt this be a constant class in some common util which everyone should refer? as i think its a contract with ng manager isn't?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-27 10:36 UTC, vtxorxwitty commented on 970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java
> -    usageData = mapper.readValue(dataNode.toString(), EntityUsageData.class);
done

2023-10-27 11:19 UTC, archit-harness requested changes
> Reviewed 3 of 17 files at r8, 2 of 5 files at r14, 4 of 8 files at r16, 4 of 14 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 24 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 67 at r15](https://reviewable.io/reviews/harness/harness-core/53480#-NgSEf_8EDCr5QjB7Rx1:-Nhkqu52CUzMoMQsa3xF:bufoomr) ([raw file](https://github.com/harness/harness-core/blob/e3c438d1d23ce51a40eef7971a029c0ec7eafa70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L67)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can we remove usageType, now its used for what?


<!-- Sent from Reviewable.io -->

2023-10-30 04:33 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 67 at r15](https://reviewable.io/reviews/harness/harness-core/53480#-NgSEf_8EDCr5QjB7Rx1:-NhyqlhL9mu_gxCJvumn:blvvpyf) ([raw file](https://github.com/harness/harness-core/blob/e3c438d1d23ce51a40eef7971a029c0ec7eafa70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we remove usageType, now its used for what?
</blockquote></details>

Can we use EntityUsageTypes.PIPELINE_EXECUTION here?


<!-- Sent from Reviewable.io -->

2023-10-30 04:46 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 24 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java` line 67 at r15](https://reviewable.io/reviews/harness/harness-core/53480#-NgSEf_8EDCr5QjB7Rx1:-Nhytv1GCX4buzJv4AnJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e3c438d1d23ce51a40eef7971a029c0ec7eafa70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/SecretResolutionEventHandler.java#L67)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we use EntityUsageTypes.PIPELINE_EXECUTION here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 05:28 UTC, vtxorxwitty commented
trigger uts

2023-10-31 07:06 UTC, sahilhindwani-harness approved these changes
> Reviewed 2 of 5 files at r14, 5 of 8 files at r16, 13 of 14 files at r17, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 14 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-31 07:35 UTC, archit-harness approved these changes
> Reviewed 1 of 3 files at r10, 1 of 5 files at r12, 1 of 4 files at r13, 1 of 8 files at r16, 9 of 14 files at r17, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53480)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-31 07:36 UTC, vtxorxwitty commented
trigger review

2023-10-31 07:38 UTC, merged