fix: [CDS-79153]: Using V2 feature flag enum instead of existing one
harness/harness-core pull request #53483
Opened 2023-09-28 08:20 UTC by abhinavmittal-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-29 08:28 UTC, Abhishek-CDC commented on 400-rest/src/main/java/software/wings/helpers/ext/account/DeleteAccountHelper.java
>        findOptions.readPreference(ReadPreference.secondaryPreferred());
how we are deciding v1 and v2 FF usage?

2023-09-29 09:15 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/software/wings/helpers/ext/account/DeleteAccountHelper.java
>        findOptions.readPreference(ReadPreference.secondaryPreferred());
There were some optimisations that were done last week
Those are being moved to v2

2023-09-29 12:37 UTC, rafaelmart1ns approved these changes

2023-09-29 13:30 UTC, abhinavmittal-harness commented
trigger uts

2023-09-29 16:45 UTC, lasdox approved these changes

2023-09-29 19:53 UTC, sribalij commented on 400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java
> +    if (featureFlagService.isEnabled(CDS_QUERY_OPTIMIZATION, accountId)) {
Can we add some JUnits around the FFs? It'll help us when we remove or update them

2023-09-29 19:53 UTC, sribalij requested changes
Can we add some JUnits around the FFs? It'll help us when we remove or update them

2023-09-29 20:51 UTC, sribalij commented on 400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java
> +    if (featureFlagService.isEnabled(CDS_QUERY_OPTIMIZATION, accountId)) {
Also a ticket to track the FF to remove

2023-10-02 21:24 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java
> +    if (featureFlagService.isEnabled(CDS_QUERY_OPTIMIZATION, accountId)) {
I will create a separate pr for that if it is okay. (As this change is just reverting a commit we did where we were removing this from code and we have decided not remove things from current gen)
Also Considering we want to hotfix changes to qa.
@sribalij

2023-10-02 21:30 UTC, abhinavmittal-harness commented on 400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java
> +    if (featureFlagService.isEnabled(CDS_QUERY_OPTIMIZATION, accountId)) {
Also we won't be removing these feature flags

2023-10-02 21:46 UTC, abhinavmittal-harness commented
trigger commonchecks

2023-10-02 23:06 UTC, sribalij commented on 400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java
> +    if (featureFlagService.isEnabled(CDS_QUERY_OPTIMIZATION, accountId)) {
Sure. This sounds good @abhinavmittal-harness.

2023-10-02 23:07 UTC, sribalij approved these changes

2023-10-03 05:30 UTC, naman-goenka approved these changes

2023-10-03 06:20 UTC, abhinavmittal-harness commented
trigger ut6

2023-10-03 06:22 UTC, abhinavmittal-harness commented
trigger pmd

2023-10-03 06:23 UTC, abhinavmittal-harness commented
trigger codebasehash

2023-10-03 07:09 UTC, merged