feat: [CDS-80410]: support type "http" for Http step and create HttpStepInfoV1
harness/harness-core pull request #53496
Opened 2023-09-28 11:23 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-29 06:15 UTC, archit-harness reviewed
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53496)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-06 07:51 UTC, utkarshchoubey-harness requested changes

2023-10-06 07:51 UTC, utkarshchoubey-harness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HTTPStepVariableCreatorV1.java
> +public class HTTPStepVariableCreatorV1 extends GenericStepVariableCreator<HttpStepNode> {
shouldn't this be HttpStepNodeV1 ?

2023-10-06 10:53 UTC, hextechpal reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53496)* status: 8 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HTTPStepVariableCreatorV1.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/53496#gh-1348370767:-Ng3bXHx3RDM6xyHykLj:b-8asjoj) ([raw file](https://github.com/harness/harness-core/blob/baa38c65a8d8499aa7c7043a3250de2688c7c10e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HTTPStepVariableCreatorV1.java#L20)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

shouldn't this be HttpStepNodeV1 ?
</blockquote></details>

@archit-harness @shalini-agr should we change our variable creator too to follow the plan creator route and expect yaml rather than POJOs


<!-- Sent from Reviewable.io -->

2023-10-09 12:12 UTC, archit-harness requested changes
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53496)* status: 17 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepInfoV1.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/53496#-NfQbzxY3n443nUxf2Um:-NgJKnyD3RrbqxIEcvJE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/12f3354bd718d753c0d48a6c934c401e75170c30/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/http/v1/HttpStepInfoV1.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why ng variable ?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HTTPStepVariableCreatorV1.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/53496#gh-1348370767:-NgJKvQ-AXykBnrdGRa4:bnaqhjw) ([raw file](https://github.com/harness/harness-core/blob/baa38c65a8d8499aa7c7043a3250de2688c7c10e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1/HTTPStepVariableCreatorV1.java#L20)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

@archit-harness @shalini-agr should we change our variable creator too to follow the plan creator route and expect yaml rather than POJOs
</blockquote></details>

@hextechpal yes we will do that, @shalini-agr can you change this, but just FYI -> we are planning once we have resource to remove variables creators all together
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/53496#-NgJLDCgBO7c1k2VcD0M:-NgJLDCgBO7c1k2VcD0N:b-2cc6vt) ([raw file](https://github.com/harness/harness-core/blob/69ffc99f436535a811b88dbc168fdbca0ec17172/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L46)):*
> ```Java
> 
> @Slf4j
> public class HttpStepUtils {
> ```

add codepulse annotation


<!-- Sent from Reviewable.io -->

2023-10-10 09:34 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53496)* status: 17 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-10 10:01 UTC, shalini-agr commented
trigger uts

2023-10-10 10:14 UTC, shalini-agr commented
trigger uts

2023-10-10 10:22 UTC, archit-harness reviewed
> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53496)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-10 10:23 UTC, utkarshchoubey-harness approved these changes

2023-10-10 10:45 UTC, shalini-agr commented
trigger uts

2023-10-10 11:03 UTC, archit-harness approved these changes
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53496)* status: 22 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-10 11:26 UTC, shalini-agr commented
trigger uts

2023-10-10 11:46 UTC, shalini-agr commented
trigger ut8

2023-10-10 12:02 UTC, archit-harness approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53496)* status: 26 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-10-10 12:02 UTC, shalini-agr commented
trigger review

2023-10-10 12:05 UTC, merged