[feat]: [CDS-80440]: Merging v0 and v1 templates inside the v1 pipeline
harness/harness-core pull request #53499
Opened 2023-09-28 11:57 UTC by brijeshdhakar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 06:38 UTC, shalini-agr commented
trigger uts

2023-10-03 07:02 UTC, archit-harness requested changes
> Reviewed 2 of 13 files at r1, 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateRefHelper.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoIBtQ4ymHjVFPpotk:-NfoIBtQ4ymHjVFPpotl:bir3adg) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateRefHelper.java#L67)):*
> ```Java
>         FQNNode secondLastNode = fqnList.get(fqnList.size() - 2);
>         if ((YAMLFieldNameConstants.TYPE.equals(fqnList.get(fqnList.size() - 1).getKey())
>                 && YAMLFieldNameConstants.TEMPLATE.equals(((JsonNode) fqnObjectMap.get(key)).asText()))
> ```

is this for v1? 
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoIMyE0-85cmiGrltS:-NfoIMyE0-85cmiGrltT:b-cps1i3) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L51)):*
> ```Java
>     Map<String, YamlField> dependencies = new HashMap<>();
>     YamlField stagesYamlNode;
>     // yaml will start with stages when a v1 template is linked with pipeline
> ```

with v0 pipeline, share a basic yaml as well, plus i think we should move into a private method to return stagesYamlNode
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoI_IT4US-UyVJy94l:-NfoI_IT4US-UyVJy94m:bf3tjfi) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L87)):*
> ```Java
>       String yaml, boolean checkForTemplateAccess, boolean getMergedTemplateWithTemplateReferences,
>       String loadFromCache) {
>     // TODO(BRIJESH): Pass the yamlVersion from caller instead of hardcoded value HarnessYamlVersion.V0. This flow is
> ```

i think todo is not required if apis calling are v0, if those are generic then we can
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 576 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJAzXDNJ0hnUIzxo5:-NfoJAzXDNJ0hnUIzxo6:b-klz3ed) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L576)):*
> ```Java
>         // If v1 pipeline has a pipeline template linked to it, the root node of processedYaml will be stages in case of
>         // v1 template and the yaml will have v0 structure in case of v0 template
>         String version = NGYamlHelper.getVersionFromProcessedYaml(planExecutionMetadata.getProcessedYaml());
> ```

is there a way template service calculates and sends this info back?



_Code quote:_
```Java
NGYamlHelper.getVersionFromProcessedYaml(planExecutionMetadata.getProcessedYaml());
```
___
*[`template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJML0AtAJDZKEFLU0:-NfoJML0AtAJDZKEFLU1:bb6sgh5) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java#L123)):*
> ```Java
>     if (TemplateRefHelper.hasTemplateRef(yaml)) {
>       Map<String, Object> resolvedTemplatesMap = templateMergeServiceHelper.mergeTemplateInputsInObject(accountId,
>           orgId, projectId, yamlNode, templateCacheMap, 0, loadFromCache, false, NGYamlHelper.getVersion(yaml));
> ```

instead of reading from yaml again and again, can caller pass this?
___
*[`template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 241 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJR8hExbH-PynMa68:-NfoJR8hExbH-PynMa69:b-8lctex) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java#L241)):*
> ```Java
>     // Template YAML corresponding to the TemplateRef and Version Label
>     TemplateEntityGetResponse templateEntityGetResponse = templateMergeServiceHelper.getLinkedTemplateEntity(
>         accountId, orgId, projectId, templateNodeValue, templateCacheMap, loadFromCache, HarnessYamlVersion.V0);
> ```

is this called currently only from v0?
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJTFM7Zc4mlglzdDH:-NfoJTFM7Zc4mlglzdDI:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L86)):*
> ```Java
>     if (TemplateRefHelper.hasTemplateRef(yaml)) {
>       Map<String, Object> resolvedTemplatesMap = templateMergeServiceHelper.mergeTemplateInputsInObject(accountId,
>           orgId, projectId, yamlNode, templateCacheMap, 0, loadFromCache, false, NGYamlHelper.getVersion(yaml));
> ```

same as above
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoK7jN03O5gbZUksGp:-NfoK7jN03O5gbZUksGq:b-bimqnv) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L174)):*
> ```Java
>   }
> 
>   public boolean isTemplatePresentV0OrV1(String fieldName, JsonNode templateValue, JsonNode jsonNode) {
> ```

i dont think we should append V0OrV1 here -> it would mean any template, you can add comment to method for more clarity
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 184 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoK5ze5ZEBNsKWdLPf:-NfoK5ze5ZEBNsKWdLPg:b-mlogmt) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L184)):*
> ```Java
>   }
> 
>   public boolean isTemplatePresentV1(JsonNode jsonNode) {
> ```

rename to isV1TemplatePresent?
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 187 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoKJc75Xh1iNABMGLD:-NfoKJc75Xh1iNABMGLE:b-t7s57i) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L187)):*
> ```Java
>     return (jsonNode.has(YAMLFieldNameConstants.TYPE)
>                && YAMLFieldNameConstants.TEMPLATE.equals(jsonNode.get(YAMLFieldNameConstants.TYPE).asText()))
>         || (jsonNode.has(YAMLFieldNameConstants.SPEC) && jsonNode.get(YAMLFieldNameConstants.SPEC).has("ref"));
> ```

use constant
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoKcz56IEBu3eUIloa:-NfoKcz56IEBu3eUIlob:b-pmgae8) ([raw file](https://git [...]

2023-10-03 13:09 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 16 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateRefHelper.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoIBtQ4ymHjVFPpotk:-NfoLQHU9DBjv38BIQpi:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateRefHelper.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is this for v1?
</blockquote></details>

yes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoI_IT4US-UyVJy94l:-NfoVKkE-RTVPUbv3hZu:bedicx5) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L87)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think todo is not required if apis calling are v0, if those are generic then we can
</blockquote></details>

this part of code would be common to both
___
*[`template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJML0AtAJDZKEFLU0:-NfpRaovEAM65CiAe2v9:b-h3kblf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java#L123)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead of reading from yaml again and again, can caller pass this?
</blockquote></details>

fixed to v0 for now
___
*[`template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 241 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJR8hExbH-PynMa68:-NfolOsF13w28a8F4cor:b96pzxu) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/InputsValidator.java#L241)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is this called currently only from v0?
</blockquote></details>

currently, yes
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJTFM7Zc4mlglzdDH:-NfpRmnV0ZJvapA8LX7Z:b-h3kblf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L86)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

fixed to v0 for now
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoK7jN03O5gbZUksGp:-NfoQUrF-o35ngLhntJR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L174)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont think we should append V0OrV1 here -> it would mean any template, you can add comment to method for more clarity
</blockquote></details>

done
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 184 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoK5ze5ZEBNsKWdLPf:-NfoPDHk6ntcft1SB6FA:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L184)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to isV1TemplatePresent?
</blockquote></details>

done
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 187 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoKJc75Xh1iNABMGLD:-NfoPCoN-i__uPm-rDSy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L187)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use constant
</blockquote></details>

done
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoKcz56IEBu3eUIloa:-NfpRpm5EybjNLxLeKkZ:b-ink2l) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L280)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets discuss this once
</blockquote></details>

changed this to pair as discussed
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoKo-i5UPIkPAnBBuR:-NfoO8Io22u--05GCpQh:b-phpggs) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L315)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this condition?
</blockquote></details>

in case of v0 templates, while merging we need to add the type name in the yaml, like step: , stage: , pipeline, etc.
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 905 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJj9l4YxQAVNTAok8:-NfoNypf3THZGDPYQwdI:b-kuq5xv) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L905)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we need different variable marker ?
</blockquote></details>

we are setting it to the version mentioned in the yaml if it is present


<!-- Sent from Reviewable.io -->

2023-10-03 13:14 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoIMyE0-85cmiGrltS:-NfpeIum6w1rC6Gey6KE:b-uxgzfz) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

with v0 pipeline, share a basic yaml as well, plus i think we should move into a private method to return stagesYamlNode
</blockquote></details>

moved to private method


<!-- Sent from Reviewable.io -->

2023-10-03 13:26 UTC, archit-harness requested changes
> Reviewed 2 of 13 files at r1, 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/NGYamlHelper.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-Nfpgaw5BKMQ3VEOnafk:-Nfpgaw69DcxXr5wrN52:b-7fzhty) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/953-yaml-commons/src/main/java/io/harness/pms/yaml/NGYamlHelper.java#L46)):*
> ```Java
>   }
> 
>   public String getVersionFromProcessedYaml(String yaml) {
> ```

can we rename this to getVersionFromProcessedPipelineYaml? because this method is specific to pipeline yaml only, plus we should check if kind is of type pipeline else return version defined in yaml
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 65 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-NfpgygcCzaKT3GRNnQX:-NfpgygcCzaKT3GRNnQY:b-ovnrcy) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L65)):*
> ```Java
>     YamlField stagesYamlNode;
>     // yaml will start with stages when a v1 template is linked with pipeline
>     if (config.getNode().getCurrJsonNode().has(YAMLFieldNameConstants.SPEC)) {
> ```

as we discussed, this planCreator will always receive spec isn't?
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-NfphRr89obdsBEFPlUE:-NfphRr89obdsBEFPlUF:bwaijwv) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L109)):*
> ```Java
> 
>       // If Template is present, Refresh the Template Inputs
>       if (templateMergeServiceHelper.isV0TemplatePresent(fieldName, value)) {
> ```

why this is checking only for v0?
___
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java` line 436 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-Nfphpf11qrnJ-DB37zS:-Nfphpf11qrnJ-DB37zT:b-arv47t) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java#L436)):*
> ```Java
>       TemplateUtils.setUserFlowContext(USER_FLOW.EXECUTION);
>     }
>     String yamlVersion = templateApplyRequestDTO.getYamlVersion();
> ```

does this request dto has base method if not version send, then consider as v0?


<!-- Sent from Reviewable.io -->

2023-10-03 13:26 UTC, archit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoL1tm5l-DLHlhkUTo:-NfphxTf4JT2gtFsTAlX:b-ly7yfd) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L85)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should calculating version again and again
</blockquote></details>

we should not*


<!-- Sent from Reviewable.io -->

2023-10-04 05:21 UTC, shalini-agr commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/NGYamlHelper.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-Nfpgaw5BKMQ3VEOnafk:-Nft-knZDj5-dbk0K3Vg:bdhk3tj) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/953-yaml-commons/src/main/java/io/harness/pms/yaml/NGYamlHelper.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename this to getVersionFromProcessedPipelineYaml? because this method is specific to pipeline yaml only, plus we should check if kind is of type pipeline else return version defined in yaml
</blockquote></details>

this method is not needed anymore


<!-- Sent from Reviewable.io -->

2023-10-04 05:21 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 65 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-NfpgygcCzaKT3GRNnQX:-Nfstx4vDSuZ7LO_AqXV:b-5g9o7c) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as we discussed, this planCreator will always receive spec isn't?
</blockquote></details>

yes, done


<!-- Sent from Reviewable.io -->

2023-10-04 05:21 UTC, shalini-agr commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 576 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoJAzXDNJ0hnUIzxo5:-Nft-oxa81dM1I5pJmM1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L576)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

is there a way template service calculates and sends this info back?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-04 05:21 UTC, shalini-agr commented
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-NfphRr89obdsBEFPlUE:-Nfsly7a0_WCyYTGGzZ8:b-aq6dzv) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L109)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this is checking only for v0?
</blockquote></details>

this flow isn't implemented for v1 yet, this change is visible because of the method rename


<!-- Sent from Reviewable.io -->

2023-10-04 05:24 UTC, shalini-agr commented
*[`template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoL1tm5l-DLHlhkUTo:-Nft0DnW52oqFcbmOG22:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/template-service/service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L85)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not*
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-04 05:25 UTC, shalini-agr commented
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java` line 436 at r4](https://reviewable.io/reviews/harness/harness-core/53499#-Nfphpf11qrnJ-DB37zS:-NfsmqVW7STaHG80g3F2:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f4e41769a477cbe54642286cfa30265e77c54c02/template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java#L436)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

does this request dto has base method if not version send, then consider as v0?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-04 05:41 UTC, shalini-agr commented
trigger uts

2023-10-04 07:21 UTC, archit-harness requested changes
> Reviewed 1 of 13 files at r1, 12 of 15 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 22 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 88 at r7](https://reviewable.io/reviews/harness/harness-core/53499#-NftYLI35LkzapYRSG6E:-NftYLI35LkzapYRSG6F:b3f8upv) ([raw file](https://github.com/harness/harness-core/blob/d99ad8c56cfab6e84f9b6112c6b5e8c0f0d21f4c/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L88)):*
> ```Java
>               .mergeTemplateInputsInObject(accountId, orgId, projectId, yamlNode, templateCacheMap, 0, loadFromCache,
>                   false, HarnessYamlVersion.V0)
>               .getResMap();
> ```

we should use overload the method 
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 326 at r7](https://reviewable.io/reviews/harness/harness-core/53499#-NftYrCXBNDcTFDJx11W:-NftYrCXBNDcTFDJx11X:bq8p0mx) ([raw file](https://github.com/harness/harness-core/blob/d99ad8c56cfab6e84f9b6112c6b5e8c0f0d21f4c/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L326)):*
> ```Java
>             .build();
>       } else {
>         if (templateEntity.getTemplateEntityType() == TemplateEntityType.PIPELINE_TEMPLATE) {
> ```

as discussed we should remove this and add todo


<!-- Sent from Reviewable.io -->

2023-10-04 07:45 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 23 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateRefHelper.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/53499#-NfoIBtQ4ymHjVFPpotk:-NftbQQL-ZR7S-GArrNy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1b2c48343fee1b20f4dfd7a3551a1c1190fcab41/953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateRefHelper.java#L67)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

yes
</blockquote></details>

done
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 88 at r7](https://reviewable.io/reviews/harness/harness-core/53499#-NftYLI35LkzapYRSG6E:-NftahuZ07feRK2uF0Kt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d99ad8c56cfab6e84f9b6112c6b5e8c0f0d21f4c/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L88)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should use overload the method
</blockquote></details>

done
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 326 at r7](https://reviewable.io/reviews/harness/harness-core/53499#-NftYrCXBNDcTFDJx11W:-NftcGIJCOhyRyTh89R8:b-fz9e0w) ([raw file](https://github.com/harness/harness-core/blob/d99ad8c56cfab6e84f9b6112c6b5e8c0f0d21f4c/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L326)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed we should remove this and add todo
</blockquote></details>

done TODO added in FQNMapGenerator


<!-- Sent from Reviewable.io -->

2023-10-04 07:50 UTC, shalini-agr commented
trigger uts

2023-10-04 09:41 UTC, shalini-agr commented
trigger uts

2023-10-05 04:24 UTC, shalini-agr commented
trigger uts

2023-10-05 05:57 UTC, archit-harness requested changes
> Reviewed 3 of 6 files at r8, 6 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 25 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java` line 68 at r10](https://reviewable.io/reviews/harness/harness-core/53499#-NfyM27g4EPqjWMBURBW:-NfyM27g4EPqjWMBURBX:bz3knc4) ([raw file](https://github.com/harness/harness-core/blob/173a1922ac822bce8dadc3fbb3f8a8f762fc09a0/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java#L68)):*
> ```Java
>       FQN currentFQN = FQN.builder().fqnList(Collections.singletonList(startNode)).build();
> 
>       if (fqnMap.containsKey(currentFQN)) {
> ```

can we discuss this?
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 326 at r7](https://reviewable.io/reviews/harness/harness-core/53499#-NftYrCXBNDcTFDJx11W:-NfyPQdR6rHJZveVYhRG:b-pmgae8) ([raw file](https://github.com/harness/harness-core/blob/d99ad8c56cfab6e84f9b6112c6b5e8c0f0d21f4c/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L326)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

done TODO added in FQNMapGenerator
</blockquote></details>

lets discuss this once


<!-- Sent from Reviewable.io -->

2023-10-05 07:46 UTC, archit-harness reviewed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 26 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java` line 68 at r10](https://reviewable.io/reviews/harness/harness-core/53499#-NfyM27g4EPqjWMBURBW:-NfykcBzByS8viD8T5mk:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/173a1922ac822bce8dadc3fbb3f8a8f762fc09a0/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we discuss this?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-05 08:07 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 26 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 326 at r7](https://reviewable.io/reviews/harness/harness-core/53499#-NftYrCXBNDcTFDJx11W:-NfysBNe9KFr-LCDlXbk:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d99ad8c56cfab6e84f9b6112c6b5e8c0f0d21f4c/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L326)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets discuss this once
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-05 09:39 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53499)* status: 26 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-05 09:42 UTC, mohitg0795 approved these changes

2023-10-05 09:43 UTC, merged