feat: [CDS-80410]: support type "shell-script" for ShellScript step and create ShellScriptStepInfoV1
harness/harness-core pull request #53506
Opened 2023-09-28 13:47 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-05 13:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53506) before we can accept your contribution.<br/>**23** out of **24** committers have signed the CLA.<br/><br/>:white_check_mark: vigneswara-propelo<br/>:white_check_mark: meenakshi-harness<br/>:white_check_mark: archit-harness<br/>:white_check_mark: vikyathharekal<br/>:white_check_mark: sandeshsalunkhegh<br/>:white_check_mark: abhinavsingh1196<br/>:white_check_mark: PragyeshMishra01<br/>:white_check_mark: laura-mannus<br/>:white_check_mark: vanshBhatia-A4k9<br/>:white_check_mark: tphoney<br/>:white_check_mark: sahibaHarness<br/>:white_check_mark: brijeshdhakar<br/>:white_check_mark: GoelPratyush99<br/>:white_check_mark: bharatgoelharness<br/>:white_check_mark: abhinavsingh-ccm<br/>:white_check_mark: utkarshchoubey-harness<br/>:white_check_mark: adivishy1<br/>:white_check_mark: Fernando-Dourado<br/>:white_check_mark: raghavharness<br/>:white_check_mark: acasian-harness<br/>:white_check_mark: arya-harness<br/>:white_check_mark: shalini-agr<br/>:white_check_mark: vcalasansh<br/>:x: sahithibanda01<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53506) it.</sub>

2023-10-11 05:52 UTC, archit-harness requested changes
> Reviewed 2 of 22 files at r1, 12 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 31 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSH6t4ByJdf8QEdSng:-NgSH6t4ByJdf8QEdSnh:bxjgqa7) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java#L26)):*
> ```Java
>   @Override
>   public String getType() {
>     return "harness";
> ```

instead of hard code, can we use constant value here?
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHBcCEd6yMhW9YWUn:-NgSHBcCEd6yMhW9YWUo:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java#L28)):*
> ```Java
>   @Override
>   public String getType() {
>     return "inline";
> ```

same as above
___
*[`960-ng-core-beans/src/main/java/io/harness/steps/shellscript/ShellTypeV1.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHEjL4e15ji0pZeb5:-NgSHEjL4e15ji0pZeb6:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/960-ng-core-beans/src/main/java/io/harness/steps/shellscript/ShellTypeV1.java#L20)):*
> ```Java
> public enum ShellTypeV1 {
>   @JsonProperty("bash") Bash(ScriptType.BASH),
>   @JsonProperty("power-shell") PowerShell(ScriptType.POWERSHELL);
> ```

same as above
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptHelperServiceImplV1.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHVZVBBK3QFgnm1c5:-NgSHVZWE4MzKt6tBpFX:b-bh4lh1) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptHelperServiceImplV1.java#L75)):*
> ```Java
> @OwnedBy(CDC)
> @Slf4j
> public class ShellScriptHelperServiceImplV1 implements ShellScriptHelperServiceV1 {
> ```

@shalini-agr do we think we can improve duplicate code by converting v1 params into v0 and rest method can remain same?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepV1.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHe073-zMhSHbLxRH:-NgSHe073-zMhSHbLxRI:bfyuong) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepV1.java#L62)):*
> ```Java
> @OwnedBy(CDC)
> @Slf4j
> public class ShellScriptStepV1 extends PipelineTaskExecutable<ShellScriptTaskResponseNG> {
> ```

can we discuss today how to minimise this duplicate code more?


<!-- Sent from Reviewable.io -->

2023-10-11 06:56 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 32 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSH6t4ByJdf8QEdSng:-NgSTlcWE1ulmrb3SBvB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead of hard code, can we use constant value here?
</blockquote></details>

Done.
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHBcCEd6yMhW9YWUn:-NgSTn1k7AujP7y52ery:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/steps/shellscript/ShellTypeV1.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHEjL4e15ji0pZeb5:-NgSWGVuEhL-7zp643Mi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/960-ng-core-beans/src/main/java/io/harness/steps/shellscript/ShellTypeV1.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-12 03:31 UTC, shalini-agr commented
trigger uts

2023-10-12 04:41 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 42 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepV1.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHe073-zMhSHbLxRH:-NgXB7F82kq7W2POxYbx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepV1.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we discuss today how to minimise this duplicate code more?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptHelperServiceImplV1.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/53506#-NgSHVZVBBK3QFgnm1c5:-NgXB8Ry8Ae3NI7RjBsP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a5216e49a45d890506ddfdd3bb2d63bb68e27d1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptHelperServiceImplV1.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shalini-agr do we think we can improve duplicate code by converting v1 params into v0 and rest method can remain same?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-12 04:50 UTC, shalini-agr commented
trigger uts

2023-10-12 06:05 UTC, archit-harness requested changes
> Reviewed 1 of 29 files at r2, 3 of 4 files at r3, 12 of 20 files at r4, 5 of 5 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 45 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 483 at r6](https://reviewable.io/reviews/harness/harness-core/53506#-NgXTc0-1z1rz3Sg0jU8:-NgXTc0-1z1rz3Sg0jU9:b-d1vpp4) ([raw file](https://github.com/harness/harness-core/blob/ed9e90693f10faf981513de291a0f839eaf9bc83/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L483)):*
> ```Java
>       resolvedOutputVariables.put(name, sweepingOutputEnvVariables.get(value));
>     });
>     return ShellScriptHelperService.getShellScriptOutcome(resolvedOutputVariables, HarnessYamlVersion.V0);
> ```

this method is local why we need to add ShellScriptHelperService again?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java` line 134 at r6](https://reviewable.io/reviews/harness/harness-core/53506#-NgXU8Vs7qoTHdEmpLv5:-NgXU8Vs7qoTHdEmpLv6:b-dp450h) ([raw file](https://github.com/harness/harness-core/blob/ed9e90693f10faf981513de291a0f839eaf9bc83/pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java#L134)):*
> ```Java
>       ShellScriptBaseOutcome shellScriptOutcome =
>           ShellScriptHelperService.prepareShellScriptOutcome(shellExecutionData.getSweepingOutputEnvVariables(),
>               instance.getOutputVariables(), instance.getSecretOutputVariables(), HarnessYamlVersion.V0);
> ```

can we create base method if version not given then default is v0 and that can cast result into shellscriptOutcome from ShellScriptBaseOutcome


<!-- Sent from Reviewable.io -->

2023-10-12 06:11 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 45 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 483 at r6](https://reviewable.io/reviews/harness/harness-core/53506#-NgXTc0-1z1rz3Sg0jU8:-NgXVXYPEs52a88skL_d:b8sn04y) ([raw file](https://github.com/harness/harness-core/blob/ed9e90693f10faf981513de291a0f839eaf9bc83/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L483)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this method is local why we need to add ShellScriptHelperService again?
</blockquote></details>

because getShellScriptOutcome is a static method and the caller is nonstatic


<!-- Sent from Reviewable.io -->

2023-10-12 06:22 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 45 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java` line 134 at r6](https://reviewable.io/reviews/harness/harness-core/53506#-NgXU8Vs7qoTHdEmpLv5:-NgXYEv7ATfLiwKaWq7G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed9e90693f10faf981513de291a0f839eaf9bc83/pipeline-service/service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java#L134)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we create base method if version not given then default is v0 and that can cast result into shellscriptOutcome from ShellScriptBaseOutcome
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-12 06:30 UTC, shalini-agr commented
trigger uts

2023-10-12 06:39 UTC, utkarshchoubey-harness approved these changes
> Reviewed 7 of 29 files at r2, 6 of 20 files at r4, 1 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 45 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-12 06:42 UTC, utkarshchoubey-harness approved these changes

2023-10-12 06:59 UTC, archit-harness approved these changes
> Reviewed 7 of 29 files at r2, 6 of 20 files at r4, 1 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 27 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-10-12 09:31 UTC, hextechpal requested changes
> Reviewed 1 of 22 files at r1, 3 of 29 files at r2, 3 of 4 files at r3, 3 of 20 files at r4, 2 of 5 files at r5, 1 of 3 files at r6, 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 14 file(s) to review. 1 change requests. 

___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java` line 21 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBJp49pOe_lM6tEoV:-NgYBJp49pOe_lM6tEoW:b-mkoynt) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java#L21)):*
> ```Java
> @JsonTypeName(ShellScriptBaseSourceV1.HARNESS)
> @OwnedBy(CDP)
> public class HarnessFileStoreSourceV1 implements ShellScriptBaseSourceV1 {
> ```

Does this need recaster aliases
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java` line 21 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYDMLB4sFqLkLvI_L4:-NgYDMLB4sFqLkLvI_L5:b-72orjx) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java#L21)):*
> ```Java
> @OwnedBy(PIPELINE)
> @JsonTypeInfo(use = NAME, property = "type", include = EXTERNAL_PROPERTY, visible = true)
> public interface ShellScriptBaseSourceV1 {
> ```

can we remove v1 prefixes and just include them in the package name. THi sis for all the entities defined
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYApUT7J8XR7SZFya7:-NgYApUT7J8XR7SZFya8:bqqjzyq) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java#L23)):*
> ```Java
> public interface ShellScriptBaseSourceV1 {
>   String HARNESS = "harness";
>   String INLINE = "inline";
> ```

Move this to inline/harnes classes
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBOBhAz-hZGwVCM0D:-NgYBOBhAz-hZGwVCM0E:btyhv5r) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java#L20)):*
> ```Java
> @Value
> @JsonTypeName(ShellScriptBaseSourceV1.INLINE)
> @OwnedBy(CDC)
> ```

Recaster Alias?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 34 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBng8A5YEvFt5XB7W:-NgYBng8A5YEvFt5XB7X:bo5b9cj) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L34)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ShellScriptStepMapper {
>   public ShellScriptStepParameters toShellScriptParametersV0(ShellScriptStepParametersV1 shellScriptStepParametersV1) {
> ```

can this be moved to the ShellScriptStepParametersV1 as method itself
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 52 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBxuLCqYZkSt23T1C:-NgYBxuLCqYZkSt23T1D:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L52)):*
> ```Java
>   }
> 
>   private ExecutionTarget toExecutionTarget(ExecutionTargetV1 executionTargetV1) {
> ```

ditto
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBzPM7HepnHB-Gwi_:-NgYBzPM7HepnHB-Gwia:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L63)):*
> ```Java
>   }
> 
>   private ShellType toShellType(ShellTypeV1 shellTypeV1) {
> ```

ditto
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 75 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYC-Z53XUx2RpPKAzM:-NgYC-Z53XUx2RpPKAzN:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L75)):*
> ```Java
>   }
> 
>   OutputAlias toOutputAlias(OutputAliasV1 outputAliasV1) {
> ```

ditto
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 82 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYC2m1Be2FewadS-Nh:-NgYC2m1Be2FewadS-Ni:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L82)):*
> ```Java
>   }
> 
>   ExportScope toExportScope(ExportScopeV1 exportScopeV1) {
> ```

ditto
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 99 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYC4Nn5gGaqZVF0kqP:-NgYC4Nn5gGaqZVF0kqQ:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L99)):*
> ```Java
>   }
> 
>   private ShellScriptSourceWrapper toShellScriptSourceWrapper(ShellScriptSourceWrapperV1 shellScriptSourceWrapperV1) {
> ```

ditto
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java` line 56 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYCnoW0ZJH3ytApqTv:-NgYCnoW0ZJH3ytApqTw:behvgb6) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java#L56)):*
> ```Java
>         .executionTarget(spec.getExecution_target())
>         .onDelegate(spec.getOn_delegate())
>         .output_vars(NGVariablesUtilsV1.getMapOfVariablesWithoutSecretExpression(
> ```

We can do an enhancement in the recaster to specify custom keys. Also, can you club all the related files all together? Like shell script, the plan creator should be present here in this package. same for http


<!-- Sent from Reviewable.io -->

2023-10-12 10:43 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 27 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 34 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBng8A5YEvFt5XB7W:-NgYJeFQACpe4CC9-piM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L34)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

can this be moved to the ShellScriptStepParametersV1 as method itself
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 52 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBxuLCqYZkSt23T1C:-NgYJebM2YckmTMx2Wbz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L52)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBzPM7HepnHB-Gwi_:-NgYJf-H3YLMS36UWYlC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L63)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 75 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYC-Z53XUx2RpPKAzM:-NgYJfDp-fzMHxOmyzFk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L75)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 82 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYC2m1Be2FewadS-Nh:-NgYJfYp4njdh-A9J6ZE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L82)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java` line 99 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYC4Nn5gGaqZVF0kqP:-NgYJfnr5H_5gxK4cl_e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepMapper.java#L99)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java` line 21 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYDMLB4sFqLkLvI_L4:-NgYQN1zEFhIRe90kBXQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java#L21)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

can we remove v1 prefixes and just include them in the package name. THi sis for all the entities defined
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 08:14 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 28 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java` line 21 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBJp49pOe_lM6tEoV:-NgwgRvH1sw9X4Mlm2X-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/HarnessFileStoreSourceV1.java#L21)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Does this need recaster aliases
</blockquote></details>

Done.
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYApUT7J8XR7SZFya7:-NgwgaHx2u59xhKvJqDI:b-jdzsmg) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptBaseSourceV1.java#L23)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Move this to inline/harnes classes
</blockquote></details>

these constants have been used in @JsonTypeName annotation on inline/harness classes, so if we define them there, we wouldn't be able to use them in @JsonTypeName, that's why kept them here.
___
*[`880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYBOBhAz-hZGwVCM0D:-NgwgTv0CFa9ozDSBj1V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/880-pipeline-cd-commons/src/main/java/io/harness/steps/shellscript/v1/ShellScriptInlineSourceV1.java#L20)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Recaster Alias?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java` line 56 at r7](https://reviewable.io/reviews/harness/harness-core/53506#-NgYCnoW0ZJH3ytApqTv:-NgwgVwe1UwqHxOgx2no:b-104sbh) ([raw file](https://github.com/harness/harness-core/blob/6b4d32d1c48d29f1ddfa6c81782c2b967d326464/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepNodeV1.java#L56)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

We can do an enhancement in the recaster to specify custom keys. Also, can you club all the related files all together? Like shell script, the plan creator should be present here in this package. same for http
</blockquote></details>

Moved all v1 files to the same package


<!-- Sent from Reviewable.io -->

2023-10-17 09:23 UTC, hextechpal submitted a review, later dismissed
> Reviewed 8 of 29 files at r2, 7 of 20 files at r4, 1 of 3 files at r6, 2 of 4 files at r7, 13 of 23 files at r8, 4 of 5 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 25 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-17 09:24 UTC, shalini-agr commented
trigger uts

2023-10-18 04:01 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepParameters.java` line 36 at r10](https://reviewable.io/reviews/harness/harness-core/53506#-Ngx4GxAC51APfPaq1N8:-Nh-w99z6fDp9XRXllQu:b42vkro) ([raw file](https://github.com/harness/harness-core/blob/0659aa48b9b13fec66f26cda18b0700e20fd14f1/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/ShellScriptStepParameters.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

did we check why all annotation are req?
</blockquote></details>

yes, here all annotations are required, removing either of them is throwing errors


<!-- Sent from Reviewable.io -->

2023-10-18 04:12 UTC, shalini-agr commented
trigger uts

2023-10-18 05:38 UTC, shalini-agr commented
trigger uts

2023-10-18 05:47 UTC, archit-harness approved these changes
> Reviewed 7 of 7 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-20 11:16 UTC, shalini-agr commented
trigger uts

2023-10-20 11:42 UTC, archit-harness submitted a review, later dismissed
> Reviewed 4 of 5 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 11 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-20 11:56 UTC, shalini-agr commented
trigger uts

2023-10-20 12:37 UTC, shalini-agr commented
trigger ut7

2023-10-23 06:08 UTC, archit-harness submitted a review, later dismissed
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 12 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 06:47 UTC, shalini-agr commented
trigger uts

2023-10-23 07:51 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 14 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 08:46 UTC, shalini-agr commented
trigger uts

2023-10-23 09:26 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 7 of 29 files at r2, 9 of 20 files at r4, 1 of 3 files at r6, 2 of 4 files at r7, 8 of 23 files at r8, 2 of 5 files at r9, 6 of 8 files at r10, 5 of 7 files at r11, 1 of 1 files at r12, 2 of 5 files at r13, 1 of 1 files at r14, 3 of 3 files at r15, 1 of 2 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 10:40 UTC, shalini-agr commented
trigger uts

2023-10-23 10:58 UTC, yogesh-chauhan approved these changes
> Reviewed 10 of 10 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 10 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 11:02 UTC, archit-harness approved these changes
> Reviewed 10 of 10 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53506)* status: 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 12:34 UTC, dhruv-harness approved these changes
Approving for srm file

2023-10-23 12:46 UTC, shalini-agr commented
trigger review

2023-10-23 12:49 UTC, merged