[feat]: [CDS-79379] Stage execution entity to info for custom stage
harness/harness-core pull request #53527
Opened 2023-09-29 05:36 UTC by lovish1999

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-06 05:29 UTC, lovish1999 commented
trigger uts

2023-10-09 09:09 UTC, abhinavmittal-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53527)* status: Some of the checks are too old. 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/CustomStageStep.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/53527#-NgIgXL05KqPhdQtA8Cm:-NgIgXL05KqPhdQtA8Cn:br73832) ([raw file](https://github.com/harness/harness-core/blob/6954fc120e1c409d1433352b16fe6cea54d13bc4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/CustomStageStep.java#L44)):*
> ```Java
> public class CustomStageStep implements ChildExecutable<StageElementParameters> {
>   public static final StepType STEP_TYPE =
>       StepType.newBuilder().setType("CUSTOM_STAGE").setStepCategory(StepCategory.STAGE).build();
> ```

Please see if there is a constant that can be used.
Same can be done in CDC service as well


<!-- Sent from Reviewable.io -->

2023-10-09 09:11 UTC, abhinavmittal-harness reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53527)* status: Some of the checks are too old. 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/CDStageExecutionHandler.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/53527#-NgIgw437ODqL14OUcl_:-NgIgw437ODqL14OUcla:bqmd5oc) ([raw file](https://github.com/harness/harness-core/blob/6954fc120e1c409d1433352b16fe6cea54d13bc4/110-change-data-capture/src/main/java/io/harness/changehandlers/CDStageExecutionHandler.java#L43)):*
> ```Java
>     // for custom stage, separate CustomStageExecutionHandler is being used
>     String stageType = dbObject.get(StageExecutionInfoKeys.stageType).toString();
>     if ((stageType != null) && ("CUSTOM_STAGE".equals(stageType.toString()))) {
> ```

nit: Would prefer if we use stage type == null and stageType = CD for better clarity


<!-- Sent from Reviewable.io -->

2023-10-09 09:16 UTC, abhinavmittal-harness requested changes
> Reviewed 2 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53527)* status: Some of the checks are too old. 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/CustomStageExecutionHandler.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/53527#-NgIhOST8W1VGRs1GRFp:-NgIhOST8W1VGRs1GRFq:b-qh70qu) ([raw file](https://github.com/harness/harness-core/blob/6954fc120e1c409d1433352b16fe6cea54d13bc4/110-change-data-capture/src/main/java/io/harness/changehandlers/CustomStageExecutionHandler.java#L43)):*
> ```Java
> 
>     String stageExecutionId = getStageExecutionId(changeEvent, dbObject);
>     columnValueMapping.put("id", stageExecutionId);
> ```

if stageExecutionId is null we should not proceed further
___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/CustomStageExecutionHandler.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/53527#-NgIhkQaAkRyZTh5y195:-NgIhkQaAkRyZTh5y196:b1o66cx) ([raw file](https://github.com/harness/harness-core/blob/6954fc120e1c409d1433352b16fe6cea54d13bc4/110-change-data-capture/src/main/java/io/harness/changehandlers/CustomStageExecutionHandler.java#L51)):*
> ```Java
>       BasicDBObject executionSummaryDetails =
>           (BasicDBObject) dbObject.get(StageExecutionInfoKeys.executionSummaryDetails);
>       if (executionSummaryDetails == null) {
> ```

is it possible if no infra is used and no failure executionSummaryDetails could be null


<!-- Sent from Reviewable.io -->

2023-10-09 09:16 UTC, lovish1999 commented
trigger ut4

2023-10-09 09:17 UTC, abhinavmittal-harness reviewed
> Reviewed 11 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53527)* status: Some of the checks are too old. 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-09 13:00 UTC, lovish1999 commented
trigger messagecheck

2023-10-09 14:29 UTC, RishabhGupta34 commented on 127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java
> +  CUSTOM_STAGE("CUSTOM_STAGE", "custom");
nit. can we create a yaml type and then use that value, like the general convention above being followed?

2023-10-09 14:35 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/ExecutionNodeType.java
> +  CUSTOM_STAGE("CUSTOM_STAGE", "custom");
It's similar to what is done for deploy stage - ```DEPLOYMENT_STAGE_STEP("DEPLOYMENT_STAGE_STEP", "deployment")```

2023-10-10 06:37 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 12 of 27 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53527)* status: 32 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/CustomStageExecutionHandler.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/53527#-NgIhkQaAkRyZTh5y195:-NgNI40Z5WtAEwfTkAkh:b-rnz9za) ([raw file](https://github.com/harness/harness-core/blob/6954fc120e1c409d1433352b16fe6cea54d13bc4/110-change-data-capture/src/main/java/io/harness/changehandlers/CustomStageExecutionHandler.java#L51)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

in case of null information, we set it via ```ExecutionSummaryDetails executionSummaryDetails \= stageExecutionInfo.getExecutionSummaryDetails() == null  
? ExecutionSummaryDetails.builder().build(). So looks like this cannot be null. But it's a null check to prevent NPE. Similar to what is done in CDStageExecutionHandler.
</blockquote></details>

Just test once this case resolving for now


<!-- Sent from Reviewable.io -->

2023-10-10 06:50 UTC, lovish1999 commented
trigger uts

2023-10-10 07:13 UTC, RishabhGupta34 approved these changes

2023-10-10 10:41 UTC, lovish1999 commented
trigger uts

2023-10-10 13:13 UTC, lovish1999 commented
trigger ut1

2023-10-11 05:58 UTC, tchaurasiya commented
LGTM

2023-10-11 06:01 UTC, tchaurasiya approved these changes

2023-10-11 06:02 UTC, RishabhGupta34 approved these changes

2023-10-11 06:38 UTC, lovish1999 commented
trigger review

2023-10-11 06:45 UTC, merged