[fix]: [CDS-79529]: Fix trigger status not changing from pending state
harness/harness-core pull request #53523
Opened 2023-09-29 04:58 UTC by rathodmeetsatish

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 18:53 UTC, vcalasansh commented on 125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java
> +      if (((ArtifactPolledResponse) pollingDocument.getPolledResponse()).getAllPolledKeys().size()
Just a quick check, can `getPolledResponse()` or `getAllPolledKeys()` return null? For example, a case where user creates a trigger for non-existing imagePath, or connector credentials are wrong. Could you please check this case?

2023-10-03 18:53 UTC, vcalasansh commented on 125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java
> +      if (((ManifestPolledResponse) pollingDocument.getPolledResponse()).getAllPolledKeys().size()
Same as above

2023-10-03 19:33 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java
> +      pollingDocId = existingPollingDoc.getUuid();
Earlier we were returning if the polling document is null after saving. Now, since the code will flow through, the existingPollingDoc can be null. 

Please add Junits for this case as well

2023-10-03 20:17 UTC, sribalij commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/polling/bean/PollingDocument.java
> +  @Nullable Long lastModifiedPolledResponseTime;
Can't we re use lastModifiedAt, do we need the new field?

2023-10-03 20:17 UTC, sribalij requested changes
Added comments

2023-10-04 04:27 UTC, rathodmeetsatish commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/polling/bean/PollingDocument.java
> +  @Nullable Long lastModifiedPolledResponseTime;
lastModifiedAt is not only updated when polled response are collected but is also updated in other case hence using it wont give accurate time when last polled keys were collected

2023-10-05 12:26 UTC, vcalasansh reviewed
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53523)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-05 12:26 UTC, vcalasansh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53523#-:-NfznWVs42kxLrDgKQNN:bnfp4nl)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-06 17:27 UTC, sribalij commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/polling/bean/PollingDocument.java
> +  @Nullable Long lastModifiedPolledResponseTime;
Do you know which other scenario it is updated?

2023-10-09 06:43 UTC, sribalij submitted a review, later dismissed

2023-10-09 06:43 UTC, sribalij commented
trigger review

2023-10-09 06:43 UTC, sribalij commented
trigger uts

2023-10-09 09:52 UTC, rathodmeetsatish commented
trigger uts

2023-10-09 11:36 UTC, rathodmeetsatish commented
trigger ut0,ut3,ut4,ut5

2023-10-09 16:35 UTC, rathodmeetsatish commented
/rebase

2023-10-09 19:01 UTC, rathodmeetsatish commented
trigger uts

2023-10-09 19:13 UTC, vcalasansh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53523#-:-NgKqwK3C4KRpIGZ22Rj:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-09 19:52 UTC, sribalij approved these changes

2023-10-09 19:52 UTC, sribalij commented
trigger review

2023-10-09 19:53 UTC, sribalij commented
trigger messagecheck

2023-10-10 04:40 UTC, rathodmeetsatish commented
trigger messagecheck

2023-10-10 04:43 UTC, merged