feat: [CDS-78150]: Added Name, Tags and Failure message
harness/harness-core pull request #53538
Opened 2023-09-29 09:08 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 03:47 UTC, shivamnegi94 commented
trigger uts

2023-10-03 03:52 UTC, shalini-agr requested changes

2023-10-03 03:52 UTC, shalini-agr commented on pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java
> +    if (PipelineEventType.PIPELINE_FAILED == pipelineEventType && null != pipelineExecutionSummaryEntity
why do we need this if block? we are setting the error message in above if block regardless of the event type.

2023-10-03 04:57 UTC, shivamnegi94 commented on pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java
> +    if (PipelineEventType.PIPELINE_FAILED == pipelineEventType && null != pipelineExecutionSummaryEntity
@shalini-agr In Case of Pipeline Event, the nodeExecution will be null and error message is present in pipelineExecutionSummary. Whereas in case of Stage or Step failure the error message is present in nodeExecution.

2023-10-03 05:07 UTC, shalini-agr approved these changes

2023-10-03 16:15 UTC, archit-harness reviewed
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53538)* status: Some of the checks are too old. 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 372 at r1](https://reviewable.io/reviews/harness/harness-core/53538#gh-1343444693:-NfqJSGt5jo3svj1Hxs9:bpd61ju) ([raw file](https://github.com/harness/harness-core/blob/795651dd7388c67f5f3f18047537281a14106b65/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L372)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

@shalini-agr In Case of Pipeline Event, the nodeExecution will be null and error message is present in pipelineExecutionSummary. Whereas in case of Stage or Step failure the error message is present in nodeExecution.
</blockquote></details>

can we do if else if condition then , this looks like it can be overridden when both are non-null


<!-- Sent from Reviewable.io -->

2023-10-04 04:22 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53538)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 372 at r1](https://reviewable.io/reviews/harness/harness-core/53538#gh-1343444693:-Nfsv8srEHKNFEyeSM9U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/795651dd7388c67f5f3f18047537281a14106b65/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L372)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we do if else if condition then , this looks like it can be overridden when both are non-null
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-04 04:23 UTC, shivamnegi94 commented
trigger uts

2023-10-04 05:34 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53538)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-04 06:22 UTC, shalini-agr approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53538)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-04 06:22 UTC, shivamnegi94 commented
trigger review

2023-10-04 06:28 UTC, merged