fix: [CDS-78124]: change workflow id and name in case of rollback if tags mismatch
harness/harness-core pull request #53564
Opened 2023-09-29 14:05 UTC by TarunUba1

## Describe your changes
Handling case when in case of rollback we show wrong workflow against the artifact.

##Testing

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-09-29 15:32 UTC, abosii-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +      if (deploymentSummary.getK8sDeploymentKey() != null
Why we're doing this check here? We should do this check  before retrieving getDeploymentSummaryForInstanceCreation. If releaseNumber will not be present you'll still end up in retrieving the wrong deploymentSummary for newly created instances

2023-10-03 08:23 UTC, TarunUba1 commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +      if (deploymentSummary.getK8sDeploymentKey() != null
added this check for initial deployment summary as well

2023-10-03 09:38 UTC, TarunUba1 commented
trigger uts

2023-10-03 11:21 UTC, TarunUba1 commented
trigger ut0, ut3, ut5, ut6

2023-10-03 11:32 UTC, abosii-harness requested changes

2023-10-03 11:32 UTC, abosii-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +      getDeploymentSummaryForInstanceCreation(deploymentSummaryMap.get(containerMetadata), rollback);
please make it more clear, use if else

2023-10-03 11:32 UTC, abosii-harness commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +      if (deploymentSummary.getK8sDeploymentKey() != null
Do we still need to do this check? What is the point of it?

2023-10-03 13:24 UTC, TarunUba1 commented on 400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java
> +      if (deploymentSummary.getK8sDeploymentKey() != null
We still need that condition cause like 
canary rollback :- then it should not change the workflow if workflow name different from existing instance workflow while updating
so i am having a check when release number is not present to not update when workflow name different

2023-10-03 14:27 UTC, TarunUba1 commented
trigger uts

2023-10-03 15:38 UTC, abosii-harness approved these changes

2023-10-03 16:23 UTC, GoelPratyush99 approved these changes

2023-10-03 16:24 UTC, TarunUba1 commented
trigger messagecheck, review

2023-10-03 16:27 UTC, merged