feat: [CI-9328]: remove .git for harness code
harness/harness-core pull request #53582
Opened 2023-10-02 06:11 UTC by abhinav-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-02 06:52 UTC, abhinav-harness commented
trigger uts

2023-10-02 15:40 UTC, johannesHarness commented on product/ci/scm/git/git.go
> +		if len(commits.GetCommitIds()) < 1 {
if the above fails, could commits be nil and this return an error?

2023-10-02 15:41 UTC, johannesHarness approved these changes

2023-10-02 15:42 UTC, johannesHarness approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53582)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-10-02 19:09 UTC, abhinav-harness commented
trigger uts

2023-10-02 19:58 UTC, abhinav-harness commented
trigger uts

2023-10-08 18:52 UTC, abhinav-harness commented
trigger uts

2023-10-11 11:23 UTC, abhinav-harness commented
trigger uts

2023-10-11 11:37 UTC, devkimittal commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> -    if (repoSplit.length != 3) {
can you provide one example of how gitStatusCheckParams.getRepo() looks like?

2023-10-11 11:38 UTC, devkimittal commented on 332-ci-manager/config/ci-manager-config.yml
> +streamPerServiceConfiguration: ${PIE_STREAM_PER_SERVICE:- false}
let's undo it?

2023-10-11 11:38 UTC, devkimittal commented on product/ci/scm/docker/Dockerfile
> +CMD ["/usr/local/bin/scm"]
let's undo it?

2023-10-11 15:35 UTC, abhinav-harness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> -    if (repoSplit.length != 3) {
It’s in ut

2023-10-11 22:28 UTC, abhinav-harness commented
trigger uts

2023-10-11 22:53 UTC, hitesharinga approved these changes

2023-10-11 23:20 UTC, rutvijmehta-harness commented on product/ci/scm/git/git.go
> +		ref = commits.GetCommitIds()[0]
This can result in NPE. Are you supposed to return at L358?

2023-10-12 02:05 UTC, abhinav-harness commented
trigger uts

2023-10-12 03:56 UTC, devkimittal commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    String orgId = repoSplit[len - 3];
looks like len is always 4, why not just hardcode like `String orgId = repoSplit[1];` to make it more readable

2023-10-12 03:59 UTC, harshjain12 commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerConfiguration.java
> +  @JsonProperty("harnessCodeGitUrl") private String harnessCodeGitUrl;
Why we need this in IACM manager ?

2023-10-12 04:01 UTC, devkimittal commented on product/ci/scm/git/git.go
> +		ref = commits.GetCommitIds()[0]
this is handled in L351 i think

2023-10-12 04:03 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/ConnectorUtils.java
> +  @Inject @Named("harnessCodeGitBaseUrl") private String harnessCodeGitBaseUrl;
can we make it optional

2023-10-12 04:05 UTC, devkimittal commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerConfiguration.java
> +  @JsonProperty("harnessCodeGitUrl") private String harnessCodeGitUrl;
Iacm also registers the same class where sendstatus call comes from

2023-10-12 04:13 UTC, devkimittal commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
> +  @Named("harnessCodeGitBaseUrl")
why not name both of them as `harnessCodeGitBaseUrl`, eventually it will become confusing harnessCodeGitBaseUrl and harnessCodeGitUrl

2023-10-12 04:30 UTC, johannesHarness commented on 332-ci-manager/chart/templates/config.yaml
> +  HARNESS_CODE_GIT_URL: '{{ .Values.global.loadbalancerURL }}/hiteshtest'
I assume this shouldn't be `hiteshtest`?

2023-10-12 04:30 UTC, hemanthmantri requested changes

2023-10-12 04:30 UTC, hemanthmantri commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
> +    String gitUrl = iacmManagerConfiguration.getHarnessCodeGitUrl();
return str.replaceAll("/$", ""); // Removes trailing "/"

2023-10-12 04:36 UTC, johannesHarness commented on 332-ci-manager/config/ci-manager-config.yml
> +streamPerServiceConfiguration: ${PIE_STREAM_PER_SERVICE:- false}
it's usually good practice to have a line break at the end of text files, so when someone adds a new line at the end the existing last line isn't actually part of the diff (and there's many other reasons)
- https://medium.com/@alexey.inkin/how-to-force-newline-at-end-of-files-and-why-you-should-do-it-fdf76d1d090e
- https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2023-10-12 04:38 UTC, johannesHarness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    if (len < 4 || len > 5) {
just double checking, what would be the case of 4 vs 5 segments?

2023-10-12 04:44 UTC, johannesHarness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    String checkUid = (gitStatusCheckParams.getOwner() + "_" + gitStatusCheckParams.getSha() + "_"
does the check-uid really need the repo info?
Also, having the sha in there will make it a new status check uid for every commit (though it should be the same - otherwise branch protection will be hard)
I think we talked about that before, maybe we can fix it now?

what we technically need is a avalue that uniquely identifies the stage in the pipeline that's submitting the status check response (or just the stage identifier - though then two pipelines with the same stage identifier would overwrite each other)

2023-10-12 04:47 UTC, johannesHarness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    if (len < 4 || len > 5) {
oh I saw it in the next file
```
Gitness repo is expected to be either "git/account/org/project/repo" or "account/org/project/repo"
```

I think it would be good to mention that here, too

2023-10-12 08:14 UTC, abhinav-harness commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
> +  @Named("harnessCodeGitBaseUrl")
both are different URLs, and can be different. Even in harness code we have 2 overrides for the two.

2023-10-12 08:16 UTC, abhinav-harness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/ConnectorUtils.java
> +  @Inject @Named("harnessCodeGitBaseUrl") private String harnessCodeGitBaseUrl;
why, is this class reused?

2023-10-12 08:16 UTC, abhinav-harness commented on product/ci/scm/git/git.go
> +		ref = commits.GetCommitIds()[0]
yeah, i handled it

2023-10-12 08:19 UTC, abhinav-harness commented on 960-api-services/src/main/java/io/harness/git/GitClientHelper.java
> +    // Extract the last 4 segments
we have this method to just extract last 4 segment from URL - which would be acc/org/proj/repo.

2023-10-12 08:19 UTC, abhinav-harness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    if (len < 4 || len > 5) {
someone mentioned not to mention in main file :(

2023-10-12 08:21 UTC, abhinav-harness commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
> +    String gitUrl = iacmManagerConfiguration.getHarnessCodeGitUrl();
i think, its nit. since urgent i think we can skip it.

2023-10-12 08:23 UTC, abhinav-harness commented
trigger uts

2023-10-12 08:44 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/ConnectorUtils.java
> +  @Inject @Named("harnessCodeGitBaseUrl") private String harnessCodeGitBaseUrl;
I meant if we fail to inject. It is util and might be using at other stages like STO

Your call if you want to proceed.

2023-10-12 08:45 UTC, harshjain12 submitted a review, later dismissed

2023-10-12 08:56 UTC, abhinav-harness commented
trigger uts

2023-10-12 19:33 UTC, johannesHarness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    if (len < 4 || len > 5) {
that's weird, why? I have no idea what's happening there reading the code.
Who said that?

2023-10-12 19:34 UTC, johannesHarness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    String checkUid = (gitStatusCheckParams.getOwner() + "_" + gitStatusCheckParams.getSha() + "_"
It does look unusable in the QA environment - and with branch protection it won't work at all. So this should be fixed sooner than later IMHO

2023-10-12 19:35 UTC, johannesHarness commented on 960-api-services/src/main/java/io/harness/git/GitClientHelper.java
> +    // Extract the last 4 segments
sure - assuming the URL is correct. but splitting by `/` doesn't guarantee the last 4 segments are in the path, they could be from the scheme, too. So too catch such an unwanted scenario explicitly, that's why i was proposing to do the above?

2023-10-12 19:37 UTC, johannesHarness commented on product/ci/scm/git/git.go
> +		if commits == nil || len(commits.GetCommitIds()) < 1 {
@abhinav-harness this should add `err != nil && commits == ...`. otherwise you overwrite the existing error (I assume if `err != nil` then `commits == nil`)

2023-10-12 22:52 UTC, abhinav-harness commented
trigger uts

2023-10-12 23:00 UTC, abhinav-harness commented
trigger uts

2023-10-13 00:26 UTC, abhinav-harness commented
trigger ut2

2023-10-13 00:26 UTC, abhinav-harness commented
trigger ut4

2023-10-13 04:26 UTC, devkimittal commented on 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java
> +  @Named("harnessCodeGitBaseUrl")
But i see the only use of HarnessCodeGitUrl is when fetching getHarnessCodeGitBaseUrl().

2023-10-13 15:47 UTC, johannesHarness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    String checkUid = ("check_" + gitStatusCheckParams.getSha().substring(0, 7) + gitStatusCheckParams.getIdentifier())
remove `check_` prefix - that's redundant and only increases the length in our UI.
remove `sha` as the checkUID has to be the same across commits (as mentioned before, otherwise branch protection doesn't work - enforcing status checks on merge requires a static check uid)

2023-10-13 15:48 UTC, johannesHarness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    if (len > 3) {
please please put the three cases in the comments - otherwise this code is so hard to read. And I don't want search through all UTs just to try to understand this.

2023-10-13 15:51 UTC, johannesHarness commented on 960-api-services/src/main/java/io/harness/git/GitClientHelper.java
> +    String[] s = Arrays.copyOfRange(segments, start, length);
we should have a check on length - unless we can guarantee it will always be `>=4` - otherwise we get indexoutofrangeexceptions

2023-10-15 05:57 UTC, abhinav-harness commented on 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
> +    String checkUid = ("check_" + gitStatusCheckParams.getSha().substring(0, 7) + gitStatusCheckParams.getIdentifier())
pipeline can start with numerical values and our status check only takes alphabest to start with

2023-10-15 05:59 UTC, abhinav-harness commented
trigger uts

2023-10-16 04:42 UTC, abhinav-harness commented
trigger ut7, ut8

2023-10-16 06:35 UTC, merged