[fix]:[CDS-73386-new]: Updating the listPackageVersions
harness/harness-core pull request #53617
Opened 2023-10-03 06:20 UTC by vinit1968

## Describe your changes
Updating the listPackageVersions in AzureArtifactsRegistryServiceImp. So that it shows correct error message when feed and package name is not selected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 06:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53617) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53617) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53617) it.</sub>

2023-10-03 06:24 UTC, vinit1968 commented
trigger uts

2023-10-03 06:26 UTC, vinit1968 commented
trigger messagecheck

2023-10-03 06:30 UTC, vinit1968 commented
trigger messagecheck

2023-10-03 06:32 UTC, naman-goenka commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +import software.wings.helpers.ext.azure.devops.*;
PR check would fail: Please change to single class imports

2023-10-03 06:33 UTC, vivekkarnatiharness requested changes

2023-10-03 06:33 UTC, vivekkarnatiharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      for (AzureArtifactsFeed azureArtifactsFeed : feeds) {
Can we have a null check on feeds?. Otherwise it can cause npe

2023-10-03 06:33 UTC, vivekkarnatiharness commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      for (AzureArtifactsPackage azureArtifactsPackage : packages) {
Can we have a null check on packages?. Otherwise it can cause npe.

2023-10-03 06:35 UTC, abhinavmittal-harness reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53617)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/53617#gh-1343567850:-NfoETur03be_YUPtlrF:b4slq97) ([raw file](https://github.com/harness/harness-core/blob/f8162e7efc21c8abf8a63c7dfc91cd569042f617/960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java#L34)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

PR check would fail: Please change to single class imports
</blockquote></details>

you should update your intellij setting to not use static import unless there are more than 100 import of same package being used.


<!-- Sent from Reviewable.io -->

2023-10-03 07:22 UTC, vinit1968 commented
trigger messagecheck

2023-10-03 11:19 UTC, vinit1968 commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +import software.wings.helpers.ext.azure.devops.*;
Done

2023-10-03 11:20 UTC, vinit1968 commented
trigger uts

2023-10-03 12:16 UTC, vinit1968 commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      for (AzureArtifactsFeed azureArtifactsFeed : feeds) {
Done

2023-10-03 12:16 UTC, vinit1968 commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      for (AzureArtifactsPackage azureArtifactsPackage : packages) {
Done

2023-10-03 12:31 UTC, vinit1968 commented
trigger uts

2023-10-03 12:33 UTC, vinit1968 commented
trigger messagecheck

2023-10-03 13:00 UTC, vinit1968 commented
trigger uts

2023-10-04 03:42 UTC, vinit1968 commented
trigger messagecheck

2023-10-04 03:43 UTC, vinit1968 commented
trigger messagecheck

2023-10-04 05:23 UTC, vinit1968 commented
trigger messagecheck

2023-10-04 05:57 UTC, naman-goenka commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      if (!feeds.isEmpty()) {
EmptyPredicate.isEmpty : this will still fail in null check

2023-10-04 05:57 UTC, naman-goenka commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      if (!packages.isEmpty()) {
similarly here

2023-10-04 07:19 UTC, vinit1968 commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      if (!feeds.isEmpty()) {
Done

2023-10-04 07:19 UTC, vinit1968 commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      if (!packages.isEmpty()) {
Done

2023-10-04 07:20 UTC, vinit1968 commented
trigger uts

2023-10-04 08:14 UTC, vinit1968 commented
trigger ut8

2023-10-04 08:36 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      if (!EmptyPredicate.isEmpty(feeds)) {
When this feeds is empty/null or doesn't contain mentioned feed, we are proceeding with null feedId.
We should be throwing a proper error message that specified feed is not present.

2023-10-04 08:37 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      if (!EmptyPredicate.isEmpty(packages)) {
same as above

2023-10-04 08:41 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      throw new HintException(String.format("Failed to get Builds: %s", ExceptionUtils.getMessage(e)));
If you check above methods where exception is thrown (listFeeds and listPackages), that message is not very meaningful.
lets keep separate try catch block for both and we can log the coming exception and construct a new exception with specific message

2023-10-04 08:42 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      throw new HintException(String.format("Failed to get Builds: %s", ExceptionUtils.getMessage(e)));
We need not to keep that coming message in the exception to be thrown

2023-10-04 08:45 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      if (!EmptyPredicate.isEmpty(feeds)) {
Example:
if list is empty/null- failed to fetch feeds
if list is present but feed not matching- feed <feed> not found in feeds

2023-10-05 09:03 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +  @Test
Please add UT for remaining cases

2023-10-05 09:10 UTC, naman-goenka commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +  @Test
+

2023-10-09 14:01 UTC, vinit1968 commented
trigger uts

2023-10-09 14:07 UTC, vinit1968 commented
trigger uts

2023-10-09 14:16 UTC, naman-goenka approved these changes

2023-10-09 14:22 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    AzureArtifactsFeed azureArtifactsFeed = new AzureArtifactsFeed();
this is not used anywhere

2023-10-09 14:22 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    AzureArtifactsRestClient azureArtifactsRestClient = mock(AzureArtifactsRestClient.class);
not used

2023-10-09 14:24 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    List<AzureArtifactsPackageVersion> azureArtifactsPackageVersionsList = new ArrayList<>();
not used

2023-10-09 14:25 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    AzureArtifactsPackageVersions azureArtifactsPackageVersions = new AzureArtifactsPackageVersions();
not used

2023-10-09 14:27 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    try (MockedStatic<AzureArtifactsRegistryServiceImpl> mockedStatic =
why we are not simply mocking method using spy?

2023-10-09 14:29 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    doThrow(new HintException("Failed to get versions. Could not fetch feeds"))
nit: please try to mock same behaviour as reflected in original method.
Here message was kept same as what is expected that is "Failed to get versions. Could not fetch feeds" but method listFeed throw a different message

2023-10-09 14:30 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    doThrow(new HintException("Failed to get versions. Could not fetch feeds"))
So later if we make change to directly throw the message coming from listFeeds, test will pass but ideally it should be failing

2023-10-09 14:30 UTC, Abhishek-CDC commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    try (MockedStatic<AzureArtifactsRegistryServiceImpl> mockedStatic =
Please check other methods for the same

2023-10-09 15:07 UTC, vinit1968 commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    AzureArtifactsFeed azureArtifactsFeed = new AzureArtifactsFeed();
Have corrected it

2023-10-09 15:08 UTC, vinit1968 commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    AzureArtifactsRestClient azureArtifactsRestClient = mock(AzureArtifactsRestClient.class);
Corrected this

2023-10-09 15:08 UTC, vinit1968 commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    AzureArtifactsPackageVersions azureArtifactsPackageVersions = new AzureArtifactsPackageVersions();
resolved

2023-10-09 15:40 UTC, vinit1968 commented
trigger uts

2023-10-10 01:43 UTC, sribalij commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      throw new HintException("Failed to get versions. Feeds not found");
Add a log here

2023-10-10 01:45 UTC, sribalij commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
>        if (azureArtifactsFeed.getName().equals(feed)) {
Can this be case sensitive?

2023-10-10 01:45 UTC, sribalij commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      throw new HintException("Failed to get versions. Packages not found");
Log message?

2023-10-10 04:20 UTC, vinit1968 commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    List<AzureArtifactsPackageVersion> azureArtifactsPackageVersionsList = new ArrayList<>();
Resolved

2023-10-10 09:48 UTC, vinit1968 commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      throw new HintException("Failed to get versions. Feeds not found");
Added

2023-10-10 09:48 UTC, vinit1968 commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
> +      throw new HintException("Failed to get versions. Packages not found");
Added

2023-10-10 09:48 UTC, vinit1968 commented on 960-api-services/src/test/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImplTest.java
> +    doThrow(new HintException("Failed to get versions. Could not fetch feeds"))
Fixed

2023-10-10 09:49 UTC, vinit1968 commented
trigger uts

2023-10-10 10:02 UTC, vinit1968 commented
trigger uts

2023-10-10 10:51 UTC, vinit1968 commented
trigger uts

2023-10-10 10:57 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java
>        if (azureArtifactsFeed.getName().equals(feed)) {
@sribalij This is old logic, not updating with this PR. Please refer deleted section (Line 320-331)

Not sure if we can create 2 feeds with same name only difference being case of letters. will check.
This feed is selected through dropdown where we show name hence doing exact match.

2023-10-10 10:58 UTC, Abhishek-CDC submitted a review, later dismissed

2023-10-10 12:22 UTC, rafaelmart1ns submitted a review, later dismissed

2023-10-10 13:31 UTC, naman-goenka approved these changes

2023-10-10 13:36 UTC, vinit1968 commented
trigger uts

2023-10-10 15:29 UTC, vinit1968 commented
trigger uts

2023-10-10 15:59 UTC, vinit1968 commented
trigger uts

2023-10-11 03:34 UTC, Abhishek-CDC approved these changes

2023-10-11 05:24 UTC, naman-goenka approved these changes

2023-10-11 05:24 UTC, naman-goenka commented
trigger review

2023-10-11 05:49 UTC, vivekkarnatiharness approved these changes

2023-10-11 05:51 UTC, merged