feat: [PL-41680]: Delete accounts MARKED-FOR-DELETION through Scheduler Job
harness/harness-core pull request #53667
Opened 2023-10-03 22:28 UTC by sahibaHarness

## Describe your changes

Adding  the thread pool to be 6 & do deletion in batches

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-03 22:38 UTC, Raghav-Murali commented on 400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java
> +    ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(
triggerDeletion gets called multiple times so we should not be creating the WorkerThreadPool in this function. Instead create this as a class variable and instantiate it only once.

2023-10-03 22:39 UTC, Raghav-Murali commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> -
Let these files be in place. We will delete them later depending on how our new approach works.

2023-10-03 22:46 UTC, Raghav-Murali commented on 400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java
> +      int pageSize = 200;
Let's discuss on this further - the way iterator job ensures it doesn't pick the same doc again is through the nextIteration field. Here there is a possibility of picking the same 200 docs again and again if we're not deleting the doc from the Accounts Collection. So let's check if as part of the delete workflow whether the Account doc gets deleted from the collection or not.

2023-10-04 05:22 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java
> +      int pageSize = 200;
For this I'm making a fixed batch size of 200 and since all of them are MARKED-FOR-DELETION we going to try and delete them if any fails to delete we move forward with others. 
Since we are doing operation on a fixed size we wont move to next 200 in same iteration so the chances of same account being picked are not there

2023-10-04 05:22 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/scheduler/account/DeleteAccountHandler.java
> -
okay

2023-10-04 05:23 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java
> +    ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(
okay

2023-10-04 18:50 UTC, sahibaHarness commented
trigger uts

2023-10-05 10:16 UTC, sahibaHarness commented
trigger uts

2023-10-05 10:20 UTC, sahibaHarness commented
trigger uts

2023-10-05 12:49 UTC, ankit-harness requested changes
> Reviewed 3 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53667)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`360-cg-manager/config.yml` line 822 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzNT4p8eyGX-UgDu9E:-NfzNT4p8eyGX-UgDu9F:bw8l9g7) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/360-cg-manager/config.yml#L822)):*
> ```YAML
>   cloudwatchEndPointUrl: https://monitoring.us-east-1.amazonaws.com
> 
> accountDeletionThreadCount: 6
> ```

maxAccountsToDeleteInParallel
___
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1366 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzNJc1A7bOP9Cfsx1k:-NfzNJc1A7bOP9Cfsx1l:bahhknb) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1366)):*
> ```Java
>         1, 5L, TimeUnit.MINUTES);
> 
>     ScheduledExecutorService cgTaskPollExecutor =
> ```

cgJobExecutor
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/53667#-NfyHpPA2GR9bxl27FZ2:-NfyHpPA2GR9bxl27FZ3:br0txdw) ([raw file](https://github.com/harness/harness-core/blob/1b5fcf08b99c466d7401643f163d1daabb0837f0/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L27)):*
> ```Java
> public class AccountDeletionJob implements Runnable {
>   @Inject private AccountService accountService;
>   final int THREADS = 6;
> ```

NO_ACCOUNTS_TO_DELETE_IN_PARALLEL = 6
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/53667#-NfyHM4YDyl6w5UHuloW:-NfyHM4Z8GsqyRUBdEh5:bc8rao3) ([raw file](https://github.com/harness/harness-core/blob/1b5fcf08b99c466d7401643f163d1daabb0837f0/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L29)):*
> ```Java
>   final int THREADS = 6;
>   final ScheduledThreadPoolExecutor executor =
>       new ScheduledThreadPoolExecutor(THREADS, new ThreadFactoryBuilder().setNameFormat("AccountDeletionJob").build());
> ```

FixedThreadPoolExecutor (NO_ACCOUNTS_TO_DELETE_IN_PARALLEL)
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 45 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzrfo3Cw55JmcBaxPK:-Nfzrfo3Cw55JmcBaxPL:b-8zxbq1) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L45)):*
> ```Java
>     final int ACCOUNT_DELETION_THREAD_COUNT = configuration.getAccountDeletionThreadCount();
> 
>     startScheduledExecutor(ACCOUNT_DELETION_THREAD_COUNT);
> ```

Field Variable
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzrf0vD7aIe_6S7Va8:-Nfzrf0vD7aIe_6S7Va9:b32vd2) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L47)):*
> ```Java
>     startScheduledExecutor(ACCOUNT_DELETION_THREAD_COUNT);
> 
>     try (AcquiredLock<?> lock = persistentLocker.tryToAcquireLock(LOCK_NAME, Duration.ofMinutes(30))) {
> ```

45
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzrhKbD-xvy7foWNxZ:-NfzrhKbD-xvy7foWNx_:bibvrzs) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L55)):*
> ```Java
>     }
> 
>     stopScheduledExecutor();
> ```

No need for this then
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzs17G4X2lKj6Kdcbc:-Nfzs17G4X2lKj6Kdcbd:b-g2d2n3) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L64)):*
> ```Java
>       try (ResponseTimeRecorder ignore1 = new ResponseTimeRecorder("Deleted accounts marked for deletion")) {
>         try {
>           List<Account> accounts = accountService.listAccountsMarkedForDeletion(pageSize);
> ```

mainConfiguration.get ()
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzsVTr84s_heOYqxn1:-NfzsVTr84s_heOYqxn2:b-87fioe) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L65)):*
> ```Java
>         try {
>           List<Account> accounts = accountService.listAccountsMarkedForDeletion(pageSize);
>           triggerDeletion(accounts);
> ```

List<List<?>> futures = submitJobsForAccountDeletion(accounts);
futures.invokeAll();
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2519 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzs6VEDg3C3NBiRkNm:-Nfzs6VEDg3C3NBiRkNn:bdea3fn) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2519)):*
> ```Java
> 
>   @Override
>   public List<Account> listAccountsMarkedForDeletion(int pageSize) {
> ```

int numberofAccountsToFetch


<!-- Sent from Reviewable.io -->

2023-10-05 16:14 UTC, sahibaHarness commented
trigger uts

2023-10-05 17:09 UTC, sahibaHarness commented
trigger uts

2023-10-06 04:41 UTC, sahibaHarness commented
trigger uts

2023-10-06 04:47 UTC, sahibaHarness commented
trigger uts

2023-10-06 06:35 UTC, sahibaHarness commented
trigger ut1,ut7

2023-10-06 06:38 UTC, ankit-harness approved these changes
> Reviewed 2 of 6 files at r3, 4 of 8 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53667)* status: 10 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1003 at r9](https://reviewable.io/reviews/harness/harness-core/53667#-Ng2h8bV4a-TvYxVIdCA:-Ng2h8bV4a-TvYxVIdCB:bahhknb) ([raw file](https://github.com/harness/harness-core/blob/59656c1a924dc4c6eab1735d36679dde8109e880/400-rest/src/main/java/software/wings/app/WingsModule.java#L1003)):*
> ```Java
>   @Singleton
>   @Named("cgJobExecutor")
>   public ScheduledExecutorService taskPollExecutor() {
> ```

cgJobExecutor
___
*[`dockerization/manager/scripts/replace_configs.sh` line 1268 at r9](https://reviewable.io/reviews/harness/harness-core/53667#-Ng2h2FUCq6BKE5LTQbB:-Ng2h2FUCq6BKE5LTQbC:b-p2llgo) ([raw file](https://github.com/harness/harness-core/blob/59656c1a924dc4c6eab1735d36679dde8109e880/dockerization/manager/scripts/replace_configs.sh#L1268)):*
> ```Shell
> replace_key_value awsServiceEndpointUrls.cloudwatchEndPointUrl "$AWS_SERVICE_ENDPOINT_URLS_CLOUDWATCH_ENDPOINT_URL"
> 
> replace_key_value maxAccountsToDeleteInParallel "$MAX_ACCOUNT_TOBE_DELETED_IN_PARALLEL"
> ```

MAX_ACCOUNTS_TO_DELETE_IN_PARALLEL


<!-- Sent from Reviewable.io -->

2023-10-06 06:41 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53667)* status: 10 file(s) to review. 15. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`360-cg-manager/config.yml` line 822 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzNT4p8eyGX-UgDu9E:-Ng2i5FOC3Yjt_uhiqvJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/360-cg-manager/config.yml#L822)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

maxAccountsToDeleteInParallel
</blockquote></details>

Done.
___
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1366 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzNJc1A7bOP9Cfsx1k:-Ng2i5dd8JZBjdBBVomi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1366)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

cgJobExecutor
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/app/WingsModule.java` line 1003 at r9](https://reviewable.io/reviews/harness/harness-core/53667#-Ng2h8bV4a-TvYxVIdCA:-Ng2i6eF92CWkyaRI6Jq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/59656c1a924dc4c6eab1735d36679dde8109e880/400-rest/src/main/java/software/wings/app/WingsModule.java#L1003)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

cgJobExecutor
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/53667#-NfyHpPA2GR9bxl27FZ2:-Ng2hzRS1_98l1kZ0fYA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b5fcf08b99c466d7401643f163d1daabb0837f0/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L27)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

NO_ACCOUNTS_TO_DELETE_IN_PARALLEL = 6
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/53667#-NfyHM4YDyl6w5UHuloW:-Ng2hyLWBBXxOc2z0vCc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b5fcf08b99c466d7401643f163d1daabb0837f0/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

FixedThreadPoolExecutor (NO_ACCOUNTS_TO_DELETE_IN_PARALLEL)
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 45 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzrfo3Cw55JmcBaxPK:-Ng2hxg687STHu50wCyh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L45)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Field Variable
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 47 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzrf0vD7aIe_6S7Va8:-Ng2hx7n5JWJ6dhhByxz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L47)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

45
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzrhKbD-xvy7foWNxZ:-Ng2hwHnDyfPuoldqO_S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L55)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need for this then
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzs17G4X2lKj6Kdcbc:-Ng2i0X4B5GQ5ih3uaNu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L64)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

mainConfiguration.get ()
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-NfzsVTr84s_heOYqxn1:-Ng2i11a2apRoCFg97pr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/scheduler/AccountDeletionJob.java#L65)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

List<List<?>> futures = submitJobsForAccountDeletion(accounts);
futures.invokeAll();
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2519 at r5](https://reviewable.io/reviews/harness/harness-core/53667#-Nfzs6VEDg3C3NBiRkNm:-Ng2i2Al0VpbRl457C2S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3547d89eeca59db45cc1ff615fadef51426e17cb/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2519)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

int numberofAccountsToFetch
</blockquote></details>

Done.
___
*[`dockerization/manager/scripts/replace_configs.sh` line 1268 at r9](https://reviewable.io/reviews/harness/harness-core/53667#-Ng2h2FUCq6BKE5LTQbB:-Ng2i3G5EGzBOS-Y1gPG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/59656c1a924dc4c6eab1735d36679dde8109e880/dockerization/manager/scripts/replace_configs.sh#L1268)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

MAX_ACCOUNTS_TO_DELETE_IN_PARALLEL
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-06 06:49 UTC, sahibaHarness commented
trigger uts

2023-10-06 08:25 UTC, sahibaHarness commented
trigger ut7

2023-10-06 13:58 UTC, ankit-harness approved these changes
> Reviewed 2 of 8 files at r6, 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53667)* status: 10 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-06 16:44 UTC, Raghav-Murali approved these changes

2023-10-06 17:02 UTC, merged