[fix]: [FFM-9542] Adds rbac permssion for stale flags and new fleature admin role
harness/harness-core pull request #53716
Opened 2023-10-04 10:59 UTC by Andrew-Hayes

## Describe your changes

Adds two new permissions `ff_featureflag_staleReadyForCleanup` and `ff_featureflag_notStale`.

Also adds a new managed role "_feature_flag_admin_role" that includes all of the feature flag permissions.

## Checklist
- [*] I've documented the changes in the PR description.
- [*] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 09:49 UTC, danmack-harness approved these changes

2023-10-09 10:16 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53716)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 599 at r1](https://reviewable.io/reviews/harness/harness-core/53716#-NgIvxNe0iS8k78opeML:-NgIvxNe0iS8k78opeMM:b-hq4nki) ([raw file](https://github.com/harness/harness-core/blob/58ed5cc032e52f521f5e96a7f3ede020586a0bf7/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L599)):*
> ```YAML
>   - identifier: ff_featureflag_staleReadyForCleanup
>     name: Mark a stale Feature Flag as ready for cleanup
>     status: ACTIVE
> ```

I hope you have gone through this doc
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812887/Permissions+Management
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 808 at r1](https://reviewable.io/reviews/harness/harness-core/53716#-NgIv_hh9_043zgY4L3b:-NgIv_hh9_043zgY4L3c:bfxbdtv) ([raw file](https://github.com/harness/harness-core/blob/58ed5cc032e52f521f5e96a7f3ede020586a0bf7/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L808)):*
> ```YAML
>         - organization
>         - project
>     - identifier: _feature_flag_admin_role
> ```

We already have _feature_flag_manage_role role. Is that needed to be different that this one?


<!-- Sent from Reviewable.io -->

2023-10-09 10:49 UTC, davejohnston commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: ff_featureflag_staleReadyForCleanup
should this be all snake case?

2023-10-10 10:24 UTC, Andrew-Hayes commented
@Jimit09Gandhi yeah it was decided with product to leave the  `_feature_flag_manage_role` as it is and add a new role `_feature_flag_admin_role`. With the new admin role being more comprehensive in it's list of permissions.

2023-10-10 12:48 UTC, Andrew-Hayes commented
We are splitting the new stale flag permissions into a separate ticket.

2023-10-10 13:09 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53716)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 821 at r2](https://reviewable.io/reviews/harness/harness-core/53716#-NgOfnkD9mCp_iuKh_JH:-NgOfnkD9mCp_iuKh_JI:b3juh8s) ([raw file](https://github.com/harness/harness-core/blob/fe9238820ab1819739bd0094f3d8cca756fa3136/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L821)):*
> ```YAML
>         - ff_target_view
>         - ff_environment_apiKeyView
>         - ff_environment_apiKeyCreate
> ```

If this FF Admin role, shouldn't it have ff_environment_apiKeyDelete ? I see few other FF permissions missing. Please check.


<!-- Sent from Reviewable.io -->

2023-10-10 13:14 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53716)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 597 at r1](https://reviewable.io/reviews/harness/harness-core/53716#gh-1350144744:-NgOiCbY0fLqm089L3ib:b-7crcxs) ([raw file](https://github.com/harness/harness-core/blob/58ed5cc032e52f521f5e96a7f3ede020586a0bf7/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L597)):*
<details><summary><i>Previously, davejohnston (Dave Johnston) wrote…</i></summary><blockquote>

should this be all snake case?
</blockquote></details>

 yes @davejohnston  for permission identifier


<!-- Sent from Reviewable.io -->

2023-10-10 13:26 UTC, Andrew-Hayes commented
Yea it was a conscious decision to leave out the delete permissions from the role. They were deemed too dangerous even for an "admin" role

2023-10-10 13:28 UTC, Jimit09Gandhi approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53716)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-10 14:01 UTC, Andrew-Hayes commented
trigger uts

2023-10-10 14:06 UTC, Andrew-Hayes commented
trigger ut0

2023-10-10 15:34 UTC, Andrew-Hayes commented
trigger ut5

2023-10-10 17:14 UTC, Andrew-Hayes commented
trigger ut7

2023-10-10 20:30 UTC, merged