[feat]: [PLG-2859]: provision FREE build credits on CI license creation
harness/harness-core pull request #53741
Opened 2023-10-05 00:24 UTC by kapil-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-05 00:24 UTC, kapil-harness commented
trigger uts

2023-10-05 01:29 UTC, neelam-harness reviewed
LGTM overall!

2023-10-05 01:29 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java
> +public class CreditConstants {
Nit: I think we should rename it to `CreditUtils` since this class contains more than just constants.

2023-10-05 01:29 UTC, neelam-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java
> +
Nit: remove extra linespace.

2023-10-05 07:10 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-Nfyf55v1Urz0lXBlxaC:-Nfyf55wEQQm1emezEEv:b80nsnx) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L68)):*
> ```Java
>       }
>     } catch (InterruptedException ex) {
>       SecurityContextBuilder.unsetCompleteContext();
> ```

why don't we log exception here?


<!-- Sent from Reviewable.io -->

2023-10-05 07:11 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfyfApjB8T112A3QH7X:-NfyfApjB8T112A3QH7Y:b-tcx2ef) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L68)):*
> ```Java
>       }
>     } catch (InterruptedException ex) {
>       SecurityContextBuilder.unsetCompleteContext();
> ```

unsetting of complete context is already handled in finally block, we can remove it from here


<!-- Sent from Reviewable.io -->

2023-10-05 07:12 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfyfYrb4f-yL7TOItVM:-NfyfYrb4f-yL7TOItVN:b-a6j6lb) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L81)):*
> ```Java
>       pollAndProcessMessages();
>     } catch (EventsFrameworkDownException e) {
>       log.error("Events framework is down for " + USERMEMBERSHIP + " stream consumer. Retrying again...", e);
> ```

why is it "USERMEMBERSHIP mentioned here? The name of the consumer class seems to be very different.


<!-- Sent from Reviewable.io -->

2023-10-05 07:13 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfyfgGpBCTfEBBGXE5J:-NfyfgGpBCTfEBBGXE5K:bjkbtcx) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L62)):*
> ```Java
>           log.info(
>               "ModuleLicense stream consumer is not running on primary deployment, will try again after some time...");
>           TimeUnit.SECONDS.sleep(30);
> ```

we have a constant for sleep duration already defined, lets use that.


<!-- Sent from Reviewable.io -->

2023-10-05 07:14 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamListener.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-Nfyg0gzDd2PwWKY25e_:-Nfyg0gzDd2PwWKY25ea:bus8gdl) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamListener.java#L41)):*
> ```Java
>       Map<String, String> metadataMap = message.getMessage().getMetadataMap();
> 
>       if (metadataMap != null && metadataMap.get(ACTION) != null && CREATE_ACTION.equals(metadataMap.get(ACTION))) {
> ```

don't need the 2nd condition check here


<!-- Sent from Reviewable.io -->

2023-10-05 07:15 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfygCq13_P1CyWlkvNb:-NfygCq13_P1CyWlkvNc:bqbs2ea) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java#L25)):*
> ```Java
>   private static final int FREE_CREDITS_QUANTITY = 2000;
> 
>   private static Calendar getStartOfNextMonth() {
> ```

I see recurring usages of such util methods. Please create a separate DateTimeUtils and put all such methods at a central place and use them rather than just defining here and there.


<!-- Sent from Reviewable.io -->

2023-10-05 07:16 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfygNTsBjnOd0SrY02K:-NfygNTsBjnOd0SrY02L:b288iu3) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java#L22)):*
> ```Java
> 
> @OwnedBy(GTM)
> public class CreditConstants {
> ```

class name is "constants" but there are hardly any constants defined: :-p


<!-- Sent from Reviewable.io -->

2023-10-05 10:10 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfyfgGpBCTfEBBGXE5J:-NfzFPJcAw_oWEvq5CHo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L62)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we have a constant for sleep duration already defined, lets use that.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-Nfyf55v1Urz0lXBlxaC:-NfzFSJz7bzE4L11MRxL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why don't we log exception here?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfyfApjB8T112A3QH7X:-NfzFawQ0j6GMbo-TZBC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

unsetting of complete context is already handled in finally block, we can remove it from here
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfyfYrb4f-yL7TOItVM:-NfzFhGC5jY-7YMl5Ztk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it "USERMEMBERSHIP mentioned here? The name of the consumer class seems to be very different.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/53741#gh-1346659724:-NfzIh9D5miEpMjXPCF6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamConsumer.java#L81)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

very very Nit: `Trying again....` or `Retrying...`
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamListener.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-Nfyg0gzDd2PwWKY25e_:-NfzGBnN7kPmUL3FnJVI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense/ModuleLicenseStreamListener.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

don't need the 2nd condition check here
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfygNTsBjnOd0SrY02K:-NfzHEku3Ivok71OMs4Z:by3176a) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

class name is "constants" but there are hardly any constants defined: :-p
</blockquote></details>

Changed the name to CreditUtils. Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfygCq13_P1CyWlkvNb:-NfzHH7h3cqLgXAGHLue:bqt1w79) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see recurring usages of such util methods. Please create a separate DateTimeUtils and put all such methods at a central place and use them rather than just defining here and there.
</blockquote></details>

That is why I pulled this piece of code inside CreditUtils class and is now being commonly used by ModuleLicenseStreamListener and ProvisionMonthlyCICreditsHandler


<!-- Sent from Reviewable.io -->

2023-10-05 10:11 UTC, kapil-harness commented
trigger uts

2023-10-05 18:33 UTC, neelam-harness approved these changes

2023-10-05 20:55 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/53741#-NfygCq13_P1CyWlkvNb:-Ng0bks-3g67JvldeObu:b-1thve1) ([raw file](https://github.com/harness/harness-core/blob/a8c924eef538420f2ad4e315c85cc5cc58ec35b0/930-ng-license-manager/src/main/java/io/harness/credit/CreditConstants.java#L25)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

That is why I pulled this piece of code inside CreditUtils class and is now being commonly used by ModuleLicenseStreamListener and ProvisionMonthlyCICreditsHandler
</blockquote></details>

Doesn't make sense as CredUtils has no relation to getStartOfNextMonth method ideally. It would've been much better to use a common util only for dateTime and use it everywhere. It would only make sense for it to be in CredUtils if and only if getting some date was having a particular relation to Credit or something else eg: getCreditStartDate() etc. Unblocking for now.


<!-- Sent from Reviewable.io -->

2023-10-05 20:56 UTC, mohitg0795 approved these changes
> Reviewed 5 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53741)* status: 9 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-06 07:36 UTC, kapil-harness commented
trigger review

2023-10-06 07:37 UTC, kapil-harness commented
trigger messagecheck

2023-10-06 07:39 UTC, merged

2023-10-06 16:39 UTC, neelam-harness commented
trigger review