feat: [CDS-78852]: adding helmchart info in release to help when we do rollback
harness/harness-core pull request #53779
Opened 2023-10-05 12:35 UTC by TarunUba1

## Describe your changes
In case of Rolling deploy we will add helm chart info for releases, these details will be used in cases of rollback to retrieve the data from release history when we create new pods. This data will update the instance details list.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-05 14:07 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
> +  public static final String RELEASE_SECRET_HELM_CHART_NAME_KEY = "harness.io/helm-chart-name";
just a suggestion, maybe it would make more sense to have this scoped to something like:
metadata.chart.harness.io/name
metadata.chart.harness.io/version
or
metadata.helm.harness.io/chart-name
metadata.helm.harness.io/chart-version
or
internal.helm.harness.io/chart-name
internal.helm.harness.io/chart-version

2023-10-06 06:55 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public HelmChartInfoDTO getHelmChartForRelease(HelmChartInfo helmChartInfo) {
The reason i created HelmChartDTO was cause HelmChartInfo, i could not refer in K8sRelease, i can not create these functions cause then the circular dependency error will come

2023-10-06 07:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public HelmChartInfoDTO getHelmChartForRelease(HelmChartInfo helmChartInfo) {
then move them to a utility class

2023-10-06 11:09 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public HelmChartInfoDTO getHelmChartForRelease(HelmChartInfo helmChartInfo) {
any suggestions for utility class cause i feel that k8sTaskHelperBase is best for this

2023-10-06 12:32 UTC, TarunUba1 commented
trigger uts

2023-10-06 13:53 UTC, TarunUba1 commented
trigger ut7

2023-10-06 13:54 UTC, abhinavsingh1196 requested changes
> Reviewed 1 of 1 files at r3, 4 of 9 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53779)* status: 18 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/rolling/K8sRollingRequestHandler.java` line 168 at r5](https://reviewable.io/reviews/harness/harness-core/53779#-Ng4F7-N2ngthoRn1MuE:-Ng4F7-N2ngthoRn1MuF:b-lo43qq) ([raw file](https://github.com/harness/harness-core/blob/082069fff44e7f98fa05b7bb226039e6fd141984/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/rolling/K8sRollingRequestHandler.java#L168)):*
> ```Java
>           k8sRollingDeployRequest.getManifestDelegateConfig(), manifestFilesDirectory);
>       if (helmChartInfo != null) {
>         release.setHelmChartInfo(toHelmChartInfoDTO(helmChartInfo));
> ```

let's just handle null within the util method `toHelmChartInfoDTO`?  I see it's handled in one util method already
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/HelmChartInfoMapper.java` line 8 at r5](https://reviewable.io/reviews/harness/harness-core/53779#-Ng4EzqL08fclqidTbSK:-Ng4EzqL08fclqidTbSL:bf3b7so) ([raw file](https://github.com/harness/harness-core/blob/082069fff44e7f98fa05b7bb226039e6fd141984/930-delegate-tasks/src/main/java/io/harness/delegate/utils/HelmChartInfoMapper.java#L8)):*
> ```Java
>  */
> 
> package io.harness.delegate.utils;
> ```

maybe we can keep this in io.harness.delegate.k8s.utils? 
___
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java` line 167 at r5](https://reviewable.io/reviews/harness/harness-core/53779#-Ng4Fr0480qUuUft5QbQ:-Ng4Fr0480qUuUft5QbR:b-93ahxn) ([raw file](https://github.com/harness/harness-core/blob/082069fff44e7f98fa05b7bb226039e6fd141984/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java#L167)):*
> ```Java
>             .repoUrl(getReleaseAnnotationValue(releaseSecret, RELEASE_SECRET_HELM_CHART_REPO_URL_KEY))
>             .build();
>     if (isEmpty(helmChartInfoDTO.getName()) && isEmpty(helmChartInfoDTO.getVersion())) {
> ```

can move this method to top of method. then returned builder object can be put inline itself 


<!-- Sent from Reviewable.io -->

2023-10-06 14:01 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53779)* status: 18 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java` line 167 at r5](https://reviewable.io/reviews/harness/harness-core/53779#-Ng4Fr0480qUuUft5QbQ:-Ng4Hh2kC1mXvkSNl-o_:b-dzugia) ([raw file](https://github.com/harness/harness-core/blob/082069fff44e7f98fa05b7bb226039e6fd141984/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java#L167)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

can move this method to top of method. then returned builder object can be put inline itself
</blockquote></details>

can't cause like it depends on helmchartinfoDto


<!-- Sent from Reviewable.io -->

2023-10-09 06:46 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
> +  public void setHelmChartInfo(@NotNull HelmChartInfoDTO helmChartInfo) {
remove @NotNull if you're expecting that helmChartInfo to be null

2023-10-09 07:10 UTC, TarunUba1 commented
trigger uts

2023-10-09 08:25 UTC, TarunUba1 commented
trigger ut1

2023-10-09 09:27 UTC, TarunUba1 commented
trigger ut6

2023-10-09 09:29 UTC, TarunUba1 commented
trigger ut1

2023-10-09 09:40 UTC, TarunUba1 commented
trigger ut1

2023-10-09 09:46 UTC, TarunUba1 commented
trigger ut1, ut6

2023-10-09 11:43 UTC, TarunUba1 commented
trigger messagecheck

2023-10-09 11:47 UTC, GoelPratyush99 approved these changes

2023-10-09 13:38 UTC, merged