feat: [CDS-80035]: Improved test coverage for CVNGStepTaskServiceImpl.java
harness/harness-core pull request #53817
Opened 2023-10-06 07:10 UTC by Anshika2203

## Describe your changes

Improved test coverage for CVNGStepTaskServiceImpl.java

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/53810)

2023-10-06 07:32 UTC, Anshika2203 commented
trigger uts

2023-10-08 18:29 UTC, sribalij approved these changes

2023-10-09 04:33 UTC, sribalij requested changes

2023-10-09 04:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/cdng/services/impl/CVNGStepTaskServiceImplTest.java
> +    List<LogAnalysisClusterChartDTO> expectedClusters = new ArrayList<>();
You can probably use Collections.emptyList() instead of new ArrayList<>();

2023-10-09 04:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/cdng/services/impl/CVNGStepTaskServiceImplTest.java
> +    List<String> expectedTransactionNames = new ArrayList<>();
You can probably use Collections.emptyList() instead of new ArrayList<>();

2023-10-09 04:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/cdng/services/impl/CVNGStepTaskServiceImplTest.java
> +    assertThat(expectedClusters).isEqualTo(resultClusters);
What about the test condition where the` deploymentLogAnalysisService.getLogAnalysisClusters` returns real values?

2023-10-09 04:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/cdng/services/impl/CVNGStepTaskServiceImplTest.java
> +    assertThat(expectedExecutionLogs).isEqualTo(resultExecutionLogs);
You need to verify both positive and negative test cases

2023-10-09 04:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/cdng/services/impl/CVNGStepTaskServiceImplTest.java
> +    assertThat(expectedTransactionNames).isEqualTo(resultTransactionNames);
Verify both scenarios

2023-10-09 04:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/cdng/services/impl/CVNGStepTaskServiceImplTest.java
> +    assertThat(expectedClusters).isEqualTo(resultClusters);
Both positive and negative scenarios

2023-10-11 09:34 UTC, Anshika2203 commented
/rebase

2023-10-11 09:38 UTC, Anshika2203 commented
trigger recency

2023-10-11 09:53 UTC, closed without merging