[feat]: [CDS-79409]: support basic strategy in ecs
harness/harness-core pull request #53836
Opened 2023-10-06 10:26 UTC by PragyeshMishra01

## Describe your changes
1. It contains delegate side logic for all tasks needed for basic strategy
2. It contains manager side logic for all steps needed for basic strategy
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-06 14:54 UTC, piyush-bhuwalka approved these changes

2023-10-08 19:05 UTC, ivan-83 requested changes
> Reviewed 27 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53836)* status: 28 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFOEkS1aqm23C5f8nh:-NgFOEkS1aqm23C5f8ni:b-4e0jvs) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java#L107)):*
> ```Java
>               .build();
> 
>       executionSweepingOutputService.consume(ambiance, OutcomeExpressionConstants.ECS_BASIC_ROLLBACK_OUTCOME,
> ```

Are we using somewhere ECS_BASIC_ROLLBACK_OUTCOME data, we already added it to step outcome. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1094 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFIVq_-t_d_cgYrhMA:-NgFIVq_-t_d_cgYrhMB:b-u9p8mw) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1094)):*
> ```Java
>     TaskChainResponse taskChainResponse = null;
>     try {
>       if (responseData instanceof EcsGitFetchResponse) { // if EcsGitFetchResponse is received
> ```

remove comment
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1109 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFIb3L2JDEddGIMnQW:-NgFIb3M3eH5bJg3d9IO:b-u9p8mw) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1109)):*
> ```Java
>             ecsS3FetchResponse, ecsStepExecutor, ambiance, stepElementParameters, ecsS3FetchPassThroughData);
>       } else if (responseData
>           instanceof EcsBasicPrepareRollbackResponse) { // if EcsPrepareRollbackDataResponse is received
> ```

remove comment
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1948 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFK4VEA5RMeWySfZ66:-NgFK4VEA5RMeWySfZ67:bfs4896) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1948)):*
> ```Java
>         ecsServiceSetupStepParameters.getSameAsAlreadyRunningInstances());
> 
>     EcsResizeStrategy resizeStrategy = ecsServiceSetupStepParameters.getResizeStrategy();
> ```

Getting resizeStrategy can be moved to a separate method and used in EcsServiceSetupStep.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1974 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFLIEF4ZT9E00zSkTD:-NgFLIEGAAebHthO5QEL:buk701e) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1974)):*
> ```Java
>             .newServiceName(basicPrepareRollbackData.getNewServiceName())
>             .sameAsAlreadyRunningInstances(sameAsAlreadyRunningInstances)
>             .serviceDeployConfig(EcsServiceDeployConfig.builder()
> ```

Minor:  serviceDeployConfig >> newServiceDeployConfig
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 1982 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFdZ8CBEaR3unqehZv:-NgFdZ8CBEaR3unqehZw:b-nozxkx) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L1982)):*
> ```Java
>             .build();
> 
>     executionSweepingOutputService.consume(ambiance, OutcomeExpressionConstants.ECS_BASIC_PREPARE_ROLLBACK_DATA_OUTCOME,
> ```

ECS_BASIC_PREPARE_ROLLBACK_DATA_OUTCOME - can we have two outcomes one for rollback data and another one for data needed in other manager steps? It's the cleaner solution for me. It could be that we will have duplicate data in two outputs, but we will know what exactly is needed for rollback. 
Or, let's have one output but have EcsBasicPrepareRollbackDataOutcome structure with two data structures currentRunningService and newService. 
EcsBasicPrepareRollbackDataOutcome - needs to be redesigned. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 2285 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFNCzcDMXKAq5d7oYG:-NgFNCzcDMXKAq5d7oYH:b9xhq89) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L2285)):*
> ```Java
>             deployData.getNewServiceData().getTasks(), infrastructureKey, deployData.getNewServiceData().getRegion()));
>     serverInstanceInfos.addAll(EcsTaskToServerInstanceInfoMapper.toServerInstanceInfoList(
>         deployData.getOldServiceData().getTasks(), infrastructureKey, deployData.getOldServiceData().getRegion()));
> ```

Do we need here new service data instead of old service data?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 2295 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFNKSQ1xtKngEawNEU:-NgFNKSQ1xtKngEawNEV:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L2295)):*
> ```Java
>             infrastructureKey, rollbackData.getNewServiceData().getRegion()));
>     serverInstanceInfos.addAll(EcsTaskToServerInstanceInfoMapper.toServerInstanceInfoList(
>         rollbackData.getOldServiceData().getTasks(), infrastructureKey, rollbackData.getOldServiceData().getRegion()));
> ```

The same as above.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFQc4n69BYNEw41BXP:-NgFQc4oAg1qNAirh8L5:bxhtr04) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java#L113)):*
> ```Java
>               .build();
> 
>       executionSweepingOutputService.consume(ambiance, OutcomeExpressionConstants.ECS_UPGRADE_CONTAINER_OUTCOME,
> ```

Are we consuming or planning to consume somewhere ECS_UPGRADE_CONTAINER_OUTCOME data?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsBasicPrepareRollbackTaskHandler.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFTGVBD9Dux9YLDrJk:-NgFTGVBD9Dux9YLDrJl:b-hcyfci) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsBasicPrepareRollbackTaskHandler.java#L113)):*
> ```Java
>       Optional<Service> activeServiceOptional = ecsCommandTaskHelper.getLatestRunningService(eligibleServices);
> 
>       int newServiceRevision = ecsCommandTaskHelper.getRevisionForDeployment(eligibleServices);
> ```

newServiceRevision  >> nextServiceRevision 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsBasicPrepareRollbackTaskHandler.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFTybkCxo261CPS2ax:-NgFTybkCxo261CPS2ay:bm175xl) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsBasicPrepareRollbackTaskHandler.java#L143)):*
> ```Java
>           logCallback, activeService.serviceName(), activeService, ecsInfraConfig);
> 
>       if (prepareRollbackRequest.isSameAsAlreadyRunningInstances()) {
> ```

Do we n [...]

2023-10-09 07:08 UTC, PragyeshMishra01 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53836)* status: 28 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFOEkS1aqm23C5f8nh:-NgI8iKyCIF1iEKZ82xB:b-42xq8y) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java#L107)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Are we using somewhere ECS_BASIC_ROLLBACK_OUTCOME data, we already added it to step outcome.
</blockquote></details>

we will not use this outcome internally, customers may use it by using fqn path of output 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 2285 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFNCzcDMXKAq5d7oYG:-NgI91z91zRDeUOPXRaA:bq5bq6a) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L2285)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we need here new service data instead of old service data?
</blockquote></details>

For instance sync, we are taking instances of both new and old service. For example if customers add approval steps in between ecs steps and executions will wait on these approvals, so we should show all existing instances during that time.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 2295 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFNKSQ1xtKngEawNEU:-NgIAP-c39uk0A2iLfZ9:bj8ow8h) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L2295)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above.
</blockquote></details>

For instance sync, we are taking instances of both new and old service. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFQc4n69BYNEw41BXP:-NgIA_1T6Udq4sN-eGQp:bkt10vy) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java#L113)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Are we consuming or planning to consume somewhere ECS_UPGRADE_CONTAINER_OUTCOME data?
</blockquote></details>

For now, there are no plans to consume it but customers can consume it in their pipelines by using fqn paths.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsServiceSetupTaskHandler.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFbMkt109Baw4kUGOY:-NgIBi2A1wCNDyPhws2N:bafbf3w) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsServiceSetupTaskHandler.java#L103)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Shouldn't we downsize and delete stale services in the upgrade step and here only create the new service? 
What if rollback happens after this step, will rollback restore the previous state on cluster?
</blockquote></details>

In CG, we follow this logic. we are keeping most of logic same here as we are doing this feature for migrating customers.
Incase of rollback, we will move oldService to its previous state and will downsize new service.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsUpgradeContainerTaskHandler.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFZlUu10abki_J_SL-:-NgIETfl5fzGrzOOATUv:bcraq1q) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsUpgradeContainerTaskHandler.java#L176)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What is the difference between stale and eligable services?
</blockquote></details>

basically, all services which matches the service prefix are eligible ones. 
Out of these, one will be new service (which we are deploying) and other one will be service (which was active service before deployment). Rest all are stale services.


<!-- Sent from Reviewable.io -->

2023-10-09 20:19 UTC, PragyeshMishra01 commented
trigger uts

2023-10-09 22:03 UTC, PragyeshMishra01 commented
trigger checkstylecodeformat

2023-10-09 22:35 UTC, ivan-83 requested changes
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53836)* status: 31 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFOEkS1aqm23C5f8nh:-NgLMMmkEFaULIup37UM:b-5wmvqf) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java#L107)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

we will not use this outcome internally, customers may use it by using fqn path of output
</blockquote></details>

right, but we are putting it as part of stepResponse.outcome(...) and it should be available by fqn by default, can you pls check.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 2295 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFNKSQ1xtKngEawNEU:-NgLY38R3dmnoDpZPyeY:b-15jmv5) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L2295)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

For instance sync, we are taking instances of both new and old service.
</blockquote></details>

I think we are taking the old instances from instances Mongo DB and only adding the new ones here when the deployment/rollback is done. We should have that calculation in instance sync.
Pls, make sure that the instance sync logic works properly, but it could be done as part of another PR.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFQc4n69BYNEw41BXP:-NgLOxv18oPkFPmqB4e8:bstge6t) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java#L113)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

For now, there are no plans to consume it but customers can consume it in their pipelines by using fqn paths.
</blockquote></details>

the same as above
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsServiceSetupTaskHandler.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFbMkt109Baw4kUGOY:-NgLPcZp70OjbSh7sPCz:b-x3aouz) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsServiceSetupTaskHandler.java#L103)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

In CG, we follow this logic. we are keeping most of logic same here as we are doing this feature for migrating customers.
Incase of rollback, we will move oldService to its previous state and will downsize new service.
</blockquote></details>

Sure. we can keep this logic, but if we delete the old services here how we are going to return to the previous state in rollback? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsUpgradeContainerTaskHandler.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFZlUu10abki_J_SL-:-NgLRdqwA91fvwAneiss:b-vy87e6) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsUpgradeContainerTaskHandler.java#L176)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

basically, all services which matches the service prefix are eligible ones. 
Out of these, one will be new service (which we are deploying) and other one will be service (which was active service before deployment). Rest all are stale services.
</blockquote></details>

stale services are services that do not have instances and are deployed by Harness, right?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 361 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLV6ty7Au6etLT-y5s:-NgLV6ty7Au6etLT-y5t:buiruuh) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L361)):*
> ```Java
>     List<Service> services = newArrayList();
>     do {
>       ListServicesRequest listServicesRequest =
> ```

Listing serviceArns should be one method, and listing service based on serviceArns another one.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 375 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLUzJY8veXd8fFUL6E:-NgLUzJY8veXd8fFUL6F:bo5nbok) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L375)):*
> ```Java
>     // We can only use this api to describe 10 services at a time.
>     while (counter < serviceArns.size()) {
>       endIndex = Integer.min(counter + 10, serviceArns.size());
> ```

10 - should be const
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 388 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLVX3rBDuGuxL4i5zu:-NgLVX3sEVwqVba6UZ4O:bqyc7av) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L388)):*
> ```Java
>   }
> 
>   public void deleteStaleServicesHavingZeroInstance(
> ```

Minor: deleteStaleServicesHavingZeroInstance >> deleteStaleServicesWithZeroInstance
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 472 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLWVjD55iWB8ENnSLh:-NgLWVjD55iWB8ENnSLi:bimp9g9) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L472)):*
> ```Java
>   }
> 
>   public Service fetchServiceWithName(List<Service> services, String serviceName) {
> ```

Minor: I prefer optional instead of null.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 500 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLXt7D8mPgY5EoGLCB:-NgLXt7D8mPgY5EoGLCC:b-8r23sk) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L500)):*
> ```Java
>   }
> 
>   public int getRevisionForDeployment(List<Service> services) {
> ```

getRevisionForDeployment >> getNextRevisionForDeployment
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 506 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLXSO9AcjAEecby7wN:-NgLXSOA2EauoB1aIFb-:b-aezbtl) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L506)):*
> ```Java
>             .collect(toList());
>     if (CollectionUtils.isEmpty(orderedServices)) {
>       return 1;
> ```

Minor: 1 should be cont with self self-describing name. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 516 at r [...]

2023-10-10 01:11 UTC, PragyeshMishra01 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53836)* status: 31 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFOEkS1aqm23C5f8nh:-NgLnq0cEbY4XeVnvoCQ:boi31ui) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java#L107)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

right, but we are putting it as part of stepResponse.outcome(...) and it should be available by fqn by default, can you pls check.
</blockquote></details>

Done, removed it from step outcome
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java` line 2295 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFNKSQ1xtKngEawNEU:-NgLo4fBEjKeA_V3Vwq7:b-yh8jz4) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java#L2295)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I think we are taking the old instances from instances Mongo DB and only adding the new ones here when the deployment/rollback is done. We should have that calculation in instance sync.
Pls, make sure that the instance sync logic works properly, but it could be done as part of another PR.
</blockquote></details>

sure, will take of it in followup PR
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFQc4n69BYNEw41BXP:-NgLoDT85g5KUmarU3lB:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java#L113)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

the same as above
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsServiceSetupTaskHandler.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFbMkt109Baw4kUGOY:-NgLoHtx9Aa3gOJjhvtk:buk1bev) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsServiceSetupTaskHandler.java#L103)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Sure. we can keep this logic, but if we delete the old services here how we are going to return to the previous state in rollback?
</blockquote></details>

we only bring that old service to previous state which was the active service before deployment. Rest of old services are stale ones. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsUpgradeContainerTaskHandler.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFZlUu10abki_J_SL-:-NgLol5C3I8qTfugpUkT:b-em8krx) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/930-delegate-tasks/src/main/java/io/harness/delegate/ecs/EcsUpgradeContainerTaskHandler.java#L176)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

stale services are services that do not have instances and are deployed by Harness, right?
</blockquote></details>

yes, that is correct..
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 361 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLV6ty7Au6etLT-y5s:-NgLrqQv6v6hEllJswj2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L361)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Listing serviceArns should be one method, and listing service based on serviceArns another one.
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 375 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLUzJY8veXd8fFUL6E:-NgLsASc7Wy6eLMBDA50:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L375)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

10 - should be const
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 388 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLVX3rBDuGuxL4i5zu:-NgLsJH8-b8Cx_PQCxkj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L388)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: deleteStaleServicesHavingZeroInstance >> deleteStaleServicesWithZeroInstance
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 500 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLXt7D8mPgY5EoGLCB:-NgLtB7z0Rdw_qiA3Ozz:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L500)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

getRevisionForDeployment >> getNextRevisionForDeployment
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 506 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLXSO9AcjAEecby7wN:-NgLtZ8pDmUDuGWDZ45k:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L506)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: 1 should be cont with self self-describing name.
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 516 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLWjQD0K2YPzV9kq5a:-NgLu-dGCc43nWEv788w:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L516)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

service.desiredCount() >> service!=null && service.desiredCount()
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java` line 521 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgLWraq5ovp2KbiGhG7:-NgLw7Sq9qP6Tc3MiZP0:b-qicn3k) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsCommandTaskNGHelper.java#L521)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

It's not a complex expression but used compiled pattern. Add Pattern.compile(pattern) as a static class variable.
</blockquote></details>

here,  string pattern can change [...]

2023-10-10 01:24 UTC, PragyeshMishra01 commented
trigger messagecheck

2023-10-10 01:24 UTC, PragyeshMishra01 commented
trigger uts

2023-10-10 04:34 UTC, PragyeshMishra01 commented
trigger uts

2023-10-10 05:53 UTC, piyush-bhuwalka approved these changes

2023-10-10 07:01 UTC, ivan-83 requested changes
> Reviewed 14 of 16 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53836)* status: 33 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/53836#-NgFOEkS1aqm23C5f8nh:-NgNMFTcEXO5NZRaQ25T:b-tbbeaa) ([raw file](https://github.com/harness/harness-core/blob/dab39f85f82f36cb897bc505d28347aaaa19a0ac/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsBasicRollbackStep.java#L107)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

Done, removed it from step outcome
</blockquote></details>

It should be part of the step outcome in order to be consumed by fqn in the next stage steps, not written explicitly in executionSweepingOutputService.consume.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsServiceSetupStep.java` line 196 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgNMz1B2OQRfA8lJRJK:-NgNMz1B2OQRfA8lJRJL:b-7c7iqw) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsServiceSetupStep.java#L196)):*
> ```Java
>         .stepOutcome(StepResponse.StepOutcome.builder()
>                          .name(OutcomeExpressionConstants.OUTPUT)
>                          .outcome(ecsServiceSetupOutcome)
> ```

the same here.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/53836#-NgNNDuxAtwndzUpFK0T:-NgNNDuxAtwndzUpFK0U:b-u1chs7) ([raw file](https://github.com/harness/harness-core/blob/97cbe0c8038a8e9bd066a55916a87466d713d72f/125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsUpgradeContainerStep.java#L126)):*
> ```Java
>                          .stepOutcome(StepResponse.StepOutcome.builder()
>                                           .name(OutcomeExpressionConstants.OUTPUT)
>                                           .outcome(upgradeContainerOutcome)
> ```

the same as above.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsUtils.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/53836#-NgNNjg96wazQtUqCFS0:-NgNNjg96wazQtUqCFS1:b-4denuv) ([raw file](https://github.com/harness/harness-core/blob/cc676bd8d2495065aef0ae26c2018821607b0391/930-delegate-tasks/src/main/java/io/harness/delegate/task/ecs/EcsUtils.java#L35)):*
> ```Java
>           return Integer.parseInt(name.substring(index + DELIMITER.length()));
>         } catch (NumberFormatException e) {
>           throw new InvalidRequestException("Invalid revision in service name. ");
> ```

Minor: Add service name to log msg.


<!-- Sent from Reviewable.io -->

2023-10-10 11:17 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53836#-:-NgOIYSJ2u5rwHaA1-C3:bnfp4nl)* status: 33 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-10 11:46 UTC, PragyeshMishra01 commented
trigger uts

2023-10-10 11:49 UTC, PragyeshMishra01 commented
trigger uts

2023-10-10 12:25 UTC, piyush-bhuwalka approved these changes

2023-10-10 12:26 UTC, PragyeshMishra01 commented
trigger review

2023-10-10 12:48 UTC, merged