fix: [CDS-80454]: adds proper handling for the timeout issues with Git
harness/harness-core pull request #53853
Opened 2023-10-06 14:36 UTC by sandeshsalunkhegh

fix: [CDS-80454]: adds proper handling for the timeout issues with Git where we make requests via SCM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 07:22 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJAeb0W8KpNVAe_Gn:-NgIJAeb0W8KpNVAe_Go:b-srnzp9) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java#L20)):*
> ```Java
>   public final String FILE_NOT_FOUND_ERROR = "File not found";
>   public final String CREATE_PULL_REQUEST_FAILURE = "Issue while creating pull request";
>   public final String REQUEST_TIMEOUT_FAILURE = "Request timed out at the Server end";
> ```

at the "GIT" server end


<!-- Sent from Reviewable.io -->

2023-10-09 07:22 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreatePullRequestScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJDFCDqp0VkODaN9Y:-NgIJDFCDqp0VkODaN9Z:b-9bmbq2) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreatePullRequestScmApiErrorHandler.java#L35)):*
> ```Java
> 
>   // TODO: Modify the HINT body
>   public static final String REQUEST_TIMED_OUT_HINT = "Please check the following:\n"
> ```

changes should be in GetFileSCMAPIErrorHandler for all git providers


<!-- Sent from Reviewable.io -->

2023-10-09 07:22 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1081 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJH7G1bxeJSESWamJ:-NgIJH7G1bxeJSESWamK:b-8c8jwk) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1081)):*
> ```Java
>       }
> 
>       Thread.sleep(65000);
> ```

this is just for testing purpose


<!-- Sent from Reviewable.io -->

2023-10-09 07:25 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1124 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJjih-tsaf33acz22:-NgIJjih-tsaf33acz23:b-q86lg5) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1124)):*
> ```Java
>           .error(exception.getMessage())
>           .statusCode(exception instanceof SCMRuntimeException ? Constants.SCM_SERVER_TIMEOUT_ERROR_CODE
>                                                                : Constants.SCM_INTERNAL_SERVER_ERROR_CODE)
> ```

if (exception is scmException), then use status code from scm excpetion ((ScmException) exception .getErrorCode())
else statusCode = INTERNAL SERVER ERROR


<!-- Sent from Reviewable.io -->

2023-10-09 07:26 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1124 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJjih-tsaf33acz22:-NgIK27U-9kv-SPaSqAW:bsibwss) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1124)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if (exception is scmException), then use status code from scm excpetion ((ScmException) exception .getErrorCode())
else statusCode = INTERNAL SERVER ERROR
</blockquote></details>

We should check behaviour if we rethrow ScmRuntimeException, just like we do it for ConnectException inside "checkAndRethrowExceptionIfApplicable(exception);"


<!-- Sent from Reviewable.io -->

2023-10-09 20:40 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreatePullRequestScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJDFCDqp0VkODaN9Y:-NgL9lILCKVZ8I-vlHBt:b-973tmn) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreatePullRequestScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

changes should be in GetFileSCMAPIErrorHandler for all git providers
</blockquote></details>

Added changes to the relevant file.


<!-- Sent from Reviewable.io -->

2023-10-09 20:40 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1081 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJH7G1bxeJSESWamJ:-NgL9qxcBFWy5I1f0vGu:b-tico6t) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1081)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this is just for testing purpose
</blockquote></details>

Removed this.


<!-- Sent from Reviewable.io -->

2023-10-09 20:41 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1124 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJjih-tsaf33acz22:-NgL9vV-EcH26KAy9nDx:br4a0tk) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1124)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should check behaviour if we rethrow ScmRuntimeException, just like we do it for ConnectException inside "checkAndRethrowExceptionIfApplicable(exception);"
</blockquote></details>

Tried it, could not get the Hint or Description to be displayed on the UI.


<!-- Sent from Reviewable.io -->

2023-10-09 20:41 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJAeb0W8KpNVAe_Gn:-NgLA0D11o47XBt6m0ex:b-cszsw0) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

at the "GIT" server end
</blockquote></details>

Modified.


<!-- Sent from Reviewable.io -->

2023-10-10 01:56 UTC, sribalij reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1298 at r2](https://reviewable.io/reviews/harness/harness-core/53853#-NgMHy_VEDZ8qJzhS5Gu:-NgMHy_VEDZ8qJzhS5Gv:busjxxo) ([raw file](https://github.com/harness/harness-core/blob/43caf463c14e3c7c67164bff99170a667f8eddaf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1298)):*
> ```Java
>   private void checkAndRethrowExceptionIfApplicable(Exception exception) throws Exception {
>     if (exception instanceof ConnectException || exception instanceof SCMRuntimeException
>         || exception instanceof GeneralException) {
> ```

Are we logging this somewhere?


<!-- Sent from Reviewable.io -->

2023-10-11 04:58 UTC, senjucanon2 reviewed
> Reviewed 2 of 5 files at r1, 4 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 11 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1298 at r2](https://reviewable.io/reviews/harness/harness-core/53853#-NgMHy_VEDZ8qJzhS5Gu:-NgS5A1t8p_OyJMXmHrb:b-q0lao8) ([raw file](https://github.com/harness/harness-core/blob/43caf463c14e3c7c67164bff99170a667f8eddaf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1298)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Are we logging this somewhere?
</blockquote></details>

Please add a log if not present.


<!-- Sent from Reviewable.io -->

2023-10-12 06:55 UTC, sribalij commented on 930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java
> +            new InvalidRequestException("Request timed out at the Git Server end.", USER));
Shouldn't this be TimeoutException instead of InvalidRequestException?

2023-10-12 06:55 UTC, sribalij requested changes
Added comment

2023-10-18 22:32 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 20 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/53853#gh-1356259892:-Nh3uaF6-7E5ykBbuqBM:bl88nch) ([raw file](https://github.com/harness/harness-core/blob/9e2d70eec9455b0d7c9b75df0c64e1e57e93b883/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L48)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Shouldn't this be TimeoutException instead of InvalidRequestException?
</blockquote></details>

Modified it.
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1124 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJjih-tsaf33acz22:-Nh3uffyEfdvwskc0zec:b116qmv) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1124)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Tried it, could not get the Hint or Description to be displayed on the UI.
</blockquote></details>

Reverted this code.


<!-- Sent from Reviewable.io -->

2023-10-19 11:35 UTC, sandeshsalunkhegh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java
> +            new InvalidRequestException("Request timed out at the Git Server end.", USER));
Modified it.

2023-10-19 19:36 UTC, mohitg0795 commented
*[`952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJAeb0W8KpNVAe_Gn:-Nh8R5unD1KZvfjr3gkc:bq8gvnz) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java#L20)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Modified.
</blockquote></details>

what has been modified here?


<!-- Sent from Reviewable.io -->

2023-10-19 19:38 UTC, mohitg0795 commented
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 73 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RFNJBBzgcrBw6M6o:-Nh8RFNJBBzgcrBw6M6p:bdayt5) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/HintException.java#L73)):*
> ```Java
>       "Please ensure Azure Vault engine have valid permissions";
>   public static final String HINT_REQUEST_TIMED_OUT =
>       "The request to the Git provider failed for some reason, please try again after some time.";
> ```

This hint is vague.

Something better may be simply: "Please try again or connect to Harness Support Team"


<!-- Sent from Reviewable.io -->

2023-10-19 19:39 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 20 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 25 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RbRw-NR7jBQoY4Vy:-Nh8RbRw-NR7jBQoY4Vz:b-ud17j0) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L25)):*
> ```Java
>   public static final String EXPLANATION_EMPTY_ACCESS_KEY = "Access Key cannot be empty";
>   public static final String EXPLANATION_REQUEST_TIMED_OUT =
>       "There was issue while performing this operation. The request to the Git provider failed for some reason.";
> ```

The explanation is vague.

It should mention clearly that the request timed out on GIT server end.


<!-- Sent from Reviewable.io -->

2023-10-19 19:40 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 20 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RyXf33XYg0Ww5rLd:-Nh8RyXf33XYg0Ww5rLe:b-ysy90r) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java#L20)):*
> ```Java
> 
>   public ScmRequestTimeoutException(String errorMessage) {
>     super(errorMessage, new RequestTimeoutException("Request timed out at the Git Server end.", USER),
> ```

what are we trying to do here?


<!-- Sent from Reviewable.io -->

2023-10-19 19:41 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 20 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/53853#gh-1356259892:-Nh8SGWu4WU9EEZDbYL1:bwruawi) ([raw file](https://github.com/harness/harness-core/blob/9e2d70eec9455b0d7c9b75df0c64e1e57e93b883/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L48)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Modified it.
</blockquote></details>

We should use the error message from incoming exception


<!-- Sent from Reviewable.io -->

2023-10-19 19:44 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 20 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java` line 86 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8Sup88axq91U-C_5y:-Nh8Sup88axq91U-C_5z:bc26c1l) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java#L86)):*
> ```Java
>             ErrorMessageFormatter.formatMessage(HintException.HINT_REQUEST_TIMED_OUT, errorMetadata),
>             ErrorMessageFormatter.formatMessage(ExplanationException.EXPLANATION_REQUEST_TIMED_OUT, errorMetadata),
>             new ScmRequestTimeoutException(REQUEST_TIMEOUT_FAILURE));
> ```

we should use errorMessage from the arguments


<!-- Sent from Reviewable.io -->

2023-10-20 02:38 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 20 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RyXf33XYg0Ww5rLd:-Nh9umqCAsL5-8LDZ2vx:b-8gl00a) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what are we trying to do here?
</blockquote></details>

In `SCMExceptionHandler.java`, we are using `RequestTimeoutException`, and in `GithubCreatePullRequestScmApiErrorHandler.java` and other such files, we are using `ScmRequestTimeoutException`.
I think there should be only one exception class which should address for both the scenarios, but then `RequestTimeoutException` can also be used at other different places, and not just limited to SCM.
What are your views on this @mohitg0795 ?
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1298 at r2](https://reviewable.io/reviews/harness/harness-core/53853#-NgMHy_VEDZ8qJzhS5Gu:-Nh9wLikBC_7Ph0G-RoV:bvmefun) ([raw file](https://github.com/harness/harness-core/blob/43caf463c14e3c7c67164bff99170a667f8eddaf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1298)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Please add a log if not present.
</blockquote></details>

What should we be logging here? That there was an exception thrown, and should the Exception type also be mentioned there?
___
*[`952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/53853#-NgIJAeb0W8KpNVAe_Gn:-Nh9tay_1YK22ap62pz1:by3ecc5) ([raw file](https://github.com/harness/harness-core/blob/cd858388627d6573e51a78bee4c510f9455b6a21/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what has been modified here?
</blockquote></details>

A constant was added earlier, but then removed, the code got reverted as this was irrelevant place to keep that constant.


<!-- Sent from Reviewable.io -->

2023-10-20 03:04 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 21 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java` line 86 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8Sup88axq91U-C_5y:-NhA1Omy86fdoWjRd8vT:b-jbxy66) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java#L86)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should use errorMessage from the arguments
</blockquote></details>

Modified to use that errorMessage if present.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/53853#gh-1356259892:-NhA1UDEEw70KZp-IN6w:b5ps7w5) ([raw file](https://github.com/harness/harness-core/blob/9e2d70eec9455b0d7c9b75df0c64e1e57e93b883/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should use the error message from incoming exception
</blockquote></details>

Modified to use the error message from incoming exception if present.
___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 25 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RbRw-NR7jBQoY4Vy:-NhA1dOfDOQsownE3hs3:b-lrgakj) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The explanation is vague.

It should mention clearly that the request timed out on GIT server end.
</blockquote></details>

Modified the explanation for Request Timeout.
___
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 73 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RFNJBBzgcrBw6M6o:-NhA1iPcCeG7Q8mzN5JY:bri4nsd) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/HintException.java#L73)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This hint is vague.

Something better may be simply: "Please try again or connect to Harness Support Team"
</blockquote></details>

Modified the hint for Request Timeout.


<!-- Sent from Reviewable.io -->

2023-10-20 09:04 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 21 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java` line 77 at r9](https://reviewable.io/reviews/harness/harness-core/53853#-NhBK4Di2CHSSfmdWliY:-NhBK4Di2CHSSfmdWliZ:b-oj6tca) ([raw file](https://github.com/harness/harness-core/blob/5772394550fa5c233228f705887603d7b49ba4e9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java#L77)):*
> ```Java
>             ErrorMessageFormatter.formatMessage(ExplanationException.EXPLANATION_REQUEST_TIMED_OUT, errorMetadata),
>             new ScmRequestTimeoutException(
>                 errorMessage == null || EmptyPredicate.isEmpty(errorMessage) ? REQUEST_TIMEOUT_FAILURE : errorMessage));
> ```

we should only use "errorMessage". Null checks and other handling on the error message is already done on other layers.


<!-- Sent from Reviewable.io -->

2023-10-20 09:13 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 21 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java` line 64 at r9](https://reviewable.io/reviews/harness/harness-core/53853#-NhBMBqW6LTqM378-_nn:-NhBMBqW6LTqM378-_no:bfhnheu) ([raw file](https://github.com/harness/harness-core/blob/5772394550fa5c233228f705887603d7b49ba4e9/952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java#L64)):*
> ```Java
>         return new ConnectException(errorMessage, WingsException.USER);
>       } else if (sre.getStatus().getCode() == Status.Code.CANCELLED) {
>         return new SCMRuntimeException("SCM request timed out with: " + errorMessage, ErrorCode.REQUEST_TIMEOUT);
> ```

SCMTimeoutException


<!-- Sent from Reviewable.io -->

2023-10-20 09:16 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 21 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 25 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RbRw-NR7jBQoY4Vy:-NhBMmkGDL0t3WUFJCKH:b-sbxjr0) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L25)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Modified the explanation for Request Timeout.
</blockquote></details>

This shouldn't be present in common class as error message isn't generic. We have our own classes for explanations and hints where we can put this one.


<!-- Sent from Reviewable.io -->

2023-10-20 09:16 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 21 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 73 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RFNJBBzgcrBw6M6o:-NhBMsOz8kPqWh4XIt2V:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/HintException.java#L73)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Modified the hint for Request Timeout.
</blockquote></details>

same as above


<!-- Sent from Reviewable.io -->

2023-10-20 10:48 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 21 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java` line 77 at r9](https://reviewable.io/reviews/harness/harness-core/53853#-NhBK4Di2CHSSfmdWliY:-NhBgF7h7W-0B-znft15:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5772394550fa5c233228f705887603d7b49ba4e9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java#L77)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should only use "errorMessage". Null checks and other handling on the error message is already done on other layers.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java` line 86 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8Sup88axq91U-C_5y:-NhBgHca2XF6HKmhQAiv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java#L86)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Modified to use that errorMessage if present.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/53853#gh-1356259892:-NhBgIUy0EqP7DsfKOoB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9e2d70eec9455b0d7c9b75df0c64e1e57e93b883/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L48)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Modified to use the error message from incoming exception if present.
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java` line 20 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RyXf33XYg0Ww5rLd:-NhBgJPp728fsjv72sbn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java#L20)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

In `SCMExceptionHandler.java`, we are using `RequestTimeoutException`, and in `GithubCreatePullRequestScmApiErrorHandler.java` and other such files, we are using `ScmRequestTimeoutException`.
I think there should be only one exception class which should address for both the scenarios, but then `RequestTimeoutException` can also be used at other different places, and not just limited to SCM.
What are your views on this @mohitg0795 ?
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1298 at r2](https://reviewable.io/reviews/harness/harness-core/53853#-NgMHy_VEDZ8qJzhS5Gu:-NhBg7f906hFWsAQLpik:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/43caf463c14e3c7c67164bff99170a667f8eddaf/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1298)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

What should we be logging here? That there was an exception thrown, and should the Exception type also be mentioned there?
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java` line 64 at r9](https://reviewable.io/reviews/harness/harness-core/53853#-NhBMBqW6LTqM378-_nn:-NhBgBqP4zyYmm_Fsv0v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5772394550fa5c233228f705887603d7b49ba4e9/952-scm-java-client/src/main/java/io/harness/utils/ScmGrpcClientUtils.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

SCMTimeoutException
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 25 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RbRw-NR7jBQoY4Vy:-NhBgCzAD6Qk8YGNn2Kx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This shouldn't be present in common class as error message isn't generic. We have our own classes for explanations and hints where we can put this one.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 73 at r7](https://reviewable.io/reviews/harness/harness-core/53853#-Nh8RFNJBBzgcrBw6M6o:-NhBgDWUDziImZeF2u6r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d39e9822fa2a92f4d1e66f131babcb917bc742be/980-commons/src/main/java/io/harness/exception/HintException.java#L73)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-20 12:48 UTC, senjucanon2 submitted a review, later dismissed
> Reviewed 1 of 8 files at r5, 1 of 1 files at r7, 1 of 15 files at r8, 2 of 23 files at r10, 6 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 36 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java` line 29 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6DW09Mk2gXntUYnI:-NhC6DW09Mk2gXntUYnJ:b-qwmp2d) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java#L29)):*
> ```Java
>       "The credentials provided in the Azure connector<CONNECTOR> do not have correct permissions.";
>   public static final String WRONG_REPO_OR_BRANCH = "The provided branch<BRANCH> or the repo<REPO> are invalid.";
>   public static final String EXPLANATION_REQUEST_TIMED_OUT = "Request timed out at the Ado Server end.";
> ```

We can have a better message something like: "Request to the Ado Server Timed out".
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java` line 30 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6RgwBhfHRGVz3rsv:-NhC6RgwBhfHRGVz3rsw:b-s2bj8i) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java#L30)):*
> ```Java
>   public static final String HINT_REQUEST_TIMED_OUT =
>       "Please try again after some time, or connect to Harness Support Team.";
> }
> ```

Let us remove contact Harness Support team, If we are sure that request has timed out, then have only timed out message.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java` line 34 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6aE89IkgzU267F73:-NhC6aE89IkgzU267F74:b-yrtgn0) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java#L34)):*
> ```Java
>   public static final String OAUTH_ACCESS_DENIED =
>       "If you are using OAUTH, access to Bitbucket may have been revoked or token is invalid or expired.";
>   public static final String EXPLANATION_REQUEST_TIMED_OUT = "Request timed out at the BitBucket Cloud Server end.";
> ```

Same as Above
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java` line 37 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6brQEXCrLOMKzpqy:-NhC6brQEXCrLOMKzpqz:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java#L37)):*
> ```Java
>   public static final String HINT_REQUEST_TIMED_OUT =
>       "Please try again after some time, or connect to Harness Support Team.";
> }
> ```

Same as above
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java` line 33 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6gxH4HZ-kXhmsdse:-NhC6gxH4HZ-kXhmsdsf:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java#L33)):*
> ```Java
>       "If you are using OAUTH, access to Github may have been revoked or token is invalid or expired.";
>   public static final String EXPLANATION_REQUEST_TIMED_OUT = "Request timed out at the Git Server end.";
> }
> ```

Same as above


<!-- Sent from Reviewable.io -->

2023-10-20 13:01 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 36 file(s) to review. 3 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java` line 29 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6DW09Mk2gXntUYnI:-NhCA4b91nH2RS1wrX3k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java#L29)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

We can have a better message something like: "Request to the Ado Server Timed out".
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java` line 30 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6RgwBhfHRGVz3rsv:-NhC9y781w_JLVcF3OhB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java#L30)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Let us remove contact Harness Support team, If we are sure that request has timed out, then have only timed out message.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java` line 34 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6aE89IkgzU267F73:-NhC9zw21-DRc9McSiyU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java#L34)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Same as Above
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java` line 37 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6brQEXCrLOMKzpqy:-NhCA-WvBGphA2AaPihI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java#L37)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java` line 33 at r11](https://reviewable.io/reviews/harness/harness-core/53853#-NhC6gxH4HZ-kXhmsdse:-NhCA-uL1mUlW1gJBFM5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69a9e0e91a918879a072bcf06586e8abc1fd679b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorExplanations.java#L33)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-22 19:40 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 42 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java` line 29 at r13](https://reviewable.io/reviews/harness/harness-core/53853#-NhNteQI3L32CE6cVB6S:-NhNteQI3L32CE6cVB6T:b-sz3amk) ([raw file](https://github.com/harness/harness-core/blob/6cf8fab64835cec74acc755c4c575b67de5ca9b5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java#L29)):*
> ```Java
>       "The credentials provided in the Azure connector<CONNECTOR> do not have correct permissions.";
>   public static final String WRONG_REPO_OR_BRANCH = "The provided branch<BRANCH> or the repo<REPO> are invalid.";
>   public static final String EXPLANATION_REQUEST_TIMED_OUT = "Request to the Ado Server Timed out.";
> ```

Its not Ado server, its "Azure server" or "Azure GIT server"


<!-- Sent from Reviewable.io -->

2023-10-22 19:40 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 42 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java` line 29 at r13](https://reviewable.io/reviews/harness/harness-core/53853#-NhNtlwo2aQcQ0oFjYc_:-NhNtlwo2aQcQ0oFjYca:b-5h08c7) ([raw file](https://github.com/harness/harness-core/blob/6cf8fab64835cec74acc755c4c575b67de5ca9b5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java#L29)):*
> ```Java
>       "Please check if the provided branch<BRANCH> or the Azure repo name<REPO> are valid.";
>   public static final String HINT_REQUEST_TIMED_OUT =
>       "Request to the Ado Server Timed out, please try again after some time. If the problem persists, please connect to Harness Support Team.";
> ```

same here.


<!-- Sent from Reviewable.io -->

2023-10-22 19:40 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 42 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java` line 29 at r13](https://reviewable.io/reviews/harness/harness-core/53853#-NhNtlwo2aQcQ0oFjYc_:-NhNtrqk8_1FXJ3KTIZ5:b-90daj9) ([raw file](https://github.com/harness/harness-core/blob/6cf8fab64835cec74acc755c4c575b67de5ca9b5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

"Please contact Harness Support Team"


<!-- Sent from Reviewable.io -->

2023-10-22 19:45 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 42 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 51 at r13](https://reviewable.io/reviews/harness/harness-core/53853#-NhNuuez-3IoVZ5HudFZ:-NhNuuez-3IoVZ5HudF_:bxpf32o) ([raw file](https://github.com/harness/harness-core/blob/6cf8fab64835cec74acc755c4c575b67de5ca9b5/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L51)):*
> ```Java
>             new RequestTimeoutException(
>                 (exception.getMessage() == null || exception.getMessage().isEmpty()
>                         ? "Request to the Server Timed out, please try again after some time. If the problem persists, please connect to Harness Support Team."
> ```

Request to "SCM" server timed out....


<!-- Sent from Reviewable.io -->

2023-10-23 07:51 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 42 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java` line 29 at r13](https://reviewable.io/reviews/harness/harness-core/53853#-NhNteQI3L32CE6cVB6S:-NhQW0zHD17l9YkpDwH5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6cf8fab64835cec74acc755c4c575b67de5ca9b5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorExplanations.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Its not Ado server, its "Azure server" or "Azure GIT server"
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java` line 29 at r13](https://reviewable.io/reviews/harness/harness-core/53853#-NhNtlwo2aQcQ0oFjYc_:-NhQW0S92OCCBrTRuoHi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6cf8fab64835cec74acc755c4c575b67de5ca9b5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/ScmErrorHints.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

"Please contact Harness Support Team"
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 51 at r13](https://reviewable.io/reviews/harness/harness-core/53853#-NhNuuez-3IoVZ5HudFZ:-NhQW1fd0IAKWk88ZE_5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6cf8fab64835cec74acc755c4c575b67de5ca9b5/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Request to "SCM" server timed out....
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-24 09:41 UTC, sandeshsalunkhegh commented
With changes in this PR:
![image](https://github.com/harness/harness-core/assets/22246973/91b0f5c5-d1d0-435a-9481-27e07f7f9ff9)
Without changes in this PR:
![image](https://github.com/harness/harness-core/assets/22246973/7da4bb0d-d595-4490-bca2-0b1486fa61b8)

2023-11-07 20:07 UTC, sandeshsalunkhegh reviewed
> Reviewed 1 of 5 files at r1, 1 of 6 files at r2, 1 of 8 files at r5, 1 of 1 files at r7, 1 of 15 files at r8, 10 of 23 files at r10, 4 of 12 files at r11, 3 of 10 files at r12, 5 of 10 files at r13, 7 of 9 files at r14, 5 of 6 files at r15, 1 of 2 files at r16, 1 of 3 files at r17, 6 of 6 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 47 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-11-08 06:02 UTC, sandeshsalunkhegh reviewed
> Reviewed 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 47 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-11-09 07:23 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 47 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java` line 34 at r21](https://reviewable.io/reviews/harness/harness-core/53853#-NimxdqgCytGrOtz7-jn:-Nimxdqh4x232lMCk4j1:bv2k2uy) ([raw file](https://github.com/harness/harness-core/blob/527a4d93eb27a3b0713799359de686ff7280fe22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java#L34)):*
> ```Java
>       "Error while getting requested file<FILEPATH> from repo<REPO> and branch<BRANCH> from Github : ";
>   private static final String GITHUB_REQUEST_TIMEOUT_ERROR_MESSAGE =
>       "Failed to fetch file: file<FILEPATH>. Request to the Github Server Timed out. ";
> ```

don't need filepath here


<!-- Sent from Reviewable.io -->

2023-11-09 07:23 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 47 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java` line 56 at r21](https://reviewable.io/reviews/harness/harness-core/53853#-Nimxg3nCtFFHoOJzYSd:-Nimxg3nCtFFHoOJzYSe:bg6mxge) ([raw file](https://github.com/harness/harness-core/blob/527a4d93eb27a3b0713799359de686ff7280fe22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java#L56)):*
> ```Java
>             ErrorMessageFormatter.formatMessage(
>                 (EmptyPredicate.isEmpty(errorMetadata.getBranchName())
>                         ? ScmErrorExplanations.EXPLANATION_REQUEST_TIMED_OUT_DEFAULT_BRANCH_PREFIX
> ```

don't need handling for default branch


<!-- Sent from Reviewable.io -->

2023-11-09 07:25 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 47 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorHints.java` line 32 at r21](https://reviewable.io/reviews/harness/harness-core/53853#-Nimy2oJDrgnbp7TinFe:-Nimy2oJDrgnbp7TinFf:b165hsa) ([raw file](https://github.com/harness/harness-core/blob/527a4d93eb27a3b0713799359de686ff7280fe22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorHints.java#L32)):*
> ```Java
>   public static final String HINT_REQUEST_TIMED_OUT = "Please try these out: \n"
>       + "1. Check if Github server is working as expected from GitHub's status page (https://www.githubstatus.com/)\n"
>       + "2. Check if your selected delegates are able to connect to the github server\n"
> ```

we can't say "selected"


<!-- Sent from Reviewable.io -->

2023-11-09 10:33 UTC, sandeshsalunkhegh reviewed
> Reviewed 20 of 20 files at r21, 4 of 4 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 47 file(s) to review. 3 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java` line 34 at r21](https://reviewable.io/reviews/harness/harness-core/53853#-NimxdqgCytGrOtz7-jn:-Nind5s86ratB489X5z3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/527a4d93eb27a3b0713799359de686ff7280fe22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

don't need filepath here
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java` line 56 at r21](https://reviewable.io/reviews/harness/harness-core/53853#-Nimxg3nCtFFHoOJzYSd:-Nind7Qt8t5r7Uz8C_NB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/527a4d93eb27a3b0713799359de686ff7280fe22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetFileScmApiErrorHandler.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

don't need handling for default branch
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorHints.java` line 32 at r21](https://reviewable.io/reviews/harness/harness-core/53853#-Nimy2oJDrgnbp7TinFe:-Nind9OD1XbYc6qNcs4O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/527a4d93eb27a3b0713799359de686ff7280fe22/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/ScmErrorHints.java#L32)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can't say "selected"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 06:17 UTC, sandeshsalunkhegh commented
New error response for Timeouts
![image](https://github.com/harness/harness-core/assets/22246973/e5792c48-1d02-4a64-a333-b48b1384824c)

2023-11-10 07:51 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 445 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisCdmwCvBTiFVFGf_k:-NisCdmwCvBTiFVFGf_l:bjo1nmx) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L445)):*
> ```Java
> 
>   protected String getErrorMessageForRuntimeExceptions(GitOperation gitOperation) {
>     return getErrorMessageForRuntimeExceptions(gitOperation, null);
> ```

why do we require all these things?


<!-- Sent from Reviewable.io -->

2023-11-10 07:52 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 46 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisCzBO-Sx-_8gRYfzA:-NisCzBO-Sx-_8gRYfzB:b-owswfu) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L46)):*
> ```Java
>             ExplanationException.EXPLANATION_SCM_INVALID_REQUEST,
>             new InvalidRequestException("SCM service running with delegate has error", USER));
>       case REQUEST_TIMEOUT:
> ```

we don't need these changes now, right?


<!-- Sent from Reviewable.io -->

2023-11-10 07:53 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java` line 22 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDB3y53R8QdYXURat:-NisDB3y53R8QdYXURau:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java#L22)):*
> ```Java
>     super(errorMessage, null, errorCode);
>     super.param(MESSAGE_ARG, errorMessage);
>   }
> ```

line spacing missing


<!-- Sent from Reviewable.io -->

2023-11-10 07:55 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java` line 19 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDK0D10LluDMtTKv8:-NisDK0D10LluDMtTKv9:b-brv5pf) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java#L19)):*
> ```Java
>   private static final String MESSAGE_ARG = "message";
> 
>   public ScmRequestTimeoutException(String errorMessage, ErrorCode errorCode) {
> ```

Instead of adding constructor which allows any error code, can we just do something to ensure there's only single error code allowed here which is 400.

My idea is that our use-case has only 2 cases : either its 504 or 400. So, by default it should always be 504 only. But if someone wants to reset, they can do it explicitly but only to 400. Lets make changes for it.


<!-- Sent from Reviewable.io -->

2023-11-10 07:55 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmUnexpectedException.java` line 16 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisD_Fj1aNw98O1LDwf:-NisD_Fj1aNw98O1LDwg:b-4w3bax) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/exception/ScmUnexpectedException.java#L16)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> public class ScmUnexpectedException extends ScmException {
>   private static final String MESSAGE_ARG = "message";
> ```

please add line spacing


<!-- Sent from Reviewable.io -->

2023-11-10 07:56 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 92 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDtn45wQKd78L1FFi:-NisDtn5EArRwyBMNaGJ:b-aajeco) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L92)):*
> ```Java
>   public static String INVALID_LDAP_AUTH_EMAIL_PWD =
>       "The email, password value supplied for the configured Ldap settings is incorrect";
>   public static final String EXPLANATION_REQUEST_TIMED_OUT = "Request to the Server Timed out.";
> ```

where's this message being used?


<!-- Sent from Reviewable.io -->

2023-11-10 07:56 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 156 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDwElDNa8zx7z4RTu:-NisDwElDNa8zx7z4RTv:b-986nif) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/HintException.java#L156)):*
> ```Java
>       "1) Please check if account level setting is expected to be enabled. \n2) Please check if requested input-set is in same repository as the linked pipeline.";
>   public static final String HINT_DOCKER_HUB_INVALID_IMAGE_PATH = "No tag found for given Image Path";
>   public static final String HINT_REQUEST_TIMED_OUT =
> ```

are we using these messages?


<!-- Sent from Reviewable.io -->

2023-11-10 07:57 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`980-commons/src/main/java/io/harness/exception/RequestTimeoutException.java` line 20 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDydSBBDeygTHzmj5:-NisDydSBBDeygTHzmj6:bd1o92u) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/RequestTimeoutException.java#L20)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
>     components = {HarnessModuleComponent.CDS_FIRST_GEN, HarnessModuleComponent.CDS_PIPELINE})
> public class RequestTimeoutException extends WingsException {
> ```

are we using this class now?


<!-- Sent from Reviewable.io -->

2023-11-10 07:58 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1131 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisE97R2O0LA4mt_Uiz:-NisE97R2O0LA4mt_Uj-:btld49) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1131)):*
> ```Java
>       checkAndRethrowExceptionIfApplicable(exception);
>       int statusCode = Constants.SCM_INTERNAL_SERVER_ERROR_CODE;
>       if (exception instanceof SCMTimeoutException) {
> ```

we aren't throwing ScmTimeoutException from anywhere but we are catching it here. How is it working? Can you please check.


<!-- Sent from Reviewable.io -->

2023-11-10 07:58 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`980-commons/src/main/java/io/harness/exception/runtime/SCMTimeoutException.java` line 19 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisEG6F7B81n8oM4Sc0:-NisEG6G7Oa_SquSOZHt:b-crp41r) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/runtime/SCMTimeoutException.java#L19)):*
> ```Java
> @Builder
> @EqualsAndHashCode(callSuper = true)
> public class SCMTimeoutException extends RuntimeException {
> ```

do we need this class?


<!-- Sent from Reviewable.io -->

2023-11-10 08:33 UTC, sandeshsalunkhegh reviewed
> Reviewed 2 of 4 files at r23, 4 of 4 files at r24, 3 of 3 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 3 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 445 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisCdmwCvBTiFVFGf_k:-NisEy7K6i_ZMaPoN3HZ:b-tygpy) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L445)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we require all these things?
</blockquote></details>

This was added to handle the message creation when we were throwing the exception instead of creating the response.
As now we are not throwing it, we no longer need it. Clearing this up.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java` line 46 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisCzBO-Sx-_8gRYfzA:-NisHG6I6JwT2nt0VVap:b4sqejd) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we don't need these changes now, right?
</blockquote></details>

No, we don't need it now. Removing it.
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java` line 19 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDK0D10LluDMtTKv8:-NisMFVZ1ZZwZKnsc5pr:b-1rccrc) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java#L19)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Instead of adding constructor which allows any error code, can we just do something to ensure there's only single error code allowed here which is 400.

My idea is that our use-case has only 2 cases : either its 504 or 400. So, by default it should always be 504 only. But if someone wants to reset, they can do it explicitly but only to 400. Lets make changes for it.
</blockquote></details>

Please check the current implementation and let me know if it works.
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java` line 22 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDB3y53R8QdYXURat:-NisIjiR-FXRZRgfdVWQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/exception/ScmRequestTimeoutException.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmUnexpectedException.java` line 16 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisD_Fj1aNw98O1LDwf:-NisIojj-SA6zDVPH1Y5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/exception/ScmUnexpectedException.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please add line spacing
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1131 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisE97R2O0LA4mt_Uiz:-NisKagZ7YdMoVPvwoK-:bdfietc) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1131)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we aren't throwing ScmTimeoutException from anywhere but we are catching it here. How is it working? Can you please check.
</blockquote></details>

Modified to ScmRequestTimeoutException as we are throwing that.
___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 92 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDtn45wQKd78L1FFi:-NisL0ZL9sV3OMR0d-8i:btstfaz) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L92)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

where's this message being used?
</blockquote></details>

It was being used in SCMExceptionHandler with our previous implementation, removing it now as it is no longer needed.
___
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 156 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDwElDNa8zx7z4RTu:-NisLOXj0oT_qO9hE7tq:btstfaz) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/HintException.java#L156)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

are we using these messages?
</blockquote></details>

It was being used in SCMExceptionHandler with our previous implementation, removing it now as it is no longer needed.
___
*[`980-commons/src/main/java/io/harness/exception/RequestTimeoutException.java` line 20 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisDydSBBDeygTHzmj5:-NisLddr3ycY4a9pKU3R:bpr6oh1) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/RequestTimeoutException.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

are we using this class now?
</blockquote></details>

It was being used with our previous implementation, removing the file as no longer needed.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/SCMTimeoutException.java` line 19 at r24](https://reviewable.io/reviews/harness/harness-core/53853#-NisEG6F7B81n8oM4Sc0:-NisLvz20940Y1SV4TZ7:bpr6oh1) ([raw file](https://github.com/harness/harness-core/blob/790f1c044daaf437d2bf7fb15c9ba52b99d6f0bb/980-commons/src/main/java/io/harness/exception/runtime/SCMTimeoutException.java#L19)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

do we need this class?
</blockquote></details>

It was being used with our previous implementation, removing the file as no longer needed.


<!-- Sent from Reviewable.io -->

2023-11-11 21:33 UTC, mohitg0795 approved these changes
> Reviewed 1 of 5 files at r1, 1 of 6 files at r2, 1 of 8 files at r5, 9 of 23 files at r10, 16 of 20 files at r21, 2 of 4 files at r22, 1 of 4 files at r23, 1 of 4 files at r24, 2 of 3 files at r25, 17 of 17 files at r26, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 49 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-11-13 06:11 UTC, adivishy1 approved these changes
> Reviewed 1 of 5 files at r1, 1 of 6 files at r2, 1 of 8 files at r5, 9 of 23 files at r10, 16 of 20 files at r21, 2 of 4 files at r22, 1 of 4 files at r23, 1 of 4 files at r24, 2 of 3 files at r25, 17 of 17 files at r26, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 2 change requests. 2. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-11-13 06:16 UTC, sandeshsalunkhegh reviewed
> Reviewed 17 of 17 files at r26, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 2 change requests. 2. unresolved discussions. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-11-13 07:18 UTC, adivishy1 approved these changes
> Reviewed 2 of 2 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53853)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-11-13 08:02 UTC, mohitg0795 approved these changes

2023-11-13 08:08 UTC, sandeshsalunkhegh commented
@sribalij I've addressed the requested changes.
CC: @mohitg0795

2023-11-13 08:13 UTC, merged