[fix]: [CDS-80573]: Added loggers to understand the Webhook listener failures
harness/harness-core pull request #53875
Opened 2023-10-09 05:16 UTC by adivishy1

## Describe your changes
Adder more loggers to understand the webhook listener failures. Have checked in QA after the recent fixes, we are not seeing the error, just to be on the safe side have added more loggers if the error occurs in future.
 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 05:22 UTC, adivishy1 commented
trigger messagecheck

2023-10-09 05:25 UTC, adivishy1 commented
trigger messagecheck

2023-10-09 07:15 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java
> +              webhookDTO.getParsedResponse().getPush().getRepo().getName()),
nothing would be null here?

2023-10-09 07:44 UTC, adivishy1 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java
> +              webhookDTO.getParsedResponse().getPush().getRepo().getName()),
nope, in case of the push events we are reaching this code, we are using it in few other places as well for push event listeners

2023-10-09 17:43 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java
> +              webhookDTO.getParsedResponse().getPush().getRepo().getName()),
Thanks @adivishy1

2023-10-09 17:43 UTC, sribalij submitted a review, later dismissed

2023-10-09 17:43 UTC, sribalij commented
trigger uts

2023-10-09 17:43 UTC, sribalij commented
trigger review

2023-10-09 20:01 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53875)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/53875#-NgL0mzMDZzuMM0-wv7C:-NgL0mzMDZzuMM0-wv7D:bbkb5f4) ([raw file](https://github.com/harness/harness-core/blob/07ac742bc319225feef8d467d1a6d9aec337bf95/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L86)):*
> ```Java
>         throw new DuplicateFieldException(
>             format(DUP_KEY_EXP_FORMAT_STRING, webhookDTO.getEventId(), webhookDTO.getAccountId()), USER_SRE, ex);
>       } catch (Exception exception) {
> ```

no logging of exception here?


<!-- Sent from Reviewable.io -->

2023-10-09 20:02 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53875)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/53875#-NgL158Q0ViHRWg7SRcG:-NgL158Q0ViHRWg7SRcH:bmx0j6s) ([raw file](https://github.com/harness/harness-core/blob/07ac742bc319225feef8d467d1a6d9aec337bf95/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java#L31)):*
> ```Java
>   public static final String EVENT_STATUS = "eventStatus";
>   public static final String CONTEXT_KEY = "contextKey";
>   public static final String REPO_KEY = "repoNameKey";
> ```

not able to understand, somewhere value is suffixed with "key" while somewhere its not. Please be consistent. I think it shouldn't be suffixed with "key" here.


<!-- Sent from Reviewable.io -->

2023-10-10 04:02 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53875)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/53875#-NgL158Q0ViHRWg7SRcG:-NgMjUKA7_O3q5uLWXOR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07ac742bc319225feef8d467d1a6d9aec337bf95/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

not able to understand, somewhere value is suffixed with "key" while somewhere its not. Please be consistent. I think it shouldn't be suffixed with "key" here.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/53875#gh-1349930622:-NgMjVCw014WMuzdXCyR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07ac742bc319225feef8d467d1a6d9aec337bf95/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/loggers/GitXWebhookEventLogContext.java#L41)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Thanks @adivishy1 
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 84 at r1](https://reviewable.io/reviews/harness/harness-core/53875#-NgL0onJ11nUXDoejstB:-NgMjwNnAuk7BV-ILn2B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07ac742bc319225feef8d467d1a6d9aec337bf95/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L84)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

no logging of exception?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 86 at r1](https://reviewable.io/reviews/harness/harness-core/53875#-NgL0mzMDZzuMM0-wv7C:-NgMjwcy7PzBujLxQbv_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07ac742bc319225feef8d467d1a6d9aec337bf95/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L86)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

no logging of exception here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-10 05:11 UTC, adivishy1 commented
trigger uts

2023-10-10 05:29 UTC, adivishy1 commented
trigger uts

2023-10-10 06:41 UTC, mohitg0795 submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53875)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-10 06:52 UTC, adivishy1 commented
trigger uts

2023-10-10 06:58 UTC, mohitg0795 approved these changes

2023-10-10 07:02 UTC, utkarshchoubey-harness approved these changes

2023-10-10 07:03 UTC, adivishy1 commented
trigger review

2023-10-10 07:52 UTC, adivishy1 commented
trigger ut9

2023-10-10 08:06 UTC, merged