feat: [CDS-78341] Move K8s BG Step service to be AsyncExecutable
harness/harness-core pull request #53905
Opened 2023-10-09 11:29 UTC by alebuh

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 11:43 UTC, alebuh commented
trigger uts

2023-10-10 06:30 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53905)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team,k8s-team. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/CdAsyncChainExecutable.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/53905#-NgNGe6E6LLNlwU9NX-R:-NgNGe6E6LLNlwU9NX-S:brervc5) ([raw file](https://github.com/harness/harness-core/blob/34085de0c59134e9da03737ead0d050aa3d15f76/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/CdAsyncChainExecutable.java#L44)):*
> ```Java
> public class CdAsyncChainExecutable<T extends CdTaskChainExecutable>
>     implements AsyncChainExecutableWithRbac<StepBaseParameters> {
>   @Inject private T cdTaskChainExecutable;
> ```

instead of we injecting this, can we make abstract class of say bluegreenstep step, and both task and async are extending it? this will have clear boundaries
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/CdAsyncExecutable.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/53905#-NgNG7F-6u8nLOAEMHZC:-NgNG7F-6u8nLOAEMHZD:b-7sho66) ([raw file](https://github.com/harness/harness-core/blob/34085de0c59134e9da03737ead0d050aa3d15f76/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/CdAsyncExecutable.java#L35)):*
> ```Java
> @OwnedBy(CDC)
> @Slf4j
> public class CdAsyncExecutable<T extends CdTaskExecutable<ResponseData>> extends AsyncExecutableWithCapabilities {
> ```

why async executable should extend taskExecutable?



_Code quote:_
```Java
CdTaskExecutable
```


<!-- Sent from Reviewable.io -->

2023-10-11 07:00 UTC, alebuh commented
trigger uts

2023-10-11 09:32 UTC, alebuh commented
trigger uts

2023-10-11 10:20 UTC, TarunUba1 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_K8S_ASYNC_STEP_STRATEGY("This Flag enables the usage of ASYNC chain orchestration for K8s step", HarnessTeam.CDP);
we might have to confirm on this FF with rohan

2023-10-11 10:20 UTC, TarunUba1 submitted a review, later dismissed

2023-10-11 10:23 UTC, alebuh commented
trigger ut9

2023-10-12 10:15 UTC, alebuh commented
trigger uts

2023-10-12 10:37 UTC, alebuh commented
trigger uts

2023-10-12 10:44 UTC, abosii-harness approved these changes

2023-10-12 10:48 UTC, abhinavsingh1196 approved these changes

2023-10-12 10:48 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sBlueGreenStepV2.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_K8S})
nit: unitCoverageRequired = false?

2023-10-12 11:28 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sBlueGreenStepV2.java
> +@CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_K8S})
yes, will update it in the next PR

2023-10-12 12:27 UTC, yogesh-chauhan approved these changes

2023-10-12 16:34 UTC, archit-harness reviewed
> Reviewed 3 of 10 files at r1, 2 of 9 files at r2, 1 of 1 files at r3, 5 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53905)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-12 16:44 UTC, archit-harness approved these changes
> Reviewed 2 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53905)* status: 14 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-12 16:45 UTC, alebuh commented
trigger review

2023-10-12 17:11 UTC, jennyjames21 approved these changes

2023-10-12 17:13 UTC, merged