fix: [PL-41065]: Added index for projection query on accounts
harness/harness-core pull request #53909
Opened 2023-10-09 12:51 UTC by tiwaritejas

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 16:47 UTC, tiwaritejas commented
trigger uts

2023-10-20 05:45 UTC, tiwaritejas commented
trigger uts

2023-10-20 05:49 UTC, tiwaritejas commented
trigger messagecheck

2023-10-20 06:03 UTC, sahibaHarness requested changes

2023-10-20 06:03 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/beans/Account.java
> +                .field(AccountKeys.uuid)
Why is a UUID included in a compound index when it's already a unique identifier ? Could you elaborate on the purpose of this index?

2023-10-20 06:13 UTC, tiwaritejas commented on 400-rest/src/main/java/software/wings/beans/Account.java
> +                .field(AccountKeys.uuid)
The query for this is introduced is highlighted in the PR description. For ref, please check - 400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java : getBasicAccountWithLicenseInfoQuery()
Since, this query has projection, it currently does a docs scan for projection. After introducing the above index, the projection can also be done without needing to scan any docs.
This query is used by a periodically running CRON job and also comes up on Mongo slow queries dashboard, hence, this needs an index.

2023-10-20 06:47 UTC, sahibaHarness approved these changes

2023-10-23 06:14 UTC, nishantsaini20 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53909)* status: Some of the checks are too old. 2 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-24 18:54 UTC, merged