fix: [CDS-80960]: Adding description and tags fields through yaml if it is empty in ServiceRequestDTO
harness/harness-core pull request #53917
Opened 2023-10-09 14:28 UTC by namantalaycha10

## Describe your changes
Adding description and tags fields through yaml if it is empty in ServiceRequestDTO

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 14:28 UTC, namantalaycha10 commented
trigger uts

2023-10-10 06:58 UTC, namantalaycha10 commented
trigger uts

2023-10-10 07:22 UTC, namantalaycha10 commented
trigger messagecheck

2023-10-10 12:23 UTC, rafaelmart1ns submitted a review, later dismissed

2023-10-10 12:24 UTC, sarthakkasat approved these changes

2023-10-10 12:24 UTC, namantalaycha10 commented
trigger messagecheck

2023-10-10 12:25 UTC, namantalaycha10 commented
trigger uts

2023-10-10 15:07 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/53917#-NgP77h3Ap7ZxPI7I3tG:-NgP77h3Ap7ZxPI7I3tH:b6b4g70) ([raw file](https://github.com/harness/harness-core/blob/c35f97dc9144c7209259e088cc1e160ca74704c5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L82)):*
> ```Java
>     ngServiceConfig.getNgServiceV2InfoConfig().setName(name);
>     ngServiceConfig.getNgServiceV2InfoConfig().setDescription(description);
>     ngServiceConfig.getNgServiceV2InfoConfig().setTags(tags);
> ```

why do we need these 3 lines ? 


<!-- Sent from Reviewable.io -->

2023-10-10 18:02 UTC, sribalij commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java
> +        throw new InvalidRequestException("Cannot create service ng service config due to " + e.getMessage());
nit: Do you want to also log which service?

2023-10-10 18:02 UTC, sribalij commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java
> +        throw new InvalidRequestException("Cannot create service ng service config due to " + e.getMessage());
Log the error?

2023-10-10 18:06 UTC, sribalij commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java
> +    ngServiceConfig.getNgServiceV2InfoConfig().setDescription(description);
Same for description and tags.

2023-10-10 18:06 UTC, sribalij commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java
> +    ngServiceConfig.getNgServiceV2InfoConfig().setDescription(description);
Are we not already doing it above?

2023-10-10 18:12 UTC, sribalij commented on 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/mappers/ServiceElementMapperTest.java
> +  @Owner(developers = YOGESH)
Change owner

2023-10-10 18:13 UTC, sribalij commented on 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/mappers/ServiceElementMapperTest.java
>    @Test
All add junits to test the exception scenario

2023-10-10 18:13 UTC, sribalij requested changes
Added a few comments

2023-10-11 07:08 UTC, namantalaycha10 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java
> +    ngServiceConfig.getNgServiceV2InfoConfig().setDescription(description);
In case of ServiceRequestDTO it can come are null
thats why we are making sure here that it is set from either ServiceRequestDTO or yaml where it is not null

2023-10-11 07:08 UTC, namantalaycha10 commented
> _[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/53917#-NgP77h3Ap7ZxPI7I3tG:-NgP77h3Ap7ZxPI7I3tH:b6b4g70) ([raw file](https://github.com/harness/harness-core/blob/c35f97dc9144c7209259e088cc1e160ca74704c5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L82)):_
> 
> > ```java
> >     ngServiceConfig.getNgServiceV2InfoConfig().setName(name);
> >     ngServiceConfig.getNgServiceV2InfoConfig().setDescription(description);
> >     ngServiceConfig.getNgServiceV2InfoConfig().setTags(tags);
> > ```
> 
> why do we need these 3 lines ?

yes, as In case of ServiceRequestDTO it can come are null
thats why we are making sure here that it is set from either ServiceRequestDTO or yaml where it is not null

2023-10-11 07:54 UTC, namantalaycha10 commented
trigger uts

2023-10-11 08:42 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/53917#gh-1353074538:-NgStlX366LQgReYZk6W:bb2k4ql) ([raw file](https://github.com/harness/harness-core/blob/c35f97dc9144c7209259e088cc1e160ca74704c5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L57)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Log the error?
</blockquote></details>

Yes, We should log the exception here


<!-- Sent from Reviewable.io -->

2023-10-12 09:01 UTC, namantalaycha10 commented
trigger uts

2023-10-12 09:02 UTC, namantalaycha10 commented
trigger uts

2023-10-16 11:32 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53917)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/mappers/ServiceElementMapperTest.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/53917#-NgP55QVA-P92_lX-v_v:-NgP55QVA-P92_lX-v_w:bletkay) ([raw file](https://github.com/harness/harness-core/blob/c35f97dc9144c7209259e088cc1e160ca74704c5/127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/mappers/ServiceElementMapperTest.java#L50)):*
> ```Java
> 
>   @Test
>   @Owner(developers = YOGESH)
> ```

owner name is not correct


<!-- Sent from Reviewable.io -->

2023-10-16 11:32 UTC, yogesh-chauhan approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53917)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-16 12:28 UTC, sarthakkasat approved these changes

2023-10-16 12:29 UTC, namantalaycha10 commented
trigger review

2023-10-16 15:49 UTC, sribalij approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53917)* status: Some of the checks are too old. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-17 04:37 UTC, merged