feat: [PL-41266,PL-41267]: Centralized notification new entities
harness/harness-core pull request #53949
Opened 2023-10-09 21:05 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-09 23:22 UTC, jennyjames21 commented
trigger uts

2023-10-10 15:19 UTC, jennyjames21 commented
trigger-uts

2023-10-10 16:14 UTC, jennyjames21 commented
trigger uts

2023-10-10 19:49 UTC, jennyjames21 commented
trigger uts

2023-10-16 06:45 UTC, jennyjames21 commented
trigger uts

2023-10-16 06:46 UTC, jennyjames21 commented
> > Reviewed 12 of 19 files at r1, 4 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/53949)_ status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team.
> 
> _[`980-commons/BUILD.bazel` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYxv3VE8X8WXtDiH3l:-NgYxv3W5c8YGsaFKkvZ:b-1l9bka) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/BUILD.bazel#L85)):_
> 
> > ```
> >         "//980-commons/src/main/java/io/harness/morphia:module",
> >         "//980-commons/src/main/java/io/harness/network:module",
> >         "//980-commons/src/main/java/io/harness/notification:module",
> > ```
> 
> Why should commons dependent on notification module?
> 
> _[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYyG3Z3yuhhwTvzv8s:-NgYyG3Z3yuhhwTvzv8t:beul486) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L10)):_
> 
> > ```
> > package io.harness.notification;
> > 
> > public enum NotificationEntity {
> > ```
> 
> Why is this class placed in commons? Shouldn't this be a part platform-service/modules/notification-service/contracts
> 
> _[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYy9wiDwNPSQbSygDZ:-NgYy9wiDwNPSQbSygD_:b-st0g3m) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L28)):_
> 
> > ```
> > }
> > 
> > enum NotificationModule { PLATFORM, CCM, CHAOS, CD, CI }
> > ```
> 
> Should be separate class.
> 
> _[`980-commons/src/main/java/io/harness/notification/NotificationEvent.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYynbw6nvlKZqDOTf4:-NgYynbw6nvlKZqDOTf5:b-4xwos4) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEvent.java#L10)):_
> 
> > ```
> > package io.harness.notification;
> > 
> > public enum NotificationEvent {
> > ```
> 
> Same for this class.
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0-0d9LIZWL8K6oO-:-NgZ0-0d9LIZWL8K6oO0:b-p7jwvc) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L65)):_
> 
> > ```
> >   MicrosoftTeamsChannel microsoftTeamsChannel;
> >   PagerDutyChannel pagerDutyChannel;
> >   WebhookChannel webhookChannel;
> > ```
> 
> Isn't channel decided on type? Why do we need a separate field for every different type of channel?
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYz_na6EI9Bqq5-R70:-NgYz_na6EI9Bqq5-R71:b-z84mei) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L68)):_
> 
> > ```
> > 
> >   @CreatedBy EmbeddedUser createdBy;
> >   @LastModifiedBy EmbeddedUser lastUpdatedBy;
> > ```
> 
> Do we need to store these? This will also get capture as audit
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationChannelRepositoryCustom.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0mCaDjMitI5ggwzT:-NgZ0mCaDjMitI5ggwzU:bor75u) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationChannelRepositoryCustom.java#L22)):_
> 
> > ```
> >   Page<NotificationChannel> findAll(Criteria criteria, Pageable pageable);
> > 
> >   List<NotificationChannel> findAllWithCriteria(Criteria criteria);
> > ```
> 
> This method can be named as findAll.
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationRuleRepositoryCustom.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ1D7JDPsJEov3Lz0v:-NgZ1D7JDPsJEov3Lz0w:bl5qokn) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationRuleRepositoryCustom.java#L22)):_
> 
> > ```
> >   Page<NotificationRule> findAll(Criteria criteria, Pageable pageable);
> > 
> >   List<NotificationRule> findAllWithCriteria(Criteria criteria);
> > ```
> 
> Method name here as well
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ29Cb1VZqYSptjJ1C:-NgZ29Cb1VZqYSptjJ1D:b-8rg87a) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L32)):_
> 
> > ```
> > 
> >   @Override
> >   public NotificationChannel create(NotificationChannel notificationChannel) {
> > ```
> 
> No validation required apart from those which get covered by @Valid?
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ2ECYCTG_ezqbMBBA:-NgZ2ECYCTG_ezqbMBBB:b-avdoi9) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L33)):_
> 
> > ```
> >   @Override
> >   public NotificationChannel create(NotificationChannel notificationChannel) {
> >     NotificationChannel channel = notificationChannelRepository.save(notificationChannel);
> > ```
> 
> Duplicate Exception handling?
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ1eL6BbmL73nYNYHy:-NgZ1eL6BbmL73nYNYHz:b45df9h) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L38)):_
> 
> > ```
> > 
> >   @Override
> >   public NotificationChannel update(NotificationChannel notificationChannel) {
> > ```
> 
> Validate existence. Non modifiable fields like scope identifiers etc should not be updatable.
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationRuleManagementServiceImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ314P5xNJpdWW2Oc3:-NgZ314QBMjmf7CNeoA1:bmrlcel) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationRuleManagementServ [...]

2023-10-16 06:49 UTC, jennyjames21 commented
> > Reviewed 12 of 19 files at r1, 4 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/53949)_ status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team.
> 
> _[`980-commons/BUILD.bazel` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYxv3VE8X8WXtDiH3l:-NgYxv3W5c8YGsaFKkvZ:b-1l9bka) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/BUILD.bazel#L85)):_
> 
> > ```
> >         "//980-commons/src/main/java/io/harness/morphia:module",
> >         "//980-commons/src/main/java/io/harness/network:module",
> >         "//980-commons/src/main/java/io/harness/notification:module",
> > ```
> 
> Why should commons dependent on notification module?
> 
> _[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYyG3Z3yuhhwTvzv8s:-NgYyG3Z3yuhhwTvzv8t:beul486) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L10)):_
> 
> > ```
> > package io.harness.notification;
> > 
> > public enum NotificationEntity {
> > ```
> 
> Why is this class placed in commons? Shouldn't this be a part platform-service/modules/notification-service/contracts
> 
> _[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYy9wiDwNPSQbSygDZ:-NgYy9wiDwNPSQbSygD_:b-st0g3m) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L28)):_
> 
> > ```
> > }
> > 
> > enum NotificationModule { PLATFORM, CCM, CHAOS, CD, CI }
> > ```
> 
> Should be separate class.
> 
> _[`980-commons/src/main/java/io/harness/notification/NotificationEvent.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYynbw6nvlKZqDOTf4:-NgYynbw6nvlKZqDOTf5:b-4xwos4) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEvent.java#L10)):_
> 
> > ```
> > package io.harness.notification;
> > 
> > public enum NotificationEvent {
> > ```
> 
> Same for this class.
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0-0d9LIZWL8K6oO-:-NgZ0-0d9LIZWL8K6oO0:b-p7jwvc) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L65)):_
> 
> > ```
> >   MicrosoftTeamsChannel microsoftTeamsChannel;
> >   PagerDutyChannel pagerDutyChannel;
> >   WebhookChannel webhookChannel;
> > ```
> 
> Isn't channel decided on type? Why do we need a separate field for every different type of channel?
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYz_na6EI9Bqq5-R70:-NgYz_na6EI9Bqq5-R71:b-z84mei) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L68)):_
> 
> > ```
> > 
> >   @CreatedBy EmbeddedUser createdBy;
> >   @LastModifiedBy EmbeddedUser lastUpdatedBy;
> > ```
> 
> Do we need to store these? This will also get capture as audit
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationChannelRepositoryCustom.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0mCaDjMitI5ggwzT:-NgZ0mCaDjMitI5ggwzU:bor75u) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationChannelRepositoryCustom.java#L22)):_
> 
> > ```
> >   Page<NotificationChannel> findAll(Criteria criteria, Pageable pageable);
> > 
> >   List<NotificationChannel> findAllWithCriteria(Criteria criteria);
> > ```
> 
> This method can be named as findAll.
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationRuleRepositoryCustom.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ1D7JDPsJEov3Lz0v:-NgZ1D7JDPsJEov3Lz0w:bl5qokn) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationRuleRepositoryCustom.java#L22)):_
> 
> > ```
> >   Page<NotificationRule> findAll(Criteria criteria, Pageable pageable);
> > 
> >   List<NotificationRule> findAllWithCriteria(Criteria criteria);
> > ```
> 
> Method name here as well
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ29Cb1VZqYSptjJ1C:-NgZ29Cb1VZqYSptjJ1D:b-8rg87a) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L32)):_
> 
> > ```
> > 
> >   @Override
> >   public NotificationChannel create(NotificationChannel notificationChannel) {
> > ```
> 
> No validation required apart from those which get covered by @Valid?
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ2ECYCTG_ezqbMBBA:-NgZ2ECYCTG_ezqbMBBB:b-avdoi9) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L33)):_
> 
> > ```
> >   @Override
> >   public NotificationChannel create(NotificationChannel notificationChannel) {
> >     NotificationChannel channel = notificationChannelRepository.save(notificationChannel);
> > ```
> 
> Duplicate Exception handling?
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ1eL6BbmL73nYNYHy:-NgZ1eL6BbmL73nYNYHz:b45df9h) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L38)):_
> 
> > ```
> > 
> >   @Override
> >   public NotificationChannel update(NotificationChannel notificationChannel) {
> > ```
> 
> Validate existence. Non modifiable fields like scope identifiers etc should not be updatable.
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationRuleManagementServiceImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ314P5xNJpdWW2Oc3:-NgZ314QBMjmf7CNeoA1:bmrlcel) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationRuleManagementServ [...]

2023-10-16 06:50 UTC, jennyjames21 commented
*[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYy9wiDwNPSQbSygDZ:-NgrF15tCROAwMDP4NwR:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L28)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should be separate class.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-10-16 06:54 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYz_na6EI9Bqq5-R70:-NgrFBbv1BSclFrCZwmo:baelwbz) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L68)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Do we need to store these? This will also get capture as audit
</blockquote></details>

Notification Listing page UI needs to show the createdBy field. We may need this for audit as well


<!-- Sent from Reviewable.io -->

2023-10-16 06:54 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationChannelRepositoryCustom.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0mCaDjMitI5ggwzT:-NgrG-NZC1ryxrqjnVts:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationChannelRepositoryCustom.java#L22)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This method can be named as findAll.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-10-16 06:55 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationRuleRepositoryCustom.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ1D7JDPsJEov3Lz0v:-NgrG1gX0sEQpnwzR2SB:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/repositories/NotificationRuleRepositoryCustom.java#L22)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Method name here as well
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-10-16 06:57 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ29Cb1VZqYSptjJ1C:-NgrG4_n484o7Tg-90cM:b-vyo86o) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L32)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

No validation required apart from those which get covered by @Valid?
</blockquote></details>

we need to add more validation and I will add in the upcoming PRs,  added a @todo to track. 


<!-- Sent from Reviewable.io -->

2023-10-16 06:58 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ2ECYCTG_ezqbMBBA:-NgrGjO3BLuO1MoYftgP:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L33)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Duplicate Exception handling?
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-10-16 06:58 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ1eL6BbmL73nYNYHy:-NgrGlwI48HivavulOwE:b6oi1k1) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationChannelManagementServiceImpl.java#L38)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Validate existence. Non modifiable fields like scope identifiers etc should not be updatable.
</blockquote></details>

 I will add in the upcoming PRs, adding @todo to track. 


<!-- Sent from Reviewable.io -->

2023-10-16 06:59 UTC, jennyjames21 commented
*[`980-commons/BUILD.bazel` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYxv3VE8X8WXtDiH3l:-NgrGyR39esXaUES3Oaw:b-ohvrkd) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/BUILD.bazel#L85)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why should commons dependent on notification module?
</blockquote></details>

this is notification module inside 980-common


<!-- Sent from Reviewable.io -->

2023-10-16 07:00 UTC, jennyjames21 commented
*[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYyG3Z3yuhhwTvzv8s:-NgrH4MG-e1cixyVfl7q:bq70itp) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L10)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why is this class placed in commons? Shouldn't this be a part platform-service/modules/notification-service/contracts
</blockquote></details>

Common class need for both notification service and notification client


<!-- Sent from Reviewable.io -->

2023-10-16 07:01 UTC, jennyjames21 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53949)* status: 23 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0-0d9LIZWL8K6oO-:-NgrHL31BSbqUGZDMlxl:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L65)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Isn't channel decided on type? Why do we need a separate field for every different type of channel?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2023-10-16 10:23 UTC, nishantsaini20 requested changes
> Reviewed 8 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53949)* status: 23 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYyG3Z3yuhhwTvzv8s:-Ngrzllw2SrnSZ31s7v3:b217dog) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L10)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Common class need for both notification service and notification client
</blockquote></details>

Didn't get it. Anything inside platform-service/modules/notification-service/contracts is also sharable.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0-0d9LIZWL8K6oO-:-Ngs-DKD5x-TmQMOaKuU:bsagpnk) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L65)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Then, why do we need a separate field for every different type of channel? Can't we have a single field named channel?


<!-- Sent from Reviewable.io -->

2023-10-16 16:02 UTC, jennyjames21 commented
*[`980-commons/src/main/java/io/harness/notification/NotificationEntity.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgYyG3Z3yuhhwTvzv8s:-NgtDCxm4JJCbGKxN1Iq:b-v9261y) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/980-commons/src/main/java/io/harness/notification/NotificationEntity.java#L10)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Didn't get it. Anything inside platform-service/modules/notification-service/contracts is also sharable.
</blockquote></details>

As discussed moved under platform-service


<!-- Sent from Reviewable.io -->

2023-10-16 16:02 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/53949#-NgZ0-0d9LIZWL8K6oO-:-NgtDKcS2jEWWwa5JP_C:b-vdfhbf) ([raw file](https://github.com/harness/harness-core/blob/3c3fb3cff06c1e791992befe89081dbba6206390/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationChannel.java#L65)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Then, why do we need a separate field for every different type of channel? Can't we have a single field named channel?
</blockquote></details>

updated with single field channel


<!-- Sent from Reviewable.io -->

2023-10-16 16:04 UTC, jennyjames21 commented
/rebase

2023-10-16 19:58 UTC, jennyjames21 commented
trigger uts

2023-10-17 17:00 UTC, nishantsaini20 requested changes
> Reviewed 1 of 19 files at r1, 12 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53949)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-Ngvni24-J-9xJbFbFhc:-Ngvni24-J-9xJbFbFhd:b-kj3eeq) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java#L55)):*
> ```Java
>   @Id @dev.morphia.annotations.Id String uuid;
> 
>   String notificationRuleIdentifier;
> ```

We can name it just identifier.
___
*[`platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationEntity.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-NgvjOBP2nsb2AL9Hpq7:-NgvjOBP2nsb2AL9Hpq8:b-2gh0r7) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationEntity.java#L8)):*
> ```Java
>  */
> 
> package software.wings.beans;
> ```

Package should be io.harness.notification.entities
___
*[`platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationEvent.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-NgvjmfA8dIkQAednuo9:-NgvjmfA8dIkQAednuoA:b-2gh0r7) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationEvent.java#L8)):*
> ```Java
>  */
> 
> package software.wings.beans;
> ```

Package should be io.harness.notification.entities
___
*[`platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationModule.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-NgvjntL8CH5B7tyNh2J:-NgvjntL8CH5B7tyNh2K:b-2gh0r7) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationModule.java#L8)):*
> ```Java
>  */
> 
> package software.wings.beans;
> ```

Package should be io.harness.notification.entities


<!-- Sent from Reviewable.io -->

2023-10-17 17:02 UTC, nishantsaini20 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53949)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationModule.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-NgvjntL8CH5B7tyNh2J:-Ngy_cP84xXcn2e0B8KW:b-sc7gue) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationModule.java#L8)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Package should be io.harness.notification.entities
</blockquote></details>

@gn-harness can approve this PR after this is done.


<!-- Sent from Reviewable.io -->

2023-10-17 21:03 UTC, jennyjames21 commented
trigger uts

2023-10-17 21:04 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-Ngvni24-J-9xJbFbFhc:-NgzS0ik6a2QN2EOPVCk:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/NotificationRule.java#L55)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We can name it just identifier.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-10-17 21:04 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationModule.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-NgvjntL8CH5B7tyNh2J:-NgzS2P35FZXgfZLqmQ-:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationModule.java#L8)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

@gn-harness can approve this PR after this is done.
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-10-17 21:05 UTC, jennyjames21 commented
*[`platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationEvent.java` line 8 at r6](https://reviewable.io/reviews/harness/harness-core/53949#-NgvjmfA8dIkQAednuo9:-NgzS4A17As01Y8TWjA-:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/54b38cb190c63d5112d8a06cf81f56e1fbcf614e/platform-service/modules/notification-service/contracts/src/main/java/software/wings/beans/NotificationEvent.java#L8)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Package should be io.harness.notification.entities
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-10-18 03:49 UTC, nishantsaini20 approved these changes
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53949)* status: 23 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-10-18 18:57 UTC, jennyjames21 commented
trigger messagecheck

2023-10-18 19:44 UTC, merged