fix: [CDS-80615]: Entity References for ServiceOverridesV2
harness/harness-core pull request #53942
Opened 2023-10-09 19:52 UTC by sarthakkasat

## Describe your changes
Currently if a secret is used in Service OverridesV2 it does not show in secret references, with this change override entities will be shown in references.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-12 08:58 UTC, mohitg0795 commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 208 at r4](https://reviewable.io/reviews/harness/harness-core/53942#-NgY5qaO0zFaS0U9NXCo:-NgY5qaO0zFaS0U9NXCp:buua5g3) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L208)):*
> ```Java
>       return serviceOverridesV2SetupUsageHelper.getAllReferredEntities(overridesEntity);
>     } catch (RuntimeException ex) {
>       throw new InvalidRequestException(
> ```

this shouldn't be invalidRequestException right? Should be something else.


<!-- Sent from Reviewable.io -->

2023-10-12 08:58 UTC, mohitg0795 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 207 at r4](https://reviewable.io/reviews/harness/harness-core/53942#-NgY5wEAC7a6zUDM4Edc:-NgY5wEB-0iDZoQzbs_x:badiq2m) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L207)):*
> ```Java
>     try {
>       return serviceOverridesV2SetupUsageHelper.getAllReferredEntities(overridesEntity);
>     } catch (RuntimeException ex) {
> ```

shouldn't we log the exception here?


<!-- Sent from Reviewable.io -->

2023-10-12 08:59 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java` line 92 at r4](https://reviewable.io/reviews/harness/harness-core/53942#-NgY6Ci681ls2Qr-BE-K:-NgY6Ci681ls2Qr-BE-L:bh27ny1) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java#L92)):*
> ```Java
>   }
> 
>   public Set<EntityDetailProtoDTO> getAllReferredEntities(NGServiceOverridesEntity entity) {
> ```

lets try to group all public methods on the top for easy reference followed by all private and protected methods


<!-- Sent from Reviewable.io -->

2023-10-16 04:20 UTC, tchaurasiya requested changes

2023-10-16 04:20 UTC, tchaurasiya commented on 970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto/EntityReferredByOverridesSetupUsageDetail.java
> +  String identifier;
we should add scope of override, to make this unique

2023-10-16 04:20 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java
> +    Set<EntityDetailProtoDTO> referredEntities = getAndValidateReferredEntities(requestedEntity);
this should be after upsert operations, Else if this fails somehow user will not be able to create entity itself

2023-10-16 04:20 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java
> +   * Delete all setup usages where the 'referred by' is the current service entity
service entity??

2023-10-16 04:20 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java
> +  public Set<EntityDetailProtoDTO> getAllReferredEntities(NGServiceOverridesEntity entity) {
nit: can be make static final

2023-10-16 04:20 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java
> +    setupUsageHelper.deleteServiceSetupUsages(getOwnerEntity(entity));
why are we using serviceSetupUsageDelete Method, if this method is agnostic of entity type we should rename it.

2023-10-16 07:17 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: Some of the checks are too old. 14 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 207 at r4](https://reviewable.io/reviews/harness/harness-core/53942#-NgY5wEAC7a6zUDM4Edc:-NgrEtdWBOUAqCwjs1-s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L207)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't we log the exception here?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 208 at r4](https://reviewable.io/reviews/harness/harness-core/53942#-NgY5qaO0zFaS0U9NXCo:-NgrEtyG6-N5hRMnDmTr:b-t2tb46) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L208)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this shouldn't be invalidRequestException right? Should be something else.
</blockquote></details>

Could you please suggest what exception can we throw here, other methods to get referred entities are throwing the same error.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 254 at r4](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360083575:-NgrF9o6CdqdrIluqccv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L254)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

this should be after upsert operations, Else if this fails somehow user will not be able to create entity itself
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360086134:-NgrFAXpDIoEggchBQ5N:bbb5b9g) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java#L59)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

service entity??
</blockquote></details>

Update the text to override entity
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java` line 62 at r4](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360087385:-NgrFFtsDADuW7tSS_tQ:bw0jje8) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java#L62)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

why are we using serviceSetupUsageDelete Method, if this method is agnostic of entity type we should rename it.
</blockquote></details>

Update the name to deleteEntitySetupUsages
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java` line 92 at r4](https://reviewable.io/reviews/harness/harness-core/53942#-NgY6Ci681ls2Qr-BE-K:-NgrFLX8D6lPsBasspAD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/setupusage/ServiceOverridesV2SetupUsageHelper.java#L92)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets try to group all public methods on the top for easy reference followed by all private and protected methods
</blockquote></details>

Done
___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto/EntityReferredByOverridesSetupUsageDetail.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360081354:-NgrFP0nDi327zA4iI1m:b7qtq0g) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto/EntityReferredByOverridesSetupUsageDetail.java#L23)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

we should add scope of override, to make this unique
</blockquote></details>

Added orgId, projectID and accountID to make it unique.


<!-- Sent from Reviewable.io -->

2023-10-16 07:28 UTC, mohitg0795 commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 208 at r4](https://reviewable.io/reviews/harness/harness-core/53942#-NgY5qaO0zFaS0U9NXCo:-NgrNVnj8mPd_fBUyHG1:b-n5k4hg) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L208)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

Could you please suggest what exception can we throw here, other methods to get referred entities are throwing the same error.
</blockquote></details>

InternalServerErrorException


<!-- Sent from Reviewable.io -->

2023-10-16 13:41 UTC, tchaurasiya requested changes

2023-10-16 13:41 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/NGServiceOverrideConfigV2.java
> +@SimpleVisitorHelper(helperClass = NGServiceConfigVisitorHelper.class)
Visitor should return this class object, We need to use another visitor.

2023-10-16 13:41 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/NGServiceOverrideConfigV2.java
> +@SimpleVisitorHelper(helperClass = NGServiceConfigVisitorHelper.class)
I am also not sure, How dummy visting node is used, Lets confirm with @Archit/ @Yogesh if this vistor is even needed.

2023-10-16 13:41 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesSpec.java
> +@SimpleVisitorHelper(helperClass = ServiceDefinitionVisitorHelper.class)
Visitor should return this class object, We need to use another visitor.

2023-10-16 13:41 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesSpec.java
> +  public VisitableChildren getChildrenToWalk() {
we should add applicationSettings & applicationSettings too , they to have connectors

2023-10-16 21:33 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 17 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/NGServiceOverrideConfigV2.java` line 38 at r6](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360672296:-NguP3dv3T1ypPJ6B2Br:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f30c50d7b451e4832d02bd84951681faef08640/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/NGServiceOverrideConfigV2.java#L38)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Visitor should return this class object, We need to use another visitor.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/NGServiceOverrideConfigV2.java` line 38 at r6](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360673591:-NguP46E3nMMCc1PR7Zj:b-47ix6i) ([raw file](https://github.com/harness/harness-core/blob/3f30c50d7b451e4832d02bd84951681faef08640/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/NGServiceOverrideConfigV2.java#L38)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

I am also not sure, How dummy visting node is used, Lets confirm with @Archit/ @Yogesh if this vistor is even needed.
</blockquote></details>

Sure will discuss this
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesSpec.java` line 45 at r6](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360673882:-NguP7hn-JFO_ybUquYX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f30c50d7b451e4832d02bd84951681faef08640/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesSpec.java#L45)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Visitor should return this class object, We need to use another visitor.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesSpec.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360676189:-NguP86I-yn_feu9jLcc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f30c50d7b451e4832d02bd84951681faef08640/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesSpec.java#L55)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

we should add applicationSettings & applicationSettings too , they to have connectors
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 10:14 UTC, tchaurasiya approved these changes

2023-10-20 05:30 UTC, yogesh-chauhan requested changes
> Reviewed 1 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 17 file(s) to review. 2 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/entitysetupusage/entity_detail_with_setup_usage_detail.proto` line 54 at r8](https://reviewable.io/reviews/harness/harness-core/53942#-NhAYYKW0irSSZPHOVMH:-NhAYYKW0irSSZPHOVMI:b-8sl6vj) ([raw file](https://github.com/harness/harness-core/blob/23e9020889d9a4e81d13a4075e78e63b39305b3f/953-events-api/src/main/proto/io/harness/eventsframework/schemas/entitysetupusage/entity_detail_with_setup_usage_detail.proto#L54)):*
> ```proto
>     string accountId = 9;
>     string orgId = 10;
>     string projectId = 11;
> ```

these numbers should be 1-5
___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto/EntityReferredByOverridesSetupUsageDetail.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360081354:-NhAY-qICqSse5lj8kvm:bokc7uk) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto/EntityReferredByOverridesSetupUsageDetail.java#L23)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

Added orgId, projectID and accountID to make it unique.
</blockquote></details>

maybe put @NotNull on some fields


<!-- Sent from Reviewable.io -->

2023-10-20 05:35 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 213 at r8](https://reviewable.io/reviews/harness/harness-core/53942#-NhA_APMATBF20gtI7CY:-NhA_APMATBF20gtI7CZ:bxvai5l) ([raw file](https://github.com/harness/harness-core/blob/23e9020889d9a4e81d13a4075e78e63b39305b3f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L213)):*
> ```Java
>           ex);
>       throw new InternalServerErrorException(
>           String.format("Exception while retrieving referred entities for infrastructure: [%s]. ",
> ```

typo , infrastructure -> overrides ?


<!-- Sent from Reviewable.io -->

2023-10-20 05:36 UTC, yogesh-chauhan reviewed
> Reviewed 2 of 8 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 17 file(s) to review. 2 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-20 06:41 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 17 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 213 at r8](https://reviewable.io/reviews/harness/harness-core/53942#-NhA_APMATBF20gtI7CY:-NhAoJFi5O9QRGdS-8mv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/23e9020889d9a4e81d13a4075e78e63b39305b3f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L213)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

typo , infrastructure -> overrides ?
</blockquote></details>

Done.
___
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/entitysetupusage/entity_detail_with_setup_usage_detail.proto` line 54 at r8](https://reviewable.io/reviews/harness/harness-core/53942#-NhAYYKW0irSSZPHOVMH:-NhAoKB7EN4XjYbriTo8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/23e9020889d9a4e81d13a4075e78e63b39305b3f/953-events-api/src/main/proto/io/harness/eventsframework/schemas/entitysetupusage/entity_detail_with_setup_usage_detail.proto#L54)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

these numbers should be 1-5
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto/EntityReferredByOverridesSetupUsageDetail.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/53942#gh-1360081354:-NhAoL4E7AX4LKkchTqX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/707c8db2024171b3533b739b59b5db44bc428008/970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto/EntityReferredByOverridesSetupUsageDetail.java#L23)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe put @NotNull on some fields
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-20 07:00 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 13 files at r1, 2 of 8 files at r5, 7 of 8 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 17 file(s) to review. 1 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-20 07:11 UTC, sarthakkasat commented
trigger uts

2023-10-20 07:30 UTC, tchaurasiya submitted a review, later dismissed

2023-10-20 07:32 UTC, sarthakkasat commented
trigger review

2023-10-20 08:32 UTC, sarthakkasat commented
trigger uts

2023-10-20 10:09 UTC, sarthakkasat commented
trigger ut3, ut5

2023-10-20 11:51 UTC, sarthakkasat commented
trigger ut3

2023-10-22 05:20 UTC, sarthakkasat commented
/rebase

2023-10-22 05:25 UTC, sarthakkasat commented
trigger uts

2023-10-22 06:42 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53942)* status: 18 file(s) to review. 1 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-22 06:44 UTC, sarthakkasat commented
trigger ut5, ut6, ut7

2023-10-22 08:15 UTC, sarthakkasat commented
trigger ut6

2023-10-23 05:18 UTC, sourabh-awashti approved these changes

2023-10-23 05:19 UTC, sarthakkasat commented
trigger review

2023-10-23 05:54 UTC, merged