fix: [CDS-80440]: fix plan creation for v1 yaml
harness/harness-core pull request #53953
Opened 2023-10-10 03:01 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-10 03:24 UTC, shalini-agr commented
trigger gitleaks

2023-10-10 03:24 UTC, shalini-agr commented
trigger uts

2023-10-10 05:03 UTC, shalini-agr commented
trigger utds

2023-10-10 05:03 UTC, shalini-agr commented
trigger uts

2023-10-10 05:20 UTC, shalini-agr commented
trigger uts

2023-10-10 05:30 UTC, brijeshdhakar commented
*[`315-sto-manager/app/src/test/resources/schema/SecurityStage/all.json` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/53953#-NgN389j8X0NiHnUeEj5:-NgN389j8X0NiHnUeEj6:b-sz979s) ([raw file](https://github.com/harness/harness-core/blob/bc3107e8cc13276d12ff54841458484aa1031946/315-sto-manager/app/src/test/resources/schema/SecurityStage/all.json#L42)):*
> ```JSON
>       ]
>     },
>     "id": {
> ```

@shalini-agr can you make the id @jsonIgnore? so that it does not come in the schema for v0 stage.


<!-- Sent from Reviewable.io -->

2023-10-10 05:31 UTC, brijeshdhakar reviewed
> Reviewed 1 of 2 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 6 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-10-10 05:46 UTC, archit-harness reviewed
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 5 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-10-18 12:24 UTC, archit-harness requested changes
> Reviewed 12 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessor.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/53953#-Nh1j6Cs40YsUmNm7FNp:-Nh1j6Cs40YsUmNm7FNq:b-4zlr4p) ([raw file](https://github.com/harness/harness-core/blob/5360df750aceceae9a5641602c283f364303e0c9/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessor.java#L19)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public interface PipelinePreprocessor {
>   PipelinePreprocessorResponseDTO preProcess(String pipelineYaml);
> ```

why we are calling this dto pipeline? can we say YamlPreprocessorResponseDTO? is this working only on pipeline and not only for lower layer?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessorFactory.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/53953#-Nh1jDLfCAyb2zetQ0_0:-Nh1jDLfCAyb2zetQ0_1:b9qxxpz) ([raw file](https://github.com/harness/harness-core/blob/5360df750aceceae9a5641602c283f364303e0c9/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessorFactory.java#L19)):*
> ```Java
>     components = {HarnessModuleComponent.CDS_PIPELINE, HarnessModuleComponent.CDS_TEMPLATE_LIBRARY})
> @OwnedBy(HarnessTeam.PIPELINE)
> public class PipelinePreprocessorFactory {
> ```

we should also not call this pipeline?


<!-- Sent from Reviewable.io -->

2023-10-18 13:11 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 22 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessor.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/53953#-Nh1j6Cs40YsUmNm7FNp:-Nh1tqqZ98Bp97I5jDSr:b-kh5pls) ([raw file](https://github.com/harness/harness-core/blob/5360df750aceceae9a5641602c283f364303e0c9/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessor.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are calling this dto pipeline? can we say YamlPreprocessorResponseDTO? is this working only on pipeline and not only for lower layer?
</blockquote></details>

Yes, it can work on stage/step yamls as well. doesn't necessarily have to be a pipeline yaml 
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessorFactory.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/53953#-Nh1jDLfCAyb2zetQ0_0:-Nh1tpeKBl2xMTfaCStL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5360df750aceceae9a5641602c283f364303e0c9/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/PipelinePreprocessorFactory.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should also not call this pipeline?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 19:04 UTC, brijeshdhakar requested changes
> Reviewed 15 of 22 files at r4, 4 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 15 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 331 at r5](https://reviewable.io/reviews/harness/harness-core/53953#-Nh396yn4dcflRdJFK_L:-Nh396yoDM3BUqNJFXHU:b-37mm9l) ([raw file](https://github.com/harness/harness-core/blob/6615b441294d2f7206af33d03be3cd9006ce779f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L331)):*
> ```Java
>         templateMergeResponseDTO =
>             getPipelineYamlAndValidateStaticallyReferredEntities(YamlUtils.readAsJsonNode(pipelineYaml), pipelineEntity,
>                 System.currentTimeMillis(), idsSuffixMap, idsValuesSet);
> ```

I think `idsSuffixMap` and `idsValuesSet` does not have to be part of TemplateApplyRequestDTO contract.  we can leave this responsibility on TemplateService to calculate the idsSuffixMap and idsValuesSet.
We should just give yaml and template-service will decide if it needs these map/set. If it need then it will calculate using the util. 


<!-- Sent from Reviewable.io -->

2023-10-19 07:16 UTC, archit-harness requested changes
> Reviewed 6 of 10 files at r5, 2 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 14 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 316 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5j7bDBOVwsojHLb9o:-Nh5j7bDBOVwsojHLb9p:bdno8h7) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L316)):*
> ```Java
>         pipelineYaml = InputSetMergeHelperV1.mergeInputSetIntoPipelineYaml(
>             mergedRuntimeInputJsonNode, YamlUtils.readAsJsonNode(pipelineEntity.getYaml()));
>         YamlPreprocessor preprocessor = yamlPreprocessorFactory.getProcessorInstance(HarnessYamlVersion.V1);
> ```

lets add comments we are processing here and not only in template resolve call if templates are not present usecase
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 284 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5jJV30H_CoSXz3pdV:-Nh5jJV30H_CoSXz3pdW:b-aed3kf) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L284)):*
> ```Java
>    * replaceTemplateOccurrenceWithTemplateSpecYaml() to get the actual template.spec in template yaml.
>    */
>   public MergeTemplateInputsInObject mergeTemplateInputsInObjectWithVersion(String accountId, String orgId,
> ```

as its public method who all are calling it? we should avoid adding fields to public method if not required by anyone
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 353 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5jZpt87UJZaeSexRV:-Nh5jZpt87UJZaeSexRW:b-f1h4qd) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L353)):*
> ```Java
>         try {
>           resMap = YamlUtils.read(
>               yamlPreprocessor.preProcess(YamlUtils.writeYamlString(resMap)).getPreprocessedYaml(), Map.class);
> ```

i think our preProcess method should only work on json and not yaml, plus it should return json only
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessor.java` line 18 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5iEzL0Qj7EZbtb40V:-Nh5iEzL0Qj7EZbtb40W:b-ua5q7u) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessor.java#L18)):*
> ```Java
>     components = {HarnessModuleComponent.CDS_PIPELINE, HarnessModuleComponent.CDS_TEMPLATE_LIBRARY})
> @OwnedBy(HarnessTeam.PIPELINE)
> public interface YamlPreprocessor {
> ```

Can we add comments to this class what it do?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessorResponseDTO.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5ikkb-fFSI-N4BhOt:-Nh5ikkb-fFSI-N4BhOu:b-uv47s9) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessorResponseDTO.java#L23)):*
> ```Java
> public class YamlPreprocessorResponseDTO {
>   Set<String> idsValuesSet;
>   Map<String, Integer> idsSuffixMap;
> ```

add comments to idValuesSet and idsSuffixMap with examples
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java` line 35 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5ipdd0k4cT7wwb6Zy:-Nh5ipdd0k4cT7wwb6Zz:bat48c9) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java#L35)):*
> ```Java
>     components = {HarnessModuleComponent.CDS_PIPELINE, HarnessModuleComponent.CDS_TEMPLATE_LIBRARY})
> @OwnedBy(HarnessTeam.PIPELINE)
> public class YamlV1Preprocessor implements YamlPreprocessor {
> ```

comments what this processor do?
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java` line 42 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5iylE2l0_jSxHdqXJ:-Nh5iylE2l0_jSxHdqXK:b-p5hocd) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java#L42)):*
> ```Java
>     // Set to keep track of what all ids are present in the YAML.
>     Set<String> idsValuesSet = new HashSet<>();
>     collectIdsFromYamlRecursively(jsonNode, idsValuesSet);
> ```

rename to collectExistingIdsFromYamlRecursively


<!-- Sent from Reviewable.io -->

2023-10-19 07:32 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 14 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 331 at r5](https://reviewable.io/reviews/harness/harness-core/53953#-Nh396yn4dcflRdJFK_L:-Nh5n2aQ5Mo0m9V5V8R2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6615b441294d2f7206af33d03be3cd9006ce779f/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L331)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think `idsSuffixMap` and `idsValuesSet` does not have to be part of TemplateApplyRequestDTO contract.  we can leave this responsibility on TemplateService to calculate the idsSuffixMap and idsValuesSet.
We should just give yaml and template-service will decide if it needs these map/set. If it need then it will calculate using the util.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 316 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5j7bDBOVwsojHLb9o:-Nh5obGJAzLD8I2Ofb5y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L316)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets add comments we are processing here and not only in template resolve call if templates are not present usecase
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 284 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5jJV30H_CoSXz3pdV:-Nh5ovuy2A12b-zaqeT-:by1s7vr) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L284)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as its public method who all are calling it? we should avoid adding fields to public method if not required by anyone
</blockquote></details>

this method is called during template resolution and inputs validator and TemplateInputsRefreshHelper, there's already an overloaded method of this
___
*[`315-sto-manager/app/src/test/resources/schema/SecurityStage/all.json` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/53953#-NgN389j8X0NiHnUeEj5:-Nh5n8oG5ecBLwGwq-0h:b-32ypbi) ([raw file](https://github.com/harness/harness-core/blob/bc3107e8cc13276d12ff54841458484aa1031946/315-sto-manager/app/src/test/resources/schema/SecurityStage/all.json#L42)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@shalini-agr can you make the id @jsonIgnore? so that it does not come in the schema for v0 stage.
</blockquote></details>

invalid
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessor.java` line 18 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5iEzL0Qj7EZbtb40V:-Nh5nPz03PlJtAyi_ssR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessor.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we add comments to this class what it do?
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessorResponseDTO.java` line 23 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5ikkb-fFSI-N4BhOt:-Nh5nljxDNz-oat9EZVJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlPreprocessorResponseDTO.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments to idValuesSet and idsSuffixMap with examples
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java` line 35 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5ipdd0k4cT7wwb6Zy:-Nh5odwQ2GdJng01Q9mA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

comments what this processor do?
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java` line 42 at r7](https://reviewable.io/reviews/harness/harness-core/53953#-Nh5iylE2l0_jSxHdqXJ:-Nh5oMC97xwyz7sBQg7l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/311a0dc6b0169c1524ca4be5dade121ea04d9234/953-yaml-commons/src/main/java/io/harness/pms/yaml/preprocess/YamlV1Preprocessor.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to collectExistingIdsFromYamlRecursively
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-20 10:22 UTC, archit-harness requested changes
> Reviewed 4 of 7 files at r6, 8 of 9 files at r10, 2 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 16 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 104 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhB_nwxDPJY24ExZn6a:-NhB_nwxDPJY24ExZn6b:b-9red94) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L104)):*
> ```Java
>   private GitAwareEntityHelper gitAwareEntityHelper;
>   private TemplateGitXService templateGitXService;
>   @Inject TemplatePreprocessorHelper templatePreprocessorHelper;
> ```

we dont need inject as we have all args constructor as top, make it private
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 646 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBaHAkEBm5oJKgsD6l:-NhBaHAkEBm5oJKgsD6m:b-yir5k3) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L646)):*
> ```Java
>         value = entry.getValue();
>         templateEntity = entry.getKey();
>         templatePreprocessorHelper.collectIdsFromTemplateYaml(templateEntity, idsValuesSet);
> ```

why we are collecting here and not preprocessing the template-yaml?
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 33 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBa_bW3D5NghZRzou2:-NhBa_bW3D5NghZRzou3:btxmgfl) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L33)):*
> ```Java
>   @Inject private YamlPreprocessorFactory yamlPreprocessorFactory;
> 
>   public Map<String, Object> preprocessResMap(TemplateEntity templateEntity, Map<String, Object> resMap,
> ```

preProcessResMap rename
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 37 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBaPff9b3-sZNOrOCL:-NhBaPff9b3-sZNOrOCM:b-e7yeb3) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L37)):*
> ```Java
>     YamlPreprocessor yamlPreprocessor = yamlPreprocessorFactory.getProcessorInstance(HarnessYamlVersion.V1);
>     if (templateEntity.getTemplateEntityType() == TemplateEntityType.PIPELINE_TEMPLATE) {
>       if (HarnessYamlVersion.isV1(templateEntity.getHarnessVersion())) {
> ```

can we add comments, verbally why do we need specific handling, like v1 having v0 template needs identifier and not id etc
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 55 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBaY4025JHE-apGej6:-NhBaY4025JHE-apGej7:bddlnbr) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L55)):*
> ```Java
>   }
> 
>   private Map<String, Object> preprocessResMap(Map<String, Object> resMap, String version, Set<String> idsValuesSet,
> ```

we should rename it to preProcessResMapInternal
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 67 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBad6YDPdjE19sJpi9:-NhBad6YDPdjE19sJpiA:b-2a52bv) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L67)):*
> ```Java
>         break;
>       default:
>         log.info("Version {} not supported", version);
> ```

log.warn
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 72 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBahg2BNFbNMrP3uW5:-NhBahg2BNFbNMrP3uW6:b-btxz8o) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L72)):*
> ```Java
>   }
> 
>   private void injectIdInYaml(String idField, Map<String, Object> resMap, Set<String> idsValuesSet,
> ```

add comments here idField value are id or identifier based on version which they are, maybe we can take version as input and based on version add id/identifier ourselves and not by caller


<!-- Sent from Reviewable.io -->

2023-10-20 10:32 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 16 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 104 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhB_nwxDPJY24ExZn6a:-NhBbKwb-0rSUDH9C6lH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L104)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we dont need inject as we have all args constructor as top, make it private
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 55 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBaY4025JHE-apGej6:-NhBbrLj-h-tkcBcVGRV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should rename it to preProcessResMapInternal
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 67 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBad6YDPdjE19sJpi9:-NhBc5WI9ISNhd20vCTw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

log.warn
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 72 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBahg2BNFbNMrP3uW5:-NhBcmdZ6GSQ7S39Ln2e:b51kgee) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments here idField value are id or identifier based on version which they are, maybe we can take version as input and based on version add id/identifier ourselves and not by caller
</blockquote></details>

added comment 


<!-- Sent from Reviewable.io -->

2023-10-20 10:36 UTC, archit-harness reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 16 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-10-22 07:53 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 16 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 33 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBa_bW3D5NghZRzou2:-NhBePWf8XPdAO5tsqQR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

preProcessResMap rename
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 37 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBaPff9b3-sZNOrOCL:-NhLMrOFD2xRxDaQDVI0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add comments, verbally why do we need specific handling, like v1 having v0 template needs identifier and not id etc
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java` line 72 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBahg2BNFbNMrP3uW5:-NhLMwTB7LHGNPD2L4cE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplatePreprocessorHelper.java#L72)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

added comment
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-23 05:43 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 1 of 22 files at r4, 4 of 7 files at r6, 1 of 9 files at r10, 11 of 11 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 11 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 646 at r11](https://reviewable.io/reviews/harness/harness-core/53953#-NhBaHAkEBm5oJKgsD6l:-NhQ1-0P8rA6oP8g7gxS:b-7qddd9) ([raw file](https://github.com/harness/harness-core/blob/d91e1c59d00ddd55fa05dcd4c2fd9f86478865f6/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L646)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are collecting here and not preprocessing the template-yaml?
</blockquote></details>

Once we need to collect at the beginning to add the ids at top level in step/stage that refers the template. And invoke the preprocessing for the template yaml that will add the ids inside it.


<!-- Sent from Reviewable.io -->

2023-10-23 06:01 UTC, shalini-agr commented
trigger uts

2023-10-23 06:24 UTC, archit-harness approved these changes
> Reviewed 11 of 11 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-10-23 06:43 UTC, shalini-agr commented
trigger uts

2023-10-23 06:57 UTC, shalini-agr commented
trigger ut8, ut9

2023-10-23 07:43 UTC, brijeshdhakar approved these changes
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-10-23 08:20 UTC, archit-harness approved these changes
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53953)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-10-23 08:27 UTC, merged