[fix]:[CDS-78451]: Error message improvement
harness/harness-core pull request #53979
Opened 2023-10-10 12:22 UTC by vinit1968

## Describe your changes
Error message needs improvement when namespace is <+input> and no value is provided and execution starts.
Added new method validateExpression which take map as a parameter and this method return error message with the unressolved expression name.
<img width="1792" alt="Screenshot 2023-10-10 at 3 43 01 PM" src="https://github.com/harness/harness-core/assets/142882920/7b50198c-e550-42c4-b80f-9341c50e42a6">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-10 12:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=53979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=53979) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=53979) it.</sub>

2023-10-10 12:22 UTC, vinit1968 commented
trigger uts

2023-10-10 12:26 UTC, rafaelmart1ns commented on 125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java
> +    doThrow(InvalidRequestException.class).when(infrastructureStepHelper).validateExpression(anyMap());
I think that you should validate the expression using the new values.

2023-10-10 12:26 UTC, rafaelmart1ns approved these changes

2023-10-10 12:59 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java
> +  public void validateExpression(Map<String, ParameterField<String>> fieldNameValueMap) {
Can we keep this as Map<String, ParameterField<T>> as the previous validateExpression method ? Otherwise there may be class cast exceptions.

2023-10-10 13:00 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java
> +        infrastructureStepHelper.validateExpression(fieldNameValueMap);
We need to make similar changes in ```io.harness.cdng.infra.steps.AbstractInfrastructureTaskExecutableStep#validateInfrastructure(io.harness.cdng.infra.yaml.Infrastructure)```

2023-10-10 13:37 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java
> +        throw new InvalidRequestException(
handle npe if parameter is null

2023-10-11 04:23 UTC, vinit1968 commented
trigger uts

2023-10-11 05:10 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 939 at r1](https://reviewable.io/reviews/harness/harness-core/53979#-NgS8D478rRgVysu2NJ5:-NgS8D488nW_Xbhf3Aog:bquj7pn) ([raw file](https://github.com/harness/harness-core/blob/fa5f26ca212f608629da1649973b2f771090e95b/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L939)):*
> ```Java
>         AwsSamInfrastructure awsSamInfrastructure = (AwsSamInfrastructure) infrastructure;
>         fieldNameValueMap.put("connectorRef", awsSamInfrastructure.getConnectorRef());
>         fieldNameValueMap.put("region", awsSamInfrastructure.getRegion());
> ```

are all these fields in different infrastructures mandatory ?
Also, please write unit tests for the same 


<!-- Sent from Reviewable.io -->

2023-10-11 09:33 UTC, vinit1968 commented
trigger uts

2023-10-11 10:41 UTC, vinit1968 commented
trigger uts

2023-10-11 10:47 UTC, vinit1968 commented
trigger uts

2023-10-18 05:02 UTC, vinit1968 commented
trigger uts

2023-10-18 07:40 UTC, vinit1968 commented
trigger uts

2023-10-18 07:41 UTC, vinit1968 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java
> +        infrastructureStepHelper.validateExpression(fieldNameValueMap);
Done

2023-10-18 07:42 UTC, vinit1968 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java
> +  public void validateExpression(Map<String, ParameterField<String>> fieldNameValueMap) {
Done

2023-10-18 07:42 UTC, vinit1968 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java
> +    doThrow(InvalidRequestException.class).when(infrastructureStepHelper).validateExpression(anyMap());
Done

2023-10-18 07:44 UTC, vinit1968 commented
trigger messagecheck

2023-10-18 09:54 UTC, tchaurasiya requested changes

2023-10-18 09:54 UTC, tchaurasiya commented on 125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStepTest.java
> +    // Verify that validateExpression is called with the expected fieldNameValueMap.
nit: code is self explanatory, We should remove these comments

2023-10-18 10:14 UTC, vinit1968 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStepTest.java
> +    // Verify that validateExpression is called with the expected fieldNameValueMap.
Done

2023-10-18 10:18 UTC, vinit1968 commented
trigger uts

2023-10-19 03:59 UTC, tchaurasiya commented on 125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStepTest.java
> +
can we write a junit with values passed as null, as all these field might not be a necessarily not null

2023-10-19 10:18 UTC, vinit1968 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStepTest.java
> +
Added the uts

2023-10-19 10:18 UTC, vinit1968 commented
trigger uts

2023-10-19 10:24 UTC, vinit1968 commented
trigger uts

2023-10-19 11:01 UTC, lovish1999 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53979)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 972 at r1](https://reviewable.io/reviews/harness/harness-core/53979#gh-1352489508:-Nh6_FMpDNnLfb22AAtK:b-o4vlp8) ([raw file](https://github.com/harness/harness-core/blob/fa5f26ca212f608629da1649973b2f771090e95b/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L972)):*
<details><summary><i>Previously, vinit1968 (Vinit Kumar) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Actually, this is still not done. There are two validateInfrastructure methods in this class and we have made changes only for one. But ok, since its non-blocker,  it can be done in another PR. 


<!-- Sent from Reviewable.io -->

2023-10-19 11:02 UTC, tchaurasiya approved these changes

2023-10-19 11:12 UTC, yogesh-chauhan approved these changes

2023-10-19 11:15 UTC, vinit1968 commented
trigger review

2023-10-19 11:18 UTC, merged