[feat]: [CDS-81130]: Added queue service for processing the webhook request
harness/harness-core pull request #53978
Opened 2023-10-10 12:04 UTC by adivishy1

## Describe your changes
Have integrated with the queue service for processing the webhook request instead of the poller by retaining the state management. Locally have test out the changes for webook configured pipelines in default and non default branches.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-10 17:57 UTC, sribalij requested changes

2023-10-10 17:57 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java
> +      try (NgTriggerAutoLogContext ignore0 = new NgTriggerAutoLogContext("eventId", webhookDTO.getEventId(),
Do we already have GitXAutoLogContext?

2023-10-10 17:57 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java
> +      throw new InvalidRequestException("Exception while processing webhook push event", e);
Log a message

2023-10-10 17:57 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java
> +    return "ng" + GITX_WEBHOOK_EVENT;
Add static variable for ng

2023-10-10 17:57 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java
> +      try (NgTriggerAutoLogContext ignore0 = new NgTriggerAutoLogContext("eventId", webhookDTO.getEventId(),
Can this be used GitXWebhookEventLogContext?

2023-10-10 17:57 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java
> +    return "ng" + GITX_WEBHOOK_EVENT;
something like used below QUEUE_TOPIC_PREFIX

2023-10-11 04:39 UTC, shalini-agr approved these changes

2023-10-11 04:47 UTC, Y0709 approved these changes

2023-10-11 05:35 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/53978#gh-1353066355:-NgRy_BK2zaFFCe9yx1b:b-5g9o7c) ([raw file](https://github.com/harness/harness-core/blob/70a33fb3df1a678d909694263f78b69650e13306/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L44)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Can this be used GitXWebhookEventLogContext?
</blockquote></details>

yes, done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/53978#gh-1353066693:-NgRyoNl0Q_CMU4p_2JJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70a33fb3df1a678d909694263f78b69650e13306/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L50)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Log a message
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/53978#gh-1353067000:-NgRywNCErIJEqBQ0wf_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70a33fb3df1a678d909694263f78b69650e13306/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L56)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

something like used below QUEUE_TOPIC_PREFIX
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 05:57 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java
> +      try (NgTriggerAutoLogContext ignore0 = new NgTriggerAutoLogContext("eventId", webhookDTO.getEventId(),
Cool. Thanks

2023-10-11 05:58 UTC, sribalij approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-11 06:17 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`120-ng-manager/config.yml` line 565 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSNK0x6pvXnZmyWIaP:-NgSNK0x6pvXnZmyWIaQ:bhnktzm) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/120-ng-manager/config.yml#L565)):*
> ```YAML
>   threadSleepTimeInMillis: ${WEBHOOK_BRANCH_HOOK_EVENT_DEQUE_THREAD_SLEEP_TIME_IN_MILLIS:-30}
> 
> gitXWebhookPushEventHsqsDequeueConfig:
> ```

can't it be simply called "gitXWebhookEventQueueConfig"? And correspondingly name other fields under it as well.


<!-- Sent from Reviewable.io -->

2023-10-11 06:18 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSNkJAAuHqigVYlDFR:-NgSNkJAAuHqigVYlDFS:b2n18cv) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L34)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PIPELINE)
> public class GitXWebhookPushEventQueueProcessor extends AbstractHsqsQueueProcessor {
> ```

why do we want to name it as PushEventQueue? Doesn't simply calling it "gitXWebhookQueue" works?


<!-- Sent from Reviewable.io -->

2023-10-11 06:20 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSO-DiBKJKHtLtqLGH:-NgSO-DiBKJKHtLtqLGI:b-l8p0pj) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L50)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error("Error while processing webhook push event", e);
> ```

error message should change. Also, same error message used while throwing exception, so we should use it from common variable itself.


<!-- Sent from Reviewable.io -->

2023-10-11 07:02 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 565 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSNK0x6pvXnZmyWIaP:-NgSVwFL4cxpys-hEmiz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/120-ng-manager/config.yml#L565)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't it be simply called "gitXWebhookEventQueueConfig"? And correspondingly name other fields under it as well.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSNkJAAuHqigVYlDFR:-NgSW3kNE4JKNHWs3Yuj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we want to name it as PushEventQueue? Doesn't simply calling it "gitXWebhookQueue" works?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSO-DiBKJKHtLtqLGH:-NgSX6I2EX0RI6H7y7II:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L50)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

error message should change. Also, same error message used while throwing exception, so we should use it from common variable itself.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSPUFXCA0igBkDdFC8:-NgSXFDY5pnddwpoi2mT:b-buyouu) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Throwing exception from here will make the event retry?
</blockquote></details>

As we are not going to ACK when we throw the exception, as per my understanding, we will be retry.
@archit-harness can you pls correct me if i am wrong?


<!-- Sent from Reviewable.io -->

2023-10-11 07:03 UTC, adivishy1 commented
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSNkJAAuHqigVYlDFR:-NgSXu8a7soDJMpqyYLy:b-m5zo1e) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L34)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Had followed the convention used in the other dequeue processors 


<!-- Sent from Reviewable.io -->

2023-10-11 07:31 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 566 at r3](https://reviewable.io/reviews/harness/harness-core/53978#-NgSdRn04uzqDGTlcvby:-NgSdRn04uzqDGTlcvbz:bdmhujs) ([raw file](https://github.com/harness/harness-core/blob/7c5215a596a8b924a1a427b8ec50128e8b7d7fdc/120-ng-manager/config.yml#L566)):*
> ```YAML
> 
> gitXWebhookEventQueueConfig:
>   batchSize: ${GITX_WEBHOOK_PUSH_EVENT_DEQUE_BATCH_SIZE:-20}
> ```

these naming would also change correspondingly


<!-- Sent from Reviewable.io -->

2023-10-11 10:41 UTC, archit-harness reviewed
> Reviewed 4 of 11 files at r1, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSPUFXCA0igBkDdFC8:-NgTJRAiC-p3llb7X3UI:b-8rame1) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If thats the case, we shouldn't be consuming exceptions inside "gitXWebhookEventProcessService.processEvent(webhookDTO);" method call. Those exceptions should be allowed to pass through until this layer.
</blockquote></details>

correct it will retry

Also check i think we have not exposed retry time per stream yet, please connect with @ankittiwari-harness for that, in your case its needed as 60 sec


<!-- Sent from Reviewable.io -->

2023-10-11 10:55 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 566 at r3](https://reviewable.io/reviews/harness/harness-core/53978#-NgSdRn04uzqDGTlcvby:-NgTHQDADrJZkzfrCNrk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c5215a596a8b924a1a427b8ec50128e8b7d7fdc/120-ng-manager/config.yml#L566)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

these naming would also change correspondingly
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/53978#gh-1353066355:-NgTHRySDjt2TZWFFXlZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70a33fb3df1a678d909694263f78b69650e13306/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L44)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Cool. Thanks
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSPUFXCA0igBkDdFC8:-NgTN7_V22mNmGP77iOc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

correct it will retry

Also check i think we have not exposed retry time per stream yet, please connect with @ankittiwari-harness for that, in your case its needed as 60 sec
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 11:18 UTC, adivishy1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/53978#-NgSPUFXCA0igBkDdFC8:-NgTSIHh7_Hq8GWozh7p:bqa1ptr) ([raw file](https://github.com/harness/harness-core/blob/65a5c86a9d07dc0e02b6acc435bc75c860407f09/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener/GitXWebhookPushEventQueueProcessor.java#L51)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Have created a ticket for the same, https://harness.atlassian.net/browse/CDS-81572, thanks @archit-harness 


<!-- Sent from Reviewable.io -->

2023-10-12 07:05 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 573 at r5](https://reviewable.io/reviews/harness/harness-core/53978#-NgXh8-7-VFrEpzyteXP:-NgXh8-7-VFrEpzyteXQ:bp7rw83) ([raw file](https://github.com/harness/harness-core/blob/b622d4564fef0b941d78caa9c9f6f4d325206954/120-ng-manager/config.yml#L573)):*
> ```YAML
> gitXWebhookEventQueueConfig:
>   batchSize: ${GITX_WEBHOOK_EVENT_QUEUE_BATCH_SIZE:-20}
>   threadSleepTimeInMillis: ${GITX_WEBHOOK_EVENT_QUEUE_THREAD_SLEEP_TIME_IN_MILLIS:-30}
> ```

check how its being used


<!-- Sent from Reviewable.io -->

2023-10-12 07:27 UTC, mohitg0795 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53978)* status: 12 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-12 07:53 UTC, adivishy1 commented
trigger uts

2023-10-12 07:59 UTC, adivishy1 commented
trigger uts

2023-10-12 08:13 UTC, mohitg0795 approved these changes

2023-10-12 09:35 UTC, adivishy1 commented
trigger ut5, ut9

2023-10-12 09:36 UTC, utkarshchoubey-harness approved these changes

2023-10-12 09:37 UTC, adivishy1 commented
trigger review

2023-10-12 11:06 UTC, adivishy1 commented
trigger ut5

2023-10-12 12:30 UTC, merged