fix: [CI-9771]: Taking Pod as Base64 object for logging purpose
harness/harness-core pull request #53975
Opened 2023-10-10 11:05 UTC by ShobhitSingh11

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-10 11:15 UTC, ShobhitSingh11 commented
trigger uts

2023-10-10 12:30 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-10 12:31 UTC, ShobhitSingh11 commented
trigger uts

2023-10-10 12:43 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-10 12:44 UTC, ShobhitSingh11 commented
trigger uts

2023-10-10 12:44 UTC, harshjain12 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/CIK8InitializeTaskHandler.java
> +      e.printStackTrace();
put it inside 
log.error()

2023-10-10 12:52 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-10 12:53 UTC, ShobhitSingh11 commented
trigger uts

2023-10-11 05:15 UTC, harshjain12 submitted a review, later dismissed

2023-10-11 05:15 UTC, harshjain12 commented
what is the size of base64 string ?

2023-10-11 05:16 UTC, harshjain12 commented
can you attach screenshot of log from your local

2023-10-11 05:44 UTC, ShobhitSingh11 commented
trigger uts

2023-10-11 05:46 UTC, ShobhitSingh11 commented
> what is the size of base64 string ?

Ref : https://stackoverflow.com/questions/13378815/base64-length-calculation

2023-10-11 09:10 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-11 09:10 UTC, ShobhitSingh11 commented
trigger uts

2023-10-11 09:32 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-11 09:33 UTC, ShobhitSingh11 commented
trigger uts

2023-10-14 20:49 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-14 20:50 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-14 20:55 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-14 20:56 UTC, ShobhitSingh11 commented
trigger uts

2023-10-14 21:11 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-14 21:15 UTC, ShobhitSingh11 commented
trigger uts

2023-10-15 11:52 UTC, ShobhitSingh11 commented
trigger ut4, trigger ut8

2023-10-15 13:05 UTC, ShobhitSingh11 commented
trigger ut8

2023-10-16 09:49 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/codebase/CodeBaseStep.java
> +      throw new RuntimeException(e);
Do not throw exception

2023-10-16 09:49 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/codebase/CodeBaseStep.java
> +      throw new RuntimeException(e);
log.error()

2023-10-16 09:49 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/V1/InitializeTaskStepV2.java
> +        throw new RuntimeException(e);
do not throw exception

2023-10-16 09:49 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/SecurityStageStepPMS.java
> +      throw new RuntimeException(e);
do not throw exeption

2023-10-16 09:50 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/STOSpecStep.java
> +      log.info("Starting execution for spec node step [{}]", EncodingUtils.convertToBase64String(stepParameters));
do not change it

2023-10-16 09:50 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/STOSpecStep.java
> +      log.info("Completed execution for spec node step [{}]", EncodingUtils.convertToBase64String(stepParameters));
do not change it

2023-10-16 09:50 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/SecurityStageStepPMS.java
> +      log.info("Executing integration stage with params accountId {} projectId {} [{}]", accountId, projectIdentifier,
do not change it

2023-10-16 09:50 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/SecurityStageStepPMS.java
> +      throw new RuntimeException(e);
do not change it

2023-10-16 09:50 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/codebase/CodeBaseStep.java
> +      throw new RuntimeException(e);
do not change it

2023-10-16 12:15 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-16 12:25 UTC, harshjain12 commented on 980-commons/src/main/java/io/harness/serializer/JsonUtils.java
> +    mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
Do not change it

2023-10-16 12:26 UTC, harshjain12 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/CIK8InitializeTaskHandler.java
> +        log.info("Creating pod with spec: {}", EncodingUtils.convertToBase64String(pod));
put it in try and catch

2023-10-16 13:27 UTC, harshjain12 commented on 980-commons/src/main/java/io/harness/data/encoding/BUILD.bazel
> +        "//980-commons/src/main/java/io/harness/serializer:module",
do we need it ?

2023-10-16 13:28 UTC, ShobhitSingh11 commented on 980-commons/src/main/java/io/harness/data/encoding/BUILD.bazel
> +        "//980-commons/src/main/java/io/harness/serializer:module",
for JsonUtils build

2023-10-17 07:21 UTC, ShobhitSingh11 commented
trigger uts

2023-10-17 08:46 UTC, ShobhitSingh11 commented
trigger ut9

2023-10-17 09:58 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-17 10:10 UTC, ShobhitSingh11 commented
trigger messagecheck

2023-10-17 10:50 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/IntegrationStageStepPMS.java
> +    // Here have to write it separately because we can't import RecastOrchestrationUtils in Encoding utils class.
remove comments

2023-10-17 10:50 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java
> +        log.info("Created params for build task: {}", EncodingUtils.convertToBase64String(buildSetupTaskParams));
Not required

2023-10-17 10:51 UTC, harshjain12 requested changes

2023-10-17 10:51 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/IntegrationStageStepPMS.java
> +      log.error("Could not serialize", e);
Could not serialize Class name

2023-10-17 10:51 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/V1/InitializeTaskStepV2.java
> +      } catch (IOException e) {
handle exception

2023-10-17 10:51 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/IntegrationStageStepPMS.java
> +      log.error("Could not serialize", e);
handle all exception

2023-10-17 10:51 UTC, harshjain12 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/CIK8InitializeTaskHandler.java
> +        } catch (IOException e) {
handle all exception

2023-10-17 11:13 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-17 11:15 UTC, ShobhitSingh11 commented
trigger uts

2023-10-17 11:26 UTC, ShobhitSingh11 commented
trigger smartchecks

2023-10-17 11:26 UTC, ShobhitSingh11 commented
trigger uts

2023-10-17 12:03 UTC, harshjain12 approved these changes

2023-10-17 14:47 UTC, merged