feat:[CDS-81011]: fix for capability check for Github App connector for CloudFormation, Azure and Terraform
harness/harness-core pull request #54090
Opened 2023-10-12 07:40 UTC by sourabh-awashti

## Describe your changes
Changes are regarding the fix in capability check for delegate tasks for CloudFormation, Azure and Terraform and Terragrunt swimlanes. We are converting account level git connector to repo level git connector before sending it to delegate tasks or capability check.
Tests Done:
1. Validation with Repo level Github connector for all of the above mentioned swimlanes.
2. Validation with Account level Github connector for all mentioned swimlanes and fetch template call in cloudformation.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-12 07:44 UTC, vlica-harness approved these changes

2023-10-12 08:49 UTC, sourabh-awashti commented
trigger uts

2023-10-12 09:16 UTC, yogesh-chauhan requested changes

2023-10-12 09:16 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +                .build();
we can create a new method that takes reponame as the 3rd argument. That will not change existing callers

2023-10-12 09:39 UTC, sourabh-awashti commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +                .build();
done

2023-10-12 09:41 UTC, yogesh-chauhan submitted a review, later dismissed

2023-10-12 09:50 UTC, vlica-harness approved these changes

2023-10-12 10:21 UTC, sourabh-awashti commented
trigger uts

2023-10-12 12:06 UTC, sourabh-awashti commented
trigger uts

2023-10-16 05:41 UTC, sourabh-awashti commented
trigger messagecheck

2023-10-16 05:42 UTC, yogesh-chauhan approved these changes
> Reviewed 5 of 12 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54090)* status: Some of the checks are too old. 12 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-16 05:52 UTC, senjucanon2 approved these changes
> Reviewed 5 of 12 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54090)* status: Some of the checks are too old. 



<!-- Sent from Reviewable.io -->

2023-10-16 06:05 UTC, sourabh-awashti commented
trigger review

2023-10-16 06:08 UTC, merged