[feat]: [PL-41294]: ng api to return Scope details from scope identifiers
harness/harness-core pull request #54098
Opened 2023-10-12 08:50 UTC by pbarapatre10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-17 11:15 UTC, ankit-harness requested changes
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: Some of the checks are too old. 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/BUILD.bazel` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxFo5eBu8lwIkaB13c:-NgxFo5eBu8lwIkaB13d:b-yusz7u) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/BUILD.bazel#L85)):*
> ```Starlark
>     "//clients/servicediscovery:module",
>     "//clients/ngsettings:module",
>     "//clients/scope-info:module",
> ```

Should we call it //clients/scope:module
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 693 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxH4JcB4fd8xz-ZRFN:-NgxH4JcB4fd8xz-ZRFO:b-vw9gwc) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L693)):*
> ```Java
>   @Singleton
>   @Named(SCOPE_INFO_DATA_CACHE_KEY)
>   Cache<String, ScopeInfo> getScopeInfoDataCache(
> ```

Should this cache be defined in orgs-n-projects module
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 696 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxH98x0lbeXCH4vMu3:-NgxH98x0lbeXCH4vMu4:b-ld0ra9) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L696)):*
> ```Java
>       HarnessCacheManager harnessCacheManager, VersionInfoManager versionInfoManager) {
>     return harnessCacheManager.getCache(SCOPE_INFO_DATA_CACHE_KEY, String.class, ScopeInfo.class,
>         AccessedExpiryPolicy.factoryOf(new Duration(TimeUnit.DAYS, 2)),
> ```

Any reason for 2 days
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 860 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxHAkMCaqsA721EAHV:-NgxHAkMCaqsA721EAHW:b-vedwlg) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L860)):*
> ```Java
>         ServiceHttpClientConfig.builder().baseUrl(appConfig.getPipelineServiceClientConfig().getBaseUrl()).build(),
>         appConfig.getNextGenConfig().getPipelineServiceSecret(), NG_MANAGER.toString()));
>     install(new ScopeInfoClientModule(appConfig.getNgManagerClientConfig(),
> ```

Why install Client here?
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 1041 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxHD9DE2U1cqtzx0Cc:-NgxHD9DE2U1cqtzx0Cd:b-3jcp7m) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L1041)):*
> ```Java
>     bind(BambooBuildStepHelperService.class).to(BambooBuildStepHelperServiceImpl.class);
>     bind(EntityRefreshService.class).to(EntityRefreshServiceImpl.class);
>     bind(ScopeInfoResolverService.class).to(ScopeInfoResolverServiceImpl.class);
> ```

Why do this here and not in orgs-n-projects-module?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxJYXmCQGuchBCeOua:-NgxJYXmCQGuchBCeOub:b5y846a) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L44)):*
> ```Java
>   private final Cache<String, ScopeInfo> scopeInfoCache;
>   private final String SCOPE_DETAIL_RESOLVER_LOG_CONST = "[ScopeInfoResolverService]:";
>   private final String SCOPE_INFO_CACHE_KEY_DELIMITER = "|";
> ```

Can we make it "/"
Thats what we are following in Access Control
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKi1hERZnVWHZT1F0:-NgxKi1hERZnVWHZT1F1:b-ynwb6i) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L66)):*
> ```Java
>       if (!accountOrgProjectValidator.isPresent(accountIdentifier, null, null)) {
>         log.warn(format(
>             "%s Account with identifier: %s does not exist", SCOPE_DETAIL_RESOLVER_LOG_CONST, accountIdentifier));
> ```

%s Account with identifier: [%s] does not exist
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKoBL-cD8acBBOpW9:-NgxKoBM6ppK0xqxfmqF:b-i2hxrk) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L71)):*
> ```Java
>       Optional<ScopeInfo> optionalAccountScopeInfo =
>           populateScopeInfo(ScopeLevel.ACCOUNT, accountIdentifier, accountIdentifier, null, null);
>       scopeInfoCache.put(cacheKey, optionalAccountScopeInfo.get());
> ```

I don't see entries removed from this cache on account/org/project deletion
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKIWg87pDUo1kph2F:-NgxKIWg87pDUo1kph2G:b-b5jl9b) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L75)):*
> ```Java
>     }
> 
>     if (isEmpty(projectIdentifier)) {
> ```

We are not calling accountOrgProjectValidator here?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKZDJ9IXwKsX9nHDu:-NgxKZDJ9IXwKsX9nHDv:b546w8h) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L83)):*
> ```Java
>         return optionalOrgScopeInfo;
>       } else {
>         log.warn(format("%s Org with identifier %s in Account: %s does not exist", SCOPE_DETAIL_RESOLVER_LOG_CONST,
> ```

%s Org with identifier [%s] in Account: [%s] does not exist
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKMcL1tzqiciUJ4uW:-NgxKMcL1tzqiciUJ4uX:b-b5jl9b) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L90)):*
> ```Java
> 
>     Optional<Project> proj = projectService.get(accountIdentifier, orgIdentifier, projectIdentifier);
>     if (proj.isPresent()) {
> ```

We are not calling accountOrgProjectValidator here?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKalE3txTJ7zm-7Ij:-NgxKalE3txTJ7zm-7Ik:b-5p13cp) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L96)):*
> ```Java
>       return optionalProjectScopeInfo;
>     } else {
>       log.warn(format("%s Project with identifier %s in Org: %s and Account: %s does not exist",
> ```

%s Project with identifier [%s] in Org: [%s] and Account: [%s] does not exist
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl. [...]

2023-10-25 13:56 UTC, pbarapatre10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: Some of the checks are too old. 20 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/BUILD.bazel` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxFo5eBu8lwIkaB13c:-Nh9y9MR-tusFizXkr8N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/BUILD.bazel#L85)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we call it //clients/scope:module
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 693 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxH4JcB4fd8xz-ZRFN:-Nh9yRtW50UCXPTKBs6j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L693)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this cache be defined in orgs-n-projects module
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 696 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxH98x0lbeXCH4vMu3:-Nhb3FV10NqRl_Wu10AO:b1iw2q7) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L696)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason for 2 days
</blockquote></details>

Made it to 1 day, so if any account/org/project is not accessed for 1 day, it will be removed from cache, thanks
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 1041 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxHD9DE2U1cqtzx0Cc:-Nh9yUuNCQ9-DnGL0UDv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L1041)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why do this here and not in orgs-n-projects-module?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxJYXmCQGuchBCeOua:-Nhb636R7WmKSpYJW6Wi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L44)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we make it "/"
Thats what we are following in Access Control
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKi1hERZnVWHZT1F0:-Nhb6A3P-e_uRUZz6wHl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L66)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

%s Account with identifier: [%s] does not exist
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKoBL-cD8acBBOpW9:-Nhb6B5W-_usM1E4Ptyu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L71)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I don't see entries removed from this cache on account/org/project deletion
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKIWg87pDUo1kph2F:-Nhb6C00518sW37iYsZM:bb2m9lc) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L75)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We are not calling accountOrgProjectValidator here?
</blockquote></details>

No, account is special case where we have to fetch from CG. For Org/Project we are directly calling the service and checking isPresent. accountOrgProjectValidator also does the same but returns a boolean but we need the value as well to put in cache, thanks
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKZDJ9IXwKsX9nHDu:-Nhb6_Im7KrX19QoMYPz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L83)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

%s Org with identifier [%s] in Account: [%s] does not exist
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKMcL1tzqiciUJ4uW:-NhA-xCVDsRZXDI0bIKz:b9qk5wc) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L90)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We are not calling accountOrgProjectValidator here?
</blockquote></details>

No, for account it is a special scenario, since we invoke CG endpoint to get account details. For Org, Project we directly invoke the service and populate the Optional value, thanks
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxKalE3txTJ7zm-7Ij:-NhA-wYS0rzA2QDhonHK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L96)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

%s Project with identifier [%s] in Org: [%s] and Account: [%s] does not exist
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxJjAM4JO8bhoYDrll:-NhA0HqQ1lVsF9nTaEn_:bgbpg94) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoResolverServiceImpl.java#L137)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason for this?
</blockquote></details>

ScopeLevel.ACCOUNT.name() gives 'ACCOUNT' (all caps) and similar for ORG & PROJECT as well. Have kept the key format as : `account|<accountid>|organization|orgid|project|projectid` , thanks
___
*[`clients/scope-info/src/main/java/io/harness/scopeinfoclient/remote/ScopeInfoClient.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxFDsgBUKEDK6OhKX9:-Nhb6i-Q2Lh0w_fJMX8N:b8rswh2) ([raw file] [...]

2023-10-25 14:36 UTC, pbarapatre10 commented
trigger uts

2023-10-25 18:00 UTC, pbarapatre10 commented
trigger uts

2023-10-26 04:24 UTC, pbarapatre10 commented
trigger uts

2023-10-26 10:15 UTC, pbarapatre10 commented
trigger uts

2023-10-26 12:01 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: 20 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ScopeInfoResource.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxGbRw3e_njqyqBfhs:-NhfqWO57y8B0YjRYP1s:b22quet) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/remote/ScopeInfoResource.java#L47)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

What does this AuthRule mean?
</blockquote></details>

Remove this
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/OrganizationProjectModule.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/54098#-NhfqZZHAP573yIgWwp4:-NhfqZZHAP573yIgWwp5:b-rnvgrb) ([raw file](https://github.com/harness/harness-core/blob/69a48d2dbc735ad34e35a6f6eabb21fc506e28c3/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/OrganizationProjectModule.java#L30)):*
> ```Java
> @Slf4j
> @OwnedBy(PL)
> public class OrganizationProjectModule extends AbstractModule {
> ```

ScopeInfoModule
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ScopeInfoResolverService.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxGffF3zma4Q0PRBsX:-Nhfqjmk29meBYkglZPQ:b7bscpk) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ScopeInfoResolverService.java#L19)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we call it just ScopeService
</blockquote></details>

ScopeInfoService


<!-- Sent from Reviewable.io -->

2023-10-27 06:25 UTC, pbarapatre10 commented
trigger uts

2023-10-27 08:46 UTC, ankit-harness requested changes
> Reviewed 5 of 17 files at r2, 4 of 8 files at r3, 7 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 675 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkEdRyDnQaBfUbw-7i:-NhkEdRyDnQaBfUbw-7j:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L675)):*
> ```Java
>   }
> 
>   private ThreadPoolExecutor environmentGitXThreadPool() {
> ```

Why this change?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 44 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkFOqU8_sX0OXZwWNp:-NhkFOqU8_sX0OXZwWNq:bljir2n) ([raw file](https://github.com/harness/harness-core/blob/9e4ac9049ab8ac14587744171ca96583f766d225/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L44)):*
> ```Java
> 
> @OwnedBy(PL)
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> ```

Any reason to remove this and use constructor?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 59 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkF5Fh6cSAtPEyHxg6:-NhkF5Fh6cSAtPEyHxg7:b-ipj60h) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L59)):*
> ```Java
> 
>   private final IPAllowlistRepositoryCustom ipAllowlistRepositoryCustom;
>   private final Cache<String, ScopeInfo> scopeInfoCache;
> ```

Instead of exposing cache outside, we can we expose methods in ScopeInfoService instead

scopeCreated(String scope)
scopeDeleted(String scope)

That will cache will not be exposed and will remain an implementation detail of ScopeInfoService
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 113 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkIugD9ShZPLAGisGU:-NhkIugD9ShZPLAGisGV:b-ffbp2h) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L113)):*
> ```Java
> 
>   @Inject
>   public OrganizationServiceImpl(OrganizationRepository organizationRepository, OutboxService outboxService,
> ```

Have we covered all create and delete paths?

Should we do action on cache first and then on DB on deletion?
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java` line 33 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkHFxpBAGR85XjN8Ad:-NhkHFxpBAGR85XjN8Ae:b-lz574t) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java#L33)):*
> ```Java
>   String orgIdentifier;
>   String projectIdentifier;
>   ScopeLevel scopeType;
> ```

I would not recommend to reuse ScopeLevel. We should define our own I think to avoid coupling.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/utils/ScopeInfoUtils.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkHq_eBTXMYERK6jYe:-NhkHq_eBTXMYERK6jYf:b-ghw5n9) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/utils/ScopeInfoUtils.java#L24)):*
> ```Java
> @UtilityClass
> @Slf4j
> public class ScopeInfoUtils {
> ```

Should this be a public class or package private. Only ScopeInforServiceImpl should be using it
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/ScopeInfoModule.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkImUrCBZCnZTbwg9a:-NhkImUrCBZCnZTbwg9b:b-ylu37c) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/ScopeInfoModule.java#L39)):*
> ```Java
>       HarnessCacheManager harnessCacheManager, VersionInfoManager versionInfoManager) {
>     return harnessCacheManager.getCache(SCOPE_INFO_DATA_CACHE_KEY, String.class, ScopeInfo.class,
>         AccessedExpiryPolicy.factoryOf(new Duration(TimeUnit.DAYS, 1)),
> ```

Should we make it expire after insertion?


<!-- Sent from Reviewable.io -->

2023-10-27 08:46 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 159 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkJ8Uu0cfJfoOr626x:-NhkJ8Uu0cfJfoOr626y:b-ffbp2h) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L159)):*
> ```Java
> 
>   @Inject
>   public ProjectServiceImpl(ProjectRepository projectRepository, OrganizationService organizationService,
> ```

Have we covered all create and delete paths?

Should we do action on cache first and then on DB on deletion?


<!-- Sent from Reviewable.io -->

2023-10-27 10:42 UTC, pbarapatre10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: 20 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 860 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxHAkMCaqsA721EAHV:-NhkLVFEBhsYoUhR24_Y:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L860)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why install Client here?
</blockquote></details>

Removed
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 675 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkEdRyDnQaBfUbw-7i:-NhkLQhdAJ6ZbLK_EHw-:btyixv7) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L675)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

There is no change here, thanks
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 44 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkFOqU8_sX0OXZwWNp:-NhkKCme8ajNoIYFkVEC:bqxdfjz) ([raw file](https://github.com/harness/harness-core/blob/9e4ac9049ab8ac14587744171ca96583f766d225/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L44)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason to remove this and use constructor?
</blockquote></details>

Yes, because with the constructor only the named cache reference is getting injected, and it is not happening with lomboks annotation mostly related to this https://stackoverflow.com/a/56579081
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 59 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkF5Fh6cSAtPEyHxg6:-Nhki_sb4dE1sB84vRVr:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L59)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Instead of exposing cache outside, we can we expose methods in ScopeInfoService instead

scopeCreated(String scope)
scopeDeleted(String scope)

That will cache will not be exposed and will remain an implementation detail of ScopeInfoService
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 113 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkIugD9ShZPLAGisGU:-NhkKMpM2O0GlHXRCNO0:b444aq1) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L113)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Have we covered all create and delete paths?

Should we do action on cache first and then on DB on deletion?
</blockquote></details>

Yes, we have handled create/delete for scope entities Account, Org, Project. 
Done for second point
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 159 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkJ8Uu0cfJfoOr626x:-Nhkifke1wVtIAD3SWuQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L159)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Have we covered all create and delete paths?

Should we do action on cache first and then on DB on deletion?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ScopeInfoResource.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxGbRw3e_njqyqBfhs:-NhjTD2U1dB9E1tm_R7M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/120-ng-manager/src/main/java/io/harness/ng/core/remote/ScopeInfoResource.java#L47)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/OrganizationProjectModule.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/54098#-NhfqZZHAP573yIgWwp4:-NhjT0TbBMMNqYuYKIuj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69a48d2dbc735ad34e35a6f6eabb21fc506e28c3/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/OrganizationProjectModule.java#L30)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

ScopeInfoModule
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ScopeInfoResolverService.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxGffF3zma4Q0PRBsX:-NhjSuxkEdHvLVHReTI5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ScopeInfoResolverService.java#L19)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

ScopeInfoService
</blockquote></details>

Done.
___
*[`clients/scope-info/src/main/java/io/harness/scopeinfoclient/remote/ScopeInfoClient.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/54098#-NgxFLYj5cAlPWnv3PN5:-NhjSwHaDPdmhnVViTeP:bpw10vg) ([raw file](https://github.com/harness/harness-core/blob/3283feffffda6e425e6f855879616c26f4917890/clients/scope-info/src/main/java/io/harness/scopeinfoclient/remote/ScopeInfoClient.java#L26)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we call it ScopeClient?
</blockquote></details>

Keeping aligned to ScopeInfoClient


<!-- Sent from Reviewable.io -->

2023-10-27 16:41 UTC, pbarapatre10 commented
trigger uts

2023-10-28 05:23 UTC, ankit-harness approved these changes
> Reviewed 6 of 6 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: 20 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-28 05:33 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java` line 29 at r11](https://reviewable.io/reviews/harness/harness-core/54098#-NhokcIQ5P1TOM6Lr7yj:-NhokcIQ5P1TOM6Lr7yk:b-waiqb1) ([raw file](https://github.com/harness/harness-core/blob/14dda85d474e3dfbce33d99df97b3720f955c9de/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java#L29)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class ScopeInfo {
> ```

Should we have accountIdentifier, orgIdentifier and projectIdentifier in ScopeInfo? I am thinking about possibility if we introduce folder in future. How will call interpret these fields. Also, these fields are already available with caller. I am in favour of exposing as less info as we can and expose only if required as its a API used by module teams
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java` line 33 at r11](https://reviewable.io/reviews/harness/harness-core/54098#-NholQ6-6oINYtN2iZ6S:-NholQ6-6oINYtN2iZ6T:b-gfjwb) ([raw file](https://github.com/harness/harness-core/blob/14dda85d474e3dfbce33d99df97b3720f955c9de/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java#L33)):*
> ```Java
>   String orgIdentifier;
>   String projectIdentifier;
>   ScopeLevel scopeType;
> ```

Lets call it only type to avoid redundancy


<!-- Sent from Reviewable.io -->

2023-10-28 05:45 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/ScopeInfoModule.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkImUrCBZCnZTbwg9a:-NhonwPM-S79qmSfceNJ:b-7aiw7c) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/ScopeInfoModule.java#L39)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we make it expire after insertion?
</blockquote></details>

No, if expiry is set after insertion, even if the ORG/PROJECT was queries recently like 5 second back we might still expire it. Cache eviction policy with AccessedExpiry is based on last referenced at, thanks


<!-- Sent from Reviewable.io -->

2023-10-28 05:49 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java` line 29 at r11](https://reviewable.io/reviews/harness/harness-core/54098#-NhokcIQ5P1TOM6Lr7yj:-NhoouMlEDE8EvHqNTlB:b23dhyx) ([raw file](https://github.com/harness/harness-core/blob/14dda85d474e3dfbce33d99df97b3720f955c9de/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we have accountIdentifier, orgIdentifier and projectIdentifier in ScopeInfo? I am thinking about possibility if we introduce folder in future. How will call interpret these fields. Also, these fields are already available with caller. I am in favour of exposing as less info as we can and expose only if required as its a API used by module teams
</blockquote></details>

We certainly need accountIdentifier, so as to be able to log details 


<!-- Sent from Reviewable.io -->

2023-10-28 05:49 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java` line 33 at r8](https://reviewable.io/reviews/harness/harness-core/54098#-NhkHFxpBAGR85XjN8Ad:-NhooVkf-MdrOVnKTAjy:b-wcjyhk) ([raw file](https://github.com/harness/harness-core/blob/746524d1fa019057ad7673809009b72111186c4c/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I would not recommend to reuse ScopeLevel. We should define our own I think to avoid coupling.
</blockquote></details>

This is needed irrespective of even if we define our own. THe same we are using in Cache key as well ACCOUNT/accountId/ORGANIZATION/orgId/PROJECT/projectId, we can discuss and fix in subsequent PR


<!-- Sent from Reviewable.io -->

2023-10-28 05:49 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java` line 33 at r11](https://reviewable.io/reviews/harness/harness-core/54098#-NholQ6-6oINYtN2iZ6S:-NhooRQVAaZitEw8aapC:bhru0zl) ([raw file](https://github.com/harness/harness-core/blob/14dda85d474e3dfbce33d99df97b3720f955c9de/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/beans/ScopeInfo.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets call it only type to avoid redundancy
</blockquote></details>

will handle in subsequent PR


<!-- Sent from Reviewable.io -->

2023-10-28 06:41 UTC, ankit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098)* status: 20 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-28 06:57 UTC, pbarapatre10 commented
trigger uts

2023-10-28 12:39 UTC, pbarapatre10 commented
trigger uts

2023-10-29 05:19 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54098#-:-NhtrrMXA-7oESN0Z-me:bnfp4nl)* status: 20 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-29 09:13 UTC, merged