feat: [PL-42000]: add index to support deletion for a notification for an accountId
harness/harness-core pull request #54184
Opened 2023-10-16 11:14 UTC by sahibaHarness

## Describe your changes
As part of data cleanup activity Notification related data gets clean up when an account is deleted. In this we remove all the data in the collection for given accountId.
As there is no index available on accountId it does a COLLSCAN.

MATCHING VALUES: 17493
TOTAL NUMBER OF RECORDS: 19889
Before adding this index:
<img width="492" alt="Pasted Graphic" src="https://github.com/harness/harness-core/assets/112424209/ab3bb3d2-73a6-4b82-8535-e55ee641ff2d">
post adding index:
<img width="705" alt="Pasted Graphic 1" src="https://github.com/harness/harness-core/assets/112424209/67aded41-3326-4ce1-87fd-dba181181057">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-16 11:18 UTC, sahibaHarness commented
trigger uts

2023-10-16 11:56 UTC, bhavya181 requested changes

2023-10-16 11:56 UTC, bhavya181 commented on platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/Notification.java
> +                 .build())
there is no need to create index on accountId and createdAt, there is no query to list notifications right now, so just put an FDIndex on accountId for now, if we add some query on timestamp in future then that time we will create index on timestamp.

2023-10-16 12:34 UTC, sahibaHarness commented on platform-service/modules/notification-service/src/main/java/io/harness/notification/entities/Notification.java
> +                 .build())
ack

2023-10-16 12:59 UTC, sahibaHarness commented
trigger uts

2023-10-17 08:01 UTC, ankit-harness approved these changes

2023-10-17 08:07 UTC, merged