feat: [CDS-80321]: caching ECR token
harness/harness-core pull request #54188
Opened 2023-10-16 12:26 UTC by GoelPratyush99

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-16 12:33 UTC, GoelPratyush99 commented
trigger uts

2023-10-16 14:03 UTC, GoelPratyush99 commented
trigger uts

2023-10-16 14:08 UTC, abosii-harness requested changes

2023-10-16 14:08 UTC, abosii-harness commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  HELM_VALUES_FETCH_NG_OCI_ECR_CONFIG_V2(
Why we need a new version of task?

2023-10-16 14:17 UTC, GoelPratyush99 commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  HELM_VALUES_FETCH_NG_OCI_ECR_CONFIG_V2(
To keep changes backward compatible we need new tasks. Earlier I used repoName which was utilised by ECR API, but now the repoName is different compared to chartName to use registryConfigFilePath. Hence changes are not backward compatible.

2023-10-16 14:24 UTC, abosii-harness commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  HELM_VALUES_FETCH_NG_OCI_ECR_CONFIG_V2(
But how providing a value is not backward compatible? What exactly breaks here? Here is the condition to use v1 or v2?

2023-10-17 05:16 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +  private void saveAuthorizationDataToCache(AuthorizationData authorizationData, String ecrKeyDirectory) {
Made the requested changes

2023-10-17 05:21 UTC, GoelPratyush99 commented
trigger uts

2023-10-17 06:00 UTC, abosii-harness requested changes

2023-10-17 06:00 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/delegate/K8sManifestDelegateMapper.java
> +    String repoName = getRepoName(ambiance, ociConnectorDTO.getIdentifier(), helmChartManifestOutcome);
Can you explain why we need repoName?

2023-10-17 06:01 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +      CacheBuilder.newBuilder().expireAfterWrite(12, TimeUnit.HOURS).build();
As well we may want to limit the maximum amount of values stored in cache

2023-10-17 06:38 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +    String repositoryUrl = getEcrRepoUrl(ociHelmStoreDelegateConfig, chartName);
I was thinking of using only registryId and region as ECR auth token can be scoped to specific region if custom IAM policy is configured. I am not considering the chartName

2023-10-17 06:58 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/delegate/K8sManifestDelegateMapper.java
> +    String repoName = getRepoName(ambiance, ociConnectorDTO.getIdentifier(), helmChartManifestOutcome);
Repo name is being used to create chartDirectory Path (i.e., working dir or cache dir)

2023-10-17 11:37 UTC, GoelPratyush99 commented
trigger uts

2023-10-17 11:58 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java
> +      CacheBuilder.newBuilder().expireAfterWrite(12, TimeUnit.HOURS).build();
done

2023-10-17 12:49 UTC, GoelPratyush99 commented
trigger uts

2023-10-17 13:50 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecr/EcrAuthKey.java
> +  private AwsConfig awsConfig;
AwsConfig shouldn't be included in the equals and hash code

2023-10-17 14:25 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecr/EcrAuthKey.java
> +  private AwsConfig awsConfig;
Done. But why do we need to exclude it?

2023-10-17 14:25 UTC, GoelPratyush99 commented
trigger uts

2023-10-17 15:06 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecr/EcrAuthKey.java
> +  private AwsConfig awsConfig;
Cache is based on hash table, so the key will be matched by the content of the AwsConfig and it's hashcode. I'm not sure if this is a good idea
Do we have something like connector id? Or maybe we should use repoName? Since registry id is optional it means that the cache will work only based on region. Can you review this key once again?

2023-10-17 15:39 UTC, abhinavsingh1196 approved these changes
> Reviewed 10 of 13 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, 10 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54188)* status: 21 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-10-17 15:44 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecr/EcrAuthKey.java
> +  private AwsConfig awsConfig;
registry Id will be null at this point in the code as I am extracting it from the ecrRepoUrl that is being call earlier.

2023-10-17 15:46 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecr/EcrAuthKey.java
> +  private AwsConfig awsConfig;
The AwsConfig does not seem a bad option to me. It should be dependent on the IAM provided by the user so that the ECR Auth token generated have proper scope.

2023-10-17 15:53 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecr/EcrAuthKey.java
> +  private AwsConfig awsConfig;
If the whole `AwsConfig` seem overkill then we use the `crossAccountRoleArn`

2023-10-18 11:55 UTC, GoelPratyush99 commented
trigger uts

2023-10-18 12:48 UTC, GoelPratyush99 commented
trigger uts

2023-10-18 12:50 UTC, GoelPratyush99 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecr/EcrAuthKey.java
> +  private AwsConfig awsConfig;
Verified for AwsConfig creating 2 instance with same value the EqualsAndHashCode works. If OciRegistry login fails then we are fetching the new token and using it.

2023-10-18 14:07 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54188)* status: 23 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java` line 901 at r7](https://reviewable.io/reviews/harness/harness-core/54188#-Nh235h66dW9B482oMeE:-Nh269SV5zpkZt0WclFz:b5reotx) ([raw file](https://github.com/harness/harness-core/blob/297baca0104874541e69123178de55c0af692c44/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java#L901)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

isn't this computing twice? if cache is refreshed, just return from cache? or compute it, store it in cache and return it?
</blockquote></details>

True, we would be computing the token twice but refresh happens async hence I thought it will be a better option compared to `cache.put` as this could cause concurrency issue which we will have handle using synchronised block
___
*[`951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java` line 528 at r2](https://reviewable.io/reviews/harness/harness-core/54188#gh-1360722339:-Nh26EXF-GD9UXC0UeOx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e03f761a9c1d970ccb40eb3630914610b1b2bc9/951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java#L528)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I still think that your changes should be backward compatible. I would even say that introducing this is not backward compatible. Let's assume that customer has already start using ECR with an old delegate that doesn't have V2. Currently you don't have any logic that decide to use V1 or V2, you're just replacing V1 with V2, so now for customer this is a breaking change
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 14:33 UTC, GoelPratyush99 commented
trigger uts

2023-10-18 14:51 UTC, abhinavsingh1196 approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54188)* status: 23 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-10-18 15:35 UTC, GoelPratyush99 commented
trigger ut9

2023-10-18 15:35 UTC, GoelPratyush99 commented
trigger review

2023-10-18 16:12 UTC, merged