feat: [CDS-80735]: Introduce Max timeout limit for Stage and Pipeline
harness/harness-core pull request #54218
Opened 2023-10-17 03:48 UTC by shivamnegi94

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-17 04:55 UTC, shivamnegi94 commented
trigger uts

2023-10-17 09:53 UTC, archit-harness requested changes
> Reviewed 8 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2-jV8401aU_g2MXI:-Ngx2-jV8401aU_g2MXJ:b-nm03cw) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L68)):*
> ```Java
>   }
> 
>   public ParameterField<Timeout> getStageTimeout(ParameterField<Timeout> timeout, String defaultTimeout) {
> ```

we should rename to maxTimeout
___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx271d3-Ha2k52YwVD:-Ngx271d3-Ha2k52YwVE:b-6yvogn) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L70)):*
> ```Java
>   public ParameterField<Timeout> getStageTimeout(ParameterField<Timeout> timeout, String defaultTimeout) {
>     if (ParameterField.isNull(timeout)) {
>       return ParameterField.createValueField(Timeout.fromString(DEFAULT_STAGE_TIMEOUT));
> ```

we shouldnt have default value for stage, if not given set as max value
___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2G-CBioBbNeY0Xli:-Ngx2G-CBioBbNeY0Xlj:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L74)):*
> ```Java
>     // If the timeout field is runtime input then use default value
>     if (timeout.isExpression() && NGExpressionUtils.matchesInputSetPattern(timeout.getExpressionValue())) {
>       return ParameterField.createValueField(Timeout.fromString(DEFAULT_STAGE_TIMEOUT));
> ```

same as above
___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2IUs070AHZdbp_cL:-Ngx2IUs070AHZdbp_cM:bhb6kp2) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L77)):*
> ```Java
>     }
> 
>     Timeout maxTimeout = Timeout.fromString(defaultTimeout);
> ```

what will happen if timeout is expression and not <+input>
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java` line 262 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2O99DpQBLvJHH3VW:-Ngx2O99DpQBLvJHH3VX:b3436sa) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java#L262)):*
> ```Java
>   public String getTimeoutDuration(String timeoutIdentifier) {
>     PlanCreationContextValue value = getMetadata();
>     return value.getExecutionContext().getSettingToValueMapOrThrow(timeoutIdentifier);
> ```

i dont think we should throw, else return high value
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx1rGE5xNo-tyNZsnt:-Ngx1rGE5xNo-tyNZsnu:b-r8y476) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L197)):*
> ```Java
>         accountId, null, null, SettingCategory.PMS, PMS_EXECUTION_SETTINGS_GROUP_IDENTIFIER);
> 
>     List<SettingResponseDTO> response = NGRestUtils.getResponse(responseDTOCall);
> ```

we should add exception handling, if error log and send some high value



_Code quote:_
```Java
    Call<ResponseDTO<List<SettingResponseDTO>>> responseDTOCall = ngSettingsClient.listSettings(
        accountId, null, null, SettingCategory.PMS, PMS_EXECUTION_SETTINGS_GROUP_IDENTIFIER);

    List<SettingResponseDTO> response = NGRestUtils.getResponse(responseDTOCall);
```


<!-- Sent from Reviewable.io -->

2023-10-18 04:38 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 21 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx271d3-Ha2k52YwVD:-Nh02xL5Bt-RR-Nfwry3:b-yw6ws9) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we shouldnt have default value for stage, if not given set as max value
</blockquote></details>

@archit-harness It was discussed right we will not set max value for now if customer not configured timeout 
?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx1rGE5xNo-tyNZsnt:-Nh03mJ93C1mz_bh-VQv:beu7tma) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add exception handling, if error log and send some high value
</blockquote></details>

But what we will set here because we have MAP of settings variable


<!-- Sent from Reviewable.io -->

2023-10-18 04:45 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 21 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2-jV8401aU_g2MXI:-Nh05BuoCEymwtUxajKS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should rename to maxTimeout
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2IUs070AHZdbp_cL:-Nh05OGy7EPu02tnmwSp:b-hoconk) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L77)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what will happen if timeout is expression and not <+input>
</blockquote></details>

We are validating right if it is expression here
if (timeout.isExpression() && NGExpressionUtils.matchesInputSetPattern(timeout.getExpressionValue())) {  
  return ParameterField.createValueField(Timeout.fromString(DEFAULT\_STAGE\_TIMEOUT));  
}


<!-- Sent from Reviewable.io -->

2023-10-18 05:11 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 22 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java` line 262 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2O99DpQBLvJHH3VW:-Nh0BQyV6eRvaI3ZOd6T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/PlanCreationContext.java#L262)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont think we should throw, else return high value
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-20 08:43 UTC, shivamnegi94 commented
trigger uts

2023-10-20 09:24 UTC, archit-harness requested changes
> Reviewed 1 of 21 files at r1, 1 of 3 files at r2, 10 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 27 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 229 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBGx7u-Ui8OaN8An1f:-NhBGx7u-Ui8OaN8An1g:b-dlvtua) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L229)):*
> ```Java
>             .adviserObtainments(adviserObtainments);
> 
>     Pair<PlanNodeBuilder, StageElementParametersBuilder> planNodeBuilderStageElementParametersBuilderPair =
> ```

can this be some short field name?



_Code quote:_
```Java
planNodeBuilderStageElementParametersBuilderPair
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 232 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBJ65S8jS4uBTIA5Q0:-NhBJ65S8jS4uBTIA5Q1:bp5q58f) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L232)):*
> ```Java
>         setStageTimeoutObtainment(stageNode.getTimeout(), builder, ctx.getTimeoutDuration(MAX_STAGE_TIMEOUT.getName()),
>             ctx.getMetadata().getExecutionContext().getFeatureFlagToValueMapOrDefault(
>                 FeatureName.CDS_DISABLE_TIMEOUT_CONFIG.toString(), false),
> ```

ctx can be passed



_Code quote:_
```Java
        setStageTimeoutObtainment(stageNode.getTimeout(), builder, ctx.getTimeoutDuration(MAX_STAGE_TIMEOUT.getName()),
            ctx.getMetadata().getExecutionContext().getFeatureFlagToValueMapOrDefault(
                FeatureName.CDS_DISABLE_TIMEOUT_CONFIG.toString(), false),
```
___
*[`310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreator.java` line 487 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBH3o7C-ZDc5XbKEnF:-NhBH3o7C-ZDc5XbKEnG:b-7h4529) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreator.java#L487)):*
> ```Java
>             .adviserObtainments(StrategyUtils.getAdviserObtainments(ctx.getCurrentField(), kryoSerializer, true));
> 
>     Pair<PlanNodeBuilder, StageElementParametersBuilder> planNodeBuilderStageElementParametersBuilderPair =
> ```

same as above and for others
___
*[`884-pms-commons/src/main/java/io/harness/pms/timeout/AbsoluteSdkTimeoutTrackerParameters.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBHFfc0Ps2S1-eE3AT:-NhBHFfc0Ps2S1-eE3AU:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/884-pms-commons/src/main/java/io/harness/pms/timeout/AbsoluteSdkTimeoutTrackerParameters.java#L31)):*
> ```Java
> 
>   @Override
>   public ParameterField<String> getTimeoutString() {
> ```

why is this needed?
___
*[`970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/54218#-Ngx2G-CBioBbNeY0Xli:-NhBHWc2EFaXrenFDdSu:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/600ff3de5e7f2d070e45338e5a2c47327568a591/970-ng-commons/src/main/java/io/harness/utils/TimeoutUtils.java#L74)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 201 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBIpFb2YPGUbkEQYfH:-NhBIpFb2YPGUbkEQYfI:bsuoyq9) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L201)):*
> ```Java
>     Map<String, String> settingsMap = new HashMap<>();
>     Map<String, Boolean> featureFlagMap = new HashMap<>();
>     if (null != metadata && null != metadata.getFeatureFlagToValueMapMap()) {
> ```

not required


<!-- Sent from Reviewable.io -->

2023-10-21 15:04 UTC, shivamnegi94 commented
Created small PRs

2023-10-26 07:01 UTC, shivamnegi94 commented
trigger uts

2023-10-26 09:22 UTC, shivamnegi94 commented
trigger ut1, ut3, ut4, ut6, ut7

2023-10-27 04:19 UTC, shivamnegi94 commented
trigger ut3, ut4, ut6

2023-10-27 10:21 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 28 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 110 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-Nhk_6e6-BPvPb_c3rXP:-Nhk_6e6-BPvPb_c3rXQ:bw8l0cl) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L110)):*
> ```YAML
>     name: Max Stage Timeout
>     category: PMS
>     defaultValue: 30m
> ```

lets have this default value of 1h
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 113 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-NhkZgG-9s3Mb_eUmuWf:-NhkZgG-9s3Mb_eUmuWg:b45f38x) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L113)):*
> ```YAML
>     groupIdentifier: pms_execution_settings
>     valueType: STRING
>     groupIdentifier: pms_execution_settings
> ```

groupIdentifer mentioned twice
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 120 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-Nhk_Cyg2V6yIuxkoLrn:-Nhk_Cyg2V6yIuxkoLro:bfg4ys3) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L120)):*
> ```YAML
>     allowedPlans:
>       FREE:
>         defaultValue: 4h
> ```

this should be 1 isnt?
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 129 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-Nhk_JrECFjOABeGi77f:-Nhk_JrECFjOABeGi77g:bsf3tg5) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L129)):*
> ```YAML
>         editable: true
>   - identifier: stage_timeout
>     name: Max Stage Timeout
> ```

stage is defined twice why?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 229 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBGx7u-Ui8OaN8An1f:-NhkaSD892vsedxsCe9R:bjbfq03) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L229)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can this be some short field name?
</blockquote></details>

we should rename it better


<!-- Sent from Reviewable.io -->

2023-10-30 06:19 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 28 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 110 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-Nhk_6e6-BPvPb_c3rXP:-NhzDsvq0U7I_9rgWbRG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L110)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets have this default value of 1h
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 113 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-NhkZgG-9s3Mb_eUmuWf:-NhzDtG936MhyijTRJmx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

groupIdentifer mentioned twice
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 120 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-Nhk_Cyg2V6yIuxkoLrn:-NhzDuA1D_3uXzmbDeHb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L120)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this should be 1 isnt?
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 129 at r7](https://reviewable.io/reviews/harness/harness-core/54218#-Nhk_JrECFjOABeGi77f:-NhzDvO35wlIshdT0VAl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e2ab429696c65c74c734d8295bf0f908dac9d39/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L129)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

stage is defined twice why?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 229 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBGx7u-Ui8OaN8An1f:-NhzDyFB5nf6EDxVa_0k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L229)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should rename it better
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 232 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBJ65S8jS4uBTIA5Q0:-NhzDz1s6e3GhDGtexn7:b-tonzxc) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L232)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

ctx can be passed
</blockquote></details>

FeatureName class is not accessible from pms-constant module.
___
*[`884-pms-commons/src/main/java/io/harness/pms/timeout/AbsoluteSdkTimeoutTrackerParameters.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBHFfc0Ps2S1-eE3AT:-NhzE9oV-HdSP_t12fj6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/884-pms-commons/src/main/java/io/harness/pms/timeout/AbsoluteSdkTimeoutTrackerParameters.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java` line 201 at r4](https://reviewable.io/reviews/harness/harness-core/54218#-NhBIpFb2YPGUbkEQYfH:-NhzECHH-_bKty_yQ1vL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f82cc6085df9981293c8a4ba476fee5c6c4cba3e/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PlanCreatorMergeService.java#L201)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

not required
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 06:21 UTC, shivamnegi94 commented
trigger uts

2023-10-30 06:41 UTC, shivamnegi94 commented
trigger uts

2023-10-31 03:40 UTC, shivamnegi94 commented
trigger ut3, ut4, ut6, ut7

2023-10-31 12:22 UTC, shivamnegi94 commented
trigger uts

2023-10-31 15:12 UTC, shivamnegi94 commented
trigger uts

2023-10-31 15:57 UTC, shivamnegi94 commented
trigger uts

2023-10-31 16:31 UTC, archit-harness requested changes
> Reviewed 3 of 14 files at r5, 6 of 14 files at r6, 7 of 7 files at r7, 1 of 3 files at r8, 2 of 8 files at r9, 7 of 9 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 33 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 220 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5YehfExcOIW1EERfg:-Ni5YehfExcOIW1EERfh:b-n7c4vw) ([raw file](https://github.com/harness/harness-core/blob/82b7be6b3a5f925f125fd3974f71cdd5bcbfe570/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L220)):*
> ```Java
>             .identifier(stageNode.getIdentifier())
>             .group(StepOutcomeGroup.STAGE.name())
>             .stepParameters(stageParameters.build())
> ```

lets introduce this back and same for below
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java` line 152 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5Z7fW6jdbs7CHisjC:-Ni5Z7fX53IlxYdtrbc6:b-n10icb) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java#L152)):*
> ```Java
>     ParameterField<Timeout> timeoutParameterField = SdkTimeoutObtainmentUtils.getTimeoutObtainment(config.getTimeout(),
>         ctx.getTimeoutDuration(MAX_STAGE_TIMEOUT.getName()),
>         ctx.getMetadata().getExecutionContext().getFeatureFlagToValueMapOrDefault(
> ```

introduce method in planCreationContext



_Code quote:_
```Java
ctx.getMetadata().getExecutionContext().getFeatureFlagToValueMapOrDefault
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java` line 37 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5ZES2AKvX_08U6rYm:-Ni5ZES2AKvX_08U6rYn:br9f2q2) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java#L37)):*
> ```Java
>     return Set.of(HarnessYamlVersion.V0, HarnessYamlVersion.V1);
>   }
>   default PlanNodeBuilder setStageTimeoutObtainment(ParameterField<Timeout> timeout, PlanNodeBuilder planNodeBuilder) {
> ```

introduce back in util
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java` line 75 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5ZWgL6pDRIKeKcOzW:-Ni5ZWgL6pDRIKeKcOzX:baenwyy) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java#L75)):*
> ```Java
> 
>     StepParameters stepParameters =
>         PipelineSetupStepParameters.getStepParameters(ctx, config, stagesYamlNode.getUuid());
> ```

introduce it here, and set after getting timeoutObtainment



_Code quote:_
```Java
PipelineSetupStepParameters
```


<!-- Sent from Reviewable.io -->

2023-10-31 16:44 UTC, archit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 33 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5bj8y8mualgVOjKMW:-Ni5bj8y8mualgVOjKMX:btucyyk) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java#L41)):*
> ```Java
>         SdkTimeoutObtainment.builder()
>             .dimension(AbsoluteTimeoutTrackerFactory.DIMENSION)
>             .parameters(AbsoluteSdkTimeoutTrackerParameters.builder()
> ```

add handling for expression for timeuot
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 42 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5b-QDBhfFk5ALxg5e:-Ni5b-QDBhfFk5ALxg5f:buc3kym) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L42)):*
> ```Java
>   }
> 
>   public ParameterField<Timeout> getTimeoutParameterField(
> ```

private
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 43 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5b0Pi6H-P6-eu5YLb:-Ni5b0Pi6H-P6-eu5YLc:brfp7e1) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L43)):*
> ```Java
> 
>   public ParameterField<Timeout> getTimeoutParameterField(
>       ParameterField<Timeout> timeoutParameterField, String maxTimeout) {
> ```

givenTimeout
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 46 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5b7yW63GNGyfLuk3i:-Ni5b7yW63GNGyfLuk3j:b-69tkum) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L46)):*
> ```Java
>     if (timeoutParameterField.isExpression()) {
>       return NGExpressionUtils.matchesInputSetPattern(timeoutParameterField.getExpressionValue())
>           ? ParameterField.createValueField(Timeout.fromString(DEFAULT_TIMEOUT))
> ```

should be maxTimeout
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 51 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5bDBc9kKDoMplw4Lg:-Ni5bDBc9kKDoMplw4Lh:buc3kym) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L51)):*
> ```Java
>     return getMinTimeoutValue(timeoutParameterField, maxTimeout);
>   }
>   public ParameterField<Timeout> getMinTimeoutValue(ParameterField<Timeout> timeout, String maxTimeout) {
> ```

private
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 51 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5bELY-S-P7AKfl0DL:-Ni5bELY-S-P7AKfl0DM:brfp7e1) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L51)):*
> ```Java
>     return getMinTimeoutValue(timeoutParameterField, maxTimeout);
>   }
>   public ParameterField<Timeout> getMinTimeoutValue(ParameterField<Timeout> timeout, String maxTimeout) {
> ```

givenTimeout


<!-- Sent from Reviewable.io -->

2023-11-02 02:48 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 220 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5YehfExcOIW1EERfg:-NiCvgmo8LN0LqgcZUPl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/82b7be6b3a5f925f125fd3974f71cdd5bcbfe570/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L220)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets introduce this back and same for below
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java` line 152 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5Z7fW6jdbs7CHisjC:-NiCvcY42xJEp_2J7X9Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java#L152)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

introduce method in planCreationContext
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java` line 37 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5ZES2AKvX_08U6rYm:-NiCvbuNDYxRXNWg6yF4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

introduce back in util
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java` line 41 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5bj8y8mualgVOjKMW:-NiCvbN_8edaGZWXftLP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PartialPlanCreator.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add handling for expression for timeuot
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java` line 75 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5ZWgL6pDRIKeKcOzW:-NiCv_sfARGd7ShV0Owi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

introduce it here, and set after getting timeoutObtainment
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 42 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5b-QDBhfFk5ALxg5e:-NiCvfqoBNASuYu_kLJL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 43 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5b0Pi6H-P6-eu5YLb:-NiCvfdbEVJmWc1eW80t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

givenTimeout
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 46 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5b7yW63GNGyfLuk3i:-NiCvfEt8xxwwcWwyb_k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should be maxTimeout
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 51 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5bELY-S-P7AKfl0DL:-NiCveYJ8XjaDsaFf4ux:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

givenTimeout
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 51 at r12](https://reviewable.io/reviews/harness/harness-core/54218#-Ni5bDBc9kKDoMplw4Lg:-NiCvestE4kz1b0Ud5sw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a03b8cefa392d68b1cb822e3e7b4c7d936eb2916/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L51)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 05:54 UTC, archit-harness requested changes
> Reviewed 1 of 8 files at r9, 5 of 9 files at r13, 4 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java` line 158 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDaDwp72jcTXU6rVJd:-NiDaDwp72jcTXU6rVJe:b-ub0wjt) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java#L158)):*
> ```Java
>       planNodeBuilder.stepParameters(
>           stageElementParameters.toBuilder()
>               .timeout(ParameterField.createValueField(timeoutParameterField.getValue().getTimeoutString()))
> ```

this can be null, thus set only if non-null



_Code quote:_
```Java
timeoutParameterField.
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java` line 92 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDa6Ay0K_1_Iv3aHFD:-NiDa6Ay0K_1_Iv3aHFE:b-agnrlo) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java#L92)):*
> ```Java
>     planNodeBuilder = SdkTimeoutObtainmentUtils.setStageTimeoutObtainment(timeout, planNodeBuilder);
>     StepParameters stepParameters = PipelineSetupStepParameters.getStepParameters(
>         ctx, config, stagesYamlNode.getUuid(), ParameterField.createValueField(timeout.getValue().getTimeoutString()));
> ```

we should add null handling it here
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 32 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDZTdJ0pDc7WZCLCfs:-NiDZTdJ0pDc7WZCLCft:b-pkz0g4) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L32)):*
> ```Java
> public class SdkTimeoutObtainmentUtils {
>   public static final String MAX_TIMEOUT = "8w";
>   public ParameterField<Timeout> getTimeoutObtainment(
> ```

this is not returning timeoutObtainment but instead its timeout



_Code quote:_
```Java
getTimeoutObtainmen
```
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 33 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDXlH02SnJgqdVYQaP:-NiDXlH02SnJgqdVYQaQ:b11xibk) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L33)):*
> ```Java
>   public static final String MAX_TIMEOUT = "8w";
>   public ParameterField<Timeout> getTimeoutObtainment(
>       ParameterField<Timeout> timeout, String maxTimeout, boolean disableTimeout) {
> ```

rename to notApplyMaxTimeout



_Code quote:_
```Java
disableTimeout
```
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 53 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDZlKqCNlnqi-PrDVV:-NiDZlKqCNlnqi-PrDVW:bqjzy0k) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L53)):*
> ```Java
>     if (givenTimeout.isExpression()) {
>       return NGExpressionUtils.matchesInputSetPattern(givenTimeout.getExpressionValue())
>           ? ParameterField.createValueField(Timeout.fromString(MAX_TIMEOUT))
> ```

it should be maxTimeout variables



_Code quote:_
```Java
Timeout.fromString(MAX_TIMEOUT)
```
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 59 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiD_0xU77f7hA2NQrlX:-NiD_0xU77f7hA2NQrlY:b-ujri8i) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L59)):*
> ```Java
>   }
>   private ParameterField<Timeout> getMinTimeoutValue(ParameterField<Timeout> givenTimeout, String maxTimeout) {
>     Timeout maxTimeoutString = Timeout.fromString(maxTimeout);
> ```

its not string, thus rename it



_Code quote:_
```Java
maxTimeoutString
```


<!-- Sent from Reviewable.io -->

2023-11-02 07:50 UTC, sahilhindwani-harness commented
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 31 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiE-eGoC_m6xc122aNr:-NiE-eGoC_m6xc122aNs:b-6ozur1) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L31)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_PIPELINE})
> public class SdkTimeoutObtainmentUtils {
>   public static final String MAX_TIMEOUT = "8w";
> ```

Should we make this configurable via environment variable?


<!-- Sent from Reviewable.io -->

2023-11-02 07:51 UTC, sahilhindwani-harness commented
Can we test what happens if timeout is defined as an expression and it is greater than the max timeout?





<!-- Sent from Reviewable.io -->

2023-11-02 07:55 UTC, archit-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 31 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiE-eGoC_m6xc122aNr:-NiE0_VxBR0GHZ7UJHCK:b-w2bmt7) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L31)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we make this configurable via environment variable?
</blockquote></details>

this value is for older path flow, eventually this code will be removed, so don't want to expose as config as of now, kept to same it consistent


<!-- Sent from Reviewable.io -->

2023-11-02 10:28 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java` line 158 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDaDwp72jcTXU6rVJd:-NiEZy9HEL0PgFwea9iW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/AbstractStagePlanCreator.java#L158)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this can be null, thus set only if non-null
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java` line 92 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDa6Ay0K_1_Iv3aHFD:-NiE_-vf-JW0xcgl8_PC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add null handling it here
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 32 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDZTdJ0pDc7WZCLCfs:-NiEZlyR4FF2w3ki5r07:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is not returning timeoutObtainment but instead its timeout
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 33 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDXlH02SnJgqdVYQaP:-NiEZnN_4_3_5HT5GWAp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to notApplyMaxTimeout
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 53 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDZlKqCNlnqi-PrDVV:-NiEZr3W-KhWZg5icWYU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be maxTimeout variables
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 59 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiD_0xU77f7hA2NQrlX:-NiEZvwG08MhRkTx_0K2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

its not string, thus rename it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 10:31 UTC, shivamnegi94 commented
@sahilhindwani-harness you are right here, as we can not compare expression.
`Can we test what happens if timeout is defined as an expression and it is greater than the max timeout?`

2023-11-02 10:42 UTC, shivamnegi94 commented
trigger uts

2023-11-02 10:44 UTC, archit-harness requested changes
> Reviewed 3 of 6 files at r15, 1 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java` line 81 at r15](https://reviewable.io/reviews/harness/harness-core/54218#-NiEcEBx-KAMCRIvu2iB:-NiEcEBx-KAMCRIvu2iC:bfe6hz7) ([raw file](https://github.com/harness/harness-core/blob/89e781562f7bddff025d470234ecf92e808741a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java#L81)):*
> ```Java
> 
>   @Builder(builderMethodName = "newBuilder")
>   public PipelineSetupStepParameters(String childNodeID, String name, String identifier, FlowControlConfig flowControl,
> ```

why we are adding this?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/cf/pipeline/FeatureFlagStagePlanCreator.java` line 94 at r15](https://reviewable.io/reviews/harness/harness-core/54218#-NiEcN4x0x0L2fjL6Wgs:-NiEcN4x0x0L2fjL6Wgt:b15h964) ([raw file](https://github.com/harness/harness-core/blob/89e781562f7bddff025d470234ecf92e808741a7/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/cf/pipeline/FeatureFlagStagePlanCreator.java#L94)):*
> ```Java
>         SdkTimeoutObtainmentUtils.getTimeout(config.getTimeout(), ctx.getTimeoutDuration(MAX_STAGE_TIMEOUT.getName()),
>             ctx.getFeatureFlagValue(FeatureName.CDS_DISABLE_TIMEOUT_CONFIG.toString()));
>     planNodeBuilder = SdkTimeoutObtainmentUtils.setStageTimeoutObtainment(timeoutParameterField, planNodeBuilder);
> ```

what if timeoutParameterField is null or blank?, can we rename this field as well?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java` line 92 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDa6Ay0K_1_Iv3aHFD:-NiEcXtY14AguOMSlBj8:b-e10jn6) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java#L92)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

timeout.getValue() will give error if null isnt?
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 67 at r13](https://reviewable.io/reviews/harness/harness-core/54218#-NiEc9Xu1niNaVK9JL1c:-NiEc9Xu1niNaVK9JL1d:bgzbun7) ([raw file](https://github.com/harness/harness-core/blob/02c4ce26269ad2e99dd28c0a51f8f7b6c1870646/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L67)):*
> ```Java
>   }
> 
>   public PlanNodeBuilder setStageTimeoutObtainment(ParameterField<Timeout> timeout, PlanNodeBuilder planNodeBuilder) {
> ```

why we are removing this?
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 32 at r16](https://reviewable.io/reviews/harness/harness-core/54218#-NiEbo_I2naf8JQjT3sF:-NiEbo_I2naf8JQjT3sG:bfj4qpx) ([raw file](https://github.com/harness/harness-core/blob/2165dc8f5dae63e7e37b5668aa690014bd6297f4/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L32)):*
> ```Java
>     if (notApplyMaxTimeout) {
>       if (ParameterField.isBlank(timeout)) {
>         return timeout;
> ```

can we return null?
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 59 at r16](https://reviewable.io/reviews/harness/harness-core/54218#-NiEbvFxCD7zRhvQrVMA:-NiEbvFxCD7zRhvQrVMB:b-wq9vku) ([raw file](https://github.com/harness/harness-core/blob/2165dc8f5dae63e7e37b5668aa690014bd6297f4/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L59)):*
> ```Java
>   private ParameterField<Timeout> getMinTimeoutValue(ParameterField<Timeout> givenTimeout, String maxTimeout) {
>     Timeout maxTimeoutValue = Timeout.fromString(maxTimeout);
>     if (null != maxTimeoutValue
> ```

can we check null check for givenTImeout as well for sake for keep consistent


<!-- Sent from Reviewable.io -->

2023-11-02 10:50 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java` line 81 at r15](https://reviewable.io/reviews/harness/harness-core/54218#-NiEcEBx-KAMCRIvu2iB:-NiEdL184qxjuH0MMme8:b-bk9zlj) ([raw file](https://github.com/harness/harness-core/blob/89e781562f7bddff025d470234ecf92e808741a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are adding this?
</blockquote></details>

We are adding timeout only if it is not Null
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/cf/pipeline/FeatureFlagStagePlanCreator.java` line 94 at r15](https://reviewable.io/reviews/harness/harness-core/54218#-NiEcN4x0x0L2fjL6Wgs:-NiEdefP34N17PkA3gAt:bxptye2) ([raw file](https://github.com/harness/harness-core/blob/89e781562f7bddff025d470234ecf92e808741a7/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/cf/pipeline/FeatureFlagStagePlanCreator.java#L94)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what if timeoutParameterField is null or blank?, can we rename this field as well?
</blockquote></details>

setStageTimeoutObtainment already verifying null or blank.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 67 at r13](https://reviewable.io/reviews/harness/harness-core/54218#-NiEc9Xu1niNaVK9JL1c:-NiEdHd06o8SD9r8pU4l:bc7qmmf) ([raw file](https://github.com/harness/harness-core/blob/02c4ce26269ad2e99dd28c0a51f8f7b6c1870646/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are removing this?
</blockquote></details>

PlanNode is not accessible here
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 32 at r16](https://reviewable.io/reviews/harness/harness-core/54218#-NiEbo_I2naf8JQjT3sF:-NiEe0O297uk2-amqosM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2165dc8f5dae63e7e37b5668aa690014bd6297f4/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we return null?
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java` line 59 at r16](https://reviewable.io/reviews/harness/harness-core/54218#-NiEbvFxCD7zRhvQrVMA:-NiEdAgG2KTeFZnOHJcu:b7qubyy) ([raw file](https://github.com/harness/harness-core/blob/2165dc8f5dae63e7e37b5668aa690014bd6297f4/884-pms-commons/src/main/java/io/harness/pms/utils/SdkTimeoutObtainmentUtils.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we check null check for givenTImeout as well for sake for keep consistent
</blockquote></details>

But we are already checking at line number 43
if (ParameterField.isBlank(timeout)) {  
  return ParameterField.createValueField(Timeout.fromString(maxTimeout));  
}


<!-- Sent from Reviewable.io -->

2023-11-02 11:36 UTC, archit-harness requested changes
> Reviewed 2 of 5 files at r16, 2 of 2 files at r17, 1 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java` line 81 at r15](https://reviewable.io/reviews/harness/harness-core/54218#-NiEcEBx-KAMCRIvu2iB:-NiEo8DA4SLDWPjBobGh:b-edwh03) ([raw file](https://github.com/harness/harness-core/blob/89e781562f7bddff025d470234ecf92e808741a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java#L81)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

We are adding timeout only if it is not Null
</blockquote></details>

not needed as discussed offline


<!-- Sent from Reviewable.io -->

2023-11-02 16:53 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java` line 81 at r15](https://reviewable.io/reviews/harness/harness-core/54218#-NiEcEBx-KAMCRIvu2iB:-NiFx3G19IsecpvcHKtW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/89e781562f7bddff025d470234ecf92e808741a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStepParameters.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

not needed as discussed offline
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java` line 92 at r14](https://reviewable.io/reviews/harness/harness-core/54218#-NiDa6Ay0K_1_Iv3aHFD:-NiFx3r31zm32P5wg81j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381f710b24aa74487b6fa375d272d7e4861b53b0/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/NGPipelinePlanCreator.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

timeout.getValue() will give error if null isnt?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-03 04:26 UTC, shivamnegi94 commented
trigger uts

2023-11-03 04:32 UTC, archit-harness submitted a review, later dismissed
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 34 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-11-03 04:38 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 14 files at r5, 6 of 14 files at r6, 6 of 7 files at r7, 1 of 3 files at r8, 5 of 9 files at r10, 1 of 2 files at r11, 2 of 2 files at r12, 2 of 9 files at r13, 2 of 5 files at r14, 1 of 6 files at r15, 2 of 5 files at r16, 2 of 2 files at r17, 1 of 2 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-11-03 05:10 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 14 files at r5, 6 of 14 files at r6, 6 of 7 files at r7, 1 of 3 files at r8, 5 of 9 files at r10, 1 of 2 files at r11, 2 of 2 files at r12, 2 of 9 files at r13, 2 of 5 files at r14, 1 of 6 files at r15, 2 of 5 files at r16, 2 of 2 files at r17, 1 of 2 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-11-03 07:09 UTC, shivamnegi94 commented
trigger ut2

2023-11-03 07:54 UTC, shivamnegi94 commented
trigger uts

2023-11-03 10:11 UTC, shivamnegi94 commented
trigger ut1

2023-11-04 07:39 UTC, shivamnegi94 commented
trigger uts

2023-11-04 08:04 UTC, shivamnegi94 commented
trigger ut6, ut9

2023-11-04 08:50 UTC, shivamnegi94 commented
trigger uts

2023-11-04 16:35 UTC, shivamnegi94 commented
trigger uts

2023-11-05 02:24 UTC, shivamnegi94 commented
trigger ut1, ut4, ut8

2023-11-05 16:43 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 2 files at r20, 2 of 3 files at r21, 4 of 5 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 8 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-11-06 04:37 UTC, shivamnegi94 commented
trigger uts

2023-11-06 05:04 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 8 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-11-06 06:16 UTC, shivamnegi94 commented
trigger uts

2023-11-06 06:21 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 2 files at r20, 2 of 3 files at r21, 4 of 5 files at r22, 1 of 1 files at r23, 4 of 4 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-11-06 07:18 UTC, shivamnegi94 commented
trigger ut5, ut6, ut7, ut8, ut9

2023-11-06 07:20 UTC, archit-harness approved these changes
> Reviewed 4 of 4 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54218)* status: Waiting on team(s): sto. 



<!-- Sent from Reviewable.io -->

2023-11-06 09:47 UTC, shivamnegi94 commented
trigger ut5

2023-11-06 09:48 UTC, shivamnegi94 commented
trigger review

2023-11-06 12:02 UTC, merged