[feat]: [PL-42024]: add background migration job for parentId in Projects
harness/harness-core pull request #54221
Opened 2023-10-17 06:28 UTC by pbarapatre10

## Describe your changes
With https://github.com/harness/harness-core/pull/54047 the one-time migration job failed to populate some projects with `parentId`. To overcome that we are introducing a background job which would check if for an Entity the parentId completed is TRUE or FALSE. If its FALSE, the parentId will be tried to populated in regular intervals of 12 hours.

Testing done:
- Verified for Project entity and missing document with parentId are getting populated correctly

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-17 10:15 UTC, ankit-harness requested changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 917 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx4vgYBOscNYeRFGyD:-Ngx4vgYBOscNYeRFGyE:bhkoww8) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L917)):*
> ```Java
>     // Do not remove as it's used for MaintenanceController for shutdown mode
>     environment.lifecycle().manage(injector.getInstance(MaintenanceController.class));
>     environment.lifecycle().manage(injector.getInstance(FixMissingParentIdForProjectJob.class));
> ```

Should we call this AddUniqueIdAndParentIdToEntitiesJob
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx56sw8x14oqkNSGYQ:-Ngx56sw8x14oqkNSGYR:b-5axsp7) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java#L41)):*
> ```Java
> @Document("uniqueIdParentIdOnEntities")
> @TypeAlias("uniqueIdParentIdOnEntities")
> public class UniqueIdParentIdOnEntitiesStatus implements PersistentEntity {
> ```

1. Would teams have to duplicate this class in their services as this entity would be stored only in NG Manager DB?
2. Should we rename this class to AddUniqueIdParentIdMigrationStatus
3. Is ng-project-n-orgs right place for this class? This class doesn't seem specific to Orgs/Projects
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx6NV1EFfSKcBRy_uN:-Ngx6NV1EFfSKcBRy_uO:bb2asaw) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java#L41)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class FixMissingParentIdForProjectService implements Runnable {
> ```

Shouldn't this be AddUniqueIdAndParentIdToEntitiesTask


<!-- Sent from Reviewable.io -->

2023-10-17 10:16 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx7fkl6_EswTuqgW_F:-Ngx7fkl6_EswTuqgW_G:b-izaj9l) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java#L138)):*
> ```Java
>       foundEntity.setIsParentIdCompleted(Boolean.TRUE);
>       mongoTemplate.save(foundEntity);
>     } else {
> ```

Didn't understand else part


<!-- Sent from Reviewable.io -->

2023-10-18 09:44 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx56sw8x14oqkNSGYQ:-Nh19W4GBoRl0GsoLVq6:b-ne4gtz) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java#L41)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

1. Would teams have to duplicate this class in their services as this entity would be stored only in NG Manager DB?
2. Should we rename this class to AddUniqueIdParentIdMigrationStatus
3. Is ng-project-n-orgs right place for this class? This class doesn't seem specific to Orgs/Projects
</blockquote></details>

1) Yes, independent microservices will have to duplicate this class, so as to store in their respective DB. Else we can expose a separate API to retrieve the info from NG-manager for the db document but that would un-necessary complicate thing, as in if we choose to do that we should also introduce a moduleName field here in the entity model, thanks

2) & 3) Done!


<!-- Sent from Reviewable.io -->

2023-10-18 09:44 UTC, pbarapatre10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 917 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx4vgYBOscNYeRFGyD:-Nh19JQc2UsiWbJWuNVx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L917)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we call this AddUniqueIdAndParentIdToEntitiesJob
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx6NV1EFfSKcBRy_uN:-Nh19OM--HAi3S5DWSwT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java#L41)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this be AddUniqueIdAndParentIdToEntitiesTask
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx7fkl6_EswTuqgW_F:-Nh19PYp80m8vN5kY9IF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectService.java#L138)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Didn't understand else part
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 15:39 UTC, ankit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 917 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx4vgYBOscNYeRFGyD:-Nh2PpvQ-ZOlZCYJovWD:b-wzjowz) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L917)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't seem to be done
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectJob.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/54221#-Nh2Qzxu1MeYvi5G3ZCu:-Nh2Qzxu1MeYvi5G3ZCv:b-92o0hm) ([raw file](https://github.com/harness/harness-core/blob/8d7e40998796d988510e1a43df21795b7ed0e06d/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectJob.java#L24)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class FixMissingParentIdForProjectJob implements Managed {
> ```

Should this job be in ng-manager as this is common to all entities
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx56sw8x14oqkNSGYQ:-Nh2Qovz4pASD2xDyhBo:b-4iypmm) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java#L41)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

1) Yes, independent microservices will have to duplicate this class, so as to store in their respective DB. Else we can expose a separate API to retrieve the info from NG-manager for the db document but that would un-necessary complicate thing, as in if we choose to do that we should also introduce a moduleName field here in the entity model, thanks

2) & 3) Done!
</blockquote></details>

If teams would have to duplicate, shouldn't this class be in ng-manager itself and not in common?
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdAndParentIdToEntitiesTask.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/54221#-Nh2QCYd8NNu62yqAVz2:-Nh2QCYd8NNu62yqAVz3:b9iypsn) ([raw file](https://github.com/harness/harness-core/blob/8d7e40998796d988510e1a43df21795b7ed0e06d/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdAndParentIdToEntitiesTask.java#L129)):*
> ```Java
>           }
>         } catch (Exception exc) {
>           log.error(format("%s job failed to iterate over all projects", PROJECT_PARENTID_MIGRATION_LOG), exc);
> ```

We are using project word in all the logs. But this class isn't just about project. Isn't it?
___
*[`959-common-entities/src/main/java/io/harness/ng/entities/UniqueIdParentIdMigrationStatus.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/54221#-Nh2QRwL8jg2mGHIWne2:-Nh2QRwL8jg2mGHIWne3:bfyjp7i) ([raw file](https://github.com/harness/harness-core/blob/8d7e40998796d988510e1a43df21795b7ed0e06d/959-common-entities/src/main/java/io/harness/ng/entities/UniqueIdParentIdMigrationStatus.java#L56)):*
> ```Java
>   @LastModifiedDate Long lastUpdatedAt;
>   @NotEmpty @EntityName String entityName;
>   Boolean uniqueIdCompleted;
> ```

uniqueIdMigrationCompleted
parentIdMigrationCompleted


<!-- Sent from Reviewable.io -->

2023-10-20 02:25 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx56sw8x14oqkNSGYQ:-Nh9tgOS7OmecHyLLit_:b-qgej98) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/UniqueIdParentIdOnEntitiesStatus.java#L41)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

If teams would have to duplicate, shouldn't this class be in ng-manager itself and not in common?
</blockquote></details>

Pt. 1) Have added a Base class, which teams can extend from and use along, thanks


<!-- Sent from Reviewable.io -->

2023-10-20 02:28 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectJob.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/54221#-Nh2Qzxu1MeYvi5G3ZCu:-Nh9ttjV9izfOm2GT3Ef:bscr21l) ([raw file](https://github.com/harness/harness-core/blob/8d7e40998796d988510e1a43df21795b7ed0e06d/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectJob.java#L24)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this job be in ng-manager as this is common to all entities
</blockquote></details>

It's only for Org, Project entities


<!-- Sent from Reviewable.io -->

2023-10-20 02:28 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdAndParentIdToEntitiesTask.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/54221#-Nh2QCYd8NNu62yqAVz2:-Nh9uRSz6jtYYGFCMgvt:bmt9imx) ([raw file](https://github.com/harness/harness-core/blob/8d7e40998796d988510e1a43df21795b7ed0e06d/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdAndParentIdToEntitiesTask.java#L129)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We are using project word in all the logs. But this class isn't just about project. Isn't it?
</blockquote></details>

Updated logs


<!-- Sent from Reviewable.io -->

2023-10-20 06:41 UTC, ankit-harness requested changes
> Reviewed 1 of 7 files at r2, 4 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 939 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAiF6nA4tgiIx0tgFi:-NhAiF6nA4tgiIx0tgFj:b-5n6a06) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L939)):*
> ```Java
>   }
> 
>   private void registerResources(NextGenConfiguration appConfig, Environment environment, Injector injector) {
> ```

Check why this is showing as change
___
*[`950-ng-project-n-orgs/BUILD.bazel` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAkyFU2Kuy4D30pW_3:-NhAkyFU2Kuy4D30pW_4:b-gphp3q) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/BUILD.bazel#L25)):*
> ```Starlark
>         "//120-ng-manager/modules/favorites/src/main/java/io/harness/favorites/services:module",
>         "//958-migration-sdk:module",
>         "//959-common-entities/src/main/java/io/harness/ng/entities:module",
> ```

This should get removed once we move migrations jobs/tasks to 120-ng-manager
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAjjbN44MTCuEPqeki:-NhAjjbN44MTCuEPqekj:b-i3g46n) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L47)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class AddUniqueIdParentIdToScopeEntitiesTask implements Runnable {
> ```

This should be moved to NG Manager
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAla2HCa7YDSHi1Frd:-NhAla2HCa7YDSHi1Fre:bcpg0v5) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L50)):*
> ```Java
>   private final MongoTemplate mongoTemplate;
>   private final PersistentLocker persistentLocker;
>   private static final String LOCK_NAME_PREFIX = "NGPeriodicMigrationTaskLock_";
> ```

This should be just 1 name
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAk49eABkNwdxoWz6V:-NhAk49eABkNwdxoWz6W:bgcyvjj) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L51)):*
> ```Java
>   private final PersistentLocker persistentLocker;
>   private static final String LOCK_NAME_PREFIX = "NGPeriodicMigrationTaskLock_";
>   private static final String SCOPE_ENTITIES_MIGRATION_LOG = "[NGAddUniqueIdAndParentIdToScopeEntitiesTask]:";
> ```

[NGManagerAddUniqueIdAndParentIdToScopeEntitiesTask]:
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAjy0A2BSzNZL-ttRj:-NhAjy0A2BSzNZL-ttRk:b-awjsqy) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L53)):*
> ```Java
>   private static final String SCOPE_ENTITIES_MIGRATION_LOG = "[NGAddUniqueIdAndParentIdToScopeEntitiesTask]:";
>   private static final int BATCH_SIZE = 500;
>   private final Set<Class<? extends UniqueIdAware>> entitiesSet;
> ```

Make it static
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAn-t100XqQ3TGqq4a:-NhAn-t100XqQ3TGqq4b:bhxvyeg) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L171)):*
> ```Java
>   }
> 
>   private void performProjectParentIdMigrationTask(ScopeEntityUniqueIdParentIdMigrationStatus foundEntity) {
> ```

Convert it into generic migration
___
*[`959-common-entities/src/main/java/io/harness/ng/entities/BaseUniqueIdParentIdMigrationStatus.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAmQbC279rKz-fvhWJ:-NhAmQbC279rKz-fvhWK:b-xp52lc) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/959-common-entities/src/main/java/io/harness/ng/entities/BaseUniqueIdParentIdMigrationStatus.java#L25)):*
> ```Java
> @NoArgsConstructor
> @FieldNameConstants(innerTypeName = "BaseUniqueIdParentIdMigrationStatusKeys")
> public abstract class BaseUniqueIdParentIdMigrationStatus {
> ```

Lets not have separate class in 959-common-entities. Have it in120-ng-manager
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAikHz8kWdKaHnOaAV:-NhAikHz8kWdKaHnOaAW:b-drj6xi) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java#L40)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> @StoreIn(DbAliases.NG_MANAGER)
> @Entity(value = "uniqueIdParentIdMigrations", noClassnameStored = true)
> ```

uniqueIdParentIdMigrationStatus
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAioGE3QmnbBjwAw7B:-NhAioGE3QmnbBjwAw7C:bewr3ad) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java#L42)):*
> ```Java
> @Entity(value = "uniqueIdParentIdMigrations", noClassnameStored = true)
> @Document("uniqueIdParentIdMigrations")
> @TypeAlias("ScopeUniqueIdParentIdMigrations")
> ```

scopeUniqueIdParentIdMigrations
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAjWfHBTj2bU3AQuKa:-NhAjWfHBTj2bU3AQuKb:b-9h5c2s) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java#L43)):*
> ```Java
> @Document("uniqueIdParentIdMigrations")
> @TypeAlias("ScopeUniqueIdParentIdMigrations")
> public class ScopeEntityUniqueIdParentIdMigrationStatus
> ```

NGManagerUniqueIdParentIdMigrationStatus

Move this class to NG Manager Only
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAl9PzBItrGc0p5uKG:-NhAl9PzBItrGc0p5uKH:b-c5cxm2) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7 [...]

2023-10-20 09:16 UTC, pbarapatre10 commented
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectJob.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/54221#-Nh2Qzxu1MeYvi5G3ZCu:-NhBMf6pEV69G96DfcTD:b6dz0l4) ([raw file](https://github.com/harness/harness-core/blob/8d7e40998796d988510e1a43df21795b7ed0e06d/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/FixMissingParentIdForProjectJob.java#L24)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

It's only for Org, Project entities
</blockquote></details>

Made it more generic, thanks


<!-- Sent from Reviewable.io -->

2023-10-20 09:16 UTC, pbarapatre10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 11 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 917 at r1](https://reviewable.io/reviews/harness/harness-core/54221#-Ngx4vgYBOscNYeRFGyD:-Nh7KEBf2ybiV0tCE6s5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8b3958bc93d64c277d551ac5f2e5b47f3ddb225/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L917)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Doesn't seem to be done
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 939 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAiF6nA4tgiIx0tgFi:-NhBA8yU8JgtqBdYJub-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L939)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Check why this is showing as change
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/BUILD.bazel` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAkyFU2Kuy4D30pW_3:-NhBA9rZ5MY38QUtzK3c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/BUILD.bazel#L25)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should get removed once we move migrations jobs/tasks to 120-ng-manager
</blockquote></details>

Done.
___
*[`959-common-entities/src/main/java/io/harness/ng/entities/BaseUniqueIdParentIdMigrationStatus.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAmQbC279rKz-fvhWJ:-NhBA62C1qBmSsl9-cVX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/959-common-entities/src/main/java/io/harness/ng/entities/BaseUniqueIdParentIdMigrationStatus.java#L25)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets not have separate class in 959-common-entities. Have it in120-ng-manager
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAikHz8kWdKaHnOaAV:-NhBABrxC0KROiA_YQhn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/ScopeEntityUniqueIdParentIdMigrationStatus.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

uniqueIdParentIdMigrationStatus
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAk49eABkNwdxoWz6V:-NhBA3ibA-PotVCRTqMV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L51)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

[NGManagerAddUniqueIdAndParentIdToScopeEntitiesTask]:
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAjy0A2BSzNZL-ttRj:-NhBA3Gi-MNcQ4VgE01K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L53)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Make it static
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 171 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAn-t100XqQ3TGqq4a:-NhBA4ta11ynQ3K7-1_p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L171)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Convert it into generic migration
</blockquote></details>

Done.
___
*[`959-common-entities/src/main/java/io/harness/ng/entities/UniqueIdParentIdMigrationStatus.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/54221#-Nh2QRwL8jg2mGHIWne2:-Nh7WlLL-Z04Sfn9VsoF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d7e40998796d988510e1a43df21795b7ed0e06d/959-common-entities/src/main/java/io/harness/ng/entities/UniqueIdParentIdMigrationStatus.java#L56)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

uniqueIdMigrationCompleted
parentIdMigrationCompleted
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-20 09:16 UTC, pbarapatre10 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 11 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAlEbA6UydbJ35tacb:-NhBMlAvBPJf1VOH0hfi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java#L28)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Change this name
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAlKEg6wrIbSVv3nkx:-NhBMm-L8l4Rxni7Vef1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java#L31)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This name should change
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAlFXhEfzjrdJhIsp4:-NhBMm_k1_ZszhpVNIn3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java#L34)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Change this thread name
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAlNyS5CUghIvUYtsS:-NhBMnDS4i3xZze-fHHT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Change name
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAlPzrDgBdJYQXS-H3:-NhBMnVe-Rla53ohUA1i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesJob.java#L45)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAjjbN44MTCuEPqeki:-NhBMoHT4DldbTHIEqSh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L47)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should be moved to NG Manager
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java` line 50 at r3](https://reviewable.io/reviews/harness/harness-core/54221#-NhAla2HCa7YDSHi1Frd:-NhBMo_fDW4AByyQ80XV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2fb1a03663a3d2842219ce7b07ec09617f0ab7fc/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/AddUniqueIdParentIdToScopeEntitiesTask.java#L50)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should be just 1 name
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-20 09:29 UTC, pbarapatre10 commented
trigger uts

2023-10-20 12:29 UTC, pbarapatre10 commented
trigger uts

2023-10-20 13:02 UTC, pbarapatre10 commented
trigger messagecheck

2023-10-22 03:16 UTC, ankit-harness approved these changes
> Reviewed 9 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54221)* status: 12 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto,del-team. 



<!-- Sent from Reviewable.io -->

2023-10-22 03:17 UTC, merged