[fix]: [SRM-15677]: mark analysisStateMachine to a different state whose slo has bee deleted.
harness/harness-core pull request #54240
Opened 2023-10-17 11:00 UTC by n00bitax

…ose slo have been deleted.

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-17 14:08 UTC, n00bitax commented
trigger uts

2023-10-18 21:09 UTC, n00bitax commented
trigger uts

2023-10-18 21:51 UTC, n00bitax commented
trigger uts

2023-10-18 22:01 UTC, n00bitax commented
trigger messagecheck

2023-10-18 22:06 UTC, n00bitax commented
trigger ut6

2023-10-18 22:33 UTC, n00bitax commented
trigger ut7

2023-10-18 22:40 UTC, n00bitax commented
trigger ut6,ut7

2023-10-19 05:27 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java
> +        log.info("The sloId {} has already been deleted, marking current analysisState to be cleaned up : {}", sloId,
composite slo with id*

2023-10-19 05:27 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java
> +            System.out.println("Status |||" + stateMachineStatus);
remove

2023-10-19 05:27 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImplTest.java
> +  public void testExecuteAfterSLODeletion() {
AfterCompositeSLODeletion* would be better to tell what test is doing

2023-10-19 05:27 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImplTest.java
> +    assertThat(orchestrator.getStatus().name()).isEqualTo(AnalysisStatus.TERMINATED.name());
can you also add validaton for state machine status

2023-10-19 05:27 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java
> +      sloId = verificationTaskService.getCompositeSLOId(verificationTaskId);
what if verificationTask is deleted and sloId is null?

2023-10-19 05:27 UTC, Varsha-lalwani requested changes
Please make the changes

2023-10-19 05:50 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java
> +      sloId = verificationTaskService.getCompositeSLOId(verificationTaskId);
in that case, also, we will not have the compositeServiceLevelObjective object also right, as we can only fetch it if all of the above are not null.

2023-10-19 07:06 UTC, n00bitax commented
trigger uts

2023-10-19 08:42 UTC, n00bitax commented
trigger uts

2023-10-19 09:02 UTC, Varsha-lalwani approved these changes

2023-10-19 09:02 UTC, merged