[fix]: [CDS-79529]: Fix trigger status not updating from pending state
harness/harness-core pull request #54289
Opened 2023-10-18 04:52 UTC by rathodmeetsatish

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-18 14:48 UTC, rathodmeetsatish commented
trigger uts

2023-10-18 21:23 UTC, vcalasansh commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +          if (responseDTO.getData().getIsExistingPollingDoc() && isNotEmpty(responseDTO.getData().getLastPolled())) {
Can we wrap this block inside another method? Something similar to what we are doing in `updateTriggerPollingStatus`, maybe create a new method in NGTriggerRepositoryCustom.

2023-10-19 12:37 UTC, rathodmeetsatish commented
trigger uts

2023-10-19 15:54 UTC, vcalasansh commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +      Criteria criteria = getTriggerEqualityCriteriaWithoutDbVersion(ngTriggerEntity, false);
Is it not possible to add this flow inside `updatePollingRegistrationStatus` method? Just so we keep things more organized and don't need to do 2 DB updates for the same trigger.

2023-10-20 00:12 UTC, rathodmeetsatish commented
trigger uts

2023-10-20 01:21 UTC, vcalasansh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54289#-:-Nh9f7xuAwKjFlpcYbYR:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-20 01:21 UTC, vcalasansh approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54289)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-20 04:58 UTC, rathodmeetsatish commented
trigger uts

2023-10-20 05:37 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java
>        if (((ArtifactPolledResponse) pollingDocument.getPolledResponse()).getAllPolledKeys() == null) {
Can we organize this code a little more. Many Ifs and else. 
May be add Switch for `pollingDocument.getPollingType()` and handle it independently?

2023-10-20 05:38 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java
>        } else {
We can also remove the else and` return new ArrayList<>(((ArtifactPolledResponse) pollingDocument.getPolledResponse()).getAllPolledKeys());` directly

2023-10-20 05:38 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java
>          return new ArrayList<>(((ManifestPolledResponse) pollingDocument.getPolledResponse()).getAllPolledKeys());
Same as above

2023-10-20 05:39 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java
>        if (((ArtifactPolledResponse) pollingDocument.getPolledResponse()).getAllPolledKeys() == null) {
cc: @vcalasansh

2023-10-20 05:47 UTC, sribalij commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +  public void updateTriggerStatus(
make this a private method

2023-10-20 05:49 UTC, sribalij commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +    if (responseDTO.getData().getIsExistingPollingDoc() && isNotEmpty(responseDTO.getData().getLastPolled())) {
Possible to avoid if else here as well?
Since there are only two states possible, can we have initialized value for responseDto and `StatusResult.PENDING`, and then pass Success or failure in `updatePollingRegistrationStatus` based on one if

2023-10-20 06:03 UTC, sribalij requested changes
Added few comments

2023-10-20 14:05 UTC, vcalasansh approved these changes
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54289)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-21 01:27 UTC, sribalij approved these changes

2023-10-21 01:27 UTC, sribalij commented
trigger uts

2023-10-21 01:27 UTC, sribalij commented
trigger review

2023-10-22 12:23 UTC, merged