fix: [CDS-81966]: Add oneoff condition on createType and useServiceNowTemplate field For serviceNow Create
harness/harness-core pull request #54300
Opened 2023-10-18 06:46 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-18 07:06 UTC, abhinavmittal-harness requested changes
Let's add a ut for this change

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54300#-:-Nh0aoJ39-1cmOZLCOjv:bhys7jq)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-18 15:23 UTC, vivekkarnatiharness commented
trigger uts

2023-10-19 07:26 UTC, abhinavmittal-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54300)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/54300#-Nh5ovPu1473KoWp-eeK:-Nh5ovPv7Z1MrWVWUJKE:b-fqz8zk) ([raw file](https://github.com/harness/harness-core/blob/ea238d66ba45f3a805e9718a9f5527c08100ad0c/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java#L52)):*
> ```Java
>     if (ParameterField.isNotNull(specParameters.getTicketType())
>         && !specParameters.getTicketType().getValue().equalsIgnoreCase(CHANGE_REQUEST)) {
>       if (specParameters.getCreateType() == ServiceNowCreateType.STANDARD) {
> ```

These if blocks can be merged


<!-- Sent from Reviewable.io -->

2023-10-19 07:27 UTC, abhinavmittal-harness submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54300)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 06:34 UTC, vivekkarnatiharness commented
trigger uts

2023-10-23 06:49 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java
> +    if (ParameterField.isNotNull(specParameters.getTicketType())
Are we getting resolved value for expressions here for ticket type

2023-10-25 06:16 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreator.java
> +    if (ParameterField.isNotNull(specParameters.getTicketType())
Have moved them createstep

2023-10-25 09:32 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java
> +      if (specParameters.getCreateType() == ServiceNowCreateType.STANDARD) {
nit: it can be added in parent if condition

2023-10-25 09:34 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreatorTest.java
> +  private ServiceNowCreateStepInfo getServiceNowCreateStepInfoWithCreateField(
is this being used ?

2023-10-25 10:00 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create/ServiceNowCreateStep.java
> +      if (specParameters.getCreateType() == ServiceNowCreateType.STANDARD) {
Ok, have refactored

2023-10-25 10:00 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreatorTest.java
> +  private ServiceNowCreateStepInfo getServiceNowCreateStepInfoWithCreateField(
Removed it

2023-10-25 16:19 UTC, naman-goenka approved these changes

2023-10-25 16:21 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54300)* status: 4 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-10-26 01:22 UTC, vivekkarnatiharness commented
trigger uts

2023-10-26 01:26 UTC, vivekkarnatiharness commented
trigger review

2023-10-26 01:28 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-10-26 01:30 UTC, merged