[fix]:[CDS-80150]:Bamboo failing at service step
harness/harness-core pull request #54315
Opened 2023-10-18 09:07 UTC by Rakshitharness

## Describe your changes
Now we are calling the get metadata for each artifactpath only not for each artifactpath and each build.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-18 09:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=54315) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=54315) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=54315) it.</sub>

2023-10-18 09:13 UTC, Rakshitharness commented
trigger messagecheck

2023-10-18 09:34 UTC, Rakshitharness commented
trigger uts

2023-10-18 12:24 UTC, rafaelmart1ns approved these changes

2023-10-18 13:03 UTC, naman-goenka commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandler.java
> +            attributesRequest.getPlanKey(), buildDetails.get(0).getNumber(), attributesRequest.getArtifactPaths());
is `buildDetails` non-empty always?

2023-10-19 04:58 UTC, Rakshitharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandler.java
> +            attributesRequest.getPlanKey(), buildDetails.get(0).getNumber(), attributesRequest.getArtifactPaths());
we check if builds are empty or not over here
checkIfEmptyBuilds(buildDetails);

2023-10-19 05:01 UTC, Abhishek-CDC commented on 930-delegate-tasks/src/test/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandlerTest.java
> +    when(
Please add UTs/cases for metadata check also. As we are calling a new method for it now.
There is no assertion to check that in these tests.

2023-10-19 05:04 UTC, Abhishek-CDC commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandler.java
> +        buildDetails.get(0).setArtifactDownloadMetadata(artifactFileMetadata);
Nit: Lets create a variable to store buildDetails.get(0) and we can perform operations on it and use in place of referring array every time

2023-10-19 05:05 UTC, Abhishek-CDC commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandler.java
> +            attributesRequest.getPlanKey(), buildDetails.get(0).getNumber(), attributesRequest.getArtifactPaths());
we are checking this in line 108 -> checkIfEmptyBuilds(buildDetails);

2023-10-19 05:06 UTC, Abhishek-CDC commented
Please add screenshot of scenarios tested

2023-10-19 07:33 UTC, abhinavmittal-harness reviewed
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54315)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-19 09:30 UTC, Rakshitharness commented
trigger uts

2023-10-19 09:30 UTC, Abhishek-CDC approved these changes

2023-10-20 09:05 UTC, naman-goenka requested changes
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54315)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandlerTest.java` line 209 at r2](https://reviewable.io/reviews/harness/harness-core/54315#-NhBK4je-uGVbPmIHxIh:-NhBK4je-uGVbPmIHxIi:b-977qky) ([raw file](https://github.com/harness/harness-core/blob/0b313c420e299d33fca8d8d7e1b49fdf612af7c7/930-delegate-tasks/src/test/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactTaskHandlerTest.java#L209)):*
> ```Java
>     assertThat(buildDetails.getArtifactPath()).isEqualTo("artifactPath");
>     assertThat(buildDetails.getNumber()).isEqualTo("45");
>     assertThat(buildDetails.getArtifactDownloadMetadata()).isEqualTo(Artifact_MetadataList);
> ```

Can you add test case for attributesRequest.getArtifactPaths() being empty and then new API call not being made


<!-- Sent from Reviewable.io -->

2023-10-20 09:08 UTC, naman-goenka requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54315)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/bamboo/BambooServiceImpl.java` line 562 at r2](https://reviewable.io/reviews/harness/harness-core/54315#-NhBKuNQ-w64z3dvRd5I:-NhBKuNQ-w64z3dvRd5J:bkvkti6) ([raw file](https://github.com/harness/harness-core/blob/0b313c420e299d33fca8d8d7e1b49fdf612af7c7/930-delegate-tasks/src/main/java/software/wings/helpers/ext/bamboo/BambooServiceImpl.java#L562)):*
> ```Java
> 
>   public List<ArtifactFileMetadata> getArtifactFileMetadataList(BambooConfig bambooConfig,
>       List<EncryptedDataDetail> encryptionDetails, String planKey, String buildNumber, List<String> artifactPathRegex) {
> ```

consider adding a notNull annottion/check on artifactPathRegex


<!-- Sent from Reviewable.io -->

2023-10-20 11:39 UTC, Rakshitharness commented
trigger uts

2023-10-20 13:55 UTC, Abhishek-CDC approved these changes

2023-10-20 13:56 UTC, rafaelmart1ns approved these changes

2023-10-23 09:03 UTC, naman-goenka approved these changes

2023-10-23 09:04 UTC, Rakshitharness commented
trigger review

2023-10-23 09:08 UTC, merged