[feat]: [CDS-81658]: Added Service Layer method for api-selection supports for Remote Env.
harness/harness-core pull request #54344
Opened 2023-10-18 17:11 UTC by senjucanon2

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-19 09:09 UTC, hingerabhinav requested changes

2023-10-19 09:09 UTC, hingerabhinav commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
> +  @Inject @Named("environment-gitx-executor") private ExecutorService executorService;
we have to create a separate managed executor for handling env like we have for service

2023-10-19 09:09 UTC, hingerabhinav commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
> +    if (isEmpty(environmentRefBranchMap)) {
env branch map should be optional. we should rely on envRefs list to process the elements.

2023-10-19 09:09 UTC, hingerabhinav commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java
> +              Environment temp = environmentRepository.getRemoteEnvironmentWithYaml(env, loadFromCache, false);
we have to create input YAML within each thread since we need git details of the file fetched as well. check services impl once.

2023-10-20 10:27 UTC, hingerabhinav reviewed
> Reviewed 2 of 10 files at r1, 10 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 919 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBZQQXCrWdkLj-HgKH:-NhBZQQXCrWdkLj-HgKI:b-7jl27f) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L919)):*
> ```Java
>   }
> 
>   private void prepareBranchMapIfEnvGroupIsPresent(EnvironmentAndServiceOverridesMetadataInput environmentYamlMetadata,
> ```

same 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 932 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBZgGv-ewrtbErGc-l:-NhBZgGw0mpvjd7ZviP4:brc2v8s) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L932)):*
> ```Java
>           envRefs.add(env);
>           environmentRefBranchMap.put(env, gitEntityBasicInfo.getBranch());
>         }
> ```

env, branch map is for transient branches. we should not add branches here. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputSetYamlAndServiceOverridesMetadata.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhB_Pmq3PsRF0jtzRu4:-NhB_Pmq3PsRF0jtzRu5:b-3urwig) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputSetYamlAndServiceOverridesMetadata.java#L33)):*
> ```Java
>   // scope identifiers
>   String orgIdentifier;
>   String projectIdentifier;
> ```

nit: check with UI where they're used
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhB_jLQBWaaTE41r4K2:-NhB_jLQBWaaTE41r4K3:b2ni214) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L144)):*
> ```Java
>       "Environment [%s] under Organization [%s] in Account [%s] already exists";
>   private static final String DUP_KEY_EXP_FORMAT_STRING_FOR_ACCOUNT = "Environment [%s] in Account [%s] already exists";
>   private static final int REMOTE_SERVICE_BATCH_SIZE = 20;
> ```

env
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 934 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBaZ282txY8jqYxLyU:-NhBaZ282txY8jqYxLyV:b-81dib8) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L934)):*
> ```Java
>         new ArrayList<>();
>     List<Environment> environmentEntities =
>         getScopedServiceEntities(accountIdentifier, orgIdentifier, projectIdentifier, envRefs);
> ```

getScopedEnv
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1020 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBbLI8ERthiW7A-5p4:-NhBbLI8ERthiW7A-5p5:b-vyv1lp) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1020)):*
> ```Java
>           CompletableFuture<Void> future = CompletableFuture.runAsync(() -> {
>             try (GitXTransientBranchGuard ignore = new GitXTransientBranchGuard(branchInfo)) {
>               Environment temp = environmentRepository.getRemoteEnvironmentWithYaml(env, loadFromCache, false);
> ```

entiyWithYaml
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1027 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBbVCK-5cKMzkZ0NIs:-NhBbVCK-5cKMzkZ0NIt:b-1eanjt) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1027)):*
> ```Java
>           batchFutures.add(future);
>         } else {
>           // For inline services, process YAML immediately
> ```

comment can be removed 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1044 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBbv7gBKoMzhhDlxxU:-NhBbv7gBKoMzhhDlxxV:bwcbqv7) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1044)):*
> ```Java
>   }
> 
>   private List<Environment> getScopedServiceEntities(
> ```

fetchesNonDeletedEnvironmentFromListOfRefs
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 294 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBc-Xm1Wiz25mqVrPX:-NhBc-Xm1Wiz25mqVrPY:b2ni214) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L294)):*
> ```Java
>     } catch (Exception e) {
>       log.error(
>           String.format("Unexpected error occurred while retrieving service YAML: [%s]", environment.getIdentifier()),
> ```

env


<!-- Sent from Reviewable.io -->

2023-10-22 05:59 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: 16 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 919 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBZQQXCrWdkLj-HgKH:-NhKwOIF8227Ut55Xls5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L919)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 932 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBZgGv-ewrtbErGc-l:-NhKwNkD74BL07_CureL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L932)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

env, branch map is for transient branches. we should not add branches here.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputSetYamlAndServiceOverridesMetadata.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhB_Pmq3PsRF0jtzRu4:-NhKxnnb3AoejA4U9VPB:b-j92mge) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentInputSetYamlAndServiceOverridesMetadata.java#L33)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

nit: check with UI where they're used
</blockquote></details>

Pending
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhB_jLQBWaaTE41r4K2:-NhKwcAg3Nu_v0LyCaNc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L144)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

env
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 934 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBaZ282txY8jqYxLyU:-NhKwls91sZDb8RqfI6g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L934)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

getScopedEnv
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1020 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBbLI8ERthiW7A-5p4:-NhKx2PKCkJSLVR835ZY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1020)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

entiyWithYaml
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1027 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBbVCK-5cKMzkZ0NIs:-NhKxBtg8_dMLWWkWcQ8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1027)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

comment can be removed
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1044 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBbv7gBKoMzhhDlxxU:-NhKxcgjDvGf4n9yKPPf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1044)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

fetchesNonDeletedEnvironmentFromListOfRefs
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 294 at r2](https://reviewable.io/reviews/harness/harness-core/54344#-NhBc-Xm1Wiz25mqVrPX:-NhKxm9w96f-LVIHat_u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/422f5adfffc52c2e286c8f403287db90986cb00e/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L294)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

env
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-23 05:10 UTC, senjucanon2 commented
trigger uts

2023-10-23 05:53 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java` line 302 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ4t210TGliH29HM65:-NhQ4t210TGliH29HM66:b-m7a98x) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java#L302)):*
> ```Java
>   @JsonProperty("useQueueServiceForGitXWebhook") private boolean useQueueServiceForGitXWebhook;
>   @JsonProperty("streamPerServiceConfiguration") private boolean streamPerServiceConfiguration;
>   @JsonProperty("serviceGitXThreadConfig") @ConfigSecret private ServiceGitXThreadConfiguration serviceGitXThreadConfig;
> ```

This should not be a configSecret. Both ServiceGitXThreadConfiguration and EnvironmentGitXThreadConfiguration


<!-- Sent from Reviewable.io -->

2023-10-23 06:01 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ6wYd0slRDp0HpHco:-NhQ6wYd0slRDp0HpHcp:bbmf1tm) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java#L19)):*
> ```Java
> import lombok.experimental.FieldDefaults;
> 
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = false, components = {HarnessModuleComponent.CDS_PIPELINE})
> ```

module component should be CDS_SERVICE_ENVIRONMENT


<!-- Sent from Reviewable.io -->

2023-10-23 06:02 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ70oK8jctwQkYD4Ky:-NhQ70oK8jctwQkYD4Kz:b-uwkxgk) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java#L22)):*
> ```Java
> @Value
> @Builder
> @FieldDefaults(makeFinal = false)
> ```

should be final right ?


<!-- Sent from Reviewable.io -->

2023-10-23 06:04 UTC, yogesh-chauhan commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 909 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ7VrZ6-eHVQ6y6MXh:-NhQ7VrZ6-eHVQ6y6MXi:b80i9xv) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L909)):*
> ```Java
>     boolean isServiceOverrideV2Enabled =
>         featureFlagHelperService.isEnabled(accountId, FeatureName.CDS_SERVICE_OVERRIDES_2_0);
>     EnvironmentInputSetYamlAndServiceOverridesMetadataDTO environmentInputsetYamlandServiceOverridesMetadataDTO =
> ```

within the context of this method, this variable name need not be so verbose. You can just call it responseDTO


<!-- Sent from Reviewable.io -->

2023-10-23 06:06 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 659 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ81t-1hEdBTfOomab:-NhQ81t-1hEdBTfOomac:b-vo79nb) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L659)):*
> ```Java
>     } else {
>       String errorMessage = "Environment identifier cannot be null";
>       throw new NotFoundException(errorMessage);
> ```

this should also be invalid request exception right ?
also, do we need to declare error message separately ? 


<!-- Sent from Reviewable.io -->

2023-10-23 06:08 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 297 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ8OaVCuqFNRSjmMgz:-NhQ8OaVCuqFNRSjmMh-:b-v0eezo) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L297)):*
> ```Java
>           e);
>       throw new InternalServerErrorException(String.format(
>           "Unexpected error occurred while retrieving environment YAML: [%s]", environment.getIdentifier()));
> ```

retrieving environment YAML: [%s] -> yaml for environment: [%s]


<!-- Sent from Reviewable.io -->

2023-10-23 06:08 UTC, yogesh-chauhan reviewed
> Reviewed 9 of 14 files at r2, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: 12 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 08:55 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 1 of 14 files at r2, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: 13 file(s) to review. 1 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-23 09:00 UTC, senjucanon2 commented
trigger uts

2023-10-23 10:01 UTC, hingerabhinav requested changes
> Reviewed 4 of 14 files at r2, 2 of 5 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 912 at r5](https://reviewable.io/reviews/harness/harness-core/54344#-NhQy2As1ErmEm2yF5ti:-NhQy2As1ErmEm2yF5tj:b-ozmohp) ([raw file](https://github.com/harness/harness-core/blob/fe5e31a51366602cb643ae588da71680e54b6ce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L912)):*
> ```Java
>     } catch (CompletionException ex) {
>       // internal method always wraps the CompletionException, so we will have a cause
>       log.error(String.format("Error while getting environments: %s", envRefs), ex);
> ```

lets put 'while getting environment inputs' in error and exceptions here 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 957 at r5](https://reviewable.io/reviews/harness/harness-core/54344#-NhQyKxu66dGgpH8ophm:-NhQyKxu66dGgpH8ophn:b-zafpbx) ([raw file](https://github.com/harness/harness-core/blob/fe5e31a51366602cb643ae588da71680e54b6ce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L957)):*
> ```Java
>                 IdentifierRefHelper.getIdentifierRef(serviceRef, accountIdentifier, orgIdentifier, projectIdentifier);
> 
>             Optional<ServiceEntity> serviceEntity = serviceEntityService.getService(
> ```

we should not get service here since there are chances service is present in some non default branch. This API would error out in that case. Let's get metadata here since we confirmed with UI YAML is not used. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1000 at r5](https://reviewable.io/reviews/harness/harness-core/54344#-NhQwCkE4TUFImAPWtNa:-NhQwCkE4TUFImAPWtNb:b-tolwq7) ([raw file](https://github.com/harness/harness-core/blob/fe5e31a51366602cb643ae588da71680e54b6ce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1000)):*
> ```Java
>   }
> 
>   private Map<String, Environment> getMapOfEntitiesInBatch(
> ```

this method should be indicative that its populating YAML for entities as well. Maybe getEnvironmentMapWithYAML. 


<!-- Sent from Reviewable.io -->

2023-10-23 11:41 UTC, senjucanon2 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java` line 302 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ4t210TGliH29HM65:-NhQSx1R7VfFwgEUXPn9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java#L302)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This should not be a configSecret. Both ServiceGitXThreadConfiguration and EnvironmentGitXThreadConfiguration
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ6wYd0slRDp0HpHco:-NhQW2DV9rFNsdI2aVB8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java#L19)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

module component should be CDS_SERVICE_ENVIRONMENT
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ70oK8jctwQkYD4Ky:-NhQW2iS-dnJZUM-nU2w:bb6tzbb) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/EnvironmentGitXThreadConfiguration.java#L22)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be final right ?
</blockquote></details>

DOne
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 659 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ81t-1hEdBTfOomab:-NhQU6qp7pGFFpCA2TrS:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L659)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this should also be invalid request exception right ?
also, do we need to declare error message separately ?
</blockquote></details>

Done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 912 at r5](https://reviewable.io/reviews/harness/harness-core/54344#-NhQy2As1ErmEm2yF5ti:-NhREyKjAFRRiIwHdo7n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fe5e31a51366602cb643ae588da71680e54b6ce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L912)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

lets put 'while getting environment inputs' in error and exceptions here
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 957 at r5](https://reviewable.io/reviews/harness/harness-core/54344#-NhQyKxu66dGgpH8ophm:-NhRKgBWAQRKcSAKDxI-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fe5e31a51366602cb643ae588da71680e54b6ce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L957)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

we should not get service here since there are chances service is present in some non default branch. This API would error out in that case. Let's get metadata here since we confirmed with UI YAML is not used.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 1000 at r5](https://reviewable.io/reviews/harness/harness-core/54344#-NhQwCkE4TUFImAPWtNa:-NhRG1laC2TqyOHu2xi2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fe5e31a51366602cb643ae588da71680e54b6ce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L1000)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

this method should be indicative that its populating YAML for entities as well. Maybe getEnvironmentMapWithYAML.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 297 at r4](https://reviewable.io/reviews/harness/harness-core/54344#-NhQ8OaVCuqFNRSjmMgz:-NhQVHpAErlBiXaQi1w1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6e68f6d9888353747d4d0e7c04bf382cf9ed210d/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L297)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

retrieving environment YAML: [%s] -> yaml for environment: [%s]
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-23 12:18 UTC, senjucanon2 commented
trigger uts

2023-10-23 15:19 UTC, senjucanon2 commented
trigger uts

2023-10-23 16:44 UTC, senjucanon2 commented
trigger ut8

2023-10-24 03:23 UTC, hingerabhinav approved these changes
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: 4 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-24 05:28 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54344)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-10-24 05:29 UTC, senjucanon2 commented
trigger review

2023-10-24 05:47 UTC, merged