feat: [CDS-80252] Move K8s Rolling step to be Async
harness/harness-core pull request #54379
Opened 2023-10-19 10:50 UTC by TarunUba1

## Describe your changes
K8s Rolling step changes
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-31 00:53 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncExecutableTaskHelper.java
> +        ambiance, StepDetailsDelegateInfo.builder().stepDelegateInfos(stepDelegateInfos).build(), taskName);
when we publish step details then they are added as details in the step running, hence didnt use stepName but adding it is possible if required

2023-10-31 05:50 UTC, abhinavsingh1196 reviewed
> Reviewed 9 of 25 files at r1, 7 of 17 files at r2, 4 of 4 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54379)* status: 29 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/54379#-Ni3Enes01oKcXr_1EU8:-Ni3Enes01oKcXr_1EU9:b-cnlgdj) ([raw file](https://github.com/harness/harness-core/blob/7fb28259cd976895c5c4598313d2f732fb8cc128/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java#L57)):*
> ```Java
>   private void notifyWithError(Map<String, ResponseData> response) {
>     try {
>       if (response.keySet().stream().findFirst().isEmpty()) {
> ```

can response be null ?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/54379#-Ni3Fjmf2h1ZS5UPLxzZ:-Ni3Fjmf2h1ZS5UPLxz_:b-3eildb) ([raw file](https://github.com/harness/harness-core/blob/7fb28259cd976895c5c4598313d2f732fb8cc128/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java#L64)):*
> ```Java
>       }
>       Ambiance ambiance = Ambiance.parseFrom(ambianceBytes);
>       log.info("AsyncSdkResumeCallback notify is called for ambiance with nodeExecutionId {}",
> ```

this is needed?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/54379#-Ni3FqdG5Egx6v_mWq3V:-Ni3FqdG5Egx6v_mWq3W:bcgre41) ([raw file](https://github.com/harness/harness-core/blob/7fb28259cd976895c5c4598313d2f732fb8cc128/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java#L79)):*
> ```Java
>           ambiance, StepDetailsDelegateInfo.builder().stepDelegateInfos(stepDelegateInfos).build(), taskName);
>     } catch (InvalidProtocolBufferException e) {
>       log.error("Not able to deserialize Ambiance bytes. Progress Callback will not be executed");
> ```

can be warn?


<!-- Sent from Reviewable.io -->

2023-10-31 06:16 UTC, namantalaycha10 requested changes

2023-10-31 06:16 UTC, namantalaycha10 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +      if (!response.keySet().stream().findFirst().get().equals(taskId)) {
nit: instead of these two if block we can use one if with or operation

2023-10-31 06:21 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sRollingStepPlanCreator.java
> +      return K8sRollingStepV2.STEP_TYPE;
Can be replaced by Ternary Operator , will look more clean and cover less lines

2023-10-31 06:21 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/K8sRollingStepPlanCreator.java
> +    } else {
Same here Can be replaced by Ternary Operator

2023-10-31 07:47 UTC, abosii-harness requested changes

2023-10-31 07:47 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +      if (!response.keySet().stream().findFirst().get().equals(taskId)) {
What if there are multiple responses, would it better to filter all of them and find the one matches the task id if it's present?

2023-10-31 07:47 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +      if (response.keySet().stream().findFirst().isEmpty()) {
I guess you mean to check if the map is empty? This is one way to do this I guess, but require a new stream pipeline to be created. why not just check for empty map? You can either get the null check with Harness Predicate

2023-10-31 07:47 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +      String accountId = ambiance.getSetupAbstractionsMap().get(SetupAbstractionKeys.accountId);
nit: is critical for us to get it from setup abstractions map or we can get it directly from ambiance?

2023-10-31 07:47 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +    responseMap.put("timeoutData", AsyncTimeoutResponseData.builder().build());
Are we sure that responseMap in this case is not immutable?

2023-10-31 07:47 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +    responseMap.put("timeoutData", AsyncTimeoutResponseData.builder().build());
Can you explain the logic behind this? Why we need to add timeoutData? And this I guess breaks the logic for notifyError, where you always check for first key

2023-10-31 10:29 UTC, alebuh requested changes

2023-10-31 10:29 UTC, alebuh commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateInfoHelper.java
> +  public LoadingCache<DelegateSelectionLogParamsKey, DelegateSelectionLogParams> taskIdToDelegateSelectionLogParams =
can be private

2023-10-31 10:29 UTC, alebuh commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateInfoHelper.java
> +  public DelegateSelectionLogParams getDelegateSelectionLogParams(String accountId, String taskId) {
can be private

2023-10-31 10:29 UTC, alebuh commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +  byte[] ambianceBytes;
why we are using byte[] instead of Ambiance Class?

2023-10-31 10:29 UTC, alebuh commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncExecutableTaskHelper.java
> +  public void publishStepDelegateInfoStepDetails(Ambiance ambiance, String taskName, String taskId) {
do we need this method? I think with your new logic it's not used anymore

2023-10-31 10:29 UTC, alebuh commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/GraphDelegateSelectionLogAsync.java
> +  DelegateSelectionLogParams selectionLogParams;
Do we need all fields from  DelegateSelectionLogParams? maybe we should provide just what is required (delegateName)

2023-10-31 10:29 UTC, alebuh commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/common/beans/StepDelegateInfo.java
> +  DelegateSelectionLogParams selectionLogParams;
I'm confused why we have StepDelegateInfo and GraphDelegateSelectionLogAsync ? I presume there is no need to have GraphDelegateSelectionLogAsync or at least it should just extend StepDelegateInfo but there is no point in having duplicated class

2023-10-31 11:44 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/GraphDelegateSelectionLogAsync.java
> +  DelegateSelectionLogParams selectionLogParams;
delegate name and id

2023-10-31 13:11 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +  byte[] ambianceBytes;
it throws stackoverflow error if not used

2023-10-31 13:27 UTC, alebuh approved these changes

2023-10-31 13:27 UTC, alebuh commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +          responses.entrySet().stream().filter(entry -> taskId.equals(entry.getKey())).map(Map.Entry::getValue);
nit: you could add findFirst().isEmpty() to avoid initialising the responseDataStream and you won't need next condition

2023-10-31 14:00 UTC, alebuh submitted a review, later dismissed

2023-10-31 14:11 UTC, alebuh submitted a review, later dismissed

2023-10-31 14:19 UTC, TarunUba1 commented
trigger uts

2023-10-31 15:04 UTC, TarunUba1 commented
trigger ut2,ut3,ut8,ut9

2023-10-31 15:37 UTC, TarunUba1 commented
trigger uts

2023-11-02 10:00 UTC, sahilhindwani-harness commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/54379#gh-1377342823:-NiET51N2NBgvgT0KZVr:btsrzjc) ([raw file](https://github.com/harness/harness-core/blob/7fb28259cd976895c5c4598313d2f732fb8cc128/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java#L40)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

it throws stackoverflow error if not used 
</blockquote></details>

why do we need to pass whole ambiance, why can't we pass the accountId only as it is the only thing  being used?
Ambiance is a little bit heavy.


<!-- Sent from Reviewable.io -->

2023-11-02 10:34 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54379)* status: 27 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/54379#gh-1377342823:-NiE_vJJAdspDlcdahWD:b-2qk7v0) ([raw file](https://github.com/harness/harness-core/blob/7fb28259cd976895c5c4598313d2f732fb8cc128/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java#L40)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why do we need to pass whole ambiance, why can't we pass the accountId only as it is the only thing  being used?
Ambiance is a little bit heavy.
</blockquote></details>

Ambiance is used in publishstepdetails to extract nodeexcutionid and planexecutionId also, for that reason i am using ambience, should i still remove this?


<!-- Sent from Reviewable.io -->

2023-11-02 10:47 UTC, alebuh approved these changes

2023-11-02 12:01 UTC, sahilhindwani-harness approved these changes
> Reviewed 2 of 25 files at r1, 7 of 17 files at r2, 1 of 4 files at r3, 3 of 11 files at r4, 4 of 8 files at r5, 3 of 3 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54379)* status: 16 file(s) to review. 2 change requests. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-02 12:02 UTC, namantalaycha10 approved these changes

2023-11-02 15:15 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +              .map(Map.Entry::getValue)
nit: What is the reason behind this map? Only maybe if you want to do later filter(nonNull), otherwise there is no point

2023-11-02 15:17 UTC, abosii-harness approved these changes

2023-11-02 15:17 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateResumeCallback.java
> +      log.warn("Not able to deserialize Ambiance bytes. Progress Callback will not be executed");
nit: we should log the exception or exception message, otherwise will be hard to debug if this is happening

2023-11-02 16:20 UTC, abhinavsingh1196 commented
trigger review

2023-11-02 17:33 UTC, TarunUba1 commented
trigger messagecheck

2023-11-02 18:11 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 17 files at r2, 7 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54379)* status: 9 file(s) to review. 2. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateInfoHelper.java` line 28 at r7](https://reviewable.io/reviews/harness/harness-core/54379#-NiGDjJJB2N1gZR5tkKA:-NiGDjJJB2N1gZR5tkKB:b-6jg0b9) ([raw file](https://github.com/harness/harness-core/blob/46800139f7fb55f1f96f00dc0b748cea692965f4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/executables/AsyncDelegateInfoHelper.java#L28)):*
> ```Java
> import lombok.Builder;
> import lombok.Data;
> import lombok.extern.slf4j.Slf4j;
> ```

nit: new line for readability


<!-- Sent from Reviewable.io -->

2023-11-02 18:12 UTC, yogesh-chauhan approved these changes
Approving as code owner of relevant files

2023-11-02 19:34 UTC, merged