fix:[CDS-81283]: Saving cd stage metadata summary during plan creation
harness/harness-core pull request #54396
Opened 2023-10-19 16:17 UTC by naman-goenka

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-25 16:03 UTC, naman-goenka commented
trigger uts

2023-10-26 06:58 UTC, naman-goenka commented
trigger uts

2023-10-26 07:01 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +    // TODO: to confirm whether we need to check for multi service and (or) env propagation that seems to be not allowed
cc: @yogesh-chauhan @tchaurasiya

2023-10-26 09:14 UTC, naman-goenka commented
trigger uts

2023-10-26 09:15 UTC, naman-goenka commented
trigger trigger smartchecks

2023-10-26 09:15 UTC, naman-goenka commented
trigger smartchecks

2023-10-27 09:47 UTC, yogesh-chauhan requested changes

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java
> +@ToString
why do we need this toString annotation from lombok ?

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java
> +  private String pipelineIdentifier;
pipelineIdentifier should also be NotNull ?

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java
> +  private ServiceDefinitionType deploymentType;
deploymentType should also be NotNull ?

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java
> +  private String stageName;
stageName should also be NotNull ?

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageType.java
> +  SINGLE_SERVICE_ENVIRONMENT(DeploymentStageTypeConstants.SINGLE_SERVICE_ENVIRONMENT);
do we really need this information ?

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageTypeConstants.java
> +public interface DeploymentStageTypeConstants {
nit: it is generally thought as a bad practice to use interface just to define constants: 
You can refer to: https://softwareengineering.stackexchange.com/questions/49572/is-it-a-bad-practice-to-have-an-interface-to-define-constants#:~:text=That%20a%20class%20uses%20some,it%20may%20even%20confuse%20them.

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +  @Inject ExecutorService executorService;
should be private ?

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +    if (isNull(planCreationResponse) || isNull(planCreationResponse.getPlanNode()) || isNull(stageConfig)) {
nit: stageConfig cannot be null here. IF it was null, plan creation would fail much earlier

2023-10-27 09:47 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +  protected void saveSingleServiceEnvDeploymentStagePlanCreationSummary(PlanCreationResponse planCreationResponse,
should we just pass planNode here and call it servicePlanNode or maybe just call planCreationResponse as ServicePlanCreationResponse

2023-10-27 10:07 UTC, yogesh-chauhan requested changes

2023-10-27 10:07 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +    executorService.submit(() -> {
do we really need an executor service for this ? Its just a DB save operation


Even if you need it, I think what we can do is to expose a new method called saveAsync and the threadPool can live with the "deploymentStagePlanCreationInfoService" instead of living with the callers


We also need to see what is the size of thread pool to maintain here. We can ask if Pipeline team has some metrics on concurrent plan creation

2023-10-27 13:27 UTC, naman-goenka reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54396)* status: 19 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374323165:-Nhl9SRX4zVXEpSPiJ9r:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java#L66)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

pipelineIdentifier should also be NotNull ?
</blockquote></details>

done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374323685:-Nhl7ghXDItHXNPD4hqa:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java#L67)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

stageName should also be NotNull ?
</blockquote></details>

done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374323403:-Nhl7O4F1AfdcClOfsLF:b9i2eaf) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java#L69)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

deploymentType should also be NotNull ?
</blockquote></details>

It wasn't marked with NotNull in ServiceStepV3Parameters
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageType.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374324822:-Nhl9YvJ9vI3UHwuFZNx:b7weq4m) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageType.java#L24)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we really need this information ?
</blockquote></details>

Decided to have polymorphic types as information stored in different cases can be different, and we are not sure also about all the cases like multi deployment, gitops, looping, etc.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageTypeConstants.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374327199:-Nhl9nEm8SqbeqHB9jPN:bt53ey1) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageTypeConstants.java#L20)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: it is generally thought as a bad practice to use interface just to define constants: 
You can refer to: https://softwareengineering.stackexchange.com/questions/49572/is-it-a-bad-practice-to-have-an-interface-to-define-constants#:~:text=That%20a%20class%20uses%20some,it%20may%20even%20confuse%20them.
</blockquote></details>

Sure understood. Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 175 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374327856:-NhlC_JCDqPHazIR-Vnh:bi06l9c) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L175)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be private ?
</blockquote></details>

yes done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 868 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374331015:-NhlCxvn52yx2o5CfB6J:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L868)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we just pass planNode here and call it servicePlanNode or maybe just call planCreationResponse as ServicePlanCreationResponse
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 872 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374329429:-NhlDXCd1dfMeLGgizEx:b7gjm2p) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L872)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: stageConfig cannot be null here. IF it was null, plan creation would fail much earlier 
</blockquote></details>

removed the redundant check
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 891 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374353791:-NhlDawaDrFcm_5fEi6X:b-pmwpsb) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L891)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we really need an executor service for this ? Its just a DB save operation


Even if you need it, I think what we can do is to expose a new method called saveAsync and the threadPool can live with the "deploymentStagePlanCreationInfoService" instead of living with the callers


We also need to see what is the size of thread pool to maintain here. We can ask if Pipeline team has some metrics on concurrent plan creation
</blockquote></details>

Motivation: was apart of save call, this would also serve other db calls which is planned to be added here like fetching environment/service/infra object to names instead of identifiers in notifications. 

Considering these usecases, preferred to have the async threads initiated in plan creator itself, is there a concern here?

Sure, will discuss regarding load during plan creation. We can discuss further whether to have executor service or not here.


<!-- Sent from Reviewable.io -->

2023-10-27 13:38 UTC, naman-goenka reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54396)* status: 19 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java` line 48 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374322031:-NhlLc597X8q27NBazdr:bbk1nr0) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java#L48)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why do we need this toString annotation from lombok ?
</blockquote></details>

removing, was redundant


<!-- Sent from Reviewable.io -->

2023-10-27 14:02 UTC, naman-goenka commented
trigger uts

2023-10-27 15:29 UTC, naman-goenka commented
trigger uts

2023-10-30 05:58 UTC, abhinavmittal-harness approved these changes
> Reviewed 13 of 17 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 3 files at r5, 1 of 1 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54396)* status: 25 file(s) to review. 1 change requests. 10. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-30 07:03 UTC, yogesh-chauhan commented
*[`120-ng-manager/config.yml` line 610 at r7](https://reviewable.io/reviews/harness/harness-core/54396#-NhzOCg3DhdcXYJFprXh:-NhzOCg3DhdcXYJFprXi:b-is5xg2) ([raw file](https://github.com/harness/harness-core/blob/1e4ed75282483765c682b9c61f6c4db442ba67bc/120-ng-manager/config.yml#L610)):*
> ```YAML
> deploymentStagePlanCreationInfoThreadConfig:
>   threadPoolConfig:
>     corePoolSize: ${SERVICE_GITX_POOL_CORE_SIZE:-1}
> ```

we should not couple it with SERVICE GITX Thread configuration. It should have its own variables to define


<!-- Sent from Reviewable.io -->

2023-10-30 07:12 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 891 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374353791:-NhzPoN1ESGUqQefH-ds:b-excxfy) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L891)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

Motivation: was apart of save call, this would also serve other db calls which is planned to be added here like fetching environment/service/infra object to names instead of identifiers in notifications. 

Considering these usecases, preferred to have the async threads initiated in plan creator itself, is there a concern here?

Sure, will discuss regarding load during plan creation. We can discuss further whether to have executor service or not here.
</blockquote></details>

Yes. One more question here was where should the executor service live. 
- with the plan creator
- with the deploymentStagePlanCreationInfoService

As of now, it does not matter. But if there were to be multiple classes that call `deploymentStagePlanCreationInfoService.save`, then its better to have it at one place that is `deploymentStagePlanCreationInfoService` 


<!-- Sent from Reviewable.io -->

2023-10-30 07:14 UTC, yogesh-chauhan reviewed
> Reviewed 13 of 17 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 3 files at r5, 1 of 1 files at r6, 5 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54396)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374323403:-NhzOofh0S9KUXURFiba:b-1eky5n) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java#L69)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

It wasn't marked with NotNull in ServiceStepV3Parameters
</blockquote></details>

It should be NotNull always in ServiceStep, but its fine for now


<!-- Sent from Reviewable.io -->

2023-10-31 18:21 UTC, naman-goenka reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54396)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 610 at r7](https://reviewable.io/reviews/harness/harness-core/54396#-NhzOCg3DhdcXYJFprXh:-Ni5xsm3EYv0kzLiPK2k:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1e4ed75282483765c682b9c61f6c4db442ba67bc/120-ng-manager/config.yml#L610)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should not couple it with SERVICE GITX Thread configuration. It should have its own variables to define
</blockquote></details>

done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374323403:-Ni5xTp0BrALLe5-HSjJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePlanCreationInfo.java#L69)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

It should be NotNull always in ServiceStep, but its fine for now
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 891 at r4](https://reviewable.io/reviews/harness/harness-core/54396#gh-1374353791:-Ni5xc6E7R4TTkfiBRCO:b8sehom) ([raw file](https://github.com/harness/harness-core/blob/5445c96792d0765cf6431ea033875e47ce082273/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L891)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Yes. One more question here was where should the executor service live. 
- with the plan creator
- with the deploymentStagePlanCreationInfoService

As of now, it does not matter. But if there were to be multiple classes that call `deploymentStagePlanCreationInfoService.save`, then its better to have it at one place that is `deploymentStagePlanCreationInfoService`
</blockquote></details>

Following this on slack to understand. If we need to call EnvironmentServiceV2 etc, shouldn't the executor stay in plan creator itself. 


<!-- Sent from Reviewable.io -->

2023-10-31 18:25 UTC, naman-goenka commented
trigger uts

2023-11-01 11:09 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 7 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54396)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-02 05:39 UTC, naman-goenka commented
trigger uts

2023-11-02 07:59 UTC, abhinavmittal-harness approved these changes

2023-11-02 09:27 UTC, naman-goenka commented
Note: unrelated uts are failing

2023-11-03 06:07 UTC, naman-goenka commented
trigger uts

2023-11-03 07:01 UTC, naman-goenka commented
trigger ut9

2023-11-03 12:41 UTC, merged