feat: [CDS-78335] Adding apply step changes in ng-manager
harness/harness-core pull request #54423
Opened 2023-10-20 07:04 UTC by TarunUba1

## Describe your changes
Just creating a manifest outcome and when manifest source is there than change the K8sManifestOutcome and use this for fetching manifests.
## Testing
1. tested older route
2. tested with manifest source with manifest in github
3. tested with manifest source with manifest in harness store
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-20 07:45 UTC, abhinavsingh1196 reviewed
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54423)* status: 6 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/54423#-NhAvxV4AfW6R67z7nTW:-NhAvxV5Da1FvN3Q4rjb:b-plmus1) ([raw file](https://github.com/harness/harness-core/blob/24323dc8cd8eeb3f8be8f74cd8f6b0758ff2d81b/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L166)):*
> ```Java
>   public static final String RELEASE_NAME_VALIDATION_REGEX =
>       "[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*";
>   public static final String MANIFEST_SOURCE_IDENTIFIER = "APPLY_STEP_MANIFEST_SOURCE_ID";
> ```

nit: can be private?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 831 at r1](https://reviewable.io/reviews/harness/harness-core/54423#-NhAwB2-4aI5iVH5QHe6:-NhAwB2-4aI5iVH5QHe7:b-49wmze) ([raw file](https://github.com/harness/harness-core/blob/24323dc8cd8eeb3f8be8f74cd8f6b0758ff2d81b/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L831)):*
> ```Java
>   }
> 
>   public ManifestOutcome getStepLevelSourceOutcome(StepBaseParameters stepElementParameters) {
> ```

nit: use Optional to avoid using null
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 831 at r1](https://reviewable.io/reviews/harness/harness-core/54423#-NhB1xw_-nb6J5TOXde3:-NhB1xw_-nb6J5TOXde4:b-q8gc2r) ([raw file](https://github.com/harness/harness-core/blob/24323dc8cd8eeb3f8be8f74cd8f6b0758ff2d81b/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L831)):*
> ```Java
>   }
> 
>   public ManifestOutcome getStepLevelSourceOutcome(StepBaseParameters stepElementParameters) {
> ```

also, let's add unit tests
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 844 at r1](https://reviewable.io/reviews/harness/harness-core/54423#-NhB-jNV8hZfC11vx18g:-NhB-jNV8hZfC11vx18h:b-fsiz0q) ([raw file](https://github.com/harness/harness-core/blob/24323dc8cd8eeb3f8be8f74cd8f6b0758ff2d81b/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L844)):*
> ```Java
>       }
>     }
>     return null;
> ```

nit: if you make the method like this, then it removes nested IFs

if ( condition X ) return Optional.empty()
...
if ( condition Y ) return Optional.empty()
..
return Optional.ofNullable(A)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java` line 127 at r1](https://reviewable.io/reviews/harness/harness-core/54423#-NhB14Wj49L15K2bPsYx:-NhB0ThW9vF-E_eUOlpJ:b-pf62zu) ([raw file](https://github.com/harness/harness-core/blob/24323dc8cd8eeb3f8be8f74cd8f6b0758ff2d81b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java#L127)):*
> ```Java
> 
>   private void validateManifestSource(K8sApplyStepParameters k8sApplyStepParameters) {
>     if (k8sApplyStepParameters.getManifestSource() == null) {
> ```

this block looks unreachable, since you already checked manifestSource to be non-null in the calling function?
 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/54423#-NhB1MGM9LwWfwRpCgtH:-NhB1MGM9LwWfwRpCgtI:b57gokt) ([raw file](https://github.com/harness/harness-core/blob/24323dc8cd8eeb3f8be8f74cd8f6b0758ff2d81b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java#L133)):*
> ```Java
>     if (!ManifestType.K8Manifest.equals(k8sApplyStepParameters.getManifestSource().getType().getDisplayName())) {
>       throw new UnsupportedOperationException(
>           format("Unsupported Manifest type: [%s]", k8sApplyStepParameters.getManifestSource().getType()));
> ```

nit: we can improve this message, saying that Apply step only supports manifests of types [K8s], and [X] is provided


<!-- Sent from Reviewable.io -->

2023-10-20 07:50 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
> +    if (k8sApplyStepParameters.getManifestSource() != null) {
This condition is sufficient as we already doing checking inside a method. It can be simplified to do it only once (probably inside a method)

2023-10-20 07:50 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
> +    // validate manifest source
do we need this comment?

2023-10-20 07:50 UTC, alebuh commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
> +          k8sApplyStepParameters.getManifestSource().getSpec().getStoreConfig().getFilePaths());
Can this .getFilePaths() throw NPE ?

2023-10-23 06:17 UTC, TarunUba1 commented
trigger uts

2023-10-23 06:49 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
> +          k8sApplyStepParameters.getManifestSource().getSpec().getStoreConfig().getFilePaths());
it should not but still added the check

2023-10-23 11:27 UTC, abhinavsingh1196 requested changes
> Reviewed 3 of 4 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54423)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java` line 287 at r4](https://reviewable.io/reviews/harness/harness-core/54423#-NhRHMS15XOjdZt-uzYS:-NhRHMS28Es5y8H0e3FE:b-vahl8c) ([raw file](https://github.com/harness/harness-core/blob/fcfbcd654507a91da5f685d08bf65a0756fd1ea1/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java#L287)):*
> ```Java
>   }
> 
>   public boolean isFilePath(String path) {
> ```

we should write unit tests for this method to ensure it behaves as expected


<!-- Sent from Reviewable.io -->

2023-10-23 11:38 UTC, TarunUba1 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sApplyStepTest.java
> +  @Test
i have added UT for this function

2023-10-23 11:39 UTC, TarunUba1 commented
trigger uts

2023-10-24 07:33 UTC, TarunUba1 commented
trigger uts

2023-10-24 07:46 UTC, TarunUba1 commented
trigger ut6

2023-10-24 08:34 UTC, abhinavsingh1196 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54423)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-10-24 09:14 UTC, alebuh approved these changes

2023-10-24 09:27 UTC, markoharness approved these changes

2023-10-24 10:01 UTC, TarunUba1 commented
trigger messagecheck

2023-10-24 10:01 UTC, TarunUba1 commented
trigger review

2023-10-24 10:03 UTC, merged