fix: [PL-42104]: fix auditing login for all accounts for a single login event
harness/harness-core pull request #54445
Opened 2023-10-20 13:06 UTC by sahibaHarness

## Describe your changes
Currently in SSO redirect flow we log audits for all the accounts the user is apart of. We are changing the flow to only audit for default account.
Similar changes have been made in other login flows as well.

<img width="1333" alt="image" src="https://github.com/harness/harness-core/assets/112424209/de52041f-1321-4b38-ab2a-2eb99f490675">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-20 13:07 UTC, sahibaHarness commented
trigger uts

2023-10-26 10:13 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
> +        authService.auditLoginToNg(Collections.singletonList(user.getDefaultAccountId()), loggedInUser);
If a user (part of multiple accounts) uses deepLink to login/IdP initiated login using SAML to one of its SAML account (which is not the user’s default account), this would create audit in wrong account (default account), right?

2023-10-26 10:32 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
> +        authService.auditLoginToNg(Collections.singletonList(user.getDefaultAccountId()), loggedInUser);
resolving it

2023-10-26 17:56 UTC, shashank-harness commented
@sahibaHarness Please test this with help of QE and make sure there is no regression.
We can merge post that

2023-10-26 17:57 UTC, shashank-harness approved these changes
lgtm

2023-10-27 04:29 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java
> +        authService.auditLoginToNg(Collections.singletonList(user.getDefaultAccountId()), loggedInUser);
we'll get the account ID from claims in the jwt token.

2023-10-27 05:25 UTC, sahibaHarness commented
trigger uts

2023-10-31 12:02 UTC, pbarapatre10 approved these changes

2023-10-31 12:08 UTC, mohitg0795 commented
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3912 at r2](https://reviewable.io/reviews/harness/harness-core/54445#-Ni4cd2i9uklZyy013kE:-Ni4cd2i9uklZyy013kF:b-sl2yf8) ([raw file](https://github.com/harness/harness-core/blob/1b2a3f6dab4eb5c4c5374b9274b321c345b853df/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3912)):*
> ```Java
>       return JWT.decode(jwtToken).getClaim(claim).asString();
>     } catch (UnsupportedEncodingException | JWTCreationException exception) {
>       throw new GeneralException("JWTToken validation failed");
> ```

why are we throwing generalException here? Looking from the error message, it should be InvalidRequestException


<!-- Sent from Reviewable.io -->

2023-10-31 12:10 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54445)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3911 at r2](https://reviewable.io/reviews/harness/harness-core/54445#-Ni4d2t_91HepiEhS3Jq:-Ni4d2ta3tbjepnA6kz8:bgkzpt1) ([raw file](https://github.com/harness/harness-core/blob/1b2a3f6dab4eb5c4c5374b9274b321c345b853df/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3911)):*
> ```Java
>       verifier.verify(jwtToken);
>       return JWT.decode(jwtToken).getClaim(claim).asString();
>     } catch (UnsupportedEncodingException | JWTCreationException exception) {
> ```

don't you think we should log the exception otherwise we won't be able to know what kind of exception did we actually face?


<!-- Sent from Reviewable.io -->

2023-10-31 12:10 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54445)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3913 at r2](https://reviewable.io/reviews/harness/harness-core/54445#-Ni4d8lR6afihNMJDewG:-Ni4d8lR6afihNMJDewH:b6ppp0q) ([raw file](https://github.com/harness/harness-core/blob/1b2a3f6dab4eb5c4c5374b9274b321c345b853df/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3913)):*
> ```Java
>     } catch (UnsupportedEncodingException | JWTCreationException exception) {
>       throw new GeneralException("JWTToken validation failed");
>     } catch (JWTDecodeException | SignatureVerificationException e) {
> ```

same here as above


<!-- Sent from Reviewable.io -->

2023-10-31 12:11 UTC, mohitg0795 commented
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3913 at r2](https://reviewable.io/reviews/harness/harness-core/54445#-Ni4d8lR6afihNMJDewG:-Ni4dBxN91EhcXuVR1ML:bu2bymt) ([raw file](https://github.com/harness/harness-core/blob/1b2a3f6dab4eb5c4c5374b9274b321c345b853df/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3913)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here as above
</blockquote></details>

"don't you think we should log the exception otherwise we won't be able to know what kind of exception did we actually face?"


<!-- Sent from Reviewable.io -->

2023-10-31 12:29 UTC, sahibaHarness commented
trigger uts

2023-10-31 13:36 UTC, shashank-harness submitted a review, later dismissed
lgtm

2023-11-01 12:31 UTC, sahibaHarness commented
trigger uts

2023-11-01 12:32 UTC, sahibaHarness commented
trigger uts

2023-11-01 12:49 UTC, sahibaHarness commented
trigger uts

2023-11-01 19:52 UTC, sahibaHarness commented
trigger uts

2023-11-01 19:53 UTC, mohitg0795 approved these changes
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54445)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-01 21:12 UTC, merged