fix: [CDS-81168]: Change field from string to parameter<string> for harness auto approval
harness/harness-core pull request #54503
Opened 2023-10-23 10:30 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-02 12:21 UTC, abhinavmittal-harness commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/ScheduledDeadline.java
> -  @NotNull String time;
qq: do we need to do any schema changes when using parameter field

2023-11-03 06:33 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java
> +public class HarnessApprovalUtils {
please add uts for this class

2023-11-03 08:08 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +        scheduledDeadline.getTime().getValue(), scheduledDeadline.getTimeZone().getValue()));
Since the feature is behind FF, we can add a backward incompatible notEmpty check and also unresolved expression fast fail

2023-11-03 08:10 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +        scheduledDeadline.getTime().getValue(), scheduledDeadline.getTimeZone().getValue()));
in utils that can be added

2023-11-03 08:23 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java
> +      if (isNotEmpty(time) && isNotEmpty(timeZone)) {
followed on slack whether we need to add condition on step timeout

2023-11-05 07:53 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans/ScheduledDeadline.java
> -  @NotNull String time;
No ,we don't need any schema changes

2023-11-05 07:56 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java
> +      if (isNotEmpty(time) && isNotEmpty(timeZone)) {
They have intentionally not added any condition related to timeout.

2023-11-06 02:25 UTC, vivekkarnatiharness commented
trigger smartchecks

2023-11-06 04:29 UTC, vivekkarnatiharness commented
trigger uts

2023-11-06 05:15 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java
> +        throw new InvalidRequestException("Auto Approval parameter Time cannot be null");
nit: should we add a check for unresolved expressions. 
nit: should we check for blank values

2023-11-06 05:27 UTC, abhinavmittal-harness requested changes
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54503)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/54503#-NiY5GeL5a_bFK-LlV4f:-NiY5GeL5a_bFK-LlV4g:bbwcn9i) ([raw file](https://github.com/harness/harness-core/blob/dc756e9e3b815a8f683acaff16c7229b9bc7a026/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java#L51)):*
> ```Java
>     return harnessApprovalSpecParameters.getAutoApproval().getScheduledDeadline().getTimeZone().getValue();
>   }
>   public static void checkForNullOrThrowAutoApproval(AutoApprovalParams autoApprovalParams) {
> ```

Can we check thow separate error if expression resolution is not happening


<!-- Sent from Reviewable.io -->

2023-11-06 07:04 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54503)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-06 07:05 UTC, abhinavmittal-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54503)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-06 07:06 UTC, vivekkarnatiharness commented
trigger uts

2023-11-06 08:44 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +      checkForNullOrThrowAutoApproval(specParameters.getAutoApproval());
this should be called before validating auto approval timestamp, we can have precheck and timestamp check behind FF

2023-11-06 08:46 UTC, naman-goenka commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java
> +      if (autoApprovalParams.getScheduledDeadline().getTime().isExpression()) {
I believe isExpression is always false is default mode irrespective of whether expression was configured.

2023-11-06 09:01 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java
> +      if (autoApprovalParams.getScheduledDeadline().getTime().isExpression()) {
But we are having similar checks for other places where we are using paramteric fields right?? @abhinavmittal-harness ??

2023-11-06 11:00 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalUtils.java
> +      if (autoApprovalParams.getScheduledDeadline().getTime().isExpression()) {
Yeah, have tested this and removed the condition

2023-11-06 11:01 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +      checkForNullOrThrowAutoApproval(specParameters.getAutoApproval());
Have moved the check behind

2023-11-06 11:01 UTC, vivekkarnatiharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStep.java
> +      checkForNullOrThrowAutoApproval(specParameters.getAutoApproval());
ff

2023-11-06 13:24 UTC, naman-goenka approved these changes

2023-11-06 15:36 UTC, vivekkarnatiharness commented
trigger smartchecks

2023-11-06 15:38 UTC, vivekkarnatiharness commented
trigger checkstylecodeformat

2023-11-06 15:38 UTC, vivekkarnatiharness commented
trigger pmd

2023-11-06 15:39 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-11-06 15:46 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-11-06 16:34 UTC, abhinavmittal-harness approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54503)* status: 6 file(s) to review. 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-06 16:43 UTC, merged