feat: [CDS-80239]: Added Access Control check for Skip in-progress verifications
harness/harness-core pull request #54517
Opened 2023-10-23 15:07 UTC by ShubhenduP

feat: [CDS-80239]: Added Access Control check for Skip in-progress verifications

## Describe your changes
Added Access Control Check For Skip In-process verification api

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-23 15:10 UTC, ShubhenduP commented
trigger its

2023-10-23 15:11 UTC, ShubhenduP commented
trigger uts

2023-10-25 23:39 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/resources/VerifyStepResourceImpl.java
> +    accessControlClient.checkForAccessOrThrow(
Add Junits to verify them

2023-11-07 05:27 UTC, ShubhenduP commented
trigger ut2

2023-11-08 04:38 UTC, ShubhenduP commented
trigger ut2

2023-11-08 05:04 UTC, AbhijithHarness approved these changes

2023-11-08 05:12 UTC, ShubhenduP commented
trigger review

2023-11-08 05:43 UTC, sandeepharness approved these changes

2023-11-08 05:44 UTC, ShubhenduP commented
trigger review

2023-11-08 06:36 UTC, sribalij approved these changes

2023-11-08 06:36 UTC, sribalij commented
trigger review

2023-11-08 11:27 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54517)* status: 3 file(s) to review. 1 change requests. 

___
*[`clients/access-control/sdk/src/main/java/io/harness/accesscontrol/NGAccessControlCheckHandler.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/54517#-NiifxIN9JJUsemUqOmk:-NiifxIN9JJUsemUqOml:b-moes9j) ([raw file](https://github.com/harness/harness-core/blob/537bad9f7a0201258c0234d167911c5c94dde1a9/clients/access-control/sdk/src/main/java/io/harness/accesscontrol/NGAccessControlCheckHandler.java#L72)):*
> ```Java
>   @SneakyThrows
>   private void populateNGAccessBuilderFromBeanParam(BaseNGAccess.Builder builder, Object object) {
>     for (Field field : FieldUtils.getAllFieldsList(object.getClass())) {
> ```

Please add context in PR around why this change is needed?


<!-- Sent from Reviewable.io -->

2023-11-08 11:34 UTC, ShubhenduP commented on clients/access-control/sdk/src/main/java/io/harness/accesscontrol/NGAccessControlCheckHandler.java
This change is required to get all fields from the super classes also of the object. Its needed because the NGAccessControlCheck annotation is used with object of class VerifyStepPathParams which is an extended class of ProjectPathParams, and to process further we would need fields from parent class(accountIdentifier, orgIdentifier and projectIdentifier).

2023-11-08 12:35 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54517)* status: 3 file(s) to review. 1 change requests. 

___
*[`clients/access-control/sdk/src/main/java/io/harness/accesscontrol/NGAccessControlCheckHandler.java` line 0 at r3](https://reviewable.io/reviews/harness/harness-core/54517#gh-1386480206:-NiivYQ5ASNvbvhDqHo2:b-isd431) ([raw file](https://github.com/harness/harness-core/blob/537bad9f7a0201258c0234d167911c5c94dde1a9/clients/access-control/sdk/src/main/java/io/harness/accesscontrol/NGAccessControlCheckHandler.java#L0)):*
<details><summary><i>Previously, ShubhenduP wrote…</i></summary><blockquote>

This change is required to get all fields from the super classes also of the object. Its needed because the NGAccessControlCheck annotation is used with object of class VerifyStepPathParams which is an extended class of ProjectPathParams, and to process further we would need fields from parent class(accountIdentifier, orgIdentifier and projectIdentifier). 
</blockquote></details>

Add this in PR description.


<!-- Sent from Reviewable.io -->

2023-11-09 04:55 UTC, Jimit09Gandhi approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54517)* status: 3 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-11-09 05:06 UTC, merged