feat: [PL-41269]: DelegateDown and DelegateExpiry Notification
harness/harness-core pull request #54519
Opened 2023-10-23 15:31 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-25 22:43 UTC, jennyjames21 commented
trigger uts

2023-10-26 01:48 UTC, jennyjames21 commented
trigger uts

2023-10-26 01:55 UTC, jennyjames21 commented
trigger commonchecks

2023-11-07 23:40 UTC, xingchi-jin commented on 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
> +      long delegateExpiry = delegateSetupService.getDelegateExpirationTime(
it's probably better not to create a new var delegateExpirOn, we can calculate the expiry time on demand

2023-11-09 00:06 UTC, jennyjames21 commented
trigger uts

2023-11-09 00:20 UTC, jennyjames21 commented
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3268 at r2](https://reviewable.io/reviews/harness/harness-core/54519#gh-1385743728:-NilRlg16N9OsErIJLpp:b-9bpv9o) ([raw file](https://github.com/harness/harness-core/blob/c179e183b8a8112c508430c8f0ed1ae52be90e38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3268)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

it's probably better not to create a new var delegateExpirOn, we can calculate the expiry time on demand
</blockquote></details>

as discussed over the call, we will keep it in the DB for iterator purpose


<!-- Sent from Reviewable.io -->

2023-11-09 00:33 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                                      .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
what does this filter mean ? why 45 days

2023-11-09 00:34 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +    if (isDelegateExpiryNotificationAlreadySent(delegateGroup)) {
this implementation depends on the "SLA" is notification. 
do we require every expiry event to deliver exactly once, or at least once ?

2023-11-09 00:38 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java
> +        triggerNotificationRequest(delegate);
what if delegate unregister, and delete delegate, do we send notification "DOWN" ?

2023-11-09 04:59 UTC, raghuAtWings requested changes

2023-11-09 04:59 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +            .setEvent(NotificationEvent.DELEGATE_DOWN.name())
why is this delegate down?

2023-11-09 04:59 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                               .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
don't understand this 45 days logic. shouldn't we keep sending update every day the delegate is expired?

2023-11-09 04:59 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +    if (isDelegateExpiryNotificationAlreadySent(delegateGroup)) {
should we make this simpler by sending one notification every day. What if the notification is missed and then we never notify. i think we should run this iterator every day and notify for every expired delegate.

2023-11-09 19:50 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java
> +        triggerNotificationRequest(delegate);
I'm not sure that's the same use case here. I can check with pratheek
1) Rolling upgrade or version upgrade or autoscaling
 2) delete on purpose

Another thing we use delegate to send notifications to email/slack if delegate is down we are relying on other delegates in the account 😆

2023-11-09 19:53 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                               .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
im using this iterator for both delegateExpiry and delegateAboutToExpire. 
DelegateaboutToExpire event allows to send notifications 1-4 weeks before expiration.

2023-11-09 19:53 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                               .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
i will change to 30 days

2023-11-09 19:54 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                                      .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
im using this iterator for both delegateExpiry and delegateAboutToExpire.
DelegateaboutToExpire event allows to send notifications 1-4 weeks before expiration.

2023-11-09 20:02 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +    if (isDelegateExpiryNotificationAlreadySent(delegateGroup)) {
interval to run in iterator in iterator_config.json
 "targetIntervalInSeconds": 86400,

2023-11-09 20:07 UTC, jennyjames21 commented
trigger uts

2023-11-09 21:41 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                               .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
should this be System.currentTimeMillis() + TimeUnit.DAYS.toMillis(30)

2023-11-09 21:43 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                               .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
in addition, is it possible to make this number "30" a configuration, i m afraid we will run into customer requests where people want to change
or should we do per account config

2023-11-09 22:13 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +                               .lessThan(System.currentTimeMillis() - TimeUnit.DAYS.toMillis(45)))
yes it should be +

It's configurable already, we just fetching the record from DB and send the notification only based on their settings
That check will be on the next iteration due to dependency to another PR

2023-11-09 22:20 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/iterator/DelegateExpiryAlertIterator.java
> +            .setEvent(NotificationEvent.DELEGATE_DOWN.name())
for testing, updated

2023-11-09 22:46 UTC, jennyjames21 commented
trigger uts

2023-11-09 22:50 UTC, jennyjames21 commented
trigger commonchecks

2023-11-09 23:05 UTC, jennyjames21 commented
trigger commonchecks

2023-11-09 23:28 UTC, jennyjames21 commented
trigger uts

2023-11-13 23:36 UTC, jennyjames21 commented
trigger uts

2023-11-14 04:30 UTC, jennyjames21 commented
trigger uts

2023-11-14 04:32 UTC, raghuAtWings approved these changes

2023-11-14 04:56 UTC, merged