feat: [PL-41273]: Notification when connector goes down
harness/harness-core pull request #54535
Opened 2023-10-24 04:02 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-25 05:50 UTC, jennyjames21 commented
trigger uts

2023-10-25 16:52 UTC, jennyjames21 commented
trigger uts

2023-10-25 18:18 UTC, jennyjames21 commented
trigger uts

2023-10-30 12:17 UTC, meenakshi-harness requested changes

2023-10-30 12:17 UTC, meenakshi-harness commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/Connector.java
> +  Long lastAlertSent;
Should we move these inside connectivityDetails

2023-10-30 16:32 UTC, jennyjames21 commented on 440-connector-nextgen/src/main/java/io/harness/connector/entities/Connector.java
> +  Long lastAlertSent;
yes makes sense. 
Moved   lastAlertSent inside connectivityDetails

keeping connectorDisconnectIteration inside the connector as it's handler job running on the entity.

2023-10-30 16:32 UTC, jennyjames21 commented
trigger uts

2023-11-06 07:42 UTC, jennyjames21 commented
trigger uts

2023-11-06 07:47 UTC, meenakshi-harness commented on 970-ng-commons/src/main/java/io/harness/constants/ConnectorConstants.java
> +  public static final String LAST_ALERT = "Last alert sent time last when connector went down";
can we get this reviewed by doc team?

2023-11-06 07:47 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/connector/ConnectorDisconnectHandler.java
> +    templateData.put("TEMPLATE_IDENTIFIER", "connector_down");
use constants?

2023-11-06 07:49 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/connector/ConnectorDisconnectHandler.java
> +            .setOrgId(connector.getOrgIdentifier() != null ? connector.getOrgIdentifier() : "")
why are we setting empty string and not null?

2023-11-06 07:51 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/connector/ConnectorDisconnectHandler.java
> +        == connector.getConnectivityDetails().getLastConnectedAt();
store this in variable `connector.getConnectivityDetails()` and re-use

2023-11-07 00:00 UTC, jennyjames21 commented on 120-ng-manager/src/main/java/io/harness/ng/core/handler/connector/ConnectorDisconnectHandler.java
> +        == connector.getConnectivityDetails().getLastConnectedAt();
updated

2023-11-07 03:52 UTC, nishantsaini20 requested changes
> Reviewed 4 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54535)* status: 6 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/connector/ConnectorDisconnectHandler.java` line 113 at r7](https://reviewable.io/reviews/harness/harness-core/54535#-NibtxRu-D-XICvJAjoq:-NibtxRu-D-XICvJAjor:bxz2xo) ([raw file](https://github.com/harness/harness-core/blob/84aba577858463839706b7ab78aa45478b891962/120-ng-manager/src/main/java/io/harness/ng/core/handler/connector/ConnectorDisconnectHandler.java#L113)):*
> ```Java
>             .setAccountId(connector.getAccountIdentifier())
>             .setOrgId(connector.getOrgIdentifier() != null ? connector.getOrgIdentifier() : "")
>             .setProjectId(connector.getProjectIdentifier() != null ? connector.getProjectIdentifier() : "")
> ```

Same here. Why not null?


<!-- Sent from Reviewable.io -->

2023-11-07 08:06 UTC, jennyjames21 commented
trigger uts

2023-11-07 08:50 UTC, meenakshi-harness approved these changes

2023-11-07 15:31 UTC, jennyjames21 commented
trigger messagecheck

2023-11-07 15:32 UTC, merged