feat: [PL-39275]: SEND METRICS TO SEGMENT Ng-manager changes
harness/harness-core pull request #54613
Opened 2023-10-25 11:44 UTC by sahibaHarness

'

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-25 11:44 UTC, sahibaHarness commented
trigger uts

2023-10-27 05:38 UTC, sahibaHarness commented
trigger uts

2023-10-27 07:04 UTC, ankit-harness requested changes
> Reviewed 3 of 15 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjnCtT-LzDkgQgYQTE:-NhjnCtU7WfaOjQND7F2:b-d2xdyn) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java#L39)):*
> ```Java
>   void deleteAuditInfo(String accountId);
> 
>   void sendAuditMetricsForAccount(List<String> accountIds, long startTime, long endTime);
> ```

This method should not be present in this class. AuditService should not have any knowledge of Segment and Prometheus.

We can expose a method such as 

getUniqueActionCount(String accountId, String action, Instant startTime, Instant endTime);
getUniqueActiveProjectCount(String accountId, Instant startTime, Instant endTime);
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 387 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjpnqXDgjrH6rOyV3y:-NhjpnqXDgjrH6rOyV3z:b-xrpd5e) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L387)):*
> ```Java
>   }
> 
>   private void sendAuditEventMetricsToSegment(
> ```

Sending of metrics should should happen in the Job itself to keep this class decoupled
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 399 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjqIOSEph-NfuWDhxC:-NhjqIOSEph-NfuWDhxD:bacitp) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L399)):*
> ```Java
>     properties.put("uniqueLogins", uniqueUserLogins);
> 
>     telemetryReporter.sendTrackEvent("account_audit_metrics",
> ```

account_activity_metrics maybe?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 404 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjpva50hFXcVfdlHGz:-Nhjpva50hFXcVfdlHH-:b-xrpd5e) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L404)):*
> ```Java
>   }
> 
>   private void sendAuditEventMetricsToPrometheus(String accountIdentifier, int activeProjects, int uniqueLogins) {
> ```

Sending of metrics should should happen in the Job itself to keep this class decoupled
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AccountAuditMetricsTracker.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjq_X94r_NM0Z4PipS:-Nhjq_X94r_NM0Z4PipT:b6itx11) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AccountAuditMetricsTracker.java#L37)):*
> ```Java
> @TypeAlias("AccountAuditMetricsTracker")
> @JsonInclude(NON_NULL)
> public class AccountAuditMetricsTracker {
> ```

AccountActivityMetricsPublishTracker
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AccountAuditMetricsTracker.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjrv3a4V01fOKWz97s:-Nhjrv3a4V01fOKWz97t:b-xxmrzm) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AccountAuditMetricsTracker.java#L37)):*
> ```Java
> @TypeAlias("AccountAuditMetricsTracker")
> @JsonInclude(NON_NULL)
> public class AccountAuditMetricsTracker {
> ```

These classes are not audit entities. These are entities related to metrics.

So, we can have a package io.harness.metrics
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AccountAuditMetricsTracker.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjr8mfAQbxLuE1RRUh:-Nhjr8mfAQbxLuE1RRUi:b-v1lram) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AccountAuditMetricsTracker.java#L41)):*
> ```Java
>   Long startTime;
>   Long endTime;
>   @NotNull Long timestamp;
> ```

Whats the purpose of this field? Time at which we published the metrics? If yes, we should call it lastPublishTime and maybe use Instant

Instant lastPublishTime;
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjsEdN4WcBX5Onv9GJ:-NhjsEdOEAkLOe8Enad_:b-xxmrzm) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java#L29)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @FieldNameConstants(innerTypeName = "DistinctProjectsPerAccountKeys")
> public class DistinctProjectsPerAccount {
> ```

These classes are not audit entities. These are entities related to metrics.

So, we can have a package io.harness.metrics
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/UniqueLoginsPerAccount.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjsGDwBy0OvbvId4KK:-NhjsGDwBy0OvbvId4KL:b-xxmrzm) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/UniqueLoginsPerAccount.java#L27)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @FieldNameConstants(innerTypeName = "UniqueLoginsPerAccountKeys")
> public class UniqueLoginsPerAccount {
> ```

These classes are not audit entities. These are entities related to metrics.

So, we can have a package io.harness.metrics
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java` line 12 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjsape9CtRXhk7IDyz:-Nhjsapf31HqtC3pwcoq:b6ym2yw) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java#L12)):*
> ```Java
> import io.harness.metrics.AutoMetricContext;
> 
> public class ProjectAuditMetricContext extends AutoMetricContext {
> ```

AccountActivityMetricContext
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjtSmW1MIDRE23FX5c:-NhjtSmW1MIDRE23FX5d:b8u1qjt) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java#L24)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class ProjectAuditMetricsServiceImpl {
> ```

AccountActivityMetricsServiceImpl
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java` line 25 at r3](https://reviewable.io/reviews/harness/harness [...]

2023-10-30 21:05 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 23 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AccountAuditMetricsTrackerRepository.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjuDzK0TTdsMeJAUZk:-Ni1L2T1-o-1NxydDpOW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AccountAuditMetricsTrackerRepository.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think we can avoid defining repository here. Just directly use MongoTemplate
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AccountAuditMetricsTrackerRepositoryCustom.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhju1_4EQPrL8L5vyYp:-Ni1L3ZPAwpqaJnfopvp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AccountAuditMetricsTrackerRepositoryCustom.java#L18)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think we can avoid defining repository here. Just directly use MongoTemplate
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AccountAuditMetricsTrackerRepositoryCustomImpl.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjtoCo2KAMajtw5LKV:-Ni1L4zn8rfQKgPn7AHk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AccountAuditMetricsTrackerRepositoryCustomImpl.java#L22)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the purpose of secondary and analytics. They don't seem to be used here.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjwJmU7bvICoU09MFy:-Ni1LAacDhFwqrB3xVoz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java#L27)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

AccountActivityMetricsPublisherJob
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjvyfe9BSY0CMbTFPZ:-Ni1L5aa5MPjWcZ8I_06:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java#L31)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can directly inject HTemplate here
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjw9J-8SNFCqTLKVRH:-Ni1L5wMBLrH23gj6AVa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java#L32)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

You should write like

if (shouldPublishMetrics()) {
  publishMetrics();
}
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjwOD27Ox_WXJr3meG:-Ni1LAExD9JQzp3Viojh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java#L43)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Instant.now()
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjwQ4_-yx1LDmtk5L2:-Ni1LB_27NGcTG0OZjgJ:b-ngurpq) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AuditMetricsJob.java#L44)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this be endTime of previous Iteration
</blockquote></details>

The data might not be perfectly consistent, but all we need is a rough estimate to get a sense of how it's being used. We could make it more consistent, but that would mean collecting data more frequently to prevent any discrepancies from causing delays. 
___
*[`platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhju_0T5O7hsuB1oufd:-Ni1KtOg7uOd7-y3-j6-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml#L1)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Account Activity Metrics
</blockquote></details>

Done.
___
*[`platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml` line 2 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-Nhjub8vCbVXlXNOPcCC:-Ni1KuDw7pRb_KqT4uEt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml#L2)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

account_activity_metrics
</blockquote></details>

Done.
___
*[`platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjudTq6boG3ZxXf-yU:-Ni1KvDJDPh7_CMGZkjF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml#L3)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

account_activity_metrics_group
</blockquote></details>

Done.
___
*[`platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml` line 5 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjufWQ1qbupRKPTfaG:-Ni1L0uA80KzRiMexEKx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/service/src/main/resources/metrics/metricDefinitions/account_audit_metrics.yaml#L5)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should perhaps split it into 2 separate metrics

active_projects
unique_login [...]

2023-10-31 12:19 UTC, nishantsaini20 submitted a review, later dismissed
> Reviewed 3 of 15 files at r1, 18 of 20 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 21 file(s) to review. 1 change requests. 12. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-31 12:41 UTC, ankit-harness requested changes
> Reviewed 1 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 20 file(s) to review. 1 change requests. 12. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/54613#-Ni4jXmHCSy2Rzj3k9ud:-Ni4jXmHCSy2Rzj3k9ue:b-nkvp0t) ([raw file](https://github.com/harness/harness-core/blob/c417b1106e7b96d268864f5967a2faf7d57ea452/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L42)):*
> ```Java
>   @Inject AccountClient accountClient;
>   @Inject AuditService auditService;
>   @Inject AuditRepositoryCustom auditRepository;
> ```

We should avoid exposing auditRepository directly outside of service layer


<!-- Sent from Reviewable.io -->

2023-10-31 13:01 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 20 file(s) to review. 1 change requests. 14. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceSetup.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjvhuUEExogXl78j6h:-Ni4oi4D9PPpmfe-hBOM:bgvs6h8) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceSetup.java#L106)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we use same pattern as environment.lifecycle().manage(injector.getInstance(AuditAccountSyncService.class)); for consistency
</blockquote></details>

will fix
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjsEdN4WcBX5Onv9GJ:-Ni4mfXN-JrZodYZ_CZL:brw2wn7) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/DistinctProjectsPerAccount.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

These classes are not audit entities. These are entities related to metrics.

So, we can have a package io.harness.metrics
</blockquote></details>

moved to a diff package 


<!-- Sent from Reviewable.io -->

2023-10-31 13:05 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 20 file(s) to review. 1 change requests. 15. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/54613#-Ni4jXmHCSy2Rzj3k9ud:-Ni4pc4z-Xr2aySbgXD4:b-xnlny6) ([raw file](https://github.com/harness/harness-core/blob/c417b1106e7b96d268864f5967a2faf7d57ea452/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L42)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should avoid exposing auditRepository directly outside of service layer
</blockquote></details>

will do it through service layer


<!-- Sent from Reviewable.io -->

2023-11-02 05:11 UTC, sahibaHarness commented
trigger pmd

2023-11-02 05:56 UTC, sahibaHarness commented
trigger uts

2023-11-02 06:16 UTC, ankit-harness requested changes
> Reviewed 14 of 20 files at r4, 1 of 2 files at r5, 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDdojA81AhHbyyo4Xj:-NiDdojA81AhHbyyo4Xk:b-o7tjn) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java#L40)):*
> ```Java
>   void deleteAuditInfo(String accountId);
> 
>   Map<String, Integer> getUniqueLoginCountPerAccountId(List<String> accountIds, Instant startTime, Instant endTime);
> ```

Can we make this method generic by having action as an input

action would be Action.LOGIN and Action.LOGIN2FA for our use-case
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDeyiY-T4jGFwW3FGo:-NiDeyiY-T4jGFwW3FGp:b-ywpzfx) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L63)):*
> ```Java
>     mongoTemplate.save(accountActivityMetricsTracker);
>     try (ResponseTimeRecorder ignore1 = new ResponseTimeRecorder(
>              "Account Activity metrics sent for unique project activity and unique logins for accounts. startTime:"
> ```

Account Activity metrics sent for active projects and unique logins.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 81 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDf8352TpWqPu88bM9:-NiDf8352TpWqPu88bMA:bj4ttd4) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L81)):*
> ```Java
>             auditService.getUniqueLoginCountPerAccountId(accountIds, startTime, endTime);
> 
>         try (ResponseTimeRecorder ignore2 = new ResponseTimeRecorder(
> ```

Any reason to log batch wise timing? Might be unnecessary. This would be in milliseconds.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherService.java` line 21 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDegXD6HlkWtLwFGrT:-NiDegXE5TYNxOmdnXom:b-h1agjm) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherService.java#L21)):*
> ```Java
> 
>   final ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor(
>       new ThreadFactoryBuilder().setNameFormat("account-activity-metrics-thread").build());
> ```

account-activity-metrics-publisher-thread
___
*[`platform-service/service/src/main/resources/metrics/metricDefinitions/account_activity_metrics.yaml` line 6 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDeSMb3Ttb17D_71WF:-NiDeSMb3Ttb17D_71WG:b162qtg) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/service/src/main/resources/metrics/metricDefinitions/account_activity_metrics.yaml#L6)):*
> ```YAML
> metrics:
>   - metricName: account_activity_metrics
>     metricDefinition: Number of unique active projects & unique project logins in an account
> ```

unique project logins?
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjtYj15mm5crDbWfXv:-NiDdek32uwc81Ps1J2G:b-vk5qwv) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

recordMetrics
</blockquote></details>

Change the method name. Metrics are not just for active projects
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/54613#-NhjtWe41NhJbe5dWneM:-NiDdkX4DXitNTgISZa3:b-vk5qwv) ([raw file](https://github.com/harness/harness-core/blob/f9bb9e8ef00fa30fe4ca3e38fa00620e625411fb/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java#L36)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

recordMetrics
</blockquote></details>

Change the method name. Metrics are not just for active projects


<!-- Sent from Reviewable.io -->

2023-11-02 06:49 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDdojA81AhHbyyo4Xj:-NiDgjGd9pl_WLOIgJpw:b-u5uw) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we make this method generic by having action as an input

action would be Action.LOGIN and Action.LOGIN2FA for our use-case
</blockquote></details>

I'm already formulating for these two with in the criteria. Making the function generic now.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 81 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDf8352TpWqPu88bM9:-NiDhKkI1Sy60XvqQtFb:b-kbwn9b) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L81)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason to log batch wise timing? Might be unnecessary. This would be in milliseconds.
</blockquote></details>

It may help us track how many accounts we successfully sent the metrics for. But makes sense; removing the recorder.


<!-- Sent from Reviewable.io -->

2023-11-02 07:04 UTC, sahibaHarness commented
trigger uts

2023-11-02 08:35 UTC, sahibaHarness commented
trigger ut3,ut5,ut6,ut7,ut9

2023-11-02 08:52 UTC, sahibaHarness commented
trigger uts

2023-11-02 08:58 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 10 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 48 at r8](https://reviewable.io/reviews/harness/harness-core/54613#-NiEF5Tq-1MWUXCu-QGe:-NiEF5Tq-1MWUXCu-QGf:b-58y3ns) ([raw file](https://github.com/harness/harness-core/blob/484459a8d79c694de69303cb58add3341a251351/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L48)):*
> ```Java
>   public void run() {
>     if (shouldPublishMetrics()) {
>       publishMetrics();
> ```

lets add a try catch here, this job would run once in 24 hours, os if it fails we should log proper exception
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 97 at r8](https://reviewable.io/reviews/harness/harness-core/54613#-NiEDz3UCe_n6TKMU_gn:-NiEDz3UCe_n6TKMU_go:b-m6rk1i) ([raw file](https://github.com/harness/harness-core/blob/484459a8d79c694de69303cb58add3341a251351/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L97)):*
> ```Java
> 
>   private Boolean shouldPublishMetrics() {
>     return mongoTemplate.findOne(getQueryForEntryInLast24Hours(), AccountActivityMetricsTracker.class) == null;
> ```

we should return TRUE is there is at least 1 activity in last 24 hours, right? this condition seems wrong.


<!-- Sent from Reviewable.io -->

2023-11-02 09:09 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 10 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 48 at r8](https://reviewable.io/reviews/harness/harness-core/54613#-NiEF5Tq-1MWUXCu-QGe:-NiEHKtYEbLLFbCjie5Q:b-8jyfjv) ([raw file](https://github.com/harness/harness-core/blob/484459a8d79c694de69303cb58add3341a251351/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L48)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

lets add a try catch here, this job would run once in 24 hours, os if it fails we should log proper exception
</blockquote></details>

If a job fails to run on one pod it will be pick by other pod to get completed. We can track executions with ResponseTimeRecorder ; more over we dont want data to be strictly consistent. 
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java` line 97 at r8](https://reviewable.io/reviews/harness/harness-core/54613#-NiEDz3UCe_n6TKMU_gn:-NiEGr968sxSrtYcZKrm:b-tu5q9e) ([raw file](https://github.com/harness/harness-core/blob/484459a8d79c694de69303cb58add3341a251351/platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherJob.java#L97)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

we should return TRUE is there is at least 1 activity in last 24 hours, right? this condition seems wrong.
</blockquote></details>

no it's a negation check; if it returns true with null then we process to send metrics


<!-- Sent from Reviewable.io -->

2023-11-02 09:13 UTC, kapil-harness approved these changes
> Reviewed 2 of 15 files at r1, 12 of 20 files at r4, 1 of 6 files at r6, 1 of 1 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-02 10:12 UTC, sahibaHarness commented
trigger uts

2023-11-02 10:32 UTC, sahibaHarness commented
trigger uts

2023-11-02 11:47 UTC, sahibaHarness commented
trigger ut0,ut1,ut2,ut9,ut7

2023-11-02 12:37 UTC, sahibaHarness commented
trigger ut9,ut7

2023-11-02 18:17 UTC, sahibaHarness commented
trigger uts

2023-11-03 02:43 UTC, ankit-harness requested changes
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDdojA81AhHbyyo4Xj:-NiI2Qon3jCVxrCfx98p:bf3kow6) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java#L40)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

I'm already formulating for these two with in the criteria. Making the function generic now.
</blockquote></details>

You will need to change the method name also if we are doing that : getUniqueActionCount


<!-- Sent from Reviewable.io -->

2023-11-03 02:47 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDdojA81AhHbyyo4Xj:-NiI3cJaC_XCy_V2upH0:b-kazdt3) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

You will need to change the method name also if we are doing that : getUniqueActionCount
</blockquote></details>

But currently the actions have been hard coded as exclusively LOGINS; We can take this change up if when we include other actions?


<!-- Sent from Reviewable.io -->

2023-11-03 02:58 UTC, sahibaHarness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java` line 40 at r7](https://reviewable.io/reviews/harness/harness-core/54613#-NiDdojA81AhHbyyo4Xj:-NiI6YJG0UrS9AK7NqTK:b2kp9p5) ([raw file](https://github.com/harness/harness-core/blob/0925f9ce61150eaa3d594509848b4ef65cae70ac/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/AuditService.java#L40)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

But currently the actions have been hard coded as exclusively LOGINS; We can take this change up if when we include other actions?
</blockquote></details>

Will fix in the following PR 


<!-- Sent from Reviewable.io -->

2023-11-03 02:59 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54613#-:-NiI6h_y4x97zfqEOx-S:bnfp4nl)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-11-03 02:59 UTC, merged