feat: [PL-41254]: Syncing accounts which got updated in last 60 seconds]
harness/harness-core pull request #54630
Opened 2023-10-25 14:43 UTC by Ashutosh2724

## Describe your changes

Earlier, accounts were synced to the Admin Portal with a delay of around 30 minutes. We have modified the delay to around 1 minute. Accounts that were updated in the last minute are fetched from the manager and updated in the local MongoDB of Admin Portal. Added unit tests as well for the same.

Tests that we ran:

-  Changed lastUpdatedAt field for 3 accounts in local->harness->accounts to within 30 seconds. Ran the scheduler and verified that the account got updated in local->admintool->accounts
-  Changed some attributes for some accounts in local->harness->accounts and verified that these are reflected in
local->admintool->accounts

We verified that the query is using the index:
```
"winningPlan" : {
            "stage" : "FETCH",
            "inputStage" : {
                "stage" : "IXSCAN",
                "keyPattern" : {
                    "lastUpdatedAt" : 1.0
                },
                "indexName" : "lastUpdatedAt_1",
                "isMultiKey" : false,
                "multiKeyPaths" : {
                    "lastUpdatedAt" : [

                    ]
                },
                "isUnique" : false,
                "isSparse" : false,
                "isPartial" : false,
                "indexVersion" : 2.0,
                "direction" : "forward",
                "indexBounds" : {
                    "lastUpdatedAt" : [
                        "(1698923319249.0, inf.0]"
                    ]
                }
            }
        }

```

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/54630)

2023-10-25 14:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=54630) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=54630) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=54630) it.</sub>

2023-10-26 04:32 UTC, ashishsanodia-harness commented
*[`.vscode/settings.json` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/54630#-NheFCex6TO9HGAgjvE7:-NheFCey89K1sEWjrruL:bdfrdvi) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/.vscode/settings.json#L2)):*
> ```JSON
> {
>     "java.compile.nullAnalysis.mode": "automatic"
> ```

Why this file?


<!-- Sent from Reviewable.io -->

2023-10-26 04:32 UTC, ashishsanodia-harness commented
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java` line 243 at r1](https://reviewable.io/reviews/harness/harness-core/54630#-NheFJW-CfR2v_j-NuLw:-NheFJW-CfR2v_j-NuLx:b220s6e) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java#L243)):*
> ```Java
> 
>   @Override
>   public List<AccountSummary> getAccountSummariesByAccounts(List<String> accountIds) {
> ```

Where this method is being used?


<!-- Sent from Reviewable.io -->

2023-10-26 04:34 UTC, ashishsanodia-harness commented
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 203 at r1](https://reviewable.io/reviews/harness/harness-core/54630#-NheFRBbEsMDXwXb64u-:-NheFRBbEsMDXwXb64u0:b9vlp4q) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L203)):*
> ```Java
>   @GET
>   @Path("get-recent-updates-account")
>   public RestResponse<List<AccountSummary>> getRecentAccountUpdates() {
> ```

Why this 30 seconds logic is harcoded? There is no existing method which can return account sorted by updated time?


<!-- Sent from Reviewable.io -->

2023-10-26 04:35 UTC, ashishsanodia-harness commented
Update PR description with change details and what all you have tested. Also add unit tests to cover flows which you have changed

2023-10-26 04:56 UTC, ashishsanodia-harness commented
Also commit message are not compliant. Don't you have git pre-commit hook installed in local?

2023-10-26 09:54 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/resources/AdminAccountResource.java
> +      long thirtySecondsAgo = currentTime - 30*1000*60;
TimeUnit.MILLISECONDS.convert(30, TimeUnit.SECONDS);

2023-10-26 10:00 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
> +            .filter("lastUpdatedAt >", timestamp)
nit: instead of filter use field

2023-10-26 10:05 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/resources/AdminAccountResource.java
> +        updatedAccountIds.add(account.getUuid());
List<String> accountIds =
        adminAccountService.getUpdatedAccounts(thirtySecondsAgo).stream().map(UuidAware::getUuid).collect(toList());

2023-10-26 10:06 UTC, sahibaHarness commented on 400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java
> +    for (String id : accountIds) {
make id -> accountId

2023-10-26 10:14 UTC, sahibaHarness commented on 400-rest/src/main/java/software/wings/beans/Account.java
> +    public  static  final String lastUpdatedAt = "lastUpdatedAt";
What is this being used for? Why it it defined as string? 
Why aren't we using lastUpdatedAt that is already there?

2023-10-27 05:53 UTC, niketan-nath commented on 400-rest/src/main/java/software/wings/resources/AdminAccountResource.java
> -
Let's restore unnecessary changes.

2023-10-27 05:54 UTC, niketan-nath commented on 400-rest/src/main/java/software/wings/resources/AdminAccountResource.java
> +
Let's follow the spacing pattern and have 1 line between 2 APIs, above and below.

2023-10-27 05:54 UTC, niketan-nath commented on 400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java
> +  public List<AccountSummary> getAccountSummariesByAccounts(List<String> accountIds) {
```suggestion
  public List<AccountSummary> getAccountSummariesByAccountIds(List<String> accountIds) {
```

2023-10-27 05:55 UTC, niketan-nath commented on 400-rest/src/main/java/software/wings/beans/Account.java
> +    public  static  final String lastUpdatedAt = "lastUpdatedAt";
Let's remove unnecessary spaces in between words.

2023-10-27 05:57 UTC, niketan-nath commented on 400-rest/src/main/java/software/wings/service/intfc/AccountService.java
>  }
Add a new line at EOF

2023-10-27 05:58 UTC, niketan-nath commented on 990-commons-test/src/main/java/io/harness/rule/OwnerRule.java
> +                  .put(ASHUTOSH_TRIPATHI, defaultUserInfo(ASHUTOSH_TRIPATHI).slack("U05R3PM8402").team(PL).build())
Let's format this line to remove extra spaces.

2023-10-27 05:59 UTC, niketan-nath commented on 400-rest/src/test/java/software/wings/resources/AdminAccountResourceTest.java
> +    List<AccountSummary> expectedAccountSummaries = Arrays.asList(accountSummary);
`updatedAccountSummaries` in place of `expectedAccountSummaries`?

2023-10-27 06:00 UTC, niketan-nath commented on 400-rest/src/test/java/software/wings/resources/AdminAccountResourceTest.java
> +  @Test
Add an empty line in between tests.

2023-10-27 07:20 UTC, ankit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54630)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java` line 83 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-Nhjyc3X1s_Vu4rskMwy:-Nhjyc3X1s_Vu4rskMwz:b-qnvk2o) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java#L83)):*
> ```Java
>   Account createGlobalDelegateAccount(Account account, String adminUserEmail);
> 
>   List<Account> getUpdatedAccounts(long timestamp);
> ```

getAccountsUpdatedSinceTimestamp
___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-NhjyfwnALKxZDDvbf1J:-NhjyfwnALKxZDDvbf1K:bvjspyg) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java#L85)):*
> ```Java
>   List<Account> getUpdatedAccounts(long timestamp);
> 
>   List<AccountSummary> getAccountSummariesByAccounts(List<String> accountIds);
> ```

getAccountSummaries
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 199 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-Nhk-06MAVTS_PviDrSO:-Nhk-06MAVTS_PviDrSP:beq7gpt) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L199)):*
> ```Java
> 
>   @GET
>   @Path("get-recent-updates-account")
> ```

This REST API name is too verbose. Lets follow REST conventions here
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 200 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-NhjzquQ7OVFqqTcsuma:-NhjzquQ7OVFqqTcsumb:b-ggecuv) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L200)):*
> ```Java
>   @GET
>   @Path("get-recent-updates-account")
>   public RestResponse<List<AccountSummary>> getRecentAccountUpdates() {
> ```

getUpdatedAccounts(long fromTimestamp)
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2528 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-NhjzSqK8XcXD5Jx0ADc:-NhjzSqK8XcXD5Jx0ADd:b-ed734k) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2528)):*
> ```Java
>   @Override
>   public List<Account> getByLastUpdated(long timestamp) {
>     return wingsPersistence.createQuery(Account.class).field(AccountKeys.lastUpdatedAt).greaterThan(timestamp).asList();
> ```

Is there index on lastUpdatedAt field


<!-- Sent from Reviewable.io -->

2023-11-03 04:28 UTC, niketan-nath commented
/rebase

2023-11-03 07:04 UTC, niketan-nath reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54630)* status: 9 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java` line 83 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-Nhjyc3X1s_Vu4rskMwy:-NiIxbme58N2psfZ8xmS:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java#L83)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getAccountsUpdatedSinceTimestamp
</blockquote></details>

Done
___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-NhjyfwnALKxZDDvbf1J:-NiIxl6SDOLJR5FBaHGi:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountService.java#L85)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getAccountSummaries
</blockquote></details>

Done
___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java` line 243 at r1](https://reviewable.io/reviews/harness/harness-core/54630#-NheFJW-CfR2v_j-NuLw:-NiIygC37hZ5qjl2I56X:b-y1kjvl) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java#L243)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

Where this method is being used?
</blockquote></details>

This method is being used to get account summaries for accounts that got updated recently. It is being used in AdminAccountResource
___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/54630#gh-1372916194:-NiIymLwDPSCJfHRIacE:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/400-rest/src/main/java/io/harness/datahandler/services/AdminAccountServiceImpl.java#L245)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

make id -> accountId
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 940 at r2](https://reviewable.io/reviews/harness/harness-core/54630#gh-1374102669:-NiIyKppBv0V6xnrU18f:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f3e87b31e05a88408d45c80803c6d51d9cf32638/400-rest/src/main/java/software/wings/beans/Account.java#L940)):*
<details><summary><i>Previously, niketan-nath (Niketan Nath) wrote…</i></summary><blockquote>

Let's remove unnecessary spaces in between words.
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 203 at r1](https://reviewable.io/reviews/harness/harness-core/54630#-NheFRBbEsMDXwXb64u-:-NiIz7qa0CFzAmeqSHP1:b-v506ji) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L203)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

Why this 30 seconds logic is harcoded? There is no existing method which can return account sorted by updated time?
</blockquote></details>

We want all accounts that got updated recently and want to update them in the Admin Portal DB. The order of accounts doesn't matter for our use-case. We have added an index as well for the accounts collection based on the lastUpdatedAt field.
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/54630#gh-1372900791:-NiIzVuo2xiZ8Fcr3Cqu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L205)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

TimeUnit.MILLISECONDS.convert(30, TimeUnit.SECONDS);
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 0 at r2](https://reviewable.io/reviews/harness/harness-core/54630#gh-1374101590:-NiIz3Fn2QEXlgyJEAMc:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f3e87b31e05a88408d45c80803c6d51d9cf32638/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L0)):*
<details><summary><i>Previously, niketan-nath (Niketan Nath) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/harness/harness-core/pull/54630#discussion_r1374101590) to the right spot — sorry!)*

Let's restore unnecessary changes.
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 203 at r2](https://reviewable.io/reviews/harness/harness-core/54630#gh-1374101958:-NiIyV0Q3YANNCDwykab:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f3e87b31e05a88408d45c80803c6d51d9cf32638/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L203)):*
<details><summary><i>Previously, niketan-nath (Niketan Nath) wrote…</i></summary><blockquote>

Let's follow the spacing pattern and have 1 line between 2 APIs, above and below.
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/resources/AdminAccountResource.java` line 199 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-Nhk-06MAVTS_PviDrSO:-NiIyW1O3nkBs6TQGyWO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/software/wings/resources/AdminAccountResource.java#L199)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This REST API name is too verbose. Lets follow REST conventions here
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2529 at r1](https://reviewable.io/reviews/harness/harness-core/54630#gh-1372909186:-NiIzfFcDonYUrXCnb-E:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/af99308525f621471e00685399f476b7564e4c0c/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2529)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

nit: instead of filter use field and gt to evaluate
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2528 at r3](https://reviewable.io/reviews/harness/harness-core/54630#-NhjzSqK8XcXD5Jx0ADc:-NiIzg7r8GD1lloPWEUI:b-dkkubm) ([raw file](https://github.com/harness/harness-core/blob/d7c6e817be17deec27761cb35758ee349ca9aecc/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2528)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is there index on lastUpdatedAt field
</blockquote></details>

Added the index
___
*[`400-rest/src/main/java/software/wings/service/intfc/AccountService.java` line 312 at r2](https://reviewable.io/reviews/harness/harness-core/54630#gh-1374103825:-NiIzhi_4-IjFuBsAC6u:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f3e87b31e05a88408d45c80803c6d51d9cf32638/400-rest/src/main/java/software/wings/service/intfc/AccountService.java#L312)):*
<details><summary><i>Previously, niketan-nath (Niketan Nath) wrote…</i></sum [...]

2023-12-19 19:44 UTC, bot2-harness commented
This PR has been automatically closed due to inactivity.

2023-12-19 19:44 UTC, closed without merging