[fix]: [CDS-82579]: Fix url artifactory generic artifact
harness/harness-core pull request #54662
Opened 2023-10-26 05:59 UTC by Abhishek-CDC

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-26 06:03 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +                                    .withArtifactPath(artifact)
adding repoName to artifactPath because referred method 'getArtifactListHelper' in line 504 has logic to search substring with value equal to repoName and delete it.
The original path doesn't contain repoName in it so if directory has any substring matching repoName it would be deleted.
Adding repoName to avoid this.

2023-10-26 06:04 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +    path = path.substring(1);
Because path has leading '/' in it.

2023-10-26 06:06 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +    path = path.substring(1);
This is not observed because it is not consumed anywhere.
This is to avoid issues if consuming these values later.

2023-10-26 06:06 UTC, Abhishek-CDC commented
trigger uts

2023-10-26 07:37 UTC, puthrayaharness approved these changes

2023-10-26 11:15 UTC, Abhishek-CDC commented
trigger ut1, ut3, ut7

2023-10-26 11:29 UTC, sourabh-awashti approved these changes
LGTM

2023-10-26 12:27 UTC, rafaelmart1ns approved these changes
lgtm

2023-10-26 14:10 UTC, naman-goenka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
> +    path = path.substring(1);
Also please add a null check to avoid npe

2023-10-26 14:16 UTC, naman-goenka commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
>                                      .build();
Why are we again doing `.substring(1)` in getArtifactListHelper

2023-10-27 05:26 UTC, Abhishek-CDC commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
>                                      .build();
because after omitting repoName there will be a leading '/'

2023-10-27 10:36 UTC, Abhishek-CDC commented
trigger uts

2023-10-27 13:04 UTC, Abhishek-CDC commented
trigger ut3, ut9

2023-10-30 01:58 UTC, Abhishek-CDC commented
trigger uts

2023-10-30 04:35 UTC, Abhishek-CDC commented
trigger ut3, ut9, ut7

2023-10-30 04:35 UTC, Abhishek-CDC commented
trigger ut3, ut8, ut7

2023-10-30 06:05 UTC, Abhishek-CDC commented
trigger ut3, ut9, ut7

2023-10-30 08:13 UTC, Abhishek-CDC commented
trigger ut3, ut7, ut9

2023-10-30 09:26 UTC, Abhishek-CDC commented
trigger uts

2023-10-31 01:23 UTC, Abhishek-CDC commented
trigger uts

2023-10-31 05:24 UTC, naman-goenka approved these changes

2023-10-31 11:03 UTC, Abhishek-CDC commented
trigger uts

2023-10-31 13:27 UTC, puthrayaharness commented
/rebase

2023-10-31 13:35 UTC, puthrayaharness commented
trigger uts

2023-11-02 04:34 UTC, Abhishek-CDC commented
trigger uts

2023-11-02 11:51 UTC, Abhishek-CDC commented
trigger uts

2023-11-03 03:37 UTC, Abhishek-CDC commented
trigger ut5, ut6, ut7, ut8, ut9

2023-11-03 07:36 UTC, puthrayaharness requested changes

2023-11-03 07:36 UTC, puthrayaharness commented on 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java
>                                      .withUiDisplayName("Build# " + path)
Do we need to change here?

2023-11-03 09:36 UTC, puthrayaharness approved these changes

2023-11-03 09:47 UTC, Abhishek-CDC commented
trigger review

2023-11-03 09:49 UTC, merged