[feat]:[CDS-79319]: Adding uts to increase code coverage
harness/harness-core pull request #54676
Opened 2023-10-26 10:03 UTC by vinit1968

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-26 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=54676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=54676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=54676) it.</sub>

2023-10-26 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=54676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=54676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=54676) it.</sub>

2023-10-26 10:55 UTC, vinit1968 commented
trigger uts

2023-10-26 12:11 UTC, vinit1968 commented
trigger messagecheck

2023-10-27 18:19 UTC, vinit1968 commented
trigger uts

2023-10-27 18:22 UTC, vinit1968 commented
trigger uts

2023-10-30 05:54 UTC, abhinavmittal-harness requested changes
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54676)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreatorTest.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/54676#-Nhz8SjlEHeEXh0pa1hZ:-Nhz8SjlEHeEXh0pa1h_:bm9qzy7) ([raw file](https://github.com/harness/harness-core/blob/ae4294ac281024bdd78f00e987479440e7bda865/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreatorTest.java#L57)):*
> ```Java
>   @Owner(developers = OwnerRule.VINIT_KUMAR)
>   @Category(UnitTests.class)
>   public void testCreatePlanForField() {
> ```

Might want to consider a diff method name as you are testing a negative case


<!-- Sent from Reviewable.io -->

2023-10-30 06:03 UTC, Abhishek-CDC commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/ApprovalInstanceServiceTest.java
> +    Optional<HarnessApprovalActivity> result = harnessApprovalInstance.fetchLastApprovalActivity();
What we are trying to validate here?
I think it is mocking a method and validating the same mocked method

2023-10-30 06:03 UTC, Abhishek-CDC commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/ApprovalInstanceServiceTest.java
> +    Optional<HarnessApprovalActivity> result = harnessApprovalInstance.fetchLastApprovalActivity();
same as below

2023-10-30 06:15 UTC, Abhishek-CDC commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/harness/beans/ApproversDTOTest.java
> +    return Approvers.builder()
In place of having these methods we can defined variable in test and instantiate as this will be used one time only and for one test

2023-10-30 06:23 UTC, Abhishek-CDC commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreatorTest.java
> +    Mockito.when(stepElement.getServiceNowCreateStepInfo())
We don't need this mock.
This will never get called. With below mock line we are throwing exception

2023-10-30 06:26 UTC, Abhishek-CDC commented on pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/servicenow/create/ServiceNowCreateStepPlanCreatorTest.java
> +        .thenReturn(getServiceNowCreateStepInfo(
These mocks are not required.
We are throwing exception with below mock line

2023-12-19 19:44 UTC, bot2-harness commented
This PR has been automatically closed due to inactivity.

2023-12-19 19:44 UTC, closed without merging