fix: [CDS-78563] Replace release identifier for instance sync if already exists
harness/harness-core pull request #54671
Opened 2023-10-26 08:34 UTC by alebuh

## Describe your changes
When HELM_STEADY_STATE_CHECK_1_16 is disabled containerServiceName will have actual value and the release identifier will look something like this:
ReleaseIdentifert1( releaseName: release1, namespace: namespace1, containerServiceName: workloadName )
When HELM_STEADY_STATE_CHECK_1_16  is enabled containerServiceName will be null and look like this:
ReleaseIdentifert2( releaseName: release1, namespace: namespace1, containerServiceName: null )
After merging release identifiers only one should be present as they are part of the same release. We always should use latest one

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-26 08:53 UTC, alebuh commented
trigger uts

2023-10-26 08:55 UTC, alebuh commented
trigger messagecheck

2023-10-26 09:54 UTC, abhinavsingh1196 commented on 400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java
> +          && k8sNewIdentifier.isHelmDeployment() == (cgK8sReleaseIdentifier.isHelmDeployment())) {
will checkstyle or PMD check complain about the redundant braces around `cgK8sReleaseIdentifier.isHelmDeployment()`?

2023-10-26 09:55 UTC, abhinavsingh1196 commented on 400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java
> +          && k8sNewIdentifier.isHelmDeployment() == (cgK8sReleaseIdentifier.isHelmDeployment())) {
I see its passed :)

2023-10-26 09:55 UTC, abhinavsingh1196 approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54671)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-10-26 10:05 UTC, TarunUba1 approved these changes

2023-10-26 12:07 UTC, namantalaycha10 requested changes

2023-10-26 12:07 UTC, namantalaycha10 commented on 400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java
> +          && k8sNewIdentifier.getClusterName().equals(cgK8sReleaseIdentifier.getClusterName())
please do the null check before doing equal operation

2023-10-27 06:06 UTC, alebuh commented on 400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java
> +          && k8sNewIdentifier.getClusterName().equals(cgK8sReleaseIdentifier.getClusterName())
done

2023-10-27 06:14 UTC, alebuh commented
trigger uts

2023-10-27 06:46 UTC, abhinavsingh1196 submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54671)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-10-27 11:07 UTC, alebuh commented
trigger uts

2023-10-27 11:31 UTC, TarunUba1 approved these changes

2023-10-30 07:57 UTC, GoelPratyush99 approved these changes

2023-10-30 08:17 UTC, acasian-harness approved these changes

2023-10-30 10:39 UTC, abosii-harness approved these changes

2023-10-30 10:42 UTC, namantalaycha10 approved these changes
lgtm

2023-10-30 10:42 UTC, merged