[feat]: [CDS-77616]: Added validations in save/execution flow for scoping services to infra
harness/harness-core pull request #54764
Opened 2023-10-30 07:35 UTC by PragyeshMishra01

## Describe your changes
Added validations in save/execution flow for scoping services to infra
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-31 05:59 UTC, sribalij commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +        ParameterFieldHelper.getParameterFieldValue(environment.getInfrastructureDefinition());
Will this not be added as a part of `List<InfraStructureDefinitionYaml> infraList`?
Do we need to add it again?

2023-11-02 19:34 UTC, PragyeshMishra01 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +        ParameterFieldHelper.getParameterFieldValue(environment.getInfrastructureDefinition());
these are two different fields

2023-11-02 19:42 UTC, PragyeshMishra01 commented
trigger uts

2023-11-03 04:04 UTC, piyush-bhuwalka submitted a review, later dismissed

2023-11-03 04:52 UTC, tchaurasiya requested changes

2023-11-03 04:52 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java
> +            parameters.getInfraId().getValue());
can we test in case infra is <+input>/ or expression/not given(from yaml) ?

2023-11-03 04:52 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +  private void addFiltersForInfraScopedToServices(
nit: We should rename this method, It is not adding filters

2023-11-03 10:33 UTC, PragyeshMishra01 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +  private void addFiltersForInfraScopedToServices(
Done

2023-11-03 10:34 UTC, PragyeshMishra01 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java
> +            parameters.getInfraId().getValue());
yes, we have tested these cases, working fine

2023-11-03 10:37 UTC, PragyeshMishra01 commented
trigger uts

2023-11-03 11:17 UTC, PragyeshMishra01 commented
trigger ut6

2023-11-03 11:24 UTC, tchaurasiya approved these changes

2023-11-03 11:33 UTC, PragyeshMishra01 commented
trigger messagecheck

2023-11-03 11:36 UTC, piyush-bhuwalka approved these changes

2023-11-03 11:36 UTC, PragyeshMishra01 commented
trigger review

2023-11-03 11:42 UTC, yogesh-chauhan approved these changes
> Reviewed 2 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54764)* status: 6 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-03 11:45 UTC, merged