feat: [CDS-82814]: Adding Artifact Bundled Manifest for TAS deployment
harness/harness-core pull request #54770
Opened 2023-10-30 09:17 UTC by namantalaycha10

## Describe your changes
Adding Artifact Bundled Manifest files for TAS deployment 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-10-30 09:25 UTC, namantalaycha10 commented
trigger uts

2023-10-30 09:46 UTC, abhinavsingh1196 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/TasArtifactBundledManifest.java
> +  @Wither TasArtifactBundledArtifactType artifactType;
are any of these fields required? if so, we should annotate with NotEmpty or NotNull

2023-10-30 09:49 UTC, namantalaycha10 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/TasArtifactBundledManifest.java
> +  @Wither TasArtifactBundledArtifactType artifactType;
ack

2023-10-30 09:56 UTC, namantalaycha10 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/TasArtifactBundledManifest.java
> +  @Wither TasArtifactBundledArtifactType artifactType;
done

2023-10-30 10:01 UTC, namantalaycha10 commented
trigger uts

2023-10-30 10:15 UTC, abhinavsingh1196 approved these changes

2023-10-30 12:13 UTC, alebuh submitted a review, later dismissed

2023-10-30 12:15 UTC, acasian-harness submitted a review, later dismissed

2023-10-31 05:20 UTC, sribalij approved these changes

2023-10-31 07:37 UTC, vlica-harness commented
@namantalaycha10 don't we need to update the alias.txt?

2023-10-31 07:39 UTC, vlica-harness requested changes
@namantalaycha10  don't we need to update the alias.txt?

2023-10-31 09:07 UTC, namantalaycha10 commented
trigger uts

2023-10-31 09:52 UTC, namantalaycha10 commented
trigger uts

2023-10-31 09:54 UTC, namantalaycha10 commented
> @namantalaycha10 don't we need to update the alias.txt?

added the change

2023-10-31 11:10 UTC, vlica-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ArtifactBundleStore.java
> +    if (!ParameterField.isNull(gitStore.getArtifactPath())) {
This should be checked with product owner if it can be null and considered as the artifact will be taken from the artifactSource configuration

2023-11-02 05:19 UTC, namantalaycha10 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ArtifactBundleStore.java
> +    if (!ParameterField.isNull(gitStore.getArtifactPath())) {
sure

2023-11-02 05:25 UTC, namantalaycha10 commented
trigger uts

2023-11-02 05:52 UTC, namantalaycha10 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ArtifactBundleStore.java
> +    if (!ParameterField.isNull(gitStore.getArtifactPath())) {
i discussed with product manager, this will be mandatory field

2023-11-02 05:53 UTC, namantalaycha10 commented
trigger uts

2023-11-02 06:02 UTC, namantalaycha10 commented
trigger messagecheck

2023-11-02 06:35 UTC, namantalaycha10 commented
trigger ut8

2023-11-02 07:07 UTC, vlica-harness approved these changes

2023-11-02 12:11 UTC, namantalaycha10 commented
trigger review

2023-11-02 12:22 UTC, yogesh-chauhan approved these changes

2023-11-02 12:22 UTC, merged