feat [CDS-78336]: Adding logic to support folderpaths in k8s apply with manifest source
harness/harness-core pull request #54908
Opened 2023-11-02 06:42 UTC by TarunUba1

## Describe your changes
in case of folderpaths, the files are saved in root level of manifest directory.
we get all the valid filepaths in root directory in this case

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-02 09:43 UTC, TarunUba1 commented
trigger commonchecks

2023-11-02 10:15 UTC, TarunUba1 commented
trigger pmd, codebasehash, uts

2023-11-03 06:11 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
>      }
We should throw exception for the else case here. It will save us creating a delegate task just to throw exception later ```
throw NestedExceptionUtils.hintWithExplanationException(KubernetesExceptionHints.APPLY_NO_FILEPATH_SPECIFIED,
          KubernetesExceptionExplanation.APPLY_NO_FILEPATH_SPECIFIED,
          new KubernetesTaskException(KubernetesExceptionMessages.APPLY_NO_FILEPATH_SPECIFIED));
```

2023-11-03 06:15 UTC, TarunUba1 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
>      }
i thought that this case will not be possible. Sure will add this  condition

2023-11-03 06:17 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +                  && !StringUtils.equals(filename, values_filename)))) {
Can we use this and simplify the logic `io.harness.delegate.task.k8s.K8sTaskHelperBase#isValidManifestFile`

2023-11-03 06:21 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +      if (!new File(filename).exists()
Can re-use this `io.harness.filesystem.FileIo#checkIfFileExist`

2023-11-03 06:34 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +    Set<String> applyPathss = new HashSet<>(applyFilePaths);
Instead of using set you could have started with empty list and populate that list in the for loop
List<String> applyPathList = new ArrayList();
for (String filePath : finalFilePaths) {
  if () {
    if (!isThereFolder) {
 applyPathList.addAll(k8sTaskHelperBase.getFilesInFolderToApply(k8sApplyHandlerConfig.getManifestFilesDirectory(), filePath));
      isThereFolder = true;
    }
    applyPathList.add(filePath)
  }
}

2023-11-03 06:37 UTC, GoelPratyush99 approved these changes

2023-11-03 07:53 UTC, abhinavsingh1196 reviewed
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54908)* status: 1. unresolved discussions. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/54908#gh-1381191219:-NiJ1Mqq4X27n_T_hAFb:bcdkrvl) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java#L201)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

i thought that this case will not be possible. Sure will add this  condition
</blockquote></details>

nit: can create a method which does this, instead of if-elseif-else which is less readable



_Code snippet:_
```Java
void setFilePathsInRequest(applyRequestBuilder) {}
OR 
List<Filepath> getFilePathsForApply() {}
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java` line 261 at r1](https://reviewable.io/reviews/harness/harness-core/54908#-NiJ1uI18hgSHIGiU_JC:-NiJ1uI18hgSHIGiU_JD:bssw1de) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java#L261)):*
> ```Java
>               || StringUtils.endsWith(filename, yml_file_extension)
>                   && !StringUtils.equals(filename, values_filename)))) {
>         if (!isThereFolder) {
> ```

nit: rename to something better like `folderExists`
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java` line 270 at r1](https://reviewable.io/reviews/harness/harness-core/54908#-NiJ1zzo8TCbc229N6MJ:-NiJ1zzo8TCbc229N6MK:bxs3jvi) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java#L270)):*
> ```Java
>       }
>     }
>     return applyPathss;
> ```

nit: typo
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java` line 2454 at r1](https://reviewable.io/reviews/harness/harness-core/54908#-NiJ2H5w2gPVynH3Iydx:-NiJ2H5w2gPVynH3Iydy:b-lqzuyg) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java#L2454)):*
> ```Java
>   }
> 
>   public List<String> getFilesInFolderToApply(String manifestFilesDirectory, String folderPath) {
> ```

is this wrapping method required or can we directly call k8sTaskManifestValidator from apply request handler? would like to avoid additions to k8sTaskHelperBase
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/manifest/K8sTaskManifestValidator.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/54908#-NiJ8DLz8bhMAtB83cTP:-NiJ8DLz8bhMAtB83cTQ:ba2sc1r) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/manifest/K8sTaskManifestValidator.java#L111)):*
> ```Java
>   public List<String> getFilesToApplyInFolder(String manifestDirectory, String folderPath, Predicate<Path> fileFilter) {
>     Path manifestPath = Paths.get(manifestDirectory);
>     Set<String> listFiles = listFiles(manifestPath, fileFilter);
> ```

how will symlinks behave?
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sApplyRequestHandlerTest.java` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/54908#-NiJ8UzBEQjD_PjD2r4W:-NiJ8UzBEQjD_PjD2r4X:b3w7s2g) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sApplyRequestHandlerTest.java#L563)):*
> ```Java
>   }
> 
>   @Test
> ```

we should add UTs for negative cases like empty folder/missing file etc. ?


<!-- Sent from Reviewable.io -->

2023-11-06 05:19 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +      if (!new File(filename).exists()
throws exception, this works file for our case

2023-11-06 07:19 UTC, TarunUba1 commented
trigger uts

2023-11-06 07:20 UTC, TarunUba1 commented
i have added tests but sonar is not working correctly for those files for some reason

2023-11-06 07:29 UTC, abosii-harness requested changes

2023-11-06 07:29 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +      if (!new File(filename).exists() || !K8sTaskHelperBase.isValidManifestFile(filename)) {
If file doesn't exists then why we want to continue? exists will check for folder as well

2023-11-06 07:29 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +        folderExists = true;
Are we saying that user can provide a single folder path only? Any reason for this limitation?

2023-11-06 07:29 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/manifest/K8sTaskManifestValidator.java
> +    return sortFilesByBestMatch(listFiles, folderPath);
Any reason why we need to sort by best match here? Since the files that you list are already part of the folder, sort is not effective. Because of this sort you'll return only 8 files, is this the limitation that you to create? Then just limit it directly, this sort is expensive. Anyway, I don't see the reason why we would want to limit it

2023-11-06 07:29 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +  private Set<String> getApplyFilePathsForFolders(List<String> applyFilePaths, String manifestDirectory) {
Overall can you explain the reason behind this complexity? Check if the filePath is folder, list files and return? What are these checks?

2023-11-06 07:29 UTC, abosii-harness commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_K8S_APPLY_MANIFEST_FROM_SOURCE_NG("Provides Custom Manifest Source functionality in Apply Step", HarnessTeam.CDP);
Custom manifest source?

2023-11-07 08:33 UTC, TarunUba1 commented
trigger uts

2023-11-07 09:49 UTC, TarunUba1 commented
trigger uts

2023-11-07 09:55 UTC, TarunUba1 commented
for some reason sonarlint not picking up on tests i have created :(

2023-11-07 13:26 UTC, abhinavsingh1196 commented
Please provide a summary of all inputs which you have tested on this Apply step. We should test out various cases (if not done already) like:
- `folder1`, `folder2` 
- `folder1` , `folder1/subfolder1`, `file1`
- `folder1`, `folder2/symlink->folder3`, `file1`

2023-11-07 17:23 UTC, abosii-harness requested changes

2023-11-07 18:19 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java
> +              Collections.singletonList(filePath), gitStoreDelegateConfig.getGitConfigDTO());
1.as explained in desciption, this was creating temprory files previously which was leading to unable to download folders if files were defined before.
2. We never used to get filepaths as a bulk from code perspective, we called this function for each path specified
`    gitStoreDelegateConfig.getPaths().forEach(filePath
        -> commitIds.add(
            downloadFilesForFilePath(gitStoreDelegateConfig, filePath.replaceAll(regexStartSlash.pattern(), ""),
                executionLogCallback, directoryPath, isManifestSource)));`
                
    in code we never used to check if path alrady exist or not
    so for multiple files lets say n we used to call n time -> n^2 fileBatchresponse 
    now we are solving it to only get file for required filepath only once

2023-11-07 18:22 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetcherUtils.java
> +    if (relativize && !isManifestSource) {
isManifestSource you can consider as a boolean to keep the older part as it is and introducing new way to save git files for apply manifest source which will support multiple folders, 
We discussed this on call to create seperate function but introducing just a variable was solving this so did so

2023-11-07 18:25 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java
> +      LogCallback executionLogCallback, boolean isManifestSource) {
i can go forward with mayHaveMultipleFolders, to specify that a different route be taken

2023-11-08 05:15 UTC, TarunUba1 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54908)* status: 6 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/54908#gh-1381191219:-NihLRpt8Egd5YaKU9SM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java#L201)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: can create a method which does this, instead of if-elseif-else which is less readable
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/54908#gh-1381201974:-NihLUTd0qjsSBs1fbO4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java#L253)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Instead of using set you could have started with empty list and populate that list in the for loop
```
List<String> applyPathList = new ArrayList();
for (String filePath : finalFilePaths) {
  if () {
    if (!isThereFolder) {
 applyPathList.addAll(k8sTaskHelperBase.getFilesInFolderToApply(k8sApplyHandlerConfig.getManifestFilesDirectory(), filePath));
    }
    applyPathList.add(filePath)
    isThereFolder = true;
  }
}
```
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java` line 260 at r1](https://reviewable.io/reviews/harness/harness-core/54908#gh-1381193674:-NihLbbQ6mbBCoCwpKhk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java#L260)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Can we re-use this and simplify the logic `io.harness.delegate.task.k8s.K8sTaskHelperBase#isValidManifestFile`
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java` line 257 at r2](https://reviewable.io/reviews/harness/harness-core/54908#gh-1382870709:-NihLTp165GcGr81JLpS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3c83e4b0dfd9de0d3b4bb5c025cc0e4c3466020/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java#L257)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Overall can you explain the reason behind this complexity? Check if the filePath is folder, list files and return? What are these checks?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java` line 263 at r2](https://reviewable.io/reviews/harness/harness-core/54908#gh-1382866283:-NihLXFICfEiL-5B1lEo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3c83e4b0dfd9de0d3b4bb5c025cc0e4c3466020/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java#L263)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

If file doesn't exists then why we want to continue? exists will check for folder as well
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java` line 270 at r2](https://reviewable.io/reviews/harness/harness-core/54908#gh-1382866554:-NihLaf19K3qJVKu9g0g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3c83e4b0dfd9de0d3b4bb5c025cc0e4c3466020/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java#L270)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Are we saying that user can provide a single folder path only? Any reason for this limitation?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/manifest/K8sTaskManifestValidator.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/54908#-NiJ8DLz8bhMAtB83cTP:-NihLer2Ag0L4fCCCPVJ:b-yuelbd) ([raw file](https://github.com/harness/harness-core/blob/cf656b5d1fbd6b0d7e360648c34ca52c3112cd27/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/manifest/K8sTaskManifestValidator.java#L111)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

how will symlinks behave?
</blockquote></details>

not supported currently as with symlink we get dont get back a file with extension
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/manifest/K8sTaskManifestValidator.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/54908#gh-1382869642:-NihLkp-CsJuef15e8_Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3c83e4b0dfd9de0d3b4bb5c025cc0e4c3466020/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/manifest/K8sTaskManifestValidator.java#L118)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Any reason why we need to sort by best match here? Since the files that you list are already part of the folder, sort is not effective. Because of this sort you'll return only 8 files, is this the limitation that you to create? Then just limit it directly, this sort is expensive. Anyway, I don't see the reason why we would want to limit it
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/git/ScmFetchFilesHelperNGTest.java` line 444 at r5](https://reviewable.io/reviews/harness/harness-core/54908#-Nie1VkT9ASikIO1jXPj:-NihLoFeBNVYUFdYVwac:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ce2b52c544c02f644fa39d30db4ccb2494274ce4/930-delegate-tasks/src/test/java/io/harness/delegate/task/git/ScmFetchFilesHelperNGTest.java#L444)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

this file should be cleaned up as well?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskManifestValidatorTest.java` line 189 at r5](https://reviewable.io/reviews/harness/harness-core/54908#-Nie1i3773xvN21LzFaq:-NihLoyC08gYWjI5KwpV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ce2b52c544c02f644fa39d30db4ccb2494274ce4/930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskManifestValidatorTest.java#L189)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

same, cleanup these files as well using `FileIo.deleteFileIfExists` or `FileIo.deleteDirectoryAndItsContentIfExists`
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 945 at r2](https://reviewable.io/reviews/harness/harness-core/54908#gh-1382871262:-NihLqJZ6py93TdPnG4X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3c83e4b0dfd9de0d3b4bb5c025cc0e4c3466020/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L945)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Custom manifest source?
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 945 at r5](https://reviewable.io/reviews/harness/harness-core/54908#-Nie2-Vr1u3a7vyqcjgP:-NihLq_40YYLDD7wK_0i:b-j8k7t2) ([raw file](https://github.com/harness/harness-co [...]

2023-11-08 05:18 UTC, TarunUba1 commented
trigger uts

2023-11-08 05:24 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +    if (storeDelegateConfig instanceof LocalFileStoreDelegateConfig) {
need to add this logic cause harnessStore acts differently than github, all files from folders are already fetched and currently not a way to segregate, as we cannot have files with same identifier its safe to ues this

2023-11-08 06:05 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +    if (storeDelegateConfig instanceof LocalFileStoreDelegateConfig) {
if there is a need to fix how we save dataa regarding folders and files we can taake it up in another ticket

2023-11-08 06:19 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +    if (storeDelegateConfig instanceof LocalFileStoreDelegateConfig) {
current liability:
i have sent two folders but we only provide one folderpath.
we can have a folderpath to manifestfile mapping which can help.
The only problem will arise when we use filestore from account and project, -> files with same name with conflict
<img width="586" alt="Screenshot 2023-11-08 at 11 46 46 AM" src="https://github.com/harness/harness-core/assets/106597485/d97fcecb-3e98-4c14-99bd-408b31f54c85">

2023-11-08 06:35 UTC, TarunUba1 commented
trigger uts

2023-11-08 07:22 UTC, TarunUba1 commented
trigger ut7

2023-11-08 10:30 UTC, TarunUba1 commented
trigger uts

2023-11-08 11:49 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyStep.java
> +    if (k8sApplyStepParameters.getFilePaths() != null && k8sApplyStepParameters.getFilePaths().getValue() != null) {
We can use getParameterFieldValue(k8sApplyStepParameters.getFilePaths()) so simplify the if logic

2023-11-08 11:55 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +      String absoluteFilePath = Path.of(manifestDirectory, filePath).toString();
Can you verify for the case when we have Custom Remote store and the file path provided is absolute file path. Asking wrt this CFD https://harness.atlassian.net/browse/CDS-83443

2023-11-08 11:58 UTC, abosii-harness requested changes

2023-11-08 11:58 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +                destinationDir = new File(Paths.get(request.getDestinationDirectory(), filePath).toString());
mutating destinationDir in a loop may end up in some unexpected behaviour, if not now then in future. We shouldn't do this

2023-11-08 11:59 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> -
Lets keep the gap for readability of methods 👍

2023-11-08 12:24 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/apply/K8sApplyRequestHandler.java
> +      String absoluteFilePath = Path.of(manifestDirectory, filePath).toString();
No supporting custom remote store

2023-11-08 12:30 UTC, TarunUba1 commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +                destinationDir = new File(Paths.get(request.getDestinationDirectory(), filePath).toString());
ah it will definitely be a problem thanks was finding it will do that

2023-11-08 14:17 UTC, TarunUba1 commented
trigger uts

2023-11-08 14:28 UTC, GoelPratyush99 submitted a review, later dismissed

2023-11-09 05:38 UTC, GoelPratyush99 approved these changes

2023-11-09 05:39 UTC, TarunUba1 commented
trigger uts

2023-11-09 06:12 UTC, TarunUba1 commented
trigger ut9

2023-11-09 10:54 UTC, abosii-harness approved these changes

2023-11-09 11:23 UTC, TarunUba1 commented
trigger review

2023-11-09 11:26 UTC, merged