[fix]: [CDS-82232]: delegate selector hierarchy service step
harness/harness-core pull request #54903
Opened 2023-11-02 05:53 UTC by Abhishek-CDC

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-03 03:58 UTC, Abhishek-CDC commented
trigger smartchecks

2023-11-03 04:32 UTC, Abhishek-CDC commented
trigger smartchecks

2023-11-03 04:38 UTC, Abhishek-CDC commented
trigger uts

2023-11-03 07:48 UTC, Abhishek-CDC commented
trigger uts

2023-11-03 10:17 UTC, yogesh-chauhan requested changes

2023-11-03 10:17 UTC, yogesh-chauhan commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_DELEGATE_SELECTOR_PRECEDENCE("Follow delegate selector precedence in service/infra step", CDC),
Should we mention SERVICE/INFRA step in the name to avoid confusion ?

2023-11-03 10:17 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +        .selectors(selectors)
will setting both not cause confusion here ?

Can we pass TaskSelector from line number: 1224
by converting "Set<String> taskSelectors" to " List<TaskSelector> selectors" ?

2023-11-03 10:17 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java
> +    StepUtils.appendDelegateSelectors(emptyStepParameters, ctx);
can we fetch this from the very top i.e DeploymentStagePlanCreator and not send the PlanCreationContext down till this point ?

2023-11-03 10:17 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +          String serviceNodeId = addServiceNode(specField, planCreationResponseMap, stageNode, serviceNextNodeId, ctx);
don't we create Service and other children nodes in the above if block ?
"if (isGitopsEnabled(stageNode.getDeploymentStageConfig()))"

2023-11-03 10:17 UTC, yogesh-chauhan reviewed
Lets test with Gitops flows also. No need to run it to success, we can just test the service step and its children steps

2023-11-03 10:19 UTC, Abhishek-CDC commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java
> +    StepUtils.appendDelegateSelectors(emptyStepParameters, ctx);
Creating EmptyStepParameters in DeploymentStagePlanCreator ?

2023-11-03 10:22 UTC, Abhishek-CDC commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +        .selectors(selectors)
In ArtifactStep we only send List selectors
for other case we send Set selectors.
So ultimately we don't set both. 
How we are consuming these selectors? if earlier we set to 'taskSelectors' and now set to 'selector' after conversion will it impact?

2023-11-03 10:23 UTC, Abhishek-CDC commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_DELEGATE_SELECTOR_PRECEDENCE("Follow delegate selector precedence in service/infra step", CDC),
Will rename

2023-11-03 10:24 UTC, Abhishek-CDC commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +      ParameterField<List<TaskSelectorYaml>> delegates) {
Then we will have to perform null check and fetch value in main method similar to this

2023-11-07 07:57 UTC, Abhishek-CDC commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java
> +    StepUtils.appendDelegateSelectors(emptyStepParameters, ctx);
Delegate selectors could be expression so we cannot pass list of task selectors as these are not resolved here.
We can either pass ParameterField<TaskSelectorYaml> or PlanCreationContext as parameter

2023-11-07 07:58 UTC, Abhishek-CDC commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java
> +        .selectors(selectors)
Updated with suggested approach

2023-11-07 07:59 UTC, Abhishek-CDC commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +      ParameterField<List<TaskSelectorYaml>> delegates) {
Updated with suggested approach

2023-11-07 07:59 UTC, Abhishek-CDC commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  CDS_DELEGATE_SELECTOR_PRECEDENCE("Follow delegate selector precedence in service/infra step", CDC),
Done

2023-11-07 08:09 UTC, Abhishek-CDC commented
trigger uts

2023-11-07 09:57 UTC, yogesh-chauhan approved these changes

2023-11-07 10:49 UTC, Abhishek-CDC commented
trigger uts

2023-11-07 12:31 UTC, yogesh-chauhan approved these changes

2023-11-08 07:47 UTC, puthrayaharness approved these changes

2023-11-08 08:07 UTC, Abhishek-CDC commented
trigger review

2023-11-08 08:10 UTC, merged