[feat]: [CDS-82273]: Trigger execution sequential
harness/harness-core pull request #54907
Opened 2023-11-02 06:40 UTC by adivishy1

## Describe your changes
Added code to start the trigger execution after the gitx webhook processing for the push based events. Trigger execution has been handled in all the different states of the gitx webhook status.
Testing:
Have tested out the change locally for push based event and non push based event. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-03 00:35 UTC, sribalij commented on 120-ng-manager/src/main/java/io/harness/ng/webhook/WebhookHelper.java
> +      //      The triggers are processed in the GitXWebhookTriggerHelper
Is this not for the old git flow?

2023-11-03 00:43 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java
>          if (gitXWebhook == null) {
How do we ensure if an exception happens the trigger event is still processed?

2023-11-03 00:44 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java
> +  private void updateEventStatusAndStartTriggerExecution(String accountIdentifier, String eventIdentifier,
Since this is called from multiple places, we need to make sure any failure would still result in trigger execution

2023-11-03 04:12 UTC, adivishy1 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java
>          if (gitXWebhook == null) {
The above code is in a try catch block and in the catch block, we are invoking the trigger execution

2023-11-03 04:15 UTC, adivishy1 commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventProcessServiceImpl.java
> +  private void updateEventStatusAndStartTriggerExecution(String accountIdentifier, String eventIdentifier,
Yes, I have added the code for trigger execution in all the code blocks where we are terminating the gitx webhook processing. Have tested out the flows locally and is working as expected.
Once the final code reviews are done, will be deploying this code in the dev space and try to run all the trigger automation against it.

2023-11-03 05:37 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/helper/GitXWebhookTriggerHelper.java
> +  public void startTriggerExecution(WebhookDTO webhookDTO) {
This is being called from multiple places and we need to ensure that it is called ONLY once.

2023-11-03 05:38 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/helper/GitXWebhookTriggerHelper.java
> +    try {
Discussed with @adivishy1 about it and we'll try to see if there is a way to centralize this

2023-11-03 05:38 UTC, sribalij commented on 136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/helper/GitXWebhookTriggerHelper.java
> +  public void startTriggerExecution(WebhookDTO webhookDTO) {
cc: @vcalasansh

2023-11-06 18:47 UTC, sribalij requested changes
Please test the GIT webhook trigger p0,p1,p2 cases(automation also) in devspaces before we can merge this to develop. We want to make sure trigger scenarios work and no regressions are found. This flow happens for 
cc: @vcalasansh @naidu-harness

2023-11-10 05:01 UTC, closed without merging