fix: [CDS-82779]: Use http connectivity to account for proxy configurations
harness/harness-core pull request #54931
Opened 2023-11-02 10:45 UTC by GoelPratyush99

## Describe your changes
Early to verify the helm repo url for Anonymous Auth type we were performing a socket validation. Now we will do a Http validation and only throw exception in case http status code is -1 or the connection throws an exception like Timeout or IO. For rest cases we pass the test this was done as proxy configurations were not compatible with socket validation.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-02 10:46 UTC, GoelPratyush99 commented
trigger uts

2023-11-03 06:04 UTC, TarunUba1 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java
> +        if (!Http.connectableHttpUrl(uriParsedOciUrl.replace(OCI_PREFIX, HTTPS_PREFIX), true)
nit: we can import Http.connectableHttpUrl

2023-11-03 06:04 UTC, TarunUba1 submitted a review, later dismissed

2023-11-03 06:35 UTC, abosii-harness requested changes

2023-11-03 06:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java
> +        if (!Http.connectableHttpUrl(uriParsedOciUrl.replace(OCI_PREFIX, HTTPS_PREFIX), true)
Why we do require both HTTPS and HTTP?

2023-11-03 06:35 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java
> +          throw new InvalidRequestException(format("Invalid oci url %s", ociUrl));
Let's change the error message, it's confusing

2023-11-03 06:42 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java
> +        if (!Http.connectableHttpUrl(uriParsedOciUrl.replace(OCI_PREFIX, HTTPS_PREFIX), true)
They might have an insecure OCI registry https://github.com/helm/helm/issues/6324#issuecomment-1687395253

2023-11-03 07:46 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java
> +          throw new InvalidRequestException(format("Invalid oci url %s", ociUrl));
Done

2023-11-03 07:46 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmValidationHandler.java
> +        if (!Http.connectableHttpUrl(uriParsedOciUrl.replace(OCI_PREFIX, HTTPS_PREFIX), true)
Done

2023-11-03 07:46 UTC, abosii-harness approved these changes

2023-11-03 07:46 UTC, GoelPratyush99 commented
trigger uts

2023-11-03 07:56 UTC, alebuh approved these changes

2023-11-03 07:56 UTC, GoelPratyush99 commented
trigger review

2023-11-03 08:02 UTC, GoelPratyush99 commented
trigger messagecheck

2023-11-03 09:22 UTC, merged