[feat]: [SRM-16083]: updated graph API to read from bucketed SLI records
harness/harness-core pull request #54955
Opened 2023-11-03 04:22 UTC by n00bitax

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-06 09:03 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOGraphUtils.java
> +  public static double getErrorBudgetValue(ServiceLevelIndicator serviceLevelIndicator, long totalErrorBudgetMinutes,
Move to errorbudget service

2023-11-06 09:04 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOGraphUtils.java
> +  public static SLIValue calculateSLIValue(SLIEvaluationType sliEvaluationType, SLIMissingDataType sliMissingDataType,
move to SLIRecordBucket service

2023-11-06 09:16 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOGraphUtils.java
> +  public static boolean isMinuteEnabled(
entity disable service

2023-11-06 09:16 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOGraphUtils.java
> +  public static long getBadCountTillRangeStartTime(ServiceLevelIndicator serviceLevelIndicator,
SLIRecordBucket

2023-11-06 09:25 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImpl.java
> +                  sliTrendList, true, false, totalErrorBudget)
trends and burndowns

2023-11-06 09:41 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOGraphUtils.java
> +      SLIRecordBucket sliRecordBucket, Pair<Long, Long> previousRunningCountPair, long beginningMinute,
rename to baseCount

2023-11-06 12:01 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOGraphUtils.java
> +public class SLOGraphUtils {
move this to utils package

2023-11-07 10:51 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServicemplV2Test.java
> +  public void testGetGraphData_allBad() {
@Varsha-lalwani will this be correct ?

2023-11-09 04:36 UTC, n00bitax commented
trigger uts

2023-11-09 06:48 UTC, n00bitax commented
trigger uts

2023-11-09 10:01 UTC, Varsha-lalwani requested changes

2023-11-09 10:23 UTC, n00bitax commented
trigger uts

2023-11-09 10:49 UTC, n00bitax commented
trigger uts

2023-11-09 17:25 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/SLOGraphUtils.java
> +    List<Instant> minutes = new ArrayList<>();
a lot of these minutes might not come to be multiple of 5. We need those to be multiple of 5 for record buckets

2023-11-10 04:10 UTC, n00bitax commented
trigger uts

2023-11-10 04:26 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2Impl.java
> +                                           currentSLIValue, serviceLevelObjective))
please check, its updated at initialization

2023-11-10 04:26 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2Impl.java
> +  private static SLODashboardWidget.SLOGraphData getSloGraphDataForMismatch(ServiceLevelIndicator serviceLevelIndicator,
done

2023-11-10 04:26 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2Impl.java
> +            currentSLIRecordBucket.getSliStates().stream().filter(sliState -> sliState == SLIState.SKIP_DATA).count();
we can do in next PR

2023-11-10 04:27 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordBucketServiceImpl.java
> +    if (!firstRecordInRange.getBucketStartTime().equals(firstRecord.getBucketStartTime())) { // TODO fix
done

2023-11-10 04:27 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordBucketService.java
> +  List<SLIRecordBucket> getSLIRecordBucketsForGraph(
done

2023-11-10 04:27 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java
> +    SLODashboardWidget.SLOGraphData sloGraphData;
done

2023-11-10 04:28 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/SLOGraphUtils.java
> +    List<Instant> minutes = new ArrayList<>();
I guess we need a test case with higher points count, currently this will result in 2000 / 5 points as a consequence, will update post discussion with you.

2023-11-10 04:29 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2Impl.java
> +  private long getBadCountTillRangeStartTime(ServiceLevelIndicator serviceLevelIndicator,
its duplicate with which method?

2023-11-10 04:31 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordBucketServiceImpl.java
> +    // Map with Timestamp as key and SLIRecord as value with merge function to take the latest -> all this just to sort
added a TODO here, I think we can correct once its working functionally perfectly.

2023-11-10 04:46 UTC, Varsha-lalwani requested changes

2023-11-10 04:46 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2ImplTest.java
> +    @Owner(developers = ANSUMAN)
why did we comment this?

2023-11-10 04:46 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2Impl.java
> +  private long getBadCountTillRangeStartTime(ServiceLevelIndicator serviceLevelIndicator,
it's also in SLIRecordBucketService

2023-11-10 04:46 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/SLOGraphUtils.java
> +    List<Instant> minutes = new ArrayList<>();
the logic will be changed as well. Let's discuss this, we shouldn't merge without this change

2023-11-10 04:46 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2Impl.java
> +                                           currentSLIValue, serviceLevelObjective))
long currentBucketEndTime =
            currentSLIRecordBucket.getBucketStartTime().plus(SLI_RECORD_BUCKET_SIZE, ChronoUnit.MINUTES).toEpochMilli();  this will set to 12:55

2023-11-10 04:56 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2Impl.java
> +                                           currentSLIValue, serviceLevelObjective))
long currentBucketEndTime = currentSLIRecordBucket.getBucketStartTime()
                                        .plus(SLI_RECORD_BUCKET_SIZE - 1, 
                                        my code shows different ? , maybe its in outdated version ?

2023-11-10 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=54955) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=54955) before we can accept your contribution.<br/>**50** out of **53** committers have signed the CLA.<br/><br/>:white_check_mark: vigneswara-propelo<br/>:white_check_mark: abhinavmittal-harness<br/>:white_check_mark: Y0709<br/>:white_check_mark: bharatgoelharness<br/>:white_check_mark: utkarshchoubey-harness<br/>:white_check_mark: vikyathharekal<br/>:white_check_mark: lovish1999<br/>:white_check_mark: brijeshdhakar<br/>:white_check_mark: adiyaar24<br/>:white_check_mark: crystal-fong<br/>:white_check_mark: sribalij<br/>:white_check_mark: AnupamIO<br/>:white_check_mark: Aashrit-Harness<br/>:white_check_mark: abhinavsingh1196<br/>:white_check_mark: markoharness<br/>:white_check_mark: arya-harness<br/>:white_check_mark: eoinmcafee00<br/>:white_check_mark: nassergonzalez<br/>:white_check_mark: vcalasansh<br/>:white_check_mark: jennyjames21<br/>:white_check_mark: vivekkarnatiharness<br/>:white_check_mark: harness-dc<br/>:white_check_mark: deepak-harness<br/>:white_check_mark: naveen-harness<br/>:white_check_mark: jamie-harness<br/>:white_check_mark: sourabh-awashti<br/>:white_check_mark: alebuh<br/>:white_check_mark: smjt-h<br/>:white_check_mark: reetika04<br/>:white_check_mark: Raghav-Murali<br/>:white_check_mark: ShubhenduP<br/>:white_check_mark: iamanmolm<br/>:white_check_mark: Jimit09Gandhi<br/>:white_check_mark: williamwissemann<br/>:white_check_mark: inderschera<br/>:white_check_mark: harshjain12<br/>:white_check_mark: senjucanon2<br/>:white_check_mark: tmacari-harness<br/>:white_check_mark: Abhishek-CDC<br/>:white_check_mark: shalini-agr<br/>:white_check_mark: xingchi-jin<br/>:white_check_mark: arpit-harness<br/>:white_check_mark: AbhijithHarness<br/>:white_check_mark: n00bitax<br/>:white_check_mark: vtxorxwitty<br/>:white_check_mark: lasdox<br/>:white_check_mark: piyush-bhuwalka<br/>:white_check_mark: AnshuH<br/>:white_check_mark: sarthakkasat<br/>:white_check_mark: vitsafronovici<br/>:x: devesh-harness<br/>:x: bot-harness<br/>:x: sahithibanda01<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=54955) it.</sub>

2023-11-10 08:40 UTC, n00bitax commented
trigger uts

2023-11-10 08:41 UTC, n00bitax commented
trigger uts

2023-11-10 08:42 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceV2ImplTest.java
> +    @Owner(developers = ANSUMAN)
changed to ignore

2023-11-10 08:44 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/SLOGraphUtils.java
> +    List<Instant> minutes = new ArrayList<>();
can you check now

2023-11-10 08:50 UTC, n00bitax commented
trigger codeformat

2023-11-10 09:08 UTC, n00bitax commented
trigger checkstylecodeformat

2023-11-10 09:13 UTC, Varsha-lalwani requested changes

2023-11-10 09:13 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordBucketServiceImpl.java
> +        startTime, endTime, numOfPoints, firstRecord.getBucketStartTime(), SLI_RECORD_BUCKET_SIZE);
you don't need these 3, you can just pass firstRecordInRange.startTime and same for lastRecordInRange.startTime. They will be correct bucket time

2023-11-10 09:13 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/SLOGraphUtils.java
> +  private static Instant adjustStartTimeToFitBuckets(Instant startTime, Instant sliStartTime, int bucketSize) {
You wouldn't need this after that change

2023-11-10 09:38 UTC, n00bitax commented
trigger uts

2023-11-10 09:50 UTC, Varsha-lalwani approved these changes

2023-11-10 09:52 UTC, n00bitax commented
trigger uts

2023-11-10 10:27 UTC, Varsha-lalwani approved these changes

2023-11-10 10:29 UTC, merged