fix: [CDS-82203]: Pipeline execution shows success post abort
harness/harness-core pull request #54979
Opened 2023-11-03 10:46 UTC by Aninditaa-ch

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-03 10:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=54979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=54979) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=54979) it.</sub>

2023-11-03 10:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=54979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=54979) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=54979) it.</sub>

2023-11-03 10:46 UTC, Aninditaa-ch commented
trigger uts

2023-11-03 10:50 UTC, ankittiwari-harness commented on pipeline-service/modules/orchestration/src/test/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandlerTest.java
> +import static org.mockito.Mockito.*;
nit: remove *

2023-11-03 11:32 UTC, Aninditaa-ch commented
trigger uts

2023-11-03 11:33 UTC, Aninditaa-ch commented on pipeline-service/modules/orchestration/src/test/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandlerTest.java
> +import static org.mockito.Mockito.*;
done

2023-11-03 11:37 UTC, Aninditaa-ch commented
trigger SmartPRChecks

2023-11-03 11:40 UTC, Aninditaa-ch commented
trigger smartchecks

2023-11-03 11:52 UTC, Aninditaa-ch commented
trigger messagecheck

2023-11-06 06:55 UTC, Aninditaa-ch commented
trigger gitleaks

2023-11-06 12:55 UTC, Aninditaa-ch commented
trigger messagecheck

2023-11-06 13:00 UTC, Aninditaa-ch commented
trigger messagecheck

2023-11-06 13:28 UTC, sahilhindwani-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54979)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/54979#-NiZoUBK63wM5_jeTUR5:-NiZoUBK63wM5_jeTUR6:b-65coyh) ([raw file](https://github.com/harness/harness-core/blob/aa8251a423845cdb318c8298dd4b1dbb69ff9ecc/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L61)):*
> ```Java
>   public Interrupt registerInterrupt(Interrupt interrupt) {
>     Interrupt savedInterrupt = validateAndSave(interrupt);
>     Status status = planExecutionService.getStatus(interrupt.getPlanExecutionId());
> ```

Can we add this condition in handleInterrupt itself?
There we are already making the same call.


<!-- Sent from Reviewable.io -->

2023-11-07 04:21 UTC, shalini-agr approved these changes

2023-11-07 06:11 UTC, Aninditaa-ch reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54979)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/54979#-NiZoUBK63wM5_jeTUR5:-NicOfrG4hhYvWmhjgzD:b-j3mna2) ([raw file](https://github.com/harness/harness-core/blob/aa8251a423845cdb318c8298dd4b1dbb69ff9ecc/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L61)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add this condition in handleInterrupt itself?
There we are already making the same call.
</blockquote></details>

The call is made in validateAndSave not in HandleInterrupt.So this cannot be added in that right?


<!-- Sent from Reviewable.io -->

2023-11-10 06:16 UTC, Aninditaa-ch commented
trigger uts

2023-11-10 08:19 UTC, shalini-agr approved these changes

2023-11-10 08:21 UTC, Aninditaa-ch commented
trigger ut3

2023-11-13 08:35 UTC, Aninditaa-ch commented
trigger reviewCheck

2023-11-13 09:27 UTC, merged