feat: [CDS-82796]: support fetching optional files and not failing th…
harness/harness-core pull request #54986
Opened 2023-11-03 11:31 UTC by vlica-harness

…e task

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-03 11:32 UTC, vlica-harness commented
trigger uts

2023-11-03 14:46 UTC, vlica-harness commented
trigger uts

2023-11-06 07:43 UTC, abosii-harness requested changes

2023-11-06 07:43 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java
> +      gitFetchFilesTaskHelper.printFileNamesInExecutionLogs(filePathsToFetch, executionLogCallback, false);
any reasons why we're replacing closeLogStream with constant?

2023-11-06 07:43 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java
> +                  && fileContent.getError().equals("Not Found")) {
Is this error generated by the scm or respective provider API. Can we be sure that this will always be not found? Isn't enough to just check for 404?

2023-11-06 07:43 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java
> +                log.warn(format("Unable to fetch optional file: %s", fileContent.getPath()));
Maybe debug will make more sense here?

2023-11-06 07:43 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +          log.warn(format("Unable to fetch optional file: %s", filePath));
maybe debug will make more sense here?

2023-11-06 07:47 UTC, tmacari-harness reviewed
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54986)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-api-services-beans/src/main/java/io/harness/git/model/FetchFilesByPathRequest.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/54986#-NiYa9QF3hWnGlLc7_q8:-NiYa9QF3hWnGlLc7_q9:ba6e964) ([raw file](https://github.com/harness/harness-core/blob/2f92b6cc4a7b86e7769e4ab6c2b2a1d1c8f88014/970-api-services-beans/src/main/java/io/harness/git/model/FetchFilesByPathRequest.java#L24)):*
> ```Java
>   private List<String> fileExtensions;
>   private boolean recursive;
>   private boolean optionalFile;
> ```

optionalFiles looks better once we have a list


<!-- Sent from Reviewable.io -->

2023-11-06 11:09 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java
> +      gitFetchFilesTaskHelper.printFileNamesInExecutionLogs(filePathsToFetch, executionLogCallback, false);
if we send closeLogStream true and we have multiple files in gitConfig then only the logs for the first filePath will be logged. This method is covered to closeLogStream if in request is yes.

2023-11-06 11:10 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java
> +                  && fileContent.getError().equals("Not Found")) {
Seems this to be generated by the respective provider API. I left to rely only on statusCode

2023-11-06 11:10 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/ScmFetchFilesHelperNG.java
> +                log.warn(format("Unable to fetch optional file: %s", fileContent.getPath()));
yes

2023-11-06 11:10 UTC, vlica-harness commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +          log.warn(format("Unable to fetch optional file: %s", filePath));
yes

2023-11-06 11:14 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java
> +      gitFetchFilesTaskHelper.printFileNamesInExecutionLogs(filePathsToFetch, executionLogCallback, false);
This should be handled by the step itself, are you sure that with this change you're not breaking other swimlanes that requires this to be closed?

2023-11-06 12:20 UTC, vlica-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/GitFetchTaskNG.java
> +      gitFetchFilesTaskHelper.printFileNamesInExecutionLogs(filePathsToFetch, executionLogCallback, false);
it should not break for other swimlanes, the method is called from try catch clause, in catch if we have an exception the log stream is closed with failure. And also before returning the response from the task we have this 
`if (gitFetchRequest.isCloseLogStream()) {
        executionLogCallback.saveExecutionLog("Done.", INFO, CommandExecutionStatus.SUCCESS);
      }`

2023-11-06 12:43 UTC, vlica-harness commented
trigger codeformat

2023-11-06 12:44 UTC, vlica-harness commented
trigger pmd

2023-11-06 15:41 UTC, vlica-harness commented
trigger pmd

2023-11-06 16:06 UTC, tmacari-harness approved these changes

2023-11-06 16:18 UTC, abosii-harness approved these changes

2023-11-06 16:19 UTC, vlica-harness commented
trigger review

2023-11-06 16:35 UTC, merged