Srm 16085
harness/harness-core pull request #55013
Opened 2023-11-05 23:48 UTC by deepak-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-07 06:04 UTC, deepak-harness commented
trigger uts

2023-11-07 08:19 UTC, deepak-harness commented
trigger uts

2023-11-08 04:53 UTC, deepak-harness commented
trigger uts

2023-11-08 06:00 UTC, Varsha-lalwani requested changes
Can we add tests for MetricLess SLI for CRUD?
Also let's ensure this is not a breaking change in terraform and UI.

2023-11-08 06:32 UTC, Varsha-lalwani approved these changes

2023-11-08 08:15 UTC, deepak-harness commented
trigger checkstylecodeformat, messagecheck, pmd, codebasehash, gitleaks, commonchecks, review, uts

2023-11-08 08:17 UTC, deepak-harness commented
trigger uts

2023-11-08 10:20 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java
> +        //        tags.add(NGTag.builder()
Can we remove this ?

2023-11-08 13:24 UTC, deepak-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVConstants.java
> +  String METRIC_LESS_SLI_IDENTIFIER = "metric_less_vyczachdfd";
We needed some  unique constant random identifier for metric_less SLIs. as per Sunil we want to keep the option for customer to name their SLI metric_less for other type of SLIs. so picked up this which customer will never use as the identifier for any other SLI

2023-11-08 13:26 UTC, deepak-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java
> +        //        tags.add(NGTag.builder()
this is part of migration scrpit. since we removed the SLIType we can't have this code. but removal of code entirely felt like deleting some info incase someone wants to revisit this migration script. if you still feel we can remove it.

2023-11-08 13:26 UTC, deepak-harness commented
trigger uts

2023-11-08 16:32 UTC, Varsha-lalwani approved these changes

2023-11-08 16:52 UTC, merged