feat: [CDS-82173]: Handle multi env and multi service deployment save
harness/harness-core pull request #55011
Opened 2023-11-05 21:42 UTC by abhinavmittal-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-05 21:43 UTC, abhinavmittal-harness commented
trigger ss

2023-11-06 23:13 UTC, abhinavmittal-harness commented
trigger smartchecks

2023-11-07 19:34 UTC, tchaurasiya requested changes

2023-11-07 19:34 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/service/MultiDeploymentStageDetailsInfo.java
> +@TypeAlias("singleServiceEnvDeploymentStageDetailsInfo")
nit: singleService...??

2023-11-07 19:34 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/MultiServiceEnvDeploymentStageDetailsInfo.java
> +public class MultiServiceEnvDeploymentStageDetailsInfo implements DeploymentStageDetailsInfo {
do we not need to register this in public interface DeploymentStageDetailsInfo {} with jsonSubTypes?

2023-11-07 19:34 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +        if (!servicesYaml.getValues().isExpression()) {
are we not handling useFromStage for multi service?

2023-11-07 19:34 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +      DeploymentStageConfig deploymentStageConfig, YamlField specField) {
lets test this one with gitops pipeline where infras are not present

2023-11-08 04:57 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55011)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/MultiServiceEnvDeploymentStageDetailsInfo.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1385437422:-NihHLo_8M4xr_CnNgwn:b8ou9zq) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/MultiServiceEnvDeploymentStageDetailsInfo.java#L35)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

do we not need to register this in public interface DeploymentStageDetailsInfo {} with jsonSubTypes?
</blockquote></details>

No this should work
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 996 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1385456900:-NihHTPvC5QcCyXJoaYS:bp6ikyj) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L996)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

lets test this one with gitops pipeline where infras are not present
</blockquote></details>

Will do but even if it doesn't work we are catching the exception and proceding firther.
Will handle that case via separate pr
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 1084 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1385454281:-NihHengAYa4LJOvANcc:b4cn0bh) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L1084)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

are we not handling useFromStage for multi service?
</blockquote></details>

In the parent call we handle useFromStage for multi case and save it to stage Node.
So it works


<!-- Sent from Reviewable.io -->

2023-11-08 05:15 UTC, naman-goenka commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/service/MultiDeploymentStageDetailsInfo.java
> +@JsonTypeName(DeploymentStageTypeConstants.MULTI_SERVICE_ENVIRONMENT)
jsonTypeName is same for this and above class?

2023-11-08 05:23 UTC, naman-goenka commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java
> +  public String refineIdentifier(String identifier) {
To confirm: do we need to worry about backward compatibility with pms client here

2023-11-08 05:28 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +        log.warn("Exception occurred while async saving deployment stage plan creation info: {}",
nit: can we add "multi" in log message

2023-11-08 05:58 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +    return infras;
Can we log here for knowing why infra was saved as empty set in case of expression

2023-11-08 09:15 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55011)* status: 7 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/service/MultiDeploymentStageDetailsInfo.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1385992416:-NiiB8uH5rrbD9YS0zaR:bc9i4tk) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/service/MultiDeploymentStageDetailsInfo.java#L34)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

jsonTypeName is same for this and above class?
</blockquote></details>

Intended class removed
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/service/MultiDeploymentStageDetailsInfo.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1385435152:-NiiBAIg8inOJlMtIvut:bc9i4tk) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/service/MultiDeploymentStageDetailsInfo.java#L35)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: singleService...??
</blockquote></details>

Intended class removed
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 949 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1386013053:-NiiBJNh9oPor_InV0Vk:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L949)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

nit: can we add "multi" in log message
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 996 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1385456900:-NiiBLli7vezKYBTQ-PC:b-a7rh1y) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L996)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Will do but even if it doesn't work we are catching the exception and proceding firther.
Will handle that case via separate pr
</blockquote></details>

gitops Would not come in this flow we will handle separately
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1386005635:-NiiBe5sA505wCb6qccg:bjyucvl) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L348)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

To confirm: do we need to worry about backward compatibility with pms client here
</blockquote></details>

No we are just changing the visibility of the method.


<!-- Sent from Reviewable.io -->

2023-11-08 10:32 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55011)* status: 7 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 1027 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1386030946:-NiiULD23nbmLgY3Dihw:b-5q1qdi) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L1027)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

Can we log here for knowing why infra was saved as empty set in case of expression
</blockquote></details>

Via ui we can't have them as expression


<!-- Sent from Reviewable.io -->

2023-11-08 10:32 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55011)* status: 7 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 1027 at r2](https://reviewable.io/reviews/harness/harness-core/55011#gh-1386030946:-NiiUPhq9TVRjZHkSJgx:b-pn7n1g) ([raw file](https://github.com/harness/harness-core/blob/eaaf4a6e4d96f3830b67c2b114428ce4beecf6b4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L1027)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Via ui we can't have them as expression
</blockquote></details>

@tchaurasiya can you confirm


<!-- Sent from Reviewable.io -->

2023-11-08 11:16 UTC, abhinavmittal-harness commented
trigger uts

2023-11-08 11:55 UTC, tchaurasiya submitted a review, later dismissed

2023-11-08 14:14 UTC, abhinavmittal-harness commented
trigger messagecheck

2023-11-08 16:22 UTC, tchaurasiya submitted a review, later dismissed

2023-11-08 17:44 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +      return finalEnvironmentYamlV2.getInfrastructureDefinitions()
Can we have a case here where we have `infrastructureDefinition` instead of `infrastructureDefinitions`

2023-11-08 17:47 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +  private Set<String> getEnvironmentRefsForMultiEnvDeploymentFromInfraYaml(
is the name of this util correct, perhaps we are getting infra ids here

2023-11-08 17:52 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +  private String getReferenceValue(ParameterField<String> parameterField) {
nit: can we use fetchFinalValue intead

2023-11-08 17:58 UTC, naman-goenka approved these changes

2023-11-09 05:04 UTC, abhinavmittal-harness commented
trigger review

2023-11-09 05:04 UTC, abhinavmittal-harness commented
trigger uts

2023-11-10 03:17 UTC, abhinavmittal-harness commented
trigger uts

2023-11-10 04:50 UTC, tchaurasiya approved these changes

2023-11-10 05:35 UTC, naman-goenka commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +      return finalEnvironmentYamlV2.getInfrastructureDefinitions()
Not possible

2023-11-10 05:47 UTC, naman-goenka approved these changes

2023-11-10 06:32 UTC, merged