feat: [CCM-14043]: Ability to save Governace rule with Autostopping properties
harness/harness-core pull request #55025
Opened 2023-11-06 07:05 UTC by sujeesh-harness

## Describe your changes

1. Instead of taking governance policy schema directly from custodian executable, introduced a static json file with schema `ce-nextgen/service/src/main/resources/governance_rule/rule_schema.json`.
2. Added autostopping fields to the static schema json
3. While validation policy, use static json schema instead of custodian
4. In `YamlSchemaValidator`, added the ability to validate an input yaml for a given schema
5. While pushing governance job to Faktory, pass connector id also for AWS.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-06 12:49 UTC, sujeesh-harness commented
trigger ss

2023-11-06 13:07 UTC, sujeesh-harness commented
trigger ss

2023-11-07 04:43 UTC, sujeesh-harness commented
trigger ss

2023-11-07 05:21 UTC, sujeesh-harness commented
trigger ss

2023-11-07 05:42 UTC, sujeesh-harness commented
trigger smartchecks

2023-11-07 05:44 UTC, sujeesh-harness commented
trigger checkstylecodeformat

2023-11-07 06:49 UTC, sujeesh-harness commented
trigger ss

2023-11-07 06:49 UTC, sujeesh-harness commented
trigger checkstylecodeformat

2023-11-07 06:50 UTC, sujeesh-harness commented
trigger messagecheck

2023-11-07 06:59 UTC, sujeesh-harness commented
trigger checkstylecodeformat

2023-11-07 07:11 UTC, sujeesh-harness commented
trigger checkstylecodeformat

2023-11-07 07:37 UTC, sujeesh-harness commented
trigger checkstylecodeformat

2023-11-07 07:37 UTC, sujeesh-harness commented
trigger messagecheck

2023-11-07 07:44 UTC, sujeesh-harness commented
trigger checkstylecodeformat

2023-11-07 07:45 UTC, sujeesh-harness commented
trigger ss

2023-11-07 07:45 UTC, sujeesh-harness commented
trigger messagecheck

2023-11-07 09:05 UTC, sujeesh-harness commented
trigger checkstylecodeformat

2023-11-07 09:05 UTC, sujeesh-harness commented
trigger messagecheck

2023-11-07 09:05 UTC, sujeesh-harness commented
trigger ss

2023-11-07 09:38 UTC, AnshuH commented on 450-ce-views/src/test/java/io/harness/ccm/views/service/impl/GovernanceRuleServiceImplTest.java
> +import static org.mockito.Mockito.times;
Move this line above and make the order alphabetically

2023-11-08 18:03 UTC, nikunj-badjatya requested changes

2023-11-08 18:03 UTC, nikunj-badjatya commented on 450-ce-views/src/main/java/io/harness/ccm/views/service/impl/GovernanceRuleServiceImpl.java
>        throw new InvalidRequestException("Policy YAML is malformed");
Can we pass the error message back to the user in case when we see "Policy YAML is malformed" error for user to understand more about the error ?

2023-11-09 07:11 UTC, sujeesh-harness commented on 450-ce-views/src/main/java/io/harness/ccm/views/service/impl/GovernanceRuleServiceImpl.java
>        throw new InvalidRequestException("Policy YAML is malformed");
@nikunj-badjatya Modified code to return error message to user. The error message generated from YAML SDK  may not be accurate though.

2023-11-09 07:12 UTC, sujeesh-harness commented
trigger ss

2023-11-16 05:05 UTC, nikunj-badjatya approved these changes

2023-11-16 05:05 UTC, merged