feat: [CDS-82817]: Adding new delegate task for Artifact bundle support in TAS deployment
harness/harness-core pull request #55034
Opened 2023-11-06 08:23 UTC by namantalaycha10

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-07 16:45 UTC, namantalaycha10 commented
trigger uts

2023-11-07 17:25 UTC, vlica-harness requested changes

2023-11-07 17:25 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/beans/ArtifactBundleFetchResponsePassThroughData.java
> +@RecasterAlias("io.harness.cdng.tas.beans.ArtifactBundleFetchResponsePassThroughData")
Missing  @OwnedBy

2023-11-07 17:25 UTC, vlica-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +    ParameterField<List<TaskSelectorYaml>> stepLevelSelectors = null;
Hey Naman, wouldn't be better if we will extract this stepLevelSelectors into a different method?

2023-11-07 17:25 UTC, vlica-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String activityId;
Haven't seen were this activityId was set

2023-11-07 17:25 UTC, vlica-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String executionLogName;
Haven't seen were this executionLogName was set

2023-11-07 17:25 UTC, vlica-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/response/ArtifactBundleFetchResponse.java
> +public class ArtifactBundleFetchResponse implements DelegateTaskNotifyResponseData {
missing ownedBy

2023-11-08 05:55 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/response/ArtifactBundleFetchResponse.java
> +public class ArtifactBundleFetchResponse implements DelegateTaskNotifyResponseData {
added

2023-11-08 05:55 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String executionLogName;
removed

2023-11-08 05:55 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String activityId;
done

2023-11-08 05:55 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +    ParameterField<List<TaskSelectorYaml>> stepLevelSelectors = null;
done

2023-11-08 05:55 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/beans/ArtifactBundleFetchResponsePassThroughData.java
> +@RecasterAlias("io.harness.cdng.tas.beans.ArtifactBundleFetchResponsePassThroughData")
added

2023-11-08 05:56 UTC, namantalaycha10 commented
trigger uts

2023-11-08 06:06 UTC, namantalaycha10 commented
trigger uts

2023-11-08 06:36 UTC, namantalaycha10 commented
trigger uts

2023-11-08 06:52 UTC, namantalaycha10 commented
trigger ut5

2023-11-08 06:52 UTC, namantalaycha10 commented
trigger ut6

2023-11-08 06:52 UTC, namantalaycha10 commented
trigger ut7

2023-11-08 06:52 UTC, namantalaycha10 commented
trigger ut9

2023-11-08 07:18 UTC, namantalaycha10 commented
trigger ut9

2023-11-08 10:09 UTC, vlica-harness approved these changes

2023-11-08 12:06 UTC, namantalaycha10 commented
trigger uts

2023-11-08 12:14 UTC, abosii-harness requested changes

2023-11-08 12:14 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +            .shouldOpenLogStream(true)
Should we rely on tasStepPassThroughData.getShouldOpenFetchFilesStream()?

2023-11-08 12:14 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +  private ParameterField<List<TaskSelectorYaml>> getStepLevelSelectors(StepBaseParameters stepElementParameters) {
nit: ideally this logic should be achieved through implementing common interface

2023-11-08 12:14 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +        AmbianceUtils.getStageLevelFromAmbiance(ambiance).map(Level::getIdentifier).orElse("Deployment stage");
nit: ideally this and TAS should be constants

2023-11-08 12:15 UTC, abosii-harness commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  ARTIFACT_BUNDLE_FETCH_TASK(TaskGroup.ARTIFACT_BUNDLE, "Artifact bundle fetch task in NG");
this task should be marked as unsupported as you don't have the del changes ready

2023-11-08 13:53 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +            .shouldOpenLogStream(true)
you mean tasStepPassThroughData.getShouldExecuteArtifactBundleStoreFetch()?

Actually PM asked to not make this behind and FF so using this getShouldExecuteArtifactBundleStoreFetch() to prevent any issues. This will be only set when customer use ArtifactBundleStore in Tas Manifest

2023-11-08 14:08 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +  private ParameterField<List<TaskSelectorYaml>> getStepLevelSelectors(StepBaseParameters stepElementParameters) {
skipping

2023-11-08 14:08 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +        AmbianceUtils.getStageLevelFromAmbiance(ambiance).map(Level::getIdentifier).orElse("Deployment stage");
done

2023-11-08 14:09 UTC, namantalaycha10 commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  ARTIFACT_BUNDLE_FETCH_TASK(TaskGroup.ARTIFACT_BUNDLE, "Artifact bundle fetch task in NG");
Done

2023-11-08 14:12 UTC, namantalaycha10 commented
trigger uts

2023-11-08 14:22 UTC, namantalaycha10 commented
trigger uts

2023-11-08 14:39 UTC, namantalaycha10 commented
trigger ut6

2023-11-09 07:03 UTC, namantalaycha10 commented
trigger uts

2023-11-09 08:10 UTC, namantalaycha10 commented
trigger uts

2023-11-09 08:39 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      commandUnits.add(CfCommandUnitConstants.FetchFiles);
can we create a new command unit, this one is used for local file fetch

2023-11-09 08:39 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      commandUnits.add(CfCommandUnitConstants.FetchFiles);
same as above

2023-11-09 08:39 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      return prepareArtifactBundleTaskChainResponse(ambiance, stepElementParameters, updatedTasStepPassThroughData);
this needs to be called in custom response handling also

2023-11-09 08:39 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +    OptionalOutcome optionalOutcome = outcomeService.resolveOptional(
We can probably reuse the line similar to `TasBGAppSetupStep.java::222`

2023-11-09 08:39 UTC, RishabhGupta34 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      } else if (tasStepPassThroughData.getShouldExecuteArtifactBundleStoreFetch()) {
pl. match this boolean usage with the git/custom one to confirm we are handling artifact cases for all scenarios.

2023-11-09 10:50 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      } else if (tasStepPassThroughData.getShouldExecuteArtifactBundleStoreFetch()) {
checked,handling artifact cases for all scenarios.

2023-11-09 10:50 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +    OptionalOutcome optionalOutcome = outcomeService.resolveOptional(
done

2023-11-09 10:51 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      return prepareArtifactBundleTaskChainResponse(ambiance, stepElementParameters, updatedTasStepPassThroughData);
done

2023-11-09 10:51 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      commandUnits.add(CfCommandUnitConstants.FetchFiles);
done

2023-11-09 10:51 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepHelper.java
> +      commandUnits.add(CfCommandUnitConstants.FetchFiles);
done

2023-11-09 10:51 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +      if (tasArtifactConfig.getArtifactType() == TasArtifactType.CONTAINER) {
done

2023-11-09 11:43 UTC, anilchowdhury-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +      if (tasArtifactConfig.getArtifactType() == TasArtifactType.PACKAGE) {
lets revert IF condition as discussed

2023-11-09 11:44 UTC, anilchowdhury-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepPassThroughData.java
> +  Map<String, List<FileData>> filesFromArtifactBundle;
As discussed please check if we can re-organise this classes into subclasses for GIT, Custom, Bundle. Currently we are putting everything inside this

2023-11-09 12:00 UTC, namantalaycha10 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasStepPassThroughData.java
> +  Map<String, List<FileData>> filesFromArtifactBundle;
Sure @anilchowdhury-harness will discuss this internally

2023-11-09 12:00 UTC, RishabhGupta34 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +    if (tasArtifactConfig != null || (tasArtifactConfig.getArtifactType() == TasArtifactType.CONTAINER)) {
nit. this should be `tasArtifactConfig == null` right?

2023-11-09 12:01 UTC, namantalaycha10 commented
trigger uts

2023-11-09 12:18 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +    if (tasArtifactConfig != null || (tasArtifactConfig.getArtifactType() == TasArtifactType.CONTAINER)) {
updated

2023-11-09 12:19 UTC, namantalaycha10 commented
trigger uts

2023-11-09 12:34 UTC, anilchowdhury-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String activityId;
Can we write this ArtifactBundleFetchRequest in a generic way such that in future if any other swimlane want to use it, that should be straight forward.
We might need get rid of TAS concept out from this class

2023-11-10 08:21 UTC, namantalaycha10 commented
trigger uts

2023-11-10 08:23 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String activityId;
Done

2023-11-10 09:21 UTC, RishabhGupta34 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String activityId;
creating `TasArtifactBundleConfig` will still require special handling for TAS case right, from delegate side to process and fetch the files?

2023-11-10 09:59 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String activityId;
yes, in delegate side we will create different handler for TAS case

2023-11-10 12:26 UTC, namantalaycha10 commented
trigger uts

2023-11-10 12:39 UTC, namantalaycha10 commented
trigger uts

2023-11-10 12:45 UTC, namantalaycha10 commented
trigger ut8

2023-11-10 12:58 UTC, anilchowdhury-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/TasArtifactBundleConfig.java
> +  TasArtifactConfig tasArtifactConfig;
Can we rename this class to ArtifactBundleConfig and drop TAS prefix from it

2023-11-10 12:59 UTC, anilchowdhury-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/TasArtifactBundleConfig.java
> +
We should remove all TAS specific classes reference from this to make it generic 
TasManifestDelegateConfig tasManifestDelegateConfig

2023-11-10 13:07 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/TasArtifactBundleConfig.java
> +
Hi @anilchowdhury-harness , but this is the implementation of the ArtifactBundleConfig interface
The idea is if somebody whats to use this Task in future  they can implement there own Config 
and handle in delegate side
Tas require I didn't created it TasArtifactConfig i just reused it
and TasManifestDelegateConfig have some Tas specific field so thats why I added the Tas Prefix in it

2023-11-10 13:07 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/TasArtifactBundleConfig.java
> +  TasArtifactConfig tasArtifactConfig;
please read this : https://github.com/harness/harness-core/pull/55034#discussion_r1389371653

2023-11-10 13:16 UTC, namantalaycha10 commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ArtifactBundleStore.java
>  @OwnedBy(CDP)
Done

2023-11-10 13:18 UTC, namantalaycha10 commented
trigger uts

2023-11-10 14:00 UTC, anilchowdhury-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/TasArtifactBundleConfig.java
> +  TasArtifactConfig tasArtifactConfig;
I mean you can create new class ArtifactBundleConfig

and have the property of TasArtifactConfig in this class as field

2023-11-13 10:35 UTC, namantalaycha10 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifactBundle/ArtifactBundleFetchRequest.java
> +  private String activityId;
Done now the request is generic

2023-11-13 10:40 UTC, namantalaycha10 commented
trigger uts

2023-11-13 11:05 UTC, namantalaycha10 commented
trigger uts

2023-11-15 04:50 UTC, namantalaycha10 commented
trigger uts

2023-11-15 10:35 UTC, namantalaycha10 commented
trigger uts

2023-11-15 10:41 UTC, anilchowdhury-harness approved these changes

2023-11-16 04:52 UTC, namantalaycha10 commented
trigger reivew

2023-11-16 04:52 UTC, namantalaycha10 commented
trigger review

2023-11-16 04:57 UTC, namantalaycha10 commented
trigger gitleaks

2023-11-16 06:38 UTC, abosii-harness approved these changes

2023-11-16 13:17 UTC, yogesh-chauhan approved these changes

2023-11-16 14:58 UTC, merged