feat:[CDS-80838]: add api for fetching all infra accessible at a scope
harness/harness-core pull request #55047
Opened 2023-11-06 11:55 UTC by sourabh-awashti

## Describe your changes
Changes are regarding the addition of new api for fetching the infras accessible at any scope.
tests Done:
1. Fetched all infrastructure at project/org/account level.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-06 12:48 UTC, sourabh-awashti commented
trigger uts

2023-11-06 14:29 UTC, lovish1999 submitted a review, later dismissed
LGTM

2023-11-07 04:07 UTC, sourabh-awashti commented
trigger uts

2023-11-07 07:01 UTC, tchaurasiya requested changes

2023-11-07 07:01 UTC, tchaurasiya commented on 120-ng-manager/src/test/java/io/harness/ng/core/infrastructure/resource/InfrastructureResourceTest.java
> +    doReturn(AccessCheckResponseDTO.builder()
nit: Lets add multiple infra in test set (with different env at different scope, and some with permitted false to ensure our filtering logic)

2023-11-07 10:36 UTC, sourabh-awashti commented on 120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java
> +  public ResponseDTO<List<InfrastructureResponse>>
done

2023-11-07 10:36 UTC, sourabh-awashti commented on 120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java
> +  listAccessInfrastructures(@Parameter(description = NGCommonEntityConstants.PAGE_PARAM_MESSAGE) @QueryParam(
done

2023-11-07 10:37 UTC, sourabh-awashti commented on 120-ng-manager/src/test/java/io/harness/ng/core/infrastructure/resource/InfrastructureResourceTest.java
> +    doReturn(AccessCheckResponseDTO.builder()
done

2023-11-07 10:37 UTC, sourabh-awashti commented
trigger uts

2023-11-07 10:54 UTC, tchaurasiya submitted a review, later dismissed

2023-11-07 11:29 UTC, lovish1999 approved these changes
LGTM

2023-11-07 13:30 UTC, sourabh-awashti commented
trigger uts

2023-11-07 13:33 UTC, sourabh-awashti commented
trigger codeformat

2023-11-07 15:37 UTC, lovish1999 approved these changes

2023-11-07 15:53 UTC, tchaurasiya approved these changes

2023-11-07 17:52 UTC, sourabh-awashti commented
trigger review

2023-11-07 17:54 UTC, sourabh-awashti commented
trigger messagecheck

2023-11-07 17:57 UTC, sourabh-awashti commented
trigger messagecheck

2023-11-07 17:58 UTC, sourabh-awashti commented
trigger messagecheck

2023-11-07 17:58 UTC, merged