feat:[CDS-83465]: Fix for Env variables not resolving at Runtime
harness/harness-core pull request #55050
Opened 2023-11-06 13:12 UTC by piyush-bhuwalka

## Describe your changes

Fix for Env variables not resolving at Runtime

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-06 13:48 UTC, piyush-bhuwalka commented
trigger uts

2023-11-07 05:59 UTC, piyush-bhuwalka commented
trigger uts

2023-11-07 06:04 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_4DB40EFrcbn5Kl1X:-NicNX8R8ck0cMXwLOme:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L58)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor:  we should use io.harness.data.structure.EmptyPredicate or org.apache.commons.lang3.StringUtils instead StringUtils from jooq.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:05 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_6WhW35UM2ghhvy-X:-NicNZKk32Z3lIDanjq-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L108)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we resolve buildCommandOptions expressions here by using cdExpressionResolver?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:05 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_5YgxAErFhqIicIfz:-NicNbGK478_NmbJPvWv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L121)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: move get connector to a separate method with identifier ref logic.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:06 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_5ixG3YKZPNSYpQ1e:-NicNsTn5gqBH_PrxUb8:b3r26yy) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L124)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What if connectorDTO value is not present?
</blockquote></details>

connectorConfigDTO instanceof DockerConnectorDTO checks for null as well


<!-- Sent from Reviewable.io -->

2023-11-07 06:06 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_4jlJ0bX9d2MXYahs:-NicNvMABsLUUhY9g4WI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L164)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: remove this comment
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:06 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_58k337R9mkQfCLkh:-NicNwCKCwFwLDCR4yJW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L168)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: Getting sam dir should be moved to a separate method.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:06 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_AP8P2TWpOsvnv6-X:-NicNzYGA_hU_E0KbN-Z:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L73)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor:  we should use io.harness.data.structure.EmptyPredicate or org.apache.commons.lang3.StringUtils instead StringUtils from jooq.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:06 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_6mMq77UJhId7e_aT:-NicO-YM8_JLSyUNCluG:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L172)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: remove comment here.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:07 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_7yfO78WDQSciVDRa:-NicO1iW6Dbv1o-7Oz3t:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L176)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move getting AwsSamInfrastructureOutcome to a separate method and do instanceOf check
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:07 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 184 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_8IbT7EjFrC-tVa-q:-NicO34X00dfBKh3L2Jn:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L184)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

why additional cast, use awsSamInfrastructureOutcom.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:07 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 195 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_9n810MTo5UGy2bJE:-NicO5Eb89z5zzSAvXgq:bflu35j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L195)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What if connectorInfoDTO value is not present?
</blockquote></details>

awsCredentialSpecDTO instanceof AwsManualConfigSpecDTO checks for null as well


<!-- Sent from Reviewable.io -->

2023-11-07 06:07 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 227 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_8syjEMYJbUm13yGu:-NicOF5q4J_AqXhRuSvR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L227)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: remove comment here
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:08 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 232 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_8wnb7Fgp4nl8SpmQ:-NicOG3uBskQSc1nhNXm:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L232)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Move getting sam dir to separate method
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:08 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 271 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_9WtdBRqbhWd-RKLi:-NicOHGTDA_3Yog4olfV:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L271)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do validateEnvVariables and for AWS SAM build step.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 06:40 UTC, piyush-bhuwalka commented
trigger uts

2023-11-07 07:03 UTC, piyush-bhuwalka commented
trigger uts

2023-11-07 07:24 UTC, piyush-bhuwalka commented
/rebase

2023-11-07 07:30 UTC, piyush-bhuwalka commented
trigger uts

2023-11-07 08:41 UTC, ivan-83 requested changes
LGTM with minor comments.

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55050#-:-NicwCgK4soQYJrhkFC3:b-o9mibo)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 195 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_9n810MTo5UGy2bJE:-NicviyaAQiVft9uueFR:b-yb432m) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L195)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

awsCredentialSpecDTO instanceof AwsManualConfigSpecDTO checks for null as well
</blockquote></details>

We will get NPE here connectorDTO.get().getConnector() if the value is not present.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 271 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_9WtdBRqbhWd-RKLi:-Nicvzik4FRotB_lEOs3:btycnpx) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L271)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Done
</blockquote></details>

We could move this method to some utility class and reuse it. 


<!-- Sent from Reviewable.io -->

2023-11-07 09:39 UTC, piyush-bhuwalka commented
trigger uts

2023-11-07 09:40 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 195 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_9n810MTo5UGy2bJE:-Nid8nxj7J8xdgBy_kun:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L195)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We will get NPE here connectorDTO.get().getConnector() if the value is not present.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-07 09:40 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 271 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_9WtdBRqbhWd-RKLi:-Nid8pdT42gG4mdcvWZO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L271)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We could move this method to some utility class and reuse it.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-08 06:15 UTC, piyush-bhuwalka commented
trigger uts

2023-11-08 06:37 UTC, piyush-bhuwalka commented
trigger uts

2023-11-08 07:54 UTC, piyush-bhuwalka commented
trigger ut7

2023-11-08 09:27 UTC, mani5h-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java` line 118 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiFNkI9GawbIf0RVo6:-NiiFNkI9GawbIf0RVo7:b-izfsvh) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java#L118)):*
> ```Java
>   }
> 
>   private AwsSamInfrastructureOutcome getAwsSamInfrastructureOutcome(Ambiance ambiance) {
> ```

nit: looks like never used, remove?


<!-- Sent from Reviewable.io -->

2023-11-08 09:29 UTC, mani5h-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java` line 130 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiFjiO4RVW_g-2SKqp:-NiiFjiO4RVW_g-2SKqq:bep4zl7) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java#L130)):*
> ```Java
>   }
> 
>   private Optional<ConnectorResponseDTO> getOptionalConnectorResponseDTO(String awsConnectorRef, NGAccess ngAccess) {
> ```

this too, is this used?


<!-- Sent from Reviewable.io -->

2023-11-08 09:36 UTC, mani5h-harness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 101 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiHGJD0Vw6rXudkuPH:-NiiHGJD0Vw6rXudkuPI:b-3cm9dm) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L101)):*
> ```Java
> 
>     Map<String, String> envVars = getEnvironmentVariables(ambiance, awsSamBuildStepParameters);
>     awsSamStepHelper.removeEnvVarsWithoutSecretRef(envVars);
> ```

this is a bit confusing, removeEnvVarsWithoutSecretRef actually removes envVars with secret ref?


<!-- Sent from Reviewable.io -->

2023-11-08 09:55 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java` line 118 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiFNkI9GawbIf0RVo6:-NiiLmwO1wmvnrwRnZ2G:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java#L118)):*
<details><summary><i>Previously, mani5h-harness wrote…</i></summary><blockquote>

nit: looks like never used, remove?
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2023-11-08 09:55 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java` line 130 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiFjiO4RVW_g-2SKqp:-NiiLpjzBJrN_ksBRvXZ:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java#L130)):*
<details><summary><i>Previously, mani5h-harness wrote…</i></summary><blockquote>

this too, is this used?
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2023-11-08 09:55 UTC, piyush-bhuwalka commented
trigger uts

2023-11-08 10:07 UTC, ivan-83 reviewed
LGTM with minor comments

> Reviewed 5 of 8 files at r6, 6 of 7 files at r7, 1 of 1 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55050#-:-NiiObDr390IGypu13ce:b-z5hs9a)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_5ixG3YKZPNSYpQ1e:-NiiKCSm7VPOhFgsO8my:b6o1ok8) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L124)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

connectorConfigDTO instanceof DockerConnectorDTO checks for null as well
</blockquote></details>

connectorConfigDTO instanceof DockerConnectorDT check will solve it.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 101 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiHGJD0Vw6rXudkuPH:-NiiKJLo3SI9RVCN1Mjg:bv9laze) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L101)):*
<details><summary><i>Previously, mani5h-harness wrote…</i></summary><blockquote>

this is a bit confusing, removeEnvVarsWithoutSecretRef actually removes envVars with secret ref?
</blockquote></details>

We are storing secrets in the secrets section on k8s cluster not as env variables
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 282 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiM9Ma9IPAAVAnVIZ1:-NiiM9Ma9IPAAVAnVIZ2:b-cpcl4w) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L282)):*
> ```Java
>     return envVars.entrySet()
>         .stream()
>         .filter(entry -> entry.getValue().contains("ngSecretManager"))
> ```

Can be done in next PR (entry.getValue()!=null && entry.getValue().contains("ngSecretManager"))
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 286 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiOKiu8UK4mnlb0DSj:-NiiOKiu8UK4mnlb0DSk:bw8l3yt) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L286)):*
> ```Java
>   }
> 
>   public Map<String, String> removeEnvVarsWithoutSecretRef(Map<String, String> envVars) {
> ```

Minor: removeEnvVarsWithoutSecretRe >> removeAllEnvVarsWithSecretRef
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 287 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiO1C3-qgQKFyzY445:-NiiO1C3-qgQKFyzY446:b-o4ia36) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L287)):*
> ```Java
> 
>   public Map<String, String> removeEnvVarsWithoutSecretRef(Map<String, String> envVars) {
>     HashMap<String, String> hashMap = new HashMap<>();
> ```

here we can call the getEnvVarsWithSecretRef method not duplicate code
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 291 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiMKhg18pRp5AKlj7N:-NiiMKhg18pRp5AKlj7O:bjxmdy9) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L291)):*
> ```Java
>         envVars.entrySet()
>             .stream()
>             .filter(entry -> entry.getValue().contains("ngSecretManager"))
> ```

The same as above (entry.getValue()!=null && entry.getValue().contains("ngSecretManager"))
"ngSecretManager" >> can be const
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamBuildPluginInfoProvider.java` line 84 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiMjPa8w6tIuXoJxaU:-NiiMjPa8w6tIuXoJxaV:b9ggfbo) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamBuildPluginInfoProvider.java#L84)):*
> ```Java
>     pluginDetailsBuilder.setImageDetails(imageDetails);
> 
>     Map<String, String> envVars;
> ```

Minor: We can put the comment about why we are only supplying secrets in getPluginInfo
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java` line 104 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiNK8J4kONod4VwX4O:-NiiNK8J4kONod4VwX4P:b-in1qto) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java#L104)):*
> ```Java
>     pluginDetailsBuilder.setImageDetails(imageDetails);
> 
>     Map<String, String> envVars;
> ```

The same here put the comment why we are doing this. 


<!-- Sent from Reviewable.io -->

2023-11-08 10:34 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/55050#-Ni_5ixG3YKZPNSYpQ1e:-NiiU5cj9kYxNUZFS_fI:b-5ok6sh) ([raw file](https://github.com/harness/harness-core/blob/9394aa4c2e3564f30c8e7d5b7cd1a7c6095d5495/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamBuildStep.java#L124)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

connectorConfigDTO instanceof DockerConnectorDT check will solve it.
</blockquote></details>

Its already there


<!-- Sent from Reviewable.io -->

2023-11-08 10:34 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 282 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiM9Ma9IPAAVAnVIZ1:-NiiUmcL1g-RrNbR0MoR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L282)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can be done in next PR (entry.getValue()!=null && entry.getValue().contains("ngSecretManager"))
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-08 10:34 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 291 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiMKhg18pRp5AKlj7N:-NiiUoMmDKLATwPPmBMJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L291)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above (entry.getValue()!=null && entry.getValue().contains("ngSecretManager"))
"ngSecretManager" >> can be const
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-08 10:34 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 287 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiO1C3-qgQKFyzY445:-NiiUpLL0HU542wBgqkZ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L287)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

here we can call the getEnvVarsWithSecretRef method not duplicate code
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-08 10:34 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 286 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiOKiu8UK4mnlb0DSj:-NiiUqZQ0ZQjpB-WbVPX:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L286)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: removeEnvVarsWithoutSecretRe >> removeAllEnvVarsWithSecretRef
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-08 10:34 UTC, piyush-bhuwalka commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java` line 104 at r8](https://reviewable.io/reviews/harness/harness-core/55050#-NiiNK8J4kONod4VwX4O:-NiiUub1604Tci3w9rjf:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee870abcaddeab2e3b45ffa971cfdccccfb362d4/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamDeployPluginInfoProvider.java#L104)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same here put the comment why we are doing this.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-08 10:35 UTC, piyush-bhuwalka commented
trigger uts

2023-11-08 11:10 UTC, ivan-83 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55050#-:-Niic9gT-taEdrQ17Z4K:bnfp4nl)* status: 12 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-08 11:10 UTC, ivan-83 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55050)* status: 12 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-08 13:05 UTC, mani5h-harness approved these changes
> Reviewed 5 of 8 files at r6, 4 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55050)* status: 5 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-11-08 13:05 UTC, piyush-bhuwalka commented
trigger review

2023-11-08 13:07 UTC, merged