feat: [CDS-83055]: Integrate rancher delete token API
harness/harness-core pull request #55114
Opened 2023-11-07 13:01 UTC by abhinavsingh1196

## Describe your changes
Continued from https://github.com/harness/harness-core/pull/55058
This change integrates the rancher delete token API (more specifically, generic k8s task cleaner) with:
- NG K8s delegate task
- NG Native helm delegate task
- v1 and v2 instance sync (K8s & Native helm)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-08 08:26 UTC, abhinavsingh1196 commented
trigger uts

2023-11-08 08:53 UTC, abhinavsingh1196 commented
trigger smartchecks

2023-11-08 08:54 UTC, abhinavsingh1196 commented
trigger gitleaks

2023-11-08 09:16 UTC, abhinavsingh1196 commented
trigger checkstylecodeformat,commonchecks,messagecheck,pmd,codebasehash

2023-11-08 09:48 UTC, abosii-harness requested changes

2023-11-08 11:36 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sngtask/K8sTaskNG.java
> +        cleanupDTOBuilder.infraDelegateConfig(k8sDeployRequest.getK8sInfraDelegateConfig());
thanks for pointing out, we want to cleanup in case task fails as well. Will move this above

2023-11-08 12:17 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmCommandRequestNG.java
> +  private KubernetesConfig kubernetesConfig;
we can avoid it, I chose the path of least refactors but I guess there is another way with similar amount of refactors where we don't use a kryo entity

2023-11-08 15:00 UTC, abhinavsingh1196 commented
trigger uts

2023-11-08 17:11 UTC, abhinavsingh1196 commented
trigger uts

2023-11-09 05:20 UTC, abhinavsingh1196 commented
/rebase

2023-11-09 05:21 UTC, abhinavsingh1196 commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/helm/HelmCommandRequestNG.java
> +  private KubernetesConfig kubernetesConfig;
Moved this to a separate delegate side class

2023-11-09 05:21 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sngtask/K8sTaskNG.java
> +        cleanupDTOBuilder.infraDelegateConfig(k8sDeployRequest.getK8sInfraDelegateConfig());
Done

2023-11-09 05:22 UTC, abhinavsingh1196 commented
trigger uts

2023-11-09 13:10 UTC, abhinavsingh1196 commented
/rebase

2023-11-09 13:12 UTC, abhinavsingh1196 commented
trigger uts

2023-11-10 08:36 UTC, abhinavsingh1196 commented
trigger uts

2023-11-10 11:40 UTC, abhinavsingh1196 commented
trigger uts

2023-11-10 12:55 UTC, abhinavsingh1196 commented
trigger ut7

2023-11-10 14:02 UTC, TarunUba1 approved these changes
Looks good just one thing that we are saving same data twice
`          return PodDetailsRequest.builder()
              .kubernetesConfig(kubernetesConfig)
              .namespace(namespace)
              .releaseName(releaseName)
              .helmChartInfo(releaseDetails.getHelmChartInfo())
              .helmVersion(releaseDetails.getHelmVersion())
              .workloadLabelSelectors(releaseDetails.getWorkloadLabelSelectors())
              .cleanupDTO(K8sTaskCleanupDTO.builder()
                              .infraDelegateConfig(k8sInfraDelegateConfig)
                              .generatedKubeConfig(kubernetesConfig)
                              .build())
              .build();
        })`
        i see that wherever we are specifying cleaupDTO we always have kubernetesConfig
        May be we can have just added infradelegateConfig only and generated K8sTaskCleanupDTO from them

2023-11-20 09:10 UTC, abhinavsingh1196 commented
/rebase

2023-11-20 13:30 UTC, abhinavsingh1196 commented
Closing this PR for now, since testing is blocked by https://harness.atlassian.net/browse/CDS-84922
Will re-open and test this once the blocking issue is addressed.

2023-11-20 14:16 UTC, abhinavsingh1196 commented
Re-opening this PR, we are going to fix the interrupt issue independently since it does not have a significant impact on overall user experience.

2023-11-20 14:28 UTC, abhinavsingh1196 commented
trigger uts

2023-11-20 14:40 UTC, abosii-harness approved these changes

2023-11-20 15:33 UTC, alebuh approved these changes

2023-11-21 06:25 UTC, abhinavsingh1196 commented
trigger uts

2023-11-21 10:48 UTC, abhinavsingh1196 commented
trigger ut6,ut7,ut8,ut9

2023-11-22 04:55 UTC, abhinavsingh1196 commented
trigger uts

2023-11-22 08:34 UTC, abhinavsingh1196 commented
trigger ut4,ut5,ut7

2023-11-22 11:57 UTC, abhinavsingh1196 commented
trigger ut4,ut5,ut7

2023-11-22 13:48 UTC, abhinavsingh1196 commented
trigger ut5,ut7

2023-11-23 05:37 UTC, merged

2023-11-23 05:41 UTC, abhinavsingh1196 commented
FM'ed because unrelated tests were continuously failing.