fix: [CODE-431]: Update API endpoint for listing repos and move to getGeneralResponse
harness/harness-core pull request #55120
Opened 2023-11-07 17:25 UTC by akhilpandey1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-07 17:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=55120) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=55120) before we can accept your contribution.<br/><hr/>**Akhilesh Pandey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=55120) it.</sub>

2023-11-07 18:04 UTC, akhilpandey1 commented
trigger messagecheck

2023-11-07 22:23 UTC, abhinav-harness submitted a review, later dismissed

2023-11-08 11:32 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55120)* status: 6 file(s) to review. 1 change requests. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeRepositoryResourceImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/55120#-Niih0rX8ojru_nnCI6T:-Niih0rX8ojru_nnCI6U:b-3zfih9) ([raw file](https://github.com/harness/harness-core/blob/1830c45b5e1fd949b990f34ad99cd7e6f222885b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeRepositoryResourceImpl.java#L94)):*
> ```Java
>     }
> 
>     List<CodeRepoResponseDTO> codeViewRepos = NGRestUtils.getGeneralResponse(codeViewRepoClient.getRepos(
> ```

Please elaborate on this change.


<!-- Sent from Reviewable.io -->

2023-11-08 21:08 UTC, akhilpandey1 commented
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeRepositoryResourceImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/55120#-Niih0rX8ojru_nnCI6T:-NikkhQC3yog7U-cDnWY:b-299i6u) ([raw file](https://github.com/harness/harness-core/blob/1830c45b5e1fd949b990f34ad99cd7e6f222885b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeRepositoryResourceImpl.java#L94)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Please elaborate on this change.
</blockquote></details>

This is done because the usual NGRestUtils.getResponse() expects the data to be present inside the object under the `data` key, whereas harness-code doesn't follow this suite and sends the API data directly and it's not enclosed in an object as expected by previous call which was failing during validation.


<!-- Sent from Reviewable.io -->

2023-11-09 05:31 UTC, Jimit09Gandhi approved these changes
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55120)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-11-09 07:04 UTC, johannesHarness commented on platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java
> +  public static final String CODE_REPOSITORY = "CODE_REPOSITORY";
this is exactly the same as we define in `CodeRepositoryResourceImpl` line 54. Do they have to match to work, and if so, should we have one source of truth. if not then ignore the comment

2023-11-09 07:05 UTC, johannesHarness submitted a review, later dismissed

2023-11-09 09:12 UTC, akhilpandey1 commented on platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java
> +  public static final String CODE_REPOSITORY = "CODE_REPOSITORY";
Good catch, now we're referencing this in CodeRepositoryResourceImpl and not defining it again. Thanks

2023-11-09 12:20 UTC, enver-bisevac approved these changes
LGTM

2023-11-09 12:33 UTC, Jimit09Gandhi approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55120)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-09 12:38 UTC, merged