feat: [CDS-81574]: Adding Helm Steady state check as account settings.
harness/harness-core pull request #55181
Opened 2023-11-08 14:26 UTC by GoelPratyush99

## Describe your changes
Adding Helm Steady state check as account settings.
<img width="685" alt="Screenshot 2023-11-08 at 7 44 18 PM" src="https://github.com/harness/harness-core/assets/97931011/a0afd09a-1dc3-4245-843c-537344440d60">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-08 14:28 UTC, GoelPratyush99 commented
trigger uts

2023-11-08 14:33 UTC, abosii-harness requested changes

2023-11-08 14:33 UTC, abosii-harness commented on 120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
> +  - identifier: enable_steady_state_for_jobs_native_helm
should be this instead native_helm_enable_steady_state_for_jobs

2023-11-08 14:33 UTC, abosii-harness commented on 120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
>      allowedScopes:
Don't we want to be configurable per project?

2023-11-08 14:33 UTC, abosii-harness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
> +            .k8SteadyStateCheckEnabled(ENABLE_STEADY_STATE_FOR_JOBS_TRUE_VALUE.equals(steadyStateForJobsSettingValue))
The settings shouldn't change the behaviour of the flag but instead should be a different parameter that will skip the jobs steady state check, I believe this should be assigned with V2 FF

2023-11-08 17:29 UTC, GoelPratyush99 commented on 120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
> +  - identifier: enable_steady_state_for_jobs_native_helm
done

2023-11-08 17:31 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
> +            .k8SteadyStateCheckEnabled(ENABLE_STEADY_STATE_FOR_JOBS_TRUE_VALUE.equals(steadyStateForJobsSettingValue))
done

2023-11-08 17:45 UTC, GoelPratyush99 commented on 120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
>      allowedScopes:
done

2023-11-08 17:46 UTC, GoelPratyush99 commented
trigger uts

2023-11-09 05:40 UTC, abhinavsingh1196 requested changes

2023-11-09 05:40 UTC, abhinavsingh1196 commented on 120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
> +    name: Enable Steady State For Jobs In Native Helm Deployment
nit: Should this be
Perform steady state **check** for Jobs in Native Helm deployments
?

2023-11-09 05:40 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
> +    String steadyStateForJobsSettingValue = "";
duplicated code in both helm steps, good candidate to extract it. Also, we can include the below equality check in that method too and return boolean `enableSteadyStateCheckForJobs` from it

2023-11-09 05:40 UTC, abhinavsingh1196 commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  HELM_COMMAND_TASK_NG_JOBS_STEADY_STATE_CHECK(TaskGroup.HELM, "Helm Command Task with Oci Helm Ecr Config");
Wrong task description

2023-11-09 07:53 UTC, GoelPratyush99 commented on 951-delegate-task-commons/src/main/java/software/wings/beans/TaskType.java
> +  HELM_COMMAND_TASK_NG_JOBS_STEADY_STATE_CHECK(TaskGroup.HELM, "Helm Command Task with Oci Helm Ecr Config");
done

2023-11-09 07:53 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmRollbackStep.java
> +    String steadyStateForJobsSettingValue = "";
done

2023-11-09 07:53 UTC, GoelPratyush99 commented on 120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
> +    name: Enable Steady State For Jobs In Native Helm Deployment
done

2023-11-09 07:53 UTC, GoelPratyush99 commented
trigger uts

2023-11-09 07:57 UTC, GoelPratyush99 commented
trigger uts

2023-11-09 10:22 UTC, acasian-harness reviewed
@GoelPratyush99 have we validated the override part: If the setting is at project level true but false for org and account level - is this considering enabled?

2023-11-09 12:20 UTC, GoelPratyush99 reviewed
Hey @acasian-harness! I have verified the following scenario. I am not sure what overrides does so I am leaving it as true as its true for others having all the scope. 

project               org                   account               allow overrides              result
true                    false                 false                    false                                 true
true                    false                 false                    true                                  true

![Screenshot 2023-11-09 at 5.38.39 PM.png](https://files.reviewableusercontent.io/images/reviewable/97931011/8z0gA7z94mLKRJFyrn07chYD/Screenshot%202023-11-09%20at%205.38.39%E2%80%AFPM.png)

![Screenshot 2023-11-09 at 5.38.59 PM.png](https://files.reviewableusercontent.io/images/reviewable/97931011/K6fAX-2kOG1yYZ8vyYoFUOnX/Screenshot%202023-11-09%20at%205.38.59%E2%80%AFPM.png)

![Screenshot 2023-11-09 at 5.40.02 PM.png](https://files.reviewableusercontent.io/images/reviewable/97931011/LgysXOqaPKSiG8ikhmbHIL0Q/Screenshot%202023-11-09%20at%205.40.02%E2%80%AFPM.png)

![Screenshot 2023-11-09 at 5.40.38 PM.png](https://files.reviewableusercontent.io/images/reviewable/97931011/UFkausDOUqufxrR638_NLl5s/Screenshot%202023-11-09%20at%205.40.38%E2%80%AFPM.png)

![Screenshot 2023-11-09 at 5.41.30 PM.png](https://files.reviewableusercontent.io/images/reviewable/97931011/dk8Vli23ZaRUp5sSLcfV8zqH/Screenshot%202023-11-09%20at%205.41.30%E2%80%AFPM.png)

![Screenshot 2023-11-09 at 5.42.10 PM.png](https://files.reviewableusercontent.io/images/reviewable/97931011/54ybTvE1x-yXcG1A2T0-u0pL/Screenshot%202023-11-09%20at%205.42.10%E2%80%AFPM.png)

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55181#-:-Nio-Fag9mgQhNh8YOaI:b-yt7e08)* status: 18 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-09 12:44 UTC, nishantsaini20 approved these changes
Approved for settings.yml

2023-11-09 12:47 UTC, GoelPratyush99 commented
trigger uts

2023-11-10 06:16 UTC, GoelPratyush99 commented
**None of the UT failure are associated with my changes**

2023-11-10 07:12 UTC, TarunUba1 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/helm/HelmRollbackStepTest.java
> +  @Owner(developers = ABOSII)
You are the owner here

2023-11-10 07:12 UTC, abhinavsingh1196 submitted a review, later dismissed

2023-11-10 07:12 UTC, abhinavsingh1196 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/helm/HelmRollbackStepTest.java
> +  @Owner(developers = ABOSII)
wrong owner

2023-11-10 07:18 UTC, TarunUba1 submitted a review, later dismissed

2023-11-10 07:18 UTC, TarunUba1 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/helm/HelmRollbackStepTest.java
> +  @Owner(developers = ABOSII)
copying my comment

2023-11-10 07:22 UTC, abosii-harness requested changes

2023-11-10 07:23 UTC, GoelPratyush99 commented on 120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml
> +    allowOverrides: false
done

2023-11-10 07:24 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/helm/HelmRollbackStepTest.java
> +  @Owner(developers = ABOSII)
done

2023-11-10 07:24 UTC, GoelPratyush99 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/helm/HelmRollbackStepTest.java
> +  @Owner(developers = ABOSII)
done

2023-11-10 07:58 UTC, GoelPratyush99 commented
trigger uts

2023-11-10 08:00 UTC, TarunUba1 approved these changes

2023-11-10 08:03 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java
> +              filterKubernetesJobResource(entry.getValue(), commandRequest.isUseSteadyStateCheckForJobs());
done

2023-11-10 08:53 UTC, GoelPratyush99 commented
trigger uts

2023-11-10 08:55 UTC, GoelPratyush99 commented
trigger uts

2023-11-10 09:01 UTC, TarunUba1 approved these changes

2023-11-10 10:03 UTC, markoharness approved these changes

2023-11-10 10:03 UTC, TarunUba1 approved these changes

2023-11-10 10:14 UTC, nishantsaini20 approved these changes
Approved for ng-settings

2023-11-10 10:15 UTC, GoelPratyush99 commented
trigger review

2023-11-10 10:52 UTC, merged