fix: [CDS-83763]: support input value when sent on whenCondition
harness/harness-core pull request #55192
Opened 2023-11-08 21:13 UTC by lasdox

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-08 21:13 UTC, lasdox commented
trigger uts

2023-11-09 00:17 UTC, lasdox commented
trigger uts

2023-11-09 04:49 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55192)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/RunPreFacilitationChecker.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/55192#-NimPGeT9g2nZAjZIZVl:-NimPGeT9g2nZAjZIZVm:bo2ursz) ([raw file](https://github.com/harness/harness-core/blob/b93a7044ff23d83a9df7939c588eed0c5de688d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/RunPreFacilitationChecker.java#L54)):*
> ```Java
>   private static final String MAX_LEVELS_LIMIT_REACHED_ERROR =
>       "The pipeline has reached the maximum nesting allowed for an execution. Please simplify the pipeline configuration so that it does not breach the allowed limit of nesting";
>   private static final Map<String, Object> CHECKER_EXPRESSION_CTX = Map.of("input", true);
> ```

Instead of this, we can add handling in RunInfoUtils which is used by all planCreators to combine when condition.
If condition is <+input> then don't consider would be apt solution


<!-- Sent from Reviewable.io -->

2023-11-09 12:30 UTC, lasdox commented
trigger uts

2023-11-09 12:42 UTC, ankittiwari-harness commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java
> +  private static String RUNTIME_EXSPRESSION = "<+input>";
nit: expression typo

2023-11-09 12:47 UTC, sahilhindwani-harness commented
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/RunPreFacilitationChecker.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/55192#-NimPGeT9g2nZAjZIZVl:-Nio6l2B0pTqDgzy1m1Q:b32v57) ([raw file](https://github.com/harness/harness-core/blob/b93a7044ff23d83a9df7939c588eed0c5de688d0/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/RunPreFacilitationChecker.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Instead of this, we can add handling in RunInfoUtils which is used by all planCreators to combine when condition.
If condition is <+input> then don't consider would be apt solution
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-11-09 12:48 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55192)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/55192#gh-1387947816:-Nio5ucp5oXe4Wjco24M:bbrezr8) ([raw file](https://github.com/harness/harness-core/blob/86b882b19c49cf4ef208aaac66392f1d50925714/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L38)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

nit: expression typo
</blockquote></details>

we already have this via NGExpressionUtils.matchesInputSetPattern
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/55192#-Nio6KdCECTRul0HOPsm:-Nio6KdCECTRul0HOPsn:bs8vh6a) ([raw file](https://github.com/harness/harness-core/blob/86b882b19c49cf4ef208aaac66392f1d50925714/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L106)):*
> ```Java
> 
>   private String combineExpressions(String statusExpression, String conditionExpression) {
>     if (EmptyPredicate.isNotEmpty(conditionExpression) && !RUNTIME_EXSPRESSION.equals(conditionExpression)) {
> ```

we discussed solution with product

in this method -> getGivenRunCondition should change that if empty string then return as it is and test it should work as false
cc: @sahilhindwani-harness 


<!-- Sent from Reviewable.io -->

2023-11-09 12:53 UTC, lasdox commented
trigger uts

2023-11-09 14:47 UTC, archit-harness reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55192)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/55192#-Nio6KdCECTRul0HOPsm:-NioYCXe9tYCfUcDodZf:b-683c3n) ([raw file](https://github.com/harness/harness-core/blob/86b882b19c49cf4ef208aaac66392f1d50925714/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L106)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we discussed solution with product

in this method -> getGivenRunCondition should change that if empty string then return as it is and test it should work as false
cc: @sahilhindwani-harness
</blockquote></details>

done @sahilhindwani-harness resolving as i will be OOO


<!-- Sent from Reviewable.io -->

2023-11-09 18:29 UTC, lasdox commented
trigger uts

2023-11-09 21:09 UTC, lasdox commented
trigger messagecheck

2023-11-13 04:49 UTC, sahilhindwani-harness approved these changes
> Reviewed 2 of 4 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55192)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-16 12:47 UTC, lasdox commented
trigger review

2023-11-16 12:49 UTC, merged