Delegate notification template registration
harness/harness-core pull request #55194
Opened 2023-11-08 23:29 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-14 16:57 UTC, jennyjames21 commented
trigger uts

2023-11-14 17:00 UTC, jennyjames21 commented
trigger uts

2023-11-15 06:09 UTC, xingchi-jin commented on 400-rest/src/main/java/io/harness/notifications/NotificationTemplateRegistrar.java
> +        notificationClient.saveNotificationTemplate(Team.OTHER, template, true);
lack some background knowledge, where is the template saved to ? and where the template is used ?

2023-11-15 06:09 UTC, xingchi-jin submitted a review, later dismissed

2023-11-15 06:11 UTC, xingchi-jin commented
btw, in the scrrnshot, the delegate disconnect email notification looks like a celebration  : P

2023-11-15 18:56 UTC, jennyjames21 commented on 400-rest/src/main/java/io/harness/notifications/NotificationTemplateRegistrar.java
> +        notificationClient.saveNotificationTemplate(Team.OTHER, template, true);
Templates saved in notification service DB on template registration
When the client sends the notification trigger to the notification service,  service will fetch the customer rule, and based on the channel type(email, slack) it fetches the template from DB to send the notification to customer.

2023-11-16 21:55 UTC, raghuAtWings requested changes

2023-11-16 21:55 UTC, raghuAtWings commented on 400-rest/src/main/resources/notificationtemplates/webhook/delegate_about_to_expire.txt
> +    "text": "Harness Delegate ${DELEGATE_ID} expires on ${EXPIRY_TIME}. Make sure auto upgrade is ON to get the latest image."
we should change the text to

Harness Delegate ${DELEGATE_ID} expires on ${EXPIRY_TIME}. Either set auto upgrade is ON or upgrade to latest version. More information at https://developer.harness.io/docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration/

2023-11-16 21:55 UTC, raghuAtWings commented on 400-rest/src/main/resources/notificationtemplates/webhook/delegate_expired.txt
> +    "text": "Harness Delegate ${DELEGATE_ID} expired on ${EXPIRY_TIME}. Upgrade the delegate"
Harness Delegate ${DELEGATE_ID} expired on ${EXPIRY_TIME}. Upgrade the delegate. More infromation at https://developer.harness.io/docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration/

2023-11-16 21:55 UTC, raghuAtWings commented on 400-rest/src/main/resources/notificationtemplates/slack/delegate_expired.txt
> +    "text": "Harness Delegate ${DELEGATE_ID} expired on ${EXPIRY_TIME}. Upgrade the delegate"
are we sending delegate id or name?

2023-11-16 22:46 UTC, jennyjames21 commented on 400-rest/src/main/resources/notificationtemplates/slack/delegate_expired.txt
> +    "text": "Harness Delegate ${DELEGATE_ID} expired on ${EXPIRY_TIME}. Upgrade the delegate"
updated

2023-11-16 22:47 UTC, jennyjames21 commented on 400-rest/src/main/resources/notificationtemplates/webhook/delegate_expired.txt
> +    "text": "Harness Delegate ${DELEGATE_ID} expired on ${EXPIRY_TIME}. Upgrade the delegate"
updated

2023-11-21 00:42 UTC, jennyjames21 commented
trigger messagecheck

2023-11-21 20:35 UTC, raghuAtWings submitted a review, later dismissed

2023-11-22 04:09 UTC, jennyjames21 commented
trigger uts

2023-11-22 17:07 UTC, jennyjames21 commented
trigger uts

2023-11-22 21:40 UTC, jennyjames21 commented
trigger uts

2023-11-24 05:25 UTC, vanshBhatia-A4k9 commented on platform-service/modules/notification-service/src/main/resources/templates/email/delegate_about_to_expire.txt
> +                Delegate ${delegateId} is getting expired on ${expiryDate}. Please make sure auto grade is ON to get the latest build image.
```suggestion
                Delegate ${delegateId} is getting expired on ${expiryDate}. Please make sure auto upgrade is ON to get the latest build image.
```

2023-11-27 16:59 UTC, jennyjames21 commented
trigger uts

2023-11-27 20:41 UTC, jennyjames21 commented
trigger ut4

2023-11-27 23:28 UTC, raghuAtWings approved these changes

2023-11-27 23:29 UTC, merged