feat: [CDS-83755]: Telemetry to Track Usage of Last Published Tag Expression
harness/harness-core pull request #55224
Opened 2023-11-09 10:57 UTC by sarthakkasat

## Describe your changes
Telemetry to Track Usage of Last Published Tag Expression

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-10 09:32 UTC, puthrayaharness requested changes

2023-11-10 09:32 UTC, puthrayaharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> -      DockerConnectorDTO connectorDTO, List<EncryptedDataDetail> encryptedDataDetails, String connectorRef) {
Why not inject the InstrumentationHelper?

2023-11-10 09:32 UTC, puthrayaharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java
> -      DockerConnectorDTO connectorDTO, List<EncryptedDataDetail> encryptedDataDetails, String connectorRef) {
Can we pass ambiance here instead of passing orgId, projectId etc

2023-11-10 09:36 UTC, sarthakkasat commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java` line 0 at r1](https://reviewable.io/reviews/harness/harness-core/55224#gh-1389137439:-Nis_PPv5soHh9mKik-E:b-gfef35) ([raw file](https://github.com/harness/harness-core/blob/ffb84f1fce71c868d60c96c4f3ed08dd8ac06c01/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java#L0)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Can we pass ambiance here instead of passing orgId, projectId etc
</blockquote></details>

We cannot inject instrumentHelper as it is a utility class
Will update the code to pass Ambiance


<!-- Sent from Reviewable.io -->

2023-11-10 09:37 UTC, naidu-harness requested changes

2023-11-10 09:37 UTC, naidu-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java
> +public class CDInstrumentationHelper extends InstrumentationHelper {
we should probably call this as ArtifactSourceInstrumentationHelper

2023-11-10 09:37 UTC, naidu-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java
> +    eventPropertiesMap.put(ARTIFACT_ACCOUNT, accountId);
check if we need to add accountId explictly. i think telemetry automatically adds this

2023-11-10 09:37 UTC, naidu-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java
> +      ArtifactConfig artifactConfig, String accountId, String orgId, String projectId, String eventName) {
we should extend this to more properties based on artifact types

2023-11-10 09:37 UTC, naidu-harness commented on 970-telemetry-beans/src/main/java/io/harness/telemetry/Category.java
> +  String CDS = "CDS";
i dont think this should be org structure. Check any existing telemtry events we sent from CDS

2023-11-10 09:37 UTC, naidu-harness commented on 125-cd-nextgen/src/test/java/io/harness/telemetry/helpers/CDInstrumentationHelperTest.java
> +  @Owner(developers = TEJAS)
change this

2023-11-10 09:38 UTC, puthrayaharness requested changes

2023-11-10 09:38 UTC, puthrayaharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java
> +  private final String userId = getUserId();
Why are we doing this? This looks incorrect. This should be part of the method and not a final field

2023-11-10 11:32 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55224)* status: 10 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-telemetry-beans/src/main/java/io/harness/telemetry/Category.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/55224#gh-1389146522:-Nisq03zC9_zwR_rt26h:b-1y1eao) ([raw file](https://github.com/harness/harness-core/blob/ffb84f1fce71c868d60c96c4f3ed08dd8ac06c01/970-telemetry-beans/src/main/java/io/harness/telemetry/Category.java#L15)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

i dont think this should be org structure. Check any existing telemtry events we sent from CDS
</blockquote></details>

For components like pipeline, connectors we were using the Category as Platform, will update this to use the same.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/55224#gh-1389140775:-NispaT_7UtZ6-fk0nDa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ffb84f1fce71c868d60c96c4f3ed08dd8ac06c01/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java#L37)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

we should probably call this as ArtifactSourceInstrumentationHelper
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55224#gh-1389146879:-NispapT82gt72VBoQJo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ffb84f1fce71c868d60c96c4f3ed08dd8ac06c01/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java#L39)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Why are we doing this? This looks incorrect. This should be part of the method and not a final field
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/55224#gh-1389145707:-NissnrV5k_ZbqfapXhU:bdtdxtk) ([raw file](https://github.com/harness/harness-core/blob/ffb84f1fce71c868d60c96c4f3ed08dd8ac06c01/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java#L42)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

we should extend this to more properties based on artifact types
</blockquote></details>

I discussed this with @puthrayaharness, currently all the required fields are present in ArtifactConfig, and we do not require any Artifact specific properties.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/55224#gh-1389142794:-Niss4SH8kKDvl8T-Zhg:b-91fid6) ([raw file](https://github.com/harness/harness-core/blob/ffb84f1fce71c868d60c96c4f3ed08dd8ac06c01/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/CDInstrumentationHelper.java#L44)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

check if we need to add accountId explictly. i think telemetry automatically adds this
</blockquote></details>

AccountId is currently added in all the existing events(Connector, Orgs, Projects). From amplitude I can see that in the response accountId is being set in the field groupId, in this case shall we update this?
___
*[`125-cd-nextgen/src/test/java/io/harness/telemetry/helpers/CDInstrumentationHelperTest.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/55224#gh-1389146634:-NisptyEBzi-BQxZ7yRB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ffb84f1fce71c868d60c96c4f3ed08dd8ac06c01/125-cd-nextgen/src/test/java/io/harness/telemetry/helpers/CDInstrumentationHelperTest.java#L38)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

change this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 12:11 UTC, naidu-harness approved these changes

2023-11-13 07:16 UTC, puthrayaharness submitted a review, later dismissed

2023-11-13 07:16 UTC, puthrayaharness commented
trigger uts

2023-11-13 08:45 UTC, sarthakkasat commented
trigger uts

2023-11-13 09:52 UTC, sarthakkasat commented
trigger uts

2023-11-13 11:37 UTC, sarthakkasat commented
trigger uts

2023-11-15 05:40 UTC, puthrayaharness approved these changes

2023-11-15 06:14 UTC, hingerabhinav approved these changes
> Reviewed 4 of 12 files at r1, 1 of 8 files at r2, 4 of 5 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55224)* status: 14 file(s) to review. 7. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-15 06:17 UTC, merged