feat: [PL-42423]: Added uniqueId in Service Account
harness/harness-core pull request #55239
Opened 2023-11-09 17:59 UTC by meenakshi-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-10 06:49 UTC, ankit-harness requested changes
> Reviewed 24 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 34 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nirwu9Y1Wzrj7Blcg8T:-Nirwu9Y1Wzrj7Blcg8U:b46mem4) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java#L37)):*
> ```Java
>   }
> 
>   public ServiceAccountDTOInternal getDTOFromServiceAccountInternal(ServiceAccountDTO serviceAccountDTO) {
> ```

Why a new DTO?
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-NirwLx29t3DcXsg3ZVu:-NirwLx29t3DcXsg3ZVv:bkfar5l) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java#L37)):*
> ```Java
> @OwnedBy(PL)
> @Slf4j
> public abstract class AddUniqueIdToNGEntitiesMigration<T extends UniqueIdAware> {
> ```

I don't think we need to make this class abstract

Also, there is a general purpose job that was written by Prateek to add uniqueId and parentId in entities. Pls check with him on how can we use that instead of registering a new migration
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nirw8D88EGnWz5BohTA:-Nirw8D9BlMNUTaXqwU9:b-my5r01) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java#L107)):*
> ```Java
>   }
> 
>   public String getId(UniqueIdAware entity) {
> ```

public String getId(T entity) {
    return entity.getUniqueId();
}
___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-NirxB9hByvxWgqMQoKE:-NirxB9hByvxWgqMQoKF:b-b42o7x) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java#L30)):*
> ```Java
> 
> @Getter
> @SuperBuilder
> ```

Why add SuperBuilder?
___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-NirxHkbC8IVK0jpFUQY:-NirxHkbC8IVK0jpFUQZ:bphgc05) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java#L33)):*
> ```Java
> @NoArgsConstructor
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @JsonIgnoreProperties(ignoreUnknown = true)
> ```

Why add this?


<!-- Sent from Reviewable.io -->

2023-11-10 07:00 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 34 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/serviceaccount/serviceaccount.proto` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0VevD-qa1GEHS6h9:-Nis0VevD-qa1GEHS6hA:bportxq) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/serviceaccount/serviceaccount.proto#L13)):*
> ```proto
> option go_package = "953_events_api";
> 
> message ServiceAccountEntityChangeDTO {
> ```

Where is this published and consumed? 
___
*[`970-ng-commons/BUILD.bazel` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0FxsB_cZVzNRHdwe:-Nis0FxsB_cZVzNRHdwf:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/BUILD.bazel#L105)):*
> ```Starlark
>         "//970-ng-commons/src/main/java/io/serializer/utils:module",
>         "//970-ng-commons/src/main/proto:970_ng_java_contract_proto",
>         "//980-commons:module",
> ```

Why this change?
___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/BUILD.bazel` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0E1F5Re2S8Me1c35:-Nis0E1F5Re2S8Me1c36:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/src/main/java/io/harness/serviceaccount/BUILD.bazel#L23)):*
> ```Starlark
>         "//970-ng-commons/src/main/java/io/harness/constants:module",
>         "//980-commons/src/main/java/io/harness/data/validator:module",
>         "//980-commons/src/main/java/software/wings/jersey:module",
> ```

Why this change?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/events/ServiceAccountEventHandler.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0tAWDWkRY5jWJ0WC:-Nis0tAWDWkRY5jWJ0WD:b-ineqhx) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/events/ServiceAccountEventHandler.java#L57)):*
> ```Java
>                                       .build();
>       Scope scope = ScopeMapper.fromParams(params);
>       harnessServiceAccountService.sync(stripToNull(entityChangeDTO.getIdentifier().getValue()), scope, "");
> ```

What would be the implication of passing empty?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/iterators/ServiceAccountReconciliationIterator.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0xcNATsZf0QHjNFq:-Nis0xcNATsZf0QHjNFr:b-58kcln) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/iterators/ServiceAccountReconciliationIterator.java#L57)):*
> ```Java
> 
>   @Override
>   public void handle(ServiceAccountDBO entity) {
> ```

How would existing service accounts in access control db have their unique id populated?


<!-- Sent from Reviewable.io -->

2023-11-10 07:45 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 39 file(s) to review. 2 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/config.yml` line 359 at r2](https://reviewable.io/reviews/harness/harness-core/55239#-NisBFiD1a4zULztxGqq:-NisBFiE6M8NIGyn_7-8:ba06sgp) ([raw file](https://github.com/harness/harness-core/blob/a502fe643fdc2f16d3c567d6cfbee3c8e40459f1/120-ng-manager/config.yml#L359)):*
> ```YAML
> 
> accessControlClient:
>   enableAccessControl: true
> ```

revert this.
___
*[`120-ng-manager/config.yml` line 375 at r2](https://reviewable.io/reviews/harness/harness-core/55239#-NisBHGa7SuGJjbEEsHq:-NisBHGa7SuGJjbEEsHr:ba06sgp) ([raw file](https://github.com/harness/harness-core/blob/a502fe643fdc2f16d3c567d6cfbee3c8e40459f1/120-ng-manager/config.yml#L375)):*
> ```YAML
>     enableHttpLogging: ${ENABLE_HTTP_LOGGING:-false}
>   accessControlServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
>   mockAccessControlService: false
> ```

revert this.


<!-- Sent from Reviewable.io -->

2023-11-10 07:54 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 39 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nirwu9Y1Wzrj7Blcg8T:-NisCDQf27dRW4Zn22E4:btrestr) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java#L37)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why a new DTO?
</blockquote></details>

This is to get uniqueID in Reconcillation iterator 
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-NirwLx29t3DcXsg3ZVu:-NisCQMT0YYXXhAYjMLW:bbd4cew) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java#L37)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I don't think we need to make this class abstract

Also, there is a general purpose job that was written by Prateek to add uniqueId and parentId in entities. Pls check with him on how can we use that instead of registering a new migration
</blockquote></details>

This is made abstract to get mongo unique ID for different entities like uuid or id etc. This is used to update the entities. Already discussed this with Prateek
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nirw8D88EGnWz5BohTA:-NisCi02C2H-_tiIarcY:b8ojr2q) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java#L107)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

public String getId(T entity) {
    return entity.getUniqueId();
}
</blockquote></details>

This method is to get existing uniqueId for entities using which we will update and save new `uniqueId`. 
___
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/serviceaccount/serviceaccount.proto` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0VevD-qa1GEHS6h9:-NisCwQX4M7fRpgJR-ue:b-gj8ymm) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/serviceaccount/serviceaccount.proto#L13)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Where is this published and consumed?
</blockquote></details>

pushed changed for usage.
___
*[`970-ng-commons/BUILD.bazel` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0FxsB_cZVzNRHdwe:-NisCzWN7LHGWMAbOY_U:b-9nimr7) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/BUILD.bazel#L105)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

To use JSONViews
___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/BUILD.bazel` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0E1F5Re2S8Me1c35:-NisD5-Q8iuPRspxKQDa:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/src/main/java/io/harness/serviceaccount/BUILD.bazel#L23)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

same
___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-NirxB9hByvxWgqMQoKE:-NisD6Zp3eZoGMH3pG3I:b-t8a2h1) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java#L30)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why add SuperBuilder?
</blockquote></details>

To use it while building in mapper
___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-NirxHkbC8IVK0jpFUQY:-NisDB2kCSv5Ul0DQCVZ:blr12fy) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java#L33)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why add this?
</blockquote></details>

We are getting one unknown filed to ignore that due to Super builder.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/events/ServiceAccountEventHandler.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0tAWDWkRY5jWJ0WC:-NisDKVy62-KV_ewLf8l:b7eoajg) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/events/ServiceAccountEventHandler.java#L57)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

What would be the implication of passing empty?
</blockquote></details>

Empty is also handled. But fixed this
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/iterators/ServiceAccountReconciliationIterator.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nis0xcNATsZf0QHjNFq:-NisDQ2o5b5IDx5ZEMdC:bun1x4u) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/iterators/ServiceAccountReconciliationIterator.java#L57)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

How would existing service accounts in access control db have their unique id populated?
</blockquote></details>

Via Reconcillation Iterator. Already added support
___
*[`120-ng-manager/config.yml` line 359 at r2](https://reviewable.io/reviews/harness/harness-core/55239#-NisBFiD1a4zULztxGqq:-NisDVD74iJy_4rZOP3T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a502fe643fdc2f16d3c567d6cfbee3c8e40459f1/120-ng-manager/config.yml#L359)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

revert this.
</blockquote></details>

Done.
___
*[`120-ng-manager/config.yml` line 375 at r2](https://reviewable.io/reviews/harness/harness-core/55239#-NisBHGa7SuGJjbEEsHq:-NisDVWU0BQXNAe8KzYw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a502fe643fdc2f16d3c567d6cfbee3c8e40459f1/120-ng-manager/config.yml#L375)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

revert this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 08:02 UTC, Jimit09Gandhi requested changes
> Reviewed 4 of 34 files at r1, 4 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 36 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisF3KvEMSrPqcC4F-Y:-NisF3KvEMSrPqcC4F-Z:b-rj6nqs) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java#L26)):*
> ```Java
>     return ServiceAccountDTO.builder()
>         .identifier(serviceAccount.getIdentifier())
>         .uniqueId(serviceAccount.getUniqueId())
> ```

Do we need uniqueId to this DTO if we are using the new internal one?


<!-- Sent from Reviewable.io -->

2023-11-10 08:05 UTC, Jimit09Gandhi reviewed
> Reviewed 1 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 36 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nirw8D88EGnWz5BohTA:-NisFqagAmH47xkZ19xK:bllvhmn) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java#L107)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

This method is to get existing uniqueId for entities using which we will update and save new `uniqueId`.
</blockquote></details>

Don't we want to enforce implementation of this method by making it abstract as migration is used to add uniqueId?


<!-- Sent from Reviewable.io -->

2023-11-10 08:07 UTC, Jimit09Gandhi requested changes
> Reviewed 3 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 36 file(s) to review. 2 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisGHK65S7NcBOfQLru:-NisGHK65S7NcBOfQLrv:b-ye9hgw) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java#L43)):*
> ```Java
>   @JsonView(JsonViews.Internal.class)
>   @Schema(hidden = true, description = "UniqueId of Service Account")
>   String uniqueId;
> ```

Do we need this now as we have new DTO?


<!-- Sent from Reviewable.io -->

2023-11-10 08:09 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 36 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisF3KvEMSrPqcC4F-Y:-NisGEhxD9fqy5GO8Yqk:b-pct3x9) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java#L26)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Do we need uniqueId to this DTO if we are using the new internal one?
</blockquote></details>

yes for all other flows like audit and redis
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/55239#-Nirw8D88EGnWz5BohTA:-NisGcQe0VSGMuXMZdhr:b-ob16g9) ([raw file](https://github.com/harness/harness-core/blob/15d91c3602702d14283f08cd75a31d28e4d8f4a4/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/AddUniqueIdToNGEntitiesMigration.java#L107)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Don't we want to enforce implementation of this method by making it abstract as migration is used to add uniqueId?
</blockquote></details>

Yes we can make it for now since project and org does not implement this hence kept it now abstract
___
*[`970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisGHK65S7NcBOfQLru:-NisGV8t3K7NoaYNpD1b:bvoqjd0) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTO.java#L43)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Do we need this now as we have new DTO?
</blockquote></details>

Yes for all other flows like Redis event or audits we use this DTO only


<!-- Sent from Reviewable.io -->

2023-11-10 08:17 UTC, Jimit09Gandhi requested changes
> Reviewed 5 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 32 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisIO5jAeewtsBqymZ-:-NisIO5jAeewtsBqymZ0:bygy3ho) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java#L59)):*
> ```Java
>     ServiceAccountDBO existingServiceAccount = existingServiceAccountOptional.get();
>     serviceAccountDBO.setId(existingServiceAccount.getId());
>     serviceAccountDBO.setCreatedAt(existingServiceAccount.getCreatedAt());
> ```

What about other fields lastModifiedAt, etc?


<!-- Sent from Reviewable.io -->

2023-11-10 08:21 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 32 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisJGwF6EiLgo9kWwp8:-NisJGwF6EiLgo9kWwp9:b-ezi209) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java#L51)):*
> ```Java
>                                           .build();
>       ServiceAccount savedServiceAccount = serviceAccountService.createIfNotPresent(serviceAccount);
>       if (savedServiceAccount.getUniqueId() == null && serviceAccountDTO.getUniqueId() != null) {
> ```

Can we do clean way to update SA so it be extended when any new field is introduced and that needs to be updated as well? 


<!-- Sent from Reviewable.io -->

2023-11-10 08:26 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 32 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisKdRt-Ni4iy45_Gbx:-NisKdRt-Ni4iy45_Gby:b2ptwbv) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java#L38)):*
> ```Java
> 
>   @Override
>   public void sync(String identifier, Scope scope, String uniqueId) {
> ```

Is this field used?


<!-- Sent from Reviewable.io -->

2023-11-10 10:50 UTC, ankit-harness requested changes
> Reviewed 7 of 34 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 23 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java` line 152 at r4](https://reviewable.io/reviews/harness/harness-core/55239#-NisqLQyCxXhEmigsLgH:-NisqLQz7VOlsNxddNEr:bxzusxm) ([raw file](https://github.com/harness/harness-core/blob/2925277586ce11cc73f8041b5d68442156df8ce2/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java#L152)):*
> ```Java
>     newAccount.setUuid(serviceAccount.getUuid());
>     newAccount.setCreatedAt(serviceAccount.getCreatedAt());
>     if (serviceAccount.getUniqueId() != null) {
> ```

Do we have to add this logic during creation of service account too?


<!-- Sent from Reviewable.io -->

2023-11-10 15:01 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 23 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java` line 152 at r4](https://reviewable.io/reviews/harness/harness-core/55239#-NisqLQyCxXhEmigsLgH:-NitjpOS83S0FtcC2gdC:b-wvjypa) ([raw file](https://github.com/harness/harness-core/blob/2925277586ce11cc73f8041b5d68442156df8ce2/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java#L152)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we have to add this logic during creation of service account too?
</blockquote></details>

No while creation its not needed
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisIO5jAeewtsBqymZ-:-NisVi645XUqp-UpP9vC:bpp6stj) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java#L59)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

What about other fields lastModifiedAt, etc?
</blockquote></details>

not needed
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisKdRt-Ni4iy45_Gbx:-NitjtEPDKA0xz4iPqoR:b-rdfq3o) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java#L38)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Is this field used?
</blockquote></details>

As discussed this will be used in followup PRs
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisJGwF6EiLgo9kWwp8:-Nitjx9iAyET8EUrRIGc:b5to4uj) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java#L51)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Can we do clean way to update SA so it be extended when any new field is introduced and that needs to be updated as well?
</blockquote></details>

We can do this by comparing object but again we will need to exclude some fields like createdAt, lastModified etc?


<!-- Sent from Reviewable.io -->

2023-12-20 10:02 UTC, bot2-harness commented
This PR has been automatically closed due to inactivity.

2023-12-26 08:53 UTC, meenakshi-harness commented
trigger uts

2023-12-26 11:26 UTC, meenakshi-harness commented
trigger uts

2023-12-27 08:03 UTC, meenakshi-harness commented
trigger uts

2023-12-27 08:08 UTC, meenakshi-harness commented
trigger pmd

2023-12-28 04:59 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 26 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java` line 310 at r9](https://reviewable.io/reviews/harness/harness-core/55239#-NmimEf81pwPXqr7z8-B:-NmimEf81pwPXqr7z8-C:bedbnr) ([raw file](https://github.com/harness/harness-core/blob/4ce3e19411b3c72b2184545557373bf25259a052/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java#L310)):*
> ```Java
>       @PathParam(IDENTIFIER) @NotNull String identifier) {
>     ServiceAccountDTO serviceAccountDTO =
>         serviceAccountService.getServiceAccountDTO(accountIdentifier, orgIdentifier, projectIdentifier, identifier);
> ```

@meenakshi-harness  We have to use list API to current limitation in Api error handling at our framework level.
Please refer:
https://github.com/harness/harness-core/pull/56895


<!-- Sent from Reviewable.io -->

2023-12-28 05:00 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 26 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java` line 152 at r4](https://reviewable.io/reviews/harness/harness-core/55239#-NisqLQyCxXhEmigsLgH:-NmimoqY-kypd7A6G-T_:bmrkvab) ([raw file](https://github.com/harness/harness-core/blob/2925277586ce11cc73f8041b5d68442156df8ce2/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java#L152)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

No while creation its not needed
</blockquote></details>

Lets use  io.harness.data.structure.EmptyPredicate#isEmpty(java.lang.String)


<!-- Sent from Reviewable.io -->

2023-12-28 17:30 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 26 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisJGwF6EiLgo9kWwp8:-NmlTHq_CDpU5rg_vgfs:b3oaa2e) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java#L51)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

We can do this by comparing object but again we will need to exclude some fields like createdAt, lastModified etc?
</blockquote></details>

Lets do that. This doesn't seem to be maintainable. And logic of comparison can be done using Equals method, way we do everywhere in code.


<!-- Sent from Reviewable.io -->

2023-12-29 07:23 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/migration/AddUniqueIdToServiceAccountMigration.java
> +}
We need to use the common background task for migration 120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java 
cc: @ankit-harness

2023-12-29 09:42 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/migration/AddUniqueIdToServiceAccountMigration.java
> +}
Done

2023-12-29 11:56 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/outbox/ServiceAccountEventHandler.java
> +                           .setUniqueId(resource.getUniqueId())
nit: can resource be null?

2023-12-29 11:59 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java
> +    return (ServiceAccountDTOInternal) ServiceAccountDTOInternal.builder()
nit: why this extra typecast to (ServiceAccountDTOInternal) is required?

2023-12-29 12:17 UTC, pbarapatre10 commented on access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java
> +    serviceAccountDBO.setId(existingServiceAccount.getId());
minor: Do we also need to set the uniqueId explicitly? as in the mapper createdAt is already mapped but we are re-setting it here

2023-12-29 12:39 UTC, pbarapatre10 commented on access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java
> +  public void sync(String identifier, Scope scope, String uniqueId) {
where is this `uniqueId` used

2024-01-02 05:01 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/ServiceAccountDTOMapper.java
> +    return (ServiceAccountDTOInternal) ServiceAccountDTOInternal.builder()
If we don't do this Builder still returns base class only

2024-01-02 05:12 UTC, meenakshi-harness commented on 120-ng-manager/src/main/java/io/harness/ng/core/outbox/ServiceAccountEventHandler.java
> +                           .setUniqueId(resource.getUniqueId())
No but still added a null check.

2024-01-02 05:13 UTC, meenakshi-harness commented on 970-ng-commons/src/main/java/io/harness/serviceaccount/ServiceAccountDTOInternal.java
> +  public String uniqueId;
uniqueId in ServiceAccountDTO is added to keep it in flow for all create/update. Here this field is hidden. Via ServiceAccountDTOInternal it is exposed in internal API.

2024-01-02 05:42 UTC, meenakshi-harness commented on access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java
> +    serviceAccountDBO.setId(existingServiceAccount.getId());
Not sure if we need it. let me check once

2024-01-02 05:44 UTC, meenakshi-harness commented on access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java
> +  public void sync(String identifier, Scope scope, String uniqueId) {
WIll be used in follow ip PRs

2024-01-02 05:44 UTC, meenakshi-harness commented on access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java
> +      harnessServiceAccountService.sync(serviceAccountIdentifier, currentScope, "");
DOne

2024-01-02 05:49 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 31 file(s) to review. 2 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java` line 310 at r9](https://reviewable.io/reviews/harness/harness-core/55239#-NmimEf81pwPXqr7z8-B:-Nn7hZmeESDY-WcMW5qS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ce3e19411b3c72b2184545557373bf25259a052/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/resource/ServiceAccountResource.java#L310)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

@meenakshi-harness  We have to use list API to current limitation in Api error handling at our framework level.
Please refer:
https://github.com/harness/harness-core/pull/56895
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java` line 152 at r4](https://reviewable.io/reviews/harness/harness-core/55239#-NisqLQyCxXhEmigsLgH:-Nn7hzHC8wx48S6TH5La:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2925277586ce11cc73f8041b5d68442156df8ce2/120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl/ServiceAccountServiceImpl.java#L152)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets use  io.harness.data.structure.EmptyPredicate#isEmpty(java.lang.String)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-02 11:57 UTC, pbarapatre10 submitted a review, later dismissed

2024-01-02 16:08 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 31 file(s) to review. 2 change requests. 16. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/55239#-NisJGwF6EiLgo9kWwp8:-Nn9v6W2EuR1p5GIJ-PU:b-wb5he) ([raw file](https://github.com/harness/harness-core/blob/f012e0edfea1cebb82799d722ea5feb042692ab2/access-control/service/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/HarnessServiceAccountServiceImpl.java#L51)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets do that. This doesn't seem to be maintainable. And logic of comparison can be done using Equals method, way we do everywhere in code.
</blockquote></details>

We won't be able to compare objects as they are different. We can compare only via fields which we will need to add on any addition of field which can change. We can discuss this over call.


<!-- Sent from Reviewable.io -->

2024-01-02 16:11 UTC, meenakshi-harness commented on access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/serviceaccounts/persistence/ServiceAccountDaoImpl.java
> +    serviceAccountDBO.setId(existingServiceAccount.getId());
Checked, not needed as uniqueId is part of DBO while createdAt and other fields are not, and need to be set explicitly.

2024-01-02 16:12 UTC, meenakshi-harness commented
trigger uts

2024-01-03 04:51 UTC, meenakshi-harness commented
trigger uts

2024-01-03 06:35 UTC, meenakshi-harness commented
trigger ut2, ut8, ut9

2024-01-03 09:01 UTC, meenakshi-harness commented
trigger ut8

2024-01-03 11:12 UTC, ankit-harness approved these changes
> Reviewed 1 of 34 files at r1, 1 of 1 files at r8, 1 of 3 files at r9, 4 of 4 files at r10, 4 of 5 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 31 file(s) to review. 1 change requests. 9. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2024-01-03 11:34 UTC, meenakshi-harness commented
trigger ut8

2024-01-03 20:33 UTC, gn-harness commented on 970-ng-commons/BUILD.bazel
> +        "//980-commons:module",
@meenakshi-harness Add dependency on specific modules, rather than on the entire top level module

2024-01-04 14:11 UTC, meenakshi-harness commented
trigger ut8, ut9

2024-01-04 17:50 UTC, meenakshi-harness commented
trigger ut9

2024-01-05 11:55 UTC, meenakshi-harness commented
trigger uts

2024-01-05 12:31 UTC, Jimit09Gandhi submitted a review, later dismissed
> Reviewed 14 of 34 files at r1, 1 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r8, 1 of 3 files at r9, 3 of 4 files at r10, 3 of 5 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 4 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2024-01-07 18:48 UTC, meenakshi-harness commented
trigger uts

2024-01-08 04:46 UTC, meenakshi-harness commented
trigger uts

2024-01-08 06:01 UTC, pbarapatre10 commented on 930-ng-core-clients/src/main/java/io/harness/serviceaccount/remote/ServiceAccountClient.java
> +      @Query(NGResourceFilterConstants.IDENTIFIERS) List<String> serviceAccountIdentifiers);
nit: Moving forward we would want to make internal calls use `accountIdentifier` & `scopeUniqueId` (parentUniqueId of entity) , approving for now, thanks

2024-01-08 06:03 UTC, pbarapatre10 approved these changes

2024-01-08 06:55 UTC, Jimit09Gandhi approved these changes
> Reviewed 3 of 3 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55239)* status: 8 file(s) to review. 6. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2024-01-08 17:38 UTC, gn-harness approved these changes

2024-01-08 17:39 UTC, merged