[feat]: [CDS-83872]: Adding APIs for triggers V1 CRUD operations in open-api spec
harness/harness-core pull request #55242
Opened 2023-11-09 18:17 UTC by brijeshdhakar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-10 05:18 UTC, shalini-agr requested changes

2023-11-10 05:18 UTC, shalini-agr commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +            - Custom
shouldn't this be custom for v1?

2023-11-10 05:18 UTC, shalini-agr commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +    TriggerPayloadConditions:
can we just name it TriggerConditions since we are using it for header and payload?

2023-11-10 05:18 UTC, shalini-agr commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        org:
why do we need org, project, and pipeline in the response?

2023-11-10 06:21 UTC, brijeshdhakar commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1327 at r2](https://reviewable.io/reviews/harness/harness-core/55242#gh-1388915599:-NirswDnE5e3oztPxZ_7:bwrxq88) ([raw file](https://github.com/harness/harness-core/blob/d562c1a6b5016c90ca4a21c34c3511e777bb4792/pipeline-service/contracts/openapi/v1/openapi.yaml#L1327)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

why do we need org, project, and pipeline in the response?
</blockquote></details>

Trigger is in the pipeline-scope. So we will need the account, org, project and pipeline identifiers in trigger response so that we can do any ops on the trigger.


<!-- Sent from Reviewable.io -->

2023-11-10 06:22 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55242)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1271 at r2](https://reviewable.io/reviews/harness/harness-core/55242#gh-1388915576:-NirsuRM7MofLSyvjfQi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d562c1a6b5016c90ca4a21c34c3511e777bb4792/pipeline-service/contracts/openapi/v1/openapi.yaml#L1271)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

shouldn't this be custom for v1? 
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1288 at r2](https://reviewable.io/reviews/harness/harness-core/55242#gh-1388915587:-NirsvIf1WuD5KRrZ8dS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d562c1a6b5016c90ca4a21c34c3511e777bb4792/pipeline-service/contracts/openapi/v1/openapi.yaml#L1288)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

can we just name it TriggerConditions since we are using it for header and payload?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 06:22 UTC, brijeshdhakar commented
trigger uts

2023-11-22 04:55 UTC, shalini-agr commented
trigger smartchecks

2023-11-22 05:35 UTC, archit-harness approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55242)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-22 05:59 UTC, shalini-agr commented
trigger uts

2023-11-22 06:03 UTC, shalini-agr approved these changes

2023-11-22 06:36 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        '201':
this should be 200

2023-11-22 06:36 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        encryptedWebhookSecretIdentifier:
please make these into snake_case

2023-11-22 07:02 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55242)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 188 at r4](https://reviewable.io/reviews/harness/harness-core/55242#gh-1401570983:-NjpnUsW3ZzpCToeNBJb:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9ff0590eb195b0c295ac2eba70932d1134ae3cd7/pipeline-service/contracts/openapi/v1/openapi.yaml#L188)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

this should be 200
</blockquote></details>

done
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1298 at r4](https://reviewable.io/reviews/harness/harness-core/55242#gh-1401572023:-NjppYAS4lsQKxhivTW6:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9ff0590eb195b0c295ac2eba70932d1134ae3cd7/pipeline-service/contracts/openapi/v1/openapi.yaml#L1298)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

please make these into snake_case
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-11-22 07:02 UTC, shalini-agr approved these changes

2023-11-22 07:14 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          propertyNames:
this should not be here, redocly isn't getting rendered because of this

2023-11-22 07:14 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          propertyNames:
same here

2023-11-22 07:14 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          propertyNames:
same here

2023-11-22 07:49 UTC, shalini-agr commented
trigger uts

2023-11-22 07:51 UTC, mankrit-singh approved these changes

2023-11-22 07:51 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55242)* status: 2 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1317 at r5](https://reviewable.io/reviews/harness/harness-core/55242#gh-1401601200:-Njq-q8M9HPpVJKCL3_U:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/707693a78e22355a178b61fc7643dd2a44b0f695/pipeline-service/contracts/openapi/v1/openapi.yaml#L1317)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

done
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1367 at r5](https://reviewable.io/reviews/harness/harness-core/55242#gh-1401600740:-Njq-rY04qmByV6MYPNN:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/707693a78e22355a178b61fc7643dd2a44b0f695/pipeline-service/contracts/openapi/v1/openapi.yaml#L1367)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

done
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1537 at r5](https://reviewable.io/reviews/harness/harness-core/55242#gh-1401600538:-Njq-sC26nGICfifQyLS:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/707693a78e22355a178b61fc7643dd2a44b0f695/pipeline-service/contracts/openapi/v1/openapi.yaml#L1537)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

this should not be here, redocly isn't getting rendered because of this
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-11-22 07:56 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55242)* status: 2 file(s) to review. 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-22 08:07 UTC, shalini-agr commented
trigger review

2023-11-22 11:59 UTC, shalini-agr commented
trigger ut1

2023-11-22 12:33 UTC, shalini-agr commented
trigger ut5

2023-11-22 14:38 UTC, merged