feat: [SRM-16127]: Add Analysis orchestrator for the metric less SLO
harness/harness-core pull request #55252
Opened 2023-11-10 04:27 UTC by deepak-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-13 11:11 UTC, deepak-harness commented
trigger uts

2023-11-15 05:14 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ErrorBudgetBurnDownResource.java
> +  @Path("")
Can we add some valid path here ?

2023-11-15 07:33 UTC, Varsha-lalwani requested changes
Also add UTS

2023-11-15 07:33 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/VerificationApplication.java
> +            .targetInterval(ofSeconds(30))
We can keep this every  5 minute, instead of putting the logic in Executor.

2023-11-15 07:33 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/jobs/MetricLessSLIStateMachineCreationHandler.java
> +      SLIRecord latestSLIRecord = sliRecordService.getLatestSLIRecord(sliVerificationTaskId.get());
can you handle the scenario where latestSLIRecord is Null

2023-11-15 07:33 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ErrorBudgetBurnDownResource.java
> +@Api("annotation")
API value is wrong

2023-11-15 07:33 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/ErrorBudgetBurnDownResource.java
> +  @ApiOperation(value = "saves error budget burn down", nickname = "saveErrorBudgetBurnDown")
can we add these apis through spec first approach?

2023-11-15 07:33 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ErrorBudgetBurnDownServiceImpl.java
> +  }
can we add these in transformer class?

2023-11-15 07:33 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/jobs/MetricLessSLIStateMachineCreationHandler.java
> +                                          .endTime(latestSLIRecord.getTimestamp().plus(5, ChronoUnit.MINUTES))
this should be plus 6 as endTime is exclusive

2023-11-21 04:35 UTC, deepak-harness commented
trigger uts

2023-11-23 02:06 UTC, deepak-harness commented
trigger uts

2023-11-23 02:23 UTC, deepak-harness commented
trigger featurenamecheck

2023-11-23 02:45 UTC, deepak-harness commented
trigger uts

2023-11-23 03:47 UTC, merged