changed the sequence for the library steps showing up
harness/harness-core pull request #55292
Opened 2023-11-10 10:43 UTC by ayushitiwari024

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-10 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=55292) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=55292) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=55292) it.</sub>

2023-11-10 10:48 UTC, ankittiwari-harness commented on pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceStepHelper.java
> +      Map<String,Integer> priorityMap = Map.of("Build", 0,"Artifacts", 1, "Security Tests",2, "Security", 3);
how did you come up with this priorityMap

2023-11-10 12:58 UTC, ayushitiwari024 commented on pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceStepHelper.java
> +      Map<String,Integer> priorityMap = Map.of("Build", 0,"Artifacts", 1, "Security Tests",2, "Security", 3);
UI is picking the exact same sequence that is being sent from the backend. This function and the priorityMap will help us to customise the sequence in which we want to send the steps supported as per the module. For eg: for CD, the priorityMap will change to `Map<String,Integer> priorityMap = Map.of("Deployment", 0,"Artifacts", 1, "Security Tests",2, "Security", 3);` , so on so forth.

2023-11-10 13:51 UTC, brijeshdhakar commented on pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceStepHelper.java
> +      Map<String,Integer> priorityMap = Map.of("Build", 0,"Artifacts", 1, "Security Tests",2, "Security", 3);
correct. To add on ayushi's points, the ticket states the required order of step categories that CI steps should be in order: First Build category steps then Artifact category steps and so on.
Currently there is no way to maintain the order of categories so defined this priority_map to sort the list of stepCategories. 
But i think we should take this order of step-categories from respective service only instead of defining priority_map here. So each service can provide their order(when they have multiple step categories) and we can sort according to that list. @sahilhindwani-harness any thought on this?

2023-11-16 19:56 UTC, ayushitiwari024 commented on clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java
>      List<SdkStep> pmsSdkStepTypeWithInfos = new ArrayList<>();
Here, we have tried to preserve the order of the stepInfo in the new List which is pmsSdkStepTypeWithInfos. So, now the order in which the steps will be sent by the CIManager will be maintained int he mapToSdkStep as well.

Also there was an observation in which we saw that on prod, we were also able to see few steps coming `Supply Chain Assurance`. While testing the changes in local, it was observed that only steps belonging to category `Builds`, `Artifacts`, `Security Tests`, `Security` were populated. We would like to understand more on how are we adding these `Supply Chain Assurance` steps in the CIManager.

2023-11-17 06:08 UTC, brijeshdhakar reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55292)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/55292#-NjQsokp5w60H080enSD:-NjQsokp5w60H080enSE:bhn7zsb) ([raw file](https://github.com/harness/harness-core/blob/c9c8765f1234064da015eefc011d8c907504a660/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L195)):*
> ```Java
> 
>     List<SdkStep> pmsSdkStepTypeWithInfos = new ArrayList<>();
>     for(String stepType: stepTypeStringToStepInfo.keySet()){
> ```

Add comment in the code that here we are keeping the order of steps sent by respective services that's why iterating over the stepTypeStringToStepInfo first.
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/55292#-NjQskFp7529Bmm-sP9e:-NjQskFp7529Bmm-sP9f:b-esrxrv) ([raw file](https://github.com/harness/harness-core/blob/c9c8765f1234064da015eefc011d8c907504a660/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L224)):*
> ```Java
> //      }
> //      pmsSdkStepTypeWithInfos.add(sdkStepWrapper.build());
> //    }
> ```

Remove these commented lines.



_Code quote:_
```Java
//    List<SdkStep> pmsSdkStepTypeWithInfos = new ArrayList<>();
//    for (String stepType : stepTypeStringToStepType.keySet()) {
//      SdkStep.Builder sdkStepWrapper = SdkStep.newBuilder();
//      sdkStepWrapper.setStepType(stepTypeStringToStepType.get(stepType));
//      if (stepTypeStringToStepInfo.containsKey(stepType)) {
//        sdkStepWrapper.setIsPartOfStepPallete(true);
//        sdkStepWrapper.setStepInfo(stepTypeStringToStepInfo.get(stepType));
//      }
//      pmsSdkStepTypeWithInfos.add(sdkStepWrapper.build());
//    }
```


<!-- Sent from Reviewable.io -->

2023-11-17 13:14 UTC, ayushitiwari024 commented
trigger smartchecks

2023-11-17 13:17 UTC, ayushitiwari024 commented
trigger uts

2023-11-17 13:59 UTC, ayushitiwari024 commented
trigger ut3, ut8

2023-11-17 14:02 UTC, ayushitiwari024 commented
trigger smartchecks

2023-11-17 14:17 UTC, ayushitiwari024 commented
trigger messagecheck

2023-11-17 14:45 UTC, ayushitiwari024 commented
trigger ut3

2023-11-19 07:34 UTC, ayushitiwari024 commented
trigger ut3

2023-11-19 13:16 UTC, ayushitiwari024 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55292)* status: 2 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/55292#-NjQsokp5w60H080enSD:-NjbiJW74kYJrx3kGFyV:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ea80fd005bcffe97356feac7a8d31b4c1890c5e6/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L195)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Add comment in the code that here we are keeping the order of steps sent by respective services that's why iterating over the stepTypeStringToStepInfo first.
</blockquote></details>

Done
___
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/55292#-NjQskFp7529Bmm-sP9e:-NjbiMQI1vRpFpkznkx_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ea80fd005bcffe97356feac7a8d31b4c1890c5e6/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L224)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Remove these commented lines.
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceStepHelper.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/55292#gh-1389238071:-NjbiOX8DBgFHRmufqpj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/75bbb1302794d864390cadd932cc8550b60a5645/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceStepHelper.java#L106)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

correct. To add on ayushi's points, the ticket states the required order of step categories that CI steps should be in order: First Build category steps then Artifact category steps and so on.
Currently there is no way to maintain the order of categories so defined this priority_map to sort the list of stepCategories. 
But i think we should take this order of step-categories from respective service only instead of defining priority_map here. So each service can provide their order(when they have multiple step categories) and we can sort according to that list. @sahilhindwani-harness any thought on this?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-20 04:52 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 195 at r3](https://reviewable.io/reviews/harness/harness-core/55292#-Njf3ZDlBB3H8UJIOUpv:-Njf3ZDm6dtuuR2IvDh9:begjjyl) ([raw file](https://github.com/harness/harness-core/blob/2df11027e894a4d514d18e57edc3a3f2daa5de51/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L195)):*
> ```Java
>     }
> 
>     // We are keeping the order of steps sent by respective services so, iterating over the stepTypeStringToStepInfo
> ```

Can we add a UT for the same?


<!-- Sent from Reviewable.io -->

2023-11-20 04:52 UTC, sahilhindwani-harness requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55292)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-20 04:54 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 208 at r3](https://reviewable.io/reviews/harness/harness-core/55292#-Njf43AJ9XMrugvDCr6E:-Njf43AJ9XMrugvDCr6F:b-r83rhd) ([raw file](https://github.com/harness/harness-core/blob/2df11027e894a4d514d18e57edc3a3f2daa5de51/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L208)):*
> ```Java
>     }
> 
>     for (String stepType : stepTypeStringToStepType.keySet()) {
> ```

Can we remove this iteration altogether by creating two lists in a single iteration itself?
One for step pallete and one without it.


<!-- Sent from Reviewable.io -->

2023-11-21 04:45 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 208 at r3](https://reviewable.io/reviews/harness/harness-core/55292#-Njf43AJ9XMrugvDCr6E:-NjkBdGk-ghjBQwbGIzu:b-78009f) ([raw file](https://github.com/harness/harness-core/blob/2df11027e894a4d514d18e57edc3a3f2daa5de51/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L208)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we remove this iteration altogether by creating two lists in a single iteration itself?
One for step pallete and one without it.
</blockquote></details>

as discussed, this looks good.


<!-- Sent from Reviewable.io -->

2023-11-21 04:45 UTC, sahilhindwani-harness commented
*[`clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java` line 195 at r3](https://reviewable.io/reviews/harness/harness-core/55292#-Njf3ZDlBB3H8UJIOUpv:-NjkBiqhEhaxzT_fZmR1:bb6tyiv) ([raw file](https://github.com/harness/harness-core/blob/2df11027e894a4d514d18e57edc3a3f2daa5de51/clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/PmsSdkInitHelper.java#L195)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a UT for the same?
</blockquote></details>

DONE


<!-- Sent from Reviewable.io -->

2023-11-21 04:46 UTC, sahilhindwani-harness approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55292)* status: 2 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-21 06:32 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55292)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-21 09:33 UTC, ayushitiwari024 commented
trigger uts

2023-11-21 13:42 UTC, ayushitiwari024 commented
trigger ut7

2023-11-21 13:42 UTC, ayushitiwari024 commented
trigger ut8, ut9

2023-11-21 16:17 UTC, ayushitiwari024 commented
trigger ut9

2023-11-22 05:11 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55292)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-22 05:17 UTC, archit-harness approved these changes
> Reviewed 1 of 2 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55292)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-22 05:27 UTC, ayushitiwari024 commented
trigger review

2023-11-22 05:30 UTC, merged