[feat]: [PLG-2970]: added support for developerLicenses in ModuleLicense
harness/harness-core pull request #55305
Opened 2023-11-10 14:36 UTC by kapil-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-10 17:52 UTC, kapil-harness commented
trigger uts

2023-11-10 19:26 UTC, mohitg0795 commented
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/ModuleLicense.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niugc_p5nRdtL0OKvZ4:-Niugc_p5nRdtL0OKvZ5:b-fr6ez0) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/ModuleLicense.java#L65)):*
> ```Java
>   @LastModifiedDate protected Long lastUpdatedAt;
>   protected Boolean trialExtended;
>   protected Integer developerLicenses;
> ```

do you think we can name it "developerLicensesCount" for better clarity?


<!-- Sent from Reviewable.io -->

2023-11-10 19:26 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiugnU90USIm1QJ0yrM:-NiugnU90USIm1QJ0yrN:btp5yrf) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L26)):*
> ```Java
> @Singleton
> public class CDLicenseObjectMapper implements LicenseObjectMapper<CDModuleLicense, CDModuleLicenseDTO> {
>   @Inject private FeatureFlagService featureFlagService;
> ```

add line spacing


<!-- Sent from Reviewable.io -->

2023-11-10 19:26 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niugs4L0CDm_KLGAPKU:-Niugs4L0CDm_KLGAPKV:buviopo) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L48)):*
> ```Java
> 
>   @Override
>   public void validateModuleLicenseDTO(CDModuleLicenseDTO cdModuleLicenseDTO) {
> ```

it should be private?


<!-- Sent from Reviewable.io -->

2023-11-10 19:28 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuh8AE0OEhFzGfL4C3:-Niuh8AE0OEhFzGfL4C4:buje2ni) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L58)):*
> ```Java
>         // TODO: fetch mapping ratio from DeveloperMapping collection, once that work is complete
>         Integer mappingRatio = 1;
>         if (cdModuleLicenseDTO.getCdLicenseType().equals(CDLicenseType.SERVICES)) {
> ```

would be better to use reverse comparison here


<!-- Sent from Reviewable.io -->

2023-11-10 19:28 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhAJf5jlDZCjsRHj6:-NiuhAJf5jlDZCjsRHj7:b6ppp0q) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L60)):*
> ```Java
>         if (cdModuleLicenseDTO.getCdLicenseType().equals(CDLicenseType.SERVICES)) {
>           cdModuleLicenseDTO.setWorkloads(mappingRatio * cdModuleLicenseDTO.getDeveloperLicenses());
>         } else if (cdModuleLicenseDTO.getCdLicenseType().equals(CDLicenseType.SERVICE_INSTANCES)) {
> ```

same here as above


<!-- Sent from Reviewable.io -->

2023-11-10 19:28 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhLip8tBB2VkZlTNP:-NiuhLip8tBB2VkZlTNQ:bh0mc69) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java#L35)):*
> ```Java
> 
>   @Override
>   public void validateModuleLicenseDTO(CEModuleLicenseDTO ceModuleLicenseDTO) {
> ```

private?


<!-- Sent from Reviewable.io -->

2023-11-10 19:29 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhObUDiDSDpR6o_v9:-NiuhObUDiDSDpR6o_vA:b9csdzc) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java#L39)):*
> ```Java
>     if (ceModuleLicenseDTO.getDeveloperLicenses() != null) {
>       throw new InvalidRequestException(
>           "Cloud Cost Management License will never have primary entitlements i.e. developerLicenses");
> ```

I think the error message should be : "cannot have primar..."


<!-- Sent from Reviewable.io -->

2023-11-10 19:29 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhTqHA6554XXGJron:-NiuhTqI9bQ59N-RI1qG:b-l721d0) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java#L25)):*
> ```Java
> @Singleton
> public class CETLicenseObjectMapper implements LicenseObjectMapper<CETModuleLicense, CETModuleLicenseDTO> {
>   @Inject private FeatureFlagService featureFlagService;
> ```

line spacing


<!-- Sent from Reviewable.io -->

2023-11-10 19:29 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhVu20QfNtfQZ1NDx:-NiuhVu20QfNtfQZ1NDy:bh0mc69) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java#L39)):*
> ```Java
> 
>   @Override
>   public void validateModuleLicenseDTO(CETModuleLicenseDTO cetModuleLicenseDTO) {
> ```

private?


<!-- Sent from Reviewable.io -->

2023-11-10 19:29 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhZ7A7GrjF1h3UNPY:-NiuhZ7A7GrjF1h3UNPZ:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java#L45)):*
> ```Java
> 
>   @Override
>   public void validateModuleLicenseDTO(CFModuleLicenseDTO cfModuleLicenseDTO) {
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-11-10 19:29 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuh_6m4yF1bcADtuFG:-Niuh_6m4yF1bcADtuFH:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java#L25)):*
> ```Java
> @Singleton
> public class CFLicenseObjectMapper implements LicenseObjectMapper<CFModuleLicense, CFModuleLicenseDTO> {
>   @Inject private FeatureFlagService featureFlagService;
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-11-10 19:30 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/ChaosLicenseObjectMapper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuhcn6C1Sd2ak3xLSX:-Niuhcn6C1Sd2ak3xLSY:b-l721d0) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/ChaosLicenseObjectMapper.java#L25)):*
> ```Java
> @Singleton
> public class ChaosLicenseObjectMapper implements LicenseObjectMapper<ChaosModuleLicense, ChaosModuleLicenseDTO> {
>   @Inject private FeatureFlagService featureFlagService;
> ```

line spacing


<!-- Sent from Reviewable.io -->

2023-11-10 19:30 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/ChaosLicenseObjectMapper.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuhe_V41RXvZ6k8eVA:-Niuhe_V41RXvZ6k8eVB:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/ChaosLicenseObjectMapper.java#L45)):*
> ```Java
> 
>   @Override
>   public void validateModuleLicenseDTO(ChaosModuleLicenseDTO chaosModuleLicenseDTO) {
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-11-10 19:31 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuhia75U4N6FiaBBl6:-Niuhia75U4N6FiaBBl7:b-x3kg3d) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java#L46)):*
> ```Java
>   @Override
>   public void validateModuleLicenseDTO(CFModuleLicenseDTO cfModuleLicenseDTO) {
>     if (featureFlagService.isEnabled(FeatureName.PLG_DEVELOPER_LICENSING, cfModuleLicenseDTO.getAccountIdentifier())) {
> ```

I see we are using the exact flag check at multiple places. It would be better to put it at central util and just use that util here. This also eliminates need to instantiate feature flag service in all these classes and also the code becomes central.


<!-- Sent from Reviewable.io -->

2023-11-11 03:43 UTC, Xin-Harness requested changes

2023-11-11 03:43 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java
> +    if (featureFlagService.isEnabled(FeatureName.PLG_DEVELOPER_LICENSING, cetModuleLicenseDTO.getAccountIdentifier())) {
It is a good practice to put guard block first. Not only for readability, it will also be easier to remove the ff in the future. Same for the rest If else statement in other license object mapper.

```
  if(!featureFlagService.isEnabled(FeatureName.PLG_DEVELOPER_LICENSING){
	  if(cetModuleLicenseDTO.getDeveloperLicense){
		  throw invalid exception.
	  }
	  return;
  }

  if (cetModuleLicenseDTO.getDeveloperLicenses() != null) {
    if (cetModuleLicenseDTO.getNumberOfAgents() != null) {
      throw new InvalidRequestException("Both developerLicenses and numberOfAgents cannot be part of the input!");
    }

    // TODO: fetch mapping ratio from DeveloperMapping collection, once that work is complete
    Integer mappingRatio = 1;
    cetModuleLicenseDTO.setNumberOfAgents(mappingRatio * cetModuleLicenseDTO.getDeveloperLicenses());
  }
```

2023-11-13 14:17 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 2 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiugnU90USIm1QJ0yrM:-Nj81gF42PhiKdQ4sO_7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

add line spacing
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niugs4L0CDm_KLGAPKU:-Nj7sIf7AD0TCMsnim0c:b-z27ked) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it should be private?
</blockquote></details>

It can only be public as its getting overridden from interface
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuh8AE0OEhFzGfL4C3:-Nj7sfot5YrNUqi6snKm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

would be better to use reverse comparison here
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhAJf5jlDZCjsRHj6:-Nj7sgZ74Xn9q3laJHpu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CDLicenseObjectMapper.java#L60)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here as above
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhLip8tBB2VkZlTNP:-Nj7sidD5FL3htO-JPXh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

private?
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhObUDiDSDpR6o_v9:-Nj81iAZ-tfTDXRMjI4A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CELicenseObjectMapper.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think the error message should be : "cannot have primar..."
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhTqHA6554XXGJron:-Nj81irc7opWvoGyrTSb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhVu20QfNtfQZ1NDx:-Nj7tHhv27wQPxiI7sjz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

private?
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/55305#gh-1390112851:-Nj7tZh3EJ3FojcPNYek:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CETLicenseObjectMapper.java#L40)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

 It is a good practice to put guard block first. Not only for readability, it will also be easier to remove the ff in the future. Same for the rest If else statement in other license object mapper.

```
  if(!featureFlagService.isEnabled(FeatureName.PLG_DEVELOPER_LICENSING){
	  if(cetModuleLicenseDTO.getDeveloperLicense){
		  throw invalid exception.
	  }
	  return;
  }

  if (cetModuleLicenseDTO.getDeveloperLicenses() != null) {
    if (cetModuleLicenseDTO.getNumberOfAgents() != null) {
      throw new InvalidRequestException("Both developerLicenses and numberOfAgents cannot be part of the input!");
    }

    // TODO: fetch mapping ratio from DeveloperMapping collection, once that work is complete
    Integer mappingRatio = 1;
    cetModuleLicenseDTO.setNumberOfAgents(mappingRatio * cetModuleLicenseDTO.getDeveloperLicenses());
  }
```
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuh_6m4yF1bcADtuFG:-Nj81k8vBWwQvwNOEOZb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-NiuhZ7A7GrjF1h3UNPY:-Nj81bR6C14tkYehkEMJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java#L45)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/55305#-Niuhia75U4N6FiaBBl6:-Nj81cVB8QPhXwVOfS-o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6592c527321202dd47b9157f25b985854f7f06e6/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CFLicenseObjectMapper.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i> [...]

2023-11-13 14:18 UTC, kapil-harness commented
trigger uts

2023-11-13 16:38 UTC, Xin-Harness approved these changes

2023-11-13 17:07 UTC, neelam-harness approved these changes
LGTM overall. just one minor comment around naming the feature flag, pls take a look.

2023-11-13 17:07 UTC, neelam-harness commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> +  PLG_DEVELOPER_LICENSING("Enable new developer licensing changes", GTM);
let's rename this to `GTM_DEVELOPER_LICENSING`

2023-11-13 19:00 UTC, mohitg0795 approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 19 file(s) to review. 13. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-13 23:11 UTC, kapil-harness commented
trigger uts

2023-11-13 23:22 UTC, kapil-harness commented
trigger uts

2023-11-13 23:29 UTC, kapil-harness commented
trigger uts

2023-11-13 23:30 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55305)* status: 24 file(s) to review. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 952 at r2](https://reviewable.io/reviews/harness/harness-core/55305#gh-1391411887:-NjA0I-nDtMo-AgDXInd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c674038854b06213c8e50fbb13cfaf8c6d7f3b3/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L952)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

let's rename this to `GTM_DEVELOPER_LICENSING`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-14 01:02 UTC, neelam-harness approved these changes

2023-11-14 05:23 UTC, mohitg0795 submitted a review, later dismissed

2023-11-14 07:59 UTC, kapil-harness commented
trigger checkstylecodeformat

2023-11-14 08:00 UTC, kapil-harness commented
trigger messagecheck

2023-11-14 08:00 UTC, kapil-harness commented
trigger codebasehash

2023-11-14 08:00 UTC, kapil-harness commented
trigger pmd

2023-11-14 08:03 UTC, kapil-harness commented
trigger review

2023-11-14 08:09 UTC, kapil-harness commented
trigger commonchecks

2023-11-14 08:17 UTC, kapil-harness commented
/rebase

2023-11-14 08:19 UTC, kapil-harness commented
trigger codebasehash,pmd,messagecheck,checkstylecodeformat

2023-11-14 08:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=55305) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=55305) before we can accept your contribution.<br/>**24** out of **28** committers have signed the CLA.<br/><br/>:white_check_mark: adivishy1<br/>:white_check_mark: kapil-harness<br/>:white_check_mark: abhinavmittal-harness<br/>:white_check_mark: Jimit09Gandhi<br/>:white_check_mark: abhijeet-harness<br/>:white_check_mark: utkarshchoubey-harness<br/>:white_check_mark: shashwat-harness<br/>:white_check_mark: reetika04<br/>:white_check_mark: devkimittal<br/>:white_check_mark: vigneswara-propelo<br/>:white_check_mark: AbhijithHarness<br/>:white_check_mark: smjt-h<br/>:white_check_mark: sandeshsalunkhegh<br/>:white_check_mark: inderschera<br/>:white_check_mark: ShobhitSingh11<br/>:white_check_mark: sahilhindwani-harness<br/>:white_check_mark: shash-harness<br/>:white_check_mark: sdsingh07<br/>:white_check_mark: abhinavsingh-ccm<br/>:white_check_mark: Xin-Harness<br/>:white_check_mark: iamanmolm<br/>:white_check_mark: jamie-harness<br/>:white_check_mark: sahibaHarness<br/>:white_check_mark: jennyjames21<br/>:x: Rakshitharness<br/>:x: Aninditaa-ch<br/>:x: bot-harness<br/>:x: devesh-harness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=55305) it.</sub>

2023-11-14 11:58 UTC, closed without merging