[feat]: [CDS-81940]: adding deployment stage plan creator for v1 schema and r…
harness/harness-core pull request #55362
Opened 2023-11-14 16:52 UTC by markoharness

## Describe your changes
Added DeploymentStagePlanCreator for V1 schema along with related classes.

DeploymentStageFilterJsonCreator and EmptyVariableCreator were added just temporary for DeploymentStagePlanCreator. They will updated in subsequent PRs.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/55362)

2023-11-16 21:13 UTC, markoharness commented
trigger uts

2023-11-16 21:16 UTC, markoharness commented
trigger checkstylecodeformat,messagecheck,commonchecks,pmd,gitleaks,codebasehash

2023-11-16 21:22 UTC, markoharness commented
trigger messagecheck

2023-11-17 06:07 UTC, archit-harness requested changes
> Reviewed 9 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 702 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQDqiN7DT7twyo_9xr:-NjQDqiN7DT7twyo_9xs:bm3h135) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L702)):*
> ```Java
>   }
> 
>   private ThreadPoolExecutor deploymentStagePlanCreationInfoV1ThreadPoolConfiguration() {
> ```

why we are creating this new? cant we use the same as in v0?
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 1117 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQDvBL0rwElFh-rVy_:-NjQDvBL0rwElFh-rVya:b-s8ixmt) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L1117)):*
> ```Java
>     bind(ExecutorService.class)
>         .annotatedWith(Names.named("deployment-stage-plan-creation-info-v1-executor"))
>         .toInstance(new ManagedExecutorService(deploymentStagePlanCreationInfoV1ThreadPoolConfiguration()));
> ```

cant we use same? 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQDyVL5Z-HCfY39aar:-NjQDyVL5Z-HCfY39aas:b-zbtuya) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java#L22)):*
> ```Java
> import org.springframework.data.annotation.TypeAlias;
> 
> @Data
> ```

why Data annotation is required? we should avoid having data annotations for these?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQE4cKDgrtwiHyi88s:-NjQE4cKDgrtwiHyi88t:b-o6m8vc) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java#L25)):*
> ```Java
> @Builder
> @JsonTypeName(YAMLFieldNameConstants.DEPLOYMENT_STAGE_V1)
> @TypeAlias("DeploymentStageNodeV1")
> ```

why type alias?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQE2nbDBdPLECDuHLH:-NjQE2nbDBdPLECDuHLI:blr3hxa) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java#L26)):*
> ```Java
> @JsonTypeName(YAMLFieldNameConstants.DEPLOYMENT_STAGE_V1)
> @TypeAlias("DeploymentStageNodeV1")
> @RecasterAlias("io.harness.cdng.creator.plan.stage.v1.DeploymentStageNodeV1")
> ```

why recaster alias is required?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 477 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQsVl80fe-WoRxvo3s:-NjQsVl95AYTw0Cw7zxX:b58a7gf) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L477)):*
> ```Java
>   }
> 
>   public static List<AdviserObtainment> addResourceConstraintDependencyForV1Schema(
> ```

we should try creating separate class for infrav1 separately
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQszjIDdYixjVzJJcG:-NjQszjIDdYixjVzJJcH:bmu99jz) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L485)):*
> ```Java
>     for (YamlField stageYamlField : stageYamlFields) {
>       if (stageIdentifier.equals(stageYamlField.getNode().getField("id").getNode().asText())) {
>         return stageYamlField;
> ```

@brijeshdhakar why do we need this?


<!-- Sent from Reviewable.io -->

2023-11-17 06:38 UTC, brijeshdhakar commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQszjIDdYixjVzJJcG:-NjQxghN6bd7Cw2Vt9Mb:bwa3pp) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L485)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar why do we need this?
</blockquote></details>

@archit-harness we would need this to find the stageNode by stageId when using useFromStage. This can be simplified more. But I am not able to think how can we avoid the yamlField traversal here.


<!-- Sent from Reviewable.io -->

2023-11-17 06:38 UTC, brijeshdhakar commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 498 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQzjjP3oB7EdieU94P:-NjQzjjP3oB7EdieU94Q:b-2gn6wq) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L498)):*
> ```Java
>       String stageFieldType = yamlNode.getStringValue("type");
>       if (YAMLFieldNameConstants.PARALLEL.equalsIgnoreCase(stageFieldType)) {
>         stageFields.addAll(getStageYamlFields(yamlNode));
> ```

In V1 parallel is also a valid stageType and has structure exactly like stage. So it will have spec and then stages field that will be list. So `getStageYamlFields` directly on yamlNode will always return empty list.



_Code quote:_
```Java
getStageYamlFields(yamlNode)
```


<!-- Sent from Reviewable.io -->

2023-11-17 06:40 UTC, brijeshdhakar commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 497 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjR-Af_6Zgf_wBUlNab:-NjR-Afa8TGMVE0KdRgG:b-al049x) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L497)):*
> ```Java
>     yamlNodes.forEach(yamlNode -> {
>       String stageFieldType = yamlNode.getStringValue("type");
>       if (YAMLFieldNameConstants.PARALLEL.equalsIgnoreCase(stageFieldType)) {
> ```

@archit-harness @markoharness since parallel is a valid stage and it will have some stages inside its spec. I think we should get clarity on how do we want to reference the stages that are inside the parallel stage. By using only stageId or parallelStageId.stageId?


<!-- Sent from Reviewable.io -->

2023-11-17 06:46 UTC, brijeshdhakar commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 477 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQsVl80fe-WoRxvo3s:-NjR14F54-oETohHLL4c:b32v57) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L477)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should try creating separate class for infrav1 separately
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-11-17 07:36 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/NGServiceEntityHelper.java
> +    return null;
what does null ServiceDefinitionType mean ? Are we going to handle it/ignore this in the caller method ?

2023-11-17 07:36 UTC, yogesh-chauhan commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java
> +    for (FailureConfigV1 failureConfig : stageFailureStrategies.getValue()) {
do we need to handle expression/runtime input here ?

2023-11-17 07:36 UTC, yogesh-chauhan commented on clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java
> +          && failureConfig.getErrors().get(0).getYamlName().contentEquals(NGFailureTypeConstantsV1.ALL_ERRORS)) {
nit: probably better to do

```java
NGFailureTypeConstantsV1.ALL_ERRORS.contentEquals(failureConfig.getErrors().get(0).getYamlName())
```

since constant would be on the left side of the comparator

2023-11-17 11:06 UTC, markoharness commented
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 702 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQDqiN7DT7twyo_9xr:-NjRxQRO3exYCjua81d8:bw9syue) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L702)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are creating this new? cant we use the same as in v0?
</blockquote></details>

Yes we can. I will make the change.


<!-- Sent from Reviewable.io -->

2023-11-17 11:07 UTC, markoharness commented
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 1117 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQDvBL0rwElFh-rVy_:-NjRxmFeCmf9QtNHkRN2:bw9syue) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L1117)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant we use same?
</blockquote></details>

Yes we can. I will make the change.


<!-- Sent from Reviewable.io -->

2023-11-17 11:29 UTC, markoharness commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/NGServiceEntityHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/55362#gh-1396798049:-NjS1VKmAnBCJ9OnJlG8:byo4y11) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/NGServiceEntityHelper.java#L100)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what does null ServiceDefinitionType mean ? Are we going to handle it/ignore this in the caller method ?
</blockquote></details>

You are right this will end up in NPE at some point. What do you suggest we do here? Maybe introduce ServiceDefinitionType.NOOP to avoid NPEs?


<!-- Sent from Reviewable.io -->

2023-11-17 11:31 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 477 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQsVl80fe-WoRxvo3s:-NjS24P6BU98AU9QjCim:b9ousnf) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L477)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Can we do that in another PR specifically when dealing with Infra? This PR is huge enough.


<!-- Sent from Reviewable.io -->

2023-11-17 11:36 UTC, markoharness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java` line 225 at r2](https://reviewable.io/reviews/harness/harness-core/55362#gh-1396807728:-NjS3BaZ8aZ5lsBzEJ4j:bhdk4zr) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java#L225)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to handle expression/runtime input here ?
</blockquote></details>

method was copied from io.harness.plancreator.steps.GenericStepPMSPlanCreator#containsOnlyAllErrorsInSomeConfig
and adjusted for v1 dtos


<!-- Sent from Reviewable.io -->

2023-11-17 13:13 UTC, markoharness commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQDyVL5Z-HCfY39aar:-NjSPK465rEpdqgzu1pU:bkdwa8g) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why Data annotation is required? we should avoid having data annotations for these?
</blockquote></details>

I can remove Data annotation, but we need Value annotation at least.


<!-- Sent from Reviewable.io -->

2023-11-17 13:13 UTC, markoharness commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQE2nbDBdPLECDuHLH:-NjSPUtrBNu_YvEahh3l:b-fp3f7v) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStageNodeV1.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why recaster alias is required?
</blockquote></details>

I will remove it


<!-- Sent from Reviewable.io -->

2023-11-17 13:14 UTC, markoharness commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/NGServiceEntityHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/55362#gh-1396798049:-NjSPXct5Tf4syXGRSMs:bcxyeqj) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/NGServiceEntityHelper.java#L100)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

You are right this will end up in NPE at some point. What do you suggest we do here? Maybe introduce ServiceDefinitionType.NOOP to avoid NPEs?
</blockquote></details>

I will keep the method as is. The only place i see NPE happening is in io.harness.cdng.creator.plan.service.ServiceAllInOnePlanCreatorUtils#addChildrenNodes
which i can refactor to avoid it.


<!-- Sent from Reviewable.io -->

2023-11-17 13:15 UTC, markoharness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 498 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQzjjP3oB7EdieU94P:-NjSQ-LRCrVBRHKYbQ-E:b34c92c) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L498)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

In V1 parallel is also a valid stageType and has structure exactly like stage. So it will have spec and then stages field that will be list. So `getStageYamlFields` directly on yamlNode will always return empty list.
</blockquote></details>

I will add the missing logic


<!-- Sent from Reviewable.io -->

2023-11-17 13:19 UTC, markoharness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java` line 227 at r2](https://reviewable.io/reviews/harness/harness-core/55362#gh-1396807729:-NjSQvNdBlq6WqEwTsgy:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/v1/FailureStrategiesUtilsV1.java#L227)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: probably better to do

```java
NGFailureTypeConstantsV1.ALL_ERRORS.contentEquals(failureConfig.getErrors().get(0).getYamlName())
```

since constant would be on the left side of the comparator
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-17 13:21 UTC, markoharness commented
trigger uts

2023-11-17 13:22 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 11 of 17 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 13 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-11-17 15:44 UTC, markoharness commented
trigger uts

2023-11-17 16:43 UTC, markoharness commented
trigger commonchecks

2023-11-17 18:15 UTC, yogesh-chauhan submitted a review, later dismissed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 15 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-11-20 11:57 UTC, archit-harness requested changes
> Reviewed 3 of 17 files at r1, 6 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 497 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjR-Af_6Zgf_wBUlNab:-Njg_RNCAVAasWjxn3dV:ba20yc7) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L497)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@archit-harness @markoharness since parallel is a valid stage and it will have some stages inside its spec. I think we should get clarity on how do we want to reference the stages that are inside the parallel stage. By using only stageId or parallelStageId.stageId?
</blockquote></details>

for starter direct stageId are fine
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 498 at r4](https://reviewable.io/reviews/harness/harness-core/55362#-Njg_kMm3Bh66kaXqstj:-Njg_kMm3Bh66kaXqstk:b-wiogdm) ([raw file](https://github.com/harness/harness-core/blob/c82025497cafca41230734716853d375b32e655a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L498)):*
> ```Java
>       String stageFieldType = yamlNode.getStringValue("type");
>       if (YAMLFieldNameConstants.PARALLEL.equalsIgnoreCase(stageFieldType)) {
>         stageFields.addAll(getStageYamlFields(yamlNode.getField("spec").getNode().getField("stages").getNode()));
> ```

can we use constants for spec, stages etc


<!-- Sent from Reviewable.io -->

2023-11-20 13:02 UTC, markoharness commented
trigger uts

2023-11-20 13:43 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 10 files at r3, 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/55362#-NjQszjIDdYixjVzJJcG:-NjgyAJiDfOM03OP47gZ:bz8e3v2) ([raw file](https://github.com/harness/harness-core/blob/f98e08479e9313ae1fb2173ffff786288c49ee58/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L485)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@archit-harness we would need this to find the stageNode by stageId when using useFromStage. This can be simplified more. But I am not able to think how can we avoid the yamlField traversal here.
</blockquote></details>

cc: @hextechpal this dependency will exist PP until cd is purely simplified that yaml traversal will exist


<!-- Sent from Reviewable.io -->

2023-11-20 15:36 UTC, brijeshdhakar commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNode.java` line 372 at r5](https://reviewable.io/reviews/harness/harness-core/55362#-NjhMwAX09yEU0fDKdif:-NjhMwAX09yEU0fDKdig:b-d785ui) ([raw file](https://github.com/harness/harness-core/blob/ff9d89477ecda0bc6a604c177dbdc85f3f854239/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNode.java#L372)):*
> ```Java
>     String uuidValue = getStringValue(UUID_FIELD_NAME);
>     if (uuidValue == null) {
>       uuidValue = getStringValue(UUID_FIELD_NAME_V1);
> ```

Why are we having this different uuid name?


<!-- Sent from Reviewable.io -->

2023-11-20 15:38 UTC, brijeshdhakar reviewed
> Reviewed 10 of 17 files at r1, 6 of 10 files at r3, 2 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-11-27 09:46 UTC, markoharness commented
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNode.java` line 372 at r5](https://reviewable.io/reviews/harness/harness-core/55362#-NjhMwAX09yEU0fDKdif:-NkFA3Ah4lJuu_3CaDAu:b-9tf86) ([raw file](https://github.com/harness/harness-core/blob/ff9d89477ecda0bc6a604c177dbdc85f3f854239/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNode.java#L372)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why are we having this different uuid name?
</blockquote></details>

Removed the logic


<!-- Sent from Reviewable.io -->

2023-11-27 09:49 UTC, markoharness commented
trigger uts

2023-11-27 10:11 UTC, yogesh-chauhan approved these changes
> Reviewed 3 of 4 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 5 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-11-27 11:07 UTC, brijeshdhakar approved these changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55362)* status: 1. unresolved discussions. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-11-27 11:35 UTC, lovish1999 approved these changes

2023-11-27 11:35 UTC, merged