feat:[IE-495]: V2 api for exposing versions for harness-core services (Platform-service)
harness/harness-core pull request #55372
Opened 2023-11-14 23:15 UTC by Vbhatia20

## Describe your changes
V2 api for exposing versions for harness-core services (Platform-service)
V2 Dropwizard app for supporting version
V2 api for platform-service to expose version

**Build**:
https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/DevSpaces/pipelines/Build_Services/executions/sx-sd2fSQyC-xPCW_z2e8Q/pipeline?connectorRef=harnessplinfra&repoName=harness-pl-infra&branch=master&storeType=REMOTE&stage=7ludiG2-Q8S4alRBXPMDxQ&stageExecId=sIN9XL_qSva1tF8XAsCcDQ

**Request**:
https://rageshm.pr2.harness.io/notifications/api/v2/version
**Response**:
{"buildVersion":"1.3.0-ie-495-281ec4","buildTime":1700000741000,"branchName":"ie-495","commitSha":"281ec4"}

<img width="1026" alt="Screenshot 2023-11-14 at 6 12 38 PM" src="https://github.com/harness/harness-core/assets/95602529/80d15412-8303-46d9-86f7-4a5d702427a0">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-15 05:26 UTC, kapilgarg1996 commented on 980-commons/src/main/java/io/harness/version/BUILD.bazel
> +        "@maven//:org_json_json",
is this required anymore ?

2023-11-15 05:28 UTC, kapilgarg1996 commented on 980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java
> +      throw new RuntimeException("Failed to retrieve version info: " + e.getMessage(), e);
should we catch specific exceptions here ? All the stuff which can go wrong
- file not found
- yaml parse error
and instead of throwing runtime exception, we can throw a Checked exception `VersionInfoException`

Suggesting this because its a common utility and will be used by a lot of services. For future integrations, service owners should know what kind of error can come from this.

2023-11-15 05:32 UTC, kapilgarg1996 commented on platform-service/build/container/Dockerfile-platform-service-multistage
> +    && echo "BUILD_TIME: $BUILD_TIME" >> version.yaml \
shouldn't this be auto-populated ? Whenever the dockerfile is run, that should be the build time. Please confirm with @ankit-harness once.

2023-11-15 10:33 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55372)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHWfl8DSAwsfnwtW2v:-NjHWfl8DSAwsfnwtW2w:b-5mlr7g) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L27)):*
> ```Java
>   private String versionFilePath = "/opt/harness/version.yaml";
> 
>   public VersionInfoV2 getVersionInfo() {
> ```

Can we cache the version info so that we don't recompute it every-time a request comes.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHWms82QaanfJBllJX:-NjHWms82QaanfJBllJY:b-txx9bl) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L29)):*
> ```Java
>   public VersionInfoV2 getVersionInfo() {
>     try {
>       InputStream inputStream = new FileInputStream(versionFilePath);
> ```

We should handle IOException here.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHX7WH-M5v-ZrqY8yJ:-NjHX7WH-M5v-ZrqY8yK:b-cpi1mq) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L38)):*
> ```Java
>       VersionInfoV2 versionInfo = VersionInfoV2.builder()
>               .buildVersion((String) data.get("BUILD_VERSION"))
>               .buildTime((Date) data.get("BUILD_TIME")) // Cast to Date
> ```

Is this working (Date) data.get("BUILD_TIME")? Have we tested it?
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoV2.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHX-ji9zP4NoBtHjJJ:-NjHX-ji9zP4NoBtHjJK:b-c6lrpo) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoV2.java#L22)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.PL)
> public class VersionInfoV2 {
> ```

Can we have tag info as well?
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoV2.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHXHzJA70m8lm-C5be:-NjHXHzJA70m8lm-C5bf:b-l0g3a9) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoV2.java#L24)):*
> ```Java
> public class VersionInfoV2 {
>   private String buildVersion;
>   private Date buildTime;
> ```

Use of Instant class is recommended now over Date class


<!-- Sent from Reviewable.io -->

2023-11-15 18:02 UTC, Vbhatia20 commented
trigger checkstylecodeformat

2023-11-15 18:02 UTC, Vbhatia20 commented
trigger messagecheck

2023-11-15 18:10 UTC, Vbhatia20 commented
trigger uts

2023-11-16 00:54 UTC, Vbhatia20 commented
trigger checkstylecodeformat

2023-11-17 05:01 UTC, ankit-harness requested changes
> Reviewed 4 of 8 files at r1, 2 of 4 files at r2, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55372)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/version/VersionInfoException.java` line 12 at r5](https://reviewable.io/reviews/harness/harness-core/55372#-NjQdmnD1FIGDKshrJgE:-NjQdmnD1FIGDKshrJgF:bcjw3rp) ([raw file](https://github.com/harness/harness-core/blob/07ed306dc91ac58e8ad480328abcece090889e74/980-commons/src/main/java/io/harness/version/VersionInfoException.java#L12)):*
> ```Java
> import java.io.IOException;
> 
> public class VersionInfoException extends Exception {
> ```

There is already a VersionInfoException - io.harness.version.VersionInfoManager
___
*[`platform-service/build/container/Dockerfile-platform-service-multistage` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/55372#-NjQdOs11wV1YQ-Chq1W:-NjQdOs11wV1YQ-Chq1X:bqu9kxf) ([raw file](https://github.com/harness/harness-core/blob/07ed306dc91ac58e8ad480328abcece090889e74/platform-service/build/container/Dockerfile-platform-service-multistage#L21)):*
> ```
> WORKDIR /app
> 
> RUN echo "BUILD_VERSION: $BUILD_VERSION" > version.yaml \
> ```

Shouldn't this be

RUN echo "BUILD_VERSION: $BUILD_VERSION" >> version.yaml


<!-- Sent from Reviewable.io -->

2023-11-17 05:06 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55372)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/55372#-NjQetbwBkRYRR6b79SN:-NjQetbwBkRYRR6b79SO:b-v38fm9) ([raw file](https://github.com/harness/harness-core/blob/07ed306dc91ac58e8ad480328abcece090889e74/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L28)):*
> ```Java
> @Slf4j
> @OwnedBy(PL)
> public class VersionInfoManagerV2 {
> ```

Slightly improved version



_Code snippet:_
```Java
package io.harness.version;

import io.harness.annotations.dev.OwnedBy;
import io.harness.annotations.dev.HarnessTeam;
import lombok.extern.slf4j.Slf4j;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.error.YAMLException;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.Map;
import java.util.Optional;

@Slf4j
@OwnedBy(HarnessTeam.PL)
public class VersionInfoManagerV2 {

    private final String versionFilePath = "/opt/harness/version.yaml";
    private Optional<VersionInfoV2> cachedVersionInfo = Optional.empty();

    public VersionInfoV2 getVersionInfo() throws VersionInfoException {
        // Check if the version info is already cached
        if (cachedVersionInfo.isPresent()) {
            log.info("Returning cached version info.");
            return cachedVersionInfo.get();
        }

        try (InputStream inputStream = new FileInputStream(versionFilePath)) {
            // Parse YAML file
            Yaml yaml = new Yaml();
            Map<String, Object> data = yaml.load(inputStream);

            if (data == null) {
                log.error("YAML file is empty or invalid.");
                throw new VersionInfoException("YAML file is empty or invalid.");
            }

            // Create a VersionInfo object to store the data
            VersionInfoV2 versionInfo = VersionInfoV2.builder()
                    .buildVersion((String) data.get("BUILD_VERSION"))
                    .buildTime(((Date) data.get("BUILD_TIME")).toInstant().truncatedTo(ChronoUnit.SECONDS))
                    .branchName((String) data.get("BRANCH_NAME"))
                    .commitSha((String) data.get("COMMIT_SHA"))
                    .build();

            // Cache the version info
            cachedVersionInfo = Optional.of(versionInfo);

            return versionInfo;
        } catch (FileNotFoundException e) {
            log.error("Version file not found: {}", versionFilePath, e);
            throw new VersionInfoException("Version file not found: " + versionFilePath, e);
        } catch (IOException | YAMLException | ClassCastException e) {
            log.error("Error processing YAML file: {}", e.getMessage(), e);
            throw new VersionInfoException("Error processing YAML file: " + e.getMessage(), e);
        } catch (Exception e) {
            log.error("Failed to retrieve version info: {}", e.getMessage(), e);
            throw new VersionInfoException("Failed to retrieve version info: " + e.getMessage(), e);
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2023-11-17 15:30 UTC, Vbhatia20 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55372)* status: 2 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHWfl8DSAwsfnwtW2v:-NjStgIZD4S9BIkSaV0B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L27)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we cache the version info so that we don't recompute it every-time a request comes.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHWms82QaanfJBllJX:-NjStguo1KL9-krYQI2o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should handle IOException here.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHX7WH-M5v-ZrqY8yJ:-NjSthjPBjo2nYqN7hpS:bayeh00) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L38)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is this working (Date) data.get("BUILD_TIME")? Have we tested it?
</blockquote></details>

yes it works, I raised PR post testing and results are there in PR description
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/55372#gh-1393659239:-NjStoa3BSNm14OGXPG-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L46)):*
<details><summary><i>Previously, kapilgarg1996 (kapil garg) wrote…</i></summary><blockquote>

should we catch specific exceptions here ? All the stuff which can go wrong
- file not found
- yaml parse error
and instead of throwing runtime exception, we can throw a Checked exception `VersionInfoException`

Suggesting this because its a common utility and will be used by a lot of services. For future integrations, service owners should know what kind of error can come from this.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/55372#-NjQetbwBkRYRR6b79SN:-NjStevk7AVDlFHm1Sbc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07ed306dc91ac58e8ad480328abcece090889e74/980-commons/src/main/java/io/harness/version/VersionInfoManagerV2.java#L28)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Slightly improved version
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoV2.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHX-ji9zP4NoBtHjJJ:-NjStpsQBSZNeKRISxzr:b-syyt1f) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoV2.java#L22)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we have tag info as well?
</blockquote></details>

not required.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoV2.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/55372#-NjHXHzJA70m8lm-C5be:-NjStrim0SiBUyTt-YrF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/VersionInfoV2.java#L24)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Use of Instant class is recommended now over Date class
</blockquote></details>

Done.
___
*[`platform-service/build/container/Dockerfile-platform-service-multistage` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/55372#gh-1393661491:-NjStyMl1nQNFXiis-by:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/platform-service/build/container/Dockerfile-platform-service-multistage#L22)):*
<details><summary><i>Previously, kapilgarg1996 (kapil garg) wrote…</i></summary><blockquote>

shouldn't this be auto-populated ? Whenever the dockerfile is run, that should be the build time. Please confirm with @ankit-harness once.
</blockquote></details>

Done.
___
*[`platform-service/build/container/Dockerfile-platform-service-multistage` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/55372#-NjQdOs11wV1YQ-Chq1W:-NjSttSZ6tY_hs96ZqZf:b-nan2ei) ([raw file](https://github.com/harness/harness-core/blob/07ed306dc91ac58e8ad480328abcece090889e74/platform-service/build/container/Dockerfile-platform-service-multistage#L21)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this be

RUN echo "BUILD_VERSION: $BUILD_VERSION" >> version.yaml
</blockquote></details>

nope, its tested.
___
*[`980-commons/src/main/java/io/harness/version/BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/55372#gh-1393657543:-NjStX5e9GL2gXYZJGPO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/281ec4d791a2bb0d361f71d18d6a1d933496d07f/980-commons/src/main/java/io/harness/version/BUILD.bazel#L26)):*
<details><summary><i>Previously, kapilgarg1996 (kapil garg) wrote…</i></summary><blockquote>

is this required anymore ?
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/version/VersionInfoException.java` line 12 at r5](https://reviewable.io/reviews/harness/harness-core/55372#-NjQdmnD1FIGDKshrJgE:-NjStZl0348brdsI00mh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/07ed306dc91ac58e8ad480328abcece090889e74/980-commons/src/main/java/io/harness/version/VersionInfoException.java#L12)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

There is already a VersionInfoException - io.harness.version.VersionInfoManager
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-17 15:49 UTC, ankit-harness approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55372)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-17 15:49 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55372#-:-NjSyLtP0c4IrGtWYVpA:bnfp4nl)* status: 3. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-12-19 19:43 UTC, bot2-harness commented
This PR has been automatically closed due to inactivity.

2023-12-19 19:43 UTC, closed without merging