[feat]: [SRM-14726]: write to CompositeSLORecordBucket in addition to write to CompositeSLORecord
harness/harness-core pull request #55395
Opened 2023-11-15 09:15 UTC by n00bitax

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-16 04:22 UTC, n00bitax commented
trigger uts

2023-11-17 05:08 UTC, deepak-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55395)* status: 13 file(s) to review. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/55395#-NjQeOdKErXY2OtqKExu:-NjQeOdLDqfism2nIxjN:b1ufw7y) ([raw file](https://github.com/harness/harness-core/blob/d7ca8ba58cab5e3ca0a75dbd2193579092a9257a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java#L74)):*
> ```Java
>   @Id private String uuid;
>   @FdIndex private String verificationTaskId;
>   private String sloId;
> ```

We can remove one of the verification task id or sloId.
I will say sloId. Since verification task id helps in code cleanup(unless we are ready to change that logic).
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/55395#-NjQe9Xp89zTM76Rob0-:-NjQe9Xp89zTM76Rob00:b-sg3iog) ([raw file](https://github.com/harness/harness-core/blob/d7ca8ba58cab5e3ca0a75dbd2193579092a9257a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java#L76)):*
> ```Java
>   private String sloId;
>   private Instant startTimestamp; // minute
>   @Setter(AccessLevel.PRIVATE) private long epochMinute;
> ```

we can drop epochMinute. I don't think we use it. If it was added in SLIBucketRecord we should remove from there as well @Varsha-lalwani 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordBucketService.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/55395#-NjQed2t85ePb0Z35Op1:-NjQed2t85ePb0Z35Op2:b-vdn57p) ([raw file](https://github.com/harness/harness-core/blob/d7ca8ba58cab5e3ca0a75dbd2193579092a9257a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordBucketService.java#L53)):*
> ```Java
>       SLIRecordBucket sliRecordBucket, ServiceLevelIndicator serviceLevelIndicator);
> 
>   org.apache.commons.math3.util
> ```

We should not have complete class path. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/55395#-NjQf9aLDRulW9ukL9JC:-NjQf9aLDRulW9ukL9JD:b-fu5lnq) ([raw file](https://github.com/harness/harness-core/blob/d7ca8ba58cab5e3ca0a75dbd2193579092a9257a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java#L78)):*
> ```Java
>   }
> 
>   private Instant getStartTime(CompositeServiceLevelObjective compositeServiceLevelObjective) {
> ```

Good one. But if we make it a AbstractSLO function only it will be great. We have this code scatttered at multiple places in the codebase.


<!-- Sent from Reviewable.io -->

2023-11-17 09:23 UTC, n00bitax commented
trigger uts

2023-11-20 02:51 UTC, n00bitax commented
trigger uts

2023-11-20 04:51 UTC, n00bitax commented
trigger uts

2023-11-20 06:52 UTC, Varsha-lalwani requested changes

2023-11-20 06:52 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordBucketServiceImpl.java
> +          Instant timeOfLastRecordWhichIsFixed = lastSLIRecordBucket.getBucketStartTime().minus(
will also need to round this down to nearest 5 minutes

2023-11-20 06:52 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordBucketServiceImplTest.java
> +  @Owner(developers = VARSHA_LALWANI)
can you change the owner to yourself

2023-11-20 08:18 UTC, n00bitax commented
trigger uts

2023-11-20 08:26 UTC, n00bitax commented
trigger uts

2023-11-20 08:36 UTC, n00bitax commented
trigger messagecheck

2023-11-20 08:37 UTC, n00bitax commented
trigger uts

2023-11-21 03:50 UTC, n00bitax commented
trigger uts

2023-11-21 03:50 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordBucketServiceImplTest.java
> +  @Owner(developers = VARSHA_LALWANI)
done

2023-11-21 03:50 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordBucketServiceImpl.java
> +          Instant timeOfLastRecordWhichIsFixed = lastSLIRecordBucket.getBucketStartTime().minus(
done

2023-11-21 03:51 UTC, n00bitax commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java
> +  private Instant startTimestamp; // minute
done

2023-11-21 04:16 UTC, n00bitax commented
trigger uts

2023-11-21 04:54 UTC, n00bitax commented
trigger uts

2023-11-21 05:11 UTC, Varsha-lalwani reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55395)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/55395#-NjQe9Xp89zTM76Rob0-:-NjkHT27Dm0xlIhhuNo_:bdzlbjb) ([raw file](https://github.com/harness/harness-core/blob/d7ca8ba58cab5e3ca0a75dbd2193579092a9257a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java#L76)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

we can drop epochMinute. I don't think we use it. If it was added in SLIBucketRecord we should remove from there as well @Varsha-lalwani
</blockquote></details>

yes we should.


<!-- Sent from Reviewable.io -->

2023-11-21 05:26 UTC, n00bitax commented
trigger uts

2023-11-21 05:58 UTC, n00bitax commented
trigger uts

2023-11-21 06:06 UTC, Varsha-lalwani approved these changes

2023-11-21 06:17 UTC, Varsha-lalwani commented
trigger uts

2023-11-21 06:28 UTC, n00bitax commented
trigger ut5,ut9

2023-11-21 06:58 UTC, n00bitax commented
trigger ut5,ut6,ut7,ut8,ut9

2023-11-21 07:55 UTC, n00bitax commented
trigger ut6,ut7,ut9

2023-11-21 09:16 UTC, n00bitax commented
trigger ut7,ut8,ut9

2023-11-21 10:14 UTC, merged