feat: [PLG-3030]: Build the account level overwrites developer mapping structure
harness/harness-core pull request #55424
Opened 2023-11-15 14:46 UTC by Xin-Harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-15 15:39 UTC, Xin-Harness commented
trigger uts

2023-11-16 12:38 UTC, neelam-harness requested changes

2023-11-16 12:38 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/resources/AccountResource.java
> +  @Path("{accountId}/ng/developer-mappings")
Let's keep the endpoint name in singular and shouldn't this be more like as follows:
`ng/developer-mapping/{accountId}` ?

2023-11-16 12:38 UTC, neelam-harness commented on 400-rest/src/main/java/software/wings/resources/AccountResource.java
> +  @Path("{accountId}/ng/developer-mappings")
Same here, path should be in this pattern: `ng/developer-mapping/{accountId}`

2023-11-16 12:38 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java
> +@Api("admin/developer-mappings")
name change required here too: `admin/developer-mapping`

2023-11-16 12:38 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java
> +  @ApiOperation(value = "create account level overwrites primary to secondary entitlement mapping",
nit: `Create account level override for primary to secondary mapping ratio.`

2023-11-16 12:38 UTC, neelam-harness commented on 960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules/DeveloperMappingDTO.java
> + * Copyright 2021 Harness Inc. All rights reserved.
nit: `2021` -> `2023`

2023-11-16 12:38 UTC, neelam-harness commented on 960-ng-license-beans/src/main/java/io/harness/licensing/remote/admin/AdminLicenseHttpClient.java
> +  String ADMIN_DEVELOPER_MAPPING = "admin/developer-mappings";
change to `admin/developer-mapping`

2023-11-16 12:42 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 738 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN-bt9AhKVfPbK3Hnk:-NjN-bt9AhKVfPbK3Hnl:b-haxt5d) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L738)):*
> ```Java
> 
>   @POST
>   @Path("{accountId}/ng/developer-mappings")
> ```

lets make it more verbose "developer-license-mapping" because for a 3rd person it doesn't make sense what "developer-mapping"?
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 748 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN01nuAGhI4r4EdPdz:-NjN01nvChD4HhgN56Lf:b-ptjsdg) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L748)):*
> ```Java
>     if (harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
>       return new RestResponse<>(
>           getResponse(adminLicenseHttpClient.createAccountLevelDeveloperMapping(clientAccountId, developerMappingDTO)));
> ```

better name createDeveloperLicenseMapping(), no need to add 'AccountLevel'
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 758 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN0D331AtZVQO2O9sD:-NjN0D343Aw6_XzyhTVW:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L758)):*
> ```Java
> 
>   @GET
>   @Path("{accountId}/ng/developer-mappings")
> ```

same here
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 767 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN0E0q9XmhlceXBZ15:-NjN0E0rDxopk5EQgFJk:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L767)):*
> ```Java
>     }
>     if (harnessUserGroupService.isHarnessSupportUser(existingUser.getUuid())) {
>       return new RestResponse<>(getResponse(adminLicenseHttpClient.getAccountLevelDeveloperMapping(clientAccountId)));
> ```

same here
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN2EbU58TE7rZF11Nr:-NjN2EbX-Gy3Z_mNBiZZ:b-ysdxl0) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L37)):*
> ```Java
> import retrofit2.http.Body;
> 
> @Api("admin/developer-mappings")
> ```

would become "developer-license-mapping"
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6AZG0KnBSqLxi9jm:-NjN6AZG0KnBSqLxi9jn:b-imiouz) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L89)):*
> ```Java
>       @Body DeveloperMappingDTO developerMappingDTO) {
>     DeveloperMappingDTO createdDeveloperMappingDTO =
>         developerMappingService.createAccountLevelDeveloperMapping(accountIdentifier, developerMappingDTO);
> ```

"AccountLevel" is not required in the name
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6Gi-A5BnY19yRsFm:-NjN6Gi-A5BnY19yRsFn:blm27lv) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java#L52)):*
> ```Java
>   @Trimmed @NotEmpty protected String accountIdentifier;
>   @NotEmpty protected ModuleType moduleType;
>   @NotEmpty protected int developerCount;
> ```

I mentioned in the doc as well, developerLicenseCount is not required here let's have ratio here e.g. developerLicenseToSecondaryEntitlementRatio with SecondaryEntitlementName
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6f2F0miLW5XM_OIc:-NjN6f2F0miLW5XM_OId:b-ov36c1) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java#L63)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(CompoundMongoIndex.builder()
>                  .name("accountIdentifier_developerMapping_query_index")
> ```

can be named to accountIdentifier_moduleType_secondaryEntitlement_query_index
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN77QyEO1aG2cyevjl:-NjN77QyEO1aG2cyevjm:b-xjwjo9) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java#L16)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.GTM)
> public interface DeveloperMappingService {
> ```

would become DeveloperLicenseMappingService
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN7Q2HCvlEY1uzYlk2:-NjN7Q2HCvlEY1uzYlk3:ba3qxwq) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L50)):*
> ```Java
>             accountIdentifier, developerMappingDTO.getModuleType(), developerMappingDTO.getSecondaryEntitlement());
>     if (existingDeveloperMapping.size() != 0) {
>       throw new InvalidRequestException(String.format(
> ```

lets throw a Duplicate exception

Also you can add this check in ValidateAccountInfo() and rename it to validateDTO(). All validations can sit inside 1 method.
___
*[`960-ng-license-beans/src/main/java/io/harness/licensing/remote/admin/AdminLicenseHttpClient.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/55424#gh-1395631590:-NjN8Yqr84npFXUnpt5m:br6mim5) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/960-ng-license-beans/src/main/java/io/harness/licensing/remote/admin/AdminLicenseHttpClient.java#L32)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

change to `admin/developer-mapping`
</blockquote></details>

@Xin-Harness lets not add developer-license-mapping API client here, as its specific to "/license" APIs.

Lets create a separate class
___
*[`970-ng-commons/src/main/java/io/harness/entities/SecondaryEntitlement.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN8mVIBFg5EUtyJjRG:-NjN8mVIBFg5EUtyJjRH:b-q18vke) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/970-ng-commons/src/main/java/io/harness/entities/SecondaryEntitlement.java#L14)):*
> ```Java
> @OwnedBy(HarnessTeam.GTM)
> public enum SecondaryEntitlement {
>   WORK_LOADS,
> ```

lets add all the secondary entitlements here 


<!-- Sent from Reviewable.io -->

2023-11-17 06:47 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/55424#gh-1395620892:-NjR-5DK4gPRh2BoCb2L:b-4ne2qm) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L76)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

nit: `Create account level override for primary to secondary mapping ratio.`
</blockquote></details>

we don't need these annotations itself for internal apis


<!-- Sent from Reviewable.io -->

2023-11-17 06:51 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjR1w8pEL8--Nqgu5DQ:-NjR1w8pEL8--Nqgu5DR:bxpfb06) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L49)):*
> ```Java
>         developerMappingRepository.findByAccountIdentifierAndModuleTypeAndSecondaryEntitlement(
>             accountIdentifier, developerMappingDTO.getModuleType(), developerMappingDTO.getSecondaryEntitlement());
>     if (existingDeveloperMapping.size() != 0) {
> ```

instead of explicit check, we should rely on unique indexing in our DB to throw duplicate key exception itself while saving an object. 


<!-- Sent from Reviewable.io -->

2023-11-17 06:51 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjR26no2eUv520gea_S:-NjR26no2eUv520gea_T:b-5iyno4) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L62)):*
> ```Java
>     if (!accountIdentifier.equals(developerMappingDTO.getAccountIdentifier())) {
>       String errorMessage = String.format(
>           "Account Identifier: [%s] did not match with the developer mapping information", accountIdentifier);
> ```

we should have logged the account id from developer mapping as well, otherwise we don't know what was the mismatch.


<!-- Sent from Reviewable.io -->

2023-11-17 14:44 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/resources/AccountResource.java
> +  @Path("{accountId}/ng/developer-mappings")
It is a good practice to use plural nouns in this case. Using plural nouns is a common convention in REST API design. It helps ensure consistency and better reflects the possibility of the endpoint returning multiple resources.

2023-11-17 14:45 UTC, Xin-Harness commented on 400-rest/src/main/java/software/wings/resources/AccountResource.java
> +  @Path("{accountId}/ng/developer-mappings")
It is a good practice to use plural nouns in this case. Using plural nouns is a common convention in REST API design. It helps ensure consistency and better reflects the possibility of the endpoint returning multiple resources.

2023-11-17 14:45 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java
> +@Api("admin/developer-mappings")
It is a good practice to use plural nouns in this case. Using plural nouns is a common convention in REST API design. It helps ensure consistency and better reflects the possibility of the endpoint returning multiple resources.

2023-11-17 15:47 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 738 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN-bt9AhKVfPbK3Hnk:-NjSq1TNAp6rCrywWTRg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L738)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

lets make it more verbose "developer-license-mapping" because for a 3rd person it doesn't make sense what "developer-mapping"?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 748 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN01nuAGhI4r4EdPdz:-NjSq2T67daRnc3QCEmG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L748)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

better name createDeveloperLicenseMapping(), no need to add 'AccountLevel'
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 758 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN0D331AtZVQO2O9sD:-NjSq5kW2lDrNiILinVN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L758)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 767 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN0E0q9XmhlceXBZ15:-NjSxINqEQzdhmG8AjSq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L767)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN2EbU58TE7rZF11Nr:-NjSqC4A-uHVwns4Qilp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L37)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

would become "developer-license-mapping"
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/55424#gh-1395620892:-NjSqI6N8oWWbGrADx03:b-1eyql9) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L76)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we don't need these annotations itself for internal apis
</blockquote></details>

It helps us better understand the APIs. In this case, I will keep it. Thank you for letting me know the info.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6AZG0KnBSqLxi9jm:-NjSqwd6CgCYb_coP57I:bchqias) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L89)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

"AccountLevel" is not required in the name
</blockquote></details>

It will help us distinguish account level developer mapping comparing to default developer mapping. I will keep the same name here for clarity. 
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6Gi-A5BnY19yRsFm:-NjSrIXg5OrFxAqctYL9:bcy534x) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java#L52)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

I mentioned in the doc as well, developerLicenseCount is not required here let's have ratio here e.g. developerLicenseToSecondaryEntitlementRatio with SecondaryEntitlementName
</blockquote></details>

The API record the exact information how many developer map to how many secondary entitlement counts. The ratio would be calculated based on the number of developer/ secondary entitlement counts with the number that stored in db. We will not store ratio itself, why? Because it is a very hard to read percentage, for example 0.25, 0.125 etc, which is not user friendly when CSE use this API. In the future, we may also need to display this information to customer, and the ratio itself is not a readable data.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6f2F0miLW5XM_OIc:-NjSxACu3xrQ_E7wH5go:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java#L63)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

can be named to accountIdentifier_moduleType_secondaryEntitlement_query_index
</blockquote></details>

Done.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN77QyEO1aG2cyevjl:-NjStYT80-Lu7O6Q_jcc:b-bdsz1d) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java#L16)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

would become DeveloperLicenseMappingService
</blockquote></details>

In my opinion, developer license is more a concept that opens to end users but it is not a real license. So under neath it is not a kind of license type. In this case, developer mapping service would be more crips and close to developer language. 
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjR1w8pEL8--Nqgu5DQ:-NjSvAWR62fIJ8P0Lwah:bjvq4h3) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

instead of explicit check, we should rely on unique indexing in our DB to throw duplicate key exception itself while saving an object.
</blockquote></details>

I have different opinion here, the [...]

2023-11-17 15:52 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 748 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN01nuAGhI4r4EdPdz:-NjSyn5Q4JpRoDsJq2q-:b-xh9ph4) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L748)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Keep the accountLevel has its meaningful reason since it indicate it create for explicit for account level not for default level. I added it back
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 758 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN0D331AtZVQO2O9sD:-NjSz0ieAX8ZzD9KG42k:b-xh9ph4) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L758)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Keep the accountLevel has its meaningful reason since it indicate it create for explicit for account level not for default level. I added it back


<!-- Sent from Reviewable.io -->

2023-11-17 15:52 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 17. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 767 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN0E0q9XmhlceXBZ15:-NjSz2ks5j_xEJRgNm4w:b-xh9ph4) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L767)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Keep the accountLevel has its meaningful reason since it indicate it create for explicit for account level not for default level. I added it back


<!-- Sent from Reviewable.io -->

2023-11-17 19:48 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/55424#gh-1395620892:-NjTohT48P-wxdN42zyx:b-xbj407) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L76)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

It helps us better understand the APIs. In this case, I will keep it. Thank you for letting me know the info.
</blockquote></details>

If we require for understanding, I would rather say add comments and not specific annotations. Also, @ApiOperation and @Operation are just duplicate swagger annotations used for different versions.


<!-- Sent from Reviewable.io -->

2023-11-17 19:49 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjR1w8pEL8--Nqgu5DQ:-NjToyDc3hZQ7VfjkAHC:b-6ytsv9) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L49)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

I have different opinion here, the pre check will give customer a more intuitive information rather than telling CSE team there is a duplicate key while trying to save in db.
</blockquote></details>

Catch the duplicateKey Exception and throw a customized exception. The explicit check doesn't anyways work for multithreaded system like us.

![image.png](https://files.reviewableusercontent.io/images/reviewable/75259284/IXfE8V7eZ80_ISoY9D4MDnH8/image.png)


<!-- Sent from Reviewable.io -->

2023-11-19 17:28 UTC, kapil-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 748 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN01nuAGhI4r4EdPdz:-NjcYfbyCiM7T4dSLWTk:bd0eht) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L748)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Keep the accountLevel has its meaningful reason since it indicate it create for explicit for account level not for default level. I added it back
</blockquote></details>

I don't agree with this but as it is not a blocking comment I will resolve.
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 767 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN0E0q9XmhlceXBZ15:-NjcYx381zxK9tpPb8Dp:bd0eht) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/400-rest/src/main/java/software/wings/resources/AccountResource.java#L767)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Keep the accountLevel has its meaningful reason since it indicate it create for explicit for account level not for default level. I added it back
</blockquote></details>

I don't agree with this but as it is not a blocking comment I will resolve.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6AZG0KnBSqLxi9jm:-NjcZb4f4EKYtUi6nALa:b-aq3faq) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L89)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

It will help us distinguish account level developer mapping comparing to default developer mapping. I will keep the same name here for clarity.
</blockquote></details>

default mappings are default and would make up for very less no. of records inside DeveloperLicenseMapping collection, so doesn't matter much to put AccountLevel in the naming. However I am resolving for now.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/55424#-NjcZB_P2YSPSiGuOrPH:-NjcZB_QBgy4WobPstNU:b-r9a3iz) ([raw file](https://github.com/harness/harness-core/blob/13940d11a6d6330843ecae22956e5a76713fabfe/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/AdminDeveloperMappingResource.java#L49)):*
> ```Java
> @Hidden
> @OwnedBy(HarnessTeam.GTM)
> public class AdminDeveloperMappingResource {
> ```

name would change from AdminDeveloperMappingResource -> AdminDeveloperLicenseMappingResource
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN6Gi-A5BnY19yRsFm:-NjcZzZOErZLdwqlp5J-:b-5lf285) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java#L52)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

The API record the exact information how many developer map to how many secondary entitlement counts. The ratio would be calculated based on the number of developer/ secondary entitlement counts with the number that stored in db. We will not store ratio itself, why? Because it is a very hard to read percentage, for example 0.25, 0.125 etc, which is not user friendly when CSE use this API. In the future, we may also need to display this information to customer, and the ratio itself is not a readable data.
</blockquote></details>

@Xin-Harness Agreed.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/55424#-Njc_Cgu7zm0_vI_X6YD:-Njc_Cgu7zm0_vI_X6YE:b3riewu) ([raw file](https://github.com/harness/harness-core/blob/e12aefd9fc6b416ce7f3b6df63dc2e0821f9b29e/930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java#L46)):*
> ```Java
> @Document("developerMappings")
> @Persistent
> public class DeveloperMapping implements PersistentEntity, NGAccountAccess {
> ```

can we name this collection as DeveloperLicenseMapping?
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN77QyEO1aG2cyevjl:-Njc_O1q1nxy4qOImdhd:b-u8asox) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java#L16)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

In my opinion, developer license is more a concept that opens to end users but it is not a real license. So under neath it is not a kind of license type. In this case, developer mapping service would be more crips and close to developer language.
</blockquote></details>

Lest take a close look at the word "DeveloperMapping", let's break it into 2 parts "Developer" and "Mapping". "Mapping" suggests that we will store some kind of mapping in this collection and what does "Developer" suggests? Not much to be honest. 

"DeveloperLicenseMapping" suggests that it's a mapping from No. of developers to Secondary entitlement license which is the actual license at the module level. So this table has something to do with licensing framework. So this makes it more verbose.

Also, we have a field called developerLicenseCount in ModuleLicense collection and DTO which has a direct relation to this table and should be named similar to each other.
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjR1w8pEL8--Nqgu5DQ:-NjcbUiL4wUIhR_Ncswh:b6v0v42) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Catch the duplicateKey Exception and throw a customized exception. The explicit check doesn't anyways work for multithreaded system like us.

![image.png](https://files.reviewableusercontent.io/images/reviewable/75259284/IXfE8V7eZ80_ISoY9D4MDnH8/image.png)
</blockquote></details>

@mohitg0795 Pls help me understand this, you mean in our multi threaded system having a explicit check like this may miss some duplicates in the DB??
___
*[`930-ng-license-manager/src/main/java/io/harness/repositories/DeveloperMappingRepository.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/55424#-NjcbvWo-DyiIVKupGlS:-NjcbvWo-DyiIVKupGlT:b-kdb6or) ([raw file](https://github.com/harness/harness-core/blob/13940d11a6d6330843ecae22956e5a76713fabfe/930-ng-license-manager/src/main/java/io/harness/repositories/DeveloperMappingRepository.java#L23)):*
> ```Java
> @HarnessRepo
> @Transactional
> public interface DeveloperMappingRepository extends CrudRepository<DeveloperMapping, String> {
> ```

would become DeveloperMappingRepository -> DeveloperLicenseMappingRepository 


<!-- Sent from Reviewable.io -->

2023-11-20 02:17 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN77QyEO1aG2cyevjl:-NjeTIt_-ThkIWlBAVm7:b-f3s991) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingService.java#L16)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

Lest take a close look at the word "DeveloperMapping", let's break it into 2 parts "Developer" and "Mapping". "Mapping" suggests that we will store some kind of mapping in this collection and what does "Developer" suggests? Not much to be honest. 

"DeveloperLicenseMapping" suggests that it's a mapping from No. of developers to Secondary entitlement license which is the actual license at the module level. So this table has something to do with licensing framework. So this makes it more verbose.

Also, we have a field called developerLicenseCount in ModuleLicense collection and DTO which has a direct relation to this table and should be named similar to each other.
</blockquote></details>

When we look at developerLicenseCount you may think about the license counts rather than developer counts. In my opinion, my first intuitive is developer counts means the number of developers and developer license counts means the number of a license which is developer type.  So rename everything from developerMapping to developer license mapping is a bit tricky. Lets resolve the PR for now and we need to discuss with team internally about the naming itself, then we can use a separate PR just to change all the names if that make sense to you.


<!-- Sent from Reviewable.io -->

2023-11-20 02:26 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/55424#-Njc_Cgu7zm0_vI_X6YD:-NjeY8Hn6-cS9JbWZWg1:b-l72f2b) ([raw file](https://github.com/harness/harness-core/blob/e12aefd9fc6b416ce7f3b6df63dc2e0821f9b29e/930-ng-license-manager/src/main/java/io/harness/licensing/entities/developer/DeveloperMapping.java#L46)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

can we name this collection as DeveloperLicenseMapping?
</blockquote></details>

Replied below, please check. 
___
*[`930-ng-license-manager/src/main/java/io/harness/repositories/DeveloperMappingRepository.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/55424#-NjcbvWo-DyiIVKupGlS:-NjeXbAWCNZdlv-8hztX:b3neg15) ([raw file](https://github.com/harness/harness-core/blob/13940d11a6d6330843ecae22956e5a76713fabfe/930-ng-license-manager/src/main/java/io/harness/repositories/DeveloperMappingRepository.java#L23)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

would become DeveloperMappingRepository -> DeveloperLicenseMappingRepository
</blockquote></details>

Replied above, please check. 
___
*[`960-ng-license-beans/src/main/java/io/harness/licensing/remote/admin/AdminLicenseHttpClient.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/55424#gh-1395631590:-NjeX4bb8xVjZJB6uUlb:bke0ge3) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/960-ng-license-beans/src/main/java/io/harness/licensing/remote/admin/AdminLicenseHttpClient.java#L32)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

@Xin-Harness lets not add developer-license-mapping API client here, as its specific to "/license" APIs.

Lets create a separate class
</blockquote></details>

The reason adding it here is because this also part of license management, not like adminCreditHttpClient which is a totally separate concept, credits. So, let's not over engineer and still keep it in the adminLicenseHttpClient.
___
*[`970-ng-commons/src/main/java/io/harness/entities/SecondaryEntitlement.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN8mVIBFg5EUtyJjRG:-NjeWNCd6T79geJ71hB-:b-sb29pp) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/970-ng-commons/src/main/java/io/harness/entities/SecondaryEntitlement.java#L14)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

lets add all the secondary entitlements here
</blockquote></details>

I will need to add it in a separate PR. Why? Because We shouldn't make this PR infinitely big and keep adding new requirements when it comes out.  In addition,  I will also add some mapping logic between module type to secondary entitlement just to ensure we are not adding the wrong secondary entitlement to the wrong module. Lets just add one here and expend it in next PR. 


<!-- Sent from Reviewable.io -->

2023-11-20 02:31 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 3 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjR1w8pEL8--Nqgu5DQ:-NjeYDYg6ZAUNKUKzUCJ:b-f58jub) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L49)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

@mohitg0795 Pls help me understand this, you mean in our multi threaded system having a explicit check like this may miss some duplicates in the DB??
</blockquote></details>

@mohitg0795 Same check is used in current defaultLicenseServiceImpl , but didn't see any issue in our multi threaded system. What happen behind the scene when this check was used in multithread system?
![image.png](https://files.reviewableusercontent.io/images/reviewable/80720012/TLlMPL4n_FotYVD3Nlc--DZn/image.png)


<!-- Sent from Reviewable.io -->

2023-11-20 03:17 UTC, neelam-harness requested changes

2023-11-20 03:17 UTC, neelam-harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java
> +    if (existingDeveloperMapping.size() != 0) {
We should use `!existingDeveloperMapping.isEmpty()` method here to check if it contains elements or not instead of checking the size.

2023-11-20 07:29 UTC, kapil-harness submitted a review, later dismissed
> Reviewed 5 of 12 files at r1, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 2 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/entities/SecondaryEntitlement.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjN8mVIBFg5EUtyJjRG:-Njfc9kB5VpEWflaGjNg:b-ulbhaa) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/970-ng-commons/src/main/java/io/harness/entities/SecondaryEntitlement.java#L14)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

I will need to add it in a separate PR. Why? Because We shouldn't make this PR infinitely big and keep adding new requirements when it comes out.  In addition,  I will also add some mapping logic between module type to secondary entitlement just to ensure we are not adding the wrong secondary entitlement to the wrong module. Lets just add one here and expend it in next PR.
</blockquote></details>

in that case the comma should have been replaced by a semi colon, I think your build would be failing in this case. Resolving for now.


<!-- Sent from Reviewable.io -->

2023-11-20 09:02 UTC, neelam-harness submitted a review, later dismissed

2023-11-20 14:27 UTC, neelam-harness approved these changes

2023-11-20 15:13 UTC, kapil-harness approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 1 change requests. 5. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-20 15:14 UTC, Xin-Harness commented
trigger review

2023-11-20 16:22 UTC, Xin-Harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55424)* status: 12 file(s) to review. 1 change requests. 6. unresolved discussions. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/55424#-NjR1w8pEL8--Nqgu5DQ:-NjhXM22-MZHgLNb03Ah:b-tr9xoz) ([raw file](https://github.com/harness/harness-core/blob/8c78c46bc9d45252fc354c08ff4112c900f4ff54/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L49)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

@mohitg0795 Same check is used in current defaultLicenseServiceImpl , but didn't see any issue in our multi threaded system. What happen behind the scene when this check was used in multithread system?
![image.png](https://files.reviewableusercontent.io/images/reviewable/80720012/TLlMPL4n_FotYVD3Nlc--DZn/image.png)
</blockquote></details>

I tried your way and did the test in my local as I changed the developerMapping db index to have unique index and do duplicate entry check during save. However it doesn’t take affect as what I expected.So far I will put precheck ahead like what our license api do. I will need to spend more time just to think through the way you have suggested. I can raise separate PR just for this enhancement
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/55424#gh-1398619831:-NjhXYvYA6E__iCmX5f5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/13940d11a6d6330843ecae22956e5a76713fabfe/930-ng-license-manager/src/main/java/io/harness/licensing/services/DeveloperMappingServiceImpl.java#L63)):*
<details><summary><i>Previously, neelam-harness (Neelam) wrote…</i></summary><blockquote>

We should use `!existingDeveloperMapping.isEmpty()` method here to check if it contains elements or not instead of checking the size.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-20 16:24 UTC, Xin-Harness commented
trigger uts

2023-11-20 17:04 UTC, merged