fix: [PL-42562]: Audit Entry for version override entry
harness/harness-core pull request #55466
Opened 2023-11-16 06:25 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-16 09:47 UTC, mdmilic requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55466)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMPmVg7Ovi-Z5kveSY:-NjMPmVh0b8xBB_xYEYB:b-lakx9g) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java#L36)):*
> ```Java
> public class AdminDelegateVersionService {
>   private final HPersistence persistence;
>   private OutboxService outboxService;
> ```

You have to make it final, otherwise it wouldn't get injected - wouldn't be set in the constructor (the lombok is marked to create required args ctor - which means for final fields). 
___
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMVdHPDX4BV_oXf9as:-NjMVdHQ0PNZBL2M33DA:b-aeh1ej) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java#L87)):*
> ```Java
>       if (filter.get() != null) {
>         delegateVersionOverrideEventBuilder.versionOverrideOld(
>             VersionOverride.auditBuilder(filter.get().getVersion()).build());
> ```

This would not give you the old version since you've already overwritten it in the DB on ln 80 (upsert). What you can do instead is upsertReturnOldOptions (which would give you old version before update, and new version is `overrideValue`. We should also probably include overrideType in the audit trail as well and all the validity fields also. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/VersionOverride.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMTWtyApxChW61b2j2:-NjMTWtyApxChW61b2j3:b-oo8q6f) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/beans/VersionOverride.java#L50)):*
> ```Java
>     return new VersionOverrideBuilder().accountId(accountId);
>   }
>   public static VersionOverrideBuilder auditBuilder(final String version) {
> ```

This build method is breaking the contract that accountId is a mandatory field (i.e. marked as NotEmpty). In general this format of builder factory methods is used when you want to make some field mandatory (i.e. so far you couldn't create the instance of the VersionOverride object without supplying accoutnId because that instance would be invalid). If you want it as a helper method that's also fine, but you should add accountId as a first param here. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMQfp78AZksUuDblJ5:-NjMQfp78AZksUuDblJ6:b-yz7imo) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java#L30)):*
> ```Java
> public class DelegateVersionOverrideEvent extends AbstractDelegateConfigurationEvent {
>   private VersionOverride versionOverride;
>   private VersionOverride versionOverrideOld;
> ```

Make the fields final (to make the object immutable, jackson can cope with that), use RequiredArgsConstructor (instead of no args - which wouldn't be possible with final anyway) and I would advise against Builder altogether (unless you have to use it because of the abstract class). 

Also, if you don't care about any other fields than just version string, you could use String here instead or create a wrapper class that has only the info you need. This way you are coupling DB object with the event and serialization which I don't think you should do. 



_Suggestion:_
```Java
  private final VersionOverride versionOverride;
  private final VersionOverride versionOverrideOld;
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMS0dt5qgPxbMwTL7q:-NjMS0dt5qgPxbMwTL7r:bhza1dp) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java#L41)):*
> ```Java
>   public String getEventType() {
>     return DELEGATE_VERSION_OVERRIDE_EVENT;
>   }
> ```

Minor hack, since you are already using @Getter, you don't need to write getResource and getEventType since they seem static anyway. You can just add a [non-static] field for each (with their default values) and lombok would do the rest. 



_Code quote:_
```Java
  @Override
  public Resource getResource() {
    return Resource.builder().identifier(versionOverrideIdentifier).type(ResourceTypeConstants.DELEGATE).build();
  }

  @Override
  public String getEventType() {
    return DELEGATE_VERSION_OVERRIDE_EVENT;
  }
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMSYVG-MWvsd-MEsUI:-NjMSYVG-MWvsd-MEsUJ:btgtdqq) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java#L73)):*
> ```Java
>           return handleDelegateUnRegisterEvent(outboxEvent);
>         case DELEGATE_VERSION_OVERRIDE_EVENT:
>           return handleDelegateUnRegisterEvent(outboxEvent);
> ```

Wrong handler



_Suggestion:_
```Java
         return handleDelegateVersionOverrideEvent(outboxEvent);
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMSgByE-n7O6lqOWY9:-NjMSgByE-n7O6lqOWYA:b2y2t89) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java#L183)):*
> ```Java
>   }
> 
>   @VisibleForTesting
> ```

Ideally we should just be able to UT this through the parent method ( `handle(outboxEvent)` ) and not reduce the access modifier here. Needs outboxEvent anyway, so we just need to provide appropriate type. 


<!-- Sent from Reviewable.io -->

2023-11-16 19:28 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMPmVg7Ovi-Z5kveSY:-NjOao6MCM_JIXTLl06n:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java#L36)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You have to make it final, otherwise it wouldn't get injected - wouldn't be set in the constructor (the lombok is marked to create required args ctor - which means for final fields).
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-11-16 19:55 UTC, jennyjames21 commented
*[`400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMVdHPDX4BV_oXf9as:-NjOfTXt7-0-nLcLuLxd:b3jxz2f) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java#L87)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This would not give you the old version since you've already overwritten it in the DB on ln 80 (upsert). What you can do instead is upsertReturnOldOptions (which would give you old version before update, and new version is `overrideValue`. We should also probably include overrideType in the audit trail as well and all the validity fields also.
</blockquote></details>

updated, im. not sure overrideType and validity add any value to the customer


<!-- Sent from Reviewable.io -->

2023-11-16 20:34 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/VersionOverride.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMTWtyApxChW61b2j2:-NjOgwHC2nfE5DQP_8bg:b-jsz1gk) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/beans/VersionOverride.java#L50)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This build method is breaking the contract that accountId is a mandatory field (i.e. marked as NotEmpty). In general this format of builder factory methods is used when you want to make some field mandatory (i.e. so far you couldn't create the instance of the VersionOverride object without supplying accoutnId because that instance would be invalid). If you want it as a helper method that's also fine, but you should add accountId as a first param here.
</blockquote></details>

added account id as first param


<!-- Sent from Reviewable.io -->

2023-11-16 20:36 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMQfp78AZksUuDblJ5:-NjOq7Y-9jQZXpyzHrRc:bynugve) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java#L30)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Make the fields final (to make the object immutable, jackson can cope with that), use RequiredArgsConstructor (instead of no args - which wouldn't be possible with final anyway) and I would advise against Builder altogether (unless you have to use it because of the abstract class). 

Also, if you don't care about any other fields than just version string, you could use String here instead or create a wrapper class that has only the info you need. This way you are coupling DB object with the event and serialization which I don't think you should do.
</blockquote></details>

im already using helper class here auditBuilder()

i would prefer to keep it as @NoArgsConstructor as all our audit events follow the same


<!-- Sent from Reviewable.io -->

2023-11-16 20:38 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMS0dt5qgPxbMwTL7q:-NjOqQXh0GDnSBRihPFO:b-xax0i9) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateVersionOverrideEvent.java#L41)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Minor hack, since you are already using @Getter, you don't need to write getResource and getEventType since they seem static anyway. You can just add a [non-static] field for each (with their default values) and lombok would do the rest.
</blockquote></details>

same follow the same as other events, dont see any reason to change


<!-- Sent from Reviewable.io -->

2023-11-16 20:38 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMSYVG-MWvsd-MEsUI:-NjOqr_X-6LC_WO6UykT:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java#L73)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Wrong handler
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2023-11-16 20:39 UTC, jennyjames21 commented
*[`420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/55466#-NjMSgByE-n7O6lqOWY9:-NjOqtJnDxtWQx7bYwK4:b-rf8v08) ([raw file](https://github.com/harness/harness-core/blob/74f50197dfe5bb6a10abdc73a6b49a5a23ad1736/420-delegate-service/src/main/java/io/harness/delegate/outbox/DelegateOutboxEventHandler.java#L183)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Ideally we should just be able to UT this through the parent method ( `handle(outboxEvent)` ) and not reduce the access modifier here. Needs outboxEvent anyway, so we just need to provide appropriate type.
</blockquote></details>

DelegateOutBoxHandler method has code to handle methods based on event type


<!-- Sent from Reviewable.io -->

2023-11-21 22:19 UTC, raghuAtWings requested changes

2023-11-21 22:19 UTC, raghuAtWings commented on 400-rest/src/main/java/io/harness/datahandler/services/AdminDelegateVersionService.java
> +    if (isNotEmpty(oldVersion)) {
why only in case of oldVersion is not empty? shouldn't we do for all updates for a customer

2023-12-18 04:12 UTC, closed without merging