feat:[CDS-81537]: save filter support for overrides
harness/harness-core pull request #55460
Opened 2023-11-16 05:29 UTC by sourabh-awashti

## Describe your changes
Support for Save filters for overrides. These changes includes addition for filter overrides class and changes in ServiceOverrideCriteriaHelper.java for fetching saved filters and including it in critieria.
Test Done:
https://docs.google.com/spreadsheets/d/1y0sYce11tBs5cmeqY-e194bvTIAlRnMCY4q495xyTFo/edit#gid=0
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-16 05:30 UTC, sourabh-awashti commented
trigger uts

2023-11-16 10:13 UTC, sourabh-awashti commented
trigger uts

2023-11-16 12:33 UTC, tchaurasiya requested changes

2023-11-17 06:33 UTC, sourabh-awashti commented on 120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java
>        @RequestBody(description = "This is the body for the filter properties for listing overrides.")
done

2023-11-17 06:33 UTC, sourabh-awashti commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverrideCriteriaHelper.java
> +      String filterIdentifier, FilterService filterService) {
done

2023-11-17 06:34 UTC, sourabh-awashti commented
trigger uts

2023-11-17 06:39 UTC, lovish1999 approved these changes

2023-11-17 07:09 UTC, sourabh-awashti commented
trigger messagecheck

2023-11-17 07:12 UTC, tchaurasiya approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55460)* status: 9 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-17 07:32 UTC, sourabh-awashti commented
trigger uts

2023-11-17 11:04 UTC, senjucanon2 approved these changes
> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55460)* status: 9 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-11-17 11:07 UTC, sourabh-awashti commented
trigger review

2023-11-17 11:07 UTC, lovish1999 approved these changes

2023-11-17 11:10 UTC, merged