[fix]: [CDS-75728]: Logs issue for custom approvals
harness/harness-core pull request #55463
Opened 2023-11-16 05:53 UTC by vtxorxwitty

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-17 14:14 UTC, vtxorxwitty commented
trigger uts

2023-11-20 06:53 UTC, vtxorxwitty commented
trigger uts

2023-11-20 13:15 UTC, puthrayaharness requested changes

2023-11-20 13:15 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java
> +    if (isCustomApprovalFlow) {
Can we pass `commandUnit` string instead of leveraging a boolean? It makes sure that the code is not generic that others can reuse and there is no reference to customApproval in this flow.

2023-11-20 13:29 UTC, naman-goenka reviewed
Can we also check these cases for console log as well

1. Abort of custom approval step after couple of polling events
2. Expiry of custom approval step after couple of polling events
3. Some error while ps script execution like (exit 1).
4. Approval criteria is met after some polling events.

2023-11-20 13:39 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55463)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 431 at r3](https://reviewable.io/reviews/harness/harness-core/55463#gh-1399192201:-NjgxE305ttMPNrUWhKH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/18ca66c92ba3d9706b55e5f65347b2446651ecbf/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L431)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Can we pass `commandUnit` string instead of leveraging a boolean? It makes sure that the code is not generic that others can reuse and there is no reference to customApproval in this flow.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-20 13:45 UTC, puthrayaharness approved these changes

2023-11-20 14:15 UTC, vtxorxwitty commented
trigger uts

2023-11-20 16:39 UTC, hingerabhinav approved these changes
> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55463)* status: 10 file(s) to review. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-20 16:40 UTC, vtxorxwitty commented
trigger review

2023-11-20 16:43 UTC, merged