feat: [CDS-83759]: Telemetry to track Approvals
harness/harness-core pull request #55476
Opened 2023-11-16 07:41 UTC by sarthakkasat

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-16 09:06 UTC, puthrayaharness requested changes

2023-11-16 09:06 UTC, puthrayaharness commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java
> +      case JIRA_APPROVAL:
They should all name same event names. The type should be different.

2023-11-16 10:31 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55476)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/55476#gh-1395370814:-NjMfxagEIxM82YhaEAD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebcfa71145f42ced54c8aa65ae0517e38fb43b2a/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java#L53)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

They should all name same event names. The type should be different.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-16 11:11 UTC, hextechpal requested changes

2023-11-16 11:11 UTC, hextechpal commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/BUILD.bazel
> +        "//pipeline-service/modules/orchestration-steps:module",
This probably is not correct. @archit-harness isnt this module package private lets make if not

2023-11-16 11:11 UTC, hextechpal commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/BUILD.bazel
> +        "//pipeline-service/modules/orchestration-steps:module",
Also why is this needed here

2023-11-16 11:11 UTC, hextechpal commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java
> +    instrumentationHelper.sendApprovalEvent(approvalInstance);
We should add a queue here

2023-11-16 11:57 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/BUILD.bazel
> +        "//pipeline-service/modules/orchestration-steps:module",
We have moved the Instumentation Helper class from 125-cd-nextgen to pipeline service so that all helper classes can extend the same class, if not here where shall we move this class?

2023-11-17 08:35 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/BUILD.bazel
> +        "//pipeline-service/modules/orchestration-steps:module",
I have moved the Instrumentation helper class to telemetry module, have reverted this change

2023-11-17 08:36 UTC, sarthakkasat commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java
> +    instrumentationHelper.sendApprovalEvent(approvalInstance);
We are calling the CompletableFuture.runAsync() method inside the Instrumentation helper method to make the call async as it is the only expensive call.

2023-11-20 05:07 UTC, hextechpal requested changes
> Reviewed 4 of 8 files at r1, 5 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55476)* status: 11 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/55476#gh-1395536144:-Njf5whl0do06r0JbnzN:bqzi3jx) ([raw file](https://github.com/harness/harness-core/blob/bb1b22fe0a39b3e020f0c6b1f040dc18a0a5996f/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java#L72)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

We are calling the CompletableFuture.runAsync() method inside the Instrumentation helper method to make the call async as it is the only expensive call.
</blockquote></details>

The point here is what if this sendApprovalEvent method throws an exception, isn't it better to wrap this into a future here

submit(() -> helper.sendApprovalEvent(instance))
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java` line 11 at r4](https://reviewable.io/reviews/harness/harness-core/55476#-Njf53bj-1sM3PEU3P8-:-Njf53bj-1sM3PEU3P80:b-37m6n8) ([raw file](https://github.com/harness/harness-core/blob/7c1a5f82ed1c9e84a6536949757795ed0a79275f/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java#L11)):*
> ```Java
> 
> import static io.harness.telemetry.helpers.InstrumentationConstants.ACCOUNT;
> import static io.harness.telemetry.helpers.InstrumentationConstants.APPROVAL_CRITERIA_SPEC_TYPE;
> ```

should these belong to 970 module?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/55476#-Njf5C6c9t7xLO4i4_Eg:-Njf5C6c9t7xLO4i4_Eh:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/7c1a5f82ed1c9e84a6536949757795ed0a79275f/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java#L18)):*
> ```Java
> import static io.harness.telemetry.helpers.InstrumentationConstants.PIPELINE_ID;
> import static io.harness.telemetry.helpers.InstrumentationConstants.PROJECT;
> import static io.harness.telemetry.helpers.InstrumentationConstants.REJECTION_CRITERIA_SPEC_TYPE;
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-11-20 06:08 UTC, puthrayaharness submitted a review, later dismissed

2023-11-20 08:23 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55476)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/55476#gh-1395536144:-Njfo_rW2KUwX0Ty4Dg0:brei5sx) ([raw file](https://github.com/harness/harness-core/blob/bb1b22fe0a39b3e020f0c6b1f040dc18a0a5996f/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/ServiceNowApprovalStep.java#L72)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

The point here is what if this sendApprovalEvent method throws an exception, isn't it better to wrap this into a future here

submit(() -> helper.sendApprovalEvent(instance))
</blockquote></details>

If the method throws any exception we are catching it and logging that error.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java` line 11 at r4](https://reviewable.io/reviews/harness/harness-core/55476#-Njf53bj-1sM3PEU3P8-:-NjfokQgBvdx8fvrgK5f:b-n4dckj) ([raw file](https://github.com/harness/harness-core/blob/7c1a5f82ed1c9e84a6536949757795ed0a79275f/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java#L11)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

should these belong to 970 module?
</blockquote></details>

I have moved it to 970-telemetry-beans module.


<!-- Sent from Reviewable.io -->

2023-11-20 11:52 UTC, sarthakkasat commented
trigger uts

2023-11-20 12:04 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55476)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java` line 18 at r4](https://reviewable.io/reviews/harness/harness-core/55476#-Njf5C6c9t7xLO4i4_Eg:-Njgba2H8ugyPgcd35Xs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c1a5f82ed1c9e84a6536949757795ed0a79275f/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers/ApprovalInstrumentationHelper.java#L18)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-20 16:36 UTC, sarthakkasat commented
trigger uts

2023-11-21 04:40 UTC, sarthakkasat commented
trigger uts

2023-11-21 04:42 UTC, hextechpal approved these changes
> Reviewed 6 of 6 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55476)* status: 14 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-21 04:44 UTC, puthrayaharness approved these changes

2023-11-21 05:03 UTC, sarthakkasat commented
trigger review

2023-11-22 06:14 UTC, merged