[fix]: [CCM-15136]: Handled NPE while checking cyclic dependency
harness/harness-core pull request #55594
Opened 2023-11-18 10:21 UTC by sdsingh07

## Describe your changes
Handled NPE while checking cyclic dependency if someone passed incorrect business mapping id.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-18 13:20 UTC, sdsingh07 commented
trigger messagecheck

2023-11-18 17:00 UTC, nikunj-badjatya requested changes

2023-11-18 17:00 UTC, nikunj-badjatya commented on 450-ce-views/src/main/java/io/harness/ccm/views/businessmapping/service/impl/BusinessMappingValidationServiceImpl.java
> +      if (Objects.isNull(businessMapping)) {
Can we do this check at the beginning itself ? get a list of all ids and check if anyone of them is non existing. That will be a single call ?

2023-11-18 20:40 UTC, sdsingh07 commented on 450-ce-views/src/main/java/io/harness/ccm/views/businessmapping/service/impl/BusinessMappingValidationServiceImpl.java
> +      if (Objects.isNull(businessMapping)) {
Yes, we can address this at the beginning. Presently, there are numerous instances where we use GET calls instead of LIST call, and these can be consolidated at the beginning. Additionally, there are other validations in place where we aren't currently invoking the DAO. We need to assess and validate them before incorporating the DAO layer to minimize the database load. For now, resolving this conversation and will create an enhancement ticket for it. Will need to check if it's applicable to perspective's GET calls in some scenarios.

2023-11-20 04:46 UTC, sdsingh07 commented on 450-ce-views/src/main/java/io/harness/ccm/views/businessmapping/service/impl/BusinessMappingValidationServiceImpl.java
> +      if (Objects.isNull(businessMapping)) {
https://harness.atlassian.net/browse/CCM-15139

2023-11-20 06:00 UTC, svmav approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55594)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-20 10:02 UTC, svmav approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55594#-:-NjgAVrt9KgMmNaVTFCD:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-20 18:13 UTC, nikunj-badjatya commented
trigger uts

2023-11-21 02:57 UTC, merged