feat: [CDS-83725]: Added new API URLS for connector config in New relic with back-support for insights.
harness/harness-core pull request #55607
Opened 2023-11-20 04:32 UTC by ShubhenduP

## Describe your changes
Added connector urls for new NewRelic apis, with back-support for insights. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-21 08:06 UTC, ShubhenduP commented
trigger uts

2023-11-22 06:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/delegate/beans/cvng/newrelic/NewRelicUtils.java
> +  private static final String INSIGHTS_DSL_FILENAME = "newrelic-applications.datacollection";
What is the difference between `NEW_API_DSL_FILENAME` and `INSIGHTS_DSL_FILENAME`

2023-11-22 06:33 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/delegate/beans/cvng/newrelic/NewRelicUtils.java
> +    return NEW_API_DSL_FILENAME;
Can you please check this? both return the same

2023-11-22 06:36 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/NewRelicServiceImpl.java
> +  private static final List<String> NEW_RELIC_ENDPOINTS = Arrays.asList("https://insights-api.newrelic.com/",
Can you also add Junits

2023-11-22 06:37 UTC, sribalij requested changes
Can you pls also list down the tests that were performed in the description. ?

2023-11-22 12:09 UTC, AbhijithHarness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/NewRelicServiceImpl.java
> +  private static final List<String> NEW_RELIC_ENDPOINTS = Arrays.asList("https://insights-api.newrelic.com/",
Please keep these inside A Feature flag, as we should allow these new URLs, only after we have complete feature ready

2023-11-28 07:18 UTC, closed without merging