feat: [IDP-1623]: Compute scores asynchronously
harness/harness-core pull request #55613
Opened 2023-11-20 05:56 UTC by vikyathharekal

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-20 14:52 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java
> +//@NextGenManagerAuth
Test code. Please re-enable

2023-11-20 15:07 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/entity/AsyncScoreComputationEntity.java
> +public class AsyncScoreComputationEntity implements PersistentEntity, CreatedByAware, CreatedAtAware {
Ok. We have an issue here. For a given account_entity_scorecard, let's say I trigger recalibrate for the first time for this unique combination and createdBy will be me.
Now, let's say you trigger it for the same combination. createdBy will not get updated and it will still be me. That's how this "@CreatedBy", "CreatedByAware" stuff works.

What we can do here is - 
Remove this createdBy stuff and have a similar EmbeddedUser object triggeredBy and this will populated with UserPrincipal in case of user action and ServicePrincipal in case of system action.

2023-11-20 15:14 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/AsyncScoreComputationRepositoryCustomImpl.java
> +  private AsyncScoreComputationEntity findByAccountIdAndIdentifier(AsyncScoreComputationEntity entity) {
This can be CrudRepository query itself -
`AsyncScoreComputationEntity findByAccountIdentifierAndEntityIdentifierAndScorecardIdentifier(String accountIdentifier, String entityIdentifier, String scorecardIdentifier)`

2023-11-20 15:16 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java
> +      @Valid ScorecardRecalibrateRequest scorecardRecalibrateRequest, String harnessAccount) {
Not related to this PR. But always annotate harnessAccount with `@AccountIdentifier` annotation.
Same is applicable for org, project, resource if used (`@OrgIdentifier, @ProjectIdentifier, @ResourceIdentifier`)

2023-11-20 15:19 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreComputerServiceImpl.java
> +    boolean asyncScoreComputationEnabled = CGRestUtils.getResponse(
nit: As same logic is there is two places, we can move it to common place.
IdpCommonService already has AccountClient injected. May be create a common method there ?

2023-11-20 15:24 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/service/AsyncScoreComputationServiceImpl.java
> +    scoreComputerService.computeScores(accountIdentifier,
If any unhandled exception happens here (computeScores), then deleteScoreComputationRequest doesn't gets invoked.
We should handle it.

2023-11-20 16:03 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/entity/AsyncScoreComputationEntity.java
> +public class AsyncScoreComputationEntity implements PersistentEntity, CreatedByAware, CreatedAtAware {
Actually, we delete the DB record as soon as we process the event. So when I trigger the re-run in the above scenario, mongo will be creating a new record right?

2023-11-20 16:04 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/entity/AsyncScoreComputationEntity.java
> +public class AsyncScoreComputationEntity implements PersistentEntity, CreatedByAware, CreatedAtAware {
We might not need saveOrUpdate(). It will always be a new insert

2023-11-20 16:05 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreComputerServiceImpl.java
> +    boolean asyncScoreComputationEnabled = CGRestUtils.getResponse(
Yeah didn't add it as we would eventually globally enable the FF and remove this piece of code (get the FF value and if condition)

2023-11-20 16:06 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/service/AsyncScoreComputationServiceImpl.java
> +    scoreComputerService.computeScores(accountIdentifier,
Done

2023-11-20 16:06 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java
> +      @Valid ScorecardRecalibrateRequest scorecardRecalibrateRequest, String harnessAccount) {
Done

2023-11-20 16:06 UTC, vikyathharekal commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java
> +//@NextGenManagerAuth
Done

2023-11-20 16:08 UTC, sathish-soundarapandian commented on idp-service/src/main/java/io/harness/idp/scorecard/scores/entity/AsyncScoreComputationEntity.java
> +public class AsyncScoreComputationEntity implements PersistentEntity, CreatedByAware, CreatedAtAware {
Ok. We delete it after processing. And if there is a request for same combination when the processing is happening, then we just return the existing row.
Then it is fine.

2023-11-20 16:11 UTC, sathish-soundarapandian submitted a review, later dismissed

2023-11-20 16:44 UTC, sathish-soundarapandian approved these changes

2023-11-20 16:50 UTC, sathish-soundarapandian commented on idp-service/contracts/openapi/v1/openapi.yaml
> +  /v2/scores/recalibrate:
Ingress changes will be needed ?

2023-11-20 17:03 UTC, vigneswara-propelo requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55613)* status: 20 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 1334 at r3](https://reviewable.io/reviews/harness/harness-core/55613#-NjhfHpAB-jAOIwH2zD0:-NjhfHpAB-jAOIwH2zD1:bu4g99g) ([raw file](https://github.com/harness/harness-core/blob/30ace3b8983bebc25a2b266cbbeb05087e46470d/idp-service/contracts/openapi/v1/openapi.yaml#L1334)):*
> ```YAML
>       description: API for triggering score recalibration for a scorecard
>       tags:
>         - Scores
> ```

V2 APIs need a new tag "ScoresV2". Otherwise the old API will not work due to conflicts. 



_Code quote:_
```YAML
Scores
```


<!-- Sent from Reviewable.io -->

2023-11-20 17:36 UTC, vikyathharekal commented on idp-service/contracts/openapi/v1/openapi.yaml
> +  /v2/scores/recalibrate:
https://github.com/wings-software/ng-prod-manifests/pull/5076
https://github.com/wings-software/ng-prod-manifests/pull/5077

2023-11-20 17:37 UTC, vikyathharekal reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55613)* status: 22 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 1334 at r3](https://reviewable.io/reviews/harness/harness-core/55613#-NjhfHpAB-jAOIwH2zD0:-NjhnaEx5u1u8JCSiCrT:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/30ace3b8983bebc25a2b266cbbeb05087e46470d/idp-service/contracts/openapi/v1/openapi.yaml#L1334)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

V2 APIs need a new tag "ScoresV2". Otherwise the old API will not work due to conflicts.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-11-20 17:37 UTC, vigneswara-propelo approved these changes

2023-11-20 18:19 UTC, sathish-soundarapandian approved these changes

2023-11-21 03:53 UTC, vikyathharekal commented
trigger uts

2023-11-21 05:12 UTC, mankrit-singh commented on idp-service/contracts/openapi/v1/openapi.yaml
> +        startTime:
can these be snake case as well?

2023-11-21 05:45 UTC, vikyathharekal commented
trigger uts

2023-11-21 05:47 UTC, sathish-soundarapandian submitted a review, later dismissed

2023-11-21 05:49 UTC, mankrit-singh approved these changes

2023-11-21 05:50 UTC, sathish-soundarapandian approved these changes

2023-11-21 05:51 UTC, vikyathharekal commented
trigger uts

2023-11-21 08:45 UTC, vikyathharekal commented
trigger ut5, ut6, ut7, ut8, ut9

2023-11-21 09:32 UTC, vikyathharekal commented
trigger uts

2023-11-21 11:29 UTC, sandeepa-kv-jois commented
Unrelated test failures, going ahead with FM. Locally tests have passed.

2023-11-21 11:29 UTC, merged