fix: [CDS-83756]: Instrumentation helper code for tracking deployments
harness/harness-core pull request #55610
Opened 2023-11-20 05:08 UTC by vivekkarnatiharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-21 09:48 UTC, sarthakkasat requested changes

2023-11-21 09:48 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactDeploymentInstrumentationHelper.java
Can we use the ArtifactSourceInstrumentationHelper class to publish the event?

2023-11-21 09:48 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactDeploymentInstrumentationHelper.java
> +  private CompletableFuture<Void> sendEvent(
Can we not duplicate this method?

2023-11-21 09:48 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +        artifactDeploymentInstrumentationHelper.sendArtifactDeploymentEvent(artifacts.getPrimary().getSpec(),
Can we call the sendArtifactDeploymentEvent method after the else if block?

2023-11-21 09:48 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +              AmbianceUtils.getProjectIdentifier(ambiance), service.getServiceDefinition().getType().name(), true);
Same as above

2023-11-21 10:55 UTC, vivekkarnatiharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactDeploymentInstrumentationHelper.java
Ok, have squashed my changes to this file

2023-11-21 10:55 UTC, vivekkarnatiharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactDeploymentInstrumentationHelper.java
> +  private CompletableFuture<Void> sendEvent(
Done, removed

2023-11-21 10:55 UTC, vivekkarnatiharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java
> +        artifactDeploymentInstrumentationHelper.sendArtifactDeploymentEvent(artifacts.getPrimary().getSpec(),
Ok, moved it!

2023-11-21 13:26 UTC, vivekkarnatiharness commented
trigger uts

2023-11-22 09:09 UTC, vivekkarnatiharness commented
trigger uts

2023-11-22 09:19 UTC, sarthakkasat submitted a review, later dismissed

2023-11-22 11:41 UTC, abhinavmittal-harness requested changes
> Reviewed 4 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55610)* status: 10 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/55610#-NjqpFTf51_mBaKiXyW6:-NjqpFTf51_mBaKiXyW7:b-pc0tde) ([raw file](https://github.com/harness/harness-core/blob/a661251f4591abd2b84d4e4ae9f099da59073816/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java#L55)):*
> ```Java
>     eventPropertiesMap.put(ARTIFACT_ORG, orgId);
>     eventPropertiesMap.put(ARTIFACT_TYPE, artifactConfig.getSourceType());
>     eventPropertiesMap.put(ARTIFACT_IDENTIFIER, artifactConfig.getIdentifier());
> ```

can we add a ut for checking if all the properties are being added


<!-- Sent from Reviewable.io -->

2023-11-23 09:23 UTC, vivekkarnatiharness commented
trigger uts

2023-11-23 11:24 UTC, abhinavmittal-harness approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55610)* status: 10 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-23 11:25 UTC, sarthakkasat approved these changes

2023-11-23 11:44 UTC, vivekkarnatiharness commented
trigger review

2023-11-23 11:47 UTC, vivekkarnatiharness commented
trigger messagecheck

2023-11-23 11:57 UTC, merged