feat: [PL-32066]: Make sorting case insentive for projects
harness/harness-core pull request #55645
Opened 2023-11-20 12:13 UTC by sahibaHarness

## Describe your changes

Make sorting case insensitive for listing projects.

<img width="1178" alt="image" src="https://github.com/harness/harness-core/assets/112424209/c9ec85c7-d212-40fb-a717-317444db597c">

Tested for:
Tested list API for project
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-20 12:16 UTC, VikasMaddukuriHarness approved these changes

2023-11-20 12:20 UTC, sahibaHarness commented
trigger messagecheck

2023-11-20 13:46 UTC, pbarapatre10 commented on 950-ng-project-n-orgs/src/main/java/io/harness/repositories/core/custom/ProjectRepositoryCustomImpl.java
> +    query.collation(Collation.of("en").strength(Collation.ComparisonLevel.secondary()));
In projects collection we have compound index on identifier and other with collation level set to primary, whereas here we are using ComparisonLevel secondary, which I believe may not be able to use the index. 
Bhavya, Ankit can you please confirm, I'm not an expert in this, thanks

2023-11-20 13:51 UTC, pbarapatre10 commented on 950-ng-project-n-orgs/src/main/java/io/harness/repositories/core/custom/ProjectRepositoryCustomImpl.java
> +    query.collation(Collation.of("en").strength(Collation.ComparisonLevel.secondary()));
@bhavya181 @ankit-harness please review from your end as well ^, thanks

2023-11-20 14:54 UTC, bhavya181 requested changes

2023-11-20 14:54 UTC, bhavya181 commented on 950-ng-project-n-orgs/src/main/java/io/harness/repositories/core/custom/ProjectRepositoryCustomImpl.java
> +    query.collation(Collation.of("en").strength(Collation.ComparisonLevel.secondary()));
1. I think we should add collation in page list query only, not on repository layer, findAll mathod is used by various different service methods which has different different queries and those queries will stop using indexes once we add collation here.
2. if index is having different strength, it will not get used by query, you have to create new index for that query with same strength. check this for example https://www.mongodb.com/docs/manual/core/index-case-insensitive/#:~:text=//%20does%20not%20use%20the%20index%2C%20finds%20three%20results

2023-11-21 10:13 UTC, sahibaHarness commented
checked with anurag we are not utilising this index, changing the collation
![image](https://github.com/harness/harness-core/assets/112424209/132b1837-af12-4e1c-aee9-0e57e719efd3)

2023-11-21 11:45 UTC, sahibaHarness commented
@bhavya181 since we have introduced a new function for collation it would not impact the results as the criteria  that pass in with collation is already list of filtered IDs.
So essentially collation is done on the list of result it self

2023-11-21 11:45 UTC, sahibaHarness commented
trigger uts

2023-11-21 11:46 UTC, adiyaar24 approved these changes

2023-11-21 12:41 UTC, sahibaHarness commented
trigger ut6,ut7,ut8,ut9

2023-11-21 13:04 UTC, bhavya181 approved these changes

2023-11-21 13:28 UTC, tiwaritejas approved these changes

2023-11-21 14:52 UTC, merged