fix: [PL-42825]: make sorting users on email and name case insensitive
harness/harness-core pull request #55676
Opened 2023-11-20 19:58 UTC by sahibaHarness

## Describe your changes
<img width="1024" alt="image" src="https://github.com/harness/harness-core/assets/112424209/ee751ad5-5234-4f56-97d0-d8c24b1be54e">

Index Utilization
<img width="1138" alt="image" src="https://github.com/harness/harness-core/assets/112424209/e68ff9a7-d9ea-4872-88fb-43edbb85ec5b">

Tested for:
-> Tested for sorting orders supported on UI
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-20 20:09 UTC, sahibaHarness commented
trigger messagecheck

2023-11-20 20:09 UTC, sahibaHarness commented
trigger uts

2023-11-20 20:55 UTC, sahibaHarness commented
trigger uts

2023-11-21 05:13 UTC, tiwaritejas requested changes

2023-11-21 05:13 UTC, tiwaritejas commented on 120-ng-manager/src/main/java/io/harness/repositories/invites/custom/InviteRepositoryCustomImpl.java
> +    query.collation(Collation.of("en").strength(Collation.ComparisonLevel.secondary()));
@sahibaHarness Can you check how does this affect the index usage? There have been incidents in the past where making a query insensitive led to poor index usage, thereby slowing down the query and increase mongo CPU load.

2023-11-21 05:41 UTC, sahibaHarness commented on 120-ng-manager/src/main/java/io/harness/repositories/invites/custom/InviteRepositoryCustomImpl.java
> +    query.collation(Collation.of("en").strength(Collation.ComparisonLevel.secondary()));
<img width="697" alt="image" src="https://github.com/harness/harness-core/assets/112424209/0a78aae0-a24d-465a-bf8d-0907b16dfb58">
I had a discussion on these indexes with @anurag as well on the indexes


`{
    "queryPlanner" : {
        "plannerVersion" : 1.0,
        "namespace" : "ng-harness.invites",
        "indexFilterSet" : false,
        "parsedQuery" : {
            "$and" : [
                {
                    "accountIdentifier" : {
                        "$eq" : "kmpySmUISimoRrJL6NL73w"
                    }
                },
                {
                    "deleted" : {
                        "$eq" : false
                    }
                },
                {
                    "orgIdentifier" : {
                        "$eq" : null
                    }
                },
                {
                    "projectIdentifier" : {
                        "$eq" : null
                    }
                }
            ]
        },
        "collation" : {
            "locale" : "en",
            "caseLevel" : false,
            "caseFirst" : "off",
            "strength" : 2.0,
            "numericOrdering" : false,
            "alternate" : "non-ignorable",
            "maxVariable" : "punct",
            "normalization" : false,
            "backwards" : false,
            "version" : "57.1"
        },
        "winningPlan" : {
            "stage" : "FETCH",
            "filter" : {
                "$and" : [
                    {
                        "orgIdentifier" : {
                            "$eq" : null
                        }
                    },
                    {
                        "projectIdentifier" : {
                            "$eq" : null
                        }
                    }
                ]
            },
            "inputStage" : {
                "stage" : "IXSCAN",
                "keyPattern" : {
                    "deleted" : 1.0,
                    "name" : 1.0,
                    "accountIdentifier" : 1.0,
                    "orgIdentifier" : 1.0,
                    "projectIdentifier" : 1.0,
                    "roleBindings" : 1.0
                },
                "indexName" : "ng_invite_deleted_name_account_org_project_roleBindings_with_collation",
                "collation" : {
                    "locale" : "en",
                    "caseLevel" : false,
                    "caseFirst" : "off",
                    "strength" : 2.0,
                    "numericOrdering" : false,
                    "alternate" : "non-ignorable",
                    "maxVariable" : "punct",
                    "normalization" : false,
                    "backwards" : false,
                    "version" : "57.1"
                },
                "isMultiKey" : true,
                "multiKeyPaths" : {
                    "deleted" : [

                    ],
                    "name" : [

                    ],
                    "accountIdentifier" : [

                    ],
                    "orgIdentifier" : [

                    ],
                    "projectIdentifier" : [

                    ],
                    "roleBindings" : [
                        "roleBindings"
                    ]
                },
                "isUnique" : false,
                "isSparse" : false,
                "isPartial" : false,
                "indexVersion" : 2.0,
                "direction" : "backward",
                "indexBounds" : {
                    "deleted" : [
                        "[false, false]"
                    ],
                    "name" : [
                        "[MaxKey, MinKey]"
                    ],
                    "accountIdentifier" : [
                        "[\"=AGYMAQ9M9AEKK;?\\x1EC? \\x18U\\x01\\x1A\", \"=AGYMAQ9M9AEKK;?\\x1EC? \\x18U\\x01\\x1A\"]"
                    ],
                    "orgIdentifier" : [
                        "[null, null]",
                        "[undefined, undefined]"
                    ],
                    "projectIdentifier" : [
                        "[null, null]",
                        "[undefined, undefined]"
                    ],
                    "roleBindings" : [
                        "[MaxKey, MinKey]"
                    ]
                }
            }
        },
        "rejectedPlans" : [
            {
                "stage" : "SORT",
                "sortPattern" : {
                    "name" : -1.0
                },
                "inputStage" : {
                    "stage" : "SORT_KEY_GENERATOR",
                    "inputStage" : {
                        "stage" : "FETCH",
                        "filter" : {
                            "$and" : [
                                {
                                    "orgIdentifier" : {
                                        "$eq" : null
                                    }
                                },
                                {
                                    "projectIdentifier" : {
                                        "$eq" : null
                                    }
                                },
                                {
                                    "accountIdentifier" : {
                                        "$eq" : "kmpySmUISimoRrJL6NL73w"
                                    }
                                }
                            ]
                        },
                        "inputStage" : {
                            "stage" : "IXSCAN",
                            "keyPattern" : {
                                "deleted" : 1.0,
                                "email" : 1.0,
                                "accountIdentifier" : 1.0,
                                "orgIdentifier" : 1.0,
                                "projectIdentifier" : 1.0
                            },
                            "indexName" : "ng_invite_account_org_project_identifiers_email_role_deleted",
                            "isMultiKey" : false,
                            "multiKeyPaths" : {
                                "deleted" : [

                                ],
                                "email" : [

                                ],
                                "accountIdentifier" : [

                                ],
                                "orgIdentifier" : [

                                ],
                                "projectIdentifier" : [

                                ]
                            },
                            "isUnique" : false,
                            "isSparse" : false,
                            "isPartial" : false,
                            "indexVersion" : 2.0,
                            "direction" : "forward",
                            "indexBounds" : {
                                "deleted" : [
                                    "[false, false]"
                                ],
                                "email" : [
                                    "[MinKey, MaxKey]"
                                ],
                                "accountIdentifier" : [
                                    "[MinKey, MaxKey]"
                                ],
                                "orgIdentifier" : [
                                    "[undefined, undefined]",
                                    "[null, null]"
                                ],
                                "projectIdentifier" : [
                                    "[undefined, undefined]",
                                    "[null, null]"
                                ]
                            }
                        }
                    }
                }
            },
            {
                "stage" : "SORT",
                "sortPattern" : {
                    "name" : -1.0
                },
                "inputStage" : {
                    "stage" : "SORT_KEY_GENERA [...]

2023-11-21 05:59 UTC, adiyaar24 approved these changes

2023-11-21 07:02 UTC, tiwaritejas approved these changes

2023-11-21 07:13 UTC, bhavya181 approved these changes

2023-11-21 09:43 UTC, merged