fix: [PL-39652]: fix NPE in validateToken in authentication service
harness/harness-core pull request #55722
Opened 2023-11-21 09:11 UTC by bhavya181

## Describe your changes
fix NPE in validateToken in authentication service

tested with UT

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-21 09:21 UTC, nishantsaini20 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55722)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/55722#-NjlAjavBNrmUQ4bzP8T:-NjlAjaw1loqHQ49WLVy:b-5d9kw5) ([raw file](https://github.com/harness/harness-core/blob/3ac1577c4574258bb2c0074080ce3d80f8bb1476/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L208)):*
> ```Java
>   public AuthToken validateToken(String tokenString) {
>     if (isEmpty(tokenString)) {
>       throw new WingsException(INVALID_TOKEN, USER);
> ```

This should be a specific type of exception, may be InvalidRequestException.


<!-- Sent from Reviewable.io -->

2023-11-21 09:43 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java
>      if (tokenString.length() <= 32) {
We should perhaps just check `if (isNotEmpty(tokenString) && tokenString.length() <= 32)` 
and avoid throwing any exception, as it may break flows on caller's end, thanks

2023-11-21 09:45 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java
> +    }
This won't be needed once above comment is handled, thanks

2023-11-21 09:48 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java
> +    }
This should not be needed once above is hndled, thanks

2023-11-21 09:49 UTC, pbarapatre10 commented on 400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java
>      if (tokenString.length() <= 32) {
or we can just return null

2023-11-21 11:08 UTC, bhavya181 commented on 400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java
> +    }
done

2023-11-21 11:08 UTC, bhavya181 commented on 400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java
>      if (tokenString.length() <= 32) {
done

2023-11-21 11:12 UTC, pbarapatre10 approved these changes

2023-11-21 11:13 UTC, bhavya181 commented
trigger uts

2023-11-21 12:46 UTC, bhavya181 commented
trigger ut8, ut9

2023-11-21 14:11 UTC, bhavya181 commented
trigger ut8, ut9

2023-11-21 15:49 UTC, sahibaHarness approved these changes

2023-11-22 06:06 UTC, bhavya181 commented
trigger messagecheck

2023-11-22 06:07 UTC, bhavya181 commented
trigger messagecheck

2023-11-22 06:13 UTC, bhavya181 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55722)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/55722#-NjlAjavBNrmUQ4bzP8T:-NjpeLzA7WypOQpM2pkE:b4tewwj) ([raw file](https://github.com/harness/harness-core/blob/3ac1577c4574258bb2c0074080ce3d80f8bb1476/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L208)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This should be a specific type of exception, may be InvalidRequestException.
</blockquote></details>

we will not throw exception as it may break any existing flow


<!-- Sent from Reviewable.io -->

2023-11-22 06:14 UTC, nishantsaini20 approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55722)* status: 3 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-22 06:47 UTC, niketan-nath approved these changes
LGTM

2023-11-22 06:53 UTC, merged