feat:[CI-8922]: secure tunnel
harness/harness-core pull request #55748
Opened 2023-11-21 13:28 UTC by HenAmar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-23 08:37 UTC, raghavharness commented
trigger uts

2023-11-23 08:49 UTC, raghavharness commented
trigger commonchecks, codeformat, checkstyle, pmd, codebasehash

2023-11-23 09:15 UTC, raghavharness commented
trigger uts

2023-11-23 09:33 UTC, raghavharness commented
trigger uts

2023-11-23 09:49 UTC, raghavharness commented
trigger uts

2023-11-24 13:17 UTC, harshjain12 commented on 120-ng-manager/src/main/java/io/harness/ng/tunnel/entities/Tunnel.java
> +        .add(CompoundMongoIndex.builder()
It is just accountId, Why are we making it compound indes ?

2023-11-24 13:22 UTC, harshjain12 requested changes

2023-11-24 13:22 UTC, harshjain12 commented on 120-ng-manager/src/main/java/io/harness/ng/tunnel/resources/TunnelResource.java
> +  registerTunnel(@Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @QueryParam(
Can we check ACL annotations need to be pull.
Seems to be missing

2023-11-24 13:22 UTC, harshjain12 commented on 980-commons/src/main/java/io/harness/network/Http.java
> +          .expireAfterWrite(1, TimeUnit.MINUTES)
Do we need it every 1 min ?

2023-11-24 15:36 UTC, raghavharness commented on 120-ng-manager/src/main/java/io/harness/ng/tunnel/entities/Tunnel.java
> +        .add(CompoundMongoIndex.builder()
We want to add an index on accountId but there's no other type of index we see in code. Is there any index type which we can use here for a single field ?

2023-11-24 15:37 UTC, raghavharness commented on 120-ng-manager/src/main/java/io/harness/ng/tunnel/resources/TunnelResource.java
> +public class TunnelResource {
I saw in ng manager we are writing all the resource class like this only that's why didn't use different way. Do you think we should add it ?

2023-11-24 15:38 UTC, raghavharness commented on 120-ng-manager/src/main/java/io/harness/ng/tunnel/resources/TunnelResource.java
> +  registerTunnel(@Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @QueryParam(
Have added `@NextGenManagerAuth` on top of the class.

2023-11-24 15:39 UTC, raghavharness commented on 980-commons/src/main/java/io/harness/network/Http.java
> +                connection.setReadTimeout(15000);
yes its in ms. BTW we are not using any custom logic of ours. We just created a copy of `responseCodeForValidation` which is already used but we created one which supports proxy.

2023-11-24 15:40 UTC, raghavharness commented on 980-commons/src/main/java/io/harness/network/Http.java
> +              log.info("Testing connectivity");
Ditto, kept it same.

2023-11-24 15:40 UTC, raghavharness commented on 980-commons/src/main/java/io/harness/network/Http.java
> +          .expireAfterWrite(1, TimeUnit.MINUTES)
Ditto, kept it same.

2023-11-24 16:48 UTC, raghavharness commented
trigger uts

2023-11-24 16:50 UTC, raghavharness commented
trigger uts

2023-11-24 16:52 UTC, raghavharness commented
trigger codeformat, checkstyle, pmd, codebasehash

2023-11-25 07:29 UTC, raghavharness commented
trigger uts

2023-11-27 06:32 UTC, harshjain12 approved these changes

2023-11-27 06:34 UTC, harshjain12 commented on 120-ng-manager/src/main/java/io/harness/ng/tunnel/entities/Tunnel.java
> +        .add(CompoundMongoIndex.builder()
@FdIndex private String accountId;

2023-11-27 07:59 UTC, raghavharness commented on 120-ng-manager/src/main/java/io/harness/ng/tunnel/entities/Tunnel.java
> +        .add(CompoundMongoIndex.builder()
fixed

2023-11-27 08:18 UTC, raghavharness commented
trigger uts

2023-11-27 09:14 UTC, adivishy1 approved these changes
> Reviewed 6 of 45 files at r1, 8 of 16 files at r4, 11 of 23 files at r6, 1 of 3 files at r7, 15 of 15 files at r8, 4 of 5 files at r9, 27 of 27 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55748)* status: 6. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-27 11:44 UTC, raghavharness commented
trigger ut5, ut7

2023-11-27 13:52 UTC, raghavharness commented
trigger ut7

2023-11-28 09:28 UTC, harshjain12 approved these changes

2023-11-28 09:36 UTC, merged