[feat]: [CDS-83701]: Add telemetry for multi service and environment deployments
harness/harness-core pull request #55755
Opened 2023-11-21 15:59 UTC by lovish1999

## Describe your changes
Add telemetry for multi service and multi environment deployments

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-22 06:42 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java
> +    try {
Can we call the sendEventMethod in Instrumentation Helper class?

2023-11-22 07:27 UTC, tchaurasiya commented
As discussed offline, lets add environment filter, envGroup, useFromStage, isMultiService, isMultiEnv info also.
Can be done in this or next pr.

2023-11-22 07:57 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java
> +    try {
done

2023-11-22 07:59 UTC, lovish1999 commented
trigger uts

2023-11-23 06:52 UTC, lovish1999 commented
trigger ut9

2023-11-23 06:55 UTC, sarthakkasat submitted a review, later dismissed

2023-11-23 10:08 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +              .stageIdentifier(StrategyUtils.refineIdentifier(stageNode.getIdentifier()))
What is this for?

2023-11-23 10:08 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +                  EnvironmentInfraFilterUtils.areFiltersPresent(deploymentStageConfig.getEnvironments()))
If filters are present in environmentGroup, are we handlung that?

2023-11-23 10:08 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/telemetry/entity/MultiSvcEnvTelemetryInfo.java
> +@Data
nit: if this class is getting set only once, better to have Value annotation, to make it immutable.

2023-11-24 10:59 UTC, lovish1999 commented
trigger uts

2023-11-24 11:08 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/telemetry/entity/MultiSvcEnvTelemetryInfo.java
> +@Data
done

2023-11-24 11:08 UTC, lovish1999 commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +                  EnvironmentInfraFilterUtils.areFiltersPresent(deploymentStageConfig.getEnvironments()))
added

2023-11-24 13:02 UTC, sarthakkasat approved these changes

2023-11-24 17:26 UTC, tchaurasiya submitted a review, later dismissed

2023-11-24 17:41 UTC, lovish1999 commented
trigger review

2023-11-24 17:42 UTC, lovish1999 commented
trigger messagecheck

2023-11-24 17:42 UTC, lovish1999 commented
trigger review

2023-11-24 17:42 UTC, lovish1999 commented
trigger messagecheck

2023-11-24 18:26 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 940 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1_JP_4YoLn2k2EJUx:-Nk1_JP_4YoLn2k2EJUy:b3t9w2a) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L940)):*
> ```Java
>   }
> 
>   protected void sendTelemetryEventForMultiSvcEnv(@NotNull PlanCreationContext ctx, DeploymentStageNode stageNode) {
> ```

are we even using stageNode directly here ? can we not pass DeploymentStageConfig ?



_Code quote:_
```Java
DeploymentStageNode stageNode
```


<!-- Sent from Reviewable.io -->

2023-11-24 18:57 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 1046 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1gKaK2d3H7qAZ0sob:-Nk1gKaK2d3H7qAZ0soc:bqn4czv) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L1046)):*
> ```Java
>       return infraStructureDefinitionYamls.size();
>     }
>     return 1;
> ```

we should write UT for this 


<!-- Sent from Reviewable.io -->

2023-11-24 18:57 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/telemetry/entity/MultiSvcEnvTelemetryInfo.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1gSN-B7nnI7dErnXm:-Nk1gPHBDQoLJTe-Rbnm:bk3kcnw) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/telemetry/entity/MultiSvcEnvTelemetryInfo.java#L23)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true,
>     components = {HarnessModuleComponent.CDS_SERVICE_ENVIRONMENT})
> @OwnedBy(CDP)
> ```

ownedBy -> CDC


<!-- Sent from Reviewable.io -->

2023-11-24 18:58 UTC, yogesh-chauhan requested changes
> Reviewed 2 of 5 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55755)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1ZeQ-AVBHNHy16fWq:-Nk1ZeQ-AVBHNHy16fWr:b-bluwmi) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L38)):*
> ```Java
>   private static final String MULTI_ENVIRONMENT_DEPLOYMENT = "multi_environment_deployment";
>   private static final String ENVIRONMENT_GROUP_PRESENT = "environment_group_present";
>   private static final String ENVIRONMENT_FILTERS_PRESENT = "environment_filters_present";
> ```

new line for readability
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1Zg7jEtu9oX5J0sGj:-Nk1Zg7jEtu9oX5J0sGk:b-bluwmi) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L39)):*
> ```Java
>   private static final String ENVIRONMENT_GROUP_PRESENT = "environment_group_present";
>   private static final String ENVIRONMENT_FILTERS_PRESENT = "environment_filters_present";
>   @Inject TelemetryReporter telemetryReporter;
> ```

new line for readability
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1Zj1oAWgIQXlw2jbs:-Nk1Zj1oAWgIQXlw2jbt:b-6mrin) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L39)):*
> ```Java
>   private static final String ENVIRONMENT_GROUP_PRESENT = "environment_group_present";
>   private static final String ENVIRONMENT_FILTERS_PRESENT = "environment_filters_present";
>   @Inject TelemetryReporter telemetryReporter;
> ```

should be private?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1Zo_H-pK-tesjvhJO:-Nk1Zo_H-pK-tesjvhJP:b-ded24m) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L41)):*
> ```Java
>   @Inject TelemetryReporter telemetryReporter;
>   public CompletableFuture<Void> sendMultiSvcEnvEvent(MultiSvcEnvTelemetryInfo multiSvcEnvTelemetryInfo) {
>     return publishMultiSvcEnvInfo(multiSvcEnvTelemetryInfo, "multi_svc_env");
> ```

extract out as a constant ?



_Suggestion:_
```Java
"multi_svc_env"
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 940 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1_4EK8cegWlpf5HEB:-Nk1_4EK8cegWlpf5HEC:bc9rhza) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L940)):*
> ```Java
>   }
> 
>   protected void sendTelemetryEventForMultiSvcEnv(@NotNull PlanCreationContext ctx, DeploymentStageNode stageNode) {
> ```

this should be private right ?
@NotNul on PlanCreationContext is redundant here
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 955 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1_jLrE37Y0s0ngTd7:-Nk1_jLrE37Y0s0ngTd8:bf4fofp) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L955)):*
> ```Java
>               .environmentCount(getEnvironmentsCountForMultiSvcEnvDeployment(deploymentStageConfig))
>               .infrastructureCount(getInfrastructuresCountForMultiSvcEnvDeployment(deploymentStageConfig))
>               .deploymentType(deploymentStageConfig.getDeploymentType().toString())
> ```

should we add information about gitOpsEnabled also ?


<!-- Sent from Reviewable.io -->

2023-11-27 05:53 UTC, puthrayaharness requested changes

2023-11-27 05:53 UTC, puthrayaharness commented on 970-telemetry-beans/src/main/java/io/harness/telemetry/helpers/InstrumentationConstants.java
> +  public static final String ACCOUNT_IDENTIFIER = "account_id";
What can we not use the existing constants? Why these?

2023-11-27 05:53 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +  protected void sendTelemetryEventForMultiSvcEnv(@NotNull PlanCreationContext ctx, DeploymentStageNode stageNode) {
Move all this logic to InstrumentationHelper instead of keeping it in this class.

2023-11-27 05:53 UTC, puthrayaharness commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
> +  protected void sendTelemetryEventForMultiSvcEnv(@NotNull PlanCreationContext ctx, DeploymentStageNode stageNode) {
Also, please go over the logic. We should not get NPEs from this code. If you are not sure, we can wrap it with a try/catch block.

2023-11-27 06:37 UTC, lovish1999 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55755)* status: 4 file(s) to review. 2 change requests. 9. unresolved discussions. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1ZeQ-AVBHNHy16fWq:-NkESeLpBHrqpXijdb9_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L38)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

new line for readability
</blockquote></details>

done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1Zj1oAWgIQXlw2jbs:-NkESYfM0tcbKlLrtq4I:bbo23aa) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L39)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be private?
</blockquote></details>

No, its used in plan creator method
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1Zg7jEtu9oX5J0sGj:-NkESdo-2_-b8YOL223y:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L39)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

new line for readability
</blockquote></details>

done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1Zo_H-pK-tesjvhJO:-NkESfWE-RkuUT4HWQtb:b-7lm34b) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/MultiSvcEnvInstrumentationHelper.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

extract out as a constant ?
</blockquote></details>

okay.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 956 at r2](https://reviewable.io/reviews/harness/harness-core/55755#gh-1403157992:-NkEUDVOCJ3CvTbPp-kO:b-t0isnj) ([raw file](https://github.com/harness/harness-core/blob/651cd64c042a0d4ea4572e6fe9d36ae42fac05de/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L956)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

to generate stage identifier in case of expressions
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 940 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1_JP_4YoLn2k2EJUx:-NkESt7s4FaklEcgnikx:b-fwzzyd) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L940)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we even using stageNode directly here ? can we not pass DeploymentStageConfig ?
</blockquote></details>

yes, stage node is required to get stage identifier. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 940 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1_4EK8cegWlpf5HEB:-NkETR123dJlfHXHMPS4:b-x53uz4) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L940)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this should be private right ?
@NotNul on PlanCreationContext is redundant here
</blockquote></details>

yes, changed. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 940 at r3](https://reviewable.io/reviews/harness/harness-core/55755#gh-1405644793:-NkETdCl7xX8ePVntKd8:b-lc00t4) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L940)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Also, please go over the logic. We should not get NPEs from this code. If you are not sure, we can wrap it with a try/catch block. 
</blockquote></details>

Yes, in this class, we are only creating the `MultiSvcEnvTelemetryInfo` entity. Send event is then handled by the code in InstrumentationHelper. Yes, the code is already in try/catch block. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 955 at r3](https://reviewable.io/reviews/harness/harness-core/55755#-Nk1_jLrE37Y0s0ngTd7:-NkEU1xWAUVvWaW3m8kZ:b-o0pjec) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L955)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we add information about gitOpsEnabled also ?
</blockquote></details>

That can be separately added iteratively if required. These changes are mainly to track multi-svc & env. information, 
___
*[`970-telemetry-beans/src/main/java/io/harness/telemetry/helpers/InstrumentationConstants.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/55755#gh-1405644195:-NkEUbLh5HroIbR6WABr:b2k83gd) ([raw file](https://github.com/harness/harness-core/blob/042039525f6c71cd7977769386486378098e2cd4/970-telemetry-beans/src/main/java/io/harness/telemetry/helpers/InstrumentationConstants.java#L24)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

What can we not use the existing constants? Why these?
</blockquote></details>

field_id is better. But yes, we can use the existing ones. Making the change. 


<!-- Sent from Reviewable.io -->

2023-11-27 06:53 UTC, lovish1999 commented
trigger uts

2023-11-27 07:02 UTC, yogesh-chauhan commented
We should write UTs as well 




<!-- Sent from Reviewable.io -->

2023-11-27 07:02 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55755)* status: 4 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-27 07:02 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55755)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-27 08:16 UTC, lovish1999 commented
trigger ut5

2023-11-27 08:16 UTC, lovish1999 commented
trigger ut7

2023-11-27 08:16 UTC, lovish1999 commented
trigger ut8

2023-11-27 08:16 UTC, lovish1999 commented
trigger ut9

2023-11-27 08:17 UTC, tchaurasiya approved these changes

2023-11-27 09:38 UTC, lovish1999 commented
trigger review

2023-11-27 09:40 UTC, merged