fix: [SRM-16172]: Add ms-reconciliation-status API
harness/harness-core pull request #55762
Opened 2023-11-21 18:36 UTC by naveen-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-22 18:21 UTC, naveen-harness commented
trigger uts

2023-11-23 03:02 UTC, deepak-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55762)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/MSReconciliationStatus.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/55762#-Nju6rGn3Fl62tG6U2D2:-Nju6rGn3Fl62tG6U2D3:bojr0a3) ([raw file](https://github.com/harness/harness-core/blob/f2fca8b1f69c85ff87ff70e550d67b4e47266302/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/MSReconciliationStatus.java#L10)):*
> ```Java
> package io.harness.cvng.core.beans.monitoredService;
> 
> public enum MSReconciliationStatus {
> ```

I think ReconciliationStatus is good enough. Can be used outside MS as well.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2356 at r1](https://reviewable.io/reviews/harness/harness-core/55762#-Nju72zg8kpM1G7tdDxV:-Nju72zg8kpM1G7tdDxW:bjqe0za) ([raw file](https://github.com/harness/harness-core/blob/f2fca8b1f69c85ff87ff70e550d67b4e47266302/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2356)):*
> ```Java
>             .filter(MonitoredServiceKeys.templateMetadata + ".isTemplateByReference", true)
>             .filter(MonitoredServiceKeys.templateMetadata + ".templateIdentifier", templateIdentifier)
>             .filter(MonitoredServiceKeys.templateMetadata + ".versionLabel", templateVersionLabel)
> ```

check this: https://github.com/harness/harness-core/blob/48aefdff5792df806b05647790d5bcefd147a540/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/entities/VerificationTask.java#L116C3-L116C3
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 2374 at r1](https://reviewable.io/reviews/harness/harness-core/55762#-Nju79OC61EWrlG-V1VO:-Nju79OC61EWrlG-V1VP:b-poaaoo) ([raw file](https://github.com/harness/harness-core/blob/f2fca8b1f69c85ff87ff70e550d67b4e47266302/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L2374)):*
> ```Java
>                       .environmentIdentifier(monitoredService.getEnvironmentIdentifier())
>                       .lastReconciledTimestamp(monitoredService.getTemplateMetadata().getLastReconciliationTime());
>               if (monitoredService.getTemplateMetadata().getTemplateVersionNumber() == versionNumber) {
> ```

Can be a static function inside enum
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 502 at r1](https://reviewable.io/reviews/harness/harness-core/55762#-Nju7GSK5p_buLjX8vfN:-Nju7GSK5p_buLjX8vfO:bjmb8pd) ([raw file](https://github.com/harness/harness-core/blob/f2fca8b1f69c85ff87ff70e550d67b4e47266302/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L502)):*
> ```Java
> 
>   @Test
>   @Owner(developers = ABHIJITH)
> ```

correct username


<!-- Sent from Reviewable.io -->

2023-11-23 08:15 UTC, deepak-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55762)* status: 10 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-11-23 08:46 UTC, karansaraswat19 commented
trigger uts

2023-11-23 08:57 UTC, karansaraswat19 commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            .filter(MonitoredServiceKeys.projectIdentifier, projectParams.getProjectIdentifier())
these will be templateProjectParams, therefore orgIdentifier and projectIdentifier can be null also as templates can be account scoped as well

2023-11-23 08:59 UTC, karansaraswat19 commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +    String templateInput = templateFacade.getTemplateInputs(projectParams, templateIdentifier, templateVersionLabel);
can we name it as templateInputs

2023-11-23 09:53 UTC, karansaraswat19 commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java
> +  @NGAccessControlCheck(resourceType = MONITORED_SERVICE, permission = EDIT_PERMISSION)
do we need the EDIT permission here?

2023-11-23 10:04 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java
> +  @NGAccessControlCheck(resourceType = MONITORED_SERVICE, permission = EDIT_PERMISSION)
I don't think so, thanks for pointing out, can we fix in the next PR ?

2023-11-23 10:04 UTC, naveen-harness commented
trigger UTs

2023-11-23 10:05 UTC, naveen-harness commented
trigger uts

2023-11-23 11:30 UTC, Varsha-lalwani requested changes

2023-11-23 11:30 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceReference.java
> +  String serviceIdentifier;
Do we not need monitoredServiceIdentifier here?

2023-11-23 11:30 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            .filter(MonitoredServiceKeys.accountId, projectParams.getAccountIdentifier())
what about template in different scope than monitored service?

2023-11-23 11:30 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            .filter(
version shouldn't be in filter, no?

2023-11-23 11:35 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            .filter(MonitoredServiceKeys.accountId, projectParams.getAccountIdentifier())
template and monitored service have to be in the same scope

2023-11-23 11:36 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceReference.java
> +  String serviceIdentifier;
I think we should add, will add in the next PR

2023-11-23 11:37 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            .filter(
versionLabel needs to be in the filter, we're filtering by templateIdentifier and version

2023-11-23 12:16 UTC, Varsha-lalwani commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            .filter(
we need to filter irrespective of template version right? template version will be used for reconcilation status only.

2023-11-23 12:22 UTC, naveen-harness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java
> +            .filter(
there are two things: versionLabel and versionNumber both are different things
versionLabel is external attribute
versionNumber is something internal for template which is incremented every time template is updated

2023-11-23 13:16 UTC, naveen-harness commented
trigger uts

2023-11-23 15:45 UTC, karansaraswat19 commented
trigger ut6, ut9

2023-11-23 19:42 UTC, deepak-harness approved these changes
> Reviewed 3 of 8 files at r2, 4 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55762)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-24 01:45 UTC, karansaraswat19 approved these changes

2023-11-24 03:15 UTC, Varsha-lalwani approved these changes

2023-11-24 03:15 UTC, merged