fix: [CDS-79257]: fix the expression for secret functor by using single quote instead of double quotes
harness/harness-core pull request #55883
Opened 2023-11-23 09:46 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-23 10:05 UTC, shalini-agr commented
trigger smartchecks

2023-11-23 10:07 UTC, archit-harness submitted a review, later dismissed
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55883)* status: 15 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-23 10:13 UTC, shalini-agr commented
trigger uts

2023-11-23 10:47 UTC, shalini-agr commented
trigger uts

2023-11-23 10:50 UTC, archit-harness submitted a review, later dismissed
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55883)* status: 16 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-23 12:33 UTC, shalini-agr commented
trigger uts

2023-11-23 12:41 UTC, shalini-agr commented
trigger uts

2023-11-23 15:59 UTC, shalini-agr commented
trigger ut6, ut8, ut9

2023-11-24 03:49 UTC, shalini-agr commented
trigger uts

2023-11-24 04:09 UTC, shalini-agr commented
trigger ut9

2023-11-24 04:43 UTC, archit-harness requested changes
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55883)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 68 at r5](https://reviewable.io/reviews/harness/harness-core/55883#-NjzctgCBMdWXkxY40dH:-NjzctgCBMdWXkxY40dI:b-5xbtpc) ([raw file](https://github.com/harness/harness-core/blob/dca1621a716bdf754af257340b2437c2ccb732eb/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L68)):*
> ```Java
>       Pattern.compile("\\<\\+secrets.getValue\\((\\\"|\\')\\w*[\\.]?\\w*(\\\"|\\')\\)>");
>   private static final String INVALID_EXPRESSION_EXCEPTION = "Expression provided is not valid";
>   private static final Pattern SECRET_EXPRESSION = Pattern.compile(
> ```

we should add both


<!-- Sent from Reviewable.io -->

2023-11-24 04:50 UTC, shalini-agr commented
trigger uts

2023-11-24 04:59 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55883)* status: 23 file(s) to review. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 68 at r5](https://reviewable.io/reviews/harness/harness-core/55883#-NjzctgCBMdWXkxY40dH:-Njzg_BZBvLd5shchSwC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/dca1621a716bdf754af257340b2437c2ccb732eb/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add both
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-11-24 05:15 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/CINgSecretManagerFunctor.java
> +      return FunctorUtils.getSecretExpression(expressionFunctorToken, secretIdentifier);
This can possibly break things in CI K8 executions. Can you a try a CI k8 execution in local with a secret expression in run step and verify ? cc: @harshjain12

2023-11-24 06:46 UTC, archit-harness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/CINgSecretManagerFunctor.java
> +      return FunctorUtils.getSecretExpression(expressionFunctorToken, secretIdentifier);
@raghavharness can you share why ci expression engine will not work as for us its working, just wanted to understand

2023-11-24 07:06 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/CINgSecretManagerFunctor.java
> +      return FunctorUtils.getSecretExpression(expressionFunctorToken, secretIdentifier);
@archit-harness Because in ci addon we replace above expression with the actual secret manually. Even if we change this to support `'` and `"` it could still fail for customers who are on older version of addon - https://github.com/harness/harness-core/blob/ff93ae963dea8e22f83c62bc567bbd3bf20bfc76/product/ci/addon/resolver/secret.go#L25

2023-11-24 07:12 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/CINgSecretManagerFunctor.java
> +      return FunctorUtils.getSecretExpression(expressionFunctorToken, secretIdentifier);
I believe container step would also not work.

2023-11-24 07:18 UTC, closed without merging