feat: [CDS-71096]: add telemetry for K8s steps and manifests
harness/harness-core pull request #55880
Opened 2023-11-23 09:15 UTC by tmacari-harness

## Describe your changes
feat: [CDS-71096]: add telemetry for K8s steps and manifests
Adding  flushQueueSize  flushInterval configuration for segmentSender.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-04 10:47 UTC, tmacari-harness commented
trigger uts

2023-12-05 08:40 UTC, tmacari-harness commented
trigger uts

2023-12-05 10:32 UTC, archit-harness requested changes
> Reviewed 10 of 26 files at r1, 13 of 20 files at r2, 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55880)* status: 29 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/55880#-NktWXg4B0nYYD1BaJwX:-NktWXg4B0nYYD1BaJwY:b-1gx16u) ([raw file](https://github.com/harness/harness-core/blob/14a0b3929c2efeefb4a7ace79279ebad8fb2236c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java#L22)):*
> ```Java
> @OwnedBy(CDP)
> public class StepExecutionTelemetryEventDTO {
>   private String stepType;
> ```

can we rename this to eventName, steps can impl to return stepType that should be fine
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/55880#-NktWVGW9g4NxND9qmi1:-NktWVGW9g4NxND9qmi2:b2oa2kt) ([raw file](https://github.com/harness/harness-core/blob/14a0b3929c2efeefb4a7ace79279ebad8fb2236c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java#L23)):*
> ```Java
> public class StepExecutionTelemetryEventDTO {
>   private String stepType;
>   private HashMap<String, Object> properties;
> ```

can we have this as Map and not HashMap
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStep.java` line 174 at r4](https://reviewable.io/reviews/harness/harness-core/55880#-NktXETE0BlI_7FpyhV1:-NktXETE0BlI_7FpyhV2:b-a2flit) ([raw file](https://github.com/harness/harness-core/blob/14a0b3929c2efeefb4a7ace79279ebad8fb2236c/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStep.java#L174)):*
> ```Java
> 
>   @Override
>   public StepExecutionTelemetryEventDTO getStepExecutionTelemetryEventDTO(
> ```

cant we get getStepType method in cd wrapper class and each step return stepType.getType


<!-- Sent from Reviewable.io -->

2023-12-05 12:33 UTC, anilchowdhury-harness submitted a review, later dismissed

2023-12-06 07:03 UTC, tmacari-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55880)* status: 29 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/55880#-NktWXg4B0nYYD1BaJwX:-Nkxv_Cn1H8HUhDPZFf2:bsz782e) ([raw file](https://github.com/harness/harness-core/blob/14a0b3929c2efeefb4a7ace79279ebad8fb2236c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename this to eventName, steps can impl to return stepType that should be fine
</blockquote></details>

I take step type so we can use it as sufix in event name.
Ex: stepType = K8sRolling
eventName = step_execution_K8sRolling.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/55880#-NktWVGW9g4NxND9qmi1:-Nkxv4W13hGPjcod4mvB:b-amnbpe) ([raw file](https://github.com/harness/harness-core/blob/14a0b3929c2efeefb4a7ace79279ebad8fb2236c/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we have this as Map and not HashMap
</blockquote></details>

Telemetry framework method takes a HashMap: ```io.harness.telemetry.TelemetryReporter#sendTrackEvent(java.lang.String, java.lang.String, java.lang.String, java.util.HashMap<java.lang.String,java.lang.Object>, java.util.Map<io.harness.telemetry.Destination,java.lang.Boolean>, java.lang.String, io.harness.telemetry.TelemetryOption...)```.


<!-- Sent from Reviewable.io -->

2023-12-06 07:13 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55880)* status: 29 file(s) to review. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStep.java` line 174 at r4](https://reviewable.io/reviews/harness/harness-core/55880#-NktXETE0BlI_7FpyhV1:-NkxyINWBPWvNy_ehFjc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/14a0b3929c2efeefb4a7ace79279ebad8fb2236c/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStep.java#L174)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant we get getStepType method in cd wrapper class and each step return stepType.getType
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-12-06 08:38 UTC, tmacari-harness commented
trigger uts

2023-12-06 10:22 UTC, tmacari-harness commented
trigger uts

2023-12-06 10:41 UTC, tmacari-harness commented
trigger uts

2023-12-06 10:41 UTC, tmacari-harness commented
trigger messagecheck

2023-12-06 11:49 UTC, tmacari-harness commented
trigger messagecheck

2023-12-06 14:40 UTC, tmacari-harness commented
trigger uts

2023-12-06 18:17 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +    HashMap<String, Object> telemetryProperties = new HashMap<>();
nit: should be Map instead ? ( interface vs concrete class )

2023-12-06 18:19 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/DeploymentsInstrumentationHelper.java
> +        HashMap<String, Object> eventPropertiesMap =
should be Map instead ?

2023-12-06 18:20 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/DeploymentsInstrumentationHelper.java
> +        eventPropertiesMap.put(PIPELINE_EXECUTION_ID, ambiance.getPlanExecutionId());
is there some unique identifier for step execution Id also ?
Maybe we can push that as well. It might be of some use later

2023-12-06 18:22 UTC, yogesh-chauhan commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/StepExecutionTelemetryEventDTO.java
> +  private HashMap<String, Object> properties;
can be Map?

2023-12-06 18:24 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java
> +  @Inject TelemetryReporter telemetryReporter;
this is not being used yet ?

2023-12-06 18:26 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/HelmChartManifestOutcome.java
> +  public Map<String, Object> getTelemetryProperties() {
can you check if having a method that starts with "get" does not cause any issues ?
- does this field Telemetry show up on the outputs of the step or maybe accessible using expressions ? ( ideally, should not be)
- maybe better to just name this "createTelemetryProperties" or "fetchTelemetryProperties" ?

2023-12-06 18:26 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/HelmChartManifestOutcome.java
> +    telemetryProperties.put("helm_command_flags", isNotEmpty(getCommandFlags()));
extract out as a constant "helm_command_flags" ?

2023-12-06 18:56 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/DeploymentsInstrumentationHelper.java` line 38 at r8](https://reviewable.io/reviews/harness/harness-core/55880#gh-1417801069:-Nl-U7TxDssvNVAo9nnf:b-q6ir33) ([raw file](https://github.com/harness/harness-core/blob/e8717519c602a623bef423c6e2aadd1eb561fc2a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/DeploymentsInstrumentationHelper.java#L38)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be Map instead ?
</blockquote></details>

not possible right now because of how TelemetryReporter fwk is written


<!-- Sent from Reviewable.io -->

2023-12-06 18:56 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 199 at r8](https://reviewable.io/reviews/harness/harness-core/55880#gh-1417799550:-Nl-UEX4CyK34yj8w8Tw:b-q6ir33) ([raw file](https://github.com/harness/harness-core/blob/e8717519c602a623bef423c6e2aadd1eb561fc2a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L199)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: should be Map instead ? ( interface vs concrete class )
</blockquote></details>

not possible right now because of how TelemetryReporter fwk is written


<!-- Sent from Reviewable.io -->

2023-12-06 19:04 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/DeploymentsInstrumentationHelper.java` line 43 at r8](https://reviewable.io/reviews/harness/harness-core/55880#gh-1417802234:-Nl-W7xeDWi1xqYSIhDZ:b-3romzx) ([raw file](https://github.com/harness/harness-core/blob/e8717519c602a623bef423c6e2aadd1eb561fc2a/125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/DeploymentsInstrumentationHelper.java#L43)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is there some unique identifier for step execution Id also ?
Maybe we can push that as well. It might be of some use later
</blockquote></details>

will discuss offline and probably do in next PR if needed


<!-- Sent from Reviewable.io -->

2023-12-06 19:07 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 26 files at r1, 4 of 20 files at r2, 4 of 7 files at r3, 1 of 1 files at r4, 5 of 5 files at r7, 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55880)* status: 29 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-06 21:39 UTC, tmacari-harness commented
trigger uts

2023-12-06 21:40 UTC, tmacari-harness commented on 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/HelmChartManifestOutcome.java
> +  public Map<String, Object> getTelemetryProperties() {
renamed

2023-12-06 23:41 UTC, yogesh-chauhan approved these changes
> Reviewed 4 of 26 files at r1, 1 of 20 files at r2, 1 of 2 files at r5, 16 of 16 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55880)* status: 30 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-07 07:03 UTC, tmacari-harness commented
trigger uts

2023-12-07 07:06 UTC, anilchowdhury-harness submitted a review, later dismissed

2023-12-07 07:12 UTC, anilchowdhury-harness submitted a review, later dismissed

2023-12-07 07:20 UTC, tmacari-harness commented
trigger uts

2023-12-07 07:28 UTC, tmacari-harness commented
trigger uts

2023-12-07 08:07 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55880)* status: 30 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-07 08:22 UTC, anilchowdhury-harness approved these changes

2023-12-07 08:22 UTC, anilchowdhury-harness commented
trigger uts

2023-12-07 08:22 UTC, anilchowdhury-harness commented
trigger review

2023-12-07 08:23 UTC, tmacari-harness commented
trigger review

2023-12-07 09:04 UTC, tmacari-harness commented
trigger ut8

2023-12-07 10:22 UTC, merged