feat: [CDS-85044]: Create Open API for Re-run and Retry pipeline for v1
harness/harness-core pull request #55882
Opened 2023-11-23 09:34 UTC by utkarshchoubey-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-23 09:45 UTC, mankrit-singh approved these changes

2023-11-23 10:11 UTC, utkarshchoubey-harness commented
trigger uts

2023-11-24 04:25 UTC, shalini-agr commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +          name: plan_execution_id
can we make this a path param like in the rerun API above?

2023-11-24 06:36 UTC, utkarshchoubey-harness commented
trigger uts

2023-11-24 06:41 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55882)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 988 at r3](https://reviewable.io/reviews/harness/harness-core/55882#-Nk-2nhtB4lN23QJms20:-Nk-2nhtB4lN23QJms21:b-xxq2hx) ([raw file](https://github.com/harness/harness-core/blob/5bc32aac7346c541aff5a5f331219addbe45084e/pipeline-service/contracts/openapi/v1/openapi.yaml#L988)):*
> ```YAML
>       tags:
>         - Input Sets
>   '/v1/orgs/{org}/projects/{project}/pipelines/{pipeline}/rerun/{execution-id}':
> ```

do we use hyphen or underscore?



_Code quote:_
```YAML
execution-id}
```
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 1036 at r3](https://reviewable.io/reviews/harness/harness-core/55882#-Nk-2pf-16VhR8in2I1z:-Nk-2pf-16VhR8in2I2-:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/5bc32aac7346c541aff5a5f331219addbe45084e/pipeline-service/contracts/openapi/v1/openapi.yaml#L1036)):*
> ```YAML
>         - Pipeline Execution
>       x-internal: true
>   '/v1/orgs/{org}/projects/{project}/pipelines/{pipeline}/retry/{execution-id}':
> ```

same as above
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 3516 at r3](https://reviewable.io/reviews/harness/harness-core/55882#-Nk-2u_L8gCZvQJ8JUCn:-Nk-2u_L8gCZvQJ8JUCo:b-y3fl74) ([raw file](https://github.com/harness/harness-core/blob/5bc32aac7346c541aff5a5f331219addbe45084e/pipeline-service/contracts/openapi/v1/openapi.yaml#L3516)):*
> ```YAML
>       type: object
>       properties:
>         inputset_pipeline_yaml:
> ```

@brijeshdhakar lets suggest better names for all params inside new apis


<!-- Sent from Reviewable.io -->

2023-11-24 10:21 UTC, brijeshdhakar commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 3516 at r3](https://reviewable.io/reviews/harness/harness-core/55882#-Nk-2u_L8gCZvQJ8JUCn:-Nk-pPi8CYdn_wPn9DgB:b10qdrn) ([raw file](https://github.com/harness/harness-core/blob/5bc32aac7346c541aff5a5f331219addbe45084e/pipeline-service/contracts/openapi/v1/openapi.yaml#L3516)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar lets suggest better names for all params inside new apis
</blockquote></details>

Lets call it yaml same as pipeline-execute api.


<!-- Sent from Reviewable.io -->

2023-11-24 12:20 UTC, brijeshdhakar commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 988 at r3](https://reviewable.io/reviews/harness/harness-core/55882#-Nk-2nhtB4lN23QJms20:-Nk0GNHTBXHWsmrOnf-Q:b-nshgxn) ([raw file](https://github.com/harness/harness-core/blob/5bc32aac7346c541aff5a5f331219addbe45084e/pipeline-service/contracts/openapi/v1/openapi.yaml#L988)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we use hyphen or underscore?
</blockquote></details>

We are using hyphen only at all places in path params.


<!-- Sent from Reviewable.io -->

2023-11-27 05:38 UTC, utkarshchoubey-harness commented
trigger uts

2023-11-29 07:20 UTC, archit-harness requested changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55882)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 3516 at r3](https://reviewable.io/reviews/harness/harness-core/55882#-Nk-2u_L8gCZvQJ8JUCn:-NkOwNldETIJ0ngFDpd2:b-pb1brm) ([raw file](https://github.com/harness/harness-core/blob/5bc32aac7346c541aff5a5f331219addbe45084e/pipeline-service/contracts/openapi/v1/openapi.yaml#L3516)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Lets call it yaml same as pipeline-execute api.
</blockquote></details>

inputs
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 4167 at r4](https://reviewable.io/reviews/harness/harness-core/55882#-NkOwU2693VZod5PAlBY:-NkOwU2693VZod5PAlBZ:b-gqpwi4) ([raw file](https://github.com/harness/harness-core/blob/0d4badeedcb2715312c9b87beb290df2f3dd9630/pipeline-service/contracts/openapi/v1/openapi.yaml#L4167)):*
> ```YAML
>           x-stoplight:
>             id: 51p0t57s170jm
>           description: InputSet YAML if the pipeline contains runtime inputs. This will be empty by default if pipeline does not contains runtime inputs
> ```

InputsSet -> Inputs 



_Code quote:_
```YAML
InputSet
```


<!-- Sent from Reviewable.io -->

2023-11-29 09:46 UTC, utkarshchoubey-harness commented
trigger uts

2023-11-29 09:46 UTC, utkarshchoubey-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55882)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 3516 at r3](https://reviewable.io/reviews/harness/harness-core/55882#-Nk-2u_L8gCZvQJ8JUCn:-NkPTBji4SvWgV2eofbq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5bc32aac7346c541aff5a5f331219addbe45084e/pipeline-service/contracts/openapi/v1/openapi.yaml#L3516)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

inputs
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 4167 at r4](https://reviewable.io/reviews/harness/harness-core/55882#-NkOwU2693VZod5PAlBY:-NkPTC899BPRpJLezIxf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0d4badeedcb2715312c9b87beb290df2f3dd9630/pipeline-service/contracts/openapi/v1/openapi.yaml#L4167)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

InputsSet -> Inputs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-30 05:29 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55882)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-30 05:34 UTC, utkarshchoubey-harness commented
trigger messagecheck

2023-11-30 05:35 UTC, adivishy1 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55882)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-30 05:36 UTC, utkarshchoubey-harness commented
trigger review

2023-11-30 05:36 UTC, vtxorxwitty approved these changes

2023-11-30 05:42 UTC, mankrit-singh approved these changes

2023-11-30 05:43 UTC, merged