[feat]: [CCM-14787]: Azure Data Pipeline
harness/harness-core pull request #55893
Opened 2023-11-23 11:36 UTC by iamanmolm

## Describe your changes
Final Queries Formed: https://harness.atlassian.net/wiki/spaces/CE/pages/21563605134/Queries+Conversion+from+BQ+to+CH
Basic Sanity Testing: https://harness.atlassian.net/wiki/spaces/CE/pages/21563736548/Testing+queries+with+billing+exports

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-27 11:31 UTC, iamanmolm commented
trigger uts

2023-11-27 11:46 UTC, iamanmolm commented
trigger pmd, checkstylecodeformat, messagecheck, codebasehash, compile

2023-11-27 11:50 UTC, iamanmolm commented
trigger messagecheck

2023-11-29 07:56 UTC, nikunj-badjatya requested changes

2023-11-29 07:56 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +    print("Running command with retries on clickhouse :", query)
We spoke about adding log structure and including accountid, severity and log message to start with

2023-11-29 07:56 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/__pycache__/ch_ddl_queries.cpython-310.pyc
.pyc files shouldnt be part of git. Ignore this in .gitignore.

2023-11-29 07:56 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/ch_ddl_queries.py
> +create_azure_cost_table = """
Lets make sure we use the same schema file for GCP as well @sdsingh07 .

2023-11-29 07:56 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +    if paths == 0:
should be len(paths)

2023-11-29 07:56 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +def run_clickhouse_command(query):
This and with_retries methods can be combined into one with optional func argument.

2023-11-29 07:56 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +    for attempt in range(1, AZURE_REPORT_RETRIES + 1):
AZURE_REPORT_RETRIES 
Should be passed as func argument after combining with above function.

2023-11-29 07:56 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +        raise e
log exception here.

2023-11-29 08:04 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +        raise e
Same at other places.

2023-11-29 08:06 UTC, nikunj-badjatya commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +def create_billing_table(jsonData, azure_column_mapping):
This func is doing more things than creating table. Lets split ?

2023-11-29 09:26 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +    print("Running command with retries on clickhouse :", query)
Added

2023-11-29 09:27 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/__pycache__/ch_ddl_queries.cpython-310.pyc
Removed

2023-11-29 09:28 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/ch_ddl_queries.py
> +create_azure_cost_table = """
Yep, that is why this ch_ddl_queries is already merged to develop so that we both use the same file.

2023-11-29 09:28 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +    if paths == 0:
Fixed it.

2023-11-29 09:29 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +        raise e
Done.

2023-11-29 09:33 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +def create_billing_table(jsonData, azure_column_mapping):
Given a more appropriate to this like create_and_ingest_data_into_billing_table.

2023-11-29 11:06 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +def run_clickhouse_command(query):
Done

2023-11-29 11:06 UTC, iamanmolm commented on scripts/terraform/cloudfunctions/ce/src/python/k8sCronJob/azure_billing_clickhouse.py
> +    for attempt in range(1, AZURE_REPORT_RETRIES + 1):
Done

2023-11-30 05:52 UTC, nikunj-badjatya approved these changes

2023-11-30 05:54 UTC, merged