fix: [CI-9556]: Add support for log-service acl check
harness/harness-core pull request #55909
Opened 2023-11-23 19:18 UTC by smjt-h

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-23 19:22 UTC, smjt-h commented
trigger uts

2023-11-25 12:02 UTC, smjt-h commented
trigger uts

2023-11-25 12:53 UTC, smjt-h commented
trigger uts

2023-11-27 10:31 UTC, smjt-h commented
trigger uts

2023-11-27 11:10 UTC, vistaarjuneja commented on product/log-service/handler/middleware.go
> +					fmt.Println("error Validating Access to pipeline: ", pipelineIdentifier, err)
Use logger instead of fmt everywhere

2023-11-27 11:10 UTC, vistaarjuneja commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New("Error validating access for resource, unauthorized or expired token"))
This should be an internal error, not a bad request

2023-11-27 11:10 UTC, vistaarjuneja commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New("User not authorized"))
This should be a 403 access denied error

2023-11-27 11:10 UTC, vistaarjuneja commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New("apikey in request not authorized for receiving tokens"))
This should be internal error - have a look at all returns and update to an error code which makes sense

2023-11-27 11:10 UTC, vistaarjuneja commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New(fmt.Sprintf("operation not permitted for accountID: %s", accountID)))
403 access denied error - we should fix it in other places as well if we have it other than this PR

2023-11-27 11:10 UTC, vistaarjuneja commented on product/platform/client/helper.go
> +func GetACLRequest(accountID, pipelineID, projectID, orgID string) ACLRequest {
A function called `GetACLRequest` in `platform/client/helper` shouldn't be hardcoding the resource permission and resource type.
If it sits in `product/platform`, the client should be generic and not be tied to the code needed for log service

2023-11-27 11:10 UTC, vistaarjuneja commented on product/log-service/handler/handler.go
> -			sr.Use(AuthMiddleware(config, ngClient, false))
We can keep the name AuthMiddleware and just update that handler directly

2023-11-27 11:10 UTC, vistaarjuneja requested changes
left comments

2023-11-27 11:15 UTC, smjt-h commented on product/log-service/config/config.go
> +		WorkerPool    int    `envconfig:"LOG_SERVICE_WORKER_POOL" default:"0"`
reverted

2023-11-27 11:26 UTC, smjt-h commented on product/platform/client/client.go
> +		Principal struct {
done

2023-11-27 11:28 UTC, smjt-h commented on product/platform/client/client.go
> +// AccountResponse represents a json-encoded response for /acl api.
done

2023-11-27 11:35 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +					fmt.Println("error Validating Access to pipeline: ", pipelineIdentifier, err)
done

2023-11-27 11:36 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New("Error validating access for resource, unauthorized or expired token"))
done

2023-11-27 11:38 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New("User not authorized"))
done

2023-11-27 11:38 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New("apikey in request not authorized for receiving tokens"))
fixed

2023-11-27 11:39 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New(fmt.Sprintf("operation not permitted for accountID: %s", accountID)))
fixed

2023-11-27 11:44 UTC, smjt-h commented on product/log-service/handler/handler.go
> -			sr.Use(AuthMiddleware(config, ngClient, false))
done

2023-11-27 12:47 UTC, vistaarjuneja commented on product/platform/client/client.go
> +// ACLPrincipal represents the principal information.
these comments are not useful, you can remove unless there's some net new information. Or we take the approach that we always add comments everywhere (which we don't)

2023-11-27 12:47 UTC, vistaarjuneja commented on product/log-service/handler/middleware.go
> +			if inputAuthToken != "" && r.Method == http.MethodGet {
Why are we checking that the method is GET? Shouldn't we be doing authorization for all the API calls?

2023-11-27 12:47 UTC, vistaarjuneja commented on product/log-service/handler/middleware.go
> +					writeError(w, errors.New("User not authorized"), 403)
lower case

2023-11-27 14:31 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +			if inputAuthToken != "" && r.Method == http.MethodGet {
We dont want to expose apis for all the calls for now we decided only for GET calls

2023-11-27 14:35 UTC, smjt-h commented on product/platform/client/helper.go
> +	resource_pipeline = "PIPELINE"
done

2023-11-27 14:37 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +						Errorln("error Validating Access to pipeline:")
done

2023-11-27 14:38 UTC, smjt-h commented on product/log-service/handler/middleware.go
> +					WriteBadRequest(w, errors.New("Scope pipelineID, projectID and orgID are required for validating access"))
done

2023-11-27 18:17 UTC, smjt-h commented
trigger uts

2023-11-29 16:49 UTC, vistaarjuneja approved these changes

2023-11-30 04:21 UTC, merged