fix:[CDS-84663]: Storing primaryManifestId in sweeping output
harness/harness-core pull request #55945
Opened 2023-11-24 11:33 UTC by GoelPratyush99

## Describe your changes
Storing primaryManifestId in sweeping output to make it accessible to the users.
Expression: <+manifests.primaryManifestId>

##Tests

1. K8s deploy using this variable in shell script
2. Helm deploy using this variable in shell script

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-24 11:57 UTC, abosii-harness requested changes

2023-11-24 11:57 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      sweepingOutputService.consume(ambiance, OutcomeExpressionConstants.MANIFESTS, outcome, StepCategory.STAGE.name());
Have you tested the full flow on this? We're going later to again store io/harness/cdng/manifest/steps/ManifestsStepV2.java:217, I believe this call then will fail

2023-11-24 11:58 UTC, abosii-harness commented
@GoelPratyush99 please add required labels to the PR and screenshots with testing scenarios

2023-11-24 12:35 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      sweepingOutputService.consume(ambiance, OutcomeExpressionConstants.MANIFESTS, outcome, StepCategory.STAGE.name());
Not completed testing yet

2023-11-24 17:17 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      sweepingOutputService.consume(ambiance, OutcomeExpressionConstants.MANIFESTS, outcome, StepCategory.STAGE.name());
done

2023-11-27 06:39 UTC, GoelPratyush99 commented
trigger uts

2023-11-27 06:39 UTC, abhinavsingh1196 approved these changes

2023-11-27 07:26 UTC, TarunUba1 submitted a review, later dismissed

2023-11-27 07:44 UTC, yogesh-chauhan commented
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifestConfigs/outcome/ManifestConfigurationsOutcome.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/55945#-NkEjB5g6a8-WvhLhMMO:-NkEjB5g6a8-WvhLhMMP:b-mnafk) ([raw file](https://github.com/harness/harness-core/blob/38d6de03f20ad50ecb6f1856b238f3ede1ccfb7c/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifestConfigs/outcome/ManifestConfigurationsOutcome.java#L31)):*
> ```Java
> @TypeAlias("ManifestConfigurationsOutcome")
> @RecasterAlias("io.harness.cdng.manifestConfigs.outcome.ManifestConfigurationsOutcome")
> public class ManifestConfigurationsOutcome implements Outcome, ExecutionSweepingOutput {
> ```

does it need to implement ExecutionSweepintOutput ?


<!-- Sent from Reviewable.io -->

2023-11-27 07:46 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 313 at r1](https://reviewable.io/reviews/harness/harness-core/55945#gh-1404276303:-NkEjPMR6ohKB72nqHc-:b-wl16lm) ([raw file](https://github.com/harness/harness-core/blob/1ee4efcb534339497945a21abd9ea5188c861833/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L313)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

done
</blockquote></details>

Does it look like the correct place to put sweepingoutput.consume() ?
The method is "resolveManifestsOutcome". 
Maybe we can have this method return the primary manifest ID and then save the sweeping output in the `io.harness.cdng.manifest.steps.ManifestsStepV2#executeAsync` method itself 
This should improve readability 


<!-- Sent from Reviewable.io -->

2023-11-27 07:46 UTC, yogesh-chauhan requested changes
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55945)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-27 10:22 UTC, GoelPratyush99 commented
trigger uts

2023-11-27 12:02 UTC, GoelPratyush99 commented
trigger ut5

2023-11-27 12:24 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55945)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-27 12:29 UTC, GoelPratyush99 commented
trigger uts

2023-11-27 13:29 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 186 at r5](https://reviewable.io/reviews/harness/harness-core/55945#-NkFy4NF0OBAj-dGSJIn:-NkFy4NF0OBAj-dGSJIo:bljpv7i) ([raw file](https://github.com/harness/harness-core/blob/b50e789a2be96813507bfb40d05bd710b111fcce/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L186)):*
> ```Java
>       Optional<ManifestsOutcome> manifestsOutcome = manifestSpec.get().getOptionalManifestsOutcome();
>       manifestsOutcome.ifPresent(manifests -> handleManifests(ambiance, manifests, callbackIds, logCallback));
>       String primaryManifestId = manifestSpec.get().getPrimaryManifestId();
> ```

nit: we can move `String primaryManifestId = manifestSpec.get().getPrimaryManifestId();` as well into the ` saveManifestConfigurationOutcome` method


<!-- Sent from Reviewable.io -->

2023-11-27 13:30 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55945)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-27 14:19 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55945)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-11-27 16:56 UTC, GoelPratyush99 commented
trigger uts

2023-11-27 16:59 UTC, abosii-harness commented
@GoelPratyush99 please add UTs

2023-11-29 05:47 UTC, abhinavsingh1196 approved these changes

2023-11-29 05:47 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      manifestsOutcome.ifPresent(outcome -> saveManifestsOutcome(ambiance, outcome, new HashMap<>()));
both optional.ifPresent() and optional.isPresent() are being used here

2023-11-29 06:05 UTC, GoelPratyush99 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      manifestsOutcome.ifPresent(outcome -> saveManifestsOutcome(ambiance, outcome, new HashMap<>()));
both are on different classes. isPresent is used in ManifestSpec class and ifPresent is used on ManifestsOutcome class

2023-11-29 07:08 UTC, abosii-harness approved these changes

2023-11-29 07:33 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      manifestsOutcome.ifPresent(outcome -> saveManifestsOutcome(ambiance, outcome, new HashMap<>()));
I meant usage should be consistent, use either not both

2023-11-29 07:48 UTC, merged