feat: [SSCA-1005]: Adding opa client, policy mgmt service and related beans to ssca manager
harness/harness-core pull request #55964
Opened 2023-11-26 19:49 UTC by dhruv-harness

## Describe your changes

1. Adding policy mgmt service client in the ssca manager with corresponding beans.
2. Making policy_file_id field optional and adding policy_set_ref as an optional field in the sbom/enforcement API request body.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/55964)

2023-11-26 19:50 UTC, dhruv-harness commented
trigger uts

2023-11-27 05:14 UTC, dhruv-harness commented
trigger uts

2023-11-27 05:24 UTC, dhruv-harness commented
trigger messagecheck

2023-11-27 08:02 UTC, mankrit-singh approved these changes

2023-11-27 11:42 UTC, inderschera commented on ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java
> +          opaEvaluationResponseHolder.getDetails().get(POLICY_SET_INDEX).getDetails();
It's better to add null checks here.

2023-11-27 11:44 UTC, inderschera commented on ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java
> +        .get(OPA_OUTPUT_JSON_KEY_2);
better to add null checks here as well

2023-11-27 13:47 UTC, deepharness requested changes
> Reviewed 5 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55964)* status: 8 file(s) to review. 1 change requests. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/55964#-NkG0yLG3UtHjyY8ZDoq:-NkG0yLG3UtHjyY8ZDor:bds9i56) ([raw file](https://github.com/harness/harness-core/blob/01f92f3cd708d9d9d55b596e07394cdf31a35ac2/ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java#L83)):*
> ```Java
>   private static JsonNode extractOpaEvaluationEngineOutputNode(
>       OpaPolicyEvaluationResponse singlePolicyEvaluationResponse) {
>     return JsonUtils.asTree(singlePolicyEvaluationResponse.getOutput())
> ```

Why don't we typecast output into ssca violation dto?
___
*[`ssca-manager/service/src/main/resources/localhost.pem` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/55964#-NkFxPQ93kK5Qi7o6n2p:-NkFxPQACIVKVU-gPcea:bwujkda) ([raw file](https://github.com/harness/harness-core/blob/01f92f3cd708d9d9d55b596e07394cdf31a35ac2/ssca-manager/service/src/main/resources/localhost.pem#L2)):*
> ```
> -----BEGIN CERTIFICATE-----
> MIIDcTCCAlmgAwIBAgIEAetBozANBgkqhkiG9w0BAQsFADBpMQswCQYDVQQGEwJV
> ```

Do we have to check-in this cert. Normally we don't keep any cert in code repo


<!-- Sent from Reviewable.io -->

2023-11-27 13:56 UTC, dhruv-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55964)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/55964#-NkG0yLG3UtHjyY8ZDoq:-NkG2X_0Bzd3IUU1iB_Z:b2uttde) ([raw file](https://github.com/harness/harness-core/blob/01f92f3cd708d9d9d55b596e07394cdf31a35ac2/ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java#L83)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why don't we typecast output into ssca violation dto?
</blockquote></details>

The output from the opa policy engine contains multiple fields, including the allow and deny list violations. The violations are further grouped by rules. They can not be directly cast into violation dto
___
*[`ssca-manager/service/src/main/resources/localhost.pem` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/55964#-NkFxPQ93kK5Qi7o6n2p:-NkG2NLE1gSe06NKQsBV:b-417s4p) ([raw file](https://github.com/harness/harness-core/blob/01f92f3cd708d9d9d55b596e07394cdf31a35ac2/ssca-manager/service/src/main/resources/localhost.pem#L2)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Do we have to check-in this cert. Normally we don't keep any cert in code repo
</blockquote></details>

localhost.pem is already present in multiple modules.


<!-- Sent from Reviewable.io -->

2023-11-27 14:10 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java
> +        .get(OPA_OUTPUT_JSON_KEY_2);
I am not sure what benefit we will get out of adding null checks. While it is possible that the json format is different than expected, it will throw an NPE with the erroring key which can be easily checked through logs.
Assuming we add null checks or use try catch to check for NPEs, in both the cases we can not proceed the execution further and will have to throw an exception like BadRequestException.
What are your thoughts?

2023-11-27 14:58 UTC, inderschera commented on ssca-manager/service/src/main/java/io/harness/ssca/services/PolicyMgmtServiceImpl.java
> +        .get(OPA_OUTPUT_JSON_KEY_2);
@dhruv-harness So, you are saying any of the gets from the object cannot be null, say in case there are no policies defined or no policy violations are there. If there is a valid case, where any of the gets could be null, then we should check for nulls.

2023-11-28 07:43 UTC, deepharness approved these changes
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55964)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-11-28 12:39 UTC, inderschera approved these changes

2023-11-28 16:53 UTC, merged