[feat]:[CDS-81185]:Added Telemetry instrumentation for API to fetch repository and packages in GAR
harness/harness-core pull request #56026
Opened 2023-11-28 05:15 UTC by Rakshitharness

## Describe your changes
Added telemetry For the API to fetch repository and Packages in GAR.
Checked in local For V1 and V2 calls.
<img width="1703" alt="Screenshot 2023-11-28 at 10 28 26 AM" src="https://github.com/harness/harness-core/assets/142882849/607ffa87-3836-4123-92a7-8f4d037fbad1">
<img width="1702" alt="Screenshot 2023-11-28 at 10 28 41 AM" src="https://github.com/harness/harness-core/assets/142882849/4f973928-7a75-49dc-b06e-66e7134249d4">
<img width="1702" alt="Screenshot 2023-11-28 at 10 29 08 AM" src="https://github.com/harness/harness-core/assets/142882849/86c19b05-f499-4d99-8b09-bb5aabe5e180">
<img width="1702" alt="Screenshot 2023-11-28 at 10 29 25 AM" src="https://github.com/harness/harness-core/assets/142882849/35358c0d-df38-4129-a55b-391fd5f9cfaf">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-28 05:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=56026) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=56026) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=56026) it.</sub>

2023-11-28 05:27 UTC, Rakshitharness commented
trigger messagecheck

2023-11-28 05:43 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +    eventPropertiesMap.put(COUNT, count);
Can we add a field to check wether the service is remote?

2023-11-28 05:44 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +    eventPropertiesMap.put(ARTIFACT_ACCOUNT, accountId);
Update this to ACCOUNT and similar for org and project

2023-11-28 05:45 UTC, puthrayaharness requested changes

2023-11-28 05:45 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java
> +    long time_taken = System.currentTimeMillis() - time_start;
Please use camelCase

2023-11-28 05:45 UTC, puthrayaharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +  public CompletableFuture<Void> sendArtifactApiEvent(String artifactSourceType, String accountId, String orgId,
Please use camelCase not snake case

2023-11-28 07:05 UTC, Rakshitharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java
> +    long time_taken = System.currentTimeMillis() - time_start;
Changed it to camelCase as timeTaken

2023-11-28 07:05 UTC, Rakshitharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +    eventPropertiesMap.put(ARTIFACT_ACCOUNT, accountId);
updated for all the three field as ACCOUNT , PROJECT , ORG

2023-11-28 07:06 UTC, Rakshitharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +    eventPropertiesMap.put(COUNT, count);
added a new field as IS_SERVICE_REMOTE

2023-11-28 07:06 UTC, Rakshitharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +  public CompletableFuture<Void> sendArtifactApiEvent(String artifactSourceType, String accountId, String orgId,
Done

2023-11-28 07:44 UTC, sarthakkasat commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +  public static final String ACCOUNT = "account";
Use the constants from InstrumentationConstants

2023-11-28 08:06 UTC, Rakshitharness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers/ArtifactSourceInstrumentationHelper.java
> +  public static final String ACCOUNT = "account";
Done

2023-11-28 08:56 UTC, sarthakkasat submitted a review, later dismissed

2023-11-28 09:28 UTC, puthrayaharness requested changes

2023-11-28 09:28 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java
> +    artifactSourceInstrumentationHelper.sendArtifactApiEvent("GoogleArtifactRegistry", accountId, orgIdentifier,
Please reuse the constants for artifact source name. 

Please create constants for constants like `fetch_packages`. Please keep it in snake case format.

2023-11-28 09:29 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java
> +    artifactSourceInstrumentationHelper.sendArtifactApiEvent("GoogleArtifactRegistry", accountId, orgIdentifier,
Artifact Source name should match the same as that of ArtifactSourceType. So directly use enum here instead of other things

2023-11-28 09:29 UTC, puthrayaharness commented on 120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java
> +    artifactSourceInstrumentationHelper.sendArtifactApiEvent("GoogleArtifactRegistry", accountId, orgIdentifier,
It should be `fetch_packages` and not `fetch_Packages`

2023-11-28 14:15 UTC, puthrayaharness approved these changes

2023-11-28 14:17 UTC, sarthakkasat submitted a review, later dismissed

2023-11-28 14:18 UTC, sarthakkasat commented
trigger uts, trigger review

2023-11-28 18:38 UTC, Rakshitharness commented
trigger ut7, ut8, ut9

2023-11-29 05:57 UTC, Rakshitharness commented
trigger copyrightcheck

2023-11-29 05:59 UTC, Rakshitharness commented
trigger commonchecks

2023-11-29 06:28 UTC, Rakshitharness commented
trigger uts

2023-11-29 06:56 UTC, sarthakkasat approved these changes

2023-11-29 09:23 UTC, tchaurasiya approved these changes

2023-11-29 09:24 UTC, Rakshitharness commented
trigger review

2023-11-30 05:10 UTC, merged