feat:[CDS-75291]: Added kubernetes java client support for canary and traffic shift step CG
harness/harness-core pull request #56028
Opened 2023-11-28 05:35 UTC by GoelPratyush99

## Describe your changes
The feature is behind FF: `CDS_DISABLE_FABRIC8_CG`
When this FF is enabled we will be using kubernetes java client for canary and traffic shift step instead of fabric8. This is being done to remove the dependency from fabric8.

## Steps Involved

- Canary
- Traffic Split
- Container resize (Deprecated need to check)

## Test

- [ ] Test canary step with FF enabled
- [ ] Test Traffic Split with FF enabled
- [ ] Test canary step with FFdisabled
- [ ] Test Traffic Split with FFdisabled

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-01 13:56 UTC, GoelPratyush99 commented
trigger uts

2023-12-01 15:12 UTC, GoelPratyush99 commented
trigger ut5, ut8

2023-12-01 19:10 UTC, GoelPratyush99 commented
trigger uts

2023-12-05 09:51 UTC, abhinavsingh1196 requested changes
> Reviewed 5 of 15 files at r1, 7 of 8 files at r2, 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56028)* status: Some of the checks are too old. 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 243 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktI-1DBJvIQNqWQAMs:-NktI-1DBJvIQNqWQAMt:busjrjd) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L243)):*
> ```Java
>           "\nNo VirtualService found with name " + virtualServiceName, ERROR, FAILURE);
>       return false;
>     }
> ```

should we also fail if we don't find virtual service using k8s client?
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktIzsl0zYfpA0WL401:-NktIzsmBDj5-eUtXZnx:bb8i3t0) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L286)):*
> ```Java
>           if (isNotEmpty(annotations) && annotations.containsKey(HarnessAnnotations.managed)
>               && annotations.get(HarnessAnnotations.managed).equalsIgnoreCase("true")) {
>             managedVirtualServices.add(resourceId);
> ```

can we write this using streams? since we just want to transform 
RESOURCES -> VirtualServices with Managed annotation
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 327 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktJknM2coZom65IQjH:-NktJknM2coZom65IQjI:b-vap644) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L327)):*
> ```Java
>     List<IstioDestinationWeight> istioDestinationWeights = k8sTrafficSplitTaskParameters.getIstioDestinationWeights();
>     istioTaskHelper.updateVirtualServiceWithDestinationWeights(
>         istioDestinationWeights, istioVirtualService, executionLogCallback);
> ```

both `updateVirtualServiceWithDestinationWeightsUsingFabric8Client` and `updateVirtualServiceWithDestinationWeightsUsingK8sClient` have duplicate code, except the input VirtualService
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 1651 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktM36R5DCVE2-nUrUX:-NktM36R5DCVE2-nUrUY:b5t231h) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1651)):*
> ```Java
>   private KubernetesResource createOrReplaceVirtualServiceUsingK8sClient(KubernetesConfig kubernetesConfig,
>       Object virtualService, String[] apiVersionArray, String name, boolean virtualServiceExist) {
>     if (kubernetesConfig == null) {
> ```

Is this possible? I think we can fail in the caller method itself, no need to perform `getVirtualServiceUsingK8sClient` too
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 1698 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktMtpcDApFg3k51_Xz:-NktMtpcDApFg3k51_Y-:b-fzo4d0) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1698)):*
> ```Java
>   @Override
>   public Object getVirtualServiceUsingK8sClient(KubernetesConfig kubernetesConfig, String name) {
>     String[] apiVersionArray = {ISTIO_GROUP, ISTIO_VERSION};
> ```

nit: we can just pass group and version directly? 
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 1716 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktMee99pd3X2j73fY-:-NktMee99pd3X2j73fY0:b8zg5iw) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1716)):*
> ```Java
>         return ObjectYamlUtils.getField(virtualServiceList, FIRST_ITEM_ELEMENT);
>       } catch (ApiException exception) {
>         String message = format("Unable to get %s/VirtualService/%s Code: %s, message: %s",
> ```

nit: should we also print apiVersion info in the message? even though it is hardcoded in code for now


<!-- Sent from Reviewable.io -->

2023-12-05 14:20 UTC, abosii-harness requested changes

2023-12-05 14:20 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +  private Object getVirtualServiceUsingK8sClient(KubernetesConfig kubernetesConfig, String name, String[] apiVersion) {
String[] can be a new class

2023-12-05 14:20 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +            customObjectsApi.listNamespacedCustomObject(apiVersion[0], apiVersion[1], kubernetesConfig.getNamespace(),
Why we're using list method here and not get? I believe this require a different permissions

2023-12-05 14:20 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +    String name = (String) virtualService.getField("metadata.name");
this can be a constant

2023-12-05 14:20 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> -import io.fabric8.istio.api.networking.v1alpha3.VirtualService;
any reason why we're removing these imports?

2023-12-06 10:58 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +    String[] apiVersionArray = {ISTIO_GROUP, ISTIO_VERSION};
i do not have access to kuberentes resource in traffic split step. We are only passing the virtual service name. In fabric8 we are fetching the virtual networks of ISTIO_VERSION: v1aplha3 hence for kubernetes java client I am only using v1alpha3. Fyi we also have v1beta1 istio apiversion.

2023-12-06 11:26 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +            customObjectsApi.listNamespacedCustomObject(apiVersion[0], apiVersion[1], kubernetesConfig.getNamespace(),
done.

2023-12-06 11:29 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56028)* status: 13 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 243 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktI-1DBJvIQNqWQAMs:-NkybFkuD8j0iLYoMuOd:bd1lit7) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L243)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

should we also fail if we don't find virtual service using k8s client?
</blockquote></details>

Yes, Because this time it depends on FF. If it is enabled then we use k8s otherwise we use fabric8. Hence it makes sense to fail we we don't find virtual service using k8s client. (Keeping behaviour same as fabric8)
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktIzsl0zYfpA0WL401:-Nkys_Sy8nH9MP4JAC6a:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L286)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

can we write this using streams? since we just want to transform 
RESOURCES -> VirtualServices with Managed annotation
</blockquote></details>

done
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 327 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktJknM2coZom65IQjH:-NkysaKKDlKuDm8uYJwC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L327)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

both `updateVirtualServiceWithDestinationWeightsUsingFabric8Client` and `updateVirtualServiceWithDestinationWeightsUsingK8sClient` have duplicate code, except the input VirtualService
</blockquote></details>

done
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 1651 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktM36R5DCVE2-nUrUX:-NkysezF8vAYTnYs6tYy:b-7rl0i8) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1651)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

Is this possible? I think we can fail in the caller method itself, no need to perform `getVirtualServiceUsingK8sClient` too
</blockquote></details>

doneW
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 1698 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktMtpcDApFg3k51_Xz:-Nkysi5i5zuRUDexMW7R:b-vo3014) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1698)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: we can just pass group and version directly?
</blockquote></details>

We are calling the getVirtualServiceUsingK8sClient at 2 places out out which in one we are reading from virtual service object and hence cannot pass them directly to keep the code generic.
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 1716 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktMee99pd3X2j73fY-:-Nkyszm8CAQ_EjuXdDvX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1716)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: should we also print apiVersion info in the message? even though it is hardcoded in code for now
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-12-06 11:30 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> -import io.fabric8.istio.api.networking.v1alpha3.VirtualService;
reverted it.

2023-12-06 11:30 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +    String name = (String) virtualService.getField("metadata.name");
done

2023-12-06 11:42 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +  private Object getVirtualServiceUsingK8sClient(KubernetesConfig kubernetesConfig, String name, String[] apiVersion) {
done

2023-12-06 11:43 UTC, GoelPratyush99 commented
trigger uts

2023-12-06 11:56 UTC, GoelPratyush99 commented
trigger uts

2023-12-07 11:56 UTC, abosii-harness requested changes

2023-12-07 11:56 UTC, abosii-harness commented on 260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java
> +        io.fabric8.istio.api.networking.v1alpha3.VirtualService fabric8VirtualService =
nit: missing import

2023-12-07 11:56 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        return customObjectsApi.replaceNamespacedCustomObject(apiVersionArray[0], apiVersionArray[1],
This should use instead new K8sApiVersion class

2023-12-07 12:52 UTC, abhinavsingh1196 reviewed
> Reviewed 1 of 2 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56028)* status: 14 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 243 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktI-1DBJvIQNqWQAMs:-Nl3I0c35J1_0LjniUf-:bvnth3) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L243)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Yes, Because this time it depends on FF. If it is enabled then we use k8s otherwise we use fabric8. Hence it makes sense to fail we we don't find virtual service using k8s client. (Keeping behaviour same as fabric8)
</blockquote></details>

I thought `istioVirtualService` has no null check, my bad. I see its there :) 
___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktIzsl0zYfpA0WL401:-Nl3J2pj5qvhCrxMP49X:bnjti9y) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L286)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

done
</blockquote></details>

this can be improved further

resourceIds.stream()  
.filter(resourceId -> Kind.VirtualService.name().equals(resourceId.getKind()))  
.map(resourceId -> kubernetesContainerService.getVirtualServiceUsingK8sClient(kubernetesConfig, resourceId.getName()))  
.filter(Objects::nonNull)  
.filter(this::containsHarnessManagedAnnotation)  
.collect(Collectors.toList())

boolean containsHarnessManagedAnnotation(...) {...}


<!-- Sent from Reviewable.io -->

2023-12-08 06:40 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56028)* status: 14 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktIzsl0zYfpA0WL401:-Nl78fu47_n8LNZuiTFa:b-daojtb) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L286)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

this can be improved further

resourceIds.stream()  
.filter(resourceId -> Kind.VirtualService.name().equals(resourceId.getKind()))  
.map(resourceId -> kubernetesContainerService.getVirtualServiceUsingK8sClient(kubernetesConfig, resourceId.getName()))  
.filter(Objects::nonNull)  
.filter(this::containsHarnessManagedAnnotation)  
.collect(Collectors.toList())

boolean containsHarnessManagedAnnotation(...) {...}
</blockquote></details>

But now wouldn't the list become List<Object> because of map whereas what I want to return is a List<KubernetesResourceId>


<!-- Sent from Reviewable.io -->

2023-12-08 06:43 UTC, GoelPratyush99 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56028)* status: 14 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktIzsl0zYfpA0WL401:-Nl79UV29wCHGpybge-e:b4hp3wb) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L286)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

But now wouldn't the list become List<Object> because of map whereas what I want to return is a List<KubernetesResourceId>
</blockquote></details>

But now wouldn't the return type become List of Object because of map whereas what I want to return is a List of KubernetesResourceId


<!-- Sent from Reviewable.io -->

2023-12-08 07:03 UTC, GoelPratyush99 commented
trigger uts

2023-12-08 07:04 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        kubernetesConfig, name, K8sApiVersion.builder().group(apiVersionArray[0]).version(apiVersionArray[1]).build());
done

2023-12-08 07:04 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        return customObjectsApi.replaceNamespacedCustomObject(apiVersionArray[0], apiVersionArray[1],
done

2023-12-08 08:41 UTC, GoelPratyush99 commented
trigger uts

2023-12-08 09:48 UTC, GoelPratyush99 commented
trigger ut5

2023-12-08 09:49 UTC, GoelPratyush99 commented
trigger messagecheck

2023-12-08 10:22 UTC, abosii-harness requested changes

2023-12-08 10:22 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        return ObjectYamlUtils.getField(virtualServiceList, FIRST_ITEM_ELEMENT);
if you're using get then why we're still getting first element? As well, let's just in case have a null check

2023-12-08 11:26 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        return customObjectsApi.createNamespacedCustomObject(apiVersionArray[0], apiVersionArray[1],
done

2023-12-08 11:26 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        kubernetesConfig, name, K8sApiVersion.builder().group(apiVersionArray[0]).version(apiVersionArray[1]).build());
done

2023-12-08 11:36 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        return ObjectYamlUtils.getField(virtualServiceList, FIRST_ITEM_ELEMENT);
Done null checks are at all the places where this function is being called. getNamespacedCustomObject return a single element so have updated the code.

2023-12-08 11:36 UTC, GoelPratyush99 commented
trigger uts

2023-12-08 17:20 UTC, abosii-harness approved these changes

2023-12-11 05:39 UTC, abhinavsingh1196 approved these changes
> Reviewed 2 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56028)* status: 14 file(s) to review. 9. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/56028#-NktIzsl0zYfpA0WL401:-NlMMYpq6tkjbqGC8HGw:b-36xemj) ([raw file](https://github.com/harness/harness-core/blob/2a53628ba791dfd9331042d71c410042650b474e/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sTrafficSplitTaskHandler.java#L286)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

But now wouldn't the return type become List of Object because of map whereas what I want to return is a List of KubernetesResourceId
</blockquote></details>

you can cast objects in stream also

..
.stream()
.filter(obj -> obj instanceof X)
.map(X.class::cast)
...

The current impl also looks fine to me, so will leave it up to you.


<!-- Sent from Reviewable.io -->

2023-12-11 05:43 UTC, GoelPratyush99 commented
trigger uts

2023-12-11 06:24 UTC, GoelPratyush99 commented
trigger ut7, ut8

2023-12-11 07:05 UTC, GoelPratyush99 commented
trigger ut5, ut6, ut9

2023-12-11 07:12 UTC, abosii-harness approved these changes

2023-12-11 07:13 UTC, GoelPratyush99 commented
trigger review

2023-12-11 08:22 UTC, merged