[feat]: [CDS-85447]: Allow all expression values for InfrastructureDefinitions List
harness/harness-core pull request #56033
Opened 2023-11-28 05:48 UTC by lovish1999

## Describe your changes
Allow all expression values for InfrastructureDefinitions List instead of only runtime

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-28 05:49 UTC, lovish1999 commented
trigger uts

2023-11-30 08:55 UTC, lovish1999 commented
trigger uts

2023-11-30 09:23 UTC, tchaurasiya requested changes

2023-11-30 09:23 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java
> +    if (environmentYamlV2.getInfrastructureDefinitions().isExpression()
if expression is resolved, will environmentYamlV2.getInfrastructureDefinitions().isExpression() be true?

2023-11-30 09:23 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java
> +    if (isNotEmpty(list) && list.get(0) instanceof String) {
if this object is not yaml of infra i think execution would have failed even before this,
Below validation would not be needed in that case

2023-11-30 09:23 UTC, tchaurasiya commented on 125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStepTest.java
> +    String infraYaml = "identifier: identifier\n"
Can we add test cases in pr description?

2023-11-30 09:23 UTC, tchaurasiya commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java
>      List<EnvironmentMapResponse> environmentMapResponses = new ArrayList<>();
I think in case of single environment too, infraStructureDefinition node can be like below
infraStructureDefinition : <+pipeline.variables.infranode>,
We should test and make changes for that too.

2023-11-30 11:49 UTC, lovish1999 commented on 125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStepTest.java
> +    String infraYaml = "identifier: identifier\n"
ok

2023-11-30 11:50 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java
>      List<EnvironmentMapResponse> environmentMapResponses = new ArrayList<>();
No, in that case, they can directly provide the expression in the identifer

2023-12-01 21:08 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 563 at r2](https://reviewable.io/reviews/harness/harness-core/56033#gh-1410385921:-NkbCXTkCG2HEv-B29S9:b-m559v) ([raw file](https://github.com/harness/harness-core/blob/4f9d6d17a4ace6014b5227d474bcf0e8942223cc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L563)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

No, in that case, they can directly provide the expression in the identifer
</blockquote></details>

but we should support it for completeness, @lovish1999 


<!-- Sent from Reviewable.io -->

2023-12-01 21:10 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 628 at r4](https://reviewable.io/reviews/harness/harness-core/56033#-NkbCyPk5WUlt8TtWeND:-NkbCyPk5WUlt8TtWeNE:brxrqjh) ([raw file](https://github.com/harness/harness-core/blob/2e1865caf95d3b896287ac220044bdd84a3501b9/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L628)):*
> ```Java
>   private void handleExpressionValueForInfrastructureDefinitions(EnvironmentYamlV2 environmentYamlV2) {
>     if (environmentYamlV2 == null || environmentYamlV2.getInfrastructureDefinitions() == null
>         || environmentYamlV2.getInfrastructureDefinitions().fetchFinalValue() == null) {
> ```

probably use ParameterField.isNull() ?


<!-- Sent from Reviewable.io -->

2023-12-01 22:04 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 630 at r2](https://reviewable.io/reviews/harness/harness-core/56033#gh-1410380325:-NkbPFSrA3Ekop08oofN:b-rnph7s) ([raw file](https://github.com/harness/harness-core/blob/4f9d6d17a4ace6014b5227d474bcf0e8942223cc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L630)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

No
</blockquote></details>

there are 2 cases here
- expression is resolved but not to a list
- expression is unresolved

should we not handle them separately ?


<!-- Sent from Reviewable.io -->

2023-12-01 22:10 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 646 at r4](https://reviewable.io/reviews/harness/harness-core/56033#-NkbQh1o3XIRE-ET1ApY:-NkbQh1p4VbCe7RGRp2b:bo9v3n8) ([raw file](https://github.com/harness/harness-core/blob/2e1865caf95d3b896287ac220044bdd84a3501b9/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L646)):*
> ```Java
>         } catch (IOException e) {
>           throw new InvalidYamlException(
>               format("Exception occurred while reading an Infrastructure Definition Yaml [%s]", l), e);
> ```

how does this exception show up in the UI ? is it readable ?


<!-- Sent from Reviewable.io -->

2023-12-01 22:14 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 5 files at r2, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56033)* status: 6 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-05 08:51 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56033)* status: Some of the checks are too old. 6 file(s) to review. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-12-05 09:29 UTC, lovish1999 commented
trigger review

2023-12-05 09:35 UTC, merged