feat: [CDS-85564]: Added new fetch applications endpoint implementation for NR graphql API
harness/harness-core pull request #56040
Opened 2023-11-28 07:28 UTC by ShubhenduP

## Describe your changes
Added a new DSL to get applications for NewRelic GraphQL endpoint, with backward-compatibility.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-28 07:29 UTC, ShubhenduP commented
trigger uts

2023-11-28 10:13 UTC, ShubhenduP commented
trigger uts

2023-11-30 08:48 UTC, ShubhenduP commented
trigger featurenamecheck

2023-11-30 08:52 UTC, ShubhenduP commented
trigger uts

2023-12-06 06:18 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/NewRelicResource.java
> +  public ResponseDTO<List<String>> getNewRelicEndPoints(@QueryParam("accountId") String accountId) {
Is this only used in FE? Else it'd be a breaking change

2023-12-06 06:22 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java
> +  public static final String CVNG_NEWRELIC_NEW_API = "CVNG_NEWRELIC_NEW_API";
This doesn't seemed to be used anywhere. Can we remove this?

2023-12-06 06:24 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/NewRelicServiceImpl.java
> +    if (featureFlagService.isFeatureFlagEnabled(accountId, FeatureName.CV_NEWRELIC_NEW_API.name())) {
@AbhijithHarness @ShubhenduP  Is there a plan to migrate existing customers to new endpoint?

2023-12-06 06:24 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/NewRelicServiceImpl.java
> +    if (featureFlagService.isFeatureFlagEnabled(accountId, FeatureName.CV_NEWRELIC_NEW_API.name())) {
What is the plan to GA this feature?

2023-12-06 06:25 UTC, sribalij requested changes
Can you please share the test plan results in the PR description or what scenarios were tested or link to the test plan?

2023-12-06 06:58 UTC, ShubhenduP commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java
> +  public static final String CVNG_NEWRELIC_NEW_API = "CVNG_NEWRELIC_NEW_API";
Removed this with latest commit

2023-12-06 07:00 UTC, ShubhenduP commented
> Can you please share the test plan results in the PR description or what scenarios were tested or link to the test plan?

@sribalij, This by itself is a small part of the feature so there has been no extensive testing on this specific change. In my local env, I simulated the usecases for these changes, and all produced results as expected.

2023-12-06 12:29 UTC, AbhijithHarness approved these changes

2023-12-06 12:29 UTC, AbhijithHarness commented on srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/NewRelicServiceImpl.java
> +    if (featureFlagService.isFeatureFlagEnabled(accountId, FeatureName.CV_NEWRELIC_NEW_API.name())) {
They will have to change manually, by changing the details in connector. 
This feature flag is just for showing new url options in connector, so that they can configure the new connector. 
We can GA it as soon as all testing is done.

2023-12-06 12:29 UTC, AbhijithHarness commented on srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/delegate/beans/cvng/newrelic/NewRelicUtils.java
> +  private static final String NEW_API_DSL_FILENAME = "newrelic-api-applications.datacollection";
nit: its better to name it NerdGraph_API_DSL_FILENAME than "New"

2023-12-06 12:55 UTC, sandeepharness approved these changes

2023-12-06 17:41 UTC, ShubhenduP commented
trigger ut3

2023-12-06 18:54 UTC, ShubhenduP commented
trigger ut4, ut5, ut6

2023-12-06 19:37 UTC, ShubhenduP commented
trigger ut7, ut8, ut9

2023-12-07 02:37 UTC, ShubhenduP commented
trigger review

2023-12-07 20:53 UTC, sribalij commented on srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/delegate/beans/cvng/newrelic/NewRelicUtils.java
> +  private static final String NEW_API_DSL_FILENAME = "newrelic-api-applications.datacollection";
+1

2023-12-07 20:54 UTC, sribalij approved these changes
On Nit comment from @AbhijithHarness  which i feel would be a good idea too (Naming of variable)

2023-12-11 04:22 UTC, merged