feat:[SSCA-1037]: Added functionality for default configuration.
harness/harness-core pull request #56088
Opened 2023-11-29 03:19 UTC by shash-harness

## Describe your changes
In case if a config is not present , we will send the default one. The naming convention for default configs in resource folder will be in the manner of name_type.json

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-29 03:19 UTC, shash-harness commented
trigger uts

2023-11-29 03:54 UTC, deepharness commented on ssca-manager/service/src/main/resources/sbomqs_scorecard.json
> +          "key": "Structural",
key for category enabled should be "IsEnabled" vale can be true or false

2023-11-29 03:54 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/services/ConfigServiceImpl.java
> +        scorecardConfig.setConfigId(randomAlphabetic(10));
why we are not using uuid for configId ?

2023-11-29 04:00 UTC, shash-harness commented on ssca-manager/service/src/main/resources/sbomqs_scorecard.json
> +          "key": "Structural",
Will update this, got this from the plugin end.

2023-11-29 04:30 UTC, shash-harness commented
trigger uts

2023-11-29 07:13 UTC, shash-harness commented
trigger uts

2023-11-29 10:47 UTC, shash-harness commented
trigger ut2, ut7

2023-11-30 04:50 UTC, deepharness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56088)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ConfigServiceImpl.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/56088#-NkTYYLKDDEBbzud8Nci:-NkTYYLKDDEBbzud8Ncj:b-fmzgt2) ([raw file](https://github.com/harness/harness-core/blob/0546f0d96d332e3651c553ed350346cc3c186649/ssca-manager/service/src/main/java/io/harness/ssca/services/ConfigServiceImpl.java#L94)):*
> ```Java
>         log.error(String.format("Could not fetch the default config for name [%s] and type [%s]", name, type));
>       }
>       if (scorecardConfig != null) {
> ```

Do we need this if ? we can simplify the flow

if(configEntity == null){
//fetch from resource
//save it in db
}

 return toConfigResponse(configEntity);


<!-- Sent from Reviewable.io -->

2023-11-30 08:26 UTC, shash-harness commented
trigger uts

2023-11-30 08:41 UTC, shash-harness commented
trigger uts

2023-11-30 09:33 UTC, deepharness approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56088)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-11-30 10:38 UTC, shash-harness commented
trigger ut6

2023-11-30 12:01 UTC, merged