[feat]: [CDS-85411] : add yamlV2 in override v1 flow
harness/harness-core pull request #56130
Opened 2023-11-29 16:31 UTC by tchaurasiya

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-01 11:52 UTC, lovish1999 commented on 127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/custom/ServiceOverrideRepositoryCustomImpl.java
> +    setYamlV2InRequestedEntity(serviceOverridesEntity);
do we need to do it for create and update calls ?

2023-12-01 11:53 UTC, hingerabhinav reviewed
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56130)* status: 11 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/custom/ServiceOverrideRepositoryCustomImpl.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/56130#-Nk_DSorAOniGbI7oUqC:-Nk_DSorAOniGbI7oUqD:bawbel0) ([raw file](https://github.com/harness/harness-core/blob/2bd1820d88471800d02ae99b61710eba5ea03053/127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/custom/ServiceOverrideRepositoryCustomImpl.java#L81)):*
> ```Java
>       serviceOverridesEntity.setYamlV2(yamlV2);
>     } catch (IOException ex) {
>       log.error("Could not save yamlV2 for override", ex);
> ```

add override information here


<!-- Sent from Reviewable.io -->

2023-12-01 11:56 UTC, lovish1999 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/ServiceOverrideUtilityFacade.java
> -        .spec(ngServiceOverrideConfig == null ? entity.getSpec() : toServiceOverrideSpec(ngServiceOverrideConfig))
Can we then remove the unused toServiceOverrideSpec method in this class ?

2023-12-01 18:58 UTC, yogesh-chauhan requested changes

2023-12-01 18:58 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java
>      return update;
I think naming the field as yamlV2 would be confusing since we would need to keep this always 

How about keeping it as "yaml" itself and using a different field to differentiate "v1" and "v2"

2023-12-04 10:06 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/custom/ServiceOverrideRepositoryCustomImpl.java
> +    setYamlV2InRequestedEntity(serviceOverridesEntity);
There is no update create call in override v1. For override v2 we will make changes post this one

2023-12-04 20:10 UTC, yogesh-chauhan commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java
>      return update;
Yes, only concern is that, will we ever we able to move back to "yaml" from "yamlv2" ?
Lets discuss on a call and close today

2023-12-04 20:12 UTC, yogesh-chauhan reviewed
only 1 comment regarding field naming "yamlv2", rest looks good

2023-12-05 09:13 UTC, yogesh-chauhan reviewed
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56130)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-05 09:49 UTC, tchaurasiya commented on 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java
>      return update;
Discussed offline

2023-12-05 09:51 UTC, tchaurasiya commented
trigger uts

2023-12-05 14:08 UTC, tchaurasiya commented
trigger messagecheck

2023-12-06 03:58 UTC, lovish1999 approved these changes

2023-12-06 04:49 UTC, yogesh-chauhan approved these changes

2023-12-06 05:01 UTC, hingerabhinav approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56130)* status: 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-12-06 06:33 UTC, tchaurasiya commented
trigger review

2023-12-06 06:41 UTC, merged