fix: [CI-10531]: added custom deserializer to support secert in outpu…
harness/harness-core pull request #56165
Opened 2023-11-30 09:57 UTC by sahithibanda01

…t variable

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-05 05:35 UTC, raghavharness requested changes

2023-12-05 05:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/plancreator/V1/RunStepPlanCreatorV1.java
> -                         .outputVariables(
Remove this change

2023-12-05 05:35 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/plancreator/V1/TestStepPlanCreator.java
> -                .outputVariables(
Ditto

2023-12-05 05:35 UTC, raghavharness commented on 332-ci-manager/service/src/test/resources/pipeline_secret_variable_test.yml
> +  name: CI-10345
Are changes needed in this file ?

2023-12-05 05:35 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/serializer/OutputVariableDeserializer.java
> +                .value(ParameterField.<String>builder().value(childNode.get(NAME).toString()).build())
Use Parameter.createValueField

2023-12-05 05:35 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/serializer/OutputVariableDeserializer.java
> +                  .value(ParameterField.<String>builder().value(childNode.get(VALUE).toString()).build())
Use Parameter.createValueField

2023-12-05 05:35 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/serializer/OutputVariableDeserializer.java
> +        if (childNode.get(TYPE).toString().equals("\"String\"")) {
Use const for comparison

2023-12-05 05:35 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/serializer/OutputVariableDeserializer.java
> +        NGVariable ngVariable1 =
Use `ngVariable` instead of `ngVariable1`

2023-12-05 05:35 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/serializer/OutputVariableDeserializer.java
> +                                           SecretRefHelper.createSecretRef(childNode.get(VALUE).toString())))
We need to see if this will work correctly for both secretRef and bash variables

2023-12-05 05:35 UTC, raghavharness commented on 953-yaml-commons/src/main/java/io/harness/yaml/core/variables/OutputNGVariable.java
> +  @ApiModelProperty(allowableValues = NGVariableConstants.STRING_TYPE)
No need of changes in this file right ?

2023-12-05 05:35 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/serializer/OutputVariableDeserializer.java
> +import static io.harness.pms.yaml.YAMLFieldNameConstants.*;
Remove * imports

2023-12-12 07:04 UTC, raghavharness requested changes

2023-12-12 07:04 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
> +import static io.harness.ci.commonconstants.CIExecutionConstants.SECRET_KEY_MINIO_VARIABLE;
Why this import

2023-12-12 07:04 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
> +import io.harness.delegate.task.stepstatus.*;
Remove * imports

2023-12-12 07:04 UTC, raghavharness commented on 879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
> +import io.harness.product.ci.engine.proto.*;
Remove * imports

2023-12-12 07:04 UTC, raghavharness commented on product/ci/addon/docker/Dockerfile.linux.amd64
> -RUN chmod +x /usr/local/bin/ci-addon-linux \
Undo this

2023-12-12 07:04 UTC, raghavharness commented on product/ci/addon/tasks/run.go
> +	outputs 		  []*pb.OutputVariable
Use go fmt ./...

2023-12-12 10:47 UTC, raghavharness requested changes

2023-12-12 10:47 UTC, raghavharness commented on product/ci/addon/go.mod
>  	github.com/spf13/jwalterweatherman v1.1.0 // indirect
Remove

2023-12-12 10:47 UTC, raghavharness commented on product/ci/addon/gojunit/parse.go
> +//   - "Hello, world!"  →  "Hello, world!"
Remove

2023-12-12 10:47 UTC, raghavharness commented on product/ci/addon/gojunit/types.go
> -//   Tests == (Passed + Skipped + Failed + Error)
Remove

2023-12-12 10:47 UTC, raghavharness commented on product/ci/addon/grpc/server.go
> +// AddonServer implements a GRPC server that listens to messages from lite engine
Remove

2023-12-12 10:47 UTC, raghavharness commented on product/ci/addon/testintelligence/java/helper.go
> -
Remove

2023-12-13 08:20 UTC, raghavharness commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/K8InitializeStepUtils.java
> +import io.harness.yaml.utils.NGVariablesUtils;
Remove

2023-12-13 18:25 UTC, sahithibanda01 commented
trigger uts

2023-12-14 07:20 UTC, sahithibanda01 commented
trigger uts

2023-12-14 07:27 UTC, raghavharness submitted a review, later dismissed
LGTM, @harshjain12 please have a look once too.

2023-12-14 08:16 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +        ngVariables.stream()
add isempty  check

2023-12-14 08:16 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +                if (outputVariable instanceof StringNGVariable) {
can you move logic inside if to new method for readability

2023-12-14 08:17 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +                } else if (outputVariable instanceof SecretNGVariable) {
can you move logic inside else to new method for readability

2023-12-14 08:17 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +                } else if (outputVariable instanceof SecretNGVariable) {
can we check type instead of instance of

2023-12-14 08:18 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/SweepingOutputSecretEvaluator.java
> +public class SweepingOutputSecretEvaluator {
can we move it to common utils  
 why to duplicate code

2023-12-14 08:19 UTC, harshjain12 commented on 879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
> +        if (OutputVariable.OutputType.SECRET.toString().equals(outputVariable.getType())
use enum comparision and not string

2023-12-15 12:12 UTC, sahithibanda01 commented
trigger uts

2023-12-15 12:13 UTC, sahithibanda01 commented on 879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
> +        if (OutputVariable.OutputType.SECRET.toString().equals(outputVariable.getType())
outputVariable.getType() is string so we cant compare with enum

2023-12-15 12:13 UTC, sahithibanda01 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/utils/SweepingOutputSecretEvaluator.java
> +public class SweepingOutputSecretEvaluator {
done

2023-12-15 12:14 UTC, sahithibanda01 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +        ngVariables.stream()
done

2023-12-15 12:14 UTC, sahithibanda01 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +                if (outputVariable instanceof StringNGVariable) {
done

2023-12-15 12:14 UTC, sahithibanda01 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +                } else if (outputVariable instanceof SecretNGVariable) {
done

2023-12-15 12:14 UTC, sahithibanda01 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +                } else if (outputVariable instanceof SecretNGVariable) {
done

2023-12-15 12:14 UTC, sahithibanda01 commented on 879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
> +              "${sweepingOutputSecrets.obtain(\"" + outputVariable.getKey() + "\",\"" + encodedValue + "\")}";
done

2023-12-15 14:16 UTC, sahithibanda01 commented
trigger uts

2023-12-15 14:28 UTC, sahithibanda01 commented
trigger uts

2023-12-15 14:54 UTC, sahithibanda01 commented
trigger ut5

2023-12-18 05:16 UTC, harshjain12 commented on 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/serializer/OutputVariableDeserializer.java
> +          NGVariable ngVariable = SecretNGVariable.builder()
Why to always assume string, 
What if user give random value

2023-12-18 05:23 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +
remove empty line

2023-12-18 05:23 UTC, harshjain12 commented on 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/SerializerUtils.java
> +  private static String getOutputVariableFromStringNGVariable(NGVariable ngVariable, String identifier) {
rename getOutputVariableFromStringNGVariable --> getOutputVarFromStringNGVar

similar for other as method name is pretty big

2023-12-18 05:53 UTC, sahithibanda01 commented
trigger uts

2023-12-18 07:21 UTC, sahithibanda01 commented
trigger ut8

2023-12-18 07:21 UTC, sahithibanda01 commented
trigger ut9

2023-12-18 07:28 UTC, sahithibanda01 commented
trigger ut7

2023-12-18 07:41 UTC, merged