Slack notif/remove running stages in action header
harness/harness-core pull request #56160
Opened 2023-11-30 08:30 UTC by naman-goenka

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/56160)

2023-11-30 20:45 UTC, naman-goenka commented
trigger uts

2023-12-04 05:39 UTC, naman-goenka commented
trigger codeformat, messagecheck, pmd

2023-12-04 05:58 UTC, naman-goenka commented
trigger uts

2023-12-04 07:16 UTC, naman-goenka commented
trigger ut5, ut6, ut8, ut9

2023-12-04 10:30 UTC, krishi0408 commented
trigger codeformat

2023-12-04 17:57 UTC, abhinavmittal-harness approved these changes
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56160)* status: 8 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-05 04:45 UTC, sahilhindwani-harness requested changes

2023-12-05 04:45 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java
> +                    ? getCurrentStageName(ambiance, pipelineExecutionSummaryEntity)
where are we getting NPE in notification client. Should we fix there?

2023-12-05 04:45 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/resources/notification_templates/approval/email/plain_text_action_execution.txt
> +subject: "Pipeline ${pipelineName} ${status} for stage: ${currentStageName}."
Will this be a change in behaviour? Do we need to notify customer for the same?

2023-12-05 04:55 UTC, naman-goenka commented on pipeline-service/service/src/main/resources/notification_templates/approval/email/plain_text_action_execution.txt
> +subject: "Pipeline ${pipelineName} ${status} for stage: ${currentStageName}."
This has been discussed and approved with product, it was a bug currently and was indicating false stages.

2023-12-05 04:55 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java
> +                    ? getCurrentStageName(ambiance, pipelineExecutionSummaryEntity)
When trying to substitute with null values in template data. It expects not null values in template data.  
Should we raise a bug here?

2023-12-05 05:16 UTC, naman-goenka commented on pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java
> +                    ? getCurrentStageName(ambiance, pipelineExecutionSummaryEntity)
`io/harness/notification/channeldetails/EmailChannel.java:63`

proto's MapField$MutabilityAwareMap.putAll doesn't expects notNull field

2023-12-05 07:38 UTC, sahilhindwani-harness approved these changes

2023-12-05 07:38 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java
> +                    ? getCurrentStageName(ambiance, pipelineExecutionSummaryEntity)
Yes, please raise a ticket for follow up.

2023-12-05 11:04 UTC, merged