[feat]: [CDS-81942]: adding Deployment Stage Filter Json Creator
harness/harness-core pull request #56172
Opened 2023-11-30 12:16 UTC by markoharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-11-30 15:32 UTC, markoharness commented
trigger uts

2023-11-30 15:54 UTC, markoharness commented
trigger checkstylecodeformat,messagecheck,commonchecks,pmd,gitleaks,codebasehash,compile

2023-11-30 16:00 UTC, markoharness commented
trigger messagecheck

2023-11-30 16:09 UTC, markoharness commented
trigger commonchecks

2023-11-30 16:09 UTC, markoharness commented
trigger pmd

2023-11-30 16:09 UTC, markoharness commented
trigger codebasehash

2023-12-01 07:34 UTC, markoharness commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 510 at r1](https://reviewable.io/reviews/harness/harness-core/56172#-NkYhJZ51dfhi29Wov4w:-NkZH7LE3PYiwl3TjvBJ:b-m9k1bi) ([raw file](https://github.com/harness/harness-core/blob/7f379795b244324af83b9098ab8575a2a99c2ce8/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L510)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar can you review this?
</blockquote></details>

@brijeshdhakar @archit-harness just for context i added this logic here to be able to support cases like this



_Code snippet:_
```Java
spec:
  stages:
    - stage1 (deployment type)
    - stage2 (parallel type)
        spec: 
          stages:
            - substage1
            - substage2 (svc useFromStage stage1)


calling getStageConfig(YamlField yamlField, String stageIdentifier)
where yamlField is substage2 element
and stageIdentifier has value "stage1"
```


<!-- Sent from Reviewable.io -->

2023-12-01 07:35 UTC, markoharness commented
trigger uts

2023-12-01 07:40 UTC, archit-harness requested changes
> Reviewed 20 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56172)* status: 25 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 510 at r1](https://reviewable.io/reviews/harness/harness-core/56172#-NkYhJZ51dfhi29Wov4w:-NkZJ_RQ44s8v4ta2B0h:bjpa1p0) ([raw file](https://github.com/harness/harness-core/blob/7f379795b244324af83b9098ab8575a2a99c2ce8/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L510)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

@brijeshdhakar @archit-harness just for context i added this logic here to be able to support cases like this
</blockquote></details>

yes @markoharness i get why you did, i was asking @brijeshdhakar when we implemented why did we miss this?


<!-- Sent from Reviewable.io -->

2023-12-01 19:29 UTC, yogesh-chauhan requested changes

2023-12-01 19:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java
> +      validateV2(filterCreationContext, deploymentStageConfig);
we can just call it validateSingleService() for now
since we are not supporting serviceV1 in "yaml simplification"

2023-12-01 19:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java
> +      addFiltersFromServiceV2(filterCreationContext, filterBuilder, deploymentStageConfig.getService());
we can just call it "addFiltersForSingleService"

2023-12-01 19:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java
> +          format("serviceConfig or service or services should be present in stage [%s]. Please add it and try again",
"serviceConfig" is not present anymore in deploy stage

2023-12-01 19:29 UTC, yogesh-chauhan commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java
> +          "infrastructure or environment or environments or environmentGroup should be present in stage [%s]. Please add it and try again",
"infrastructure" is not present in deploy stage anymore

2023-12-04 09:24 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/56172#gh-1412479054:-Nko89mdA8RGHY7GqiOA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f379795b244324af83b9098ab8575a2a99c2ce8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java#L131)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can just call it validateSingleService() for now
since we are not supporting serviceV1 in "yaml simplification"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-04 09:24 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java` line 221 at r1](https://reviewable.io/reviews/harness/harness-core/56172#gh-1412480260:-Nko8B5q43wg354k4Lg7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f379795b244324af83b9098ab8575a2a99c2ce8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java#L221)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can just call it "addFiltersForSingleService"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-04 09:24 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java` line 226 at r1](https://reviewable.io/reviews/harness/harness-core/56172#gh-1412481240:-Nko8Cag-mJ80l1zgqpF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f379795b244324af83b9098ab8575a2a99c2ce8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java#L226)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

"serviceConfig" is not present anymore in deploy stage
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-04 09:24 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java` line 250 at r1](https://reviewable.io/reviews/harness/harness-core/56172#gh-1412481541:-Nko8Ddk9F-NkJaFyUZb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f379795b244324af83b9098ab8575a2a99c2ce8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/v1/DeploymentStageFilterJsonCreator.java#L250)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

"infrastructure" is not present in deploy stage anymore 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-04 09:24 UTC, markoharness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56172)* status: 25 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 510 at r1](https://reviewable.io/reviews/harness/harness-core/56172#-NkYhJZ51dfhi29Wov4w:-NkZKFWI1kM1Mg76Tv6K:b-2rscvs) ([raw file](https://github.com/harness/harness-core/blob/7f379795b244324af83b9098ab8575a2a99c2ce8/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L510)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

yes @markoharness i get why you did, i was asking @brijeshdhakar when we implemented why did we miss this?
</blockquote></details>

This issue does not happen with V0 schema.
I copied this method from io.harness.pms.plan.creation.PlanCreatorUtils#getStageConfig when doing the DeploymentStagePlanCreatorV1 changes

And noticed the issue with the logic now, hence i added the fix for it.

If you think there is a better way to do this, let me know.


<!-- Sent from Reviewable.io -->

2023-12-04 17:52 UTC, yogesh-chauhan approved these changes
> Reviewed 22 of 25 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56172)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-05 09:24 UTC, markoharness commented
trigger ut5,ut6,ut8

2023-12-05 09:55 UTC, archit-harness approved these changes
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56172)* status: :shipit: complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-05 10:45 UTC, markoharness commented
trigger review,ut8

2023-12-05 12:21 UTC, merged