[fix]: [CDS-85196]: Bulk Triggers API
harness/harness-core pull request #56250
Opened 2023-12-04 02:35 UTC by vtxorxwitty

## Describe your changes

New API for Enabling/Disabling triggers in bulk. 

Design Spec - https://harness.atlassian.net/browse/CDS-85196?focusedCommentId=619097
Test Plan - https://harness.atlassian.net/browse/CDS-85196?focusedCommentId=621078

API response -  
<img width="1728" alt="Screenshot 2023-12-06 at 4 07 57 PM" src="https://github.com/harness/harness-core/assets/85863680/d12ae5a8-b9a4-4f34-bef2-476dc4579503">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/56250)

2023-12-04 09:53 UTC, vtxorxwitty commented
trigger uts

2023-12-05 10:45 UTC, vtxorxwitty commented
trigger uts

2023-12-05 11:36 UTC, vtxorxwitty commented
trigger uts

2023-12-05 22:53 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 378 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwAcKS9mICR6DaJDd1:-NkwAcKS9mICR6DaJDd2:ba7bjft) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L378)):*
> ```Java
> 
>   @PATCH
>   @Path("/bulk")
> ```

The path doesn't look indicative of what it does. Shouldn't it be more like update-triggers-bulk or bulk/update?


<!-- Sent from Reviewable.io -->

2023-12-05 22:55 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java` line 286 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwBMDyBbwNojqjd8iD:-NkwBMDyBbwNojqjd8iE:bk74l09) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java#L286)):*
> ```Java
>     }
>     if (StringUtils.isBlank(orgIdentifier) && StringUtils.isNotBlank(projectIdentifier)) {
>       throw new InvalidRequestException(
> ```

do we need such combinational validation checks? Can't we simply put null checks for each field?


<!-- Sent from Reviewable.io -->

2023-12-05 22:56 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java` line 286 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwBMDyBbwNojqjd8iD:-NkwBULJ9IP8i4HunO6l:bpavmtw) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java#L286)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

do we need such combinational validation checks? Can't we simply put null checks for each field?
</blockquote></details>

I'm assuming here that triggers exist only on project level ^^


<!-- Sent from Reviewable.io -->

2023-12-05 23:03 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 378 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwAcKS9mICR6DaJDd1:-NkwD5AD5mCsDaa6wUur:buwa8sk) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L378)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The path doesn't look indicative of what it does. Shouldn't it be more like update-triggers-bulk or bulk/update?
</blockquote></details>

Based on the PR, it seems it only enables / disables triggers in bulk. So then better path would be "bulk/toggle" or "toggle-triggers-bulk"


<!-- Sent from Reviewable.io -->

2023-12-05 23:04 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1483 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwDJ9D7lchiL-iQEQ3:-NkwDJ9D7lchiL-iQEQ4:bgki6pa) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1483)):*
> ```Java
> 
>   @Override
>   public TriggerUpdateCount enablingDisablingTriggersInBulk(
> ```

better name could be "toggleTriggersInBulk"


<!-- Sent from Reviewable.io -->

2023-12-06 01:40 UTC, vtxorxwitty reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 13 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 378 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwAcKS9mICR6DaJDd1:-NkwlGg20p3TmBqKHbtc:b-70vigb) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L378)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Based on the PR, it seems it only enables / disables triggers in bulk. So then better path would be "bulk/toggle" or "toggle-triggers-bulk"
</blockquote></details>

bulk/toggle looks more indicative. Will update that.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java` line 286 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwBMDyBbwNojqjd8iD:-NkwlQEyAqoLiwUYDnrJ:b-2lhcek) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java#L286)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I'm assuming here that triggers exist only on project level ^^
</blockquote></details>

@mohitg0795 the aim for this API is to toggle all triggers for diff scopes like account/org/..
We cannot add null checks as you'll have to pass them for every API call. But we don't need the every time. For example, 
If we want to disable all triggers for an organization "abc", the projectIdentifier sent in the API will be null and hence the DB query criteria will be formed. 
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1483 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwDJ9D7lchiL-iQEQ3:-NkwmC0W8sy0c73FlUVP:bdf7zgi) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1483)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

better name could be "toggleTriggersInBulk"
</blockquote></details>

Will update this.


<!-- Sent from Reviewable.io -->

2023-12-06 04:52 UTC, vtxorxwitty commented
trigger uts

2023-12-06 10:42 UTC, vtxorxwitty commented
trigger uts

2023-12-06 13:30 UTC, rathodmeetsatish requested changes

2023-12-06 13:30 UTC, rathodmeetsatish commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java
> +  public long toggleTriggersInBulk(String accountId, boolean enable, Criteria criteria) {
Here we are just updating the enabled field but we should also update yaml, we already have a method to disable trigger in bulk io.harness.ngtriggers.service.impl.NGTriggerServiceImpl#disableTriggers
We can modify this(disableTriggers) method itself to enable/disable triggers in bulk

2023-12-06 13:35 UTC, vtxorxwitty commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java
> +  public long toggleTriggersInBulk(String accountId, boolean enable, Criteria criteria) {
Checked that method already @rathodmeetsatish. The ask here is a bit different and we want it for only Admin users behind the access control. Also Yaml updation is not the ask as we just want an API to toggle the trigger.

2023-12-07 05:16 UTC, rathodmeetsatish requested changes

2023-12-07 05:16 UTC, rathodmeetsatish commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java
> +        list(criteria, PageRequest.of(0, 100000, Sort.by(Sort.Direction.DESC, NGTriggerEntityKeys.createdAt)))
why are we using this and not io.harness.repositories.custom.NGTriggerRepositoryCustomImpl#findAll(org.springframework.data.mongodb.core.query.Criteria) method?

2023-12-07 06:57 UTC, vtxorxwitty commented
trigger ut5, ut6, ut7, ut8, ut9

2023-12-07 09:14 UTC, mohitg0795 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 17 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java` line 286 at r4](https://reviewable.io/reviews/harness/harness-core/56250#-NkwBMDyBbwNojqjd8iD:-Nl2Y8o1EVs-ZGe6nkWX:b-4hvi0m) ([raw file](https://github.com/harness/harness-core/blob/7f2974794e3667d6ebdd6584e32b3d3c10b2d2f2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/TriggerFilterHelper.java#L286)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

@mohitg0795 the aim for this API is to toggle all triggers for diff scopes like account/org/..
We cannot add null checks as you'll have to pass them for every API call. But we don't need the every time. For example, 
If we want to disable all triggers for an organization "abc", the projectIdentifier sent in the API will be null and hence the DB query criteria will be formed.
</blockquote></details>

Got it.


<!-- Sent from Reviewable.io -->

2023-12-07 12:39 UTC, vcalasansh approved these changes
> Reviewed 1 of 11 files at r1, 1 of 3 files at r2, 2 of 11 files at r3, 1 of 7 files at r4, 3 of 9 files at r7, 4 of 9 files at r8, 1 of 2 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56250)* status: 17 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-08 07:41 UTC, merged