techdebt: [CDS-84682]: Remove CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG ff
harness/harness-core pull request #56305
Opened 2023-12-05 00:11 UTC by sribalij

## Describe your changes
Remove CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG from code
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-05 00:11 UTC, sribalij commented
trigger uts

2023-12-05 00:45 UTC, sribalij commented
trigger ut4

2023-12-05 00:58 UTC, sribalij commented
trigger uts

2023-12-05 05:17 UTC, GoelPratyush99 reviewed
The Feature flag is being used in the UI side as well, If the feature is GAed then only lets remove this FF

2023-12-05 05:19 UTC, GoelPratyush99 approved these changes

2023-12-05 05:30 UTC, abhinavsingh1196 requested changes

2023-12-05 05:30 UTC, abhinavsingh1196 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG(
we remove the enum value only once pipeline service is released to prod, after removing all code usages of the FF. so we should do this enum removal later?

2023-12-05 06:01 UTC, abhinavsingh1196 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG(
cc: @abosii-harness

2023-12-05 06:51 UTC, sribalij commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG(
@abhinavsingh1196 ,
Can you please help me understand why that would be the case? This is in manager side of code and not pipeline service right?

2023-12-05 07:39 UTC, abhinavsingh1196 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG(
Looks like this FF should be good, but some FFs which are shared across services have been known to cause problems.
a relevant thread: https://harness.slack.com/archives/C04B88N1HQD/p1687839229511729

2023-12-05 07:42 UTC, sribalij commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG(
Yes. Thanks @abhinavsingh1196 for bringing this up

2023-12-05 08:02 UTC, acasian-harness submitted a review, later dismissed

2023-12-05 08:08 UTC, abosii-harness submitted a review, later dismissed

2023-12-05 09:15 UTC, abhinavsingh1196 commented on 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
> -  CDS_HELM_MULTIPLE_MANIFEST_SUPPORT_NG(
Sure, approving this PR.

2023-12-05 09:15 UTC, abhinavsingh1196 submitted a review, later dismissed

2023-12-06 00:01 UTC, sribalij commented
trigger uts

2023-12-06 06:44 UTC, sribalij commented
/rebase

2023-12-06 06:58 UTC, sribalij commented
trigger uts

2023-12-06 07:33 UTC, GoelPratyush99 approved these changes

2023-12-07 07:08 UTC, sribalij commented
trigger messagecheck

2023-12-07 07:14 UTC, abhinavsingh1196 approved these changes

2023-12-07 07:15 UTC, sribalij commented
trigger review

2023-12-07 07:23 UTC, abosii-harness approved these changes

2023-12-07 19:12 UTC, merged

2023-12-08 14:06 UTC, acasian-harness commented
@sribalij this has a label `do-not-merge` and i see it is merged, can you confirm?