feat: [CDS-82481] Add traffic routing for K8s BG deployment step [Istio provider] - delegate
harness/harness-core pull request #56411
Opened 2023-12-06 10:40 UTC by alebuh

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-06 11:55 UTC, alebuh commented
trigger uts

2023-12-06 16:49 UTC, alebuh commented
trigger uts

2023-12-07 08:18 UTC, alebuh commented
trigger ut1,ut5

2023-12-07 08:56 UTC, markoharness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java
> +public class IstioTrafficRoutingMapper {
The entire logic is based on having only two destinations (which will be the case for bg and canary, but not necessarily for traffic routing).
We should have a one logic that covers all of it.

2023-12-07 10:30 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java
> +public class IstioTrafficRoutingMapper {
I refactored it a little bit so it supports multiple destinations and case when stage and stable are not provided. I added method 
```
getTrafficRoutingManifests(
      IstioProviderConfig k8sTrafficRoutingConfig, String namespace, String releaseName)
```
that should be called in that case.
The one thing here that we need to think of is how to name VirtualService if the stable name is not present. I hardcoded value for now but that should not be a permanent solution. I suppose there should be some identifier that would be used for this (provided by the customer, something similar to the provisionerId for terraform and terragrunt. This would also make it easier to inherit configuration)

2023-12-07 16:47 UTC, alebuh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56411)* status: 20 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/56411#-Nl1gl5J0mIAtHIITtK3:-Nl49mYY1AROhKOqzENV:b-82sfrq) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L62)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: all methods/vars are marked static by @UtilityClass annotation by default :)
</blockquote></details>

Thanks for pointing this out, I didn't know that. Removed static now
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/56411#-Nl1h0vH54a7k7jDdMDu:-Nl49t7PEHNSEqz6six5:b6u6vey) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L63)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: `secondaryService` ?
</blockquote></details>

For BG it will be called stage, and for Canary, it's canary so I named it secondary. However to avoid confusion I renamed it to the stage
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/56411#-Nl1hNgN8zvJOIoODe3D:-Nl4ADi18-Ifmk12Xe7r:buzcxkq) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L97)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: `VS_NAME_MAX_LENGTH - VS_SUFFIX.length()` can be a static constant as well?
</blockquote></details>

Extracted this to the common class
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java` line 118 at r2](https://reviewable.io/reviews/harness/harness-core/56411#-Nl1kLCk80eJtDluW8x9:-Nl4AL-l4LGqcCcG6i1s:b-oicv7z) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java#L118)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: is this unused?
</blockquote></details>

removed now
___
*[`960-api-services/src/main/java/io/harness/k8s/K8sCommandUnitConstants.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/56411#-Nl2BelZ0VKmIvEQ0YBR:-Nl4ANXp0nFRkLXdeTF8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/960-api-services/src/main/java/io/harness/k8s/K8sCommandUnitConstants.java#L19)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: R in routing should be uppercase
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-12-07 16:48 UTC, alebuh commented
trigger uts

2023-12-07 16:51 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java
> +  public final String ISTIO_API_VERSION = "networking.istio.io/v1alpha3";
We should detect version based on available CRDs in customer cluster? Can we look into this option?

2023-12-07 17:05 UTC, abosii-harness requested changes

2023-12-07 17:05 UTC, abosii-harness commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java
> +  public List<TrafficRoutingDestination> getNormalizedDestinations() {
add empty line before for readability

2023-12-07 17:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingCommon.java
> +  public String updatePlaceHoldersIfExist(String host, String stable, String stage) {
add empty line for readability

2023-12-07 17:05 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingCommon.java
> +public class TrafficRoutingCommon {
Please add UT for this class

2023-12-08 09:13 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java
> +  public final String ISTIO_API_VERSION = "networking.istio.io/v1alpha3";
We can execute `kubectl api-versions` and check all available API versions in cluster. I'll take a look at where it's best to place this logic so we can potentially use this information for other things as well

2023-12-08 09:13 UTC, alebuh commented on 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java
> +  public List<TrafficRoutingDestination> getNormalizedDestinations() {
done

2023-12-08 09:14 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingCommon.java
> +public class TrafficRoutingCommon {
done

2023-12-08 17:22 UTC, alebuh commented
trigger uts

2023-12-08 17:26 UTC, alebuh commented
trigger uts

2023-12-08 21:41 UTC, alebuh commented
trigger ut7,ss

2023-12-11 06:45 UTC, alebuh commented
trigger ss

2023-12-11 07:51 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +      final ApiVersionsCommand apiVersionsCommand = kubectl.apiVersions();
Can we do this using java client?

2023-12-11 08:30 UTC, markoharness commented
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java` line 27 at r10](https://reviewable.io/reviews/harness/harness-core/56411#-NlMzWO7-XSq9L6kQhxj:-NlMzWO7-XSq9L6kQhxk:b7qx162) ([raw file](https://github.com/harness/harness-core/blob/befd1e6f9f9204f1022ca5149ffdca2b284f0f36/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java#L27)):*
> ```Java
> 
>   public List<TrafficRoutingDestination> getNormalizedDestinations() {
>     int sum = destinations.stream().mapToInt(TrafficRoutingDestination::getWeight).sum();
> ```

TrafficRoutingDestination.weight is currently of int type (but should actually be Integer).
Having that in mind this particular line of code would throw an NPE when weight is null (not provided by customer).
So this should be taken into consideration.


<!-- Sent from Reviewable.io -->

2023-12-11 08:36 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 67 at r10](https://reviewable.io/reviews/harness/harness-core/56411#-NlN-ebU5JESRD2BvrIC:-NlN-ebU5JESRD2BvrID:b-fqvc1b) ([raw file](https://github.com/harness/harness-core/blob/befd1e6f9f9204f1022ca5149ffdca2b284f0f36/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L67)):*
> ```Java
>       String releaseName, String stableName, String stageName, String apiVersion) {
>     List<TrafficRoute> routes = k8sTrafficRoutingConfig.getRoutes();
>     if (routes.size() != 1) {
> ```

Routes and destinations are being configured separately from each other in yaml.
We should allow multiple routes to be configured and passed here and then apply same destinations (all of them which are configured) to each of the routes.


<!-- Sent from Reviewable.io -->

2023-12-11 08:40 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/56411#gh-1418614079:-NlN0gkA4wCQ0_gLD-Yx:b-ws1ryv) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L55)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

I refactored it a little bit so it supports multiple destinations and case when stage and stable are not provided. I added method 
```
getTrafficRoutingManifests(
      IstioProviderConfig k8sTrafficRoutingConfig, String namespace, String releaseName)
```
that should be called in that case.
The one thing here that we need to think of is how to name VirtualService if the stable name is not present. I hardcoded value for now but that should not be a permanent solution. I suppose there should be some identifier that would be used for this (provided by the customer, something similar to the provisionerId for terraform and terragrunt. This would also make it easier to inherit configuration)
</blockquote></details>

We can change the naming in this case in subsequent PR. Maybe "harness-vs-<hash of destination names>"? We can discuss offline


<!-- Sent from Reviewable.io -->

2023-12-11 08:40 UTC, markoharness reviewed
> Reviewed 1 of 4 files at r5, 3 of 6 files at r7, 7 of 9 files at r8, 8 of 9 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56411)* status: 31 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-11 08:41 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/56411#gh-1418614079:-NlN1KMYE6fhldQL9ng0:b-vcc1t) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L55)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

We can change the naming in this case in subsequent PR. Maybe "harness-vs-<hash of destination names>"? We can discuss offline
</blockquote></details>

*
harness-vs-hash_of_desintation_hosts


<!-- Sent from Reviewable.io -->

2023-12-11 15:11 UTC, alebuh commented
trigger uts

2023-12-11 15:11 UTC, alebuh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56411)* status: 39 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/56411#gh-1418614079:-NlNN0cV21E0T3UTmIHY:bwa1b69) ([raw file](https://github.com/harness/harness-core/blob/0a7c4577de9a47b3d69240ef5c1d4cea8f0275b6/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L55)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

*
harness-vs-hash_of_desintation_hosts
</blockquote></details>

for now let's leave it as it is, and we can change it in future by adding some identifier
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java` line 67 at r10](https://reviewable.io/reviews/harness/harness-core/56411#-NlN-ebU5JESRD2BvrIC:-NlO6sPpCe7XiOmtV98V:b-72t2jr) ([raw file](https://github.com/harness/harness-core/blob/befd1e6f9f9204f1022ca5149ffdca2b284f0f36/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingMapper.java#L67)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Routes and destinations are being configured separately from each other in yaml.
We should allow multiple routes to be configured and passed here and then apply same destinations (all of them which are configured) to each of the routes.
</blockquote></details>

Changed now, so we can have multiple routes
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java` line 3338 at r10](https://reviewable.io/reviews/harness/harness-core/56411#gh-1422046495:-NlO6xw8DHWlh_LyXSdR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/befd1e6f9f9204f1022ca5149ffdca2b284f0f36/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java#L3338)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we do this using java client?
</blockquote></details>

done
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java` line 27 at r10](https://reviewable.io/reviews/harness/harness-core/56411#-NlMzWO7-XSq9L6kQhxj:-NlOQjUaA7cLmvkC_TXV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/befd1e6f9f9204f1022ca5149ffdca2b284f0f36/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/trafficrouting/K8sTrafficRoutingConfig.java#L27)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

TrafficRoutingDestination.weight is currently of int type (but should actually be Integer).
Having that in mind this particular line of code would throw an NPE when weight is null (not provided by customer).
So this should be taken into consideration.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-12-11 15:20 UTC, markoharness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56411)* status: 39 file(s) to review. 1 change requests. 10. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-11 16:00 UTC, alebuh commented
trigger uts

2023-12-11 16:14 UTC, markoharness submitted a review, later dismissed
> Reviewed 13 of 18 files at r11, 2 of 2 files at r12, 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56411)* status: 39 file(s) to review. 1 change requests. 10. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-11 16:31 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public Set<String> getAvailableApisFromCluster(K8sInfraDelegateConfig k8sInfraDelegateConfig, String workingDir,
Is this method required? What is the difference between this and getApiVersions?

2023-12-11 16:51 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java
> +  public Set<String> getAvailableApisFromCluster(K8sInfraDelegateConfig k8sInfraDelegateConfig, String workingDir,
Not really, I just thought that helper base class was a place for it. But you are right it increases complexity without a reason. Removed now

2023-12-11 16:51 UTC, alebuh commented
trigger uts

2023-12-11 19:33 UTC, alebuh commented
trigger ut4,ut5

2023-12-11 21:19 UTC, alebuh commented
trigger ut4

2023-12-12 06:38 UTC, abosii-harness approved these changes

2023-12-12 07:06 UTC, markoharness approved these changes

2023-12-12 07:10 UTC, alebuh commented
trigger review

2023-12-12 07:13 UTC, merged