feat: [CDS-86336]: Add pipeline, stage, step delegate selectors in parentInfo
harness/harness-core pull request #56470
Opened 2023-12-07 08:23 UTC by shalini-agr

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-07 09:39 UTC, shalini-agr commented
trigger uts

2023-12-08 08:00 UTC, utkarshchoubey-harness submitted a review, later dismissed

2023-12-12 05:22 UTC, archit-harness requested changes
> Reviewed 7 of 16 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 444 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRLls2E1yqiM9Tl-2:-NlRRLls2E1yqiM9Tl-3:b-r0tdhg) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L444)):*
> ```Java
> 
>   public List<String> getDelegates(YamlNode node) {
>     YamlField delegatesField = node.getField("delegate");
> ```

can we use const here?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 451 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRcNg7X7_m29tIQbC:-NlRRcNg7X7_m29tIQbD:b-f3me59) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L451)):*
> ```Java
>       }
>     } catch (Exception ex) {
>       throw new InvalidRequestException("Invalid Yaml", ex);
> ```

can we have better error message with string.format of ex message
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 487 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRXXmDOZaNQeec9jK:-NlRRXXmDOZaNQeec9jL:beo5vz2) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L487)):*
> ```Java
>   }
> 
>   ParameterField<List<String>> getDelegatesParameterField(YamlNode delegateYamlNode) throws Exception {
> ```

can we handle <+input>
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 497 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRki16EmXRKiRpXCN:-NlRRki16EmXRKiRpXCO:bwrjjx1) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L497)):*
> ```Java
>       if (ParameterField.isNotNull(delegateV1ParameterField)) {
>         delegateListV1ParameterField =
>             ParameterField.createValueField(new ArrayList<>(List.of(delegateV1ParameterField.getValue())));
> ```

if delegate is <+input> then it would be list of null?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRS6Wm0vl1ycFU0-bu:-NlRS6Wm0vl1ycFU0-bv:b-y17l5n) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java#L98)):*
> ```Java
>     List<String> delegates = PlanCreatorUtilsV1.getDelegates(config.getNode());
>     List<FailureConfigV1> stepGroupFailureStrategies = PlanCreatorUtilsV1.getFailureStrategies(config.getNode());
>     if (delegates != null && stepGroupFailureStrategies != null) {
> ```

can we create a map of dependency based on delegate and failure strategy present or not? current code has duplicate lines



_Code quote:_
```Java
delegates != null && stepGroupFailureStrategies != null
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 91 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRSZJw7pQBG35rZbvj:-NlRSZJw7pQBG35rZbvk:b-xtaego) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L91)):*
> ```Java
>   }
> 
>   List<String> getPipelineDelegates(YamlField field) {
> ```

if delegates are not present can we not add this to parentInfo and handle if parentInfo not present then consider empty


<!-- Sent from Reviewable.io -->

2023-12-12 05:54 UTC, shalini-agr commented
trigger uts

2023-12-12 06:27 UTC, archit-harness reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-12 06:30 UTC, shalini-agr commented
trigger ut9

2023-12-12 06:40 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 17 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 444 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRLls2E1yqiM9Tl-2:-NlRjFa34z_piYuxMI-k:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L444)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we use const here?
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRS6Wm0vl1ycFU0-bu:-NlRjUjFEt3oQjkn2ewW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group/GroupPlanCreatorV1.java#L98)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we create a map of dependency based on delegate and failure strategy present or not? current code has duplicate lines
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 91 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRSZJw7pQBG35rZbvj:-NlRj1My2lWueGM7h-vj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L91)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if delegates are not present can we not add this to parentInfo and handle if parentInfo not present then consider empty
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-12 06:42 UTC, shalini-agr commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 497 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRki16EmXRKiRpXCN:-NlRkY_C3KMChaWAluXa:b-ifllmm) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L497)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if delegate is <+input> then it would be list of null?
</blockquote></details>

if it's <+input> and the value is not provided in the run form then ParameterField.isNotNull would be false and it won't come to this point, right?


<!-- Sent from Reviewable.io -->

2023-12-12 07:16 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 17 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 487 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRXXmDOZaNQeec9jK:-NlRsWuW9s1TcBns4mQb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L487)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we handle <+input>
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 497 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRki16EmXRKiRpXCN:-NlRsYF23vBID_PG--QZ:broj9pk) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L497)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

if it's <+input> and the value is not provided in the run form then ParameterField.isNotNull would be false and it won't come to this point, right?
</blockquote></details>

handled the case of <+input> by adding a check for expression


<!-- Sent from Reviewable.io -->

2023-12-12 07:46 UTC, archit-harness requested changes
> Reviewed 1 of 3 files at r4, 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 17 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 62 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRyIf7AwFwO3jS-gS9:-NlRyIf7AwFwO3jS-gSA:b11ca1v) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L62)):*
> ```Java
>     List<String> delegates = null;
>     if (ParameterField.isNotNull(stageNode.getDelegate())) {
>       if (stageNode.getDelegate().isExpression()) {
> ```

to be discuss
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 72 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRyMZZ5oAJaCqghqWO:-NlRyMZZ5oAJaCqghqWP:bchs1oo) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L72)):*
> ```Java
>       stageFailureStrategies = stageNode.getFailure().getValue();
>     }
>     if (delegates != null) {
> ```

use EmptyPredicate



_Code quote:_
```Java
delegates != null
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 497 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRki16EmXRKiRpXCN:-NlRz0CSAl6mBd0YS3uK:ba9rba6) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L497)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

handled the case of <+input> by adding a check for expression
</blockquote></details>

yet to be discussed in channel
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 447 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRybL42BFRNJpV-rLi:-NlRybL42BFRNJpV-rLj:b-b8muhv) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L447)):*
> ```Java
>     ParameterField<List<String>> delegatesParameterField = null;
>     try {
>       if (delegatesField != null) {
> ```

add a UT for this case
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 459 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRzCKA5wB7KDGw9n1W:-NlRzCKA5wB7KDGw9n1X:bkuyzq3) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L459)):*
> ```Java
>     } else {
>       return null;
>     }
> ```

check if needed
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 96 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRzQAs31Ee23wDLj4c:-NlRzQAs31Ee23wDLj4d:b-9b479t) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L96)):*
> ```Java
>   HarnessStruct buildParentInfo(YamlField config) {
>     List<String> delegates = getPipelineDelegates(config);
>     if (delegates != null) {
> ```

emptyPredicate



_Code quote:_
```Java
delegates != null
```


<!-- Sent from Reviewable.io -->

2023-12-12 15:08 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 26 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 72 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRyMZZ5oAJaCqghqWO:-NlSLXomAI0R-Kc1P3FE:bl166qa) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use EmptyPredicate
</blockquote></details>

used ParameterField.isNotNull()
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 451 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRcNg7X7_m29tIQbC:-NlSLHrEDgWy6og1H6HQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L451)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we have better error message with string.format of ex message
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 459 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRzCKA5wB7KDGw9n1W:-NlTZFWT5GJfFPF8Gi1l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L459)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check if needed
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 96 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRzQAs31Ee23wDLj4c:-NlSLNzjEhM71_LZqDC7:b-jn0ai7) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L96)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

emptyPredicate
</blockquote></details>

used ParameterField.isNotNull


<!-- Sent from Reviewable.io -->

2023-12-13 05:38 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 26 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 62 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRyIf7AwFwO3jS-gS9:-NlWfcODBWxlGhB87JWV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

to be discuss
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 497 at r3](https://reviewable.io/reviews/harness/harness-core/56470#-NlRRki16EmXRKiRpXCN:-NlWfdpr82axdCf4JuQD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e52a6778972c4e4674f957f78580bbdcbb06d797/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L497)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

yet to be discussed in channel
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 06:06 UTC, shalini-agr reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 26 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 447 at r6](https://reviewable.io/reviews/harness/harness-core/56470#-NlRybL42BFRNJpV-rLi:-NlWmAk82I9k1lMKT4G8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d805813cc903afb00bc55f57e809cb76de084c5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L447)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add a UT for this case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 06:11 UTC, archit-harness requested changes
> Reviewed 2 of 16 files at r7, 1 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 28 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/v1/AbstractStageNodeV1.java` line 50 at r9](https://reviewable.io/reviews/harness/harness-core/56470#-NlWmh513pqoaEyR_vmx:-NlWmh513pqoaEyR_vmy:b-sq00yj) ([raw file](https://github.com/harness/harness-core/blob/997eb3c508e4bfdd73743e2734afbd5a140e2a64/953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/v1/AbstractStageNodeV1.java#L50)):*
> ```Java
>   ParameterField<String> when;
>   NGVariableV1Wrapper variables;
>   @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY) ParameterField<List<TaskSelectorYaml>> delegates;
> ```

why we are changing to this? i think we should keep list only


<!-- Sent from Reviewable.io -->

2023-12-13 06:14 UTC, shalini-agr commented
*[`953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/v1/AbstractStageNodeV1.java` line 50 at r9](https://reviewable.io/reviews/harness/harness-core/56470#-NlWmh513pqoaEyR_vmx:-NlWniPh2RpqcSx6x1Np:bobjsvv) ([raw file](https://github.com/harness/harness-core/blob/997eb3c508e4bfdd73743e2734afbd5a140e2a64/953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/v1/AbstractStageNodeV1.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are changing to this? i think we should keep list only
</blockquote></details>

if we remove this, we won't be able to support a single fixed value for delegates as a string in yaml 
eg:
`delegates: localdelegate`


<!-- Sent from Reviewable.io -->

2023-12-13 07:17 UTC, archit-harness requested changes
> Reviewed 8 of 16 files at r7, 7 of 11 files at r8, 1 of 2 files at r9, 3 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 28 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 517 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWv6gk4oPUTrMpufnS:-NlWv6gk4oPUTrMpufnT:b-m7ir97) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L517)):*
> ```Java
>   }
> 
>   public static void appendDelegateSelectorsToSpecParameters(StepSpecType stepSpecType, PlanCreationContext ctx) {
> ```

discussed offline on adding simplified overloaded method taking version 
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java` line 45 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWxky74wyrEHbZrZua:-NlWxky74wyrEHbZrZub:b2d4jan) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java#L45)):*
> ```Java
>   String desc;
>   ParameterField<String> when;
>   @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY) ParameterField<List<String>> delegates;
> ```

remove this field
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 130 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWyr6J0pM63YeldzNH:-NlWyr6J0pM63YeldzNI:bop6ctn) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L130)):*
> ```Java
>     }
> 
>     try {
> ```

add UT and decsription here why its needed earlier
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 504 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWzT2S6v4i8XwIuz1q:-NlWzT2S6v4i8XwIuz1r:bkl17m6) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L504)):*
> ```Java
>   }
> 
>   ParameterField<List<TaskSelectorYaml>> getDelegatesParameterField(YamlNode delegateYamlNode) throws Exception {
> ```

can we keept it close to getDelegates
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 31 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWyAtf3NUCfqmJLpgG:-NlWyAtf3NUCfqmJLpgH:b2d4jan) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L31)):*
> ```Java
>     stepBuilder.name(stepElementConfig.getName());
>     stepBuilder.id(stepElementConfig.getId());
>     stepBuilder.delegateSelectors(stepElementConfig.getDelegates());
> ```

remove this field
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/v1/PmsAbstractStepNodeV1.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlX0cKc5xdrd2U_EQTq:-NlX0cKc5xdrd2U_EQTr:bpc0oji) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/v1/PmsAbstractStepNodeV1.java#L38)):*
> ```Java
>   public StepElementParametersV1 getStepParameters(PlanCreationContext ctx, KryoSerializer kryoSerializer) {
>     StepElementParametersV1Builder stepBuilder = StepParametersUtilsV1.getStepParameters(this);
>     StepUtils.appendDelegateSelectorsToSpecParameters(getSpec(), ctx, kryoSerializer);
> ```

as discussed, method name will change
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 84 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlX0s121lOUKF9_UKv_:-NlX0s1384KX16YEIj_k:b-vld75u) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L84)):*
> ```Java
>     if (parentInfo != null) {
>       return Dependency.newBuilder()
>           .setNodeMetadata(HarnessStruct.newBuilder().putData(
> ```

can we reduce duplicate code using builder
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepInfoV1.java` line 59 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlX16mpAx0hWBjEBd_g:-NlX16mpAx0hWBjEBd_h:b-gkl6gi) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepInfoV1.java#L59)):*
> ```Java
> 
>   @Override
>   public void setDelegateSelectors(ParameterField<List<TaskSelectorYaml>> delegateSelectors) {
> ```

rename this to delegates



_Code quote:_
```Java
delegateSelectors
```


<!-- Sent from Reviewable.io -->

2023-12-13 08:06 UTC, shalini-agr commented
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java` line 45 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWxky74wyrEHbZrZua:-NlX2TeF3O2ZvrON8tHa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/953-yaml-commons/src/main/java/io/harness/plancreator/steps/v1/AbstractStepNodeV1.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove this field
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 08:07 UTC, shalini-agr commented
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java` line 504 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWzT2S6v4i8XwIuz1q:-NlX2djd4xSCbKDMhNU_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/PlanCreatorUtilsV1.java#L504)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we keept it close to getDelegates
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 08:07 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java` line 31 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWyAtf3NUCfqmJLpgG:-NlX2qXT55xGKGeP8SHr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/common/v1/StepParametersUtilsV1.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove this field
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 08:07 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/v1/PmsAbstractStepNodeV1.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlX0cKc5xdrd2U_EQTq:-NlX2tAb1LxAd1hVo0Xf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/v1/PmsAbstractStepNodeV1.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed, method name will change
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 08:07 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java` line 84 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlX0s121lOUKF9_UKv_:-NlX7kUZ0S3P7UmRwDf2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelinePlanCreatorV1.java#L84)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we reduce duplicate code using builder
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 08:07 UTC, shalini-agr commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepInfoV1.java` line 59 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlX16mpAx0hWBjEBd_g:-NlX3Vjr--6VMt6XCe5u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/HttpStepInfoV1.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename this to delegates
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 08:07 UTC, shalini-agr commented
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 130 at r10](https://reviewable.io/reviews/harness/harness-core/56470#-NlWyr6J0pM63YeldzNH:-NlXCs558mjRiDx-IwXR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74e14c3912104d282fb4d950b2979e0a4b7066a7/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L130)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add UT and decsription here why its needed earlier
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 08:42 UTC, shalini-agr commented
trigger uts

2023-12-13 09:23 UTC, archit-harness approved these changes
> Reviewed 8 of 12 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 32 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-13 10:05 UTC, brijeshdhakar submitted a review, later dismissed
> Reviewed 1 of 16 files at r1, 2 of 4 files at r3, 7 of 16 files at r7, 6 of 11 files at r8, 3 of 4 files at r10, 8 of 12 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-14 07:09 UTC, yogesh-chauhan commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 551 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb8ipv3_4Mu2Nc_sk2:-Nlb8ipv3_4Mu2Nc_sk3:be5ev1p) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L551)):*
> ```Java
>         break;
>       default:
>         return null;
> ```

I would say, don't directly return from here. Keep a single return statement at the end of the method. Here you can set your objectOptional to be Optional.empty()
and also make objectOptional as "final"


<!-- Sent from Reviewable.io -->

2023-12-14 07:09 UTC, yogesh-chauhan commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 536 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9CgECsqq6-JWRF1C:-Nlb7tW9-YJ7T-VyE3Rr:b9yoew) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L536)):*
> ```Java
>   private static ParameterField<List<TaskSelectorYaml>> getDelegateSelectorsFromParentInfo(
>       PlanCreationContext ctx, String key, KryoSerializer kryoSerializer) {
>     Optional<Object> objectOptional;
> ```

nit: can make this final and put a better name for objectOptional


<!-- Sent from Reviewable.io -->

2023-12-14 07:10 UTC, yogesh-chauhan commented
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java` line 30 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9LCq6G2sJ4jiGUR5:-Nlb9LCrDuf9xH_f4cG9:b-ki5vc6) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java#L30)):*
> ```Java
>   public final String SET_STARTING_NODE_ID = "setStartingNodeId";
>   public final String IS_INSIDE_PARALLEL_NODE = "isInsideParallelNode";
>   public final String PIPELINE_DELEGATES = "pipelineDelegate";
> ```

should this be plural ? "pipelineDelegate" and same below also


<!-- Sent from Reviewable.io -->

2023-12-14 07:11 UTC, yogesh-chauhan commented
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 135 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9dZi5ieKKrzVYNv-:-Nlb9dZi5ieKKrzVYNv0:b-mb5gpt) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L135)):*
> ```Java
>       // valueDeserializer.deserialize() deserializes it to a list of size 1 with element abc,def.
>       // That is why this if block is needed here before valueDeserializer.deserialize().
>       if (JsonUtils.isJsonList(text)) {
> ```

what all existing behaviour can this change ?


<!-- Sent from Reviewable.io -->

2023-12-14 07:15 UTC, yogesh-chauhan reviewed
> Reviewed 1 of 16 files at r1, 2 of 4 files at r3, 7 of 16 files at r7, 5 of 11 files at r8, 2 of 4 files at r10, 6 of 12 files at r11, 4 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-14 07:31 UTC, shalini-agr commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 536 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9CgECsqq6-JWRF1C:-NlbCERU1luTuC7Po6yz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L536)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: can make this final and put a better name for objectOptional
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-12-14 07:32 UTC, shalini-agr commented
*[`878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java` line 551 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb8ipv3_4Mu2Nc_sk2:-NlbCFCI9JwT6UXy-gvg:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L551)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I would say, don't directly return from here. Keep a single return statement at the end of the method. Here you can set your objectOptional to be Optional.empty()
and also make objectOptional as "final"
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-12-14 07:32 UTC, shalini-agr commented
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java` line 30 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9LCq6G2sJ4jiGUR5:-NlbCUtS9sIjlq5Ed0Ek:b-5g9o7c) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java#L30)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should this be plural ? "pipelineDelegate" and same below also
</blockquote></details>

yes, done


<!-- Sent from Reviewable.io -->

2023-12-14 07:32 UTC, shalini-agr commented
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 135 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9dZi5ieKKrzVYNv-:-NlbCcxd25ZTrfK4bHcY:btji744) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L135)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what all existing behaviour can this change ?
</blockquote></details>

The change in behavior will only be observed for the fields of type ParameterField<List<?>> and with annotation @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY) that would allow a single value as array

earlier, if the value of this field was ["abc", "def"], it would get deserialized to a list of a single element, now it will be deserialized as a list of two elements abc and def.

without the above annotation, it was already deserializing to the list of two elements, because valueDeserializer.deserialize(p, ctxt) used to throw error and then in the catch we had a handling of `if (referenceType.getRawClass() == List.class) ` which used to correctly convert it to array of two elements. 

so, only one case was missing which is handled now.


<!-- Sent from Reviewable.io -->

2023-12-14 08:19 UTC, shalini-agr commented
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 135 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9dZi5ieKKrzVYNv-:-NlbP3TSAm8ZiSuXZkT2:b-ycjq4y) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L135)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

The change in behavior will only be observed for the fields of type ParameterField<List<?>> and with annotation @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY) that would allow a single value as array

earlier, if the value of this field was ["abc", "def"], it would get deserialized to a list of a single element, now it will be deserialized as a list of two elements abc and def.

without the above annotation, it was already deserializing to the list of two elements, because valueDeserializer.deserialize(p, ctxt) used to throw error and then in the catch we had a handling of `if (referenceType.getRawClass() == List.class) ` which used to correctly convert it to array of two elements. 

so, only one case was missing which is handled now.
</blockquote></details>

There's just one field in v0 that has above annotation but it's not parameterField, so, there shouldn't be any impact of this change in v0


<!-- Sent from Reviewable.io -->

2023-12-14 08:20 UTC, shalini-agr commented
trigger uts

2023-12-14 08:20 UTC, yogesh-chauhan commented
*[`970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java` line 135 at r12](https://reviewable.io/reviews/harness/harness-core/56470#-Nlb9dZi5ieKKrzVYNv-:-NlbPRDYAfi4dL2nY6x9:b-bo4pyd) ([raw file](https://github.com/harness/harness-core/blob/a206405e816a827aecb1c01edb333c88c4694c9b/970-ng-commons/src/main/java/io/serializer/jackson/ParameterFieldDeserializer.java#L135)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

There's just one field in v0 that has above annotation but it's not parameterField, so, there shouldn't be any impact of this change in v0
</blockquote></details>

Sound good
```
@JsonFormat(with = JsonFormat.Feature.ACCEPT\_SINGLE\_VALUE\_AS\_ARRAY) List<ResourceLinkage> data;
```


<!-- Sent from Reviewable.io -->

2023-12-14 08:20 UTC, yogesh-chauhan approved these changes
> Reviewed 1 of 11 files at r8, 2 of 12 files at r11, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: 2 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-14 08:35 UTC, archit-harness approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56470)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-14 08:47 UTC, shalini-agr commented
trigger review

2023-12-14 09:28 UTC, merged