Move Project API
harness/harness-core pull request #56588
Opened 2023-12-11 04:56 UTC by adiyaar24

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-12 10:41 UTC, adiyaar24 commented
trigger uts

2023-12-12 12:48 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java
> +  @InternalApi
Hidden is sufficient, if we mark internal we woyuld need service to service token to call this API even from POSTMAN, thanks

2023-12-13 05:28 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +      @ProjectIdentifier String identifier, @OrgIdentifier String destinationOrgIdentifier) {
Why the `@OrgIdentifier` is needed for destinationOrg? thanks

2023-12-13 05:31 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +  public boolean moveProject(String accountIdentifier, @OrgIdentifier String orgIdentifier,
This API should ideally take `ScopeInfo` as input and not the current `orgIdentifier`, thanks

2023-12-13 05:31 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +    Optional<Organization> organizationOptional = organizationService.get(accountIdentifier, destinationOrgIdentifier);
Please update to use organizationService.get with `scopeInfo`

2023-12-13 05:32 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +    Optional<Project> duplicateProjectCheck = get(accountIdentifier, destinationOrgIdentifier, identifier);
Same as here, lets try to use internal get with `scopeInfo`, thanks

2023-12-13 05:33 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +          USER_SRE);
change `USER_SRE` to `USER` thanks

2023-12-13 05:34 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +    Optional<Project> optionalProject = get(accountIdentifier, orgIdentifier, identifier);
same as above, use scopeInfo, thanks

2023-12-13 05:35 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +            identifier, orgIdentifier, destinationOrgIdentifier));
Lets also log source 'scopeUniqueId' and destination 'scopeUniqueId' is available, thanks

2023-12-13 05:36 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +    Optional<Project> duplicateProjectCheck = get(accountIdentifier, destinationOrgIdentifier, identifier);
For destination scopeInfo might not work, so ignore if not applicable, thanks

2023-12-13 05:37 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java
> +          description = "This is the updated org identifier") @NotNull @Valid MoveProjectRequest moveProjectRequest) {
Add `@Context ScopeInfo scopeinfo` as a resource param and that will be propagated to the service, thanks

2023-12-13 05:38 UTC, pbarapatre10 commented on 960-ng-core-beans/src/main/java/io/harness/ng/core/dto/MoveProjectRequest.java
> +public class MoveProjectRequest {
nit: add `OwnedBy(PL)`, thanks

2023-12-13 06:44 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +    Optional<Project> duplicateProjectCheck = get(accountIdentifier, destinationOrgIdentifier, identifier);
But I am checking at the destination org Identifier, so thereby I need to do this way

2023-12-13 09:37 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56588)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 523 at r3](https://reviewable.io/reviews/harness/harness-core/56588#-NlXX3Xc9LuaMeQyC6cO:-NlXX3Xc9LuaMeQyC6cP:b-4ym7uu) ([raw file](https://github.com/harness/harness-core/blob/23f88dba7b7920b55c066b00242158644e99da61/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L523)):*
> ```Java
>         Project updatedProject = projectRepository.save(project);
>         addToScopeInfoCache(updatedProject);
>         setupProject(Scope.of(accountIdentifier, destinationOrgIdentifier, project.getIdentifier()));
> ```

What this method will do internally?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 525 at r3](https://reviewable.io/reviews/harness/harness-core/56588#-NlXX0mhAuPqeYL5ff2j:-NlXX0mhAuPqeYL5ff2k:b-x7cf0u) ([raw file](https://github.com/harness/harness-core/blob/23f88dba7b7920b55c066b00242158644e99da61/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L525)):*
> ```Java
>         setupProject(Scope.of(accountIdentifier, destinationOrgIdentifier, project.getIdentifier()));
>         log.info(String.format(
>             "Project with identifier [%s] and source orgIdentifier [%s] was successfully migrated to [%s] orgIdentifier",
> ```

Moved instead of migrated
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 527 at r3](https://reviewable.io/reviews/harness/harness-core/56588#-NlXWv3k29qAA8dUhlb-:-NlXWv3k29qAA8dUhlb0:b43pyng) ([raw file](https://github.com/harness/harness-core/blob/23f88dba7b7920b55c066b00242158644e99da61/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L527)):*
> ```Java
>             "Project with identifier [%s] and source orgIdentifier [%s] was successfully migrated to [%s] orgIdentifier",
>             identifier, orgIdentifier, destinationOrgIdentifier));
>         outboxService.save(new ProjectUpdateEvent(
> ```

Should this be projectMoveEvent?
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/MoveProjectRequest.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/56588#gh-1424869763:-NlXXRxw0rpDPDX-rZmA:bdp0dqv) ([raw file](https://github.com/harness/harness-core/blob/a2ebf948ffd6a4d22a006b0bb509fbc8787b2385/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/MoveProjectRequest.java#L20)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: add `OwnedBy(PL)`, thanks
</blockquote></details>

Shouldn't this also contain accountIdentifier, sourceOrgIdentifier?


<!-- Sent from Reviewable.io -->

2023-12-13 09:40 UTC, ankit-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56588)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 491 at r3](https://reviewable.io/reviews/harness/harness-core/56588#-NlXY9so2ZouGBSG3XMg:-NlXY9so2ZouGBSG3XMh:bzepnej) ([raw file](https://github.com/harness/harness-core/blob/23f88dba7b7920b55c066b00242158644e99da61/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L491)):*
> ```Java
>   public boolean moveProject(String accountIdentifier, @OrgIdentifier String orgIdentifier,
>       @ProjectIdentifier String identifier, @OrgIdentifier String destinationOrgIdentifier) {
>     Optional<Organization> organizationOptional = organizationService.get(accountIdentifier, destinationOrgIdentifier);
> ```

destinationOrgOptional


<!-- Sent from Reviewable.io -->

2023-12-13 09:44 UTC, ankit-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56588)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 527 at r3](https://reviewable.io/reviews/harness/harness-core/56588#-NlXYryj6QeMPzQuibHI:-NlXYryj6QeMPzQuibHJ:b-4ok00j) ([raw file](https://github.com/harness/harness-core/blob/23f88dba7b7920b55c066b00242158644e99da61/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L527)):*
> ```Java
>             "Project with identifier [%s] and source orgIdentifier [%s] was successfully migrated to [%s] orgIdentifier",
>             identifier, orgIdentifier, destinationOrgIdentifier));
>         outboxService.save(new ProjectUpdateEvent(
> ```

How will this event show up in Audit YAML diff? Update to orgIdentifier or update to parentUniqueId field? Do we expose uniqueId and parentUniqueId in YAMLs?


<!-- Sent from Reviewable.io -->

2023-12-14 06:26 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +
nit: should we trigger `ProjectCreate` event and let it take care of this? I'm fine to have it here for now, thanks

2023-12-14 06:26 UTC, pbarapatre10 submitted a review, later dismissed

2023-12-14 08:41 UTC, adiyaar24 commented on 120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
> +
Created a handleProjectMove , will discuss in call

2023-12-14 08:57 UTC, adiyaar24 commented
trigger uts

2023-12-14 09:37 UTC, pbarapatre10 approved these changes

2023-12-14 09:39 UTC, merged