feat: [SSCA-1077]: Implement SSCA Event Handler
harness/harness-core pull request #56587
Opened 2023-12-11 04:14 UTC by reetika04

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-11 11:30 UTC, inderschera approved these changes

2023-12-11 11:46 UTC, reetika04 commented
trigger uts

2023-12-11 11:47 UTC, inderschera approved these changes

2023-12-11 14:53 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/events/handler/SSCAArtifactEventHandler.java
>      this.objectMapper = NG_DEFAULT_OBJECT_MAPPER;
where are we using this objectMapper?

2023-12-11 14:53 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/events/handler/SSCAArtifactEventHandler.java
> +                    sscaArtifactCreatedEvent.getArtifact().getOrchestrationId(), Pageable.unpaged())
we should save it in bathes , it will increase the memory of ssca-manager also put a strain in mongo if we are reading large SBOM

2023-12-11 14:53 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/events/handler/SSCAArtifactEventHandler.java
> +        searchService.updateArtifact(sscaArtifactUpdatedEvent.getArtifact());
we have to add few enrichment in artefact https://harness.atlassian.net/wiki/spaces/SSCS/pages/21477196126/Query+Filtering#Latest-Tag-for-artifact%3A

2023-12-12 05:12 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/ssca/events/handler/SSCAArtifactEventHandler.java
>      this.objectMapper = NG_DEFAULT_OBJECT_MAPPER;
This is the default object mapper to read the contents of the event.

2023-12-14 04:57 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/ssca/events/handler/SSCAArtifactEventHandler.java
> +        searchService.updateArtifact(sscaArtifactUpdatedEvent.getArtifact());
This will not be necessary, invalid flag and sorting should take care of this already.

2023-12-14 06:02 UTC, reetika04 commented
trigger uts

2023-12-14 06:20 UTC, deepharness requested changes
> Reviewed 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56587)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/helpers/BatchProcessor.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/56587#-NlauMEn6iGrFA70HUDq:-NlauMEn6iGrFA70HUDr:b-4bygje) ([raw file](https://github.com/harness/harness-core/blob/7cbb3c16469f7a2bfd8148f5d538534d94ff7e87/ssca-manager/service/src/main/java/io/harness/ssca/helpers/BatchProcessor.java#L32)):*
> ```Java
>   private final Class<T> entityClass;
> 
>   //    @Inject
> ```

remove commented code
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/jobs/ElkMigrationJob.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/56587#-NlaybrX8avCf6QxfzIf:-NlaybrX8avCf6QxfzIg:bo7t6vo) ([raw file](https://github.com/harness/harness-core/blob/7cbb3c16469f7a2bfd8148f5d538534d94ff7e87/ssca-manager/service/src/main/java/io/harness/ssca/jobs/ElkMigrationJob.java#L79)):*
> ```Java
>       throw e;
>     }
>     migrationEntity.setStatus(SUCCESS);
> ```

you have to update migration entity within distributed lock , or else pods can rerun migration 


<!-- Sent from Reviewable.io -->

2023-12-14 07:19 UTC, reetika04 commented
trigger uts

2023-12-14 07:40 UTC, reetika04 commented
trigger uts

2023-12-14 09:05 UTC, deepharness approved these changes
> Reviewed 1 of 2 files at r2, 5 of 10 files at r3, 1 of 4 files at r4, 2 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56587)* status: 1. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-12-15 03:47 UTC, reetika04 commented
trigger uts

2023-12-15 03:51 UTC, inderschera approved these changes

2023-12-15 03:59 UTC, merged