feat: [SSCA-1030]: Artifact search ELK Queries
harness/harness-core pull request #56585
Opened 2023-12-11 03:39 UTC by reetika04

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-11 11:21 UTC, reetika04 commented
trigger uts

2023-12-11 11:40 UTC, inderschera approved these changes

2023-12-12 04:23 UTC, deepharness requested changes

2023-12-12 04:23 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactServiceQueryBuilder.java
> +      String accountId, String orgIdentifier, String projectIdentifier, ArtifactListingRequestBody body) {
Can we avoid taking request body ? As it may change , also ArtifactQueryBuilder is the entry point for any ELK query execution , which can be called from other parts of domain

2023-12-12 04:23 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactServiceQueryBuilder.java
> +      String accountId, String orgIdentifier, String projectIdentifier, ArtifactListingRequestBody body) {
We can create a dto which takes serachTerm, licenseFilter & componentFilter

2023-12-12 04:23 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/search/ElasticSearchQueryBuilder.java
> +public class ElasticSearchQueryBuilder {
Nice abstraction

2023-12-12 04:23 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactServiceQueryBuilder.java
> +public class ArtifactServiceQueryBuilder {
why we want to name it as service , it looks redundent , ArtifactQueryBuilder itself is explanatory

2023-12-12 04:23 UTC, deepharness commented on ssca-manager/service/src/main/java/io/harness/ssca/search/SearchServiceImpl.java
> +      ArtifactListingRequestBody body, Pageable pageable) {
We can take FilterDto here

2023-12-12 06:20 UTC, reetika04 commented
trigger uts

2023-12-12 06:28 UTC, reetika04 commented
trigger uts

2023-12-12 07:04 UTC, reetika04 commented
trigger uts

2023-12-12 07:07 UTC, dhruv-harness submitted a review, later dismissed

2023-12-12 07:14 UTC, reetika04 commented
trigger uts

2023-12-12 07:56 UTC, deepharness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56585)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/56585#-NlRzK9PDrZGqbE9F1Cd:-NlRzK9PDrZGqbE9F1Ce:b-ck849r) ([raw file](https://github.com/harness/harness-core/blob/b2dd60da242b261e63660e4259d6ea757a593509/ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java#L53)):*
> ```Java
>   }
> 
>   public Query getQuery(String accountId, String orgIdentifier, String projectIdentifier, ArtifactFilter body) {
> ```

can we call it artifactFiler instead of body


<!-- Sent from Reviewable.io -->

2023-12-12 07:57 UTC, reetika04 commented
trigger uts

2023-12-12 09:08 UTC, deepharness approved these changes
> Reviewed 3 of 6 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56585)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-12 09:20 UTC, merged