fix: [CDS-85942]: improving logs
harness/harness-core pull request #56589
Opened 2023-12-11 05:01 UTC by TarunUba1

## Describe your changes
Reason: There was a case where customer was not sending identifier with manifest which was throwing a bad exception, instead we will throw a general exception to prevent this scenario.
##Test
<img width="664" alt="Screenshot 2023-12-11 at 10 31 23 AM" src="https://github.com/harness/harness-core/assets/106597485/991c092f-c8c7-4ac5-88a6-18517becc109">
<img width="890" alt="Screenshot 2023-12-11 at 10 31 12 AM" src="https://github.com/harness/harness-core/assets/106597485/837848cb-221b-41be-81f0-38b2d32fd434">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-11 11:18 UTC, TarunUba1 commented
trigger uts

2023-12-11 11:20 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      throw new InvalidRequestException("File/Folder path must be present");
could this be misleading during other exceptions?

2023-12-12 09:35 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      throw new InvalidRequestException("File/Folder path must be present");
saveManifestOutcome has one functionality which is to consume manifests into sweepingOutput, the other option is to add it in executionsweepingoutput was is but used everywhere,
The actual error is coming when we try to get identifier and map it butt its not there
RecastOrchestrationUtils.toJson(value) throws this error actually

2023-12-12 11:36 UTC, abhinavsingh1196 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      throw new InvalidRequestException("File/Folder path must be present");
Also, we should probably throw hint/explanation exception here. I feel that this message by itself is not enough

2023-12-12 11:36 UTC, abhinavsingh1196 commented
Small comment above, please check.

2023-12-12 12:32 UTC, abosii-harness requested changes

2023-12-12 12:32 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      throw new InvalidRequestException("File/Folder path must be present");
This doesn't work

2023-12-12 15:28 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java
> +      throw new InvalidRequestException("File/Folder path must be present");
yeah i cross checked the YAML of customer then realized it was for service input

2023-12-12 15:39 UTC, TarunUba1 commented
trigger uts

2023-12-13 06:51 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeValidator.java
> +      throw new InvalidRequestException("File/Folder path must be present");
Can we make this error a bit more generic, we could actually do the next thing:
- Wrap hasValue with another method that will have as input parameterField, fieldName and manifestId
- Once the exception is caught, we can provide the next error message:
Incorrect value {parameterField.getValue()} for field {fieldName} in manifest {manifestId}. 

With some hints like:
- Check provided value for {fieldName} in manifest {manifestId}
-  If using runtime input make sure that valid input is provided for manifest with {manifestId}. Input yaml should contain identifier {manifestId}

2023-12-13 10:18 UTC, TarunUba1 commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeValidator.java
> +      throw new InvalidRequestException("File/Folder path must be present");
i have added  a hint, couldn't introduce NestedException cause it was not working correctly.

2023-12-13 10:31 UTC, TarunUba1 commented
trigger uts

2023-12-13 11:05 UTC, abosii-harness commented on 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeValidator.java
> +      + "Valid input with an identifier is required in the YAML file for proper manifest processing during runtime.";
please add a space either after . or before Valid
Also this message may be confusing, let's make sure that hint is applicable in context of runtime input

2023-12-13 11:18 UTC, GoelPratyush99 approved these changes

2023-12-13 11:38 UTC, TarunUba1 commented
trigger uts

2023-12-13 12:05 UTC, TarunUba1 commented
trigger ut6, ut7, ut8

2023-12-13 12:49 UTC, TarunUba1 commented
trigger uts

2023-12-13 12:54 UTC, abosii-harness approved these changes

2023-12-13 13:20 UTC, TarunUba1 commented
trigger review, messagecheck

2023-12-13 13:24 UTC, merged