feat:[CDS-83858]: helm chart for debezium-service
harness/harness-core pull request #56590
Opened 2023-12-11 05:01 UTC by Aninditaa-ch

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-11 05:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=56590) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=56590) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=56590) it.</sub>

2023-12-14 07:34 UTC, arya-harness commented on debezium-service/charts/README.md
> +# access-control
install and run helm-docs to generate the readme, it currently contains access control

2023-12-14 07:40 UTC, arya-harness requested changes

2023-12-14 07:40 UTC, arya-harness commented on debezium-service/charts/templates/config.yaml
> +  CF_CLIENT_API_KEY: {{.Values.CF_CLIENT_API_KEY}}
use external secrets and helper functions

2023-12-14 07:40 UTC, arya-harness commented on debezium-service/charts/templates/config.yaml
> +  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{.Values.EVENTS_FRAMEWORK_REDIS_SENTINELS}}
Are all of these values required for debezium service?

2023-12-14 07:48 UTC, arya-harness commented on debezium-service/charts/templates/deployment.yaml
> +              path: /api/health
set those values in values.yaml

2023-12-26 06:04 UTC, arya-harness commented on debezium-service/build/container/Dockerfile-debezium-service-multistage
> +# Copyright 2022 Harness Inc. All rights reserved.
To be reviewed by @Vbhatia20

2023-12-26 06:05 UTC, arya-harness commented on debezium-service/chart/templates/config.yaml
> +  IS_ENABLED_PIPELINE: {{.Values.global.IS_ENABLED_PIPELINE | quote}}
dont use .Values.global for ordinary configuration
global is reserved for configuration reused accross multiple charts.

use .Values.config instead

2023-12-26 06:07 UTC, arya-harness commented on debezium-service/chart/templates/config.yaml
> +  MONGODB_CONNECTION_STRING_PLG: {{.Values.global.MONGODB_CONNECTION_STRING_PLG | quote}}
use helper function for mongo and move it to deployment.yaml
all database secrets and string are in deployment.yaml to be reffered directly from a secret or external secret

2023-12-26 06:08 UTC, arya-harness commented on debezium-service/chart/templates/config.yaml
> +  IS_ENABLED_SSCA: {{.Values.global.IS_ENABLED_SSCA | quote}}
use .Values.global.ssca.enabled. There are charts which uses this flag

2023-12-26 06:08 UTC, arya-harness commented on debezium-service/chart/templates/config.yaml
> +  MONGODB_SSL_ENABLED_SSCA: {{.Values.global.MONGODB_SSL_ENABLED_SSCA | quote}}
use mongo helper

2023-12-26 06:08 UTC, arya-harness commented on debezium-service/chart/templates/config.yaml
> +  MONGODB_CONNECTION_STRING_SSCA: {{.Values.global.MONGODB_CONNECTION_STRING_SSCA | quote}}
use mongo helper and move to deployment.yaml

2023-12-26 06:10 UTC, arya-harness commented on debezium-service/chart/values.yaml
> +  httpGet:
use a enabled flag and set it to false, in ng-prod-manifests its not using livenessprobre

2023-12-26 06:11 UTC, arya-harness commented on debezium-service/chart/templates/config.yaml
> +  MONGODB_CONNECTION_STRING_APPLICATIONS: {{.Values.global.MONGODB_CONNECTION_STRING_APPLICATIONS | quote}}
check if this is a mongodb uri, and move to deployment.yaml if necessary

2023-12-27 11:10 UTC, Aninditaa-ch commented
trigger uts

2023-12-28 05:37 UTC, Aninditaa-ch commented
trigger uts

2023-12-28 05:50 UTC, Aninditaa-ch commented
trigger messagecheck

2023-12-28 05:53 UTC, Aninditaa-ch commented
trigger uts

2023-12-28 05:58 UTC, Aninditaa-ch commented
trigger gitleaks

2023-12-28 06:53 UTC, arya-harness submitted a review, later dismissed

2023-12-28 06:59 UTC, arya-harness approved these changes

2023-12-28 07:07 UTC, jyotiraval submitted a review, later dismissed

2023-12-28 07:10 UTC, Aninditaa-ch commented
trigger uts

2023-12-28 07:10 UTC, sahilhindwani-harness commented
trigger gitleaks

2023-12-28 08:25 UTC, Aninditaa-ch commented
trigger uts

2023-12-28 09:55 UTC, arya-harness approved these changes

2023-12-28 09:56 UTC, jyotiraval approved these changes

2023-12-29 06:20 UTC, Aninditaa-ch commented
trigger uts

2023-12-29 08:15 UTC, merged