fix:[CDS-85856]: Update instanceSyncPerpetualTaskInfoDTO when helm chart info is updated
harness/harness-core pull request #56617
Opened 2023-12-11 10:37 UTC by GoelPratyush99

## Describe your changes
Update instanceSyncPerpetualTaskInfoDTO every time when the helm chart info is updated. We are getting the latest helm chart information from deployment summary and we need to update same in instanceSyncPerpetualTaskInfoDTO

Earlier we were only updating the instanceSyncPerpetualTaskInfoDTO for new deployments this resulted in old values of helm chart info during auto scaling.

The changes have been for InstanceSync V1 / V2 and for K8s / Native Helm deployment of helm charts.

## Test Plan

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-11 11:13 UTC, GoelPratyush99 commented
trigger uts

2023-12-12 12:30 UTC, namantalaycha10 commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +      updateDeploymentInfoListAndConnectorId(
Please Dont use this method , this giving wrong indication that we are updating connectorID in instanceSyncPerpetualTaskInfoDTO instead of helm chart info

2023-12-12 13:15 UTC, GoelPratyush99 commented
trigger uts

2023-12-12 14:42 UTC, abosii-harness requested changes

2023-12-12 14:42 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +    deploymentInfoDetailsDTOList.stream()
Do we actually require to this manual update or we can replace the deployment info directly?

2023-12-13 05:04 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +      updateDeploymentInfoListAndConnectorId(
done

2023-12-13 09:34 UTC, GoelPratyush99 commented
trigger uts

2023-12-13 09:37 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/K8sInstanceSyncHandler.java
> +    deploymentInfoDetailsDTOList.stream()
Yes, For k8s deployment with new releaseName. A deploymentInfoDTO got appended to this list.

Also, for native helm with new deployment a new deploymentInfoDTO is appended to the list.

 Hence to be on a safer side it is best to check the list and then update it instead of replacing the list with new deployment.

2023-12-13 09:37 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/service/instancesynchandler/AbstractInstanceSyncHandler.java
> +  public boolean isHelmChartInfoNotUpdatedInInstanceSyncPerpetualTaskInfo(
done

2023-12-18 08:00 UTC, abosii-harness requested changes
What about NativeHelm?

2023-12-18 08:00 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +    if (isInstanceSyncPerpetualTaskInfoUpdated) {
Why we need this? We're not going to bundle release details with PT task in V2

2023-12-18 08:00 UTC, abosii-harness commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +  private void updateDeploymentInfoListAndConnectorId(AbstractInstanceSyncHandler abstractInstanceSyncHandler,
What is the idea behind this empty method?

2023-12-18 09:02 UTC, GoelPratyush99 commented on 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
> +  private void updateDeploymentInfoListAndConnectorId(AbstractInstanceSyncHandler abstractInstanceSyncHandler,
removed it. Thanks

2023-12-18 09:04 UTC, GoelPratyush99 commented
> What about NativeHelm?

For native helm with new deployment a new deploymentInfoDTO is appended to the list. Hence we do not require this fix.

2023-12-18 09:04 UTC, GoelPratyush99 commented
trigger uts

2023-12-18 10:48 UTC, GoelPratyush99 commented
trigger uts

2023-12-18 12:53 UTC, abosii-harness approved these changes

2023-12-19 05:02 UTC, namantalaycha10 approved these changes

2023-12-19 05:03 UTC, GoelPratyush99 commented
trigger review

2023-12-19 05:07 UTC, merged