fix: [CDS-86427]: A new internal Api to be used for template api
harness/harness-core pull request #56665
Opened 2023-12-12 11:34 UTC by abhinavmittal-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-12 13:37 UTC, abhinavmittal-harness commented
trigger uts

2023-12-12 13:39 UTC, abhinavmittal-harness commented on template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +  @ApiOperation(value = "Gets a merged template by identifier", nickname = "Get Resolved Template")
Gets a resolved template by identifier

2023-12-12 13:41 UTC, abhinavmittal-harness commented on template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +  @Operation(operationId = "getResolvedTemplate", description = "Returns a Template by Identifier based on userInput",
Returns the merged template by identifier

2023-12-12 13:42 UTC, abhinavmittal-harness commented on template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +      summary = "Fetch a Resolved Template",
Fetch merged template by identifier

2023-12-12 13:42 UTC, abhinavmittal-harness commented on template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +        ApiResponse(responseCode = "default", description = "Returns pipeline YAML")
Returns Template DTO with original yaml and resolved Yaml

2023-12-12 20:19 UTC, mohitg0795 commented on template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java
> +  @ApiOperation(value = "Gets a merged template by identifier", nickname = "Get Resolved Template")
If its fetching merged template, then why not name the path as well accordingly. Currently from the path, it looks like just getting a template.

2023-12-13 04:11 UTC, abhinavmittal-harness commented
trigger uts

2023-12-13 06:08 UTC, utkarshchoubey-harness approved these changes

2023-12-13 09:03 UTC, sahilhindwani-harness commented
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 724 at r3](https://reviewable.io/reviews/harness/harness-core/56665#-NlXPeLS5dgqeKIaXwNE:-NlXPeLS5dgqeKIaXwNF:bdgrcbh) ([raw file](https://github.com/harness/harness-core/blob/4570a89ad269eecdbe526a9290e245560d7bc6da/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java#L724)):*
> ```Java
>   @Hidden
>   ResponseDTO<TemplateResponseDTO>
>   getTemplateByIdentifier(@Parameter(description = PipelineResourceConstants.ACCOUNT_PARAM_MESSAGE, required = true)
> ```

nit: can we rename this to something like getResolvedTemplate?


<!-- Sent from Reviewable.io -->

2023-12-13 09:06 UTC, sahilhindwani-harness requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56665)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-13 09:42 UTC, utkarshchoubey-harness approved these changes
lgtm!

2023-12-13 09:48 UTC, abhinavmittal-harness commented
trigger messagecheck

2023-12-13 19:11 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56665)* status: 5 file(s) to review. 2 change requests. 1 of 2 approvals obtained. 

___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 711 at r4](https://reviewable.io/reviews/harness/harness-core/56665#-NlZ_U2I-RCFbMXYv_Ao:-NlZ_U2I-RCFbMXYv_Ap:b-qjuebr) ([raw file](https://github.com/harness/harness-core/blob/a1d28752643a9ce4c1b9a9f9ccb9dc82004753e4/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java#L711)):*
> ```Java
> 
>   @POST
>   @Path("/getResolvedTemplate/{templateIdentifier}")
> ```

path naming should be kebab case


<!-- Sent from Reviewable.io -->

2023-12-13 19:11 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56665)* status: 5 file(s) to review. 2 change requests. 1 of 2 approvals obtained. 

___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 722 at r4](https://reviewable.io/reviews/harness/harness-core/56665#-NlZ_oFt0FLPKN8pGEA2:-NlZ_oFt0FLPKN8pGEA3:b-iu277z) ([raw file](https://github.com/harness/harness-core/blob/a1d28752643a9ce4c1b9a9f9ccb9dc82004753e4/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java#L722)):*
> ```Java
>   @Timed
>   @ResponseMetered
>   @Hidden
> ```

If its hidden, then lets not put any swagger annotations for easier readability. No swagger annotation makes sense for hidden API.


<!-- Sent from Reviewable.io -->

2023-12-13 19:13 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56665)* status: 5 file(s) to review. 2 change requests. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java` line 578 at r4](https://reviewable.io/reviews/harness/harness-core/56665#-NlZa93-2i0vFjoXPn3B:-NlZa93-2i0vFjoXPn3C:b-sa79x0) ([raw file](https://github.com/harness/harness-core/blob/a1d28752643a9ce4c1b9a9f9ccb9dc82004753e4/template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java#L578)):*
> ```Java
>       String templateIdentifier, String versionLabel, boolean deleted, GitEntityFindInfoDTO gitEntityBasicInfo,
>       MergeTemplateRequestDTO mergeTemplateRequestDTO, boolean loadFromFallbackBranch, String loadFromCache) {
>     ResponseDTO<TemplateResponseDTO> templateResponseDTO = get(accountId, orgId, projectId, templateIdentifier,
> ```

lets not put any functional logic in resource layer. All functional logic should go to service layer only.


<!-- Sent from Reviewable.io -->

2023-12-14 04:51 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56665)* status: 5 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 711 at r4](https://reviewable.io/reviews/harness/harness-core/56665#-NlZ_U2I-RCFbMXYv_Ao:-NlaeKec5Tgomx0ymcxI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1d28752643a9ce4c1b9a9f9ccb9dc82004753e4/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java#L711)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

path naming should be kebab case
</blockquote></details>

Done.
___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 722 at r4](https://reviewable.io/reviews/harness/harness-core/56665#-NlZ_oFt0FLPKN8pGEA2:-NlaeL4o59U6j_tYz_4y:b-d1eih4) ([raw file](https://github.com/harness/harness-core/blob/a1d28752643a9ce4c1b9a9f9ccb9dc82004753e4/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java#L722)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If its hidden, then lets not put any swagger annotations for easier readability. No swagger annotation makes sense for hidden API.
</blockquote></details>

removed swagger 2 annotation
___
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java` line 578 at r4](https://reviewable.io/reviews/harness/harness-core/56665#-NlZa93-2i0vFjoXPn3B:-NlaeNoGEdC7vg9TyqhP:b-uu1cjo) ([raw file](https://github.com/harness/harness-core/blob/a1d28752643a9ce4c1b9a9f9ccb9dc82004753e4/template-service/service/src/main/java/io/harness/template/resources/NGTemplateResourceImpl.java#L578)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets not put any functional logic in resource layer. All functional logic should go to service layer only.
</blockquote></details>

UNfortunately the methods we are using are present int he resource layer.
For me to move the buisness logic to service layer would require larger refactoring.
And considering this is a time sensitive CFD for now  I would prefer keeping it this way..
We can create a tech debt to handle this refactoring later.


<!-- Sent from Reviewable.io -->

2023-12-14 07:02 UTC, mohitg0795 approved these changes
> Reviewed 2 of 5 files at r1, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56665)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-14 11:50 UTC, sahilhindwani-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56665#-:-Nlc9WPo7RGM1oVfJSF3:bnfp4nl)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-14 11:51 UTC, abhinavmittal-harness commented
trigger review

2023-12-14 11:51 UTC, abhinavmittal-harness commented
trigger uts

2023-12-14 12:55 UTC, abhinavmittal-harness commented
trigger ut6,ut7,ut8,ut9

2023-12-14 13:37 UTC, abhinavmittal-harness commented
trigger ut6,ut7,ut8

2023-12-14 14:23 UTC, abhinavmittal-harness commented
trigger ut6

2023-12-14 15:21 UTC, merged