[fix]: [CDS-86026]: Telemetry for BulkToggleTriggers API
harness/harness-core pull request #56675
Opened 2023-12-12 13:42 UTC by vtxorxwitty

## Describe your changes
Added telemetry for bulk-toggle-triggers API. 

Tested via amplitude - 
<img width="1616" alt="Screenshot 2023-12-13 at 12 52 54 PM" src="https://github.com/harness/harness-core/assets/85863680/4d255545-92c0-450b-9077-f8a452000569">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/56675)

2023-12-12 13:59 UTC, vtxorxwitty commented
trigger uts

2023-12-13 05:48 UTC, sarthakkasat commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java
> +    triggerTelemetryHelper.sendBulkToggleTriggersApiEvent(accountIdentifier,
Can we directly pass bulkTriggersResponseDTO in method instead of individual parameters, as the parameters might increase in future?

2023-12-13 05:48 UTC, sarthakkasat commented on 970-telemetry-beans/src/main/java/io/harness/telemetry/helpers/InstrumentationConstants.java
> +  public static final String TRIGGER_TOGGLE = "trigger_toggle";
Can we move these constants to TriggerTelemetryHelper class as they will only be used in that class?

2023-12-13 05:48 UTC, sarthakkasat commented on pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java
> +        bulkTriggersRequestDTO.getFilters().getPipelineIdentifier(), bulkTriggersRequestDTO.getFilters().getType(),
Shall we add null checks here?

2023-12-13 07:37 UTC, vtxorxwitty commented
trigger uts

2023-12-13 08:33 UTC, abhinavmittal-harness requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56675)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/instrumentation/TriggerTelemetryHelper.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/56675#-NlXIcLf9ZO-Hpzai_cA:-NlXIcLf9ZO-Hpzai_cB:b-osd1rt) ([raw file](https://github.com/harness/harness-core/blob/f4e9bde841d41320ae0567e3a3fbabdc2a56a8c8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/instrumentation/TriggerTelemetryHelper.java#L61)):*
> ```Java
>   private CompletableFuture<Void> publishBulkToggleTriggersApiInfo(String eventName, String accountId, String orgId,
>       String projectId, String pipelineId, String type, boolean enable, long timeTaken, long modifiedCount) {
>     HashMap<String, Object> eventPropertiesMap = new HashMap<>();
> ```

Can we add tests here, regarding properties containing the given keys


<!-- Sent from Reviewable.io -->

2023-12-13 09:00 UTC, sarthakkasat approved these changes

2023-12-13 09:01 UTC, abhinavmittal-harness approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56675)* status: 4 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-12-13 09:02 UTC, vtxorxwitty commented
trigger uts

2023-12-13 09:05 UTC, abhinavmittal-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56675)* status: 4 file(s) to review. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/instrumentation/TriggerTelemetryHelper.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/56675#-NlXPuKb7USmqEZO_4kp:-NlXPuKb7USmqEZO_4kq:byr566p) ([raw file](https://github.com/harness/harness-core/blob/18039243cd3d0a3f561f029dcc3507bc022f40c2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/instrumentation/TriggerTelemetryHelper.java#L52)):*
> ```Java
>     }
> 
>     if (bulkTriggersRequestDTO.getData() != null) {
> ```

nit: comment that request dto can't be null


<!-- Sent from Reviewable.io -->

2023-12-13 11:25 UTC, vtxorxwitty commented
trigger review

2023-12-13 11:30 UTC, merged