feat:SSCA[1058]: Added access control for remediation tracker
harness/harness-core pull request #56676
Opened 2023-12-12 13:53 UTC by humanshu2002

## Describe your changes
Add access control client and config in SSCA, and access for Remediation Tracker.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-12 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=56676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=56676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=56676) it.</sub>

2023-12-12 14:33 UTC, humanshu2002 commented
trigger uts

2023-12-12 15:18 UTC, humanshu2002 commented
trigger uts

2023-12-12 17:27 UTC, humanshu2002 commented
trigger uts

2023-12-12 19:15 UTC, pranay-harness submitted a review, later dismissed

2023-12-13 05:07 UTC, humanshu2002 commented
trigger uts

2023-12-13 05:54 UTC, reetika04 requested changes

2023-12-13 05:54 UTC, reetika04 commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +      name: SSCA Remediation Tracker
The role name isn't supposed to be SSCA Remediation Tracker. We can add this as `SSCA Remediation Admin` or `SSCA Remediation Manager` Please check with @KapilDigani

2023-12-13 05:54 UTC, reetika04 commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +        - ssca_remediation_tracker_close
Why do we need both create and update, only have update single permission. We can have a single manage permission as well.

2023-12-13 05:54 UTC, reetika04 commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +    - identifier: _ssca_remediation_tracker
Update the version of this file.

2023-12-13 05:54 UTC, reetika04 commented on access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml
> +  - identifier: ssca_remediation_tracker_create
Update the version for the file

2023-12-13 05:54 UTC, reetika04 commented on ssca-manager/chart/templates/config.yaml
>    {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
Update the chart version as well.

2023-12-13 08:07 UTC, humanshu2002 commented
trigger uts

2023-12-13 08:12 UTC, reetika04 commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +        - account
please remove changes in this file

2023-12-13 08:20 UTC, humanshu2002 commented on access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
> +        - account
it was this only earlier

2023-12-14 05:40 UTC, humanshu2002 commented
trigger uts

2023-12-14 07:04 UTC, humanshu2002 commented
trigger ut6

2023-12-14 07:11 UTC, humanshu2002 commented
trigger uts

2023-12-14 07:31 UTC, humanshu2002 commented
trigger ut5,ut6,ut7,ut8,ut9,ut4

2023-12-14 07:33 UTC, reetika04 requested changes

2023-12-14 07:33 UTC, reetika04 commented on dockerization/manager/scripts/replace_configs.sh
> +replace_key_value accessControlClientConfig.enableAccessControl "$ACCESS_CONTROL_ENABLED"
This is not where the replace_configs go @humanshu2002 . Please update this in ssca-manager/build/container/scripts/replace_configs.sh

2023-12-14 07:57 UTC, reetika04 approved these changes

2023-12-14 08:01 UTC, humanshu2002 commented
trigger uts

2023-12-14 08:45 UTC, arya-harness approved these changes

2023-12-14 09:16 UTC, jyotiraval approved these changes

2023-12-14 09:56 UTC, humanshu2002 commented
trigger ut8,ut0

2023-12-14 10:10 UTC, humanshu2002 commented
trigger ut0

2023-12-14 12:35 UTC, humanshu2002 commented
triggger ut8

2023-12-14 12:42 UTC, humanshu2002 commented
trigger ut8

2023-12-14 15:19 UTC, humanshu2002 commented
trigger ut8

2023-12-14 16:38 UTC, merged