feat: [CDS-86300]: Added the endpoint to update multiple version in git
harness/harness-core pull request #56680
Opened 2023-12-12 16:01 UTC by shivamnegi94

## Describe your changes
Added the Endpoint to update multiple Git files for template.

Test Cases:

Verified the Multiple files are getting updated
Verified the error for invalid version

**Project Endpoint:**
`curl --location --request POST 'https://localhost:8181/template/api/v1/org/default/project/TestProject/git-metadata/TestRemote?accountIdentifier=kmpySmUISimoRrJL6NL73w&projectIdentifier=TestProject&orgIdentifier=default&projectIdentifier=TestProject&connectorRef=GitShivamtest&repoName=shivam-test&filePath=.harness%2FTestTemp1234_v1.yaml' \
--header 'Accept: */*' \
--header 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50SWQiOiJrbXB5U21VSVNpbW9SckpMNk5MNzN3IiwiYXV0aFRva2VuIjoiSFhUclhVMWtIZ1RFV0oyZWFGd0xBTU1leTVySGlNRWoiLCJpc3MiOiJIYXJuZXNzIEluYyIsIm5hbWUiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwidXNySWQiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwiZXhwIjoxNzAyNDc5NzI3LCJlbnYiOiIiLCJ0eXBlIjoiVVNFUiIsImlhdCI6MTcwMjM5MzMyNywiZW1haWwiOiJhZG1pbkBoYXJuZXNzLmlvIiwidXNlcm5hbWUiOiJBZG1pbiJ9.dfryd5ShIaaAg712-utiYaVYGL93o8t6XxU8xZNPoNQ' \
--header 'Connection: keep-alive' \
--header 'Cookie: jenkins-timestamper-offset=-19800000; __stripe_mid=e58251a3-2210-41f2-8657-486019b5e50d041a7b; _hjSessionUser_3650791=eyJpZCI6ImY1YjBiOTAwLWQzMjYtNWFiNC05N2YzLTdmNDVkZWEzNWRiMyIsImNyZWF0ZWQiOjE2OTcyMDQwNzE5NzUsImV4aXN0aW5nIjp0cnVlfQ==; intercom-id-iw4sgfzm=d2cdcdce-b415-40ce-8534-ed9e5d6360ef; intercom-device-id-iw4sgfzm=8877662e-f408-4b7c-8b91-244cbd3711a0; intercom-session-iw4sgfzm=; ajs_user_id=admin@harness.io; ajs_anonymous_id=352787ab-1ae5-44fa-ab37-881908de17bf; ADRUM=s=1702273743279&r=https%3A%2F%2Flocalhost%3A8181%2Fauth%2F%3Fhash%3D358787835' \
--header 'Origin: https://localhost:8181' \
--header 'Referer: https://localhost:8181/ng/account/kmpySmUISimoRrJL6NL73w/home/orgs/default/projects/TestProject/setup/resources/templates' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--header 'Harness-Account: kmpySmUISimoRrJL6NL73w' \
--data-raw '[{"connectorRef":"GitShivamtest","repoName":"shivam-test","filePath":".harness/TestRemote_v1.yaml", "version": "v1"}]'`

For org: 
`curl --location --request POST 'https://localhost:8181/template/api/v1/org/default/git-metadata/TestRemote?accountIdentifier=kmpySmUISimoRrJL6NL73w&projectIdentifier=TestProject&orgIdentifier=default&projectIdentifier=TestProject&connectorRef=GitShivamtest&repoName=shivam-test&filePath=.harness%2FTestTemp1234_v1.yaml' \
--header 'Accept: */*' \
--header 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50SWQiOiJrbXB5U21VSVNpbW9SckpMNk5MNzN3IiwiYXV0aFRva2VuIjoiSFhUclhVMWtIZ1RFV0oyZWFGd0xBTU1leTVySGlNRWoiLCJpc3MiOiJIYXJuZXNzIEluYyIsIm5hbWUiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwidXNySWQiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwiZXhwIjoxNzAyNDc5NzI3LCJlbnYiOiIiLCJ0eXBlIjoiVVNFUiIsImlhdCI6MTcwMjM5MzMyNywiZW1haWwiOiJhZG1pbkBoYXJuZXNzLmlvIiwidXNlcm5hbWUiOiJBZG1pbiJ9.dfryd5ShIaaAg712-utiYaVYGL93o8t6XxU8xZNPoNQ' \
--header 'Connection: keep-alive' \
--header 'Cookie: jenkins-timestamper-offset=-19800000; __stripe_mid=e58251a3-2210-41f2-8657-486019b5e50d041a7b; _hjSessionUser_3650791=eyJpZCI6ImY1YjBiOTAwLWQzMjYtNWFiNC05N2YzLTdmNDVkZWEzNWRiMyIsImNyZWF0ZWQiOjE2OTcyMDQwNzE5NzUsImV4aXN0aW5nIjp0cnVlfQ==; intercom-id-iw4sgfzm=d2cdcdce-b415-40ce-8534-ed9e5d6360ef; intercom-device-id-iw4sgfzm=8877662e-f408-4b7c-8b91-244cbd3711a0; intercom-session-iw4sgfzm=; ajs_user_id=admin@harness.io; ajs_anonymous_id=352787ab-1ae5-44fa-ab37-881908de17bf; ADRUM=s=1702273743279&r=https%3A%2F%2Flocalhost%3A8181%2Fauth%2F%3Fhash%3D358787835' \
--header 'Origin: https://localhost:8181' \
--header 'Referer: https://localhost:8181/ng/account/kmpySmUISimoRrJL6NL73w/home/orgs/default/projects/TestProject/setup/resources/templates' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--header 'Harness-Account: kmpySmUISimoRrJL6NL73w' \
--data-raw '[{"connectorRef":"GitShivamtest","repoName":"shivam-test","filePath":".harness/TestRemote_v1.yaml", "version": "v1"}]'`
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-12 18:48 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1694 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlULreaDMDjNMdHDBV6:-NlULreaDMDjNMdHDBV7:bykuphq) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/contracts/openapi/v1/openapi.yaml#L1694)):*
> ```YAML
>       type: object
>       description: Lists down request params for template update git details request
>       properties:
> ```

I think we should further classify the params into defined structure : GitDetails and version. Currently all of them reside at same level.


<!-- Sent from Reviewable.io -->

2023-12-12 18:49 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlUM4Yr888lwnTAUxWE:-NlUM4Yr888lwnTAUxWF:bqdc3lx) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java#L481)):*
> ```Java
>         Resource.of(TEMPLATE, templateIdentifier), PermissionTypes.TEMPLATE_EDIT_PERMISSION);
>     templateUpdateGitMetadataRequests.forEach(request
>         -> templateService.updateGitDetails(accountIdentifier, orgIdentifier, projectIdentifier, templateIdentifier,
> ```

lets not do any logic in resource layer. Create a service layer method and then internally call whatever we may want to.


<!-- Sent from Reviewable.io -->

2023-12-13 04:25 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1694 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlULreaDMDjNMdHDBV6:-NlWPupA-5r3hTWi7Jub:bn26zen) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/contracts/openapi/v1/openapi.yaml#L1694)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we should further classify the params into defined structure : GitDetails and version. Currently all of them reside at same level.
</blockquote></details>

Can you please elaborate as I need git detail corresponding to the template version therefore keeping it at same level.
___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlUM4Yr888lwnTAUxWE:-NlWPh9w45X5fRJlksZX:b25u8w9) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java#L481)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets not do any logic in resource layer. Create a service layer method and then internally call whatever we may want to.
</blockquote></details>

It is not resource layer, it's a helper class for template


<!-- Sent from Reviewable.io -->

2023-12-13 04:38 UTC, shivamnegi94 commented
trigger uts

2023-12-13 05:56 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1694 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlULreaDMDjNMdHDBV6:-NlWjXmb7c_lUNFkzeQk:be1gpr8) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/contracts/openapi/v1/openapi.yaml#L1694)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

Can you please elaborate as I need git detail corresponding to the template version therefore keeping it at same level.
</blockquote></details>

I mean lets create structure like:
struct Template..MetadataRequest {
    struct GitDetails gitDetails;
    String templateVersion;
}

Then GitDetails becomes a separate struct. Right now all fields are combined into a single one.


<!-- Sent from Reviewable.io -->

2023-12-13 05:57 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlUM4Yr888lwnTAUxWE:-NlWjlqY27K_J16PHBmq:b-iyikar) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java#L481)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

It is not resource layer, it's a helper class for template
</blockquote></details>

Yes, but helper class is having a logic which it shouldn't have. Resource layers (or any of its helpers) aren't bound to contain service logics. Ideally helper class is nothing but an extension of the main class itself.
So, by design, its better to create a service method which does it for you and simply call it from resource layer. One major pro for it is that if tomorrow some other service also wanted to this operation, then they could easily do it, but not in current implementation.


<!-- Sent from Reviewable.io -->

2023-12-13 08:54 UTC, shivamnegi94 commented
trigger uts

2023-12-13 09:16 UTC, shivamnegi94 commented
trigger uts

2023-12-13 09:17 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1694 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlULreaDMDjNMdHDBV6:-NlXSrLB3YY9dpgm-nQ9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/contracts/openapi/v1/openapi.yaml#L1694)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I mean lets create structure like:
struct Template..MetadataRequest {
    struct GitDetails gitDetails;
    String templateVersion;
}

Then GitDetails becomes a separate struct. Right now all fields are combined into a single one.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/56680#-NlUM4Yr888lwnTAUxWE:-NlXSpTg-dDFzevTTiaI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/249cef055f9ee06cf43691b34959dac65d560184/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiHelper.java#L481)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, but helper class is having a logic which it shouldn't have. Resource layers (or any of its helpers) aren't bound to contain service logics. Ideally helper class is nothing but an extension of the main class itself.
So, by design, its better to create a service method which does it for you and simply call it from resource layer. One major pro for it is that if tomorrow some other service also wanted to this operation, then they could easily do it, but not in current implementation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 09:20 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1576 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTHVg1jgYMb_tIyw_:-NlXTHVg1jgYMb_tIywa:b7j0kdl) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1576)):*
> ```Java
>   public Response updateGitDetailsForMultipleVersion(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String templateIdentifier,
>       List<TemplateUpdateGitMetadataRequest> templateUpdateGitMetadataRequests) {
> ```

We need to use different argument class for service. A service shouldn't have any coupling with any other layer. Currently, if we use resource layer's class in service, then we create a binding.


<!-- Sent from Reviewable.io -->

2023-12-13 09:20 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1577 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTUdi4id9Dq53e23h:-NlXTUdi4id9Dq53e23i:b4idgrj) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1577)):*
> ```Java
>       String projectIdentifier, String templateIdentifier,
>       List<TemplateUpdateGitMetadataRequest> templateUpdateGitMetadataRequests) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
> ```

access control check should be in resource layer only.

A resource layer should do access control as its the entry point via external API. It should also do any entry level validations if required.

Service layer can have additional access checks, or validations based on the requirements.


<!-- Sent from Reviewable.io -->

2023-12-13 09:21 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1582 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTglT33JqQaKW6i7p:-NlXTglT33JqQaKW6i7q:bucfnt3) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1582)):*
> ```Java
>     for (TemplateUpdateGitMetadataRequest request : templateUpdateGitMetadataRequests) {
>       if (request == null || EmptyPredicate.isEmpty(request.getVersion())) {
>         throw new EntityNotFoundException("Template Version can not be empty or null");
> ```

This is a validation failure that input request is wrong. So, we should send invalidRequest and not EntityNotFound.


<!-- Sent from Reviewable.io -->

2023-12-13 09:21 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1587 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTnXm38ItDQqX6PqX:-NlXTnXm38ItDQqX6PqY:b-5h08c7) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1587)):*
> ```Java
>           || EmptyPredicate.isEmpty(request.getGitDetails().getConnectorRef())
>           || EmptyPredicate.isEmpty(request.getGitDetails().getRepoName())) {
>         throw new EntityNotFoundException("Git details field can not be empty or null");
> ```

same here.


<!-- Sent from Reviewable.io -->

2023-12-13 09:22 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1584 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTvhHBmwgg8eBT-JG:-NlXTvhHBmwgg8eBT-JH:b-jx1vm4) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1584)):*
> ```Java
>         throw new EntityNotFoundException("Template Version can not be empty or null");
>       }
>       if (request.getGitDetails() == null || EmptyPredicate.isEmpty(request.getGitDetails().getFilePath())
> ```

this if and prev if are both validations, so we can club them in a separate method to keep the code clean and readable.


<!-- Sent from Reviewable.io -->

2023-12-13 09:23 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1598 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXU1G28yYg-ZAi7q0g:-NlXU1G28yYg-ZAi7q0h:b-1dikbe) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1598)):*
> ```Java
>     }
> 
>     return Response.ok().entity(TemplateUpdateGitMetadataResponse.builder().status(true).build()).build();
> ```

A service should simply return its own response. It doesn't depend on any external layer. Resource layer will get this response and then transform into the API response however is required.


<!-- Sent from Reviewable.io -->

2023-12-13 11:53 UTC, shivamnegi94 reviewed
> Reviewed 2 of 7 files at r2, 1 of 2 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1576 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTHVg1jgYMb_tIyw_:-NlY0aJPDu7_9JC_xc9g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1576)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We need to use different argument class for service. A service shouldn't have any coupling with any other layer. Currently, if we use resource layer's class in service, then we create a binding.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1577 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTUdi4id9Dq53e23h:-NlY0a2j-6frL7BioYFg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1577)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

access control check should be in resource layer only.

A resource layer should do access control as its the entry point via external API. It should also do any entry level validations if required.

Service layer can have additional access checks, or validations based on the requirements.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1582 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTglT33JqQaKW6i7p:-NlY0_Yg8LShEjYygE1p:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1582)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is a validation failure that input request is wrong. So, we should send invalidRequest and not EntityNotFound.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1584 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTvhHBmwgg8eBT-JG:-NlY0_6L1IrqQiligq6L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1584)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this if and prev if are both validations, so we can club them in a separate method to keep the code clean and readable.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1587 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTnXm38ItDQqX6PqX:-NlY0Z1fDrl_1hkLQnA7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1587)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1598 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXU1G28yYg-ZAi7q0g:-NlY0YiT1vPv3v4P-gYW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1598)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

A service should simply return its own response. It doesn't depend on any external layer. Resource layer will get this response and then transform into the API response however is required.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-14 03:00 UTC, shivamnegi94 commented
trigger uts

2023-12-14 03:31 UTC, krishi0408 commented
trigger uts

2023-12-14 03:35 UTC, shivamnegi94 commented
trigger commonchecks

2023-12-14 06:25 UTC, shivamnegi94 commented
trigger uts

2023-12-14 06:42 UTC, utkarshchoubey-harness approved these changes

2023-12-14 06:45 UTC, shivamnegi94 commented
trigger uts

2023-12-14 06:59 UTC, mohitg0795 requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1576 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTHVg1jgYMb_tIyw_:-Nlb6jKYAU8lH6LCGDdX:byga0le) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1576)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What change did we do in argument here? I still see the same argument "TemplateUpdateGitMetadataRequest" being used which is resource layer entity.


<!-- Sent from Reviewable.io -->

2023-12-14 09:02 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1576 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTHVg1jgYMb_tIyw_:-NlbYnd42e3jyZAQfQ5D:b-k6lxuj) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1576)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

What change did we do in argument here? I still see the same argument "TemplateUpdateGitMetadataRequest" being used which is resource layer entity.
</blockquote></details>

What do you suggest here ? Create again another entity using TemplateUpdateGitMetadataRequest and pass to service layer ?


<!-- Sent from Reviewable.io -->

2023-12-14 10:15 UTC, shivamnegi94 commented
trigger uts

2023-12-15 03:59 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1576 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTHVg1jgYMb_tIyw_:-Nlfc7UCAD7Nh8RkfFnF:b5bgnco) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1576)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, Imagine we are writing a service layer interface to do the required operation. How will you do it then? Just think about it and thats how you do it. Then we just call this service layer method from resource layer, so then do the integration accordingly.
</blockquote></details>

In this case we have to iterate TemplateUpdateGitMetadataRequest as it is a list in resource layer helper.


<!-- Sent from Reviewable.io -->

2023-12-15 08:15 UTC, shivamnegi94 commented
trigger uts

2023-12-15 08:23 UTC, shivamnegi94 reviewed
> Reviewed 3 of 4 files at r6, 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1576 at r3](https://reviewable.io/reviews/harness/harness-core/56680#-NlXTHVg1jgYMb_tIyw_:-NlgZc9x5EFG-Zda0k7i:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee89fd9be4600df8040e1fbb4d7d843d6b065fc2/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1576)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

In this case we have to iterate TemplateUpdateGitMetadataRequest as it is a list in resource layer helper.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-15 08:28 UTC, mohitg0795 approved these changes
> Reviewed 1 of 7 files at r2, 1 of 2 files at r3, 3 of 4 files at r6, 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 11 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-15 08:35 UTC, mohitg0795 submitted a review, later dismissed

2023-12-15 08:58 UTC, shivamnegi94 commented
trigger uts

2023-12-15 09:13 UTC, utkarshchoubey-harness submitted a review, later dismissed
lgtm!

2023-12-15 09:25 UTC, shivamnegi94 commented
trigger review

2023-12-15 09:30 UTC, shivamnegi94 commented
trigger messagecheck

2023-12-15 11:35 UTC, shivamnegi94 commented
trigger ut4, ut9

2023-12-15 12:18 UTC, shivamnegi94 commented
trigger ut1

2023-12-15 13:23 UTC, shivamnegi94 commented
ut1

2023-12-18 04:29 UTC, sahilhindwani-harness commented
*[`template-service/service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java` line 100 at r9](https://reviewable.io/reviews/harness/harness-core/56680#-NlvAjJAEk_xv-YZCWPx:-NlvAjJAEk_xv-YZCWPy:bnk6t3z) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java#L100)):*
> ```Java
>   @Override
>   public Response updateGitMetadataDetailsOrg(String templateIdentifier, String org,
>       @Valid List<TemplateUpdateGitMetadataRequest> body, String harnessAccount) {
> ```

Should we add a limit on the size of this list?
Is there any chance that user can send very big list?


<!-- Sent from Reviewable.io -->

2023-12-18 04:29 UTC, sahilhindwani-harness submitted a review, later dismissed
> Reviewed 1 of 7 files at r2, 1 of 2 files at r3, 3 of 4 files at r6, 4 of 6 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 1 file(s) to review. 



<!-- Sent from Reviewable.io -->

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        name: templateIdentifier
please refer to other APIs here, this should use - $ref: '#/components/parameters/Template' and not `templateIdentifier`

similar for others

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        - schema:
please use - $ref: '#/components/parameters/AccountHeaderParam'

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        - $ref: '#/components/parameters/Org'
is this adding a query param?

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        name: org
we should use - $ref: '#/components/parameters/Org' here

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        in: path
same comments as above for org/project/template identifiers

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        gitDetails:
git_details

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        filePath:
casing for this too, file_path, repo_name etc.

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        filePath:
Also i thought we had this already in this file for Templates GitX? Could you verify once?

2023-12-18 05:07 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +      description: Template GitMetadat response
typo here

2023-12-18 05:43 UTC, shivamnegi94 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56680)* status: 2 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 81 at r9](https://reviewable.io/reviews/harness/harness-core/56680#gh-1429505685:-NlvRe2p9juw7jX0g74f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/contracts/openapi/v1/openapi.yaml#L81)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

please refer to other APIs here, this should use - $ref: '#/components/parameters/Template' and not `templateIdentifier`

similar for others
</blockquote></details>

Done.
___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 194 at r9](https://reviewable.io/reviews/harness/harness-core/56680#gh-1429506639:-NlvRecq3SleYFSBVI2P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/contracts/openapi/v1/openapi.yaml#L194)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

is this adding a query param? 
</blockquote></details>

Done.
___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 195 at r9](https://reviewable.io/reviews/harness/harness-core/56680#gh-1429505836:-NlvRf2G813W3rSSl6Kb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/contracts/openapi/v1/openapi.yaml#L195)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

please use - $ref: '#/components/parameters/AccountHeaderParam'
</blockquote></details>

Done.
___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 219 at r9](https://reviewable.io/reviews/harness/harness-core/56680#gh-1429506692:-NlvRfUB5YXppJp8OdB9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/contracts/openapi/v1/openapi.yaml#L219)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

we should use - $ref: '#/components/parameters/Org' here
</blockquote></details>

Done.
___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 400 at r9](https://reviewable.io/reviews/harness/harness-core/56680#gh-1429506974:-NlvRg8A9Yj5N4Ny23pA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/contracts/openapi/v1/openapi.yaml#L400)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

same comments as above for org/project/template identifiers
</blockquote></details>

Done.
___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1699 at r9](https://reviewable.io/reviews/harness/harness-core/56680#gh-1429507068:-NlvRgYbE90Z7t2I7Sb4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/contracts/openapi/v1/openapi.yaml#L1699)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

git_details
</blockquote></details>

Done.
___
*[`template-service/contracts/openapi/v1/openapi.yaml` line 1707 at r9](https://reviewable.io/reviews/harness/harness-core/56680#gh-1429507180:-NlvRh408ygzuHlxzszI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/contracts/openapi/v1/openapi.yaml#L1707)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

Also i thought we had this already in this file for Templates GitX? Could you verify once?
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java` line 100 at r9](https://reviewable.io/reviews/harness/harness-core/56680#-NlvAjJAEk_xv-YZCWPx:-NlvRjeu4Ja3aiM3O7eP:bybzaq6) ([raw file](https://github.com/harness/harness-core/blob/a4c8c8dff5c88d990b3a821dd3ba116580c256da/template-service/service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java#L100)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we add a limit on the size of this list?
Is there any chance that user can send very big list?
</blockquote></details>

We can add in subsequent PR


<!-- Sent from Reviewable.io -->

2023-12-18 05:43 UTC, shivamnegi94 commented
trigger uts

2023-12-18 05:50 UTC, shivamnegi94 commented
trigger uts

2023-12-18 06:06 UTC, mankrit-singh commented on template-service/contracts/openapi/v1/openapi.yaml
> +        in: path
this api is still not fixed for prev comments

2023-12-18 06:37 UTC, shivamnegi94 commented
trigger uts

2023-12-18 06:44 UTC, shivamnegi94 commented
trigger uts

2023-12-18 07:03 UTC, mankrit-singh approved these changes

2023-12-18 07:03 UTC, shivamnegi94 commented
trigger uts

2023-12-18 07:14 UTC, utkarshchoubey-harness approved these changes

2023-12-18 07:17 UTC, shivamnegi94 commented
trigger review

2023-12-18 09:15 UTC, shivamnegi94 commented
trigger ut0, ut2

2023-12-18 10:41 UTC, shivamnegi94 commented
trigger ut2

2023-12-18 14:08 UTC, merged