[feat]: [PLG-3073]: Stop marking accounts as EXPIRED with atleast 1 active NG license and BG migration
harness/harness-core pull request #56757
Opened 2023-12-13 19:34 UTC by kapil-harness

## Describe your changes

Logs of background migration:

` 2023-12-14 00:59:38,170 [main-app-pool-2] INFO  io.harness.migrations.all.UpdateAccountStatusForAllExpiredAccountsMigration - licenseInfo.accountStatus field is successfully updated for account: kmpySmUISimoRrJL6NL73w with values: {licenseInfo.accountStatus=ACTIVE, lastUpdatedAt=1702495778153} [updateAccountStatusMigration=ZjNbwYjwRUK2UJBmfmjJjQ] 

2023-12-14 00:59:38,174 [main-app-pool-2] INFO  io.harness.migrations.all.UpdateAccountStatusForAllExpiredAccountsMigration - Total accounts with failed migration= 0 and the list= [] [updateAccountStatusMigration=ZjNbwYjwRUK2UJBmfmjJjQ] 

2023-12-14 00:59:38,175 [main-app-pool-2] INFO  io.harness.logging.ResponseTimeRecorder - Update licenseInfo.accountStatus field for all the expired accounts BG Migration Job: TIME TAKEN (ms) : 31812  

2023-12-14 00:59:38,175 [main-app-pool-2] INFO  io.harness.migrations.all.UpdateAccountStatusForAllExpiredAccountsMigration - Migration to mark all the EXPIRED accounts as ACTIVE which have at-least 1 active NG license finished  

2023-12-14 00:59:38,178 [main-app-pool-2] INFO  software.wings.service.impl.MigrationServiceImpl - [Migration] - Background migration complete  
`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-13 19:59 UTC, sahibaHarness commented on 390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java
> +        wingsPersistence.createQuery(Account.class).field(AccountKeys.accountStatusKey).equal(AccountStatus.EXPIRED);
This will fetch all the accounts where license is expired. Close to 18k;  @ankit-harness don't we have a 10k limit on docs we can bring in memory?

2023-12-13 20:08 UTC, sahibaHarness commented on 390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java
> +              wingsPersistence.update(account, updateOperations);
When we are updating the status should we update the license expiry as well? And do the same in license expiry job check to align with account status?

2023-12-13 20:11 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56757)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/56757#gh-1425823477:-NlZn4ae1Gu2HPg7KIVu:bevnd08) ([raw file](https://github.com/harness/harness-core/blob/5eae995c29882a55d5b9f192b474ef62d75d21a4/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L49)):*
<details><summary><i>Previously, sahibaHarness (Sahiba Khan) wrote…</i></summary><blockquote>

This will fetch all the accounts where license is expired. Close to 18k;  @ankit-harness don't we have a 10k limit on docs we can bring in memory? 
</blockquote></details>

yes this BG job will run on all the EXPIRED accounts present in a cluster, however its just a one time job, so I don't think any risk.

We are logging the time it takes for this BG job to finish and also prints the accounts for which this migration doesn't run, so we are good from that perspective as well.


<!-- Sent from Reviewable.io -->

2023-12-13 20:14 UTC, kapil-harness commented
trigger uts

2023-12-13 20:59 UTC, kapil-harness commented
trigger uts

2023-12-14 04:11 UTC, ankit-harness requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56757)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/56757#gh-1425823477:-NlaSYBeCqwJFWI8E0T1:b-8p2bpw) ([raw file](https://github.com/harness/harness-core/blob/5eae995c29882a55d5b9f192b474ef62d75d21a4/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L49)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

yes this BG job will run on all the EXPIRED accounts present in a cluster, however its just a one time job, so I don't think any risk.

We are logging the time it takes for this BG job to finish and also prints the accounts for which this migration doesn't run, so we are good from that perspective as well.
</blockquote></details>

@kapil-harness We have 10K limit on all queries. You will have to override the value in your query
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaTq7Y2WF4PxnChZgw:-NlaTq7Y2WF4PxnChZgx:b-8zbmsb) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L63)):*
> ```Java
>             account = records.next();
>             CheckExpiryResultDTO ngLicenseDecision = getResponse(ngLicenseHttpClient.checkExpiry(account.getUuid()));
>             if (!ngLicenseDecision.isShouldDelete()) {
> ```

Should we check ngAccountActive instead?
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaU4l1CId2bHZNUsvP:-NlaU4l1CId2bHZNUsvQ:blbkil0) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L65)):*
> ```Java
>             if (!ngLicenseDecision.isShouldDelete()) {
>               UpdateOperations<Account> updateOperations = wingsPersistence.createUpdateOperations(Account.class);
>               updateOperations.set(AccountKeys.accountStatusKey, AccountStatus.ACTIVE);
> ```

Can we call API instead to update account status

AccountServiceImpl.updateAccountStatus(String accountId, String accountStatus)
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 220 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaUY-E2nzWVls_r1Li:-NlaUY-E2nzWVls_r1Lj:b2v6wun) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L220)):*
> ```Java
>         }
>       } else {
>         if (AccountStatus.ACTIVE.equals(accountStatus) && ngLicenseDecision.isShouldDelete()) {
> ```

Should we check ngLicenseDecision.ngAccountActive instead?
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 590 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaWA1gBOc3n9vZUffv:-NlaWA1gBOc3n9vZUffw:blt0yiu) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L590)):*
> ```Java
> 
>     if (System.currentTimeMillis() > licenseInfo.getExpiryTime()) {
>       CheckExpiryResultDTO ngLicenseDecision = getNgLicenseDecision(account);
> ```

Can we add this code above if block

if (!getNgLicenseDecision(account).isShouldDelete()) { return false; }


<!-- Sent from Reviewable.io -->

2023-12-14 22:08 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56757)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/56757#gh-1425823477:-NleFA9G9iGHJUm8Ty1u:bdpl7n5) ([raw file](https://github.com/harness/harness-core/blob/5eae995c29882a55d5b9f192b474ef62d75d21a4/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@kapil-harness We have 10K limit on all queries. You will have to override the value in your query
</blockquote></details>

@ankit-harness @sahibaHarness thanks for the important feedback here, I have added the limit as 30k, was just trying to make sure we take a max limit and don't miss any accounts during this migration.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaTq7Y2WF4PxnChZgw:-NleBDEh2BO6ZmfH073I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L63)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we check ngAccountActive instead?
</blockquote></details>

Done.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaU4l1CId2bHZNUsvP:-NleCsUnDBZEpwbI40Vt:bqfoi1g) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L65)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we call API instead to update account status

AccountServiceImpl.updateAccountStatus(String accountId, String accountStatus)
</blockquote></details>

Done. 

@ankit-harness but how is this better? according to me both are same operations :) 
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 220 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaUY-E2nzWVls_r1Li:-Nle9bZp-qvW4IHl3eEu:b-we5pxl) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L220)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we check ngLicenseDecision.ngAccountActive instead?
</blockquote></details>

@ankit-harness that's a really good catch, .isNgAccountActive() makes more sense.
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 590 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaWA1gBOc3n9vZUffv:-Nle8hMNCOmjH9gu5xwx:bql3fjs) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L590)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we add this code above if block

if (!getNgLicenseDecision(account).isShouldDelete()) { return false; }
</blockquote></details>

it will be a waste of operation if we put it outside if block because we are only interested in checking active NG licenses if currentTime  > expiryTime


<!-- Sent from Reviewable.io -->

2023-12-14 22:22 UTC, kapil-harness commented
trigger uts

2023-12-15 02:41 UTC, ankit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56757)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/56757#gh-1425823477:-NlfK1gW0RW_8GAI0Ctn:b-kn7coq) ([raw file](https://github.com/harness/harness-core/blob/5eae995c29882a55d5b9f192b474ef62d75d21a4/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L49)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

@ankit-harness @sahibaHarness thanks for the important feedback here, I have added the limit as 30k, was just trying to make sure we take a max limit and don't miss any accounts during this migration.
</blockquote></details>

You can make it Integer.MAX_VALUE to be on safer side.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaU4l1CId2bHZNUsvP:-NlfK7EM20GoGVDZ4vDQ:b-xld4vn) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L65)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

Done. 

@ankit-harness but how is this better? according to me both are same operations :)
</blockquote></details>

There is encrypted license info in which account status has to be updated too. this method will take care of that
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 590 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaWA1gBOc3n9vZUffv:-NlfKvrJ9tQr1JuT1msp:b9gaq8m) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L590)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

it will be a waste of operation if we put it outside if block because we are only interested in checking active NG licenses if currentTime  > expiryTime
</blockquote></details>

Code is bit unreadable right now. See ideally code to expire license should not be here in the first place. This method is just to check if license is expired or not. But we are having a side effect in this method to expire the license as well. If in future, we remove this side effect, it might be confusing to readers what to do with ngLicenseDecision.


<!-- Sent from Reviewable.io -->

2023-12-15 03:05 UTC, kapil-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56757)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/56757#gh-1425823477:-NlfOWFp7H2DZjDUbvBO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5eae995c29882a55d5b9f192b474ef62d75d21a4/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

You can make it Integer.MAX_VALUE to be on safer side.
</blockquote></details>

Done.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaU4l1CId2bHZNUsvP:-NlfOcxY9r1GE8A_tH5b:b-pqov82) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/390-db-migration/src/main/java/io/harness/migrations/all/UpdateAccountStatusForAllExpiredAccountsMigration.java#L65)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

There is encrypted license info in which account status has to be updated too. this method will take care of that
</blockquote></details>

makes sense
___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 590 at r2](https://reviewable.io/reviews/harness/harness-core/56757#-NlaWA1gBOc3n9vZUffv:-NlfPcAf4V-9lpl_X8F3:b4xl0hl) ([raw file](https://github.com/harness/harness-core/blob/4c6bf0bebb558f27db3e2b57e0c236d70673002f/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L590)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Code is bit unreadable right now. See ideally code to expire license should not be here in the first place. This method is just to check if license is expired or not. But we are having a side effect in this method to expire the license as well. If in future, we remove this side effect, it might be confusing to readers what to do with ngLicenseDecision.
</blockquote></details>

Done.
@ankit-harness that's a really good suggestion, thank you!


<!-- Sent from Reviewable.io -->

2023-12-15 03:05 UTC, kapil-harness commented
trigger uts

2023-12-15 03:10 UTC, ankit-harness approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56757)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-15 03:11 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56757#-:-NlfSAXd3nuORMheolD4:bnfp4nl)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-15 04:56 UTC, sahibaHarness approved these changes

2023-12-15 05:44 UTC, kapil-harness commented
trigger ut0

2023-12-15 06:32 UTC, mohitg0795 approved these changes

2023-12-15 07:00 UTC, kapil-harness commented
trigger ut0

2023-12-15 07:03 UTC, kapil-harness commented
trigger review

2023-12-15 07:19 UTC, merged