[feat]: [CDS-86981]: Adding get-steps API in open-api spec to filter steps by yaml-version
harness/harness-core pull request #56796
Opened 2023-12-14 19:16 UTC by brijeshdhakar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-14 19:23 UTC, brijeshdhakar commented
trigger uts

2023-12-15 04:02 UTC, archit-harness requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56796)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 917 at r1](https://reviewable.io/reviews/harness/harness-core/56796#-NlfcMWIETYJ-KKExMm2:-NlfcMWIETYJ-KKExMm3:b9nmmzr) ([raw file](https://github.com/harness/harness-core/blob/88bc22e929b98b5d8ba7e79cfd08568e9283e814/pipeline-service/contracts/openapi/v1/openapi.yaml#L917)):*
> ```YAML
>     parameters: []
>     post:
>       summary: Get steps
> ```

can we have better summary for this? like list steps for pallete, plus can we make this API hidden
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 479 at r1](https://reviewable.io/reviews/harness/harness-core/56796#-Nlfcom8E5QjNIODmJyQ:-Nlfcom8E5QjNIODmJyR:b-wmtzzq) ([raw file](https://github.com/harness/harness-core/blob/88bc22e929b98b5d8ba7e79cfd08568e9283e814/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L479)):*
> ```Java
>   }
> 
>   public static StepPalleteFilterWrapper mapToStepPalleteFilterWrapperDTO(
> ```

isnt this code duplicate of what we have today? can we just reuse


<!-- Sent from Reviewable.io -->

2023-12-15 05:10 UTC, brijeshdhakar commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 917 at r1](https://reviewable.io/reviews/harness/harness-core/56796#-NlfcMWIETYJ-KKExMm2:-NlfsKLM4cUDLn1vosvL:bal48h1) ([raw file](https://github.com/harness/harness-core/blob/88bc22e929b98b5d8ba7e79cfd08568e9283e814/pipeline-service/contracts/openapi/v1/openapi.yaml#L917)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we have better summary for this? like list steps for pallete, plus can we make this API hidden
</blockquote></details>

API is already hidden. `x-internal: true`.


<!-- Sent from Reviewable.io -->

2023-12-15 05:10 UTC, brijeshdhakar commented
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 917 at r1](https://reviewable.io/reviews/harness/harness-core/56796#-NlfcMWIETYJ-KKExMm2:-NlfsVYu-KEcNVFaEHqp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/88bc22e929b98b5d8ba7e79cfd08568e9283e814/pipeline-service/contracts/openapi/v1/openapi.yaml#L917)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

API is already hidden. `x-internal: true`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-15 05:11 UTC, brijeshdhakar commented
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java` line 479 at r1](https://reviewable.io/reviews/harness/harness-core/56796#-Nlfcom8E5QjNIODmJyQ:-NlfsXLxCKmCUS03ATc9:bi45vrb) ([raw file](https://github.com/harness/harness-core/blob/88bc22e929b98b5d8ba7e79cfd08568e9283e814/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiUtils.java#L479)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this code duplicate of what we have today? can we just reuse
</blockquote></details>

We don't have this mapper today becasue current getSteps API is not onboarded on open-api spec.


<!-- Sent from Reviewable.io -->

2023-12-15 05:12 UTC, brijeshdhakar commented
trigger uts

2023-12-15 05:22 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        - Pipelines
Recommended to add this under a new tag called Steps due to this known issue - https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21203550744/Summary+of+API+Redesign+Changes#Adding-Tags-to-your-APIs

2023-12-15 05:22 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        featureRestrictionName:
casing

2023-12-15 05:22 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +        shouldShowCommonSteps:
here too

2023-12-15 05:41 UTC, archit-harness reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56796)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-15 05:41 UTC, archit-harness reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56796)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-15 05:41 UTC, archit-harness submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56796)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-15 06:00 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56796)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 923 at r2](https://reviewable.io/reviews/harness/harness-core/56796#gh-1427560309:-Nlg1Fvy3ccj6mIE-_2f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0f85df9673300b42d86bc998bbbd467a76080284/pipeline-service/contracts/openapi/v1/openapi.yaml#L923)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

Recommended to add this under a new tag called Steps due to this known issue - https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21203550744/Summary+of+API+Redesign+Changes#Adding-Tags-to-your-APIs
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 4576 at r2](https://reviewable.io/reviews/harness/harness-core/56796#gh-1427560401:-Nlg1G_6DLihAQmtk_6_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0f85df9673300b42d86bc998bbbd467a76080284/pipeline-service/contracts/openapi/v1/openapi.yaml#L4576)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

casing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-15 06:00 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56796)* status: 5 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 4749 at r2](https://reviewable.io/reviews/harness/harness-core/56796#gh-1427560457:-Nlg30-L0Ac_-ZwX5Qwq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0f85df9673300b42d86bc998bbbd467a76080284/pipeline-service/contracts/openapi/v1/openapi.yaml#L4749)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

in this object too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-15 06:03 UTC, archit-harness approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56796)* status: 5 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-15 06:04 UTC, brijeshdhakar commented
trigger uts

2023-12-15 06:14 UTC, mankrit-singh approved these changes

2023-12-15 06:16 UTC, mankrit-singh commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +  /v1/steps:
minor comment - this will be unique across all apis and entities in harness. if you choose to you can also use pipeline-steps if other services / products might use steps as a different entity too

2023-12-15 06:48 UTC, brijeshdhakar commented
trigger review

2023-12-15 07:40 UTC, brijeshdhakar commented
trigger ut9

2023-12-15 08:25 UTC, brijeshdhakar commented on pipeline-service/contracts/openapi/v1/openapi.yaml
> +  /v1/steps:
Ok. I am renaming this path to `v1/step-pallete` in my the next PR to make sure it remains unique.

2023-12-15 08:52 UTC, merged