fix: [PL-42600]: Calculate delegate cpu and memory usage from top command
harness/harness-core pull request #56812
Opened 2023-12-15 05:32 UTC by jennyjames21

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-18 01:22 UTC, jennyjames21 commented
trigger uts

2023-12-18 02:01 UTC, jennyjames21 commented
trigger uts

2023-12-18 18:53 UTC, raghuAtWings requested changes

2023-12-18 18:53 UTC, raghuAtWings commented on 260-delegate/src/main/java/io/harness/delegate/service/LogPerformanceImpl.java
> +          if (isNotEmpty(processInfo[0]) && processInfo[0].equals("%Cpu(s):")) {
should do case insensitive %Cpu

2023-12-18 18:53 UTC, raghuAtWings commented on 260-delegate/src/main/java/io/harness/delegate/service/LogPerformanceImpl.java
> +            if (isNotEmpty(cpuLine) && isNotEmpty(cpuLine.get(1)) && !resourceUsuageMap.containsKey("CPU")) {
why double? can we not use float?

2023-12-19 04:47 UTC, jennyjames21 commented on 260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
> +    final double cpuUsage = resourceUsuageMap.get("CPU");
add fallback logic to old flow

2023-12-19 04:47 UTC, jennyjames21 commented on 260-delegate/src/main/java/io/harness/delegate/service/LogPerformanceImpl.java
> +          if (isNotEmpty(processInfo[0]) && processInfo[0].equals("%Cpu(s):")) {
updated

2023-12-19 04:48 UTC, jennyjames21 commented on 260-delegate/src/main/java/io/harness/delegate/service/LogPerformanceImpl.java
> +            if (isNotEmpty(cpuLine) && isNotEmpty(cpuLine.get(1)) && !resourceUsuageMap.containsKey("CPU")) {
calculation on the threshold and everywhere is double currently

2023-12-19 04:49 UTC, jennyjames21 commented
trigger uts

2023-12-19 23:53 UTC, jennyjames21 commented
trigger uts

2023-12-21 05:30 UTC, raghuAtWings approved these changes

2023-12-21 07:42 UTC, jennyjames21 commented
trigger messagecheck

2023-12-21 07:46 UTC, jennyjames21 commented
trigger messagecheck

2023-12-21 08:10 UTC, merged