feat: [CDS-86929]: Plan Creator for approval Stage v1
harness/harness-core pull request #56825
Opened 2023-12-15 08:46 UTC by sarthakkasat

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-15 08:59 UTC, shalini-agr commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/StepParameterUtils.java
> +  private StageElementParametersV1.StageElementParametersV1Builder getCommonStageParameters(
we have this exact same method in 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/StepParametersUtils.java 
let's put them in ng-common-utilities and use it from there.

2023-12-15 08:59 UTC, shalini-agr commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java
> +    stageParameters.type(YAMLFieldNameConstants.CUSTOM_V1);
this should be APPROVAL_V1

2023-12-15 10:04 UTC, sarthakkasat commented on pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java
> +    stageParameters.type(YAMLFieldNameConstants.CUSTOM_V1);
Done

2023-12-15 10:55 UTC, archit-harness requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/BUILD.bazel` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/56825#-Nlh6Nor3f6PEDXkkmxA:-Nlh6Nor3f6PEDXkkmxB:b-x5pn2o) ([raw file](https://github.com/harness/harness-core/blob/7d73d0a8f753c6e1b739142b34fe34825176e15e/125-cd-nextgen/BUILD.bazel#L149)):*
> ```Starlark
>         "//clients/pipeline-service/pms-sdk:module",
>         "//clients/pipeline-service/pms-sdk-core:module",
>         "//pipeline-service/modules/orchestration-steps:module",
> ```

why do you need this?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/StepParameterUtils.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/56825#gh-1427720631:-Nlh6VhO2PGYlOOicrIU:b32v57) ([raw file](https://github.com/harness/harness-core/blob/13be19a84a87e2a9cb9540bed4295a8914db5336/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/StepParameterUtils.java#L36)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

we have this exact same method in 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/StepParametersUtils.java 
let's put them in ng-common-utilities and use it from there.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-12-15 12:14 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/BUILD.bazel` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/56825#-Nlh6Nor3f6PEDXkkmxA:-NlhOBjB5-BNTRA307Wq:bwk0n31) ([raw file](https://github.com/harness/harness-core/blob/7d73d0a8f753c6e1b739142b34fe34825176e15e/125-cd-nextgen/BUILD.bazel#L149)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need this?
</blockquote></details>

Removed it, moved the method ng-common-utilities
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/StepParameterUtils.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/56825#gh-1427720631:-NlhOYUeDIzeqmIahVbk:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/13be19a84a87e2a9cb9540bed4295a8914db5336/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/StepParameterUtils.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-15 12:32 UTC, archit-harness requested changes
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/BUILD.bazel` line 149 at r3](https://reviewable.io/reviews/harness/harness-core/56825#-NlhRVBZBCIZaLhqQZ2A:-NlhRVBZBCIZaLhqQZ2B:b-e22dd1) ([raw file](https://github.com/harness/harness-core/blob/d6980c9eecfb581903a1cb34e03daf3c50749de1/125-cd-nextgen/BUILD.bazel#L149)):*
> ```Starlark
>         "//clients/pipeline-service/pms-sdk:module",
>         "//clients/pipeline-service/pms-sdk-core:module",
>         "//pipeline-service/modules/orchestration-steps:module",
> ```

i still dont see the remove


<!-- Sent from Reviewable.io -->

2023-12-15 12:44 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/BUILD.bazel` line 149 at r3](https://reviewable.io/reviews/harness/harness-core/56825#-NlhRVBZBCIZaLhqQZ2A:-NlhVOwv2I0OZ75VRgwg:bz0qfcb) ([raw file](https://github.com/harness/harness-core/blob/d6980c9eecfb581903a1cb34e03daf3c50749de1/125-cd-nextgen/BUILD.bazel#L149)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i still dont see the remove
</blockquote></details>

Forgot to commit the file earlier please check again


<!-- Sent from Reviewable.io -->

2023-12-15 16:22 UTC, brijeshdhakar commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/stage/v1/ApprovalStageStep.java` line 48 at r5](https://reviewable.io/reviews/harness/harness-core/56825#-NliH4FhC28AROpigts6:-NliH4FhC28AROpigts7:b-prxhti) ([raw file](https://github.com/harness/harness-core/blob/5c0a548a2cba7ac9ab62f292d56a76aa15633d40/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/stage/v1/ApprovalStageStep.java#L48)):*
> ```Java
>   public ChildExecutableResponse obtainChild(
>       Ambiance ambiance, StageElementParametersV1 stepParameters, StepInputPackage inputPackage) {
>     ApprovalStageSpecParameters specParameters = (ApprovalStageSpecParameters) stepParameters.getSpec();
> ```

Are the ApprovalStageSpecParameters same for V0 and V1? Don't we have any change in approval YAML?


<!-- Sent from Reviewable.io -->

2023-12-15 17:31 UTC, sarthakkasat reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/stage/v1/ApprovalStageStep.java` line 48 at r5](https://reviewable.io/reviews/harness/harness-core/56825#-NliH4FhC28AROpigts6:-NliVgbg4UE0B9DAM17M:b-qt3ggb) ([raw file](https://github.com/harness/harness-core/blob/5c0a548a2cba7ac9ab62f292d56a76aa15633d40/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/stage/v1/ApprovalStageStep.java#L48)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Are the ApprovalStageSpecParameters same for V0 and V1? Don't we have any change in approval YAML?
</blockquote></details>

We are only using the child node Id from the specParameters, which will the same field for v0, v1. Do we have to create a new class in that case?


<!-- Sent from Reviewable.io -->

2023-12-18 06:39 UTC, brijeshdhakar approved these changes
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-18 07:15 UTC, sarthakkasat commented
trigger uts

2023-12-18 07:18 UTC, shalini-agr submitted a review, later dismissed

2023-12-18 07:28 UTC, sarthakkasat commented
trigger review

2023-12-18 07:53 UTC, archit-harness requested changes
> Reviewed 3 of 5 files at r1, 2 of 6 files at r3, 1 of 1 files at r4, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: <span>:shipit:</span> complete! ✓

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java` line 69 at r7](https://reviewable.io/reviews/harness/harness-core/56825#-NlvrmxhAmO-2fU2LfNs:-NlvrmxhAmO-2fU2LfNt:b-ijsfkr) ([raw file](https://github.com/harness/harness-core/blob/b6d05f3aaf9a645c4a55ce8dac8f920d2c83e0ea/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java#L69)):*
> ```Java
>     if (stepsField == null) {
>       throw new InvalidRequestException("Steps section is required in Approval stage");
>     }
> ```

why we are checking this? wouldnt this be check with schema validation?



_Code quote:_
```Java
    // Add dependency for execution
    YamlField stepsField = specField.getNode().getField(YAMLFieldNameConstants.STEPS);
    if (stepsField == null) {
      throw new InvalidRequestException("Steps section is required in Approval stage");
    }
```


<!-- Sent from Reviewable.io -->

2023-12-18 08:33 UTC, archit-harness approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-18 09:01 UTC, sarthakkasat commented
trigger uts

2023-12-18 09:04 UTC, sarthakkasat commented
/rebase

2023-12-18 09:07 UTC, sarthakkasat commented
trigger uts

2023-12-18 09:37 UTC, archit-harness approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: 1 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-18 09:51 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-18 09:52 UTC, sarthakkasat commented
trigger review

2023-12-18 18:52 UTC, yogesh-chauhan commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/StepParametersUtils.java` line 27 at r9](https://reviewable.io/reviews/harness/harness-core/56825#-NlyG98z8maXMriJFbCs:-NlyG98z8maXMriJFbCt:b-p20yks) ([raw file](https://github.com/harness/harness-core/blob/c9fd4c4ed03f5d8e5759f19378f5b7554130a5b2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/StepParametersUtils.java#L27)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = false, components = {HarnessModuleComponent.CDS_PIPELINE})
> public class StepParametersUtils {
>   public StageElementParametersV1Builder getStageParameters(DeploymentStageNodeV1 stageNode) {
> ```

should we not call this "getStageParametersBuilder" ? 
or 
this returns StageElementParameters. Callers caller the toBuilder() method to override properties ?


<!-- Sent from Reviewable.io -->

2023-12-18 18:52 UTC, yogesh-chauhan commented
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/StageParameterUtilsV1.java` line 24 at r9](https://reviewable.io/reviews/harness/harness-core/56825#-NlyGQu389cs5OOqs7Bw:-NlyGQu389cs5OOqs7Bx:b-6jg0b9) ([raw file](https://github.com/harness/harness-core/blob/c9fd4c4ed03f5d8e5759f19378f5b7554130a5b2/878-ng-common-utilities/src/main/java/io/harness/plancreator/stages/v1/StageParameterUtilsV1.java#L24)):*
> ```Java
> @UtilityClass
> @OwnedBy(HarnessTeam.PIPELINE)
> public class StageParameterUtilsV1 {
> ```

nit: new line for readability


<!-- Sent from Reviewable.io -->

2023-12-18 18:55 UTC, yogesh-chauhan commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java` line 68 at r9](https://reviewable.io/reviews/harness/harness-core/56825#-NlyH2BK-fm0oRwnBMy5:-NlyH2BK-fm0oRwnBMy6:b-nwovbw) ([raw file](https://github.com/harness/harness-core/blob/c9fd4c4ed03f5d8e5759f19378f5b7554130a5b2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java#L68)):*
> ```Java
>     YamlField stepsField = specField.getNode().getField(YAMLFieldNameConstants.STEPS);
>     if (stepsField == null) {
>       throw new InvalidRequestException("Steps section is required in Approval stage");
> ```

Lets set REPORT Target also as USER


<!-- Sent from Reviewable.io -->

2023-12-18 18:55 UTC, yogesh-chauhan commented
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java` line 60 at r9](https://reviewable.io/reviews/harness/harness-core/56825#-NlyHABnEGHv0WJ1Y6Ik:-NlyHABnEGHv0WJ1Y6Il:b-boxc8m) ([raw file](https://github.com/harness/harness-core/blob/c9fd4c4ed03f5d8e5759f19378f5b7554130a5b2/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1/ApprovalStagePlanCreator.java#L60)):*
> ```Java
>       PlanCreationContext ctx, ApprovalStageNodeV1 field) {
>     LinkedHashMap<String, PlanCreationResponse> planCreationResponseMap = new LinkedHashMap<>();
>     Map<String, YamlField> dependenciesNodeMap = new HashMap<>();
> ```

Lets make these final


<!-- Sent from Reviewable.io -->

2023-12-18 18:57 UTC, yogesh-chauhan reviewed
> Reviewed 3 of 5 files at r1, 2 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56825)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-19 06:19 UTC, yogesh-chauhan approved these changes

2023-12-19 06:22 UTC, sarthakkasat commented
Will address the comments by @yogesh-chauhan in next PR

2023-12-19 06:22 UTC, merged