Changes for ExecutionModeFilter All
harness/harness-core pull request #56841
Opened 2023-12-15 14:41 UTC by ayushitiwari024

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-15 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=56841) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=56841) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=56841) it.</sub>

2023-12-15 14:54 UTC, ayushitiwari024 commented
trigger smartchecks

2023-12-15 14:54 UTC, ayushitiwari024 commented
trigger uts

2023-12-15 16:07 UTC, ayushitiwari024 commented
trigger smartchecks

2023-12-15 16:09 UTC, brijeshdhakar commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 278 at r2](https://reviewable.io/reviews/harness/harness-core/56841#-NliEDqACDAJBVonXd7N:-NliEDqACDAJBVonXd7O:bsi00r0) ([raw file](https://github.com/harness/harness-core/blob/f3b38b747ef63863a479502c92acedb92c41514a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L278)):*
> ```Java
>     } else if (EmptyPredicate.isEmpty(filterIdentifier) && filterProperties != null) {
>       return filterProperties.getExecutionModeFilter();
>     }
> ```

We need to handle the case when filterIdentifier is provided. Saved filter might have a different ExecutionMode in it. 


<!-- Sent from Reviewable.io -->

2023-12-15 16:10 UTC, brijeshdhakar commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 276 at r2](https://reviewable.io/reviews/harness/harness-core/56841#-NliEUYd8YpSvaR-kTeA:-NliEUYd8YpSvaR-kTeB:bh0549c) ([raw file](https://github.com/harness/harness-core/blob/f3b38b747ef63863a479502c92acedb92c41514a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L276)):*
> ```Java
>     if (EmptyPredicate.isNotEmpty(filterIdentifier) && filterProperties != null) {
>       throw new InvalidRequestException("Can not apply both filter properties and saved filter together");
>     } else if (EmptyPredicate.isEmpty(filterIdentifier) && filterProperties != null) {
> ```

Only this 2nd condition is enough as we have already checked that both can not be non-empty. 



_Code quote:_
```Java
filterProperties != null
```


<!-- Sent from Reviewable.io -->

2023-12-16 06:13 UTC, ayushitiwari024 commented
trigger messagecheck

2023-12-16 06:18 UTC, ayushitiwari024 commented
trigger messagecheck

2023-12-16 06:45 UTC, ayushitiwari024 commented
trigger uts

2023-12-16 06:50 UTC, ayushitiwari024 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56841)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 276 at r2](https://reviewable.io/reviews/harness/harness-core/56841#-NliEUYd8YpSvaR-kTeA:-NllNtLK9KO0IDh0XbWc:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f3b38b747ef63863a479502c92acedb92c41514a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L276)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Only this 2nd condition is enough as we have already checked that both can not be non-empty.
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 278 at r2](https://reviewable.io/reviews/harness/harness-core/56841#-NliEDqACDAJBVonXd7N:-NllNubh-tsxn5zRd3g7:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/f3b38b747ef63863a479502c92acedb92c41514a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L278)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We need to handle the case when filterIdentifier is provided. Saved filter might have a different ExecutionMode in it.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-18 04:59 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 171 at r4](https://reviewable.io/reviews/harness/harness-core/56841#-NlvHnB809sN3we_5cP3:-NlvHnB809sN3we_5cP4:bnrtolz) ([raw file](https://github.com/harness/harness-core/blob/abb2377dec20fbf629454984b852d2d734832357/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L171)):*
> ```Java
>     // showAllExecution will be handled by the ExecutionModeFilter once this condition has been removed.
>     if (!showAllExecutions
>         && !(getExecutionModeFilter(accountId, orgId, projectId, filterIdentifier, filterProperties)
> ```

We can add a function that returns boolean directly


<!-- Sent from Reviewable.io -->

2023-12-18 05:01 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 177 at r4](https://reviewable.io/reviews/harness/harness-core/56841#-NlvHvFJ4EZPzYDsZXt7:-NlvHvFK7jMZis6B7Ym3:bz8v7g1) ([raw file](https://github.com/harness/harness-core/blob/abb2377dec20fbf629454984b852d2d734832357/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L177)):*
> ```Java
> 
>     Criteria filterCriteria = new Criteria();
>     if (EmptyPredicate.isNotEmpty(filterIdentifier) && filterProperties != null) {
> ```

Currently we are calling the filterIdentifier two times, can we refactor some code  such that we call this only once?
We can sync up and figure this one out.


<!-- Sent from Reviewable.io -->

2023-12-18 05:01 UTC, sahilhindwani-harness commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 281 at r4](https://reviewable.io/reviews/harness/harness-core/56841#-NlvID3b9HVuFmdEaQ0H:-NlvID3b9HVuFmdEaQ0I:b-ozki1h) ([raw file](https://github.com/harness/harness-core/blob/abb2377dec20fbf629454984b852d2d734832357/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L281)):*
> ```Java
>       return filterProperties.getExecutionModeFilter();
>     } else if (filterIdentifier != null) {
>       FilterDTO pipelineFilterDTO = this.filterService.get(
> ```

nit: this keyword is not required.


<!-- Sent from Reviewable.io -->

2023-12-20 11:15 UTC, brijeshdhakar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56841)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 292 at r5](https://reviewable.io/reviews/harness/harness-core/56841#-Nm5vREOEOdwJITqQf2d:-Nm5vREOEOdwJITqQf2e:bzcj157) ([raw file](https://github.com/harness/harness-core/blob/8c145c7559f2627460c12ba634e6c499e8dfeed8/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L292)):*
> ```Java
> 
>   public boolean isAllExecutionModeFilterPresent(FilterDTO filterDTO, PipelineExecutionFilterPropertiesDTO filterProperties){
>     if(ExecutionModeFilter.ALL.equals(filterProperties.getExecutionModeFilter())){
> ```

add a null check for `filterProperties` to avoid NullPointerException.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 295 at r5](https://reviewable.io/reviews/harness/harness-core/56841#-Nm5vYC-8DsDw8qVWLcX:-Nm5vYC-8DsDw8qVWLcY:b4ene0a) ([raw file](https://github.com/harness/harness-core/blob/8c145c7559f2627460c12ba634e6c499e8dfeed8/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L295)):*
> ```Java
>       return true;
>     }
>     else if(ExecutionModeFilter.ALL.equals(((PipelineExecutionFilterPropertiesDTO) filterDTO.getFilterProperties()).getExecutionModeFilter())) {
> ```

Same as above. Add null check.



_Code quote:_
```Java
filterDTO
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 437 at r5](https://reviewable.io/reviews/harness/harness-core/56841#-Nm5vvUF5ldqaxWZ_FSw:-Nm5vvUF5ldqaxWZ_FSx:b-z6vw1z) ([raw file](https://github.com/harness/harness-core/blob/8c145c7559f2627460c12ba634e6c499e8dfeed8/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L437)):*
> ```Java
>       ModuleInfoOperators operatorOnModules, List<Criteria> criteriaList, boolean isPipelineIdentifierPresent, FilterDTO pipelineFilterDTO) {
> //    FilterDTO pipelineFilterDTO = this.filterService.get(
> //        accountIdentifier, orgIdentifier, projectIdentifier, filterIdentifier, FilterType.PIPELINEEXECUTION);
> ```

remove the commented code.



_Code quote:_
```Java
//    FilterDTO pipelineFilterDTO = this.filterService.get(
//        accountIdentifier, orgIdentifier, projectIdentifier, filterIdentifier, FilterType.PIPELINEEXECUTION);
```


<!-- Sent from Reviewable.io -->

2023-12-22 10:35 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +    if (!showAllExecutions && !(isAllExecutionModeFilterPresent(filterDTO))) {
This can be simplified with
``` 
if (!(showAllExecutions || isAllExecutionModeFilterPresent(filterDTO))) {
...
}```

2023-12-22 10:38 UTC, sahilhindwani-harness requested changes

2023-12-22 10:38 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +      FilterDTO filterDTO = filterService.get(
Please add a check for type too
Validate if the FilterDTO is of type PIpelineExecutionFilterPropertiesDTO only.

2023-12-22 10:38 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +    }
nit: repetitive code

2023-12-22 10:38 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +    }
Also please add a null condition for filterDTO i.e filterDTO being null

2023-12-22 10:38 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +          filterCriteriaList, EmptyPredicate.isNotEmpty(pipelineIdentifier), null);
is the new argument required now?

2023-12-22 10:38 UTC, sahilhindwani-harness commented on pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
> +      boolean isPipelineIdentifierPresent, FilterDTO filterDTO) {
Is filterDTO required here?

2023-12-22 11:47 UTC, ayushitiwari024 commented
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 421 at r6](https://reviewable.io/reviews/harness/harness-core/56841#gh-1434940348:-NmGKsA721WJaXdLiVS-:bs1r545) ([raw file](https://github.com/harness/harness-core/blob/a6d2e87c94580747e560a6b3193ba71713dfebbf/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L421)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Is filterDTO required here?
</blockquote></details>

Confused. We are passing null in place of filterDTO in below method call (last parameter):
populatePipelineFilterUsingIdentifierOROperator(filterCriteria, accountId, orgId, projectId, filterIdentifier,  
    filterCriteriaList, EmptyPredicate.isNotEmpty(pipelineIdentifier), null);

Can you confirm if we should pass filterProperties that is coming as a parameter as part of formCriteriaOROperatorOnModules method?


<!-- Sent from Reviewable.io -->

2023-12-28 12:21 UTC, sahilhindwani-harness approved these changes

2023-12-28 12:32 UTC, ayushitiwari024 commented
trigger uts

2023-12-28 13:21 UTC, sandeshsalunkhegh approved these changes
LGTM

2023-12-28 13:21 UTC, sandeshsalunkhegh commented
trigger ut1, ut9, review

2023-12-31 13:11 UTC, merged