[feat]: [CDS-87082]: Add feature flag to support different infrastructure during environment propagation
harness/harness-core pull request #56878
Opened 2023-12-18 08:40 UTC by lovish1999

## Describe your changes
Add feature flag to support different infrastructure during environment propagation

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-18 09:05 UTC, lovish1999 commented
trigger commonchecks

2023-12-18 09:05 UTC, lovish1999 commented
trigger uts

2023-12-18 10:00 UTC, lovish1999 commented
trigger ut0

2023-12-18 10:00 UTC, lovish1999 commented
trigger compile

2023-12-18 10:00 UTC, lovish1999 commented
trigger codebasehash

2023-12-18 10:00 UTC, lovish1999 commented
trigger pmd

2023-12-18 11:30 UTC, lovish1999 commented
trigger ut0

2023-12-19 05:56 UTC, lovish1999 commented
trigger ut0

2023-12-20 03:00 UTC, yogesh-chauhan approved these changes

2023-12-20 06:24 UTC, tchaurasiya requested changes

2023-12-20 06:24 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
>      }
if this new FF is disabled, and environmentYaml contains useFromStage, Wont that throw exception as per below code

2023-12-20 06:24 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java
> +          EnvironmentYamlV2 useFromStageEnvironmentYaml = getUseFromStageEnvironmentYaml(filterCreationContext, env);
before calling this method shouldn't we check if env is using useFromStage?

2023-12-20 06:24 UTC, tchaurasiya commented on 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStagePlanCreator.java
> +        environment, serviceNodeId, nextNodeId, serviceType, envGroupRef, ctx, true));
nit: Though this piece of code is not in use right now, But lets make last parameter false for now. we will onboard this feature to yaml v1 later

2023-12-20 09:12 UTC, tchaurasiya approved these changes

2023-12-20 09:25 UTC, lovish1999 commented
trigger uts

2023-12-20 11:29 UTC, lovish1999 commented
trigger ut5

2023-12-20 11:29 UTC, lovish1999 commented
trigger ut6

2023-12-20 11:29 UTC, lovish1999 commented
trigger ut7

2023-12-20 11:29 UTC, lovish1999 commented
trigger ut8

2023-12-20 11:29 UTC, lovish1999 commented
trigger ut9

2023-12-20 15:25 UTC, naidu-harness commented
Review happened in other PR. Merging

2023-12-20 15:25 UTC, merged