feat: [PL-43269]: Enhancement on Move Project API
harness/harness-core pull request #56894
Opened 2023-12-18 10:20 UTC by adiyaar24

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-18 10:43 UTC, adiyaar24 commented
trigger uts

2023-12-18 10:58 UTC, ankit-harness requested changes
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56894)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/56894#-NlwZ9Cd7YMl2jPk8QlD:-NlwZ9Cd7YMl2jPk8QlE:b8srgt8) ([raw file](https://github.com/harness/harness-core/blob/03328aece91a9a1d5bbe4587568fea18f6f7586e/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java#L29)):*
> ```Java
>   public static final String RESTORE_ACTION = "restore";
>   public static final String UPDATE_ACTION = "update";
>   public static final String MOVE_ACTION = "moved";
> ```

move not moved
___
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/56894#-NlwZCzM9Ods3QMQirtP:-NlwZCzM9Ods3QMQirtQ:bb6zpli) ([raw file](https://github.com/harness/harness-core/blob/03328aece91a9a1d5bbe4587568fea18f6f7586e/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java#L53)):*
> ```Java
>   ROLE_ASSIGNMENT_DELETED,
>   MOVED
> }
> ```

MOVE


<!-- Sent from Reviewable.io -->

2023-12-18 11:07 UTC, ankit-harness submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56894)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 511 at r1](https://reviewable.io/reviews/harness/harness-core/56894#-NlwalVs0L6O3bSLZgOW:-NlwalVs0L6O3bSLZgOX:b-r00v6a) ([raw file](https://github.com/harness/harness-core/blob/03328aece91a9a1d5bbe4587568fea18f6f7586e/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L511)):*
> ```Java
>     if (optionalProject.isPresent()) {
>       Project project = optionalProject.get();
>       Project oldProject = (Project) HObjectMapper.clone(project);
> ```

Any side effects of using HObjectMapper?


<!-- Sent from Reviewable.io -->

2023-12-18 18:52 UTC, adiyaar24 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56894)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 511 at r1](https://reviewable.io/reviews/harness/harness-core/56894#-NlwalVs0L6O3bSLZgOW:-NlyGQCLCNaiDI73QRLe:b32w12) ([raw file](https://github.com/harness/harness-core/blob/03328aece91a9a1d5bbe4587568fea18f6f7586e/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L511)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any side effects of using HObjectMapper?
</blockquote></details>

No
___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/56894#-NlwZ9Cd7YMl2jPk8QlD:-NlyGS-s6tzYVsLPy-_M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03328aece91a9a1d5bbe4587568fea18f6f7586e/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

move not moved
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/56894#-NlwZCzM9Ods3QMQirtP:-NlyGUB5--L7KtTHLr-1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03328aece91a9a1d5bbe4587568fea18f6f7586e/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/Action.java#L53)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

MOVE
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-18 19:04 UTC, adiyaar24 commented
trigger uts

2023-12-26 09:08 UTC, adiyaar24 commented
trigger uts

2023-12-26 10:40 UTC, adiyaar24 commented
trigger ut7, ut8

2023-12-28 06:58 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/events/ProjectMoveEvent.java
> +  }
nit: can be covered by `@AllArgsContructor`

2023-12-29 04:00 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java
> +                         .getValue());
please handle exception case on this, thanks

2023-12-29 04:02 UTC, pbarapatre10 commented on 120-ng-manager/src/main/java/io/harness/ng/core/outbox/ProjectEventHandler.java
> +        case "ProjectMoved":
nit: we should extract this in a constant, thanks

2023-12-29 06:51 UTC, pbarapatre10 commented
trigger uts

2024-01-03 05:23 UTC, ankit-harness requested changes
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56894)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/ProjectEventHandler.java` line 74 at r4](https://reviewable.io/reviews/harness/harness-core/56894#-NnClOKm06Z3uAkXzcBS:-NnClOKm06Z3uAkXzcBT:b-upv48p) ([raw file](https://github.com/harness/harness-core/blob/ed332ada6dcb2bbbd2b9a2298bfe58b666540aee/120-ng-manager/src/main/java/io/harness/ng/core/outbox/ProjectEventHandler.java#L74)):*
> ```Java
>         case "ProjectRestored":
>           return handleProjectRestoreEvent(outboxEvent);
>         case PROJECT_MOVED:
> ```

Should we be consistent here? I agree these events type strings can be converted into a constant. But, this is also bringing in inconsistency. Maybe we can separate out constants as a separate PR


<!-- Sent from Reviewable.io -->

2024-01-03 05:59 UTC, pbarapatre10 commented
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/ProjectEventHandler.java` line 74 at r4](https://reviewable.io/reviews/harness/harness-core/56894#-NnClOKm06Z3uAkXzcBS:-NnCtnyU5yRPpcWxrs5k:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ed332ada6dcb2bbbd2b9a2298bfe58b666540aee/120-ng-manager/src/main/java/io/harness/ng/core/outbox/ProjectEventHandler.java#L74)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we be consistent here? I agree these events type strings can be converted into a constant. But, this is also bringing in inconsistency. Maybe we can separate out constants as a separate PR
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-03 06:49 UTC, ankit-harness approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56894#-:-NnD4Pkq2QkIbCkahWjj:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2024-01-03 07:18 UTC, pbarapatre10 commented
trigger uts

2024-01-03 07:40 UTC, pbarapatre10 commented
trigger ut6

2024-01-03 07:40 UTC, pbarapatre10 commented
trigger ut8

2024-01-03 07:40 UTC, pbarapatre10 commented
trigger ut9

2024-01-04 10:10 UTC, pbarapatre10 commented
trigger uts

2024-01-05 09:12 UTC, pbarapatre10 commented
trigger ut7

2024-01-05 09:13 UTC, pbarapatre10 commented
trigger ut9

2024-01-05 09:33 UTC, merged