feat: [CDS-85736]: <+stage.variables> and <+pipeline.variables> are e…
harness/harness-core pull request #56893
Opened 2023-12-18 10:17 UTC by prashantsharma04

…nding up with bad substitution error when stage and pipeline have secrets in them

todo: will be adding
## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-18 10:22 UTC, sahilhindwani-harness requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56893)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/56893#-NlwRkNN6kcQ2qp6-I2Q:-NlwRkNN6kcQ2qp6-I2R:bnakz81) ([raw file](https://github.com/harness/harness-core/blob/a53017ec5aef2e9307f8ef6f791e8602a0be9f67/pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java#L19)):*
> ```Java
> public class PmsSecretSanitizer {
>   private static final String SECRET_REGEX =
>       "\\$\\{ngSecretManager\\.obtain\\(\\\\\"[\\w|.]+\\\\\", [\\w|.|-]+\\)}|\\$\\{ngSecretManager\\.obtain\\(\\\\\\\\\\\\\"[\\w|.]+\\\\\\\\\\\\\", [\\w|.|-]+\\)}|\\$\\{sweepingOutputSecrets\\.obtain\\(\\\\\"[\\S|.]+?\\\\\",\\\\\"[\\S|.]+?\"\\)}";
> ```

Can we add test for this regex?


<!-- Sent from Reviewable.io -->

2023-12-18 23:37 UTC, sribalij commented on pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java
> +      "\\$\\{ngSecretManager\\.obtain\\(\\\\\"[\\w|.]+\\\\\", [\\w|.|-]+\\)}|\\$\\{ngSecretManager\\.obtain\\(\\\\\\\\\\\\\"[\\w|.]+\\\\\\\\\\\\\", [\\w|.|-]+\\)}|\\$\\{sweepingOutputSecrets\\.obtain
Since this is not easily readable, can you add a comment explaining the regex?

2023-12-18 23:37 UTC, sribalij commented on pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java
> +      "\\$\\{ngSecretManager\\.obtain\\(\\\\\"[\\w|.]+\\\\\", [\\w|.|-]+\\)}|\\$\\{ngSecretManager\\.obtain\\(\\\\\\\\\\\\\"[\\w|.]+\\\\\\\\\\\\\", [\\w|.|-]+\\)}|\\$\\{sweepingOutputSecrets\\.obtain
Add Junit

2023-12-18 23:37 UTC, sribalij requested changes
Added comments

2023-12-19 05:44 UTC, prashantsharma04 commented
trigger uts

2023-12-19 06:27 UTC, prashantsharma04 commented
trigger uts

2023-12-19 06:27 UTC, prashantsharma04 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56893)* status: 2 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/56893#-NlwRkNN6kcQ2qp6-I2Q:-Nm-kYBOAkZ7vZWRGlWs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a53017ec5aef2e9307f8ef6f791e8602a0be9f67/pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java#L19)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add test for this regex?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/56893#gh-1430752264:-Nm-kYYOCwiLX2oU1eIf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a53017ec5aef2e9307f8ef6f791e8602a0be9f67/pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java#L19)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Since this is not easily readable, can you add a comment explaining the regex?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/56893#gh-1430752456:-Nm-kZ0_1tUy8-iS_2Zt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a53017ec5aef2e9307f8ef6f791e8602a0be9f67/pipeline-service/service/src/main/java/io/harness/serializer/jackson/json/PmsSecretSanitizer.java#L19)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

Add Junit
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-19 09:31 UTC, prashantsharma04 commented
trigger ut6,ut7,ut8,ut9

2023-12-19 11:28 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56893)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-19 11:33 UTC, prashantsharma04 commented
trigger gitleaks

2023-12-20 01:39 UTC, sribalij approved these changes

2023-12-20 01:40 UTC, sribalij commented
trigger review

2023-12-20 03:31 UTC, prashantsharma04 commented
trigger review

2023-12-20 03:31 UTC, prashantsharma04 commented
trigger codeformat

2023-12-20 03:31 UTC, prashantsharma04 commented
trigger messagecheck

2023-12-20 03:56 UTC, prashantsharma04 commented
trigger codeformat

2023-12-20 03:57 UTC, prashantsharma04 commented
trigger uts

2023-12-20 04:11 UTC, prashantsharma04 commented
trigger messagecheck

2023-12-20 04:16 UTC, prashantsharma04 commented
trigger messagecheck

2023-12-20 04:17 UTC, merged