feat:[SSCA-1059]: Open API spec for CreateTicket
harness/harness-core pull request #56918
Opened 2023-12-18 16:12 UTC by humanshu2002

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-18 17:14 UTC, Varsha-lalwani requested changes

2023-12-18 17:14 UTC, Varsha-lalwani commented on ssca-manager/service/src/main/java/io/harness/ssca/api/CreateTicketApiImpl.java
> +public class CreateTicketApiImpl implements TicketApi{
You can add in Remediation as API will be specific to Remediation

2023-12-18 17:14 UTC, Varsha-lalwani commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +  '/v1/orgs{org}/projects/{project}/remediation/{remediation-id}/create-ticket':
have this as just remediation instead of remediation-id

2023-12-18 17:14 UTC, Varsha-lalwani commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +      properties:
Can you check from the figma what all fields are there and only add those?

2023-12-20 19:45 UTC, humanshu2002 commented
trigger uts

2023-12-20 19:56 UTC, humanshu2002 commented
trigger messagecheck

2023-12-20 20:00 UTC, humanshu2002 commented
trigger uts

2023-12-21 07:18 UTC, Varsha-lalwani requested changes
> Reviewed 12 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56918)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/beans/ticket/TicketRequestDto.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/56918#-NmADfhWAS4zf2D-YZsA:-NmADfhWAS4zf2D-YZsB:b-gxn1f0) ([raw file](https://github.com/harness/harness-core/blob/138b83359d5ba25138f07888c76a594b07b6b5dd/ssca-manager/service/src/main/java/io/harness/ssca/beans/ticket/TicketRequestDto.java#L27)):*
> ```Java
>   String priority;
>   String projectKey;
>   String title;
> ```

Can you make these fields as not null



_Code quote:_
```Java
  String priority;
  String projectKey;
  String title;
```
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/ticket/TicketServiceRestClientFactory.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/56918#-NmAEHUe0a74DaLyZ15v:-NmAEHUf7tG4hlZJs2mT:b-cweh5o) ([raw file](https://github.com/harness/harness-core/blob/138b83359d5ba25138f07888c76a594b07b6b5dd/ssca-manager/service/src/main/java/io/harness/ssca/ticket/TicketServiceRestClientFactory.java#L46)):*
> ```Java
>       return new OkHttpClient.Builder()
>           .connectionPool(Http.connectionPool)
>           .readTimeout(60, TimeUnit.SECONDS)
> ```

these values should also come from config



_Code quote:_
```Java
.readTimeout(60, TimeUnit.SECONDS)
```


<!-- Sent from Reviewable.io -->

2023-12-21 09:11 UTC, Varsha-lalwani reviewed
> Reviewed 1 of 15 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56918)* status: 1 change requests. 0 of 1 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-21 09:12 UTC, Varsha-lalwani approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56918#-:-NmAdMcg2o9j09RbuDOU:bnfp4nl)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-21 09:51 UTC, humanshu2002 commented
trigger uts

2023-12-21 11:36 UTC, humanshu2002 commented
trigger ut6,ut7,ut9

2023-12-21 12:56 UTC, humanshu2002 commented
trigger ut7,ut9

2023-12-21 13:11 UTC, humanshu2002 commented
trigger ut9

2023-12-21 13:43 UTC, merged