feat: [PL-43365]: OIDC Support for CD Tasks
harness/harness-core pull request #56937
Opened 2023-12-19 06:55 UTC by Raghav-Murali

## Describe your changes

This PR adds support for OIDC in CD GCR Task. This PR contains the changes on the SAAS side pertaining to ng-manager and the pipeline service. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-19 07:27 UTC, TarunUba1 commented on 930-oidc-core/src/main/java/io/harness/oidc/gcp/dto/GcpOidcAccessTokenRequestDTO.java
> +import lombok.*;
nit: remove this * and lets import only required entities

2023-12-19 07:27 UTC, TarunUba1 commented on 930-oidc-core/src/main/java/io/harness/oidc/gcp/dto/GcpOidcTokenRequestDTO.java
> +import lombok.*;
nit: remove this * and lets import only required entities

2023-12-19 08:20 UTC, Raghav-Murali commented on 930-oidc-core/src/main/java/io/harness/oidc/gcp/dto/GcpOidcAccessTokenRequestDTO.java
> +import lombok.*;
Done.

2023-12-19 08:20 UTC, Raghav-Murali commented on 930-oidc-core/src/main/java/io/harness/oidc/gcp/dto/GcpOidcTokenRequestDTO.java
> +import lombok.*;
Done

2023-12-19 09:11 UTC, TarunUba1 requested changes
Also please add the test files for the oidc module for better coverage and in description what all cases were tested as part of testing in general

2023-12-19 12:38 UTC, abhinavsingh1196 commented
cc: @puthrayaharness @Abhishek-CDC for review

2023-12-20 09:12 UTC, Raghav-Murali commented
trigger uts

2023-12-20 09:43 UTC, TarunUba1 approved these changes

2023-12-20 17:44 UTC, Raghav-Murali commented
trigger ut5, ut6, ut7, ut8, ut9

2023-12-21 01:44 UTC, Raghav-Murali commented
trigger ut5, ut7

2023-12-21 01:53 UTC, Raghav-Murali commented
trigger messagecheck

2023-12-21 05:05 UTC, Raghav-Murali commented
trigger ut8, ut9

2023-12-21 07:24 UTC, Raghav-Murali commented
trigger ut9

2023-12-21 07:31 UTC, Abhishek-CDC commented
Looks good from GCR artifact side

2023-12-21 07:32 UTC, Abhishek-CDC approved these changes

2023-12-21 09:04 UTC, VikasMaddukuriHarness approved these changes

2023-12-21 10:02 UTC, TarunUba1 commented
trigger ut9

2023-12-21 12:00 UTC, merged