fix:[CDS-86513]: adding retry logic for clone command
harness/harness-core pull request #56950
Opened 2023-12-19 11:21 UTC by GoelPratyush99

## Describe your changes
Added a retry logic only for clone command to avoid intermittent git failure due to git connectivity issue.
<img width="1364" alt="Screenshot 2023-12-19 at 4 27 31 PM" src="https://github.com/harness/harness-core/assets/97931011/ab1d407a-cf45-4ef1-89c6-1202b86f00fa">

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-19 11:24 UTC, GoelPratyush99 commented
trigger uts

2023-12-19 12:16 UTC, abhinavsingh1196 requested changes

2023-12-19 12:16 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +  private RetryPolicy<Object> getRetryPolicyForCloneCommand() {
this can be class level, no need to create it each time

2023-12-19 12:16 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +        .handleIf(gitClientHelper::shouldRetryGitCloneCommand)
won't this always be false? since we wrap the GitAPIException exception in GitConnectionDelegateException

2023-12-19 12:17 UTC, abhinavsingh1196 commented
screenshot does not show any retry, can be misleading.

2023-12-19 12:27 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +        .handleIf(gitClientHelper::shouldRetryGitCloneCommand)
It is while doing `gitClientHelper.checkIfGitConnectivityIssue( )` that we wrap the GitAPIException exception in GitConnectionDelegateException. ShouldRetryGitCloneCommand happens before it, hence it works.

2023-12-19 12:38 UTC, GoelPratyush99 commented
> screenshot does not show any retry, can be misleading.

Added another one with log showing retry.

2023-12-19 13:15 UTC, GoelPratyush99 commented
trigger ut8

2023-12-20 10:01 UTC, alebuh approved these changes

2023-12-20 10:10 UTC, abosii-harness requested changes

2023-12-20 10:10 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +      Failsafe.with(retryPolicyForGitClone).get(cloneCommand::call);
Will this close the call result?

2023-12-20 10:32 UTC, GoelPratyush99 commented
trigger uts

2023-12-20 10:36 UTC, GoelPratyush99 commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +      Failsafe.with(retryPolicyForGitClone).get(cloneCommand::call);
Done. Preserved the earlier behaviour.

2023-12-20 10:36 UTC, GoelPratyush99 commented
trigger uts

2023-12-20 12:06 UTC, GoelPratyush99 commented
trigger ut5, ut6, ut7, ut8, ut9

2023-12-20 12:41 UTC, abhinavsingh1196 approved these changes

2023-12-20 12:41 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java
> +      if (exception.getCause() instanceof GitAPIException) {
nit: should probably log a separate warning/error in case this condition is not met?

2023-12-20 14:47 UTC, GoelPratyush99 commented
trigger uts

2023-12-20 15:28 UTC, alebuh approved these changes

2023-12-20 16:01 UTC, markoharness approved these changes

2023-12-20 16:52 UTC, GoelPratyush99 commented
trigger review

2023-12-21 05:20 UTC, GoelPratyush99 commented
trigger ut5, ut6, ut7, ut8, ut9

2023-12-22 07:20 UTC, abosii-harness approved these changes

2023-12-22 07:24 UTC, merged