[fix]: [CDS-86605]: Fix calculating parent-type and finding the node in schema for given FQN in YAML
harness/harness-core pull request #56967
Opened 2023-12-19 17:52 UTC by brijeshdhakar

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-19 17:52 UTC, brijeshdhakar commented
trigger uts

2023-12-20 05:21 UTC, archit-harness requested changes
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56967)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/56967#-Nm4eJOx9H1mpfUji-Ru:-Nm4eJOx9H1mpfUji-Rv:bo5qmxu) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java#L74)):*
> ```Java
>           // fetch corresponding input-details for the given template yaml
>           String parentNodeType =
>               YamlInputUtils.getParentNodeTypeForGivenFQNField(new YamlNode(yamlConfig.getYamlMap()), fqn);
> ```

can we optimise this?



_Code quote:_
```Java
YamlInputUtils.getParentNodeTypeForGivenFQNField(new YamlNode(yamlConfig.getYamlMap()), fqn);
```
___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/56967#-Nm4eqgj4oCyZ70efKWd:-Nm4eqgj4oCyZ70efKWe:b-jfepef) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java#L63)):*
> ```Java
>     String fqnFromParentNode = inputFieldMetadata.getFqnFromParentNode();
>     // TODO Refactor: Use TemplateSchemaMetadata and create TemplateSchemaRequest instead of using
>     // PipelineSchemaRequest.
> ```

@brijeshdhakar can you create ticket for this


<!-- Sent from Reviewable.io -->

2023-12-20 05:46 UTC, utkarshchoubey-harness commented on 953-yaml-commons/src/main/java/io/harness/yaml/individualschema/AbstractStaticSchemaParser.java
> +  private JsonNode getFieldByFQN(JsonNode jsonNode, List<String> fqn, int currentIndex, int depth) {
can we add a desciption of what this function is doing

2023-12-20 05:46 UTC, utkarshchoubey-harness commented on 953-yaml-commons/src/main/java/io/harness/yaml/individualschema/InputFieldMetadata.java
> +  public static List<String> parentTypesOfNodeGroups = Arrays.asList("stages", "steps");
is the same for both v0 and v1 ?

2023-12-20 06:17 UTC, brijeshdhakar commented
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/56967#-Nm4eJOx9H1mpfUji-Ru:-Nm4r_lt7h-8DrjqT2lH:bsfgwio) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java#L74)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we optimise this?
</blockquote></details>

I don't see any scope of optimisation here. The existing utils work on yamlNode only. But we can pass the jsonNode from here and convert into YamlNode in the YamlInputUtils::getParentNodeTypeForGivenFQNField for better reading.


<!-- Sent from Reviewable.io -->

2023-12-20 06:18 UTC, brijeshdhakar commented
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/56967#-Nm4eqgj4oCyZ70efKWd:-Nm4ruYeDohSntQV4NUU:b-rx4pgr) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar can you create ticket for this
</blockquote></details>

Created the ticket: https://harness.atlassian.net/browse/CDS-87227


<!-- Sent from Reviewable.io -->

2023-12-20 06:18 UTC, brijeshdhakar commented
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/56967#-Nm4eqgj4oCyZ70efKWd:-Nm4ryUxD31C_-RsBGNB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java#L63)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Created the ticket: https://harness.atlassian.net/browse/CDS-87227
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-20 07:31 UTC, brijeshdhakar commented
*[`953-yaml-commons/src/main/java/io/harness/yaml/individualschema/InputFieldMetadata.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/56967#gh-1432273275:-Nm57KZt6j0swcPtv7y-:b3wd8xd) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/953-yaml-commons/src/main/java/io/harness/yaml/individualschema/InputFieldMetadata.java#L28)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

is the same for both v0 and v1 ?
</blockquote></details>

Yes, This list is the parent of nodeGroups. And we start our FQN from the next path of these. 


<!-- Sent from Reviewable.io -->

2023-12-20 08:07 UTC, brijeshdhakar commented
trigger uts

2023-12-20 08:07 UTC, brijeshdhakar reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56967)* status: 12 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/individualschema/AbstractStaticSchemaParser.java` line 173 at r1](https://reviewable.io/reviews/harness/harness-core/56967#gh-1432271881:-Nm5G14Z1R3TqOf35nF4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/953-yaml-commons/src/main/java/io/harness/yaml/individualschema/AbstractStaticSchemaParser.java#L173)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

can we add a desciption of what this function is doing
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/56967#-Nm4eJOx9H1mpfUji-Ru:-Nm5G2pK9si-ylNHvxN5:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/71fd4338ef66e61b568ada52e1928367da229fe9/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/InputsSchemaServiceImpl.java#L74)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I don't see any scope of optimisation here. The existing utils work on yamlNode only. But we can pass the jsonNode from here and convert into YamlNode in the YamlInputUtils::getParentNodeTypeForGivenFQNField for better reading.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-20 08:21 UTC, brijeshdhakar commented
trigger uts

2023-12-20 08:43 UTC, brijeshdhakar commented
trigger uts

2023-12-20 08:57 UTC, utkarshchoubey-harness approved these changes
lgtm!

2023-12-20 09:16 UTC, brijeshdhakar commented
trigger ut7 ut8 ut9

2023-12-20 09:50 UTC, archit-harness approved these changes
> Reviewed 1 of 12 files at r1, 3 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56967)* status: 12 file(s) to review. 2. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-12-20 09:57 UTC, brijeshdhakar commented
trigger ut8 ut9

2023-12-20 10:22 UTC, brijeshdhakar commented
trigger ut7 ut9 review

2023-12-20 10:35 UTC, brijeshdhakar commented
trigger ut8

2023-12-20 11:22 UTC, merged