fix:[CCM-14986] Added more secrets to ce-nextgen charts
harness/harness-core pull request #57000
Opened 2023-12-20 10:00 UTC by riyasyash

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/57000)

2023-12-20 10:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=57000) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=57000) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=57000) it.</sub>

2023-12-20 10:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=57000) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=57000) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=57000) it.</sub>

2023-12-20 10:25 UTC, sdsingh07 commented on ce-nextgen/chart/templates/deployment.yaml
> +            {{- include "harnesscommon.secrets.manageAppEnv" (dict "ctx" $ "variableName" "FAKTORY_PASSWORD" "defaultKubernetesSecretName" "nextgen-ce" "defaultKubernetesSecretKey" "FAKTORY_PASSWORD"
Do we need `FAKTORY_PASSWORD` in env? I think `FAKTORY_URL` will work.

2023-12-21 03:55 UTC, hitesharinga requested changes
test request change icon

2023-12-21 03:55 UTC, hitesharinga approved these changes

2023-12-21 03:58 UTC, hitesharinga requested changes
test r

2023-12-21 03:59 UTC, hitesharinga submitted a review, later dismissed

2023-12-21 09:14 UTC, riyasyash commented on ce-nextgen/chart/templates/deployment.yaml
> +            {{- include "harnesscommon.secrets.manageAppEnv" (dict "ctx" $ "variableName" "FAKTORY_PASSWORD" "defaultKubernetesSecretName" "nextgen-ce" "defaultKubernetesSecretKey" "FAKTORY_PASSWORD"
we needed faktory password to be replaced from the external secret @sdsingh07 
But now we have removed the password setting from here after discussing with Nikunj since the password is not supported by JAVA client for faktory

2023-12-21 09:16 UTC, riyasyash commented
trigger messagecheck

2023-12-21 09:30 UTC, sdsingh07 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57000#-:-NmAhXqV4UE9wpHHBWvo:bnfp4nl)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-21 09:30 UTC, sujeesh-harness approved these changes

2023-12-21 09:54 UTC, sandyydk approved these changes

2023-12-21 11:01 UTC, abhinavsingh-ccm approved these changes

2023-12-22 06:00 UTC, kapilgarg1996 approved these changes

2023-12-22 06:00 UTC, merged