fix: [CDS-80231]: adds Header support in custom webhook notification method
harness/harness-core pull request #57001
Opened 2023-12-20 10:04 UTC by sandeshsalunkhegh

fix: [CDS-80231]: adds Header support in custom webhook notification method

Issue: Headers were not supported for webhook notification method.

Changes: Added support for headers in PmsWebhookChannel for Webhook Notification method and added empty map for other methods for header.

Testing: Tested on local.
Webhook Link: https://webhook-test.com/?address=5cb57a3296fd7d1ac8b8bde332da6a3a
Request:
```yaml
pipeline:
  name: dateValueFix_1
  identifier: dateValueFix_1
  projectIdentifier: Project_1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: date
        identifier: date
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          if [[ $mydate =~ [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(Z|\+[0-9]{4})$ ]]
                          then
                            echo "ISO date";
                          else
                            echo "Malformed date";
                          fi
                    environmentVariables:
                      - name: mydate
                        type: String
                        value: <+input>
                    outputVariables: []
                    delegateSelectors:
                      - localdelegate
                  timeout: 10m
        tags: {}
  delegateSelectors:
    - platform-delegate-cd
  notificationRules:
    - name: test_notify_1
      identifier: test_notify_1
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://webhook-test.com/5cb57a3296fd7d1ac8b8bde332da6a3a
          headers:
            Accept: "*/*"
            Accept-Language: en-GB,en;q=0.9
            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9 eyJhY2NvdW50SWQiOiJrbXB5U21VSVNpbW9SckpMNk5MNzN3IiwiYXV0aFRva2VuIjoiUEFSNzl0WTBmdk0zYnlKQTJVYnBJSUVubUZlTFh4MW8iLCJpc3MiOiJIYXJuZXNzIEluYyIsIm5hbWUiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwidXNySWQiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwiZXhwIjoxNzAyNjM2Njc5LCJlbnYiOiIiLCJ0eXBlIjoiVVNFUiIsImlhdCI6MTcwMjU1MDI3OSwiZW1haWwiOiJhZG1pbkBoYXJuZXNzLmlvIiwidXNlcm5hbWUiOiJBZG1pbiJ9.inVJ_W83FFjD37PWA6Iig_nF6dLPlNm8hhXPUptD84k
            Connection: keep-alive
            Cookie: intercom-id-iw4sgfzm=f7550b6f-caaf-4ca6-997f-269e86520b8d; intercom-session-iw4sgfzm=; intercom-device-id-iw4sgfzm=57d2f0b2-cc58-49e7-b40e-3c39b7768dd5; ajs_anonymous_id=9f0b7d92-bc7c-4a67-a665-a990248e2065; ajs_user_id=admin@harness.io; ADRUM=s=1702550279071&r=https%3A%2F%2Flocalhost%3A8181%2Fauth%2F%3Fhash%3D358787835
            Origin: https://localhost:8181
            Referer: https://localhost:8181/ng/account/kmpySmUISimoRrJL6NL73w/home/orgs/default/projects/Project_1/pipelines/dateValueFix_1/pipeline-studio/?storeType=INLINE
            Sec-Fetch-Dest: empty
            Sec-Fetch-Mode: cors
            Sec-Fetch-Site: same-origin
            User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
            content-type: application/json
            sec-ch-ua: "\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\""
            sec-ch-ua-mobile: "?0"
            sec-ch-ua-platform: "\"macOS\""
            content-length: 10000
      enabled: true

```

Response:
```json
{
    "status": "SUCCESS",
    "data": {
        "yaml": "{\"pipeline\":{\"__uuid\":\"YRGHZddXQHmw0vxQPLAZsg\",\"name\":\"zyC9bgRISKu3ffZ9i0yQIw\",\"identifier\":\"dateValueFix_1\",\"description\":\"8REOmQztQtqOiBOGFeDKyw\",\"tags\":{\"__uuid\":\"D1JOTz6MTdO7PeVCpqc-ww\"},\"stages\":[{\"__uuid\":\"i3fK6DMHSya9g3mnE-yGpw\",\"stage\":{\"identifier\":\"date\",\"name\":\"nxCVsrtbShy4aJW69cY09A\",\"description\":\"AYh5MEbxRqmYqMKMdafvMQ\",\"when\":\"AjIqUCpnQvmi_kw_MzNWig\",\"tags\":{\"__uuid\":\"h9Ib6-ncRZ6n_ek6eDfIRQ\"},\"delegateSelectors\":\"pBEArAxFSzWhPyiAfdqTUA\",\"timeout\":\"Wt7BUhpzTLaMYYN7BajnMQ\",\"__uuid\":\"WTTHdkJTSJ24iXvOA5X_BA\",\"type\":\"Custom\",\"spec\":{\"__uuid\":\"m6Sr9TVGS-OxvJ_CyxVQoQ\",\"execution\":{\"__uuid\":\"x3i4P6FGR12BvJ0jn9OvKg\",\"steps\":[{\"__uuid\":\"fkLwIuQJRcefN0whNpcepg\",\"step\":{\"identifier\":\"ShellScript_1\",\"name\":\"mAgCMl3rQpOrEsGljP-7MA\",\"description\":\"k6pnRxHiRMqni6l5fX7CCw\",\"when\":\"2NF4JKKUT3O5eibu9ErGyg\",\"timeout\":\"ivLs9rpYRgqCJL6X7Ctz7g\",\"__uuid\":\"N6ZNGOxXTQiaoCLiy6OhLQ\",\"type\":\"ShellScript\",\"spec\":{\"shell\":\"Bash\",\"source\":{\"__uuid\":\"71phEKMKS2yIxau9yyjvfA\",\"type\":\"Inline\",\"spec\":{\"script\":\"vEoCeiAiRHyzawzjvYEcgQ\",\"type\":\"Inline\"}},\"executionTarget\":\"u0LLv5csR5OkS6PHSSbUQA\",\"onDelegate\":\"J6brgwyJQnyrOwsp3AV9eQ\",\"delegateSelectors\":[\"localdelegate\"],\"includeInfraSelectors\":\"p46I6AlKSHqceqBatinI4Q\",\"environmentVariables\":[{\"name\":\"mydate\",\"type\":\"String\",\"value\":\"DLa8WvT4TK2VebfP-aIxCA\",\"required\":false,\"__uuid\":\"J1sFC09-Q8KxNST_tfuHww\"}],\"__uuid\":\"wqxSqjp9SnSHyDxNiI-APw\"}}}]}}}}],\"notificationRules\":[{\"name\":\"test_notify_1\",\"enabled\":true,\"pipelineEvents\":[{\"type\":\"AllEvents\"},{\"type\":\"PipelineStart\"},{\"type\":\"PipelineEnd\"},{\"type\":\"PipelineSuccess\"},{\"type\":\"PipelineFailed\"},{\"type\":\"StageFailed\"},{\"type\":\"StageSuccess\"},{\"type\":\"StageStart\"},{\"type\":\"StepFailed\"}],\"notificationMethod\":{\"type\":\"Webhook\",\"spec\":{\"webhookUrl\":\"https://webhook-test.com/5cb57a3296fd7d1ac8b8bde332da6a3a\",\"headers\":{\"Accept\":\"*/*\",\"Accept-Language\":\"en-GB,en;q=0.9\",\"Authorization\":\"Bearer eyJhbGciOiJIUzI1NiJ9 eyJhY2NvdW50SWQiOiJrbXB5U21VSVNpbW9SckpMNk5MNzN3IiwiYXV0aFRva2VuIjoiUEFSNzl0WTBmdk0zYnlKQTJVYnBJSUVubUZlTFh4MW8iLCJpc3MiOiJIYXJuZXNzIEluYyIsIm5hbWUiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwidXNySWQiOiJsdjBldVJoS1JDeWlYV3pTN3BPZzZnIiwiZXhwIjoxNzAyNjM2Njc5LCJlbnYiOiIiLCJ0eXBlIjoiVVNFUiIsImlhdCI6MTcwMjU1MDI3OSwiZW1haWwiOiJhZG1pbkBoYXJuZXNzLmlvIiwidXNlcm5hbWUiOiJBZG1pbiJ9.inVJ_W83FFjD37PWA6Iig_nF6dLPlNm8hhXPUptD84k\",\"Connection\":\"keep-alive\",\"Cookie\":\"intercom-id-iw4sgfzm=f7550b6f-caaf-4ca6-997f-269e86520b8d; intercom-session-iw4sgfzm=; intercom-device-id-iw4sgfzm=57d2f0b2-cc58-49e7-b40e-3c39b7768dd5; ajs_anonymous_id=9f0b7d92-bc7c-4a67-a665-a990248e2065; ajs_user_id=admin@harness.io; ADRUM=s=1702550279071&r=https%3A%2F%2Flocalhost%3A8181%2Fauth%2F%3Fhash%3D358787835\",\"Origin\":\"https://localhost:8181\",\"Referer\":\"https://localhost:8181/ng/account/kmpySmUISimoRrJL6NL73w/home/orgs/default/projects/Project_1/pipelines/dateValueFix_1/pipeline-studio/?storeType=INLINE\",\"Sec-Fetch-Dest\":\"empty\",\"Sec-Fetch-Mode\":\"cors\",\"Sec-Fetch-Site\":\"same-origin\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\",\"content-type\":\"application/json\",\"sec-ch-ua\":\"\\\"Not_A Brand\\\";v=\\\"8\\\", \\\"Chromium\\\";v=\\\"120\\\", \\\"Google Chrome\\\";v=\\\"120\\\"\",\"sec-ch-ua-mobile\":\"?0\",\"sec-ch-ua-platform\":\"\\\"macOS\\\"\",\"content-length\":\"10000\",\"__uuid\":\"VOlN-pAhQXa0bs1zlVBKSw\"}}}}],\"orgIdentifier\":\"default\",\"projectIdentifier\":\"Project_1\",\"allowStageExecutions\":false,\"delegateSelectors\":[\"platform-delegate-cd\"]},\"__uuid\":\"9D6Kc1sDTHqL8WpPYbzwjQ\"}",
        "metadataMap": {
            "Wt7BUhpzTLaMYYN7BajnMQ": {
                "yamlProperties": {
                    "fqn": "pipelin [...]

2023-12-20 10:28 UTC, brijeshdhakar requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57001)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/notification/src/main/java/io/harness/notification/channeldetails/NotificationChannel.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/57001#-Nm5kwb_Dvggk3GzCAWJ:-Nm5kwb_Dvggk3GzCAWK:bwmwdga) ([raw file](https://github.com/harness/harness-core/blob/d41a627ac11a5f1436f80fc06dc0028e0c583300/clients/notification/src/main/java/io/harness/notification/channeldetails/NotificationChannel.java#L46)):*
> ```Java
>   String templateId;
>   Map<String, String> templateData;
>   Map<String, String> headers;
> ```

Why do we need headers here? Its already present in the `WebhookChannel` that extends this class.
___
*[`clients/notification/src/main/java/io/harness/notification/channeldetails/WebhookChannel.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/57001#-Nm5lDGC5iMzOCtRUvbI:-Nm5lDGC5iMzOCtRUvbJ:b-pa9xat) ([raw file](https://github.com/harness/harness-core/blob/d41a627ac11a5f1436f80fc06dc0028e0c583300/clients/notification/src/main/java/io/harness/notification/channeldetails/WebhookChannel.java#L52)):*
> ```Java
>     this.projectIdentifier = projectIdentifier;
>     this.expressionFunctorToken = expressionFunctorToken;
>     this.headers = headers;
> ```

already setting headers here. No need to pass on to super constructor.



_Code quote:_
```Java
this.headers = headers;
```


<!-- Sent from Reviewable.io -->

2023-12-20 11:53 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57001)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/notification/src/main/java/io/harness/notification/channeldetails/NotificationChannel.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/57001#-Nm5kwb_Dvggk3GzCAWJ:-Nm63Pb6-EHjnzfzjiUR:bss4a2b) ([raw file](https://github.com/harness/harness-core/blob/d41a627ac11a5f1436f80fc06dc0028e0c583300/clients/notification/src/main/java/io/harness/notification/channeldetails/NotificationChannel.java#L46)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why do we need headers here? Its already present in the `WebhookChannel` that extends this class.
</blockquote></details>

Removed.
___
*[`clients/notification/src/main/java/io/harness/notification/channeldetails/WebhookChannel.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/57001#-Nm5lDGC5iMzOCtRUvbI:-Nm63dhN2gwjFSIWQbut:b-cszsw0) ([raw file](https://github.com/harness/harness-core/blob/d41a627ac11a5f1436f80fc06dc0028e0c583300/clients/notification/src/main/java/io/harness/notification/channeldetails/WebhookChannel.java#L52)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

already setting headers here. No need to pass on to super constructor.
</blockquote></details>

Modified.


<!-- Sent from Reviewable.io -->

2023-12-20 11:53 UTC, sandeshsalunkhegh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57001)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/notification/src/main/java/io/harness/notification/channeldetails/NotificationChannel.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/57001#-Nm5kwb_Dvggk3GzCAWJ:-Nm63iQ15sMhWGPPo6r7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d41a627ac11a5f1436f80fc06dc0028e0c583300/clients/notification/src/main/java/io/harness/notification/channeldetails/NotificationChannel.java#L46)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Done.
___
*[`clients/notification/src/main/java/io/harness/notification/channeldetails/WebhookChannel.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/57001#-Nm5lDGC5iMzOCtRUvbI:-Nm63k6S8dRtCupNxwVV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d41a627ac11a5f1436f80fc06dc0028e0c583300/clients/notification/src/main/java/io/harness/notification/channeldetails/WebhookChannel.java#L52)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Modified.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-20 18:49 UTC, sandeshsalunkhegh commented
trigger ut5

2023-12-21 09:52 UTC, brijeshdhakar approved these changes
> Reviewed 1 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57001)* status: 7 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-22 04:38 UTC, sahilhindwani-harness commented
*[`953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/57001#-NmEoErD9MYkLEuXyZmU:-NmEoErD9MYkLEuXyZmV:b-oxwr9v) ([raw file](https://github.com/harness/harness-core/blob/ab7b73a8fdad03f4f64cac80239b08b59cf9782f/953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java#L40)):*
> ```Java
> public class PmsWebhookChannel extends PmsNotificationChannel {
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> webhookUrl;
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_MAP_CLASSPATH) Map<String, String> headers;
> ```

Please update static schema for the same if required.


<!-- Sent from Reviewable.io -->

2023-12-22 04:39 UTC, sahilhindwani-harness commented
please check for the following tests as well:
- One of the header value as expression (pipeline variables)
- One of the header value as secret.

Please share the screenshot for the same.





<!-- Sent from Reviewable.io -->

2023-12-22 05:39 UTC, sandeshsalunkhegh commented
> please check for the following tests as well:
> 
> * One of the header value as expression (pipeline variables)
> * One of the header value as secret.
> 
> Please share the screenshot for the same.

Webhook URL: https://webhook-test.com/payload/f50fb63a-d06d-4f11-ba48-7ac0690558f7
YAML:
```yaml
pipeline:
  name: dateValueFix_1
  identifier: dateValueFix_1
  projectIdentifier: Project_1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: date
        identifier: date
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          if [[ $mydate =~ [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(Z|\+[0-9]{4})$ ]]
                          then
                            echo "ISO date";
                          else
                            echo "Malformed date";
                          fi
                    environmentVariables:
                      - name: mydate
                        type: String
                        value: <+input>
                    outputVariables: []
                    delegateSelectors:
                      - localdelegate
                  timeout: 10m
        tags: {}
  delegateSelectors:
    - platform-delegate-cd
  notificationRules:
    - name: test_notify_1
      identifier: test_notify_1
      pipelineEvents:
        - type: AllEvents
        - type: PipelineStart
        - type: PipelineEnd
        - type: PipelineSuccess
        - type: PipelineFailed
        - type: StageFailed
        - type: StageSuccess
        - type: StageStart
        - type: StepFailed
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://webhook-test.com/5cb57a3296fd7d1ac8b8bde332da6a3a
          headers:
            Accept: "*/*"
            Accept-Language: en-GB,en;q=0.9
            Connection: keep-alive
            Origin: https://localhost:8181
            Referer: <+pipeline.variables.var_1>
            User-Agent: <+pipeline.variables.var_3>
            content-type: application/json
      enabled: true
  variables:
    - name: var_1
      type: String
      description: ""
      required: false
      value: "\"N/A\""
    - name: var_3
      type: Secret
      description: ""
      required: false
      value: test_secret

```

2023-12-22 07:47 UTC, sandeshsalunkhegh commented
> _[`953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/57001#-NmEoErD9MYkLEuXyZmU:-NmEoErD9MYkLEuXyZmV:b-oxwr9v) ([raw file](https://github.com/harness/harness-core/blob/ab7b73a8fdad03f4f64cac80239b08b59cf9782f/953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java#L40)):_
> 
> > ```java
> > public class PmsWebhookChannel extends PmsNotificationChannel {
> >   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> webhookUrl;
> >   @ApiModelProperty(dataType = SwaggerConstants.STRING_MAP_CLASSPATH) Map<String, String> headers;
> > ```
> 
> Please update static schema for the same if required.

Raised a PR with the change: https://github.com/harness/harness-schema/pull/274
CC: @sahilhindwani-harness

2023-12-22 07:51 UTC, archit-harness approved these changes

2023-12-22 07:54 UTC, sandeshsalunkhegh commented
trigger ut6, ut7, ut8, ut9

2023-12-22 08:06 UTC, sahilhindwani-harness commented
*[`953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/57001#-NmEoErD9MYkLEuXyZmU:-NmFZ0I7ApBUh_EJhGnb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ab7b73a8fdad03f4f64cac80239b08b59cf9782f/953-yaml-commons/src/main/java/io/harness/notification/channelDetails/PmsWebhookChannel.java#L40)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Raised a PR with the change: https://github.com/harness/harness-schema/pull/274
CC: @sahilhindwani-harness 

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-22 08:07 UTC, sahilhindwani-harness approved these changes
> Reviewed 1 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57001)* status: <span>:shipit:</span> complete! ✓



<!-- Sent from Reviewable.io -->

2023-12-22 08:47 UTC, sandeshsalunkhegh commented
trigger ut9

2023-12-22 09:40 UTC, merged