feat: [PL-43387]: Add support to migrate smp file secret
harness/harness-core pull request #57016
Opened 2023-12-20 16:59 UTC by meenakshi-harness

## Describe your changes
Add support in `fileMigration` api to migrate secrets in SMP en from CG to NG. This is case where encrypted file is stored in mongo.

Testing:
1. Migrated CG secret in NG through this API and tested secret decrypt in git connector using file secret.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-21 11:18 UTC, meenakshi-harness reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57016)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 362 at r1](https://reviewable.io/reviews/harness/harness-core/57016#-NmB14rS2fyOsPvSi5Wy:-NmB5-r74Rfla3Lh0RG-:b3ift21) ([raw file](https://github.com/harness/harness-core/blob/f07b3e327ca0ddeec4a1ad782376b76923987553/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L362)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Do we need new argument encryptedFileContent? encryptedValue can be used to pass the file content.
</blockquote></details>

Yes but it can be confusing for caller as well as for us to have validation in case of SMP env


<!-- Sent from Reviewable.io -->

2023-12-21 12:16 UTC, lasdox commented on 100-migrator/src/main/java/io/harness/ngmigration/client/NGClient.java
> +      @Query("encryptedFileContent") String encryptedFileContent, @Part("spec") RequestBody spec);
Is it possible to have limitations for big file contents?

2023-12-22 07:18 UTC, meenakshi-harness commented on 100-migrator/src/main/java/io/harness/ngmigration/client/NGClient.java
> +      @Query("encryptedFileContent") String encryptedFileContent, @Part("spec") RequestBody spec);
Removed from query param and moved to form data

2023-12-22 07:19 UTC, meenakshi-harness commented
trigger uts

2023-12-22 07:22 UTC, meenakshi-harness commented
trigger uts

2023-12-22 08:35 UTC, nishantsaini20 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57016)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 362 at r1](https://reviewable.io/reviews/harness/harness-core/57016#-NmB14rS2fyOsPvSi5Wy:-NmFeCzqDqXEh6cYEKBc:b-drxgbo) ([raw file](https://github.com/harness/harness-core/blob/f07b3e327ca0ddeec4a1ad782376b76923987553/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L362)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Yes but it can be confusing for caller as well as for us to have validation in case of SMP env
</blockquote></details>

How does it relate to smp? The current logic of creating file secret also works for both SMP and SAAS. How does it matter here?


<!-- Sent from Reviewable.io -->

2023-12-22 09:31 UTC, nishantsaini20 approved these changes
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57016)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 362 at r1](https://reviewable.io/reviews/harness/harness-core/57016#-NmB14rS2fyOsPvSi5Wy:-NmFqvaE9bYVNYQC3iDC:b13xlk2) ([raw file](https://github.com/harness/harness-core/blob/f07b3e327ca0ddeec4a1ad782376b76923987553/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L362)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

How does it relate to smp? The current logic of creating file secret also works for both SMP and SAAS. How does it matter here?
</blockquote></details>

As discussed since this is migration specific, we decided to go with extra parameter.


<!-- Sent from Reviewable.io -->

2023-12-22 11:54 UTC, meenakshi-harness commented
trigger uts

2023-12-22 13:16 UTC, lasdox approved these changes

2023-12-22 13:25 UTC, meenakshi-harness commented
trigger uts

2023-12-26 06:17 UTC, meenakshi-harness commented
trigger ut9

2023-12-26 06:18 UTC, meenakshi-harness commented
trigger messagecheck

2023-12-26 13:01 UTC, lasdox approved these changes

2023-12-26 13:01 UTC, merged