feat: [CDS-86005] Add logic for saving K8s Traffic Routing Metadata in Release
harness/harness-core pull request #57046
Opened 2023-12-21 10:56 UTC by alebuh

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-21 11:53 UTC, alebuh commented
trigger uts

2023-12-21 13:42 UTC, abosii-harness requested changes

2023-12-21 13:42 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
> +  public static final String RELEASE_SECRET_TRAFFIC_ROUTING_INFO_NAME = "harness.io/traffic-routing-info/name";
this wouldn't work, you can a dns domain as prefix and / but not multiple /
Can we just store everything as one annotation and just following a specific format? Or we can just use json

2023-12-21 15:37 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseConstants.java
> +  public static final String RELEASE_SECRET_TRAFFIC_ROUTING_INFO_NAME = "harness.io/traffic-routing-info/name";
done

2023-12-21 15:37 UTC, alebuh commented
trigger uts

2023-12-21 16:10 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +  private String trafficRoutingInfoName;
Wouldn't it better to put it a single object?

2023-12-21 16:26 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sLegacyRelease.java
> +  private String trafficRoutingInfoName;
I was not sure if this object should be serialized/deserialized anywhere so I followed the same format as it's for helm chart info, but I think you are right, we can keep it as a single object.
Changed now

2023-12-21 16:26 UTC, abosii-harness approved these changes

2023-12-21 16:27 UTC, alebuh commented
trigger uts

2023-12-21 17:58 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
> +        K8sReleaseSecretHelper.putAnnotationsItem(
will it be beneficial to compress this JSON (and b64 encode) and then store it? k8s secrets with declarative rollback store the release manifests also, so we need as much space for them as possible. 
Although, if this object `TrafficRoutingInfoDTO` is not very huge, so there may not be much benefit. But if it grows in future, then compressing it later will need to handle backward compatibility. In that case it's best to do it now itself

2023-12-21 21:11 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
> +        K8sReleaseSecretHelper.putAnnotationsItem(
I don't think it's worth doing it, as I don't expect this object to grow. We were thinking of storing resource yaml as encoded into release, but this came as a better solution.

2023-12-21 21:13 UTC, alebuh commented
trigger ut5,ut6,ut7,ut9

2023-12-22 06:00 UTC, alebuh commented
trigger ut5,ut7,ut9

2023-12-22 06:46 UTC, alebuh commented
/rebase

2023-12-22 06:48 UTC, alebuh commented
trigger uts

2023-12-22 07:51 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sRelease.java
> +        K8sReleaseSecretHelper.putAnnotationsItem(
In that case, we can skip doing this

2023-12-22 07:52 UTC, abhinavsingh1196 approved these changes

2023-12-22 08:22 UTC, markoharness approved these changes

2023-12-22 08:30 UTC, TarunUba1 approved these changes

2023-12-22 08:46 UTC, GoelPratyush99 approved these changes

2023-12-22 08:48 UTC, alebuh commented
trigger ut0,ut5,ut7,ut9

2023-12-22 10:11 UTC, alebuh commented
trigger ut7,review

2023-12-22 11:25 UTC, merged