feat: [CDS-82614] Add logic for Traffic Routing in K8s BG swap step [delegate]
harness/harness-core pull request #57083
Opened 2023-12-22 11:56 UTC by alebuh

Adding logic for traffic routing in the BG Swap step. When we execute the swap step and change selectors from stage to stable service, we should update the TrafficRouting resource to send all traffic to the new Stable service. To do this we will use the Patch method with information persisted in the Release. (Resource name, API version, and plural).
We will print the patch that will be applied and updated resource:
<img width="1504" alt="Screenshot 2023-12-22 at 11 29 48" src="https://github.com/harness/harness-core/assets/98389528/4691b3f0-2d3d-493e-8ae9-c640a0543431">
Each provider should implement a method for the creation of the patch.

Additionally added two fixes:
1. All args, and No Args constructor for TrafficRoutingDTO because serialization/deserialization requires it
2. If routes are not presented return empty collection to avoid NPE
## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-22 11:56 UTC, alebuh commented
trigger uts

2023-12-22 11:59 UTC, alebuh commented
trigger commonchecks

2023-12-22 13:53 UTC, alebuh commented
trigger commonchecks, uts

2023-12-22 14:24 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +        LogLevel.INFO, CommandExecutionStatus.RUNNING);
`logCallback.saveExecutionLog(message)` should by default take the loglevel as INFO and status as RUNNING

2023-12-22 14:24 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    if (swapServicePatch.isPresent()) {
nit: all below nested if/else can be simplified if we use inverse conditions? like 
if (swapServicePatch.isEmpty()){
  log("message")
  return;
}

...

2023-12-22 14:24 UTC, abhinavsingh1196 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    Map<String, Object> map = new ObjectMapper().convertValue(patchedObject, Map.class);
convertValue can throw IllegalArgumentException, should we handle that?

2023-12-22 14:24 UTC, abhinavsingh1196 commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        log.error(message);
just curious, we'll just log our failure to patch and continue with the overall execution?

2023-12-22 17:28 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +        LogLevel.INFO, CommandExecutionStatus.RUNNING);
changed

2023-12-22 17:29 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    if (swapServicePatch.isPresent()) {
done

2023-12-22 17:30 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    Map<String, Object> map = new ObjectMapper().convertValue(patchedObject, Map.class);
I don't expect this to happen. If patching succeeds we will get the object back, if it fails it will be null so I'm not sure that IllegalArgumentException will ever happen

2023-12-22 17:34 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        log.error(message);
I feel like that's the right thing to do, as at this point we already swapped service selectors, and I don't see the point of failing the whole step if updating the destination fails. We just print a warning and the customer may update it by themself if patching fails. 
This is just a suggestion, if you think that we should fail it we can discuss it?

2023-12-22 17:34 UTC, alebuh commented
trigger uts

2023-12-25 09:28 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactory.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/57083#-NmVHmu-75ZWVbAWfro8:-NmVHmu-75ZWVbAWfro9:b-gkb7ee) ([raw file](https://github.com/harness/harness-core/blob/e7575e4aba29fd962eaed8df4104bb630abcdb93/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactory.java#L49)):*
> ```Java
>         return Optional.empty();
>     }
>     return resourceCreator.getSwapTrafficRoutingPatch(stable);
> ```

nit: Since this is a Factory class I would just create additional method for creating specific resource creator class and then call getSwapTrafficRoutingPatch(stable) in the original calling method 

something like this
TrafficRoutingResourceCreatorFactory.create(plural).getSwapTrafficRoutingPatch(stable)


<!-- Sent from Reviewable.io -->

2023-12-25 09:29 UTC, markoharness submitted a review, later dismissed
> Reviewed 13 of 15 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57083)* status: 15 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-12-25 11:00 UTC, alebuh reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57083)* status: 15 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactory.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/57083#-NmVHmu-75ZWVbAWfro8:-NmVc_QM96aMsLWBHCsn:b-6z8dbw) ([raw file](https://github.com/harness/harness-core/blob/e7575e4aba29fd962eaed8df4104bb630abcdb93/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/TrafficRoutingResourceCreatorFactory.java#L49)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

nit: Since this is a Factory class I would just create additional method for creating specific resource creator class and then call getSwapTrafficRoutingPatch(stable) in the original calling method 

something like this
TrafficRoutingResourceCreatorFactory.create(plural).getSwapTrafficRoutingPatch(stable)
</blockquote></details>

good point, changed now


<!-- Sent from Reviewable.io -->

2023-12-25 11:28 UTC, alebuh commented
trigger uts

2023-12-25 12:03 UTC, markoharness submitted a review, later dismissed
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57083)* status: 15 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 



<!-- Sent from Reviewable.io -->

2023-12-26 06:36 UTC, abosii-harness requested changes

2023-12-26 06:36 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        log.error(message);
It should fail, from the deployment perspective we weren't able to bring it to desired state so user should be aware of it

2023-12-26 06:36 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreator.java
> +          List.of(VirtualServiceDetails.builder()
I believe we should include both services (stage and primary)

2023-12-26 08:12 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/trafficrouting/IstioTrafficRoutingResourceCreator.java
> +          List.of(VirtualServiceDetails.builder()
added stage destination as well

2023-12-26 08:13 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        log.error(message);
added error handling (execution will fail with HintException) if this method returns null

2023-12-26 08:15 UTC, alebuh commented
/rebase

2023-12-26 08:21 UTC, alebuh commented
trigger uts

2023-12-26 08:32 UTC, abosii-harness commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        log.error(message);
I don't think this is a good idea, we're losing the context of why it failed, it's better to propagate the error and if you want to add more details just try catch it

2023-12-26 09:01 UTC, alebuh commented on 960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java
> +        log.error(message);
done

2023-12-26 09:11 UTC, alebuh commented
trigger uts

2023-12-26 11:49 UTC, GoelPratyush99 commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    Map<String, Object> map = new ObjectMapper().convertValue(patchedObject, Map.class);
If it fails and returns null then we should handle the NPE for
`map.remove("metadata");`

2023-12-26 11:53 UTC, GoelPratyush99 reviewed
Please add cd-deployments and cd-kubernetes labels

2023-12-26 11:56 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sSwapServiceSelectorsBaseHandler.java
> +    Map<String, Object> map = new ObjectMapper().convertValue(patchedObject, Map.class);
It should never return a null. If it fails it will throw an exception, if it succeeds it will return an object that can be transformed into a map

2023-12-26 12:34 UTC, markoharness approved these changes
> Reviewed 9 of 11 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57083)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2023-12-26 12:55 UTC, GoelPratyush99 approved these changes

2023-12-26 13:05 UTC, TarunUba1 approved these changes

2023-12-27 09:28 UTC, alebuh commented
trigger review

2023-12-27 09:37 UTC, abosii-harness approved these changes

2023-12-27 09:38 UTC, alebuh commented
trigger review

2023-12-27 10:10 UTC, alebuh commented
trigger review

2023-12-27 12:24 UTC, alebuh commented
trigger review

2023-12-27 12:26 UTC, merged