feat:[CODE-1200]: add support for repoSize as String
harness/harness-core pull request #57081
Opened 2023-12-22 10:40 UTC by akhilpandey1

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-22 14:45 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/CodeModuleLicense.java
> +  String maxRepoSizeString;
Can you explain a bit why we are adding a maxRepoSizeString as we already have maxRepoSizeInBytes? Why we would duplicate it in maxRepo and are we planning to enforce both in the future?

2023-12-22 14:47 UTC, Xin-Harness requested changes

2023-12-22 14:47 UTC, Xin-Harness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java
> +        .maxRepoSizeInBytes(DataSize.parse(codeModuleLicenseDTO.getMaxRepoSizeString()).toBytes())
This looks a little odd to me as we just converting string to byte but add both in DTO which we only need String as data transfer object as my understanding.

2023-12-28 17:48 UTC, akhilpandey1 commented on 930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/CodeModuleLicense.java
> +  String maxRepoSizeString;
removed

2023-12-28 17:51 UTC, akhilpandey1 commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java
> +        .maxRepoSizeInBytes(DataSize.parse(codeModuleLicenseDTO.getMaxRepoSizeString()).toBytes())
so UI requires string value and backend communication depends on long byte value for repo sizes.
Current approach makes sure that the string that is received from the user via DTO while creating the license gets converted to the correct byte value, which is now stored in the db via CodeModuleLicense.

2023-12-28 17:58 UTC, johannesHarness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java
> +            .numberOfRepositories(5)
**minor** should number of repos also be constants?

2023-12-28 18:00 UTC, johannesHarness commented on 970-ng-commons/src/main/java/io/harness/entities/ModuleType.java
> +  @JsonProperty("CODE") CODE("Code", PUBLIC, ONBOARDED),
move it out of the internal "section" (comment above states below are internal modules)

2023-12-28 18:01 UTC, johannesHarness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java
> +  private String GIBSuffix = "GiB";
make it a constant

2023-12-28 18:04 UTC, johannesHarness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java
> +    if (codeModuleLicenseDTO.getMaxRepoSizeString().isEmpty()) {
**minor** since we return both bytes and string - we could also take both as input, and use whatever is provided? And if someone provides both or neither we return an error?

2023-12-28 18:05 UTC, johannesHarness submitted a review, later dismissed

2023-12-28 19:30 UTC, akhilpandey1 commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java
> +  private String GIBSuffix = "GiB";
done

2023-12-28 19:30 UTC, akhilpandey1 commented on 970-ng-commons/src/main/java/io/harness/entities/ModuleType.java
> +  @JsonProperty("CODE") CODE("Code", PUBLIC, ONBOARDED),
thx, done

2023-12-28 19:31 UTC, akhilpandey1 commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java
> +    if (codeModuleLicenseDTO.getMaxRepoSizeString().isEmpty()) {
sure, let me create a ticket we can discuss?
Current requirement was a string as input and we kept bytes in the DTO for backend systems.

2023-12-28 19:39 UTC, akhilpandey1 commented on 930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java
> +            .numberOfRepositories(5)
done

2023-12-28 19:46 UTC, akhilpandey1 commented
trigger smartchecks

2023-12-28 22:54 UTC, Xin-Harness requested changes
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57081)* status: 6 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseSummaryHelper.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/57081#-Nmmc4ra-umVJrQLz8Zw:-Nmmc4ra-umVJrQLz8Zx:b-grajj6) ([raw file](https://github.com/harness/harness-core/blob/e7e4097d5e6912f0ace6f5e09ea23b8bae5103cb/930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseSummaryHelper.java#L223)):*
> ```Java
>             codeLicenseSummaryDTO.setNumberOfRepositories(codeModuleLicenseDTO.getNumberOfRepositories());
>             codeLicenseSummaryDTO.setMaxRepoSizeInBytes(codeModuleLicenseDTO.getMaxRepoSizeInBytes());
>             codeLicenseSummaryDTO.setMaxRepoSizeString(codeModuleLicenseDTO.getMaxRepoSizeString());
> ```

maxRepoSizeString was removed and why we are still keeping it here?
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java` line 47 at r4](https://reviewable.io/reviews/harness/harness-core/57081#-NmmcDG5CigqZnLOBmZO:-NmmcDG5CigqZnLOBmZP:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/e7e4097d5e6912f0ace6f5e09ea23b8bae5103cb/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java#L47)):*
> ```Java
>         return builder.numberOfDevelopers(ENTERPRISE_TRIAL_DEVELOPERS)
>             .numberOfRepositories(Integer.valueOf(UNLIMITED))
>             .maxRepoSizeString(REPO_SIZE_ENTERPRISE.toString())
> ```

Same as above
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/57081#gh-1435130672:-NmmcWjs6MMYcE6G09Do:b-72y0i4) ([raw file](https://github.com/harness/harness-core/blob/1a851e9252fb8b8917ae3dd62beaec3f5b832f39/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java#L43)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

so UI requires string value and backend communication depends on long byte value for repo sizes.
Current approach makes sure that the string that is received from the user via DTO while creating the license gets converted to the correct byte value, which is now stored in the db via CodeModuleLicense.
</blockquote></details>

Can't we just store string in db? 
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/57081#-NmmcGAf8Ko3619MNHjK:-NmmcGAf8Ko3619MNHjL:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/e7e4097d5e6912f0ace6f5e09ea23b8bae5103cb/930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java#L33)):*
> ```Java
>         .numberOfDevelopers(moduleLicense.getNumberOfDevelopers())
>         .numberOfRepositories(moduleLicense.getNumberOfRepositories())
>         .maxRepoSizeString(toGibiByteString(moduleLicense.getMaxRepoSizeInBytes()))
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-12-29 08:16 UTC, johannesHarness commented on 930-ng-license-manager/src/main/java/io/harness/licensing/mappers/modules/CodeLicenseObjectMapper.java
> +    if (codeModuleLicenseDTO.getMaxRepoSizeString().isEmpty()) {
hmm but the DTO is used for input and output, right. that's why I was proposing the above.
I agree that requirement was string so we can keep it - but from api perspective it seems weird. either the object shouldn't have a byte input, or should support it (and not just blindly ignore it).

Ticket sounds is fine to me :)

2023-12-29 08:17 UTC, johannesHarness approved these changes

2023-12-29 08:18 UTC, johannesHarness approved these changes
> Reviewed 3 of 8 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57081)* status: 1 change requests. 4. unresolved discussions. 



<!-- Sent from Reviewable.io -->

2023-12-29 08:20 UTC, johannesHarness commented
*[`930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseSummaryHelper.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/57081#-Nmmc4ra-umVJrQLz8Zw:-NmodvbeEzLtWPwlFgQf:b-3rslp6) ([raw file](https://github.com/harness/harness-core/blob/e7e4097d5e6912f0ace6f5e09ea23b8bae5103cb/930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseSummaryHelper.java#L223)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

maxRepoSizeString was removed and why we are still keeping it here?
</blockquote></details>

We want the user to provide a string to avoid accidental misconfigurations of the value in bytes as it can go in billions (if a support engineer configures 400MB instead of 4GB that could cause issues).
Hence, the input is in string.


<!-- Sent from Reviewable.io -->

2023-12-30 19:42 UTC, akhilpandey1 commented
trigger smartchecks

2024-01-04 13:38 UTC, akhilpandey1 commented
trigger uts

2024-01-04 13:42 UTC, abhinav-harness commented
@Xin-Harness we will merge this today

2024-01-04 16:55 UTC, abhinav-harness commented
trigger ut5, ut7, ut8

2024-01-04 17:37 UTC, abhinav-harness commented
trigger uts

2024-01-04 17:38 UTC, abhinav-harness approved these changes

2024-01-04 17:43 UTC, abhinav-harness commented
trigger uts

2024-01-04 17:43 UTC, abhinav-harness approved these changes

2024-01-04 20:00 UTC, merged