feat: [SSCA-1140]: Adding resource and service layers for Exemption workflow
harness/harness-core pull request #57114
Opened 2023-12-26 11:43 UTC by dhruv-harness

## Describe your changes

- Adding resource impl for exemption API
- Adding service and impl for exemption workflow
- Adding mapper util class
- Updating exemption custom repo to provide create method which takes care of populating uuid and createdAt fields
- Updating API spec to use common limit and page params and list of status to use enum dto
- Adding User client to use users details APIs

UTs will be present in next PR.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-26 11:43 UTC, dhruv-harness commented
trigger uts

2023-12-26 15:32 UTC, dhruv-harness commented
trigger uts

2023-12-27 03:58 UTC, reetika04 commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +             $ref: '#/components/schemas/ExemptionStatusDTO'
Missing DTO?

2023-12-27 04:01 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustomImpl.java
> +      exemptionRequest.setUuid(UUID.randomUUID().toString());
mongo automatically sets _id as a random string. Are we not using that?

2023-12-27 04:04 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustomImpl.java
> +    if (Objects.isNull(exemptionRequest.getCreatedAt())) {
You can directly use the annotation @CreatedDate Long createdAt; in the DB entity. You don't have to manually set it here.

2023-12-27 04:06 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/ssca/api/ExemptionsApiImpl.java
> +      exemptionInitiatorDTO = new ExemptionInitiatorDTO();
Can we move this to ExemptionInitiatorDTOMapper class as this is being used everywhere.

2023-12-27 04:10 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +    if (StringUtils.isNotBlank(artifactId)) {
Wouldn't artifactId either be null or a string? Do we need this if condition?

2023-12-27 04:13 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +    if (CollectionUtils.isNotEmpty(exemptionStatusDTOs)) {
What are these exemptionStatusDTOs are they part of the filter for exemptions? Can we create a ExemptionFilterBody?

2023-12-27 04:15 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +      createdExemption = existingExemptions.get(0);
In this case should we throw exemption already exists error?

2023-12-27 06:40 UTC, dhruv-harness commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +             $ref: '#/components/schemas/ExemptionStatusDTO'
I am afraid I did not understand your question @reetika04 , can you please elaborate?

2023-12-27 06:40 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustomImpl.java
> +      exemptionRequest.setUuid(UUID.randomUUID().toString());
Mongo uses ObjectId if the _id is not set by us. Using ObjectId requires conversion or mapping when used in queries, which is especially painful during manual debugging. Hence I am manually setting it with uuid string

2023-12-27 06:40 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustomImpl.java
> +    if (Objects.isNull(exemptionRequest.getCreatedAt())) {
You are correct, but that works only when MongoDB sets the _id itself. If the _id is being set by the application layer, the @CreatedDate annotation doesn't work.

2023-12-27 06:40 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +    if (StringUtils.isNotBlank(artifactId)) {
Without the if condition, the query will become like `where artifactId is null` which is not the intention. If the artifactId is not part of the query params, the search results should be agnostic of it.

2023-12-27 06:40 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +    if (CollectionUtils.isNotEmpty(exemptionStatusDTOs)) {
These are coming from the query params. I don't think we should create a filter body (and convert this method from GET to POST) for a few query params. If the number increases, we can revisit this.

2023-12-27 06:40 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +      createdExemption = existingExemptions.get(0);
Yes, I will change this to throw an exception

2023-12-27 06:40 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/ssca/api/ExemptionsApiImpl.java
> +      exemptionInitiatorDTO = new ExemptionInitiatorDTO();
The mapper class is being used to convert DTO to entities and vice-versa. Here, I am populating the request dto itself from the API params. 
I can extract this as a private method in the same class

2023-12-27 06:42 UTC, reetika04 commented on ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustomImpl.java
> +      exemptionRequest.setUuid(UUID.randomUUID().toString());
can we name this identifier instead then?

2023-12-27 07:27 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustomImpl.java
> +      exemptionRequest.setUuid(UUID.randomUUID().toString());
@reetika04 what is the difference between _id and identifier?

2023-12-27 07:30 UTC, Varsha-lalwani requested changes

2023-12-27 07:30 UTC, Varsha-lalwani commented on ssca-manager/service/src/main/java/io/harness/ssca/entities/OperatorEntity.java
> +public enum OperatorEntity {
OperatorEnum is exactly the same

2023-12-27 07:30 UTC, Varsha-lalwani commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +  private Map<String, String> fetchUsers(List<Exemption> exemptions) {
Instead of adding it here, can you add a userService and add it there. It will be used in other services as well. You can take list of userIds as params

2023-12-27 07:45 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/ssca/entities/OperatorEntity.java
> +public enum OperatorEntity {
While the values are the same, I do not want to use the same enum class for both API and entity. This breaks abstraction. I am using a mapper to map these two.

2023-12-27 07:46 UTC, dhruv-harness commented on ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java
> +  private Map<String, String> fetchUsers(List<Exemption> exemptions) {
You are correct, I am adding that change in the next PR

2023-12-27 12:00 UTC, Varsha-lalwani approved these changes

2023-12-27 12:24 UTC, reetika04 approved these changes

2023-12-27 15:13 UTC, dhruv-harness commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +        '200':
While I was also thinking the same way, we should also return the URI of the created resource with 201, which we are not doing. Hence I changed it to 200 and returned the newly created resource in the response

2023-12-27 15:20 UTC, mankrit-singh approved these changes

2023-12-27 15:20 UTC, mankrit-singh commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +        '200':
201 with response is the right way to go, please add it in the next PR

2023-12-27 15:21 UTC, dhruv-harness commented on ssca-manager/contracts/openapi/v1/openapi.yaml
> +        '200':
Discussed, will the response code to 201 while including the saved entity

2023-12-27 15:22 UTC, merged