[feat]: [CDS-86007]: adding traffic routing delegate task logic for config option
harness/harness-core pull request #57118
Opened 2023-12-26 15:29 UTC by markoharness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2023-12-27 08:18 UTC, alebuh requested changes
Please make sure that logic for creation of resources works when stable and stage are null (as in this step it will always be the case) and when we have multiple destinations as I didn't test that scenario

2023-12-27 08:18 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java
> +      currentReleaseNumber = latestRelease.getReleaseNumber();
Shouldn't we increase the release number here?

2023-12-27 08:18 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java
> +      if (useDeclarativeRollback && isEmpty(releaseHistory)) {
isEmpty(releaseHistory) this condition is already covered, here it will always be true

2023-12-27 08:18 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java
> +  void prepareForTrafficRouting(K8sTrafficRoutingRequest k8sTrafficRoutingRequest,
nit: I noticed that we have the same logic under this prepareForTrafficRouting for all steps (Checking if trafficRouting is null, getting apiVersions, creating trafficResources) We can maybe think of extracting this into some existing helper class, or create a new one just for traffic routing. Anyway we can do it either now, or in some future PR

2023-12-27 08:18 UTC, alebuh commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java
> +    if (K8sTrafficRoutingConfigType.CONFIG.equals(k8sTrafficRoutingRequest.getTrafficRoutingConfigType())) {
nit: I feel like this condition logically should be inside prepareForTrafficRoutingMethod as we

2023-12-27 08:19 UTC, alebuh commented
> Please make sure that logic for the creation of resources works when stable and stage are null (as in this step it will always be the case) and when we have multiple destinations as I didn't test that scenario

NVM, I just saw screenshoot

2023-12-27 09:34 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 158 at r1](https://reviewable.io/reviews/harness/harness-core/57118#gh-1436830186:-NmebPW4D6ZspPaBd-9c:b-r0cqg3) ([raw file](https://github.com/harness/harness-core/blob/e672e15b3de1921a693ac16700148ad1fad7e0d5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L158)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: I noticed that we have the same logic under this prepareForTrafficRouting for all steps (Checking if trafficRouting is null, getting apiVersions, creating trafficResources) We can maybe think of extracting this into some existing helper class, or create a new one just for traffic routing. Anyway we can do it either now, or in some future PR 
</blockquote></details>

True, but request object is not the same nor stable and stage services are used in Traffic Routing step. 
We can check how and if it makes sense to create common method and do it in a future PR.


<!-- Sent from Reviewable.io -->

2023-12-27 09:35 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/57118#gh-1436832268:-NmebyJm6alJP1uPydbj:b-o40kgh) ([raw file](https://github.com/harness/harness-core/blob/e672e15b3de1921a693ac16700148ad1fad7e0d5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L102)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: I feel like this condition logically should be inside prepareForTrafficRoutingMethod as we 
</blockquote></details>

I would like to keep it where it is, because we will have different preparation and application/patching in case of Config and Inherit.


<!-- Sent from Reviewable.io -->

2023-12-27 09:36 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/57118#gh-1436826673:-NmecIJ006AP5cuel3iY:b-yba0vi) ([raw file](https://github.com/harness/harness-core/blob/e672e15b3de1921a693ac16700148ad1fad7e0d5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L145)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

Shouldn't we increase the release number here?
</blockquote></details>

I was thinking if the step comes after BG/Canary step then we should just reuse the same release. 


<!-- Sent from Reviewable.io -->

2023-12-27 09:42 UTC, abosii-harness requested changes

2023-12-27 09:42 UTC, abosii-harness commented on 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java
> +    k8sTaskHelperBase.saveRelease(
Can you please explain what is the logic behind this release history? Why traffic routing should update a release? It should be an independent step or I'm missing something?

2023-12-27 14:54 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/57118#gh-1436827631:-NmflF4y7cxaWWlL7CCq:b-s7uo4r) ([raw file](https://github.com/harness/harness-core/blob/e672e15b3de1921a693ac16700148ad1fad7e0d5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L148)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

isEmpty(releaseHistory) this condition is already covered, here it will always be true
</blockquote></details>

removed this logic after an offline discussion


<!-- Sent from Reviewable.io -->

2023-12-27 14:55 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 190 at r1](https://reviewable.io/reviews/harness/harness-core/57118#gh-1436886069:-NmflONMBQ5iuI8qbFbA:b-s7uo4r) ([raw file](https://github.com/harness/harness-core/blob/e672e15b3de1921a693ac16700148ad1fad7e0d5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L190)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can you please explain what is the logic behind this release history? Why traffic routing should update a release? It should be an independent step or I'm missing something?
</blockquote></details>

removed this logic after an offline discussion


<!-- Sent from Reviewable.io -->

2023-12-27 14:58 UTC, mdmilic approved these changes
Approving delegate owned changes

2023-12-27 23:38 UTC, markoharness commented
trigger smartchecks,uts

2023-12-27 23:46 UTC, markoharness commented
trigger compile,checkstylecodeformat,messagecheck,commonchecks,pmd,codebasehash,gitleaks

2023-12-28 01:06 UTC, markoharness commented
trigger uts

2023-12-28 01:12 UTC, markoharness commented
trigger uts

2023-12-28 07:35 UTC, markoharness commented
trigger uts

2023-12-28 09:35 UTC, alebuh requested changes
> Reviewed 1 of 6 files at r1, 18 of 26 files at r2, 7 of 7 files at r3, 2 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57118)* status: 31 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team,k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java` line 118 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjdI6C8po2Jnc7uxSR:-NmjdI6C8po2Jnc7uxSS:bcbaabd) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java#L118)):*
> ```Java
> 
>     K8sTrafficRoutingConfig k8sTrafficRoutingConfig =
>         fetchTrafficRoutingConfig(k8sTrafficRoutingStepParameters, trafficRoutingInfoDTO);
> ```

nit: Might be better to add this object in K8sTrafficRoutingRequest directly and not through K8sTrafficRoutingConfig. I don't think that we need one more layer in wrapping
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java` line 132 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-Nmjgldh6i2GYcI_gcVl:-Nmjgldh6i2GYcI_gcVm:bg2b0jl) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java#L132)):*
> ```Java
> 
>     if (cdStepHelper.shouldPassReleaseMetadata(accountId)) {
>       k8sTrafficRoutingRequestBuilder.releaseMetadata(
> ```

for what we need releaseMetadata?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 159 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjgOsl8p93UIqzpBI3:-NmjgOsl8p93UIqzpBI4:bz4asdm) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L159)):*
> ```Java
>     if (!releaseHistory.isEmpty()) {
>       latestRelease = releaseHistory.getLatestRelease();
>       currentReleaseNumber = latestRelease.getReleaseNumber();
> ```

do we need currentReleaseNumber now?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 194 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjhLrK3HQ1Wy7cHo0T:-NmjhLrK3HQ1Wy7cHo0U:bbjeyzp) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L194)):*
> ```Java
>     }
> 
>     logCallback.saveExecutionLog("Traffic Routing configuration was not provided.", WARN);
> ```

We should throw an exception and fail if TrafficRoutingConfig is not provided
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 212 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-Nmjldwl6NMXcdguSQ1U:-Nmjldwl6NMXcdguSQ1V:b-rjergs) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L212)):*
> ```Java
>         trafficRoutingConfig.getDestinationsNormalizationInfo();
>     if (destinationsNormalizationInfo != null) {
>       logCallback.saveExecutionLog("Configured destinations weights will be normalized:", WARN);
> ```

we need to log this only if there is a need for normalization right? If don't change anything we should not log it?
___
*[`delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java` line 559 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjlQ4lEk36cOShPxt4:-NmjlQ4lEk36cOShPxt5:b-bcgxto) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java#L559)):*
> ```Java
>     kryo.register(K8sTrafficRoutingResponse.class, 20002013);
>     kryo.register(K8sTrafficRoutingConfigType.class, 20002014);
>     kryo.register(TrafficRoutingInfoDTO.class, 20002016);
> ```

we registered it twice


<!-- Sent from Reviewable.io -->

2023-12-28 10:20 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java` line 118 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjdI6C8po2Jnc7uxSR:-Nmjw4d38Zc-g2kr9j3m:bh72e02) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java#L118)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: Might be better to add this object in K8sTrafficRoutingRequest directly and not through K8sTrafficRoutingConfig. I don't think that we need one more layer in wrapping
</blockquote></details>

It makes no difference in my opinion. However i changed it.


<!-- Sent from Reviewable.io -->

2023-12-28 10:21 UTC, markoharness commented
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java` line 132 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-Nmjgldh6i2GYcI_gcVl:-NmjwDyr-uzMVtiZdXdy:b-nf9gnl) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/asyncsteps/K8sTrafficRoutingStep.java#L132)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

for what we need releaseMetadata?
</blockquote></details>

No need for it. Removed it


<!-- Sent from Reviewable.io -->

2023-12-28 10:21 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 159 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjgOsl8p93UIqzpBI3:-NmjwGDs6X-tnCyBizEB:b-pyrbqy) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L159)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

do we need currentReleaseNumber now?
</blockquote></details>

No. Removed.


<!-- Sent from Reviewable.io -->

2023-12-28 10:21 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 194 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjhLrK3HQ1Wy7cHo0T:-NmjwHsKB_UDOsnP7CRj:b499q7j) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L194)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

We should throw an exception and fail if TrafficRoutingConfig is not provided
</blockquote></details>

Changed


<!-- Sent from Reviewable.io -->

2023-12-28 10:21 UTC, markoharness commented
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java` line 212 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-Nmjldwl6NMXcdguSQ1U:-NmjwR_q3VhE7Xa2k6GH:b-a2ujfl) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sTrafficRoutingRequestHandler.java#L212)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

we need to log this only if there is a need for normalization right? If don't change anything we should not log it?
</blockquote></details>

Changed.


<!-- Sent from Reviewable.io -->

2023-12-28 10:22 UTC, markoharness commented
*[`delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java` line 559 at r6](https://reviewable.io/reviews/harness/harness-core/57118#-NmjlQ4lEk36cOShPxt4:-NmjwUGX0PjcaUNRmLbX:b-a2ujfl) ([raw file](https://github.com/harness/harness-core/blob/79cbaffa62dbc8d7a530d85e7f84fcd514c300cf/delegate/src/main/java/io/harness/kryo/registrars/K8sNgTaskRegister.java#L559)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

we registered it twice
</blockquote></details>

Changed.


<!-- Sent from Reviewable.io -->

2023-12-28 10:22 UTC, markoharness commented
trigger uts

2023-12-28 10:25 UTC, alebuh approved these changes
> Reviewed 1 of 2 files at r5, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57118)* status: 34 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 



<!-- Sent from Reviewable.io -->

2023-12-28 10:32 UTC, abosii-harness submitted a review, later dismissed

2023-12-28 10:39 UTC, mdmilic approved these changes

2023-12-28 12:03 UTC, markoharness commented
trigger uts

2023-12-28 12:04 UTC, mdmilic approved these changes

2023-12-28 12:05 UTC, alebuh approved these changes

2023-12-28 12:05 UTC, markoharness commented
trigger review

2023-12-28 12:21 UTC, abosii-harness approved these changes

2023-12-28 13:55 UTC, merged