feat: [PL-43140]: Central certificate management, create certificate API
harness/harness-core pull request #57209
Opened 2024-01-02 11:08 UTC by nishantsaini20

## Describe your changes
Create API for Ng-Certificate feature

### Testing
1. Create a new certificate at account, org and project scopes via text as input
2. Create a new certificate at account, org and project scopes via file as input

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2024-01-03 08:49 UTC, pbarapatre10 commented on 120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/entities/NgCertificate.java
> +  @NotEmpty String name;
nit: we can add the `NGEntityName` if it is intended to follow NG entity name convention, thanks

2024-01-03 08:56 UTC, pbarapatre10 commented on 120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/mapper/NgCertificateMapper.java
> +      dnInfoMap.put(bcStyle, rdns.length > 0 ? IETFUtils.valueToString(rdns[0].getFirst().getValue()) : null);
nit: can rdns can ever be null? we can have the notNull check just in case, thanks

2024-01-03 09:02 UTC, pbarapatre10 commented on 120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/mapper/NgCertificateMapper.java
> +        throw new UnsupportedOperationException("This cannot be extracted from DTO");
minor: can we enhance the exception message here

2024-01-03 09:07 UTC, pbarapatre10 commented on 120-ng-manager/modules/ng-certificates/src/main/java/io/harness/ngcertificates/services/NgCertificateService.java
> +public interface NgCertificateService {
nit: Add `OwnedBy`

2024-01-04 05:00 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57209)* status: 25 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 2045 at r3](https://reviewable.io/reviews/harness/harness-core/57209#-NnHq-y00qKYUfP-K9Ag:-NnHq-y14ZoBemudXzwD:b1rzixo) ([raw file](https://github.com/harness/harness-core/blob/115950e1d2f1ccea874cd50d3fdeb037e5a50ce2/120-ng-manager/contracts/openapi/v1/openapi.yaml#L2045)):*
> ```YAML
>       description: Retrieves the list of certificates in account scope
>     post:
>       summary: ''
> ```

shouldn't we populate summary fields for post?


<!-- Sent from Reviewable.io -->

2024-01-04 05:01 UTC, Jimit09Gandhi reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57209)* status: 25 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 2070 at r3](https://reviewable.io/reviews/harness/harness-core/57209#-NnHqEdg5T-9iHamD7MV:-NnHqEdg5T-9iHamD7MW:b-jv4900) ([raw file](https://github.com/harness/harness-core/blob/115950e1d2f1ccea874cd50d3fdeb037e5a50ce2/120-ng-manager/contracts/openapi/v1/openapi.yaml#L2070)):*
> ```YAML
>       summary: Your GET endpoint
>       tags:
>         - Org Certificate
> ```

nit:  Organization Certificate


<!-- Sent from Reviewable.io -->

2024-01-04 07:53 UTC, Jimit09Gandhi requested changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57209)* status: 25 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NgCertificateModule.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/57209#-NnISTaaBJ_TtlvFy5SV:-NnISTab0Q12d5CIZD8p:b-5s5ehv) ([raw file](https://github.com/harness/harness-core/blob/115950e1d2f1ccea874cd50d3fdeb037e5a50ce2/120-ng-manager/src/main/java/io/harness/ng/NgCertificateModule.java#L25)):*
> ```Java
>   protected void configure() {
>     bind(NextGenConfiguration.class).toInstance(config);
>     bind(NgCertificateService.class).to(NgCertificateServiceImpl.class);
> ```

Why is this needed ?



_Code snippet:_
```Java
bind(NextGenConfiguration.class).toInstance(config);
```


<!-- Sent from Reviewable.io -->

2024-01-04 13:02 UTC, Jimit09Gandhi reviewed
> Reviewed 6 of 21 files at r1, 2 of 2 files at r3, 4 of 4 files at r4, 13 of 13 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57209)* status: 25 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2024-01-04 13:02 UTC, Jimit09Gandhi approved these changes
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57209)* status: 25 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2024-01-04 13:31 UTC, nishantsaini20 commented
trigger uts

2024-01-04 13:31 UTC, pbarapatre10 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +    x-displayName: 'Account Certificates [Beta]'
nit: should be 'Org Certificates [Beta]'

2024-01-04 13:31 UTC, pbarapatre10 commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +    x-displayName: 'Account Certificates [Beta]'
nit: same as above

2024-01-04 13:34 UTC, pbarapatre10 submitted a review, later dismissed

2024-01-05 04:49 UTC, nishantsaini20 commented
trigger uts

2024-01-08 04:32 UTC, pbarapatre10 approved these changes

2024-01-08 04:35 UTC, pbarapatre10 submitted a review, later dismissed

2024-01-08 04:49 UTC, nishantsaini20 commented
trigger uts

2024-01-10 05:38 UTC, nishantsaini20 commented
trigger uts

2024-01-10 07:37 UTC, nishantsaini20 commented
trigger ut5, ut6, ut7, ut8, ut9

2024-01-10 10:42 UTC, nishantsaini20 commented
trigger ut5, ut6, ut7, ut8

2024-01-10 13:12 UTC, nishantsaini20 commented
trigger messagecheck

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +      responses: {}
no response here?

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        name: org
please use the global org path param

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        name: project
same here

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        certificateValue:
should be in snake case

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        certificateDetails:
here too

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        createdAt:
created and updated

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        validTo:
snake case for this object

2024-01-10 13:15 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        organisation:
snake case for commonName and this should be organization (American)

2024-01-11 06:10 UTC, nishantsaini20 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57209)* status: 26 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 2041 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447368849:-NnqpWyo09yGViGUuWtm:b-wy3adl) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L2041)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

no response here?
</blockquote></details>

This will be coming in subsequent PRs. All the APIs are marked internal for time being.
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 2065 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447369370:-NnqyEr63V13LwkZ6zW2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L2065)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

please use the global org path param
</blockquote></details>

Done.
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 2101 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447369697:-NnqyFa-6qj4wmJFKDt5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L2101)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 3521 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447370460:-NnqyIcX1DXsVKxbQdAw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L3521)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

should be in snake case
</blockquote></details>

Done.
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 3591 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447370775:-NnqyJeP6XP2pntM9qxY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L3591)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 3593 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447370889:-NnqyKAUEsj1oo-XUR7f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L3593)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

created and updated
</blockquote></details>

Done.
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 3618 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447371094:-NnqyL_c1hsNe55SMwKD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L3618)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

snake case for this object
</blockquote></details>

Done.
___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 3646 at r10](https://reviewable.io/reviews/harness/harness-core/57209#gh-1447371474:-Nnr85g46ZSsMDyQvoty:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d651aa2069668197c467d39e2ff5badf3e70cf7c/120-ng-manager/contracts/openapi/v1/openapi.yaml#L3646)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

snake case for commonName and this should be organization (American)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-11 06:16 UTC, nishantsaini20 commented
trigger uts

2024-01-11 06:26 UTC, mankrit-singh commented on 120-ng-manager/contracts/openapi/v1/openapi.yaml
> +        created_at:
should be `created` and `updated`

2024-01-11 07:12 UTC, nishantsaini20 commented
trigger uts

2024-01-11 07:26 UTC, nishantsaini20 reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57209)* status: 26 file(s) to review. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/contracts/openapi/v1/openapi.yaml` line 3581 at r11](https://reviewable.io/reviews/harness/harness-core/57209#gh-1448345135:-NnrPaz5DcdGp54Leb_7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c8d5a5e140a467c4ca00df5e3585500ffe7621a/120-ng-manager/contracts/openapi/v1/openapi.yaml#L3581)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

should be `created` and `updated`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-11 09:41 UTC, nishantsaini20 commented
trigger ut1, ut9

2024-01-11 13:49 UTC, pbarapatre10 approved these changes

2024-01-11 14:02 UTC, mankrit-singh approved these changes

2024-01-12 07:13 UTC, merged