feat:[CDS-88165]: Add logs to check how many secrets does not have pe…
harness/harness-core pull request #57394
Opened 2024-01-09 12:29 UTC by Aninditaa-ch

…rmission to access secrets using SecretFunctor

## Describe your changes
Changes added to get the logs for the case in which user without the secrets permission is running the pipeline.
Testing: Tested that the logs were being registered with the necessary information. Changes were implemented as required, after running the pipeline. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/57394)

2024-01-09 12:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/harness-core?pullRequest=57394) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/harness-core?pullRequest=57394) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/harness-core?pullRequest=57394) it.</sub>

2024-01-10 07:12 UTC, sahilhindwani-harness commented
Please add the following to PR description:
- What testing was done? If no testing was done, please mention the same on the ticket.

2024-01-10 07:14 UTC, sahilhindwani-harness requested changes

2024-01-10 07:14 UTC, sahilhindwani-harness commented on pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/SecretFunctor.java
> +    try (PmsSecurityContextEventGuard securityContextEventGuard = new PmsSecurityContextEventGuard(ambiance)) {
This seems to be not in sync with the changes mentioned in the ticket, could you please check once?

2024-01-10 12:24 UTC, Aninditaa-ch commented
trigger uts

2024-01-11 05:26 UTC, Aninditaa-ch reviewed
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57394)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/SecretFunctor.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/57394#gh-1446967160:-Nnqz3m7CHDC2qUILjIu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a7c076606ca12294cd7ee863edada077871842a/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/SecretFunctor.java#L52)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This seems to be not in sync with the changes mentioned in the ticket, could you please check once?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-11 05:35 UTC, sahilhindwani-harness requested changes

2024-01-11 10:17 UTC, Aninditaa-ch commented
trigger SmartPRChecks
trigger uts

2024-01-11 10:23 UTC, Aninditaa-ch commented
run code-formatter

2024-01-11 10:59 UTC, Aninditaa-ch commented
trigger code-formatter
trigger uts

2024-01-11 11:10 UTC, Aninditaa-ch commented
trigger uts

2024-01-11 11:20 UTC, sahilhindwani-harness submitted a review, later dismissed

2024-01-11 12:53 UTC, Aninditaa-ch commented
trigger ut8

2024-01-11 13:27 UTC, Aninditaa-ch commented
trigger uts

2024-01-11 13:48 UTC, Aninditaa-ch commented
/rebase

2024-01-11 13:58 UTC, Aninditaa-ch commented
trigger uts

2024-01-12 04:41 UTC, sahilhindwani-harness approved these changes

2024-01-12 04:53 UTC, ankittiwari-harness approved these changes

2024-01-12 07:10 UTC, merged