feat: [CDS-87167]: support anonymous github provider in SCM
harness/harness-core pull request #57430
Opened 2024-01-10 11:10 UTC by vlica-harness

## Describe your changes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2024-01-10 11:19 UTC, vlica-harness commented
trigger smartchecks

2024-01-10 12:12 UTC, devkimittal commented
Looks alright to me, let's just make sure it's backward compatible with delegate. You can do following tests with e2e run of a connector test and pipeline execution. (both via delegate and platform)
1. Delegate with old binary but other services with your changes. (both via delegate and platform)
2. All services on older version and only scm with your changes.

2024-01-10 12:50 UTC, vlica-harness commented
trigger uts

2024-01-10 14:30 UTC, vlica-harness commented
> Looks alright to me, let's just make sure it's backward compatible with delegate. You can do following tests with e2e run of a connector test and pipeline execution. (both via delegate and platform)
> 
> 1. Delegate with old binary but other services with your changes. (both via delegate and platform)
> 2. All services on older version and only scm with your changes.

Have tested this, looks to be ok. @devkimittal

2024-01-11 08:54 UTC, adivishy1 approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57430)* status: 3 file(s) to review. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2024-01-11 09:27 UTC, raghavharness requested changes

2024-01-11 09:27 UTC, raghavharness commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +    return ((GithubHttpCredentialsDTO) githubConnector.getAuthentication().getCredentials())
We should check if the `githubConnector.getAuthentication().getCredentials()` is of type `GithubHttpCredentialsDTO` first otherwise it can lead to cast exception in case the authentication is of type ssh.

2024-01-11 09:27 UTC, raghavharness commented on product/ci/scm/gitclient/gitclient.go
> +		if isGithubAnonymous {
You can directly use `if p.GetGithub().GetIsAnonymous()`

2024-01-11 10:28 UTC, vlica-harness commented on 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
> +    return ((GithubHttpCredentialsDTO) githubConnector.getAuthentication().getCredentials())
added a check for Authentication and also for GithubHttpCredentialsDTO, thanks, done

2024-01-11 10:28 UTC, vlica-harness commented on product/ci/scm/gitclient/gitclient.go
> +		if isGithubAnonymous {
yeah, just left as it is for more readability

2024-01-11 10:28 UTC, vlica-harness commented
trigger uts

2024-01-11 10:30 UTC, adivishy1 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57430)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 



<!-- Sent from Reviewable.io -->

2024-01-11 10:57 UTC, raghavharness approved these changes

2024-01-11 11:03 UTC, mohitg0795 approved these changes

2024-01-11 11:05 UTC, vlica-harness commented
trigger review

2024-01-11 11:07 UTC, merged